### ISSUE TITLE
House of Twain giving incorrect rewards

### ISSUE THREAD

**Issue by kullf** [Wynncraft/Issues#1301]
After I beat the quest 'The House of Twain' I did not get the correct emerald reward, I instead got 14 emerald blocks. I do not know what I did to make this occur but I felt it should be reported just in case.

**Comment by AckroGaming** [comment]
You have been very unlucky to experience this, as some people get the full reward and some don't.
There is no way for the actual quest to give you more emeralds now, but Jumla/Crunkle could always try to prevent this from happening again!

**Comment by Jamdog** [comment]
This bug has actually been fixed now - instead of giving 2 stacks of EB, anyone doing the quest after the 1.13 update should find that they get 2 LE instead.

As @AckroGaming said though, kullf, I'm afraid you won't be able to get back the lost EB...
