### ISSUE TITLE
[Group] Some items with special characters are not identifiable + relic daggers

### ISSUE THREAD

**Issue by MrBattleHammer** [Wynncraft/Issues#1312]
every item that contains a special letter cannot be ID'd. I have a legendary helmet (pélier) that cannot be ID'd and a spear (Ik-El-Vän) that cannot. other players have said that it is a glitch and i wish to report it so that you guys can fix it and make it fair. thanks

(pics)

![screen shot 2014-12-05 at 4 29 25 pm](https://cloud.githubusercontent.com/assets/10092464/5324064/eeaecf76-7c9b-11e4-991a-cf0cc1341348.png)

![screen shot 2014-12-05 at 4 29 12 pm](https://cloud.githubusercontent.com/assets/10092464/5324067/f61f74a4-7c9b-11e4-8a0e-86b2b6899a83.png)

**Comment by Trixter313** [comment]
Also, just for the sake of organization and to have them all in one place, Damassé can't be identified either.

**Comment by awemanrank100** [comment]
This may be bringing up an old topic, but Pelier still can't be identified, at least not for me.

**Comment by Quint93** [comment]
Relic Daggers still bugged. Just got my second pair today, still can't ID them.

**Comment by PingasGaming** [comment]
You can not ID the leaf chestplate. Why I dont know it just doesn't work for me.

**Comment by Penguinepowadude** [comment]
Tried today, still cannot ID relic daggers.

**Comment by Trixter313** [comment]
If https://github.com/Wynncraft/Issues/issues/2144 is true, the leaf chestplate also can't be identified.

**Comment by Sync-L** [comment]
Still can't identify the pélier, is it working for everyone else?

**Comment by DarkDemonDragon** [comment]
So are these items completely impossible to ID or do they just randomly sometimes work and sometimes don't? I have a Pelier and an Ajax (both have the exact same defense) and obviously I'd prefer to ID the Pelier but should I just get rid of it and ID my Ajax?

**Comment by TrashcanMan** [comment]
@DarkDemonDragon as far as I know they used to be broken, then they were supposedly fixed, so now some of them work and some of them don't. I'd advise you to try IDing the Peiler, but if that fails just go with the Ajax. Hold on to the Pelier though since you never know when it might be fixed.
