### ISSUE TITLE
./fixquests not working

### ISSUE THREAD

**Issue by IronWoodPick** [Wynncraft/Issues#1317]
I have recently reached level 68 to do the Temple of the Legends quest.  In the past I have deleted my quest items for more space.  Other people told me then that /fixquests in game will return any missing quest items.  However, when I issue the command, it says I'm not missing any items.

![2014-12-07_14 49 28](https://cloud.githubusercontent.com/assets/10108526/5332333/cc9ce2d4-7e20-11e4-9147-c7692baa413e.png)

![2014-12-07_14 49 41](https://cloud.githubusercontent.com/assets/10108526/5332351/5aacea9c-7e21-11e4-83ef-0a039b23b644.png)

**Comment by thecoolkogut4** [comment]
this happend to me, i waited 4 months then it worked and i got my items back... i dont know what changed but just give it some time

**Comment by Tama63** [comment]
Apparently Jumla fixed this a while back
