### ISSUE TITLE
Something wrong with the "wrath of the mummy" quest

### ISSUE THREAD

**Issue by LukeHill** [Wynncraft/Issues#1333]
I started the quest , "wrath of the mummy" and when i went to the bandit to talk to him he just said the same thing not letting me in and i couldn't pay him or do anything it was like the quest just flipped out. It said in my quest book to go talk to him but he talks like the dialog is suppose to be for people that haven't started the quest. I don't know what to do or if I can restart the quest. Any suggestions?

**Comment by Tama63** [comment]
Apparently this has been fixed internally
