### ISSUE TITLE
Improper Spelling Error Hunter Class

### ISSUE THREAD

**Issue by ghost** [Wynncraft/Issues#1338]
Hello, I just recently saw an issue that when someone logs in as a Hunter, it says, "...has logged into WC1 as an Hunter." Notice it the word "an" when it should be the term "a". Just something I saw that bothered me a tad, I hope this gets some consideration. Here's a photo for verification.
![2014-12-21_11 09 29](https://cloud.githubusercontent.com/assets/10261470/5518796/fa8ebdaa-8903-11e4-8d83-b07826aecba6.png)

**Comment by Trixter313** [comment]
Is this issue still open?
