### ISSUE TITLE
WynnExcavation Site A/ Vade not Working Properly

### ISSUE THREAD

**Issue by Ento0127** [Wynncraft/Issues#1415]
After I basically completed the "WynnExcavation Site A" quest, my quest book said, "Return and talk to Excavator Vade," but when I talked to him, he said, "Have you translated that text yet? I told you, take it to the tent up there and give it to Tesha!" Then Tesha said, "Take that to Vade, and don't read it!." I even tried multiple servers. I really don't know what to do to get my rewards I deserve and I need help.

**Comment by Ento0127** [comment]
This still isn't working.

**Comment by AckroGaming** [comment]
Ento, have you got the rewards and everything? In that case you shouldn't bother with the quest not properly end. This will be fixed, but until that, enjoy the rest of Wynncraft :)

**Comment by Ento0127** [comment]
Not even the rewards, but thanks.

**Comment by Trixter313** [comment]
Can someone experiencing this issue try /fixquests again? Aparently it just worked for someone so maybe they fixed it.

**Comment by Ento0127** [comment]
Lol wow I haven't played that game in like 6 months
On Aug 8, 2015 11:09 PM, "Nick Cipriani" <notifications@github.com> wrote:
>
> Can someone experiencing this issue try /fixquests again? Aparently it
just worked for someone so maybe they fixed it.

**Comment by iZoomPvP** [comment]
i cant click on Santa at the end of my quest, please help me resolve the issue

**Comment by Trixter313** [comment]
@iZoomPvP Please don't post of topic posts on other people's issues. I have already responded to your first post.

**Comment by Trixter313** [comment]
I see @AssassinGamer13 ... That's odd that it worked for one person but not others.

**Comment by Ento0127** [comment]
Still doesn't work. Here's the problem. My quest book says, "Return and
talk to Excavator Vade." I do so, and he says, "Have you translated that
text yet? I told you, go back to the tent up there and ask Teresa!" Glitch
that isn't patched for a year by now maybe?

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by gamex22** [comment]
This Problem happend  to me and i have tried everything you have suggested

**Comment by YunoFGasai** [comment]
@gamex22 please open a new issue, you need to collect a crystal shard from the tomb and give it to vade.
