### ISSUE TITLE
Member cannot join guild

### ISSUE THREAD

**Issue by EbobSilvr** [Wynncraft/Issues#1418]
So I had made a guild earlier tonight, and I wanted to invite my friends. So it worked for the first five people, I leveled up the guild a bit and then I tried to invite my brother. Despite the fact that he was getting messages telling him that he was invited when he attempted to join it did not work. It said he was not invited but the text saying he was invited was displayed just above. Screenshots enclosed
![screen shot 2014-12-30 at 1 35 38 am](https://cloud.githubusercontent.com/assets/10347141/5576670/26d4ec5e-8fc6-11e4-82ec-b249ecc370ec.png)
![screen shot 2014-12-30 at 1 35 37 am](https://cloud.githubusercontent.com/assets/10347141/5576671/28f4142e-8fc6-11e4-8d9b-1ea8d332f4a4.png)

**Comment by TheCelo** [comment]
I'm having the same Problem, @Tama63 when is it gonna be Fixed ? I really wanna invite People to my Guild ..

**Comment by AckroGaming** [comment]
This will be fixed as soon as possible, and as Tama stated, this is a bug regarding the prefixes (The "Cor" in this case) which makes the code not recodnise the guild you are trying to join.
