### ISSUE TITLE
Forum and Minecraft Account Linking Not Working

### ISSUE THREAD

**Issue by flyingsheep1433** [Wynncraft/Issues#1421]
I can not link my forum account to my minecraft account because when ingame I use the /forum (my username) command and it says "We can't authorize this account! Try again later..." What does this mean and what can I do to link these accounts, and on my forum account it says they are linked but they aren't because I'm a VIP+ and my forum account isn't that tells me I have been lied to... ;-; I need to /forum command to work.

**Comment by AckroGaming** [comment]
Oh, I know that the VIP+ tag on the forums is under fixing ATM. I do not know, but since it does not recognise you as only a VIP, it can't say anything yet.
