### ISSUE TITLE
Unable to proceed in  the tower of ascension

### ISSUE THREAD

**Issue by Epicsg** [Wynncraft/Issues#1425]
I'm a normal player on wynncraft and i decided to take on the tower of ascension, i was on the first place floor 8 when the token collector just stopped cloceting myy tokens, even when i had 10 of them in my hand he say "I need 10 tokens as proof...." please help i have lost many soul points doing this and lots of time getting back to the tower of ascension

Proof: https://www.youtube.com/watch?v=3RYZsaHFfCM&list=UUH1pelfSo1sSB6ko8YPvSOg

Yours faithfully
- Epicsg

**Comment by Roflstompzor** [comment]
I, too have this problem. I'm now sitting here with over 3 stacks of tokens.

**Comment by AckroGaming** [comment]
I just heard that basically everybody is having this issue currently. The shards have a diffrent ID from what the Level Master accepts. This will be fixed ASAP, or as soon as possible ;)

**Comment by CheezyGoodness** [comment]
Make sure you're using tokens for the right floor.

**Comment by CheezyGoodness** [comment]
Ignore that
