### ISSUE TITLE
WynnExcavation Site B Lykron (Quest starter) says NOTHING

### ISSUE THREAD

**Issue by rhbvkleef** [Wynncraft/Issues#1429]
When trying to talk to Lykron, he only sends empty lines. I am unable to start the quest.

**Comment by rhbvkleef** [comment]
Now the quest status is started, but the book still says to talk with Lykron, He doesn't say anything and the quest status is not updated.

**Comment by SammyB957** [comment]
Agreed I have the same problem

**Comment by rhbvkleef** [comment]
![2015-01-13_20 10 50](https://cloud.githubusercontent.com/assets/1645352/5727063/8d3799ba-9b60-11e4-8799-a55ac1773c4c.png)
here's a screenshot, just for the record.
Look at the big empty chat log block.
