### ISSUE TITLE
Quest Bugs

### ISSUE THREAD

**Issue by darkc0le** [Wynncraft/Issues#1430]
I Logged on to Wynncraft and saw that some awesome new quests were implemented so I started them but there are three I cant finish.
The first quest that was bugged was Frost Bitten, I cant collect lava from the springs to progress father in the quest.

The second quest that was bugged is called Wynncraft Excavation Site B, when I talk to Excavator Lykron a blank text appears in my chat, and when I look at the quest in the quest book it says talk to Excavator Lykron and says I already started the quest.

The third quest is called The Relic Shrines, and it doesn't show up in my quest book.

**Comment by darkc0le** [comment]
nvm i finished the Frost Bitten quest, i still need help with the other 3 tho

**Comment by vorck** [comment]
i have the same promblem on Wynncraft Excavation Site B .... help
