### ISSUE TITLE
Tower of ascension bug floor 1 lvl 8 

### ISSUE THREAD

**Issue by fluidanims1** [Wynncraft/Issues#1433]
![2015-01-01_16 37 30](https://cloud.githubusercontent.com/assets/10364994/5592574/62a93f26-91d5-11e4-8381-1670afa4957c.png)
if u have 10 shards u still can not pass, he stil says that u can pass and that u need 10 tokens

**Comment by Roflstompzor** [comment]
Have you yet been able to resolve this for yourself? I'm having the same problem and would like to know if there is a quick fix, instead of just wasting my time trying.

**Comment by Tama63** [comment]
dupl
