### ISSUE TITLE
Stuck in walls

### ISSUE THREAD

**Issue by XXWhiteDragonXX** [Wynncraft/Issues#1434]
Me XXWhite_DragonXX and my friend XXLapis_DragonXX are stuck in walls beneath blocks, ive worked hard on this server even though im only level 36, anyways i used a zombie key and got stuck and therefor lost it i can log in and show you where if need be please respond with good news
-XXWhite_DragonXX

**Comment by Trixter313** [comment]
All you need to do is type /kill into chat and you will respawn in the nearest visited town, with 2 less soul points so make sure you have 3+.
