### ISSUE TITLE
WynnExcavation Site B: Quest Start Bug

### ISSUE THREAD

**Issue by Roflstompzor** [Wynncraft/Issues#1435]
Upon entering the excavation cave and speaking with Excavator Lykron, I am greeted with only blank lines, as opposed to the text which is supposed to appear (gotten via the wiki). I've looked around and seen that some people have absolutely no problems completing the quests, while others have the same problem as me. I'd like to know why it is that this happens, and how I can fix it. Thank you.

**Comment by epicman739** [comment]
Known issue, should be fixed soon.
