### ISSUE TITLE
WrynnExcavation Site B Starter NPC Bug

### ISSUE THREAD

**Issue by NieLegalny81** [Wynncraft/Issues#1438]
Hello.
I wanna do quest WrynnExcavation Site B but i can't talk with Starter NPC (Excavator Lykron).
In screenshots you can see free space on chat. This free space i've got when i try talk with this npc.
![2015-01-01_19 37 07](https://cloud.githubusercontent.com/assets/10363843/5592995/274c5d0a-91ee-11e4-97a5-d3d3fa3afd90.png)
![2015-01-01_19 36 59](https://cloud.githubusercontent.com/assets/10363843/5592991/061676f2-91ee-11e4-9023-557105fe0dab.png)
That's all what i found.
Have a nice day. /NieLegalny81

**Comment by epicman739** [comment]
This one's been affecting quite a few people recently, it should be fixed soon.
