### ISSUE TITLE
Entrance to Tomb of Excavation Site A Not Working

### ISSUE THREAD

**Issue by CheezyGoodness** [Wynncraft/Issues#1442]
I can get past Vale just fine, but after locating and giving a "tribute" to the wood that is different, the area around the entrance will teleport me back a few blocks. This happens every item, every server.

**Comment by CheezyGoodness** [comment]
Well, I managed to get in, but it was after a good 15 minutes of parkouring into the hole.

**Comment by epicman739** [comment]
This is a known issue, and it should be fixed "soon".

**Comment by AckroGaming** [comment]
If you encounter this bug once again, you only need to switch server. There is some kind of forcefield that makes you unable of getting close to the drop.
