### ISSUE TITLE
Wynn Excavation Site A - If no room in inv. results in no item.

### ISSUE THREAD

**Issue by Turtlemuffin321** [Wynncraft/Issues#1443]
I finished the quest, removed things from my inventory, then accidentally picked it up. Did not give me the items, and it reset the quest. But it won't let me re-do the quest. He orders me to go translate the tablet, but the quest book says to talk to the quest giver.

I assume the Yellow Crystals are for a quest later on.

Thank you.

**Comment by epicman739** [comment]
Try /fixquests, it should return your items. However, the command may not work, as it is still in development.

**Comment by Turtlemuffin321** [comment]
Thank you.
 

     On Friday, January 2, 2015 2:12 PM, epicman739 <notifications@github.com> wrote:
   

 Try /fixquests, it should return your items. However, the command may not work, as it is still in development.—
