### ISSUE TITLE
Water Mini-Dungeon Glitch

### ISSUE THREAD

**Issue by TheFortyCave** [Wynncraft/Issues#1445]
In the puzzel part of the water mini-dungeon when releasing the water in the plinko puzzel, it does not work. The water, for some reason will not flow. Here is proof. https://www.youtube.com/watch?v=RLQElJ-WZ8I

**Comment by AckroGaming** [comment]
I am not sure as I have yet to complete that dungeon. The water flows behind the walls maybe, so try and do it anyway. Even if it seems weird, try it ;)

**Comment by TheFortyCave** [comment]
No even when you press the button the water wont flow
