### ISSUE TITLE
Disapearing Items/Stuck on past Selchar

### ISSUE THREAD

**Issue by bobbysnub** [Wynncraft/Issues#1446]
I was trying to complete the Christmas quest when I logged out to do homework. I returned and it was lagging so I reloged. upon reloging I was greeted by coarse dirt covering my entire screen and seeing the space in my hotbar where my bow normally is, empty. At first I thought it was the invisible item glitch. So I tried to fix it by opening my inventory and clicking on the box (which is what I do to make the item reappear) The item did not reappear. I reloged and nothing changed. I am now stuck on past Selchar for I am unarmed and unable to defeat the boss.

**Comment by AckroGaming** [comment]
Pictures please?

**Comment by bobbysnub** [comment]
I have no pictures of the glitch in action so here is the aftermath. 
![2015-01-05_15 49 29](https://cloud.githubusercontent.com/assets/10377498/5622212/7f23a0fc-94f4-11e4-9e09-cc8ce4dd72ca.png)   

![2015-01-05_15 56 22](https://cloud.githubusercontent.com/assets/10377498/5622217/aa743fbe-94f4-11e4-9c04-bd827632bc9c.png)

Just Showing that the shovel in my inventory isn't for my class

![2015-01-05_15 49 57](https://cloud.githubusercontent.com/assets/10377498/5622221/bee4a36c-94f4-11e4-85fe-57707c9d9dfc.png)

Again. I am not showing any picture or videos of it in action because I was not expecting this to happen.
