### ISSUE TITLE
Frost Bitten quest Item disappearing from inventory

### ISSUE THREAD

**Issue by ps454** [Wynncraft/Issues#1447]
When I was doing the quest I discovered that the explosive I was supposed to give to the excavator disappeared from my inventory. I've checked my bank and other classes, but the quest item is not there. When I did /fixquests it said that I was not missing any quest items.

**Comment by AckroGaming** [comment]
Can you tell us exactly how and when did this explosive disappear? Did it disappear when you should have gotten it, or did it disappear when you tried to give it to the Excavator.
About the /fixquests issue, that command does only react to the quest rewards, not mid quest items. The command does not work anyway, so there is nothing to it yet.

**Comment by Tama63** [comment]
dupl
