### ISSUE TITLE
Excavator Lykron NPC Not Talking

### ISSUE THREAD

**Issue by TheRedAnt** [Wynncraft/Issues#1448]
hey there, TheRedAnt here, and I was recently playing wynn the other day and I came across this bug today
Heres a screenshot
![2015-01-02_21 29 53](https://cloud.githubusercontent.com/assets/10377758/5601478/bf60290e-92c6-11e4-9961-70dc3bcb997f.png)

**Comment by Trixter313** [comment]
Have you tried clicking on him with an empty hand? Or have you tried relogging in?

**Comment by AckroGaming** [comment]
Can you tell us at what part of the quest you are? If you are at the start, then this clearly is a bug. If you are mid ways, then he is not supposed to speak, yet.

**Comment by Tama63** [comment]
dupl
