### ISSUE TITLE
I can kill Sayleros' Brother during the Grave Digger quest without bringing 24 Rotten Flesh.

### ISSUE THREAD

**Issue by HoldSpaceShift** [Wynncraft/Issues#1450]
I got into Stage 4 of the quest. I realized that I can enter the crypt without bringing 24 Rotten Flesh to The Priest. Then I killed Sayleros' Brother. I got the dusty will, and go to get 24 Rotten Flesh.
I got into Stage 5. The Priest told me to kill Sayleros' Brother and get the dusty will. I tried to give the will that I had but The Priest didn't receive it. So I kill Sayleros' Brother to get the dusty will again and give it to The Priest, even I restart my Minecraft, click The Priest with a bare hand, it didn't work.

This is what happen when I give the dusty will to The Priest.
![2015-01-03_13 57 29](https://cloud.githubusercontent.com/assets/10378318/5601735/9404b0b0-9350-11e4-935d-8e5e103965cf.png)

**Comment by AckroGaming** [comment]
I think that you should go to the church and give the 24 Rotten Flesh to the priest. That is where your quest book updates (Or atleast the code recognises that you are there, and sends a motion to The Priest to accept the Dusty Will).
Do that, and if that does not work, come back and report it ;)

**Comment by Tama63** [comment]
take the will to Detlas
