### ISSUE TITLE
bush and charge issues

### ISSUE THREAD

**Issue by hwathe** [Wynncraft/Issues#1451]
i noticed that when i used charge the enemies that i passes at the zstart of the charge dont take mach damage as the enemies that i passes later
also i notice that bush sametime make dirt block disappeared-
<a href="http://jpg.co.il/view/54a7b2612ed26.png/"><img src="http://srv2.jpg.co.il/7/54a7b2612ed26.png" alt="2015-01-03_11.06.01" /></a>
<a href="http://jpg.co.il/view/54a7b26139adf.png/"><img src="http://srv1.jpg.co.il/8/54a7b26139adf.png" alt="2015-01-03_11.08.54" /></a>
<a href="http://jpg.co.il/view/54a7b26124fed.png/"><img src="http://srv1.jpg.co.il/9/54a7b26124fed.png" alt="2015-01-03_11.05.38" /></a>
<a href="http://jpg.co.il/view/54a7b26131b90.png/"><img src="http://srv1.jpg.co.il/6/54a7b26131b90.png" alt="2015-01-03_11.08.03" /></a>

**Comment by AckroGaming** [comment]
It is supposed to remove dirt blocks for a small amount of time. Those blocks will come back, do not worry ;)
Also, as I haven't seen the source code, I can not tell if the damage issue is intentional or not. 
Sorry for that!

**Comment by hwathe** [comment]
the blocks dont retern until i right click on them or unlode the chunk
also if thay arnt there when i standing on tham or near them i start to glitch
