### ISSUE TITLE
8 Le Disappeared...

### ISSUE THREAD

**Issue by nathannck** [Wynncraft/Issues#1455]
I just lost my 8 le and i don't know how its gone! I was on Server 9 on Saturday, January Third, 16:29 or 4:29PM ( I live in The Netherlands). The Server was restarting and i think the error occurred during the counting from 5 to 1. Can i please get it back? And could one of the admins/moderators fix the bug or error? Thank You! :-(

**Comment by Trixter313** [comment]
Wynncraft has a strict no refund policy so I doubt you will be able to get the LE back. It could have been something you did like accidentally dropped it etc. and I doubt it was a server side issue. Go farm and enjoy Wynn even longer. :)

**Comment by nathannck** [comment]
Thank You Trixter313! I had an idea of quitting minecraft... But your comment changed my idea. Thanks :-D
