### ISSUE TITLE
Emeralds not working

### ISSUE THREAD

**Issue by Cuffnigga** [Wynncraft/Issues#1456]
I am new to wynncraft and I've been playing wynncraft for 2 days now but I cant interact with my emeralds at all. I drop them on the ground and even when I put them back up I cant do anything with them. Could anyone help me with this problem? I've been enjoying playing wynncraft and would appreciate it if someone could help me out.

**Comment by AckroGaming** [comment]
Pictures?
Can you not drag them around, or what is it? If they are "old emeralds" just exchange them into new ones by going to the nearest bank.

**Comment by Cuffnigga** [comment]
I cannot use them at any merchant at all. I can drag the emeralds out of my inventory but thats all I can do.
