### ISSUE TITLE
Map glitching in and out

### ISSUE THREAD

**Issue by Sorakin** [Wynncraft/Issues#1457]
I had switched my render distance down two due to a lag spike i had but when i turned it back parts of the map were disappearing and re appearing with other parts of the map in it so i couldn't see the blocks, it also stopped me from doing some dungeons due to not being able to see parkour pr puzzle parts.

**Comment by Trixter313** [comment]
Thats most likely an issue on the computer's side and not server side. Don't know how to fix it though.

**Comment by AckroGaming** [comment]
That is a bug from Minecraft itself. When you go into "Video Settings", turn on VBOs. Otherwise it will be very glitchy at around render distance 16.
