### ISSUE TITLE
Keibon Dialogue after Retrieving Lava Invisible

### ISSUE THREAD

**Issue by CheezyGoodness** [Wynncraft/Issues#1458]
After retrieving the 8 lava for the quest, Keibon's speech doesn't appear. The text box still appears, but there's nothing in it.

**Comment by flyingsheep1433** [comment]
You talk to Alein not Keibon after you have all the lava.

**Comment by Jamdog** [comment]
As @flyingsheep1433 said, when you have collected the 8 lava, you need to take the lava, and the bucket back to Alein in the cave.  Keibon simply enchanted the bucket so it would hold the lava.  It does tell you where you need to go in your quest book.

Having said that, @CheezyGoodness - you are quite right.  When you speak to Keibon after collecting the lava, he _should_ say:
[1/1] Keibon: Be careful with the bucket when you go to Alein! The lava can easily burn you!

He doesn't say anything, and yes, this is a bug...

**Comment by anders1122** [comment]
I had the same problem, got me frustrated for half an hour, came here and realized how unfocused I am. Hopefully this gets fixed.
