### ISSUE TITLE
Tower of Ascension bug

### ISSUE THREAD

**Issue by jeffrypig23** [Wynncraft/Issues#1459]
I started the quest called Tower of Ascension a few weeks after the update. Most of the levels were behaving like they should, untill I got to level 8 on floor 1. A few of the mobs were spawning in the wall, but I just thought that this was a small bug, and proceded to collect the 10 shardes. After I had gotten all 10, I proceded to the villager, and clicked on him. He said that I needed 10 shards to procede to the next level. I had all 10, but I also had many other extra shards from the previous levels. I threw the old shards out of my inventory, and kept the 10 from this level. The villager said that I needes 10 shards. I thought that this was strange, and tried collecting more. 169 shards later the villager would still not take the shards. I ended the quest by doing /kill .

**Comment by AckroGaming** [comment]
#1425 - Check out that one. These are the same.
Always be on the look out for similar posts to the ones you'd like to post!
