### ISSUE TITLE
Christmas chaos Past selchar teleportion not working properly

### ISSUE THREAD

**Issue by TheDpowers** [Wynncraft/Issues#1460]
So I am currently working on the christmas chaos quest while its still out and I just went through the chimney teleport, but it keeps on putting me in the ground somewhere. I have killed myself 3 times using /kill but it keeps on putting me in the ground somewhere. The coordinates are x:-6845 y:60 z: -11463

**Comment by TheDpowers** [comment]
I've killed myself again and it worked so I dont know what happened.

**Comment by TheDpowers** [comment]
great now im stuck somehwere else...

**Comment by Trixter313** [comment]
Have you tried jumping? Or using a spell? (Charge for warrior or Escape for Archer)
It teleported me too low also but jumping always fixed it for me.

**Comment by TheDpowers** [comment]
I've tried both and neither worked. But I did manage to finish the quest

**Comment by vogelmet** [comment]
same happend to me. just do /kill (cost 2 sooulpoints!) when you will be teleport back to selchar. you must run the whle way again but you only must go to old tom in destroied selcar and so you don´t must kill santa again
