### ISSUE TITLE
You cannot identify Ik-El-Vän

### ISSUE THREAD

**Issue by kakarot798** [Wynncraft/Issues#1461]
I have a rare item named Ik-El-Vän , min lvl: 66, dam: 161-201, but I cannot identify it. Please fix this. ~Kakarot

**Comment by Jamdog** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

**Comment by AckroGaming** [comment]
This is a known issue, although we would be happy if you could check the bug tracker for a similar post like the one you'd like to post.
Thank you anyway!
