### ISSUE TITLE
Quests Not Resgistering

### ISSUE THREAD

**Issue by coolandsmoove** [Wynncraft/Issues#1463]
One of the quests I started did not start properly, Quest WynnExcavation Site B glitched out for me, whenever I try to talk to the NPC that starts the quest it gives me a single blank line instead of any text. When I open up my Quest Book the status of the quest is started but it still tells me to talk to the starting NPC. I'm not sure what the problem is, but I was wondering if you would be able to fix this.
![2015-01-04_14 08 55](https://cloud.githubusercontent.com/assets/10392476/5607299/6b0bbe1c-941b-11e4-8b60-71b50ef5e585.png)
![2015-01-04_14 08 57](https://cloud.githubusercontent.com/assets/10392476/5607310/af0124a4-941b-11e4-95a6-80d1be6b4dce.png)

![2015-01-04_14 08 42](https://cloud.githubusercontent.com/assets/10392476/5607293/46d850dc-941b-11e4-9303-c4482452ccda.png)

**Comment by ColeLole** [comment]
Same problem
