### ISSUE TITLE
Quest Problems

### ISSUE THREAD

**Issue by ThatChudley** [Wynncraft/Issues#1468]
I'm sure everyone's aware of this, but I know no information about it,

The quest Troubled Tribesmen has not been added to the game, nor has Relic Shrines, also recently Wynn Excavation Site B has been blocked from starting, can anyone explain why these things have/haven't happened? Thanks :)

**Comment by AckroGaming** [comment]
The first two quests did not manage to be finished in time for the 1.13 release, but the Site B quest should work just fine.
