### ISSUE TITLE
Can't start Wynnexcavation Site B quest

### ISSUE THREAD

**Issue by Gaeth52h** [Wynncraft/Issues#1469]
Hi, 
Yesterday evening i wanted to start the WynnExcavation Site B quest but when i right-click the npc a "blank" line appear in my chat, and i can't start the quest.
One of my friend have been able to do this quest few days ago, maybe one week in don't really know :/ but not me, and i met another player (i don't remember his name) who have the same problem as me.
I hope i good explained and sorry if my english is bad, i'm french and i learned english at school.
Bye, Gaeth
![2015-01-06_17 04 02](https://cloud.githubusercontent.com/assets/10424585/5634543/e6bd5c70-95e0-11e4-9917-22cd7e5c8a9f.png)

**Comment by Tama63** [comment]
dupl
