### ISSUE TITLE
Can't Connect to Any Worlds

### ISSUE THREAD

**Issue by Fyloket** [Wynncraft/Issues#1470]
Hello Staff/Devs.
  This is my first time on Wynncraft. I have been referred to this server by a friend who claims it's one of the best he's played. However, I first tried joining the game on World 14. I chose my class and waited, but I got put back in spawn, saying that there was an error. I tried this on several other worlds and other lobbies, but found the same result. I even tried using other classes to see if it changed anything, but that did not work either.

  I am using Minecraft 1.8.1 with Optifine, but I have also tried unmodded 1.8.1 as well as 1.8, none of those have worked. My friend, however, is using 1.8.1 unmodded, and has no trouble joining. (If this affects anything, I am using the Faithful 32x32 resource pack.)

  I am hearing great news about this server, and from the looks of it, it looks incredible. Please help, I am feeling like I'm missing out.

![2015-01-06_15 52 12](https://cloud.githubusercontent.com/assets/10426637/5637050/51b97136-95bd-11e4-9e96-77c99b78aea5.png)
This is the screen after I select a class. It will stay like this for a few seconds before putting me back in the lobby.

![2015-01-06_15 52 23](https://cloud.githubusercontent.com/assets/10426637/5637068/710c828a-95bd-11e4-8f94-903b041198ac.png)
This is the screen when I am kicked from the world.

**Comment by epicman739** [comment]
I think there might be some sort of Internet-related problem. Try again in a few hours or so, perhaps it will work then.

**Comment by AckroGaming** [comment]
In this case, there is pretty much nothing about version or Internet that is affecting it.
It may be that the server is heavely loaded, or that the Wynncraft servers in general are not working properly ATM. Try joining in a couple of hours!

**Comment by Fyloket** [comment]
This has happened multiple times over a period of several days. On other servers I have no internet issues.
As for servers being "heavily loaded", I choose the least populated worlds to join and it fails every time.
