### ISSUE TITLE
WynnExcavation Site B: Unable to communicate with Excavator Lykron

### ISSUE THREAD

**Issue by Alexicon1** [Wynncraft/Issues#1474]
When I recently went on a quest-fest, I went to the starting point for the nearest quest, which was WynnExcavation Site B. When I got there, I right-clicked Excavator Lykron to begin dialogue, but all I got was empty lines. I continuously clicked, hoping it would start quest, it did, but still told me to talk Lykron at coords. I went down the cave and right-clicked Flendar, the next NPC in the quest. But he gave me the message 1/1 Get out of here. Which means I need to talk to Lykron to proceed, but he is saying nothing. I tried this last night it didnt work, so I relogged, still didn't work. Came on this morning still isn't working. I have ruled out lagging, because 3 other players have come and not received dialogue. I have asked them and they said no they hadn't received anything and just left. This is a bug, and I hope it gets fixed.

Steps to reproduce
1. Go to WynnExcavation Site B
2. Right-click Excavator Lykron
3. Scream and shout in frustration

Thanks for everything WynnTeam, you guys are awesome.
Alexicon1
![Excavator Lykron Static
](https://cloud.githubusercontent.com/assets/8433578/5667902/46db211e-97d0-11e4-820b-ef5b1c43e0da.png)
![Quest Book First Page](https://cloud.githubusercontent.com/assets/8433578/5667903/46e0d898-97d0-11e4-9b99-1514f19ceb57.png)
![Quest Book WynnExcavation Site B Page](https://cloud.githubusercontent.com/assets/8433578/5667904/46e17f3c-97d0-11e4-9a54-07dc2040304b.png)

**Comment by Tama63** [comment]
duplicate, but thanks for the report
