### ISSUE TITLE
i just lost 25 le

### ISSUE THREAD

**Issue by mathias-e-k** [Wynncraft/Issues#1475]
so i was sellingmy adamantite and i ahad 15 le in my inventory and i got 10 and then i wanted to contribute 6 to my guild and then i presed accept donation and it did not work and 5 seconds later all my le was gone please fix this and give back my 25 le my minecraft username is mathias_e_k

**Comment by epicman739** [comment]
So you pressed "accept donation" once and it took all your 25 LE?
