### ISSUE TITLE
Glitched under map at past selchar

### ISSUE THREAD

**Issue by frisout** [Wynncraft/Issues#1477]
While I was doing the christmas quest I went to past selchar, but once I entered ''Selchars Hearth'' this happened:

![2015-01-09_13 12 09](https://cloud.githubusercontent.com/assets/9353139/5682855/8299b5d2-9823-11e4-8344-c252b1920e4c.png)
![2015-01-09_13 12 19](https://cloud.githubusercontent.com/assets/9353139/5682856/829df9f8-9823-11e4-85a2-e388d3bc71e0.png)

How do I get back up and continue the christmas quest?
My ingame name is frisout

**Comment by vogelmet** [comment]
do /kill this cost 2 soulpoints and teleport you back to your last visited city. you must run the whole way of the quest again ...

**Comment by frisout** [comment]
It worked! thank you
