### ISSUE TITLE
My Quests Were Reset

### ISSUE THREAD

**Issue by NeoxVip** [Wynncraft/Issues#1478]
Its quite a long time since i joined wynn but i finally did, when when i do... Basically, almost ALL of the quests were reset. I'm level 40 and i can't even step into Ragni because it says i didnt talk to the king. Please help, i just want to play wynn again but without my quests i can't even acess Almuj's bank.

Here is some prints: http://prntscr.com/5qes7i

**Comment by flyingsheep1433** [comment]
Use /fixstart
