### ISSUE TITLE
Guild Broken Buffer

### ISSUE THREAD

**Issue by Felixfex** [Wynncraft/Issues#1479]
I cannot attack a territory because the buffer "This territory was just in a battle! please wait another ... seconds before attacking again" keep resetting when it reaches 130 seconds so i cannot attack D:
And the Territory map isn`t working it only shows the the guilds who captured the territory long before
I hope you will fix it D:

**Comment by AckroGaming** [comment]
This appears to be happening to everyone, so I guess we need to wait for a patch that covers this.

I think the latest patch bringed tons of new bugs, haha!

**Comment by hatunemiku01** [comment]
I'm having the same problem. If I knew about it, I wouldn't have made my own guild ;-;
