### ISSUE TITLE
Craftmas Glitch

### ISSUE THREAD

**Issue by stevemacie321556** [Wynncraft/Issues#1481]
Since christmas is almost over, i wanted to finish the Craftmas quest in Wynncraft.  In two places i had gotten stuck in a block. 1. When I was teleported to corrupt Selchar, which I was able to escape from. 2. when I was teleported out of corrupt Selchar, this one i am not able to escape from because I am stuck in a block that is surrounded.  I enjoyed the quest but am not able to finish it.  please help soon I would like to finish before you remove the quest.

Please help,
       Steve

**Comment by epicman739** [comment]
Do you have screenshots or coordinates?
