### ISSUE TITLE
I have 51 Stat points at level 27, when I should have 52.

### ISSUE THREAD

**Issue by Ramzicmain** [Wynncraft/Issues#1482]
Allocating points when your client lags from the server doesn't allow the server to register them, and my total stat point count dropped from 52 to 51. I have 0 unallocated points, btw, with 36 Str and 15 Dex. I put 1 in Agi, but it doesn't seem to work...?

**Comment by vogelmet** [comment]
maybe this is because you can´t write the number 1 under the book amout. drive with the mouse over the books it should say chance of 1 % to ... then you spend another point on this its say 2 % and so you have 2 books.

**Comment by Ramzicmain** [comment]
Yes, it works! Thanks!
