### ISSUE TITLE
This territory was just in a batlle! Please wait another X seconds before attacking,

### ISSUE THREAD

**Issue by ahmadrules** [Wynncraft/Issues#1483]
So, the error message in the title shows up when I try to attack territories. I wait the amount of seconds it tells me to wait, but it never reaches 0. It just increases a bit or decreases. It never goes under 100.
This is really annoying and is making it near impossible to get any territories.

**Comment by Felixfex** [comment]
Some Territorys are bugged like the silverfish dungeon one of the Mods or Admin guild should attack these territorys to fix the bug (btw all territorys around troms are unbugged because of that)
