### ISSUE TITLE
Multiple quest items

### ISSUE THREAD

**Issue by mrord1** [Wynncraft/Issues#1484]
Sometime ago, I managed to pick up an extra breathing helmet. I now have two. Is there a way to get rid of one of them?
![double bh](https://cloud.githubusercontent.com/assets/10474452/5691153/6492d838-98b0-11e4-8fca-9b90485543f5.PNG)

**Comment by Trixter313** [comment]
You probably did the underwater quest on 2 different classes, resulting in 2 helmets is all.

**Comment by Jamdog** [comment]
As Trixter313 said, the Breathing Helmet is gained during the *Underwater* quest, which is gained at Level 8.  You have 2 classes (Archer and Mage) that you may have completed the quest with.  The image above shows your Mage class, with 2 helmets, but your Archer class does not have a Breathing Helmet.

The Breathing Helmet is also required for the *Underice* quest, once you reach the snowy wastes of Nesaak.  You should hold onto it, but I recommend putting one of those helmet back on your Archer class (via your bank chest).

**Comment by mrord1** [comment]
Thanks. I kinda feel stupid.
