### ISSUE TITLE
Lost Soles Quest Issue

### ISSUE THREAD

**Issue by Nega9** [Wynncraft/Issues#1489]
I lost my Abyssal Galoshes, in when  gave the Boots and boot case to Ferndor everything started to lag then I got a "Timed Out" error and lost the Abysso Galoshes in the wonders of cyber space. Im really sad now because unless I get another class to Lvl 60 and do the quest all over again to get the boots I have no chance of completing the mission.

**Comment by epicman739** [comment]
/fixquests might give them back, though it's buggy and might not work.
