### ISSUE TITLE
Emerald Blocks Missing From Inventory

### ISSUE THREAD

**Issue by doctorwhovian86** [Wynncraft/Issues#1490]
I had over forty emerald blocks in my inventory when i logged off, when i logged back in they were all missing. The only emeralds in my inventory were the few i had not put in block form yet.

**Comment by AckroGaming** [comment]
My main guess would be some sort of rollback occured for you.
In other means, the server maybe retracted the last 20 minutes of your gameplay (possibly).

Strict no refund policy, and that is how the song goes.
It is a nice song, just sing along.
