### ISSUE TITLE
I am stuck in Past selchar after completing Craftmas Chaos Quest

### ISSUE THREAD

**Issue by arjunanuj999** [Wynncraft/Issues#1492]
Hey guys, So I finished the Craftmas Selchar quest, and got my reward, but then I randomly got teleported to past selchar. What Am I supposed to do? PLEASE HELP! I don't want to lose my Archer account!

**Comment by Trixter313** [comment]
Type /kill into chat. This will cost 2 soul points so make sure you have at least 3. You will respawn in the nearest visited town.
