### ISSUE TITLE
WynnExcavation Site B - Cannot be done

### ISSUE THREAD

**Issue by KenzieRiann** [Wynncraft/Issues#1495]
When you speak to the starting NPC, all you're given is a blank chat.  The quest did not start for me.
For my friend, he says the quest started when he finished Site B.

I went to complete another quest, and noticed when I opened the book that Site B had started.  But it still instructs me to talk to the starting NPC.

I'm not able to move forward with the quest.

Screenoshts:  http://imgur.com/a/YVznF

**Comment by vogelmet** [comment]
Known issue. dublication of #1429
