### ISSUE TITLE
Floating Mob Display (non-interactable)

### ISSUE THREAD

**Issue by Louis-D** [Wynncraft/Issues#1499]
I found this in Troms and other parts of the Wynncraft world. I don't know how
to reproduce it, I only find it...

![2015-01-13_14 47 30](https://cloud.githubusercontent.com/assets/6114858/5727372/d56d804e-9b62-11e4-95e8-40cb9a022e08.png)

**Comment by epicman739** [comment]
So there's a nametag with no mob? Did you try attacking the space where the mob should be?

**Comment by Louis-D** [comment]
Yes.

**Comment by Louis-D** [comment]
Thats why non-interactable...

**Comment by vogelmet** [comment]
something like this happend also to me
