### ISSUE TITLE
Hole In floor 

### ISSUE THREAD

**Issue by PortugaXD** [Wynncraft/Issues#1500]
Hello i find 1 hole in floor and im stuck inside him can you help me i gonna give the cordenates
![2015-01-13_19 50 32](https://cloud.githubusercontent.com/assets/10520672/5727802/a55f55da-9b5d-11e4-97dc-58e1af542df5.png)

**Comment by Louis-D** [comment]
Still need help?

**Comment by Trixter313** [comment]
Now that it's reported it should be fixed "soon" and to get yourself out simply type /kill into chat. This will take 2 souploints and you'll respawn in the nearest visited town.

**Comment by Louis-D** [comment]
@Trixter313 correct..
