### ISSUE TITLE
Teleport to Craftmas Cave in Past Traps me In Stone

### ISSUE THREAD

**Issue by beheemark** [Wynncraft/Issues#1502]
I am a level 30 mage on Wynncraft and was playing the craftmas quest, so I went into the portal under Selchar in past Selchar. Upon teleporting, I glitched through the world for a moment, and then appeared trapped in stone. I had some teleport scrolls on me, yet was unable to use them after many tries. I can also not be hit by anything while in the stone, so either it was just a personal glitch or a glitch for others too, I'm not sure. either way, it would help to be teleported out or have the floor lowered. Thank You, beheemark

**Comment by Trixter313** [comment]
To get out type /kill into chat. This will take 2 soul points and you will respawn in the nearest visited town.

**Comment by beheemark** [comment]
thank you! I was kind of worried that my mage would become impossible to use...
