### ISSUE TITLE
[Quest] Bulbo not clickable

### ISSUE THREAD

**Issue by Louis-D** [Wynncraft/Issues#1505]
I tried to do the lord of the clock quest... Frudo
 only sends plain lines.
The forum says to use 1.7.10 but still it won't work..

How to reproduce: Rightlcick Frudo

![2015-01-14_14 26 41](https://cloud.githubusercontent.com/assets/6114858/5739465/1a1b254c-9bfa-11e4-898d-9bbfe83478c1.png)

**Comment by Trixter313** [comment]
Try standing right in him and while looking straight down and spam clicking him while kinda moving in small circles with the wasd keys.. This usually works with the baby villagers.

**Comment by Louis-D** [comment]
@Trixter313 Wont work D:
