### ISSUE TITLE
banned

### ISSUE THREAD

**Issue by cap705** [Wynncraft/Issues#1506]
Hey I'm new and i can't log in cause it says I'm banned from fly hack I see this as a Bug cause I just got the server to see and it says that I'm banned please help!! my littlebrother has played on my account and i think that is the reason cause i'm banned he have been told me before that I got banned from a server and I was just like yeah what ever and i think this was the server he told me about!!

**Comment by Louis-D** [comment]
Well anyone can say that. Please appeal here: https://forums.wynncraft.com/forums/ban-appeals/
