### ISSUE TITLE
Apostrophe becomes Caret in "Level Up!" log

### ISSUE THREAD

**Issue by lepoaro** [Wynncraft/Issues#1507]
The apostrophes (') becomes caret (^) in the sort of changelog / résumé you get when you level up.

![2015-01-14_17 41 50](https://cloud.githubusercontent.com/assets/8739636/5744222/06fbecb0-9c1f-11e4-8578-91d20b33e952.png)
![2015-01-14_18 10 14](https://cloud.githubusercontent.com/assets/8739636/5744223/0988d970-9c1f-11e4-86bf-8852c7f0404a.png)

Look at the quests names, Maltic's Well becomes Maltic^s Well, and ''Hallowynn 2014'' becomes ^^Hallowynn 2014^^

**Comment by Louis-D** [comment]
This could be because u might use a texturepack...
