### ISSUE TITLE
"Dam." or "Def." in items tooltips not syntaxed properly

### ISSUE THREAD

**Issue by lepoaro** [Wynncraft/Issues#1509]
The "Dam." (for weapons) or "Def." (for armor) lines are **for some items** not syntaxed properly (they're not in italic)

![2015-01-14_18 58 46](https://cloud.githubusercontent.com/assets/8739636/5744621/a2efda48-9c22-11e4-8eba-e60c355cc063.png)
![2015-01-14_19 24 47](https://cloud.githubusercontent.com/assets/8739636/5744682/3260926c-9c23-11e4-95f6-c24d224cf24c.png)
![2015-01-14_19 24 49](https://cloud.githubusercontent.com/assets/8739636/5744688/352826c2-9c23-11e4-8e4f-05a62b510504.png)
*As you can see above, the "Def." or "Dam." lines are not in italic*

![2015-01-14_18 58 48](https://cloud.githubusercontent.com/assets/8739636/5744623/a4dbf2a6-9c22-11e4-96de-a5e28e2f3d59.png)
*Here, it's normally syntaxed*

I've noticed that for more items, but didn't have them in my possession when I felt the need to report that bug.

*PS : Unlike the [tooltip width bug](https://github.com/Wynncraft/Issues/issues/1508) it's not fixed by relogging*

**Comment by hunter14** [comment]
it does this sometimes with everything like after u place an enchantment on the item or if its a weapon after i use a spell it will do that
