### ISSUE TITLE
wont let me attack another guilds territory

### ISSUE THREAD

**Issue by hunter14** [Wynncraft/Issues#1510]
hey guys for some reason it wont let me attack another persons territory because of the glitched countdown thing
![screen shot 2015-01-13 at 8 41 25 pm](https://cloud.githubusercontent.com/assets/10526584/5747270/48c8a700-9be3-11e4-95ad-1445a85fb9fa.png)

**Comment by epicman739** [comment]
This is a known issue, just wait until it's fixed.
