### ISSUE TITLE
Trainers in Temple of Legends bugged D: 

### ISSUE THREAD

**Issue by Th3GoodGam3r** [Wynncraft/Issues#1511]
Casually grinding in tol , then this happens .. I am aware it happens to other players , not just me , they act as live mobs , Just do no damage , only nudge you around a little , very Annoying when they get into your face D: Hope is fixed. Pretty sure the picture shows you all I can say, Edit: Cannot be killed.
![2015-01-15_20 41 06](https://cloud.githubusercontent.com/assets/10552677/5766253/e7959a04-9cf7-11e4-915d-8a6c8d0adc5a.png)

**Comment by vogelmet** [comment]
same happend to me:
![2014-10-28_18 44 57](https://cloud.githubusercontent.com/assets/6832858/5781256/811003e0-9db1-11e4-996a-f91b3014d1c4.png)

**Comment by flyingsheep1433** [comment]
Try hitting them again as if they are still alive..
