### ISSUE TITLE
Nevermind!

### ISSUE THREAD

**Issue by Flames99Fuse** [Wynncraft/Issues#1514]
After getting the eight lava for the frost bitten quest and talking to keibon, I get no text, just nothingness.

**Comment by Flames99Fuse** [comment]
Wait, disregard this

**Comment by hunter14** [comment]
is the frost bitten quest fixed now

**Comment by AckroGaming** [comment]
The quest is fully fixed as of some of the latest patches. Go and talk to Alein, and not Keibon for future reference ;)
