### ISSUE TITLE
Guilds Cannot Be raided

### ISSUE THREAD

**Issue by AnnoyingGuildBug** [Wynncraft/Issues#1515]
Cannot raid guilds due to a timer reset bug. Specific guilds (PoW, wTH, and WYA) have been unraidable for the last day and a half, it seems that whenever their timer from a raid protection gets down to 1:30 it resets and prevents any raids. Their levels will keep increasing and no counter-raids can be launched

**Comment by epicman739** [comment]
Known issue, should be fixed soon.

**Comment by hunter14** [comment]
does anyone know when it will be fixed
