### ISSUE TITLE
Escape spell not boosting me up?

### ISSUE THREAD

**Issue by anders1122** [Wynncraft/Issues#1516]
Using the escape spell doesn't "throw me" as it's supposed to, it's been happening for 3 days straight now, I thought giving it time would fix it, apparently not.

One more thing I've noticed, is that the exploding bottle that's supposed to appear when I use Escape, appears almost one block away from me instead.

**Comment by anders1122** [comment]
Anything?

**Comment by hunter14** [comment]
have you tried restarting your computer

**Comment by anders1122** [comment]
You can't be serious, I say it's been happening for 3 days (4 now) straight and you ask me that?
Yes, I have tried restarting my computer, more than 5 times now.

**Comment by anders1122** [comment]
Still happening, sadly.
