### ISSUE TITLE
I'm Stuck

### ISSUE THREAD

**Issue by Ultradragon364** [Wynncraft/Issues#1517]
Dear Wynncraft Admins,
 I seem to be stuck in a wall and I won't die due to a teleportation glitch and no matter what I do I cannot be unstuck unless I get teleported out by an Admin or Moderator (or someone of power). My coordinates at the moment are X: -370 Y: 21 Z: -1966. Please attempt to unstick me from the wall/floor. Please attend to my simple request as soon a possible.

Thanks, Ultradragon364

**Comment by Trixter313** [comment]
Type /kill in to chat. You will respawn in the nearest visited town and it will take 2 soulpoints so make sure you have 3+.
