### ISSUE TITLE
Horse Breeding Issues.

### ISSUE THREAD

**Issue by mastaplaya112** [Wynncraft/Issues#1520]
In the past two days I have purchased 8 horses from the horse merchant in the Ternaves. With two brown horses when you put them both into your crafting grid it should make one black. I've tried with all 8 browns which SHOULD give 4 blacks in return. They didn't make ANY blacks, only made the 2 browns, back into 1 brown. It has been a complete waste in Emeralds and I think it should be fixed and I should receive my 4 blacks. Thank you for your time and consideration.

- [VIP] Mastaplaya112

**Comment by P3BBL35** [comment]
This is not a bug. Every time you breed 2 brown horses, there is a chance that you will receive a better horse. The chances are: 50% to get the same tier horse back, 30% to get a lower tier horse, and 20% to get a better horse.
