### ISSUE TITLE
Wynncraft Online Player Info not Working

### ISSUE THREAD

**Issue by P3BBL35** [Wynncraft/Issues#1521]
When I try to look at my player info online, it returns with a "Page Not Found" page, but everyone else's player info page works. I don't know why. Can anyone help me? 
Here's a picture
![capture](https://cloud.githubusercontent.com/assets/9964841/5790699/dbaacd9e-9e6a-11e4-940f-cf0d2a56a363.PNG)

**Comment by AckroGaming** [comment]
This is happening to everyone, including me. 
I do not know why, but I can confirm that you are not alone.

**Comment by Tama63** [comment]
Fixed!
