### ISSUE TITLE
Old Emerald blocks > New ones

### ISSUE THREAD

**Issue by Jemmerl** [Wynncraft/Issues#1525]
I haven't been on Wynncraft for a while and I had 8 Emerald Blocks. Now, they are called Blocks of Emerald. I can't turn the old ones into the new ones- any way to change them?
![2015-01-18_07 54 46](https://cloud.githubusercontent.com/assets/10583456/5792459/5f508a04-9ee7-11e4-99be-5cdd0181a1e0.png)
![2015-01-18_07 54 44](https://cloud.githubusercontent.com/assets/10583456/5792460/6a1eb0dc-9ee7-11e4-9c32-12ae426eb278.png)

**Comment by lepoaro** [comment]
I had the same problem few months ago, but I could convert them into stacks of new emeralds and then to new blocks of emeralds thanks to the Emerald Merchant. Is that still possible ? (Put the Emerald Blocks into the slot of the Merchant's first trade)

**Comment by Jemmerl** [comment]
No it is not
:/

**Comment by Jemmerl** [comment]
Can any1 help?

**Comment by epicman739** [comment]
I think it should work in 1.7. In 1.8, villagers now check item lore, but in 1.7 they don't. You should probably do this fast before Wynncraft updates to 1.8 and renders old emeralds useless.

**Comment by Jemmerl** [comment]
wynncraft is already 1.8

**Comment by Trixter313** [comment]
Wynncraft is 1.7.10 but it's using protocol hacks to allow 1.7 and 1.8 clients.

**Comment by Jemmerl** [comment]
oooh!

**Comment by epicman739** [comment]
So can we still convert old EB to new ones?
Also, Wynncraft is hacking?

**Comment by Trixter313** [comment]
Yes, as long as you are using 1.7 you should be able to convert the old emeralds into the new ones.
Also, Hacking isn't always necessarily bad. One of the definitions of "Hack" on Merriam-Webster dictionary is, "a usually creative solution to a computer hardware or programming problem or limitation" so thats really all that they did, fixed an "issue" in a creative way ;)

**Comment by Jemmerl** [comment]
worked- if that failed, i was going to sell them to players who might want old relics
