### ISSUE TITLE
Missing Quest Item - Unable to continue with quest

### ISSUE THREAD

**Issue by samtheman43** [Wynncraft/Issues#1526]
Earlier this week I tried to start the quest "Lost Soles" But once I got to Fernanfor the quest NPC I realized he wanted the "Abysso Galoshes" which I recieved after completing the "Beneath the Depths" quest. But apon looking in my ender chest, I didn't have them. I'm positive I had them at one point after finishing the quest and now they've dissappeared. So now I'm unable to finish the "Lost Soles" Quest. Is there any way I can get them back so I can finish the quest? 

Please help,
samtheman43

**Comment by epicman739** [comment]
/fixquests should return it, but it's buggy and may not work properly.

**Comment by samtheman43** [comment]
thank you.
