### ISSUE TITLE
My Friend is stuck!

### ISSUE THREAD

**Issue by fandrus** [Wynncraft/Issues#1528]
Hello there! My friend seems to be in a... STICKY situation.... I'm so sorry. Anyways, she is stuck in some blocks (like if you were to suffocate in them) but doesn't die and can't use her teleportation scrolls to get herself out. We have tried to contact any staff, but we haven't seen any. If there is any way to get her out, please help! her IGN is kitikat13 Thanks! =)

**Comment by Trixter313** [comment]
Tell your friend to type /kill into chat. They will respawn in the nearest visited town and it will take 2 soul points so make sure they have 3+

**Comment by fandrus** [comment]
ok thanks!! :D
