### ISSUE TITLE
Don't retrieve items after winning a war

### ISSUE THREAD

**Issue by AnnoyingGuildBug** [Wynncraft/Issues#1529]
At the end of a war, it says we get drops. Yet the guild world has never let me bring back one of the hundred legendary endgames I've gotten in it.

**Comment by SkySaito** [comment]
I don't think it's possible to bring back items from a war. You just said how many endgames are dropped so I think for the good of the market, we won't have any of these.

**Comment by AckroGaming** [comment]
This is not a bug. Clearly intended!
