### ISSUE TITLE
Teleportation glitch using /class while riding people

### ISSUE THREAD

**Issue by Anuze** [Wynncraft/Issues#1530]
When VIP's or VIP+' ride people and the rided player types /class to select another one, he will be teleported to the position he was at with the class used before.

**Comment by epicman739** [comment]
Your description is a little confusing.
So, for example, if I was on my mage class and a VIP was riding me, then if I switch to archer class, my archer will be at the same spot as my mage?

**Comment by Anuze** [comment]
Sry forgot to reply :D Ik its hard to explain but ur right ur archer will be at the same location as ur mage

**Comment by poppet1693** [comment]
this happened when i had 6 ppl stacked on me it was rly freaking but when i changed classes they went back
