### ISSUE TITLE
WynnExcavation Site B Quest Not Working

### ISSUE THREAD

**Issue by builderJP** [Wynncraft/Issues#1531]
Hello, this is builderJP, and I'm sorry about last time about the Frost Bitten quest. I read the quest book wrong. Now, I'll get to the point. I want to do the WynnExcavation Site B quest, but when I tried to talk to Excavator Lykron, it just came up blank! Please fix this bug!

-builderJP

**Comment by epicman739** [comment]
This one's a known issue, it should be fixed in the next update.
