### ISSUE TITLE
Lost quest items in server restart

### ISSUE THREAD

**Issue by d1ckl3mcp1ckl3** [Wynncraft/Issues#1532]
When attempting to complete the 'Lord of the Clock quest, the server restarted after Frudo took the clock, and when I logged back in, I couldn't finish the quest. Please help as soon as possible. 
Steps to reconstruct:
- Start lord of the clock quest, and complete it up until the point when you are supposed to destroy it.
- Enter Mt. Wynn and after Frudo takes the clock, restart the server. (Before he finishes talking!)
-linuxminer

**Comment by epicman739** [comment]
Well, /fixquests should give you back the clock, but it's a buggy command and may not work.
Next time, be careful with what you do around restarts.

**Comment by d1ckl3mcp1ckl3** [comment]
Thank you so much![?] Like I was really sad.
