### ISSUE TITLE
I cant identify the Pélier helmet

### ISSUE THREAD

**Issue by TheMineNerf** [Wynncraft/Issues#1533]
I was trying to identify the helmet but it kept telling me that i can only identify items w/ Unique Rare Legendary or special (the helm is special) and according to the wiki it was fixed in the 1.12.1 update but it still not working

**Comment by MrBattleHammer** [comment]
common problem, apparently they arent going to fix it or something cause it
has been a problem since the beginning, but they havent fixed it yet

**Comment by epicman739** [comment]
This is a known issue. Most items with accented charecters cannot be identified.
