### ISSUE TITLE
Caught in WynnExcavation Site B

### ISSUE THREAD

**Issue by bvx** [Wynncraft/Issues#1536]
I am in the purple chrystal hall/room and got the purple chrystal, but i can't get out of there. I'm walking on the coal blocks what i think is the exit, but nothing happens. Please fix this bug so fast as possible, i want to play!!

**Comment by Louis-D** [comment]
Same...

**Comment by Louis-D** [comment]
Try going to the back. Just move around a little it worked for me..

**Comment by bvx** [comment]
Thank you for the advice, but it didn't work. I still need help to get out!!

**Comment by Trixter313** [comment]
Type /kill into chat and you will respawn at the nearest visited town. This will take 2 soul points so make sure you have 3+.

**Comment by bvx** [comment]
Thank you guys for your advice, I finally got out! :D
