### ISSUE TITLE
I do not get my loot...

### ISSUE THREAD

**Issue by Toeffe3** [Wynncraft/Issues#1537]
I do not get any loot from the wither skeleton boss, the chat say that i have got:
498 xp
3 fallen emreals
1 spider dungeon key
what should i do???!!!

**Comment by vogelmet** [comment]
do you have a picture? the key shold be in your inventory and the emeralds fall down next to you after you was teleported out of the dungeon.

**Comment by Toeffe3** [comment]
![2015-01-21_20 59 01](https://cloud.githubusercontent.com/assets/10633478/5843918/61d0d844-a1b0-11e4-8089-3d398300d4c1.png)
after i was teleported out nothing happened. this picture was taked short after
