### ISSUE TITLE
Excavator Vade quest glitched or wrong text

### ISSUE THREAD

**Issue by xMrPoi** [Wynncraft/Issues#1538]
I tried clicking on Excavator Vade and I got this message: http://i.imgur.com/fh1XsTB.png
Either the quest is glitched or the text is wrong. Either way, there should also be a space between the colon and the text.

**Comment by Jamdog** [comment]
Thanks for the report - I changed the text to say Lv 35, and added the space.  You should see the changes next time the live servers are updated.

@Tama63 - this can be closed...
