### ISSUE TITLE
Water puzzle in  Water Mini Dungeon is broken

### ISSUE THREAD

**Issue by bamboobazooka** [Wynncraft/Issues#1539]
me and a friend were trying to complete this and it sorta worked once then flat-out did not work. There is no water flow and sometimes the blocks will not move at all i feel as though this is simple redstone errors but still thought i should post this please fix this quick we are kinda stuck in there aside from doing /kill

**Comment by epicman739** [comment]
This one's a known issue, it should be fixed soon.

**Comment by Jamdog** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/1445
