### ISSUE TITLE
Stuck and accidentally item

### ISSUE THREAD

**Issue by skylordruler1** [Wynncraft/Issues#1540]
I (skylordruler1) was recently playing Wynncraft when I came across a persisting problem of getting stuck in blocks while doing the mask maker's quest of fetching a mask. I get stuck every time I teleport back into the main hallway leading to the parkour. 
(The third time this happened I accidentally dropped my Flawless Birch Sharpness II Wand, is there a way of getting this back?)

![2015-01-22_17 37 46](https://cloud.githubusercontent.com/assets/10662039/5867234/ecea2742-a25e-11e4-9ff9-acb2f2443710.png)

**Comment by epicman739** [comment]
Well if the teleporting's not working, all you can do is wait until it's fixed. Also, there's a no-refund policy, so you can't get your wand back, though if you ask nicely someone will probably give you a decent weapon for cheap or for free.
