### ISSUE TITLE
Time Cycle Not Working

### ISSUE THREAD

**Issue by AtripleN** [Wynncraft/Issues#1542]
All the worlds are day forever they never become night. And at a random time in day it says "the sun has risen, you feel safer" +1 Soul Point! And its been day the whole time since then!

**Comment by epicman739** [comment]
Perhaps it's your Minecraft client that isn't rendering the day-night cycle properly. Check your settings to see if anything is wrong.

**Comment by AtripleN** [comment]
Its not my minecraft its glitched with everyone j have sun and stars amd
everything on and all my friends see it day forever and I have optifine and
I talked with some VIPs ans they also experience this.
