### ISSUE TITLE
Trade Glitch 

### ISSUE THREAD

**Issue by AtripleN** [Wynncraft/Issues#1543]
I was showing someone my Emerald Blocks in the trade thing, then I put 2 stacks and 42 emerald blocks and the 42 disappeared I tried re-logging and and restarted Minecraft and I double checked my bank because I brought it from their but it still wasn't their, this might be la but I had perfect connect to the server. Please Fix! I lost a third of my money!

**Comment by AckroGaming** [comment]
No-Refund policy, and this is also a known occurance.

Be a bit careful when using the trading feature ;)
