### ISSUE TITLE
lost a quest item because of the 1.12 update

### ISSUE THREAD

**Issue by TheMineNerf** [Wynncraft/Issues#1544]
i was training my archer (lvl 25) and i just finished the quest "grave digger" and when i finished i noticed that i didnt had another Sayleros' brother ashes in my enderchest but with my mage (lvl 40) i already did this quest before the 1.12 update.

**Comment by epicman739** [comment]
/fixquests should return it to you, though the command is buggy and may not work.

**Comment by MrBattleHammer** [comment]
it never works, it never has for anybody

**Comment by Jamdog** [comment]
Have you tried it recently?  Jumla fixed some issues with the /fixquests command - if you have lost a quest item, it's worth trying.

**Comment by MrBattleHammer** [comment]
i tried it maybe a week after the new major update came out, so maybe it
has been fixed, but every time i have tried it or somebody else has it
hasnt worked
