### ISSUE TITLE
Underwater Quest is Glitched

### ISSUE THREAD

**Issue by GammingTNT** [Wynncraft/Issues#1545]
I was doing the underwater mission when a problem occurred Sayrr asks me for the water bottle and 3 pigmen meat. I go and grab them return to him and he doesn't give me the helmet or take the items and wont let me proceed with the quest can someone fix this problem?

**Comment by Jamdog** [comment]
There are actually 2 types of pigman meat, and Sayrr only accepts one type.

I believe the pigmen in Pigman Ravines drop the correct type.  The 'lore' should say 'Misc Item' when you hover over it.
