### ISSUE TITLE
Mage teleport in duel do no damage

### ISSUE THREAD

**Issue by SkySaito** [Wynncraft/Issues#1547]
Hello,
I'm posting this issue to tell about a bug I have seen, which make the teleport spell unable to do any damage in a PvP duel. When I try to attack someone, I teleport but my opponent didn't get damaged.
I though it was just me but I then ask someone to duel me and to attack me with that spell. Same reaction, it doesn't work. So I was wondering if it can be fixed within the next bug update and if I can do anything to help that out.
Thanks in advance for a reply ^^

**Comment by AckroGaming** [comment]
This was intentionally removed in one of the latest major updates (1.12 I believe) since it was considered too over powered since mages already have the healing spell.

This still affects PvE, just not PvP.

**Comment by SkySaito** [comment]
;-; Wai ?
Just kidding, yeah that seems legit but now mage have only 2 spells that damage
