### ISSUE TITLE
Still happening.

### ISSUE THREAD

**Issue by anders1122** [Wynncraft/Issues#1550]
I'm not sure what to do anymore, it's really starting to bother me.
https://github.com/Wynncraft/Issues/issues/1516

**Comment by anders1122** [comment]
Just amazing how you don't even take the time to reply to it.

**Comment by Jamdog** [comment]
It's odd that this is only happening to you.  No other players appear to be affected by this.  This suggests to me that the issue may be with you Minecraft client.  What version are you using, and is it a vanilla Mojang client, or a third-party modded client?

The only thing I can suggest is that you re-install a fresh vanilla Mojang client.  This can be done by removing the contents of your **%APPDATA%/Minecraft** folder, and when you use your launcher, it should download a new copy.  Note that you may wish to leave the 'Saves' subfolder which has your single-player maps, and the texturepacks and resourcepacks subfolders, as these shouldn't cause an issue.
