### ISSUE TITLE
Emeralds

### ISSUE THREAD

**Issue by StillAliveGames** [Wynncraft/Issues#1556]
I have Emeralds and Emerald-Blocks that i can't use in my Enderchest.
Can you help me with that?
Username: kkevin2001
Thanks ;)

**Comment by Trixter313** [comment]
Use Minecraft 1.7.10 to log onto Wynncraft and trade those emeralds with some emerald merchants. You will get the new emeralds in return. This won't work in 1.8 because of a big fix in it.

**Comment by StillAliveGames** [comment]
Thanks ;)
