### ISSUE TITLE
WynnEvcavation Site B broke

### ISSUE THREAD

**Issue by JustRoks** [Wynncraft/Issues#1557]
The starter NPC Lykron is broken.  Whenever you try to click on him to begin the quest, he just says an empty chat bar shown in the picture.
![2015-01-25_16 04 20](https://cloud.githubusercontent.com/assets/10700154/5893486/f574d5b6-a4ab-11e4-8b0a-636c622178e5.png)

**Comment by epicman739** [comment]
Known issue, should be fixed soon.
