### ISSUE TITLE
Sayrr doesnt accept 

### ISSUE THREAD

**Issue by ondrej008** [Wynncraft/Issues#1558]
Ok so i have just started the Underwater quest and then i go to sayrr and im clicking that dude and im like wut? Wheres his hitbox! And then i find it i bring the meat and the water bottle and you know WHAT? He doesnt want it! He refuses to do anything but spam his Bring me 3 Pigmans meat and 1 Water Bottle.

**Comment by ondrej008** [comment]
http://imgur.com/a/6FjbN

**Comment by Trixter313** [comment]
Go to the pigman ravines and get the meat from there. There are 2 different types and the one you have isn't the one wanted for the quest. The lore on the meat should be "Misc. Item" not "Junk Item"

**Comment by ondrej008** [comment]
Oh thanks and the hitbox of Sayrr is not where the halfling one is its on his right kinda of.
