### ISSUE TITLE
Guild territory bug (NOT FIXED!)

### ISSUE THREAD

**Issue by MISSINGNO274** [Wynncraft/Issues#1561]
Driver and have him fix today confirmed that the occupation and to attack Great Bridge.
Ending the occupation '/ guild defend' he bought a mop through, it was out of the server.
I came back the territory, and the recognition of our territory , is the occurrence of bugs that should have struck again.
And the bug is not all territories except the attack Throms.
Please fix this bug again properly.

**Comment by Trixter313** [comment]
I'm assuming english isn't your first language but what I got from that is your guild bought some land and defended it and now it has a different guild's name on it? If thats the issue, another guild attacked the land and won it for themselves. Although the /guild attack command seems to be broken right now so I'm not sure... Did I understand what you mean incorrectly?

**Comment by MISSINGNO274** [comment]
I was only an attempt is made to the story in detail.
(Revised)
