### ISSUE TITLE
The 1.8 Armor System is buggy when you changed your skin

### ISSUE THREAD

**Issue by croclingplays** [Wynncraft/Issues#1562]
Hey Wynncraft team! 
I changed my skin in Minecraft but when i wear my armor my old skin is showing so what is wrong?
![2015-01-28_17 19 22](https://cloud.githubusercontent.com/assets/10744226/5941587/44ea62e2-a712-11e4-8fbf-3fc9c7a93295.png)
![2015-01-28_17 19 11](https://cloud.githubusercontent.com/assets/10744226/5941588/44f43e5c-a712-11e4-8738-4470e4c9e041.png)

**Comment by epicman739** [comment]
Well the armour skins are technically semi-beta, so there may still be minor issues. I think if you wait maybe a week or so the skin database should update properly, and it should work.

**Comment by Tama63** [comment]
Being fixed soon!
