### ISSUE TITLE
Falling through Ground.

### ISSUE THREAD

**Issue by pokerpo** [Wynncraft/Issues#1568]
So, I was in the Silverfish Dungeon, Teleported to boss, And the chunk I was standing in didn't load in time and I sunk right through.
Can't show a pic because I suicided afterwards.
Has been happening a lot, I went in the Tower of Ascension floor 2, Teleported and sunk through chunks, and had to suicide.
I don't want to lose more soul points. Please fix.

**Comment by epicman739** [comment]
I think this might be an issue with your internet connection.

**Comment by poppet1693** [comment]
I have something like this but its worse i am actually stuck underground cant use tele scrolls and nothing is there to kill me, not my internet this has happened for 1 week, I can not play again till i get teleported out.... Can a mod or something teleport me to a towns coords or something? I really like this game, my minecraft username is: poppet1693

Please help   -Thnx

**Comment by Trixter313** [comment]
Type /kill into chat and you will respawn in the nearest visited village @poppet1693
