### ISSUE TITLE
Urgent: I am Stuck Underground

### ISSUE THREAD

**Issue by poppet1693** [Wynncraft/Issues#1569]
Hi, Im stuck underground in the future of selchar where the santa boss is... I teleported to the bossroom but I fell underground and cannot move... I tried using tele scrolls, my escape spell!!!

Please teleport me out so i can keep playing! This is an amazing mmorpg server My IGN is poppet1693, My Coords are:
x -8054.700
y  92.00000
z -12245.300

Please Help, This is urgent this has also happened to my friend Tomleeds but he can right his own post if he has to           -thnx

**Comment by poppet1693** [comment]
I actually think that its the santa bossroom doing because he got stuck same place as me when traveling to the santa bossroom

**Comment by vogelmet** [comment]
do /kill but make sure that you have 3 or more soul points. it will teleport you to the next city. its known that there are some strange points where you can get stuck in this quest

**Comment by poppet1693** [comment]
K i have 12 thanks

**Comment by poppet1693** [comment]
NO
I went back but i got respawned underground again NOOO

**Comment by poppet1693** [comment]
I did /kill

**Comment by poppet1693** [comment]
I had to do /kill twice to get out of the ground
