### ISSUE TITLE
Wynncraft Relic Leggings [Cant enter this region and Red stone hole]

### ISSUE THREAD

**Issue by bolt88** [Wynncraft/Issues#1570]
First of all when you first open the relic door there is a hole that u can easly fall in.
secondly when climbing the ladders to the relic its says "you may not enter this region" 
so i cant get the relic :(

**Comment by vogelmet** [comment]
which relic is this?

**Comment by Jamdog** [comment]
Same as Issue https://github.com/Wynncraft/Issues/issues/1566

The reason you get the message "You may not enter this region", is that you cannot reach the top of any of the 'islands' in the Mesa until you have given a Rare Rose to the Hermit during the Canyon Condor quest.  You will need to do this before you can get to the relic.

**Comment by PinkWool** [comment]
what a troll
