### ISSUE TITLE
Stuck in the ground

### ISSUE THREAD

**Issue by minecartrider21** [Wynncraft/Issues#1571]
I was playing through the Craftmas Chaos quest when I jumped through the pit to past Selchar (If that's how you pronounce it) and I got stuck in the ground! I've tried disconnecting and reconnecting also going to the hub and back. But nothing worked Plz halp.
![2015-01-31_19 06 23](https://cloud.githubusercontent.com/assets/10791591/5990395/be3f2b2a-a97c-11e4-9ee9-eee3d2b6822e.png)

**Comment by Trixter313** [comment]
Type /kill into chat. You will respawn in the nearest visited town.

**Comment by vogelmet** [comment]
dublication of #1569
