### ISSUE TITLE
Leggings Relic Redstone Wiring Exposed (a lot)

### ISSUE THREAD

**Issue by coolduck22** [Wynncraft/Issues#1572]
After entering the combination for the door to the Leggings Relic at Rymek, there is a hole in the floor where the Piston Door opens up that leads to the circuits. I think whoever made it forgot to seal it off after editing it.

**Comment by coolduck22** [comment]
Here's a screenshot: 

![image](https://cloud.githubusercontent.com/assets/10681977/5990763/f61ca614-aa15-11e4-8015-63d687a57f99.png)

**Comment by BlackAlchemist** [comment]
Another screenshot of how bad...
![2015-02-01_19 32 28](https://cloud.githubusercontent.com/assets/10802769/5994637/acff8d28-aa49-11e4-8267-e6d66d7837ed.png)

**Comment by coolduck22** [comment]
Yeah, I had to /kill to get out when I fell in the first time...
