### ISSUE TITLE
Assassin Spin Attack Retrieves Negative Effects

### ISSUE THREAD

**Issue by FOEVERGOD73** [Wynncraft/Issues#1573]
The official wynncraft class description says that level 3 spin attack has a new effect called vampire
"Vampire, steals all the positive effects your opponent has, and clean all the negative ones you have"
But not only positive effects are stolen, negative effects are as well. when you hit a mob casting a spell with a spin attack, you get "frozen" in place

**Comment by P3BBL35** [comment]
It actually does not steal the negative effects. When a mob casts a spell, it is frozen in place by the Speed effect. Since Speed is a positive effect, you'll steal that effect, which in turn, freezes you in place.
