### ISSUE TITLE
Unable to access wynncraft fourms

### ISSUE THREAD

**Issue by FOEVERGOD73** [Wynncraft/Issues#1574]
when i try to open any specific post in wynncraft fourms i get this error:
Fatal error: Class 'XenForo_Application' not found in /usr/local/apache2/htdocs/wynncraft_forums/library/XenForo/ControllerPublic/Thread.php on line 2121

**Comment by NerdYouDontKnow** [comment]
I can confirm this.

**Comment by NerdYouDontKnow** [comment]
Appears to be fixed
