### ISSUE TITLE
 Wynncraft Excavation Site B want start bugg

### ISSUE THREAD

**Issue by vorck** [Wynncraft/Issues#1575]
When talking to Excavator Lykron when doing Wynncraft Excavation Site B to start the quest, I get a blank text, and when I check my quest log, it says I need to talk to Excavator Lykron and it has the "started icon" instead of "Not Started" can you help me.

**Comment by vorck** [comment]
and can you explane me what is duplicate?

**Comment by thesirhc** [comment]
They have not done well with this quest. I've seen a lot of people not know what to do and they haven't done much to clear it up. 

Anyways, you have to bring with you the yellow crystal from the WynnExcavation Site A quest.

**Comment by vorck** [comment]
Tanks so mutch men!!!! Your the  best
