### ISSUE TITLE
Questions were not answered! after one year. + my Problem

### ISSUE THREAD

**Issue by fabikong02** [Wynncraft/Issues#1578]
I put my issues a year ago. now the problem is still there.
I made a video to !: http://youtu.be/PtaCYIAklOM
In this video you can see my problem. I can not select classe and chatting is should I joinen again. this is what I did (total of 100 times (no joke!)).
Now I wonder why does it take so long? The problem is there already for ages. I fande the server but the good support now worse than bad. I therefore ask what to do about it. I know there are many problems but it is not acceptable that I have a year to the answer to my problem was to no avail! My in game name is Fab_Kong02.
Please fixes the problem and the bad support!

with friendly greet Fabikong

**Comment by AckroGaming** [comment]
That seems odd. I have only seen people falling through void, but no actually get exited from the world. I think that there is something to do with world loading, which may be something from the coding Crunkle did to prevent map downloading. I have had that happen quite sometimes, like I am walking around and all of a sudden a corrupted world chunk kicks me out.
