### ISSUE TITLE
 Wynncraft Excavation Site B stock in the purple crystal room 

### ISSUE THREAD

**Issue by vorck** [Wynncraft/Issues#1579]
im stuck in the purple crystal room i can't get out ist all time tp me back in the room help

**Comment by epicman739** [comment]
Try /kill. It will cost you 2 soul points and respawn you at the nearest city.

**Comment by vorck** [comment]
work but dosen't finish the quest i need tu solve the puzzel

**Comment by P3BBL35** [comment]
You need to walk up to the door behind the archaeologist, and the quest book should update. If it doesn't say so, check in your quest book and make sure it says something along the lines of, "Find the Crystal."
