### ISSUE TITLE
Water at Ocean Puzzle thing not flowing

### ISSUE THREAD

**Issue by PokeyzRule** [Wynncraft/Issues#1580]
There is a puzzle at around X= -934 Y= 1 Z= -3500 that involves blocking and unblocking paths for the water flow using buttons, however when I press the "start" button, the water will not flow, it is stationary.
-After pressing the start button, block retracts and water is supposed to start flowing, however it gets stuck
![image](https://cloud.githubusercontent.com/assets/10509677/6004789/6bfbb718-aad3-11e4-86e8-61cf163ba420.png)
It doesn't matter how many buttons you press, the water will not flow

Also, kind of related, but I don't think the yellow button works. Not sure if I should file a separate bug report or not.

**Comment by epicman739** [comment]
Known issue.
