### ISSUE TITLE
excavation B, quest not starting

### ISSUE THREAD

**Issue by Draneol** [Wynncraft/Issues#1581]
![2015-01-30_19 47 56](https://cloud.githubusercontent.com/assets/10818863/6009934/27a19c42-aaf4-11e4-8623-08dfa02beb95.png)

i cant get his quest no matter what i do :P

**Comment by Trixter313** [comment]
Make sure you have the yellow stained glass in your inventory from part A. ;)

**Comment by Draneol** [comment]
Thx that makes sense, i would have never figured it out myself. :P
