### ISSUE TITLE
wrong teleport destination

### ISSUE THREAD

**Issue by MrEvil135** [Wynncraft/Issues#1583]
So what happened It happened another time in the ice valley, where I dead and instead of sending me to the town, the death teleporter sent me underground beneath the ground. One week later it fixed itself so I thought it was an isolated incident, but after I got the purple crystal and headed out to the teleport, the teleport sent me beneath the ground again. And I am still stuck there. For some reason these only happened in my archer class. Whenever I play a different class I don't have this problem. I hop that this can get fixed.

**Comment by vogelmet** [comment]
tip: do /kill but make sure you have more then 3 soulpoints. it will teleport you to the next city so you don´t need to wait a week ;)
