### ISSUE TITLE
Animal Dungeon won't let me finish

### ISSUE THREAD

**Issue by ItsLukasz** [Wynncraft/Issues#1585]
So I was playing on wynncraft, and I decided to do every dungeon twice for loads of XP. I got to Animal dungeon and went to fight the Lava Cow. I'm a level 33 mage right now, if that affects anything. So I go and kill the Lava Cow once. It then appears again. I remember doing this before with 2 friends and one said it was the "Second Stage" or something, so I was like, "Ok, whatever. Twice it is". So I go and do the Lava Cow in again, and then it pops up a THIRD time. Then it pops up a fourth time, so I decided to just leave and  join back because I thought it was a weird glitch or something. Now I wasted a key and valuable time, and still can't actually complete the dungeon. Please help.

**Comment by epicman739** [comment]
So did this happen just that one time? I think it does glitch occasionally.
