### ISSUE TITLE
Name changing when VIP removes fly ability in lobby

### ISSUE THREAD

**Issue by Ward1246** [Wynncraft/Issues#1590]
In minecraft (1.7.10 tested only) players with VIP who change their name will no longer be able to fly in the lobby They will also be invisible, as if they did not have VIP at all. Everything else (In game stats, other VIP features) are just fine. There is also no blue name when in lobby

**Comment by Ward1246** [comment]
![vip bug](https://cloud.githubusercontent.com/assets/10855655/6049980/119d8f7c-ac8a-11e4-8c78-28e4f8897c1d.png)
![2015-02-04_16 21 40](https://cloud.githubusercontent.com/assets/10855655/6049992/22a609de-ac8a-11e4-9457-d0b76bd1a87c.png)

**Comment by Jamdog** [comment]
I believe this is the same issue as https://github.com/Wynncraft/Issues/issues/1589

**Comment by Theloverboy** [comment]
Same issue for me, I am Vip in game but not in the lobby, and yes I have changed my name.

**Comment by Theloverboy** [comment]
Same issue for me, I am Vip in game but not in the lobby, and yes I have changed my username.

**Comment by i-couldnt-think-of-a-name** [comment]
I made a final name change, my new name is Michael_de_santa and i lost lobby VIP again. I'm sure it will come back soon, but you should be sure to take a look into this.

**Comment by epicman739** [comment]
Don't worry, name changes only affect VIP/VIP+ in the lobby. It still works ingame. A patch should be out soon to fix lobby VIP glitching.
