### ISSUE TITLE
/class : tube world

### ISSUE THREAD

**Issue by Isabeau37** [Wynncraft/Issues#1594]
Typing /class alot results in to being teleported to this tube world?! (relog doesnt help)
![2015-02-07_16 57 42](https://cloud.githubusercontent.com/assets/10898381/6092766/f42d3a3a-aeed-11e4-9a3c-e7299bfc04d6.png)

**Comment by Trixter313** [comment]
Try typing /kill into chat. Also, can you post a screenshot without your HUD hidden? It can help with diagnosing the issue.

**Comment by Isabeau37** [comment]
Yes I know but thank you ( didnt get that last part about HUD hidden? what is that? )

**Comment by Trixter313** [comment]
When you press F1 and it hides your hotbar, hand, and crosshairs

**Comment by Jamdog** [comment]
There is a handy workaround to prevent you from experiencing this issue.  Simply don't spam the /class command...

Your HUD (Head-Up Display), as Trixter said, can be turned on and off by pressing F1. When taking screenshots to help diagnose problems, it may also be useful to hit F3 to display some client/player information, although in this case I can't see how showing the HUD, or extended information, would be particularly useful.

**Comment by Isabeau37** [comment]
Okey thank you :)
