### ISSUE TITLE
Old Questbook & Compass in Enderchest

### ISSUE THREAD

**Issue by Skjoldminecraft** [Wynncraft/Issues#1596]
I played Wynncraft back when it still were in early dev and back then i put my questbook and compass in my enderchest so i didnt miss them. (then i got kille by a cat and never played again)

Then ~1 year later i gave it a try again. i had really much fun until i realised that some quests didnt want to work and i cant take the questbook and compass out of my enderchest.

Now, ~1 year later, im posting this cause im trying to get into playing it again.(and hope i dont get killed by an ocelot c:) so yeah, for example i cant complete the Yahya quest cause my questbook says i've still not dont it even though i did 1 year ago and then when i tried to rightclick him both with and without the required items, he doenst even react or say anything. now i actually just want to start from a freash :(

http://i.imgur.com/9cthA7y.png
http://i.imgur.com/9cthA7y.png

please help if you can. i really want to get back into Wynn.

**Comment by Skjoldminecraft** [comment]
why'd Tama63 close this? :(

**Comment by Tama63** [comment]
The best way to solve this is to speak w/ a mod

**Comment by Skjoldminecraft** [comment]
i tried but either they wouldnt listen or just plain old couldn't find any :(

**Comment by Skjoldminecraft** [comment]
and they also just told me to report it so i did :(

**Comment by Jamdog** [comment]
Sorry, @Tama63 - we mods can't solve this one.  Only admins can actually remove items from player's inventory/bank, I believe.

Maybe drop an email to support@wynncraft.com asking for these items to be removed from the bank chest?
