### ISSUE TITLE
Bug VIP 

### ISSUE THREAD

**Issue by TheCarma** [Wynncraft/Issues#1597]
Hello i've a realy big probleme i change my username with mojang and in game my rank is an default rank like if im a new player my ancient username are the_carma my new is Royality_Carma please fix the problme :'( 
Ps:Sorry for my very bad english im french ans i've not use googletranslater

**Comment by P3BBL35** [comment]
Known issue

**Comment by dmhacker** [comment]
Similar problem [here](https://github.com/Wynncraft/Issues/issues/1600).
