### ISSUE TITLE
Changing to new guild not working correctly

### ISSUE THREAD

**Issue by kd8axg** [Wynncraft/Issues#1598]
I left guild KingDom of Sky(KoS)  5 days ago and made a new guild called Army of Wynn. Yesterday the bar at top was giving me stats for KingDom of Sky and everything in chat worked with Army of Wynn Today (2/8/2015) Army of Wynn is showing stats on the bar at top of screen but everything in chat works with KingDom of Sky. Also, between all this I am having trouble giving xp to either guild.

Sorry to be the bearer of bad news and I hope this is detailed enough a description to help out.

**Comment by Tama63** [comment]
Linked to #1607
