### ISSUE TITLE
Guild Chat Unresponsive

### ISSUE THREAD

**Issue by TheBluesGuild** [Wynncraft/Issues#1599]
Our guild is starting to have problems where people cannot see guild chat at all (I type and some of the others see but I can't), and current events like wars and defending won't show up as well. Also, lands aren't updating again, with us capturing territory and having it not change over or show up as captured in guild logs. Logs are completely out of date on that note.

Notice how there was no conquer message for this battle: http://imgur.com/kIKNten
No one saw that message in guild chat either, as well as the last time the confused sender saw anything in guild chat either, after this, it became completely unresponsive.

I hope this gets fixed.
-BlueLightning2K of The Blues

**Comment by epicman739** [comment]
Did you change your username? I think that causes issues with guild chat.
