### ISSUE TITLE
Block Glitch/Im Stuck

### ISSUE THREAD

**Issue by FatCat247** [Wynncraft/Issues#1601]
Hey I was doing the halowynn quest and when I received the pumpkin it glitched me into a stone block and I have a scroll and it wont let me teleport to anywhere I would really appreciate if you teleported me to Detlas, Ragini anywhere really my current co-ords  -372 21 -1967

**Comment by Trixter313** [comment]
Type /kill into chat. You will respawn in the nearest visited town and it will cost you 2 soul points.

**Comment by FatCat247** [comment]
Oh Thanks dude I spent like an hour trying to fix this and you come in like dude ..../kill XD lol thanks
