### ISSUE TITLE
Weapon Ids not working.

### ISSUE THREAD

**Issue by Alayathekid** [Wynncraft/Issues#1602]
I Ided my Windforce bow, and when I put it on I saw no change in any of my stats. I also tried this on a mage, and it showed no change in the stats. You can reproduce this by taking off all your armour, and putting your weapon in slot one. Then hovering over your head in the Character Info compass.

**Comment by epicman739** [comment]
I think it might be the compass not working properly.

**Comment by Alayathekid** [comment]
Yes after doing some calculations I realized this is there already an open issue on that?
