### ISSUE TITLE
Stuck in past selchar!

### ISSUE THREAD

**Issue by MooshieMaster** [Wynncraft/Issues#1606]
Today I was playing wynncraft and I didnt need to do a dungeon when I thought I did so I just died. It teleported me to past selchar even though that wasnt the last place i was at. I now have no way to get out and I am completely stuck there. Please help me. 

(ive tried swimming away, killing myself, etc.)

**Comment by flyingsheep1433** [comment]
Have you tried redoing the quest (Go into the caves again then go back to the evil place and teleport out when your done.)
