### ISSUE TITLE
wynnexcavation site b wont work

### ISSUE THREAD

**Issue by sting0626** [Wynncraft/Issues#1608]
i talked to lykron but it had no text in the text box ant my boot tells me to talk to lykron but it says its started

**Comment by Jamdog** [comment]
Your quest book should tell you that you need to bring along the Yellow Crystal Shard that you received at the end of the WynnExcavation Site A quest.  If you have the yellow crystal in your inventory, then Lykron should talk to you.

**Comment by sting0626** [comment]
no text comes up when i talk to him

**Comment by Jamdog** [comment]
Yes, you need to be holding the yellow crystal.  If you aren't holding it, then no text comes up...

Or do you mean that you are holding the crystal, and he still won't speak to you?
