### ISSUE TITLE
Stuck in the floor

### ISSUE THREAD

**Issue by quaser282** [Wynncraft/Issues#1609]
I was doing the Craftmas Chaos quest and died due to lag in future Selchar. upon re spawning I spawned in the ground and cant move

**Comment by quaser282** [comment]
![2015-02-12_11 02 15](https://cloud.githubusercontent.com/assets/10968499/6159847/1038aa04-b2a7-11e4-9f7c-cea1b8c9e1b0.png)

**Comment by Trixter313** [comment]
Type /kill into chat and you will respawn in the nearest visited town.

**Comment by quaser282** [comment]
Ok thanks
