### ISSUE TITLE
I don't get teleported to rpg area after choosing class

### ISSUE THREAD

**Issue by EnderDestroyer** [Wynncraft/Issues#1611]
I logged into the server on 1.8 to play and after i chose my class i was stuck in a black room and not teleported to the actual area where people play in. i took a photo of me in the black room with all my  inventory items can someone please help.
![2015-02-12_16 54 31](https://cloud.githubusercontent.com/assets/10971518/6162502/88a1c58a-b2d8-11e4-817d-66225e9cb5b4.png)

sorry that it's dark

**Comment by vogelmet** [comment]
do /kill it will teleport you out, but make shure that you have more then 2 soulpoints
