### ISSUE TITLE
Can't Leave Guild

### ISSUE THREAD

**Issue by Emily7974** [Wynncraft/Issues#1614]
*This didn't happen to me, it happened to MaxScrubLord (mc username) just he didn't have an account so I am making it for him.

I invited him to join my guild, but he couldn't leave his old one. He lost the 3 soul points, but was still in the guild. He tried doing /class and completely re-logging, but it didn't work. He tried again, and lost an additional 3 soul points, but still couldn't leave.

Thanks for reading!

**Comment by AckroGaming** [comment]
I do not know why this is occuring, and I do not think that you can fix this effectively.
The only way I think as of now would be that his old guild would be deleted. That is to the extreme.

**Comment by Tama63** [comment]
Linked to #1607
