### ISSUE TITLE
Custom armour not working

### ISSUE THREAD

**Issue by magmotarburn** [Wynncraft/Issues#1615]
Please! Just take the Custom armour off, It literally does not work! I only take about 25% damage with full gold armour and a Dead Subrub Resident took 1 Heart out of me per hit! Please get rid of it!

**Comment by epicman739** [comment]
Custom armour is just retexturing, it should have no effect on gameplay. If you don't want to see custom armour, just disable seeing the second layer of skins in video settings, or downgrade to 1.7x.
