### ISSUE TITLE
Quest Chat Not working

### ISSUE THREAD

**Issue by FatMatt1** [Wynncraft/Issues#1617]
Hi my Minecraft name Is Jutras87, now I don't know if its just me but my quests are not working, It started when I tried to start Wynn Excavation Site B, And the first person u talk to does not respond to me, It just comes up as a blank space in chat, So, I decided to go on a different one, Frost Bitten, And everything seemed fine until I brought back the 8 lava and the bucket to the old guy, and then it started comeing in as blank text chat again, I have met several others who are also experiencing this problem, and to be honest, IT SUCKS, So please can u look into it?

**Comment by P3BBL35** [comment]
For Wynn Excavation B, did you make sure you had a Yellow Crystal Shard in your inventory b4 talking to Lykron? Also, for Frost Bitten, you should try turning in the 8 lava and the bucket to Alein instead of the "old guy". :/

**Comment by FatMatt1** [comment]
Yes It worked, but how was I supposed to know to bring a shard? I understand the frost bitten thing, but really i would have never known to bring a shard

**Comment by P3BBL35** [comment]
It makes it so that you have to do all the Wynn Excavation quests in order starting at A

**Comment by Trixter313** [comment]
Yeah, @FatMatt1 it's something they forgot to mention in the part B quest. They will fix it soon.

**Comment by FatMatt1** [comment]
k thanks for the help
