### ISSUE TITLE
Tower Of Ascension Glitch

### ISSUE THREAD

**Issue by dennismattias** [Wynncraft/Issues#1618]
I was just trying to lvl up on my ninja so i completed the tower of asencion on lvl 40. How i did that was like this, i took all the tokens from my other account and transfered them to my ninja and when i was done with that i finnaly completed the Quest but then i noticed that i only have gotten 1/10 xp from the quest. And how i know how much xp i would have gotten is becuse i have of course completed the Quest on other low lvld classes and lvld up alot from the quest. But i didn't even lvl up once from the quest and i was in lvl 40. Thank you for reading this and i hope i can get the rest of the xp that i deserv.

from: Dennis. Minecraft account: dennismattias

**Comment by epicman739** [comment]
The higher your level, the more xp it takes to get to the next level. This may make quests seem to give less xp.

**Comment by dennismattias** [comment]
didn't you see what i writed? i sayd that i have completed it on other classes already and gotten like 7 lvl ups form the quest but i didn't lvl up once from it on my ninja!

**Comment by epicman739** [comment]
Well you said that you completed the quest on other low-level classes, but your current charecter's level was level 40, so I assumed that it was a higher level than the others.

**Comment by dennismattias** [comment]
omg....read please. the quest is for lvl 40 -_- i lvld up like 7 times on my other classes from the quest! and this time when i completed it on a lvl 40 class i got no lvl up. what don't you understand?

**Comment by dennismattias** [comment]
and no the classes i got so many lvl ups from was in lvl 40-45 that means that some of them was in a higher lvl then lvl 40 and got lvl ups! but on my ninja in lvl 40 didn't get a single lvl up
do you understand now?
