### ISSUE TITLE
Guild Attacks

### ISSUE THREAD

**Issue by TheBluesGuild** [Wynncraft/Issues#1619]
Attacking and retaking lands continue to be broken in a new way.

The Chat feedback for war servers (E.g. "A war will start in 20 seconds") is broken in that when it counts down to one, it stops playing entirely and the guild freezes. It's very selective when this, shown by how it's down to certain players. Wars I start with the command will be broken wars, but others can do it fine. Sometimes it's just me, sometimes a few of us, and more recently everybody.
We can no longer retake any land whatsoever and in a lot of cases it seems to be only certain guilds.
I hope this gets fixed as this is being added to a long line of previous bugs that are still extant in some way or another.

Thanks for the time and consideration.

-BlueLightning2K of the Blues.

**Comment by AckroGaming** [comment]
Thanks for submitting, as I have never seen this occur before. I guess Jumla will change the coding a bit again then.
