### ISSUE TITLE
Stuck underground during restart and need help

### ISSUE THREAD

**Issue by seanm1999** [Wynncraft/Issues#1620]
Hello my name is ign seanm1999 over the past few hours i have played on this wonderful server but during a restart i fell underground at around -979 63 -1692 if you could please tell me a way to get out that would be great as this server is fun and I'd love to continue playing
![image](https://cloud.githubusercontent.com/assets/11009329/6200880/afd07d08-b45a-11e4-81bd-7631c93c4a2d.jpg)

**Comment by epicman739** [comment]
Next time, please take a screenshot with F2 instead of taking a picture of your screen. As for your problem, /kill should get you out. Remember that /kill will cost you 2 soul points.
