### ISSUE TITLE
Teleporting to Past Selchar again?

### ISSUE THREAD

**Issue by XxG0ldLeg3ndxX** [Wynncraft/Issues#1621]
Hello Wynncraft Mods and Devs, 
I'd like to report an issue. I had just finished the Craftmas Chaos quest and went to Detlas. Then I went to Maltic. And then Ragni. My friend wanted me to do the spider dungeon with him, so I did. I had to go afk, forgot to log out, and when I respawned, I was in Past Selchar. Why??? I went to MAatic, Detlas, and Ragni (A major city) but I still spawned in Past Selchar. I find it very annoying that I have to complete the quest AGAIN, so could you please fix this bug, or teleport me out? I think that this is a MAJOR bug and will disappoint many players. PLEASE FIX

**Comment by XxG0ldLeg3ndxX** [comment]
My username in WynnCraft is XxG0ld_Leg3ndxX. Please teleport me out of PAST SELCHAR

**Comment by epicman739** [comment]
/kill may or may not bring you out of Past Selchar. Note that it will cost you 2 soul points.

**Comment by XxG0ldLeg3ndxX** [comment]
It doesn't work. It just teleports me to Past Selchar again. I've consulted a few mods
