### ISSUE TITLE
Excavation B issue- cant get out

### ISSUE THREAD

**Issue by TreeJay** [Wynncraft/Issues#1622]
Ive run through the quest, twice, everything has been fine. Up until the point where i reached the crystal. I have shards, but it wont teleport me out of the area when i go onto the black area. The quest book says 'solve the puzzle' which, i believe i have done unless i missed something. But i found the door and everything. Please help.

**Comment by epicman739** [comment]
Have you tried switching servers, relogging, etc? If all else fails, do /kill, which will cost you 2 soul points and respawn you at the nearest town.

**Comment by TreeJay** [comment]
Ive done all that, even done /kill, ran back and went back through it and i cant complete the quest without going through this part i believe :/ Not sure if the quest is 'stuck', but the quest book says 'solve the puzzle'. I can try and do another quest then come back to it but not sure if that would fix it :/

**Comment by P3BBL35** [comment]
You have to walk up to the door behind the Archaeologist. It should say "[Quest Book Updated]". If it doesn't, check your quest book to make sure it says something like, "Retrieve the crystal."

**Comment by TreeJay** [comment]
Yeah it didnt say that. What can i do to fix that? Can i restart quests?

**Comment by P3BBL35** [comment]
You can't restart quests. Not that I know of. The quest book just says, "Solve the Puzzle", which is kind of confusing since you won't know how to "solve the puzzle". From what I've experienced, you would have to walk up to the door to get the quest book updated so you can get the Purple Crystal Shard and be able to exit the cave.
