### ISSUE TITLE
Jungle Fever Reward Glitch

### ISSUE THREAD

**Issue by phoenix7980** [Wynncraft/Issues#1626]
Hello,

I'm phoenix7980, today I finished jungle fever quest. I already had two liquified emeralds in my inventory, so when I finished the quest, he turned my two liquified emeralds into quest items called Almuj's Liquified Emerald, and gave me one normal liquified emerald as my reward for the quest.
Here is a screenshot from when I finished the quest.
![2015-02-15_18 40 36](https://cloud.githubusercontent.com/assets/7629728/6205791/924198a8-b5bd-11e4-9789-380e723f6242.png)
Here is another screen show showing that I was left with quest item emeralds.
![2015-02-15_18 33 54](https://cloud.githubusercontent.com/assets/7629728/6205794/99ce5200-b5bd-11e4-90df-d7aee6bfac7f.png)

Please is there anyway that I can get them back, because there is no way that I could have known that I shouldn't have already had Liquified Emeralds in my inventory.

Phoenix7980

**Comment by epicman739** [comment]
This is a known issue. Unfortunately Wynncraft has a no-refund policy, so you can't get them back. Hopefully this will be fixed soon.
