### ISSUE TITLE
Stuck in the floor in the craftsmas cahos quest

### ISSUE THREAD

**Issue by lucko4576** [Wynncraft/Issues#1627]
I was doing the craftsmas cahos, but when I jumped into the cave it teleported me into the floor (I think).
![2015-02-15_19 52 20](https://cloud.githubusercontent.com/assets/11022378/6205903/568b1832-b54c-11e4-825d-abe914458c5e.png)

**Comment by epicman739** [comment]
/kill should get you out, though it will cost 2 soul points.
