### ISSUE TITLE
I can't leave my Armor.

### ISSUE THREAD

**Issue by Hectowood** [Wynncraft/Issues#1628]
Hello,
I have a problem with my armor,
i cant leave it since the new armor skin.
Now i had slimeball for my Armor and i can't leave it.

Can you help please?

(Sorry for my bad english, it's not my native language.)

**Comment by SkySaito** [comment]
What do you mean by you can't leave it ?

**Comment by Trixter313** [comment]
He most likely means he can't take the armor off. Try restarting your Minecraft.

**Comment by Hectowood** [comment]
Restart my game worked ! Thank you very much guys ! <3
