### ISSUE TITLE
Archer Account is stuck in the black room where classes are normally chosen

### ISSUE THREAD

**Issue by FireAfire** [Wynncraft/Issues#1629]
After the choose class screen comes up, I click archer, and I get my items, but I stay in the black box. I have a very good account and I currently have six of my eight legendary items on me. I can't do anything to get out. I tried a detlas to scroll but that didn't work. Please help get me out. Thanks in advance.
P.S. my mine craft account name is .
abksploder

**Comment by Trixter313** [comment]
I believe typing /kill worked for others who had the same issue as you.

**Comment by FireAfire** [comment]
Thank you so much!
You do not know how thankful I am!
