### ISSUE TITLE
Winter's Essence Pants not textured/applied to skin

### ISSUE THREAD

**Issue by tattoochicken** [Wynncraft/Issues#1630]
Hello, i recently acquired a pair of pants by the name of Winter's Essence a legendary pair with 55 def for levels 44 and above. For some reason they are not textured/they do not show up when i apply them to my skin i dont know if it is a work in progress or a bug but surly i shouldn't have bare legs when i have a set of legendary pants on.

**Comment by SkySaito** [comment]
Try restarting your Mineraft

**Comment by epicman739** [comment]
Could you have accidentaly turned off visibility on parts of your skin's second layer? Check your video settings.

**Comment by tattoochicken** [comment]
I have tried all these things and yet it still doesnt show
