### ISSUE TITLE
A bug reguarding guild creation

### ISSUE THREAD

**Issue by TheUltimateHunter** [Wynncraft/Issues#1631]
Hello Reader.
             I recently tried to make a guild of my own and spent 5 liquids to make one I choose a guild name a prefix and the guy toke the 5 le and soul points except I never got the prefix or the guild.
Others said the guild didn't even exist. Assuming It was just with my name changing my friend did it to
only to have the same outcome. So I don't think it has to do with name changing but it might have something to do with it. I'm not saying I want 5le for me and my friend back I'm aware of the no refunds policy. But if you could look into this bug I would appreciate that

**Comment by Trixter313** [comment]
I'm assuming it resolved itself because you closed the issue? Always great when that happens.

**Comment by TheUltimateHunter** [comment]
yes it was resolved although it took a lot longer than it should have in my opinion
