### ISSUE TITLE
[Stuck!] Hole you can fall in when doing the Craftmas Chaos quest

### ISSUE THREAD

**Issue by CookedPelvis** [Wynncraft/Issues#1632]
Hello, I was playing the Craftmas Chaos quest, and I went to Future Selchar to complete the quest and while I was looking for Santa, I fell into a hole, and I can't get out! There is no way out, I was hoping someone could help me.
![2015-02-17_21 17 24](https://cloud.githubusercontent.com/assets/11055356/6242798/76e70ed4-b6ea-11e4-8d90-4393d292db4a.png)

**Comment by Jamdog** [comment]
This hole has already been fixed on the build server - it is just waiting for a synchronisation push to the live servers.

You can use the **/kill** command to escape, as you have 12 Soul Points in your screenshot.
