### ISSUE TITLE
Tower of ascension bug 

### ISSUE THREAD

**Issue by Konanee** [Wynncraft/Issues#1633]
In the tower of ascension I'm stuck at the level 1 of the first floor. The floormaster is telling me that I have finished the lvl but I can't get teleported to the next level even if I do /kill and I come back. help ;(

http://puu.sh/g2geh/7f07af2fea.jpg

IGN : Konanee

**Comment by AckroGaming** [comment]
Stay in the teleport area for a bit longer, run around to the far back of it. That should work.

**Comment by SkySaito** [comment]
The floormaster won't teleport you, you have to go behind him, near the wall.

**Comment by Konanee** [comment]
I thought I already tried this but thx its working ._.
