### ISSUE TITLE
Guild xp Broken

### ISSUE THREAD

**Issue by PotatoDurp** [Wynncraft/Issues#1634]
After capturing 2 territories I decided to go grind xp for my guild. After a while I noticed that my guild's xp was over 100 %, deciding that it would probably be fixed if i just killed a mob or two i shrugged it off. So i started killing more mobs, however, the guild xp % wasn't resetting to zero. Even though, when i killed a mob it said that i was gaining xp when I checked /guild stats the number didn't actually go up. 

After relogging/joining different servers the guild xp just got a lot higher and my guild still isn't levelling up and then resetting the xp to zero
![guildxp2](https://cloud.githubusercontent.com/assets/11061910/6250459/efd1b256-b75b-11e4-857c-e7dd15135fca.jpg)
![guildxp](https://cloud.githubusercontent.com/assets/11061910/6250461/f6234228-b75b-11e4-9b77-5b3ae197031c.jpg)

**Comment by AckroGaming** [comment]
I think others have experienced this before, although I do not know how to fix it.
I do not think you yourself can fix it, since this is a messy code line I think.
