### ISSUE TITLE
Excavetor Lykron Bug

### ISSUE THREAD

**Issue by noni7070** [Wynncraft/Issues#1636]
my username is noni707070 and i have a bug in the quest WynnExcavation Site B.
I'm click on Excavetor Lykron and it shows me writing chat with nothing!
Attached is a picture.

Thank you!

![excavetor lykron problem](https://cloud.githubusercontent.com/assets/10988864/6253763/84eaea06-b7ac-11e4-8de0-4fe961c38560.PNG)

**Comment by Trixter313** [comment]
Click on him while holding the yellow shard you got from site A.

**Comment by noni7070** [comment]
Thank you!
