### ISSUE TITLE
I have broken Emerald's

### ISSUE THREAD

**Issue by LaPierSeth** [Wynncraft/Issues#1637]
I was on the server for a while and I left because of family problems. When I logged in today I found you switched the emeralds and I have  2 blocks and 2 stacks and 36 emeralds so if you can may they be switched with the new emeralds that are out pleas.

**Comment by Trixter313** [comment]
Log onto Wynncraft using 1.7.10 and trade your emeralds with the emerald merchants and it will give you the new emeralds. For the emeralds that are left over that is less than 64, theres nothing you can do about that but it can easily be regained with a little mob killing. ;)

**Comment by LaPierSeth** [comment]
I tried and its not working for me at all. :(

**Comment by SkySaito** [comment]
Did you trade blocks into emerald and then back to block ? In 1.7.10 ?
