### ISSUE TITLE
My Invintory is gone and my accound is gone!

### ISSUE THREAD

**Issue by minecraftzzgame** [Wynncraft/Issues#1639]
My old username was minecraftzzgame Now its Minecraftzz_Game ...
i thought the player ppid was used now its all gone!

Can you pleas Fix this bug!

Thanks ! 

Gmail:minecraftzzgamezz@gmail.com

**Comment by epicman739** [comment]
Wynncraft does use the UUID, so nothing should have disappeared. How much has been reset? Is it just your inventory, or is it levels and quests as well?

**Comment by minecraftzzgame** [comment]
Evry thing all of it i was lvl 75 on all classws vertran and all but 6 quest compleat.... With OLD items.... Alpha itens

**Comment by minecraftzzgame** [comment]
Its back

**Comment by minecraftzzgame** [comment]
but its a Old save from dec 2014

**Comment by minecraftzzgame** [comment]
i grinded from dec to jan

**Comment by epicman739** [comment]
That probably means you had a rollback for some reason.
