### ISSUE TITLE
No vip tag on forums

### ISSUE THREAD

**Issue by Victory-FTW** [Wynncraft/Issues#1641]
I bought vip a long time ago in like 2013 or something like that and on my character in-game I have the vip and all but on the forums I don't so is there a way to fix or...

**Comment by Trixter313** [comment]
Did you ever type the /forum command ingame?

**Comment by Victory-FTW** [comment]
Yes and it says "We can't authorize this account! Try again later...

**Comment by epicman739** [comment]
I think /forum is temporarily down right now for some reason.
