### ISSUE TITLE
Guild not working

### ISSUE THREAD

**Issue by Victory-FTW** [Wynncraft/Issues#1644]
I am a level 48 Victory_FTW and I just bought a guild for 5 LE and 5 soul points I made LegendsOfLeague guild and the pre-fix is SAD where is it it says that I am not in a guild and I am a little ticked off that it didn't work. Please get back to me as soon as possible.

**Comment by epicman739** [comment]
So you created a guild and you're not part of it?

**Comment by Trixter313** [comment]
I've heard from others that relogging/giving it some time usually resolves this issue.

**Comment by Victory-FTW** [comment]
Yeah its fixed just the servers had to restart and it worked
