### ISSUE TITLE
Skeleton Dungeon Bug

### ISSUE THREAD

**Issue by sammei19021** [Wynncraft/Issues#1647]
I was walking up the stairs and I fell completely down the floor and into this room. I know for sure this isn't meant to happen. Please fix. Im stuck in there atm.

http://i.imgur.com/wHefrWw.png
http://i.imgur.com/5DDTIEi.png
http://i.imgur.com/Bc3Pb9A.png
(Ignore Pg-13 Language, just a friend of mines)

Press Next to see the images. Cords are provided in the image

**Comment by Trixter313** [comment]
Type /kill and you will respawn at the nearest visited town. Make sure you have 3+ soul points when you do this.
