### ISSUE TITLE
[Quest Error] Wrath of the Mummy Quest: Taking 2 Pink Wool

### ISSUE THREAD

**Issue by DragonKing87** [Wynncraft/Issues#1649]
Hello, and first off thanks for reading this. A couple days ago I got to level 36, and started the "Wrath of the Mummy" quest. It requires you to go talk to a bandit to get into the "tomb". When I went to him to find out what to pay him, it didn't tell me. (Ignore text other than in black box, this pic was taken after I figured out this was a bug.
![2015-02-23_16 58 22](https://cloud.githubusercontent.com/assets/11167076/6338925/63d2e094-bb80-11e4-9e5b-6157c41c23e0.png)
It says "I'm not letting you in, unless you can pay me". I had no idea what this meant, so I turned to google. I went onto the wiki and found I needed a block of pink wool, and lucky for me I had one. I got it in my inventory, then went back to talk to the bandit. I clicked him, and he removed my pink wool, then gave me this. 
![2015-02-23_16 58 16](https://cloud.githubusercontent.com/assets/11167076/6338845/d2c40b1e-bb7f-11e4-94d6-f763dc517be6.png)
It then required me to get another piece of pink wool, something I still do not have. To restate that, he took my wool, then asked me for another piece of wool. 
I guess that's it, if this isn't a bug/isn't the right way to do this sorry, I just joined the forums today.

**Comment by epicman739** [comment]
I think you can ignore his message and walk past him. This is a known glitch with certain NPCs.

**Comment by DragonKing87** [comment]
Sadly I don't have a picture of it, but when I would try to enter the tomb he would say something along the lines of "I"m not letting you in unless you can pay me". It was impossible to get in.
