### ISSUE TITLE
Can't talk to Quest NPC

### ISSUE THREAD

**Issue by thegamershooter** [Wynncraft/Issues#1651]
I can't talk to quest NPC :

Before right click : 
![2015-02-25_18 19 26](https://cloud.githubusercontent.com/assets/11197073/6375980/1278ac50-bd1b-11e4-9fc7-79f4c15f4782.png)

After right click :
![2015-02-25_18 19 39](https://cloud.githubusercontent.com/assets/11197073/6375991/2640b976-bd1b-11e4-87f9-5eccb2cf7ed2.png)

But I can talk to the others NPC :
![2015-02-25_18 20 00](https://cloud.githubusercontent.com/assets/11197073/6376009/3b74d0e8-bd1b-11e4-920e-7c59c58b320a.png)

**Comment by epicman739** [comment]
What part of the quest are you on? Have you tried changing servers or relogging?

**Comment by thegamershooter** [comment]
After killing Sayleros brother's in the quest grave digger when I returned to Deltas to talk to the Quest NPC... He said nothing :(
I can not speak at all Quest NPC even if I changes server.
But this bug affect only my warrior...

**Comment by epicman739** [comment]
That's the wrong NPC for the quest. After killing Sayleros' brother, you should take the Dusty Will to Sayleros in Detlas, not Drucksh in Nemract.

**Comment by thegamershooter** [comment]
Errr.... thank you but sorry for the incoveniance
