### ISSUE TITLE
Not able to identify Relic Bow

### ISSUE THREAD

**Issue by ForenzoMintinez** [Wynncraft/Issues#1652]
Hi there!

I am here to tell you about an issue with the Relic Bow. 
It has come to my attention that I need Bob's Tear in order to continue in the quest "Bob's Lost Soul." Unfortunately, I cannot identify the bow, making it unable to give me loot bonus and such. 
What is weirder is that I can identify my Mummy's Rag and other legendaries that are untradable items.

Please help with this issue, if possible. Thanks for your time!

**Comment by epicman739** [comment]
Known issue, relic items currently do not have any identifications. Try another item.
