### ISSUE TITLE
Problem in troms!

### ISSUE THREAD

**Issue by Ulta80** [Wynncraft/Issues#1654]
I have found a little glitch! I let you see : https://www.youtube.com/watch?v=Xn9xgnWmNho&feature=youtu.be

**Comment by Trixter313** [comment]
The video is private so you're the only person who can see it.

**Comment by Ulta80** [comment]
Now you wan see it! : https://www.youtube.com/watch?v=Xn9xgnWmNho&feature=youtu

**Comment by epicman739** [comment]
I'm not quite sure what your problem is.

**Comment by Ulta80** [comment]
In theory i can't go in this cave.
