### ISSUE TITLE
Spider dungeon entrance error

### ISSUE THREAD

**Issue by Kyesel** [Wynncraft/Issues#1655]
I attempted to enter the spider dungeon, but instead of the dungoen, i was teleported to some wierd place, after wandering a bit, i took this screen shot, is this just the edge of the map, or something? When I did /kill, i went back to the beginning of the spider dungeon
![2015-02-26_21 12 16](https://cloud.githubusercontent.com/assets/11223936/6407794/918ea62a-bdfc-11e4-85b2-835f45b85b0b.png)

**Comment by Trixter313** [comment]
If you try to enter again now do you get teleported to the correct place? If so it was probably just a one time hiccup and you shouldn't have to worry.

**Comment by 31Yoshi31** [comment]
I had this problem too. i tried it again and i got there too :/

**Comment by Thibaud379** [comment]
I had this problem too and when i got in a secnd time same location for the builders I would guess
![2015-02-27_18 07 31](https://cloud.githubusercontent.com/assets/7968681/6419127/f154ef9c-beba-11e4-867f-53add70587c2.png)
