### ISSUE TITLE
Spider Dungeon Bug?

### ISSUE THREAD

**Issue by RickIsLegit** [Wynncraft/Issues#1658]
So I tried to go to the spider dungeon and this happened.
![2015-02-27_18 58 38](https://cloud.githubusercontent.com/assets/11233788/6418224/aa5fc442-beb3-11e4-8876-48449cfe889e.png)
![2015-02-27_18 56 13](https://cloud.githubusercontent.com/assets/11233788/6418225/aa656ca8-beb3-11e4-9276-691ead26e162.png)

**Comment by Ulta80** [comment]
That's happen a lot those time ;/

**Comment by epicman739** [comment]
/kill should get you out, but it costs 2 soul points.

**Comment by P3BBL35** [comment]
i did /kill when i was there, and i got tp-ed to Past Selchar lol
