### ISSUE TITLE
Lost GC

### ISSUE THREAD

**Issue by dennismattias** [Wynncraft/Issues#1659]
i bought 100 GC on the website and i have waited for over a half hour and i have still not gotten it.
 can someone please help me

**Comment by Ulta80** [comment]
Do you have a proof?

**Comment by Ulta80** [comment]
Do you have a proof?

**Comment by Ulta80** [comment]
Do you have a proof?

**Comment by Ulta80** [comment]
Do you have a proof?

**Comment by Ulta80** [comment]
Do you have a proof?

**Comment by Ulta80** [comment]
Do you have a proof?

**Comment by Ulta80** [comment]
Do you have a proof?

**Comment by dennismattias** [comment]
no i don't
but i am not lying

**Comment by epicman739** [comment]
If you don't have a proof of purchase of any sort, I think we probably can't help you. However, you can still email support@wynncraft.com to see if they can help.
Also @Ulta80 please don't spam the comments.

**Comment by dennismattias** [comment]
omg i finnaly gott my GC after 7 hours.....why so long

**Comment by Tama63** [comment]
Sorry the handler was down @dennismattias
