### ISSUE TITLE
Glitch at the barracks!!!

### ISSUE THREAD

**Issue by poppet1693** [Wynncraft/Issues#1660]
Hi, i had 2 soulpoints and one of the amoured bandits killed me and i lost all my stuff this isnt fair since  it was a glitch plz help :(

**Comment by poppet1693** [comment]
OMFG I CANT EVEN EARN MORE THAN 2 SOUL POINTS FIX THIS

**Comment by P3BBL35** [comment]
When you die with 2 soul points or less, you WILL lose all your items, except for quest and untradeable items. When you respawn, you only get 1 soul point back.
