### ISSUE TITLE
Quest Christmas Chaos

### ISSUE THREAD

**Issue by Starfoxx17** [Wynncraft/Issues#1661]
In the Quest Christmas Chaos, in Future Selchar when you need to go find Santa you go down the cave to find him in the Heart of Selchar. When teleported I was teleported into the floor and can't get out. Not quite sure if it's just a one time thing or if it happens to everyone.

**Comment by epicman739** [comment]
/kill should get you out, however it will cost 2 soul points.

**Comment by Starfoxx17** [comment]
I tried /kill but when it killed me is spawned me in the ground again.

**Comment by Starfoxx17** [comment]
Never mind, i relogged and it spawned me above ground. Thanks for the help!
