### ISSUE TITLE
Bugs = Less Soulpoints

### ISSUE THREAD

**Issue by poppet1693** [Wynncraft/Issues#1662]
Everyone time I join my hunter i have no hunger and start dying it doesnt hurt but i cant do spells this is really weird and i cant do anything about it i tried drinking instant hunger but it doesnt work, I did /kill and it fixed this but it happened again and again I think this is caused because of randomly and rapidly losing hunger i relogged about 3 times and reset my computer twice eventually it worked but i wasted a total of 6 soulpoints!! i am really sick of having to do /kill it wasted alot of soulpoints fixing bugs and also lost all my stuff because i had to do /kill 5 TIMES to get out of the ground in past selchar this is ridiculous, that i have wasted so many soulpoints on bugs!

**Comment by Trixter313** [comment]
Since the issue has resolved itself and soul points regenerate every 20 minutes so you're good there, what would you like us to fix? If this ever happens again try getting on a different Wynncraft world; that usually works for most people.

**Comment by poppet1693** [comment]
I just want to ask if you could try to fix some bugs? I mean 1 soulpoint every 20 minutes, but bugs are there forever untill you fix them

**Comment by Trixter313** [comment]
Has it happened to you again since?

**Comment by SkySaito** [comment]
I know this bug (I think). When you do /class and then redo /class to your character, it works.
