### ISSUE TITLE
Losing Items (supersquirt007)

### ISSUE THREAD

**Issue by BlurrSlime** [Wynncraft/Issues#1664]
My friend supersquirt007 has thrown away a quest item called climbing helmet a while back and he has not been able to get it back any help from admins?

**Comment by Trixter313** [comment]
Your friend can try the command /fixquests but it isn't completely finished yet so it most likely won't work. These kind of bugs have been reported already many times so the admins are aware but all anyone can do for now is either wait for a fix or you can do the quest that gives you the item on another class, put it in your bank, and take it out on the class that needs the helmet. Lesson to take away from this: Don't... whatever you do... throw away or eat any of your quest items! Good luck to your friend!
