### ISSUE TITLE
WynnExcavation Site B's shard room has some issues

### ISSUE THREAD

**Issue by Aiedail89** [Wynncraft/Issues#1666]
http://youtu.be/crrnZcUbelE
This is happening
I don't know what to do since it keeps teleporting me back and forth
(It's not lag from the server for sure)

**Comment by epicman739** [comment]
Have you tried switching servers?

**Comment by Aiedail89** [comment]
Yep
It doesn't work
I've been trying for a couple of days now even at different hours when there aren't many players but it won't let me go through :/

**Comment by AckroGaming** [comment]
I have tried this on the GM server, so what is occuring to you is not occuring to everybody.
I am not sure on what you could do, keep switching servers, or do /kill and go back to Lykron.

**Comment by HeadsetO** [comment]
Go back to the start of the cave, where you drop down after the puzzle and wait at that exact spot for 15 seconds, there is a region that will put you further in the quest, it's possible that it did not work when you passed it for the first time.

**Comment by Aiedail89** [comment]
IT WORKED!
Thanks and sorry for the pointless report
