### ISSUE TITLE
Can't identify the Ik-El-Vän Spear

### ISSUE THREAD

**Issue by Rijam** [Wynncraft/Issues#1667]
When I leveled up to 66, I was happy to use the Ik-El-Vän spear. When I went to the Item Identifier, it said "Only identify unique, rare, legendary, and special tags". This confused me because the spear is rare. I know there is a problem with identifying the relic bow, but I didn't think a rare was a problem. Hope you can fix it.

**Comment by slendersir739** [comment]
Known bug, the Wynncraft team is working on it. It's because of the special character.
