### ISSUE TITLE
Emeralds old and new

### ISSUE THREAD

**Issue by mindxt20** [Wynncraft/Issues#1668]
so I played this game when it was a lot older and I really loved it. my only problem is that I came on after a few months without playing and I have the older emeralds D: so this currency is useless and I only have 3 emeralds that are usable can anyone help I have 15 emerald blocks and 11 emeralds I was saving for a horse

**Comment by Trixter313** [comment]
Log onto Wynncraft using 1.7.10 and trade your old emerald blocks with the emerald merchants to convert them to the new ones.
