### ISSUE TITLE
Tripwire hook in the Silverfish dungeon does not work.

### ISSUE THREAD

**Issue by DarkExus** [Wynncraft/Issues#1670]
On the Forth phase. The part where "The fourth phase is a very simple puzzle. Upon reaching the end of the path, the player is faced with two corridors, however invisible blocks prevent the player from continuing through them. Instead the player must trigger a tripwire hook which opens a drop in the ground. The player must drop down. Afterwards, the player is faced with a short room with the closed door at the end. To open it a button at the other side must be pressed, then the player has to sprint for the door as huge swarms of mobs will be released. At the other side of the room the door leads to is the entrance to the boss."  The tripwire hook does not open the pistons.  I am stuck in here. I would like this fixed asap. plz

**Comment by epicman739** [comment]
Have you tried switching servers? Sometimes certain servers will glitch.

**Comment by AckroGaming** [comment]
I will check this out on the GM server, to see if it truly is broken.

**Comment by AckroGaming** [comment]
I have gone through the whole Silverfish Dungeon on the GM server, without finding any problems.
I'd recommend that you switch servers.

**Comment by DarkExus** [comment]
Ya I switched servers and it worked.
