### ISSUE TITLE
picking a class makes me trapped

### ISSUE THREAD

**Issue by purplenarwhalXD** [Wynncraft/Issues#1672]
when I always pick my archer class I am trapped in the dark room they show while your on the class menu. I tried to reset my computer and minecraft upload, but I am still stuck in the room with nothing to get me out. All I want is to be free from the room so I can roam around on the map again doing my quests as usual.
![minecraft problems](https://cloud.githubusercontent.com/assets/11306415/6477879/6414cf46-c1dd-11e4-9332-a0134c5d247e.png)

**Comment by epicman739** [comment]
/kill should get you out, but it will cost 2 soul points.
