### ISSUE TITLE
WynnExcavation site A quest now working

### ISSUE THREAD

**Issue by Troll2828** [Wynncraft/Issues#1673]
I was playing as warrior, and I started the wynnexcavation site A quest but when i returned to excavator Vade with the translated writing my minecraft timed out. I relogged on wynncraft and my translated writing was gone, I would be very thankful if i could get the translated writing because i want to finish the quest. My username in minecraft is Troll2828 by the way. Thanks! :)

**Comment by P3BBL35** [comment]
Try doing /fixquests. If it doesn't work, then you won't be able to do the quest unless you get the translated writing from one of your other classes, which means that one of your classes will not be able to finish the quest until you are able to get the translated writing back from /fixquests
