### ISSUE TITLE
Tower of Ascension can't proceed

### ISSUE THREAD

**Issue by Cloud6551** [Wynncraft/Issues#1676]
So, after clearing the first Tower of Ascensions floor and getting the 10 tokens I talk to the Villager, and he says "you can now proceed" I try to proceed but nothing happens, I don't get tp'd or anything... :x so I can't complete the quest, I would really appreciate some help, my username is Cloud6551.
![2015-03-05_00 27 55](https://cloud.githubusercontent.com/assets/11322483/6495925/82efe4b8-c2ce-11e4-98a4-a66b31f8ade7.png)

**Comment by epicman739** [comment]
Have you tried relogging or switching servers?

**Comment by Cloud6551** [comment]
Yes, I have tried both.

**Comment by xLifeFelix** [comment]
Same problem here. It won't teleport me on Floor 1 Lvl 2.
