### ISSUE TITLE
Can't enter Rymek *SOLVED*

### ISSUE THREAD

**Issue by ppanket** [Wynncraft/Issues#1678]
Hermit doesn't let me in even though i am level 39
![2015-03-06_14 51 39](https://cloud.githubusercontent.com/assets/11350022/6525632/73b84df8-c410-11e4-808f-68fa34d30212.png)
Ingame username = ppanket

**Comment by NLSlayer21** [comment]
u need to walk around the edge

**Comment by ppanket** [comment]
It was because i was at the wrong coords the corrds at the wiki or quest book is wrong

**Comment by ppanket** [comment]
It was because i was at the wrong coords the coords at the wiki or quest book is wrong

**Comment by ppanket** [comment]
It was because i was at the wrong coords the coords at the wiki or quest book is wrong

**Comment by ppanket** [comment]
It was because i was at the wrong coords the coords at the wiki or quest book is wrong

**Comment by ppanket** [comment]
It was because i was at the wrong coords the coords at the wiki or quest book is wrong

**Comment by ppanket** [comment]
It was because i was at the wrong coords the coords at the wiki or quest book is wrong

**Comment by ppanket** [comment]
It was because i was at the wrong coords the coords at the wiki or quest book is wrong

**Comment by ppanket** [comment]
It was because i was at the wrong coords the coords at the wiki or quest book is wrong

**Comment by epicman739** [comment]
The Hermit is a quest NPC, you need to do part of a quest to get past him. There are other ways into Rymek though, I know at least three tunnels exist. Or you could just jump off the cliff, you don't take fall damage.
