### ISSUE TITLE
Help im stuck

### ISSUE THREAD

**Issue by Poseidonz1342** [Wynncraft/Issues#1679]
![2015-03-06_19 06 39](https://cloud.githubusercontent.com/assets/11354184/6530815/5c3a641c-c434-11e4-8e47-1f9f62cc3eef.png)

pls help im stuck when i choose a class im still in this blackroom and not getting telepported

**Comment by NLSlayer21** [comment]
I'm 2

**Comment by NLSlayer21** [comment]
so annoying

**Comment by vogelmet** [comment]
Try /kill it will teleport you to the next city. but it will cost 2 soulpoints
