### ISSUE TITLE
Spawn Killing Me

### ISSUE THREAD

**Issue by That-Gamer** [Wynncraft/Issues#1680]
I was collecting mashed incests near Amuji when I died to lag again. The lag had been an issue randomly for me on practically all the servers so I was at 1 SP. when I got stuck in a wall and no amount of jumping or trying to teleport could get me out. I did slash kill hoping that it wouldn't take my stuff because of a glitch but it did. It just randomly teleported me into the ground or wall or something I don't know.

**Comment by epicman739** [comment]
Well if you were stuck in the ground with 1 soul point, you should just log off and wait for your soul points to regen before using /kill.
