### ISSUE TITLE
I'm stuck

### ISSUE THREAD

**Issue by DutchGamer349** [Wynncraft/Issues#1683]
I'm stuck in a hole in the pit of the Dead. I jumped in the water and i got teleported under the water
![2015-03-07_17 50 26](https://cloud.githubusercontent.com/assets/11366444/6542199/7c1599fa-c4f2-11e4-98d4-de292d7aa2c3.png)

**Comment by Trixter313** [comment]
Type /kill into chat and you will respawn at the nearest visited town.

**Comment by DutchGamer349** [comment]
Tnx bro
