### ISSUE TITLE
teleport bug that made me die and lose my stuff

### ISSUE THREAD

**Issue by Savage-striker** [Wynncraft/Issues#1685]
i was in the hallowynn masquade cave and when i should have teleported back to the beginning of the parkour, i glitched and fell through the world. due to me not having many soul points left i died and lost all of my weapons, armor, etc. sorry i dont have any pictures of in but i was a little shocked. if someone could get my stuff back i would be a lot happier, but its just the bug that annoys me.

**Comment by epicman739** [comment]
Sorry, no refunds. The bug might be a one-time thing, since nobody else has reported a similar issue. Next time, try not to do anything dangerous when you're low on soul points. Remeber that soul points will regenerate when you're offline.

**Comment by Savage-striker** [comment]
Yeah I kinda expected that. Luckily I've learned from my mistakes and have
gotten myself set back up, as well as gotten backup weapons incase i die
again. I just think it was a bug for teleporting in general, i respawned
before the chunks loaded,and i fell through. The reason i didn't just "do
nothing" while i was low on soul points is because I hate to do nothing on
the server, and I was determined to beat the quest. So thanks for
responding anyways, I feel a lot better that someone actually replied to my
issue. P.S. sorry I didn't respond to your reply I check my email very
rarely.
