### ISSUE TITLE
Guild 100% xp sharing bug!

### ISSUE THREAD

**Issue by Mextrin** [Wynncraft/Issues#1687]
When I'm sharing 100% of my xp with my guild and clear a dungeon worth about 5500 xp, the amount of xp that my guild xp isn't increasing.
Pic 1: Before clearing dungeon
Pic 2: Message when you clear the dungeon (0 xp because I share 100%)
Pic 3: After clearing the dungeon
![2015-03-08_02 26 14](https://cloud.githubusercontent.com/assets/11370687/6544074/06b1e570-c53c-11e4-9069-de4394905b5d.png)
![2015-03-08_02 26 24](https://cloud.githubusercontent.com/assets/11370687/6544075/0c85fb12-c53c-11e4-80bb-e8beb10f55d9.png)
![2015-03-08_02 26 36](https://cloud.githubusercontent.com/assets/11370687/6544076/127a6044-c53c-11e4-9bdb-961f23d74ac0.png)

I guess it is within the dungeon finish part of the code. (Can't find access to the code so I'm only guessing).

**Comment by Trixter313** [comment]
Have you tried waiting a bit to check the guild's xp? It can take a few minutes to even a few hours for the stats to update at times.
