### ISSUE TITLE
Stuck in a black room after picking a new class

### ISSUE THREAD

**Issue by starkiller206** [Wynncraft/Issues#1688]
I was an archer and I have a mage class too so I was going from archer to mage and when I picked mage I was stuck in a black room and could get out I went back to archer and I was still stuck in the room can you please help me 
-Starkiller206

**Comment by starkiller206** [comment]
sorry I mean I couldn't get out as mage or archer

**Comment by P3BBL35** [comment]
Try doing /kill. It'll teleport you to the nearest city, but costing 2 soul points, so make sure you have 3 or more soul points.

**Comment by starkiller206** [comment]
ok thank you so much it worked u da best
