### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by OmegaXelix** [Wynncraft/Issues#1689]
I was doing quest wynnexcavation b and i was going through caves and i grabbed purple cristal.
The cave that teleports you out from dungeon teleported me behend the piston door, and now i cant go out, even teleportation scrolls dont work.
Can a staff member teleport me out or what should i do?

**Comment by Trixter313** [comment]
Type /kill into chat and you will respawn at the nearest visited town. This will take 2 spikiness do make sure you have 3+.

**Comment by OmegaXelix** [comment]
ok thanks
