### ISSUE TITLE
I can not do two quests!

### ISSUE THREAD

**Issue by doriko45** [Wynncraft/Issues#1691]
Hey, my name is Dor Bacal and I am level 49 in your server. I am playing a long time, almost 2 years.

When I have started the quest "WynnExcavation site A", it all glitched out for me. I could start it, but whenever I went talking to Tesha, he told me to get away. I started the quest and the book updated, week after week I am still trying to continue the quest but the same thing happens.
Almost the same thing happened to WynnExcavation site B, but this time, the book tells me I have started the quest but I need to talk to Lykron. He only tells me they have another place of job in Almuj and bluh bluh bluh. I can't even start the quest.

Both of my WynnExcavation sites are not even possible to continue, but it didn't happen to any other quest.
I really want to finish those two but I can't. Is there any way to like reset those two quests? My Minecraft username is doriko45 and this happened in my Warrior class. I hope you can fix this problem as fast as possible. Please email me back or leave a message if you did something about it, my email is dordor61@gmail.com
Thanks for paying attention.

**Comment by epicman739** [comment]
You need to do Wynnexcavation A to do Wynnexcavation B. Are you sure you're following the right steps for Wynnexcavation A?

**Comment by doriko45** [comment]
Yes I am. I watched videos about it but it is not working at all. Tesha is
like telling me to get away...
I come back to him every week but it's not working :(

2015-03-09 6:16 GMT+02:00 epicman739 <notifications@github.com>:
