### ISSUE TITLE
Cannot sign in to Wynncraft

### ISSUE THREAD

**Issue by Xerain** [Wynncraft/Issues#1692]
I cannot sign in, as it says "Unable to find a server to connect to. Please report."

All I do is click Wynncraft to join the server, and that appears.
![2015-03-08_21 30 46](https://cloud.githubusercontent.com/assets/11382122/6548787/fdc1ba40-c5da-11e4-9495-2a1189dd1426.png)

I am hoping it is an update glitch or something of the sort.

**Comment by Xerain** [comment]
Is anyone else getting this?

**Comment by Trixter313** [comment]
I just tried logging on and got the same message, so it's not just you. This message usually appears when maintenance is occurring so just wait a while and try again later.

**Comment by Xerain** [comment]
Ah ok, thanks

**Comment by Xerain** [comment]
Now that I think about it, theres only about 200-300 people on, and its getting lower.

**Comment by Trixter313** [comment]
Yeah, the situation is most likely that people who are already logged on stayed but once they log off they can't log back on.

**Comment by Trixter313** [comment]
The Wynncraft twitter account just tweeted about it

**Comment by Trixter313** [comment]
It should be back up now, "And we're back up now!! Have fun everyone! http://play.wynncraft.com"
