### ISSUE TITLE
Stuck under the shine in the quest 'Pit of the dead'

### ISSUE THREAD

**Issue by greenmind4** [Wynncraft/Issues#1693]
After I did the 2014 Halloween quest (yes, I know I did it late) my hunger glitched out and wouldn't come back. I tried drinking a saturation potion, but that didn't work, so I remembered a quest that I did recently, 'Pit of the dead' and thought that it might fix it. I went in the shrine and got frozen for a minute until I decided to log out and log back in to fix it. First I was stuck directly under the water, then after another log-out-log-in, I was able to move around under the shrine. I tried once more to log-out-log-in, but I was stuck for good. I am hoping that someone could possibly Tp me out, because now I can't play as my most-used class.
Here is a screenshot of where I'm stuck;
![2015-03-09_10 29 36](https://cloud.githubusercontent.com/assets/11394207/6560658/07cb4060-c649-11e4-946f-add2bbbe4b5e.png)

**Comment by greenmind4** [comment]
Never mind. By using my horse, I was able to get out. Still, look into fixing this

**Comment by vogelmet** [comment]
then this happens again somewhere else do /kill but make sure that you have more then 2 soul points
