### ISSUE TITLE
"username" has an invalid spell configuration

### ISSUE THREAD

**Issue by bartoul** [Wynncraft/Issues#1694]
I was farming Trainers at ToL when i saw the spam. 
it kept repeatedly saying someone had an invalid spell configuration in chat.  i took a few screenshots.
(didn't know whether to mark this into bug reports or spam. sorry if its in the wrong place!)
i didn't know if it was actually a bug or if he was just spamming so I'm putting it here.

i did ask him to stop, it just kept going for awhile.  it stopped when i walked out of range of
 the CoW area...

I do not know how to reproduce this issue. ask the guy that did it. (in the screenshot)

![2015-03-10_20 52 44](https://cloud.githubusercontent.com/assets/7854477/6590159/3f12dc24-c769-11e4-946f-5361a9e0d15e.png)
![2015-03-10_20 52 52](https://cloud.githubusercontent.com/assets/7854477/6590160/40acd4ae-c769-11e4-8f3f-94b9f56b3b1b.png)
![2015-03-10_20 54 10](https://cloud.githubusercontent.com/assets/7854477/6590178/660b9b54-c769-11e4-891e-a1d5763df3e8.png)
![2015-03-10_20 54 18](https://cloud.githubusercontent.com/assets/7854477/6590180/69bdeb30-c769-11e4-95d4-fee58ec9772f.png)
![2015-03-10_20 55 40](https://cloud.githubusercontent.com/assets/7854477/6590181/6c557ce6-c769-11e4-82f8-0d15bc8779f1.png)
![2015-03-10_20 56 06](https://cloud.githubusercontent.com/assets/7854477/6590183/6e6385be-c769-11e4-8443-8c1b55ca8a3f.png)

**Comment by epicman739** [comment]
As far as I know, this is not a player issue, but an issue with a mob, similar to the spirit2 problem. It is a known issue and should be fixed soon.
