### ISSUE TITLE
Invalid Spell Config.

### ISSUE THREAD

**Issue by zMisterX** [Wynncraft/Issues#1695]
So when I go to Half moon island to farm emeralds then i go in to the ruins or the building to the left the bug started to appear it says "PFAenara2 has an invalid spell configuration"
![wynn bug](https://cloud.githubusercontent.com/assets/11421947/6594085/ff413b94-c818-11e4-84ec-a9e5283e77e3.PNG)

**Comment by epicman739** [comment]
From what I know, this is an issue with the coding of a certain mob. It should be fixed soon.
