### ISSUE TITLE
Helmet Glitching Screen

### ISSUE THREAD

**Issue by CuteKittyChick** [Wynncraft/Issues#1696]
Hi there is something wrong when I have my lvl 4 unique helmet it acts like I constantly keep joining and joining for some reason I have no idea why it is doing that

**Comment by doriko45** [comment]
If you're using Minecraft 1.8, you need to know that the server uses a 1.8 feature that whenever you put on some armor, it changes your skin (don't worry, it gets deleted after you leave the server but gets back when you join again - also it gets removed when you put off the armor piece). To do so, it has to like kind of re-log you, but not in a way of like kicking you out of the server, it just takes a few seconds and you can see on your skin the armor. So all you need to do is just to stand and not touch anything untill it tells you in chat the server has drawn your armor.

If that's not working, try using 1.7._, but if you're already using it, use 1.8, if doesn't work also then I don't know.

**Comment by CuteKittyChick** [comment]
ty
