### ISSUE TITLE
Colour Error [Reincarnation]

### ISSUE THREAD

**Issue by AckroWynn** [Wynncraft/Issues#1697]
I found a colour code error in the Reincarnation quest, at 12/13 of the first dialogue with Batelu.
![2015-03-11_19 27 34](https://cloud.githubusercontent.com/assets/7467934/6603976/959143e4-c825-11e4-9bd9-9b8769fab3df.png)

**Comment by AckroWynn** [comment]
Fixed

**Comment by Moe-Ronickah** [comment]
There's a difference in that screenshot?  Even with Visolve, I don't see any.  LOL
