### ISSUE TITLE
Item Disappearing(Once logging in to server)

### ISSUE THREAD

**Issue by Hyperion90599** [Wynncraft/Issues#1699]
When I logged into the server, the item I was holding suddenly vanished. The item I was holding was a Detlas Legacy Wand(XP boost, Loot boost, spell dmg boost). Please help I don't know how it actually happened.

**Comment by epicman739** [comment]
Did you accidentaly drop it?

**Comment by Hyperion90599** [comment]
No, I didnt drop it, it was there before i logged out. I am assuming it might be because of server restart.

**Comment by epicman739** [comment]
It could have been a minor rollback. Has anything else (eg exp, inventory, bank) been reset as well?

**Comment by Hyperion90599** [comment]
Chain leggings and sickle got removed i forgot which chain it was but i remember it to be a Rare one
