### ISSUE TITLE
RPG joining Problem

### ISSUE THREAD

**Issue by MrFlamingPyroWire** [Wynncraft/Issues#1701]
![2015-03-12_17 54 09](https://cloud.githubusercontent.com/assets/11448496/6629311/6cb4e516-c8e3-11e4-9fa2-1413a5a4bef2.png)

I tried playing the rpg on wynnraft ad ever time i pick a class it sends me back to the spawn

**Comment by epicman739** [comment]
Have you tried restarting Minecraft, rebooting the internet, or anything?

**Comment by MrFlamingPyroWire** [comment]
Year I have tried that but nothing happens.I feel like I'm banned In a way,but I don't know

**Comment by MrFlamingPyroWire** [comment]
Yea*

**Comment by MrFlamingPyroWire** [comment]
Yea*

**Comment by Xenon2014** [comment]
My brother has the same problem.
Tama closed my thread 13 hours after posting it.

**Comment by Xenon2014** [comment]
MrFlamingPyroWire, do you have a brother/sister who played wynncraft before you?

**Comment by MrFlamingPyroWire** [comment]
Nope,when I first joined with my friends it said the same thing but I thought it would work after a while.
