### ISSUE TITLE
Website not functioning properly

### ISSUE THREAD

**Issue by DaThresh** [Wynncraft/Issues#1702]
I'm on my Mac and I tried loading the website in Opera, Chrome, and Safari and this issue happened every time.  I tried clearing the data for the website and that still didn't fix it.

Issue is:

Banner at the top doesn't work.
Wiki banner doesn't work.
And most of all, the icons like "classes", "item guide", and so on, don't work either, which is frustrating.

![screen shot 2015-03-13 at 10 22 29 am](https://cloud.githubusercontent.com/assets/4720003/6642533/e591281e-c96a-11e4-9351-6e8cc442a433.png)

![screen shot 2015-03-13 at 10 22 54 am](https://cloud.githubusercontent.com/assets/4720003/6642538/efde49d2-c96a-11e4-95fb-10e7166710f7.png)

**Comment by epicman739** [comment]
The icons aren't working for me either. Don't worry, this is probably a temporary thing. If you need info about stuff, just go to wiki.wynncraft.com (the official Wynncraft wiki). Everything is on there.

**Comment by DaThresh** [comment]
Yeah that's what I've been doing in the meantime, thanks!
