### ISSUE TITLE
TP undergrounds

### ISSUE THREAD

**Issue by RHKramer01** [Wynncraft/Issues#1703]
I don't know what I have to do, I logged in on wynncraft I chose my class and suddenly I was into the same chamber as where you have to choose your class but then without torches. I hope a moderator will see this and tp me back above the ground. https://www.youtube.com/watch?v=4g7l1yXYkTk&feature=youtu.be

**Comment by Trixter313** [comment]
Type /kill into chat and you will respawn at the nearest visited town. Make sure you have at least 3 soul points when you do this.
