### ISSUE TITLE
Tomb door in the wrath of the mummy quest not working

### ISSUE THREAD

**Issue by finlayj123** [Wynncraft/Issues#1705]
I was trying to to the wrath of the mummy quest and when i came to the tomb door i had to work out the code which is 63814275 (or so i thought) i put it in, it didnt work so i tried again and it still didnt work so i went to th wiki and searched it up, i had gotten the code right it turned out but the door just wouldent open, i even tried changing servers. please fix this bug asap please thx.
P.S. Sorry for my bad grammar

**Comment by Trixter313** [comment]
Have you tried switching servers? Sometimes it can be just a temporary issue on one server but work on others.

**Comment by finlayj123** [comment]
Hi nick, yes i have tried changing servers but it still the same, I put in
the code stand back and watch nothing happen I've tried putting the code in
backwards, I've tried making one up, I've tried practically everything but
to no avail.
If you know of anything I could do please let me know.

**Comment by Trixter313** [comment]
Yeah, sorry I didn't read it very well the first time. I deleted that post shortly after publishing it because I re-read your post and noticed you said you had already done that. Another person reported the same bug and you two seem to be experiencing the same issues. I will attempt to go to the mummy's tomb and see if I can enter and report back here shortly.

**Comment by finlayj123** [comment]
Ok thanks, im on server 7

**Comment by Trixter313** [comment]
It appears that there are currently issues logging onto the servers so I can't test it right now. Most likely just congestion issues. I'll test as soon as possible.

**Comment by finlayj123** [comment]
I'll be there

**Comment by Trixter313** [comment]
Confirmed also. Most likely just some broken redstone that needs to be repaired.

**Comment by DutchGamer349** [comment]
Same problem here! Still not working...

**Comment by finlayj123** [comment]
Has there been any updates with the door, because I've run out of quests to do XD

**Comment by MCMainiac** [comment]
I'm having this problem too! Please fix it :)

**Comment by finlayj123** [comment]
Its still broken, I just checked. Does anyone have any idea when it will be fixed?

**Comment by finlayj123** [comment]
Still broken... now i have no quests except the tower of ascension which, is the hardest quest in Wynncraft... ;(

**Comment by finlayj123** [comment]
fixed
