### ISSUE TITLE
Spawn zone bug

### ISSUE THREAD

**Issue by RaresCbn** [Wynncraft/Issues#1707]
Hey, I'm one of your server player and I wanted to tell you that I found a bug.
After I select my Archer Class it spawns me in a black room and I can't get out of there. I tried to use the scroll but in doesn't work. With the other classes works and spawns me correctly but when I try to get on my Archer Class spawns me there. Please help me! Thank you!

**Comment by P3BBL35** [comment]
Try doing /kill. It'll cost 2 soul points, but it will teleport you to the nearest city.

**Comment by RaresCbn** [comment]
It worked thanksSent from Yahoo Mail for iPadAt 15 mar. 2015, 16:06:15, P3BBL35 wrote:Try doing /kill. It'll cost 2 soul points, but it will teleport you to the nearest city.
