### ISSUE TITLE
Abysso Galoshes missing

### ISSUE THREAD

**Issue by Louis-D** [Wynncraft/Issues#1708]
Im doing the "Lost Soles" quest but I don't have the Abysso Galoshes which you are supposed to get in the quest "Beneath the Depths" which I did. But I don't have the boots in my bank, inventory... I checked to other classes too, but they don't have them either... And /fixquests doesn't work. :(

Also: Why do I have to redo the quest "Tribal Agression" I did this one 2 months ago...

**Comment by epicman739** [comment]
Are you sure you didn't throw the Abysso Galoshes away? I know some people did.
Also /fixquests is still really buggy and partially broken.
