### ISSUE TITLE
Connection to Server.

### ISSUE THREAD

**Issue by Boltrax** [Wynncraft/Issues#1710]
I can't connect to the server, I live in New Zealand but I have already played on it the last two days what do I do?

**Comment by Trixter313** [comment]
Have you tried to restart your router and/or your computer?

**Comment by Boltrax** [comment]
Yes both.

**Comment by Boltrax** [comment]
All it does is say Cannot Connect to Server

**Comment by Boltrax** [comment]
Please someone help me please.
