### ISSUE TITLE
I did a dungeon and I didn't get the key

### ISSUE THREAD

**Issue by Squaker** [Wynncraft/Issues#1716]
So I finished up the Animal dungeon, and after completing it on my own I never ended up getting any key/keys for my next dungeon, even though in chat it was specified that I would get a "Zombie Key". I do have a picture to support my fact, but I am just really confused of why this happened. I ended up searching all around the area to find the key, but I still couldn't find it. Can you please fix this bug?
![i never got the key](https://cloud.githubusercontent.com/assets/11524910/6692790/48db5a88-cca5-11e4-9131-8a0999e45cc4.PNG)
![i never got the key 2](https://cloud.githubusercontent.com/assets/11524910/6692794/4dbc11e6-cca5-11e4-9413-da3772f52af7.PNG)

**Comment by P3BBL35** [comment]
It's probably due to the fact that you finished it with a full inventory.
