### ISSUE TITLE
Bug About Guilds

### ISSUE THREAD

**Issue by BlooDragoN0907** [Wynncraft/Issues#1717]
Hey Wynncraft's owners and admins
I am writing to tell you guys about the guilds. my friend created the guild but it says he is not the guild captain and the guilds name is [DXR] but it shows his bar as [DDM] his old guild and my bar show [DRX] when he tried to promote me it says he ''you need to be a captain to do this'' pls help us as we worked hard for the 5LE that is needed to create the guild my in game name is BlooDragoN0907 and my friends is Darren2211

**Comment by Trixter313** [comment]
Usually issues like these are resolved just by waiting. See if the issue is still occurring a few hours from now. It usually just takes some time for the server to update with the right information.
