### ISSUE TITLE
Useless Emeralds

### ISSUE THREAD

**Issue by Tagudin** [Wynncraft/Issues#1718]
There is bug where I have useless emeralds(I dont know if people have this issue too)When old wynncraft players log back in the new update(s) they have useless emeralds due to having different names and discription(the new emerald names are in green and have a discription of how much they are worth)While the "old" emeralds have default names and no description resulting in them being useless due to the curreny names and discription not matching the NPCs.

**Comment by Trixter313** [comment]
To convert your old emerald blocks to the new emerald blocks, log onto Wynncraft using 1.7.10 and trade them with the emerald merchants at banks to get the new type of emerald. For any spare emeralds that are less than 64, theres nothing you can do.
