### ISSUE TITLE
Not owner of my guild

### ISSUE THREAD

**Issue by ShardoWynn** [Wynncraft/Issues#1721]
Guilds were brought back up after they were disabled for two days, now I don't own my guild after it came back up, and there is no one owning it, but my friends own there guilds and have commands still
![bug issue](https://cloud.githubusercontent.com/assets/11564079/6762473/454599da-cf37-11e4-820e-4c38678850fb.png)

My guild is Black Fangs, I changed my name a few weeks ago from MightyMrDude to Shardo
My Username is Shardo

**Comment by epicman739** [comment]
Name changes are known to affect guild mechanics.

**Comment by ShardoWynn** [comment]
Yes, but is the staff going to help fix this is what i'm trying to ask

**Comment by epicman739** [comment]
I'm sure the staff is working on a patch, just be patient in the meantime.
