### ISSUE TITLE
WynnExcavation Site B - Yellow Crystal Shard

### ISSUE THREAD

**Issue by xEvah** [Wynncraft/Issues#1722]
So, I've completed the WynnExcavation Site A quest, so that means I have earned the Yellow Crystal Shard. But I randomly lost it. I thought I could just kill Pharaoh Nabak again, but then, you earn a Yellow Crystal (so without Shard, hehe). I want to Excavator Lykron with this, held it in my hand, and clicked on Lykron to start the quest, but it wouldn't start. 
I don't know how I could've lost the Yellow Crystal Shard, because I can't remember that I threw it out of my inventory, and it isn't in my bank either. 
Can anybody help me with this?

**Comment by epicman739** [comment]
/fixquests should give your Yellow Crystal Shard back, but it might not work.

**Comment by xEvah** [comment]
Thanks so much! It worked :)
