### ISSUE TITLE
I can't regenerate hunger.

### ISSUE THREAD

**Issue by BCaptain** [Wynncraft/Issues#1723]
My in game name is CommanderFives and I can't regenerate hunger please help me

**Comment by BCaptain** [comment]
Oh and I'm at zero hunger

**Comment by BCaptain** [comment]
I tried /kill but I just can't stop degenerating hunger it just goes down to 0 please help

**Comment by epicman739** [comment]
Have you tried relogging, restarting, etc? Usually that helps.

**Comment by BCaptain** [comment]
I fixed the issue
