### ISSUE TITLE
Guild without a leader

### ISSUE THREAD

**Issue by C-O-O-K-I-E** [Wynncraft/Issues#1724]
I logged in today (21/3/15) and i was no longer the leader of my guild Silver Dragon. I checked the guild list on the wynncraft website and it says there is 'No Owner Found'.
![silver dragon](https://cloud.githubusercontent.com/assets/11579530/6762365/b43ce744-cfc3-11e4-9b4b-7bfa404c3185.png)

If you could fix this issue so I am the leader of my guild again that would be great thanks ;) My username is C_O_O_K_I_E.

Something else I noticed was the /guild list was taking a few hours to update... just thought i'd let you know- It doesn't stop the guild from leveling up it just takes a long to for the exp to appear.

**Comment by epicman739** [comment]
Did you change your username? That is known to cause some bugs with guilds.
