### ISSUE TITLE
My Old Emeralds and Emerald Blocks don't work.

### ISSUE THREAD

**Issue by Danielskyj** [Wynncraft/Issues#1725]
My old currency I had achieved a while ago and put in the BANK no longer is useable, because they do not have the pre set Green name with the lore line, please help.

**Comment by Trixter313** [comment]
Log onto Wynncraft using 1.7.10 and trade your emerald blocks with the emerald merchants to convert them to the new emeralds.

**Comment by Danielskyj** [comment]
Thanks!!
