### ISSUE TITLE
Lost my Blue Mask due to trading

### ISSUE THREAD

**Issue by Thaunceil** [Wynncraft/Issues#1727]
I was show N1njap3rs0n my Blue Mask IDs and my inventory had one slot in it and he threw rotten flesh at me while I was showing him my IDs with /trade. Then when the trade ended... I did not get my blue mask because he had thrown rotten flesh at me and I had no space to get it back, I think it should have at least dropped on the ground or something. I would really like a clean one back. Mine had really good IDs on it and I would just love to have it back.

**Comment by epicman739** [comment]
Sorry, Wynncraft has a no refunds policy.
Next time, be really careful with trading, some actions can lead to loss of items.
