### ISSUE TITLE
-label:bug No Hunger Glitch

### ISSUE THREAD

**Issue by Tagudin** [Wynncraft/Issues#1728]
For some reason, when I equip an identified item, i get 0 hunger having to forced to die to regain back the hunger, but most of the time i usually have to die 2 times to fix the thing trashing away 4 soul points.
This also happens when my friend connects to the server, randomly.Even mana potions(potions that give the saturation effect) are useless.

**Comment by Trixter313** [comment]
Usually the issue only occurs on one server so switching servers should resolve the problem.
