### ISSUE TITLE
Silverfish Dungeon Door Glitch

### ISSUE THREAD

**Issue by LethosX** [Wynncraft/Issues#1733]
Dear Wynncraft Team,
       I, LethosX, was playing Wynncraft with my party. We were trying to beat the Silverfish Dungeon. So, once I got to the boss room, I pressed the button, and suddenly, I was pulled into the redstone wiring of the door, also, whenever I tried to beat the dungeon again, the door kept pulling me in to the wiring. I hope you guys can fix this, a few of my friends have also found this problem. That is all, thank you for you time!
                                                                                                                            LethosX

**Comment by epicman739** [comment]
So every time you go press the button, you're glitched into the redstone wiring?
