### ISSUE TITLE
can't sign into any servers

### ISSUE THREAD

**Issue by Bostonfan3334** [Wynncraft/Issues#1734]
I'm having a very big issue :P i really would like to play the server. I can log into any lobby and i can log into any server but when i get into the black wool box and the classes come up and i select a class i would like to play it then disconnects and says "there has been an error. Please log back in"

**Comment by Trixter313** [comment]
Type /kill into chat and you should respawn at the closest town.

**Comment by Bostonfan3334** [comment]
i can not use commands in that wool box

**Comment by 00jammin** [comment]
Ive been having the same problem and yeah you cant even get past the class selection, you get sent back to the Hub
