### ISSUE TITLE
My warrior are block.

### ISSUE THREAD

**Issue by Nolmin02** [Wynncraft/Issues#1735]
When i join the wynncraft server with my Warrior class i am block at the place where the class is chosen
and the /kill don't work pls can someone help me :'(

**Comment by Nolmin02** [comment]
nobody ;(

**Comment by SkySaito** [comment]
Try another class ?

**Comment by Nolmin02** [comment]
other class work but i want play with my warrior he is lvl 54

**Comment by Nolmin02** [comment]
the /kill work again it's now done
