### ISSUE TITLE
Shears and Mooshrooms

### ISSUE THREAD

**Issue by SkySaito** [Wynncraft/Issues#1737]
Hello there !
As the title say, I've found a bug about these two things. When you right click on a Mooshroom with the shears (like when you do a spell near them), it make them disappearing. Just like that.
So since a bug, I'm telling you this. 
Thanks for reading !

**Comment by epicman739** [comment]
Is this only with shears?

**Comment by Trixter313** [comment]
This happens because when you shear mooshrooms they turn into normal cows. This was fixed before but must have been broken in a later update. Hopefully it can easily be fixed again.
