### ISSUE TITLE
Wolf Fang not Wolf's Fang

### ISSUE THREAD

**Issue by DragonSamot100** [Wynncraft/Issues#1738]
So I farmed up a bunch of wolves collecting fangs to buy myself some Tribal Armor. But when I went to buy it in Bremmiglar I was not able to. The Armor NPC in Bremminglar requires 4 "Wolf's Fang" for each piece of armor, but the wolves in Neesak drop "Wolf Fang," which cannot be traded to the NPC.

**Comment by epicman739** [comment]
Try using 1.7.10 if you're using 1.8. 1.8 trading checks for name as well as item ID, but 1.7.10 does not.

**Comment by Adrilidexus** [comment]
Issue still exists, tested in 1.8, 1.11, and 1.12.1
25 "Wolf's Fangs" cannot be traded for emeralds. Only have one "Wolf Fang". Merchant does not recognize the quartz as being a fang.

Was there ever a way to convert broken items?
