### ISSUE TITLE
Help me Im Stuck underground in a dark box

### ISSUE THREAD

**Issue by Treecko814** [Wynncraft/Issues#1742]
My IGN is Treecko814, and I just logged onto my account, and I'm stuck below Detlas in a dark box, and can not get out. It'd be great if you could help. There were also other people stuck down their, and they couldn't get out. I think its a glitch. Thank you for your help!

**Comment by Trixter313** [comment]
Have you tried typing /kill into chat?

**Comment by Treecko814** [comment]
^I did and it worked thanks

**Comment by Piggypotato78** [comment]
OMG, that is the answer to my question too, I got stuck in a dark box when teleporting in Craftmas Chaos thank you!
