### ISSUE TITLE
(Relics)Relic Dagger not being identified 

### ISSUE THREAD

**Issue by kingsknight9** [Wynncraft/Issues#1743]
The Relic Daggers cannot be identrified.

![2015-03-27_22 34 52](https://cloud.githubusercontent.com/assets/8338592/6879701/9619da48-d4d1-11e4-9834-45444a08546e.png)

![2015-03-27_22 35 09](https://cloud.githubusercontent.com/assets/8338592/6879702/98b40936-d4d1-11e4-89cf-4f687229c4a4.png)

**Comment by SkySaito** [comment]
That's normal, they still not have ID. Wait a later update.
