### ISSUE TITLE
Tower of ascension

### ISSUE THREAD

**Issue by minimand** [Wynncraft/Issues#1746]
When entering the ice part of the tower of ascension (level 40-50) I get to kill sheep! Yay! I then kill 10 of those, hand in the things I get from them aaand nothing happens. I don't know if it's a bug or if I'm just stupid >_> but I've tried going in there 2-3 times and I get stuck every time.

In game name is minimand111 or you can catch me on ts if I'm on.

**Comment by Trixter313** [comment]
I believe the tower is currently having issues. Should be fixed "soon"
