### ISSUE TITLE
All servers are full...

### ISSUE THREAD

**Issue by anthonycreeperk** [Wynncraft/Issues#1747]
I logged on to my account and found out that every server is full. Well that is what is says on the server , yet the signs say there are a lot of slots to join. What I am saying is that all servers appear to be full even when they are not , meaning non of us can play on any of the servers. I have not been informed that you are trying to fix there server or anything . If so , please do inform me.

**Comment by epicman739** [comment]
Have you tried relogging or restarting? Sometimes that fixes these things.
