### ISSUE TITLE
Links on the webpage

### ISSUE THREAD

**Issue by minimand** [Wynncraft/Issues#1748]
First link is to your teamspeak. I still leads to your old ts voice.craftedcloud.com and it doesn't try to open ts. I don't know if the not opening teamspeak is a problem only I am having but the main problem is that it's linked to your old ts that doesn't exist anymore. 

The next few links are your help links (click help at the top and you'll get to them) Almost none of them works! For me it's only 2 of them that does something, one is map that leads to the map, the other is start guide that leads to a 404. 

Everything else seems to work properly :)

My in-game name is minimand111, or your can catch me on teamspeak if I'm online.

**Comment by epicman739** [comment]
Most of the links are broken right now, I'm sure they're working on a fix.
If you need information about anything in Wynncraft, just use the Wynncraft wiki at http://wiki.wynncraft.com
