### ISSUE TITLE
I'm stuck in the starting box

### ISSUE THREAD

**Issue by Alexamder52** [Wynncraft/Issues#1749]
When i start playing, everything is normal. I choose my archer kit, and then i get all my items, but i don't get teleported to my last spot where i was before. I can't use a teleportation scroll, my horse doesn't want to come out and i can barely see anything. this only happens when i use my archer kit. Please fix this issue.

**Comment by Trixter313** [comment]
Have you tried typing /kill into chat?

**Comment by Alexamder52** [comment]
no... what does it do?

**Comment by Trixter313** [comment]
You will respawn at the nearest visited town.

**Comment by Alexamder52** [comment]
omg thanks so much
