### ISSUE TITLE
Teleportaion not working in Craftmas Chaos

### ISSUE THREAD

**Issue by Piggypotato78** [Wynncraft/Issues#1752]
I was walking through the fireplace like Santa said but then while i was teleporting it stopped and i got stuck in a block FOREVER, please help, my minecraft username is Piggypotato78 teleport me out of something, but I can't play as my warrior until it is released, and its my favorite class.

**Comment by Trixter313** [comment]
Type /kill into chat and you will respawn at the nearest visited town.

**Comment by epicman739** [comment]
Repost of #1751
