### ISSUE TITLE
Spawning in a wrong/bad place

### ISSUE THREAD

**Issue by ReapRays** [Wynncraft/Issues#1753]
I was an archer as i died to a Snow Golem just outside of Elkurn (which i had entered). After i died, i spawned in a place In Elkurn but i can't see because i suffocate (without taking damage). I took the co-ords and went there as a Warrior. Then i realised that i was stuck under the house of Elkurn.
![2015-03-29_20 05 28](https://cloud.githubusercontent.com/assets/11703722/6884451/c0ddf6ae-d64f-11e4-8c0b-67575e3c18b9.png)
![2015-03-29_20 05 47](https://cloud.githubusercontent.com/assets/11703722/6884452/c1f542ae-d64f-11e4-9898-7b846cac85f1.png)

**Comment by ReapRays** [comment]
Please could i be teleported or brought out of the ground because i want to use my archer ALOT!

**Comment by ThunderRemix** [comment]
TP Scrolls or /kill if you have 3 or more soul points
