### ISSUE TITLE
Issues that made me rage for like 1 year 

### ISSUE THREAD

**Issue by TCT2K2** [Wynncraft/Issues#1754]
Wynncraft was once my favorite server i had everything lvl 75 vip played on archer on a sad sad day i was grinding in TOL and i had about 9 Soul Points and i died because i was doing something so when i spawned i looked in my inv and i had nothing when i had 7 soul points left so i tried relogging and  i did not have anything if this is a issues can i atleast get my bobs bow back then ill grind the rest.

Your Sincerely

TomGaming_ (TCT2K2)

**Comment by slendersir739** [comment]
Screenshot proof?

**Comment by Jamdog** [comment]
**Player IGN:** TomGaming_
Screenshot proof isn't necessary, and could be too easily faked... Moderators and Admins are able to see any players' inventory/bank anyway.  I can confirm that TomGaming_ has no legendary items at all, although he has retained his Climbing Helmet, Breathing Helmet and Helmet of Legends (presumably in the bank at the time).

Unfortunately, Wynncraft has a strict no refunds policy.  I know that this isn't what you want to hear, Tom, but it's the same for everyone.  Any lost items are gone for good.  You do have 5 other classes available though, and could regain your lost items by playing those classes (except the Mythic Bow, of course).
