### ISSUE TITLE
Trapped in class selector

### ISSUE THREAD

**Issue by Tpg6** [Wynncraft/Issues#1757]
when i change my class to the assassin in the class selector it for some reason it does not teleport me and instead leaves me trapped in a black wool box with no way to leave. i don't really know what caused this to start happening although it could be to do with me changing my name or not playing for a while. The class selector works for all my other classes, just not assassin (i have tried different servers / reloging). my IGN is Tpg

**Comment by Trixter313** [comment]
Try typing /kill into chat with 3+ soul points.

**Comment by Tpg6** [comment]
worked thanks
