### ISSUE TITLE
I am Stuck in The Void

### ISSUE THREAD

**Issue by ATheNarwhal** [Wynncraft/Issues#1758]
I was going into the Silverfish dungeon boss when I went through I fell through to the void. I couldn't die, I was at 1 heart but I kept regenerating it. I don't know if this is supposed to happen... Its on my Archer and I couldn't move or use magic to get out. I don't know what to do so ya... ^-^ narwhal need help.
My Minecraft username is A_The_Narwhal

**Comment by Jamdog** [comment]
Simply type **/kill**
This will cost you a couple of Soul Points, but as long as you have 3 or more, it will teleport you safely to the nearest city.  If you have less than 3 SP, then using /kill would cost you everything in your inventory.  In this case, stay logged out for a few hours, and you should gain SP while offline, then use the /kill command when your SP has gone back over 3.

**Comment by ATheNarwhal** [comment]
Thx! :) 
Just have to do the dungeon over again :-/
