### ISSUE TITLE
Stucked in a block.

### ISSUE THREAD

**Issue by ichigodt** [Wynncraft/Issues#1759]
So I've taked purple crystal scraps in the cave for the quest wynnexcavation B, and i've take the teleporter . But i've been teleporter in a block, coordinates 58 61 -530 . I don't know where I am, but I'm stucked in a dirt block from head to feets . Can you help me ?

**Comment by Trixter313** [comment]
Type /kill into chat with 3+ soul points and you will respawn at the nearest visited town.

**Comment by ichigodt** [comment]
Thanks  !
