### ISSUE TITLE
Name Changing issue

### ISSUE THREAD

**Issue by megaxlr** [Wynncraft/Issues#1760]
I lost my VIP Perks in the Main lobby after I changed the capitalisation of my IGN. The perks still aply in-game.

I lost control over my guild aswell. The guild is Oxygenclan. It tells my in the Player menu that I am offline. When I attack an area It tells me there is nobody to start  the war (I am in the area though). 

Old IGN: megaxlr
IGN: MegaXLR

**Comment by epicman739** [comment]
These are both known issues with name changes, a patch is currently in progress and should be released soon.
