### ISSUE TITLE
I am Trapped in a Black Box

### ISSUE THREAD

**Issue by Foobnoob** [Wynncraft/Issues#1763]
When I log into any server and then pick either my archer or my assassin (my favourite characters), my character instantly gets teleported into a black box
![2015-04-01_10 58 26](https://cloud.githubusercontent.com/assets/11752361/6938920/61b5e54e-d85f-11e4-8cd2-65b4fba3c264.png)

You can see in the picture below that I am most probably in the starting zone as there is a caravan driver, an armour seller and tons of chickens.
![2015-04-01_11 11 00](https://cloud.githubusercontent.com/assets/11752361/6938963/cd0bf860-d85f-11e4-98aa-43579d0f2692.png)

**Comment by SkySaito** [comment]
Do /kill with at least 3 soulpoint. You'll be teleported to the nearest city.

**Comment by Foobnoob** [comment]
Thankyou!
