### ISSUE TITLE
Start Guide, Classes, Commands, Loot etc. isn´t working on the Wynncraft homepage

### ISSUE THREAD

**Issue by Huhn360** [Wynncraft/Issues#1764]
I want to see which indentifies some items have... so i went to the wynncraft homepage and clicked on the item guide... but nothing happend! Then I tried to open the Start Guide, the Classes, the Commands and they all aren´t working except for the map! The Map ist still working.
Do you have the same problem? I use firefox as browser but i tried to open it in the internet explorer and it doesn´t work too....

![wynncraft_homepage](https://cloud.githubusercontent.com/assets/11507196/6943008/823ba1c4-d88b-11e4-992d-18128fa70fd4.PNG)

Sorry for my englisch. It isn´t my native language.

**Comment by SkySaito** [comment]
Doesn't work for me too on Google Chrome. Maybe April Fools ?

**Comment by Huhn360** [comment]
That can't be an April fool because I have had this problem since started again playing at wynncraft and this is 2 weeks ago... :/

**Comment by epicman739** [comment]
The Wynncraft site is currently broken. However, there are other resources you can consult.
General Information: Wynncraft wiki at https://wiki.wynncraft.com/
Identification Stats: Jamdoggy's site at http://stefancole.com/Wynn/Items/ or Dakota's site at http://katoa.ca/wynncraft/items/
