### ISSUE TITLE
Getting Stuck When Teleporting

### ISSUE THREAD

**Issue by KingCharlie** [Wynncraft/Issues#1765]
I was doing the quest Craftmas Chaos and got stuck while I was teleporting into the cave from selchars past. I don't know why and I can sort of cast spells and shoot my bow and it  sounds like it's hitting a wall but I can't really move. I've teleported before so I don't know if this glitch is specific to craftmas Chaos or just really rare. if it's really rare and lag related if someone could TP me back to the cave and I can just go throughout again and pretend this never happened. I will take some screen shots to show myself casting spells, getting speed boost from the escape spell and such right here:
![screen shot 2015-04-01 at 6 26 44 pm](https://cloud.githubusercontent.com/assets/11762218/6954153/c55a055c-d89c-11e4-858a-71b36e69af56.png)
![screen shot 2015-04-01 at 6 26 49 pm](https://cloud.githubusercontent.com/assets/11762218/6954155/cc5a5f5a-d89c-11e4-9bbd-f3fdba9281a7.png)
![screen shot 2015-04-01 at 6 26 55 pm](https://cloud.githubusercontent.com/assets/11762218/6954157/d0a8f5f8-d89c-11e4-99e5-b930d732c32e.png)

**Comment by KingCharlie** [comment]
Please help me I love the server and am bored already!

**Comment by KingCharlie** [comment]
Also I forgot to say I tried using scrolls and none of them worked.

**Comment by epicman739** [comment]
Do /kill if you have at least 3 soul points.
