### ISSUE TITLE
Arrows stuck in ender chest

### ISSUE THREAD

**Issue by Flamspur** [Wynncraft/Issues#1766]
I'm a vip+ so my ender chest is double size - when I go into it (since i first joined the server) there are like 4 stack of arrows placed around the chest that I cannot move or take. (i have all my stuff around it) I thought this was normal and basically didn't think about it until my friend said his wasn't like that. 
![rsz_1nugget](https://cloud.githubusercontent.com/assets/11778770/6976240/cd953970-d974-11e4-91c8-c4da7cb9217b.jpg)

**Comment by gerlove** [comment]
I have that too!
