### ISSUE TITLE
Im stuck in the floor of Lusuco

### ISSUE THREAD

**Issue by Omekaox** [Wynncraft/Issues#1769]
As I was playing normally in Wynncraft as kit archer, I went to the tower of ascension as I was clearing the 1st floor I killed myself so I can return to Lusuco. When I respawn in Lusuco I get stuck in the floor. Its been a day now and im still stuck. I ask for staff or help and nobody listen so this is why im sending you this email so u can help me out on this situation. By the way my username is Omekaox_XZ if u don't know my minecraft username.

**Comment by Trixter313** [comment]
Have you tried using teleport scrolls or killing yourself again?

**Comment by Omekaox** [comment]
Teleportation scrolls don't work and I cant kill myself cause im stuck

**Comment by Omekaox** [comment]
Thank you so much for your help. I could not kill myself cause of the lag

**Comment by Trixter313** [comment]
It also might have been because of your agility but you're saying it's
fixed now? :)

**Comment by Omekaox** [comment]
Yes.
