### ISSUE TITLE
Looking for Irt

### ISSUE THREAD

**Issue by Redpanda382** [Wynncraft/Issues#1770]
I just wanted to point out that I was doing a quest called Drought Sand in Almuj and it said to talk to Irt. The MPC told me he lived on the east side of town, after a while of searching I gave up and went to look on the wiki. Here it said her lived on the south side of town! This is where I found him. I don't know if you can change what the MPC Chilye says to people but it is confusing. Also someone might not have access to the wiki and it would be very hard for them to complete the quest. I hope you take this into consideration. Thanks.

**Comment by Jamdog** [comment]
Thanks for the bug report.  I have just updated this in the quest files, so he will say 'south of the town' after the next live-server update
