### ISSUE TITLE
my guild cant attack 

### ISSUE THREAD

**Issue by mcgamer751** [Wynncraft/Issues#1771]
i keep attacking places on the wynncraft map HOWEVER while it will start the count down even when i have my whole guild in the right place on the same server it says "no one logged in for the attack" my guild is only me and one other for the time being however it is still a pain idk how to fix it or if im doing something wrong my guild name is Black Ducks my user name is mcgamer751 if any one can help me fix this it would be great

**Comment by Masterhand99** [comment]
Im a new member of your Guilde and i have to tell you something...

Shay from the guild SVS wants to talk with you.

MFG Masterhand99
