### ISSUE TITLE
Can get in the chest in Almuj Bank without being level 30!

### ISSUE THREAD

**Issue by lordofdenmark** [Wynncraft/Issues#1773]
I found out that you could get to the back of Almuj Bank and get in the chest as you can see below
![2015-04-04_18 29 09 - kopi](https://cloud.githubusercontent.com/assets/6604816/6993608/227fae3a-dafa-11e4-91e3-5f3626c86315.png)
![2015-04-04_18 29 09](https://cloud.githubusercontent.com/assets/6604816/6993610/22826f76-dafa-11e4-814e-91e582848a97.png)
![2015-04-04_18 29 13 - kopi](https://cloud.githubusercontent.com/assets/6604816/6993609/228230a6-dafa-11e4-87b9-4fbe457557ca.png)
![2015-04-04_18 29 13](https://cloud.githubusercontent.com/assets/6604816/6993611/2284c3b6-dafa-11e4-94f3-aa8d130876a2.png)
![2015-04-04_18 29 18 - kopi](https://cloud.githubusercontent.com/assets/6604816/6993613/22a54140-dafa-11e4-958d-d609ce9d14ff.png)
![2015-04-04_18 29 18](https://cloud.githubusercontent.com/assets/6604816/6993612/22a51ec2-dafa-11e4-8ddf-aff3539eddd4.png)
![2015-04-04_18 29 24](https://cloud.githubusercontent.com/assets/6604816/6993615/22a66f8e-dafa-11e4-9514-accddd63bbf5.png)
![2015-04-04_18 29 28](https://cloud.githubusercontent.com/assets/6604816/6993614/22a63d34-dafa-11e4-9dfa-0d6a213589b3.png)
![2015-04-04_18 29 40](https://cloud.githubusercontent.com/assets/6604816/6993616/22bd404c-dafa-11e4-9bd6-704e48788ad0.png)

**Comment by AckroWynn** [comment]
I will discuss a possible change in the design of the bank walls with Grian in order to prevent this.
Thanks for noticing this!
