### ISSUE TITLE
Tower of Ascension Teleportation problem

### ISSUE THREAD

**Issue by Staraptia** [Wynncraft/Issues#1774]
When I gather 10 shards for a floor and hand them to the Npc and try to teleport to the other floor by standing behind him, I don't teleport. Only rarely after a couple relogs and retries does it teleport me.
It's a really frustrating problem for me because it makes getting to the next floor so much harder.

**Comment by Trixter313** [comment]
Relogging probably help because when you log in it's a block or 2 higher than where you logged in at and I've noticed that if you jump at the teleportation area (especially with jump boost) it will eventually teleport you.
