### ISSUE TITLE
Spider Dungeon Boss Not Working

### ISSUE THREAD

**Issue by Ghost88788** [Wynncraft/Issues#1778]
One problem, rest is fine. Whats fine is everything but one thing. I hit her with Mulithit (Assassin Class) and she went pretty far. Far enough to where I couldn't see her, so I climbed high ground and jump off hopefully finding her. Then, as soon as I jumped off, she spawned webs, making me stuck in air. Finally finding her and then I got kicked out saying "Flying isn't allowed". I understand if you can't fix it, but at least I want my Spider Dungeon Key Back!

**Comment by Ghost88788** [comment]
I still have 1 more spider key right now

**Comment by Ghost88788** [comment]
Going to fight her again and hoping not to get kick for no reason and losing my loot, xp, and my fight

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strict no refund policy but luckily it shouldn't be that hard to get another. I would log on and give you another key but I'm on vacation right now... Sorry. I can give you one on the 7th or 8th of April if you'd like though =)

**Comment by Ghost88788** [comment]
Ty Trixter
and now for some reason, that when I get on my assassin class, I spawn in a dark box.

**Comment by Ghost88788** [comment]
nvm mind about stuck in box. After 3rd /kill, it worked.

**Comment by Ghost88788** [comment]
ok, since you've going to give me a Spider Key, Im guessing your name on WynnCraft is Trixter313 correct?

**Comment by Trixter313** [comment]
That's correct. Once I get home from my flight I'll try to log on and see if you're online.

**Comment by Ghost88788** [comment]
Ghost88788 is my name on Wynncraft too btw

**Comment by Ghost88788** [comment]
Um, I have another issue

**Comment by Ghost88788** [comment]
Lava Cow Infinite Respawns

**Comment by Ghost88788** [comment]
Once I get him 50% or lower on health, he just vanish and respawns a new one

**Comment by Ghost88788** [comment]
IDK what

**Comment by Ghost88788** [comment]
Mission pops up, Kill 14 LAVA COWS for 14 emeralds. Lol

**Comment by Ghost88788** [comment]
hmmm..... Tryed to fight again, Lava Cow used a respawn... Then while his second life was still alive, I beat the  dungeon...How did I beat without killing? Eh, combine the damage of the two Lava Cows the battled with equal to one normal Lava Cow Death.

**Comment by epicman739** [comment]
If you have another issue, please post a seperate bug report.

**Comment by Ghost88788** [comment]
k
