### ISSUE TITLE
Guild attacks not working

### ISSUE THREAD

**Issue by KingCharlie** [Wynncraft/Issues#1779]
I don't have any screen shots for this but my guild hasn't been able to attack recently because even though all of us are there, it says that no one is. I don't know if we are doing it wrong but I don't think so because we used to be able to do it fine! Also on a side note I tried to start an attack as chief and captain but It said I couldn't because "I wasn't captain" but that might of been it updating since I had just been promoted like 30 seconds ago. I got demoted again so I haven't been able to get screen shots or try at all since.

**Comment by NinjaElfBoy** [comment]
The same thing is happening to me. I hope someone can fix this glitch soon D:
