### ISSUE TITLE
Relic Daggers not indentifiable

### ISSUE THREAD

**Issue by DerpKingShay** [Wynncraft/Issues#1784]
I tried to identify my relic daggers, but the identifier just said, 'I can't identify that item! I can only identify... blah blah blah"
![2015-04-06_19 53 26](https://cloud.githubusercontent.com/assets/11828532/7016593/4c6051ca-dc9c-11e4-825b-6c8af522a8cb.png)
My username is ShayRide
Thank you

**Comment by epicman739** [comment]
Known issue, none of the Relic items have identifications yet. They will in a future update.

**Comment by DerpKingShay** [comment]
But I tried identifying one of my other relic weapons, and it worked.

**Comment by epicman739** [comment]
So it's just the dagger then? Have you tried getting another dagger and identifying it? If that still doesn't work, perhaps it's just the daggers that don't have IDs yet.

**Comment by Jamdog** [comment]
I've just looked in the identification data file, and the Relic Daggers are there - the (average) ID stats should be:
  Spell Damage: 1
  Mana Steal: 1
  XP Bonus: 31.0
  Loot Bonus: 24.0

I can't immediately see any errors in the file that might prevent it from working with this one item, but I'll try to get in-game later on today and test this...  I'll report back here.

**Comment by DerpKingShay** [comment]
I've tried many things.
I went to the Almuj, Detlas Troms, Emerald Trail, Nemract, most of the identifiers, they all don't let me identify it. I've tried to identify a different relic daggers, but that didn't work either.

**Comment by Tama63** [comment]
Merging with #1312
