### ISSUE TITLE
Item Bomb Not letting me collect items

### ISSUE THREAD

**Issue by IsraphelHunter** [Wynncraft/Issues#1787]
Recently I had just purchased 100 GC From the store for $5:00. I thought it would be cool to see what i would get from an item bomb so i bought 2. When i got them the first 1 I opened it in a very small place and it wouldn't let me pick up items. I thought they glitched out so i couldn't pick them up. The second one i opened in a big area and it still wouldn't let me open it up. If this is a bug please help fix this but if it isnt, Would i be able to get my GC Back because you didnt specify that you cant pick up items in an item bomb. Please help ASAP
~ _IsraphelHunter_

**Comment by HeadsetO** [comment]
Items dropped by an item bomb are not meant to be picked up by the player that used the bomb, it is meant as small gift to nearby players. You can check that here:
https://forums.wynncraft.com/threads/announcing-the-new-wynncraft-store.46818/

**Comment by IsraphelHunter** [comment]
Nothing was said when i purchased it that i cant pic it up myself

**Comment by Tama63** [comment]
"
Gift Bombs

Share a little something with other players."
