### ISSUE TITLE
Item Statistics Not Adding to Correct Total

### ISSUE THREAD

**Issue by Snipinginunition** [Wynncraft/Issues#1788]
When using items, my compass is not showing the correct amount of experience and loot bonus that I should be getting. I am not sure if it is just a visual glitch, or if i am not receiving the amount I should be.
![2015-04-07_16 47 05](https://cloud.githubusercontent.com/assets/11842428/7033278/03edb4f4-dd47-11e4-9a8f-4df7fa215f66.png)
![2015-04-07_16 46 54](https://cloud.githubusercontent.com/assets/11842428/7033280/03ef0336-dd47-11e4-948c-33406b406281.png)
![2015-04-07_16 46 56](https://cloud.githubusercontent.com/assets/11842428/7033279/03eea940-dd47-11e4-94e6-23469a24e7f2.png)
![2015-04-07_16 46 57](https://cloud.githubusercontent.com/assets/11842428/7033281/03f0c48c-dd47-11e4-8512-03ac2eb5adf6.png)
![2015-04-07_16 46 59](https://cloud.githubusercontent.com/assets/11842428/7033282/03f359c2-dd47-11e4-86e2-495b2870dc53.png)

**Comment by Moe-Ronickah** [comment]
Snipinginunition, I'm seeing the same thing that you are.  I'm not going to post screen shots, however, I will post my statistics.

       ID Info              Sum of All Armor and Weapon     Show's on My Info
       Regen Bonus                     5.2                           4.1
       Mana Regen                      0.0                           0.0
       Spell Bonus                    92.0                          74.0
       Life Steal                      0.9                           0.8
       Mana Steal                      1.0                           0.0
       XP Bonus                       90.0                          66.0
       Loot Bonus                     91.0                          66.0

**Comment by epicman739** [comment]
I think this might be because the info uses average values, while identifications can vary 3% or so from the average.

**Comment by Tama63** [comment]
dupl
