### ISSUE TITLE
Missions not giving proper XP (Too little XP) and not giving full emeralds.

### ISSUE THREAD

**Issue by Moe-Ronickah** [Wynncraft/Issues#1789]
I wanted to be certain of this problem before I posted it, hence, the multiple examples.

This error cannot be reproduced unless the player is given a mission.

In this first example, notice that the XP for the mission was to be 13200, however, upon completion, the XP given was 10368.  That is 78.5% of the XP, not taking into account any XP bonus.  Obviously, I cannot say whether or not an XP bonus was included in the calculation, as I cannot see the formula that was used to calculate the XP that was received.  In other words, the XP received may have been considerably less had I not been wearing armor and carrying weapons that carried XP bonuses.

![2015-03-18_17 20 59](https://cloud.githubusercontent.com/assets/11842380/7033051/e624f9be-dd3c-11e4-8972-2ff8bb56f66e.png)

In this second example, notice the XP discrepancy: 8850 expected, versus 7483 given, for 84.6% given, again not taking into account any XP bonus.

![2015-04-03_14 27 11](https://cloud.githubusercontent.com/assets/11842380/7033117/74c531ca-dd3d-11e4-8478-4f50809581fd.png)

In this third example, notice the XP discrepancy: 2800 expected, versus 2436 given, for 87.0% given, again not taking into account any XP bonus.

![2015-04-04_20 26 37](https://cloud.githubusercontent.com/assets/11842380/7033193/0e72cf08-dd3e-11e4-8da0-6f9667ad07f6.png)

In this fourth example, notice the XP discrepancy: 10248 expected, versus 9121 given, for 89.0% given, again with no apparent XP bonus.  This time, however, I also screen captured my player information, which shows that I should have had an XP Bonus of 66%.

![2015-04-07_10 43 39](https://cloud.githubusercontent.com/assets/11842380/7033249/5a0dff50-dd3e-11e4-9a6a-0a48d04f95ec.png)
![2015-04-07_10 44 04](https://cloud.githubusercontent.com/assets/11842380/7033251/6087a700-dd3e-11e4-8131-7640b8633d0e.png)

**Comment by ThunderRemix** [comment]
I believe the XP given is dependent on how fast the mission is completed.

**Comment by Moe-Ronickah** [comment]
ThunderRemix, that has not been my experience over the course of the past year, and it would entail a new XP mechanic having to be implemented, of which I have seen no announcement or discussion.

**Comment by Moe-Ronickah** [comment]
My apologies, as I hit the wrong button to respond.

**Comment by Moe-Ronickah** [comment]
The issue is ongoing; the XP monster is still munching my XP.  [I know that it is awaiting confirmation.]

![2015-05-04_22 31 55](https://cloud.githubusercontent.com/assets/11842380/7472352/3730bdbe-f2f7-11e4-80ed-1c8bbaface54.png)

**Comment by Moe-Ronickah** [comment]
Here's another mission:
![2015-05-29_19 59 31](https://cloud.githubusercontent.com/assets/11842380/7895200/322d2ae4-0645-11e5-9255-67a8f9f68cdc.png)

With a Spectre, Adamantite, Crystal, Bad Wolf, and Maelstrom, I should be getting close to or more than double the mission XP upon completion.

**Comment by Moe-Ronickah** [comment]
And now, with my Dark Wizard, this is still going on.  And on.  And on.  I think I'm just going to sit in the corner and cry.
First, I get a promise of 2598XP for completing a mission, but is that what I get?  Oh, NOOOO~~~~!
![2015-07-21_11 48 10](https://cloud.githubusercontent.com/assets/11842380/8843009/b4551ee4-30c7-11e5-9d03-32d6b0c3bbd4.png)

I complete the mission and I get a measly 1663XP.
![2015-07-21_11 48 16](https://cloud.githubusercontent.com/assets/11842380/8843008/b4522928-30c7-11e5-93b8-dc236f3961dd.png)

I feel like Rodney Dangerfield - I don't get any respect, either.

**Comment by CryogenicFrost** [comment]
I've had this issue too, it's not just you. It may have something to do with armour xp weapon xp bonuses.

**Comment by McMasterx** [comment]
I've had issues in early days of my playing when I'd get over the amount of exp, simply because I had finished within a certain amount of time. I never recorded when it happened, because it never seemed like a bug.

**Comment by Moe-Ronickah** [comment]
Frost, if you read through my original post, you will see that I posted XP expected, XP received, and XP bonus as reported in the Player Info screen.  This glitch has not always been present, my percentage XP received took a very sudden drop, which was why I posted this in the first place.

McMasterx, if you don't finish the mission on time, you get no XP, no matter what.  True?  And if you finish in time, you get the XP plus a bonus based upon your XP bonus.  True?  Well, I suddenly started receiving significantly less of a bonus, which is why I posted this, nearly a year ago.

**Comment by Trixter313** [comment]
Does this still happen since the Gavel update?

**Comment by Moe-Ronickah** [comment]
I have not had a chance to check this.

**Comment by Moe-Ronickah** [comment]
Now that I have a little more time: I started a new class, and as soon as I
can actually complete a quest, I'll try to figure out if any XP bonus that
I have is actually being applied.  It may take a few days, as I fell in a
poorly lit movie theater, and I'm pretty dang sore and stiff.

**Comment by Trixter313** [comment]
Good luck with your tests and feel better!

**Comment by Moe-Ronickah** [comment]
Good Grief!  It's not better, it's gotten worse!  I get a simple mission to kill a few zombies, 17 of them for 530 XP points. Here's a screen shot taken when I had killed 16/17 zombies.  (When I first started this new class, I set my XP with /guild XP 0, and it was confirmed.)
![2015-12-23_00 39 52](https://cloud.githubusercontent.com/assets/11842380/11976380/67b2c69c-a93d-11e5-8aff-7154c3057ad8.png)

One more zombie re-killed, and I should get 530 XP, at least.  So, I re-kill one of the poor things, and what do I get?  "Great job! You have completed the mission! [292 xp]"  That's only 55% of the XP that I should have gotten.  Something is rotten in XP land.
![2015-12-23_00 39 58](https://cloud.githubusercontent.com/assets/11842380/11976479/190e40f6-a93e-11e5-83a4-82564ebfe6ee.png)

**Comment by Moe-Ronickah** [comment]
Chris, why did you close this when it has not been resolved and is still
affecting my characters?

**Comment by Moe-Ronickah** [comment]
Chris, please reopen this issue, as it is not resolved.

**Comment by Moe-Ronickah** [comment]
Has someone worked on this issue in the past 3 days?  If so, my account is very glitched.  My mission XP is working, now, HOWEVER, in 5 hours, trying to get depressing weapons, I did not get even ONE weapon of any type, and only 1 piece of armor, in front of Ragni, with no Loot Bonus.

**Comment by Moe-Ronickah** [comment]
Here we go, again.  A maintenance update was pushed through, last night, at 9:41 my time.  Well, guess what that update did to my mission XP percentages?  They are back down to 50% (274/538).  Here are shots of the mission XP chat, my weapon, and all of my armor.  With 2%XP boost, completing the mission should have gotten me 1.02 x 538 = 548.76 or 549 XP.

So, yes, I happen to be a barometer of whatever is being pushed through.  Lucky me.

![2016-01-04_23 45 33](https://cloud.githubusercontent.com/assets/11842380/12118355/9f18d5c4-b38b-11e5-8a5e-737446ea0be1.png)
![2016-01-04_23 45 55_2](https://cloud.githubusercontent.com/assets/11842380/12118367/b02ff6a8-b38b-11e5-8aad-6c09c06a725c.png)
![2016-01-04_23 45 55](https://cloud.githubusercontent.com/assets/11842380/12118372/b4af0cbe-b38b-11e5-82de-29ef1b29982f.png)
![2016-01-04_23 45 57](https://cloud.githubusercontent.com/assets/11842380/12118376/b8c00eb6-b38b-11e5-8b42-a17ee822790d.png)
![2016-01-04_23 45 56](https://cloud.githubusercontent.com/assets/11842380/12118381/bc278516-b38b-11e5-8e4e-b35e0dee1b7c.png)
![2016-01-04_23 45 58](https://cloud.githubusercontent.com/assets/11842380/12118384/c0052b52-b38b-11e5-9e0b-d85632e6a97b.png)

**Comment by Moe-Ronickah** [comment]
Once again, I hit the wrong switch.

I have several more examples of receiving around 50% of the expected base mission XP, however, I'm not going to post them unless they would be of further value.

**Comment by Moe-Ronickah** [comment]
Well, I thought of this, recently.  Where can we go with this information?
With the stats pages, here are my current stats:
![2 16 mission xp problem](https://cloud.githubusercontent.com/assets/11842380/12964101/d8fcade8-d013-11e5-9d18-dbd3032aea81.jpg)
And, here are three videos where we can see this in action, recorded live, with the stats, above, of course.

https://youtu.be/cITYQard7Aw

https://youtu.be/DaAyJRF2YJ8

https://youtu.be/zFyXGwbNaP0

**Comment by Moe-Ronickah** [comment]
ajdude9 reported, on the forums, on Feb 17, 2016, in https://forums.wynncraft.com/threads/what-is-the-stupidest-thing-youve-heard-in-wynncraft.89369/page-25#post-1244107:

"So, I was given this mission:
![ajd 01](https://cloud.githubusercontent.com/assets/11842380/13352672/8223fd58-dc54-11e5-82bb-e5192f8bc80d.png)
Is this even possible? How do I "Kill" a clock? It's not living; how can I kill something that isn't alive?

Also, the mission bloody lied:
![ajd 02](https://cloud.githubusercontent.com/assets/11842380/13352705/be7d8206-dc54-11e5-8c55-9b84a146e5ab.jpg)
I was promised a whopping 16xp and it paid out with a measly 9. Missions are scumbags. "

At least I'm not the only one to see this happening.

**Comment by DarkDemonDragon** [comment]
Wow never realized this because I almost always have xp bonus armor on when I do missions.

**Comment by Moe-Ronickah** [comment]
Dark, is this happening to you, too?

**Comment by Odnod** [comment]
Yeah this has been happening to me for as long as I have been playing wynncraft (about 2 years now.)   I always thought it had to do with player level.

**Comment by Moe-Ronickah** [comment]
OK, I have now purchased a second MC account, and begun playing it with a single class.  I have had at least 5 missions, and every one of them has been given the posted XP when I didn't have XP gear, and more XP when I did have XP gear on.

**Comment by DarkDemonDragon** [comment]
Who's Verret001?

**Comment by Verret001** [comment]
@Dark who knows?

**Comment by DarkDemonDragon** [comment]
When/how did you get admin permission? Tama's been inactive since February.

**Comment by Verret001** [comment]
@darkdemondragon Back when trickster got it, gravel update

**Comment by YunoFGasai** [comment]
> @darkdemondragon Back when trickster got it, gravel update
*Gavel
its a bit weird for us because you only started being active recently (also never seen you in game/on forums) also its pretty weird as you were active for 4 days back in December one day in march and that's all until today.

**Comment by Moe-Ronickah** [comment]
@Verret001 , this really is not the place for this, but it's here, so, how do you know Tama, or do you know any of the other admins?

**Comment by DarkDemonDragon** [comment]
@YunoFGasai exactly what I'm confused about.

**Comment by Verret001** [comment]
@yunoFGasai I was pretty busy from school. Since it's April break I got a break, though I am planning on being more active since I got my new iPhone.

**Comment by lungyiin** [comment]
In terms of tagging me I haven't been part of the Wynn team for a while and such do not have any perms on this repo

**Comment by DarkDemonDragon** [comment]
@lungyiin RIP to the pig that flew away. (Still slightly peeved that you never bothered to respond to my emails over like a 2 month period xP )

**Comment by Moe-Ronickah** [comment]
Now, it's started happening to my second account.  Oh, joy, of joys.

DDD, we're going to miss you and your help, around here.  Maybe you'll decide to come back in the future.

**Comment by 0x0000null** [comment]
Still happens in 1.14.1 Patch 3.

<img width="818" alt="1" src="https://cloud.githubusercontent.com/assets/16504771/18255795/084cf958-7362-11e6-8081-9975baf521c3.png">
<img width="788" alt="2" src="https://cloud.githubusercontent.com/assets/16504771/18255794/0849e880-7362-11e6-896b-d4827858369c.png">

**Comment by Celsonic** [comment]
@Moe-Ronickah I doubt that this will be fixed in the near future.... something to do with their algorithm probs. Personally I think it shouldn't give u missions to kill defense mobs like Almuj soldiers as said by @0x0000null

**Comment by 0x0000null** [comment]
This time it actually gave me *more* xp.

My XP bonus at the time, not including my bow, was definitely more than +100% (I think around +107%), while the mission gave me about 77.6% more XP.

<img width="882" alt="1" src="https://cloud.githubusercontent.com/assets/16504771/18639403/a41b3cc8-7e48-11e6-8f9a-40c3d9e1ecea.png">
<img width="786" alt="2" src="https://cloud.githubusercontent.com/assets/16504771/18639404/a423792e-7e48-11e6-8ed6-c55146246e30.png">

So missions don't always give *less* XP... they always seem to give the *wrong* amount of XP.

**Comment by Celsonic** [comment]
Might have something to do w/ xp bonus.

**Comment by Moe-Ronickah** [comment]
You got that much extra xp?  I'm gonna go sit in a corner and cry, now.

**Comment by 0x0000null** [comment]
It's possible that the mission wanted to give less XP, but then doubled the XP from DXP weekend.

**Comment by insectdude1258** [comment]
As of Dec 2016, this issue happens to me constantly. I always get less xp than the mission states. one of my friends gets more xp than it says its gonna give him.  I have a +38% xp bonus so i should be getting more not less if anything.
![2016-12-07_22 41 58-2](https://cloud.githubusercontent.com/assets/24449926/21001175/cef36618-bcd3-11e6-8418-18930c722f7a.png)
![2016-12-03_15 09 15](https://cloud.githubusercontent.com/assets/24449926/21001277/4eacfaae-bcd4-11e6-96b6-11ed2968a204.png)

**Comment by Villageacules** [comment]
Missions are to be reworked eventually.

**Comment by 0x0000null** [comment]
Soon™

**Comment by DebugingLonks** [comment]
Sholdn't be tag this as needing confirmation, its true

**Comment by Moe-Ronickah** [comment]
MISSIONS HAVE BEEN PERMANENTLY REMOVED.  THIS IS A DEAD ISSUE.
