### ISSUE TITLE
Changing username causes glitches in guild, player stats, etc.

### ISSUE THREAD

**Issue by MCminion** [Wynncraft/Issues#1791]
Hi wynncraft,

Recently I changed my username, but it probably glitched a bit.  Guild chat hasn't been working, but one of my guild members say that they can see chat.  But he says that it doesn't say that I"m owner, when I am the owner. Anyways, if u can help out, my old username is Draculaura0930 and my guild name is TheFrostFire. Also my player stats aren't working as well, I have to use my old username to view the stats Is this supposed to be a bug? 

MCminion0930

**Comment by epicman739** [comment]
Known issue, a patch should be out for this soon.

**Comment by MCminion** [comment]
I checked back on WC, and saw that everything is back to normal, I guess I
was kinda impatient :P anyways yea false alarm.
