### ISSUE TITLE
Im Stuck in a hole in Wynn Mountain

### ISSUE THREAD

**Issue by kahunae202** [Wynncraft/Issues#1792]
In wynncraft mountain I wanted to explore because I was bored and then I found a hole with a tier 3 chest in it the holw was unescappable and I am stuck there now. Please help

**Comment by epicman739** [comment]
/kill will kill you and teleport you to the nearest town. It costs 2 soul points, so make sure you have plenty to spare.

**Comment by kahunae202** [comment]
thank you
