### ISSUE TITLE
Glitched items in my bank

### ISSUE THREAD

**Issue by TBurningT** [Wynncraft/Issues#1794]
I played this game a very long time ago. I saw that archer spawned with arrows and I normally stock pile things if you can run out of them, so thats what I did. Now I have 3 stacks of glitched arrows in my vualt that I cant move touch or do anything to. I need help with someone to remove them please! I have screenshots linked here:
http://i.imgur.com/R9EehM7.png
http://i.imgur.com/A1vchvv.png
http://i.imgur.com/7du5976.png
http://i.imgur.com/xnHftnp.png

Thank you for the help!

**Comment by TBurningT** [comment]
anyone going to help me?

**Comment by Trixter313** [comment]
I would help if I could but seeing as only an admin can fix this we'll just have to wait and hope for a response soon.

**Comment by Tama63** [comment]
support@wynncraft.com
