### ISSUE TITLE
Old emeralds = usless

### ISSUE THREAD

**Issue by DoraExplorer** [Wynncraft/Issues#1795]
I have som old emeralds that is really old, i cant use them cause of that, can i get some new maybe?
Thank you
http://i.imgur.com/Mekvqas.png

**Comment by Moe-Ronickah** [comment]
Dora, there are three ways to fix the issue with old emeralds:
1)  The next time that you identify something, give all of them to the identifier.  The identifier will return only "new" emeralds to you,
2)  Change your Minecraft version to 1.7 temporarily, and all of your "old" emeralds will be usable,  or
3)  Obviously, but not the best way, you can just dump the "old" emeralds.

Personally, I believe the best method is method 1.

Good luck.

**Comment by DoraExplorer** [comment]
Thank you!!
