### ISSUE TITLE
Stuck in ground after dying in dungeon

### ISSUE THREAD

**Issue by MessinwthReality** [Wynncraft/Issues#1797]
I died in the zombie dungeon, and once I respawned I was stuck in the ground. I tried re-logging, going on different servers, restarting my minecraft, and teleporting, but I couldn't get out of the ground. Now I'm stuck there, with no way out!  The mage is the only class I use, and I find it annoying how now I'm incapable of using it. I would use a scroll but I had no scrolls on me at the time. If someone could help me, and fix this glitch it me greatly appreciated.

**Comment by Trixter313** [comment]
I'm guessing you're no longer stuck because you closed the issue but just incase it was unintentional, you can type /kill anytime and you will respawn at the nearest visited town with 2 less soul points.
