### ISSUE TITLE
Changing Classes-Staying In The Black Box!

### ISSUE THREAD

**Issue by Skeleton457** [Wynncraft/Issues#1799]
I play Wynncraft Every Day With My Friends And They've Experienced This Lag A Couple OF Times.
We've Tried To Restart Our Minecraft But It Never Seems To Work.

**Comment by Trixter313** [comment]
The issue is most likely not lag but just not getting teleported out of the black box like other players are experiencing. Typing /kill with 3+ soul points should do the trick and make you respawn at the nearest visited town. (/kill is affected by agility so it can take multiple tries sometimes)
