### ISSUE TITLE
World-edited hole in Mt. Wynn

### ISSUE THREAD

**Issue by LordDestroyer** [Wynncraft/Issues#1800]
I've been completing the Lord of the Clock, and this is what I found:

![2015-04-11_03 11 22](https://cloud.githubusercontent.com/assets/11894763/7099691/4321d302-dffa-11e4-8927-fb913259cf86.png)

Coordinates are in the screen.

Steps to reproduce:
1) Create a world-edited hole
2) Find it

**Comment by AckroWynn** [comment]
This is fixed on the build server, but it will take a while to update on the public servers.
