### ISSUE TITLE
an item can't be itentified

### ISSUE THREAD

**Issue by Nolmin02** [Wynncraft/Issues#1802]
Damassé rare pant for lvl 2 can't be identified. Normally u can hv spell dam 2% and xp bonus 3% that writing on the site. Can u do something pls

**Comment by SkySaito** [comment]
What does the Identifier say ?

**Comment by Trixter313** [comment]
Thats a long standing issue that has to do with the special character é in it.
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

**Comment by epicman739** [comment]
The strange thing is, sometimes items with special charecters will identify, and sometimes they don't.
