### ISSUE TITLE
Stuck in a block

### ISSUE THREAD

**Issue by rajulchawla** [Wynncraft/Issues#1804]
I have been doing the hallowynn quest for lvl 21 and over and I am loading a part of the quest but when I spawn I am stuck in a block and my coords are -371 -1967 23 and I cant get out. Can some admin teleport me to Nesaak or Detlas please or can someone give me a solution?

**Comment by SkySaito** [comment]
Do /kill with at least 3 soulpoints, it will teleport you to the nearest visited city.

**Comment by LordDestroyer** [comment]
Why are so many issues ending so sadly, with suicide? :-/
