### ISSUE TITLE
Guild Master Not Creating Guild but Taking Cost

### ISSUE THREAD

**Issue by Caks2** [Wynncraft/Issues#1806]
Hello, my IGN is Caks_ recently saved up enough LE to buy a guild as I went to purchase this guild. I ran into a problem I create the name and tag and entered yes as shown here http://gyazo.com/82ee6697bd210462ece7f5cb85beb3e0 and here http://gyazo.com/f400caaa46813bc3b7765aa6c328e408 but a guild was not created for me and it took my 5 LE and 5 Soul points shown here http://gyazo.com/2130315cc8b5362d3466dc79ace9b8de I relogged and still nothing has happened. Thanks for your time.

**Comment by Trixter313** [comment]
Sometimes it can take up to a couple hours for it to register fully so all I can suggest is waiting to see if that is the case here.
