### ISSUE TITLE
tower of ascention teleportation

### ISSUE THREAD

**Issue by tiduseleven** [Wynncraft/Issues#1808]
the teleportation in the tower of ascention (to pass from level 1 to level 2, level 2 to level 3...) is not good coded and the mobs kill me and my friends.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/1774
Jumping (especially with speed boost) seems to work eventually. So just keep jumping at the teleport spot and it will teleport you eventually.
