### ISSUE TITLE
Getting stuck in the class selecting area

### ISSUE THREAD

**Issue by Herobryne523** [Wynncraft/Issues#1809]
I'm not sure what it is really called, but i got stuck in the class selecting area. I do not really know how to duplicate this glitch, but I just selected my class, and I didn't leave the room. Now whenever i get on that charachter it just keeps me in that room with no way to get out.(the class is knight) and this is a picture of it:
![2015-04-12_08 25 03](https://cloud.githubusercontent.com/assets/11912539/7106189/461574e8-e0ee-11e4-8145-562ef7ca6f13.png) (i know that t is very dark, but that is kind of the point in that area, right?) Here's another picture:
![2015-04-12_08 24 53](https://cloud.githubusercontent.com/assets/11912539/7106206/7b1ca88c-e0ee-11e4-85eb-840c500f5d0f.png)

**Comment by Herobryne523** [comment]
the fire at the botom of the picture is just my particles

**Comment by Jamdog** [comment]
To get out of this room, type **/kill**
This will return you to the nearest city (probably Ragni), and cost 2 Soul Points.
