### ISSUE TITLE
Wrong direction in The Tower of Amnesia

### ISSUE THREAD

**Issue by cityuserGitHub** [Wynncraft/Issues#1810]
In the quest, The Tower of Amnesia, level 25 difficulty medium..
the text points in the wrong direction. It says: "Talk to Tinemild in Detlas Suburb at [99,70,-1212]"
That is the text before you started it. But, the cordinates doesn't point at Detlas Suburb, it points at The tower of amnesia, which is correct. The text should say "Talk to Tinemild in The Tower of Amnesia at [x,y,z]"

Screenshot to show as sort of proof..
![2015-04-12_19 07 28](https://cloud.githubusercontent.com/assets/11913427/7106631/302714d4-e148-11e4-91aa-ed570d6ebc5b.png)

**Comment by AckroWynn** [comment]
Well, I feel like whoever did the quest, felt like Detlas Suburbs reach all the way to The Tower of Amnesia. Even though this may be incorrect according to some people, you always have the coordinations!

**Comment by Tama63** [comment]
Bit of a subjective issue
