### ISSUE TITLE
items inside the enderchest are stuck and inable to trade with others

### ISSUE THREAD

**Issue by HappyMusicFan** [Wynncraft/Issues#1815]
I need some help with my enderchest. I cannot take any stuff out of it. When I click onto any slot of the enderchest, the chest menu closes immediately without any report. So everything I once put in there, will be stuck forever.

It's not even working after a restart of the game or a reconnect. At the moment I play MC version 1.8. On 1.7.2 it didn't work either...

I really need my enderchest and would be really thankful for some help.

My second problem is the inability to trade. When the trading menu is opened and the trading ready, both need to press the red button to confirm the trade, that's what I know. But when I press this red button to trade with somebody, the menu closes and in both traders chat a report "The trade has been canceled." appears. I always made sure that we really didn't cancel it and both clicked on the red button. Now I trade stuff with my friends by throwing it on the floor. I would be happy if I could trade and not have to worry that somebody else steals the trade stuff off the floor.

Thanks in advance.

HappyMusicFan (ingame name)

**Comment by epicman739** [comment]
Perhaps there is something wrong with your key binding. Go to the controls section of options, and see if left-click is bound to the wrong function.

**Comment by HappyMusicFan** [comment]
I saw in my controls that the button 1 is just bound to attack and destroy. Should be the normal setting for this button...
![2015-04-15_09 20 23](https://cloud.githubusercontent.com/assets/11947422/7153926/fa9aa730-e350-11e4-9597-e1d906881c3b.png)

**Comment by AckroWynn** [comment]
Button 1 is basically Left-Mouse-Button. All your controls seem in order, so that wouldn't be the problem.
I can't answer on questions that are specific to certain players like in this case, so I am very sorry.

**Comment by Tama63** [comment]
support@wynncraft.com
