### ISSUE TITLE
old Liquified Emeralds aren`t working anymore.

### ISSUE THREAD

**Issue by Mo230900** [Wynncraft/Issues#1817]
Hi there,
my Problem is that I cannot trade my liquified emeralds to emerald blocks at a villager.
I think i know why: I have traded both i think a half year ago. Now there are new with an subtitle which says their worth. I can only trade with LE´s with subtitle. Please fix this.
![2015-04-16_17 52 47](https://cloud.githubusercontent.com/assets/11981089/7185215/b7723e02-e461-11e4-8281-b798b7f6a8eb.png)

**Comment by HeadsetO** [comment]
You need to be in Minecraft 1.8 or lower to do that, they fixed a bug in 1.8.1 that blocks that kind of trade.

**Comment by Mo230900** [comment]
Ok  i played in 1.8.3. Thanks for your fast answer!

**Comment by Mo230900** [comment]
Ok  i played in 1.8.3. Thanks for your fast answer!
