### ISSUE TITLE
WynnExcavationSite B wall glitch

### ISSUE THREAD

**Issue by dontmind** [Wynncraft/Issues#1818]
when i was finishing the quest WynnExcavationSite B, i was teleported into dirt, so what i did was to relog, but this but me into the redstone room beside, which would open the wall, and let you throu, but instead i was now stuck, until an admin would help me out.

**Comment by epicman739** [comment]
/kill will kill you and teleport you to the nearest town. Note that it costs you 2 soul points, so make sure you have at least 3 left.

**Comment by dontmind** [comment]
thank you, i luckily have 13 :)
