### ISSUE TITLE
WynnExcavationSite B wall glitch

### ISSUE THREAD

**Issue by dontmind** [Wynncraft/Issues#1819]
when i was finishing the quest WynnExcavationSite B, i was teleported into dirt, so what i did was to relog, but this but me into the redstone room beside, which would open the wall, and let you throu, but instead i was now stuck, until an admin would help me out.
![2015-04-16_22 29 12](https://cloud.githubusercontent.com/assets/11984517/7190693/2ccf34ae-e488-11e4-95bd-8c812ccc3074.png)

**Comment by vogelmet** [comment]
dublication of #1818

**Comment by dontmind** [comment]
i was adding the picture, but it made a number 2, im gonna delete it
