### ISSUE TITLE
Jungle Fever emerald Guild glitch

### ISSUE THREAD

**Issue by poepser132** [Wynncraft/Issues#1821]
When you go to the bank and get the 64 Liquified Emeralds you need to bring them to Worid but if you go to the Guild donate menu you can insert the emeralds and give them to the guild if you did that (thats what i did) You cant complete the quest it says to talk to Worid but he says "Hey! Are you done with what I asked?" and you cant get new emeralds i got this and i am really stuck now i hope you guys find a way to make that not possible and return the liquified emeralds from the guild to the players.

**Comment by ThunderRemix** [comment]
Did you try ./fixquests ?

**Comment by Tama63** [comment]
You shouldn't have done that....
Looks like you'll have to earn them again?
