### ISSUE TITLE
Ingame Armour not loading

### ISSUE THREAD

**Issue by JustRoks** [Wynncraft/Issues#1822]
Whenever I log in, it says drawing your in-game armour.  Normal.  But then, 15 minutes later, I the slime ball armor in my inventory appears and it has not yet drawn.  My helmet is Blue Mask, and the rest of my armour is champion armour.  I have seen all 4 of these armour pieces drawn, so I know that it is possible for them to be drawn into your character.  I have tried to get on un-modded, different versions of minecraft, but none of them seem to work, it just never loads my armor.  For some reason, my other accounts that play Wynn can load the armour, but I can't.  It sort of goes along with my status/forum glitch on the 1st page of glitches.  I went on another account, and the in-game armour drawing loaded perfectly.  It wasn't a combo of a blue mask then the rest champion, though.  I am not sure if its just the champion and the endgame, or if its me.
http://prntscr.com/6vauxh
http://prntscr.com/6vauak
http://prntscr.com/6vasv2

P.S.  I experimented, it is me.  I put on some leather boots then took off all my regular armor, this was the end product:
http://prntscr.com/6vdwlo
http://prntscr.com/6vdxtn
(Nothing loaded)

Even on my level 24 ninja the armor doesn't load on it, so it is my account.

**Comment by Thanassis95** [comment]
I have the same Problem... i cant see the armor from anybody, not even mine
i tried it with my 22 mage and i leveld my assasin from lvl 1 to 18, without armor
