### ISSUE TITLE
Silverfish dungeon door does not open

### ISSUE THREAD

**Issue by CactusOwnage** [Wynncraft/Issues#1826]
Hello, I've tried the silverfish multiple times but the first door doesn't open. I drop something on the pressure plate after the parcour then I drop an emerald on the black wool in both snakes. But still the door doesn't open. Please help me :(

**Comment by epicman739** [comment]
Have you tried it on a different server? Sometimes one or two servers will glitch.

**Comment by CactusOwnage** [comment]
I have switched between multiple server but nothing changed.

**Comment by AckroWynn** [comment]
After you put the emeralds in the snakes, a door opens inside of that snake room. Follow that upwards and put emeralds on the 2 plates, and then it will work!
