### ISSUE TITLE
Jungle Fever Quest Complete Le conversion

### ISSUE THREAD

**Issue by ArrowBowen** [Wynncraft/Issues#1827]
Wynncraft Staff,

So I completed this quest.  I look in my inventory for the new LE and I already had 3 in my inventory before.  What I come across is my old LE converted into the quest LE and I get the 1 LE quest reward.  In short: 3 LE turned into Almuj's Liquified Emerald, 1 LE gained from quest completion.  Net loss of 2 LE.  I searched and found this error however there wasn't a fix yet.

-ArrowBowen IGN:BowenArrow

**Comment by BloodLad** [comment]
Thats what happened to me too...
