### ISSUE TITLE
Disappearing Liquid Emerald

### ISSUE THREAD

**Issue by mrpeepers** [Wynncraft/Issues#1829]
I had just traded in 64 emerald blocks for a liquid emerald from the Detlas liquid emerald merchant. I then traveled to the bank to deposit it and it was out of my inventory. I am sure i did not drop it out of my inventory because it was not in my hotbar and i checked the ground around where I went. After I bought the emerald it was in my inventory but im not exactly sure when it disappeared. I waited a while and kept moving things in my inventory and checking the path I used but it did not come back.

**Comment by musicwolf** [comment]
Maybe It was the lag. But i'm still sorry to hear that. Btw my bank is broken and i can't get items out of my chest (maybe you know how to fix this). I can get in my chest but when i click on an item it will throw me out of the bank and the item is still in his place.

Tip: You can easy collect emerald by placing 1 emerald in all the open slots that way you can only pick up emeralds.

I wish you luck.
