### ISSUE TITLE
KANGRONOMICON GUILD GLITCH

### ISSUE THREAD

**Issue by Spham99** [Wynncraft/Issues#1831]
Every time double xp weekend comes, it always glitches our guild for some reason!!! This time we cannot attack at all. It says your guild is in a battle but honestly we haven't attacked in the past 2 hours. This means that our guild is in a continual battle, also meaning that we cannot take ANY territory during double xp which gives us a disadvantage considering our negative xp. We've been trying to attack for the past hour so we know for sure that we are glitched. Please do something about this. 
-Spham

**Comment by ThunderRemix** [comment]
Yeah, it's annoying. T-T
