### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by poppet1693** [Wynncraft/Issues#1833]
Everytime i try to connect to play.wynncraft.com it comes up with "Unable to find a server to connect to. Please report." i tried restarting my computer and minecraft this was a couple of minutes after the server restarted and it became the double xp weekend! Please Help Me Figure this out!

**Comment by AATAM0** [comment]
I need help with that too

**Comment by Trixter313** [comment]
Wynncraft just tweeted, "And we're back online! Sorry about that, someone flamingo'd up. It's like a cock-up only much bigger. Enjoy your double XP weekend!"

So it's back online now :)
