### ISSUE TITLE
Why i cant login to Wynncraft

### ISSUE THREAD

**Issue by acehate12** [Wynncraft/Issues#1834]
i cant login to wynncraft it say "Unable to find a server to connect to. Please report" i dont know what just happen.(like #1833)
![image](https://cloud.githubusercontent.com/assets/10232276/7332018/e0a04f12-eb55-11e4-93d2-87a68465cd13.png)

**Comment by Huhn360** [comment]
have the same problem.... my last server was server 9 and then the restarte came and nothing works....

**Comment by Qustomm** [comment]
Have the same problem.

**Comment by AATAM0** [comment]
Me too

**Comment by AATAM0** [comment]
I want to play in wynncraft now!

**Comment by Trixter313** [comment]
Wynncraft just tweeted, "And we're back online! Sorry about that, someone flamingo'd up. It's like a cock-up only much bigger. Enjoy your double XP weekend!"

So it's back online now :)

**Comment by AckroWynn** [comment]
Please check if there are any previous issues here stating this certain issue.

Thanks!

**Comment by AATAM0** [comment]
thanks :)))))
