### ISSUE TITLE
Unable to find a server to connect to. Please report!            How to fix?

### ISSUE THREAD

**Issue by Qustomm** [Wynncraft/Issues#1835]

**Comment by Qustomm** [comment]
Please help me!

**Comment by AATAM0** [comment]
When i try to connect wynncraft it says "Unable to find server to connect to. Please report.
Help me pleasee my name is AATAM0

**Comment by AATAM0** [comment]
How i can fix it D:

**Comment by poppet1693** [comment]
This problem is already in a issued

**Comment by AATAM0** [comment]
But how can i join server

**Comment by Trixter313** [comment]
Wynncraft just tweeted, "And we're back online! Sorry about that, someone flamingo'd up. It's like a cock-up only much bigger. Enjoy your double XP weekend!"

So it's back online now :)

**Comment by AckroWynn** [comment]
Please check if there are any previous issues here stating this certain issue.

Thanks!
