### ISSUE TITLE
I cant join wynncraft it says Unable to find a server to connect to

### ISSUE THREAD

**Issue by AATAM0** [Wynncraft/Issues#1836]
Heelp meee

**Comment by uae2ae** [comment]
Yep .. me too it's not a good sign ... please fix the server ... whatever I do I cannot connect

**Comment by AATAM0** [comment]
Double xp weekend and i cant join D:

**Comment by AATAM0** [comment]
I really want to play in wynncraft

**Comment by Trixter313** [comment]
Wynncraft just tweeted, "And we're back online! Sorry about that, someone flamingo'd up. It's like a cock-up only much bigger. Enjoy your double XP weekend!"

So it's back online now :)

**Comment by AckroWynn** [comment]
Please check if there are any previous issues here stating this certain issue.

Thanks!
