### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by ronandasylvo01** [Wynncraft/Issues#1837]
Unable to find a server to connect to. Please report.
Everytime i log onto wynncraft i see this, could you fix this?
Thank you!

-ronandasylvo

**Comment by vorck** [comment]
same for me

**Comment by Trixter313** [comment]
Wynncraft just tweeted, "And we're back online! Sorry about that, someone flamingo'd up. It's like a cock-up only much bigger. Enjoy your double XP weekend!"

So it's back online now :)

**Comment by AckroWynn** [comment]
Please check if there are any previous issues here stating this certain issue.

Thanks!
