### ISSUE TITLE
i cant join wynncraft server ! Help

### ISSUE THREAD

**Issue by 7asoOonyi14** [Wynncraft/Issues#1838]
i cant join the server it says { connect lost }

this issue started today . yesterday i was playing an there was no issue

**Comment by vorck** [comment]
same for me

**Comment by Trixter313** [comment]
Wynncraft just tweeted, "And we're back online! Sorry about that, someone flamingo'd up. It's like a cock-up only much bigger. Enjoy your double XP weekend!"

So it's back online now :)

**Comment by AckroWynn** [comment]
Please check if there are any previous issues here stating this certain issue.

Thanks!
