### ISSUE TITLE
Hunger empty and stalled

### ISSUE THREAD

**Issue by jbruni** [Wynncraft/Issues#1839]
I recorded a video of the issue - http://youtu.be/34aY_l1SnpY

My hunger is empty and it does not increase. I can't run. I can't use the combo skills. It used to raise automatically before it happened.

It started suddenly and since then I am stuck in this situation. I tried changing client version. I was using 1.8.4 when it started. I connected using 1.7.10 and it behaved exactly the same way.

Please, help! Thank you.

**Comment by Trixter313** [comment]
Going to a different world should resolve your issue. This can sometimes happen temporarily on just one world.

**Comment by jbruni** [comment]
I just entered the game now and it was normal again. It was temporary, indeed. Thanks.

**Comment by jbruni** [comment]
It happened again with me.
Auto-select the player class was turned on.
I turned it off, and immediately the issue vanished (uponr reconnection).
