### ISSUE TITLE
While Questcompletion timed out bug

### ISSUE THREAD

**Issue by MCHacker1706** [Wynncraft/Issues#1840]
Hey, I timed out while handing in the Zight Island quest (giving this guy his crate), so I reconnected tried to complete it and I get the response as if i no crate. So I checked my inventory and the crate was gone. How will I be able to complete this quest now?
![691049e09d039297cd934450232b7851](https://cloud.githubusercontent.com/assets/2955065/7334847/3ae9779c-eba0-11e4-8ccc-d4a204d3866e.png)

**Comment by jbruni** [comment]
Does `/fixquests` work?
