### ISSUE TITLE
Iam bugged in the ground

### ISSUE THREAD

**Issue by lucashilhorst** [Wynncraft/Issues#1843]
I did a mission and i won but iam teleported in to the ground i can't tpa to a city with the scrolls i can't do nothing can you tp me or break the ground the mission is find the haunted mask and bring it back to  the mask salesman

**Comment by Huhn360** [comment]
then you have to type /kill

**Comment by Huhn360** [comment]
and there dont open more servers....

**Comment by epicman739** [comment]
Also /kill costs 2 soul points, so make sure you have plenty to spare.
