### ISSUE TITLE
New and "Old" emerald.

### ISSUE THREAD

**Issue by hello2me23** [Wynncraft/Issues#1845]
I don't know wtf is it, but my liquified emerald useless. He has no registry , which is equivalent , so the game does not see it ...
![screenshot_3](https://cloud.githubusercontent.com/assets/12126641/7338915/9cd6b718-ec6c-11e4-9839-7c84d8206270.png)

**Comment by hello2me23** [comment]
![screenshot_4](https://cloud.githubusercontent.com/assets/12126641/7338938/756c1226-ec6d-11e4-91aa-6797adfd3b08.png)

**Comment by SkySaito** [comment]
Go back on 1.7 and trade them into blocks. It should work.

**Comment by Xenon2014** [comment]
You can't fix this without help of admins.
There was an update which updated the WHOLE map and the emeralds.

**Comment by hello2me23** [comment]
SkySaito, thx you! This is work!
