### ISSUE TITLE
Armor's skin bug

### ISSUE THREAD

**Issue by SkySaito** [Wynncraft/Issues#1846]
Hey !
I've found a bug with the armors. So I got a new piece of armor, Bad Wolf, and I decided to put them. But then ALL my armor's skin has changed. My equipment is Spectre, Millenium, Frosted Leggings and the boots were originally Bloudil. When I put the last one, it turns back to normal. 
Here with Bloudil on, thus normal :
![2015-04-27_00 00 59](https://cloud.githubusercontent.com/assets/7000957/7339518/eed1bf5e-ec71-11e4-8085-1a5cf557556c.png)
Now with Bad Wolf :
![2015-04-26_23 57 46](https://cloud.githubusercontent.com/assets/7000957/7339534/128d6470-ec72-11e4-9a35-6810575ffa1f.png)

**Comment by epicman739** [comment]
I think this might be a known error where sometimes an older skin is used for armor skinning instead of the most recent one.

**Comment by SkySaito** [comment]
Just to say here, it's an old armor skin, not my skin, so it appears that this bug occur with every other type of skin.

**Comment by Tama63** [comment]
Try relogging
