### ISSUE TITLE
Identification relic daggers not working

### ISSUE THREAD

**Issue by Kylecoolguy3** [Wynncraft/Issues#1847]
![2015-04-27_12 09 45](https://cloud.githubusercontent.com/assets/12134803/7345597/8aa54ac2-ecd6-11e4-8b61-7f82d8b8d65d.png)
![2015-04-27_12 09 41](https://cloud.githubusercontent.com/assets/12134803/7345587/77ba7932-ecd6-11e4-9c1a-2d4c90c71817.png)

**Comment by Xenon2014** [comment]
Are you sure that relic items can be identified?
(I'm not sure but I think that they can't.)

**Comment by Huhn360** [comment]
Relic items are identifiable!

**Comment by epicman739** [comment]
I think the Relic Daggers are currently being glitchy. All other Relic items identify properly.
