### ISSUE TITLE
Chunk Area missing

### ISSUE THREAD

**Issue by blackjack2222** [Wynncraft/Issues#1848]
This area is missing a chunk or two. I reloged twice and log on diff servers and its still missing. The Missing Chunk Coords are -153, 66, -1973 Its under Mt. Wynn.

Pictures: 
![2015-04-28_07 21 06](https://cloud.githubusercontent.com/assets/12152341/7368661/51a00b5c-ed78-11e4-85a7-6372a471f02d.png)
![2015-04-28_07 21 08](https://cloud.githubusercontent.com/assets/12152341/7368665/5ede5684-ed78-11e4-8017-9d4c93ab2db3.png)
If these don't work: http://imgur.com/EcMoFXV,A4LDfBM#0

**Comment by Trixter313** [comment]
In case you're stuck, type /kill into chat and you will respawn at the nearest visited town.

**Comment by epicman739** [comment]
This one's been found already, it should have been fixed a while ago.
