### ISSUE TITLE
Skeleton dungeon mobs give no drops

### ISSUE THREAD

**Issue by HopeAndPlay22** [Wynncraft/Issues#1849]
I'm working on the quest "Lab assistant" and I thought I'd go through the Skeleton Dungeon to get the bonemeal needed. But after killing 50 or so skeletons in there, I still had no more bonemeal. When I went to kill skeletons near Nemract I got the normal drop rates. 

Is this a bug or are the skeletons in the dungeon supposed to not drop any bonemeal?

**Comment by Trixter313** [comment]
I don't think they're supposed to drop bone meal because of how easy it would be to farm it.

**Comment by epicman739** [comment]
I'm pretty sure dungeon mobs have either a really low item drop rate, or no drops at all.
