### ISSUE TITLE
Pelier helmet un-identifiable and invisible

### ISSUE THREAD

**Issue by Riverstarship** [Wynncraft/Issues#1850]
The legendary lvl. 42 helmet "Pelier" (with a special e) is unidentifiable, and I haven't been using it for this reason. I imagine that this is caused by the special character in the name, otherwise I have no idea why this occurs. It also appears invisible when equipped and drawn onto your skin.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

**Comment by Riverstarship** [comment]
So it is, thanks!
