### ISSUE TITLE
I can't regen hunger

### ISSUE THREAD

**Issue by zoth138** [Wynncraft/Issues#1851]
Ign: zoth138
i logged in as normal and i found my hunger going down unusually fast but it wouldn't come back. now i cant use spells or even run. I have tried suicide and all that did was let me run for about 30 secs before i was down to walking speed and constant hitting of hunger. Edit: just also found out im invisable when like this.

**Comment by zoth138** [comment]
its resolved. i just waited a long time and hopped between worlds

**Comment by zoth138** [comment]
its back...

**Comment by Trixter313** [comment]
This can happen temporarily on only a certain world. Switching to another world when this happens should effectively solve the issue.
