### ISSUE TITLE
List of all known issues

### ISSUE THREAD

**Issue by Tama63** [Wynncraft/Issues#1852]
# Items
* Some items can't be identified #1312 
* Some items have dodgy tooltips #1508, #1509 

# Game messages
* Incorrect grammar w/ hunter class login message #1338 
* Apost not parsed in some messages #1507 
* Sometimes exp isn't shown on mob deaths #1329 

# Website
* Some players aren't found #1798 - UUID or??

# Game functionality
* Mage class teleportation glitches #1565 
* Riding teleportation glitch #1530

**Comment by AckroWynn** [comment]
This will be pretty useful, thanks!
