### ISSUE TITLE
ToA

### ISSUE THREAD

**Issue by LavaWarriorBoy** [Wynncraft/Issues#1854]
Help! when i go behind tho Floor Master, it will not teleport me, i gived the Floor Master 10 Items and it's says You May Proceed... But when i go behind the floor master it doesn't teleport me to the next Lv It's Floor 1 Level 1, The Enemy is Winter Ram (Sheep) Lv 41

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/1774
