### ISSUE TITLE
Porque exigir nível superior para programadores?

### ISSUE THREAD

**Issue by mrMarko** [Wynncraft/Issues#1855]
was changed to
                                > https://github.com/abraphp/CarreiraPHP/issues/17
mudada para

**Comment by Trixter313** [comment]
Creo que usted ha publicado esto en la incorrecta Github. No hay reporte de error o problema en su declaración sobre el servidor de Minecraft Wynncraft.

**Comment by mrMarko** [comment]
Mudei o comentário para o link acima.
Obrigado!

**Comment by mrMarko** [comment]
fechando!
