### ISSUE TITLE
I spawned to void

### ISSUE THREAD

**Issue by 1234sasu** [Wynncraft/Issues#1857]
When i joined to server and selected my class i spawnd to void my minecraft username is 1234sasu
![2015-05-02_10 55 01](https://cloud.githubusercontent.com/assets/12207527/7440384/db947eda-f0b9-11e4-94ab-5a8fd59a8197.png)

**Comment by SkySaito** [comment]
Do /kill with at least 3 soulpoints. You'll be teleported to the nearest visited town.

**Comment by 1234sasu** [comment]
Thanks that helped me
