### ISSUE TITLE
My armor wont show!

### ISSUE THREAD

**Issue by MrZulux** [Wynncraft/Issues#1859]
![2015-05-02_19 42 16](https://cloud.githubusercontent.com/assets/12212287/7442111/7a2257ae-f103-11e4-9df3-dbdd16d5e701.png)

why is this happening?

**Comment by Moe-Ronickah** [comment]
This is an error where the server is not always updating the skin.  Your best bet is to log off of the server, and then log back on.  It is an old, and well known error.

[Using the "search" box, type in "armor".  The search will find nothing, at first.  Change from "code" to "issues", I believe, then re-run the search, and you will find many other issues posted of this same thing.]
