### ISSUE TITLE
Hidden hole inside Mt. Wynn 

### ISSUE THREAD

**Issue by comimato** [Wynncraft/Issues#1860]
I was helping my friend in the Lord of the Clock quest, and already inside Mt. Wynn, I found some weird completely black blocks near a lava flow, so I jumped inside of it and there was a giant hole! There was a beautyful-decorated cave too.
                                                                 
![imagem de diogo 1](https://cloud.githubusercontent.com/assets/12213694/7442754/c7d72556-f0f4-11e4-83a0-3af0d61ba604.jpg)
                                                        The black blocks(taken by my friend)

![imagem de diogo](https://cloud.githubusercontent.com/assets/12213694/7442758/f98a8e3a-f0f4-11e4-9fd6-57e00f38c33f.jpg)
                                                              The Hole(taken by my friend)

![2015-05-02_17 22 46](https://cloud.githubusercontent.com/assets/12213694/7442785/705d1ed2-f0f6-11e4-8081-6d76acc4b80b.png)

                                                                           Inside of it

![2015-05-02_17 23 19](https://cloud.githubusercontent.com/assets/12213694/7442776/050b3394-f0f6-11e4-8f63-aba651a30458.png)
                                                                The place where I felt

![2015-05-02_17 28 47](https://cloud.githubusercontent.com/assets/12213694/7442779/2c9001ce-f0f6-11e4-8a1b-b8ebf907548b.png)
                                                                   The decored cave

Sorry for the bad english

**Comment by epicman739** [comment]
Known issue, this was supposed to be fixed a while back.

**Comment by AckroWynn** [comment]
This is fixed, but it has yet to be pushed to the main servers.
Be patient!
