### ISSUE TITLE
Problem with Cloud Player Trail.

### ISSUE THREAD

**Issue by Terabyte-2** [Wynncraft/Issues#1861]
I couldn't seem to find a current issue ticket open pertaining to this particular problem. I've recently purchased the cloud player effect from the gold coin shop. I also purchased VIP+ recently as well. When I continue to activate the cloud effect, it gives me the letters effect. I have both the option for the letters effect and cloud effects. All of the other effects that I have work perfectly fine. I don't know if it is just me, or what. I can also provide screenshots of exactly which effects I have as well. I would really like this to be resolved in one way or another. I spent 220 GC on said cloud effect, and I could have used it on other effects/bombs. I hope this isn't a duplicate. Thanks for reading!

~Terabyte

**Comment by epicman739** [comment]
I'm fairly certain that this has been reported before, but a fix has not yet been implemented yet.
