### ISSUE TITLE
Recieving 0 experience

### ISSUE THREAD

**Issue by TheElder34** [Wynncraft/Issues#1862]
I was playing on my lvl 74 warrior and did the depth, clock, craftmas, and halloween quest, thinking my XP bar wasn't moving because I was a higher level, but after about 100K xp, I got curious and headed over to my lvl 12 hunter, where I started killing lvl 13 zombies, and continued to get 0 XP (I still recieve guild XP), I then got a mission that told me I would recieve 1100 XP upon completion, when I did complete it, I recieved 0 XP, verifying that my character cannot earn experience. I am aware that this is an account problem, but it may also be happening with others. 
![2015-05-02_18 50 04](https://cloud.githubusercontent.com/assets/6487868/7443172/323a814c-f0fd-11e4-97cf-d345b33c35e1.png)

**Comment by Trixter313** [comment]
Try typing /guild xp 0 and see if that fixes your problem. You might be giving all of your xp to your guild.
