### ISSUE TITLE
Unable to find a server to connect to. Please report.

### ISSUE THREAD

**Issue by Restarting69** [Wynncraft/Issues#1864]
Hello,
Whenever I attempt to connect to Wynncraft, I receive the error message 'Unable to find  a server to connect to. Please report.' so here I am reporting it xD This happens whenever I attempt to join, and restarting game and re-connecting to wifi doesn't fix it. I have never come across this error before and I was wondering if anyone knew of a fix?

Thanks!
~Restarting

**Comment by xXDruideXx** [comment]
yeah me too it dosen't work please fix this probleme

**Comment by Terabyte-2** [comment]
This is annoying, I just want to get on so I can go on a questing spree lol.

![screenshot_20150503094058](https://cloud.githubusercontent.com/assets/12214732/7445248/1bffaf52-f179-11e4-9103-6bc0edfe578d.png)

**Comment by Restarting69** [comment]
Server has 0 players on now?

**Comment by Terabyte-2** [comment]
https://forums.wynncraft.com/threads/server-downtime.77896/#post-867912

**Comment by xXDruideXx** [comment]
the server was just restarting yhe serve take time for lunch

2015-05-03 15:45 GMT+02:00 Terabyte-2 <notifications@github.com>:
