### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by Marcel1432001** [Wynncraft/Issues#1865]
we can't connect to the server: Unable to find a server to connect to. Please report

**Comment by Terabyte-2** [comment]
I have the same problem. I've tried using a different account, starting with a clean vanilla version of both 1.7.10 and 1.8, my optifine of those versions, and nothin'.

![screenshot_20150503094058](https://cloud.githubusercontent.com/assets/12214732/7445243/eab779c0-f178-11e4-8af0-a14a349b3182.png)

**Comment by Terabyte-2** [comment]
https://forums.wynncraft.com/threads/server-downtime.77896/#post-867912

If that page no longer exists, then it's fixed.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/1864
Please refer to it.
