### ISSUE TITLE
Losing Quest Items Due To Glitches

### ISSUE THREAD

**Issue by AgentEdward** [Wynncraft/Issues#1866]
I Just Finished The Creeper Infiltration Quest When I Accidently Dropped It Trying To Get Rid Of A Potion When It Said You Can't Drop Quest Items And Never Gave It Back!!! Any Help With This?

IGN: Agent_Edward

**Comment by Trixter313** [comment]
Have you tried typing /fixquests into chat?

**Comment by AgentEdward** [comment]
No I Didn't Know That Was A Thing Thanks =D
