### ISSUE TITLE
Can't buy the pet I want.

### ISSUE THREAD

**Issue by Rawrmouse123** [Wynncraft/Issues#1868]
![](http://i.imgur.com/9K8jiDd.png)
So, since it's 50% off weekend my brother (jeffthewailmer) wanted a pet wither skeleton. We got him the coins, but the game says he needs the normal amount to purchase them. Can it be helped? His IGN is in the parentheses.

**Comment by Terabyte-2** [comment]
I've had a similar problem. I purchased the cloud play effect, but every time I use it, it gives me the letters effect instead.. I opened a ticket about it quite some time ago. No responses.
