### ISSUE TITLE
/forum not working, still stats glitch 

### ISSUE THREAD

**Issue by JustRoks** [Wynncraft/Issues#1871]
I'm a little annoyed first for my issue being closed but not fixed.  https://github.com/Wynncraft/Issues/issues/1798 is the issue.  But a new glitch has arrived.  Not only does my page not work even though the thread is closed, @Tama63.  The /forum command for me hasn't been working for the pas few months even though I am a VIP+.

*update, my face on my stats page has been changed from Steve to this random skin, along with clicking myself sending me back to the stats page.

**Comment by Moe-Ronickah** [comment]
I hate it when that happens.  /forum => "We can't authorize this account.  Try again later."  Yep, it's still there.  "http://wynncraft.com/player/Moe_Ronickah" just brings me to the general stats page, still.

**Comment by Terabyte-2** [comment]
Same thing is happening to me. I've also made an issue ticket on my cloud player trail not work. I've emailed them as well. No response yet. It's a bit irritating

**Comment by Tama63** [comment]
@Terabyte-2 issues like that belong on the tracker.

@JustRoks I've been busy and will be busy until the first week of June so don't expect any progress on this issue until then.

**Comment by Tama63** [comment]
```
array(2) {
  ["command"]=>
  string(10) "Just-;Roks"
  ["limit"]=>
  string(0) ""
}
{"request":{"timestamp":1432062299,"ip":"x"},"error":"No username found"}
```

The fix has been pushed to the repo it may take some time because our deployment solution is down.

**Comment by Tama63** [comment]
I'll try and get it deployed ASAP, if I don't email me@chrisireland.me
