### ISSUE TITLE
Stuck in a Wall at Skiens

### ISSUE THREAD

**Issue by PlayToNguyen** [Wynncraft/Issues#1873]
I was exploring Skiens island when I fell into a trap in the ground. To get out you kit a button which opens a piston door. I got stuck in the door. I can't use Teleportation scroll for some reason and, after searching the internet, tried doing /die and /kill but neither of them kill me. Is there another way? Or at least, is anyone willing to come hit the button?

**Comment by epicman739** [comment]
Try /kill again, it may be a lag issue. Also make sure you have at least 3 soul points, since /kill costs 2.
