### ISSUE TITLE
Lost skill points

### ISSUE THREAD

**Issue by Mechwolf30** [Wynncraft/Issues#1874]
Upon using a Skill Reset Scroll with *UNSPENT* skill points, it will convert all *SPENT* skill points into *UNSPENT* skill points, without adding in previously unspent ones. This means that it completely resets your *UNSPENT* skill points value.

I had four unspent skill points before resetting my skills, and lost those four totally. I am now a level 26 with only 50 total skill points.

This can cause *huge* problems, especially if someone with a lot of unspent skill points resets.

-To recreate this, simply:
1. Have one or more unspent skill points
2. Acquire a Skill Reset Scroll
3. Reset your skills with the scroll
4. You now have missing skill points!

Here is a screenshot of my skill points screen after resetting and re-applying.
This is the moment I realized I had some missing points. Note my level, the spent skill points that you can see, and the unspent skill points, which says 0 at the top.
http://prntscr.com/72gdnt

**Comment by TwinLotus** [comment]
In my perspective, this is a little confusing ..

I don't see anything wrong in the picture. Okay, let's see how this works. You spread out your skill points evenly beyond two skills, strength and dexterity. Each level you get two skill points. There is 25 for both of those skills. You're level 26. Remember that level 1 is excluded of skill points. Every level "AFTER" level 1 grants you two skill points. I think i'm missing something here that I may not be seeing...

**Comment by Mechwolf30** [comment]
Must have been my mistake then, I asked some others and they said I should have extra skill points. I thought: 2 skill points per level = level 26 = 52 skill points. I will close this now.
