### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Blizem** [Wynncraft/Issues#1882]
Hello there good reader <3

I'f found a little bug, in this report Ill explain what the bug is :D 

IGN = Grundig_NL UUID = 92a9b283-ec66-4334-8e10-05ba780a0825

When did the bug bug = 9.5.2015

Mission = Lord of the Cloak

Bug 
Well, I was playing this mission, on a certain point I had to speak to Frudo, he was at in Mt.Wynn, I had the cloak in my inventory. I talked to the NPC, yet then I had to log out D:

When I came back in, I found out the cloak was not in my inventory, yet I still needed to talk to  the NPC.

Here are some additional schreenshots

http://prntscr.com/73ddck 
This is my inventory

http://prntscr.com/73ddoe
This is the book.

Thank you for reading this report, a good day to you sir! :D 
- Sem / Grundig_NL

**Comment by epicman739** [comment]
/fixquests should return missing quest items, though it's a bit buggy and might not work.
Next time, make sure the title tells us what the problem is, don't just put "Bug Report".

**Comment by R41z** [comment]
Blizem?
