### ISSUE TITLE
When I kill a mob i get no exp

### ISSUE THREAD

**Issue by Preston111** [Wynncraft/Issues#1885]
This server used to be my favorite server but then I had lots of issues with combat like when I kill a mob I don't get exp.

**Comment by Trixter313** [comment]
Are you in a guild?

**Comment by Preston111** [comment]
no i am not

**Comment by epicman739** [comment]
There is a level mechanic thing with mobs where if you kill a mob whos level is too different from yours, you have a chance of getting no XP.
@Jamdog can probably explain it better than I can.
