### ISSUE TITLE
spawn lag

### ISSUE THREAD

**Issue by Preston111** [Wynncraft/Issues#1887]
When I try to log in when I choose my mage kit I will stay in the dark room and I cant get out also I don't want to kill myself to loose my nether stars they are very important for when I die

**Comment by Trixter313** [comment]
You get more soul points every Minecraft sunrise and the only way out is by using /kill.

**Comment by Preston111** [comment]
If you cannot tell i have a lot of issues with the server

**Comment by epicman739** [comment]
If you have other issues post more bug reports, don't just pile them all into one.
