### ISSUE TITLE
This server needs a mod request command

### ISSUE THREAD

**Issue by Preston111** [Wynncraft/Issues#1889]
I have a lot of problems with this server and i think there should be a mod request command like /modreq or something of that sort so I can inform a mod my issues on the server

**Comment by pieguy333** [comment]
yes please do a mod request command please wynncraft

**Comment by Trixter313** [comment]
On https://forums.wynncraft.com there is a box with currently online staff that you can message, you can email support@wynncraft.com, and there is this website to report your issues therefore I don't think that another form of contact is really nessecary but we'll see what the admins on here decide.

**Comment by epicman739** [comment]
This is the bug report section, not the suggestions section.
Suggestions go here: https://forums.wynncraft.com/forums/general-suggestions/

**Comment by AckroWynn** [comment]
There is a mod requesting tool on over at the servers!
Just use /report, and a moderator will check you out.
