### ISSUE TITLE
Useless emeralds

### ISSUE THREAD

**Issue by mnb9877** [Wynncraft/Issues#1892]
I havent played for a few months and when i return all my emeralds i previously owned are useless as in i cant trade with them 

https://cloud.githubusercontent.com/assets/12386237/7556795/fbf1c0f8-f74d-11e4-8eeb-c53cdc49c872.png

(https://cloud.githubusercontent.com/assets/12386237/7556803/1efad54e-f74e-11e4-98c5-46a9503c63f1.png

https://cloud.githubusercontent.com/assets/12386237/7556804/264153be-f74e-11e4-973b-34fd86b00d45.png

**Comment by Trixter313** [comment]
Logging onto Wynncraft using Minecraft 1.7.10 will let you convert all of your old format emeralds to the new format.

**Comment by mnb9877** [comment]
yeah fixed it
