### ISSUE TITLE
NO MOD ARE EVER ONLINE

### ISSUE THREAD

**Issue by Preston111** [Wynncraft/Issues#1895]
the title says it all

**Comment by Trixter313** [comment]
I believe this would be better as an email to support@wynncraft.com since it's not an issue or bug with the game.

**Comment by Trixter313** [comment]
Also there is a box on https://forums.wynncraft.com that has all of the currently online staff listed.

**Comment by Jamdog** [comment]
There are probably mods online more often than you realise.  When I log in, there is often 3 or 4 of us online at once - we have a 'staff' chat channel, so can tell who is about.  It's just that they may be logged into a different server, or invisible and chasing down hackers - if you need a mod try asking on server 1 in Detlas, where we tend to hang out when idle.
Another useful way to find a mod is to look at the forum homepage, where there is a 'Staff Online Now' box on the right-side.  Hover over the avatar to see who it is, then you could use /find in-game to see if they are also logged into the game.  If there are mods online, then you can /msg us if it's important.

**Comment by AckroWynn** [comment]
Just to add to Jamdoggy's reply, you can also use the /report tool in order to call for a moderator if needed for different causes.
