### ISSUE TITLE
Fell through world, lost all my stuff

### ISSUE THREAD

**Issue by DexNeenja** [Wynncraft/Issues#1896]
So i was questing by myself and the game was pretty laggy and the world unloaded beneath my feet and i fell and got stuck in the world after is loaded in and I suffocated. I didn't have any soul points so i lost everything and i cant get it back. Please help.

**Comment by epicman739** [comment]
Sorry, we can't restore your stuff, though I'm sure you can find somebody nice enough to give you some free things. The next time this happens, just log off and wait for your soul points to regenerate.
