### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lol363** [Wynncraft/Issues#1898]
Me bug in chose a classes .

**Comment by lol363** [comment]
me bug in shose a classes

**Comment by lol363** [comment]
ssssssssssssssssssssvvvvvvvvvvvvvvvvvvvvvvvvvvvvvppppppppppppppppppppppppppp

**Comment by epicman739** [comment]
Please describe the issue properly. Don't just say that there's a bug.

**Comment by lol363** [comment]
i don't issue possoble

**Comment by epicman739** [comment]
What does that even mean?
