### ISSUE TITLE
Stucking in the selection room

### ISSUE THREAD

**Issue by Huckibucki** [Wynncraft/Issues#1899]
When i'm logging in as Huckibucki (Mage) to any server and choose my mage, i get teleported into the room where i just chose my class. There's no chance to get out, i'm stucking in this room. Please help me.  
![2015-05-15_22 24 58](https://cloud.githubusercontent.com/assets/12465705/7661269/68b6d24e-fb51-11e4-8a4f-0dac6dc52205.png)
![2015-05-15_22 25 05](https://cloud.githubusercontent.com/assets/12465705/7661271/69a69900-fb51-11e4-929a-dd922d14e786.png)

**Comment by Trixter313** [comment]
Typing /kill into chat will teleport you to the nearestvisited town.

**Comment by Huckibucki** [comment]
Ok thank you :D
