### ISSUE TITLE
Mount Wynn Empty Large Room 

### ISSUE THREAD

**Issue by jabramso** [Wynncraft/Issues#1901]
There is a large room in mount wynn... I got trapped there but was only able to escape because I regularly carry a TP scroll. Someone else was there at the same time with the same problem. There is no way out. 
To reproduce run into Mount Wynn and around the spiral downwards. When you see a black part of the wall with lava flowing out, stop there and enter the hole. You will get stuck.

**Comment by AckroWynn** [comment]
This problem has already been fixed on the build server, so my only advice is not to go down there until we have transferred the world over to the main servers.

**Comment by jabramso** [comment]
Thank you.
