### ISSUE TITLE
Jungle Fever Bug?

### ISSUE THREAD

**Issue by BloodLad** [Wynncraft/Issues#1902]
So I was finishing up the Jungle Fever quest, and I talked to Worid to finish it, I get all the XP and the Liquid Emerald, Buuut... My other 2 Liquid Emerald in my inventory was turned into the Almuj Liquid Emeralds, so I can't use them now... Anything you can do? Here are screenshots.
![2015-05-17_00 06 33](https://cloud.githubusercontent.com/assets/12479731/7669006/1738335c-fc2a-11e4-9b04-9863d4456eb3.png)
![2015-05-17_00 06 42](https://cloud.githubusercontent.com/assets/12479731/7669008/30e68efc-fc2a-11e4-9596-01036afccced.png)

**Comment by mizzkissy** [comment]
''The LE given in stage 6 cannot be spent, but when giving them to Worid, ensure you don't have any normal LE in your inventory, as there is a glitch which may cause him to take the wrong ones, leaving you with worthless LE.''

**Comment by BloodLad** [comment]
Oh. Alright, So Theres nothing they can do? :P Oh well. 2 LE isn't terribly hard to get back. Can that message be plainly stated somewhere, where everyone can see it though ? Don't want anyone else to get this problem
