### ISSUE TITLE
Stuck in a tree

### ISSUE THREAD

**Issue by keno511** [Wynncraft/Issues#1903]
It all happened when I was teleporting in the forest and I saw a small opening on the bottom of a tree, I got curious and I teleported into it and got stuck in the tree.

**Comment by vogelmet** [comment]
Typing /kill into chat will teleport you to the nearestvisited town.

**Comment by keno511** [comment]
I havent been playing that game for months, because of that problem...and the answer was that simple. I feel like an idiot, but thank you very much!
