### ISSUE TITLE
Cannot sell my liquid emerald!

### ISSUE THREAD

**Issue by 1littlebig1** [Wynncraft/Issues#1904]
I used to play Wynncraft a while ago, but I stopped playing. Yesterday, I got back on and I was going to upgrade my armor, but I could not sell my liquefied emerald back to the merchant. I noticed that the one that he buys is colored green for the name, but mine is the normal color for items. If you could get my my emeralds it would be greatly appreciated. Thanks.

**Comment by Trixter313** [comment]
Log onto Wynncraft using 1.7.10 and you will be able to convert your old LE to the new kind.
