### ISSUE TITLE
helmet not appearing 

### ISSUE THREAD

**Issue by mnb9877** [Wynncraft/Issues#1909]
My helmet wont appear when i put it on    
https://cloud.githubusercontent.com/assets/12386237/7716684/8310194c-fe63-11e4-963a-4020723e2996.png

https://cloud.githubusercontent.com/assets/12386237/7716689/8dd2c01e-fe63-11e4-9c73-66e661cece6e.png

**Comment by Moe-Ronickah** [comment]
This is an old and well known error.  This is an error where the server is not always updating the skin. Your best bet is to log off of the server, and then log back on.

[Using the "search" box, type in "armor". The search will find nothing, at first. Change from "code" to "issues", then re-run the search, and you will find many other issues posted of this same thing.]

**Comment by mnb9877** [comment]
its not a one time thing its been doing this for a while and i have logged off and on many times

**Comment by Moe-Ronickah** [comment]
Please note that I said that it was "your best bet", not a guaranteed cure. There are some known problems that exist between MC 1.7.10 and the various 1.8's.  I can only suggest that you try switching between different helmets.  In any event, it is an on-going issue.

**Comment by mnb9877** [comment]
ok but i thought you were a computer or something since that was copy pasted

**Comment by Moe-Ronickah** [comment]
I am of the "or something" variety; perfectly capable of writing comprehensible sentences and repeating myself when needed.  lmao

If you get something to work to make your helmet appear, please post it.

**Comment by mnb9877** [comment]
ok at least i know its not a one person thing {but i would like a way to simply turn off the special textures} if there isnt one

**Comment by CrosseyedTiger** [comment]
So i had this problem too and i had asked other players if they can see my Armour and they cant.

hope this extra bit of info helps!

**Comment by Moe-Ronickah** [comment]
To the best of my knowledge, armor skins do not show in any version of 1.7.  If anyone else has this problem, would you please try a non-modded version of 1.8 and let us know what happens when you use a version of 1.8?  I believe that this will help the developers.  Further, to my knowledge, there is sadly no work-around for armor skins in 1.7.

Please also note that WynnCraft has been rumored to move to 1.8 entirely in the foreseeable future, so you may want to go ahead and update to some flavor of 1.8.

**Comment by mnb9877** [comment]
i was in 1.8 im never in 1.7

**Comment by Trixter313** [comment]
This is an issue that is occurring no matter what version you're using and we'll just have to wait until the Wynncraft team fixes it. :)

**Comment by Moe-Ronickah** [comment]
According to a recent post by Ackro, Mojang became aware of the unique way in which WynnCraft was accessing the skin servers.  There was nothing wrong with the access method, however, Mojang had, apparently, not given anyone approval to use the specific method that WynnCraft was using.  Mojang then blocked WynnCraft's access to the skin servers.  Hence, WynnCraft skins no longer work as they were meant to work.  Until Mojang approves of the method used by WynnCraft, the WynnCraft skins will be off and on, apparently, for reasons that I have no idea of.

**Comment by Trixter313** [comment]
In case anyone's looking for the thread, here it is: https://forums.wynncraft.com/threads/what-just-happened.84489/#post-938622

**Comment by Trixter313** [comment]
Armor skins seems to be, at least for now, back.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
