### ISSUE TITLE
I spawn in the air

### ISSUE THREAD

**Issue by Dartiass** [Wynncraft/Issues#1910]
When i want to play my warrior, i click on the shovel, then i spawn in the air i can't move i can't do anything please someone help me.

~Dartiass
![2015-05-20_17 35 30](https://cloud.githubusercontent.com/assets/12531562/7729743/b8313580-ff16-11e4-9ce1-cdd8fa10b60d.png)

**Comment by Trixter313** [comment]
Try typing /kill. This will consume 2 soul points and you should respawn at the nearest visited town.
