### ISSUE TITLE
Bank problem

### ISSUE THREAD

**Issue by TheMusicGuy** [Wynncraft/Issues#1912]
Alright this time more detailed.
I can't take out items out of my bank (wich contains all kinds of stuff like quest items, emeralds, armour, etc.) i can put items in my chest, but once i putted it in my chest, it won't get out of it anymore. 
I have already sent an email, but the answer said i need to post the issue here.
The first one i posted got a label with duplicate on it (idk what it means by that label) and also a closed label.
I don't know what to add anymore so that it can be helped, but if you need my ign: The_Music_Guy (yes original ik)

Well atleast thank you for your time reading this

-The_Music_Guy

ps: that is what is left in my chest, if a picture was needed maybe![2015-05-21_15 36 11](https://cloud.githubusercontent.com/assets/12380150/7749616/2dd70edc-ffcf-11e4-9a48-b39f2261c497.png)

**Comment by Moe-Ronickah** [comment]
The term "Duplicate" means that this issue is already known to exist.  Tama closed your previous post because the issue is already known to exist, and he labelled it as "Duplicate" so that you, the mods, builders, and coders know why he closed it.

**Comment by TheMusicGuy** [comment]
Oh sorry for that, i didn't know, i'll close it

**Comment by MusicalWhovian** [comment]
I have come to notice that all the people having this problem have the word "music" in their name.
