### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by lol363** [Wynncraft/Issues#1916]
I am stuck in the block spider Dongon

**Comment by lol363** [comment]
save me if you like it

**Comment by lol363** [comment]
save me if you like it

**Comment by Trixter313** [comment]
The title "Bug" gives us no information about the bug at hand, as it's in the bug report section I think it's safe to assume that it's a bug.

Typing /kill into chat will make you respawn at the nearest visited town. Make sure you have at least 3 soul points before you do it though.
