### ISSUE TITLE
Water Dungion puzzle Issue

### ISSUE THREAD

**Issue by FatMatt1** [Wynncraft/Issues#1917]
Hi im on a small island off the coast of pirate town and I don't know if i'm doing the puzzle wrong, but it seems that the water isn't flowing out of the hole when I press the button. This wouldn't normally be a problem but I am locked in and I have no intention of trying to get out I just want to beat this. Thanks

**Comment by Moe-Ronickah** [comment]
If you do a search for "Water Dungeon"/ issues (not code), you will see that this has been reported before.  The advice given was that the water is flowing, it's a visual error, go ahead and finish the puzzle.

**Comment by FatMatt1** [comment]
Thank you

**Comment by FatMatt1** [comment]
Ok I give up Its not just a visual glitch, I Tried about 30 times in different ways for the water to reach the end its just broken
