### ISSUE TITLE
Trade Glitch deleted my Chestnut horse

### ISSUE THREAD

**Issue by higuy72597** [Wynncraft/Issues#1918]
I was trading my friend my chestnut horse so they could return it to me when I switched classes, and apparently it got deleted in the process, the trade was complete, and I switched classes, only to find out that the horse had been deleted. Here's a picture of my friend's inventory after the trade.
http://gyazo.com/fd849a002a41be731381e54b9db8ef1c

Please help with this issue, I spent all my money on my horse and I need it for fast transit.

**Comment by Moe-Ronickah** [comment]
I hate to be the bearer of bad news, but WynnCraft has a "no refunds" policy.  Unless you have video evidence of this occurring, you have no proof that it happened.  I'm not doubting you, I'm saying that there is no proof of what you are claiming.  Partly for that reason, it's been a rule of WynnCraft that there are no refunds.  You aren't alone, you aren't the first, and you won't be the last.  Sometimes, MC and WC glitch for unknown reasons.  
Good luck.

**Comment by higuy72597** [comment]
Okay, thank you for taking the time to read this anyways.
