### ISSUE TITLE
Can't find bat - Potion Making

### ISSUE THREAD

**Issue by ToneLomb** [Wynncraft/Issues#1919]
First, I want to apoligize, i'm not english so i'll try to explain my issue as i can.

My problem is simple, i have a quest : Potion Making. On wynncraft wiki i saw this :
https://wiki.wynncraft.com/index.php?title=Bat

It says that bat can be found in black road, near Detlas. I went to black road and there was nothing, only Wild Cow. I have screenshot. I saw video on Youtube, all people were to black road, and there was bat. But bats can be found around Rymek or Matlic too. Still 0 bats. I looked for more than 2 hours. I tried to find an adminstrateur in game but no one was here. So now i post my issue on this forum, and i hope that you'll answer me.

Thanks, ToneLomb

![2015-05-24_15 18 07](https://cloud.githubusercontent.com/assets/7395391/7788026/c9c814ce-0229-11e5-8619-a6df66158628.png)
![2015-05-24_15 18 14](https://cloud.githubusercontent.com/assets/7395391/7788027/c9cb0da0-0229-11e5-81af-92ed7b3e4f8f.png)
![2015-05-24_15 18 19](https://cloud.githubusercontent.com/assets/7395391/7788028/c9d7b29e-0229-11e5-8d3e-6f35234f4008.png)
![2015-05-24_15 18 43](https://cloud.githubusercontent.com/assets/7395391/7788029/c9d97304-0229-11e5-9188-c776538a4719.png)

**Comment by vogelmet** [comment]
the wiki have some old informations. try it in Maltic in the questcave under the city with the bat-witch

**Comment by ToneLomb** [comment]
Thanks i found bats ! Finally <3

**Comment by musicwolf** [comment]
You can also find bat is a hidden room under the route from ragni to nivlia forrest
