### ISSUE TITLE
Falling through map

### ISSUE THREAD

**Issue by Caligula-the-mad** [Wynncraft/Issues#1920]
I've been trying to start a new class of mage, but every time I select the class i get spawned in at Ragni then teleported away into the void, is says you need to talk with the king first but I get teleported into the void, and die then re-spawn in Ragni. It's just and endless cycle.

![2015-05-24_14 27 35](https://cloud.githubusercontent.com/assets/8356776/7788036/e1f5acbc-0221-11e5-8a6b-962c5db8457f.png)

**Comment by vogelmet** [comment]
Typing /kill into chat will make you respawn at the nearest visited town. Make sure you have at least 3 soul points before you do it though.

**Comment by Caligula-the-mad** [comment]
You're right! thanks.
