### ISSUE TITLE
Cant Tp into the world where i was 

### ISSUE THREAD

**Issue by JcGaming0** [Wynncraft/Issues#1921]
when i get into the character selection, i choose my warrior character, but lately when ever i choose my cahracter, it doesnt tp me to where i was in the world.. instead it doesnt tp me at all and im left in the black box to choose your character, i logged out for a couple seconds and this happened when i logged back in.. i tried to relog and i even tried to go to a different lobby - this has happened to a couple other people with different characters such as the archer and the mage... PLS FIX THIS!!

IGN: Jc_Gaming_

**Comment by JcGaming0** [comment]
Character*

**Comment by Trixter313** [comment]
Typing /kill will respawn you at the nearest visited town and take 2 soul points.

**Comment by JcGaming0** [comment]
okay thanks!
