### ISSUE TITLE
The Bank Is Broken

### ISSUE THREAD

**Issue by musicwolf** [Wynncraft/Issues#1922]
I'm stuck in the game because my bank is broken. I cant my items out of the bank And i cant redo quests. If i click on an item in my bank it will throw me out of the bank menu. I'm an older player on the server that why i thought that it was because the older items but i put a red powder II in my bank and i didnt work. (I have putted it in the bank with shift+left click. But you can't get your item with it out of your bank).

**Comment by epicman739** [comment]
This is usually fixed by relogging, rebooting, etc. Have you tried all of that yet?
Also have you tried accessing the bank from a different class?

**Comment by musicwolf** [comment]
i have try the Mage, Warrior, Assasin and Archer. I also try restarting my computer and laptop and relog my wynncraft. But thx for your help.
