### ISSUE TITLE
Tower of Accention Broken

### ISSUE THREAD

**Issue by lolmandru** [Wynncraft/Issues#1923]
I tried to proceed into the next room and I didn't teleport, The Guy says I can proceed, but I don't teleport when I step in the teleport area

**Comment by ThunderRemix** [comment]
Jump on the carpet or where it should be.

**Comment by lolmandru** [comment]
Nope, nothing works. Trying to get admins on to fix it.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/1774
Jumping, especially with a jump boost, should eventually teleport you. The search area for teleporting players is set a little to high so jumping at the exact moment it checks for a player teleports you eventually.

**Comment by lolmandru** [comment]
Ok, do you have a way to get an admin on to fix the height? And thank you.

**Comment by Trixter313** [comment]
They already know about the issue so all we can do in the mean time is wait for them to fix it. The bug was first reported about a month ago so it's appearing to be a more difficult to fix bug.

**Comment by lolmandru** [comment]
Ok, thank you!
