### ISSUE TITLE
Can't open this loot chest 

### ISSUE THREAD

**Issue by mizzkissy** [Wynncraft/Issues#1924]
There is a loot chest on Zhight Island which you can't open due the log above it. So please make a slab of it so you can open it.

The coordinates are: 
x -473
y 43
z -2842

![](http://i.imgur.com/esSqJZJ.png)

**Comment by AckroWynn** [comment]
Thanks! We will take a closer look into this!

**Comment by AckroWynn** [comment]
This has already  been fixed on the build server, so this will be fixed on main when we get a map push!

**Comment by mizzkissy** [comment]
Good job! :+1:
