### ISSUE TITLE
Breaking pots

### ISSUE THREAD

**Issue by Raxcu** [Wynncraft/Issues#1927]
I discovered that players can break pots by hitting a mob and a flowerpot at the same time 
![2015-05-27_20 06 52](https://cloud.githubusercontent.com/assets/12630429/7842725/ac78b3b6-04ad-11e5-9088-8bff4fed7579.png)
And afterwards
![2015-05-27_20 07 15](https://cloud.githubusercontent.com/assets/12630429/7842740/da4fd562-04ad-11e5-980d-c7d297769ae8.png)
I don't think this is a problem though because they reset every time after the server restarts.

**Comment by mizzkissy** [comment]
It is actually a way to get emeralds or items (I got an item once)...

**Comment by awemanrank100** [comment]
You can break pots without any mob interruption, though in 1.8, you have to aim a little higher. Breaking pots is a way to rarely get emeralds and every more rarely get items.
