### ISSUE TITLE
hallowynn mask quest teleport system broken

### ISSUE THREAD

**Issue by fossie2000** [Wynncraft/Issues#1928]
after i had defeated the mask i tried to leave and i teleported me outside of some rooms in the void and i just started falling
![2015-05-27_17 33 22](https://cloud.githubusercontent.com/assets/12633948/7849004/8b48f37a-0496-11e5-9c2a-06c2321e489c.png)

**Comment by epicman739** [comment]
/kill will get you out. Make sure you have at least 3 soul points though.
