### ISSUE TITLE
"Unable to find a server to connect to. please report."

### ISSUE THREAD

**Issue by xXDevastationXx** [Wynncraft/Issues#1930]
![2015-05-28_09 15 52](https://cloud.githubusercontent.com/assets/10757323/7860823/66ed1216-051a-11e5-8011-9bc25aa1331f.png)
How can I fix this?

**Comment by Trixter313** [comment]
Wynncraft recently tweeted, "We are aware of some issues with our host, and we may experience disrupted service until they have fixed the issue."

https://twitter.com/Wynncraft/status/603919263779422208
