### ISSUE TITLE
Troms Gateway Glitch

### ISSUE THREAD

**Issue by Wynnhelper** [Wynncraft/Issues#1934]
I have noticed That with a teleport spell or another kind of boosting spell players can boost or teleport into a one space crack on the sides of the secret Troms entrance. Without being sent back. This allows low level players to walk along and boost out on the other side gaining them entrance to Troms. Sorry I can not supply you with a picture but I'm wanting to help. hope you can fix or stop this problem if you can.

**Comment by AckroWynn** [comment]
The issue seems to be solved on the GM servers, so I would suppose that will be fixed shortly.

**Comment by Wynnhelper** [comment]
Okay. Thank You.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
