### ISSUE TITLE
Bug Probleme

### ISSUE THREAD

**Issue by MisterSoldat** [Wynncraft/Issues#1937]
At I join A wynncraft server I select my normaly class(Warrior) and I won`t teleport in the spawn. I still stay in a dark room with yellow wool as wall. 
![probleme](https://cloud.githubusercontent.com/assets/12669816/7896123/43bd6656-06af-11e5-835b-f7993be4d1ff.png)

**Comment by Trixter313** [comment]
Type /kill into chat. You will respawn at the nearest visited town.
