### ISSUE TITLE
My item bomb.

### ISSUE THREAD

**Issue by eoyg766** [Wynncraft/Issues#1939]
Hello Wynncraft support persons!
 
  I used an Item bomb today, and' I couldn't pick up my item! If you could assist me this would be great. Username : eoyg766

Some screenshots of proof can be found here : http://gyazo.com/0acbc2628210ec9923b70d94408c217c 

And also here 
http://gyazo.com/5c45a8077917f523a25d4c1f3e95fc40

Thank you for your time!

**Comment by Trixter313** [comment]
Item bombs aren't intended for the user to get the items, it's meant for the community around the bomb.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by Penguinepowadude** [comment]
You are not suppose to pick up your own items from your item bomb, they are for everyone else.
