### ISSUE TITLE
Troubled Tribesmen

### ISSUE THREAD

**Issue by WolfGrimm** [Wynncraft/Issues#1940]
In this lvl. 73 quest once you kill the boss mob you cannot leave the came with the tunnel because it just says "/" and you can't do /kill, the quest book then never updates so you can't finish the quest.

**Comment by Moe-Ronickah** [comment]
WolfGrimmm, I just did this quest as an archer, with no problems.  Would you try the quest, again, and let everyone know what happens?  Maybe the server was acting up?

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by Pingvin101** [comment]
I have this bug too i have the insect beacuse i did /kill but the book has't uptated so i can't complete the quest.
