### ISSUE TITLE
Glitch inside world, cant teleport out

### ISSUE THREAD

**Issue by DexNeenja** [Wynncraft/Issues#1941]
So i have a level 32 wizard and when i tried to play him today i was glitched inside the world and i cant use my teleportation scrolls, i have tried everything to get out. Please help.

**Comment by Trixter313** [comment]
Type /kill into chat and you will respawn at the nearest visited town.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
