### ISSUE TITLE
Unable to find a server to connect to. Please report.

### ISSUE THREAD

**Issue by Jellyf1sh** [Wynncraft/Issues#1942]
Although the twitter says all issues are fixed, apparently they are not. I'm reporting this issue as it asked. Any suggestions on what I can do to fix this, please help. If it's a server issue, I hope it's fixed soon. I'm running the latest version of Minecraft, unmodded.
![image](https://cloud.githubusercontent.com/assets/11895084/7900151/72819204-0714-11e5-94ba-eed4733e7c97.png)

**Comment by Toortle** [comment]
Same for me!

Minecraft IGN: Toortle

**Comment by Darkdragon902** [comment]
Same thing for me too!
Minecraft IGN: Darkdragon902
