### ISSUE TITLE
Unable to connect to server.

### ISSUE THREAD

**Issue by GruntZone360** [Wynncraft/Issues#1945]
I haven't been able to connect to the server for a while now. I thought it had been down time or something, but when I had checked the forum there was nothing explaining why I was unable to connect. The exact phrase I receive is "Unable to find a server to connect to. Please report." 

Heres a screenshot of the error: http://imgur.com/DSPVuur

Hope to hear some answers!

**Comment by Toortle** [comment]
Same for me!

**Comment by GruntZone360** [comment]
I think they might be updating the server, but why has it been down for this long and why does it look like there are people on the server? Like an odd 587/1044 

And if I needed to include my minecraft name: spymine
