### ISSUE TITLE
Macabre Masquerade Teleportation Glitch

### ISSUE THREAD

**Issue by Linkperez** [Wynncraft/Issues#1947]
This issue may not follow the correct format, but without this issue existing, my WynnCraft career would come to an abrupt end at level 25, as an archer.

I was attempting to complete a level 21 quest, Macabre Masquerade, also nicknamed as "Hallowynn 2014." After some bunch of struggles, I finally completed the task for the quest: Getting the Haunted Mask. I thought that there wasn't a teleportation area, so I was thinking of letting the Mask Guards kill me. But then, I found a teleportation area, and got glitched into a wall. I'm currently stuck at these coordinates: x: -371, y: 21, z: -1967.
![2015-05-31_12 46 11](https://cloud.githubusercontent.com/assets/12685596/7902982/3514df6e-0793-11e5-9493-652f45bdce2a.png)
I didn't even have a scroll, since they have a one-time use before needing to buy it again.
![screenshot 2015-05-31 12 45 02](https://cloud.githubusercontent.com/assets/12685596/7902985/5ee6ece2-0793-11e5-8ea5-b9e216531316.png)
Thank you for taking this time to review my issue. I praise to the WynnCraft staff that my WynnCraft journey may continue.
P.S. I am okay with being teleported anywhere on the map (that isn't inside a wall).
- Linkperez

**Comment by Trixter313** [comment]
Typing /kill teleports you to the nearest visited town.

**Comment by Linkperez** [comment]
Thank you so much!
