### ISSUE TITLE
Emeralds

### ISSUE THREAD

**Issue by eoyg766** [Wynncraft/Issues#1948]
Hello! 
 I have some emeralds (41 to be exact) that have no lore. I can not combine them with anything and cant find any like it. Please help me!! 

   Screenshot here http://gyazo.com/43f1592771ff5578e49947ad6c83059b

Thank you for your time!

**Comment by epicman739** [comment]
During the 1.12 update, emeralds/EB/LE were all given lore. However, the old emeralds were not automatically converted. Old EB and LE can be converted to the new ones if you use 1.7.10. Unfortunately you can't convert old emeralds to the new emeralds. However, if you switch back to 1.7.10, you can still use them to buy stuff from NPCs, or for identifying. Or you could keep them as a souvenier from the good old days.

**Comment by eoyg766** [comment]
Thank you for the help epicman739!
