### ISSUE TITLE
Can't get out of a black box after selecting the warrior class

### ISSUE THREAD

**Issue by GabettB** [Wynncraft/Issues#1950]
I've logged in with my lvl72 warrior, it worked fine, but then I changed to my other classes, they had no probem, but when I change back to the warrior, I find myself in a black box (maybe made out of dirt, because I can hear its sound, when I walk), and I can't get out. I've tried to log in and out, change server, restart my minecraft, nothing helpes. Yes, I've /kill-ed myself many times, but it brings my healthbar down to a half heart instead of killing me, and it does this every single time. I don't have any teleportation scrolls on me, and my other classes are still working fine, so I think this has something with the warrior to do. (I was in the Nemract bank, if it matters.)

**Comment by Trixter313** [comment]
Have you tried using /kill while you have only one heart?

**Comment by GabettB** [comment]
Yes. I've logged in and out, typed /kill  a million times, and finally it worked. (I don't know why, because I did the same thing as before.) I hope, that it won't happen again, thank you for your help! :)
