### ISSUE TITLE
Sewer Trap exit on the Emerald Trail broken

### ISSUE THREAD

**Issue by matheod** [Wynncraft/Issues#1951]
When you push the final button (wich is supposed to "reveal a water elevator which the player must climb", it's open a room with nothing inside. And just after that the wall behind you close so your are blocked.

**Comment by epicman739** [comment]
If you're still trapped there, do /kill if you have at least 3 soul points.

**Comment by Yoda15565** [comment]
This should hopefully get fixed soon as less experienced players who need to do the quest won't be able to get out and may get confused. That's the main reason I posted post #2015

**Comment by matheod** [comment]
I think you closed all existing issue about this.
