### ISSUE TITLE
Water not flowing down in a water lock at -930, -3500

### ISSUE THREAD

**Issue by tolin99** [Wynncraft/Issues#1955]
When the start button is pressed and the piston retracts to expose the water, the water just stays where it is, not flowing down like it should to activate the door opening.
![2015-06-02_21 18 12](https://cloud.githubusercontent.com/assets/8350700/7950782/c17febf2-096d-11e5-9d09-cd962f61b9c2.png)
![2015-06-02_21 23 29](https://cloud.githubusercontent.com/assets/8350700/7950781/c17e35aa-096d-11e5-89e5-79391df8b85d.png)

**Comment by epicman739** [comment]
Some people have said that this is a visual glitch and that you should just do the puzzle as if the water is flowing. Others say that the puzzle is actually broken. I have no idea who is right on this one.
