### ISSUE TITLE
WynnExcavaton Site A bug

### ISSUE THREAD

**Issue by mizzkissy** [Wynncraft/Issues#1957]
So I started the quest when I was like lvl 40 and I couldn't end it due a bugg. Now I am lvl 75 and I still can't do it. I really want do Site D, but now I can't do it.

My quest books says I have to talk to Tesh(a). If I click on Tesha he/she says:
Tesha: Take that to the vade, and don't read it!

So I went to the vade and the vade says this:

I don't know what I am supposed to do now...
I did /fixquests, but it didn't say I lost an item. I checked my bank and it's nowhere. 

![](http://i.imgur.com/ec7pylF.png)

![](http://i.imgur.com/Wkhzb1v.png)

**Comment by Trixter313** [comment]
Have you tried typing /fixquests ?

**Comment by mizzkissy** [comment]
Yeah: ''I did /fixquests, but it didn't say I lost an item. I checked my bank and it's nowhere.''
