### ISSUE TITLE
Wynn excavation site b (cant leave)

### ISSUE THREAD

**Issue by jayttt** [Wynncraft/Issues#1959]
I am doing the quest Wynn excavation site b. I have past the archeologist, and collected a purple shard, but when I attempt to leave through the back of the cave, it doesn't teleport me. Please help, I am stuck in this cave.

**Comment by epicman739** [comment]
/kill will get you out, but it costs 2 soul points.

**Comment by jayttt** [comment]
But how am I supposed to complete the quest?

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
