### ISSUE TITLE
The / Door

### ISSUE THREAD

**Issue by FlameGameMaster** [Wynncraft/Issues#1960]
I was doing the quest Troubled Tribesmen and i killed Aenara and got the insect of corruption, when i tried to go out the door to leave it just said / and teleported me back into the room? Am I misunderstanding something or is this a bug? So i am stuck here now, i know to do /kill to get out so i will be doing it shortly but i wanted to report this first. Here is a picture. http://imgur.com/atitE2q

**Comment by FlameGameMaster** [comment]
Now a new problem has arisen, Like i said i have the insect of corruption and when i tried to bring it to Inrekei like my quest book said, he just said the previous line. So it is now impossible for me to finish the quest. Here is another picture. http://imgur.com/dcvju01

**Comment by epicman739** [comment]
If you have multiple issues, please post another bug report.
