### ISSUE TITLE
Wynncraft Excavation D Quest bug

### ISSUE THREAD

**Issue by SupremeShikute** [Wynncraft/Issues#1962]
So I am doing wynncraft exacavation quest D and when you have to go to the site, there is nothing there I am at the exact co-ords and nothing pops up and not even a villager
![2015-06-04_10 41 49](https://cloud.githubusercontent.com/assets/12745364/7981482/1894259a-0aa7-11e5-88a5-2ff6c20a096f.png)
![2015-06-04_10 41 39](https://cloud.githubusercontent.com/assets/12745364/7981485/1dcb462e-0aa7-11e5-8696-7dc34d107641.png)

I even re-logged and I even did /class and it didn't work please fix this

**Comment by Trixter313** [comment]
Have you tried a different world?

**Comment by Emily7974** [comment]
I had the same problem at first as well XD You have to go up to the top of the temple. I'm not sure why the coordinates led to there, its a bit confusing.

**Comment by Moe-Ronickah** [comment]
Emily is correct, the coordinates lead to the start/ entrance to the stairs to enter Site D.  It would be clearer if a set of colored stones led up the steps to the entry room puzzle, however, there are none.  Maybe the build team will change this "soon" (tm).
