### ISSUE TITLE
Wynnexcavation Site C quest not working

### ISSUE THREAD

**Issue by KhaosTempest** [Wynncraft/Issues#1963]
So in the quest, i brought 1 of the purple crystals when i first got there to do the quest, and it started fine, and the purple crystal i brought disappeared(i assume the guy takes it). After going through the whole volcano I was teleported back out to the guy you talk to to start the quest and in the book it just says "report back to excavator picardus"(or whatever his name was...) When i talk to him though, it says that the purple crystal is needed to start the quest, which is odd considering i already did start it. But at this point i wasn't too worried since i had another one. Once i returned with the remaining crystal however, the same message appeared even though i had already started the quest and even had the crystal in my inventory, preventing me from continuing in the quest. I'm guessing this is some sort of issue with the ncp himself in how he reacts to being talked to. It may also be worth noting that i started the quest and had logged out for a day before continuing, as well as the fact that in the last section of the volcano i didn't pick up anything. Should i have picked up a crystal or something there? i sorta rushed through the end because i assumed there would be another section to it

**Comment by 3TheDunadan3** [comment]
Did you get the Lava Crystal from the Volcano?
