### ISSUE TITLE
/fixquests broken

### ISSUE THREAD

**Issue by JuiciFruit** [Wynncraft/Issues#1965]
The /fixquests command seems to give the player 2 purple crystal shards from the WynnExcavation Site B quest. The command doesn't care that the player already has the shard as well as giving 2 shards.

**Comment by Trixter313** [comment]
I believe the command is still an experimental feature so issues like this are too be expected. Hopefully it will be fixed soon. :)

**Comment by AckroWynn** [comment]
Fixquests always, at the moment, gives fixed amounts of items at all fix times. I hope it will be fixed by Crunkle soon.
