### ISSUE TITLE
Extra Breathing helmet

### ISSUE THREAD

**Issue by FatMatt1** [Wynncraft/Issues#1968]
I just noticed this, I have 2 Breathing helmets, exactly the same. Its a bit anoying so could I get that removed from my enderchest, Its taking up space

**Comment by Moe-Ronickah** [comment]
There is a way to remove it, on your own.  Do this with caution, as that helmet is not going to come back, so, if you want to help someone else, you will only have the one helmet for both of your classes, which may have you running to the bank, a lot.  This process works, but it is dangerous, if you make a mistake.

1st:  Put the "extra" helmet into your player (MC) inventory.
2nd  Fill up all of the available player inventory slots.  Emeralds will work fine for this, and you will want to have at least one slot with 2 or more emeralds.
3rd:  Replace the "extra" helmet with an emerald.  The "extra" helmet will fall to the ground, and soon disappear.
