### ISSUE TITLE
Loot Chest particle glitch

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#1969]
I'm not entirely sure if this happens in this exact area or not, but the particle for this Loot Chest doesn't go away.
![2015-06-07_00 17 36](https://cloud.githubusercontent.com/assets/9545223/8023004/ac689454-0caa-11e5-985e-6cd33f9d3b6a.png)
Also, I once got nothing from that Loot Chest. May or may not be a glitch as well.

**Comment by Trixter313** [comment]
I can confirm that this happens also. I see it from time to time.
