### ISSUE TITLE
WynnExcavation Site D Yellow Puzzle Bug

### ISSUE THREAD

**Issue by AshAngg2000** [Wynncraft/Issues#1972]
I'm in the yellow puzzle room and have completed game 1 and 2, but game 3 won't register as being completed even though I did the matching correctly... this was on server 8. I tried on other servers and they wouldn't let me get past game 2. Now when I try server 8 again, it won't even let me complete game 3...

I tried on server 16 and the quest worked fine...

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
