### ISSUE TITLE
Christmas Chaos Santa Text Not Working

### ISSUE THREAD

**Issue by CallingCheese** [Wynncraft/Issues#1973]
On the 6th of June 2015 I was Playing Wynncraft at around 6pm GMT and i was doing the Christmas Chaos Quest Now I Got To The Very end Of it Where You Are Meant To Talk To Santa And Collect You Rewards However When I Clicked On The Santa he spoke but then the server reset before he finished and then i went back on and i couldn't click him i went through the whole quest again and i still couldn't the quest book didn't update at any point nd other players in the lobby said they Could click him and he spoke. Now Im really Quite Disappointed That I Spent an hour of my time doing this to find that i can not finish it i hope you can fix this because i am regular player level 49 IGN: CallingCheese And Would really be angry if i could never complete this quest.

**Comment by Trixter313** [comment]
Typing /fixquests might solve your issue but it;s still an experimental feature so don't be surprised if it doesn't. Other than that I'm not sure there's much that can be done about it.

**Comment by CallingCheese** [comment]
thanks Trixter313

**Comment by Trixter313** [comment]
Anytime :)

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by AckroWynn** [comment]
The quest tool registers your stage where you need to speak to an NPac once, and will not allow a second time. The reward and the actual stage update only happens after the dialogue, which causes you to be in this state.

I am sorry, bur /fixquests is also not made for repairing causes like these.
