### ISSUE TITLE
I lost quest item that i need

### ISSUE THREAD

**Issue by brendon96068** [Wynncraft/Issues#1974]
My IGN is brendon96068 and i lost my corrupt potatoe by eating it. I was tricked by a troll video i was told there is a command to get it back that i do not know

**Comment by Trixter313** [comment]
The command is /fixquests
It should work but can be buggy at times.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
