### ISSUE TITLE
(Maybe A Bug) Tower of Ascension Floor 6 Alkev

### ISSUE THREAD

**Issue by CarsonK152** [Wynncraft/Issues#1975]
So as I'm fighting Alkev, the level 110 boss on Floor 6 of the hardest quest, Tower of Ascension, It suicides every time it gets to around 90,000 health (As I have attacked more, this number isnt fixed on 90,000, as it can be any number). I have tried this multiple times, but It keeps on blowing itself up and re-spawns at full health. A way to fix this would be to possibly remove this attack and replace it with something else (Please not ranged, i always die with range attacks).

                                    Snapshot of the boss, Alkev
![2015-06-08_13 46 41](https://cloud.githubusercontent.com/assets/12802331/8042443/ebc60812-0de4-11e5-9869-426a6b7e3e04.png)

**Comment by epicman739** [comment]
Some Tower of Ascension bosses have a self-destruct spell, which activates a certain amount of time after the battle begins. This is intended to encourage players to fight bosses in a group instead of solo.
