### ISSUE TITLE
Teleport doesn't deal damage

### ISSUE THREAD

**Issue by lesliep3579** [Wynncraft/Issues#1976]
I went through the changelings, and found that teleport was supposed to deal damage and blind players/mobs. While I believe that the blindness now only applies to mobs, everybody I've seen says that teleport is supposed to damage players. However, I've dueled 10 different people to try this, and I went to the nether. In all these cases, teleport didn't deal any damage whatsoever.

Is this a bug or intentional?

**Comment by epicman739** [comment]
Teleport only deals damage after the second upgrade, which is at level 26. If you aren't level 26 yet, your teleport will not deal damage.

**Comment by lesliep3579** [comment]
I'm level 75.

**Comment by lesliep3579** [comment]
Someone <3

**Comment by Trixter313** [comment]
It's possible that the feature was removed but the site hasn't been updated yet. Today I finally go back home from vacation so when I get a chance I will log on and see if my mage's teleport spell does damage to mobs I teleport through. Don't worry, you haven't been abandoned :)

**Comment by Trixter313** [comment]
Ok, I finally had a chance to log on and can confirm that teleport is still supposed to be doing damage.
Are you still having the issue?
