### ISSUE TITLE
loss of diving helmet

### ISSUE THREAD

**Issue by lucko4576** [Wynncraft/Issues#1977]
I don't know how, but I lost the diving helmet. I think it was by putting it in a chest. This means that I cant complete the under ice quest. Here's a pic. of my completion.
![2015-06-08_20 20 45](https://cloud.githubusercontent.com/assets/11022378/8048144/094463ca-0e1c-11e5-9e6f-2cb6a20bca6d.png)

**Comment by epicman739** [comment]
Have you tried /fixquests?

**Comment by lucko4576** [comment]
thx didn't know about it

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
