### ISSUE TITLE
hole in the ground

### ISSUE THREAD

**Issue by Scherzkeks** [Wynncraft/Issues#1978]
In a cave under the Candycane island is a hole in the ground (coordinates: 1142  34 -3171).
If you jump throught that hole you are landing in a cave without an exit.
And I jumped down -.- xD
Hole:
![screenshot 3](https://cloud.githubusercontent.com/assets/12816150/8061696/67c1cf22-0ecc-11e5-876a-c47ac56b1014.png)
Cave:
![screenshot 4](https://cloud.githubusercontent.com/assets/12816150/8061923/5c84d996-0ecd-11e5-9924-09bf2f256a92.png)

**Comment by Trixter313** [comment]
Topping /kill will make you respawn at the nearest visited town.
Once someone who has access to the build server sees this they will be able to fix it/see if it had already been fixed and just needs to be pushed to the main server. 😊

**Comment by Scherzkeks** [comment]
ok thx

**Comment by Trixter313** [comment]
I meant typing. Can't find where to edit on mobile.
