### ISSUE TITLE
No hunger when joining with the keep in command

### ISSUE THREAD

**Issue by skay159357** [Wynncraft/Issues#1980]
Hey WynnCraft
i have been in some problems.
It is when i join with auto join (its skip the class menu) i have no hunger and can't get hunger so i just keep losing health!

i hope u guys can fix it and i can't remember the command but i does so it skips the class menu when u join

**Comment by Trixter313** [comment]
Switching to a different server should fix the issue.

**Comment by skay159357** [comment]
Ok but what is the command course i hate it allways do it

**Comment by Trixter313** [comment]
Oh sorry, didn't see that part. The command should be /toggle autojoin but if not try typing /help
I'm on vacation right now so I can't check it right now, sorry!

**Comment by skay159357** [comment]
Its fine i'll just need the command to turn it off but it would be awesome if it did't do it :D

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
