### ISSUE TITLE
LE glitch

### ISSUE THREAD

**Issue by applebunny33** [Wynncraft/Issues#1981]
Currently I have found a glitch that could do a lot of damage to the Wynncraft economy. Its a glitch where if someone throws down a LE another person can throw one on top of it and pick BOTH of the LE's up. So the victim loses 1 LE and that person who scammed them now has 2 LE or however many LE this victim has dropped. I think this should be fixed before any other players figure it out!

**Comment by Trixter313** [comment]
This is an already acknowledged bug I believe and occurs with any item, not just LE's. Not sure if there's anything that can be done about it because of the nature of dropped items.

**Comment by applebunny33** [comment]
Awh. Well the best thing we could do is alert player about the glitch.
