### ISSUE TITLE
Lag Out Death

### ISSUE THREAD

**Issue by vidgamenate** [Wynncraft/Issues#1982]
Whenever I lag out while in combat, the game thinks I died and I lose soul points.

**Comment by epicman739** [comment]
What exactly do you mean by "lag out"? Also after you lose soul points, are you teleported to the nearest city/town, or do you remain where you are?

**Comment by vidgamenate** [comment]
Lag out means I lag and I lose connection to the game. After I lose my soul points it teleports me to the nearest town.

**Comment by Trixter313** [comment]
It sounds like something is killing you while you're lagging, which there's not much Wynncraft can do about. Do you lag out often? I believe that the best solution would be to fix the lagging out issue itself.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
