### ISSUE TITLE
Inactive guild: Asking to move leadership

### ISSUE THREAD

**Issue by Bcuhtotceor** [Wynncraft/Issues#1983]
I came back from a few months of inactivity and started playing again recently a around a week ago. During that time I've seen the massive downsize in the number of members and everyone left is inactive, including the guildmaster. Since I seem to be the only one left playing actively, I was wondering if leadership could be transferred to me.

--Yours truly Chocobutter
(P.S I've given more exp to the guild then all of the remaining members combined.)

**Comment by Trixter313** [comment]
I believe nothing can be done except you making your own guild. The master is the one who paid the LE and has full ownership. Sorry!

**Comment by Bcuhtotceor** [comment]
He didn't pay the liquid emeralds and neither was he the original leader. Ironwoodpick moved the rank over to Hedless after quitting himself. More or less just to clarify if any of this means anything to the appeal at this point.

**Comment by Trixter313** [comment]
The only way you'd be able to do this is with the permission of the current leader, so basically the current leader making you guild master rank. It wouldn't be fair to take leadership from the current owner without their permission, especially without a warning.

Maybe find a way to get in contact with the leader and ask him if he wouldn't mind logging on and transferring the guild to you?

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
