### ISSUE TITLE
Tower of Ascension Bug

### ISSUE THREAD

**Issue by lmbest** [Wynncraft/Issues#1984]
When i was level 40 i started the quest and did the 1st floor of level 1 then died, i'm now 47 and wanted to try again but when i want to go to the 2nd floor of level 1 it won't tp me, I hope you would look into this. Thanks

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/1774

**Comment by Trixter313** [comment]
If you believe that https://github.com/Wynncraft/Issues/issues/1774 is the same issue you're having, please close this one and watch it instead.
