### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by MzxGamer** [Wynncraft/Issues#1985]
My bug is,when i'm doing the quest grave digger and when i'm at the final bit where i have to give sayleros the dusty will,my chat says something but its not showed it just blank and it doesnt let me complete the quest.This only happens on my mage account.Please do something about this.

Minecraft username:Mzx_Gamer
Rank:Vip

                                                                                                                                                   Thank You!

**Comment by Moe-Ronickah** [comment]
First of all, please read the introductory information for posting bugs, as your title tells us nothing about the problem.

Second, do you have the will in your inventory?  If yes, and Sayleros is not recognizing it, try putting it in your hot bar, and trying to get Sayleros to recognize it.  If this works, please let us know, and please close the issue report.
