### ISSUE TITLE
Stuck in the ground.

### ISSUE THREAD

**Issue by IiStrawbsiI** [Wynncraft/Issues#1987]
I was in the sewers completing a quest when the lobby restarted. This is completely normal so I just joined a different lobby, but when I spawned, I was stuck in a 2 block hole with no escape. I don't know if this has happened to anyone else but, I am still stuck in the hole beneath the surface and above the sewers. I would really like to carry on levelling up my archer so please respond as quick as possible.

**Comment by Trixter313** [comment]
Typing /kill will respawn you at the nearest visited town. If this solves your issue, we'd appreciate it if you would close this (and the duplicate) issue. Thanks and have a fun time playing!

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
