### ISSUE TITLE
Xp Bug

### ISSUE THREAD

**Issue by Draidum** [Wynncraft/Issues#1988]
First, I apologize for my bad english i speak german :D 
Yesterday I farmed an hour for the guild and the XP have increased by 0%

![2015-06-11_21 18 56](https://cloud.githubusercontent.com/assets/12849932/8116111/78535058-1080-11e5-88ea-75c93eb7f71b.png)

and now you can see I'm # 13 with 635457xP 

![2015-06-11_20 46 39](https://cloud.githubusercontent.com/assets/12849932/8115406/5a1003ac-107b-11e5-8a8c-5614247fb841.png)

I have farmed for the guild and I always get 1000 xP and i always have /guild xP 100

![2015-06-11_21 17 30](https://cloud.githubusercontent.com/assets/12849932/8116137/a0466bae-1080-11e5-8b08-da9f3a38c2db.png)

Now I farmed again and nothing happens...can any1 help me how can i fix this?

**Comment by Trixter313** [comment]
It can take a while for the stats to update when you do something so I'd give it a couple hours or another day and see if it has updated by then. Other than that I don't see any issues.

**Comment by Draidum** [comment]
the last is a wrong picture :D

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
