### ISSUE TITLE
Ocean mini dungeon puzzle door will not open.

### ISSUE THREAD

**Issue by dtyn8** [Wynncraft/Issues#1989]
(I apologise if this has already been posted) The puzzle room door just won't open for me, I've tried changing my client to 1.8.1, looking up tutorials on youtube and copying the method into the puzzle, rushing to the door as soon as the puzzle has been "solved" I don't know if it is just how I am doing it, but it seems something has glitched. Thanks for taking the time to read.

**Comment by epicman739** [comment]
The ocean dungeon puzzle does appear to be broken for some people.
Sometimes it's just a visual error where the water doesn't appear to flow, sometimes the puzzle is actually broken.
The only possible fix I know of would be switching servers.

**Comment by dtyn8** [comment]
Thanks, I managed to get it open, but it took me a long time just constantly trying... Thanks for the advice

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by dtyn8** [comment]
I don't know if it is "resolved" as such. I can't quite tell how I opened it... I ended up just spamming the button and even then it only worked about 20% of the time... My worry is that others will get stuck there too.

**Comment by Trixter313** [comment]
I'm sorry, what I meant was that since this is a duplicate of https://github.com/Wynncraft/Issues/issues/1445 there's not really a need for both so what people normally do is close the duplicate and just follow the original. :)

**Comment by dtyn8** [comment]
Ok, I'll do that now!
