### ISSUE TITLE
(Now) impossible to get red crystal shard?

### ISSUE THREAD

**Issue by Noareames** [Wynncraft/Issues#1990]
When doing the quest Wynn Excavation Site C, I didn't get the red crystal shard while in the volcano dungeon and left. The questbook tells me to check with the NPC, but he tells me that I need the purple shard to begin the quest when I already have purple shards. /fixquests just gives me two purple shards and not a red one. Is there any way to get the red crystal shard now or am I stuck?

**Comment by chrisnumberz** [comment]
same exact issue, could I get a quest restart?
