### ISSUE TITLE
Lag Lead to Being Trapped in a Black Box?

### ISSUE THREAD

**Issue by Vacive** [Wynncraft/Issues#1992]
I'm not sure at all what happened to be quite honest... one second I'm trying to get bonemeal near Nemract for the Potion Assistant quest and the next my game crashes and returns to the multiplayer menu. I logged back in, went on a random server; next thing I knew I was a thousand blocks away on my coordinates inside a black box made out of wool. Again, no idea at all what this is. Please help, I literally just got my assassin today and was really hoping to use it ;-;
![2015-06-11_15 52 02](https://cloud.githubusercontent.com/assets/12857309/8125793/71bb1c8e-10ae-11e5-9180-a818ff2e6d5d.png)
![2015-06-11_15 52 10](https://cloud.githubusercontent.com/assets/12857309/8125796/75eb7b46-10ae-11e5-8f1c-4649e9589b32.png)

**Comment by Vacive** [comment]
Resolved: THIS MAY NOT BE A PERMANENT RESOLUTION TO THE ISSUE SO PLEASE STILL LOOK INTO IT. I happened to have more than one Soul Point on me at the time along with a teleportation scroll to Nemract, but in the case that someone doesn't have a teleportation scroll to somewhere, they may be stuck there for good. Please fix this. Thank you :)

**Comment by Moe-Ronickah** [comment]
There are two ways to fix this; teleportation or /kill.  Sometimes, teleportation doesn't work.  This has been a running issue for a while.

Would you be kind enough to "Comment and Close" this issue?  Thanks, in advance, and I'm glad you found a way out.
