### ISSUE TITLE
Trading named horse glitch

### ISSUE THREAD

**Issue by vidgamenate** [Wynncraft/Issues#1995]
When Someone traded me a named horse, the name wasn't there. It is there for the person who traded it to me, but not for me.

**Comment by Trixter313** [comment]
Horse naming is something that a player pays GC to do. It's saved on the player and not on the horse. I believe that this is an intended action.
If you'd like to name your horse, go to http://Wynncraft.com and you can buy GC to trade for the renaming ability in-game.
If this solves your issue, it would be great if you could close this. Thanks!
