### ISSUE TITLE
Fire and Xp

### ISSUE THREAD

**Issue by lilacsilver020** [Wynncraft/Issues#1997]
I know that putting fire on a weapon is very good, but if the mob dies from the fire, you won't get the xp. I think this is unfair and should be changed. Idk how it would be and if it can't then I understand

**Comment by epicman739** [comment]
This is a known issue, and it will be resolved when the powder system is redone in the Gavel update this summer.

**Comment by lilacsilver020** [comment]
OK Thanks.
