### ISSUE TITLE
Animal Dungeon Repetition

### ISSUE THREAD

**Issue by Unotheonly** [Wynncraft/Issues#1998]
There is something wrong with the Animal dungeon there was another player and i and we were at the Lava Cow boss but every time we defeated it it would just respawn this happend in world 14. Thank you for looking over this isuue.

**Comment by epicman739** [comment]
This is a known issue, some people say that killing it in the middle of the room will fix this.

**Comment by Unotheonly** [comment]
Can I be given the key to the dungeon again since it bugged out

**Comment by epicman739** [comment]
Unfortunately Wynncraft has a no-refunds policy, so you can't get your key back.
