### ISSUE TITLE
Negative Guild Emeralds

### ISSUE THREAD

**Issue by essem2** [Wynncraft/Issues#1999]
Look at the inventoryname, i cant buy any mobs in other terrirories and it says when i buy one mob that i need 3006 emeralds... how is this possible? 
![2015-06-15_13 42 26](https://cloud.githubusercontent.com/assets/12894598/8159258/1cf4c2d6-1365-11e5-975d-c6420d9d836c.png)

**Comment by essem2** [comment]
and I think some mods in the guild Nethers Ascent abusing their rights...

**Comment by epicman739** [comment]
If you have issues about other players' behaviour, please get some evidence of rule-breaking and post a ban report here: https://forums.wynncraft.com/forums/player-reports/
Make sure you read the guides first.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by essem2** [comment]
i payed 1 le to get in the positive and I hope it will not happen again... and a other bug: sometimes when I type /guild defend i get this error: An internal error occurred while attempting to perform this command
