### ISSUE TITLE
/fixquest bug

### ISSUE THREAD

**Issue by TheDeadKiller** [Wynncraft/Issues#2000]
I am sorry i used that command for no reason, it was too hard for me to do The Tower of Ascention so I wanted to test if it would give me the token but instead it gave me 1 "Healing Water" (idk what it is so I think it's a bug) and 2 purple shards.

**Comment by epicman739** [comment]
/fixquests probably won't give you ToA tokens, because you can get infinite amounts from killing the mobs inside. /fixquests will only restore items that you can only get once from the quest.
/fixquests is known to bug out sometimes. The Healing Water is for a level 69 quest called Grand Youth.
