### ISSUE TITLE
Quest Item Can't Dispose

### ISSUE THREAD

**Issue by vidgamenate** [Wynncraft/Issues#2001]
I did the quest in The Mummy's tomb but the problem is I completed it and I have an extra Mummy's bandage. I try to dispose of it, but it won't let me. It says This item is needed in a later quest.

**Comment by Trixter313** [comment]
As the message says, you do need the bandage for an important quest later on so you don't want to dispose of that.

**Comment by Trixter313** [comment]
If this resolves your question, it would be appreciated if you closed this issue. Thanks! :)

**Comment by vidgamenate** [comment]
I'm so dumb! I thought that The mummy's bandage only had one type. Thanks a bunch. the one I have was the temple of legends one :D
