### ISSUE TITLE
I use teleport spell and im stuck at -604, 76, -1112

### ISSUE THREAD

**Issue by giatoai159** [Wynncraft/Issues#2004]
Stuck at the wall and cant get out help :(

**Comment by Trixter313** [comment]
Typing /kill will teleport you to the nearest visited town at the price of 2 soul points.
If this solves your issue it would be appreciated if you closed this issue. Thanks and enjoy your time on Wynncraft! :)

**Comment by giatoai159** [comment]
Thanks

**Comment by giatoai159** [comment]
Thanks

**Comment by giatoai159** [comment]
Thanks
