### ISSUE TITLE
/fixquest work too good

### ISSUE THREAD

**Issue by sjukalegogubbar** [Wynncraft/Issues#2006]
so yesterday i was wondering where my item was and when i did /fixquests i got it back, normal but i also got 2 "Purple Crystal Shard" And another item that i did'nt need. And now when ive completed Wynn Exervation on ALL classes i still have those 2 Purpl Crystal Shards. And today i was trying if this worked and now i have 42 Purple crystal shards(2 or 42 it still takes same space so... i thought i culdtry it) and the first time i also got a "Chuckles' Favourite Feather" and 2 "Yellow Crystal Shards". And i have completed all quests on all four charracters so these items shouldnt be missing.
And here is my proof for the ones who want to see my issue.
http://imgur.com/qmc0ZKN,Nfup24T,1F8OBQ5,vyZ2jij,vEKdDLm#0

**Comment by sjukalegogubbar** [comment]
Well i did'nt find out how to edit the thread but many people in my guild have the same problem.

**Comment by Trixter313** [comment]
/fixquests is still an experimental feature I believe so something like this is bound to happen.
Also, duplicate of https://github.com/Wynncraft/Issues/issues/2000

**Comment by sjukalegogubbar** [comment]
I will then close this i guess.

**Comment by Trixter313** [comment]
I see that you've reopened this issue. Did you find something that differentiates this one from https://github.com/Wynncraft/Issues/issues/2000 or is there another reason for the reopening? We're happy to help resolve any issues you're experiencing to the best of our ability. We hope you have a great time and experience playing Wynncraft! :)

**Comment by sjukalegogubbar** [comment]
I missunderstood the answere or something... well i had a good reson yesterday when i opened it back... well also mine is more detailed, it can be a difference if the quests are completed or not? However, will close it again...
