### ISSUE TITLE
[Website] Guild search directs to the wrong link for guilds with spaces in name

### ISSUE THREAD

**Issue by Trixter313** [Wynncraft/Issues#2009]
When you attempt to view a guild's stats that has spaces in the name, it directs you to the wrong page and just ends up redirecting you back to the stats leaderboard.

Ex:
When you click on Kangronomicon's guild on https://wynncraft.com/#stats it brings you to https://wynncraft.com/guild/Kangronomicon , the guild's stats page. As it should.

But when you click on say, Nethers Ascent, it attempts to direct you to https://wynncraft.com/guild/Nethers-Ascent but just ends up bringing you back to the stats page.

What it should bring you to is https://wynncraft.com/guild/Nethers%20Ascent instead.

**Comment by TheRex94** [comment]
bien qu'il n'y ait pas rapporter nécessairement qu'il est super importan /! \ je créais ma bouteille et il a été lâché sur le sol au moment du redémarrage de telle sorte que je perdais liquide 5bouteille Emeraude vous aider, je suis suppli

**Comment by Trixter313** [comment]
French:
Malheureusement Wynncraft a une très strict aucune politique de remboursement de sorte qu'il n'y a pas beaucoup qui peut être fait. Tout ce que je peux suggérer, est d'essayer d'être conscient de si un redémarrage se produit dès la prochaine fois que vous tradez rien. Aussi, si vous devez signaler tous les problèmes à l'avenir, de créer une nouvelle émission plutôt que de spamming sur les questions non liées. :)

English:
Unfortunately Wynncraft has a very strict no refund policy so there's not much that can be done. All i can suggest is to try to be mindful of whether a restart is happening soon next time you're trading anything. Also, if you have to report any issues in the future, create a new issue rather than spamming on unrelated issues. :)

**Comment by Tama63** [comment]
This is fixed on our internal site build
