### ISSUE TITLE
I can't go into any games

### ISSUE THREAD

**Issue by sheepers-grass** [Wynncraft/Issues#2010]
I can not login into any games, I can click on them but it does not teleport me to any games

**Comment by Trixter313** [comment]
Have you tried restarting your computer and router? If neither of these
things work, usually just giving it a break for a few hours sorts things
out.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
