### ISSUE TITLE
Glitched into zombie dungeon wall

### ISSUE THREAD

**Issue by lilacsilver020** [Wynncraft/Issues#2011]
Somehow, i glitched into a wall in the area of the zombie dungeon with the two skulls. I was teleporting ahead bit by bit(I am a mage) and then just glitched through to a redstone area. i tried to glitch back but got stuck in the wall. now i cant do anything, cant use any teleportation scrolls.

**Comment by Trixter313** [comment]
Typing /kill will teleport you to the nearest visited town and consume 2
soul points.

If your issue is now resolved, we'd appreciate it if you closed this issue.
If it's not, we'd be happy to continue to assist you as much as possible.
Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by lilacsilver020** [comment]
Thanks :D it worked!
