### ISSUE TITLE
Stuck Underground

### ISSUE THREAD

**Issue by JorgDierens** [Wynncraft/Issues#2012]
Me and my friend are stuck underground when we tried to respawn we can't do annything other than changing class my mc name is SSG_Jorg and that of my friend is Namelezzz plz i hope you can help us i like this server verry much

**Comment by Trixter313** [comment]
Typing /kill into chat will respawn you at the nearest visited town for 2
soul points.

If your issue is now resolved, we'd appreciate it if you closed this issue.
If it's not, we'd be happy to continue to assist you as much as possible.
Thanks and we hope you enjoy your time playing Wynncraft! :)
