### ISSUE TITLE
Jungle mini dungeon puzzle door broken.

### ISSUE THREAD

**Issue by PingasGaming** [Wynncraft/Issues#2014]
I went to #yolo the jungle mini dungeon and now this.

![wynncraft glitch 2](https://cloud.githubusercontent.com/assets/12382958/8268344/844c2fa2-1782-11e5-9c25-eb4e4d64ecc3.gif)

**Comment by epicman739** [comment]
Try switching servers, relogging, restarting, etc. If all else fails, /kill with at least 3 soul points.

**Comment by AckroWynn** [comment]
That is supposed to happen. There is a little entrance to the right.
