### ISSUE TITLE
The Sewer Trap has no exit

### ISSUE THREAD

**Issue by Yoda15565** [Wynncraft/Issues#2015]
The Sewer Trap on the outskirts of Ragni doesn't seem to have an exit any longer (The old exit is now blocked off with cobblestone)
I've attached a few images regarding the issue.
![2015-06-20_18 38 26](https://cloud.githubusercontent.com/assets/12980438/8268376/a2cac94a-177b-11e5-8f0e-f6140617c6c2.png)
![2015-06-20_18 23 42](https://cloud.githubusercontent.com/assets/12980438/8268377/b95907b2-177b-11e5-8612-388c95b2d79b.png)
![2015-06-20_18 23 45](https://cloud.githubusercontent.com/assets/12980438/8268378/c000f138-177b-11e5-87cc-1985e3eed79e.png)
![2015-06-20_18 23 46](https://cloud.githubusercontent.com/assets/12980438/8268379/c685092c-177b-11e5-95ea-efae542e94ab.png)

**Comment by epicman739** [comment]
I'm pretty sure this has been reported before. If you can't get out, do /kill with at least 3 soul points.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/1951
I suggest closing this issue and following the original to stay up to date on the status of the issue. :)

**Comment by Yoda15565** [comment]
Firstly, sorry but I'm new to GitHub and didn't know how to check old issues.

Epicman, there is no way out unless you do /kill but there used to , which has been recently (Since Summer '14) been blocked off.
I was wondering if this was a build error or if it has been patched up for good?

**Comment by Trixter313** [comment]
That's ok that you didn't know how to check, it's not a huge issue. The staff member most likely didn't know there was an open issue.
If you think about it logically there's no point in having multiple issues open about the same thing. It just makes things more cluttered and harder to find a specific issue.
Like I said, if you just follow the original issue your will stay updated on the status. :)

**Comment by Yoda15565** [comment]
Alright, closing the issue and will follow the original. Sorry about any problems that may of been caused.

**Comment by Trixter313** [comment]
No problems here :)
