### ISSUE TITLE
Again i cant join the server WHY !? - other porblem

### ISSUE THREAD

**Issue by 7asoOonyi14** [Wynncraft/Issues#2016]
Again i cant join the server it says connection lost , please report , and also ! , before it make this i was online and i couldn't identify my relic dagger it says u need legendary or rare or .. etc

and it is legendary ?!!

**Comment by Trixter313** [comment]
Many people can't connect right now so it;s appearing to be a server wide
issue right now.

**Comment by mkotb** [comment]
Issue is resolved.
