### ISSUE TITLE
Not able to log in

### ISSUE THREAD

**Issue by mookiesue** [Wynncraft/Issues#2018]
Whenever I tried to log in around 3:30pm and past that time in Wisconsin it would say unable to find a server to connect to please report. In the morning around 8:00 am  on the same day it was working fine. I tried restarting my game and changing what version I was in.  

-mookiesue

**Comment by epicman739** [comment]
The servers are sometimes down while the Devs are doing maitenance. It fixes itself after a while, just be patient.

**Comment by Trixter313** [comment]
I just tested and the issue seems to be resolved. Are you still unable to log in?
