### ISSUE TITLE
I want to identify My dagger But i cant !!!!

### ISSUE THREAD

**Issue by 7asoOonyi14** [Wynncraft/Issues#2019]
it says you can only identify legendary - rare - special etc 

also he says i am too afraid to identify this item ?!

is it jut cause it is relic or it is a bug HELP

**Comment by epicman739** [comment]
Is it the Relic Dagger? That one is known to have issues with identifications. All other Relic items will identify fine. Also, most items with special (AKA accented) charecters in their name will not identify properly either.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/1312
What I suggest doing is closing this issue and following the original so you'll see when it gets fixed. :)

**Comment by 7asoOonyi14** [comment]
oh ok cause it is annoying i want xp bonus and other thing ok guys thx for helping :)
