### ISSUE TITLE
Excavator Vade speech and /find error

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#2022]
I don't have a screenshot for it, because it happened a while ago, but Excavator Vade's speech before you can start the quest is completely dark green, though only the name should be dark green and the speech being green, if it's supposed to be the same as other quest NPC's speech.

When typing /find, it says in red, "Invalid synthax: /find [player]". "synthax" should be spelled "syntax".

**Comment by Trixter313** [comment]
Thanks for reporting these textual issues! As soon as a staff member who can fix these issues sees this they will as soon as possible.
