### ISSUE TITLE
Right-Click detection bug

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#2023]
Occasionally, or with some mobs, seemingly always, right-clicking a mob can either make a right-click for a weapon not register or duplicate. For example, if you were to right-click a Dead Miner, it would display "Right-Right", rather than "Right" (If not playing as an Archer, of course). When I was right-clicking a Frozen Iron Golem, it would sometimes not register the click at all and nothing would happen. Not sure what causes it.

**Comment by Trixter313** [comment]
Thanks for reporting this issue! It's most likely a bug in the code that will hopefully be fixed when their coder(s) (Jumla I think?) sees this bug. Have a nice day!

**Comment by epicman739** [comment]
This may actually be a lag issue.

**Comment by Trixter313** [comment]
At first, I was agreeing with you @epicman739 but after some testing I'm pretty sure it isn't a lag issue. For me personally, I notice it when on archer and wolves are what seem to be the issue. If I try to cast arrow bomb while directly focused on a wolf in reach, only the first left click is recognized but not the two following right clicks. It's possible it affects more but this is the only one I can confirm with certainty.
