### ISSUE TITLE
Wynncraft chest error

### ISSUE THREAD

**Issue by TheRealMalmOo** [Wynncraft/Issues#2024]
I cant open a chest,but it have particles.Coords x -7 z -1196 please fix it.
![2015-06-22_13 34 21](https://cloud.githubusercontent.com/assets/12996309/8277351/a8721d12-18e3-11e5-993b-8eb93d83273c.png)
![2015-06-22_13 34 22](https://cloud.githubusercontent.com/assets/12996309/8277352/a8857d1c-18e3-11e5-99ac-43ef1b022280.png)

**Comment by Trixter313** [comment]
Thanks for reporting this issue! When a staff member with access to the build server sees this they will fix out as soon as possible. Have a nice day! :)

**Comment by AckroWynn** [comment]
Here is the link to the recently created forum post by Jamdoggy that is about these issues: 
https://forums.wynncraft.com/threads/repairing-broken-floating-loot-chests.83400/page-2#post-927763
