### ISSUE TITLE
Lacrona NPC responding with blank chat

### ISSUE THREAD

**Issue by ARCEcho97** [Wynncraft/Issues#2025]
So I (basically) finished the Suspending Flowers quest, but when I go to talk to Lacrona in Detlas, she responds with no text and does not take the 4 tainted aerolia flowers. Please fix!!! Kinda similar to an older glitch with the Wynncraft excavation.

Thanks!!!

**Comment by epicman739** [comment]
Have you tried switching servers, restarting Minecraft, etc?

**Comment by ARCEcho97** [comment]
Still doesn't work. Must be a glitch overall.

**Comment by Arsene78** [comment]
You are supposed to bring them back to Asher first because they need to be purified and cleaned. Then, you will be able to give Lacrona the Aerolia Flowers.
