### ISSUE TITLE
bug in the jungle 

### ISSUE THREAD

**Issue by TheRex94** [Wynncraft/Issues#2026]
I have 5 soul point I cherche The reliques and I'm died but I'm not K.O I'm died so I cherche my stuff and  
my stuff is dispawn therefore I am no stuff ad I don't have a change stuff and I'm blocked in Jungle.

please exept news by modo please

**Comment by epicman739** [comment]
I don't quite understand what you're saying.
So you went to get a Relic in the jungle and you died with 5 soul points, but you lost all your items?

**Comment by TheRex94** [comment]
yes and excuse my I'm french :)

**Comment by TheRex94** [comment]
if you can do something I would be very grateful

**Comment by epicman739** [comment]
Unfortunately there is no way to get your items back. However, I'm sure if you ask around there will be somebody willing to give you some decent gear for free.

**Comment by TheRex94** [comment]
thanks for you help very

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by TheRex94** [comment]
thank i close the question
