### ISSUE TITLE
Armor disappears when changing between them

### ISSUE THREAD

**Issue by Dar-krusos** [Wynncraft/Issues#2030]
When I tried to change armor skins, the armor I unequipped disappeared, even after switching classes, changing servers, and logging off.

![lost armor](http://i.imgur.com/I9NrNVD.png)

**Comment by Moe-Ronickah** [comment]
By "disappears" do you mean that you lost the armor or do you mean that it is not being rendered?
If you lost the armor, there is nothing that can be done about it, as it is apparently a MineCraft issue and not a WynnCraft issue.
If you mean that your armor is not being rendered, then this is a duplicate of #1909 and you should follow that bug report.

Either way, would you kindly close this report, *unless* I have missed something that you have said?  In which case, would you please explain further what you mean?
Thanks.

**Comment by Dar-krusos** [comment]
Yes, I lost it
