### ISSUE TITLE
Fix this rn please

### ISSUE THREAD

**Issue by PiggieIsMyIgn** [Wynncraft/Issues#2035]
Today I had around 124le, and I decided to show it to my friend via trade. I clicked the first stack(60), then clicked the 64 stacked, suddenly it just formed into one 64 stack, removing my other 60 le. I tryed everything, to make sure it wasn't just lag or me being stupid, but it couldn't been found. I understand you can't restore it, but please fix this for future purposes and if you can restore it that would make me beyond splendid.

**Comment by epicman739** [comment]
Known issue, adding a stack of LE to a part-stack of LE in a trade window can delete the part-stack. Unfortunately there is no way for you to get your LE back.
