### ISSUE TITLE
Tedious: Emeralds from previous updates

### ISSUE THREAD

**Issue by CountReavyr** [Wynncraft/Issues#2036]
This is just more tedious than anything, nothing abusive.
Emeralds and Emerald blocks from previous updates are in white text while the newer ones are in green with the added value. To change blocks I can just place them in the emerald merchant and they change into the new and improved emeralds, but the other emeralds are just kind of there and garbage. 

No big deal but I felt I should bring it up if it wasn't already addressed.

![image](https://cloud.githubusercontent.com/assets/13052542/8359952/9a1b5886-1b37-11e5-888b-4954746bf20e.png)

![image](https://cloud.githubusercontent.com/assets/13052542/8359955/a1e27e78-1b37-11e5-9f4f-8b00f576f4b5.png)

![image](https://cloud.githubusercontent.com/assets/13052542/8359960/a89147a4-1b37-11e5-837b-6c8e35ddace3.png)

![image](https://cloud.githubusercontent.com/assets/13052542/8359963/adcf56fc-1b37-11e5-94fa-830b35f0e17d.png)

![image](https://cloud.githubusercontent.com/assets/13052542/8359970/c1dce88a-1b37-11e5-8fcd-8563f4f61603.png)

**Comment by PingasGaming** [comment]
you can convert your blocks by trading them with an emerald merchant. the normal ones you can still use to ID stuff.

**Comment by Trixter313** [comment]
It's an already known issue and the only way to fix it is by trading with the merchants while using 1.7.10.
There's not really a workaround for this as it's built into Minecraft itself. I agree that it's extremely tedious and aggravating for some but sadly it can't be helped much. Have

**Comment by epicman739** [comment]
I think there was an old emerald to new emerald merchant on Selchar.

**Comment by Trixter313** [comment]
Hmm, that's an odd place to put one. I'll check when I get home to see if theres one there for sure or not done you're not 100%. :)

**Comment by ThunderRemix** [comment]
It's called the "Converter Merchent". It's in the bank.

**Comment by Trixter313** [comment]
Huh, good to know. Thanks! :)

**Comment by AckroWynn** [comment]
Yes, there is a coverting merchant up the stairs of the Selchar bank. It was added by Headset himself I believe in the latest update.
