### ISSUE TITLE
guild experience is not changing

### ISSUE THREAD

**Issue by fafa824** [Wynncraft/Issues#2037]
After playing for a considerable amount of time, i realized that the amount of guild experience had not changed. this angered/confused me as i had completed a 39,500 xp quest, with my guild experience at 100%, and my guild experience had not changed. I cannot post a picture as it cannot show the passage of time. This is the end of my Bug report.

**Comment by epicman739** [comment]
This is a known issue, guild xp seems to be broken for many guilds. The staff are aware of this and are working on a fix.

**Comment by TheRex94** [comment]
ok thanks for your help because i have xp guild bug to ;)

**Comment by kristan100** [comment]
with me the guild xp doesn't work either farming like 4 hours today and no guild xp :( that was a waste of time than
