### ISSUE TITLE
Outfit Glitch

### ISSUE THREAD

**Issue by doomrider023** [Wynncraft/Issues#2041]
I equipped some new armor, and it suddenly will NOT load... I have tried one piece at a time, I have also tried leaving and coming back... I also tried a full restart...

I play on 0% lag servers... please, can I get some help or something?!

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/1909
What we suggest doing is closing this issue and following the original to stay informed on the status of it. Thanks and have a wonderful time playing Wynncraft! :)

**Comment by doomrider023** [comment]
Oh, my apologies! I had no idea this has been reported before!

**Comment by Trixter313** [comment]
Apparently, this isn't an issue Wynncraft can fix and it's something Mojang "fixed" and as a result, the way Wynncraft was making armor skins is broken. Stated in this thread: https://forums.wynncraft.com/threads/what-just-happened.84489/#post-938622
