### ISSUE TITLE
Frudo isn't talking

### ISSUE THREAD

**Issue by Bilbo1968** [Wynncraft/Issues#2042]
Im doing the [Lord Of The Clock] Quest and Frudo won't speak to me.
Any help?

**Comment by Trixter313** [comment]
It usually helps to stand on the same block as the villager and look straight down and spam click. Wynncraft seems to have issues with clicking baby villagers. If that specifically doesn't work, all else I can recommend is trying as many angles as possible and maybe switching servers.

**Comment by Bilbo1968** [comment]
It worked!
Thanks a ton!😃😃😃

**Comment by Trixter313** [comment]
No problem! :)

If your issue is now resolved, we'd appreciate it if you closed this issue.
If it's not, we'd be happy to continue to assist you as much as possible.
Thanks and we hope you enjoy your time playing Wynncraft! :)
