### ISSUE TITLE
My mage class won't load

### ISSUE THREAD

**Issue by kjentes** [Wynncraft/Issues#2043]
I try loging into my other classes and they work fine, but i sit in this black box forever with my mage class. I can't seem to get out of it, and it has been a couple days. What can i do to fix this glitch?

**Comment by vogelmet** [comment]
Try /kill this should teleport you out but make sure you have more than 2 soulpoints

**Comment by kjentes** [comment]
thanks!

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue.
If it's not, we'd be happy to continue to assist you as much as possible.
Thanks and we hope you enjoy your time playing Wynncraft! :)
