### ISSUE TITLE
Armor skins not fully loaded

### ISSUE THREAD

**Issue by Slaten6** [Wynncraft/Issues#2048]
Armor Skins just started working again :D but my armor skin only loads waist up and my pants and shoes layer isn't there http://prntscr.com/7nnkie Yes I do have the armor layers  in the skin customization menu set to ON http://prntscr.com/7nnrj6

**Comment by Clarence117** [comment]
Exact same problem for me. :/ Hope this gets fixed soon

**Comment by epicman739** [comment]
This is happening to quite a few people, unfortunately there is no fix as of right now.
