### ISSUE TITLE
Warrior Falls through floor!

### ISSUE THREAD

**Issue by xDoobydragon84** [Wynncraft/Issues#2049]
So when I choose the warrior class, (First time I ever chose it) it spawned me in Ragni instead of the starting quest with the wagon and stuff. I didn't get to move around in ragni, the minute I spawned, I saw ragni and imediatly fell through the floor into the void. It said something about talking to the king, and using my Right-Left-Right spell.  I tried /kill. Wouldn't work. I tried relogging and gouing on another WC server. Didn't work. I tried selecting another class, (archer) and I spawned in the correct place.

**Comment by awemanrank100** [comment]
Maybe /die?

**Comment by Jamdog** [comment]
Try the /fixstart command.

This will restart your class, teleporting you to the starting quest area.  It only works if you have not completed the first quest.
