### ISSUE TITLE
Dungeons not showing up

### ISSUE THREAD

**Issue by LivingShadowWof** [Wynncraft/Issues#2051]
I tried to do the skeleton dungeon all worked well until I got to the boss room the boss and all the enemies  but not the room it was a super flat world I had to /kill myself to get out after killing the boss I got nothing for it. I then tried to do the spider dungeon the none of the dungeon would show up the enemies did but the was, once I looked around I found random buildings and one block thick trees there was nothing in side the buildings or at least the ones on the ground then there was just a cliff had to die to get out again my key was used both times

**Comment by Trixter313** [comment]
I believe that this issue was temporary. Is it still happening?

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
