### ISSUE TITLE
Not able to get leggings relic

### ISSUE THREAD

**Issue by AssassinGamer13** [Wynncraft/Issues#2053]
Im not sure if it is a true issue, and I'm just missing something, but it does feel like an issue for me. So, first of all, when you try to do the parkour to get to the crystal, at one point in the parkour, it tells you that "you are not ready for this region yet", but this seems to be not right because I'm doing the parkour for a relic and the parkour goes straight up, please fix this. Or I'm just missing something that is very obvious

Watch this video: https://youtu.be/fe4-ALxfeCA
It shows the problem.

**Comment by epicman739** [comment]
All armor/weapon relics have an 8-hour cooldown before they can be accessed again, I would assume that's why you can't get to the relic.

**Comment by AssassinGamer13** [comment]
Wrong. It won't let me finish the parkour. Watch the video.

**Comment by epicman739** [comment]
That's interesting...
I can't think of any reason why that would happen then.

**Comment by AssassinGamer13** [comment]
i know it is, I can't complete my full set of relic armor. I only got the boots, chestplate and helmet.
