### ISSUE TITLE
Guild Ranking Glitch?

### ISSUE THREAD

**Issue by DoctorTreeko** [Wynncraft/Issues#2055]
So I was playing Wynncraft and grinding in Herb Cave and camp there a minute a time while on a safe platform until I saw someone had called a guild war and I went there, but I was too late the peculiar thing was no one was online so I thought maybe they started before they logged out and then I typed /g Wth and then my name had 2 stars aka I am a captain so I was like "OMG!!!"
![2015-07-02_23 02 56](https://cloud.githubusercontent.com/assets/13161420/8493463/1d450f18-210f-11e5-915a-1f40c0e4fa59.png)

As you can see I was promoted to Captain and then after I created a guild war by myself and I won back the territory only to find out I was not anymore a Captain. Now here is the creepy part it did not state I was demoted and everyone was offline and when I logged back into a world my rank was gone! I did not understand it was not in the /guild log and I want to understand what happened.

![2015-07-02_23 03 08](https://cloud.githubusercontent.com/assets/13161420/8493480/5b852d30-210f-11e5-9493-5c3b698180cc.png)

As you can see I have 1 star meaning I am a recruiter. And you could also see that we won Katoa Ranch back which was the war I created. Plz Help! :)

**Comment by Trixter313** [comment]
How are you sure someone didn't log on and change your rank? Also, it didn't notify you when you were promoted to captain, did it? If not, then it's not surprising that it didn't notify you when you were demoted.
You could ask someone who has the ability to promote you to promote you back up to Captain, maybe?
