### ISSUE TITLE
Getting trapped while picking classes

### ISSUE THREAD

**Issue by ntren1** [Wynncraft/Issues#2056]
So while I was playing, I did /class to pick a different class and I found my warrior and my mage classes trapped in the black room that you pick classes in. I attempted to use my teleportation scroll to get out however I couldn't teleport. I am not sure how this happened or how to replicate the issue.
![2015-07-03_03 21 33](https://cloud.githubusercontent.com/assets/13162328/8494446/156d94a8-2133-11e5-9271-945fee858600.png)
![2015-07-03_03 21 24](https://cloud.githubusercontent.com/assets/13162328/8494448/1cd3837e-2133-11e5-9bd3-7aa7aa76111c.png)

**Comment by Trixter313** [comment]
Typing /kill into chat should get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
