### ISSUE TITLE
I am Stuck in a wall/ground and teleportation scrolls aren't working

### ISSUE THREAD

**Issue by GEORGESIMPSON** [Wynncraft/Issues#2059]

**Comment by Trixter313** [comment]
Typing /kill will get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by GEORGESIMPSON** [comment]
Ty! =3
