### ISSUE TITLE
Stuck in class section?

### ISSUE THREAD

**Issue by Jk725** [Wynncraft/Issues#2060]
When I pick my assassin class in Wynncraft it doesn't do anything... I press the assassin class and it keeps me in the black box that you pick your class with. I have tried /class and picking it again and nothing happens. I restart my minecraft, try again, and nothing happens. Please help I cant use that class and I have a lot of good weapons on it. Heres proof that Im stuck in the class part.
http://gyazo.com/00e49607844f434820d0e836235a088a
In the background you can see that im stuck in the wool section after I pick my class please help.

**Comment by Trixter313** [comment]
Typing /kill will get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by Jk725** [comment]
It did think you very much :)
