### ISSUE TITLE
NoCheat is broken

### ISSUE THREAD

**Issue by bleedoutkid** [Wynncraft/Issues#2061]
hi, id like to tell you about nocheat being buggy. its not all of the time when this happens, but when it does it is annoying. if i try to do lobby parkour sometimes, i get kicked for "flying". if i try to do the tree parkour in animal dungeon, i get kicked for "flying". if i duel an archer or warrior, and am knocked in the air, i am kicked for "flying". i don't know why it happens, but it does, and is very annoying. if you could find a way to fix this, like maybe changing the file so you can be in the air for more than 2 seconds, it would be amazing. i know that all the developers are busy, but i dont want peoples experiences ruined by in game protection mechanics, such as the anti fly. thanks for all the help, and hard work on the server.

**Comment by epicman739** [comment]
This could be a lag issue.
