### ISSUE TITLE
Server restart mid talking to someone.

### ISSUE THREAD

**Issue by CiPCheech** [Wynncraft/Issues#2062]
Hello I am CiP_Cheech,
Yesterday I was doing the Chraftmas Chaos Quest. I was near the end of the quest and in my quest book it said: Return the present and report back to Santa. I went to santas Island and talked to Santa, Midway through talking to him the server restarted. When I logged back in I could not talk to santa. What do I do? Please help.

-CiP_Cheech

**Comment by Trixter313** [comment]
Have you tried typing /fixquests
