### ISSUE TITLE
Stuck in the neather

### ISSUE THREAD

**Issue by FatMatt1** [Wynncraft/Issues#2063]
I went into the neather to see what it was like and now im trying to get out, but I spawn mid portal fall down, and get sent back into the neather, Could I get a tp or something?

**Comment by Trixter313** [comment]
Have you tried typing /leave into chat?

**Comment by FatMatt1** [comment]
Lemme try that quick

**Comment by FatMatt1** [comment]
I made it out, I spawned in with lag and I was able to just walk out, 
The one time im happy the server is so laggy
