### ISSUE TITLE
im stuck creeperkiller627

### ISSUE THREAD

**Issue by chandler2003** [Wynncraft/Issues#2064]
im stuck in a blcok in the animal dungeon at X:-10911 Y:6 Z:-10339
![2015-07-04_23 12 42](https://cloud.githubusercontent.com/assets/13180475/8509426/504c6f20-22a2-11e5-9c10-afc644f49289.png)

**Comment by Trixter313** [comment]
Typing /kill will get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
