### ISSUE TITLE
[Quests] Bob's Lost Soul Incorrect Blacksmith Location

### ISSUE THREAD

**Issue by Trixter313** [Wynncraft/Issues#2068]
In the quest book it says to go to the Blacksmith in Ternaves but the Blacksmith is in the little town near Ternaves, not in it. Wedyf says the correct location, "There is a blacksmith close to Ternaves who does this kind of stuff." but not the quest book.

I told a moderator about this when this quest was first released (before I knew about this bug tracker) and they said it would be fixed but it still isn't so I'm assuming they forgot to report it to anyone.

**Comment by Trixter313** [comment]
I believe you have this issue and https://github.com/Wynncraft/Issues/issues/1936 confused @Tama63 . They are different issues. The other one is talking about the colors of Wedyf's text.

**Comment by Tama63** [comment]
Ah okay, I'll check the game files for this but often the quest
descriptions are for the general area.

On Mon, 6 Jul 2015 at 11:44 Nick Cipriani <notifications@github.com> wrote:

> I believe you have this issue and #1936
> <https://github.com/Wynncraft/Issues/issues/1936> confused @Tama63
> <https://github.com/Tama63> . They are different issues. The other one is
> talking about the colors of Wedyf's text.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/2068#issuecomment-118706610>.
>
-- 
Chris Ireland,

Sent from my iPhone
