### ISSUE TITLE
Stuck after collecting crystal from Wynnexcavation site B

### ISSUE THREAD

**Issue by fiper1** [Wynncraft/Issues#2071]
I got stuck in the ground after i collected the crystal and i cant get out i tried relogging but was still stuck

**Comment by epicman739** [comment]
Do /kill with at least 3 soul points.

**Comment by Sonicjumper** [comment]
This happened to me as well, though epicman739 has the right idea: you can type /die or /kill to respawn your character at the nearest town. I'll just confirm this has happened to multiple players recently.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
