### ISSUE TITLE
Me and my friend are stuck in the ground.

### ISSUE THREAD

**Issue by Boonsbox** [Wynncraft/Issues#2072]
After the restart of the server, i joined server 18, and was at the bottom of the world, a flat world. My friend also had this occur to him. We left and rejoined server 2, and we were stuck in blocks. We couldn't get out and still are stuck now. Please help in some way, we really love and enjoy playing wynncraft and are upset that we cannot play anymore.

**Comment by TheRex94** [comment]
I advice you to do /kill

**Comment by epicman739** [comment]
Make sure you have at least 3 soul points though.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
