### ISSUE TITLE
Guild XP not working

### ISSUE THREAD

**Issue by Marianol24** [Wynncraft/Issues#2074]
The guild XP I've contributed has been stuck at 79.500 for about a week. I have grinded mobs for hours with /guild xp set to 99, and yet I'm still stuck at that.

**Comment by Trixter313** [comment]
This is a currently known issue and all we can do is wait for it to get fixed by staff.

**Comment by ltvuong** [comment]
We've been patiently waiting for roughly 3 weeks now.

**Comment by TheMineNerf** [comment]
its been about a month even more and its not fixed yet

**Comment by Marianol24** [comment]
I know right

**Comment by PenguinJ2** [comment]
This is happening to my guild still. When it was first made one member of the guild could contribute about 100 xp before it stopped. It comes up saying how much guild xp we earn after we kill mobs, but doesnt update.

**Comment by DonkeyThunder** [comment]
I am  from the same guild as PenguinJ2 and I have set my guild xp to 100% for all my quests and grinding but it is still on 372 xp and which it got too when it was first created and we cant add more people to the guild until we level up so please help.

**Comment by PenguinJ2** [comment]
Why has this been closed? as far as I'm concerned it hasn't been fixed

**Comment by mewking** [comment]
Still confirmed

**Comment by Kidgib5** [comment]
Guild XP Glitch is still an issue.
