### ISSUE TITLE
Emerald Trail: Potion Path Cut Off

### ISSUE THREAD

**Issue by Storm-lord** [Wynncraft/Issues#2077]
In the Emerald Trail (by Ragni), walking into the underground located in the sketchy potion vendor's  house normally leads you to the exit under the second house (which is located on the opposite end of the trail). However, there is a cobblestone block blocking the waterway, which doesn't allow the player to swim up. This forces the player to /kill themselves, since there is no escape from their current location. The "stuck" coordinates are -508 65 -1545. I'm not sure whether or not this is intentional, however I doubt it since this exit used to exist in previous map updates. I have enclosed images of: Being in the Trapped Position, and Viewing the Exit from the Other Side.

![2015-07-07_17 42 45](https://cloud.githubusercontent.com/assets/13227016/8558105/09a6c6c6-24d0-11e5-82c5-f261acc80b18.png)

![2015-07-07_17 44 33](https://cloud.githubusercontent.com/assets/13227016/8558124/22e2381e-24d0-11e5-9d3c-e7ea50c8c358.png)

![2015-07-07_17 44 38](https://cloud.githubusercontent.com/assets/13227016/8558117/16a858a8-24d0-11e5-917f-24a615664fb5.png)

**Comment by epicman739** [comment]
Known issue, Sage33 said that he would fix this on the build server and it should update soon.
