### ISSUE TITLE
/fixquests glitch

### ISSUE THREAD

**Issue by Notthebacon** [Wynncraft/Issues#2078]
![2015-07-07_19 52 29](https://cloud.githubusercontent.com/assets/10939745/8560088/6082549e-24e2-11e5-8408-c80cb3710536.png)

So I did /fixquests and that happened... I got extra Purple crystal shards and a extra pair of Quest boots

**Comment by Trixter313** [comment]
This is a known issue and we are waiting for a fix. Hopefully it won't take long. :)
