### ISSUE TITLE
Guild xp

### ISSUE THREAD

**Issue by Dodikabird** [Wynncraft/Issues#2079]
I have been in troms, nesaak, and even detlas to try to get guild xp... I typed ./guild xp 100 and it says i give it all to the guild but the guild's xp bar is left unchanged and all that xp is going to waste... My guild cannot go past lvl 1 because the xp doesn't register...

IGN: dodikabird
Guild: TLD | The last dodos
E-mail: szsm2003@gmail.com

**Comment by TrashcanMan** [comment]
Known issue, it has been affecting many guilds recently. A fix should be on its way.

**Comment by Dodikabird** [comment]
Okay thank you then i will just wait :)
