### ISSUE TITLE
Outside The Map!?

### ISSUE THREAD

**Issue by BatPanda** [Wynncraft/Issues#2084]
Dear Wynncraft,
As I (agentekul) and my friend (Xx_GreatCorey_xX) tried to enter the Zombie dungion via the normal way we ended up outside the map. we are currently stuck outside and cannot play D: here is a picture to prove this:
![2015-07-11_19 06 44](https://cloud.githubusercontent.com/assets/9087069/8634844/8b58ccd0-2801-11e5-8bc0-cf392965cccb.png)

**Comment by BatPanda** [comment]
![2015-07-11_19 19 42](https://cloud.githubusercontent.com/assets/9087069/8634850/d678ea7e-2801-11e5-8328-48a37d8727ea.png)
Its almost like the dungeon itself has been overridden , but as you can see the mobs and wall parts still seem to be there... odd.

**Comment by BatPanda** [comment]
Btw... just found out the dungion is actually not there at all... just tried to go back in and was but back outside the map again!

**Comment by Moe-Ronickah** [comment]
Your only options are to use /kill, with 3 or more soul points, or to use a teleport scroll, with 2 or more soul points.  I believe that this is a lag issue, and I may be wrong, Trixter313 is a better source for why this happens than I am.

As this has happened in the past, it will probably be closed with the tag "duplicate", so don't be surprised if that happens.  Thanks for reporting this, and have fun.

**Comment by BatPanda** [comment]
ok, ty

**Comment by AckroWynn** [comment]
If this happens on multiple servers for multiple people, I think we have an... Issue.
