### ISSUE TITLE
I fell through the world

### ISSUE THREAD

**Issue by EpicOverKill567** [Wynncraft/Issues#2089]
Hello developers of wynncraft, my mc name is GrimSkullGaming and I kinda fell into the ground, the game bugged and sent me into a super flat world and when I went into another server im in the ground, if you could fix this and get my assassin character out of the ground it would help a lot, please!

**Comment by Trixter313** [comment]
Typing /kill into chat should fix your issue.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by EpicOverKill567** [comment]
Thank you so much
