### ISSUE TITLE
Troms not Capturable Glitch

### ISSUE THREAD

**Issue by MajesticMaj** [Wynncraft/Issues#2091]
No one is able to take Troms and I think this issue should be fixed. If any guild attacks Troms and gets it. Once they log back in. The other guild still has it.

Video Proof: https://www.youtube.com/watch?v=T3BA3yl92KE&feature=youtu.be

**Comment by mizzkissy** [comment]
Deluxe still gets the xp. So they have a territory they don't have to defense and get a lot of xp for free (due Tol) Hello? That's so unfair. Please remove some xp from them if you fix this...
