### ISSUE TITLE
[Dungeons] Silverfish and Zombie dungeon door bypass

### ISSUE THREAD

**Issue by Trixter313** [Wynncraft/Issues#2093]
You can stand right next to the beginning three pressure plate door, switch worlds, and the door will most of the time be open on the new world for a few seconds, enough to go through and not have to put items on the 3 pressure plates.

I'm assuming this happens when a player leaves those chunks and the redstone get 'frozen' so the door stays open until the chunks are reloaded. If this is true, the door isn't always open because some players take longer than others with the parkour so the items have time to despawn and the door can close properly.

A possible fix would be to add more things in the area after the door to occupy the player long enough for the items to despawn and the door to close correctly. Or, I'm sure you could rewire the door in a different way to avoid it at the source completely. Thanks!

**Comment by AckroWynn** [comment]
Never knew about this!
We will see what can be done.

**Comment by Trixter313** [comment]
Edited, can be done with the Zombie Dungeon also.
And, while things are possibly going to be changed, I'm just gonna leave this here in case you feel like adding this in too =3: https://forums.wynncraft.com/threads/silverfish-dungeon-needs-mobs-that-drop-emeralds.83065/#post-924366

**Comment by Trixter313** [comment]
You can reproduce yourself (most easily with Zombie instead of Silverfish) by doing the puzzle on server A, quickly going to and killing the boss on server A, then switching to server B and going to the door. Switch back to server A and the door will still be open for a few seconds as long as no one else went through and you went to the boss fast enough.

**Comment by Trixter313** [comment]
Also, here's a link to a video showing the issue. In case you needed any more validation xD
http://youtu.be/EtKAM5SoY7g
