### ISSUE TITLE
Crash During the "Pit of the Dead" Quest

### ISSUE THREAD

**Issue by SergeantRojo** [Wynncraft/Issues#2097]
When ever I get close to the pit during the "Pit of the Dead" quest i crash.  I can walk around it and or go anywhere else on the map and not crash.  Only when I get close to or inside the pit I crash.  I talked to Merloni (the NPC for the quest) to see if that would help but the same thing happens.

**Comment by Trixter313** [comment]
Are you still crashing, even now?
