### ISSUE TITLE
Unable to login - Unable to find a server to connect to

### ISSUE THREAD

**Issue by EmpoleonAvalon** [Wynncraft/Issues#2099]
Whether this a maintenance or a legitimate error, the text states to please report. The current time is 10:47 PM (UTC -5:00) and I have been attempting log in for approximately 10 minutes. I also attempted log in approximately 2 hours ago, at which time the same message was displayed. Please info or fix!

**Comment by Trixter313** [comment]
I just logged in right now, are you still having the issue?

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
