### ISSUE TITLE
Wynncraft Issues 

### ISSUE THREAD

**Issue by BateauSD** [Wynncraft/Issues#2102]
Hello, im player Batya in Wynncraft and i found issuel in quest entry Temple of the Legends. VIP +68 lvl done quest Temple of the Legends, VIP ride in default member, default player can go to Temple. Sorry per my English.
P.S my forum account in Wynncraft Scout, can im give VIP for it?

**Comment by Trixter313** [comment]
The temple is not VIP only so non VIPs should be able to go in, as long as they did the quest. Did I understand your issue correctly?

**Comment by BateauSD** [comment]
Temple of Legends location open after quest, but VIP which finished quest can to go Temple with player which quest not started. VIP ride in player, player enters in temple.

**Comment by BateauSD** [comment]
You fixed glitch?

**Comment by Trixter313** [comment]
Ah, I see what you're saying now. A VIP can ride a player who didn't do the quest and the player can then enter. Once a staff member sees this, it'll be fixed. Thanks for reporting!

**Comment by AckroWynn** [comment]
We are aware of several glitches that are abused by VIPs this way.
This will probably not be fixed until Gavel+
