### ISSUE TITLE
I'm stuck in a wall

### ISSUE THREAD

**Issue by Kaui101** [Wynncraft/Issues#2104]
I'm stuck in a wall. I was in a dungeon, and then there was to many mobs for me so I tried to, and I found a button *Pressed it* and I when't in a little room, but there was no way out, no buttons, levers, pressure plates, nothing, so I try to get myself out by switching classes, and I got pushed by something and for some reason, I got stuck in a wall. Help! 
Picture: 
![2015-07-14_21 25 23](https://cloud.githubusercontent.com/assets/13345949/8693094/0ebe3eb4-2a70-11e5-8881-223fb58b01ed.png)

**Comment by Trixter313** [comment]
Typing /kill into chat should get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
