### ISSUE TITLE
Bob Reincarnation Quest is Broken 

### ISSUE THREAD

**Issue by Jacoblouis13** [Wynncraft/Issues#2106]
When i went into the tomb and went to the area that teleports you to the long walk way, instead of teleporting me to the walk way, it teleported me to a flatland. here is a picture
![2015-07-15_22 55 12](https://cloud.githubusercontent.com/assets/13360725/8716419/bd831aca-2b45-11e5-8be3-e686e516d47a.png)

I hope that image works. If it does not, then i shall describe it. It is me and my friend who were going to fight bob but we were teleported into a grassy flat land and in the back ground you can see the farm of a village. Please make sure that the tp is correct.

Thanks

**Comment by Trixter313** [comment]
This has been happening to a few people lately. Typing /kill and then doing the quest on another world should fix the issue if it's the same as the others. Try that and report back here whether it worked, if you could. Thanks! :)

**Comment by Jacoblouis13** [comment]
Yes I did try it on another server and it worked just fine. Thank you

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
