### ISSUE TITLE
Unable to find a server to connect to.

### ISSUE THREAD

**Issue by dante4603** [Wynncraft/Issues#2107]
So I was waiting for the wynncraft servers to come back up so I go play another server, When I come back and try to log on it says the following: "Unable to find a server to  connect to. Please report." So now im reporting like it told me to, please fix this issue ASAP because I love the server and can't wait to play.

**Comment by simsonas86** [comment]
I have the same issue aswell, it has to be fixed asap.

**Comment by Trixter313** [comment]
Same issue here. I tweeted Grian and the official Wynncraft twitter, I'll report here if anything is said.

**Comment by dante4603** [comment]
Ok, thanks

**Comment by Trixter313** [comment]
It appears to be back up now!

**Comment by dante4603** [comment]
Not for me.

**Comment by Trixter313** [comment]
I am able to login now and there are a few other people online. It appears to have just restarted so give it some time, it should for you work soon.

**Comment by dante4603** [comment]
Ok, thanks a lot :D

**Comment by Trixter313** [comment]
I see that you were able to get logged on. This is great news!

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
