### ISSUE TITLE
VIP Shop

### ISSUE THREAD

**Issue by BateauSD** [Wynncraft/Issues#2108]
Im buy premium 50$, but going 4 day and premium no work and activiated, why?

**Comment by Trixter313** [comment]
Did you make sure while typing your Minecraft username you typed it exactly as it is, even the correct capital letters?

**Comment by BateauSD** [comment]
My IGN Batya but im use batya in shop

**Comment by Trixter313** [comment]
That is most likely the issue. Usernames are case sensitive so capitals like that matter. Try emailing support@wynncraft.com about this and explain that you didn't correctly capitalize your username. They should get it sorted out! :)
