### ISSUE TITLE
People can't join my guild

### ISSUE THREAD

**Issue by BeastyMs** [Wynncraft/Issues#2110]
I created a guild Eternal Storm - EnS 
I invited my friend but he couldn't join

when I would chat guild tag ( EnS ) would have extra space 
[75/As/ EnS] BeastyMs:
           ^ like this

can you pls fix it

**Comment by BeastyMs** [comment]
come on help me  pls

**Comment by Trixter313** [comment]
When was the last time your friend tried to join the guild? Guilds have been having many issues lately. Sometimes they resolve themselves on their own but if not all you can do is wait for a staff member to fix it. Hope it gets fixed soon!

**Comment by BeastyMs** [comment]
last time my friend tried to join was 18 / 7 / 2015
