### ISSUE TITLE
Ocean mini D. puzzle not working

### ISSUE THREAD

**Issue by Fuyret** [Wynncraft/Issues#2111]
i try at least 20 times or more, and sometimes it works, sometimes it doesn't. If only the puzzle worked, it would be such an awesome spot to grind :(. Anyway, Basically each time I put the right combo in, it does nothing. Not to mention, you cant even see the water run. Here, I will show you:
https://www.youtube.com/watch?v=Y5iy293iBxU
That door has been the bane of my existence, and probably a lot of people feel the same way.

**Comment by TrashcanMan** [comment]
Known issue, sometimes the door does break down. Switching servers might resolve the issue.
