### ISSUE TITLE
Stuck in a Black Box?

### ISSUE THREAD

**Issue by TheBeanCenturion** [Wynncraft/Issues#2113]
So i don't know if this counts as a bug, but...

I logged on at around 9 pm EST on July 16, 2015, and my assassin was in a small box made of black wool. I've seen this box before when I log on sometimes; usually i fall thru the world, land in said box for a second, and then clip back to the normal world. I recall logging off somewhere in the Nemract area, then not playing for around two hours. When i relogged, I was already in the box and have no way of getting out. all of my other classes are fine, just the assassin. Any help would be appreciated, my MC username is TheBeanCenturion.

**Comment by TrashcanMan** [comment]
If you have at least 3 soul points, do /kill. This does happen from time to time.
Also, if this resolves your issue, we would appreciate it if you could close the report. Thanks, and have a great day!
