### ISSUE TITLE
mana glitch

### ISSUE THREAD

**Issue by XxcrowmasterxX** [Wynncraft/Issues#2118]
Hey! I Know I am not the only one that has this glitch but sometime when I go into a world it spawns me with no Mana (hunger). its really annoying because it always occurred in a lobby with all my friends. Have You Found a way to fix this Bug?

 Crow

**Comment by Trixter313** [comment]
Typing /class should fix your issue.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
