### ISSUE TITLE
Are servers down

### ISSUE THREAD

**Issue by EpicOverKill567** [Wynncraft/Issues#2119]
For some reason again I cannot connect to wynncraft, idk if the servers are down or not but they just kinda lagged and now I cant connect

**Comment by Trixter313** [comment]
I also can't connect to the server, so it most likely is a server wide issue.

**Comment by Trixter313** [comment]
Ok, they appear to be back up now!

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by EpicOverKill567** [comment]
I still cannot connect to the server, it wont let me

**Comment by Trixter313** [comment]
Did you restart your Minecraft?

**Comment by EpicOverKill567** [comment]
Yea, and all other servers are working fine

**Comment by Trixter313** [comment]
I'd suggest restarting your computer and if that doesn't work, you should be able to connect soon just by giving it some time.

**Comment by EpicOverKill567** [comment]
Okay Ill give it some time, if it doesnt come up Ill repost

**Comment by EpicOverKill567** [comment]
Okay its back up thank you
