### ISSUE TITLE
Guild Prefix Glitch (spaces between letters)

### ISSUE THREAD

**Issue by shashvatg** [Wynncraft/Issues#2121]
My in game name is ssgupta . I recently created a guild with 5 le and 5 soul points. I named the guild     GodsofWynn , but when it came to the prefix, i tried doing GoW, but it wasn't available, so i put G o W , and it worked. After that though, when friends tried to join, they could not, for they had to type in "/guild join G o W" , but it would only recognize the "G". Would I be able to change the guild prefix name? Thank you for reading this :)

**Comment by TrashcanMan** [comment]
I suppose you could try emailing support@wynncraft.com.
