### ISSUE TITLE
Stuck in Block

### ISSUE THREAD

**Issue by Lbthegreat357** [Wynncraft/Issues#2124]
I was doing the quest called Craftmas Chaos and i was looking for Evil Santa and i ran into a portal and it took me somewhere where I am stuck in a block. I have tried disconnecting, restarting minecraft, jumping, and none of these methods have worked.None of these methods have worked.
http://gyazo.com/914013c0560af9c5ec9a8b929de29ca6
If I could get some help with telporting me above or breaking a block or two, that would be great.
My coordinates are -5920 36 -13020
Thank you. ;)

**Comment by Trixter313** [comment]
Typing /kill should get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by Lbthegreat357** [comment]
but i want to stay where i am would /kill take me to the nearest town?

**Comment by Lbthegreat357** [comment]
Because I have no idea where I am and if it takes me back to Selchar or something i would not be happy with restarting the quest..

**Comment by Trixter313** [comment]
Yes, it would.

People get stuck in blocks multiple times per day and ask to be teleported
out etc. but staff always just says to use /kill. It's the easiest and
painless method of getting out of somewhere.

If you'd still like to attempt to have a staff member teleport you out, you
can leave this open but it could take a few days to a week for a staff
member to see it.

Either way, good luck with your issue! =)
