### ISSUE TITLE
Half the Dungeon is missing!

### ISSUE THREAD

**Issue by Xantiah** [Wynncraft/Issues#2126]
![2015-07-21_01 54 23](https://cloud.githubusercontent.com/assets/13429657/8793934/7c99db16-2f4b-11e5-9f92-00af20c7d2ea.png)
![2015-07-21_01 54 35](https://cloud.githubusercontent.com/assets/13429657/8793936/802eea00-2f4b-11e5-9eed-c0ea75f45f64.png)

**Comment by Trixter313** [comment]
If you go back to that now, is it still missing?

**Comment by TrashcanMan** [comment]
Try switching servers, I'm fairly certain that this is a known issue with corrupted chunks.
