### ISSUE TITLE
Frosted Leggings xp bonus glitch

### ISSUE THREAD

**Issue by Wolfcrag** [Wynncraft/Issues#2130]
Hello,
I found a glitch with Frosted leggings xp bonus. My Frosted leggings has +17% xp bonus and my Kratke has +18% xp bonus, but when I wear Frosted leggings it gives me 98% xp bonus while when I wear Kratke it gives me 88% xp bonus. Please fix this soon :)

**Comment by ring0ff1re** [comment]
Read my post #2189. I don't know how to link it here, so you have to look for it.
