### ISSUE TITLE
Guild Fail

### ISSUE THREAD

**Issue by gizmosarousrex21** [Wynncraft/Issues#2133]

**Comment by TrashcanMan** [comment]
Could you add some detail?

**Comment by gizmosarousrex21** [comment]
Sorry it's was a mistake please disregard idk how to delete it so can it be
done for me?

On Thursday, July 23, 2015, TrashcanMan <notifications@github.com> wrote:

> Could you add some detail?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/2133#issuecomment-124327571>.
>


-- 
Vladanator

**Comment by Trixter313** [comment]
You should see a button to close the issue right next to the comment button =)

**Comment by gizmosarousrex21** [comment]
Thx I'll do that first thing tomorrow

On Thursday, July 23, 2015, Nick Cipriani <notifications@github.com> wrote:

> You should see a button to close the issue right next to the comment
> button =)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/2133#issuecomment-124329693>.
>


-- 
Vladanator
