### ISSUE TITLE
Killed the animal dungeon boss 3 times and it wouldnt let me out

### ISSUE THREAD

**Issue by xThad** [Wynncraft/Issues#2134]
I entered the Animal Dungeon with my friend and we did it perfectly fine. We went into the boss battle and she died but i killed the boss right after. It respawned and didn't tp me out so i killed it again. It went on repeat to where i killed him 3 times and then i let him kill me because there wasnt anything i could do.... Can i atleast get the key back or something?

**Comment by Trixter313** [comment]
You have to make sure both you and the boss are near the center when the boss is killed. If it's too close to the edge the game doesn't detect the kill and nothing happens. Unfortunately Wynncraft has a strict no refund policy so we cannot give you another key. Hopefully these tips help you in the future! :)
