### ISSUE TITLE
Warrior charge deals no damage at some points

### ISSUE THREAD

**Issue by Penguinepowadude** [Wynncraft/Issues#2135]
Charge is suppose to deal damage to any mobs in the way. However, if you cast the spell, enemies that are very close will simply take knockback and take no damage.

**Comment by EnderMan123PvPz** [comment]
Yeah, this has happened ALL the time when im charging very close to an enemy. I guess its like if u hit an enemy from 3 blocks they dont take damage just knockback, cause the charge isnt "charged enough to do damage". Its still unfair. SO i agree
