### ISSUE TITLE
Food

### ISSUE THREAD

**Issue by dante4603** [Wynncraft/Issues#2137]
So whenever I join I start loosing food randomly and not gaining energy, making me basicly powerless against mobs, sprinting, and most things I need to do. Please help.

**Comment by Trixter313** [comment]
Typing /class should fix the hunger whenever it happens.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
