### ISSUE TITLE
Tower Of Ascension Floor 5 Boss Attack Kills Behind Wall 

### ISSUE THREAD

**Issue by AngelicDemons** [Wynncraft/Issues#2140]
So while I was trying to beat the boss in floor 5 (having him trapped in a cob web and hiding behind a wall spamming multi-hit because mana steal is op) I just die, BOOM. I understand that I do get 1hko'd by him because my armor sucks right now. The reason why I'm posting this is because I was behind a wall, he was still in the cob webs, and he should not be able to hit me because his only attack is Charge. 

This might just be charge hits in a relative location to where they land, so I tried going back off the block (Now 3 blocks away, still hitting with multi-hit) I get killed, I also have had someone trying to kill him with me (A lv 72 warrior) see that happen, just me dying out of the blue. Also, I know he does a crud ton of dmg, but I'm pretty sure that lv 72 warrior also with the resistance he applied to us with his move, should be able to withstand one hit so his damage might also be glitched.

**Comment by mizzkissy** [comment]
Same thing happened to my assassin
