### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by Loji310** [Wynncraft/Issues#2141]
Hi, I don't know why, I cant connect to the server, when I try it say: 
java.net.ConnectExeption: Connection timed out: no further information 
It's really weird because my friend can... :/
Pls help me!

**Comment by Trixter313** [comment]
Have you tried restarting your computer and router? Also, if you're using Forge, LiteLoader, or any mods, try logging in with vanilla Minecraft. These type of issues usually resolve themselves with a little bit of time if nothing above works.

**Comment by Jamdog** [comment]
There are several things that you can try, any of which may or may not help:
* Restart your minecraft client
* Log into a different server, or a single-player map, then come back.
* Wait for 1 hour *(to ensure your user data is 'unloaded' from the server)*

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Loji310** [comment]
Well it's really weird, sometime it's working and sometime not, and it's happening the same for my friend but not at the same time, for exemple:
X and Me can connect but Y can't, and later, X and Y can but I can't, etc...
I'm living in France btw ^^ And my friend to

**Comment by Trixter313** [comment]
Are you and/or your friends using any mods or any mod loaders such as Forge or Liteloader?
