### ISSUE TITLE
Guild Glitch

### ISSUE THREAD

**Issue by Hakishiro** [Wynncraft/Issues#2142]
My name is Hakishiro, on my level 34 Mage account, my friend and I made it to Troms in hopes of starting a guild. I got my 5 Liquid Emeralds and was ready to buy it, but I was sent the message saying that I needed to be level 40. My friend and I sighed and prepared to head back, when I got a message asking what I wanted to name it, I named it "Hozuki Clan" then was asked what the prefix was going to be, I made it HoZ. When I confirmed it, I got the message telling me to do /guild to check what I could do. Then I got a message saying "/guild join to join a guild" please help, I really don't want to have wasted 5 Liquid Emeralds, as well as 5 soul points.

**Comment by Jamdog** [comment]
It will usually take around half an hour for a guild to become visible after it is created.  I can see from [here](http://katoa.ca/wynncraft/guilds/index.php?g=Hozuki%20Clan) that your guild has created successfully.

If you are still experiencing issues, then please let us know, but if you can now use the /guild command to administer your guild in-game, then please close this issue using the button below.
