### ISSUE TITLE
I I have fallen into the world.

### ISSUE THREAD

**Issue by miningcrazy** [Wynncraft/Issues#2147]
I have fallen into the world near Ragni. I'm at y:13 and my screen is pitch black. Someone is probably going to need to teleport me out.

![2015-07-27_10 31 44](https://cloud.githubusercontent.com/assets/13527881/8917222/0969e744-346e-11e5-8b99-fbc6970a03c2.png)

Please.

~Miningcrazy

**Comment by Trixter313** [comment]
Typing /die should teleport you to the nearest visited town.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by miningcrazy** [comment]
Awesome thanks.
