### ISSUE TITLE
Unable to find a server to connect to

### ISSUE THREAD

**Issue by finlayj123** [Wynncraft/Issues#2148]
I was playing on Wynncraft when the server disconnected me and said server restarting so after it kicked me i tried to get back on and it said "Unable to find a server to connect to. Please report." I've tried reloading countess times, I've restarted Minecraft, I've restarted my computer and it still gives me the same message. Any ideas?

![2015-07-28_17 43 26](https://cloud.githubusercontent.com/assets/11471605/8926082/4bc5161c-3550-11e5-8f18-c835b9c6d105.png)

**Comment by Trixter313** [comment]
Can you still not log on?

**Comment by Trixter313** [comment]
Multiple people are experiencing this so the issue appears to be with the server and not you so all we can do it wait.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
