### ISSUE TITLE
Un-Given XP reward from quest

### ISSUE THREAD

**Issue by MlgDavid** [Wynncraft/Issues#2150]
Username: DavidIsHere
So yesterday i was doing the qeust "Out of my Mind" and i completed it. BUT i completed the quest while on my horse. (Last step to do in quest is to talk to Villager NPC Ariodo) <------ When i did that, i was on my horse. I got the emerald rewards but i didnt get any XP cause i was on my horse! I dont have any screenshots sadly because i never knew this was a bug or a thing until this incident happend.
I really need the XP.
Hope u guys fix the bug!

-David

**Comment by AckroWynn** [comment]
I am sorry it ended up like that, but all we can do for you is nothing. We are sorry.
