### ISSUE TITLE
Stuck in a big black box

### ISSUE THREAD

**Issue by xShearer** [Wynncraft/Issues#2159]
For some reason whenever i login with my warrior class, im stuck in a huge big black box of wool with no way to get out. Im not sure why or how this happened. This is just an issue ive been experiencing everytime i login with warrior. It works with other classes fine, but im just stuck in this box and i cant get out, making it impossible to play with my best class warrior.

Thanks for checking my issue!
My in game name: Shearer

Please save me :(
http://prntscr.com/7zdgo7
http://prntscr.com/7zdh9s

**Comment by Trixter313** [comment]
Typing /die with 3+ soul points should get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
