### ISSUE TITLE
name change problem

### ISSUE THREAD

**Issue by WillowTheDragon** [Wynncraft/Issues#2161]
i had made a guild a little less then a week ago and I added a friend and everything was good but then I changed my name and now it says my old IGN in the guild tab and I also cant use /g or any other guild commands will this be fixed  or will I have to make a new guild?

Old IGN: WillTheDragon
New IGN: WillowTheDragon
Guild: NewTeamRocket [NTR]

**Comment by Trixter313** [comment]
I do see that the guild is still showing your former username as the owner here https://wynncraft.com/guild/NewTeamRocket

Once a staff member sees this they should be able to help. Good luck!
