### ISSUE TITLE
Could not find a server to connect to, please report

### ISSUE THREAD

**Issue by Evieboxhead** [Wynncraft/Issues#2162]
Tried to connect and came up with the following message:

Could not find a server to connect to, please report.

Thanks,
Evieboxhead

**Comment by Evieboxhead** [comment]
I could not even get to that stage 1/2 an hour ago. It couldn't find a connection to the server/it was refused/etc.

**Comment by Moe-Ronickah** [comment]
Try play.wynncraft.net, play.wynncraft.com, play.wynncraft.org, and you can place a number after the word "play", such as "play1", "play2", etc.  Why this works is a different matter, but please do try all of those options.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Evieboxhead** [comment]
Ok thankyou! Wynncraft is awesome. Thankyou for your support.
