### ISSUE TITLE
Guild master took my LE and SP but didnt create guild???

### ISSUE THREAD

**Issue by ohhcon** [Wynncraft/Issues#2164]

**Comment by Trixter313** [comment]
It usually just take a few hours to register. It should resolve itself with time.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
