### ISSUE TITLE
Already logged in to all servers

### ISSUE THREAD

**Issue by GLaDOSkiller** [Wynncraft/Issues#2166]
I am currently unable to connect to any server after Server 10 Restarted and most likely Crashed.
when attempting to connect to server 10 it says "Could not connect to default or fallback server, please try again later. Java.net.ConnectionException" and when trying any other server, it says "you are already logged on, please try again later". I have a feeling that It believes I'm still logged on in Server 10 and is not letting me play. I am not the only player to experience this as Ziggeh2 reports something similar. Please find out what happened as soon as possible.

*Note: server 5 says the same thing as server 10*

**Comment by Trixter313** [comment]
Just logging off of Wynncraft for a little bit of time usually fixes this issue. Are you still experiencing it?

**Comment by Ziggeh2** [comment]
I'm still experiencing it. It hasn't gone away and has been doing this for quite some time

**Comment by Trixter313** [comment]
Did you make sure to be logged off while waiting @Ziggeh2 ?

**Comment by Ziggeh2** [comment]
@Trixter313  logged off how?

**Comment by Ziggeh2** [comment]
@Trixter313  It let me play on a world or two, but as soon as another world restarted, it would happen again.

**Comment by Trixter313** [comment]
As in not on the server. Usually if you just close Minecraft and wait a few minutes to hour, it resolves itself. If it is caused by server restarts, doing /hub before the countdown reaches zero might prevent this in the future.

**Comment by Ziggeh2** [comment]
@Trixter313  I was thinking of doing that. Ill try. In the meantime, are Wynncraft staff trying to fix this problem?

**Comment by Trixter313** [comment]
I'm sure they probably are. I doubt they would intentionally leave a bug open. If you have any more replies, it would be appreciated if you posted them in the issue you created from now on. Keeps things a little more organized. ;)

**Comment by Ziggeh2** [comment]
@Trixter313 Oh, sorry. I'm a bit new.
