### ISSUE TITLE
Reset Characters Option Please

### ISSUE THREAD

**Issue by Socksykins** [Wynncraft/Issues#2173]
I have been playing for a while when wynncraft first came out and then i left it alone for a few years and it updated, so i wanted to restart fresh. or if it already exists i would like you to tell me. THIS IS NOTHING TO DO WITH TOWER OF AMNESIA

**Comment by Trixter313** [comment]
The staff said that the option to reset a class will come with the release of Gavel. So we'll just have to wait until then ;)

**Comment by Trixter313** [comment]
Also, if you have any more suggestions, they would fit better and be seen by more people in the suggestions section of the forums. https://forums.wynncraft.com/forums/general-suggestions/
