### ISSUE TITLE
Relic Helmet disappeared

### ISSUE THREAD

**Issue by Jaguar11891** [Wynncraft/Issues#2176]
So I found the Relic Helmet, touched it, got the message saying I got it, couldn't find a way out of the chamber and died. When I respawned, the Relic Helmet was no where to be found on my person. I went back to the location and it looks like it still counts as I already claimed it. Weird thing is that I got a piece of paper with strange letters on it after touching the relic and that stayed with me when I died. I have some screenshots of the message in the chat and my inventory afterwards. Is this a glitch or if you die in the relic chamber you can't get it again? Please help and thank you.
![2015-08-05_10 05 49](https://cloud.githubusercontent.com/assets/13673281/9105064/98665f66-3bc8-11e5-9ba2-911d9fd52a5f.png)
![2015-08-05_10 06 08](https://cloud.githubusercontent.com/assets/13673281/9105065/9b192996-3bc8-11e5-9a74-39e263519e83.png)

**Comment by Trixter313** [comment]
There's a chance of getting a "sealed letter" instead of getting the relic item when collected. You should be able to go back to the relic spot and collect it again once it regenerates. For more information, https://wiki.wynncraft.com/index.php?title=Relics#Sealed_Letter might help.
