### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by sammei19021** [Wynncraft/Issues#2179]
There is an login issue that occurs randomly that existed for months!

When you opened your minecraft game and click to join wynncraft, you get the Login in error. Then you get disconnected, or you get a bungeecord message.

There's a problem with players logging in to wynncraft. I am not able to login for this past 30 minutes and this keeps happening. The number of players keep decreasing and no players can join back in.

This bug needs an immediate fix!

**Comment by Trixter313** [comment]
Are you using any mods? Or any mod loaders such as Forge or LiteLoader? Users using these things have been having troubles logging in lately and this might be the cause.

**Comment by sammei19021** [comment]
Just minecraft 1.8.7  with Optifine.

The same bug happened right now

**Comment by Trixter313** [comment]
Can you login with no mods at all? Any mood seems to be causing issues for some players recently, even optifine.
