### ISSUE TITLE
quests not working

### ISSUE THREAD

**Issue by jenna0192** [Wynncraft/Issues#2180]
i get the items for the quests and then it asks me if i got the item yet. this ishappening with the tribal agression quest and the theiving rodents quest. my mc username is jenna0192. thanks!

**Comment by Trixter313** [comment]
What items are you trying to give the NPC's? What are their exact names? You are most likely trying to give the NPCs the wrong item. Also, what part of the quest are you on for each?

**Comment by iZoomPvP** [comment]
I have a quest bug as well, just not the same, for the Christmas Chaos quest, you might want to lower the health of the crystal and santa, i almost dropped my inv twice, but thats besides the point, i cant click on santa to finish the quest. pls help me.

**Comment by jenna0192** [comment]
its the owl totem and i sucessfuly got 2 owl tomtems and it kep t on asking me if i got it. plus the wedding ring for the theiving rodents wont let me click on him and i got 6! help me please! this server isnt helping me at all!

**Comment by Trixter313** [comment]
@jenna0192 Make sure you're giving the right totems to the right people and to read the quest book carefully. There shouldn't be any issue with this quest. And for the rodents quest you first have to give the villager a ring from the regular rats in the field and then you have to give him a ring from a king rat in the ground.

**Comment by Trixter313** [comment]
@iZoomPvP What does your quest book say?

**Comment by iZoomPvP** [comment]
it says Return back to the present and report back to Santa.
