### ISSUE TITLE
Im stuck in Evil Selchar 

### ISSUE THREAD

**Issue by zwamdurkel** [Wynncraft/Issues#2181]
Im stuck in a 3 deep hole in Evel Selchar and I consider this as a bug. Also I want to get out of that hole plz :'(.

**Comment by Trixter313** [comment]
Typing /kill with 2+ soul points should get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
