### ISSUE TITLE
Respawn Not In The Right City

### ISSUE THREAD

**Issue by ItsBlob** [Wynncraft/Issues#2182]
so i was doing the Tower Of Amnesia quest.. then when i'm done i proceed to the quest called "Macrabe Masquerade "Hallowynn 2014"" i have been doin that quest for 3 days back then.. and when i decide to give it another try.. i died again and what really shocked me was that i didnt respawn in maltic.. (which is the nearest city) but instead, i spawned in selchar which is thousands of blocks away..

and at that point i have no emerald, no boat, and no teleportation scroll with me so i had to swim all the way to nemract... i hope you guys can fix this, any questions based on this issue will be replied by me

and any further information you need just comment it..

my IGN is : ItsBlob 

Thx ^^

**Comment by Trixter313** [comment]
For some quests you are teleported far outside of the actual map of Wynncraft into a super flat area where the builders aren't limited by space. This results in respawning in unexpected places such as Selchar.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by AckroWynn** [comment]
Exactly. Most/many of the quest locations are actually outside of the map, just as Trixter implied.
I suppose there is no way, yet, to change that.
