### ISSUE TITLE
under the map because of craftmas choas

### ISSUE THREAD

**Issue by infoattack** [Wynncraft/Issues#2184]
i was just heading into the crystal cave place, and it put me in the camp... for about 5 seeconds.
the i fell through the map. im in a minecraft village (a normal one)

**Comment by Trixter313** [comment]
Typing /die with 2+ soul points should get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
