### ISSUE TITLE
Wynncavation A glitched

### ISSUE THREAD

**Issue by EpicOverKill567** [Wynncraft/Issues#2186]
Hey, I am having a problem, a while back wynncavtion site A quest gltiched, when the girl was supposed to give me the translated script I got nothing, is there any way you can help me? I need to do these quests to help level up :(

**Comment by Trixter313** [comment]
You can try doing /fixquests but other than that a staff member would have to help you.

**Comment by EpicOverKill567** [comment]
Ty so much! 😂

**Comment by Trixter313** [comment]
Did this actually work for you? Others have had this issue also but /fixquests didn't work for them. Maybe they finally fixed it!
