### ISSUE TITLE
Spells not working

### ISSUE THREAD

**Issue by Killos** [Wynncraft/Issues#2188]
Hello, I've not seen this very annoying issue yet, but it may have already been pointed out. The issue is that since quite some time, some of my spells don't seem to work even if I have enough hunger to use them. I'm currently using my Mage and I died many times because of that. I use the good combination of clicks and it shows my three clicks (for example right-left-right for my heal) but the spell doesn't work nor play the 'ding' sound which often leads me to a death. It happens under any circumstances, when I click fast, when I click slower, when there's lag, when there's no lag at all and it ruins my experience of the game because it happens a lot. I'd like to know if this issue can be resolved and sorry if someone already posted this issue.

**Comment by TrashcanMan** [comment]
This is a known issue, and it appears to be a lag-based problem of some sort.
I don't think there's any fix as of right now.

**Comment by Killos** [comment]
Thank you for your answer, I hope there will be a fix, because it is REALLY annoying and I died a lot because of that problem.
