### ISSUE TITLE
Armor (and possibly weapons) show incorrect Identifications

### ISSUE THREAD

**Issue by ring0ff1re** [Wynncraft/Issues#2189]
Recently I have been testing the ID's of my armor to determine how they add up, and noticed that for XP, Loot Bonus, and Spell Damage on an armor set or singular piece, to determine their totals for "ID Info" (found by clicking the compass object labeled Character Info, and hovering the mouse over the head object labeled [IGN]'s Info while in a server), add the totals normally, and multiply the sums by .77 (the head coder might know this [Jumla?]. 

For example, wearing a Blue mask with the following ID's;  Xp: 30%, Loot: 32, and Spell: 26%
and an Adamantite with the following ID's;                           Xp: 31%, Loot: 29, and Spell: 31%.
would have the total ID's;                                                      Xp: 61%, Loot: 61, and Spell: 57%
and have an "ID Info" (all rounded to nearest whole);          Xp: 47%, Loot: 47, and Spell: 44%. 

The issue I found is that some of my armor's ID's when multiplied by .77 don't show the expected product. 

For example, wearing my Kratke with the following ID's;     Xp: 15%, Loot: 13, and Spell: 26%.
gives me the unexpected "ID Info" of;                                  Xp: 15%, Loot: 14, and Spell: 24%.

Wearing that with my Blue Mask with;                                 Xp: 30%, Loot: 32, and Spell: 26%

I should technically be getting an "ID Info" of;                     Xp: 35%, Loot: 35, and Spell: 40%,
but actually, I am getting an "ID Info" of;                             Xp: 38%, Loot: 39, and Spell: 44%

doing some math, I found that my Kratke seems to have;  Xp: 20%, Loot: 18, and Spell: 31%

I also have a similar problem with my Montefiore with it's spell damage, meaning the problem is not in the Kratke's coding, but perhaps in the Identification Process coding. What's an interesting thought is that many people could own what they believe to be crappy armor or even weapons because of their ID's are presented false, while they are actually pretty strong and the made a mistake in selling them to an Item Buyer! What's worse is that although armor can be tested for their accuracy, weapons can't since they aren't totaled with the "ID Info"!

Oh, and if any coder replies to this, I would love to know the equation for one's Armor Info, it's been driving me crazy.

**Comment by TrashcanMan** [comment]
I think the armor ID indicator in your compass shows the average IDs, not the IDs you actually have on your armor.
For example, if armor X has an average of 15% spell damage, and you got 17%, it would still display 15% in your compass.

**Comment by ring0ff1re** [comment]
I know that the ID Info that the compass displays is not the one displayed on the armor. I claimed that the compass multiplies the armor's IDs (only Spell, Loot, and XP) by .77 and rounds it to the nearest whole number (rounding occurs after all the ID's on all the armor one is wearing is summed then multiplied, or any other equivalent calculation).

What do you mean by "average"? If one was wearing armor with a total of +17% Spell, the compass would (or should) say the armor had 17 x .77 = 13.09 -> +13% Spell Damage. If one had a weapon with 100-120 Damage, the compass would say the weapon would have 
(100-200) x 1.1309 = 113.09-226.18 -> 113-226 Damage.

Are you saying that the "average of 15% spell damage" is the 17% x [whatever constant, which I claim to be .77]? If so, your comment doesn't really add anything more to my post (I'm not trying to be mean or anything! Really, I can't think of a better way to say it).

**Comment by Trixter313** [comment]
I believe @TrashcanMan means that it goes by the average of all of the possible ID percentages a player can get. So pretty much, the amount that will show is pre set and it doesn't matter what you get on it, it's always going to use the same number for that specific piece of armor.

**Comment by ring0ff1re** [comment]
So you're saying that regardless of what an armor piece's ID's are, on the compass, it's always the same? Like one armor with +14 Spell and another armor with +8 Spell (given that both armors have the same name) would both have a +12 Spell (if 12 was the "average") shown in the compass? If so, wouldn't that make one full ID'd armor equivalent to another full ID'd armor if both armors have the same name, making, for example, one crappy ID'd Blue mask equal to a perfect ID'd Blue Mask?

**Comment by Trixter313** [comment]
Yeah, if @TrashcanMan is correct, and I interpreted it correctly.

I believe that the actual boosts you get are exact percentages.

Yes, the point is it gives the user a rough estimate of the ID's their armor has and they don't have to do any math. If a user doesn't really care about the ID aspect of the game, it's something they can just look at

**Comment by ring0ff1re** [comment]
Ok, I think I get what you're saying.
