### ISSUE TITLE
Stuck forever in sewer

### ISSUE THREAD

**Issue by Whatisthisname** [Wynncraft/Issues#2190]
Under the Potion Merchant in the area in front of Ragni there is a hidden sewer. When you enter it, you cannot leave it again because the exit is blocked.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/2077

We recommend closing the duplicate and following the original to stay up to date on the status of the issue. Thanks!

**Comment by sammei19021** [comment]
do /kill. That kills you and you loose 2 soul points to respawn to the closest town
