### ISSUE TITLE
Im stuck in the ground! HELP! PLEASE!

### ISSUE THREAD

**Issue by yuvalmeiro** [Wynncraft/Issues#2192]
my name is Yuval Meiro (or yuvalmeiro)
and I'm stuck in the ground as you can see in the picture I added
you can also see the croods there (X:876 Y:65 Z:-1467)
Can you please help me and get me back to Ragni?
I belive that if I paid $25 you can at least get me out of there...
TNX anyway, yuvalmeiro
![2015-08-10_20 10 31](https://cloud.githubusercontent.com/assets/13734588/9178349/7757a2d2-3f9f-11e5-914a-e145a9eca49a.png)

**Comment by Trixter313** [comment]
Typing /die will teleport you to the nearest visited town and free you.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
