### ISSUE TITLE
My assassin class is stuck in the class selection room

### ISSUE THREAD

**Issue by Pyro37** [Wynncraft/Issues#2194]
im not  sure how it happened, but me and one of my friends got stuck in a small dark room while on server 14. we were in Nemract by the potion shop when my friend tried to change his class, when he did he found himself stuck in a small room. we changed servers thinking it would fix the problem but then we were both in the room. we each changed classes again and the other classes are fine, but my assassin class and my friend's warrior class are still stuck in the room. please help ;-;

**Comment by Trixter313** [comment]
Typing /kill with 2+ soul points should get you out of the box.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Pyro37** [comment]
Thank you very much. I didn't think that non-mods/admins would have access to any commands. I greatly appreciate your help
