### ISSUE TITLE
Stick j'en the class choice with my Warrior

### ISSUE THREAD

**Issue by SuperBiscuitsMan** [Wynncraft/Issues#2195]
With my login I discover that I lost my emeralds and my outfit with my warrior. I decided to go to a city for checked my bank, nothing has disappeared. I disconnected and then a few hours later I decided to go buy some weapons and armor. I then find myself stuck in the dark room of the choice of classes ! I look at my inventory , I do not have a teleport scroll to exit the room. The other classes walk but my warrior stuck . I play for a long time on this server and this is the first bug that happens to me. I will not complain ais just be teleported to the world map of Wynncraft to resume my adventures . Thank you for reading this message and sorry for the mistakes but I'm French and my English is not very good.
SuperBiscuitsMan

**Comment by Trixter313** [comment]
Typing /kill will get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by SuperBiscuitsMan** [comment]
Thanks you
