### ISSUE TITLE
Get out of map bug

### ISSUE THREAD

**Issue by Lake902** [Wynncraft/Issues#2196]
So recently, I discovered a way to get out of the map using the mage tp. It tp's you past the world guard border, then you leave the server really fast, and it save your position there. If you do this multiple times, you can get out of the map. The only place I've been able to do it is near the angry village. I have a video showing how below. It also shows another bug, which is food does not regen on some servers. My solution to the map bug is by having an invisible wall of some sort so you can't get past.

Thanks!

https://www.youtube.com/watch?v=eufS0qQ3-jw&feature=youtu.be

**Comment by Trixter313** [comment]
For the food part of the bug, all you have to do is type /class and it foxes the issue.

**Comment by Lake902** [comment]
Ok, Thanks, I will do that next time

**Comment by AckroWynn** [comment]
I am sure that it is bannable, and we do know that these issues exist. No action will be taken against it, yet, though.

**Comment by Trixter313** [comment]
There's always barrier blocks now ;)
Another reason to update the server to full 1.8.

**Comment by Lake902** [comment]
True, I wish they would, it could fix some problems

**Comment by Lake902** [comment]
And ok, I won't tell anyone else
