### ISSUE TITLE
Prison story not working

### ISSUE THREAD

**Issue by Ripjaw95** [Wynncraft/Issues#2198]
With my lvl 67 warrior i tried to complete the quest prison story but i lost the prison key and cant get it back.
the server was about to restart so i was rushing and i gave ooni the key and he took it and the server restarted afterwards i tried talking to ooni and he keeps asking about warnot and i tried talking to warnot again but he wont say any thing

**Comment by TrashcanMan** [comment]
Have you tried /fixquests?
