### ISSUE TITLE
guild mobs respawning

### ISSUE THREAD

**Issue by finlayj123** [Wynncraft/Issues#2199]
I have just spent half an hour attacking a territory for my guild it had 603 mobs defending when i last attacked and after killing at least 300 i died and when I went to finish them of it still said that there were 603 mobs defending.

**Comment by finlayj123** [comment]
It just did it again!!! I took them down to 50 mobs or so and after i respawned its like nope you didnt kill any at all your still on 415 mobs and we'll take your soul points too. Could someone please help me with this?

**Comment by TrashcanMan** [comment]
When it said there were 600 mobs defending, did it look like there were 600 or did it look like there were 300?
