### ISSUE TITLE
Guild's are not being created properly 

### ISSUE THREAD

**Issue by CryogenicFrost** [Wynncraft/Issues#2201]
http://i.imgur.com/ifmVxWc.png Guilds are still broken, I have a feeling that it is always reproducible each time you create a guild. You need to relog for the guild to be created properly http://i.imgur.com/vcExnPE.png

**Comment by Trixter313** [comment]
I'm not sure what the issue is here, didn't it resolve itself? All you have to do is wait a bit/relog and your guild is created.

**Comment by CryogenicFrost** [comment]
Relogging does fix the issue, but you still need to find a fix for it, a fix that will not require anyone to relog or do anything stupid
