### ISSUE TITLE
Liquidfied emeralds disappeared?

### ISSUE THREAD

**Issue by XtyfoonX** [Wynncraft/Issues#2209]
Hi, recently I've been playing and I've lost 6 Liquified emeralds from unknown reasons. I had recently sold something and the buyer gave me old liquified emeralds. I knew to go back to 1.7.10 to convert it and that's just what I did. I went to the liquefied guy in detlas and put in 12 le. That didn't work so I immediately split my 12 into 6 and converted. After getting out of my inventory I saw that my le were on the group. I assumed they were the 6 I split and walked towards them to pick them up but right when I got there they disappeared. I proceeded to look around and double check my inventory by clicking all the empty spaces.  I'm not asking for a refund, but can anyone help me with why this would happen?

**Comment by TrashcanMan** [comment]
You can't convert old emeralds to new ones unless you're either in 1.7 or if you're at the Converter Merchant in Selchar.

**Comment by XtyfoonX** [comment]
I was in 1.7.10

**Comment by XtyfoonX** [comment]
Oh by the way I meant ground not group my bad
