### ISSUE TITLE
Bear Mask No longer Bear Mask

### ISSUE THREAD

**Issue by Bubbabubba49** [Wynncraft/Issues#2218]
If you put on the Bear Mask now, it will be a Teenage Mutant Ninja Turtles head. When I asked another player if he saw the turtle head, he said he didn't even see the mask on.
![2015-08-17_19 12 14](https://cloud.githubusercontent.com/assets/13843390/9320904/280d4e0a-4514-11e5-808e-8dfbc4994be9.png)

**Comment by AckroWynn** [comment]
That might just be that the player we used the head for changed their skin.
I am unsure if it really should update, but it might have, and I suppose that must be the reason.
