### ISSUE TITLE
Mana (hunger) stay always to 0 . . . 

### ISSUE THREAD

**Issue by JoeHawk** [Wynncraft/Issues#2219]
Mana (hunger) stay always to 0 . . .  on all servers..
IGN: xJoeHawk

**Comment by Trixter313** [comment]
Typing /class should fix the issue.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by 8MeGusta8** [comment]
same problem but cant be fixed with /class, relog, and /kill. only if i changed server it starts to regen, but when i came back to the server i cant regen, its starts to not regening again. please help!
