### ISSUE TITLE
character spawn issue

### ISSUE THREAD

**Issue by sonamars05** [Wynncraft/Issues#2221]
every time I pick my mage I spawn in the black thing where people pick there classes and then I cant get out or do anything.

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue.
If it's not, we'd be happy to continue to assist you as much as possible.
Thank you and we hope you enjoy your time playing Wynncraft! :)
