### ISSUE TITLE
Spawning underground

### ISSUE THREAD

**Issue by RaymondZGames** [Wynncraft/Issues#2223]
So yeah i was in the Dern jungle and died all of a sudden, I had 1 soul point left and i was stuck in the ground. I waited a bit to see if it was a screen glitch but, 5 min after i was still stuck in the ground. Me being so smart i did /die with 1 soul point left and expecting my stuff to pop out from the ground, i died and lost everything. The only important thing i lost from the incident was my chestnut horse. I dont know if it is possible if you guys could give one to me but i just wanted to file this bug so that no one else does the same stupid thing i did and ends up losing their stuff. My ign is RaymondZGames by the way. (If u wana gimmi my horse back thats cool).

**Comment by TrashcanMan** [comment]
Unfortunately it's your own fault for using /kill with only 1 soul point. Remember that soul points generate even when offline, so next time just log off for an hour or so then come back. Also, sometimes spamming movement keys will get you out of the ground.
