### ISSUE TITLE
Wynn Excavation Site C

### ISSUE THREAD

**Issue by Gravestrike** [Wynncraft/Issues#2224]
When I started the quest Wynn Excavation Site C, my purple crystal shard (which is required for the quest) got taken away. Now, to turn in the quest, it says I need the purple crystal shard, however, I still got 1 purple crystal shard left, but it keeps saying that I need the shard from wynn excavation site B to complete the quest.

![2015-08-19_17 07 48](https://cloud.githubusercontent.com/assets/13871615/9360157/f0c5010e-4694-11e5-9907-e09c785a4dca.png)

**Comment by 63502** [comment]
I just had this issue now.
