### ISSUE TITLE
Eating Corrupted Potato

### ISSUE THREAD

**Issue by PenguinJ2** [Wynncraft/Issues#2225]
It is possible to eat a corrupted potato (quest item) which I believe would usually be required for another quest. It is impossible to dispose of it otherwise; this is clearly a bug and I would also like to get my potato back. I have been playing for 2 days (about 2 hrs playtime) since I ate it in Nemract pier, and I have not recieved it back.

**Comment by Trixter313** [comment]
/fixquests will return the potato.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
