### ISSUE TITLE
Could not find a server to connect to, please report

### ISSUE THREAD

**Issue by Ripjaw95** [Wynncraft/Issues#2226]
I tried to join wynncraft but this error message kept popping up, i aolso tried play1.wynncraft.com and so on as well are the .org and .net endings ive been getting this error message commonly now a days and usually i wait it out but this is lasting a really long time

**Comment by Trixter313** [comment]
Are you still experiencing this issue?

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
