### ISSUE TITLE
Warrior Charge Bug

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#2228]
I've seen this get reported before, so even if it's just something client-sided, I'd at least like some sort of explanation, even if it's hard to explain. Or maybe it was intentional, though I doubt it.

Recently, charging with my Warrior gives a strange kind of charge, as in after I land, I get pushed forwards and downwards in a few short bursts. Somewhat like charging multiple times, though it doesn't really have any upwards force, has some force pushing me forwards, and has a lot of downwards force. This makes it difficult to aim where I am charging, as I move forwards an apparently random distance after landing where I want to.

**Comment by TrashcanMan** [comment]
This could be lag-related.
Can you get a video of this?

**Comment by awemanrank100** [comment]
I would, but I'm not entirely sure if I can record already, and getting software might not be possible... I'll see what I can do.
