### ISSUE TITLE
Connection Lost

### ISSUE THREAD

**Issue by zorkiez** [Wynncraft/Issues#2232]
A friend and I are both having the same issue while trying to connect to the server. We have tried using 1.7 and 1.8 and get the same message:
Exception Connecting:RuntimeException : Server is online mode! @ net.md_5.bungee.ServerConnector:261

My friend and I both live in different states in the US. 
The server says that there are almost 500 players on line.

**Comment by Ripjaw95** [comment]
i was getting the same thing may be gavel is coming out?

**Comment by TrashcanMan** [comment]
Nope, unfortunately Gavel is not coming out just yet. This happens from time to time, just wait an hour or two.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by MegaPixelPerfect** [comment]
Has just happened to me.
