### ISSUE TITLE
Cant enter the server 

### ISSUE THREAD

**Issue by Dguerrex** [Wynncraft/Issues#2233]
Today , I stayed the whole mornig playing in the wynncraft server but after midday , when i try to log in the server this is the result 

![Error Image](https://cloud.githubusercontent.com/assets/13892649/9393743/25349d88-4784-11e5-8d09-7c01fa24b110.png)

anyone knows abour that problem ?

please if someone knows about it reply this

**Comment by zorkiez** [comment]
my friend and i are having the same issue

**Comment by Dguerrex** [comment]
but ever or only today ?

**Comment by dragonfly19981** [comment]
I already reported it 
https://github.com/Wynncraft/Issues/issues/2231

**Comment by TrashcanMan** [comment]
This is probably routine maintenance, just wait an hour or two and it should be fine.
