### ISSUE TITLE
Stuck in Class Choosing Room

### ISSUE THREAD

**Issue by negativestar54** [Wynncraft/Issues#2234]
Hey. When I choose my main class (a Level 27 Mage) I don't get teleported out of the dark room I'm in; I just stay in there. I don't see another way out, and I don't have any scrolls. I selected another class and it worked fine. How can I fix this? I wanna play as my mage!
![stuck in black room](https://cloud.githubusercontent.com/assets/13894917/9398352/dbe34a34-476b-11e5-8aa8-152d30e5bed6.png)

**Comment by Emily7974** [comment]
Do /kill or try /class again.

**Comment by negativestar54** [comment]
Okay, /kill worked, thank you!
