### ISSUE TITLE
Stuck In The Black Room

### ISSUE THREAD

**Issue by Xauf** [Wynncraft/Issues#2236]
![javaw 2015-08-21 11-36-01-284](https://cloud.githubusercontent.com/assets/13908068/9416182/eb6f6a5e-47f8-11e5-9b41-3c8010dba9c9.png)

I Got Stuck In The Black Room While Trying To Play As My Mage,
I Tried Everything To Try And Get Out(Teleporting, Disconnecting, Switching Servers).

I First Was At Nemract As A Knight Then I Said /class
I Clicked My Mage And Got Stuck Here

**Comment by Trixter313** [comment]
Typing /kill should get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
