### ISSUE TITLE
Were Drawing Your Armor Glitch

### ISSUE THREAD

**Issue by Hypoterrian** [Wynncraft/Issues#2238]
So i just started with my archer from lvl1 and when i tried to put armor it says We're drawing your armor please wait but it never does finish it

**Comment by PenguinJ2** [comment]
This was fixed a few days ago.

**Comment by sammyreddy0011** [comment]
I have a glitch right now where my game crashed while wearing armour and now when I try to log into a server it says already logged in and puts me back into the main lobby.
