### ISSUE TITLE
Bug glitch

### ISSUE THREAD

**Issue by GangstaChica** [Wynncraft/Issues#2241]
I'm outside the Glitcher my map coordinates are -979 63 -1693 I just connect me and I'm back in there I can not get out then I will ask an admin to teleport me if you like it

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
