### ISSUE TITLE
Server data lost after account transfer

### ISSUE THREAD

**Issue by AeroArchonite** [Wynncraft/Issues#2243]
I recently had some trouble migrating my Minecraft account to Mojang's servers, and I had my account's paid status revoked without getting a refund. I only recently was able to get my account back, and I used my old username, SpencerLev38, though when I logged onto Wynncraft, none of my stuff was there. I was a level 21 or 28 archer, can't remember the level. Think I had a witherstring, though I'm not sure. 
I uploaded two screenshots I took of my archer in Almuj below.
![2015-03-24_19 38 27](https://cloud.githubusercontent.com/assets/13931595/9429056/764ab39c-4978-11e5-9740-151e168a094a.png)
![2015-03-24_19 37 51](https://cloud.githubusercontent.com/assets/13931595/9429057/7d1449f4-4978-11e5-809d-fcec281a125b.png)

**Comment by TrashcanMan** [comment]
So you migrated your Minecraft account to a Mojang account and it reset your character data?
I suppose you could email support@wynncraft.com

**Comment by AeroArchonite** [comment]
Load of crap. I emailed them and this happens. Won't be getting back on anytime soon.
