### ISSUE TITLE
i fell in the ravine while doing the Macabre Masquerade and it tp me to a superflat world with random parts of wynncraft

### ISSUE THREAD

**Issue by MysticCrumbz** [Wynncraft/Issues#2245]

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should teleport you back to the nearest town.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
