### ISSUE TITLE
Delay teleport in Tower of Ascension

### ISSUE THREAD

**Issue by Vas0sky** [Wynncraft/Issues#2248]
In each floor, after giving the floor master 10 items, entering the portal doens't trig the teleport immediately to the next floor, but enemies still can get you while trying to teleport. This is frustrating and makes you loose Soul Points if you can't teleport fast enough, especially when on low level/armor.

**Comment by TrashcanMan** [comment]
This is a known issue and unfortunately there is no fix right now. Usually spam-jumping at the teleportation site helps.

**Comment by Vas0sky** [comment]
I found that if you go touch the wall right in the middle the delay is way shorter.

**Comment by TrashcanMan** [comment]
That's good to know, thanks!
