### ISSUE TITLE
server not found

### ISSUE THREAD

**Issue by meelock** [Wynncraft/Issues#2254]
when ever i try and join it says "Could not find a server to connect to, please report."

please help... but im guessing this is going to stop soon so... if it doesn't ill repost

**Comment by meelock** [comment]
oh oh oh please close now... it works now... :P

**Comment by TrashcanMan** [comment]
If your issue is fixed we would appreciate it if you closed the issue. Thanks!

**Comment by meelock** [comment]
... how?

**Comment by TrashcanMan** [comment]
There should just be a button underneath the comment box labelled "Close Issue" or something.
