### ISSUE TITLE
powders not working

### ISSUE THREAD

**Issue by taller-than-pd** [Wynncraft/Issues#2257]
ok, so this is my first time on getting this glitch, reproducing it, not sure how i did it. I was in the deltas bank when i wanted to go to lobby. next thing i know, when i choose my warrior kit, my spawn point is in the kit room :(. plz fix this soon, the coords to the spawn room are -987, 63, -1692

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Louis-D** [comment]
#Vote for close!
