### ISSUE TITLE
i am still banned on this server

### ISSUE THREAD

**Issue by nyehee** [Wynncraft/Issues#2258]
@capa has unbanned me about 13 days agoe but when i got onto minecraft and went on the server it says that you have been banned appeal truthly on the forms
i have but i am still banned on the server
please fix this bug this is my favourite server
@capa

**Comment by Trixter313** [comment]
Your best bet would probably be to first reply to the appeal on the forums if you still can. If that doesn't work, emailing support@wynncraft.com should help.
