### ISSUE TITLE
Definitive armor skin bug

### ISSUE THREAD

**Issue by SkySaito** [Wynncraft/Issues#2260]
Continuation of #1846
Hey again, Sky's here !
I'm here today to talk about my old problem. As you can see in my old issue, Spectre and Millenium didn't have their right skin when I put Bad Wolf. But now the problem is worse ! The now have permanently the wrong skin, even when I put on me other pieces of armor or nothing else with it.
So my question is : is there any way of fix this bug or I have to keep them like that ?
Thanks for your response ^^

**Comment by SkySaito** [comment]
Bump ?

**Comment by SkySaito** [comment]
Gonna add more proof. 
![2015-08-30_13 14 29](https://cloud.githubusercontent.com/assets/7000957/9954330/6a724cae-5de8-11e5-96cc-518395f4211d.png)
![2015-08-30_13 14 32](https://cloud.githubusercontent.com/assets/7000957/9954336/736f06f8-5de8-11e5-9d4b-4e82f1224b79.png)
![2015-08-30_13 14 33](https://cloud.githubusercontent.com/assets/7000957/9954338/7a8dbe16-5de8-11e5-8294-5505d22f4198.png)
As you can see, I still have the same bug with theses pieces of equipment, with or without anything else : 
![2015-09-18_09 40 58](https://cloud.githubusercontent.com/assets/7000957/9954464/8e600466-5de9-11e5-912d-deec90247de0.png)

**Comment by SkySaito** [comment]
Whoops, wrong button

**Comment by SkySaito** [comment]
Hum... Somebody ?

**Comment by SkySaito** [comment]
Helloooooo ?

**Comment by Chewsterchew** [comment]
Sorry for the long wait. Are you saying that the armour pieces are stuck to your skin, even when you take off that armour?

**Comment by SkySaito** [comment]
Nah, I'm saying that when I put those armor piece, they always have this wrong texture.

**Comment by SkySaito** [comment]
Bumpytibump

**Comment by SkySaito** [comment]
News ! Now Spectre is fixed ! Dunno how or why but the helm is fixed. Also Millenium is still wrong but there's good thing going on so.

**Comment by SkySaito** [comment]
Millenium is still glitchy tho.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
