### ISSUE TITLE
Connection Lost: Could not find a server to connect to, please report.

### ISSUE THREAD

**Issue by MegaPixelPerfect** [Wynncraft/Issues#2264]
![kjdg8oy](https://cloud.githubusercontent.com/assets/6833403/9573284/8de920ea-4f88-11e5-9a0d-b84f36d6a5e4.png)

I can't get on the server, every time I try to log on, I get this error. I have tried restarting my game. I'm using Optifine for 1.8, but I don't think that's part of the issue.

**Steps to reproduce the issue**
Main menu > multiplayer > join Wynncraft > this error instead of connection

**Comment by TrashcanMan** [comment]
This is probably just routine maintenance, just wait an hour or so and it should work.
If your issue is resolved we would appreciate it if you hit the "Close Issue" button. Thanks, and have a great day!
