### ISSUE TITLE
Stuck in Class Choice Area

### ISSUE THREAD

**Issue by Emirate-Joey** [Wynncraft/Issues#2267]
When I join any Wynncraft server, regardless of player number, after choosing the Archer class, I am stuck in the black area where you are supposed to change/choose your class. Going on any other class (e.g. My Warrior) I can leave the area and go into the normal world, but for the Archer I am stuck. This is especially annoying as the Archer is my highest level and the main class I play. I have restarted the game and done everything I could think of to try and resolve this issue, but I have no way to fix it without admin support now.
![2015-09-01_11 18 06](https://cloud.githubusercontent.com/assets/14072675/9602925/83b45c80-50a4-11e5-9b94-060caac9ba80.png)
![2015-09-01_11 18 11](https://cloud.githubusercontent.com/assets/14072675/9602928/87835a5a-50a4-11e5-8b0d-fce60b1b0157.png)
![2015-09-01_11 18 34](https://cloud.githubusercontent.com/assets/14072675/9602930/8a61dc92-50a4-11e5-905b-ca902be6ae22.png)

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue.
If it's not, we'd be happy to continue to assist you as much as possible.
Thank you and we hope you enjoy your time playing Wynncraft! :)
