### ISSUE TITLE
Payed 5 LE for a Guild, Didn't Create

### ISSUE THREAD

**Issue by supermariowifi** [Wynncraft/Issues#2268]
Around 8:55-9:00 on September 1st, 2015 I created a guild called "The Anarchy" with the abbreviation ANR. It deducted my LE and Soul Points, and said "You are the proud owner of "The Anarchy". However, when I did /guild to invite my friends, it said do '/guild join to join a guild'. I tried doing /guild join ANR to join my guild, but to no avail. I would like to request either my LE and Soul Points back, or the guild created for me. 

P.S. My IGN is supermariowifi and I play as a 51 Archer class.

Thank You,
supermariowifi

![2015-09-01_20 57 32](https://cloud.githubusercontent.com/assets/14083744/9620952/bc258892-50ee-11e5-87ad-585ad4d341bf.png)

![2015-09-01_20 58 35](https://cloud.githubusercontent.com/assets/14083744/9620963/da5737c0-50ee-11e5-93c1-5de1d7d571dd.png)

![2015-09-01_20 58 36](https://cloud.githubusercontent.com/assets/14083744/9620966/e0196caa-50ee-11e5-9119-62c7d7f61120.png)

![2015-09-01_20 58 40](https://cloud.githubusercontent.com/assets/14083744/9620968/e3d00c1e-50ee-11e5-9d49-f2af0886ba06.png)

![2015-09-01_21 00 23](https://cloud.githubusercontent.com/assets/14083744/9620970/e76589f8-50ee-11e5-8626-1a80d7f6794d.png)

**Comment by supermariowifi** [comment]
Wait a moment, it just created itself. That's weird. I guess it's a bit of lag. Sorry for bothering you! Keep working hard staff! :)

**Comment by TrashcanMan** [comment]
If your issue is resolved we would appreciate it if you could hit the "Close Issue" button. Thanks, and have a nice day!
