### ISSUE TITLE
Stuck in the class choosing room

### ISSUE THREAD

**Issue by bossbuster908** [Wynncraft/Issues#2269]
I was playing in when the server almost restarted so i did /hub then i got on another world and since i had the auto chose class thing on and the world as soon as i got on it restarted so i went on to another world but i was stuck in the tiny box of the class choosing room with no teleportation scroll.
I also tried to switch classes, log out and back in, restart Minecraft, kill myself, ask for help and use spells and horse my way out.

Also side note i was at nekromat by the item buyers, i was on my level 46 warrior and my user name is the same as this one so I would really appreciate it if you could please do something about it.

Sincerely bossbuster908.

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue.
If it's not, we'd be happy to continue to assist you as much as possible.
Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by bossbuster908** [comment]
ty
