### ISSUE TITLE
The custom skin will not be added to me.

### ISSUE THREAD

**Issue by Bombastickj** [Wynncraft/Issues#2270]
Hey Wynncraft Team!
I have a problem. The custom skin will not be added to my skin.. so there is just a gray guy in a suit(my skin :D) . 
Please help me and fix it :)!
My ingame name is TTG_Bombastickj

**Comment by PenguinJ2** [comment]
Turn on everything in the skin customisation (eg right sleve, left sleve, hat etc.)
