### ISSUE TITLE
Liquified Emerald not working

### ISSUE THREAD

**Issue by Infernox1099** [Wynncraft/Issues#2271]
I had a liquified emerald and i haven't been on wynncraft for a while and it seems like some NBT data might have changed with the liquified emeralds and i can't convert the 1 i already had back to emeralds or use it.

**Comment by TrashcanMan** [comment]
You can either go back to 1.7 and convert the old LE to the new ones, or you can go to the Converter Merchant at Selchar, which works in every version.
