### ISSUE TITLE
Blackscreen after Class selection

### ISSUE THREAD

**Issue by bTeam99** [Wynncraft/Issues#2273]
Hey, my friend has an issue. After he selects his Archer class, the only thing that happens, is that he gets his stuff. He stucks in the black wool room and is unable to do anything. Other classes work. That is not the first time it happens. Toggle Autojoin doesnt work, please help us,
~funnY

**Comment by Trixter313** [comment]
Typing /kill will get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by bTeam99** [comment]
Thanx rly. Hopefully it will wirklich out :D Do u know this issue allready, cause 3 of my Friends (all ve rubbish notebooks...) hat this issue.

**Comment by Trixter313** [comment]
Yeah, if you look at all of the closed issues you'll see this gets reported often, almost at least once a day.

**Comment by bTeam99** [comment]
And sorry, my Keyboard automaticually fills up german words... (*Work, *had)

**Comment by bTeam99** [comment]
I was not able to find this issue... If I searched for blackscreen After class selection there were no results...

**Comment by Trixter313** [comment]
Make sure you're searching the closed issues, not open.

If you search for just black, you see a few of them. https://github.com/Wynncraft/Issues/issues?utf8=✓&q=Black

People word it differently every time so you'd have to just scroll through all of the closed issues to see them all.

**Comment by bTeam99** [comment]
Ok, can I ask u another issue in this conversation? ^^

**Comment by Trixter313** [comment]
It's recommended to open individual posts for different issues and closing and solved ones.

**Comment by bTeam99** [comment]
Ok, so if it is, I will close this one. Thanks a Lot for ur help!
