### ISSUE TITLE
Cant See my Bow Animation 

### ISSUE THREAD

**Issue by bTeam99** [Wynncraft/Issues#2274]
Ive Seen some YouTuber, that have the normal bow Animation, but I cant See it. Is there any way to fix this?

**Comment by Trixter313** [comment]
Could you give a link to the video here? Or if not, at what date was the video posted?

Wynncraft uses a special system for bows to have more control over the arrows, so you shouldn't see the animation at all. This change was made months ago.

**Comment by bTeam99** [comment]
The Video is pretty old, I think it was Posted before one year. Ok thanks
