### ISSUE TITLE
Glitched in the void from using a selchar teleport scroll

### ISSUE THREAD

**Issue by malum2** [Wynncraft/Issues#2275]
![2015-09-07_14 56 58](https://cloud.githubusercontent.com/assets/14157880/9710835/e2ff1204-5570-11e5-9b71-f6c45d58cbe0.png)

My character is glitched. The screen is black whenever I log into it, this started when I used a Selchar Teleport scroll.

IGN: malum2

**Comment by Trixter313** [comment]
Typing /kill will respawn you at the nearest visited town.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
