### ISSUE TITLE
Guild XP Glitch

### ISSUE THREAD

**Issue by Pzev** [Wynncraft/Issues#2277]
I recently made a guild, and for some reason nobody in my guild, including me, can contribute any XP.  When I kill mobs it says they drop guild xp, but my guild remains at 0%.  I have easily pumped thousands of xp in trying to get it to work.  My ign is Pzev and my guild is Zevata (ZVT).

**Comment by TrashcanMan** [comment]
Known issue, duplicate of #2074. The staff is currently working on a fix. We advise that you watch the original post, and close this one.
