### ISSUE TITLE
Bugging in Blocks

### ISSUE THREAD

**Issue by SabionLp** [Wynncraft/Issues#2279]
Hi Wynncraft team 
Im in the Skeleton Dungon (Coords: -10046 -10585) and im bugging in the wall
Im ma mage and tried to teleport 
pls Help me

**Comment by Trixter313** [comment]
Typing /kill will get you out and bring you to the nearest visited town.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
