### ISSUE TITLE
Spawning with no Saturation

### ISSUE THREAD

**Issue by Bardley** [Wynncraft/Issues#2280]
Occasionally I spawn in with no Saturation and I do NOT regenerate hunger either. This is a quick relog to fix but it can get quite annoying. I have not found any form of pattern that would cause this issue to occur.

**Comment by Trixter313** [comment]
Doing /class should fix it also, which is easier and less time consuming.

**Comment by PenguinJ2** [comment]
This only happens to me when I have autojoin on.
