### ISSUE TITLE
Stuck in an area can't get out

### ISSUE THREAD

**Issue by Jamtarts** [Wynncraft/Issues#2282]
I am stuck in a little area with blocks 2 high all around me. I do not have any teleport scrolls and I have no idea how I got stuck and how I am going to get out. Any help would be appreciated.

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will bring you to the nearest visited town.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
