### ISSUE TITLE
tempel of legends

### ISSUE THREAD

**Issue by creeperkiller627** [Wynncraft/Issues#2283]
i have been reported by AllyouDoIsWynn because i hsowed him a glitch that i hoped he will report but he thaught i think that i wanted to use it but i seacrhed for a month someone to say to it but nonody did it so i hope i will not get banned and that grian will fix this glitch

**Comment by TrashcanMan** [comment]
Well if you didn't abuse the glitch, then I see no reason for you to get banned. Also, what exactly is this glitch? If it's easily abused, you might want to send a private message to Tama.
