### ISSUE TITLE
Climbing Helmet

### ISSUE THREAD

**Issue by talkMC** [Wynncraft/Issues#2285]
So yesterday, I was just grinding. I had my climbing helmet in my inventory (because I just did the Zhight Island Quest). Then, I somehow managed to drop my climbing helmet. Now first of all, this is usually not even possible. A message popped up in the chat saying that I'll need the item in later quests. Usually, you then get your item back but it was gone. I relogged the next morning to see if this was just a visual glitch but I still did not have it. Here is proof that I actual did have the climbing helmet: https://gyazo.com/b2d2bb0297597a7ed9334fa136270920. For the quest, 'Zhight Island', you need the climbing helmet. That picture shows that I completed it, meaning I had the climbing helmet. Can someone please find me in-game and give me a new climbing helmet (Because I'll need it in later quests).

Thanks!

-tallk

**Comment by Trixter313** [comment]
Typing /fixquests might return the helmet.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by talkMC** [comment]
Thanks!
