### ISSUE TITLE
Animal Dungeon

### ISSUE THREAD

**Issue by csum367** [Wynncraft/Issues#2286]
I got to the boss room one time and killed the boss, but I didn't get teleport out, so i had to kill the boss again. Even though the boss was no hard, the bug need to be fix after killing the boss in the dungeon.

Don't know if true: Seem like the game detects getting XP as killing the boss

**Comment by Trixter313** [comment]
This is most likely the issue where if you kill the boss too close to the edge of the arena it doesn't detect that it was killed. I suggest making sure it is as close to the center as possible when the final hit is made and seeing if you still experience this issue.

**Comment by PenguinJ2** [comment]
if it gets killed by fire e.g: the xp sign doesnt come up, it will also not register.
