### ISSUE TITLE
/guild xp

### ISSUE THREAD

**Issue by guillau213** [Wynncraft/Issues#2288]
Hey, I farm for 2 hours near Lusuco, it says that I won guild XP... and I didn'T won any... Example: 0 xp and 97 guild xp. I do /guild info and it says nothing... After 1 month. Please fix it!

**Comment by TrashcanMan** [comment]
Duplicate of #2074. The staff is working on this one, just be patient.

**Comment by Kidgib5** [comment]
Is this a 5 month repair process? Still an issue.
