### ISSUE TITLE
I'm stuck in the classes black box.

### ISSUE THREAD

**Issue by ChawHD** [Wynncraft/Issues#2289]
I'm stuck in the black box when i select warrior class, idk how this happened and please can someone tp me out?

https://gyazo.com/c84f3af97f818949b844003f59eed741

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will respawn you at the nearest visited town.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
