### ISSUE TITLE
Fell in the void from dungeon

### ISSUE THREAD

**Issue by AndyE7** [Wynncraft/Issues#2290]
I went to the silverfish dungeon and gave a key to the key collector guy and walked in and got teleported, the server then kicked me for flying for some reason, so I rejoined only to find myself falling in the void. I then typed /kill and re spawned at the tutorial area of the map instead of almuj

**Comment by Trixter313** [comment]
Are you stuck in the tutorial area? If you can get out there's not really a reportable issue here, unless you can reproduce it. Sounds like a one time issue to me.
