### ISSUE TITLE
Quest Glitch

### ISSUE THREAD

**Issue by AncientPancakes** [Wynncraft/Issues#2292]
When I started 'Lost Soles' [lvl 66 quest] The guy took my 'Abysso Galoshes' [boots needed to start the quest] and I had to log out, when I logged back in my Galoshes were gone, and my quest book was not updated, and the villager still wanted ma Boots, so now I cant do the quest ;_;

**Comment by TrashcanMan** [comment]
Have you tried /fixquests? It should return missing quest items.

**Comment by AncientPancakes** [comment]
omg im an idiot thanks! xD
