### ISSUE TITLE
Can't trade or access my bank

### ISSUE THREAD

**Issue by AshenKitty** [Wynncraft/Issues#2294]
Well, first of, I'm writing this in the name of my fiancé.
She doesn't speak English at all, but it's about her account.

Last night we changed her Mojang/Minecraft user name (from Sayu_Sanada to BlackMusicWolf), all good, everything worked.
When I logged in on her account today and tried to put some emerald blocks in her bank, it wouldn't let me, instead it kicked me out of that window and the blocks dropped down.
The same happened with the trade. I asked her to log in on my account so we could try to trade, again, it got cancelled.

Now I know to first look if anyone had the same issue, to no avail.
All I found people losing their VIP/VIP+ abilities in the lobby or how their name wasn't changed in guilds.

She still has the VIP+ status and abilities and her name changed in game, but she can't trade or access the bank anymore.
I even tried using another class she hasn't played yet, also to no avail.
Could anyone tell me how to solve that, without changing her name back?

**Comment by TrashcanMan** [comment]
I've heard of a similar issue before, though I can't find it right now.
A few people had the same problem, and it seemed to be somehow connected to having "music" in their usernames. After they changed it to something else everything was fine. I have no idea why that works, but I think it's your best shot right now. Unfortunately, I don't think there are any fixes that don't involve username changes.

**Comment by AshenKitty** [comment]
Hm, guess we have to give it a shot then, though that still would have to wait 28 days as Mojang won't let me change it yet.

I just really hope it works.
Thank you for the fast answer. ^^

**Comment by TrashcanMan** [comment]
Oh, I found the old one. #2076

**Comment by AshenKitty** [comment]
It's sort of creepy how a little innocent word has such an effect in game and I really wonder how this is even possible.

Well, as I said, I sadly have to wait until Mojang will let me change the name again and I really hope it works.

Guess we have to use my bank for the time.
Thanks again.

**Comment by AshenKitty** [comment]
So, after a long wait of 30 days and secretly throwing items at each other, we finally could change the name from BlackMusicWolf to ColdShadeWolf and tadaa, everything seems to be fine again.

As I said before, it's kind of creepy that a little word messes up so much, but oh well, the wait is over. 

Again, thank you for the help TrashcanMan, I'll close this case now.
