### ISSUE TITLE
Stuck In the Black Box

### ISSUE THREAD

**Issue by Wobbert** [Wynncraft/Issues#2298]
I tryied to join a server and now I'm stuck in the area where you select a class. I'm stuck there as my archer class, and my IGN is ThatWobbuffetGuy.
Edit: Others are getting stuck in here with me. We're on server 3. I don't know if other servers are being affected

**Comment by Trixter313** [comment]
I see that you closed the issue. Just in case you didn't mean to, using /kill with 3+ soul points will teleport you to the nearest visited town. =)
