### ISSUE TITLE
Underwater Quest

### ISSUE THREAD

**Issue by Jinxisnotonfire** [Wynncraft/Issues#2299]
Not only does the little guy at the ship at sea sometime not work but the chest under water in the ship won't open! Help???

**Comment by Trixter313** [comment]
You never actually open a chest in the quest, it should have said that your quest book was updated and you just return to the guy outside of the ship. As for the baby villager, sometimes you have to stand right inside of them and look down to be able to click on them. And you have to have the right kind of meat, from the pigman ravines.

**Comment by Jinxisnotonfire** [comment]
Thanks I'll try that
