### ISSUE TITLE
Quests Restarted

### ISSUE THREAD

**Issue by BlueRootm959** [Wynncraft/Issues#2307]
Both me and my friend's account's quests got restarted completely, saying we have not completed a single quest. We when back and was able to finish all of the quests except for the very first quest. The barrier keeps us from starting the quests and doing anything in Ragni, and there is no way to get to there. Is there a way we can fix this without having to create brand new characters? Our Minecraft account names are BlueRotom959 (Me) and Kungfu888 (my friend).

**Comment by Trixter313** [comment]
You can try typing /fixstart

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by BlueRootm959** [comment]
Thank you for your help. I will pass this information on too my friend.
