### ISSUE TITLE
Not allowing me to join Wynncraft? username: Diamondz_n_lava

### ISSUE THREAD

**Issue by Diamondz123** [Wynncraft/Issues#2311]
Hello, I recently tried to join the wynncraft server, after not going on it for many months, upon trying to join, i was denied with this message: 
Exception Connecting:RunTime Exception:Server is online mode! @net.md_5.bungee.ServerConnector:261
I tried to post a screenshot of this but it is not allowing me to
Prior to this message i was greeted with a different one saying:
No server to connect to,please report
I'm not sure what I have to do as I've never dealt with this before, any help?

**Comment by Diablo338** [comment]
I have the same problem since yesterday I do not any more manage to connect

**Comment by Diamondz123** [comment]
Now working after repeated attempts to join, sorry.

**Comment by MrPigglet** [comment]
Don't worry man, you have not been banned or anything like that, i have the same issue, and all of my friends have it aswell. Wish they would fix it ;(

**Comment by Diamondz123** [comment]
After reepeated attempts I managed to connect once, I disconnected to retry it to no avail, I guess I'll just have to wait for it to be fixed.
