### ISSUE TITLE
Spawn point not working for me

### ISSUE THREAD

**Issue by TakeshiHaruto** [Wynncraft/Issues#2315]
when I go into a world and choose my warrior class it doesn't spawn me anywhere. I just get stuck in a black room and a can't go anywhere.
need this to be fixed plz and need a mod or someone to change my spawn point so I can play.
:D

**Comment by Trixter313** [comment]
I see that you closed the issue so I'm guessing you going a way to get out but just in case you accidentally closed it, typing /kill with 3+ soul points should get you out and teleport you to the nearest visited town.
