### ISSUE TITLE
Armour skins resetting skin changes

### ISSUE THREAD

**Issue by azureadventurer** [Wynncraft/Issues#2317]
I have a set of armour I've been using for quite a while as a mage, I'm lv.54 if that helps.
I recently changed my skin and it will revert to my old skin if I am wearing the full set, the skin will change if I'm not.. I want to at least know what is happening.
Using Minecraft ver 1.8

**Comment by Trixter313** [comment]
It will just take a little while for the armor system to update to your new skin.
