### ISSUE TITLE
The server is completely bugged! (This issue is fixed now)

### ISSUE THREAD

**Issue by Emik03** [Wynncraft/Issues#2321]
I have joined the server and I realised that you cannot play Wynncraft, You canont join lobbys, You can't do commands, PvP is enabled, People use caps in chat and flood the chat with one message and so on.

I am sorry if this is not to long but I really needed to notify the Moderators that the server needs to be fixed.

Good luck!

(I attempted to upload a video here but it is too big...)

**Comment by Emik03** [comment]
Also proof for caps, advertising and spam:
![2015-09-21_20 51 20](https://cloud.githubusercontent.com/assets/14614115/10002686/e46dc3cc-60a8-11e5-88c4-db6de390dc94.png)

**Comment by TrashcanMan** [comment]
Ban reports go here: https://forums.wynncraft.com/forums/player-reports.83/ Make sure you follow the correct format.

**Comment by Emik03** [comment]
Now the server is fixed, can anyone close this issue?
