### ISSUE TITLE
Guild Chief gone after name changing.

### ISSUE THREAD

**Issue by Corneille198** [Wynncraft/Issues#2324]
Hello, 

I made a guild quick after the guild update and I was the Chief. I changed my ign after name changing was introduced to minecraft, I changed it from "supercorneille" to "Corneille", after that I lost my Chief rank. and nobody else was a higher rank then recruit so my Guild became useless. my guild is named "Team Heromysta" and "THm". I don't want to change it back.
I have send a mail to Wynncraft Support but they responsed prety late and they said I had to mail Jumla about it because they could fix this, but he didn't response after a couple of months.
I hope someone can help me with this.

-----------
Corneille

**Comment by TheMineNerf** [comment]
u will have to change it back and then wait again to change it to what u want as u need to leave the guild by that giving leader (as u said u opened the guild so u are leader) to the oldest chief. after u leave u change your name and get reinvited. then he demoted all other chiefs gives you chief and leaves. then u inv him and give him and all the other that had chief. hope its not too complicated
