### ISSUE TITLE
2 water air pocket at blue shrine I

### ISSUE THREAD

**Issue by shaharcoolmen** [Wynncraft/Issues#2333]
i found these 2 water air pockets at the blue shrine I
(there are cords in the images)

![2015-09-25_16 10 56](https://cloud.githubusercontent.com/assets/7313099/10101271/6519f208-63a0-11e5-8731-5fdca3d74646.png)

![2015-09-25_16 11 21](https://cloud.githubusercontent.com/assets/7313099/10101295/87f34824-63a0-11e5-9f25-e74f723879f1.png)

**Comment by shaharcoolmen** [comment]
the cords are under the map....

**Comment by TrashcanMan** [comment]
This is kind of unrelated but from what I can tell your mob radar is on, and that is a bannable offense. Minimaps are allowed, but ALL radars must be turned off.

**Comment by shaharcoolmen** [comment]
wait dont ban me!
if i will turn off the radar in the minimap settings is it ok?


2015-09-26 3:41 GMT+03:00 TrashcanMan <notifications@github.com>:

**Comment by Trixter313** [comment]
Yes, you should be ok as long as you keep all radars disabled. =)

**Comment by shaharcoolmen** [comment]
ok ill turn it off....

2015-09-26 23:20 GMT+03:00 Nick Cipriani <notifications@github.com>:
