### ISSUE TITLE
spawns in a dark room??

### ISSUE THREAD

**Issue by Miningmachine1** [Wynncraft/Issues#2334]
I was last in Nemract when I logged out. I think in the bank. Now when I log in again I choose my class and am spawned in a dark room made of wool blocks!? obviously no escape so I can't play anymore!! please fix it quick! :(

**Comment by TrashcanMan** [comment]
Do /kill if you have at least 3 soul points

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
