### ISSUE TITLE
mana/hunger

### ISSUE THREAD

**Issue by shaharcoolmen** [Wynncraft/Issues#2335]
when you think about it the hunger is actually mana and that means that running should'nt use the mana... what's annoying is that you cannot regenerate mana while you run....
i suggest making running and normal minecraft hunger uses not really use mana and maybe block the mana usage of them
(maybe add hunger using the same code that removes hunger?)

**Comment by TrashcanMan** [comment]
This isn't really a bug...

**Comment by Trixter313** [comment]
It would be better to post this here: https://forums.wynncraft.com/forums/general-suggestions.69/

Also it would be appreciated if you closed the issue here to keep the issue tracker decluttered. Thanks!

**Comment by shaharcoolmen** [comment]
sry... closing...

**Comment by shaharcoolmen** [comment]
waaait
how do i close this post?

**Comment by Trixter313** [comment]
When you comment there should be a button that says comment and close. =)

**Comment by shaharcoolmen** [comment]
oh i found it tnx @Trixter313
