### ISSUE TITLE
Lobby, able to get outside the map

### ISSUE THREAD

**Issue by TNTPata** [Wynncraft/Issues#2337]
I was bored, and discovered that you could get outside the map in following cords.
![2015-09-26_13 32 02](https://cloud.githubusercontent.com/assets/11095852/10117342/e1dc4fd0-6453-11e5-8701-9cdeee647131.png)

**Comment by Chewsterchew** [comment]
There are many ways to get out of spawn, I have myself. I think it is intentional, but it may just be an Easter egg :O
