### ISSUE TITLE
Server is online mode!

### ISSUE THREAD

**Issue by Chalybern** [Wynncraft/Issues#2339]
When i try to connect i get the message:
Exception Connecting:RuntimeException : Server is online mode! @ net.md_5.bungee.ServerConnector:261
I'd really like to play this server and i don't know how to fix it on my end.

**Comment by Trixter313** [comment]
Could you provide a screenshot of the issue? It might resolve itself with a little bit of time but you could try restarting Minecraft, your computer, and your router.

**Comment by Chalybern** [comment]
It resolved itself and i can access it, but thanks for responding! : )

**Comment by Trixter313** [comment]
Ok, great!

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
