### ISSUE TITLE
Jungle Fever

### ISSUE THREAD

**Issue by Tuddy2** [Wynncraft/Issues#2342]
In the Jungle Fever Quest I did the last stage: I brought Worid 64 Quest LE, during this I got 4 Real LE in my inventory.
When I finished the quest, Worid took 60 of the 64 Quest LE and my 4 Real LE. I got the XP and 1 LE as present from Worid. But now I still got 4 Quest LE.
I would like to have my 4 LE back...

I hope this bug will get fixed

**Comment by FreeFlyin** [comment]
This happened to me too I had real le in my inventory and i did the same thing now i have 2 quest le left over
