### ISSUE TITLE
My relice paper gone 

### ISSUE THREAD

**Issue by XwaleedGaMeRX** [Wynncraft/Issues#2343]
there is A bug when i were  trade with someone in a dungeon i accepted the trade and my inv was full 
i put the paper in trade inv and when i canceled my paper remoed !! Cuz my inv was full and i cant drop any item in trade so can u bring back my relic paper plz ;( 

my name in minecraft is ; XwaleedGaMeRX

**Comment by TrashcanMan** [comment]
Unfortunately if you're conducting a trade with a full inventory any loss of items is your fault. Also, Wynncraft has a no-refunds policy, so we can't get it back.

**Comment by XwaleedGaMeRX** [comment]
ok but i cant drop any item when i trade

**Comment by TrashcanMan** [comment]
Well you shouldn't enter a trade with a full inventory, or even a near-full inventory if there are items on the ground near you.
