### ISSUE TITLE
Wynncraft VIP Forum Command isn't working

### ISSUE THREAD

**Issue by tancat** [Wynncraft/Issues#2344]
I keep trying to use the VIP forum command /forum tancat100 (my forum username) to link my minecraft account to the forums, but it never works

![image](https://cloud.githubusercontent.com/assets/14859968/10123038/c7f39946-64fa-11e5-8587-fed22ab1cc42.png)

It always says this
Please help!!

**Comment by tancat** [comment]
Also all the other threads i found didn't give me an answer

**Comment by zutetflute** [comment]
that is sane for me

**Comment by SkySaito** [comment]
This command is still broken. Wait for the next update, it'll be fixed.
