### ISSUE TITLE
"Cannot find a server to connect to"

### ISSUE THREAD

**Issue by CheesePrince13** [Wynncraft/Issues#2346]
![wynnreport](https://cloud.githubusercontent.com/assets/13487814/10126305/453662bc-6555-11e5-9761-8502164f9c29.png)
Whenever I try to connect to the Wynncraft, I am met with this message. In case I did not attach it properly, the message simply states "Could not find a server to connect to, please report." I appreciate any help that may be provided and hope it will be resolved soon.

EDIT: I now no longer have just this one specific issue, I now also get a screen telling me that the server is in Online Mode. Unless I am misinformed, this stops fake accounts from accessing a server. However, my account should not be false since I purchased it from the Minecraft website.

**Comment by tttom64** [comment]
I'm having the exact same issue. All other servers are working fine.
![capture](https://cloud.githubusercontent.com/assets/13117753/10126520/568ba036-65d7-11e5-8925-924eb5ccd978.PNG)

**Comment by CheesePrince13** [comment]
is there a way to specifically connect to the other servers?

**Comment by tttom64** [comment]
Not sure what you mean, they all (except Wynncraft) work as you'd expect.

**Comment by JayStarMC** [comment]
Ive been having the same problem for the past [ Two Days ] and haven't seen it before. It usually works the next day but comes back during the night.

**Comment by casa144** [comment]
That happened to me just now, idk what happened ALL the other servers are fine, but don't panic, it could be because of 1 small update (NOT Gavel :O) but who knows.

**Comment by TrashcanMan** [comment]
If you can't connect to the server it's probably down for maintenance, just wait an hour or two and it should be back on.
If your issue is resolved we would appreciate it if you could close this report. Thanks!

**Comment by kreenka** [comment]
same

**Comment by tttom64** [comment]
Judging by the hundreds of players online, the error code and the amount of time we've had thw issue for, I highly doubt that the server is down for maintainence.
