### ISSUE TITLE
BungeeCord Error - Server is online mode!

### ISSUE THREAD

**Issue by Whist34** [Wynncraft/Issues#2347]
Error: Exception Connecting:RuntimeException : Server is online mode! @ net.md_5.bungee.ServerConnnector:261

I and a friend continue to get this as we try to login to the Wynncraft server - not worlds, just the lobby.

I looked this error up and it is caused when the configuration file for bungeecord is not set correctly - server is supposed to be set to offline mode when you are using bungeecord. I think someone has been working on the servers or updating things and didn't check the config settings?

Solution and Reference  Github BungeeCord Issue 847:
https://github.com/SpigotMC/BungeeCord/issues/847

**Comment by kreenka** [comment]
same its not working for me help
