### ISSUE TITLE
My own /fixquests problem

### ISSUE THREAD

**Issue by XXDeathScytheXX** [Wynncraft/Issues#2348]
So ya My IGN is : XXDeathScytheXX
and recently I had a problem with /fixquests ive did it and now i have 65 purple crystals that I cant get rid off and 1 or 2 yellow crystals it can be found in my Enderchest could you please remove it its taking up inventory place and its so annoying.

**Comment by TrashcanMan** [comment]
You could try glitch-destroying them by placing them into a loot chest and then closing the loot chest really fast, or filling your inventory then dropping them.

**Comment by XXDeathScytheXX** [comment]
Omg ty so much I don't know how i can thank you enough
