### ISSUE TITLE
Can't beat Wynn Excavation D

### ISSUE THREAD

**Issue by xCalico** [Wynncraft/Issues#2355]
for some reason when I am supposed to kill Corrupted Amadel, when I kill him, nothing happens and I still can't get out, I killed him twice before he killed me (some how) in one hit. I don't know if it is a bug, or what, but still wanted you all to know about it. oh, and whoever made the story for the quest, kudos to them. it is great.

**Comment by Trixter313** [comment]
Was he near a wall/far away from the center when you killed him? There is a known issue where if the mob is killed far away from the center it won't register. This might be what you're experiencing.
