### ISSUE TITLE
Cant log into any server

### ISSUE THREAD

**Issue by Sorceric** [Wynncraft/Issues#2357]
I can't join any server. It's been 8 hours now and It still says "You are already logged in! Please wait a few seconds." Plz Fix this

**Comment by M0RGaming** [comment]
same thing is happening to me

**Comment by M0RGaming** [comment]
exept its been happening to me for 2 days

**Comment by Ambertje** [comment]
I know this problem and i made a bug about it go look at it it explains

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
