### ISSUE TITLE
The priest

### ISSUE THREAD

**Issue by bronzzze** [Wynncraft/Issues#2358]
When I am talking with The Priest from Grave digger quest(https://wiki.wynncraft.com/index.php?title=The_Priest). I am cliking on him and nothing happend just blank space go on.
http://i.imgur.com/uZlImVa.png

**Comment by Trixter313** [comment]
Have you tried doing it on a different server?

**Comment by bronzzze** [comment]
yes. But its okay. I didn't need to speak with him anyway. I messed up. Thanks anyway.
