### ISSUE TITLE
Bug in a block

### ISSUE THREAD

**Issue by iJordan06** [Wynncraft/Issues#2359]
I am to surround in a block, can free me to you or me tp has the city or I am please.

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will teleport you to the nearest visited town.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by iJordan06** [comment]
Your solution solved my problem! Thank you very much!
