### ISSUE TITLE
Got stuck in a wall

### ISSUE THREAD

**Issue by Windstorm6961** [Wynncraft/Issues#2364]
I logged off when entering a dungeon (spider dungeon) because it wasn't loading correctly and when I logged on again, I was stuck in a wall, this happened with another class as well and I just really don't want to have to redo all the quests in a different class. My IGN is windstorm6961

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
