### ISSUE TITLE
Teleported into a tree

### ISSUE THREAD

**Issue by UriahTheColombian** [Wynncraft/Issues#2365]
I was teleported into a tree in Nemract and i am now stuck under the tree and i cannot teleport out

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will teleport you to the nearest visited town.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
