### ISSUE TITLE
Wynn Excavation Quest Glitch A->B , I Done Wynn Excavation A, But Somehow, I Auto Started Wynn Excavation B, and When i Talked to That Starting Wynn Excavation B Guy, He Said to Go to Almuj And do Wynn Excavation A When i Had done It

### ISSUE THREAD

**Issue by PwnagePotato4** [Wynncraft/Issues#2366]
Wynn Excavation Quest Glitch A->B , I Done Wynn Excavation A, But Somehow, I Auto Started Wynn Excavation B, and When i Talked to That Starting Wynn Excavation B Guy, He Said to Go to Almuj And do Wynn Excavation A When i Had done It

Please Fix This
Lovely Pwnage,
Pwnagezzzz

**Comment by PwnagePotato4** [comment]
someone help i beg u guyz i wanna do quests :)

**Comment by TrashcanMan** [comment]
You're supposed to bring the Yellow Crystal Shards that you got from Wynnexcavation A to Wynnexcavation B to start the quest.
