### ISSUE TITLE
Zhight quest climbing helmet not working

### ISSUE THREAD

**Issue by PlumedeGivre** [Wynncraft/Issues#2367]
Hello, Thyras here, so I am currently doing the Zhight quest, I have my climbing helmet from the icy nations quest, and well I still have that message 'you need the climbing helmet' but I have it !

I got this climbing helmet from my archer.

**Comment by Trixter313** [comment]
You have to be wearing the helmet to do the quest. Are you sure you're wearing it and it's not just in your inventory?
