### ISSUE TITLE
Almuj Liquified Emerald

### ISSUE THREAD

**Issue by WorkmanMM** [Wynncraft/Issues#2368]
I did the Jungle Fever quest with the 2 le i got from Twain Mansion, and it took the two real le and 62 of  the fake. Now i've lost 2 le and got 2 quest items i can never get rid of. plz help ;-;
My IGN is WorkmanMM
![2015-10-03_09 02 02](https://cloud.githubusercontent.com/assets/14667740/10263492/de1a8682-69ad-11e5-9575-7fe3d10fb966.png)

**Comment by Chewsterchew** [comment]
Relates to Issue #1827 and confirms it.
