### ISSUE TITLE
Login Bug...

### ISSUE THREAD

**Issue by MythikiX** [Wynncraft/Issues#2372]
This is really a problem my friend has been having actually. Her username is Hailgame, and every time she tries to log into Wynncraft, the farthest she can go is the lobby. Whenever she gets to the class selection screen and chooses a class, everything pauses and she gets sent back to the lobby. It'll always say "There has been an error. Please log back in!" But she'd tried that. Many many many times. So please help by fixing this bug! Thank you.

**Comment by Chewsterchew** [comment]
Has it just been happening or has it been for a while now?

**Comment by MythikiX** [comment]
It has been happening for a while now. We tried contacting Wynncraft's Twitter Support but they didn't answer yet...

**Comment by Ambertje** [comment]
I know this problem and i made a bug about it go look at it it explains

**Comment by Trixter313** [comment]
Is the issue still occurring?

**Comment by MythikiX** [comment]
The issue is in fact still occurring... but thanks Ambertje for clearing up on what is exactly happening. So all that needs to be done is a global restart?

**Comment by Trixter313** [comment]
Are you still having this issue since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by MythikiX** [comment]
Unfortunately, it is still persisting. :(

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
