### ISSUE TITLE
"Disconnected/Timed out"

### ISSUE THREAD

**Issue by GreenGG** [Wynncraft/Issues#2374]
This happens whenever I log in.

**Comment by Chewsterchew** [comment]
Does this work on every server or just this one?
Has it been happening often or just now started?

**Comment by raider112233** [comment]
Same here... i can't connect to wynncraft and it only happens to that server, and it didn't happen before

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
