### ISSUE TITLE
Real Liquid Emeralds being taken instead of Quest Item LE

### ISSUE THREAD

**Issue by TheBeaver99** [Wynncraft/Issues#2375]
I (TheBeaver99) was trying to do the level 52 Quest called "Jungle Fever" with my level 52 Archer.(https://wiki.wynncraft.com/index.php?title=Jungle_Fever) When I completed the quest, I was given a Liquid Emerald and the Stack of 64 Quest-item-Liquid-Emerald was taken away. Here's the problem though; I keep nearly all my money that I have earned on my Archer with my Archer, instead of in my bank. When I completed the Jungle Fever Quest, it took 64 "Bottle of Enchanting" IDs out of my Inventory. However, instead of taking the 64 Quest item LE, the quest took five of my Liquid Emeralds that I had on me and 59 of the Quest item LE's. This left me with the one LE that the quest gives you as a reward, and five Quest item LE's. I only realized this once I had gotten to Troms. I would like it these five Quest-item LE could be traded back for my regular LE. If a moderator could set up a time with me for trading the Quest LE for the Regular LE, that would be greatly appreciated, as I worked pretty hard for that stuff. My username is TheBeaver99.

As a proposed "fix" you could edit the Quest Dialogue to include a warning along the lines of "WARNING: Do not try and complete this quest with Non-Quest item Liquid Emerald in your inventory." Or maybe try and assign the quest item LE a certain damage value and have the quest only take Liquid Emerald with that damage value, so it avoids taking Liquid Emerald that isn't a quest item.

Below should be two screenshots confirming that I did in fact complete the quest, and that I have the 5 Quest item LE.
![2015-10-05_21 22 46](https://cloud.githubusercontent.com/assets/12473340/10299021/e5adb49c-6baa-11e5-87ba-8d4f53a2b35d.png)
![2015-10-05_21 23 10](https://cloud.githubusercontent.com/assets/12473340/10299031/f9af629c-6baa-11e5-9748-994f8f27a62f.png)

**Comment by Chewsterchew** [comment]
#1827 #2368

**Comment by TrashcanMan** [comment]
I think if you contact support@wynncraft.com they might be able to help you.
