### ISSUE TITLE
quest bug

### ISSUE THREAD

**Issue by mcmac223** [Wynncraft/Issues#2376]
i did the reincarnation quest but never get the corrupted treasure
![2015-10-06_10 40 36](https://cloud.githubusercontent.com/assets/14993263/10303877/f2b2dbec-6c16-11e5-8a81-a658ee2203a5.png)
![2015-10-06_10 40 57](https://cloud.githubusercontent.com/assets/14993263/10303888/fb515df0-6c16-11e5-8b96-47261fb2a914.png)
![2015-10-06_10 41 01](https://cloud.githubusercontent.com/assets/14993263/10303894/0190e848-6c17-11e5-9c65-51b0138226b8.png)
![2015-10-06_10 41 04](https://cloud.githubusercontent.com/assets/14993263/10303899/06a3ff46-6c17-11e5-98ae-b8a0b73ed669.png)
![2015-10-06_10 41 06](https://cloud.githubusercontent.com/assets/14993263/10303904/0ab1eaf8-6c17-11e5-9c0a-1b3471e4803c.png)

**Comment by SkySaito** [comment]
Have you tried the command /fixquest ?

**Comment by mcmac223** [comment]
yeah i tried but it gave me nothing

2015-10-14 23:22 GMT+02:00 SkySaito <notifications@github.com>:
