### ISSUE TITLE
"You are already logged in"

### ISSUE THREAD

**Issue by M0RGaming** [Wynncraft/Issues#2377]
hey, when i join the server, and attempt to join a "sub server" (like WC1) then it stops me from joining and sais that you are already logged in to that server. Plz help me. My IGN is M0R_Gaming. M(Zero)R

**Comment by SkySaito** [comment]
Try restarting your Minecraft.

**Comment by Ambertje** [comment]
I know this problem and i made a bug about it go look at it it explains

**Comment by SkySaito** [comment]
If your problem is not a problem anymore, please close this issue.
