### ISSUE TITLE
new skin and armor skins problem

### ISSUE THREAD

**Issue by PingasGaming** [Wynncraft/Issues#2378]
So I got a new skin but when I logged in I had my old skin (with armor)
![javaw 2015-10-06 17-10-13-07](https://cloud.githubusercontent.com/assets/12382958/10313005/d97c075c-6c4d-11e5-8fff-251452405bdc.gif)

**Comment by Chewsterchew** [comment]
This is intentional, the armour changes your skin.

**Comment by TrashcanMan** [comment]
@Chewsterchew what he meant is that he updated his skin but when he put armor on it goes back to his old skin.
@PingasGaming this is a known issue though I can't find the original. Just wait a few weeks and the skin database should update.
