### ISSUE TITLE
I am stuck in the wall on christmas chaos

### ISSUE THREAD

**Issue by Thogurus** [Wynncraft/Issues#2381]
PLEASE HELP, I WAS PLAYING CRAFTMAS CHAOS WHEN I GOT TO THE CAVE THAT LEAD TO THE HEART OF SELCHAR (The future one where everything is corrupted) I went down there, jumped in, and now all the sudden Im stuck in the wall with noway to get out, I have no teleportation scrolls, I AM STUCK ON MY MAGE ACCOUNt, PLZ HELP, MY IGN IS THOGURUS

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by etayyy12** [comment]
man i have a pretty Similar issue
i played for like hour today and after i restart my minecraft i suddenly get stuck in dark cage D:
I cat see nothing there and im starting to freakout 
my souls r not Renewable so i cant even /kill
plz help

**Comment by etayyy12** [comment]
and i cant use nemract scroll 
im thnk im stuck under this town

**Comment by Trixter313** [comment]
Are you saying that your soul points aren't regenerating @etayyy12 ?
