### ISSUE TITLE
creative mode hole next to Ragni.

### ISSUE THREAD

**Issue by Zeldon567** [Wynncraft/Issues#2385]
Just thought this was a little immersion breaking and should be fixed. 
![image](https://cloud.githubusercontent.com/assets/15073285/10416145/1bc5704c-6fcf-11e5-97ff-e0e9df0161b3.png)

**Comment by AckroWynn** [comment]
We will look into fixing it, and it should be updated once Gavel is released.
Thank you for noticing!

**Comment by Zeldon567** [comment]
Glad I could help.
