### ISSUE TITLE
/guild defend in Detlas Does Not Work; Able To Claim Detlas Territory Automatically By Doing /guild attack

### ISSUE THREAD

**Issue by Submonsterine** [Wynncraft/Issues#2388]
Hello! I was experiencing this issue the day beofre, and thought it was just a glitch on the server that would get fixed with a server restart. However, I logged on again this morning to test if the glitch still occurred; it did. I went on multiple servers to see if it was just one server that was being affected by this, but it seems most, if not all, are.

   I'm not sure if this applies to territories other than Detlas, but from what it seems, Detlas is the only one that I know of that is affected by this (I went to Detlas Suburbs and a bit of the surrounding area. They all had many mobs defending the territory, indicating that /guild defend is working properly)[Possibly Nesaak Bridge Transition has the same issue...?]. With Detlas, if you simply use the command /guild attack, it automatically hands the territory over to you. You are also not given any message when you buy mobs for the territory, and when looking again, it does not show that you have purchased any mobs. The emeralds used to buy troops for defending are either refunded, or never spent in the first place.

Steps to recreate:

1. Go to Detlas
2. If you are in a guild and have the rank required to claim and defend land, do /guild attack
(The land should automatically be handed to you, without a countdown or confirmation asking [WARNING: THIS TERRITORY HAS [number] MOBS DEFENDING IT. ARE YOU SURE YOU WANT TO ATTACK?])
3. Look at the top "guild" bar. After a bit, once it finishes updating, you should see that you are, in fact, in control of the territory. You can also type the command /guild attack again to confirm.
4. Do /guild defend.
5. Buy a random number of mobs for the territory, preferably low leveled ones that don't use many emeralds in the scenario that emeralds are lost and mobs are not bought for the territory (although I myself have not had this happen, better to be safe.)
6. Wait a few minutes.
7. You should notice that there is no "Congratulations! You have bought x mobs for this territory" in the guild log. 
8. Do /guild defend again, and check the number of mobs you have bought that are defending Detlas. If the bug is still occurring, then there should be none, and your emeralds *should* still be the same in amount.

Attachments:
![2015-10-11_11 16 42](https://cloud.githubusercontent.com/assets/15076431/10417543/6fa20cb4-700d-11e5-93a1-1c7c3f03aaa4.png)
![2015-10-11_11 21 45](https://cloud.githubusercontent.com/assets/15076431/10417545/770984be-700d-11e5-8228-07ade9d16e13.png)
![2015-10-11_11 21 47](https://cloud.githubusercontent.com/assets/15076431/10417546/78342650-700d-11e5-9d1d-27aaa05578e2.png)
![2015-10-11_11 41 24](https://cloud.githubusercontent.com/assets/15076431/10417550/89993ad4-700d-11e5-85f1-666e013bd4f2.png)

(I had several apps running in the background, so don't comment on my framerate... It's usually around 40-50 fps.)

**Comment by Chewsterchew** [comment]
I am attacking Detlas but I haven't claimed it instantly.
