### ISSUE TITLE
Tower of Asce. Quest Glitch

### ISSUE THREAD

**Issue by Grantdrew** [Wynncraft/Issues#2389]
Ok Im not going to fully introduce myself, but I am Grantdrew. So I was at the tower of ascension and Im a lvl 50 Archer so I though that I should finish up the first floor. So I enter the floor go through all the mobs kill and collect all the way to the last boss. Now I hadn't experienced anything strange or glitchy until battling with him. The first time I got him cornered and killed him. He died but dropped nothing. I searched all over but was interrupted by another one of his clones/the same boss. I died and respawned at the local spawnpoint town. Thinking I had missed something, I continued going through the levels again and killing the boss 4 more times only to receive nothing over and over. I was frustrated by now and at only 8 soul points I decided to try it one more time. I ran past the levels with the shards passing level after level. I killed the boss/polar bear again and I saw the token! I ran to it and collected it, but when I tried to turn it in I was teleported. (at this point I was completely confused) Minecraft's "Downloading terrain" poped up along side with the dirt background and then I was just disconnected to the server. Still confused I joined back and joined the 2nd world to find that I was now in the very beginning! No, not the local town, not the tower of ascension's other floors, but at the very beginning where when a person FIRST logged on to wynncraft they would be taken to when they joined a class into a world. I was behind Ragni. I stood there watching as others passed me doing the tutorial and moving along. I ran all the way back to the tower of ascension and went through all the floors and killed the boss (dropping nothing as usual) and proceeded to the gate keeper or the floor guy. As soon as I try to pass him I am glitched and not allowed to move while the messages of not being allowed to be there because I have no token spammed my chat. Now there was something more than just this taking place. I turned my head still not able to move as I watch a big fury white with black eyed face pop up and SMOTHER ME WITH ITS FUR.. which was that DAMN POLAR BEAR! I died. I respawned again (enraged) and decided to report this but just to make sure. I logged back in (yes I rage quit :P) and joined the 2nd world again only to be spawned into the local town unground as I slowly suffocated. I managed to survive with my trusty Relic Bow which gave me a boost up out of the cold hard ground. Then decided to just verify the email to secure my account and be able to tell you about this terrible glitch. I have all the shards and the boss shard if you would like to contact me and have me show them to you I'd be more than happy to do so. Thank you for reading this long annoying story (if you did)... wait. Thats not all. Now I had finished this story that you just read and made some corrections to make it flow a bit more smoothly then I thought, "Maybe I should just add the screenshot with this." So I logged back into wynncraft at the hub and pulled out my navigator right clicked then proceeded to crash :^). I like wynncraft in all its glory, but THIS, this is not glory. Ill get the screenshot though. Somehow..
![2015-10-11_20 04 54](https://cloud.githubusercontent.com/assets/15080512/10419898/65b984b6-7053-11e5-9f08-ac3e7ff06b36.png)

**Comment by Moe-Ronickah** [comment]
I don't know if you have gotten past this mess, yet, however, here is some advice.  First, if you ever get the dreaded background "Downloading terrain" again, after you get logged in, logout and login.  That is a server error and it can glitch your game.  Second, if you get glitched in any MC game or server, and cannot move, close down MC and restart it.  If you are still glitched and cannot move, use your arrow keys when you log back in, this will sometimes get you out of a stuck place.  Let us know if any of this helped, or if you are already through the boss, finally.  [Sign me "Been there.  Done that.  Raided the peanuts."]
