### ISSUE TITLE
Chunk Error/ deleted Chunks

### ISSUE THREAD

**Issue by Leon2403** [Wynncraft/Issues#2390]
In the Ocean at the border to Gavel are a couple missing chunks (flat grass land). The coordinates are -700, -4100

**Comment by Chewsterchew** [comment]
![2015-10-12_14 53 57](https://cloud.githubusercontent.com/assets/8278263/10437207/20acab70-70f1-11e5-9044-f586c5cccd7e.png)
I can't find what you're describing.

**Comment by Leon2403** [comment]
Maybe it was just a clientside bug

**Comment by Chewsterchew** [comment]
can you provide a screenshot?

**Comment by Leon2403** [comment]
Unfortunately not :/ I'll check this out again tomorrow and report if it still occurs

**Comment by Chewsterchew** [comment]
Awesome! If I have helped you, you may close this issue, you can always re-open if need be.

**Comment by Leon2403** [comment]
OK thx :) ill close this and reopen if I find this bug again

**Comment by MKStudios** [comment]
![2015-12-23_22 06 02](https://cloud.githubusercontent.com/assets/16423015/11990966/4b75516e-a9da-11e5-88a1-b9f887180d28.png)
![2015-12-23_22 02 01](https://cloud.githubusercontent.com/assets/16423015/11990965/4b6daafe-a9da-11e5-822b-4c3e0b2eaf81.png)

To the mod following this I attached two chunks i found in the approximate area being described.

Your welcome!

-MK
