### ISSUE TITLE
My character is bugged!!!

### ISSUE THREAD

**Issue by DrPepperMessiah** [Wynncraft/Issues#2391]
I try to log onto my old character that I created a long while ago; but I am stuck in the room filled with black wool where you pick your class. Help!!!

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
