### ISSUE TITLE
Can't finish quest!

### ISSUE THREAD

**Issue by kuuhakusenpai** [Wynncraft/Issues#2393]
![2015-10-13_02 55 14](https://cloud.githubusercontent.com/assets/15106633/10455280/03bdf8a6-7156-11e5-9200-34de622ccfdf.png)
So I was doing the Lord of the Clocks quest and when I was giving the clock to Frudo the server restarted, now I can't turn it in.. If I right click frudo it shows blank text

**Comment by commandhat** [comment]
Does /fixquests not work?
