### ISSUE TITLE
I'm lock !

### ISSUE THREAD

**Issue by Jumojulien** [Wynncraft/Issues#2394]
Hi, I'm stuck in the world via a teleportation poorly made, I am in the ground I can not get out

My coordinates are: x: y -8680: 48 z: 11396

Thank you to release me (my nickname is Jumojulien)

**Comment by Jumojulien** [comment]
I'm just waiting to see when a report-is that you are available

**Comment by Jumojulien** [comment]
I'm just waiting to see when a report-is that you are available

**Comment by TrashcanMan** [comment]
If you have at least 3 soul points do /kill.
