### ISSUE TITLE
Guild Glitched

### ISSUE THREAD

**Issue by SPMan** [Wynncraft/Issues#2395]
I bought a Guild Yesterday and now I am unable to contribute xp to it, neither my members
We've tried 100%,50,10,5... nothing works, we only got 965 from a quest yet, but other than that, we don't get any Guild XP
Guild name: Tsardom of Wynn
Guild tag: Taw

**Comment by TrashcanMan** [comment]
Guild XP has been broken for a while, all you can do is wait until it's fixed.

**Comment by SPMan** [comment]
Thx for info, so I guess it's wise to just leave guild xp at 0 atm

**Comment by Chewsterchew** [comment]
If we've solved your problem, it would be helpful to close this issue, you can always re-open it later.

**Comment by TrashcanMan** [comment]
Found the old one, it's #2074
