### ISSUE TITLE
the Bugged Sealed letter 

### ISSUE THREAD

**Issue by mcmac223** [Wynncraft/Issues#2397]
Lol i got this sealed letter 
![2015-10-15_18 21 27](https://cloud.githubusercontent.com/assets/14993263/10520312/d7a951aa-7369-11e5-9fab-2b60ce77cd12.png)
what number is this?

**Comment by Chewsterchew** [comment]
Its 1-9 if that narrows it down

**Comment by ThunderRemix** [comment]
This is sealed letter nine. Please close this issue if nothing is wrong. You should ask the forums for general questions like this.
