### ISSUE TITLE
start box bug

### ISSUE THREAD

**Issue by eggy551** [Wynncraft/Issues#2400]
Hello,
after selecting my dark mage I´m sporning in the start box please help me.
Username is eggy551

**Comment by eggy551** [comment]
ok I´ve been tryed and you only need to do /kill

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
