### ISSUE TITLE
Server bugged then took my weapon

### ISSUE THREAD

**Issue by Shadowzombie115** [Wynncraft/Issues#2401]
I logged into Wynncraft this morning an died, then when i logged back in later after the servers were fixed I didnt have my max id'ed infinity bow with sharpness 2 on it anymore. it was just gone.  this whole "no refund" policy is crap because its YOUR servers fault for losing my inventory and taking my bow i worked so hard for. if i seem annoyed in this post its because i have already been told by so many people to "suck it up and get over it." when it was not my fault at all my bow was taken.

**Comment by Trixter313** [comment]
If that's the only item that's missing you most likely accidentally dropped it which people do all the time. I recommend changing the drop item key to something less likely to be accidentally pushed to lessen the chances of accidentally dropping any more items.

**Comment by Shadowzombie115** [comment]
i have the drop key disabled

**Comment by Moe-Ronickah** [comment]
Shadowzombie, I lost a Mythic weapon due to a permissions error.  It will not be refunded, so, I know how you feel, but take it easy.  There is a thread on the forums, in suggestions, about Item Locks.  Please take a look at it.
