### ISSUE TITLE
My friend is banned for no reason

### ISSUE THREAD

**Issue by SteveClinton** [Wynncraft/Issues#2402]
Help my friend. He is banned because of a bug. When he try to log in he only can read ,,Reason: vanilla server,, He told me that he only wanted to swich the lobbys and then he get banned. His name: Miribu. Sorry for my english vocabulary/grammar im german. Please unban my friend. Thanks.

**Comment by Trixter313** [comment]
Nan appeals belong here https://forums.wynncraft.com/forums/ban-appeals.84/

It would be helpful if you'd close this issue to keep the bug tracker uncluttered. Thanks!
