### ISSUE TITLE
Vanishing LE bs

### ISSUE THREAD

**Issue by FelixLive44** [Wynncraft/Issues#2403]
Hi, yesterday I traded  64 EB for my second LE and today i found out it vanished!!?? I dsconnected and reconnected and evrything and it didn't come back. I didn't ver used it and I think it gliched out when i did the trade so i saw it tho it took my EB and didn't give me the LE. (Since the server reseted right after)

**Comment by Moe-Ronickah** [comment]
If you were attempting to trade the EB for an Le during a countdown to reset, then you were taking a big risk at having your inventory glitch.  That is a risky time to do anything.  As to the loss of your LE, there is a strict no refunds policy on the server.  I'm sorry, but your LE is gone.
