### ISSUE TITLE
Archer class stuck in spawn

### ISSUE THREAD

**Issue by DogeOnMirage** [Wynncraft/Issues#2404]
My archer class is stuck in spawn at lvl 20 and whenever I talk to the caravan driver he says nothing. I really want my archer class out and I have tried /kill and everything. It would be nice to get it out because it is my 2nd favorite class.

**Comment by TrashcanMan** [comment]
Just go to the teleport spot at the end of the path (it's the stone wall after the lake bit) and you should teleport into Ragni.

**Comment by DogeOnMirage** [comment]
I can't get past the caravan driver thing because whenever I use the leather cap or anything I can't get past the chicken place.

**Comment by blakistone10** [comment]
My Archer is stuck in the room the walls and ceiling of obsidian floor made of black wool tried everything I can not get out help please

**Comment by Trixter313** [comment]
@DogeOnMirage are you still stuck?

@blakistone10 typing /kill should get you out.
