### ISSUE TITLE
My Legendary Chestplate is gone when I changed the server! Please give me the Item back asap!

### ISSUE THREAD

**Issue by Krallorddark** [Wynncraft/Issues#2406]
I logged in the game for grinding.. ten I see somebody else was grinding and ı changed the server.. then I started to tkae more damage So I looked to my Inventory and I saw my chestplate was gone!
I spend Most of my emeralds to Identify It! It had really good stats tho! Please give me my "Sawdust" With all the Identifiers Back ASAP!

**Comment by ThunderRemix** [comment]
Sorry, Wynncraft has a strict no-refunds policy. You will have to get another one from somewhere.

**Comment by Krallorddark** [comment]
Thunder Remix Can you at least give me 20 EB ( 1/3 Of It's Identification cost ?

**Comment by Moe-Ronickah** [comment]
Please understand, there is a strict no refunds policy.  You can ask around in Detlas to see if someone will be kind enough to help you out, however, there is no obligation from anyone to do so.

**Comment by Krallorddark** [comment]
Ok dude I found another one :(
