### ISSUE TITLE
VIP rank bug.

### ISSUE THREAD

**Issue by kirage78** [Wynncraft/Issues#2409]
Hello. My name is Wesley, IGN kirage78.
Today i bought VIP rank (25.00) on 10/19/2015 around 16:16 PM.
I waited for 10-15 minutes and i still dind't get the rank. I dont know if this is a bug but i would like it to be fixed. If it can't be fixed, Then i want my money back.

Tranfser the money on PAYPAL. wesleyguijt123@hotmail.com

**Comment by HetIsKylian** [comment]
I have the same problem I think just waiting to when they fixed it

**Comment by kirage78** [comment]
Hmm, Yes i quess you're right
