### ISSUE TITLE
Can't Start A War

### ISSUE THREAD

**Issue by DuskZeDragon** [Wynncraft/Issues#2412]
Starting A War Is Pointless in our guild " Adventurous" We Would Always Join And Nothing Would Happen. it Would Say No-one joined in but we were all in the area. we were even less than 5 blocks away from the war starter.
![2015-10-19_17 02 08](https://cloud.githubusercontent.com/assets/15203733/10592697/908936d0-7672-11e5-9cfb-17ec21c90b66.png)

**Comment by TrashcanMan** [comment]
Guilds are kind of broken right now. Sometimes attack/defend doesn't work properly, and sometimes /guild XP doesn't actually give your guild XP.
