### ISSUE TITLE
Animal dungeon boss fight

### ISSUE THREAD

**Issue by gwylkill** [Wynncraft/Issues#2415]
the lava cow kept respawning

i made a video but i cant post it

**Comment by Chewsterchew** [comment]
You didn't go through the black wool portal?

**Comment by gwylkill** [comment]
Yes I did it was the lava cow that kept respawning.?

**Comment by drag0nr1der** [comment]
it was happening to me to

**Comment by Trixter313** [comment]
You have to make sure the cow isn't too far away from the center of the arena or it won't register that you killed it.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
