### ISSUE TITLE
Unable to login?

### ISSUE THREAD

**Issue by Kethkel** [Wynncraft/Issues#2417]
Hello, i don't know what's happened but i can't enter in the game after i crashed yesterday.. After the maintenance.
I got this 2 error :

Exception Connecting:ReadTimeoutException : null
Or this:
You Are already logged in! Try again in a few seconds.

Bye, hope it can help to fir this problem.

**Comment by Ambertje** [comment]
Yeah i know already made a bug on it to go look at it it explains everything
