### ISSUE TITLE
I can't click baby villagers to talk with them for quests.

### ISSUE THREAD

**Issue by Fr0sto** [Wynncraft/Issues#2420]
Probably a hitbox bug, but I can't seem to talk with any of the baby villagers. Please fix?

**Comment by Chewsterchew** [comment]
Press F3+B to see its hitbox, and click inside the white rectangle, it that still doesn't work, click around the villager. Hope this helps!

**Comment by Trixter313** [comment]
Usually standing right in the villager and looking down is the best way to click on them.
