### ISSUE TITLE
Invisible Armour

### ISSUE THREAD

**Issue by EthanGatch** [Wynncraft/Issues#2423]
Whenever I play wynncraft my armour doesn't show up. In the inventory they are fine (It looks like a normal piece of armour) but when I put them in the armour slot it shows up as a slime ball and doesn't show up on my appearance and doesn't give me any armour points. Not sure if this is supposed to happen plz help?

![2015-10-21_16 46 11](https://cloud.githubusercontent.com/assets/15228126/10631797/d72d07a0-7812-11e5-9c66-0d1f22d3da6d.png)
![2015-10-21_16 46 25](https://cloud.githubusercontent.com/assets/15228126/10631798/d736be76-7812-11e5-8609-deebfc4da0e6.png)
![2015-10-21_16 46 35](https://cloud.githubusercontent.com/assets/15228126/10631799/d758ab08-7812-11e5-82f9-bdcec554902d.png)

**Comment by Chewsterchew** [comment]
This is intentional, all armour is supposed to change your skin.

**Comment by TheIronArrow** [comment]
The same thing keeps happening to me!

**Comment by TheIronArrow** [comment]
Chewsterchew, it is supposed to change your skin, but it didn't change his and it doesn't change mine.

**Comment by EthanGatch** [comment]
Some times it works for a bit but then it stops again.

**Comment by brainscript** [comment]
@EthanGatch I think the rendering system can't find the armour textures. (Check [WynnSkin1-30](https://de.namemc.com/s?WynnSkin1))
A week before I've got normal vanilla armour.

*Maybe this has something to do with the upcoming Gavel update. Coming this fall ...*

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
