### ISSUE TITLE
Cant join any servers already in one?

### ISSUE THREAD

**Issue by Ambertje** [Wynncraft/Issues#2425]
All the people who where in server 5 at a certain moment cant join any servers atm. This is because we are apperently still in server 5. I think there has been a glitch in server 5 that caused it dont know what. I do know how to solve this problem and that is to manualy restart server 5. Then when it is restarted everybody who was glitched in server 5 isnt in it anymore then and should be free to join whatever server they want again. Now we cant join any server anymore because we are already in one and now we cant play the game. Please restart server 5 :)

**Comment by SuperSeanRPG** [comment]
PLEASE!!!

**Comment by SoloSnuggles** [comment]
^ ^ ^

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
