### ISSUE TITLE
Mages Can Break Flower Pots

### ISSUE THREAD

**Issue by drag0nr1der** [Wynncraft/Issues#2427]

**Comment by drag0nr1der** [comment]
If you hit the flower in the pot the entire thing breaks.

**Comment by SuperSeanRPG** [comment]
its not a bug thats natural

**Comment by TrashcanMan** [comment]
The flower pots are supposed to be breakable, and occasionally drop emeralds. However at some point this stopped working properly so you can't break them unless you hit them the right way.
