### ISSUE TITLE
guild will not create

### ISSUE THREAD

**Issue by Wghardy** [Wynncraft/Issues#2428]
i had 5 le and i had 7 soul points and i'm level 44 and i tried to make a guild and it took 5 le plus the 5 soul points and it did not give me the guild can somebody fix this

**Comment by Trixter313** [comment]
This usually resolves itself with a little time. Wait a few hours to a day and chances are the guild will be created.

**Comment by Wghardy** [comment]
Thx

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
