### ISSUE TITLE
Flashing sky...

### ISSUE THREAD

**Issue by MattHei1** [Wynncraft/Issues#2432]
I was on the way to Neesak and i saw this: the sky was flashing from day to night on and on.
Plz fix this.
Btw dont post comments of f.ex This is a copy of bla bla bla...

**Comment by MattHei1** [comment]
This happend also when i logged in a nother world

**Comment by arneturuc** [comment]
This may happen when you are in the area around the Nether Portal, when the transition between the biomes happens.
Since said biomes don't have a sudden border the sky colour changes a lot at certain points.
Is that what you meant?

**Comment by MattHei1** [comment]
Yes arnecturuc

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
