### ISSUE TITLE
Hole in the map

### ISSUE THREAD

**Issue by 63502** [Wynncraft/Issues#2433]
There is a hole in the map at X -83 Y 61 Z -456.
It is a cave that is obviously not a part of the map and is inescapable for any single player alone in any class except archer. Only tp scrolls and the /kill command can be used to escape.
![2015-10-23_12 21 09](https://cloud.githubusercontent.com/assets/15267053/10698748/a85ffba2-7980-11e5-8335-1bf739155008.png)

**Comment by TrashcanMan** [comment]
Is it still there when you switch worlds? Sometimes certain worlds develop corrupt chunks and stuff disappears.

**Comment by arneturuc** [comment]
I've also been to the said point.
![image](https://cloud.githubusercontent.com/assets/14214668/10871778/e11b7ff8-80f0-11e5-9116-1c3dfa08b520.png)
![image](https://cloud.githubusercontent.com/assets/14214668/10871781/f2dc5a5a-80f0-11e5-9de5-36a2561d4a32.png)
As you can see it definitely is an unintentional hole in the world.
Tested this on 3 different servers at different times.
Even though it is a not-easy-to-find spot, it should get filled up by a builder.
