### ISSUE TITLE
Guild XP not leveling us up :I

### ISSUE THREAD

**Issue by DuskZeDragon** [Wynncraft/Issues#2434]
It seems that when leveling it doesn't level us up at all. It's been around 2 days now :/. I know guilds are broken right now, i just wanted to post this to help people know what to fix! also, is there a fix for this? if there even is one.
![2015-10-23_15 19 09](https://cloud.githubusercontent.com/assets/15203733/10704052/07375bae-7989-11e5-920d-ce6d4d6130a4.png)
more proof
![2015-10-23_15 19 13](https://cloud.githubusercontent.com/assets/15203733/10704082/392000b2-7989-11e5-9095-002f50721f11.png)

**Comment by TrashcanMan** [comment]
This issue has been reported multiple times and the staff are working hard on it, just be patient.
