### ISSUE TITLE
I created a guild but it says it does not exist and i am not the owner

### ISSUE THREAD

**Issue by Payton53** [Wynncraft/Issues#2435]
![2015-10-23_14 38 56](https://cloud.githubusercontent.com/assets/15236159/10704546/c5907bca-7994-11e5-827b-f32111868f80.png)

**Comment by Trixter313** [comment]
This issue usually resolves itself with time, is everything ok now?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Payton53** [comment]
yes thank you i have a guild now and am able to add members

**Comment by brainscript** [comment]
@Payton53 Please close the issue when your problem is solved.
