### ISSUE TITLE
im in the middle of the map, in the floor pls help me

### ISSUE THREAD

**Issue by MitoKai** [Wynncraft/Issues#2436]
I was trying to  enter in the  animal boss room and when I get out of my horse I get in there I dont know how. pls can any adm or mod tp me back to other place

**Comment by TrashcanMan** [comment]
If you're stuck and have at least 3 soul points do /kill.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
