### ISSUE TITLE
Lobby Glitch

### ISSUE THREAD

**Issue by ZeroplaysMC** [Wynncraft/Issues#2437]
Whenever my friend trys to join a lobby,it doesnt work

**Comment by Trixter313** [comment]
If your friend still having this issue? If so, could you give any more details such as an error message or screenshot? Thanks!

**Comment by ZeroplaysMC** [comment]
Well,it happens sometimes and then works an hour later,I will post a video
to you once it happens again.
But trust me,it really pulls your hair out.

**Comment by ZeroplaysMC** [comment]
Sometimes it even happens to me! It really stinks.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by ZeroplaysMC** [comment]
Yes,i have not experienced this glitch since,thank you!

**Comment by ZeroplaysMC** [comment]
so i am having another issue

**Comment by ZeroplaysMC** [comment]
Amerigo in Nemract just says nothing,and im on the Mercenary Quest. Plz fix
this!

**Comment by Trixter313** [comment]
If you have a new, different issue, please make sure there isn't already a thread for it, and if there isn't, create a new one. Thanks!
