### ISSUE TITLE
Can't convert my LE

### ISSUE THREAD

**Issue by StormD4** [Wynncraft/Issues#2438]
So today I went to Selchar to convert my old Emeralds, the Emerald blocks worked fine. The Liquid Emerald, not so much.
![screen shot 2015-10-23 at 9 47 12 pm](https://cloud.githubusercontent.com/assets/15273330/10708508/8ecb781a-79d0-11e5-8a0b-aa85bc02ba92.png)
![screen shot 2015-10-23 at 9 54 47 pm](https://cloud.githubusercontent.com/assets/15273330/10708511/be5d7038-79d0-11e5-8510-19ca8627e53b.png)

**Comment by TrashcanMan** [comment]
You could always try switching back to 1.7 and then trading them.
