### ISSUE TITLE
Frost Bitten Quest Glitched for me

### ISSUE THREAD

**Issue by Goatswag0723** [Wynncraft/Issues#2440]
Problem : i can't complete this quest for some reason. i'm being prompted to do something i've already done and i cannot go back and complete it again.

and the explosive isn't in my inventory.

i started the quest earlier and i had already gotten the explosive and it didn't work and he wanted me to get lava or a bucket, whichever it is as i haven't done that part yet. once i had given him the explosive i logged off for awhile to do something else around the house. i logged back on and i checked my quest book and it said to give him the explosive, but i had already done that?

It isn't in my inventory or bank or 
![screenshot 335](https://cloud.githubusercontent.com/assets/15275824/10709923/cf5ef61c-7a0d-11e5-8032-fa7439bc1819.png)
![screenshot 331](https://cloud.githubusercontent.com/assets/15275824/10709891/c878a5c4-7a0c-11e5-8a23-50b8cdaa7af0.png)
![screenshot 332](https://cloud.githubusercontent.com/assets/15275824/10709894/d13713e4-7a0c-11e5-9fee-76dd25b39675.png)
I figured i'd just go back and get another explosive but when i went back to the npc it just gave me a blank message.
![screenshot 333](https://cloud.githubusercontent.com/assets/15275824/10709895/d927dd54-7a0c-11e5-8d97-dc95f43533cc.png)
then i just tried to see if i could skip the explosive part, however far fetched that might be and the npc's had no interaction with me before as you can see.
![screenshot 334](https://cloud.githubusercontent.com/assets/15275824/10709896/d935b898-7a0c-11e5-95a1-346176d02bba.png)

**Comment by TrashcanMan** [comment]
Try /fixquests.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
