### ISSUE TITLE
hub bug

### ISSUE THREAD

**Issue by xinzhong4321** [Wynncraft/Issues#2441]
i choosed my kit (archer) than i spawned in the kit menu room pls help me

**Comment by silverlego** [comment]
same happened to me, accept my assassin got bugged instead

**Comment by xinzhong4321** [comment]
silverlego i know what we can do. make /kill than you on the village where you were at last but you lost one soulpoint

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
