### ISSUE TITLE
I'm stuck??

### ISSUE THREAD

**Issue by Bunneywabbit** [Wynncraft/Issues#2442]
I've been in the emerald trail sewers before, and the waterfall exit was always there.  I went today and there was only water and now I'm trapped??? Please help!!!

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
