### ISSUE TITLE
I'm stuck??

### ISSUE THREAD

**Issue by Bunneywabbit** [Wynncraft/Issues#2443]
I've been in the emerald trail sewers before, and the waterfall exit was always there.  I went today and there was only water and now I'm trapped??? Please help!!!
![image](https://cloud.githubusercontent.com/assets/15280909/10711887/7b0bfd40-7a57-11e5-997d-d5f251907853.png)

**Comment by TrashcanMan** [comment]
The sewer thing is broken at the moment, it should be fixed soon. /kill if you have at least 3 soul points and you should get out. Also for future reference try not to post the same issue twice (#2442)

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
