### ISSUE TITLE
Im stuck

### ISSUE THREAD

**Issue by booomx9** [Wynncraft/Issues#2444]
So i was exploring the map and i somehow got into a cave where i shouldnt go... basically i got stuck.
https://gyazo.com/bb9f47eae06a44cfd8afd5ca797f4931
https://gyazo.com/69a7f5dbe9c0274fea1847f820d16512
Please, can someone tp me somewhere... where i won't get stuck?
My ingame nickname - boomx9.

**Comment by TrashcanMan** [comment]
/kill if you have at least 3 soul points.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
