### ISSUE TITLE
I can´t join...

### ISSUE THREAD

**Issue by MattHei1** [Wynncraft/Issues#2445]
Gavel confirmed?
It says Disconnected even if it is 40ms...
And i can join other servers really easy...

**Comment by Jamesym100** [comment]
Same here, I was looking for a fix but this works too... just wish I could play at the moment...

**Comment by SuperSeanRPG** [comment]
ikr

**Comment by Fr0sto** [comment]
same.. really ticking me off

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Jamesym100** [comment]
its now not happening constantly but it does happen often still... could
you investigate this please?

**Comment by Trixter313** [comment]
I personally can't investigate further but if you leave the issue open a staff member should see it soon and hopefully be able to help. =)
