### ISSUE TITLE
Could someone give me a bit of help?

### ISSUE THREAD

**Issue by juicebox182** [Wynncraft/Issues#2447]
I can't seem to connect to the server, I can connect to other servers fine but with Wynncraft it seems to just keep trying to connect and eventually just says 'disconnected'. It may have something to do with the wifi i am currently connected to, I am trying to connect from a house I have never played Wynncraft from do you think that may have something to do with it? I need my quest'y fix man!

**Comment by Trixter313** [comment]
Are you still having this issue?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
