### ISSUE TITLE
Can't enter Wynncaraft

### ISSUE THREAD

**Issue by thrillking** [Wynncraft/Issues#2448]
Once I get to the hub aria I try to use the portals to enter the game but when I select a server nothing happens 
![image](https://cloud.githubusercontent.com/assets/15309770/10715697/d8cc916c-7adc-11e5-9608-77cb3d9180f6.jpg)

**Comment by Trixter313** [comment]
Are you still having this issue?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
