### ISSUE TITLE
Why I cant enter Wynncraft

### ISSUE THREAD

**Issue by acehate12** [Wynncraft/Issues#2449]
i try to enter but it show like this
![image](https://cloud.githubusercontent.com/assets/10232276/10715931/f6a4bd72-7b59-11e5-9e9b-ec3e900d09df.png)

**Comment by Fr0sto** [comment]
Same problem fix asap

**Comment by iLikeGamesYT** [comment]
I have the same problem and I've been trying to get on all day.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
