### ISSUE TITLE
Unable to connect for hours

### ISSUE THREAD

**Issue by wizardcheetah55** [Wynncraft/Issues#2450]
![image](https://cloud.githubusercontent.com/assets/11051478/10716175/76c42442-7aed-11e5-8f2a-3bd7eaf7785c.png)
Any timetable as to when this will be fixed? It's been this same message for me since 9 PM Saturday.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by wizardcheetah55** [comment]
Happy to close it . . . how?

Stan Emert
206-250-9839
Skype: stan.emert

**Comment by Trixter313** [comment]
When you comment from the website it should say comment and close next to the regular comment button.
