### ISSUE TITLE
- Quest - Wynnexcavation C -

### ISSUE THREAD

**Issue by Wroxel** [Wynncraft/Issues#2451]
How do i delete this Text?

**Comment by Wroxel** [comment]
![2015-10-25_17 30 42](https://cloud.githubusercontent.com/assets/15311463/10716593/4da44ac8-7b3e-11e5-8d89-2ba1e2037b2e.png)
![2015-10-25_17 30 48](https://cloud.githubusercontent.com/assets/15311463/10716594/526b504c-7b3e-11e5-9469-c73e4e249c81.png)
![2015-10-25_17 31 09](https://cloud.githubusercontent.com/assets/15311463/10716595/548bf688-7b3e-11e5-82e9-38ad278559a8.png)
![2015-10-25_17 31 24](https://cloud.githubusercontent.com/assets/15311463/10716596/55e82920-7b3e-11e5-9dc8-aaf33334f8c5.png)

**Comment by TrashcanMan** [comment]
If you want to close the issue there should be a button along the lines of "Comment and Close" next to the "Comment" button.
