### ISSUE TITLE
The guild master has taken my LE without created my guild !

### ISSUE THREAD

**Issue by Endersim07** [Wynncraft/Issues#2454]
So, I've come to the guild master with my 5LE and 11 soul points, then, I've talked to him and he had begun to ask me about my choices for my guild, nothing bad, I had to change many things because it was already taken. After that, he asked me if I was agree for the name, for the prefix, I said "yes", and then he said "Hey! You don't have 5 liquid emeralds!" !!! So with my friend we searched them 1 or 2 minutes but NO-THING !! Please help me, my player nickname is EnderSim07 and I really need them ! Thank you . 
PS: Sorry for english errors ,I'm french xD
![2015-10-26_15 28 54](https://cloud.githubusercontent.com/assets/15326233/10734544/196cecbc-7c04-11e5-9bf0-e15086634ac6.png)

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by SkySaito** [comment]
Désolé, mais actuellement les guildes sont bugguer. De plus WynnCraft a une politique d'aucun remboursement ingame. Tu va devoir refarmer ces 5 LE :/
