### ISSUE TITLE
Im stuck in a hole and I cant escape.

### ISSUE THREAD

**Issue by Jayrome23** [Wynncraft/Issues#2455]
I am at the Nemract bank, after I just finished the underwater quest, I take off the respiration 3 quest item, and then it glitched. I have a full inventory, I take the helmet off my player, and the hat disappears. I can't find it, so I disconnect, and when I spawn back in, I'm stuck in a gray wool box, and can't escape. If anyone you guys see this., please get me out of the jail cell, and get back the hat that I need for later quests. Thanks! My IGN is Jayrome!

**Comment by TrashcanMan** [comment]
/kill if you have at least 3 soul points.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
