### ISSUE TITLE
Stuck in dark box.

### ISSUE THREAD

**Issue by alice3774** [Wynncraft/Issues#2457]
I tried logging in and when I selected my class (mage) I was not teleported into the main map. I understand that this is a storing area of sorts for the player to wait in as they select their class. This is extremely frustrating for me because I can't use the teleportation scrolls I have on my person and I can't move.

screenshots:
http://imgur.com/a/0yVYV

**Comment by alice3774** [comment]
nevermind. i looked into the other reports and i did /kill. it worked.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
