### ISSUE TITLE
Ocean Dungeon Glitched

### ISSUE THREAD

**Issue by Fr0sto** [Wynncraft/Issues#2458]
I have been doing the Ocean Mini-Dungeon, and at the puzzle room it stops working. I always set up the blocks exactly right, and then when I click the Start button again to open the door, the door doesn't open and the puzzle just resets.

**Comment by TrashcanMan** [comment]
The puzzle is known to be a little broken, I suggest you change servers and try again.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
