### ISSUE TITLE
I'm lost my black horse

### ISSUE THREAD

**Issue by DominikGamer** [Wynncraft/Issues#2459]
The black horse disappeared !!!!!! Please return because of some bug got on the server to restart it, burrow back by the time I joined another server I did not have a saddle. What was another black horse , was 11 Liquidfield Emerald . :(

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strict no refund policy and can't do much about this. As a general rule to follow, don't do or use anything important when close to a server restart and if you see it's going to restart soon, it may be good to type /hub and go to a different server before the time runs out.
