### ISSUE TITLE
Snow Bear (Boss in Tower of Ascension lvl 40-50) isn't dropping anything.

### ISSUE THREAD

**Issue by Nyannikins** [Wynncraft/Issues#2460]
I've tried to hit it directly instead of firing special attacks from afar. I've have already killed it multiple times, even with another player joining in later but it still doesn't drop its token. I can't progress without it, please help! Would be preferred if someone could notify me once it's been fixed.

Thank you very much ^_^

(Also I'm not sure if this is deliberate but the boss spawns again almost immediately after death. Is it possible to change that to be a bit later? A lot of players accidentally die searching for any tokens)...

**Comment by eldarkolinko** [comment]
I did loot it like 5 days ago so you are the unluckiest person in the world.
It respawns immediatly after his death because you take too long to kill him, so the game waits for you to kill him to spawn another one.

**Comment by Nyannikins** [comment]
Oh... thank you! I thought people forgot about this thread lol.
