### ISSUE TITLE
I Bugging in a Wall ...

### ISSUE THREAD

**Issue by mikeymm64** [Wynncraft/Issues#2461]
I Bugging in a wall and I can not teleport back
... This is very bad because I iwill play ... Can are teleport me off somehow because I can continue playing ^^ have a Warior where it did not happen ... : D my cordienates is 
X -507 Y 65 Z -1546

Please Help me Thanks ^^

**Comment by TrashcanMan** [comment]
If you have at least three soul points do /kill.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
