### ISSUE TITLE
Major Guild Bug Causing Server Crash For Everyone

### ISSUE THREAD

**Issue by KraZeCrafter** [Wynncraft/Issues#2462]
Hello, i bought a guild the other day on a laggy server. Called Kappini, but it gitched and got removed. Then i used another 5LE so in total 10LE. The tag is iNi. But when i invite someone to the guild, kick someone, like any command at all the whole server crashes. Servers has been crashing like 10 times this day and i didnt realise it was because of me but it is. I don't want to harm the servers but i need to manage my guild.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
