### ISSUE TITLE
Stuck in a wall.

### ISSUE THREAD

**Issue by ITheWolfyzI** [Wynncraft/Issues#2463]
Since ive been not online for a little period, i thought "lets play wynncraft again" i have chosen archer, and with that im stuck at the coords: X -10040 Y 49 Z -10472.
Would be great if any1 helps me out :D

**Comment by ITheWolfyzI** [comment]
Fixed.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
