### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by SteveClinton** [Wynncraft/Issues#2466]
my friend is still banned because of a stupid bug. He cant join any worlds. He only can read: Reason Vanilla-server...  pls help him. His name: Miribu

**Comment by AckroWynn** [comment]
Hello there!

This actually was not a bug, but a ban for the reason of remaining in a vanilla server.
Please tell him to make a ban appeal on forums.wynncraft.com

**Comment by Fr0sto** [comment]
Ackro could you explain that a little more?

**Comment by SteveClinton** [comment]
Just help me me please -.-. Its important for me and him

**Comment by Trixter313** [comment]
Did you make a ban appeal at https://forums.wynncraft.com/forums/ban-appeals.84/create-thread like AckroWynn suggested? That's the best way to get this issue resolved.
