### ISSUE TITLE
Bobs Mythic Wand

### ISSUE THREAD

**Issue by Assassine2000** [Wynncraft/Issues#2467]
I accidently dropped my Mythical Wand(Ful ID) and it disappeared after a second! please return it, it doesnt matter if ist a clean or identified wand, but i Need it!

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strict no refund policy and Wynncraft isn't accountable if a player drops their own item. To prevent this from happening to any other item, I suggest changing your drop key to something you are less likely to accidentally press.
