### ISSUE TITLE
fly bug

### ISSUE THREAD

**Issue by Lodsafg** [Wynncraft/Issues#2469]
i was walking with a friend and killing mobs.
and then i was teleported high in the sky, and the it says you have been banned for flying

**Comment by TrashcanMan** [comment]
You can go submit a ban appeal here: https://forums.wynncraft.com/forums/ban-appeals.84/
Make sure you read this first though: https://forums.wynncraft.com/threads/%E2%9C%8E-appeal-submission-guide-%E2%9C%8E.89247/
