### ISSUE TITLE
[Mission] Kill 16 Charons in 3 minutes

### ISSUE THREAD

**Issue by brainscript** [Wynncraft/Issues#2470]
![2015-10-30_15 48 16](https://cloud.githubusercontent.com/assets/8706734/10848781/d62b3fae-7f1d-11e5-9847-945bf4b202ec.png)
Is that a joke? Charon is the **BOSS** of the Zombie Dungeon and killing him 16 times in three minutes is impossible just because of the way you need to run from the dungeon entrance.

**And that for 14 Xp?!!** *Not really ...* :smile:

**Comment by TrashcanMan** [comment]
This isn't really a bug, it's just an unfortunate coincidence. Since missions are always for killing nearby mobs, if you're near a boss, you get to kill bosses.

**Comment by brainscript** [comment]
@TrashcanMan But for **14 Xp**?!

**Comment by TrashcanMan** [comment]
I believe the XP amount is randomly generated, something like this was bound to happen eventually.

**Comment by PieKing1215** [comment]
Wow, as I see this I get a mission to kill 24 Sand-Witches-
![kill 24 sand witches](https://cloud.githubusercontent.com/assets/13819558/11454859/2b83d686-960d-11e5-9629-8cb6024c5c34.png)
![kill 24 sand witches 2](https://cloud.githubusercontent.com/assets/13819558/11454860/2b849026-960d-11e5-9932-c0e618613142.png)

(BTW amazing grammar on their part with 'Sand-Witchs')

**Comment by brainscript** [comment]
@PieKing1215 7694 xp, that's much. *But you can't get it. :cry:*
