### ISSUE TITLE
[Glitched identifiication] Relic dagger's can't be identified

### ISSUE THREAD

**Issue by Plobby** [Wynncraft/Issues#2471]
As the title would suggest, I am unable to identify my set of Relic Daggers. I have confirmed this by getting a few of my friends to check and they are unable to identify the daggers aswell, despite the fact it is Legendary and Untradeable. We have also tried every other relic weapon, all of which can be identified perfectly fine. 

Message when trying to identify:
"Item Identifier: I'm afraid I can't identify this item! Only weapons and armours with a unique, rare, legendary and special tags can be identified."

Hopefully this gets fixed so I can identify and properly use my relic daggers, since they have the best damage compared to any of my other weapons and took some annoyance to obtain!

Thanks, plobnob.

**Comment by TrashcanMan** [comment]
Known issue, #1312. We advise you to close this issue and follow the original for updates.
