### ISSUE TITLE
lost my chestnut horse

### ISSUE THREAD

**Issue by sirGavino** [Wynncraft/Issues#2472]
I was doing a quest and the server started to lag when i opened my inventory and i dropped my chestnut horse and the server timed out.

**Comment by KraZeCrafter** [comment]
I don't think wynncraft is responsable for lost items, even due server crashes.

**Comment by skillerfox3** [comment]
I lost my pumpkin the times that server restarts where not announced that good. No refunds.

**Comment by Trixter313** [comment]
Yep, there's a strict no refund policy. We'd appreciate it if you closed this issue. Thanks!
