### ISSUE TITLE
stuck in a black box

### ISSUE THREAD

**Issue by MrFishbudder** [Wynncraft/Issues#2473]
help im stuck in a black box when i use archer
![2015-10-31_08 25 44](https://cloud.githubusercontent.com/assets/15490873/10860852/6a6aa196-7faa-11e5-829c-5dd989da0895.png)
![2015-10-31_08 25 56](https://cloud.githubusercontent.com/assets/15490873/10860853/6be5d1b2-7faa-11e5-9b8c-06a627b3c4b4.png)

**Comment by MrFishbudder** [comment]
never mind i looked at the other isseue

**Comment by brainscript** [comment]
@MrFishbudder This is the room where you can select your class.
Did you try `/toggle autojoin` or `/kill`?

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by MagicCreeper771** [comment]
this is happening to me too how do i fix

**Comment by Trixter313** [comment]
@MagicCreeper771 just type /kill with 3+ soul points, as @brainscript said
previously.
