### ISSUE TITLE
Guild creation glitch

### ISSUE THREAD

**Issue by Fr0sto** [Wynncraft/Issues#2474]
My friend henifataffle was creating a guild (we were on skype), he named it and gave the prefix and it should have worked, but no guild is there now. It was named "The Doctors", with prefix TED, he confirmed and the 5LE and 3SP was taken. He couldn't add people (i.e. me) to the guild because "ted is not a real guild". Please either refund us or fix the guild.

![e023975cd74beb529cb13fe88bb5972e49c46950b325f648aapimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/15222806/10861483/1ef3f4d6-7f57-11e5-94d7-c14d634bb8fb.jpg)

p.s. we apologize for poor image quality :)

**Comment by Brynnz** [comment]
Same thing Happen to me took my Le and soul points
I made the guild but it said I had made the guild.
but no guild ?

**Comment by Dweller2000** [comment]
happened to me to this sucks...
![2015-10-31_13 55 46](https://cloud.githubusercontent.com/assets/15141727/10863692/82241bf0-7fd7-11e5-8aa9-01650032d3ec.png)

**Comment by Dweller2000** [comment]
^^^ i got the guild now YAY

**Comment by Trixter313** [comment]
Guilds usually just take a little time to fully register with the server, as you've already found out =)
