### ISSUE TITLE
Major Server Crash Bug That I Can Cause

### ISSUE THREAD

**Issue by KraZeCrafter** [Wynncraft/Issues#2477]
Hello, i bought a guild the other day on a laggy server. Called Kappini, but it gitched and got removed. Then i used another 5LE so in total 10LE. The tag is iNi. But when i invite someone to the guild, kick someone, like any command at all the whole server crashes. Servers has been crashing like 10 times this day and i didnt realise it was because of me but it is. I don't want to harm the servers but i need to manage my guild.

**Comment by TrashcanMan** [comment]
Have you tried switching servers, restarting Minecraft, waiting a few hours, etc? That might help.

**Comment by KraZeCrafter** [comment]
Yes, i tried everything possible but its not client sided but its server
sided

Op zondag 1 november 2015 heeft TrashcanMan <notifications@github.com> het
volgende geschreven:
