### ISSUE TITLE
VIP+ In-Game But not on forums

### ISSUE THREAD

**Issue by KraZeCrafter** [Wynncraft/Issues#2478]
Title says it all..

Ign: KraZe
Forum Name: FlashKraZe

**Comment by Maxecito** [comment]
There is the /forums command ingame, it is currently broken tho I think.

**Comment by BateauSD** [comment]
./forum command broken

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by KraZeCrafter** [comment]
If your minimodding i cant for a few days, if "we" is the staff team you
can do it for me

Op dinsdag 22 december 2015 heeft Nick Cipriani <notifications@github.com>
het volgende geschreven:

**Comment by Trixter313** [comment]
Unfortunately I'm not staff so I can't do anything to help besides suggest fixes. Hopefully they fix the /forum command soon!
