### ISSUE TITLE
Glitching in front of the Temple of Legends

### ISSUE THREAD

**Issue by Nepherex** [Wynncraft/Issues#2480]
I was on top of the Temple and jumped off and thought that I would just teleport back to where I was, but instead i teleported to the middle of my jump. Now I am in an infinite loop of fall and teleport. Every time I touch the ground I teleport back to where I was in mid-jump.

**Comment by BateauSD** [comment]
./kill

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
