### ISSUE TITLE
QUEST BUG PLZ LOOK AT D:

### ISSUE THREAD

**Issue by Bloodyhandshake** [Wynncraft/Issues#2483]
I was farming in herb cave when I was going to pick up an item.  I pressed E and accidentally clicked my [corrupted potato] quest item and it disappeared.  I did /fixquests and it gave me 2 purple crystals (something that I didn't need because I had 1 already.  I did /fixquests 32 more times and I had an inventory full of purple crystals! what should I do? D:  ALSO:the corrupted potato isn't in my bank and any of my other classes.  It happened to my lvl 60 archer class.  Also, my inventory was full

IGN (if u need it) : Bloodyhandshake

**Comment by Bloodyhandshake** [comment]
Plz help me D:

**Comment by eldarkolinko** [comment]
The admins or mods doesn't seem to care about the forum, that's why you should wait until Gavel. 
Maybe they are too busy right now but they can help you after the update :) .

**Comment by TrashcanMan** [comment]
You could get the Corrupted Potato on another class and use it for your archer, then wait until /fixquests is fixed to get your original potato back.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
