### ISSUE TITLE
VIP+ Forum Problem

### ISSUE THREAD

**Issue by BateauSD** [Wynncraft/Issues#2484]
Command /forum doesn't work. Plz fix it.
IGN Aters
Forum: https://forums.wynncraft.com/members/ater.34391/

**Comment by TrashcanMan** [comment]
Known issue /forums is broken right now. Unfortunately, all you can do is wait for a fix.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
