### ISSUE TITLE
Item huge bug

### ISSUE THREAD

**Issue by eldarkolinko** [Wynncraft/Issues#2490]
30 minutes ago, I showed my legendary items to my friend ( show off ) but my game crashed. I showed him 6 of them, but when I came back, 4 of them dissapeared !
He took screenshots that I can show you, all the ID and powders are shown. 
Here are the items I lost : Fierte, Chained Pixels, Scorpion and Bad wolf
![bad wolf](https://cloud.githubusercontent.com/assets/14957201/11010510/992197d0-84df-11e5-9dba-fbc7b4f409f1.png)
![scythe](https://cloud.githubusercontent.com/assets/14957201/11010523/abc3697c-84df-11e5-8771-43d1aa06f3ff.png)
![chained pixels](https://cloud.githubusercontent.com/assets/14957201/11010530/bd08612e-84df-11e5-8da4-b11f6d401fc2.png)
![scorpion](https://cloud.githubusercontent.com/assets/14957201/11010533/c8bd6f6e-84df-11e5-92be-72ee934f70a9.png)
I show you my ender chest : 
![empty chest](https://cloud.githubusercontent.com/assets/14957201/11010603/4c86658a-84e0-11e5-8cf0-7aa944efe759.png)

**Comment by eldarkolinko** [comment]
My username is : eldarkolinko ( level 59 warrior )

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done. We'd appreciate it if you closed the issue. Thansk!
