### ISSUE TITLE
Stuck in block

### ISSUE THREAD

**Issue by CookieCow** [Wynncraft/Issues#2495]
I logged in after a couble of months and im stuck in grass and i cant teleport out so im just stuck listening to the music and cant get out

**Comment by DarkDemonDragon** [comment]
just do /kill and you'll be sent to the nearest town. Seems to be the only option to me.

**Comment by SeawingFire** [comment]
Or use a teleportation scroll.

**Comment by Trixter313** [comment]
If your problem is now resolved we'd appreciate it if you closed the issue. Thanks!
