### ISSUE TITLE
I fell out of the world on the boss room silverfish dungeon.

### ISSUE THREAD

**Issue by CustomCreated** [Wynncraft/Issues#2496]
I fell out of the world and it did 0 damage to me so i had to do /kill
Then i spawned at the toturial place :P.
![2015-11-07_21 22 49](https://cloud.githubusercontent.com/assets/15708246/11017142/70792246-8596-11e5-9cab-681e4ee23d81.png)

**Comment by shaharcoolmen** [comment]
i dont see a problem...

if it doesnt happen again its just a little bug..

btw i suggest next time to do /fixstart and it will teleport you to where you are in the picture for no soul cost..

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
