### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by FishieMeister** [Wynncraft/Issues#2497]
I can't connect to Wynncraft

![image](https://cloud.githubusercontent.com/assets/15709461/11017794/3e9fd11a-8579-11e5-909c-dff924c48e7b.png)
![image](https://cloud.githubusercontent.com/assets/15709461/11017795/4aa81f80-8579-11e5-9199-fbfbc394f72c.png)
![image](https://cloud.githubusercontent.com/assets/15709461/11017796/52d10bf4-8579-11e5-9a0d-cd7923d5f30b.png)

Now I know there were other ip's that you could use in place of play.wynncraft.com by replacing the "play" part of the ip with a number or random word. Those don't work either.

**Comment by skillerfox3** [comment]
I have had the same problem! The one time it did not work, the other time it did. Replacing "play.wynncraft.com" to "158.69.120.46" fixed. Now it always works for me!

**Comment by Trixter313** [comment]
Are you still experiencing these issues? If not, we'd appreciate it if you
closed this issue. Thanks!
