### ISSUE TITLE
Please help me [connection error]

### ISSUE THREAD

**Issue by minimatt36** [Wynncraft/Issues#2498]
Hello i want to play but i keep getting kicked out. I can join the sever but when i go to connect to get in the lobby it lets me pick a class then it kicks me out of the game back into the lobby and it said {there has been an error please log back in} what do i do

**Comment by TrashcanMan** [comment]
Have you tried logging off and back on, restarting Minecraft, waiting a while, etc? Usually that'll fix the problem.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by minimatt36** [comment]
Yes im still having the problem of not being able to play.

**Comment by Trixter313** [comment]
Hmm, very odd indeed... Thanks for the bug report! An admin should see this soon and hopefully will be able to help.

**Comment by minimatt36** [comment]
yes thanks up i tried msg some admins no help
