### ISSUE TITLE
Unable to join a server

### ISSUE THREAD

**Issue by ItsEnigma** [Wynncraft/Issues#2499]
I am having an issue where I join the lobby but then I am unable to join a game server, it kicks me from the server before I am able to choose a class with the message "You are already logged in! Try again in a few seconds." 
![2015-11-08_10 29 58](https://cloud.githubusercontent.com/assets/15713769/11019835/b61e0580-85c0-11e5-9dab-baf73f98376c.png)

**Comment by shaharcoolmen** [comment]
the red read time out message will happen if there is a problem with the spesific server and to fix that go to another server..

the "you are already logged in try again in a few seconds" will happen after the player tries to join a server and it kicks him out not by request reasons(will not happen when the player does "/change" or "/lobby")

to fix that just move to another location(a few blocks should update that you are not in a server anymore
and if it happens more then 5 times after you move try to disconnect and wait for20 seconds and come back...

works for me,,,,

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
