### ISSUE TITLE
Just a little bug with small missions.

### ISSUE THREAD

**Issue by Dagovrek333** [Wynncraft/Issues#2501]
It's not a really big or important bug, but I thought I'll tell it so it can be fixed..
When you get a mission, like "*Kill 20 zombies in 10 Minutes*", as soon as you have for example __3__ minutes left in the sidebar, the chat will say: "*Only  __2__ minutes left to kill 20 zombies.*"

**Comment by brainscript** [comment]
@Dagovrek333 *2 Minutes and 59 seconds* != *2 Minutes*
Yeah, this should be fixed.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by brainscript** [comment]
@Trixter313 Yeah, this is not fixed.

**Comment by Trixter313** [comment]
That's unfortunate. An admin should see this soon and hopefully will be able to help.

**Comment by brainscript** [comment]
@Tama63 Why do you close this?! It is **NOT** fixed:
![2015-12-26_11 38 53](https://cloud.githubusercontent.com/assets/8706734/12006737/511ca4d6-abe3-11e5-9ec3-28c1716bba5c.png)
