### ISSUE TITLE
Stuck in Black Box at Beginning of Class Progress

### ISSUE THREAD

**Issue by clolniraed1214** [Wynncraft/Issues#2502]
I have the same stuck in black box issue as many people, but unlike most, I had this issue the first time I tried to load the archer class. Because of this, when I type /kill, I teleport to the Ragni town center, but teleported back to the box because "[I] must talk to the king first."

PLEASE don't respond with just saying, "Just type /kill, it'll get you out". The issue goes beyond that.

MC Username: Marshmallow3000

**Comment by Trixter313** [comment]
Have you tried typing /fixstart ?

**Comment by shaharcoolmen** [comment]
happend to me before... i used a scroll to get out...

**Comment by clolniraed1214** [comment]
Well yes, that would work, but having never used the class before, I don't
have scrolls, let alone any items (besides starting ones).

**Comment by clolniraed1214** [comment]
Oh, missed the fixstart message. I'll try that now.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
