### ISSUE TITLE
Unrecognizable item (doesn't show up in skin and can't ID)

### ISSUE THREAD

**Issue by DarkDemonDragon** [Wynncraft/Issues#2503]
So I recently found a Legendary called Pelier and when I went to the Item Identifier to ID it, the NPC said it couldn't because it wasn't a special, rare, etc... However, it still works and affects my defense so I'm not too sure what's going on with it. Here are some screenshots and I used another item to show that the skin thing was working for me but just not with Pelier.
![2015-11-08_19 38 01](https://cloud.githubusercontent.com/assets/15721340/11023861/9a61f202-8651-11e5-93a0-c2121ac8b66f.png)
![2015-11-08_19 38 08](https://cloud.githubusercontent.com/assets/15721340/11023862/9a6aef6a-8651-11e5-9836-13eda19154a4.png)
![2015-11-08_19 38 14](https://cloud.githubusercontent.com/assets/15721340/11023864/9a6e4ffc-8651-11e5-901a-d664d448e9fd.png)
![2015-11-08_19 38 20](https://cloud.githubusercontent.com/assets/15721340/11023863/9a6d1772-8651-11e5-8bd4-16a76514fdcc.png)
![2015-11-08_19 38 38](https://cloud.githubusercontent.com/assets/15721340/11023866/9a6f2292-8651-11e5-9f52-4bb3e4ee2d0b.png)
![2015-11-08_19 38 48](https://cloud.githubusercontent.com/assets/15721340/11023865/9a6f18d8-8651-11e5-880d-a73b4648ceff.png)
![2015-11-08_19 38 51](https://cloud.githubusercontent.com/assets/15721340/11023867/9a6f715c-8651-11e5-9744-232da3c9fcf6.png)
![2015-11-08_19 38 57](https://cloud.githubusercontent.com/assets/15721340/11023869/9a7ad4e8-8651-11e5-842f-af93623f45f9.png)
![2015-11-08_19 39 14](https://cloud.githubusercontent.com/assets/15721340/11023870/9a7c4a6c-8651-11e5-9767-4abe3ca60c6e.png)
![2015-11-08_19 39 17](https://cloud.githubusercontent.com/assets/15721340/11023868/9a7a249e-8651-11e5-9c01-f75ca8a7903a.png)

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!

**Comment by DarkDemonDragon** [comment]
My bad Trixter313 didn't realize there was already a post on this. Just made this github account today so I'm not aware of how well-known issues are. Will close now thanks for your help!
