### ISSUE TITLE
lobby parkour at end not giving jump boost but only speed..

### ISSUE THREAD

**Issue by shaharcoolmen** [Wynncraft/Issues#2506]
JUST TO BE CLEAR IM USING A DIFFRENT WORLD THEN THE WYNNCRAFT SERVER!
WHAT IM DOING IS NOT IN WYNNCRAFT BUT IN SINGLE PLAYER WITH THE COPIED WORLD!

so i was checking out the lobby in creative in singleplayer breaking what i could :D and then i saw that at the end of the parkour it gives you speed..
![2015-11-10_17 57 37](https://cloud.githubusercontent.com/assets/7313099/11067486/6c612a28-87d5-11e5-99ad-7ec01f6b021e.png)
so i wanted to see what speed it was and then i saw that there were 2 commandblocks
one had speed(which i now found that the speed level was 20)
![2015-11-10_17 57 48](https://cloud.githubusercontent.com/assets/7313099/11067513/89a25d0a-87d5-11e5-8edb-14da88fb80d1.png)
and then i saw this:
![2015-11-10_17 57 54](https://cloud.githubusercontent.com/assets/7313099/11067534/a27948fc-87d5-11e5-965e-35d74c32450f.png)
the effect tries to give you "jump" instead of "jump_boost"
![2015-11-10_17 58 08](https://cloud.githubusercontent.com/assets/7313099/11067586/df81819c-87d5-11e5-98de-11117de3f0a1.png)
so i just fixed it in my world and it gave me the jump
![2015-11-10_17 58 12](https://cloud.githubusercontent.com/assets/7313099/11067598/f09054b8-87d5-11e5-84cd-2ea9cfe9fdb6.png)
so can you just do this little fix there please?

**Comment by ThunderRemix** [comment]
Although downloading anything wynncraft server related isn't allowed, thanks for the report.

**Comment by shaharcoolmen** [comment]
@ThunderRemix i will never upload a copied content of wynncraft and i knew that it wasnt allowed..
this world will be only opened on my PC with my minecrarft and i will never ever publish it...

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
