### ISSUE TITLE
I can't leave the choose class room!!!!

### ISSUE THREAD

**Issue by Lesko06** [Wynncraft/Issues#2507]
![2015-11-10_20 49 06](https://cloud.githubusercontent.com/assets/15789383/11073867/ec290fc0-87ec-11e5-97ad-ed23df975750.png)
![2015-11-10_20 49 16](https://cloud.githubusercontent.com/assets/15789383/11073873/f13e5664-87ec-11e5-8ebb-cfbcc36c6e5b.png)
My username is Lesko06.
(sorry for the english I am french)

**Comment by shaharcoolmen** [comment]
do /fixstart and it will teleport you to the start where you later teleport to ragni...

**Comment by TrashcanMan** [comment]
Alternatively you can do /kill with at least 3 soul points and it'll take you to the nearest city.

**Comment by shaharcoolmen** [comment]
@TrashcanMan well not in that situation..
the class selection room is located behind ragni.. so its not smart to kill yourself if you can already get there for free...

**Comment by TrashcanMan** [comment]
@shaharcoolmen I don't think /fixstart works if you're done the starter quest though

**Comment by shaharcoolmen** [comment]
@TrashcanMan 
actually fixstart makes you come back to the start no matter what have you done...
it will not reset the first quest "kings recruit" but it will still bring you there...
at  the end of the quest you will be talking to the king in ragni is you can just come to detles or something...

just so you know there is the place that its located in
![start](https://cloud.githubusercontent.com/assets/7313099/11138847/5b104b94-89d0-11e5-81e2-5555dfbe4eeb.png)
the large place on the right that is visible is where the start quest is..
behind that is the black wool selection room on the left...

**Comment by TrashcanMan** [comment]
@shaharcoolmen I know what it does but I remember somebody saying that /fixstart only works if you haven't completed King's Recruit

**Comment by shaharcoolmen** [comment]
i dont know... ill test it later....
but i remember doing it after when i was level 34....

2015-11-13 8:03 GMT+02:00 TrashcanMan <notifications@github.com>:

**Comment by SeawingFire** [comment]
This happens to me a lot but I always have teleportation scrolls.

**Comment by shaharcoolmen** [comment]
yeah me too... i always have on me something like 32 detles scrolls...

2015-11-14 15:57 GMT+02:00 SeawingFire <notifications@github.com>:

**Comment by Trixter313** [comment]
If your problem is now resolved we'd appreciate it if you closed the issue. Thanks!
