### ISSUE TITLE
Skeleton dungeon bug

### ISSUE THREAD

**Issue by Troll2828** [Wynncraft/Issues#2508]
So I was leveling up my mage by doing the skeleton dungeon. Whenever I got to the boss I just got teleported to the beginning and it said that I had completed the dungeon. That happened a couple of times but sometimes I killed the boss. I'm pretty sure there was no one with me in the dungeon. I don't know if this is a bug or I just had lag. If it's a bug I hope you guys will fix it soon.

**Comment by shaharcoolmen** [comment]
so.. you got teleported to the start and it told you you finished?
and you got the xp and used only one key and it brought you back to the start?

if this is like i think it is when someone finds a way to recreate the problem he would have basicly infinite xp for the price of 1 key,,,

**Comment by AssassinkKitten** [comment]
No you get out of the dungeon U dont go to the begining of the dungeon :package:

**Comment by shaharcoolmen** [comment]
oh....

well then....

are items dropping?
you get the done message?
and do you get xp?
if you dont get the message but you do get xp and items it must be a tiny
problem with the message.. maybe your chat options...
but if you dont get any items this is a bug that will be hard to fix as the
developers cannot recreate the bug,,
if it happens only to you in wynncraft it will be impossible for them to
fix...

2015-11-14 19:38 GMT+02:00 AssassinkKitten <notifications@github.com>:

**Comment by AssassinkKitten** [comment]
Its all normal but sometimes u "skip" the boss part

**Comment by shaharcoolmen** [comment]
well why is it a problem? :D

i would abu..  abuu...   abuuuutimbeloi.. that's a new word... keep up with
the world....
:D

2015-11-14 20:58 GMT+02:00 AssassinkKitten <notifications@github.com>:

**Comment by DarkDemonDragon** [comment]
I was grinding the skele dungeon with my assassin (lvl 13 or so at the time) and this happened on like my 3rd or 4th run.  I ran in and barely got a couple hits in and somehow the boss instantly died or something.  Similar occurances happened in a couple other different dungeons where the boss somehow died early or died without me hitting them. Considering how it happens pretty rarely and is actually helpful, just deal with it for now.

**Comment by shaharcoolmen** [comment]
OHHHH! that's what you meant! i latly been having this with zombie dungeon
boss...
but its super rare for me, and i found that it happens under some
conditions:
1.you cannot be in the agro range of the boss and also not in his agro range
2.the first hit has to be a spell that is not involved with the
player(meteor,long bow shots,someother things of that kind)
3.i find that i happens more when the server if about full(57ish+)
4.the server has to have atleast 10% lag

and it wont happen every time you meet these conditions,
you still have a really low chance of that happening.
i think rufly about 3% for this to happen...

and that's all i know about the bug...
and i dont really work towards it getting fixed and i dont really not like
it when it happens but if someone reported this i may as well give all i
know...

2015-11-18 15:35 GMT+02:00 DarkDemonDragon <notifications@github.com>:
