### ISSUE TITLE
Vip rank in game bug.

### ISSUE THREAD

**Issue by kirage78** [Wynncraft/Issues#2510]
Hello. My name is kirage78 and a few months ago i bought VIP. But for some reason i still dindt get my VIP rank. I still have the payment proof and i want my VIP ASAP. If it cant be fixed, Then i want my money back.

**Comment by TrashcanMan** [comment]
Email support@wynncraft.com and they should help you sort it out.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
