### ISSUE TITLE
"Server is in online mode!" why is that a problem...

### ISSUE THREAD

**Issue by zoltanelder** [Wynncraft/Issues#2512]
whenever I try connecting to the wynncraft server I get this. Don't know if it is intentional or not but I cant find anything on it... (I'm on a mac if that helps)
![screen shot 2015-11-12 at 11 45 04 am](https://cloud.githubusercontent.com/assets/15820255/11124418/e51e7084-8932-11e5-9c13-9acbd7235392.png)

**Comment by mozai** [comment]
Also seeing this, Linux, JRE 1.8.  

    Conection Lost
    Exception Connecting:RuntimeException : Server is onilne mode! @  
    net.md_5.bungee.Serverconnector:261

**Comment by xXAdamXx** [comment]
Usually when someone is getting "Online" mode errors, it means that they are using an illegal copy of minecraft. so, If you are:
**BUY IT.**

**Comment by mozai** [comment]
Are you accusing me of theft?  Don't be insulting.

**Comment by brainscript** [comment]
@mozai Why insulting? "Online mode" is the feature which checks if your account is saved in the Mojang database. If it returns yes you bought minecraft, if no you use an illegal copy (Cracked Minecraft).

Online mode is **enabled** on Wynncraft.

**Comment by mozai** [comment]
I'm using a paid-for copy of Minecraft; that should go without saying.   
Shouting "buy it" at me, or implying I'm using an illegal copy, won't fix the problem.

**Comment by xXAdamXx** [comment]
Ah, excuse that then. try reinstalling Minecraft, Or check for filters that might potentially mess up your Alg. key.

**Comment by AssassinkKitten** [comment]
Btw when that happened everyone had that error because the server was "down"

**Comment by FlyingfrogsES** [comment]
This a issue with bungeecord. You are using a valid version of minecraft. How bungeecord works is that the other servers in the network need to be offline to connect to them through bungee. Hope this helps it should be fixed already doe just wanted to tell you all what happened.

**Comment by FlyingfrogsES** [comment]
Also if you had a illegal version of MC you would get the measage "Failed to log in try restarting you game" this is the error message that appears when mc loses connection to the login servers or were never connected.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
