### ISSUE TITLE
VIP+ didnt work?

### ISSUE THREAD

**Issue by gangstaboy711** [Wynncraft/Issues#2514]
I bought a 50 dollar Visa at a store the other day and a few hours ago I bought VIP+ and it didnt give it to me, I'm 100% i wrote the right username. I already had the older vip which I bought a year ago, so maybe that is why it didnt give it to me? Or maybe I just need to wait but it has been a few hours now and i am getting concerned .

**Comment by NetherPup** [comment]
It might just be the server glitching out

**Comment by gangstaboy711** [comment]
kk, i'll wait a till tomorrow and if it still isn't there I'll see if i can get in contact with a admin

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by gangstaboy711** [comment]
Yeah I just dont really play wynncraft anymore because of the money issue
