### ISSUE TITLE
Servers are down

### ISSUE THREAD

**Issue by NetherPup** [Wynncraft/Issues#2515]
Hey all the worlds on the server are down and nobody can get on pls fix it its been like this for an hour or 2

**Comment by NetherPup** [comment]
I just found out about the server and i keep going on to see if its fixed

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
