### ISSUE TITLE
helmets

### ISSUE THREAD

**Issue by Hayamaka** [Wynncraft/Issues#2516]
helmets dont appear on my skin

**Comment by NetherPup** [comment]
it might be because the helmets arnt compatable with your skin or they didnt load correctly

**Comment by Hayamaka** [comment]
So i should try to change my skin and see if tht works

**Comment by DarkDemonDragon** [comment]
Sometimes it just takes a sec. If you're worried about whether the effects are being applied just check your stats in the compass. Also as a general tip always be careful when handling armor as everytime you put on and take off armor will cause a mini lag spike for you and you may accidentally throw something away.

**Comment by Hayamaka** [comment]
Is it possible its just taking the helmet to load since the rest of my
armor loads just fine and when i take it off the helmet and put it back it
does the lag spike then i still dont see the helmet. I also tried changing
skins which also didnt work so idk. Also i play for at least 45min at times
and at the end my helmet doesnt appear. If its hard to fix i think its fine
so long i still have the defense stats from the helmet.

On 19 November 2015 at 13:34, DarkDemonDragon <notifications@github.com>
wrote:

> Sometimes it just takes a sec. If you're worried about whether the effects
> are being applied just check your stats in the compass. Also as a general
> tip always be careful when handling armor as everytime you put on and take
> off armor will cause a mini lag spike for you and you may accidentally
> throw something away.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/2516#issuecomment-158149007>.
>



-- 
Reply back A.S.A.P

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
