### ISSUE TITLE
I cant get on servers

### ISSUE THREAD

**Issue by NetherPup** [Wynncraft/Issues#2517]
a lot of people are on the worlds but it wont let some of us on any help?

**Comment by FlyingfrogsES** [comment]
This happens alot and cant really be helped. If other people can join then sometimes what i do is log off the server and reconnect to the network through a different ip suck as .net for example for some reason it works but it shouldnt.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
