### ISSUE TITLE
I got teleported into the ground and cant move!

### ISSUE THREAD

**Issue by PattyMonster** [Wynncraft/Issues#2519]
I was doing the quest "Excavation site B" and got to the part where you gather the purple crystals and go through at the end of the room to teleport out. However when i did, i found myself stuck in the ground and unable to move. I dont have any teleport scrolls to teleport out of here and I'm not willing o restart as another class as I'm level 46. All i can see it a blank screen (like when you suffocate in a wall)

Please help!

**Comment by TrashcanMan** [comment]
Do /kill with at least three soul points.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
