### ISSUE TITLE
Ocean Mini-Dungeon Puzzle

### ISSUE THREAD

**Issue by brendanlolz** [Wynncraft/Issues#2520]
The puzzle is pretty much not doable, the puzzle is easy to solve, but the water never flows, ive tried at least 20 time switching from server to server, still the water never flows, i hope that the staff will do something about this

**Comment by TrashcanMan** [comment]
This one has been reported a few times. Sometimes the water not flowing is just a visual error and the puzzle works fine, but sometimes it's actually broken. If switching servers isn't helping try waiting an hour or two.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
