### ISSUE TITLE
Dungeon and mini-dungeon bosses respawning and disapearing  

### ISSUE THREAD

**Issue by finlayj123** [Wynncraft/Issues#2521]
I have been using the silverfish dungeon to grind at and whenever I kill the sand witch (the boss) instead of teleporting me out and giving me the reward for completing the dungeon like it should, it just respawns the boss. More often than not i have to kill it 3 times to be rewarded. This also occurs in the jungle mini-dungeon with the slime boss except in the mini-dungeon the boss doesn't even respawn, once you kill him you have to leave the dungeon and you don't get rewarded. I hope you will look into this. Thanks.
-Fin

**Comment by Trixter313** [comment]
Make sure that at the moment of death the boss is as close to the middle of the arena as you can get it. This is a known issue where if it's too close to the edges it won't register when killed. It might be intentional to discourage people from keeping the boss in a corner and mindlessly attacking it, but who knows.

**Comment by finlayj123** [comment]
Ok thank you for helping me, that is probably why it respawned. However in the case of the slime boss in the jungle mini-dungeon The boss was fairly close to the middle when he was killed and I din't get rewarded for the kill and he didn't respawn. Do you know why that was?

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
