### ISSUE TITLE
Infinite Purple Shard Crystal with /fixquests

### ISSUE THREAD

**Issue by SkySaito** [Wynncraft/Issues#2522]
So here's the bug, when doing /fixquests without the purple shards in the inventory it gives you 2 shards and you can do this again infinitely.
Look at the screenshots
![2015-11-15_11 26 38](https://cloud.githubusercontent.com/assets/7000957/11168349/44c8a940-8b8c-11e5-8fbc-829a76a370d5.png)
![2015-11-15_11 26 42](https://cloud.githubusercontent.com/assets/7000957/11168350/44e06e40-8b8c-11e5-9080-89e6aa2419e5.png)
Thanks for reading this issue

**Comment by SkySaito** [comment]
Hue ?

**Comment by SkySaito** [comment]
Bumping it for maybe referencing this issue, if no fixes are done yet.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
