### ISSUE TITLE
Christmas quest took me to below the map?

### ISSUE THREAD

**Issue by Lady-of-Rohan** [Wynncraft/Issues#2523]
So I was taking the Craftmas Chaos quest and I ended up here.

http://i.imgur.com/hshcSVL.jpg

http://i.imgur.com/97C9aCf.jpg

**Comment by TrashcanMan** [comment]
/kill with at least 3 soul points.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
