### ISSUE TITLE
My guild says theres no guild

### ISSUE THREAD

**Issue by Mbcrafter** [Wynncraft/Issues#2525]
I created a guild recently and it took the stuff and said i wasnt in a guild for some reason i completed all the stuff.

**Comment by TrashcanMan** [comment]
Sometimes it might take a while for it to register, try waiting a bit.

**Comment by Moe-Ronickah** [comment]
Guilds are currently highly bugged. Guild invites do not work, and kicking any guild member may cause the guild to be disbanded. See #2533 , #2481

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
