### ISSUE TITLE
Trapped in a corner.

### ISSUE THREAD

**Issue by TimJSwan89** [Wynncraft/Issues#2526]
71, 59, -1906 trapped in the corner of a building.
I had slept in a bed then got up again, spawning there.
I will do /kill, but maybe someone should fix.

**Comment by TrashcanMan** [comment]
You're not supposed to sleep in the beds, they're just for decoration.

**Comment by TimJSwan89** [comment]
I understand. However, I'm still going to wait to see what the staff will do about it. I'm sure they don't want it to be possible for players to get stuck, seeing as how they designed just about every other known cubic meter of the universe that way. For a minute there I was afraid you were staff responding, but I noticed that you were just someone commenting. Good design practice, which consistently see WynnCraft following heavily, will be sensitive to account well for that which is not explicitly intended. I'm sure they'll be glad I brought it up.

**Comment by TrashcanMan** [comment]
I remember somebody else bringing this issue up, and a staff member replied saying that it's sort of a common sense thing, and there's not really a need to disable beds.

**Comment by Moe-Ronickah** [comment]
Sleeping in a bed on a multi-player server in vanilla MC has no effect on any player in the game at the time.  However, WynnCraft runs on a custom plugin, and, apparently, beds have not been disabled.  This is either a code issue or a permissions issue.
See also #634 and #331.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
