### ISSUE TITLE
VIP+ Tag doesn't appear on forums

### ISSUE THREAD

**Issue by supermariowifi** [Wynncraft/Issues#2527]
I bought VIP+ a while back, and it shows in game, but not on the forums. https://wynncraft.com/player/supermariowifi
This link shows that I do in fact have VIP+
https://forums.wynncraft.com/members/supermariowifi.43727/
This link shows that I dont have it on the forums.

**Comment by TrashcanMan** [comment]
You should be able to do /forums (forum username) ingame to register your account, but the command might still be broken.

**Comment by supermariowifi** [comment]
Okay, I will try that now.

**Comment by TrashcanMan** [comment]
Yeah, it's still broken then. There's nothing you can do except wait until it's fixed.

**Comment by supermariowifi** [comment]
Alright then.
