### ISSUE TITLE
No Exit For Tunel Under Potion Merchant Near Ragni

### ISSUE THREAD

**Issue by NormyGt** [Wynncraft/Issues#2528]
I was going into the tunnel under the potion merchant near Ragni X= -498 Y= 67 Z= -1607 and at the end of the tunnel normally you would exit by pressing a wooden button and exit using a ladder but there is no link to the ladder there is a cobble wall blocking the path

**Comment by SkySaito** [comment]
Yeah, this is a known problem. You're only escape is to have either a scroll or doing /kill with at least 3 SP.
This problem will fortunately be fixed in the Gavel Update, so don't go there again.

**Comment by NormyGt** [comment]
yeah i wont its not hard im level 45 but its still ananoying

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
