### ISSUE TITLE
Guild

### ISSUE THREAD

**Issue by daansmienk12** [Wynncraft/Issues#2530]
I have make a new guild and i relog and my guild is away. nothing is working but if i kill a zombie there stay guild xp.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
