### ISSUE TITLE
My Guild Disappeared 

### ISSUE THREAD

**Issue by LivingShadowWof** [Wynncraft/Issues#2531]
So today I made a guild went through everything lost the 5 soul points and 5 le the bar was up for a while then it disappeared and it said I wasn't in a guild the guilds name was The Chaos Pack, I took a screen cap incase something like this happened, 
![2015-11-17_18 11 52](https://cloud.githubusercontent.com/assets/13156220/11230685/2163f468-8d5e-11e5-9eba-0fab5fcef587.png)
![2015-11-17_18 12 02](https://cloud.githubusercontent.com/assets/13156220/11230686/216a3ce2-8d5e-11e5-8908-c3e2426d36f1.png)
my user name is LivingShadowwolf if that helps at all.

**Comment by daansmienk12** [comment]
Me to

**Comment by CompactVenom12** [comment]
As I

**Comment by LivingShadowWof** [comment]
well in don't know if there fixed it but my guilds back now

**Comment by SkySaito** [comment]
Guilds are glitchy as heck, you must wait for the next update for a fix. Sorry about the other tho.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
