### ISSUE TITLE
Cant connect to the game world

### ISSUE THREAD

**Issue by Azrealon** [Wynncraft/Issues#2532]
Guys I tried to connect to the game world, and it only close the inventory tht shows all the game world.

**Comment by LivingShadowWof** [comment]
Been happening to me now and again just try restarting you launcher.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
