### ISSUE TITLE
Guild not working.

### ISSUE THREAD

**Issue by CompactVenom12** [Wynncraft/Issues#2533]
I created a guild, costing me 5LE/Liquid Emeralds and 5SP/Soul Points. In the attempt in bringing my fellow friends into the guild, It stated an internal error when they tried to accept the request. It is now 3 hours later and it now states I am not in a guild. Is there any bugs in GUILD? I'd like to be able to own my guild. The guild name is Revolution and the Prefix is LIR

**Comment by Bloodpearl969** [comment]
Same here. i created a guild, costed me 5LE and 5 SP, i tried to invite a friend to the guild and it said internal error occured, then just about 20 mins after i created the guild, it said ' you are not in a guild '
btw sorry if my english isnt good i am not english
thanks.

**Comment by mrlaubsauger** [comment]
We have the exactly same problems here :/

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
