### ISSUE TITLE
Guild & Level

### ISSUE THREAD

**Issue by bvx** [Wynncraft/Issues#2534]
Well, I've just noticed that my Guild, that I've made and is leader in is gone. And that I've lost a lot of levels or experience somehow. I achieved lvl. 71 for some time ago... I don't really know how long ago, but now I'm in lvl 56! (Archer). Seems like my character has lost levels. And my guild is gone. I don't know if this is a temporary bug. I don't know what more it is to say about it, I'm kinda sad now.

I really hope someone knows about this bug, or are able to do something with it.

**Comment by DarkDemonDragon** [comment]
Some screenshots would be necessary for anything to be done. Perhaps you've remembered wrong, on the wrong account, or looking at the wrong class (if you're a donor check the normal and donor versions).

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by bvx** [comment]
I am still experiencing this or these issues after the update. I  don't have any schreenshots from the time before the issues, but I hope you will belive me. I am enjoying Gavel, ranking up with my archer class, trying to reach 71 once again. The worst is the Guild issue - my Guild does not have a leader!

**Comment by Trixter313** [comment]
That's very unfortunate! Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
