### ISSUE TITLE
Quest "Frost Bitten"

### ISSUE THREAD

**Issue by counto1** [Wynncraft/Issues#2535]
I have tried every way to try and go on with the quest and get the bucket but I can not get the bucket you need to for the quest "Frost Bitten" back because I am up to the bit where you get the lava and you have the bucket but I do not have the bucket anywhere.  Please fix this because I need to exp so the mindless hours of grinding isn't as long. ty :D

**Comment by TrashcanMan** [comment]
Have you tried /fixquests?

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
