### ISSUE TITLE
right click with weapon glitch

### ISSUE THREAD

**Issue by finlayj123** [Wynncraft/Issues#2536]
Now I have seen this bug before (I think its a bug) when i was playing as a low level archer, i would try to cast arrow storm spell (left-right-left) and it would exclude the right and i would just have left-left and the spell would not cast. This instance is a bit different, a lot of the time when i attempt to cast the uppercut spell (as a warrior) which is right-left-right it shows up as right-right-left which is war scream. I can only assume that it thinks I have right clicked twice. I also fiddled with my mouse (changed battery, sensitivity, ect,) and can confirm that it is not the mouse or my computer as this only happens inside of wynncraft. Please do look into this and any info would be greatly appreciated.
-Finlay

**Comment by DarkDemonDragon** [comment]
The left/right clicks get mixed up or double clicked if you do it on something like a door, button, or mob.

**Comment by TrashcanMan** [comment]
Also sometimes if you click too fast it doesn't register all the clicks, and if you click twice, then try to cast another spell, the first two clicks will still register and screw things up.

**Comment by Moe-Ronickah** [comment]
Right-clicking on an entity in MC or Wynn is the "use item" control.  Therefore, when a mob is close to you, close enough to be "used", both MC and Wynn expect for you to "use" the mob.  In the case of an NPC, right-clicking let's you talk with the NPC.  In the case of a hostile mob, there is no interaction interface to open, so Wynn does nothing.  It's one of the cases where maintaining a safe distance, or right-clicking AWAY from the mob, or at the floor, is currently the only work-around.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
