### ISSUE TITLE
My liquified emerald dissapeared

### ISSUE THREAD

**Issue by silverlego** [Wynncraft/Issues#2539]
So i was on wynncraft putting a liquified emerald away then i close the bank, after that i soon want to check something in the bank, AND BAM it is just gone i try everything i can, but nothing works plz fix, also would like liquified emeralds back, btw i had 5 liquified emeralds.

**Comment by LivingShadowWof** [comment]
sometimes  the icon is just invisible try picking it up if that doesn't work then you just lost some LE unless you had a screen cap before and after with timestamps then there no proof you had them sorry to say this bad news to you.

**Comment by silverlego** [comment]
Well that sucks for me then

**Comment by DarkDemonDragon** [comment]
Yea unfortunately Wynncraft has a strict no item-refund policy. When I'm doing ANYTHING with LEs I'm super careful and make sure I do one movement at a time I keep it in my inventory for as little as possible.

**Comment by Trixter313** [comment]
We'd appreciate if if you closed this issue. Thanks!
