### ISSUE TITLE
Suddenly not part of my guild

### ISSUE THREAD

**Issue by Awesomeqfries202** [Wynncraft/Issues#2540]
I was traveling to the Tower of ascension with a friend, and was kicking a player out of the guild I made. He hadn't been online in forever. However, instead of him being kicked out, I was suddenly not part of the guild. Guild page is now displaying incredibly weirdly: https://wynncraft.com/guild/Fallen%20Star and I am no longer the owner and no longer in the guild.

**Comment by Awesomeqfries202** [comment]
I checked back in today, and it seems that I'm still not back in the guild. Any ideas on what could have happened?

**Comment by Moe-Ronickah** [comment]
Guilds are currently highly bugged. Guild invites do not work, and kicking any guild member may cause the guild to be disbanded. See #2533 , #2481

**Comment by Awesomeqfries202** [comment]
Thank you, that puts my mind at ease for now. Guess I'll just wait 'til they fix it then...
