### ISSUE TITLE
Firewalled?

### ISSUE THREAD

**Issue by Quinary** [Wynncraft/Issues#2541]
I would like to know if my IP is firewalled because I cannot connect to the server. I can connect to the website though unless they are hosted on 2 separate boxes. I wouldn't like to say my IP here though maybe some other way I can tell you guys it.

**Comment by Quinary** [comment]
I also would like to note that I can connect with a VPN which makes it even more likely that it is something to do with my IP address.

**Comment by Moe-Ronickah** [comment]
Quinary, when someone cannot connect to the game, there is usually a message displayed.  Unless that message says that you were banned, your IP should not be the problem.

**Comment by SkySaito** [comment]
Or that, or you should try with a .net or .org at the end of the server IP

**Comment by Quinary** [comment]
I found the problem it was my minecraft version. I guess wynncraft doesn't work with forge.

**Comment by Moe-Ronickah** [comment]
WynnCraft works quite well with Forge as I've been using it for more than a year.  I'm glad that you found a way to fix your issue.  Enjoy playing WynnCraft, and please close this issue.
