### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by Gargarath** [Wynncraft/Issues#2542]
Hello,
I recently re-play wynncraft, but I got some quests problems, with my Mage (lvl 47) the only quest possible is tower of assention (extremely hard) ans I've started an assassin (lvl 37) who have any possible quest... So what is wrong with me? Do I have to only farm dongeon?
                                         Thank for reading and hope for a answer, Gargarath87.

P.S: Sorry for my bad english (I'm frensh ^^)

**Comment by DarkDemonDragon** [comment]
Yea there are a couple what I like to call "Awkward" levels where there aren't any clear ways to level up. With your Mage I recommend doing dungeons with friends and paying attention to xp bombs. Good luck with your adventure! :)

**Comment by Moe-Ronickah** [comment]
Gargarath, if this issue is resolved, would you close it, please?  Thank you.

**Comment by TrashcanMan** [comment]
Once Gavel comes out (which should be "soon"), they're going to add a ton of new quests and grinding spots, so you could just wait until then.

**Comment by SkySaito** [comment]
Attend le prochain niveau pour de nouvelles quêtes, donc oui tu va devoir farm un peu. Si ta question est répondu, tu devrais fermé cette issue ^^
