### ISSUE TITLE
Lost Xp Bombs 

### ISSUE THREAD

**Issue by DevinPritts** [Wynncraft/Issues#2543]
I recently had bought gold coins to buy xp bombs, but I tried to throw them recently and they didnt work instead they just say cannot be thrown at this time. thanks for reaaddy and please help I lost 3 xp bombs.
http://imgur.com/8xRAwH7

**Comment by Moe-Ronickah** [comment]
You need to send an email to: support@wynncraft.com
Be specific about what happened and include the image that you posted, above.  Please give them 72 hours to respond, and if they don't, contact them, again.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
