### ISSUE TITLE
Wynncraft Wiki Email Confirmation

### ISSUE THREAD

**Issue by meatloaf4311** [Wynncraft/Issues#2545]
Wynncraft wiki will not let me confirm my email account in order to edit articles.

The Mailer returned: Failed to add recipient: {EMAIL ADDRESS} [SMTP: Invalid response code received from server (code: 451, response: Temporary local problem - please try later)]

This issue had happened multiple times even when trying to create a new account or use a different email. I even have tried emailing support to no avail.

I just want to confirm my so that I can contribute to the wiki.

**Comment by TrashcanMan** [comment]
Wynncraft doesn't actually host the Wynncraft Wiki, it's done through a site called MediaWiki. You could go check out their site and see if there's something about this error.
https://www.mediawiki.org/wiki/MediaWiki

**Comment by meatloaf4311** [comment]
Went and checked that out, no real answers and I can confirm my email for one of their accounts as well.

**Comment by Trixter313** [comment]
Are you still experiencing this issue?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by meatloaf4311** [comment]
This is still an issue.

I have tried here, tried support@wynncraft . I dont know what else to do

**Comment by Trixter313** [comment]
Because this is a 3rd party website I don't think there's much we can do here. I suggest contacting the MediaWiki people using one of these various methods: https://www.mediawiki.org/wiki/Communication
