### ISSUE TITLE
Stuck in a Box

### ISSUE THREAD

**Issue by Ligaligi** [Wynncraft/Issues#2546]
Dear Wynncraft staff,
        Hi, I was playing around on my archer class when I randomly got teleported into a box made of black wool. It is only the archer class that is stuck, no matter what I do I can't leave the box with that class. It would be very helpful if someone told me how to get out or just teleported me out.
PS: If it helps, my coordinated are X: -981 Y: 63 Z: -1693
Thank you,
Ligaligi

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Ligaligi** [comment]
Thank you so much!
