### ISSUE TITLE
[Guild Invite Error] Can't join my friend's guild (Screenshots provided)

### ISSUE THREAD

**Issue by DarkDemonDragon** [Wynncraft/Issues#2547]
We tried relogging and all sorts of things but nothing worked. Basically when he invites me to his guild, and I do /guild accept ASO it says I joined, and immediately says there was an error. He also gets a message I accepted and joined, but I don't see guild chat, don't get the tag, and can't use guild commands. After the 1st attempt the game thinks I don't get an invite despite him sending me invites.
![2015-11-22_17 29 32](https://cloud.githubusercontent.com/assets/15721340/11329666/5fe8947e-916d-11e5-8de1-705ec29ac313.png)
![2015-11-22_17 43 09](https://cloud.githubusercontent.com/assets/15721340/11329667/5fec9ac4-916d-11e5-9198-1362c43dfa06.png)

**Comment by Moe-Ronickah** [comment]
Guilds are currently highly bugged.  Guild invites do not work, and kicking any guild member will cause the guild to be disbanded. See #2533 , #2481

**Comment by DarkDemonDragon** [comment]
#2533 is related to this but why haven't staff responded? Are guilds planned to be fixed anytime soon? (please don't say it'll be fixed when Gavel is released @_@)

**Comment by Moe-Ronickah** [comment]
From the comments and responses in the sub-forum on Guilds, where staff is responding, these glitches will be fixed -after- Gavel is released, due to the amount of work needed to fix them.  For the time being, guilds are broken.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
