### ISSUE TITLE
Character Info in my bank?

### ISSUE THREAD

**Issue by Ligaligi** [Wynncraft/Issues#2552]
For some odd reason I have a character info compass in my bank. It is a waste of space and I can't take it out. If anyone knows how to get it out or can take it out then please tell me. 
Username: Ligaligi
Thank You,
Ligaligi

**Comment by DarkDemonDragon** [comment]
Some screenshots would be necessary. Also most "illegal" items should be removed once you relog.

**Comment by Ligaligi** [comment]
![2015-11-25_18 06 34](https://cloud.githubusercontent.com/assets/15972250/11412859/5ceaaf30-939f-11e5-8ada-1eded8bb5ed1.png)

**Comment by DarkDemonDragon** [comment]
Well that is strange o.O What message appears when you try to move it around, or does it just return to the bank GUI on it's own without a message?

**Comment by Ligaligi** [comment]
It just puts itself back in the bank, same spot.

**Comment by DarkDemonDragon** [comment]
@Ligaligi feel free to reopen this if the issue still persists.
