### ISSUE TITLE
I can´t join... again.

### ISSUE THREAD

**Issue by MattHei1** [Wynncraft/Issues#2553]
I join the server, try to join WC1, wait a minute and still no errors or full server error or still connecting to this server, is this a glitch or are the servers temporarily down?

**Comment by TrashcanMan** [comment]
The servers are probably down for maintenance, just wait a while and it should work.

**Comment by Moe-Ronickah** [comment]
Please close this issue if you have been able to login to WynnCraft.  Thank you.
