### ISSUE TITLE
Glitched Emeralds from Item Buyers

### ISSUE THREAD

**Issue by Jerry9011032** [Wynncraft/Issues#2554]
So I have been selling some things at Detlas, and you know those emeralds they drop but you can't pick up? I somehow picked some up. They don't have the normal emerald name, and can't be traded for items or stacked with normal emeralds. I really don't know what to do with them, so I put them in the bank. 
![screen shot 2015-11-24 at 5 53 19 pm](https://cloud.githubusercontent.com/assets/16015146/11394877/b51aeaaa-93a2-11e5-9c61-77a7f7138f7c.png)

Those are the glitched emeralds. As you can see, they don't have green titles. You don't have to fix it, but it just caused a lot of confusion for me.

**Comment by DarkDemonDragon** [comment]
I think those are actually usable in shops and stuff, but I'm not sure. It's just 5 emeralds so either keep them or destroy them. Your choice :) If your issue is resolved please close this.
