### ISSUE TITLE
 I can't connect to servers .

### ISSUE THREAD

**Issue by DominikGamer** [Wynncraft/Issues#2556]
nto the lobby eases yet to go, but if I select a server, onto which I would like to go up, nothing happens. I tried everything out already, and not good. :(

**Comment by SkySaito** [comment]
Did you installed a mod ? 
Did you try from another lobby ?
Tell us what you already did

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
