### ISSUE TITLE
Head Stuck in wall

### ISSUE THREAD

**Issue by Majordopeness** [Wynncraft/Issues#2557]
on sever 5 in the town of almuj i was using the mage skill of teleportation when i got my head stuck in a wall I cant use my fast travel scrolls to get out of it and i was wondering if someone could help me out my gt is : TheDJPenguin

**Comment by SkySaito** [comment]
Try /kill with at least 3 SP, it'll bring you back to the closest visited town.

**Comment by Moe-Ronickah** [comment]
You can also try changing servers as your position changes slightly when you do.  If your problem is resolved, please close this issue as it occurs in Wynn because we cannot take suffocation damage..
