### ISSUE TITLE
Guild problem

### ISSUE THREAD

**Issue by SteveClinton** [Wynncraft/Issues#2560]
We just want to start attacks. Then there was a fallback server thing.. and now we cant attack anymore! It says: your guild is already in a battle......

**Comment by SteveClinton** [comment]
can we end this battle with a command???

**Comment by SkySaito** [comment]
Guild are broken at the moment. Please wait for the next update before doing something else with your guild.
And have fun playing on Wynncraft !

**Comment by Moe-Ronickah** [comment]
As has been said, guilds are broken at this time.  This is a duplicate of #2204.  Please close this issue.

You might want to read the forums, guilds subforum, before taking the time to post a bug report.  The problem with guilds is well known and well discussed.

**Comment by SteveClinton** [comment]
now i can attack again but if we try that we dont get teleportet xDD

**Comment by Syltan-Adam** [comment]
...


This is a duplicate of #2204. **Please close this issue.**
