### ISSUE TITLE
STUCK IN PISTON AND CAN'T GET OUT BY SCROLLS (nvm i got out by changing class over and over again)

### ISSUE THREAD

**Issue by CHENS85** [Wynncraft/Issues#2561]
![2015-11-25_07 38 56](https://cloud.githubusercontent.com/assets/5460820/11411935/45d423a4-9411-11e5-9eac-845416b94ac4.png)

**Comment by CHENS85** [comment]
PLEASE ADMINS HELP ME

**Comment by TrashcanMan** [comment]
If your issue is resolved, you can close it by clicking the button at the bottom of the comment box.

**Comment by Syltan-Adam** [comment]
Please close this issue.
__you can close it by clicking the button at the bottom of the comment box.__
