### ISSUE TITLE
Forum Welcome Message

### ISSUE THREAD

**Issue by NiNjAiKoToBa** [Wynncraft/Issues#2563]
I apologise if this isn't the right place to report it, but i thought i'd let people know that from the looks of it, all the links provided in the forum welcome message don't seem to work.

The links i'm referring to are as follows:
http://forums.wynncraft.com/forums/questions/
http://forums.wynncraft.com/forums/trade-market/
http://forums.wynncraft.com/forums/general-suggestions/
http://forums.wynncraft.com/forums/player-reports/
http://forums.wynncraft.com/forums/introduce-yourself

What i have noticed is that it seems the index of the forums itself has been moved from /forums to just /
That, and there isnt a questions board anymore.

Hopefully this could be fixed to better help out the newcomers :)

**Comment by SkySaito** [comment]
Where did you get these links ? From https://forums.wynncraft.com/ everything is accessible

**Comment by SkySaito** [comment]
If you had these links before 9/7 , it's more likely that they aren't usable due to the accidental forum wipe

**Comment by Syltan-Adam** [comment]
There are Numbers amended to the links.

**Comment by NiNjAiKoToBa** [comment]
I had finally re-registered my account, and these were all in the welcome PM i received as shown here:
http://prntscr.com/97f93e

**Comment by brainscript** [comment]
https://forums.wynncraft.com/conversations/welcome-to-the-wynncraft-forums.77000/

**Comment by Moe-Ronickah** [comment]
@Tama63, it appears that the links in the "Welcome to the Forums" message are no longer valid.

No further comments are necessary.  Please DO NOT close this issue, as it is an issue that only Tama or another admin can fix.
