### ISSUE TITLE
Accidently ate my quest item...

### ISSUE THREAD

**Issue by Mobjoe** [Wynncraft/Issues#2566]
(I dont know if i could call this a bug, but i think it is one) So... Some days ago, i did a quest called "The angry village" I got a item from that quest (The corrupted potato), that i will need inn a later quest called "Temple off legends" The thing that really does me frustrated is that i ate up this potato. And i dont have one anymore. Could you please fix this for me? If its possible to get a new one? I know i could change class and get it, but it would take alot of time becuase i need to level my self up to do the quest.

**Comment by CF12** [comment]
You should be able to use /fixquests to get the potato back. :D

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
