### ISSUE TITLE
Legendary Item - Pélier Helmet, not being identified 

### ISSUE THREAD

**Issue by WexterMV** [Wynncraft/Issues#2567]
For some unknown reason I cant identify my helmet, (IT SAYS LEGENDARY!!!!) and when I try to identify it the npc says, I'm afraid I can't identify this item! Only weapons and armours with a Unique, Rare, Legendary, and Special tags can be identified.

**Comment by DarkDemonDragon** [comment]
Duplicate of #1312

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!
