### ISSUE TITLE
Lose My 5 LE

### ISSUE THREAD

**Issue by Magicalyule** [Wynncraft/Issues#2568]
I was at the bank I just go to the Item Buyer and when I came back all of my Liquified Emeralds were gone.

**Comment by brainscript** [comment]
:tired_face:

**Comment by GamerGamerFTW** [comment]
There is no evidence, you might be lying.

**Comment by brainscript** [comment]
@GamerGamerFTW That's what I mean.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strict no refund policy so getting the emeralds back probably won't happen. We'd appreciate it if you closed this issue. Thanks!
