### ISSUE TITLE
Liquid emerald changing to quest items for Jungle Fever quest

### ISSUE THREAD

**Issue by KnightSanctity** [Wynncraft/Issues#2569]
So I had two liquid emeralds from completing the House of Twain quest and I had to do the Jungle fever quest, so when I complete the quest to get my reward the two liquid emeralds from the House of Twain quest turned into the quest item emeralds making them useless.

**Comment by DarkDemonDragon** [comment]
1) Don't carry around LE ;-;
2) This is a known bug

**Comment by GamerGamerFTW** [comment]
In selchar there is a villager that turns old (that type of yours) emeralds into new ones. So dont throw them out!

**Comment by DarkDemonDragon** [comment]
@GamerGamerFTW that doesn't help. He has Quest LE not Old LE.

**Comment by GamerGamerFTW** [comment]
I tried with these quest emeralds it worked but i wanted to finish the quest

**Comment by DarkDemonDragon** [comment]
@GamerGamerFTW ... WHAT!!! You're saying that I could have taken all 64 LE and converted them to normal LE!?! I think a lot of people would choose to do that than continue with the quest ._.

**Comment by GamerGamerFTW** [comment]
Yeah i figured that out when i was doing santa and i saw that old LE name and the quest LE name and it was the same and i even tried and it worked
