### ISSUE TITLE
Stuck in a black box

### ISSUE THREAD

**Issue by HyperFire12** [Wynncraft/Issues#2572]
When I log on to a server, and click the warrior icon, I get sent to a black box where I cant teleport using my scrolls, but can use my moves. Please Help!!! My IGN is  : exdragon47

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will respawn you at the nearest visited town.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by HyperFire12** [comment]
Thx alot Nick! It really Helped.
