### ISSUE TITLE
Guild troop donation bug

### ISSUE THREAD

**Issue by SolidStrafe** [Wynncraft/Issues#2573]
https://gyazo.com/e36d8b8b06ce1f31759fb62e57e9e7f9

**Comment by GamerGamerFTW** [comment]
Youre sure you did everything right?

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
