### ISSUE TITLE
/guild xp 100

### ISSUE THREAD

**Issue by DetlasMaster** [Wynncraft/Issues#2575]
(sorry, this is my first issue)

Hi, my name is DetlasMaster and yesterday I have done the command '/guild xp 100' without knowing the consequences. I regret this now, because now I can't level up. Is there any fixes for this?

**Comment by SkySaito** [comment]
Do /guild xp with a different number mate

**Comment by SkySaito** [comment]
If your issue is fixed, I hope you'll close this thread.
Have a good game !

**Comment by DetlasMaster** [comment]
Thanks!
