### ISSUE TITLE
2 Skill points missing

### ISSUE THREAD

**Issue by Cubixz** [Wynncraft/Issues#2576]
I leveled up to level 34, trying to max out strength on my ninja,  but when I used both of my skill points on it, nothing changed, I already had 64, and was trying to get 70 (being the maximum according to the wiki.) I would like to know if anybody else had had this problem, or how to fix it.

Thanks,
Cubixz

**Comment by SkySaito** [comment]
Did you try to relog after that ? It could be a graphic bug

**Comment by TrashcanMan** [comment]
Since items in Minecraft only stack up to 64, you only see 64 even if you go past that. However if you mouse over the skill points it should say you have 70.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
