### ISSUE TITLE
My Reward disappared

### ISSUE THREAD

**Issue by Krallorddark** [Wynncraft/Issues#2579]
I did the Bob's Lost soul quest and I did not get the bob's battle chestplate! I did other quests after bob's lost soul.. then I checked my Inventory, There was no chestplate! I did the /fixquests but I got the other quest's item! please help ASAP!

**Comment by Trixter313** [comment]
Wynncraft has a strict no refund policy so not much can be done here. If not already, soon you should find an even better chestplate! Especially since the Gavel update added so many new armors. We'd appreciate it if you closed this issue. Thanks!
