### ISSUE TITLE
Staying at Class Selector Room

### ISSUE THREAD

**Issue by GluonPlays** [Wynncraft/Issues#2580]
Hello...
First I'm sorry about my english... im german...

IGN: gluon8
Well my problem is: If i equip my mage after joining a server im not teleported anywhere so i stay there and cant move away which is a big problem because its my most powerful char... it would be cool if you can help me!

Thanks
gluon8

**Comment by GluonPlays** [comment]
Ok if done /kill... sorry

**Comment by TrashcanMan** [comment]
If your issue is resolved we would appreciate it if you could close the issue. Thanks!
