### ISSUE TITLE
2 bugs in one report!

### ISSUE THREAD

**Issue by SolidStrafe** [Wynncraft/Issues#2581]
Bug #1 So today I went to farm XP for my guild and some lvl 59 archer was in the Trainer farming area. He told me he logged on and spawned in the Temple.

proof: https://gyazo.com/400f44db0304345f276bb8a653710f9c

https://gyazo.com/4e36d3d22073e59202ac7e0d3c85245c
-------------------------------------------------------------------------------------------------------------------------------------------
Bug #2 When I do /fixquests I got some items from a quest I finished for example from the quest "Grand Youth" I get another Healing Water and 2x Yellow Crystal Shard and 2x Purple Crystal Shard... even though I did the quests and all I need to do is the boss fight. And also my friend who has done the quest completely he has the SAME problem!

**Comment by Trixter313** [comment]
Are you still experiencing these issues since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
