### ISSUE TITLE
Guilds Issues

### ISSUE THREAD

**Issue by BudderBiscuit** [Wynncraft/Issues#2582]
Small bug with /guild xp

I did /guild xp 90, killed something, got the normal amount of EXP (as if I did /guild xp 0), but an additional 110% EXP went to the guild.

Example: Kill Frost Golem, get 200 EXP like normal, but a magical 220 EXP appears from nowhere and goes to the guild.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by BudderBiscuit** [comment]
Oh yeah, it's fixed.

Buuuuuuuut
1 last thing, edited the post.

**Comment by Trixter313** [comment]
Hmm, that is odd indeed. I wonder if it's just a temporary issue or not. If you could, report back tomorrow or so on whether it's still happening or not. Thanks!
