### ISSUE TITLE
Hallowyyn Quest 2014 Still in Book

### ISSUE THREAD

**Issue by Jerry9011032** [Wynncraft/Issues#2583]
I still have the 2014 Hallowynn quest with the haunted mask thing, but the cave is not there and I don't know any way to complete the quest. They removed the cave and person on Nov 5th of 2014, but the quest still remains inside the quest book. Can you remove this quest from the book?
![screen shot 2015-12-03 at 11 26 56 pm](https://cloud.githubusercontent.com/assets/16015146/11564752/c3af9ba0-9a15-11e5-8d11-34e1616fdece.png)

**Comment by DarkDemonDragon** [comment]
I literally just helped someone out with this quest last night so it's there. Search the wiki if you wish to find exact coordinates (https://wiki.wynncraft.com). If this solved your issue please close this.

**Comment by 21harrisont** [comment]
The wiki dosen't have the co-ordinates! It just says to enter the cave you stupid idiot!

**Comment by LordHelmchen98** [comment]
@21harrisont keep calm please and read the whole page of the quest. It doesn't help anyone if you just insult people. On the bottom of [this page](https://wiki.wynncraft.com/index.php?title=Macabre_Masquerade) you can find the coords.
