### ISSUE TITLE
/guild stat and /guild leaderboard bugged (Screenshots provided)

### ISSUE THREAD

**Issue by DarkDemonDragon** [Wynncraft/Issues#2584]
Basically when I do /guild stat and /guild leaderboard it'll show the guild "Nobody". I don't even understand this bug since "Nobody" seemed to be a legitimate guild at one point, so this is honestly kind of weird. Here are some screenshots:
![2015-12-01_21 06 36](https://cloud.githubusercontent.com/assets/15721340/11573952/e9e945b2-99d6-11e5-9a52-184d57060112.png)
![2015-12-01_21 08 03](https://cloud.githubusercontent.com/assets/15721340/11573953/e9e99530-99d6-11e5-9e77-87fadf7eb6cd.png)

**Comment by SkySaito** [comment]
What a creepy bug ;-;

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by DarkDemonDragon** [comment]
@Trixter313 welcome back! Yes, this is still a persistent issue.  Additionally, my guild is now not leveling up and is at 118% xp the last time I checked.

**Comment by Trixter313** [comment]
Sorry to hear that! Thanks for the bug report and welcome! An admin should see this soon and hopefully will be able to help.

**Comment by DarkDemonDragon** [comment]
@Tama63 I realize that you've done a mass close because the issues were piling up, but please revisit this as this issue still persists. Post-Gavel evidence can be provided if necessary.
