### ISSUE TITLE
STILL Bugged Loot Chest (Screenshots Provided)

### ISSUE THREAD

**Issue by DarkDemonDragon** [Wynncraft/Issues#2585]
At Zhight Island there's a chest that you can't open due it's location directly under a block. It has been about SEVEN months since this issue was brought up ( #1924 ) and it may have been forgotten.
![2015-11-29_11 36 22](https://cloud.githubusercontent.com/assets/15721340/11574129/bfb55e9c-99d7-11e5-8344-64159d2762cf.png)
![2015-11-29_11 36 24](https://cloud.githubusercontent.com/assets/15721340/11574128/bfb50d48-99d7-11e5-88dd-8acb2275b925.png)
![2015-11-29_11 36 26](https://cloud.githubusercontent.com/assets/15721340/11574127/bfb3fb2e-99d7-11e5-9069-c4bb8a26a463.png)

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by DarkDemonDragon** [comment]
Is there some test server where you could check this because I'd have to take a boat out there whereas you could simply tpa there since I have the coords provided. If necessary though I'll take some time to go back to Zhight Island and see if the chest is still like this.

**Comment by Trixter313** [comment]
I just checked and I believe the issue has been resolved! Here are some images I took so you can verify.

I think this issue can finally lay to rest!

![2015-12-22_23 54 10](https://cloud.githubusercontent.com/assets/7178055/11971209/73ce2e5c-a907-11e5-97fa-25e34f4147f5.png)
![2015-12-22_23 54 19](https://cloud.githubusercontent.com/assets/7178055/11971211/73d3bb06-a907-11e5-8b65-60e7b329f5db.png)
![2015-12-22_23 54 22](https://cloud.githubusercontent.com/assets/7178055/11971210/73d2ca34-a907-11e5-890b-fb39a9e45445.png)

**Comment by DarkDemonDragon** [comment]
Hooray! Thanks for your help! :smile:
