### ISSUE TITLE
MAJOR Issue makes the servers lag!

### ISSUE THREAD

**Issue by Krallorddark** [Wynncraft/Issues#2587]
First off... I know U added the gavel in to the map for testers,so I understand a "little" bit of lag..
But the HUGE Problem that caouses servers instantly Lag and restart is using HORSEs, right!I joined a server that had %0 lag shown and It was really lagless... But When I put down my horse EVERYBODY In that server lagged out! literally! then Lobby is laggy when you type /servers after that laggy server! even disconnecting does not works properly! And I have a friend that has same Issue! so It's not bcs of my connection or PC...

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
