### ISSUE TITLE
Bugged Emeralds

### ISSUE THREAD

**Issue by OfficialVigg3** [Wynncraft/Issues#2589]
For some reason I got 64 blocks of bugged emeralds. They cant be traded. I dont know if they updated the server and changed all the emeralds. Any help? My ingame name is OfficialVigg3

**Comment by TrashcanMan** [comment]
There's a Converter Merchant in Selchar that will convert older emeralds to new ones.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
