### ISSUE TITLE
TOL Trainer glitch

### ISSUE THREAD

**Issue by Pzev** [Wynncraft/Issues#2590]
You guys probably know about this, but the TOL trainers are pretty glitched.  Sometimes they die but become glitched and still alive, sometimes they are glitched and you cant kill them, and they cant kill you.  Its just generally annoying. Please fix when you guys get a chance. Thanks!
![2015-12-04_18 56 12](https://cloud.githubusercontent.com/assets/11162262/11604318/0c0b599a-9ab9-11e5-9443-6b6a0044f932.png)

**Comment by Pzev** [comment]
Heres a video of the glitch, these ones cant hurt me but they push me around a bunch, super annoying.
https://www.youtube.com/watch?v=iPZwJcbivJg

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
