### ISSUE TITLE
Skin Not Rendered Properly With Armors (12/4/2015)

### ISSUE THREAD

**Issue by BravestTech** [Wynncraft/Issues#2591]
New skin uploaded from "Minecraft Skin Studios" appears in lobby and in world without any armor, once armor is applied (Example: Helmet of legends + Endgame chestplate, leggings and boots) skin reverts to an older version.
This occurs on my Mage and Assassin but my Warrior seems unaffected, Please fix this soon.

**Comment by TrashcanMan** [comment]
This is a known issue, just wait a few weeks for the skin databases to update.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
