### ISSUE TITLE
Xp Bug

### ISSUE THREAD

**Issue by Larrynator** [Wynncraft/Issues#2592]
I don´t get any XP from Mobs,Missions ore Quests.When i kill a mob i only get Guild XP.

Name: _Larry_

**Comment by MisterShinigami** [comment]
use the command /guild xp 0

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
