### ISSUE TITLE
Water dungeon - Water glitch/bug?

### ISSUE THREAD

**Issue by GamerGamerFTW** [Wynncraft/Issues#2595]
I found water dungeon and in the water puzzle, water doesnt move, so i cant get to kraken.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
