### ISSUE TITLE
Nether bug

### ISSUE THREAD

**Issue by Seberichsen** [Wynncraft/Issues#2596]
So if you change class while the arena is reseting and then join nether again.

Then you will be alle to fly and you cant take any damage so i Think this isue should be fixed pretty quick because it looks like you are hacking

**Comment by GamerGamerFTW** [comment]
Can you hit others tho?

**Comment by Seberichsen** [comment]
Yes you can push back with spells but cannot damage them.
Den 06/12/2015 17.26 skrev "GamerGamerFTW" <notifications@github.com>:

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
