### ISSUE TITLE
Climbing helmet

### ISSUE THREAD

**Issue by Emiell123** [Wynncraft/Issues#2597]
When I completed the quest 'Ice Nations' I didn't received the helmet. Now i can't finish the quest Zhight Island. Please help

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
