### ISSUE TITLE
Stuck in block from TP

### ISSUE THREAD

**Issue by craigp20** [Wynncraft/Issues#2598]
I was doing the WynnExcavation B quest, and I got to the end of the mines where it tp's you out, and it had tp'd me into a block and I have to teleport scrolls and im now stuck there. I wanted to report this so it doesnt happen to others, also I need a mod to tp me out please! My MC IGN is BobRossIsDead

**Comment by GamerGamerFTW** [comment]
Theres a way, /kill it will teleport you to nearest village.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
