### ISSUE TITLE
Armor

### ISSUE THREAD

**Issue by GamerGamerFTW** [Wynncraft/Issues#2599]
For my armor some parts are missing - 
http://prntscr.com/9b0kwk
For some other players i see the same so these textures need to be fixed.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
