### ISSUE TITLE
Dungeon bosses glitch.

### ISSUE THREAD

**Issue by GamerGamerFTW** [Wynncraft/Issues#2601]
This is not for most of the bosses but for some bosses if you knock the to wall in corner they cant use theyr special ability. Im not saying that its bad but it needs to be fixed.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
