### ISSUE TITLE
ToL glitch

### ISSUE THREAD

**Issue by CryogenicFrost** [Wynncraft/Issues#2602]
If you already have a class in ToL, you can get another class in by glitching the riding system. If you're the one who wants to get the class in, get someone to ride onto you, then swap to the class you want to get in, and you'll spawn where you were sat on. http://i.imgur.com/ern9NYd.png
I tested to see if XP could be gained with a level 25, luckily none can be gained.

**Comment by Trixter313** [comment]
Can this still happen since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
