### ISSUE TITLE
[CLOSED] Double Guild Chat?

### ISSUE THREAD

**Issue by ShayminKeldeo421** [Wynncraft/Issues#2604]
After changing my username I receive 2 of every message I send or receive in the guild's chat. Any way to fix this?

**Comment by GamerGamerFTW** [comment]
I think leaving and rejoining should fix it

**Comment by SkySaito** [comment]
Guild are still glitchy, and doing that can result in bad things for your guild. So wait for the next update for a guild fix.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by ShayminKeldeo421** [comment]
It was fixed when Gavel was released, thanks. :)
