### ISSUE TITLE
takes me back to an earlier stage in the quest so I can not continue the quest

### ISSUE THREAD

**Issue by jared-s05** [Wynncraft/Issues#2605]
I was doing the quest wynn excavation A so I have explored the tombs and I come back to talk to
excavator vade and he is saying for me to translate a scroll which I had already done!

you could fix this by well I dont know how but plz help because then I wont be able to do other
wynn excavations :(

**Comment by GamerGamerFTW** [comment]
Did you talk to the woman (That NPC near it)?

**Comment by jared-s05** [comment]
yeah and I explored the tombs but now it says talk to her again but I dont have the piece of paer

**Comment by jared-s05** [comment]
oh ok well apparently I had to kill a mob and I did last time but it didnt give me its item sorry for
the trouble

**Comment by TrashcanMan** [comment]
If your issue is resolved we would appreciate it if you could hit the "Close Issue" button. Thanks!
