### ISSUE TITLE
Lobby Banned turned to a server ban

### ISSUE THREAD

**Issue by jeremiasdk** [Wynncraft/Issues#2606]
hey  wynncraft in got banned in 2014 for fly hack in a lobby 
and why the rules first came in 07-09-2015
if i saw in the rules du not use hack I would not have done this please 
be sweet to say there is a way to unban
kicked whilst connecting to lobby2: you have ben banned reson: do not hack on our servers tag @TKWild in appeal

lobby ban + auto connecting to a lobby=serverban please help

**Comment by GamerGamerFTW** [comment]
As i know, if you can fly in lobby you can fly ingame.

**Comment by SkySaito** [comment]
And even that, it's obvious to not hack on a server. anyway if you want to be unbanned from the servers, do a ban appeal on the forums, and do not beg for it on admin and mod profile. Just do the formal way and after some times, if they accept, you'll eventually play again on Wynncraft.

**Comment by jeremiasdk** [comment]
I buts that when my ban came I was in a lobby
so if I remember it like it is as if I joiner will automatically show I'm banned from the lobby so I side firmly in the lobby

**Comment by AckroWynn** [comment]
https://forums.wynncraft.com/forums/ban-appeals.84/create-thread
Post your ban appeal there. Tag TKWild in there as well.

**Comment by Moe-Ronickah** [comment]
Please close this issue, as it is not bug.
