### ISSUE TITLE
Glitched Quest: Wynn Excavation Site A

### ISSUE THREAD

**Issue by bretonhoover** [Wynncraft/Issues#2607]
so I did the quest normally, get the paper decrypt it, give a tribute, fight the boss. After I fought the boss, there was another person in there, so I helped him do it, for me it was the second time. I go to Vade at the end, and he wants me to decrypt the paper that I don't have! Also while were at it, I still have the santa killing quest, that I didn't finish. Is there a way to get rid of that quest from my book?

**Comment by GamerGamerFTW** [comment]
Try to do /fixquests and, no you cant cancel quests that you have started, if you need help with santa msg me. ;)

**Comment by bretonhoover** [comment]
fixquests doesn't do anything.

**Comment by GamerGamerFTW** [comment]
Just say your IGN

**Comment by xItsNickHD** [comment]
it's still happening.

**Comment by Moe-Ronickah** [comment]
@xItsNickHD , make certain that you have the Yellow Crystal Shard from the boss fight when you go to talk to Vade.
