### ISSUE TITLE
Craftmes Chaos Clicking bug

### ISSUE THREAD

**Issue by omershoplays** [Wynncraft/Issues#2611]
While i was doing the craftmes chaos mission i went back to the present santa and for some reason i cannnot interact with the ncp, i tried to change the server or relog but nothing helps.
just wanted to let you know!

**Comment by DarkDemonDragon** [comment]
What step of the quest are you at? Check your Quest Book to see if you are supposed to talk to Santa at this time.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
