### ISSUE TITLE
Armor

### ISSUE THREAD

**Issue by Hayamaka** [Wynncraft/Issues#2612]
my armor isnt working. For some reason armor has become a problem for me, first my helmet stopped appearing now everything is gone. I gave it a week and a half but to no luck. ;-;

**Comment by GamerGamerFTW** [comment]
Is it like glitched textures or its gone?

**Comment by Hayamaka** [comment]
like you cant see the armor its just skin

**Comment by Hayamaka** [comment]
@GamerGamerFTW you cant see any armor its just skin

**Comment by GamerGamerFTW** [comment]
I have the same problem, it looks like some parts of my armor is missing and my helmet doesnt appear

**Comment by GamerGamerFTW** [comment]
http://prntscr.com/9b0kwk

**Comment by Hayamaka** [comment]
i wonder who we could actually complain to
@GamerGamerFTW

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
