### ISSUE TITLE
Relic Daggers

### ISSUE THREAD

**Issue by iruleyousuck** [Wynncraft/Issues#2613]
Basically I can't identify the Relic Daggers
![2015-12-08_22 06 03](https://cloud.githubusercontent.com/assets/16219003/11677912/e97ea0e8-9df7-11e5-8873-891d2478263d.png)

**Comment by TrashcanMan** [comment]
Known issue, most items with accented characters, along with Relic Daggers, don't identify properly. This should be fixed soon.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!
