### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by CertifiedBunny** [Wynncraft/Issues#2614]
So, I just logged onto my archer, and the world around me wasn't loading at all. My armour loaded on but the world won't. I thought it was just a fluke, so I got off the server and came back on. Nothing changed. So I restarted my minecraft, still no changes. So I decided to check my warrior. Everything loaded fine for my warrior. So, i've been just sitting in this blackness for a good while now. And nothing has changed. Can I have a little help please? Note I've tried changing world's and lobby's. But no change.
Just in case you need this my IGN is CertifedBunny (If it's not obvious)
![help](https://cloud.githubusercontent.com/assets/16219852/11679010/098f6cfa-9e02-11e5-8dde-d03b854082d9.png)

**Comment by CertifiedBunny** [comment]
P.S. I'm not sure if I should've made an account with Github or with Wynncraft... So I did both. Sorry if it's confusing.

**Comment by DarkDemonDragon** [comment]
You've spawned in the black box that you're in when you class change. This is a random bug that happens occasionally. All you can do is /kill to be sent back to spawn or use a scroll. Be sure you have more than 3 SP.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
