### ISSUE TITLE
I just lost a complete set of endgame armor.

### ISSUE THREAD

**Issue by Balancer79** [Wynncraft/Issues#2616]
I was trying to replace my endgame armor to put it on my other class so I can Help my friend fight Death. I put the armor into the chest. Then I tried to go back into the chest and the chest was completely empty. Then it kicked me out of the server and said there was an error. Then I went back into the server and tried to continue my armor replacement when I found that it was gone. 

This is no joke. I lost my only Blue Mask And Stalagmites, all because I wanted to help my friend. I need an Admin to spawn those armors back for me, because they are very valueable. I also lost The Adamantite and Crystal, but the Blue Mask and Stalagmites are why I'm sad. 

Edit: I think it might have been because I removed many of my old friends from my friend list just before I started changing the armor.

**Comment by DarkDemonDragon** [comment]
Was the bank empty or had other items before you placed the armor there? Also there's a random chance where if you open the bank you actually open up the Ender Chest. This causes an error message to occur and you will be automatically kicked to prevent any further glitches. As long as you didn't put your items in the ENDER CHEST everything should be fine. Check the bank again to see if it's there. Remember if something seems wrong the worst thing to do is to move around your expensive items. The main difference between the Bank and the Enderchest GUI is that each is labeled appropriately in the upper left hand corner, the Bank will have all of the previous items you've placed, and the Enderchest will have the vanilla amount of storage (3 rows) while the Bank has whatever amount of storage you've upgraded it to. If this resolved your issue please close this.

**Comment by Balancer79** [comment]
no. When I came back after the error kick, the other stuff was in my chest, but the armor was gone. I click everywhere and there was nothing. If the admins can somehow check by code if the armor is still there, that would be nice, but other than that, it's gone from anything I can do.

**Comment by Balancer79** [comment]
I want my Armor back. This sucks. A stupid glitch ruined my life.

**Comment by DarkDemonDragon** [comment]
I'm sorry but Wynncraft has a strict no-refund policy.

**Comment by Balancer79** [comment]
Wynncraft is flawed!
