### ISSUE TITLE
The Priest, Grave Digger Quest

### ISSUE THREAD

**Issue by Speyrow** [Wynncraft/Issues#2617]
I am experiencing problems with the priest on the grave digger quest at the old cathedral outside Nemract,
I have killed Sayleros' brother and go to give the dusty will to the priest but there is just a blank space that shows up on chat, no steps to complete or anything,
I have tried doing it on a few different servers but still doesn't work and even tried it with the will in my hand, hotbar and inventory.

Is there any way past this or is the bug planned to get fixed anytime soon?

Thanks.

**Comment by Speyrow** [comment]
Pardon me, I got mixed up with who I was supposed to give the will to, thanks, done it now

**Comment by TrashcanMan** [comment]
If your issue is resolved we would appreciate it if you could hit the "Close Issue" button. Thanks!
