### ISSUE TITLE
Kangronomicon - The "Nobody" Glitch + Negative XP

### ISSUE THREAD

**Issue by Dar-krusos** [Wynncraft/Issues#2618]
Kangronomicon is now #77 according to the /guild leaderboard.
![Our rank and name on the leaderboard](http://i.imgur.com/N24bHid.png)

We are also running on negative xp, and our xp was at 90% when it turned into negatives.
![Our XP prior to bugging](http://i.imgur.com/RK1YrQV.png)

Hope you can fix this swiftly.
Regards,
     Krusos, of the Name Dar

**Comment by DarkDemonDragon** [comment]
I made an issue about this too. #2584 
Check if your /guild stats is also bugged.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Dar-krusos** [comment]
No, the problem has not been resolved and still persists. The Update did not change this bug in any way.

**Comment by Trixter313** [comment]
That's unfortunate. Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
