### ISSUE TITLE
Already in guild glitch

### ISSUE THREAD

**Issue by superdswimmer** [Wynncraft/Issues#2619]
So a few weeks ago i had a plan to go visit adventures with hippies guild but i was in kangronomicon, so what i did is i left kangro to try to join but it said i was in a guild. ive had people in kangro see if i was still in the guild and i was, then they kicked me out but it said "player is not in the guild." we have tried that and ive waited almost a month now just incase it needs to update but that doesnt seem to be the problem. if you could please help me a soon as possible that would be great and if you need my username it is superdswimmer and if you need any other info please ask.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by superdswimmer** [comment]
Yes as a matter of fact it is still happening since gavel like I said its been happening for 2 months including gavel.
