### ISSUE TITLE
I get stuck in a tree (no kidding)

### ISSUE THREAD

**Issue by mtbdv02** [Wynncraft/Issues#2620]
Buenas, Me quede atorado en un arbol cerca del castillo con mi habilidad de teletransporte y no puedo salir y no quiero cambiarme de clase porque es mi preferida y quiero salir pero no me deja porfavor ayudenme!

**Comment by TrashcanMan** [comment]
/kill con al menos tres puntos del alma
/kill with at least three soul points

**Comment by Trixter313** [comment]
Si su problema se ha resuelto, le agradeceríamos si ha cerrado el tema. Si no es así, estaremos encantados de seguir ayudando a usted tanto como sea posible. Gracias y esperamos que disfrute de su tiempo de juego Wynncraft! :)
