### ISSUE TITLE
I can't change my name on the forums

### ISSUE THREAD

**Issue by King-Wasabi** [Wynncraft/Issues#2621]
My old username used to be King_Wasabi666 and when the name change update came out I switched to plain old King_Wasabi. When I changed my name in the forums to King_Wasabi the change didn't switch over and I am stuck with King_Wasabi666.

Any tips on how to fix that?

**Comment by TrashcanMan** [comment]
You could just try changing it again. You can change your forum username as many times as you like but there's a 90-day delay between changes.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by King-Wasabi** [comment]
Thanks! Sorry. I forgot to close the issue. It worked.

**Comment by Trixter313** [comment]
Good to hear!
