### ISSUE TITLE
Can't talk to quest NPC 

### ISSUE THREAD

**Issue by KREISI88** [Wynncraft/Issues#2623]
So I've tried to talk to this one quest NPC and I've logged in over and over again and changed servers but I still can't talk to them.
This is before right click:
![nimeton](https://cloud.githubusercontent.com/assets/16261511/11757267/aa9e2e02-a068-11e5-9e3b-10b258411710.png)
And this is after right click:
![2](https://cloud.githubusercontent.com/assets/16261511/11757274/b7cb0e74-a068-11e5-9081-b0e5c454112c.png)

**Comment by DarkDemonDragon** [comment]
Could you please back up a bit so we can see the NPC's name? XD Either that or provide coordinates. Make sure to check your quest book that you're supposed to talk that NPC at this time.

**Comment by KREISI88** [comment]
@DarkDemonDragon oh nevermind I watched video of it and it was old xD

**Comment by DarkDemonDragon** [comment]
Alright then. Please close this issue if you have no further problems. (At the bottom there is a close issue button)
