### ISSUE TITLE
Lord of the Clock

### ISSUE THREAD

**Issue by PixlCraftr** [Wynncraft/Issues#2624]
I was making the Quest "Lord of the Clock" and I talked to Frudo when Gullum kicked me down in the Lava. Frudo stopped at sentence 2/4 and now the Clock has vanished from my inventory and I cant talk to Frudo anymore...

**Comment by TrashcanMan** [comment]
Have you tried /fixquests?

**Comment by PixlCraftr** [comment]
found a mod ingame who told me, but thanks anyway, its working fine now :)
