### ISSUE TITLE
XP WynnExcavation Site C

### ISSUE THREAD

**Issue by Tieskee** [Wynncraft/Issues#2625]
So a few months ago (Yes I know I haven't been playing wynn for a while) I did the quest ''WynnExcavation site C'' But I didn't get the xp for it! I guess that's why I stopped playing wynn for a while. Anyways can this bug be fixed soon, and am I getting my xp anyways? Because I'm a mage lvl 55 and I really want to level up!

Thanks for reading this, I hope I get a fast response :)

-Ties

**Comment by Seberichsen** [comment]
/guild xp 0 try it out you might have ben giving all xp to your guild

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
