### ISSUE TITLE
You cant attack!

### ISSUE THREAD

**Issue by iTurtelzz** [Wynncraft/Issues#2628]
So today me and some friends where playing and we discovered we were not able to hit with out weapons but we could do some spells so yea how am i suppose to kill bob with my firsts?( you can attack with other items only not your weapon)btw my mc name is iturtlez am also in server 21

**Comment by Moe-Ronickah** [comment]
If you were in a duel with any player, by accident or by intent, then no, you cannot hit mobs.  The mobs, on the other hand, can hit you.  If your issue has been resolved, please close this issue.
