### ISSUE TITLE
A Question, not an issue

### ISSUE THREAD

**Issue by Ghost88788** [Wynncraft/Issues#2629]
I repeat, this is a question, not an issue. Okay, we got this over with, now for the question. If you buy VIP+, do you get the items for VIP too, or only VIP+?

**Comment by Krallorddark** [comment]
You Get The Both

**Comment by Krallorddark** [comment]
I guess becaouse ın Store It says in VIP+ Has: 
+ All VIP bonuses.
+ VIP+ reserved slots.
+ Skeleton Horse Cloak.
+ All available Dye Kits.
+ Ride your pets.
+ Slap & rocket in lobby.
+ 5 Party, 2 Item & 1 XP Bomb.
+ 7 Global Shouts.
+ Cyan name.
+ OST Jukebox.
+ Attack animations

**Comment by Ghost88788** [comment]
ok, thank you
