### ISSUE TITLE
Invisible Guild Messages, War Messages and Weird Guild Bugs

### ISSUE THREAD

**Issue by HelioPlayz** [Wynncraft/Issues#2632]
When you are in a guild, for me I get a bug where I can't see anything my guild types in chat, nor can I see any war announcements for the guild. I have to leave and rejoin to see them again. However this has happened to me multiple times.

Also when I sometimes try to rejoin my guild I get this 
https://gyazo.com/e2222047ca750635f04a7c23a0f8d126

and sometimes it works but then I get this:
https://gyazo.com/93129cb1db001e2c4ce50cba8da777f3

Thanks!
-HelioPlayz

**Comment by HelioPlayz** [comment]
Also, could you message me on forums when this is fixed so I can rejoin my guild? ty

**Comment by DarkDemonDragon** [comment]
Yea literally every guild is having this issue, so the staff are aware of the situation. Just be patient and sit tight while they fix it :)

**Comment by Trixter313** [comment]
Are you still having this issue since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
