### ISSUE TITLE
Jungle Fever LE Glitch

### ISSUE THREAD

**Issue by Amaranthix** [Wynncraft/Issues#2634]
I was playing on my Assassin doing the Jungle Fever Quest, and I had 5 normal LE in my inventory for convenience purposes. When I finished the quest, all of my LE I had turned into the Almuj Quest Item LE, and there was one normal LE left. I don't know if this was a glitch or not because I don't think I can use the Quest Item LE when, before I finished the quest, it was 5 normal LE. 

Here's the screenshot after I completed the quest.

http://i.imgur.com/BXE3cwr.png

**Comment by Trixter313** [comment]
Does /fixquests do anything for you? Wynncraft has a strict no refund policy so getting the lost LE back probably won't happen but the issue of those 5 quest LE's that you can't get rid of is quite annoying. Hopefully this works!
