### ISSUE TITLE
Jungle Fever Quest Glitch

### ISSUE THREAD

**Issue by KODY41704** [Wynncraft/Issues#2635]
I was doing the Jungle Fever quest like any normal level 52 would do. I had 2 liquified emeralds on me. I finished the quest and I get one liquified emerald and Exp to get me half way for leveling up. But I look in my inventory and I see my liquified emeralds are in different places, so I check the 1 liquified emerald and it is a normal one, then I check the other 2 and they are called Almuj liquified emeralds, so I go to Detlas and try to get the emerald blocks doesn't work so can you please fix this glitch and give me my 2 liquified emeralds? I worked hard for those emeralds.
After the quest: http://imgur.com/0yAz8X0

**Comment by GalacticPhantom** [comment]
As mentioned in the quest on wiki it stats that players should remove any Le to prevent glitches like this from happening

**Comment by KODY41704** [comment]
I wish I would have know that before I did that. But could I still have my 2 Le back?

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strict no refund policy so getting those LE back probably won't happen. I suggest enjoying and playing the game and you'll find the 2LE is gained back pretty fast. =)
If you don't mind, we'd appreciate it if you closed this issue now. Thanks!
