### ISSUE TITLE
animal dungeon boss reset

### ISSUE THREAD

**Issue by nyehee** [Wynncraft/Issues#2636]
every time me and my friend scott defeate the animal boss
he always dissapears for a second and reapears with full hp
hopefuly this is a glitch because then me and my friend scott could never beat the animal dungeon

**Comment by DarkDemonDragon** [comment]
This is a frequent bug that occurs a lot in the animal dungeon. The recommendations have been to not kill with a knockback attack or drive the boss into a corner.

**Comment by nyehee** [comment]
thank you

**Comment by nyehee** [comment]
um
wynncraft says cant connect to server can you please help?

**Comment by Trixter313** [comment]
Are you still having this issue since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
