### ISSUE TITLE
My le Pelier can't be identified

### ISSUE THREAD

**Issue by GGMARVEL** [Wynncraft/Issues#2637]
I got a pelier  during killing monsters. But when I tried to identify, it says it is common items such as Jungle wood bow.

**Comment by TrashcanMan** [comment]
Duplicate of #1312, many items with accented characters do not identify properly. This should be fixed soon.

**Comment by Trixter313** [comment]
As TrashcanMan said, this is a duplicate. We recommend closing duplicates and following the original to stay updated on the status of the issue. Thanks!
