### ISSUE TITLE
Whats wrong with Wynncraft??

### ISSUE THREAD

**Issue by SteveClinton** [Wynncraft/Issues#2638]
In the last time there are only lags and bugs! I cant do /hub, if i leave i cant join anymore.... and the best thing: i lost my chestnut because of a stupid bug -.-!  Great!

**Comment by SteveClinton** [comment]
Also i cant type in guild chat anymore...

**Comment by TrashcanMan** [comment]
If you have multiple issues, please make separate posts for each of them. That said:
What do you mean by "I can't join anymore"? Are you permanently unable to log onto Wynncraft?
Wynncraft has a strict no-refunds policy, so unfortunately you're not getting your horse back.
If you have changed your username, you may be experiencing problems with guilds. If not, guilds are known to be very buggy at the moment, and should be patched when Gavel comes out.

**Comment by GalacticPhantom** [comment]
If I am not wrong Ops on wynncraft have reduce the amt of players joint rate to allow their team to test Gavel more efficient besides if you manage to log into wynncraft itself it will be v laggy

**Comment by TrashcanMan** [comment]
@GalacticPhantom I am fairly certain that Gavel testing and whatnot is done on the developer server, which is separate from the server everybody else plays on.

**Comment by Trixter313** [comment]
Have any of your issues been resolved since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
