### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by blackmagic9988** [Wynncraft/Issues#2639]
When I try to join the server it's kicks me saying "Failed to connect to server" "Java.net.ConnectException: Connection refused: no futher information:" what can I do to be able to get on and play :(

**Comment by PineappleEcho** [comment]
I'm having the same problem and I cant fix it no matter what I do.

**Comment by blackmagic9988** [comment]
I still am unable to connect for the same reasons and now i think the server might have gotten DDOSed

**Comment by TrashcanMan** [comment]
It's probably not DDOS, it's more likely just routine maintenance. Wynncraft servers go down every so often for maintenance, if it happens, just wait an hour or two and try again.

**Comment by Trixter313** [comment]
Can you connect now since the update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
