### ISSUE TITLE
trying to connect Minecraft name to forum account, game returns can't authorize this account

### ISSUE THREAD

**Issue by seanschilling** [Wynncraft/Issues#2640]
Hello, I'm trying to use the /forum command to connect my forum account with my Minecraft account to gain access to the VIP section of the forums. When I type "/forum Seanofthedead", the game returns "We can't authorize this account, try again later". I can provide proof that I bought VIP plus if needed.

thanks

IGN: Seanofthedead0
forum name: Seanofthedead

**Comment by TrashcanMan** [comment]
/forum is super broken right now, and has been broken for a while. It should be fixed soon, but all the devs are busy with Gavel right now.

**Comment by Trixter313** [comment]
Are you still having this issue since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
