### ISSUE TITLE
Disconnected?

### ISSUE THREAD

**Issue by woodie2013** [Wynncraft/Issues#2642]
For some weird reason everytime I try to connect it always disconnects me, is it because I live in Australia or something?

**Comment by GalacticPhantom** [comment]
If I am not wrong Ops on wynncraft have reduce the amt of players joint rate to allow their team to test Gavel more efficient besides if you manage to log into wynncraft itself it will be v laggy.
Correct me if I am wrong

**Comment by Trixter313** [comment]
Are you still having this issue since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
