### ISSUE TITLE
Chest in Ice Biome which you CAN'T open :( 

### ISSUE THREAD

**Issue by merac419** [Wynncraft/Issues#2643]
Hey guys!
I walked around the mountains of the "Tower of Amnesia" and found a hidden chest at -193 86 -271
BUT I wasn't able to open it because there's a block on top of the chest ;(
Would be great if you change it =)

**Comment by GalacticPhantom** [comment]
Is the chest a loot crate?
If no you can't open it if yes there might be a bug

**Comment by Trixter313** [comment]
Are you still having this issue since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
