### ISSUE TITLE
Guilds are bugged again

### ISSUE THREAD

**Issue by DetlasMaster** [Wynncraft/Issues#2644]
Hey, I would like to report a problem about guilds.

I can't guild chat, I can't contribute XP, I dunno what's wrong! Is it something to do with bugs? Or is it just me?

**Comment by TrashcanMan** [comment]
Guilds are known to be incredibly buggy in the past few months, this should be fixed sometime after Gavel when the devs have some time. Also if you've changed your username that may be causing problems as well.

**Comment by DetlasMaster** [comment]
Guild chat used to work and now it doesn't.

**Comment by Trixter313** [comment]
Are you still having this issue since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
