### ISSUE TITLE
Class selection issue

### ISSUE THREAD

**Issue by luminytz** [Wynncraft/Issues#2645]
I've tried to play as Archer class today, i selected Archer class on class selection menu and warped me to this black room. I assume its class selection room (?) i cannot do anything right now and i really need to warp out of this place.

**Comment by TrashcanMan** [comment]
If you have at least 3 soul points do /kill.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by luminytz** [comment]
I have tried doing /kill before, it does not really do anything.
