### ISSUE TITLE
Lobby Escape....

### ISSUE THREAD

**Issue by BlueNova117** [Wynncraft/Issues#2647]
So i got out of the map but you need to be able to fly. (VIP, VIP+, MOD, Builder, GM)

when you spawn in on your right the very first mountain you have to fly above (as high as you can go) and there will be a 1 block gap that you can leave threw.. from there you can make your way away from the lobby... and find the other lobby's.
Ill be honest i did leave the area and go to the old lobby's but i'm reporting it now so it cant happen again... the main reason why i left the map is to help out by finding bugs like this one.

**Comment by Trixter313** [comment]
Is the gap still there in the new holiday lobby?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by BlueNova117** [comment]
Yes  it's still there and I just realized that it's between the two mountains and you have to go to the very top of the map to leave the area.

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
