### ISSUE TITLE
Skill Points

### ISSUE THREAD

**Issue by FredDigger** [Wynncraft/Issues#2648]
When you have skill points and you level up you loose them.

**Comment by DarkDemonDragon** [comment]
Please provide some pictures or video to show this happening.

**Comment by Trixter313** [comment]
Are you still having this issue since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
