### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by ImperialMarshal** [Wynncraft/Issues#2649]
All of the servers are being bugged. It doesn't show your levels, you lost your items, and you start at the very beginning of where you spawned. You can't enter the city, and your hunger gets drained. You lose hearts and we can't do anything. This won't be permanent, but please do your best to make sure this won't happen again. Thank you, Imperial_Marshal

**Comment by Trixter313** [comment]
Are you still having this issue since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
