### ISSUE TITLE
Old Player and emeralds broken...

### ISSUE THREAD

**Issue by destroyerdj135** [Wynncraft/Issues#2650]
I come back after several long months and now all my emeralds don't work because it was deiced to put a description on emeralds.... I have over 7 stacks of 64 blocks and 11 liquid emeralds i traded for and worked for in good old days and now its all gone..... Any help please I'm begging in game name is destroyerdj135

**Comment by TrashcanMan** [comment]
There is a converter merchant in Selchar's bank who will turn your old emeralds into new functional ones. If this fixes your problem please hit the "Close Issue" button. Thanks, and have a nice day!
