### ISSUE TITLE
glitched horse

### ISSUE THREAD

**Issue by TheSourceOfHope** [Wynncraft/Issues#2651]
My black 10/10 horse disappeared, but I legitimately bred that horse. Is there a way to get it back without have to breed a new one?

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strong no refund policy so not much can be done about it. There's no way we can tell whether it was a server issue or a player issue such as just accidentally dropping it. If you wouldn't mind, we'd appreciate it if you closed this issue. Thanks!
