### ISSUE TITLE
Stuck in the class room

### ISSUE THREAD

**Issue by jonne3008** [Wynncraft/Issues#2652]
I am stuck in the room where you choose your class. I won't get teleported away.
![2015-12-19_10 53 49](https://cloud.githubusercontent.com/assets/16360618/11912513/25ebbcdc-a640-11e5-97cd-1d94ed2af15e.png)

**Comment by jonne3008** [comment]
I can't use a telportation scroll either.

**Comment by jonne3008** [comment]
Nevermind /kill worked. But you guys need to fix this.

**Comment by Trixter313** [comment]
Are you still having this issue since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
