### ISSUE TITLE
i can't connect to the server even with my other accounts.

### ISSUE THREAD

**Issue by Alteyr** [Wynncraft/Issues#2653]
Hello,as the title say,i have a problem when it's time to connect to the server.
Here's a screen : 
http://hpics.li/367eb0b

I don't understand,both of my accounts are premium.
Hope i can have an answer for this,

Thanks :P,

SaitamaOPM.

**Comment by karel5123** [comment]
i have the exact same problem, with the same error as on your screenshots

**Comment by Trixter313** [comment]
Are you still having this issue since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
