### ISSUE TITLE
On mission "Grave Digger" I cant give "The Priest" The Dusty Will" Read Below...

### ISSUE THREAD

**Issue by ElliotRain** [Wynncraft/Issues#2654]
When I try to click "The Priest" It does not take the will not award me with the ending of the mission. Instead it just comes up with a blank chat there is some kind of output but its unreadable... (See screen shot) ![2015-12-19_18 19 04](https://cloud.githubusercontent.com/assets/16320281/11914613/08ef0ca0-a67d-11e5-9e54-1bb2b59b1b6f.png)
Thanks,
Yours SoRainyYT AKA Rainy

**Comment by TrashcanMan** [comment]
The Dusty Will is supposed to go back to Sayleros in Detlas. If your issue is resolved, please hit the "Close Issue" button. Thanks, and have a nice day!
