### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by brendon96068** [Wynncraft/Issues#2656]
If i refresh my server page it says there are people online but it won't let me log in it keeps saying either "Couldn't find a server to log into, please report" or it says some weird stuff that i cant really type it all, please help

**Comment by Cupcakesncream** [comment]
I'm having the same problems. :(

**Comment by Trixter313** [comment]
Hopefully this will be fixed when the server gets back up from the Gavel update!

**Comment by Trixter313** [comment]
Are you still having this issue since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by tacticalsk8er** [comment]
I am still having this problem.

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
