### ISSUE TITLE
WynnExcavation Site C

### ISSUE THREAD

**Issue by Topslice** [Wynncraft/Issues#2658]
Hello, I currently having issues with this quest. I have the purple crystal shard and I have tried talking to the npc and it said "I still need to get the purple shard from Excavation B." I have tried fix quest and it didn't work. Does anyone have a answer for this problem?

**Comment by Trixter313** [comment]
There are two different purple shards I believe, one that says quest item and one that doesn't. I think the one that says quest item is the one you need. Is that the one you have?

**Comment by dogelord117** [comment]
This issue occurs after you finished the quest. You only need the purple shards to start the quest, which we already did.

**Comment by Trixter313** [comment]
If your issue is still occurring, please first make sure someone else hasn't posted it already, and if no one has, repost the issue. A massive closing sweep was done to clear out all of the already fixed issues. Thanks!
