### ISSUE TITLE
Emerald block disappear in bank

### ISSUE THREAD

**Issue by TWSgearX** [Wynncraft/Issues#2660]
Originally I have one set of emerald block in my bank. But 10 minutes later, when I check my bank. The set of emerald black disappeared.

**Comment by Trixter313** [comment]
Wynncraft has a strict no refund policy so there's not much that can be done here. After a little bit of time you should gather enough emeralds to replace that block, and more! Just enjoy playing the game and it'll happen =)
We'd appreciate it if you closed this issue. Thanks!
