### ISSUE TITLE
Lost Quest Item...

### ISSUE THREAD

**Issue by Darkdragon902** [Wynncraft/Issues#2663]
My brother Firemaster39 was doing the Wynn Excavation Site A quest and he was up to the part where you have to get the translated paper back from the person in the tent. When Firemaster39 talked to the NPC, it didn't give him the paper. He tried /fixquests but it didn't work. It is also not in his bank. Is there any way to fix this? He can't finish the quest now.

**Comment by Trixter313** [comment]
Hmm, this might require an admin or moderators' help. Keep this issue open and it should be seen by someone who can help. Good luck!
