### ISSUE TITLE
I got out of bounds

### ISSUE THREAD

**Issue by Syio** [Wynncraft/Issues#2664]
And don't ask How I got out of bounds I don't know I flew up between one of the mountains and must of glitched out http://i.imgur.com/3i0CEUr.jpg?1

**Comment by Trixter313** [comment]
Can you still escape since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
