### ISSUE TITLE
WynnExcavation Site A BUGG

### ISSUE THREAD

**Issue by mvcuijk** [Wynncraft/Issues#2665]
So me and my friend are doing the quest WynnExcavation Site A but when i want to talk with Tesh in the tent lab notthing happens and my quest book will not update. And when my friend does it Update so ithink the quest is bugged for me u can see it here:
https://gyazo.com/1a93432b026ca8f909c3d579e7a5aa76
every time i get this think and it will not update i tried so much things.

I hope u guys can help me

**Comment by Trixter313** [comment]
Are you still having this issue since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by mvcuijk** [comment]
Hi @Trixter313  its still not fixed so i hope someone can help me with it

**Comment by Trixter313** [comment]
Hmm, have you tried using the command /fixquests ?
