### ISSUE TITLE
Relic Wand is saying it is an assassin/ninja weapon

### ISSUE THREAD

**Issue by Lake902** [Wynncraft/Issues#2666]
http://imgur.com/jFywkWB

**Comment by Trixter313** [comment]
Thanks for the bug report! Hopefully this will be fixed soon!

**Comment by Trixter313** [comment]
Some users are saying it's now fixed. Can you confirm?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
