### ISSUE TITLE
Lost my Chestplate and Boots to Item Identifier?

### ISSUE THREAD

**Issue by TheyCallMePinkXD** [Wynncraft/Issues#2667]
I just got into the new wynncraft server and I was identifying my armor and I lost my chestplate and boots to the item identifier. No, they did not drop on the ground nor are they in my inventory. I have no clue where they went. What happened?

**Comment by Trixter313** [comment]
It's hard to tell what happened exactly but Wynncraft has a strict no refund policy so not much can be done. We'd appreciate it if you closed this issue. Thnaks!
