### ISSUE TITLE
I can't use my weapon anymore :(

### ISSUE THREAD

**Issue by Nelroby** [Wynncraft/Issues#2671]
I love the new Gavel xpac, but I can't use my relic spear anymore...... I identified it and it is now only usable for Assassins and Ninja's :(. Please help me.

**Comment by Hoquen** [comment]
Same here my relic wand turned into an Assassin/Ninja weapon. Have you tried getting a new one?

**Comment by Nelroby** [comment]
No, I kinda can't. I'm supremely weak now

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/2666

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!
