### ISSUE TITLE
Cinfras Identifier Not Present

### ISSUE THREAD

**Issue by MedievalBladeRPG** [Wynncraft/Issues#2674]
I checked on four different worlds and he is absent on all of them, screenshots included.
![2015-12-21_01 11 31](https://cloud.githubusercontent.com/assets/16379066/11924532/1d374fd4-a780-11e5-80f6-83d04415613a.png)
![2015-12-21_01 11 41](https://cloud.githubusercontent.com/assets/16379066/11924531/1d360a34-a780-11e5-8b5e-4208813a15c6.png)
![2015-12-21_01 11 44](https://cloud.githubusercontent.com/assets/16379066/11924530/1d3469e0-a780-11e5-9f8c-f3e7247a5c35.png)

**Comment by Trixter313** [comment]
Are they still missing now? Sometimes these issues just need a little time.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
