### ISSUE TITLE
Identified Item with +400% Stat Increases

### ISSUE THREAD

**Issue by wetherae** [Wynncraft/Issues#2675]
I went to identify a normal wand, expecting a small increase in stats, but when this came out, I was really surprised and thought it was a bug in the text, but I tried it on a level 10 zombie assassin outside of Ragni, which promptly got one-shot.

http://i.imgur.com/RghQzZV.png

**Comment by Trixter313** [comment]
This does seem like a bug! An admin should see this soon and hopefully fix it soon also.
