### ISSUE TITLE
Lost armor

### ISSUE THREAD

**Issue by Deggazomboe** [Wynncraft/Issues#2676]
Gavel came out and as I was identifying my armor I lost all of my armor, and one was glitched.  My helm was pelier, my chest was mummy's rags, my legs I don't know the name of but they were level 40 rare, and boots were neanderthal.  If I could get them back that would be much appreciated, I was very disappointed to see this update mess something up that bad.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strict no refund policy so not much can be done here. We'd appreciate it if you closed this issue. Thanks!

**Comment by Deggazomboe** [comment]
Okay, that's fine, I pretty much have better armour now.  Thanks for the
response.
