### ISSUE TITLE
lost 3/4 parts of my armor

### ISSUE THREAD

**Issue by luka0033** [Wynncraft/Issues#2678]
Hello
My ign is xTerror_HD and I lost 3/4 parts of my champions armor for my lvl 75 assasin. I only got the helmet.
I hope you can fix it and I become my armor back :D
Btw I love Gavel :3
xTerror_HD

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strict no refund policy so not much can be done. We'd appreciate it if you closed this issue. Thanks!
