### ISSUE TITLE
Old Id'd weapons unable to be re-id'd and are broken

### ISSUE THREAD

**Issue by Jacoblouis13** [Wynncraft/Issues#2679]
firstly id like to say lovely update! thanks for all the great work! while the launch was smooth, there are a number of things that must be fixed D: one of them is that when i first logged into wynn, i noticed that all my armor had been unidentified except for my spear, Fierte (i think that is how it is spelled). it has all of the old ID's and i cannot re-ID it. it says Something along the lines of "sorry, you can only identify items that are unique, rare etc... I can not use that weapon at all so it is currently gathering dust in my bank. hopefully something can be done to fix this! thank you for reading and for all of Gavel!

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully be able to help.

**Comment by Trixter313** [comment]
A user reported that this issue is fixed. Can someone else please confirm?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by iCreativity** [comment]
I found a weapon, that didn't convert, in the new format, just without accents:
![2015-12-23_00 07 38](https://cloud.githubusercontent.com/assets/14164385/11968202/ea0d8de0-a909-11e5-96f1-08747899cd73.png)

**Comment by iCreativity** [comment]
No, actually, the staff completely broke after a while, I don't know why:
![2015-12-23_00 48 49](https://cloud.githubusercontent.com/assets/14164385/11968680/1be67782-a90f-11e5-9e94-80bcc3e6880a.png)

**Comment by EPICB3N** [comment]
![2015-12-22_22 56 19](https://cloud.githubusercontent.com/assets/14899119/11970829/9f2a790a-a8ff-11e5-9d5d-ea3d326209b3.png)
thing is I cant use it

**Comment by Trixter313** [comment]
I guess it isn't totally fixed yet then. Hopefully it get's fixed soon!

**Comment by Inter1tum** [comment]
My weapon is not converted yet, it still has old IDs etc. and I can't use it. 
![kozdaqc](https://cloud.githubusercontent.com/assets/16384190/11975439/79436df6-a976-11e5-9dd9-d6cdac384229.png)

**Comment by DarkSamus9000** [comment]
This happened to me, too. It seems to be consistent with certain items, like Tarnhelm, Montefiore, and Fierte for instance: http://prntscr.com/9gxaeg

**Comment by iCreativity** [comment]
I found a fixed Dévoreuse.
![2015-12-21_22 33 36](https://cloud.githubusercontent.com/assets/14164385/12006997/7fef1468-abef-11e5-899e-ead05e587a21.png)
