### ISSUE TITLE
Wand for assassin class?

### ISSUE THREAD

**Issue by Vamacheron** [Wynncraft/Issues#2683]
So, I logged on to Wynncraft right after the Gavel update and I see that I need to identify my stuff to use it, ok I identified my Relic Wand to see that it is an assassin item... Please fix this error, I had to use a depressing stick to start of
![2015-12-21_08 13 09](https://cloud.githubusercontent.com/assets/16380231/11925874/fa057e2e-a7bf-11e5-9980-d2057e556261.png)

**Comment by Vamacheron** [comment]
Ok they fixed it

**Comment by Trixter313** [comment]
Good to know they fixed it!

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
