### ISSUE TITLE
I am having trouble playing wynncraft after the Update

### ISSUE THREAD

**Issue by LeeJoochan** [Wynncraft/Issues#2684]
Hello, My In game name is Zykuu_, and I am having alot of issues playing wynncraft. First of all, When I get the texture pack, I get 20+ Lag spikes Every Minutes. I dont know why, but I wish I can play without the texture pack or anything. Also After joinning the server, I lost all my armour that I was wearing, after few lag spikes and a Kick from server ( You got disconnected ). I've been playing this server for  a little long, I love wynncraft and I wish I can play again. This server is all I play.. I am not joking about this, or acting like it so that i can earn something from Wynncraft but All I want is a fix so that i can start again. Please Help me

**Comment by Trixter313** [comment]
Once the servers start dying down and getting more stable your issues might go away. For now I'd suggest trying to get on the least crowded world you can.
