### ISSUE TITLE
Identify glitch

### ISSUE THREAD

**Issue by LegendOfTheCreep** [Wynncraft/Issues#2687]
So when the update came out, I was teleported to the update room, like everyone else, but my ID on my helmet from pre-update didn't get removed so now I can't identify my helmet and i am stuck with 6%  xp bonus and 8% spell dmg

**Comment by greenbeast001** [comment]
i have the same problem my fierté has a locked 0.6 health regen pls help me i need that weapon

**Comment by Trixter313** [comment]
This seems to be a variation of #2679

We recommend closing the duplicate and instead adding any comments the the original issue. Thanks!
