### ISSUE TITLE
i LOST my ARMOR help !!

### ISSUE THREAD

**Issue by 7asoOonyi14** [Wynncraft/Issues#2688]
when gavel came out i was excited , entered an world , with the new resource pack , then i knew that i need to identifie my armor and weapon , so i was wearing an unidentified armor , when i picked the helmet { my armor was end game armor } my leggens  armor and boot dispared , and in the chat it said with red color { YOU cant use stuff that arent identified } OK OK , but my ARMOR , i spent alot of le to get it , and worked hard ! , what i think it should have done is to put my armor in my inventory , BUT my inventory was full , so it didnt DROP my armor , it just removed them ! , and some how now i only have my chest plate and helmet , please give me back my crystal and the boot , i forgot what its name !

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strict no refund policy so not much can be done. We'd appreciate it if you closed this issue. Thanks!
