### ISSUE TITLE
Missing Villagers?

### ISSUE THREAD

**Issue by Moistful** [Wynncraft/Issues#2689]
I think there was supposed to be villagers put into place but never put there.. there are many redstone blocks with signs on them saying what they should be. 
The location is the area behind the mountain behind the guild hall. The coords are x -207 y 84 z -4939.

I know this isn't really a bug but I didn't know where else to post this. 

![missing1](https://cloud.githubusercontent.com/assets/16380942/11926623/e95ee6de-a78b-11e5-8fa4-9c2ad2a6d069.png)
![missing2](https://cloud.githubusercontent.com/assets/16380942/11926629/f2f54c4c-a78b-11e5-99af-f99d6f431de8.png)
![missing3](https://cloud.githubusercontent.com/assets/16380942/11926632/f8639af8-a78b-11e5-9acd-939e58e6eb5b.png)

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
