### ISSUE TITLE
Royal Token of Gratitude

### ISSUE THREAD

**Issue by TheResonant** [Wynncraft/Issues#2690]
Well i was buying the necklace from the royal token of gratitude, and i slipped and sold it to the item buyer, i was wondering if i could get the royal token back. if not ill work towards it on my assassin, but here is the screenshot text of me selling it.
![2015-12-21_04 01 53](https://cloud.githubusercontent.com/assets/16381614/11927354/faf06c16-a799-11e5-8982-daafa4c041a6.png)

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strict no refunds policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
