### ISSUE TITLE
Identifier stole my Armor!

### ISSUE THREAD

**Issue by CaptainFight** [Wynncraft/Issues#2691]
Hello Wynncraft team , i was happy that gavel came out so i logged in in my Archer acc. then i got teleported to the Update room like everyone else. i had Unindentifierd Armor. so i taked my Emeralds (17 EB) and Identifierd my Helmet. Then he just stole my Chestplate, Leggings, and Boots and my Climbing Helmet

What should i do now?

**Comment by ITheWolfyzI** [comment]
The same happened to me, it would be great if we could get our armor back

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
