### ISSUE TITLE
Quest cooking assistand reward bug?

### ISSUE THREAD

**Issue by Snappedmetal** [Wynncraft/Issues#2694]
So when the gavel update came out i started new class (assasin) and found a problem about Cooking assistant quest.Because of the new mana potion lvl requirement you get lvl 40 mana potion and i dont think i should be like that because its like 4th quest in start and you probably will be lvl 5 or 6.

Problem:Quest reward lvl is too high

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
