### ISSUE TITLE
Weapon Identification

### ISSUE THREAD

**Issue by zekrom74** [Wynncraft/Issues#2696]
My stabsand is not re-identifiable and it's now currently stuck at it's old state. BOTH my stabsands are stuck in this state where it shows the stats that were there in the past and not showing that it in unidentified. Due to this, I cannot use any weapons on my assassin.

**Comment by zekrom74** [comment]
by the way i still have the stabsands on the account, so i can show it and prove that it's there and that i cannot use it atm

**Comment by zekrom74** [comment]
i can identify it now :)

**Comment by Trixter313** [comment]
That's great to hear! Have a wonderful day!
