### ISSUE TITLE
Fire Wire: No Attributes

### ISSUE THREAD

**Issue by bnmaz** [Wynncraft/Issues#2697]
The Leggings from the quest "from the mountains" Called fire Wire Have no Level cap, Defense Etc etc.
![2015-12-21_10 57 29](https://cloud.githubusercontent.com/assets/16383235/11929390/674bdc28-a7d2-11e5-9287-ec438fa3f8cf.png)

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
