### ISSUE TITLE
I Cant use my skills :c

### ISSUE THREAD

**Issue by Tomipoika11** [Wynncraft/Issues#2700]
I joined to server, and there was this update place were i was, and i needed to identify my weapon, but i cant because my weapon is 'Relic Daggers' so its legendary and Untradeable item :c So i teleported to Ragni and tried to use my Vanish spell so i can go explore new map. but i cant use any my spells, it wont say why but i think because i didn't identify my weapon.

**Comment by Trixter313** [comment]
This seems to be a variation of #2679

We recommend closing the duplicate and instead adding any comments the the original issue. Thanks!
