### ISSUE TITLE
 Relic Daggers not updating

### ISSUE THREAD

**Issue by EdamCheese** [Wynncraft/Issues#2701]
This could already be known, but the relic daggers don't update to the Gavel versions and instead stay as they were before. I believe Salted was talking about something similar in a shout before and it is something to do with a spelling mistake on the updating-code.

**Comment by Trixter313** [comment]
This seems to be a variation of #2679

We recommend closing the duplicate and instead adding any comments the the original issue. Thanks!

**Comment by EdamCheese** [comment]
I believe it probably is, but has been fixed in the patch earlier.

**Comment by Trixter313** [comment]
Great to hear!
