### ISSUE TITLE
Liquefied Emerald throwing glitch is back

### ISSUE THREAD

**Issue by Dar-krusos** [Wynncraft/Issues#2703]
As the title says, right-clicking with a Liquefied Emerald removes it entirely from your inventory.

**Comment by DarkDemonDragon** [comment]
Drink? You know they're throwable items not drinkable items. Also, if you're lagging this happens as the system can prevent you from throwing it in time. In general just DON'T have LE in your Inventory and having them in your hotbar is completely unnecessary other than to easily show them off. If you're doing that, then karma just hit you.

**Comment by Dar-krusos** [comment]
Or.....
Or or or karma didn't hit you and you just did a quest.

**Comment by DarkDemonDragon** [comment]
What quest requires LE o.O

**Comment by keviny3** [comment]
It happened to me shortly after completing the Jungle Fever quest.
I was walking in Troms and I accidentally threw it when talking to an Emerald Merchant.
BOOM!
REKT!

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.

**Comment by Villageacules** [comment]
Issue resolved a lone while ago, plus this issue is dead.
