### ISSUE TITLE
Bugged weapon.

### ISSUE THREAD

**Issue by Inter1tum** [Wynncraft/Issues#2705]
First of all, this update is amazing and it keeps players interested and stuff, but there is still some bugs (just like in everything). Today I joined to the server, and I didn't have enough emeralds to identify my stuffs at the "update room", so I travelled to Detlas to identify my armors. The problem is, that my weapon still has all the old identifies (picture of it; http://i.imgur.com/KOZdAQc.png it also says that rare items can't be identified, is this a bug too?), and I can't use my spells with it. Also if I hit mobs with it, it does only 1dmg. Is there any way to fix this?

**Comment by Inter1tum** [comment]
Update: 
I found an usable Rare Spear from my bank, and I'm able to identify it. Sadly it has way lower dmg than my bugged weapon.

**Comment by JaysonDestroyer** [comment]
im experincing the same problem with my old pants

**Comment by Trixter313** [comment]
This seems to be a variation of #2679

We recommend closing the duplicate and instead adding any comments the the original issue. Thanks!
