### ISSUE TITLE
losing health

### ISSUE THREAD

**Issue by Ritcheur** [Wynncraft/Issues#2709]
am I losing health without doing anything but just with my archer.

**Comment by DarkDemonDragon** [comment]
Please provide some details supplemented with some picture or video proof.

**Comment by Ritcheur** [comment]
![wynncraft 1](https://cloud.githubusercontent.com/assets/16384891/11933021/931a8706-a7f9-11e5-9a95-1380f4ede69c.png)
![wynncraft 2](https://cloud.githubusercontent.com/assets/16384891/11933026/975422c8-a7f9-11e5-8204-bff1d8115a34.png)

**Comment by Ritcheur** [comment]
![wynncraft 3](https://cloud.githubusercontent.com/assets/16384891/11933224/e5c8ebd6-a7fa-11e5-9fb5-ab6e7454aadd.png)

**Comment by Ritcheur** [comment]
![wynncraft losing healh](https://cloud.githubusercontent.com/assets/16384891/11934009/adb8dff8-a7ff-11e5-865f-5981a705a509.GIF)

**Comment by DarkDemonDragon** [comment]
Ahh that is the health regen bug. It's already been brought up I think.

**Comment by Ritcheur** [comment]
i'm still losting health

**Comment by Ritcheur** [comment]
oh i understand why. I got a leggin -21%health regen xD

**Comment by DarkDemonDragon** [comment]
That's probably it. Please close this issue if there are no other problems.
