### ISSUE TITLE
Item loss

### ISSUE THREAD

**Issue by Computteren** [Wynncraft/Issues#2712]

**Comment by Computteren** [comment]
So far, im NOT happy with the gavel update. I went to the identifier to identify my bow and armor, and POOF! MY leggings disapphered. How in the world, can that happen? It was the best leggings (For the last update, idk if there are better ones now) and they were Legendary. ANY way that I can get them back, cuz this is like... The worst "1st look" on an update that I been looking forward too.

Please, can anyone do something?
-Computteren

**Comment by anonymousderp** [comment]
i like the whole update and everything guys but it caused me to lose my leggings too, since it was a high tier item before the upgrade i will now question you guys how the hell will i get it back, my next leggings are 3 levels dif(65 to 68)

**Comment by Computteren** [comment]
I dont have any spare leggings, and im level 75. I would love to get then back, and would love if anony to get his back too.

**Comment by anonymousderp** [comment]
and another item to the list my chesplate got deleted when my game crashed but that would be my fault?

**Comment by Dibujaman** [comment]
I had the same problem with my Bob's legendary spear and my endgame chestplate, boots and leggings.
I would like yo know how to get them back, because there's no way to get another bob's legendary weapons...
And I have videos on the internet when you can see that I've got all of that stuff.
Now I have no good weapon and I have a useless armor.

**Comment by CoolBlueDragon** [comment]
Same here, my endgame leggs and boots disappeared as well as my "Bob Mythic Daggers" after identifying :/

**Comment by Dibujaman** [comment]
I heard that you can do quests again, so I hope I can get my stuff back by myself, but there might be new armor and weapons way better than those, so we should cheer up ourselves and go get those damn items back!!
Cheer up people, get those sad faces off!! :D

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. I like the way you think @Dibujaman =D. We'd appreciate it if you closed this issue. Thanks!
