### ISSUE TITLE
stuff gone?

### ISSUE THREAD

**Issue by TheSilver-Shadow** [Wynncraft/Issues#2715]
I had a level 49 legendary chestplate named "sawdust" it was fully identified, and was lost in the update. I also never spawned in the respawn room. It gave me the notification that I died and respawned me to luscolo for some reason.

Username---> TheSilver_Shadow

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
