### ISSUE TITLE
Endgame, and Bob's Mythic Daggers lost

### ISSUE THREAD

**Issue by CoolBlueDragon** [Wynncraft/Issues#2716]
I went over to the identifier to identify my bobs mythic dagger and I everything went well until it finished and I clicked on the daggers to pick it up. It had just disappeared. I'm not sure if it had to do with inventory space but I had 1 open. Now when I took off my endgame armor I had expected for only 1 piece to come off but the whole set came off and I was left with just adamadite and blue mast. I had lost my staglamites, and the end game boots (Can't remember the name of the boots, been about a month since I last logged in)  Not sure what can really happen, I do really want my dagger, leggs, and boots back...

**Comment by CoolBlueDragon** [comment]
My bad, I lost the leggs an staglamites. Just remembers the boots are staglamites. I believe the leggs were called Crystal? Cannot remember

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
