### ISSUE TITLE
Water Bottle

### ISSUE THREAD

**Issue by Philosophunculist** [Wynncraft/Issues#2717]
You can no longer fill empty water bottles, making the quest "Underwater" impossible.
EDIT: There is a water bottle merchant in Ragni.

**Comment by pewpeed** [comment]
You can fill empty water bottles with a cauldron. There is one in Nemract docks.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
