### ISSUE TITLE
I can't buy potatos IMPOSSIBLE QUEST!

### ISSUE THREAD

**Issue by ItzItchyYT** [Wynncraft/Issues#2723]
I am trying to complete the quest 'The Angry Village', however when I went to the only Potato Merchant in Wynn (Bremminglar), the potato is not an option to buy! This makes the quest impossible. This is what it says when I click on the villager:
![2015-12-21_17 03 45](https://cloud.githubusercontent.com/assets/16387333/11934878/ec402f9c-a804-11e5-8d7a-c0c59d493643.png)

Please help!!!!!!!!!!!!!

**Comment by ItzItchyYT** [comment]
I had to get someone to help me and go to Rymek for me to buy from the potato merchant there. Please fix it anyway since it's a level 27 quest that you need to go through a level 35 place to complete!¬

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
