### ISSUE TITLE
Potion Making is unfinishable

### ISSUE THREAD

**Issue by pewpeed** [Wynncraft/Issues#2725]
The quest Potion Making is no longer able to be completed because [Potion of Healing I] do not exist anymore. I tried to use the lowest level tier of healing potions (level 1) and it still doesn't work.

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.

**Comment by Nightfighter001** [comment]
I had the Problem now, too. It is because of old Potions. You have to buy new potions!
