### ISSUE TITLE
Lost Items

### ISSUE THREAD

**Issue by Zach570** [Wynncraft/Issues#2727]
After the new update my armor was forced off because it wasn't identified.  When it was forced off my boots were deleted.  They were super rare boots called adventure's boots that are now impossible to get without trading with players.

**Comment by AwesomeTUX** [comment]
Same Thing! Except for me it DELETED ALL OF MY ARMOUR EXCEPT FOR THE HELMET. All of my GOOD armor that I can't get back because without it, I'm to weak to go back and get it, or to get enough emeralds to buy it back!

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
