### ISSUE TITLE
Bug with VIP+ and pets.

### ISSUE THREAD

**Issue by BertleTheTurtle** [Wynncraft/Issues#2729]
Today I bought VIP+. And when ever I rightclick with my pet out, I keep on riding it, forcing me to get rid of my pet when I want to even fight. I would suggest to add a command to enable to ride your pet because it gets quite annoying.

**Comment by Trixter313** [comment]
This isn't really a bug and more of a suggestion. I suggest closing this issue and posting here instead: https://forums.wynncraft.com/forums/general-suggestions.69/

Thanks!
