### ISSUE TITLE
bolt blizzard and arrow storm not working

### ISSUE THREAD

**Issue by herobrian11** [Wynncraft/Issues#2730]
bolt blizzard and arrow storm are not working but says it is casted and takes mana and does no dmg or show any way of seeing it

**Comment by SteveClinton** [comment]
oops solved :D

**Comment by SteveClinton** [comment]
wait

**Comment by brendon96068** [comment]
how did you solve it

**Comment by Trixter313** [comment]
Great to hear!

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
