### ISSUE TITLE
Lost items

### ISSUE THREAD

**Issue by Supplying** [Wynncraft/Issues#2731]
I was told about the new update, so I got on and was reading the new info, then I decided to take off my boots, but it took all my armor off, since it was "Unidentified" and since my inventory was full, it all just disappeared, so I have no armor now, I was wondering if a staff could help me with this. :{

**Comment by Nils800** [comment]
I have exactly the same problem...

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
