### ISSUE TITLE
Stuck in the ground when I join a world

### ISSUE THREAD

**Issue by Tete444** [Wynncraft/Issues#2735]
First time logging on since the update, and every time I join a world and pick a class, it spawns me in the ground (what I'm guessing is under the spawnpoint). I've tried every class and its the same, and it makes it impossible to play Wynncraft

**Comment by TrashcanMan** [comment]
Do /kill with at least 3 soul points, if this solves your issue, please hit the "Close Issue" button at the bottom. Thanks!
