### ISSUE TITLE
Spawned inside blocks

### ISSUE THREAD

**Issue by JustSnowy** [Wynncraft/Issues#2739]
I played today just fine after the update and went up north, 3 hours after I logged out, above the ground, I spawned inside blocks. I can't use Teleport Scrolls and I'm definitely in there, it's not just lagg.
I'm stuck at: (-271 32 -4035) at the moment but I logged out at a higher Y coordinate I think. Did the map change or did something go wrong? I'll be afk in the world right now and I hope someone can tp to a safe place somewhere above the ground.

**Comment by TrashcanMan** [comment]
Do /kill if you have at least 3 soul points. If this solves your issue, please hit "Close Button" at the bottom. Thanks!
