### ISSUE TITLE
My Bobs Mythical Daggers dissapeared!!!

### ISSUE THREAD

**Issue by nickmathes** [Wynncraft/Issues#2740]
I was very happy to see gavel was out and I logged in. I was stuck in a cave and people told me to do /kill once and I had all my soul points. I did /kill and I spawned in another bock and again and again. After 4 or 5 times /kill I got out and my mythical daggers were gone! I really liked gavel but if it wasnt a bug and the daggers just got deleted by the game it is just stupid. I farmed REALLY long for them and I soloed Bob to get them. I indentified them completely and they were really good. Now I want to know if this is a bug (and I can have them back) or the game deleted them and it is just stupid.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
