### ISSUE TITLE
I lost my Sage Wand Legendary...

### ISSUE THREAD

**Issue by Darkeangels** [Wynncraft/Issues#2741]
I lost when we are in vanilla world... and i'm bugged inside a block when I hav been tp. And i wanted to use my Scroll Detlas (change item with Sage (the hand)) and is now I hav rollback and my Sage dropped. :(
![the image when i was bugged inside a block](https://cloud.githubusercontent.com/assets/16388796/11937759/b71dc8e4-a816-11e5-89f1-61a49dff964c.png)

PS : Sry for my bad english bcz i'm not a English ;x

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. Also, if you're ever stuck, typing /kill with 3+ soul pints should teleport you to the nearest visited town. We'd appreciate it if you closed this issue. Thanks!
