### ISSUE TITLE
Quest:Potion Making

### ISSUE THREAD

**Issue by Snappedmetal** [Wynncraft/Issues#2743]
So there is a bug where u need to get all indigrients but you cant actualy get potion of healing 1 because new potion is diffirent 

Problem:Potions that u need in quest arent the new ones

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/2725

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!
