### ISSUE TITLE
Vip glitch

### ISSUE THREAD

**Issue by CommandoPlays** [Wynncraft/Issues#2744]
I'm vip on wynncraft and it isn't giving me access to some areas of the game. By this I mean the last three slots in the class selection area. -_CommandoPlays_
![2015-12-21_18 08 49](https://cloud.githubusercontent.com/assets/16389024/11938128/6d42b9a6-a810-11e5-9b80-a0e654ffd56b.png)

**Comment by CommandoPlays** [comment]
please help me with this problem

**Comment by mirajhall** [comment]
I believe those three slots are for VIP+ only. VIP only unlocks two more than regular players.
