### ISSUE TITLE
Spell Glitch

### ISSUE THREAD

**Issue by brendon96068** [Wynncraft/Issues#2745]
My IGN is brendon96068 and my arrow storm spell doesnt work since the gavel update. It worked a few times while i was in wynn but later it just stopped working, it still takes the mana and says that i casted the spell, but nothing actually happens, all my other abilities are working and all my other classes work fine pls help, its really hard to grind out gavel when my main attack spell doesnt work.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by brendon96068** [comment]
Yes the issue is still ocurring but only with one bow, the bow i was using was the relic bow so it wasn't too hard to get another one, and it works. There are people who had Bob's bow before the update and can't use arrow storm with it, getting myself a new relic bow is a lot harder than getting a new Bob's mythic bow like some people will have to do.

**Comment by brendon96068** [comment]
easier*
bob's mythic bow is a lot harder to get and some people may have to go a while without arrow storm untill they get a better bow or kill bob again

**Comment by Trixter313** [comment]
According to this post it should be fixed now: https://forums.wynncraft.com/threads/gavel-patch-14-0-3.98796/

**Comment by brendon96068** [comment]
thnx, i actually got a new relic bow and it worked even before the patch
