### ISSUE TITLE
Unidentified Armor, Full inventory

### ISSUE THREAD

**Issue by Nils800** [Wynncraft/Issues#2748]
Username: Nils800

Issue: Okay, so I logged in today and saw that the gavel had been out for some days and became really hype, so I logged in on the server. When I started, as you know, I got teleported to the major update room and I read on the wall what I had to do. And now starts the issue: First I filled my inventory until I had every slot full except one slot (I think, Im 95% about that, I cant say for 100%, but I didnt have 4  slots open, around 1-2 slots open) and then I realised I also had to identify the armor I had on me, and was going to start with identifying my legendary chestplate. But when I took the chestplate, the game took off my whole armor + the legendary chestplate and the leggings, boots, and helmet disapeared!, The items didnt drop on the ground, just disapearing, and taking every gold armor piece I had inventory with it (I think it took every gold armor in my inventory, because when I checked my inventory first Im pretty sure it was gold armour in my inventory, but after the bug it opened up for slots in my inventory, where I belive the gold armor had been)

Okay, so this is the issue, and Im asking if I could get my items back? The level range was about 20-27, I cant really remember, since it was some weeks ago since I played on wynncraft. Especially I want my legendary chestplate that was for lvl 24 I think.

**Comment by Nils800** [comment]
The rest of the armor was unique

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
