### ISSUE TITLE
No Ghostly Armor Merchant

### ISSUE THREAD

**Issue by Kettlekorn** [Wynncraft/Issues#2749]
I'm close to being finished with the House of Twain quest but I had to buy a ghostly cap. I went to the merchant that sold it in the mansion and there wasn't a ghostly armor merchant. It was a normal armor merchant selling nothing! I can't complete the quest without the ghostly cap!

**Comment by DomDale** [comment]
Yep same here.

**Comment by Kettlekorn** [comment]
It's the only quest available for me other than TOA.

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
