### ISSUE TITLE
Some items were not converted on the Gavel update

### ISSUE THREAD

**Issue by DarkSamus9000** [Wynncraft/Issues#2754]
When I logged on after the Gavel release, I looked in my inventory at all of my equipment. Most of the items were changed to the new item system, but others had not. Coincidentally, both my and my friend's Fierte had not been converted.

These items cannot be identified, either: http://prntscr.com/9gxaeg

**Comment by Trixter313** [comment]
This seems to be a variation of #2679

We recommend closing the duplicate and instead adding any comments the the original issue. Thanks!
