### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by FreddieA2003** [Wynncraft/Issues#2756]
Hello i am stuck in a block i think and i can not get out. my friends tried to help but i cant. Please help
Coords: -1915 70 -4411 
Username: FreddieA2003
And i spent almost an hour trying to get out :( Help

**Comment by Inter1tum** [comment]
Make sure you have atleast 3 soul points, and then write /kill in chat. You'll loose 2 soul points, but you will be teleported to town nearby.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
