### ISSUE TITLE
My Wand is broken..... I think.......

### ISSUE THREAD

**Issue by MochiBrewster** [Wynncraft/Issues#2760]
![2015-12-21_20 29 00](https://cloud.githubusercontent.com/assets/16390727/11940585/85a932d4-a821-11e5-8026-8ec46dc02467.png)
My wand was a unique unidentified wand and now it is a normal wand with a weird name after identification.
It looks like a mistake and seems quite OP for a level 1. I would keep it but I just wanted to know if this item is illegal (illegal as in: Not Allowed To Have.)

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
