### ISSUE TITLE
My bow doesn't like arrow storm D:

### ISSUE THREAD

**Issue by Supercrafter55** [Wynncraft/Issues#2761]
Ok so i started up wynncraft after a thousand times of retrying to see if gavel is up and i joined. I went over to the identifier and identified all of my armor and my weapon (Bob's mythical bow) and everything was normal i guess but then the server went down for about 30 minutes to and hour or something.(I have an awful sense of time going by. But when i got back into game i started in ragni used arrow storm a bunch of times to kill one of the guard golems. But when i went to gavel i tried to use arrow storm a number of times, While it does says its using the skill (It even takes MP) it doesn't use arrow storm.

I made a video of what it does with it, and other bows.
http://www.screencast.com/t/7xd88aZzTMno

**Comment by Alayathekid** [comment]
I have had the exact same issue. I hope this gets fixed soon.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Supercrafter55** [comment]
Yes, its still occurring. BUT only with "Bob's Mythic bow" My depressing bow has no issue with using it.

**Comment by Trixter313** [comment]
Hmm, that's odd indeed. Weird request, but does it work if you take all your armor off? Thanks!

**Comment by Supercrafter55** [comment]
o.o yea it does wierd XD thanks, also just gunna add another thing, today or well tonight, OR WELL this early early morning I logged on after awhile and my "Pirate queens ring" went all buggy and all i see when i scroll over it is this massive black bar where in purple text says; ("type";LOOTBONUS") and a whole other mumble of stuff, also i cannot put it on. Just gunna throw that out there.

**Comment by Trixter313** [comment]
Hmm, then it seems a specific piece of armor is causing it. I suggest doing some testing to figure out which it is and then either throw it out or temporarily not use it until it's fixed. About the ring, some people have reported that issue with other items but I don't really know much about it. It's probably something an admin will have to fix.

**Comment by Supercrafter55** [comment]
Yea, i found out it was my "Crystal" Witch needs a specific amount of agility (30) and i have to either use rings/necklaces/armor to boost my agility to 30 to use it.
