### ISSUE TITLE
Resource packs

### ISSUE THREAD

**Issue by JECorrLazer** [Wynncraft/Issues#2762]
WOWOWOW
Hello the people of wynncraft! Many new updates I'm dying to see, only problem is i can't :/ I accidentally denied the resource pack, and couldn't get back in. It wont send me another request to accept, so I'm stuck here. I even tried using wynncraft's resource pack i have downloaded and still ldidnt work, please help

**Comment by Inter1tum** [comment]
I'm gonna help you mate.

First, go to your server list, and click your "Wynncraft" server once.
Then click that "edit" button, and there is an option for resource packs. Make sure it's enabled, then simply click "done" and enjoy your stay :)

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
