### ISSUE TITLE
Bug with water bottle 

### ISSUE THREAD

**Issue by FudyMC** [Wynncraft/Issues#2764]
Hi! in the gavel expansion, the developers insert a change in the potions and broke the water bottles, now the water bottles is impossible to craft (fill) and the mission underwater is impossible. (PD: my inglish sucks ;) )

**Comment by TrashcanMan** [comment]
I just checked on the Wynncraft Map and apparently there's a water bottle merchant somewhere in Ragni. I don't know if it's actually there ingame, but you could go check.

**Comment by mrgzf233** [comment]
same problem

**Comment by Trixter313** [comment]
TrashcanMan is correct. That's how you get water bottles now.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by mrgzf233** [comment]
ok
