### ISSUE TITLE
Point into defence (0) takes point but does'nt add 

### ISSUE THREAD

**Issue by faste234** [Wynncraft/Issues#2765]
After the new update, all points were reverted so I decide to put some in, all the categories go up in levels but when I put a point into defence it takes the point and does not level up defence (which is at level 0).

**Comment by Trixter313** [comment]
Could you maybe provide screenshots and elaborate a bit more? Thanks!

**Comment by faste234** [comment]
Aight. Basically it stays at zero when i put a point into it. The point is consumed but not used.
![2015-12-21_21 17 55](https://cloud.githubusercontent.com/assets/16391926/12003801/6fe1c60c-ab26-11e5-8443-e5c4746f1374.png)

**Comment by Trixter313** [comment]
Hmm, that is odd indeed! If the issue is still occurring, please check to see if someone has posted it already or not, and if no one has, repost the issue. A massive closing sweep was made to declutter all of the already fixed issues. Thanks!
