### ISSUE TITLE
Boots are gone!

### ISSUE THREAD

**Issue by faste234** [Wynncraft/Issues#2766]
When I clicked my armour after the update it all went into my inventory apart from my boots! They just disappeared so now I'm sad :(

**Comment by Dibujaman** [comment]
It happened to me too, but cheer up!
You can still get new and awesome items because Gavel is up to lvl 100!
I'm sure that everyone who had that issue (I'm one of them too) can get better and awesome new items to explore this amazing new update!
Thanks for reading and good luck!

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. Listen to @Dibujaman ! We'd appreciate it if you closed this issue. Thanks!
