### ISSUE TITLE
Montefiore Didn't Convert

### ISSUE THREAD

**Issue by scorpio5** [Wynncraft/Issues#2768]
With the new update, we had to ID equipment to make the item fit the update.  Montefiore was left behind.
![2015-12-21_15 26 12](https://cloud.githubusercontent.com/assets/7762355/11941771/a47099e8-a7f7-11e5-9bcf-8fa9a9cd268d.png)

**Comment by BsnNick** [comment]
Can confirm, I have the Montefiore.

**Comment by MedievalBladeRPG** [comment]
This also happens with my fierte, I guess its a common problem with all items that contain special characters in their names

**Comment by Trixter313** [comment]
This seems to be a variation of #2679

We recommend closing the duplicate and instead adding any comments the the original issue. Thanks!
