### ISSUE TITLE
Dévoreuse can't be identified

### ISSUE THREAD

**Issue by iCreativity** [Wynncraft/Issues#2769]
The wand "Dévoreuse" is still in the old format, and not just for me.
![2015-12-21_22 33 36](https://cloud.githubusercontent.com/assets/14164385/11941901/0396bf8e-a833-11e5-8273-34fabdaa7860.png)

**Comment by mirajhall** [comment]
It seems that weapons with accents are still in the old format.

**Comment by iCreativity** [comment]
Interesting.

**Comment by Trixter313** [comment]
This seems to be a variation of #2679

We recommend closing the duplicate and instead adding any comments the the original issue. Thanks!
