### ISSUE TITLE
TestId HealthRegenRaw Staff

### ISSUE THREAD

**Issue by Major-Lue** [Wynncraft/Issues#2770]
![](http://i.imgur.com/GXD5cXg.png)
Got this item after id'ing a unique item. Pretty sure it's a bug item so.. If you can remove it or something thank you :)
IGN: Major_Lue

**Comment by TrashcanMan** [comment]
This is most likely a developer item and is thus illegal to own, toss it into the Detlas trash can, a lava pit, a fire, etc. to get rid of it.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
