### ISSUE TITLE
Quest Underwater bug

### ISSUE THREAD

**Issue by mrgzf233** [Wynncraft/Issues#2779]
So there was a huge update yesterday which I kind of liked it.However, every equipment became unidentified so I decided to start a new character, Archer. I'm currently level 12 now and I'm up to the quest underwater, the quest requires you to bring 1 water bottle and 3 pigman meat to the guy so he will give you the underwater hat.I got the meat but when I used a glass bottle to try to get water from the ocean, it doesn't do anything, it remains empty. I don't know is this a bug or it got updated because that's what I did to my other characters before doing this quest... Plz fix it or update the quest info..
![88n b7rv yr3g 0 9 c qwd](https://cloud.githubusercontent.com/assets/16392777/11943348/25232e62-a80b-11e5-965f-6c22471063ad.png)

**Comment by TheDerpyMan** [comment]
Actually, at the Ragni's Skeleton Dungeon exit, next to the Wheat Merchant is a Water Bottle Merchant that sells Water bottles. Go get them from there.

**Comment by mrgzf233** [comment]
Ok, I will check them out, thanks

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by mrgzf233** [comment]
OK
