### ISSUE TITLE
/fixquests gave me quest items for quests I already did

### ISSUE THREAD

**Issue by SonioExpert46** [Wynncraft/Issues#2781]
Specifically, I got Cluckles' Favorite Feather, 2 Yellow Crystal Shards, 2 Purple Crystal Shards, and Healing Water. I already completed all the quests that require these items, and I have no way of removing them from my inventory. Anything that can solve this problem?

**Comment by mirajhall** [comment]
This is a bit of a cheaty method, but if you fill your inventory entirely (like just spread out all your emeralds), then when you drop the quest items you can't pick them back up.
