### ISSUE TITLE
Silverfish, Animal, and zombie key sellers do not exist

### ISSUE THREAD

**Issue by Nodygnomes** [Wynncraft/Issues#2782]
I've hoped to multiple servers to buy some keys to find that the key merchants are not currently there.

**Comment by Zeryther** [comment]
Experiencing this bug too. Wanted to play zombie with a friend but we could not get the key.

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
