### ISSUE TITLE
Can't Invite to Party [RESOLVED]

### ISSUE THREAD

**Issue by Philosophunculist** [Wynncraft/Issues#2784]
Niether my friend or I can invite anybody to a party using "/party invite [playername]". No output apears after entering the command for the person being invited or me.

**Comment by TheDerpyMan** [comment]
You have to use /party create then /party invite. (Just saying)

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
