### ISSUE TITLE
My Royal Dusty Amulet was taken!

### ISSUE THREAD

**Issue by xCalico** [Wynncraft/Issues#2785]
I just got to cinfras and I got myself a royal dusty amulet with my royal recommendation paper thing and it gave me an unidentified amulet, so I go to identify it and get the item, when the server restarted when I was identifying it and now it's gone, please help.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
