### ISSUE TITLE
Death Whistle

### ISSUE THREAD

**Issue by Snowballcps** [Wynncraft/Issues#2786]
I have the flower but the quest doesn't notice it... I'm stuck.

**Comment by mirajhall** [comment]
Did you go through the cave and get teleported? If you used spells to get around the barrier, it won't register.

**Comment by Snowballcps** [comment]
You don't go in a cave. You go to the top of the hill to collect the flower? That's what the quest book says.

**Comment by mirajhall** [comment]
There is a cave oh the hill right before the barrier on the path. It's mostly just an obsidian hole that will teleport you. If you don't go into the cave and just "spell" your way to the top, your quest book won't update.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
