### ISSUE TITLE
Kicked for Flying?

### ISSUE THREAD

**Issue by Nrm-1** [Wynncraft/Issues#2787]
Name: Noah
IGN: FurnoBlade
About 7 months ago I started playing Wynncraft. I was in awe of the builds, npcs, and class abilities. Honestly, I prefer Wynncraft over any other server and hence I spent all my free-time playing on the server. However in the first few days of June I was playing with the archer class and was banned. It occured while I was mid-air using the splash potion that allows the player to have a huge leap. I didn't have any proof like a video or a screenshot to show that I didn't use fly cheats. Apparently Wynncraft also has a closed ban appeal. I didn't know what to do or how to appeal my ban so I became hopeless. However, it has been over 7 months and I still love the server and haven't deleted it off my server list. I have recommended the server to my Minecraft friends hoping they could show me all the new add-ons. 

Recently I looked on the forums and saw this bug reports forum. I have decided to give it a go. I don't expect to have an un-ban noting that there are several other more important issues at hand. Whatever the outcome I will still have a positive attitude. I'm honestly more grateful that I had the courage to say this. It is really hurtful when my friends think I'm a cheater by seeing my ban on Wynncraft. 

Thank you so much Wynncraft. This is the best MMORPG server in the history of Minecraft. Im glad to have participated. :)
~Noah (aka FurnoBlade)

**Comment by Alayathekid** [comment]
Please do not put ban appeals in the issue tracker. I'm not a mod, but I have that much common sense.

**Comment by Trixter313** [comment]
Ban appeals go here: https://forums.wynncraft.com/forums/ban-appeals.84/create-thread

Please close this issue. Thanks!
