### ISSUE TITLE
Quest : Potion Making not working! [RESOLVED] Thank you Content Team :D

### ISSUE THREAD

**Issue by TheDerpyMan** [Wynncraft/Issues#2788]
Potion Making
Level : 15
It doesn't work at the part of *Bring back 8 Bat ears, 16 Bone meal and 3 Potion of Healing I to The Assistant*
If I try to continue the quest, when I have all of the items required in my inventory, it doesn't work. I think it might be an issue with the new potions, because they're different from the old ones.
I have 14 Bat ears, 16 Bone Meal and 3 Potion of Healing (The lowest rank of potions available in the shop.
Maybe update the quest so it works in the new update.

Other bugs : 
1. Like 25% of the times, I get an empty Loot Chest. It happens to all Tiers, since I got a Loot Chest III empty and IV.
2. Bow of Wisdom Not converted. (At the moment when I post this)

I hope you fix these bugs :D

**Comment by Trixter313** [comment]
Could you tell me what the content team did to fix this? Thanks!

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by TheDerpyMan** [comment]
The most important one, Potion Making is resolved, the bug about Loot chests is still out there in Wynncraft.
Idk who fixed this, but I expect it was the people that also made Gavel. Why do you use "We" if I remember correctly you're not a part of the staff.
