### ISSUE TITLE
Arrow Storm ISN'T WORKING AT ALL

### ISSUE THREAD

**Issue by Danieldrago** [Wynncraft/Issues#2792]
try it it just doesn't work

**Comment by Alayathekid** [comment]
*This is not very accurate it only doesn't work for certain bows. I am going through other treads similar to this and trying to find a possible cause.

**Comment by Alayathekid** [comment]
I have a similar issue, but have you tried using it with a different bow. It seems to not only work with one bow when ever I use it. If I use it with another bow it works just fine.

**Comment by brendon96068** [comment]
Not for me, Its not working for me with ANY bow

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Alayathekid** [comment]
Trixter313 is that your default reply?

**Comment by Trixter313** [comment]
@Alayathekid I made a few presets that fit most cases because I had 300+ bug reports to rifle through and didn't have the time or patience to re-type a new response for each.

It works for most of them because a lot of bugs are fixed by just waiting a bit.

**Comment by brendon96068** [comment]
i found that getting a new bow actually worked, but im still upset as my new bow isn't as good as my old one, also i see a lot of people who have bob's mythic bow and can't use arrow storm

**Comment by Trixter313** [comment]
According to this thread, the issue should be fixed. https://forums.wynncraft.com/threads/gavel-patch-14-0-3.98796/
