### ISSUE TITLE
Fierte weapon not being able to ID.

### ISSUE THREAD

**Issue by LuciferVH** [Wynncraft/Issues#2793]
Well, i know there has been notes about Fierte which is a Legendary weapon for the worrier. But is seems that its been brocken when the gavel was released. Im just a bit sad that is brocken because i was exited for using that weapon which i was only 4lvl. away. So im just asking for it to be fixed, that will make me and other player who had it happy.
![screenshot_83](https://cloud.githubusercontent.com/assets/14062447/11944616/0d07edbe-a850-11e5-9b52-030a48128875.png)
![screenshot_84](https://cloud.githubusercontent.com/assets/14062447/11944617/0d084796-a850-11e5-8936-2615f4997dcc.png)

**Comment by coolminer** [comment]
Same here :/
![2015-12-22_01 06 28](https://cloud.githubusercontent.com/assets/16393541/11944821/362085c8-a849-11e5-93b1-1cba213afbb5.png)

**Comment by TheGamingReaver** [comment]
From what I read it has something to do with the special characters in this case the "é" That's why it looks like an old weapon also.

**Comment by LuciferVH** [comment]
Well this isnt the only case there were also other items with the same problem. But this problem only happened when Gavel was realeased. It was something that they had to look out becuase its an old bug.

**Comment by coolminer** [comment]
I think it will probably be fixed in an hour after the 14.0.2 patch does effect in every server.

**Comment by Trixter313** [comment]
This seems to be a variation of #2679

We recommend closing the duplicate and instead adding any comments the the original issue. Thanks!
