### ISSUE TITLE
Skillpoints are gone after putting them in agility

### ISSUE THREAD

**Issue by DoggyRampage** [Wynncraft/Issues#2795]
By accident did not put a discription: Well My skillpoints just disappear when I try to click on agility. I lost 5 skill points http://prntscr.com/9h15rx Here is a screenshot

**Comment by ThunderRemix** [comment]
Check if you have gear that subtracts Agility points.

**Comment by DoggyRampage** [comment]
It does. My helm has -6. Thanks!

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
