### ISSUE TITLE
Need help with these issues

### ISSUE THREAD

**Issue by GlacierExplorer** [Wynncraft/Issues#2796]
![bug1](https://cloud.githubusercontent.com/assets/16383868/11944985/ac486e3c-a885-11e5-9493-2bd35d624a35.png)
![bug2](https://cloud.githubusercontent.com/assets/16383868/11944986/ac4a2970-a885-11e5-95cd-a50ff70f72ae.png)
![bug3](https://cloud.githubusercontent.com/assets/16383868/11944987/ace141ca-a885-11e5-82db-0c2097d3873a.png)

![bug5](https://cloud.githubusercontent.com/assets/16383868/11944983/ac45cf60-a885-11e5-9ecd-20c33486154f.png)
![bug6](https://cloud.githubusercontent.com/assets/16383868/11944984/ac46f26e-a885-11e5-9b57-d3fe92dbfa11.png)

Well, i encountered some bugs here. After an hour of normal playing and a log-out, I found that i can't interact with anything in the WC servers. After I right-clicked my maelstorm it turned from a wooden slab to a normal bow which has wierd purple words,and no click-combos are working now, then all potions turned into 'HEALING **'.
I tried to send a message to help but I can't send any messages out. I tried to use commands but only 'You can't use commands right now!' :(
Can you help me to fix all these problems? (My username is RElNHARD) Thanks! :D

P.S. English isn't my first language so please ignore the grammar/spelling mistakes :)

**Comment by Trixter313** [comment]
Are all of these issues still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
