### ISSUE TITLE
My Item Disappeared

### ISSUE THREAD

**Issue by Gavinator647** [Wynncraft/Issues#2797]
The update made it so to use your items you have to re-identify them. So I wanted to take my armor pieces off one by one to identify them. Then it took off all my armor and i only had 3 slots in my inventory left. So I only got my helmet, chest plate, and leggings back. My boots disappeared. It didn't drop on the ground. I tried re-logging and it didn't show up still. The old name of the boots before the update was Meanderthal. My in-game name is Gavinator647. I would appreciate it if I could get them back.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
