### ISSUE TITLE
Item disappearing

### ISSUE THREAD

**Issue by alexis-le-dur** [Wynncraft/Issues#2800]
Sometimes while traveling in Gavel, I don't know why, item in my inventory disappear, the only item which I saw the disparition was my helmet "Blue Mask" I was doing the Shrek Quest, I leave the tower with the helmet quest I put it in my inventory and put back "Blue Mask", 1 hour after (Yes 1 hour), I disconnect/reconnect after a bug in the mansion's quest of Dark Forest and "Blue Mask" was not here anymore and I had the helmet from Shrek's quest on my head ! This happen to the pants of "An Iron Heart Part-2" too (Which a bug make me choose the wrong choice).

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
