### ISSUE TITLE
Green Gloop Quest Is Impossible

### ISSUE THREAD

**Issue by TheLeirbag** [Wynncraft/Issues#2801]
So, for this quest, you have to give 5 glass bottles to this dude, but thanks to the new Gavel update, it's impossible to get glass bottles. I am sure in time people will realize this, but I'm stuck with this quest and no more to do....so....I'll just wait, I guess? Please look into this, I'm sure having a quest being impossible is not very good news. Thank you!

**Comment by stazrocks** [comment]
I can sell ya 5

**Comment by TheLeirbag** [comment]
Sure! When and where?

**Comment by stazrocks** [comment]
how much will u pay?

**Comment by TheLeirbag** [comment]
Well, in the latest updates they wouldn't cost that much

**Comment by TheLeirbag** [comment]
So I say a block of emerald?

**Comment by stazrocks** [comment]
no way

**Comment by TheLeirbag** [comment]
Alright, that's how much they would cost, though.

**Comment by TheLeirbag** [comment]
I'm not going any more than 5 EB

**Comment by stazrocks** [comment]
k no deal

**Comment by TheLeirbag** [comment]
Fine

**Comment by TheLeirbag** [comment]
How much do you want?

**Comment by stazrocks** [comment]
say a good offer

**Comment by TheLeirbag** [comment]
I'll go more than 5

**Comment by TheLeirbag** [comment]
What do you want, though?

**Comment by stazrocks** [comment]
rememer i also have to travel from gavel to wynn for the trade

**Comment by TheLeirbag** [comment]
Okay.

**Comment by TheLeirbag** [comment]
Where from Gavel?

**Comment by stazrocks** [comment]
u in gavel?

**Comment by TheLeirbag** [comment]
Not atm, I'm in Almuj

**Comment by TheLeirbag** [comment]
But I'm considering to come to LLevigar

**Comment by TheLeirbag** [comment]
But no further

**Comment by stazrocks** [comment]
hrm if u come It will cost u 1LE

**Comment by TheLeirbag** [comment]
That much?!

**Comment by TheLeirbag** [comment]
For 5?

**Comment by TheLeirbag** [comment]
If I come, it should not cost that much

**Comment by stazrocks** [comment]
yep

**Comment by stazrocks** [comment]
there rare now

**Comment by TheLeirbag** [comment]
They're rare? How did u get them?

**Comment by stazrocks** [comment]
you cant

**Comment by TheLeirbag** [comment]
Well, I gave up a lot of my emeralds by accident earlier....

**Comment by TheLeirbag** [comment]
I only have like 25EB

**Comment by TheLeirbag** [comment]
Maybe less because of that

**Comment by TheLeirbag** [comment]
You don't need them for a single quest, or anything dude.

**Comment by stazrocks** [comment]
25EB for 3 bottles

**Comment by TheLeirbag** [comment]
Seriously?

**Comment by TheLeirbag** [comment]
I might as well just wait for this to be patched

**Comment by TheLeirbag** [comment]
You should really just be generous and let me buy them for a few EB

**Comment by TheLeirbag** [comment]
Like 10

**Comment by stazrocks** [comment]
have fun this will be one of the last things to be patched

**Comment by TheLeirbag** [comment]
You don't need them for anything, but I do.

**Comment by TheLeirbag** [comment]
I don't have that many emeralds

**Comment by TheLeirbag** [comment]
It's impossible for me to do it. Just let me do it for 20 EB

**Comment by TheLeirbag** [comment]
Then I'll have like 1 EB left

**Comment by TheLeirbag** [comment]
I would spend almost all my money

**Comment by TheLeirbag** [comment]
And just have a little money left to spare

**Comment by TheLeirbag** [comment]
Please, dude?

**Comment by TheLeirbag** [comment]
I'll have like all my money spent on that.

**Comment by TheLeirbag** [comment]
All of it.

**Comment by TheLeirbag** [comment]
Well, now you're not responding.

**Comment by stazrocks** [comment]
15EB per bottle

**Comment by TheLeirbag** [comment]
25 for all of em

**Comment by TheLeirbag** [comment]
So that's 5EB each

**Comment by stazrocks** [comment]
nope

**Comment by TheLeirbag** [comment]
That's all I have, dude

**Comment by stazrocks** [comment]
k

**Comment by TheLeirbag** [comment]
So please, 25 in all

**Comment by TheLeirbag** [comment]
I still need to get to 25 eb

**Comment by TheLeirbag** [comment]
I don't have that much, but I'll go to there

**Comment by stazrocks** [comment]
nope i might do 2 fir 25EB

**Comment by TheLeirbag** [comment]
Dude, I'm only lvl 33

**Comment by stazrocks** [comment]
cool

**Comment by TheLeirbag** [comment]
How much do you expect me to have?

**Comment by stazrocks** [comment]
a few LE is what I hade at ur lvl

**Comment by TheLeirbag** [comment]
Remember? I also wasted money.

**Comment by TheLeirbag** [comment]
By accident.

**Comment by TheLeirbag** [comment]
Do you ACTUALLY have this stuff?

**Comment by TheLeirbag** [comment]
Please make it 25 in all. Or else, I'll like spoil Star Wars or something...lol

**Comment by stazrocks** [comment]
no dont spoil it

**Comment by TheLeirbag** [comment]
Dude

**Comment by TheLeirbag** [comment]
I think I just found out a way anyway, hopefully

**Comment by TheLeirbag** [comment]
I might as well spoil it

**Comment by stazrocks** [comment]
no plz

**Comment by stazrocks** [comment]
dont

**Comment by TheLeirbag** [comment]
5.....

**Comment by TheLeirbag** [comment]
4...........

**Comment by stazrocks** [comment]
no plz

**Comment by TheLeirbag** [comment]
3......................

**Comment by TheLeirbag** [comment]
2.........

**Comment by stazrocks** [comment]
sryos

**Comment by TheLeirbag** [comment]
1.............

**Comment by stazrocks** [comment]
Fine il sell

**Comment by TheLeirbag** [comment]
Are you sorry?

**Comment by stazrocks** [comment]
nope

**Comment by TheLeirbag** [comment]
0.............

**Comment by stazrocks** [comment]
nooooooooooo

**Comment by stazrocks** [comment]
ok

**Comment by TheLeirbag** [comment]
What spoiler should I do first?

**Comment by stazrocks** [comment]
none

**Comment by TheLeirbag** [comment]
Okay, I'll tell you who dies:

**Comment by stazrocks** [comment]
no plz

**Comment by TheLeirbag** [comment]
Mhm....

**Comment by TheLeirbag** [comment]
So do you want to trade me for 20EB?

**Comment by stazrocks** [comment]
noope

**Comment by TheLeirbag** [comment]
If say no, I'll spoil the whole thing

**Comment by TheLeirbag** [comment]
If you say no to 20eb, then I'll spoil a person who dies

**Comment by TheLeirbag** [comment]
And you said no to 20EB

**Comment by stazrocks** [comment]
no

**Comment by stazrocks** [comment]
k im not reading it

**Comment by TheLeirbag** [comment]
Right.

**Comment by TheLeirbag** [comment]
Well first, I'll tell you who Kylo Ren actually is

**Comment by TheLeirbag** [comment]
Should I?

**Comment by TheLeirbag** [comment]
Would you like it if you couldn't really play Wynncraft anymore?

**Comment by stazrocks** [comment]
?

**Comment by TheLeirbag** [comment]
Trade with me, or else

**Comment by TheLeirbag** [comment]
25EB, PLEASE

**Comment by stazrocks** [comment]
or  else what?

**Comment by TheLeirbag** [comment]
Just, please.

**Comment by TheLeirbag** [comment]
How would you like it not being able to play?

**Comment by stazrocks** [comment]
DDOS?

**Comment by TheLeirbag** [comment]
Please, just accept the trade for 25EB.

**Comment by TheLeirbag** [comment]
That's the only money you're going to GET. You're not using those bottles anyway!

**Comment by TheLeirbag** [comment]
I just want to play the game.

**Comment by stazrocks** [comment]
Then log on

**Comment by TheLeirbag** [comment]
I am on.

**Comment by TheLeirbag** [comment]
I want to continue on playing quests and such.

**Comment by stazrocks** [comment]
nice

**Comment by TheLeirbag** [comment]
You're gonna be this kinda guy?

**Comment by TheLeirbag** [comment]
The guy that everybody hates?

**Comment by stazrocks** [comment]
nope

**Comment by TheLeirbag** [comment]
Can we please make an agreement?

**Comment by TheLeirbag** [comment]
Meet at the gates of gavel

**Comment by TheLeirbag** [comment]
We trade 5 glass bottles for 25EB

**Comment by TheLeirbag** [comment]
Boom, done, this thing is over with.

**Comment by TheLeirbag** [comment]
EZPZ

**Comment by TheLeirbag** [comment]
You just got rekt.

**Comment by TheLeirbag** [comment]
I have 7 glass bottles

**Comment by TheLeirbag** [comment]
Bye bye.

**Comment by Trixter313** [comment]
Wow.... Just so you know, you now have to buy water bottles from the merchant in Ragni then drink them for empty bottles. They are 1 emerald a piece...

**Comment by TheLeirbag** [comment]
You realize, that doesn't work. You cannot drink water bottles anymore (maybe they fixed it, let me see...). Anyway, I have to close this.

**Comment by Trixter313** [comment]
I tested it out before I recommended it to anyone and the instant drink doesn't apply to water bottles ;)
Have a good time playing Wynn!

**Comment by Trixter313** [comment]
Edit: You get empty bottles as drops from some mobs now. I know for sure the zombies near the identifier on the emerald trail drop them, I've gotten a few from them.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by TheLeirbag** [comment]
Yeah, I realized that. The Wynncraft wiki doesn't have weak zombies on the list of dropping them.

I'm trying to close this issue, I'm hitting it, but it's not really working. Am I doing it wrong? Lol, I'm a little bit of a noob sometimes.

**Comment by Trixter313** [comment]
Nope, it's closed just fine =)

**Comment by TheLeirbag** [comment]
Alright, thanks for helping me out, man. :)
