### ISSUE TITLE
Quest Bug

### ISSUE THREAD

**Issue by sZmanMythhead** [Wynncraft/Issues#2805]
When I joined again with, I was reset, and now my thieving rodents quest won't be completed even with the necessary items. Can I have the quest out of my quest book, because it will not go away no matter what. I don't know what caused the glitch, but i do know it happened right before the update. I tried again after the update and it is still bugged out. My in-game name is ZmanMythhead.
Please fix it soon,
Thanks.

**Comment by sZmanMythhead** [comment]
Bump

**Comment by Trixter313** [comment]
Have you tried using the command /fixquests ?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
