### ISSUE TITLE
rip wand

### ISSUE THREAD

**Issue by stazrocks** [Wynncraft/Issues#2806]
so im playing I crash and this happends and I also cant use it 
![screenshot_12](https://cloud.githubusercontent.com/assets/13687836/11946630/2d12475e-a822-11e5-9d74-f409233e7989.png) thats only part of the name  

and ing is stazboyYT

**Comment by TheDerpyMan** [comment]
Those are some bugs with the progamming behind the item. You have to tell them (The Admins) more informations about the item. It's name, your stats (Strength, agility etc) so they can fix it.

**Comment by stazrocks** [comment]
how do i contact them?

**Comment by TheLeirbag** [comment]
Yeah. Well. Rip.

**Comment by Trixter313** [comment]
Admins read this bug tracker so if you post the information here they should see it.
