### ISSUE TITLE
souls bug

### ISSUE THREAD

**Issue by ccs96507** [Wynncraft/Issues#2808]
When I had only 2 souls i died

but I lose my all items

My Minecraft ID:ccs96507

**Comment by TheDerpyMan** [comment]
That's because you had 2 Soul Points and you lost 2 soul points by dying.
2-2 = 0. It says on the Soul points that when you lose all of them, you'll drop your items.
You got 0 Soul points, you lost your items.

**Comment by ccs96507** [comment]
but when i died my soul is not 0
it is still 2

**Comment by TheDerpyMan** [comment]
Still, that means you got your souls on 0 by dying. It doesn't mean anything if after you died you have 2 or 100, you lost your items, bro.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
