### ISSUE TITLE
House Of Twain Cap Merchant

### ISSUE THREAD

**Issue by CaptainBubbles89** [Wynncraft/Issues#2809]
I don't want to spam or bother anyone but House Of Twain is a very hard quest that gives an amazing amount of xp and emeralds. Although, this quest is now literally impossible. The ghostly cap merchant needed for the quest is well, bugged. To get into the graveyard you need an item called "The Ghostly Cap". This cap is now impossible to get! Why? Because the merchant does not sell anything! Its just there with no purpose. As a solution to THIS problem, I would delete the NPC, then re-code it. I am a level 49 mage who really needs xp. Thanks for everything.

P.S (Now that everyone is in Gavel, we can't use friends caps. This quest is past Nesaak.)

![screen shot 2015-12-21 at 9 46 29 pm](https://cloud.githubusercontent.com/assets/16394824/11946813/9b91027e-a82c-11e5-991a-f9644100d9d4.png) This is an image of what pops up.

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
