### ISSUE TITLE
quest dialog will not continue

### ISSUE THREAD

**Issue by linzefeng** [Wynncraft/Issues#2810]
i was doing shattered mind quest, and i was was talking to Likeru? npc in the crazy forest, but the server crashed mid dialog and now the dialog is stuck on 1/3 and will not continue, nor can i progress.
swiching servers does not work.
![2015-12-21_18 45 23](https://cloud.githubusercontent.com/assets/10836969/11946864/03a02e44-a814-11e5-844a-35b9cf2daab0.png)

![2015-12-21_18 45 30](https://cloud.githubusercontent.com/assets/10836969/11946878/3fbeebf4-a814-11e5-994d-8e2d9207c718.png)

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.

**Comment by Trixter313** [comment]
Have you tried /fixquests ?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
