### ISSUE TITLE
Lost Champions Helm

### ISSUE THREAD

**Issue by dmhacker** [Wynncraft/Issues#2816]
Hello,

So I logged on to try out the new update with the Gavel province after a several month-long hiatus, but when I tried to do the Orc quest, I put on the Orc Mask and - poof! - my Champions helmet disappeared. I can't find it in my inventory, and I am assuming it is lost. Please help! What is the set when it is missing a piece?

-dmhacker (IGN: Amursoc)

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
