### ISSUE TITLE
Lost Adventurer Armor

### ISSUE THREAD

**Issue by nickz25** [Wynncraft/Issues#2818]
I just came back to Wynncraft today, I had a full inventory, and I had an Adventurer armor (All but leggings) equiped. My armor said unidentified. I was confused, so then I clicked it. Then all my armor disappeared without a trace. I really want it back. I'm a Wynn veteran so I got that armor before it was removed, and it holds a lot of value to me. I still have my leggings in my chest, but I would really appreciate if it could get rolled back. If more evidence is needed, just let me know.

Edit 1: This was in the new tutorial room, and I thought it was a graphical glitch, so I logged out. When I came back, bam nothing. (I looked around before)
Edit 2: I took off the pants, and it all disappeared. When I tried to put the pants back, they disappeared as well. I didn't lose them. It glitched out

**Comment by Zach570** [comment]
I lost my adventure boots the same way

**Comment by ResistanceGaming** [comment]
It would have dropped behind you, so you kinda lost the peices.

**Comment by ResistanceGaming** [comment]
I will sell you a full set for around 6 LE

**Comment by nickz25** [comment]
Btw: this was in the new tutorial room, and I thought it was a graphical glitch, so I logged out. When I came back, bam nothing.

**Comment by nickz25** [comment]
@ResistanceGaming lets talk about it. Skype: nick.ward00

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
