### ISSUE TITLE
Shattered Mind Glitched

### ISSUE THREAD

**Issue by DevinPritts** [Wynncraft/Issues#2819]
I was doing the "Shattered Mind" quest when I got kicked from the world, during the chat from "Likeru?"  now when I get in the quest book will not update even tho I do what my friend did and turned in the mission. I am now stuck in there and am hoping for help with either a section of the mission reset or just the quest its self 

                                                               -ToastedPenguin

**Comment by Trixter313** [comment]
Have you tried the command /fixquests ?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
