### ISSUE TITLE
Randomly Dissapearing Weapons.

### ISSUE THREAD

**Issue by HybridBonnie** [Wynncraft/Issues#2820]
So, I Found a bug, it;s where your weapon randomly vanishes. This happened to me, my MaelStrom is gone, and I can't proceed through the province of Gavel. This Also Happened to my brother on his account. His Spear has dissapeared. Can you help me?

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
