### ISSUE TITLE
I died with 3 soul points

### ISSUE THREAD

**Issue by PorkyDaTepig** [Wynncraft/Issues#2821]
I had died in the Hallowynn Quest and lost all my items. The thing is, I had 3 soul points. I have pictures of the text saying I had gotten a soul point, but not one of them during the fight. Im not asking for my items back, Im just reporting it. Pictures: http://imgur.com/a/6ofXW

**Comment by CoolBlueDragon** [comment]
The one you got from sun rising, was that your 3rd soul point?

**Comment by PorkyDaTepig** [comment]
Yes, I had 2 before and was running around until the sun rise came up so
that I wouldn't lose my stuff, and then I saw the message and that I had
three So I started attacking again, which is why there is a lvl up msg.
