### ISSUE TITLE
Assassin Spin Attack Bug

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#2822]
The Assassin seems to make enemies move FASTER for a short amount of time rather than SLOWER. The hit enemies (if not dead) will zip around for a second or two.

**Comment by mirajhall** [comment]
I knew something felt different! The same thing is happening to me, spin attack used to stop the mobs from moving too much, but now it seems that they spin around me with the attack, and it ends up pulling them closer to me.

**Comment by SaltEfan** [comment]
That is indeed the case, it only started happening to me after I unlocked the Spin Attack 2 though.
