### ISSUE TITLE
Quest Glitch

### ISSUE THREAD

**Issue by MarioSonicL** [Wynncraft/Issues#2823]
I was doing the new Green Skinned Trouble quest and when i killed the boss and got the axe so
I exited the room and now i'm stuck in a wall.
![](http://mp-su.com/u/9aed4.png)
I tried everything and the scroll but nothing worked but nothing worked.

**Comment by mirajhall** [comment]
If you have 3 or more soul points just do /kill. People get stuck in blocks all the time.

**Comment by MarioSonicL** [comment]
Thanks

**Comment by mirajhall** [comment]
Please close this thread if it is resolved.
