### ISSUE TITLE
Unable to complete quests that use items changed in Gavel update

### ISSUE THREAD

**Issue by Roxlvox** [Wynncraft/Issues#2825]
These are only the quests that I know of 

In the potion maker quest it requires the old type of healing potion which I cant get because of the new type of potion introduced in the update.

In the creeper infiltration quest you need green powder for the mask which cant be gotten because powders were removed till a later update

I hope this can be fixed soon

**Comment by Trixter313** [comment]
The potion part has been reported in #2725 but the creeper infiltration part is new. Thanks for the bug report! An admin should see this soon and hopefully will be able to help.

**Comment by Roxlvox** [comment]
Thanks and I was able to trade some guy for green powder but hopefully a compromise can be made till powders are added back

**Comment by Trixter313** [comment]
Good to hear! =)
