### ISSUE TITLE
Phantom Blade Visual Glitch

### ISSUE THREAD

**Issue by ElisaRoseD** [Wynncraft/Issues#2827]
I identified the phantom blade and it got the texture of some bow. 
![2015-12-21_21 06 33](https://cloud.githubusercontent.com/assets/16396269/11948312/fcd76dc2-a82f-11e5-918d-cfdd5a386121.png)

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
