### ISSUE TITLE
Potato Merchant not selling potatoes

### ISSUE THREAD

**Issue by ElisaRoseD** [Wynncraft/Issues#2828]
I'm working on "The Angry Village" and went to the potato merchant, only to see that he sells nothing.
![2015-12-21_22 07 17](https://cloud.githubusercontent.com/assets/16396269/11948347/578d08d0-a830-11e5-81ad-22745bf596da.png)

**Comment by Trixter313** [comment]
I believe this issue has been fixed. Can you confirm? Thanks!

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
