### ISSUE TITLE
Banned players allowed into lobbies

### ISSUE THREAD

**Issue by anders1122** [Wynncraft/Issues#2829]
To clarify, I am banned. I am not proud of it. I wish I had acted wiser back then, but I know for a fact it's too late now. 

I'm not 100% sure how it works, and what causes it to let banned players in. But repeatedly attempting to join the server eventually lets you in (first time it let me in was on my second try). It isn't lobby specific from what I've noticed, but I've only tried 2 or 3 times to really tell for sure. Joining a World doesn't work from what I've seen, but I've only tried joining once. 
If you require any questions or testing from me, I would be happy to help.

**Comment by ThunderRemix** [comment]
The bans on the server need time to sync up with lobbies.

**Comment by Trixter313** [comment]
About how long ago were you banned? By the way you're talking, it sounds like a while ago.

**Comment by anders1122** [comment]
Yeah it's a while ago. About 5 or 6 months, not 100% sure though.
