### ISSUE TITLE
Recourse Pack Issue

### ISSUE THREAD

**Issue by ResistanceGaming** [Wynncraft/Issues#2836]
As the title says, that is what I am experiencing.  The pack was working perfectly a few hours ago, but now this is what happened:  So I get back on Wynn, and the pack is at 100%, just stays there for eternity.  So I do what Salted's thread says, I remove Wynn from my server listing.  Now, whenever I click the accept button, the download does not even start...

**Comment by ResistanceGaming** [comment]
Finally started working, the current solution is to connect to a server with low lag levels it seems.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
