### ISSUE TITLE
Cant identify RARE weapon!

### ISSUE THREAD

**Issue by GamerGamerFTW** [Wynncraft/Issues#2837]
So i cant indetify rare weapon (Coeur De Lion) and i cant use it... Cmon wtf did you need to do these type of updates?!?

**Comment by RusTy-TCat** [comment]
Yeah, im not a mod or anything but i found items that didnt need iding and had the old interface of items, maybe they were removed in the update?

**Comment by DarkDemonDragon** [comment]
This is an old bug. Please close this issue and follow the main one #1312
