### ISSUE TITLE
My Archer is stuck under the map.

### ISSUE THREAD

**Issue by ShadowSen** [Wynncraft/Issues#2839]
This occured today when the servers started glitching out. I logged into a server when the map was all messed up and there were huge craters. Sadly, I spawned on one and fell in, losing my items. I got them back somehow and the server shut down. After the server came back on, my archer was just stuck in the ground, unable to move or get back up. Here are some screenshots every time I go log back into a server.
![2015-12-21_22 36 05](https://cloud.githubusercontent.com/assets/16398444/11951279/db4e6918-a833-11e5-9e18-c4d9420c1d35.png)
![2015-12-21_22 36 07](https://cloud.githubusercontent.com/assets/16398444/11951280/db500d90-a833-11e5-864f-96bbe7b749bd.png)
![2015-12-21_22 36 08](https://cloud.githubusercontent.com/assets/16398444/11951281/db52781e-a833-11e5-9750-0b937b39588b.png)

My username is __Sen__ btw.

**Comment by ResistanceGaming** [comment]
Wait for sunrise and then do /kill or use a TP scroll, either way you will have to afk on top of a tree to survive.  And also, how do you have no XP?

**Comment by ShadowSen** [comment]
I have no idea. I was level 25 but when this happened, I lost my levels

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
