### ISSUE TITLE
Ankou Quest NPC not working!

### ISSUE THREAD

**Issue by avaruus1** [Wynncraft/Issues#2841]
So i completed 3rd floor of tower of ascension quest but when i clicked Ankou it doesn't do anything :/
I tried to click around it but it still doesn't work!

**Comment by Trixter313** [comment]
Have you tried typing /fixquests ?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by avaruus1** [comment]
i tried /fixquests now but it didn't work!

**Comment by Trixter313** [comment]
Hmm, very odd indeed. An admin should see this soon and hopefully will be able to help.
