### ISSUE TITLE
The Shadow Of The Beast Quest BUG

### ISSUE THREAD

**Issue by Rentokraft** [Wynncraft/Issues#2842]
at the ancient ruins you are supossed to kill the ancient guardian in a order so i was killing the golem and then it stuck at the yellow golem i try to kill them all at once but only got the drops from pink to yellow golem
![2015-12-22_16 28 17](https://cloud.githubusercontent.com/assets/16392627/11952198/17bc8f84-a8c9-11e5-89c6-07d57d0b1144.png)

**Comment by mirajhall** [comment]
This is part of the quest, you must figure out what it means :)

**Comment by Rentokraft** [comment]
ik, but the other golem didnt drop the wool only the pink light blue green and yellow and i kill them all at once

**Comment by Rentokraft** [comment]
i try like 3 times still the same :\

**Comment by mirajhall** [comment]
These are the only four colors that drop. If I remember correctly, Pink drops 1 wool, blue drops 2, green drops 3, and yellow drops 4. This would make the code pink, blue, green, yellow.

**Comment by Rentokraft** [comment]
so only that?

**Comment by mirajhall** [comment]
If I got the numbers right that should work. Like I said, it's part of the quest that some colors don't drop anything.

**Comment by Rentokraft** [comment]
only 4?
ty its work
i though you need to kill al the golem
