### ISSUE TITLE
Green skinned quest bug?

### ISSUE THREAD

**Issue by KiriKorn** [Wynncraft/Issues#2844]
I'm not sure if it's a bug, but when I'm supposed to kill orcs so I get 5 axe heads, I somehow don't get any drops from them.

**Comment by mirajhall** [comment]
There are specific axe-wielding orcs that you must kill in the three camps, not all orcs drop the axe heads.

**Comment by MarioSonicL** [comment]
Kill the orcs with the longer names and they drop them and you are also suppose to get 5 axe heads from 3 camps each. (15 axe heads)

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
