### ISSUE TITLE
My Gear dissapeard when i took 1 peace off

### ISSUE THREAD

**Issue by KingRobin24** [Wynncraft/Issues#2845]
i was identifying my items and i wanted to identify my gear and as soon as i took 1 peace off all of it disspeard and i lost it all and IDK how to get it back

IGN: KingRobin24

**Comment by mirajhall** [comment]
If you didn't have the inventory space, it should've dropped behind you. Unless you picked it up, you won't be able to get it back. Sorry :/

**Comment by KingRobin24** [comment]
i looked around me and it wasnt there so.... i lost all my gear

**Comment by mirajhall** [comment]
Sorry about that :( On the bright side, Gavel has brought so many new armor pieces that I'm sure you'll find even better gear in no time.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
