### ISSUE TITLE
Underwater quest

### ISSUE THREAD

**Issue by TyrantHD** [Wynncraft/Issues#2848]
I cannot fill a bottle with water in it. Wynncraft staff please fix

**Comment by CoolBlueDragon** [comment]
If you spawn in Ragni and head to the left at the edit near the ranch should be a water potion merchant

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
