### ISSUE TITLE
Gavel quest mistype

### ISSUE THREAD

**Issue by CryogenicFrost** [Wynncraft/Issues#2852]
Just a minor grammar issue, http://i.imgur.com/ZNWjPb7.png It's "The Hunger of Gerts part 2"

**Comment by CryogenicFrost** [comment]
Bit easier to spot http://i.imgur.com/IK7NgHr.png

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
