### ISSUE TITLE
I'm Also Stuck In The Ground

### ISSUE THREAD

**Issue by EmmyChan** [Wynncraft/Issues#2856]
A chunk didn't load properly and I fell not realizing that I'd would spawn in the ground in all worlds 
![2015-12-23_01 05 55](https://cloud.githubusercontent.com/assets/16402140/11957047/01961e24-a913-11e5-87df-9a9333befe99.png) Please fix this when you get a chance <3

**Comment by MarioSonicL** [comment]
Do /kill but you will lose soul points (about 2) and you will be teleported to the closest city.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
