### ISSUE TITLE
Creeper pet turns into horse

### ISSUE THREAD

**Issue by HarryTurney** [Wynncraft/Issues#2860]
When I was using my spells to get through the water fast I kept getting on a horse that was changing type and I then found out if you right click a creeper with a spear (it seems any item works) it will turn into a horse and when you right click again it will change the look of it
![2015-12-22_15 20 22](https://cloud.githubusercontent.com/assets/6391483/11958532/476914fe-a8c0-11e5-9c2a-fe5ce3d466cb.png)
![2015-12-22_15 25 18](https://cloud.githubusercontent.com/assets/6391483/11958534/476f4b76-a8c0-11e5-89e0-208913908aad.png)
![2015-12-22_15 25 28](https://cloud.githubusercontent.com/assets/6391483/11958535/4770706e-a8c0-11e5-95a1-869922ddb770.png)
![2015-12-22_15 25 33](https://cloud.githubusercontent.com/assets/6391483/11958533/476d599c-a8c0-11e5-9542-66354db91873.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by HarryTurney** [comment]
Not fixed, just tried it and it still turned into a horse

**Comment by HarryTurney** [comment]
![2015-12-23_08 19 24](https://cloud.githubusercontent.com/assets/6391483/11973139/e504ba8c-a94d-11e5-8fa5-d30a45709fd1.png)
![2015-12-23_08 19 38](https://cloud.githubusercontent.com/assets/6391483/11973138/e504be1a-a94d-11e5-9a51-49a48e7c8926.png)

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.

**Comment by HarryTurney** [comment]
Why isn't this fixed yet? :(
![2016-03-03_22 05 02](https://cloud.githubusercontent.com/assets/6391483/13511247/5f6f2f52-e18c-11e5-8305-91db2812c176.png)
![2016-03-03_22 05 03](https://cloud.githubusercontent.com/assets/6391483/13511246/5f6d347c-e18c-11e5-8b06-06fb32ed418a.png)
![2016-03-03_22 05 00](https://cloud.githubusercontent.com/assets/6391483/13511248/5f727400-e18c-11e5-9bfe-8a8af919fac5.png)
