### ISSUE TITLE
Stuck in a chest room

### ISSUE THREAD

**Issue by mcleonida3000** [Wynncraft/Issues#2862]
So I was playing normally on WynnCraft. After the restart, I joined another server. I fell through the world and I died (I think) then I found myself in a SuperFlat world with some players that looked like could see the normal world and interact with it (I saw some of them killing mobs, that I couldn't see). I relogged, and I found myself in a room full of chests, with no entrance. I didn't touch anything. Also I tried to escape with a Ragni Teleportation Scroll, but I couldn't because "you are already in Ragni", it said. Can someone please tell me if there is a way out of there?
![2015-12-22_16 01 27](https://cloud.githubusercontent.com/assets/16402883/11958604/142c4eea-a8c9-11e5-9adb-5862a0843c97.png)
![2015-12-22_16 01 31](https://cloud.githubusercontent.com/assets/16402883/11958615/1da87ad4-a8c9-11e5-91b7-60ca23d86a12.png)

**Comment by Scoopedia** [comment]
Yes I have the same Problem I dont now why we have to wait was the support to.

**Comment by Scoopedia** [comment]
![2015-12-22_16 45 47](https://cloud.githubusercontent.com/assets/16403165/11959041/898594ce-a8cb-11e5-80b2-94f1495213ca.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by mcleonida3000** [comment]
Still there...
![2015-12-23_07 38 38](https://cloud.githubusercontent.com/assets/16402883/11972157/57cf1478-a948-11e5-8405-6d49fd43efdc.png)
Anyway if I use another character I'm ok

**Comment by brainscript** [comment]
@mcleonida3000 I think this is the Chest room with the equipment of the mobs filled by the Content Team as you can read [here](https://docs.google.com/document/d/1Riy4CUpLLwHB4iS7qfnDR0sEAwyE8wEjaAk9NUFGRMw/edit) I don't know if the room is still used after the Gavel Update.

Doing `/kill` with more than 3 soulpoints should fix your problem.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by mcleonida3000** [comment]
Solved with /kill, thank you all
