### ISSUE TITLE
The Maiden Tower bug

### ISSUE THREAD

**Issue by Aviee** [Wynncraft/Issues#2864]
On the The Maiden Tower quest theres a part where you have to kill a mob to get a helmet that you then give to an NCP I got the helmet from the mob that you had to kill and went to the NCP but the NCP wont accept it and says that I have to go to the mob and get the helmet when I already have. I tried going back to the mob like 5 times but it still wont accept the helmet. Video is down there showing it.

https://drive.google.com/file/d/0BxpqpjsMHbfDTk1EcU1uN3pMWnc/view

**Comment by Aviee** [comment]
Nvm I'm dumb and didnt know I had to put the helmet on so I could get into the tower...

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
