### ISSUE TITLE
No Rewards Bug

### ISSUE THREAD

**Issue by HeyItsMeTom** [Wynncraft/Issues#2865]
On completion of the "Lord of the Clock" quest, you're supposed to receive 64 emeralds. However, I didn't receive any emeralds for completing it (however, I did get the XP).

**Comment by mirajhall** [comment]
Are you sure you didn't get an emerald block? You may not have noticed it if you were looking for 64 regular emeralds.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by HeyItsMeTom** [comment]
Nope, I didn't get an emerald block. It happened on a couple other quests as well, such as the level 2 quest where you had to find the wedding ring with the rats.
