### ISSUE TITLE
Spawning in a "SuperFlatWorld"

### ISSUE THREAD

**Issue by EnderProLogic** [Wynncraft/Issues#2866]
Hello, recently I tried to spawn in as my assassin class and was teleported to a superflatworld since I don't have any teleportation scrolls I've been stuck for the past day.   Just wondering if anyone could provide me with a way out. 
Thanks 

My username is "Bigfoo"

**Comment by EnderProLogic** [comment]
Never mind I was able to use the /kill command and my issue was fixed

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
