### ISSUE TITLE
Arrow storm doesn't work and nobody responded to my previous post

### ISSUE THREAD

**Issue by brendon96068** [Wynncraft/Issues#2868]
If I use arrow storm it takes my mana and says that i cast it but nothing happens, iv seen multiple posts like this and its still not fixed or mentioned in the recent patch updates

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/2745

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Please don't spam the issue tracker just because you haven't gotten a response within a few hours.
