### ISSUE TITLE
Mage Class Deleted?

### ISSUE THREAD

**Issue by ThatGamingCat** [Wynncraft/Issues#2869]
When I logged onto Wynncraft today I noticed that instead of my mage class being the very first one out of the classes archer class was, and mage class wasn't even in the line with the classes. I'm really confused because I'm a level 56 mage and I was just doing the new gavel quests. Will I be able to get my   class back?! Please Help!

**Comment by HeyItsMeTom** [comment]
Did you accidentally delete it?

**Comment by ThatGamingCat** [comment]
No it would have put a up pop up menu if I wanted to delete it, today it was just gone.

**Comment by Verret001** [comment]
Strange...

**Comment by Trixter313** [comment]
If your issue is still occurring, please first make sure someone else hasn't posted it already, and if no one has, repost the issue. A massive closing sweep was done to clear out all of the already fixed issues. Thanks!
