### ISSUE TITLE
Craftmas Chaos cannot finish quest after logging out during dialogue.

### ISSUE THREAD

**Issue by pewpeed** [Wynncraft/Issues#2875]
I was on the last step for Craftmas Chaos (where you return to Santa to claim your reward) and I started the dialogue for him. I accidentally logged out during his dialogue and when I logged back in, I could no longer talk to him. I've tried spamming left AND right click to activate the dialogue again but the dialogue still doesn't restart, so I am unable to finish the quest. I check my quest book and it says the quest isn't completed yet and my xp bar hasn't gone up at all.

This issue may apply to other quests also but this is the first quest where I've had this problem.

**Comment by Trixter313** [comment]
Have you tried /fixquests ?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by pewpeed** [comment]
The issue that I had was not with pertaining to an item; the dialogue simply didn't start when I tried talking to Santa again. HOWEVER, I tried /fixquests and I got back an item (Corruption Relic Shard) that was used during the quest. I'm guessing that I'll have to redo the quest from that point. I'll reply/close this issue when I try redoing that part of the quest.

**Comment by pewpeed** [comment]
I talked to Santa again with the Corruption Relic Shard in my inventory and it started the dialogue again. What I believe that happened was that when I first started the dialogue, it took away the item and when I tried to start the dialogue the second time, it didn't start because Santa took the shard the first time. Thanks Trixter!

**Comment by Trixter313** [comment]
Happy to hear the issue is resolved! Have a great day!
