### ISSUE TITLE
Cant use Bobs Mysthic Bow because Quest got reseted

### ISSUE THREAD

**Issue by TheShadow129** [Wynncraft/Issues#2876]
i played for a long time and now i cant use my farmed gear because an fxking quest reset and i dont want to play anymore longer without my gear can you do something pls?

want play gavel but with my gear! :C

**Comment by Trixter313** [comment]
Could you elaborate a little bit more?

**Comment by TheShadow129** [comment]
i palyed so long for lv 75 klilled bob and now the fucking game says you cant use bobs mysthic bow first do the reincarnation quest yeah fuck you game DONE THAT A YEAR AGO

**Comment by Trixter313** [comment]
Do you meet all of the other requirements for the bow shown when you mouse over it? It could be one of those causing the issue but the message is just incorrect. Also, does it show the quest as being complete in your quest book?

**Comment by TheShadow129** [comment]
the only requirement that isnt completed is complete bobs reincarnation quest and like i said my quest got reseted

**Comment by Trixter313** [comment]
If your issue is still occurring, please first make sure someone else hasn't posted it already, and if no one has, repost the issue. A massive closing sweep was done to clear out all of the already fixed issues. Thanks!
