### ISSUE TITLE
Item bug, legendary helmet Pélier was destroyed/robbed of it's powers. 

### ISSUE THREAD

**Issue by Vamury** [Wynncraft/Issues#2879]
I got a new legendary helmet, Pélier, I identified it and put it on. The server was restarting so I jumped to another one, but when I got on I noticed that I had a lot less HP. I checked my gear and noticed that my helmet no longer had any stats. It's name had also been changed to what looked like the ending of a commandline. "EARTHDEFENSE","percent":85}.]} something like that. please help.I want my helmet back ;-;

**Comment by Trixter313** [comment]
Could you please provide screenshots? Thanks!
