### ISSUE TITLE
lost my indentified specture

### ISSUE THREAD

**Issue by Rfreaky** [Wynncraft/Issues#2882]
i tryed too equip my helmed and than it disappered

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!

**Comment by Rfreaky** [comment]
cant they give me the helmed back the item is extreamly rare and i only fond it once

**Comment by Trixter313** [comment]
The only way you could get another is to buy one from another player unfortunately.

**Comment by Rfreaky** [comment]
i dint played that game for around 1 year i saw that there is an update and the first Thing i see is that my helmed is bugged away and i cant get it back? not realy
