### ISSUE TITLE
Bug , I'm under the floor

### ISSUE THREAD

**Issue by iBenja** [Wynncraft/Issues#2883]
I want to ask plox get me out of here or something , here the capture :
http://imgur.com/6SPv8JE
My nick de minecraft is iBenja

**Comment by mirajhall** [comment]
You have plenty of soul points, just do /kill

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
