### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Deformity** [Wynncraft/Issues#2885]
I was told to report. Here it is.
http://imgur.com/WlrqAfY

**Comment by RusTy-TCat** [comment]
I had this aswell, just restart minecraft/your internet/both, this should work.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
