### ISSUE TITLE
Vanilla Items from Armorstand

### ISSUE THREAD

**Issue by Cubepuzzler** [Wynncraft/Issues#2887]
Hello Wynnteam
You are able to get Vanilla Items from Armorstands at x:1423 y:58 z:-2016 . Just right klick with an emty slot at the armorstand.

**Comment by Lukiwoki** [comment]
You're able to put items in the hands of Armorstands and take items from armorstands.
Not only that one armorstands, but ALL amorstands.

**Comment by Cubepuzzler** [comment]
thats right  but you can disable this with commandblocks. The team should do this.

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
