### ISSUE TITLE
Shattered Minds Progression Issue

### ISSUE THREAD

**Issue by Elemika** [Wynncraft/Issues#2889]
I was doing the quest, 'Shattered Minds', with a friend yesterday. We got pretty far into it, with it working fine, until the server crashed. I was in the middle of reading dialogue at the time, and it left off in the middle. I don't quite remember the NPC's name, but it was the lady who directs you to the house near the frog. When I came back onto the server, the quest did not progress from "find civilization in the forest" to whatever the next thing should be. The lady only says her first line out of 3, no matter how much I click on her. I tried going into the house, up to the attic, but was kicked out multiple times. My friend was able to finish the quest without problem, so it's a bug for me personally, it seems.

**Comment by Trixter313** [comment]
Have you tried using the command /fixquests ?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
