### ISSUE TITLE
Wheat Merchants

### ISSUE THREAD

**Issue by RichTheLord** [Wynncraft/Issues#2890]
I can't find any Wheat Merchant

**Comment by RusTy-TCat** [comment]
If you go to https://map.wynncraft.com/#/-853/64/-1677/min/0/0 most are marked on the map, but if you dont want to do that, one i know of is if you go out of ragni and turn left, there is one, also, next time you have a question that is not really a bug, I suggest you post it here, https://forums.wynncraft.com/forums/questions.89/

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
