### ISSUE TITLE
Flight in Distress - Missing detail.

### ISSUE THREAD

**Issue by Lukiwoki** [Wynncraft/Issues#2893]
There's a Puzzle, you get a hint to help you complete the puzzle, when you have completed the Puzzle, you then lose the hint (The hint is an item)

If you die and then go back, then you won't get the hint again, you'll have to solve the puzzle without the hint, if you don't remember what the hint is, then it's nearly impossible to complete.

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
