### ISSUE TITLE
Generator Amulet stats wrong

### ISSUE THREAD

**Issue by Ron123456** [Wynncraft/Issues#2894]
The amulet says that it gives:
+10 fire defense
+10 water defense
-10 air defense
+10 thunder defense
-20 earth defense
And in reality it lowers my water defense by 10, increases my thunder defense by 10 and lowers my earth defense by 20 and thats it.
And also the "+5% spell damage, +20 spell damage and +5% Exploding" doesnt do anything.

**Comment by Trixter313** [comment]
Are you sure nothing else you're wearing is affecting your stats? If not, thanks for the bug report! An admin should see this soon and hopefully will be able to help.

**Comment by Ron123456** [comment]
why is it closed?
