### ISSUE TITLE
Items Disappearing

### ISSUE THREAD

**Issue by LuckyJon13** [Wynncraft/Issues#2895]
When I was identifying my Bob's Mythic Daggers from before the Gavel update, I did it and I said I got it, but then the daggers disappearing. I'm not sure if this was because of server lag or if this is a bug. Would love if you guys could get me another pair and could fix either the lag or bug for everyone else.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
