### ISSUE TITLE
Unlisted quest givers and item sellers on the wynn world map

### ISSUE THREAD

**Issue by Everfeather** [Wynncraft/Issues#2896]
on the wynncraft world map there are npc's who aren't shown on the map.
https://gyazo.com/dd5853b6f52bd4867ebb11d876d8f0ca
This is a photo of where a quest is located but isn't on the map. There is also a item buyer in Ragni that isn't shown.

**Comment by meatloaf4311** [comment]
A lot of Merch's and quest points are mess up right now, most staff are working on the in game problems so it may be a while until this gets fixed

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
