### ISSUE TITLE
Loot II chest with no items in it.

### ISSUE THREAD

**Issue by grecolons** [Wynncraft/Issues#2901]
![2015-12-22_21 18 44](https://cloud.githubusercontent.com/assets/16406272/11966021/3609f474-a8f9-11e5-9dae-538c4a0e017c.png)
As you can see in the image, a chest (dont have coords) in a hole on the ground in the troll cave next to llevigar's city has no items on it. 
(I know I can take off items and then do screenshot, but didn't just want to repair a bug)

**Comment by ResistanceGaming** [comment]
Did you open the chest with your bow?  If so is Arrow Storm not working either?  If both of those are true, you must have dropped your bow at some point, triggering a bug.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
