### ISSUE TITLE
Assassin Spin Attack bug/glitch

### ISSUE THREAD

**Issue by SmileyAlec** [Wynncraft/Issues#2903]
I don't know if this is supposed to work like this but when I cast my spin attack spell on my assassin class every mob that I hit starts running around like CRAZY. I checked the wiki and it said that it SLOWS DOWN mobs which is really weird. If it is a bug/glitch then please fix it, if it is not then let me know. I am level 60 by the way.

thanks for reading.

**Comment by Trixter313** [comment]
This has changed since the Gavel update and the Wiki is outdated. Not sure if it's intentional or not.

**Comment by skillerfox3** [comment]
It is supposed to be an animation I guess? I always lose a lot of health when I do this since mobs sometimes get really close to you while doing this attack. They should fix they disable mob damage using this ability.
