### ISSUE TITLE
Reward glitch, No reward

### ISSUE THREAD

**Issue by baileyboy125** [Wynncraft/Issues#2904]
I just finished the quest 'The Bigger Picture' but when it came to give me the reward, I did not get the 5888 emeralds it said I did, however I did get the 571685 experience though. What can I do to get the emeralds I was entitled to? I was also stuck in a wall and I had to do /kill when the quest ended.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!

**Comment by dogelord117** [comment]
Actually I had the same issue too. I have screenshots.

**Comment by baileyboy125** [comment]
Here are some screenshots:
https://gyazo.com/ddbd0856def1d0dca516a483d08db9db
https://gyazo.com/03858bfe87bd15e8bfae8bfadb6aa53e
