### ISSUE TITLE
Class selection screen quest counter.

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#2906]
On the class selection screen, it displays my level 25 Assassin as having completed 54 quests; however, I have only completed 19. This is likely due to the fact that my level 75 Assassin has (according to the class selection screen) completed 54 quests, and it is not reading the numbers correctly. 

Also, "completed quests" seems to include quests that you have started but not yet completed. My Mage has only completed 51 quests, yet it displays as 54 quests.

Not sure of the reasoning behind this, but my level 75 Assassin seems to have completed 54 quests, even though I've only completed 52.

I may be wrong about something; please correct me if I am.

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help. Providing some screenshots would probably help!
