### ISSUE TITLE
Item losing

### ISSUE THREAD

**Issue by JakeTheBoss** [Wynncraft/Issues#2907]
I accidentally threw my infinity bow and i lost it 
![image](https://cloud.githubusercontent.com/assets/16406851/11967566/ddc10158-a8d1-11e5-81c6-3fafa5972254.jpg)

**Comment by TrashcanMan** [comment]
Unfortunately Wynncraft has a strict no-refunds policy so you can't get your bow back. However, there is probably somebody willing to sell you another if you ask around. I advise you to change your drop key to something further away, like H, to prevent further accidents.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
