### ISSUE TITLE
Taproot quest glitches 

### ISSUE THREAD

**Issue by Akamito** [Wynncraft/Issues#2908]
The tree parkour is broken most of the time, took me 8 tries after it keep teleporting me back to the beginning even though I was doing it right.

Also, this:

Basically I finished the quest and the parkour and it said to head back to Tiek. But instead she just tells me the dialogue that she did when I was following the pixie.

Please fix this ;(

**Comment by Trixter313** [comment]
Have you tried the command /fixquests ?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Akamito** [comment]
Nope, fixquests did not work.

**Comment by Trixter313** [comment]
Hmm, that's unfortunate. Hopefully an admin will read this soon and be able to help!
