### ISSUE TITLE
Quest item, Abysso Galoshes, vanished from inventory.

### ISSUE THREAD

**Issue by ReconDev** [Wynncraft/Issues#2912]
IGN: ReconTM
Character: Mage, 66

Hello. I was doing the quest "Lost Soles" where the server suddenly closed and came back with it gone and an item (chestplate) got corrupted or something in my inventory. I checked my enderchest, it is also not there.

I remember going back to Troms to retrieve it, and talking to the NPC "Ferndor" the moment when the server closed. Now, Ferndor requests for the shoes when I go talk to it.

I also tried redoing the last stage of the quest, "Beneath the Depths" just to get another shoes, by getting the "Ocean Treasure" and giving it to NPC "Javier", but I can't seem to repeat it again.

So I request for another "Abysso Galoshes", or make my mage character able to repeat the quest "Beneath the Depths". Thanks!

![2015-12-22_16 17 56](https://cloud.githubusercontent.com/assets/12772474/11968309/3c64ad86-a8c8-11e5-9e31-1eb18f840ba1.png)

**Comment by ReconDev** [comment]
Searched the forum and found out about /fixquest command, it returned the boots.

**Comment by Trixter313** [comment]
Good to hear =)
