### ISSUE TITLE
Glitched Quests

### ISSUE THREAD

**Issue by LarryRULEZ1** [Wynncraft/Issues#2913]
So, today my friend (jexmanor) and I (LarryRULEZ1) were doing the quests Finding the Light and The Hunger of Gerts Part 2. My friend was unable to complete both of the quests while I was able to complete both. We did the exact same thing. 

In Finding the Light, my friend was trying to talk to Ollie for the second time, and he was unable to. Even though he did the same thing I did, Ollie just repeated the same lines over and over again. In his Quest Book, it said, "Talk to Ollie." 

The next quest, The Hunger of Gerts Part 2, my friend had the same issue. We were in the third room of the thing under Jitak's house (I don't remember what it was called), and when it said speak to the Captured Gert, he couldn't click on it. It just said the line that he says when you speak to him before your Quest Book updates. When he tried to leave the room and go backwards, the Captured Gert didn't let him go and said, "Hey, talk to me first!" Something along those lines. In his Quest Book, it said speak to the Captured Gert. We don't know what to do.

**Comment by Trixter313** [comment]
Have you guys tried typing /fixquests ?

If that doesn't work, maybe try it on a different world?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by LarryRULEZ1** [comment]
We have tried both options to no avail. Also, the Hunger of Gerts Part 2 quest was fixed for jexmanor, but Finding the Light is still glitched. Ollie keeps saying, "Didn't you hear what I just said? Here, I'll write it down in your Quest Book."

**Comment by Trixter313** [comment]
Hmm, odd indeed. Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
