### ISSUE TITLE
Glitched Lore On Fiert & Glitched Name

### ISSUE THREAD

**Issue by BsnNick** [Wynncraft/Issues#2914]
The Glitched Lore in this picture happened after storing it in my enderchest. Before, the only bug was that the name said "Fiert??" except the two question marks were tiny and in small boxes (two): http://i.imgur.com/Zv3NCDW.png

**Comment by Hasteful** [comment]
I have this very same issue with a different item.  Whereas you can see the name, I see the opposite side.  It appears we are able to see the identification chances.

**Comment by Trixter313** [comment]
I believe this is related to #2679
