### ISSUE TITLE
Broken Spears

### ISSUE THREAD

**Issue by InvertedReaper** [Wynncraft/Issues#2915]
I don't know if this is a problem for other classes, but I've only had this problem on my Warrior. Whenever I log out and log back in, any unidentified spears I have in my inventory get bugged.

This one was an unidentified level 64-68 Rare spear
http://prntscr.com/9hg6j2

Can't remember what this one was
http://prntscr.com/9hg8a2

Also, they cannot be sold to Item Buyers or identified.

**Comment by Trixter313** [comment]
This seems to be a variation of #2679

We recommend closing the duplicate and instead adding any comments the the original issue. Thanks!
