### ISSUE TITLE
Quest Dialogue miss spelt and...

### ISSUE THREAD

**Issue by MrExzibit** [Wynncraft/Issues#2917]
Hey there is a bug with one quest called Rise of the Quarton. And the bug with it is there is one world miss spelled which instead should be saying "shipping" here you are the link including the picture http://prntscr.com/9hexn5

There is also yet another problem and that's in the conversation after you defeat Popo and you come back to Manager Nethea which is at the Karoc Quarry he/she tells you to go to the bandits mansion on the given coordinates or something however the coordinates are not given in the quest book.

**Comment by AshKernel** [comment]
1. Siphoning: 2. To take or transfer (something), often illicitly: siphon money from an account; siphon customers from a competitor. So this means the word is not misspelt.

2. Had the same problem. Hope they fix this!

**Comment by AshKernel** [comment]
I found the solution to 2.
The coordinates is on the paper!

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
