### ISSUE TITLE
Stuck in the ground 

### ISSUE THREAD

**Issue by Pigwidgeon33** [Wynncraft/Issues#2918]
When I logged on I should have been at Nemract but instead it put me on a flat land with the Nemract quest people. The problem eventually fixed itself, but when Nemract reappeared it made me stuck in the ground on my level 25 mage. Now I can not do anything, it will not let me teleport or move and I also can not use a teleportation scroll. If the developers can fix this, my username is Pigwidgeon33.

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should teleport you to the nearest visited town.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
