### ISSUE TITLE
extra class slots for vip and vip+ slots not working (vet rank)

### ISSUE THREAD

**Issue by crue911** [Wynncraft/Issues#2922]
i was vip for over a year and before the 1.12 update.
because of this i was given the vet rank.
now that gavel is out, the 4 extra class slots that you get when you are vip or vip+ do not work.
im not sure if this is because i have the vet rank or if its just not working right now.
i just hope for a fix soon since i want to start multiple classes.

**Comment by Trixter313** [comment]
I am a vet also and it works fine for me. It seems to only occur to VIP's but no VIP+'s have reported it. Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
