### ISSUE TITLE
Missing Skill Points

### ISSUE THREAD

**Issue by hooish** [Wynncraft/Issues#2923]
<img width="1440" alt="screen shot 2015-12-22 at 7 20 20 pm" src="https://cloud.githubusercontent.com/assets/16408393/11970073/d49056d2-a8e1-11e5-82f5-f9ceaaef4bd4.png">
Hi my minecraft username is hooish and I am having a problem with the skill points system. I am a level 43 as you can see in the picture above but I logged on and my skill points were all messed up so I went to the tower of amnesia and spent an LE resetting them and they just got messed up again. I only have 64 skill points and 0 left to assign, this is equivalent to a lvl 32's skill points so its hard to continue adventuring in gavel when I'm missing 11 skill points. Can you fix this or at least reset my skill points for free so I can try to reassign them again and not have to spend another LE. Thanks

**Comment by Trixter313** [comment]
Are you sure none of your armor or your weapon isn't subtracting any values? I suggest checking it again without armor on or a weapon in your hotbar to make sure.
