### ISSUE TITLE
Losing items with new identification system

### ISSUE THREAD

**Issue by Tostitokid** [Wynncraft/Issues#2924]
Hey, i had just spent the royal ticket of gratitude you get from the Wynn Excavation quest line on the fire amulet, and had just identified it when the server i was on reset, that or i was kicked out for reasons. anyhow, when i got back on, both the ticket and the amulet were gone, wasted. Can you please fix this issue and get my amulet back?

Or at least the ticket?

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
