### ISSUE TITLE
Glitch in Gavel quest Flight  in Distress 

### ISSUE THREAD

**Issue by Monkeysz** [Wynncraft/Issues#2925]
In this quest when you die while you are in the queen's ship you will respawn in a city/town. Once you do you won't be able to get back to the queen's ship so you are stuck and can't continue the quest. I'm myself am stuck. .-. help. (Yes I know there are still glitches but yea, here's one)
P.s I tried 2 times it is still happening. I /killed made it back there and the quest still won't continue. PLEASE HELP MEH.

**Comment by Trixter313** [comment]
Have you tried using the command /fixquests ?

**Comment by Monkeysz** [comment]
Why will you tell me a command to get back quest items. This bug is preventing you to not continue the quest because you can't go to the location anymore because it won't tp you back. Instead it puts you back to lexdale. Basically you can't go back to the queen's ship therefore preventing you to continue the quest.

**Comment by Trixter313** [comment]
/fixquests has helped people with more than missing items including stuck dialogue and being stuck in places etc. It's always a good start. Other than that I don't believe there's anything a non-admin can help with. I haven't done this quest personally yet so I don't exactly know the plot or anything like that that might help. Good luck!

**Comment by Monkeysz** [comment]
I AM STUCK AND CAN'T GO BACK THAT IS THE PROBLEM I CAN'T GO BACK TO THE SHIP.
