### ISSUE TITLE
Auto Join Not Working Properly

### ISSUE THREAD

**Issue by RanManGaming** [Wynncraft/Issues#2926]
Hi, I'm having an issue with the new auto join on wynncraft. I have it marked as off, but it still selects my first class and server. When I toggle it again, it still auto joins me on the same class on the same world, no matter if it says on or off. My IGN is RanMan_Gaming, and I would like to have this problem fixed ASAP. Thanks for reading!

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
