### ISSUE TITLE
Broken Class Selection

### ISSUE THREAD

**Issue by MegaSlowbro** [Wynncraft/Issues#2927]
When I join a server, I get stuck into a void and I can't do any commands or do anything. It won't let me pick a class and I can't play anymore because of this. Please help whenever possible. Thank you for your help.

**Comment by Trixter313** [comment]
Hmm, very odd. So even the /kill command doesn't work I assume?

**Comment by MegaSlowbro** [comment]
Nope, i dont have anything from my inventory and I can not do ANY command. /kill, /server, /class, etc.

**Comment by Trixter313** [comment]
Hopefully an admin sees this soon and will be able to help!

**Comment by AshKernel** [comment]
Possibly it's your computer/internet that's slow. It happened to me as well on my old laptop.

**Comment by intheshadowsXD** [comment]
I'm having a problem where choosing mage and archer will instantly hit an error and log me out but choosing warrior and assassin is okay. If i were to create a new character with mage or archer i would be able to play but i dont wan to retrain

**Comment by Verret001** [comment]
IntheshadowsXD, I have the extact same problem, my lvl 42 mage seems to be unable to load. Ive joined multiple servers but it just refuses to load. I have not fixed this problem yet but I have learned how to fix getting stuck n the void, You just have to delete and redownload your texture packs.

**Comment by Verret001** [comment]
Solution; You have to delete and redownload your texture packs.
