### ISSUE TITLE
Arrow Storm / Bolt Blizzard spell is not working

### ISSUE THREAD

**Issue by Drewiss1** [Wynncraft/Issues#2930]
Hello there i have noticed a massive bug and the Arrow Storm spell is not working and i use this to kill Bosses and i can't use it. Thanks :) 
Drewiss1

**Comment by Monkeysz** [comment]
Did you drop your bow because it triggeres it.

**Comment by Drewiss1** [comment]
Yes i did drop it as i play more than just Wynn I sent to reload it like a gun in GTA and dropped it opps
