### ISSUE TITLE
Some ID effects on weapons don't seem to work

### ISSUE THREAD

**Issue by RedMorcus** [Wynncraft/Issues#2931]
The 106/3s poison and 20/2s life steal on my zombified branch wand literally have no effect whatsoever. In fact, many weapon ID's do not seem to have any effect. What is going on here?

**Comment by AshKernel** [comment]
Have you tries hitting a mob and see if the poison damages him every 3 seconds?

**Comment by RedMorcus** [comment]
Yes, there really is no poison damage dealt from the weapon. There is a much smaller one, but that is from my boots.

**Comment by AshKernel** [comment]
How about putting the weapon in your first slot?

**Comment by RedMorcus** [comment]
Suddenly now it is working. Maybe the weapon needs to be used for a bit before the id effects actually apply?

**Comment by AshKernel** [comment]
Idk, putting the weapon in your first slot will make it your main weapon, which I think will only give the IDs the effects.
