### ISSUE TITLE
bank has items that can't be moved

### ISSUE THREAD

**Issue by ninjaneh** [Wynncraft/Issues#2938]
from way back when the server first started i decided to put random stuff in my bank, leading to a stack of arrows and a quest book being stuck in my bank forever
https://gyazo.com/648e5b66e2da20fce93940abb7e53f98
the empty slot on the left is the quest book, guess it lost its texture in the gevel update

ign:NinjaNEH

**Comment by Trixter313** [comment]
I suggest emailing support@wynncraft.com for this so it can be handled faster. Once they fix it, please close this issue here. Thanks!
