### ISSUE TITLE
Stuck in a block

### ISSUE THREAD

**Issue by Mooie12** [Wynncraft/Issues#2940]
my username is morganbeanbuck and whenever i log in as a mage im stuck in a block i need help please

**Comment by GamerGamerFTW** [comment]
/kill will tp you to closest village

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Mooie12** [comment]
thanks gamergamerFTW
