### ISSUE TITLE
Empty Loot Chests

### ISSUE THREAD

**Issue by BlahtheIceguy** [Wynncraft/Issues#2942]
I'm constantly finding loot chests that are empty, and I have no idea if this is intentional or not. It doesn't seem to be because I'm holding certain items either.

**Comment by Jorno10** [comment]
I'm having the same problem.

**Comment by grecolons** [comment]
Seen this problem 2 times in loot chest II and once in loot chest I.

**Comment by skillerfox3** [comment]
Only happened to me with Tier 1 chests yet.

**Comment by Jorno10** [comment]
I've had it happen to me multiple times with tier 3 loot chests as well
