### ISSUE TITLE
Huge Item Drops

### ISSUE THREAD

**Issue by FelixFlame** [Wynncraft/Issues#2943]
I was in Olux yesterday and this happened:
![2015-12-22_17 07 48](https://cloud.githubusercontent.com/assets/15987155/11974583/7d9505c2-a95d-11e5-9456-dbacda6cc688.png)

It was as if all the mobs that could spawn had been killed and there drops were littering the floor and if you picked up all the drops, more would spawn constantly, which means people would farm emeralds if this happens again.

![2015-12-22_17 07 13](https://cloud.githubusercontent.com/assets/15987155/11974617/be4b0d64-a95d-11e5-886b-965e18f6ee64.png)
![2015-12-22_17 07 23](https://cloud.githubusercontent.com/assets/15987155/11974618/c9e1a1a6-a95d-11e5-9fe5-4df4b2a69ec7.png)

**Comment by skillerfox3** [comment]
Haha, Yep.
Items do not stack that fast anymore. Since gavel the item stack distance has been decreased. I actually like it but it could be a bit laggy for some people.
