### ISSUE TITLE
LE is throwable

### ISSUE THREAD

**Issue by danny688** [Wynncraft/Issues#2944]
I just did the quest: Lost Royalty and I was in a bit of a hurry so I kept clicking the NPC and eventually threw the LE that came in that slot. And before the update the LE wasnt throwable. My IGN is danny688 please fix this bug, so it won't happen to others. And I would like to get my LE back.

**Comment by DarkDemonDragon** [comment]
Wynncraft has a strict no-refund policy, so unfortunately you will not be getting your LE back.

**Comment by danny688** [comment]
It will be fixed right? So it wont happen again right?
