### ISSUE TITLE
The server kick

### ISSUE THREAD

**Issue by wynncraftlupascu** [Wynncraft/Issues#2947]
It kick me and iv lost mai horse (wight) 37/40 and my daggers :(

**Comment by KingPandaZach** [comment]
i got banned for no resone like wtf i can get in lobby but not on my charecters!

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!

@KingPandaZach if you'd like to attempt to appeal your ban, please make a post here: https://forums.wynncraft.com/forums/ban-appeals.84/create-thread
