### ISSUE TITLE
Loosing Unidentified Armour when removing it from body.

### ISSUE THREAD

**Issue by bazimon** [Wynncraft/Issues#2952]
I just went on the server for the first time Post:Gavel Update and saw that I had teleported into the new Server Update Room. This was fine, except I checked my inventory and saw that the majority of my weapons and armor was renamed as being unidentified (everything but my helmet, the Pélier and a few weapons). I had something like 2 empty spaces in my inventory, so in order to identify my armour, I planned to removed it one by one from my body, however, as soon as I removed my pants 3 error messages popped up saying something along the lines of ''You cannot wear these items because they have not been identified" (I was unable to get the exact message because I logged out soon after). The game automatically put my pants in my inventory but my chestplate and shoes disappeared. I checked the floor around my person, but they had not been thrown on the ground and none of the pieces of armour had been glitched as being invisible in my inventory so I assume both my chestplate and my shoes have been permanently deleted...
This is quite annoying because I had some great pieces of armour which are now gone...

IGN: CrafterBazimon

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. I suggest exploring around and finding all of the awesome new armors to replace the lost items. We'd appreciate it if you closed this issue. Thanks!

**Comment by bazimon** [comment]
I completely understand, I just wanted to report this because I hoped that this could be fixed so other people don't suffer from the same issue.
