### ISSUE TITLE
Book piles in weird place(s)

### ISSUE THREAD

**Issue by EdamCheese** [Wynncraft/Issues#2958]
I don't know if this is the right place to post this, but I'm unsure of where else this would go...

With the Gavel update resource pack came some textured blocks, mainly for atheistic purposes. The daylight sensor was re-textured into a book pile and this has had an effect on some tables.

The one I know of is at -87, 56, -2486 and is on the balcony of the barn on Rooster Island. It appears this was a table using a daylight sensor, but has been slightly broken by the texture pack.

![book pile 2](https://cloud.githubusercontent.com/assets/10776644/11976808/e25070ee-a973-11e5-8961-00740fe148d3.png)

There are probably other problems like this around the map, but this is the only one I know of.

If this need to go somewhere else, please tell me so I can change it.

**Comment by DarkDemonDragon** [comment]
Idk I mean a random daylight sensor there would look just as awkward as a pile of books balancing on a fence.
