### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by CrystalAngel243** [Wynncraft/Issues#2964]
I teleported to Nemcrat but it looked like a flat world, then I rejoined and I'm stuck in a wall and now I can't rejoin...please help me -_-'

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should teleport you to the nearest visited town.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by CrystalAngel243** [comment]
Thank you sooo much! I was so worried I would be in that wall FOREVER!
