### ISSUE TITLE
Pirate Queen's Ring of Rubines changed in a JSON-String

### ISSUE THREAD

**Issue by essem2** [Wynncraft/Issues#2966]
after i logged in today it changed in this and got removed from my ring slot...
http://imgur.com/cKqFon8
i hope this will be fixed soon and i'll get a fixed ring or so ^^

~DevPixel

**Comment by jexmanor** [comment]
The same thing happened to me when I got on to Wynncraft. I tried re-logging and server hopping. The ring still remained the same, yet my other items are working fine.

**Comment by ed58** [comment]
same for me
