### ISSUE TITLE
Glitched in Y=12

### ISSUE THREAD

**Issue by AlbertovoladorMC** [Wynncraft/Issues#2967]
Hi, when I log in with an archer class I spawn in x= -934 y= 12 z= -1423 and I cant teleport or anything, and every time I log in I move one block up. Help

**Comment by TheWiseDisorder** [comment]
tried /kill (this will cost 2 soulpoints)

**Comment by AlbertovoladorMC** [comment]
Thank u so much, didn't thought I could /kill

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
