### ISSUE TITLE
stuck in the ground

### ISSUE THREAD

**Issue by budderfactory** [Wynncraft/Issues#2972]
well i acidently clicked a super flat world and am ow stuck in the ground and need admin help to get out teleport scrolls dont work because im in the ground and cant click the air

**Comment by Lukiwoki** [comment]
Do /kill
then you'll kill yourself and respawn in a nearby city.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
