### ISSUE TITLE
Identify Bug | Please fix it!

### ISSUE THREAD

**Issue by tttre** [Wynncraft/Issues#2973]
Hey Guys,
I have found a Bug....
When you drop a unidentified Item on a ground, it changes the texture to the model of the identified Item, so you can see wich you want to identify and wich not...
Hopefully you can fix that Bug

Best Regards
-Ciaran-
aka. Feasgar'Ciaradh

**Comment by DAV1DCRE8R** [comment]
I was going to post this one, too.
It seems this bug sprouted within the recent patch.

**Comment by tttre** [comment]
Yes
