### ISSUE TITLE
Weird name glitch

### ISSUE THREAD

**Issue by MobSlayers9** [Wynncraft/Issues#2974]
I had 2 spears, one was unidentified and one I just identified, then they turned into things with the name something like Ik-El-Vyyyyn and they are useless now, they cant be identified or sold, and they only do 1 dmg, the same as punching. Here are some screenshots of the 2:

![2015-12-23_09 48 54](https://cloud.githubusercontent.com/assets/7538417/11978925/395abf46-a95d-11e5-927d-b2ec5b404e75.png)

![2015-12-23_09 48 56](https://cloud.githubusercontent.com/assets/7538417/11978928/3bd44dbe-a95d-11e5-9f6b-a7672cf56e69.png)

**Comment by Lukiwoki** [comment]
I have experienced the same.
My friend with the same ring has also experienced this.

![](http://i.imgur.com/w3HIJxP.png)

**Comment by MobSlayers9** [comment]
Ik it sucks...
Btw how did u get lvl 80 already????? Its only been out for 2 days
