### ISSUE TITLE
Bob's Tear

### ISSUE THREAD

**Issue by mvcuijk** [Wynncraft/Issues#2981]
so i killed bob now like 60 times but i don't get the tear and if i ask other people of they can tell me if they see bob they say i have 2 tears and they killed him 1 time. so WTF is wrong with that bob

**Comment by Lukiwoki** [comment]
You're probably very unlucky.
Also; Try to use gear with loot bonus.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
