### ISSUE TITLE
Skill point bug

### ISSUE THREAD

**Issue by Chri630** [Wynncraft/Issues#2986]
While playing I've noticed my skill points have been rolling back. I was trying to get my strength to 25 so I could use a weapon but when I finally had enough points for some reason my points had reset to 20 while I remember them being 24. I highly doubt it's just me and I'd like a refund or something cause I worked really hard to get to 25 strength, I was literally this close but ya it was 20.

**Comment by TheDerpyMan** [comment]
Did you know that Items' stats affect your Skill Points. Maybe you had an item that gave you +5 strength and you're not wearing it. If it isn't for items, it might be a bug.

**Comment by Trixter313** [comment]
TheDerpyMan probably has it correct.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
