### ISSUE TITLE
fierte bug id

### ISSUE THREAD

**Issue by yairkaraso** [Wynncraft/Issues#2987]
Hey. after the last update i got problem with id the fierte it lvl56 spear legendery. 
![2015-12-23_19 29 18](https://cloud.githubusercontent.com/assets/16417060/11981529/299a60da-a9ac-11e5-8418-8ae490cc4d00.png)

**Comment by TheDerpyMan** [comment]
It's not converted to the new item thingy. It has to be updated, just wait a little and it will get repaired (like a day or something like that)

**Comment by Trixter313** [comment]
Duplicate of #2679 

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!

**Comment by yairkaraso** [comment]
ok thx
