### ISSUE TITLE
My friend 's bug in a wall

### ISSUE THREAD

**Issue by blueleon69** [Wynncraft/Issues#2988]
my friend is bug after slept in a bed can you help me please?

**Comment by Pokextreme** [comment]
Can you be a little more specific, try/kill

**Comment by blueleon69** [comment]
after sleep in a bed he was block in the wall of the house

**Comment by blueleon69** [comment]
we have resolute the probleme thanks you very mutch!

**Comment by Pokextreme** [comment]
please close the thread then, Happy to help C:
