### ISSUE TITLE
Overhead name glitch

### ISSUE THREAD

**Issue by CaptainFireStorm** [Wynncraft/Issues#2990]
i cant see the names/levels of mobs/npcs. i can see player names but its been doing this ever sense the gavel update. ive asked about and it doesnt appear to happen to everyone. the only two cases i know are me and my brother. if someone can help it would be great. and reloging doesnt work

**Comment by Lukiwoki** [comment]
Switch to another update of Minecraft. (This should fix it)
I use 1.8.7 and it works.

**Comment by CaptainFireStorm** [comment]
that worked, thank you for the help

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
