### ISSUE TITLE
The creation of classes is having issues

### ISSUE THREAD

**Issue by lapron3000** [Wynncraft/Issues#2991]
I'm a VIP and when i hover the "create a new class slot", it says " you need VIP or VIP+ to use this slot" then i try to click it, and it doesn't do anything. 

This is weird because just yesterday(12/22/2015) i created a new archer class. 

Here is a photo:
![magic](https://cloud.githubusercontent.com/assets/16417279/11982304/f38a26b2-a977-11e5-89e7-60630496a841.png)

**Comment by lapron3000** [comment]
maybe a bug, or it's just me.

**Comment by Lukiwoki** [comment]
Same thing happens to me.

**Comment by Trixter313** [comment]
It seems to happen to VIP's only but works fine for VIP+'s. Odd.

**Comment by lapron3000** [comment]
I think i know my solution then....!!!!! BUY VIP+!!!!!
