### ISSUE TITLE
Glitched Weapon

### ISSUE THREAD

**Issue by Antsatme** [Wynncraft/Issues#2994]
My mage weapon is glitched. Here is a screenshot: http://prntscr.com/9hqyxw

It was previously 20-30 damage with (I think) 46% Soul Point recharge

**Comment by Lukiwoki** [comment]
You forgot to make a description.

**Comment by Antsatme** [comment]
@Lukiwoki Sorry.

**Comment by Lukiwoki** [comment]
I have the same problem with one of my rings.
And I know that one of my friends with this ring, have the same problem.


![](http://i.imgur.com/w3HIJxP.png)

**Comment by Antsatme** [comment]
The problem with mine was that the name changed yesterday, but the wand actually worked. Today, the wand cannot do any damage or spells.

**Comment by TheDerpyMan** [comment]
Because as you can see, its name is TestId Soulpoints. That means is a wand used for testing the features in the game. Once they finished testing, the Wand will be disabled. Just get another one and we're done here :D
