### ISSUE TITLE
Leggings Relic Door

### ISSUE THREAD

**Issue by PinkWool** [Wynncraft/Issues#2995]
I've opened the door twice but never been able to get the relic. now that i could get it i cant open the door. im doing the same thing i did. is there something i missed?

**Comment by Lukiwoki** [comment]
Can you describe yourself a bit more? What door are we talking about? Where is it? Maybe include some pictures.

Btw. I believe Relics are broken.

**Comment by PinkWool** [comment]
lololl sorry. its the legging relic door.

**Comment by TheDerpyMan** [comment]
Maybe is something about how you did it, because I got the Relic Leggings already. I got the full Relic Set. ( It gives 360 health, +15% spell and melee damage and xp bonus )

**Comment by PinkWool** [comment]
i have all but the leggings.
im kinda gooing insane
ive opened it twice before i did canyon condor

**Comment by PinkWool** [comment]
ive been trying for an hour straight ;-;

**Comment by TheDerpyMan** [comment]
It's not bugged or broken.
Try changing the server or reviewing the way to open that door.

**Comment by PinkWool** [comment]
)))): i have

**Comment by PinkWool** [comment]
watched every guide and server hopped

**Comment by TheDerpyMan** [comment]
Maybe it's lag. Try tommorow or when the server is a lot more empty. Good luck with that.

**Comment by PinkWool** [comment]
will do. thanks.
