### ISSUE TITLE
Void glitch

### ISSUE THREAD

**Issue by kenny123723** [Wynncraft/Issues#3004]
Whenever I try to enter into one of the servers, I spawn and quickly fall into the void.

**Comment by TheDerpyMan** [comment]
Just die in void and then see if you spawn. If you keep falling down infinitely, try using /kill. If It doesn't works, maybe the game doesn't render the chunks. (Game = You / Server)

**Comment by kenny123723** [comment]
Still doesn't work. It shows me as if I were choosing a class, with no armor or inventory. I believe it spawns me at the new Gavil spawn then I just drp and fall into the void

**Comment by lowbobcelso** [comment]
I have the same problem. When i enter a lobby and shuld suposed to chose a class i fall into the voide.
I recorded it https://www.youtube.com/watch?v=FJM1T_mL8sQ

**Comment by kenny123723** [comment]
thats exactly what I have! At least I know I'm not the only one with the problem now.. XD
