### ISSUE TITLE
Weapons not giving buffs to the stats 

### ISSUE THREAD

**Issue by Slaten6** [Wynncraft/Issues#3005]
I logged on today to find that I couldn't wear my Crystal leggings. I was confused because it worked just fine yesterday. So I looked around all my gear to see if anything changed (I have not reset my skills at all) I found out the issue was that my Ethereal was not giving me the +8 Agility Boost that it originally gave me enough Agility to use the crystal. I swapped my Ethereal for my Bobs Mythic which gives +7 agility instead of 8 which is still more than enough to make my skill over 30 but that didn't work either this is a bug that I'd would appreciate be fixed. Thank you

**Comment by TheDerpyMan** [comment]
I think there's a delay when you switch between 2 weapons. Maybe try shooting with it, hopefully it will fix the problem for a time, but not the bug entirely.

**Comment by Slaten6** [comment]
no it didn't ;-;

**Comment by Trixter313** [comment]
Someone posted that for it to update you have to switch your selector to a different hotbar position then switch it back to the item. Maybe try that?
