### ISSUE TITLE
Unable to choose class

### ISSUE THREAD

**Issue by MrNinjaBen** [Wynncraft/Issues#3006]
I wanted to play wynncraft because of the massive gavel update, and when I went to choose the archer class, my primary class, It just exited the menu and left me alone in the wool room and after a few second, sent me back to the hub. Any help is appreciated, thanks.

**Comment by ibrendon456** [comment]
I am having the same problem. I am unable to play my level 56 mage. When I go to the character selection or /class function, I select the character but due to some error, I am unable to play as that character and ONLY that character.

**Comment by intheshadowsXD** [comment]
I having issues with my archer and mage

**Comment by shacharss** [comment]
Same with my level 50 archer, Someone help!!!!!
IGN: shacharss
