### ISSUE TITLE
Shreks house is missing?

### ISSUE THREAD

**Issue by Louis-D** [Wynncraft/Issues#3007]
This picture expains everything... :+1: 
![2015-12-23_21 57 00](https://cloud.githubusercontent.com/assets/6114858/11984947/5086a4b0-a9c0-11e5-85c3-88ece63fcdec.png)
This problem is on server 48.

**Comment by TrashcanMan** [comment]
Try going on a different server, usually it's just one or two of them that are broken.

**Comment by skillerfox3** [comment]
This is just a chunk loading issue. Pressing _F3 + A_ will fix this. If not relog.

This issue can be closed!
