### ISSUE TITLE
Dropping Unidentified Weapons on the Ground Shows Texture

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#3008]
When you drop an unidentified weapon on the ground, it will show what the weapon will look like once you identify it.

**Comment by TheDerpyMan** [comment]
Actually, it updates the texture because, for example a bracelet is a fence, once you drop it, becomes a ring. I'm not really sure if it reveals its appearance, but I don't think so.

**Comment by awemanrank100** [comment]
Either I'm really lucky or it does, as I've tested it.
