### ISSUE TITLE
no xp bug and broken ring

### ISSUE THREAD

**Issue by dragonhunter9001** [Wynncraft/Issues#3010]
ok so first bug i want to touch on is a xp bug  i have been having although my guild xp is at 0 after i have completed these quests my xp bar is still at 0 (im level 75) this bug might have been due to either lag or my internet (my internet is not the best :/) or something else im not sure
flight in distress:level 75
acquiring credentials:level 74
shattered minds:level 70
memory paranoia:level 67
the worm holes:level 54
rise of the quartron:level 49
heart of llevigar:level 41
another bug is one of my rings (pirate queens ring of rubies) is bugged out when i logged in i found it like this im not sure what caused it and i cant put it on 
![2015-12-23_15 30 10](https://cloud.githubusercontent.com/assets/16418820/11985477/c641fb2c-a98a-11e5-903f-8fcdde8d1155.png)

**Comment by TheDerpyMan** [comment]
Your leveling bug has to be fixed by the staff. The bug with the ring will be fixed soon.

**Comment by TheDerpyMan** [comment]
Because it's a visual and probably a game issue that will be fixed after a few weeks.

**Comment by dragonhunter9001** [comment]
its not just a visual glitch cause i cant but the ring on its no longer a ring just a glitched ring but how do i get in touch with a mod?

**Comment by RusTy-TCat** [comment]
Try looking on the forums and on the right sidebar there is "Current online staff" or something
