### ISSUE TITLE
Flight in Distress Bug

### ISSUE THREAD

**Issue by jackson30007** [Wynncraft/Issues#3011]
Hello, I was doing the Flight in Distress Quest when I was teleported to the cell on the pirate ship with the locksmith. He told me how to get out of the cell and to go find the key so I left the cell and tried to find the key. At the time, the server I was on was experiencing immense lag and I walked over to a door that had a pressure plate next to it. I stepped on the plate, the door opened, and I walked inside. I was then teleported to a room where I was surrounded with barriers, then the server instantly crashed. I rejoined to find myself trapped in that same room for all of eternity. Here is pictures of the room I am doomed to be stuck in for the reset of my life on Wynn.

1) https://gyazo.com/d75240bc379b10c6024e78962b0711c8
2) https://gyazo.com/3bcc66c300c03018d1402104cf9875ff
3) https://gyazo.com/a470dba9c988a1a562310d85b978900d

Would appreciate some help on getting out of this room.

If you have to do it manually im stuck in the room on my Hunter class and would prefer not to be killed. I just want to finish the quest.

Thanks,
jackson30007

EDIT: Decided to try /kill and am no longer stuck in the room, however, when I tried to go back and retry the quest, I was teleported to the start of the quest, when the ship is fully intact and I cannot go back to where I was. My quest book says "Escape the cell and finalize they key to reach the pirate queen." Any way I can be teleported back to the location I need to be at?
PS: You should make it so when a player dies in a quest like that they are teleported to the right location to finish the quest. If you were to die to mobs you would have the same problem as me.

**Comment by dragonhunter9001** [comment]
you can get back all you have to do is skip everything and teleport to the next area and keep doing that until you get there

**Comment by jackson30007** [comment]
Where would I have to go to teleport? It only teleported me when I finished a part of the quest, but since I have already finished the part I need to teleport back, it wont let me do it again.

**Comment by jackson30007** [comment]
Alright, I retried going through all the motions of the quest, and I finally got back to where I was. It was confusing and hard to do so I still think it should be made so when you die you are teleported to the correct spot on a quest like that but at least it is possible to finish the quest.
