### ISSUE TITLE
Mislabeled Weapon?

### ISSUE THREAD

**Issue by TheRealToxictoaster** [Wynncraft/Issues#3012]
So I went to identify all my items while I could, when I got to my assassin's stuff... I got this thing. To me, it looks A LOT like a bow. It is held like a bow, it even has string?! This thing is "probably" a bug, but who knows? I have no problem stabbing people with a bow as an assassin.

![2015-12-23_15 46 15](https://cloud.githubusercontent.com/assets/16418999/11985719/55755f94-a98d-11e5-957b-824336ef542a.png)

![2015-12-23_15 54 16](https://cloud.githubusercontent.com/assets/16418999/11985788/f7be4a22-a98d-11e5-9643-dd57804b7843.png)

![2015-12-23_15 54 10](https://cloud.githubusercontent.com/assets/16418999/11985791/ff5f19c8-a98d-11e5-86e3-a9bedf18d3f6.png)

**Comment by TheDerpyMan** [comment]
They'll fix it in time. The Gavel just got released and they still got a lot of bugs that are gonna get fixed. Anyway, thank you for submitting this bug.


(I'm not a part of the staff)

**Comment by TheRealToxictoaster** [comment]
Yeah, but its still better to show a bug then wait and hope they found it :p.
