### ISSUE TITLE
I lost an essential quest item!

### ISSUE THREAD

**Issue by Raccoonial** [Wynncraft/Issues#3014]
I was on the Volcano Island and I was starting the quest "Wynnexcavation Part C". Right after I had given the quest NPC my "Purple Crystal Shard", the server shut down, and I was kicked to the lobby. There was no warning of the world restarting.The NPC was not finished talking, so he took my shard, but the quest wasn't initiated. When I rejoined in another world, I didn't have the shard, and the quest wasn't started. I tried "/fixquests", but it didn't do anything.

**Comment by TheDerpyMan** [comment]
Try /fixquests another day. Wait for it to be fixed. Idk how you could repair that. Good luck getting the shard.

**Comment by Raccoonial** [comment]
bump
