### ISSUE TITLE
Stuck in Memory Paranoia

### ISSUE THREAD

**Issue by Zetonix** [Wynncraft/Issues#3015]
When i wanna get through the rift at the end, it teleports me in a black room with pressure plates, and i can't do anything. I tried twice on different server, and it still not work.

**Comment by TheDerpyMan** [comment]
Try /kill, that's my only way I know you could fix it. But I'm not 100% sure about that, but just try.

**Comment by Zetonix** [comment]
I did escape this way, but i can't end the quest
