### ISSUE TITLE
Murder Mystery Quest ending Bug.

### ISSUE THREAD

**Issue by NinjaElfBoy** [Wynncraft/Issues#3016]
Hello, today I want to report a bug about this quest: Murder Mystery. Once I talked to the Innkeeper (Aka, the murderer of the victim). I went to Captain Lorias and attempted to claim my reward. However, Captain Lorias still says the same dialogue over and over which he said at the beginning. Please fix this, as I can't complete the quest!

**Comment by Zetonix** [comment]
did you find the murderer's weapon before talk back to Lorias ?

**Comment by Akamito** [comment]
Yeah, this happened to me as well with the "taproot" quest. Hopefully it will be fixed soon.

**Comment by NinjaElfBoy** [comment]
@Zetonix, what is the murderer's weapon?

**Comment by Zetonix** [comment]
You will find a 'suspicious bag' at the murderer's house,in the second floor, in a little room
