### ISSUE TITLE
great bug!

### ISSUE THREAD

**Issue by SteveClinton** [Wynncraft/Issues#3017]
When everyone leave from the world, maybe because the world went down,  i lost 6 le and my horse well thanks a lot! And because of that damn policy i wont get the stuff back... thanks again ^^

**Comment by SteveClinton** [comment]
well if i at least get like 3-4 le back it would be nice.

**Comment by TheDerpyMan** [comment]
So, the server went down, maybe because of a non-announced restart. Where was your Horse's Saddle? Where were your LEs? What were you doing at the moment of the Shut down?

I'm trying to help because the Staff gives no fucks about answering these things..

**Comment by SteveClinton** [comment]
well before the restart i put my saddle and the le in my chest... then it dissapeared.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. Once a server restarts any items on the ground are gone and if it hasn't shown up within a few hours of losing it, it's probably safe to say it's gone for good. We'd appreciate it if you closed this issue. Thanks!

**Comment by SteveClinton** [comment]
well that doesnt help. What if i lose items again? And stop copy the same text of other issues...

**Comment by wynncraftlupascu** [comment]
It hepend to me 2 with a white horse 37/40

**Comment by SteveClinton** [comment]
and? Horses arent that important anymore.
