### ISSUE TITLE
Corrupted Grian Head

### ISSUE THREAD

**Issue by 8BitShadows** [Wynncraft/Issues#3020]
The Corrupted Grian enemy is using the wrong head, as Grian has a new skin which is no longer Link.
![2015-12-23_15 37 02](https://cloud.githubusercontent.com/assets/5266948/11986956/8f3a54c0-a98b-11e5-8104-fac8c161abb1.png)

**Comment by TheDerpyMan** [comment]
I saw that too. They'll fix it when a staff will give a flying f*ck about this. It's just visual, get over it.
