### ISSUE TITLE
Identified Items Unidentified After Update

### ISSUE THREAD

**Issue by nebman227** [Wynncraft/Issues#3022]
I haven't played wynncraft in a long time (months) and decided to get on today. However, I couldn't do much because every item that i owned that was identified, including my equipped things were marked unidentified. It should also be noted that all of my skill points were reset.
![2015-12-23_18 32 36](https://cloud.githubusercontent.com/assets/16419866/11987385/011b6c10-a9a4-11e5-8178-5a7513cad644.png)
![2015-12-23_18 32 37](https://cloud.githubusercontent.com/assets/16419866/11987386/0129bdb0-a9a4-11e5-9721-f8bd0c514f44.png)
![2015-12-23_18 32 38](https://cloud.githubusercontent.com/assets/16419866/11987388/013b094e-a9a4-11e5-8534-6fbaa075bb71.png)
![2015-12-23_18 32 40](https://cloud.githubusercontent.com/assets/16419866/11987387/0137f614-a9a4-11e5-801d-0cf6ef290ca9.png)
![2015-12-23_18 32 29](https://cloud.githubusercontent.com/assets/16419866/11987389/013f3c58-a9a4-11e5-999f-f706bd43f7be.png)
![2015-12-23_18 32 35](https://cloud.githubusercontent.com/assets/16419866/11987390/0140b3d0-a9a4-11e5-9788-26c6a4fe0725.png)

**Comment by Akamito** [comment]
This is intended. The item system has been completely reworked so they are giving you a chance to restat your points and to get the new bonuses on armor. Pls close this issue as it's been addressed. Also, you should read the forums and the patch notes to fully understand before reporting "bugs"
