### ISSUE TITLE
Servers full

### ISSUE THREAD

**Issue by Chri630** [Wynncraft/Issues#3023]
All servers are full. Please help

**Comment by Chri630** [comment]
"Could not find a server to connect to, please report" is what is says I cant even join a lobby.

**Comment by RusTy-TCat** [comment]
Try restarting you game/router/both, this has happened to me and this worked

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
