### ISSUE TITLE
Can't log in to wynncraft

### ISSUE THREAD

**Issue by MrWhaleMan17** [Wynncraft/Issues#3027]
I can't login to wynncraft it says unknown host, the ip I have is: play.wynncraft.com. Should be the right ip but its not working, is the server down or something?

**Comment by XxStartRestartxX** [comment]
This is happening to me too!

**Comment by MrWhaleMan17** [comment]
Can someone please help?

**Comment by XxStartRestartxX** [comment]
Do you own a mac of some sorts?
