### ISSUE TITLE
Cant use my armor!

### ISSUE THREAD

**Issue by GamerGamerFTW** [Wynncraft/Issues#3041]
After the new update it asks me to indentify my armor and weapons, i cant, even if there unique+, so i cant do any quests, duels, xp farming, anything. Game has stopped for me.

**Comment by MrWhaleMan17** [comment]
Do you have enough emeralds?

**Comment by GamerGamerFTW** [comment]
Yes

**Comment by GamerGamerFTW** [comment]
It says the same if you try to id not unique+ items

**Comment by MobSlayers9** [comment]
Can you post a screenshot of the items? Some didn't convert or a weird, i have a few like that

![2015-12-24_08 48 49](https://cloud.githubusercontent.com/assets/7538417/11995261/a73352c6-aa1b-11e5-980f-3e0ddeea2b5b.png)
![2015-12-23_09 48 54](https://cloud.githubusercontent.com/assets/7538417/11995270/ca2e4470-aa1b-11e5-8eac-3ba678d1cae4.png)
![2015-12-23_09 48 56](https://cloud.githubusercontent.com/assets/7538417/11995274/cc9549ca-aa1b-11e5-838e-5b0a60bb127d.png)

**Comment by GamerGamerFTW** [comment]
looks like normal not-identified item, try identiifying not unique or better items and thats what it says when i try to id unique+ items
