### ISSUE TITLE
Assasain Spin Attack does crazy knockback?

### ISSUE THREAD

**Issue by NuclearImpact** [Wynncraft/Issues#3045]
Should Spin Attack deal knock-back to enemies, like, spin them around the player? It feels weird, and this gives an advantage to enemies who are stronger close to you. Maybe this is intended, however, multihit doesn't seem to kb anymore. Maybe they switched?

**Comment by BenjaminPlayz** [comment]
I have the same problem, when I am in ToL grinding Trainers when they do their special heal ability it happens they spin around me and do over 3k dps.
