### ISSUE TITLE
Items not converted

### ISSUE THREAD

**Issue by xXJetstreamXx** [Wynncraft/Issues#3049]
I just started playing Wynncraft with the new extension but I have a problem:

my Spear didn't got converted to the new system.
Here a screenshot:

![screenshot_1](https://cloud.githubusercontent.com/assets/10688123/11994712/a0c43798-aa43-11e5-92dc-0dd5c80619da.png)

I hope I can still do this.

Greetings

**Comment by xXJetstreamXx** [comment]
Oh yeah, not to forget that my whole armor is now gone,
I can't use my helmet because I somehow need strength
and that I have to identify EVERYTHING before I can use it.

Sorry for saying this, but for me the new extension made Wynncraft something awful, could you please set up servers for players that just want to play the old Wynncraft? I really liked the game but I can't play it like that...

**Comment by MobSlayers9** [comment]
I think it is just a few items, all of mine were converted except the Fierte
I hope they can fix this, it sucks to lose a ledgendary item :(

![2015-12-24_08 48 49](https://cloud.githubusercontent.com/assets/7538417/11995240/5491d59c-aa1b-11e5-8f6e-b139d5079170.png)

**Comment by xXJetstreamXx** [comment]
Yeah, I hope so too ^^
