### ISSUE TITLE
Can't use all 10 Character Slots as a VIP

### ISSUE THREAD

**Issue by Chewsterchew** [Wynncraft/Issues#3056]
Just look at this. :(

![2015-12-21_09 42 55](https://cloud.githubusercontent.com/assets/8278263/11995769/24c44bd2-aa1c-11e5-8456-7ace12e4c6c6.png)
![2015-12-21_09 43 17](https://cloud.githubusercontent.com/assets/8278263/11995770/24c55a54-aa1c-11e5-8738-57363ab8bc28.png)

**Comment by grecolons** [comment]
Yep, I'm also VIP and can't use all the char slots.

**Comment by skillerfox3** [comment]
Confirmed!

**Comment by Chewsterchew** [comment]
*Theory*
**Those final 3 slots are VIP+?**
