### ISSUE TITLE
I Have My Armor And Its Gone......

### ISSUE THREAD

**Issue by LockeC** [Wynncraft/Issues#3065]
[Title] And How This Happened So You Know Now Armor Cant Be On If Un-Identifyed And My Used To Be Gargantuan, Holy [Something] Pants, And My Assasins Hood Is Gone....... My Inventorys Full And Poof Gone..... Id Like Someone Admin Help Me With This Ive Played To Long To Just Lose My Best And ONLY Armor.... My Other Armor Was Fine... Had One Slot Open And My Boots Made It Im Level 46 And I Think Only Holy [Something] Pants Were 45.

Please Help Me.....

**Comment by Schnidischna** [comment]
got the same issue! All my armor was legendary :cry: Is there any chance to get my items back? pls fix!
