### ISSUE TITLE
Crossing the ocean in a boat is impossible!

### ISSUE THREAD

**Issue by AwesomeTUX** [Wynncraft/Issues#3070]
Chunks don't load, I'm constantly teleported backwards and I can't get very far. Crossing w/out a boat works, but takes forever!

**Comment by TrashcanMan** [comment]
I believe this is an inherent issue with Minecraft, not something specific to Wynncraft. This has been reported a few times before and I don't think there's anything the developers can do about it.

**Comment by grecolons** [comment]
Thats only caused by lag. Not a bug.

**Comment by grecolons** [comment]
Just border it by horse or foot.
