### ISSUE TITLE
Cant get depressing items?

### ISSUE THREAD

**Issue by Chri630** [Wynncraft/Issues#3074]
So I've been farming lvl 1-5 zombies for the past 2 hours on the emerald trail near ragni and I havn't gotten a single depressing item! Is this a glitch due to the Gavel expansion update or what?

**Comment by TrashcanMan** [comment]
Do you have loot bonus? I've heard that loot bonus negatively affects your chance of getting depressing items, but I'm not sure if that's true. It's worth a try though.
