### ISSUE TITLE
Daily rewards glitched?

### ISSUE THREAD

**Issue by Chri630** [Wynncraft/Issues#3076]
I've been logging in every day but my streak multiplier has been 1 the whole time. Is it maybe because I've been logging out at 12am every day? If thats the problem I'd suggest to fix that issue because I heard someone got a legendary from the daily rewards and I'd love to be able to participate in that.

**Comment by grecolons** [comment]
[Another bug] Daily chest can't be opened. Yesterday, I couldn't open the daily rewards chest, when I clicked it, it just exited the menu. I've tried for 3h until I could open it. (Got legendary :D)

Also, what is happening to you never happened to me.
