### ISSUE TITLE
[Not working] Mage class 

### ISSUE THREAD

**Issue by Verret001** [Wynncraft/Issues#3078]
My level 42 mage seems to be unable to load, Ive joined multiple servers but it refuses to load at all. All I get when i load mage is "There has been a error, try again" 

I know this may be a duplicate, Im trying to get all the information together on this bug.
These are some of the issue fourms that are related
https://github.com/Wynncraft/Issues/issues/3006
https://github.com/Wynncraft/Issues/issues/3059
If you find any more related fourms please comment them.

This is what It looks like: 
https://youtu.be/NpyLuoczjBc

**Comment by shacharss** [comment]
Happened to me to im #3059

**Comment by Verret001** [comment]
Its strange... I hope it gets fixed soon, mage is really my only class thats above level 20.

**Comment by Verret001** [comment]
Why?
