### ISSUE TITLE
Can't finish WynnExcavation Site C Quest

### ISSUE THREAD

**Issue by sonicilsung** [Wynncraft/Issues#3098]
i started WynnExcavation Site C quest so i gave purple crystal shard to Excavator Placardus. then i started quest until my quest book says "report back to excavator placardus." so i talked to him and he said "the purple crystal shard from wynnexcavation site b is required to start this quest. please fix this bug  i really want to finish this quest. 
here is the screenshot.
![2015-12-25_09 19 39](https://cloud.githubusercontent.com/assets/16427426/11998580/aa156538-aae8-11e5-8509-42f81d67a594.png)

**Comment by Mistaria** [comment]
I am also having this problem.

**Comment by pmatha123** [comment]
You should have been given one that doesn't stack with those. It is given out at the end of each WynnExcavation quest.

**Comment by sonicilsung** [comment]
I just typed /fixquests that's it.
