### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by SoulBerry** [Wynncraft/Issues#3100]
I'm in this black screen were I can't move and I can go in my inventory and see me health and all but I can't move and see anything but a black screen.  It's just only one of my class.
![2015-12-24_19 15 39](https://cloud.githubusercontent.com/assets/16432346/11998741/12ed0bf6-aa7b-11e5-9691-4478fe55d007.png)
![2015-12-24_19 15 47](https://cloud.githubusercontent.com/assets/16432346/11998742/17bc9566-aa7b-11e5-8f49-570418d34d97.png)

**Comment by bigaapes** [comment]
I am having the same problem and i don;t know how to fix it :'(

**Comment by bigaapes** [comment]
i just used /kill and it got me out, try that :)
