### ISSUE TITLE
Armor disappearing bug

### ISSUE THREAD

**Issue by MechaelR** [Wynncraft/Issues#3102]
So today my friend called me and told me about the update, I was really excited about it and got on right a way then when I was getting my items identified I finished my weapons and moved on to armor, because my inventory was full I decided to switch my are boots with these gold boots I had because I did not think that would do any harm, but then it said I could not wear unidentified armor and all of my armor was deleted except for my iron boots which were still in my inventory. I am trying to get new armor right now but I was just wanted to tell you about this. Also is there anyway to get my armor back?

**Comment by MechaelR** [comment]
still thanks for the update

**Comment by Schnidischna** [comment]
Got the same issue! Pls fix!
