### ISSUE TITLE
legendary item losing its coding i think, aka it went vanilla and is now broke

### ISSUE THREAD

**Issue by budderlover09** [Wynncraft/Issues#3107]
well you see i had a legendary chain helmet and it was from me killing  a wild llevigar horse and it was legendary tier and had the bule title and the name was like pylier and had symbols now the name is white and everything is broken on it and this happened before and thought it was a small bug the first time so i did nothing now that it happens with this im kinda mad and yeah it happened after i logged off i logged back on a hour later all my items r fine except that helmet the helmet is broken, if i could get a role back or  a new helmet that would be great. thx there will be pictures agttached for proof.
![2015-12-24_22 14 52](https://cloud.githubusercontent.com/assets/16433475/11999822/e77f481e-aa8c-11e5-81e3-46f613962a15.png)
![2015-12-24_22 14 55](https://cloud.githubusercontent.com/assets/16433475/11999824/eb94d7ca-aa8c-11e5-90c2-76e511873007.png)
![2015-12-24_22 14 40](https://cloud.githubusercontent.com/assets/16433475/11999825/f00d5462-aa8c-11e5-9bde-3cf7c34ca7fa.png)

**Comment by budderlover09** [comment]
Well why did u close this issue and not even comment on what will be done or how to fix it

**Comment by budderlover09** [comment]
I see you really don't care on helping and fixing this bug

**Comment by budderlover09** [comment]
What help you guys are

**Comment by Trixter313** [comment]
If you're still experiencing the issue, please make sure it isn't already posted, and if it isn't repost it. Most issues were closed to have a fresh start since many issues were fixed in the Gavel update. Thanks!
