### ISSUE TITLE
[Spoiler Alert] Weapon missing skin

### ISSUE THREAD

**Issue by ohyeah1357** [Wynncraft/Issues#3110]
<details> 
  <summary>Spoiler alert</summary>
    "Pure," a Mythic weapon, is missing a model. The lore describes it as "pure white."
http://i.imgur.com/MQgNzNQ.png
I can see why this is missing a skin, for Mythics are so rare that few have one.
</details>

**Comment by AshKernel** [comment]
You should have left this in the suggestions page rather then the bug reports page.

**Comment by Verret001** [comment]
It is a bug, All weapons should have models.
