### ISSUE TITLE
Teleported to flat world, Spawning emerald, Loot chest particle (WC 12 right now or 5-15 minutes ago)

### ISSUE THREAD

**Issue by failtofell** [Wynncraft/Issues#3111]
Happens now and 5-15 minutes ago for the first time. I was at secret library(Gundalf's place) at WC 12.

Near that place I seen some loot chest particle without the loot chest(there's pitcures)
![2015-12-25_12 47 14](https://cloud.githubusercontent.com/assets/16434017/12000441/1224b1ea-ab09-11e5-817c-34d77b57e5e3.png)
![2015-12-25_12 47 21](https://cloud.githubusercontent.com/assets/16434017/12000442/16199cc0-ab09-11e5-8b01-95d3b7379d24.png)

And I seen pile of emerald inside the tower, after I picked them up I tried to jump to the top off the tower using escap spell and when I comeback to the tower's floor the emerald spawns again.( no pitcures)

I tried reconnecting to the server, but then I was teleported to the flat world then die once, after that I respawned there again.
![2015-12-25_12 51 04](https://cloud.githubusercontent.com/assets/16434017/12000443/2189d322-ab09-11e5-8139-7639a61f2584.png)

**Comment by Haystak23** [comment]
I had the flat world happen to me, and when trying to log into a different server im stuck in the ground and my y is at 6.
