### ISSUE TITLE
Smoke Bomb Problems

### ISSUE THREAD

**Issue by FwapaDurp** [Wynncraft/Issues#3112]
I know Smoke Bombs from Assassins have limited attack times but I found that the smoke from them act weirdly. They seems to move around by themselves.
First of, heres 2 pictures I just tested. Both pictures are from the same ability and the bomb is away from all mobs nearby as you can see below:
![2015-12-25_01 26 24](https://cloud.githubusercontent.com/assets/16434132/12000545/c41a1e3e-aaa6-11e5-89bc-34133e18479f.png)
It some how hits the mobs behind me, damaging them only once within the 5 second period as stated on https://wynncraft.com/help
![2015-12-25_01 26 26](https://cloud.githubusercontent.com/assets/16434132/12000569/20c69b58-aaa7-11e5-9fb7-191635987af0.png)
Here is another set of smoke bombs I tested and it further proves my statement:
![2015-12-25_01 34 13](https://cloud.githubusercontent.com/assets/16434132/12000604/b786a128-aaa7-11e5-89fb-814d3a3905d4.png)
![2015-12-25_01 34 15](https://cloud.githubusercontent.com/assets/16434132/12000605/bcb074bc-aaa7-11e5-8f79-c9c84c220da2.png)
How can the smoke even reach the mobs at the back?
This makes the ability unuseable for slowing the mobs down at all which is what it is supposed to act like. I don't know if it is intentional but can we see a fix for these "moving" smoke? Thanks :)

**Comment by luka0033** [comment]
I have the same problemm with my assasin, they hit only mobs which I dont target, and the take only 
1-2 ticks then it stops working
