### ISSUE TITLE
disconnected

### ISSUE THREAD

**Issue by wynncraftlupascu** [Wynncraft/Issues#3120]
![2015-12-25_12 58 01](https://cloud.githubusercontent.com/assets/14152318/12002459/2e716d40-ab07-11e5-99e1-88c7d72f8f22.png)
I cant conect to wynncraft

**Comment by Gualdim-Pais** [comment]
Nobody cant, its being updated or it's some problem with the host

**Comment by Rupterch** [comment]
This is really annoying

**Comment by wynncraftlupascu** [comment]
SO will the powders will go up again
