### ISSUE TITLE
[BUG] Assassin weapon that looks like a bow

### ISSUE THREAD

**Issue by grecolons** [Wynncraft/Issues#3124]
![2015-12-24_19 27 04](https://cloud.githubusercontent.com/assets/16406272/12002607/b2772be8-ab02-11e5-9032-b5022abf097c.png)
As you can see, this dagger looks like a bow... WTF

**Comment by arneturuc** [comment]
As it says, it truly is a 'Phantom Blade' :D
It is truly the master weapon of disguise ;)
Well, I don't think that behavoir was intentional; sry for the unnecessary post (and bad joke) :/

**Comment by grecolons** [comment]
Hahahhahaha :D
