### ISSUE TITLE
Can't join the server

### ISSUE THREAD

**Issue by zekrom74** [Wynncraft/Issues#3126]
to clarify, the server tag is still there with the gavel update sentence. however, it says that the server either has 0/1, 1/1 or 2/1 players and when trying to join, i will get disconnected without any error signs, it just says disconnected.

i have refreshed the server list, checked the ip and restarted my client, is there anything else i can do?

**Comment by HugoThePlugo** [comment]
I'm having the same issue right now. At least now I know it isn't client sided, but I haven't got a solution either...

**Comment by vboyswag** [comment]
I got the same issue. Maybe its just down for Christmas

**Comment by vboyswag** [comment]
I have loaded up the server and 0/1 people are on so ... its down for everyone ATM.

**Comment by KiloOhm** [comment]
Yea I can't join either :-/
![2](https://cloud.githubusercontent.com/assets/7194154/12003271/7fb4870a-ab20-11e5-9b40-68d542acbdc7.png)
