### ISSUE TITLE
Dark Room, no way out. Bugged log in?

### ISSUE THREAD

**Issue by bigaapes** [Wynncraft/Issues#3135]
When i log in onto my archer i find myself in a room where i cant see at all, i cant get out..... Need help please

**Comment by Haystak23** [comment]
I have the same problem. and it wont let me log into the world where it happened so essentially i cant fix it.

**Comment by bigaapes** [comment]
i got told to use /kill when i was in game and it fixes it, it fixed it for me :). so hopefully that will help you
