### ISSUE TITLE
Gavel clean

### ISSUE THREAD

**Issue by Tama63** [Wynncraft/Issues#3138]
The issue tracker has been purged for the Gavel update.

**Comment by Trixter313** [comment]
Thank you! It was getting very messy.

**Comment by Verret001** [comment]
It was. Can you repost if you issue is still a issue?

**Comment by Tama63** [comment]
@Verret001 yeah I just cleaned it because of the silly number of duplicates.

**Comment by meatloaf4311** [comment]
Thank the lord, its a christmas mirical

**Comment by DarkDemonDragon** [comment]
@Tama63 I've tagged you in the issues that should be reopened.

**Comment by Tama63** [comment]
@Trixter313 you can now help manage the repo :)

**Comment by Trixter313** [comment]
Thank you very much! I hope I can help out =)
