### ISSUE TITLE
Horse Enemy Glitch

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#3143]
Right-Clicking any enemy that is a horse will cause you to turn around, as the game expects you to sit on said horse, yet you do not.

**Comment by Verret001** [comment]
:+1:

**Comment by Trixter313** [comment]
Confirmed as still occurring. https://youtu.be/JhW5GXl8Ewg

**Comment by Moe-Ronickah** [comment]
This is a normal MC mechanic for the right-click, it affects any spell that begins with a right-click if the hostile mob is close enough.  There are two ways around this: 1) make your first right-click away from the hostile mob, then turn back to the hostile, or 2) click attack while looking at the hostile mob's feet.

**Comment by YunoFGasai** [comment]
This happens when you try to mount other people's horses (except if they logged off while riding).
But as said it can't be changed.
