### ISSUE TITLE
Knocking Death out of the arena

### ISSUE THREAD

**Issue by Marianol24** [Wynncraft/Issues#3144]
When fighting Death as warrior, using war cry, bash, or uppercut when it's in a corner will make it go throught the wall, restarting the fight. I haven't tested this with other classes, but I suppose it should also happen with spells like archer's bomb arrow
https://www.youtube.com/watch?v=Yd0-taUDdwk

**Comment by Verret001** [comment]
Extra blocks need to be added outside of the arena.

**Comment by Moe-Ronickah** [comment]
Fixed
