### ISSUE TITLE
Resource Pack Broken

### ISSUE THREAD

**Issue by ToasterAmol** [Wynncraft/Issues#3146]
So I went on today to find that my resource pack did not work. I went out of the server and found that the resource pack prompt should have been enabled. I went back on and it froze at 100% and I had to press escape to get out, after which the game played normally but without textures which made it harder. I closed and reset minecraft, but it was still broken. I put it on disabled, and then enabled it again, no affect. If I put it on prompt it will prompt me, but then say "error, please try again." My username is minecraftthe1st.

**Comment by HeroTheZero** [comment]
Same thing happend to me,  My pack was working, but then i relogged and it stopped working - i Refreshed, made it to enabled, promp, disabled, i restarted minecraft ,my computer, i tried absolutely eeverything yet it doesnt work!!

**Comment by vboyswag** [comment]
My pack just isn't working in general. I don't have a choice of ESC

**Comment by ToasterAmol** [comment]
Idk, I think its a gavel problem. There are even more problems with some boss battles. I tried to go online to manually put on a wynncraft pack, but now that gavel uses more items then just sticks shovels shears and bows for weapons, and because they added accessories, it doesn't work anymore, and there isn't an official pack to download, so I'm just playing texture less.

**Comment by Tsugeta7** [comment]
Same thing happened to me. The server just will not grab the resource pack for me. I tried it on my little brothers computer and it works perfectly fine. Took his resource pack, put it into my server pack folder and it still didnt work

**Comment by ToasterAmol** [comment]
I tried on all my computers, none of them worked. I saw some people earlier as well who had the same problem. And it was working earlier today when they were talking, but I logged on after playing a few other games on different consoles, and got back on and it did not work. I don't think anything happened between then, was only a matter of 1-2 hours.

**Comment by ToasterAmol** [comment]
It's an account problem not a computer problem, it seems. What did you guys do before it stopped working. I was just running around and got a legendary accessory in time valley.

**Comment by Tsugeta7** [comment]
I was sitting in deltas after i bought a legendary helmet. My brother just started and was running through ragni

**Comment by vboyswag** [comment]
I got a few bracelets

**Comment by vboyswag** [comment]
The thing is, some people have the pack

**Comment by ToasterAmol** [comment]
yeah, but there might be something that if you do it will break

**Comment by vboyswag** [comment]
Oh

**Comment by HeroTheZero** [comment]
I was in nemract about to do some quests, the server was about to reset so i tried to relog, when i relogged, my texturepack stopped working.

**Comment by ToasterAmol** [comment]
Maybe its just a bug they need to patch.

**Comment by DeathByShrimp** [comment]
I'm experiencing the same issue. I hope this gets patched soon; I'm unable to play at all right now.

**Comment by ToasterAmol** [comment]
The pack is now working for me, so it may still work for you guys. I am going to close the thread now, but will reopen if it stops working.

**Comment by Chillydog117** [comment]
Yeah, lucky it randomly started working. Did you do anything different? I got the same problem.

IGN: chillydog117
