### ISSUE TITLE
Can't remove items from bank (Arrows & Questbooks)

### ISSUE THREAD

**Issue by LadaZ** [Wynncraft/Issues#3147]
Hello 
I cannot remove arrows from my bank and everytime i try it pops back into my bank again... I would like if someone could help me ;D

**Comment by meatloaf4311** [comment]
Are they quest items?

**Comment by DarkDemonDragon** [comment]
Arrows are Vanilla items. It is your fault for whatever bugs that occur for possessing them.

**Comment by meatloaf4311** [comment]
When the title update came about, I had vanilla emeralds for ever cause I didnt convert them, but that didnt seem to be a problem

**Comment by DarkDemonDragon** [comment]
Emeralds are different as the server used to use vanilla emeralds. Arrows are not obtainable naturally anymore.

**Comment by LadaZ** [comment]
No they are not quest items :N

**Comment by Trixter313** [comment]
The server used to use vanilla arrows also though, and at one point you could take the arrows and move them around but the arrow spot would be refilled without taking the arrows back but now they are stuck in people's banks. I know of at least one other user still experiencing this issue and their IGN is mufassa121 if anyone gets around to removing the items. Thanks!

**Comment by sinomsinom** [comment]
i also still have some in my bank IGN:sinomsinom would be nice to see them removed

**Comment by Trixter313** [comment]
@opps123456789 also can't remove some questbooks from their bank. https://github.com/Wynncraft/Issues/issues/3818

**Comment by SirKyler** [comment]
I too have arrows stuck in my bank IGN: SirKyler 
Didn't bug me much until multiple classes required slots for quest items. Please remove

**Comment by Dar-krusos** [comment]
From #3818:

> To remove these items, read these instructions along with this image:
> !(http://i.imgur.com/f859G9o.png)
> 
> Images:
> 1. Fill all inventory space (make sure you have a stack of 2 or more emeralds somewhere in there)
> 2. Halve a stack of emeralds
> 3. Place it upon the item you want removed
> 4. Throw out the unwanted item
> 
> Only use this for this situation and don't do this to any Quest Items (or there will be consequences)."
> - Dar-krusos

**Comment by SirKyler** [comment]
I assume it works with unwanted items in your inventory that you can move
around, but it doesn't work with items that are stored inside a bank that
you can't move around at all.  When I try to do this technique, it blocks
me from throwing the item out. Is there any other way to remove the arrows
from my bank?

**Comment by Dar-krusos** [comment]
Oh, I see. Try filling up both bank and inventory, then click the arrows while holding emerald to swap them.

If the arrows do not swap with the emeralds, then you will need an admin to remove them for you.

**Comment by Trixter313** [comment]
Yeah, tried that and pretty much everything I could think of but these items are super stubborn. Nothing worked.

**Comment by DarkDemonDragon** [comment]
What happens when you try to swap them with an item? Does it revert immediately after a tick? Try swapping them with another stubborn item like an extra quest item from doing /fixquests.

**Comment by Trixter313** [comment]
Yeah, trying to swap items just swaps them back immediately. I don't get any extra items from /fixquests so I don't think I can test that theory out. I'd assume it would just put the item back in my mouse like any other item though.

**Comment by DarkDemonDragon** [comment]
Can they be picked up at all or does it slip away after "x" seconds?

**Comment by Trixter313** [comment]
Swapping, picking up, shift clicking, everything instantly goes back.

**Comment by DarkDemonDragon** [comment]
Honestly aside from purposely glitching the item away by somehow keeping it out of the bank even if for a split second just as the server resets or by purposely making yourself lag (disable and enable wifi, unplug and replug modem, etc.) and then swapping the arrow out and then killing yourself once it's in your inventory, I don't think there's a simple way for players to get rid of arrows. At this point the Admins should just remove all arrows from everyone's Bank/Inventory. This was shown to be possible when all Legendary Relics were forcibly removed from everyone's inventory.

**Comment by Trixter313** [comment]
Confirmed as still an issue. https://youtu.be/ahjeEexJQyI

**Comment by Trixter313** [comment]
@omirolf is experiencing this also https://github.com/Wynncraft/Issues/issues/4880
With a compass as well.

**Comment by Trixter313** [comment]
@helldwarfskid has some arrows stuck in their bank https://github.com/Wynncraft/Issues/issues/4918

**Comment by helldwarfskid** [comment]
Yea :P it really should be fixed

**Comment by helldwarfskid** [comment]
Thanks for re-directing me here too.

**Comment by Trixter313** [comment]
@Ligaligi is experiencing this with a stuck compass. https://github.com/Wynncraft/Issues/issues/4928

**Comment by GambitDarkh** [comment]
I have a several stacks of arrows stuck in my e chest IGN: Anubis______

**Comment by zoggi2000** [comment]
Hopefully i can still post this here 

I still have one stack of arrows in my ender chest
ign: zoggi2000

Thank you!

**Comment by Trixter313** [comment]
@zoggi2000 This is the correct place to post it. Hopefully someone will get around to fixing it soon. =)

**Comment by helldwarfskid** [comment]
I have found what I think might be a bug... In the pumpkin Halloween area,
you are meant to fail the parkour, however a glitch with the pistons, as an
archer with speed, allows you to make it to the end... :P

**Comment by helldwarfskid** [comment]
I Have managed to do said bug twice...total.

**Comment by Trixter313** [comment]
Another report, of some arrows and compasses: https://github.com/Wynncraft/Issues/issues/6222

**Comment by 3535677** [comment]
Will anyone ever fix it, it only takes an admin to do /enderchest [username] and force remove / delete the item. ( assuming they have essentials)

**Comment by Trixter313** [comment]
Another report: https://github.com/Wynncraft/Issues/issues/6301

**Comment by Moe-Ronickah** [comment]
OK. I'm closing this, as of now.  All of the arrows and compasses should be removed, UNLESS you were online.  If you were online, and you still have arrows or compasses, OPEN ONE NEW ISSUE, PLEASE, SO THAT IT WILL BE EASIER TO TRACK YOU.  If there are more than one of you, just add your name and we will try to get your items cleared out, later this week.

**Comment by remcolego** [comment]
Anyone still reading this? i have like 4 stacks in my enderchest aswell, arrows so the trick didnt work. Please any admin help me, also what other way is there to get in contact with a admin?

**Comment by ColinRioux** [comment]
@remcolego If you are still having the issue, please open a new issue (so it's easier to track). Thank you. Also title it and describe the issue you're still having.
