### ISSUE TITLE
Lost Items in Update

### ISSUE THREAD

**Issue by Toadby** [Wynncraft/Issues#3149]
In interacting with items while my inventory was full, I lost most of my gear. I tried to remove my armor as it was still unidentified but it all simply disappeared. It did not drop on the ground. I now have no armor and am not sure what to do. Sorry if this is an issue only on my part.

**Comment by meatloaf4311** [comment]
As far as I know, the armor has not been replaced for most people and others just went and found better or the same thing again.

**Comment by Toadby** [comment]
Thank you I have started just trying to muscle through. I suppose a few deaths as I get back on my feet isn't too bad :)

**Comment by Trixter313** [comment]
Yeah, Wynncraft doesn't do refunds for ingame items but as meatloaf4311 said, it isn't that hard to get equal or better items back and some people even enjoy it =) Hope you enjoy the update!
