### ISSUE TITLE
Can't join the server.

### ISSUE THREAD

**Issue by vboyswag** [Wynncraft/Issues#3152]
The server seems to be down but I can't join. Can anybody help me with this?

**Comment by meatloaf4311** [comment]
If you are using any mod like optifine, Update. I had that issue the other day. 

Simple solution is to Restart Minecraft
If that didn't work then try Toggling your internet on/off
If that didn't work then try restarting your computer
If that didn't work then try updating Java
If that didn't work then something is probably broken on Wynncraft end

If on of the the steps works, Please Close the Issue
