### ISSUE TITLE
Armor is being Deleted!! IMPORTANT!

### ISSUE THREAD

**Issue by 0Patrick0** [Wynncraft/Issues#3153]
This has happened to me TWICE, resulting in valuable armor being deleted.  Please fix this issue. The last time it happened, which was about 10 minutes ago, I lost two legendary armor pieces.

BUG INFO:

NOTE: DO THIS WITH A FULL INVENTORY!
1) Wear a piece of armor or weapon that boosts a SKILL.
2) Now wear a different piece of armor that requires that skill to be a certain level.
3) Remove the thing you were using in Step 1.
4) Now the game will automatically take off the armor in Step 2 and delete it, since there was no inventory space. (If it doesn't take that armor piece off, try taking off another piece of armor.)

A solution for this would be to just drop the items on the ground when  your inventory is full instead of moving them to the inventory. I'm a hoarder when it comes to RPG's, and I know there are many like me, so I beg you to have this hotfixed/patched as soon as possible!

**Comment by Verret001** [comment]
A script needs to be added stating for when inventory is full It would drop the item.
:+1:

**Comment by domrich** [comment]
I wanted to identify my armor after the update and i had 3 free slots in my inventory. So i took off my helmet BUT the game took of all of my armor in just one step .That's how i lost my Crystal Pants. I don't know why I lost the pants even though the boots are a slot down below.

**Comment by domrich** [comment]
Logged on today...
[http://imgur.com/a/tAu8Q](url)
Lost Anchoryl due to the full inventory. But as you can see from the screenshots i **did** have enough Skillpoints to wear the equipment.

**Comment by Moe-Ronickah** [comment]
This is an issue of loading order.  The game loads your base skill points, then loads your armor and accessories.  If your armor pieces and/or accessories require other armor pieces and/or accessories in order for you to have enough skill points to use them, you won't have enough skill points to use them.  Until this is fixed, don't rely on using armor and/or accessories for skill points for other pieces of armor and/or accessories.

**Comment by domrich** [comment]
I did have enough skillpoints without my armor and accessoires. I don't know why that happened. My level 80 Archer who has not enough skillpoints did not have that problem...

**Comment by Moe-Ronickah** [comment]
@domrich , there is another, similar, and probably linked error, where the game can load your character with zero skill points.  It is possible that it loaded your armor and accessories with you having no skill points, dumped your items, then loaded your skill points.  Salted and Jumla have been working on these errors, lately.  That is why we see them login as one class, then another class, then back to the first class, etc.

**Comment by AgentPanda** [comment]
Horse Glitch

**Comment by YunoFGasai** [comment]
@AgentPanda please keep the thread on topic

**Comment by AgentPanda** [comment]
@YunoFGasai How did you get those numbers?

**Comment by YunoFGasai** [comment]
@AgentPanda what numbers?

**Comment by AgentPanda** [comment]
@YunoFGasai Like for example number #5152

**Comment by YunoFGasai** [comment]
@AgentPanda different issues are sorted by numbers, we use it to reference other issues.

**Comment by Moe-Ronickah** [comment]
@AgentPanda , what I meant by "follow and comment on the issue there" was that you can see what is happening with the issue that affected you, and you can add any relevant new information that you came across that concerned the issue.  Sorry if I confused you.  :)

Just above your first comment, you can see the tag to your closed issue, so your issue is known to be part of this overall issue.

**Comment by Moe-Ronickah** [comment]
This issue has been fixed by a game patch.
