### ISSUE TITLE
Able to interact - and lost items to - Armor Stands.

### ISSUE THREAD

**Issue by TheCalculatorCat** [Wynncraft/Issues#3154]
Armor stands, such as the one holding the paper in front of Chief Lobo, can be interacted with while holding weapons. They go into the grasp of the Stand. Right Clicking them reclaims them. But, if someone were to accidentally have the stand take their Bob's Mythic Bow and then the server crashes before they can reclaim it, one can lose their items to it.

Example: https://youtu.be/-cTYhXoi6No

**Comment by meatloaf4311** [comment]
Can I like upvote this issue

**Comment by Trixter313** [comment]
Could anyone tell me the location of another armor stand or what quest I have to do to be able to access the one from the video? Thanks!

**Comment by Trixter313** [comment]
Does anyone know of another location with an armor stand? I can't access the shown one to test to see if the issue is still occurring.

**Comment by Trixter313** [comment]
Someone on the forums told me the location of another armor stand and I just tested and wasn't able to interact with it. I believe this issue has been fixed! =)

**Comment by DebugMC** [comment]
@Trixter313 not true. Ik one place but I think I shouldn't put coords to a place that isn't perfect ;P you can't take off armor, but you can still put stuff on them and push.
