### ISSUE TITLE
Stuck Underground

### ISSUE THREAD

**Issue by Trentster13** [Wynncraft/Issues#3155]
The other day I logged out of Wynncraft at Elkurn. When I came on the next day, I was stuck in a block under Elkurn. Is there a way for me to get out? If this doesn't get fix, so players could get stuck forever, unless they use a different class!

Thank,
Trentster13

**Comment by ToasterAmol** [comment]
Maybe an admin could teleport you out

**Comment by Verret001** [comment]
Does /kill work? That should do the charm.
Only Use if you have above 3 soul point though.

**Comment by Verret001** [comment]
Please close the topic if this resolves the problem.

**Comment by ToasterAmol** [comment]
I can help.
I am there right now and can pick up your items or maybe duel with you, and kill you, and you will be out. Then I can trade back items lost. Tell me what server if so.

**Comment by meatloaf4311** [comment]
Close the topic
