### ISSUE TITLE
Wiki Email Confirmation

### ISSUE THREAD

**Issue by meatloaf4311** [Wynncraft/Issues#3158]
Hello all.

This has been an ongoing issue that still has not been fixed. I have been trying to confirm my email so that I can contribute to the articles but the confirmation would not send. I have tried contacting support by email, but to no avail. 

I used to get 

The Mailer returned: Failed to add recipient: {EMAIL ADDRESS} [SMTP: Invalid response code received from server (code: 451, response: Temporary local problem - please try later)]

But Now
I get this now: 

[895de3f3] /index.php?title=Special:ConfirmEmail Exception from line 268 of /usr/share/nginx/html/wynncraft_wiki/includes/mail/UserMailer.php: PEAR mail package is not installed

Backtrace:

#0 /usr/share/nginx/html/wynncraft_wiki/includes/User.php(4012): UserMailer::send(MailAddress, MailAddress, string, string, NULL)
#1 /usr/share/nginx/html/wynncraft_wiki/includes/User.php(3988): User->sendMail(string, string)
#2 /usr/share/nginx/html/wynncraft_wiki/includes/specials/SpecialConfirmemail.php(77): User->sendConfirmationMail()
#3 /usr/share/nginx/html/wynncraft_wiki/includes/specials/SpecialConfirmemail.php(58): EmailConfirmation->showRequestForm()
#4 /usr/share/nginx/html/wynncraft_wiki/includes/specialpage/SpecialPage.php(363): EmailConfirmation->execute(NULL)
#5 /usr/share/nginx/html/wynncraft_wiki/includes/specialpage/SpecialPageFactory.php(584): SpecialPage->run(NULL)
#6 /usr/share/nginx/html/wynncraft_wiki/includes/MediaWiki.php(275): SpecialPageFactory::executePath(Title, RequestContext)
#7 /usr/share/nginx/html/wynncraft_wiki/includes/MediaWiki.php(584): MediaWiki->performRequest()
#8 /usr/share/nginx/html/wynncraft_wiki/includes/MediaWiki.php(435): MediaWiki->main()
#9 /usr/share/nginx/html/wynncraft_wiki/index.php(46): MediaWiki->run()
#10 {main}

So something has changed but the problem has not been resolved

I have tried poking around https://www.mediawiki.org/wiki/MediaWiki but nothing helped this issue seams to only pertain to the Wynncraft Wiki. Thanks for Y'alls help

- Meat

**Comment by ThunderRemix** [comment]
@Tama63 Might need to look into this.

**Comment by PieKing1215** [comment]
Same here. When I emailed support about the first issue, I was told the people in charge would be informed. I guess that issue was fixed, but now I'm getting the same 2nd issue. It's probably just that they accidentally uninstalled <a href="https://pear.php.net/package/Mail">PEAR mail package</a>

**Comment by meatloaf4311** [comment]
That's what I thought by looking at the code

**Comment by Tama63** [comment]
installed the pear package
