### ISSUE TITLE
Flight in Distress ~ Door Key Glitch

### ISSUE THREAD

**Issue by zQuy** [Wynncraft/Issues#3160]
Well I was doing the Flight in Distress Quest, everything was going ok until I got captured and found a way out. If you walk up to this door with a pressure plate 1 block away from that door it will let you look in the key hole. It found it pretty neat, but I could not exit the key hole. So I decided to kill myself. When I came back to the quest everything was restarted so I had to do everything again, but this time most of the quest npcs were not their. I don't really know what happened but I am not able to do this quest anymore because if I do see a npc it will not talk to me. Thanks for reading and I really hope this doesn't happen to anyone else.

**Comment by Trixter313** [comment]
Are the NPCs showing up for you now?

**Comment by Trixter313** [comment]
I'm assuming the issues is now resolved because there hasn't been a response for 14 days and closing the issue. If it's still occuring simply comment that it isn't and I'll reopen the issue. Thanks!
