### ISSUE TITLE
Items not updated to new item system

### ISSUE THREAD

**Issue by xXBLA2EKILLAXx** [Wynncraft/Issues#3161]
My Rare Helmet Tarnhelm will not be identified
also my priests underwear wont be identified

**Comment by Matthew12133** [comment]
Identifying has been changed, as of the new update, meaning that you can't identify armour and weapons to give _enchantments_ as such, but rather _unseal_ their power, allowing you to use the new **ALL POWERFUL** weapons and armour.

This just means you can't use _enchant_ your weapons until they're good, but making it so you don't throw weapons out until you _identify_ their power. This also means that you don't get too attached to your **old, boring** weapons.

Hope this helps!

**Comment by DarkDemonDragon** [comment]
@Matthew12133 I have no clue what you're talking about. @xXBLA2EKILLAXx most likely you have items that didn't update to their Gavel versions. You can choose to either hold onto them until they get updated or throw them out as older gear will provide no benefits whatsoever. The selling of glitched pre-Gavel gear is prohibited so please refrain from doing that.

**Comment by Matthew12133** [comment]
I was talking about the fact that you cannot make any old weapon, a super weapon, using the old identification system. Meaning that you have to explore weapons using the new different stats.

Sorry, if I was confusing.

**Comment by Trixter313** [comment]
Some screenshots of the items would be helpful, if possible =)

**Comment by xXBLA2EKILLAXx** [comment]
I cant take screen shots of the items I have thrown them out because of an earlier comment

**Comment by xt449** [comment]
Screenshot
![image](https://cloud.githubusercontent.com/assets/3751431/12076965/f58ff752-b192-11e5-942d-d06d42a18b5c.png)

**Comment by stangefall** [comment]
this are some of the broken items i found 
![2016-01-10_17 38 08](https://cloud.githubusercontent.com/assets/16395360/12343458/e9e57ce2-bb1a-11e5-9124-3cf683f8dd64.png)
![2016-01-10_17 40 16](https://cloud.githubusercontent.com/assets/16395360/12343456/e9e37212-bb1a-11e5-9cf6-81559ae743c3.png)
![2016-01-10_18 05 55](https://cloud.githubusercontent.com/assets/16395360/12343459/e9e6e320-bb1a-11e5-9cd5-f7b6d104b85f.png)
![2016-01-14_16 09 00](https://cloud.githubusercontent.com/assets/16395360/12343460/e9e725ce-bb1a-11e5-8f74-a568eb95b4bd.png)
![2016-01-14_16 09 02](https://cloud.githubusercontent.com/assets/16395360/12343457/e9e4bc12-bb1a-11e5-8a6a-1742d661ecf8.png)

**Comment by UnstableCodeScarlet** [comment]
I have a pre-grovel tizatuko that isn't updated yet.

![2016-01-30_01 22 00](https://cloud.githubusercontent.com/assets/16712799/12694322/ee72fe66-c6ef-11e5-94e7-a8101eb84a4b.png)

**Comment by Trixter313** [comment]
Is anyone still experiencing this with any items they've acquired post-gavel update? Any items received before the Gavel update don't count as they could have been fixed for new drops. Thanks!

**Comment by DarkDemonDragon** [comment]
So is there no hope for pre-update drops?

**Comment by Trixter313** [comment]
I'd say probably not. I don't think the dev team would be willing to make a script to fix the items, if it would even be possible at all to automate it with scripts. They would probably have to re-create another script per item, and a lot of items are affected. But as long as new items aren't spawning like this I'd consider the issue to be fixed and eventually all of the broken items will just disappear.

**Comment by DarkDemonDragon** [comment]
Hmm I wonder if they can be considered rare collectibles now.

**Comment by Moe-Ronickah** [comment]
I keep hearing random comments that the old items will be fixed, but I haven't heard anything official.

**Comment by DarkDemonDragon** [comment]
@Moe-Ronickah well @Trixter313 seemed to hear of some new update that fixed future drops, but I don't know what his source is, but I'm assuming it's somewhat official.

**Comment by Trixter313** [comment]
@DarkDemonDragon not really a new update but just an observation that all of the items people are reporting were dropped pre-gavel. I wanted to test the observation by asking if anyone had had this happen to an item dropped post-gavel, and so far no one has stepped forward. It seems the moment of release some items just weren't updated correctly but any items dropped now aren't affected because they don't need to be updated, they are dropped using the new system by default.

**Comment by Trixter313** [comment]
Okay, since all the posts about this seem to be about pre-Gavel items, I'm going to close this thread. Eventually all the items will become extinct and as long as this isn't happening to any new items I don't see it as a bug anymore. Thanks!
