### ISSUE TITLE
"Potion making" quest currently not possible

### ISSUE THREAD

**Issue by Matthew12133** [Wynncraft/Issues#3162]
It seems that some IDs need some changing, or the items being submitted to the assistant are accepted, so that the potions of healing (I) can be submitted to the assistant.

The new (and improved) potion system means that the potions have extra NBT, meaning that the assistant doesn't accept them. I would assume that this is because the items are white-listed very specifically.

I know that you guys are still working out the kinks for most of this update and the smaller details might have been skimped on to bring the update out faster.

I, would like to, think I know how much effort has gone into this update.

Keep up the good work. :)

**Comment by ThunderRemix** [comment]
I'm pretty sure this has been fixed already. Be sure to use the lowest potions from Detlas.

**Comment by Matthew12133** [comment]
I have _already_ tried this. I _will_ try again when I next get on.

**Sorry** if I sound stubborn, I am just eager to finish this quest.

**Thank you for the help. :)**

**Comment by Matthew12133** [comment]
You have to use the potions so that they have **1/3** uses left. Lowest level potion to be used.

Little bit confusing, I know, but this is how you can complete the quest.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
