### ISSUE TITLE
I cant buy a royal amulet

### ISSUE THREAD

**Issue by RaymondZGames** [Wynncraft/Issues#3163]
![image](https://cloud.githubusercontent.com/assets/13869598/12005274/256b5770-ab51-11e5-8509-74c154f3d18f.png)

and

![image](https://cloud.githubusercontent.com/assets/13869598/12005275/2cff84e8-ab51-11e5-9653-5f21d5f9039f.png)

help pls

**Comment by meatloaf4311** [comment]
You do need to have the Royal Token of Gratitude in your inventory

**Comment by RaymondZGames** [comment]
i didnt get one from the quest

**Comment by Verret001** [comment]
Are you sure, It even states on the wiki thats how you get it.
https://wiki.wynncraft.com/index.php?title=Royal_Token_of_Gratitude

**Comment by RaymondZGames** [comment]
i did the quest, didnt get a token.

**Comment by slendersir739** [comment]
Maybe you got it, and you threw it away, try /fixquests, but it might not work.

**Comment by RaymondZGames** [comment]
ill just buy an amulet :c
