### ISSUE TITLE
WynnExcavation Part A bugged

### ISSUE THREAD

**Issue by Enginier24** [Wynncraft/Issues#3165]
Ok so i went to go do the WynnExcavation quest part A and after I went trough the area with the yellow crystal The excavator Vade  asked to decipher the tablet again... but the tablet was already deciphered so the person (forgot name) Will ask to return it to 
Vade and then the endless loop begins...

**Comment by Enginier24** [comment]
i need some help :,(

**Comment by superabel123** [comment]
Hm do /fixquests ?

**Comment by Trixter313** [comment]
Did /fixquests fix your problem? If so, we'd appreciate it if you closed this issue. Thanks!
