### ISSUE TITLE
Armor Deleted When Forcibly Removed While Having A Full Inventory

### ISSUE THREAD

**Issue by SwiftShadow11** [Wynncraft/Issues#3166]
When I was playing earlier today, I ended up losing my Crystal leggings when putting on a Purified Helmet of Legends in place of my Blue Mask. Because the Blue Mask was removed, I lost the intelligence bonus that it gave, and it forcibly removed my Crystal as a result. Because my inventory was full, the Crystal was instead deleted. I looked around on the ground to see if it had been thrown out of my inventory instead, but there was nothing there at all.

Replication: Have a full inventory. Replace a piece of armor with an armor that does not give a stat bonus, which will force a piece of armor to be removed because of you not having the correct stat to wear it anymore. This will force the piece of armor to be removed, but because the inventory is full, the armor will instead be deleted.

Screenshot of Crystal not being able to be worn: http://prntscr.com/9im5z1
Screenshot of inventory: http://prntscr.com/9im604
If there is anyway that I could possibly get a Crystal back because I lost mine due to this, it would be appreciated. If not, I completely understand. My IGN is SwiftShadow.

**Comment by 0Patrick0** [comment]
I already wrote an issue for this, but yea, spread the awareness.
