### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by Hazelstorm** [Wynncraft/Issues#3168]
Since the Gavel update came out, I simply can't connect to a world. I join the server as usual, and the lobby lags, but only as much as usual. When I join a world, the texture pack loads, and then my game freezes and either disconnects me or crashes. I really want to play and see all the new stuff, but I won't be able to if this is not fixed :sob: 

Can someone please tell me how to fix this?

**Comment by Ziggeh2** [comment]
I had the same problem, but I changed my version from 1.8.7 to 1.8 with Optifine, and it let me play. Try that. If it doesn't work, I don't know.

**Comment by meatloaf4311** [comment]
If you are using any mod like optifine, Update. I had that issue the other day.

Simple solution is to Restart Minecraft
If that didn't work then try Toggling your internet on/off
If that didn't work then try restarting your computer
If that didn't work then try updating Java
If that didn't work then something is probably broken on Wynncraft end

If on of the the steps works, Please Close the Issue
