### ISSUE TITLE
My stuff is going to code 

### ISSUE THREAD

**Issue by Alex172** [Wynncraft/Issues#3175]
One of my best helmets has gone to a lot of code please can you Fix it and make it go back

http://puu.sh/m922Y/4bcef02671.png

**Comment by Alex172** [comment]
Its called Pelier

**Comment by Matthew12133** [comment]
**Don't worry!** I believe that it should still work. It might just be a pain having that as a label. My best guess is that your helmet didn't port probably when the servers updated. From what I have heard JSON is one of the trickier things to handle, and the update would have also added to the difficulty.

**My best suggestion,** if the label bothers you a lot, is to grab a weapon from the Gavel province, around the LLevigar region, according to your level.

**Comment by Alex172** [comment]
Ok thank you

**Comment by Matthew12133** [comment]
I know it is **a pain** getting a new weapon.

I would do _whatever_ I could to keep my weapons... ...I have become attached to them.

**Sorry,** I couldn't be more of a help.

**Comment by Matthew12133** [comment]
Actually, it could be because of the **mods** you have installed. Just try deleting one mod at a time to see which mod is the reason for this happening.

**Comment by 0Patrick0** [comment]
This has happened to me many different times. All you have to do is swap to a different server. Some servers do this while others don't. Don't worry, your items aren't useless.

**Comment by wwgaming** [comment]
my item is fierty the spear doesnt attack or do specials no matter what server

**Comment by Frostwulfe** [comment]
Happened to me and it still doesnt work ;-;

**Comment by Frostwulfe** [comment]
What do you mean by "Grab a new weapon"? my helmet got messed up. i didnt identify it and it wont identify

**Comment by bobotje** [comment]
https://gyazo.com/84eacd8bcb760128119ad9bf5639df05
I got the same problem.
The wand is called Dévoreuse

**Comment by napster1** [comment]
^^^^ thats the same staff as i have i got the same problem

**Comment by OverFlareDX** [comment]
My helmet doesnt even give me any bonuses and stats anymore. It is literally useless right now. 


![wynncraft helm bug](https://cloud.githubusercontent.com/assets/16639489/12225163/a562277e-b83f-11e5-9a37-140bddeffe18.png)

**Comment by stangefall** [comment]
lost legendary and rare items ;-;
![2016-01-10_17 38 08](https://cloud.githubusercontent.com/assets/16395360/12343496/47284326-bb1b-11e5-8d70-cd984b45b58a.png)
![2016-01-10_17 40 16](https://cloud.githubusercontent.com/assets/16395360/12343497/4743164c-bb1b-11e5-8224-c498ad29b1b1.png)
![2016-01-10_18 05 55](https://cloud.githubusercontent.com/assets/16395360/12343499/4753cc3a-bb1b-11e5-8cde-686608111519.png)
![2016-01-14_16 09 00](https://cloud.githubusercontent.com/assets/16395360/12343498/4751ffcc-bb1b-11e5-8ead-82000707eee3.png)
![2016-01-14_16 09 02](https://cloud.githubusercontent.com/assets/16395360/12343500/4755a1cc-bb1b-11e5-8861-36e5c8905c25.png)

**Comment by OverloadMC** [comment]
It happens only to items, that have a name with special characters. I made a possible solution thread on the forums: [Thread](https://forums.wynncraft.com/threads/devs-special-characters-make-weapons-broken-possible-solution.104580/)

**Comment by TheRealfanibu** [comment]
I have the same Problem with the helmet Pélier like Alex172, must be fixed.
![2016-01-17_17 05 30](https://cloud.githubusercontent.com/assets/16745700/12378453/3db6d58a-bd3e-11e5-8980-4c797c511282.png)

**Comment by TheRealfanibu** [comment]
P.S my Ingamename is "fanibu" not "TheRealfanibu" , because the Name "fanibu" is already taken.

**Comment by ThisLittleGirl** [comment]
I've got the same issue with my chestplate 
![yfbfhof](https://cloud.githubusercontent.com/assets/16853504/12531450/2084679a-c1fb-11e5-9005-3f6e25c1a055.png)

**Comment by 0Patrick0** [comment]
So... When is this going to be fixed? It's a big issue.

**Comment by ThisLittleGirl** [comment]
I haven't played in almost a month now, tought it'd be better by now.

**Comment by stangefall** [comment]
i just cheked and still broken
![2016-02-16_14 37 04](https://cloud.githubusercontent.com/assets/16395360/13089617/a980e290-d4d8-11e5-910c-08f6e650950a.png)
![2016-02-16_14 37 00](https://cloud.githubusercontent.com/assets/16395360/13089618/a9832cda-d4d8-11e5-89f3-dee342e480e2.png)
![2016-02-16_14 37 02](https://cloud.githubusercontent.com/assets/16395360/13089619/a99ef99c-d4d8-11e5-878f-a3228b79f04a.png)

**Comment by DarkDemonDragon** [comment]
At this point I think the support for those items have been dropped. You guys can continue to hold onto the items in hopes of the Admins fixing this, have them for collection purposes, or just toss them out.

**Comment by Ron123456** [comment]
My helmet pelier broke too

**Comment by DarkDemonDragon** [comment]
@Ron123456 is it pre-Gavel or post-Gavel item?

**Comment by Moe-Ronickah** [comment]
Way past the 30 days for a response.

**Comment by TDeltasora4** [comment]
Okay, but what about weapons and armor that you get from quests?  I lost my mythic bow and mythic wand with the update, I of course cannot get another quest item to gain them back, so how am I supposed to move on?

**Comment by LordHelmchen98** [comment]
@TDeltasora4 are you talking about Bob's Mythic items? If so you can buy new ones in the Trade Market on the Forums.
