### ISSUE TITLE
Bugged quests

### ISSUE THREAD

**Issue by FuriousSniper** [Wynncraft/Issues#3176]
There are some new, bugged quests.
For example I went to the marked location, I got the required item. When I came to the right NPC he says, that I have to go to the location I'm coming from and find this item (I still got it).
Examples of bugged quests: Death Wristle, Maiden Tower.

Plz fix

**Comment by Trixter313** [comment]
I know that a lot of people were confused with the maiden tower quest. You have to put the veil on and just go up the tower. I haven't done the death whistle quest yet so I'm not sure what you're talking about with that one but I do know many of my friends have done it so maybe you're just forgetting something and doing the quest wrong.

Could you explain the issue you're having with the death whistle quest in a little more detail? Thanks!

**Comment by Wervel7** [comment]
I've got an issue with the Death Whistle quest. I've killed the With three times so far, but she has only dropped the Junk Item "Alga" and not the requested Quest item. Is the drop rate not 100% or is it really a bug?
