### ISSUE TITLE
Green Skinned Trouble Quest Wrong spawning location

### ISSUE THREAD

**Issue by JavaBots** [Wynncraft/Issues#3177]
When you do the quest Green Skinned Trouble when you enter the hidden camp if you die you will spawn at the first quest location behind ragini.

**Comment by enviroassess** [comment]
This also happens when i do it.

**Comment by Trixter313** [comment]
Consolidated into https://github.com/Wynncraft/Issues/issues/3617

Please direct any future comments to this thread. Thanks!
