### ISSUE TITLE
Can't right nether 

### ISSUE THREAD

**Issue by bidule995** [Wynncraft/Issues#3180]
We can't right-click to the nether join sign at the Hub.

**Comment by Matthew12133** [comment]
My best idea, as to why this doesn't work is that, the {action:} parameter on the sign needs to be updated.
Wynncraft must have updated BungeeCord along with the Gavel update.

Is it possible to give a **snapshot** and/or **error message** to help identify the problem?

**Comment by DarkDemonDragon** [comment]
@Matthew12133 that isn't necessary just right click the sign and you prove it in like 10 seconds. 

@bidule995 this is an issue that has been persisting way before Gavel. There is currently no way to access the Nether, although if you wish to PvP just duel a player by holding shift and leftclicking.

**Comment by Matthew12133** [comment]
To @DarkDemonDragon 
I'm sorry. I seem to missing the point:
"@Matthew12133 that isn't necessary just right click the sign and you prove it in like 10 seconds."

I am trying to provide reasons, any reason, as to why it doesn't work. And I am trying to use my knowledge on Vanilla and updating mods. 

P.S
**My best idea** means my best assumption. Also I don't quite understand what you mean by your message.

**Comment by Matthew12133** [comment]
/blockdata ~ ~1 ~ {
    Text1: "{\"text\":\"Teleport to the Nether\",\"clickEvent\":{\ __"action\":\"run_command\",\"value\":\"/tp @p ~0 ~0 ~0\"__ }}"
}

Action parameter ^^
Works on a sign placed directly above

I just want problems to be fixed.

**Comment by DarkDemonDragon** [comment]
@Matthew12133 the sign is NOT the issue. If you attempt to access the Nether in-game (there's a portal between Detlas Suburbs and Corrupted Village) it will not work. Most likely all methods of accessing the Nether has been closed down because the Devs are working on it.

**Comment by Trixter313** [comment]
I believe this is no longer an issue then because it makes sense that the sign doesn't work if the nether is down all together. I thought I saw an admin post somewhere that it was being updated but i couldn't find where.
