### ISSUE TITLE
don't Level Bug

### ISSUE THREAD

**Issue by FauLau** [Wynncraft/Issues#3181]
I don't can Leveling, becorse my Level is at 101% and I didn't level up.

P.s: My Level is 53.

**Comment by Matthew12133** [comment]
Is it possible to get any **snapshots**, just to help **visualise** what is happening exactly.

**Comment by FauLau** [comment]
her are 2 snapshots, and my proplem is when I Kill Mobs or make Quests i dont bekom Xp.
(https://cloud.githubusercontent.com/assets/16444123/12008125/482476d0-ac27-11e5-8e6a-53e5ac04eb12.png)
(https://cloud.githubusercontent.com/assets/16444123/12008141/333a400a-ac28-11e5-9e3b-6395686d47e9.png)

**Comment by neonJason52** [comment]
Has there been a solution yet?

**Comment by FauLau** [comment]
No.

**Comment by neonJason52** [comment]
Update; After some testing I have figured out I am only gaining XP out of the Gavel updated area. Still don't know why...

**Comment by Trixter313** [comment]
Is the issue still occurring for you? Try typing "/guild xp 0" to make sure you aren't giving all of your XP to the guild. Other than that I don't know what else to suggest.

**Comment by neonJason52** [comment]
Already did that. Didn't work.

**Comment by Moe-Ronickah** [comment]
Looking at your second screenshot, your personal XP is zero, your guild XP is 266.  You may well have used "/guild xp 0", but it didn't work.  Please try it again, and let us know if your problem is resolved.

**Comment by Moe-Ronickah** [comment]
CLOSED DUE TO NO RESPONSE
