### ISSUE TITLE
"Could not find a server to connect to, please report."

### ISSUE THREAD

**Issue by bowman102** [Wynncraft/Issues#3184]

**Comment by Forcellrus** [comment]
Same issue here.

**Comment by Ziggeh2** [comment]
Same.

**Comment by Verret001** [comment]
Please close the topic. The servers are back online now.

**Comment by meatloaf4311** [comment]
If you are using any mod like optifine, Update. I had that issue the other day.

Simple solution is to Restart Minecraft
If that didn't work then try Toggling your internet on/off
If that didn't work then try restarting your computer
If that didn't work then try updating Java
If that didn't work then something is probably broken on Wynncraft end

If on of the the steps works, Please Close the Issue
