### ISSUE TITLE
My item Dissapeard

### ISSUE THREAD

**Issue by Suegerman** [Wynncraft/Issues#3185]
Hey, about a day ago me and my friend was playing Minecraft his inventory was full so he right clicked his Mummy rags into his inventory for some reason it went into the accessory slot and disappears he got so sad because he new he could never get it back please if you guys could help us with this it would be very appreciated! If you can give back the Mummy rags to my friend -nexusgman I will thank you!

By
  Suegerman

**Comment by Forcellrus** [comment]
You won't get it back. I had same issue, I lost Helmet, Leggings and Shoes the same way. Staff just doesn't care, so yeah, better not lose time and grab a new gear.
