### ISSUE TITLE
Trying to understand changes

### ISSUE THREAD

**Issue by wizardcheetah55** [Wynncraft/Issues#3188]
I was gone from Wynncraft for about a month - was happy about Gavel until I (WizardCheetah55) logged in. I'm a level 75 Mage and I find I can't use my Ethereal wand unless I have 60 intelligence points. That is nearly double what I have. Is this a glitch or the way it is going forward? There may be other issues but I can't get beyond this now.

**Comment by meatloaf4311** [comment]
It is the way for the Wynncraft designers making the game more dynamic and balanced. It seems that this design is the template for the near future and so that you can use your weapons, there is a merchant to reset skill points in the Wynn Province

**Comment by Verret001** [comment]
@meatloaf4311 As well as your skill points should automatically reset after the update.

**Comment by Verret001** [comment]
If this has helped you may you please close the topic.

**Comment by wizardcheetah55** [comment]
Thank you - no wonder I couldn't find it to report it had been resolved.

Stan Emert
206-250-9839
Skype: stan.emert
