### ISSUE TITLE
Can't Create A Guild

### ISSUE THREAD

**Issue by ChaosMartin** [Wynncraft/Issues#3190]
I have 7 Liquid Emeralds and it starts the guild creation process however the very first thing that popped up on my screen was a sign asking what I wanted to name the guild. I tried naming it and it said that "Please only use English characters A-Z in your guild name." When I click escape on the sign it says "There is a 3 Character Limit  on guild names. Make it a bit longer!" I am at the guild master in the new town of Cinfras and I'm attempting to name the guild "Rising Phoenix" Any help would be appreciated.

**Comment by ThePixelPony** [comment]
Same problem here.

**Comment by Lafy** [comment]
Same problem.

**Comment by jensiwaa** [comment]
Problem still occurs so it wasn't fixed in 14.0.4 patch

**Comment by Zdyzeus** [comment]
Im also having this problem, any fixes yet?

**Comment by Trixter313** [comment]
Can someone confirm whether this is still happening? Supposedly some guild related things were fixed in the latest patch. Hopefully this was one!

**Comment by Trixter313** [comment]
Assuming it's fixed due to no response. If it's still broken, simply comment and I can reopen the issue. Thanks!
