### ISSUE TITLE
Barriers Preventing Access To Loot Chest

### ISSUE THREAD

**Issue by ltvuong** [Wynncraft/Issues#3192]
![2015-12-25_21 47 49](https://cloud.githubusercontent.com/assets/9344447/12007455/b2c845c8-abca-11e5-86c7-2cb8bddfa136.png)
The title explains it all.

**Comment by Trixter313** [comment]
Are you sure this was a loot chest and not a decoration chest? Were there sparkles coming off of it?

**Comment by ltvuong** [comment]
Yes. It is a loot chest. In the picture you can see the slight sparkle coming off in the picture. Also I have visited this chest many times before Gavel came out.

**Comment by Trixter313** [comment]
I see, it should get fixed soon then. Thanks for the bug report!

**Comment by DarkDemonDragon** [comment]
I submitted a report to the build team and they have fixed it. Please close this issue as I have confirmed it is live on all Worlds.
