### ISSUE TITLE
[MUST READ] Directory

### ISSUE THREAD

**Issue by Verret001** [Wynncraft/Issues#3197]
Please make sure there are no duplicates by using this chart. This is getting very frustrating when looking to help people and there are about 7 duplicates of the same thing.
This is to help organize the forums and hopefully stall another clean. If there is anything new or that I'm missing, comment it below. Thank you.

These are some of the topics (Not all) That may solve your problem.

**Lag**
If you experience lag, Please don't make a issue about it, 
currently we're trying to fix issues that are making gameplay impossible,
So lag is not our top priority right now and some solutions might be to try joining a different 
server or turning your render down. Even try turning your graphics down. 
Thank you and have a good day -Verret

**Solved Topics;**

  - Stuck in blocks; Solution [ type /kill with 3 or more soul points ] [SOLVED]
https://github.com/Wynncraft/Issues/issues/3157 https://github.com/Wynncraft/Issues/issues/3156 https://github.com/Wynncraft/Issues/issues/3086 https://github.com/Wynncraft/Issues/issues/2972 https://github.com/Wynncraft/Issues/issues/2940

  - Class selection problem [Solved]
https://github.com/Wynncraft/Issues/issues/3203

  - Nether Is broken [Solved] [nether being changed to be compatible with gravel update]
https://github.com/Wynncraft/Issues/issues/3180 https://github.com/Wynncraft/Issues/issues/3217

**Open Topics;**
**Bolded** = Existed for over a week

  - **Old classes are not working at all *error message: [There has been a error, try again] [OPEN]**
https://github.com/Wynncraft/Issues/issues/3139

  - Assassin spells not working [OPEN] 
https://github.com/Wynncraft/Issues/issues/3140

  - Mage teleport blinding not working [OPEN]
https://github.com/Wynncraft/Issues/issues/3223

  - Armor Deleted When Forcibly Removed While Having A Full Inventory [OPEN]
https://github.com/Wynncraft/Issues/issues/3153 

  - Emeralds not received upon finishing quest.
https://github.com/Wynncraft/Issues/issues/3246

  - Ahmsord not acting as a city | Not spawning in city you died in
https://github.com/Wynncraft/Issues/issues/3202

  - Guild naming broken [OPEN]
https://github.com/Wynncraft/Issues/issues/3190

  - Items un-naming themselfs [OPEN]
https://github.com/Wynncraft/Issues/issues/3175

  - Unable to identify items [OPEN]
https://github.com/Wynncraft/Issues/issues/3161

  - Arrows unremovable from bank [OPEN]
https://github.com/Wynncraft/Issues/issues/3147

  - Not leveling correctly [OPEN]
https://github.com/Wynncraft/Issues/issues/3181

  - Horse enemy glitch [OPEN]
https://github.com/Wynncraft/Issues/issues/3143

**Open & Closed Topics;**

  - **Broken Quests [BOTH]**
Hunger of gerts Part 2 - https://github.com/Wynncraft/Issues/issues/3174
Green Skinned Trouble Quest - https://github.com/Wynncraft/Issues/issues/3177
Lost in the jungle - https://github.com/Wynncraft/Issues/issues/3172
Memory Paranoia - https://github.com/Wynncraft/Issues/issues/3167
Potion making - https://github.com/Wynncraft/Issues/issues/3162
Flight in Distress - https://github.com/Wynncraft/Issues/issues/3160
Heart of Llevigar - https://github.com/Wynncraft/Issues/issues/3178
Hive - https://github.com/Wynncraft/Issues/issues/3169
Animal Dungeon - https://github.com/Wynncraft/Issues/issues/3191
Wynncraft Excavation Side D - https://github.com/Wynncraft/Issues/issues/3196
WynnExcavation Site A - https://github.com/Wynncraft/Issues/issues/3200
The Qira Hive Air boss - https://github.com/Wynncraft/Issues/issues/3204

  - Connection problems [BOTH]

(Not a full list; Will update soon)

**Some ways to fix connection problems**

Following Info from @meatloaf4311 
If you are using any mod like optifine, Update. I had that issue the other day.
Simple solution is to Restart Minecraft
If that didn't work then try Toggling your internet on/off
If that didn't work then try restarting your computer
If that didn't work then try updating Java
If that didn't work then something is probably broken on Wynncraft's end

**Did none of these solve your problem? I got you; 
[Create New Topic](https://github.com/Wynncraft/Issues/issues/new)**

<3 You all and have a good day.
P.S. This took me 2 hours to make so please use it. - Verret001

The **[Directory](https://github.com/Wynncraft/Issues/issues/3197)**

**Comment by meatloaf4311** [comment]
Also Everyone having Connection Issues [Read Below]

If you are using any mod like optifine, Update. I had that issue the other day.

Simple solution is to Restart Minecraft
If that didn't work then try Toggling your internet on/off
If that didn't work then try restarting your computer
If that didn't work then try updating Java
If that didn't work then something is probably broken on Wynncraft end

If on of the the steps works, Please Close the Issue

**Comment by Verret001** [comment]
[GitHub](http://github.com)

**Comment by Trixter313** [comment]
Edited for closed issues. Here's a copy of the un-edited version in case you don't like something I did: https://drive.google.com/file/d/0B1ONgNZTFXnwNDBUQ25jWm1ERjg/view?usp=sharing

**Comment by Verret001** [comment]
@Trixter313 Fell free to edit anything you like! I can't really get online as much, I hate it.

**Comment by DarkDemonDragon** [comment]
Barriers blocking loot chests [OPEN]
#3192

Fixed for that instance.

**Comment by Trixter313** [comment]
Gonna close for now because it's so far behind in the pages and out of date. Also using the search feature would probably be easier.
