### ISSUE TITLE
STOP THAT

### ISSUE THREAD

**Issue by SteveClinton** [Wynncraft/Issues#3199]
Just stop that f*cking spell laggs!!!! Bosses are impossible to make! Excpt you have so mates with you. Just stop that. Or just make some vip servers with lower ammounts of players. But do something! And dont type ,,Its not a bug or we cant do anything pls close that issue,, i wont close anything before its solved. Thanks for reading.

**Comment by Verret001** [comment]
If you won't close it a admin will.

**Comment by Gualdim-Pais** [comment]
The lag is on servers not on players side, I can't even use my white horse 40-40 cause its slower than walking bt foot... trolol

**Comment by Verret001** [comment]
Who knows I can't play!
https://github.com/Wynncraft/Issues/issues/3139

**Comment by SteveClinton** [comment]
very funny
