### ISSUE TITLE
WynnExcavation Site A Quest

### ISSUE THREAD

**Issue by Drake2100** [Wynncraft/Issues#3200]
Hello, I found a bug in the quest "WynnExcavation Site A". After you talk with an excavator and after you go in pharaon boss room, you have to kill the boss, I killed him 4 times but every time I try to go in the black portal it tells me: "You feel you need to complete something first" and I can't go on to complete the quest, even If I have4 Yellow Crystals.
See the screenshot:
![2015-12-26_21 27 59](https://cloud.githubusercontent.com/assets/16447195/12007876/b0cafa64-ac19-11e5-843a-7e01e45e2d71.png)
![2015-12-26_21 28 01](https://cloud.githubusercontent.com/assets/16447195/12007877/b0d113c2-ac19-11e5-9efb-883f2d7814c2.png)
![2015-12-26_21 27 51](https://cloud.githubusercontent.com/assets/16447195/12007878/b158d28a-ac19-11e5-8ed2-2ea70dc00b8c.png)

**Comment by Trixter313** [comment]
Could you show us a screenshot of your questbook also? Thanks!

**Comment by Drake2100** [comment]
I can't anymore, I've finished this quest. I finally could through the portal and I've finished the quest.

**Comment by SioN-wynncraft** [comment]
I can give the photo if you can wait for something like 2 Or 3 hours(maybe 20 min)

**Comment by SioN-wynncraft** [comment]
sorry I just did the quest

**Comment by Trixter313** [comment]
Oh, great to hear!
