### ISSUE TITLE
Ahmsord not acting as a city!

### ISSUE THREAD

**Issue by BlahBlah161616** [Wynncraft/Issues#3202]
I died in Ahmsord and respawned in Thesead, it is marked as a city, yet appears not to be one. If this is a bug please fix it.

**Comment by Kyappu** [comment]
I don't think it's a bug since that's happened to me several times. For example:
One time I've been to Detlas, then died near the Roots of Corruption, then teleported to Ragni.
It's pretty annoying but I think it teleports you to the closest town.

**Comment by BlahBlah161616** [comment]
I don't think you get it, I died in the city and spawned elsewhere.

**Comment by BlahBlah161616** [comment]
In addition, it doesn't register you entering the city...

**Comment by Odnod** [comment]
I believe this has since been fixed, as I have been to Ahmsord, it said I was entering, I died and respawned in Ahmsord.

**Comment by BlahBlah161616** [comment]
It was fixed, they must've seen it.
