### ISSUE TITLE
Class Selection Problem | With proof this isn't lag.

### ISSUE THREAD

**Issue by Kyappu** [Wynncraft/Issues#3203]
I've been trying to do this for a couple days: Switch my class from archer to mage.
My issue started when I couldn't do /class in game with the server saying "You can not use commands right now." I did /toggle autojoin then relogged. When I entered the class selection, I feel right through the dark spawn room. I checked if this was lag or not, but I saw people's shouts and I tried performing commands like /help, resulting in "You can not use commands right now." I finally did /hub then went back to the lobby. Then repeated the process. (Plus, I even visited an internet cafe to see if it was just my internet or not) I continue to fall through every time. I asked my friends once if this was a problem for them and they said no, even with terrible internet speed. Whenever I fall, I look up and see what seems to be either a dent, or a hole in the bottom of the room. I'm not sure if this is a personal problem or not, but I just want to see it fixed. IGN: Captain_Amazing3
Screens:
![2015-12-26_13 29 13](https://cloud.githubusercontent.com/assets/16447423/12007995/cded21f2-abd4-11e5-906a-3f76f6788f3b.png)
![2015-12-26_13 29 21](https://cloud.githubusercontent.com/assets/16447423/12007996/dba529f2-abd4-11e5-9b13-1dbc2dbb1b6f.png)

**Comment by Verret001** [comment]
**Answer**
I encountered this problem, You have to use wynncraft's texture pack. If this still doesn't work try uninstalling and reinstalling the texture pack.
