### ISSUE TITLE
The Qira Hive Air boss bug

### ISSUE THREAD

**Issue by opps123456789** [Wynncraft/Issues#3204]
I was playing as an assassin and I was fighting the boss for the air level. When he was about to use his special attacking, shooting millions of arrows and going as fast as the speed of light, I used my vanish skill and he just started flying around really fast and just disappeared out of the map. Please fix

**Comment by Trixter313** [comment]
If you switch servers the boss should be back. Does it happen again? If it doesn't, this was most likely a one time rare issue and this can be closed.
