### ISSUE TITLE
Quest Item Gone! (Clearsight Spectacles)

### ISSUE THREAD

**Issue by TIROW2** [Wynncraft/Issues#3205]
My friends helmet (Questitem) is gone!
He was fixing stuff in his enderchest and when the server crashed a few items got deleted.
Now he can't do the quest "The Realm of Light" because you need the helmet to go there!
Please Help!

In Game Name of My Friend: DarkStarMoonPvP

**Comment by Verret001** [comment]
Tell your friend to do /fixquests, That should help, Also please use the **[Directory](https://github.com/Wynncraft/Issues/issues/3197)** before posting duplicates. If this fixes your problem please close the topic.
