### ISSUE TITLE
Quest Item Missing

### ISSUE THREAD

**Issue by AlexanderNag** [Wynncraft/Issues#3207]
I recently started the "Temple of Legends" quest and have gotten to the part where the creeper mask is needed to continue further. I had recently thrown this away, and have found no possible means of re-obtaining it. /fixquests only gave 'Purple Glass Shards' (which I already had).

**Comment by slendersir739** [comment]
Sadly, /fixquests does not work sometimes, also, Wynncraft has a NO-REFUND policy, you can get the mask again in a different class, but that class will not be able to do ToL..

**Comment by Trixter313** [comment]
I don't think that the quest actually takes the creeper helmet because I still have all of mine so just doing the quest on another class should fix it for you.
