### ISSUE TITLE
The New Wynncraft Update

### ISSUE THREAD

**Issue by DaveyVE** [Wynncraft/Issues#3210]
Hey,
My name is DaveyVE and i have a problem..

I joined the Wynncraft server because i saw there was a ''big'' update and I wanted to check it out. When I joined the game I saw some new things and the first thing I saw was that my stats were set to 0. After I saw this I just pressed some attack and crit stats because I thought it fits my Assassin class. After I did this I went to Detlas to get in my bank for some of my coins because I needed to identify my weapon because the new update features (I still didnt know anything about the update features at this point). After I identified my weapon I saw that I still could not use my weapon because my stats were to low.. Now I have the problem that I can't use my weapons anymore..

Can a GM pls help me with this problem and do something like reset my stats again??

- DaveyVE

**Comment by DaveyVE** [comment]
At my level it's also pretty hard to just say: level up to get your stats..

**Comment by Noobgalaxies** [comment]
You can reset your stats by buying a scroll of amnesia at the tower of amnesia, but you have to complete the tower of amnesia quest first.

**Comment by DaveyVE** [comment]
How am I supposed to clear this tower without a weapon of my lvl? I can only find lvl20 weapons that i can use..

Date: Sat, 26 Dec 2015 20:37:38 -0800

**Comment by Trixter313** [comment]
Really the only things I can suggest are what you don't want to hear, level up until you can use the weapon or just at least attempt to do the quest with your current weapon. By leveling up though, you could find a different, possibly better weapon that you fit the requirements for. It isn't too hard to avoid mobs and get into a new town so I think with a little effort you could do the quest legitimately.

I don't think it would be fair to just reset a player's skill points for free when everyone else has to do it the normal way of doing the quest and paying the LE for the scroll. But that's just me.

Hope this helps!
