### ISSUE TITLE
All my LE disappeared

### ISSUE THREAD

**Issue by Equipa2** [Wynncraft/Issues#3212]
My 11 LE disappeared, it happened like this: They were all on my bank. I disconnected and when I returned they were gone, please help me.

**Comment by Verret001** [comment]
Can you give a more precise statement? 
By back do you mean inventory?
How long did you disconnect?
Did you rejoin the same server?

**Comment by Equipa2** [comment]
I have only Optifine.
I disconnect only 1-3 min
I rejoin the same server 
and isnt in my invetory was in my bank

**Comment by Verret001** [comment]
https://github.com/Wynncraft/Issues/issues/3170 https://github.com/Wynncraft/Issues/issues/3166 https://github.com/Wynncraft/Issues/issues/3153 https://github.com/Wynncraft/Issues/issues/3185 https://github.com/Wynncraft/Issues/issues/3205 https://github.com/Wynncraft/Issues/issues/3216
Do any of these resemble your case? If so please close the topic and follow them.

**Comment by Equipa2** [comment]
No that dosent happend to me
