### ISSUE TITLE
Resource pack disagreeing with heads (Cacti)

### ISSUE THREAD

**Issue by colinday99** [Wynncraft/Issues#3214]
Player heads being used in decorations disagree with textures in resource pack
e.g:
![cactus](https://cloud.githubusercontent.com/assets/16448102/12008324/2dc0746c-abe9-11e5-91ff-13f06348a84b.png)
Not a seriously urgent issue; thought it should be brought forward.

**Comment by DarkDemonDragon** [comment]
This isn't really an issue, just how they wanted it to look like. Please close this.
