### ISSUE TITLE
Double XP week not working!

### ISSUE THREAD

**Issue by TheDerpyMan** [Wynncraft/Issues#3215]
After playing for like 2 hours, I saw that like 60% or more of the Wynncraft's server are not with double XP. Only like 5-10 of them got 2x xp. Fix pls.

Another bug I found was at the WynnExcavation C quest, when you escape from those iron golems chasing you, escaping from the meeting, there's a chance you'll get teleported above the lava cave that comes after. So, I spawned on it, and near it was a lot of locations made for creating Maps (Those made out of paper). I saw the Dog missing, reward x20 Emeralds. I got there 2 times in a row, so I had to lose 4 SPs.

**Comment by Verret001** [comment]
Is this still a bug? if so please close the topic, if not we would be happy to help you ferther.
