### ISSUE TITLE
Can not level up

### ISSUE THREAD

**Issue by Antyyy** [Wynncraft/Issues#3219]
Hi, after not logging on to the server for about a year or so, i came on to see the new update. After a hour of so of completing the new quests, i realized i was not gaining experience. I am a level 75 archer and i gained over 200k experience through quests, although in the player menu it says i have 0% till level 76, and my experience bar has not filled a single bit. I remember that leveling was hard, but 200k XP would raise my level by a lot. Can you please fix this issue for me, and anybody else that is experiencing this.

IGN: Anty

**Comment by neonJason52** [comment]
Did anyone find a solution yet?

**Comment by Trixter313** [comment]
Make sure you aren't giving all of your xp to a guild by typing /guild xp 0

**Comment by neonJason52** [comment]
Already did that. I figured out it's just not giving XP in the new Gavel areas of the map.
