### ISSUE TITLE
Texture pack not working 

### ISSUE THREAD

**Issue by Suegerman** [Wynncraft/Issues#3221]
Hey, Ive been playing wynn craft for a long time and every time there is a new update there are never this many amounts of bugs/glitches one is for me is that the texture pack isn't working for me on servers i said texture pack prompt and enabled but its NOT working and when is says want to download it temporary and i click yes it dosent work Please can you help the texture pack did work a few days ago but it is not working now can you please help my problem please!

By:
    Suegerman                                                                     Minecraft Username: suegerman

**Comment by Suegerman** [comment]
Can you please help!

**Comment by Verret001** [comment]
Can you please not make duplicates?
We already have three #3150 #3183 #3150

**Comment by Verret001** [comment]
Please close the topic, Other wise we will have to close some good topics
