### ISSUE TITLE
Map Disappearance

### ISSUE THREAD

**Issue by 0rw** [Wynncraft/Issues#3222]
I joined into a 0% lag lobby the other day, and the map was in chunks, I left and went to a different lobby, I spawned in the grown. Now ever time I want to play Wynncraft, I can no longer play because I always spawn in the ground. Please help me, I want to continue playing.

**Comment by Verret001** [comment]
Please read the directory!

  Stuck in blocks; Solution [ type /kill with 3 or more soul points ] [SOLVED]

#3157 #3156 #3086 #2972 #2940
