### ISSUE TITLE
Mage teleport blinding not working

### ISSUE THREAD

**Issue by Noobgalaxies** [Wynncraft/Issues#3223]
Title says it all. Mobs don't get blinded by my tp anymore ):

**Comment by Trixter313** [comment]
Are you still having this issue? How do you know whether they are being blinded or not?

**Comment by meatloaf4311** [comment]
Most of the bonus effects on spells other than damage are being reworked right now

**Comment by Noobgalaxies** [comment]
Bit of a late reply, but the way I know whether they are being blinded or not is by tping through them and seeing their reaction. Before, they would just get blinded and stand around for a few seconds, but now whenever I tp through them they still immediately turn and come towards me.

**Comment by Trixter313** [comment]
Just tested and they have black particles coming from them and don't attack. Issue seems to be fixed.
