### ISSUE TITLE
PigMan glitch

### ISSUE THREAD

**Issue by superjoan6464** [Wynncraft/Issues#3224]
okay so im not the only one but when i go to that small cave of pig man to get the pigman meat, when i die i lose all my stuff and my money all i had is now gone no matter where i log on or how many times i reset please help i want my stuff back.

**Comment by Johnneh** [comment]
You should only lose your items if you have 0 soul points. Maybe you died too many times, dropped to 0 soul points and now you are dropping your stuff each time you die?

**Comment by DarkDemonDragon** [comment]
@superjoan6464 I've tested it and you don't lose your items unless you have less than 3 soul points. As for your stuff, Wynncraft has a strict no refund policy. Please close this issue as this is your own fault and not due to a bug.
