### ISSUE TITLE
Green Gloop

### ISSUE THREAD

**Issue by Alexiscool2000** [Wynncraft/Issues#3227]
After I have farmed 8 slimey Goo from the cave and go upstairs and talk to Eluzterp he won't accept it and I can't complete the mission if anyone knows what to do please help me

**Comment by Trixter313** [comment]
Could you provide screenshots of the goo and what it currently says in your questbook? Thanks!

**Comment by Alexiscool2000** [comment]
everytime i trow it away and try again so i don't know wat is wrong

**Comment by Trixter313** [comment]
Could you provide screenshots of the goo and what it currently says in your questbook? Thanks!
