### ISSUE TITLE
Resource pack isn't working 

### ISSUE THREAD

**Issue by SuperRavenPro** [Wynncraft/Issues#3228]
I did what it told me to do on the server. I also restarted my computer and restarted minecraft several times ,but the resource pack isn't working. Please and thank you if you are able to help me with my problem.

**Comment by Verret001** [comment]
Please stop making duplicates
#3150 #3183 #3150
Follow up on any of these and close the topic, Thank you.
If none of the listed are your problem we will be happy to assist you.
