### ISSUE TITLE
Temple of The Legends bug!

### ISSUE THREAD

**Issue by bvx** [Wynncraft/Issues#3229]
I was doing the lvl 68 Temple of The Legends quest: I had just gotten the purified light dust from the "magic teacher" on Mage Island, scrolled back to Troms and went to Kelight. I talked to him, gave him the dust, but before i should have got qeust book update, my minecraft crashed. When I joined after this, the dust was gone and Kelight wanted it, but now I can¨t get it - again. (I could not give him the dust twice! The dust is gone!). The quest is now impossible to complete, something which is very unfortunate! I really hope somebody can help me. (In that case: I need a new purified light dust)

**Comment by W-Schnee** [comment]
Did you try the **/fixquests** command? I heard it usually helps with missing quest items.

**Comment by bvx** [comment]
Thank you very much! Didn't know about that command! It fixed it! :D
