### ISSUE TITLE
Guild attack doesn't work

### ISSUE THREAD

**Issue by RickFrensen** [Wynncraft/Issues#3230]
I tried to do a guild attack on a area where were almost none mobs but everytime I typ yes it says battle canceled. I tried everything Yes, yes, ''yes'', 'yes', YES and all of that stuff but none of them worked then i thought I needed to have more soulpoints so I waited till the next morning so I had all of them but still nothing.

(for if it is only bugged for me  or my guild)
Guild name: Ellenor (Ell)
Mc name: rickmen1998

**Comment by Trixter313** [comment]
Confirmed here. Thanks for the bug report!

**Comment by Trixter313** [comment]
Happy to report this is now fixed and working! =)
