### ISSUE TITLE
Water Bottle 'Drought Sands

### ISSUE THREAD

**Issue by INTRUDER74** [Wynncraft/Issues#3233]
I'm doing the quest 'Drought Sands' and for some reason, I cant fill up water bottles. The wiki says I can, I'm  not sure if its out of date or just in-correct, but I don't want to sit there and farm water bottles for a year.

**Comment by Ajusa** [comment]
You have to buy them from the water bottle merchant in Ragni. He is located near the wheat merchants, towards the skeleton dungeon. Hope that helps :D

**Comment by DarkDemonDragon** [comment]
@INTRUDER74 the wiki was out of date even before Gavel, so use it as a general guide, but don't follow it strictly.

**Comment by meatloaf4311** [comment]
There is also a water bottle merchant in the merchant hall in the mesa biome
