### ISSUE TITLE
Docs API Broken

### ISSUE THREAD

**Issue by Ajusa** [Wynncraft/Issues#3234]
This has been bothering me for the past 30 min. I tried sending GET requests to the api, but they all error out saying stuff about MongoDB. Also, since the player counter on the site is broken, is it safe to assume that the api is broken?
Here is the error text:
```
Fatal error: Uncaught Exception: Serialization of 'MongoDB\Driver\Cursor' is not allowed in /usr/share/nginx/html/Website/api/private/library/Cache.php:48 Stack trace: #0 /usr/share/nginx/html/Website/api/private/library/Cache.php(48): Memcached->set('wynncraft_site_...', Object(MongoDB\Driver\Cursor), true, 60) #1 /usr/share/nginx/html/Website/api/private/views/api/generator/onlineplayers.php(24): wynncraft\library\Cache::set('online_player_l...', Object(MongoDB\Driver\Cursor), 60) #2 /usr/share/nginx/html/Website/api/private/controllers/API.php(33): require_once('/usr/share/ngin...') #3 /usr/share/nginx/html/Website/api/public_api.php(49): wynncraft\controllers\API::load('onlineplayers') #4 {main} thrown in /usr/share/nginx/html/Website/api/private/library/Cache.php on line 48
```

UPDATE: I also tried using the stats page on wynncraft. It returns the same error when looking up achievements. Hm...

**Comment by Tama63** [comment]
Working on it this evening , player count just takes a while to load :/
On Sun, 27 Dec 2015 at 15:20, Ajusa Jain <notifications@github.com> wrote:

> This has been bothering me for the past 30 min. I tried sending GET
> requests to the api, but they all error out saying stuff about MongoDB.
> Also, since the player counter on the site is broken, is it safe to assume
> that the api is broken?
> Here is the error text:
>
> Fatal error: Uncaught Exception: Serialization of 'MongoDB\Driver\Cursor' is not allowed in /usr/share/nginx/html/Website/api/private/library/Cache.php:48 Stack trace: #0 /usr/share/nginx/html/Website/api/private/library/Cache.php(48): Memcached->set('wynncraft_site_...', Object(MongoDB\Driver\Cursor), true, 60) #1 /usr/share/nginx/html/Website/api/private/views/api/generator/onlineplayers.php(24): wynncraft\library\Cache::set('online_player_l...', Object(MongoDB\Driver\Cursor), 60) #2 /usr/share/nginx/html/Website/api/private/controllers/API.php(33): require_once('/usr/share/ngin...') #3 /usr/share/nginx/html/Website/api/public_api.php(49): wynncraft\controllers\API::load('onlineplayers') #4 {main} thrown in /usr/share/nginx/html/Website/api/private/library/Cache.php on line 48
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/3234>.
>
-- 
Chris Ireland,

Sent from my iPhone

**Comment by Ajusa** [comment]
Alright, thanks for the update. What language is the backend for it written in? PHP?

**Comment by Tama63** [comment]
The new site is written using the meteor framework and the api written
using an in house PHP micro framework. Meteor isn't really suited for apis
so the Api is legacy for now

On Sun, 27 Dec 2015 at 15:58, Ajusa Jain <notifications@github.com> wrote:

> Alright, thanks for the update. What language is the backend for it
> written in? PHP?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/3234#issuecomment-167421548>.
>
-- 
Chris Ireland,

Sent from my iPhone

**Comment by Ajusa** [comment]
I think it would be a great idea to rewrite the API in Golang. I would be
willing to contribute as well, since I have written some code for backend
before. Also, what do you mean by the API is legacy? Is it no longer being
updated?

**Comment by Tama63** [comment]
API is only updated as needed now
