### ISSUE TITLE
Murder Mystery Quest 

### ISSUE THREAD

**Issue by luka0033** [Wynncraft/Issues#3235]
I cant claim my reward
![2015-12-27_15 31 41](https://cloud.githubusercontent.com/assets/16379672/12010864/423db14a-acaf-11e5-95bc-8cd2ee62a6ad.png)

**Comment by Verret001** [comment]
He needs the murder weapon. I
[2/2] Captain Lorias: I can see you've done good work so far. But there's simply no way to prove anyone's guilt unless we have the murder weapon
Try right-clicking him with the murder weapon?

**Comment by luka0033** [comment]
Ok, ty

**Comment by luka0033** [comment]
I know where the problemm is I dont have the weapon in my inventory and I dont know how to get it.
