### ISSUE TITLE
Bug at the Identiefier

### ISSUE THREAD

**Issue by chrixio** [Wynncraft/Issues#3236]
I played Wynncraft and completed the Quest Memory Paranoia and i got a rare ring, so i go to the Identiefier and all players left the game and i got kicked, when i relloged the ring was not in my Inventory. So pls give me back the Ring! 

My ingame Name: chrixio

**Comment by BUTTERBLOB1** [comment]
that happened to me too just with my bobs mythic wand!

**Comment by Verret001** [comment]
Im sorry but wynncraft has a very strict rule about no item refunds.
