### ISSUE TITLE
Quest cancelled due to server 

### ISSUE THREAD

**Issue by Masmotte** [Wynncraft/Issues#3240]
Hello everyone,
I was finishing a very long quest, and i was doing the last step : look for my reward i guess. Just after right-clicking the NPC the server crash and after reconection i had lost all my item quest that i had to collect (The Assistant still asks me for what he need) i look at my inventory and i found out that all my item quest have disappear ! (here the screen)
![screen capture bug](https://cloud.githubusercontent.com/assets/16454210/12011360/65b3eb9c-acca-11e5-8071-7759989136ff.png)

**Comment by TrashcanMan** [comment]
Is this Potion Making? If so, unfortunately you have to go and collect all those items again. Since none of the items are quest items, there's no way to get them back.
