### ISSUE TITLE
Mage's Ice Snake not slowing/freezing enemies?

### ISSUE THREAD

**Issue by AmbassadorArt** [Wynncraft/Issues#3241]
Okay, so isn't Mage's Ice Snake supposed to apply massive slowness to enemies?  That's the whole point of the attack and makes Mage's a lot weaker actually.  I don't think this intentional for two reasons:

#1: The "Classes" section of the help menu still says it's supposed to slow
#2: It still slows other players when in the Nether/Dueling

I tried this on enemies of all elements and movement speed/AI's.  Some clarity and a fix would be nice.

**Comment by TrashcanMan** [comment]
I've been experiencing this as well.

**Comment by RedMorcus** [comment]
In some cases it even seem to make enemies faster, but maybe that's just my imagination...

**Comment by Wozabs** [comment]
It doesn't work for me either and Im using the Dark Wizard class, that may be it. I would appreciate if this gets fixed in the next patch/update.

**Comment by CMWizard** [comment]
This is true for all mages, being dark wizard doesn't really make a difference. I personally find this to be quite annoying, especially because I can't slow the really fast mobs, like CoW.

**Comment by Trixter313** [comment]
I just tested and to me they looked like they are being slowed now. If not, reply back.

**Comment by CMWizard** [comment]
It is now functional again thank you

**Comment by Trixter313** [comment]
Great to hear and see confirmed! =)
