### ISSUE TITLE
LOST MY LEGENDARY WEAPON

### ISSUE THREAD

**Issue by Lambirisk** [Wynncraft/Issues#3245]
I WAS IDENTIFYING A WEAPON AND WHEN I WAS LOOKING AT IT DISAPPEARED. IT WAS A WIND WEAPON WITH 10-190 AND THE SERVER RESTARTED I LOST IN TOTAL 222 EMERALDS

**Comment by Verret001** [comment]
Good job, Your the 7th duplicate!!!
#3170 #3166 #3153 #3185 #3205 #3216

**Comment by Lambirisk** [comment]
LOOK IN MY MINECRAFT LOG

**Comment by Verret001** [comment]
Wynncraft has a strict no refund rule. 
I hate to break it to you but your **not getting your weapon back.**

**Comment by zeovas** [comment]
I lost my weapon too! please fix this

**Comment by Ajusa** [comment]
This isn't really an issue that can be fixed. If you lost your weapon, you will not get it back. Simple.
