### ISSUE TITLE
Reward not received upon finishing quest.

### ISSUE THREAD

**Issue by Deestinyer** [Wynncraft/Issues#3246]
So recently I finished the headless hunt, it exlaimed that I was awarded 5120 emeralds however I did not receive them. My inventory was not full, there were approximately 3-4 empty slots which would have been enough for the reward. http://prntscr.com/9j6ku2 http://prntscr.com/9j6kz2
(The 50 emerald blocks seen in inventory were not originally received from the quest if that is of much importance). Hopefully this evidence is sufficient enough. If not, I understad. Though I would be very grateful if this issue was to be resolved, thank you!

**Comment by Verret001** [comment]
Your not the only one. Two others are experiencing the exact same thing.
#3227 #3242

**Comment by Deestinyer** [comment]
My issue is not the exact issue that the other players are experiencing.

I did not receive the reward, the other issues complain about not receiving the quest item.

In simple terms, I completed the quest, yet did not get the emerald prize. Therefore I believe that no other user has experienced this, from what I have researched.

**Comment by Deestinyer** [comment]
The same thing happened upon completing the 'shattered minds'. I'm really hoping for a quick solution to this, as I'm losing out on rewards. Also, this only seemed to have happened on 3x xp worlds.

**Comment by Trixter313** [comment]
I think this happens when you already have emeralds in your inventory. Try doing quests without any emeralds in your inventory to see if that helps as a temporary workaround. Even just dropping any emeralds on the ground before you get the reward and then picking them back up afterward should help.

**Comment by Deestinyer** [comment]
So there is no way for me to gain back the emeralds that I have lost? I do admit that I had emerald blocks in my inventory when completing both quests, and only had a couple of emeralds when finishing the muder mystery. This may be the cause, I'll bare that in mind for next time. If there's no way for me to regain the emeralds that I received, I fully understand - thanks a bunch for the help!

**Comment by Trixter313** [comment]
Yeah, unfortunately Wynncraft has a strict no ingame item refunds policy so as for the emeralds already lost, there's not much that can be done. I hope this doesn't happen to you any more!

**Comment by Deestinyer** [comment]
Quite a shame, anyway thanks again for the replies! :)
