### ISSUE TITLE
Wiki Email Confirmation

### ISSUE THREAD

**Issue by PieKing1215** [Wynncraft/Issues#3249]
@Tama63 just fixed the PEAR glitch ( #3158), but  now I get this when I try to confirm my wiki email:

Fatal error: Uncaught TypeError: Argument 1 passed to MWExceptionHandler::rollbackMasterChangesAndLog() must be an instance of Exception, instance of ParseError given, called in /usr/share/nginx/html/wynncraft_wiki/includes/exception/MWExceptionHandler.php on line 139 and defined in /usr/share/nginx/html/wynncraft_wiki/includes/exception/MWExceptionHandler.php:112 Stack trace: #0 /usr/share/nginx/html/wynncraft_wiki/includes/exception/MWExceptionHandler.php(139): MWExceptionHandler::rollbackMasterChangesAndLog(Object(ParseError)) #1 [internal function]: MWExceptionHandler::handle(Object(ParseError)) #2 {main} thrown in /usr/share/nginx/html/wynncraft_wiki/includes/exception/MWExceptionHandler.php on line 112

Plz fix. I want to verify my wiki acct.

**Comment by Tama63** [comment]
will look into tomorrow xxx :heart:

**Comment by PieKing1215** [comment]
thx <3

**Comment by meatloaf4311** [comment]
I went to click on the mail confirmation button then:



Fatal error: Uncaught TypeError: Argument 1 passed to MWExceptionHandler::rollbackMasterChangesAndLog() must be an instance of Exception, instance of ParseError given, called in /usr/share/nginx/html/wynncraft_wiki/includes/exception/MWExceptionHandler.php on line 139 and defined in /usr/share/nginx/html/wynncraft_wiki/includes/exception/MWExceptionHandler.php:112 Stack trace: #0 /usr/share/nginx/html/wynncraft_wiki/includes/exception/MWExceptionHandler.php(139): MWExceptionHandler::rollbackMasterChangesAndLog(Object(ParseError)) #1 [internal function]: MWExceptionHandler::handle(Object(ParseError)) #2 {main} thrown in /usr/share/nginx/html/wynncraft_wiki/includes/exception/MWExceptionHandler.php on line 112

**Comment by Tama63** [comment]
fixed

**Comment by PieKing1215** [comment]
Thanks Tama you're the best!

**Comment by meatloaf4311** [comment]
Yay!
