### ISSUE TITLE
Mage & Archer Classes not working

### ISSUE THREAD

**Issue by Verret001** [Wynncraft/Issues#3250]
This is a compilation of many people that have had the tiring glitch/bug, and have lost their
mage or archer class due to it. [ ERROR; "There has been an error... Try again. ]
Let it begin!

#1
First coming up is @MrNinjaBen (https://github.com/MrNinjaBen)

  - Title: **Unable to choose class**
I wanted to play wynncraft because of the massive gavel update, and when I went to choose the archer class, my primary class, It just exited the menu and left me alone in the wool room and after a few second, sent me back to the hub. Any help is appreciated, thanks.

  -  **Comment #1 @ibrendon456 (https://github.com/ibrendon456)**
I am having the same problem. I am unable to play my level 56 mage. When I go to the character selection or /class function, I select the character but due to some error, I am unable to play as that character and ONLY that character.

  -  **Comment #2 @intheshadowsXD (https://github.com/intheshadowsXD)**
I am having issues with my archer and mage

  -  **Comment #3004  @shacharss  (https://github.com/shacharss)**
Same with my level 50 archer, Someone help!!!!!
IGN: shacharss

**End (Closed from gravel clean)**
https://github.com/Wynncraft/Issues/issues/3006         
                                                               
-------------------------------------------------------------------------------------------------------------------------

#2
Second up with #2 comes @shacharss (https://github.com/shacharss)

  - Title: **Classes not loading in**
My best class, archer wasnt loading. I tried to click it in the class selection, but nothing happened! I havent played in a while and that might be the problem.

**No further comments.**

**End (Closed from gravel clean)**
https://github.com/Wynncraft/Issues/issues/3059              
                                                                  
---------------------------------------------------------------------------------------------------------------------------------

#3 
The already long #3 comes @fabikong02 (https://github.com/fabikong02)

  - Title: **Class select errors (unsolved problem for years)**
Dear Wynncraft-Team,
I have an BIG problem on the Wynncraft MMORPG srever.
If i select a class, i getting an error.
The chat says : 
"There has been an error... Try again.
Select a class! Each class saved
individually across all servers, you can comeback at any time with /class and select
another class!"

I had try it again (more than 5 times) but i`m getting anytime an error.
No matter which class I select, I always get the same error.

Also, I've ever reported this error, but did not get the reaction to what I find very badly by the server team.
Now another year passed and I still have the same error.
Can you fix the error or unable to eliminate these errors for her?

And don`t close this Issue without fix the problem (if the server team do this i spam this everyday in the issues with different accounts, because i have this problem for many years!)

My Minecraft Ingamename is: Crystalkong

I hope the serverteam fix this error quickly, because I want to play on the Wynncraft-server

-Crystalkong

**End (Still open, Check it out!)**
https://github.com/Wynncraft/Issues/issues/3182               
                                                                      
---------------------------------------------------------------------------------------------------------------------------------

#4 
And #4 comes with @Gregoryus (https://github.com/gregoryus)

  - Title: **Can't play server ! Admin help please!**
So basically when I come to play Wynncraft, I connect to Wynncraft then to a server, and at the class chosing step, I click on archer and nothing happens, I just get a message telling to try again, but no matter how much I try it just doesn't work. So I tried to logout and login and to close and run the game again but this time I can't connect to Wynncraft at all, I get this message: "ExceptionConnecting:RuntimeException : Server is online mode! @net.md_5.bungee.ServerConnector:261".
I just don't know what's going on, I've never been able to play Wynncraft NOT ONCE,If it can help I changed my pseudo from Gregorius78 to Gregoryus.
Hope you will find something to help, Gregoryus

**End (Still open, Check it out!)**
https://github.com/Wynncraft/Issues/issues/3278

--------------------------------------------------------------------------------------------------------------------------------------

#5 
With #5 comes @kiwikrazy (https://github.com/kiwikrazy)

  - Title: **Haven't played since this summer, cant log in to archer class**
Hi, I recently decided to start to play wynncraft again because of the new expansion. I was immediately sad though because whenever i tried to choose my level 45 archer class, it says "There has been an error. Try again." Is there anyway I can get my account back? I spent probably 150-200 hours playing this class, and I really do not feel like starting over. Please help me!

**End (Closed, Check it out!)**
https://github.com/Wynncraft/Issues/issues/3258

------------------------------------------------------------------------------------------------------------------------------------------

#6 
And then with #6 comes @MrMcWalrus (https://github.com/MrMcWalrus)

  - Title: **Logins**
I can enter a world my other classes but not my mage, it says 'there has been an error please try again'. If someone could respond quickly that would be awesome since the mage is my main.

**End (Closed, Check it out!)**
https://github.com/Wynncraft/Issues/issues/3338

----------------------------------------------------------------------------------------------------------------------------------------

#7 
Coming up with a legendary #7 comes @survivalmonkney (https://github.com/survivalmonkney)

  - Title: **Corrupted character?**
I logged on to the Wynncraft server, joined the game, and it logged me into my fairly low level mage. OK, so I typed in /class to get onto my level 53 archer. I click the icon and it says 'there's been an error... please try again' I try it again, it says it again. I've tried it on multiple servers, none work. I can get into my other classes fine, it's just this one level 53 archer. I've tried relogging, restarting minecraft, restarting my computer, nothing works. I've also noticed that in the stats it says the archer has 112% xp? I have no idea what this is or how to fix it.

I haven't played Wynncraft for a few months, so it might've been an update that messed something up.

**End (Closed, Check it out!)**
https://github.com/Wynncraft/Issues/issues/3322

--------------------------------------------------------------------------------------------------------------------------------------
Finally, My own complaint.

This issue is still not fixed, 
My level 42 mage is unable to load. Everytime I load it I get a message saying
 "There has been a error, try again" This not happen to my archer (Thank god)
But It has to others. I have a video As to show exactly what is going on (https://youtu.be/NpyLuoczjBc)

This upsets me. This is a altered version of my earlier statement, I have not been able to use my mage 
for a while now, as well as my 40/40 horse and all the other things that were in my inventory.
Please fix this, I really want to be able to use my mage again. Thank you for reading this and have a good day.

Known People affected by this mess;
@MrNinjaBen (https://github.com/MrNinjaBen)
@ibrendon456 (https://github.com/ibrendon456)
@intheshadowsXD (https://github.com/intheshadowsXD)
@shacharss  (https://github.com/shacharss)
@Verret001  (https://github.com/Verret001)
@fabikong02 (https://github.com/fabikong02)
@kiwikrazy (https://github.com/kiwikrazy)
@MrMcWalrus (https://github.com/MrMcWalrus)
@survivalmonkney (https://github.com/survivalmonkney)
If you are affected or you know someone affected please post it in the comments bellow.

**Comment by kiwikrazy** [comment]
This is so true. I still cannot access my level 45 archer, and I'm glad I'm not the only one with this problem! These admins need to actually do something and help!

**Comment by Verret001** [comment]
@kiwikrazy Exactly! This is the biggest problem and least reconized one. Hopefully this can shine some light on it!

**Comment by shacharss** [comment]
I agree, this needs some attention!

**Comment by Verret001** [comment]
This bug isn't a one person thing. This is a server wide phenomenon, as well as it being a unsolved problem for years. Hopefully we can shine some light on this.

**Comment by survivalmonkney** [comment]
Glad I was seen, this is a huge problem, one the admins seem like they're ignoring.

**Comment by scorixear** [comment]
any sign that someone cares from the team?

**Comment by Dar-krusos** [comment]
Oh wow. I never even knew this bug existed. I will try and help your cause, guys!

**Comment by Verret001** [comment]
Thank you @Dar-krusos! Any help is apreciated at this point.

**Comment by Verret001** [comment]
@survivalmonkney I am a admin, Just not a developer

**Comment by sheepyyy** [comment]
I just started out, and when I made my classes, or tried to select on them, they didn't work either :c

Same error message said above kept appearing.

IGN xxMineSheepxx

**Comment by lkjfdsaofmc** [comment]
Have fun getting a new minecraft account sheepyyy, my accounts been bugged for years and years, i've yet to even find a place where a dev says they're trying to fix this... yay for alternate accounts -.- though i wanna start playing again on my main account cause the account i've been using is kinda lame now :c
