### ISSUE TITLE
Internal Exception: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory

### ISSUE THREAD

**Issue by supersonicth** [Wynncraft/Issues#3253]
Recently, the resource pack stopped downloading for me. Trying to resolve this issue, I deleted my server-resource packs folder. However, now when trying to join the game, this message pops up.
![screen shot 2015-12-27 at 3 19 14 pm](https://cloud.githubusercontent.com/assets/16456327/12012547/34f74526-acc0-11e5-8fcc-295488c7efbb.png)

**Comment by Verret001** [comment]
Your not supposted to delete the entire folder, your supposed to delete whats inside the folder.
Make a new folder and it will work again.

**Comment by v3Monsta** [comment]
Just to be even clearer on this, name the folder "server-resource-packs"
