### ISSUE TITLE
Bug on WynnExcavation Site A

### ISSUE THREAD

**Issue by pinkynice1** [Wynncraft/Issues#3255]
Basically, after I clicked on Vade with the translated scroll, the game timed out, before the quest book updated. This is problematic as now I'm stuck at the step of bringing Vade back the translated scroll and am unable to continue with the quest. Please help me, I don't want to restart my archer world

**Comment by pinkynice1** [comment]
Or is there a no item refund rule?

**Comment by Ajusa** [comment]
Did you try /fixquests ?
It is a generic command for when you lose  quest item. Other than that, I don't know.

**Comment by pinkynice1** [comment]
oh thanks :D

**Comment by Verret001** [comment]
Please close the topic if this resolved your issue, If not we will help you in every way we can. Thank you.
