### ISSUE TITLE
Lost Soles Quest

### ISSUE THREAD

**Issue by essem2** [Wynncraft/Issues#3257]
you need to identify the Abysso Galoshes for the quest and one time during the quest

**Comment by Verret001** [comment]
Could you be more specific, What is the problem?

**Comment by essem2** [comment]
1. at Stage 2 you need to bring Ferndor the Abysso Galoshes, so you need it to identify them for the quest
2. After this stage you'll get them back but agian unidentifyed so you must identify them agian to finish the quest

**Comment by Trixter313** [comment]
I don't think there's really any way around this since the game doesn't give you the exact boots back but instead spawns in some more new ones. As long as you don't identify them until the quest is over you should be good.
