### ISSUE TITLE
Haven't played since this summer, cant log in to archer class

### ISSUE THREAD

**Issue by kiwikrazy** [Wynncraft/Issues#3258]
Hi, I recently decided to start to play wynncraft again because of the new expansion. I was immediately sad though because whenever i tried to choose my level 45 archer class, it says "There has been an error. Try again." Is there anyway I can get my account back? I spent probably 150-200 hours playing this class, and I really do not feel like starting over. Please help me!

**Comment by slendersir739** [comment]
It is probably lag because after Gavel came out, there has been mass amounts of players. You should wait a while, then try again.

**Comment by Verret001** [comment]
This is not lag!
https://github.com/Wynncraft/Issues/issues/3250
