### ISSUE TITLE
Lost my main Spear

### ISSUE THREAD

**Issue by mbrsbsh** [Wynncraft/Issues#3259]
I logged in to play a little wynncraft and as soon as i logged in i realized my spear that i use was gone. It was called the razor or something like that.

**Comment by RedMorcus** [comment]
Sorry, there is a strict no refund policy. Also, please try to be specific when you describe issues like this.

**Comment by Verret001** [comment]
I have to say @RedMorcus Is right, but try to be more specific so we can try and fix it.
Is it similar to any of these?
#3205 #3216
#3170 #3166 #3153
#3236 #3237
