### ISSUE TITLE
Iron Heart Part 2 Glitch

### ISSUE THREAD

**Issue by Chri630** [Wynncraft/Issues#3260]
This house says I require a factory helmet, I have it on me, even tried it just in my inventory but it wont let me in. Please help

![2015-12-27_23 38 53](https://cloud.githubusercontent.com/assets/16396890/12014103/7aee3598-acf3-11e5-98db-8f244bf85fee.png)
![2015-12-27_23 38 58](https://cloud.githubusercontent.com/assets/16396890/12014102/7aeca34a-acf3-11e5-9120-806f18dedc77.png)

**Comment by M64mc** [comment]
You need to go to Daxes house first.

**Comment by Verret001** [comment]
If this has resolved you problem please close the topic, if it has not we would be happy to help.
