### ISSUE TITLE
Potions display incorrect nametag

### ISSUE THREAD

**Issue by TrashcanMan** [Wynncraft/Issues#3263]
If you right-click on the Potion Merchant, then mouse over a potion in your inventory, its nametag changes back to the old nametag. This fixes if you exit the shop window. I'm not sure if this works with other merchants as well.
![2015-12-25_20 15 43](https://cloud.githubusercontent.com/assets/6947594/12014705/20574ae6-ace6-11e5-9c05-6024ba3399c1.png)

**Comment by Trixter313** [comment]
I just tried reproducing and can't seem to get it to do this. If you can, comment and I'll reopen the issue but I believe it's been fixed.

**Comment by TrashcanMan** [comment]
Yeah, it appears to be fixed now.

**Comment by Trixter313** [comment]
Great =)
