### ISSUE TITLE
Stuck in wall or floor

### ISSUE THREAD

**Issue by DanTheManHovan** [Wynncraft/Issues#3264]
I just finished doing a quest with my friends and the end teleporter teleported me into the floor or wall (idk which cause i cant see anything). Now every time I log in, I am stuck in this wall and cant do anything. I've tried using my teleport spell (didn't work). Then I tried what i did the first time this happened(this is the second): using a tp scroll (game wouldn't let me). So now i cant even play the game due to me being stuck in a wall. Which is upsetting because now I cant play during double xp week. Fix your servers pls.
![2015-12-28_01 20 57](https://cloud.githubusercontent.com/assets/16459341/12014914/83c36e9a-ad02-11e5-87aa-2815af2a200e.png)

**Comment by Monkeysz** [comment]
Do /kill... with +3 soul points.
