### ISSUE TITLE
Can't complete the "Prison Story" quest

### ISSUE THREAD

**Issue by NAgaming** [Wynncraft/Issues#3265]
I was replaying the game when Gavel came out. I started the Prison Story quest and got the key to help Ooni escape, but the server crashed mid-conversation, but before I got the reward. I logged back in, and it said I still needed to give Ooni the key, but the problem was I didn't have it because of the server crashing in the middle of a quest reward conversation. I went back to the guy in the sewer who gives you the key, but since I already talked to him, the game wouldn't let me get the key back from him. I really need an Admin for the Wynccraft server to help, but I don't know how to contact them.

**Comment by DarkDemonDragon** [comment]
Try doing /fixquests and seeing if this gives you back the key.

**Comment by Trixter313** [comment]
If DarkDemonDragon's suggestion worked, we'd appreciate it if you closed the issue. Thanks!

**Comment by NAgaming** [comment]
Thanks!

**Comment by Trixter313** [comment]
I'm assuming your issue is now fixed. Have a great day!
