### ISSUE TITLE
cant log into wynncraft

### ISSUE THREAD

**Issue by ImFRozn** [Wynncraft/Issues#3267]
a friend of mine cant log into wynncraft, his name is ReMooooN 
screenshots: http://imgur.com/a/meuAq

**Comment by Verret001** [comment]
I had this problem, Try changing your version of minecraft. It worked for me.
If this resolves your problem please close the topic.

**Comment by Trixter313** [comment]
Does your friend have the server resourcepack enabled?

**Comment by Trixter313** [comment]
I'm guessing your issue is now resolved due to no response. If that doesn't work for your friend, tell them to try enabling the server resourcepack. Have a great day!
