### ISSUE TITLE
/forum command broken

### ISSUE THREAD

**Issue by tttre** [Wynncraft/Issues#3268]
Hello Wynncraft Team,
I have a very "common" bug to report. As you probaly know that when you write "/forum [Forumname]" you would get the Rank Vip/Vip+ in the Forum... but you didn't get it, i hope you'll ffix it in the next Update!
Best Regards
-Ciaran-

**Comment by Trixter313** [comment]
Should be fixed now! https://forums.wynncraft.com/threads/forum-account-linking.153758/ =)
