### ISSUE TITLE
Items lost through new gavel update and other unnecessities.

### ISSUE THREAD

**Issue by superabel123** [Wynncraft/Issues#3269]
So I was a player before the gavel update and thus all my items became unidentified including the ones i was wearing at that time but when i took my helm off the rest of my set of gear was lost
The following was lost:
An epic chestplate
A legendary pants called Kratke
and another legendary,a boots named Anchoryl
Another notice is about the questioning of the needs of requiring certain stats points to use my weapons,at the spawnpoint of the game I immediately used up my skill points to put all defence and the rest intelligence.Then,I realised i needed 10 strength to use my bow so I wondered around 3 hours straight to get 1 le and died multiple times.Once I got the scroll,I pumped it into strength,defence and intelligence and finally i realised i needed aglity,now having no money,I am unable to do anything about this.Thus,I hope you are able to fully restore my items and consider whether the usage for meeting skills points requirements for weapons are neccesary.Thanks
Yours Sincerely
Superabel123

**Comment by BlahBlah161616** [comment]
There is a strict no return policy on Wynncraft. But I'm sure there are some friendly players who can help you.

**Comment by superabel123** [comment]
Ok noted thx guys
