### ISSUE TITLE
+Tier attack speed doesn't work

### ISSUE THREAD

**Issue by Killerboy2807** [Wynncraft/Issues#3271]
Tested it with Mummy's rag and a bow.
Absolutely no attack speed was gained from using it.

**Comment by Ajusa** [comment]
Switch to another item, then back. It should work.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
