### ISSUE TITLE
Pirate Island - No item identifier and Emerald bankers

### ISSUE THREAD

**Issue by Forcellrus** [Wynncraft/Issues#3272]
Title says it all. There is no Item Identifier inside his house and no bankers inside bank.

**Comment by DarkDemonDragon** [comment]
You'll need some pictures, but I can confirm that this is a legitimate issue.

**Comment by stangefall** [comment]
here are the pictures
![2016-01-08_17 10 04](https://cloud.githubusercontent.com/assets/16395360/12212736/c3530394-b654-11e5-9b24-90e3b2c3fdd4.png)
![2016-01-08_17 10 07](https://cloud.githubusercontent.com/assets/16395360/12212737/c353df1c-b654-11e5-8974-383339f751b7.png)
![2016-01-08_17 10 20](https://cloud.githubusercontent.com/assets/16395360/12212740/c357cf0a-b654-11e5-96cd-41f29cd64871.png)
![2016-01-08_17 10 25](https://cloud.githubusercontent.com/assets/16395360/12212739/c355cea8-b654-11e5-88bf-d0a73feda526.png)
![2016-01-08_17 10 32](https://cloud.githubusercontent.com/assets/16395360/12212738/c3549dda-b654-11e5-8d0b-0f9420d78b0b.png)
![2016-01-08_17 10 36](https://cloud.githubusercontent.com/assets/16395360/12212741/c358c6da-b654-11e5-88fc-e0c11dcd17e0.png)

**Comment by Trixter313** [comment]
Confirmed to still be occurring.

**Comment by RedNightDragon** [comment]
I found this before I posted. This is still occurring.

**Comment by AckroWynn** [comment]
I will fix this today, so be sure to close this at the end of the day @Trixter313

**Comment by Fornax96** [comment]
This is still happening, the item identifier is nowhere to be seen:
![2016-07-22_20 13 35](https://cloud.githubusercontent.com/assets/1247928/17066770/da05548c-5048-11e6-8549-9b10c81c9893.png)
![2016-07-22_20 13 48](https://cloud.githubusercontent.com/assets/1247928/17066775/df9e8b34-5048-11e6-91d9-91515bf2c986.png)

It's also not just a one-time thing, it happened yesterday too

**Comment by Moe-Ronickah** [comment]
Did you try changing servers to see if the identifier was missing on multiple servers?

**Comment by Trixter313** [comment]
It's been fixed on the GM server but hasn't been pushed to the play server yet.
