### ISSUE TITLE
Phantom blade wrong skin

### ISSUE THREAD

**Issue by SioN-wynncraft** [Wynncraft/Issues#3274]
I am using phantom blade and see it like a elemental bow.

**Comment by Trixter313** [comment]
Could you provide a screenshot if possible? Thanks!

**Comment by SioN-wynncraft** [comment]
![2015-12-29_182100094](https://cloud.githubusercontent.com/assets/16464117/12037608/129331da-ae59-11e5-809e-c13e547effde.PNG)
here

**Comment by Trixter313** [comment]
Thanks for the screenshot! This should be fixed soon. =)

**Comment by Trixter313** [comment]
Just checking in, is the issue still occurring? Thanks!

**Comment by SioN-wynncraft** [comment]
Soru I don't know I Gave the item to another guy

**Comment by Trixter313** [comment]
Ok, that's fine. I'll try and find one to see if it's still happening or not.

**Comment by Trixter313** [comment]
I believe this has been fixed. If anyone is still experiencing it, simply comment and I can reopen the issue. Thanks!
