### ISSUE TITLE
I can't complete the "Jungle Fever" quest.

### ISSUE THREAD

**Issue by Zoomings** [Wynncraft/Issues#3275]
I was talking to Worid and I had the 64 LE and the server crashed so I got back on and he asks me for the LE, and I don't have it because the server crashed when I was in mid-conversation. So I went back to the guy in Almuj and tried to get the LE but he wouldn't give it to me, now I can't complete the Quest. Please, help me. http://imgur.com/1EkYgeF

**Comment by DarkDemonDragon** [comment]
Try doing /fixquests and seeing if it gives you back the LE.

**Comment by Zoomings** [comment]
Thank you very much
