### ISSUE TITLE
Missleading text in Aldorei's Secret Part I

### ISSUE THREAD

**Issue by Marianol24** [Wynncraft/Issues#3280]
To start this quest you are supposed to talk to Elrund, at one of the entrances to Alderei. The NPCs at the other entrances tell you he is at the eastern entrance, as you can see in the screenshot below

http://prntscr.com/9jheha

However, Elrund is in the western entrance

http://prntscr.com/9jhgw3

**Comment by Trixter313** [comment]
I agree with you. Thanks for the bug report!

**Comment by Verret001** [comment]
A developer made a mistake...
Proves wynncraft is not made by AI

**Comment by Moe-Ronickah** [comment]
Is this fixed, yet?

**Comment by Moe-Ronickah** [comment]
FIXED.
