### ISSUE TITLE
Green Gloop

### ISSUE THREAD

**Issue by Meowlegend** [Wynncraft/Issues#3281]
I was doing the Green Gloop quest and it asks for 5 glass bottles. How are players suppose to do this, the potions disapear out of the invetory. Water bottles dont work either. Hopefully you guys can get this fixed.

Thanks,
-Meow

**Comment by Trixter313** [comment]
You now get empty bottles as mob drops. One location I know of is near the identifier on the emerald trail. Hope this helps!
