### ISSUE TITLE
Stuck on ''A Fighting Species'' quest.

### ISSUE THREAD

**Issue by kolkkie** [Wynncraft/Issues#3282]
Hello,

When i was about to finish the ''a fighting species'' quest the server stopped.
when i logged back in the items I needed for the quest were gone, but the quest NPC says that he still need them.

I can't get the items back because i need the ''orc mask'' to get ''Gorgu's Handprint''
I need both items to finish the quest.

I hope you guys can fix this bug

Gamer-tag: kolkkie

-kolkkie

(sorry for the bad grammatic)

**Comment by Marianol24** [comment]
Does /fixquests work?

**Comment by kolkkie** [comment]
it worked thanks
