### ISSUE TITLE
Making Guilds Don't Work. 

### ISSUE THREAD

**Issue by HybridBonnie** [Wynncraft/Issues#3283]
So I was trying to name my new guild I was going to make, but whenever I type ANYTHING the guild master says I need to use english characters A-Z. I was at the master for an hour trying to make a guild. Can you fix this,

**Comment by Verret001** [comment]
duplicate of #3190
Please follow up on that issue.
Use the **[Directory](https://github.com/Wynncraft/Issues/issues/3197)** to make sure your not making duplicates
