### ISSUE TITLE
Gavel Pack isn't loading???

### ISSUE THREAD

**Issue by farouk47** [Wynncraft/Issues#3284]
With the new update came with a new Texture Pack. Whenever I play it doesn't load! I have 
Server Resource Packs: Enabled
It still doesn't load! I guess a way to help myself and others who have this problem is to make
an actual texture pack.
Please solve this issue. It's really hard to play without the pack

**Comment by Verret001** [comment]
duplicate of #3150 #3183 #3150

**Comment by Chillydog117** [comment]
Got the same issue. That's a good idea where there's a downloadable texture pack.
