### ISSUE TITLE
Rise of the Quartron issue... again

### ISSUE THREAD

**Issue by dragan17** [Wynncraft/Issues#3286]
I'm sorry to bother you, this issue has been described before. However for me, the game is not just lagging. The NPC just does not seem to recognize that I have everything I need.
![image](https://cloud.githubusercontent.com/assets/16466463/12022857/323f38c8-ad94-11e5-83d7-3b068aee8987.png)

**Comment by Verret001** [comment]
May I see a screenshot of your book?

**Comment by dragan17** [comment]
![image](https://cloud.githubusercontent.com/assets/16466463/12023485/3d7100ae-ad9a-11e5-971f-9f495df37574.png)

**Comment by Verret001** [comment]
Try /fixquests

**Comment by dragan17** [comment]
That does not work because I am not missing an item. Also just a moment ago the same thing happened. I cannot complete the Maiden's tower because it isn't recognizing that I have a Black Veil. I don't know what it causing this

**Comment by Troll2828** [comment]
I had the same issue. When you get to the entrance of the fight with beacons, don't go through the beacons. Go through the entrance under the stairs(I don't know if this makes sense). The only reason you were able to get through the beacons is lag. I hope this helped.

**Comment by dragan17** [comment]
Thank you so much! This worked. I couldn't go through there the first time because of the lag, but now it worked!
