### ISSUE TITLE
Guild Attacks not working

### ISSUE THREAD

**Issue by CoolZakCZ** [Wynncraft/Issues#3290]
I do /guild attack

The chat says "This territory has 1000 mobs protecting it
Are you sure you want to launch an attack?"

The sign appears, I type "yes" and hit done, but it does nothing. Instead it tells me "battle cancelled"

**Comment by Trixter313** [comment]
Confirmed here also =)

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3230

Please direct any further comments to the original issue. Thanks!
