### ISSUE TITLE
seriously? Why?

### ISSUE THREAD

**Issue by SwagMasterDee** [Wynncraft/Issues#3292]
I was doing the "Memory Paranoia" quest and died after being AFK for like, 2 seconds. After I respawned this mission popped up....

![2015-12-28_12 10 42](https://cloud.githubusercontent.com/assets/16467214/12023991/9b6b56f2-ad5c-11e5-9aed-0e4df2782e8c.png)

Not really a bug, but come on? really?

**Comment by Tama63** [comment]
yeah it's not really a bug but I think the game team are aware of these ridiculous missions
