### ISSUE TITLE
Spawn error

### ISSUE THREAD

**Issue by stake4443** [Wynncraft/Issues#3294]
Whenever i try to spawn into a world it spawns me at the starting caravan, then teleports me to 0,0 but doesn't open the class choosing menu, i see an island but then fall through it. every once and a while there is another player there. 

![2015-12-28_12 48 39](https://cloud.githubusercontent.com/assets/16468110/12025379/35d7b82e-ad63-11e5-8a59-b11f4fc7987d.png)
![2015-12-28_12 48 40](https://cloud.githubusercontent.com/assets/16468110/12025380/36b101e2-ad63-11e5-8e5f-2e0722fecb59.png)
![2015-12-28_12 49 18](https://cloud.githubusercontent.com/assets/16468110/12025381/3930126e-ad63-11e5-86b4-2b78e67fed7a.png)
![2015-12-28_12 49 56](https://cloud.githubusercontent.com/assets/16468110/12025382/3a131dde-ad63-11e5-8728-2ab1de50be23.png)
![2015-12-28_12 49 58](https://cloud.githubusercontent.com/assets/16468110/12025383/3b4fb068-ad63-11e5-855b-bf49aa3fe2dd.png)
![2015-12-28_12 51 15](https://cloud.githubusercontent.com/assets/16468110/12025384/3ddf2958-ad63-11e5-8bfd-b041990dc150.png)

**Comment by Verret001** [comment]
Redownload your texture pack.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by stake4443** [comment]
It just started working again a few minutes ago thanks t=for the help

**Comment by Trixter313** [comment]
Great to hear!
