### ISSUE TITLE
Wynncraft quest bug: wynncraft excavation site A 

### ISSUE THREAD

**Issue by SioN-wynncraft** [Wynncraft/Issues#3296]
I killer the boss like 4 Or 5 times but I can't finish it. Quest book stucked on ''found the tomb'' help would be appreciated.

**Comment by Verret001** [comment]
duplicate of https://github.com/Wynncraft/Issues/issues/3200
Use the **[Directory](https://github.com/Wynncraft/Issues/issues/3197)** to make sure your not making duplicates
