### ISSUE TITLE
Resource 

### ISSUE THREAD

**Issue by bazingashinga** [Wynncraft/Issues#3299]

**Comment by bazingashinga** [comment]
So pretty much I log on, the resource pack loads I pick my class and I get extreme lag ; (0-9 fps) normally I can get 50-150 so I don't understand why the texture pack makes me lag so much. Thank you for reading. :)

**Comment by Verret001** [comment]
Following Info from @meatloaf4311 
If you are using any mod like optifine, Update. I had that issue the other day.
Simple solution is to Restart Minecraft
If that didn't work then try Toggling your internet on/off
If that didn't work then try restarting your computer
If that didn't work then try updating Java
If that didn't work then something is probably broken on Wynncrafts end

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by bazingashinga** [comment]
Thank you for the replies but unfortunately it hasn't been resolved.

**Comment by Trixter313** [comment]
Hmm, well have you tried using Optifine already? It's a mod that usually makes Minecraft run better and lets you customize a bunch of different settings. Here's a link to the mod in case you're interested: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272953-optifine-hd-g9-fps-boost-hd-textures-shaders-and

Other than that I'm not sure what can be done. Could you post a screenshot with the F3 menu up to give us a little more information? Than might help. Thanks!

**Comment by bazingashinga** [comment]
I will post a f3 later but I have optifine, I increased my RAM, I lowered Graphics settings, and I used my other CPU core to help mc but still it freezes

**Comment by Trixter313** [comment]
Do you have any other resource packs enabled in the resource packs screen maybe?

**Comment by bazingashinga** [comment]
No, that's what I find wierd.

**Comment by bazingashinga** [comment]
http://imgur.com/a/SpTbG
The first one is when I move
The second one is when Im not moving at all.
Also Im not using optifine on this profile, it doesnt make a difference.

**Comment by Trixter313** [comment]
To try and find the source, try this resourcepack that I edited to remove all of the 3D models. Everything else is the same. You'll have to select Wynncraft in the server menu and click edit then disable server resourcepacks and enable this one like any other resourcepack. This will at least tell us if maybe it's all of the 3D models causing it.

https://drive.google.com/file/d/0B1ONgNZTFXnwQXcxNlN5RklqXzQ/view?usp=sharing

**Comment by bazingashinga** [comment]
Well, it works, I get decent fps with the minus 3D pack

**Comment by bazingashinga** [comment]
But that doesn't make sense, since I used to play on other servers with custom 3D resource packs and they worked... But now they don't work??

**Comment by Trixter313** [comment]
I agree, it is very strange.

**Comment by bazingashinga** [comment]
It was something with animations so I disabled all animations and Voila! It works!
Thanks to the people who tried to help!

**Comment by Trixter313** [comment]
Huh, weird. Glad to hear your issue is now resolved now though!
