### ISSUE TITLE
Tped to ragni -,-

### ISSUE THREAD

**Issue by vboyswag** [Wynncraft/Issues#3300]
I died while trying to kill an orc in llevigar and I got teleported BACK TO RAGNI!!!
Please either staff give me a scroll back/tp me back or someone please sell me one

**Comment by Verret001** [comment]
By the time some admin were to get on and tp you back you would already be in llevigar

**Comment by vboyswag** [comment]
And If I'm not??????

**Comment by vboyswag** [comment]
I am still in Ragni, Please get me back to Llevigar

**Comment by vboyswag** [comment]
I am back to Llevigar thanks to my friend Keyda
Thanks!
