### ISSUE TITLE
Connection  at the server

### ISSUE THREAD

**Issue by ZekyHD** [Wynncraft/Issues#3301]
Hello guys,
I have a problem i can't join a server and my friend see me all time at lobby 3 but i'm not connected
Please help me.

http://www.noelshack.com/2015-53-1451341468-2015-12-28-23-19-55.png

**Comment by Verret001** [comment]
You may of been hacked, I recommend that you change your account password.
It could also be that the first time you tried to connect you lagged out but was not kicked. 
So when you try to then join the server thinks your already in.

**Comment by Verret001** [comment]
If this has resolved you problem please close the topic, if it has not we would be happy to help.

**Comment by ImSickPT** [comment]
It happened to me too

**Comment by ImSickPT** [comment]
The solution you gave us won't do anything

**Comment by ImSickPT** [comment]
Can't you do /kick ImSickPT, so that I get kicked out of the servers and then I can join again ?

**Comment by Verret001** [comment]
No I told you what I think the server is doing. I said change your password.
