### ISSUE TITLE
Cowfusion Bug

### ISSUE THREAD

**Issue by brcarpy95** [Wynncraft/Issues#3304]
At the end of the quest when you talk to Ranol he will repeat the words that Veekhat had said before you go to the cow.

![screen shot 2015-12-28 at 9 02 13 pm](https://cloud.githubusercontent.com/assets/16392816/12028529/86584910-ada6-11e5-94ab-03b3568d112a.png)

**Comment by slendersir739** [comment]
Email support@wynncraft.com, this is a bug.

**Comment by Huhn360** [comment]
![2016-01-02_13 21 48](https://cloud.githubusercontent.com/assets/11507196/12074428/0ea7001c-b154-11e5-825d-48d0167713d0.png)
i have the same issue and have you reported to support@wynncraft.com ?

**Comment by brainscript** [comment]
@slendersir739 **THIS** is the **issue tracker**. Why should he report it to the **support**?!

**Comment by Huhn360** [comment]
ahh true... :DD that was a normal user :D no mod

**Comment by brainscript** [comment]
@Huhn360 :smile: No problem.

**Comment by Moe-Ronickah** [comment]
Requires fixing by a GM.  A GM has been notified.

**Comment by Moe-Ronickah** [comment]
I think this has been fixed.
