### ISSUE TITLE
my health keeps going down and i don't know why

### ISSUE THREAD

**Issue by assasin49** [Wynncraft/Issues#3306]

**Comment by ThunderRemix** [comment]
This isn't helpful without some more information. If you do not provide any more information, then this issue will be closed in some way or another.

**Comment by slendersir739** [comment]
You have a piece of armor that has negative Health Regen, you have to stop wearing it if you do not want to lose health.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by DarkDemonDragon** [comment]
@assasin49 if you don't respond the staff can't help you.
