### ISSUE TITLE
Bug... Maybe?

### ISSUE THREAD

**Issue by Tristhet** [Wynncraft/Issues#3308]
Hi!, I don't know if its a bug or it the skill points reset scroll work this way, I ASSUME IT'S NOT THE RIGHT WAY, but I don't really know so:
I bought a SPRS to fresh start my archer and I used and it kinda worked, cos I was left with 10-20ish, pont in each skill, and the rest were free to use... (am I explaining it right?)
I really don't want/have LE to buy another Scroll... is there any chance to reset the skill point for real?

**Comment by ThunderRemix** [comment]
Do you have armor or things equiped that change your skill points?

**Comment by Tristhet** [comment]
no, they were put in my inventory when I used the reset scroll.

**Comment by slendersir739** [comment]
Email support@wynncraft.com, this is a bug.

**Comment by timmy14085** [comment]
You could also use a more descriptive title.

**Comment by Trixter313** [comment]
Is the issue still occurring?

**Comment by Trixter313** [comment]
I'll assume the issue is now fixed due to no response and close it but if it isn't, simply reply and I can reopen it for you. Thanks!
