### ISSUE TITLE
After finishing the craftmas chaos quest, my archer still keep the corruption relic shard.

### ISSUE THREAD

**Issue by failtofell** [Wynncraft/Issues#3309]
![2015-12-28_15 08 09](https://cloud.githubusercontent.com/assets/16434017/12030226/24c00430-ae2e-11e5-911a-54a277502217.png)
nickname : Fail_To_fell

**Comment by pewpeed** [comment]
You can get rid of the shard by putting the shard in your 2x2 crafting grid then filling every single slot in your inventory (with emeralds or something) and the shard will magically disappear.
