### ISSUE TITLE
Cant Load Wynncraft Map World

### ISSUE THREAD

**Issue by Hydrophic** [Wynncraft/Issues#3312]
When i open the Wynncraft Map World, it didnt show anything, it only show Wynncraft logo, is it only me or other people cant load too?

**Comment by Trixter313** [comment]
Are you talking about the map here: https://map.wynncraft.com/#/-1583/64/-1636/min/0/0 ?

If so, the map loads fine for me. Maybe you had the wrong link or something?

**Comment by Hydrophic** [comment]
the link you give me is the one i using too, but is nothing for me

**Comment by Trixter313** [comment]
Hmm, that is odd. What browser are you using? I'd suggest making sure your browser is up to date and if you have any extensions or addons to maybe try temporarily disabling them or trying a whole nother browser to at least see if it's a browser specific issue. If none of this works hopefully a more experienced user will come along and know what to do.

**Comment by Hydrophic** [comment]
Can you screen shot the whole map of the Wynncraft for me?cause all the thing you tell me it still cant work for me.

**Comment by Trixter313** [comment]
It's kind of a huge area but I did the best I can do. If you'd still like to try to fix the issue, try pressing the F12 button while on the tab with the map open and click console then take a screenshot of that and upload it here, it might help. Thanks!
![image](https://cloud.githubusercontent.com/assets/7178055/12054383/318f846a-aef1-11e5-816d-79bcae3331fe.png)
