### ISSUE TITLE
Mob's drop their armor but can't be picked up

### ISSUE THREAD

**Issue by Creecreeprs** [Wynncraft/Issues#3313]
At X: 1532 Y: 58 Z: -5147, their are a strange cave with Dwarven Soldier lvl 90 and fire scarab lvl 80 but the drops of the Dwarven Soldier bug. When they drops emeralds, I can take it, but they drops their heads, their chesplates, their pants, their boots and their weapons and this items, I can't take it.
I think that the mobs has not suppose to drop this items but meanwhile, that's make lots of items on the ground ( https://lh5.googleusercontent.com/-A74dF5jyeUY/VoJCtZieb6I/AAAAAAAAADU/FGrXSPQ53Ls/w927-h485-no/2015-12-29_09.18.52.png )

**Comment by Okuupls** [comment]
I've had this issue with a couple other mobs too, I think one of the guards outside Rodoroc did it

**Comment by Creecreeprs** [comment]
Idk, its the first mob like I meet

**Comment by Creecreeprs** [comment]
Little news: The Drarf Miner do the same things with their pickaxe in Dogovi (may be he do that's on the others place to). He died because he fall on the lava.

**Comment by Trixter313** [comment]
Can someone confirm whether this is still occurring or not? Thanks!
