### ISSUE TITLE
Bear Masks

### ISSUE THREAD

**Issue by patrat3121** [Wynncraft/Issues#3314]
Just a short one. Bear masks didn't update to the new item system and are wearable at any level

**Comment by Trixter313** [comment]
Could you post a screenshot of the helmet's stats? Thanks!

**Comment by Trixter313** [comment]
I'll assume the issue is now fixed due to no response and close it but if it isn't, simply reply and I can reopen it for you. Thanks!

**Comment by Trixter313** [comment]
From 3837
![](https://cloud.githubusercontent.com/assets/16863545/12538118/5023a610-c2d1-11e5-911b-d20ce4ee1737.png)

**Comment by Trixter313** [comment]
Are masks bought right now still using the old system or are they updated?

**Comment by Trixter313** [comment]
Ok, got the chance to check and can confirm even new masks have the old style. The merchant just needs to be updated. =)

**Comment by Trixter313** [comment]
Should be fixed, according to https://forums.wynncraft.com/threads/gavel-patch-14-0-9.112397/
