### ISSUE TITLE
Resource pack not loading

### ISSUE THREAD

**Issue by ReyDeLosCreepers** [Wynncraft/Issues#3316]
It always stays has this message
    Downloading Resource pack
      Making Request... 100%

it never gets past that screen, and its not because of my internet.

**Comment by Trixter313** [comment]
What version of Minecraft are you running? Updating to the latest version (1.8.9) might fix this for you.

**Comment by ReyDeLosCreepers** [comment]
I am on version 8.9, i am not sure if this is a bug that multiple people have or is just me

**Comment by Trixter313** [comment]
I believe some others were experiencing it also but many just started working out of nowhere. Are you using any mods or Forge or LiteLoader? I'd suggest trying it with Vanilla Minecraft if so and if it works without them, then it's a mod issue.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by ReyDeLosCreepers** [comment]
I don’t have any mods, i will close the discussion once the problem is fixed though, also i don’t have forge liteloader, is there a downloadable recource pack backup incase it doesn’t work???

**Comment by Trixter313** [comment]
Disabling the server resourcepack and using this one should temporarily fix your issue but I'd suggest still checking every once in awhile to see if the normal server side resourcepack way works because if you do it this way they can't auto update the resourcepack for you if anything gets added or changed.

Here is a link for the resourcepack https://drive.google.com/file/d/0B1ONgNZTFXnwbU9senNwaXJaR3M/view?usp=sharing

**Comment by ReyDeLosCreepers** [comment]
Ok, i will use this only as a temporary solution until this gets fixed, thanks for your help

**Comment by Dorpius** [comment]
I got just the same problem :-/...

Picture of the message:  http://imgur.com/DP1xCUx

**Comment by enderzombie921** [comment]
have the same problem as Dorpius please can a mod fix it\

**Comment by DarkDemonDragon** [comment]
Is this issue still persisting? A minor update broke the pack, but the latest updates fixed it.

**Comment by ReyDeLosCreepers** [comment]
Let me test it. thanks

**Comment by DarkDemonDragon** [comment]
No problem. If your issue is solve please close this unless you have further quests.

**Comment by ReyDeLosCreepers** [comment]
Still not working, though i said before, i will close it when it works

**Comment by Trixter313** [comment]
I don't see any issues in Dorpius's screenshot, that is just the message for when you don't have the server resourcepack enabled.

**Comment by DarkDemonDragon** [comment]
@Trixter313 if you look in the hotbar Dorpius has a slab. This is back when the pack was having issues on the server's side, because you can see that the health and mana is there. 

@Dorpius if you could, please post a new screenshot.

**Comment by Dorpius** [comment]
In meanwhile I'm using the resource pack online for temporary solution (Given by Trixter313)
--> https://drive.google.com/file/d/0B1ONgNZTFXnwbU9senNwaXJaR3M/view?usp=sharing

Hopefully I'm not the only one whit this problem
![wynncraft resource pack problem](https://cloud.githubusercontent.com/assets/16445683/12222227/6efd15ec-b7b6-11e5-838d-48434abf4036.jpg)

**Comment by ReyDeLosCreepers** [comment]
I have it enabled, and it loads forever, i am still using the downloaded version

**Comment by InvisibleAnt** [comment]
The same problem happened with me, all I did was update the mine craft launcher and it worked

**Comment by InvisibleAnt** [comment]
all i need to do now is try and find a way to get the class selector to work

**Comment by ReyDeLosCreepers** [comment]
so updating it will work? i will try this week-end, thanks

**Comment by Dorpius** [comment]
Yup.... InvisibleAnt is right!
I used the old Minecraft launcher... I updated it, it works.

![schermafbeelding 2016-01-18 om 19 24 33](https://cloud.githubusercontent.com/assets/16445683/12399269/3ed349fe-be19-11e5-8352-8208ab58e24b.png)

**Comment by Trixter313** [comment]
Good to hear, if your problem is now resolved @ReyDeLosCreepers , we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by ReyDeLosCreepers** [comment]
ok, i still have the old launcher, let me update it

**Comment by ReyDeLosCreepers** [comment]
got the new version, isn’t working

**Comment by Trixter313** [comment]
Is the official way still not working for you, @ReyDeLosCreepers ?

**Comment by ReyDeLosCreepers** [comment]
unfortunately, still has the same problem

**Comment by Trixter313** [comment]
Okay, it's been 20 days... Is it working correctly for you now? *crosses fingers*

**Comment by ReyDeLosCreepers** [comment]
I am ok now! it is working

**Comment by Trixter313** [comment]
Phwew, thank goodness! Glad to hear =)
