### ISSUE TITLE
Poison not working

### ISSUE THREAD

**Issue by trollunderbridg** [Wynncraft/Issues#3319]
I hop worlds whilst in hive, and I realized my hp wasn't regening, which my poison helps do, I duel my friend and it never worked. The item was a bamboo cuff and a bracer.

**Comment by Trixter313** [comment]
Are you sure you don't have any items on that subtract health regen? They could be subtracting more than they are adding.

**Comment by Trixter313** [comment]
Are you having the same issues as described in https://github.com/Wynncraft/Issues/issues/3225 ?

If so, please close this issue and direct any further comments the the original. Thanks!
