### ISSUE TITLE
Shadow of the beast

### ISSUE THREAD

**Issue by Hayamaka** [Wynncraft/Issues#3324]
i completed the entire quest (shadow of the beast) but when i went back to Dereg i didnt have the toenail. I went back to the npc that gives the toenail but he instructed me to follow footsteps idk wht to do. I looked int my bank too i dont have the toenail for some reason.

**Comment by Troll2828** [comment]
try /fixquests

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
