### ISSUE TITLE
Stuck between barrier blocks on mountains

### ISSUE THREAD

**Issue by merac419** [Wynncraft/Issues#3325]
Hello,
I am just walking around the mountains around "Tower of Amnesia" and see a loot chest at 
-64 112 -458
So I try to teleport there and get stuck in between barrier blocks I think .. why?!

screen: http://imgur.com/VXWbzXM

**Comment by timmy14085** [comment]
Use a TP-Scroll or do /kill

**Comment by Trixter313** [comment]
The unobtainable loot chest has already been reported and as timmy14085 said, you can use /kill with 3+ soul points to get to the nearest visited town. This should fix all of your issues! Have a great day. =)
