### ISSUE TITLE
(BUG) I'm stuck in blocks (FIXED UP)

### ISSUE THREAD

**Issue by TheYusuke** [Wynncraft/Issues#3326]
It was completing the Green Skinned mission and kill the Ogre giving a diamond axe slipped out the door and teleported to a site that I can not leave

![screenshot_20151229132710](https://cloud.githubusercontent.com/assets/16479574/12039257/0b0944ae-ae31-11e5-9d40-ad3bb1733f86.png)

that's how I am right now.

**Comment by SkySaito** [comment]
The penis mission ?
Wat ?

**Comment by TheYusuke** [comment]
ups xDD sorry my mistake the mission is Green Skinned

**Comment by TheYusuke** [comment]
even that has already been fixed the problem got out of the block by repeatedly put on and take command /class

**Comment by SkySaito** [comment]
Well if you have no more problem, close the issue, it would be appreciated

**Comment by SkySaito** [comment]
o3o

**Comment by SkySaito** [comment]
This Penis mission tho xD

**Comment by timmy14085** [comment]
Use a TP-Scroll or /kill m8

**Comment by Trixter313** [comment]
I believe you issue is now fixed. Have a great day!
