### ISSUE TITLE
Ring sprite before identifying.

### ISSUE THREAD

**Issue by RagingPat** [Wynncraft/Issues#3327]
Today I finished the Memory Paranoia quest. After this quest I recieve a ring called "Ring of generosity".

If I were to place this ring in one of my ring slots, the sprite of the ring appears, but it remains unidentified.

**Comment by TrashcanMan** [comment]
That's intended, you have to identify it first. All quest items are now unidentified when given. Please hit the "Close Issue" button below. Thanks!

**Comment by RagingPat** [comment]
I'm sorry, I don't think I gave enough details.

So I received the ring, it was unidentified (intended). Unidentified ring is just a normal golden ring. I placed the unidentified ring in my ring slot, it remained unidentified, but the ring changed sprite to as it is identified. 

So it went from a golden ring -> golden ring with blue gemstone

**Comment by DarkDemonDragon** [comment]
I don't think this is a serious issue as there's a thing where players can drop UnIded items to also obtain this effect.

**Comment by Moe-Ronickah** [comment]
There is no way to link this to #3318, but my best guess is that it is the same effect.

**Comment by Moe-Ronickah** [comment]
I can now confirm that this is a dupe of #3318 .
