### ISSUE TITLE
Jungle Fever and normal LE

### ISSUE THREAD

**Issue by Capelinha** [Wynncraft/Issues#3328]
I did the mission Jungle Fever with two normal LE in inventory now I have two useless LE.  IGN: NIkoni

![screenshot_5](https://cloud.githubusercontent.com/assets/10324664/12041534/6e490266-ae59-11e5-9dac-ca3b02b9b144.png)

**Comment by Forcellrus** [comment]
That's because you shall recieved 64 Almuj's Liquified Emeralds by Almuj's banker after you did the maze (If you even did it). If not, this is what you got.

**Comment by HeyloLP** [comment]
sorry but even the wiki says that you need to be careful and now nobody from the team will give you your le back because of the strict no refund policy

**Comment by Trixter313** [comment]
You can get rid of the useless LE by filling your inventory and dropping them while standing on an item.
