### ISSUE TITLE
Shadow of the beast

### ISSUE THREAD

**Issue by Capelinha** [Wynncraft/Issues#3329]
I did everything the mission Shadow of the beast sent and when I came to speak to the Dereg with the item dropped by the beast I can not complete the mission and he tells me to follow the new blood.  IGN: NIkoni

![screenshot_6](https://cloud.githubusercontent.com/assets/10324664/12041586/d90ac008-ae59-11e5-8146-77823d083358.png)

**Comment by Monkeysz** [comment]
U have to give all of the three evidences to Dereg. Do /fixquests otherwise.
