### ISSUE TITLE
Bob's Reincarnation not give XP

### ISSUE THREAD

**Issue by Capelinha** [Wynncraft/Issues#3330]
I finished the mission Bob's Reincarnation, won the Corrupted Treasure but did not show any messages in chat and I did not get any XP and continue at level 74. IGN: NIkoni

![screenshot_7](https://cloud.githubusercontent.com/assets/10324664/12041652/658bc982-ae5a-11e5-8c68-76c2269959fa.png)

**Comment by Trixter313** [comment]
Are you in a guild? It's possible that you have it set to give all or most of your XP to your guild. You can make sure you aren't by doing "/guild xp 0". Wynncraft has a strict no refunds policy so the missed XP can't be refunded, unfortunately. Hopefully this doesn't happen again!
