### ISSUE TITLE
An Issue with Lazarus Pit

### ISSUE THREAD

**Issue by CraftLord951123** [Wynncraft/Issues#3332]
Hello, i am trying to do the quest Lazarus Pit. I have gotten the Rotten Skin and attempting to return the skins to Vesdar. When I try the button combinations(which I have written down), nothing happens. the background of the buttons don't turn to gold and after the pair is made it isn't made the color(like green for example). I have logged off the servers, waited a few hours came back and it is still not working. I have also tried doing it on many different servers and it is still not working. Please help. Thanks.

**Comment by CraftLord951123** [comment]
Well, it seems to be working now.

**Comment by Trixter313** [comment]
Great to hear!
