### ISSUE TITLE
The Shadow of the Beast glitch

### ISSUE THREAD

**Issue by patatepower** [Wynncraft/Issues#3336]
Hie everyone I have a bug for the Shadow of the Beast quest.
I spoke to Tolem and he gave me the Stinge Hair so now he say me that
![2015-12-30_00 01 04](https://cloud.githubusercontent.com/assets/16481875/12043942/5e80543e-ae8a-11e5-8be8-39e903089301.png)
After I spoke to Kroac and he gave me his object I don't remember what it was and now he say me that
![2015-12-30_00 04 27](https://cloud.githubusercontent.com/assets/16481875/12043997/e44125ee-ae8a-11e5-86b6-ee9726a3f960.png)
After I spoke to the last guys Rileen and he said me where the beast is hiding so now he say me that
![2015-12-30_00 19 40](https://cloud.githubusercontent.com/assets/16481875/12044038/72c7a626-ae8b-11e5-8326-9a766b626beb.png)
And my quest is that 
![2015-12-30_00 22 58](https://cloud.githubusercontent.com/assets/16481875/12044041/7e4e757e-ae8b-11e5-8082-0c31f8ad2bee.png)
So I go to dereg but he say me that 

![2015-12-30_00 00 11](https://cloud.githubusercontent.com/assets/16481875/12044049/9526b1e4-ae8b-11e5-90fc-30f89bee9ca5.png)
He take me hair, the object of Kroac and the Piece of Big Foot but nothing happened and I still have to speak to Dereg with 3 pieces of evidence.
Plis help :(
first of all sorry for my bad english :)

**Comment by Trixter313** [comment]
Have you tried the command /fixquests
It might help.

**Comment by patatepower** [comment]
Thx alot :)
