### ISSUE TITLE
Tower of Ascension Mage bug

### ISSUE THREAD

**Issue by kirby5098** [Wynncraft/Issues#3337]
Whenever I am in Tower of Ascension with my Mage, I notice how the server crashes. I realized that this occurs whenever I cast the meteor spell. This is a huge issue because, without Meteor, Mage can't beat the Tower of Ascension. Hopefully, you can patch this issue so that Mages, such as myself, may be able to complete the Tower

**Comment by TrashcanMan** [comment]
Was it just once or twice, or is it happening constantly?

**Comment by essem2** [comment]
Can confirm that the server start a lag when you use meteor in tower of ascension...

**Comment by HeyloLP** [comment]
it happens every time and this su***

**Comment by kirby5098** [comment]
It happens every time. It's EXTREMELY annoying. It crashes the whole server

**Comment by starwars1139** [comment]
this has been happening to me too, and it has happened more than twice.

**Comment by kirby5098** [comment]
So, is there any way to possibly fix this?

**Comment by ImSickPT** [comment]
@starwars1139 @HeyloLP @essem2 @kirby5098 when I cast the meteor spell in TOA, it doesn't lag the server though.

**Comment by HeyloLP** [comment]
@ImSickPT greetings then you got luck but it's pretty anoying

**Comment by jensiwaa** [comment]
I completed ToA yesterday as mage. I couldn't use meteor the whole time because everybody in my party would get lag (possibly the whole server). So this is still a problem.

**Comment by Trixter313** [comment]
Is this still happening since the server downtime?

**Comment by Trixter313** [comment]
Due to 20 days without a response I'm assuming the issue is now resolved. If not, simply comment and I can reopen. Thanks!
