### ISSUE TITLE
assassin skills

### ISSUE THREAD

**Issue by Lunarhelix** [Wynncraft/Issues#3340]
basically all assassin skills aren't doing what they are supposed to except vanish

1)  smoke bomb does no damage
2)spin attack hits enemy but doesn't stun them, it makes them go wild like multihit lvl 2 before the update
3) multihit doesn't make them go wild like before, and i'm not lvl 56 to have force yet, 

all of these hasn't happened before the gavel update. PLEASE FIX or any suggestions as to how to fix, 

ign: Lunarhelix
assassin lvl : 52

**Comment by essem2** [comment]
1) Can confirm
2) when i use spin attack i get stun and cant move for a moment
3) i cant control them like before gavel
Assasin Lv. 93

**Comment by Trixter313** [comment]
1 & 3 are fixed now, and 2 has been reported in a previous issue. =)
