### ISSUE TITLE
I lost Horses please help I need them back !

### ISSUE THREAD

**Issue by JuniorTheGhost** [Wynncraft/Issues#3341]
I just completed the stable story and I was using my horse leveling it up and then went back to detlas and that was when I opened my inventory shift clicked my saddle to the top and it disappeared from my inventory.Please help.

**Comment by Monkeysz** [comment]
Sorry but Wynncraft has a strict no refund policy, Good luck.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
