### ISSUE TITLE
Wynncraft Excavation Site D Broken?

### ISSUE THREAD

**Issue by MDBL** [Wynncraft/Issues#3342]
the king has no dialogue therefore i cannot update my quest book and/or pass the "investigate the catacombs" part of the quest!

screenshot proof: https://gyazo.com/0f5d35cdb4a11333f1ddaa63efce5aeb

**Comment by Monkeysz** [comment]
Do /fixquests.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
