### ISSUE TITLE
Murder mistery bug

### ISSUE THREAD

**Issue by salimaduen** [Wynncraft/Issues#3344]
I was doing today the quest "Murder Mistery" with my archer I followed every step and now I have to talk to Captain Lorias to claim my reward (That's what the book says) And nothing happens he is saying the same thing that he said at the begining of the quest.

**Comment by Troll2828** [comment]
maybe  try bringing him the axe in the murderers house

**Comment by Trixter313** [comment]
Did Troll2828's suggestion fix your issue? If so, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
