### ISSUE TITLE
Bob

### ISSUE THREAD

**Issue by wynncraftlupascu** [Wynncraft/Issues#3345]
it regens so fast and dose not take any damage with 4 ppl
![2015-12-30_10 57 12](https://cloud.githubusercontent.com/assets/14152318/12048481/4cb5bd0c-aee4-11e5-9372-5352fdf0f33d.png)
![2015-12-30_10 57 09](https://cloud.githubusercontent.com/assets/14152318/12048483/51375516-aee4-11e5-9bc0-4b393adc0352.png)
![2015-12-30_10 57 07](https://cloud.githubusercontent.com/assets/14152318/12048486/5483fe9a-aee4-11e5-821a-67a963273b88.png)

**Comment by Troll2828** [comment]
try using weapons that deal neutral damage since he is immune to all elements

**Comment by Trixter313** [comment]
Use troll's advice.
