### ISSUE TITLE
Reclaiming the house

### ISSUE THREAD

**Issue by IceNinjaCreeper** [Wynncraft/Issues#3347]
Upon completing this quest it didn't give me the rewards that it said that it gave me in chat please fix this so others do not need to go though this as its gives a good amount of emeralds.
if its possable can i have what i was owed from finishing the quest it gave me the exp just not the emeralds
http://prntscr.com/9k99ch <---- Quest chat when finished
http://prntscr.com/9k9b06 <---- inventory 
Thanks
IceNinjaCreeper

**Comment by Trixter313** [comment]
Quests don't give emeralds a lot of the time if you already have emeralds in your inventory so as a precautionary measure for future quests, make sure you don't have any emeralds in your inventory at the moment you receive your reward. Unfortunately Wynncraft has a very strict no refund policy so not much can be done about the already lost emeralds.
