### ISSUE TITLE
Legendary boots dropped due to a huge lag...

### ISSUE THREAD

**Issue by Necroflammes** [Wynncraft/Issues#3348]
Hello moderators,

5 minutes until the enormous lag, I just bought my new legendary boots lvl 60 : "Bad Wolf" for 1 liquified emerauld and 20 emerauld blocks. In other words, all my fortune...

Then, 5 minutes later at 12h40 GTM, the enormous lag happened and my stuff dropped on the ground... and it disconnected myself because my minecraft totally crashed.

I couldn't reconnect in the 5 next minutes because the server was full so when I reconnected after 8 minutes , the boots have been dispawned...

Could you please give me them because this is really not my faute :'(

Thanks you for your attention.

PS : My nickname ingame is : Necro_flammes

**Comment by Trixter313** [comment]
How did the item drop on the ground? I've never seen lag that drops people's items on the ground. Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!

**Comment by Necroflammes** [comment]
I wanted to replace my old boots by the new ones and when i took the new boots in my inventory, I couldn't replace them by the olders ones and the item desappeared...
Please I'll have to leave the server because this ruined my gaming experience :'(

**Comment by Trixter313** [comment]
Like I said, there's really nothing we can do. I suggest asking around and some nice player might give you some pretty good boots. We'd appreciate it if you closed this issue. Thanks!
