### ISSUE TITLE
Bug loot dungo spider

### ISSUE THREAD

**Issue by Foxrim** [Wynncraft/Issues#3350]
Apres avoir batue l'araignée et que je me suis fait téléporter à l'entrée, un block dans le sol et j'ai obtenue l’exp, mais pas la "animal Key" et les "9 falling emeralds", je suis persuadé que c'ets un bug car au donjon précédent cela ne me l'avais pas fait. 

Merci d'avance (Foxrim)
![2015-12-30_16 21 33](https://cloud.githubusercontent.com/assets/16490764/12052793/cf2a3226-af12-11e5-9ed4-95706c2ea3ad.png)

**Comment by Trixter313** [comment]
Dupliquer des https://github.com/Wynncraft/Issues/issues/3276

S'il vous plaît se référer des commentaires à venir à la question initiale. Merci!

Duplicate of https://github.com/Wynncraft/Issues/issues/3276

Please refer any future comments to the original issue. Thanks!
