### ISSUE TITLE
wynncraft wynnexcavation Site A another bug

### ISSUE THREAD

**Issue by SioN-wynncraft** [Wynncraft/Issues#3351]
![2015-12-30_17 46 11](https://cloud.githubusercontent.com/assets/16464117/12053073/1ac005ac-af1e-11e5-85b2-5bb9d10400de.png)
Here The foto can tell you everything have the crytal and I talked to tesha and she says that I should give the tablet to wade guy

**Comment by Trixter313** [comment]
Have you tried using the command /fixquests

**Comment by BudderBiscuit** [comment]
I had the same bug on my Archer, and no, /fixquests didn't work.

Had to reset ;(

**Comment by SioN-wynncraft** [comment]
yes but the problem is diffrent. vade says to give it to tesha but tesha says to give it to vade and when I talk to vade he again says to give it to tesha and I already killed the pharoh
![2015-12-31_07 06 17](https://cloud.githubusercontent.com/assets/16464117/12061382/293eae8e-af8d-11e5-8757-46a42efe1a04.png)

**Comment by BudderBiscuit** [comment]
No, that's the exact same thing that happened on my Archer. My OCD triggered so I reset it because I couldn't complete the quest.

**Comment by SioN-wynncraft** [comment]
İs there a way to reset quests?

**Comment by Trixter313** [comment]
@SioN-wynncraft no, there isn't currently a way to reset quests. This looks like it will need admin intervention to be fixed.

**Comment by SioN-wynncraft** [comment]
Ok thanks for saying

**Comment by Moe-Ronickah** [comment]
Requires an admin.

**Comment by Moe-Ronickah** [comment]
OK, we need to know what happened prior to your getting caught in this loop, if you can remember it, at all.  We need to know what triggered the loop in order to fix it.

**Comment by Lazzuu** [comment]
Same problem with me

**Comment by Moe-Ronickah** [comment]
@SioN-wynncraft ,  if this is still alive, try /fixquests, please.  It seems to be fixing this Site A bug.

**Comment by koohikoo** [comment]
I'm not sure if this is the right place but I am having the exact same issue

**Comment by Moe-Ronickah** [comment]
@koohikoo , OK, we need to know what happened prior to your getting caught in this loop, if you can remember it, at all. We need to know what triggered the loop in order to fix it.

**Comment by koohikoo** [comment]
leaving the boss room

**Comment by BlitzAsogi** [comment]
Having the same issue here

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
