### ISSUE TITLE
GET RID OF THE GUILD MASTER (NOT A LIE OR ANYTHING TO GET FREE LE)

### ISSUE THREAD

**Issue by KevinW825** [Wynncraft/Issues#3356]
"wynncraft doesn't replace lost items"
GET RID OF THE GUILD MASTER THEN
What I want fixed
---------------
I don't want my Le to be replaced, I see the policy of "Wynncraft doesn't replace lost or missing items" so all I want is that guild master to be removed and AT LEAST WARN PEOPLE THAT THE SERVER WAS GOING TO LET PEOPLE LEAVE AT SAME TIME, This was not a server restart too

What was the biggest effect
---------------------------
19 Le were missing in total for me
Explanation what happened:
----------------------------------
"Use characters A-Z to make a guild"
Inserting back LE in echest
A sign menu opens up
Server kicks me, tons of leaving people shown
THEN THIS HAPPENS
---------------------------------
![2015-12-30_12 03 40](https://cloud.githubusercontent.com/assets/16431360/12054924/71dd9128-aeed-11e5-9ea7-dbf424a7a986.png)
I SOLD THIS GUY TO SHOW HOW ELSE I GET THE LE
---------------------------------
![2015-12-30_10 45 02](https://cloud.githubusercontent.com/assets/16431360/12054946/b3037be0-aeed-11e5-8e45-745b8c54c1d8.png)
MY ECHEST AND QUESTS DONE
--------------------
![2015-12-30_11 49 07](https://cloud.githubusercontent.com/assets/16431360/12054780/e4539c7c-aeeb-11e5-8330-50a9e8a4d3a1.png)
![2015-12-30_11 45 44](https://cloud.githubusercontent.com/assets/16431360/12054782/ea6ad288-aeeb-11e5-9cb0-8b0bc17c2d4f.png)
GET RID OF GUILD MASTER
--------------------------------------------------------
![2015-12-30_11 47 06](https://cloud.githubusercontent.com/assets/16431360/12054783/eff82ce6-aeeb-11e5-875f-b74844c070af.png)

**Comment by BudderBiscuit** [comment]
Um ...what?

**Comment by superabel123** [comment]
Sry to say this but you have to be more clear with your screenshot descriptions because it is very hard to understand and I myself can't fully understand what you are talking about
all I know is that echest means enderchest but I don't know what u mean by
GET RID OF GUILD MASTER and what does the quest completion
percentage got to do with the problem here?

**Comment by Trixter313** [comment]
Unfortunately we can't do anything about items lost due to server restarts or crashes. The servers are much more stable now and shouldn't crash unexpectedly anymore, only for scheduled restarts.
