### ISSUE TITLE
Corrupter of Worlds - immortal

### ISSUE THREAD

**Issue by Forcellrus** [Wynncraft/Issues#3357]
I was killing Corrupter of World with 3 more people, we mostly had air amage weapons but his HP was regenerating too fast, he had 100k in total. We could barely reach 90k of his health and then he could just regen back to 100k. I bet 10x level 100 players can't kill him now. This must be some bug, he is regenrating back to 100k HP every like 30 seconds. We spent 15 mins of fighting with him and then we just gave up this endless fight. Please fix him, Amadel and Bob together are easier to kill now than CoW.

**Comment by happyquake0422** [comment]
We were level 68-70, and we were using relatively good gear. There were 4 of us in total, all wailing on him as hard as possible. Nothing would even dent his HP that he wouldn't regen but a minute later. I'm not sure if the timing intervals on his heals are too short or if there's an extra 0 in his regen amount, but I don't think it's supposed to be quite this difficult for a level 68 quest.

**Comment by Forcellrus** [comment]
Exact thing happened to us.

**Comment by shacharss** [comment]
i tried doing it alone, didnt  really do me any good :P. however he was immune to my meteor spell and thats all my damage!! too hard

**Comment by sinomsinom** [comment]
I solod him yesterday and i was only level 69 so he is beatable bob's reincarnation ib bugged.

**Comment by Forcellrus** [comment]
I killed him after I bought Maelstrom, looks like he doesn't like air element.
