### ISSUE TITLE
Shadow of the Beast not updating

### ISSUE THREAD

**Issue by ntuttle11** [Wynncraft/Issues#3359]
I'm trying to complete this quest. I've made it all the way to Bigfoot's cave, killed him, and have all the items, but my quest book is still telling me to go deeper in the cave. I've tried to talk to Dereg (I think, whoever you need to start the quest, I forgot :P), but he just asks for the items when they're in my inventory.

**Comment by Forcellrus** [comment]
Same bug happened to me, just simply go from the beggining of the cave to the boss, book should update.

**Comment by ntuttle11** [comment]
Thanks, that seemed to have worked, I think it happened because the server was laggy.
