### ISSUE TITLE
Respawn Glitch in "A Fighting Species"

### ISSUE THREAD

**Issue by TheGreatPiggy** [Wynncraft/Issues#3362]
So I was doing the quest "A Fighting Species". I got down to the caves with my helmet on, but as soon as I saw in chat that they smelled human and the Orcs were hostile, I switched the Orc Mask for my regular helmet, as it has better stats. I fought through the Orcs, continued down the cave, and got to Gurg's (or whatever his name was) room. I beat him, and went out the portal. As soon as I did so, I got the message that presumably appears if you didn't have the Orc Mask on (the Orcs say for you to get out), and I was teleported to a room with redstone, one of the wiring for the 3x3 doors.
![2015-12-30_13 43 32](https://cloud.githubusercontent.com/assets/16493104/12056595/b4e7b592-aefd-11e5-915b-460917e141d1.png)
I looked around but it was a rather small area with no exits so I typed in /die to escape. Once I did so, I found myself in the caravan that you spawn in when starting a new character, all the way back into the Wynn province.
![2015-12-30_13 49 55](https://cloud.githubusercontent.com/assets/16493104/12056612/eb3a8674-aefd-11e5-8718-07c7e108175f.png)
I haven't tried replicating this glitch (nor will I ever want to) but it is probably possible by doing what I did.

**Comment by TrashcanMan** [comment]
I've seen this happen in Green Skinned Trouble as well if you die in the boss room. I believe the problem here is that some rooms are located outside the map, mostly near the Ragni area, so when you die in any of them you respawn at the spawn.

**Comment by DarkDemonDragon** [comment]
This exact thing happened to me and I assumed it was due to lag, but @TrashcanMan 's explanation is most likely what happened. Simply use a scroll or go through Ragni Outskirts again to return to the main map.

**Comment by Trixter313** [comment]
Consolidated into https://github.com/Wynncraft/Issues/issues/3617

Please direct any future comments to this thread. Thanks!
