### ISSUE TITLE
Thieving Rodents

### ISSUE THREAD

**Issue by OneMon** [Wynncraft/Issues#3364]
Hi, I have an issue with quest Thieving Rodents, I had already got the key and put it in the preparation of the quest, but the quest is still shown in the book quests and NPC are still begging me this ring, what to I must do?

**Comment by Troll2828** [comment]
You have to go in the cave and get the real ring. So basically you give the guy two rings.

**Comment by OneMon** [comment]
But I can`t understand what cave must I go?
