### ISSUE TITLE
Archers can break flower pots with arrows, and can sometimes gain emeralds from them. 

### ISSUE THREAD

**Issue by Mythbustman** [Wynncraft/Issues#3365]
If an archer uses any of their spells, it will break a flower pot that the spell is being aimed at. Also, they will sometimes drop emeralds because of the loot chance.

**Comment by Trixter313** [comment]
Flower pots are intended to be able to be broken and sometimes drop loot. =)

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
