### ISSUE TITLE
Qira Hive Water Level Floor 9 only dropping Floor 8 Catalysts 

### ISSUE THREAD

**Issue by ShadowgunMC** [Wynncraft/Issues#3366]
I am killing the mobs on Floor 9 for the Water Catalysts and they're dropping Floor 8's not 9

**Comment by Trixter313** [comment]
Have you tried switching to a different world?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by ShadowgunMC** [comment]
I have tried switching, I was able to just walk through to the next floor, however. I think they are still dropping 8's though

**Comment by Trixter313** [comment]
I believe the issue has been fixed. If anyone has found evidence of otherwise, please comment below and I'll reopen the issue. Thanks!
