### ISSUE TITLE
Quest bug. (Murder Mystery)

### ISSUE THREAD

**Issue by CatalystSurvival** [Wynncraft/Issues#3368]
https://i.gyazo.com/8ae75bcfdf05f8d495786ffc2fc8feeb.png
That image should explain it doesn't let me finish the quest i finished it on assassin but its not letting me with Mage...

**Comment by Troll2828** [comment]
maybe try to "redo" the quest by doing everything necessary to complete it. For example: Go in the sewers, take the weapon from the killer's house. I think your problem was caused by lag. Hope this helps.

**Comment by CatalystSurvival** [comment]
wait you need to get a wepon of the killers... i didn't remember doing that on assassin so since my quest book said just talk to captain maybe it was a bug and that i tried /fixquests but nothing so i gotta get the killer's weapon xD woops maybe fix the info given on the book to find the killers weapon on their things ?

**Comment by Troll2828** [comment]
The killer kind of hints it he says: don't do in my things to find proof or something so I jut checked and found it in his bedroom.
