### ISSUE TITLE
/fixquests is buggy.

### ISSUE THREAD

**Issue by TheDerpyMan** [Wynncraft/Issues#3371]
I don't know what starts the bug, but I'm gonna tell you my circumstances.

Lvl 80, I have finished all quests in Wynn except Haven Antiquity. If I use /fixquests I get 2 Yellow Crystal Shards and 2 Purple Crystal Shards (I finished the Wynnexcavation quests), If I use /fixquests again I get only 2 Purple Crystal Shards. If I continue, I can get unlimited (Purple) Crystal shards.

**Comment by Forcellrus** [comment]
Same thing here

**Comment by superabel123** [comment]
Errrrr it happened to me too,
/fixquests doesn't actually work and actually gives you more purple crystal shards instead

**Comment by Equipa2** [comment]
It happened to me too but i want get back my baab´s wool for the bob´s battle but it only give purple crystals

**Comment by HeyloLP** [comment]
@Equipa2 baab's wool is untradeable not a quest item so go back to maro peaks and kill him again

**Comment by DarkDemonDragon** [comment]
As @HeyloLP certain quest related items aren't tagged as "Quest Items". While they may be unTradeable, if you can drop an item normally like a non-quest item then it will NOT be returned to you if you do /fixquests.

**Comment by ImSickPT** [comment]
@DarkDemonDragon 1st - Once I ate my corrupted potato and the /fixquests command gave it back to me. 
2nd - Quest Items are marked as Quest Items and they are not droppable. 
3rd - Baab's Wool is an untradeable and cannot be given to you by the /fixquests command.

**Comment by HeyloLP** [comment]
@ImSickPT 
i'd like to add that baab's wool a mob drop is and so you could get infinite baab's wool so of you lost it go back to his cave and kill him again

**Comment by ImSickPT** [comment]
I was not able to understand you. Please try again.

**Comment by DarkDemonDragon** [comment]
@ImSickPT that's exactly my point.

**Comment by ImSickPT** [comment]
@DarkDemonDragon sorry, i misunderstood

**Comment by HeyloLP** [comment]
@ImSickPT  Baab's wool isn't a quest item just a mob drop

**Comment by ImSickPT** [comment]
@HeyloLP really? I already knew that -.-

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3311

Please direct any future comments to the original thread. Thanks!
