### ISSUE TITLE
Guild commands not working

### ISSUE THREAD

**Issue by England-F** [Wynncraft/Issues#3373]
For a few days, since Gavel came out our guild commands have been broken. Whenever someone does /guild leaderboard or /guild stats, it does not work. When we try these commands it appears if we didn't even type it. No error message or anything. We type it, and i guess the server does not even see we type anything.

**Comment by TGNebulA** [comment]
worse yet: you cant even make a guild!

**Comment by Trixter313** [comment]
Are you still experiencing this issue? A recent patch fixed some guild issues and hopefully this was one of the fixed ones. Let me know!
