### ISSUE TITLE
TOA crashes world

### ISSUE THREAD

**Issue by RaymondZGames** [Wynncraft/Issues#3377]
every time me and my friends do toa the world starts to lag, then it crashes

**Comment by kirby5098** [comment]
I wrote a bug report on this too. The issue is that, if you cast meteor, the Wynncraft server crashes.

**Comment by RaymondZGames** [comment]
oh

**Comment by ImSickPT** [comment]
@kirby5098 cast the meteor where ? in TOA ?

**Comment by DarkDemonDragon** [comment]
@RaymondZGames please close this as this is a duplicate as mentioned above.
