### ISSUE TITLE
"Finding The Light" Issue

### ISSUE THREAD

**Issue by CiPCheech** [Wynncraft/Issues#3379]
I was trying to talk to the Guardian of The Light forest but it says I need a Taproot to wake him up I have the taproot quest item in my inventory and it keeps saying I need the taproot to wake him up. Am I doing something wrong? Please help.

**Comment by Monkeysz** [comment]
You also need to find a sheep in the forest that is colored yellow. Kill it and you shall obtain a item called the Zoat Goat Horn. Just find it in the forest. It spawns randomly. Good Luck.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
