### ISSUE TITLE
skill points shuffled and re distributed

### ISSUE THREAD

**Issue by fweston** [Wynncraft/Issues#3383]
I have 30 strength. I die, look at my inventory and my chest plate has popped into my inventory. I check the chest plate and it says I do not have 30 strength. I check my strength and all my skill points have been changed. This has happened five times now. Not really sure what is going on but it is hard to use my weapons and armor if I cant specialize around a certain skill.

**Comment by BudderBiscuit** [comment]
Um, your armor or weapons may be modifying your skill points. Take all your armor off and then check again. The attributes will have a "This skill was modified by your equipment" or something like that if it is changed.

**Comment by fweston** [comment]
ok thank you.
