### ISSUE TITLE
Temple of Legends Quest Issue

### ISSUE THREAD

**Issue by BattlingApollo** [Wynncraft/Issues#3385]
When I try to show the 64 Blaze Powder/Leather/Rotten Flesh to Garull, it didn't work. I think it's because my Rotten Flesh was from a long while back, and doesn't have the "Junk Item" tag.

https://i.imgur.com/E2evsSK.png

**Comment by ImSickPT** [comment]
what is the mod u have to show the fps and stuff in the upper left corner ?

**Comment by superabel123** [comment]
I too have faced this issue

**Comment by BattlingApollo** [comment]
It's OptiFine, there's an option somewhere in the settings that says "Show FPS:"

**Comment by HeyloLP** [comment]
yes it's because vanilla items aren't acceptable any more

**Comment by Trixter313** [comment]
Yeah, old items won't work anymore so you simply have to get the new type of item and it should work. If not, let us know!
