### ISSUE TITLE
Finding the Light Quest Error

### ISSUE THREAD

**Issue by Brightscales** [Wynncraft/Issues#3386]
I was going to start Finding the Light Quest and I found out I couldn't because I was missing Taproot but I've finished that quest already. It won't let me give the Taproot to the Forest Guardian. 

Here's a pic.
http://imgur.com/TyPOfoE

**Comment by essem2** [comment]
"and something to wake him up" you need the "Volt Goat Horn" to wake him up too

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
