### ISSUE TITLE
Random wool block in a plain

### ISSUE THREAD

**Issue by Creecreeprs** [Wynncraft/Issues#3387]
At 870 45 -5334 their a white wool block and I think he's not supposed to be here ^^

**Comment by superabel123** [comment]
It could be intentionally placed or simply a misplacing
Either way I feel that it's a minor issue

**Comment by Trixter313** [comment]
Could you post a screenshot? That would be great, thank you!

**Comment by Dar-krusos** [comment]
It"s art.

**Comment by DarkDemonDragon** [comment]
Has this been confirmed yet?

**Comment by Moe-Ronickah** [comment]
Fixed.
