### ISSUE TITLE
Stuck in a black room

### ISSUE THREAD

**Issue by yorimtschgi** [Wynncraft/Issues#3391]
Me again 😁 This time I killed the orc leader but as I wanted to tp out at the black area at the end of the room I got teleported to a black room, I cant use teleportation scrolls neither

**Comment by superabel123** [comment]
do /kill

**Comment by yorimtschgi** [comment]
Tyvm

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
