### ISSUE TITLE
Quest "WynnExcavation Site A" bugged

### ISSUE THREAD

**Issue by yairkaraso** [Wynncraft/Issues#3392]
![2015-12-31_15 50 04](https://cloud.githubusercontent.com/assets/16417060/12064876/4f611266-afd6-11e5-9e4a-f010ae2392d8.png)
![2015-12-31_15 49 59](https://cloud.githubusercontent.com/assets/16417060/12064878/50b3b54c-afd6-11e5-9fe6-5f83dba6babd.png)
![2015-12-31_15 49 48](https://cloud.githubusercontent.com/assets/16417060/12064879/518c7dfa-afd6-11e5-9ada-d34b5093ba0a.png)
![2015-12-31_15 49 25](https://cloud.githubusercontent.com/assets/16417060/12064880/525efa1e-afd6-11e5-90b8-d8a61f251a36.png)

**Comment by KillaSnow** [comment]
Same issue here as well.... I can back to the quest a while later, about a day, and that happened to me..
