### ISSUE TITLE
Baab's health regeneration is bugged!

### ISSUE THREAD

**Issue by ImSickPT** [Wynncraft/Issues#3393]
When I spoke to a GM in the forums, he said that Baab's health regeneration is 1250 but if you go to Maro Peeks you will see that Baab's health regeneration is 5000+. I hope you fix this bug since I want to do the Reincarnation quest.

**Comment by Trixter313** [comment]
It could have changed in the Gavel update or the GM simply could have been mistaken. I don't believe this is enough proof to prove this as a bug but thanks for posting!
