### ISSUE TITLE
Green Skinned Trouble Quest Bug

### ISSUE THREAD

**Issue by tttre** [Wynncraft/Issues#3397]
When I'm in the cavern, I complete puzzle but when I fall in the hole in the floor, they tp me back and say me "null"

**Comment by Trixter313** [comment]
Are you still having this issue?

**Comment by Dar-krusos** [comment]
I think you must have missed part of the quest, such as a Quest Update/Dialogue or the tp was simply not working.

**Comment by Dar-krusos** [comment]
This is also a duplicate of Issue #3339
