### ISSUE TITLE
inventory wipe???

### ISSUE THREAD

**Issue by FmgOnline** [Wynncraft/Issues#3398]
just logged in after lunch and my inventory was empty i had loads of stuff including a black horse 17 eb full gold armor and a legendary smasher warrior weapon and a pair of alumj walker its got nothing to do with update i have logged in since then and i wasnt afk i was in deltas bank when i left and i switched my computer off so please can some one give me my items back and this is my fav server in mc and i need my items back

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. I wish I could help out. We'd appreciate it if you closed this issue. Thanks!

**Comment by FmgOnline** [comment]
do you have any idea why this happened because i have spent hours and hour on wynncraft and i really think i Should get a refund because it wasnt my fault that it got wiped it was wynncraft's so i still think i should get my stuff back

**Comment by Trixter313** [comment]
There are many possible reasons, the most likely one, even though you're pretty sure it wasn't, is that somehow you died with less than 3 soul points. Other than that, someone could have possibly been on your account and accidentally died, or it could have just been the server glitching but it's extremely rare that an entire inventory is wiped from a server glitch so I doubt that was what happened. We can only speculate what happened.

**Comment by FmgOnline** [comment]
so can u have my stuff back i was on 8 soul points when i logged off and when i logged in i had nothing Please will u be able to give them back it taken forever to get my items and i dont want to have nothing

Thanks

**Comment by Trixter313** [comment]
There's nothing I personally can do, unfortunately. Wynncraft sticks by it's no refund policy very strongly. I suggest asking around and maybe some nice players will give you some of their items.

**Comment by FmgOnline** [comment]
is there any one you or i can speak to to get my items back

**Comment by Trixter313** [comment]
I don't believe so. In the ~3 years of Wynncraft running, they haven't broken the EXTREMELY strict no refunds policy, ever. Hopefully this isn't too much of a disappointment! Good luck!
