### ISSUE TITLE
Beyond The Grave Bug

### ISSUE THREAD

**Issue by PoisonedPotato** [Wynncraft/Issues#3403]
After you are killed and you talk to Death, your questbook will say "Leave Deaths Realm". When you do the puzzle it says something like "From the back of the mansion glass breaks" When you go to the back there is no glass, there is just a barrier blocking you from leaving.

**Comment by PoisonedPotato** [comment]
Nevermind I was going through a diff thing

**Comment by meatloaf4311** [comment]
close the issue please
