### ISSUE TITLE
Flowerpot

### ISSUE THREAD

**Issue by coolrode991785** [Wynncraft/Issues#3408]
I was doing one of the new quests in Karoc Quarry and i clicked on a flowerpot with the flower it gave me and i lost it how can I finish the Quest

**Comment by W-Schnee** [comment]
Did you try **/fixquests** ?

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by coolrode991785** [comment]
sorry but how do i close it I'm new
