### ISSUE TITLE
Damage Value of Weapons

### ISSUE THREAD

**Issue by meatloaf4311** [Wynncraft/Issues#3410]
Heyo, 

I have been playing wynncraft for a long time and have just finished adjusting to the new Gavel Changes.

I have just found one thing missing: EFFECTIVE DAMAGE VALUES.

Before the Gavel Update I would be able to see about how much my weapon was going to do after being affected by armor and skill points but ever since the update the feature disapeared.

Here are some screan shots to show what I mean.

![skill point value](https://cloud.githubusercontent.com/assets/15972169/12069521/c986d162-afe9-11e5-9567-004cf3868d07.PNG)
![weapon effect value](https://cloud.githubusercontent.com/assets/15972169/12069520/c984f2f2-afe9-11e5-8865-e4b5ceb43ce8.PNG)
![weapon value](https://cloud.githubusercontent.com/assets/15972169/12069522/c9893920-afe9-11e5-8b49-fce578fa50f3.PNG)

**Comment by TrashcanMan** [comment]
I think this is more of a design flaw than a bug, that said, I've made [a post] (https://forums.wynncraft.com/threads/slight-change-to-damage-info.101050/) suggesting that this be changed.

**Comment by DarkDemonDragon** [comment]
Like @TrashcanMan this isn't truly a bug, so please close this and follow his post if you want it to be changed.
