### ISSUE TITLE
Relic Bow in Junk Merchant

### ISSUE THREAD

**Issue by ModingMc** [Wynncraft/Issues#3414]
For some reason the Junk Merchant is selling a Relic Bow in world 21.  One of my guild members managed to move it from his inventory into the Junk Merchant.  http://imgur.com/QL1VIBi

**Comment by IceNinjaCreeper** [comment]
Lol

**Comment by Trixter313** [comment]
This will probably fix itself after the server restarts, if it hasn't yet. Once it is fixed, we'd appreciate it if you closed this issue. Thanks!
