### ISSUE TITLE
Wiki You are not using cookies problem

### ISSUE THREAD

**Issue by Anive** [Wynncraft/Issues#3415]
You cant create a account for the wiki,i have tried in google chrome,microsoft edge,and the mobile version of google chrome

**Comment by PieKing1215** [comment]
Same here trying to log into my account with Firefox & IE, but getting: <i><b>

Login error
Wynncraft Wiki uses cookies to log in users. <br>You have cookies disabled. Please enable <br>them and try again. </i></b>

I am 100% sure cookies are enabled in both browsers. Not sure, but this might be something for @Tama63.

**Comment by Trixter313** [comment]
I believe the issue is now resolved. If anyone is still experiencing this, comment down below and I'll make sure to reopen the issue. Thanks!
