### ISSUE TITLE
Liquified Emerald Disappeared in Inventory

### ISSUE THREAD

**Issue by GreenDeqth** [Wynncraft/Issues#3417]
Hello My name is GreenDeqth (IGN name aswell) and I was at detlas with my friend Icyr and I made a liquefied emerald, so I tried trading with him and it randomly disappeared out of my inventory. I tried relogging and clicking the inventory space it was in, but nothing worked so I wanna ask for another Liquefied emerald back, I'm not trying to scam but I'm being serious, Please reply soon as you can

**Comment by IceNinjaCreeper** [comment]
Sorry wynncraft as a strict non-refund policy

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. There's no way to tell what happened to the item, or what caused it, the server or the player. We'd appreciate it if you closed this issue. Thanks!
