### ISSUE TITLE
Armors disappeared

### ISSUE THREAD

**Issue by cubepuzzlemaster** [Wynncraft/Issues#3418]
I hadn't come this server and today I connected server after such a long time. I had to identify my items to use. My inventory was full. When I clicked my armors to identify, it said it needed to be identified and my armors were disappeared. ID is C_P_Master, the class was an archer, magician. Please help. Thanks.

**Comment by Trixter313** [comment]
Unfortunately, due to Wynncraft's very strict no refund policy, nothing can be done about the already lost armor but there is an issue open about this and it should get fixed soon. Please direct any future comments to the original thread, here: #3153

Thank you very much!
