### ISSUE TITLE
Threw a "Almuj Liquified Emerald" and cant complete quest nor get more

### ISSUE THREAD

**Issue by MadmanAl** [Wynncraft/Issues#3419]
I thew one of the Almuj Liquified Emeralds that was designated for one of the quest now i cant do the quest, i tried getting more from the quest NPC that gives it to you but he wont give me more and now i cant do the quest, You can check my inventory to see im missing 1/64 leaving me with 63

IGN: MadmanAl
Class: Mage
Quest: Jungle Fever 

![screen shot 1](https://cloud.githubusercontent.com/assets/16506605/12069928/94dbf0c2-b008-11e5-96ee-3fb54e37b0ae.png)

![screen shot 2](https://cloud.githubusercontent.com/assets/16506605/12069929/9bc795b2-b008-11e5-8d7d-30cfbb0f23cb.jpg)

**Comment by IceNinjaCreeper** [comment]
do /fixquests

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by MadmanAl** [comment]
This did not work, I did /fixquests and it says im not missing anything even though im missing 1 of the 64 "Almuj Liquefied Emeralds" 
![screen shot](https://cloud.githubusercontent.com/assets/16506605/12070500/3d9a19a4-b02d-11e5-81b9-3db478768b1d.png)

**Comment by MadmanAl** [comment]
Should i do what i did before and just throw all of them out, and then do it, or just wait till somone can assist me?

**Comment by Trixter313** [comment]
It's your call, if it does work like below and just gives you more, that would probably be perfect but there's always the chance that it doesn't work again. Specific issues of missing quest items that /fixquests can't fix can take a while to get fixed, so it depends on how long you're willing to wait.

**Comment by MadmanAl** [comment]
It won't let me throw it like before... so im not sure, Im guessing im going to have to wait

**Comment by HeyloLP** [comment]
put the fake le's in your inventory crafting section and fill every other slot with before stacked emeralds or every other item and then close your inventory then do /fixquests

**Comment by MadmanAl** [comment]
@HeyloLP That worked, Thank you so much!
