### ISSUE TITLE
White dragonling bug

### ISSUE THREAD

**Issue by trey1436** [Wynncraft/Issues#3422]
The white dragonling's near Ahmsord fight each other aswell as drop a lvl 36-40 spear alot (i have gotten 4 and only killed about 25) i don't know why they drop this weapon, it is the only weapon i have seen them drop but i have got diamond pants off them lvl 98 also.
EDIT: i also got a staff lvl 92-96 off them so its just the spears that are messed up, i have killed several more and still gotten the same spear (i now have 26 spears) they are all of the same type so they stack,they seem to be a common drop.

**Comment by TrashcanMan** [comment]
The spears might be an intended feature, can you get a screenshot?

**Comment by trey1436** [comment]
yeah here is a screenshot along with coordinates http://prntscr.com/9l4pkk

**Comment by DarkDemonDragon** [comment]
Certain mobs are more likely to drop certain loot. While the mob attacking each other thing is a bug, it's a general issue with all mobs. Unless a mob is dropping a quest item it shouldn't be dropping, mob drops are just what they are. Some are unusual and some are typical.

**Comment by TrashcanMan** [comment]
Have you tried identifying any of the spears? If so, are they still the same? It might be two or three different spears in the same level range.

**Comment by trey1436** [comment]
yes they are the exact same
