### ISSUE TITLE
House of Twain Quest Bug

### ISSUE THREAD

**Issue by Hydrophic** [Wynncraft/Issues#3423]
when i click the button of the code 5732, the door didnt open, did i click the wrong code or is a bug?

**Comment by Forcellrus** [comment]
You have to do it slowly, try switching servers that may help, same thing happened to me.

**Comment by DarkDemonDragon** [comment]
Please give each button 1 second as the button takes about .5 seconds to depress.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
