### ISSUE TITLE
Cinfras - No item buyer and no item identificator icon on world map

### ISSUE THREAD

**Issue by Forcellrus** [Wynncraft/Issues#3424]
There is item identificator across the bank where Item Buyer is supposed to be according to map. I don't know if the icon on world map is misplaced or the NPC is wrong, just wanted to let you know. I believe Item buyer icon should be replaced with icon of Item Identificator.

**Comment by Dar-krusos** [comment]
Yeah, I noticed this the day Gavel came out. The icon for the Identifier is missing and should be where the map says the Item Buyer is, and the Item Buyer should be diagonally opposite of where it is now.
