### ISSUE TITLE
Quest "WynnExcavation Site C" issues

### ISSUE THREAD

**Issue by chrisnumberz** [Wynncraft/Issues#3425]
Quest; WynnExcavation Site C

Issue: I am unable to give Excavation Placardus the purple crystal shards. I tried /fixquests which in return only gave me even more purple crystal shards (that don't work). They do not say untradable quest item, but they only say quest item. http://prntscr.com/9kv4zi
If at all possible I would appreciate a quest reset where it would rest my excavation quest. 

Book: Report back to Excavator Placardus

**Comment by Trixter313** [comment]
You're sure you don't have any other purple crystal shards in any other class inventories or your bank? I'd try all possible to be safe.

**Comment by chrisnumberz** [comment]
Turns out I forgot to grab the red crystal shard at the end of the quest near the level 100 golems, figured it out about 2 weeks ago but thanks ^.^

**Comment by Trixter313** [comment]
Glad to hear! =)
