### ISSUE TITLE
Quest cords

### ISSUE THREAD

**Issue by wynncraftlupascu** [Wynncraft/Issues#3434]
![2016-01-01_19 43 05](https://cloud.githubusercontent.com/assets/14152318/12071669/133d098a-b0c0-11e5-869f-465fd1e37397.png)

**Comment by Trixter313** [comment]
I'm not seeing the issue here. Could you please provide more of a description? Thanks!

**Comment by HeyloLP** [comment]
there is no problem exept you don't find the camp

**Comment by Trixter313** [comment]
So... What exactly is the issue here?
