### ISSUE TITLE
Wynncraft charackter auswählen

### ISSUE THREAD

**Issue by EnderDragonHD** [Wynncraft/Issues#3435]
Leider versuche ich schon lange beim Server play.Wynncraft.net mie ein charackter auszuwählen aber kommt die charackter auswahl immer wieder und ich werde nicht zu der welt tp

**Comment by HeyloLP** [comment]
1 versuch mal die nicht vip charaktäre
2 bitte demnächst auf englisch

**Comment by EnderDragonHD** [comment]
1.Ich keine vip charaktäre genommen
2.sorry

**Comment by HeyloLP** [comment]
versuch doch einfach den Warrior zu nehmen

**Comment by EnderDragonHD** [comment]
Hab ich ja schon aber dann kommt die Charakter auswahl nochmal

**Comment by HeyloLP** [comment]
hmm dann versuch es im nächsten Patch sorry

**Comment by Trixter313** [comment]
Is the issue still occurring?

**Comment by EnderDragonHD** [comment]
Trixter313 
Yes  I dont can play my charakter

**Comment by Trixter313** [comment]
Could you or a friend re-type your issue in English? I don't fully know what's happening here.

**Comment by HeyloLP** [comment]
@Trixter313 his problem is that he is unable to pick a class

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3139

Please direct any future comments to the original thread. Thanks!
