### ISSUE TITLE
Issues on quest: Rise of the Quartron!

### ISSUE THREAD

**Issue by WynnPhoenix** [Wynncraft/Issues#3437]
When you get to the part where you have gone through the secret passage way in the mansion you go down and find beacon rays in your path. As a mage I could Teleport through (there is a bug but there is more). Then I killed the Quartron but when I went to the villager behind it, he still said the same 1 sentence (another bug). so I kept on killing it and nothing happened so eventually I teleported back through and did it the proper way and it worked how it was meant to work (luckily).

**Comment by HeyloLP** [comment]
you need to "kill" the arms and legs untill you have all 4 energy cores and bring the villager behind the mech them and then go back to the quest start npc

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
