### ISSUE TITLE
I did not get bobs soul in the end of the quest bobs lost soul!!!!!!

### ISSUE THREAD

**Issue by snowminer22** [Wynncraft/Issues#3438]
can someoen help me to get a new bobs soul so i can do tempel of legens!!!!!!!
![2016-01-01_20 27 12](https://cloud.githubusercontent.com/assets/16511179/12071951/963cf712-b0c7-11e5-949c-0f1b2006fb9f.png)
![2016-01-01_20 27 17](https://cloud.githubusercontent.com/assets/16511179/12071952/9afc816e-b0c7-11e5-80c8-2a4b02ad54c9.png)

**Comment by Trixter313** [comment]
Try typing /fixquests

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Trixter313** [comment]
If /fixquests didn't work you will just have to wait until someone can fix it. The only other option would be to do the bob quest on another class and use the crushed soul you get from that but then the other class wouldn't be able to do it until someone can fix this. The /fixquests command is still a work in progress so hopefully it will be able to help you soon.
