### ISSUE TITLE
Using Skill Points But It's Not Registering That I Used Them On Something

### ISSUE THREAD

**Issue by Coco10203** [Wynncraft/Issues#3440]
So I Click What Skill I Want To Use The Skill Point On But The Skill Point Gets Used But Nothing Happens To My Skills.

**Comment by DarkDemonDragon** [comment]
Please check all your armor IDs for something that says something like: -10 Agility in red. This means that you lose 10 agility so if you have <10 pts alloted it will show 0 for Agility.

**Comment by Trixter313** [comment]
If DarkDemonDragon's suggestion helped, or the issue fixed itself, please close this issue. Thanks!
