### ISSUE TITLE
"Beneath the depths" Quest boss "Treasure Guradian" is too OP

### ISSUE THREAD

**Issue by GamerGamerFTW** [Wynncraft/Issues#3441]
I cannot kill the treasure guardian even if i have the best gear for my level (61) and he uses hes special like each 3 seconds, and it takes off like 5 hearts. I even asked some players to help me! Even level 76 died. Please make him not so op because i cant finish this quest.

**Comment by Smurfman254** [comment]
If you have a range attack use it and stand in the doorway, if you get mana steal you should be able to spam it fast enough to kill the boss (at least that is what I did)

**Comment by DarkDemonDragon** [comment]
Well I did it alone as a Mage (about Lv 63 or so) Here are the tactics for each class:
Archer: Do not go into the room and gradually bring hp down with Arrow Bomb and use Arrow Shield/Escape in dire situations
Warrior: Attack with Uppercut and avoid the arrows with Charge
Mage: Keep back and use Meteor. Make sure to have mana ready to teleport if necessary
Assassin: Smoke Bomb and Vanish. If he gets too close use Multihit as you'll still be caught with his arrows if you try to Vanish

Remember to use a KB spell when he's about to attack. This way the arrows go into the air and not into you. Please close this issue if this helped.
