### ISSUE TITLE
Bank Fountain in Llevigar

### ISSUE THREAD

**Issue by fernbreeze** [Wynncraft/Issues#3447]
I have a quest that has clues and one is on top of the Fountain in L'levigar And it says "You should not be swimming in the bank fountain." And puts me back out Please fix this glitch!!

**Comment by HeyloLP** [comment]
try other servers

**Comment by fernbreeze** [comment]
I tried all I can it still WONT WORK

**Comment by Anive** [comment]
Thats the 3 part of the quest ... Find another

**Comment by Trixter313** [comment]
Could you post a screenshot of your quest book? Thanks!
