### ISSUE TITLE
I'm losing my items

### ISSUE THREAD

**Issue by ChaosPlays** [Wynncraft/Issues#3449]
I'm losing my items due to identifying them when the server crashes. After this, my item mysteriously vanishes. A example is my skeletal legs. FIX THIS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Trixter313** [comment]
It's not a bug that items not in your inventory at the time of a restart disappear, if it's not in your inventory when the server goes down, the item is gone. Unfortunately Wynncraft has a very strict no refund policy so we can't give you the legs back but for in the future, if it says a restart is coming, switch worlds before it forces you to. Unexpected crashes are unavoidable and annoying but a risk all players must take. I hope this doesn't happen to you again!
