### ISSUE TITLE
The Hunger of Gerts Part 1

### ISSUE THREAD

**Issue by trollkarl** [Wynncraft/Issues#3450]
At the stage where you have to escape your prison cell, I do the "code" and then the jail bars open. i go out of the cell and it says "sum txt" in white. I have tried to do /kill and change server, but nothing seems to work. Please reply/fix ASAP.

**Comment by Trixter313** [comment]
Some screenshots would be helpful. Thanks!

**Comment by trollkarl** [comment]
![2016-01-02_12 40 59](https://cloud.githubusercontent.com/assets/10392816/12074350/2b290cfe-b14e-11e5-9eb6-9e882b8d49bf.png)
![2016-01-02_12 41 10](https://cloud.githubusercontent.com/assets/10392816/12074352/3996b9e4-b14e-11e5-9ca7-6c28cdcd0f57.png)

**Comment by Trixter313** [comment]
Are you still experiencing this since the server downtime yesterday?

**Comment by Trixter313** [comment]
Due to no response in 20 days, I'm going to assume the issue is resolved. If not, simply comment and I'll reopen it. Thanks!
