### ISSUE TITLE
/class problem

### ISSUE THREAD

**Issue by GlacierExplorer** [Wynncraft/Issues#3451]
This is the second time i was occuring that problem. :(
I switched my account to a newer one (ID: Artifacter)  and found out that if I use /class in another account on my computer, it will turn all my items into old style and said that There has been an error, which means I can't exit that room because all my items are in the old-style and I can't interact with any signs. Since my old account is still glitching, I'm sure that /class has some problems, at least on my computer/under my IP address. :(
All my friend are playing like usual and they can use /class, so I think this is a 'personal glitch'. :(
I liked to play Wynncraft a lot. I would be really appreciated if you solve that glitch out for me

P.S. My old Minecraft ID is RElNHARD, now is Totoriott, and when I joined Wynncraft I'm using Favsu as my Minecraft ID. I'm not sure if it matters ._.

**Comment by Dar-krusos** [comment]
This is a very big problem that several people have had. I don't think many peolle know about it though. See Issue #3139 for more details.
