### ISSUE TITLE
Texture Packs

### ISSUE THREAD

**Issue by ItzDwarfPvP** [Wynncraft/Issues#3452]
As the texture pack the server uses doesn't help my fps like my normal texture pack does I decided to turn the server one off and use my normal pack, but when I join a world I just fall through it and nothing happens. However when I turned it back on again the game continued fine. Please fix this or i'll be stuck in one area due to me running 5fps in that area and get teamed on by mobs so I die before I can do anything about it.

**Comment by TrashcanMan** [comment]
I don't think the texture pack should affect performance since it's the same resolution as default. It might be a lag issue, or a hardware issue on your side.
