### ISSUE TITLE
The Mummy is not working

### ISSUE THREAD

**Issue by KwaiiKittens** [Wynncraft/Issues#3454]
![wtf mummy](https://cloud.githubusercontent.com/assets/16512936/12072856/6a95b4e6-b0c7-11e5-8b3c-e26a22d59d09.png)
Why does he have do much health?  He isn't taking ANY damage from any of my attacks!I started playing Wynncraft again because they updated it and I did the Wrath of the Mummy Quest and the Mummy isn't supposed to have 6750 health! Only like 1250 health! I don't know if it's a bug or they buffed the mummy so much that he killed me it 2 hits! Someone plz help.

**Comment by Trixter313** [comment]
Try using different elements. Bosses will usually be damaged a lot more by a specific element. I don't believe this is a bug.
