### ISSUE TITLE
Fantastic Voyage teleport

### ISSUE THREAD

**Issue by DarkValor** [Wynncraft/Issues#3457]
I was at the end of the quest and only had to talk to Relend. I walked arround a bit before I wanted to talk to Relend. But when I walked arround, I got teleported to the starting area in Wynn, close to Ragni. I don't see any way for me to get back there so now I can't complete it.
(If I could get teleported there somehow, that would be great. My IGN is DarkValor)

**Comment by TrashcanMan** [comment]
You can just go through the starting bit again and enter the teleport into Ragni. Then head back to Gavel and continue on.

**Comment by Dar-krusos** [comment]
I found out the same thing the hard way. If you walk too far in the ending room, you will get teleported to the Starting Point, so this should be viewed as a bug.
Please fix this issue, as it will only frustrate many unbeknownst players.

**Comment by Villageacules** [comment]
Salted has confirmed that there is a way back into the gateway realm after death.  Getting moe to close this.
