### ISSUE TITLE
Two different textures for Nesaak's Shadow

### ISSUE THREAD

**Issue by TrashcanMan** [Wynncraft/Issues#3458]
So I have two different Nesaak's Shadows, one of them is chain but the other is iron. It's not really that big of a bug but it's still there. Also one was from pre-Gavel and the other was from today, if that helps.
![2016-01-01_21 28 17](https://cloud.githubusercontent.com/assets/6947594/12073336/25f68a6e-b0d0-11e5-90a3-324404e1484e.png)
![2016-01-01_21 28 18](https://cloud.githubusercontent.com/assets/6947594/12073337/261a65c4-b0d0-11e5-89e0-a3c27b1f22c9.png)

**Comment by FFacepunch** [comment]
dont worry about it, i had the same "issue" its not, it just means that u have duplicated something =)

**Comment by TrashcanMan** [comment]
I think the issue is that the pre-Gavel ones are iron, but after Gavel they were changed to chain and the old ones didn't update. I've sold my iron one since the chain one is better, so I guess there's nothing much left to report.
