### ISSUE TITLE
Items lost during identification

### ISSUE THREAD

**Issue by SubmissiveMC** [Wynncraft/Issues#3459]
Hey there

I was in the update room and I was identifying my items, however the items were still in the NPC's inventory as the server restarted. Is there any way I can retrieve these lost items?

Thanks :)

**Comment by ThunderRemix** [comment]
Nope, "no refund policy" and all that.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so we can't do much in this situation. I suggest switching to a different world when you first get notified that the server will restart soon to prevent this. I hope this doesn't happen to you again!
