### ISSUE TITLE
Lost my bow during identification 

### ISSUE THREAD

**Issue by kingakm** [Wynncraft/Issues#3460]
While I was trying to re-identify my relic bow with sharpness +2 (after update a couple weeks ago) . I was trying to identify the bow when the whole server crashed and I never saw it again :( is there any way to get it back? Thank you for your time,
kingakm

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so we can't do much in this situation. For future reference, I suggest you switch to a different world when the first message pops up that the server will be restarting soon so this doesn't happen again. Hope this helps!

**Comment by kingakm** [comment]
The world didn't re-start it crashed!

**Comment by Trixter313** [comment]
Unfortunately there's a strict no refunds policy no matter what the circumstances are. You can visit the relic shrine on another class or buy another bow from someone.
