### ISSUE TITLE
Memory Paranoia Glitch

### ISSUE THREAD

**Issue by Smurfman254** [Wynncraft/Issues#3461]
After defeating the boss caritat at the end of the quest I was teleported to -1420 67 -1605 and was then stuck. I was stuck in the room with someone else, we were both forced to /kill. After that we ran through the quest again and went through the rift, we again got stuck in the same box (yes we made sure to go through at different times) again forced to /kill.

**Comment by Smurfman254** [comment]
Oh it might also be important that someone's server shut down during the dialog that is supposed to happen there and switched to my server.

**Comment by Trixter313** [comment]
This was most likely due to lag but shouldn't happen now that the server are stable. If it does happen again, comment and I'll reopen the issue. Thanks!
