### ISSUE TITLE
Custom Resource Pack doesn't seem to work for Mac Users

### ISSUE THREAD

**Issue by Ahi637** [Wynncraft/Issues#3462]
Ever since December 26th, Mac users like me and some other people on the forums have had trouble loading the resource pack(And yes, I do have server resource packs enabled in server settings). I don't know if their was an update recently, but the pack stopped working. It used to work perfectly fine, and I haven't made any changes to my computers since the resource pack has worked. Also I've logged onto my account from my sister's laptop and resource pack has worked there. I've been on other servers with server resource packs and they work too. If any mods or admins do happen to see this post, I'd appreciate it if you could help. (If you want to see my post about this issue on the Wynncraft forums my name is the same there, Ahi637.)

**Comment by Tama63** [comment]
![Screenshot](https://www.dropbox.com/s/haf1coaiqc5ia9q/Screenshot%202016-01-02%2010.45.56.png?dl=1)
