### ISSUE TITLE
WynnExcavation Site A GLITCH  - It's bugged thanks for a restart

### ISSUE THREAD

**Issue by Kobcy** [Wynncraft/Issues#3464]
Hey! 

I wanted to do the WynnExcavation Site A mission, but it's bugged thanks for a random server restart.
The server shut down during the a dialog. I talked with Excavator Vade and he said to go to speak with Tesha. I started to talk with him, but in the end of the speaking happened the restart. Now Tesha says: "Take that to vade, and don't read it!".
Okay I tried to talk with Vade too, but he said: "Hmm 'Throw tribute an item to the wood that stands out, the right angle will open the way' What does this translation mean? I know it must be inside the temple, but where? Huh? Be gone, you!". Then I tried to go inside the temple. I find the secret "lock" and I opened the diamondblock trapdoor. When I tried to fall down I couldn't, and it said: "A strong force is preventing your entry" I didn't have any ancient writing, what I had before. Now I can't do anything and the Quest Book don't want to update. It says: "Go talk to the Lab Assistant Tesh in the tents". But I wrote what's happening if I talk with him. 
Please help me, I think I have to restart this quest or just give me an ancient writing or translated ancient writing, maybe it solves the problem.

My character's name is: Kobcy
I'm a 38 level Warrior.

Thanks for helping!

PS: Sorry for my bad english knowledge, I'm hungarian. :D

**Comment by Trixter313** [comment]
Try typing /fixquests to see if it helps at all.

**Comment by Kobcy** [comment]
Thanks for helping, I didn't know this command before, but it solved my problem and fixed the quest.
And again THANK YOU VERY MUCH! :D

**Comment by Trixter313** [comment]
Great to hear =)
