### ISSUE TITLE
Random damage

### ISSUE THREAD

**Issue by XYodelingpickleX** [Wynncraft/Issues#3466]
In Wynn when gavel came out only as my assassin I have been taking random damage fir no reason while standing still with full hunger anyone know how to fix?

**Comment by arneturuc** [comment]
There are some equipment pieces with negative health regeneration identifications introduced in the update.
Do you wear such an item?

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
