### ISSUE TITLE
Bob's reincarnation near immortal

### ISSUE THREAD

**Issue by sinomsinom** [Wynncraft/Issues#3467]
we were a 12 headed party (lvl 75-80) and it still was near impossible for us to kill bob. also the feature for dropping items for every player in the fight didn't work

**Comment by ImSickPT** [comment]
When I tryed to do the Bob's fight, it was also near impossible. We were around 20 people.

**Comment by HeyloLP** [comment]
that's because Bob only gets normal dmg and is imune to all elements

**Comment by 0Patrick0** [comment]
They are going to nerf him in a future patch. Just be patient or fight him with normal damage weapons. I took him with with about 7 other people.

**Comment by Trixter313** [comment]
As HeyloLP mentioned, make sure you are using high neutral attack weapons. I believe some people have soloed him since the update so it just comes down to making sure you have the correct weapons.
