### ISSUE TITLE
Reincarnation Reward 

### ISSUE THREAD

**Issue by annoyingenderman** [Wynncraft/Issues#3469]
So, i killed Bob, got the approval and handed it in to Batelu. But then, after he was done with talking, he gave me the Corrupted Treasure and nothing else. The quest didn't "End" and i got no XP at all.

So basically, the problem is that i didn't get the XP while the server was on Triple XP. Could i maybe get the XP or a compensation for it?

Thank you.

Ingame name: Annoyingenderman
Class: Level 87 Archer.

**Comment by HeyloLP** [comment]
thats a common bug and you won't get any xp because of the strict no refund policy

**Comment by Trixter313** [comment]
Are you getting other XP? It's possible that you are giving all or a lot of your XP to your guild. To make sure you aren't, type "/guild xp 0".

**Comment by annoyingenderman** [comment]
I'm not currently in any guild, or ever have been in one for the sake. It just didn't do anything. But, eh, i have to live with it i guess.

**Comment by Trixter313** [comment]
So is the quest finished in your questbook?
