### ISSUE TITLE
Green Skinned TP Trouble

### ISSUE THREAD

**Issue by CMWizard** [Wynncraft/Issues#3471]
During the quest: "Green Skinned Trouble", after killing the Orc with the Axe of Llevigar, I walked into the coal block teleport hole and it tped me to a wierd location. I was completely encased in solid blocks, could not move and had to /kill. This happened with an Assassin Class. This quest went fine with my other classes, however, proving that it is not something that happens often. Just thought you should know.

**Comment by Dar-krusos** [comment]
This seems to be a recurring problem #3139

**Comment by CMWizard** [comment]
This is not a class-loading issue

**Comment by Dar-krusos** [comment]
Oh woops, wrong link xD.
Here's the correct one #3339.

**Comment by CMWizard** [comment]
I see, well, lag is weird I guess...

**Comment by Trixter313** [comment]
Now that the servers are more stable this shouldn't happen. I have tested and it seems to not be happening anymore. If anyone still experiences it, just comment below and I'll reopen the issue. Thanks!

**Comment by CMWizard** [comment]
Good to hear the servers are more stable. Probably because the player population has dropped a bit since it's been a little while since gavel came out ;)

**Comment by Trixter313** [comment]
That and the staff have been releasing patches fixing lag pretty well. They are so confident that they are planning on testing increasing the player limit per server to 75 then possibly even higher.

**Comment by CMWizard** [comment]
Well ;P I don't know about that just yet. Boats still desync and riding horses seem to get pretty laggy, connection-wise. So I think 60 is good for now.
