### ISSUE TITLE
Stuck in a invisible barrier

### ISSUE THREAD

**Issue by lolmandru** [Wynncraft/Issues#3472]
I am stuck in a mountain but i can see through the blocks but they are there. Its hard to explain but I need to get out!!! Im at X-582 Y129 Z-5603. PLEASE HELP

**Comment by lolmandru** [comment]
Oh and I cant use teleportation scrolls in there either so :|

**Comment by GuerrierHache** [comment]
Try /kill.

**Comment by lolmandru** [comment]
Ok

**Comment by lolmandru** [comment]
Thank you I finaly got out!!!
