### ISSUE TITLE
Item bug

### ISSUE THREAD

**Issue by GuerrierHache** [Wynncraft/Issues#3473]
Help!!After an identification ,my old wand (diablo) and my new wand (Burning Torch) disappeared!!Help!!

**Comment by HeyloLP** [comment]
sorry there is a no refund policy so they won't give you back anything maybe you ask other players if you could buy a wand and then go farming again sorry

**Comment by GuerrierHache** [comment]
finally,i have found an another Burning torch ^^

**Comment by GuerrierHache** [comment]
thanks HeyloLp for your reponse ^^
