### ISSUE TITLE
Crop Failure not giving full reward

### ISSUE THREAD

**Issue by CMWizard** [Wynncraft/Issues#3474]
After completing Crop Failure, even though it said in the text, and again in the chat after completing the quest, that I would recieve 10 eb, I only recieved 6.

**Comment by Trixter313** [comment]
Did you already have emeralds in your inventory before you finished the quest? This is known to cause issues with quest rewards so if you did, for future reference, try not to finish quests with emeralds in your inventory to prevent this.

**Comment by CMWizard** [comment]
I only had normal emeralds, not blocks. Also, this happened twice, with both my mage and assassin classes.

**Comment by Trixter313** [comment]
Normal emeralds might also do this, I'm not sure.
