### ISSUE TITLE
"Flight in Distress" Teleport Issues

### ISSUE THREAD

**Issue by Omnireg** [Wynncraft/Issues#3475]
I'll attempt to keep this polite, but I had to redo the qeust 5 times now...

Issue: Towards the end of the quest (after fighting the Pirate Queen and obtaining her ring) when you jump down in the Treasure Room... there seems to be an Issue where the Command blocks lag and don't teleport you out of the dark room...

Fix?: Just add a Fail-safe where it tries multible times to teleport you... atleast reduces the chance of missing the signal

Fix ASAP, its INSANELY frustrating to redo all of that... every... time..
Thanks.

**Comment by Omnireg** [comment]
(You can just add a Fail-Safe where 2 it tries multible times to teleport the players out which are in that area, not just one)

**Comment by Dar-krusos** [comment]
This happened to me as well. I don't think it was lag, because I got teleported a few days after when I logged back on (I was still in that obsidian room).

This should fix itself after a few days.
