### ISSUE TITLE
Can't access my Mage

### ISSUE THREAD

**Issue by RiasPawn** [Wynncraft/Issues#3476]
Hello, I used to play on this server AGES AGO back before 1.12 and I returned recently to find myself unable to access my level 60 Mage. Idk what the issue is but for some reason I always get an error whenever I attempt to enter with it.

**Comment by Ewaszczypior1** [comment]
Hey, I've got the same issue just a bit lower in the topics. There was a big update in Wynncraft so you can't basically enter. I need help too :/

**Comment by Dar-krusos** [comment]
See Issue #3139, as this is a duplicate.

**Comment by Trixter313** [comment]
What is the error message you get?
