### ISSUE TITLE
Quest: Murder Mystery

### ISSUE THREAD

**Issue by 1Entropy** [Wynncraft/Issues#3478]
My quest book did not update after I talked to Rohem, so I cant get into the bar to reach the sewers. Whenever I get close I get a message saying. "The smell of old whiskey is nauseating around this building, driving you back". Please fix this quest so I can turn it in, if you need to know my username it is "0Entropy".

**Comment by Trixter313** [comment]
Have you tried talking to Rohem again?

**Comment by 1Entropy** [comment]
Yes I have tried that. I think the problem is that my quest book did not update after talking to him, it still has the first set of instructions.

**Comment by Troll2828** [comment]
After you talk to him he tells you to find a bat symbol(wither skull) at the victim's house. When you do press the button next to the bat symbol, to reveal the number. Then go to the house with the same number in cinfras. I hope this helps.
