### ISSUE TITLE
Stuck.

### ISSUE THREAD

**Issue by cole9136** [Wynncraft/Issues#3479]
I left the sever inside the Identifiers place, as my mage. When I rejoined the sever I was trapped in a cage under the identifiers house and rejoined at least 5 times and I still couldn't get out. Now I can no longer play as my mage. Please fix this. My in game name is cole9136.

**Comment by HeyloLP** [comment]
use /die

**Comment by Ewaszczypior1** [comment]
You can try to use the command /kill so you will be killed and will respawn in the city (for the cost of 2 soul items of course, as it counts as a death).
