### ISSUE TITLE
Forge + Wynncraft

### ISSUE THREAD

**Issue by iAstroGames** [Wynncraft/Issues#3480]
Decided to put a minimap on. Loaded up forge, and the server pings for about 3 minutes and says cannot connect. Other servers load up instantly.

**Comment by Trixter313** [comment]
I just logged in with Forge on and works fine for me. What IP address are you using and mods?

**Comment by slendersir739** [comment]
Maybe you can try Liteloader?

**Comment by iAstroGames** [comment]
I'll try Liteloader, also I'm using Optifine and journeymap.

**Comment by Trixter313** [comment]
What about the IP address? Try one of the other ones listed here to see if that helps https://forums.wynncraft.com/threads/all-possible-ips.100486/

You could also try and disable the mods you have to see if it works without them.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
