### ISSUE TITLE
Server Crash during "Flight In Distress" cutscene

### ISSUE THREAD

**Issue by 0Patrick0** [Wynncraft/Issues#3482]
I was doing the quest "Flight in Distress," and during the cutscene, the server did one of those spontaneous crashes. After rejoining the server, I was stuck in the cutscene, and it didn't advance at all, making me stuck in the 1x1 block area. I did /kill (and was teleported to Olux?) then made my way back to the ship. I retraced my steps, and got to the part where you have to put in the code. I put it in, and when I go talk to the engineer, nothing happens. Keep in mind that I already gave back the code sheet, since I had gotten to the cutscene before. Please fix this for me, and next time create a fail safe that continues doing a cutscene whenever there is a player present. Message me in-game so that I can finally finish this quest. Username: 0Patrick0

**Comment by Trixter313** [comment]
What does it say in your questbook? You can try the /fixquests command but it may not help.

**Comment by 0Patrick0** [comment]
It says "Get to the other ship," but obviously I cannot due to the fact that I cannot get to the cutscene and/or after the cutscene. I'm stuck at the part where you  have to put in the code.

**Comment by 0Patrick0** [comment]
Can someone get me teleported to the part after the cutscene?

**Comment by 0Patrick0** [comment]
Also, /fixquests does not help. It gives me quest items from quests that I have already finished...

**Comment by 0Patrick0** [comment]
I still need this fixed btw.

**Comment by Dar-krusos** [comment]
I'll guide you through it. My IGN is Dar-krusos.

EDIT: We met just today, lol.

**Comment by Trixter313** [comment]
Did you two get the issue sorted out or is it still occurring? Thanks!

**Comment by Dar-krusos** [comment]
Haven't yet. I haven't been online as much, lately.

**Comment by AckroWynn** [comment]
As far as I remember, you need to go to the bedroom and then downstairs to the ladder. That should re-a tivate the cutscene.

**Comment by AckroWynn** [comment]
However, there is nothing more we can do on the matter. Sorry.
