### ISSUE TITLE
Daily Rewards not opening.

### ISSUE THREAD

**Issue by Magic-Pyro** [Wynncraft/Issues#3485]
When selecting the daily reward from the character info screen, the screen will close. But the Reward Chestt will not open.

**Comment by Trixter313** [comment]
This was most likely a one time issue. Try again tomorrow and if it works please close this issue. Thanks!

**Comment by Monkeysz** [comment]
Doesn't work for me too.

**Comment by Trixter313** [comment]
This issue should be fixed now. if anyone still experiences it, please just comment and I'll reopen the issue. Thanks!
