### ISSUE TITLE
Quests Finished: 0/104?

### ISSUE THREAD

**Issue by AlphaMasterYi** [Wynncraft/Issues#3487]
It says i have completed 0/104 quests, but i really completed 39 quests
![2016-01-02_19 27 47](https://cloud.githubusercontent.com/assets/16521634/12076758/c62aef36-b187-11e5-99ba-d247bd1bbba5.png)
![2016-01-02_19 28 02](https://cloud.githubusercontent.com/assets/16521634/12076759/c7e6b7ce-b187-11e5-8f53-7e130d947015.png)

**Comment by slendersir739** [comment]
This is just lag.

**Comment by Verret001** [comment]
@slendersir739 Don't assume. It hasn't happened to you.
It could be lag, Or it could be some curuption on your assassin,
Or incorrect data transfer. I recommend ignoring it the best you can,
Hopefully one of the developers will fix this.
