### ISSUE TITLE
Helm of Darkness (Rare - Chain Helmet) not updated for Gavel

### ISSUE THREAD

**Issue by xt449** [Wynncraft/Issues#3489]
Old "Helm of Darkness" (Rare - Chain Helmet) was not updated/reset for the Gavel update.

![image](https://cloud.githubusercontent.com/assets/3751431/12076965/f58ff752-b192-11e5-942d-d06d42a18b5c.png)

**Comment by slendersir739** [comment]
Please wait for the Wynncraft team to get to it, not all armour is identifiable yet.

**Comment by Tyzillion** [comment]
It looks like they kinda updated it, just not all the way...

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3161

Please refer any future comments to the original thread. Thanks!
