### ISSUE TITLE
I lost the purple crystal shard needed for WynnExcavation Part C.

### ISSUE THREAD

**Issue by Raccoonial** [Wynncraft/Issues#3492]
I was on the Volcano Island and I was starting the quest "Wynnexcavation Part C". Right after I had given the quest NPC my "Purple Crystal Shard", the server shut down, and I was kicked to the lobby. There was no warning of the world restarting.The NPC was not finished talking, so he took my shard, but the quest wasn't initiated. When I rejoined in another world, I didn't have the shard, and the quest wasn't started. I tried "/fixquests", but it didn't do anything.

**Comment by slendersir739** [comment]
If /fixquests did not work, then you will have to get the shards on another class, and that class will not get to do the quest. Try /fixquests at a different time and it might work.

**Comment by Moe-Ronickah** [comment]
Have you been able to complete the quest?  Did /fixquests work?
