### ISSUE TITLE
Getting kicked 

### ISSUE THREAD

**Issue by ZFSAIFv0** [Wynncraft/Issues#3495]
So every time i get in any server i get kicked 
i download the resource pack and still and it give me this massage 
![dfgkldfkmg](https://cloud.githubusercontent.com/assets/16523688/12077989/8208168e-b20f-11e5-84c6-b5069b7e70f6.PNG)

**Comment by Trixter313** [comment]
The issue should be resolved by now. if it isn't, please comment below and I'll reopen the issue. Thanks!
