### ISSUE TITLE
Party XP Share

### ISSUE THREAD

**Issue by Hankyana** [Wynncraft/Issues#3496]
It happened once to me, and I'm not sure what the exact conditions are. I was level 91, with 99% exp, when I did Bob's Reincarnation with a group of people. When they turned it in, I was the only person to get xp, and I leveled up to 93.

**Comment by ZFSAIFv0** [comment]
maybe because u got the kill shot ?

**Comment by Hankyana** [comment]
... I took their quest xp not the xp got from killing Bob himself..

**Comment by CrafterTheMaster** [comment]
yea happened to me during a gavel quest. I was 57 and leveled up to 63

**Comment by Moe-Ronickah** [comment]
If the difference in levels in the party members is too great, then only the highest level class will receive any XP.  Also, and more importantly to this issue, Salted has said, "It won't work though if the party members' level difference is too high. Also does not work with quest XP."
