### ISSUE TITLE
Stuck underground can't get up!!!!!!!

### ISSUE THREAD

**Issue by niko44lai** [Wynncraft/Issues#3500]
Hello. My ign is niko44lai... I was playing casually with my friend! There came a huge lag spike. And a render bug came i fell down to the hole! And the lag was gone then i was stuck in the hole with dirt untop of me and can't get up! Ive tried to type in chat if any staff's were on. No-one could help me! so i would deeply appreciate if you would be able to teleport me to Deltas or ragni or just away from the hole!

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should bring you to the nearest visited town.

**Comment by niko44lai** [comment]
thanks!
