### ISSUE TITLE
Bag on quest Frost Bitten 

### ISSUE THREAD

**Issue by ZozoStudio** [Wynncraft/Issues#3501]
My quest item Bucket I was gone and I can not get the quest please help me

**Comment by Trixter313** [comment]
Try typing /fixquests

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by ZozoStudio** [comment]
Thanks
