### ISSUE TITLE
Bugged warrior/archer weapon. (Warrior weapon with archer class requirement)

### ISSUE THREAD

**Issue by SrgtCartman** [Wynncraft/Issues#3502]
I found this weapon in Llevigar after identifying this from a bow. I have a feeling that this wasn't intended.
![2016-01-03_03 25 18](https://cloud.githubusercontent.com/assets/3431097/12078911/8084deec-b1e1-11e5-8c1e-8a85d01225be.png)

**Comment by xTheSilverWolfx** [comment]
I had the same problem a few days ago. Who knows, maybe they will fix it and that item will be super rare and valuable. Or more likely they will fix it and reset it so that you have to reidentify it, and it will be worthless.

**Comment by xTheSilverWolfx** [comment]
I haven't been on wynncraft for a while so I'm not 100% sure, but I believe that they did change it to a warrior/knight weapon. At least, that's what I recall.

**Comment by Moe-Ronickah** [comment]
There have been no other reports of this since this was first found, so I am assuming that it was fixed.  If it isn't, then we can reopen it.
