### ISSUE TITLE
Item Identifier Glitch

### ISSUE THREAD

**Issue by xXusernameXx** [Wynncraft/Issues#3503]
One day, I was just grinding, and then BAM!!! I find a legendary item! (YEAH!!!) I have it identified right away. I am just looking at it (it's still in the item identifier's hands and not in my inventory) and BAM (again)!!! Server restart. The 222 emeralds I spent on the identifying and the item (that I won't find ever again) is gone. I recommend making identifiers instantly give you the item to fix this. Also, can I please get staff help getting the item back? I'm pretty sure the name ended with "slash," dealt mostly neutral and some air damage for about 27-210 damage. (That is just an estimate.) It was an assassin weapon, and it cost 222 emeralds to get identified. It had a few buffs. My IGN is HayHay_200, and I would really appreciate it if I could get it back. If I can't get it back, at least fix the glitch so no one else will have to lose their new item to a badly timed server restart.

**Comment by GamerGamerFTW** [comment]
Sorry but wynn doesnt give any refunds if you dont have the evidence

**Comment by xXusernameXx** [comment]
Oh... okay. Thanks for telling me.

**Comment by Trixter313** [comment]
As mentioned above, Wynncraft has a very strict no refunds policy so you probably won't get the items back. To prevent this from happening again, I reccomend switching to another world right when it starts announcing the server will restart soon. Server restarts can cause items to disappear, as you now have experienced and can break quests if you are in the middle of some dialogue so it's best to just leave as soon as possible. Hopefully it isn't too much of an inconvenience!
