### ISSUE TITLE
Beyond The Grave Puzzle

### ISSUE THREAD

**Issue by annoyingenderman** [Wynncraft/Issues#3506]
This is more a complaint than a bug. The Puzzle in the Beyond the Grave quest is kinda broken. The lag makes it impossible to spell out the word "Tombstone", making the highlight suddenly go faster, slower, or completely stop. 

I would say that the puzzle is broken at this point, it's not efficient as a puzzle, it's more of  a frustrating mini-game. I've literally, not even exaggerating, been trying to do it for an hour now. 

If you could fix the puzzle by changing it to something else or atleast make the highlight go at a steady pace, that would be great. Thanks.

**Comment by Trixter313** [comment]
This shouldn't be an issue anymore due to the servers being more stable now. If anyone still experiences, please just comment below and I'll reopen. Thanks!
