### ISSUE TITLE
Problem with the quest "WynnExcavation Site D"

### ISSUE THREAD

**Issue by OmerBenGera** [Wynncraft/Issues#3507]
There is no way to kill the last boss, called "Fully Formed Amadel".
We are 3 players (2 mages & archer) and we can't kill it. both of us levels 90...
Can you check it please? :)

**Comment by trey1436** [comment]
i solo'd it last night as a lvl 90 archer it is possible i was using the spiritshock level 81 legendary bow if that helps at all

**Comment by OmerBenGera** [comment]
Maybe you can help me...?

**Comment by Trixter313** [comment]
What are your element builds?

**Comment by trey1436** [comment]
these are my stats http://prntscr.com/9lr01p http://prntscr.com/9ls8qu http://prntscr.com/9ls976 and my gear is Helm: http://prntscr.com/9lqzs1 Chest: http://prntscr.com/9ls9l7 Legs: http://prntscr.com/9ls9sn Boots: http://prntscr.com/9lsa04 Ring1: http://prntscr.com/9lsa6k Ring2: http://prntscr.com/9lsact Bracer: http://prntscr.com/9lsakz Necklace: (well what was my necklace im using the reward one now) http://prntscr.com/9lsata Weapon: http://prntscr.com/9lsb3h

**Comment by Trixter313** [comment]
I'm not sure but it's possible that Thunder damage doesn't do much to Amadel and that's why it's so hard. I'm not very caught up on the new elements but I heard that some bosses aren't damaged much by certain ones. Something to think about maybe.
