### ISSUE TITLE
Losing items

### ISSUE THREAD

**Issue by Inetosti** [Wynncraft/Issues#3510]
I lost a lot of emeralds they just were gone, it were like 62 blocks. If a owner or something reads this please give me back my emeralds, my ign. is Pepijn_HvR

**Comment by xCalico** [comment]
I'm sorry to tell you this, but throughout all of my time playing wynncraft, it seems they have a very very strict rule of no refunds. they won't give back anything that was taken away, I know it sucks, but that is just how the server is.
