### ISSUE TITLE
Spirit of Gale

### ISSUE THREAD

**Issue by Loganblahtimes2** [Wynncraft/Issues#3513]
Whenever I try to fight the Spirit of Gale boss in the Hive, it teleports out of the arena. It can teleport as you probably know, but out of the arena, and falls down to a place unreachable by any spell. From there, I can barely read the name tag even with optifine zoom. How to fix?

**Comment by Trixter313** [comment]
Is the boss still doing this? Is shouldn't by now. If it does, just comment below and I'll reopen the issue.
