### ISSUE TITLE
Guild /leave bugs

### ISSUE THREAD

**Issue by Zevys** [Wynncraft/Issues#3514]
I did /guild leave and it pops up a sign where it tells me to say yes or no to leave the guild. I type yes and i'm still in this guild. 

Staff please help IGN: Zevys | VIP  |

**Comment by OhZeltar** [comment]
Same problem with me.
IGN: OhZeltar

**Comment by CrafterTheMaster** [comment]
Me too. IGN: CrafterTheMaster

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3405

Please direct any future comments to the original thread. Thanks!
