### ISSUE TITLE
Teleport zone glitching on quest "Pit of the Dead"

### ISSUE THREAD

**Issue by AntTehNee** [Wynncraft/Issues#3515]
I was completing the quest "Pit of the Dead" and jumping into the water portal. When I did, I suddenly fell through the area into a small underground spot under it. I am unable to get out as lagging may have contributed to it. All I ask is that the account "xMooFace666" be teleported out of the hole into another area. (EX: Detlas) Please help as I am far into the game and I don't want to restart. 
Info that might help: 
Class: Archer 
Level: 33
Account Name: xMooFace666
First Item in Inventory: Relic (Weapon)
Coords: x= -2985 y= 25 z= -4453

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will teleport you to the nearest visited town.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
