### ISSUE TITLE
Respawn issues in Llevigar Plains.

### ISSUE THREAD

**Issue by feedonswords** [Wynncraft/Issues#3516]
If you die in the parkour part of the quest "Green Skinned Trouble", you respawn in the area in which you start the game. (The place before Ragni)

**Comment by SioN-wynncraft** [comment]
I died inn boss fight and it took me there too

**Comment by meatloaf4311** [comment]
Wow, that would really stink, but I believe that if the game does not log you ever going to LLevinger, that is the closest spawn location

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3617

Please direct any future comments to the original thread. Thanks!

**Comment by NyanCatZ06** [comment]
I died while doing a quest in Llevigar Plains and got teleported there too
