### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by oblivian126** [Wynncraft/Issues#3517]
So i wanted to switch classes and typed /class which didn't work and bugged me out , after that i did /toggle autojoin and now every time i try to join it spawns me in a weird ass place with a chest and a sign from salted saying if someone touches the chest he will be kicked from the team . IDK how i got here (oh and also there's this villager npc guy aswell ) the only command i can type is /hub so i can't toggle the autojoin back so im basically stuck there . I need help ASAP. D:

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out and respawn you at the nearest visited town.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by oblivian126** [comment]
You see /hub is literally the only command i can type when i try to type /class , /kill or /toggle or any other command it just says : "You can't use commands right now!" .

**Comment by oblivian126** [comment]
Oh and also , if u want screenshots go to the topic i made in the forums : https://forums.wynncraft.com/threads/salted-is-mad.102623/

**Comment by Trixter313** [comment]
Oh, you're in that place. I believe enabling the server resourcepack fixed this for some people. Try selecting Wynncraft in the servers menu and then click edit then turn server resourcepacks to enabled. Hope this helps!

**Comment by oblivian126** [comment]
That worked , thanks! I'll close the issue.

**Comment by Trixter313** [comment]
Great to hear =)
