### ISSUE TITLE
TELEPORTATION PROBLEMS IN QUEST

### ISSUE THREAD

**Issue by CHENS85** [Wynncraft/Issues#3518]
![2016-01-03_17 32 23](https://cloud.githubusercontent.com/assets/5460820/12081205/08165f8a-b227-11e5-9398-595ec02d7379.png)
![2016-01-03_17 32 43](https://cloud.githubusercontent.com/assets/5460820/12081206/0b9be148-b227-11e5-896c-5fef8ea2d5f6.png)
Its where i escape through the mysterious rift 
PLEASE HELP 
and doing /kill doesnt work when i get back here
IGN: CHENS85 | VIP+
Class: Archer
Level: 67
Quest: Memory Paranoia

**Comment by Trixter313** [comment]
Try doing it now, the servers should be a lot more stable and this was most likely caused by lag. If it still happens, comment and I'll reopen the issue. Thanks!
