### ISSUE TITLE
No Potion Effects Are Added During Spells

### ISSUE THREAD

**Issue by CrazyCoaster101** [Wynncraft/Issues#3519]
Before the update, several spells would give enemies potion effects. For example, my Escape spell would freeze enemies from 2 seconds. After the update, it stopped doing that. Can someone please notify a mod or owner about this so they can fix it ASAP? It would allow fighting to be much easier! Thank you!

**Comment by PikachuMC321** [comment]
The new update, Gavel, has nerfed this spell. It not freezing the mobs is intended to happen. Instead, press shift while falling to attack around you. For more info, go to https://wynncraft.com/help
