### ISSUE TITLE
Stuck in a wall when on the quest Green skinned trouble

### ISSUE THREAD

**Issue by DualPikachu** [Wynncraft/Issues#3520]
Please anyone tp me out 
Username DualPikachu
![a1374873123e578c1b3e1ea840ebbc85e6fc842ba51b2541f2 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/16531269/12081993/f554c2b6-b23e-11e5-93ac-027f87eea969.jpg)

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should teleport you to the nearest visited town.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by DualPikachu** [comment]
Thanks
