### ISSUE TITLE
Falling through floor?

### ISSUE THREAD

**Issue by Arakai13** [Wynncraft/Issues#3521]
Hello, I'm user Arakai_.

I haven't played on Wynn in quite some time, so when I decided to come back I tried to connect to the server as usual but whenever I choose a server from your lobby I seem to fall through the floor of the class selection area? I get that little peek of where I was logged out last before being taken to the selection area, where I immediately drop into the void. I know that it isn't lag on my end, as I'm able to do /lobby and it takes me back to the main lobby immediately (I tried testing other commands and it immediately came up with error messages as well, so I know it's not kicking me). I have no idea what might be causing it, all I get is a few broadcasts telling me I don't have the recommended resource pack (which I have never previously installed, and have had no problems not using it)

Any idea what's going wrong? I'd really love to get back into my Wynncraft account now that this new expansion has come out. Also my apologies if this isn't the area to report this, it's my first time using your forums.

Best regards,
-Arakai

**Comment by Trixter313** [comment]
Go to your server list and select Wynncraft then click edit. Switch server resourcepacks to enabled and see if it helps at all.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Dar-krusos** [comment]
Try right-clicking when you are in the class selection menu. This should bring up your classes. If it doesn't, please reply back here.

**Comment by CubeRoot06** [comment]
![2016-01-13_17 46 14](https://cloud.githubusercontent.com/assets/16751761/12382949/12de45ac-bd6e-11e5-9520-9622e51a510c.png)
For some reason, whenever I enable server resourcepacks, it causes my Minecraft to stop responding, resulting in me losing connection to the server with the message: 'Timed out'. I had to manually download the Wynnpack and disable server resourcepacks to solve this issue. I haven't tried right-clicking in the class selection menu, so I may try that.

**Comment by Trixter313** [comment]
Hmm, another user had issues with the resourcepack lagging and disabling animations helped them. Try having the server resourcepack on and turning animations off in the video settings.

**Comment by CubeRoot06** [comment]
Well, I DO have OptiFine as well, and I have all my animations disabled along with it. Is there anything else I should do?

**Comment by Dar-krusos** [comment]
Try deleting Wynncraft from your serverlist and re-adding it. This worked for one person.

Another suggestion, that worked for some people, was to find a newer/diffeeent version of the minecraft launcher

**Comment by CubeRoot06** [comment]
![2016-01-27_17 38 57](https://cloud.githubusercontent.com/assets/16751761/12630963/00ef78aa-c51d-11e5-9b4c-c2ea71d446a3.png)
I tried downgrading to 1.8.3. Unfortunately, the problem persisted regardless. Any other suggestions?

**Comment by Trixter313** [comment]
@CubeRoot06 if you were following Dar-krusos's advice directly above, they mean the actual launcher, not the Minecraft version. It is recommended to always use the latest stable Minecraft version, currently being 1.8.9. What the suggestion is talking about is located here https://minecraft.net/download

**Comment by CubeRoot06** [comment]
@Trixter313 I forgot to read that advice. Thanks. So I just download the .exe version, right?

**Comment by CubeRoot06** [comment]
Okay, so I tried to download the old version of the launcher, still having this problem. At this point, I have no idea what to do.

**Comment by Trixter313** [comment]
If you're on Windows, the best version would probably be the .msi one. Not sure if that's the one you tried or not but it's seeming that it's not helping anyway. Does disabling the downloaded resourcepack and enabling the server side one still crash? That seems odd in itself and I wonder if it has anything to do with the issue.

**Comment by Trixter313** [comment]
@CubeRoot06 if no suggestions for you so far work, please open a new issue specifically for your issue as I believe this original issue has been resolved. Thanks!
