### ISSUE TITLE
Can't choose a class. Trying to play since it came out!

### ISSUE THREAD

**Issue by Frogicis** [Wynncraft/Issues#3522]
Hey, My IGN Is frogicis. I can't seem to join the acuatlly mmo servers. I choose a class and says try again and i try but nothing happens. Could you please fix this iv'e been trying to play since it came out.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3139

Please direct any future comments to the original thread. Thanks!
