### ISSUE TITLE
Quest Placement Issue - Flight In Distress

### ISSUE THREAD

**Issue by Myoplex** [Wynncraft/Issues#3523]
I don't know if this is the correct place for my question but here goes anyways

I was doing the flight in distress quest and I died halfway through the quest on the "Pirate Airship/2nd Ship". When try and return to my death location it only takes me to the first Airship and I can not reach the second Airship. All the NPC's tell me everything I already know and it won't take me to the other Ship where I need to go to finish my quest. 
You can recreate this by dying anywhere on the second pirate airship. It will take you to Olux and once you go back to Cinfras, board the airship and you will be stuck on the first one again with no way to return
Is there any way for me to get to where I am supposed to be or will I be stuck forever? My in game name is Myoplex

**Comment by Dar-krusos** [comment]
Pretend that you're redoing the quest. You have to find the little boy again, which will trugger a teleport. Then talk to the Captain, go to your room, fix the colors, etc.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Klabautergeist** [comment]
@Trixter313 i have the same problem now but after the thing with the colors i cant rest anymore, so there is no pirate airship appearing

**Comment by Dar-krusos** [comment]
After the colors, you should walk around on the top of the ship for a bit because you will get teleported. You might've missed this trigger.

**Comment by Klabautergeist** [comment]
Okay, thank you very much. I will try it when i come home today.
Am 19.01.2016 1:35 vorm. schrieb "Vince Vo" <notifications@github.com>:
