### ISSUE TITLE
Temporary Weakening?

### ISSUE THREAD

**Issue by homerknight** [Wynncraft/Issues#3524]
I have recently began the Eye of the Storm quest in gavel. I got to the boss fight after you weaken Naragath. I ended up killing Naragath but in the pit of lava closest to the exit. I did not get the drop from the boss therefore I can not complete the quest. Am I supposed to defeat Naragath? Can I get a do-over (hehe) somehow? Please let me know. Thanks for reading! :D

**Comment by Troll2828** [comment]
if you killed him then you should be able to do /fixquests to get it back
