### ISSUE TITLE
Shadow of the beast.

### ISSUE THREAD

**Issue by ProGuitarist** [Wynncraft/Issues#3525]
When Tored said that he gave me Stringy Hair it never appeared in my inventory. I have finished everything else in the quest and I'm not able to collect the reward because I don't have the Hair.
IGN - ProGuitarist

**Comment by Trixter313** [comment]
Try typing /fixquests

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by ProGuitarist** [comment]
It is not currently resolved I still haven't finished the quest :/

**Comment by ProGuitarist** [comment]
I fixed it! Thanks for your help! :D
