### ISSUE TITLE
Toggle Blood Command

### ISSUE THREAD

**Issue by LarryRULEZ1** [Wynncraft/Issues#3526]
In short, when you do /toggle blood, it's supposed to stop all blood; however, it doesn't even reduce blood. The blood particles cause a lot of lag when you are fighting a boss with a big party. I die frequently due to the fact that I can't toggle blood. I'm sure many people can agree with me. I've also tried turning off ALL particles, but the blood remains. I don't know if there's a fix to this.

**Comment by Trixter313** [comment]
I just tested and it should be working now. No blood here.
