### ISSUE TITLE
Teleporter in Belua the Unquenchable's prismarine water mini dungeon boss room

### ISSUE THREAD

**Issue by sicklylemon** [Wynncraft/Issues#3528]
Loving the mini dungeon things you can find through Gavel such as the Fire mini dungeon outside of Thanos but I've found the teleporter/blacked out cave part at the end of Belua's boss room wont teleport me out to the start of the dungeon.
![2016-01-04_19 01 57](https://cloud.githubusercontent.com/assets/16394526/12086553/051f9828-b317-11e5-9076-bee7c397bb30.png)
![2016-01-04_19 12 22](https://cloud.githubusercontent.com/assets/16394526/12086581/3ff9895e-b317-11e5-9596-810d5c4108f1.png)
I've also found that you can enter to the unblocked area outside of the boss room by swimming through the water at the sides of Belua's room.
![2016-01-04_19 12 47](https://cloud.githubusercontent.com/assets/16394526/12086602/70a9b754-b317-11e5-9ab5-6f2ec03c244a.png)
![2016-01-04_19 13 02](https://cloud.githubusercontent.com/assets/16394526/12086612/7d88210e-b317-11e5-9c80-024076558a3e.png)
![2016-01-04_19 13 07](https://cloud.githubusercontent.com/assets/16394526/12086613/7ed8d698-b317-11e5-97ec-059e0e8e579c.png)

**Comment by Trixter313** [comment]
Doing it now should work normally, due to the servers being more stable and less laggy. If you still experience this, simply comment below and I'll reopen it. Thanks!
