### ISSUE TITLE
Guild Stats Command

### ISSUE THREAD

**Issue by Tobyshaggs** [Wynncraft/Issues#3529]
Whenever I, or any of the guild members of the guild I am in try to do /guild stats it doesn't come up; and there isn't any error message. Is this a bug, or is it because the content team is working on the new guild interface?

**Comment by HeyloLP** [comment]
i think it's /guild list

**Comment by Tobyshaggs** [comment]
That's a different command that /guild stats
The /guild stats command should tell me the stats of the entire guild, including guild level, xp percentage, and some other things. While the /guild list command just tells me the position of xp donation for all of the guild members.

**Comment by HeyloLP** [comment]
then just look at them via the website

**Comment by DarkDemonDragon** [comment]
@HeyloLP LOLOLOLOLOLOLOLOLOLOLOL Honestly when was the last time you checked stats on the website? It hasn't been accurate for a long time.

**Comment by Trixter313** [comment]
Are you still experiencing this today? Many guild issues were fixed in the recent patch and hopefully this is one of them. Report back here!

**Comment by DarkDemonDragon** [comment]
Still an issue.

**Comment by YunoFGasai** [comment]
I believe they removed that command because of all the guilds that glitched and the guild limbo bug.
