### ISSUE TITLE
Typo in Quest

### ISSUE THREAD

**Issue by Hibbel** [Wynncraft/Issues#3531]
In the lv 49 Quest "An Iron Heart Part I" is a typo after you started it. The guy wants to have 1 Mechanical piece. After the Quest startet and you talk again to him he says he wants 2 pieces.
![2016-01-04_16 34 37](https://cloud.githubusercontent.com/assets/12662151/12093072/186d90f8-b301-11e5-9c6a-a98cc9187e58.png)

**Comment by HeyloLP** [comment]
yeah i know un many quests there are these sort of bugs but you only need 1

**Comment by Moe-Ronickah** [comment]
Fixed!
