### ISSUE TITLE
issues with the skill point

### ISSUE THREAD

**Issue by NinjaWaffle61016** [Wynncraft/Issues#3532]
![2016-01-04_10 59 11](https://cloud.githubusercontent.com/assets/16542979/12094105/c1a67b44-b2d4-11e5-8398-efaaed48ce10.png)

my level is 46 and for some reason there are only 69 skill points I can used. my friend that is lower lvl they all have more skill point than me. someone need to fix this

**Comment by Trixter313** [comment]
Try taking all your armor off. Armor can affect skills so some piece(s) might be subtracting skill points.

**Comment by NinjaWaffle61016** [comment]
I try taking my armor off, the amount of skill point is still around the same

**Comment by meatloaf4311** [comment]
I know this can be expensive, but you could try to do a skill reset, its the only short term solution that may work. Otherwise you will just have to wait until its fixed
