### ISSUE TITLE
Wrong placed questbook-icons on the map

### ISSUE THREAD

**Issue by MineJallerXD** [Wynncraft/Issues#3535]
I found 2 wrong placed quest books on the Worldmap:
The first one should be at the house where I marked it
![bug_report_map_quest1](https://cloud.githubusercontent.com/assets/16543458/12094642/eb669c54-b309-11e5-88a7-e10ceee61c4a.PNG)
 The second one is double placed and one should be removed (you can only see it if you zoom in).
![bug_report_map_quest2](https://cloud.githubusercontent.com/assets/16543458/12094692/4ae120d2-b30a-11e5-99c9-8149854ccc19.PNG)

**Comment by thecoolkogut4** [comment]
@Trixter313 the first book got fixed (moved to the house). I can't find the duplicate book on the map atm (might be there but I can't find where it is according the the picture)

just tagged you to see if you can find the book & lock this. 

posting b/c of the recent website map update
