### ISSUE TITLE
Flying tree in the quest "Taproot" in the non decayen forest

### ISSUE THREAD

**Issue by MineJallerXD** [Wynncraft/Issues#3536]
I found this flying tree at the shown coordinates:
![2015-12-23_17 09 23](https://cloud.githubusercontent.com/assets/16543458/12094762/d5f5680e-b30a-11e5-91fa-9f02b4b61e75.png)
![2015-12-23_17 09 16](https://cloud.githubusercontent.com/assets/16543458/12094785/f547e01a-b30a-11e5-9f31-33e7a9388613.png)

**Comment by Moe-Ronickah** [comment]
Fixed.
