### ISSUE TITLE
If you are identidieing stuff and the server restarts you loose your stuff

### ISSUE THREAD

**Issue by ichwichseimmer** [Wynncraft/Issues#3538]
So I lost my Abysso Galoshes boots which I need for a quest now

**Comment by TrashcanMan** [comment]
Do /fixquests and you should get them back.

**Comment by Dar-krusos** [comment]
The title is pretty explanatory. This isn't really a bug, as you shouldn't be trying to identify anything when a server restarts. Those server restart notifications are there for a reason.
