### ISSUE TITLE
I cant move

### ISSUE THREAD

**Issue by njziebold** [Wynncraft/Issues#3541]
i am on your server with my level 29 mage and i cant move and these are my cords: X:
-649 Y:124 Z:-1067 
P.S. i tried teleporting and i cat get out
![image](https://cloud.githubusercontent.com/assets/16548890/12103744/168658da-b313-11e5-8009-9660796ed543.png)

**Comment by njziebold** [comment]
i meant cant get out not cat get out

**Comment by TrashcanMan** [comment]
If you're stuck in a block or something, do /kill with at least 3 soul points. If this fixes your issue please hit the "Close Issue" button at the bottom. Thanks!
