### ISSUE TITLE
Zhight Island Odd Smelling Crate glitch

### ISSUE THREAD

**Issue by LittleMrsMuffet** [Wynncraft/Issues#3542]
I was doing the Zhight Island quest and i talked to Czytash to get the crate for Zhight and I got it, then i headed over to Zhight to give him the crate and a message said, Please empty your inventory. So I did so, and i let him talk, then it said his text, and didn't give me the items, and it just said to get the package from Czytash, but when i go back to him, it says he already gave it to me. I am stuck in that quest, and cannot finish, Please help.
Ty
~LittleMrsMuffet

**Comment by Trixter313** [comment]
Try the command /fixquests

Hope this helps!
