### ISSUE TITLE
"Multipath Prototype" Quest

### ISSUE THREAD

**Issue by SpitfiresThunder** [Wynncraft/Issues#3543]
So, I just logged into server 17 to finish one of my quests, and leveled up because of it. I went to check my quest-book to see the new quests I had available, and I got this;

http://oi66.tinypic.com/2zp6u1j.jpg
http://oi64.tinypic.com/2qlgz7p.jpg

This quest is level one, asking me to talk to the NPC "Guy1" in a location FAR outside of the Wynncraft map.

**Comment by TrashcanMan** [comment]
It's probably a test quest that the content team forgot to remove...
Judging by the name I'm assuming it's a test for quests where you can make choices like Iron Heart II.

**Comment by SpitfiresThunder** [comment]
Alright, that makes sense. It appears to have disappeared now as well, so this can probably be closed.
