### ISSUE TITLE
did acquiring credentials quest broken

### ISSUE THREAD

**Issue by xXMLGCATXx** [Wynncraft/Issues#3544]
I cant do the quest I started and I cant talk to the preculiar old man

**Comment by Troll2828** [comment]
Go talk to the guard first and then talk to the old man, I had that same error.

**Comment by xXMLGCATXx** [comment]
what guard?

**Comment by xXMLGCATXx** [comment]
I talked to all npc at airbase

**Comment by Troll2828** [comment]
i suggest you watch this to better understand what you have to do : https://www.youtube.com/watch?v=JAbWFHvuWqc
