### ISSUE TITLE
Flight in Distress error

### ISSUE THREAD

**Issue by NatsuSchultz** [Wynncraft/Issues#3545]
After killing the Pirate Queen and going down the escape hatch, I arrived to a strange black box with a completely useless tripwire inside, I do not think this is part of the quest, mind fixing?

**Comment by Jenoma** [comment]
i got that error too, i did /kill but quest is broken now

**Comment by NatsuSchultz** [comment]
A bit upsetting since I /kill (ed) and went all the way back through the extremely colorful, but inconvenient quest instances to arrive to the same box :/. Anyways, hope I'll be notified when its fixed.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3475

Please direct any future comments to the original thread. Thanks!
