### ISSUE TITLE
Shattered Minds Broken

### ISSUE THREAD

**Issue by Phoenix79800** [Wynncraft/Issues#3546]
Hello,

I have found the village in the strange forest when you are high, and I have talked to likeru and been told to find the rabbit, but my quest book never updates and I can't go up the ladder because it says "It seems rude to just barge into someones house like that" so I cannot complete the quest, would it be possible to fix this?

Thank you,

Phoenix7980

**Comment by Trixter313** [comment]
What does your questbook currently say?

**Comment by Trixter313** [comment]
Follow this video as a guide to ensure you're doing everything correctly and your issue should be resolved. https://www.youtube.com/watch?v=nwk9pDSO74U
