### ISSUE TITLE
Air Base Wall bug

### ISSUE THREAD

**Issue by dotGenco** [Wynncraft/Issues#3547]
Next to arch, there are buttons, 5/6 of them doesnt do anything, but this one moves this side of the pillar up, not sure if intentional or bug.

![2016-01-05_09 39 17](https://cloud.githubusercontent.com/assets/16554267/12110047/e74656aa-b390-11e5-904f-106fa56b304c.png)
![2016-01-05_09 39 20](https://cloud.githubusercontent.com/assets/16554267/12110048/e7498730-b390-11e5-9d45-8bbcd623ac34.png)
![2016-01-05_09 39 14](https://cloud.githubusercontent.com/assets/16554267/12110049/e7509476-b390-11e5-88f7-c1063c4cb93d.png)

**Comment by Trixter313** [comment]
It's most likely an easter egg or just functional decoration. I don't see it hurting anything though.
