### ISSUE TITLE
Spawn after Death

### ISSUE THREAD

**Issue by Arreme2000** [Wynncraft/Issues#3549]
Toady, I was fighting some orcs on GAVEL when i died because of them. When I respawned, I appeared on the START of Wynncraft, inside the cart. It was quite annoying for me, and i was wondering if this could be a bug or something and if you culd fix it.
Thanks.

**Comment by BlahBlah161616** [comment]
If you were teleported during a quest you were tped there because all of those areas are actually located outside of the map in many areas.
