### ISSUE TITLE
Armor losing enchant

### ISSUE THREAD

**Issue by yorimtschgi** [Wynncraft/Issues#3550]
I teleported to Llevigar with a scroll and my, I think its called pelier helmet lost it's enchants, it says like {"type":"WATERDEFENSE","percent":72},{"type":"EARTHDEFENSE","percent":106}]}
I can't read more since it goes out of the screen. I would really like to have that back so can you help me?

**Comment by SkySaito** [comment]
It's a little bug, you didn't lost your Pélier, don't worry. Try relogging on the server or change servers. It should work.

**Comment by yorimtschgi** [comment]
Ty it worked
