### ISSUE TITLE
Flight in distress got a bug

### ISSUE THREAD

**Issue by Jenoma** [Wynncraft/Issues#3553]
I was doing the Flight in distress quest, than I killed the queen , got the ring, tried to escape the ship and then i was teleported to Vanilla.
Now the quest can't be done back... What should i do?

**Comment by ThatChudley** [comment]
I am in the same position, my in game name is That_Chudley.

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul point should teleport you to the nearest visited respawn point.
