### ISSUE TITLE
Corruptor too hard?

### ISSUE THREAD

**Issue by Kriminus** [Wynncraft/Issues#3555]
I cannot defeat the Corruptor of worlds because he always heals up to full health. I would have to deal about a hundred times more dmg to be even close to winning him. Is this a bug?

**Comment by DarkDemonDragon** [comment]
No this is not a bug. Most people cannot do Corruptor of Worlds on their own even with the best gear for their level. It's recommended to be in a party of at least 3.

**Comment by Kriminus** [comment]
Ok ty
