### ISSUE TITLE
stuck in a wall

### ISSUE THREAD

**Issue by StiLaZz** [Wynncraft/Issues#3557]
Hello Wynncraft-Team,
I have played the all day on your Server.
But now I'm stucking in a wall.
The coordinates are: 
x=427,300
y=26,000
z=-3484,300
My ingamename is: StiLaZz

Ps: pls fix this 

Best regards: StiLaZz

**Comment by jensiwaa** [comment]
You can use /kill to get out if you don't get help any time soon.

**Comment by StiLaZz** [comment]
Ok thank you very much :D

**Comment by DarkDemonDragon** [comment]
If your issue is solved now please close this.
