### ISSUE TITLE
Website Achievements don't work with VIP+ Classes

### ISSUE THREAD

**Issue by Corneille198** [Wynncraft/Issues#3558]
Hello, I have noticed that on the website you can see the achievements you got. https://wynncraft.com/player/Corneille

But what see is that VIP/VIP+ classes doesn't count.
The Warrior Master I doesn't count for a Knight but Only Warrior, While I'm level 31 atm.

I don't know if it is a bug, but I just wanted to report it.

Thanks for listening and have a nice day!

**Comment by Moe-Ronickah** [comment]
Player stats page has been remade.  This page type no longer exists.
