### ISSUE TITLE
Archer Class Glitch Deleted? 

### ISSUE THREAD

**Issue by Satsuki9** [Wynncraft/Issues#3560]
When I went on wynncraft a while ago I saw that my level 41 archer was deleted. I would appreciate it if you could get it back. Last time I was on with him was Dec. 31. Username is Satsuki9.

**Comment by Satsuki9** [comment]
I even made a new one just to see if my items would come back. They didn't. PLS HELP

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so we can't do much in this situation. You can delete classes now so you might have accidentally deleted it. There's no way to know what happened for sure. If you ask around, some nice players might be able to give you some items to help out. I hope this doesn't happen to you again!

**Comment by Satsuki9** [comment]
I know for a fact i didn't delete it. Your saying that YOUR server messed up and now the people who have had this happen to them have to pay for it. LEVEL 41!!! LOST ALL MY STUFF BECAUSE OF NO REFUNDS. wow...... thought a server like this, growing, would have done something to players who have had this happen. 5 liquid emeralds, one of the best bows in the game that i couldn't use because it was to high of a level for me (traded someone for it). OK welp I'm done with this god awful server

**Comment by Trixter313** [comment]
You're actually the first and only person to have reported their entire class getting deleted. I suggest making sure no one else uses your account/knows your login info incase someone logged in as you and might have accidentally did it. Like I said, there's no way to know for sure whether it was caused by a user or the server. Hopefully some people will give you some items to help you get back on your feet.

**Comment by Satsuki9** [comment]
Sorry dude my brother got mad for the class being deleted. He played on my archer (sometimes) when we still had it. I'm guessing he didn't think that the hacker could have done it. My account was hacked about 2ish weeks ago. This account was banned off mineplex (we worked it with with mineplex and we are unbanned) so I'm guessing it wasn't from Wynncraft messing up unless the server has that glitch. I deleted his comment because it was a little rude. I'll apologize for him. So most likely the hacker deleted my class. 
Last we were on with the level 41 archer class was Dec.30 or 31. The hacker was known on my account on around Jan. 4. I have 2 questions. 

A) If I make a new archer class, will I still have all the things in my vault? (I have good bows i never got to use because i want a high enough level for them and i had tons of emeralds) 

B) Are you sure there is nothing you can do about it being deleted? 
Thanks for your help.

**Comment by Trixter313** [comment]
As for the first question, all items in your bank should still be there. =)

Wynncraft has an extremely strict no refunds policy that as far as I know, they haven't broken in the ~3 years they've been running. I really don't think there's anything that can be done about this unfortunately. I hope it isn't too much of a hassle rebuilding the lost class. I hope you don't get hacked again also! Good luck!

**Comment by Satsuki9** [comment]
Ok thanks! I guess ill start going to get my levels back
