### ISSUE TITLE
Emeralds in inventory mess with quest rewards

### ISSUE THREAD

**Issue by HurensohnDeinerMutter** [Wynncraft/Issues#3562]
Today i made the headless hunt quest. The chat said i got 5120 emeralds (80 emerald blocks) but i just got 1536 emeralds (24 emerald blocks). Please fix it. IGN: _Zohan

**Comment by Trixter313** [comment]
Did you have any emeralds in your inventory already, before you finished the quest? It's a known issue that if you finish a quest with emeralds in your inventory you might not get the correct amount so I suggest making sure you don't have any emeralds in your inventory when you finish a quest to maximize your chances of getting the correct amount.

**Comment by Moe-Ronickah** [comment]
Closing: no response from OP.
