### ISSUE TITLE
Vanilla server glitch caused item loss

### ISSUE THREAD

**Issue by SpitfiresThunder** [Wynncraft/Issues#3564]
Please read this whole thing before tagging it as a repeat.

This bug is really starting to piss me off. So far, I've lost two legendary chestplates (One Mummy's Rag, and another Gold one which I forget the name of), and a pair of rare boots (Talaria). The chestplates I don't mind, seeing as they are now well below my level. However, my latest lost (the Talaria) is really getting on my nerves. Not just because these boots were useful, but also because of the way in which I lost them.

I had been in the Jungle Village on server 9, and I was going to start the "Out of my Mind" quest. So, I switched out my Abysso Galoshes for my Talaria (which gave me +20% walk speed and +17% loot bonus). I traded them without using shift-click, but they traded out fine. I didn't lose either of them, and was now indeed wearing the Talaria, with the Galoshes safely in my inventory. So I made my way to Troms. Everything was going fine; The server was still operating, I could still use spells, hurt mobs, move, etc.. My life and mana indicates (the numbers) were still on and refreshing, meaning that the server was updating and, so far, working as it was supposed to.

So, I make it to the Troms gate, and suddenly everyone gets kicked. The world became Vanilla, so I simply let it time me out. Getting back on, I went to the bank to turn in some emeralds. Doing so, I noticed a certain spot in my inventory was open: The area in which I put my Abysso Galoshes. I panicked, and checked my armor slot, and was surprised to see that the Galoshes were actually on my feet. My insanely useful Talaria, however, were nowhere to be found.

These boots gave me +20% Walk speed, and +17% Loot bonus, which ended up being higher than my Treasure boots. I went back to look for them, and of course, had no luck finding them.

Sure, I would blame myself if the server had crashed while I was moving them with my mouse, because that's actually understandable. What isn't acceptable, however, is the fact that the server essentially STOLE the my Talaria RIGHT OFF OF MY FEET.

Now, I'm not expecting a refund, seeing as Wynncraft won't offer them. Which, I mean, is understandable, considering half the time they'd be replacing items that were lost due to their server screwing up. But seriously, nobody likes it when a server fails at THEIR EXPENSE. I'm not about to have another Legendary or Rare armor piece or weapon STOLEN FROM MY INVENTORY when it's clearly safely in it.

**Comment by oblivian126** [comment]
Same happened to me just now with my legendary leggings they were in the bank and now they are not , I did take a screenshot right after the crash which probably doesn't change anything as wynncraft won't give back items lost because of their crashy servers which is totally fair .

**Comment by DarkDemonDragon** [comment]
Unfortunately this happens. I really don't know what's up with the recent sudden crashes, but players have lost things as expensive as Bob's Mythical weapons.

**Comment by SpitfiresThunder** [comment]
Yes, I'm aware that this "Happens", but the way that I lost my Talaria, it shouldn't. If they're in my inventory or on my body, and the server is still updating after the point I put them there, I should lose them.

Again, if it did something like this while I was manually moving my items, I would understand it. It was out of my inventory, I was "carrying it", and the server crashed causing me to throw it. But, that isn't what happened. And so, I don't understand it.

**Comment by Trixter313** [comment]
The world should no longer go into vanilla as the servers have stabilized so this issue shouldn't happen again.
