### ISSUE TITLE
Stuck on respawn (entering a server)

### ISSUE THREAD

**Issue by Gualdim-Pais** [Wynncraft/Issues#3565]
Every time you enter a server it checks/downloads the resource pack and you get stuck for 5/10 seconds, you get stuck but not the mobs in the "area", so while the servers are checking the resource pack and your are stuck the mobs kills you.
The players should have invisibility or other thing while the servers checks/download, it's not fair being killed because of it, the servers are crashing very often so the chance of this happen is very high.

**Comment by Trixter313** [comment]
This would probably fit in better and get more attention on the forums, in the suggestions section, here: https://forums.wynncraft.com/forums/general-suggestions.69/
