### ISSUE TITLE
bows not usable

### ISSUE THREAD

**Issue by GizmoTurtulez** [Wynncraft/Issues#3567]
My 2 Bow of Wisdoms are not working, and didn't need to be identified when I joined after the update. 
![2016-01-05_21 18 21](https://cloud.githubusercontent.com/assets/16569462/12134225/d39fda9c-b3f2-11e5-9391-d96798383961.png) 
![2016-01-05_21 18 18](https://cloud.githubusercontent.com/assets/16569462/12134234/e8d91b62-b3f2-11e5-866f-7a4a0354625e.png)

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3161

Please direct any future comments to the original thread. Thanks!
