### ISSUE TITLE
Flight in Destress | Stuck

### ISSUE THREAD

**Issue by Zevys** [Wynncraft/Issues#3568]
IGN: Zevys Im doing the Flight Destress quest and I defeated the Pirate Queen and I hoped on the coal to be teleported to Captain Ackbars ship and... Im not being teleported. Staff please tp me out please.

**Comment by Trixter313** [comment]
Have you tried switching worlds?

**Comment by Zevys** [comment]
I have

**Comment by Zevys** [comment]
I spoke to [Mod] Prezule lastnight and I switched servers, even /killed to get out, I somehow re-did the quest and then got stuck in the same position. Btw I am kit archer and the coal-block teleporting area there is a hole where I can get out Is there supposed to be a hole in the teleporting area?

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3475

Please direct any future comments to the original thread. Thanks!
