### ISSUE TITLE
Stuck in /class(kind of)

### ISSUE THREAD

**Issue by Hankyana** [Wynncraft/Issues#3569]
The first time I spawned I spawned on top of a forbidden area, or x-0 z-0. There were signs all over saying to keep out. I logged into a different server, and was trapped with the villager. There was a threat on the sign left by Salted. I logged off again, and then was stuck in a block and somehow I could fly like the lobby. I found my way to Nesaak, and Detlas, and couldn't read chat except the guidelines and people using shouts/xp bombs. I can't play the game, please unstuck my class.

**Comment by Trixter313** [comment]
Try enabling the server resourcepack by going to your servers, selecting Wynncraft and then click edit. Change server resourcepacks to enabled. Many people were seeing that island with the signs when they didn't have the resourcepack enabled and enabling it helped them.

**Comment by Hankyana** [comment]
http://prntscr.com/9mpenu It's been enabled.

**Comment by DarkDemonDragon** [comment]
Screenshots? :3 lol not gonna lie I want to know what that area looks like >.<

**Comment by Hankyana** [comment]
I don't think it would be appropriate to give you a view of an area that's been blocked off.

**Comment by Trixter313** [comment]
Are you still experiencing this issue? I'd hope it would sort itself out by now. Report back with your response!

**Comment by Hankyana** [comment]
Yep, its been a month, changed my name, admins don't even bother to look at it, still can't play.

**Comment by Trixter313** [comment]
It's been 20 days, is this *still* occurring? Thanks!

**Comment by DarkDemonDragon** [comment]
Is 20 days a rule you're going by now? I'm seeing a trend XD

**Comment by Hankyana** [comment]
Still occuring

**Comment by DarkDemonDragon** [comment]
Test if your classes are ok by joining the Nether.

**Comment by Odnod** [comment]
have you tried typing /kill? that can often fix player problems like this.

**Comment by DarkDemonDragon** [comment]
@Odnod that only works if he is on a character. For players that are clearly stuck in some limbo area (noted by lack of level or items) they typically cannot use ANY commands whatsoever other than returning to the lobby.

**Comment by Odnod** [comment]
@DarkDemonDragon ah, ok then.

**Comment by Moe-Ronickah** [comment]
Closed: no response by op.
