### ISSUE TITLE
Clocktower plus Mage = crash, crash, and more crashes.

### ISSUE THREAD

**Issue by Rujala** [Wynncraft/Issues#3570]
When I'm trying to kill one of the bosses in the clocktower (aka Mystery of the Clocks easter egg) my Mage crashes the server. Either it's Ice Snake or Meteor that crashes it, but it's unplayable. I can't kill a boss with only my normal attack that deals 30 damage. :/

**Comment by Trixter313** [comment]
It was previously reported that the meteor spell was causing this but it should be fixed now.
