### ISSUE TITLE
Can't leave guild glitch

### ISSUE THREAD

**Issue by superdswimmer** [Wynncraft/Issues#3572]
This has been happening for over 3 months now and im kind of annoyed it hasn't been fixed. Since 3 months ago i left my guild (Kangronomicon) to try to visit Hippies of wynn. However of course it didn't work when i've tried to join any guild all it says is that im already in a guild. Ive tried doing /guild leave but it says you arent in a guild ive gotten a member of my old guild to kick me out but it says player is not in a guild. I thought this would be fixed in the gavel update or a followup update but its been happening since early november. I would like to join my guild again if possible but if not then well...
Username:superdswimmer

**Comment by lXetnosl** [comment]
i just cant leave my guild... I do /guild leave... then theres the warning about 3 soul points... the sign opens and i type yes. and thats it. I could do it as often as i want, I won't be able to leave. and my leader changed his name and is not able to do anything

**Comment by lXetnosl** [comment]
lol i just tried again and it worked xD

**Comment by Trixter313** [comment]
Are you still experiencing this issue now? A recent patch said it fixed some guild related things so hopefully this was one of them. Report back with any updates or comments!

**Comment by Trixter313** [comment]
I'm going to assume that the issue is now resolved due to no response. If anyone is still experiencing it, simply comment and I can reopen the issue for you. Thanks!
