### ISSUE TITLE
Spell Damage Glitch

### ISSUE THREAD

**Issue by Wyzards** [Wynncraft/Issues#3574]
I was doing the quest Craftmas Chaos and everything was fine, and then I got to Santa. I started fighting him and I noticed that my left click attacks did no damage. It did damage to other mobs but not him. Then I opened up my Character compass and I noticed that all of my spells said that their damage was 0-0. Is this a glitch or is it part of the quest? Please help! <3 Wyzards

**Comment by Trixter313** [comment]
What weapon and armors were you using? The issue should have fixed itself by now. Report back and changes or comments!
