### ISSUE TITLE
The Shadow of the Beast

### ISSUE THREAD

**Issue by kadaj353** [Wynncraft/Issues#3578]
In the quest, "The Shadow of the Beast" I accidentally dropped the hair received from the farmer which was the "first piece of evidence" upon dropping it, it reverted to a normal piece of string, and I'm now unable to complete the quest. If you could help it would be greatly appreciated. My IGN is Kadaj353.

**Comment by TrashcanMan** [comment]
Have you tried /fixquests?

**Comment by kadaj353** [comment]
I was unaware that was a command. Thank you very much for your time and I
apologize for any inconvenience.

**Comment by TrashcanMan** [comment]
If it works, we would appreciate it if you could hit the "Close Issue" button at the bottom. Thanks!
