### ISSUE TITLE
Skill Points

### ISSUE THREAD

**Issue by VoidWyvern** [Wynncraft/Issues#3581]
Hey, i was hoping i could get someones help on this. I logged into the server and i was in the update zone so i tried to use my skill points. The problem was that i lost quite a bit of them because they wouldn't register on anything but agility. So now i'm a level 44 assassin with harshly any skill points So i was hopeing i could get help. Though i am not sure if anyone else is having the same issue. If anyone who can help me personaly is reading this my username is Void_Wyvern

**Comment by RedEagleGames** [comment]
i lost  2 of my dexterity points i cant use my weapon now and ive been using it a lot

**Comment by Trixter313** [comment]
If you used all of your skill points on one thing the only options are leveling up to get more or doing the quest Tower of Amnesia so you can buy a skill reset scroll. Skill reset scrolls do cost 1 LE so they are quite expensive though.

**Comment by ItsYourPlay** [comment]
Can someon help me I have been so Agillity skilled to 30 times but its still on level 0 and i go not higher it doesn't metter when i skill it

**Comment by ItsYourPlay** [comment]
My ingame name is ItsYourPlay
 and i am a VIP on the server pls help me when you know a answer

**Comment by Trixter313** [comment]
@ItsYourPlay please start another issue, thanks!
