### ISSUE TITLE
Hi this EthanHyun

### ISSUE THREAD

**Issue by EthanHyun** [Wynncraft/Issues#3582]
Hi, I was trying to identify an armour(Ragni's Mail) and the server crashed and I lost the chestplate.. please give it back to me :( I had this armour from before the update! :'( IGN: EthanHyun

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so we can't do much in this situation. I hope this doesn't happen to you again. Staff is working on the random crashes which should help.
