### ISSUE TITLE
Bugged quest

### ISSUE THREAD

**Issue by TheRealMalmOo** [Wynncraft/Issues#3585]
I did first part in quest "heart of LLevigar",but when im doing second part nothing happens,i watched some videos on YT and doing all like in but nothing happens,quest book just dont update... #pls4help 
Video is here: https://www.youtube.com/watch?v=x8F83d80PuE&feature=youtu.be

**Comment by Trixter313** [comment]
Doing the quest now should work because the servers have stabilized. This was most likely caused by lag.
