### ISSUE TITLE
WHY

### ISSUE THREAD

**Issue by Yz0x** [Wynncraft/Issues#3589]
i was have ban for no reason and i don't know who give this ban please help me Username:Yz0x

**Comment by meatloaf4311** [comment]
Why

**Comment by Yz0x** [comment]
i was have ban for no reason and i don't know who give this ban please help me Username:Yz0x

**Comment by DarkDemonDragon** [comment]
This is not the place for ban appeals. Please go to the ban appeal section of the forums and close this.

**Comment by Trixter313** [comment]
Like DarkDemonDragin said, read this first https://forums.wynncraft.com/threads/%E2%9C%8E-appeal-submission-guide-%E2%9C%8E.89247/ then make a report here https://forums.wynncraft.com/forums/ban-appeals.84/create-thread

Thanks!
