### ISSUE TITLE
Yay, another Wiki Issue (Not Saving)

### ISSUE THREAD

**Issue by meatloaf4311** [Wynncraft/Issues#3590]
Hey all, the wiki progression with the Gavel Update halted when a new bug erupted on 1/1. For some reason saving changes doesn't work. @Tama63 I think has to fix this personally. Hopefully can be resolved soon

**Comment by GAsplund** [comment]
Yup, I cannot log in to the wiki either. Do not log out even if it tells you to. Something seems to be broken with the cookies system.

**Comment by Trixter313** [comment]
Are you still experiencing this issue? Should be fixed by now.

**Comment by Moe-Ronickah** [comment]
Issue was resolved.
