### ISSUE TITLE
my legendary endgame items and maelstrom bow all got unidentified wen my mc crashed an when i went to indentify them it didnt registrate them as legendary items 

### ISSUE THREAD

**Issue by magm4cube** [Wynncraft/Issues#3592]
![2016-01-07_23 28 49](https://cloud.githubusercontent.com/assets/16600916/12184706/3b7c767a-b597-11e5-8e88-ff2fb1a48ff4.png)
![2016-01-07_23 29 12](https://cloud.githubusercontent.com/assets/16600916/12184711/4310b392-b597-11e5-8628-159307f4641d.png)

ALL OF THIS UNUSABLE

**Comment by TheChampion879** [comment]
Same thing has happened to me, except I switched servers and now everything is unidentified. Cant identify it, although the armor is still wearable, it does not do anything. Switching servers/classes/towns didnt help, and I cant identify anything.

**Comment by survivalmonkney** [comment]
All of my items (Armor, weapon, accessories, etc.) Got unidentified and I can't reidentify them. I was back to 10 health, though i was wearing the unidentified armor. It was fine yesterday, and it seems loads of people are having this problem, admins/mods/everyone probably broke something

**Comment by TheChampion879** [comment]
It was really sudden, one second it was working fine, then the next everything is broken. Not sure what caused it.

**Comment by magm4cube** [comment]
All my time for this finally lvl 75 and now THIS

**Comment by ItzGhostBruh** [comment]
Imagine trying to do a quest at the time and it breaks.. You die instant cause of low health.

**Comment by survivalmonkney** [comment]
Did this happen like 30 mins ago, because suddenly everyone is having this problem

**Comment by Eribear** [comment]
Having the same problem- all armor and weapons were identified yesterday, logged in today- all are unidentified and the item identifier can't identify them?

**Comment by magm4cube** [comment]
Exact thing happened to me

**Comment by ItzGhostBruh** [comment]
It happened to a lot of people

**Comment by magm4cube** [comment]
How can we contact the staff about this cuz a lot of people are having the
same problem

**Comment by survivalmonkney** [comment]
Only certain people broke though, everyone else near me was fine. Are we the chosen ones?

**Comment by ItzGhostBruh** [comment]
It's weird cause stuff on my other class everything is fine but on my main class what I had on at the time broke.

**Comment by ItzGhostBruh** [comment]
Chosen one of Wynn (and Gavel)

**Comment by survivalmonkney** [comment]
Yea, it was only my main class, i went on my other one and he was fine

**Comment by magm4cube** [comment]
I fkn hope not I just want to continue playing wynn

**Comment by ItzGhostBruh** [comment]
Lmao. Struggle real for us.

**Comment by WintryWarrior** [comment]
Same, I just literally got done doing Reincarnation, I turned in Bobs note, then the server crashes. I log back into a different server and every single thing of mine is unidentified, not only that but I lost the note and I have to re-kill bob again. :'(

**Comment by magm4cube** [comment]
It happened just now in light forest

**Comment by ItzGhostBruh** [comment]
It happened by Trom too.

**Comment by WintryWarrior** [comment]
I can't even open my bank.

**Comment by TheChampion879** [comment]
My bank works fine, and it was in Aldorei that this happened

**Comment by magm4cube** [comment]
We need to get some help from mods and the other staff

**Comment by magm4cube** [comment]
Does anyone know how to get to them

**Comment by Eribear** [comment]
I can open my bank- everything in there is fine, anything that was on my character is now unidentified and is unable to be "reidentified"...

**Comment by TheChampion879** [comment]
Salted is online right now, but he isnt responding to my messages

**Comment by GarBro** [comment]
I am too

**Comment by magm4cube** [comment]
Same here

**Comment by Eribear** [comment]
Oy vey

**Comment by GarBro** [comment]
I want my stuff back, most of my best diamond armpit was on me

**Comment by magm4cube** [comment]
Guys I'm gonna go to bed now mabey I'll talk a bit later bye

**Comment by Majesti** [comment]
This happened to me just now.. ;-;

**Comment by XionFakiez** [comment]
This happened to me as well oh sad days it is ;-;

**Comment by ItzGhostBruh** [comment]
Welcome to the group. Population everyone here.

**Comment by Elemika** [comment]
Happened to me as well. I hope it gets resolved somehow soon.

**Comment by ItzGhostBruh** [comment]
Hope we don't have to spend more Emeralds on this.

**Comment by XionFakiez** [comment]
I hope we actually get our items to work lol

**Comment by ItzGhostBruh** [comment]
Just don't understand why it happened.

**Comment by magm4cube** [comment]
I don't mind spending emeralds but just let it work again plz lord Grian

**Comment by ThePromisedLAN** [comment]
https://www.youtube.com/watch?v=qoAIwWgCLeQ&feature=youtu.be

Here's a video of it as well, in case you need it as well.

**Comment by ItzGhostBruh** [comment]
Struggle is real.

**Comment by magm4cube** [comment]
Nice skin thepromisedlan

**Comment by Moogly49** [comment]
Haha. All my shit got un-id'ed too. My rings are now glitched, I don't have them anymore. it's all good tho,, i'm sure they'll figure something out. GL to everyone getting their shit back!

**Comment by TheChampion879** [comment]
Network just went down, here to hoping the fix is on the way?

**Comment by MageEcho** [comment]
I was at full inventory when this happened. I my accessories when they glitched off me. This happened to both my assassin and archer. Please fix?

**Comment by Majesti** [comment]
R.I.P. Wynn

**Comment by Drakost** [comment]
Happened to everyone I guess...

**Comment by magm4cube** [comment]
Wohho the problem is fixed except now I quit Wynncraft for fucking ever
they reroled my entire fucking inventory to January 4 and that means royal
blazing amulet is gone half of my endgame armor is gone 10 fucking le are
gone quest items from all quests I did from 4. To now are gone and can't be
obtained again trough this class I do not accept their apology "oh we
screwed up but here is a 300% loot and xp bonus. I know they can fix it for
all of us they just need to come on and give us the items we once had
trough simple creativeeee mode fss those are just fucking wooden slabs
untill then I DUCKING QUIT BYE

**Comment by GarBro** [comment]
Same here, I don't even know if I have a screenshot of my inv but do those quest items do anything? If not I don't want them but I do want my armour and weapons

**Comment by survivalmonkney** [comment]
It said something like 'sorry, we screwed up, have 300% loot and xp bonus for 4 days, please forgive us' I didn't lose anything important except for time, though other people lost a lot more. If they broke everything and made people lose endgame stuff, they should give it back and not hope an xp bonus is going to make us forgive them

**Comment by magm4cube** [comment]
Exactly

**Comment by Trixter313** [comment]
This shouldn't happen anymore due to the servers stabilizing. Good luck!
