### ISSUE TITLE
Identified Items Became Unidentified

### ISSUE THREAD

**Issue by Elemika** [Wynncraft/Issues#3593]
When I logged on today, every single one of the items worn by my mage were unidentified, even though I had identified and had been using them for a while. 

My rings, bracelet, necklace, and wand remain as their models after after identification, and I can put on my armor without any problems. I can't place the accessories into their correct slots, however, nor can I use my wand. My armor doesn't give me any benefits; it's like I'm not wearing it at all. My wand doesn't show the typical "This item needs to be identified" message when I attempt to attack something with it.

 I tried to identify the items again, however that did not work. Logging out or switching servers fails as well. The items stay the same even after being put into my bank and into the inventories of my other classes, who do not seem to have this issue.

Is there anything else I can try to correct this issue?

![screenshot 178](https://cloud.githubusercontent.com/assets/13159080/12185000/979c0a82-b566-11e5-8363-38f339c8d719.png)

**Comment by Eribear** [comment]
Having exact same issue...

**Comment by GarBro** [comment]
Me too
