### ISSUE TITLE
All gear is unidentified [FIXED] [PLEASE CLOSE]

### ISSUE THREAD

**Issue by RubberDuckyNinja** [Wynncraft/Issues#3594]
RIP me I was trying to level up :(
Everything was okay 3 hours ago
![screen shot 2016-01-07 at 5 59 49 pm](https://cloud.githubusercontent.com/assets/16601189/12185477/22254fa4-b569-11e5-98e2-1ffbd7178791.png)
![screen shot 2016-01-07 at 5 59 59 pm](https://cloud.githubusercontent.com/assets/16601189/12185479/22284d94-b569-11e5-9954-f1fe7ab4140e.png)
![screen shot 2016-01-07 at 6 00 02 pm](https://cloud.githubusercontent.com/assets/16601189/12185478/22283390-b569-11e5-84af-59a4311d72aa.png)
![screen shot 2016-01-07 at 6 00 03 pm](https://cloud.githubusercontent.com/assets/16601189/12185480/22296896-b569-11e5-87b7-117a5728597c.png)
![screen shot 2016-01-07 at 6 00 06 pm](https://cloud.githubusercontent.com/assets/16601189/12185481/222be968-b569-11e5-9d87-4079652ae784.png)
![screen shot 2016-01-07 at 6 00 07 pm](https://cloud.githubusercontent.com/assets/16601189/12185482/222f58fa-b569-11e5-9e70-7c56568e0031.png)
![screen shot 2016-01-07 at 6 00 14 pm](https://cloud.githubusercontent.com/assets/16601189/12185483/223174fa-b569-11e5-8824-b7fe548890fd.png)
![screen shot 2016-01-07 at 6 00 15 pm](https://cloud.githubusercontent.com/assets/16601189/12185485/2236790a-b569-11e5-984c-7ae9c66b3f77.png)
![screen shot 2016-01-07 at 6 00 17 pm](https://cloud.githubusercontent.com/assets/16601189/12185484/22344b4e-b569-11e5-826f-799b3bad34c4.png)

**Comment by TrashcanMan** [comment]
So all your items were identified before and they all suddenly un-identified themselves? I guess you'll have to just identify them all over again, at your level it shouldn't cost too much.

**Comment by xElitaa** [comment]
...Trashcanman, in case you didn't see the chat in most of his screenshots, he CAN'T identify, and this is a widespread bug. The server is down and has been down for a while as I'm writing this, it is probably down for fixing.

**Comment by TrashcanMan** [comment]
Whoops, sorry, I missed that bit.
I would assume that the devs already know about a bug this game-breaking and are fixing it, all you can do is wait then.

**Comment by meatloaf4311** [comment]
You can close this now

**Comment by RubberDuckyNinja** [comment]
i just realised how to close :D
