### ISSUE TITLE
Glitched out Quest Item That Can't be Restored

### ISSUE THREAD

**Issue by pipman3698** [Wynncraft/Issues#3595]
Hi, i was playing Wynncraft and doing a lvl 35 quest. This quest is Wynnexcavation Site A. At the time the server was laggy and i turned in the paper that i was supposed to give to the quest MPC side the mine. I did the quest but while exploring it i crashed. When I got out my quest book says to talk to the MPC, and when i talk to him it tells me to give him the paper i translated. I didnt have it anyone since i already gave it to him when the server was lagging. I did /fixquests and / fixquest and /questfix and etc. nothing worked. I checked my inventory clicked every space, went on every character and the bank but nothing was found. If you could take this to note and help me fix this problem. This quest cant be complete unless i get the paper back which can't be gotten without you'r help Wynncraft. Thank you!

**Comment by DarkDemonDragon** [comment]
The only option at this point is to start a new class and have that character get to Wynnexcavation A. Then the 2nd character gets the paper, puts the paper in the bank, and then your 1st character takes the paper and does the quest from there. After that, do /fixquests with your 2nd class.

**Comment by Moe-Ronickah** [comment]
Closed: no response by op.
