### ISSUE TITLE
Not being able to connect. aka java.net.connectexception: connection refused: no further information:

### ISSUE THREAD

**Issue by StrafeScout** [Wynncraft/Issues#3596]
I saw a video and saw that it could be either server side/client side. It is server side. I can log in to other servers.

**Comment by TheChampion879** [comment]
Wynncraft is down right now.

**Comment by dragonwarrior495** [comment]
Is there another thread talking about this?

**Comment by xElitaa** [comment]
The network is likely down for maintenance as it seems that several dozen people (including me) have gotten their gear unidentified. The glitch works that all items are unidentified and can't be ID'd

**Comment by dragonwarrior495** [comment]
Oh that actually happened to me, I had a full set of black armour before the big update, and I had joined into a server and was sent to detlas. I opened my inventory, and all I had was my spear, my horse, and some potions. But I took off my armour and my chest plate, leggings, and helmet disappeared. I still have my boots, but they're useless without the rest. And I went back to the shop, and they only sell the helmet and only assassins can wear it.

**Comment by sarah7272665** [comment]
I cant get on and it keeps saying "Exception Connecting:RuntimeException : Server is online mode! @ net.md_5.bungee.Server.Connector:261" when I try to connect who else has this problem?

**Comment by dragonwarrior495** [comment]
That's what happened to me!

**Comment by Trixter313** [comment]
Finally, an official response from Wynncraft =D
https://twitter.com/Wynncraft/status/685906501899284480

**Comment by sarah7272665** [comment]
Yay! :D

**Comment by dragonwarrior495** [comment]
thanks!

**Comment by Trixter313** [comment]
Everyone should be able to access the server now.
"We're back up! Sorry about the delay, it took us a bit longer than expected."
https://twitter.com/Wynncraft/status/686124698095251456
