### ISSUE TITLE
Glitched armor after the downtime

### ISSUE THREAD

**Issue by alfredchi** [Wynncraft/Issues#3597]
My rare armor glitched and now it doesnt gives health/buff
![0000000000000000000000](https://cloud.githubusercontent.com/assets/16517609/12189686/e2bcd4d0-b5fa-11e5-9ffb-73252eee90fd.png)
![000000000000000000000](https://cloud.githubusercontent.com/assets/16517609/12189688/e6649938-b5fa-11e5-83c5-b19678af61b4.png)

**Comment by xElitaa** [comment]
This will be fixed over time most likely, I had similar issues and they fixed themselves inside about a week.

**Comment by TheChampion879** [comment]
Switching servers sometimes fixes this problem. Some items are broken on some servers

**Comment by alfredchi** [comment]
Thanks champion, it fixed after i switched server  <3
