### ISSUE TITLE
A few typos

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#3600]
I've gotten a few screenshots in the past few days while doing (a) quest(s) and other things concerning typos and potential mistakes in things. Keep in mind this is all based on what I've learned and, well, Google.

"but sadly I have nothing to give you [. . .] ." It's preference, from what I know, but you may want to add a "..." to the left of "but."

"[. . .] never been late on an order before... I [. . .] ." If this speech is comprised of two sentences, you'll want to add an extra period after the ellipsis. If it is only one sentence, carry on (you can do on space before, a space after, both, or none).
![2016-01-06_19 56 02](https://cloud.githubusercontent.com/assets/9545223/12191312/f0617352-b587-11e5-85a2-6b1998e532e2.png)
-
"[. . .] 'take back what was stolen from him', [. . .] ." At least in American English (don't believe this affects Europe and stuff), the commas (and other punctuation) will always go inside the quotes, and not after (Yes, it's weird. Blame whoever made that. :I).

Also, as you can see, Phief says something he probably shouldn't say before you complete a certain part of the quest, if you talk to him after the main quest dialogue.
![2016-01-06_20 01 34](https://cloud.githubusercontent.com/assets/9545223/12191331/28e8d594-b588-11e5-913f-1b8520d79ac7.png)
-
As mentioned earlier (this is concerning the first line), if it is a sentence, you put a fourth period. That would seem to be the case, as the next line starts with a capital letter.

Unless Zhight's full name is "Doofbumble Zhight," don't capitalize the "D" in "Doofbumble." Just have it as "[. . .] that doofbumble Zhight."

You may want to replace "Luckily" with "Lucky." on line 5. This is your choice, however.

Line 6 does not have a period at the end of the sentence.
![2016-01-06_20 36 06](https://cloud.githubusercontent.com/assets/9545223/12191429/b0d9b1a2-b589-11e5-9e99-c48a0f08ecc6.png)
-
Again, if this is the end of his speech (as it would seem to be), add a fourth period at the end.
![2016-01-06_20 37 00](https://cloud.githubusercontent.com/assets/9545223/12191517/acbebc60-b58a-11e5-89f0-342bcb166759.png)
-
"wielded" is spelled as "weilded" in the lore.
![2016-01-04_22 26 08](https://cloud.githubusercontent.com/assets/9545223/12191544/007ef806-b58b-11e5-8b7b-c8f776312f08.png)
-
The Potion of Wisdom has the incorrect lore.
![2016-01-07_21 29 51](https://cloud.githubusercontent.com/assets/9545223/12191559/33e9ef7a-b58b-11e5-9bd6-4554c73ebe0a.png)

**Comment by Moe-Ronickah** [comment]
Actually typos are fixed.
