### ISSUE TITLE
i can't equip accessories items

### ISSUE THREAD

**Issue by tollymolly** [Wynncraft/Issues#3602]

**Comment by DarkDemonDragon** [comment]
Some screenshots would help staff analyze the situation.

**Comment by tollymolly** [comment]
![2016-01-08_14 20 56](https://cloud.githubusercontent.com/assets/16608997/12198797/659d8f44-b613-11e5-898f-bc72ecb063e6.png)
![2016-01-08_14 20 58](https://cloud.githubusercontent.com/assets/16608997/12198798/67bf6734-b613-11e5-867d-d1d6c35d7f3a.png)

**Comment by DarkDemonDragon** [comment]
Check that you have the requirements to equip it.

**Comment by tollymolly** [comment]
Yeah everything

**Comment by tollymolly** [comment]
![2016-01-08_14 52 10](https://cloud.githubusercontent.com/assets/16608997/12199315/85a061d2-b617-11e5-8842-7154edb82929.png)

**Comment by Trixter313** [comment]
Can you still not equip the amulet? It should be fixed by now. If not, just comment below and I'll reopen the issue. Thanks!
