### ISSUE TITLE
Typo in Cinfras

### ISSUE THREAD

**Issue by bobbob983** [Wynncraft/Issues#3603]
![2016-01-08_10 20 41](https://cloud.githubusercontent.com/assets/16611891/12201336/cd23effe-b5f1-11e5-8b8c-5c6ffd62622c.png)

**Comment by DarkDemonDragon** [comment]
The GMs be like:" uhh... it's just his accent o3o"

**Comment by DarkDemonDragon** [comment]
@AckroWynn I don't know if this is easy to fix, but you've fixed a couple things like this, so I figured you should know about it.

**Comment by AckroWynn** [comment]
Oh, sorry, I fixed this back in May, but forgot to respond here.
@Moe-Ronickah @Trixter313

**Comment by Moe-Ronickah** [comment]
Now we know . . ..  Closed, fixed on build server.  It will show on the game server with the next map push.  Thanks, Ackro!
