### ISSUE TITLE
pirate town has no indentifier or bankers

### ISSUE THREAD

**Issue by stangefall** [Wynncraft/Issues#3604]
![2016-01-08_17 10 04](https://cloud.githubusercontent.com/assets/16395360/12206945/fe4e2aca-b62a-11e5-8d1b-806fcf6f1ca4.png)
![2016-01-08_17 10 07](https://cloud.githubusercontent.com/assets/16395360/12206946/fe4e5bd0-b62a-11e5-8f1e-93f72a3feb4b.png)
![2016-01-08_17 10 20](https://cloud.githubusercontent.com/assets/16395360/12206949/fe50c230-b62a-11e5-816a-6146cd269f02.png)
![2016-01-08_17 10 25](https://cloud.githubusercontent.com/assets/16395360/12206950/fe523232-b62a-11e5-8ebc-aa85653b6291.png)
![2016-01-08_17 10 32](https://cloud.githubusercontent.com/assets/16395360/12206948/fe509f8a-b62a-11e5-90cc-e322e14840b2.png)
![2016-01-08_17 10 36](https://cloud.githubusercontent.com/assets/16395360/12206947/fe4f734e-b62a-11e5-8525-f4c244c4fe20.png)

**Comment by TrashcanMan** [comment]
Have you tried a different server? It might just be this one server.

**Comment by DarkDemonDragon** [comment]
This is a duplicate of #3272 Please close this issue and follow the original.

**Comment by stangefall** [comment]
sorry didn't see the other issue
