### ISSUE TITLE
Taproot is gone

### ISSUE THREAD

**Issue by TheChampion879** [Wynncraft/Issues#3606]
Because of the inventory reset, I no longer have the taproot, despite having the quest Finding The Light still available to do. I completed it between Jan 4. and Jan. 7, but the Taproot isnt in my inventory anymore?

**Comment by TrashcanMan** [comment]
Have you tried /fixquests?

**Comment by TheChampion879** [comment]
Didnt know if worked like that.

**Comment by TrashcanMan** [comment]
If the item has a Quest Item tag and you can only get it once, /fixquests should return it.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
