### ISSUE TITLE
Lost Armour after wearing it.

### ISSUE THREAD

**Issue by DCCCV** [Wynncraft/Issues#3607]
Username:Alistair_Semidei

So, when the update came in, I was still wearing my armour. When I came to identify it, I was successful. when I tried to wear my armour, the unidentified pieces all came off. I didn't have them in my inventory, and I didn't see them on the ground either. Could someone please help me resolve this? It wouldn't really affect me, but I lost my Mummy's Rag, and I can't get anything back. It has sentimental value, of sorts.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so we can't do much about the already lost armor but they are working on fixing the fact that armor doesn't get dropped on the ground and just gets deleted. You could do to mummy quest again on another class to get another chestplate. Hopefully this doesn't happen to you again!
