### ISSUE TITLE
My chestplate got converted!!!

### ISSUE THREAD

**Issue by Kriminus** [Wynncraft/Issues#3608]
So i was about to try to defeat bob with some other players and then the server restarts(i was not in the fight when it restarted) and montifiorei* got converted into a Psychomend Vest so now i have two.
Also when this happened my montifiorei* was glitching out so i did not provide any protection or buffs like i wasn't even wearing it.

**Comment by Kriminus** [comment]
*e

**Comment by Trixter313** [comment]
This should have been just a one time thing so if it happens again, simply comment below and I'll reopen your issue. Thanks!
