### ISSUE TITLE
Can no longer do quest! :(

### ISSUE THREAD

**Issue by Shockey88** [Wynncraft/Issues#3609]
I just ranked up to level 31, and there is a new quest available. The quest is title "Green Gloop", and I believe the Gavel update has made it undoable. You talk to the starting NPC, and then the NPC tells you to go to a shop in Almuj, where you meet another guy, and he asks you to get him 5 glass bottles. Before the gavel update, you could just go to the potion merchant, drink a potion and get the glass bottles. Now you no longer acquire the glass bottle after drinking a potion. If there is any other way to acquire these glass bottles please let me know :(

**Comment by stangefall** [comment]
kill some mobs near ragni they drop the bottle

**Comment by Shockey88** [comment]
Thanks, just any mob near Ragni or one in particular?

**Comment by Shockey88** [comment]
Thanks so much, got the bottles.
