### ISSUE TITLE
Problem with resource pack

### ISSUE THREAD

**Issue by 9000underscore** [Wynncraft/Issues#3610]
Hey! So I joined recently (as in after the gavel release) and I got my brother to join. Well, whenever he joins the resource pack tries to load, but never does actually load. He is on a mac, though I doubt that contributes to the problem. Server resource packs are enabled, and, like I said, the pack TRIES to download, but when it gets to 100% it just stops. Thanks so much for the help! I really appreciate it!

**Comment by Shockey88** [comment]
Yeah, the mac thing doesn't effect it, I'm on a mac and it is perfectly fine for me.

**Comment by Trixter313** [comment]
Are you still experiencing this issue?

**Comment by Dar-krusos** [comment]
Get your brother to download a different version of the launcher (or another copy), and then try connecting. Also try changing resource packs to _Enabled_ in the Edit menu of Minecraft's Server Menu. You can also try deleting the server from your server list and re-adding it.
