### ISSUE TITLE
Finding The Light Start Quest

### ISSUE THREAD

**Issue by Tobyshaggs** [Wynncraft/Issues#3611]
I am trying to start the Finding the Light quest, but it won't let me. I try to talk to the Guardian, but it says the following even though I already have completed, and have the Taproot: 

![2016-01-07_17 14 04](https://cloud.githubusercontent.com/assets/16386369/12213095/7b9e44a0-b640-11e5-9c68-aed88bc12c30.png)

**Comment by Trixter313** [comment]
If you look at the message, is also says, "and something to wake him up" which is a Volt Goat Horn. With both those items, you should be able to do the quest. Hope this helps!
