### ISSUE TITLE
Accessories benefits not working

### ISSUE THREAD

**Issue by Jupuh** [Wynncraft/Issues#3612]
When I equip a accessory my character traits don't change. For example when I equipped lazaurus' bracelet my health regen didn't change, I tested multiple accessories and none of my traits changed.

**Comment by ImSickPT** [comment]
same bug with me
my ring says -25 health and when I put it in the slot, my health doesnt decrease

**Comment by HeyloLP** [comment]
the benefits are working after a reconnect or class change

**Comment by ImSickPT** [comment]
ok thx.

**Comment by Jupuh** [comment]
Great! Now my Royale Amulet will finally work!
