### ISSUE TITLE
You get teleported to the starting area after you take off your creeper mask in the creeper cave

### ISSUE THREAD

**Issue by Kettlekorn** [Wynncraft/Issues#3613]
You get teleported to the starting area after you take off your creeper mask in the creeper cave.

**Comment by slendersir739** [comment]
Because you need the mask to be in the cave, if you take it off, you will glitch out.

**Comment by Trixter313** [comment]
Consolidated into https://github.com/Wynncraft/Issues/issues/3617

Please direct any future comments to this thread. Thanks!
