### ISSUE TITLE
Shadow of the Beast Quest Problem

### ISSUE THREAD

**Issue by Christinel8** [Wynncraft/Issues#3615]
I am at the end of the quest and I have killed the huge zombie beast several times. I go to the bedrock warp and it will not let me enter. It says something about the smell of blood and danger and that I should not go in as it forces me back. I did /kill and entered the cave over again, completed the puzzle again and I am still stuck. please help? Thanks

**Comment by ImSickPT** [comment]
@Christinel8 that is not considered a bug as I was able to complete that quest in the past

**Comment by TheChampion879** [comment]
You need to pick up the item that the giant zombie drops to leave
