### ISSUE TITLE
Collective respawning in incorrect place issue

### ISSUE THREAD

**Issue by Trixter313** [Wynncraft/Issues#3617]
Green Skinned Trouble https://github.com/Wynncraft/Issues/issues/3177 https://github.com/Wynncraft/Issues/issues/3516
Shattered Minds https://github.com/Wynncraft/Issues/issues/3360 https://github.com/Wynncraft/Issues/issues/4103
A fighting species https://github.com/Wynncraft/Issues/issues/3362
Creeper Cave https://github.com/Wynncraft/Issues/issues/3613
Hallowynn Quest https://github.com/Wynncraft/Issues/issues/3713
Flight in Distress https://github.com/Wynncraft/Issues/issues/3742
Craftmas Chaos Past Selchar https://github.com/Wynncraft/Issues/issues/3866

Please comment with any other places you know of. I know this is caused by these places being outside of the regular map but that doesn't make it unfixable. Not sure if this is worth fixing or not but they are all in one issue now to easily close or deal with. You could add a tag or somehow make it so that if players are within a certain area they respawn at a custom location instead of the default closest place.

**Comment by Dar-krusos** [comment]
I do not think this is an issue with mechanics, rather that these locations are closest tot eh Starting Location, and hence dying takes you there, which happens to be the closest spawn.

**Comment by Trixter313** [comment]
But it's an overlook in the game mechanics and I'm sure they could probably mark certain locations off to respawn in a different location than just what is closest.

**Comment by DarkDemonDragon** [comment]
Another thing is that if you just completed a dungeon and die by the dungeon, then you will spawn at the dungeon entrance rather than the nearest town.

Ex. Finished Silverfish dungeon, get killed by a nearby spider, respawn in front of Silverfish Dungeon by the Key collector instead of in Almuj

**Comment by Trixter313** [comment]
After rereading this, I realize this should probably be in the suggestions on the forums and not an issue.

**Comment by Trixter313** [comment]
Thread: https://forums.wynncraft.com/threads/changing-respawn-locations-for-some-places.117002/

**Comment by adam-jw** [comment]
I'd like to add it occurred to me today in a fighting species.

Not sure if it has been fixed, (attempted)

(I was teleported after killing Gorgu to the starting tutorial area)

**Comment by Moe-Ronickah** [comment]
@adam-jw , it's not an issue.

**Comment by adam-jw** [comment]
@Moe-Ronickah - I didn't believe that it was expected behaviour.

**Comment by Moe-Ronickah** [comment]
If you read Trixter's first comment, you will see why it isn't an issue.  The quest tp areas are outside of the main map.  If a player dies, they respawn in the **nearest** city, which may be a long ways away from the quest area.  This is something that the developers would need to address, IF they can.  It's not an issue that we can further deal with, as the developers already know about it.  You can post your concern on the forums where they will see it, again, so that they get reminded about it, nicely, please.

**Comment by sammyvsparks** [comment]
Silverfish dungeon https://github.com/Wynncraft/Issues/issues/5566

**Comment by AckroWynn** [comment]
I have actually fixed the Flight in Distress issue somewhat using a special technique on GM servers.
The way it will work is that you will be able to go and sleep in the very first stage of the airship. If the quest is complete, it will just teleport you to Detlas (which it already does ingame). If you have reached the cutscene part in the quest, sleeping will make you teleport to the part just before the cutscene. This will essentially take away most of the work needed to return to your stage in the quest, if the Queen kills you.

(The method I am using to fix the issue will not be updated on the servers for quite a while. Expect it to arrive when the main storyline is out!)

@Moe-Ronickah

**Comment by AckroWynn** [comment]
Addition: I asked Grian if we were allowed to add custom respawn points to certain quest areas, but he responded accordingly:

(This was a discussion about how we should fix the Flight in Distress issue, but this goes for all of the respawning issues you have!)
![image](https://cloud.githubusercontent.com/assets/7467934/17100859/69f18fd2-5271-11e6-9745-20261ab20be2.png)


![image](https://cloud.githubusercontent.com/assets/7467934/17100882/8a167ebc-5271-11e6-956d-919a80ae3864.png)

**Comment by Moe-Ronickah** [comment]
I'm concerned about one thing: with the custom loop in the airship, does that somehow interfere with a player who is helping another player to complete the quest?  If is does, is there a way around it?

**Comment by AckroWynn** [comment]
You see, this "sleeping-to-skip"-teleport only works in the very beginning. You usually do not sleep there, to proceed in the quest, otherwise. I am not sure what you mean, if it's not that.

**Comment by Moe-Ronickah** [comment]
So, is sleeping at that point an option, so that someone can repeat the quest and help someone else through the quest, or is sleeping at that point a forced action, thereby preventing a player who has already finished the quest from running through the quest a second or third time?

**Comment by AckroWynn** [comment]
It is completely optional.
If you check it out in game right now, you can see that there is an Attendant. At the moment, as I said, you can skip the quest by sleeping at that point if you've completed it. 

When my fix is functional, it'll make it so that sleeping there at that point, depending on where in the quest you are (finished, or past-animation), it will get you to that point.
