### ISSUE TITLE
Selchar emerald converter

### ISSUE THREAD

**Issue by us5013** [Wynncraft/Issues#3618]
So i recently found out that I could convert an old le i had into the new le... Although, when i went to selchar to see the emerald converter, he wouldn't work. I did keep saying thank you for your business, but it never actually gave the new le. This might be a derp on my part, but if i could get some help that would be nice.

**Comment by Trixter313** [comment]
Have you tried doing the transaction on another world?

**Comment by us5013** [comment]
i have and it hasn't worked... I will try to do it again today... but there is something wrong with the server so i can't get on

**Comment by us5013** [comment]
i got back on and it worked

**Comment by Trixter313** [comment]
Good to hear! =)
