### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by sarah7272665** [Wynncraft/Issues#3619]
For some reason I cant connect to Wynncraft, it says unable to connect however when it says I can it still wont let me please help!

**Comment by gerlove** [comment]
I have the same problem!

**Comment by Deadoverlord** [comment]
same i have been checking beck every half hour but it wont let me connect and it says 100/100 people on isnt the server more than 100 people? or slots

**Comment by sarah7272665** [comment]
Yea and the error message for me says "Exception Connecting:RuntimeException : Server is online mode! @ net.md_5.bungee.Server.Connector:261"

**Comment by Deadoverlord** [comment]
yea

**Comment by Deadoverlord** [comment]
same

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3596

Please direct any future comments to the original thread. Thanks

**Comment by Deadoverlord** [comment]
looked at it its about the items not the server and that was 2 days ago it worked perfect yesterday

**Comment by Trixter313** [comment]
It's not about items, someone just mentioned items and they are both talking about not being able to connect.

**Comment by Deadoverlord** [comment]
yea but still 2 days ago and the person who started it made it about items and other people went into connecting

**Comment by Trixter313** [comment]
I don't see anywhere where the OP said anything about items? And no matter when it occured, they are the same issue and some people are getting the same error codes.

**Comment by Deadoverlord** [comment]
ok im just trying to watch Ytube bye

**Comment by sarah7272665** [comment]
I doubt this is a duplicate. The other issue was two days ago and they probably werent having the same problem. I just want to know whats going on and the other issue isnt specific so I dont know if they got the same error message.
