### ISSUE TITLE
Mana Steal Issue

### ISSUE THREAD

**Issue by Okuupls** [Wynncraft/Issues#3621]
Mana Steal seems to only work when I'm using an item that has Mana Steal on it, for example, when using my Bob's Mythic Spear I gain no mana from hitting enemies, despite my amulet giving me Mana Steal 2, however the Mana Steal 2 does apply when I'm using my Scythe, which does have Mana Steal

**Comment by Trixter313** [comment]
When did you put the amulet on? Some people reported it taking a relog for accessories to apply their effects to the player. Try restarting your Minecraft and see if the amulet maybe works then.
