### ISSUE TITLE
My leggings had gone

### ISSUE THREAD

**Issue by SkyBluer** [Wynncraft/Issues#3624]
![2016-01-10_18 50 26](https://cloud.githubusercontent.com/assets/16632452/12221095/088081a4-b7d0-11e5-8cc7-a21e144ae4b6.png)
![2016-01-10_19 10 39](https://cloud.githubusercontent.com/assets/16632452/12221096/09de8136-b7d0-11e5-979c-e254a3eff8ca.png)

i got legendery leggings and go identifying, but servers go shut down.
After shut down, i logged in sever, but my leggings had gone.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refunds policy so not much can be done about the lost armor. There's no way to tell what caused it to disappear either. Hopefully it isn't too much of an inconvenience!
