### ISSUE TITLE
Tower of Maiden Black Veil bugged

### ISSUE THREAD

**Issue by bobotje** [Wynncraft/Issues#3630]
Can't finish the Tower of Maiden quest because it's bugged. Those pictures and 1 gif below this is the proof.

https://gyazo.com/d829db1e6c95fdaf67415cbbd60dc979
https://gyazo.com/15dd08c3b5ef2fdc08729cae84d0be98
https://gyazo.com/8de259b949ee667417d8371cad338f26

**Comment by Troll2828** [comment]
Try to go get the veil again maybe when you acquired it, your quest book didn't update because of the lag.

**Comment by bobotje** [comment]
Tnx it worked.
