### ISSUE TITLE
Bonemeal and Bat Ears

### ISSUE THREAD

**Issue by sarah7272665** [Wynncraft/Issues#3632]
Whenever I try to turn in the potion making quest it dosent work even though I have all the required materials, however some of the bonemeal and bat ears wont stack? please help

**Comment by sarah7272665** [comment]
Im also finding that other items that Ive had from awhile back wont stack with new items I get

**Comment by Troll2828** [comment]
that's normal old items don't work anymore so you have to get new ones.

**Comment by sarah7272665** [comment]
Dang, well this is gonna be a pain in the butt, is there any way to fix them?

**Comment by Troll2828** [comment]
I don't think there is anyway to fix them

**Comment by Trixter313** [comment]
If getting new items fixes your issue, we'd appreciate it if you closed this issue. Thanks!
