### ISSUE TITLE
Soulpoints don't work

### ISSUE THREAD

**Issue by Zorrkhart** [Wynncraft/Issues#3634]
Hello.
All my items, as my horse, are lost because i was killed by a group of zombies.
By that time, I had 12 Soulpoints, past the death 0.
Maybe it is because i haven't use my archer since the last update but it is very stressfull to get the items back.
Please Fix!
Thanks, (User) Zorrkhart

**Comment by Monkeysz** [comment]
Sorry but wynncraft has a strict no refund policy therefore you can't get your items back so you should close this thread since no one will do anything about it.

**Comment by Trixter313** [comment]
This shouldn't happen again and was just a one time occurrence. Due to the no refunds policy, we can't give any items back but if you ask some players they will usually give you some good items.
