### ISSUE TITLE
Black box

### ISSUE THREAD

**Issue by sarah7272665** [Wynncraft/Issues#3635]
Sometimes when I spawn into a world it puts me into this dark room made of what im assuming is grey wool and I cant use any commands or anything? It tells me to choose my class but because I cant use commands I cant do that I dont know whats going on please help!

**Comment by sarah7272665** [comment]
Also when I can get on the quest giver for the quest Potion Making is gone

**Comment by swaggerdav** [comment]
Same for me except I can do things but I cant leave the box
