### ISSUE TITLE
Class Selection

### ISSUE THREAD

**Issue by Scrambleking** [Wynncraft/Issues#3636]
I have not encountered this issue until just now, and was on after the servers were revitalized just a little while ago, exited the game, and have tried to rejoin, however when I am teleported to the black box for class selection, I end up falling through the ground into the void, and can only use the /hub command and have tested getting back in on multiple worlds, to no avail. 

IGN: Scrambleking

**Comment by sarah7272665** [comment]
Im having the same problem

**Comment by TheChampion879** [comment]
I get teleported to the black box, and then nothing happens. Just sit here waiting for the class selection to appear, but it does not. Tried switching servers as well

**Comment by Scrambleking** [comment]
Yea Champion a friend of mine just tried getting on and had the same issue

**Comment by stangefall** [comment]
still stuck here after relogging
![2016-01-10_14 34 24](https://cloud.githubusercontent.com/assets/16395360/12222568/4550fdf8-b7a7-11e5-9927-c9946bd4c18b.png)
![2016-01-10_14 34 38](https://cloud.githubusercontent.com/assets/16395360/12222569/4552811e-b7a7-11e5-800e-8e1cbe631eae.png)
![2016-01-10_14 34 40](https://cloud.githubusercontent.com/assets/16395360/12222570/45556c30-b7a7-11e5-9198-2894d5c26da8.png)

**Comment by Scrambleking** [comment]
Bozepatric, Scotty2895, and Mystogon_Gaming are in the box but no class selection

**Comment by Kaitnoday** [comment]
I'm having the same problem, I cant use the /class command and the Class Selection won't appear.

**Comment by Scrambleking** [comment]
Scotty joined server 18 and it seemed to work for him

**Comment by Scrambleking** [comment]
tried joining the world, however no avail

**Comment by Scrambleking** [comment]
Same for Mystogon

**Comment by Scrambleking** [comment]
Op90 is having the black box on multiple servers, and was able to bypass on server 2

**Comment by stangefall** [comment]
great, when i get to a server and it let me play, server restarting in 1 minute.......

**Comment by Scrambleking** [comment]
and all working are full, even when I get in a working server I can't get it to work

**Comment by Scrambleking** [comment]
Problem seems to be semi fixed for the people who only did not get the class screen, I still have a persisting problem where I fall through and don't get the screen, no matter the server

**Comment by Scrambleking** [comment]
Yep seem to be fixed for almost everyone but me, Sarah you getting the same thing still?

**Comment by sarah7272665** [comment]
Yea its been ok for me for awhile now

**Comment by Scrambleking** [comment]
Still falling, Does this have anything to do with not installing the Resource pack? I have it disabled because it would never finish downloading, so I downloaded it manualy.

**Comment by Scrambleking** [comment]
Problem Persist.

**Comment by Scrambleking** [comment]
I had recreated the thread because there was no response from staff

**Comment by Trixter313** [comment]
Don't worry Scrambleking, we see it even if there's no response. We are trying to fix this annoying issue and just don't have anything else to say about it right now. One report per issue is good enough =) Thanks!

**Comment by Scrambleking** [comment]
ok,sorry for reopening it before

**Comment by Scrambleking** [comment]
just reporting, incase you finished trying to fix it, still going

**Comment by Scrambleking** [comment]
Same as above

**Comment by Scrambleking** [comment]
"

**Comment by Scrambleking** [comment]
Tried logging in on a friend's account that worked and I kept falling, however when he logged back in, he was fine

**Comment by Scrambleking** [comment]
redownloading mc?

**Comment by Scrambleking** [comment]
fixed

**Comment by Scrambleking** [comment]
just deleted my wynncraft list on the server, and it fixed it

**Comment by Trixter313** [comment]
Glad to hear!

**Comment by TimThePvpMaster** [comment]
I tried that, it won't work for me. Help???
