### ISSUE TITLE
Stupid Quest Glitch, Lost Quest Item!

### ISSUE THREAD

**Issue by Shockey88** [Wynncraft/Issues#3637]
I'm doing the "Canyon Condor" quest right now, and at the end of it you have to fight an annoying boss with minions to obtain a beast egg, and so you have to then return it to a guy, I did this, but it said empty some space in your inventory first, but still took the egg, once i had enough space in my inventory I talked to him again and he asked me to bring him another beast egg. I want my beast egg back.

**Comment by Shockey88** [comment]
I just did the boss fight again and got the egg, still is an issue though so I'm leaving this open.

**Comment by Trixter313** [comment]
Did it let you finish the quest with the new egg? I just helped someone do the quest recently and it worked fine for them so it was probably just a one time fluke issue. If so, please close this issue. Thanks!

**Comment by Mirqcles** [comment]
Try typing /fixquests
