### ISSUE TITLE
Class selection 

### ISSUE THREAD

**Issue by nikgamermc** [Wynncraft/Issues#3639]
I can join the lobby servers w/o any problems. But when i join a server its says loading recourse pack, and then i takes me to the class selection box. I cant choose any class as normally. I can move around and the command i can use is "/lobby". Any help on fixing this?

**Comment by CHENS85** [comment]
same

**Comment by DemGreens** [comment]
same pls do something about it as some people can join and not others

**Comment by Trixter313** [comment]
I was experiencing this but after trying a few different worlds, I found one that worked so I'd suggest just going through all of them till you find one that works for you.

**Comment by Trixter313** [comment]
This should be all good now.
