### ISSUE TITLE
Weapons dont change the skills (strength dexterity etc...)

### ISSUE THREAD

**Issue by Equipa2** [Wynncraft/Issues#3641]
Weapons dont change skill points.
![2016-01-10_20 02 36](https://cloud.githubusercontent.com/assets/16447942/12223663/3f41c130-b7d5-11e5-8dea-f591a6bc80e1.png)
![2016-01-10_20 02 41](https://cloud.githubusercontent.com/assets/16447942/12223664/420b7b9a-b7d5-11e5-9465-42f364c016c9.png)
![2016-01-10_20 02 46](https://cloud.githubusercontent.com/assets/16447942/12223665/48423e90-b7d5-11e5-9e4d-1ac18ce4db6a.png)

**Comment by Trixter313** [comment]
Have you tried doing /class then re-selecting the class? Some people reported it taking that to make the stats update.

**Comment by meatloaf4311** [comment]
My weapons don't change any stats in the compas except the actual weapom used. Although each do seems to corresponding amounts of damage

**Comment by HeyloLP** [comment]
it's only effecting if your holding the bow

**Comment by meatloaf4311** [comment]
So if my assumption is correct, you cant see it unless you can open compass and hold bow at the same time
