### ISSUE TITLE
Armor Dissapeared! No Pants!

### ISSUE THREAD

**Issue by Gu1n3a** [Wynncraft/Issues#3642]
Today, I was doing the Qira Hive Quest and I finished the Earth part. I got my voucher and got the Elder Oak Roots. Those are the legs you get with the Earth Voucher. I put them on but then they got auto-taken off. They require a higher level than I am. No problem, I will just put my Crystal back on... Wait, where did it go. It's gone!? It couldn't have! So now I got no pants. Please help me in this situation. What do I do?

![2016-01-10_15 45 33](https://cloud.githubusercontent.com/assets/16637946/12223889/4a6998cc-b7b1-11e5-94e1-421aeff3c1fd.png)
![2016-01-10_15 45 44](https://cloud.githubusercontent.com/assets/16637946/12223890/4cd9a2fa-b7b1-11e5-9d11-4c3dfbd3404d.png)

**Comment by Trixter313** [comment]
Try asking players around you if they can give you some pants, or check your daily rewards for some possibly. Wynncraft has a strict no refunds policy so unfortunately nothing can be done about the lost armor.
