### ISSUE TITLE
Texture Pack Issue

### ISSUE THREAD

**Issue by PlunGi** [Wynncraft/Issues#3643]
I know there is probably a billion threads about this, but I need help with this. It tells me it loads, and says, "Thank you for using the WynnPack. Enjoy the game!" and the textures aren't there. Image:
http://imgur.com/Hh8KWAs
It's obvious that the WynnPack didn't load, as my spear is a stone brick slab. 
How to solve? 
I currently use the downloadable WynnPack, but it is kind of annoying that I have to change back to my normal pack.

**Comment by Trixter313** [comment]
Could you post a screenshot of your F3

**Comment by KoiPond182** [comment]
Same it's not working for me either I use 1.8.8, I use a IMac if that has to do anything

**Comment by zeldahuman** [comment]
Make sure you don't have any other resource packs loaded when the WynnPack gets downloaded and applied: it looks to me like you have a Faithful resource pack applied, which will overwrite basically everything in the WynnPack.

**Comment by KoiPond182** [comment]
I have another resource pack for it but it doesn't  have a model for all the weapons, only the default ones.

**Comment by NinjaPiggy** [comment]
I still have all the textures, except for my bow (Etikal), which is a wood slab.
![2016-03-20_13 02 14](https://cloud.githubusercontent.com/assets/17673269/13905642/367d39c8-ee9c-11e5-84d2-8a52263662cc.png)
This started up just today. Also, for some reason my custom armor isn't working.
I am using Minecraft 1.9.

**Comment by KoiPond182** [comment]
Go back to 1.8 or 1.8.9
