### ISSUE TITLE
Broken Wand! (Devoreuse.) 

### ISSUE THREAD

**Issue by Tyzillion** [Wynncraft/Issues#3644]
I really hope u guys can fix this and keep the stats the same because that had 14/4 mana regen.
http://imgur.com/a/TAHF1
Pls fix it and make it have the same stats it had....Pls.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!
