### ISSUE TITLE
Quest Glitch  Craftmas Chaos - I Died Fighting Santa, And Re spawned at llevigar

### ISSUE THREAD

**Issue by Killcode96** [Wynncraft/Issues#3648]
when i was fighting Santa i was killed by him, and then re spawned and llevigar (a city i have only been to once) on the normal map i am unable to get back to the future to try the fight again is there any thing i can do like get tp'd why an admin or something or is the quest over for good? Ty for your time.

**Comment by Trixter313** [comment]
Have you tried going through the fireplace again?

**Comment by lXetnosl** [comment]
just go back to santas home and try again

**Comment by Killcode96** [comment]
ill try to get back from llevigar it will be hard because it so far away but i will keep you posted ok so it worked ty very much
