### ISSUE TITLE
Skeleton boss "wither head" boss broken

### ISSUE THREAD

**Issue by GamaRadiation282** [Wynncraft/Issues#3649]
The wither head boss for the skeleton dungeon is broken. I attack it repeatedly and it goes down a bit but it regens all its health just after a few hits from 756 to 548. its impossible for a level 15-25 to beat it because it regens all its health back so quickly please fix this :(

**Comment by chesters31** [comment]
it is not impossible as i did it myself with a lvl 15 ninja myself it nearly killed me but i did it

**Comment by Trixter313** [comment]
Could you post a picture of your weapon? It's possible you're using the wrong elements for that boss.
