### ISSUE TITLE
Some Typos

### ISSUE THREAD

**Issue by TrashcanMan** [Wynncraft/Issues#3650]
Two typos to report here:
1. Shadow of the Beast, Rileen. Should be "any more", not "anymore"
![2016-01-10_20 30 31](https://cloud.githubusercontent.com/assets/6947594/12227355/313b1248-b7e0-11e5-973c-60cce2d56ba2.png)
2. Item Identifier. Should be "contains", not "contain"
![2016-01-10_20 57 21](https://cloud.githubusercontent.com/assets/6947594/12227318/88cbf0f0-b7df-11e5-960c-b516df0a029d.png)

**Comment by lXetnosl** [comment]
nobody cares xD rather mind the really annoying bugs like deleting stuff...

**Comment by Trixter313** [comment]
I believe the identifier part has now been fixed, according to https://forums.wynncraft.com/threads/gavel-patch-14-0-9.112397/

**Comment by Dar-krusos** [comment]
Thanks for letting me know. They fixed it cuz of you :)

**Comment by TrashcanMan** [comment]
:)
Since both of these are fixed I guess I can close this now.
