### ISSUE TITLE
i am vip+ but dont have any of the perks

### ISSUE THREAD

**Issue by chesters31** [Wynncraft/Issues#3651]
hey there i am a vip+ veteran on the server and i do not have access to most of the perks like a reserved slot, attack animations lobby perks or the skeleton horse diguise can you please fix this my in game name is chesters31

thank you and hope to hear from you on the matter and hope it can be resolved

**Comment by Trixter313** [comment]
As for the slots, you don't actually see anything different. The lobby commands still aren't implemented yet unfortunately. What animations do you have access to?

**Comment by chesters31** [comment]
I have access to the few ones you get as vip

**Comment by Trixter313** [comment]
So could you list out the ones you have access to? Thanks!
