### ISSUE TITLE
Weapons got converted

### ISSUE THREAD

**Issue by Moon-night0922** [Wynncraft/Issues#3653]
I got an Ohm's Wish. Then the server closed when I used it to click on an Olux's Prized Bow in the inventory. When I logged in again, it converted into another one.
![2016-01-11_18 11 10](https://cloud.githubusercontent.com/assets/16646499/12231966/42262406-b896-11e5-9f26-b04a557507d2.png)
![2016-01-11_18 11 07](https://cloud.githubusercontent.com/assets/16646499/12231971/50f07e78-b896-11e5-8c3f-0ec0db3b0bb4.png)

**Comment by DarkDemonDragon** [comment]
Similar thing happened to me, but fortunately only a useless Quest Item got converted to a 2nd pair of Abysso Galoshes.

**Comment by Trixter313** [comment]
This was most likely a one time issue type thing and if it happens again just comment and I'll reopen the issue.
