### ISSUE TITLE
Death crash server..

### ISSUE THREAD

**Issue by EarlzZZ** [Wynncraft/Issues#3659]
When i go to death. I hit it to 200k , and then the server crashes. 
I check all the server. The same thing.. 
I can"t event kill him.. Tried with 3 people.. Server is crashing all the time when he got 200k.

**Comment by TrashcanMan** [comment]
Might be related to #3337, but I'm not quite sure.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes issues like this are just a one time thing. If it's over, please close this issue. Thanks!
