### ISSUE TITLE
I tried identifing my items and they all disapeared

### ISSUE THREAD

**Issue by DeadAtNooN** [Wynncraft/Issues#3660]
Its been a few months sense I last loged on to wynncraft and when I tried my leavel 45 mage it said all my items were unidentified exept for my stick devorse  ( I don't know how to spell it) and my boots< but my stick didn't cast spells and when I tried to unequip my helmet it disappeared with all my other armour exept my boots, I had the mummies cloths on (exept for my boots)        I don't know if this is because my items have been removed from the game entirely or if its just a glich please help.        Itook a lot of screenshots as proof. they show my items my level and so on. my minecraft username is Skullcrusher1027                                                        
![2016-01-11_17 11 21](https://cloud.githubusercontent.com/assets/15008041/12248383/01168e1a-b887-11e5-8396-ef8d6f222aaf.png)
![2016-01-11_17 11 24](https://cloud.githubusercontent.com/assets/15008041/12248386/063594ae-b887-11e5-8f72-94d6a387f021.png)
![2016-01-11_17 13 18](https://cloud.githubusercontent.com/assets/15008041/12248388/0aa17c10-b887-11e5-8b22-6d6b6d584e0d.png)
![2016-01-11_17 14 13](https://cloud.githubusercontent.com/assets/15008041/12248393/13ca3732-b887-11e5-8aeb-37a19a00023f.png)
![2016-01-11_17 14 39](https://cloud.githubusercontent.com/assets/15008041/12248398/19c806a0-b887-11e5-8815-7dabd2fb394c.png)
![2016-01-11_17 13 30](https://cloud.githubusercontent.com/assets/15008041/12248401/21695526-b887-11e5-91ac-e3c6511585cd.png)

**Comment by Trixter313** [comment]
Unfortunately due to Wynncraft's strict no refunds policy nothing can be done about the already lost armor but we are working on fixing the bug where items are just deleted instead of dropped on the ground. All items need to be reidentified since the Gavel update because there are a lot of new cool identifications. Hopefully this isn't too much of an inconvenience!
