### ISSUE TITLE
Tower of Ascension meteor lag

### ISSUE THREAD

**Issue by PaulWaffle** [Wynncraft/Issues#3661]
Using the meteor spell in ToA causes ~2-5 seconds of lag after casting at about the time the burning ground effect is starts. I have seen this consistently ever since i've tried doing ToA after gavel came out.

[toa lag.zip](https://github.com/Wynncraft/Issues/files/86531/toa.lag.zip)

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3337

Please direct any future comments to the original thread. Thanks!
