### ISSUE TITLE
My boots literally dissapered.

### ISSUE THREAD

**Issue by Cinfras** [Wynncraft/Issues#3667]
I logged into my account during a laggy period to find that my stalagmite boots were magically gone im pretty disappointed in this because it took me a while to earn them and I still wear them even though im level 91. If this is because i was moving my inventory when i was randomly kick due to the servers crashing I would like my boots refunded. Im a dedicated player and I feel as if I have been wronged even though I doubt the staff had any intention on that. If you could take the time to return my lost boots I would very much appreciate it. ign (Cinfras)

**Comment by DarkDemonDragon** [comment]
Unfortunately Wynncraft has a strict no-refund policy. For something like this you'd be better off closing this and PMing an Admin on the forums. Remember that players have lost things even worse from Bob Mythical Weapons to their whole inventory.
