### ISSUE TITLE
Armour dissapear Glitch

### ISSUE THREAD

**Issue by MatiGamePlay** [Wynncraft/Issues#3668]
I logged onto gavel (yesterday) then i realised i had everything apart from my armour, i was very angry so heres an image also i had the blue mask, ect best armour before gavel came out....
2016-01-12_19 13 57
![2016-01-12_19 13 57](https://cloud.githubusercontent.com/assets/16672667/12275329/712ab998-b967-11e5-9e96-bfa063636859.png)

**Comment by MatiGamePlay** [comment]
this is a spare chestplate

**Comment by Kettlekorn** [comment]
This happened to me too. I'll be really pissed off if the Wynncraft staff just apologizes and tells us to get the armor back ourselves.

**Comment by HeyloLP** [comment]
1 i think you had a full inv. when you clicked on your armor or an accessoire slot and then the system deleted the items
2 there is still a no refund policy so you won't gat anything back (why does nobody understand this *facepalm*)

**Comment by Dar-krusos** [comment]
Before the Gavel Update, you were told to remove your armor before it happened, and leave four slots empty in your inventory. This was announced on the forums (which clearly means you should be reading it :P )

**Comment by Trixter313** [comment]
As was mentioned, Wynncraft has a very strict no refunds policy so getting the already lost armor probably won't happen but we are working on fixing the fact that armor just gets deleted instead of being dropped so this doesn't keep happening. Hopefully it isn't too much of an inconvenience.
