### ISSUE TITLE
OMG No Why

### ISSUE THREAD

**Issue by FurtherApart** [Wynncraft/Issues#3671]
I was doing Temple Of Legends and it was going so well like IT WAS GOING SO WELL until I realized one or two things! I Lost The Mummy's Rag, Maltic's Recommendation Letter, Sayleros's Ashes (Maybe), and Sodeta Boots!!!! I need help getting it back but /fixquests doesn't work for these items since I lost them a long time ago!!! If you are willing to help then I will be happy for you. IGN (Ingame User Name): Elite_Chicken (If It Doesn't Work, Try Priority_Four). Thank you! - Further

**Comment by DarkDemonDragon** [comment]
You're duplicating yourself. Please close one of your duplicates. Anyways check your bank and the inventory of your other classes.

**Comment by FurtherApart** [comment]
The Sodeta Boots wasn't there and I thought the first thread post was
glitched. Sorry about that.

**Comment by Trixter313** [comment]
So did you find everything except the boots?

**Comment by FurtherApart** [comment]
Yep

**Comment by Trixter313** [comment]
Are you sure you need the boots for that quest? I never needed any "Sodeta Boots" when I did it. I don't think I've even seen these boots before.

**Comment by DarkDemonDragon** [comment]
He doesn't, but Sodeta boots have good stats though.

**Comment by Trixter313** [comment]
Ah. Well, due to the no refund policy, we can't do anything about an item 'lost' especially since we don't know anything about how it was lost. As long as it isn't a needed item for a later quest, you should be fine.
