### ISSUE TITLE
Quest was reset

### ISSUE THREAD

**Issue by FangZo** [Wynncraft/Issues#3672]
While talking to the Guardian of the Forest in the opening dialogue after I had searched forever for the Volt Horn and did the Traproot quest. While talking to him I lagged out and died, when I saw the text it ended at the 3rd line of text (after which I died), when I came back to the guardian it required me for another traproot and volt horn, and the quest did not start even though I started it. Please help me.

Thank you,

- FangZo

**Comment by FangZo** [comment]
I have returned my traproot back through /fixquests but I will have search for a volt horn again. If you read this, thank you though.

**Comment by TrashcanMan** [comment]
If your issue is resolved, please hit the "Close Issue" button at the bottom. Thanks!
