### ISSUE TITLE
First time in Gavel update since Guilds - Can't login as best character

### ISSUE THREAD

**Issue by Tufukins** [Wynncraft/Issues#3673]
Unable to login as my best character:
![erro2](https://cloud.githubusercontent.com/assets/16678131/12284462/a6a14e5a-b97d-11e5-9b4f-498b034fd6d1.png)
![erro1](https://cloud.githubusercontent.com/assets/16678131/12284464/abc6c3ec-b97d-11e5-946c-692bd9c6dd30.png)

-Tufukins

**Comment by TrashcanMan** [comment]
Probably the same issue as #3250
