### ISSUE TITLE
Lost my boots due to unidentified armor glitch?

### ISSUE THREAD

**Issue by TeleportingNinja** [Wynncraft/Issues#3675]
Hello, I recenetly came back to Wynncraft after the gavel update, and when I clciked on my armor, it took all of them off, and my boots dissapeared :known as the Talaria. Can you please give them back? it was fully identified... It said it was because it was unidentified, please fix.
Username: TeleportingNinja

**Comment by DarkDemonDragon** [comment]
This is not a bug. All armor was purposefully UnIdentified after Gavel came out and there was a warning on the forums. Unfortunately Wynncraft has a strict no-refund policy. Since this is not a bug, please close this issue.
