### ISSUE TITLE
Stuck in a wall after teleport through a portal !

### ISSUE THREAD

**Issue by zavaman** [Wynncraft/Issues#3676]
Hello,my ign is ''L1ghtn1ngBl4d3r'' and i am stuck in a wall i cannot move or use a scroll to exit that.! That happend after the quest ''Excavation Site B'' in the end at the pink crystal i pick some of those and i jump through the portal and teleport me inside some wall.! I need some help someone to teleport me out of this place ! Ty for your time !

(I Use /kill to end this place i didnt know we have that access to that command sorry for the ticket !)

**Comment by TrashcanMan** [comment]
If your issue is resolved please hit the "Close Issue" button, thanks!

**Comment by meatloaf4311** [comment]
^
