### ISSUE TITLE
I can't connect to the building server (build.wynncraft.com)

### ISSUE THREAD

**Issue by nickmathes** [Wynncraft/Issues#3677]
I am not sure if issues about the build server are supposed to be written down here but I can't join the server. It says that I am logging in for a very long time and then it says "Disconnected". I can join the wynncraft server totally normal and every other server works too. I would really like to join the build server and I would be happy if you could answer me how I can fix this :)

**Comment by TrashcanMan** [comment]
Are you supposed to be allowed onto the build server?

**Comment by nickmathes** [comment]
I thought everyone could join it and build to show their skills and maybe get a builder? ...

**Comment by TrashcanMan** [comment]
No, you have to send in an application at http://katoa.ca/apply/ and then get accepted to be allowed on.
