### ISSUE TITLE
Craftmas Chaos Fall Damage

### ISSUE THREAD

**Issue by GameScout180** [Wynncraft/Issues#3678]
The quest craftsman chaos is currently bugged. After destroying the corrupted shard and falling trough Santas mouthe you get teleported half into ground dieing almost instantly and being teleported to Selchar and loosing 2 soul points.

**Comment by Dar-krusos** [comment]
As of late, many teleport mechanics have been broken and it seems this is the same issue, albeit in a different location. You will have to wait until the teleport trigger in that area is fixed.

**Comment by Moe-Ronickah** [comment]
Fixed.
