### ISSUE TITLE
SilverFish Dungeon Bug 

### ISSUE THREAD

**Issue by 7asoOonyi14** [Wynncraft/Issues#3680]
in silverfish dungeon , in the Trap room where you need to push the button and run to the door while pistons open and silverfish come out , its broken and bugged , now the silverfish can go out at anytime ! , also there is technical issues with the doors in the snake puzzle where some times an block is removed when the door opens and it shows the redstone under the door , Hope i helped

**Comment by DarkDemonDragon** [comment]
A couple pictures would be helpful.

**Comment by Dar-krusos** [comment]
In the Silverfish Dungeon, when you push a button, Silverfish are meant to come out and attack you so that you cannot run across the room to push the other button so easily.
As for the redstone being revealed, that is just a glitch and only sometimes occurs. Not a big deal :)
