### ISSUE TITLE
Weapons Texture Bug ! 

### ISSUE THREAD

**Issue by 7asoOonyi14** [Wynncraft/Issues#3681]
i loved the new weapons texture , even if the weapon is sucky i loved to use it , it looks amazing , specially getting an weapon that you need to identify , have all the excitement to identify it and see how strong it it and its Texture , i found this Bug where when you Drop the weapon , its Texture get shown , even when you hold it ! , but you cant see the abilities , its just the texture that get shown , hope this bug gets fixed , and we need to identify it to see it texture !

**Comment by HeyloLP** [comment]
there is already a ticket for this so please close this thread

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3318

Please direct any future comments to the original thread. Thanks!
