### ISSUE TITLE
Falling into void

### ISSUE THREAD

**Issue by Skrypted** [Wynncraft/Issues#3682]
Whenever I try to join a server from the hub I keep falling into the void through the blocks during the class selection menu. I cannot do /class and it keeps happening.

**Comment by Dar-krusos** [comment]
When you are in the class selection screen, you cannot do any command other than /hub. When in this menu, you must choose a class. If you the menu does not pop-up, try right-clicking to bring it up.
If the issue still persists, please reply back here.

**Comment by am987ab** [comment]
I think I am experiencing the same issue.  Right-clicking does absolutely nothing.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3521

Please direct any future comments to the original thread. Thanks!
