### ISSUE TITLE
Mob Names not showing

### ISSUE THREAD

**Issue by Komandoe** [Wynncraft/Issues#3683]
For some reason, the mob names aren't showing up, neither are the damage i'm dealing or the exp i'm receiving. I have the texture pack as you can see, and i'm running on 1.8.1 optifine (to help with my lag)

If you could please tell me what I can do to fix this, that'd be great.

![2016-01-13_17 59 27](https://cloud.githubusercontent.com/assets/16695546/12313876/76aadca4-ba20-11e5-9e27-7eab0e48901b.png)
Thats a pic^

**Comment by TrashcanMan** [comment]
I just scrolled through some of the old issues and apparently this will fix itself if you update Minecraft to the latest version (1.8.9 as of right now). Optifine is available for 1.8.9 so you should still be good.

**Comment by Komandoe** [comment]
Ah yes, it worked. Thanks!

**Comment by TrashcanMan** [comment]
If your issue is now resolved, please hit the "Close Issue" button at the bottom. Thanks!
