### ISSUE TITLE
Assassin multi hit

### ISSUE THREAD

**Issue by wynncraftlupascu** [Wynncraft/Issues#3686]
Now that we have the texurepack can u plss animate the multi hit tnx

**Comment by Dar-krusos** [comment]
Well this isn't an "issue", per se, so I don't think this belongs.
Requesting thread close.

But about that, what part of it do you mean? I thought there was already animation in it that pursued past the Gavel Update.

**Comment by Trixter313** [comment]
This would be better in the suggestions area of the forums https://forums.wynncraft.com/forums/general-suggestions.69/
