### ISSUE TITLE
Accessory set bonus activating when whole set isn't used

### ISSUE THREAD

**Issue by RapidReverze** [Wynncraft/Issues#3687]
So I was using the Jester Necklace but the set bonus was activated when I wasn't wearing the bracelet and ring. I hope you guys can fix this

**Comment by TrashcanMan** [comment]
The set bonus is supposed to do this, it activates to a certain extent depending on how many set pieces you have equipped. For example if an armor set gave you +50% XP for the full set, wearing only one piece might give you only +10%, or something like that.

**Comment by RapidReverze** [comment]
no but it said set bonus: -35xp and -35loot but i was only wearing necklace
and it decrease all of it

**Comment by DarkDemonDragon** [comment]
I can confirm this is an issue. I think players have begun to notice this as there has been a recent rise in Jester trading. Even only wearing the necklace only may sometimes provide just the buffs and not the de-buffs though this isn't as consistent.

The way the Jester set is supposed to work is that each stage of wearing gives different set bonuses.

1/3 Jester Set bonus: -35% Loot Bonus -35% Xp bonus
2/3 Jester Set Bonus (don't remember some values so I use "x"):
-75% Loot Bonus
-75% Xp bonus
+200 Melee Damage
+X Hp
-X Walking Speed

I don't know 3/3 Jester Set bonus.

These "Set Bonuses" are to balance the Jester Set as it is merely Unique yet can have very unusually high IDs. A good Jester Necklace gives 50+ Loot Bonus 50+ Xp Bonus and 2/2 Mana Steal. The Jester Ring gives 2-4 in FOUR skills and a good one gives 30+ in both Loot and XP. This is a very powerful set even with the Debuffs. It's perfect for Lv 100s as the main debuffs are in Loot and XP with some minor debuffs in Spell Dmg and Walking Speed.

**Comment by Trixter313** [comment]
Is this still occurring? A recent patch supposedly fixed some set related issues. ( https://forums.wynncraft.com/threads/gavel-patch-14-0-8.109965/ ) Thanks!

**Comment by Trixter313** [comment]
I'm going to assume that the issue is now fixed due to no response. If anyone is still experiencing it, simply comment and I'll reopen the issue. Thanks!
