### ISSUE TITLE
/fixquests broken

### ISSUE THREAD

**Issue by PhilipJohnsen** [Wynncraft/Issues#3688]
My /fixquests is broken, i threw away some of my quest items before gavel and now i can't complete temple of legends, and i have checked bank, other classes, etc.

**Comment by Dar-krusos** [comment]
Which items were they?

**Comment by DarkDemonDragon** [comment]
He probably means Maltic Letter of Recommendation, Corrupted Potato, Bob's Crushed Soul, etc. You'll need to provide images as proof that none of your classes have it and your bank doesn't have it.

**Comment by Trixter313** [comment]
What does /fixquests say when you try to use it? Also, you're sure you checked every class inventory and your bank? Thanks!

**Comment by Trixter313** [comment]
I'm assuming the issue isn't occurring anymore due to no response. If it is, simply comment and I can reopen the issue. Thanks!

**Comment by PhilipJohnsen** [comment]
No, it isn't an issue anymore, since i stopped on wynncraft due to a hack
and in the process i lost every item in my inventory on my main class.

2016-02-20 21:00 GMT+01:00 Nick Cipriani <notifications@github.com>:
