### ISSUE TITLE
Joined to find myself lost and without any items.

### ISSUE THREAD

**Issue by Conswaylos** [Wynncraft/Issues#3691]
I logged on to my level 81 Warrior to find that I wasn't in Cinfras where I had logged off but in a lake outside of Detlas without anything in my inventory except the compass, book, and soul points. I had no armor or weapons, any items at all. I went to my bank to find that most of my bank was empty, but it had some of the items that were supposed to be in my inventory (one of my weapons and a three pieces of armor, as well as some quest items that were actually in my ban). I wanted make sure it wasn't just a fluke so I /classed to check my other characters and found two of my other classes (assassin and hunter) were in the same situation, itemless and in that same lake outside of Detlas.

**Comment by Dar-krusos** [comment]
Sounds like someone didn't like you, logged onto your account and threw away your items >.>

Nah, but that's really, really odd. Hope someone can solve that for you.

**Comment by BlahBlah161616** [comment]
It's one of two things, either the server glitched, and deleted everything, or your account was hacked.

I recommend changing your MC password just in case.
