### ISSUE TITLE
Wynncraft: Not Leveling Up

### ISSUE THREAD

**Issue by SlipperySlimYT** [Wynncraft/Issues#3692]
I've been playing Wynn a lot more now, so I've been doing some quests. When I completed Worm Holes, I didn't level (when I should've) and quests haven't been giving me levels. What is wrong?

**Comment by Dar-krusos** [comment]
It depends. What level are you?

**Comment by TrashcanMan** [comment]
If you're in a guild, check your guild XP donation percentage, maybe you're donating too much XP.

**Comment by SlipperySlimYT** [comment]
We'll I am donating about 10% of my XP and I am lvl 59.

On Thursday, January 14, 2016, TrashcanMan <notifications@github.com> wrote:

> If you're in a guild, check your guild XP donation percentage, maybe
> you're donating too much XP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/3692#issuecomment-171835077>.
>


-- 
-A Dikoson

**Comment by DarkDemonDragon** [comment]
Some quests simply don't give as much xp as others.

**Comment by SlipperySlimYT** [comment]
Yah, but I have done Worm Holes, and about 3 other quests and stayed at lvl
59 when I should be at lvl 62 with my friend.

On Friday, January 15, 2016, DarkDemonDragon <notifications@github.com>
wrote:

> Some quests simply don't give as much xp as others.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/3692#issuecomment-171959434>.
>


-- 
-A Dikoson

**Comment by ohyeah1357** [comment]
There is something wrong with your question. Is your XP bar moving up or not?

**Comment by Dar-krusos** [comment]
Try changing your guild donation to */guild xp 0* and see if that works.

**Comment by SlipperySlimYT** [comment]
It has been moving up, but barely any. Just like I've said, I've done
about 4 quests after getting lvl 59 and my XP bar has barely budged.

**Comment by meatloaf4311** [comment]
Check to see if you are wearing armors with -% xp bonus, I have scene that before

**Comment by Trixter313** [comment]
Is this still happening to you?

**Comment by DarkDemonDragon** [comment]
Is this still happening to you?

**Comment by SlipperySlimYT** [comment]
I don't go on Wynncraft a lot, but no, this is not happening anymore.

On Thursday, March 24, 2016, DarkDemonDragon <notifications@github.com>
wrote:

> Is this still happening to you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/3692#issuecomment-200807506>
>


-- 
-A Dikoson

**Comment by Trixter313** [comment]
Glad to hear!
