### ISSUE TITLE
Random Lag Spikes and Random Kicks for "flying"

### ISSUE THREAD

**Issue by BlahBlah161616** [Wynncraft/Issues#3695]
The addition of armor skins makes most servers unjoinable, and also you randomly get kicked for flying. In addition, everything lags. It makes the game near unplayable. Please fix this.

**Comment by BlahBlah161616** [comment]
Also my health tag says I have full, my vanilla bar of heart says different,

**Comment by Dar-krusos** [comment]
Read this please. https://github.com/Wynncraft/Issues/issues/3685
Please check the Github for the same issue before posting a thread.
