### ISSUE TITLE
Some missing armor skins

### ISSUE THREAD

**Issue by ohyeah1357** [Wynncraft/Issues#3697]
Snow Helmet
Sodeta Boots
Cloak of Luminosity
Clock Boots
Skeletal Legs

And basically everything else that is something from a quest or something that has been missing pre-gavel.

**Comment by Dar-krusos** [comment]
Shhhh. Don't let them know. We want to be able to see our skins.

Shhhhhhhhhhhhhh.

**Comment by EnglishCamper** [comment]
More armour pieces that don't have skins; Veekhat's Udders and Veekhat's Horns

**Comment by Dar-krusos** [comment]
Same for
Changeling's Chestplate
The Kaerynn armor set

**Comment by Trixter313** [comment]
Is this still affecting all of the armors listed above? Thanks!

**Comment by Moe-Ronickah** [comment]
I know that Sodeta Boots, Cloak of Luminosity, Veekhat's Udders, Veekhat's Horns, Changeling's Chestplate, and The Kaerynn armor set all work.  So, after this long, without any further issues showing for the three that I are left, we can take it that those are fixed, also.
