### ISSUE TITLE
chestplate bugged

### ISSUE THREAD

**Issue by Rentokraft** [Wynncraft/Issues#3698]
![2016-01-15_15 36 43](https://cloud.githubusercontent.com/assets/16392627/12348904/fede2b98-bb9d-11e5-8653-ddfac979a1df.png)

**Comment by alfredchi** [comment]
I got the same problem with it, plus its a chestplate named "montefiore" i wish it helps

**Comment by Dar-krusos** [comment]
This is a recurring bug that occurs with chestplates that contain special letters and characters in their name, which causes them to be like this. A similar glitch happened with identifying them prior to the Gavel Expansion and they fixed that one. This bug should be fixed accordingly.

**Comment by DarkDemonDragon** [comment]
Duplicate of #3175

Please close this issue and direct any future comments to the original thread. Thanks!
