### ISSUE TITLE
le

### ISSUE THREAD

**Issue by wynncraftlupascu** [Wynncraft/Issues#3699]
i can throw le

**Comment by Dar-krusos** [comment]
Yeah, this seems to happen when you are lagging quite a bit or at random times. Just try not to puy it in your hotbar too often, and even then, don't hold it ever. o.o

**Comment by DarkDemonDragon** [comment]
Yea what @Dar-krusos said. Unless you're doing a quest that requires it or you're trading, do NOT hold your LE especially in your hotbar.
