### ISSUE TITLE
Creeper infiltration bugg

### ISSUE THREAD

**Issue by Castelaization** [Wynncraft/Issues#3701]
i cant complete the creeper infiltration mission because i cant get green powder

**Comment by RubixNubix** [comment]
How is this a bug... It just means your luck is bad. Plus, powders are broken for now so your out of ouck

**Comment by Trixter313** [comment]
If you want to do the quest, you will have to buy green powder form someone for now.

**Comment by meatloaf4311** [comment]
The only way to finish is to buy a powder off of someone.


If you have fixed the issue, please close the issue. If not gives us an update.
