### ISSUE TITLE
Untradable armor pieces not shown on skin

### ISSUE THREAD

**Issue by Forcellrus** [Wynncraft/Issues#3703]
As the title says, in my armor set, I can only see boots on my skin, nothing else. Everything else is not drawn on my skin.
Check out screenshots here, notice that only boots are tradable: http://imgur.com/a/NfwJI

**Comment by ohyeah1357** [comment]
It's usually items from quests in general that don't show. However, some exceptions to this are the Mummy's Rag and Champion Armour.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3697

Please direct any future comments to the original thread. Thanks!
