### ISSUE TITLE
Bugged thorugh wall...

### ISSUE THREAD

**Issue by lXetnosl** [Wynncraft/Issues#3704]
I somehow bugged through the wall next to the pressure plate/button in the tree at X: -1115 Z: -5490

![2016-01-15_17 39 04](https://cloud.githubusercontent.com/assets/16638925/12358775/2dd92306-bbaf-11e5-8e64-891109d00e4a.png)
![2016-01-15_17 39 32](https://cloud.githubusercontent.com/assets/16638925/12358774/2dd7d7ee-bbaf-11e5-80a3-7e1dc14d55bb.png)
![2016-01-15_17 40 21](https://cloud.githubusercontent.com/assets/16638925/12358772/2dd65b76-bbaf-11e5-8dc1-204a38b90936.png)
![2016-01-15_17 42 19](https://cloud.githubusercontent.com/assets/16638925/12358773/2dd67750-bbaf-11e5-947d-d3d7581a9c65.png)

**Comment by lXetnosl** [comment]
Dont know what to do xD HELP

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will bring you to the nearest visited town.
