### ISSUE TITLE
Can't create Guild

### ISSUE THREAD

**Issue by Casper315** [Wynncraft/Issues#3705]
I can't create a guild, when I type in the name I want I get an error: Please only use English characters A-Z in your guild name. I want the name Delta Warriors  as guild name.

**Comment by Troll2828** [comment]
There's a bug with guilds at the moment, just wait until they fix it or join a guild instead of creating one.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3190

Please direct any future comments to the original thread. Thanks!
