### ISSUE TITLE
Barrier Bug

### ISSUE THREAD

**Issue by devzrafter** [Wynncraft/Issues#3708]
Hello,
I have just tried to climb the walls near to Ragni (I am a mage). So I used the teleport spell to go upwards and now I am in a barrier block.
Perhaps you could check if a player is in a barrier block and port out.
I would be nice if you can port me out :)
Hope it can help you improving this awesome server
MyJojoX

Here is a screenshot (https://cloud.githubusercontent.com/assets/11852677/12363918/d52f51e0-bbcb-11e5-8f08-0b39019f8278.png) :

**Comment by devzrafter** [comment]
Fixed my situation myself - using /kill :)
but the problem still exist (porting into a barrier block)

**Comment by Trixter313** [comment]
I'm pretty sure if you try hard enough you can get stuck in any block using teleport but it shouldn't really happen if you don't try.
