### ISSUE TITLE
I Keep getting Teleported into the void and cant play

### ISSUE THREAD

**Issue by ThomasDomo** [Wynncraft/Issues#3709]
i Keep spawning in a wood house and within less than a second after, i get teleported to a stone island in the void and i spawn under it so i fall into the void and i cant use any commands and i cant die so I'm stuck to fall forever

**Comment by Dar-krusos** [comment]
I think that is the class selection room. Try doing a right-clicm to bring up the menu.

**Comment by am987ab** [comment]
I think I am experiencing the same issue.  Right-clicking does absolutely nothing.

**Comment by Trixter313** [comment]
Do you guys have the server resource pack enabled? You can check by selecting Wynncraft in the servers menu, clicking edit, then making sure it says enabled for the resource pack.
