### ISSUE TITLE
Pelier Helmet Broken

### ISSUE THREAD

**Issue by DaDominat0r** [Wynncraft/Issues#3710]
The helmet doesn't give me any more health and the name and lore of the helmet is glitched out.

![2016-01-15_17 22 53](https://cloud.githubusercontent.com/assets/10334102/12369484/d5d90632-bbac-11e5-9c8d-7324f4b88120.png)
![2016-01-15_17 22 59](https://cloud.githubusercontent.com/assets/10334102/12369485/d8cfb5c0-bbac-11e5-9aaa-c0a7470b64e2.png)

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!
