### ISSUE TITLE
Holes to get stuck in

### ISSUE THREAD

**Issue by Lake902** [Wynncraft/Issues#3711]
http://imgur.com/a/rWSr8

**Comment by Moe-Ronickah** [comment]
The builders have been known to make those types of holes on purpose.  Usually, they are 1x1 or 1x2.  If they are any deeper, then yes, it is probably a flaw.  So, I'm going to call the upper image as an intentional trap.  I can't make out where the problem is in the lower image.

**Comment by Villageacules** [comment]
Fixed, patch will be in follow up update.

**Comment by Moe-Ronickah** [comment]
See above.
