### ISSUE TITLE
where are all my stuff

### ISSUE THREAD

**Issue by atax360** [Wynncraft/Issues#3714]
when i have like 10 deaths i haven't stuff, like when i respawn all the gear i have, all the wepons that i farm, and all the money i collect, have gone, plz can fix that

**Comment by slendersir739** [comment]
When you lose 10 soul points, you lose everything you have.

**Comment by RubixNubix** [comment]
If you die 10 times in a row, you lose all your items.
This is to prevent the player being "invincible" and rush into things with no consequence.
