### ISSUE TITLE
Eye of the Storm puzzle not appearing.

### ISSUE THREAD

**Issue by keviny3** [Wynncraft/Issues#3715]
This might just be me not noticing a "start" button of some sort, but all of the guides I have looked at don't seem to suggest there is any need to press any buttons or step on any pressure pads to start the puzzle in Eye of the Storm.

Basically, the buttons and item frames e.t.c aren't appearing and the actual puzzle itself seems to be on the third stage, not the first.

![2016-01-16_17 46 16](https://cloud.githubusercontent.com/assets/16396163/12370982/282b3eb0-bc79-11e5-8c88-d8b44862d474.png)
![2016-01-16_17 41 40](https://cloud.githubusercontent.com/assets/16396163/12370969/9ef7a1ba-bc78-11e5-8e7b-700eef7a221d.png)
![2016-01-16_17 41 31](https://cloud.githubusercontent.com/assets/16396163/12370970/9ef9a94c-bc78-11e5-9ef0-dded72923fd0.png)

**Comment by Dar-krusos** [comment]
Sometimes it just takes a bit of time for it to open. If not, try re-doing the puzzles on another server.

**Comment by keviny3** [comment]
I logged onto another server, and it seems to work.

**Comment by Trixter313** [comment]
Glad to hear =)
