### ISSUE TITLE
My wepon lost its stats and code things

### ISSUE THREAD

**Issue by PotatoMan2507** [Wynncraft/Issues#3716]
![2016-01-16_19 09 48](https://cloud.githubusercontent.com/assets/16524812/12371428/7e5a5aec-bc87-11e5-8538-31b8c75d97e2.png)

**Comment by Dar-krusos** [comment]
Issue #3175

**Comment by PotatoMan2507** [comment]
so how do i fix it?

**Comment by Dar-krusos** [comment]
Right now, you can't. You'll have to let the developers fix that ;)

**Comment by PotatoMan2507** [comment]
awwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

**Comment by Trixter313** [comment]
Please direct any future comments the original issue, linked above. Thanks!
