### ISSUE TITLE
WynnExcavation Site D Can't talk to king Ragni to finish the quest

### ISSUE THREAD

**Issue by MART1N1** [Wynncraft/Issues#3717]
Finished the boss fight with Amadel and teleported to Ragni but the King 's dialogue is "Off you go, I've said everything I have to say." instead of the normal dialogue. Quest book also says Talk to king of ragni

**Comment by Dar-krusos** [comment]
I don't think you should be in the Ragni area. You should be in a spacey, closed-off room where the King is standing next to the black teleport hole.

**Comment by MART1N1** [comment]
Thanks did not realise that there was a Ragni King NPC right after the final fight probably lag.

**Comment by Dar-krusos** [comment]
No problem ;D
