### ISSUE TITLE
Had no idea armour needed stats now, may i have stat reset?

### ISSUE THREAD

**Issue by Tozzu78** [Wynncraft/Issues#3721]
i had no flippin idea i needed to have some stats for armour so im asking for a stat reset, im still in the update hub :P

**Comment by Troll2828** [comment]
Don't reset your skill points just to wear a piece of armor, choose like 2-3 elements and skill them. Also, wear armor that buffs your elements. This can help you: https://forums.wynncraft.com/threads/gavel-survival-guide-how-to-be-effective-with-the-new-combat-system.100081/

**Comment by Tozzu78** [comment]
i dont know if i should start over or just get new armour in a shitty helmet .-.

**Comment by Trixter313** [comment]
The only options are living with not being able to wear or use certain things for a bit until you level up and get more skill points to even everything out or you can do the quest Tower of Amnesia and buy a kill reset scroll for a LE. Hopefully it isn't too much of an inconvenience!
