### ISSUE TITLE
Can't Identify certain Items

### ISSUE THREAD

**Issue by ThatGuyDerp1** [Wynncraft/Issues#3722]
After the update, a few of my items are unidentifiable. I have a chest piece that I was wearing before the Gavel update, and my legendary spear Fierte. Both of these items will not identify. 
![2016-01-16_06 47 40](https://cloud.githubusercontent.com/assets/16732473/12372200/a411f714-bc1d-11e5-9b77-1dfd3a6e614b.png)

![2016-01-16_06 47 19](https://cloud.githubusercontent.com/assets/16732473/12372201/b349a880-bc1d-11e5-837d-0fc70c68bad3.png)

![2016-01-16_06 47 17](https://cloud.githubusercontent.com/assets/16732473/12372202/b85ee060-bc1d-11e5-85df-b788c30bef7f.png)

**Comment by Dar-krusos** [comment]
Ah, those items with special names. You see, both of those have accents in them, and most of these type of items are bugged in some way.
See Issue #3175 for more details and to comment on that thread. No further replies are needed here.
