### ISSUE TITLE
Armour piece doesnt have any effects bug

### ISSUE THREAD

**Issue by Sharn1337** [Wynncraft/Issues#3724]
![screenshot 59](https://cloud.githubusercontent.com/assets/16733021/12372471/956477a2-bc93-11e5-886d-e012aff2e18d.png)

my armour piece isnt giving me the effects. please fix this. it just shows a bunch of commands/codes

**Comment by Dar-krusos** [comment]
What is its name? I think it might have special letters in its name, so that might be the reason it's bugged. See Issue #3175, and if it is the same problem you're having, please close this current thread and watch out for any dwvelopments on thread #3175.
