### ISSUE TITLE
Weird Item Called Damassÿyÿy

### ISSUE THREAD

**Issue by ReyDeLosCreepers** [Wynncraft/Issues#3725]
Is it glitched, before it said it was a unidentified
![2016-01-16_10 10 11](https://cloud.githubusercontent.com/assets/13819381/12373021/9baba1bc-bc39-11e5-9c76-f238ee05fc17.png)
 leggings level 0 - 4

**Comment by Dar-krusos** [comment]
Yeah, this is a glitch in which items with special characters in their name become like this. Please look at issue #3175 as this is the same problem.
