### ISSUE TITLE
No weapon and armour merchant in Thanos

### ISSUE THREAD

**Issue by Forcellrus** [Wynncraft/Issues#3726]
There is his house with item frames saying "Weapon merchant" when pointing to them, but there is no NPC inside. Same applies for armour merchant.

**Comment by Trixter313** [comment]
Have you tried looking on another world?

**Comment by Forcellrus** [comment]
I did, you can also check it yourself.

**Comment by Trixter313** [comment]
Are the merchants still missing? Thanks!

**Comment by DarkDemonDragon** [comment]
I have confirmed that the merchants have returned from their vacations and are now there 24/7. Please close this as the issue has been resolved.

**Comment by Trixter313** [comment]
Thanks! =)
