### ISSUE TITLE
Rise of the Quatron - Planted Quest Item

### ISSUE THREAD

**Issue by Plobby** [Wynncraft/Issues#3727]
As the title would imply, I have managed to plant the necessary quest item needed to complete the quest "Rise of The Quatron". I managed to right click the flower pot in the back of the cave with the Elf in and planted the flower, losing it from my inventory and finding myself unable to get it back and instead just stare it at. Upon relogging the flower is still visible in the pot to me but not in my inventory. The Elf refuses to give me another one. The world that you may find a flower in is World 28. As a result of my stupidity with flowers, I am unable to talk to the next quest NPC and can't proceed with the quest.

I would appreciate if I could get a flower so I can finish the quest, or some alternative that allows me to gather another one. My apologies for my stupidity on this area. My in-game name is plobnob, just incase.

Thanks.

**Comment by Troll2828** [comment]
do /fixquests

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Plobby** [comment]
Thank you. Was unaware of this command up until now. :)
