### ISSUE TITLE
Glitch with a special signed wand

### ISSUE THREAD

**Issue by lead8964878** [Wynncraft/Issues#3729]
I got a wand last night... pretty love its mana regen effect
but when I just login and try using spells... i saw it became like this
![698](https://cloud.githubusercontent.com/assets/16736535/12373952/567e941c-bcc7-11e5-9b60-09b423e08dd5.jpg)
can't spell and even attack... let me feel kinda weird and upset :(

It's content is like this
![12321](https://cloud.githubusercontent.com/assets/16736535/12373957/91db87e0-bcc7-11e5-865d-23b18bce2f77.jpg)
Too long to take the whole part
The value of ability all became just nametag :<
Im guessing its like the name of the wand make this happened

ID:HanaKuru

**Comment by Dar-krusos** [comment]
Issue #3175

**Comment by Trixter313** [comment]
Please direct any further comments to the original thread, linked above. Thanks!
