### ISSUE TITLE
Null message confusing riddle

### ISSUE THREAD

**Issue by Empty2k12** [Wynncraft/Issues#3732]
At -1859 23 -4917 there is a riddle that requires you to step on a pressure plate indicated which wrks fine. When the postion opens and you try to go into the hole the PlayerMoveEvent is cancelled causung you to be teleported back on top of the hole just to fall in again. When the piston closes again you can glich back to a secure position. Every time you are getting teleported back up it also prints "null" in chat. Also the cave features no mobs.

![2016-01-16_21 33 57](https://cloud.githubusercontent.com/assets/6954968/12374368/d6055b9a-bc99-11e5-9ac9-b3d2a2698c59.png)

**Comment by Empty2k12** [comment]
Turns out it is related to a quest and if you are supposed to go there it works. Also the tp at the end of the quest tp's into a solid block, /kill was needed!

**Comment by Empty2k12** [comment]
@Trixter313 why did this get closed? The tp glitch and null printing sttill exists!

**Comment by Trixter313** [comment]
You said that if you are doing the related quest it works correctly, right?

**Comment by Empty2k12** [comment]
Yes, but if you don't have the quest active it is still buggy and prints
out null, might even be a area without the "quest to enter required" text.

**Comment by DarkDemonDragon** [comment]
Weird when I did this quest I didn't come across this. We might need some confirmation on this.

**Comment by Moe-Ronickah** [comment]
I just ran this quest, today, and all of the issues were fixed.  No idea when they were fixed, but they are fixed.
The "Null" isn't a problem.  It's simply a Java message.
