### ISSUE TITLE
Cant resolve hostname

### ISSUE THREAD

**Issue by sarah7272665** [Wynncraft/Issues#3733]
I cant connect to the server and its saying its because it "cant resolve hostname". I was able to get on earlier please help!

**Comment by Dar-krusos** [comment]
That means something on your end is going wrong

**Comment by Trixter313** [comment]
Try restarting your computer, and if that doesn't work, your router.
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by sarah7272665** [comment]
It worked! Thanks so much ^v^
