### ISSUE TITLE
Lost 4 defense skill

### ISSUE THREAD

**Issue by SageSlay** [Wynncraft/Issues#3734]
I had a total of 18 defense skills/points now I have only 14. I was using kamikaze which required a defense skill of 18 and when I reached level 30 (by finishing the quest The Mercenary) in the game I used the 2 skill points on dexterity and intelligence but somehow lost 4 points on defense. I don't have any images of me originally having 18 skill points of defense but can someone figure out how many total skill points a level 30 player is suppose to have in total?
![image](https://cloud.githubusercontent.com/assets/16737462/12374445/a99e97f4-bc69-11e5-95d0-ae54c612421f.png) 
![image](https://cloud.githubusercontent.com/assets/16737462/12374458/45690c50-bc6a-11e5-8fd6-2e65b0af0d39.png)

**Comment by Dar-krusos** [comment]
That Kamikaze right there has "-2 Defense" which means the other missing two might be due to another armor.

Remember that armor and weapons can now remove or add Skill Points to you, so if you hover over a Skill Point, it should say in green text that the skill has been modified.
