### ISSUE TITLE
Lost my full legendary, formely Best-In-Slot-Armor :C

### ISSUE THREAD

**Issue by Felixo240300** [Wynncraft/Issues#3735]
So yeah, joined Wynn for the first time in months as i saw we finally got Gavel. At some point, i was seeing there are now ring, amulet etc slots, and i was curious what would happen if i pulled some stuff into these slots. 
Well, as i pulled one part of my legendary armor into one of these slots, all of my armor suddenly disappeared. Altho i don't really play this game as often anymore, i would appreachiate if some Mod could rollback my account or something, as i remember that I've worked hard for this set of armor, which used to be BiS. If I remember correctly, there names were Blue Mask, Adamantide, Crystal and Stalagmites. Thank you.
(Ingame Name: Felixo240300)

**Comment by Dar-krusos** [comment]
Yeah this happens when your inventory is full and and you try to take off armor that you are not eligible to wear. I'm really, really sorry, but the admins and mods have an absolute non-refund policy, in precautions that some players might use this to cheat.

**Comment by RubixNubix** [comment]
1) Sorry :( Strict no refund policy
2) No offense, but why would you try do put stuff in the accessories slot? Why not try an emerald instead of your armor
3) Blue mask, stalagmites, etc kinda suck now •3•
4) Have fun getting your stuff back... Heh... Heh

**Comment by Felixo240300** [comment]
Aww. :c
Whatever, playing real MMOs now anyways.
Just out of curiosity: How much would that set have been worth?

**Comment by Trixter313** [comment]
Like above people said, Wynncraft has a strict no refunds policy so getting the already lost items back probably won't happen but we are working on fixing the issue that they are just plain deleted instead of dropped on the ground. Also, the entire server and all players would have to be rolled back so I don't think that is an option either. Hopefully it isn't too much of an inconvenience!
