### ISSUE TITLE
weird item??

### ISSUE THREAD

**Issue by Azrior** [Wynncraft/Issues#3736]
No words. just look.

https://gyazo.com/6f0e0628fc8b69fbffc514a5a952ca23

**Comment by Dar-krusos** [comment]
Oh, this issue was posted only a few gours ago, so please do check the Github for similar issues as we do not like duplicates.

The first issue is #3175, where ou should post there instead.

**Comment by Azrior** [comment]
Sorry, I Was told to post it by MrSebbelonien o.e

**Comment by Dar-krusos** [comment]
No problem, but remember to check the Github for similar or related issues before posting one :)
