### ISSUE TITLE
armor wont load on skins

### ISSUE THREAD

**Issue by Darknanowolf** [Wynncraft/Issues#3739]
The armor wont load on my skin any armor i will get a whole new set and still it wont load

**Comment by Satsuki9** [comment]
I have the same problem

**Comment by Dar-krusos** [comment]
Are you guys up to date with the latest version of minecraft (1.8.9)?

**Comment by Trixter313** [comment]
Have you tried typing /armors
This is the command to disable/enable armor skins I believe.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by HeroTheZero** [comment]
/armors isn't a command ;-; also  i have the same problem and its infuriating!

**Comment by Darknanowolf** [comment]
Nope that command dose not work as well ever once in a bit an Armor will
show

**Comment by HeroTheZero** [comment]
My montefiore is broken! my armour won't load!! the only thing that loaded was my chestplate because i had if off before teh new update! please fix my montefiore chestplate and my armour cuz it won't draw!

**Comment by Trixter313** [comment]
Oh, sorry, the command is /armour

**Comment by HeroTheZero** [comment]
ok... i'll test that soon, but how about my broken chestplate? i hae a crappy leather chestpltae now since my main is broken
all it shows is purple writing instead of bonuses

**Comment by Trixter313** [comment]
As for the chestplate, follow https://github.com/Wynncraft/Issues/issues/3175 to see when it is fixed. There's nothing the player can do about it and admins must fix it.

**Comment by HeroTheZero** [comment]
doesn't work.... please get  us the legit command

**Comment by Trixter313** [comment]
Hopefully that command should be working soon. Salted posted the command here https://forums.wynncraft.com/threads/gavel-patch-14-0-6.105366/ but it doesn't appear to be working yet.

**Comment by HeroTheZero** [comment]
yo, can you come to world 4 and fix my montefiore? i can't even use it because the armour broke. plus none of my armour skin works, except helmet and this shitty chestplate
w

**Comment by Dar-krusos** [comment]
You can also use /armor.

@HeroTheZero:
Some armor doesn't have skins yet (which will be fixed).

**Comment by Trixter313** [comment]
Are people still experiencing this issue since the latest patch? Thanks!

**Comment by Trixter313** [comment]
I'll close this due to no response but if anyone still experiences this, simply comment and I'll reopen it. Thanks!

**Comment by mdragonwhite** [comment]
I still have this problem, i cant see my amour, i already tried everything
