### ISSUE TITLE
Jester necklace/set

### ISSUE THREAD

**Issue by Tom886** [Wynncraft/Issues#3740]
Whenever I use the Jester necklace, I get the perks of the full set. I think its bug, because i'm not wearing the full set, I could be wrong.

http://prntscr.com/9r3eja

**Comment by Dar-krusos** [comment]
It's fine, nothing's wrong. The set bonus that is displayed shows what happens when you only have one piece on. When you have two pieces of the set on, it will change, and the same goes for when you wear even more pieces of the set.
