### ISSUE TITLE
Invisibility issue

### ISSUE THREAD

**Issue by Zavier50** [Wynncraft/Issues#3743]
For some reason, I appear invisible to everyone in game. I can see them, and they can see each other, but they can't see me. Any suggestions?

**Comment by TrashcanMan** [comment]
Can the other people see you interacting with other stuff? Eg if you hit a mob can they see the mob being hit? If not, then this might be a connection/lag issue on your end.

**Comment by Trixter313** [comment]
Try typing /class or going to a different world #.

**Comment by DarkDemonDragon** [comment]
This typically happens during armor applying onto your skin and a lag spike happening at the same time. The result is a very strange skin lag that removes your skin completely. You're not invisible by effect, but you simply do not have a skin to be seen by other players. This typically goes away after changing your armor again or doing /armor.
