### ISSUE TITLE
Names and levels of mobs are not visible

### ISSUE THREAD

**Issue by Faszultan** [Wynncraft/Issues#3744]
Hello there,

I can't see the names and levels of mobs, so I don't know who I am facing with. I always go with my friend so he can tell me the levels. How to fix this?

Thank you :)

**Comment by TrashcanMan** [comment]
This should resolve itself if you update to the latest version of Minecraft (1.8.9).
If your issue is now resolved please hit the "Close Issue" button. Thanks!
