### ISSUE TITLE
Weapon bug

### ISSUE THREAD

**Issue by Drake2100** [Wynncraft/Issues#3745]
I can't use my weapon because it has no power. When I see its stats I  only see a purple name like "damage point, intelligence" ecc... that means that the server doesn't download my weapon. I've restarted the game like 6 times, but nothing

**Comment by TrashcanMan** [comment]
Known issue, some items are broken right now.

**Comment by Trixter313** [comment]
Please direct any future comments to the original thread, linked above. Thanks!
