### ISSUE TITLE
Bob's Reincarnation Glitch!

### ISSUE THREAD

**Issue by fredesuper** [Wynncraft/Issues#3746]
Alright. So there I was, soloing Bob. I got him down to 10k health, on my own, when all of a sudden, he glitches out of the arena... he did this several times where I was soloing him. It got to a point where I was freaking out to my friend about of annoying it was. I did this on my warrior, the skill that got him outside of the arena was war scream. This skill is a pretty essential part of the boss fight, so no, I can't just not use it. Doesn't work like that. If you could fix this, that would be amazing. Thanks for reading.
![2016-01-17_17 49 28](https://cloud.githubusercontent.com/assets/10280751/12378588/e139ae36-bd42-11e5-8e99-9d1998d3c9c3.png)
![2016-01-17_17 49 31](https://cloud.githubusercontent.com/assets/10280751/12378589/e5ee7484-bd42-11e5-8999-d0ace04d36d0.png)
![2016-01-17_17 49 33](https://cloud.githubusercontent.com/assets/10280751/12378590/ea9a6452-bd42-11e5-89de-ec8f1797ac04.png)

**Comment by Trixter313** [comment]
I have added this to #3191 and referenced this issue. Thanks for adding more information!
