### ISSUE TITLE
ToA floor 6 Boss bug

### ISSUE THREAD

**Issue by Troll2828** [Wynncraft/Issues#3747]
So I was doing ToA floor 6 with a warrior alongside a mage and an archer. the floor wasn't hard and we got to the boss fight, but it's impossibe. The boss has a special ability called suicide-strike, when this ability triggers, he explodes. The problem is that he uses this every 5 seconde so it's impossible to get him down to 0 hp. I would like this to be fixed, I want to finish ToA.

**Comment by Dar-krusos** [comment]
You'll have to do constant damage to him otherwise he'll suicide. Try getting more players to help.

**Comment by Troll2828** [comment]
Thank I'll try.
