### ISSUE TITLE
Quest: Hollow Sirine

### ISSUE THREAD

**Issue by 1Entropy** [Wynncraft/Issues#3748]
In the middle of the quest my quest book stopped updating, and I can no longer finish this quest. My quest book just keeps telling me to solve the puzzle and get the ear muffs, but when I solved the puzzle and got the ear muffs it did not update. I tried just going into the banshee cave anyways, while wearing the ear muffs I had acquired, to see if I could finish the quest. But I get teleported away and it says something along the lines of: "you should not enter here without the proper protection", even when I'm wearing the ear muffs. I have tried re-talking to every quest NPC in this quest, getting rid of the ear muffs and resolving the puzzle to get new ear muffs, as well as just running into the cave with banshee in it, but I cant get my quest book to update. If this problem could be resolved I would greatly appreciate it. My suggestion (if possible) is to have an admin reset the quest for just my account so I can start from the beginning of the quest again. This might resolve the problems I'm experiencing, thank you for reading. My IGN was

**Comment by Dar-krusos** [comment]
There should try going back into the crypt, because there's a quest trigger there that I missed as well. I think it was near the stairs of the crypt, so don't use any spells when entering.
