### ISSUE TITLE
D__voreuse Wand

### ISSUE THREAD

**Issue by Pastams** [Wynncraft/Issues#3749]
Hello
I found this wand and indentified it. The result is on screenshots. 

![](http://i.imgur.com/2uKVBta.png)

![](http://i.imgur.com/lo6OAx2.png)

![](http://i.imgur.com/F4smb7z.png)

![](http://i.imgur.com/CR5XmPr.png)

**Comment by TrashcanMan** [comment]
Known issue, many items, especially ones with accented characters in their names, are broken right now.

**Comment by Trixter313** [comment]
Please direct any future comments to the original issue, linked above. Thanks!
