### ISSUE TITLE
Mountain teleport bug

### ISSUE THREAD

**Issue by MichaelKimTime** [Wynncraft/Issues#3752]
I am mage lv 15 and I was trying to see what is in the top of the mountain so I was teleporting up and now I am trapped by invisible blocks and do nothing... I would like it if you fix the bug and teleport my mage into the spawn of Rangi spawn

**Comment by Troll2828** [comment]
do /kill if you have 3 soul points of more.

**Comment by MichaelKimTime** [comment]
Thank you
