### ISSUE TITLE
Thanks wynncraft You're Doing a great job!

### ISSUE THREAD

**Issue by maccamoppy** [Wynncraft/Issues#3753]
too much of an inconvenience... well it was, you probably don't know how long it takes to get good fucking armour the hours spent grinding to get this and when you guys fuck up, we can get our hours of grinding wasted for some armour that we can't get back... well fuck it was a massive inconvenience this is stupid. you should've ended your sentence like "Well we don't care that much about the players so fuck your armour cunt, Sorry for your loss."

no compensation or anything like that at all?...
 
No refund policy? this isn't really a refund... its more of a wynncraft fucked up when they made an update. its your guys fault that i lost my stuff, it shouldn't have to be "well we fucked up" and your not getting your stuff back.

Plus i have no idea what i had anymore so you guys probably can't fix this anyways but i find it stupid that you don't even try to help somehow. You guys wanted this to be an mmorpg kind of server people spend hours on it to try get good armour and when you guys stuff up you don't have some way for fixing this? you just say oh sorry good luck nerd.

On Mon, Jan 11, 2016 at 1:57 AM, Nick Cipriani <notifications@github.com> wrote:
Items will be unidentified when you first login since the Gavel update, but it is currently a bug where instead of dropping unidentified worn armor on the ground when the inventory is full, it just disappears. Due to Wynncraft's strict no refunds policy, not much can be done about the already lost armor but we are working on fixing the issue of them disappearing in the first place. Hopefully this wasn't too much of an inconvenience!

**Comment by Trixter313** [comment]
This isn't a bug report and probably belongs on the Wynncraft forums instead, here https://forums.wynncraft.com/

Thanks!
