### ISSUE TITLE
Green Skinned Trouble quest reset

### ISSUE THREAD

**Issue by Afkor** [Wynncraft/Issues#3757]
A weird glitch is going on that makes this happen-
![2016-01-17_22 53 27](https://cloud.githubusercontent.com/assets/16751844/12383046/10ed1c40-bd6f-11e5-9b4f-e4d9870a02ff.png)
I do not have the magical axe, and cannot give anything to the detective either way as he asks for the axe heads from earlier. This happened after I was block glitched into one of the portals underground in the middle of this quest. I killed myself, respawning in the nearest town. My quest book had been updated and I had no axe.

**Comment by slendersir739** [comment]
Then just go back to Gregg'r's cave. You have to kill Gregg'r for the axe.
