### ISSUE TITLE
servers closed

### ISSUE THREAD

**Issue by wynncraftlupascu** [Wynncraft/Issues#3762]
![2016-01-18_18 59 32](https://cloud.githubusercontent.com/assets/14152318/12397415/c7371ef0-be15-11e5-868b-08f1e2305c6b.png)
![2016-01-18_18 59 25](https://cloud.githubusercontent.com/assets/14152318/12397419/cb04474c-be15-11e5-899c-29bfebe566cc.png)
![2016-01-18_18 59 30](https://cloud.githubusercontent.com/assets/14152318/12397421/cd15e946-be15-11e5-8e07-5789d5afbab9.png)

**Comment by ThatGuyDerp1** [comment]
This is ridiculous. It's been a problem for over 12+ hours...

**Comment by Trixter313** [comment]
Should be fixed now. =)
