### ISSUE TITLE
ToA Floor 6 Boss

### ISSUE THREAD

**Issue by Perifidite** [Wynncraft/Issues#3763]
The tower of ascension floor 6 boss is impossible to kill. Let me explain, his special ability is exploding himself and in the process dying (kamikaze). When he does die from the explosion he doesn't drop the item that allows you to advance. He spams his special ability, so right as he spawns he would smack you in the face and be like "bye bitch," and die. I couldn't get him down to 80% hp, because he would just kill himself by then.

**Comment by Trixter313** [comment]
As said in https://github.com/Wynncraft/Issues/issues/3747 , you have to be constantly be doing damage to the boss or it will self destruct so it's recommended that you battle this boss in a group. If this solves your issue, we'd appreciate if if you closed it. Thanks!
