### ISSUE TITLE
Baab is impossible to kill, so I can't complete reincarnation

### ISSUE THREAD

**Issue by RedMorcus** [Wynncraft/Issues#3765]
I have obtained the other 2 animal drops needed for reincarnation, but I can't get baab's wool. The problem is that baab seems to despawn within 3-5 seconds of spawning, so I can't kill him.
-This also occurs with his followers

**Comment by Dar-krusos** [comment]
This started happening just recently. All mobs have been doing this, so you'll have to wait until this get fixed.

**Comment by Troll2828** [comment]
Try switching servers. It worked for me, but you do have to switch a couple of times and it's really annoying.
