### ISSUE TITLE
Weapon is unusable; lore is messed up

### ISSUE THREAD

**Issue by Vindiictive** [Wynncraft/Issues#3766]
The weapon I use, which is a legendary spear named "Fierté", cannot be used due to the fact that the lore is "incorrect", per se. Here's what part of the lore looks like (as you can tell I can't get all of the lore in the picture): https://gyazo.com/5a59cc140c85c966b3a077f101d4d6a1 (bottom right shows that the spear's Fierté). Since the lore is in purple italics, it ends up as an "unallowed" weapon and I can't use any of the warrior's abilities on it, or do the correct amount of damage to mobs if I normally melee hit them. Is there a way to solve this in order to retrieve my spear back to a state where I can use it properly?

**Comment by Dar-krusos** [comment]
Oh, right. This is part of issue #3175.

**Comment by Trixter313** [comment]
Please follow the original issue, linked above.
