### ISSUE TITLE
Mobs Despawning Really Quickly

### ISSUE THREAD

**Issue by EnderTurtle** [Wynncraft/Issues#3770]
When I logged on around 5:30 est I went to grind for so items and noticed that the mobs were despawning within the first 10 seconds of them spawning.  There is not much more I can say about this except the fact that it is only happening on wynncraft.
![image](https://cloud.githubusercontent.com/assets/16767374/12404938/f243baac-be0d-11e5-9124-ee02b5a35a50.png)
![image](https://cloud.githubusercontent.com/assets/16767374/12404953/0e20056e-be0e-11e5-83ee-31972d0a6939.png)

**Comment by Dar-krusos** [comment]
Yeah, this has been happening quite a lot lately, and I encountered it myself during a boss fight, so I had to switch servers. All you can do now is to go on different servers until this bug is resolved completely.

**Comment by GamaRadiation282** [comment]
![f73e475892ecf8ff348703dfe9685078](https://cloud.githubusercontent.com/assets/16642284/12405451/18f74070-bdf9-11e5-9147-9c6e54e096ea.gif) This is happening too, i tried to grind but they keep despawning

**Comment by Troll2828** [comment]
Same here, I had to switch servers a couple of times. It's fine on some servers but on others they despawn too quickly.

**Comment by TheChampion879** [comment]
Salted has fixed it I think.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
