### ISSUE TITLE
Wynncraft excavation site C is messed up for ME!

### ISSUE THREAD

**Issue by DeputyMooMoo** [Wynncraft/Issues#3771]
I lost one of my purple shards, and when i tried to talk to the excavator after talking to Amadel it said i needed the purple shards from site B. I did /fixquests but it gave me 2 purple shards so i got 3. I tried to talk to the excavator after, it said i still needed the purple shards! pls help me!

**Comment by Troll2828** [comment]
you need all the shards not only the purple ones to start the quest i believe

**Comment by meatloaf4311** [comment]
If you have fixed the issue, please close the issue. If not gives us an update.
