### ISSUE TITLE
Issues with Wynncraft and Minecraft Shaders

### ISSUE THREAD

**Issue by mattthowell** [Wynncraft/Issues#3773]
I have been using the GLSL Shaders mod for Minecraft to edit my profile in order to use my new shaders pack. What I have noticed is that when I'm not using the modified profile (normal Minecraft 1.8), I have absolutely no issues, but when I'm using the modified profile (1.8-ShadersMod), the game crashes as soon as I select my class while on the Wynncraft server. Are any of you having the same issues? Your help is much appreciated. Thanks!

**Comment by mattthowell** [comment]
Update: Minecraft now doesn't crash as quickly, but the issue is still obvious.

**Comment by mattthowell** [comment]
Update: You may disregard this thread. I solved the issue for myself.

**Comment by Troll2828** [comment]
If you solved it, it would be nice to close your issue.

**Comment by mattthowell** [comment]
Will do. ^
