### ISSUE TITLE
Old Emerald Block Fix?

### ISSUE THREAD

**Issue by ItsStryder** [Wynncraft/Issues#3774]
Can someone help me with fixing my emerald blocks in my bank? Because there was a update that ruined my 24 emerald blocks so I cant use them, could someone help?
IGN - ItsStryder

**Comment by TrashcanMan** [comment]
There should be a Converter Merchant in Selchar that turns your old emeralds into new ones.

**Comment by ThunderRemix** [comment]
All types of EB should work with the Emerald Merchent. The Converter Merchant in Selchar has been removed.

**Comment by meatloaf4311** [comment]
If your issue has been resolved, please close it. If not please update us on whats going on.
