### ISSUE TITLE
Hole in the Wynn Map

### ISSUE THREAD

**Issue by ChiLynn27** [Wynncraft/Issues#3776]
https://youtu.be/R5zpgbuOcP8

Hey there, some friends and I were looking around for ??? and found a hole in the map around @x: 443 z: -5017. The hole brings you down into an area with command blocks, redstone, lava, and water. We couldn't edit anything with the blocks, but it's best you know it's there. It is under this waterfall: http://prntscr.com/9rymnt

**Comment by DarkDemonDragon** [comment]
Are you the same ChiLynn from Hypixel or you just happen to have a similar name?

**Comment by Castelaization** [comment]
there is a chunk out of the water near the island where chuckles is

**Comment by Moe-Ronickah** [comment]
Fixed.
