### ISSUE TITLE
My Breathing Helmet is Lost

### ISSUE THREAD

**Issue by MyEternalHope** [Wynncraft/Issues#3778]
I can't use the command. { /fixquests }
My Account is < joanna_cat >
Please help me.

**Comment by SmileyAlec** [comment]
You can just create a new character and lvl it up to lvl 8 and just do the
quest again its really simple.
Op 19 jan. 2016 16:28 schreef "MyEternalHope" <notifications@github.com>:

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by MyEternalHope** [comment]
The problem is solved! Thank you. :D
