### ISSUE TITLE
bug with wynnexcavatoin site b

### ISSUE THREAD

**Issue by archerdeath666** [Wynncraft/Issues#3779]
when I try to go in the hole in the near the start of the quest its said u were pushed in to the hole but u wasn't I cant even jump in it  pls help soon it will make me happy

**Comment by archerdeath666** [comment]
sorry guys my bad sorry

**Comment by Dar-krusos** [comment]
If this issue is resolved, we would like you to close this thread or tell us here if it is still occurring.
