### ISSUE TITLE
Items disappearing out of random.

### ISSUE THREAD

**Issue by Forman11** [Wynncraft/Issues#3781]
So I was putting on armor that i felt was better, and it said I needed more defense or agility to use it, so it re loads the game as usual and I look in my inventory and they are gone. They are called "Admiral's Aegis" and "Omnitread Boots" both for warrior class and they were really good armor I was wanting to keep until I reach the ability to. The boots are legendary and I was already wearing them but when I swapped them out with something else as i said it re loaded the game and the boots are gone. My IGN is Forman11 if anyone can help with the problem, thank you.

**Comment by Dar-krusos** [comment]
Sorry, but Wynncraft has a non-refund policy that disallows them from giving you items back in-case players are lying and scamming.

**Comment by Forman11** [comment]
I understand, I just hope this type of bug can somehow be fixed in the near future.

**Comment by Trixter313** [comment]
IWas your inventory full at the time?

**Comment by Forman11** [comment]
No it was not.

**Comment by TheChampion879** [comment]
This happened to me twice. Once was like you said, the other was when I identified a weapon. My inventory was full, so the identifier "threw" it on the floor. Disappeared instead
