### ISSUE TITLE
Breathing Helmet

### ISSUE THREAD

**Issue by pebblewolf** [Wynncraft/Issues#3784]
I am trying to to complete the Underice quest and lost my Water Breathing Helmet, I have tried to buy a new one off of Sayrr however it will not let me speak to him. Please help.
-IAmPebblewolf

**Comment by Dar-krusos** [comment]
Try doing [/fixquests]. If that does not work, please reply back.

**Comment by TrashcanMan** [comment]
If /fixquests fails, just get the helmet again on a different quest and transfer it over.

**Comment by pebblewolf** [comment]
It is still not working after I did

**Comment by pebblewolf** [comment]
It is still not working.

**Comment by TrashcanMan** [comment]
Get the helmet on a different class and transfer it over via your bank

**Comment by pebblewolf** [comment]
I fixed it now thanks, btw I now have another problem where I am stuck in the ground and cannot get out even if I use teleportation scrolls

**Comment by Dar-krusos** [comment]
Do /kill to get teleported to the nearest town (you will lose 2 Soul Points)
