### ISSUE TITLE
Stuck in class selection box

### ISSUE THREAD

**Issue by TimThePvpMaster** [Wynncraft/Issues#3785]
I log in, and fall through the floor, not being able to use any commands. Only way I could leave, is by crashing my minecraft. I would keep falling. I waited it out once to see if it was just lag, and I was at around -250000 Y before I gave up. I hope no one else has experienced this issue... I really want "unbanned" from this bug. I hit tab as well, you get the screen with all players heads as steve, and no names. I really wish to play again, if possible at all, and it is a major bug that should truly be fixed. If anyone reads this, I can repeat the "bug" for you. Thanks so much! I want to come back as much as possible! I only searched half of gavel!

**Comment by TimThePvpMaster** [comment]
Bump, please read this is major and could result in millions of "bannings" ( I mean that by your literally getting banned if you type this command).

**Comment by Dar-krusos** [comment]
This issue has been going on for quite some time now. See issue #3636 and try the second to last message on there (remove Wynncraft from your server list and re-add it).

**Comment by TimThePvpMaster** [comment]
Tried your idea out. Didn't work. I read the #3639 bug, and I tried server 2. If I go on there, I can constantly jump, but as soon as  I stop jumping, I get pushed into the void. I mean pushed.  I saw a piston to the right of me, not that it is of any importance.

**Comment by TimThePvpMaster** [comment]
I think, I may have solved this problem. When you log in to a world, you go to the blackbox for choosing a kit. However, you are pushed into a chest, which has NO BLOCK underneath. When you are pushed to this chest, seeing there is no block underneath you just fall. I know it might take days to reset all the boxes, but maybe you just have to place a block under that chest? I've tried everything, even server 2. I've tried jumping up and down then moving, to no avail. On Post #3639, I saw some people got out of the glitch. How, I don't know.

**Comment by DarkDemonDragon** [comment]
@TimThePvpMaster is this still an issue? If your issue has been resolved please close this as a recent update has fixed this.

**Comment by TimThePvpMaster** [comment]
Yea, sadly it is. It won't let me in. I tried re-logging, deleteing from server list, and just about everything, but to no avail. Is there a way you could teleport me "into" the game, or toggle autojoin for me? I believe an admin can do that if you have the time. Something like /autojoin toggle TimThePvpMaster.  @DarkDemonDragon

**Comment by DarkDemonDragon** [comment]
I unfortunately can't do that. I suggest go on the forums and PMing staff there.

**Comment by TimThePvpMaster** [comment]
Alright, thanks, how do I do that without being denied since I am a simple playing wishing to get a crazy bad bug fixed.

**Comment by TimThePvpMaster** [comment]
Bump, please someone help! I can't use any commands except /hub when I join the server. I go into the /autojoin box, but I always fall through the floor no matter what. Please help, I want to play again so badly!

**Comment by TimThePvpMaster** [comment]
@Trixter313 It isn't that, What happends is I typed /autojoin over 3 weeks ago, and now I spawn in the black box to change a kit, BUT I KEEP FALLING INTO THE VOID. I am legit sad... I want to play and search gavel so much more.

**Comment by TimThePvpMaster** [comment]
@Jumla Bump. This is a very bad bug that needs to be fixed asap. Thanks! I am still glitched out of the server, so I love all the help I can get. Thanks Guys and gals!

**Comment by DarkDemonDragon** [comment]
@TimThePvpMaster lol Jumla doesn't check here that often. The admin of the bug report section should be @Tama63 but he's his activity here is very inconsistent. Hopefully @Trixter313 can notify a Mod about this, but I'm not sure what his staff position here allows him to do.

**Comment by TimThePvpMaster** [comment]
@DarkDemonDragon Alright lol, was worth a try though! Yea, if I could get a Staff member on this post it would probably help fix it a ton. Thanks guys for trying!

**Comment by TimThePvpMaster** [comment]
Bump. Anyone who wants to help, really much appreciated! @Trixter313 @Tama63

**Comment by Dar-krusos** [comment]
Okay, try doing /kill ''once'' and see what happens.

**Comment by TimThePvpMaster** [comment]
@Dar-krusos I tried the following commands:

/kill
/suicide
/autojoin
/autjoin toggle
/class

All come up with: (In red text) "You can not use commands here!"

Only command I am able to use is /hub, that I know of. The Dev's probably didn't want people glitching while choosing a class. Commands won't work, so maybe an Admin could go into the game, and either teleport me, or /autojoin toggle TimThePvpMaster. No idea. From this point, I think I broke the game for myself. I've tried just about everything. Thanks again for trying to help!

**Comment by Trixter313** [comment]
I haven't commented because I can't think of any solutions, unfortunately. A server dev or admin will probably have to intervene to help here, so it's just down to how long it takes for one to see this. Hopefully, soon!

**Comment by TimThePvpMaster** [comment]
Alright, sorry if I am "rushing" this. Wynncraft is one of my main servers, and I don't want anyone else falling into the same trap. Thanks for all the work that is being done!

**Comment by Trixter313** [comment]
After rereading, I noticed this is just the regular class box issue and doesn't really have to do with the autojoin command, it's just because you typed that that you actually went to the box to experience the issue.

**Comment by DarkDemonDragon** [comment]
@Trixter313 this isn't a class box issue. In the main post he mentions falling down. In the class box (unless they changed it recently) you are just stuck in a box are remain in one constant place.

**Comment by Trixter313** [comment]
People in the past mentioned being in the class selection area and then falling through the ground while in it.

**Comment by TimThePvpMaster** [comment]
@Trixter313 That is correct, I log on, click compass, select world 2  ( Only world that allows me to move for 3 seconds ), then I go to "the box" where the class menu SHOULD show up, but instead, does not, and somehow I am shoved out of the box.

**Comment by TimThePvpMaster** [comment]
@DarkDemonDragon That is also true, except something pushes me or the game just glitches out.

**Comment by Trixter313** [comment]
Is this still occurring, even now?

So you've made sure the server resourcepack is enabled in Multiplayer > Wynncraft > Edit, correct?

**Comment by TimThePvpMaster** [comment]
Yes. I've used everything I can think of. Recourse pack > On Wynncraft ip > Correct. I can get into the nether, All my stuff, well my archer kit, is still there. @Trixter313

**Comment by TimThePvpMaster** [comment]
Holy crap... I can't believe it. I toggled the texture pack on, went to the nether, came back, went to Wynn, and I'm in. Thank the LORD! Thank you guys so much for helping, this is a MAJOR bug.

**Comment by Trixter313** [comment]
Woot! Very glad to hear! Welcome back! =D

**Comment by DarkDemonDragon** [comment]
Finally, a month long issue finally solved! :D
