### ISSUE TITLE
Archer weapon not for archer

### ISSUE THREAD

**Issue by xTheSilverWolfx** [Wynncraft/Issues#3786]
I recently got an item by the name of Flamiche. It has the skin of a spear, but does everything a bow does. It's not that good for an archer weapon though. It is a unique item, but I can't find it anywhere on the wiki. Is this a bug? Will the admins take it away? If it is a bug does someone want to buy it for a ridiculous amount of money like some people do with bugs? Help me answer my questions! :) 
![image](https://cloud.githubusercontent.com/assets/16787875/12436238/6c86eaf4-bee1-11e5-9034-4b1afdbd7ee1.png)

**Comment by Dar-krusos** [comment]
This is a bug that was put forward in issue #3502. Please close this thread and reply there.
