### ISSUE TITLE
Thieving Rodents Bug

### ISSUE THREAD

**Issue by specialcream927** [Wynncraft/Issues#3788]
I cannot return a wedding ring to the farmer in stage 2,he just say the same thing

**Comment by TrashcanMan** [comment]
Are you sure it's the right ring? I think there are two different ones in the quest and only one is right.

**Comment by DarkDemonDragon** [comment]
The ring you get from the rats only progress you through Stage I. The next step is to kill the King Rat for the real ring and then you'll complete the quest.
