### ISSUE TITLE
Lag Spikes 

### ISSUE THREAD

**Issue by TheChampion879** [Wynncraft/Issues#3790]
Every couple seconds a massive lag spike happens, freezing everything. I can still cllck, but it does nothing. This is making bosses unkillable for me, because the regen cycle still ticks during these lag spikes. Whats going on?

**Comment by Dar-krusos** [comment]
I only think this is your connection, as many others don't experience this. This could also just be at a very bad time for the server, so try waiting a while. If it's a constant problem, it's just your internet.

**Comment by mfehmer** [comment]
I have the same problem. I don't think this is my connections fault, because the same bug happens on my 1gbps connection at work.
Its's really annoying, because mobs stand still for more than a second and then you get hit like 20x at once.
This is happening since the last update of Wynncraft to me

**Comment by Dar-krusos** [comment]
Yeah, I didn't have this happen before this week, but recently is has been occurring as such.

**Comment by Trixter313** [comment]
Are people still experiencing this since the latest patch? Thanks!

**Comment by Trixter313** [comment]
I'm assuming the issue isn't occurring anymore due to no response. If it is, simply comment and I can reopen the issue. Thanks!
