### ISSUE TITLE
Lag Dropped my helmet

### ISSUE THREAD

**Issue by yairkaraso** [Wynncraft/Issues#3791]
I was in my bank in detlas and I checked my helmet in the bank and it just dropped cus LAGGGGGGGS, and till I saw that the helmet missing some1 took it and he was afk so I have nothing to do with it. Pls contact me I want it back it was lvl65 legendery helmet. DDDD:

**Comment by Trixter313** [comment]
Wynncraft has a very strict no refund policy so we can't do much in this situation. To prevent this from happening again, I suggest changing your drop key to something less likely to be accidentally pressed. Hopefully this helps!
