### ISSUE TITLE
/Forum

### ISSUE THREAD

**Issue by Dagovrek222** [Wynncraft/Issues#3792]
Hey,
I have bought VIP+ some time ago. On the wynncraft servers it is working completely fine, but the /forum command doesn't work so I can't connect my minecraft to the forums. When I type the command it doesn't give any feedback and on the forum: nothing changes.
Or am I doing something wrong when I type this: /forum Dagovrek222 ?

I hope it can be fixed.

**Comment by TrashcanMan** [comment]
Copy of #3268, please close this issue and follow the original for updates. 
/forum has been broken for quite a while, a fix should be out soon.
