### ISSUE TITLE
Guild attack not working

### ISSUE THREAD

**Issue by Flying-Froge** [Wynncraft/Issues#3794]
I tried to attack a territory and it said ok battle started. then when the count down got to 0 it didn't teleport me to the battle arena or where ever u go
so I thought ehh big deal battle server probably full. so I try later and says guild already in a battle when we are not

**Comment by Zeryther** [comment]
Me and my guild tried to attack a territory aswell, however we did not get teleported into the battle server. It did not say we are already in a battle or that the server is full

**Comment by Flying-Froge** [comment]
it never teleports me to where the battle is supposed to be held

**Comment by Trixter313** [comment]
I just tested and this should be working now. If you still are experiencing this even now, simply comment and I'll reopen the issue. Thanks!

**Comment by Zeryther** [comment]
Seems to be broken again. (At least for me, tried to attack Jungle Leak in front of Troms 2 mins ago on server 19)

**Comment by drag0nhunter1** [comment]
i started a war and got teleported but there is no mobs and ive been sat here for 20 mins

**Comment by LordHelmchen98** [comment]
Guild wars are bugged. If there are no mobs just leave the war server and try again.
