### ISSUE TITLE
I keep getting kicked for flying

### ISSUE THREAD

**Issue by TheShadowMaster** [Wynncraft/Issues#3796]
Somehow I got stuck somewhere in the air and it keeps kicking me out of the game for flying whenever I join into a server. I really want to play again please help me.

**Comment by Trixter313** [comment]
Does https://github.com/Wynncraft/Issues/issues/3785 look like the same issue you're having? Try the suggestions in that thread and see if any help.

**Comment by coen712** [comment]
same
