### ISSUE TITLE
Can't speak to Amadel WcE site D

### ISSUE THREAD

**Issue by LotKnockMC** [Wynncraft/Issues#3797]
So, simply put, whilst I was talking to Rebel Leader Amadel for the first time, the server crashed. (that issue is fixed now) However, upon trying to speak to him again all it does is show an empty black bar as though text were there.
![screen shot 2016-01-20 at 4 28 34 pm](https://cloud.githubusercontent.com/assets/16809010/12468018/053f5f0c-bf95-11e5-8797-e55745bd713d.png)
So, along with getting this fixed, I need to have the quest reset for my character: LotKnockMC as well as the crystal shards used to start it.

**Comment by Dar-krusos** [comment]
What does your quest book say, and are you online now so I can try and help?

**Comment by LotKnockMC** [comment]
It says to speak to him....

**Comment by Dar-krusos** [comment]
What's your IGN? I'll try helping you in-game.

**Comment by LotKnockMC** [comment]
IGN is LotKnockMC, as stated in the issue

**Comment by LotKnockMC** [comment]
Also I'm not on this site a whole lot, so a scheduled time would probably work best.

**Comment by LotKnockMC** [comment]
So by this point should i just pull this issue? it appears it's not gonna be fixed...

**Comment by LotKnockMC** [comment]
Still need help with this...

**Comment by LotKnockMC** [comment]
![screen shot 2016-02-06 at 4 34 26 pm](https://cloud.githubusercontent.com/assets/16809010/12870222/b436a260-ccef-11e5-8302-ef4f12fb2159.png)
Yep there we go! after doing /fixquests (for something unrelated) I got an item i thought i didn't need, but it's working now so hurrah!

**Comment by Trixter313** [comment]
Great to hear! =)
