### ISSUE TITLE
Animal Dungeon Boss Glitch

### ISSUE THREAD

**Issue by Ninja8201** [Wynncraft/Issues#3798]
Lava Cow (Animal Dungeon boss) takes a lot of knockback, and most of the time get stuck inside one of the obsidian spikes inside of the arena. I have done this dungeon three times, but never was able to beat the boss. The first time, he got stuck outside of the arena. The next two times, he got stuck inside of one of the said obsidian spikes. Please reply soon! Thanks.

**Comment by Dar-krusos** [comment]
Are you an Archer, because Arrow Storm has high knockback.

**Comment by Ninja8201** [comment]
Yas, and I didn't use arrow storm, though.

**Comment by Dar-krusos** [comment]
Is your bow slow, very slow or super slow? Each tier of speed has different strengths of knockback and the slower it is, the more knockback there eill be.

This bug of mobs getting stuck is pretty common nowadays, though. I think they'll get onto that soon, though any knockback is intentional.

**Comment by Trixter313** [comment]
This should be fixed now but if not, simply comment below and I'll reopen the issue. Thanks!
