### ISSUE TITLE
Guild Statistics Bugged Out

### ISSUE THREAD

**Issue by Dar-krusos** [Wynncraft/Issues#3799]
Hi, my name (IGN) is Dar_krusos.

The problem I am presenting is an outstanding problem that has been this way for over half a year. Our guild, Kangronomicon, has weird and wrong stats as follows:
!['Nobody' in /guild stats and /guild leaderboard](http://i.imgur.com/7LPQd11.png)

We really want this fixed soon, or in-sync with when guild wars are updated and up-and-running. Thank you for reading this, and godspeed in upgrading/repairing guild-related problems. nobody

**Comment by DarkDemonDragon** [comment]
To be exact this has only been a problem since December. This has been reported before, but was closed because of @Tama63 wiping everything.

**Comment by Dar-krusos** [comment]
Yes, I know of the wipe, so I'm just reposting. Also, the problem has been occuring much longer before December...

**Comment by DarkDemonDragon** [comment]
Are you sure? My guild was formed in late November and guild stat and leaderboard were ok til a few weeks.

**Comment by Dar-krusos** [comment]
Each guild was bugged at different times and, as we are an older guild, we would've gotten and noticed it first.

**Comment by Trixter313** [comment]
Is this still happening since the latest patch? They said they fixed some guild issues. Hopefully this is included in one of the fixed issues. Thanks!

**Comment by Dar-krusos** [comment]
Yes, it is still occurring as they have not touched this part of guilds yet.

**Comment by DarkDemonDragon** [comment]
I really wish they'd at least fix wynncraft.com/stats because there's no way to see the top ranking guilds at the moment other than asking every top guild what their Level and percentage is.

**Comment by Zeryther** [comment]
Got the same problem with my guild

**Comment by Kidgib5** [comment]
Add here as well that Guild stats are still displaying incorrectly. Experience is also not displaying correctly for /guild list. I have had my XP set to 100 but it is showing 0XP given to the guild.

**Comment by Moe-Ronickah** [comment]
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds are on hold until guild mechanics are re-written, at which time ALL current guild issues will closed.  Current guild issues are being left open for reference purposes.

**Comment by Moe-Ronickah** [comment]
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds will closed.  If you want to know if your guild issue has been reported already, please go back and do a search on "guilds".  From there, you will see all of the guild issues and you can check to see if your issue is known.
Only ONE current guild issue is being left open for reference purposes.  #3665
