### ISSUE TITLE
Drought Sand Typo

### ISSUE THREAD

**Issue by cheezcakes1** [Wynncraft/Issues#38]
When you click Irt, it says he needs 24 bottles of water. You only need to give him one.

**Comment by Trixter313** [comment]
Reopened. Still happening.

**Comment by Trixter313** [comment]
Maybe you could fix this typo @AckroWynn ? =)

**Comment by TheDollarBill** [comment]
Just gonna put this screenshot here cause it seems relevant:
http://i.imgur.com/LJcd6Ns.png

**Comment by AckroWynn** [comment]
@Trixter313 
It never alerts me when someone tags D;
(fixing it)

**Comment by AckroWynn** [comment]
In fact, I can not locate any such text. I must've already fixed it, however, the map and quests haven't been updated in a few months.

**Comment by Trixter313** [comment]
Ah, okay! Thanks!
