### ISSUE TITLE
bug with all my stuff

### ISSUE THREAD

**Issue by archerdeath666** [Wynncraft/Issues#3800]
when I went on in the moring all my stuff was gone all I had was  6 oak wood bow pls hurry I feel rtealy sad

**Comment by TrashcanMan** [comment]
Unfortunately Wynncraft has a no refunds policy, especially without convincing evidence of any sort. You'll just have to go get new items. Try asking around, usually there's somebody there with extra stuff they can give you.

**Comment by archerdeath666** [comment]
r u a admin

**Comment by archerdeath666** [comment]
cus it would help full if u can tellerport me somewere else cose I soo week here

**Comment by Dar-krusos** [comment]
This is because you died that many times :/
When you log off, make sure that you're not in an area where you're not exposed to mobs.

**Comment by archerdeath666** [comment]
oh thx
