### ISSUE TITLE
Escaping the map in the light realm

### ISSUE THREAD

**Issue by TheLMiffy1111** [Wynncraft/Issues#3801]
It seems like that the building team forgot to put barriers around the light realm, allowing escape of the map. Please fix this.

**Comment by TrashcanMan** [comment]
Could you get coordinates?

**Comment by TheLMiffy1111** [comment]
Everywhere.
All around the light realm.

**Comment by DarkDemonDragon** [comment]
The light realm of which quest are you referring to?

**Comment by TheLMiffy1111** [comment]
THE Light Realm of THE Light Realm.

**Comment by LotKnockMC** [comment]
I think miffy means the light realm where the heliorions or whatever they're called.

**Comment by ttykox59** [comment]
the literal light realm dimension place where you get teleported to

**Comment by ttykox59** [comment]
after completing the quest for light or something quest

**Comment by ttykox59** [comment]
The light realm/dimension which you get access to after completing the quest for light or something quest, mages can teleport out of the barrier and escape into the surroundings where only lvl 74+ can go.

**Comment by TheLMiffy1111** [comment]
No what I meant that they forgot to put barriers

**Comment by Moe-Ronickah** [comment]
I can confirm this issue.  There were no barriers around the Light Realm mountains two weeks ago, so anyone could escape the map, if they chose to do so..

Forewarning to anyone reading this: leaving the map, through any means, is a banable offense.

**Comment by Moe-Ronickah** [comment]
Issue was fixed.
