### ISSUE TITLE
Stuck outside the map

### ISSUE THREAD

**Issue by TenjiGaming** [Wynncraft/Issues#3803]
I've been stuck outside the map for 2 days and its really annoying. I don't wan't to start over because I'm a level 27.
![2016-01-20_22 55 34](https://cloud.githubusercontent.com/assets/16813548/12473713/9fc31094-bfc9-11e5-8939-c39a61b00d3c.png)

Coordinates: 1238 137 -2218

**Comment by Dar-krusos** [comment]
Do /class in-game and see if you can get out of that. If not, do /kill.
