### ISSUE TITLE
.... is it fallen delievery? or fallen NPC?!!!!!

### ISSUE THREAD

**Issue by whiteXD12** [Wynncraft/Issues#3804]
![screen shot 2016-01-21 at 8 09 22 pm](https://cloud.githubusercontent.com/assets/16817887/12480181/7295b178-c07b-11e5-9d16-914ea5004606.png)
..... like wow, where is the npc exactly?!!!!!!!!

**Comment by DarkDemonDragon** [comment]
I've done this quest recently so just look around he's there.

**Comment by SmileyAlec** [comment]
I cant find him too :( ive looked everywhere but i still havent found him
Op 21 jan. 2016 14:07 schreef "DarkDemonDragon" <notifications@github.com>:

**Comment by TheChampion879** [comment]
Look for a burning ship in the air, look around the base of the mountain near there.

**Comment by whiteXD12** [comment]
..... i have been travelling in a 100 block radius, afk'ed in the exact spot for 20 min, and also changed servers...

**Comment by Troll2828** [comment]
the book says x:65 and you're at x:-65....

**Comment by Trixter313** [comment]
If Troll2828's comment resolves your issue, we'd appreciate if it you closed this issue. Thanks!

**Comment by whiteXD12** [comment]
.... god, i derp way too much
