### ISSUE TITLE
internet bug or someting?

### ISSUE THREAD

**Issue by coen712** [Wynncraft/Issues#3807]
the last two days i got kicked 4 times for flying :-1: i think this may look like hacking
this bug happends when i die and when i have lagg im scared that i will be banned for this cause i got banned a few years ago. i think that the mods will ban me faster becouse of that, plz tell me if other pepole this problem have too tell me if it is smart to be not online for a while

**Comment by Dar-krusos** [comment]
Nah, don't worry. You won't be banned for that, as it is a recurring problem for a lot of people.

**Comment by Wozab** [comment]
It's just the connection between you and the server, they won't ban you as long as you don't use any hacks.

**Comment by Trixter313** [comment]
Are you still experiencing this since the latest patch? Thanks!

**Comment by coen712** [comment]
Nope
Op 30 jan. 2016 16:45 schreef "Nick Cipriani" <notifications@github.com>:

**Comment by Trixter313** [comment]
Great to hear!
