### ISSUE TITLE
Bosses shooting through blocks

### ISSUE THREAD

**Issue by TheChampion879** [Wynncraft/Issues#3812]
Recently, some of the bosses that have ranged attacks have been hitting me through blocks and walls, despite not doing this before. Anyone else having this problem?

**Comment by DarkDemonDragon** [comment]
Has this actually been confirmed?

**Comment by Moe-Ronickah** [comment]
50 days and no confirmation or other reports, so I'm closing this as presumably fixed.  If it happens again, please refer to it as a new issue.
