### ISSUE TITLE
Wynn excavation side B

### ISSUE THREAD

**Issue by whocaresaboutUsernames** [Wynncraft/Issues#3813]
the riddle with the block value doesnt work, Buttons might be broken

**Comment by whocaresaboutUsernames** [comment]
im sorry, i didnt saw that the White block was Quarz and not snow, is it possible to deleate this?

**Comment by Dar-krusos** [comment]
Uh, what's your IGN. I could come in and help you.

**Comment by DarkDemonDragon** [comment]
If your issue is resolved please close this with the button at the bottom.
