### ISSUE TITLE
Stuck in the ground

### ISSUE THREAD

**Issue by Soumeh** [Wynncraft/Issues#3814]
While i was playing one of the chunks near the Skeleton Dungeon wasn't loaded,and i jumped in.
Now i'm stuck there and i can't teleport out!

**Comment by Dar-krusos** [comment]
As @Wozab said, do /kill to suicide and spawn in the nearest town (this causes you to lose two Soul Points, just as you would when getting killed by a mob). Remember to never let your Soul Points go down below one, or you will drop/lose all your items.
