### ISSUE TITLE
Armor Bug

### ISSUE THREAD

**Issue by TLFGshoddy** [Wynncraft/Issues#3815]
Ok i had a lvl 54 warrior before the gavel patch and then i was going to lvl another one to get the hang of it again because im just coming back.So i noticed that my legs and chest plate was not showing up for some reason.I thought that that armor was just glitched but now im lvl 21 and no armor i have worn will show my legs or chest plate.PLEASE HELP...

**Comment by Dar-krusos** [comment]
It seems you have lost them, and the staff cannot/is not allowed to give you items due to their non-refund policy.

**Comment by Trixter313** [comment]
When your inventory is full and armor is forced of it is currently deleted but we are working on fixing that. The already disappeared armor is lost but hopefully it doesn't happen again.
