### ISSUE TITLE
Silverfish Dungeon

### ISSUE THREAD

**Issue by iner22** [Wynncraft/Issues#3817]
I was trying to solo the Silverfish dungeon, but fell into what I guess is a pit trap, just after feeding emeralds to the snake statues.  The pit is 1 block in area and 2 blocks tall, which is just enough that you can't easily jump out, and impossible if you play an assassin.  I was a warrior, but before I could decide to use Charge to get out, the block above me, which was part of the floor, closed.  I had to ask a moderator how to get out of that situation.

**Comment by DarkDemonDragon** [comment]
Actually Assassin can get out with Vanish once you unlock jump boost. You would have to provide coords with a picture of the area for staff to do anything.

**Comment by Trixter313** [comment]
I just thoroughly searched the dungeon and can't find what you're talking about. It might have just been a one time glitch where some blocks were missing. If you can post proof that it's still there, I'll reopen the issue. Thanks!
