### ISSUE TITLE
1.09 quest book bug

### ISSUE THREAD

**Issue by opps123456789** [Wynncraft/Issues#3818]
Well, back in 1.09, right before quests came out, the quest book was buggy and was some how able to be moved out of the quest book slot. Then, another quest book would spawn in your quest book slot and the one that you took out could be moved around and just put anywhere. I put 4 into my enderchest and thought I could sell them for some le in the future but now they are stuck in my enderchest, I was hoping for an admin to remove them.

**Comment by Dar-krusos** [comment]
To remove these items, read these instructions along with this image:
!(http://i.imgur.com/f859G9o.png)

Images:
1. Fill all inventory space (make sure you have a stack of 2 or more emeralds somewhere in there)
2. Halve a stack of emeralds
3. Place it upon the item you want removed
4. Throw out the unwanted item

Only use this for this situation and don't do this to any Quest Items (or there will be consequences).

**Comment by opps123456789** [comment]
The item is in my enderchest, it isn't like a quest item, it's like the quest book is in my inventory, it is unable to be moved and will go back to the place it was when I try to move it.

**Comment by Trixter313** [comment]
I merged your issue into a similar one, about others having items stuck in their bank. Here is the issue so you can stay updated on the status of it https://github.com/Wynncraft/Issues/issues/3147
