### ISSUE TITLE
I'm not sure if this is a bug or not, I have access to server but not the homepage

### ISSUE THREAD

**Issue by iseldesire** [Wynncraft/Issues#3820]
I actually joined the Crafted Movie server just barely when the video about Wynncraft came out so I can say it's approximately 2 years ago since I have properly logged in onto the page on the internet.

I got permission for the whitelist back then and have a very small history on playing on the server. All I remember is I cleaned out a portion of jungle trees right exit out into the building area from the spawn. After that I remember the server renewed itself and starting in an underground place, I had serious lag issues back then so I couldn't really log in.

I forgot the game about a year, I had it installed but never really played it save for a tiny bit of singleplayer.

After a year after present day, I wanted to bring along a friend to play with me on the server and pressed the link on my bookmark which the icon was still the face of Salted. Apparently the link has changed and all taking me to Wynncraft.

I am quite positive that I remember the e-mail which I used to use and tried searching for my password alas no success on any attempt on any of my e-mails. I checked if I still had access to the server in case I got erased from the list for long time being away, and I saw that I still had access since it took me to some place like a initial starting area.

I would like to ask if anything happened to my forums ID and ask if there is a sequence I have to take to get the ID back, or have to re-register for the site again then connect my minecraft ID again

**Comment by Dar-krusos** [comment]
I reckon that you'll still have your forums account, so just try logging in on that. Connecting your minecraft account to the forums also doesn't work at the moment, but it should still be connected to your old forums account. In any case, just log in and see what happens.

**Comment by iseldesire** [comment]
@Dar-krusos Eh, I actually made a typo on that part so you might have not understood, however I did state above that none of my e-mails work on the site, if it did I wouldn't have posted here in the first place

**Comment by Dar-krusos** [comment]
Oh alright. Just try making a new forums account. I'm sure you will still be able to connect your forums to your Wynncraft player.
