### ISSUE TITLE
Dropping items even with 3+ soul points

### ISSUE THREAD

**Issue by HeyloLP** [Wynncraft/Issues#3821]
It's right now possible that when you die with for exaple 10 soul points that you lose ANYTHING so whatch out
(PS: i konw about the N.R.P.)

**Comment by Trixter313** [comment]
If you experience this again since the latest patch, please just comment and I'll reopen the issue but it shouldn't happen now.

**Comment by 0x0000null** [comment]
Is this still applicable for the new soul point system?

**Comment by HeyloLP** [comment]
No this isn't a bug anymore since it is a new feture that it is possible.
