### ISSUE TITLE
weapon bug

### ISSUE THREAD

**Issue by Tom66597** [Wynncraft/Issues#3822]
hello there owner of the server. sins the new update my weapon stop working and it was a power full one. if you could fix it I would be very happy this server is my favorite one. my username is Tom66597 thank you

**Comment by Trixter313** [comment]
Could you post a screenshot of the stats of the weapon and possibly give more description? What is the name of the weapon, how has it 'stopped working', etc. Thanks!

**Comment by Tom66597** [comment]
the weapon name is: Dévoreuse
Dam: 33-40
Lv. min: 45
its a unique Item

![2016-01-24_10 44 55](https://cloud.githubusercontent.com/assets/16852021/12534358/255fb6a6-c288-11e5-9d6e-0607ab814fbf.png)

**Comment by Tom66597** [comment]
the weapon just stop working at all, wen I hit some it does not do damage and the spell don't work at all. It became a useless stick

**Comment by Trixter313** [comment]
Ah, I believe you are having the same issue as https://github.com/Wynncraft/Issues/issues/3161 where the item hasn't been updated to the new system. Read that original thread and try any suggestions in it to see if it helps. Also, please direct any future comments to the original thread. Thanks!
