### ISSUE TITLE
Random Map

### ISSUE THREAD

**Issue by jojoIv** [Wynncraft/Issues#3826]
Whilst going to the island where Santa is on for the Craftmas Chaos quest, i picked up a random map. Its appears to be a map of the island that Santa is on. Am I supposed to have this? Can someone please tell me what do to with it. I thinks its a bug.
![2016-01-23_15 05 37](https://cloud.githubusercontent.com/assets/16521494/12533107/3915918e-c1e3-11e5-9e17-b875cbdb9ffd.png)

**Comment by Trixter313** [comment]
I'm not sure what it is but maybe someone else will know. I'd say just throw it in the trash can in Detlas to be safe, I don't see any use for it and I believe that some people have been banned for having items like this so just be careful.

**Comment by DarkDemonDragon** [comment]
jojolv you should probably post this on the forums and tag a mod and maybe an admin about the legitimacy of the item. If a GM okays the item then feel free to do what you want with it. If they say it should not be allowed and to get rid of it, toss it either into lava, fire, or a trash disposal at a bank.
