### ISSUE TITLE
Not Joinable

### ISSUE THREAD

**Issue by CloudZeroxAndBearsAreEz** [Wynncraft/Issues#3830]
Says There Is No Server To Conect To Please Report
What do I do Ign: CloudZeroX

**Comment by Trixter313** [comment]
This seems to be an isolated issue as I was just able to connect fine. I suggest restarting your computer and router to see if that resolves the issue. Report back what happens!

**Comment by sonicrush** [comment]
nothing happens. ive tried many times. i could tell everyone (almost is having this prob bc there are only 64 ppl online
