### ISSUE TITLE
armor still being old style

### ISSUE THREAD

**Issue by epicnezz135** [Wynncraft/Issues#3832]
i havent played wynncraft in over 2 years (before Gavel and when pets could still attack and there was a VIP town) im trying to get back into the game, but the armor i have still uses the out of date format when armor was defense not a health boost, im unable to equip it and cant get it re-identified for it to work

![2016-01-23_19 05 36](https://cloud.githubusercontent.com/assets/16859591/12534246/68f16b00-c204-11e5-98c5-d8bfa70ace31.png)

**Comment by Slaten6** [comment]
Some items haven't been converted to the new item system like this one just give it some time

**Comment by epicnezz135** [comment]
how long ago was the new system implemented?

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3161

Please direct any future comments to the original thread. Thanks!
