### ISSUE TITLE
Bear helmet

### ISSUE THREAD

**Issue by Robinjo7** [Wynncraft/Issues#3837]
The helmet you can buy on the The Bear Zoo Island is not updated.

**Comment by Trixter313** [comment]
Could you post a screenshot of what the item shows when you mouse over it in your inventory?

**Comment by Robinjo7** [comment]
![screenshot 12](https://cloud.githubusercontent.com/assets/16863545/12538118/5023a610-c2d1-11e5-911b-d20ce4ee1737.png)

**Comment by DarkDemonDragon** [comment]
Duplicate of #3314 Please close this.
