### ISSUE TITLE
Lost quest item used for Temple of the Legends

### ISSUE THREAD

**Issue by SageSlay** [Wynncraft/Issues#3838]
I was going to Thomas to finish the Creeper Infiltration quest when I realized I had the creeper mask on so I switched it with my other helm which was the pierced helmet, consequently the skin changed midway of placing the creeper mask back into the inventory and it disappeared from my cursor and my inventory, I could not locate it on the ground so I resumed to finishing the quest. 
![image](https://cloud.githubusercontent.com/assets/16737462/12536330/e749261c-c26f-11e5-9399-f662f0043e66.png)

![image](https://cloud.githubusercontent.com/assets/16737462/12536333/ef81e0ee-c26f-11e5-9328-a0a3718f45e9.png)

**Comment by Trixter313** [comment]
Try typing /fixquests and see if that returns the helmet. If not, you can simply redo the quest on another class.

**Comment by SageSlay** [comment]
I've never heard of the /fixquests command but you have a good point of doing it on another account.

**Comment by Trixter313** [comment]
No problem, glad I could help!
