### ISSUE TITLE
I lost two of my diamond legging

### ISSUE THREAD

**Issue by KrazyPain** [Wynncraft/Issues#3840]
So i joined the server (5 month since i didn't join), It said unidentified for my armor and weapon, I went to the closest identifier near Ragni (cauz i spawned there) and I shift clicking all my armor to unequip them and i lost my Leggings called "crystal" before i could identifie it, but i kept my helmet (Blue mask)
my chesplate (adamantite) and my boots (stalagmites) but i lost my legs.
The other time, i looked into my bank to see if I had any replaced leggings, and I found these Dalaam
I Identifie them, and then I suddenly loose them while I was travelling to -5000
Please can you give me back my stuff or some money cause Crystal are very expensive (in the old times)

**Comment by KrazyPain** [comment]
P.S it happened the same day as I posted the comment

**Comment by sonicrush** [comment]
dont shift click!

**Comment by KrazyPain** [comment]
well last time I played there wasn't this time of glitch

**Comment by Trixter313** [comment]
Unfortunately, due to Wynncraft's strict no refunds policy, we can't do anything about this. To avoid the first scenario from happening again, try not to shift click armor. I don't know what you mean in the second scenario. If you ask around someone might give you some decent replacements.
