### ISSUE TITLE
Email Confirmation Notification Error

### ISSUE THREAD

**Issue by fredesuper** [Wynncraft/Issues#3842]
Alright, so I just got my new account name set in stone, I made a new Wynncraft account for the forums. I got the confirmation email the second time I tried the resend button, I opened up the email and clicked on the link. This is what happened.

http://prntscr.com/9u7g0d

Please do fix this A.S.A.P.
//Delta

**Comment by Trixter313** [comment]
If you try now, does the issue still occur? Thanks!

**Comment by Trixter313** [comment]
I'm going to assume the issue isn't still occurring due to no response. If it is, simply comment and I can reopen the issue. Thanks!
