### ISSUE TITLE
Could Not Find a Server to Connect to

### ISSUE THREAD

**Issue by Mininglover21** [Wynncraft/Issues#3843]
It says it couldn't find a server to connect to and to report it. Is the server restarting or something?

**Comment by pebblewolf** [comment]
I am having the same problem

**Comment by sonicrush** [comment]
Same. Please help!

**Comment by samwj02** [comment]
Happening to me as well :s

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3830

Please direct any future comments to the original thread. Thanks!
