### ISSUE TITLE
Broken Pipe: Get the Plumber!!!

### ISSUE THREAD

**Issue by axmoorman00** [Wynncraft/Issues#3850]
So, I wanted to get on Wynncraft because I wanted to, so I selected a random server.
But it came up with this:
java.io.IO ConnectException:Connection refused: Broken pipe

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes issues like this resolve themselves with a little bit of time. If it's still happening, try restarting your computer and router. Hopefully this helps! If it does, please close this issue. Thanks!
