### ISSUE TITLE
Wynn Excavation site D 

### ISSUE THREAD

**Issue by jeffrypig23** [Wynncraft/Issues#3851]
During the fight with Shadow Amadel, the boss can (and probably will) run away, then charge/teleport, and get stuck in a wall, and will not be able to get out, making the boss fight impossible.

**Comment by Trixter313** [comment]
How many times has this happened to you? If you switch to another world the boss should reset. See if it happens again. It might just be a rare issue.

**Comment by Dar-krusos** [comment]
Do /class whenever mobs you need to kill get stuck in a wall as this will despawn all entities. This is a common issue (especially when you use a spell that pushes mobs), and the only thing you can do is to just keep trying to kill the boss without it getting stuck in a wall. The devs will need to fix this, though.

**Comment by jeffrypig23** [comment]
It has occured more than once. It has happened 3 times. When I tried
re-logging, I died immediately.

On Mon, Jan 25, 2016 at 12:43 AM, Vince Vo <notifications@github.com> wrote:

> Do /class whenever mobs you need to kill get stuck in a wall as this will
> despawn all entities. This is a common issue (especially when you use a
> spell that pushes mobs), and the only thing you can do is to just keep
> trying to kill the boss without it getting stuck in a wall. The devs will
> need to fix this, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/3851#issuecomment-174438623>.
>



-- 
Sent from my iPotato

**Comment by DarkDemonDragon** [comment]
@Dar-krusos that's what you do with minor mobs not bosses...

@jeffrypig23 try to not corner Amadel too much. Pushing him into a corner with a high KB attack like Arrow Storm will push him into blocks which will then cause him to teleport further into blocks.

**Comment by Dar-krusos** [comment]
@DarkDemonDragon I don't see what you mean, as doing /class will despawn the boss.

**Comment by DarkDemonDragon** [comment]
@Dar-krusos and leave you venerable for ~5 seconds because of teleportation lag and spawning in gives you 0 mana. For unexperienced players this is a death sentence.

**Comment by Dar-krusos** [comment]
@DarkDemonDragon Corners are useful.

**Comment by Trixter313** [comment]
Is this still occurring? Thanks!

**Comment by Moe-Ronickah** [comment]
Excessive knockback was fixed a while ago.  With no new reports, I'm calling this one fixed.  If it starts up again, please open a new issue.
