### ISSUE TITLE
Button in "The Worm Holes" Isn't Working

### ISSUE THREAD

**Issue by Valinity** [Wynncraft/Issues#3852]
Me and my friend were doing the quest "The Worm Holes" and when we got to the end of the cave, we pressed the button on the golden block, ran back a little bit and went through a door. I got the "Slimy Skin" first and we had to wait until the skin respawned for my friend. Once she got it we went back to the door and saw it was closed. We looked and saw a button near the door thinking that it would open it. We pressed it once and waited a few seconds. Nothing happened. We tried over and over again. We also looked around if to see if the walls would open and nothing happened still. I decided to use /kill and came back, used the button on the gold block and got my friend out. I tried the button near the door once again and it didn't work.

**Comment by Trixter313** [comment]
Try switching to a different world, sometimes it's limited to just one and is fixed after a server restart.
