### ISSUE TITLE
Guild attacks not working

### ISSUE THREAD

**Issue by TeleportingNinja** [Wynncraft/Issues#3854]
Hello. For several days, I've been trying to attack places in which enemy guilds own, however, after starting an attack, it does not teleport me to the guild world in which I should be able to kill the mobs protecting the place, and take over. Is this a bug or is it disabled?

**Comment by Dar-krusos** [comment]
Yeah, this has been going on since Gavel; they are just disabled, as the devs are updating/fixing guilds at a later date (being it not a priority).
