### ISSUE TITLE
Item lost?

### ISSUE THREAD

**Issue by Costa24Craft** [Wynncraft/Issues#3857]
I was playing in a new character, and i found a legendary leather armor (pants)
Then the server kicked me and putted me in another server.
I lost my legendary pants and the emeralds i used to identifie it.

I have a screenshot but i don't know how to post it.

Please do something! I lost alot of emeralds and the armor.

**Comment by Costa24Craft** [comment]
![Uploading 2016-01-25_08.47.44.png…]()

Here it is.

**Comment by Costa24Craft** [comment]
![2016-01-25_08 47 44](https://cloud.githubusercontent.com/assets/16882678/12556279/c03ad26a-c34a-11e5-8abd-f84939e7b953.png)

**Comment by Odnod** [comment]
It's a shame that you lost your armor, but wynncraft has a no refund policy and you will have to buy a new pair or use different one. Sorry that this happened to you.
