### ISSUE TITLE
Item + dont really work

### ISSUE THREAD

**Issue by yairkaraso** [Wynncraft/Issues#3858]
![2016-01-25_19 09 09](https://cloud.githubusercontent.com/assets/16417060/12558272/68f38504-c397-11e5-85bb-d2000465e334.png)

look at the loot bonus and exp bonus ^^^^^^^

![2016-01-25_19 09 19](https://cloud.githubusercontent.com/assets/16417060/12558276/6ca90b24-c397-11e5-9aaf-06e60880c87e.png)

look at the loot bonus and exp bonus ^^^^^^^

The exp and the loot bonus not working

**Comment by Odnod** [comment]
Set bonuses are currently broken, just wait until they patch it.

**Comment by Trixter313** [comment]
A recent patch fixed some set bonus related things. Is this still occurring?

**Comment by yairkaraso** [comment]
No ty the patch fix it :D

**Comment by Trixter313** [comment]
Good to hear! =)
