### ISSUE TITLE
The Maiden Tower (Can't give Black Veil to Erlard)

### ISSUE THREAD

**Issue by pebblewolf** [Wynncraft/Issues#3859]
It will not let me give the Black Veil to Erlard please help me.

**Comment by Odnod** [comment]
Try going backward in the quest. You may have used teleport/charge/escape over a trigger for the quest. Retrace your steps and make sure you don't go over any potentially key points.

**Comment by Dar-krusos** [comment]
You are not supposed to give the Black Veil to Erlard. Wear the Black Veil and kill the Maiden inside the tower.

**Comment by DarkDemonDragon** [comment]
@pebblewolf whenever you get a helm during a quest you're supposed to wear it. This is true for every quest helm except for the unpurified helm in ToL.
