### ISSUE TITLE
Cant attack territory?

### ISSUE THREAD

**Issue by CorruptNitro** [Wynncraft/Issues#3863]
Whenever I attack a territory it counts down and then nothing happens. The mobs defending the area dont appear and nothing really happens. Wondering if this is a bug or glitch?

**Comment by Odnod** [comment]
I am fairly certain guild territories are broken right now. If not, try going on server 2 or 3 and doing it.

**Comment by Trixter313** [comment]
There was a patch that supposedly fixed this issue. If you still experience it now, please comment below and I'll reopen the issue. Thanks!
