### ISSUE TITLE
Died in Selchar, spawned in Olux..

### ISSUE THREAD

**Issue by ITheWolfyzI** [Wynncraft/Issues#3866]
Hello, I was doing the craftmas chaos quest, but when i died, i spawned in Olux. And now i cant get away from there bcus the mobs are too strong for me. 

~ Wolfyz

**Comment by DarkDemonDragon** [comment]
At what part did you die? In Past or Future Selchar? Also, if you wish to return to Wynn use a 2nd character to buy a wynn scroll, place the scroll in the bank, and the pick up the scroll on your main character and use it.

**Comment by meatloaf4311** [comment]
Have you resloved your issue, if so give close the issue. If not give us an update

**Comment by Trixter313** [comment]
Merged into https://github.com/Wynncraft/Issues/issues/3617

Thanks for the addition!

**Comment by ITheWolfyzI** [comment]
I was in past i think
