### ISSUE TITLE
Server join bug

### ISSUE THREAD

**Issue by KeepoPrideHD** [Wynncraft/Issues#3872]
Ecxeption Connection:RuntimeException : Server is online mode! @net.md_5.bungee.ServerConnector:261

often refuses to join the server because of that. No idea what to do.

**Comment by TopazMarauder** [comment]
Same here

**Comment by ColtoTheHobbit** [comment]
this is also happening to me

**Comment by Renaldo-Moon** [comment]
Same, just found this server and would hate to have to stop playing on it.

**Comment by bannana345543** [comment]
I kept spamming it and got in after about 30-50 times. Just relog and hope for the best. Same issue here. The servers online are laggy anyhow. Might wanna might a couple of hours xD. Last I was on there was nearly all worlds full too.

**Comment by Trixter313** [comment]
Are you still having this issue? I just successfully logged in.

**Comment by KeepoPrideHD** [comment]
I have this issus from time to time, actually it takes me over 5 minutes to log in, and if I lag out I need to try again and again. I can waste even half an hour everyday then, which is not really nice as for just a little issue.

**Comment by Trixter313** [comment]
What about now? There was a patch recently that might have fixed the issue.

**Comment by KeepoPrideHD** [comment]
That's right. It's okay now.

2016-01-31 18:05 GMT+01:00 Nick Cipriani <notifications@github.com>:

**Comment by Trixter313** [comment]
Great to hear! =)
