### ISSUE TITLE
Death by lava and teleporting

### ISSUE THREAD

**Issue by bannana345543** [Wynncraft/Issues#3873]
So as normal I jump into the lava after finishing the quest with all the lord of the ring stuff and I didn't want to climb out of Mt. Wynn, but this time was different, actual very strange... So when you die you teleport to the nearest town and that was the case... then I teleported me right back into lava killing me once more. I wasn't so mad until it repeated for a third time making me lose my last soul points making me lose all my items. So either that volcano really hates me or teleporting within that area was/is messed up. I really don't care for the items it was on my lvl18, just the fact that it did that to me. I talked to some staff named snowing , but s/he was busy. Could you guys check out that issue. Mt.Wynn and Matlic have some real issues. I don't know what was up with it, but I really don't want to have this happen and get stuck on a loop.

**Comment by meatloaf4311** [comment]
Umm, you were stupid enough to kill yourself too many times and it is not how i ended the quest, I just climbed back out.

**Comment by Trixter313** [comment]
Unfortunately due to wynncraft's strict refund policy we can't give you the items back but in the future, instead of doing something risky like this, simply type /kill with 3+ soul points and it will respawn you to the nearest visited town.
