### ISSUE TITLE
Thieving Rodents Quest Bug

### ISSUE THREAD

**Issue by scottystake** [Wynncraft/Issues#3874]
When ever I try to finish the quest Thieving Rodents, It won't let me finish it even though I have the wedding ring in my inventory. Screenshot bellow.

![screenshot 5](https://cloud.githubusercontent.com/assets/16906280/12594378/b00c4f5a-c42a-11e5-9caf-c79a44e0edec.png)

**Comment by bannana345543** [comment]
Go into the cave within the farm. That isn't the correct ring. That is just what you have to show him before he allows you in the cave. There is a lvl5 silverfish that drops the golden nugget "wedding ring"

**Comment by scottystake** [comment]
Thanks

**Comment by Troll2828** [comment]
If your issue is resolved, you should close this issue.
