### ISSUE TITLE
Test Boots 80

### ISSUE THREAD

**Issue by Smurfman254** [Wynncraft/Issues#3877]
I just received an item called test boots 80 from a loot chest. I was told that it was an illegal bug item that was removed early after gavels release. If that person was telling the truth that means the bug is back.

**Comment by TrashcanMan** [comment]
Can you get a screenshot of the boots?
If they do turn out to be a test item you'll have to destroy them somehow.

**Comment by Smurfman254** [comment]
![test boots 80](https://cloud.githubusercontent.com/assets/16483431/12603267/c67630c0-c476-11e5-9bc6-2385837cbf44.png)
They are leather boots

**Comment by Smurfman254** [comment]
![2016-01-26_22 15 47](https://cloud.githubusercontent.com/assets/16483431/12603742/e016737e-c47a-11e5-9246-a813a2d8b80f.png)
Confirmed that they are unintentional

**Comment by TrashcanMan** [comment]
If your issue is resolved, please hit the "Close Issue" button. Thanks!

**Comment by Smurfman254** [comment]
Bug still remains in the game, that last post was just confirming that it was a bug

**Comment by Smurfman254** [comment]
Just got test chestplate 80, looks similar to the boots

**Comment by DarkDemonDragon** [comment]
Bug claims to have been fixed by the recent patch. If you don't find another test item within a couple days please close this.
