### ISSUE TITLE
Not Able To Use the Teleport Spell in Llevigar

### ISSUE THREAD

**Issue by SaturnFire** [Wynncraft/Issues#3878]
Title is self-explanatory, but I'll explain it anyways: 
Every time I tried to use the teleport spell in Llevigar. I got a red text, saying: 
"You are not permitted to enter this area." 
Here's a [video.](https://youtu.be/4gvoo7_QudE)
I was also not able to use a teleport scroll to Llevigar either. I'm not entirely sure if this is happening to anyone else, or if it's happening any where else, however I thought it would be best to report this glitch here.

**Comment by kraft2004** [comment]
Thats happening to me too. If you wanna see wtf happened to me, i used 4 scrolls at the same time (bug) and got all the perm errors. Btw, http:// pastebin .com/cjXRPF9b.

**Comment by DarkDemonDragon** [comment]
The recent patch claims to have fixed this. Please check if this issue still persists. If your issue has been resolved please close this.
