### ISSUE TITLE
can't teleport out of Lievigar 

### ISSUE THREAD

**Issue by rathat2000** [Wynncraft/Issues#3879]
Im stuck in a room with no teleport out and cant use scrolls each time I kill my self it comes up in chat saying I died but I just get all my hearts back

quest: heart of Lievigar 

try to find a way into the machine

**Comment by Nagisa-Blue** [comment]
If you are a assassin,then there is no way to help you . . .

**Comment by Nagisa-Blue** [comment]
Try to use moves to leave the rooms,some parkour may help you also.

**Comment by Trixter313** [comment]
Try the command /die instead of /kill, it might work better.

**Comment by Trixter313** [comment]
This should be fixed now in the latest patch.
