### ISSUE TITLE
Really, Wynn? Bugavel expansion ;-;

### ISSUE THREAD

**Issue by kraft2004** [Wynncraft/Issues#3881]
1 - I used 4 Scrolls, trying to go back to Llevigar. None of them worked, "You dont have permission for that area"... Also, they were used at the same time.
2 - I died 3 times and respawned at the same location the 3 times. But even spawning in a place full of zombies, getting attack, my HP were the same. But i was dying.
I know you arent gonna give me my Soul Points back, but please try to do something. Im not the only one with Gavel problems.

**Comment by kraft2004** [comment]
Nice. I SPAWNED IN VOID. WYNNCRAFT, PLEASE DO SOMETHING WITH GAVEL!

**Comment by kraft2004** [comment]
Died in void at cords 1, something, 1, and then i respawned at Nesaak...

**Comment by VOVOT** [comment]
Yes, Havel is not working, I used TP scroll and it eat one my soul point, but nothing happened. Only message You are not permitted to enter this area. I traveled to gavel with boat and if i try to use teleport spell (I am mage) it will write the same error message. When I relog it will spawn me in a dark box and I must type /kill.

**Comment by Odnod** [comment]
Llevigar (is? Was?) broken. Just look at the forums and other posts on this bug fixes thread. There were some network errors yesterday and they are getting cleared up.

**Comment by Trixter313** [comment]
So the bugs are tp scrolls not working and your HP isn't going down?

**Comment by kraft2004** [comment]
Its now working (Im on Wynn), but yeah, my HP wasnt going down, even being attacked by 5 zombies at the same time.

**Comment by kraft2004** [comment]
Sorry for the retarded report, its better now.

**Comment by Trixter313** [comment]
Great to hear!
