### ISSUE TITLE
armour skins

### ISSUE THREAD

**Issue by wynncraftlupascu** [Wynncraft/Issues#3882]
it dose not show the armour skins

**Comment by DarkDemonDragon** [comment]
Please provide information or this issue will be closed by staff.

**Comment by wynncraftlupascu** [comment]
help me

**Comment by DarkDemonDragon** [comment]
.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3739

Please direct any future comments to the original thread. Thanks!
