### ISSUE TITLE
Heart of Llevigar quest bug

### ISSUE THREAD

**Issue by FireGath** [Wynncraft/Issues#3884]
I can't enter the teleporters to the next room, i tried them all, they all have same results
"You are not permitted to enter this area
![2016-01-27_21 08 53](https://cloud.githubusercontent.com/assets/16920095/12615807/72288828-c53a-11e5-8b58-94130b497967.png)

**Comment by KeepoPrideHD** [comment]
There's something other to complete before you get into this portal, but if you completed it all already I have no idea what to tell you.

**Comment by Trixter313** [comment]
This issue should have been fixed in the latest patch. Comment below if you still experience it and I will reopen. Thanks!
