### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Moderocky** [Wynncraft/Issues#3886]
Hi this happens like twice a week and lasts for like a day each time.

I just get a timeout.

**Comment by Odnod** [comment]
Try switching ip to play.wynncraft.net or play.wynncraft.org

**Comment by Moderocky** [comment]
Can't get on any.

**Comment by mfehmer** [comment]
Same for me. Found out it might be a problem with forge. Because if I start the newest Minecraft version without any mods I can connect. But with 1.8.8 + Forge I get "Connection Lost: Internal Exception: io.netty.handler.timeoutReadTimeoutException"

**Comment by Moderocky** [comment]
But how can I record without my special youtube mod?? D:

Hmm and what is more worrying is how many shady tricks, sticks and hacks the Wynncraft developers have done to bungeecord to break it.

**Comment by Trixter313** [comment]
I just successfully logged in with Forge so this should be fixed now.
