### ISSUE TITLE
Skin and Armour trouble

### ISSUE THREAD

**Issue by DanDYolo** [Wynncraft/Issues#3889]
Every time when i now log in my skin becomes Alex and i get invisible for all players.When i do /Armour my skin  gets back,but not my armor skin and i still become invisible for all players.Please if you can help me get rid of this bug.
![2016-01-27_19 31 41](https://cloud.githubusercontent.com/assets/16438486/12624206/cd614936-c568-11e5-8d38-6e5a8d4057c1.png)
![2016-01-27_19 31 27](https://cloud.githubusercontent.com/assets/16438486/12624209/d22ae404-c568-11e5-8323-66411514f8b4.png)

**Comment by wynncraftlupascu** [comment]
i kow right?

**Comment by DanDYolo** [comment]
ye

**Comment by Trixter313** [comment]
Are you still experiencing this now? There was a recent patch and it might have fixed the issue. Report back any updates or comments!

**Comment by Moe-Ronickah** [comment]
Trixter, I had the same problem, but it's been fixed for me.
