### ISSUE TITLE
Lost all my items, was offline the entire time....

### ISSUE THREAD

**Issue by PhilipJohnsen** [Wynncraft/Issues#3892]

**Comment by PhilipJohnsen** [comment]
I was possibly hacked, but i was offline the entire time, i had my computer open and thats IT, please help with this issue, if i cant get my items back i will just be stuck forever

**Comment by PhilipJohnsen** [comment]
It is confirmed i have been hacked, all possible items that were sell able was selled and / or traded to another person. Restore inventory file or something, please let me know if this is possible...

**Comment by Odnod** [comment]
There is a no refund policy in wynncraft, I don't think that there is much anyone can do.

**Comment by Odnod** [comment]
What level are you?

**Comment by PhilipJohnsen** [comment]
Level 75 arhcer, why?

**Comment by Odnod** [comment]
Hmm... I recommend you just start over on another class. I started a Knight 2 weeks ago and it is already level 75 with around 20 le to call its own.

**Comment by Trixter313** [comment]
Like mentioned above, Wynncraft has a strict no refunds policy so there's nothing we can do here. I suggest changing your Minecraft password and possibly email password also to prevent this from happening again. Good luck!
