### ISSUE TITLE
Don't have permission

### ISSUE THREAD

**Issue by us5013** [Wynncraft/Issues#3893]
So i was doing The Hunger of Gerts Part 2 quest, and i went into the person's basement, to try and find the battery farm. I am sure that to find the farm, i need to press a button that will open an entrance, but when i press the button it says i don't have permission, so I can't continue the quest...

**Comment by Trixter313** [comment]
This should be fixed now by a recent patch. Simply comment below if it isn't and I'll reopen the issue. Thanks!
