### ISSUE TITLE
Log in time/Armor skins

### ISSUE THREAD

**Issue by Moogly49** [Wynncraft/Issues#3894]
Hi, since the update, which was just a while ago, I've been having two issues, one of which is not being able to see my armor skin, at least on my assassin class. I have tried /armor, I thought maybe it would just take time, so I gave it a bit longer than usual, nope, still refuses to load. My second issue, which isn't as minor, is the amount of time it takes me to log into a world, not the server. I can log into the server itself just fine, it's logging into the worlds I have issues with. I have tried several worlds, all have failed and given me the same issue. I'm not sure what this update did and hopefully you can fix it, just to clarify, I'm certain this problem is not client side. One more thing I might add, neither of these issues were occurring pre-update.(If you need 'proof,' I can easily get it, just not too how I would go about posting it on this site.)
Thank you, Asplia (IGN)

**Comment by Odnod** [comment]
The "taking a long time to get into a server" is likely just server lag. It will get better in time. If you think it is not just that, you could post the error message which would better allow me to help.

When it comes to the armor skins, they have no impact on the actual game. If you really want to see your armor skins, I can give you more explicit directions later.

**Comment by Moogly49** [comment]
Sadly this login lag has come back, guess I'll have to live with it until it's fixed. Thanks for the help.

**Comment by Trixter313** [comment]
Are you still experiencing this now, since the latest patch? I am able to login fine.

**Comment by Moogly49** [comment]
Yes, I am. It's beyond frustrating, but I can't exactly do anything to help it. Alls I can do is hope the server lag lessens. If that even is the cause.

**Comment by Odnod** [comment]
Could you post the error message you have been getting? It could help a lot. 

Also, if you are using forge it is known to not work with Wynncraft.

**Comment by Moogly49** [comment]
It's more it says "downloading terrain" then either puts me into the world with severe lag or kicks me back into one of the hubs(where you pick what world you'd like to enter). The main message I get would just be "downloading terrain," but it shows that on my screen for minutes, then disconnects me the the hub. If this didn't make sences to you, tell me, I'll try to explain again.

**Comment by Trixter313** [comment]
It's been 20 days, is this still occurring? Thanks!
