### ISSUE TITLE
Tisuan's Valor Legendary Chestplate not obtainible

### ISSUE THREAD

**Issue by slimmyjimmy3369** [Wynncraft/Issues#3895]
Tisuan's Valor Legendary Chest plate isn't obtainable in game. I really want it to be obtainable because I really want it for my build xD Thx if you fix

**Comment by Trixter313** [comment]
Could you provide a little more information? How do you know that it isn't obtainable? Thanks!

**Comment by slimmyjimmy3369** [comment]
Sorry for later answer but many people i asked said it was unobtainable. Many shop owners/players that wanted it said that it wasn't obtainable.

**Comment by slimmyjimmy3369** [comment]
Thanks!

**Comment by Moe-Ronickah** [comment]
This item is not obtainable in-game.  You will have to wait, just like the rest of us, for it's release.  It is no longer in the Item Guide.

**Comment by slimmyjimmy3369** [comment]
Thanks all that helped :100:
