### ISSUE TITLE
Server Connection Freezing and then Getting Kicked - 'Connection Lost. Timed out'

### ISSUE THREAD

**Issue by bazimon** [Wynncraft/Issues#3897]
I've played a lot on the Wynncraft Server, but recently I was switching between Worlds in order to find Bob the Zombie in order to get his item for the 'Bob's Lost Soul Quest' and I was suddenly hit with a drastic amount of server-side lag and kicked from the server. This happened yesterday and since then I have logged back on multiple times but the same thing happens: I walk around, experiencing no server lag for anywhere in between 1-5 minutes and then I am hit with an incredible about of server-side lag, where all mobs freeze and I'm the only one who can move around, quite often, within a minute, the server will unfreeze, but only for a brief second and then immediately freeze back up and eventually kick me from the server with the message 'Connection Lost. Timed out'. As far as I can tell, as long as i don't walk or ride my horse (aka not move), I can stay on the server either indefinitely or for an extended period of time, however this bug means that I can't move anywhere without the server kicking me. This has never happened before and it never occurs in the Wynncraft Lobby or on any of my other classes, so I was hoping that there was a way to fix my profile's Mage account.
IGN:CrafterBazimon

**Comment by Moogly49** [comment]
I've been getting the same issue. The server-side lag has drastically changed(for the worst) for me, and a few others, since this update. Hopefully they get their stuff together and figure out a solution.

**Comment by bazimon** [comment]
Yeah, It seems fixed (for now). Fingers crossed the lag doesn't get any worse then that.

**Comment by bazimon** [comment]
Welp. It just started happening again about 15 minutes ago.

**Comment by Moogly49** [comment]
Yah, came back for me too. Nothing we can do except hope it gets resolved.

**Comment by Trixter313** [comment]
Is the issue still occurring now, since the latest patch?

**Comment by bazimon** [comment]
As far as I can tell, I can't even get past the character selection screen because I just get sent back to the 'Timed out' Message again when selecting my class. I'm unsure if this a result of the same issue, or this is just a bug that is inconveniently occurring at the time when I tried to log in. As soon as I join a lobby, the game either kicks me when failing to load the character selection area (before I download the resource pack), or will teleport me to the character selection menu (after downloading the resource pack), but when I select my class the server doesn't react to me left-clicking the wand and eventually just disconnects me anyway. The furthest I have been able to do is log in and 1/2 chunks will load, but then the game will crash relatively immediately afterwards.

**Comment by Moogly49** [comment]
You have just described what I was trying to say in much better detail, thank you. (Yes, the exact same bug/glitch/not even sure)

**Comment by bazimon** [comment]
I was just able to play for a few minutes and was able to ride my horse from Ragni to Nemract with little to no lag, however, after doing some trading, I rode my horse back to Ragni and the server disconnected me on the way back. As far as I can tell, the problem is fluctuating in severity through out the day, but as soon as I get kicked for the first time after playing for a while, the server will continue to kick me relatively quickly as I log in after the first kick.

**Comment by Moe-Ronickah** [comment]
I haven't experienced this in several days.  Moogly49, bazimon, are either of you still experiencing this?

**Comment by Moogly49** [comment]
This glitch? I honestly don't know. I'm sure this glitch is fine now, but I have no motivation to play. Not from this bug alone, but from my 'login issue.' I have a different post about it so I won't go into it on here.

**Comment by bazimon** [comment]
Its still happening for me. Nothing at all seems to have changed.

**Comment by Dar-krusos** [comment]
You can never be sure if it's server-side. Don't pin the blame too fast, as it may be your internet or the connectiom between the two.

**Comment by bazimon** [comment]
I am relatively sure that it is server-side. It just happened to me in the middle of a playthrough and nothing else, on other servers in Minecraft or out of it, has been affected. I would be really surprised if it was my internet,  since there have been correlation between me and other players suffering from the same glitch, including having similar times of lag and no lag.

**Comment by Moe-Ronickah** [comment]
This was a server issue that was identified and fixed about two weeks after this report.
