### ISSUE TITLE
When everything gets rready for me to start to play I spawn in some little black box?? 

### ISSUE THREAD

**Issue by mickymaster24** [Wynncraft/Issues#3899]
I can't move or anything just simply a little box full of blackness

 - In Llevigar,
 East Statue
I would love if you could Fix this Because I have some good stuff on my mage! and im not gonna do all of that Again to get that It took time, so i would appreciate Some Help! Thanks ! ^-^ <3
- mickymaster24

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should bring you to the nearest visited town. If your issue is now resolved, we'd appreciate if if you closed this issue. Thanks!

**Comment by mickymaster24** [comment]
Thanks It worked Love you! <3 <# ^-^

**Comment by Trixter313** [comment]
Great to hear! =)
