### ISSUE TITLE
'Failed to connect to the server'

### ISSUE THREAD

**Issue by TheTrueComp** [Wynncraft/Issues#3900]
When I am trying to log into the server, it says this: http://imgur.com/AWCNpGk
I think the image speaks for itself.
Just to clarify, I have tried to change the ip to wynncraft.net and wynncraft.org, this does not solve my problem at all...

**Comment by Odnod** [comment]
Try restarting minecraft

**Comment by TheTrueComp** [comment]
Not working andI have this bug since yesterday, so, if your next reply would be "try restarting your computer", I can say for sure that i have tried this out often enough.

**Comment by Trixter313** [comment]
Are you still experiencing this now, since the latest patch? Thanks!

**Comment by Trixter313** [comment]
I'm going to assume the issue isn't still occurring due to no response. If it is, simply comment and I can reopen the issue. Thanks!
