### ISSUE TITLE
Item bug

### ISSUE THREAD

**Issue by maxyme37** [Wynncraft/Issues#3901]
![2016-01-28_18 40 18](https://cloud.githubusercontent.com/assets/16943694/12655128/63cd6c8e-c5ef-11e5-95e6-7832e723de63.png)

**Comment by maxyme37** [comment]
This wand does not work now but it was yesterday...

**Comment by ThunderRemix** [comment]
Throw it away. It's not supposed to exist.

**Comment by maxyme37** [comment]
It was m'y n'est wand .... Sniff and it was m'y only one snif sniff

**Comment by Smurfman254** [comment]
I get a similar issue sometimes but it normally gets fixed with a couple relogs

**Comment by DarkDemonDragon** [comment]
@maxyme37 that was a bugged wand. Holding onto them or selling them is bannable.

**Comment by Trixter313** [comment]
I'm very sorry about your lost wand. May it rest in peace. Ask around and a nice player will most likely give you a new one that can hopefully fill the void in your heart. Good luck!
