### ISSUE TITLE
Set/Dyed Armor is Undyed/Colorless when it drops from mobs.

### ISSUE THREAD

**Issue by ThunderRemix** [Wynncraft/Issues#3903]
I'm sure you all have seen it before. Leaf, Nether, Adventurer, and other set items that are supposed to be dyed are not when the items drop from mobs. I believe this is unintentional, seeing how the Item API lists the items with armorColor values.

**Comment by Trixter313** [comment]
When would a mob drop these items? Aren't you only supposed to be able to get them from merchants?

**Comment by Odnod** [comment]
@Trixter313 they changed it up so that you no longer buy set items from a merchant, but rather you get them from drops around the level like any other item.

**Comment by ThunderRemix** [comment]
I just want to kill this believe that these uncolored/dyed set items are new versions of the colored/dyed ones.

**Comment by Moe-Ronickah** [comment]
" I believe this is unintentional, seeing how the Item API lists the items with armorColor values."  Each set has a unique color value assigned to it, yet the items do not drop with the items colored.  This isn't how it should work.

**Comment by YunoFGasai** [comment]
I think they made it so the old sets will keep their value as collectors items

**Comment by ThunderRemix** [comment]
@YunoFGasai Nah, it's a glitch. Ask Selvut.

**Comment by DebugingLonks** [comment]
@Odnod Tribal Armor. Dyed and buyable is a set item. :) So not all set merchants have been removed.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.

**Comment by DebugMC** [comment]
This is still an issue Moe. Although its a duplicate I think (Can not look
at actual github, only reply on email. Can't link it) but this is why
adventure set is not dyed ingame.
