### ISSUE TITLE
Classes have been lost

### ISSUE THREAD

**Issue by MyEternalHope** [Wynncraft/Issues#3904]
Class(Mage) has been lost. I don't know why.
ID : Joanna_Cat
Last Sign in : 2016-01-20

**Comment by MyEternalHope** [comment]
She can't play the WynnCraft because of busy work.
When she come back. Her Mage has been lost. Can you help us?

**Comment by Odnod** [comment]
You may have accidentally deleted it. Regardless of how you lost the class, I don't think anyone can retrieve it.

**Comment by MyEternalHope** [comment]
I know, but I never delete it. I really want to cry because Mage is my only role. Please, help me.

**Comment by Trixter313** [comment]
Unfortunately there's nothing we can do to recover the lost class but there are some things you can do to minimize the chances of it happening again. Is it possible the the account was hacked or someone else besides you two logged in and deleted the class? If there's any possibility at all, I'd reccomend changing both the Minecraft and associated email's passwords to be safe. Hopefully this ensures this doesn't happen again!
