### ISSUE TITLE
Unable to finish Taproot Quest

### ISSUE THREAD

**Issue by KidFuras** [Wynncraft/Issues#3905]
I am unable to finish the taproot quest as every time I try to do the parlour is does not allow me and prompts me by saying I Shouldnt try to escape

**Comment by Odnod** [comment]
This happens a lot. Go back in the cave a bit and take the parkour slowly. Make sure to hit each part as you go.

**Comment by DarkDemonDragon** [comment]
This happens when you use a travel spell. The reason @Odnod tells you take it slow and hit all the parts is because if you skip over it you will NOT trigger the quest and it assumes you're escaping because you aren't following the quest properly.
