### ISSUE TITLE
Armor health glitch??

### ISSUE THREAD

**Issue by ecwarriorz** [Wynncraft/Issues#3911]
![screen shot 2016-01-27 at 5 13 36 pm](https://cloud.githubusercontent.com/assets/16756977/12693536/6b49864c-c747-11e5-8f63-09ce97292dd9.png)
![screen shot 2016-01-27 at 5 13 56 pm](https://cloud.githubusercontent.com/assets/16756977/12693537/6b4fa590-c747-11e5-8a88-f60cbc51e9cf.png)

I don't know if this is a bug or something, because I'm not too familiar to the new update. But here, Mithril Leggings have +350 health while Chain Link has +400 health. Yet, when I wear Mithril Leggings, I have 2030 total health (18 total hearts), and when I wear Chain Link, I only have 1820 total health (17 total hearts). Is this a bug, or am I just ignorant to the new armor system?

**Comment by Dar-krusos** [comment]
As long as you have 50 more health when wearing Chain Link, it shouldn't be a problem. I think this may just be part of how the heart system works.

**Comment by ecwarriorz** [comment]
The problem is that I have 210 **less** health when I wear Chain Link than when I wear Mithril Leggings.

**Comment by Dar-krusos** [comment]
Oh alright, then it's a bug. There's nothing there that would make sense otherwise.

**Comment by DarkDemonDragon** [comment]
This could have been a bug with on of the items. Most likely one of your items had a typo so on the lore it said one thing, but applied another thing.

**Comment by aaryanbatra** [comment]
I have the same except with different items

**Comment by Moe-Ronickah** [comment]
@aaryanbatra , if you remember what those items were, could you tell me, please?
