### ISSUE TITLE
1x1x2 hole near ice cave

### ISSUE THREAD

**Issue by opps123456789** [Wynncraft/Issues#3913]
![2016-01-29_20 47 15](https://cloud.githubusercontent.com/assets/16432130/12693761/aa09b592-c6c9-11e5-99e8-78c760c43d0d.png)
This needs to be fixed

**Comment by Trixter313** [comment]
Thanks for the report! Should be fixed soon.

**Comment by DarkDemonDragon** [comment]
Well what level area is this? If it's above lvl 40ish (I think you're in a pretty high leveled area due to your mission) then at this point no matter what class you are (Warrior - Charge/Archer - Escape/Mage - Teleport/Assassin - Escape (II+)) you will be able to escape a 1x1x2 hole.
