### ISSUE TITLE
About The Brigand's Brogues Boots

### ISSUE THREAD

**Issue by ItsEdwardGaming** [Wynncraft/Issues#3915]
There is somewhat a bug (or not) is happening on my Brigand's Brougues Boots when ever i try to wear it it keeps saying that i need to have my dexterity to lvl 10 but my dexterity is already lvl 12 and it
keeps telling me the same thing. Pls. fix Thnx you in advance

**Comment by Trixter313** [comment]
Could you post a screenshot of the boots stats and your skill point menu? Thanks!

Also, restarting Minecraft might help.

**Comment by ItsEdwardGaming** [comment]
i tried a couple of times but it didnt work also just now but no it didnt work here's the screenshot of the boots stats and my skill point menu 
![2016-01-30_13 08 28](https://cloud.githubusercontent.com/assets/16969128/12693836/32eec166-c753-11e5-9a0c-2d802ca3e6d0.png)
![2016-01-30_13 08 41](https://cloud.githubusercontent.com/assets/16969128/12693838/3e803514-c753-11e5-8a5a-bfdcb276eba2.png)

**Comment by ThunderRemix** [comment]
Maybe the boots you are trying to replace give a skill point bonus?

**Comment by ItsEdwardGaming** [comment]
i dont think so

**Comment by Dar-krusos** [comment]
When you take off all boots, how much dexterity do you have?

**Comment by ItsEdwardGaming** [comment]
12

**Comment by ItsEdwardGaming** [comment]
literally

**Comment by Trixter313** [comment]
It's been 20 days, is this still happening to you? Thanks!

**Comment by Moe-Ronickah** [comment]
33 days, and closed, due to no response.
