### ISSUE TITLE
Relic Puzzle Bug 

### ISSUE THREAD

**Issue by Complex26** [Wynncraft/Issues#3916]
The Relic Leggings Puzzle door won't stay open long enough, it stays open for around 2 seconds give or take.

**Comment by Dar-krusos** [comment]
Is it a pressure plate system? If so, drop an emerald, or other item you don't need, on it.

**Comment by Verret001** [comment]
@Dar-krusos If its a stone pressure plate that won't work.

**Comment by Complex26** [comment]
No, its a 4 button system

**Comment by Trixter313** [comment]
Will it still not open for long enough?

**Comment by Complex26** [comment]
Yes, still doesn't stay open long enough.

**Comment by Trixter313** [comment]
Is anyone still experiencing this issue? Thanks!

**Comment by Moe-Ronickah** [comment]
Fixed on build server.
