### ISSUE TITLE
Servers Down?

### ISSUE THREAD

**Issue by Deltaaa** [Wynncraft/Issues#3917]
I cant join

**Comment by Dar-krusos** [comment]
Could you provide a screenshot please?

**Comment by wynncraftlupascu** [comment]
![2016-01-30_10 27 39](https://cloud.githubusercontent.com/assets/14152318/12694640/807e05a2-c73c-11e5-9deb-cd1fda32ac8e.png)

**Comment by Dar-krusos** [comment]
Alright, just wait for a bit; they'll come back up. The only time you need to report about the server 'being down' is when you can't connect for more than 2 days.

**Comment by lkjfdsaofmc** [comment]
Anybody?

**Comment by archerdeath666** [comment]
I cant eather

**Comment by lesliep3579** [comment]
its been about a day and a half for me :/

**Comment by SageSlay** [comment]
I like how they close the other thread about this situation and not give an update to what is happening.... At least tell us if you contacted someone to fix this or what they are doing...

**Comment by Dar-krusos** [comment]
Try using node7.wynncraft.com node12.wynncraf.com or any other node#.wynncraft.com.
(Anything works in front of .wynncraft.com)

**Comment by SageSlay** [comment]
That method doesn't work, I just tried it.

**Comment by Dar-krusos** [comment]
Hmm. It's worked for me. Try changing the the first part of the IP until you can get in.

**Comment by Trixter313** [comment]
It should be working now, if it isn't for someone still, simply comment below and I'll reopen the issue. Thanks!
