### ISSUE TITLE
Be put in block

### ISSUE THREAD

**Issue by TienS2** [Wynncraft/Issues#3920]
![2016-01-30_19 20 08](https://cloud.githubusercontent.com/assets/16972006/12695128/585aa526-c787-11e5-8e3e-d2edc5889452.png)

![1eca8e5eb90fe3e908bf27a0fcc461b819c9c689c1613ba814 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/16972006/12695130/5c2eea86-c787-11e5-9053-9dc423d06423.jpg)

I can't use scroll

**Comment by Verret001** [comment]
Try typing /kill with 3+ soul points
