### ISSUE TITLE
I cant join since the new patch

### ISSUE THREAD

**Issue by XderKatzeX** [Wynncraft/Issues#3921]
Everytime I try to log in I 'time out'. That happens everytime since the new patch was added

**Comment by ItsEdwardGaming** [comment]
Me too

**Comment by Verret001** [comment]
Screenshots?

**Comment by XderKatzeX** [comment]
![2016-01-30_16 15 32](https://cloud.githubusercontent.com/assets/16972002/12696505/de56deee-c76c-11e5-85a5-b01b91b90436.png)

**Comment by XderKatzeX** [comment]
That stand in the chat after I went on a other server
![2016-01-30_16 19 08](https://cloud.githubusercontent.com/assets/16972002/12696534/8005fd9c-c76d-11e5-9f0e-f20501fbfcb6.png)

**Comment by Trixter313** [comment]
You should be able to connect now. If not, simply comment down below and I'll reopen the issue. Thanks!
