### ISSUE TITLE
Can you help my friend

### ISSUE THREAD

**Issue by ItsEdwardGaming** [Wynncraft/Issues#3923]
I think me and my firend (ImCrazyGerjan) were having a problem, the thing is that his assassin was standing on top on the floor in the Nemract bank and he was changing armor  when it was drawing the armor to his skin, he fell through the floor and we dont know what to do, we've tried to use teleportation scrolls but it didn't work, so what do we do to get his assassin class back out?

**Comment by archerdeath666** [comment]
try /kill but make sure u hav 3 or more soul points

**Comment by ItsEdwardGaming** [comment]
thnx
