### ISSUE TITLE
Couldn't get into Wynncraft?

### ISSUE THREAD

**Issue by potatopvpmaster** [Wynncraft/Issues#3924]
It says "Error occurred while contacting login servers, are they down?" I have tried to join many times and restarted my computer,what do I do?

**Comment by mickymaster24** [comment]
They Admins and the owner say to report this if u cant get in for 2 or more days :(

**Comment by potatopvpmaster** [comment]
but what do i do right now?

**Comment by mickymaster24** [comment]
I guess we just wait :/

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3917

Please direct any future comments to the original thread. Thanks!
