### ISSUE TITLE
When i join!

### ISSUE THREAD

**Issue by Lixy12** [Wynncraft/Issues#3930]
I select my class and then in the chat it says "Error try again"  so i cant play ;(

**Comment by Trixter313** [comment]
What class is it and what is the exact error message? Thanks!

**Comment by Lixy12** [comment]
The class is all of them mage is my class, i tryed to used other and it just says There has been an error... Try again

**Comment by Lixy12** [comment]
It says There has been an error... Try again
Its on all the classes

**Comment by Trixter313** [comment]
Ah, this would be a duplicte of https://github.com/Wynncraft/Issues/issues/3139 then even though you say it affects all of your classes.

Please direct any future comments to the original thread. Thanks!
