### ISSUE TITLE
Losing items to a full inventory

### ISSUE THREAD

**Issue by Christinel8** [Wynncraft/Issues#3931]
I lost my Momento boots tonight when I was changing armor around. I removed my helm and the boots popped off. The message said that Momentos need my intel at 50. So I expected them to be on the ground. Nope! They were not to be found. This is not the first time this has happened to me and I am asking you to please fix it? Its hard enough to get legendaries and Im so bummed I lost them. Please help :(

**Comment by Odnod** [comment]
Sorry, but Wynncraft has a strict zero-refund policy, your best bet is to buy another pair or move on.

**Comment by Troll2828** [comment]
Go on the forums, people sell a lot of legendaries there. You should find what you're searching for.
