### ISSUE TITLE
Beneath the Depths Boss broken

### ISSUE THREAD

**Issue by Herthi20** [Wynncraft/Issues#3933]
The Treasure Guardian Boss Teleports himself in Lava and he burns so he die.

**Comment by Trixter313** [comment]
How many times has this happened to you?

**Comment by Zeryther** [comment]
It happens constantly to us (I'm with Herthi in a party when we battle the boss).

**Comment by DarkDemonDragon** [comment]
Well he teleports at and away from you so don't lead him into lava.

**Comment by Herthi20** [comment]
We don't lead him into lava. He spawns and then He teleports himself in lava.

**Comment by yairkaraso** [comment]
I Tried to kill him in around 15min and he all the time teleport into the lava.
He teleport every 5sec and he Died around 20+ times in that time and once he killed me with his Arrows storm skill

**Comment by Zeryther** [comment]
Got fixed

**Comment by Trixter313** [comment]
Glad to hear! =)
