### ISSUE TITLE
Stuck in a Block

### ISSUE THREAD

**Issue by Pimm3lZ0mbi3** [Wynncraft/Issues#3937]
I am stuck in a Block. I am in the Quest Green Skinned Trouble. I defeated the boss and stuck in a block by entring the portal. My ingame name is Pimm3lZ0mbi3

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will respawn you at the nearest visited town. If this doesn't fix your issue, comment down below. Thanks!
