### ISSUE TITLE
Item Bomb lost!!!

### ISSUE THREAD

**Issue by craftaurus** [Wynncraft/Issues#3938]
ok, so i was about to use an xp bomb, but when i used, i immediately died cause i fell into a group of zombies, now i lost one and it isnt even active

**Comment by craftaurus** [comment]
i had bought 7, used 1 previously, so i had 6, now i have 5

**Comment by craftaurus** [comment]
is there a way i cn get it back orrrrrrrr

**Comment by craftaurus** [comment]
im about to use one so i will have 4

**Comment by craftaurus** [comment]
halp

**Comment by Trixter313** [comment]
Due to Wynncraft's strict no refunds policy, we can't do anything about the lost bomb. To prevent this from happening again, make sure you are at a safe place when you use a bomb so you don't die and the bomb doesn't despawn.
