### ISSUE TITLE
I am stuck in a tree

### ISSUE THREAD

**Issue by Rexzzzzz** [Wynncraft/Issues#3940]
In the cave used for the quest: Suspended flowers, there is a tree, which has an opening where you can see pumpkins inside the tree. It is easily possible to use the teleport spell to get inside, but there is no way out. the coordinates of the inescapable location in which I'm trapped are: X -501 Y 49 Z -1342

Teleport scrolls aren't working, my theory is they don't work because no matter where you look you'll be in range of a block.

Teleport spell is not working because there is nowhere where I'm not too close to something.

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will respawn you at the nearest visited town. =)
