### ISSUE TITLE
Mob drops don't drop for everyone in a party.

### ISSUE THREAD

**Issue by Aaron9737** [Wynncraft/Issues#3941]
#I've been in about 3 Amadel parties, all of them succeeded at killing Amadel, however, I never got the drop, even though I did participate in the battle and I dealt a lot of damage to Amadel. So I should be getting the drop, but I don't. It only drops for 3 random people in the party and nobody else. Please fix this, as it is incredibly annoying.

**Comment by Trixter313** [comment]
You say you dealt a lot of damage but how do you know for sure? It drops one item per person who did enough damage. It's possible that you just think you did a lot but didn't do enough to make it. I've never had any issues and no one else has reported any issues with it.

**Comment by Trixter313** [comment]
I'm going to assume the issue isn't still occurring due to no response. If it is, simply comment and I can reopen the issue. Thanks!
