### ISSUE TITLE
Slow attack speed weapons don't work with spells

### ISSUE THREAD

**Issue by opps123456789** [Wynncraft/Issues#3944]
I have a slow attack speed wand and it I try to do my right left right to heal but it doesn't do anything.
I spam it and it will finally work after I wait 2 seconds for each click. This needs to be fixed other wise if you have a slow attack speed weapon, and want to heal right away, you won't be able to.

**Comment by Trixter313** [comment]
Could you post some screenshots or a video of the issue? Thanks!

**Comment by DarkDemonDragon** [comment]
Well it is a slow attack speed so expect to have slow gestures. Unless your movements are unusually slow (each left click at slow should take roughly 1-2 seconds) this is just a normal mechanic. If this is too much of a problem for you to fight properly I recommend switching to a weapon with a faster attack speed.
