### ISSUE TITLE
Aldorei elves spawning on ocean coast outside Gavel

### ISSUE THREAD

**Issue by LabyrinthMaster** [Wynncraft/Issues#3947]
Everything is said in the title.
Screenshots : 

https://i.imgur.com/4DHGMNO.png (on the Wynn map, stretches further)

https://i.imgur.com/DGwY47m.png (In-game)

_- Cordialement, Labyrinth~_

**Comment by XavierEXE** [comment]
I believe this has been fixed. @Moe-Ronickah Close?

**Comment by Moe-Ronickah** [comment]
@AckroWynn , has this been fixed?  I don't remember if you got a response from either the GM or builder who made this area.

**Comment by AckroWynn** [comment]
@Moe-Ronickah I am pretty sure I never did.
I'll see to try and fix the issue myself, this time, but as you know from earlier; it's not easy to find other people's mob work.

**Comment by AckroWynn** [comment]
@Moe-Ronickah Lowered the radius of the Aldorei mobs, so now it should be fixed!
