### ISSUE TITLE
Unreachable quest NPC?

### ISSUE THREAD

**Issue by games4maurice** [Wynncraft/Issues#3948]
I found a quest NPC underground that I can't seem to get to.

(I don't want to spoil much because of the rules about "???")

**Comment by Odnod** [comment]
I would not call this a bug. Perhaps you should post it in the questions section of the forums?

**Comment by Johnneh** [comment]
Not a bug. The NPC in question is accessible, but it'll take a lot of work! It's hidden!

**Comment by ThunderRemix** [comment]
You gave us a hint to where this NPC is located. I suggest you close this.

**Comment by DarkDemonDragon** [comment]
Are you sure this is "???" related? Also, a screenshot of said NPC is necessary for staff to do anything. By the way if the NPC is simply called "???" it's just a normal quest NPC. This is used throughout the Wynnexcavation quests and others for a NPC that is simply unknown.

**Comment by Troll2828** [comment]
It is probably the king in Thanos or the other NPC's.

**Comment by games4maurice** [comment]
@Troll2828 No, I've already done all the quests in Thanos.

**Comment by games4maurice** [comment]
Closed, I found out what the NPC was for.
