### ISSUE TITLE
The Sister City Quest {Not Spawning Sand In Selchar}

### ISSUE THREAD

**Issue by Xauf** [Wynncraft/Issues#3950]
In Selchar The Sand From The Hourglass Is Not Spawning

**Comment by Johnneh** [comment]
I cannot go on the server to check for myself, but have you tried changing servers? Are you sure you're at the right spot? If you can, try checking up on the tower, where the glass is (teleport if mage). Sometimes it spawns up there.

**Comment by Xauf** [comment]
yeah i've tried to go to different servers but the same thing happens {no sand in the tower too}

**Comment by Johnneh** [comment]
Maybe after a server restart, it'll be fine? Otherwise I'm not sure what to say

**Comment by Dar-krusos** [comment]
It falls down to the ground, so check on the ground and even below the hill.

**Comment by Xauf** [comment]
Oh, thanks dar it just wasn't spawning inside
thanks :D

**Comment by Dar-krusos** [comment]
No problem! ;D
