### ISSUE TITLE
Items despawn instantly after death

### ISSUE THREAD

**Issue by gpro61978** [Wynncraft/Issues#3954]
I died in the pigman area by the first city and I had 8 stacks of emeralds 3 emerald blocks and I don't remember my exact armor and weapons but they were lvl 16 stuff I really love this server but don't want to lose all of that gear over a tiny glitch please help

**Comment by Troll2828** [comment]
If your soul points drop below 0 you lose your items. Next time you should watch out and afk until your soul points regenerate (they regenerate even if you're offline). Plus you said you were lvl 16 so it shouldn't be hard to get items for your level.

**Comment by RS-Mind** [comment]
He's not talking about his items dropping. He's talking about his items instantly despawning because of chunk loading glitches.

**Comment by Troll2828** [comment]
Oh, ok then.

**Comment by gpro61978** [comment]
yeah it literally just happened again with really good gear so I really can't see the point in starting again if my gear keeps despawning when I get there :/

**Comment by xylke** [comment]
i had the same thing though i had 2 soul points when it happened and still lost all my stuff
after respawning i still had 107 health but when i went to find my stuff near the lvl 15 zombie hill it was all gone....

**Comment by xylke** [comment]
extremely agitating cause i was about to be able to use my toothbrush wand and legendary chest plate next level :(

**Comment by Troll2828** [comment]
Not sure if I get this right but your gear disappears without you dying? If so then I don't know how to fix this. But as @xylke said he lost his stuff when he had 2 soul points, if you die you lose 2 soul and your stuff drops. Therefore it is normal what happened to @xylke .

**Comment by ForcedToxin** [comment]
Yea Im mad too I died in a little Cave with no souls and it Despawned instantly and im really man I have been working hard im lvl.25 and Its hard to get stuff my lvl Please someone fix this and give me something to work with I have the Bedrock Spear Legendary helmet and some rare pants and shoes.

**Comment by ITzGl1TCH** [comment]
WTF?! I lost my stuff! I just got to level 25 with 545 HP and an OP spear and lost it all. My bank has been cleared and I don't want to start over! Pls help!

**Comment by Trixter313** [comment]
@ITzGl1TCH please open your own issue for different issues. Thanks!

**Comment by Moe-Ronickah** [comment]
If you die, and there is no one else in the chunk, the chunk will unload, and all of your items will be despawned.
Don't go out of a city with less than 4 soul points.
