### ISSUE TITLE
Lost Horse Item

### ISSUE THREAD

**Issue by SpraksFly** [Wynncraft/Issues#3958]
5 minutes ago I purchased 2 horses in order to breed them, unsuccessfully. The end result was a brown horse (tier 1) in my inventory. I selected the item in my hotbar and right clicked the ground, as soon as this happened the horse appeared for a second, then disappeared. At the same time Enksar (Quest NPC outside of the horse merchant area) was activated, the quest was already done so all he  basically said was "How is your horse doing?". The horse saddle in my hotbar is now nowhere to be found now, it is simply gone. There was no server restart or loss of connection during this time and I did not drop the item. Has anyone else had this issue? 

Note: I understand others have reported similar issues but most of them lost their horse in the middle of a server restart or connection drop, thus why I noted that either of these were not occurring at the time I lost my horse.

**Comment by Odnod** [comment]
Right click the saddle again?

**Comment by SpraksFly** [comment]
The saddle is completely gone from my inventory, therefore it cannot be right-clicked. It was not dropped either (as stated above).

**Comment by Trixter313** [comment]
Unfortunately due to Wynncraft's strict no refunds policy we can't give you another horse and seeing that no one else has ever reported this, this seems to have been a one time glitch. If you ask around, someone might just give you their horse or maybe at least a discount. Sorry for the inconvenience!
