### ISSUE TITLE
[Chat Issue] Quest dialogue saying [4/4] AFTER quest complete

### ISSUE THREAD

**Issue by CookedPelvis** [Wynncraft/Issues#3959]
![2016-02-01_17 51 56](https://cloud.githubusercontent.com/assets/11055356/12737433/40960502-c90d-11e5-9a88-62ab79386c97.png)

After you complete the quest "Star Thief", Trunan laughs maniacally, but the chat says its [4/4], instead of [1/1]. It's a minor issue, but still should be fixed for consistency with quest dialogues.

**Comment by Alexandrress** [comment]
Fixed! :)
