### ISSUE TITLE
Stuck at Silver Fish dungeon

### ISSUE THREAD

**Issue by MC-Tr0ll3r** [Wynncraft/Issues#3960]
My "character" (MC_Tr0ll3r, if that helps) is stuck at X: -11795, Y: 2, Z: 11722. In the room where you go after "feeding" the snakes.
![2016-02-01_21 20 23](https://cloud.githubusercontent.com/assets/17017296/12737868/f7f1db24-c929-11e5-913c-d0a3358bd687.png)

**Comment by Dar-krusos** [comment]
Okay, do /kill to get out. This will get you out of most 'stuck' situations, but only do it when you have3 or more Soul Points.

**Comment by DarkDemonDragon** [comment]
Still, that's the SF dungeon where each key is like 2 or 4 EB so not the most ideal method.

**Comment by Moe-Ronickah** [comment]
Fixed by Villageacules.
