### ISSUE TITLE
Barriers? Map glitch..

### ISSUE THREAD

**Issue by LotKnockMC** [Wynncraft/Issues#3961]
So, as a mage/archer there are some barriers near the area over the cave with the corrupted sentinels:
![screen shot 2016-01-30 at 2 56 10 pm](https://cloud.githubusercontent.com/assets/16809010/12739179/f4dfef92-c91b-11e5-8338-887e0caa9117.png) Should only be minor to fix and probably won't effect most people, but here it is anyways

**Comment by Trixter313** [comment]
Are you standing on top of barriers in the screenshot, or just glitched into a wall of them?

**Comment by DarkDemonDragon** [comment]
@Sage33 more barriers for you XD

**Comment by LotKnockMC** [comment]
Standing on top of them.

**Comment by Moe-Ronickah** [comment]
Fixed, by Villageacules.
