### ISSUE TITLE
Deadly Lag (Literally)

### ISSUE THREAD

**Issue by bannana345543** [Wynncraft/Issues#3966]
So I have given it my go and I pretty much give up on Wynncraft at this point towards this quest. I get lag, we all do, but this is just dumb. Whenever I go try finishing the final final final boss of Excavation Site D I lag out and sometimes even crash from it. The amount of particles and mobs spawning at a time are crazy. I turn particles off and it actually helps but the fact that there is still lag like no tomorrow is just wrong. I know its not my computer because I have tried multiple computers and over a few days period. I really just wanna get this quest done and its impossible with a lvl100 boss with minions creating crazy lag spikes and crashing me. I even went in there 3 times and died before even spawning in the Final-Final-Final room (there is 3 lvl100 boss, 1 per room). Could you guys reduce the amount of particles or make a timer allowing laggy or players in general from taking damage for teleporting. After trying so many times I am just gonna hope that one of my buds can reach my level soon to help me. I can solo every other boss below lvl70 questing. Combining a laggy boss room and quest with a difficult powerful higher level boss. I get its a hard quest but no one wants to try and hit something that teleports while you lag. Please Fix the lag and boss issue thanks.

**Comment by DarkDemonDragon** [comment]
Hey it's actually recommended to be in a **team** of 3-5 players in order to beat Amadel. It's nearly impossible to solo unless you have the best items available and are one of the top players.

**Comment by DarkDemonDragon** [comment]
I suggest posting on the forums or asking around towns to form a party in order to beat Amadel.
