### ISSUE TITLE
Skeleton Dungeon Glitch?

### ISSUE THREAD

**Issue by Ryxinator** [Wynncraft/Issues#3967]
I've been recently trying to level up my archer on wynncraft and, so i've been doing dungeons. But every time i try (2x so far) the witherhead has gone into the walls and by doing so, making the dungeon impossible to complete.

**Comment by Trixter313** [comment]
Is this issue still occurring?

**Comment by Trixter313** [comment]
I'm going to assume that the issue is now fixed due to no response. If anyone is still experiencing it, simply comment and I'll reopen the issue. Thanks!
