### ISSUE TITLE
Dieing and all my stuff is gone

### ISSUE THREAD

**Issue by ForcedToxin** [Wynncraft/Issues#3968]
I Went into this cave and Died by a ruin guard and when I spawned and went all the way back it was all gone there spawns reset and everything im really sad I had really good stuff that I cant get back what do I do

**Comment by Dar-krusos** [comment]
You can't do anything unfortunately; there's a no-refund policy, so the only thing you can do is move on and get other, possibly better, gear.

**Comment by DarkDemonDragon** [comment]
The only thing you can do is learn from this experience to be more aware of your SP so that this doesn't happen again :)
