### ISSUE TITLE
Broken Item

### ISSUE THREAD

**Issue by Racer10** [Wynncraft/Issues#3969]
I have a Pelier in my inventory that is completely messed up. Screenshot for reference.
The skin shows when equipped, but the stat bonuses don't take effect
![2016-02-02_22 13 05](https://cloud.githubusercontent.com/assets/4590683/12771851/7f43b7c0-c9fa-11e5-910f-afdaef9084c0.png)

**Comment by Dar-krusos** [comment]
Duplicate: Issue #3175

Please follow the [(https://github.com/Wynncraft/Issues/issues/3969)directory] and see if your issue is already there, as they do not like it when multiple threads of the same issue clump up the Github.

**Comment by DarkDemonDragon** [comment]
@Dar-krusos the directory is a bit outdated which is why it was closed.
