### ISSUE TITLE
Stuck under floors?

### ISSUE THREAD

**Issue by Shaebertooth** [Wynncraft/Issues#3970]
The server reset while I was in the bank in one of the towns. When I logged back in there was a message saying I wasn't permitted only once, and I'm trapped in what I think is a small space beneath the floor. It's dark, I can't use my jumping or skills to get out of the floor, but I can run in a small space that I think is about 3x2 squares big (since when I run in a certain direction my mana goes down). I also can't talk in-game for whatever reason, and I can't use my teleportation scroll to get out.

My IGN is Ghostwhisker.

**Comment by Odnod** [comment]
Contact a moderator and explain to them that nemract bank is broken like llevigar recently. They will tp you out.

**Comment by Troll2828** [comment]
just do /kill if you have 3 or more soul points
