### ISSUE TITLE
Stuck in wall

### ISSUE THREAD

**Issue by karel512345** [Wynncraft/Issues#3971]
i'm not sure if i need to put this in this section, but this is my problem,

Over in Nemract i was doing the 'mansion' mission when i used teleport (i am a mage)
I got stuck in this wall and i have 3 teleportation scrolls but none of them works for some reason,
I also tried to use my teleportation spell but that doesn't work either, i just remain in the same wall i was in before.
Can anyone help me?
Thanks in advance!

IGN: karel5123

**Comment by DarkDemonDragon** [comment]
When you are stuck in a block you can't use scrolls because you have to click the air with them. If you are stuck in a block do /kill if you have enough SP do go to the nearest town.
