### ISSUE TITLE
Wynncraft

### ISSUE THREAD

**Issue by ricardoandren** [Wynncraft/Issues#3972]
Died when i was in Craftmas quest
i died 2 times and i have enough of buying boats and getting back to where i was

died during stage 8

**Comment by Odnod** [comment]
How is this a bug exactly?

**Comment by DarkDemonDragon** [comment]
This is a place for bug reports, not complaints on game mechanics. @Trixter313 please close this.

**Comment by Trixter313** [comment]
You can create a post here https://forums.wynncraft.com/forums/general-suggestions.69/ if you'd like to submit a suggestion. Thanks!
