### ISSUE TITLE
Forum post "More Options" not working

### ISSUE THREAD

**Issue by TheChampion879** [Wynncraft/Issues#3975]
My forum post isnt letting me click more options, it just goes to a blank page. Its also only the first forum post in the thread, all other posts work fine. Any ideas?

**Comment by DarkDemonDragon** [comment]
What sort of post were you trying to make? Profile post, New Thread, Comment, etc.

**Comment by Trixter313** [comment]
Also, try using another browser to see if it works then.

**Comment by Trixter313** [comment]
I'm going to assume that the issue is now fixed due to no response. If anyone is still experiencing it, simply comment and I'll reopen the issue. Thanks!
