### ISSUE TITLE
Disconnect or no disconnect? - Personal bug

### ISSUE THREAD

**Issue by yayRoku** [Wynncraft/Issues#3976]
Hi. _I'm spanish. My english level is minimal_

Today, 1-2 hours ago, I lost all my stuff for a Minecraft 1.8.8 bug (or a Wynncraft server bug; I don't know)
I leave the server and 10-20 minutes later, i trying to connect to the server, but the server says: "Already connect to the server" in red words
I try to restart the game (Minecraft), I went back to try to connect but I lsot all my stuff. 

Deaths? Inventory bug? Minecraft bug (from my point of view, the most likely)? 
(The console of the server makes clear the intense bug :V)

I don`t remember my stuff, but It is why I make this report
I hope I have been understandable.
(Ah, nickname: yayRoku / Archer / Lvl48)

Bye!

**Comment by redxdev** [comment]
None of the above. Wait an hour or two, then try to reconnect. Sometimes there are some issues with the way the servers handle disconnects, and they think you're still connected.

**Comment by DarkDemonDragon** [comment]
@yayRoku I'm sorry, but Wynncraft has a no-refund policy. I'm not sure if you were able to read the tips, but Wynncraft has a death system were you every time you die you lose 2 soul points. Once your soul points hit 0 you will lose all your items.

**Comment by yayRoku** [comment]
The vug of my policy
I don't have the experience of this "deaths"
I staying "disconnected"

**Comment by yayRoku** [comment]
Bug*

**Comment by DarkDemonDragon** [comment]
@Trixter313 do you know anyone that can speak Spanish because I think there is some miscommunication.

**Comment by Trixter313** [comment]
I think they are saying that they got disconnected and when they logged back in, all of their items were gone.

**Comment by Trixter313** [comment]
Unfortunately there's not much we can do because of the no refunds policy and because of the language barrier, we can't even figure out what really happened. Maybe your account got hacked and someone else logged in as you and deleted your items? If that's at all a possibility, I'd recommend changing your MC and associated email's passwords to prevent it from happening again.
