### ISSUE TITLE
Falling through small Island, when joining a World

### ISSUE THREAD

**Issue by Joly0** [Wynncraft/Issues#3978]
![2016-02-03_22 04 16](https://cloud.githubusercontent.com/assets/13993216/12797083/87a7032c-cac2-11e5-8ff5-f9ac21e40879.png)

Everytime i spawn in the Lobby, then i try to join a world, with the compass or the portal, then i spawn on this rly weird island and fall through the ground and deeper and deeper but i never die and cant play normally

**Comment by DarkDemonDragon** [comment]
Whoa that's really strange. So have you made a class before? Also have you used /autojoin before?

**Comment by Joly0** [comment]
No, i havent made a class before, its the first time i join this Server. A while ago i played with the account of a friend in the Server, there everything worked, also if i try to join now.i havent used /autojoin, will try it later

**Comment by Joly0** [comment]
Ok, /autojoin doesnt work, it says: plsease go into a game world to use commands

**Comment by Joly0** [comment]
Ok, /autojoin doesnt work, it says: plsease go into a game world to use commands

**Comment by Trixter313** [comment]
Do you have the server resourcepack enabled? Most people who see this island have it disable and enabling fixes it for them. Go to your server list, select Wynncraft, click edit and make sure server resourcepacks says enabled. Hope this helps!

**Comment by Joly0** [comment]
I did, what u wrote, but its still the normal standart minecraft texturepack, it doesnt ask me to download or something like this

**Comment by Joly0** [comment]
ok, finally it worked, i can play on the server. but do i always need to play with this texture pack?  cant i play with my own?

**Comment by DarkDemonDragon** [comment]
@Joly0 do you mean the WynnPack? The game is meant to be played with the Resource Pack on and doesn't support the default vanilla Minecraft look anymore.

**Comment by Joly0** [comment]
Why is this so?

**Comment by DarkDemonDragon** [comment]
Just play through the game and you'll realize. Is it problematic for you to use the Server Resource Pack?

**Comment by Joly0** [comment]
More or less, its confusing me, cause i normally play with HD texturepacks

**Comment by DarkDemonDragon** [comment]
Well they wouldn't be compatible since most of the weapons are just slabs in Vanilla Minecraft and the GUIs would look awkward.
