### ISSUE TITLE
Quest : "Green Skinned Trouble" broken

### ISSUE THREAD

**Issue by LabyrinthMaster** [Wynncraft/Issues#3980]
In the cave underneath the lake, after resolving the pressure plate puzzle, falling down the hole is impossible and instead, this message will appear : 
https://i.imgur.com/Dr7F21A.png

_-Cordialement, Labyrinth~_

**Comment by Moe-Ronickah** [comment]
Are you trying to walk/run/jump into the passage, or are you trying to teleport into the passage?

**Comment by LabyrinthMaster** [comment]
Just simply falling in it, as I'm supposed to be after solving the puzzle.
And I get teleported out with a "null" message.

**Comment by Moe-Ronickah** [comment]
Where are you with this now?  Is it solved?  If you solved it, how did you do it?

**Comment by Trixter313** [comment]
I'm going to assume that the issue is now fixed due to no response. If anyone is still experiencing it, simply comment and I'll reopen the issue. Thanks!
