### ISSUE TITLE
Skin Bug

### ISSUE THREAD

**Issue by xXSubmindXx** [Wynncraft/Issues#3982]
I dont see me with my actual skin. I see me in this default Alex skin. Can someone help me with this ?
It took long to make this skin and i dont see it on this server.

**Comment by Trixter313** [comment]
When did you upload your new skin to Minecraft? It can take time for the skin servers to update and with how Wynncraft does their armor skins, it can take longer than usual for it to update. Try taking all of your armor off and see if the correct skin shows up then.

**Comment by xXSubmindXx** [comment]
I uploaded my skin some month ago and i dont have any armor. In the lobby i see my skin but in the rpg world its gone. i see skin from other players but not my own.

**Comment by Roran27** [comment]
I have exact the same problem. In the lobby my skin is as I want it to be, but in the game I'm just Alex...

**Comment by Moe-Ronickah** [comment]
If you are using any version of MC older than 1.8 this is a known MC bug.

**Comment by Trixter313** [comment]
What MC version are you using? 1.8.9 is recommended.

**Comment by xXSubmindXx** [comment]
I play with 1.8 and i tried to use 1.8.8 because there is no 1.8.9 in my launcher but it didnt work :c

**Comment by Trixter313** [comment]
Hmm, your launcher might be outdated. What version does it say at the top of the launcher? The latest should be 1.6.51

You can try redownloading the launcher at https://minecraft.net/download (The .msi is recommended for Windows) and see if that helps anything. I know that was the issue for a few users.

**Comment by xXSubmindXx** [comment]
Oh i didnt saw 1.8.9 it was between all the snapshots but i tried now with 1.8.9 but it didnt work :c

**Comment by Roran27** [comment]
So I haven't changed my skin for a while, but first time I played Wynncraft, I was Alex. The next day my Skin was all right, but now I'm Alex agan. (and my Version is 1.8.9) I don't know why.

**Comment by Dari1919** [comment]
same problem here, in the lobby my skin is the one i made but when i enter the actual game im alex.

**Comment by Moe-Ronickah** [comment]
@Dari1919 , give it some time, sometimes as long as a day.  Skins information is stored in-game for loading speed, and it can take a while for the information to update in-game.
