### ISSUE TITLE
Stuck in an Inn Underground

### ISSUE THREAD

**Issue by SenorPig** [Wynncraft/Issues#3983]
I found an Inn while on an adventure and decided to go into a bed, i got thrown out and now i am in a 4x4 of pitch blackness underground HELP!! I can't use my range tp scroll  and i need to get back to Deltas or something, please help quick

**Comment by Troll2828** [comment]
do /kill if you have 3 soul points or more

**Comment by SenorPig** [comment]
Thank You so much man!!
