### ISSUE TITLE
i cant see my armor's skin.What should i do?

### ISSUE THREAD

**Issue by AnarchistArcher** [Wynncraft/Issues#3984]

**Comment by Troll2828** [comment]
It's just a bug, sometimes it won't show up

**Comment by AnarchistArcher** [comment]
the game says :"We are drawing your new armor but it isnt.(My english not very well.Because im from turkey.).Can you help me about it or can i fix the bug ?

**Comment by Troll2828** [comment]
There is no fix, sometimes it doesn't appear on my skin either. It's not a big deal.

**Comment by AnarchistArcher** [comment]
thx for helping.
