### ISSUE TITLE
Jungle Fever Quest Broken

### ISSUE THREAD

**Issue by XilverSemi** [Wynncraft/Issues#3986]
Okay, so, I only have 63 Almuj's LE, and I can't even finish the quest! I hope you guys can help me soon, because I'm just really frustrated that I can't finish the quest. Thank you for taking your time to read this, and bye. I also couldn't do /fixquests

**Comment by DarkDemonDragon** [comment]
Please provide screenshots.

**Comment by Trixter313** [comment]
If you make all of the quest LE disappear by dropping it with a full inventory while standing over an item, /fixquests should work. Report back any changes or updates!

**Comment by XilverSemi** [comment]
THANK YOU!

**Comment by Trixter313** [comment]
Glad to hear it's fixed =)
