### ISSUE TITLE
Stuck in the classes box

### ISSUE THREAD

**Issue by Place-Name-Here** [Wynncraft/Issues#3987]
Whenever I try to connect to my Archer class it just leaves me in the box but other accounts work

IGN: Place_Name_Here

**Comment by Place-Name-Here** [comment]
I managed to fix it with /kill to suicide but I'll leave it open as I don't know what caused it, and it's a bug.

**Comment by Trixter313** [comment]
This randomly happens sometimes and is known about so the issue didn't need to stay open. In most cases, /kill fixed it anyway like you did.
