### ISSUE TITLE
No Item Identifier?

### ISSUE THREAD

**Issue by Fiireburner** [Wynncraft/Issues#3988]
Idk if the staff hasnt gotten to put him here yet but there isnt one in Pirate Town..
![2016-02-05_14 17 26](https://cloud.githubusercontent.com/assets/17088890/12856695/225a92f6-cc14-11e5-95b6-caa22149d51c.png)

and btw.. the reason why im here at lvl 28 was for the item identifier xD

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3272

Please direct any future comments to the original thread. Thanks!

**Comment by Fiireburner** [comment]
oops i didnt know sry :C

**Comment by Trixter313** [comment]
It's fine =) No big deal
