### ISSUE TITLE
Mage teleportation reversing progress of quest

### ISSUE THREAD

**Issue by Moon-night0922** [Wynncraft/Issues#3990]
When I'm going to submit (finish) the quest "The Headless Hunt", the Quest NPC (Referick) told me to empty some space in my inventory first.
Then I threw some Mana Potion behind the NPC to continue the conversation by right-clicking it with my weapon.
After Referick had said 5/6 out of 8 of the conversation, I accidentally teleported to its back and pick up the potions.
After that, I threw the potions again and it didn't continue the conversation, instead, it told me to check out the mansion again. (I still had the paper in my inventory)

P.S. It has happened on my friend and I just help him to report
P.P.S. He doesn't have any screenshot about it

**Comment by Trixter313** [comment]
So was your friend able to complete the quest? Thanks!

**Comment by Moon-night0922** [comment]
My bad lol, I made some mistakes here:
1. The item we need to submit is the sugar called "Memento of the Lost"
2. What actually happened is the NPC took the sugar, but he couldn't complete the quest because the inventory is full again and was unable to take the reward. As a result, it required him to submit the sugar again.

Btw, he completed the quest after re-submitted it.

**Comment by Trixter313** [comment]
If he completed the quest the issue should be resolved.
