### ISSUE TITLE
I Cant Complete The Quest "Prison Story"

### ISSUE THREAD

**Issue by Pupydani** [Wynncraft/Issues#3993]
i cant get the prison key, and in the book is write give the key to ooni but i cant complete it

**Comment by Trixter313** [comment]
If you lost the key, you can try typing /fixquests to see if it returns it. If that doesn't work, make sure it isn't in any other classes or your bank.

**Comment by Trixter313** [comment]
Did /fixquests fix the issue? Thanks!

**Comment by Pupydani** [comment]
yes, very thx for the support ;)

**Comment by Trixter313** [comment]
Glad to hear!
