### ISSUE TITLE
Permanently stuck in "Your Guild is already in a battle" Mode

### ISSUE THREAD

**Issue by ltvuong** [Wynncraft/Issues#3995]
So when I was attacking a territory, as the countdown hit 0, it said that there was an error connecting to the server. I didn't get tp'd to a war server I just sat there. Every since then whenever me and my guild try to attack a territory, it tells us that the guild is already in a battle, even when no one is in a war server.

**Comment by Trixter313** [comment]
A decent amount of time has passed, is the issue still occurring now? Thanks!

**Comment by ltvuong** [comment]
The issue seemed to fix itself. Thanks!

**Comment by Trixter313** [comment]
Good to hear =)
