### ISSUE TITLE
Can't do WynnExcavation Site A Quest

### ISSUE THREAD

**Issue by xXJDAXx** [Wynncraft/Issues#3997]
I did not get the items in the beginning from the Lab Assistant Tesh so now I can't complete it. Could you please reset this quest for me?

IGN: xXJDAXx
Class: Warrior
Level: 52

**Comment by TrashcanMan** [comment]
Try doing /fixquests.

**Comment by Trixter313** [comment]
Did /fixquests resolve your issue? Thanks!

**Comment by Trixter313** [comment]
I'm going to assume that the issue is now fixed due to no response. If anyone is still experiencing it, simply comment and I'll reopen the issue. Thanks!
