### ISSUE TITLE
Right clicking not working when trying to cast a spell

### ISSUE THREAD

**Issue by opps123456789** [Wynncraft/Issues#4000]
When I am on top of a platform and trying to right click with my weapon to cast a spell, most of the time the right click doesn't work and I am unable to cast a spell while doing so. This ONLY happens when looking down from a platform and no where else I believe. Plz fix :)

**Comment by Moe-Ronickah** [comment]
This is not a glitch, it is actually an MC mechanic.  The right click in MC is read as if you are interacting with either an item or an NPC, therefore, if the mob is very close to you, the game will read it as if you are intentionally trying to interact with the mob.
