### ISSUE TITLE
Grave Digger Quest

### ISSUE THREAD

**Issue by TheRainbowPanda** [Wynncraft/Issues#4001]
when i killed sayleros' brother and went back to sayleros i tried to click on sayleros but he doesn't say anything

**Comment by TrashcanMan** [comment]
Do you have the Dusty Will with you? Maybe you didn't collect it.

**Comment by TheRainbowPanda** [comment]
i got the dusty will

**Comment by Trixter313** [comment]
Could you post a screenshot of what it shows in your questbook and your inventory? Thanks!

**Comment by Trixter313** [comment]
I'm going to assume that the issue is now fixed due to no response. If anyone is still experiencing it, simply comment and I'll reopen the issue. Thanks!
