### ISSUE TITLE
Resource Pack

### ISSUE THREAD

**Issue by ImRyan17** [Wynncraft/Issues#4002]
Resource pack will not load..
I have the old resource pack that was before Gavel.
I tried deleting and re-adding the server and enabling the resource pack but it won't work.
Every time I try it i get the old bad resource pack.

Yes I have read the post Salted made about "If it isn't working" but
I try it and try it and try it again but I just can't get the resource pack.
I'm very tired us using a block as a weapon, and not having the resource
pack just ruins the game.

**Comment by Trixter313** [comment]
There wasn't an official resource pack before Gavel, so I assume you mean a 3rd party, player-created resource pack. If so, simply going into settings, then resource packs, and disabling any resource packs there should fix it. Or you could just delete the resource pack(s) from the resource pack folder in your .Minecraft folder.

**Comment by Dar-krusos** [comment]
Are you in the latest version of minecraft? Also, have you tried using an alternate launcher, whether newer, older, or different?

**Comment by ImRyan17** [comment]
When I joined Wynncraft before Gavel it asked me if I'd like to download their texture pack and I hit yes, and that is the texture pack I have today.I tried de-selecting my resource packs then re-joining and it wouldn't work.

I also updated to 1.8.9 and it still will not work.
I am not deleting my resource packs, I've also tried prompting the resource pack yet it still gives me the old crappy one.

**Comment by Dar-krusos** [comment]
There was no old resource pack before this one. There has only ever been one version of it implemented, and that is the current one.

> Also, have you tried using an alternate launcher, whether newer, older, or different?
> - Dar-krusos
Have you tried this yet?

**Comment by Trixter313** [comment]
You can also try deleting anything located in the server-resource-packs folder in your .minecraft and see if that helps anything.

**Comment by ImRyan17** [comment]
I updated my Minecraft launcher and it worked,

thanks for the help.

**Comment by Trixter313** [comment]
Glad to see your issue is now resolved =)
