### ISSUE TITLE
Santa Skin not working

### ISSUE THREAD

**Issue by SamBellettiere** [Wynncraft/Issues#4003]
I recently did the Craftsmas Chaos Quest and noticed the the santa npc had a really weird skin. Not sure if this is intentional but I figured I would bring it to your attention. I have attached a screenshot of what it looks like.
![2016-02-06_15 08 28](https://cloud.githubusercontent.com/assets/17102575/12869466/4216004e-cce6-11e5-8d37-c220e02883e9.png)

**Comment by GlitchDoesMC** [comment]
Yup, there are many NPCs with the player type not having their skins. As a result, they look like this. It should be fixed soon.

**Comment by Trixter313** [comment]
I've seen this happen to Sherk also.

**Comment by Moe-Ronickah** [comment]
Fixed on build server as of this date.  It will show up with the next map push.
