### ISSUE TITLE
I'm stuck >:O

### ISSUE THREAD

**Issue by wolfiehannah** [Wynncraft/Issues#4005]
I am stuck in the class picking room, nothing can fix it. I have all of my settings correct, I have the resource pack enabled. Please help. 
![2016-02-06_18 07 13](https://cloud.githubusercontent.com/assets/17103301/12869962/71a30cd8-ccfc-11e5-9d63-11f98850a90e.png)

**Comment by Trixter313** [comment]
Typing /kill with 4+ soul points should bring you to the nearest visited town. If this resolves your issue, please close the thread. Thanks!

**Comment by MCtroller3936** [comment]
oh hey that happened 2 me 2

**Comment by wolfiehannah** [comment]
thank you very much :3
