### ISSUE TITLE
Wedding Ring Quest

### ISSUE THREAD

**Issue by DarkGamer41** [Wynncraft/Issues#4006]
I've been playing and I just did the Wedding Ring quest, I'm level 10, but when I have the Wedding Ring I can't rfinish the quest. Is this a bug? If not can you tell me how to fix it?!

**Comment by Trixter313** [comment]
There are two rings. The first one turns out to just be a washer and then you have to go in a hole in the field to get the real ring. I believe the real ring is a golden nugget. Many people make this mistake and is most likely the issue. Hope this helps!
