### ISSUE TITLE
Cant log onto wynncraft

### ISSUE THREAD

**Issue by HeroicaIIy** [Wynncraft/Issues#4010]
For some reason after 10am australian time me and my friend cant log on, it will take awhile using the compass in the lobby and if we do get in a world then it will show downloading terrian or we will get kicking for flying. pls help
all other servers work normally :/

**Comment by TrashcanMan** [comment]
It might be a scheduled restart for maintenance, is it every day or just one or two times?

**Comment by HeroicaIIy** [comment]
Seems to be happening everyday, it started on Friday night in the silver fish dungeon...

**Comment by HeroicaIIy** [comment]
Well... It was working ._.

**Comment by Dar-krusos** [comment]
This doesn't happen to me, so it may just be a problem on your end.

**Comment by Trixter313** [comment]
What MC version are you using? Also, you could try restarting your router and computer to see if that helps any. Other than that I'm stumped.

**Comment by Trixter313** [comment]
I'm going to assume that the issue is now fixed due to no response. If anyone is still experiencing it, simply comment and I'll reopen the issue. Thanks!
