### ISSUE TITLE
Items Despawn Upon Death?

### ISSUE THREAD

**Issue by ShrimplePuff** [Wynncraft/Issues#4011]
I'm level 27 and a mage class, and I died during the quest "Pit Of The Dead".  I had the cap and boots of the Adventurer Set, the Alligator chestplate, and I can't remember the pants.  I had a total health of about 415 when I died and respawned.  I also had two rare wands- the Midnight Bell and Celestial (which took me a while to get) When I went back to the pit, everything was gone, but I thought nothing of it.  I went back to Detlas and started to try and get some armor and another wand than the Oak Wood Stick that was given.  After I died some more times due to a weak weapon against tougher enemies, I realized that I was getting there in 20 seconds or so and everything was gone.  There was no one around me either.  Is there anyway I can get any of my things back, or do I have to start from square one again? Thanks anyways.
~ShrimplePuff

**Comment by Dar-krusos** [comment]
You'll have to get your items back through other methods. You won't be able to get those ones you dropped back as the chunks have despawned. Ask around for some items; I'm sure someone can help you back on your feet (I wish I could, but I have no items around lv27 :/ ).

**Comment by ShrimplePuff** [comment]
Alright, that's a bit of a bummer, but thanks.  Hopefully I'll find someone soon!
