### ISSUE TITLE
Lord of The Clock quest Problems

### ISSUE THREAD

**Issue by DopeFreshPanda** [Wynncraft/Issues#4015]
Sooo im doing the lord of the clock quest and ive done the hole thing until i get to the NPC Frudo In the mountain of whynn. When i click on him he does not say anything.... Was i suppose to get the clock in my inv or something?  can someone help me maby?

**Comment by Dar-krusos** [comment]
Yes, you need to have the clock in your inventory. If it, for any reason, is not in your inventory, do /fixquests and see if you can recover it from that.

**Comment by DopeFreshPanda** [comment]
Me and a friend already tried to do /fixquests and it gave me nothing.

**Comment by Trixter313** [comment]
Are you sure the clock isn't in any other classes inventory or your bank?

**Comment by DopeFreshPanda** [comment]
I don't use any other classes besides my archer and I just checked my bank and there was nothing in there

**Comment by Trixter313** [comment]
Hmm, what does it say in your quest book?

**Comment by Trixter313** [comment]
I'm going to assume that the issue is now fixed due to no response. If anyone is still experiencing it, simply comment and I'll reopen the issue. Thanks!
