### ISSUE TITLE
Farmer Kelri (Ragni)

### ISSUE THREAD

**Issue by CyranoTrinity** [Wynncraft/Issues#4016]
Farmer Kelri is a pain in the ass...
I have the wedding ring yet he dosent accept it.
![2016-02-07_15 27 07](https://cloud.githubusercontent.com/assets/12232487/12871334/b4136a00-cdaf-11e5-9d15-22408293e1c3.png)
![2016-02-07_15 27 16](https://cloud.githubusercontent.com/assets/12232487/12871335/b8019254-cdaf-11e5-9ba2-8e3917ef385b.png)

**Comment by Dar-krusos** [comment]
If this is the first part of the quest, you need to obtain 'A Washer' from the rats, and if you've already done that, you need to go in the cave in the wheat field where there will be a Giant Rat which drops 'The Wedding Ring'.

**Comment by Trixter313** [comment]
Also, I believe the real wedding ring is a golden nugget, if that helps.

**Comment by CyranoTrinity** [comment]
Ah I see, thanks. (P.S. The game is tricky)
