### ISSUE TITLE
Forum IGN didnt update when i changed my name.

### ISSUE THREAD

**Issue by CodenBeast** [Wynncraft/Issues#4017]
Hi, i changed my name a pretty long while ago to CodenBeast but it never updated me IGN in my profile. It still says kennel1. Does anyone know how to update what my current username is?
Thanks

**Comment by Dar-krusos** [comment]
Your in-game username does not sync with your forums account. You'll have to change it manually by following these instructions with this picture
> !(http://i.imgur.com/0M3QNpE.png)
> Images:
> 1. Click on the _Personal Details_ section in your drop-down menu at the top.
> 2. Locate the _Minecraft:_ box and change the username accordingly.
> - Dar-krusos

**Comment by CodenBeast** [comment]
@Dar-krusos Thx, will this maybe fix that it doesnt account for the xp i gain for my guild?

**Comment by Dar-krusos** [comment]
No, sorry. The forums actually has no real connection to the game, other than that you can display your VIP/VIP/Staff/Creator tag if you link the two in-game using _/forums [forum username]_ (this doesn't work right now).
