### ISSUE TITLE
I can't get out from the starting point

### ISSUE THREAD

**Issue by dhghktjd** [Wynncraft/Issues#4018]
![2016-02-07_22 49 08](https://cloud.githubusercontent.com/assets/17109191/12872708/207504aa-cded-11e5-833f-5bfbb3d130da.png)
My warrior can't get out from the starting point.
At first, I thought it was simple bug, so I waited until this problem solved.
But it didn't solved nevertheless I waited for 30 minutes.
This happened only when I logged in warrior. Other characters worked well.
Also I can't use my Nemract teleportation scroll, too.
I don't know why. Please help me.

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should bring you to the nearest visited town.
