### ISSUE TITLE
can,t open or touch things

### ISSUE THREAD

**Issue by olta2309** [Wynncraft/Issues#4021]
every time i try to open a chest or open a door i can,t it just says "you don,t have permission in this area" that,s it

**Comment by DarkDemonDragon** [comment]
This is because you have a weapon in your hand. Weapons are just reskined slabs so when you rightclick with them, the server thinks you're trying to place a block. Simply right click with an empty hand and you[ll be able to open things. If this resolved your issue please close this,

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3902

Please direct any future comments to the original thread. Thanks!

**Comment by olta2309** [comment]
thanks for the help
