### ISSUE TITLE
Creeper Mask Disappeared

### ISSUE THREAD

**Issue by BigTomD** [Wynncraft/Issues#4022]
I was doing the Creeper Infiltrator Quest that requires the Creeper mask, however, i had to move around my inventory for more items and it disappeared when I was holding it and a Mob attacked me and I was forced to go out of my inventory. Since I cannot get another one because it was a quest item, I can no longer finish the quest without it.

**Comment by Trixter313** [comment]
Try typing the command /fixquests

If this works, please close this issue. Thanks!
