### ISSUE TITLE
Stuck under silverfish dungeon

### ISSUE THREAD

**Issue by poepser132** [Wynncraft/Issues#4025]
So, i was doing the silverfish dungeon with my friend and i got on my horse after the parkour part where you need to choose between the 3 types of parkour, when i got off my horse i glitched under the ground, i hope you can fix this so i dont loose my soulpoints

**Comment by Trixter313** [comment]
If you type /kill with 3+ soul points it should get you out. Soul points regen every ingame sunrise (~20 min I believe) and every hour while offline so it shouldn't be that much of a loss.
