### ISSUE TITLE
Relic Boots Not Drawing

### ISSUE THREAD

**Issue by Blocktopia9** [Wynncraft/Issues#4027]
Hi, just wanted to say that the relic boots are not drawing on my character, I've waited 10 minutes and they didn't draw. I don't know if it happens for the whole set as I do not have the whole set.

**Comment by Blocktopia9** [comment]
It finally drew after about half an hour, but still fix pls

**Comment by Dar-krusos** [comment]
Just try changing servers. If that doesn't work, it might be that the whole server is lagging or the item itself is bugged.

**Comment by Trixter313** [comment]
Have you experienced this at all since then? It might just have been a one time issue or as Dar-krusos said, lag which not much can be done about.

**Comment by Trixter313** [comment]
I'm going to assume that the issue is now fixed due to no response. If anyone is still experiencing it, simply comment and I'll reopen the issue. Thanks!
