### ISSUE TITLE
Cant see certain people, or they cant see me.

### ISSUE THREAD

**Issue by MrNinjaBro** [Wynncraft/Issues#4028]
So on some worlds i can see my friend and he cant see me. But on other worlds I cant see my friend and he can see me. Anybody know?

**Comment by TrashcanMan** [comment]
Try relogging, restarting Minecraft, updating Minecraft, etc.

**Comment by Trixter313** [comment]
Are you still experiencing this after trying the above advice? Thanks!

**Comment by Trixter313** [comment]
I'm going to assume that the issue is now fixed due to no response. If anyone is still experiencing it, simply comment and I'll reopen the issue. Thanks!
