### ISSUE TITLE
Nicola Woods lagging me out!

### ISSUE THREAD

**Issue by RoundPikachu** [Wynncraft/Issues#4031]
When I was walking through Nivla woods, the world starting flashing, as if it kept refreshing the chunk, the spiders in Nivla woods eventually killed me and I lost all of my stuff. When I respawned the world kept refreshing and it was really annoying. Don't know if it is just me but I really need help on this. I was level 29/30 Archer. IGN Round_Pikachu. I hope you can fix this. I will try a different class now even though I spent 3 days getting good loot. Thx

**Comment by Moe-Ronickah** [comment]
This can occur when you have another program trying to get your attention visually.  Is it still happening with your archer, or is it fixed, now?

**Comment by Dar-krusos** [comment]
This has mostly to do with your computer. The easiest solution is just to get a better video card and/or processor. I'm sure they can decrease the lag in Nivla Woods some way, but it won't nearly be as effective as the first solution.

**Comment by Trixter313** [comment]
Also, turning your graphics to fast should help a lot. Many people lag when there are a lot of leaves present but fast makes leaves completely opaque and greatly reduces this lag.
