### ISSUE TITLE
I lost my stuff for no reason

### ISSUE THREAD

**Issue by TheBrianiacisawesome** [Wynncraft/Issues#4035]
When I logged back in to Wynncraft, My stuff disappeared completely. While I was at a Kingdom spawn. 
Even my legendaries and about three stacks of emeralds. :(. Even when I logged of alive, I returned with nothing but a Oak starter shear. I felt like I gave up on the server. I want my stuff back! Only the ones in my enderchest survived the loss. My username is The_Brianiac. I am level 23 assassin. Is there anyway to get my stuff back? Just askin.

**Comment by Moe-Ronickah** [comment]
I'm sorry to have to tell you this, but WynnCraft has a no-refund policy, and you aren't the first person that this has happened to.  It's a bug that the coders are working on.

**Comment by TheBrianiacisawesome** [comment]
I don't think someone would have access to my account. I'm sure of it.

**Comment by Trixter313** [comment]
Like mentioned above, we can't do anything about the already lost items and just to be safe, I'd reset my Minecraft and the associated email's passwords just in case it was hacked somehow. It can happen many ways and even if you're careful (fake websites, 3rd party launchers, etc.) Hopefully this doesn't happen again!
