### ISSUE TITLE
SilverFish 

### ISSUE THREAD

**Issue by ForcedToxin** [Wynncraft/Issues#4037]
The wire in the silverfish Dungeon after the parkour wont spawn. Please fix aswell as dieing and the items despawning.

**Comment by DarkDemonDragon** [comment]
There is a wire it's just that redstone on certain worlds are broken. Simply switch to another world and see if it works there.

**Comment by Trixter313** [comment]
Did switching solve your issue? Thanks!

**Comment by ForcedToxin** [comment]
Thanks and yes it did.

**Comment by Trixter313** [comment]
Glad to hear!
