### ISSUE TITLE
No exit pit on Maro Peaks

### ISSUE THREAD

**Issue by aramaril** [Wynncraft/Issues#4041]
I was on Maro Peaks at location 166, 14, -3967. there is no way out of this pit unless you an archer, possibly a wizard as well. the ladder just ends and leads to no exit whatsoever.

**Comment by DarkDemonDragon** [comment]
Please provide screenshots or a video to show why exiting is impossible.

**Comment by aramaril** [comment]
![noescape1](https://cloud.githubusercontent.com/assets/17123618/12947727/1f087138-cfc3-11e5-89b4-79c7b8d3b3b4.png)
![noescape2](https://cloud.githubusercontent.com/assets/17123618/12947730/1f09e130-cfc3-11e5-8def-5f4bd4b6c2e2.png)
![noescape3](https://cloud.githubusercontent.com/assets/17123618/12947728/1f085f4a-cfc3-11e5-945e-1823052c41b4.png)
![noescape4](https://cloud.githubusercontent.com/assets/17123618/12947729/1f08ae14-cfc3-11e5-9158-d1a8b7167cd0.png)
you cant see it fully but in picture two there is a 5 block minimum jump for a player to have to make just to get to the bottom of the ladder or the little ledge up above. I hope these screen grabs help otherwise the coordinates i gave above (166,14,-3967) are at the bottom of the hole. I'm not even sure what the point of having those ladders that far down in the first place even are. Likely just a world edit goof. either who hope this helps

**Comment by DarkDemonDragon** [comment]
Does that hole actually lead to anywhere or just a random hole, and does the ladder going up lead to an upper floor? I'm trying to see if this is just a hole that needs to be filled or if ladders need to be added.

**Comment by aramaril** [comment]
the hole leads to nothing its like a 3 block area of just rocks. the ladder looks like it was supposed to be attached to a barrier block or something but it dissipated and the 5 extra ladders vanished. either way filling in the hole or adding ladders would fix the problem. the ladder does lead up to a higher area but the bottom part of the scaffold or whatever this is supposed to be just kinda juts into the ground for no reason particular reason. its tunneling is actually kinda irritating if you want to just get down to the main floor.

**Comment by Villageacules** [comment]
Fixed, patch coming out in the follow up update.

**Comment by Moe-Ronickah** [comment]
See, above.
