### ISSUE TITLE
Silverfish dungeon 

### ISSUE THREAD

**Issue by 7asoOonyi14** [Wynncraft/Issues#4043]
i have said this before ..

so the issue is , when you pass the bridge of arrows , and then you walk on trap that opens the ground and let you fall in an room that has an button and door , when you click the button the pistons pull stairs and unleashes the silverfish on you , and you need to make your way to the door to complete this section-room !.

after Gavel update !
when you pass the arrow bridge and walk on the trap then you fall in the room , before you do ANYTHING , you just entered the room , not clicking the button , the silverfish just walks above the stairs that the pistons supposed to pull after clicking the button , but the silverfish just walk on it and fight you , that is totally an bug , silverfish are supposed to fight you after clicking the button so you need to hurry and go to the door , but now as i said before you do anything , the silverfish just walk gently above stair and follow you , i mean , i don't have an issue with that , i can kill them easily , but this isn't what is supposed to happen , so please fix it :)

**Comment by Moe-Ronickah** [comment]
Single incident glitch.  Tested on build server.
