### ISSUE TITLE
Site C Horrible Bug.

### ISSUE THREAD

**Issue by KeepoPrideHD** [Wynncraft/Issues#4045]
So, I thought I've completed WynnExcavation Site C... I was wrong. In my quest book I had "Report back to Excavator Placardus". That was supposed to end the quest. I talk to him... and then what appears is:
"The Purple Crystal Shard from WynnExcavation Site B is required to start this quest." What? I have 13 of these shards (because I spammed /fixquests) and I've been everywhere I should've been, completed everything I shouldhave completed. Also, look up to what was said. "Start". I have started this quest and I went through every stage, I had to report to Excavator Placardus and finish the quest and I couldn't... start it?...

**Comment by KeepoPrideHD** [comment]
Close it, it was some kind of a bug to which I waited for 2 hours, got back and everything worked fine.

**Comment by Trixter313** [comment]
Glad to hear it's fixed now =)
