### ISSUE TITLE
Cowfusion Stage 23 cutscene is not working

### ISSUE THREAD

**Issue by Moe-Ronickah** [Wynncraft/Issues#4051]
At the moment, the cutscene in the Cowfusion quest, the Stage immediately after exiting the tunnel, is not working.  You will get stuck in a 2x3 transparent box, from which the only way out is to use /kill.  The builders and GMs are aware of the problem, and are working to fix it.  I have no information on when this will be fixed, at this time.

**Comment by Trixter313** [comment]
Should be fixed now, according to https://forums.wynncraft.com/threads/gavel-patch-14-0-9.112397/
