### ISSUE TITLE
Character Bugg and i dont have any Scroll!

### ISSUE THREAD

**Issue by T3ktr0nix** [Wynncraft/Issues#4052]
My Archer is bugging inside the start screen... a black room (where you choose kit) And i cant get out of there... Please help..

**Comment by Dar-krusos** [comment]
Is this the same issue as #3250?

**Comment by nerohecklp** [comment]
i have the same problem!

**Comment by Gualdim-Pais** [comment]
Do /kill if you have more than 3 soul points
