### ISSUE TITLE
Ban Bug!

### ISSUE THREAD

**Issue by AlexomonHD** [Wynncraft/Issues#4054]
Hey,i have found a bug i have been baned from wynncraft because flying but i only buged in the air because my bad internet/ping and then i was baned i already post a Appeal but nobody reads it :( i hope u can help. (ingame:Alexomon mage lvl:47)

**Comment by Odnod** [comment]
That is not a bug. If you sent an appeal, I guarantee that it will have been read as long as you tagged the person who banned you.

**Comment by AlexomonHD** [comment]
Ok,and will i be unbanned?

**Comment by Moe-Ronickah** [comment]
Only the mod who banned you can answer that question.  If you were honest and explained what happened clearly, it can take from 1 to 5 days for the unban to usually occur.  If, however, the mod catches a player clearly flying, and that player is not honest, there is no chance for an unban to occur.  Sit tight, wait a few days.  If you don't hear back from the mod in 7 days, re-send your ban appeal.

**Comment by AlexomonHD** [comment]
But there was no mod there was only my friend and me so the server has ban me!

**Comment by Moe-Ronickah** [comment]
Are you sure, that when you try to logon, that the message does not say who the ban was made by?

**Comment by AlexomonHD** [comment]
There only is (@Acer) what do that mean?

**Comment by Moe-Ronickah** [comment]
It means that Acer was the mod who banned you.  You will need to write a ban appeal, and tag it to Acer.  Be sure to be honest.  There are instructions for writing an appeal, on the WynnCraft forums.  Good luck.

**Comment by Moe-Ronickah** [comment]
I finally located this, it's the official ban appeal guide.  Read it, and follow it.  It's the best to go.
https://forums.wynncraft.com/threads/%E2%9C%8E-appeal-submission-guide-%E2%9C%8E.89247/#post-989111
