### ISSUE TITLE
Wynncraft Excavation Site A

### ISSUE THREAD

**Issue by ricardoandren** [Wynncraft/Issues#4055]
Lol i got a problem same as the others and i do not know how to fix it:

I killed the pharao with low health and if i go to vade he says: Have you translated the text already?

**Comment by Odnod** [comment]
Try going back through the quest. Make sure to do everything the way it is meant to be done and avoid using spells like charge and teleport.

**Comment by ricardoandren** [comment]
Lol i said that i did it without using spells: I killed the witch and he
says: That i need to translate it? this is a bug see the bug reports on
github

2016-02-10 6:37 GMT+01:00 Odnod <notifications@github.com>:

**Comment by Dar-krusos** [comment]
Did you go talk to Tasha (don't remember her name) in this tent near the excavation site? You need to give a tablet to her, return to Vade, and then retrive the crystal.

If you've already done that, then it'd be a bug. I in ver encountered this problem post-Gavel, and I've done it twice post-Gavel.

**Comment by Rccoon** [comment]
i cant do the quest too
