### ISSUE TITLE
Forge Client

### ISSUE THREAD

**Issue by LordPhrozen** [Wynncraft/Issues#4057]
The most recent patch seems to have broken forge clients. Now, sure there are some negitive effects to forge clients. 

However, allowing us to use shaders however, is a rather large boon imo. 

Is this a bug, or was this change intentional?

**Comment by Trixter313** [comment]
I just logged in with forge and it worked perfectly fine for me. It's most likely just an issue for you. Could you give us some more information like what forge version you're using, what MC version, and a list of the mods you're using. Thanks!

**Comment by Trixter313** [comment]
I'm going to assume that the issue is now fixed due to no response. If anyone is still experiencing it, simply comment and I'll reopen the issue. Thanks!
