### ISSUE TITLE
Very strange merchant glitch.

### ISSUE THREAD

**Issue by talkingkittycat** [Wynncraft/Issues#4059]
Hello. Today i'm here to report a very strange merchant bug: My inventory seems to break when entering the GUI, most of them turn into code form, Some turn back to the old item system (Factory helmet and breathing helmet to be precise) And nothing even happens to the potions. 

Link to the glitch: https://embed.gyazo.com/7545772fa9d34dbeb114c4935cd7db84.gif

I thank you for reading and hope that this bug is patched soon,
-Kitty

**Comment by DarkDemonDragon** [comment]
So is entering the GUI changing the items? You didn't get a "before" look of the items in the gif and only the "after" part so wasn't sure what was the exact cause. Some additional info to provide:
- Was this permanent?
- Is this item-specific or all items? (I know you mentioned about pots not being affected, but does this mean all armor, weapons, etc. get affected?)
- What world were you in? 
- Does the problem still persist after relogging and switching worlds?

**Comment by talkingkittycat** [comment]
No, this was not permanent, they would revert back after 1-2 seconds after exiting the GUI.

From what I can tell, is kinda item specific, This revert to code form effects Non-quest items, while quest items were reverted to the old item system. This happened on world 15.

Yes, this still persists after Relogging.

**Comment by DarkDemonDragon** [comment]
I have confirmed this issue on world 1. Fortunately items will change back, but I noticed that my life/mana steal also stopped working. This was the first thing I did on the world, so not sure if this was just the world I was in being buggy or a side effect of this. I'll do some more testing around when I have time.

**Comment by ThunderRemix** [comment]
I can confirm that this is a thing, but I think this is useful in a way.

**Comment by Moe-Ronickah** [comment]
Useful or not, it is unintentional as far as I know.

**Comment by DarkDemonDragon** [comment]
Why would this be useful? The items remain like this for a few seconds after exiting the GUI. This could be very troublesome. Say a person has:
Default: 15 INT
Item Req: 20 INT
Bonus from other items: +5 INT

If the items register improperly the item with the 20 INT Req will be taken off. Currently there is a bug where items that should be dropped from your Inventory are instead removed. So if your inventory is full and you use a skill reset scroll (or anything else that modifies your skill points) then all your armor and accessories will vanish. Considering that this already happens by random chance when spawning in, I'd rather they try to fix this just in case before things get too problematic.

**Comment by Moe-Ronickah** [comment]
This is known to the admins, and on the to-do list.

**Comment by Moe-Ronickah** [comment]
Fixed.
