### ISSUE TITLE
Holy Blast being able to Remove Lighting

### ISSUE THREAD

**Issue by True-Rikio** [Wynncraft/Issues#4060]
This happened by accident in the Temple of Legends. I used Holy Blast near the lights (Glowstone behind fences) and the light disappeared when a piece of the Glowstone from Holy Blast spawned in there. So basically, the Glowstone from Holy Blast took the light with it. Now the light is gone on that certain server.

**Comment by DarkDemonDragon** [comment]
Which class uses Holy Blast again? I'm not a donor so I don't know all the moves.

**Comment by Odnod** [comment]
@DarkDemonDragon Knight as a replacement for Bash

**Comment by DarkDemonDragon** [comment]
Thanks and that's pretty strange... mind giving screenshots and mentioning what world this happens on? Also were there any NPCs/Mobs nearby or no?

**Comment by True-Rikio** [comment]
Actually, the lights came back after a short while, as if the world regens in case someone breaks it.
