### ISSUE TITLE
Potion nametags being weird again

### ISSUE THREAD

**Issue by TrashcanMan** [Wynncraft/Issues#4061]
So a month or so back I posted issue #3263 about potion nametags glitching out when you opened a shop window, then closed it after it ended up being fixed. Now it's happening again, though the potions glitch to a code-style nametag instead of reverting to the pre-Gavel nametags.
![2016-02-08_20 57 44](https://cloud.githubusercontent.com/assets/6947594/12938203/5cff9eac-cf65-11e5-9db1-96d4b3bdb399.png)

**Comment by DarkDemonDragon** [comment]
May or may not be related to #4059

**Comment by Trixter313** [comment]
Is this still occurring?

**Comment by TrashcanMan** [comment]
Nope, closing the issue now.
