### ISSUE TITLE
Wynncraft pack Issues

### ISSUE THREAD

**Issue by firedragon2wsx** [Wynncraft/Issues#4062]
When I load the pack I'm at 1-2 fps and without the pack I have 200-230. Pls help 

With other 3D packs I have 190-215 fps 

I get around 60 fps when I'm not moving/moving my mouse but when I move my fps drop to 1-2 fps

**Comment by TrashcanMan** [comment]
That's odd, it's a 16x16 pack so it shouldn't cause any framerate issues. Try using the pack on a singleplayer world or a different server and see if the framerate still drops.

**Comment by firedragon2wsx** [comment]
Something's really weird... When I use it in the Minecraft main menu, my game is still at 1-2 fps

**Comment by firedragon2wsx** [comment]
Maybe it's because I'm on Windows 10....

**Comment by TrashcanMan** [comment]
I'm on Windows 10 as well and I'm having no problems.

**Comment by firedragon2wsx** [comment]
Hmm

**Comment by firedragon2wsx** [comment]
Is there a 2d pack that I can use ?

**Comment by TrashcanMan** [comment]
Unfortunately not at the moment. You could try playing with the default pack but then all the weapons would be stairs and bricks and stuff, and it would be very confusing.

**Comment by Dar-krusos** [comment]
Minecraft framerates do tend to drop when using the pack + the new Minecraft launcher. If you don't already have it, download the java launcher [here](https://s3.amazonaws.com/Minecraft.Download/launcher/Minecraft.jar).

**Comment by firedragon2wsx** [comment]
Ok thx for all the tips

**Comment by firedragon2wsx** [comment]
And btw I have to wait until all the chunks around me load to be able to move without lagging and as soon as I move, I starts lagging again.

**Comment by Moe-Ronickah** [comment]
Have you updated your video driver recently, and is it correctly installed?

**Comment by Moe-Ronickah** [comment]
We will close this issue in 5 days if we do not hear back from you.
