### ISSUE TITLE
Buggin in a wall

### ISSUE THREAD

**Issue by Explaysive** [Wynncraft/Issues#4063]
When I insert my caracter into a bed and got up then my caracter was buggin in a wall.

Please Help
Explaysive

**Comment by Odnod** [comment]
Do /kill, but only if you have 3 or more soul points.

**Comment by Explaysive** [comment]
Ok thank you!

**Comment by Moe-Ronickah** [comment]
Duplicate of #88
Please read this guide on the first page of the WynnCraft Wiki: https://forums.wynncraft.com/threads/are-you-stuck.89123/
Thanks!
