### ISSUE TITLE
Possible glitch/connection issues

### ISSUE THREAD

**Issue by flossy6701** [Wynncraft/Issues#4064]
Basically for the past couple of days I've been trying to play on the Wynncraft server.  I can login in just fine but as soon as I enter a world and click on my profile my screen goes black and I can't see or do anything.  My health, stamina and tool bar appear and I can still see players messages, but everything else is black.  I'm not sure if this is a glitch or just connection issues but if someone could please help me it would be appreciated.

**Comment by Odnod** [comment]
Try typing /kill or contact a moderator. A mod called RaphusCucullatus is probably on right now and can get you out.

**Comment by flossy6701** [comment]
Thank you so much the /kill command worked.
