### ISSUE TITLE
Questitem-Bug

### ISSUE THREAD

**Issue by LetsPlayAlex** [Wynncraft/Issues#4067]
Hello.
I have a bug with the Quest Items "Yellow Crystal Shard","Purple Crystal Shard" and Healing Water.
I have the Items in the inventory but i have finished all these Quests and i cannot drop the items. I need help because my inventory has 3 places fewer. I hope a Staff can help me with my problem.

~Alexander

**Comment by Odnod** [comment]
The issue is that all three items will be used in the quest: WynnExcavation Site 'D.' At which time they will be taken from your inventory. 

The quest is for level 70, and is notorious for having a very difficult boss fight. I recommend you bring some higher-leveled people with you when you do it.

**Comment by LetsPlayAlex** [comment]
I'm Level 73 and have finished the Questline of Wynnexcavation. I got the items as i joined on the server. And yes the Boss is very hard, i have killed the Sorrupted and Shadow Amadel solo, but by the Final formed Amadel, i killed him with a friend. And this was this morning.

**Comment by DarkDemonDragon** [comment]
@Odnod not healing water. @LetsPlayAlex if you wish to remove a quest item follow these instructions:
1) Wait for your daily chest
2) Open Daily Chest with Quest items in inventory
3) Drag Quest items into the Chest GUI
4) Close chest
5) Quest items gone

**Comment by Odnod** [comment]
@DarkDemonDragon
Easier way :3
Maintaining a full inventory, put your unwanted items in your bank and drop them.

/fixquests to get them back

**Comment by DarkDemonDragon** [comment]
It's annoying to explain the full inventory technique because people don't understand it at first usually.

**Comment by LetsPlayAlex** [comment]
Thanks for the Help! It worked! <3

~Alexander
