### ISSUE TITLE
The Maiden Tower - Stage 4

### ISSUE THREAD

**Issue by Gargarath** [Wynncraft/Issues#4068]
Hello, I've got a problem during The Maiden Tower quest. In fact Stage 4 do not launch. I've just get the "Black veil" in Olux but when I want to enter into the tower "Erlard" say that I need to aquire the veil buried in the catacombs of Olux. That my only one possible quest with "Tower of Amnesia" so I need quick help. Thanks for reading, Gargarath87

**Comment by Odnod** [comment]
But the veil on, then enter the tower. If that does not work, retrace your steps in the quest and make sure to not pass over any potential triggers for the questbook to update.

**Comment by Gargarath** [comment]
Ok thank you :)
