### ISSUE TITLE
My weapon is bugged!

### ISSUE THREAD

**Issue by Furious12** [Wynncraft/Issues#4069]
I have an "Fierte" wich is legendary, and the wynncraft changed everything. I have to identify all my stuff but my Fierte still the same, the old Fierte and i cant identify and i cant use it. http://prntscr.com/a1hazn

**Comment by Odnod** [comment]
Yeah they are fixing those.

**Comment by DarkDemonDragon** [comment]
The moment all items with special characters are broken.

**Comment by Moe-Ronickah** [comment]
Duplicate of #2679 
It's a known issue.  If you want to make any further comments, please post on the original thread.  Thanks!

**Comment by DarkDemonDragon** [comment]
@Moe-Ronickah actually this is a duplicate of #3161 as the one you're referring to was closed by Tama's mass clean up after the Gavel Wave of issues.
