### ISSUE TITLE
Teleport doesn't work

### ISSUE THREAD

**Issue by IIChocotacoII** [Wynncraft/Issues#4070]
Me and my friend were dueling and we kept teleporting into each other but it wasnt damaging us. We tried it with other people and the same bug happened. Hope you can fix it as soon as possible and thank you for your hard **work** on Gavel

**Comment by DarkDemonDragon** [comment]
Is this issue still persisting? If not please close this.

**Comment by Moe-Ronickah** [comment]
Two months with no further responses.  Good night, sweet issue.
