### ISSUE TITLE
Skin Drawing Bug

### ISSUE THREAD

**Issue by BlahBlah161616** [Wynncraft/Issues#4071]
My champion helmet took half an hour to draw(not the issue) maybe longer, and then when it finally drew to my skin, the game started glitching and adding my armor from other classes to my skin, redrawing it and adding it to my skin, and kicking me off my horse to draw it to my skin. This is an issue because when it draws my skin so often, it gets spammy, annoying, and deadly. If it could just add it to my skin once, it would be awesome.

**Comment by DarkDemonDragon** [comment]
Hmm if you really want to have the armor skins on then I suggest making sure that your Minecraft launcher is the latest one and checking your skin settings. However, if you rather not deal with skins at all or don't care whether you have the armor on your skin or not then simply do /toggle armor and this will disable armor skins for one session.

**Comment by BlahBlah161616** [comment]
My settings are fine and my launcher is up to date.

**Comment by Moe-Ronickah** [comment]
BlahBlah, are you still having this same issue occur, or is it resolved?  If it's resolved, is it something that you changed, and if so, what did you change?  I'd like to narrow this down as to whether it was a problem on your computer, your connection to the game, or in the game, itself.

**Comment by BlahBlah161616** [comment]
I'll check this weekend if it's still a bug.
