### ISSUE TITLE
Skin issue

### ISSUE THREAD

**Issue by BluKukki277** [Wynncraft/Issues#4075]
I don't know if this is a bug, but my skin won't load, and it's only mine. Proof will be provided below

 Broken skin: [https://gyazo.com/f6318cf7134d418e4e15cec84f0c0551](url)

**Comment by Odnod** [comment]
try typing /armor

**Comment by BluKukki277** [comment]
Thank you!

**Comment by Trixter313** [comment]
Did that fix your issue? If so, please close this issue. Thanks!
