### ISSUE TITLE
Skin was drawn, lost stuff

### ISSUE THREAD

**Issue by xApX3** [Wynncraft/Issues#4076]
Hi, So my skin updated for no reason and i had a full inventory so my hat, chest plate and pants came off though i didnt touch them and they just disappeared, this is the second it has happened to me when i was wearing my full set of ghostly armor. I lost Venision, Dravarden, and Frosted Leggings. 
![2016-02-10_21 13 40](https://cloud.githubusercontent.com/assets/17170811/12968227/0aac10da-d03d-11e5-88ac-cc7a191f945a.png)

**Comment by Odnod** [comment]
this likely happened due to you switching some gear or weapon and losing the skillpoints required to use those pieces of armor. However wynncraft has a no-refund policy, so you will not be able to get back your items without buying them or finding them again.

**Comment by xApX3** [comment]
The only thing is this is the Second time its happened and to me and same items. like helmet chest and legs. My skill points are all the requirements and the i didn't touch anything. i was walking and it just randomly did it

**Comment by Odnod** [comment]
well, I have a spare venison that I could give you. Otherwise just don't keep all of that random stuff in your inventory. The 60 emerald blocks and all of those scrolls are completely unnecessary.

**Comment by xApX3** [comment]
that would be very helpful thank you. im in w2 in troms and ill give you some blocks

**Comment by DarkDemonDragon** [comment]
You should NEVER have a full inventory when moving armor around. If armor pops off and you have a full inventory the game will delete it instead of dropping it now. I've lost a couple legendaries that I didn't have the skill points for like this in the past.

**Comment by xApX3** [comment]
I was walking to the item buyer to sell my stuff and I never touched my armor I was just walking and it just updated my skin on its own randomly

**Comment by xApX3** [comment]
The need to remove the skins because everyone has the same problem just leave it as basic armor like we don't need the skins it's too glitchy

**Comment by DarkDemonDragon** [comment]
To turn off armor skins do /toggle armor and armor will be off for 1 session.
