### ISSUE TITLE
Stuck in a wall

### ISSUE THREAD

**Issue by WhatTheWessel** [Wynncraft/Issues#4077]
Hello,
I was playing the wynncraft excavation B quest when I was teleported after having picked up pieces of the crystal. When I teleported I accidently used my charge (warrior) spell. Now I'm stuck in a wall and I can't teleport anywhere or get out. Please help me.
gamename: whatthewessel

**Comment by Odnod** [comment]
Do /kill with 3 or more soul points

**Comment by TheCrafterMiner** [comment]
Thank you odnod!

**Comment by TheCrafterMiner** [comment]
That happened to me. Thanks! ;)
