### ISSUE TITLE
Stuck in Class box, but can do commands and walk

### ISSUE THREAD

**Issue by RandomInThree** [Wynncraft/Issues#4078]
It all started just yesterday around 10-12 (pacific time), I log on to Wynncraft wanting to start some missions after doing research (I forget the plots easily so no worries) when after choosing my higher class I'm stuck in a large black box where sometimes players come out of no where telling me that this is the "class selection box" and that this usually happens. After that small chitchat they just vanish and Im stuck in the box. My skin loads w/ armor, I can do /class, I can even use my combos. I tried relogging, deleting the server ip and then adding it back, calling out for help. But for some odd reason, my second class seems to be working and all that stuff. Does the server have a limit on when you need to stop being on your first class and start playing on your second class? Or no??

**Comment by DarkDemonDragon** [comment]
It's an occasional glitch that happens to players when their class gets stuck in the class selection box due to lag of some sort. Simply use a teleport scroll or /kill to get out.

**Comment by RandomInThree** [comment]
ah okie, teleport scroll cannot due but I can try the /kill.....thankies!
