### ISSUE TITLE
no lobbys are open

### ISSUE THREAD

**Issue by Rccoon** [Wynncraft/Issues#4080]
i cant play because there is not lobby that is open

**Comment by Odnod** [comment]
Could you give us more information or screenshots?

**Comment by Rccoon** [comment]
the proplem is fixed
when i was in the server there was only 1 lobby

**Comment by Odnod** [comment]
Ok :) if it is fixed you should close the issue.

**Comment by peter13212** [comment]
i had this issue all i did was go to nether fighting area and back to lobby and it was fixed
