### ISSUE TITLE
Keep falling in the void and can't use commands

### ISSUE THREAD

**Issue by RiesvGeffen** [Wynncraft/Issues#4085]
I basicly keep falling deeper and deeper in the void and I can't use any commands. So the only way to get out of here is by teleporting me on the ground! please help me! And fix this bug so noone gets it.

**Comment by Odnod** [comment]
I am familiar with this bug, I do not know the exact cause but I think it happens when the server has no idea where to spawn you. It has occurred for me and I was able log into the nether and create a new class in order to fix it. No promises whether or not it work work for you though.

**Comment by DarkDemonDragon** [comment]
Duplicate of #3785 Please close this and post any further comments in the original

**Comment by TimThePvpMaster** [comment]
Tried to go to the nether, wouldn't let me in. I am having this same problem.

**Comment by TimThePvpMaster** [comment]
Alright, I got inside the nether, toggled the autojoin, and yet it still puts me in the box.... UGH.
