### ISSUE TITLE
Canyon Condor quest doesn't work

### ISSUE THREAD

**Issue by Endertricity** [Wynncraft/Issues#4086]
I got 10 gold bars for a part of the Canyon Condor quest. The guy isn't collecting them!
![screen shot 2016-02-11 at 4 39 51 pm](https://cloud.githubusercontent.com/assets/17186189/12991703/642820bc-d0de-11e5-98e6-ec2cff429088.png)

**Comment by Odnod** [comment]
Try going back a little ways down the cave. Be sure to not use escape, as it can launch you over triggers for the quest to progress. You could also try going to another server and talking to Jankan.

**Comment by Endertricity** [comment]
Tried changing servers, but not the cave

**Comment by TrashcanMan** [comment]
Are you sure they're the right gold bars? There are two types: one is dropped from the zombies nearby, and the other is found at the end of a cave full of TNT. You should have the ones from the cave.

**Comment by Endertricity** [comment]
I killed the dead prospectors

**Comment by Endertricity** [comment]
fixed, resolved

**Comment by TrashcanMan** [comment]
If your issue is resolved please hit the "Close Issue" button at the bottom. Thanks!
