### ISSUE TITLE
armour glitch way diffrent please fix

### ISSUE THREAD

**Issue by ninjamaster330** [Wynncraft/Issues#4088]
ok so every time I put on armor my armor makes my skin go back to my old skin ok now I editited this anddddd it got used to it but my armor wont load just my regular now skin
I did /armor and redid it but it didn't work

**Comment by Odnod** [comment]
just wait a while, eventually it will fix to your new skin.

**Comment by DarkDemonDragon** [comment]
Remember that if the armor doesn't look like it's applied, it's stats are still in effect.
