### ISSUE TITLE
hourses

### ISSUE THREAD

**Issue by Rccoon** [Wynncraft/Issues#4092]
i looked in youtube how to get black horse
i got two brown horses and i puted them in the crafting in my inventory
and i got brown hores!

**Comment by Strabismuss** [comment]
There is only a chance for you to get a Black Horse, it is not guaranteed

**Comment by Rccoon** [comment]
why?

**Comment by Dar-krusos** [comment]
Because it would be too easy to get a White horse, let alone a Black. You won't see it now, but Brown horses are very cheap in the eyes of the community. Black horses are cheap as well; it's only when you get to Chestnuts (Horse tier after Black) that the pricr becomes moderately high.
