### ISSUE TITLE
Lost 3 of 4 of my nether armor after joining after a long time.

### ISSUE THREAD

**Issue by Spookki** [Wynncraft/Issues#4094]
I had a full set of nether armor on from a long time ago and i joined this server. i was in the update room and decided to indetify my best armorset (nether armor) it then unequipped my armor and because i only had 2 slots in my inventory it gave me the hat and the tunic. the other 2 were gone.
then i identifyied my hat and it dissapeared. then i identified my tunic witch didn't dissapear. i got it as an identified item. so i just lost a really expensive armorset because im guessing i used old emeralds.

**Comment by Odnod** [comment]
Nether armor isn't expensive anymore as it can now be dropped from mobs, and the reason your armor got deleted is because you did not have enough inventory slots. The hat likely got put on top of the tent because the Identifier does that when you don't have enough slots.

**Comment by Spookki** [comment]
still i'd like it back somehow. any idea where mobs drop it?

**Comment by Odnod** [comment]
The blazes by the nether entrance drop it I think.
