### ISSUE TITLE
Abilities not working

### ISSUE THREAD

**Issue by Zeroid37** [Wynncraft/Issues#4095]
So,  I haven't played Wynncraft in like, 6 months or more, but when I logged in on my level 46 mage, it's abilites does not work. Every other character I've made works. 

Please help

Best regards, -Zeroid

Update: 3/4 of my armor I have equipped is "unindentified" but still gives me up to 1700 HP. Too scared to take it off, since I probably wont be able to put it on again

Update: Took them off, cant equip them and cant still do spells

**Comment by Odnod** [comment]
Identify your armor and wand

**Comment by Zeroid37** [comment]
The wand I am using is already identified. I took off all the unidentified stuff and equipped some else, still doesn't work

**Comment by Zeroid37** [comment]
Alright, so I bought a new wand (Level 1) and it seems to work with that wand, not with my other one for some reason. Anyhow, it works now, woo
