### ISSUE TITLE
chrashes

### ISSUE THREAD

**Issue by ninjamaster330** [Wynncraft/Issues#4096]
my game crashes several times and my armor doesn't load

**Comment by Trixter313** [comment]
Could you give us some more information like what MC version you're using, where you character is, etc? Thanks!

**Comment by ninjamaster330** [comment]
I use 1.8.9

**Comment by ninjamaster330** [comment]
and what do you mean where is your character?

**Comment by Trixter313** [comment]
Where is the class that you are trying to login as? Could you give us coords or some nearby landmarks? Thanks!

**Comment by ninjamaster330** [comment]
I tried all the classes

**Comment by ninjamaster330** [comment]
its at ragni

**Comment by Trixter313** [comment]
Hmm, could you paste the crash log on a website such as http://pastebin.com/ and post the link here? That might help us determine the problem. I'm not the best at reading crash logs but it could help. Thank you!

**Comment by ninjamaster330** [comment]
ok

**Comment by Moe-Ronickah** [comment]
Just a reminder, ninjamaster, if this is still going on, would you post a crash log, please?  And if it's fixed, would you close this issue?  Thanks, in advance.

**Comment by DarkDemonDragon** [comment]
@ninjamaster330 please respond if this issue is still bothering you, so that we can remedy it. If the issue is not longer persisting please close this.
