### ISSUE TITLE
Im stuck in a wall

### ISSUE THREAD

**Issue by TheCrafterMiner** [Wynncraft/Issues#4098]
I was doing the angry village quest in my mage class, and I was at the lava parkour, so I tryed teleporting myself to the end, but it teleported me straight into a wall and now I cant move. Please help! D:

**Comment by TheCrafterMiner** [comment]
I've tried using my teleportation scroll, but it doesn't work for some reason.

**Comment by Trixter313** [comment]
Typing /kill should fix your issue.

**Comment by TheCrafterMiner** [comment]
Thanks!

**Comment by TheCrafterMiner** [comment]
;)
