### ISSUE TITLE
Guild issue

### ISSUE THREAD

**Issue by darkovic** [Wynncraft/Issues#4100]
So I have a problem with my guild... It was a pre-gavel guild with only 8 or so members. I cant add more people, it says there are members in that even if I kick stay and our guild on the leader board apparently has no name or tag... Is there anything that can be done? Thanks in advance

**Comment by DarkDemonDragon** [comment]
Please provide more details. What happens when you try to add more people? Note that guilds have a max player limit depending on what level the guild is so the guild just might be full.

**Comment by DarkDemonDragon** [comment]
Is this issue still persisting?

**Comment by Trixter313** [comment]
Closing due to no response.
