### ISSUE TITLE
Lost My Pants

### ISSUE THREAD

**Issue by CorruptNitro** [Wynncraft/Issues#4101]
I took off my blue mask and in return it took off my pants(crystal) and since me invo was full i lost the pants. I am asking to get my pants back and make it so if your invo is full the items should drop to the ground. I payed to get crystal and now im a bit salty since i lost them .-.

**Comment by CorruptNitro** [comment]
I decided to buy new ones but fix the bug

**Comment by TrashcanMan** [comment]
Unfortunately Wynncraft has a no-refunds policy so you can't get your pants back. I think this issue has been reported already, and should be fixed soon. In the meantime, be more careful when doing stuff like this in the future.

**Comment by CorruptNitro** [comment]
Alright

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3153

Please direct any future comments to the original thread. Thanks!
