### ISSUE TITLE
Lazarus Pit quest glitched!

### ISSUE THREAD

**Issue by chuckthemage** [Wynncraft/Issues#4102]
I was doing the Lazarus Pit quest and at the very end when I gave Burtur the [Healing Water] nothing happened, no quest completion no xp and he acts as if I just started the quest telling me to go to the grave where the cords are. I tried doing the quest again but its like I did all the parts already and I can no longer get the [Healing Water] from Sesad in the pit. Please help me!

Minecraft Name: Chuckthemage

**Comment by Trixter313** [comment]
Try typing /fixquests and see if that helps at all.

**Comment by Dar-krusos** [comment]
What is your IGN? I may be able to help you in-game.

**Comment by DarkDemonDragon** [comment]
Is this bug still persisting for you?

**Comment by Trixter313** [comment]
Closing due to no response.
