### ISSUE TITLE
Water Bottles Are Not Drinkable

### ISSUE THREAD

**Issue by xXK1NGxR3APERXx** [Wynncraft/Issues#4105]
As the title says, I'm doing the green gloop quest and I'm getting the water bottles from the spider drops and the water bottles are not drinkable.

**Comment by DarkDemonDragon** [comment]
Bottles aren't meant to be obtained from drinking something. Mobs will randomly drop empty bottles.

**Comment by Trixter313** [comment]
Especially the mobs around Ragni will drop them.
