### ISSUE TITLE
low level Mobdrop bug

### ISSUE THREAD

**Issue by HeyloLP** [Wynncraft/Issues#4106]
Right now it is unable for high levels to get drops for high levels, so if you want to do the Bob's lost soul quest you need a low level class to get the Items. Because of that it is impossible for Players who don't have a class slot left.

**Comment by Odnod** [comment]
It is not impossible, it just takes a long time.

**Comment by DarkDemonDragon** [comment]
Another option is to just buy the drops from other players. There are plenty of players that sell Depressing items.

**Comment by HeyloLP** [comment]
No you don't get my point i farmed with my lvl 45 Dark Wizzard and got nothing but a few emeralds i wouldn't got any weapon (normal,depressing...) if i wouldn't used my lvl 9 Ninja and i tryed with the Wizzard 4h

**Comment by DarkDemonDragon** [comment]
@HeyloLP Check your loot bonus. Also, I don't think level affects things too much. A lv 80 can still get a lv 20 drop from lv 25 mobs, so just try to raise your loot bonus as depressing items have a relatively low drop rate.

**Comment by HeyloLP** [comment]
my ninja got +5 loot bonus (to farm depr. items took 20min0)
and my dark wizzard got a loot bonus from + 23 (after 4h i switched to the ninja)

**Comment by DarkDemonDragon** [comment]
If your issue is resolved now please close this. If you have any further problems related to this feel free to ask.

**Comment by Moe-Ronickah** [comment]
This is not an issue, it is an intentional game mechanic implemented with the Gavel update.  Mob drops are based upon the player's level and a probability factor.
