### ISSUE TITLE
Cowfusion

### ISSUE THREAD

**Issue by ThatChudley** [Wynncraft/Issues#4108]
Due to a glitch, I am unable to complete the quest Cowfusion.  I have used /kill and retried it 6 times, so please can a moderator reset the quest for me?

**Comment by Trixter313** [comment]
Could you provide more information so we can properly help you? There is currently no way for quests to be reset by anyone. You could try the command /fixquests and see if it helps. Thanks!

**Comment by Odnod** [comment]
Cowfusion is currently broken, unfortunately.

**Comment by Dar-krusos** [comment]
What part of the quest is this?

**Comment by Trixter313** [comment]
According to https://forums.wynncraft.com/threads/gavel-patch-14-0-9.112397/ this should be fixed now.
