### ISSUE TITLE
Lost "the Mummy's Rag (bound)" in armour drawing glitch

### ISSUE THREAD

**Issue by Moderocky** [Wynncraft/Issues#4109]
I sold my Almuj's walker to somebody for 2LE.
I went to Deltas and I was switching around my armour to try and find a good combo and then the armour drawing kicked me and I had to log back in with "Internal Error". I had an empty chest plate slot and no "the mummy's rag" which is a quest reward and can't be traded.

I want my chest plate back

**Comment by Moderocky** [comment]
And just lost another set of armour because it unequipped it while I was switching my rings and my stats dropped ;-;

I think I'm just gonna quit I feel like somebody is trying to ruin my game.

**Comment by Trixter313** [comment]
If you have a full inventory there is a chance of items getting deleted if they pop off of your player and there isn't anywhere for them to go. You can try to get the chestplate back by using the command /fixquests but it might not work for that specific item. You could also do the quest again on another class to get another chestplate. Wynncraft has a strict no refunds policy so besides that there's nothing else we can do. Hopefully this isn't too much of an inconvenience.

**Comment by Moderocky** [comment]
Actually it is quite an inconvenience as it's an 'untradeable' item. I think I'm going to quit wynncraft until the skin drawing thing is removed, it's caused me so many problems and frankly it looks awful.

Until next time.

**Comment by Trixter313** [comment]
You can also do the command /armors and it will disable armor skins but I believe this lasts for only one session so you'd have to retype the command whenever you log out and back in, but it is an option.
