### ISSUE TITLE
Quest "Shattered Minds" Not Working

### ISSUE THREAD

**Issue by TheDnl** [Wynncraft/Issues#4110]
I've been trying to do the shattered minds quest, but I'm very sure I broke it or came across a bug, and thus this has happened:
![2016-02-13_18 28 47](https://cloud.githubusercontent.com/assets/17219347/13028429/d31701b2-d27f-11e5-864c-d95573369d43.png)
For clarification, I somehow broke the quest in a way where the NPC dialogue shows text for the next part of the quest, but the textbook wont update at all. I'm very very sure this is the part of the quest I'm meant to be at; I've checked countless walkthroughs and referenced the wiki several times.

**Comment by TheDnl** [comment]
I can't progress in this quest either:
![2016-02-13_18 32 21](https://cloud.githubusercontent.com/assets/17219347/13028444/2a663b86-d280-11e5-8a1b-4e4b4d3854e4.png)

**Comment by Trixter313** [comment]
Try using the command /fixquests and see if it returns any items you might need for this quest.

**Comment by Dar-krusos** [comment]
What is your IGN? You may have missed something, but either way, I can come on to help you if I can.

**Comment by Thegamerplus1** [comment]
same problem here

**Comment by Thegamerplus1** [comment]
oh


The shroom's in my bank

**Comment by Moe-Ronickah** [comment]
No comment.
