### ISSUE TITLE
Chained Pixels doesn't equip

### ISSUE THREAD

**Issue by Zeiph** [Wynncraft/Issues#4111]
Hello there ! For some reason, when I tried to equip my Chained Pixels, it put a message in the chat (the " We're drawing [...] " but, even after a few minutes, nothing happened.
So, I tried to re-equip the leggings I had, and...
It worked. It only took a few seconds.

Could you help me ? Thanks very much !

**Comment by Trixter313** [comment]
What version of MC are you using? Also, have you tried putting the pants on then logging out and back in?

**Comment by RedMorcus** [comment]
You still get the buffs from the armor, don't worry about that. It's just the armor skin not working, therefore they should still be usable.

**Comment by Zeiph** [comment]
It finally worked. I restarted Minecraft several times, and eventually, it did it. I have absolutely no clue why, but hey, 'won't complain !
Thx for the help guys !
