### ISSUE TITLE
Armor Skins Bug

### ISSUE THREAD

**Issue by BlahBlah161616** [Wynncraft/Issues#4114]
I have noticed that sometimes when I switch classes, my armor skins stay the same OR, after they equip, they add the ones from the class previously used a second time. So basically, I would be wearing my armor on my level 81, and out of nowhere my armor would be added to my skin again, and my armor would be the same on my level 11. This causes deaths too, because when the armor adds, it makes you slow. So if you're fighting something fast, you'll be killed by the mobs.

**Comment by DarkDemonDragon** [comment]
If you don't want to deal with the lag with the armor skins and don't mind being in your own skin then do /toggle armor. This will disable armor for 1 session.

**Comment by BlahBlah161616** [comment]
It's not the lag, it's the fact it gets added every 5 seconds.

**Comment by DarkDemonDragon** [comment]
Well that's what lag is. A difference in timing between the initiation of an action and the execution of the action. So if armor application was lagless it would instantly apply. If it has lag then it takes some time for it to apply. Therefore you have a 5 second lag for armor application. Again if this hinders your gameplay simple toggle armor off with /toggle armor.

**Comment by Moe-Ronickah** [comment]
BlahBlah161616, is this fixed?

**Comment by BlahBlah161616** [comment]
Well, considering they removed armor skins for the time being, I should close the issue.
