### ISSUE TITLE
Armor skin bugged

### ISSUE THREAD

**Issue by MerlinDHF** [Wynncraft/Issues#4117]
I just changed my mc skin and my wynncraft skin with armor was still my old skin. when i unequipped everything it turned into my new skin but if i equipped other armor it changed into my last equipped armor with the old skin or it didn't change at all. when i selected a different class my skin changed into the steve skin whithout any armour but I had armor equipped. after that it remained steve whithout any armor.

**Comment by Trixter313** [comment]
It just takes time to update. If it still hasn't updated after 2 days report back here.

**Comment by Dar-krusos** [comment]
This is an old problem that has stuck around since 2014. It just takes some time (sometimes a week or more) before it updates, so just wait a while :)
