### ISSUE TITLE
IM STUCK Silverfish Dungeon

### ISSUE THREAD

**Issue by Endertricity** [Wynncraft/Issues#4121]
I was going through the silverfish dungeon, and after putting the emeralds in the snakes, I walked through the doorway. I'm not sure what happened - maybe the doorways closed - but I was teleported into the floor, and I can't get out (I don't have any TP scrolls on me)

![screen shot 2016-02-13 at 4 52 56 pm](https://cloud.githubusercontent.com/assets/17186189/13030277/e9fe8240-d272-11e5-8e1c-ddf9f8b8e96b.png)

**Comment by Odnod** [comment]
Type /kill with 3 or more soul points

**Comment by Endertricity** [comment]
Well then, Wynncraft owes me a silverfish key and a bug fix

**Comment by Odnod** [comment]
It isn't really a bug, just walking into pistons closing at the wrong time. Also wynncraft has a no-refund policy.

**Comment by Ponkky** [comment]
the thing is that you don´t want to pay 4 more blocks of emeralds to get in

**Comment by Endertricity** [comment]
Well, yea. 4 blocks of emeralds still takes a while to get
