### ISSUE TITLE
Lava Cow Escapes

### ISSUE THREAD

**Issue by Endertricity** [Wynncraft/Issues#4122]
Lava cow managed to get out at  animal dungeon. We can't hit him

![screen shot 2016-02-13 at 1 16 44 pm](https://cloud.githubusercontent.com/assets/17186189/13030281/1dac8e52-d273-11e5-9bbc-dbd1b79b2f07.png)

**Comment by Odnod** [comment]
This probably happened because arrow storm and war scream can knock enenies through walls. Use assassin spin attack to get them back in or have everyone type /class to reset the fight.
