### ISSUE TITLE
I CAN NOT LOG INTO THE SERVER (HELP) :/

### ISSUE THREAD

**Issue by HamburguerFriboi** [Wynncraft/Issues#4124]
After upgrading Valentine, I can not login server, I tried and tried, but could not. need help :(

![2016-02-13_21 08 06](https://cloud.githubusercontent.com/assets/17225744/13030562/224b2a90-d296-11e5-8f6a-ff99b610b31f.png)

I logged on account of my friend and was not giving this message :/

**Comment by JKvn** [comment]
Hahah tbm estou assim, se fodemos kkk

**Comment by Odnod** [comment]
Try restarting minecraft

**Comment by JKvn** [comment]
It also does not work

**Comment by HamburguerFriboi** [comment]
It also does not work :/

**Comment by Moe-Ronickah** [comment]
Transient connection issue
