### ISSUE TITLE
Ethereal natural damage

### ISSUE THREAD

**Issue by dltkdwns** [Wynncraft/Issues#4126]
My ethereal deals 0 natural damage although i don have any negative spell dmg
![mage monster](https://cloud.githubusercontent.com/assets/17229985/13033666/8042d6b6-d345-11e5-9831-1bdb5582486b.PNG)

![mage](https://cloud.githubusercontent.com/assets/17229985/13033701/9755e414-d346-11e5-9402-064d4d653d07.PNG)

**Comment by TrashcanMan** [comment]
Are you casting spells? There's this bug where neutral damage doesn't apply when spellcasting, though I can't find the issue number.

**Comment by DarkDemonDragon** [comment]
@TrashcanMan actually someone reported this on the forums. I think this is the first time someone reported it on Github.

**Comment by dltkdwns** [comment]
@TrashcanMan  Is that going to be fixed in the next patch?

**Comment by TrashcanMan** [comment]
No idea when this is going to be fixed, hopefully soon though

**Comment by RedMorcus** [comment]
I had this same bug for a while, it seems only to do neutral damage if you use an item with a raw spell damage boost (in my case, the jester set bonus).

**Comment by Moe-Ronickah** [comment]
After a bit of video capturing, and copying and pasting from one of my classes, I've got this, below.  
Bob's Mythic Wand, which is a purely neutral wand, appears to be doing both Earth and Fire damage.  Right below that, a Lunar Spine, which is a neutral and Water wand, appears to be doing Water, Earth, and Fire damage.  Coding glitch in calculations? Coding glitch in visual reporting?  I have no idea.

![neutral vs water wand damage symbols](https://cloud.githubusercontent.com/assets/11842380/14142972/54892bac-f64e-11e5-95f7-d1edb6ef96ea.png)

**Comment by DarkDemonDragon** [comment]
@Moe-Ronickah are you using spells? Spells use elemental damage regardless of the weapon.

**Comment by Moe-Ronickah** [comment]
@DarkDemonDragon , yes, both of those images are from Meteor spells, as are the OPs.

@dltkdwns , OK, now that I've clarified what we are seeing, as I wasn't certain, the first damage item that you are reporting, the -0 (heart symbol), is, indeed, your neutral damage.

My Ethereal, in my stats, shows 15 - 30 Neutral Damage.
My stats also shows -5% Melee.
When melee hitting an NPC, I see a range of -17 to -60 Neutral Damage (lost Hearts).

What we need to see is if you have any negative melee damage stats that were causing this problem, or if it is your Ethereal, or if it is something that has been fixed in the interim.

Come back and help us here, please.

**Comment by RedMorcus** [comment]
@Moe-Ronickah I can help if you can't find the original guy, my Ethereal does the exact same thing. I also do 0 neutral melee damage, but that's becuase of my three piece jester set.

**Comment by shinyafro** [comment]
I seem to have the same issue with my lunar spine and previously, my ethereal. i grabbed me some screenshots of the Detlas town massacre of 15/4/15, including both wands (Bob + Lunar) and Stat screen. Stats are 90 Int, 65 agility, 55 dexterity, 2 strength and 3 defense., don't recall which order. 
![2016-04-15_08 08 16](https://cloud.githubusercontent.com/assets/18068356/14547738/6bc9172c-02e3-11e6-95b8-0f8663af9136.png)
![2016-04-15_08 08 08](https://cloud.githubusercontent.com/assets/18068356/14547741/706dc7d2-02e3-11e6-8785-2aa1b0d99aa2.png)
![2016-04-15_08 10 09](https://cloud.githubusercontent.com/assets/18068356/14547743/780dfc32-02e3-11e6-97d5-1292c4c9a555.png)
So we can see my status effects and the 2 wands stats, We can see it apply my spell+ as neutral damage, other then that neutral is a no-go, except on my bobs mythic.
![2016-04-15_08 07 45](https://cloud.githubusercontent.com/assets/18068356/14547797/ea03a9a4-02e3-11e6-8595-9515ce1a5b04.png)
![2016-04-15_08 07 53](https://cloud.githubusercontent.com/assets/18068356/14547798/ef9f2b36-02e3-11e6-90d9-8be5f054597f.png)
![2016-04-15_08 07 59](https://cloud.githubusercontent.com/assets/18068356/14547802/f5078938-02e3-11e6-8080-a1551e28e2c7.png)
A second after the attack, we get a second strike that does a tiny bit of damage, however what is strange is it does wand damages, as advertised?
![2016-04-15_08 08 00](https://cloud.githubusercontent.com/assets/18068356/14547825/22199056-02e4-11e6-844d-d0a169de90a1.png)
Heres my bobs mythic doing its job
![2016-04-15_08 08 31](https://cloud.githubusercontent.com/assets/18068356/14547832/2be00944-02e4-11e6-889c-24005bf815d2.png)
![2016-04-15_08 08 32](https://cloud.githubusercontent.com/assets/18068356/14547833/31c39e7a-02e4-11e6-9907-ceae5b2a07ce.png)

Hopefully this was helpful in the slightest.

**Comment by shinyafro** [comment]
As for the Earth and Fire, i am pretty sure that's intentional. If you look at the meteor spell, its supposed to deal fire and earth damage (30%/30%) if you check Help -> Classes. All spells have their own elemental damages that are applied.

**Comment by Yoavronen** [comment]
@shinyafro the second beat of damage comes from the poison identification, please check if any of your items have it.

**Comment by Yoavronen** [comment]
And as @Moe-Ronickah said this might br a visual glitch, as soon as I'll get back from my weekend I'll test it out (unless one of you guys do it before me)

**Comment by shinyafro** [comment]
@Yoavronen I included my bonuses screens, no poison. I just assumed it was from the meteors burning ground effect, which is odd as it does no fire damage.

**Comment by Yoavronen** [comment]
@shinyafro it may be because of the Burning effect, I haven't thought of that. 
But the compass bonuses tab shows only the bonuses from your armor and accessories (doesn't count the weapon). Also lady time I checked it isn't big enough to show all the bonuses.

**Comment by shinyafro** [comment]
@Yoavronen i also included weapon stats, which lunar spine to my knowlege does not include poison.

**Comment by Moe-Ronickah** [comment]
We now know that this is an intentional game mechanic, at this time.  Whether or not it will be changed in the future, we don't know.
