### ISSUE TITLE
Loosing skill points, after skill reset

### ISSUE THREAD

**Issue by Crilless** [Wynncraft/Issues#4127]
Hello!
Yesterday i did a reset of my skills, i started by upgrading Agility, and that was fine, but then i tryed to upgrade Strength. I put some points into it, but it dident get higher, it stayed at 0, but it still used my skillpoints, after a while, with wasting skillpoints, i finaly got it upgraded. And now, i have lost almost 30 skillpoints.
So now i cant equip a alot of my gear... Please help me! D:

**Comment by Trixter313** [comment]
Could you post a screenshot of your skill points? Thanks!

**Comment by Crilless** [comment]
Yeah, bt i dont know how... I have never used this site before. :P

**Comment by IDockson** [comment]
Take a screenshot, drag it into the commenting section. It even says it down there :)

**Comment by Dar-krusos** [comment]
You can try resetting your Skill Points again.

**Comment by trickstini** [comment]
I have this same issue, but with strength, and also mine is stuck at 64 and not 0

**Comment by Dar-krusos** [comment]
> I have this same issue, but with strength, and also mine is stuck at 64 and not 0
> - trickstini

Are you sure it's not bugged, because the Skill Point per Skill cap is 100, but it will only show up to 64 (you must hover over the Skill to see the actual number).

**Comment by DarkDemonDragon** [comment]
Is this issue still persisting? Most likely you had some items with some major negative IDs for Agility and Strength.

**Comment by DarkDemonDragon** [comment]
@Crilless please respond if this is still happening.
