### ISSUE TITLE
I lost my armor and cant use my weapons

### ISSUE THREAD

**Issue by Jobili** [Wynncraft/Issues#4128]
I logged on to the server a long time ago and i had some pretty good goodies. When i logged back on, i couldnt use my goodies anymore... i cant even identify them...

http://www.noelshack.com/2016-06-1455465530-2016-02-13-17-03-43-2.png
http://www.noelshack.com/2016-06-1455465541-2016-02-13-17-03-43.png
there you go

**Comment by TrashcanMan** [comment]
Items with special characters in their name (eg Fierte) are broken right now and should be fixed soon.
