### ISSUE TITLE
Lifesteal doesn't work

### ISSUE THREAD

**Issue by DoctorFryder** [Wynncraft/Issues#4129]
Hi, I think this is not only my problem. I don't know why lifesteal doesn't work, when I hit an enemy I will not get healed (when I am lower than 100%). Like my friend have weapons and some armor that is mainly on lifesteal, so now is unusable for him. I don't know if that's bug or if it's change. Will lifesteal work again?

**Comment by TrashcanMan** [comment]
Known issue, #3225. Please close this issue and follow the original for updates. Thanks!
