### ISSUE TITLE
Typo in the "The Angry Village" quest.

### ISSUE THREAD

**Issue by IDockson** [Wynncraft/Issues#4130]
happend -> happened

![2016-02-14_18 21 15](https://cloud.githubusercontent.com/assets/17236650/13035148/b61f51b2-d348-11e5-918a-4af2904d01f2.png)

**Comment by Dar-krusos** [comment]
Yeah, there are typos in many quests. Please send all typos to me in a conversation with [my forums account](https://forums.wynncraft.com/members/dar-krusos.2849/).

**Comment by Dar-krusos** [comment]
I will also make a thread to catch all typos.

**Comment by Moe-Ronickah** [comment]
Fixed on build server.
