### ISSUE TITLE
Woo! Your armor has been added to your skin.

### ISSUE THREAD

**Issue by HyperSpeedy11** [Wynncraft/Issues#4134]
I have disabled armor because it would never load and just randomly add nothing to my skin in the middle of fighting mobs. When I have it disabled, sometimes it will randomly say, "Woo! Your armor has been added to your skin." and re-add my armor on, but when I do /armor it enables it.
![2016-02-14_19 36 31](https://cloud.githubusercontent.com/assets/17241728/13038081/432c4966-d353-11e5-852b-8928c7114737.png)

**Comment by DarkDemonDragon** [comment]
This is because you're toggling armor too quickly. First wait for the armor to apply onto your skin. Then do /toggle armor. Most likely you did /toggle armor when the server started to apply the armor onto you. This causes a weird paradox that prioritizes applying the armor.

**Comment by ThunderRemix** [comment]
Also, disable that mob radar.

**Comment by Dar-krusos** [comment]
Yes, disble the mod radar, as it is an illegal mechanic that is [not allowed in use on Wynncraft](https://forums.wynncraft.com/threads/game-forum-rules.111874/).

This is the rule here:
> 1. No hacking/hacked clients.
(ex. fly hacking, aimbotting/killaura, water walking, xray, entity tracker, speed hacking & possession of a hacked client, even when not in use.)
> - Salted

**Comment by HyperSpeedy11** [comment]
1. It's not a mob radar its Journey Map but ok.

2. I disable it as soon as i get on the server and an hour later it does that

**Comment by Dar-krusos** [comment]
What are those Steve and Villager icons? If those are NPCs and players, it is illegal.

**Comment by jcutrell2016** [comment]
lol
