### ISSUE TITLE
XP Bomb Lost

### ISSUE THREAD

**Issue by ChrisRyann** [Wynncraft/Issues#4135]
I was attempting to throw an XP Bomb on a server, and as soon as I went to throw it, the chat said the server was restarting in 10 minutes - which means it said 'This bomb cannot be thrown at this time'. I went into another world to then attempt to throw the bomb I was going to throw, and it says that I do not have a bomb to throw, and that I need to purchase one.

My friend also had this happen 2 times today. 

Is there a way to get this XP Bomb back?

IGN : ChrisRyann

**Comment by Dar-krusos** [comment]
No, there is no way for you to get this bomb back. I'm sorry, but I don't think you could get this bomb back without video proof, and even then, it might not be enough to pass the no-refund policy.

**Comment by ChrisRyann** [comment]
I figured that would be the case. Either way, my Bomb is missing and it's a glitch and/or bug, so I was just submitting it to have it known so maybe it won't happen to other people.

**Comment by ThunderRemix** [comment]
The no-refund policy only affects in-game obtained items. For questions concerning items purchased from the Wynncraft store, please contact support@wynncraft.com . Although, you might not have enough evidence to support your claim.

**Comment by ChrisRyann** [comment]
I'm not going to bother pursing the cause of getting my XP Bomb back, that I paid real life money for, because it will just be a waste of my time. I do not record my gameplay in order to have proof for when a glitch occurs. I know now where not to spend my money, however.
