### ISSUE TITLE
Resource pack

### ISSUE THREAD

**Issue by BreakkAway** [Wynncraft/Issues#4137]
The resource pack that you have does not work for some reason. The armour textures work but the level/health/weaponskins do not work. Please fix this. Yes i have enabled the texture pack and i have deleted the server and retryed and logged in and out.

**Comment by Dar-krusos** [comment]
Have you tried deleting the pack residing in your /.minecraft/server-resource-pack/ folder? This will make you download the pack again once you join the server again.

Have you also disabled all other resource packs (all the ones in the menu)?

**Comment by BreakkAway** [comment]
yea i tried doing the last one didnt work and i dont know where to find that minecraft server resource folder so :c

**Comment by Dar-krusos** [comment]
To go to your Minecraft directory:

> 1. Press [Windows + R] on a computer running Windows.
> 2. Type in _%appdata%_ and enter.
> 3. Your /.minecraft folder will be in there.
> - Getting to your .minecraft folder

**Comment by Trixter313** [comment]
Is the issue still occurring?

Also, what is your operating system?
