### ISSUE TITLE
Kick for Flying

### ISSUE THREAD

**Issue by sicklylemon** [Wynncraft/Issues#4138]
Any time I get teleported on Wynncraft, whether its from logging in to going through a portal at the Hive I have an outrageously high chance of getting kicked from that server for "flying"; this makes trying to do something like helping others out with the tower of ascention a real pain. Could this please be fixed its causing me a lot of problems.

**Comment by Dar-krusos** [comment]
This is plainly just a result of lag. Try toning down all performance to the lowest settings, use Optifine, or lastly, get better internet. If you cannot  improve your internet, and the server developers cannot reduce its lag enough, I'm afraid there's nothing much you can do.

If you are using the New Minecraft Launcher, you can try using the Java Launcher [here](https://s3.amazonaws.com/Minecraft.Download/launcher/Minecraft.jar), as I cannot use the New Minecraft Launcher, as it causes lag for me that the Java Launcher doesn't.

**Comment by Moe-Ronickah** [comment]
Is your issue fixed, or is it still happening to you?

**Comment by DarkDemonDragon** [comment]
Is this still happening and if so does it happen repeatedly like multiple times in a 20 minute period?

**Comment by Moe-Ronickah** [comment]
@sicklylemon hasn't responded in well more than a month, so, I think it's safe to assume that it was just lag, as @Dar-krusos suspected.
