### ISSUE TITLE
Stuck in floors at the Hive and teleported under Hive rooms

### ISSUE THREAD

**Issue by sicklylemon** [Wynncraft/Issues#4139]
Sometimes when teleporting into the next room of a floor at the Hive can stick you into the floor, often getting stuck completely is avoidable by simply doing /class and re-logging but other times you could get stuck and are forced to /kill or use a town teleport scroll. Also though I might add that sometimes I get teleported just under a Hive level a floor (though I've only had this issue with the water floor) and get dropped to the flat land that lies under each of the rooms and die from fall damage, not great to experience.

**Comment by Dar-krusos** [comment]
Hmmm. I've only ever gotten stick in the floor of the Hive once. Whenever I go into the next room of a Hive floor, I spawn in the ground, but can always simply jump out of it without having to do /class. I also only have to jump once, so it may just be lag or something changed. If something did change, I think they might have to rollback the Hive mechanics/replicate the ones that let you just jump out. I don't have much to contribute to this issue, but I'll just put this out there.

**Comment by shinyafro** [comment]
I soloed the hive up to floor 8 water temple then when i was gonna git number 9 the game was like lolno and spawned me under the floor. i am a level 82 mage as of now. Teleporting did not work however i was able to farm mad exp from under the floor with meteorite, but i could not escape only /kill worked.

**Comment by shinyafro** [comment]
Alright, i found a solution to my issues. what i did was i spawned an iron golem, then my horse which didn't spawn because no room (for some reason this step is required) then i am able to jump on my iron golem, dismount, desummon it (as i don't want to mount it again instead of blowing holes in the mobs). i was able to beat the water temple after that. For non donors or donors who don't have pets this would have been a major issue. It might be because i am from Australia?

**Comment by IceMephit** [comment]
I was stuck in the floor at spawn, jumping did not help.  I just logged off in frustration and will not be playing again.

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will get you out @IceMephit

**Comment by shinyafro** [comment]
@Trixter313 what about when it happens 100% of the time? i have been to water floor, level 9 of the hive, about 20+ times, every time without fail i have ended up stuck in the floor. I could /kill but it will not help progress the issue. The only fix is being a VIP / VIP+ and jumping on a pet and glitching out of the floor. This is literally what i have to do every time either i A: Carry someone or B: Level a new char. 

I know this does not happen to everyone, but to give you some information, i live in western Australia, I use 1.8.9 with optifine, no texture packs etc.

**Comment by Trixter313** [comment]
I believe it is sill an issue but I was just making sure that they knew how to get out of it until it is fixed. =)

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
