### ISSUE TITLE
Stuck in the dark room where you choose the class

### ISSUE THREAD

**Issue by nikitonus** [Wynncraft/Issues#4141]
Iamnik who is me in the game is permanently stuck inside the dark room where you get teleported when you choose a class in game. On any lobby and any server when I login I get teleported into that room.

If any administrators see this I really like your server and the fact that you added a whole new province is quite impressive so if you see this can you teleport me (my nick in game is Iamnik) anywhere on the ACTUAL map. Thanks.

**Comment by Kevinny77** [comment]
Same! I have been stuck here for almost a week I think.

**Comment by Dar-krusos** [comment]
Does doing /kill work? If not, then I'm afraid you won't be able to do anything, and is a duplicate of issues [3139](https://github.com/Wynncraft/Issues/issues/3139)/[3250](https://github.com/Wynncraft/Issues/issues/3250).

**Comment by nikitonus** [comment]
/kill works you should try it just make sure you have 2 soul points to spare

**Comment by nikitonus** [comment]
I'll still keep the issue up so that any other player who encounters this problem will be able to refer to this issue
