### ISSUE TITLE
LOSING ALL MY STUFF BUG PLS HELP

### ISSUE THREAD

**Issue by Yiqids** [Wynncraft/Issues#4142]
I TRADED WITH SOMEONE TO SHOW MY GEAR/WEAPONS AND I GOT IT BACK IN MY INVENTORY, I DIDNT HAVE FULL INVENTORY WHATSOEVER. I JUST PUT IT BACK IN THEN IT COMES BUG/ERROR AND THEN I LOSE ALL MY GEAR PLEASE HELP I WANT MY GEAR BACK -Yiqids PLEASE OMG.

**Comment by Yiqids** [comment]
AND GET /HELPOP

**Comment by Yiqids** [comment]
PLEASE ROLLBACK FOR ME OR SOMETHING

**Comment by TelamonFTW** [comment]
SAME I HAVE LOST MY STUFF WITH THE BIG GRAVEL UPDATE HELPPPP!!!!!!!!!!!

**Comment by Dar-krusos** [comment]
I'm afraid you guys can't get your items back, as there is a no-refund policy. The only thing you can do is ask people for items, or buy some if you have money.

**Comment by Yiqids** [comment]
.....

**Comment by Odnod** [comment]
could you please explain the bug in greater detail and not use all caps?

**Comment by Yiqids** [comment]
i was doing a quest that i needed scrolls or whatever the ones you teleport with and you get drained 1 soul point, i was doing that quest then i came to neesak and i dueled a archer and i won by 400hp, he wanted to see my gear so i traded with him, took my stuff back not full inv had space whatsoever. then it came "Woo! we are getting your armor or whatever." then it came you crashed so we put you back in the class section, i logged back into my assasin and what i see, all my stuff that i traded was gone. armor/gear,

**Comment by Moe-Ronickah** [comment]
Servers cannot write everything that is occurring on them, to memory, instantaneously.  There is a delay in committing to hard drive everything that is in RAM.  So, it is possible to lose items when one memory commit occurs, showing that you took something out of your inventory, followed by a crash, before the server can record what you did with that item.  This happens in MC, too, on your local game.
