### ISSUE TITLE
guild + quest bugs

### ISSUE THREAD

**Issue by trickstini** [Wynncraft/Issues#4143]
1---- I'm not sure if this is meant or a bug, but I am the owner of my guild and I can not contribute any guild xp, when I do /guild list it says I have given 0, so I'm thinking that I'm actually giving xp but it isn't showing, and then I kill some mobs and do dungeons and nothing. No xp was given. and yes I did /guild xp 100. With that being said I also turned in quest (while I had my guild xp at 100) that was 82,500 xp (which I also had double active so it was actually 165,000) when I turned it in I got 0 xp for my actual self ( which is expected Bc I had my guild xp at 100) and I got 0 xp towards the guild. My guild lvl was at 15 and we were 57% in the lvl and nothing changed after the quest. 

So if this is a bug plz fix if not plz let me know. 

2---- the quest "WynnExcavation site C" and the quest if fine until you try to turn it in, it says (not 100% sure what the exact words were Bc I forgot but this is close) "you need the purple crystal to start this quest". Which doesn't make sense Bc I already started the quest. 

3---- I changed my name on the Mojang website ( Bc I hated my name) and the name change registered in the game, but I can no longer type in guild chat (/g). My guess is that Bc the owner of the guild is my old name? 

Thank you for taking the time to read this and helping me fix my issues.

**Comment by Dar-krusos** [comment]
1. Guild xp contribution has been bugged for quite a long time, and can only work illegally (not allowed to be known).

2. Do you have the Purple Crystal from the golem area in the fire-y caverns?

3. If you change your name, you have to be kicked or peave the guild, and then be re-invited back (though a recent patch sort-of fixed this).

**Comment by trickstini** [comment]
I turned in the purple crystal at the start of the quest. Now trying to finish it, it'll say I need the purple crystal to START it again. When I have already done so.

**Comment by Dar-krusos** [comment]
Ok, I will come online later to assist you.

**Comment by Trixter313** [comment]
Try using /fixquests and see if that helps with number two.

**Comment by ShortsLPs** [comment]
I am having the same issue with the wynnexcavation site C quest, i started the quest. spied at the meeting, went through the lava cave and then got back at the island, the quest book updated and said i had to report back to Excavator Placardus, but when i talk to him it says i need the shard from site B, even though i already started the quest...
