### ISSUE TITLE
I lagged out(crashed) and died

### ISSUE THREAD

**Issue by Cheetqh** [Wynncraft/Issues#4146]
So I was fooling around with the mercenaries while trying to kill ocelots and started lagging and crashed and got sent to the hub, i lost my stuff because the crashing happened twice and i ended up going to 0 souls and lost my inventory. (link is showing that I died and afterwards saying that I was flying, aswell as showing that i was put in the hub from crashing)
![2016-02-15_18 32 56](https://cloud.githubusercontent.com/assets/17261057/13063103/aff6f068-d412-11e5-8417-6e3a345e7f96.png)

**Comment by ThunderRemix** [comment]
Wynncraft has a no refund policy. Sorry.

**Comment by Dar-krusos** [comment]
Sorry, no-one can do anything about it. In extremity, you could just upgrade your net. :/
