### ISSUE TITLE
Armour Never Loads

### ISSUE THREAD

**Issue by simon9664** [Wynncraft/Issues#4147]
Every time i login, it says my armour has loaded but it doesn't, doing /armor does nothing.

**Comment by HeyloLP** [comment]
just walk a bit around after sometime your armour will be added (this could take up to 30min)

**Comment by simon9664** [comment]
doing this does not work. I have walked around for 3 hours and nothing happens. I logged on once and did ToA from floor 2 to floor 7, my amor did not load at all.

**Comment by yoctomentric** [comment]
This is hapening to me, too. My chestplate hasn;t loaded sinse I got it, 7 days ago.

**Comment by HeyloLP** [comment]
it will draw it just takes a while because they load your skin in to a minecraft account wich they btw. bought for this feature then load the standart skin of the armour parts and then send this updated skin to the server wich "updates" your skin

**Comment by Moe-Ronickah** [comment]
simon9664, are your armor pieces loading, yet?
Second, in your MineCraft -> Options -> Skin Customization screen, do you have all of your "Second Layer" options turned on or off?  You will need to have them all set to "On" for your armor to show at all.

**Comment by simon9664** [comment]
I had no idea that you had to have those skin options turned on. Thank you for the help. It also seems sometimes that my armour loads. Not the shield items. But thank you all for the help.
