### ISSUE TITLE
Losing a weapon 

### ISSUE THREAD

**Issue by THATONEORC** [Wynncraft/Issues#4148]
I logged off at nivla forest and had my spear joker equipped in my hand. When I logged back on it was gone I looked to make sure I did not throw it down anywhere but I looked and could not find it. please help

**Comment by ThunderRemix** [comment]
Wynncraft has a no refund policy. Sorry.

**Comment by Trixter313** [comment]
Like stated above there is a very strict no refunds policy and if the item was dropped before you logged out it's most likely that it despawned or someone else picked it up.

To prevent this from happening again, I'd suggest changing your drop key to something way less likely to be accidentally pressed. Hopefully this helps!
