### ISSUE TITLE
Thanos & Llevigar no permission

### ISSUE THREAD

**Issue by CrafterTheMaster** [Wynncraft/Issues#4151]
"You are not permitted in this area" it says. No button or lever works in Thanos for some reason. The minecart doesn't activate, the door won't open, and the secret tier 3 chest door won't either. Please fix this immediately. Thank You, 

IGN: CrafterTheMaster

**Comment by TrashcanMan** [comment]
Try /kill with at least 3 soul points. The "You are not permitted" thing is a known issue and appears to be affecting the majority of chests, doors, buttons, etc. on the server. It should be fixed soon but for now hold off on quests with buttons and doors.

**Comment by CrafterTheMaster** [comment]
Ok, thank you. This is a huge help.

**Comment by CrafterTheMaster** [comment]
Umm, Sorry I know that it is closed but it didn't work. So war do I do?

**Comment by TrashcanMan** [comment]
Try right-clicking with an empty hand, that might work.

**Comment by Trixter313** [comment]
Pretty sure there's nothing we or you can do, the admins have to fix it and they know about the issue so it should be fixed pretty soon.

**Comment by CrafterTheMaster** [comment]
Ok. I guess I just have to wait and see.

**Comment by Trixter313** [comment]
This has happened with another town before and was fixed relatively quickly so it should be fixed soon. =)

**Comment by SpeederSam** [comment]
Its also happening in Llivgar just so you guys know. Thanks for the help Trixter

**Comment by Trixter313** [comment]
Thanks @SpeederSam , added Llevigar to the title.

**Comment by BlueThunder25** [comment]
@SpeederSam Please close Thread if issuses are resolved :)

**Comment by CrafterTheMaster** [comment]
I figured out how to fix it. It isn't on the city. Only the player gets it.
Just right click with an empty slot.

**Comment by DarkDemonDragon** [comment]
If your issue has been resolved please close this.

**Comment by CrafterTheMaster** [comment]
ShopBelieve

@media screen and (max-width:1025px){
.mobilize{
	width:100% !important;
	}
.mobileDelete{
	display:none;}

}



	
    	
        	
                
                    
                        
                        	
                            	
                            
                        
                        
                    	     
                    
                
    		
        
    
    
    	
        	
                
                    
                        
                          	My group, Buena Park Junior High, kicked off our Believe Kids fundraiser and I need your help! We are raising $20,000 for essential programs not currently funded through traditional means..
  							Will you help me reach my goal? You can support my fundraiser by clicking the "Help Support Now" button below. You can shop 24/7 and everything is shipped directly to you.  If you don't click the link below, you need go to www.ShopBelieve.com, click SHOP NOW and then put in CA and Buena Park Junior High.
                    	
                	
                
                
                    
                    	
                        
                        	Help Support Now 
                        
                        
                	
                
				
                    
                        
  							I get credit for your order and our group gets, on average, 40% profit.  You'll find items like wrapping paper, gift bags, Jelly Belly, magazines, cookbooks, chocolates, candles, flowers and a whole lot more! 
  							Our fundraiser will be running from 8/11/2016 through 8/25/2016. Please help me by placing your order before the end of our sale. 
  							Thanks for helping me reach my goal and for supporting my group.
  							Aidan
                           
                    
                
    		
        
        
        	
                
                    
                        
  							
                           
                    
                
    		
        
        
        	
                
                    
                        
							
                          	
                          	Please use the links provided in this email. This will ensure that the student you are supporting receives credit.
                          	CLICK HERE to Shop
                            If you are having trouble with the above link, you can copy and paste the following link into your browser:https://shop.believekids.com/Shop?t=EM&sid=45716&e=reply%2b00fc1f78dbf5ab48f2c103256e599249ee51122786b8191692cf0000000112dd726392a169ce07fad259%40reply.github.com
                         	
                           
                    
                
    		
        
    
    
    	
        	
                
                	
                    	
                    
                
    		
        
        
        	
                
                    
                    	
                        
                        	
                            	
                                	
                                    
                                    	
                                            
                                        
                                    
                                    
                                    
                                    	
                                            
                                        
                                    
                                    
                                    
                                        
                                            
                                        
                                    
                                    
                                    
                                        
                                            
                                        
                                    
                                    
                                    
                                        
                                            
                                        
                                    
                                    
                                
                            
                          
                          
                    
                
    		
        
        
        	
                
                    
                    	
                        	Sale quantities are limited, and all sales are final on discounted items.Prices listed in US dollars. Sale pricing not valid on previous purchases.
                    To ensure delivery to your inbox, add home@shopbelieve.com to your address book.
                    © Believe Kids, Direct Marketing, 7101 S. Fulton St. Suite 200 Centennial, CO 80112.
                    
                    		
  If you do not wish to receive these emails from your friends and family, you can remove yourself from future mailings by clicking here to Unsubscribe.

**Comment by CrafterTheMaster** [comment]
ShopBelieve

@media screen and (max-width:1025px){
.mobilize{
	width:100% !important;
	}
.mobileDelete{
	display:none;}

}



	
    	
        	
                
                    
                        
                        	
                            	
                            
                        
                        
                    	     
                    
                
    		
        
    
    
    	
        	
                
                    
                        
                          	My group, Buena Park Junior High, kicked off our Believe Kids fundraiser and I need your help! We are raising $20,000 for essential programs not currently funded through traditional means..
  							Will you help me reach my goal? You can support my fundraiser by clicking the "Help Support Now" button below. You can shop 24/7 and everything is shipped directly to you.  If you don't click the link below, you need go to www.ShopBelieve.com, click SHOP NOW and then put in CA and Buena Park Junior High.
                    	
                	
                
                
                    
                    	
                        
                        	Help Support Now 
                        
                        
                	
                
				
                    
                        
  							I get credit for your order and our group gets, on average, 40% profit.  You'll find items like wrapping paper, gift bags, Jelly Belly, magazines, cookbooks, chocolates, candles, flowers and a whole lot more! 
  							Our fundraiser will be running from 8/11/2016 through 8/25/2016. Please help me by placing your order before the end of our sale. 
  							Thanks for helping me reach my goal and for supporting my group.
  							Aidan
                           
                    
                
    		
        
        
        	
                
                    
                        
  							
                           
                    
                
    		
        
        
        	
                
                    
                        
							
                          	
                          	Please use the links provided in this email. This will ensure that the student you are supporting receives credit.
                          	CLICK HERE to Shop
                            If you are having trouble with the above link, you can copy and paste the following link into your browser:https://shop.believekids.com/Shop?t=EM&sid=45716&e=reply%2b00fc1f780cc30e3863ce20c6fa99ba8f18727937a98acc2e92cf0000000112dec48392a169ce07fad259%40reply.github.com
                         	
                           
                    
                
    		
        
    
    
    	
        	
                
                	
                    	
                    
                
    		
        
        
        	
                
                    
                    	
                        
                        	
                            	
                                	
                                    
                                    	
                                            
                                        
                                    
                                    
                                    
                                    	
                                            
                                        
                                    
                                    
                                    
                                        
                                            
                                        
                                    
                                    
                                    
                                        
                                            
                                        
                                    
                                    
                                    
                                        
                                            
                                        
                                    
                                    
                                
                            
                          
                          
                    
                
    		
        
        
        	
                
                    
                    	
                        	Sale quantities are limited, and all sales are final on discounted items.Prices listed in US dollars. Sale pricing not valid on previous purchases.
                    To ensure delivery to your inbox, add home@shopbelieve.com to your address book.
                    © Believe Kids, Direct Marketing, 7101 S. Fulton St. Suite 200 Centennial, CO 80112.
                    
                    		
  If you do not wish to receive these emails from your friends and family, you can remove yourself from future mailings by clicking here to Unsubscribe.

**Comment by CrafterTheMaster** [comment]
ShopBelieve

@media screen and (max-width:1025px){
.mobilize{
	width:100% !important;
	}
.mobileDelete{
	display:none;}

}



	
    	
        	
                
                    
                        
                        	
                            	
                            
                        
                        
                    	     
                    
                
    		
        
    
    
    	
        	
                
                    
                        
                          	My group, Buena Park Junior High, kicked off our Believe Kids fundraiser and I need your help! We are raising $20,000 for essential programs not currently funded through traditional means..
  							Will you help me reach my goal? You can support my fundraiser by clicking the "Help Support Now" button below. You can shop 24/7 and everything is shipped directly to you.  If you don't click the link below, you need go to www.ShopBelieve.com, click SHOP NOW and then put in CA and Buena Park Junior High.
                    	
                	
                
                
                    
                    	
                        
                        	Help Support Now 
                        
                        
                	
                
				
                    
                        
  							I get credit for your order and our group gets, on average, 40% profit.  You'll find items like wrapping paper, gift bags, Jelly Belly, magazines, cookbooks, chocolates, candles, flowers and a whole lot more! 
  							Our fundraiser will be running from 8/11/2016 through 8/25/2016. Please help me by placing your order before the end of our sale. 
  							Thanks for helping me reach my goal and for supporting my group.
  							Aidan
                           
                    
                
    		
        
        
        	
                
                    
                        
  							
                           
                    
                
    		
        
        
        	
                
                    
                        
							
                          	
                          	Please use the links provided in this email. This will ensure that the student you are supporting receives credit.
                          	CLICK HERE to Shop
                            If you are having trouble with the above link, you can copy and paste the following link into your browser:https://shop.believekids.com/Shop?t=EM&sid=45716&e=reply%2b00fc1f78af1eeb16a646d3db6fcbb07d8a8a9fa1fca8eb5d92cf0000000112da696f92a169ce07fad259%40reply.github.com
                         	
                           
                    
                
    		
        
    
    
    	
        	
                
                	
                    	
                    
                
    		
        
        
        	
                
                    
                    	
                        
                        	
                            	
                                	
                                    
                                    	
                                            
                                        
                                    
                                    
                                    
                                    	
                                            
                                        
                                    
                                    
                                    
                                        
                                            
                                        
                                    
                                    
                                    
                                        
                                            
                                        
                                    
                                    
                                    
                                        
                                            
                                        
                                    
                                    
                                
                            
                          
                          
                    
                
    		
        
        
        	
                
                    
                    	
                        	Sale quantities are limited, and all sales are final on discounted items.Prices listed in US dollars. Sale pricing not valid on previous purchases.
                    To ensure delivery to your inbox, add home@shopbelieve.com to your address book.
                    © Believe Kids, Direct Marketing, 7101 S. Fulton St. Suite 200 Centennial, CO 80112.
                    
                    		
  If you do not wish to receive these emails from your friends and family, you can remove yourself from future mailings by clicking here to Unsubscribe.

**Comment by CrafterTheMaster** [comment]
ShopBelieve

@media screen and (max-width:1025px){
.mobilize{
	width:100% !important;
	}
.mobileDelete{
	display:none;}

}



	
    	
        	
                
                    
                        
                        	
                            	
                            
                        
                        
                    	     
                    
                
    		
        
    
    
    	
        	
                
                    
                        
                          	My group, Buena Park Junior High, kicked off our Believe Kids fundraiser and I need your help! We are raising $20,000 for essential programs not currently funded through traditional means..
  							Will you help me reach my goal? You can support my fundraiser by clicking the "Help Support Now" button below. You can shop 24/7 and everything is shipped directly to you.  If you don't click the link below, you need go to www.ShopBelieve.com, click SHOP NOW and then put in CA and Buena Park Junior High.
                    	
                	
                
                
                    
                    	
                        
                        	Help Support Now 
                        
                        
                	
                
				
                    
                        
  							I get credit for your order and our group gets, on average, 40% profit.  You'll find items like wrapping paper, gift bags, Jelly Belly, magazines, cookbooks, chocolates, candles, flowers and a whole lot more! 
  							Our fundraiser will be running from 8/11/2016 through 8/25/2016. Please help me by placing your order before the end of our sale. 
  							Thanks for helping me reach my goal and for supporting my group.
  							Aidan
                           
                    
                
    		
        
        
        	
                
                    
                        
  							
                           
                    
                
    		
        
        
        	
                
                    
                        
							
                          	
                          	Please use the links provided in this email. This will ensure that the student you are supporting receives credit.
                          	CLICK HERE to Shop
                            If you are having trouble with the above link, you can copy and paste the following link into your browser:https://shop.believekids.com/Shop?t=EM&sid=45716&e=reply%2b00fc1f783a85ee502c0f9deaed9daf8d576f4f73c2f633c592cf0000000112e4370392a169ce07fad259%40reply.github.com
                         	
                           
                    
                
    		
        
    
    
    	
        	
                
                	
                    	
                    
                
    		
        
        
        	
                
                    
                    	
                        
                        	
                            	
                                	
                                    
                                    	
                                            
                                        
                                    
                                    
                                    
                                    	
                                            
                                        
                                    
                                    
                                    
                                        
                                            
                                        
                                    
                                    
                                    
                                        
                                            
                                        
                                    
                                    
                                    
                                        
                                            
                                        
                                    
                                    
                                
                            
                          
                          
                    
                
    		
        
        
        	
                
                    
                    	
                        	Sale quantities are limited, and all sales are final on discounted items.Prices listed in US dollars. Sale pricing not valid on previous purchases.
                    To ensure delivery to your inbox, add home@shopbelieve.com to your address book.
                    © Believe Kids, Direct Marketing, 7101 S. Fulton St. Suite 200 Centennial, CO 80112.
                    
                    		
  If you do not wish to receive these emails from your friends and family, you can remove yourself from future mailings by clicking here to Unsubscribe.
