### ISSUE TITLE
this is not a issue its a question for wynncraft

### ISSUE THREAD

**Issue by ninjamaster330** [Wynncraft/Issues#4152]
what is the texture pack send me a link if you can please I really enjoy the texture pack

**Comment by ThunderRemix** [comment]
Not an issue.

**Comment by Dar-krusos** [comment]
The resource pack's textures affect blocks, not items. For example, one of the spears on Wynncraft is really a dirt block or some other thing.

If you really want the resource pack, you can download it [here](https://dl.dropboxusercontent.com/u/51915451/Wynncraft/Wynncraft%20Resource%20Pack.zip).

**Comment by shannonfaye** [comment]
I also have a question, please if you can help me I'll be very great full. I joined the server back 2 years ago and long story short I put all my emeralds into a bank but then got stuck in a fire pit of death so I rage quit and I didn't go back onto the server until now. It's telling me I have to identify everything I own before I can use them but I haven't got any emeralds to pay villagers with, HELP PLEASE

**Comment by ninjamaster330** [comment]
dar krusos thanks I was looking for the items but still thanks

**Comment by Odnod** [comment]
@ninjamaster330 no texture pack exists with just the items. the way they are able to be 3d is by being blocks.
