### ISSUE TITLE
Read-Me Pls/ Bugs with sliver fish dungeon 

### ISSUE THREAD

**Issue by ElitePvpPlanet** [Wynncraft/Issues#4154]
Me and my Friend was doing the sliverfish dungeon,when we got to the boss , we killed it then a another one spawned, and killed that one too, then an another one spawned ,we died from the 3rd one and we said "know what? we buying as many healing pots as we can". so we did and when we got to the door inside from the dungeon, we died. I was like" WTF WHY?!?!?!?!" after me raging for a couple minutes, I went to do a quest "Wrath of the Mummy"  the mummy had 6000 health. when I killed it. I saw the bandage, but could't pick it up -_-. and thats when a came here, Am not gonna lose m money like that. Can I get 12 EB back. pls I hate server lag ;-;

![2016-02-16_09 38 44](https://cloud.githubusercontent.com/assets/17274346/13079948/9e74eef8-d494-11e5-9ef4-561b32cd6271.png)

**Comment by ElitePvpPlanet** [comment]
![2016-02-15_20 58 37](https://cloud.githubusercontent.com/assets/17274346/13079984/c285a49a-d494-11e5-848f-404ed8ef88f2.png)

**Comment by Odnod** [comment]
With the silverfish dungeon issue, it is a well-known issue that everyone has been dealing with for a long time. And with the mummy, did you kill it alone?

**Comment by Moe-Ronickah** [comment]
I've asked that a GM check the silverfish boss re-spawn rate.

As to the Mummy's rag, if you don't do enough damage, you won't get credit for the kill.

**Comment by Moe-Ronickah** [comment]
The Silverfish Boss has a 50% chance of respawning within seconds after it dies.  It was born that way, e.g., it's not an issue, it's meant to be like that.
