### ISSUE TITLE
WynnExcavation Site A - Quest Bug

### ISSUE THREAD

**Issue by BlueThunder25** [Wynncraft/Issues#4155]
I beat the boss and went back to return the item and Vade took the item and it reset my quest but it is bugged, this youtube vid I found, describes it http://m.youtube.com/watch?v=e6bwXAxQOZE please help me.

My Username is BlueThunder25,
Thank you for your time.

**Comment by Trixter313** [comment]
What happens when you talk to Tesha? Also, does it return any important quest items when you type /fixquests

**Comment by yoctomentric** [comment]
when you talk for tesha he just says return the translated traspcript back to the head excavator dude. then the excavator dude yells at you to go to tesha and translate the tablet. it is an endless loop
