### ISSUE TITLE
Bug for me

### ISSUE THREAD

**Issue by nMarshmallosweet** [Wynncraft/Issues#4162]
I have had no item since the last server reload(about 5:00, 2016.02.17). Please return my item.

**Comment by Odnod** [comment]
please give more detail

**Comment by nMarshmallosweet** [comment]
I was in the skeleton dengeon, and killed by skelleton. As soon as I alive, the server closed, and re-opened. So I joined again to play. However, my wizard's item was none. What should I do?

**Comment by nMarshmallosweet** [comment]
Ah, I died while fighting with skeleton, and as soon as I revive, the server was restarted.

**Comment by Trixter313** [comment]
If you die with less than 3 soul points, your items get dropped on the ground. If it's only one item missing, you most likely just dropped it and to prevent that from happening you should change your drop key to something you're less likely to accidentally press.

Wynncraft has a strict no refunds policy so either way there's nothing we can do about the lost item but if you ask around or just farm a bit you should get items again pretty fast. Hope this helps!

**Comment by nMarshmallosweet** [comment]
I have no item

**Comment by Trixter313** [comment]
Then you most likely died with less than 3 soul points. Make sure to keep an eye on them. You get one back every ingame sunrise.
