### ISSUE TITLE
Creeper Infiltration

### ISSUE THREAD

**Issue by AssasirePikachu** [Wynncraft/Issues#4164]
Because Powders are blocked and i can't dismiss quests, i need some help to get through that quest or dismiss it.. ore something like this.. :-1:

**Comment by DarkDemonDragon** [comment]
I'm sorry, but you need to provide more details. Saying "..." doesn't help much. Powders are not blocked you just can't use them til the next update, but they are still obtainable. You can get powders from relics, or from other players that sell them.
