### ISSUE TITLE
I found a glitch (Under the map!)

### ISSUE THREAD

**Issue by ActivityTest** [Wynncraft/Issues#4166]
I am stuck under the map....
Cordinates : 
X: -979
Y: 62 : 63 if you jump!
Z -1691
I hope a MOD can fix this for me to tp me back!
I am stuck so... Help me pls
Thank u for the help!

**Comment by DarkDemonDragon** [comment]
You would have to message a staff member ingame. Also, please explain how you got there in the first place.

**Comment by Dar-krusos** [comment]
Try just doing /kill to get out.
