### ISSUE TITLE
Infinite Loot Chest

### ISSUE THREAD

**Issue by KiRtAp2** [Wynncraft/Issues#4169]
Near Almuj, there is a house.
X: 719
Z: -1985
A loot chest spawned next to a chest in the build and now the loot chest is infinite, no cooldown, does not dissapear. Server 22, 18.2.2016 at 15:44

**Comment by Odnod** [comment]
This has been fixed.

**Comment by Trixter313** [comment]
@Odnod just wondering, what is your source? Thanks!

**Comment by AckroWynn** [comment]
This has indeed been fixed. I have checked it on the build server. Thanks!

**Comment by Trixter313** [comment]
Ok, glad to hear! =)
