### ISSUE TITLE
lost armour

### ISSUE THREAD

**Issue by linus301203** [Wynncraft/Issues#4170]
i have lost some of my armour after my wynncraft shut down to the normal minecraft page.

when i go in again i miss all my armour exept my chestplate i really don't now why please help

**Comment by Trixter313** [comment]
You're probably experiencing https://github.com/Wynncraft/Issues/issues/3153 where if you have a full inventory, armor sometimes gets deleted. Please direct any future comments to the original thread. Thanks!
