### ISSUE TITLE
Server Not Loading / Stuck In Black Box

### ISSUE THREAD

**Issue by SlashTheRekter** [Wynncraft/Issues#4171]
# Delete this line if you've searched for a duplicate issue first
When i join the server i spawn in the hub. i Choose a server to connect to and when i do i spawn in a black box made of wool. after awhile my armour loads but i never get out of the box.

Pleas help i really wanna play

Regards, Slash (fabwit)

**Comment by SlashTheRekter** [comment]
And i can stay in the box as long as i want. i dont get disconnected

**Comment by SlashTheRekter** [comment]
Upon further insection it seems to only be my archer class (my higest level class)

**Comment by Odnod** [comment]
just type /kill

**Comment by SlashTheRekter** [comment]
Thanks so much!
