### ISSUE TITLE
Horse Skins Not Working

### ISSUE THREAD

**Issue by BluKukki277** [Wynncraft/Issues#4172]
I donated a few days ago and i got everything, but my horse skins. My pets work and I can ride my horse, but the skeleton and zombie one wont work. if there is a need to fix the issue with my user it is BluCooqi thanks :D
![2016-02-18_20 13 35](https://cloud.githubusercontent.com/assets/17170795/13163554/25bcc35c-d67c-11e5-8313-44d8a42dcbd5.png)

**Comment by Trixter313** [comment]
Have you tried logging out and back in to see if that makes the skin work? Thanks!

**Comment by BluKukki277** [comment]
I'll try, sorry for not responding couldn't get on to test
