### ISSUE TITLE
STuck in hole on santa island

### ISSUE THREAD

**Issue by Mixo67** [Wynncraft/Issues#4173]
stuck in hole on santa island at x:1125 y:62 z:-3176 can u get me out of it and fix it so noone else falls in it

-xXSquirtleMixoXx

**Comment by TrashcanMan** [comment]
Do /kill with at least 3 soul points.

**Comment by Mixo67** [comment]
o ok

**Comment by TrashcanMan** [comment]
Yeah it should hopefully be fixed in the next map update, whenever that is

**Comment by Villageacules** [comment]
Fixed, moe should close soon.

**Comment by Moe-Ronickah** [comment]
Fixed.
