### ISSUE TITLE
Finished WynnExcavation Site A (wasn't rewarded)

### ISSUE THREAD

**Issue by HaveThomeCandy** [Wynncraft/Issues#4175]
I love Wynncraft, don't get me wrong, but I've spent 2 days on this mission because my computer is crap and FPS drops like flies when I'm in dungeons.
Well, I finally get to the final room with the giant crystal thing and I look up that I need to do nothing else, just to go and talk to Vade again to get my rewards and guess what? It glitched out on me to I can't complete the quest!!
I talk to Vade and he yell at me and asks if I have the translated text from Tesha yet (which, SPOILER ALERT, I did. he has the translated text with him, that's why I'm exploring the site!)
 
Please help, I don't want to spend another two days doing the parkor to redue it.

~ HaveThomeCandy

**Comment by Trixter313** [comment]
Try typing /fixquests to see if it returns any vital quests items.

**Comment by yoctomentric** [comment]
This happened to me too! And I can't redo the quest because I dont have the tablet that needs to be translated, obviously! So im stuck, knowing how to complete and having completed a difficult quest, but no reward!

**Comment by HaveThomeCandy** [comment]
I tried /fixquest, but it gives me old quest items that I don't need.

**Comment by BlueThunder25** [comment]
You must go and kill the pharaoh and then return the item to vade again
