### ISSUE TITLE
account problem

### ISSUE THREAD

**Issue by Magnetose** [Wynncraft/Issues#4176]
i was playing my warrior and i had to afk to go to dinner and when i came back i was disconected and i gone back and everything in my inventory is gone was gone and replaced by oak wood wpears and i had no armor anymore and my skin is gone it was default but i am still the same level and location in Nesaak but when i checked my archer (my second class) and it was completely fine with everything i had before and my warrior's enderchest is fine with all the things i originally had inside of it but main inventory is gone and replaced by 7 oak wood spear 
please help me restore all my items i had

**Comment by AckroWynn** [comment]
You are not able to get your items back, because there is a no refund policy. I assume you were killed in Nesaak several times, therefore lost all items. Some nice people in Detlas might help out if you ask nicely! ;D

**Comment by Magnetose** [comment]
<img width="1280" alt="screen shot 2016-02-19 at 8 03 46 pm" src="https://cloud.githubusercontent.com/assets/17336099/13175838/3740a7a2-d748-11e5-8519-ccfc8ce75e63.png">
