### ISSUE TITLE
Boat Merchants Missing & Unlisted

### ISSUE THREAD

**Issue by Crushtoe** [Wynncraft/Issues#4178]
Multiple Boat Merchants are missing, including: 

1. Bear Zoo's Boat Merchant
2. Santa's Island's Boat Merchant
3. Mage Island's Boat Merchant
4. The Boat Merchant on the river to the east of the Nivla Forest
5. Boat Merchant at ~X:402 Z: -3209

Additionally, Selchar has no boat merchant icon on the map, but has one in-game.

**Comment by Odnod** [comment]
A lot of things on the map are outdated. They have been like this for a while.

**Comment by DarkDemonDragon** [comment]
This is less of a bug and more that the map is just incomplete. They update the map periodically so it's only a matter of time before it's fully updated.

**Comment by Moe-Ronickah** [comment]
Thanks for the report!  I've passed it on.

**Comment by Moe-Ronickah** [comment]
Actually, some of the merchants sometimes go on vacation.  Swim for it, carry a tp scroll on you at all times, or switch servers/worlds.  It's known and being looked into.
