### ISSUE TITLE
Cant leave guild

### ISSUE THREAD

**Issue by Jobili** [Wynncraft/Issues#4179]
Everytime i do /guild leave a sign appear, I type yes, i lose my 3 souls and i'm still in the guild...

http://www.noelshack.com/2016-07-1455907579-2016-02-19-13-45-35.png
http://www.noelshack.com/2016-07-1455907590-2016-02-19-13-39-13.png

**Comment by Trixter313** [comment]
I'd give it at least 24 hours to confirm that it is really a bug because guilds can take time to update after a change is made, but there seems to be a lot of guild related bugs going on right now so I wouldn't be surprised if it were really a bug. Report back in ~21 hours please, thanks!

**Comment by Jobili** [comment]
Alright thanks

**Comment by Jobili** [comment]
Still cant leave the guild... If someone could do it for me my IGN is Jobili

http://www.noelshack.com/2016-07-1455986626-2016-02-20-11-41-38.png

**Comment by Trixter313** [comment]
Ah, I see that you've changed your name a couple of times. That makes this a duplicate of https://github.com/Wynncraft/Issues/issues/3908

Please direct any future comments and follow the original thread to stay updated on the status of the issue. Thank you!
