### ISSUE TITLE
There is a way to get rid of quest items (such as the breathing helmet)

### ISSUE THREAD

**Issue by DubTheDev** [Wynncraft/Issues#4185]
While opening a loot chest, you can place your quest items inside of it and exit out. Once you exit out of the chest, the chest will break and the quest item will be gone. This could be serious, so please fix it.

**Comment by Odnod** [comment]
It is not serious, as you can just type /fixquests to get them back. I actually reccomend deleting your quest items until you need them again.

**Comment by Cyraxien** [comment]
when your inventory is not full and you throw out a quest item, in the chat comes the text that you need your quest items later again. but when you threw it out  to put an other thing on this slot when your inventory is  full it will bugg away. so i lost my quest item: saylors brothers ashes
Ingame name: Cyraxien
please fix this bug

**Comment by Odnod** [comment]
@Cyraxien as I said earlier, just type /fixquests.

**Comment by DarkDemonDragon** [comment]
What do you mean by loot chest? The daily chest or any loot chest found across the world? This is strange as normally you cannot move quest items around while looking in a chest to prevent this sort of thing from happening. In any case, if you ever lose a quest item just do /fixquests and you'll get back any missing quest items.

**Comment by Moe-Ronickah** [comment]
ANY loot chest that is closed, whether or not it has an item in it, will be destroyed.  ANY item placed in any kind of loot chest will be destroyed when the loot chest is closed.  This is an intentional game mechanic.

**Comment by DarkDemonDragon** [comment]
@Moe-Ronickah however, this is still a bug. Previously, you couldn't move quest items at ALL while opening chests. It would snap back into the original spot with the red text saying you'll need it for future quests.
