### ISSUE TITLE
Bug for me

### ISSUE THREAD

**Issue by nMarshmallosweet** [Wynncraft/Issues#4187]
I am got caught by a block at x:700, y:142, z:-2167 . I can't move. Please help me or kill me.
I tried to use a teleportation scroll but it didn't work.

**Comment by Odnod** [comment]
Type /kill with 3 or more soul points

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/4184

Please direct any future comments to the original thread and try not to double post again. Thanks! =)
