### ISSUE TITLE
Santa looks a bit odd

### ISSUE THREAD

**Issue by aramaril** [Wynncraft/Issues#4188]
so my friend and i are doing the Craftmas quest and found the "santa" guy and he looks a bit odd. think he could use a texture update
![santa](https://cloud.githubusercontent.com/assets/17123618/13196249/b7e220ac-d78e-11e5-8a1e-0621d0d5807d.png)

**Comment by Odnod** [comment]
Yeah this is well known and had been around for a while

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/4003

Please direct any future comments to the original thread. Thanks!
