### ISSUE TITLE
Out of My Mind Final Stage No Dialogue

### ISSUE THREAD

**Issue by Alexicon1** [Wynncraft/Issues#4189]
After defeating Ozio, I can't do complete the quest, because I get blank dialogue from Ariodo.

**Comment by Dar-krusos** [comment]
You must go back to Troms and talk with Buendo. Reminder that if you are stuck, use the [wiki guides](https://wiki.wynncraft.com/index.php?title=Quests).

**Comment by Alexicon1** [comment]
Thanks, stupid me realised that after I had done it.
