### ISSUE TITLE
Item Bugged (Dragon Skin Chestplate)

### ISSUE THREAD

**Issue by Vyst** [Wynncraft/Issues#4190]
My chestplate (Dragon Skin) got bugged out. There's no stats assigned to it.

http://prntscr.com/a5punw

**Comment by Alexicon1** [comment]
That happens when you are in a merchant screen, items seem to revert to what they were before the stat change. Its ok, it should fix itself

**Comment by Vyst** [comment]
Nope, I've relogged, wore it and took it off. It doesn't change back.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!
