### ISSUE TITLE
You can get rid of quest stuff

### ISSUE THREAD

**Issue by BlackPanderz** [Wynncraft/Issues#4191]
you can get rid of the items by throwing them into the daily loot chest it deletes them and i may or may not have got rid of my climbing helmet and now i need it

**Comment by Alexicon1** [comment]
if you need it, type /fixquests to return the helmet

**Comment by Odnod** [comment]
also a copy of #4185

**Comment by Trixter313** [comment]
Please direct any future comments to the original thread, linked above. Thanks!
