### ISSUE TITLE
Trying to use a shout then using another shout will lose you a shout.

### ISSUE THREAD

**Issue by TheIvyX** [Wynncraft/Issues#4192]
So I tried using a global shout, then realized I did not want to. I thought I could go through /use and use another shout to cancel it out, then finding out it didn't work. I looked back in the /use menu and saw that I had lost a shout.

**Comment by Alexicon1** [comment]
I don't think it is a glitch, the server just figured you were using a shout so taxed you for it.

**Comment by Odnod** [comment]
yeah you cannot retract a shout once you first click it, this is not really a glitch.

**Comment by Trixter313** [comment]
I agree with the above people and since Wynncraft has a strict no refunds policy there's not much we can do about the lost shout. Next time, make sure you want to shout and think about what you're going to say before you activate a shout. That should prevent this from happening again. =)
