### ISSUE TITLE
stuck in ground??

### ISSUE THREAD

**Issue by yeeaah** [Wynncraft/Issues#4193]
# Delete this line if you've searched for a duplicate issue first

I was in house of twain. I have no tp scrolls and i got stuck underneath with all the redstone and commandblocks. I got off my horse and tped under. Please help?

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will teleport you to the nearest visited town (Most likely Nesaak). Thanks!

**Comment by yeeaah** [comment]
thank you
