### ISSUE TITLE
WynnExcavation Site C is glitched

### ISSUE THREAD

**Issue by treeyo** [Wynncraft/Issues#4194]
WARNING MAY CONTAIN SPOILERS FOR THIS QUEST
 

So I was doing the WynnExcavation Site C and I died by the guards behind the shard because of my stupid curiosity.  I get mad especially since I spawned in Almuj.  I get back to the volcano island and I go back to where I died I survive the guards and my quest book tells me to go back and talk to Excavator Placardus and I do.   Then it tells me that I need the purple crystal shard from Wynnexcavation B and I have the shard in my inventory.   I even typed /fixquests and it just added on to the stack I already had of the shards.  I personally love the WynnExcavation series and it kinda sucks how I can't finish it now. I also have some screen shots for you to see what I mean.
![2016-02-20_11 58 09](https://cloud.githubusercontent.com/assets/17358351/13197932/c9958d80-d7c9-11e5-8724-c39df84b5995.png)
![2016-02-20_11 58 12](https://cloud.githubusercontent.com/assets/17358351/13197933/cc26de82-d7c9-11e5-9a23-bd533b9ae883.png)

Thank you for your time

~treeyo

**Comment by Odnod** [comment]
Try running back through the quest.

**Comment by treeyo** [comment]
Ok I'll try

**Comment by TheIvyX** [comment]
Yeah I had the same problem, just go through the cave again until you get the red shard. Then go back to Placardus and you'll finish the quest.

**Comment by treeyo** [comment]
Yeah it worked, thanks for your guys' help! :D

**Comment by Trixter313** [comment]
Glad to hear!
