### ISSUE TITLE
Liquid emerald

### ISSUE THREAD

**Issue by Sarxo** [Wynncraft/Issues#4196]
ahmmmm i wanted gave a liquid emerald my friend i right clicked him then my liquid emerald vanished i clicked in the hotbar i relog but the emerald didnt come back ;-; can you help me ?

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so unless the item happens to reappear in you inventory, there's nothing we can do. I'd suggest clicking on every blank space in your inventory to see if it comes back. Hope this helps!
