### ISSUE TITLE
A Bug

### ISSUE THREAD

**Issue by BroBroSkope** [Wynncraft/Issues#4197]
My Bow...

I was in the house of twain (x:120,y:-342) and i was doing the quest. suddenly my bow was away and i have nothing to fight and cant go out. I want my bow back!! pls :( My ingame name is BroSkopeBro

**Comment by Trixter313** [comment]
Weapons don't usually just disappear so you most likely just dropped the item. Wynncraft has a strict no refunds policy so nothing can be done about the lost item. To prevent this from happening again, I'd suggest changing your drop key to something you're less likely to accidentally press. If you ask around someone might give you one of their bows. Thanks!

**Comment by BroBroSkope** [comment]
i am in the house and cant get out my bow was away
pls give it back :(

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will bring you to the nearest visited town. (In is case, Nesaak most likely)
