### ISSUE TITLE
Out dated item

### ISSUE THREAD

**Issue by wereout** [Wynncraft/Issues#4200]
# Delete this line if you've searched for a duplicate issue first
In my bank i have a Liquid Emerald, but i cant use it because its old. I've been around for a few years, and a lot has changed. Recently there was an update that changed weapons or something. On my mage class, i cant use my wand anymore because its outdated. The style of the stats is written differently than other wands. I really want to be able to use that wand D:

**Comment by Odnod** [comment]
you can fix your liquid emerald by trading it with the liquid merchant in Detlas. Could you post a screenshot of the wand?

**Comment by wereout** [comment]
![screen shot 2016-02-20 at 6 29 05 pm](https://cloud.githubusercontent.com/assets/17364363/13199590/ea9fe418-d7ff-11e5-8927-fd58b1ca190a.png)
im not sure if this is how you post images..

**Comment by Dar-krusos** [comment]
To convert old emeralds into new ones, go to Selchar where you'll find a converter in the bank. About the wand, there is really nothing you can do about it, so just chuck it ou.

**Comment by Trixter313** [comment]
@Dar-krusos The converter merchant is actually no longer in Selchar.

**Comment by Dar-krusos** [comment]
What ....
