### ISSUE TITLE
Mummy Tomb bug

### ISSUE THREAD

**Issue by RMH0131** [Wynncraft/Issues#4201]
name: RMH0131
lv: 37
class: Assassin

Problem: I tried to walk up to the tomb and it says "As you approach the tomb, your fears become greater, and you decide to stay away from this place... for now..."  So I looked it up on wiki and it said I needed pink wool. I got some pink wool and went back to the tomb, but it still said the same thing. what do I do? it didn't mention anything about this on the wiki page. PLS HELP MEH

**Comment by SpeederSam** [comment]
Did you open the quest for the tomb? Talk to the person on the other side of Almuj to start it if you have not.

**Comment by Moe-Ronickah** [comment]
Please check your Quest Book and see what it tells you to do.

**Comment by BlueThunder25** [comment]
You must also give the pink wool the the NPC outside of the tomb

**Comment by Moe-Ronickah** [comment]
Best guess is that @SpeederSam figured our what @RMH0131 was doing wrong.
