### ISSUE TITLE
loosing items

### ISSUE THREAD

**Issue by joulupukki21** [Wynncraft/Issues#4203]
i have a issue with my items. my items just disappear sometimes. like today i lost my legendary helmet. i have lost jester ring weapons and armor. they just disappear from my inventory while i am playing pls help me if you've searched for a duplicate issue first

**Comment by Moe-Ronickah** [comment]
"pls help me if you've searched for a duplicate issue first"
This is something that you are supposed to do, first.  If you had, you would have found many duplicates of this same issue.

Unfortunately, WynnCraft has a no-refunds policy, for several reasons, and your items cannot be refunded.
