### ISSUE TITLE
Corrupt File Data?

### ISSUE THREAD

**Issue by pRizeD** [Wynncraft/Issues#4205]
Alright so I stopped playing a long time ago and now I am back, but whenever I try to select a class it crashes my game.. I am going to just believe that my data file is corrupted and might need to be deleted, and to be honest I dont mind at all if its the case. Can someone please help me ?
My IGN (oldest to current)
monsterbill212
vGina
c0cky

**Comment by pRizeD** [comment]
I realized I can actually delete my classes, and now its actually starting to work. Its fixed lol

**Comment by Trixter313** [comment]
Good to hear!
