### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by InimiciVivent** [Wynncraft/Issues#4206]
While I was standing at the Nemract bank, I logged off to switch to another server, However when I logged on to the other server the message "you do not have permission to enter this area" appeared in chat. Somehow I now got teleported into a dark 5x5x5 hole at the coordinates: X: -975 Y: 62 Z: -1691 which I can not leave, I am basically stuck here. I have no idea how to get out of here or what to do.
-InimiciVivent

**Comment by InimiciVivent** [comment]
I did /kill and got out to Ragni, while I was at nemract. now i only got 1 soul point left. I still am confused about what has happened.

**Comment by Odnod** [comment]
Nemract bank is sometimes broken like that. The box is the class selection area, in which people sometimes get stuck. The nearest town that you have been to to the class selection area is Ragni.

**Comment by InimiciVivent** [comment]
Thanks Odnod for your explanation x3

**Comment by Odnod** [comment]
No problem.
