### ISSUE TITLE
Pirate Town's npcs

### ISSUE THREAD

**Issue by gabriel338PT** [Wynncraft/Issues#4210]
So, recently, with my level 39 warrior, i was heading to llevingar, and i got to pirate town, and i didn't found some npcs!
There wasn't item identifiers and the esmerald merchants! 
Sadly i couldn't take a print, but i hope this will be fixed.

**Comment by Trixter313** [comment]
Duplicate of #3272 

Please direct any future comments to the original thread. Thanks!
