### ISSUE TITLE
Lost my black horse while changing lobbys

### ISSUE THREAD

**Issue by apensnotje3** [Wynncraft/Issues#4211]
i was trying to switch lobby when i arrived in the other lobby my black horse was gone from my inventory

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so there's nothing we can do to return the lost item but it sounds like it was accidentally dropped so to prevent this from happening again I suggest changing your drop key to something you're less likely to accidentally press. Hope this helps!
