### ISSUE TITLE
I can't get my sexy skin to work on this server

### ISSUE THREAD

**Issue by Leg420** [Wynncraft/Issues#4215]
When I log in I have an Alex skin whai pls help

**Comment by Trixter313** [comment]
Try taking all your armor off, doing /class, then put your armor back on.

**Comment by Trixter313** [comment]
Did this help at all? Thanks!

**Comment by Dar-krusos** [comment]
Are you on the latest version of Minecraft and using the latest version of the launcher?

If so, then are you using any mods? If anything, it could just be a random occurence and will resolve itself some time in the future. Let's hope this isn't a permanent thing ;)

**Comment by Moe-Ronickah** [comment]
This is an off-and-on issue that has been resolving itself within 2 to 3 days for affected players.  I'm closing this for two reasons: 1) it's known to resolve on it's own, and 2) no response from the OP for more than a month.

If anyone else reports this as happening a lot to them, we can reopen this issue as the original thread.
