### ISSUE TITLE
I lost me Horse and Weapon be a Glitch..

### ISSUE THREAD

**Issue by ingmarv2** [Wynncraft/Issues#4216]
I lost me Black Horse And Legendary Chear Be a glitch in a chest

I shift clickt the chest and me items get in there and i lefted the chest and i lost al me items i am freaking out now

I can proof that i had the horse and the weapon... ..

Is there any change that i get it back ?? Time of the bug 20:36 Place Nesaak

Mc Name Ingmarv2     Rank Vip+

**Comment by ingmarv2** [comment]
(Chit only proof of the horse not of me Legendary weapon) ;(

**Comment by TrashcanMan** [comment]
Why would you put your items into a loot chest?

**Comment by ingmarv2** [comment]
Me minecraft was glitching ....

xD But yeaah..

**Comment by ThunderRemix** [comment]
No refunds, sorry

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so unfortunately there's nothing we can do about the lost horse. Please try to be more careful next time to prevent this from happening again. Thanks!
