### ISSUE TITLE
xp bonus

### ISSUE THREAD

**Issue by OMGitsTomix** [Wynncraft/Issues#4217]
This is my stuff:
http://nahraj.to/g/sTR
Helmet:18 xp bonus
Chestplate:13 xp bonus
Leggings:0 xp bonus
Boots:33 xp bonus
Bracelet:31 xp bonus
Necklace:32 xp bonus
Thats 127 xp bonus,but my stats are saying i have only 82 xp bonus...
I know the Jeseter Set gives -45 xp bonus (127-45=82...) but I have only Jeseter Bracelet and Necklace,not the whole set but I still have the -45 xp bonus,how to fix it? Is it bug or its only me? (I tried reloging so many times,equiping my armor again and again,nothing worked.)

**Comment by Alexicon1** [comment]
I do not completely get it. But I believe that the jester items share out the xp negation, and the items have logged and it has taken away the xp. I would suggest removing all jester items and see if the xp bonus changes.

**Comment by OMGitsTomix** [comment]
All my items have together 127 xp bonus,and the -45 xp bonus should give only when I have the whole Jeseter set,the jeseter necklace and bracelet gives me together 63 xp bonus and -45 xp bonus so I get only 18 xp bonus from it...

**Comment by Dar-krusos** [comment]
No, the Jester Set bonus can activate with only one item. Wearing more Jester items will change the bonus (larger negative number to compensate for each Jester item's high xp bonus).

**Comment by yeeaah** [comment]
@Dar-krusos is right

**Comment by Moe-Ronickah** [comment]
Resolved.
