### ISSUE TITLE
Bugs with armor skin and green powder

### ISSUE THREAD

**Issue by Superstar202** [Wynncraft/Issues#4218]
So for some reason the armor doesn't edit onto my skin, and when I did the shrine in the forest to get the green powder, it didn't give me the item even though I had next to nothing in my inventory.

**Comment by TrashcanMan** [comment]
There's a 4-hour cooldown for powder relics, are you sure you waited long enough?

**Comment by Superstar202** [comment]
I didn't get it the first and only time I did it.

**Comment by DarkDemonDragon** [comment]
I think that Powder Relics don't give Powders until the Powder Update comes out.
