### ISSUE TITLE
Resource Pack

### ISSUE THREAD

**Issue by BlizzardFalme** [Wynncraft/Issues#4219]
Ok so I showed my friends Wynncraft, but the resource pack didn't work for them. I made sure that they enabled server resource packs, but it didn't help.

**Comment by Dar-krusos** [comment]
Try getting them to remove and re-add the server to their server list. If that doesn't work, get them to update their MineCraft version AND launcher.

**Comment by Trixter313** [comment]
Is the issue still happening?
Also, what OS are you using?
Thanks!

**Comment by Moe-Ronickah** [comment]
For further reference, this issue can be resolved by the following the instructions at the Minecraft Wiki at  http://minecraft.gamepedia.com/Tutorials/Loading_a_resource_pack.
