### ISSUE TITLE
Deleting characters

### ISSUE THREAD

**Issue by Driam69** [Wynncraft/Issues#4221]
# Delete this line if you've searched for a duplicate issue first
Ok me and my friends wanted to do an assassin play through together but his character slots are full and he can't delete them :(  please help

**Comment by Odnod** [comment]
Classes do not delete immediately, and can take a while in some cases to be deleted.

**Comment by Driam69** [comment]
What do u mean by not immediately

**Comment by BlueThunder25** [comment]
It may take up to a few hours or sometimes a day or two

**Comment by BlahBlah161616** [comment]
Or 3-4 minutes.

**Comment by BlueThunder25** [comment]
Please close this thread if the issues/bugs have been resolved

**Comment by BlueThunder25** [comment]
@BlahBlah161616 Please close this thread if the issues/bugs have been resolved
