### ISSUE TITLE
Spell damage %

### ISSUE THREAD

**Issue by Perifidite** [Wynncraft/Issues#4222]
I think that spell damage% is not working. I have a total of 737 raw Spell damage, and I also have a 39% spell damage helmet. According to my math that should add on 287.4 more spell damage. Now I tested damages, but my damage didn't go up by the expected numbers. So then I tried out tests to from wearing the helmet that gave me 39% spell damage to wearing nothing. I did the same amount of damage with or out without the helmet.

**Comment by Dar-krusos** [comment]
Try changing servers after wearing the helmet. Sometimes lag causes several servers to not update your stats.

When you find a server that changes your damage, try applying the percentage before the raw damage, and see if you get correct calculations.

**Comment by Perifidite** [comment]
You really think I haven't tried that? I've tried restarting my PC... Can
you do separate tests on your own to confirm that spell damage% is not
functioning properly?

**Comment by Dar-krusos** [comment]
Can I ask exactly where you got your raw spell damage stat from?

**Comment by Perifidite** [comment]
-300 from full jester set bonus
-293 for millenium
-144 from boots of blue stone

**Comment by Moe-Ronickah** [comment]
@Perifidite , is this still an issue? If not, did you do something to fix it, or did it resolve on it's own?

**Comment by Perifidite** [comment]
idec anymore
