### ISSUE TITLE
Wynnexcavation site B teleported me into a wall

### ISSUE THREAD

**Issue by lexjo** [Wynncraft/Issues#4223]
# Delete this line if you've searched for a duplicate issue first
I reached the end of the wynnexcavation site B cave and stepped into the darkness, this then teleported me into a wall and I can't get out, I've tried using a scroll and it won't work.

Please help!

-lexjo

**Comment by lexjo** [comment]
Never mind, I just realised I could do /kill

**Comment by Odnod** [comment]
If you have resolved your issue, ease close it :)
