### ISSUE TITLE
Jester accessories % rate

### ISSUE THREAD

**Issue by gettodachopa** [Wynncraft/Issues#4224]
Issue getting jester accessories from chests

Players above level 72 are getting 98% of the time jester bracelets, 1% jester rings and 1% jester necklaces

Players under level 72 and above level 52 are getting 98% jester rings 

I think it should be like 33% of each item (bracelet, necklace, ring) for players above level 72

I'm level 78 and I rarely get jester rings or necklaces, and I get tons of bracelets

And this is the main reason why jester rings are ridiculously overpriced (10/15 le for a razonable jester ring)

**Comment by yeeaah** [comment]
I dont think they can really fix this since it is with loot chests. It depends on level so if they made it random, you would have lv 1's getting mythics lv 100 and lv 100s getting an oak spear. Besides, i am lv 55 and i get a ton of necklaces and rings, a mixure

**Comment by TrashcanMan** [comment]
Do you actually have conclusive proof of this, or is it just based on your experience or the experiences of two or three people you know? It might just be really bad luck.

**Comment by gettodachopa** [comment]
I doubt it's bad luck, I'm pretty sure this happens to all players above level 72, as explained in the first post

**Comment by Moe-Ronickah** [comment]
As there is no evidence for this issue, I am closing it.
