### ISSUE TITLE
Belua the Unquenchable's teleporter doesn't work

### ISSUE THREAD

**Issue by TheIvyX** [Wynncraft/Issues#4225]
The mini dungeon in Thanos for Belua the Unquenchable doesn't teleport back. I tried going in, then going back out and then in again, which failed every time. I had to suicide to leave :/

**Comment by Trixter313** [comment]
Have you tried switching to another world? Sometimes things get temporarily broken on a few servers but work on others.

**Comment by TheIvyX** [comment]
I tried that, didn't work :/ Once again I had to suicide to leave because mages can't teleport back up

**Comment by TheIvyX** [comment]
Any updates for this?

**Comment by Trixter313** [comment]
No updates currently, unfortunately. Most of the contributors on the issue tracker aren't informed of updates and can't directly contact any admins to make sure they know about it and are working on it. It's very frustrating.

**Comment by Moe-Ronickah** [comment]
Fixed.
