### ISSUE TITLE
Life/Mana steal wont working

### ISSUE THREAD

**Issue by Equipa2** [Wynncraft/Issues#4227]
Im a archer lvl.84 and i have 61/2s life steal and 1/2s mana steal, but when is use a arrow strom nothing appens.
Equipa2

**Comment by Odnod** [comment]
Life and Mana steal no longer steal per 2 seconds but rather on a percent chance based on attack speed.

**Comment by DarkDemonDragon** [comment]
Please close this as this is not a bug, but an intentional feature of the game.
