### ISSUE TITLE
Disappearing emeralds

### ISSUE THREAD

**Issue by crazydud24** [Wynncraft/Issues#4231]
# Delete this line if you've searched for a duplicate issue first
Ok so I was going to make a new and I talked with the guy. It was taking a while for the naming screen to appear so I was sorting my inventory and I went to move the 5 le you need to make a guild when he pulled up the naming sign and I droped them all. Within the next 20 ish seconds when I tried to get out of the screen to get them, they disappeared, gone. And I am really upset becouse it took me a week to farm up the le

**Comment by crazydud24** [comment]
I just went through a lot of the bug reports and I see no others like this but I don't know how to remove the I didn't check for other reports like this one line

**Comment by BlueThunder25** [comment]
Wynncraft has a strict no refunds policy so unfortunately there's nothing wynncraft can do about the lost Emeralds.

**Comment by DarkDemonDragon** [comment]
@crazydud24 I'm pretty sure this has been reported.

**Comment by Moe-Ronickah** [comment]
"It was taking a while for the naming screen to appear"  I'm sorry, but whenever there is a delay of any kind, that is a big clue that some type of lag is occurring.  If you could move, but the server was not reacting, it was server lag.  All of the time that you spent sorting your inventory was ticking along on the server, so when the server display caught up, your 5LE had been on the ground for a long time, long enough to disappear.  Remember this in the future, especially if you are around mobs or trading with someone.

The WynnCraft admins are working on reducing lag all of the time, so there really is nothing to report further.
