### ISSUE TITLE
Skill point bug

### ISSUE THREAD

**Issue by trickstini** [Wynncraft/Issues#4234]
how can i fix this? it says i only have 64 and when i put more points into it it still says 64, however if you look under the % it says 76, so do i have all 76 points or only 64?
![2016-02-23_15 33 12](https://cloud.githubusercontent.com/assets/17256464/13267415/c481bf00-da42-11e5-89a7-52f89524bad4.png)
![2016-02-23_15 33 19](https://cloud.githubusercontent.com/assets/17256464/13267416/c60043ba-da42-11e5-9920-c8be6d72e3b7.png)

**Comment by yeeaah** [comment]
its supposed to be like that. as long as the number in the the thing says 76 points your good. 64 items in a stack remember. cant go past that

**Comment by trickstini** [comment]
ahh icicici ty!
