### ISSUE TITLE
Loss of items

### ISSUE THREAD

**Issue by Alex097** [Wynncraft/Issues#4237]
After the update recently, my bank account has been a bit weird. But just as I thought it was all stable, BOOM the stuff I recently put into my ender chest is gone. My items messed up and I lost my crystal with 3/4 mana and 64% reflection, also lost my 3/4 mana and 37% ethereal and my 35% BadWolf. Please fix this or atleast give me back my items

**Comment by Odnod** [comment]
Sorry, but Wynncraft has a strict no-refunds policy.

Also, as this is essentially a clone of #4235 please redirect all additional responses to that post.
