### ISSUE TITLE
Canyon Condor Bug

### ISSUE THREAD

**Issue by Crazyj704** [Wynncraft/Issues#4240]
#4236 When I get to the end of the mine near Old Man Jenkins, the gold does not appear on the ground. I have waited about 10 minutes and switched between servers and still it is not there.

**Comment by Odnod** [comment]
So it seems this issue is still prevalent. This has been an problem throughout the day and I am sure it is being solved asap.

**Comment by DarkDemonDragon** [comment]
Duplicate of #4236 Please close this and follow the original.
