### ISSUE TITLE
bug for the mission (the ultimate weapon)

### ISSUE THREAD

**Issue by ChoAbbg** [Wynncraft/Issues#4243]
the mission needs u to gather some wetstone in the river
i been waited for an hour and there still hav none to spawn
i tried to join other server, but the same problem happened
![2016-02-24_15 02 43](https://cloud.githubusercontent.com/assets/17446819/13277999/c7840e22-db07-11e5-97f3-3218e25880c7.png)

**Comment by DarkDemonDragon** [comment]
This is a very widespread issue that affects ALL items that are supposed to spawn. The Admins are aware of the situation and are working on it. Please check again in a few hours or so.

**Comment by Odnod** [comment]
Also this is a duplicate of #4236, please close this and put any additional comments on the original thread.
