### ISSUE TITLE
missing items for two  quests

### ISSUE THREAD

**Issue by natourod1** [Wynncraft/Issues#4244]
hello, so,
My account name is natourod1 and I have a big problems with two quests with my archer level 58 now.
The first quest is underice and when I have finish underwater, i didn't drop the [Climbing helmet] (not in my stuff or in my ender chest) , so I can't finish this quest .
The second quest is the shadow of the beast. when i get back 6 [Marsh Robur] to Tolem, i didn't receive (or I missed but i don't know how) the [Stringy Hair], but i have the two other items but i can't finish the quest, i need the three items.
If you can help me please, it can be nice . 
Thank you for  read my message.

**Comment by DarkDemonDragon** [comment]
For Underice you need the Breathing Helmet NOT the Climbing Helmet
For Shadow of the Beast do /fixquests if you somehow deleted the Stringy Hair. If you don't get it back from that it may be in your inventory of your other classes, or in your bank somewhere.

**Comment by natourod1** [comment]
okey thanks and i have verified I have the climbing helmet but not the breathing  ^^' thank you very much!

**Comment by DarkDemonDragon** [comment]
No problem! If your issue has been fixed please close this. If you have any further questions/issues related to this feel free to ask.
