### ISSUE TITLE
spider cave saccharum

### ISSUE THREAD

**Issue by chrisko131** [Wynncraft/Issues#4246]
idk y,there is no saccharum spawning at da pit of da spider cave.

**Comment by DarkDemonDragon** [comment]
Please provide screenshots as you may be at the wrong location. If no saccharum spawn then I recommend switching worlds.

**Comment by NeyRisson** [comment]
I have the same problem,([this is the right place](http://www.noelshack.com/2016-08-1456324375-minecraft-1-8-24-02-2016-15-19-06.png))
I switch worlds many times but nothing

**Comment by DarkDemonDragon** [comment]
Duplicate of #4236 Please close this and follow the original
