### ISSUE TITLE
Temple Of Legends (Quest)

### ISSUE THREAD

**Issue by GodlySkull** [Wynncraft/Issues#4248]
# Delete this line if you've searched for a duplicate issue first
So there is a part where you have to get ligning dust. it does not spawn at the place it should be.

**Comment by Odnod** [comment]
Duplicate of #4236 please close this and put any additional responses on the original thread, thanks.

**Comment by DarkDemonDragon** [comment]
Duplicate of #4236 Please close this and follow the original
