### ISSUE TITLE
What's the point of this maze

### ISSUE THREAD

**Issue by TheIvyX** [Wynncraft/Issues#4253]
There's a maze in between Thesead and Kandon-Beda. I'm assuming it's unfinished or just not worked on very well because:

The end of the maze has two exits, which the right one doesn't even work: http://imgur.com/MaOe3mP

The piston door, well, is just a piston door (I expected more) and doesn't take the middle block: http://imgur.com/DJfmPin

There's a note that is too long to read, literally: http://imgur.com/s0raxqv

I don't want to give away coordinates since it might be a spoiler, but I can if needed.

**Comment by TheIvyX** [comment]
Never mind, the right side does work (didn't work in the first place due to lag), but they both just lead to the entrance of the maze.

**Comment by Odnod** [comment]
If this is resolved, you should close it.

**Comment by TheIvyX** [comment]
I just don't see a point in this maze though. It seems to serve no purpose and thought it was a bug because it shouldn't have been accessed.

**Comment by RedMorcus** [comment]
I think it may be from an unused quest.

**Comment by Odnod** [comment]
Oh this leads to the air minidungeon or something

**Comment by TheIvyX** [comment]
It's the entrance behind a Loot Tier 4 chest. The cave is at 580/28/-4624. If it were one of the elemental mini-dungeons, then I would've seen a monster's name or two. I didn't see any :/

Plus the water elemental dungeon is bugged, as the exit does not work and doesn't teleport out. I opened a thread for this but it's not closed.

**Comment by Odnod** [comment]
Then this is most likely just an easteregg
