### ISSUE TITLE
Archper and Friends

### ISSUE THREAD

**Issue by LikelyNoob** [Wynncraft/Issues#4254]
Two things: One, I see the green particle effects around where Archper SHOULD be on my screen
(btw i started the mummy quest) But not the actual Archper...
Two: /friends does not seem to show an online friend... that is standing right next to me... that /friends list does...

**Comment by Odnod** [comment]
A bunch of bug fixes are happening right now and as a result the server is pretty messed up. Things should be back to normal eventually.

**Comment by NotHyper** [comment]
Can't get past the Caravan Driver ;-;
