### ISSUE TITLE
Can't see Quest Villagers!

### ISSUE THREAD

**Issue by Venomous321** [Wynncraft/Issues#4255]
I have recently been playing WynCraft and all of a sudden all the Quest villagers disappeared, rendering all the items that I have collected useless, and me not been able to complete quests! Please help or fix!

**Comment by Odnod** [comment]
@Venomous321 This is a server-wide glitch for everyone and may be linked to #4236. A bunch of bug fixes are happening right now and as a result the server is pretty messed up.

**Comment by Venomous321** [comment]
thank yo. do you know how to fix it?

**Comment by Odnod** [comment]
Also this is a duplicate of #4254 you should close this one and put additional comments on the original.
