### ISSUE TITLE
I lost my gear cause of server problems

### ISSUE THREAD

**Issue by crazy0o07** [Wynncraft/Issues#4256]
The server was having some troubles and it kept on logging out people and when i logged back in i lost lots of stuff, one being my leggings which are katke, Ethereal wand, locrian dagger, legendary lvl 47 helm and lvl 38 leggings (don't know their names). What am i suppose to do!?

**Comment by DarkDemonDragon** [comment]
Do you remember what the chat said when this happened? Was it something like:
"Armor Requires 15 Dexterity"
in red text?

**Comment by Moe-Ronickah** [comment]
When you see people being logged out, use the /hub command, immediately, as this is a sign of a server-wide error.

I'm sorry, but WynnCraft has a no-refunds policy..
