### ISSUE TITLE
Mage- used teleport in Almuj, now I'm stuck.

### ISSUE THREAD

**Issue by Racoln** [Wynncraft/Issues#4261]
So, I was in Almuj, looking for a quest NPC, and I was teleporting around, and found my head stuck in a block. I can get out if I shift but other than that, nothing. Just the inside of a sandstone block, and no mobility. My coords are: X: 926.3 Y: 76.375 Z: 1970.3
Any help? Thanks!

**Comment by Odnod** [comment]
type /kill with 3 or more soul points to free yourself.

**Comment by Racoln** [comment]
Thank you!

**Comment by Odnod** [comment]
Please close the issue if it has been resolved :)
