### ISSUE TITLE
quest bug 

### ISSUE THREAD

**Issue by Jolerty** [Wynncraft/Issues#4262]
When In quest progress minecraft just crash and quest bug. I can abandon this quest and clear him again ? 

![image](https://cloud.githubusercontent.com/assets/17461446/13305872/d4971448-db6f-11e5-937f-88af12b9ff4d.png)

![image](https://cloud.githubusercontent.com/assets/17461446/13305880/de61fcb8-db6f-11e5-8964-d4f55ee4dcb3.png)

**Comment by Odnod** [comment]
Go to the nearby hive of rats and give him the golden ring.

**Comment by Jolerty** [comment]
I cant give him golden ring i have 3

**Comment by Odnod** [comment]
Did you go into the nearby cave and kill the giant rat?

**Comment by Jolerty** [comment]
all right i clear him but i have new problem I cant drop  saccharum from spider cave

**Comment by Moe-Ronickah** [comment]
Your new issue is a duplicate of #4236.  Please follow this issue there.
