### ISSUE TITLE
Hourglass sand not spawning

### ISSUE THREAD

**Issue by iceswordluma** [Wynncraft/Issues#4264]
The hourglass sand in Selchar does not spawn, rendering the sister city quest impossible. When you go to the hourglass, no sand spawns anywhere on any server.

**Comment by iceswordluma** [comment]
Nor do the sunflower seeds seem to be spawning for Aldorei's Secret Part I in Aldorei valley.

**Comment by Odnod** [comment]
duplicate of #4236, please close this post and put and additional comments on the original topic.
