### ISSUE TITLE
Out of the map glitch

### ISSUE THREAD

**Issue by blinkschool** [Wynncraft/Issues#4268]
I was playing wynncraft doing the santa mission and i was on my boat going to santa but then i fell through the map now im under the map and cant get up I dont have a scroll or anything Could someone please set me back to detlas/nemract?

**Comment by MonsterShark** [comment]
You can do /kill to killyourself thus respawning to the closest respawn point. Keep in mind you lose 2 soul points.

**Comment by DarkDemonDragon** [comment]
@blinkschool whenever you are stuck anywhere and wish to go to the nearest town always use /kill UNLESS you have less than 3 SP. If you only have 1 or 2 SP you will lose all your items upon respawning.

**Comment by blinkschool** [comment]
Thankyou very much i was worried i had to start all over again
