### ISSUE TITLE
 Glitch/Bug?

### ISSUE THREAD

**Issue by SoulAyce** [Wynncraft/Issues#4274]
So,  i was playing wynncraft and wanted to do the Animal dungeon. What happend was that when i hit the boss in to the corner/wall the boss would glitch trough  the wall and be outside the ring,
![2016-02-25_16 44 57](https://cloud.githubusercontent.com/assets/17478065/13325401/f2d7313c-dbe1-11e5-9be6-60f72be140b5.png) this made it a little harder to deafeat the boss

**Comment by Odnod** [comment]
War scream can knock mobs through walls, just type /class to reset the arena

**Comment by SoulAyce** [comment]
Oh Thanks :D

**Comment by Odnod** [comment]
If your issue has been resolved, you should close it with the button (somewhere on your page) :)
