### ISSUE TITLE
I worked so hard for this day and... Wait, where's the light dust?! 

### ISSUE THREAD

**Issue by TimThePvpMaster** [Wynncraft/Issues#4278]
Yea, simple bug that Wynn hasn't fixed yet... SO I was doing the Temple of Legends quest, I had been working so hard to hit level 68 to get it, and I get to the part where you talk to Jorkins about the light dust in the nether region. I go over to the light dust area, thinking i'll find some, and just bring it back to jorkins without a problem. Well, to my great sadness, just like the Low level Sacharrum quest in the Nivala forest, They stupid caves won't drop their items like they used to. Wynn apparently hasn't upgraded to the lvl 0 mobs in these 2 caves, and it is really depressing for me. I had just got lvl 68 yesterday, and I had to rankup a whole new Mage just to get to lvl 27 to get a stupid Corrupted Potato for the TOL quest. I then went on mineplex to calm down because I just got murked by 3 mobs because wynncraft was having server issues, and my friend whom is a lvl 86 Assassin, ign is Woochie, told me about /fixquests. I then go back on the server, super happy, to find it works, and I got my potato back. All is good. Then I talk to Jorkins and well, I lost my opportunity in the Temple OF Legends because THE CAVE WON'T PRODUCE THE DUST! I've been having a bad week. My dog got skunked last night too. Anyhow, thanks for looking at this @Trixter313 and I believe DarkDemon (Sorry, forget your user). I have found another gamebreaking glitch, which pains me just as much as the stupid class box falling bug... Thank you so much guys for helping & reading!

**Comment by TimThePvpMaster** [comment]
I guess what I'm trying to say is, Is there any way I can get the light dust? Because it isn't in the cave the wiki shows, and it isn't exactly anywhere else. Worse yet, in my quest book it states: Go back to Jorkins and tell him what you've found. Which, I go back to him thinking it's there but not actually there, and he says: Have you got the light dust yet?! So sad, I wanted to go inside the Temple Of Legends so badly.

**Comment by Odnod** [comment]
Hey, this is a duplicate of #4236. Please close this post and direct any additional comments to the original thread. Thanks!

P.S. Know that this issue is very well known by now and it is being worked on.

**Comment by TimThePvpMaster** [comment]
Alright, cool man. I've been waiting 2 years for this day, and I am real discouraged about it. Thanks!
