### ISSUE TITLE
Stuck in black box please help?????

### ISSUE THREAD

**Issue by Kosua** [Wynncraft/Issues#4280]
I get on the server and try to load mt lvl 21 archer and it says Thanks for using WynnPack, Enjoy the game and I get stuck in this black box but if i do /kill it brings me to ragani and i was at a different place before and i also lose 2 soul points everytime please help me.

**Comment by Odnod** [comment]
So does this happen every time you log in?

**Comment by Kosua** [comment]
yes

**Comment by Moe-Ronickah** [comment]
The server was having some severe issues two days ago.  Is this still happening to you?

**Comment by Xauf** [comment]
If you are stuck in a black box just say
/kill

**Comment by Moe-Ronickah** [comment]
If you are still having this problem, please reinstall your MineCraft.  If the issue is resolved, please close the issue.

**Comment by Moe-Ronickah** [comment]
30 days.  No response.  Closed.
