### ISSUE TITLE
Missing quest item bug

### ISSUE THREAD

**Issue by beck2115** [Wynncraft/Issues#4285]
breathing helm is required for lvl 43 quest but i do not have it sadly. what should i do? i already completed the maltic quest tho.....
![2016-02-25_20 49 47](https://cloud.githubusercontent.com/assets/17486360/13340837/80d465ee-dc01-11e5-9f25-7a57769127ca.png)

**Comment by TheIvyX** [comment]
Type in /fixquests

**Comment by beck2115** [comment]
o
Thanks :)

**Comment by beck2115** [comment]
it worked :)
