### ISSUE TITLE
Silverfish Dungeon fail

### ISSUE THREAD

**Issue by MrMaggen** [Wynncraft/Issues#4290]
The redstonetrap to get to boss does not work it will not open 
![2016-02-26_13 59 28](https://cloud.githubusercontent.com/assets/17232865/13352956/1f0837f6-dc91-11e5-81dd-1273dab351bf.png)

**Comment by DarkDemonDragon** [comment]
Some worlds have broken redstone. Simply switch to another world and continue the dungeon from there.

**Comment by Moe-Ronickah** [comment]
Is this issue still ongoing, or did switching worlds fix the issue?

**Comment by Moe-Ronickah** [comment]
Fixed.
