### ISSUE TITLE
Temple of the legends

### ISSUE THREAD

**Issue by RaiAlt** [Wynncraft/Issues#4291]
In Lightdust cavern no spawning light dusts

**Comment by RaiAlt** [comment]
#4236

**Comment by RaiAlt** [comment]
![2016-02-26_14 14 50](https://cloud.githubusercontent.com/assets/17496110/13353355/0ce3d24e-dc94-11e5-8507-11d591bc9067.png)

**Comment by Moe-Ronickah** [comment]
Duplicate of #4236  but you already knew that.  Please, don't post duplicates, but, rather, add to the original issue.  Thank you.
