### ISSUE TITLE
Armour Skins Not Working

### ISSUE THREAD

**Issue by TalkitiveJerry** [Wynncraft/Issues#4295]
I don't know why but when I put armour on its just regular armour. It never puts on the armour on my skin and everything. When I try doing /armour nothing ever happens. If you guys can fix this I would appreciate it so much. (My MC username is SavagePlayer)

**Comment by Place-Name-Here** [comment]
It isn't a bug the skin textures are getting redone. :)

**Comment by pokemonthefirst** [comment]
I was going to say the same thing! Thank you for telling us that the skins are getting redone!!

**Comment by Place-Name-Here** [comment]
No problem. :)

**Comment by sakke03** [comment]
the annoying thing is that if you use vanish your armour can still be seen
