### ISSUE TITLE
WynnExcavation Site C is Broken

### ISSUE THREAD

**Issue by Spikeddragon** [Wynncraft/Issues#4297]
So I start the quest, no issues and I continue as normal. Then as I get through all the rooms and past the orange crystal (note that no crystals would drop/idk if they should), I'm told I need the Purple Crystal from Site B to start the quest. At this point I say "Ok, maybe I missed a crystal at the golems."
I go back and still nothing. 
![2016-02-26_14 25 44](https://cloud.githubusercontent.com/assets/8258403/13363015/7fe2b552-dc95-11e5-9e43-e2ce3cdddb74.png)
![2016-02-26_14 25 54](https://cloud.githubusercontent.com/assets/8258403/13363022/843d5aee-dc95-11e5-802c-2af0ff752cad.png) 
(Btw I have 3 Crystals because I used /fixquests)

**Comment by KeepoPrideHD** [comment]
I've already reported the same bug. It's not a bug though, in the room where level 95 guards are, under the huge red crystal sometimes red crystal shards should appear. Once you have one of these, you can finisz the quest. The thing that's bugged is that not the shard from B is needed but from C. It would be all clear and logical if it was so.

To sum up, go through all the rooms and remember to collect the **Red Crystal Shard!**

**Comment by Spikeddragon** [comment]
Alright, ty! Hopefully the crystal is there this time

**Comment by Spikeddragon** [comment]
It was a kind of early close... I went through every world and no crystals dropped, is there a reason behind the crystals not dropping?

**Comment by Odnod** [comment]
Duplicate of #4236, please close this issue and put any additional comments on the original post. Thanks!

This issue is very well known and it is being worked on.

**Comment by Spikeddragon** [comment]
Ok
