### ISSUE TITLE
+400 = -400?

### ISSUE THREAD

**Issue by KeepoPrideHD** [Wynncraft/Issues#4298]
![2016-02-24_12 09 52](https://cloud.githubusercontent.com/assets/16866631/13365821/9b541816-dcd7-11e5-9962-fb99bc7d043f.png)
![2016-02-24_12 09 42](https://cloud.githubusercontent.com/assets/16866631/13365842/b388be50-dcd7-11e5-93c4-271db67b3de8.png)

So, I bought a Jester Bracelet with nice identifications from a player. I had to have 2-piece bonus, I remembered it gave nice boosts. I can see I have 400 less health... although the set bonus is +400 health, not -400! I'd also like to remind, that not only in the game 2-piece bonus has +400 health written, but also on the wiki. I will also provide you with screenshots about the bug. 

Photos:
![2016-02-24_12 09 55](https://cloud.githubusercontent.com/assets/16866631/13365767/4a0ea1ec-dcd7-11e5-9adf-0fbc4bfbff21.png)

**Comment by Place-Name-Here** [comment]
Huh wierd...

**Comment by KeepoPrideHD** [comment]
And 2 of the photos got posted before the actual text "Photos:" fail

**Comment by DarkDemonDragon** [comment]
Can you do a before and after image? You images just show what happens when your wear the jester items, so I can't tell what they change.

**Comment by Moe-Ronickah** [comment]
@KeepoPrideHD , I do not see an image of where you have lost 200HP, can you give us one, so that you can confirm what you are saying?

**Comment by AckroWynn** [comment]
@Moe-Ronickah If you look at the final image, you can see how a heart is returned after the bracelet is taken off.

**Comment by Moe-Ronickah** [comment]
I know, but because he didn't take another cap with the actually health number showing, this is not definitive, unless each heart has a set value at all levels.

Well, I was going to check the numbers with my Jester Set, but when I Esc killed my 71 Warrior, it was wearing my Jester Pieces.

**Comment by AckroWynn** [comment]
That was very unfirtunate. I have a jester bracelet, so I could see if this is a global issue.

**Comment by AckroWynn** [comment]
@Moe-Ronickah It seems like this is not a global issue. I am receiving 400hp, as stated in the lore.

**Comment by Moe-Ronickah** [comment]
Individual glitch, with no further input from op.
