### ISSUE TITLE
Beneath the Depths quest bug

### ISSUE THREAD

**Issue by treeyo** [Wynncraft/Issues#4299]
SPOILERS

I am at the room where the maps are supposed to drop, no maps are dropping.  I even checked the wiki and I was at the right place.  The screenshots even had many maps just sitting on the floor.   I even tried dropping an emerald on the chest.  Please help :c

~treeyo

**Comment by Odnod** [comment]
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

This issue is very well known and is being worked in.
