### ISSUE TITLE
Wynn Excavation site C

### ISSUE THREAD

**Issue by 63502** [Wynncraft/Issues#4301]
I can't complete the quest.
I have started the quest, had one purple crystal shard taken, and successfully gone through every step except talking to Excavator Placardus. When I try to complete the quest, It says I need the shard from site B and doesn't let me do anything, even when I bring an extra shard.

/fixquests has no effect

Issues #2224 and #1990 which are the only related issues are closed and somewhat outdated. I thought it would be best to open a new issue.

![2016-02-26_23 08 46](https://cloud.githubusercontent.com/assets/15267053/13370704/04b1f926-dcde-11e5-84c8-a7d546d79ce5.png)

**Comment by Odnod** [comment]
you have to retrieve the red crystal. Which is currently broken. Visit #4236 for more info and also kindly close this issue. Thanks!

**Comment by 63502** [comment]
...
