### ISSUE TITLE
Soul point loss

### ISSUE THREAD

**Issue by Superkirbygalaxy** [Wynncraft/Issues#4302]
I was in the nether area with all the black spikes in the hole. I fell in the lava and died, but it took 2 soul points and spawned me back in the lava. i got out and ran from mobs, teleported to town with a scroll, but died from afterburn again.
i have inserted a picture for proof
![lava glitch](https://cloud.githubusercontent.com/assets/17508405/13370879/e563840c-dce4-11e5-822b-818e6641b627.png)

**Comment by gettodachopa** [comment]
Your have died twice and you use one teleport scroll = 5 soul points lost, nothing wrong

**Comment by Trixter313** [comment]
Fire damage most likely killed you the second time, which is intended.
