### ISSUE TITLE
My weapons disappeared...

### ISSUE THREAD

**Issue by HeroicaIIy** [Wynncraft/Issues#4303]
My apocalypse and bobs mythical spear both disappeared from my inv when i was changing lobbies. i definitely didn't drop them just before i changed lobbies because i always make sure that i have my stuff. i dont have any screenshots of my weapons. it was outside of the cowfusion quest laboratory. This happened to me before but instead i lost all my stuff (before gavel) 
pls help

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refunds policy so there's nothing we can do about the lost items. All I can suggest is try clicking on the empty slots in your inventory to see if they reappear. Sorry!
