### ISSUE TITLE
All of My Stuff Have stuff have dissapeared:(

### ISSUE THREAD

**Issue by angriestsumo** [Wynncraft/Issues#4305]
So i go off the server for about 5 mins and i log in and go in wynncraft and all of my items were gone.
Such as Ragni's spear, Sarched leggings padded armour as the rest. all i have is 2 regular spears 
also now my top classes have all lost items

**Comment by wynncraftlupascu** [comment]
Dude you died with 2 sp !

**Comment by angriestsumo** [comment]
??? what wynncraftlupascu

**Comment by Trixter313** [comment]
How many soul points did you have when you logged back on? Soul points are in the last slot of your hotbar and if you die with less than 3, all of your items drop on the ground. You lose 2 soul points every time you die and get one soul point every ingame sunrise.

**Comment by angelgirl767** [comment]
same i lost my lvl 19 class and its was a warrior and i didnt delete it and i logged off and logged back in 5 mins later and that class was gone

**Comment by angelgirl767** [comment]
and i had 11 soul points

**Comment by Trixter313** [comment]
Closing due to be response.
