### ISSUE TITLE
Slime Scooper Stuck In Inventory

### ISSUE THREAD

**Issue by BrianMcFluffy** [Wynncraft/Issues#4310]
So I used the fixquest command oonce and now I'm stuck with the slime scooper in my inventory, and everytime I try to drop it, it tells me I'll need it for later quests, but I checked and it's only needed for the  Green Gloop quest, that I have already completed. What am I supposed to do?

**Comment by Moe-Ronickah** [comment]
I'm sorry, but this is not a glitch.  It is a protective mechanic.

**Comment by Endertricity** [comment]
Same thing happened to me. So what if it's a protective mechanic? It takes up space in the bank. Also happening to factory helmet, I did both I and II of Iron Heart
