### ISSUE TITLE
Shattered Minds teleport not working

### ISSUE THREAD

**Issue by yairkaraso** [Wynncraft/Issues#4314]
So I did the Shattered minds quest and I entered black room/coal blocks that teleports you and then I started to fall down and died because the teleport didnt worked and then I spawnd at the lvl1 Caravan.
Where you start the game. I died where I need to find way to "escape the temple" with the jump/speed boost that the button gives you.

**Comment by Moe-Ronickah** [comment]
You will have to go back through the quest to where the error occurred in order to complete the quest.  Sometimes, things like this happen in MC.  Unless further reports of this issue occur, then it was just a random glitch.
