### ISSUE TITLE
Wrong text when interacting with NPC "Irt" in Almuj

### ISSUE THREAD

**Issue by Baumey** [Wynncraft/Issues#4315]
![](http://puu.sh/nnxaR/924ab0183f.png)
Wrong text when interacting with NPC "Irt" in Almuj
X:+940 / Y:+76 / Z:-1892

**Comment by Place-Name-Here** [comment]
That's a 404...

**Comment by Moe-Ronickah** [comment]
Please post a screenshot of the issue.  Your link does not lead anywhere.

**Comment by Trixter313** [comment]
You have to copy and paste the link instead of clicking on it, the text is correct but the hyperlinked link is broken.
Here's the image:

![](http://puu.sh/nnxaR/924ab0183f.png)

**Comment by Moe-Ronickah** [comment]
Duplicate of #4177
