### ISSUE TITLE
Issues regarding the map link.

### ISSUE THREAD

**Issue by Deathgrip477** [Wynncraft/Issues#4316]
Hello during the begining stages of starting out you come across an NPC that gives you a link to the map the like is as follows https://wynncraft.com/map. I believe this should be updated to hold the correct map link here https://map.wynncraft.com/#/-1583/64/-1636/min/0/0. (edit. The king In Ragni Is the one who gives the link.)

**Comment by Moe-Ronickah** [comment]
Thank you for reporting this!

**Comment by Trixter313** [comment]
Just https://map.wynncraft.com would work too, to simplify things =)

**Comment by DarkDemonDragon** [comment]
@Dar-krusos you might want to add this to your typo thread.

**Comment by AckroWynn** [comment]
I will fix this before you manage to blink with your eyes!

**Comment by DarkDemonDragon** [comment]
OMG @AckroWynn is back! Btw I've been trying to apply as an official Github Staff for the past 3 weeks through E-mails to Tama, but he's still on his hiatus. If I sent you my application through e-mail is it possible for you to look it over and decide if I'm qualified to be a staff here? Thanks for any help you can give! :D

**Comment by Trixter313** [comment]
Can this issue be closed now? =)

**Comment by Moe-Ronickah** [comment]
@AckroWynn , did you fix this?

**Comment by AckroWynn** [comment]
Yes, I did fix this.

**Comment by Trixter313** [comment]
Alright, thanks!
