### ISSUE TITLE
lost all skill points

### ISSUE THREAD

**Issue by Rccoon** [Wynncraft/Issues#4317]
the server crashed and when i logged in i lost all my skill points pls help
![2016-02-27_22 21 30](https://cloud.githubusercontent.com/assets/17179681/13375147/ed7f7f26-dda0-11e5-8417-4eca54e39594.png)

**Comment by gettodachopa** [comment]
Relog or do /class

**Comment by Moe-Ronickah** [comment]
Did the problem resolve when you relogged on or used /class?

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/4304

Please direct any future comments to the original thread. Thanks!
