### ISSUE TITLE
Guild leaving bug

### ISSUE THREAD

**Issue by RockyPlayzMC** [Wynncraft/Issues#4320]
My username is RockyPlayzMC and km trying to create my own guild but I'm stuck in a guild and when I do /guild leave and type yes it takes my soils but doesn't kick me from guild these members don't play anymore and I want to create my own please fix this.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes it just takes a little time for the removal to update.

**Comment by RockyPlayzMC** [comment]
No I'm still in the guild

**Comment by RockyPlayzMC** [comment]
Still in guild and it took my souls

**Comment by ChiefInferno** [comment]
for me I think it was because of a name change ive been trying to leave my guild for months

**Comment by RockyPlayzMC** [comment]
Bye the way is this Goin to be fixed soon because I want to join my friends or make my own guild. And I just want to thank the staff team recently with all the bugs, they have all been working very hard especially with the items despawning now that it's fixed. Cheers :D

**Comment by Trixter313** [comment]
I see that you've changed your name in the past, meaning this is most likely a duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!
