### ISSUE TITLE
Skill point reset and taken

### ISSUE THREAD

**Issue by superbacca792** [Wynncraft/Issues#4321]
# Delete this line if you've searched for a duplicate issue first
ok im a level 53 assassin and i got on today and all of my skill points were gone from all my skills and it says i have no skill points to be used. so i have no skill points now i cant use my armor or my weapon i want to know if i can get my points back please.

**Comment by LightningGamezX** [comment]
Just log out and re join and if it doesn't work ask a mod or admin.

**Comment by Moe-Ronickah** [comment]
You can either relog in, or use /class.  Is this problem resolved?

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/4304

Please direct any future comments to the original thread. Thanks!
