### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by fr0ty** [Wynncraft/Issues#4325]
# Delete this line if you've searched for a duplicate issue first
The site (Not the forums) https://wynncraft.com/, isn't working for me. In a websearch, I find the site perfectly fine, click on it. Then it loads, but all it loads is a webpage background and no actual menus or anything.

**Comment by Moe-Ronickah** [comment]
This is just due to the servers being very busy, but thanks for letting us know.

**Comment by fr0ty** [comment]
The problem has persisted over the last 6 hours, now. Are the servers really that busy?
