### ISSUE TITLE
Unidentified Items Glitch or Bug

### ISSUE THREAD

**Issue by ebroslayer** [Wynncraft/Issues#4326]
[Click me for video](https://www.youtube.com/watch?v=7J7Yl88f8FI)

**Comment by Moe-Ronickah** [comment]
Your link does not work.  Please post screenshots of the issue.

**Comment by ebroslayer** [comment]
![2016-02-28_08 01 07](https://cloud.githubusercontent.com/assets/17521595/13380195/33354a40-ddf2-11e5-8d5a-bf69ab3e5c17.png)
![2016-02-28_08 01 38](https://cloud.githubusercontent.com/assets/17521595/13380196/3630d85e-ddf2-11e5-923d-5b31e796c006.png)
![2016-02-28_08 02 35](https://cloud.githubusercontent.com/assets/17521595/13380197/3889b1ca-ddf2-11e5-9363-10e467c52954.png)

**Comment by ebroslayer** [comment]
Basically, I can see the name of the unidentified item by using the emerald merchant.Once I do identify the item it comes out what was shown. I don't know if it's a big or small problem I just thought it was best to let you know.

**Comment by Trixter313** [comment]
You have to copy the text for it to work. The link it's pointing to is incorrect but the actual shown link is correct. The way github does links is confusing. When you click insert link, it inserts `[](url)` into the box. Most people just paste the link between the brackets but the link is supposed to replace the "url" part and what you want the text to say that you click on goes in the brackets, such as "click me".
[Here's the working link](https://www.youtube.com/watch?v=7J7Yl88f8FI)
Also, I've fixed the first post.

**Comment by BasicallyNothing** [comment]
I have no idea how that happened, cause I can't stack them. Isn't a problem for me.

**Comment by Moe-Ronickah** [comment]
Fixed
