### ISSUE TITLE
Please Help? Serious problem

### ISSUE THREAD

**Issue by angriestsumo** [Wynncraft/Issues#4327]
i get a new highest level for my classes the items disappear my 3 best classes warrior,assasin,archer

**Comment by Moe-Ronickah** [comment]
Could you be a bit more specific about what is happening, please?  I can't follow what you are saying.

**Comment by Asa473** [comment]
I only have an archer class and all my skills have been reset plz I am lvl 30 plz can u give me 60 skill points back thx asa :+1:

**Comment by PenguinInSnow** [comment]
Would love to reply and help you with your problem but as Moe-Ronickah said, could you be a bit more precice on your problem please? As explaining with a clear writing your problem and with more details so we can understand and possibly help you with it.

**Comment by Verret001** [comment]
Closed due to inactivity over ten days
