### ISSUE TITLE
lost quest item in a armour bug

### ISSUE THREAD

**Issue by linus301203** [Wynncraft/Issues#4328]
My armour disapeared for seacond time and i had a quest item on now i should use it and can't get it back please help me (it's abysso galoshes)

**Comment by gettodachopa** [comment]
type /fixquests

**Comment by Trixter313** [comment]
Did /fixquests fix your issue? Thanks!

**Comment by linus301203** [comment]
Yes it helped a lot thanks:D

Den søndag den 28. februar 2016 skrev Nick Cipriani <
notifications@github.com>:

**Comment by Trixter313** [comment]
Glad to hear, have a good day!

**Comment by linus301203** [comment]
Have a good Day too

Den søndag den 28. februar 2016 skrev Nick Cipriani <
notifications@github.com>:

**Comment by linus301203** [comment]
Thanks a lot it helped AS it should

Den søndag den 28. februar 2016 skrev gettodachopa <notifications@github.com
