### ISSUE TITLE
Quest "Confused Farmer" indeed

### ISSUE THREAD

**Issue by McSeed** [Wynncraft/Issues#4331]
The Quest "Confused Farmer" have a problem with the emerald credit.
At the end of the quest I have 48 emerald on my inventory i talk to "Drale" and it suppose to add me 44 emerald, instead i have the same amount 48.

**Comment by DarkDemonDragon** [comment]
@McSeed you don't get the emeralds at the end of the quest. You get them from the FARMER NPC not Drale.
