### ISSUE TITLE
Emerald Block Loss

### ISSUE THREAD

**Issue by MrRalliv** [Wynncraft/Issues#4332]
Me and my friend lost our emeralds blocks for some reason can any one help?

**Comment by Trixter313** [comment]
Could you explain what happened in more detail? Where were you, what were you doing, etc. Wynncraft has a strict no refunds policy so there's nothing we can do about the lost emeralds but we can try to figure out what happened to prevent it from happening again. Thanks!

**Comment by Trixter313** [comment]
Closing due to no response.
