### ISSUE TITLE
Horse bug

### ISSUE THREAD

**Issue by KartfahrerLP** [Wynncraft/Issues#4336]
hi
i was trying to get a better horse  every time when i had enough emerald blocks.
Today i got a black horse ca.20 seconds before the Server restarted.
i loged a few Moments later in and yey i havn`t a black horse i have a Brown horse.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strict no refunds policy so there's nothing we can do. Weird things can happen with items near server restarts so I suggest switching to a new world long before the server actually restarts to prevent any weird issues like this from happening again. Thanks!
