### ISSUE TITLE
Stuck inside a room

### ISSUE THREAD

**Issue by penguin9541** [Wynncraft/Issues#4338]
When selecting my class, I was never taken out of the room. I tried reloging and waiting ( I waited about 2 hours).
![2016-02-28_11 31 19](https://cloud.githubusercontent.com/assets/15089194/13381276/12ed53d4-de26-11e5-80e9-16df3a5fa4de.png)
# Delete this line if you've searched for a duplicate issue first

**Comment by penguin9541** [comment]
I was in Nemract before this happened.

**Comment by Trixter313** [comment]
Just type /kill with 3+ soul points and you will be teleported to the nearest visited town to your current location. Thanks!
