### ISSUE TITLE
Yellow Crystal Shard lost to glitch

### ISSUE THREAD

**Issue by DubTheDev** [Wynncraft/Issues#4339]
I just leveled up to level 46 and I am currently trying to do the Wynnexcavation site B quest.
The quest is requiring me to bring a yellow crystal shard to the excavator to start the quest, but I lost my shard to a glitch a couple weeks ago. I now cannot start the quest. Is there a solution to this?

**Comment by Trixter313** [comment]
Try using the command /fixquests and see if that returns the needed quest items. Report back whether this works or not! Thanks! =)

**Comment by DubTheDev** [comment]
thanks for the help! It worked

**Comment by Trixter313** [comment]
Glad to hear =)

Have a great day!
