### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by DrWaffleBottom** [Wynncraft/Issues#4344]
I made a tier 2 horse and then I brought 2 tier ones and the I put them together making a tier 2 horse but it just got rid of one of them and then I tried put the tier one with the tier thinking it would make tier because I thought it just glitched out and called it a tier 1 and then I put them together and I got a tier 1. This was a lost of 72 emerald blocks which took me a very long time to get because I was only level 28 at the time.

Please someone help me fix this.

**Comment by Trixter313** [comment]
I'm not sure exactly what you're saying but when breeding horses, there's no guarantee what you're going to get and sometimes you even get the same or a lower tier horse. Does that clear any confusion?
