### ISSUE TITLE
Armor Skins

### ISSUE THREAD

**Issue by Ghost88788** [Wynncraft/Issues#4345]
So I have been playing Wynncraft, traveling Wynn and Gaval, but one day, the armor skins stopped working. Ever since that day, it hasn't been working. The armor skins put something special to Wynncraft, making ever single piece you get have it's specialty, but seeing regular leather, gold, chain, iron, and diamond armor makes it less entertaining and less unique. I have tried 1.8.9, turning all skin texture off and on, and taking off my armor then doing /class and putting my armor back on. Everything I try result to no progress. I am not turning into Steve or Alex either, but the only thing is the Armor. I played with a friend in game and irl and use Skype and he says everything is just find for him, so he can see every armor skins, but  I can't. 
![2016-02-28_17 28 32](https://cloud.githubusercontent.com/assets/11810672/13382700/dbf3503e-de40-11e5-8a79-e0b1f4268c21.png)

**Comment by HoboFTW** [comment]
Maybe the server is reseting how armor looks??

**Comment by Ghost88788** [comment]
Well again, I asked my friend on the a day it was still not working, he said it was fine

**Comment by DarkDemonDragon** [comment]
Yea skins are down at the moment. I think they're trying to fix something. Just be patient and they'll be back.

**Comment by TheQuantumBro** [comment]
I like this armor more

**Comment by Ghost88788** [comment]
I understand you DarkDemonDragon by the huge update, Gaval.

**Comment by Moe-Ronickah** [comment]
I doubt that anyone, including the devs, can predict exactly when the problem will be solved.  I know that they have been working on new armor skins, too, but I'm not making any predictions.
