### ISSUE TITLE
Horse Glitch 

### ISSUE THREAD

**Issue by DireFire112** [Wynncraft/Issues#4346]
i had a maxed out black horse but i was trying to get a better one so with 3 le i bought a couple horses and when i scrolled over my horse it said brown horse so i crafted it and then later to realize that i only have a brown horse. So now i have a brown horse and no money

**Comment by DireFire112** [comment]
im not very good at explaining so if you dont understand a part just ask

**Comment by DarkDemonDragon** [comment]
I'm not too sure what the situation is, but please be aware the horse breeding has risks. The horse has a 50% of being the same breed, 30% of becoming a better breed, and a 20% chance of downgrading.

**Comment by Moe-Ronickah** [comment]
I'm sorry, but you must have crafted your black horse with a brown horse.  As stated, above, there is a 20% of getting a lower level horse, and that is what must have happened.

**Comment by DireFire112** [comment]
umm

**Comment by DireFire112** [comment]
no it said it was a brown horse but my black horse disappeared

**Comment by DarkDemonDragon** [comment]
I think he means he accidently breed his black with his brown. At any rate, Wynncraft has a strict no refunds policy so there's not much for staff to do in your case.

**Comment by DireFire112** [comment]
aghhh this sucks
