### ISSUE TITLE
Armor Glitch 

### ISSUE THREAD

**Issue by DireFire112** [Wynncraft/Issues#4347]
when i logged on it toke my armor off and threw it on the ground and i couldn't pick it up cause my inventory was full and then it just kicked me off the server i had one inventory slot so i got my helmet and my chest stayed on but my pants (Krakete i think) and my boots (Archolary or something like that) are just gone

**Comment by Asa473** [comment]
i lost my best pieces of armor omg what the hell is going on I cant take any more ! I lost my legendary gold legs and my boots that give me like 125
as well as loosing all my skill points plz  give me my 60 skill points back as I am lvl 30 and they have been reset! how idk! plz plz plz give my stuff back !

**Comment by Moe-Ronickah** [comment]
Servers cannot write everything that is occurring on them, to memory, instantaneously. There is a delay in committing to hard drive everything that is in RAM. So, it is possible to lose items when one memory commit occurs, showing that you took something out of your inventory, followed by a crash, before the server can record what you did with that item. This happens in MC, too, on your local game.

**Comment by DireFire112** [comment]
what soo your just gonna be a bitch?

**Comment by DireFire112** [comment]
they wernt that easy to get

**Comment by DireFire112** [comment]
the first guy who commented
