### ISSUE TITLE
Lost quest things

### ISSUE THREAD

**Issue by Buggers99** [Wynncraft/Issues#4348]
When i was doing the quest Jungle Fever after I had gotten the le from the banker i miss clicked and it threw the bottle and now i only have 63 and i also lost the Factory Helmet for the quest 
"An Iron Heart Part II"  anyway I am hoping you can help but if not it is ok.
Ty

**Comment by TrashcanMan** [comment]
Do /fixquests

**Comment by Buggers99** [comment]
It worked for the helmet but not for the almuj'so Le

**Comment by Buggers99** [comment]
That so isn't in there lol

**Comment by Buggers99** [comment]
Never mind I was to quick to react
