### ISSUE TITLE
Died, lost everything, after glitch

### ISSUE THREAD

**Issue by readcollin0** [Wynncraft/Issues#4350]
So, first off, what I mean by glitch, is it was not detecting my Right Click for spells.
As a result, I could not kill a relatively easy enemy, and I died with few soul points.

I had also recently died due to lag spike, so that's why I was low on points.

Is there anything I can do about this kind of thing?

**Comment by TrashcanMan** [comment]
Unfortunately Wynncraft has a strict no-refunds policy, so we can't give your items back. In the future, avoid going anywhere dangerous when you're at low soul points.

**Comment by readcollin0** [comment]
Oh well, in a way, I kind of expected that...
