### ISSUE TITLE
I can't get my Clearsight Spectacles back.

### ISSUE THREAD

**Issue by TheIvyX** [Wynncraft/Issues#4354]
(/fixquests doesn't fix it.)

During the Realm of Light quest, my helmet changed from the Clearsight Spectacles to the Helmet of Shimmering Light. When I died during the quest, I was sent back to Lexdale. I tried going back to the cave but I didn't have the right helmet. I used /fixquests and did not get the helmet back. I thought the helmet was the problem so I got rid of it, which I didn't get back either.

**Comment by Moe-Ronickah** [comment]
I would advise you to never throw away any quest item unless you are absolutely certain that you won't need it.  Your options at this time are to contact an admin, or contact support@wynncraft.com.  The second option is probably your best option.

Let us know when this gets resolved, please.

**Comment by TheIvyX** [comment]
Well I never threw away the Clearsight Spectacles. It changed to the Helmet of Shimmering Light when I started the Realm of Light quest. I have an extra from another class fortunately, and wearing it does not let me enter the area that the quest is in.

I will try to contact support though. Thanks for the feedback.

**Comment by Moe-Ronickah** [comment]
Let us know if this get resolved.

**Comment by TheIvyX** [comment]
I tried contacting Support but they never got back to me :/

**Comment by Moe-Ronickah** [comment]
Please send them another email.  Sometimes they get swamped.

**Comment by TheIvyX** [comment]
I sent another e-mail, I'll check back here to see if I can get it resolved.
