### ISSUE TITLE
I am invisible

### ISSUE THREAD

**Issue by Diego30090** [Wynncraft/Issues#4355]
I have a problem, my player is always invisible.
I can't play with my friends because they can't see me, i have lost all my stuff in bank and in my inventory.
I tried to restart minecraft (only 1.8.9), I tried to death or use teleport scroll to solve the problem but it persists.
How can I solve?

**Comment by McSeed** [comment]
I can confirm. I add Diego in my party, we have a duel, we try tread successfully and he was always invisible to me and other our friends.

**Comment by Tolemi959** [comment]
Have you tried switching client version? (ie. 1.8 > 1.8.9 or the other way around)

**Comment by Diego30090** [comment]
yes, I tried it but nothing happened

**Comment by Equipa2** [comment]
Do /armour it happened the same

**Comment by Moe-Ronickah** [comment]
Is your issue fixed, or are you still invisible?

**Comment by Moe-Ronickah** [comment]
30 days without a response, and I'm closing this.  If it's still a problem, we can re-open it.
