### ISSUE TITLE
Purple And Blue

### ISSUE THREAD

**Issue by felipeargoll27** [Wynncraft/Issues#4356]
I don't get the Magical Fragment when I entered in the purple and blue meteor cave, probably because my inventory was full (or maybe not). Please help

**Comment by Jenoma** [comment]
Got the same bug. Every item that should fall , is not falling to the ground

**Comment by Moe-Ronickah** [comment]
Duplicate of Quest Items Are Not Spawing #4236 .  Please refer all future comments to the original thread.

**Comment by Sonicmaster418** [comment]
They must fix it

**Comment by Sonicmaster418** [comment]
I literally can't do any quest
