### ISSUE TITLE
Corruption Relic Shard bug

### ISSUE THREAD

**Issue by Tolemi959** [Wynncraft/Issues#4357]
It is listed as a quest item, instead of untradable. Now if you kill the boss for the santa quest more than once (like I did to help a friend) you CAN'T throw away the additional Shard. It isn't used for anything else either and at the end of the quest it only takes one shard off of you. Could this item be changed to be untradable instead?

**Comment by felipeargoll27** [comment]
Open the compass in your hotbar and click on the chest of daily reward. You can drop any item in the chest and then exit it. The item will disappear.

**Comment by Moe-Ronickah** [comment]
No quest item will be changed to untradeable.  Using a glitch to get rid of an item is glitch abusing, therefore, if you use a glitch to solve your problem, don't tell anyone.
