### ISSUE TITLE
Quest item not falling to the ground

### ISSUE THREAD

**Issue by Jenoma** [Wynncraft/Issues#4358]
Lots of quest need to take item that falls to the ground (every wynnexcavation, ultimate weapon, aldorei secret pt2, purple and blue). Every item in every location is NOT falling. I tried to change server, char, lobby, everything. But is useless, so.. Maybe it's a bug

**Comment by Moe-Ronickah** [comment]
Duplicate of Quest Items Are Not Spawing #4236 .  Please refer all future comments to the original thread.
