### ISSUE TITLE
Hourglass sand not Spawning!

### ISSUE THREAD

**Issue by MrBeanyGuy** [Wynncraft/Issues#4359]
When I go to Selchar to retrieve 12 Hourglass Sand, it won't spawn.
I've looked in the Wiki on how to complete the quest (Sister City), thinking I'm doing something incorrect. But the sand just won't spawn.

**Comment by Moe-Ronickah** [comment]
Duplicate of Quest Items Are Not Spawing #4236 .  Please refer all future comments to the original thread.
