### ISSUE TITLE
Temple of the Legends

### ISSUE THREAD

**Issue by ItsYourPlay** [Wynncraft/Issues#4360]
The light dust don't spawn/drop in the Light cave.

**Comment by ItsYourPlay** [comment]
Can someon help me pls.I don't know what i must do.

**Comment by TheQuantumBro** [comment]
It`s bug...Again!

**Comment by Moe-Ronickah** [comment]
Duplicate of Quest Items Are Not Spawing #4236 .  Please refer all future comments to the original thread.
