### ISSUE TITLE
Faded map is not spawning

### ISSUE THREAD

**Issue by duclong889** [Wynncraft/Issues#4362]
# Delete this line if you've searched for a duplicate issue first
This item should be spawned at skull cave for "Beneath the depths" quest but it isn't

**Comment by DikkeHenk1989** [comment]
I can confirm that its not dropping
Quest : beneath the depths

**Comment by Moe-Ronickah** [comment]
Duplicate of Quest Items Are Not Spawing #4236 .  Please refer all future comments to the original thread.
