### ISSUE TITLE
Armor Glitch 

### ISSUE THREAD

**Issue by DireFire112** [Wynncraft/Issues#4370]
When i logged onto a server the server threw my armor on the ground and said in chat you must have min lvl 15 defense (i dont remember what the real lvl and skill was) and a few others including my helm pants and boots not my chest piece for some reason but it did that and then i looked at my stats and they were all 0 and then i was kicked from the server but when i tryed to join back onto the same server all the armor was gone

**Comment by Odnod** [comment]
If you had a full inventory at the time the armor would have either popped off onto the ground or tried to move into your inventory. If they had popped off onto the ground, they would have despawned when the chunks unloaded when you got kicked. Had they tried to move into your inventory, they would have just gotten deleted.

Your only chance of getting your armor back is to obtain the pieces from other players or grind them on your own as Wynncraft has a zero-refunds policy.

**Comment by DireFire112** [comment]
well that sucks but thanks for the info
