### ISSUE TITLE
Beneath the depths

### ISSUE THREAD

**Issue by RedNightDragon** [Wynncraft/Issues#4371]
Recently I have been trying to do this quest but the map does not seem to be spawning in. I have tried servers 2 and 3 and neither worked. I am assuming it is like that for all of the servers. I hope that this gets fixed soon and if it is not broken then... damn I feel stupid. lol but thanks

**Comment by RedNightDragon** [comment]
also it appears and if the item identifier npc and the emerald merchant are missing.

**Comment by ZzJarnozZ** [comment]
I have the same problem to im trying to do it too but not spawning for me either

**Comment by Moe-Ronickah** [comment]
Duplicate of #4236 . Please, use the search instructions on the front page so that you don't post duplicates, but, rather, add to the original issue. Thank you.
