### ISSUE TITLE
Wynncraft "WynnExcavation site B"

### ISSUE THREAD

**Issue by halo33** [Wynncraft/Issues#4373]
Hello I'm Halo3 and I was doing the quest "WynnExcavation Site B" and at the end where you're supposed to get a purple shard off the ground there was none. So I decided to go through the exit in the back and it wouldn't let me tp through. I tried a few times and it finally teleported me except I'm in the ground. I'm presently stuck with no way of leaving. Do not have any scrolls with me to teleport. I hope this can be resolved soon. My cooridnates in game are (x=56) (y=63) (z=-529). 

Maybe adding a /suicide? So when stuff like this happens you can get out of it?

**Comment by TursedTomb** [comment]
There is /kill command.
