### ISSUE TITLE
My points are glitched

### ISSUE THREAD

**Issue by Asa473** [Wynncraft/Issues#4374]
1st he's not my dam friend also I want this problem to be fixed plz! I lost my points when I rejoined I had some not all of them I was like 5-6 short !

**Comment by Trixter313** [comment]
Could you tell us your level and post a screenshot of your skill point menu? Thanks!

**Comment by Skillett** [comment]
Usually doing /class and logging back in fixes that issue!

**Comment by DarkDemonDragon** [comment]
@Asa473 check your armor and weapon. Some gear will give negative skillpoints and will say something like " - 1 Agility " in red in the lore of the item. Please briefly skim through your gear before posting screenshots of all your gear IDs and your skillpoints from your compass.

**Comment by Moe-Ronickah** [comment]
30 days out without a response from the OP, so we don't know if it was a change due to changing accessories or an actual glitch.  I'm closing this, now.  It can be reopened if we need to.
