### ISSUE TITLE
Spider cave

### ISSUE THREAD

**Issue by Amminate** [Wynncraft/Issues#4383]
No Saccharum!

**Comment by Trixter313** [comment]
Have you tried switching to another world? It might just be a temporary issue on one world.

**Comment by kmo900** [comment]
NO this is happening several drops quests i saw it in the spider cave and also in the suspended flowers. reading thrugh the issues i think it is the same problem with the diamond shards

**Comment by Odnod** [comment]
Duplicate of #4236, please close this issue and put any additional comments on the original. Thanks!

Please know that this bug is very well known and is being worked on.
