### ISSUE TITLE
can,t see my armor skin and can,t get xp?

### ISSUE THREAD

**Issue by olta2309** [Wynncraft/Issues#4386]
can,t get my armor skin to look like the skin armor so it jsut looks normal and my xp bar can,t get filled so i can,t get in higher lvl plzzz help

**Comment by DarkDemonDragon** [comment]
For the armor, this is a temporary thing as Admins are working on something with the armor skins.

For your other issue I couldn't quite understand what you mean. Please elaborate and provide more details.

**Comment by Dodo-Bird** [comment]
You might have guild xp set to 100

**Comment by Moe-Ronickah** [comment]
30 days out without a response from the OP, so we don't know if it was a temporary bug an actual glitch. I'm closing this, now. It can be reopened if we need to.
