### ISSUE TITLE
Stuck in cave ceiling

### ISSUE THREAD

**Issue by TheDeltaSmasher** [Wynncraft/Issues#4387]
# Delete this line if you've searched for a duplicate issue first
In the quest "Green Skinned Trouble" after I beat the boss in the underwater cave, I used the teleporter in the room, and now I'm stuck in the cave's ceiling at -1867 33 -4899. MC username is TheDeltaSmasher

**Comment by Odnod** [comment]
type /kill with 3 or more soul points to get teleported to the nearest city.
