### ISSUE TITLE
[Quest]The Ultimate Weapon

### ISSUE THREAD

**Issue by OJGold** [Wynncraft/Issues#4388]
I need 50 soft whetstones for complete the quest The Ultimate Weapon..and whetstones are random-dropping item.. but It's not dropping again.. T_T maybe It's error again? how can I do?.. or just wait for fixing?

**Comment by Odnod** [comment]
Duplicate of #4236, please close this issue and put any additional comments on the original. Thanks!

Please know that this bug is very well known and is being worked on.
