### ISSUE TITLE
[Quest]Forbidden Prison

### ISSUE THREAD

**Issue by OJGold** [Wynncraft/Issues#4389]
nah.. I'm stucked in prison..
I should get Prison key for escape. but I can't.. door is not opening... I solved the puzzle, but door is not opening. maybe this is error too?.. should I wait again?? T_T

**Comment by Moe-Ronickah** [comment]
Are you still stuck at this point, or is it resolved?

**Comment by OJGold** [comment]
I'm not stucked now :P you may the close this issue. Thanks for comment to me.

**Comment by OJGold** [comment]
oh I can close my issue XD (I'm newbie at github.)
