### ISSUE TITLE
WynnEscavation glitch/bug   

### ISSUE THREAD

**Issue by RKMASTER202** [Wynncraft/Issues#4391]
# Delete this line if you've searched for a duplicate issue first.
I am RK_MASTER_202 and I was playing wynnescavation B I logged out already started it says to talk to Lykron again. I can play the mission. What do i do?

**Comment by Wildtim9** [comment]
I am having the same bug, its happening for a lot of people... Hopefully they fix it soon.

**Comment by Moe-Ronickah** [comment]
I'll take a guess that you CAN'T play the mission?

**Comment by Moe-Ronickah** [comment]
No comment.
