### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by Narwhal0413** [Wynncraft/Issues#4394]
I seem to be falling. Anytime I join any server from the lobby, I just fall through the floor. My inventory isn't appearing, nor did I pick a class. I tried relogging, which didn't work... and the only command that seem to go through is /lobby. I can't speak in chat. I need help asap. Thanks for reading.

**Comment by Odnod** [comment]
There really isn't anything that can help with this bug. There are users that have been stuck in this limbo for months now and it has not gotten any better. I am sorry to spoil any hopes but it does not look to be getting any better.

**Comment by joeybobo152** [comment]
Try redownloading minecraft or java. It happened to me and i fixed it by doing that

**Comment by Narwhal0413** [comment]
This solved the problem, thanks! :+1:

**Comment by Odnod** [comment]
Awesome! Time to spread the news I guess. It is great to know that there is a way to fix this issue. If it has been resolved, could you close the issue?

**Comment by Narwhal0413** [comment]
Sure, will do. Thanks again!
