### ISSUE TITLE
Lord of the Clock

### ISSUE THREAD

**Issue by joeybobo152** [Wynncraft/Issues#4395]
I'm doing the Lord of the Clock quest and i ran into a bug. After talking to Gundalf, the guy in the secret library, i didnt receive a Instantic Clocks and I already went to Frudo to destroy the clock. Since i dont have the clock, i cant proceed, please help.

**Comment by Odnod** [comment]
try typing /fixquests

**Comment by Moe-Ronickah** [comment]
The clock is a quest item.  This may be the same issue as #4236 .  Let us know if /fixquests works for you, please.

**Comment by joeybobo152** [comment]
oh it works. Tysm Moe-Ronickah!

**Comment by Odnod** [comment]
If your issue has been resolved please close it. Thanks! :)

**Comment by Moe-Ronickah** [comment]
You're welcome.  I'm glad that it worked.
