### ISSUE TITLE
Golden Bars (Quest "Canyon Condor") 

### ISSUE THREAD

**Issue by NewCubeOp** [Wynncraft/Issues#4397]
The "Golden Bars" not reappear in the mine on the mission "Canyon Condor"! Thank you to have read this message!

**Comment by NewCubeOp** [comment]
The same goes for the flowers in the quest "Suspended flowers"

**Comment by NewCubeOp** [comment]
#4236

**Comment by DarkDemonDragon** [comment]
This is a duplicate of #4236 Please close this and follow the original.

**Comment by NewCubeOp** [comment]
> @
