### ISSUE TITLE
Sand Won't Spawn At Selchar For Mission "Sister City"

### ISSUE THREAD

**Issue by ChoccyBiccy3** [Wynncraft/Issues#4399]
Aswell as myself I have come across many people at Selchar's Hourglass Tower, wondering why no sand has spawned. I have checked several times and have watched youtube videos on how to complete the mission but it is not where it appears to be in these videos. I would appreciate if someone could fix this issue. ~ChoccyBiccy~

**Comment by Odnod** [comment]
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.
