### ISSUE TITLE
Join glitch

### ISSUE THREAD

**Issue by Greenmchn** [Wynncraft/Issues#4409]
I cant join a game. I try to join one, and i just fall into an endless abyss while loosing hunger quickly? Then it says I cant use commands. Also, before I couldn't join, I tried to use /class in game. then it wouldn't work, and I couldn't use commands again. PLEASE help.

**Comment by Odnod** [comment]
heyy we figured out how to fix this one yesterday. I am afraid the only way to fix this is to uninstall and reinstall minecraft. If this does not work then I have no idea.

**Comment by Greenmchn** [comment]
Ill try it... Will I also have to reinstall Optifine though?

**Comment by Odnod** [comment]
you may, I do not know all of the details of uninstalling mc but as far as I know it is the only chance of fixing this bug.
