### ISSUE TITLE
Canyon Condor Mission

### ISSUE THREAD

**Issue by McSeed** [Wynncraft/Issues#4411]
I try to find the Golden bars, for the quest Canyon Condor, but they don't spawn at the end of the trail.
I have restart mc and i try to change servers but the problem still persist.

**Comment by Odnod** [comment]
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Comment by UryuuMinene** [comment]
Same here, Have gone into the cave at least 3 to 5 times and still no golden bars spawning. Sorry to trouble you Odnod.
