### ISSUE TITLE
Wynncraft Excavation site D has a hole

### ISSUE THREAD

**Issue by GaPoiVN** [Wynncraft/Issues#4414]
Theres a hole at these coords : -4098 38 -305 , people can get stuck if they fall in that hole

**Comment by Odnod** [comment]
How deep is the hole?

**Comment by GaPoiVN** [comment]
is like 20 blocks ? i cant use charge to get up

**Comment by GaPoiVN** [comment]
i have an image about that hole : http://imgur.com/bncLS8t
bad english sry

**Comment by AckroWynn** [comment]
I'll have this fixed in 20 minutes. Thanks for reporting!

**Comment by Trixter313** [comment]
Thanks, Ackro!
