### ISSUE TITLE
Armor is changing IDs in war!

### ISSUE THREAD

**Issue by OMGitsTomix** [Wynncraft/Issues#4416]
Hello,I have my chestplate "Soul signal" that I can wear when I'm level 92,and when I have 40 intelligence and 40 dexterity,few days ago I joined war with my guild and I saw a message what was saying I can't use Soul signal beacuse I don't have enough dexterity skill points,I looked at my chestplate and it wanted level 92, 40 intelligence and 45 dexterity! Please fix this.

http://imgur.com/67SSKJS Before war

http://imgur.com/UT3XGDz In war

**Comment by Odnod** [comment]
Soul Signal used to require 30 int and 45 Dex, wars must not be running on the most recent version if the game.
