### ISSUE TITLE
XP over 100% at level 60

### ISSUE THREAD

**Issue by Xeromere** [Wynncraft/Issues#4418]
So I have had this bug since the start of the gavel update, my xp is over 100% and stuck at level 60.
![02d0470b5b1edbff08e11c13a66d58ac](https://cloud.githubusercontent.com/assets/17623872/13508383/c3c81974-e154-11e5-91b1-e590a9a27cad.png)
IGN is PhijkchSerperior

**Comment by HeyloLP** [comment]
look on your compass there is your real xp amount

**Comment by Moe-Ronickah** [comment]
PLEASE, post an image of your xp from your compass.  I'd like to take a closer look at this.

**Comment by Xeromere** [comment]
![2016-03-05_00 45 54](https://cloud.githubusercontent.com/assets/17623872/13545961/bdceee2c-e26b-11e5-8319-6a4a6fc38483.png)

**Comment by Xeromere** [comment]
Issue seems to have fixed itself after killing a Bank golem, wasnt doing this for lower level mobs for obvious reasons.
