### ISSUE TITLE
Roulette damage

### ISSUE THREAD

**Issue by mortiferum** [Wynncraft/Issues#4419]
My roulette has 445% melee damage and 284% thunder damage and its only doing 27 normal damage and 100 thunder damage. I asked many people on wynncraft and most said it should do a lot more damage.

**Comment by TrashcanMan** [comment]
Are you sure you don't have any negative damage boosts on any of your other equipment?

**Comment by mortiferum** [comment]
I'm sure

**Comment by Odnod** [comment]
The gimmick with roulette is that it does an incredibly randomized amount of damage, every single hit with it will do a completely different amount of damage. This is not a bug, but rather a risky weapon not paying off.
