### ISSUE TITLE
Bank issues lost all my precious items

### ISSUE THREAD

**Issue by MrMadPvpMester** [Wynncraft/Issues#4428]
I Just bought the last row in the Ender chest and all my five jester necklaces just disappeared. I would be much appreciated if there was a way to get the items back.

**Comment by Odnod** [comment]
Since necklaces are glass panes, they often get deleted from the bank upon expansion. Sadly, the only way to get your lost items back is to obtain them from other players or find them on your own due to Wynncraft's no-refund policy.
