### ISSUE TITLE
Forum system time is incorrect

### ISSUE THREAD

**Issue by GAsplund** [Wynncraft/Issues#4437]
A few weeks ago I was not able to log onto my account because the server time was incorrect. When I was prompted with the Authenticator screen it did not accept my token even though it was correct.

After some investigation it seemed like the server time was a little bit less than 2 minutes ahead of the normal time, forcing me to change my system time to match the server time. (Authenticator codes are only usable for 30 seconds each)

So to prevent others from having the same problem, I hope that you can sync the time to some kind of time server and have the problem fixed ASAP.

**Comment by BlahBlah161616** [comment]
Huh weird

**Comment by Trixter313** [comment]
So this is why 2 step authentication wasn't working for me... Thank you very much for reporting this!

**Comment by DarkDemonDragon** [comment]
Thanks for the report! Perhaps this could help other players with authentication issues.

**Comment by AckroWynn** [comment]
Just a little note. As we have no web-developer as it stands now, any web related issues shall be on hold.

**Comment by DarkDemonDragon** [comment]
So Tama has officially quit or does Wynncraft officially not recognize him as staff due to inactivity? His admin tag was removed a while back so I'm assuming it may be the latter.

**Comment by BlahBlah161616** [comment]
I believe Tama officially quit, however, I believe that there are others out there that could fill that slot...easily.

**Comment by Moe-Ronickah** [comment]
Well, as of this moment, I can confirm that the server time is withing 5 seconds of gov time.  Would anyone who was affected please check your pc's time?  I'd like to know if I need to pass this along, still, to admins.

**Comment by redxdev** [comment]
![image](https://cloud.githubusercontent.com/assets/472625/15064137/2bbd0f48-131f-11e6-840d-95aa5b6de5ad.png)

I can confirm that the server's time is correct. There may be something configured wrong on the forums themselves or with your own computer's time.

**Comment by GAsplund** [comment]
I didn't know that the time was incorrect, I just tested it. Note that this was two months ago. The issue seems to have fixed itself. I can log in using the authenticator app having no problems right now. Just tested it.

**Comment by DarkDemonDragon** [comment]
Yas actual Wynncraft staff looking at Github ^-^
