### ISSUE TITLE
Too high skill points gives negative values

### ISSUE THREAD

**Issue by Zyphicx** [Wynncraft/Issues#4438]
So, I now have 133 points in agility, but now the item counting system using the books says -123. I believe this is because whenever I surpassed 127 the signed bit turned into a 1, therefore it will display a negative value. To fix this you could either change the byte to an integer value or make it unsigned in some way.
![books messed up](https://cloud.githubusercontent.com/assets/17144482/13539001/44d113ca-e256-11e5-9580-e2d206f073ad.png)

**Comment by DarkDemonDragon** [comment]
Wow I guess they never expected anyone to stuff that many points in agility. Just curious, what's the percentage of dodging/air damage with that much agility?

**Comment by Zyphicx** [comment]
76.2%
