### ISSUE TITLE
Memory Paranoia

### ISSUE THREAD

**Issue by DarraghWynn** [Wynncraft/Issues#4444]
So I was on my way through the quest going through the mansion, when all of a sudden, map design decides to kick in and gets me stuck in a cobweb. Now this wouldn't be a problem only I couldn't get out. So what then happened was I was getting attacked by the mobs in the mansion and in panic, dropped my bow "Infinity" *not going to lie, that was my bad.* 

But then what happens is that I go to continue the quest, but I can't get back to the area because the quest requires *A lot* of teleporting, so I couldn't get my bow back which should be my fault for dropping but if I can't get it back due to something like map design, sadly, I'm going to complain. As well as this I still cannot finish the quest.

If at all possible I would really appericiate my bow back, Thanks for reading! :D

**Comment by TrashcanMan** [comment]
Unfortunately Wynncraft has a very strict no-refunds policy, so we can't give you back any lost items. In the future, change your drop key to something far away to prevent such accidents.
