### ISSUE TITLE
Floor 4 Boss Room Gardian Drop

### ISSUE THREAD

**Issue by furno246** [Wynncraft/Issues#4446]
I beat the Gardian in the Tower Of Ascension and the mob glitched through the wall and I killed it withmy friend Haku_YukiNe and since he was mage and I was assassin he was able to glitch through the wall to get the drop and I was not. So please help I would very much like to not fight him again. He was pretty tough. I would also like the drop so I could go to floor 5. And I would like it as soon as possible if you can.

**Comment by Odnod** [comment]
Wynncraft does not give out items, and has a strict no refund policy. If you want the drop you need to fight the boss again.
