### ISSUE TITLE
My skill ponits

### ISSUE THREAD

**Issue by Kongmneg12345** [Wynncraft/Issues#4447]
They are all gone when the server reset all my skill points is all gone so i need help to get them back my ign is :kongmeng plzz help me solve this problem because i cant play with it :-: HEELELLLLLLLLPPPPPP MMMEEEEEE

**Comment by Moe-Ronickah** [comment]
Did you try /class or relogging in?

**Comment by Kongmneg12345** [comment]
ok thx i did it and it works but they sould there to fix this problem

**Comment by Moe-Ronickah** [comment]
Great, glad it worked.
