### ISSUE TITLE
Skill points don't add to some of my skills and disappear.

### ISSUE THREAD

**Issue by BaconStrips111** [Wynncraft/Issues#4449]
I have just logged back on to my account on Wynncraft for the first time after the big update and noticed my skill points were removed from the skills I added them too.  I tried to add the skill points back to my skills but some skills stay at 0 no matter how many skill points I try too add and other skills only take my skill points sometimes.  My total number of skill points remaining goes down by one every time I left click but they aren't all being added to my skills.  I've tried logging off and on again but this does not fix my problem and I am worried about losing any more skill points. Anyone else experience this and knows what to do??

**Comment by Trixter313** [comment]
Skill points can sometimes just take a little time to update and display the correct amount. I'd say give it a couple more hours to rule that out. Also, if you could post a screenshot of your skill point menu, that would help give us some more information. Thanks!

**Comment by BaconStrips111** [comment]
Okay I checked my account just now and nothing has changed with my skill points, I still seem to be missing some.  I took a screenshot yesterday of my skill points and just now so you will be able to see there is no change.  You can also see I'm a level 45 mage so the total skill points i have added and the total skill points remaining would be too low for my level.

Here's the first screenshot (from yesterday): 
![2016-03-04_21 46 05](https://cloud.githubusercontent.com/assets/17665317/13549944/c42f01d4-e2c6-11e5-9644-affd9afbb739.png)

Heres the second screenshot (from today): 
![2016-03-05_11 32 46](https://cloud.githubusercontent.com/assets/17665317/13549948/e27fd136-e2c6-11e5-8066-baee19f14a09.png)

Let me know if you can't see the screenshots.

**Comment by BaconStrips111** [comment]
@Trixter313 I have figured out what was wrong with my skill points!  My helmet had some effects where it reduced my skill points upon wearing it, I didn't know armor could do that.  All my skill points are accounted for, sorry about this confusion and thank you for the help.

**Comment by Trixter313** [comment]
Glad to hear! =)
