### ISSUE TITLE
Underice quest broken

### ISSUE THREAD

**Issue by NinjaPiggy** [Wynncraft/Issues#4453]
When I start the "Underice" quest, the text appears as normal. However, when I try to go into the hole, it gives me the message "Fredris: Are you really trying to dive in that without the proper equipment?" and it will teleport me out. I think (I'm not sure) that's the text that will appear when you attempt to enter before starting the quest. What is going on?

**Comment by Moe-Ronickah** [comment]
You need to wear the Underwater Breathing Helmet from a previous quest.
