### ISSUE TITLE
lost all my skills

### ISSUE THREAD

**Issue by picachuthefirst1** [Wynncraft/Issues#4454]
i went on wynncraft to day and i look at me skills it said there were all 0 so i looked at my level and it was still 36 but i can't use and of my weapons now so is this a glitch???

**Comment by Moe-Ronickah** [comment]
Try changing classes or reloging on.  Those usually fix the problem.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/4304

Please direct any future comments to the original thread. Thanks!
