### ISSUE TITLE
Skill points all to 0

### ISSUE THREAD

**Issue by halo33** [Wynncraft/Issues#4455]
Yeah my skill points are all at 0, Level 73 with 14 in reserve so I can place them in things that need it. This needs fixed ASAP please. But it looks like wynncraft is going to be layed off until this can be resolved.

Minecraft name: Halo3

**Comment by Moe-Ronickah** [comment]
Log back on, and see if it persists.  If it does, try changing classes.  If those don't work, let us know, OK?

**Comment by halo33** [comment]
Alright that seemed to have fixed the issue. logging in and out. I closed my client as well and it appeared to have fixed it.

**Comment by Moe-Ronickah** [comment]
I'm glad that worked.  It seems to be the fix-it for this, for now.
