### ISSUE TITLE
WynnExcavation Site C Glitch With Crystals

### ISSUE THREAD

**Issue by MC-Tr0ll3r** [Wynncraft/Issues#4456]
So when I was doing the _WynnExcavation Site C_ quest and got to the bottom of the volcano there were no crystals, And to make sure someone wasn't just there I went server hoping and still nothing spawned but the mobs.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/4236

Please direct any future comments to the original thread. Thanks!
