### ISSUE TITLE
Quest Bug

### ISSUE THREAD

**Issue by XxBatman99xX** [Wynncraft/Issues#4463]
I can't do the Farmer Kelri quest because as you can see I have the Wedding Ring but it won't let me complete it.
![2016-03-05_14 32 07](https://cloud.githubusercontent.com/assets/17678415/13550302/4f7f38c6-e2e0-11e5-95fd-1908fb1bbade.png)

**Comment by Trixter313** [comment]
That isn't the real ring, you must go into a hole in the field underground to get the real ring. The real ring is a golden nugget.
