### ISSUE TITLE
Glitch with Classes

### ISSUE THREAD

**Issue by MemoTheEmo** [Wynncraft/Issues#4465]
I logged on today and my mage class was deleted, which was level 56 with a 40/40 white horse. To check if there was a bug I went onto my Hunter class and all of my skill points were gone? The skill points will probably come back, but is there anyway to get back my mage class?

**Comment by McSeed** [comment]
I had the same problem 4 days ago. First i simply restarted minecraft, but in second time i have restart my pc. It may be a problem with the Wynn pack and your pc just that moment.

**Comment by MemoTheEmo** [comment]
Nvm I accidentally deleted it ;/ carry on

**Comment by Trixter313** [comment]
I'm sorry for your loss.
