### ISSUE TITLE
Wynn Excavation site B no shards spawning

### ISSUE THREAD

**Issue by GlynOw** [Wynncraft/Issues#4468]
I'm trying to complete wynnexcavation site b and I'm in the purple shard cave but no shards are spawning on the floor, the quest book tells me to "talk to excavator lykron" but when I talk to him I get the response "Hello there! We are working very hard here at this... etc" and the quest stage does not change.

**Comment by Trixter313** [comment]
Duplicate of #4236 

Please direct any future comments to the original thread. Thanks!
