### ISSUE TITLE
Armor Glitching when Logging in

### ISSUE THREAD

**Issue by TheCatArchy** [Wynncraft/Issues#4470]
Anyone else having the issue, spawning without some armor/accessories and losing them? I just logged on and wasn't wearing my armor or accessories and my bracelet got deleted. 
This has happened to me multiple times now and I've lost a necklace, bracelet, and ring to it now. 
I'm terrified of losing my armor because it's really nice for my level. Can this please get fixed?
Necklace lost: Nutrition
Bracelet/Ring lost: ?? don't recall

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/4120

Please direct any future comments to the original thread. Thanks!
