### ISSUE TITLE
Seeing Certain items while in the shops Before you Identify them

### ISSUE THREAD

**Issue by facepoke** [Wynncraft/Issues#4471]
When i was interacting with the shops, there were items, that seems to be named such as the legendary chest plate called Blessed Warppings.

http://imgur.com/XNY1n0H

**Comment by RMH0131** [comment]
shut up that's useful don't fix it please

**Comment by Odnod** [comment]
Duplicate of #4059, please close this post and direct any additional comments to the original thread. Thanks!

**Comment by Moe-Ronickah** [comment]
facepoke, do you remember which shop this happened in?

**Comment by facepoke** [comment]
Well it happened in any of the shops

**Comment by DarkDemonDragon** [comment]
Then this definitely is a duplicate of #4059

**Comment by Moe-Ronickah** [comment]
@RMH0131 , please don't be rude.
