### ISSUE TITLE
Website Store

### ISSUE THREAD

**Issue by Rainbowro** [Wynncraft/Issues#4472]
I am trying to buy a rank but everything I click makes the website shaded and I can not do anything else on the website. I refreshed it and it did the same thing.

**Comment by TrashcanMan** [comment]
Have you tried using a different browser?

**Comment by Rainbowro** [comment]
I used safari on my phone and then Internet Explorer on my computer both did the same thing

**Comment by TrashcanMan** [comment]
I just tried on Chrome and it works fine.

**Comment by Moe-Ronickah** [comment]
Rainbowro, the entire website was having issues last night.  Is this fixed for you, yet?

**Comment by Rainbowro** [comment]
Yes the entire website and does not work today

**Comment by Moe-Ronickah** [comment]
If it's still not working, try clearing your browser cache.  If it's fixed, please the issue.  If it's a problem, please let us know.

**Comment by Rainbowro** [comment]
I cleared my browser cache still nothing

**Comment by Moe-Ronickah** [comment]
Do you have pop-ups blocked?  If they are, please turn them off for wynncraft.com and let us know what happens.

**Comment by Rainbowro** [comment]
It worked finally

**Comment by Trixter313** [comment]
Glad to hear!
