### ISSUE TITLE
/Leave Guild Not Working

### ISSUE THREAD

**Issue by ChiefInferno** [Wynncraft/Issues#4473]
Me and my friends made a guild and I am already in 1 so when I tried to leave the 1 I was in for my friends it took the soul points and said I left in chat but it didn't delete me from the guild, I think this was from my old name change so if there's a command that can kick me out plz do so, my ign is PierceTheVeil_ and I cant get some 1 in it to kick me because the guild is inactive

**Comment by Moe-Ronickah** [comment]
This issue is back.  It's a duplicate of #4320
