### ISSUE TITLE
Unable to See HP, Level, etc. of a Mob

### ISSUE THREAD

**Issue by ElectroMantis** [Wynncraft/Issues#4475]
This problem has been with me since the Gavel update, but because I already knew most of the mob levels in the Wynn province I decided I wouldn't do anything until now. I am unable to see the HP, level, elements and etc. of a mob and as the Gavel province is new to me, this severely affects me. Before the Gavel update, this was not a problem and I could see the names, HP and everything else on a mob, though for some reason, after Gavel, I could not see this. I have tried resetting my video settings, changing the resolution and even the allocated storage on Minecraft, and so far, nothing has worked. Please try to find out if this is a bug. Thank you.

**Comment by BasicallyNothing** [comment]
It may not be a bug, there is a mob or a few mobs that is like that, and it's not a glitch

**Comment by Moe-Ronickah** [comment]
Are you using MC 1.8.8 or higher?  If not, then there will be a large gap between mobs and the mobs information.  Also, are you using any mods that tell you how much damage a mob has taken?  Those mods don't work with the new Wynn information system.

**Comment by Verret001** [comment]
If changing versions or uninstalling mods doesn't help you could try deleting .minecraft?

Search> %appdata% Go application support> delete .minecraft

Please note that your worlds and your saved worlds and inventory will be deleted when you remove the files. If you want to keep your progress, you need to locate the saves folder and save it on your computer before you drag the .minecraft folder to the trash.

Hopefully this helps,

**Comment by ElectroMantis** [comment]
Hundreds of thanks to Moe-Ronickah for helping me solve my problems! Everyone else contributed too, and I would like to thank them for their support!
