### ISSUE TITLE
Golden Bars not poping out of the ground in Canyon Condor mission

### ISSUE THREAD

**Issue by Shadooow123** [Wynncraft/Issues#4477]
I'm at Canyon Condor mission and I cannot get any golden bars. Please fix this issue

**Comment by Moe-Ronickah** [comment]
Duplicate of #4236 
This is why there are instructions to help you do a search, first; it helps to prevent duplicates, and it can let you know that an issue is already known, so that you don't have to worry about it as much.
Thanks!
