### ISSUE TITLE
Lagging out cause of texture pack. Again. 

### ISSUE THREAD

**Issue by Zoee64** [Wynncraft/Issues#4479]
I have a issue logging into the game. I can walk around the lobby's perfectly well but when I join a server I time out. And I thought it was my computer at first but then my friend with a worse computer then me with no optifine could get onto the game no problem. Normally I crash when the texture pack loads. 

I've had this issue when Gavel first came out but then it just started working again 2 months later. If any one could help me find a solution to this it would be great help.

Thx

**Comment by Odnod** [comment]
You could try to disable server resource packs and have the wynncraft texture pack on as a normal texture pack.

If you want to know how to do thius, follow these steps.
1. Go into your .minecraft folder
2. Open up the Server Resource Packs folder.
3. Find a file named legacyzip or something along those lines.
4. Put a period between 'legacy' and 'zip'
5. Move the new zipped folder to your normal resource packs folder.

**Comment by Moe-Ronickah** [comment]
@Zoee64 , did you try following Odnod's instructions?  Did that solve your issue?

**Comment by RisingPhoenix01** [comment]
i've got the same problem. but that with the period isn't working, and my issue is that i can join the worlds but after a few seconds i get a timeout. can you help me to fix this?

**Comment by Moe-Ronickah** [comment]
@Zoee64 , did you, once again, try following Odnod's instructions?  Did you try to run WynnCraft in vanilla 1.8?

@RisingPhoenix01 , I would like to try to help you, but I don't understand what you mean by "but that with the period isn't working."  Could you explain that a little more, please?

**Comment by RisingPhoenix01** [comment]
my english is very bad, but i follow his instructions

**Comment by RisingPhoenix01** [comment]
and when i make this period and connect to a world, the resource pack is downloading again

**Comment by Odnod** [comment]
@RisingPhoenix01 move the legacy.zip folder to your resource packs folder, then disable server resource packs from Wynncraft.

**Comment by Moe-Ronickah** [comment]
Did you get this fixed?

**Comment by Moe-Ronickah** [comment]
Closed.  Without further response, I am assuming that the issue(s) was resolved.
