### ISSUE TITLE
Purple Crystals not Spawning in WynnExcavation Site B Quest!

### ISSUE THREAD

**Issue by Matt10y** [Wynncraft/Issues#4481]
I know you probably are trying to fix these issues, but it is really annoying! Please fix immediately!!!!!!

**Comment by liual1** [comment]
yup. im in the cave ryt now, tried relogging. Nothing happened. No crystals.. help me pls i cant finish the quest xD

**Comment by Trixter313** [comment]
Duplicate of #4236 

Please direct any future comments to the original thread. Thanks!
