### ISSUE TITLE
Lost all my stuff!

### ISSUE THREAD

**Issue by Craftingmario64** [Wynncraft/Issues#4486]
![screen shot 2016-03-06 at 2 49 26 pm](https://cloud.githubusercontent.com/assets/17692488/13557721/a7a6341c-e3aa-11e5-9cca-8da9c9d52707.png)
Hi. I just logged on today and selected my class like normal, but lost all my stuff! I still have the same level and completed quests, but just starter bows! I checked my ender chest and all my stuff is still in there. Please fix this and respond asap! 
![screen shot 2016-03-06 at 2 46 09 pm](https://cloud.githubusercontent.com/assets/17692488/13557688/6fc0fc44-e3aa-11e5-8792-df99dbb5bfcc.png)
![screen shot 2016-03-06 at 2 46 37 pm](https://cloud.githubusercontent.com/assets/17692488/13557691/6fe3ffc8-e3aa-11e5-95be-6ccef1b6cabf.png)
![screen shot 2016-03-06 at 2 47 48 pm](https://cloud.githubusercontent.com/assets/17692488/13557689/6fc3b4fc-e3aa-11e5-94da-1fc9dabf2a80.png)
![screen shot 2016-03-06 at 2 46 30 pm](https://cloud.githubusercontent.com/assets/17692488/13557690/6fdca0de-e3aa-11e5-9ef0-753157642944.png)
![screen shot 2016-03-06 at 2 46 15 pm](https://cloud.githubusercontent.com/assets/17692488/13557692/7017c1fa-e3aa-11e5-9d8e-8f82e8a3fd2c.png)

**Comment by Trixter313** [comment]
It appears that you were killed enough times to run out of soul points and your items were dropped on the ground. If you don't remember this, it could have happened while you were AFK or someone besides you could have done it. It could have been someone in the same house, a friend who knows your login credentials, or a stranger if you've ever logged into Minecraft on a public computer. You could have also been hacked and tricked into giving someone your login information. I'd suggest changing the password to your Minecraft account and the associated email to prevent this from happening again if that is the case. Hopefully this information helps!

**Comment by Craftingmario64** [comment]
Earlier this morning I was fine around 9 A.M PST. I log on a few hours
later and its all gone. If this happened, how did I get all the bows? I do
not want to start again, this is the second time this happened to me

**Comment by Trixter313** [comment]
When you die with no soul points it gives you an untradable bow.

It seems that you were killed many times with no soul points so when you respawned you just picked up the bows again then you were killed and dropped them and re-picked them up again etc.

Unfortunately Wynncraft has a very strict no refunds policy so even if it were an issue caused by the game itself, there wouldn't be anything we could do about the lost items.
