### ISSUE TITLE
Quest Glitch

### ISSUE THREAD

**Issue by IamExotic** [Wynncraft/Issues#4491]
Hi Wynncraft staff one of my quests are broken it is the WynnExcavation Site A Quest ive already done the whole thing but when i talkj to him to complete the quest he says something else and i didnt complete the quest.

so can you please just atleast reset the quest so i can do it again and complete it.

Link/Evidence: (https://youtu.be/ht8tNMxeYo4)

**Comment by Odnod** [comment]
You have to kill the Pharaoh (or whatever it is) at the end of the pyramid and get the yellow crystal shard.

**Comment by AThao1** [comment]
Yeah. you don't have the yellow crystals. You'll have to go back down into the pyramid and kill the boss again to get the crystal. It might work.

**Comment by IamExotic** [comment]
oh cus i didnt get any crystals before

**Comment by AThao1** [comment]
If it doesn't work then the quest is glitched. Lol. There's a bug that's messed up alot of quests that makes it so stuff doesn't spawn when you are at the right location but it doesn't spawn. The admins are working on it so don't worry about it.

**Comment by Odnod** [comment]
@AThao1 they actually just fixed it yesterday :)

**Comment by DarkDemonDragon** [comment]
@AThao1 actually that bug doesn't even apply because I think the crystal is a drop item not a spawned item.

**Comment by Moe-Ronickah** [comment]
@IamExotic, did you get the yellow crystal shard?  Where you able to complete the quest?

**Comment by Moe-Ronickah** [comment]
Closed. Without further response, I am assuming that the issue(s) was resolved.
