### ISSUE TITLE
Shattered Minds Glitch

### ISSUE THREAD

**Issue by WitherLogo** [Wynncraft/Issues#4497]
I'm having some problems with level 70 quest Shattered Minds. I'm not sure what caused it.

Firstly, I find Likeru? in the rainbow light forest with this in my quest book.
![2016-03-07_21 36 47](https://cloud.githubusercontent.com/assets/17715372/13590485/1311b420-e4ae-11e5-8f02-c85c4841d7ce.png)

But, when I talk to her, I get dialogue as if I already had spoken to her.
![2016-03-07_21 36 54](https://cloud.githubusercontent.com/assets/17715372/13590505/4156d964-e4ae-11e5-8b0e-d6d00be40177.png)

After that, I tried going into the house that Likeru? mentions, to go to the Yahya fight (strongest boss in the game), and this happens.
![2016-03-07_21 37 16](https://cloud.githubusercontent.com/assets/17715372/13590522/80180830-e4ae-11e5-8054-3aea176b452d.png)

I tried doing /class, /kill, but nothing seems to work. If somebody would help me with this, I would gladly appreciate it. My IGN is WitherLogo.

**Comment by Odnod** [comment]
Try entering the frog in the lake.

**Comment by WitherLogo** [comment]
Nevermind, I needed the Bluecap Mushrooms. Going to close this.
