### ISSUE TITLE
My character items are broken.

### ISSUE THREAD

**Issue by ichimo** [Wynncraft/Issues#4498]
I have an issue and only a really slow way of grinding to fix it.  All my armour and weapons are un identified leaving me weapon less.  My rotten flesh I planning on using to re identify my stuff isn't the right id not considering it an option to the junk merch.  Like I said the only way for me to fix this is to slowly grind my way back up to my old gear.

**Comment by Trixter313** [comment]
All items are unidentified the first time you login since the Gavel update. This isn't a bug and it shouldn't take too long to get the items identified.
