### ISSUE TITLE
Wynnexcavation Site C item is doesn't spawned

### ISSUE THREAD

**Issue by windopper** [Wynncraft/Issues#4500]
Wynnexcavation SIte C item(red crystals) doesn't spawned

WHAT HAPPENED?!?!?!?!?!?!?

**Comment by legoman72** [comment]
Same happened to me, I went down and back up multiple times yet no crystal shards spawned, I then tried doing /fixquests which then gave me 2 shards from B while I had already started C so I should only have one, I also had one in my inventory/enderchest. Also when I click on the starting NPC it says that I need a shard from B to start the quest while I already started it. Also my username for mine craft is lego_man724 if you want to look into account data and stuff.

**Comment by Trixter313** [comment]
When was the last time you checked for the crystal? This bug was fixed recently but it might be broken again. I'd suggest trying it one more time and seeing if it works now or not. Thanks!

**Comment by legoman72** [comment]
Three four days ago I think, is the weird quest NPC thing also fixed, I currently have 2 or 3 crystal shards from b when I only have one, also when I clicked on the starting NPC it acted like I hadn't started the quest yet, was that also fixed? Also a friend of mine also said that the gold in the mine wasn't spawning in in the canyon condor quest if you want to check that out. Also is there a way to fix items that still have the old defence tags from before the gavel update?

**Comment by Odnod** [comment]
@legoman72 the developers have fixed the bug where quest items did not fall to the ground, which affected many quests. I am afraid I do not quite understand your other problems, but old items are unfixable by just about anyone other than Jumla.

**Comment by DikkeHenk1989** [comment]
https://www.youtube.com/watch?v=c27VqqM6DXc

**Comment by Odnod** [comment]
@DikkeHenk1989 they fixed it.
