### ISSUE TITLE
I cant find a tp to selchar scroll where it says it is on the map 

### ISSUE THREAD

**Issue by dtoney02** [Wynncraft/Issues#4501]

**Comment by dtoney02** [comment]
pls help me as soon as possible i am trying to complete more quest than my friend and i need this tp scroll to go on with the quest

**Comment by Trixter313** [comment]
Could you explain a bit more? The scroll merchant should be right there.

**Comment by DarkDemonDragon** [comment]
Is this an in game issue or just an issue with the map?

**Comment by dtoney02** [comment]
the scroll merchant is not any where in the city i looked around the whole city and could not find it

**Comment by DarkDemonDragon** [comment]
Are you sure? It's right next to the fountain

**Comment by dtoney02** [comment]
i looked and could not find it unless i am blind

**Comment by DarkDemonDragon** [comment]
I'll confirm the location of the scroll merchant when I have time, but I know there is a shop there. Perhaps the NPC despawned.

**Comment by Odnod** [comment]
I was in the city two days ago for Tower of Amnesia. I can confirm that the scroll merchant is in fact still there and it is in the main circle of buildings around the fountain.

**Comment by DarkDemonDragon** [comment]
@dtoney02 please post a screenshot of where you think the NPC merchant is so we can point you in the correct direction.

**Comment by dtoney02** [comment]
i found him today but thx
