### ISSUE TITLE
 I can not select a class

### ISSUE THREAD

**Issue by TopChmo** [Wynncraft/Issues#4504]
I went to the server , put resurspak after crashes class selection window . I opt for a class , and then write it in the chat :
http://prntscr.com/ad4h94
Then he flies out the window classes and everything happens according to the new

**Comment by DarkDemonDragon** [comment]
Do /kill if you have 3 or more SP. This will send you to Ragni. You can also use a scroll if you have 2 or more SP. If this solved your issue please close this,

**Comment by TopChmo** [comment]
The first join . Write commands I can not.

**Comment by DarkDemonDragon** [comment]
Make sure Minecraft Launcher is up to date. Also what version of Minecraft are you using? If all else fails I suggest uninstalling Minecraft and then reinstall. Right now your character is stuck in a Limbo. You cannot use commands like this.
