### ISSUE TITLE
Forbidden Prison button?

### ISSUE THREAD

**Issue by DarraghWynn** [Wynncraft/Issues#4505]
So on my way through the quest Forbidden Prison and I have gotten to the section where you do the puzzle to get the prison key. Although I seem to have come across a problem. The button to open the door, isn't there. I have watched numerous youtube videos looking at where the button is and it is very clear that it should be on the *Chiseled Stone Brick* 

Switching servers does not work either as I have done it numerous times.

**Comment by Odnod** [comment]
You have to go up the stairway into a crack in the wall to activate something for the button to appear.
