### ISSUE TITLE
Quest Items

### ISSUE THREAD

**Issue by DrivenMC** [Wynncraft/Issues#4506]
I've been playing Wynncraft for a while and this has never happened, but all my quest items are glitched.

I try to do the guardian of the forest quest and when I give him Taproot it doesn't work and it says you need the quest item. My item is a quest item and it's not a untradeable item. Maybe that's it but I want to play Wynncraft again so I need this fixed, thanks.

**Comment by Odnod** [comment]
You also need to bring the volt goat horn. This is dropped by the volt goat which can spawn anywhere in the light forest.
