### ISSUE TITLE
Forums: 44kb>50kb?! My Profile Picture Predicament

### ISSUE THREAD

**Issue by Dravern** [Wynncraft/Issues#4507]
So, I upload my 44kb avatar, but it doesn't work. It says I need something less than 50kb. Like, seriously Forums, learn to math!

Here's my avatar-
https://40.media.tumblr.com/6ba5175fc86b738b6ca4e0062f5c3218/tumblr_o3s8wzyaZH1v9djgdo1_500.png

**Comment by DarkDemonDragon** [comment]
@Dravern try making it smaller with MS Paint or copy and paste it into Powerpoint, then reduce the side, and then save the image.

**Comment by Dravern** [comment]
I did that, but it did not work unfortunately.

**Comment by DarkDemonDragon** [comment]
I resized it. Try it now.
![dravern](https://cloud.githubusercontent.com/assets/15721340/13655049/9718e3ba-e62a-11e5-8844-a98fae09fa32.png)

**Comment by Dravern** [comment]
@DarkDemonDragon Nope. still doesn't work.

**Comment by DarkDemonDragon** [comment]
What does the message say? The image I gave is like 38 KB

**Comment by Dravern** [comment]
It says it has to be under 50kb, which I got well under with my attempts and it doesn't work.

**Comment by DarkDemonDragon** [comment]
Strange... try changing your profile picture to something else to see what works. If all images don't work perhaps there's something wrong with your account or just the site in general.

**Comment by Dravern** [comment]
I did. All of my previous avatars work other than the one I had last, making me have an old avatar, which sucks.

**Comment by Moe-Ronickah** [comment]
For now, I'm labeling this as a website issue.  I have seen, on occasion, where the meta data on an image file is messed up, and the file itself says that it is larger than it really is.  Try changing the file type, then see if you can upload it.  Changing type always rewrites the file meta data.

**Comment by Moe-Ronickah** [comment]
@Dravern , I know that you put a new avi up, but did you try my idea, above?  Did it work, or not?
