### ISSUE TITLE
gear dissapearance

### ISSUE THREAD

**Issue by RareGamerz** [Wynncraft/Issues#4508]
i was farming some mobs when i saw that the server was restarting, then i just switched to another server but when i was logged in, my stats were all 0 and this happend a couple of times to me. so i relogged again and because you need stats to wear gear my gear went to my inventory but i was holding to much stuff and now all my accessories are gone, PLS FIX PLS

**Comment by BlahBlah161616** [comment]
I lost a ring to this same glitch, the admins have already stated that it's a hard bug to fix, and are working on it. The item should have dropped onto the ground.

**Comment by RareGamerz** [comment]
no it didn't ,_,

**Comment by DarkDemonDragon** [comment]
Duplicate of #4120 Please close this issue. Also make sure you look around at the ground because gear now just falls off instead of disappearing.

**Comment by BlahBlah161616** [comment]
DarkDemonDragon, not my gear, with my luck it drops on a server restarting in 10 seconds, so I don't have the time to pick it up.

**Comment by DarkDemonDragon** [comment]
Are you sure? The skill bug happened to me like 10 times and the armor falls off consistently now. This may be due to the skins being removed.

**Comment by BlahBlah161616** [comment]
It's not, it's due to buggy skill points.

**Comment by DarkDemonDragon** [comment]
No I mean that items fall off because of armor skins being removed.

**Comment by Moe-Ronickah** [comment]
Please use the search function as explained on the front page.
