### ISSUE TITLE
Player Relocation On Join

### ISSUE THREAD

**Issue by DRedDogPE** [Wynncraft/Issues#4510]
I logged out with my assassin class at Nemract and when i logged back into the server 3 hours later i was at `Z: 0 X: 0 Y: Falling in void` and i had to use /kill and when i did i got teleported to Elkurn. This glitch has also happened before where i have been trapped in the location in the mountain next to ragni where you are teleported to when you use /class. Please can this be fixed as i dont want to have the possibility of logging in and loosing all of my items because i run out of soul points due to this bug.

**Comment by DarkDemonDragon** [comment]
Screenshots would be helpful and does this happen a lot? It'd help staff out a lot if you explain how this usually happens. Also, if you find yourself in this situation again make sure to check how many SP you have. If you don't have enough or you're not comfortable being lowered to much just switch to another class and let the trapped class gain some SP before doing /kill with it.
