### ISSUE TITLE
Out of date quests [Hallowynn, Craftmas Chaos]

### ISSUE THREAD

**Issue by DRedDogPE** [Wynncraft/Issues#4511]
These quests appear when they are unable to be done because the NPC's have been removed.

![Hallowynn](http://i.imgur.com/mFJVIO3.png) ![Craftmas](http://i.imgur.com/WmNSLrP.png)

**Comment by DarkDemonDragon** [comment]
Actually these quests are 100% doable  As many players have done these quests recently. Please go to the indicated coordinates, press F3 to show your own coordinates, and take a screenshot of the area.

**Comment by DRedDogPE** [comment]
Oh ok, My friend told me that the NPC's were removed and that they were bug quests.
