### ISSUE TITLE
WynnExcavation Site B End

### ISSUE THREAD

**Issue by Timcampy** [Wynncraft/Issues#4512]
At the end of this quest I've been teleported in a wall with no way to escape. I know I can type /kill and I've done it but I notify it so it can be fixed and following players won't loose 3 soul point because of a bug.

Hope it will help.

Thanks for reading.

P.S. : Please notice that if my grammar/conjugaison is bad, it's because english is not my native language.

**Comment by DarkDemonDragon** [comment]
Are you inside a wall or just in a small hole? If you are in a small hole this is correct. There is a button that will let you leave.

**Comment by Timcampy** [comment]
No I was stuck in a block with no way to escape

**Comment by DarkDemonDragon** [comment]
Hmm could have been Teleportation lag. I'll test it a couple times and see if I get stuck

**Comment by Timcampy** [comment]
Okay thanks, I should have taken screenshots and xyz, it may have helped

**Comment by DarkDemonDragon** [comment]
Could you see any NPCs near you when you got stuck?

**Comment by AThao1** [comment]
This happends because you didn't have the purple crystal. The purple crystal is suppose to be dropped when you enter the chambers with the giant purple glass crystal in the center of the ceiling. It didn't drop because all the items in the world of wynncraft that are suppose to spawn are broken atm. I looked into this already so yeah... Btw. You'll have to do /kill to get out of the wall. But the quest itself will be broken. You won't be able to do it until they fix it. So just quit on the quest if so.

**Comment by Moe-Ronickah** [comment]
Timcampy, please be certain that you are not holding down any of your movement keys, also, as this may cause this error, also.

**Comment by Timcampy** [comment]
As I remember it, I had the purple cristal, I didn't see any NPC and didn't hold my movement keys. Also I did use the /kill but it didn't broke the quest. The lag could be a valid explanation.

**Comment by AThao1** [comment]
Well. Me and another guy had the same case as this guy. Then as we came back to the quest guy at the front of the entrance he didn't say anything or do anything. We didn't have the purple Crystal and we knew where it spawned.

**Comment by Mrtenz** [comment]
Here's a screenshot with the coordinates:
![Help](http://g2f.nl/00plns1)

**Comment by AThao1** [comment]
Oh yes. You do get stuck in the ground. I just did it. But now since the purple crystal drops. You can comeplete the quest if you do /kill.

**Comment by Timcampy** [comment]
Yeah I know, it was just for it to be fixed to avoid annoying situations for next players, like having to wait 20-60 mins to get four soul point so you don't loose your stuff.

**Comment by Moe-Ronickah** [comment]
You should not be getting dropped in the ground.  This is definitely one for the builders.

**Comment by Moe-Ronickah** [comment]
Fixed.
