### ISSUE TITLE
Name/Level/Hp Glitcg

### ISSUE THREAD

**Issue by NLNick7** [Wynncraft/Issues#4513]
you cant see the hp of the mob or his name or level hoop you can fix it

**Comment by DarkDemonDragon** [comment]
Please provide screenshots as this could just be an issue with specific mobs.

**Comment by NLNick7** [comment]
oke

**Comment by NLNick7** [comment]
how can i do that a screen shot

**Comment by NLNick7** [comment]
but i cant place a screen shot

**Comment by DarkDemonDragon** [comment]
Because you don't know how to or what? Github is compatible with all files. If you need an explanation on Evidence please check out my guide on the forums: https://forums.wynncraft.com/threads/evidence-ban-reports-bug-reports-etc.116166/

**Comment by NLNick7** [comment]
it is over i had wrong versieon

**Comment by NLNick7** [comment]
but tnx for help

**Comment by DarkDemonDragon** [comment]
Alright please close this issue by pressing the close button at the bottom
