### ISSUE TITLE
Un-Identified Item seeing

### ISSUE THREAD

**Issue by minetech48** [Wynncraft/Issues#4515]
# Delete this line if you've searched for a duplicate issue first
1. If you look into a merchant it will tell you what an item is (in your inventory) along with other information about the item.

2. If you drop an item (Un-Identified) on the ground it will change textures to the items texture.

**Comment by DarkDemonDragon** [comment]
Please search for duplicate issues beforehand.
1) Duplicate of #4059 
2) Duplicate of #3318 

Please close this.
