### ISSUE TITLE
SAVE ME

### ISSUE THREAD

**Issue by KoalaDharBear** [Wynncraft/Issues#4516]
[https://gyazo.com/f1bc30f5eb027ed71f55294f30981ac4](url)
Send help
> Tried restarting game
> Tried /server and new lobbies
> My archer class works but my (main) mage is stuck
> TRIED TO UPLOAD A VID BUT MY YT IS ACTING UP NVODEOOVJSOd
Please help, i'm losing it ;-;

**Comment by KoalaDharBear** [comment]
I'M A BLOODY GENIUS !! /KILL AND IT WORKED WOOOOOOOOOOOOOOOOOOOO!!

**Comment by Odnod** [comment]
If your issue has been fixed, please close it.
