### ISSUE TITLE
Items disappearing in inventory

### ISSUE THREAD

**Issue by JediArcanaan** [Wynncraft/Issues#4517]
So, I was in my inventory (on my mage account) when all of a sudden, the game froze. I spent a long time trying to fix it, but nothing worked. So, I just exited Minecraft altogether. Then, when I went back onto my mage account, my two best wands were gone... They're not in my inventory or my bank. Before this happened, I spent a long time getting to level 44 so I could use the Frozen Brook (my best wand)... And I was so excited to use it. Now it's gone :/ PLEASE HELP!

**Comment by Moe-Ronickah** [comment]
I hate to be the bearer of bad news, however, WynnCraft has a strict no-refunds policy, so there is no way for anyone to give you your lost items back.

The admins are aware of this problem, and they have been working on it.  It doesn't help if I say "you're not alone", but it is the truth.  Ask around in Detlas, and maybe some kind player will give you a wand to help.
Good luck, and happy Wynning.
