### ISSUE TITLE
Cowfusion Boss Head Glitched

### ISSUE THREAD

**Issue by xApX3** [Wynncraft/Issues#4519]
Hello, the end of the cowfusion quest is glitched. i dont have his head. i talked to the hopper and the key doesnt do anything. i have no idea how to fix it. ive done it over and over again and havent gotten the head. please help 
![2016-03-10_15 25 34](https://cloud.githubusercontent.com/assets/17170811/13683372/540d4084-e6d4-11e5-801b-b1742571452d.png)

**Comment by TrashcanMan** [comment]
Have you tried /fixquests?
