### ISSUE TITLE
Grave digger impossible to complete

### ISSUE THREAD

**Issue by Wumbology7** [Wynncraft/Issues#4520]

**Comment by Wumbology7** [comment]
I was doing the Grave digger quest and got to the part where I had to turn in 24 rotten flesh. After it said "_Quest book updated,"_ it said to bring 3 flesh of the corrupted, 1 shattered bone from the skin-less, and 1 twisted spider eye, so he could brew up a cure. I presume it executed the wrong quest, but he quest book still says to bring in 24 rotten flesh. Please help.
![screen shot 2016-03-10 at 7 14 54 pm](https://cloud.githubusercontent.com/assets/17773693/13689112/6a785cbc-e6f4-11e5-986b-a1f5d52f19d8.png)
![screen shot 2016-03-10 at 7 15 37 pm](https://cloud.githubusercontent.com/assets/17773693/13689120/8553ccd8-e6f4-11e5-905e-2d81bcb7baf9.png)

**Comment by Trixter313** [comment]
What happens when you try to bring 24 flesh to the priest now?

**Comment by Trixter313** [comment]
Oh, I see you made another issue https://github.com/Wynncraft/Issues/issues/4522
