### ISSUE TITLE
Close

### ISSUE THREAD

**Issue by gettodachopa** [Wynncraft/Issues#4521]
Theres some glitch with the deletion of the classes, it was showing 1 day left this morning and now the deletion timer disapeared and is showing to ritght click to delete again... i right click and the timer started from the beginning 3 days and 9 hours again...

cmon, force delete my level 81 assassin  
my nickname Lusitano27BC

**Comment by Moe-Ronickah** [comment]
As you were told on the forums, I think, only an admin can force delete an individual player's class.  So, you will have to contact an admin in game and try to get help, or, send an email to support@wynncraft.com, tell them what is going on, and ask for help.  In the meantime, the timer reset is either bugged, or it's running on a different clock than it appears to be on, just like the loot chests do.

**Comment by gettodachopa** [comment]
My bad, i think I miss click and entered on the class yesterday, and when you left click the class it cancels the deletion, I just noticed it today when i took a print screen of it...

Close
