### ISSUE TITLE
Grave digger impossible to complete

### ISSUE THREAD

**Issue by Wumbology7** [Wynncraft/Issues#4522]
I was doing the Grave digger quest and got to the part where I had to turn in 24 rotten flesh. After it said "Quest book updated," it said to bring 3 flesh of the corrupted, 1 shattered bone from the skin-less, and 1 twisted spider eye, so he could brew up a cure. I presume it executed the wrong quest, but he quest book still says to bring in 24 rotten flesh. Please help.
![screen shot 2016-03-10 at 7 14 54 pm](https://cloud.githubusercontent.com/assets/17773693/13689294/ef687fe6-e6f5-11e5-916e-75ddf967554f.png)
![screen shot 2016-03-10 at 7 15 37 pm](https://cloud.githubusercontent.com/assets/17773693/13689297/f2862480-e6f5-11e5-804f-e882041ca66e.png)

**Comment by TrashcanMan** [comment]
Not sure how that makes it impossible...
Just bring both the items in the chat and the items in the quest book and see which one works. It should be the 24 rotten flesh unless it got updated recently.

**Comment by Moe-Ronickah** [comment]
From the chat: 3 rotten flesh, 1 bone meal from a skeleton, and 1 (twisted?) spider eye.  It really sounds like the quest is being updated, but the quest book and the quest chat are not synchronized.  Which is right?  Get 24 rotten flesh and the other items, and let us know.  My guess is, it's going to be 24 rotten flesh as I haven't seen any chatter about any very recent update.

**Comment by Odnod** [comment]
It is still 24 rotten flesh, pay no heed to the dialogue as it was probably something that was planned but not implemented.

**Comment by Moe-Ronickah** [comment]
@Wumbology7 , did the quest work 24 rotten flesh?

**Comment by Wumbology7** [comment]
As is turns out, | wa using the old rotten flesh, without the subtitle "junk item." Thanks for helping.

**Comment by Trixter313** [comment]
Ah, I see. Glad to hear!
