### ISSUE TITLE
Died in fight against Gregg'r, got teleported to tutorial area

### ISSUE THREAD

**Issue by Mrtenz** [Wynncraft/Issues#4523]
I died while fighting against Orc Leader Gregg'r for the quest Green Skinned Trouble. I got teleported all the way back to the tutorial area and then to Ragni...

**Comment by Moe-Ronickah** [comment]
This is not a bug.  You will get teleported to the nearest city whenever you die, and the Gregg'r fight is off of the main map, with the closest city being the tutorial area.
