### ISSUE TITLE
Horse not spawning

### ISSUE THREAD

**Issue by bcl31** [Wynncraft/Issues#4524]
When i use my horse it spawns for a millisecond then de-spawns and my saddle reappears, only been able to mount it once, once i mount it it stays but it is nearly impossible to do so. yes, i did try two different horses, neither of them worked

**Comment by DarkDemonDragon** [comment]
Mind posting a video recording? My horse works just fine.

**Comment by Moe-Ronickah** [comment]
@bcl31 , is this issue fixed?  If it is, it was probably some transient bug, but I'd like to be certain.  If it fixed itself, would you please close this issue?  If it's still happening, we'd really like to help.

**Comment by bcl31** [comment]
the horse still is not fixed, working on getting a video of it

**Comment by bcl31** [comment]
uploaded video to you tube, link here https://youtu.be/10XZ6bQyjuk

**Comment by DarkDemonDragon** [comment]
What version of Minecraft are you using? The Wynnpack also seems to be broken for you. I recommend first switching to 1.8 and if that doesn't work, then reinstall Minecraft.

**Comment by aaryanbatra** [comment]
I'm having the same problem, I went to 1.8 and it worked but the fences are messed up and doing quests then just gets hard because the fences look like messed up blocks. When can you get this to work in 1.9 (the horse glitching)

**Comment by DarkDemonDragon** [comment]
@aaryanbatra mind making a separate report with pictures about the fences?

**Comment by aaryanbatra** [comment]
@DarkDemonDragon Oh it's ok I went to 1.8.9 and those problems are gone, Im able to place the horse in 1.8.9 and it doesn't glitch. The main problem is that if possible the problem gets fixed for 1.9

**Comment by bcl31** [comment]
thanks i switched to 1.8.9 and now it works thanks

**Comment by aaryanbatra** [comment]
Why is it closed though, it's still an issue for 1.9 right? I mean it's fine that we can just do 1.8.9, but I guess in the future this could get fixed. Thanks everyone :)

**Comment by DarkDemonDragon** [comment]
Yea 1.9 is still a WIP so they're constantly working on it.

**Comment by aaryanbatra** [comment]
Thanks! I appreciate it
