### ISSUE TITLE
Error After Class Switch

### ISSUE THREAD

**Issue by TopHatProductions115** [Wynncraft/Issues#4525]
Recently, I have run into an issue that is a bit costly in nature. Whenever I change classes, I run the risk of, instead of being teleported to where I previously was, being sent to what looks like a dark area. I can't see anything when that happens (except for GUI and current weapon), and can only escape by using a Teleportation Scroll while looking straight up. In addition to this, the console also says that I don't have permission to enter the area. Almost every time this happens, I was sitting in a public area before it happens- usually, a bank. It happens inconsistently, and I have no idea how or why this occurs. Please help.

**Comment by DarkDemonDragon** [comment]
This is an old bug. Please close this as it has been reported numerous times. Another way to exit the box is to do /kill. Unfortunately, this bug is nearly impossible to get rid of as the nature of it is entirely due to lag which obviously is impossible to 100% eradicate.

**Comment by TopHatProductions115** [comment]
I intend to close this issue as requested. However, I need to ask this as well - does the /kill command require elevated permissions, or is it accessible to general players on WynnCraft servers?

**Comment by DarkDemonDragon** [comment]
Everyone can do /kill. It sends you to the nearest town and costs 2 SP.
