### ISSUE TITLE
Set/Dyed Armor is Undyed/Colorless when it drops from mobs.

### ISSUE THREAD

**Issue by ThunderRemix** [Wynncraft/Issues#4526]
I'm sure you all have seen it before. Leaf, Nether, Adventurer, and other set items that are supposed to be dyed are not when the items drop from mobs. I believe this is unintentional, seeing how the Item API lists the items with armorColor values.

#3903 got closed without any resolution or explanation.

**Comment by DarkDemonDragon** [comment]
Just ask @Trixter313 or @Moe-Ronickah to reopen it for you.

**Comment by Moe-Ronickah** [comment]
Reopened #3903
