### ISSUE TITLE
Wand with the ancient stats

### ISSUE THREAD

**Issue by Creecreeprs** [Wynncraft/Issues#4528]
I don't no why, just see : [https://i.imgur.com/UemOXKc.png](url)
I drop it in Neesak on an Hungry Wendigo.

**Comment by DarkDemonDragon** [comment]
The picture doesn't work for me

**Comment by DarkDemonDragon** [comment]
Nevermind Github is being weird with imgur links
Also all items with an accent will break.

**Comment by atz775** [comment]
Btw, to get pics working u just need to highlight the link and paste ¬-¬

**Comment by DarkDemonDragon** [comment]
ik that's why I said "Nevermind Github is being weird with imgur links"

**Comment by Moe-Ronickah** [comment]
@Creecreeprs : 
1: Do you still have the wand?
2: Was this a wand that you recently obtained, or was it an old wand that you had in your inventory?
3: If you got it recently, did you find it on the ground or was it from a mob drop or loot chest?

**Comment by Creecreeprs** [comment]
@Moe-Ronickah 
1 : I throw it because I thought I toke a screen (and I don't have much place in that time)
2 : 2 days ago
3 : Like I said, in an Hungry Wendigo in Nesaak

**Comment by DarkDemonDragon** [comment]
@Moe-Ronickah seems like this bug is still persisting even with new drops.

**Comment by Moe-Ronickah** [comment]
There was a recent fix pushed in the past 12 hours.  As we have no way to diagnose this issue with Creecreeprs any further, I'm closing his issue.

**Comment by Trixter313** [comment]
Fixed image. You **must** put the link where it says URL, between the parentheses. **Not** between the brackets! =)

**Comment by Creecreeprs** [comment]
Thx and sorry ^^

**Comment by atz775** [comment]
Yeah but I was saying what you need to do to fix it duh :P
