### ISSUE TITLE
Not sure Where This would Go. 

### ISSUE THREAD

**Issue by saintdevin** [Wynncraft/Issues#4530]
I Went to use a teleport scroll and crashed right as I used it so I have been unable to log back onto the server for the last 20 minutes. My friend said it just looks like I am floating there.
![error](https://cloud.githubusercontent.com/assets/17796412/13722311/349fb394-e80f-11e5-9af7-5531fe0bef08.PNG)

**Comment by DarkDemonDragon** [comment]
First try relaunching Minecraft. If this doesn't work you'll just have to wait a moment. If the issue persists after an hour reinstall Minecraft. I'm sorry I can't offer any more help, but this seems to be a Minecraft issue as opposed to a Wynncraft Bug.

**Comment by Moe-Ronickah** [comment]
Are you back in game, or is this problem still happening?
