### ISSUE TITLE
Status bug disappeared

### ISSUE THREAD

**Issue by flowRearB** [Wynncraft/Issues#4532]
# Delete this line if you've searched for a duplicate issue first
Today (March 12), was to occur Baku status disappears account is called flow_RearB, Lv, possession item was not only the status disappears as it is.
It is not even in the remaining are state not by SP is distributed, it has disappeared as well equipped.
(In the status shortage)
And as much as possible early correspondence please
(When was the staff of the Japanese is even more thankfully)

**Comment by DarkDemonDragon** [comment]
Sorry, I can't understand. Please use Japanese. I will try my best to translate. Also please provide pictures.

**Comment by flowRearB** [comment]
すいません、今日入ったら治っていました。
でも装備一式がステータスが足りず、はがれて消えてしまったのですが保証ってしてもらえるのでしょうか？

**Comment by DarkDemonDragon** [comment]
Ok, I think I get it. I'm sorry, but my Japanese is really bad. My response will be in English. I'll **bold** important words

1) Wynncraft has a **no refund** policy. This means your **item** will **NOT** be **returned**.
2) This is a **duplicate** of **another issue** #4120 
3) This **error** is **caused** when the server **lags** and you have **0 skill points**. When this happens any **armor** that **needs skill points** will **fall off**. However, you have **time** to **pick up** the **armor** and **put it back on**. When **armor falls off** quickly **find** it and **put it on**.

ごめんなさい, 私はより多くのを助けることがしたいです.
