### ISSUE TITLE
Test Spear, Test Boots and Test Chestplate

### ISSUE THREAD

**Issue by Creecreeprs** [Wynncraft/Issues#4534]
I found this 3 items in a guild attack.
The picture are here : 
[https://i.imgur.com/Z55vJyq.png](url)
[http://i.imgur.com/c7N5RHS.png](url)
[https://i.imgur.com/22z4xOZ.png](url)

**Comment by DarkDemonDragon** [comment]
Images don't work

**Comment by KokeCacao** [comment]
It's so cool! How about try identifying... Will it disappear? Or return null message to server?
@DarkDemonDragon you can just copy the link. Do not click.

**Comment by Creecreeprs** [comment]
@KokeCacao I will try it
@DarkDemonDragon Sorry for the link,I think its a bug of Git Hub

**Comment by MisterMisterious** [comment]
you can just copy and paste them.

**Comment by Moe-Ronickah** [comment]
Apparently, this bug is happening again.  @Creecreeprs , you MUST destroy those items, as 1) they are illegal to keep, and 2) they will never be identifiable.

**Comment by ThunderRemix** [comment]
@Moe-Ronickah You don't keep items from wars...

**Comment by Trixter313** [comment]
Edited pictures to work
