### ISSUE TITLE
MEMORY PARANOIA MASTER BEDROOM GLITCH

### ISSUE THREAD

**Issue by yeeaah** [Wynncraft/Issues#4535]
I got the master bedroom key and didnt get teleported. Ive been running around for like an hour trying to find barriers that will tp me or something. No luck. Please help

**Comment by Moe-Ronickah** [comment]
This is probably not a glitch.  Check here to see where you are: https://wiki.wynncraft.com/index.php?title=Memory_Paranoia .
Let us know if this helps, or if the next step really isn't there.

**Comment by yeeaah** [comment]
i got it fixed, it turns out its cause i died and i had to redo the quest to get back to the area

**Comment by Odnod** [comment]
If your problem has been solved, please close your issue. Thanks!
