### ISSUE TITLE
Dungeon Glitch

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#4538]
I was planning on doing the Skeleton Dungeon 20 times just to get EXP. The 18th time I completed it this happened. I have absolutely no idea what just happened, but it appeared to give me the double of what I was supposed to get. Here's a screenshot.
http://imgur.com/dkWlci6

Just to confirm that this is a bug you can notice that the dungeon man only said that the message once, which means I only did it once, but got it twice.

Thanks.

- Nothing

**Comment by DarkDemonDragon** [comment]
When this happened did you kill the boss twice? (boss respawned and you didn't get teleported) Also was the server laggy when this happened?

**Comment by Moe-Ronickah** [comment]
Almost two months out, and no response.  Maybe there was a 2X xp bomb on?

**Comment by DarkDemonDragon** [comment]
@Moe-Ronickah no this is happens randomly because of lag. It's not just xp, you also get double the keys.
