### ISSUE TITLE
Tp wrong city.

### ISSUE THREAD

**Issue by EJCrusher** [Wynncraft/Issues#4540]
Yeah so I was doing shattered minds quest near that city, I run around apparently get teleported to a memory paranoia thing, which is still near shattered minds (-1000 x ) and then i /kill to get out SINCE THERE IS NO WAY OUT and I TELEPORT TO DAMN OLUX.

**Comment by Moe-Ronickah** [comment]
When you die, or when you use /kill, you will get teleported to the closest city, by map coordinates.  So, that's not a problem.

However, somehow jumping from Shattered Minds to Memory Paranoia is a problem.

**Comment by shinyafro** [comment]
yeah the area to teleport into the manor is all around the house, not just near the door. i have completed the quest and have went by the manor to get sucked into its event horizon of no escape so i just /kill to save me an hour of my life. like literally i can be like 50 blocks away from the inside of the manor and i get sucked in.

**Comment by Moe-Ronickah** [comment]
Fixed.
