### ISSUE TITLE
Skill Reset Glitch

### ISSUE THREAD

**Issue by RagnStivins** [Wynncraft/Issues#4543]
I have wasted 2 LE trying to reset my skills via the scrolls. It lets me distribute the skills points, but when I'm finished; the points are placed in areas I never put them. I bought another scroll to fix this issue, but it didn't work.

**Comment by Odnod** [comment]
Armor and weapons can put additional points into stats, are you sure that this is not what is happening?

**Comment by Creecreeprs** [comment]
Did you try /class ?
