### ISSUE TITLE
Stuck In Class Choosing Room 

### ISSUE THREAD

**Issue by sonpiJP** [Wynncraft/Issues#4544]
I played a lot on other characters and then when I switched to my archer character it didn't tp me out of that class choosing room but instead I stayed there and now I'm stuck. Can an Admin pleas fix this and tp me out of there. I really want continue playing on my character that got stuck.

**Comment by TrashcanMan** [comment]
Do /kill with at least 3 soul points.

**Comment by sonpiJP** [comment]
Ok thank you

**Comment by sonpiJP** [comment]
It worked ;D thx a lot
