### ISSUE TITLE
Memory paranoia tp not working properly

### ISSUE THREAD

**Issue by MisterMisterious** [Wynncraft/Issues#4545]
After I completed the quest and had come back from doing a different one I walked past the Erca Mansion and I got teleported back into the mansion. I had to kill myself to get out... Also the quest didn't give me 3000 something emeralds but only 5 EB

**Comment by Moe-Ronickah** [comment]
First "issue": it's not.  Every quest allows you to go back into it, in case you die, or in case you want to help someone, or just in case you want to re-run through the quest.

Second issue: you should have gotten 48EB.  You may not have realized that the EB in your inventory increased, your inventory may have been full, there may have been a glitch with the reward.  I'm sorry, but in any event, WynnCraft has a strict no-refunds policy, and there is nothing that we can do to help.

**Comment by MisterMisterious** [comment]
My first issue was that I ran past the back of the mansion and not anywhere near the 'tp zone' at the front. I don't know if it is intended to tp you then but I didn't think so. Should've described it better that's my bad. The second one was just checking if it wasn't happening to more people in case it was an actual bug.
