### ISSUE TITLE
Health Decreasing for no reason.

### ISSUE THREAD

**Issue by DRedDogPE** [Wynncraft/Issues#4546]
Shown in this video
https://youtu.be/ddvmq5i4J-o

**Comment by Creecreeprs** [comment]
Check in you'r compass you'r IDs (right click on the compass then put you'r mouse on you'r head) and see if they are an health regen negative like: - Health Regen : -17 (and not in %)

**Comment by Moe-Ronickah** [comment]
@DRedDogPE , is this solved, or not?

**Comment by DRedDogPE** [comment]
I think so.
