### ISSUE TITLE
Character-Choose-Box-Bug

### ISSUE THREAD

**Issue by DeathlyPhantom** [Wynncraft/Issues#4547]
Please Help me, I stuck in this Character-Choose Box. I Choosed my Mage-Character and then I don't teleportet in Detlas, I was still logged in with my Armor and etc. in this Wool-Box amd i can't get out. With my other Character is all still working, but my Mage is the strongest Character and I don't want to do a new start with my Mage Please Help me

**Comment by stoneenderman** [comment]
i had this problem too and despite wanted to do this i had to do /kill ... it should teleport you to the city but just make sure you have enough soul points to not lose your stuff

**Comment by Moe-Ronickah** [comment]
@DeathlyPhantom , did /kill (with more than 2sp) work?  If it did, would you please close this issue?  If it didn't, let us know what is going on with your mage.
