### ISSUE TITLE
Troubled Tribesman & Flight in Distress glitches

### ISSUE THREAD

**Issue by qhastly** [Wynncraft/Issues#4549]
It will not let me finish Troubled Tribesman (even when i had the item, i got rid of it since it was taking up inventory space), and whenever I speak to the quest starter for Flight in Distress, it won't let me. Although in my quest book it says I've started it, but I never get anything saying that the quest was started.
I'm level 75, so I am the required level to do the quest.

**Comment by Odnod** [comment]
So for flight in distress, you first need to have completed the quest "Acquiring Credentials." And for Troubled Tribesmen, try going back through the quest without using charge, teleport, leap as they can sometimes cause you to miss regions that advance the quest.

**Comment by Moe-Ronickah** [comment]
@qhastly , please do not combine issues into one report.  It's better to keep them separate so that we can work on them.

Did Odnod's advice help, or are you still stuck in these quests?

**Comment by AckroWynn** [comment]
If you completed Acquiring Credentials, and you had the passport when talking to the Flight in Distress starter, then I'd tell you to simply move in to the airship.
