### ISSUE TITLE
Broken Wand for mage kit

### ISSUE THREAD

**Issue by PhoenixRemast** [Wynncraft/Issues#4550]
# Delete this line if you've searched for a duplicate issue first
https://gyazo.com/eb6ac7d80cbb4df1d0d9a67edc76fe9c
I cant use it and no skills work it only does 1 damage
its old name was devourse or something
please fix it!

**Comment by Sandertv** [comment]
Yep I had the same, Devoureuse.

**Comment by Moe-Ronickah** [comment]
First, your link isn't to anything WynnCraft related.
Second, it's a **duplicate** of #3161 .
Third, there was a patch pushed out in the past twelve hours, so it should be fixed.  It it isn't fixed, you can follow #3161 to see when it gets fixed.
