### ISSUE TITLE
Winter's Essence Drains health every few seconds

### ISSUE THREAD

**Issue by LeafyWizard** [Wynncraft/Issues#4551]
The Legendary Pants **Winter's Essence** drains health every few seconds. 
![2016-03-13_13 55 11](https://cloud.githubusercontent.com/assets/8340278/13731323/3fb30866-e923-11e5-90ba-886764b18dfd.png)
I bought it off of a guy that had the same problem. It didn't happen for like a week or so until now.

**Comment by ThunderRemix** [comment]
-17 Health Regen?

**Comment by LeafyWizard** [comment]
-19

**Comment by ThunderRemix** [comment]
That's why?

**Comment by LeafyWizard** [comment]
Idk but I'm pretty sure [- Health Regen] is supposed to drain your health, just make the Regen time slower

**Comment by Moe-Ronickah** [comment]
Negative Health Regen **will** drain your health.  You need armor that overcomes this, or your health will go down.  It's not supposed to kill you, but it will hurt you, a lot.  Don't go AFK with an overall negative health regen stat, unless you want to test out the "supposed" part.
