### ISSUE TITLE
Can´t play Wynncraft

### ISSUE THREAD

**Issue by RisingPhoenix01** [Wynncraft/Issues#4552]
everytime i go on the lobby, nothing is wrong, then i join into a world, i download the resourcepack and after a few seconds i would be kicked out and there stands: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
can someone help me please

**Comment by TrashcanMan** [comment]
It's probably temporary, just wait an hour or two and try again, or try restarting your computer/Minecraft/router etc. If this resolves your issue please close this issue. Thanks!

**Comment by DRedDogPE** [comment]
It will be your internet connection. This happens to me alot when I tab out of mc while connecting to the server.

**Comment by Moe-Ronickah** [comment]
It's definitely a MineCraft issue.  There is a brief discussion of it, and a solution for it, at http://www.minecraftforum.net/forums/support/unmodified-minecraft-client/2444668-how-to-fix-internal-exception-io-netty-handler
