### ISSUE TITLE
Resource pack not working

### ISSUE THREAD

**Issue by phoenixV3D** [Wynncraft/Issues#4553]
The resource pack doesn't work. Each time I log in, it always tell me "making request: 100%", but it never downloads the resource pack. I don't receive any error message, apart from the one telling me that I don't have the resource pack on in the chat. I've tried to follow the advice of deleting the packs in my "server-resource-pack" file, but I don't have any pack whose name indicates that it is the Wynncraft pack. I've tried deleting them all, just in case, but it still doesn't work. 
Could someone help me fix this please?

**Comment by Odnod** [comment]
The wynncraft resource pack should be titled 'legacyzip' in your server-resource-pack folder. Also, may I recommend something?

Try putting a '.' between legacy and zip, then move the resulting folder into your resource packs.

**Comment by Moe-Ronickah** [comment]
@phoenixV3D , did you try Odnod's advice?  Is the problem fixed?

**Comment by PenguinInSnow** [comment]
Usualy what you need to do to fix the problem is to go on the server list, click on wynncraft server and then click the Edit button, next, click the *Server Ressource Packs* button and make sure it says Enabled. When its done, log back in the server and it should be working, Hope it helped :p

**Comment by Verret001** [comment]
Closed due to inactivity over ten days
