### ISSUE TITLE
Spawning Glitch

### ISSUE THREAD

**Issue by Cdog4ever** [Wynncraft/Issues#4554]
# Delete this line if you've searched for a duplicate issue first
I have a problem where I when i spawn in i am stuck in an unknown location in a black box, where i am unable to do anything. Is it possible that an admin could just tp me to the town i was in. This has happened before and had caused me to reset my character, but i don't want to reset it again as it was annoying level up again.
![2016-03-14_20 15 15](https://cloud.githubusercontent.com/assets/17836457/13758704/9cfe9bca-ea22-11e5-99fa-9e73c6a7320f.png) i have included an image of what i can see is there anyone who can help. My in game name is Cdog4ever if anyone can help

**Comment by TrashcanMan** [comment]
Do /kill with at least 3 soul points. If this resolves your issue, please close it. Thanks!
