### ISSUE TITLE
Broken Wynncraft API

### ISSUE THREAD

**Issue by DRedDogPE** [Wynncraft/Issues#4556]
Please could you fix the Guild Stats API and the Server Stats API. I really want to use these on a website I am creating and if I had these API's it would be so much better. Alot of people might not use the API or know what it is but I think I could make something very good with it. I have already started working with the other APIs and have created some pretty cool stuff. I hope this gets fixed.

**Comment by brainscript** [comment]
+1

**Comment by Moe-Ronickah** [comment]
The server stats and the guild stats have been messed up for a very long time.  They are not of major importance, compared to many other bugs, hence, the admins have said "When we get time to fix them."  No, I don't know when they will be fixed, all we can do is wait and be patient.

**Comment by DRedDogPE** [comment]
I have offered to code the api myself as I am very good with php, I have had no reply yet though.

**Comment by Trixter313** [comment]
Is this still an issue? https://forums.wynncraft.com/threads/wynncraft-public-api.127085/
