### ISSUE TITLE
Spawning glitch

### ISSUE THREAD

**Issue by xXCrescentRoseXx** [Wynncraft/Issues#4557]
When i click on a server on either of my accounts, xXCrescentRoseXx or Nosnevetsekim, I tp to the wynncraft world, fall through the ground, and get stuck in the void. I cant use any commands except /hub, and it doesnt ask me to pick my class. Or download the resource pack, which i haven't done yet.  ![screenshot 4](https://cloud.githubusercontent.com/assets/17839429/13764376/028ae352-ea25-11e5-802c-f0c4e8c03fc4.png)     Btw the link it gives me doesnt work, says page is unavailable when i try to load it.

**Comment by Odnod** [comment]
This bug has sometimes been fixed in the past by uninstalling and reinstalling mc. No promises, but this may work for you.

**Comment by Trixter313** [comment]
Also try going to Multiplayer > Wynncraft > Edit and enable resource packs from there if it isn't promoting you ingame.

**Comment by xXCrescentRoseXx** [comment]
Thankyou very much, it worked :)

**Comment by Trixter313** [comment]
Glad to hear =)

**Comment by sabercobra** [comment]
i have the same problem too

**Comment by sabercobra** [comment]
ii chose a class and i have the resourcepack installed but it just pt me in a pitch black box

**Comment by sabercobra** [comment]
i tried all the tips you gave but it still doens't work

**Comment by Trixter313** [comment]
@sabercobra try typing /kill

If that doesn't work, please create a new thread. Thanks!
