### ISSUE TITLE
Guild Leave Bug

### ISSUE THREAD

**Issue by Camillerir1** [Wynncraft/Issues#4561]
![bug](https://cloud.githubusercontent.com/assets/17856486/13786393/a4580aae-ead7-11e5-8aee-bb2791c26ce2.PNG)
Why ken`t I leave the guild Pls fix it as fast as you ken

**Comment by Tom886** [comment]
Did you change your name when you were in the guild? People who do this show up twice in guild tab, and cannot be kicked or leave.

**Comment by Ziggeh2** [comment]
@Tom886 s there any way to fix this? I have the same problem.

**Comment by Dar-krusos** [comment]
Try getting someone to kick you. If you've waited some time after, and this doesn't work, there's really nothing you can do :/

**Comment by Trixter313** [comment]
I see that you've changed you name before, making this a duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!
