### ISSUE TITLE
Horse bug

### ISSUE THREAD

**Issue by Ikheetkalle** [Wynncraft/Issues#4562]
A few days ago I gained a lot of loot: Even a horse! So I was happy.
But sometimes my horse seems to be moving forward but isn't! Making me die! This happend so many times that I have lost all my stuff by the soul system! 

So what I ask o mighty operators is to fix this bug and PLEASE I beg you give me my stuf back that I have lost by this bug

**Comment by Trixter313** [comment]
What version of MC are you using? Thanks!

**Comment by Ikheetkalle** [comment]
1.9

**Comment by Ikheetkalle** [comment]
O by the way I only want back my horse: the armor staff etc isnt needed

**Comment by Odnod** [comment]
This is probably just a 1.9 thing. Wynncraft is still really shaky in 1.9 and I highly reccomend that you just use 1.8.9

**Comment by Trixter313** [comment]
As stated in the 1.9 update post, horses are currently buggy for 1.9 clients and are being worked on. It should be fixed soon. =)

https://forums.wynncraft.com/threads/wynncraft-1-9.115900/
