### ISSUE TITLE
Teleport because of Crash :(

### ISSUE THREAD

**Issue by Thooler33** [Wynncraft/Issues#4565]
Hi guys ! 

Can you explain me why when I disconnect in the volcano for the WynnExcavation Site C Quest, i reconnected in the city of... Almuj

I'm desperate because I must re-teleport to Llevigar, then go to the volcano island with a boat... 

Is this happening often ? Seriously... now, I don't want to continue the quest

**Comment by Odnod** [comment]
I think the problem might be that you died when the server was frozen, causing you to respawn in what is the closest city to wherever the tunnels are in the quest. In this case, that city would be Almuj.

**Comment by Trixter313** [comment]
How many times has this issue happened to you?

**Comment by Thooler33** [comment]
Around already 10-15 times :(

**Comment by Thooler33** [comment]
@Odnod At least i could've been teleported to Selchar, but no... to Almuj. x)

**Comment by Moe-Ronickah** [comment]
The builders are aware of this, however, unfortunately, there is no fix for this, yet.
