### ISSUE TITLE
The Shadow of the Beast Bug

### ISSUE THREAD

**Issue by Edywang** [Wynncraft/Issues#4568]
Upon attempting to turn in The Shadow of the Beast Bug (Happened to occur during a DXP which is when I turn in all my quests), a dialogue began with Dereg essentially saying to bring back the three pieces of evidence.. I've taken screenshots of 3 items that were in my inventory at the time (the three pieces of evidence) and the quest text which reads that 3 are required.

Quest Text: https://gyazo.com/1702f9cfcb6bf4014d7ef3b01a96dc44

Items in my inventory:
https://gyazo.com/3a7ebbf2570d9a08e2e365b7efa30920
https://gyazo.com/131bfd510d74c2f9a751fc98ae7a4dc1
https://gyazo.com/788bb7bc98504ba87834410b1cb356fc

I also noticed that the Piece of Bigfoot Bone was an untradeable item rather than a quest item, is that a mistake or is it because one can kill Bigfoot more than once and accidentally stack them up taking up inventory space.

**Comment by Trixter313** [comment]
I'd suggest throwing out the current and trying to get more Bigfoot bone. Also try /fixquests although it probably won't do much in this situation.

**Comment by Edywang** [comment]
I had to relog and try it again but I'm still saying that it's a bug that should be fixed.

**Comment by AckroWynn** [comment]
I completed the quest today, and it worked just fine.
As for the Bone, yes, it is supposed to be untradable.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
