### ISSUE TITLE
LOST ALL SKILL POINTS

### ISSUE THREAD

**Issue by PikaPlayzzz** [Wynncraft/Issues#4569]
i am almost level 32 and i got on today to not being able to use my ONE ANS ONLY *good*  WEAPON.
I know this happend to other people as well so please get this fixed fast! ;-;

dont beleive me? well here...
http://imgur.com/gallery/QnHOxfs/new

p.s. i do have 2 because i havnt usesd them. i lost all the others.

**Comment by PikaPlayzzz** [comment]
NEVERMIND I LOGED BACK IN AND ITS BACK SORRY FOR THE INCONVENIANCE LUV YOU

**Comment by PikaPlayzzz** [comment]
IDK HOW TI DELETE IT SO IMA JUST LEAVE IT OK BYE

**Comment by Trixter313** [comment]
Glad to hear it's resolved now =)
