### ISSUE TITLE
Nesaak's Shadow

### ISSUE THREAD

**Issue by McSeed** [Wynncraft/Issues#4571]
The Nesaak's Shadow armor have a bug.
It have to gain +50 in water defense and -30 in thunder, but wen i equip it I have only +20 in water and -30 in thunder, air and earth defense.
How it is possible?

The other pieces of armor have no debuff defense.

**Comment by CookedPelvis** [comment]
Have you made sure that all armor and weapons you are using does not have an identification of subtracting a **percentage** of defense?

**Comment by McSeed** [comment]
Yes i do.
I don't know how but until today it still work like i describe that.
Now i have new item and all of my stats are normal.
