### ISSUE TITLE
I cant Leave The Guild im in

### ISSUE THREAD

**Issue by AlphaScottMcCalll** [Wynncraft/Issues#4574]
I want to leave my guild but i cant for some reason when i try to leave the guild  im still in the guild 
and i want to join another guild

**Comment by Odnod** [comment]
Currently, if you change you username while in a guild it causes you to become stuck indefinitely in the guild.

**Comment by AlphaScottMcCalll** [comment]
is there a way to leave the guild tho iff u change your name back to what it was before

**Comment by Odnod** [comment]
Sorry for no response, but I am afraid there is no way to leave your guild if you are affected by this bug.

**Comment by Moe-Ronickah** [comment]
Until there is a major overhaul of guilds, there is no fix for this.
