### ISSUE TITLE
Precision, Etikal type bows not showing

### ISSUE THREAD

**Issue by RoundPikachu** [Wynncraft/Issues#4577]
My Precision bow isn't showing. It appears as a wooden slab and my other bow, Etikal, also doesn't show. They are both the same bow with different stats (they look like elemental bows that have the moving colour things) please fix this bug when you can because I know there are much more important bugs than this. Thanks.
![2016-03-17_16 12 55](https://cloud.githubusercontent.com/assets/17113839/13853381/5591f7a8-ec5e-11e5-8fbd-ee92a9efda9a.png)

**Comment by TrashcanMan** [comment]
Are you in 1.9? Wynncraft 1.9 is really sketchy right now, I'd suggest you use 1.8 for the time being.

**Comment by RoundPikachu** [comment]
I am in 1.9, thanks for the tips, will revert back to 1.8. Thanks!

Date: Thu, 17 Mar 2016 14:42:02 -0700
