### ISSUE TITLE
WUT THE FRIG

### ISSUE THREAD

**Issue by Dumbfk** [Wynncraft/Issues#4578]
# Delete this line if you've searched for a duplicate issue first
Oi... Look mate... I'm trying to spend my nice time as a mage, running spider dungeons and crap. UNTIL GOD KNOWS FK ALL... I teleport into the ground and find a bunch of fucking redstone contraptions. Can I get out? In particular yes. But either by /kill (losing 2 soul points) or using a teleport scroll (losing 1 soul point). You may be saying "Oh no biggie, just use the teleport scroll if you're so worked up about losing soul points. WELL GUESS WUT... I don't just lose soul points.. I lose my fkin key... and that fckin key that I had to waste time to spend 20e on a skeleton key... then run the skeleton dungeon.. and run my arse back over to spider.. OH you think this happened to me once? No.. Last time I was minding my own business.. running from Detlas on the way to Ragni.. when all the sudden I TELEPORT... INTO A FUCKING TREE... Oh and can I teleport out? NO... CAUSE FUCK ALL TELEPORT RESTRICTIONS on BEING NEXT TO A FUCKING BLOCK.. (had to kill myself since I had no scrolls losing 2 soul points and my valuable fucking time.) Thank fuck you and Fuck this server until it is fixed.

**Comment by RockyPlayzMC** [comment]
Someone's mad lol, teleport restrictions are needed because people try to glitch into places where not need to be. For one Temple of Legends you must be that certain level. If this happens to you ever again just maybe ask someone (A higher level) hey are you able to give me 20 eb for the spider dungeon maybe you could help me to? Sorry that has happened to you, Cheers :D

**Comment by DarkDemonDragon** [comment]
Dude worse has happened. I've had this happen in the ZOMBIE dungeon and those keys cost 2 EB. @Trixter313 please close this as this.

**Comment by Trixter313** [comment]
All we can suggest is try not to teleport into walls and don't spam the teleport button. Hope this helps prevent this from happening again.
