### ISSUE TITLE
I lost all my skill points for no reason and i cant use most of my gear

### ISSUE THREAD

**Issue by TheMajicGamer** [Wynncraft/Issues#4581]
So i was going on wynncraft and then my armor was tooken off and i was at 10 health. so i came to the forums and wanted to ask you if i could have my skill points back because i had 21 on everything except defense and agility were 20 I just want to play on that account not start over

**Comment by TheMajicGamer** [comment]
my skill points were put all to 0

**Comment by TheMajicGamer** [comment]
![2016-03-18_07 13 59](https://cloud.githubusercontent.com/assets/17929325/13880328/02daee9a-ecd9-11e5-94fc-770df783d72a.png)

**Comment by TheMajicGamer** [comment]
![2016-03-18_07 13 42](https://cloud.githubusercontent.com/assets/17929325/13880333/0a7e5434-ecd9-11e5-98b8-5e7f429b423e.png)

**Comment by TheMajicGamer** [comment]
![2016-03-18_07 13 44](https://cloud.githubusercontent.com/assets/17929325/13880341/158cc626-ecd9-11e5-8acc-d62d8a0883f0.png)

**Comment by TheMajicGamer** [comment]
![2016-03-18_07 13 35](https://cloud.githubusercontent.com/assets/17929325/13880361/1f3d61bc-ecd9-11e5-9fc6-4774d9da5b54.png)

**Comment by TheMajicGamer** [comment]
![2016-03-18_07 13 34](https://cloud.githubusercontent.com/assets/17929325/13880369/282dc956-ecd9-11e5-8a5a-48dc55047dce.png)

**Comment by Tom886** [comment]
Whenever this happens, make sure all the items you have are in you inventory. Then type /class, and that should fix you skill points. Logging off with your items on the ground will result you you losing them, so be careful!

**Comment by TheMajicGamer** [comment]
thank you for your help
I do appreciate it
