### ISSUE TITLE
Can not log on

### ISSUE THREAD

**Issue by Flaimsy775** [Wynncraft/Issues#4582]
I tried loging on to play.wynncraft.com and it worked then I tried the next day and it said unknown host
And I have been trying to log on but it still wont let me

**Comment by Odnod** [comment]
try changing it to "play.wynncraft.net" or "play.wynncraft.org" instead.

**Comment by Flaimsy775** [comment]
I tyred the play.wynncraft.net didn't work ill try the other on rn

**Comment by Flaimsy775** [comment]
well I just played that for like 1 hours then my game crashed and now It wont let me log on again...

**Comment by Flaimsy775** [comment]
I have tried play.wynncraft.net play.wynncraft.com play.wynncraft.org us.wynncraft.org us.wynncraft.com 
So I don't know what to do now
