### ISSUE TITLE
Spawning in Nesaak

### ISSUE THREAD

**Issue by MrBam9021** [Wynncraft/Issues#4583]
# Delete this line if you've searched for a duplicate issue first
 this started the other day when i logged on and some how fell through the world and died, i spawned in Nesaak and since then every time i die i spawn back in Nesaak and cant leave cause every time i try to i die

**Comment by TrashcanMan** [comment]
Well you respawn in the nearest city so if you don't get far away enough from Nesaak you'll respawn there upon death... Also what do you mean you can't leave?

**Comment by MrBam9021** [comment]
the thing is i was in Deltas when i fell through the world  and it stared that

**Comment by DarkDemonDragon** [comment]
Do you have a 2nd class at Detlas? If yes, follow these instructions:
Lets say Class A is the one in Nesaak and Class B is the one that is at Detlas.

Make sure Class A can access the bank.
Switch to Class B and buy a Detlas Teleportation Scroll.
Bring the Scroll to the bank.
Switch to Class A and take the Scroll out of the bank.
Use the scroll and Class A will be back in Detlas where it is safer.

Make sure you have enough SP before teleporting!
