### ISSUE TITLE
Armour not drawing itself

### ISSUE THREAD

**Issue by dans1479** [Wynncraft/Issues#4584]
When I put on armour it doesn't draw the armour texture and returns my player skin to the normal one that I have for any server I play. It didn't use to be like this but after coming back to this game after 3 months this problem has started. If anyone knows why this is happening and can tell me what I can do to fix it I would be very grateful. 

Thx!!

**Comment by Creecreeprs** [comment]
You can't do nothing to fix that, this bug is here for some times (I don't know why) and he will be fix in some times. Just wait.

**Comment by Trixter313** [comment]
Armor skins are currently being worked on and are disabled.
