### ISSUE TITLE
teleportation glitch

### ISSUE THREAD

**Issue by SuperSaiyanGrunt** [Wynncraft/Issues#4586]
I was doing the quest "green skinned trouble" and I just defeated the boss and earned his axe. I then entered the teleporter to go to the detective, but I got stuck in a black screen and I can't do anything. I've  tried using teleportation scrolls to Llevigar and Selchar but both do nothing when prompted. Somehow in the midst of this, I also lost my bow and the two bows in my inventory are too high level for me to use. Please help!
![2016-03-18_19 30 29](https://cloud.githubusercontent.com/assets/17937709/13894587/fee53fa4-ed3f-11e5-9cde-5b76787e3c9a.png)
![2016-03-18_19 35 50](https://cloud.githubusercontent.com/assets/17937709/13894641/cf246208-ed40-11e5-9704-b16bfa85b70c.png)
![2016-03-18_19 36 01](https://cloud.githubusercontent.com/assets/17937709/13894631/bae35c5e-ed40-11e5-83dd-615af8d4870c.png)

**Comment by TrashcanMan** [comment]
Do /kill with at least 3 soul points.

**Comment by SuperSaiyanGrunt** [comment]
thanks!
