### ISSUE TITLE
Funny quests book typing mistake

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#4587]
I was doing the quest "Underice" when I noticed that it says "in the squid villageR", not "in the squid village". Seems kinda wierd that that happened twice though.
Here's a screenshot: http://imgur.com/a/cdCPv

I really found this funny xD

Thanks.

- Nothing

**Comment by AckroWynn** [comment]
Fixed it. Thanks.

**Comment by Trixter313** [comment]
=)
