### ISSUE TITLE
Animal Dungeon Glitch

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#4589]
I was playing animal dungeon and... Just watch the video.
https://youtu.be/RjtvPXIMTcE
Since I kinda wasted an Animal Key and had to do /kill to get out again I was hoping that I could get it back.

Thanks

- Nothing

**Comment by Trixter313** [comment]
This is a vanilla Minecraft issue that sometimes causes players to glitch through blocks when dismounting a horse. I don't believe there is anything Wynncraft can do about it without breaking the redstone.
