### ISSUE TITLE
Depressing Weapons

### ISSUE THREAD

**Issue by ChoccyBiccy3** [Wynncraft/Issues#4593]
This isn't much of a bug but I have been roaming around the emerald trail, constantly killing low level zombies looking for Depressing Items, these are for the Bob Quest. I have been doing this for nearly 3 hours and have only gathered 1 Depressing Shears, I think it's slightly annyoing how long it's taking to do this. I have also seen other people with the same problem, is there any way you could increase the drops of Depressing things or maybe create a depressing merchant or something like that. Thankyou for reading.

**Comment by Trixter313** [comment]
This has been brought up before, please refer to https://github.com/Wynncraft/Issues/issues/4106 for answers to your concerns.
