### ISSUE TITLE
I lost my whole inventory!

### ISSUE THREAD

**Issue by MCChakram** [Wynncraft/Issues#4597]
Hi, my IGN is Chakram and my main character is (or was) a level 35 archer. I closed Minecraft and then shut down my computer. I left for 6 hours or so , and when i came back , my whole inventory was gone, including armour! Strangely, i kept my Cluckles' Favourite Feather , 5 oak wood bows (Which weren't in my possesion before) and only 8 emeralds. What could i do to get my inventory back?

EDIT: I also had 6 soul points when logging out, so that rules out the possibility of *somehow* dying and losing my inventory. What boggles my mind is how did i get those bows i did not have?

![screenshot_19](https://cloud.githubusercontent.com/assets/17953821/13900938/423db69c-ee1b-11e5-8c22-4f3926f4f4e8.png)

**Comment by Trixter313** [comment]
It sounds like someone was logged on as you and died enough times to drop your inventory a few times. It could have been someone on the computer you use or someone who has your login credentials. To prevent this from happening again, I'd suggest changing your Minecraft and the associated emails passwords.

When you die you get oak unsellable items so it appears that the person who killed your player continually picked up the bows every time, and some emeralds. The soul points could have been from the person staying logged in a bit or regenerated from being offline.

**Comment by MCChakram** [comment]
Then what about the feather?

**Comment by Trixter313** [comment]
Quest items are also kept in the inventory on death so that's why the feather was left.

It could have been a lucky guess or the hacker could play Wynncraft themselves and checked if you did also.

Or it could be that they were specifically targeting Wynncraft players and saw you online or on the forums. Something similar to this did happen to one other person recently.

**Comment by MCChakram** [comment]
Woah.. Ok then.
