### ISSUE TITLE
Black Horse Randomly disappeared out of my inv after server restart

### ISSUE THREAD

**Issue by PhoenixRemast** [Wynncraft/Issues#4598]
# Delete this line if you've searched for a duplicate issue first
The server restarted while i was around the ragni area
It then just disappeared out of my inv
I dont have any proof of having it unfortunatly but DarkGapple and Nicol3 both saw me with it so yea

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refunds policy so there's nothing we can do shot the lost horse.

What most likely happened is that you accidentally dropped it so to prevent this from happening again, I'd suggest changing your drop key to something you're less likely to press.

**Comment by PhoenixRemast** [comment]
I've disabled dropping btw
And i've been refunded items in the past?

**Comment by Trixter313** [comment]
The policies at that time might have been different but there is currently a no refunds policy for items. Sometimes quest items will be replaced if they don't have any ingame value but other than that it rarely happens.
