### ISSUE TITLE
Potions Bug

### ISSUE THREAD

**Issue by TheAllStar** [Wynncraft/Issues#4599]
Potions of Healing look like Potions of Mana (it's blue instead of pink).

**Comment by Trixter313** [comment]
Could you post a screenshot showing this? Thanks!

**Comment by TheAllStar** [comment]
![2016-03-20_11 30 27](https://cloud.githubusercontent.com/assets/17955288/13906364/d316df24-ee91-11e5-87c4-383032336613.png)

**Comment by DarkDemonDragon** [comment]
Where you get this? Did you buy it, get it from a mob drop, or randomly pick it up? Also, do you have more than 1?

**Comment by Trixter313** [comment]
Appears to be a duplicate of the 2nd part of https://github.com/Wynncraft/Issues/issues/4548

Please direct any future comments to the original thread. Thanks!
