### ISSUE TITLE
Lost some of armour

### ISSUE THREAD

**Issue by ElitePlayer** [Wynncraft/Issues#4601]
I logged on to my warrior today and my helmet, chestplate, leggings,one ring, and bracelet were missing. I searched my enderchest and all my classes. I only had boots and one ring and one necklace. My skill points were still normal.

**Comment by Trixter313** [comment]
When did you check your skill points? The skill points issue is fixed by switching classes and I see that you checked your other classes. It might have been caused by your skill points being reset but then you switched classes which fixed your skills.

**Comment by Trixter313** [comment]
Closing due to no response. Just comment back if it's still happening and I'll reopen. Thanks!

**Comment by ElitePlayer** [comment]
OK

**Comment by Trixter313** [comment]
So are you still experiencing the issue? If so, I believe this to be a duplicate of https://github.com/Wynncraft/Issues/issues/4120 even though when you checked your skill points they were fine, as explained in my first comment.

Please direct any future comments to the original thread. Thanks!

**Comment by ElitePlayer** [comment]
OK
