### ISSUE TITLE
Ancient Scout Shoes automatically ID'd in loot chest

### ISSUE THREAD

**Issue by TheDollarBill** [Wynncraft/Issues#4602]
I opened a loot chest and happened to find a pair of boots that were already "partially" ID'd.. (with name and stat requirements but no actual identifications). I did not put the boots into the chest myself; it was like that when I initially opened it.

The loot chest: http://i.imgur.com/We3G1Dn.png
This is what happens when I try to ID them: https://i.imgur.com/ZVEHAAi.png

**Comment by Moe-Ronickah** [comment]
Are you sure that you didn't fall asleep and somehow put them in there?  If so, then how do you manage to find these issues?

**Comment by TheDollarBill** [comment]
Yeah, I didn't put them in for sure. I've found these shoes like 5 times now.

Found this when I was looting on a level 8 class

**Comment by TheDollarBill** [comment]
Another one: http://i.imgur.com/73uiMTN.png

**Comment by ThunderRemix** [comment]
@Moe-Ronickah The reason why this happens is because the item doesn't have any IDs.I looked it up in the item guide/api/db. So close this issue?

**Comment by Moe-Ronickah** [comment]
Thunder, thank you for checking this in the api.  It appears that these shoes are supposed to be exactly as they seem; identified, as found, with no other identifications possible.
See https://api.wynncraft.com/public_api.php?action=itemDB&search=ancient%20scout%20shoes

**Comment by YunoFGasai** [comment]
this brings to mind the pre gavel bow that came pre enchanted (forgot its name)
we might wanna make sure with a team member this is intentional

**Comment by Moe-Ronickah** [comment]
See the results for https://api.wynncraft.com/public_api.php?action=itemDB&search=ancient.  There are six items, all ancient.  The ones that are armor all have all fixed identifications while the two weapons have a range of identifications for some ids, and not for others.  That seems pretty intentional to me.
