### ISSUE TITLE
Weird Black room when I spawn in

### ISSUE THREAD

**Issue by NickHuff** [Wynncraft/Issues#4603]
So I recently loaded up my Assassin class on WynnCraft and when i loaded in I was in this black room and could not do anything in. Here is the other thing that is weird, when i load up my other classes i am back where i left off at. I dont want to delete my current assassin to make a new one because of his level. I just hope I can get help on this because I recently donated and got bored of playing on my archer so i switched to my assassin and now i cant get any items off of my assassin to put back on my archer.

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out.

If that doesn't work, please comment below. Thanks!
