### ISSUE TITLE
[Small Quest Dialogue Issue] Wynn Excavation Site D NPC 

### ISSUE THREAD

**Issue by CookedPelvis** [Wynncraft/Issues#4604]
While helping two friends do WynnExcavation Site D, I came across 3 NPCs in a cavern where you start the puzzles stage of the quest (leading to the fight with Amadel's 3 different forms). I noticed when you clicked on him, he said the dialogue for after you've finished the quest, but the numbers before his name said he was on the **4th line of dialogue out of his total of 4** , but shouldn't it say "[1/1]"?

Picture:
http://imgur.com/lJaS8mi

**Comment by Moe-Ronickah** [comment]
I'll take a guess, you've done the quest, already, and that's your screenshot, right?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
