### ISSUE TITLE
Loss of VIP+ rank

### ISSUE THREAD

**Issue by awesomeguy3350** [Wynncraft/Issues#4606]
Ok i did not really know where to post this but bugs seemed to be the closest one to post it on.
i had VIP+ and basically i had not played WynnCraft in a while and i came on to see the new updates. as i came on i wanted to start fresh and thought id use one of the VIP+ kits as i had used hunter before the massive update but not used it that much. when i looked at the /class list it said i needed VIP+ when i already have definitely bought it. i had bought it back when they had just released the Assasin kit and i had wanted VIP+ so i could get in that VIP+ area (witch they had taken down not to long after i got VIP+).
so really i would just like someone to see if they could get my VIP+ back as i had payed for it and its really annoying that its been taken away from me.
Thanks
btw my ingame name is     awesomeguy3350

if theres a way to track the payment i made then that could work or i could get my dad to check his credit card history for the payment made

**Comment by awesomeguy3350** [comment]
i dont have any screen shots of me with it but if theres a way to see the payment then that could work or i could get my dad to look through his credit card history to find the payment

**Comment by Trixter313** [comment]
Hmm, I think you are confusing VIP and VIP+.

When there was the VIP town that only donors could go into, only VIP existed. VIP+ wasn't in the game yet.

If you look [here](https://api.wynncraft.com/public_api.php?action=playerStats&command=awesomeguy3350) you'll see that near the beginning it says, "'rank':'VIP'" so it appears that you **are** VIP but just not VIP+. 

If you'd like to upgrade to VIP+ from VIP, you can do so [here](http://store.wynncraft.com/checkout/packages/add/945490/single) for $25.

Hopefully this clears up some confusion. If you have any more questions, simply comment below and I'll try my best to answer them.

Enjoy the rest of your day!

**Comment by awesomeguy3350** [comment]
ok srry for the mixup
