### ISSUE TITLE
Thorns armor

### ISSUE THREAD

**Issue by Creecreeprs** [Wynncraft/Issues#4607]
A friends talk to me about thorns items.
He sends me the screenshots and he saids that he never identify them.
Just see : 
https://i.imgur.com/WWA4uwI.png
https://i.imgur.com/41FNr0s.png
Now, he identify them and the enchant disapair.

**Comment by Trixter313** [comment]
Well powders are currently being reworked so the fact that the enchant was removed when identified was probably intended. Wait until powders are done, it should work correctly then. =)
