### ISSUE TITLE
Quest book has reset itself. 

### ISSUE THREAD

**Issue by Steropes** [Wynncraft/Issues#4611]
Hello. I recently started playing again after about  a year and a half. I noticed that my entire quest has reset itself. I just got done doing r"rise of qaurton" quest and then my next quest to do was thieving rodents all the way back in ragni. Is there any way my quests can be restored?

**Comment by Trixter313** [comment]
So your saying you have 0 quests completed on your quest book? Could you post a screenshot of the first page of the quest book? Thanks!

**Comment by DarkDemonDragon** [comment]
I think he misunderstood. Thieving Rodents is a NEW quest. The quest book orders quest you haven't done by **Level Order**. If you have no active quests then the lowest leveled quest will be the first quest to pop up.
