### ISSUE TITLE
Possible Melee damage bonus bug 

### ISSUE THREAD

**Issue by KrabTheScrab** [Wynncraft/Issues#4620]
So pretty much it could be a bug or an intentional thing (no idea why you would make it like that on purpose but ok) 
so if i have +200 melee damage for example but i am using a weapon with only Elemental damage the melee damage wont give me 200 neutral damage with it and will render useless BUT when i have +200 melee damage on a weapon with neutral damage it will increase my damage , it says +Melee damage not +Neutral damage anyways
now the reason i dont understand why its like that is that Inferno (a mythic dagger) has 40 melee damage bonus and since it only has elemental damage its pretty much useless .
soooo ye , it would be nice if i could get a response if its a bug or if its on purpose :P

**Comment by TrashcanMan** [comment]
The +Melee damage should increase damage in all elements, it might just be bugged.

**Comment by KrabTheScrab** [comment]
hmm , thanks for the response , i hope a staff sees this

**Comment by DarkDemonDragon** [comment]
Most likely it is being applied. The problem with trying to measure a weapon's damage is the range. Most likely the 40 melee dmg gets divided evenly with all the elemental damage. Since Inferno has high damage it's hard to see if the damage is really being added. Inferno also gets +x% Melee damage and has skill requirements so it's impossible to really calculate if the damage is added. If you REALLY want to test it here's what to calculate:
410 + 410*(Percent in Defense)^2 + 410*(Percent of Melee Damage Bonus NOT raw Melee Damage Bonus)
This will give you the Max damage you will do per melee hit if you do not get Raw Melee Damage bonus. Then, find something with 1000+ HP and 0 Def to Fire. Smack it 100 times. If the damage ever goes higher than the calculated value then the Melee Damage bonus is applied.

**Comment by DarkDemonDragon** [comment]
Until proven to actually be a bug this should be closed for now since there's no proof to indicate otherwise @Trixter313

**Comment by KrabTheScrab** [comment]
it must be a bug , i can get a proof i will record it if needed
i used an archangel (small damage range) and  and 2 jester rings that give me 200 melee damage , the damage was the same
than i did the same with alzarin and my damage went up by a ton

**Comment by DarkDemonDragon** [comment]
Yea some proof will be necessary. I'll test around with Jesters if I have time.

**Comment by KrabTheScrab** [comment]
got a proof https://www.youtube.com/watch?v=rThuxZNtEUc

**Comment by DarkDemonDragon** [comment]
Sorry you didn't prove anything. 2 Jester rings do NOT give melee damage. You must have 2 DIFFERENT Jester items on at the same time.

**Comment by KrabTheScrab** [comment]
yes they do.... you can clearly see that they do when i scroll onto my stats
2 jester rings give +200 melee damage
you can also see my damage on alazarin went up by 200 ...

**Comment by DarkDemonDragon** [comment]
![image](https://cloud.githubusercontent.com/assets/15721340/14060566/21283d46-f33f-11e5-9214-d565bb887879.png)

**Comment by DarkDemonDragon** [comment]
Where does it say +200 in your stats?
![image](https://cloud.githubusercontent.com/assets/15721340/14060570/4e396a94-f33f-11e5-9b06-9b547d4f5da5.png)

**Comment by KrabTheScrab** [comment]
on my raw melee damage +208
i have 8 from my pants and 200 from the rings , the stats wont show on them because of a bug , if you dont believe me jester rings give melee damage research it on the forums
also you can clearly see the damage on the alazarin was increased ... if the rings didnt give melee damage than how is that possible?

**Comment by DarkDemonDragon** [comment]
Hmm first it's strange that the jesters even do that, and for all we know this may or may not be intentional. We'd need some confirmation from an admin.

**Comment by KrabTheScrab** [comment]
the jester thing is fine
pretty much the thing is , raw melee damage wont effect elemental weapons for some reason , is that a bug or intentional , if its on purpose than it makes no sense since it will render melee damage on inferno useless
so ye we just need a gm/admin to answer that

**Comment by Moe-Ronickah** [comment]
There are a couple of problems with your video that I would like for you to correct, before I can say anything else.
First, you show your stats page with the Jester rings, but never without them.
Second, if you want to show anyone something in your inventory, such as your Jester rings, when they are equipped, please hold over the items for 5 to 10 seconds.  Anything less, is too little time for the viewer to properly grasp.
If you would recreate your video, with the above changes, I would greatly appreciate it, as there is no evidence in your video that the Jester rings supply 208 raw melee damage.

**Comment by KrabTheScrab** [comment]
i happily would
but i no longer own the archangel :(
i asked my friend to test it with his archangel and no armor on , if you want i can make a video showing that jester rings do give 200 melee damage

**Comment by KrabTheScrab** [comment]
https://www.youtube.com/watch?v=5zV5AVoLIys&feature=youtu.be
hf

**Comment by KrabTheScrab** [comment]
i am gonna bump this

**Comment by Moe-Ronickah** [comment]
OK, Kraby, I see it, now.  I'll have to see if I can find out anything, or you can ask on the forums about it.  Put it in the questions, please, and see if melee damage is supposed to affect elemental-only weapons.  It doesn't make sense to me that it wouldn't, so it's probably a programming bug.

**Comment by Moe-Ronickah** [comment]
I got it confirmed, that it's not a bug. It's meant to be that way.  Whether or not it will change in the future, I have no idea, only that that is the way it is.
