### ISSUE TITLE
A question about Classes.

### ISSUE THREAD

**Issue by norepinephrine** [Wynncraft/Issues#4621]
Hi! So I was wondering if there was any way that I could get my mage stats traded with my dark wizard stats? I like dark wizard more and I want my 84 and my gear to be on that instead of my mage. Thanks!

**Comment by TrashcanMan** [comment]
Unfortunately this is not possible right now. You can transfer all the gear over via your bank but there is no way to transfer stats right now.

**Comment by Moe-Ronickah** [comment]
Not an issue.
