### ISSUE TITLE
Cant Fight CoW

### ISSUE THREAD

**Issue by Endeh** [Wynncraft/Issues#4622]
I am wearing the right helmet to enter and fight corrupter of worlds, however, it still will not let me enter.
EDIT: I fell down it and is now stuck at the bottom of the hole
https://gyazo.com/99a8432366fa5959fffd121585314c05
https://gyazo.com/58ad051c45cbe3176c53f4d1cc116a76

**Comment by TrashcanMan** [comment]
If you're stuck in a hole, do /kill with at least 3 soul points.

**Comment by Endeh** [comment]
I have, that;s not the problem, the problem is that I cant complete the quest, I have the helmet on.

**Comment by Trixter313** [comment]
Could you post a screenshot of what it says in your quest book? Thanks!

**Comment by Endeh** [comment]
https://gyazo.com/cd24a6ab636d48ebcea6296a131feb0e
