### ISSUE TITLE
All my skill points have disappeared!

### ISSUE THREAD

**Issue by 3519Mulberry** [Wynncraft/Issues#4623]
![2016-03-21_20 15 55](https://cloud.githubusercontent.com/assets/17995625/13939415/031bae18-efa3-11e5-98a5-8fd5fc021d7c.png)

**Comment by 3519Mulberry** [comment]
Omg im so mad :(

**Comment by TrashcanMan** [comment]
Have you tried relogging? Usually that fixes the issue.

**Comment by Moe-Ronickah** [comment]
You can either switch classes or relog into the game.
