### ISSUE TITLE
Bob the Zombie???

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#4629]
Bob the Zombie doesn't spawn in Ragni, I've walked around in Ragni for about 4-5 hours now, and in the last hour they stopped spawning. Yes, I know it's uncommon, but it's not like a legendary weapon.

**Comment by DarkDemonDragon** [comment]
It probably spawned in a really weird place. If you're having trouble obtaining the tear simply buy it from someone at Ragni, Detlas, or on the forums.

**Comment by BasicallyNothing** [comment]
I walked at every single spot of Ragni, and there was no "Bob". I got bored after an hour searching and logged off. There was noone else at Ragni at that point, so nobody could've killed it.

**Comment by Trixter313** [comment]
Only ~1 bob will spawn at once so it's most likely what Dark said, it spawned somewhere no one could find and no more spawned from there. It could have even been in a place not accessible to players such as a hollow spot in a building. It's rare but it happens and to fix it you can go to another world. The stuck Bob will disappear when the chunks are unloaded or the server restarts and all will be fine. =)
