### ISSUE TITLE
i lost my Le for no reason!!

### ISSUE THREAD

**Issue by HyperBeast01** [Wynncraft/Issues#4630]
i had my Le inside my inventory because i was gonna buy a item to do a quest, and when i tryed to buy the item it just dissepeard. help

**Comment by DRedDogPE** [comment]
Wynncraft has no refunds, sorry.

**Comment by Trixter313** [comment]
Like said above, unfortunately Wynncraft has a strict no refunds policy and because we don't really have that much information we can't determine the issue to try and help prevent it from happening again. It could have been a number of things but all we can do is hope it doesn't happen again.
