### ISSUE TITLE
Right click consistently double clicking.

### ISSUE THREAD

**Issue by Totsy30** [Wynncraft/Issues#4632]
Recently came back to the server and had no issues previously. Now almost any time I right click, it will double click. I've tried doing a single click as fast as I can, but still, it registers 2 clicks. There are no issues with Left click. This is extremely annoying and basically makes some of my abilities impossible to use, along with instantly despawning my horse when I try to spawn it.

**Comment by DRedDogPE** [comment]
Are you sure it isn't your mouse? I haven't experienced this, if anything my right clicks don't register quick enough.

**Comment by Odnod** [comment]
What version of Minecraft are you running?

**Comment by Trixter313** [comment]
I agree with DRedDogPE, we haven't gotten any other reports of this so I'd have to guess it has something to do with your setup specifically. Do you have any mods installed? If so, I'd suggest completely disabling any mods and mod loaders then trying again. If it still happens, try doing some tests with your mouse to see if it really is just your mouse or not. Report back with any new information that comes of this please. Thanks!

**Comment by Odnod** [comment]
@Trixter313 this issue has been seen a bit on the forums, caused by 1.9 in every case. I have also encountered people in game with this same bug and they were all using 1.9, so I assume that it is the cause.

**Comment by Trixter313** [comment]
Ah, then all we can really suggest is try downgrading to 1.8.9 and if it works use that until it's fixed for 1.9 =)

**Comment by Moe-Ronickah** [comment]
1.9 is a menace.  It messes with the right click, causing double-clicks, and, because "push player" is active, mobs can block you into a corner, but that is another issue/non-issue.

**Comment by Moe-Ronickah** [comment]
Minecraft was updated to 1.9.2, today.  Try it, and try going back to 1.8.9, then let us know if the issue is still going on, please.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
