### ISSUE TITLE
Dieing glitch

### ISSUE THREAD

**Issue by Avocadoz** [Wynncraft/Issues#4633]
Hi Wynn craft staff and members, I logged of the server wynncraft last night for a little while. I logged off the server in a safe spot and tonight I logged on and all of my stuff had been lost... all of my items had disappeared and I did find out I have full soul points. I believe that this is a glitch and I want to know want you can do?

Thanks,
Avocadoz

**Comment by Trixter313** [comment]
Hmm, these kind of situations are tricky. The most sensible answer that I can think of is that your account was hacked and someone else performed these actions to kill your player repeatedly. It could have been someone on your local computer or a computer you've used to sign into Minecraft to or they could have gotten your login information somehow and logged in as you. To be safe, I'd suggest you change the password to your Minecraft account and the associated email account in hopes that that prevents this from happening again.

Wynncraft has a very strict no refunds policy so unfortunately there's nothing we can do about the lost items. Hopefully this doesn't happen to you again!
