### ISSUE TITLE
Entering Olux

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#4635]
When you enter Olux nothing appears on screen even though it's supposed to. It happens to all the other cities on the map. If you could fix this it would be awesome. :o.

Thanks.

- Nothing

**Comment by Moe-Ronickah** [comment]
Fixed now?

**Comment by AckroWynn** [comment]
I took a look at the town yml we have, and everything should work just fine. Tell us if it keeps (not) happening.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
