### ISSUE TITLE
Quest book + map glith

### ISSUE THREAD

**Issue by bluemusic999** [Wynncraft/Issues#4638]
why hello there person that is reading this letter/email/forum/thread/letter from 2016 where we care about games instead of our life, i am here to report a glitch that involves the map and the quest book (btw i'm a bit tired when i wrote this so if i said it off or odd it might be because i'm really tired or because i'm a 14 year old staying awake all night because of sh!t sleep patterns) 

so the glitch is basically a small one where if i have done a step, the book/map does not update but the chat/dialogue does and you will be able to see it in chat, and this quest is Grave Digger, and i hope this can be fixed, but if it could not be fixed, please tell me and maybe even make a thread saying what bugs are trying to be fixed (also if my letter sounds like im mad, its just how i type if its not involving "lol" "haha" "XD" ) and yeh, and if you dont know how to fix it, maybe u can add a "restart quest" feature, where it starts u from the begining of the quest, and helps you retrace your steps/fix the glitch, plus this will help people join friends on quests with them not making new classes/profiles of being the same class

and i hope my letter has helped you in anyway, and if it has or just felt like it was vomit from my mouth please tell me so i can rephrase it 

( i am also on a map that might be the prob, or i have a few mods on : Foxlib/Tails, Zaero's Minimap, Forge, Optifine, few shaders packs )

( i have 2 imaged one for imgur and one from my mac, so if the from my mac one does not work u can just use the imgur one : http://imgur.com/DHNaW3u )
![2016-03-24_05 00 42](https://cloud.githubusercontent.com/assets/18036471/13995737/95daf434-f17e-11e5-927a-87aee64b7923.png)

**Comment by Moe-Ronickah** [comment]
Oh, nice.  A pic of this dang thing.

Reported in #4522 , but not the same issue as what happened in #4522 , ergo, not a duplicate.

As @Odnod said in that thread, "It is still 24 rotten flesh, pay no heed to the dialogue as it was probably something that was planned but not implemented."

**Comment by TrashcanMan** [comment]
@Moe-Ronickah I think it might actually be from a different (but also unimplemented) quest entirely, since the rotten flesh is to "purify the crypt" and here the NPC is talking about "brewing a cure".

**Comment by bluemusic999** [comment]
@Moe-Ronickah @TrashcanMan but i already gave the npc the 24 rotten flesh, and my book no update,

**Comment by bluemusic999** [comment]
and it just tells me that i still have to do it which is really annoying

**Comment by TrashcanMan** [comment]
Try entering the crypt, sometimes it doesn't update but you can still progress.

**Comment by bluemusic999** [comment]
i already tryed that ;-; i got a snapshot, and i can even share my screen
on skype showing it

**Comment by DarkDemonDragon** [comment]
@Moe-Ronickah why isn't this a duplicate? This is pretty much the exact same issue. 

@bluemusic999 what did the chat say when you gave him the rotten flesh? If you don't remember then check your log that day. If you have no clue what I'm talking about check the Logs section in my Evidence Thread:
https://forums.wynncraft.com/threads/evidence-ban-reports-bug-reports-etc.116166/

**Comment by Moe-Ronickah** [comment]
Well, there haven't been any other reports of this, and I've just ran 3 classes through it without any problems.  Whatever it was, it isn't any more.
