### ISSUE TITLE
Stuck in Bucie

### ISSUE THREAD

**Issue by edtheminecrafter** [Wynncraft/Issues#4641]
I was doing the Christmas Chaos quest and died. The weird part?
I re-spawned in Bucie which is on the other side of the world and about 20 levels higher than I should be.  When I arrived I was instantly killed by an Ogre, and was continually one shot killed till all my soul points were gone before I could log out.  There is no bank nearby and whenever I try to leave I just get insta-killed by much higher level mobs.

Listen, I'm not asking for my stuff back - I enjoy starting from scratch and I've looked up slightly similar issues, but please can someone get me out of this higher level town and back to Wynn Province?

-Edtheminecrafter

**Comment by AckroWynn** [comment]
I am surprised you spawned in Bucie. Have you ever been there with your class?

**Comment by edtheminecrafter** [comment]
I've been there with a different class (Hunter) - that's what makes it more confusing.  But it was also strange to respawn there since it was nowhere near any of the most recent towns I explored on either class.

**Comment by AckroWynn** [comment]
Yeah, that sure is strange. 
Although, when you die, you don't respawn at the most recent area. You respawn at the closest. Many things are off-map, making you respawn at weird places, that you have visited.

**Comment by DarkDemonDragon** [comment]
This should be impossible since you can't respawn somewhere you've never been to with the character. Anyway what Level and Class is the character that is currently stuck there?

**Comment by edtheminecrafter** [comment]
Well that's not comforting haha.
Current character stuck there is a level 32 Archer.  I have a level 30 Hunter elsewhere.

**Comment by DarkDemonDragon** [comment]
@edtheminecrafter try to head South West towards Llevigar by using Escape and jumping over enemies. If you find it impossible to reach Llevigar then I recommend going to the forums and asking for a player to help escort you to Llevigar.

**Comment by edtheminecrafter** [comment]
I did exactly that! Took quite a few tries but eventually made it safely. Thanks for the input!

**Comment by DarkDemonDragon** [comment]
Awesome! Glad to hear it :)
