### ISSUE TITLE
Health bar showing incorrect health

### ISSUE THREAD

**Issue by TrashcanMan** [Wynncraft/Issues#4643]
Sometimes when I log onto a server, the health bar shows only ten out of twenty hearts even though I am at full health. This usually resolves itself after a few seconds, but I'd like to put it out there all the same.
![2016-03-04_21 29 29](https://cloud.githubusercontent.com/assets/6947594/14027729/52c74dcc-f1b6-11e5-92e0-ab617e47e032.png)

**Comment by Creecreeprs** [comment]
That hapened to me too, and this is  frequently

**Comment by DarkDemonDragon** [comment]
It's a simple visual glitch. It's pretty small and you actually do have the health so it's probably not going to get addressed unless there's a simple fix.

**Comment by TrashcanMan** [comment]
@DarkDemonDragon Yeah it's not too big of a glitch, but I'm just leaving this for the devs to see in case they do want to fix it.

**Comment by DCM627** [comment]
It happens to me every time I log on and it goes away once I get hit by a mob. Whether I'd get hit just to rid this annoying glitch is up to you. I haven't tried drinking a health potion, but that may actually help, as it would probably cause the server to reload and/or update the health bar.

**Comment by Moe-Ronickah** [comment]
I have to switch what I'm holding onto, in the hotbar, for the hearts to populate properly.

**Comment by DCM627** [comment]
For me it's when I get hit by a mob, as it reloads the hearts. Maybe Moe's bow has a + # health identification?... I don't know. And I think it occurs because the health bar is loaded before the armor stat health thingey is. I never tried switching weapons because I usually never log out in a town. Whoops. Maybe drinking a health potion would help too? Just an idea.

**Comment by Moe-Ronickah** [comment]
It doesn't matter what class I am playing, I get the same issue.  As long as I switch the item in my hand, just by rolling my mouse wheel, the rest of the hearts populate.  It happens on login, on class changes, and on tping.
