### ISSUE TITLE
Cant join any worlds

### ISSUE THREAD

**Issue by davidthewimp** [Wynncraft/Issues#4644]
i have wanted to play wynncraft but when i join i fall into void and stay there i dont know why but my other account RedBomb20 which i lost was fine but now it is ruined also RedBomb20 was a rank and i am the person himself right now my ign is DavidtheWimp i had the first rank so please give me the rank and fix the bug Thanks for reading

**Comment by Creecreeprs** [comment]
I don't know for the bug but for the ranks, you have no proof that "RedBomb20" was your account. Wynncraft can't just give you the VIP without any proof.

**Comment by davidthewimp** [comment]
i can proof with my ip but im not giving it away

**Comment by Trixter313** [comment]
Do you fall in the void when you first login or after selecting a world from the lobby? Also, check your F3 menu to see whether you're falling or not. You might just be in a dark wool box and not the void. Make sure server resource packs are enabled in Multiplayer > Wynncraft > Edit. If you have your items while stuck, try typing /kill and see if that helps.

Let me know if any of this fixes the issue. Thanks!

**Comment by Odnod** [comment]
Also, in the past the void glitch has been fixed only by uninstalling and reinstalling minecraft. So that may solve your problem.
