### ISSUE TITLE
Healing Potion displays wrong in chat.

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#4646]
When you use the Potion of Healing that gives you +560 HP it says "+559HP" in chat.

Thanks.

- Nothing.

**Comment by LazerSnipe** [comment]
Probably have Full Health???\
Example:1/560 Used health potion and healed 559 health

**Comment by DarkDemonDragon** [comment]
@BasicallyNothing mind giving some screenshots to confirm if @LazerSnipe 's explanation is correct?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
