### ISSUE TITLE
No neutral damage from spells

### ISSUE THREAD

**Issue by sicklylemon** [Wynncraft/Issues#4651]
After the 14.0.10 patch spell damage was nerfed by quite a lot, it was needed but now you deal 0 neutral damage from spells even with a neutral damage wand. The only way to deal neutral damage now is to use +spell damage items or melee. This may have been intentional but I doubt it.

**Comment by dltkdwns** [comment]
I have exactly same problem

**Comment by TrashcanMan** [comment]
Pretty sure this is the same issue as #4126

**Comment by DarkDemonDragon** [comment]
@TrashcanMan hard to tell since they changed how spell damage is calculated.

**Comment by Moe-Ronickah** [comment]
We now know that this is an intentional game mechanic.  Whether or not it will be changed in the future, we don't know.
