### ISSUE TITLE
Fell Off Ahmsord With 4 Soul Points

### ISSUE THREAD

**Issue by YummyDuck** [Wynncraft/Issues#4652]
So, as a knight, i was using my Leap spell and fell off Ahmsord with 4 soul points. I wasn't worried because i knew i would have 2 left and not lose my stuff. So then, after i died, i somehow died another time, and lost all my stuff. The stuff isnt on the floor, and i couldnt be in the void.

![2016-03-24_18 35 08](https://cloud.githubusercontent.com/assets/18080013/14057700/66b83424-f2d6-11e5-946a-b5d87fe30b0e.png)

![2016-03-25_20 55 37](https://cloud.githubusercontent.com/assets/18080013/14057706/77eaf664-f2d6-11e5-8e4b-6e8b35342269.png)

![2016-03-25_22 11 52](https://cloud.githubusercontent.com/assets/18080013/14057713/a1e7799c-f2d6-11e5-92b5-5708c347cb7d.png)

Also, it seems that untradable items and accessories don't get dropped on death either.

Would it be possible if i could have my items back? I worked really hard for them. I had a white horse(maxed), and a chestnut horse(lvl13 or so), and I had bought some items and armor on there which costed me alot of money.

**Comment by TrashcanMan** [comment]
Unfortunately there is a strict no-refunds policy, so we can't give your items back. How did you die twice though? Was there the "you died" message twice in a row when you fell off?

**Comment by YummyDuck** [comment]
Yes, I did get the death message twice in a row when I fell off.

**Comment by Moe-Ronickah** [comment]
Unfortunately, you took a flying Leap to your death with only 4sp, therefore, 2sp left.  How you died a second time, I don't know, but that is the real issue, here.  I'd like to know if you saw what happened.  Was it a mob?  Did you respawn over the abyss?  What do you remember about it?

As to the lost items, as TrashcanMan said, I'm sorry, but there is a strict no-refunds policy.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
