### ISSUE TITLE
Worlds aren't rendering correctly for me.

### ISSUE THREAD

**Issue by DIroDoku** [Wynncraft/Issues#4653]
# Delete this line if you've searched for a duplicate issue first
After entering wynncraft after an extended period of time, I came back to notice that spawn was completely unidentifiable. This may be a 1 time thing, but I am a afraid to go back on simply because of what it looks like:

![20160325222250_1](https://cloud.githubusercontent.com/assets/7871758/14057798/d9364138-f2d8-11e5-997f-3b660f33b7b9.jpg)
![20160325222208_1](https://cloud.githubusercontent.com/assets/7871758/14057799/d93660fa-f2d8-11e5-9fb3-6db6f95d0faf.jpg)
![20160325222215_1](https://cloud.githubusercontent.com/assets/7871758/14057803/d93a1a7e-f2d8-11e5-9e41-8d9cb5e77fe9.jpg)
![20160325222219_1](https://cloud.githubusercontent.com/assets/7871758/14057801/d938455a-f2d8-11e5-91b7-9db21ea493b8.jpg)
![20160325222222_1](https://cloud.githubusercontent.com/assets/7871758/14057802/d9393604-f2d8-11e5-8e4d-dabcb4d9b1d9.jpg)
![20160325222239_1](https://cloud.githubusercontent.com/assets/7871758/14057800/d93778be-f2d8-11e5-9544-d036bd482b06.jpg)

**Comment by Odnod** [comment]
What version of minecraft are you using? also what client?

**Comment by TrashcanMan** [comment]
Update your graphic card drivers, I've seen this happen before and usually it's client-side. Also if you are in 1.9 I'd recommend you downgrade to 1.8.9 for now since 1.9 is fairly buggy.
