### ISSUE TITLE
Im stuck

### ISSUE THREAD

**Issue by SanneLoves** [Wynncraft/Issues#4655]
I'm stuck idk where but i cant see anything i got all my stuff
I looked on f3 and look whats around me and there was black wool.
Please help me i cant play now on my other classes im out and the last time i played with mage i was standing in detlas or nemrect now im stuck :(

**Comment by SanneLoves** [comment]
Im out now but still its weird

**Comment by Trixter313** [comment]
That was the class selection room. Glad to hear you got out!
