### ISSUE TITLE
I stuck in my guild

### ISSUE THREAD

**Issue by CracotteFX** [Wynncraft/Issues#4656]
Hi.I need help i can't leave my guild with my friend.Can you disband this pls ? (Name of the guild : KryJeKtion)
Thank you for your help

**Comment by Trixter313** [comment]
Could you give us a little more detail? What happens when you try to leave? Are there any messages in chat about it? Etc. Thanks!

**Comment by Trixter313** [comment]
Assuming your username is the same as your Github, it appears that you've changed your name in the past, meaning this is a duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!
