### ISSUE TITLE
In LLevigar At Lv.24

### ISSUE THREAD

**Issue by LazerSnipe** [Wynncraft/Issues#4659]
I was a Lv.24 Mage and I was curious about the other islands. When I reached LLevigar, The screen said that I reached LLevigar but there was a barrier blocking me.So I died from a Guardian guarding a relic for a powder and when I respawned and I was in LLevigar.Please tell me if this is a bug or was supposed to be there.Thanks!

**Comment by Odnod** [comment]
I know that I have been to llevigar at level one, but it was a while ago. I don't quite understand what you have experienced.

**Comment by Moe-Ronickah** [comment]
What he found was a quirk of the death teleport system.  He died next to Llevigar, so he got tped into Llevigar to respawn, it being the closest town to where he died, however, he couldn't get into Llevigar through the doors, originally.  It's not an issue, it's just an artifact of the respawn system.
