### ISSUE TITLE
Items Gone

### ISSUE THREAD

**Issue by ZerGom** [Wynncraft/Issues#4660]
So I was In Detlas when I went to get something to eat. When I came back all my Items were gone except quest items and an Oak Wood Stick (I'm level 19 Mage). So please help me :(.
(Only Inventory is gone).
IGN: ZerGom

**Comment by Trixter313** [comment]
That's what happens when you are killed with less than 3 soul points. Something must have killed you while you were away from the computer.

**Comment by ZerGom** [comment]
But if something killed me i would've gotten teleported, but it didn't teleport me.

**Comment by Trixter313** [comment]
Is it possible someone else got on the computer and did it, moving the player after they died?

Wynncraft has a strict no refunds policy so no matter the case we can't give any items back and there's no way we can find the cause if all we have is that you left, came back, and the inventory was exactly as if you ran out of soul points. This looks like a dead end unfortunately.

**Comment by ZerGom** [comment]
Then there's nothing to do. Thank you anyways ^^

**Comment by Trixter313** [comment]
I hope this doesn't happen to you again!
