### ISSUE TITLE
Bugs galore

### ISSUE THREAD

**Issue by Nethertaker** [Wynncraft/Issues#4661]
I just finished the lvl 20 sayleros's brother quest (as in, i had killed the brother). I went to go talk to the church person and only blank lines of chat showed up. i logged out and logged back in to see if that would fix it, but I logged on and was immediately stripped of half my armor, with the message "nightmail requires your agility skill to be at least 3" and "kuuchi requires your intel skill to be at least 5". Checking my skill points, I found that they had all been reset, and i had 0 points and 0 to spend. Also, mobs can't attack me anymore. Instead they simply push me around.

help?!?
Nethertaker

**Comment by Trixter313** [comment]
Simply typing /class or relogging should fix the issue. Comment back if it doesn't. Thanks!

**Comment by Odnod** [comment]
For gravedigger, the quest ends at Sayleros
