### ISSUE TITLE
Flight in distress engineer Npc won't spawn

### ISSUE THREAD

**Issue by Matchubaka** [Wynncraft/Issues#4662]
I was starting the Flight in distress quest when the server restarted and when i logged back in i was in the tutorial, now i can't talk to Captain Ackbar and the Engineer won't spawn so i can't complete the quest. Please help!

**Comment by Odnod** [comment]
Progress through the quest as you did before. Talk to the kid, then the captain, then sleep, etc.

**Comment by Trixter313** [comment]
Can you still not progress?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
