### ISSUE TITLE
Wynncraft Excavation site A

### ISSUE THREAD

**Issue by icecreeper01** [Wynncraft/Issues#4663]
Hi my mine craft name is icecreeper01 and the wynncraft excavation site A. i have done most of the quest but then i had to take a tablet to tesha to translate and she said it was translated and she said she gave it back to me but i didn't get it now it says to go to excavator vade and he asks if i have translated the text yet and to take it up to tesha. This happened over a year ago and i reported the issue. They said to use /fixquests which didn't work and i posted one like a year ago which they closed and said to follow a duplicate of the case which was also closed because /fixquests worked for one guy. i have been waiting for an update because they said that the update would fix this quest but update came out and same problem with /fixquests still not working. now i can't even do excavation site B because i need an item from wynncraft excavation site A. Please fix this as soon as possible because this problem has really been bothering me. Would it maybe be possible to give me that item or at least reset just that quest? also i don't want to restart because I'm level 47. Please fix this really soon this is really messing up my progression in wynncraft.

**Comment by Odnod** [comment]
Go into the temple, it is just a weird dialogue thing. Progress through the quest as you normally would following the wiki.

**Comment by icecreeper01** [comment]
Thanks SOOO much it finally let me finish this quest and now i can do the second part :D Thanks!
