### ISSUE TITLE
MY BOW IS A HALF SLAB

### ISSUE THREAD

**Issue by razzoe2880** [Wynncraft/Issues#4667]
my precision bow look is a half slab.
is it something in the resource pack or what

**Comment by DarkDemonDragon** [comment]
Yes it's probably something to do with the resource pack. What version of Minecraft are you using?

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

Please direct any future comments to the original thread. Thanks!

**Comment by DarkDemonDragon** [comment]
@Trixter313 he's using the Precision bow not the relic bow.

**Comment by Trixter313** [comment]
The other comments and the title mention that it affects other bows also. They are all in one issue rather than being scattered all around.
