### ISSUE TITLE
Help- I'm stuck

### ISSUE THREAD

**Issue by peerbooms** [Wynncraft/Issues#4669]
IGN-peerbooms
Whilst finishing of the wynnexcavation site A quest, as i kill the boss and enter the black portal, i am tped into blackness and i currently cannot do anything about it, I'm online atm in world 1 i believe; i would very much appreciate if a member of staff can tp me out.
Regards, peer.

**Comment by peerbooms** [comment]
![image](https://cloud.githubusercontent.com/assets/18100393/14065586/12248892-f428-11e5-9f04-b8a7d1f9df05.png)

**Comment by DarkDemonDragon** [comment]
Do /kill if you have 3 or more SP and you'll respawn in the nearest town (most likely Almuj)

**Comment by peerbooms** [comment]
And I wont lose my equips?

**Comment by DarkDemonDragon** [comment]
Only if you have more than 3 SP. I see you have 11 so you should be fine..

**Comment by peerbooms** [comment]
Ah okay thanks a lot!

**Comment by DarkDemonDragon** [comment]
Remember this tip if you are ever stuck anyway. If your issue has been resolved please close this.
