### ISSUE TITLE
Teleport Configuration Blank @ -124, 98, -245

### ISSUE THREAD

**Issue by Josh-Sturgeon** [Wynncraft/Issues#4672]
A cave near the Temple of Legends area has a button at the end. After pressing it you are blinded as if you are teleporting but you then get the following message: "_>ERROR: Teleportation configuration blank. No destination found!_"

The location of the button meant to trigger the teleport is: -124, 98, -245

You may find the following Imgur album of screenshots useful: http://imgur.com/a/bQgDf

**Comment by Odnod** [comment]
This location is not meant to be accessible yet. So it isn't so much a bug as a little Easter egg.
