### ISSUE TITLE
Class Selection Broken

### ISSUE THREAD

**Issue by Cyber4** [Wynncraft/Issues#4673]
Upon logging into the server to select my class, I fall out of the chamber infinitely.  If I am ingame I cannot do /class, it doesn't teleport me and I can't speak or use commands

**Comment by Odnod** [comment]
The only way we have found to fix this in the past has been by uninstalling and reinstalling Minecraft.

**Comment by Moe-Ronickah** [comment]
@Cyber4 , did Odnod's suggestion work?  If it did, please close this issue, and if it didn't, please let us know.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
