### ISSUE TITLE
Wynn Excavation Site D - Dialogue Bug

### ISSUE THREAD

**Issue by Rapid418** [Wynncraft/Issues#4675]
When I was completing the quest 'Wynn Excavation Site D', I came upon an issue with 'Traitor Amadel'. If you were to click on him, instead of giving you his normal dialogue, he gave you a blank line. I've tried switching servers, but to no avail. For reference on his location, he is in the Traitor Camp in the Dernel Jungle. Here is a photo of the issue: 
![2016-03-27_13 54 25](https://cloud.githubusercontent.com/assets/18103190/14066938/fb1f3a90-f425-11e5-9261-811e96a9e3ef.png)

**Comment by Odnod** [comment]
This probably means that you have either already talked to him or you skipped a step of the quest by accident. Check your quest book, and if it says to talk to Amadel, leave the chamber through the back, then re-enter.

**Comment by DarkDemonDragon** [comment]
Please post a screenshot of your quest book.

**Comment by Rapid418** [comment]
![2016-03-29_12 32 54](https://cloud.githubusercontent.com/assets/18103190/14115808/893bc9bc-f5aa-11e5-9602-f77474f2587d.png)

**Comment by DarkDemonDragon** [comment]
Try talking to all the NPCs in that mini cave and see what happens. I think you're supposed to talk to one of the other's first and then he says talk to Amadel. Tell me if this works or not.

**Comment by Rapid418** [comment]
I have checked what they said. They both seem to just say how they hate Wynn Excavation, and how they used to work for them. None of them said anything about Amadel. My best guess for the problem is that the NPC I need to talk to should have the name of 'Rebel Leader Amadel', rather than 'Traitor Amadel'.

**Comment by crazydud24** [comment]
i have the exact same thing happening to me and i cant do anything to fix it

**Comment by crazydud24** [comment]
still no fix or information about what is going on here. i was looking forward to finishing the story but i cant progress and i haven't been able to do anything for ALMOST 2 MONTHS

**Comment by Moe-Ronickah** [comment]
Please check the Wiki for WynnExcavation Site D and make certain that you have not skipped any steps, then let us know what is happening.

https://wiki.wynncraft.com/index.php?title=WynnExcavation_Site_D

**Comment by crazydud24** [comment]
I have not been on wynncraft for a few weeks so I don't know if it's fixed but I did go back though and I didn't skip anything. The only thing I can think of is I went into the teleport zone the instant befor it said the quest book updated in chat so it may have confused the systems

**Comment by Moe-Ronickah** [comment]
OK, give it another try, when you can, and see if it works now.  If it doesn't work, let us know.
