### ISSUE TITLE
Falling through the world?

### ISSUE THREAD

**Issue by OrangeNinjaBunny** [Wynncraft/Issues#4682]
I've searched for an issue similar to mine, but there isn't really anything similar.

Every time I connect to a world I start of at x: 1 y: 52 z: 1, this is presumably where I last logged off at however I cannot remember if this is true. A crafting table in front of me with a wooden structure appear around me but this immediately goes away and I start falling into a black abyss. The x and z stay the same but the y coordinate keeps going on into the negative. I haven't tested exactly how far "down" I can go but it's at least -40,000.

I have no idea how to fix this: I've uninstalled Minecraft and reinstalled it, I've tried to /kill myself, and I've even used several computers. 

If needed, my in game name is: OrangeNinjaBunny

**Comment by Trixter313** [comment]
Do you have the resource pack enabled? If not, make sure you enable it in Multiplayer > Wynncraft > Edit > Server Resource Packs

**Comment by OrangeNinjaBunny** [comment]
The resource pack is enabled, I still fall into the black abyss. It makes no difference whether I have the Wynncraft resource pack or default on.

**Comment by Td193616** [comment]
Have you tried /kill?

**Comment by OrangeNinjaBunny** [comment]
Yes, it says that I can't perform that command at 'this time'. I'm not sure if I just can't do it or maybe it's because I'm technically moving, which can cancel out the command.

**Comment by OrangeNinjaBunny** [comment]
This is still an issue, it's a month later. I'm really not sure what to do. I may need a mod to help me out, I don't know.

**Comment by mcmasterchief100** [comment]
i still have that issue as well

**Comment by OrangeNinjaBunny** [comment]
Just got teleport-ed to the major updates room, not sure when it happened but it fixed my problem, woo!
