### ISSUE TITLE
Xp and Loot Bonus 

### ISSUE THREAD

**Issue by DoubleSnipe** [Wynncraft/Issues#4684]
So I have an issue when I look at my character info, it says I have +4% xp bonus and +17% loot bonus when in reality I should have more. I have armor and accessories that also buff these, but for some reason my character info says it's always less than it should be. I have proof of how it's higher than what it should be here ->http://imgur.com/a/RUgQq
Now would this affect my overall stats or is it just not displaying in my character info because I want to get credit for all the bonuses I have and not get ripped off from these accessories

**Comment by Odnod** [comment]
Your xp bonus and loot bonus are realistically displayed.
**XP:**
+29 from jester necklace
-25 from jester necklace
+4 Total
**Loot:**
+6 from Capstone
+15 from Shameful Greaves
+21 from Jester Necklace
-25 from Jester Necklace
+17 Total

Any bonuses from weapons do not count unless you are currently holding them

**Comment by DoubleSnipe** [comment]
Here's my question though. The -25 xp and loot bonus from the jester necklace is a set bonus. So how does that still affect me when I don't have the full set?

**Comment by DarkDemonDragon** [comment]
The jester set is different from other sets. For all other sets you need the whole set for a bonus. The jester set gives a bonus at 1/3, 2/3, and 3/3 each having a different bonus.

**Comment by Moe-Ronickah** [comment]
It's a Jester set.  Jester's jest, that is, they joke.  The wonderfully high XP and Loot bonuses are jokes and only really "add up" when you have a full set.
