### ISSUE TITLE
I can't see name tags on monsters

### ISSUE THREAD

**Issue by AdaClovisdoesMC** [Wynncraft/Issues#4688]
When i entered the game once i couldn't see any monsters names or their health, What do i do?

**Comment by Trixter313** [comment]
What MC version are you using? Make sure it's either 1.8.9 or 1.9.

**Comment by Dar-krusos** [comment]
This is probably just a temporary glitch that fixes itself in time or after restarts. If not, then try switching versions and/or changing to all default visual settings.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
