### ISSUE TITLE
Item Identifier gives outdated message

### ISSUE THREAD

**Issue by TheDollarBill** [Wynncraft/Issues#4689]
This item identifier message is outdated since mythic items have came out (and the word "set" should be green)

http://i.imgur.com/oWqA56R.png

**Comment by CookedPelvis** [comment]
Welllll, mythics are sort of a hidden little feature of the item tier system. They are not mentioned directly in the "Help" tab on wynncraft.com, but it says something along the lines of "There are myths that another tier of weapon exists..." after legendary, but who knows.

In response to the set being dark blue, you are right, that should be changed.

**Comment by Moe-Ronickah** [comment]
Fixed.
