### ISSUE TITLE
I can not ping to the wynncraft server!

### ISSUE THREAD

**Issue by GordonDaFreeman** [Wynncraft/Issues#4690]
I tryed to ping just normaly with just refreshing the Minecraftserverlist.
Also i tryed to ping the wynncraft server manualy via CMD "ping play.wynncraft.com"
got an timeout Error.
thank you for any help.

**Comment by CaptainPrickles** [comment]
This has been happening to me lately aswell. Simply restart your computer to fix it.

**Comment by Moe-Ronickah** [comment]
Just close and restart your MC, that's usually all that it takes.
