### ISSUE TITLE
2 Grammar errors in Finding the light!

### ISSUE THREAD

**Issue by Endeh** [Wynncraft/Issues#4692]
Error #1: 
"I'm sorry dads" (assume it is "dad" unless... well... ya'know)
https://gyazo.com/576fdcd9c78173befc3184d16577e9f9

Error #2:
"Look that's the price. I can' change it" (assume it is "can't)

**Comment by Odnod** [comment]
Nah, with error number one, the kid's parents are a gay couple. And as for number 2, @AckroWynn.

**Comment by AckroWynn** [comment]
Fixed the second. Thanks!
