### ISSUE TITLE
IM STUCK WITH NO WAY OUT !!! 

### ISSUE THREAD

**Issue by BlackDiamond44** [Wynncraft/Issues#4693]
in the mission Wynn excavation site B I fell on a hole and I tried to use a scroll to go back and it didn't work, can someone help me> Im an assassin lvl 46
![2016-03-28_22 29 25](https://cloud.githubusercontent.com/assets/18134170/14098822/9f5343e0-f534-11e5-84a0-9d492ac881bf.png)

**Comment by Odnod** [comment]
type /kill

**Comment by BlackDiamond44** [comment]
thanks
