### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by PikaLord** [Wynncraft/Issues#4694]
I have more than one char and my best one is stuck at the inn in Wynn. I sleeped in a bed there and then i pressed esc and i got stuck in fire walls. It was in room 3. Teleport scrools arent working and i cant se anything in there. And i tried useing teleport scrools both to Ragni and to Deltas. Please write to me when you are in and helping me out.
Mincraft name: PikaLord2

PikaLord

**Comment by DarkDemonDragon** [comment]
Tip 1: NEVER sleep in a bed as the are all purely for decoration. Even the build team and admins suggest this.

Tip 2: If you are ever stuck in something and wish to get out then do /kill if you have 3 or more Soul Points. Doing /skill with 2 or less SP will result in the loss of all items, so be careful.

**Comment by PikaLord** [comment]
Okay thanks but its was actually an accident but thanks anyway

**Comment by PikaLord** [comment]
But stil my scrolls dont work

**Comment by DarkDemonDragon** [comment]
Aim at the air. Scrolls don't look if you're pointing at the ground.

**Comment by DarkDemonDragon** [comment]
If you issue has been resolved please close this.
