### ISSUE TITLE
Negative Guild XP

### ISSUE THREAD

**Issue by OMGitsTomix** [Wynncraft/Issues#4695]
Hello,

Few days back,our guild got -631 xp,we don't know how it happened but it's not getting into normal.
Now we are at -621 xp and it will took us months to get back to normal,please reset our xp to 0 (not level,only xp),we have level 39 and get back to 0 xp and start getting xp will took us so long,please help.

Screenshot: http://imgur.com/ZersRCZ

**Comment by OMGitsTomix** [comment]
Well,it looks like nobody is going to help,why is there that "bug report" section? lol

**Comment by Dar-krusos** [comment]
This has been a longstanding issue, and will doubtfully be fixed any time soon. Guilds are the last of the developers priorities (as it would be so), so all you can do now is wait.
For this specific bug, you must get that percentage back down to 0% so it can go into positives again. That may take some time, but I haven't heard of guilds going into negatives at that low of a level, and by that much percentage.

**Comment by YunoFGasai** [comment]
correct me if I'm wrong but your xp is positive now.
