### ISSUE TITLE
I lost my 2 legendary daggers in a glitch their levels are 51 and 55.

### ISSUE THREAD

**Issue by AwaPlaysWC** [Wynncraft/Issues#4696]
I lost them in a glitch that when i had my lvl 51 dagger on my hand i did /lobby and then i came back it was gone and when i was farming with my lvl 55 dagger i noticed my dagger was missing and i searched the entire cave i was farming in and i did not see it. It was in a cave near the jungle village i hope i get my daggers back because now i have no daggers and i cant do any quests and i can't farm and nobody sells daggers :,(

**Comment by DarkDemonDragon** [comment]
Unfortunately Wynncraft has a strict no-refunds policy. Please try to explain the glitch in further detail so that this does not happen to other players.

**Comment by Verret001** [comment]
No reply in more than two days; If this issue persists repost with a link to this thread.
