### ISSUE TITLE
Wynn Excavation site A

### ISSUE THREAD

**Issue by Itor223** [Wynncraft/Issues#4697]
After completing the end of the quest, I went to go talk to the main NPC of the quest and my inventory space was full, so I cleared my inventory by dropping some emeralds. Then when i talked to him i accidentally pick the emeralds back up, thinking that what i got would just drop onto the ground. But after he finished talking an error message popped up saying my inventory space was full again. so I tried talking to him again, and he told me to go talk to another NPC to get the "Translated mummy writings" which i had used to complete the quest the first time. So when i go and talk to the other NPC thats supose to give you the translated writings, and she tells me top go give the writings to vade, the main NPC. Which i used for the quest the first time. Please help.

**Comment by Itor223** [comment]
I forgot to add that when I do /fixquests it says i don't have any missing quest items

**Comment by Odnod** [comment]
you probably just have to go back and get some of the yellow crystals by killing the pharaoh in the temple. Bring Vale the crystal to complete the quest.

**Comment by BlueThunder25** [comment]
@Odnod is correct. Please close this issue if it is solved.

**Comment by Odnod** [comment]
@BlueThunder25 calm down, we don't know if my advice actually worked or not.

**Comment by BlueThunder25** [comment]
@Odnod Oh i am sorry if that came across rude I did not mean it like that, my apologies :)

**Comment by Odnod** [comment]
@BlueThunder25 it's fine, but it will (likely) be closed in time.

**Comment by Verret001** [comment]
13 days of inactivity. Think it's safe to say it's resolved.

**Comment by Moe-Ronickah** [comment]
@Itor223 , was the problem that you didn't have the Yellow Crystal when you went back to talk with Vade?  Is this fixed for you?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
