### ISSUE TITLE
Bob's Reincarnation

### ISSUE THREAD

**Issue by Strikefire150** [Wynncraft/Issues#4698]
My sister and I were doing Bob's Reincarnation, when we killed it, but as soon as we killed it, my sister was killed by a sword... I had to open the gate for her (it was just us two and the item was still there), but when we got back, the item disappeared... Now we are going to have to do it all over again... Usually a item would despawn within five minutes, but it despawned instantly... please help. Thanks.

**Comment by Strikefire150** [comment]
Nevermind, we just did it again. You can close it now.

**Comment by Odnod** [comment]
You can close it .-.
