### ISSUE TITLE
Screen glitching out

### ISSUE THREAD

**Issue by LordAsher** [Wynncraft/Issues#4699]
I went on Wynncraft one day, and out of now where my screen started freaking out. This is the only server this has happened on.
![2016-03-29_17 49 39](https://cloud.githubusercontent.com/assets/18155283/14128626/5ac6e92c-f5d7-11e5-881c-19455d15dac1.png) 
This is what is happening, and it is really strange, PLS HELP

**Comment by TrashcanMan** [comment]
I've seen similar issues before, and usually it's an issue with your graphics card drivers. Make sure they're all up to date, then try again.
