### ISSUE TITLE
FixQuests Glitch *Need Help*

### ISSUE THREAD

**Issue by sportdudeman** [Wynncraft/Issues#4700]
To start off, If there does happen to be a thread that is the same as this one, simply reply a link directly to that thread and I will remove this one. What happened was while doing The Ultimate Weapon quest, the soft whetstones were not spawning. (This is fixed now) I attempted /fixquests to see if it would do anything. Instead, it gave me a few crystal shards and cluckle's feather. I can not remove these items even though I have finished their respective quests. I have provided a video that shows exactly what I mean.
http://sendvid.com/wjlfzmc6
(P.S. The 64 LE are legit and I got them from trading a mythic)

**Comment by Odnod** [comment]
Have you completed Reincarnation as well as all of the Wynnexcavation quests?
