### ISSUE TITLE
Lost my items. I think I was hacked.

### ISSUE THREAD

**Issue by Zebstrikal** [Wynncraft/Issues#4701]
I was walking around Nesaak doing shopping and stuff. I saw a server restart message so I logged out and just decided to come back later. After I logged out my internet shut off (Ddos attack im assuming) then when I rebooted the router and toyed with the DNS I logged back on and I got the message that my someone was on using my account. When I got back all of my emeralds were gone and my legendary leggings with +32% loot bonus Opulenity were gone. and one of my items was dequipped. I don't think it was lag because then all of my items would be equipped and not just my highly valued leggings would be gone. IGN The_Waffle_House
Rank: VIP+ Veteran
Level: 41
If I could I would have screenshots but I was very discombobulated at the time. Any way to reclaim my items and help me secure my account would be much appreciated and I can also provide exactly what I lost and a play by play on what happened.

**Comment by TrashcanMan** [comment]
Unfortunately we cannot refund lost items, especially without any proof. I'd say you were most likely hacked, so I'd advise you to change your password as soon as you can.

**Comment by Zebstrikal** [comment]
Thankfully it wasnt everything I owned I appreciate the quick response however.
