### ISSUE TITLE
Item bomb glitch

### ISSUE THREAD

**Issue by Flying-Froge** [Wynncraft/Issues#4706]
I have recently bought an item bomb for my me and my friends. I went to go set it off it exploded; I saw the armor fly out and onto the ground but then it disappeared after like a couple seconds of trying to pick the items up. My friends looked in their inventory for any new items and didn't find anything, I didn't have anything in my inventory either.
Please help me with this problem

**Comment by DarkDemonDragon** [comment]
Be honest, did you try to pick up the items for yourself or did you really have other people around?

**Comment by Flying-Froge** [comment]
I Reyes to pick up the items my self it was just me and another friend 2 people and we both couldn't pick the items up

**Comment by Flying-Froge** [comment]
Tried*

**Comment by Flying-Froge** [comment]
Really?

**Comment by Flying-Froge** [comment]
That sucks

**Comment by TrashcanMan** [comment]
Unfortunately as part of the EULA you aren't allowed to pay real money for an in-game advantage so you can't pick up items from your own item bombs.

**Comment by Moe-Ronickah** [comment]
And now that you know about yourself trying to pick up items from your own item bomb, did you really have two friends with you?

**Comment by Flying-Froge** [comment]
Yes

**Comment by DarkDemonDragon** [comment]
Well do you have any evidence of the situation? Any screenshots would be nice. Unfortunately without any concrete evidence it'll be difficult for the Admins to deal with this bug as without knowing the cause they can't do anything. If this happened as you said it couldn't be lag unless you're exaggerating "disappeared after like a couple seconds". Remember that using hyperbole is not effective when making a report.
