### ISSUE TITLE
Lost Account.

### ISSUE THREAD

**Issue by ethanscheiber** [Wynncraft/Issues#4710]
Recently, my account was compromised due to Mojang losing my email information. I was a level 24 Archer with the following items: Meridian, Skin Piercer, Sunblock, and some random golden armor. Here is proof of the meridian and some other junk: https://gyazo.com/9b373422bb977672a8748b9f173bddc5. Now I really do not fancy restarting my whole journey on my new account, so is there a way all of my data can be transferred from the account EthanBuilds to EthanBuilds_ ? Please respond quickly.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strict no refunds policy so there's not anything we can do to get the lost items to your new account.
