### ISSUE TITLE
Glitch with Item Pickup

### ISSUE THREAD

**Issue by JackOFrost** [Wynncraft/Issues#4712]
I was taken to the jungle village where I died, my friends who took me there helped me get back to my tear that contains my items. It would not let me pick up my items and I had to stand on them for multiple minutes before watching all of my hard work disappear in-front of my eyes. I lost a legendary Dislocator, a legendary The Divine (both assassin weapons) all of my amazing armor including a zombie helm and my night-something armor (can't quite remember it's name) and other amazing items as well as just over 20 Emerald Blocks. Please try to fix this bug sometime soon as this has made me almost completely quit Wynncraft as I spent a huge amount of hours grinding to get that gear and for the emeralds to pay a friend of mine to get The Divine (bought off forum).

PS. If you need to find me I'll be walking around the jungle village as I am trapped there with no items but a brown horse, starter dagger and a dagger my friend gave me for lvl 57 (I'm a lvl 22 assassin)

**Comment by Odnod** [comment]
Sorry about the loss, but if you want to get out of the jungle I can escort you. Also why were you there at level 22?

**Comment by JackOFrost** [comment]
I wanted to level up quickly to level 26 so I could use The Divine so I went with them to higher leveled mobs.

**Comment by JackOFrost** [comment]
If you could please give me a teleport scroll to detles or ragni that would be prefered I have 1 soul point and I managed to kill one of those things that throw iron swords and it gave me a rather rare chain armor piece worth a good chunck of change.

**Comment by JackOFrost** [comment]
I'm on server 6 atm...
