### ISSUE TITLE
I have lost all my items after logging off

### ISSUE THREAD

**Issue by yolomaster546** [Wynncraft/Issues#4713]
Before I logged off the game i had some items in my inventory, and 11 soul points. But when i logged back on my messages were being spammed: You have died, Two soul points have been taken away. The next thing i knew was i had lost all items in my inventory. My armour, weapons and emeralds had been taken away. So now i am here, asking for the Server admins, asking if it will be possible to retrieve all my lost items. I would be very much appreciated if you could do that.
 
Minecraft username: yolo_master546

The list of items i lost:
-Duskhelm
-Katoa's Warmth
-Skeletal Legs
-Cyclo
-Broken Trident
-Granite Dewn Spear
-2x Liquified Emerald 
34x Emerald Blocks

That is all that i ask for and I hope that you may help

Sincerely- Yolo_master546

**Comment by DarkDemonDragon** [comment]
Okay several things:
1) MAJOR: Wynncraft has a strict no-refunds policy
2) Some proof would be necessary such as your logs. Please check the Logs section in my Evidence thread here: https://forums.wynncraft.com/threads/evidence-ban-reports-bug-reports-etc.116166/
I'll need the logs of the day of the incident and the day before.
3) Server Admins rarely check Github
4) NEVER have LE in your inventory unless you are making a trade or need it for a quest, but even then make sure it's in your inventory for a minimal amount of time.

**Comment by Moe-Ronickah** [comment]
Where did you die, and where did you respawn, if you remember.
