### ISSUE TITLE
[URGENT/Still Need Help] Server Crashes on Join

### ISSUE THREAD

**Issue by MrFlameMC** [Wynncraft/Issues#4715]
Hello! I have found a glitch so I joined today and I spawned 30k blocks on the X and the Z coords. which when I join the server crashes, I am unsure how I got there as I woke up and joined and I teleport in every world to those coords. I am extremely annoyed as it crashes that world and I can't play with my friends. My username is Xen0n and I might need to be tped or set to be at some place so that I am not far away and don't crash the game.

**Comment by Trixter313** [comment]
Have you tried typing /kill as soon as you login? This will bring you to the nearest visited town. There may or may not be enough time to do it but try to do it as fast as possible and it's worth a shot.

**Comment by MrFlameMC** [comment]
Yes I cannot type a command as it instantly lags and crashes leaving no time to type it I tried for about an hour to do that and it has not fixed it

**Comment by MrFlameMC** [comment]
Oddly /hub works but other commands like /kill don't

**Comment by MrFlameMC** [comment]
I just figured that out

**Comment by Odnod** [comment]
I feel like I have seen this issue on the github before, but I am unable to find the issue exactly. This seems somewhat similar in nature to the falling in the void glitch, and **may** be fixed by uninstalling and reinstalling minecraft.

**Comment by MrFlameMC** [comment]
Already tried that no cigar. I read it on the 3rd page and no luck with it!

**Comment by Odnod** [comment]
Does this happen once you select a class? Or is it when you initially try to join a server.

**Comment by MrFlameMC** [comment]
No it's on every class

**Comment by MrFlameMC** [comment]
I have auto join
and once it tped me to where I last was it then crashes since it puts me in the location that I logged out on which is at x 30k and z 30k.

**Comment by Odnod** [comment]
Strange. You could try to contact an online mod via the forums to see if they can teleport you in time/at all.

**Comment by MrFlameMC** [comment]
Okay

**Comment by MrFlameMC** [comment]
Staff aren't replying to when I try to request them to help. Great day my friend is 10 levels ahead of me now in a completely new zone. I wish this would have a fix!

**Comment by MrFlameMC** [comment]
Bump...

**Comment by DarkDemonDragon** [comment]
When you get spawned in I want you to pay attention right before you crash. Do you see a level?

**Comment by MrFlameMC** [comment]
Okay I see downloading terrain and then I see my hotbar and such but I am in the void.

**Comment by MrFlameMC** [comment]
I don't crash the server crashes like the actual worlds shuts off for everyone it is a huge error

**Comment by MrFlameMC** [comment]
It says Server Shutdown when I get placed in the hub after it crashes

**Comment by MrFlameMC** [comment]
It's not my connection the server can't load the chunks at the coords and it crashes...

**Comment by MrFlameMC** [comment]
so I can never play wynn craft again.

**Comment by Trixter313** [comment]
I just put the closest tags to the issue on it to make it pop more so higher admins are more likely to see it. There isn't really a better tag.

**Comment by MrFlameMC** [comment]
Oh alright.

**Comment by DarkDemonDragon** [comment]
@MrFlameMC when you spawn in do you see a level or no? If yes then your character is actually stuck somewhere. If no, then you're stuck in a limbo situation as for some reason you cannot access your character at all.

**Comment by MrFlameMC** [comment]
Yes I see a level. my level and my hotbar if that's what you mean. if you mean land then no I am in limbo.

**Comment by MrFlameMC** [comment]
I have my character on autojoin

**Comment by MrFlameMC** [comment]
and can't get off autojoin as only /hub works because the server insta crashes

**Comment by DarkDemonDragon** [comment]
@MrFlameMC I mean like the level of the character. So if your autojoin is on your lvl 50 Archer then when you spawn in you should see 50 at your hotbar.

**Comment by MrFlameMC** [comment]
Yes I see a level 32 which is my mages level.

**Comment by MrFlameMC** [comment]
Still needing help

**Comment by MrFlameMC** [comment]
I quit my friend is level 80 now I have no point in playing.

**Comment by Moe-Ronickah** [comment]
@MrFlameMC , if you are still around, and this is still going on, from the hub, go to the Nether, then turn off outjoin.  That seems to be helping with other issues that are similar.

**Comment by MrFlameMC** [comment]
Thanks !

**Comment by Trixter313** [comment]
Is your issue now resolved then? =D

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
