### ISSUE TITLE
LOGGED OUT MID END-QUEST DIALOG, LOST QUEST ITEMS

### ISSUE THREAD

**Issue by TheCatArchy** [Wynncraft/Issues#4716]
This is a huge issue for me because I logged out mid-quest and lost the [Boot Container] which I can obtain again but my real issue is I lost the [Abysso Galoshes] which are a quest item that cannot be obtained again without completing the quest. 
Please help?
I know that Wynn's biggest rule is no refunds, but this is a quest item! I can't reobtain it ;-;
Help please!

**Comment by Odnod** [comment]
type /fixquests to regain them I believe.

**Comment by TheCatArchy** [comment]
Thanks for the help! I didn't know about that x3
