### ISSUE TITLE
Mummy's Rag Attack Tier Bug

### ISSUE THREAD

**Issue by riptidecraft** [Wynncraft/Issues#4719]
For the Mummy's Wrath quest I got the Mummy's Rags chestplate, and on it it had + 2 tier attack speed, yet when i put it on it doesn't add anything to my attack speed. Am I the only one having this issue?

**Comment by DarkDemonDragon** [comment]
Please provide screenshots so we can better access the situation.

**Comment by riptidecraft** [comment]
This is also the same for a +1 tier attack speed i got on my assassin but stopped working for that one too.
![2016-04-01_17 18 25](https://cloud.githubusercontent.com/assets/18203684/14223038/fc3535fe-f82d-11e5-961b-0144d1bf2d81.png)
![2016-04-01_17 18 49](https://cloud.githubusercontent.com/assets/18203684/14223039/008e6936-f82e-11e5-8db8-4a72495388f1.png)
![2016-04-01_17 19 13](https://cloud.githubusercontent.com/assets/18203684/14223041/04fd3fce-f82e-11e5-920d-a6770b748b2b.png)

**Comment by riptidecraft** [comment]
Sorry for the 2nd thread. Anyways please notify me when the issue has been fixed

**Comment by Lulink13** [comment]
I have the same problem with my lv 49 Archer... Maybe it's be due to the fact that the archer is the only one who attacks with right clicks instead of left? Please try to find a solution: this is a real handicap...

**Comment by Odnod** [comment]
Ok. So I believe that this bug is actually the same as another. Attack speed bonuses (on armor only?) Only affect the speed at which you attack with your weapon and not the speed at which your attacks register (spell damage is still affected.) However, archer does not attack by swinging so it is harder to tell. I hope this brings some clarity to the situation as to what is going on here.

**Comment by riptidecraft** [comment]
So is there a way to fix it?

**Comment by Lulink13** [comment]
I know that might sound unrelated, but the Mummy rags disappeared from my bank chest... Maybe they decided to take the item down rather than fixing it's stats right away? That might also be a coincidence...

**Comment by riptidecraft** [comment]
i still have mine

**Comment by RedMorcus** [comment]
Can confirm that it still affects spell damage.

**Comment by Lulink13** [comment]
I don't really care now that It's underleveled for me, but it would be nice if other attack tier items worked... It's other starts worked so I believe it's only that one which bugs on archers.

**Comment by Yoavronen** [comment]
> I don't really care now that It's underleveled for me, but it would be nice if other attack tier items worked... It's other starts worked so I believe it's only that one which bugs on archers.
 I just noticed the difference now, but I think it's the same bug that prevents archers from shooting from horses! the inversion left/right click might be involved in that other bug.

the attack tier works on all items, its just harder to notice it on archer as you don't swing your weapon. it does effect the spell damage tho.

**Comment by Lulink13** [comment]
Actually, no class should be able to shoot/swing on horses. The wiki is just outdated.

**Comment by DarkDemonDragon** [comment]
Warrior used to be able to attack with Melee hits from the horse but that was fixed with the Gavel Update

**Comment by Moe-Ronickah** [comment]
I have two classes who have both completed the Mummy's Wrath within the past 7 days.  One has a Tier 1 and one has a Tier 2 Mummy's Rag.  Both work as expected.

It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
