### ISSUE TITLE
Blackwool-jail

### ISSUE THREAD

**Issue by LittleDirtyMinecraft** [Wynncraft/Issues#4720]
I'm stuck in a "Blackwool-jail". I'm not sure if this is a buck but I just cant get out there

**Comment by LittleDirtyMinecraft** [comment]
should i just warp to a City?

**Comment by DarkDemonDragon** [comment]
If you are stuck anywhere do /kill if you have 3 or more Soul Points. Be careful as if you have 2 or less soul points you will drop all items upon death. If this solved your issue please close this.

**Comment by DarkDemonDragon** [comment]
You can also use a scroll if you have one.
