### ISSUE TITLE
Stuck as Alex, and can't see my friend

### ISSUE THREAD

**Issue by Grievous07** [Wynncraft/Issues#4721]
I've tried both 1.8.8 and 1.9 as well as multiple servers, so why am I stuck as Alex when I have a skin. And when in the server's Lobby I have the skin I choose. Also whenever I join a server like #10 for example, and my friend I am trying to do the YT series with gets on the same server I can't see him, or he can't see me?

**Comment by Odnod** [comment]
Just unequip and reequip a piece of armor. Or, if you aren't wearing armor just put a piece on.

**Comment by Moe-Ronickah** [comment]
@Grievous07 , if this is fixed or not, either way, please let us know.  If it's fixed, please close the issue.

**Comment by Grievous07** [comment]
Ya it worked
