### ISSUE TITLE
Tower of ascension

### ISSUE THREAD

**Issue by VraelDragonRider** [Wynncraft/Issues#4723]
So I started this quest and managed to beat the first floor. I had all the shards required (x10) and the Boss shard, but Ive not been able to talk to Ankou. I thought I forgot something, so I through the stuff away and did it again. Still cant talk to him. Please help
(sorry for my bad english)

**Comment by Trixter313** [comment]
Could you post a screenshot of your quest book? Thanks!

**Comment by TursedTomb** [comment]
Go just to next floor. You can only talk to him at start and end of quest.

**Comment by TrashcanMan** [comment]
As @TursedTomb said, Ankou is only for the start and end of the quest. When you've beaten floor one, you should be able to enter the portal to floor two.
