### ISSUE TITLE
Not Collecting 52k XP - Level 53

### ISSUE THREAD

**Issue by BelongoTheBelog** [Wynncraft/Issues#4725]
# Delete this line if you've searched for a duplicate issue first
I completed both quests, Master Piece, and Death Whistle, yet I did not collect ANY exp, but I did collect the items! You can tell because you can only get the quests at level 53 and im barely level 53

**Comment by BelongoTheBelog** [comment]
https://gyazo.com/73f94670f3fe718683612a7170a94622
https://gyazo.com/2147397233556e0afe89e522d94b9412
https://gyazo.com/c3ae11af8f9a9bb261e27e82ef97b60f

**Comment by TheDollarBill** [comment]
Did you accidentally leave your /guild xp at 100?

**Comment by BelongoTheBelog** [comment]
unfortunately, yet, SORRY!, you can close it now ;-;

**Comment by TrashcanMan** [comment]
You can close this issue yourself by clicking the "Comment and close" button.
