### ISSUE TITLE
Dragon Skin armour is the old type of armour.

### ISSUE THREAD

**Issue by Rubzz** [Wynncraft/Issues#4726]
My dragonskin armour is still the kind of armour we had before the gavel update.
![2016-04-01_22 39 22](https://cloud.githubusercontent.com/assets/18220242/14219469/b341acce-f85a-11e5-99c3-3addea644c76.png)

**Comment by Trixter313** [comment]
This issue has been marked as fixed because this doesn't happens to new items and only occurred when the update initially happened. You can keep or throw out the item but other than that that's all.
