### ISSUE TITLE
ID's are too long

### ISSUE THREAD

**Issue by FightingPlays** [Wynncraft/Issues#4729]
Hello,
I have indentified a legendary bow and rare chainmail boots.
But the ID Section is so long that I can't see the name and Damage/Heart section.
Items founded in Ligh Forest and identiefied in Cinfras and LLevigar.

Pictures :
Taken from the items in my hotbar
https://gyazo.com/8d25920cdbf99bb1c0d07b11c87c0393
https://gyazo.com/0a1e8ff0d583807788058c9c4f954ef7

**Comment by TursedTomb** [comment]
At video settings you can change your GUI scale.

**Comment by Moe-Ronickah** [comment]
http://minecraft.gamepedia.com/Options
MC: Options => Video Settings => GUI Scale
Not a WynnCraft issue.
