### ISSUE TITLE
Can't complete craftmas chaos

### ISSUE THREAD

**Issue by Glenncrafter** [Wynncraft/Issues#4730]
I did craftmas chaos (the quest) with my archer, assassin and mage. I already completed it with my archer and assassin, but for a reason I can't complete it with my mage.
When I try to talk with santa on candycane island he doesn't talk ?!?
I did everything till there, my questbook even says: "Return to the present and repost back to Santa".
Is there anything I can do to fix this ?
Or could anyone plz help me ?

Thx for reading :)

**Comment by DarkDemonDragon** [comment]
Please provide screenshots of the Quest Book and you talking to the NPC.

**Comment by Odnod** [comment]
Did you die anytime while in the quest?

**Comment by Verret001** [comment]
No reply in more than two days; If this issue persists repost with a link to this thread.
