### ISSUE TITLE
Glitching through the world

### ISSUE THREAD

**Issue by LilyTigre** [Wynncraft/Issues#4731]
I keep spawning in the ground and falling into the void i have tried many thing to fix such issue but i can't seem to get out of it. I can move around in the Nether PvP area but i not in the main server.

My IGN is: tigrelily

**Comment by superstar947** [comment]
same

**Comment by TrashcanMan** [comment]
Apparently reinstalling Minecraft will fix this, try that.

**Comment by Moe-Ronickah** [comment]
@LilyTigre , let us know if TrashcanMan's suggestion works or doesn't work, please.
