### ISSUE TITLE
Can't get Depressing Weapons after hours of farming.

### ISSUE THREAD

**Issue by GamePixle** [Wynncraft/Issues#4732]
I am a level 45 assassin doing the Bob's lost Soul quest. So far I've bought the shears and stick, and picked up the bow that someone threw away, and I've been farming for 3 hours trying to get the depressing spear. I have been farming in the Katoa Ranch, Detlas Sheep Pen and Emerald Trail. After three hour I haven't even gotten one depressing item. I have also have no loot bonus armour on, and I am not using loot bonus weapons. I've heard of several farming spots where people could get depressing items in 3 - 4 minutes. However they've said the spot became useless after the Gavel update. Is there any way for me to get the depressing spear? 

P.S. I've also been trying to trade someone for it for over an hour, nobody has had it.

**Comment by DarkDemonDragon** [comment]
The way item drops work is that the closer you are to the level then the higher chance you'll have of obtaining it. It's recommended you grind with a lower leveled class on Emerald Trail or search on the forums to buy one.

**Comment by GamePixle** [comment]
That seems a little bad considering the fact that not everyone will have an extra class spot open... But I did manage to trade someone for a depressing spear, so I'm good now. Although, It would be nice if loot was based off of just the mob's level and not the mob and player's level.

**Comment by DarkDemonDragon** [comment]
Unfortunately there's nothing we can do about that here. If your issue is now resolved please close this.
