### ISSUE TITLE
Typing mistake #3

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#4733]
During the House of Twain quest the guy called Twendle asks for "[1 Twain's Journal]". Even though the item you get is called "Twain Journal".

Thanks.

- Nothing.

**Comment by DarkDemonDragon** [comment]
Mind providing screenshots? I finished the quest so I can't confirm this.

**Comment by BasicallyNothing** [comment]
Well... I didn't think of that... And now I'm also done with the quest,  but the vids on yt clearly has that mistake too. Just watch a vid on yt

**Comment by Moe-Ronickah** [comment]
Yes, you get Twain's Journal, as it was owned by Twain, not you.  Yes, it is a Twain Journal.  It's not a typo.
