### ISSUE TITLE
Two "Giruto" in the guild

### ISSUE THREAD

**Issue by Giruto** [Wynncraft/Issues#4736]
**Hello,**

Since I have changed my name on the Mojang's website, my friends see two "Giruto" on the guild panel.
Every message I write appear two times too. Finally, when someone sends me a message through the guild channel, I can read two of them.
My chief has tried to kick me and I have tried to leave (I loose 3SP) but nothing changes. I am still a member of my guild. 
![2016-04-02_18 15 47](https://cloud.githubusercontent.com/assets/18233130/14227481/312b9632-f8ff-11e5-8b70-b322521792ad.png)

I hope you can help me fix this bug.

**Kind regards,
Giruto.**

**Comment by DarkDemonDragon** [comment]
What you need to know about guilds:
1) Changing your username messes things up because it's not supported by the system
2) When doing any guild commands that changes the status of a player you must wait a moment for it to update.

**Comment by Blortias** [comment]
I have a similair Problem im the guild leader and i have two Synchhro's in my guild i cant kick him(dont even remember inviting him) and theres also a person called creativecraft1 who i cant kick
