### ISSUE TITLE
Tattytale Flower

### ISSUE THREAD

**Issue by Kfajver** [Wynncraft/Issues#4738]
Tattytale Flower..... I got this item and then i had to do a restart.... After entering it turned out that this item does not have the npc can't i go a second time to give

**Comment by DarkDemonDragon** [comment]
Please provide more details.

**Comment by Kfajver** [comment]
I was doing a quest called "Rise of the Quarton" ... I started to doit ... After talking with a few npcs got a flower called "Tattytale Flower" .... I had to restart the game because i had low FPS .... It will display when you look at the equipment and do not have the item and nps cant give me the second same item... i don't know what I have to do in such a situation

**Comment by TrashcanMan** [comment]
Try doing /fixquests, it should return any missing quest items. If this resolves your issue, please close it. Thanks, and have a nice day!

**Comment by Kfajver** [comment]
Thank you very much for your help.
