### ISSUE TITLE
Jungle Fever 63 le?

### ISSUE THREAD

**Issue by mortiferum** [Wynncraft/Issues#4740]
So i talked to the almuj banker and then got 64 almuj le so then when im rideing back i find out that i only have 63 almuj le and cant finish the quest... plz could someone help me out by giving me 64 almuj le or reseting my quest.

**Comment by mortiferum** [comment]
oh yea and ./fixquests didnt work as well ;/

**Comment by DarkDemonDragon** [comment]
Here's what to do:
1) Check EVERYWHERE: Bank and ALL Player inventories
2) If you still cannot find the final LE then do this:

INSTRUCTIONS ON HOW TO DELETE QUEST ITEMS (Simple method):
1. Wait for Daily Chest
2. Loot Daily Chest
3. Drag and place Quest Item into Daily Chest
4. Exit out of Daily Chest

After deleting the 63 Almuj LE do /fixquests

**Comment by Moe-Ronickah** [comment]
And don't try to take a Quest LE, it will mess up the quest.
