### ISSUE TITLE
Glitching into the void

### ISSUE THREAD

**Issue by Awesomelily** [Wynncraft/Issues#4742]
When I try to join a server and get to the class selection screen I start to fall into the void and it wont stop. Please help.
IGN: _DrToxic_

**Comment by superstar947** [comment]
that happens to me too we need a staff on

**Comment by Odnod** [comment]
The only way people have managed to fix this in the past has been by uninstalling and reinstalling minecraft. @Awesomelily @superstar947

**Comment by Moe-Ronickah** [comment]
If Odnod's advice works for you, @Awesomelily , please close this issue.

**Comment by superstar947** [comment]
All you have to do is /kill yourself it worked for me

**Comment by Verret001** [comment]
Closed due to inactivity over ten days; and a possible solution was given.
