### ISSUE TITLE
Bug in wall and don't come out

### ISSUE THREAD

**Issue by Blacknick2000** [Wynncraft/Issues#4743]
# Delete this line if you've searched for a duplicate issue first
I slept in a bed and when i stand up im in a hole in the wall. But the problem is i can't teleport me to a city, out of this hole. So i stuck in the wall and don't come out. What can I do? Please Help.

**Comment by TrashcanMan** [comment]
Do /kill with at least 3 soul points. If this resolves your issue, please close it. Thanks, and have a nice day!

**Comment by Moe-Ronickah** [comment]
And don't sleep in a bed again.  The game world clock is not set by the players.
