### ISSUE TITLE
Daily Rewards multiplier stuck at 1 every day.

### ISSUE THREAD

**Issue by SteveNorris** [Wynncraft/Issues#4746]
[found duplicate issue but it was closed without response]

Title. I log in each day, and each day my daily rewards streak multiplier says 1. I've waited 1 day and gotten a couple emeralds, I've waited 5 days and gotten the same amount...

**Comment by Odnod** [comment]
You have to open it each day for it to increase.

**Comment by meatloaf4311** [comment]
I have same issue no matter how persistent, the multiplier never increases

**Comment by SteveNorris** [comment]
Odnod, are you absolutely sure this is the case? Unless they changed it recently, I'm pretty sure it is supposed to go up each day you dog in but don't take it. Could be wrong though.

**Comment by Odnod** [comment]
Nope, you have always had to open it every day to increase the multiplier (max 5)

**Comment by meatloaf4311** [comment]
I have always opened it everyday for a few days, then forget, but my spring break just ended so I was on everyday, grabed it everyday, and the multiplier wouldnt move

**Comment by Moe-Ronickah** [comment]
You must open the chest every day in order for it to increase.  If you miss a day, by the SERVER TIME CLOCK, the chest will reset to "1".  The easiest way to get to the 5 day rewards, and stay there, is to open that chest every day at the same time.

**Comment by SteveNorris** [comment]
Alright, thanks. Do you know at what time the server clock is set to in relation to PST?

**Comment by Moe-Ronickah** [comment]
Unfortunately, I have no idea.  I wish that I did know.
