### ISSUE TITLE
Exclavation site A

### ISSUE THREAD

**Issue by PenguinInSnow** [Wynncraft/Issues#4748]
So I did the quest inside the exclavation site A, now it says I need to go talk to Exclavator Vade and this happens.. [Look Screenshots]

I don't understand why, I didn't threw away any item and I don't really know what to do now..
Would love to get a bit of help if anyone know how to solve this. (Tried to do /fixquests but didn't worked)

![problem 1](https://cloud.githubusercontent.com/assets/18248274/14233896/6f1a022c-f9a3-11e5-9106-2eb792324e64.png)
![problem 2](https://cloud.githubusercontent.com/assets/18248274/14233898/7b1178f8-f9a3-11e5-93c5-ada4086e1beb.png)

**Comment by Odnod** [comment]
You have to bring Vade the yellow crystal that you get from killing the Pharaoh in the temple. If you already have the crystal, run back through the temple anyway as it is possible to miss key spots that update the quest.

**Comment by PenguinInSnow** [comment]
Yeah it didn't really gave me anything when I killed him.. gonna try that. Thanks :p
