### ISSUE TITLE
Broken - /toggle blood

### ISSUE THREAD

**Issue by VeloxisGaming** [Wynncraft/Issues#4753]
I'm not sure if anyone else has encountered this problem, but the /toggle blood command is broken. It works for a while but then reverts back to normal. I've tried to disable particles, but it still did not work. Please fix this :(

**Comment by thecoolkogut4** [comment]
yup its been broken for a while now. i have the same problem.

**Comment by Moe-Ronickah** [comment]
Whatever the problem was, it has since been fixed.  I've been testing every week since this report, and it's been working.  Also, no one else has reported it since this issue.  Have fun playing Wynncraft, and let us know if anything else needs fixing.
