### ISSUE TITLE
Randomly Teleportded

### ISSUE THREAD

**Issue by Draak5** [Wynncraft/Issues#4755]
me and my friend played and in some sort of way he got teleported. we where in the Nemract bank and i needed to eat i did i came back my friend was still in the server just like me he was watching some videos on youtube. everything was fine when i came back from eating i sad to him: I'm back! and then we played agian then for some reason when he left the bank he got teleported a couple times and then he relogged because he thought it was a bug and relogging would fix it. But when he came back on the server; he was on the place where you enter ragni (in the intro part where you enter ragni for the first time) and then we where like NOO it was his level 18 archer class. his minecraft name is: florisbuijnsters
-Draak_5

**Comment by TrashcanMan** [comment]
Just tell him to walk through the tutorial again, he should teleport into the Ragni castle when he gets to the end of the path.

**Comment by majidaq12** [comment]
I was playing as a warrior then i switched to the mage class. when i came back to the warrior class. i found my self in the class selector (the black room) now am stuck. i can't get out. my minecraft name is:MajidAQ12 i am logged in now

**Comment by Moe-Ronickah** [comment]
Did your friend get back into Ragni?  If he did, please this issue.  If he didn't, please let us know what is going on.

**Comment by Verret001** [comment]
No reply in more than two days; If this issue persists repost with a link to this thread.

**Comment by Draak5** [comment]
he was above the barriers... he was stuck

2016-04-09 22:01 GMT+02:00 Verret001 <notifications@github.com>:

**Comment by Trixter313** [comment]
If you're ever stuck, typing /kill with 3+ soul points will respawn you at the nearest visited town.

It appears that this was just a one time issue and it's effects weren't permanent, as long as you can get back to where you were, do everything should be good now.
