### ISSUE TITLE
I can't join a guild even though I was invited

### ISSUE THREAD

**Issue by Arrowhawk5** [Wynncraft/Issues#4757]
I am trying to join a guild and it says in my chat "you have been invited to ___ type /guild join ___ to accept." However when i type that in, it says "You were not invited to ___" please help.

**Comment by Odnod** [comment]
Have them invite you again, this glitch has existed for a while. If it doesn't work a second time just have them continue to invite you.

**Comment by Arrowhawk5** [comment]
i have tried that many... many times

**Comment by Arrowhawk5** [comment]
i will try again i suppose. Thanks for the feedback. If anything else comes up please let me know.

**Comment by Odnod** [comment]
Are you currently in a guild or have you changed your name recently?

**Comment by Arrowhawk5** [comment]
no, neither

**Comment by Odnod** [comment]
Hmm... Guilds are in general very buggy right now. I would just give it some time.

**Comment by Arrowhawk5** [comment]
ok thank you

**Comment by Arrowhawk5** [comment]
i will try what you said about trying again... other friends have joined but had the same problem

**Comment by Odnod** [comment]
I would reccomend keeping this open if you were planning on closing it, as it is a pretty important bug.

**Comment by Arrowhawk5** [comment]
ok

**Comment by Arrowhawk5** [comment]
again thanks for help and if anyone else has something to say please do

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/4245

Please direct any future comments to the original thread. Thanks!
