### ISSUE TITLE
Equipped items lost after switching server

### ISSUE THREAD

**Issue by PandaPeach88** [Wynncraft/Issues#4759]
Hi there,

I was about to fight Corrupted Santa during the questline Craftmas Chaos. I pushed the button to open the door, saw that there were 3 minutes to server reset and figured it would be best to switch to a fresh server.

When I logged in to the new server mere seconds later, I noticed that all of my items had been unequipped. No biggie I thought, as this has happened a few times already during my one week spent here on Wynn. Went to re-equip and... Wait a minute; I'm missing items. My boots (Meanderthal, legendary) had completely vanished (perhaps my inventory was full during the auto-unequip). My chestplate was also affected but strangely enough, it was swapped out for my old chestplate that I was using a few levels ago (NOTE: I honestly have no clue if the chestplate was indeed swapped as Its quite late and I cant remember haha, but the boots are DEFINITELY missing).

My username is PandaPeach88 and this occurred on my warrior account at approximately 2:30am EST. I do not have any screenshots prior to this incident, however I have taken a screenshot of my inventory after this happened, showing only a pair of unidentified, non-legendary boots in my inventory.

Any help would be much appreciated!
![tst](https://cloud.githubusercontent.com/assets/18279793/14273598/d79b1f5c-fad9-11e5-9466-0edcfc4ab22f.jpg)

**Comment by PandaPeach88** [comment]
I'd also like to add that I've just noticed I'm also missing a ring (it was my only accessory). I don't recall what its name or IDs were unfortunately

**Comment by PandaPeach88** [comment]
Update: found the logs;

[02:35:23] [Client thread/INFO]: [CHAT] Loading the WynnPack...
[02:35:23] [Client thread/INFO]: [CHAT] Select a class! Each class is saved individually across all servers, you can come back at any time with /class and select another class!
[02:35:23] [Client thread/INFO]: [CHAT] Thank you for using the WynnPack. Enjoy the game!
[02:35:28] [Client thread/INFO]: [CHAT] Little Inferno requires your defense skill to be at least 15.
[02:35:28] [Client thread/INFO]: [CHAT] Bronze-Plated Greaves requires your strength skill to be at least 5.
[02:35:28] [Client thread/INFO]: [CHAT] Meanderthal requires your strength skill to be at least 12.
[02:35:28] [Client thread/INFO]: [CHAT] Juniper requires your strength skill to be at least 8.

Looks like the ring was Juniper, hah. Guess my plate was untouched then. I hate this glitch!

**Comment by BlueThunder25** [comment]
HI @PandaPeach88,

This is a common glitch that has happened to me many times before. To fix it log off of Wynn craft to the mine craft home page then rejoin wynncraft and choose a different server.

Hope This Helps,
BlueThunder25

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refunds policy so there's nothing we can do about the already lost items. To prevent it from happening again until the issue is fixed, please try to keep your inventory not too full.

There is already an open issue for this, located here https://github.com/Wynncraft/Issues/issues/4120 so please follow that one for updates on the status of the issue and direct any future comments to the original thread. Thanks!
