### ISSUE TITLE
My exp bar is broken I've done 5 quests but the green bar doesnt go up once 

### ISSUE THREAD

**Issue by InnocentChicken** [Wynncraft/Issues#4760]
![screenshot_20160405191914](https://cloud.githubusercontent.com/assets/18280599/14274256/596a0ffe-fb64-11e5-8cca-19c8c33c2c1c.png)

I have talked to Shtafjord

**Comment by InnocentChicken** [comment]
Plz fix this cause I want to beat my friend by level's

**Comment by InnocentChicken** [comment]
I didn't use optifine or any mods. I was using it before and thought it was a glitch so I used a non optifine and just used regular 1.8.9
( sorry for my bad english)

**Comment by Odnod** [comment]
Is your guild XP set to 100?

**Comment by InnocentChicken** [comment]
I don't know 
:'( noooo

**Comment by InnocentChicken** [comment]
how do I check?

**Comment by InnocentChicken** [comment]
You are smart

**Comment by InnocentChicken** [comment]
Thank you so much

**Comment by InnocentChicken** [comment]
Odnod
