### ISSUE TITLE
Quest Items missing

### ISSUE THREAD

**Issue by SlimeTehFire** [Wynncraft/Issues#4761]
#
 My IGN is SlimeTheFireX and Im stuck in the quest called Iron Heart II... I have done the first part but I have NO IDEA where the factory helmet is. I been trying to look in my other classes but I cant find the factory helmet... Help?

**Comment by HajriWynn** [comment]
did you try /fix quest ?

**Comment by TrashcanMan** [comment]
@HajriWynn Isn't it /fixquests?

**Comment by Verret001** [comment]
No reply in more than two days; If this issue persists repost with a link to this thread.

**Comment by SlimeTehFire** [comment]
Oh ty I finally can do this quest
