### ISSUE TITLE
Memory Paranoia - Server restart while "animation"

### ISSUE THREAD

**Issue by Nilsteichert** [Wynncraft/Issues#4763]
Hi
I was doing the quest Memory Paranoia and while an animation got showed (the one in the masters bedroom) the server restarted, and the animation was frozen as soon i rejoined.
Im NOT able to do the quest now because after some time i killed myself to not be stuck anymore.
Im in the start room now (all doors closed) and not able to join the masters bedroom. 
I dunno if thats a big bug, because its a very low chance that this happens again.
My ign is EnterTheJourney and if you could somehow help me (maybe tp in that room) complete the quest i would be pretty happy.
I put some screenshots too ^^
![2016-04-07 00_08_56-minecraft 1 8 9](https://cloud.githubusercontent.com/assets/12115140/14334486/fae65784-fc54-11e5-987b-949d4ed0c764.png)
![2016-04-07 00_09_11-minecraft 1 8 9](https://cloud.githubusercontent.com/assets/12115140/14334487/fae965dc-fc54-11e5-837b-39a9312ceded.png)

**Comment by Odnod** [comment]
Run back through the quest as you did before, the quest uses multiple versions of the mansion to accomplish its affect and the one you initially enter is not the one you need to be in.

Just try to remember the steps you went through or rather use the wiki https://wiki.wynncraft.com/index.php?title=Memory_Paranoia to assist you.

**Comment by Verret001** [comment]
Closed due to inactivity over ten days; and a possible solution was given.
