### ISSUE TITLE
Underwater quest not advancing

### ISSUE THREAD

**Issue by mattylvke** [Wynncraft/Issues#4765]
The quest requires 3 Pigman's Meat and 1 Water Bottle, i have both but the Quest NPC keeps saying he needs them items even though they are in my inventory. 
this is the error message, and you can see the two items needed in my hotbar.
![2016-04-07_21 21 44](https://cloud.githubusercontent.com/assets/18336614/14365712/0e07219c-fd07-11e5-86c5-813a9b5fb5e4.png)

**Comment by Trixter313** [comment]
When did you get the items? And where from? If you've had them for a while, try getting new ones and make sure you get the meat from the pigman in the pigman ravines.

Did this help anything? Thanks!

**Comment by Odnod** [comment]
In addition to what trixter said, try checking your quest book to see if you accidentally skipped something.

**Comment by Verret001** [comment]
Closed due to inactivity over ten days; and a possible solution was given.
