### ISSUE TITLE
getting kicked when i try to get on my horse

### ISSUE THREAD

**Issue by tilly38** [Wynncraft/Issues#4766]
Whenever i try to get on my horse i get kicked from the game. The message says "Internal Exception: io.netty.handler.codec.DecoderException: IntArray with size 1 is bigger than allowed 0

**Comment by Trixter313** [comment]
What version of MC are you using? If you're using 1.9, we suggest you downgrade to 1.8.9 until the staff have time to fix the many issues with 1.9 clients. Let me know if this helps at all. Thanks!
