### ISSUE TITLE
Horse Glitching

### ISSUE THREAD

**Issue by iruleyousuck** [Wynncraft/Issues#4768]
# Delete this line if you've searched for a duplicate issue first
when I spawn in my horse it instantly  disappears with like 1 or 2  frames to right click, and it happens with all my horses.

**Comment by Trixter313** [comment]
What version of Minecraft are you using? If it's 1.9, please try downgrading to 1.8.9 until the staff have time to fix the issues with 1.9 clients.

Does this help at all? Thanks!

**Comment by iruleyousuck** [comment]
It works! thanks

**Comment by Trixter313** [comment]
Glad to hear. Hopefully all of the 1.9 issues get fixed soon.

**Comment by iruleyousuck** [comment]
yea
