### ISSUE TITLE
Horse disappeared while Headless Hunt

### ISSUE THREAD

**Issue by Sono96** [Wynncraft/Issues#4769]
Hello,
I was killed during the quest Headless Hunt (lvl64) and i had full Soul Points!
After i was killed i was respawned in Gelibord and my black horse (20/20) wasn't in my inventory anymore.

Hope the bug will be solved
_Sono

**Comment by Odnod** [comment]
You must have dropped it, as there is not really any other reason why this would happen as far as I know.

**Comment by Sono96** [comment]
I have not...
I searched for it on the place i died and on the place i respawned!
My fingers were not even in the near of Q.

_Sono

**Comment by Trixter313** [comment]
Well there is currently a bug where items despawn immediately after you leave the area/die so if you did accidentally drop it and then die, there's no way to know for sure. It's very easy to press wrong keys, especially when you believe you're about to die, so really it does appear that you just dropped it on accident.

If you have any other questions or comments, feel free to comment back. Thanks!
