### ISSUE TITLE
Items not updating

### ISSUE THREAD

**Issue by FaithofTheWorld** [Wynncraft/Issues#4770]
# Delete this line if you've searched for a duplicate issue first
When wynncraft updated, all of my item updated too ,but my spear can someone plz tell me how to fix it.

**Comment by TrashcanMan** [comment]
Which spear is it? If it's got accented characters in its name, it's one of the glitchy broken ones. Hang on to it for now until the devs release a fix.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3161

Please direct any future comments to the original thread & fully read it. Thanks!
