### ISSUE TITLE
the pack

### ISSUE THREAD

**Issue by milbrandtt** [Wynncraft/Issues#4773]
It said i was downloading the custom resource pack. then it kicked me and now i dont have the pack and it looks like trash

**Comment by PenguinInSnow** [comment]
Hello, All you got to do to fix the problem is go on your server list, Click on Edit and then click on *Server Ressource Packs* to make it Enabled and then when you'll log onto one of the multiple servers, the texture pack should be present. Hope it helped :)

**Comment by milbrandtt** [comment]
I just tried that and it does the "do you want to download and automagically install it" and clicked yes but it still doesn't work..

**Comment by Trixter313** [comment]
Try closing Minecraft, [going to your .minecraft folder](http://minecraft.gamepedia.com/.minecraft) and deleting anything in the server-resource-packs folder, then restarting Minecraft and attempt to login again.

Also, what version of Minecraft are you using to login?

Thanks!

**Comment by Verret001** [comment]
Closed due to inactivity over ten days
