### ISSUE TITLE
Hollow trees that should be filled

### ISSUE THREAD

**Issue by benberinoLP** [Wynncraft/Issues#4776]
there are several trees where a mage can get stuck in after teleporting below it's leaves without being able to use scrolls or there skills to get out. In one tree at X:198 Y:28 Z:-2199 there are already 2 people stuck by the name COSMO_DW and albinGA41. COSMO already got free after we had to lead a slidding gravel mod to him so he would be killed and teleported somewhere else but albin is still stuck, could this be fixed in any way?

**Comment by Odnod** [comment]
Type /kill to escape situations like that.

**Comment by Trixter313** [comment]
I think it would be helpful if someone on build or whoever has access filled these trees so no one else can get stuck, so I'll leave this open.

**Comment by Trixter313** [comment]
Were you stuck in the trunk of the tree, or the leaves?

**Comment by benberinoLP** [comment]
they were stuck in the leaves that were one block above the ground

**Comment by Trixter313** [comment]
Ah, that could be fixed by moving the leaves up by one then.

**Comment by YunoFGasai** [comment]
I'm currently forum banned but you can post it on my "fillimg holes" thread.

**Comment by Moe-Ronickah** [comment]
Fixed on the build server.
