### ISSUE TITLE
mission: Pit of the Dead  weird invisible structure/semi)wall

### ISSUE THREAD

**Issue by benberinoLP** [Wynncraft/Issues#4777]
# Delete this line if you've searched for a duplicate issue first

**Comment by Odnod** [comment]
Please elaborate as to give us a better understanding of the issue at hand.

**Comment by benberinoLP** [comment]
in the hole itself, on the bridge in the 1st section above the blackness there is a invisible wall but a couple of blocks before that, there is a 2 block wide and 5+ blocks tall in the middle of the bridge that is kinda confusing

**Comment by Trixter313** [comment]
Ah, the wall is there to stop you from being able to go forward. To continue the quest, you have to jump down off of the bridge.

Does this solve all confusion? Thanks!

**Comment by benberinoLP** [comment]
I understand that but before that wall there a strange little wall whare yu're able to walk around and jump on but is also invisible. It's trivial matter but it's strange that it's there :/

**Comment by Turmfalke2** [comment]
hi, I would like to reopen this issue, I just spent like 10 minutes stuck between these invisible walls. It is not exactly intuitive that you are supposed to jump off the bridge. Nothing hints that it is necessary or even remotely a good idea.
