### ISSUE TITLE
Stuck in a roof as Mage-Ign Loliger3000

### ISSUE THREAD

**Issue by Loliger3000** [Wynncraft/Issues#4779]
# Delete this line if you've searched for a duplicate issue first

Please teleport me out of this roof, i even cant use teleportion Scrolls.
 Ign: Loliger3000

**Comment by Loliger3000** [comment]
Killed myself, Nice lost 2 Soul Points. Great beginning

**Comment by Trixter313** [comment]
Glad to hear you're out =)
