### ISSUE TITLE
Rise of Quartron Bug?

### ISSUE THREAD

**Issue by Cheetqh** [Wynncraft/Issues#4780]
# Delete this line if you've searched for a duplicate issue first

![2016-04-07_17 19 11](https://cloud.githubusercontent.com/assets/17261057/14405021/a18d81ee-fe52-11e5-970c-2241abd291a7.png)
![2016-04-07_17 19 05](https://cloud.githubusercontent.com/assets/17261057/14405022/a7568f8a-fe52-11e5-92f5-b3bf2396d882.png)

So ive been trying to give Nasea the contract and it wont accept it and tells me "come back when you have a solid lead on the missing quartz"

**Comment by Trixter313** [comment]
Could you post a screenshot of what it says in your quest book? Thank you!

**Comment by Cheetqh** [comment]
![2016-04-09_13 10 55](https://cloud.githubusercontent.com/assets/17261057/14405089/93d5c9d8-fe54-11e5-90f8-0e42c2689ee8.png)

**Comment by Cheetqh** [comment]
@Trixter313

**Comment by Trixter313** [comment]
I've never done this quest so sorry if I mess something up.

So do you get the contract from the mansion in the hidden bandits village?
If so, try revisiting the village. It appears that you missed a checkpoint there that you need to continue the quest.

**Comment by Cheetqh** [comment]
@Trixter313 I havent even gone to the bandits village, i looked up the quest and saw the message its suppose to say but it wont say anything. So should i just try going to the village?

**Comment by Trixter313** [comment]
Ah, yes, I believe so. That's probably what's missing. When you get to the right place, it will probably say something in chat like your quest book has been updated. That's how you know you can continue and check your quest book for the next steps. Let me know if you can get it to work. Thanks!

**Comment by Cheetqh** [comment]
@Trixter313 It worked! almost done with the quest.

**Comment by Trixter313** [comment]
Glad to hear! =)
