### ISSUE TITLE
Qira Hive Bug

### ISSUE THREAD

**Issue by JediArcanaan** [Wynncraft/Issues#4782]
In the Earth division on floor nine of the Qira Hive, the mobs stopped spawning when I only had four tokens. I waited for about ten minutes for another mob to spawn before I killing myself. Please fix, thanks.

**Comment by Trixter313** [comment]
Does switching to another world fix your issue?

**Comment by shinyafro** [comment]
I had an issue like this and /class worked.

**Comment by JediArcanaan** [comment]
Oh okay. Thanks guys! All sorted out now!
