### ISSUE TITLE
Nether exit loop

### ISSUE THREAD

**Issue by shinyafro** [Wynncraft/Issues#4784]
So, when entering the nether portal from an actual server, you are teleported into the nether, but when you go back you to the lobby and connect, you will be teleported back inside the nether portal, where you will then be teleported back to the nether. You can escape if you are VERY FAST and understand whats going on but otherwise you are pretty much stuck in an endless loop. I managed to /class, change to another class then log in, /class back and managed to get out like that as it seems to load faster then using /class as the server texture pack loading no longer prevents movement.

**Comment by meatloaf4311** [comment]
Some one said to try toggling internet off before i get tp, move away, turn it back on. I'll try this and that, then report back if it works.

**Comment by shinyafro** [comment]
I ended up writing down in the op how i solved mine, literally was pretty fast, dxp got released with patch then i logged in and was magnetically flung into the nether portal before realizing my mistake and managed to get out in like 5 minutes.

**Comment by meatloaf4311** [comment]
https://forums.wynncraft.com/threads/stuck-in-nether.121331/#post-1339136

Forum post about it with more possible solutions, still haven't tried any.

**Comment by Moe-Ronickah** [comment]
Slated to be fixed in the next patch.  I'll assume that it's not here, anymore, unless someone says otherwise, and we have to re-open this issue.
