### ISSUE TITLE
Rymek isn't considered a town, so it's not a spawnpoint.

### ISSUE THREAD

**Issue by RedMorcus** [Wynncraft/Issues#4787]
# Delete this line if you've searched for a duplicate issue first
As the title says, Rymek isn't a spawnpoint, so dying in the mesa area spawns you in Tenarves. This can be quite annoying when doing the canyon condor quest.

**Comment by TrashcanMan** [comment]
Odd, I could have sworn that Rymek was a spawn point back when I used to play... It might just be that you're closer to Ternaves than to Rymek, since part of the Canyon Condor quest does take place right at the edge of the mesa area.

**Comment by RedMorcus** [comment]
I just died **in **rymek** and respawned in Tenerves, can't say what killed me though.

**Comment by Odnod** [comment]
They removed Rymek as a spawn point because you would always respawn there after dying in places like Bob's reincarnation fight.

At least I'm pretty sure that's what happened.

**Comment by YunoFGasai** [comment]
@AckroWynn can you confirm if its intentional or not and if it is close this issue?

**Comment by Odnod** [comment]
Well according to the wiki, Rymek was removed as a spawn point almost 2 years back shortly after the 'mob update' in August 2014
