### ISSUE TITLE
texturepack

### ISSUE THREAD

**Issue by barbi13245** [Wynncraft/Issues#4792]
once between the server and put no to the installation of texture pack and now when I want to go I appear to fall, and hope nothing happens. help!!!!

**Comment by xXthunder369Xx** [comment]
You have to accept the texture pack in order to play the game.

**Comment by barbi13245** [comment]
yes! But I didn`t know and now I want to play and i can not :C

**Comment by Trixter313** [comment]
Don't worry, just go to your servers list, select Wynncraft, click edit, and then set server resource packs to enabled. That should fix it =)
