### ISSUE TITLE
Can't complete WynnExcavation Site C

### ISSUE THREAD

**Issue by SnowyAE** [Wynncraft/Issues#4795]
I'm on the last part of WynnExcavation Site C where I'm supposed to return to Excavator Placardus, but when i talk to him it says "The Purple Shard from WynnExcavation Site B is required to start this quest." even though i already did all of the quest except for the last part. Even if I have the Purple Crystal Shard in my inventory it says the same thing.

**Comment by Trixter313** [comment]
Try typing /fixquests, it might give you an item you need.

**Comment by SnowyAE** [comment]
It still doesn't work I'm still getting the "The Purple Shard from WynnExcavation Site B is required to start this quest."

**Comment by Odnod** [comment]
You need the quest item optained from finishing site b, not the untradable one you get in the room with the crystal.

**Comment by Trixter313** [comment]
I don't think that's the issue because they said they have already started part C, and are ready to finish, but it's asking them what it should have asked at the beginning of part C.

**Comment by Odnod** [comment]
Oh I see, sorry for the confusion. Try running back through the whole cave (make sure to pick up the crystal if you haven't) because you can sometimes skip over key regions that are supposed to progress the quest.

**Comment by KrabTheScrab** [comment]
mybe  you also need the shard from site A but it just doesnt say it?

**Comment by SnowyAE** [comment]
I've run through the entire cave multiple times, and have tried talking to Excavator Placardus with shards A and B in my inventory he still says that I need shard B to start the quest even though I've already done all of it except for the last part where I have to return to him.

**Comment by Odnod** [comment]
@SnowyAE do you have the site C crystal from the end of the cave?
