### ISSUE TITLE
Cant finish Qira Hive

### ISSUE THREAD

**Issue by Endeh** [Wynncraft/Issues#4797]
So I have the rainbow block (Master Catalyst) item to finish the quest, and im right-clicking the npc like crazy, but im getting no dialogue

**Comment by Odnod** [comment]
Check your quest book, then if that doesn't help, quickly run through each floor to make sure you didn't miss a region to update the quest.

**Comment by Endeh** [comment]
@Odnod Oh yes, when fighting qira, i got the item then died, i didnt exit, thanks!
