### ISSUE TITLE
Mana bug

### ISSUE THREAD

**Issue by PikaLord** [Wynncraft/Issues#4799]
Im playing at wynncraft at my best character and the day this is wrotten in thats the day i just dident have any mana at all, and i arent comming back.¨
Please help me, i realy need my mana.
Minecraft username: PikaLord2
Thanks for reading :)

**Comment by Trixter313** [comment]
Try typing /class
Does this fix it?

**Comment by PikaLord** [comment]
Yeah thanks

**Comment by Trixter313** [comment]
Glad to hear!

**Comment by PikaLord** [comment]
Got another question?
Can you or someone else try to fix it so it dosent happen agian?

**Comment by Trixter313** [comment]
It's something that's been happening for a really long time and the staff know about it but they either haven't had the time to fix it or, most likely, can't figure out how to fix it. Luckily, the fix is pretty simple and painless though. All we can do is hope it gets fixed soon. =)
