### ISSUE TITLE
Archers can't attack on horse?

### ISSUE THREAD

**Issue by Lulink13** [Wynncraft/Issues#4800]
According to the wiki, EVERY class is supposed to be able to attack while on a horse. That would make sense right? However, I think archer is the only class not to be able to do so... That's a real handicap. Can you fix that? I think it comes from the reversed mouse controls (L<=>R)...

**Comment by Lulink13** [comment]
I just tested, and now it seems that my mage isn't able to attack on horses too... is it normal? is it just that the wiki is wrong?

**Comment by Trixter313** [comment]
No classes can attack on horse, the wiki is just outdated. You can edit it if you want or post the link here and I can. Thanks!
