### ISSUE TITLE
Resource Pack not Working

### ISSUE THREAD

**Issue by BlahBlah161616** [Wynncraft/Issues#4801]
As many forumers know, my resource pack hasn't worked in 2 months...I've tried everything I've been given, delete .minecraft, delete legacy, readd the server as enabled resource packs, which it already had, and other random stuff...the issue with this is, it works on every other server, I don't know what's between this rp and my Mac, but it won't work.

**Comment by Odnod** [comment]
The resource pack is known to sometimes not work on Mac, perhaps it has to do with the os version?

**Comment by BlahBlah161616** [comment]
Then maybe they should be fixing that because that's a bug

**Comment by Odnod** [comment]
I think I have said this before, but I can send you a copy of the resource pack to use independently from the server, it would not fix the issue of it not downloading but it would allow you to play again.

**Comment by BlahBlah161616** [comment]
You have said that before, I believe they should fix it to help other Mac users play the game too.

**Comment by Trixter313** [comment]
What version of OSX are you using?

**Comment by BlahBlah161616** [comment]
I'll find out.

**Comment by Moe-Ronickah** [comment]
The resource pack is now available on the Issues page of this GitHub.
