### ISSUE TITLE
Stuck in lion tamer cavern

### ISSUE THREAD

**Issue by CreeperGuy7777** [Wynncraft/Issues#4802]
# Delete this line if you've searched for a duplicate issue first
I am a Mage, level 32. I have many things, including a legendary wand, Daltas' Legacy. I thought you needed to teleport here, but I was wrong, teleported into a area where there is light... My coordinates are, X: 880.300 Y: 35 Z: -2326.700. I do not remember what server I joined. I cannot teleport out, and want to know how to escape. There is no monsters near me. Please help me! I love this account, spent so much time on it! I am so sad that I am stuck ;-; I need help.

**Comment by CreeperGuy7777** [comment]
Nevermind! Someone told me that you can do /kill on the game :/ I feel like a noob

**Comment by AThao1** [comment]
Close this issue if it's resolved.
