### ISSUE TITLE
Quest Items Removed

### ISSUE THREAD

**Issue by Badqex** [Wynncraft/Issues#4803]
Hello,

I have recently reached level 68 (as warrior) on your server and have been recently trying to complete the quest 'The Temple Of Legends'. Although, many of my quest items have disappeared from my bank over the time I have quit (1 year). I have been forced to complete several quests on other classes but I don't want to prevent one class from being maxed. I'm not sure if this is a glitch although I can prove that I have completed many quests but not received items from them. 

Kind Regards,
Badqex.

**Comment by Verret001** [comment]
If you do /fixquests that should fix your problems
