### ISSUE TITLE
Liquified Emeralds Lost

### ISSUE THREAD

**Issue by QuantumMaster333** [Wynncraft/Issues#4804]
I had just logged on after the big Gavel update (I hadn't played for several months) just to see what it had changed, and I noticed a few things:
           -All weapons and armor were now unidentified (don't know if this was intentional or not)
           -when I was grabbing the 13 Liquefied emeralds I had saved up to go and identify all my items, I pressed Shift + Left Click to move the money into my character's inventory, not noticing that I did not have a space open, it is all gone and I have checked all my characters and cannot find anything

Is there anyway that this can be remedied? It was a lot of money and I can't use most of my items due to them being unidentified.

**Comment by thecoolkogut4** [comment]
weapons and armour are meant to be unid'ed(to update to the new system)
and there is a strict no refund policy. lots of people have lost stuff due to the update.
for the part where you cant use your items, maybe ask someone to lend you some emeralds to help you ID your items.
