### ISSUE TITLE
Lost all my items when I spawned

### ISSUE THREAD

**Issue by Pearinatorz** [Wynncraft/Issues#4807]
I lost all my stuff when I spawned... I changed servers and nothing happened? I didn't die and I still had 5 SP when I  spawned. # #_**WHAT**_
The stuff I had:
Relic Bow
Peiler
Giant's Bracer
Winter's Essence
Cerid's Ingenuity
Decoder Ring x2
Tree Bracelet
17 LE and 45 EB
White Horse
I didn't lie, I really lost all and I spawned without the oak bow

**Comment by Trixter313** [comment]
The scenario you described sounds exactly as if someone was logged in as you and died multiple times, making me think that maybe your account was hacked? Or a friend/family member could have done it. Anyone with access to a computer you've logged into Minecraft on or your login credentials. I'd suggest changing the password to your Minecraft and the associated email to be safe.

Other than that, unless you can explain it in a different way, there's really not anything we can do.

**Comment by Pearinatorz** [comment]
Fine... I might as well quit...

**Comment by Trixter313** [comment]
I'm very sorry about this loss but if anything else comes up about it I will make sure to update you with new information.
