### ISSUE TITLE
Stuck in the void.

### ISSUE THREAD

**Issue by MalyTheKing** [Wynncraft/Issues#4808]
Hello,
my friend (IGN: "Methoribus") just joined the server for the first time. Now he is stuck in the void and is constantly falling before he could even choose a class. If he wants to type in /class, it says: "You can't use commands right now." We tried to switch servers but he can't get out of there.

**Comment by Trixter313** [comment]
Then them to go to their servers list, select Wynncraft, click edit, then change Server Resource packs to enabled. That might be the issue. =)

**Comment by Trixter313** [comment]
Let me know what happens after you try that, please. Thanks!

**Comment by Odnod** [comment]
This glitch has sometimes been fixed in the past by uninstalling and reinstalling mc, so I think that is his best bet.
