### ISSUE TITLE
Horse glitch

### ISSUE THREAD

**Issue by WolfySnap** [Wynncraft/Issues#4809]
So, when I was just out riding, trying to complete some quests, I start to get hurt. And I were nowhere near any hostile mobs, so I just keep on riding. I'm almost dead, so I get off my horse. And I end up like **200 blocks** away from where I were. So I try again, and just as i thought, the horse is glitching. It appears that when riding, I glitch back about **25 blocks** every time I **dismount**. And when I'm in the grand canyon, on the upper part, I sometimes glitch down. This is very annoying, and I can't play Wynncraft anymore.

**Comment by Trixter313** [comment]
This happens to people using 1.9, is that what you're using? We reccomend using 1.8.9 until the issues with 1.9 are fixed. Let me know if this fixes your issue. Thanks!

**Comment by WolfySnap** [comment]
I have tried playing 1.8.9, but the grass blocks are glitched blocks. Soooo
that's not an option. But thank you for trying to help me :D

2016-04-12 18:05 GMT+02:00 Nick Cipriani <notifications@github.com>:

**Comment by Trixter313** [comment]
Grass has the missing texture in 1.8.9 for you? Weird, all the reports so far were of that issue happening for people using 1.9. Maybe the staff fixed it for 1.9 and sacrificed the working 1.8.9 one.

**Comment by WolfySnap** [comment]
Yea, and when I'm playing on mineplex in 1.9, the glass panes have a
glitched block rim. Very weird.

2016-04-12 21:48 GMT+02:00 Nick Cipriani <notifications@github.com>:

**Comment by Andy0132** [comment]
In 1.9, not only will horses glitch out, they may not spawn. To spawn them, ensure that you are aiming about five blocks away from you, and that both you and the spawn area are level, and level with one another. Furthermore, in order to solve the horse lag, you can periodically (Every 20-30 blocks or so) quickly dismount and get back on.

There tends to be an instant, and very slight, stutter from the frames when the horse begins to lag. When such occurs, it is recommended that you dismount and remount.

**Comment by WolfySnap** [comment]
Yeah, I try to get off the horse from time to time, but when I'm in the
canyons my horse will glitch out from the top of the canyons to the bottom,
which is very frustrating.

2016-05-08 0:50 GMT+02:00 Andy0132 <notifications@github.com>:

**Comment by Moe-Ronickah** [comment]
The resource pack has since been updated multiple times.

Wynncraft is not coded for 1.9+.  You use those versions at your own risk, however, there are tips for them in other threads in the GitHub and on the forums.
