### ISSUE TITLE
Relic Glitch

### ISSUE THREAD

**Issue by Spitfire696** [Wynncraft/Issues#4810]
I was trying to get the dagger relic, but when i was "touching it" idk if it was left or right click or stand on it, so i did all of them, but it wasn't dropping me the dagger, i actually did it about 10 minutes before and it worked but it didnt work after that, can u only get it once or something?

**Comment by Trixter313** [comment]
There is a cooldown. You can learn more here https://wiki.wynncraft.com/index.php?title=Relics

**Comment by Felphyre** [comment]
I actually have a question pertaining to this. i have gotten the helmet technically once before (or i wouldve if my inventory didnt fill up on the trash helms in the room.) and after waiting the 8 hours attempted again, and it just refuses to give it to me. is there something i am doing wrong?

**Comment by YunoFGasai** [comment]
@Felphyre try doing it again now
