### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by KawaiiCrafter7** [Wynncraft/Issues#4812]
I was just playing on the new Gavel part and I just logged out with lvl 54 gear and I was lvl 55 ( I didn't have full inv.) and when I rejoined And I lost all my iron armour and I lost 1/4 of my lvl! Help me!

**Comment by Yoavronen** [comment]
Are you sure you lost 1/4th of your level?
Also, when you came back how many soul points did you have? 
Did you lose just your armor or your whole inventory?

**Comment by KawaiiCrafter7** [comment]
15 soul points and I lost 1/4 lvl for some reason!
I also lost my armour just on my Character(Pants and helmet)!

**Comment by KawaiiCrafter7** [comment]
If you trust me or not is a glitch!

**Comment by KawaiiCrafter7** [comment]
I wont pay any more emeralds to get armour and until u fix it I'm not gonna play wynncraft

**Comment by KawaiiCrafter7** [comment]
Its the same thing

**Comment by Verret001** [comment]
Please provide some screenshots, It may help

**Comment by KawaiiCrafter7** [comment]
but I don't have any screen shots of my inv! Will it help if u see a screen shot that my friend took of me?

**Comment by YunoFGasai** [comment]
if he or you have a screenshot of you (or your chat) that your darkwizard was level 55 that will confirm that you lost a level (the api claims your darkwizard is level 54)

**Comment by KawaiiCrafter7** [comment]
well my friend can tell you the same thing but you might think its a lie

**Comment by KawaiiCrafter7** [comment]
i really don't care about that 1/4 lvl but i really need my liquid and gear back

**Comment by KawaiiCrafter7** [comment]
i worked on it for over a year and i payed for vip+ so i guess i deserve my stuff back

**Comment by KawaiiCrafter7** [comment]
i reported several players and helped in many ways

**Comment by Verret001** [comment]
I'm sorry about your loss but as said beforehand Wynncraft has a strict no-refund policy. Back at the gravel update I lost an entire Mage rank. It's not budging.

**Comment by KawaiiCrafter7** [comment]
sorry for that

**Comment by Verret001** [comment]
Its fine, I continued working and got it back to where it was. I think you should do the same.

**Comment by Moe-Ronickah** [comment]
There haven't been any more reports of this as far as I know.  I believe that it may have been a on-time occurrence, and I'm hoping that we never see it again.  @KawaiiCrafter7 , if you have any more problems or issues, please feel welcome to report them to us.
