### ISSUE TITLE
1.9.2 Optifine Horses

### ISSUE THREAD

**Issue by Edywang** [Wynncraft/Issues#4813]
On version 1.9.2, modded with only optifine, horses show up then immediately disappear when I try to spawn them in (I use a chestnut horse).
On version 1.8.9, ", horses show up and work as intended.

**Comment by Trixter313** [comment]
If it only happens with Optifine it's an issue with Optifine, not Wynncraft. I'd suggest reporting it to the Optifine developer and see if they can fix it.

**Comment by Edywang** [comment]
Just tested with vanilla Minecraft and horses still vanish instantly after spawning.

**Comment by Trixter313** [comment]
Okay, right now we are recommending staying in 1.8.9 until the issues with 1.9 are fixed. The house issues are being worked on.
