### ISSUE TITLE
Losing Soul Points leads to loss of items

### ISSUE THREAD

**Issue by IArePolar** [Wynncraft/Issues#4814]
I logged off last night because I had one soul point. No one had got on after me and I logged off in a safe place. My computer has a password that only I know so no one can get on. Now all I have is 5 bows (not mine) that are all level 1, and the 2 untradeable items I got from quests. Other than that I lost all other items.

**Comment by Trixter313** [comment]
This scenario fits your account being hacked perfectly. I'd suggest changing the password to your Minecraft account and the associated email to prevent it from happening again.

Unfortunately there's really nothing that we can do if that is the case and there's no other explanation that fits this that I can think of. Maybe you can think of something else but it appears to be just that from this information.

**Comment by IArePolar** [comment]
I know I wasn't hacked

**Comment by IArePolar** [comment]
Maybe it's a server problem, can you not go back and see what a player had? You responded almost the exact thing you posted here on another problem like mine. Is it likely that two players that posted in the same day both lost their inventory? Sorry to be pushy, but I honestly just want my items back.

**Comment by Trixter313** [comment]
It's almost impossible to know that you haven't been hacked for sure. It's very possible that it's someone specifically targeting Wynn players. These aren't the first reports, they have been popping up every couple weeks or so. Even if we could look at what you had, that wouldn't tell us what happened to the items unfortunately. I'm open to suggestions of what else could have happened but someone killing your player is the only scenario that fits perfectly. You had low soul points & your inventory looks exactly how it would look if you died with less than 2 soul points.

**Comment by IArePolar** [comment]
I logged off when I knew I would die nothing would have killed my character

**Comment by IArePolar** [comment]
I still think it's a problem with the server

**Comment by Trixter313** [comment]
I'll leave the issue open just in case but it seems very unlikely. Especially since there is something that perfectly explains what happened already. If someone hacked your account, it doesn't matter where you logged off because they can move your player.

If it does turn out to be a server issue, unfortunately Wynncraft has a strict no refunds policy so it's not likely you will be able to get the lost items back.

**Comment by IArePolar** [comment]
You can't even check what time my player was on? 
And I was in the exact spot I logged off facing the same direction. Also how do you explain 5 untradable bows in my inventory. I couldn't have got 5, exact same bows, that can't be traded.

**Comment by IArePolar** [comment]
And either way, if it was a server problem then it's their fault my items are gone and they should return it. If it was somehow someone hacking then I agree, don't return the items even though it's still not my fault.

**Comment by Trixter313** [comment]
When you die, you are given an untradable weapon that fits the class you died with. If you die multiple times and keep picking the untradable bows up, you end up with a bunch of them.

That does seem reasonable but it had never happened. No matter the circumstances, Wynncraft has always stuck to the no refunds policy. Whether it was on them or the player. The closest they've come to is rolling back everyone when an issue affects enough people and it's caught early enough.

**Comment by IArePolar** [comment]
But I didn't die

**Comment by IArePolar** [comment]
Well I didn't lose all my soul points

**Comment by Trixter313** [comment]
If your account was hacked, the hacker could have done all the dying. And they could have stayed logged in and regenerated some soul points.

**Comment by IArePolar** [comment]
If I was hacked or not, what can I do to get my level 30+ items back? I can't just regain them easily

**Comment by Trixter313** [comment]
Well the options aren't the greatest but you can try asking friends or just people in towns for items they could spare, you could try doing some quests for items, and you could just farm up the items again. What level is the archer?

**Comment by IArePolar** [comment]
Are you asking my level?

**Comment by IArePolar** [comment]
40

**Comment by IArePolar** [comment]
Where exactly does it specify the 'no return policy'

**Comment by IArePolar** [comment]
Is there a chance the staff would give the items back

**Comment by Trixter313** [comment]
I'm gonna say no. If you look through the forum posts of people with disappearing items etc, there's always a bunch of people commenting about the no refunds policy because it's so strict and well enforced. Here's an example thread: https://forums.wynncraft.com/threads/my-weapon-just-dissapeared.91778/

**Comment by Yoavronen** [comment]
@IArePolar did you by any chance kept minecraft open and logged into wynncraft for some time before disconnecting or playing again? (for example opening minecraft , logging into wynncraft and tabbing out to listen to music for a while).

**Comment by VinnyLegend** [comment]
i have the same problem but i was only left with quest items and my 2 bows

**Comment by atomicaustin8** [comment]
I have lost all my items. I logged out with 2 soul points and now everything is gone. this also happened to my friend 2 days ago. This is a serious problem with the server because now I have to get everything I had again. It ruins the gameplay and I know for sure I was not hacked.

**Comment by YunoFGasai** [comment]
Please change the issue name to "loosing soulpoints leads to loss of items"

**Comment by JMLG1999** [comment]
I'm 100% sure i wasn't hacked cause; 1- it happened in between 5 min, 2- i changed the password 2 days before, therefor i am sure i was not hacked.

**Comment by VinnyLegend** [comment]
I was still logged on to Minecraft just not on the the sever

**Comment by atomicaustin8** [comment]
@YunoFGasai It just happened to be when I had 2 soul points that I lost my items. I did not lose those points. To add, my friend had 10 soul points.

**Comment by Moe-Ronickah** [comment]
There is another way that these can happen, but no player would ever have a way to test for it; you logoff, but the server doesn't get the message.  Extreme lag could do this, dropped packets could do it, maybe, but I'm at a loss to any other explanations.
