### ISSUE TITLE
Wynncraft Excavation Site A

### ISSUE THREAD

**Issue by tilly38** [Wynncraft/Issues#4815]
When I started the quest i did everything it told me and when i defeated the boss I got teleported back to the site. I talked to Vade to finish my quest but he told me i needed to translate the tablet and now i cant complete the quest

**Comment by Odnod** [comment]
You need to kill the Pharaoh in the last room of the temple and bring Vade the yellow crystal that gets dropped by said Pharaoh.

**Comment by tilly38** [comment]
I did but he never dropped it and i killed killed him 3 times

**Comment by Trixter313** [comment]
Try doing it on another world, does it get dropped now? Thanks!

**Comment by Yoavronen** [comment]
The [dropped items not spawning] glitch is back, this has happened before,  it will be fixed soon.
My advice is to go do some other quests and check on site A every once in a while to see if it's fixed.

**Comment by Odnod** [comment]
No, yuno site A is different from the others. Site A is the only one that requires you to kill a boss that drops the crystal, whereas in the others you just pick it up off the ground.

**Comment by Yoavronen** [comment]
then ignore what I said

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
