### ISSUE TITLE
Class's were deleted when kicked

### ISSUE THREAD

**Issue by Endeh** [Wynncraft/Issues#4816]
I talked to my friend and he explained to me that when he was kicked for suspicious movement due to lag, it kept giving messages he was kicked for while (30 mins have passed since kick) but when he finally logged back on his only class got deleted. He knows for sure he didn't accidentally press deleted because he was on the class, kicked, and came back to it being gone. He also was a low-ish level archer (lvl. 14) but he has depressing items and a legendary. He sadly does not have any screen shots though. His IGN is: bolt67890

**Comment by thecoolkogut4** [comment]
was he in 1.9 when this happened? or 1.8.X

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
