### ISSUE TITLE
Invisible Enemy

### ISSUE THREAD

**Issue by aamike123** [Wynncraft/Issues#4819]
A little while outside Nemract, within veiw of it, i was grinding some 19-21lvl skeletons, and after killing a large wave of them, I started taking damage from an unkown scouce. No range enimies spawn in the area i was grinding in (between the river and mt. wynn) so i am wondering if this is a bug.

Unfortunatley i lost my items at that death, and was not able to reterive them after apox 7 min. of searching. Incedent accured around 9:35P.M. U.S. central time, 4/12

1. Can you please have this Invisible enemy glitch looked into and resolved
2. May you rooll back my invetory

**Comment by ThunderRemix** [comment]
1. Might be possible.
2. Not possible due to no-refund policy.

**Comment by Moe-Ronickah** [comment]
I will take a guess here and bet that there was no invisible enemies, but rather, it was due to lag.  You didn't "see" the skeletons, because they killed you, before you killed them.  There have been no other reports of this, so I'm fairly certain that this was a lag issue.

**Comment by YunoFGasai** [comment]
@Moe-Ronickah not sure if this is connected but guild wars used to have a similar bug, some of the last mobs left (probably a percent of all mobs and I just didn't notice in the clusterfuck which is a guild war) will be invisible until hit or killed.
