### ISSUE TITLE
Um... Potion of Hunger?

### ISSUE THREAD

**Issue by bolt67890** [Wynncraft/Issues#4820]
I was finishing the quest where you get ingredients for the cook in Ragni with my friend, Enduh. He and I finished it at the same time and received potions of mana, which are given on quest finish. We looked at our text box and we found there is a typo that says that you received 3x "Potion of Hunger" I have a screenshot, but I will be posting the picture later because I am on a device. Please fix!

**Comment by DarkDemonDragon** [comment]
The irony... xD
@AckroWynn is this an easy fix?

**Comment by Blocktopia9** [comment]
This is because before the Gavel update, they were called potions of hunger because there was no texture pack, so mana looked like hunger (they also did nothing).

**Comment by DarkDemonDragon** [comment]
Actually mana potions work now

**Comment by bolt67890** [comment]
XD I can't draw!
![hunger pic](https://cloud.githubusercontent.com/assets/18435567/14516227/b772e27c-01b5-11e6-9cba-330918ac08d0.PNG)
![mana pic](https://cloud.githubusercontent.com/assets/18435567/14516233/bebfcbee-01b5-11e6-8d2e-7707fe3e20be.PNG)

**Comment by Blocktopia9** [comment]
Yeah, I know they work now, I was just saying that in the past they did nothing.

**Comment by Yoavronen** [comment]
@Blocktopia9 the hunger potions worked fine in the past (no need to continue debating it as it was changed since then)

**Comment by bolt67890** [comment]
Is the potion name going to be changed?

**Comment by AckroWynn** [comment]
Fixed!

**Comment by Trixter313** [comment]
Woot! You can expect to see the fix when the next map update occurs.
