### ISSUE TITLE
Teleported into a wall.

### ISSUE THREAD

**Issue by OrBatson** [Wynncraft/Issues#4821]
Hey Admins/Mods/Builders... idk...!
i've been in Llevigar area (somewhere is the forest near it) and i found a underwater cave and inside of it i found a sign that tells me to move just like the light. After doing it, its opened a piston that trapped me and spammed in the chat "Null". Now i am stuck in a wall, hearing horses and chickens. (-1584, 52, -1637) Please help me get out and fix that bug! I cant teleport im just stuck there :( (btw, this server is awesome! great work builders/admins! :D) Thanks!

**Comment by OrBatson** [comment]
If someone got stuck to, i just got out of there. Rejoin to an other server and teleport with a scroll (you need to move a litle bit). Please fix that bug!

**Comment by Trixter313** [comment]
Just so you know, you can almost always type /kill with 3+ soul points and it will respawn you at the nearest visited town.

**Comment by OrBatson** [comment]
Oh.... Thanks

**Comment by Odnod** [comment]
If you have resolved your issue, please close the thread :) Also, the place where you got stuck is I believe a location from the quest "green skinned trouble" so you probably were just denied access to a teleport zone that was under the piston (the 'null' messages point to this)
