### ISSUE TITLE
No armor skins

### ISSUE THREAD

**Issue by Endern** [Wynncraft/Issues#4824]
Whenever I equip armor,it doesn't add on to my skin,and only shows on my character like vanilla armor.This started when Gavel update was released.
     I am sorry if this feature actually was removed with Gavel update.
Version:1.9
Mods:OptiFine

**Comment by Yoavronen** [comment]
> Whenever I equip armor,it doesn't add on to my skin,and only shows on my character like vanilla armor.This started when Gavel update was released.
 I am sorry if this feature actually was removed with Gavel update.
 Version:1.9
 Mods:OptiFine

this is probably due to the fact that you are using version 1.9, ty to use 1.8.9 and tell us if there is any change in the issue.

**Comment by Endern** [comment]
I tried using 1.8.9 with and without OptiFine,and no results.The armor still shows like in vanilla,and I have seen some youtubers on wynncraft had this feature after the Gavel update.

**Comment by Odnod** [comment]
The armor skins feature is currently disabled due to maintenance.

**Comment by Yoavronen** [comment]
@Endern are you talking about armor skins (different skins for each armor) or 3d armor skins?

**Comment by Endern** [comment]
About armor skins that are diffrent for each piece of armor.I never heard about 3D armor skins though

**Comment by nont43** [comment]
wynncraft's members r creating new armor skin bro.
