### ISSUE TITLE
Small NPC Bug (Ice Nations)

### ISSUE THREAD

**Issue by RedMorcus** [Wynncraft/Issues#4825]
Just a small bug that has been in the game for ages, the villagers on the ice islands make spider sound effects.

**Comment by Sandertv** [comment]
I don't think that is a bug, probably just made like that as whispers or something.

**Comment by RedMorcus** [comment]
I doubt it was intentional that they hiss loudly when damaged...

**Comment by Moe-Ronickah** [comment]
Nothing to fix.  They were born that way.  => That sound is intentional.

**Comment by YunoFGasai** [comment]
To continue what moe said,  it was made to sound like they have runny noses
