### ISSUE TITLE
Black Abyss of Nothingness???

### ISSUE THREAD

**Issue by DarkAssassinLink** [Wynncraft/Issues#4827]
I was in the snowy Biome, i forgot wat the place was called, and i logged out of my Archer. i got off, a few days later I get back on and I'm just stuck on my Archer. I'm able to get on my other classes, but i cant do anything when i get on my archer. 

![af3860d1856f3b68532a3b8292314ec6](https://cloud.githubusercontent.com/assets/18412517/14552551/8d7d5454-02ad-11e6-951f-84cfd22c0be7.png)

**Comment by DarkAssassinLink** [comment]
plz help

**Comment by Yoavronen** [comment]
@DarkAssassinLink according to your screenshot you didn't select your class and you're still in the class selection room.

**Comment by Yoavronen** [comment]
@DarkAssassinLink can you hit f3 for me so we can know if you're falling in the void or stuck in the class selection room?

**Comment by DarkDemonDragon** [comment]
If you are stuck anywhere and you have 3 or more soul points, do /kill to be respawn in the nearest town. Please close this issue if my suggestion worked for you.

**Comment by DarkAssassinLink** [comment]
If the suggestion worked, i wouldnt close it so that way people with this same problem would be able to fix it. 
![2016-04-15_17 19 37](https://cloud.githubusercontent.com/assets/18412517/14575193/400761d4-032e-11e6-89d1-c00c0934883e.png)

**Comment by DarkAssassinLink** [comment]
also ur idea worked, but they need to investigate the problem. because if someone is stupid enough to not have so many soul points, dey be screwed.

**Comment by Jeisuta** [comment]
I'm having the same problem, but it won't let me use commands..

**Comment by DarkDemonDragon** [comment]
@DarkAssassinLink this tip is very easy to learn and applies to a multitude of issues. Therefore once the issues are resolved they are asked to be closed or will be closed by Github staff.

@Jeisuta you are not having same problem. Please make a separate issue while providing screenshots. Most likely you cannot see your level and items in the hotbar as you are in a limbo; however, I can't say anything more without seeing a screenshot of your situation.

@Trixter313 @Moe-Ronickah  the main issue has been resolved please close this
