### ISSUE TITLE
black room on nothingess but black wool 4x4x4

### ISSUE THREAD

**Issue by shadowdragon166** [Wynncraft/Issues#4829]
while I was logging on to me archer level 32 I was able to go into the game but the thing is its still at the main old black room and now I'm stuck there and cant go anywhere because I don't have any teleportion scrolls plz fix the bug.
also it just like the black for of the abyss

**Comment by DarkDemonDragon** [comment]
If you are stuck anywhere and you have 3 or more soul points, do /kill to be respawn in the nearest town. Please close this issue if my suggestion worked for you.

**Comment by shadowdragon166** [comment]
thank you

**Comment by DarkDemonDragon** [comment]
If your issue has been resolved please close this issue.
