### ISSUE TITLE
Skill bug

### ISSUE THREAD

**Issue by PikaLord** [Wynncraft/Issues#4832]
Hi.
This is very annoying. Its my skills that a going down with out my doing anything
The skills that i "Had"
Strength: 10
Dexterity: 12
Intelligence: 11
Defense: 12
Agilty: 15
Now they are only:
Strength: 10
Dexterity: 12
Intelligence: 11
Defense: 9
Agility: 12
Please, Help me out with this. My MC - Name is: PikaLord2

**Comment by Odnod** [comment]
You can gain and lose skill points from armor and weapons, I assume this is the cause of the issue but you should check anyway. Have you switched he'd out any pieces of armor recently?

**Comment by PenguinInSnow** [comment]
He's right indeed. Watch your equipment, most of them will add and remove some of thoses stats who may be useful as a requirement to use other pieces of equipement.

**Comment by Verret001** [comment]
Is this resolved?
