### ISSUE TITLE
classes

### ISSUE THREAD

**Issue by angelgirl767** [Wynncraft/Issues#4833]
my class got deleted when  i logged off and a day later i logged back on and my lvl 18 warrior was gone.

**Comment by Trixter313** [comment]
So you deleted a class and another one was also deleted? You say you deleted it and then when you logged on it was gone. Sounds like the proper thing to happen.

Or are you saying you accidentally deleted it and would like it to be brought back?

Thanks!

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
