### ISSUE TITLE
Quest Jungle Fever

### ISSUE THREAD

**Issue by VoidPotato** [Wynncraft/Issues#4835]
this quest gives you 64 liquid emeralds and somehow i drank one of them and forever glitched out this quest.
some moderators/admins are able to help me finish this quest that would be great other than that i got 63 emeralds in my inventory
-lilzuktato

**Comment by Odnod** [comment]
Try typing /fixquests

**Comment by VoidPotato** [comment]
yea it says no missing quests items

**Comment by Trixter313** [comment]
You have to get rid of all of the quest emeralds then use the command /fixquests

To get rid of them, fill up your inventory completely then stand on an item and drop the emeralds. The item you were standing on will fill up the space and make no room for the emeralds to come back. Then make some space and type /fixquests

That should fix it! Let us know whether it works out not, thanks!

**Comment by VoidPotato** [comment]
its fixed thanks!

**Comment by Trixter313** [comment]
Glad to hear =)
