### ISSUE TITLE
Wynncraft Items System Bug

### ISSUE THREAD

**Issue by MagicGum** [Wynncraft/Issues#4836]
As you probably know, casting a spell changes the name of an item. However, this invalidates your item's stats and makes them not work during this time period when you cast a spell. For example, a grimtrap's life steal is procced by thorns and reflect. But when you're in the middle of casting a spell, life steal will not proc when you are hit.

**Comment by Yoavronen** [comment]
@MagicGum I'm pretty sure that the weapon id's still work when casting spells, maybe you have a negative id on something that negates it?

**Comment by thecoolkogut4** [comment]
I noticed something like this before. I was not 100% about what it was though. whenever I charge on my warrior I lose some health, but if I don't use any spells my health keeps regening. (I lose health faster with spells due to the life steal cutting out)

**Comment by YunoFGasai** [comment]
I can confirm this is not happening, I have a wand with a health id and while casting spells my hp doesn't change so the effect is still valid.
