### ISSUE TITLE
/armor (/armour) Not working

### ISSUE THREAD

**Issue by Endern** [Wynncraft/Issues#4837]
So,I have armor skins toggled off,and I only recently learned about this command.I wanted to toggle the skins on,but the command doesn't work.
Version:1.8.9 
Mods:OptiFine

**Comment by Yoavronen** [comment]
Armor skins were disabled server wide some time after the release of gavel, hopefully the texture making team will finish making a skin for all of the new armor soon.

**Comment by Endern** [comment]
Oh.Thanks!
