### ISSUE TITLE
Texture Pack Error

### ISSUE THREAD

**Issue by Marcus270** [Wynncraft/Issues#4838]
![2016-04-16_13 23 56](https://cloud.githubusercontent.com/assets/18505203/14583167/cb9d0f3e-03d6-11e6-8b09-ecb4d23659ca.png)
![2016-04-16_13 23 58](https://cloud.githubusercontent.com/assets/18505203/14583168/ce853384-03d6-11e6-8142-c3511998e27b.png)
![2016-04-16_13 24 04](https://cloud.githubusercontent.com/assets/18505203/14583169/d11894ce-03d6-11e6-9e5f-2b4b312e5223.png)

I logged on to WynnCraft this morning, just to find that the texture pack glitched. I've tried everything from relogging to restarting my computer. It would be much appreciated if someone could give me an answer/fix the bug. Thanks

**Comment by Yoavronen** [comment]
Do you have any other texture packs on?
If so pkease disable them.

**Comment by Marcus270** [comment]
I already disabled all of them

**Comment by Trixter313** [comment]
Hmm, what version of Minecraft are you using? If it's 1.8.9, try using the latest 1.9 and if it's 1.9, try using 1.8.9.

Let me know if that helps at all.

**Comment by SapphireStar05** [comment]
Something Weird Happened To Me Related To This Too, It Won't Load The WynnPack No Matter What I Do. I Changed Versions, I Edited Server Info, But It Still Won't Work!

**Comment by bolt67890** [comment]
That happened to me too! XD

https://gyazo.com/a63d57140628b5e07ee1c910996e4818

**Comment by thecoolkogut4** [comment]
this happened to me on 1.9, i switched back to 1.8 and it got fixed.

**Comment by Moe-Ronickah** [comment]
At the present, the texture pack is 1.8 compliant, not 1.9 compliant.  The game itself is 1.8 compatible, but it is a 1.7 game.  If you don't want weird floors, go back to any version of 1.8.
