### ISSUE TITLE
Craftmas chaos glitch

### ISSUE THREAD

**Issue by CreeperGuy7777** [Wynncraft/Issues#4839]
I was doing the craftmas chaos quest, and it didn't let me into the room where you fight the summoner. I saw the dialog and the door didn't open. This is annoying because I can't get home without reseting :(

**Comment by Trixter313** [comment]
So what part are you on in the quest? If you're just stuck in past Selchar, you can try using /kill with 3+ soul points to see if that helps.

If not, what does it say in your quest book?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
