### ISSUE TITLE
BUG help

### ISSUE THREAD

**Issue by RORO20002** [Wynncraft/Issues#4844]
I have a big bug on my skill point due to update me they have not been reset then I can use my bow 
https://gyazo.com/39cb5b90c4fbafa6413a2a03c3630515
https://gyazo.com/0d420e0601f44205d4549fe02b0159da

**Comment by Yoavronen** [comment]
you can buy a skill reset scroll from the tower of amnesia you unlock at the tower of amnesia quest that starts at level 25 (according to your skills you are level 40 so I guess you completed it).

**Comment by RORO20002** [comment]
or

**Comment by Verret001** [comment]
The solution to this matter has been given.

**Comment by Moe-Ronickah** [comment]
@RORO20002 , I'm sorry, but there is no other solution to this.  If you want to use that bow, you will need to reset your skill points buy either buying a skill reset scroll, on your own, as Yuno said, or you can buy one from another player.  Honestly, it's not worth it to do that for a single weapon or piece of armor; it's better to just get another piece.
