### ISSUE TITLE
Texture Pack Issue

### ISSUE THREAD

**Issue by SapphireStar05** [Wynncraft/Issues#4849]
The Wynncraft Texture Pack Won't Load No Matter What I Do. I Changed versions, I changed server resource packs, and it still doesn't work. I deleted everything wynncraft related in the server resource pack folder. NOTHING WORKS! Please help me.

**Comment by Verret001** [comment]
What version of minecraft are you using?

**Comment by SapphireStar05** [comment]
I've Tried 1.9.2, 1.9.1, 1.9, 1.8.9, And 1.8.8

**Comment by Verret001** [comment]
Could you record or give screenshots?

**Comment by SapphireStar05** [comment]
ok

**Comment by SapphireStar05** [comment]
in a second

**Comment by SapphireStar05** [comment]
![screen shot 2016-04-19 at 5 15 54 pm](https://cloud.githubusercontent.com/assets/18516605/14659659/bd4cf114-0652-11e6-9ca7-e7a7445ad619.png)
![screen shot 2016-04-19 at 5 16 21 pm](https://cloud.githubusercontent.com/assets/18516605/14659660/bd4d2670-0652-11e6-9232-c87bb95fce25.png)
![screen shot 2016-04-19 at 5 16 27 pm](https://cloud.githubusercontent.com/assets/18516605/14659662/bd5f48e6-0652-11e6-91dd-ffd405214805.png)
![screen shot 2016-04-19 at 5 16 40 pm](https://cloud.githubusercontent.com/assets/18516605/14659661/bd5f0ade-0652-11e6-8c37-fc3532310df9.png)
![screen shot 2016-04-19 at 5 17 12 pm](https://cloud.githubusercontent.com/assets/18516605/14659663/bd725706-0652-11e6-92ef-029ff51e97eb.png)

**Comment by SapphireStar05** [comment]
It just keeps spamming me like that.

**Comment by Trixter313** [comment]
What OS are you using? Some people have reported issues on Macs I believe.

**Comment by SapphireStar05** [comment]
OSX Yosemitie

**Comment by SapphireStar05** [comment]
auto resource packs works on all servers BUT wynncraft.

**Comment by Trixter313** [comment]
Ah, that would explain it then. I don't believe we know what the issue is with OSX right now. Hopefully another staff member might be able to help you out.

**Comment by siddo0sidddo** [comment]
This happened to me and a bunch of my friends. :( we are all running windows 7 enterprise. PLZ HELP!

**Comment by SapphireStar05** [comment]
Maybe I should update to El Capitan

**Comment by Trixter313** [comment]
If you think it might help, I don't see any harm in trying. Maybe that would solve it.

**Comment by SapphireStar05** [comment]
Updating now... should take about 15 minutes

**Comment by Trixter313** [comment]
Great, I hope it works out. Let us know!

**Comment by SapphireStar05** [comment]
Ok. BTW, If you are high enough level and actually play on wynn, i need quest help

**Comment by SapphireStar05** [comment]
LV 70+

**Comment by SapphireStar05** [comment]
Updates Successful & Texture Pack Works.

**Comment by Trixter313** [comment]
Really? That is great to hear!

As for the help, I've been busy with work for a long time so I don't get on too often.

Have fun playing now that it works! =)
