### ISSUE TITLE
Texturepack/server issue?

### ISSUE THREAD

**Issue by JJkeer** [Wynncraft/Issues#4850]
I got to Nemrac and i bought very interesting staff.
Is this server bug or texturepack
![2016-04-17_19 54 48](https://cloud.githubusercontent.com/assets/18516705/14588647/d460b2dc-04d6-11e6-968c-98620a492fb8.png)
![2016-04-17_19 55 00](https://cloud.githubusercontent.com/assets/18516705/14588648/d469c322-04d6-11e6-831d-e57aaa8857f5.png)

**Comment by Odnod** [comment]
This probably means you are playing in minecraft 1.9, make sure this is the problem and switch to minecraft 1.8.9 if it is the case.

**Comment by JJkeer** [comment]
1.9.2 , Im moving down to 1.8

**Comment by Odnod** [comment]
Yeah, that issue is often caused by running Minecraft 1.9, switching to 1.8.9 usually fixes it.

On another note, did it work?

**Comment by JJkeer** [comment]
Yep, it worked.
