### ISSUE TITLE
lost items when server closed

### ISSUE THREAD

**Issue by wyll1972** [Wynncraft/Issues#4851]
I was on server 5 at 7:54pm pst on april 17th 2016 in my bank organizing my inventory. Then all of the sudden the server closed. No countdown to it just closed. I thought nothing of it but when I got back in the server my stuff I put into my bank including pelier was missing, not in my inventory or my bank. There was only 1 other item missing my sandstorm boots. Please help me get back the items I lost, and thank you for whatever you try to do to help me.

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so unfortunately there's not really anything we can do in this case. I'm very sorry about it and I hope it doesn't happen to you again!

Try asking around, someone might give you replacement items.
