### ISSUE TITLE
I lost something

### ISSUE THREAD

**Issue by KawaiiCrafter7** [Wynncraft/Issues#4852]
Hello admins and ppl! I lost my armour for level 54 (iron) and most of my emeralds(4 liquid)! Also 1/4 of my lvl is gone for some reason! I need my stuff back! Help me admins! I was lvl 55

**Comment by Verret001** [comment]
Wynncraft issues as a strict no return policy, but do you know where you were? Did the server close? Also were you using 1.9?

**Comment by KawaiiCrafter7** [comment]
I was near gelibor on 1.8.9 and the server didn't close!

**Comment by Verret001** [comment]
Do you have any screenshots?

**Comment by YunoFGasai** [comment]
#4812 you made this thread a week ago, did it happen again or are you talking about the same incident?

**Comment by Verret001** [comment]
Either way You shouldn't make deplicates

**Comment by Verret001** [comment]
Please use the thread #4812.
