### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by solsdii** [Wynncraft/Issues#4853]
Hello, i was playing normaly but i AFK for eat fro sometings like 20mins and when i come my items disapers and i just have 5 bows in my inventory.

I really like this server and i don't when to restart and new personage, thx for help me !!

**Comment by Verret001** [comment]
Wynncraft has a strict no refund policy

**Comment by YunoFGasai** [comment]
@solsdii you probably afk'd in a non safe spot and got killed by mobs several times leading you to lose your items and get the oak bows. 
wynncraft has a no-refund policy but I'm sure some players will help you out with your missing gear.
