### ISSUE TITLE
baal impüossible 2 find

### ISSUE THREAD

**Issue by Vlanna** [Wynncraft/Issues#4854]
ok i need help i have more than 10 deaths ... i am not  find this baal in the barracts

if the coordinate correkt in the wiki ? pls help

**Comment by TrashcanMan** [comment]
Can you get a screenshot of where you've looked? You're supposed to go into the barracks, all the way down the path and parkour, and you should be outside a meeting hall with Ba'al right below you.

**Comment by Vlanna** [comment]
ok i have an reinstall my client... my client was brocken....sry can be closed here...thx :)
