### ISSUE TITLE
I'm stuck in the Pigmen's Ravine

### ISSUE THREAD

**Issue by SniperWolf94** [Wynncraft/Issues#4855]
![2016-04-18_17 30 57](https://cloud.githubusercontent.com/assets/18540520/14621854/57d1cc28-058b-11e6-959f-03e637bcf6b8.png)
I was play in the server when i teleport up to mountain in that place, but finally ends stuck at coordinates:

X: -830
Y: 124
Z: -1295

If your staff can teleport to any place please

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out.
