### ISSUE TITLE
Dead Miners

### ISSUE THREAD

**Issue by bolt67890** [Wynncraft/Issues#4856]
I UNDERSTAND THE POLICY.

I died on the emerald trail, to be teleported back to Ragni. When I respawned, I spawn next to 2-3 DEAD MINERS who killed me over and over again and made me lose all of my stuff. Can you find how to fix this?
![2016-04-18_21 19 42](https://cloud.githubusercontent.com/assets/18435567/14627707/bb8e6170-05ab-11e6-87ee-65cbdd3f954e.png)

https://gyazo.com/d5e34e99270e9644dd39d5403d6cbd2c

Dang it miner. Stupid thing made me lose my 4 depressing sticks.

**Comment by ThunderRemix** [comment]
It's just a player made invasion. It cannot really be fixed. Sorry. This issue will be closed soon.

**Comment by Verret001** [comment]
If it ever happens again you can type /hub quickly and switch servers.

**Comment by bolt67890** [comment]
Thanks. Are player made invasions bannable?

**Comment by Trixter313** [comment]
It's rule #12 here https://forums.wynncraft.com/threads/game-forum-rules.111874/
