### ISSUE TITLE
Bug Destroyer

### ISSUE THREAD

**Issue by Spotgizmo12110** [Wynncraft/Issues#4859]
There is a huge bug/glitch, and I call it Bug Destroyer. I have spawned in to Wynn and got stuck in some hole or time frame that has deleted my weapon, I have no clue how but that is the only object missing.  I also have experienced lots of lag when I get on now, almost to much to play.  There is no way for me to level up or move around. Hope this gets fixed so someone else doesn't have it happen to them. :P

**Comment by Trixter313** [comment]
If you're stuck, typing /kill with 3+ soul points should get you out.

As for the weapon, it's most likely that you accidentally dropped it at some point. Wynncraft has a no refunds policy so unfortunately there's nothing we can do about that.

Does this solve all of the issues you were having? Thanks!

**Comment by Spotgizmo12110** [comment]
I relogged in and got unstuck, but since that time I have been having lot of lag just on that server.

**Comment by Trixter313** [comment]
Hmm, well I don't really know what we can do about lag. You didn't change some setting that might cause more lag? Or did it begin around the same time as a Wynncraft update?

**Comment by Spotgizmo12110** [comment]
I'm not sure when the update was, but I changed all of my settings back to what they were before and it is a little better but there is still a lot of lag.

**Comment by nont43** [comment]
try change your video setting from fancy to fast and force stop cloud might help a bit.

**Comment by Spotgizmo12110** [comment]
The clouds were off and I will try the other, thank you.

**Comment by Trixter313** [comment]
Did nont43's suggestion fix your issue? Thanks!

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
