### ISSUE TITLE
Horses disappeared

### ISSUE THREAD

**Issue by Kfajver** [Wynncraft/Issues#4861]
One day, I wanted to make a tier 3 horse. I released this 427 blocks Emerald and succeeded. I went on it a few minutes, but after a short time I had to clean up the room so not starting from the server I began to clean up. When you return to the computer says that I have been kicked from the server, probably by my internet. I went to the server again, and it turned out that my tier 3 disappeared and instead I have a tier 1. What do I do in this situation?

**Comment by nont43** [comment]
Refresh your router and try join again.

**Comment by Kfajver** [comment]
It didn't help

**Comment by YunoFGasai** [comment]
so you only had one horse and it was tier one?
how many emeralds did you have went you logged back on?

**Comment by Kfajver** [comment]
I have only one tier 1 horse and how I logged into it I had with you any emeralds.

**Comment by YunoFGasai** [comment]
sorry for the late response, do you remember putting/removing the horse from your bank before it disappeared and wherever a server reset happened shortly after?

**Comment by sammyvsparks** [comment]
@Kfajver was the kick message the one where you fail to connect to the lobbies? or an actual kick?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
