### ISSUE TITLE
I have gliched in location 71.3/59/1905.300

### ISSUE THREAD

**Issue by ble1x** [Wynncraft/Issues#4862]
I click on bed, in some location and "puff", im in some chimney or I don't know were. I can't go out. I'm scared, I can't use teleportation scroll. I need help. It's so frustrating to be traped. : ((((

**Comment by YunoFGasai** [comment]
Use /kill if you have more than 3 soul points

**Comment by ble1x** [comment]
Thanks i'll try it later
20 kwi 2016 17:49 "Yuno" <notifications@github.com> napisał(a):
