### ISSUE TITLE
Items missing except bow + breathing helmet

### ISSUE THREAD

**Issue by SilverSpeedster** [Wynncraft/Issues#4863]
I went back on the server this morning and all my items were missing, I honestly don't know how it happened, I had 2 stacks of emeralds, a bunch of good armor and an iron string bow. At least try to find a way to fix this,

**Comment by Trixter313** [comment]
It sounds like you died with less than 3 soul points at some point. That would explain you still having your quest items and a bow.

**Comment by YunoFGasai** [comment]
@Trixter313 there seem to be multiple complaints of people that logged on and lost everything, I'm not sure if they died while logging in (then its lag to is to blame) or if it's  #3821 all over again

**Comment by YunoFGasai** [comment]
this is a dupplicate of #4814 please refer any and all comments to the original thread
