### ISSUE TITLE
ALL ITEMS MISSING

### ISSUE THREAD

**Issue by Destroyer282828** [Wynncraft/Issues#4865]
Hello my name is Destroyer282828. Before I logged off to go to bed I had 13 soul points. Then I logged off. (I logged off in cinfras) and now when I log back on, I am missing all my armour, and all weapons, and all my quest items with some crappy bows in my inventory. Which did like 20-34 dmg. And last night I had AZ, and some really good armour. And now I can't leave cinfras, I die when I exit the city. But the weird thing is when I logged back on and all my items were missing but I had 15 soul points. I don't get it. I am seriously very angry and sad and confused, I just get on BAM 15 SOUL POINTZ! OH AND THE COST FOR 2 SOULPOINTS IS ALL YOUR ITEMS! THANK YOU -.-... But somebody please help me get the items back, I love wynncraft

**Comment by YunoFGasai** [comment]
the fact your soul points went from 13 to 15 is a normal mechanic in wynn, everyone has a passive soul point regen at a rate of [not sure need to check, before you logged off did you do anything else?
did you by any chance leave wynncraft open and went to do something else? (like watching some YouTube or getting something to eat)

**Comment by Destroyer282828** [comment]
nope, i closed minecraft and closed my computer and went to watch a movie

**Comment by YunoFGasai** [comment]
this is a supplicate of #4814 please refer any and all comments to the original thread
