### ISSUE TITLE
Olux's prized weapon didnt give additional skill points.

### ISSUE THREAD

**Issue by nont43** [Wynncraft/Issues#4867]
# Delete this line if you've searched for a duplicate issue first

I've just got olux's prized weapon, and i see that this weapon have additional skill points with it but
it just didnt add them to my skill points
        dunno why?

thank

**Comment by Trixter313** [comment]
See if doing /class helps at all. Also, make sure the weapon is in your first slot.

**Comment by Odnod** [comment]
It only adds them to your skill points if you are holding it, holding the compass=not holding the weapon=no extra skill points.

**Comment by nont43** [comment]
Thank u guy so much!! Im going to apply your discussions soon :D

**Comment by DarkDemonDragon** [comment]
I explain about the compass in this video: https://www.youtube.com/watch?v=P8MZxhy_3bc

**Comment by nont43** [comment]
@Odnod I think u r right, thankyou!
