### ISSUE TITLE
All items missing

### ISSUE THREAD

**Issue by Omgkat** [Wynncraft/Issues#4868]
I've seen a lot of people losing their items, most of the time being the player going afk and losing all their soul points. I've faced a similar problem, but I still remember logging off with about 1 or 3 soul points in a town so I wouldn't lose all my items. Today, I logged into my archer class and saw I had nothing but an oak bow. I was still level 54 and my stats were all still there (excluding the ones from my armor and weapon). I did buy the armor and bow from the town I was in so I could at least try to survive outside. I don't know what to do .-.

**Comment by nont43** [comment]
This's life man, wont be sad

**Comment by YunoFGasai** [comment]
@Omgkat can I ask which town that was?

**Comment by TheSeahawkDerp** [comment]
same happened to dr_pepper185

**Comment by Zamice** [comment]
Same thing happened to me, lost 2+ stacks of emeralds and 2 emerald blocks.
I afked in Ragni and came back in Maltic.

**Comment by Zamice** [comment]
Same thing happened to me, lost 2+ stacks of emeralds and 2 emerald blocks.
I afked in Ragni and came back in Maltic.

**Comment by Zamice** [comment]
Same thing happened to me, lost 2+ stacks of emeralds and 2 emerald blocks.
I afked in Ragni and came back in Maltic.

**Comment by YunoFGasai** [comment]
this is a supplicate of #4814 please refer any and all comments to the original thread
