### ISSUE TITLE
I`m stuck at the quest craftmas chaos

### ISSUE THREAD

**Issue by FwonQ** [Wynncraft/Issues#4869]
I`m stuck in invisble blocks. Can a mod or admin help me to get out this 
![ml9hjwr](https://cloud.githubusercontent.com/assets/18531802/14712633/3d65f864-07de-11e6-9798-bb11d82c1a44.png)

**Comment by YunoFGasai** [comment]
Do /kill if you have more than 3 soul points.

**Comment by nont43** [comment]
U r mage?? if u r try to teleport out.

**Comment by FwonQ** [comment]
i used my teleport but it has invisible blocks so i can`t
