### ISSUE TITLE
Wand Relic

### ISSUE THREAD

**Issue by CreepaBoy** [Wynncraft/Issues#4870]
The door on the island dosen't work. I put an item in the hopper and i click the button but it still dosen't open it is also day time.

**Comment by Trixter313** [comment]
Try switching to another world. Is it still broken?

**Comment by CreepaBoy** [comment]
Yes

**Comment by Odnod** [comment]
I think it might only open at night. Not positive but I heard it somewhere.

**Comment by CreepaBoy** [comment]
k

**Comment by YunoFGasai** [comment]
can confirm that the wand relic is a bit funky, I suggest that a builder either removes the day/night requirement or place a sign that will hint at the requirement.

**Comment by Moe-Ronickah** [comment]
It only opens at night.  Period.  No ifs, ands or buts.  Nighttime only.
