### ISSUE TITLE
Horses bug

### ISSUE THREAD

**Issue by Amminate** [Wynncraft/Issues#4872]
I travelled on my horse, when i get off I get back a lot.
Pls fix.

**Comment by Trixter313** [comment]
Are you using 1.9? Try using 1.8.9 instead. Let us know if it helps, thanks!

**Comment by YunoFGasai** [comment]
this sounds like regular horse lag that derives from the server lag, check your internet connection.

**Comment by thecoolkogut4** [comment]
This is a bug that happens on 1.9. Horses are pretty glitchy when you use it on 1.9. I recommend switching down to 1.8.X if you want to use a horse.

**Comment by YunoFGasai** [comment]
#4809

**Comment by Trixter313** [comment]
Please follow the original thread, linked above. Thanks!
