### ISSUE TITLE
WynnExcavation Site B Teleporting Issue

### ISSUE THREAD

**Issue by OneTupacArmy** [Wynncraft/Issues#4874]
Hey, so I was doing the Site B, all was good till I reached the purple crystal room. I collected some of them and I headed to the typical black teleportation place, but when I did tp, I was inside the blocks. I tried using my horse, and abilities, but I was stuck. The thing is that I dropped my Scorpion (legendary lvl 44 assassin weapon) in the process. After doing /kill and getting stuck another time, I finally made it into the small room where you should get tp'd, but It wasn't there, probably it suffocated. So yeah I hope I can get it back, I guess you can check the logs if you want evidence. I don't mind about the stats.

I have a screenshot of my inventory after completing the quest, my weapon was on the 1st slot of the hotbar. http://i.imgur.com/pnpbCEE.png

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refunds policy so there's nothing we can do in this situation.

To help prevent any more items from getting dropped, try changing your drop key to something that you are less likely to accidentally ever press. Hopefully it doesn't ever happen again after that adjustment!
