### ISSUE TITLE
Email Conformation

### ISSUE THREAD

**Issue by TheSeahawkDerp** [Wynncraft/Issues#4875]
When I tried to verify my account on the wynncraft forums it said it would send me an email, so I opened my email and when I saw that the email wasn't there I clicked resend email and it never sent. I double checked that my email was right and it was. Can someone please help me I want to appeal my ban.

**Comment by Trixter313** [comment]
I've also been having this issue today.

**Comment by Trenderz** [comment]
i got this issue too hrlp please

**Comment by Trixter313** [comment]
Everyone having this issue, try now. I just successfully logged in and received the email. Let me know if you can too! =)
