### ISSUE TITLE
Super Fast

### ISSUE THREAD

**Issue by TheSeahawkDerp** [Wynncraft/Issues#4876]
I was playing wynncraft like normal when I used my spider jump spell (or whatever its called), my game was lagging so i kept spamming the mouse combination for the spell and when my game stopped lagging I had super fast SPEED. It sucks because someone saw me and banned me for speed hacking. I need help I LOVE wynncraft.

**Comment by Trixter313** [comment]
If you've already been banned, post an appeal here: https://forums.wynncraft.com/forums/ban-appeals.84/

That's all that can be done about it. Good luck with the appeal!
