### ISSUE TITLE
super fast

### ISSUE THREAD

**Issue by TheSeahawkDerp** [Wynncraft/Issues#4877]
I was playing normally when I decided to do my spider jump spell (or whatever its called), it started lagging so I spammed the combination for the spell and when my game stopped lagging I had super fast speed. I had my brother (Dr_pepper185) test this and the same thing happened to him. Unfortunately someone saw me and banned me for speed hacking. Please help me I love this server and don't want to be banned.

**Comment by TheSeahawkDerp** [comment]
opps just realized I was using the wrong search bar to look for duplacites and it turns out there was one please forgive me

**Comment by Trixter313** [comment]
It's fine =)
