### ISSUE TITLE
wynncraft.com is permanently cached for me and i cant undo it

### ISSUE THREAD

**Issue by DireFire112** [Wynncraft/Issues#4879]
![image](https://cloud.githubusercontent.com/assets/16979950/14759896/03dd489e-08e8-11e6-85fd-5302544b79cf.png)

**Comment by Omirolf** [comment]
Try clearing browser cache, try it in incognito mode, if all fails reinstall the browser

**Comment by YunoFGasai** [comment]
try on another browser first

**Comment by DireFire112** [comment]
ive done everything

**Comment by DireFire112** [comment]
dosent work

**Comment by Trixter313** [comment]
Even visiting in an incognito tab didn't work?

**Comment by DireFire112** [comment]
nope

**Comment by Trixter313** [comment]
Is the issue still occurring for you? There was recently work done on the website. Hoping it might have fixed it. Thanks!
