### ISSUE TITLE
Trapped in a jail cell

### ISSUE THREAD

**Issue by WynncraftIsBae** [Wynncraft/Issues#4882]
![2016-04-23_12 53 21](https://cloud.githubusercontent.com/assets/18629462/14761249/79636282-0952-11e6-8015-c6ccbeb2ad4f.png)
I was in Llevigar doing the pirate trove quest. I got confused with a clue and went into the jail cell area in llevigar and then looked around then suddenly i was teleported into a jail cell i can't get out of! IGN - Squid_Plays

Thanks for reading.

**Comment by Omirolf** [comment]
Put an item in the hopper, it opens a door. Or you could do /kill

**Comment by WynncraftIsBae** [comment]
Thanks :)
