### ISSUE TITLE
Lost Items

### ISSUE THREAD

**Issue by SheppyBiy** [Wynncraft/Issues#4883]
When i was leveling my mage up, I was doing the quest Macabre Masquerade. when  i went down into the cave after a few minutes the server restart, I believe it was server 1, and when it came back it said I didn't have the skill points for my armour (but when I checked I did)and I got it all taken away apart from my helmet and it wasn't in my Inventory as it was full.I had 560ish health and now i have 200. is there anyway I can somehow get this back?

**Comment by Trixter313** [comment]
What happened was probably https://github.com/Wynncraft/Issues/issues/4120

Unfortunately Wynncraft has a strict no reruns policy so there's nothing we can do in this situation.

We are working on fixing this issue so it didn't happen again!

**Comment by SheppyBiy** [comment]
Okay, thanks anyway :)
