### ISSUE TITLE
Not being given the resource pack

### ISSUE THREAD

**Issue by PepsiFanatic** [Wynncraft/Issues#4884]
I've not been able to play on Wynncraft for a long time now, a bit after Gavel was officially released. I've tried everything, but nothing works. I tried disabling the resource pack, enabling it, and prompting it, but nothing. People tell me to reset my launcher, but it's not working. Can I be given the resource pack if nothing works? Anything would be helpful right about now

**Comment by Trixter313** [comment]
What OS are you using?

**Comment by PepsiFanatic** [comment]
I have a laptop with Windows 10 and a Mac with OS X I believe

**Comment by Trixter313** [comment]
Neither are working?
Also, what version of OSX is the Mac running?

**Comment by PepsiFanatic** [comment]
The version is 10.6.8

**Comment by PepsiFanatic** [comment]
Also the Windows 10 is not having this problem, its the Mac that is. Sorry for mentioning it for no good reason.

**Comment by Trixter313** [comment]
Ah, that is Snow Leopard. Can you upgrade to El Captain? This fixed this issue for someone else recently.

If it's something that you're interested in trying, you should be able to do do here: https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=1018109117&mt=12&ls=1

Unfortunately we haven't been able to find any other fixes yet so this is all we can suggest.

Let us know what you decide to do and if it helps at all. Thanks!
