### ISSUE TITLE
Kicked jumping of a building.

### ISSUE THREAD

**Issue by Rafcin** [Wynncraft/Issues#4885]
Why...
Go whatever IDE fix it, push it to your branch, merge it with master upload it be done. <3

Also will you ever be hiring (devs who don't want to be payed and can work in Java)

**Comment by Trixter313** [comment]
So what is the issue, you got kicked while jumping off a building?
Can you log back in and does it happen any more?
Thanks!

**Comment by Rafcin** [comment]
I has occurred 5 times today, and i'm familiar with the many anti-cheat systems and how they work, but the one you guys have must be structured differently, but that is about it.

**Comment by Trixter313** [comment]
Could you tell us where this building is located?

**Comment by YunoFGasai** [comment]
Maybe it's because you're lagging,  I jumped from the top of the mountains surrounding sky islands into the void and I didn't get kicked (that fall is ~150 blocks)

**Comment by Rafcin** [comment]
Mesa Mts (Bird quest) also I would show you the other but apparently I was banned on one account that my friend got banned on and I cant use my account due to apparently "Speed hacking" but the other ones I think are around, one was I just jumped around in the Sechlar town when it was red from no Christmas onto a house and jumped off, another was the Mesa areas high up, and then jumping from the building along the mesa pillar that leads to the leg relics.

**Comment by Rafcin** [comment]
Sorry for my responses i'm working on Project Tango stuff supery not secrety

**Comment by Rafcin** [comment]
well I bought an account just to show you some location just shoot me a msg if your on

**Comment by thecoolkogut4** [comment]
Rafcin what's your new IGN?

**Comment by Rafcin** [comment]
CanadianBull, Linkthe0ne

**Comment by Rafcin** [comment]
Why?
Also in a bit Robot testing auto mode.

**Comment by thecoolkogut4** [comment]
So i could message you to show me where it is.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
