### ISSUE TITLE
lost items

### ISSUE THREAD

**Issue by SereIta** [Wynncraft/Issues#4889]
Hello,
I'm just died during the quest "Jungle Feaver" and obviously due to the many travel required by the story I consumed, without realizing,all soul points. 
in the labyrinth beneath the Almuji bank I was brutally murdered by Golem. 
I've lost all items leaving nothing on the ground. Friends who were with me have found only a bow and a soul point on ground. 
It's a bug or it's normal? I was convinced that all objects were dropped on ground.

Thanks for your time, 
Cheers
_Sere_

**Comment by SereIta** [comment]
Any news?

**Comment by Trixter313** [comment]
This is probably what happened to you: https://github.com/Wynncraft/Issues/issues/3954

Please direct any future comments to the original thread. Unfortunately Wynncraft has a strict no refunds policy so there's nothing we can do about the lost items but we are working on fixing the issue so it doesn't happen again. Thank you!
