### ISSUE TITLE
Lost Items

### ISSUE THREAD

**Issue by SpookDraku** [Wynncraft/Issues#4890]
I went into the spider dungeon and died so i logged out. Then when i got back on the next day(Today 4/24/2016) all my gear is gone including my horse. 
Summary - Log on all gear is gone.
IGN is Xeg

**Comment by KawaiiCrafter7** [comment]
How many soul points did u have?

**Comment by SpookDraku** [comment]
Got done doing a quest that required me to travel a lot and get teleportaion scrolls from different towns. And I had 3 left. And I remember the death penalty only taking 2. Once I saw I had one left I hoped to regen  souls.

**Comment by Andy0132** [comment]
Head off the game when you're below five soul points. You lose 3 from /kill, you lose 1 from scrolls, and I have no idea how you lost your last soul point. Did you use any scrolls before you logged off, or when you logged on?

**Comment by YunoFGasai** [comment]
this is a supplicate of #4814 please refer any and all comments to the original thread
