### ISSUE TITLE
Well i was wondering

### ISSUE THREAD

**Issue by KawaiiCrafter7** [Wynncraft/Issues#4891]
I cant find the Guild master anywhere in Troms! Plz mark it on the wynncraft map or send me the cords!

And how many subs or vids do I need for yt rank?

**Comment by YunoFGasai** [comment]
The guild master is in Cinfras (level 70) in Gavel.
And I'm not sure about the media rank. (I think there is an answer in the faq thread on the forums)

**Comment by Trixter313** [comment]
Neither of these are issues so I'll close this. If you have any more questions or suggestions, post instead on the forums at https://forums.wynncraft.com

Thanks!
