### ISSUE TITLE
Emeralds not stacking because or Lore?

### ISSUE THREAD

**Issue by Sean040299** [Wynncraft/Issues#4892]
This isn't a huge bug as such but it has been very annoying to have to use multiple inventory space to allow the emeralds to be in your inventory because of the Lore.

Images:
![2016-04-25_13 42 22](https://cloud.githubusercontent.com/assets/18660141/14784238/6ddd6840-0aec-11e6-91f6-8e4a11258f22.png)
![2016-04-25_13 42 25](https://cloud.githubusercontent.com/assets/18660141/14784239/6de62b60-0aec-11e6-9c19-cd9aaf1caecd.png)

If my inventory if full and I need to pick up items but I cannot because of the emerald are not stackable

**Comment by TrashcanMan** [comment]
There should be a Converter Merchant somewhere in Selchar that will turn your old emeralds into new ones.

**Comment by Sean040299** [comment]
But that does not mean I have to go there every time to fix this issue though? :/

**Comment by Odnod** [comment]
This issue will never happen again unless they change the description/lore of emeralds again like they did over 2 years ago.

**Comment by Trixter313** [comment]
I believe they removed that converter merchant and as Odnod said, this issue is technically fixed because it's no longer actively occurring and it's just a matter of time until the all the old emeralds are extinct. I'd suggest just throwing them out.
