### ISSUE TITLE
Blocked loot chest

### ISSUE THREAD

**Issue by vipteacher** [Wynncraft/Issues#4894]
first, i can't speak english.

https://gyazo.com/2e6b3b591e265ef06f7664f00b13f553.png

I can't open this Lootchest(maybe tier 3)
I did serch this cave,but i didn't find some switchs.
I think its bug.please fix it. :(

**Comment by Trixter313** [comment]
There used to be a forum thread for loot chests like this but I can't seem to find it now and I'd imagine it died by now anyway.

Thanks for the report, it should be fixed soon!

**Comment by vipteacher** [comment]
Thank you ! :)

**Comment by Shadoweagle5098** [comment]
if you were trying to open it with a bow, then that would be your problem. I dont know what prevents you from opening stuff with bows, but it usually happens for everything that involves right-clicking. My advice: Open chests, doors, etc and press buttons with your soul points (aka slot 9 in your inventory). Also, I think i was the one that made the thread, Trix. I called it "You don't have permission for this area"

**Comment by Trixter313** [comment]
The thread I'm thinking of was made by an admin on the forums and it was older than the issue about no permission. If you look at the picture in the report there's a block above the chest, preventing it from opening. Just something that needs to be fixed on the build server. =)

**Comment by AckroWynn** [comment]
Fixed. 
@Trixter313

**Comment by Trixter313** [comment]
Yay! Thank you! :)

**Comment by hanakocz** [comment]
This chest is still being blocked by a block. Was there no update whole month to see the fix or...? :)

**Comment by Moe-Ronickah** [comment]
It's fixed on the build server, however, until the build server gets pushed to the game server, we won't see the fix.

**Comment by coreynj** [comment]
Still not fixed.

**Comment by Moe-Ronickah** [comment]
## **It's fixed on the build server, however, until the build server gets pushed to the game server, we won't see the fix.**
