### ISSUE TITLE
Weapons turned into lv1 starter item other items are missing (expect amulet and quest items)

### ISSUE THREAD

**Issue by Orhan27** [Wynncraft/Issues#4896]
![2016-04-25_23 16 42](https://cloud.githubusercontent.com/assets/18667310/14797711/b0d50e00-0b3c-11e6-92b1-378798c5825e.png)

**Comment by Orhan27** [comment]
![2016-04-25_23 16 59](https://cloud.githubusercontent.com/assets/18667310/14797725/bda774ce-0b3c-11e6-9000-018fc8296b82.png)

**Comment by Odnod** [comment]
Did you put that armor on after you found yourself with an empty inventory?

**Comment by Andy0132** [comment]
Is your necklace untradable, or did you put it on after you found your inventory empty?

**Comment by Trixter313** [comment]
It's been over a month since the OP had responded. I'm going to close the issue. If you're still having the issue, simply respond and I'll reopen it. Thanks!
