### ISSUE TITLE
Knockback

### ISSUE THREAD

**Issue by RoiYles** [Wynncraft/Issues#4897]
Bonjour, 

Lors de mes attaques avec mon Mage, Il y a un effet de knockback. Je ne pense pas que c'est normal car mon frère n'a pas cet effet. De plus, les mobs semblent passer à travers les murs (notamment le boss du donjon Animal).

PS: Dans le donjon Animal, j'ai réussi à passer à travers les barrière via mon sort de téléportation.
      Le boss réapparaît aussi parfois après qu'on l'ai tué.

**Comment by Trixter313** [comment]
Could you post screenshots of all of the armor you're wearing, accessories, and your weapon? It's possible one of them is causing the extra knockback.

The other issues are know issues already reported.

Thank you!
---
Google translated into French:
Pourriez-vous poster des captures d'écran de toutes les armes que vous portez, les accessoires, et votre arme? Il est possible un d'entre eux est à l'origine du repoussement supplémentaire.

Les autres questions sont savoir les questions déjà signalées.

Je vous remercie!

**Comment by Odnod** [comment]
What attack speed weapon are you using? A while back we learned that a knockback effect corresponds to weapon attack speed, with super fast attack speed items having very little knockback and super slow weapons having lots of knockback.

Quelle attaque arme de vitesse que vous utilisez? Un temps, nous avons appris qu'un effet de repoussement correspond à la vitesse d'attaque de l'arme, avec des éléments de la vitesse d'attaque Super Fast ayant très peu de repoussement et des armes Super Slow avoir beaucoup de repoussement.

**Comment by RoiYles** [comment]
@Trixter313 Je n'ai aucun équipement qui pourrait être à l'origine de l'extra knockback mais si vous voulez en être sûr, je vous ai mis des screenshots ci-dessous. 
![2016-04-26_17 45 32](https://cloud.githubusercontent.com/assets/18668258/14824673/0db33e7c-0bd7-11e6-9b78-8b97b5875154.png)
![2016-04-26_17 45 34](https://cloud.githubusercontent.com/assets/18668258/14824674/0db574b2-0bd7-11e6-954d-59f3decd4dc0.png)
![2016-04-26_17 45 35](https://cloud.githubusercontent.com/assets/18668258/14824675/0dba78a4-0bd7-11e6-8c17-0f076dcc9bf4.png)
![2016-04-26_17 45 37](https://cloud.githubusercontent.com/assets/18668258/14824676/0dbe0d98-0bd7-11e6-827a-6eea2af84b94.png)
![2016-04-26_17 45 40](https://cloud.githubusercontent.com/assets/18668258/14824677/0dbe8d36-0bd7-11e6-8185-9c511c2deef6.png)

@Odnod Mon arme a une Slow attack speed, c'est sans doute pour ça que j'ai un effet de knockback.


**Merci pour votre aide !**

**Comment by Trixter313** [comment]
Glad to see your questions were answered.
