### ISSUE TITLE
Super annoying bug

### ISSUE THREAD

**Issue by Chrocomoker** [Wynncraft/Issues#4899]
Hey, before 5 minutes I lost my armor, and I just logged in. this is very annoying I am level 78 and to buy a new set is very expensive and I'm poor. Please help me I can't play right now cause my armor is gone.... my in-game name is Lluray

**Comment by YunoFGasai** [comment]
how many soul points did you have when you logged off?
was your inventory full?

**Comment by Chrocomoker** [comment]
it was full. and i had 15. I just want my crystal, my legendary level 78 chestplate (don't remember the name :P) and i lost 2 of these (bought one after the bug) and my stalagmites. this is all i lost. please give it back to me, and now i know i need to check i have at least 4 clear slots. thanks...

**Comment by Chrocomoker** [comment]
@YunoFGasai  my inv was full. and i had 15. I just want my crystal, my legendary level 78 chestplate (don't remember the name :P) and i lost 2 of these (bought one after the bug) and my stalagmites. this is all i lost. please give it back to me, and now i know i need to check i have at least 4 clear slots. thanks...

**Comment by YunoFGasai** [comment]
Wynncraft has a no refund policy, sorry for your loss.
either way this is a duplicate issue and should be closed.

**Comment by YunoFGasai** [comment]
I'm sure that if you'll ask nicely on detlas server 1 someone will be glad to sell you some items

**Comment by YunoFGasai** [comment]
#4120

**Comment by Chrocomoker** [comment]
@YunoFGasai  are you trying to repair this bug? it happened to my friend too... and someone sold to me a chestplate with a good price...

**Comment by YunoFGasai** [comment]
as you can see on the issue I referenced (#4120) the issue is known and is been worked on by the coding team.
please post any comments on the referenced thread.

**Comment by YunoFGasai** [comment]
@Trixter313 can you close this issue?
