### ISSUE TITLE
Animal dungeon boss bug

### ISSUE THREAD

**Issue by DavidTennant17** [Wynncraft/Issues#4902]
the bug that happened to me is recorded on this video.. https://www.youtube.com/watch?v=hYR-S7LsBKg&feature=youtu.be

**Comment by thecoolkogut4** [comment]
what is your IGN? Il go check this out to see if its still going on.

**Comment by DavidTennant17** [comment]
DavidTennant17 is my IGN

**Comment by Moe-Ronickah** [comment]
Duplicate of #3191 .  Thank you for your video of this issue!  Please refer all future comments to #3191 .

**Comment by Moe-Ronickah** [comment]
PS - Don't forget to turn off your entity radar, now that we can see that the Boss Cow vanishes.
