### ISSUE TITLE
class disapear i got kinds proof of the class in a vid liste below

### ISSUE THREAD

**Issue by Silenrocker** [Wynncraft/Issues#4903]
so i just logged in and my mage was just gone a lvl 37 mage like 8 hrs play time my life is gone if you could find a fix thanks idk if you can get back my class but i hope you can refund something im sure i dint delete it cause i have been on the delete screan by exedent once and it doent delete it you need to confirm

**Comment by thecoolkogut4** [comment]
there is a no refund policy so i don't think you'll be getting your class back...

**Comment by Silenrocker** [comment]
are u a mod
?

**Comment by Silenrocker** [comment]
well fuck my life

**Comment by Silenrocker** [comment]
i have been working on this for 3 years

**Comment by Silenrocker** [comment]
o have a lvl 50 arch lvl 37 warior had a lvl 37 mage and have a lvl 26 assasin

**Comment by Silenrocker** [comment]
https://www.youtube.com/watch?v=VtQjVBKJSHA this is a link to a video i made sometime ago on about the middel im on the class select screan for like 1sec
