### ISSUE TITLE
All my Stuff was deleted

### ISSUE THREAD

**Issue by WolfGamer32** [Wynncraft/Issues#4904]
# Delete this line if you've searched for a duplicate issue first

So i was playing Wynncraft and i had to go do something, i logged off and when i can back on, all my Armour, weapons and emeralds had gone from my inventory. My username is WolfGamer32, i noticed this issue at 21:19 GMT.

If you could please help that would be great!
WolfGamer32

**Comment by Silenrocker** [comment]
I lost my hole mage class

**Comment by YunoFGasai** [comment]
How many soul points did you have?

**Comment by WolfGamer32** [comment]
I had 2 when i logged off and when i came back on  had 3, it said i gained 1 sould point while i was away

**Comment by WolfGamer32** [comment]
I was considering buying a rank on the server, but now this has happened i feel like all my hours were wasted, please this seems to be a bug and i don't know what to do.

**Comment by YunoFGasai** [comment]
this is a supplicate of #4814 please refer any and all comments to the original thread
