### ISSUE TITLE
Stuck in wall doing wynn excavation site b

### ISSUE THREAD

**Issue by CreeperGuy7777** [Wynncraft/Issues#4909]
I was doing the wynncraft excavation site b and when I was leaving the cavern after getting the purple crystal, before talking to Excavator Lykron, and I got stuck in a wall, what gives?https://gyazo.com/6306b1c8725bd5ea1e74dbf47fc489d9
Coords;
X: 56
Z: 62
Y: -529

**Comment by CreeperGuy7777** [comment]
Also, scrolls aren't working, and I don't want to lose my soul points :(

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out. Thanks!
