### ISSUE TITLE
Recurve Bow?

### ISSUE THREAD

**Issue by Shadoweagle5098** [Wynncraft/Issues#4911]
okay, so i accidentally left my game on for half an hour (._.) after i went to lobby something, i dont remember which number. However, when i come back to my computer to notice WynnCraft has been on, i have this thing called a "Recurve bow" in my inventory, as well as 64 arrows. When i logged into a world and got back out to the lobby, it was deleted from my inventory. However, i still want to know if this is a bug or something.

**Comment by Trixter313** [comment]
Near the shooting range in the lobby you can press a button that gives you a bow and some arrows.

Thanks!

**Comment by Shadoweagle5098** [comment]
i can assure you i never moved in the lobby, but its good to know it wasnt a bug. thanks!

**Comment by Trixter313** [comment]
Someone most likely dropped the items on you is what I meant but forgot to say, sorry.
