### ISSUE TITLE
missing skill points

### ISSUE THREAD

**Issue by infinityfire100** [Wynncraft/Issues#4913]
I am level 41 so i should supposedly have 80 skill points, but i only had 56. I reset my skill points using the tower of amnesia scroll thing, and it gave me 80, but while i was redistributing my points some of them didn't increase my skill levels, but still used points. In addition, I did not recieve experience for completing the quest.

**Comment by Trixter313** [comment]
Could you post a screenshot of your skill points without any armor or accessories on? Thanks!

**Comment by Moe-Ronickah** [comment]
If you set any of your skills beyond 64 skill points, the number of points shown will not be correct UNTIL you hover your mouse over the skill stat.  MC has a limit of "64" for item display in any one item slot.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
