### ISSUE TITLE
Guild stuff....

### ISSUE THREAD

**Issue by hihock** [Wynncraft/Issues#4915]
# Delete this line if you've searched for a duplicate issue first
So i am trying to join this guild and when the leader trys to inv me it syays that i am already in a guild i do /guild leave and it syas that i am not in a guild wtf what's the cause?

**Comment by Trixter313** [comment]
Have you ever changed your Minecraft username?

**Comment by hihock** [comment]
i havent

**Comment by Trixter313** [comment]
What is your Minecraft username?

**Comment by hihock** [comment]
hihock

**Comment by Trixter313** [comment]
We're you gifted your account? According to [this](https://namemc.com/profile/ccd797e3-17c4-437c-86df-b15de14c3a02) the name on that account has been changed twice.

That being said, it would make this a duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!

**Comment by hihock** [comment]
but i changed my name before joining wynncraft
