### ISSUE TITLE
Villagers Are too Greedy to Fix Their Doors

### ISSUE THREAD

**Issue by Endeh** [Wynncraft/Issues#4916]
So I was walking up to gavel for the first time for my archer and this happened xD,
https://gyazo.com/6a27936c879eae81cc0a480536a25154
I assure you, this isn't a client side glitch, I am standing INSIDE the chunk of the door missing with out and screen spasms or anything on my side
This is on Server 3.

**Comment by Trixter313** [comment]
Once the server restarts it will be fixed. Thanks!
