### ISSUE TITLE
All My Stuff Is Gone

### ISSUE THREAD

**Issue by xNiGhTMaResSx** [Wynncraft/Issues#4919]
i logged off with 8 soul points in a safe area and i logged back on and all my stuff and emeralds were gone

**Comment by thecoolkogut4** [comment]
how many soul points did you log back in with?

**Comment by VinnyLegend** [comment]
i have the same problem

**Comment by YunoFGasai** [comment]
this is a supplicate of #4814 please refer any and all comments to the original thread
