### ISSUE TITLE
Pirate Town again

### ISSUE THREAD

**Issue by 31Yoshi31** [Wynncraft/Issues#4920]
Hey, the original thread says that this was fixed but there are still no bank npcs and ID.

![2016-04-30_15 29 29](https://cloud.githubusercontent.com/assets/11230645/14936119/9150ecca-0ee8-11e6-850c-91ef9906c233.png)
![2016-04-30_15 29 41](https://cloud.githubusercontent.com/assets/11230645/14936120/96b5df5e-0ee8-11e6-92e4-b58489055a13.png)

**Comment by AckroWynn** [comment]
The map has not yet been updated.
@Trixter313

**Comment by Trixter313** [comment]
As AckroWynn said, it has been fixed on the build server but hasn't been pushed to the playing server yet.

It should be fixed for players soon! =)
