### ISSUE TITLE
Potion making Quest

### ISSUE THREAD

**Issue by Desne153** [Wynncraft/Issues#4921]
I cant complete the quest but i habe all items i need.
![2016-04-30_15 40 24](https://cloud.githubusercontent.com/assets/15544400/14936294/5fc238b0-0eea-11e6-9914-cffeb2f85de5.png)
![2016-04-30_15 40 30](https://cloud.githubusercontent.com/assets/15544400/14936295/63c6031a-0eea-11e6-92a1-bff137f781e5.png)

**Comment by Trixter313** [comment]
Do you have the 16 bonemeal and 8 bat ears? In your screenshot it looks like there's only 3 bonemeal there. Thanks!

**Comment by hihock** [comment]
it's becuz of the potions prob i heard this issue before it's becuz u can't obtain lvl 1 potions now (i think not 100% sure) so i think you cant do that quest

**Comment by thecoolkogut4** [comment]
what is your IGN?

**Comment by Moe-Ronickah** [comment]
1. The quest requirements are "Bring back 8 bat ears, 16 bone meal and 3 potions of healing I to The Assistant".  You must have all of the items at once in order to complete the quest.  **You do not need 16 potions.**

2. Entity radar is illegal.  Turn it off.  Play fair.

**Comment by XavierEXE** [comment]
This seems to not be an issue with the server itself, @Moe-Ronickah close?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
