### ISSUE TITLE
Fix the skill point glitch

### ISSUE THREAD

**Issue by HeroicaIIy** [Wynncraft/Issues#4922]
# Delete this line if you've searched for a duplicate issue first
The skill point glitch.. it makes you skill points all to 0 when entering a world.
I lost a few of my armors like my memento and my electrocharged greaves because my inventory was full and i was stupidly in a corner (items went through a block into a place i couldnt get to)
Im not asking for my items back but i would like this glitch to be fixed.

**Comment by Trixter313** [comment]
Duplicate of #4120 

Please direct any future comments to the original thread. Thanks!
