### ISSUE TITLE
Stuck In a wall After Teleporting 

### ISSUE THREAD

**Issue by Barpli** [Wynncraft/Issues#4923]
After Been doing some quest, and had to use the Teleporter. 
After teleporting i get stuck in a Hole, in the wall This is happening to my for the second time
first i did think it' was a one time Thing but this time it happen again.  I hope You guys can Fix it
(It' happen in the Green skinned trouble After killing the Orc' Boss )
![2016-04-30_15 44 28](https://cloud.githubusercontent.com/assets/14335339/14936391/e239b812-0eeb-11e6-81c4-45439d858495.png)
![2016-04-30_15 47 30](https://cloud.githubusercontent.com/assets/14335339/14936392/eccdb760-0eeb-11e6-8e85-9e6cdb895bae.png)

**Comment by Trixter313** [comment]
Does it happen if you try doing it on another world? Thanks!

**Comment by IceMephit** [comment]
I want to comment a similar issue; after my character died and I respawned, I respawned in the floor with no way to get out.  I hope this gets fixed for future players, as I will not be playing again.

My character died in the first cave, where you save the soldier.

**Comment by Villageacules** [comment]
@Barpli are you still having this issue? Closing the issue, if you are still having problems tag me @Villageacules and we'll address this.
