### ISSUE TITLE
Stuck In Invisible Blocks

### ISSUE THREAD

**Issue by DJGILGA** [Wynncraft/Issues#4924]
# I am Stuck

I was trying to get to Thomas for the Creeper Infiltration quest so i scaled the mountain and i uncounterred some invisible blocks and so i went towards the entrance of Pigmens Ravine and i used the Teleport spelll and got stuck in a air space between some of the invisible blocks i also cant use any of my scrolls to teleport to other villages
![2016-04-30_10 32 48](https://cloud.githubusercontent.com/assets/18752958/14936959/0314476e-0ebf-11e6-92ca-d3ea1da3637d.png)
![2016-04-30_10 32 57](https://cloud.githubusercontent.com/assets/18752958/14936963/0aa51cc4-0ebf-11e6-909d-abe38e8a6a53.png)

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out. Thanks!
