### ISSUE TITLE
Texture buged

### ISSUE THREAD

**Issue by alantara1000** [Wynncraft/Issues#4925]
![2016-04-30_16 42 15](https://cloud.githubusercontent.com/assets/18755235/14938202/9b53e7d6-0ef2-11e6-85d7-0e91371698f6.png)

**Comment by alantara1000** [comment]
help me pls.
I'm whith forge but i want to continue with it and fix this bug

**Comment by Trixter313** [comment]
What version of Minecraft are you using and does the issue happen without forge?

**Comment by alantara1000** [comment]
1.9 
no it dosnt happens without forge but i want the minimap

**Comment by Picklechill** [comment]
Same issue for me I've done it in 1.9 , 1.8 and have deleted my texture files, same issue
![2016-04-30_18 25 36](https://cloud.githubusercontent.com/assets/18756448/14938901/a5d6398e-0f01-11e6-814d-bfe308afb435.png)
![2016-04-30_18 26 01](https://cloud.githubusercontent.com/assets/18756448/14938902/a5d6c4da-0f01-11e6-8cd7-07a848002630.png)

**Comment by Picklechill** [comment]
This is in vanilla and i tried optifine soooooo idk what to do, it is really annoying

**Comment by Moe-Ronickah** [comment]
1. There are some issues with the texture pack at this moment, especially in 1.9.  Try reverting to 1.8.9.

2. If your minimap has entity radar on, turn it off.  It is against the game rules.  Play fair.

**Comment by Moe-Ronickah** [comment]
Aaaaaand, Forge 1.9 is apparently having some issues with Wynn, also.  Try Forge 1.8.9 and MC 1.8.9, together.
