### ISSUE TITLE
Horse glitched away, lost.

### ISSUE THREAD

**Issue by pizzagirl1228** [Wynncraft/Issues#4926]
Yesterday i was just traveling aroung by my brown 10/10 horse, but then minecraft bugged and i couldn't use a or d(move left/move right) or t (chat) i could still move forward and move my cursor. I disconnected and relogged, but when i came back online my horse was just gone, it wasn't in my inventory anymore, and it didn't get replaced. I told my friend the story and he gave me a black 17/20 horse, because he just got a chestnut and he didn't need it anymore. Because there was a chance that i could've dropped my brown horse, i changed the control to some place i can't reach on my keyboard, to be sure i couldn't drop it. It went well for 2 hours, but after that minecraft bugged again, the same way, and my black horse disappeared just like my brown one had. It didn't get replaced too. I tried searching for it, i relogged countless times, but nothing helped. Does anyone know hownthis could have happened? Thanks if you answer this.

**Comment by thecoolkogut4** [comment]
are you on 1.9 or 1.8? does anyone have access to  your account that might of taken you horses? when your game froze, did your computer also freeze at the same time?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
