### ISSUE TITLE
Unable to resummon horse

### ISSUE THREAD

**Issue by CrashTC** [Wynncraft/Issues#4927]
The title pretty much explains it. I've tried relogging, using different version of 1.9, entering different worlds, etc. The problem has persisted over several weeks.

**Comment by TrashcanMan** [comment]
Try using 1.8, 1.9 is pretty buggy right now.

**Comment by Andy0132** [comment]
If you're determined to use 1.9+, spawn your horse about 5 blocks away from you, while you are on a flat ground, and the area you are spawning your horse in is also flat ground.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
