### ISSUE TITLE
Compass stuck in bank!

### ISSUE THREAD

**Issue by Ligaligi** [Wynncraft/Issues#4928]
https://cloud.githubusercontent.com/assets/15972250/11412859/5ceaaf30-939f-11e5-8ada-1eded8bb5ed1.png

This compass has been stuck in my bank since like 2 years ago and it really pisses me off because I can't make it look nice, plus it wastes space! plz help. D:

**Comment by Trixter313** [comment]
Duplicate of #3147 

Please direct any future comments to the original thread. Thanks!
