### ISSUE TITLE
Mysterious wood log

### ISSUE THREAD

**Issue by antoinedjazz** [Wynncraft/Issues#4929]
I've found a wood log near the Maro Peaks, he is alone, attached to nothing !

Loc: 251 34 -3822

[Image](https://i.gyazo.com/7d873caef0944aedcedbe4ee774dc9d9.png)

**Comment by YunoFGasai** [comment]
@AckroWynn can you take this down on the build server?
also you aren't allowed to use entity radar on your minimap, please turn in off in the settings.

**Comment by AckroWynn** [comment]
Fixed!

**Comment by Trixter313** [comment]
You can expect to see the fix when the next map update occurs. =)
