### ISSUE TITLE
Horses spawning issues

### ISSUE THREAD

**Issue by T0onLink** [Wynncraft/Issues#4931]
For some reason it is hard to spawn horses.
When ever I try to spawn mine. It immediately despawns. I have to keep right clicking to get it to respawn.

**Comment by Mushrooooooooom** [comment]
I find it helpful to jump while summoning a horse

**Comment by YunoFGasai** [comment]
Try using version 1.8 in case you are using 1.9

**Comment by thecoolkogut4** [comment]
if you try to spawn in a horse in 1.9 its really glitchy (half the time it does not spawn and when you ride it, it gets messed up) i recommend you switch to 1.8 if you need to use a horse frequently.

**Comment by DarkDemonDragon** [comment]
I recommend 1.8 in general unless you're bored and want to see how glitchy 1.9 can be.

**Comment by YunoFGasai** [comment]
is the issue resolved?

**Comment by Villageacules** [comment]
@T0onLink Are you still having problems? I'm going to close the issue, if you are still having problems and/or didn't resolve the issue tag me @Villageacules and we'll address this.
