### ISSUE TITLE
Cleared hotbar

### ISSUE THREAD

**Issue by Mushrooooooooom** [Wynncraft/Issues#4932]
# Delete this line if you've searched for a duplicate issue first

I was just grinding with my wand (Olux's Prised Wand) which was the only thing in my hotbar and then suddenly my wand just vanished, idk what happened but all i know is im never retrieving it :( :( :(

Rip my best wand :( :( :(

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so no matter what there's nothing we can do about the lost item unfortunately.

You must likely just dropped the item. There's nothing that points to anything else happening. To prevent it form happening again, I'd suggest changing your drop key to something you're less likely to accidentally press. Thanks!
