### ISSUE TITLE
I lost skill points please help

### ISSUE THREAD

**Issue by TheFlyingUkely** [Wynncraft/Issues#4934]
So I had my Dexterity and Strength at 20 but for no reason they were reverted back to 18 and most likely my other skills, this is a HUGE inconvenience if anyone has a solution please leave a comment. :)

**Comment by TrashcanMan** [comment]
Did you switch armor or accessories? Some items provide skill point boosts, so if you took them off then the boosts are gone. If not, doing /class, restarting Minecraft, etc. should fix it.

**Comment by TheFlyingUkely** [comment]
Haha yeah it was an armor piece I'm stupid
