### ISSUE TITLE
Grave Digger- Quest bug

### ISSUE THREAD

**Issue by Rytrex03** [Wynncraft/Issues#4935]
I do not know if it is already known of or if it is this way for a reason but in the last instance of the 
quest " Grave Digger " in the graveyard Saints Row near Nemract, Slayruos's brother dose not spawn 
making the quest uncompleted and I just wanted to adresse this in the forums page if it is indeed a bug 
in the quest.
-Thank you 
_Rytrex_

**Comment by TrashcanMan** [comment]
Try switching servers, sometimes one or two servers glitch out.

**Comment by Moe-Ronickah** [comment]
When you switched servers, did Sayleros's brother spawn, were you able to complete the quest?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
