### ISSUE TITLE
Horse Breeding

### ISSUE THREAD

**Issue by ItzGhostBruh** [Wynncraft/Issues#4936]
I was attempting to get another Chestnut horse, as I was breeding my Chestnut became a Brown. I made sure I wasn't breeding that horse with a Brown but when I got done I looked for it to ride back, I didn't see it. Is there anyway to roll my inventory back or something? I am actually wondering.. If it is a few months ago I didn't have it then. I got it a week or less ago and now it poof.

**Comment by thecoolkogut4** [comment]
so you put a chestnut horse in the crafting slots in your inventory and it turned brown? or you put 2 chestnuts together and it turned to a brown horse? or did you put 2 blacks together, and your chestnut lets say was in your hotbar and the chestnut turned into brown? can you please be more specific?

**Comment by ItzGhostBruh** [comment]
>  did you put 2 blacks together, and your chestnut lets say was in your hotbar and the chestnut turned into brown

That is what happened, but it wasn't the one I just breed. I lost the one I got about a week or so ago.

**Comment by thecoolkogut4** [comment]
so you bred 2 black horses and got horse X, then a week later your original chestnut turned brown?

**Comment by ItzGhostBruh** [comment]
When I attempted to breed again.

**Comment by YunoFGasai** [comment]
I'd say it's the same thing that happened to me yesterday, I tried breeding horses and accidently bred my chestnut with a brown resulting in a brown horse.
when breeding horses make sure your own horse is not in your inventory as you can mistake it for a different tier.

**Comment by Moe-Ronickah** [comment]
I'm sorry, but Wynncraft has an absolute no-refunds policy.  As such, you cannot get your horse back.  Further, it would require rolling back the entire server, and everyone else's progress, to roll anything back.  That, obviously, isn't going to happen.
