### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by Rainbowro** [Wynncraft/Issues#4937]
When I try to buy a +vip rank it looks like a photo it will provide after this. This problem has happened before and did steps they told me again.

**Comment by Rainbowro** [comment]
http://imgur.com/9hZ0MEf
http://imgur.com/vELQYH1
These are before and after pictures

**Comment by thecoolkogut4** [comment]
http://store.wynncraft.com/category/241622 <-- use that if the default store on wynncraft.com is not working. your second screenshot does not work so im not exactly sure what the problem is.

**Comment by Rainbowro** [comment]
That worked thanks
