### ISSUE TITLE
1x1x2 "hole"

### ISSUE THREAD

**Issue by iruleyousuck** [Wynncraft/Issues#4938]
While teleporting around the canyon of the lost I somehow got myself stuck in a 1x1x2 "hole" in the barrier. (X: 510, Y: 148, Z -5589) not a major issue but and issue. (I can /die)

**Comment by thecoolkogut4** [comment]
are the blocks broken? or are you just glitched inside of it (while the blocks are still there)

**Comment by YunoFGasai** [comment]
Reported to the filling holes thread.

**Comment by DarkDemonDragon** [comment]
@AckroWynn can you easily fix this?

**Comment by YunoFGasai** [comment]
fixed on the build server by blackbirdmc

**Comment by Trixter313** [comment]
Great, thank you!
