### ISSUE TITLE
Forum Register Bug

### ISSUE THREAD

**Issue by HypdUp** [Wynncraft/Issues#4940]
Hello, I have a bug where whenever I try to register for the Wynncraft forums it keeps saying invalid minecraft username but I know as a fact my username and I started playing on it you can check that my minecraft username is indeed HypdUp, Ive tried all capital letters all non capital letters and still nothing, always says invalid minecraft username, my friend had made an account and it worked for him, he used his normal minecraft username and it worked. Please help me I want to interact with the community on the forums :/

**Comment by YunoFGasai** [comment]
Lately there has been a bug on the wynncraft forums side, the issue is known and I'm sure our web admin is taking care of it.
We tested this with other xenforo forums so we know the problem is with wynn.

**Comment by HypdUp** [comment]
Oh ok great, thanks so much for replying so quick :) any idea when it will be fixed?

**Comment by YunoFGasai** [comment]
no idea, I'm not in contact with the web admin at all.

**Comment by HypdUp** [comment]
Ok no problem, thanks for the help :)

**Comment by YunoFGasai** [comment]
I'm pretty sure that it got fixed. (It's not yelling at me anymore that my ign is invalid)

**Comment by Trixter313** [comment]
Can you confirm whether the issue is fixed or not for you @HypdUp ? Thank you!

**Comment by HypdUp** [comment]
Yeah its fixed

**Comment by Trixter313** [comment]
Glad to hear! =)
