### ISSUE TITLE
These items are glitched and didn't update with the update.

### ISSUE THREAD

**Issue by InfectedAsylum** [Wynncraft/Issues#4942]
So I have run into this issue and after searching through a couple of pages of bugs, no one seems to have a similar problem. I have a couple of items that still have the old stats of a previous version of Wynncraft, They are currently un-sellable please help me with this issue.
Here are screenshots of the items in question:
![2016-05-03_17 44 43](https://cloud.githubusercontent.com/assets/19178301/15002586/8a6c49d8-1157-11e6-9085-922631982ecd.png)
![2016-05-03_17 44 42](https://cloud.githubusercontent.com/assets/19178301/15002588/8e0f3fd2-1157-11e6-9868-b241f0db397f.png)

**Comment by Trixter313** [comment]
https://github.com/Wynncraft/Issues/issues/3161 is the original issue.

To summarize it, you can keep the items if you want or you can just throw them out. It's not happening with new items and was just a one time issue that occurred in the update to Gavel. Thanks!
