### ISSUE TITLE
Ice Snake Information tab (website)

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#4943]
If you go to the main website, and view the information tab for Ice Snake, the first tier is missing damage information. I'm fairly sure it does do damage due to a let's play I watched (released today), where someone kills a mob with it.

**Comment by thecoolkogut4** [comment]
was his level under 46?

**Comment by Moe-Ronickah** [comment]
@awemanrank100 , do you remember whose Let's Play it was, and what the topic was?

**Comment by awemanrank100** [comment]
@thecoolkogut4 @Moe-Ronickah 

Uhp. Sorry for not responding; I don't come here often.
https://www.youtube.com/watch?v=9IAuQzubszQ

**Comment by YunoFGasai** [comment]
@awemanrank100 he doesn't kill anything with ice snake there, that's the damage from his friend's arrow shield.

**Comment by awemanrank100** [comment]
@YunoFGasai Actually, if you slow it down a bit, you can see that the Arrow Shield is still intact, and the 0 XP went to the user of the Ice Snake. However, I realized he used Meteor before Ice Snake, so that could be it. Not sure, though.

**Comment by Trixter313** [comment]
What was the level of the Mage in question? Burning ground for Meteore is unlocked at level 56.

**Comment by YunoFGasai** [comment]
I'm power leveling a mage just for this.

**Comment by awemanrank100** [comment]
@Trixter313 31. Said Mage used Ice Snake just after leveling.

**Comment by YunoFGasai** [comment]
I can confirm ice snake is doing damage at tier 1

**Comment by Moe-Ronickah** [comment]
@awemanrank100 , you can pass this along to Elements on the forums, or I can do it.  If you do it, tell him that I asked you to go ahead and pass it along, and reference this issue.

**Comment by awemanrank100** [comment]
@Moe-Ronickah You do it. :I

**Comment by Moe-Ronickah** [comment]
@awemanrank100 , LOL.. OK, I'll tell him.
