### ISSUE TITLE
Quest items missing

### ISSUE THREAD

**Issue by TheProfessor53** [Wynncraft/Issues#4944]
# Delete this line if you've searched for a duplicate issue first
There were too many quest items, so i threw some out of my inventory, but now i need the water breathing helm, and i dont know how to get it back

**Comment by TrashcanMan** [comment]
Try doing /fixquests, it should return any missing quest items. If this resolves your issue, please close it. Thanks, and have a nice day!

**Comment by Trixter313** [comment]
Also if that doesn't work you can do the quest on another class and put the helmet in your bank to get it to your main class. It's a lower level quest luckily if you do need to resort to that.
