### ISSUE TITLE
1.8 to 1.9 (and the other way) Resource Pack bug

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#4945]
If you play on 1.9, the resource pack you get is permanently locked onto 1.9's "fixed" pack (so textures aren't strange on 1.9). This causes 1.8's textures to look strange (models are tilted, Soul Points are error blocks, and maybe some other stuff). I have attempted deleting server resource packs; it doesn't work.

**EDIT:** I've found a temporary fix for the issue. By switching to version 1.8, precisely (other versions that may work are unknown to me; I have not tested), it reverts back to the 1.8 version, where you can then go back to whatever 1.8.x version of Minecraft you were using, without the server using the 1.9 pack.

**Comment by YunoFGasai** [comment]
thanks for finding a fix, that saved us a lot of time.
can someone close this issue?
