### ISSUE TITLE
Resource pack bug

### ISSUE THREAD

**Issue by 448858y** [Wynncraft/Issues#4946]
I have a voxel's minimap and i use liteloader, but i tried pure 1.9 vanila and still the grass is bugged
http://puu.sh/oFTNk/6a6714c902.jpg

**Comment by YunoFGasai** [comment]
1.9 is bugged, try using 1.8 instead

**Comment by thecoolkogut4** [comment]
same thing happend to me, but 1.9 its fine and 1.8 texture pack is messed up. (i think its because they updated the pack to work in 1.9) but an effect was that it changed things up on how it looks in 1.8

**Comment by Moe-Ronickah** [comment]
@448858y , aside from whatever error is affecting the resource pack, you have your minimap set to show entities.  That is, your radar is on.  That is a very big no-no, as in, it is a bannable offense.  TURN OFF THE RADAR.

Check today and see if you are still having bugs with the resource pack - it may have already been fixed.  Let us know if it's still buggy for you in 1.8 or 1.9?  Thanks.

**Comment by 448858y** [comment]
I didn't use it in any way because there is no minimap for 1.8 and the resource in 1.9 was unplayabe. So thank you for warrning me

**Comment by Moe-Ronickah** [comment]
First, your link, http://puu.sh/oFTNk/6a6714c902.jpg, clearly shows player entities turned on, and those are a no-no.  NO radar is allowed.

Second, there have been some recent updates in the past week that you might want to look into.  Forge 1.8.9 and LiteLoader 1.8.9 are both out and stable.  Optifine 1.8.9 and VoxelMap 1.6.7 for MC 1.8.9b work just fine together.  I'm using all four, and there have been no problems, in MC 1.8.9.
