### ISSUE TITLE
Instantly going down to 1 hp

### ISSUE THREAD

**Issue by Lionkingx999x** [Wynncraft/Issues#4947]
Its an issue of a friend of mine. But if he joins or is just walking around hes loosing life every second until he has only one hp left.

**Comment by YunoFGasai** [comment]
does he have any armor pieces with negative health regen?

**Comment by Lionkingx999x** [comment]
no this also happens with no armor on and no item in hand

**Comment by DarkDemonDragon** [comment]
Some screenshots of his stats would be necessary to confirm if this isn't caused by an item.

**Comment by Andy0132** [comment]
Are they wearing any accessories?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
