### ISSUE TITLE
This isnt a Bug Report but I have no where else to post this because of the forum bug

### ISSUE THREAD

**Issue by HypdUp** [Wynncraft/Issues#4948]
As the title says I am very sorry for posting this on here but its urgent and I cant post on forums since I cant register due to the invalid minecraft username bug. I recently donated for VIP on my 2nd account and I had no idea that was the account I did it on, up until I checked my email for my 2nd account. I have the email and also the paypal transaction ID, I was tempted to do a dispute to refund the money, but I thought I would post here instead first to see if there is any way to transfer my VIP and benefits/items I got from my 2nd account If I show all the proof of the purchase. Im sorry for making it a hassle for you guys but I made a mistake :(. Thank you so much for taking your time and looking at this post and again I am sorry for posting this onto here.

**Comment by thecoolkogut4** [comment]
dont quote me on this, but if you email support they might transfer the rank & ban the other account. but youd need to have all the proof (which looks like you have).

**Comment by HypdUp** [comment]
@thecoolkogut4 Ah ok thanks for the reply, also I know you said dont quote you but any idea if they actually ban the other account? or can they just take away the VIP rank and benefits/items? Since I would like to still be in contact with my guild to change it to my main.

**Comment by thecoolkogut4** [comment]
an old admin told me in the hub one day that they would ban the account with VIP and give it to the new acc.  ever since then i never heard anything about it.

**Comment by HypdUp** [comment]
@thecoolkogut4 Ah ok, thanks a lot for the information!
