### ISSUE TITLE
Texture bug report

### ISSUE THREAD

**Issue by seco31** [Wynncraft/Issues#4949]
**screenshot here**
http://imgur.com/a/fGEEz

**Comment by TrashcanMan** [comment]
If you're using 1.9, go back to 1.8 for now. Although 1.9 is technically supported, it has quite a few issues.

**Comment by seco31** [comment]
1.8 screenshot
http://i.imgur.com/HqUkIP0.png
lol

**Comment by seco31** [comment]
1.8 screenshot
http://i.imgur.com/HqUkIP0.png

**Comment by YunoFGasai** [comment]
#4945

**Comment by YunoFGasai** [comment]
try following that issue
