### ISSUE TITLE
Rising of the quartron

### ISSUE THREAD

**Issue by St0nedHenge** [Wynncraft/Issues#4951]
I was at the end of the quest and i finished it at Nassea but he gave me 4096 emeralds but it was not in my inventory what should i do ?

**Comment by thecoolkogut4** [comment]
you should check your inventory for it, as it wont let you finish a quest with a full inventory (you must have space for the money when you finish a quest), if you  picked up an item while the NPC was talking which made you inventory full then the LE is gone.
