### ISSUE TITLE
u

### ISSUE THREAD

**Issue by Fire-Mage-Mai** [Wynncraft/Issues#4953]

**Comment by Fire-Mage-Mai** [comment]
Sorry using my phone, but I haven't been able to use the teleportation scrolls because I don't have the soul points but my soul points are always full and it can't be because of my level because I used one when I was a lower level. I would kindly like some help please

**Comment by DarkDemonDragon** [comment]
Please provide some screenshots or a video recording or what happens when you attempt to use a scroll.

**Comment by thecoolkogut4** [comment]
when you use the scroll, try to break grass with it. that sometimes helps you get tp'ed.

**Comment by Fire-Mage-Mai** [comment]
No the point was that I couldn't tp at all but a friend of mine fixed the issue...they got on my account to see if they can record what's going on but before he tested to see if he can do it and guess what..it worked of course then I got back on it and it works again...geez I swear makes it seem like I was lying but I wasn't but thank you anyway for take the time to read it and try to help

**Comment by DarkDemonDragon** [comment]
No its fine. Most likely you were using the scroll on the block. Scrolls only work when used on the air. Glad to hear your issue was resolved ^-^
