### ISSUE TITLE
IDs With Value of -1 Sometimes Won't Apply

### ISSUE THREAD

**Issue by NumberSoul** [Wynncraft/Issues#4955]
When identifying items that have an identification with an "average" value of -1 (examples include Mind Rot, Clock Leggings, Mythical Trousers, Changeling's Chestplate, etc.), that identification will sometimes seem to roll a 0 and not appear in the list of the item's identifications. As a simple example, I collected screenshots of two different "Mind Rot" helmets.

![2016-05-06_13 35 18](https://cloud.githubusercontent.com/assets/9507302/15083109/0d7fdc96-1391-11e6-8e18-a55e3dc0c86a.png)
This one very clearly has -1/4s Mana Regen...

![2016-05-06_13 35 19](https://cloud.githubusercontent.com/assets/9507302/15083111/10814862-1391-11e6-9f1f-22621f5b5793.png)
But this one does not...

When I first discovered this, I thought it was an intended consequence of game mechanics. But according to a short conversation I had with Selvut, this should not be happening.

**Comment by Creecreeprs** [comment]
I have the same thing with snail chestplate and I think it's not bug

**Comment by Odnod** [comment]
It has to do with the ranging. The base mana regen on those items is -1, so it can go from 0 to -2 mana regen as far as I know.

**Comment by Moe-Ronickah** [comment]
How do you display 0/4s Mana Regen?

**Comment by YunoFGasai** [comment]
@Moe-Ronickah according to the screen shots it doesn't display it at all.

**Comment by Moe-Ronickah** [comment]
RESOLVED
