### ISSUE TITLE
Mounts Glitching Out

### ISSUE THREAD

**Issue by Devdiablooper** [Wynncraft/Issues#4957]
The boats and horses glitch out when i and a couple of my friends ride them, 
we are somewhere else than what we see.
this is a sample:
F1 is following F2 on a boat on her screen, but F2 doesn't see F1 next to him, and when F1 jumps out of her boat, she gets teleported to where her body actually is.

pls fix the glitch.

**Comment by YunoFGasai** [comment]
I'm pretty sure that it has to do with your internet connection so nothing we can do about it (unless it happens because of lag)

**Comment by Devdiablooper** [comment]
nah i've tested it with multiple people and they all say the same.

**Comment by Devdiablooper** [comment]
nah i've tested it with multiple people and they all say the same.

i've even tested it with someone from israël.

**Comment by YunoFGasai** [comment]
I'm in Israel and the only time I experienced something like this was pre gavel. (I also upgraded to a better computer back then so that might be to blame). 
Either way this issue is a duplicate, I'll reference the original in a minute.

**Comment by YunoFGasai** [comment]
#4907

**Comment by YunoFGasai** [comment]
Sorry #4809

**Comment by Moe-Ronickah** [comment]
@Devdiablooper , are you using 1.9?  If you are, try it in 1.8, please, then get back to us and let us know what happens.

**Comment by Devdiablooper** [comment]
@Moe-Ronickah it seems that the glitch only aplies to 1.9 and higher. because in 1.8.9 and lower i can travel with the mounts, it sometimes stops for a millisecond because it needs to load the chunks but it's pretty much fixed.

so... thanks!
