### ISSUE TITLE
Soul Points

### ISSUE THREAD

**Issue by KoalaGamer** [Wynncraft/Issues#4958]
I have 1 soul point on my level 44 archer and I'm am offline waiting to regen soul points but they aren't regening

**Comment by YunoFGasai** [comment]
I think that when you're offline you only regen one per hour.
Also I'm not sure if the sp regen identification effects offline regen but if it does check your armor and accessories for -sp regen items and un-equip them.

**Comment by KoalaGamer** [comment]
Ok thx
