### ISSUE TITLE
Glitched Item

### ISSUE THREAD

**Issue by Kra3tys** [Wynncraft/Issues#4959]
I was playing on Wynncraft, doing the Aldorei's Secret quest, about to give the Sunblight Boots to those two guys, but then there was a lag spike and i timed out. Unfortunately i had already given the boots, and left before any dialogue could happen. I am now stuck, with no boots, and no way to complete the quest.

**Comment by YunoFGasai** [comment]
Try going through all the stages of the quest again. 
If that doesn't work try /fixquests

**Comment by Andy0132** [comment]
/fixquests should fix the issue, as the boots have been given. Furthermore, if you've already given the boots to one of the elves, you will recieve the medallion/receipt.

**Comment by Trixter313** [comment]
Could you let us know of /fixquests fixed the issue or not? Thank you!

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
