### ISSUE TITLE
Keep Getting Kicked Off Server

### ISSUE THREAD

**Issue by JediArcanaan** [Wynncraft/Issues#4960]
I log onto Wynncraft, and about 30 seconds later, I get kicked off with a message saying, "An existing connection was forcibly closed by the remote host."
I have checked my internet connection, and it was fine, so that is not the problem I don't think. Also, my laptop is in perfect condition, so that is not the cause either. I have also repeatedly quit minecraft altogether and rebooted it, but I get the same result. Please fix it, would be greatly appreciated.

**Comment by thecoolkogut4** [comment]
what IP are you using to connect to the server? could you go to http://www.speedtest.net/ and tell me what you ping, upload and download speed is? Did you give someone else access to  your account recently?
