### ISSUE TITLE
[BUG] Fieré weapon is not updated to Gavel

### ISSUE THREAD

**Issue by DerpyBush** [Wynncraft/Issues#4961]
My fieré weapon is still the old way, with the minimum lvl, de damage amount in purple, no extra bonusses, just like before Gavel. Does someone know what to do with this? [Picture](https://gyazo.com/30aa99517cf2aebb60b2478674892393)

**Comment by Place-Name-Here** [comment]
This is a known bug any item with a é wasn't updated to Gavel it's wierd but it's how it is. :/

**Comment by YunoFGasai** [comment]
You are allowed to keep it but I'm not sure about trading it, it's just a useless item now so you can either keep it or throw it away.

**Comment by DarkDemonDragon** [comment]
@DerpyBush when was this Fierte obtained? Before or after Gavel?

**Comment by Moe-Ronickah** [comment]
Dark's question is the most important one; is the item new, post-Gavel, or old, pre-Gavel?

**Comment by DerpyBush** [comment]
@DarkDemonDragon @Moe-Ronickah It was obtained before Gavel. ;D So it probably didn't update itself. By the way thanks for the answers everyone! ;D

**Comment by Trixter313** [comment]
Ah, please refer to issue https://github.com/Wynncraft/Issues/issues/3161 then. It explains the issue in detail.

Basically you can keep or throw out the item or whatever you want to do but rest assured it won't happen to you again. Enjoy your time playing Wynncraft!
