### ISSUE TITLE
Graphical bug

### ISSUE THREAD

**Issue by MDLuffy94** [Wynncraft/Issues#4964]
Hello there,

I have bugs when I am using my favorite map mod VoxelMap.
I got some texture errors, there is a screen of the probleme
http://i86.servimg.com/u/f86/17/22/99/08/2016-010.jpg

How can I solve this ?

I'm on MC 1.9 with Forge and LiteLoader installed

**Comment by YunoFGasai** [comment]
try switching to 1.8

**Comment by MDLuffy94** [comment]
It's working thanks

**Comment by thecoolkogut4** [comment]
turn off your radar, its against the rules.

**Comment by YunoFGasai** [comment]
> turn off your radar, its against the rules.

what kogut's is saying is that the entity radar is against the rules, you can keep the map.

**Comment by Moe-Ronickah** [comment]
"A Word to The Wise: As of 5/8/2016, if you post an image that shows that you have entity radar turned on in a minimap, that information may be passed on to the game moderators, without further notice to you. Play Fair!"
