### ISSUE TITLE
Crashed while download server resource pack

### ISSUE THREAD

**Issue by aira1101** [Wynncraft/Issues#4965]
I crashed while I relog the server and it suddenly ask me to download server resource pack , then my game crashed
is there anyway to debug or something to fix it?
I tried to reinstall my minecraft but it still happened after I login a few times :(
plz help me ;-;

**Comment by Moe-Ronickah** [comment]
Right now, you will just have to wait and try again in an hour or so.  The servers are all down, at this moment.

**Comment by aira1101** [comment]
@Moe-Ronickah I know but its still not work when I download the resource pack

**Comment by Trixter313** [comment]
Is your issue still occurring or has it been resolved? Thanks!

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
