### ISSUE TITLE
Typo in Finding the Light

### ISSUE THREAD

**Issue by GaPoiVN** [Wynncraft/Issues#4966]
so Im doing the quest "Finding the Light" , and then I found this typo
http://imgur.com/z1DDdpP
"Sasha: Look, that’s the price. I CAN' change it. It’s all safely stored in my basement."
I think that should be "can't" , not "can'"

**Comment by Endeh** [comment]
Duplicate of #4692

**Comment by Trixter313** [comment]
Ah, nice catch. Please direct any future comments to the original thread. Thanks!
