### ISSUE TITLE
I Lost all my stuff

### ISSUE THREAD

**Issue by ILikeYellowSnow** [Wynncraft/Issues#4967]
I Played for a few hours on the wynncraft server i still had 3 soulpoints than i logged out and when i logged on the next day i lost all my stuff please help me getting my stuff back.

**Comment by YunoFGasai** [comment]
sorry, Wynncraft has a no-refund policy. I'm sure people will be glad to sell you stuff back at your level.
the bug is a known one thus making this a duplicate issue.

**Comment by YunoFGasai** [comment]
this is a supplicate of #4814 please refer any and all comments to the original thread
