### ISSUE TITLE
Glitched Pelier

### ISSUE THREAD

**Issue by Lionkingx999x** [Wynncraft/Issues#4969]
My Pelier (Chain helmet) is glitched because its from older days :yum: 
http://imgur.com/wkhdtC2

**Comment by Lionkingx999x** [comment]
Just like my Devourese http://imgur.com/UmOElN5

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3161

Please direct any future comments to the original thread & read the whole thread. Thanks!
