### ISSUE TITLE
What???

### ISSUE THREAD

**Issue by KawaiiCrafter7** [Wynncraft/Issues#4970]
I just turned lvl 60 and I got a new quest! So I came to the Pirate island and there are no NPCs here only villagers

**Comment by YunoFGasai** [comment]
did you check the cords given in the book?

**Comment by KawaiiCrafter7** [comment]
yes and it said Pirate island

**Comment by KawaiiCrafter7** [comment]
and there were no NPCs

**Comment by KawaiiCrafter7** [comment]
No bank,indentifier...

**Comment by thecoolkogut4** [comment]
try to switch servers? are you sure your at the right Y cord?

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3272

Please direct any future comments to the original thread and read it all. Thanks!
