### ISSUE TITLE
Stuck Reset Profile

### ISSUE THREAD

**Issue by MoreGamesForUs** [Wynncraft/Issues#4971]
# Delete this line if you've searched for a duplicate issue first

Hello, my name is MoreGamesForUs, and I have 2 classes, Archer and Assassin. My archer class is fine, but I'd like to ask you to reset my Assassin class, because my Assassin class is glitched and I can't fix it. It's stuck in blocks, and I tried every possible way to get out but I can't. My IGN is MoreGamesForUs, and I should say I have 2 classes, please delete the "Assassin" class.

Thanks
_**MoreGamesForUs**_

**Comment by thecoolkogut4** [comment]
have you tried /kill?

**Comment by ChocolatyBear** [comment]
./kill will cost 2sp but you will be free.
