### ISSUE TITLE
Shadow of the beast glitch

### ISSUE THREAD

**Issue by Venemian** [Wynncraft/Issues#4974]
I'm at the point where I need to talk to Rileen, and all he says is: 

**[1/1] Rileen: Welcome to our little village!**

Please help I need the xp for this quest and I do not know how to fix. I've logged on and off so much, because I have to anyways, and It wont fix itself. HeLP!

**Comment by thecoolkogut4** [comment]
what does your quest book say?

**Comment by Venemian** [comment]
"follow the footprints to find another victim of the attack"

**Comment by Trixter313** [comment]
Try walking around the paths in areas you've needed to visit for the quest. It's possible that you missed a location-based quest book update that requires you to walk in a certain spot. If you do trigger it, something should pop up in chat such as quest dialogue or a message saying your quest book has been updated. Let us know if that helps at all, thank you!

**Comment by Odnod** [comment]
You may be at the third npc that needs help in the quest. Have you already talked to Kroac?

**Comment by YunoFGasai** [comment]
no response from the OP for 2 months.
