### ISSUE TITLE
Resource pack not loading properly

### ISSUE THREAD

**Issue by Dimetomic** [Wynncraft/Issues#4975]
I joined the server and downloaded your resource pack so that I could play. But I think it doesn't download properly. All the skins for items and blocks are messed up. I've tried deleting the resource pack in the .minecraft file and have never used any other resource pack, when I try it again, it loads properly for a second then bugs out again. I've tried changing some of the video options and such but nothing helps. I've attached some screenshots to help show my problem.
![2016-05-11_23 49 57](https://cloud.githubusercontent.com/assets/19318850/15203586/2c936d28-17d3-11e6-9561-5d3e05f50f76.png)
![2016-05-11_23 50 04](https://cloud.githubusercontent.com/assets/19318850/15203590/31055ea2-17d3-11e6-9067-0ee57301d78f.png)
![2016-05-11_23 50 13](https://cloud.githubusercontent.com/assets/19318850/15203593/348bb1d4-17d3-11e6-928c-58f8ba7aba1e.png) Thanks for any help people can provide. I almost forgot, when I died I lost all my items and my weapon keeps duplicating itself. I am not sure why.

**Comment by Trixter313** [comment]
What version of Minecraft are you using? If it's 1.9, try using 1.8 to see if it helps at all. 1.9 is still very buggy with Wynncraft. Thanks!

**Comment by AThao1** [comment]
Is it lagging? Because sometimes when I lag out on the server my items keep duplicating.

**Comment by Trixter313** [comment]
Closing due to no response.
