### ISSUE TITLE
Bug With Clock - (Lord of the Clock Quest)

### ISSUE THREAD

**Issue by zombiehunterkill** [Wynncraft/Issues#4976]
So i was doing the quest and i gave the guy at the volcano the clock, and now it is glitched. My quest book still says to go to the depths of Mt. Wynn, but i have no clock.. Someone pleasehelp!
Some Screenshots:
![image](https://cloud.githubusercontent.com/assets/19319566/15204505/d5da84cc-17c2-11e6-8e56-2709c853f68c.png)
![image](https://cloud.githubusercontent.com/assets/19319566/15204515/e18d7f90-17c2-11e6-81f4-426283d0312c.png)
Ty for your help <3

**Comment by Trixter313** [comment]
Try using the command /fixquests
Does it return the clock? Thanks!

**Comment by zombiehunterkill** [comment]
OMG THANK YOU SO MUCH

**Comment by zombiehunterkill** [comment]
ILY <333

**Comment by Trixter313** [comment]
Glad to help! =)
Enjoy your time playing Wynncraft!
