### ISSUE TITLE
all my stuff gone

### ISSUE THREAD

**Issue by VinnyLegend** [Wynncraft/Issues#4978]
# Delete this line if you've searched for a duplicate issue first
I logged off in a safe zone with 1 soul and came back and all my armor and everything except my bow was gone but had 11 souls

**Comment by VinnyLegend** [comment]
Plus my skin is gone and some times my skin comes back

**Comment by YunoFGasai** [comment]
this is a supplicate of #4814 please refer any and all comments to the original thread
