### ISSUE TITLE
Lost all my characters, Levels and all.

### ISSUE THREAD

**Issue by theykilledkeny** [Wynncraft/Issues#4979]
well actually, my younger brother lost all his levels and inventory items. he was on my computer but he logged off and immediately after he went to go play on his own computer and had no characters. I have no way of knowing what he had but he just unlocked the bomb spell on his archer and spent a long time playing to earn it.

His username is: theykilledkeny

Since they got reset he has started a warrior account. he didn't get too far though.

**Comment by Trixter313** [comment]
There is a way to reset your classes, right click instead of left click when selecting a class. What most likely happened it someone playing accidentally deleted it.
