### ISSUE TITLE
Zombie hiding in bush has a wand for a hat!

### ISSUE THREAD

**Issue by bob10234** [Wynncraft/Issues#4980]
Screenshot 
![2016-05-12_18 38 56](https://cloud.githubusercontent.com/assets/16420737/15235551/48b15fc6-1871-11e6-832b-c34c0ecbd2d1.png)

**Comment by YunoFGasai** [comment]
well that's cute, @AckroWynn can you fix this on the build server?

**Comment by Moe-Ronickah** [comment]
It's not a wand, it's a stem.  A bush stem.
