### ISSUE TITLE
Zight Island messup 

### ISSUE THREAD

**Issue by Endeh** [Wynncraft/Issues#4981]
so After I talked to Pheif {FOR THE FIRST TIME}, I right-clicked again and it displayed the message after you finish the quest. This is my Second class to do this quests so that may be part of the cause.
https://gyazo.com/d1f859622f8493e8d3f55de3e62b996d

**Comment by Trixter313** [comment]
So did it let you finish the quest or are you stuck on a part and can't progress?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
