### ISSUE TITLE
I cant leave my guild

### ISSUE THREAD

**Issue by Vydros** [Wynncraft/Issues#4982]
I can leave my guild, someone plz help me. i lost 3 souls point but i didnt leave the guild .-.

**Comment by Vydros** [comment]
My minecraft username are _FlamingTiger im gonna change it to _Vydros_ soon

**Comment by Vydros** [comment]
I mean _Vydros_

**Comment by Moe-Ronickah** [comment]
My first question is, did you change your name while in the guild, before it was Vydros?

**Comment by YunoFGasai** [comment]
OP hasn't responded for 2 months, I'd say it was probably the name change bug that glitched him.
