### ISSUE TITLE
Bug at the temple of the legends

### ISSUE THREAD

**Issue by xXxletsplayxXx** [Wynncraft/Issues#4985]
I am at the temple of the legends quest right now, and i already got the helmet which is required to enter the temple. But everytime i want to enter the temple i get pulled back and the npc kelight says:"only the bravest adventurers who succeed in my quest can enter the temple of the legends". i hope you can help me with that. And sorry for my bad english if there are any mistakes.

**Comment by thecoolkogut4** [comment]
what does your quest book say?

**Comment by xXxletsplayxXx** [comment]
@thecoolkogut4 Kill the Corrupter of Worlds and bring a proof of its death to Kelight.

**Comment by thecoolkogut4** [comment]
put on the helmet, and you need to kill CoW. if you go north (i think) of kelight youll see a cave. (the cave is right beside him) go in the cave and all the way at the bottom is a boss you need to fight (CoW). kill him and he drops a slime ball. give the slime ball to kelight to finish the quest (and that will give you access to the temple)

**Comment by xXxletsplayxXx** [comment]
@thecoolkogut4 thx :D i though i was supposed to go in the temple -.- stupid me
