### ISSUE TITLE
Taproot Gltich

### ISSUE THREAD

**Issue by EEopkc** [Wynncraft/Issues#4986]
Hi, so I did the taproot quest and i went up to the point where I was sent to the other side of the taproot and i was confused on what to do... So I ended up wandering around. I was completely lost, so I checked the quest book and it said to take to tiek; however, when I went back to him, he said the same thing he said before I left for the taproot. PLS HELP

**Comment by YunoFGasai** [comment]
There are two tiek's the book is probably talking about the one in the other dimension (you can follow the wiki for help)

**Comment by EEopkc** [comment]
Thanks
