### ISSUE TITLE
Suspended Flowers, can't start dialog with asher

### ISSUE THREAD

**Issue by bob10234** [Wynncraft/Issues#4987]
I get stuck wtih black text everytime I talk with asher, I can't complete this quest because of this bug ;(
Video of it happening: https://www.youtube.com/watch?v=Ma6PMSZSxKE (I added music lol)

**Comment by thecoolkogut4** [comment]
what does your quest book say?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
