### ISSUE TITLE
Lost out on Double XP

### ISSUE THREAD

**Issue by NotTech** [Wynncraft/Issues#4990]
I finished the quest "The Worm Holes" on a Double XP server, and the quest is supposed to give 175000 Xp normally, and around 350000 with double XP. It only gave me 175000 XP instead of the 350000, which I should've been able to level up from. The counter at the top still stated 5 minutes left, so I'm unsure of what happened here.

**Comment by YunoFGasai** [comment]
the chat announcement isn't effected by the double xp but the actual amount of xp you got has doubled.

**Comment by NotTech** [comment]
I am aware of this, but using the xp chart on the wiki, I shoukd have been able to level up through 55 and have around 60% of level 56 completed. Instead, I only got around 70% of level 55, which is around 175k.

**Comment by YunoFGasai** [comment]
I think it also depends on the level gap between you and the quest's intended level, the larger the gap the less xp you'll get.

**Comment by NotTech** [comment]
Shadow of the Beast is a Hard Level 54 quest, I am currently Level 55.

**Comment by YunoFGasai** [comment]
do you have any armor pieces with negative xp bonus?

**Comment by NotTech** [comment]
Nope, I made sure of this then and checked just now as well.

**Comment by Odnod** [comment]
Worm Holes used to give a hell of a lot more experience than it was supposed to, but it got nerfed. My guess is that whoever lowered the amount of xp you get forgot to change the text that tells the player how much they get.

**Comment by Moe-Ronickah** [comment]
Lv53, Death Whistle, 52000 xp.  Lv 54, Shadow of the Beast, 82,500 xp.  Lv54, The Worm Holes, 175,000 xp?!  175,000 is what the Lv67, From the Mountains, quest gives in xp.  No, we need to pass this along to the GMs to find the correct amount of xp given, so the dialogue can be fixed, and the Wiki updated.

**Comment by Moe-Ronickah** [comment]
Confirmed by a GM, it's 60 000, not 175 000.  It was changed in the database, but not in the dialogue.  End of story, the 175 000 is a typo.

**Comment by DarrianProducts** [comment]
So will our quest exp be restored?

**Comment by Moe-Ronickah** [comment]
There is nothing to restore as you received the correct amount of xp; the game was updated.  The quest xp was fixed quite a while ago, however, the dialogue was not fixed, nor was the Wiki.  The Wiki is now fixed, as is the quest dialogue.  The quest dialogue may not change for a while until the changes get pushed through.
