### ISSUE TITLE
Glitched In A Small Hole/In a Wall With a Black Screen After Trying To Leave WynnExcavation Site B's Cave

### ISSUE THREAD

**Issue by Killcode96** [Wynncraft/Issues#4991]
I need a teleport or something this is all i can see I was trying to leave WynnExcavation Site B and this happened 
![2016-05-14_17 16 33](https://cloud.githubusercontent.com/assets/16640598/15270732/78b7fc5c-19f7-11e6-9c45-1d37a2286e5f.png)
![2016-05-14_17 16 33](https://cloud.githubusercontent.com/assets/16640598/15270733/7967a648-19f7-11e6-8b65-4ab18bea51af.png)

**Comment by TrashcanMan** [comment]
Do /kill with at least 3 soul points. If this resolves your issue, please close it. Thanks, and have a nice day!
