### ISSUE TITLE
Item isn't working

### ISSUE THREAD

**Issue by SuicideFalcon** [Wynncraft/Issues#4993]
I wasnt playing Wynncraft for a LONG Time and when I joined my weapon wasnt working anymore...Im a lv.48 magican and my weapon is called Devereuse.It lost all Plugin effects and spells.Its like a normal Minecraft stick but I should have all spells and make more than 0.5 Hearts damage.There also where a lots of new updates for armor and weapons.Maybe it has something to do with them. + (Sorry for my English Im german.Maybe I made some mistakes) This weapon is my ONLY weapon in my ineventory and bank.I cant get a new one because i cant fight against mobs with a useless MC vanilla stick without Wynncraft Plugins.

**Comment by YunoFGasai** [comment]
this is a duplicate issue (not sure where the original is)
this is caused from the fact deveruse has an apostrophe over one of the e's. 
add Yuno Gsai in game, I'll try to grind you a wand for your level.

**Comment by YunoFGasai** [comment]
the original thread is #3175 please refer all future comments to the original thread
