### ISSUE TITLE
Armour Merchant

### ISSUE THREAD

**Issue by 1mccreeper** [Wynncraft/Issues#4997]
# Delete this line if you've searched for a duplicate issue first
I was in the sky islands area and found a Armour merchant by where the sky snails spawn
(996,120,-4844). It seems he does not sell anything.

https://gyazo.com/1392742f304344e6316dd79f350672ba

^^^^
That shows that it doesnt sell armor. It might just be that he is going to sell things in the next update, but if not then here is a merchant who doesnt sell anything.

**Comment by YunoFGasai** [comment]
I've seen that guy on several threads on the forums.
I believe he was created after they designed the new sets but before they decided to make them obtainable only via mob drops.

**Comment by YunoFGasai** [comment]
but that is only my opinion

**Comment by Moe-Ronickah** [comment]
Yuno is correct.  The armor merchant has nothing to sell right now, he was supposed to sell snail armor, and may or may not be there in the next update.  Only the builders and GMs know, and they aren't talking.  So this really isn't an issue, unless nothing changes after the next update.  Or, maybe, they'll leave him there, with nothing to sell, just as a troll.

Anyway, I'm closing this.  We can re-open it after the next update, if we need to.
