### ISSUE TITLE
falling out of the world

### ISSUE THREAD

**Issue by jack1423** [Wynncraft/Issues#4998]
every time I try to join a world I fall out of the world with no way to get but to go to the lobby

**Comment by Odnod** [comment]
This bug has been fixed in the past by uninstalling and reinstalling minecraft. Try starting with that.

**Comment by Trixter313** [comment]
Did Odnod's suggestion help you? Thanks!

**Comment by jack1423** [comment]
I uninstalled and reinstalled but it didn't work; however I found that after I set the server resource pack to enabled it did fix my issue.

**Comment by Trixter313** [comment]
Great to hear! Enjoy your time playing Wynncraft! =)
