### ISSUE TITLE
Guild Battles Will not work

### ISSUE THREAD

**Issue by KintaroGaming** [Wynncraft/Issues#4999]
# Delete this line if you've searched for a duplicate issue first
When ever me and my guild start a battle with only 2 of us the battle world does not work it lets us leave the area and the mobs do not spawn.

**Comment by KintaroGaming** [comment]
Please help

**Comment by Trixter313** [comment]
Sorry for the late reply, is this still happening to you? Thanks!

**Comment by Trixter313** [comment]
Closing due to no reply
