### ISSUE TITLE
I lost all my LE

### ISSUE THREAD

**Issue by kabongollei** [Wynncraft/Issues#5001]
Whenever i logged on in the morning I looked in my EnderChest and saw none of my 15 LE, I know it isn't much for a level 57 but its still hard work to me. If someone can help me with this glitch please do so. Thank you.

**Comment by YunoFGasai** [comment]
it sounds like someone else logged onto your character.
does anyone else have access to your account?

**Comment by kabongollei** [comment]
No no one else does

**Comment by DarkDemonDragon** [comment]
Check ALL of your classes just in case. Many times you just can't find something because you glance over it because you put it somewhere abnormal. Anyways unfortunately Wynncraft has a strict no-refunds policy due to abusers, so just check if you still have it.
