### ISSUE TITLE
Lost all my stuff!!

### ISSUE THREAD

**Issue by JMLG1999** [Wynncraft/Issues#5002]
I, with my warrior class, was in the middle of the quest: "Jungle Fever" when i used the Troms Teleportation scroll (and I had 7 soul points) when i spawned in Troms i had nothing, literally nothing...
I would like to have all my stuff back :(

**Comment by YunoFGasai** [comment]
This is a duplicate of #4814 please refer all future comments to the original thread.

**Comment by Trixter313** [comment]
Or possibly even https://github.com/Wynncraft/Issues/issues/3821
