### ISSUE TITLE
Cant finish Quest

### ISSUE THREAD

**Issue by yoxon** [Wynncraft/Issues#5005]
Hello Everyone
I have a problem that i cant finish the "a fighting species" quest. I was just finishing it by talking to "Darnes" when the server started laging and we all got kicked. That happend before i got the reward and everyting and the "Orc Mask" and "Gorgu's Handprint" are gone. So i rejoined and wanted to try to finish the quest again but now i have to bring "Darnes" the Handprint again, though i cant enter the cave without the Mask, which i lost and cant get a new one.
Pleas help me solving this problem if anyone can.
yoxon

**Comment by YunoFGasai** [comment]
try using /fixquests

**Comment by yoxon** [comment]
Thank you that worked fine


2016-05-16 15:13 GMT+02:00 Yuno <notifications@github.com>:
