### ISSUE TITLE
I cannot sit on anything like on my friends (VIP perk) nor sit on a horse.

### ISSUE THREAD

**Issue by meolord** [Wynncraft/Issues#5006]
So, I have never done of the this issue letters. So I will just stay formal and logical.

To Whom It May Concern,

The problem first occurred around a week ago when I have tried to sit on my friend's head or to try to sit on a horse. This action had always been followed by the same outcome: "Internal Exception: io.netty.handler.codec.DecoderException: IntArray with size 1 is bigger than allowed 0"
![2016-05-16 20 24 35](https://cloud.githubusercontent.com/assets/19389463/15290669/43477620-1ba4-11e6-94a2-9e45b5412ce2.png)

I searched for the solution but as I searched I found that many people had the same problem on other servers, some have said that is something to do with spigot (I do not know what spigot is, I am sure that you have heard of it... I hope). This started to occur to people after the 1.8 update and 1.9 as it was not fixed in 1.8. If you need more information collected, I am more than happy to do it, my timezone is ICT (indochina Time) UTC/GMT +7 hours.

Best wishes to try fixing my situation,
meolord

**Comment by YunoFGasai** [comment]
first time hearing about it, which minecraft version are you using? if you area using 1.9 try changing to 1.8.

**Comment by meolord** [comment]
Yes, it works in 1.8.9. But... Should I need to play on the old version only for wynn? For mac, you have to close MC fully and open it and change the setting (or make a second version just for wynn). Is there a way to just fix it for 1.9... Some people may have same problem but no one have mentioned it yet. Thanks for the fix though!

**Comment by meolord** [comment]
Interesting to know what is so different between 1.8.9 and 1.9 that it crashes you every time you try to sit on something in 1.9

**Comment by YunoFGasai** [comment]
1.9 has been giving us troubles in all sorts of things (including horses and mounts) for now just use a 1.8 version until the server gets updated

**Comment by Moe-Ronickah** [comment]
WynnCraft is 1.9 compatible, however, it uses no features of any 1.9 version.  If you are crashing using a 1.9 version, then you need to use a 1.8 version.  I'm sorry, but the game is not coded for 1.9 and there are still a few rough edges in the 1.9 compatibility.  I don't when they are planned to be fixed.

**Comment by Moe-Ronickah** [comment]
Sorry, I didn't mean to close this, as it is still a 1.8.x problem for you.  Try changing 1.8 versions, and see if that helps.  And yes, you may have to create a separate version for Wynn, as Wynn is custom coded to run on top of the MC core game.  It's just a fact of the game.

**Comment by Trixter313** [comment]
@meolord said that the game works while using 1.8.9 above, so I believe that this issue actually can be closed. =)
