### ISSUE TITLE
Guild Leave

### ISSUE THREAD

**Issue by KnowYouM8** [Wynncraft/Issues#5007]
soo I have a problem that when I trying to leave the guild it says that I left the guild but when I trying to join a new guild it says that I need first to leave the guild that I already in pliz help me

**Comment by thecoolkogut4** [comment]
your not the only person whos like this right now. other people are in the same situation as you. all you can do at this point is wait it out.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!
