### ISSUE TITLE
No boats?

### ISSUE THREAD

**Issue by NinjaMaster909** [Wynncraft/Issues#5009]
I went to Bear Island to see what it was about. I didn't bother to bring an extra boat, as the map showed that they had a boat merchant. Turns out, there isn't! There's a stall for it, but no merchant.

**Comment by ChocolatyBear** [comment]
The map isn't completely updated on things like this. There probably was a boat merchant in earlier game years.

**Comment by YunoFGasai** [comment]
There used to be a merchant there. I think boat merchants have a habit of disappearing lately

**Comment by Moe-Ronickah** [comment]
If you find a merchant missing, yet the merchant stall is still there, try changing worlds, please.  That usually fixes the issue.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
