### ISSUE TITLE
Too Many Packets

### ISSUE THREAD

**Issue by Zyrbaiakor** [Wynncraft/Issues#5010]
I'm currently playing Wynncraft on 1.9.4 because I couldn't select anything in the compass when I played on 1.8.8. When I connect to a world, the resource pack loads as usual. However, a second after I gain control of my character, the game boots me back to the lobby with the message "You are sending too many packets!" Is there a way to fix this?

**Comment by YunoFGasai** [comment]
Go back to a 1.8 version, 1.9 versions are a bit buggy atm

**Comment by Trixter313** [comment]
1.8.9 is most recommended then just 1.8 is next but if neither of those work you can try the in between versions and if they work, woot!

Let us know if you happen to fix it please. Thanks!

**Comment by Trixter313** [comment]
Closed due to no response. Assuming issue is fixed.
