### ISSUE TITLE
Quest bug - Lord Of The Clock.

### ISSUE THREAD

**Issue by Miiiikkel** [Wynncraft/Issues#5013]
The quest Lord Of The Clock, dosen't work at all.. When you are at the last person *Spoiler* Frudo you cant talk to him, if you right click him he will just say a blank message... :/ 
When a talked to Gundalf he didnt give me the clock?!
-Miiiikkel

**Comment by YunoFGasai** [comment]
what does your quest book say?

**Comment by Miiiikkel** [comment]
It says "Destory the clock in the depth of Mt. Wynn"

**Comment by Miiiikkel** [comment]
And i've already tryed /fixquests!

**Comment by Miiiikkel** [comment]
Anything new? :)

**Comment by YunoFGasai** [comment]
try to run through all of the quest stages again (luckily there aren't many stages in this quest)
I would guess you missed something from the point of talking to gundalf

**Comment by Miiiikkel** [comment]
I will try that :)

**Comment by Trixter313** [comment]
Is your issue resolved? Thanks!

**Comment by Miiiikkel** [comment]
No it's not :/ When i talk to the last guy i dont get any message, and i cant get the clock anywhere :/

**Comment by Trixter313** [comment]
Hmm, did you happen to log out while some dialogue was going on? That seems to be what happened by the information I have.

**Comment by Miiiikkel** [comment]
No i didnt log out, im pretty sure i have tryed everything now, and nothing seems to work :/
What to do next? :)

**Comment by Moe-Ronickah** [comment]
Wait until the next update and see if this got fixed.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.

**Comment by finalchild** [comment]
I too have this bug
