### ISSUE TITLE
Tower Of Ascension; Falling through Floor after getting off horse

### ISSUE THREAD

**Issue by Denns300** [Wynncraft/Issues#5015]
Title explains it. Just wanted to say that it happened to me.

**Comment by YunoFGasai** [comment]
When you get off a horse it places you by a vanilla mechanism that was coded by mojang.
What we can do is change the arenas to be more hospitable to the dismount mechanic or you can just not ride in it as it majes no sense to do that whatsoever.

**Comment by YunoFGasai** [comment]
please lock this thread
