### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by CreepaBoy** [Wynncraft/Issues#5016]
I have an alt account i'm planning on using for storage but I can't get into Wynncraft Like I can get into the lobby but once I start downloading the texture pack I crash. Everything is the same with my main account and I can log into Wynncraft with my main but I cant with my alt for some reason. Can you help me?

**Comment by Odnod** [comment]
since it is just going to be a storage alt, you could disable server resource packs before joining.

**Comment by Trixter313** [comment]
Did Odnod's suggestion help you at all? Thanks!
