### ISSUE TITLE
Crashing when shooting bow

### ISSUE THREAD

**Issue by MCTuler** [Wynncraft/Issues#5017]
Hello. I would like to report a bug that seems to be occurring when I shoot an enemy with my bow. I've tried on other classes and I can't seem to recreate it. When randomly, when I shoot an enemy it kicks me from the server and gives me this message.
![image](https://cloud.githubusercontent.com/assets/19418405/15342282/2218a5dc-1c62-11e6-8e22-b9e17837537c.png)
"Internal Exception: io.netty.handler.codec.DecoderException: Unknown serializer type 16"
I hope someone can give me a solution or this problem can be resolved. Thank you for your time!
EDIT: It appears it only happens on my "Hunter" class. I noticed a difference between my other class and my Hunter class; when I right click a block, they say "You do not have permission for this area." However, on my Hunter class it does not say that. Upon further investigation; when I right click a wall (shooting the bow), it kicks me with the message that is provided above.

**Comment by MCTuler** [comment]
It appears that it is only on my "Hunter" class, as I am a VIP on the server.

**Comment by MCTuler** [comment]
It appears it only happens on my "Hunter" class. I noticed a difference between my other class and my Hunter class; when I right click a block, they say "You do not have permission for this area." However, on my Hunter class it does not say that. Upon further investigation; when I right click a wall (shooting the bow), it kicks me with the message that is provided above.

**Comment by YunoFGasai** [comment]
The message is because your bow is actually a block and when you click the wall you're trying to place it.
If you can do something for me, can you pop in game for a minute and tell me what's the block for your archer's bow and the block for your hunter's bow?

**Comment by DarkDemonDragon** [comment]
Also, what version are you using? 1.8 or 1.9?

**Comment by MCTuler** [comment]
On my Hunter class, it is a log. On my Archer class, it is a wooden slab.
I am also playing on 1.9 (Optifine).

**Comment by MCTuler** [comment]
I also purchased a bow that was strictly a bow. I checked the minecraft:id of it. I right click a block; it kicked me.

**Comment by MCTuler** [comment]
This did not occur until the "Statistic Update" came out as well.

**Comment by YunoFGasai** [comment]
The statistics update was website only as far as I was informed. 
Try switching to 1.8, 1.9 is still buggy in wynn.

**Comment by Trixter313** [comment]
Does using 1.8 fix your issue? Thanks!

**Comment by Trixter313** [comment]
According to [this announcement](https://forums.wynncraft.com/threads/minor-patch-fixing-the-kicking-bug.128303/), this issue should now be fixed! =) Shoot away!
