### ISSUE TITLE
Can't Join a World

### ISSUE THREAD

**Issue by truesurvivor9** [Wynncraft/Issues#5018]
I can't seem to join any world. I don't even have a clock in my inventory in the lobby, so I can't switch lobbies. Whenever I open my compass and click a world, nothing happens. I can attach screenshots if necessary.

**Comment by YunoFGasai** [comment]
everyone had this issue a couple of hours ago, it seems to be fixed now.

**Comment by Devdiablooper** [comment]
nope it's still not fixed

**Comment by Devdiablooper** [comment]
i tried joining, won't work.

**Comment by Odnod** [comment]
it seems you are stuck in the 'falback' server. I was stuck there for a bit and got out by changing the ip to "play.wynncraft.net" or "play.wynncraft.org"

**Comment by Moe-Ronickah** [comment]
The fastest way out of the fallback server issue is to completely exit Minecraft, wait 5 minutes, and try again.  It may take two or three tries, however, it's always worked for me.

**Comment by Devdiablooper** [comment]
uhm do you think i haven't tried that?

**Comment by YunoFGasai** [comment]
I heard that the node ip can bypass this, no idea what it is tho

**Comment by Moe-Ronickah** [comment]
duplicate of #5012
