### ISSUE TITLE
Can't join a world?

### ISSUE THREAD

**Issue by AVeryBoredGamer** [Wynncraft/Issues#5020]
Why can't I join a world? I had this problem before, and a re-log fixed it, but now it won't. I can't join the nether and leave, I can't use any commands because an "internal error occurs", and the compass and Portals are both not working. Any help?

**Comment by Odnod** [comment]
You are probably stuck in the 'Fallback' server. Try relogging and if that doesn't work change "play.wynncraft.com" to "play.wynncraft.net" or "play.wynncraft.org."

**Comment by AVeryBoredGamer** [comment]
I tried all your options, nada. Any other suggestions?

**Comment by Moe-Ronickah** [comment]
The fastest way out of the fallback server issue is to completely exit Minecraft, wait 5 minutes, and try again.  It may take two or three tries, however, it's always worked for me.

**Comment by Moe-Ronickah** [comment]
duplicate of #5012
