### ISSUE TITLE
falling through map when join a server

### ISSUE THREAD

**Issue by Salik0sa** [Wynncraft/Issues#5021]
![2016-05-18_19 18 03](https://cloud.githubusercontent.com/assets/19434471/15368183/c6ebc1a0-1d2c-11e6-9f6b-9b24319fe601.png)    i drop down there, under this place is nothing

hey, whenever i join the gameserver,i fall into void,cant die,cant write in chat,no /kill or other commands work, /class wont work. nothing works, i tried it about 3 hours, changed the lobbies, on each server the same problem. falling into deep^^  pls need help.  second problem: sometimes when i try to join a game i cant get in, i klick the world button,but nothing. 

i play on that server a long time, so its the problem of my minecraft^^  i was also trying much versions

 thx for coming help ;)

**Comment by Odnod** [comment]
This problem has been fixed in the past by uninstalling and reinstalling the minecraft client. I do not know what causes it or how it can be fixed every time, but so far the uninstalling method has worked for most people.

**Comment by Salik0sa** [comment]
ok i try^^

**Comment by Odnod** [comment]
That was very fast, not to be rude but are you sure you completed the whole process of uninstallation and installation?

**Comment by Salik0sa** [comment]
i have a really good computer^^ completely deleted minecraft from my computer and reinstalled

**Comment by Odnod** [comment]
Hmm. I am afraid I don't know any other way to fix this. Have you tried logging on from any different computers or perhaps ips?

**Comment by Salik0sa** [comment]
in my home i just have this computer^^   idk maybe teleporting me to a random spot in normal world? one time i was spawning on that place i falled down.. its the gm area. idk why i spawn there^^

**Comment by Odnod** [comment]
I think people sometimes spawn there do to a bug, but are able to get out just fine(?)

Try using a command like /kill or /hub the instant you get sent there, while you are still in the block. You should be able to queue up a chat message while the server is still in loading.

**Comment by Salik0sa** [comment]
wont work :/

**Comment by Salik0sa** [comment]
cant you just teleport me to a random place? maybe it works

**Comment by Odnod** [comment]
In the past players in this state were unable to be teleported. After doing a little bit of research I just found that most cases of this are due to connection problems. If you are on a VPN you may want to turn it off, if not you could try restarting your router.

**Comment by Salik0sa** [comment]
i restarted the router few hours ago,  i have that problem since yesterday. have reinstalled minecraft again.wont work

**Comment by Salik0sa** [comment]
PROBLEM SOLVED :D    lol man... after reinstalling the wynncraft ressource pack and activating....WHOPS!  spawned in normal world :DDDD

**Comment by Odnod** [comment]
nice! if your issue has been solved, please close it.
