### ISSUE TITLE
left-click bug when opening chests

### ISSUE THREAD

**Issue by Bonoboplayz** [Wynncraft/Issues#5022]
whenever i open a chest ignore with a bow or a potion quipped i somehow use the potion or the bow starts a spell combo by showing "LEFT - ??? - ???". in addition whenever i right click to shot and a block is within the range it says in the chat "you don't have permission to this area" which is kinda annoying. would be cool if someone could help me ^^

**Comment by YunoFGasai** [comment]
I have no idea why it would start a left combo (unless you left clicked)
The permission message is because your bow is a block and whenever you right click it it tries to place it.

**Comment by Bonoboplayz** [comment]
no i did not left click and the permission massage only showed up yesterday when the thing with the chest started, it all used to be ok..

**Comment by YunoFGasai** [comment]
Did you change your minecraft version recently?

**Comment by Bonoboplayz** [comment]
logged in today and it somehow fixed itself xD thanks anyway <3

**Comment by Trixter313** [comment]
Glad to hear! 😊
