### ISSUE TITLE
Lost Items In Duel.

### ISSUE THREAD

**Issue by LifelessWolf** [Wynncraft/Issues#5023]
So I dueled my friend, and when I lost it killed me and I lost EVERYTHING. I'm on World 11 as this is made and my username is LifelessWolf.

**Comment by YunoFGasai** [comment]
How many soul points did you have?

**Comment by Trixter313** [comment]
Appears to be a duplicate of https://github.com/Wynncraft/Issues/issues/3559

Please direct any future comments to the original thread. Thanks!
