### ISSUE TITLE
WynnExcavation Site A

### ISSUE THREAD

**Issue by NinjaShisui** [Wynncraft/Issues#5024]
I had just exited the tomb of Site A after defeating the boss, and my quest book told me to talk with Vade again, though when I did, he repeatedly told me to talk to Tesha, and Tesha told me to bring the translation to Vade. I've been stuck like this and cannot turn in the mission.

**Comment by YunoFGasai** [comment]
run through the tomb again and grab the crystals and then speak with vade

**Comment by Moe-Ronickah** [comment]
@NinjaShisui , did you try Yuno's advice?  Did it work?

**Comment by NinjaShisui** [comment]
Yes @Moe-Ronickah it worked. :)
