### ISSUE TITLE
Can't join a world

### ISSUE THREAD

**Issue by Devdiablooper** [Wynncraft/Issues#5025]
When i join the Wynncraft server everything is fine and all, but when i try to join a world or the nether nothing happens and i'm forever stuck in the lobby.

BTW: i've already tried to restart my computer, restart minecraft, relog, i've also changed the server IP several times, won't work.

pls help.

**Comment by Trixter313** [comment]
Is there any error message that pops up in chat or on screen? Also, what is your Minecraft username?

**Comment by Devdiablooper** [comment]
i only get errors with /server and my MC name is devdiablo

**Comment by LordPotatoz** [comment]
Well umm it's still going on atm and there are people saying that we are on a fall back server.

**Comment by Moe-Ronickah** [comment]
The fastest way out of the fallback server issue is to completely exit Minecraft, wait 5 minutes, and try again.  It may take two or three tries, however, it's always worked for me.

**Comment by Devdiablooper** [comment]
uhm, i've already tried that and i said that i've tried everything and when i said that, i actually ment EVERYTHING!

**Comment by Devdiablooper** [comment]
i've tried rerouting my router, tried restarting the computer, tried restarting MC, waited for more than an hour restarting MC, changing ip to .com/.net/.org, i've even tried reinstalling mc, nothing works.

**Comment by Moe-Ronickah** [comment]
duplicate of #5012
