### ISSUE TITLE
i cant leave my guild

### ISSUE THREAD

**Issue by Vydros** [Wynncraft/Issues#5026]
# Delete this line if you've searched for a duplicate issue first
I CANT LEAVE MY GUILD HELP ME

**Comment by Odnod** [comment]
Have you changed your username recently?

**Comment by Vydros** [comment]
I only changed my username once

**Comment by Vydros** [comment]
when i use guild chat, i type "/g hi" and the chat says 
_FlamingTiger:hi 
_FlamingTiger:hi
twice

**Comment by Vydros** [comment]
i have a question, it means i have to change my username back to my old name? then only i can leave my guild?

**Comment by KrabTheScrab** [comment]
Its a known bug i am sure the devs will get it fixed soon
בתאריך 20 במאי 2016 06:25,‏ "Vydros" <notifications@github.com> כתב:

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!
