### ISSUE TITLE
Wrath of the mummy quest is a bit broken

### ISSUE THREAD

**Issue by siddo0sidddo** [Wynncraft/Issues#5030]
When you give the pink wool to the bandit at the entrance his dialogue starts over from when you first go talk to him and he tells you to get pink wool. Then he continues and lets you in. This wouldn't be a big deal exepttThis happened to my friend and about half way through the dialogue he lagged out and when he rejoined the server he was all the way back at the very begining (behind ragni) without his pink wool and we had to buy another.

**Comment by Moe-Ronickah** [comment]
Currently, there is no way to fix the dialogue re-start on any quest.
Lagging out at any time can have unexpected consequences, again, mostly an MC mechanic issue.
Don't buy pink wool, kill the sheep in the sheep pen outside of Detlas.  They have a chance of dropping pink wool at random and the Great Sheep always drops pink wool.
