### ISSUE TITLE
Loot Bonus broken

### ISSUE THREAD

**Issue by LordPotatoz** [Wynncraft/Issues#5034]
My Jerra has a 52% bonus loot and my necklace has a 28% bonus loot but when I check my character information is displays 54%
Is this some kind of a bug or just necklaces, bracelets and rings don't add into the character info?

**Comment by YunoFGasai** [comment]
Do you have negative loot bonus on anything? Or a set bonus active?

**Comment by LordPotatoz** [comment]
Necklace is called Jester Necklace

**Comment by LordPotatoz** [comment]
Oh ok yeah thx I thought it was a plus sign... Too late at night...

**Comment by Moe-Ronickah** [comment]
Fixed with clear eyes.
