### ISSUE TITLE
Possible Typo in Lost Tower?

### ISSUE THREAD

**Issue by DCM627** [Wynncraft/Issues#5035]
I'm no grammar freak, but I think the last line should say, "one of the skeletons probably have it." There are more skeletons in the tower than just one, obviously.

![typo in lost tower](https://cloud.githubusercontent.com/assets/19480434/15442879/0426a95a-1eb2-11e6-9efb-7b7fd61d9e23.png)

**Comment by Villageacules** [comment]
This seems like just a minor grammatical mistake, I'll fix it right away. @Moe-Ronickah please close.
