### ISSUE TITLE
trophy points mis-calculate 

### ISSUE THREAD

**Issue by YunoFGasai** [Wynncraft/Issues#5036]
as I've been wandering across the forums I decided to check my trophy points so I went to the board and saw that Salted has 3 more points more than me, when I looked at our trophies I noticed that not only I have every single trophy Salted has, I have trophies he doesn't have, so where did the 3 points come from? (I suspect the answer has to do with either his account that got moved or 9/7 messing up trophies)

**Comment by YunoFGasai** [comment]
same when looking at tantibus and hoke, the only difference between our trophies is that they have the addictive member trophy and I don't, the rest of our trophies are the same. but yet I have 199, hoke has 209 and tanti has 217.

**Comment by Moe-Ronickah** [comment]
Unless someone is putting the points in by hand, I'm scratching my head at this one, Yuno.  Maybe ask Elements to take a look at it in a pm?

**Comment by Moe-Ronickah** [comment]
RESOLVED
