### ISSUE TITLE
/fixquests Does not replace Abysso Galoshes

### ISSUE THREAD

**Issue by Crazysickmonkey** [Wynncraft/Issues#5037]
I am doing the Lost Soles quest and I don't have the boots needed. I have checked every one of my classes and my bank i don't have the boots there is no way i can do the quest. I have only 3 classes that had the ability to do the quest and all three of them did it and yet i don't the boots I have done /fixquests on all of my classes. If a staff member could possibly fix this problem I would love it i really need to do the quest for my archer.

**Comment by Trixter313** [comment]
Sorry for the late reply! This is very unfortunate! The /fixquests command can be a little weird and not work with some items. We will try to get it working with the Abysso Galoshes. So you're 100% sure that you don't have any in any of your classes or bank?

**Comment by Crazysickmonkey** [comment]
I am 100% sure that I don't have the boots

**Comment by Moe-Ronickah** [comment]
RESOLVED
