### ISSUE TITLE
Fighting Species items lost with server crash

### ISSUE THREAD

**Issue by FrozenCherreh** [Wynncraft/Issues#5040]
I was doing a quest "fighting species" when suddenly the server crashed. I was on my way to go give Darnes Gorgu's hand print when that happened. After i logged back in, Both the hand print and the orc mask disappeared but Darnes still told me to give him those items... 
I cant continue the quest since my orc mask disappeared. Can anyone help fix this problem?

**Comment by TrashcanMan** [comment]
Try doing /fixquests, it should return any missing quest items. If this resolves your issue, please close it. Thanks, and have a nice day!

**Comment by Trixter313** [comment]
Did TrashcanMan's suggestion help you? Thanks!

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
