### ISSUE TITLE
Skillpoints

### ISSUE THREAD

**Issue by MeBigDan5** [Wynncraft/Issues#5041]
(hopfully i am right in this topic)

I did not play for a long time. I joined yesterday and was in the update room.
I set my skillpoints, after it i saw i cant use my wands. I identified the item and saw i my skills are wrong. Ok, my fail. I went to buy a reset scrol for 1LE!! (all i had saved befor ...) i reset my skills and set them to what i need (0,40,30,30,40) ... i closed the menu and my wand still did not work ... i open the menu and saw my points were totally different than i had set them .... wasted 1LE for nothing...

Is it possibil to become a new scrol or at least the 1LE?

---------------
(i am german, hope you understand what i wirte. If you understand german ->)
Hallo, Ich habe eine lange Zeit nicht gespielt. Habe gestern mal wieder vorbei geschaut und das Update mitbekommen. Die Skillpoint neu gesetzt danach bemerkt das die Items nicht gehen sie Identifiziert und gemerkt das die Skillpoints falsch gesetzt sind. Ok mein fehler, habe eine reset Scrol gekauft von all meinem erspartem (1LE) und die Punkte resetet und neu verteilt (0,40,30,30,40) dann gemerkt das die iteams immernoch nicht gehen das Menu wieder auf gemacht und gesehen das die Punkte an kommplet anderen Orten gesetzt ....

Ist es möglich die Rolle wieder zu bekommen oder wenigstens den LE?

**Comment by YunoFGasai** [comment]
check your armor, armor, weapon and accessories id's can change your skill points.

**Comment by MeBigDan5** [comment]
Nice to know ... thanks
