### ISSUE TITLE
Not gaining any XP from mobs nor quests.

### ISSUE THREAD

**Issue by HaydenHunter** [Wynncraft/Issues#5042]
I'm gonna be blunt... As the title explains it, but i've been playing with any of my
characters and none of them seem to gain XP. Not from quests or monsters.
If this is a client problem, IGN is Hayden_Hunter

Thank you

**Comment by YunoFGasai** [comment]
mobs wont give you xp if you are more than 30 levels from their level.
if this isn't the issue please make sure your guild xp isn't set to 100% (/guild xp [amount in %])
also check your armor for any negative xp id's.

**Comment by HaydenHunter** [comment]
This not the case. Even new classes do not

**Comment by HaydenHunter** [comment]
do this.

**Comment by HaydenHunter** [comment]
Yeh. Its fixed. Thanks.
