### ISSUE TITLE
Stuck In World Border

### ISSUE THREAD

**Issue by CheesepuffMC** [Wynncraft/Issues#5043]
Hi, recently I was on Skype with one of my friends, agentx56431 when he got stuck outside the world border and was not able to escape. I suggested dueling, but you re-spawn in the place where you die. Then we tried a teleportation scroll, boat, and even a horse, none of which worked. As I am writing this he is still stuck. If any server staff reads this, can you tp him to the nearest village or at least do /kill, because nobody is able to get him out.
![2016-05-21_10 54 32](https://cloud.githubusercontent.com/assets/19506185/15449110/72e797c4-1f42-11e6-9eba-ccd24a0e50d8.png)

**Comment by YunoFGasai** [comment]
if you have more than 3 soulpoints use /kill

**Comment by YunoFGasai** [comment]
if you can ask him to grab his cords before he kills himself so e could fix that hole.
