### ISSUE TITLE
CANT LEAVE MY GUILD

### ISSUE THREAD

**Issue by chrisko131** [Wynncraft/Issues#5044]
i tried many times 2 leave my guild
but every single time i do /guild leave
after type yes on da sign im still in da guild
n i lost 3 soul points
plus some of da guild command r not working as well
such as /guild leaderboard /guild stats etc
is da guild system currently down or sth
plz fix it thanks

**Comment by YunoFGasai** [comment]
The two commands were temporarily removed as guilds are broken right now.
As to the leaving part, that is a know issue and there isn't anything we can do about it.
