### ISSUE TITLE
WynnExcavation Site A

### ISSUE THREAD

**Issue by DJNothing** [Wynncraft/Issues#5045]
I started the Quest.At the next day my Quest Book said i need to go to the Lab Assistant.If I talk to her she says I should take this to Vade.But Questbook has not gotten updated.If i talk to him he says there is a riddle in the Tomb.But i cant enter the Tomb.

**Comment by YunoFGasai** [comment]
what happens when you try to enter the tomb?

**Comment by DJNothing** [comment]
It throws me out and says:"A strong force is preventing your entry"

**Comment by DJNothing** [comment]
Still doesnt work :/

**Comment by Moe-Ronickah** [comment]
https://wiki.wynncraft.com/index.php?title=WynnExcavation_Site_A

So, you have completed Stages 1, 2, and 3, and can't enter the tomb?  You've triggered all of the dialogue?

**Comment by DJNothing** [comment]
My Questbook is stuck at Stage 2

**Comment by Moe-Ronickah** [comment]
Go back through all of Stage 1 and 2.

**Comment by AckroWynn** [comment]
Duplicate. #4079
