### ISSUE TITLE
Missing items again

### ISSUE THREAD

**Issue by IArePolar** [Wynncraft/Issues#5046]
I lost my items once in Almuj, when I logged off and I was told I was probably hacked. But again?
I was in a safe place so I couldn't have died. Also I was only gone for 1-2 hours. Is something in Almuj making me lose my items? .-.

**Comment by YunoFGasai** [comment]
duplicate of #4818 
to be honest I think this is made up from 2 bugs, one that makes you die (or loose soulpoints) and another that makes you drop your stuff.

**Comment by Moe-Ronickah** [comment]
#3821 is the first report of these
