### ISSUE TITLE
PLEASE HELP

### ISSUE THREAD

**Issue by zombiehunterkill** [Wynncraft/Issues#5047]
...I'm so sad rn...
Just before I start, this will probably sound like a lie, but please try to help me...
So i was doing the House of Twain quest, and I was at the part where I threw in the items into the wither head... Then, because I'm STUPID, I accidentally threw in my MAXED OUT Black Horse... :(((
So i was just hoping that I could do something to get it back, because I spent so much LE just getting that :( 
I don't even care if it is maxed out or not, I just really want my horse back :(
Thanks for reading :(

**Comment by YunoFGasai** [comment]
there is a no refund policy, but I'm sure someone will be willing to sell you a horse for 2.5-3 le.

**Comment by Moe-Ronickah** [comment]
Anything thrown into a hopper vanishes in a few minutes, so it's long gone.  You aren't the first person to do that, and you won't be the last.  And there is NO record of what gets dumped into hoppers, either; that data file would be absolutely overwhelming.

As Yuno said, there is a no refund policy, too.
