### ISSUE TITLE
Stuck On the 'Fallback' Server.

### ISSUE THREAD

**Issue by TimThePvpMaster** [Wynncraft/Issues#5048]
Issue: I am stuck on the fallback server, and can not join any other servers. I click the compass, click a server, and nothing happens. I've changed the IP from .com / .net / .org and nothing has worked. I've also tried using the recourse pack and not using the recourse pack. @Trixter313 your very helpful, having helped solved a few of other bugs of mine. Anyone feel free to help! There's about 40 people in the Fallback server stuck there right now, saying stuff like "Jumla's screwed the server up again" and much more. Thanks!!!

**Comment by TimThePvpMaster** [comment]
Username: TimThePvpMaster

**Comment by TimThePvpMaster** [comment]
Nevermind this issue. The server restarts in ten minutes, so we were all saved. Thanks though guys!!! Thread closed.

**Comment by TimThePvpMaster** [comment]
My bad, I am still stuck on the Fallback server. @Jumla  @Trixter313  @SaltedSalmon

**Comment by TimThePvpMaster** [comment]
You've got to be joking... I'm in now.... @Jumla  Please check this thread out, people keep getting stuck and it's getting annoying. Thanks mate! <3

**Comment by Moe-Ronickah** [comment]
The fastest way out of the fallback server issue is to completely exit Minecraft, wait 5 minutes, and try again.  It may take two or three tries, however, it's always worked for me.

Please, do not tag Jumla or Salted.  They aren't able to respond to you as fast as Trixter or I can.

**Comment by Moe-Ronickah** [comment]
duplicate of #5012
