### ISSUE TITLE
Can't join a world? 2.0

### ISSUE THREAD

**Issue by AVeryBoredGamer** [Wynncraft/Issues#5050]
Okay this time I can't join a world (I'm in a fallback server) and I waited like +30 minutes in the same fallback server, and the servers restart, kicking me out, and now I should reconnect and everything should be alright, right? No, what happens is I get kicked out, I try to reconnect, and it says: _failed to connect_  And below that: _java.net.ConnectException._  I know this is not a client-side issue (a.k.a., not my fault) because I can join other servers without a struggle. And get this, when I can finally connect, guess what? You got your guess? Ring-a-ding-ding, we got ANOTHER fallback server! Yay, and I want to punch a wall. 

   If you're an admin reading this, please, please help. I'm absolutely in love with this server. Please help. Now, if you'll excuse me, I have walls to punch. :/

**Comment by Moe-Ronickah** [comment]
The fastest way out of the fallback server issue is to completely exit Minecraft, wait 5 minutes, and try again.  It may take two or three tries, however, it's always worked for me.

**Comment by Moe-Ronickah** [comment]
duplicate of #5012
