### ISSUE TITLE
Quest Bug ~ From the Bottom

### ISSUE THREAD

**Issue by Xannuh** [Wynncraft/Issues#5051]
So in the quest, I have this egg where someone needs to buy it from me. I've found the npc who needs to buy it; however, when I try to click on the npc no text appears in the chat.

https://gyazo.com/9aa36c3eeaf6d8c1c22553012cd076be

In this video, I'm clicking both the right and left buttons on the mouse and nothing appears.

**Comment by YunoFGasai** [comment]
that's the wrong npc, Dobile wants to buy your egg

**Comment by Xannuh** [comment]
Thanks, I thought I already checked all the npcs
