### ISSUE TITLE
Memory Paranoia bug

### ISSUE THREAD

**Issue by Quaduor** [Wynncraft/Issues#5052]
I was doing the Memory Paranoia Quest searching Timmy's Bedroom Key when i died. I went back to the mansion, everything was as the begining of the quest, I cant have acces to Timmy's Bedroom while I got the key. I dont know if it's a bug or if I'm just stupid...
Help me plz <3

**Comment by YunoFGasai** [comment]
Because the different rooms you enter ate in different copies of the mansion you have to run through the entire quest again.
The wiki will help you with the steps.

**Comment by Quaduor** [comment]
Thank you so much !
