### ISSUE TITLE
getting emeralds out of bank and server crashed out of no where

### ISSUE THREAD

**Issue by Macthecardinal** [Wynncraft/Issues#5053]
I LOST 3 LE!!!!!! 
another time i lost one EB
another time i lost a depressing wand!

i want a mod or someone to help!

**Comment by PrinceOfBellair** [comment]
What version are you playing on? Its possible it could be a glitch on 1.9.

**Comment by Moe-Ronickah** [comment]
I'm sorry that you lost so much, but WynnCraft has a no-refunds policy.  Mods cannot restore lost items, and admins will not restore items, because of the policy.

If you had searched for "lost items" you would have found 33 pages on this topic, many of which are duplicates of your issue.
