### ISSUE TITLE
I paid for VIP+ over 24 hours ago, still hasn't arrived

### ISSUE THREAD

**Issue by PrinceOfBellair** [Wynncraft/Issues#5054]
Yesterday (21st May 2016), I bought the VIP+ rank for £35 ($50) and it still hasn't been added to my account. I bought it off the Wynncraft website so it wasn't a scam. I bought it using PayPal and also using the GBP option on the store.

On the forums, I had received help but I had tried and checked everything, including waiting, the payment and the name I entered, and it still hasn't turned up.

Thanks

**Comment by Moe-Ronickah** [comment]
Sorry about the delay in your status update.

In the past, on rare occasions, it has sometimes taken up to 3 days for both VIP and VIP+ to show up on an account.  I don't know all of the details, but I believe that I've heard that sometimes the system has to be manually pushed for upgrades to come through.

If you still don't have your VIP/VIP+ rank in another two days, send an email to support@wynncraft.com, with all of the details.  They can, and will, manually change your status after confirming your purchase.
