### ISSUE TITLE
melting blocks

### ISSUE THREAD

**Issue by Kroko64** [Wynncraft/Issues#5055]
i was farming in the ice caves and i say some blocks missing. The glitched me out. I think they were accidently melted by the glowstones

**Comment by YunoFGasai** [comment]
can confirm this is happening

**Comment by Moe-Ronickah** [comment]
Around ToA or around Rodoroc?

**Comment by YunoFGasai** [comment]
happened to me at frozen hights, I don't think I encountered it anywhere else

**Comment by Trixter313** [comment]
Is this still happening?

**Comment by YunoFGasai** [comment]
I figured out why this is happening, when an ice snake is cast on ice blocks (on the exact coordinates) the terrain block will disappear and cause a desync issue between the server and the client when walking into the missing blocks.

**Comment by Moe-Ronickah** [comment]
Oops.

**Comment by Villageacules** [comment]
Known bug, should be addressed this update.
