### ISSUE TITLE
+Tier Attack Speed problem

### ISSUE THREAD

**Issue by LotKnockMC** [Wynncraft/Issues#5063]
So to put it simply, +Tier attack speed doesn't work properly for me. It affects the visuals, and even increases spell damage, but hit speed remains the same. 

Weirder still is that it works for everyone else that I ask about having this problem. Any ideas?

**Comment by LotKnockMC** [comment]
Oh this affects -Tier attack speed as well

**Comment by YunoFGasai** [comment]
weirdly enough that what gm's claim it's supposed to do. (I know it sounds weird).

**Comment by Moe-Ronickah** [comment]
"even increases spell damage"  That's because you are getting more dps (damage per second) from hitting your target more times, via increased Tier attack speed.  Hence, this is not an issue; it's working like it should.
