### ISSUE TITLE
Tree Hole

### ISSUE THREAD

**Issue by Ninjazzzzzz** [Wynncraft/Issues#5064]
At 237, 83, -1676, there is a hole in a tree.
You might be saying "Nobody who plays Wynncraft will ever manage to be so gullible to fall into that hole in the middle of a tree!"
Well idk how, but my friend managed to fall into it and had to /kill. He's just that dumb.
Anyway fix it plz thanks

**Comment by Moe-Ronickah** [comment]
I'm so curious as to who your friend is, Ninja.  However, Yuno has a thread on the forums that lists holes that need filling.  Would you post this information, there, please?

**Comment by YunoFGasai** [comment]
@Moe-Ronickah added it on monday

**Comment by Moe-Ronickah** [comment]
Cool!  Thanks, Ninja, for the report, and Yuno, for adding it to your thread.  I'm closing this issue, as the builders are aware of it and WILL fill it in.
