### ISSUE TITLE
Get kicked when do right click. Please help

### ISSUE THREAD

**Issue by JustFl0w** [Wynncraft/Issues#5065]
When I right click something with a bow as a Hunter I get kicked from the server and the player who are near to me get kicked too .

Please help me and sorry for my bad english skills.

**Comment by Moe-Ronickah** [comment]
I will bet that you are using some version of 1.9.  If I am correct, switch to a version of 1.8.  Wynncraft is NOT updated to 1.9.

**Comment by Moe-Ronickah** [comment]
@JustFl0w , is this still happening?  Did you try switching MC versions?  Did it help, at all?

**Comment by Moe-Ronickah** [comment]
Hopefully, https://forums.wynncraft.com/threads/minor-patch-fixing-the-kicking-bug.128303/ fixed this issue.
