### ISSUE TITLE
Help i bug in a block

### ISSUE THREAD

**Issue by xerces01** [Wynncraft/Issues#5066]
I and my friend was in the cave for WynnExcavation Site B. We found the crystal and we went to the coalblocks and then I was teleported in a block. I cant use the teleportations scroll. My ingame name is _xerces_.

**Comment by DarkDemonDragon** [comment]
Use /kill if you have 3 or more Soul Points whenever you are stuck in an area. This will respawn you in the nearest city/respawn point at the cost of 2 SP.
