### ISSUE TITLE
Items dissapearing out of bank

### ISSUE THREAD

**Issue by HomingArrow** [Wynncraft/Issues#5067]
I had all the relic armor, I achieved it by doing the relics.
So I had it in my bank, I have no proof how so ever of this. 
And about 1 hour ago, I was running around in troms farming and when I returned to the bank, I saw that the armor was gone, I didn't use or take it the last few days.
The same happened to my nemract's rage, no proof of that either.

So basically, stuff started dissapearing out of my bank. No one has access to my account, so no, no one could've done this.

Hope someone could help me out,
HomingArrow

P.S. I spoke to some people at Detlas and a few told me this happened to them too.

(And is it possible to get my relic armor back in any way?)

**Comment by YunoFGasai** [comment]
I'm not sure what made your stuff disappear.
as to relic armor, I'm not sure why everyone thinks you can only get one set, the relics have an 8 hour cooldown after you use them, just go through them again.

**Comment by Moe-Ronickah** [comment]
@HomingArrow , check for DUPLICATEs, please.  "items bank" will give you a long list.
