### ISSUE TITLE
Dark Wizard Crashing The World

### ISSUE THREAD

**Issue by Mininglover21** [Wynncraft/Issues#5068]
I am having a problem with my Dark Wizard, whenever I log in as it, it spawns me into the void. I have pressed F3 and looked at the coordinates and the y value is at a ridiculous number that I can't even fully see. While I'm in this state, I am unable to use commands, the compass, or the quest book. All of my other classes are fine but when I log into a world as my dark wizard, after a few seconds, it crashes the world and everyone is kicked from it into a lobby. (I did not abuse this bug, there have been some complaints about the servers crashing, but I only tried to log in as my dark wizard three times) If there are any suggestions, I would appreciate it.

**Comment by YunoFGasai** [comment]
if you are on 1.9 try using 1.8.
try connecting to the node ip (will post in a minute)

**Comment by YunoFGasai** [comment]
node7.wynncraft.com

**Comment by Mininglover21** [comment]
ok I will try that

**Comment by Mininglover21** [comment]
It didn't work, my dark wizard still made the world I joined crash.

**Comment by Mininglover21** [comment]
I've tried 1.9 and 1.8

**Comment by Mininglover21** [comment]
@Jumla If you can help with my issue that would be great.

**Comment by Mininglover21** [comment]
IGN: Mininglover21

**Comment by thecoolkogut4** [comment]
If you have enough soul points try /kill

**Comment by Mininglover21** [comment]
@thecoolkogut4 i can't do any commands.

**Comment by Moe-Ronickah** [comment]
Immediately after logging in to a world, try /kill.

**Comment by Mininglover21** [comment]
@Moe-Ronickah, that is a good idea, but i just tried it and it didn't work. (Even on the first second of joining still nothing works.)

**Comment by Moe-Ronickah** [comment]
We can't find your character as stuck.

**Comment by Moe-Ronickah** [comment]
What are your coordinates?
Are you using a different name in-game?
I just don't get why we can't find you as stuck in-game.

**Comment by Moe-Ronickah** [comment]
FIXED!
