### ISSUE TITLE
Lost Soles continuation bug

### ISSUE THREAD

**Issue by DCM627** [Wynncraft/Issues#5069]
[link to example](https://www.youtube.com/watch?v=cBlUjgyg9Y8)

I saw this bug on MrSebbelonien's video and it also occurred to me. Shoutout to him for unknowingly providing the video proof of this bug. So, if you look from 14:30 to 15:15 in Seb's video, Grandon lets you speak to him right after he tells you to throw something behind the map. You do not need to throw something behind the map in order to continue, though you will need it later when actually entering the code. I just spam clicked through his dialogue (usually I'm not in the mood to read when I'm playing and I read the dialogue on the wiki later) and basically skipped that whole riddle. Any way that this could be fixed?

**Comment by YunoFGasai** [comment]
They can add a whole stage to the quest that will require you doing the riddle. 
OR you can press t and read the chat log.

**Comment by DCM627** [comment]
I know about reading the chat log, but they have a stage. I think the problem is that whoever made this quest forgot to put a requirement to do something before being able to talk to Grandon again. The step is there. You know how when you do something in a quest and is says in the chat [Quest Book Updated]? They never created one for the map puzzle. That's what I think happened.

**Comment by Moe-Ronickah** [comment]
Thanks for pointing this out.  We'll add it to our list.  And another quest bug gets added to the list.
