### ISSUE TITLE
Lost Soles Typo

### ISSUE THREAD

**Issue by DCM627** [Wynncraft/Issues#5070]
![2016-05-22_17 32 00](https://cloud.githubusercontent.com/assets/19480434/15485125/7d6b6e58-210b-11e6-9255-46ced56ba29a.png)

For part 5/5 2nd line, the word should be it's, not its. Yes, I know it's trivial, but it bugs me.

**Comment by Moe-Ronickah** [comment]
Thanks for pointing this out.  We'll add it to our list.  It bugs us, too.

**Comment by AckroWynn** [comment]
Fixed!
