### ISSUE TITLE
Extra quest items

### ISSUE THREAD

**Issue by mikaela656** [Wynncraft/Issues#5071]
After deleting one of my classes and making a new one, and doing the first few quests in the beginning I realized that I have 6 creeper heads in my bank which don't stack. At the moment I have 4 different classes but I have 6 creeper heads. They are filling up my bank space and I can't even throw them away. Is there any way out of this?
![2016-05-23_12 33 47](https://cloud.githubusercontent.com/assets/8674995/15486769/c5701528-20e3-11e6-9355-26ada03a6097.png)
![2016-05-23_12 42 34](https://cloud.githubusercontent.com/assets/8674995/15486787/e1aa15ae-20e3-11e6-97bf-0af1763aae28.png)

**Comment by YunoFGasai** [comment]
you can put them into your daily rewards chest to get rid of them
