### ISSUE TITLE
Can't join a world? 3.0

### ISSUE THREAD

**Issue by AVeryBoredGamer** [Wynncraft/Issues#5072]
Before I discuss this topic, why can someone just close your issues on the forums? This random guy just replied to me a method to fix my problem and closed the issue, and when I tried the solution, it didn't even work. You know who I'm talking to.

Okay this time I can't join a world (I'm in a fallback server) and I waited like +30 minutes in the same fallback server, and the servers restart, kicking me out, and now I should reconnect and everything should be alright, right? No, what happens is I get kicked out, I try to reconnect, and it says: failed to connect And below that: java.net.ConnectException. I know this is not a client-side issue (a.k.a., not my fault) because I can join other servers without a struggle. And get this, when I can finally connect, guess what? You got your guess? Ring-a-ding-ding, we got ANOTHER fallback server! Yay, and I want to punch a wall.

If you're an admin reading this, please, please help.

**Comment by Moe-Ronickah** [comment]
If play.wynncraft.com isn't working for you, then try play.wynncraft.net.They are exactly the same server, but, for some reason, they seem to be handled differently by the main server.  It's also possible that while one isn't working NOW, it will work in 5 min.  If you are still having trouble, shut down Minecraft, wait 5 min., then try again. Sometimes, it takes 2 or 3 tries to get in, but you will get in.

PS: They know about it and are working on it.

**Comment by Moe-Ronickah** [comment]
_"Before I discuss this topic, why can someone just close your issues on the forums?"_

I've been asked about your comment by others, so now, I'm going to address it.  There are no "random" people that can close any issue that anyone posts on either the forums or here, in the GitHub.  If someone has managed to close an "issue", that is, a forum thread, that you have posted, you need to discuss that with a either a moderator or an admin on the forums.  If someone, other than an admin, here, on the GitHub, has managed to close an issue that you know of, please let either Trixter or me know about it, as I haven't heard anything about it, from anyone, and we will deal with it.

_"This random guy just replied to me a method to fix my problem and closed the issue, and when I tried the solution, it didn't even work."_

The WynnCraft GitHub issue tracker is a community-based issue tracker and assistance forum, where anyone and everyone is welcome to participate and assist in helping other players, and, eventually, admins, in dealing with the myriad of issues that can and do arise in a game as complex as WynnCraft, which exists _on top of_ Minecraft.  There are no "random" people here, so please, try to refrain from thinking that way.  Everyone is here to try to help other players and the game admins to make WynnCraft a more enjoyable experience.

_"You know who I'm talking to."_

I'm not certain who you are talking to, however, I suspect that it is/was me.  Did I get it right?
PS: If I'm correct, look on the front page of the GitHub.  I'm not "random", well, at least not completely.  :)

**Comment by Moe-Ronickah** [comment]
duplicate of #5012
