### ISSUE TITLE
Horses

### ISSUE THREAD

**Issue by Telvres** [Wynncraft/Issues#5073]
I just spent 20 le on horses and didnt even get a single black, this game is so rigged.

**Comment by YunoFGasai** [comment]
so youre telling me you bred 53.3 brown horses and you got brown every single time?

**Comment by YunoFGasai** [comment]
that is 52 breeding operations, that means 10 blacks

**Comment by Telvres** [comment]
Yes it was 52 browns and I didn't get a single black

**Comment by YunoFGasai** [comment]
well statistically that can happen (has a really low chance tho).
but in your case it seems you had an unlucky roll of the program.

**Comment by Trixter313** [comment]
All we can say is you must have gotten very unlucky. People are still getting black horses and there's no hard evidence to anything else.

Good luck with your breeding! Maybe you could post on the forums about it and see if anyone else has experienced anything similar.

**Comment by YunoFGasai** [comment]
@Telvres add me in game I will give you a black horse.
my ign is Yuno Gsai
