### ISSUE TITLE
Server going into restart, glitch fall through world and lost my chest and legs...wtf?

### ISSUE THREAD

**Issue by Zer0honor** [Wynncraft/Issues#5074]
So server had 2 minutes...world 4...to restart so I start running back to detlas. as riding my horse I fall through the ground and the server restarts. I log back in and my legendary chest and legs are unequipped and gone....help plz.

**Comment by YunoFGasai** [comment]
was your inventory full at the time?

**Comment by Moe-Ronickah** [comment]
@Zer0honor , as to the falling through the ground, I'm curious.  Which version were you playing in, 1.9 or 1.8?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
