### ISSUE TITLE
Death Whistle mountain teleporting

### ISSUE THREAD

**Issue by gijswl** [Wynncraft/Issues#5076]
In the Death Whistle quest you have to go up a mountain and get a black whistle leaf.
If you teleport up the mountain it wont trigger that stage of the quest, I walked down the mountain into one of the black teleport things. It kept teleporting me inside it and saying a bold '**/**'. After using the class menu multiple times to get myself out it teleported me to the Caravan Driver at the start of Wynn, didn't lose any of my gear though.

**Comment by Trixter313** [comment]
If you even get stuck again just use /kill with 3+ soul points. This sometimes happens but shouldn't happen to you again. Thanks!
