### ISSUE TITLE
Stuck in Battle Dome 

### ISSUE THREAD

**Issue by ThatGuyLegend** [Wynncraft/Issues#5077]
I went to the battle arena through the Nether Portal then i got confused becasue i thought i was going to the Angry Village then i tried to do /leave but nothing happened ...
Someone please Tp Me Out of the Arena :(
its been a day since i had this problem
Ign:TrooperGaming

**Comment by YunoFGasai** [comment]
try /hub and re-enter a game world and as soon as you're in type /kill

**Comment by Trixter313** [comment]
Let us know if you get out. Thanks!

**Comment by ThatGuyLegend** [comment]
Thanks

**Comment by ThatGuyLegend** [comment]
uhhhh im still stuck

**Comment by ThatGuyLegend** [comment]
Wait im out :O Thanks Yuno and Trixter :o
