### ISSUE TITLE
I Don´t get my VIP+ rank

### ISSUE THREAD

**Issue by Cyjuga** [Wynncraft/Issues#5078]
Hello, yesterday i have buy vip+ but i don´t get it.
My in game name is Cyjuga_
(sry for my bad english, I´m from germany)

**Comment by thecoolkogut4** [comment]
Send an email to support@wynncraft.com with your transaction ID. Say that you bought vip+ and it's been a day and you still didint get it. Make sure you send the id

**Comment by Trixter313** [comment]
The people at that email should be able to take care of this but let us know if the issue persists!
