### ISSUE TITLE
I lost something

### ISSUE THREAD

**Issue by KawaiiCrafter7** [Wynncraft/Issues#5080]
I bought the 1600 gc pack and I didn't get the coins! Help me! I paid 50€

**Comment by YunoFGasai** [comment]
when did you buy it?
it can take some time to arrive

**Comment by thecoolkogut4** [comment]
Send an email to support@wynncraft.com with your payment transaction ID

**Comment by Trixter313** [comment]
They should be able to help there. Let us know if your issue stays unsolved!
