### ISSUE TITLE
Missing Tall Grass (Maybe Grass) and Fence Textures

### ISSUE THREAD

**Issue by Areorah** [Wynncraft/Issues#5082]
I am using Optifine with Shaders built in. I am using a Shaders pack, but for some reason my grass and fences are changing. My friend had the same problem with just adding forge itself with 0 mods. I am using a texture pack, but when I remove it, it still shows missing textures. Any idea how to fix this?
http://imgur.com/a/k2KuJ

**Comment by YunoFGasai** [comment]
try using 1.8 if you are using 1.9

**Comment by Trixter313** [comment]
Let us know of that solves your issue or not!

**Comment by Areorah** [comment]
Sorry for late response, but switching over to 1.8 (not 1.8.9, just 1.8) with my mods worked fine. Thanks!

**Comment by Trixter313** [comment]
Good to hear!
