### ISSUE TITLE
ANOTHER Lost Soles Typo

### ISSUE THREAD

**Issue by DCM627** [Wynncraft/Issues#5083]
![screenshot 36](https://cloud.githubusercontent.com/assets/19480434/15519851/78918cfc-21d1-11e6-82de-f471f80b0562.png)

Wow... 2 typos, same quest... I took this dialogue from after the quest is over. It's repair, not rapair. *facepalm*

**Comment by Moe-Ronickah** [comment]
Thanks for pointing this out.  We'll add it to our list.

**Comment by AckroWynn** [comment]
Fixed!
