### ISSUE TITLE
Stop the aids pls items desapearing

### ISSUE THREAD

**Issue by ChaosDunkFTW** [Wynncraft/Issues#5085]
I login and fking lose my stuff ? ._.
I was grinding and i logged on then next day when i logged in i lost my speaker,Memento,and jester bracelet !
I payed like 40 le for those 3 items!
Its like the wynncraft doesnt want me 2 play ._.

**Comment by YunoFGasai** [comment]
was your inventory full upon logging in? 
how many soulpoints did you have when you logged off? 
where did you log off?

**Comment by ChaosDunkFTW** [comment]
i logged in whit 14 sp and yes it was full 
I logged off in  ice thingy area where i grind but i looked around me there was nothing on the ground ._.

**Comment by YunoFGasai** [comment]
duplicate of #4814 
please refer all future comments to the original thread
