### ISSUE TITLE
Fallback server

### ISSUE THREAD

**Issue by Telvres** [Wynncraft/Issues#5086]
What is with this fallback server that probably all of us have joined? It is rare now that I can get into wynncraft. Please fix

**Comment by Moe-Ronickah** [comment]
If play.wynncraft.com isn't working for you, then try play.wynncraft.net.They are exactly the same server, but, for some reason, they seem to be handled differently by the main server.  It's also possible that while one isn't working NOW, it will work in 5 min.  If you are still having trouble, shut down Minecraft, wait 5 min., then try again. Sometimes, it takes 2 or 3 tries to get in, but you will get in.

**Comment by Moe-Ronickah** [comment]
duplicate of #5012
