### ISSUE TITLE
Glitched guild member

### ISSUE THREAD

**Issue by MrRobinHood** [Wynncraft/Issues#5087]
# Delete this line if you've searched for a duplicate issue first
I have a guildmember that is taking up 2 spots in my guild and can't be kicked.
if you look at my screenshots you can see the game will tell me he got kicked but he didn't get removed also if you look at the guild list he is on both 17 and 18.
If anyone knows how to fix this please tell me,
thanks.
![bugged uturn](https://cloud.githubusercontent.com/assets/19535391/15549166/b4ae98b2-22ab-11e6-8d87-4263d6d91429.png)
![double uturn](https://cloud.githubusercontent.com/assets/19535391/15549167/b4af0b26-22ab-11e6-8dab-24669e665973.png)

**Comment by Moe-Ronickah** [comment]
Please check for DUPLICATEs.
