### ISSUE TITLE
Bow "Az" not usable during guild wars

### ISSUE THREAD

**Issue by RunningGag18** [Wynncraft/Issues#5088]
I can't use my mythic bow "Az" during the guild wars. Normal arrows and spells aren't working. The bow isn't even registrating whether I do right- or leftclick.
Furthermore it shows a unlikely description.
![2016-05-25_20 40 33](https://cloud.githubusercontent.com/assets/19578779/15556433/202a7cc4-22ce-11e6-926c-24bc95a180f3.png)

**Comment by DCM627** [comment]
Very interesting. I know that the purple text is from when you look at an item through a GUI, aka Emerald Merchant, Item Buyer, etc. Is it possible that you went into the war server while in the Emerald Merchant's GUI? Does playing on a normal, regular Wynncraft world fix your bow? Also, are you using 1.9? That could also be the problem, causing arrows and spells not to work.

**Comment by RunningGag18** [comment]
In the regular world everything is fine with that bow. 
I am using 1.8.
I tried to join Guild Wars with Az multiple times but unfortunetly it doesn't work.

**Comment by Moe-Ronickah** [comment]
The guild wars server is coded separately from the main server, so there must be an error in the Az coding.

**Comment by YunoFGasai** [comment]
there are a couple of items that act like this (should we make a list?)

**Comment by Moe-Ronickah** [comment]
"there are a couple of items that act like this (should we make a list?)"

YES!  I only knew about the Az.  Put it on the forums, it will help Salted and Jumla to see the list.

**Comment by YunoFGasai** [comment]
will do

**Comment by RunningGag18** [comment]
Yuno, could you send me the link then? ;)

**Comment by DCM627** [comment]
https://forums.wynncraft.com/threads/list-of-items-unusable-in-guild-wars.128718/#post-1436015 Yeah I already had this copied... I stalk the forums too much...

**Comment by YunoFGasai** [comment]
@DCM627 the forum links are made from a couple of "pieces"
https://forums.wynncraft.com leads to the forums themselves
/threads/ will lead you to a thread
thread title -guess what this does
.128718 is the thread address
/#post- leads to a specific post on that thread

**Comment by YunoFGasai** [comment]
just delete the /#-1436015

**Comment by Moe-Ronickah** [comment]
**PLEASE NOTE:
For any item that cannot be used in a Guild War, there is a thread on the forums that we are using to list these items.**  Please post your item name in this thread [List Of Items Unusable In Guild Wars](https://forums.wynncraft.com/threads/list-of-items-unusable-in-guild-wars.128718/).  Thanks, in advance!

**Comment by Villageacules** [comment]
It's been almost a year, can this be confirmed it is still happening?

**Comment by Moe-Ronickah** [comment]
I'm closing this thread.  Any item with this problem should be posted on the forums in `[List Of Items Unusable In Guild Wars](https://forums.wynncraft.com/threads/list-of-items-unusable-in-guild-wars.128718/)`.
