### ISSUE TITLE
Few Disappointing Bugs.

### ISSUE THREAD

**Issue by Nicostrophy** [Wynncraft/Issues#5092]
Some things on my armor doesnt affect my stats?
http://prntscr.com/b8x7ur Does not increase hit speed, mining fatigue doesnt change (Proof)
http://prntscr.com/b8x81q (Chestplate) http://prntscr.com/b8x88b (No Chestplate)
As well as skill contributions that are pulled from weapons.
http://prntscr.com/b8x8ej (Ex.)
No Weapon (After Relogging) http://prntscr.com/b8x8rq
With Weapon (After Reloggin) http://prntscr.com/b8x95i
As you can see there are no skill point changes even though i'm supposed to be getting them, as well as the attack speed increase from my chestplate. That also, does NOT increase. Please fix and "Git" back to me when fixed and / or mentioned to dev to fix whatever. Sucks for me, i thought this chestplate was going to be epic..

**Comment by YunoFGasai** [comment]
attack tiers don't effect the swinging speed, they effect the damage.
the game counted your weapon in both pics, put a normal weapon in your first slot and look at your stats.

**Comment by Nicostrophy** [comment]
Does not change. http://prntscr.com/b90hkx

**Comment by YunoFGasai** [comment]
about the skill points I think I know whats the issue, it only counts the +5 strength when you are holding the weapon but when you open the compass you aren't holding it so it doesn't sow up.
the attack tier is supposed to increase your attack speed therefore increasing your damage output. the coders decided that it will only increase damage thus skipping the middle step (the end result is the same).

**Comment by Moe-Ronickah** [comment]
Hey, @Nicostrophy , the best way to tell if the attack speed tier is changed is to look at the difference when you are using a normal or slow weapon.  Even an attack +1 tier is very apparent, if you try to see it with a very fast weapon, you won't be able to see it; it's already at the end of the graphic speed.

The other problem, the one with the skill points, is exactly as Yuno said, it just won't show up when you move your mouse to your compass.  It may be a compass error, I just don't know.  There are several problems with the compass, and the admins know about them, and are working on them.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
