### ISSUE TITLE
Poison not working?

### ISSUE THREAD

**Issue by LordPotatoz** [Wynncraft/Issues#5093]
My weapon has +115/3s of poison but when I hit a mob it only does 4dmg for the poison. ???

**Comment by LordPotatoz** [comment]
Great now there isn't even any poison anymore...

**Comment by YunoFGasai** [comment]
does any other piece of armor/accessory/weapon have negative poison?

**Comment by LordPotatoz** [comment]
nope

**Comment by Moe-Ronickah** [comment]
I am in-game right now, and poison is working for me, as far as I can tell.  Please check and see if this issue is still happening to you, or if it has resolved itself.

**Comment by LordPotatoz** [comment]
now it's doing 42 damage of poison?...

**Comment by Moe-Ronickah** [comment]
The actual damage done to a mob depends on the weapon that you are using.  Your damage rate is +115/3s, so your poison damage is, once again, working properly.  We love temporary glitchs - they go away when we relog or switch servers or change classes.  Let us know if it comes back.
