### ISSUE TITLE
Compass Failure - Wont let me join a world

### ISSUE THREAD

**Issue by Flying-Froge** [Wynncraft/Issues#5094]
I have tried to join one of the wynn servers, i click on the green block, and it just exits me out of the screen and i stay in the lobby

**Comment by YunoFGasai** [comment]
try using another ip
play.wynncraft.net

**Comment by Trixter313** [comment]
Did Yuno's suggestion fix your issue? =)

**Comment by Moe-Ronickah** [comment]
The admins know about this, and are working on it.
