### ISSUE TITLE
I can't get the texture pack

### ISSUE THREAD

**Issue by jonothanli8899** [Wynncraft/Issues#5097]
Every time I log in the texture pack doesn't work at all. It might be that I'm falling through the world and its not letting the server load the texture pack. . .(yes I've finished all of the steps from the forums)

**Comment by Trixter313** [comment]
Can you link the steps you've tried so we know? So you've tried making sure server resource packs are enabled in Multiplayer > Wynncraft > Edit ?
If that didn't work, try closing Minecraft and deleting the ”serverresourcepacks” folder in your .Minecraft folder.

Let us know the results of these tips. Thanks!

**Comment by jonothanli8899** [comment]
I've tried all of them and none of them have worked
Link to steps: http://jumla.in.Fd

**Comment by jonothanli8899** [comment]
actually its this one O-o
https://forums.wynncraft.com/threads/cant-play-wynncraft-because-of-the-pack-heres-how-to-fix.98023/

**Comment by Trixter313** [comment]
Previously people have solved this issue by uninstalling & reinstalling Minecraft. If that sounds like something you'd like to try, that might fix it. Other than that I personally don't have that many more suggestions for this particular issue.

**Comment by Moe-Ronickah** [comment]
@jonothanli8899 , you might try to get a copy of the current texture pack from a friend, then follow the instructions for installing it either from the forums or from Minecraft forums.

**Comment by Trixter313** [comment]
Just checking in, were you able to fix your issue? Thanks!

**Comment by jonothanli8899** [comment]
I could not fix it, but I'm just playing my account on my little brother's
computer and it works. Not sure if its a server connection or computer thing

**Comment by Trixter313** [comment]
Did you try my suggestion of uninstalling and reinstalling Minecraft on the affected computer? That is usually the last resort that fixes a lot of issues.

**Comment by Moe-Ronickah** [comment]
Sorry, I'm late posting this to you.  Go to our [front page](https://github.com/Wynncraft/Issues), and follow the Resource Pack page.  The latest Friday resource pack will be available there, every week, until the resource pack issues are solved.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
