### ISSUE TITLE
WynnExcavation Site D

### ISSUE THREAD

**Issue by YouWynnILose** [Wynncraft/Issues#5098]
I am in the stage whereas I have to talk to the Rebel Leader Amadel.
I right-clicked on him but nothing showed up.
Please help!

**Comment by Trixter313** [comment]
What does it say in your quest book?

**Comment by YouWynnILose** [comment]
Speak to Rebel Leader Amadel.

**Comment by Trixter313** [comment]
Hmm, did you happen to logout and/or get kicked while some quest dialogue was happening? That sometimes causes things like this.

**Comment by RealNeuhier** [comment]
A friend of me has the same problem...
He is called Baumi_ and he can't talk to Amadel, he never could...
When we arrived in the camp the bug was already caused for no reason.

Is there a way to fix this somehow?

**Comment by AckroWynn** [comment]
Duplicate. #4675
