### ISSUE TITLE
Devoreuse does not work cannot be identifyed

### ISSUE THREAD

**Issue by Mathieu0424** [Wynncraft/Issues#5099]
My Devoreuse wand did not transfer to an identifiable item in the new update plz help me i cannot use it and its the best wand i have as of now HELP

**Comment by Trixter313** [comment]
Could you post a screenshot of the item or describe the issue a little more?

**Comment by Moe-Ronickah** [comment]
@Mathieu0424 , would you do a search for "Devoreuse" and tell us which of those 15 or so closed issues your issue most resembles?
