### ISSUE TITLE
What should I do

### ISSUE THREAD

**Issue by pullapulla1** [Wynncraft/Issues#5100]
What should I do if I can not put my Defence poition and it is taken in most 20 Point and it will always remain a zero my minecraft name is pullapulla1

**Comment by Trixter313** [comment]
Hmm, I don't really know what you're saying the issue is. Defense potions are temporary so maybe the effect is wearing off? If I misunderstood, could you try to explain it again? Thanks!

**Comment by pullapulla1** [comment]
I reset my skill points I do not receive any defense to skill points
and I tested it n.10-20 and it was just zero

**Comment by Moe-Ronickah** [comment]
Is this still happening, or is it fixed?
