### ISSUE TITLE
Silverfish Dungeon Bug

### ISSUE THREAD

**Issue by Masterpringles** [Wynncraft/Issues#5101]
The problem is, im with a friend in the Silverfish Dungeon. Everything was fine but were are in the last part with the trap and the Silverfishes. But the trap doesnt work. We dont fall in to the trap and the Redstone doesnt. Pls help me thanks

**Comment by YunoFGasai** [comment]
try switching a server, that part of the dungeon is known to break at times

**Comment by YunoFGasai** [comment]
and go back to the start of the bridge to re-trigger the redstone

**Comment by Masterpringles** [comment]
Thank you i try it

**Comment by Trixter313** [comment]
Let us know if that helps or not, thanks!

**Comment by Moe-Ronickah** [comment]
RESOLVED
