### ISSUE TITLE
2 bugs that are making me seriously consider quitting

### ISSUE THREAD

**Issue by Stag2001** [Wynncraft/Issues#5102]
I have 2 bugs:
1. If you invite someone for a trade, then go into your inventory and click something, and while it is not in your inventory but you are 'holding' it with your mouse, the person accepts the trade. The item you were holding simply disappears and never comes back. I lost my first stack of LE from this, thank you wynncraft.
2. If you put an item into your bank while the server is restarting within 5 minutes, it will simply disappear. I lost my Pure because of this, again, thank you.

**Comment by YunoFGasai** [comment]
as to "bug" number 1 its a vanilla mechanic that has nothing to do with wynn. when holding an item its technically not in the inventory and when you close the inventory's gui it will drop and in wynncraft's case get deleted
as to bug number 2 its a duplicate issue (will link original issue)

**Comment by YunoFGasai** [comment]
probably related to #4199 although I seem to remember a more specific report
