### ISSUE TITLE
Lost in Heart of Llevigar

### ISSUE THREAD

**Issue by Masterpringles** [Wynncraft/Issues#5105]
Im in the Quest Heart of Llevigar. But i cant find a way to enter in to the mashine. Can anyone tell me how can i get in to it? Yes i read the wiki but it doesnt help. Thanks

**Comment by Moe-Ronickah** [comment]
Check Youtube for a walk through video.  You'll find something like https://www.youtube.com/watch?v=cfNX_gRB5AQ

Good luck, and let us know if this resolved your issue.

**Comment by Trixter313** [comment]
Just checking in, is your issue still occurring or is it fixed? Thanks!
