### ISSUE TITLE
Guild Leaving Bug

### ISSUE THREAD

**Issue by Exotrot** [Wynncraft/Issues#5106]
I signed up to join a new guild, and they asked me to leave my old one first, but whenever I do /guild leave, it says I already left.

**Comment by YunoFGasai** [comment]
guilds are extremely glitchy at the moment and a fix is being worked on, sorry for the inconvenience

**Comment by Moe-Ronickah** [comment]
There are so many duplicates of this:   #3665 .

@Exotrot , if you changed your name while in your guild, you are absolutely stuck until the guild issues are fixed.  If you didn't change your name, keep trying, once or twice a day, and it might, MIGHT, resolve itself.  No guarantees.
