### ISSUE TITLE
Guild is Broken

### ISSUE THREAD

**Issue by ChocolatyBear** [Wynncraft/Issues#5107]
# Delete this line if you've searched for a duplicate issue first
I know there are multiple threads, but no one responded to ANYTHING I asked for about this. I can't leave my guild. Is there a way an admin can kick me out of it? It's been like 7 months. My IGN is Chocolaty_Bear. Guild is Gystiriem. Thanks. Please try to kick me!

**Comment by YunoFGasai** [comment]
guilds are extremely glitchy at the moment and a fix is being worked on, sorry for the inconvenience

**Comment by Moe-Ronickah** [comment]
PLEASE, do not post duplicate issues.  Guilds are being worked on, and until they are fixed, there is nothing anyone here can do to help you, or anyone else.

**Comment by ChocolatyBear** [comment]
Oh ok thanks.
On May 30, 2016 4:51 AM, "Yuno" <notifications@github.com> wrote:
>
> guilds are extremely glitchy at the moment and a fix is being worked on,
sorry for the inconvenience
