### ISSUE TITLE
Lag removed quest item - Flight in Distress

### ISSUE THREAD

**Issue by Decimatee** [Wynncraft/Issues#5109]
So I was doing a quest (Flight in Distress) and I did it all, but when I talked to the end NPC, I lagged out, it ate my item, and I can't get back to the ship to finish it :/

/fixquests doesn't work

**Comment by Odnod** [comment]
You are going to have to go back through the quest as you did before in order to get the item back. Sorry for the inconvenience.

**Comment by PandaBanditz** [comment]
im doing the shadow of the beast i killed bigfoot and all that went to the quest giver and the stringy hair you get from the farmer was gone, i cant complete the quest, and idea for what to do

**Comment by Moe-Ronickah** [comment]
@Decimatee , did you follow Odnod's advice?  Is your issue fixed?

**Comment by Decimatee** [comment]
Yeah but it was hard doing it a few hours later without any quest book
guiding xd

**Comment by Moe-Ronickah** [comment]
I'm glad that you got through it!

There are youtube video guides on every, if not nearly every, quest.  If you ever find yourself again in a position where the Wiki doesn't help enough, turn to one of the walk throughs/guides.
