### ISSUE TITLE
Potion Price Isnt Right

### ISSUE THREAD

**Issue by jeffrey1607** [Wynncraft/Issues#5111]
Hey,
The prices of the potion buyer in olux arent right:
The 750 Heal potion costs 23 And the 560 Heal potion costs 27.
Hope you can fix this :smile: 
Cya! Ps Lovely server you have there.

**Comment by Moe-Ronickah** [comment]
Thanks for pointing this out.  We'll add it to our list.

**Comment by Moe-Ronickah** [comment]
RESOLVED
