### ISSUE TITLE
Animal Riding

### ISSUE THREAD

**Issue by EricSalata** [Wynncraft/Issues#5112]
# Delete this line if you've searched for a duplicate issue first
When you right click near a pet it automatically puts you on it, this prevents having pets out while fighting. Please make it to where you shift click to get onto a pet, instead of just right click.

Thank you in advance.

**Comment by YunoFGasai** [comment]
I'm pretty sure that there is a forum suggestion about this.
anyways, thanks for reporting this!

**Comment by Trixter313** [comment]
Please search for your suggestion on the forums first and if there isn't a topic for it yet, make one there. Because the feature is currently working as intended this post would fit better here instead: https://forums.wynncraft.com/forums/general-suggestions.69/

Thanks!

**Comment by EricSalata** [comment]
Wait, do you mean there is a way too turn off this? And how do I fix it?


Thanks in advance.

**Comment by YunoFGasai** [comment]
there is no way to turn it off, this is an intended feature.
The linked thread is a suggestion to disable that feature.

**Comment by Moe-Ronickah** [comment]
It's the standard Minecraft "interact with" right-click mechanic.  It does not apply only to pets, but rather, to all entities that can be interacted with, from chests to NPCs.
