### ISSUE TITLE
Green-skinned Trouble: Trapped after a teleportation

### ISSUE THREAD

**Issue by FC3000** [Wynncraft/Issues#5116]
I am trapped in a block i think, after the teleportation in the mission "green skinned trouble" and i can't do nothing (write in chat or use my teleportations scrolls)
Please help me

**Comment by YunoFGasai** [comment]
if you have more than 3 soulpoints do /kill

**Comment by Moe-Ronickah** [comment]
Please search for "Green-skinned Trouble" and tell us which one of those issues most closely resembles your issue.

**Comment by Trixter313** [comment]
It's been over a month since a response from @FC3000 . I'm going to assume this is abandoned and close it. If you still have information to give us, simply comments below. Thanks!
