### ISSUE TITLE
I got stuck in the mountains and it deleted my scroll when i tried to use it.

### ISSUE THREAD

**Issue by sirpancaker** [Wynncraft/Issues#5117]

**Comment by sirpancaker** [comment]
In the mountains that you arent supposed to be able to climb over... i forgot and tried to get up on and i got stuck in place. I couldnt use my teleport ability(i am a mage) and then i tried to use a teleportaion scroll and it deleted it.

**Comment by YunoFGasai** [comment]
if you have more than 3 soulpoints use /kill

**Comment by Moe-Ronickah** [comment]
Which mountains?  What are your coordinates?  WynnCraft is a big place.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
