### ISSUE TITLE
Cant Leave Guild /guild leave not working

### ISSUE THREAD

**Issue by ChiefInferno** [Wynncraft/Issues#5120]
I changed my name in February while in the guild, I tried leaving the guild 2 months later due to it becoming inactive, I have looked and wrote stuff to even the Wynn support team and nothing is being done about it, it is now June and I've been stuck like this since February, so what did I do, I changed my name back which has brought back things like /g and other commands but I still cannot leave my inactive guild. as it being inactive I cannot ask any 1 to kick me and when I do /guild leave, type yes, it says you have left your guild, 3 soul points lost, bla bla bla, and nothing happens, I say Moe this isn't an attack on u but your the only person I see helping with this stuff and nothing happens, I say stand up your game or get more people on the job, because it is ridiculous

**Comment by Moe-Ronickah** [comment]
It may seem ridiculous, however, this is the way things are right now.  Guilds, while they are a big part of the game for many people, are not THE reason for the existence of the server, and, as you've already been told, there is only ONE coder who works on the game, itself.  I've seen dozens, if not hundreds, of reports of problems with guilds, here, in the forums, and in the shoutbox, in one form or another, so I know how frustrating it is.  I also know that the owners are very well aware of the guild issues, and are working on them; something IS being done about it, about all of it.  I don't know what the time-frame is for the guilds to be fixed, but the issues are on their radar.  That's the best that they can do, and the best that I can tell you.  There are people who have had guild issues for far longer than you, so just take it easy.  That's the best that we can do.
