### ISSUE TITLE
Wynnexcavation site A

### ISSUE THREAD

**Issue by Mat196** [Wynncraft/Issues#5122]
So I killed the "boss" in there but gave me nothing. (Did not think this was a problem) Left through the black portal and went outside. The quest book updated and said talk to Vade. I talked to Vade who said "Bring this to Tesha." However, I already gave him/her the paper. I did /fixquests but nothing worked.

**Comment by Moe-Ronickah** [comment]
You are going to have to go back through the entire underground passage, kill Pharoh Nabak again, and get the Yellow Crystal.  Don't leave without that crystal; it's the item that Vade is looking for.
