### ISSUE TITLE
I lost my items

### ISSUE THREAD

**Issue by buzzsaw847** [Wynncraft/Issues#5124]
I was in nessak as a level 47 mage I had sage a full 30/30 chestnut horse the ledgendary wand sage 2 le i am really upset about this and am considering quitting if my items are not returned

**Comment by Moe-Ronickah** [comment]
First, it would really help us if we knew how you lost your items, as that could help us to prevent this from happening, again.

Second, WynnCraft has a strict no-refund policy, whether or not you have proof of the loss of your items.  I suggest asking around in Detlas for help, you might find that there are many players who will be willing to help you in some way.

**Comment by buzzsaw847** [comment]
I dont know exactly how it happened i logged in and my items were gone

**Comment by YunoFGasai** [comment]
how many soulpoints did you have when you logged on?
where did you log in? 
did any items remain in your inventory?

**Comment by buzzsaw847** [comment]
i had 15 and no i had none of my quest items

**Comment by Moe-Ronickah** [comment]
Are you saying that you had no quest items on you to lose, or that you lost everything that you had on you, including your quest items?

**Comment by buzzsaw847** [comment]
i lost everything including quest items

**Comment by Moe-Ronickah** [comment]
Evidence of a hacked account.
