### ISSUE TITLE
Im stuck In A Wall .-.

### ISSUE THREAD

**Issue by LegoCollecter14** [Wynncraft/Issues#5125]
I'm Not Sure exactly what happened but anyways im stuck in A wall =/
Heres a screenshot.

https://gyazo.com/82f03adf4ec1b656a366bf2dab92896b

What Should I Do?
All i Did was get off my horse
And Yes i already tried tping out with a tp scroll, it doesnt work

IGN; LegoCollecter14

Also im sorta new so im not sure as to how i can contact staff

**Comment by YunoFGasai** [comment]
do /kill if you have more than 3 soulpoints.
also if you can get the coordinates for me I can male sure that that hole will get filled

**Comment by LegoCollecter14** [comment]
Okay Ive got the soul points and ill let you know about the coords Its in travennes fyi if i forget

TKYSM

**Comment by LegoCollecter14** [comment]
801 71 -16278 to 801 75 -1628

**Comment by YunoFGasai** [comment]
thank you. that hole will be filled in soon!

**Comment by Villageacules** [comment]
Fixed, will be pushed this update.
