### ISSUE TITLE
Dont have permission for 'this area'

### ISSUE THREAD

**Issue by Peeves5200** [Wynncraft/Issues#5126]
Game constantly says I dont have permission for this area when I right click - even on chests so I cant open them
![bug](https://cloud.githubusercontent.com/assets/19710290/15746472/a1693df6-28ce-11e6-843a-5b2a4bf62b6a.png)
Only happens for one character and not the other

**Comment by YunoFGasai** [comment]
it happens because your weapon is actually a bloc/slab so when you click it the game thinks you are trying to place it.

**Comment by Moe-Ronickah** [comment]
Switch to clicking with another item or an empty hand.
