### ISSUE TITLE
Unable to complete Wynn Excavation D

### ISSUE THREAD

**Issue by AliAli1009** [Wynncraft/Issues#5131]
Hey,
I had completed the wynn excavation site D quest and had waited for double xp and when i return to the king I am simply replied to with "Off you go, I've said everything I have to say." which I'm fairly certain is from King's Recruit. Either way, I'm unable to complete the quest

**Comment by Odnod** [comment]
You are taking to the wrong king, you have to go to the coal teleport region behind the final form fight and that takes you to a large chamber with the king.

**Comment by AliAli1009** [comment]
So I have to redo the whole boss?!

**Comment by YunoFGasai** [comment]
you just need to run through the gates and it will teleport you to the next stage

**Comment by AliAli1009** [comment]
Thank you so much

**Comment by Moe-Ronickah** [comment]
Fixed.
