### ISSUE TITLE
Stuck on top of door of time

### ISSUE THREAD

**Issue by Levykitten** [Wynncraft/Issues#5132]
I was exploring looking for a cave and I tellported.When I telleported i must have telleported in a none entering area now i cant telleport out. Every time i try to telleport out it tells me i am in a restricked area. 

Thanks from 
Levykitten
![stuck](https://cloud.githubusercontent.com/assets/19732991/15784609/d62b5484-2978-11e6-98f6-ab7bb56b33d9.png)

**Comment by Odnod** [comment]
Just type /kill if you have 3 or more soul points.

**Comment by Andy0132** [comment]
How on earth...

Use a scroll if you don't want to burn 2 SP.

**Comment by Moe-Ronickah** [comment]
@Levykitten , are you out of there?  If you are, would you please close the thread.
