### ISSUE TITLE
Death Whistle bug?

### ISSUE THREAD

**Issue by baconLovertoo** [Wynncraft/Issues#5136]
When I was doing the Death Whistle quest I was doing all the things the quest book said (Go up a mountain and get the Black Whistle Leaf and bring it back to him). So I get the leaf and give it back to Voer and he says " Go and get me the flower, I wrote the location in your book!" like I didn't have the leaf in my inventory. So I decided to go back to the mountain and get more leafs and try and see if the quest book would update. 15 minutes later I am still trying to figure out why it isn't working,

![2016-06-03_13 28 07](https://cloud.githubusercontent.com/assets/17680939/15788906/4b3db42c-298f-11e6-8d4b-39a9ae5b6a03.png)

As you can see I had 12 leafs in my inventory and he was still saying the same message " Go and get me the flower, I wrote the location in your book!"

Hopefully I can get some help on this quest and/or the staff team can fix this quest

_~Bacon_
Have a nice day

**Comment by TheBestSurfer** [comment]
That happened with me too, i think what you did was climb the mountain without entering it. There's a "cave" in the bottom where you can enter to climb up the mountain.

Have a nice day :)

**Comment by baconLovertoo** [comment]
I will try the cave although I am pretty sure it didn't teleport me the first time I tried, but thanks for the information.
