### ISSUE TITLE
Stuck in Squid Village Entrance

### ISSUE THREAD

**Issue by MewTheConqueror** [Wynncraft/Issues#5139]
I jumped into the entrance for the Squid Village without my Water Helmet and am now stuck in an endless loop of being teleported just above the hole and being told "Are you really trying to dive in without the proper equipment?" I have already done this quest and wanted to explore more of the lake in search of easter eggs. I am now stuck infinitly.
![image](https://cloud.githubusercontent.com/assets/19743979/15798372/1051af0e-29e3-11e6-95f5-1d7d4d17e580.png)

**Comment by MewTheConqueror** [comment]
I've attempted to use a teleportation scroll, and it does not work due to being too close to aggressive mobs.

**Comment by YunoFGasai** [comment]
in case you accidentally closed the thread, you /kill with more than 3 soulpoints.
