### ISSUE TITLE
Mummy's Rag

### ISSUE THREAD

**Issue by ScourgeDarkness** [Wynncraft/Issues#5141]
Well I haven't really looked deeply into the issue but it says +1 tier attack speed and I didn't see a difference when I put it on. I have a slow weapon and I tested it with and without the armor there was no difference and then I also looked at the weapon it still said slow... Is this a glitch or bug or is this feature not completely done yet?

**Comment by Moe-Ronickah** [comment]
What class are you using?

**Comment by ScourgeDarkness** [comment]
Mage

**Comment by Moe-Ronickah** [comment]
It won't change the information on the weapon, however, you should see an increase in visual attack speed on your mage.  Try comparing the visual speed with both a slow and normal speed weapon.  Even more important, though, is there an increase in the amount of damage that you do while wearing the Mummy's Rag?  If so, then the mechanics are working as they should.

**Comment by ScourgeDarkness** [comment]
I haven't seen an increase in damage it still takes me 5 hits to kill a level 30 silverfish and still the same amount of time with or without the chest plate. I think that the mechanics are a little broken but it's not a really big problem more of an annoyance. It still gives me enough health for it to be useful though.

**Comment by YunoFGasai** [comment]
if your weapon is already super fast it wont boost it any further.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
