### ISSUE TITLE
Silverfish dungeon

### ISSUE THREAD

**Issue by ScourgeDarkness** [Wynncraft/Issues#5142]
So I have looked for a while and can't seem to find one thing about this... I have entered the dungeon multiple times on different servers and I tried to open the first door. I went to the parkour finished that put and emerald on that pressure plate then the snakes put an emerald inside each of the little holes. Even after all that the door never opened I wasted probably about 5 keys and 30 emeralds now that is not what makes me mad because those are easily made back but I just want to be able to complete the dungeon. Can anyone tell me what I am doing wrong or if the dungeon is broken etc.?

**Comment by Moe-Ronickah** [comment]
First plate: one emerald
Four snake holes: one emerald each
**Two plates: one emerald each**

You don't seem to have run up the stairs to the last two plates.  For further help, google "wynncraft silverfish dungeon walkthrough" and https://wiki.wynncraft.com/index.php?title=Silverfish_Dungeon, The First Phase.

**Comment by Trixter313** [comment]
Did you get the door to open? Thanks!

**Comment by chfboyardie** [comment]
Hast his been resolved? I've been having this issue both yesterday and today. Sometimes it'll open, other times it will not. I've wasted 3 keys on it now :(

**Comment by Moe-Ronickah** [comment]
It's glitchy.  Try changing servers, instead of leaving the dungeon by any other method.  Also, dungeons are getting major revamps when the gameplay update comes out.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
