### ISSUE TITLE
No damage or horses

### ISSUE THREAD

**Issue by Peeves5200** [Wynncraft/Issues#5144]
Just logged in and cant deal any damage or use my horse with either character. Tried multiple weapons and still nothing

**Comment by Moe-Ronickah** [comment]
It's a minor, but annoying glitch, and might get your character killed.  By now, you should have logged out, closed Minecraft and restarted it.  Are you still stuck without any ability to interact with the game?

**Comment by Peeves5200** [comment]
Ok it works now. Restarted a few times and it didnt but apparently just waiting for a bit works

**Comment by Moe-Ronickah** [comment]
Good deal.
