### ISSUE TITLE
stuck in the nether

### ISSUE THREAD

**Issue by trikkilol** [Wynncraft/Issues#5145]
i got stuck in the nether and i can get out.
for some reason i can't use /leave and wen i step in the netherportal in the middel of the nether world i got sended to the lobby. and wen i join i am standing in the portal so i get right away telleported back.

can someone help me pls i don't know how to stop this or break it i have tryd multiple things.
my MC name is trikki

**Comment by YunoFGasai** [comment]
disable your server texture pack and enter a wynncraft server, walk out of the portal and run to detlas, log out, enable your texture pack, log back in.

**Comment by Trixter313** [comment]
Did Yuno's suggestion resolve your issue? Thanks!

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
