### ISSUE TITLE
[Aldorei's Secret Part I] I can't finish the quest

### ISSUE THREAD

**Issue by ShyniaKogami** [Wynncraft/Issues#5147]
Hello, i can't finish the quest "Aldorei's Secret Part I" because at the last stage, I started speak to Corak and Kansard, i gave them the "Sunblight boots" , but finally I have search a Double XP server, so I return back to the lobby and when I relog ingame, the quest has [taken] the boots but didn't finish the quest. so now i need the boots but i don't have them. Can you help me ?

Screens:
[http://image.noelshack.com/fichiers/2016/22/1465083948-2016-06-05-01-20-19.png](url)
[http://image.noelshack.com/fichiers/2016/22/1465083962-2016-06-05-01-20-37.png](url)

**Comment by Andy0132** [comment]
Try /fixquests.

**Comment by ShyniaKogami** [comment]
Ty for helping :D

**Comment by Andy0132** [comment]
No problem, happy that it worked!
