### ISSUE TITLE
Sayleros' Brother quest: No experience Bug. Please Help!

### ISSUE THREAD

**Issue by quinnrockstar** [Wynncraft/Issues#5149]
Me and my friend tacoliam2 were playing wynncraft and doing casual quests together like sayleros' Brother quest, When we got the dusty will we went back to sayleros. We completed the quest at the same time and got no experience. We got sayleros brother's ashes and access to the graveyard. But no xp, I think this is a bug,  Please can somebody help me out with this bug. Thank you.

I was at lv 20 and 2 bars before i beat the quest and i didn't gain any xp.

![wynncraft bug](https://cloud.githubusercontent.com/assets/15721487/15802908/159e40aa-2a9a-11e6-8267-86c796ee94f2.png)

**Comment by Odnod** [comment]
Is your guild xp set to 100? Do /guild list and see how much xp you have contributed to your guild.

**Comment by quinnrockstar** [comment]
I think that was it, my bad. Thank you
