### ISSUE TITLE
Random Damage issues

### ISSUE THREAD

**Issue by Laufinthehunter** [Wynncraft/Issues#5150]
# Delete this line if you've searched for a duplicate issue first
I keep taking damage half-heart per time. This happens even when nothing is attacking me. Please help me, I'm really low on soul points, and I don't want to lose my stuff.

**Comment by Andy0132** [comment]
You've probably got negative regen. What are your stats?

**Comment by TheCatArchy** [comment]
This can be due to lag, I was having the same issue the other day.
Try using an area attack along any path you've been travelling and around yourself, might fix the problem.

**Comment by Laufinthehunter** [comment]
Thanks guys, my regen stats are actually positive, but my bow, the glacial crest, has a minus 84 health thing, perhaps it takes away 84 health at random intervals?

**Comment by Moe-Ronickah** [comment]
Your health will drop on an odds-based rate.  I suggest that you keep it in your second hot-bar slot, and don't walk around with it in order to prevent losing health all of the time.
