### ISSUE TITLE
Connected when banned...

### ISSUE THREAD

**Issue by thediamondgames** [Wynncraft/Issues#5155]
This is a bit different from issue #2829

I was banned I think over a year ago and because I was a young annoying kid who camped near Nesak and used kill aura to get xp (but was banned for aimbotting while playing mage :/). I wish I wasn't such an i*iot, that's why now I appealed it .
One week later after an appeal I tried to join the server and successfully did it.
The difference between #2829 is that I could join the world and play it for as long as I wanted to. Well, I didn't after I tried to switch to different world, because after typing /lobby it said I was banned (but could play more). This is quite a big deal actually as there might be people who would cheat again who would actually cheat again can join the server at random times.

I hope this gets resolved

**Comment by Moe-Ronickah** [comment]
Have you heard back from a moderator as to whether or not you're ban appeal was accepted?  Are you, or are you not, still banned?

**Comment by thediamondgames** [comment]
I am still banned I believe. Haven't heard anything from the moderator.
