### ISSUE TITLE
Unable to Leave Guild

### ISSUE THREAD

**Issue by Apexisawesome** [Wynncraft/Issues#5159]
I've been doing /guild leave for the past 6 months and it doesn't work. I know it doesn't work for people who changed their names while in the guild but I didn't know that and now I'm stuck in a guild. I'm not asking for this to be fixed(it'd be nice though..) 
I just wanted to ask if someone could remove me from my guild. My guild leader has also tried to kick me out lots of times but it doesn't work so please help! My ign is xtralalalax

~Thanks

**Comment by YunoFGasai** [comment]
actually currently the opposite is being done, instead of kicking manually all the players the coding team is working on a fix.
duplicate issue please refer all comments to the original thread #3665
