### ISSUE TITLE
Jester Necklace Missing

### ISSUE THREAD

**Issue by Battleslay1000** [Wynncraft/Issues#5160]
This may sound weird, but i had bought a jester necklace, and about 2 minutes after that, it dissapeared. It was not in my inventory, not in my bank. I did click the empty square where it was. I simply don't know.
ItsBrozer will confirm this, as he was the one who sold me the necklace.

**Comment by Mininglover21** [comment]
Before it disappeared did the server restart, (you) relog, or did it just go missing without any type of a "relog"? Also are you sure you didn't somehow drop it or clicked on it while doing an action, making it disappear?

**Comment by Battleslay1000** [comment]
I didn't touch it at all, and I only relogged after I realized it was gone.

**Comment by YunoFGasai** [comment]
is your drop key set to the default "Q"?

**Comment by Battleslay1000** [comment]
Yes

**Comment by YunoFGasai** [comment]
what happened is that you probably pressed Q accidently and dropped the necklace.
I would suggest binding your drop key to something far from your other keys like "-" on your number pad.

**Comment by YunoFGasai** [comment]
btw did you upgrade your bank after buying the necklace?

**Comment by Battleslay1000** [comment]
The necklace was not on my hotbar, it was in my inventory.

On Tue, Jun 7, 2016 at 2:14 AM, Yuno <notifications@github.com> wrote:

> what happened is that you probably pressed Q accidently and dropped the
> necklace.
> I would suggest binding your drop key to something far from your other
> keys like "-" on your number pad.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/5160#issuecomment-224211005>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS2Q1UAjgRshatmTKpAgPUBkwN9ukf_cks5qJSh-gaJpZM4IuZXO>
> .
>



-- 
[image: [​IMG]] <http://www.nodiatis.com/personality.htm>

**Comment by Battleslay1000** [comment]
no

On Tue, Jun 7, 2016 at 2:15 AM, Yuno <notifications@github.com> wrote:

> btw did you upgrade your bank after buying the necklace?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/5160#issuecomment-224211067>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS2Q1StOqTcnxMP_kU4_5PIZykzMSmSVks5qJSiNgaJpZM4IuZXO>
> .
>



-- 
[image: [​IMG]] <http://www.nodiatis.com/personality.htm>

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
