### ISSUE TITLE
Memory Paranoia - No TP at the Hole in the Wall

### ISSUE THREAD

**Issue by Denns300** [Wynncraft/Issues#5162]
So, i tired to do the Memory Paranoia quest and I got to the point where had to go into the hole in the wall and I went in there and wasn't teleport.
Dunno if this is my fault or the server's (I tried switchign servers and reconnecting)

**Comment by Mininglover21** [comment]
Make sure that it said to go into the hole in the wall and not something else in your questbook.

**Comment by Moe-Ronickah** [comment]
There are multiple places that appear to be the final exit hole.  Are you certain that you were at the actual exit?  Please do a search in youtube for a walk-through to be certain that you were at the right place and let us know what happens.

**Comment by Trixter313** [comment]
It's been a month since a reply from @Denns300 so I'm going to close the issue as it appears abandoned. If you're still experiencing it, simply comment below. Thanks!
