### ISSUE TITLE
Item Identifier Tree - Llevigar: The Sequel

### ISSUE THREAD

**Issue by Benzillatron** [Wynncraft/Issues#5163]
About 2 minutes ago you guys fixed the tree in Llevigar so I decided to test it to see if you could get in the spot again. The good thing is, you can no longer get in said spot. The bad news is, I found another whilst trying to get in the fixed one. Sorry for constantly breaking the game. WC 21.
![2016-06-05_19 20 13](https://cloud.githubusercontent.com/assets/19753570/15807304/9ca09324-2b52-11e6-9992-302014260c21.png)

**Comment by Moe-Ronickah** [comment]
Please post this to Yuno's thread on "Holes" in the forums.  Thanks!
