### ISSUE TITLE
My bow

### ISSUE THREAD

**Issue by IEatChickenWingz** [Wynncraft/Issues#5164]
I was doing a quest and I switched servers now my maelstorm bow is gone... Can i have it back or somehing.. Ign: IEatChickenWingz

**Comment by Mininglover21** [comment]
Did you accidentally drop it or have you traded with a friend and clicked it mid trade? Sorry about your Bow being gone but Wynncraft has a strict No-Refund policy.

**Comment by IEatChickenWingz** [comment]
I didn't trade it or drop it I was doing my quest and it disappeared out of my hand...

**Comment by Moe-Ronickah** [comment]
I'll take a guess that you are still using the default MC drop key of "Q".  If you are, switch it to something far away from your normally used keys.  I use "Delete", ever since I dropped a Mythic weapon.

**Comment by IEatChickenWingz** [comment]
Well yeah im using Q but it still doesnt make sense that it disappeared out of my hand..

**Comment by YunoFGasai** [comment]
@IEatChickenWingz most players change their drop key to something on the right end of the keyboard.
what happened to you was that you probably pressed Q which is really close to your movement keys and dropped the bow.

**Comment by Moe-Ronickah** [comment]
It probably didn't "just disappear", @IEatChickenWingz .  I suspect, as Yuno suggested, that you accidentally hit the "Q" key and dropped the bow, while you were busy doing something else, and didn't notice it.  Please change your drop key to another key, far away from left side of your keyboard, to something that you would rarely get near in-game.  More likely than not, that will solve your issue.
