### ISSUE TITLE
Level 3 Meteor is bugged. ( Mage )

### ISSUE THREAD

**Issue by GrapeGuitar** [Wynncraft/Issues#5166]
So, if you get level 3 meteor, it has a fire aura once it lands. BUT if the meteor hits a target it will not be affected by the fire damage. Only the meteor damage. ALSO, if a mob walks into the fire it will only get hit once by the fire damage, not continuously. I can probably imagine this isn't a bug/glitch, considering mage is OP as it is. If this IS a bug/glitch, please fix it.

-Grape

**Comment by Odnod** [comment]
As far as I know, the mob is instantly hurt by the fire ring after it is hit by the meteor, giving the illusion of it taking no damage from the ring, but I would need to do more research. And the fire ring is supposed to only do damage once.

**Comment by Moe-Ronickah** [comment]
Not a glitch.  Confirmed intentional mechanic.
