### ISSUE TITLE
Rymek -  I teleported where I shouldn't have

### ISSUE THREAD

**Issue by Latexi2001** [Wynncraft/Issues#5168]
In Rymek you can get stuck inside the stalls and i got inside of one and now i cant get out.  come teleport me out

**Comment by Moe-Ronickah** [comment]
If you try to tp everywhere and it doesn't work, and if you have no tp scrolls to another city, you will need to use /kill to get out, but only if you have more than 3 soul points.

**Comment by Latexi2001** [comment]
Ok thanks!

**Comment by Latexi2001** [comment]
I didnt teleport i got inside the stall by opening the trapdoor wich shouldnt be able to open and i got inside but i couldnt get out
