### ISSUE TITLE
How is this possible?

### ISSUE THREAD

**Issue by SteveClinton** [Wynncraft/Issues#5170]
Am i dreaming or why is this guy lvl 101?

![2016-06-06_20 18 45](https://cloud.githubusercontent.com/assets/15172127/15832837/5090b52c-2c24-11e6-801b-166794a65e93.png)

**Comment by YunoFGasai** [comment]
level 101 is possible and requires the same amount of xp as level 1-100.
currently I only know of five players that are 101.

**Comment by SteveClinton** [comment]
? i thought the limit is lvl 100

**Comment by SteveClinton** [comment]
oh ok just saw that its possible :P ill close that issue
