### ISSUE TITLE
Horse movement bug

### ISSUE THREAD

**Issue by CharlieDowns** [Wynncraft/Issues#5171]
Hello, I am reporting a issue where if you move with your horse, you sometimes see unloaded chunks, get teleported or attacked mysteriously by that zombie you were running away from, as if the server missed some movement packets.

This is can For Example be reproduced by using a horse and continuously walking through the Detlas sandclocktower hall.
You will notice how sometimes when you get of the horse, you end up teleporting to sides of the tower where you just came from looking like you somehow got stuck.

If needed, I can revert to 1.8.9 temporarily (1.9 forge is kinda unstable right now) and install a camera mod like [Minema](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280148-minema-3-0-the-smooth-movie-recorder/), then record the issue and upload to [Vidme](https://vid.me).

I found about this while playing with a assasin class, but noticing while on a horse pigmen attacking me from 20 blocks away and when getting off, teleported to said pigmen or suddenly teleporting into river from a bridge.

**Comment by YunoFGasai** [comment]
1.9 hirses are glitchy in wynn, try using 1.8 instead.

**Comment by Trixter313** [comment]
Let us know if trying 1.8 instead fixed your issues. Thank you! =)

**Comment by CharlieDowns** [comment]
Yup, if you use 1.8.9, you will not experience this issue and horses will work as expected.

Also, not sure if useful, but I noticed horses movement behavior in 1.9-1.10 being more strict, where as in 1.8 horse movement is looser as in if you move or turn around it feels elastic.

Anyway, if there is no fix to this except using 1.8.9, this issue can be closed.

**Comment by Moe-Ronickah** [comment]
@CharlieDowns ,I'm using this, without any problems:
forge-1.8.9-11.15.1.1722-installer-win.exe
liteloader-installer-1.8.9-00-SNAPSHOT.exe
mod_voxelMap_1.6.7_for_1.8.9b.litemod
OptiFine_1.8.9_HD_U_H5.jar

Maybe that forge and liteloader combination will work with your other mods?

**Comment by CharlieDowns** [comment]
Hello, I know a Forge and Liteloader envoriment exists for mod makers on 1.8.9, but certain bug fixes in '[Matmos](https://github.com/Sollace/MAtmos/releases)' such as game crashes on certain items, memory leaks which annoyed me only exists on 1.9.

Also a recoursepack which I really like called '[Ragecraft](http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/2128869-16w20a-ragecraft-faithful-64x64-a-traditional)' only has the main pack on 1.8.9, not the addons are the real points which make the texture pack great.
