### ISSUE TITLE
Enderchest Pre-Update Items.

### ISSUE THREAD

**Issue by AlternateFlows** [Wynncraft/Issues#5172]
I have some arrows stuck in my enderchest that I can't remove or move.  What do I do or do I get an admin to help? Also I've had these arrows before the gavel update when archers needed to have arrows in their inventory.  I need help removing them.  Also, if they are in my possession will that result in a ban?

**Comment by ThunderRemix** [comment]
Dupe of #3147 or a similer issue.

**Comment by Moe-Ronickah** [comment]
don't worry about a possible ban, it's not a problem.  getting rid of them is the problem.
