### ISSUE TITLE
Pink Wool

### ISSUE THREAD

**Issue by JustCrona** [Wynncraft/Issues#5173]
I purchased a pink wool and gave it to the bandit on the Wrath of the Mummy quest, and the bandit repeated his text and didn't allow for entry. Help?

**Comment by JustCrona** [comment]
I should clarify that while I did lose the wool, I got my emerald blocks back. Please look into this glitch so other players don't get confused please :)

**Comment by Moe-Ronickah** [comment]
this sounds more like a severe lag spike or a server rollback.  there is no way for the bandit to give you money, it's just not possible.

**Comment by JustCrona** [comment]
Alright, thanks anyway!
