### ISSUE TITLE
Pelier

### ISSUE THREAD

**Issue by Dennisdao123** [Wynncraft/Issues#5175]
![2016-06-06_21 45 34](https://cloud.githubusercontent.com/assets/19791032/15846285/757adc30-2c30-11e6-94d4-d8dd83f7e32a.png)

My pelier was unidentified when there wasn't a gavel update and it's now glitched out and it doesn't give me any HP and any id's

**Comment by YunoFGasai** [comment]
some items didn't get updated with the update.
you are allowed to own them but trading them is bannable.
they do absolutely nothing but take an inventory slot.

**Comment by YunoFGasai** [comment]
also they wont get updated to the new version

**Comment by Moe-Ronickah** [comment]
Not an issue, just a change in mechanics.
