### ISSUE TITLE
Visage avatars use usernames

### ISSUE THREAD

**Issue by unascribed** [Wynncraft/Issues#5176]
Your Visage avatars on player stat pages (e.g. https://wynncraft.com/stats/player/Aesen) are using usernames instead of UUIDs. This form of using the API is slow and discouraged, and generates excess requests and redirects that are better handled on your end.

I don't know how your database schema is, but I'd imagine it has UUIDs in there somewhere. It's a lot faster and has less chance of breaking if you use them. (Visage will accept dashed or dashless UUIDs, though dashless is preferred.)

Thanks for using Visage!

P.S. The page will also reflow when images load, as you don't specify a width or height for the img tag. You really should!

**Comment by YunoFGasai** [comment]
wynn is using custom coded everything so we had problems adapting to UUIDs (that's why guilds are fucked up).
it is being worked on and will hopefully be sorted out soon.

**Comment by Moe-Ronickah** [comment]
This request has been passed along to the admin team.

**Comment by Trixter313** [comment]
This might be a better fit in the suggestions area on the forums but I'll let you guys decide. There more players will see it and they will be able to like the post to show that it is a very wanted feature. Just make sure to explain it in a layman form as well so people can see how it would benefit them also if you do post it there. =)

**Comment by unascribed** [comment]
This is mostly a technical issue with little-to-no end-user effect, so posting it on the suggestions forum (where I also won't get notifications -- remember, I'm not a player on your server, I just run Visage) won't be terribly useful.

**Comment by Trixter313** [comment]
Ah, I didn't realize you were associated with Visage. I thought you were a developer of sorts who played Wynncraft and wanted to make use of it. Thank you for reaching out to us to help try to improve our system! =)

**Comment by Moe-Ronickah** [comment]
RESOLVED
