### ISSUE TITLE
Beacons are Broken...

### ISSUE THREAD

**Issue by DCM627** [Wynncraft/Issues#5179]
![2016-06-07_10 45 33](https://cloud.githubusercontent.com/assets/19480434/15862256/21839f64-2c9d-11e6-871c-e14908cc151e.png)

I found this glitch while doing the Aldorei's Secret Part 2 parkour. If you interact with a beacon, it workss like normal minecraft! This gets so annoying and made the parkour all the more challenging. I have yet to complete it, partially due to this.

**Comment by Moe-Ronickah** [comment]
Beacons aren't broken.  They are used, as they are, as part of the challenge.
