### ISSUE TITLE
Stuck in The Mansion

### ISSUE THREAD

**Issue by NESZapper** [Wynncraft/Issues#5180]
While I was warping around the Nemract Mansion for fun, I became stuck in a room, which I assume is supposed to be off limits, as it has a redstone circuit leading to a new room. I am unable to teleport out, and I don't have any scrolls.
[http://imgur.com/lStQiON](url)

**Comment by YunoFGasai** [comment]
use /kill if you have more than 3 soulpoints
also can you get me the cords of that room so we could fix it?
thanks,
Yuno

**Comment by NESZapper** [comment]
Sure, here are the coordinates:
x 209, y 51, z -2179
These may be slightly off, but you should be in the room at that location.

**Comment by ThunderRemix** [comment]
[http://imgur.com/lStQiON](url)

**Comment by ThunderRemix** [comment]
[http://imgur.com/lStQiON](http://imgur.com/lStQiON)

**Comment by TheBlobMiner** [comment]
https://www.youtube.com/watch?v=GxUiTaQvxpA just like him, /kill

**Comment by Moe-Ronickah** [comment]
RESOLVED
