### ISSUE TITLE
Accessories

### ISSUE THREAD

**Issue by NESZapper** [Wynncraft/Issues#5182]
I am unable to equip any accessories. I have tried relogging, switching servers, quitting out of Minecraft, but nothing is working.

**Comment by YunoFGasai** [comment]
can you hover over the accessories take a screen shot and put it on here?

**Comment by Moe-Ronickah** [comment]
Make certain that you have the requirements, usually levels, for the accessories.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
