### ISSUE TITLE
Stuck in wormy holes...

### ISSUE THREAD

**Issue by EnderKing567** [Wynncraft/Issues#5183]
I was doing "The Worm Hole" quest when I fell into a 1 by 1 hole with a web in it. I was unable to jump or use the escape spell to leave and had to /kill myself. Here are screenshots of the incident.
![2016-06-08_13 02 28](https://cloud.githubusercontent.com/assets/19824497/15905459/957a2e78-2d7a-11e6-9055-6f1396199ad5.png)
![2016-06-08_13 02 26](https://cloud.githubusercontent.com/assets/19824497/15905466/9ace9da0-2d7a-11e6-931c-5384fbe93586.png)

**Comment by YunoFGasai** [comment]
that's a pretty smart trap (I'm sure it was unintentional)
@AckroWynn can you fix this on the build server?

**Comment by Moe-Ronickah** [comment]
It's posted on the forums.

**Comment by Villageacules** [comment]
There were a lot of those in that area, all fixed, will be pushed in the next update. Closed.
