### ISSUE TITLE
Jungle Fever Glitch

### ISSUE THREAD

**Issue by SquidSplashing** [Wynncraft/Issues#5184]
I was returning the 64 almuj Liquified Emeralds to Worid when suddenly i decided to open a chest and i lost a liquified emerald which was supposed to be a "Quest Item" i thought it was probably just a screen glitch so i changed hubs and re-loged but then i noticed it wasn't a visual glitch and i actually lost a liquified emerald which was from the quest, and now i cant complete Jungle Fever quest. (I also opened a chest to see if i could get the emerald back but instead i just lost another Liquified Emerald, Please reply as soon as possible)

Some Proof:https://gyazo.com/66d7c0796975d5fccd37485e858f4797

https://gyazo.com/66d7c0796975d5fccd37485e858f4797

**Comment by YunoFGasai** [comment]
Try using /fixquests

**Comment by Trixter313** [comment]
In this specific situation, just /fixquests probably won't work. You need to get rid of the 63 liquefied emeralds and then use /fixquests. To get rid of them, fill your inventory completely and stand over am item then drop the liquefied emeralds. Then you should be able to use /fixquests and complete the quest. =)

If that solves your issue, please let us know and close the issue. Thanks!

**Comment by Moe-Ronickah** [comment]
@SquidSplashing , there are 30 closed issues concerning "Jungle Fever", many of which pertain to your issue, and discuss how to solve it.  Please use the instructions for doing searches, before posting an issue, as it will save everyone time.  Thanks.
