### ISSUE TITLE
I cannot leave the Nether

### ISSUE THREAD

**Issue by JCPie** [Wynncraft/Issues#5186]
Hey Guys, I cannot leave the nether. /leave doesnt work, and when I go throught the portal, I go to the lobby. That good I guess? But when I log back in, I will spawn inmediately in the nether. AGAIN. What do I need to do to leave the nether and go further with my quests? Plz help me. 
Btw sry for my English, Im kinda noob at it xD

**Comment by Moe-Ronickah** [comment]
When you log in, you are in the Nether.
You can leave the Nether, go to the lobby.
Can you go from the lobby into a game world?

**Comment by JCPie** [comment]
Nope, when I try it, I will spawn in the Nether. Again...

**Comment by YunoFGasai** [comment]
Did you enter the nether from the portal in the roots of corruption?

**Comment by JCPie** [comment]
Yeah
Is that a bad thing?

**Comment by JCPie** [comment]
And if it cannot go any worse, I spawn in a few blocks of obsidian. Now am I really, REALLY STUCK

**Comment by JCPie** [comment]
Ok RIP wynncraft this isnt normal?! I spawn with a new class in the end..?

**Comment by JCPie** [comment]
Yeah.. I cannot play ever again Wynncraft.. I spawn always in obsidian blocks right now.. :'(

**Comment by Trixter313** [comment]
Does the command /kill at least get you out of the obsidian?

**Comment by JCPie** [comment]
Trixter. You. ARE MY HERO!!!!! Im out of the Nether :D <3 ty

**Comment by Trixter313** [comment]
Oh wow, that's great to hear! Enjoy your time playing Wynncraft =)

**Comment by JCPie** [comment]
Ty :)
