### ISSUE TITLE
Unopenable Loot Chest

### ISSUE THREAD

**Issue by DeanAyalon** [Wynncraft/Issues#5187]
Hi, I have found an inoperable loot chest on your server, with a block on top.
Bummer, from its white sparkles, I am pretty sure it contains some awesome loot....
Here's a screenshot:
![screen shot 2016-06-09 at 8 53 37 pm](https://cloud.githubusercontent.com/assets/19843319/16174170/fc2b8d5e-35bf-11e6-943a-de722de01529.png)

**Comment by Villageacules** [comment]
Fixed, should be pushed in the next update. Closed.
