### ISSUE TITLE
Horse Movement Issue in MC 1.10

### ISSUE THREAD

**Issue by NinjaPiggy** [Wynncraft/Issues#5188]
So I was just riding along the treetops of Nivla Forest, then suddenly I was taking damage.
I was really confused, so I hopped off my horse and...
I was below the tree, getting swarmed by Forest Spiders.  My horse had been teleported down there with me.
I got back up, then continued riding, thinking that it was a one-time oddity (nothing like this had ever happened to me before).
Then it happened AGAIN.
I came here to report it.
I was using Minecraft version 1.10, very recently released at the time.

**Comment by NinjaPiggy** [comment]
It happened again, except this time I had been teleported backwards, getting assaulted by Wild Snow Wolves near Nesaak.
The weird thing about this was that I had been teleported into the corner of the building right near the bridge to Nesaak (X:19, Z:899), a building I had passed right by a moment earlier.
I only get teleported upon dismounting, and the taking damage before dismounting only makes the screen shake and makes the *tick* noise that comes with taking damage, my health does not seem to deplete.

**Comment by Trixter313** [comment]
Wynncraft isn't 1.9 or 1.10 ready yet. We reccomend using 1.8 until it is. Let us know if switching to 1.8 fixes the issue for you, thanks!

**Comment by NinjaPiggy** [comment]
Okay, Thanks!

**Comment by CharlieDowns** [comment]
Hello NinjaPiggy,

Your issue which is caused by a change in horse movement behaviour in 1.9 is related to my issue [#5171](https://github.com/Wynncraft/Issues/issues/5171) which I closed yesterday.

The temporary fix is to use a older Minecraft version like 1.8.9.
Most mods and resourcepacks you might use should have a version existing for it 1.8.

**Comment by Moe-Ronickah** [comment]
Wynncraft is based on version 1.8.  This movement issue is a Minecraft version issue.  If you use any MC version higher than a 1.8.x version, you do so at your own risk.  Please use a MC 1.8.x version for playing Wynncraft.  Note: Some players have had no trouble with 1.10, but this isn't always the case.  I wish that we knew what the difference was.
