### ISSUE TITLE
I lost my stuff on my class

### ISSUE THREAD

**Issue by omgDjBannana** [Wynncraft/Issues#5189]
I logged in to my lvl 88 mage and i was checking my inventory and my diablo my bob's mythic were turned into Oak wood sticks
my Grvaes of honor were gone i have proof that i haad those items in my screenshot folder.
Fix this pls

**Comment by Trixter313** [comment]
How many soul points did you have when you logged in? When you die with less than 3 soul points your items drop and you get the oak version of your classes weapon. Also, is there any other information or any other details? Thanks!

**Comment by omgDjBannana** [comment]
i had 4 soul points

**Comment by omgDjBannana** [comment]
but the thing is my ethreal ddint turn into oak wood sticks
and i lost my chestnut and my graves of honor as well

**Comment by Moe-Ronickah** [comment]
After a lot of checking, it appears that you died multiple times and lost your items.  You were fortunate enough to keep your Ethereal.
