### ISSUE TITLE
I lost everything and im invisible. Glitch?

### ISSUE THREAD

**Issue by Madzelia** [Wynncraft/Issues#5191]
This was after a server reset, I logged back into my account and all my armor, emeralds, weapons are all gone. My stat points are still intact, plus I only have 1 soul point now and it doesnt get regenerated. I know I never died because before I got disconnected I had 8 soul points. I have restarting my minecraft 5 times. Still the same. Please do help. I have another character that is level 50 and it isnt glitched so its just this character. ._.

Also my friend says he cant see me so I must be invisible as well. U

If required my username in game is xMadi.

Some pics:
![screenshot_28](https://cloud.githubusercontent.com/assets/19853823/15958342/5f3c4782-2f38-11e6-97a9-696a57dfdc46.png)

**Comment by Madzelia** [comment]
So I searched around and found out that I mustve died 4 times to be able to lose 8 soul points but I dont understand, when you die you get teleported to the nearest location which is detlas, but then I would only have 6 soul points. So there wouldve been a glitch where MOBS teleported with me and one shot me over and over again. I dont even understand how I died if I just left with the server reset. So stupid. Even though im level 18, this shouldnt be happening to anyone after a reset.

**Comment by Trixter313** [comment]
Did you mean to close the issue or was it accidental?
