### ISSUE TITLE
I went to Ragni, but I don't know how

### ISSUE THREAD

**Issue by surpriseMDF** [Wynncraft/Issues#5192]
im lvl 37 archer i just try to get high place and i got too high and its teleport me before ragni

**Comment by surpriseMDF** [comment]
plis fix

**Comment by surpriseMDF** [comment]
x825 z-1587 i was there and its happend

**Comment by Moe-Ronickah** [comment]
See that little pencil icon in the upper right of each of your comments?  It's an edit button.
No matter how high you get, you won't get tped to anywhere else, it's just not in the game.  Perhaps you fell and died or perhaps you had a Ragni tp scroll in your hotbar and you accidentally used it.

**Comment by YunoFGasai** [comment]
you mean that you got teleported to the starting quest area?

**Comment by surpriseMDF** [comment]
yes

**Comment by Villageacules** [comment]
According to these coordinates, you flew out of the top floor tower of ascension into the sky. Sounds fishy, unless you gave the wrong coordinates.
Did you glitch out of the arena and then fall to your death in the void, but you spawned in the tutorial area? That's quite common.
