### ISSUE TITLE
Ocean bug

### ISSUE THREAD

**Issue by HRJDragon** [Wynncraft/Issues#5203]
# Delete this line if you've searched for a duplicate issue first
I have tried to travel from Selchar to Llevigar, although when I pass the volcano island, I "Time out" or just plain teleport back to Selchar, losing 2 soul points. I feel entirely fed up of going there as i Will drop all my items in the middle of the ocean. I know this is not my client, as sometimes I stay on wynn and don't time out, just teleport. Please fix the mechanics of boats, or just get me to Llevigar to start a quest as I;m pretty much fed up.

**Comment by YunoFGasai** [comment]
What game version are you using?

**Comment by Moe-Ronickah** [comment]
Boat mechanics are buggy.  I suggest that you move in a boat for a count of 7 seconds, then drift for 4 seconds, and repeat this all the way to your destination.

Wynncraft is NOT 1.9 or 1.10.  Those updates will take quite a well to meet.  We suggest that you use 1.8.9.

**Comment by HRJDragon** [comment]
Using a version like 1.9.4
Will try out a boat with 1.8.9 although I just made it to Llevigar with my escape spell which took half an hour...
