### ISSUE TITLE
Problem with Wynnexcavation Site A

### ISSUE THREAD

**Issue by Habiii** [Wynncraft/Issues#5204]
Hey I have a problem talking about the quest WynnExcavation Site A does not work it sthet I want to Tesh and then goes on once the quest not Tesha say : but Take That to vade and dont read it and then I'll go to vade and he says something the book still stands I want to Tesha

**Comment by Moe-Ronickah** [comment]
Please do a search for open issues on Site A, and see if any of those resemble what is happening to you.
