### ISSUE TITLE
java.net.ConnectionException

### ISSUE THREAD

**Issue by AwesomeQuinton** [Wynncraft/Issues#5207]
"Could not connect to default or fallback server, please try again later: java.net.ConnectException" I logged off last night and tried to get back on today, after restarting my computer and checking my firewall settings I have not been able to reconnect to the server at all today. Please help.

**Comment by Moe-Ronickah** [comment]
If play.wynncraft.com isn't working for you, then try play.wynncraft.net and play.wynncraft.org.They are exactly the same server, but, for some reason, they seem to be handled differently by the main server.  It's also possible that while one isn't working NOW, it will work in 5 min.  If you are still having trouble, shut down Minecraft, wait 5 min., then try again. Sometimes, it takes 2 or 3 tries to get in, sometimes more, but you will get in.  Did this solve your issue?

**Comment by AwesomeQuinton** [comment]
All of the different addresses come back with that same error, I left my computer off all night and came back to the same error. The same error has been there for 2 days now.

**Comment by Shadoweagle5098** [comment]
I'm not sure of this, but I think I had the same error as you. If you've already restarted your computer and that hasn't worked, try using direct connect

**Comment by AwesomeQuinton** [comment]
Using direct connect does not work for any of the different ip connects.

**Comment by Moe-Ronickah** [comment]
OK, the next step is to make certain that your MC launcher is up to date.  After that, you try deleting the wynn ips from the launcher, shut down MC.  Wait 5-10 min, restart MC, then put the wynn ips back in.

**Comment by AwesomeQuinton** [comment]
It just allowed me to log in, I uninstalled MC and Java then reinstalled them, now it works. Thank you for that idea though.
