### ISSUE TITLE
Warrior Skill-Charge Tier 3 Bug

### ISSUE THREAD

**Issue by LordPotatoz** [Wynncraft/Issues#5210]
The warrior skill charge tier 3 adds on the aerodynamics where you charge twice, adding on a second charge after the initial charge of tier 2. But sometimes the second phase where the player can switch directions in the air doesn't activate, in other words only half of the skill activates. This occurs about 60% of the time and sometimes it activates the tier 3 charge only after spamming the skills for several times. Not sure if this is a bug in coding or something, but it is definitely frustrating as the tier 3 skill shouldn't be the same as tier 2 skill.

**Comment by Moe-Ronickah** [comment]
If you hold down your spacebar, you can double charge with warriors at tier 1.  This is really an effect of whether or not the terrain allows you to "skip", as in hop, skip, and jump.  Try charging across a flat surface both with, and without, holding down your spacebar, and let us know if you see a difference.

**Comment by LordPotatoz** [comment]
Well the second charge has the aerodynamics part in it so if the tier 1 skill can also double charge and it also has aerodynamics then... isn't that a bug? Well I tried jumping it just made the second charge go up higher and has this charging downward effect where as without jumping it would just charge straight as you would automatically go down because of gravity. Even with the jump sometimes there wouldn't be the second charge.

**Comment by Moe-Ronickah** [comment]
It's not a bug actually, it's an effect that you can get, if you happen to time it correctly.
