### ISSUE TITLE
Memory Paranoia [Spelling Mistake]

### ISSUE THREAD

**Issue by DalekCaan2** [Wynncraft/Issues#5212]
In Memory Paranoia, the NPC by the entrance "Check" is spelt wrong. This spelling of "Check" does not mean a Cheque in a monetary way. The correct spelling is "Cheque" -- I would like to point out several search engines and sites agree with me, Especially since "Cheque" is a noun, because it is a name of a thing.
![cheque](https://cloud.githubusercontent.com/assets/19890049/15991389/90520fe2-30a9-11e6-817c-2ce962d34253.png)

**Comment by Trixter313** [comment]
Are you outside of the US? It appears that the difference just differs in location, US being check and most other places being cheque. I've never seen it spelled the q way. http://grammarist.com/spelling/check-cheque/

**Comment by DalekCaan2** [comment]
Ah so its only the US that use that spelling, thanks!

**Comment by Trixter313** [comment]
Happy to help =)
