### ISSUE TITLE
Stuck in a Caravan

### ISSUE THREAD

**Issue by Romumu31** [Wynncraft/Issues#5214]
I just completed the Green _Skinned Trouble quest_ but I teleported "under" the caravan of the detective. I accidentally dropped my boots and I am stocked under the caravan, I cannot TP or anything.
Could you help me ?

**Comment by Trixter313** [comment]
Oops, sorry, I thought I answered this but I think I forgot to send the comment. Seeing that you closed it, you probably already got out but just in case, you can use the command /kill with 3+ soul points and it should get you out.
