### ISSUE TITLE
The Angry village quest bug.

### ISSUE THREAD

**Issue by HonzaSTECH** [Wynncraft/Issues#5217]
Hi. I discovered a bug in the Angry village quest. When I tell to Lekal, he wants 5 potatos and 3 potion of drunkness, but I finished the quest with 5 potatos and only 1 potion of drunkness. Sorry for my nad English.

**Comment by HonzaSTECH** [comment]
*bad English

**Comment by Moe-Ronickah** [comment]
Thanks for reporting this.  We will have a GM check this out.

**Comment by AckroWynn** [comment]
Fixed! Removed the requirement of three bottles, and put a requirement of only one.
