### ISSUE TITLE
That's a Hole...

### ISSUE THREAD

**Issue by DCM627** [Wynncraft/Issues#5218]
There's a nice 1x1x1.5 hole in the Llevigar Plains / Pre-Light forest.
![2016-06-12_18 20 46](https://cloud.githubusercontent.com/assets/19480434/15994169/339ccf04-30cb-11e6-9572-2c862028a70b.png)
There are the coords. I know this isn't really a bug, but this is the best place to put it.

**Comment by ASHcraft04** [comment]
type /Kill

**Comment by DCM627** [comment]
I know that is one solution, but from all the holes people come across in Wynncraft, we would have to /kill so many times, we'd lose all our stuff. An easier solution is to just have the admins of this forum put it on a list for the builders to fix. I know how to /kill... You'd think if I got to level 82 that I might know something about the game's mechanics.

**Comment by YunoFGasai** [comment]
Will add to the forum list when I will have access to my computer again.

**Comment by DCM627** [comment]
Thanks! I would have, but I don't want to post much public on the forums yet. I'm gonna close this now...

**Comment by YunoFGasai** [comment]
added to list
