### ISSUE TITLE
Bug in the quest: Jungle Fever

### ISSUE THREAD

**Issue by gui140** [Wynncraft/Issues#5219]
Hey, my name is IC3L0rD in Minecraft, I play in the Wynncraft server and I am a archer level 53, and I and my friend was made the quest Jungle Fever, but in the middle of the quest when you have to talk with a Almuj's Banker and he give to you 64LE, I receive only 63LE, so I can't finish this quest.

Sorry if I type a wrong word, I am Brazilian and don't know write in English very well.

**Comment by Trixter313** [comment]
Don't worry! All you need to do is get rid of the 63 LE you have right now and then use the command /fixquests

To get rid of the LE, simply fill up your inventory and drop it while standing on another item.

That should fix it! Comment back letting us know if it helped or if you have any more questions. Thanks!
