### ISSUE TITLE
Literal Hole in quest Forbidden Prison #Stage 5

### ISSUE THREAD

**Issue by CharlieDowns** [Wynncraft/Issues#5223]
Hello, I found a hole with a small tunnel which ends up nowhere in quest Forbidden Prison #Stage 5.

Presumeable this hole was either made by a 'Rioting Prisoner' trying to escape by making a tunnel (which failed so he died of hunger) or a Builder poked a hole into the map and fabric of reality.
This hole is deep enough so Assasins and Warriors can not escape. Mages and Archers*(not tested) can escape.

For Reference: https://imgur.com/sTrllTA

**Comment by Moe-Ronickah** [comment]
Thanks, Charlie.  We will pass this along to a builder to get it fixed.

**Comment by YunoFGasai** [comment]
added to hole thread

**Comment by Villageacules** [comment]
Fixed, should be pushed in the next update. Closed.
