### ISSUE TITLE
Alice bug issue

### ISSUE THREAD

**Issue by ASHcraft04** [Wynncraft/Issues#5224]
I am on Wynncraft and I am trying to complete the "Creeper Infiltration" quest. I was told to get 18 string, Green Powder 1, and 3 blocks of wool, so I did. went to Alice in Detlas and she would accept the items. I tried re-loging and deleting the server and add it again. I do not know what to do. Anything would help.

**Comment by Trixter313** [comment]
Could you post a screenshot of the items you've gathered and of what it says in your quest book? Thanks!

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
