### ISSUE TITLE
Lost an item

### ISSUE THREAD

**Issue by LightAura** [Wynncraft/Issues#5225]
I had a really good weapon The stabsand when i had a bug and it disapeared ! Please can u give it to me !
I really need it ! 
Have a good day

**Comment by Moe-Ronickah** [comment]
Is your drop key still set to "Q"?  Was the Stabsand the first item on your hotbar?

**Comment by YunoFGasai** [comment]
@Hutsalot is your drop button set to Q?
If it is you might want to change it to prevent future accidents.

**Comment by Hutsalot** [comment]
@YunoFGasai My drop button is set to Q, but I'm absolutely sure that I didn't press the button by accident.

**Comment by YunoFGasai** [comment]
Try changing it to something farther away and return to us if it happens again.

**Comment by Moe-Ronickah** [comment]
"I'm absolutely sure that I didn't press the button by accident."  Except that "Q" is right next to "W" and this is THE most common cause of losing a single item.  Hence, move your drop key to something near "Delete", please.
