### ISSUE TITLE
no hp steal

### ISSUE THREAD

**Issue by CheeseLover** [Wynncraft/Issues#5226]
Hi
i just wanted to say that i was grinding on mobs to get level up but when they hit me they do allot of damage. But then my hp steal doesn't work so well so i cant get some hp without using any potions
thats been realy anoying and caused me to die allot can you pls fix this

**Comment by YunoFGasai** [comment]
Health steal now works randomly when you hit a mob.
Check if you got negative health regen on any equipment.

**Comment by CheeseLover** [comment]
i dont have any negative health steal
but thanks

**Comment by Moe-Ronickah** [comment]
RESOLVED
