### ISSUE TITLE
Slow Attack Speed Weapon Glitch

### ISSUE THREAD

**Issue by DaNarwhalChannel** [Wynncraft/Issues#5229]
# Delete this line if you've searched for a duplicate issue first
There has always been a glitch after the Gavel Update where Slow Attack Speed weapons (any type) will not cast spells properly. For example, with a bow, you would click |Right-Left-Left| for bomb spell, but it would simply name itself "Right-Left-Left" and stay that way until you tried to cast again or it simply faded away. I find this very annoying whenever I find an enemy that is resistant to all enemies, and my Bob's Mythic Bow repeatedly fails at spell casting, costing me many soul points and up 15-30 minutes to get back to where I was after dying. I find this glitch extremely annoying when I am about to complete a quest and some mobs kill me because I cost Bomb Arrow and it did nothing.

**Comment by YunoFGasai** [comment]
After some testing it seems this happens with all weapons and happens because of server lag

**Comment by Moe-Ronickah** [comment]
It's an unavoidable game mechanic, unless the admins decide to change to the speed of "slow attack" weapons.  You just have to get used to timing your mouse clicks for slow weapons so that they work.
