### ISSUE TITLE
resource pack not downloading

### ISSUE THREAD

**Issue by kenny250** [Wynncraft/Issues#5231]
when I load in to your server I am given a prompt to download the resource pack. I click yes it says the resourse pack was not able to download. I am unsure whether this is a problem on my computer or your server.

here are some screen caps
![capture](https://cloud.githubusercontent.com/assets/19943709/16067795/86575174-3274-11e6-89f9-166366bb3ec6.PNG)
![capture1](https://cloud.githubusercontent.com/assets/19943709/16067797/88f67f36-3274-11e6-9ab1-9e1211813619.PNG)

this time the prompt didn't even ask me  if i wanted to use the pack.

**Comment by Trixter313** [comment]
Have you tried deleting the resource pack, located in .minecraft > serverresourcepacks?

**Comment by Moe-Ronickah** [comment]
1. Go to [this page](https://github.com/Wynncraft/Issues).  At the top of the list is latest Resource Pack, click on it.
2. Read the instructions on that page.
3. Click on the "View" button.
4. On the next page that opens, click the "Raw" button.
5. Save the file.
6. Follow the instructions that you read in step "2", above.

**Comment by Trixter313** [comment]
Closing due to no response.
