### ISSUE TITLE
Guild

### ISSUE THREAD

**Issue by Masterpringles** [Wynncraft/Issues#5236]
Why i cant leave my guild with ./guild leave. I do this i only lost my soul points but im still in the guild. Why?

**Comment by Trixter313** [comment]
What is your Minecraft username?

**Comment by Masterpringles** [comment]
DemonHD

**Comment by Masterpringles** [comment]
Can you help?

**Comment by Trixter313** [comment]
I see that you've changed your name before. Unfortunately there's nothing you can currently do to fix it, it's an issue staff has to fix.

You can follow the original issue, #3665 for updates. Thanks!
