### ISSUE TITLE
Pack Issue in a Mac

### ISSUE THREAD

**Issue by SirBoneapart** [Wynncraft/Issues#5238]
My pack wont work iv restarted minecraft iv deleted and re-added the server the worst part is that i'm used to windows (I'm using a macbook pro now) so i wouldn't know how to get into %appdata% if i tried

**Comment by Trixter313** [comment]
It appears that on Mac it's located in ~/Library/Application Support/minecraft if that helps at all. If you do find it, try deleting the serverresourcepacks folder.

**Comment by Moe-Ronickah** [comment]
I'll also toss this in here just in case the RP fails to download.

1. Go to [this page](https://github.com/Wynncraft/Issues).  At the top of the list is the latest Resource Pack, click on it.
2. Read the instructions on that page.
3. Click on the "View" button.
4. On the next page that opens, click the "Raw" button.
5. Save the file.
6. Follow the instructions that you read in step "2", above.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
