### ISSUE TITLE
/class Menu Displays Incorrect Number of Finished Quests

### ISSUE THREAD

**Issue by TheDollarBill** [Wynncraft/Issues#5239]
The /class menu incorrectly displays the number of quests that I have finished. Instead, it displays the number of quests that I have **started**, not completely finished.

Here's a gif of my /class menu and quest book. https://gfycat.com/UniformEdibleAmericanbobtail
Note the "101/104" in the /class menu, despite me having many incomplete quests in my quest book.

**Comment by DRedDogPE** [comment]
according to the api there is also only 101 quests.... stuff is broken with the quest count..

**Comment by Villageacules** [comment]
Weird, is this the only class it applies to?

**Comment by Moe-Ronickah** [comment]
RESOLVED
