### ISSUE TITLE
Can't speak to Alein in Frost Bitten quest

### ISSUE THREAD

**Issue by xPanduz** [Wynncraft/Issues#5246]
I can't speak to Alein in Frost Bitten quest. It appears only a no-words line as soon as i right click on the body of Alein. Any suggestions?
![schermata 2016-06-16 alle 22 38 16](https://cloud.githubusercontent.com/assets/19982429/16132517/b076fd7e-3413-11e6-8814-e74e3f60899e.png)

**Comment by Trixter313** [comment]
Hmm, what does it say in your quest book? Thanks!

**Comment by xPanduz** [comment]
Well now it goes, thank you sir! :)

**Comment by Moe-Ronickah** [comment]
Fixed!
