### ISSUE TITLE
Kings recruit quest help.... please

### ISSUE THREAD

**Issue by WolfOfWafflez** [Wynncraft/Issues#5249]
One day i log on to my lvl 54 archer, and notice all my quests are no longer done, so i go and do 9 of them. Then, I realize that Kings Recruit is not started, and i have no way to apprach the king or get to the caravan driver. Help please? Like auto complete the quest?

**Comment by Trixter313** [comment]
Try using the command /fixstart

Let us know if that helps! =)

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
