### ISSUE TITLE
Dub Xp not working

### ISSUE THREAD

**Issue by Peppernado** [Wynncraft/Issues#5250]
# Delete this line if you've searched for a duplicate issue first
So I completed the quest zhight island which gives 45k exp default
Proof: https://wiki.wynncraft.com/index.php?title=Zhight_Island_(Quest)
There was dub xp and i was suppose to get 90k but this is the issue 
http://imgur.com/vR8XEEP

Also I had on some gear with xp bonus(Bobs chest/Jera) but those didnt seem to work wither

**Comment by YunoFGasai** [comment]
the xp amount it says in chat doesn't change but the actual amount it gives changes they way it should
