### ISSUE TITLE
Lost all my items, how am I supposed to get them back?

### ISSUE THREAD

**Issue by Skittlewink** [Wynncraft/Issues#5251]
I recently died in the pigman ravine and dropped all my stuff, now I cant even get into the ravine. How am I supposed to get my stuff back? If there's no way than what is the point to even playing anymore?

**Comment by Skittlewink** [comment]
If that is how the system is supposed to work, than this is one of the shittiest designs I've ever seen.

**Comment by Trixter313** [comment]
When you die with less than 3 soul points, you drop all of your items. We reccomend not leaving the town you're in with less than 3 soul points. To get your items back you would have had to go back to where you died and gotten them back before they despawned. The soul points system is a lot more forgiving than vanilla Minecraft mechanics.

**Comment by Skittlewink** [comment]
that isnt how mmos are supposed to work you realise

**Comment by YunoFGasai** [comment]
skittle to prevent players from just running around and trying to rush high level bosses a death penalty was added, you get to die a couple of times before the penalty happens. this makes the players consider their actions and develop better builds and strategies.
the game warned you when you had 2 soul points and there are server announcements about this all the time. you are on our server you play by our rules. if you have anything else to say you are welcome to post a thread on the forums.
(also if you died in pigman ravine's you were probably under level 30, you can get there in a day)
