### ISSUE TITLE
A bunch of Wynncraft glitches around the map. Also a hacker :|

### ISSUE THREAD

**Issue by Owgla** [Wynncraft/Issues#5252]
So some of these glitches are just plain stupid XD
![2016-05-30_14 40 15](https://cloud.githubusercontent.com/assets/19985469/16138402/f4aa4a8c-342c-11e6-97d5-13366fb82d2e.png)

![2016-05-27_18 08 03](https://cloud.githubusercontent.com/assets/19985469/16138406/0ff2517c-342d-11e6-814b-ef73302dcf17.png)

![2016-04-25_17 10 51](https://cloud.githubusercontent.com/assets/19985469/16138413/3ea4dddc-342d-11e6-8855-148009e52dd8.png)

![2016-04-20_15 03 15](https://cloud.githubusercontent.com/assets/19985469/16138418/579772dc-342d-11e6-9ffc-d6a943c8d0b7.png)

![2016-04-18_13 21 58](https://cloud.githubusercontent.com/assets/19985469/16138432/6d9da998-342d-11e6-96e1-5ce047c41000.png)

![2016-04-18_20 50 59](https://cloud.githubusercontent.com/assets/19985469/16138507/dd1452f4-342d-11e6-9a82-21774a3b50f6.png)

![2016-05-31_18 16 36](https://cloud.githubusercontent.com/assets/19985469/16138541/2e348550-342e-11e6-94e2-2fbfde1535ae.png)

![2016-05-31_18 16 38](https://cloud.githubusercontent.com/assets/19985469/16138542/2e34f6d4-342e-11e6-86f6-9163b0efaf6a.png)

![2016-06-03_23 19 33](https://cloud.githubusercontent.com/assets/19985469/16138568/68dab670-342e-11e6-83ea-e4a08412e206.png)

**Since you can't really see where i am, this is under the lake in one of the orc quests with the detective guy.**
![2016-06-15_13 39 24](https://cloud.githubusercontent.com/assets/19985469/16138579/7d9e2af6-342e-11e6-9699-6479f92796ef.png)

![2016-06-17_01 36 32](https://cloud.githubusercontent.com/assets/19985469/16138589/9e27c5d4-342e-11e6-8cae-f64fcaf93c5c.png)

**Comment by YunoFGasai** [comment]
ill reply to this in the order of the pictures.
1) are you using 1.9a non vanilla launcher?
2) fixed and waiting for an updated
3) try 1.8
4) refer to 1
5) known issue will fix
6) known issue will fix
7+8) cant do anything about it, for all we know he jumped down from the top and you screen'd him twice
9) happens vecause of lag
10) will add to to do list
11) lag

**Comment by Moe-Ronickah** [comment]
Please, do not post multiple issues in a single issue post.
