### ISSUE TITLE
/class not working

### ISSUE THREAD

**Issue by M0RGaming** [Wynncraft/Issues#5254]
hey, I've been playing wynncraft now for about 3 years, and just recently i came across an issue.
when i do /class, the game stops working...
my minecraft is 1.9 forge with optifine and a minimap.
i tried using just strait up 1.9 and it works.
also in my forge 1.9, i use a modified wynnpack, so it doesn't show the purple missing texture boxes.

Thanks for taking the time to read this. I look forward to reading your response.
  -M0R

Also on another note, is there a way to make the "wynnpack not loaded" message in chat go away? I'm using a downloaded version of the wynnpack.

**Comment by YunoFGasai** [comment]
try using vanilla 1.8, 1.9 versions are compatible with wynn but cause some problems.
about the wynnpack @Moe-Ronickah can help you with that better than I can.

**Comment by Moe-Ronickah** [comment]
There is currently no known way to stop the "wynnpack not loaded" message.

If 1.9 works, but 1.9 with Optifine and a minimap does not, the error is in either Optifine or your minimap.  As Yuno said, try using 1.8.  I'm running 1.8.9 with Optifine and a Voxelmap, without any problems.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
