### ISSUE TITLE
Bug with the mobs...

### ISSUE THREAD

**Issue by LightAura** [Wynncraft/Issues#5258]
Hi,
I cant hit mobs anymore ! 
I dont know why it does it but please can u fix it i want to play on this server !
Have a good day.

**Comment by YunoFGasai** [comment]
It may be that you are in a duel.
Try relogging

**Comment by Moe-Ronickah** [comment]
Fixed, or still happening?

**Comment by thecoolkogut4** [comment]
this is a bug with the server which happens every so often. it was not just you. salted is aware of this. when this happens you also can't spawn in horses (if its the bug you were talking about). if you were able to spawn in horses then its what the people said above me, you were most likely in a duel, or if its reoccurring its something else. but if it was just that one time on that one server, the staff are already aware of it.

**Comment by Moe-Ronickah** [comment]
1:  Where you in a duel?
2.  Was it the issue where you could not interact with any mob?

We can't help to fix something if we don't what has happened.
