### ISSUE TITLE
Horse Glitch

### ISSUE THREAD

**Issue by AgentPanda** [Wynncraft/Issues#5259]
Hey guys,
so today I was at the Mesa and I was riding my horse and then I died by some mobs. Somehow my horse saddle then disappeared out of my inventory and I didn't drop it.
IGN: AgentPanda_ (Yeah, I know its not required)

**Comment by Moe-Ronickah** [comment]
I'm sorry, but losing items randomly happens when players die.  The admins are aware of it, and are working on it.

duplicate of #3153 .  Please follow and comment on this issue there.

**Comment by AgentPanda** [comment]
Is there any way to get my horse back?

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strict no refunds policy so we can't give you a horse back but we are working on fixing it so it doesn't happen again!
