### ISSUE TITLE
Armour Disappeared 

### ISSUE THREAD

**Issue by CosmicSound** [Wynncraft/Issues#5263]
I was grinding mobs for XP near Troms when the server I was in restarted. When I logged back into another server all my armour except for my pants were gone. I restarted the game and checked my inventory and it was nowhere to be found. Is there any reasonable explanation for this?

**Comment by YunoFGasai** [comment]
was you inventory full?

**Comment by CosmicSound** [comment]
Actually, I think it was... but still, why would it go into my inventory in the first place?

**Comment by Trixter313** [comment]
The part about the items coming off is issue https://github.com/Wynncraft/Issues/issues/4120 & the part about it disappearing is issue https://github.com/Wynncraft/Issues/issues/3153

We're working on fixing the issues so it doesn't happen again!
