### ISSUE TITLE
Suddenly lost my Assassin class?

### ISSUE THREAD

**Issue by DarkBacca** [Wynncraft/Issues#5266]
Midgame, I did /class and I didn't see the Assassin option. I didn't delete it. I included a screenshot. 
![assassin missing](https://cloud.githubusercontent.com/assets/20028693/16178319/7327c3da-3612-11e6-839b-3f4c6c068267.PNG)

**Comment by Moe-Ronickah** [comment]
Are you absolutely certain that you did not right click your assassin class at any time?  It only takes two clicks to reset a class, either by intent, or by accident.

**Comment by DarkBacca** [comment]
Yes, I am certain. And thanks for responding!

**Comment by Moe-Ronickah** [comment]
My best suggestion is that you change your Minecraft password.  Is it possible that someone else has access to your account?  Maybe you left Wynncraft open and someone else had access to your computer?

**Comment by DarkBacca** [comment]
No, it is not possible. Plus my assassin was only lvl 25. I have a lvl 88 archer and lvl 78 warrior. But thanks for the help!

**Comment by Moe-Ronickah** [comment]
OK then, it's possible that we have a game mechanics issue.

**Comment by Moe-Ronickah** [comment]
CONFIRMED.  If you enter the Class Deletion dialogue box, do not exit the box by using the "EXC" key.  Use the "Cancel" button in the dialogue box.

**Comment by DarkBacca** [comment]
Could I possibly get it back? @Moe-Ronickah

**Comment by Moe-Ronickah** [comment]
There is no way to get a deleted character back, that I know of.  In order to do that, the entire server would have to be rolled back to some time before your class was lost.  That would roll back every gain that every player made in the mean time.  The game admins aren't going to do that.  I'm sorry.
