### ISSUE TITLE
Didn´t get bounty

### ISSUE THREAD

**Issue by FartFrog** [Wynncraft/Issues#5268]
In my last two missions that I have done I did not get emeralds. Can you help me?

**Comment by Trixter313** [comment]
Did you have any emeralds in your inventory when you finished the quest?

**Comment by YunoFGasai** [comment]
Are you sure that the bounty was emeralds and not xp?

**Comment by FartFrog** [comment]
Do i have to have Emeralds in my Inventory to get the bounty?

**Comment by Moe-Ronickah** [comment]
If your inventory is full, the missions may not give you any emeralds.  Usually you do get however many emeralds you have inventory space to hold, so, if you have a bunch of emeralds already, you might not have seen the ones that you did get.  And if your inventory was full and all of your emeralds were at "64", there was no place to put any emeralds.

Missions don't act as bankers and trade you emeralds for EB.

**Comment by FartFrog** [comment]
My inventory was not full and i had less Emeralds

**Comment by Moe-Ronickah** [comment]
OK.  I'm connecting this to #1789 and expanding that issue.
