### ISSUE TITLE
bob rencarnation

### ISSUE THREAD

**Issue by CheeseLover** [Wynncraft/Issues#5270]
hi i was just doing bob with a couple of other players and we killed him but i didn't get anything so i thought there were to many people so not everyone could get his reward but when the most left me and 2 other guys stayed and we killed him again so i thought that i would get his reward but i didn't i had to kill him 2 times and still dont have anything.
can you please make that everyone gets his reward when he dies cause its very anoying and hard to find people who want to do it.

**Comment by Trixter313** [comment]
I believe there's a chance that bosses die and don't drop anything. I'll
leave it open so someone else can confirm yes or no.

**Comment by YunoFGasai** [comment]
bosses drop their items depending on the amount of damage you did. if you only stand back and heal it wont drop one for you.
because the drop is untradeable he other players cant trade you it. what you can do is kill him again and stand over one o the drops for a couple of seconds (can take minutes) until you pick it up.

**Comment by CheeseLover** [comment]
Thanks for the help but im Archer and i do much damage most of the Time he is focused on me so im Often at Low hp and Than i need to drink a potion and i had like 10 potions and ended up with only 1 after defeting him 2 times

**Comment by CheeseLover** [comment]
But maby i dont do enough Il try to do More damage Next time if there Will Be a Next time

**Comment by CheeseLover** [comment]
Ow and all the other players got the reward i think

**Comment by Moe-Ronickah** [comment]
Follow Yuno's advice, just tell everyone else to stay away from the next drop so that you can pick it up.
