### ISSUE TITLE
Lost Item

### ISSUE THREAD

**Issue by Felphyre** [Wynncraft/Issues#5271]
when attempting to get a Relic just outside of Almuj, I somehow lost my Waves Raiser wand in the middle of combat with guardians. I am sure I did not drop it myself since my drop key is G and not Q, making it extremely unlikely to hit it when my fingers were resting on movement keys. If there is any possible way to get that item back, I would be very grateful. It was my hardest hitting item and the only way i have gotten any relics up to this point.

My user in game is Felphyre and any sort of help would be very awesome. Thanks for your time.

**Comment by thecoolkogut4** [comment]
looks like it wasn't your lucky day and you pressed G :/ well they have a strict no refund policy so you won't be getting the wand back. sorry about that :(

**Comment by Felphyre** [comment]
well, figured nothing would be done if it, but i am extremely sure i didnt press G, so that may be something to look into to ensure others dont get bad luck for the game deciding to do something you didnt do.

**Comment by YunoFGasai** [comment]
you might want to bind your drop key to something farther like the "-" on the number pad to prevent future accidents

**Comment by Moe-Ronickah** [comment]
"my drop key is G and not Q, making it extremely unlikely to hit it when my fingers were resting on movement keys"

I'm sorry, but the "G" key is NOT "extremely unlikely to hit", as it is next to the "F" movement key.  This is not a Wynncraft issue, it is a normal Minecraft mechanic and you should bind your drop key far away from your left hand.
