### ISSUE TITLE
Guild

### ISSUE THREAD

**Issue by Dennisdao123** [Wynncraft/Issues#5275]
So i joined a guild like 6 months ago and my name was PikaIChewYou. i changed my name to leafyisfugly and couldn't leave the guild (the glitch i know) but when i changed my name BACK to PikaIChewYou. i tried to leave the guild again and it didn't let me. 

http://imgur.com/a/vdMXz link to the proof

**Comment by Moe-Ronickah** [comment]
Duplicate
