### ISSUE TITLE
All my items in my inventory disappeared when I logged in

### ISSUE THREAD

**Issue by Buffalo1324** [Wynncraft/Issues#5276]
When I logged in all of my armor and items were gone and i was left with the default oak wood shears, I am level 37. Also the only thing that I was allowed to keep was 2 corruption relic shards from a quest I recently completed. Please help me recover my items if possible

**Comment by Moe-Ronickah** [comment]
You died, multiple times, lost all of your soul points, and all of your items except your quest items.  You were then given the most basic weapon for your class.

Don't AFK in any city, unless you go into a building and get up past the first floor.  Mobs are currently bugged and enter cities when they should not.  You can also AFK safely by going into the class selection screen.

**Comment by Buffalo1324** [comment]
well i logged out in almuj with 6 soul points and logged in at ternaves with 4 soul points

**Comment by Trixter313** [comment]
I'd suggest changing your Minecraft password as it sounds like someone besides you logged into your account.
