### ISSUE TITLE
Guild Problems

### ISSUE THREAD

**Issue by nettlebane** [Wynncraft/Issues#5277]
My friend accidentally kicked me from the guild and cannot invite me back. When he tries it says that i am already in a guild but im not. When i do /guild leave it says "you are not in a guild".

**Comment by GlitchDoesMC** [comment]
Did you change your username recently? If so, your phantom self is still in the guild you were in before. I'm afraid there is no way to get back in, so you're going to have to wait until guilds get fixed.
