### ISSUE TITLE
Mana Bug

### ISSUE THREAD

**Issue by Nikkigirl1209** [Wynncraft/Issues#5279]
I have a friend named pandemianman, he is a level 61 and he has a bug with his mana. It is stuck at 0, this means he is unable to run or perform spells. Is there a way to fix this? We have already tried mana potions and /kill. Thank you so much for reading and I hope you can help.

**Comment by Trixter313** [comment]
See if switching to a different world helps

**Comment by Bloww** [comment]
Does he have negative mana regen ?

**Comment by YunoFGasai** [comment]
Either he has negative mana regen or it's the same bug from pre gavel, tell him to try /class.

**Comment by Moe-Ronickah** [comment]
And please, tell him to file the report himself, the next time.  It's really hard to help someone through another person.
