### ISSUE TITLE
Can't log in to Wynncraft at all- crashes everytime

### ISSUE THREAD

**Issue by zeldstarro** [Wynncraft/Issues#5280]
Just yesterday I was having a good time playing wynncraft, so I decided to do that again today. For some odd reason, the game crashed right when I logged on. So, I tried lowering the render distance to two chunks and that didn't help either. This isn't an issue with any other server that I use (except for hypixel's pixel painters) it's just Wynncraft. Please help.

**Comment by zeldstarro** [comment]
Update: It only started with wynncraft, now Hypixel is crashing, too... just a bit later. Also, I did tried to restart it, things only seem to be worse.

**Comment by zeldstarro** [comment]
Another update: everything is crashing, help.

**Comment by zeldstarro** [comment]
*everything in minecraft

**Comment by zeldstarro** [comment]
Sorry for the billionth update, I"m just trying to provide as much information as possible so I can get this fixed ASAP. Oh, and the game only crashes in the multiplayer servers. I can technically connect to it, it just crashes right afterwards because of some rendering bug.

**Comment by Trixter313** [comment]
What version of Minecraft are you using, do you have Forge or LiteLoader on? What OS are you using? Thanks!

**Comment by zeldstarro** [comment]
I was using minecraft 1.10.1, I don't have forge or lifeloader at all, and I'm using windows 10.

I have realized that it has something to do with the version, since once I switched to minecraft 1.9.4 everything was fine. However, I want to use minecraft 1.10.1 when I play wynncraft, since that's the version I also use in my single player worlds. I prefer to just keep it at the latest update.

**Comment by Trixter313** [comment]
We reccomend using Minecraft 1.8 when playing Wynncraft. Anything other than that isn't officially supported. Until it is, all you can do is keep switching in between versions.

I'd suggest following this guide to make multiple profiles in your launcher, one for Wynncraft and one for your single player. http://www.howtogeek.com/203196/how-to-change-your-minecraft-game-version-and-set-up-profiles/

It's the method I use and I love it. It makes it super easy to keep everything tidy and seperated.

Good luck!

**Comment by Moe-Ronickah** [comment]
Wynncraft is coded for 1.7.X/1.8.X.  If you use any other versions, such as 1.9.X or 1.10.X, you do so at your own risk.  I use 1.10 for my personal worlds, but 1.8.9, with Forge and Liteloader for Wynncraft.  We can only suggest that you go back to 1.8.9 as Wynncraft isn't coded for any newer versions of MC.
