### ISSUE TITLE
Dupet Apocalypse

### ISSUE THREAD

**Issue by yazanbb9** [Wynncraft/Issues#5281]
hey i just just bougth a apocalypse for good price and im trying to sell it and there some people saying to me rip its dupet i didnt understand whats that but i know that a buged weapon what to do...

**Comment by Trixter313** [comment]
I'm not sure what you mean. Could you post a screenshot of the weapon and what the weapon shows when you mouse over it in your inventory. Thanks!

**Comment by Moe-Ronickah** [comment]
If you mean that you bought an Apocalypse for a lot less than the market value, then you most likely have a duplicated, "duped", item.  It exists because someone used a hacking program to make a copy of a legitimate item.  It is illegal to own, and both you and the seller/hacker/duper can be banned for it.  If you suspect that it is a duped item, you should report it to a mod and let them deal with this entire issue.

**Comment by yazanbb9** [comment]
i mean that http://prntscr.com/bjwejw my friends saying u got scammed and this a glitch item...

**Comment by yazanbb9** [comment]
soo when i bougth it i wasn't know its duped.... idk what to do with it and im not the only guy got it.. my friend got 1 too

**Comment by Moe-Ronickah** [comment]
OK.  Go to the forums.  Go to player reports.  Post a report of a possible duped item by whoever sold it to you both.  Tell your friend to do the same thing.  Include screenshots of both items.  If the stats are the same, there is no doubt that they are dupes, and illegal.  Make the report yourselves, before someone else reports you both.

**Comment by yazanbb9** [comment]
ok ty

**Comment by Moe-Ronickah** [comment]
by the way, do you remember who sold it to you?  And what is your friend's name?  I'd like to make sure he knows what to do.

**Comment by yazanbb9** [comment]
yeah a girl lvl 56 called _nova or _noova_ somthing like that i trade ignis for it :/ and after 10 min he had the same apocalypse...

**Comment by yazanbb9** [comment]
my friend name called zephylox
ill tell him when he enter
https://forums.wynncraft.com/threads/auction-apocalypse-3.132671/
