### ISSUE TITLE
Cannot Upgrade Skill Points Bug

### ISSUE THREAD

**Issue by GlazedNEO** [Wynncraft/Issues#5284]
This happened to me a few days back, I got up to Level 51, for some unknown reason, I have been unable to upgrade my Agility Skill. I'm Level 53 now, and I lost about 4 Skill Points trying to upgrade my Agility Skill.

I've uploaded a video to show the proof.

https://youtube.com/watch?v=G3kraKHXkT4

**Comment by YunoFGasai** [comment]
you probably have a piece of armor or an accessory with negative agility

**Comment by Moe-Ronickah** [comment]
RESOLVED
