### ISSUE TITLE
Cannot enter iron heart II house

### ISSUE THREAD

**Issue by AstralPigeon** [Wynncraft/Issues#5286]
I'm wearing a factory helmet but i cannot get in for the quest, i'm thinking it might have to do with changing my Minecraft name.

**Comment by Moe-Ronickah** [comment]
Check your quest book and see what it tells you to do next.

**Comment by AstralPigeon** [comment]
oh... i'm dumb. sorry for wasting your time!

**Comment by Moe-Ronickah** [comment]
It's OK, and it's not a waste of time.  I wish that all of the issues were that easy to fix.  Have fun!
