### ISSUE TITLE
Trapped!

### ISSUE THREAD

**Issue by Jakman333** [Wynncraft/Issues#5290]
In Elkrun, there is a space that is entirely enclosed by fences. There are logs one would think you could jump onto to escape, but half-slabs have been placed over the tops. There are leaves next to a house within Elkrun, giving easy access into this entrapment, but offering no way out. Truthfully, the leaves look like stairs. There is a pool of water with a singular 2x1x1 hole. I've tried drowning myself, but my breathing bubbles return after the first one pops.
I have no way out of this. Mobs don't spawn near enough to kill me from the other side, and its in such a remote location I can't ask other players in-game for help. I went back to lobby and asked for assistance, but I think I merely managed to confuse people. 
Please help with this. Even if it's just a tiny teleport or breaking one of the Half-slabs. Thank you for your time.

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out and return you to the nearest visited town.

**Comment by Moe-Ronickah** [comment]
Please post this in this thread: https://forums.wynncraft.com/threads/community-project-filling-holes-open-16-closed-15.123931/

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
