### ISSUE TITLE
Cant talk with Santa

### ISSUE THREAD

**Issue by woohan0213** [Wynncraft/Issues#5298]
Unfortunately, when i talking with santa(finished quest)(Christmas Chaos)
my computer turned off, i was so nervous.
and i turned on again, i was talking with santa.
i rejoined, but santa doesnt say anything.
can you fix this problem?

**Comment by Moe-Ronickah** [comment]
Unfortunately, Santa doesn't talk to us elves very often.  However, he did leave a note and told us to tell you to take a [look here](https://wiki.wynncraft.com/index.php?title=Craftmas_Chaos), and see if that helps you at all.  He also said to check your quest book, and see if it tells you what to do next.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
