### ISSUE TITLE
Bug on Forums

### ISSUE THREAD

**Issue by ArchDestroyer** [Wynncraft/Issues#5301]
For some reason on Wynn Forums, when I'm changing my title, it says invalid username, but that IS my IGN but for some reason it just says it's invalid.

**Comment by Moe-Ronickah** [comment]
Hello, Agent Washington.  No, your IGN isn't ArchDestroyer, it's Agent Washington.  Your Minecraft name is ArchDestroyer.  You changed your IGN this past Monday, from BOT Temmie to Agent Washington.  I hope that this information helps you.

**Comment by redxdev** [comment]
I want to note that this is actually an issue, I've actually had it happen on my profile despite not changing my name (ever) and not touching that profile field. I've passed this on to someone who can hopefully help :)

**Comment by Moe-Ronickah** [comment]
@ArchDestroyer , did you get your name confused, or are you really running into an issue, as redxdev has described it?

**Comment by BronzeArrow** [comment]
I have had a similar issue and when I input my IGN it does not let me create a profile, I changed my IGN a long while ago and I am using that name for profile creation.

**Comment by YunoFGasai** [comment]
@ArchDestroyer @BronzeArrow @redxdev I understand it got fixed for some (including myself) was it just for some of the players or all of them?

**Comment by redxdev** [comment]
I don't know, but the issue was fixed.

**Comment by Moe-Ronickah** [comment]
@BronzeArrow , please open a new issue report, and describe your issue in detail.

This issue was resolved.
