### ISSUE TITLE
Problem:Shadow of the Beast

### ISSUE THREAD

**Issue by xMatei** [Wynncraft/Issues#5302]
I was searching for double xp and finish the Shadow of the Beast quest.I miss clicked the final NPC and disconected so i can find  a dxp.When i reconected my quest items disapeared and it made the quest imposibile to be done.Please help!

**Comment by Moe-Ronickah** [comment]
What does your quest book say to do?

**Comment by xMatei** [comment]
To kill the beast and talk to the final NPC

**Comment by Moe-Ronickah** [comment]
Through whatever kind of glitch happened, the game did not register that you had killed the Beast.  You'll have to kill it again.

**Comment by xMatei** [comment]
I did it but I need 2 other items which i lost to finish the quest

**Comment by Trixter313** [comment]
You can try the command /fixquests but it might not work. Doesn't hurt to try it though!

**Comment by Moe-Ronickah** [comment]
If /fixquests does not work, you will have to put the quest on hold until an update for it comes out.  /fixquests does not cover all quest items, yet.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
