### ISSUE TITLE
WynnExcavation A Quest Bug

### ISSUE THREAD

**Issue by TheGylonCrafter** [Wynncraft/Issues#5305]
Hi.
After Getting In the Temple And Solving The Riddle And founding Pharoh Nabak. The Quest Tell me Go o Speak With Excavator Vade...When i talk to him he tell me Go to Tesha To translate the ANCIENT Text. Not Stage 7 !!!! Pls Help And Thanks.

**Comment by XavierEXE** [comment]
Did you try /fixquests?

**Comment by YunoFGasai** [comment]
You need to kill the pharoh and take the crystal to vade

**Comment by Trixter313** [comment]
Did the above suggestions help to resolve your issue? Thanks!

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
