### ISSUE TITLE
Skill Points Reset Bug

### ISSUE THREAD

**Issue by AguriYu** [Wynncraft/Issues#5312]
Howdy!

I recently wanted to reset my skill points to use my new armor I got because my Agility LV was too low.
Somehow it keeps changing back to my old skill points count.
So I tried it again.
I spent 2LE on resetting my Skill Points for nothing.
Somebody please help. Because I don't know what to do anymore.

What I wanted it to be: http://imgur.com/08tcySA
![image](https://cloud.githubusercontent.com/assets/7178055/16363569/8cf851d2-3b9c-11e6-8651-6c603fa52669.png)

What I got: http://imgur.com/Ye69yS7
![image](https://cloud.githubusercontent.com/assets/7178055/16363570/969647f8-3b9c-11e6-944b-cd3b9cbd418e.png)

After some time (to my old skill points count): http://imgur.com/AOotHvC
![image](https://cloud.githubusercontent.com/assets/7178055/16363571/9ec88e22-3b9c-11e6-9151-4e0cb12c61db.png)

I would be really happy, with any kind of help.
Love
~Akisa

**Comment by Moe-Ronickah** [comment]
Your skill points can be both positively and negatively affected by your armor.  Is your armor affecting your skill points and causing this?

**Comment by Karatedodo** [comment]
This happens to me too. :(

**Comment by Moe-Ronickah** [comment]
RESOLVED
