### ISSUE TITLE
Invalid Minecraft Username Entered

### ISSUE THREAD

**Issue by BronzeArrow** [Wynncraft/Issues#5317]
The reason I posted this is because I do not believe this is a duplicate issue. This is because the issues similar to this were posted a while ago and are since closed. 

So here it is.

I try registering for a new account for the wynncraft forums. I have never had one before so this is my first time. Anyhow, when I try to register, the error message labeled Invalid "Minecraft Username Entered" appears and prevents me from making my account.

Any help?

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/5301

Please direct any future contents to the original thread. Thanks!
