### ISSUE TITLE
Fall Through World When I Get On Server

### ISSUE THREAD

**Issue by SandyVerse** [Wynncraft/Issues#5318]
When i get on a server, im in a room and then i fall through the world and just keep on falling down.

**Comment by SandyVerse** [comment]
I also tried to use /classes while or as falling but then it says that I can't use commands. /lobby, /hub works though

**Comment by Moe-Ronickah** [comment]
Do you have autojoin on?  If you do, please try going into the nether, then turning autojoin off.  Let us know what happens.

**Comment by SandyVerse** [comment]
I fall through the nether world too, and how would i turn autojoin off
@Moe-Ronickah

**Comment by Moe-Ronickah** [comment]
The command is /toggle autojoin , however, if you are also falling through the nether, it probably won't work.  When you try to enter the neither, only go into the portal far enough for the visual effects to start, then hold there.  Try to use /toggle autojoin while you are part way into the nether, and see if that helps.

**Comment by SandyVerse** [comment]
Ok so i keep on trying but once i get on either a nether or regular server, I immediately fall through the world and I even tried jumping to get into them but i just end up falling through the floor anyways and it still says that I cant use commands.

**Comment by SandyVerse** [comment]
@Moe-Ronickah

**Comment by Moe-Ronickah** [comment]
OK, lets try these: first, make certain that you have your resource pack set to enabled. Second, uninstall and reinstall Minecraft.

**Comment by SandyVerse** [comment]
Solved it! Turns out it was just because server resource pack was off. Thanks for the help!

**Comment by Moe-Ronickah** [comment]
You're welcome.  I'm glad that it's solved, and that you're able to play, again.
