### ISSUE TITLE
Bug With Lost Soles Quest

### ISSUE THREAD

**Issue by SkittleM0D** [Wynncraft/Issues#5319]
I started the quest ''Lost Soles'' and at the part of throwing an item on the map i believe it glitched since i did it to fast or something. Now when i try it doesn't update the book. I've relog and changed server nothing is working. I tried /fixquests and now it restarted the quest, but now this error happens: http://imgur.com/CKCEgkC please help me thanks.

**Comment by Moe-Ronickah** [comment]
Sometimes, just sometimes, this kind of error will fix itself after you log out for a couple of hours.  Have you tried to start the quest lately?  Is it working or are you still stuck with this error?

**Comment by SkittleM0D** [comment]
16 hours later... Still same messages Ferndor says but I almost have this weird thing: http://imgur.com/a/Q8HM6

**Comment by Moe-Ronickah** [comment]
Throw an emerald at the painting, and then look to your left, immediately.

**Comment by SkittleM0D** [comment]
Doesn't update... Do you have the power to reset the quest? it's an easy quest.

**Comment by Moe-Ronickah** [comment]
Unfortunately, or fortunately, depending on your point of view, we don't have the power to reset quests.

While I'm not endorsing any youtuber over another, you might want to take a look at [this walk through](https://www.youtube.com/watch?v=cBlUjgyg9Y8) of Lost Soles to see how the quest is supposed to work, just on the chance that you are missing something.

**Comment by Moe-Ronickah** [comment]
RESOLVED

**Comment by janjao12** [comment]
im having the same issue now.
how can I fix this?
