### ISSUE TITLE
Stuck in the Nether

### ISSUE THREAD

**Issue by sulkbliss** [Wynncraft/Issues#5321]
I'm not able to leave the Nether. /leave does not seem to work, and using the center portal sends me to the lobby, where upon reconnecting, I end up in the Nether again.

IGN Psychedelic10

**Comment by Moe-Ronickah** [comment]
Are you still stuck?  Given this, and #5320 , I think that you may be have been experiencing a glitch between your MC and Wynncraft.

**Comment by sulkbliss** [comment]
Yes I'm still stuck. I was going to post about the necklace before I became stuck. I'm certain that it was not a glitch between my client and wynncraft.

**Comment by sulkbliss** [comment]
Oh I'm not stuck now, no.

**Comment by Trixter313** [comment]
Glad to hear it's fixed. Have a great day!
