### ISSUE TITLE
Inventory lost

### ISSUE THREAD

**Issue by Craziel** [Wynncraft/Issues#5323]
Hello! Sorry for my English if that's bad, I'm French!
Today I played with my warrior and I was afk (next to a merchant in Detlas) for a few minutes. When I came back, I needed to disconnect, but I saw that I had lost all my inventory and that I had just 3 start weapons , 2 quest items and a mushroom. I thinked that when I will come back, my inventory will come again, but I have lost everything, weapons, armor, emerald and also my Soul point. A player said to me that I have the inventory of  a player that losted all his soul point. I was not die so it's impossible. (Sorry again for the mistakes, I hope you understand my problem)

**Comment by Moe-Ronickah** [comment]
You did die.  Never AFK in any city right now, as the mobs are bugged and they will enter a city.  You probably died due to Mooshrooms that followed someone into the city.  Sorry about that.  The admins know about this and it should be fixed with the next update.
