### ISSUE TITLE
Can't Get Past /class

### ISSUE THREAD

**Issue by AntiRobo** [Wynncraft/Issues#5324]
I tried starting playing WynnCraft again after a couple years, so as soon as I log in, it makes me create and choose a class. I do this, then I just see blackness, and after a few seconds it makes me choose another class, and the cycle keeps repeating. I've tried nearly every version, too.

**Comment by Trixter313** [comment]
Is there an error message displayed in chat at any time? Also, do you have anything in your inventory while stuck? Thanks!

**Comment by Moe-Ronickah** [comment]
"I've tried nearly every version, too."  If by this, you mean every version of MC, try version 1.8.9 and let us know if that fixes your issue.

**Comment by Moe-Ronickah** [comment]
RESOLVED
