### ISSUE TITLE
Broken/incomplete 'area map'

### ISSUE THREAD

**Issue by CharlieDowns** [Wynncraft/Issues#5327]
Hello, I want to report a issue where a 'area map', which shows how the area looks like is broken or incomplete.

![2016-06-28_01 21 57](https://cloud.githubusercontent.com/assets/19643543/16398982/f4cffaca-3cce-11e6-84d9-5798a01f977b.png)

**Comment by Trixter313** [comment]
When you switch to another world is it still broken or is it just broken on the world you were on at the time? Thanks!

**Comment by Moe-Ronickah** [comment]
It's not broken.  That's the map that would cover Canyon of the Lost, but if you had a map, you wouldn't be lost when you were doing the quest there.
