### ISSUE TITLE
Logged in to Wynncraft - Everything missing but Oak Wood Bows

### ISSUE THREAD

**Issue by EximiusWynncraft** [Wynncraft/Issues#5329]
In Game Name: Eximius

When logging into Wynncraft after being gone most of the day, I entered the server. I was put into the class selection box, as I have the auto-join feature disabled. It was to great surprise, I had lost all of my items. Instead, I had 6 Oak Wood Bows, the Untradable kind. I kept one ring and a necklace, but all my other items had vanished. 

Recalling the contents of my inventory, I had an Eruption Bow, a White Horse, teleportation scrolls to Olux (4 of them), and scrolls to Llevigar (5, I believe). Along with the bunch were a few emeralds, and most likely various items I had gotten from opening loot chests.

I kept my level, as well as my dedicated skill points. The contents of my vault remained intact, while my skin was reset to the default skin. Similar to the beginning tutorials of the game, putting on a hat located in my vault loaded my skin. Hoping this would also load in the rest of my valuable items, I was displeased when after multiple log-ins, my inventory remained the same.

I recall disconnecting while mounted on my horse.

I play Wynncraft on Version 1.8.8 Forge, with Optifine & a Coordinates Mod installed.

My inventory as it appeared:
https://gyazo.com/4a0ed0f0032aa07a81a498a1ae2f1a1f

All items that I kept were of the 'Untradable' description.

If there were a possible way to rollback my player data, spawn back in items, or anything else in mind, it would be much appreciated if action were taken.

**EDIT: Logging in again, I seem to have the default skin as well. It is not until putting on my armor that it loads.

https://gyazo.com/36edf4fe9244101b85fd7de5a505bea4

I have noticed several other posts of players having the same problem, losing all items but their quest items, and being given starter weapons upon logging in. These posts have all been within the past 6 hours. Therefore, I have reason to believe that something is acting up, and I do hope you are able to solve the issue.

** EDIT TWO: When my skin refuses to load, I appear invisible to other players.

https://gyazo.com/f14c5b905d0910bef16bd84c22f1183a

Thank you for your time,
Sincerest regards,

Eximius

**Comment by YunoFGasai** [comment]
Was the ring and necklace you kept quest items?

**Comment by EximiusWynncraft** [comment]
> All items that I kept were of the 'Untradable' description. <

Yes, they were quest items.

**Comment by omintrevor** [comment]
that happened to me just a few hours to

**Comment by Moe-Ronickah** [comment]
You died, respawned in an area with hostile mobs, and died again.  It won't happen again, with the Gameplay update.
