### ISSUE TITLE
Lost Item

### ISSUE THREAD

**Issue by Kfajver** [Wynncraft/Issues#5330]
I had in your inventory quest item(corrupted potato) that somehow appeared in loot your when it opened. When I tried to take that item it writes to me that I will need them later, and at the time when it closed my item have disappeared. The command/fixquests does not work.

**Comment by YunoFGasai** [comment]
so did you find a quest item or loose a quest item?

**Comment by Moe-Ronickah** [comment]
If you have managed to lose, or to eat, the corrupted potato, /fixquests will return it.  You will need to have a couple of open inventory slots in order to get it back.  If it does not work on one server, try changing servers and try /fixquests again.

**Comment by Kfajver** [comment]
It still does not work

**Comment by Moe-Ronickah** [comment]
Read this issue, [here](https://github.com/Wynncraft/Issues/issues/502).  Is it possible that you have the Corrupted Potato in your bank, or in the inventory of another character?  Would you check, please?

**Comment by XavierEXE** [comment]
If you try to use /fixquests for an item, it won't work if you have another copy of that item, even if it's on another class.

**Comment by Moe-Ronickah** [comment]
RESOLVED
