### ISSUE TITLE
Horse lagg

### ISSUE THREAD

**Issue by MaerPerx** [Wynncraft/Issues#5331]
http://cs636131.vk.me/v636131368/16880/FA9tR00CM6k.jpg (my friend see me)
http://cs633230.vk.me/v633230752/32140/vEYRPa2h6-o.jpg (me)

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/5188

Please direct any future comments to the original thread. Thanks!
