### ISSUE TITLE
Mana Bug

### ISSUE THREAD

**Issue by xXRobotKnightXx** [Wynncraft/Issues#5333]
When i'm killing a mob with any spell, i lost mana!

**Comment by IntSerErr** [comment]
When you're killing a mob, using any spell, you lose mana?

That's how the game mechanics are supposed to work...

**Comment by Trixter313** [comment]
I'm not sure I'm understanding it correctly.

Spells use mana so it would make sense that you lose mana.

**Comment by YunoFGasai** [comment]
do you have negative mana steal on your gear?

**Comment by Moe-Ronickah** [comment]
RESOLVED
