### ISSUE TITLE
Unusuable item

### ISSUE THREAD

**Issue by Olaxce** [Wynncraft/Issues#5334]
So hey guys, I had a problem with a weapon today, here is my story:
I wasn't able to play wynncraft for while, because of lag problems, but now I can. I have not been on since the new update, with the new texturepack, weapon update, and gavel, so I got a bit confused, but I figured it out. Me and my friend did some quests, and we leveled up, but when I checked my bank there is a weapon I left, its a spear (I play as warrior), its legendary and its named "Fierté". I am not in the right level for it, but when I try to use it, nothing happens, not even a "You are not in the required level" message or something, I tried giving to the identifier, but he does not accept it, even if its a legendary weapon. This weapon seems bugged, it even has the old weapon description before the update, not the new fire, air, lightning description. I would really want to be able to use this weapon because it seems powerful, but I cant. Please help me.

**Comment by Trixter313** [comment]
This was something that happened randomly when the Gavel update released. Unfortunately all you can do is get new items and either get rid of the broken one or keep it as a souvenir.

It was a one time thing so you don't have to worry about it occurring to any more items.
