### ISSUE TITLE
Skill points Glitch

### ISSUE THREAD

**Issue by Trooper2027** [Wynncraft/Issues#5335]
Hi i recently haven't been playing on the server lately and now i  have come back to play but i have an issue involving my skill points.

when i started up my lvl 34 mage all of skill points were reset so i went and tried to put the right amount back to where they belonged. But when i clicked on the skill to add the points it dint show anything added, so i exited the menu and tried to try again, and this time all of my points were stuck on one skill and now i cant fix it 

any help would be greatly appreciated.

**Comment by Trixter313** [comment]
Could you post a screenshot of your skill points? Thanks!

**Comment by Trooper2027** [comment]
![2016-06-28_11 40 45](https://cloud.githubusercontent.com/assets/20189989/16422179/773e2198-3d25-11e6-9450-7d3d4754036f.png)

**Comment by Trooper2027** [comment]
i was going to make them all even but this glitch happened and all my skill points got stuck on two of them

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refunds policy so I don't think we'll be able to reset your points but if you do the quest Tower of Amnesia you will be able to obtain a skill reset scroll to reset them.

**Comment by Trooper2027** [comment]
alright i guess i got t farm to emeralds thanks for the help

**Comment by KitiNek0** [comment]
Hey i also have a problem with my skill points, every now and then it says i have 17 skill points for my strength when i updated it to 20 and sometimes it says 20 which it should but goes to 17 which takes of some of my armor. Please help

**Comment by Moe-Ronickah** [comment]
@KitiNek0 , part of your issue is #3153 .  You can follow it, there.

@Trooper2027 , where you don't see a number or a red "0", you have one skill point.  If you right clicked any skill, you put 5 skill points into it.  You probably got hit by lag, too.
