### ISSUE TITLE
Forums Signature Issue?

### ISSUE THREAD

**Issue by DaNarwhalChannel** [Wynncraft/Issues#5337]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.
I created a new signature on the forums, but it only shows 1/3 of the actual image. Help?

**Comment by Trixter313** [comment]
I've taken a look at it and your image appears to be too tall unfortunately. Signatures have a height limit to prevent people from using too large images that would make threads much harder to scroll through. The only workaround is to edit the image you want to use to be less tall or choose another image. Thanks!
