### ISSUE TITLE
Particale glitch

### ISSUE THREAD

**Issue by Destroyer282828** [Wynncraft/Issues#5339]
Okay so, i purchased GCs from the wynncraft store for 15$ and spend 220 of those coins into purchasing the "cloud particale" when the only other options were emerald and redstone. so I click on the cloud particale which costed 220GC and I had 330GC. so it said "You have purchased the cloud effect, open /use to use it." or something like that. so then I go to turn it on but when I press the gold ingot that says "turn on cloud particales" it says "letter particales activated." so I don't know what to do, because this kind of scammed my GC. I wanted to cloud particales but it gave me the letter particales even though the gold ingot says "cloud particales" so please somebody help me or tell me what to do to get the particales I want. I would really appriceate it. (I am very bad at spelling but whatever)

~Destroyer282828

**Comment by Trixter313** [comment]
It doesn't look like there's anything you can do about it right now. An admin will have to fix it. This is a pretty old bug and all of the previous issues for it have been closed with no statements. The original is issue https://github.com/Wynncraft/Issues/issues/1222

Hopefully it will be fixed soon!

**Comment by Moe-Ronickah** [comment]
Contact support@wynncraft.com and tell them what happened to you.  You should go ahead and include information from the original #1222 bug report.  Let us know what they say.

**Comment by Moe-Ronickah** [comment]
RESOLVED
