### ISSUE TITLE
Two of my skill points dissapeared

### ISSUE THREAD

**Issue by KitiNek0** [Wynncraft/Issues#5340]
I am currently level 43 and i used two skill points when i got to 42. I used them on strength so i could wear these pants and now they went down, i used one from my uping to 43 on strength but the ones from before are gone and i can't wear the pants when i could before. Please help

**Comment by Trixter313** [comment]
Check your skill points with all armor off. Armor can increase or decrease skill points. That is probably what is happening here.

Let us know if this helps!

**Comment by KitiNek0** [comment]
No it didn't change my skill points but the fact armor can change that is useful knowlage

**Comment by KitiNek0** [comment]
wait is it possible for the skill point to move on their own? I think my agility went up

**Comment by Trixter313** [comment]
I don't think anything intended would cause that except armor or accessories or weapons.
So when you mouse over each skill point none of them say they are being modified?

**Comment by KitiNek0** [comment]
My agility does say that yes

**Comment by Trixter313** [comment]
Then something your wearing is affecting your agility. Find what it is and take it off then see if you have the appropriate amount of skill points for your level or if any are missing.

**Comment by KitiNek0** [comment]
ok i noticed i just took off my chestplate and it took 2 off my agility but my strength stays 18 when i use to have it at 20, can i fix it?

**Comment by KitiNek0** [comment]
same with my boots, it takes 2 off agility, i did the math for it by adding it all up and it took me to 84. divide that by 2 (2 skill point each level up) and im left with 42 which is a level under me and wouldn't that mean im missing two skill points?

**Comment by Trixter313** [comment]
I think you have the correct amount since your player starts on level one with no skill points until level two.

So it seems to have just been a little wonky before but at least you aren't missing any skill points.

**Comment by KitiNek0** [comment]
ok, im just kind of confused cause i remember using two skill points on strength to wear my pants and i could wear then before when it said it was 20. Do you know if that was a glitch or so? It did last for around a day

**Comment by Trixter313** [comment]
The points might have switched to another skill or they were returned and you didn't notice. Skill points can be odd sometimes.

**Comment by KitiNek0** [comment]
Ok thank you for helping me

**Comment by Moe-Ronickah** [comment]
Or your other pants added to points to your strength.
