### ISSUE TITLE
Incorrect Map Link

### ISSUE THREAD

**Issue by HeyItsMeTom** [Wynncraft/Issues#5345]
When you start off and talk to the king of Ragni for the first time, he tells you to use "wynncraft.com/map" if you get lost. This is the wrong link - it should be map.wynncraft.com.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/4316

The issue has been fixed internally but hasn't been pushed to the play server yet. Hopefully it is done soon!
