### ISSUE TITLE
guild xp 

### ISSUE THREAD

**Issue by DeathMage666** [Wynncraft/Issues#5349]
i put my guild xp to 100% and i kill somthing it puts it into the guild but when i do guild list it dosent show i have put xp in the guild

**Comment by Moe-Ronickah** [comment]
Wait a day or two and let us know if the xp shows up.  Guilds are truly messed up, right now.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
