### ISSUE TITLE
Animal Dungeon Cow Boss - Mage push

### ISSUE THREAD

**Issue by spenaat** [Wynncraft/Issues#5350]
Went 3 times in a row Animal Dungeon and these things happened always at final boss (Fire Cow):

1.) When I attack it, the cow gets pushed behind the invisible wall (I can attack it, although it can't attack me)

2.) When I attack it, the cow gets stuck in the wall and dies immediately.

**Comment by Moe-Ronickah** [comment]
duplicate of #3191
