### ISSUE TITLE
THE TEXTURE PACK

### ISSUE THREAD

**Issue by Ravi-minecraft** [Wynncraft/Issues#5351]
I have  A SERIOUS COMPLANT to make about the texture pack, I HAVE A GOOD COMPUTER, and with the REQUIRED texture pack i go to 0-1 fps, I cant even move, while normally I am running 100-200 fps, WHY is it required to have the texture pack, I LOVED THE SERVER before you screwed it up, it was dying and now its dead because half of the players I know cant play anymore because of what you guys did, PLEASE fix this and make the game playable again, just make the texturepack NOT REQUIRED I BEG OF YOU, BECAUSE I CANT PLAY ANYMORE,

**Comment by YunoFGasai** [comment]
actually lately there are a more players on the server than there was pre gavel.
without the pack nothing would make sense as you would be attacking with blocks and there would be brick slabs everywhere.
the texture pack isn't supposed to lower your fps, do you have anything running in the background?

**Comment by Ravi-minecraft** [comment]
no
I have nothing open and it runs fine until I have to use the texture pack, please dont make it neccisarry, idc if you couldnt understand anything, atleast then I COULD PLAY IT

**Comment by Moe-Ronickah** [comment]
If you are using a version of MC greater than 1.8.9, I suggest that you go back to 1.8.9.  Wynncraft is coded in 1.7.X, and even though it is 1.8/1.9 compliant, versions higher than 1.8.9 don't always work well.

**Comment by ende124** [comment]
This happened to me too whie using Liteloader, I switched to Forge and it was running smooth.

**Comment by Trixter313** [comment]
Closed due to no response from OP. Assuming using 1.8.9 fixed their issue.
