### ISSUE TITLE
Hp differnce between nether and server

### ISSUE THREAD

**Issue by YunoFGasai** [Wynncraft/Issues#5352]
I went over the 79 issues containing "nether" and didn't found anything similar.
my hp seems to change between nether and regular servers, the difference is a couple of hundreds.
I suspect some items have different hp values in the two servers.
will check later.

**Comment by Moe-Ronickah** [comment]
Oh, fun.  Some weapons don't work in guild wars, some armor doesn't work right in the nether.

**Comment by YunoFGasai** [comment]
found the difference 
this is my suppression in a normal server
[http://i.imgur.com/uw0B8ML.png?1](url)
this is the same suppression in the nether
[http://i.imgur.com/Iegzz2I.png?1](url)

**Comment by Moe-Ronickah** [comment]
Unless you have two Suppresions, I'm totally confused.  I don't get how a piece of armor, or anything else for that matter, should change it's IDs like that, unless there was a coding modifier added to the item.

**Comment by YunoFGasai** [comment]
I do have two suppressions, in the overworld they each have -100hp (do note it's not an id) and in the nether they do not effect my hp.

**Comment by Moe-Ronickah** [comment]
Does your other Suppression do the same thing, or is it limited to just this one?  I'm going to assume that they both act strangely.  This has to be a Jumla and team issue.

**Comment by YunoFGasai** [comment]
They both have negative hp in the overworld and no hp at all in the nether.
This is the same as the guild war issue (although it seems guild war servers and the nether get updated separately)

**Comment by Moe-Ronickah** [comment]
I can confirm that they do, indeed, get updated separately.  I've read that they are completely different servers, on their own, separate schedules.

**Comment by XavierEXE** [comment]
Could this be like another item where the dexterity requirement changed between the normal world and guild wars? It was a bow but I don't remember the name :/

**Comment by YunoFGasai** [comment]
@XavierEXE I have a thread on the forums to keep track of the items, I think you are talking about one of the mythic bows and yes this is the same issue.

**Comment by Moe-Ronickah** [comment]
@YunoFGasai , do you know if this is fixed?
