### ISSUE TITLE
Ice snake spell glitch

### ISSUE THREAD

**Issue by Zeng12138** [Wynncraft/Issues#5355]
When you cast the ice snake spell on an ice block
the ice block will transformed to a falling block, and disappear
when you stand on it you'll stuck on it.
you can fix it by right clicking on the block, but it is annoying when you are doing long term grinding ;/

**Comment by Moe-Ronickah** [comment]
This is the first time that I have heard of this.  Have you changed servers?  Is it still happening?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
