### ISSUE TITLE
Possible Teleport Lag/Glitch

### ISSUE THREAD

**Issue by Muddykipper** [Wynncraft/Issues#5357]
At the coordinates X:215, Y:89, Z:-4303, there is a waterfall.  When I went to the top of it, I believe the game tried to teleport me.  I also believe it couldn't, because it eventually timed out, and I was forced out of the server.  This happened **twice** as soon as I logged back on to my level 86 Archer class, and the third time I logged back on I was able to go back down the waterfall.  I don't believe it's a big issue, but it made me curious about what's up there and scared that I could lose my Archer class to a glitch.

**Comment by Moe-Ronickah** [comment]
You probably ran into part of the Gavel mountain barrier, but I'll ask a builder about it.

**Comment by Moe-Ronickah** [comment]
RESOLVED
