### ISSUE TITLE
Item Bug

### ISSUE THREAD

**Issue by hihiji** [Wynncraft/Issues#5359]
my jester ring is broken it says the set bonus is -25% loot and xp bonus which is normal but thats only when you have the whole set but for some reason the set bonus is activated and is counter acting the jester ring. i spent a long time trying to get it and i dont just wanna throw it away

**Comment by Moe-Ronickah** [comment]
The Jester set is not like any other set.  There are bonuses and nerfs that occur at 1/3, 2/3, and 3/3 pieces of the set.  For example, if the ring says "+29% loot", just wearing the one ring will deduct 25% from your loot bonus.  You will end up with +4% loot bonus.  Remember what it's called: The Jester Set.  Like the Court Jester, the massive bonuses that each piece shows, individually, is actually joking.

**Comment by XavierEXE** [comment]
But if you wear 2 pieces of the set yoy get a huge melee bonus and if you wear all 3 you get a huge spell boost.
So it's not all bad :D

**Comment by YunoFGasai** [comment]
I just talked with Tantibus and he said it is intended to work this way.
