### ISSUE TITLE
On'omi in Iron Heart II

### ISSUE THREAD

**Issue by Endertricity** [Wynncraft/Issues#5362]
Small issue - this character's name is glitched. I've seen in the Content Team Application thread that all apostrophes are replaced with carets, and I guess someone forgot to remove this one.
![screen shot 2016-06-18 at 4 07 47 pm](https://cloud.githubusercontent.com/assets/17186189/16526571/ec006980-3f7f-11e6-86ad-859fdbb05821.png)

**Comment by Moe-Ronickah** [comment]
That is a caret, ( ^ ), not an apostrophe, (  '  ).

**Comment by Endertricity** [comment]
Yes. I'm just saying I believe it was supposed to be an apostrophe, not a caret.

**Comment by Moe-Ronickah** [comment]
OK, now I understand what meant.

**Comment by XavierEXE** [comment]
I think this happens with quests too, I remember Maltic's Well showing up as "Maltic^s Well" in chat when you hit level 18.

**Comment by YunoFGasai** [comment]
I don't think this can be fixed due to how the code works in Wynncraft.

**Comment by AckroWynn** [comment]
This can be fixed, however, the GM that made this mob, hid it really well somewhere. I can't find it in our mob folder ;-; (AKA They did not name the yml after the mob, #GMStuff)

**Comment by sammyvsparks** [comment]
@AckroWynn (granted your computer would probably have a horrific fit) open all the files and search for the mob name perhaps? I have to do that a lot when I lose something in a folder.

**Comment by AckroWynn** [comment]
Sammy, seeing as I would have to enter and exit each and every single file, which is about 2572 files, and would take ages. I don't think it's happening that soon ;D

**Comment by AckroWynn** [comment]
All right! After 20 minutes of searching, I finally found the file (I had to look up the GM who made the quest, and then search all regions they had made, that I could find, and go from there *phew*).
This issue has now been resolved!

**Comment by AckroWynn** [comment]
And, about that quest issue, I could fix it, however, it would make it reset for everyone on the servers, which Salted would never let me do ;D

**Comment by Moe-Ronickah** [comment]
Unfixable, dead issue.  Noted!  Thanks, Ackro!

**Comment by sammyvsparks** [comment]
@AckroWynn Dont you have a editor that lets you do all file lookups?

**Comment by AckroWynn** [comment]
@sammyvsparks Yes, all GMs do. However, as I said, whatever GM made the file, named it very poorly, and I had to do quite the research to find the mob file.
