### ISSUE TITLE
I lost my Bob's Dagger

### ISSUE THREAD

**Issue by LucasJordan2000** [Wynncraft/Issues#5365]
I didn't knew where to go, but here. I was in my horse, and as always, when you use your inventory while riding your horse, he will disappear. ALL I did was put the Bob's Daggers in the inventory and then... Puff! It was gone! I'm so pissed right now. Please, someone help me get it back. I worked so hard to get it, and now i don't have any weapons to fight monsters.

**Comment by Moe-Ronickah** [comment]
I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency.  You might be able to find someone to buy your lost item from, or, possibly, someone who will even give you one, for free, depending on the value of your item.  Ask around in Detlas and check the Trade Market on the forums.  Good luck.

**Comment by Moe-Ronickah** [comment]
There are several situations that can cause you to lose an item - the server closing very soon after you add an item to your inventory or bank is one that's fairly well known.  If this happened to you, try to avoid moving anything in your inventory within a minute or two before the server closes.  It's also possible, if you were moving when you put the item into your inventory, that the server didn't register it there, and that you dropped it, as far as the server is concerned.
