### ISSUE TITLE
Can't use certain guild commands and is owner of guild. Please help

### ISSUE THREAD

**Issue by KitiNek0** [Wynncraft/Issues#5367]
I noticed this a while ago but whenever i try to do a command for my guild it doesn't do anything like nothing even pops up, I am also the owner of the guild so i'm really lost on what to do. I can still add people, kick people from it and up people ranks in it but i can't do the leader board or stats command. Someone please help

**Comment by YunoFGasai** [comment]
Leaderboard and stats are temporarily removed because guilds are really glitched atm.
Hopefully the commands will return when guilds will be fixed.

**Comment by Moe-Ronickah** [comment]
Resolved.
