### ISSUE TITLE
Comeback to the "Starting point"

### ISSUE THREAD

**Issue by LGP1234** [Wynncraft/Issues#5369]
If you die in this room from the "Shattered Minds Quest", you will respawn at the "Starting point"
![2016-07-02_17 15 59](https://cloud.githubusercontent.com/assets/19672352/16541101/7363ad92-407a-11e6-8af0-8bdb7352d6bd.png)
![2016-07-02_17 16 02](https://cloud.githubusercontent.com/assets/19672352/16541102/83d219e8-407a-11e6-987a-aec409f92f5a.png)
![2016-07-02_17 16 28](https://cloud.githubusercontent.com/assets/19672352/16541104/88c853b8-407a-11e6-878c-9ecdee4ae5dc.png)
![2016-07-02_17 22 38](https://cloud.githubusercontent.com/assets/19672352/16541105/8f398f00-407a-11e6-97f7-adc26f3d48a2.png)

**Comment by Moe-Ronickah** [comment]
I'm sorry, but it's not a glitch.  It's an effect of the map layout.  You always return to the nearest to city to where you died.
