### ISSUE TITLE
Randomly lost Legendary item

### ISSUE THREAD

**Issue by aofekiko** [Wynncraft/Issues#5371]
Hello, I had a legendary Holy Greaves, and after taking them from the item identifier they just dissappeared. i have video evidence using Nvidia shadow play, that you can watch here: https://www.youtube.com/watch?v=NEnoqGTN5u0&feature=youtu.be
Hopefully it is acceptable that i get the item back.
if so, my IGN is "Yassuri"

**Comment by Moe-Ronickah** [comment]
You had the Holy Greaves in your inventory when you left the Item Identifier.  What happened to them after that, I have no idea.

I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency.
