### ISSUE TITLE
TP bug

### ISSUE THREAD

**Issue by Nolmin02** [Wynncraft/Issues#5372]
In the WynnExacavation site A, after you kill the crystal keeper you are teleported into a wall/ground and the only way to escape is the /suicide so... it's not very funny at all :c
Please if you can fix that quickly :'(

**Comment by Trixter313** [comment]
Using the command /kill with 3+ soul points should get you out and take you to the nearest visited town. I believe that this only happens to people sometimes and is caused by lag so there's not much we can do about it. There will always be some sort of lag unfortunately.
