### ISSUE TITLE
Suspended Flowers Quest bug

### ISSUE THREAD

**Issue by chasedig** [Wynncraft/Issues#5375]
Hello, i had a problem with this quest, so i dropped the purified flowers so what do i do now? I thought you can't drop quest items. I hope theres a way to fix this. :)

**Comment by YunoFGasai** [comment]
try /fixquests

**Comment by Trixter313** [comment]
Did @YunoFGasai's suggestion fix your issue? Thanks!

**Comment by chasedig** [comment]
yes!
