### ISSUE TITLE
The mercanary quest

### ISSUE THREAD

**Issue by Squebsly** [Wynncraft/Issues#5376]
in ba'aals palace in the mercenary quest you can get stuck in a hole and its impossible to get out with certain classes I hope you could fix this
Ps:I got nocked in and I'm very sad :(

**Comment by Moe-Ronickah** [comment]
Can you tell me the coordinates of the whole?
PS: So am I.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
