### ISSUE TITLE
My item disappeared

### ISSUE THREAD

**Issue by gyw2002** [Wynncraft/Issues#5377]
Hello,
One day, when I logged in to my lvl 47 Archer, My Legendary 'Glacial Crest' has been disapeared.
I tried to find in the bank and every other classes' inventorys but I was not able to find out.
What should I do? And MY in game name is G_G_Marvel

**Comment by gyw2002** [comment]
Sorry for misunderstanding.
In the spider dungeon, I accidently pressed q and I dropped my bow in front of the boss entrance. So I died and get up to the boss entrance and I was not able to find my bow. What should I do?

**Comment by Moe-Ronickah** [comment]
FIRST, change your drop key to something like "Delete".  Then, find or buy a new bow.  Dropped items despawn after a fixed amount of time.

**Comment by YunoFGasai** [comment]
even if you got back in time the dungeon is located of the main map so when you died the chunk unloaded and the items despawned
