### ISSUE TITLE
Wynn Site D Traitor Amadel Won't talk

### ISSUE THREAD

**Issue by CreepaBoy** [Wynncraft/Issues#5380]
My Quest book say "Speak to Rebel Leader Amadel" But when I go up to Traitor Amadel and click him He puts a blank line in chat. And my book won't update.

**Comment by Trixter313** [comment]
Does using the command /fixquests return any items for the quest?
Also, did you log out or get kicked while some quest dialogue was happening in chat?

**Comment by XavierEXE** [comment]
I think the quest trigger for entering the hideout might have messed up, try exiting the hideout, and then going back up to the guy you gave the map fragments to and entering the hideout again.

**Comment by Yaendhal** [comment]
you need to have the map "enter the traitor camp at x/y/z"
