### ISSUE TITLE
i cant get unbanned

### ISSUE THREAD

**Issue by osher16** [Wynncraft/Issues#5381]
blahblah161616 tried to unban me he said im unbanned but when i try to log in to the server it sais im BANNED and i cant log in please help me and him IGN: MikmakBadassXz 
thanks

**Comment by YunoFGasai** [comment]
@osher16 please wait some time, it might take some time for the server to receive that you were unbanned. 
also please don't spam the moderator.

**Comment by AckroWynn** [comment]
The banning panel is currently not working for moderators. Please, wait until this has been repaired.

**Comment by Moe-Ronickah** [comment]
@osher16 , I've read your thread on the forums, today.  Let us know when this is fixed for you, OK?

**Comment by Moe-Ronickah** [comment]
RESOLVED
