### ISSUE TITLE
I keep getting kicked for flying

### ISSUE THREAD

**Issue by MajesticCreeper** [Wynncraft/Issues#5382]
I can't get on without being constantly being kicked. It started when I finally logged back on after a few months and I was normally kicked and put into lobby by a normal suspicious movement kick. But when I got put into lobby, I we getting kicked for flying constantly, one after the other, giving me no time to do anything. I have reclogged numerous times already and nothing is working. Please help. Thank you.

**Comment by MajesticCreeper** [comment]
false alarm just got help from someone else and it seemed to have worked. Sorry.

**Comment by YunoFGasai** [comment]
@MajesticCreeper can you share the help with us? how did you resolve the issue?

**Comment by Trixter313** [comment]
I'll close the issue but feel free to comment how you fixed it as YunoFGasai said.
