### ISSUE TITLE
Entities attacking after death

### ISSUE THREAD

**Issue by ilcalmissimo** [Wynncraft/Issues#5384]
After i killed a mob, the health bar doesn't instantly disappear and a ghost hits me if i'm near.
This is a serious problem for close-range classes like warrior or assassin.

IGN: ItaWarriorYT

P.S.: i died many times cause of this bug and even lost dungeons

**Comment by Trixter313** [comment]
Could you tell us what you were attacking when you experienced this? It might be limited to one mob group. Thanks!

**Comment by ilcalmissimo** [comment]
Rats, Zombies, Pigmans, Skeletons (The only types i have fighted so far)

**Comment by ilcalmissimo** [comment]
btw it's ItaWarriorYT not ItaWarroprYT

**Comment by ilcalmissimo** [comment]
After 1-2 seconds the ghost disappears.

**Comment by Moe-Ronickah** [comment]
Possibly linked to the recent 14.0.11 patch?

**Comment by YunoFGasai** [comment]
salted posted another fix for this, please let us know if this keeps happening.

**Comment by Moe-Ronickah** [comment]
Fixed.

**Comment by ilcalmissimo** [comment]
Thanks

Il lunedì 4 luglio 2016, Nathan Stolov <notifications@github.com> ha
scritto:
