### ISSUE TITLE
Skills Glitch

### ISSUE THREAD

**Issue by Karatedodo** [Wynncraft/Issues#5385]
My strength is lvl 11 and it keeps going down to lvl 9. It does this constantly and the weapon i use needs lvl 10 strength so I cant use it most of the time. Please help to see why this happens to me!

**Comment by Trixter313** [comment]
Your armor or accessories are probably modifying your skill points. Check them all to see if they say anything about it in their stats. Also, if a skill is being modified, it will say so when you mouse over it.

**Comment by Moe-Ronickah** [comment]
RESOLVED
