### ISSUE TITLE
Unescapable area on Christmas Island

### ISSUE THREAD

**Issue by CookieDreams57** [Wynncraft/Issues#5386]
Ok, I was in the middle of helping Santa and looking for the time machine. I thought I found a secret or wherever I needed to go on the mountain, but after jumping in I panicked because there is no way to use teleport scrolls or kill yourself to get out without a rank. If you can teleport me out and fix this hole that'll be greatly appreciated. 👍 The hole is located at 1125 62 -3177 thank you.

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out. =)

**Comment by Moe-Ronickah** [comment]
Yuno, another hole for your list.

**Comment by YunoFGasai** [comment]
added to the to do list

**Comment by Moe-Ronickah** [comment]
Thanks @CookieDreams57 .
