### ISSUE TITLE
Traproot Quest Bug

### ISSUE THREAD

**Issue by QuotenPole** [Wynncraft/Issues#5388]
At the point, where i have to give the Witch their Flowers, she don't take them and says:
The flowers we need are Ginseng, which grows in caves, Lobelia... etc.
Please help ._.

**Comment by Trixter313** [comment]
What does it say in your quest book?

**Comment by QuotenPole** [comment]
Grab Tiek [1 Ginesang], [1 Lobelia], and [1 Vervian] from her garden

**Comment by QuotenPole** [comment]
Done.
But thanks for your answer :D
