### ISSUE TITLE
Bug cowfusion

### ISSUE THREAD

**Issue by Boil9** [Wynncraft/Issues#5389]
In a quest i got an item and i went to pick it up and it disappeared i needed it to finish the quest
is there anyway i could get it back so i can finish the quest
quest: Cowfusion

**Comment by YunoFGasai** [comment]
you need 2 items for this quest. which one cant you pick up?
is it  [1 Drale’s Permission] or [1 Sacred Hay] ?

**Comment by Moe-Ronickah** [comment]
RESOLVED
