### ISSUE TITLE
The House of Twain (KEEP IN MIND THIS ALSO MEANS SPOILERS FOR THE QUEST ITSELF)

### ISSUE THREAD

**Issue by CrystalGarnet** [Wynncraft/Issues#5391]
Well.
I was doing well in the Twain quest.
I pushed the button inside the tomb and I went out ASAP to get to the quartz grave.
I quickly equipped my Ghost Veil helmet and tried to go in, but
It said I didnt have it on.
When I look back, my Iron helmet (Helm of the Dead) is equipped, while the Ghost Veil is in my Hotbar. I tried DRAGGING the helmets and it still didn't work.
I couldn't finish the quest JUST because of this part.
(In a nutshell, it wont not only say i dont have the veil, but also unequip it and put back my iron one)

**Comment by YunoFGasai** [comment]
you probably lagged, try equipping your ghost helm beforehand (make sure its on) and do that part again (only costs 3 emeralds, one for each eye and one for the tomb).

**Comment by Villageacules** [comment]
@CrystalGarnet are you still having issues? Did you look at a quest guide and discover if you did anything wrong?

**Comment by Moe-Ronickah** [comment]
So, you are trying to enter the grave in House of Twain with a Ghostly Veil helmet, and not a Ghostly Cap?  Is this a helmet from another quest, because the [helmet that you need](https://wiki.wynncraft.com/index.php?title=Ghostly_Armour) costs 1LE and must be purchased in the Haunted Mansion.

**Comment by CrystalGarnet** [comment]
Thanks. I fixed the problem. Lag came in. I finished the quest, thanks so
much for the help
Keep going with the good Wynncraft game :)
-Garnet

2016-07-26 16:05 GMT-04:00 Nathan Stolov <notifications@github.com>:
