### ISSUE TITLE
Stuck in prison cell at Gavel!

### ISSUE THREAD

**Issue by BrewhausB** [Wynncraft/Issues#5392]
I was exploring the prison and I went through a door and I teleported to inside a cell and there is no way for me to get out. Plus, I CANT FIND THE STUPID SEWER FOR Heart of Llevigar!

**Comment by YunoFGasai** [comment]
use /kill if you have more than 3 soulpoints.
you can youtube a walkthrough and follow it. (the sewer entrance is in front of the bank)
