### ISSUE TITLE
Set bonuses have no affect in guild wars

### ISSUE THREAD

**Issue by MedievalBladeRPG** [Wynncraft/Issues#5393]
In guild wars, set bonuses have no affect, however, i have only tested this with the full snail set.
Below are pictures of my health and set bonus before and after entering the guild war.
![2016-07-04_23 58 12](https://cloud.githubusercontent.com/assets/16379066/16573584/9c5f041a-4243-11e6-8e50-3a7311155737.png)
![2016-07-04_23 58 17](https://cloud.githubusercontent.com/assets/16379066/16573583/9c5e466a-4243-11e6-8b56-8f43a337355a.png)
![Uploading 2016-07-04_23.59.10.png…]()
![2016-07-04_23 59 13](https://cloud.githubusercontent.com/assets/16379066/16573606/d73a3988-4243-11e6-8182-241bfc252637.png)

**Comment by YunoFGasai** [comment]
will add to guild war thread
