### ISSUE TITLE
Horses from the new update

### ISSUE THREAD

**Issue by emirlw** [Wynncraft/Issues#5394]
The new horses are fast, yes. But they (almost all the time) cause me to glitch back even though I'm already there. For example, I went to Rodoroc's bank with my horse. But when I dismounted, I'm still at the main entrance. The horses before this update never did this. Please fix it. :)

**Comment by YunoFGasai** [comment]
please use Minecraft version 1.8.9 or bellow to fix this issue.

**Comment by Trixter313** [comment]
Let us know if switching MC versions fixes your issue or not. Thanks!

**Comment by emirlw** [comment]
Alright! Thanks!

**Comment by Moe-Ronickah** [comment]
I'll take it from your response that it's fixed.  Closed!
