### ISSUE TITLE
Flight in Distress: Quest Broken?

### ISSUE THREAD

**Issue by EximiusWynncraft** [Wynncraft/Issues#5397]
While running through the Flight in Distress quest, I lagged out and died fighting the Pirate Queen. On my return to the airship, there was no way to enter the pirate ship once again. I'm not allowed to enter the bed, nor am I allowed to talk to anyone that will get me anywhere. 

The Captain is still telling me to look for the boy, and the boy is giving me his post-script dialogue whenever I speak with him.

I have come to a point where it is impossible to progress in this quest, and addressing this issue would be greatly appreciated.

My kindest regards,
Eximius

**Comment by YunoFGasai** [comment]
you will have to go through all the stages again to get to where you were, I recommend following a YouTube tutorial so you can watch what you have to do.

**Comment by XavierEXE** [comment]
You can also just follow the steps on the wiki.

**Comment by AmbassadorArt** [comment]
You have to do everything over again, don't pay attention to the dialogue.

**Comment by Moe-Ronickah** [comment]
@EximiusWynncraft , did you get this fixed?

**Comment by EximiusWynncraft** [comment]
@Moe-Ronickah Yes, I have fixed this, a moderator can close the issue.
