### ISSUE TITLE
"Etikal" bow's sprite has many problems...

### ISSUE THREAD

**Issue by Collincreeper** [Wynncraft/Issues#5399]
The elemental bow sprite used for "Etikal" seems to have a few issues. Whenever you right-click anywhere with a bow with this sprite, it will spam "You don't have permissions in this area" in red, which completely breaks immersion.

Secondly, it is found in many item frames behind torches throught the wynn province, suggesting it was used as a torch holder. This also slightly breaks 
immersion.

Below is a picture of the bow sprite which is effected:

![2016-07-03_14 17 42](https://cloud.githubusercontent.com/assets/20301591/16587169/2ff706dc-42c1-11e6-9b91-08dc426c8685.png)

**Comment by YunoFGasai** [comment]
both issues happen because your bow is actually a block, hopefully both will get fixed soon
