### ISSUE TITLE
Misplaced HP of Villagers

### ISSUE THREAD

**Issue by bobotje** [Wynncraft/Issues#5403]
When I did hit a villager of troms this happened.
http://i.bobotje.com/gARuaf.png

**Comment by Moe-Ronickah** [comment]
Are you using any version of MC higher than 1.8.9?  If so, go back to 1.8.9.

**Comment by bobotje** [comment]
Forge 1.8.9

**Comment by Trixter313** [comment]
Can you reproduce it in vanilla Minecraft without forge?

**Comment by YunoFGasai** [comment]
@Trixter313 I can reproduce it, it seems that weapons with high knockback (slow weapons) can knock away the armor stand farther than the mob itself.

**Comment by XavierEXE** [comment]
Sometimes mobs spawn naturally with misplaced health bars as well.

**Comment by DCM627** [comment]
This also happens every time I multi hit the skeletons in Nemract with my Assassin...

**Comment by Moe-Ronickah** [comment]
RESOLVED
