### ISSUE TITLE
Can't Run

### ISSUE THREAD

**Issue by FromTheDark** [Wynncraft/Issues#5405]
So I just started and I'm a assassin but I cannot run most the time. I keep rapidly lose mana and can't run and it's super annoying cause it keeps slowing me down. Can someone fix this? Thanks

**Comment by Moe-Ronickah** [comment]
It's part of the current game mechanics, and there is nothing that we can do about it.  While it is an issue for players, it's not a bug-type issue.  You can find this problem on the forums, if you want to address it.

**Comment by DebugMC** [comment]
@FromTheDark You are in vanish :P you loose mana in vanish
