### ISSUE TITLE
Falling into ground

### ISSUE THREAD

**Issue by ProPandaAssasin** [Wynncraft/Issues#5407]
So i Had a legendary spear and all of a sudden it dissapeared so i rage quit because it took me so long to find that then all of a suddent the next day i join back i find myself in a town called like Troms and i try to find my way out and then  all of a sudden i get sucked into the ground and im like floating and i die and lose soul points and respawn back in Troms so not only am i stuck in a town called troms but i also lost my Legendary spear :( please help

**Comment by YunoFGasai** [comment]
Where were you when you lost your spear?
What level were you?
It's a bit hard to understand from your description but it seems like you are falling in the void and respaening in Troms, is that so?

**Comment by IncBear101** [comment]
Might be lag when u were sucked into the ground, because the chunks are unloaded due to lag, and the sucking to the ground void thing has happened to me with weak internet connections/lag

**Comment by IncBear101** [comment]
*chunks are loading and that causes lag sometimes

**Comment by sammyvsparks** [comment]
@IncBear101 Falling in the void to lag does not generally be considered as falling into the void and I have never seen it deal damage.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
