### ISSUE TITLE
My Inventory Disappeared And Was Replaced By Wood Bows, Please Help

### ISSUE THREAD

**Issue by Jekulidi** [Wynncraft/Issues#5408]
I logged on after leaving for a bit. I made sure that I stayed in a safe place in a village so I wouldn't die. But when I came back I found some wooden bows in my hot bar of my inventory and the rest of my stuff (also soul points), gone. I kept my level, and quest data, also my character info. If a staff member could look into my player data and see what happened please notify me. Also, if you are a player that knows why this happened, please do the same. Thank you hope you guys and gals can help that. :)

Your fellow WynnCrafter,
Jekulidi

**Comment by Trixter313** [comment]
Are the bows oak wooden bows that are untradeable? If so, it would sound like you were killed many times because when you die you keep quest items and untradeable items but also get an untradeable item for your class so they would stack up after a while of dying. Is ti possible someone else has access to your account/knows your password?

**Comment by YunoFGasai** [comment]
also, where did you afk?

**Comment by C0meGetS00me** [comment]
Trixter there's no untradable bows for quests in wynncraft.

**Comment by YunoFGasai** [comment]
@C0meGetS00me the starter bow is untradeable, trixter never said the untradeable bow is for a quest.
when you die with less than 2 soulpoints you lose all of your stuff and get an untradeable bow.

**Comment by XSpringtrapX** [comment]
Today I log into Wynncraft, I jump into a world, everything looks fine so far. I pick out my Archer class, I log in & to my surprise I've lost everything that was trade-able, my money, my 1st black horse, all my good gear I was wearing, GONE. Plus I got tons, Skele-TONS of crappy wooden starter bows. PS I was in a safe place when I last logged off. I was in Nesaak village. If anybody got any idea how to get their stuff  back that they lost plz tell me. 8U

**Comment by YunoFGasai** [comment]
@XSpringtrapX please open a new issue, nesaak isnt safe in any way for you to afk there.

**Comment by XSpringtrapX** [comment]
Just being very clear here I logged off of Wynncraft before I lost my stuff, if I was to be afk, I'd try to find myself in a suitable spot where those Windigoes won't get to me. You seem to assume I was afk on the ground which I was not. I logged out. I logged back in. Stuff is gone. End of story. Very simple stuff to understand, am I not correct?

**Comment by sammyvsparks** [comment]
@XSpringtrapX We'd suggest you do as @YunoFGasai asked and make a new issue as it was not part of this original issue.

**Comment by XSpringtrapX** [comment]
What subject do you wish me to issue on anyway? Do tell. I'm all ears & zero brains. Also I only came to this particular Issue cuz I was having the problem. I thought if I came here & asked how to fix the problem I thought I'd be much happier... but, I get criticized instead. How lovely... I'm only but a noob (I'm new to this website) not trying to make peoples lives harder, Ya know. So I guess all I can say is I'm sry. Plz no hate on me. (6_6)
P.S. I barely even know how to make an issue, so far the best I can do is comment on things. (9_9)

**Comment by sammyvsparks** [comment]
@XSpringtrapX at the top press "New Issue" to post a new issue with your details, that will allow us and anyone else to investigate the issue further and easier.

**Comment by XSpringtrapX** [comment]
Ok thx for your help buddy, but what will my issue even be?! I need ideas. Something about Wynncraft might be fun. :3

**Comment by sammyvsparks** [comment]
@XSpringtrapX your inventory issue. We can at least tell you what happened and how.

**Comment by XSpringtrapX** [comment]
Ok. Wuts an inventory issue?

**Comment by sammyvsparks** [comment]
Everything you posted here, but in its own issue.

**Comment by XSpringtrapX** [comment]
Ok. :3 Welp I'll give it a try & make my own issue despite it possibly being random in the end. Will you look at it & see if it'll work for here? If you think it needs ta be changed a bit plz tell me & I'll change it up a bit. "TemMIE wal mac uz prods" Temmie from Undertale. :)

**Comment by XSpringtrapX** [comment]
I did it I made an issue & I can say it'll be pretty punny in the long run.

**Comment by Moe-Ronickah** [comment]
I'm sorry.  I accidentally deleted a comment that I wanted to keep.  There are untradeable beginner weapons in WynnCraft, and no one referred to them as quest items.

The rest of the comments were deleted because they simply did not belong in this issue.
