### ISSUE TITLE
Disappearing Wand!

### ISSUE THREAD

**Issue by Archlight3** [Wynncraft/Issues#5410]
I was playing with a friend on the server, we decide to take a quest to "rooster island" so while i teleported to Nemract i decided to get a backup teleport scroll. When i went in, i glitched in the roof, i then had no choice but to teleport to Ragni, when i did, my staff disappeared and now im stuck with a low level staff at lvl 31! The staff didn't appear no matter how much i searched for it. It was something like the Broken Harp

**Comment by Moe-Ronickah** [comment]
First, if your drop key is set to "Q", change it to something like "Delete."

I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency.  You might be able to find someone to buy your lost item from, or, possibly, someone who will even give you one, for free, depending on the value of your item.  Ask around in Detlas and check the Trade Market on the forums.  Good luck.
