### ISSUE TITLE
My Relic wand disappers after getting it

### ISSUE THREAD

**Issue by GunAssassin50** [Wynncraft/Issues#5411]
I went to get my relic wand and got it then tped to llevingar and it magically disappered

can you please get it back

**Comment by Moe-Ronickah** [comment]
First, if your drop key is set to "Q", change it to something like "Delete."

I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency.  You might be able to find someone to buy your lost item from, or, possibly, someone who will even give you one, for free, depending on the value of your item.  Ask around in Detlas and check the Trade Market on the forums.  Good luck.
