### ISSUE TITLE
Stuck in Finding the Light 

### ISSUE THREAD

**Issue by SlapMyDice** [Wynncraft/Issues#5412]
At stage 20 of finding the light, Charlie gives me his text from stage 7. The book tells me to go to Ollie. When I talk to Ollie, he tells me to check my book. I'm stuck and unable to finish the quest, any help is appreciated! In Game Username is SlapmyDice, if that is of any help.

**Comment by Moe-Ronickah** [comment]
At Stage 20, you only need to talk to Ollie.  Ollie should tell you to go back and talk to the Guardian of the Forest.

You have no reason to talk to Charlie, at this stage, at all.
