### ISSUE TITLE
Potions and Powder makes Quests bug

### ISSUE THREAD

**Issue by Amonzip** [Wynncraft/Issues#5413]
Hello, in the Wynncraft update 14.0.11 Powders can not be used and that is an issue.

In the quest "Tempel of The Legends" you need red powder 2 and green powder 2, but they can not be used so the quest cant be completed. The same for the quest "Potion Making" where you need 3 "Potion of Healing 1" wich no longer exists because the item got changed.

The "Temple of The Legends" quest is a VERY important quest in Wynncraft and everyone is annoyed of grinding/farming in herb cave so they want to farm the "Trainer"s in Tempel of Legends.

I think this is a big issue, please fix.

**Comment by Moe-Ronickah** [comment]
It's not a problem:
Green, blue, and red powders I and II can be obtained from their respective relic shrines.
Potion of Healing I is simply the weakest healing potion that you can buy.

**Comment by YunoFGasai** [comment]
(please close this)

**Comment by Moe-Ronickah** [comment]
@Amonzip , have you found everything, now?
