### ISSUE TITLE
I m blocked in to a wall :/

### ISSUE THREAD

**Issue by LuxanPnk** [Wynncraft/Issues#5415]
I do the quest Wynn excavation site B, but I have blocking in the wall  at the end of the quest :/ Help me please !

**Comment by Moe-Ronickah** [comment]
Some teleport areas are very finicky, unfortunately.  If you have a teleport scroll, you can try to use it.  If not, make certain that you have 3 or more soul points, then use /kill.

**Comment by XavierEXE** [comment]
You can also do /class multiple times, as doing /class raises your y coordinate by one. You can use this to get out of the floor.

**Comment by Moe-Ronickah** [comment]
I'm not certain if LuxanPnk is stuck in the floor, but your advice is good to remember.

**Comment by YunoFGasai** [comment]
(please close this)

**Comment by Moe-Ronickah** [comment]
@LuxanPnk , are you still stuck in the floor?
