### ISSUE TITLE
Died with 12 soul points, lost inventory

### ISSUE THREAD

**Issue by hawser** [Wynncraft/Issues#5416]
I died and lost all my inventory when I still had 12 soul points. I was in a safe village on top of a house and I went to the wynncraft map .  When I returned I was dead and I had nothing but oak wood wands and 10 soul points.

**Comment by Moe-Ronickah** [comment]
Hostile mobs are glitched, right now, in that they can enter cities and villages.  The fact that you had oak wood wands means that you died multiple times, until you were killed.  You got one wood wand for every time that you were killed.  Somehow, one or more hostile mobs got up there with you, and clobbered you.  The admins know about this, and they are working on it.
