### ISSUE TITLE
Im stuck at the innkeeper

### ISSUE THREAD

**Issue by MyNinjaMike** [Wynncraft/Issues#5421]
i went to explore the inkeepers house near nemract and got in one of the beds.  when i got out of it, it spawned me in a 1x1 block hole. than there was NO way out.  if there is a way for this to be fixed, it should be. i figured out that you can type /kill, but some people might not know that.  just want to let people know before they go quitting because they are ''stuck''.

**Comment by Moe-Ronickah** [comment]
Sleeping in a bed in a multi-player world does have it's dangers.  I'm glad that you got out.
