### ISSUE TITLE
Extra purple crystal shards after WynnExcavation site B

### ISSUE THREAD

**Issue by AK-saurus** [Wynncraft/Issues#5422]
I thought i was missing a quest item when doing Temple of the Legends, but it was just hidden in my enderchest, so i did /fixquests and it gave me 2 extra purple crystal shards that I don't need and can't get rid of. It'd be helpful if someone could help me get rid of them

**Comment by YunoFGasai** [comment]
fill up your inventory with items (emeralds work fine) and then split a stack of emeralds and click on the quest item and throw it away, it will try to return to your inventory but wont have any space so it will delete itself.
