### ISSUE TITLE
Death Whistle (The_Dragon_Rider doesn't get the drops from the witch)

### ISSUE THREAD

**Issue by ethandonley2002** [Wynncraft/Issues#5423]
So I'm doing this for the_dragon_rider since he doesn't have an account here. So whenever he kills the witch, he doesn't get her drops. He tried killing her more than 3 times and still no luck. Is there a solution to this. And no, I wasn't there so i didn't have the drops.

**Comment by Moe-Ronickah** [comment]
Trying to trouble-shoot a problem through a third party is usually very difficult, however, this one is easy.  Your friend is at the wrong mountain.  He needs to keep going in the same general direction.  The only thing at the top of the mountain with the Death Whistle is the Death Whistle.  The witch is at the top of the only mountain that is in between Voer and the Death Whistle mountain at [-2064,56,-5190].

**Comment by YunoFGasai** [comment]
(please close this)

**Comment by Moe-Ronickah** [comment]
@ethandonley2002 , did you find the right mountain?

**Comment by ethandonley2002** [comment]
sorry for the late reply, but I had to check in with dragon rider and it seems like he did.
