### ISSUE TITLE
Missions Impossible

### ISSUE THREAD

**Issue by traviryan88** [Wynncraft/Issues#5425]
I was in Detlas after grinding keys for animal dungeon and i got a mission to kiss the spider boss 23 times in 5 minutes for 16,456 exp. I timed myself on running the spider dungeon and it took me 6+ minutes to complete the dungeon. That's without me falling and waiting for someone ahead of me. Not even an archer do it in that time with speed and escape. I would like this to be fixed by wither adding time or dropping the kills by over half. I also had a mission a while back to kill 24 lonely spiders and i had 5 minutes to do so. It took about 30 seconds for him to respond and about 30 to kill him. Its was impossible because it wasn't consistent. So either reduce the kills or increase the time so that way it can be possible to a certain extent.

**Comment by Moe-Ronickah** [comment]
Missions are picked purely on a random basis.  If you get a mission to kill mobs, it will be to kill the last mob that you killed.  There is nothing here to fix.
