### ISSUE TITLE
Server Restarting Xp Bomb Glitch! Help!

### ISSUE THREAD

**Issue by quinnrockstar** [Wynncraft/Issues#5426]
This glitch has happened to me 2 times now. When i was gonna throw an xp bomb right before i finished the reincarnation quest, Earlier in the chat it said Server restarting in 5 minutes. And i didn't see that, so i threw the bomb and it said something like you can not use this at this time. So i went back into the  Bomb section of my inventory to see if i had the xp bomb still. And i didn't it disappeared. So can some admin or moderator give me back my bombs or at least fix this glitch. I payed real money for xp bombs and its a waste when they glitch out of my inventory. Thank you.

![2016-07-07_17 52 22](https://cloud.githubusercontent.com/assets/15721487/16670029/b8f599d6-446e-11e6-83f3-335226802464.png)

**Comment by Moe-Ronickah** [comment]
You need to report this to support@wynncraft.com, as they are the ones that can help you with this.  Include your description of the event, and your screen cap.  Give them two days, at least, to respond.  They deal with all issues that involve hard currency.

**Comment by quinnrockstar** [comment]
@Moe-Ronickah Ok thanks

**Comment by quinnrockstar** [comment]
@Moe-Ronickah I searched up support@wynncraft.com as well as clicked your link and nothing came up or happend only an old twitter account. What do i do and were do i report this.

**Comment by Moe-Ronickah** [comment]
Send an email to that address.  Send an email to "support@wynncraft.com".  I'm sorry that I confused you by not saying that it was an email address.
