### ISSUE TITLE
how to fix unban bug!!!! (thanks salted)

### ISSUE THREAD

**Issue by osher16** [Wynncraft/Issues#5427]
so you crate an appeal you were supposed to get unbanned and you just not getting unbanned?
well thats probably because you created and appeal with the old seystem tell the mod that were supposed to unban you that you are creating new appeal
tag him
and thats it basically you are unbanned :D
-------------------------------------------------
special thanks
--------
salted
blahblah161616

**Comment by Moe-Ronickah** [comment]
I'm not really sure what you mean by this, that is, I don't really understand your issue.  Would you try to be a little more clear in what you are saying, please?

**Comment by Moe-Ronickah** [comment]
OK.  It would have been better if you had added this as a comment to your original issue, but it's alright - I understand what is going on, now.  WynnCraft has a new ban appeal system that needs to be used by the moderators, instead of the old system.
