### ISSUE TITLE
Guild contribution glitch eats your emeralds

### ISSUE THREAD

**Issue by SSentrie** [Wynncraft/Issues#5431]
I put 64 EB into my guild contribution bar then pressed e to close it and then it just ate my 64 EB; I didn't get it back and it wasn't contributed to the guild.

**Comment by Moe-Ronickah** [comment]
When you open the /guild contribute screen, there is a big, green check mark on the upper right of the donation bar.  When you hover over that check mark, it says "Accept Donation".  That's what you click on to donate to your guild.  What you did was close the interactive panel, and the emeralds vanished.
