### ISSUE TITLE
Block Glitch

### ISSUE THREAD

**Issue by HeroComm3nd4U** [Wynncraft/Issues#5433]
When you're teleporting with Mage into a corner of a block or out of your horse near command blocks, so it's tp you near the command blocks, I got out of my horse near the boss and I tp to command blocks and I was need to do /kill and suicide, Hope you fix it, 
IGN: HeroComm3nd4U

**Comment by YunoFGasai** [comment]
Nothing to fix here, this is a vanilla minecraft mechanic we have no control over.

**Comment by XavierEXE** [comment]
Well, a builder could fill in the corner so it's more than one block thick preventing a mage teleport from clipping o.b...

**Comment by Moe-Ronickah** [comment]
First, I'd like to know how you know that you are near a command block unless you are hacking.
Second, as Yuno said, it's vanilla.

Xav.  NO.  There are so many buildings and roofs in Wynncraft, that it would take way too long to fix all of it.
