### ISSUE TITLE
Skill points

### ISSUE THREAD

**Issue by ocoeeboy11** [Wynncraft/Issues#5436]
So recently I have gotten back into wynncaft and have a lvl. 42 archer class, unfortunately after the big update I was able to reset all of my classes skill points except for my archer. This making it so that I cannot use most of my gear and weapons since the new update.
Please help. Is there any way I can reset them?

**Comment by BrewhausB** [comment]
There is a NPC that sells Skill Reset scrolls

**Comment by ocoeeboy11** [comment]
Where can I find that npc

**Comment by BrewhausB** [comment]
It's a quest called the tower of amnesia. Complete it and you'll get access
to skill reset scrolls

**Comment by ocoeeboy11** [comment]
ok thanks
