### ISSUE TITLE
Enderchest Deletion Bug

### ISSUE THREAD

**Issue by BrewhausB** [Wynncraft/Issues#5437]
I had a necklace called Nutrition and a Jester Necklace in my enderchest. I traveled to another city and opened my enderchest to find that both necklaces are gone.. And I paid good money for the Jester Necklace. And I KNOW I didn't drop them

**Comment by Moe-Ronickah** [comment]
Did you upgrade your enderchest?

**Comment by BrewhausB** [comment]
I did. But that was a while after I got it

**Comment by YunoFGasai** [comment]
This makes this issue a duplicate, the blocked rows in your bank are filled with glass panes, upgrading the bank deletes the glass panes. 
Necklaces are made from glass panes so it deletes them too.

**Comment by Moe-Ronickah** [comment]
If you upgraded your enderchest with necklaces in your enderchest, well, they vanished, as Yuno described.  Is that what happened?  [#4091]

**Comment by Moe-Ronickah** [comment]
RESOLVED
