### ISSUE TITLE
Reset Scroll Merchant accessible without completing The Amnesia tower quest

### ISSUE THREAD

**Issue by inserviente** [Wynncraft/Issues#5440]
Using my mage class I was able to teleport around and up the tower until reaching the merchant, however I haven't complete the quest yet.

**Comment by YunoFGasai** [comment]
I guess we have to add barriers in the windows now...

**Comment by YunoFGasai** [comment]
@AckroWynn

**Comment by Villageacules** [comment]
I've added barriers to the windows of the tower, should prevent unwanted visitors. Closed.
