### ISSUE TITLE
Unable to join server

### ISSUE THREAD

**Issue by MechanicSlayer** [Wynncraft/Issues#5443]
Yes so what the problem is, basically, my brother Aurellis has this incapability to join any of the Wynncraft servers. What happens when he joins is that he gets put into the class select room, but the hud to choose the classes never appear on his screen rendering it impossible for him to play as a result. I had made a forum where I showed that he was actually in my guild despite him never even joining the server, and that this problem actually prevents me from being allowed to use any of my guild command like /g. The only problem I could think of is that since both our characters have had the same name at some point, the player files screwed up and overwrote his files and think that his character is mine so they don't show his stats. I think this as his name appears twice in my guild and mine doesn't even appear at all. [image](https://i.gyazo.com/545cbabb60853d5e7d70bf0c8b67fc66.png)

**Comment by YunoFGasai** [comment]
I guess he changed his name while he was in the guild, your player files don't matter as we use UUIDS but name changing in the guild will lead to a double name and not being able to se some of the commands.
as to the connection to servers have him connect to the nether server through the lobby and tell me what happens.

**Comment by MechanicSlayer** [comment]
It's not even that I had changed my name inside of the guild, the second day of the guild his name had already over wrote mine and appeared twice, as to the nether server I'll let you know

**Comment by MechanicSlayer** [comment]
When he joins the nether server he is put in an ocean and that's just basically it. Everywhere around is just the ocean. @YunoFGasai

**Comment by Moe-Ronickah** [comment]
If he was in your guild, and he changed his name, the server created a ghost copy of him.  He generally cannot, at this time, leave the guild or be kicked from the guild.  This one is duplicate.

If he was in your guild, and changed his name to a name that you had previously used, then you also are ghosted.  You may have found a new issue with guilds.

As to not being able to join the server, does he have server resource packs enabled?

**Comment by MechanicSlayer** [comment]
He has never joined the server, meaning any wynn servers. He has joined the lobby but that was it. Other than that he has never made a class or has been able to. Yes he has the resource pack on but that wouldn't change much anyways. What happened is that randomly one day, his account for some reason, had joined my guild (EVEN BEFORE HE HAD EVER JOINED THE SERVER) and it took my place. So I changed both our names to try and fix it but nothing happened.

**Comment by MechanicSlayer** [comment]
@Moe-Ronickah

**Comment by Moe-Ronickah** [comment]
Your brother has joined the lobby, but never been on any game server, correct?
Having the resource pack off can prevent a player from selecting a class.
I have a very difficult time believing that his account, which has never been in game, randomly joined your, or anyone else's, guild.  That just doesn't happen.  Either you or he added him to your guild.
You changed both of your names, again, even though you both already had been ghosted in your guild?

**Comment by MechanicSlayer** [comment]
@Moe-Ronickah I could stream the exact outcome of what happens when he tries to join the server. I could also get my guild owner to confirm that we never indeed invited him

**Comment by Moe-Ronickah** [comment]
In all likelihood, you mentioned his name to your guild owner, who invited him, whether he remembers it or not.

When he is in the ocean, have him hit F3 and see what his coordinates are.  That might be helpful.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
