### ISSUE TITLE
Breathing Helmet BUG [disappearing]

### ISSUE THREAD

**Issue by DerpTW** [Wynncraft/Issues#5446]
So I had a breathing helmet I on me and I was trading with my friend. We traded but I didnt have enough space so I made some space but there wasn't enough so I tried selling a breathing helmet for fun but then it deleted it and now I cannot complete the next breathing helmet quest!

**Comment by YunoFGasai** [comment]
use /fixquests
if that doesn't work youll have to create a new class and level it up and do the quest with it (the helmet doesn't get used up in any quest)
