### ISSUE TITLE
bugged mage wand please help me

### ISSUE THREAD

**Issue by Hawkndrag** [Wynncraft/Issues#5447]
i need help i found a bugged wand and it dose nothing can any one help me? 
![2016-07-10_08 06 19](https://cloud.githubusercontent.com/assets/20382077/16713488/12d7cdde-4677-11e6-94ee-32aba8149371.png)
![2016-07-10_08 06 53](https://cloud.githubusercontent.com/assets/20382077/16713490/1998e4f0-4677-11e6-9620-08078e0906ad.png)

**Comment by Hawkndrag** [comment]
(my ing is hawkndragon by the way)

**Comment by YunoFGasai** [comment]
that happens because your wand has an accented letter, it fixes itself periodically but I would suggest getting a new wand.
btw how and when did you get that wand?

**Comment by Hawkndrag** [comment]
@YunoFGasai i found it on the ground in the spider dungen about 2 hours before i posted this page

**Comment by YunoFGasai** [comment]
did it drop from a mob or did another player drop it?

**Comment by Hawkndrag** [comment]
@YunoFGasai a mob dropped it
