### ISSUE TITLE
ban glitch

### ISSUE THREAD

**Issue by rhinococo2004** [Wynncraft/Issues#5451]
I got banned and someone accepted the ban appeal
,but it wont let me join the wynncraft server still

**Comment by rhinococo2004** [comment]
someone pls say something

**Comment by YunoFGasai** [comment]
the ban panel is having some problems at the moment, please be patient we working on fixing this issue.

**Comment by XavierEXE** [comment]
The appeal system updated so unbans are a bit screwy right now, keep in contact with the moderator that banned you but don't beg or push for them to hurry. They're doing their best to fix all the unbans that didn't go through, you aren't the only one.

**Comment by rhinococo2004** [comment]
well @selvut283 banned me and sci_fi_nut_123 accepted my ban appeal

**Comment by rhinococo2004** [comment]
so I don't know who should I keep in contact with
