### ISSUE TITLE
Guild wars not working?

### ISSUE THREAD

**Issue by Coooldude34u** [Wynncraft/Issues#5454]
So, me and my guild are trying to attack some other territories and this is what happens: it counts to 0 then nothing at all happens, or it teleports me but no mobs spawn. Even after 10 seconds.

**Comment by Moe-Ronickah** [comment]
Please do a search for "guild war" and tell us if any of those issues matches what you are reporting.

**Comment by Coooldude34u** [comment]
nope, no reports

**Comment by sammyvsparks** [comment]
https://github.com/Wynncraft/Issues/issues/4664 is a direct duplicate with a semi-workaround comment @Coooldude34u @Moe-Ronickah.

**Comment by Moe-Ronickah** [comment]
@Coooldude34u , follow the instructions on the first page.  You will find, currently, 32 issues that match the phrase "guild war".
