### ISSUE TITLE
Dont Have Quest Item.

### ISSUE THREAD

**Issue by michal111030111** [Wynncraft/Issues#5456]
I dont have quest item. I want to do the Quest lvl 43 UnderIce but i dont have the helmet i done the quest with helmet and i dont know how but i lost it. Can some admin help me? Or give me it?

**Comment by sammyvsparks** [comment]
@michal111030111 you can use /fixquests to restore quest items, sometimes they bug and can become lost.

**Comment by michal111030111** [comment]
thank you :)

**Comment by Moe-Ronickah** [comment]
Or, sometimes, people read about a normal MC mechanic and use it to get rid of quest items, not realizing that they will need those items later on.  In Wynncraft, it's a bug abuse, so don't use it.
