### ISSUE TITLE
Stuck in an inactive guild

### ISSUE THREAD

**Issue by RealStrafeZ** [Wynncraft/Issues#5457]
So,i'm stuck in this inactive guild ( literally no one has entered for 4 months ) and whenever I try to leave,well,i cant.My name is Strafeeeee and please kick me out of this guild.The guilds name is Outcasts/OTC.Please mods,make me proud <3

**Comment by sammyvsparks** [comment]
@RealStrafeZ It can take a few tries to leave. How many times have you tried? I've had to do it over 5 times before.

**Comment by Moe-Ronickah** [comment]
@RealStrafeZ , is your current MC name GoldenLife?

**Comment by IncBear101** [comment]
You're so active Moe_Ronickah

**Comment by YunoFGasai** [comment]
@IncBear101 moe is asst. admins, he better be active.

**Comment by RealStrafeZ** [comment]
Moe,i said in the post that my name is STRAFEEEEE ( 5 of e )

**Comment by Moe-Ronickah** [comment]
@RealStrafeZ , at no time, in this issue, have you said that.  In any event, you've changed your MC name four times this year.

Duplicate of #3665

**Comment by Moe-Ronickah** [comment]
Strange, I don't remember seeing your name in the post, yesterday.  Maybe I overlooked it.  Let's just chalk it up to my reading your post to fast, and too late at night.

**Comment by IncBear101** [comment]
Who's Nathan stolov? My email from GitHub issues say its from Nathan

**Comment by sammyvsparks** [comment]
@IncBear101 Nathan is Moe-Ronickah

**Comment by IncBear101** [comment]
Oka

**Comment by Radiantal** [comment]
Could you help me as well, my username is Radiantal
