### ISSUE TITLE
Missing Stuff

### ISSUE THREAD

**Issue by m2cold** [Wynncraft/Issues#5458]
Hi, my friend was doing some quest and while she had her water breathing/diving helmet and its a quest item. Which means she can not sell, trade, or drop the item but her game glitched and she sold the helmet and now she cant finish the future quests that needs the helmet. Also while she was about to finish this quest it said was full and she dropped some items (enough to have room for the quest items) and it glitched and she picked up something and it said "you do not have enough room for the quest/rewards items" so she did not get the ex or the quest items. Please give her the quest items that she need. Her in game name is decessus101. Please do something about this as soon as possible. 
Thank you very much.

**Comment by sammyvsparks** [comment]
@m2cold sent your friend a in-game message. For future reference there is a command called /fixquests to restore any lost quest items due to bugs or drop glitches.

**Comment by m2cold** [comment]
@sammyvsparks thank so much

**Comment by sammyvsparks** [comment]
@m2cold your very welcome :smile:

**Comment by Moe-Ronickah** [comment]
@m2cold , contrary to your friend's claims, you can remove quest items through a normal MC mechanic, so you need to be careful to lose quest items.  /fixquests will currently restore most quest items from Wynn quests, but not Gavel quests.

If a quest says that you don't have enough room for the quest rewards or items, you still get the XP.
