### ISSUE TITLE
Jester Ring Vanished

### ISSUE THREAD

**Issue by Nicius** [Wynncraft/Issues#5459]
My Jester Ring Vanished!

**Comment by sammyvsparks** [comment]
Wynncraft has a no refund policy for ingame items, you will need to find another or buy from a player.

**Comment by Moe-Ronickah** [comment]
@Nicius , please give us more details on this.  Was it in your bank?  Was it in your inventory?  Were you wearing it?  Had you just expanded your bank by buying a new row?  Had you been moving things around in your inventory?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
