### ISSUE TITLE
a lot of xp glitch

### ISSUE THREAD

**Issue by puppuppies2** [Wynncraft/Issues#5461]
Hello, I was doing the Wynncraft Excavation Site D quest when i was lvl 71. I then cleared the quest and only got 1 lvl from the xp. The xp said it had gave me 600,000 xp when it only gave me around 150,000 xp. My friend had finished the quest with me and got 4 lvls from the quest. My friend was lvl 71 as well. I would like to get my xp back, due to it being really hard to lvl up with the missing xp. If you need proof please check the files.
![2016-07-11_15 47 25](https://cloud.githubusercontent.com/assets/20410166/16752650/ec4f6f24-477e-11e6-962c-d618f4d721f2.png)
I didn't get to take a photo at the time, due to me having to go to sleep right after. Please help me get my xp back.

**Comment by sammyvsparks** [comment]
Did you have guild xp enabled perhaps?

**Comment by puppuppies2** [comment]
what do you mean?
I always get my xp normally and this one didnt give me the xp.

**Comment by sammyvsparks** [comment]
@puppuppies2 as it seems you are a member of "xXFairyTailXx" . Quest experience is lowered if you use the command **/guild xp ##** which may of caused your deducted experience from WynnExcavation Site D

**Comment by puppuppies2** [comment]
i have not been giving guild xp...
even before i did the quest.

**Comment by sammyvsparks** [comment]
@puppuppies2 is your XP Bonus negative? (Check the compass)

**Comment by puppuppies2** [comment]
no

**Comment by sammyvsparks** [comment]
Then last likely cause is because your level 82 you need a significantly higher amount of experience to level up. 

![mage_stats_puppuppies2](https://cloud.githubusercontent.com/assets/12182390/16753594/46f6720a-47a8-11e6-932e-f8d9f9ce62a4.png)

**Comment by puppuppies2** [comment]
like i said i was lvl 71 when i did the quest and only went to lvl 72

**Comment by sammyvsparks** [comment]
@puppuppies2 directly from the wiki is the experience requirements
Lv. 071 	920,000 xp 	Lv. 072
Lv. 072 	1,010,000 xp 	Lv. 073 
The full quest experience would not have gave you a full level unless you were partially complete on level 71, your friend may of used high experience bonus armor and double exp bomb to obtain more.

**Comment by puppuppies2** [comment]
my friend only had 4% more xp bonus than me.
That would have not made that much of a difference.

**Comment by sammyvsparks** [comment]
@puppuppies2 as it stands you received as you did from the quest. Wynncraft has a no-refund policy for in-game items and rewards that are not from the WynnCraft store. Your friend must of done something different to get additional experience from the quest.

**Comment by puppuppies2** [comment]
okay well that sucks.

**Comment by Moe-Ronickah** [comment]
@puppuppies2 , without video evidence from both of you, it is impossible for us to tell what really happened.  As sammyvsparks said, there must have been some difference between the xp bonuses that you and your friend had on your armor and weapons in order for there to be such a huge difference in xp gained.  Were you finishing the quest with an XP bomb?  Is it possible that you turned yours in a moment too late for the XP bomb bonus?

**Comment by Moe-Ronickah** [comment]
Also, please set your guild xp to "0".

**Comment by YunoFGasai** [comment]
it might be possible that your friend used a wisdom potion to boost his xp.

**Comment by IncBear101** [comment]
Wisdom Pots don't bootst ur QUEST XP only MOB XP

**Comment by Moe-Ronickah** [comment]
@IncBear101 , that is not correct.

**Comment by XavierEXE** [comment]
I got almost 10 levels from this quest with Double XP, a Wisdom Potion, and 127% XP Bonus, is it possible your friend used any of those methods to get more xp?

**Comment by IncBear101** [comment]
@Moe-Ronickah
https://wiki.wynncraft.com/index.php?title=Potion_of_Wisdom
The wiki says it does not apply to quests. 
Are you saying that it's a typo on the wiki? 
(No rudeness intended)

**Comment by IncBear101** [comment]
Sammy where did u get the stats? Like the blocks walked, death count, etc

**Comment by sammyvsparks** [comment]
@IncBear101 http://wynnapps.tk/

**Comment by Moe-Ronickah** [comment]
@IncBear101 , I'm saying that we get different information from staff at different times.
