### ISSUE TITLE
I failed you Wynncraft I don't know how to get rid of this ISSUE!!!

### ISSUE THREAD

**Issue by XSpringtrapX** [Wynncraft/Issues#5463]

**Comment by sammyvsparks** [comment]
@XSpringtrapX This is considered a invalid issue. Issues here pertain to wynncraft mechanics, gameplay, world, inventory, etc.

@Moe-Ronickah Could you close this please.

**Comment by XSpringtrapX** [comment]
I knew it. I knew you'd tell me to change some things on here. I'm a mind reader. But ya sure I can close this issue down. Or maybe I can edit it? You said that it needs to follow Wynncraft mechanics or something like that right. Can I make an issue about the Classes you can choose from & what the classes are capable of? Or will that not work either?

**Comment by sammyvsparks** [comment]
@XSpringtrapX This place for issues regarding wynncraft. Suggestions or anything else is for the forums [ http://forums.wynncraft.com/ ]

**Comment by XSpringtrapX** [comment]
Ok so WHY does my issue have to be at the TOP of the page?! This is so embarrassing!  ._. But ya I see yr point this is under the Bugs or Glitches subject & what I have here needs to CHANGE. 8U

**Comment by XSpringtrapX** [comment]
ok I had another idea so how do u like it now? Is it better or is it worse?

**Comment by XSpringtrapX** [comment]
Hey Sammy how do I get rid of an issue when you know you don't want to keep it for your own good?... (9_6)

**Comment by Moe-Ronickah** [comment]
@XSpringtrapX , if you are using any version of MC above 1.8.9, we suggest that you revert to 1.8.9.  There are severe problems with horses in newer issues of MC and Wynncraft is 1.8.9 compliant.
