### ISSUE TITLE
Thieving Rodents - Wedding Ring not accepted

### ISSUE THREAD

**Issue by adam-jw** [Wynncraft/Issues#5464]
Hi there!

Old player, returning after a long time.

With the quest Thieving Rodents, the NPC doesn't seem to accept the Wedding Ring item. Infact, I had 3 of them and I couldn't complete the quest as the NPC simply wouldn't accept it!

Thanks

**Comment by sammyvsparks** [comment]
@adam-jw what part of the quest are you on (in quest-book), and did you re-obtain it since you last played (the lore/data values may of changed on it). Also there is 2 variants of the "Wedding Ring", There is a Iron and Golden one. You may be using the wrong variant

**Comment by adam-jw** [comment]
"Find the ring in the hive and return it to Farmer Kelri"

I wasn't aware there was 2x variations, I had only obtained an Iron (ghast tear) variant, I will return and attempt to obtain a gold variant. 

@sammyvsparks

**Comment by sammyvsparks** [comment]
@adam-jw you need to enter the nest to obtain the golden ring (the dialog informs you of that when you turn in the iron ring)

**Comment by adam-jw** [comment]
@sammyvsparks Thank you. Totally missed it - I apologise, in the middle of the quest I was battling the missing tall grass texture, had to downgrade to 1.8.9

Thank you - I will reopen if unsuccessful.
