### ISSUE TITLE
Simple bug with receiving the: New Quest: Maltic^s Quest notification (Typo)

### ISSUE THREAD

**Issue by TheTrueBanana** [Wynncraft/Issues#5466]
https://gyazo.com/6cd103b061487af72d02ae6c75bd6567

**Comment by sammyvsparks** [comment]
Issue Mentioned in https://github.com/Wynncraft/Issues/issues/5362; Possible duplicate.
@TheTrueBanana those typos may or may not be able to be fixed due to wynncraft coding setup.
