### ISSUE TITLE
Impossible To Open High In the Sky Loot Chest

### ISSUE THREAD

**Issue by IncBear101** [Wynncraft/Issues#5470]
Don't ask me how this got here:
![2016-07-12_11 00 21](https://cloud.githubusercontent.com/assets/20328015/16775859/f1898352-481f-11e6-845d-96f72e6b7645.png)
![2016-07-12_11 02 21](https://cloud.githubusercontent.com/assets/20328015/16775905/1f591e14-4820-11e6-95c9-32b12bcb3a12.png)
Its above the ocean mini dungeon I used optifine (don't ban me for that plz)
![2016-07-12_11 03 48](https://cloud.githubusercontent.com/assets/20328015/16775959/501984e4-4820-11e6-88ae-73dbdf696067.png)

**Comment by YunoFGasai** [comment]
I think someone did get there, I am also pretty sure this got removed in the game server.
@AckroWynn can you check if it was removed?

**Comment by IncBear101** [comment]
What do u mean someone did get there? and if it was removed shouldn't chunk upload and remove it as a visual glitch?

**Comment by IncBear101** [comment]
It IS a loot chest, I'm an archer and used "escape" Spell to see it with particles

**Comment by YunoFGasai** [comment]
I think someone got there, not sure if they did or not.
if it was removed on the build server it wont be gone on the play server until the next map push.

**Comment by IncBear101** [comment]
Got it
