### ISSUE TITLE
Not able to join Wynncraft servers with a Mac

### ISSUE THREAD

**Issue by SmexySam** [Wynncraft/Issues#5472]
Hi. I haven't played this server in about 1-2 years but am now interested in playing again. Whenever I try to join a wynncraft server I end up falling into the abyss. I do not have resource packs on and I prefer them not to be on, has something changed where it is necessary to use to resource pack? I am using a Mac. Thanks.

**Comment by sammyvsparks** [comment]
@SmexySam is your system capable of the min. specs for minecraft? also it is recommended that you use the resource pack or the game makes absolutely 0 sense.

**Comment by SmexySam** [comment]
Yes it is, all the requirements are there. And I never really liked the wynncraft resource pack, I prefer the blocky look even though certain items look a little odd.

**Comment by sammyvsparks** [comment]
Im not 100% sure but they may require the resource pack, perhaps try using the resource pack to see if there is a difference in loading?

**Comment by YunoFGasai** [comment]
Smexy the game changed, you now have to enable the texture pack or the game won't make any sense.

**Comment by Moe-Ronickah** [comment]
And we have several reports of players being unable to join without the resource pack enabled.  It's not something that Wynncraft is doing intentionally.  There seems to be a timing error of some kind going on that's letting players fall through the setup phase if they don't have texture packs enabled.  Please, enable texture packs, and don't use any MC higher than 1.8.9 as that is the highest level that WynnCraft is set up for.  Let us know what happens.  Good luck.

**Comment by XavierEXE** [comment]
Let's just hope this isn't another case of corrupted player data.

**Comment by Moe-Ronickah** [comment]
@SmexySam , are you able to join the servers?
