### ISSUE TITLE
My Sage wand (35% Xp, 2/4 Mana) got deleted

### ISSUE THREAD

**Issue by Comazur** [Wynncraft/Issues#5474]
My dog stepped on my keyboard, and accidently hit my "Q" button. I had my Sage in my hands so I dropped on a cactus. You really should patch the cactus-destroying items problem.

**Comment by sammyvsparks** [comment]
I don't believe that can be patched, as it is a hard coded mechanic in minecraft (I would have to javadoc check myself on that one)
However, Wynncraft has the No-Refund Policy for in-game obtained items and non-store purchases. Sorry for any inconvenience it may cause you. However I will check if patching cactus drops is even possible.

**Comment by Comazur** [comment]
ty i guess...

**Comment by sammyvsparks** [comment]
Also a semi-fix you can do to prevent this in the future is simply disable your drop control while playing Wynncraft. I do that just so I can't ever do that to myself.

**Comment by YunoFGasai** [comment]
Please prevent from shitposting on the github.

**Comment by Moe-Ronickah** [comment]
@Comazur , you know that anything that hits a cactus in normal MC is going to be damaged.  Well, the same thing happens in WynnCraft.

Also, teach your dog to stay off of your keyboard.
