### ISSUE TITLE
Powders

### ISSUE THREAD

**Issue by IncBear101** [Wynncraft/Issues#5475]
Are Powders being reworked? Its very confusing as I wonder if I should get/find them, or just wait until they're finished doing whatever they're doing with the powders and does this mean that I can get the powder that I thru out because I thought they were useless?

**Comment by sammyvsparks** [comment]
They are currently disabled but it is recommended that you can keep them if you wish because they will be usable once they are finished recoding Wynncraft's Powder System. (Some quests require powders of different levels.)

**Comment by IncBear101** [comment]
Do you know anything about the New Power System?

**Comment by sammyvsparks** [comment]
Not one bit, they haven't made any teasers that I've seen yet.

**Comment by IncBear101** [comment]
They make those?

**Comment by IncBear101** [comment]
trailers/teasers

**Comment by IncBear101** [comment]
Also, can u get the relics twice in one class?

**Comment by sammyvsparks** [comment]
They have a cooldown of a specific time. Also on the Forums they make periodic new posts in the form of video or screenshot.

**Comment by YunoFGasai** [comment]
The powder relics have a 4 hour cooldown.

**Comment by Moe-Ronickah** [comment]
**This entire thread would be better discussed on the forums, and not on the GitHub.**
