### ISSUE TITLE
Horse

### ISSUE THREAD

**Issue by ramirobuisan** [Wynncraft/Issues#5477]
My Horse disapired from my inventory
i dont do nothing

**Comment by ramirobuisan** [comment]
i'm in world 18 ign: RamiroBuisan

**Comment by YunoFGasai** [comment]
what is your drop key?

**Comment by ramirobuisan** [comment]
q

**Comment by ramirobuisan** [comment]
when i press the q the mount disapier

**Comment by glowinginoureyes** [comment]
That happened to me too, I just logged in and my horse saddle wasnt in my inventory anymore.

**Comment by YunoFGasai** [comment]
@ramirobuisan so you threw your horse out?

**Comment by YunoFGasai** [comment]
@glowinginoureyes please open a new issue.

**Comment by Moe-Ronickah** [comment]
@ramirobuisan , that's a normal MC mechanic.
