### ISSUE TITLE
Lost emeralds

### ISSUE THREAD

**Issue by lasse333** [Wynncraft/Issues#5479]
I lost 20EB because of server Lag kicking everyone out of the Game please help

**Comment by sammyvsparks** [comment]
@lasse333 Wynncraft has been having these issues for the last few days with it being more frequent. It is nothing we can control at the current time and Wynncraft's No Refund Policy still stands with these issues. Sorry for any inconveniences it may cause for you.

**Comment by Trixter313** [comment]
As mentioned above, there's nothing we can do about the lost emeralds unfortunately but we are working on fixing the issues so it doesn't happen again. Until they are fixed, try and be as speedy as possible with any risky actions that could result in loss of items please. Thank you!
