### ISSUE TITLE
Thunder Voucher from Qira Gone - Didn't Use It

### ISSUE THREAD

**Issue by bikergal12** [Wynncraft/Issues#5481]
I was playing Wynncraft and was going to go advance in the Qira Hive and defeat the Air Floor Boss when I noticed that my Thunder Voucher wasn't in my inventory like I remember. I looked in my Bank and even checked all of my other classes but couldn't find it at all. I know I did not use it because I don't have any of the armor or accessories that you can get from the Thunder Merchant. 

I have attached screenshots of my inventory and Bank to show that it is not apparent in either and that I have not purchased any of the armor. The diamond armor that is in my bank is a Speaker, White-Hot Leggings, and Ensa's Ideals. The diamond boots in my inventory is the Boots of Blue Stone.
![2016-07-14_01 35 46](https://cloud.githubusercontent.com/assets/20452500/16830260/6fd9c656-4963-11e6-8687-8bf8c82cc514.png)
![2016-07-14_01 36 34](https://cloud.githubusercontent.com/assets/20452500/16830259/6fd948de-4963-11e6-978e-a68c32c3460d.png)

**Comment by sammyvsparks** [comment]
@bikergal12 Where did you store it and is there a chance you accidentally dropped it? 
However Wynncraft has their no refund policy for in-game items that are not purchased from the store. So there is no way you can get it back except for facing it on another class. Sorry for any inconveniences it may cause.

**Comment by bikergal12** [comment]
@sammyvsparks I had it in my inventory and I'm not 100% sure but there is a possible chance I did drop it. (Which I will be very salty about if so) But it's not like I can get it back that easily on another class. The closest class I have to getting to Qira is only lvl 26 since I really only play on my ranger rather than any other class.

**Comment by Moe-Ronickah** [comment]
Don't use "Q" as your drop key.  Move it to something like "Delete", instead.
