### ISSUE TITLE
resource pack not working 

### ISSUE THREAD

**Issue by Ghastlytrain71** [Wynncraft/Issues#5484]
so i had been play for a bit now and one day i got on and my resource pack is not loading so im like k i will try the things it says to fix it none of that stuff worked now im asking for help here

**Comment by osher16** [comment]
remove the server from the server list then when you add it just click on the button 
server resource packs and click until it'll be enabled

**Comment by Trixter313** [comment]
Could you list the things you've tried so far? Thanks!

**Comment by Ghastlytrain71** [comment]
removing it from my server list than adding it back worked thanks
