### ISSUE TITLE
Sound cutting out.

### ISSUE THREAD

**Issue by TimThePvpMaster** [Wynncraft/Issues#5486]
Bug: My sound cuts out for Wynncraft
How: I log into a server on wynn, everything is fine. I then have to go to a different server due to a restart, but when i log in again, I have 100% no sound. I've tried other servers, and the sound is fine there. I've also tried f3+s but to no avail.
Have you lost any items: Nope

**Comment by TimThePvpMaster** [comment]
Currently am redownloading minecraft. Hopefully this works.

**Comment by sammyvsparks** [comment]
@TimThePvpMaster I'll check to see if this happens to my game or not shortly.

**Comment by Trixter313** [comment]
Did reinstalling Minecraft help resolve your issue? Thanks!

**Comment by sammyvsparks** [comment]
Cannot confirm the issue with Wynncraft servers. both /hub and being kicked from restart did not cut out sound.

**Comment by YunoFGasai** [comment]
this is a vanilla issue that seems to happen from time to time. this happened to me too before I joined Wynn, it stopped happening at some point so I have no idea what caused it.

**Comment by TimThePvpMaster** [comment]
@Trixter313 Not a single bit. All I know if, if I use the WynnPack that wynn provides, when I log in a second time (for example I log into wc1, then choose it's too laggy so i go to wc2.) It cuts out on me when I Download the pack again. One thing i have noticed is that it started happening a bit after I toggled music back on. I am currently testing it with music off. I know it's not my computer and it's only Wynn for sure, tested it with other servers like Mineplex with it's fifty trillion worlds. It's a very odd bug i'm sure, I've never seen anything like it.

**Comment by Trixter313** [comment]
Hmm, that is very odd indeed. Have you tried deleting the resource pack from your serverresourcepacks folder and seeing if that helps at all? Maybe something got corrupted in it or something weird like that. I haven't been able to reproduce it.

**Comment by sammyvsparks** [comment]
The issue with that is (correct me if I am wrong) but the pack is defined per server. Since the lobbies are on other server instances (like a network) then I don't believe it could stay loaded. (Not 100% on this though.)

**Comment by YunoFGasai** [comment]
@sammyvsparks the pack can stay loaded in the lobby, it stays for me at least.

**Comment by TimThePvpMaster** [comment]
@Trixter313 Tried it, nothing.

**Comment by TimThePvpMaster** [comment]
It makes no sense whatsoever, I log in for the second time after a restart, redownload the pack again, and yet my sound just cuts?

**Comment by Moe-Ronickah** [comment]
@TimThePvpMaster , make sure that your java is up to date, and check to see if anything else is running that is grabbing your sound driver.  This really sounds like (haha, punny) a system error of some kind on your side.

**Comment by TimThePvpMaster** [comment]
@Moe-Ronickah Java is up to date, and I am 95% sure it's not my computer... But I bet it probably is a system error. I beleive what may actually be happening is the WynnPack is possibly to overkill for my computer, causing it to lag out. But what doesn't make sense is, the game should crash, not lose sound?

**Comment by sammyvsparks** [comment]
@TimThePvpMaster if your sound manager crashes it could possibly cause you to lose sound. The game may not always crash. Not entirely sure how the crashes work from different parts of minecraft.
Do you receive other sounds when minecraft's sound cuts out, or does all sound cease?

**Comment by TimThePvpMaster** [comment]
@sammyvsparks Yea, When my wynn sound cuts, I can go on YouTube and i'll have perfect sound.

**Comment by sammyvsparks** [comment]
@TimThePvpMaster Alright, I will look into trying to replicate the issue my side and look at possible fixes. However I don't experience it usually.

**Comment by Trixter313** [comment]
Just wondering, what version of Minecraft are you using to play Wynncraft and are you using any mod loaders or mods? That info can help us try and reproduce it. Thank you!

**Comment by Trixter313** [comment]
Ooh, and if you could post the log when it stops working, that might help give us an error message or see whats causing it. To do that, click "Edit Profile" on the launcher and change "Launcher Visibility" to "Keep the launcher open" then click "Save Profile" and launch the game. Try and get the sound to cut out then close the game and copy all of the text in the launcher to a website like http://pastebin.com/ and post the link to the log here.

**Comment by TimThePvpMaster** [comment]
@Trixter313 http://pastebin.com/raGitL8i Of course, it didn't want to work for two server changes because I was TRYING to get it to break. I use Optifine, and minecraft 1.8.9. No other mods/lag-removers. I note near the bottom it says something about the sound, however, since I am no good at coding and such, no idea what it means. Hope this helps! I'm actually going to try 1.9 real fast, see if a difference pops up.

**Comment by TimThePvpMaster** [comment]
@sammyvsparks Good luck. I don't get a lot of FPS and such, but Wynn usually works fine. If you use optifine, maybe put your render distance at max to lag your computer like mine does? (No I don't use 32 render distance that's plain stupid..) I usually lag when it happens... Other then that, no clue.

**Comment by TimThePvpMaster** [comment]
This happend with 1.9 WITHOUT optifine: http://pastebin.com/f8bvURwu Started spamming all kinds of weird junk.

**Comment by sammyvsparks** [comment]
@TimThePvpMaster Wynncraft is 1.8 based, 1.9 causes a bunch of issues with the resource pack as it changes some things.

**Comment by sammyvsparks** [comment]
@TimThePvpMaster are you using the latest Java 8 JRE?

**Comment by Trixter313** [comment]
@sammyvsparks They are using Java 8 update 25 it appears. Right now the latest version is 8 update 92 but 8 update 25 is what is bundled with Minecraft if you use the version of the launcher that doesn't require you to install Java on the system so I'd assume that update 25 is the recommended version to use with Minecraft.

**Comment by Trixter313** [comment]
With the 1.9 log I do see where it says switching to "No Sound". 
Does holding f3+t fix it?

Also, if you click Multiplayer > Wynncraft > Edit and turn the server resourcepack off, can you still get the sound to cut off?

**Comment by sammyvsparks** [comment]
@Trixter313 My sound doesnt cut but vanilla music plays over the wynn pack.

**Comment by sammyvsparks** [comment]
I am going to say I cannot help reproduce this issue. I just noticed I am not using Java 8, I am using 7. So that may change the outcome.

**Comment by TimThePvpMaster** [comment]
@sammyvsparks Just letting you know, The Vanilla music still plays for me and most people when using the Wynnpack, just turn your vanilla music off in music settings. 

@Trixter313 If I don't use the WynnPack, The sound will not cut out, the only difference that it makes to the game is 
1) Skin won't load
2) Can't use /class for some reason
3) 90% of the time I'm in 'vanish', unseen by players.

If any of those are bugs, feel free to make another thread... xD 

Also I am sorry to say I am not sure of which Java update I use. I use the one minecraft provides, and usually when I see an update I just update it without payin much attention to numbers. Also, tried f3+t to reload the pack, nothing happend. The pack reloaded, but sound did not start up. 

When I went to the log after reloading the pack, it shows this:

[23:39:27] [Client thread/INFO]: Created: 2048x2048 textures-atlas
[23:39:28] [Client thread/WARN]: Missing model for: minecraft:tall_grass#normal
[23:39:28] [Client thread/WARN]: Missing model for: minecraft:tall_grass#normal
[23:39:28] [Client thread/WARN]: Missing model for: minecraft:tall_grass#normal
[23:39:28] [Client thread/WARN]: Missing model for: minecraft:tall_grass#normal
[23:39:28] [Client thread/INFO]: [CHAT] [Debug]: Reloaded resourcepacks
**[23:39:44] [Client thread/FATAL]: Error executing task** 
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at g.a(SourceFile:46) [1.9.jar:?]
	at bcf.av(SourceFile:954) [1.9.jar:?]
	at bcf.a(SourceFile:392) [1.9.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [1.9.jar:?]
Caused by: java.lang.NullPointerException
	at bks.a(SourceFile:452) ~[1.9.jar:?]
	at fo.a(SourceFile:68) ~[1.9.jar:?]
	at fo.a(SourceFile:15) ~[1.9.jar:?]
	at fh$1.run(SourceFile:13) ~[1.9.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at g.a(SourceFile:45) ~[1.9.jar:?]
	... 3 more
[23:39:44] [Client thread/INFO]: [CHAT] [VIP+] ALEXMCDIG97 has just logged in!
[23:39:49] [Sound Library Loader/WARN]: ERROR MESSAGE:
[23:39:49] [Sound Library Loader/INFO]: SoundSystem did not load after 30 seconds.
[23:39:49] [Sound Library Loader/INFO]: Starting up SoundSystem...
[23:39:50] [Thread-19/INFO]: Switching to No Sound
[23:39:50] [Thread-19/INFO]: (Silent Mode)
[23:39:50] [Sound Library Loader/INFO]: Sound engine started
[23:39:50] [Sound Library Loader/INFO]: Sound engine started
[23:39:50] [Sound Library Loader/INFO]: Sound engine started
[23:39:50] [Sound Library Loader/INFO]: Sound engine started

**Comment by sammyvsparks** [comment]
Try using Java 7 as your default perhaps? Also do not use 1.9 with wynncraft. It breaks the game usually. Wynncraft uses 1.8 as its base jar allowing newer versions to connect with some unwanted results.

**Comment by TimThePvpMaster** [comment]
@sammyvsparks Yea, I don't like 1.9/1.10. Usually stick to the 1.8 versions, due to lag and pvp reasons.

**Comment by Moe-Ronickah** [comment]
As @YunoFGasai said originally, this is a vanilla MC error.  @TimThePvpMaster , you should read [this thread, at PlanetMinecraft](http://www.planetminecraft.com/forums/can-hear-minecraft-noises-t62846.html), and try the various fixes suggested.  Let us know if anything works for you, OK?  Good luck.

**Comment by TimThePvpMaster** [comment]
@Moe-Ronickah well.... I wish I could say those ideas worked, but they haven't. Just got some new log info, the log actually SAYS the sound system shut off, take a look: http://pastebin.com/bH2wWhii @Trixter313

**Comment by TimThePvpMaster** [comment]
Please note at the bottom it 'switching to silent mode'. From there, I have no sound. It seems like it truly is a Vanilla issue, but what is causing it? My guess is the resource pack, it's the only thing that activates it. But why the pack and nothing else?

**Comment by Moe-Ronickah** [comment]
When you say that you are downloading the rp again, are you deleting and downloading the rp, or is the game giving you a message that it's dling the rp?  I'm wondering if your rp is corrupt.  How about deleting the rp that you have, and letting the server give you a new one?

I've read the file.  I've seen Lines 154-160 before on my own pc, and I've been through a dozen attempts to fix it.  Yours is being a bit more stubborn.

**Comment by TimThePvpMaster** [comment]
@Moe-Ronickah Done that about twenty times, to no avail. Basically I am currently just spamming f3+s till it turns back on, and usually it does. Really I don't think there is anything else we can do.

**Comment by EricSalata** [comment]
Have you tried, deleting and reinstalling your sound drive? I had a driver stop working that disabled s ton of things if you delete it and reinstall it, it might update and fix itself.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
