### ISSUE TITLE
Didn't get VIP+

### ISSUE THREAD

**Issue by TurtleWurtle** [Wynncraft/Issues#5492]
Hi, my IGN is TurtleWurtle. I am currently VIP on the Wynncraft server and I purchased VIP+ using paypal yesterday, but I never received my rank. I sent an email to support@wynncraft.com with my IGN, transaction ID, and a description of my problem but I haven't gotten a response. I was wondering how long it takes to get a response and if it's abnormal that I haven't gotten one yet?

Thanks c:

EDIT: to make it more clear, I **did** get a response saying that my support ticket was opened, but nothing since then.

**Comment by sammyvsparks** [comment]
@TurtleWurtle Was your issue resolved? It can take 3-5 days after the initial email. Varies on who is available and when. Just wait it out and they will get to you :)

**Comment by Moe-Ronickah** [comment]
@sammyvsparks , you can pretty much bet that it was, as turtle closed the issue.
