### ISSUE TITLE
Stoneslab Weapons?!?!

### ISSUE THREAD

**Issue by ItsStryder** [Wynncraft/Issues#5497]
Some weapons, such as the "Knight's Toothbrush" are not sticks, they are stonebrick slabs.
![2016-07-15_19 03 28](https://cloud.githubusercontent.com/assets/16769338/16892157/e2b791f6-4abe-11e6-9abf-13ecb395dd54.png)

**Comment by sammyvsparks** [comment]
@ItsStryder What version of minecraft are you running the game with?

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

Please direct any future comments to the original thread. Thanks!
