### ISSUE TITLE
Blinked (Teleport Skill) into a tree.

### ISSUE THREAD

**Issue by ZestPlayz** [Wynncraft/Issues#5499]
I accidently blinked into a tree, can anybody help me?

im currently trapped in the tree.

**Comment by YunoFGasai** [comment]
please post you cords and then use /kill if you have more than 3 soulpoints.

**Comment by XavierEXE** [comment]
You could also try using a teleportation scroll if you have one with you, or just spamming /class a few times, as every time you log in your Y coordinate will rise by 1.

**Comment by ZestPlayz** [comment]
ok
