### ISSUE TITLE
Falling into the Void

### ISSUE THREAD

**Issue by IncBear101** [Wynncraft/Issues#5502]
Um... What? I was looking for a DXP, then when I joined server six, this happened:
![2016-07-16_14 30 05](https://cloud.githubusercontent.com/assets/20328015/16897011/f348a4c6-4b61-11e6-9868-26eb607aa81a.png)

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out.

**Comment by IncBear101** [comment]
Shouldn't someone look into it?

**Comment by Trixter313** [comment]
Void issues happen pretty often but luckily are usually really easy to fix. It's kinda just random with logging in and with all of the issues we get of people stuck, the devs probably know of the issue but either haven't tried fixing it yet or can't find the issue/how to fix it.

**Comment by Moe-Ronickah** [comment]
"falling into void" brings up 25 issues.  It's old.  It's well-known.  The devs are working on it, when time permits.

**Comment by IncBear101** [comment]
Very poetic.
