### ISSUE TITLE
Glitch Teleportation Quest [Flight In Distress]

### ISSUE THREAD

**Issue by NicholasID** [Wynncraft/Issues#5503]
After defeating the Queen i got the jewels and went to the teleportation thing, and it went me to a box and i dont get teleported back to the ship. Cuz of this i can't finish my quest because i have to find the right airship to talk to the captain.

**Comment by XavierEXE** [comment]
Try switching servers, the tripwire to teleport you is broken on some worlds, I know it's broken on wc14 currently.

**Comment by NicholasID** [comment]
I did /kill and i have to restart the quest again. Now i cant get to the teleportation thing again

**Comment by YunoFGasai** [comment]
if you killed yourself you have to walk through the entire quest again, I'd suggest opening the wiki or a youtube tutorial so it will be easier to follow
