### ISSUE TITLE
Resource Pack not working on a Mac

### ISSUE THREAD

**Issue by hackssss** [Wynncraft/Issues#5507]
Whenever I log in, it says that it downloaded the resource pack. yet it isnt working.
please help.
important notes: Im using optifine 1.8.0
i have a mac 10.6

**Comment by Trixter313** [comment]
Try using 1.8.9, does the issue still occur?

**Comment by hackssss** [comment]
yes. it does.

**Comment by sammyvsparks** [comment]
hackssss, try resetting the local resource pack? You can do that by locating your minecraft directory and going to *Server Resource Packs* (I believe it is that, or something similar) and deleting either all or just the Wynncraft Resource Pack from there.

**Comment by hackssss** [comment]
Done that before. didn't work.

**Comment by Ghastlytrain71** [comment]
remove the sever from your server list and add it back it happen to me too

**Comment by hackssss** [comment]
did that, didnt work.

**Comment by Moe-Ronickah** [comment]
Update to the latest launcher, update your os to the latest that your machine will handle.

**Comment by Moe-Ronickah** [comment]
If your resource pack extension is blank, and it's smaller than 2MB, change it to .zip.  If it's greater than 3MB, zip it.

**Comment by hackssss** [comment]
nothing works.
im finished, salted isnt taking any preparations to make it compatible with certain updates.

**Comment by sammyvsparks** [comment]
@hackssss It is already compatible. I know several mac users who have no problems since the pack was released. Its a issue your side, not with the pack itself.

**Comment by hackssss** [comment]
I meant with **actual computer updates.** not on the game's side, but the computer's side.

**Comment by sammyvsparks** [comment]
The resource pack is handled gameside, salted made the pack compatible with all systems. It just depends on how your system can handle and run it effectively. Which is nothing he can control.

**Comment by Moe-Ronickah** [comment]
@hackssss , what updates are you referring to?

**Comment by ColinRioux** [comment]
@hackssss, if you are still having this issue, could you be more specific? 

Thanks.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
