### ISSUE TITLE
The Hunger of Gerts, Part 1, text mistake

### ISSUE THREAD

**Issue by ryanmac1** [Wynncraft/Issues#5508]
Hello, my name is Ryanmac1 and I recently discovered a dialogue mistake in the quest "The Hunger of Gerts, Part 1". I already posted this issue on the forums. And Ackro said he has fixed the issue, (see forum page yourself) https://forums.wynncraft.com/threads/dont-know-if-this-was-intentional.138647/#post-1539369 . I recently when back to the area and the mistake was still present. Im posting it here to hopefully get more attention. 
![2016-07-17_12 32 28](https://cloud.githubusercontent.com/assets/10858372/16901852/0f008a38-4c1d-11e6-8c8a-074b6885adc1.png)

The original forum post and screenshot was taken two days ago. I don't know if something like this takes time to fix itself, but just in case i'm posting it here to make sure that its seen.

If I find anymore bugs or problem in the future ill post them, ill try to help bit by bit to make Wynncraft problem free (which will take awhile).

**Comment by YunoFGasai** [comment]
if ackro said it's fixed it's fixed.
when we fix stuff we do it on the build server  so you won't see it until the next map push.
