### ISSUE TITLE
Green Powder IV Relic Not Dropping

### ISSUE THREAD

**Issue by setery10** [Wynncraft/Issues#5509]
I did what I was supposed to do and I don't see any powders.
![2016-07-17_17 17 33](https://cloud.githubusercontent.com/assets/8347065/16903132/efd1bfbc-4c42-11e6-9a0c-91708a93b76f.png)
![2016-07-17_17 17 43](https://cloud.githubusercontent.com/assets/8347065/16903131/efd0ea56-4c42-11e6-9d3a-45d6d2beea6d.png)

**Comment by YunoFGasai** [comment]
all powders except red 1 red 2 green 1 green 2 blue 1 blue 2 are disabled until the next update.
