### ISSUE TITLE
The Angry Village not given promised emeralds

### ISSUE THREAD

**Issue by DCM627** [Wynncraft/Issues#5511]
![2016-07-17_21 17 43](https://cloud.githubusercontent.com/assets/19480434/16904441/788be92e-4c64-11e6-8b29-e12b5d7bd6f5.png)
So, the guy says he has emeralds, but the chat doesn't cooperate with him. It looks in my inventory like I did gain a few emeralds, though I cannot be certain. I feel stingy reporting this.

**Comment by sammyvsparks** [comment]
@DCM627 This quest does not give emeralds as a reward, perhaps you picked them up from monsters?

**Comment by DCM627** [comment]
No, in 2/4 of the chat, he says he has emeralds to pay me back though.

**Comment by Moe-Ronickah** [comment]
But he doesn't.  You get XP and the Corrupted Potato, that's all.  Villagers aren't always truthful.

**Comment by Trixter313** [comment]
The potato probably distracted them and they forgot to give you the emeralds.

**Comment by DCM627** [comment]
I don't have any other class to test it on, but I'm 99.9% certain I got some emeralds from the quest. I didn't take screenshots because I didn't expect this to happen to me...
