### ISSUE TITLE
My Stuff disappeared 

### ISSUE THREAD

**Issue by TheGamingBunny** [Wynncraft/Issues#5512]
I don't know why but when my soul points depleted all my stuff was deleted, i do not know if this was on my end or if a server wipe happened right as i died, i'm upset that this happened and wish you can get back to me as soon as possible.

**Comment by sammyvsparks** [comment]
@TheGamingBunny Depending where you died with <2 Soul Points the chunk(s) may of unloaded and to reduce lag Wynncraft automatically clears items when the chunk unloads. However they have a strict No-Refund Policy for lost items obtained in-game. Sorry for any inconveniences it may cause for you.

**Comment by TheGamingBunny** [comment]
thank you for clearing that up for me.
