### ISSUE TITLE
I'm stuck in a one block area underground near Karoc Quarry please help it's dark

### ISSUE THREAD

**Issue by Manglonaboy** [Wynncraft/Issues#5513]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

**Comment by Manglonaboy** [comment]
Can a staff person get online and teleport me out

**Comment by Manglonaboy** [comment]
![2016-07-17_19 21 22](https://cloud.githubusercontent.com/assets/20508264/16904978/1c494676-4c54-11e6-890e-bb44e730d42a.png)

**Comment by sammyvsparks** [comment]
@Manglonaboy Please use /kill or a teleport scroll when you get stuck in a hole like that with +3 Soul Points. But if you are still stuck please post your cords so that area could possibly be fixed to prevent this in the future.

**Comment by Manglonaboy** [comment]
Thank you my scrolls weren't working so I thought that I was doomed XD Thank you so much
