### ISSUE TITLE
Boats and Horse Transportation Glitch

### ISSUE THREAD

**Issue by MrSanfrinsisco** [Wynncraft/Issues#5514]
Hello, I have been having a problem recently with horses and boats, or really any transportation that I have to ride where I guess what happens is my character stops moving? Like I don't stop moving but the music stops and so does my character, the best way I can explain this. I'm going into detlas, music stops so I think it's just the music switching, I'm in detlas on my horse and all of a sudden i'm being hurt. I hit shift and then I teleport all the way back outside of detlas because I was glitched back. Hopefully that makes sense but it's really annoying and makes it difficult for me

**Comment by YunoFGasai** [comment]
try using minecraft version 1.8.9

**Comment by ende124** [comment]
Yeah, using version 1.8.9 solve dthe problem for me, I didn't even know Wynncraft supported 1.8.9. I think WYnncraft should uppgrade to 1.10 so we can use the new boats wich is much better than the old ones.

**Comment by Moe-Ronickah** [comment]
If you are using any version of MC above 1.8.9, we suggest that you revert to 1.8.9. There are severe problems with horses and boats in newer issues of MC and Wynncraft is 1.8.9 compliant.

There is somewhere around 200+ reports of this, so I'm not going to specify any one issue report.
