### ISSUE TITLE
problem with relics

### ISSUE THREAD

**Issue by ljthekiller1** [Wynncraft/Issues#5516]
I have been at the Boot relic for the past hour trying to obtain the boots and I have gone to different servers and still couldn't retrieve them

**Comment by sammyvsparks** [comment]
@ljthekiller1 Did you get it prior to that recently or fail to obtain it (it can give you another item).

**Comment by YunoFGasai** [comment]
try standing in the crystal and hitting it, the last update fucked them up a bit.

**Comment by ljthekiller1** [comment]
Yuno that worked I had to hit it like 10 times with out stoping

**Comment by YunoFGasai** [comment]
glad to know that worked for you! 
have fun playing Wynn!
