### ISSUE TITLE
Teleport Glitch

### ISSUE THREAD

**Issue by justice1000** [Wynncraft/Issues#5517]
I used the Teleport Spell for Mages inside the WynnExcavation Site A next to some stairs and I got stuck inside them, there are no mobs there to kill me, and the scrolls to go to cities aren't working.

Screenshot of where I am:
![2016-07-17_23 08 35](https://cloud.githubusercontent.com/assets/20510932/16929127/13747790-4ceb-11e6-9c9c-6d09c6db5166.png)

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out.
