### ISSUE TITLE
Two shouts did not work.

### ISSUE THREAD

**Issue by SliceThePi** [Wynncraft/Issues#5520]
![2016-07-19_07 42 36](https://cloud.githubusercontent.com/assets/11011773/16950224/d2236964-4d84-11e6-8051-94f674640aed.png)
![2016-07-19_07 36 57](https://cloud.githubusercontent.com/assets/11011773/16950225/d2249424-4d84-11e6-9cea-638387bd089c.png)

If it matters, I used /use to get to the menu.

Also: Am I able to get my two shouts back? My IGN is SliceThePi.

**Comment by SliceThePi** [comment]
I was originally on WC7 with the first one, then on WC5 with the second. The screenshots are out of order, the one with me chatting was on WC7.

**Comment by sammyvsparks** [comment]
@SliceThePi Try contacting support@wynncraft.com regarding those issues. That would be the fastest way to get them resolved.

**Comment by Moe-Ronickah** [comment]
It's actually the only way to properly go about it.
