### ISSUE TITLE
Not able to join Wynncraft servers

### ISSUE THREAD

**Issue by Derysed** [Wynncraft/Issues#5521]
So... 2 days ago i was playing on wynncraft as i usually do... after i took a break and went to play on cs:go i returned on minecraft and i couldn't enter wynncraft anymore... plz help i tried everything but i still can't get in... i miss wynncraft so much even if i didn't play it for only 2 days

**Comment by sammyvsparks** [comment]
@Derysed can you give more detail? What does the server do/say? Does it show offline or not let you connect?

**Comment by Derysed** [comment]
ok it just says can't connect to server and i don't know why cause i was playing normally before... when i try and go in the server it give me an internal exception

**Comment by Moe-Ronickah** [comment]
Duplicate of #4552.  Please read the comments on that issue for further assistance.
