### ISSUE TITLE
/fixquests WynnExcavation

### ISSUE THREAD

**Issue by PixlCraftr** [Wynncraft/Issues#5522]
When I do /fixquests, there is a bug, so that i always get 2 Purple Crystal Shards (if I don't have them in my inventory but in my chest), despite I finished WynnExcavation Site A, B and C.

I hope you understand my problem, english is not my prime language.
If you have questions, just ask.

**Comment by sammyvsparks** [comment]
That is a known issue that will be fixed eventually.

**Comment by ende124** [comment]
Thanks, now I have 8 of those

**Comment by ende124** [comment]
Found an easy way to get rid o tehm :P

**Comment by sammyvsparks** [comment]
Just fill up your inventory with emeralds and switch it out with a item then drop it. That will allow you to delete duplicate quest items.
