### ISSUE TITLE
The Hunger of Gerts Part II (and likely other related quests) Teleport Glitch

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#5524]
In some areas of the game, there's some form of detection to prevent you getting in somewhere; it teleports you out of aforementioned "somewhere" and to where you were last before you tried getting into that somewhere.

When about to complete The Hunger of Gerts Part II, I looked around for Double XP to boost my rewards, and took off the Gert Mask to put on my Speaker, for additional experience.

Upon exchanging the mask with the Speaker, I was teleported back to the spawn, where you start the game. I believe this has something to do with my not having been anywhere outside the detected area in the current session before I stopped satisfying the requirements for being in the zone, thus teleporting me to some kind of "fallback" teleport.

Maybe some kind of set fallback for each area (though tedious) can be useful. Or maybe just to the nearest town.

**Comment by YunoFGasai** [comment]
this is a known issue, when you die you get teleported to the nearest spawn point, because most quests are off map you get teleported to the initial spawn.
this is on the to fix list.
