### ISSUE TITLE
Teleported to redstone mechanics

### ISSUE THREAD

**Issue by smirlianos** [Wynncraft/Issues#5525]
_(Searched for a duplicate, nothing found)_

I tried teleporting with "teleportation spell" while doing the parkour in spider dungeon, and I was teleported to a room full of redstone. 

Here is a video of it:
[video-1469006940.zip](https://github.com/Wynncraft/Issues/files/373531/video-1469006940.zip)

**Comment by YunoFGasai** [comment]
use /kill if you have more that 3 soulpoints
