### ISSUE TITLE
Un-reachable chest in Dernel Jungle

### ISSUE THREAD

**Issue by LabyrinthMaster** [Wynncraft/Issues#5526]
Dear staff,
I've found a level 3-4 chest in the Dernel Jungle but I am unable to reach it due to the height limit.
Screenshot of location with coordinates : 
https://imagizer.imageshack.us/v2/1377x775q90/922/u6ZaIc.png

Cordialement,
-Lab.

**Comment by Moe-Ronickah** [comment]
Oops..  Thanks for telling us about it.  We'll pass the information along to a builder to get it fixed.

**Comment by Villageacules** [comment]
Chest relocated to reachable area close to original location, thanks for that.
