### ISSUE TITLE
I have a problem on wynncraft

### ISSUE THREAD

**Issue by ByShaDowsGame** [Wynncraft/Issues#5528]
Hello, I am french my English should be Approximate Do ridge are not careful.
Here I have a poblème soon as I connect 1 second after it makes me crash my Minecraft

I'm no mod  and version 1.9.4 .

thank you in advance

By_ShaDows future geek on wynncraft :)

**Comment by ByShaDowsGame** [comment]
Can you help me plz i realy want to play at wynncraft.

**Comment by YunoFGasai** [comment]
try using 1.8.9
