### ISSUE TITLE
Problem with Quest "Headless Hunt"

### ISSUE THREAD

**Issue by PixlCraftr** [Wynncraft/Issues#5532]
(This Thread may contain Spoilers!)

After I got to the cave under the castle, the dialogue with "saaaaaaveeee uuuusssss" or so was triggered and the quest book updated to "Return the Lost Soul of Referick to its owner."
When I got back to Referick, he just said "Have you investigated the Mansion yet?..."
Apparently here was something skipped because at the beginning of the quest he couldn't talk.
Even when I try to enter the mansion I get kicked out because my quest book isn't updated yet.

All in all, I can't progress with the quest. Can someone reset it or so?

**Comment by Moe-Ronickah** [comment]
Take a look at the [Wiki](https://wiki.wynncraft.com/index.php?title=Main_Page) and see if there is anything that you have missed.

**Comment by PixlCraftr** [comment]
https://wiki.wynncraft.com/index.php?title=The_Headless_Hunt

the whole dialogue in stage 3 was skipped

**Comment by XavierEXE** [comment]
Did you bring the item that represents Referick's soul that the mob in that prison-like area drops back to Referick?

**Comment by PixlCraftr** [comment]
i thought i have it, but it seems like i didnt. its working now, but there is still the bug, that referick can speak and tells me to go to the mansion, even when i didnt bring him his soul

**Comment by Moe-Ronickah** [comment]
So, the real issue is that Referick will speak to you, even though you don't have the item that should be necessary in order to trigger him to speak again?
