### ISSUE TITLE
Hole to void in lava at Rodoroc

### ISSUE THREAD

**Issue by CharlieDowns** [Wynncraft/Issues#5533]
Hello, I want to report a mistake where a hole to the void exists in Rodoroc.
This hole lies 1 block near a 'glowstone' in the lava pit nearest to the 'Item Buyer\'s'.

For reference:
![2016-07-21_00 39 54](https://cloud.githubusercontent.com/assets/19643543/17005814/953df2ae-4edc-11e6-8100-c650bd8c4167.png)

**Comment by Moe-Ronickah** [comment]
@YunoFGasai, here's an interesting hole for your thread.

**Comment by YunoFGasai** [comment]
added to fixing thread

**Comment by Moe-Ronickah** [comment]
Thank you, kind sir!

**Comment by IGotBeef** [comment]
OMFG im pretty sure i fell through that. I was riding on my horse and then the world wasnt loading so i got off the horse and got glitched out of the world and i lost all my stuff so PLEASE could a staff member reset my invent by about half an hour from when im posting this. I lost a full set of champion armour and a maelstrom bow and a 40/40 white horse and a few other things so in total i lost about 3 stacks of LE... PLEASE HELP

**Comment by YunoFGasai** [comment]
@IGotBeef please create a new issue

**Comment by Villageacules** [comment]
Fixed, thanks for that.

**Comment by DebugingLonks** [comment]
@IGotBeef fam what. ur just making stuff up know xD dying in the void can't remove all your items unless ur at 1SP, and even so, you would havea horse
