### ISSUE TITLE
'Dwarven Soldier' at Molten Peaks dropping their gear on death

### ISSUE THREAD

**Issue by CharlieDowns** [Wynncraft/Issues#5534]
Hello, I want to report a issue of the level 90 'Dwarven Soldier' mob 'randomly' dropping its gear on death.
The drops do not become pick-upable, neither do they disappear, but the mobs do stop dropping more after a certain amount of drops.

I use Minecraft client version 1.10.2, but this has been tested to also happen in client version 1.8.9.

For reference:
![2016-07-21_01 10 53](https://cloud.githubusercontent.com/assets/19643543/17006297/07745e50-4ee0-11e6-8cf6-6ce9ee2a241e.png)

**Comment by sammyvsparks** [comment]
What is the gear name? Also is it an actual item or a vanilla item?

**Comment by CharlieDowns** [comment]
Probably Vanilla, but as I explain, I am not able to pick-up the drop.

**Comment by Moe-Ronickah** [comment]
There are several mobs that do this.  It's not really a problem, it's really a prank by the GMs.
