### ISSUE TITLE
Floating loot chest in Qira's Hive

### ISSUE THREAD

**Issue by CharlieDowns** [Wynncraft/Issues#5536]
Hello, I want to report a issue of a loot chest floating high in the sky in Qira's Hive, 'seeming' impossible to loot.

For reference:

![2016-07-21_03 28 17](https://cloud.githubusercontent.com/assets/19643543/17008644/69c04228-4ef3-11e6-8d94-faf892c65cec.png)

**Comment by Moe-Ronickah** [comment]
I'll have to ask about this one.  Thanks, Charlie.

**Comment by AckroWynn** [comment]
I simply cannot find it on our GM server, so I will assume it has been fixed.

**Comment by Moe-Ronickah** [comment]
Thank you, Ackro.  Closing  - it'll show up when the next game map update gets pushed to live.
