### ISSUE TITLE
Resource pack bug

### ISSUE THREAD

**Issue by setrador** [Wynncraft/Issues#5538]
Game wynncraft the years, but today for the first time my resource pack did not work. I tried to uninstall and reinstall minecraft. Updated the java. I authorized server texture. And I did not work, I would like you to help me with this? Could pass me download the resource pack?

**Comment by Moe-Ronickah** [comment]
There are two copies of it on our front page, with instructions on how to download it.  Let me know if you still are having trouble.

**Comment by setrador** [comment]
Thx, i resolve the problem !
