### ISSUE TITLE
Fell out the world and lost all my items PLEASE HELP

### ISSUE THREAD

**Issue by IGotBeef** [Wynncraft/Issues#5542]
PLEASE HELP ME STAFF!
Basically i was riding my 40/40 white horse in Rodoroc and the world stopped loading so i got off my horse (usually when i do this i get glitched back about 10 seconds) but this time i got lagged out of the world (someone has already mentioned that there is a whole in the ground that goes into the void) so i ended up losing all of my items (my 40/40 white horse, Maelstrom bow and champion armour as well as some other stuff) so please could you reset my invent by about an hour from when i posted this or just give me the items back please. My stuff was worth about 3 stacks of LE and now i have nothing. Im a level 88 archer and i really enjoy playing wynncraft but i cant play until i get my items back so PLEASE HELP i would really appreciate it. Thanks for reading :D
-IGN: IGotBeef

**Comment by IGotBeef** [comment]
I'm not 100% sure but I think it was more than 2 so I shouldn't have lost my stuff even if I died.

**Comment by sammyvsparks** [comment]
I've fallen into the void like that. Sounds like you had less than 3 soul points because I just slowly fell to my death and respawned.

**Comment by IGotBeef** [comment]
Yeah i really hope i get my items back but WynnCraft don't usually let you :( even though it was not at all my fault and i lost everything :'( Also i was using minecraft 1.10 so that probably explains the horse glitch i guess? So is there any chance i could get my items back please?? Also the servers have all just crashed idk if that has anything to do with it?

**Comment by sammyvsparks** [comment]
Sadly You most likely won't. For the future use 1.8.9 And watch your soul points.

**Comment by IGotBeef** [comment]
Unfortunately I probably won't keep playing if I don't get my items back. Not cause I'm really salty but it's just gunna be too hard to get my stuff back because I have no spare armour or emeralds so I'd just be a level 90 stuck in ragni...

**Comment by sammyvsparks** [comment]
Try asking around detlas and maybe use armor off another class temp.

**Comment by Moe-Ronickah** [comment]
@IGotBeef , whether or not you choose to keep playing or quit, whether you choose to ask for help in Detlas or anywhere else, whether or not you choose to start a new class, is only up to you.  You aren't alone in being upset, but remember, WynnCraft is built on top of MC, and glitches do happen, even in vanilla MC without plugins.  Many of us have lost items, even an entire class, however, we keep on playing, because we enjoy the game and the community.

I'm sorry, but unless there is a server-wide rollback, there is no way that you will get your items back from WynnCraft.  We don't have the power to do it, and neither do the mods, and the admins won't do it because they are too busy.

I hope that you change your mind and stay.  Good luck, with whatever you choose to do.

**Comment by IGotBeef** [comment]
I'm fine losing my bow and armour I just really want my white horse back cause they are worthopaedic so much and so hard to aquire. Also I dont know why but after I glitched and died I respawned with 3 starting bows and I kept my leggings. They are the static charged ones from qira hive so maybe they are soul bound or something...

**Comment by IGotBeef** [comment]
I meant to say worth but it autocorrected to worthopaedic...

**Comment by Moe-Ronickah** [comment]
I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency.  There is nothing we can do about your horse.  The three starting bows actually mean that you died three times, not just once.  It may be the crash severed your connection, but the server saw you as still alive in-game.  In which case, the mobs killed you multiple times, even though you didn't see it happen from your perspective.

**Comment by IGotBeef** [comment]
Yeah I kinda understand that cause for all you know I could be lying I guess. Anyway I'm an archer so I don't really need to horse but it just sucks that I paid 2 stacks of le to get it and I lost it to a glitch... I just need to get hold of a bow so please let me know if anyone has an Az or something?

**Comment by YunoFGasai** [comment]
@IGotBeef I got a spare earthsky equonix if it fits your build

**Comment by IGotBeef** [comment]
Thanks for the offer but I'm only level 88 so I can't use it... But anot archer build for my level would be really helpful if anyone knows 1. I'm using a maelstrom bow atm (I bought 1) and I found a return to ether today so I can use that next level. I also bought a new set of champion armour so I'm using that atm so let me know what u reccomend

**Comment by DebugingLonks** [comment]
@IGotBeef So first your lvl 90, then 88 xD.

Also, whats the chance you were lagging SO BAD that you fell of sky islands from rodoroc on this horse? (I doubt it happened but it could...)
