### ISSUE TITLE
Tower of Ascension a level 2 stage 10

### ISSUE THREAD

**Issue by tomkouwenb** [Wynncraft/Issues#5543]
When im doing Tower of Ascension level 2 stage 10 and i fight the boss there are a few weird buggs:
the first one is that the boss sometimes glitches into the wall so i cant hit or kill him

the second one is that when he doesnt glitch into the wall and i kill him he doesnt drop anything so i cannot complete the level and im forever stuck or i have to kill my self 

i hope im getting any response

**Comment by Moe-Ronickah** [comment]
@tomkouwenb , is the boss actively moving into the wall, or is it happening when you attack?  If it's happening when you attack, what class are you playing, and what attack are you using?

**Comment by sammyvsparks** [comment]
@Moe-Ronickah Its usually warrior/knight using uppercut or when he charges near a wall. I've experienced that myself.

**Comment by Moe-Ronickah** [comment]
I know what it usually is.  What I want to know is what is happening, now, to @tomkouwenb.

**Comment by sammyvsparks** [comment]
Alright

You can edit this out if you want, but is there a place I can contact you out of here? Wanted to ask a few questions and I am not sure if your forum name matches here.

**Comment by Moe-Ronickah** [comment]
My forum name is Moe_Ronickah.  Apparently, when I tried to make my account, many eons ago, GitHub didn't like "_", so I had to use "-".  Glad to answer anything that I can.

**Comment by sammyvsparks** [comment]
Alright, thank you :smile:

**Comment by tomkouwenb** [comment]
im archer and it doesnt matter if i do it with a basic attack or spell he just glitches into the wall and does nothing.
 
ive try'd it around 7 or 8 times.

**Comment by sammyvsparks** [comment]
@tomkouwenb try to keep him away from walls and do not attack when he is near a wall so he has a far less chance of getting stuck somehow.

**Comment by tomkouwenb** [comment]
i tryd that but he still doesnt drop anything

**Comment by sammyvsparks** [comment]
are you doing it alone or with multiple people?

**Comment by tomkouwenb** [comment]
alone

**Comment by sammyvsparks** [comment]
want me to try to help you get the shard real quick?

**Comment by tomkouwenb** [comment]
uuhm yeah sure

**Comment by sammyvsparks** [comment]
which server?

**Comment by tomkouwenb** [comment]
11

**Comment by Moe-Ronickah** [comment]
We still need to understand what is going on with this issue and if this is a general bug that is now happening..

**Comment by sammyvsparks** [comment]
@Moe-Ronickah It dropped first try several times, I think the shards burned in fire for him actually. That floor has the fire and turrets on it.

**Comment by Moe-Ronickah** [comment]
@sammyvsparks , please see tomkouwenb's second comment.  This is why this issue remains open.

**Comment by legoman72** [comment]
This also happened to me when fighting the guardian, chained beast and in the Qira give during general floors(I haven't gotten up to a boss one yet though), when you kill the mob you also can't get its drop resulting in you having to kill a boss again

**Comment by Moe-Ronickah** [comment]
RESOLVED
