### ISSUE TITLE
Lost items due to server crash

### ISSUE THREAD

**Issue by CelloEnthsiast** [Wynncraft/Issues#5544]
Hi, I just recently finished the Tower of Ascension quest and took the unidentified armor to Detlas to get it identified, including a few other helmets. During the identification, the server lagged out and I could not retrieve my armor from the identifier. This was around 1:30 pm MST today and when I returned back to the server all of the items I identified and the emerald blocks used to identify the armor were not there. Is there any way to get the armor back or the emeralds used to identify it, considering it only is obtainable from the npc or trade market (I don't feel like spending more emeralds on it).

**Comment by Moe-Ronickah** [comment]
I was in-game when the servers crashed.  I'm sorry, but unless there is a server-wide rollback, there is no way that you will get your items back from WynnCraft. We don't have the power to do it, and neither do the mods, and the admins won't do it because they are too busy.

**Comment by C0meGetS00me** [comment]
I can give you champion armor

**Comment by ralamus** [comment]
my items is gon there sever chase

**Comment by sammyvsparks** [comment]
Ralamus, Please make a new issue if something occurred to you.

**Comment by Yaendhal** [comment]
dude, i was dividing 36 LE when the server crashed, lost 18 ....
