### ISSUE TITLE
Horse Glitch

### ISSUE THREAD

**Issue by DabitoD** [Wynncraft/Issues#5545]
I spent 30 LE on getting a white horse and ended up with 2 chestnut horses BUT i  noticed that when i breed 2 brown horses and get a black that a firework was summoned, When i breeded by 2 chestnut horses i got a firework and recieved a black.

**Comment by sammyvsparks** [comment]
Horse breeding can fail, return the same or upgrade your horse

**Comment by Moe-Ronickah** [comment]
This isn't a glitch.  Any time that you breed horses, a firework is set off.  It's an intentional game mechanic.

**Comment by sammyvsparks** [comment]
@Moe-Ronickah Isnt it only when you get a successful breeding?
