### ISSUE TITLE
Jungle Fever - Emerald Golems

### ISSUE THREAD

**Issue by Chri630** [Wynncraft/Issues#5546]
I'd like to ask why the emerald Golems at the last part of the quest so hard. I even got help from a high level mage and we both died trying to complete the quest. I feel like these Golems are way too op and if they won't be nerfed I think the quest difficulty should be changed.

**Comment by sammyvsparks** [comment]
They are ment to be hard. I can try to help later if you want. Its that quest that you gotta get lucky

**Comment by Villageacules** [comment]
Salted has already given me permission to handle these types of situations, do you feel as the mob fighting experience would be better if they were nerfed?
I'll go check out and investigate these mobs and give my opinion.

**Comment by Chri630** [comment]
If anything I believe their speed should be reduced because I simply cannot outrun them with my mage. Back when I did this quest with my Archer months before it was not as difficult. I actually remember being able to kill them but not they are way too overpowered.

**Comment by Moe-Ronickah** [comment]
@Chri630 , I'd like to know several things from you: What armor are you using and what are the stats on the armor?  Some armor has speed reduction and some armor reduces your stats.  What weapon are you using?  Is it as high a level as your class is, or is too low to be effective against higher-level mobs?  What are your skill point stats?  Where do you have your skill points set at?

**Comment by sammyvsparks** [comment]
@Villageacules Honestly I don't think they should be nerfed. They are guarding a bank vault. They should be strong. I was able to do that even after it took a few tries when I just reached the level for the quest. Just takes time.

**Comment by YunoFGasai** [comment]
I did the quest recently too and found it impossible to do that part of the quest, I had to get my main in the vault to open the door for my lower mage.

**Comment by Chri630** [comment]
Well question if they cant be nerfed, why were they buffed in the first place? As I said before it was much easier to do on my archer months before and that was just around when gavel came out.

**Comment by sammyvsparks** [comment]
Archer has speed. It helps drastically with avoiding.

**Comment by Chri630** [comment]
Still tho, anyways I somehow managed to finish it but it took me a few days so I'll be closing this thread. Thanks for all the help.

**Comment by YunoFGasai** [comment]
archer can run past the golems, mage can teleport through half wall and thus avoiding them completely, assassin vanishes all the way and warriors tank it/charge
