### ISSUE TITLE
The Qira hive - MAJOR Bug

### ISSUE THREAD

**Issue by TimThePvpMaster** [Wynncraft/Issues#5547]
![2016-07-21_21 08 20](https://cloud.githubusercontent.com/assets/16787176/17043721/8bad09ae-4f87-11e6-89a3-44d64a443831.png)

So this able happens. I submitted The Qira Hive, with normal double xp and I also had 74% xp bonus. But what? A month ago when I submitted it, I went from level 80 to 88, what happened? Can someone please fix/explain this bug? Happened to me again when I did Tower of Ascension the other day as well, No clue why. I should have gotten 4 levels, but I only ranked up once? Dude.. I'm really ticked. I've been trying to do Qira all day to rankup so I can use my Guardian, but apparently, Wynn doesn't want me too? @SaltedSalmon @Jumla @Trixter313

**Comment by C0meGetS00me** [comment]
im his friend

**Comment by sammyvsparks** [comment]
Dont tag admins unless needed first of all.
Secondly, Your level may determine how much you get.  Higher levels need a lot more xp then lower.

**Comment by C0meGetS00me** [comment]
-.- ure blind? He wrote "A month ago when I submitted it, I went from level 80 to 88, what happened?" And he was 80lvl now, and went to 81..

**Comment by sammyvsparks** [comment]
The level system may of changed, but 1mil xp is not a lot

**Comment by C0meGetS00me** [comment]
yes, when i got from 72 to 80 just by wynn site d which gives 600kxp on dxp and some xp gear

**Comment by TimThePvpMaster** [comment]
It was submitted Double xp, and with good xp gear... If you look it up, Level 80-81 only requires about 750k xp, while qira gives 1 million. Submitted with double xp, along with good xp gear, shouldn't rank me so little.

**Comment by sammyvsparks** [comment]
Minus next level does not equal higher then 1

**Comment by Moe-Ronickah** [comment]
@C0meGetS00me .  "-.- ure blind?"  Please, do not insult anyone here.  Everyone here is a volunteer and trying to help.  People make mistakes.

@TimThePvpMaster , I really wish that you had proof that you went from Lv80-88 with only the Hive quest being completed.  As it stands, the known xp of 1 000 000 for the Hive, at double xp, explains your level gain in the screen cap, submitted, above.  The next time that you do a mission for XP, please check your xp reward against what was promised.  If it's far off, screen cap and let us know.
