### ISSUE TITLE
/Toggle blood is 90% useless

### ISSUE THREAD

**Issue by DaNarwhalChannel** [Wynncraft/Issues#5551]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.
Title says it all. When using a spell, such as arrow storm, bomb arrow, war scream, even with blood toggled off, it still spews a ridiculous amount of blood outwards, and this severely lags and irks me. When I duel as a warrior, if I just hit them ONCE with particles and minimal, everything off, with optifine, and blood off, it summons the particles of 6 redstone blocks breaking at once. Is there any way to fix this?

**Comment by Moe-Ronickah** [comment]
#4753 May be back.  It's needs to be tested on multiple servers.

**Comment by Moe-Ronickah** [comment]
It's working fine, for me, right now.  "/toggle blood" turns blood off and on.
