### ISSUE TITLE
"Equipment" not "equiptment" in "Out Of My Mind" quest

### ISSUE THREAD

**Issue by DoYouPikachu** [Wynncraft/Issues#5552]
![2016-07-22_10 04 59](https://cloud.githubusercontent.com/assets/16530766/17064903/cc2f989a-4ff3-11e6-9112-bb15945b856f.png)
The text after finishing the quest "Out Of My Mind" 
yes, I care about spelling :D

**Comment by sammyvsparks** [comment]
@AckroWynn all you.

**Comment by Moe-Ronickah** [comment]
This is not an issue.  It is an archaic spelling of "truly" and does not need to be changed.

**Comment by DoYouPikachu** [comment]
Equipment*

**Comment by sammyvsparks** [comment]
@Moe-Ronickah ^

**Comment by Moe-Ronickah** [comment]
sammy, you don't need to tag me.

**Comment by Moe-Ronickah** [comment]
@DoYouPikachu , we'll pass this along to the builders and get it fixed.  Thanks.

**Comment by AckroWynn** [comment]
Fixed!

**Comment by Trixter313** [comment]
Yay! You can expect to see the changes when the next map update is made. =)
