### ISSUE TITLE
Kicked for flying

### ISSUE THREAD

**Issue by TheGamingWorm** [Wynncraft/Issues#5553]
I don't know if this has been happening to anyone else, but about 25% of the time I join the Wynncraft hub, I get kicked for flying, then my game automatically rejoins and it happens over and over again. I have to open a task manager to even close my game to stop it. And before you ask, no, I was not using hacks in any way shape or form. I was just using plain old minecraft 1.10.

**Comment by Moe-Ronickah** [comment]
Please, play WynnCraft with MC 1.8.9, and no versions higher.  WynnCraft is 1.8.9 compatible, and that difference, alone, can cause unexpected errors to occur.

**Comment by TheGamingWorm** [comment]
okay thanks

**Comment by TheEpicCorgi** [comment]
i have the same problem.

**Comment by Trixter313** [comment]
So did using 1.8.9 help solve the issue for you guys? =)

**Comment by TheGamingWorm** [comment]
yes

**Comment by Trixter313** [comment]
Glad to hear!
