### ISSUE TITLE
Missing Textures in the Creeper Hideout

### ISSUE THREAD

**Issue by Knastoron** [Wynncraft/Issues#5554]
Tere are some missing textures in the Creepoer Hideout  next to the NPC in there
![2016-07-23_10 19 07](https://cloud.githubusercontent.com/assets/20609939/17076923/f78643f6-50be-11e6-92b3-4f9ccf94ab71.png)

**Comment by Trixter313** [comment]
What version of Minecraft are you using?

**Comment by Knastoron** [comment]
1.10. but it was fixed after relog

**Comment by Trixter313** [comment]
Good to hear. For future issues you might encounter, we recommend using 1.8 for Wynncraft and that's the version we can best help you with if you run into any issues. Some issues stem mainly from using something higher than 1.8.
