### ISSUE TITLE
Lazarus Pit Quest Glitched (NPC refuses to pass on to the next stage)

### ISSUE THREAD

**Issue by JackyKit123** [Wynncraft/Issues#5555]
According to the quest book and wiki, that should be the last stage of the quest.I have the items required and I've finished the previous stages yet I was not able to finish the quest and it is stuck.
https://wiki.wynncraft.com/index.php?title=Lazarus_Pit
https://www.youtube.com/watch?v=eXnjpiqmdJY

**Comment by sammyvsparks** [comment]
Walk around and follow the quest, you may of missed a region trigger or something along the way.

**Comment by Loganpt** [comment]
It appens with me to

**Comment by Moe-Ronickah** [comment]
Right-click on Burtar with an empty hand and see what happens.

**Comment by Loganpt** [comment]
I try to go back to see if I made something wrong and when I got back I
realised that I didn't gave him the right item. The npc that did that is
lacrona
But now there's a quest npc that when I try to talk to him the mensage
apears invisible.
The npc is in the detlas city.

Em 27/07/2016 10:46 da tarde, "Nathan Stolov" <notifications@github.com>
escreveu:

**Comment by sammyvsparks** [comment]
@Loganpt Which NPC are you talking to that toggles it. Also what stage is your quest book on?

**Comment by JackyKit123** [comment]
so I've found the problem, the item 'Healing Water' which is minecraft:flower_pot was given by me typing /fixquests
while the correct quest item 'Healing Water' should be minecraft:experience_bottle
I think it's becuz of the outdated database of /fixquests

**Comment by sammyvsparks** [comment]
Unless they changed it, it should be a flower pot. It was when I did the quest not to awfully long ago.

**Comment by Trixter313** [comment]
I did the quest today and it gave me an experience bottle to use.

**Comment by Loganpt** [comment]
Right now I can't tell you now because I'm having problems with my laptop
but when I enter in the server I will see the npc name and I will tell you

Em 29/07/2016 19:21, "Samuel Voeller" <notifications@github.com> escreveu:

**Comment by Moe-Ronickah** [comment]
@AckroWynn  - is this fixed?

**Comment by AckroWynn** [comment]
@Moe-Ronickah I checked the quest YML for this, and you can have a look, yourself.
![image](https://cloud.githubusercontent.com/assets/7467934/18417039/dd43478a-7825-11e6-8ab7-6f63b7eeae37.png)
![image](https://cloud.githubusercontent.com/assets/7467934/18417043/fafb97be-7825-11e6-9f98-1e1abfee05e9.png)

They seem to be stuck somewhere in the quest coding. Nothing that I can fix.

**Comment by AckroWynn** [comment]
However, I took a further look in to it, and it seems like the quest requirement changed in to a new item:
![image](https://cloud.githubusercontent.com/assets/7467934/18417065/7466065c-7826-11e6-8d35-da3afa898325.png)
Some GM updated it, and I do not know why.

**Comment by Moe-Ronickah** [comment]
Which means that they are stuck and cannot complete the quest, correct, until /fixquests is updated?

**Comment by AckroWynn** [comment]
If /fixquests gave you Quest Items from within the quest, that would fix it.

**Comment by AckroWynn** [comment]
This can not be fixed for this person, but is fixed for the future.
