### ISSUE TITLE
Fantastic Voyage boat steering..

### ISSUE THREAD

**Issue by C0meGetS00me** [Wynncraft/Issues#5556]
Hello, while doing 90lvl "Fantastic voyage" quest I can't steer the boat becuase it's lagged and im on different position than it shows, im throwing emeralds to check, and I see that my actual possition is like 15 blocks away, and it tp's me to start like every time because im hitting something that i don't see.. What now :/

**Comment by YunoFGasai** [comment]
what game version are you using?

**Comment by Moe-Ronickah** [comment]
Besides making certain that you are on 1.8.9 or lower, I've heard that you can swim that section, instead of using a boat.  I haven't tried it, but I would like to know if you try it and it works.

**Comment by C0meGetS00me** [comment]
Thread to close, I swam it, on 1.10.

**Comment by Moe-Ronickah** [comment]
I'm glad that you made it!  And, especially, thank you for trying the suggestion that I heard, and confirming that it works.
