### ISSUE TITLE
Pelier not updated during Gavel Update

### ISSUE THREAD

**Issue by Audei** [Wynncraft/Issues#5558]
![2016-7-23_9 46 48](https://cloud.githubusercontent.com/assets/17649334/17079079/89fb3016-50ba-11e6-9729-72a4ca649230.PNG)

Pelier doesn't have any of the attributes of normal armor after the gavel update?

**Comment by sammyvsparks** [comment]
Some items with accented names could not be updated to the new item system. Those items can either be kept or thrown out. Sadly they are virutally useless.
