### ISSUE TITLE
There's a LootChest inaccessible

### ISSUE THREAD

**Issue by VixenViper** [Wynncraft/Issues#5559]
![2016-07-23_12 30 40](https://cloud.githubusercontent.com/assets/20615654/17079326/2a354e2e-50d2-11e6-82bf-7f587406fa32.png)

As you can see there's a loot chest inaccessible due to it fusing with another chest. Please if you can fix this that would be bueno!

**Comment by YunoFGasai** [comment]
@AckroWynn

**Comment by Villageacules** [comment]
Fixed, repair will come out in the next update.
