### ISSUE TITLE
Skill points wrongly distributed bug

### ISSUE THREAD

**Issue by ImToe** [Wynncraft/Issues#5560]
I haven't played in several months on this server. I had to re-distribute my skill points since there's been a big patch sometime in the past. I put at least 15 SP on each skill but for some reason my Agility skill is at 5 and I cannot use any decent armour/spear. I'm level 47 so grinding 15 skill points with starter weapons is going to take too much. Same issue with grinding emerals for the skill reset.

**Comment by sammyvsparks** [comment]
ImToe, Does your armor/weapons give negative points on agility? (It should show "This skill was modified by your equipment" on the compass when you hover over agility)

**Comment by ImToe** [comment]
I tried removing my armour but it didn't change. I had 96 points to distribute when I started but some got transfered into different skills. (they add up 96 if you count them)

**Comment by sammyvsparks** [comment]
ImToe, when you apply armor some stats get lowered by the armor. What armor do you have currently?

**Comment by Moe-Ronickah** [comment]
Remove all of your armor, empty your hotbar, then look at your stats.  What do you get then?  Is it still low or is it 15 or better?

**Comment by ImToe** [comment]
Yes, my agility went up. I just realised it was my armour that was affecting my skills.
I'm currently using "The Knight's Chestplate" and "Diorite Boots". I also have "Winter's Essence" and "Ajax" but my Agility is too low for "Winter's Essence" and Ajax lowers my agility 10 points.

**Comment by Moe-Ronickah** [comment]
Issue solved!  Have fun playing WynnCraft.
