### ISSUE TITLE
Roots of Corruption hole

### ISSUE THREAD

**Issue by DCM627** [Wynncraft/Issues#5561]
![2016-07-23_16 20 17](https://cloud.githubusercontent.com/assets/19480434/17080102/c8f1807c-50f1-11e6-915d-492aadeb20d1.png)
just a nice, simple 1x1x2 hole that I had to waste 2 soul points on cause I was playing on my mage... that's about it.

**Comment by YunoFGasai** [comment]
added to fixing list

**Comment by DCM627** [comment]
Thanks!
