### ISSUE TITLE
Dagger Texture Causes Blade to Float in Air

### ISSUE THREAD

**Issue by DCM627** [Wynncraft/Issues#5563]
![2016-07-23_20 07 33](https://cloud.githubusercontent.com/assets/19480434/17080949/b735c86e-5111-11e6-8571-dde811a6e02b.png)

I'm not sure if it was meant to be this way or not, so I'd figure I'd post it here. I'm using 1.8.9 and the dagger is called "Dislocater". I don't believe assassins are secretly mages and can move stuff through telekinesis, so I think someone messed up this texture.

**Comment by GlitchDoesMC** [comment]
I'm pretty sure it's supposed to be like that.

**Comment by DCM627** [comment]
Ok, are you certain, though?

**Comment by sammyvsparks** [comment]
A lot of daggers are like that. Either they intended it that way or never decided to fix it yet.

**Comment by Moe-Ronickah** [comment]
This just isn't an issue, even though it does look weird.  It's this way with any weapon that has a blade on it.  There's probably a duplicate here, somewhere, but issue titles aren't always  clear, so finding it isn't going to happen.

**Comment by DCM627** [comment]
I tried looking, but found none. Thanks for the help anyways!

**Comment by Moe-Ronickah** [comment]
Thank you for reporting this, so that we could check it!
