### ISSUE TITLE
"You don't have permission for this area" pop-up for unknown reason

### ISSUE THREAD

**Issue by bmarshall79** [Wynncraft/Issues#5565]
Whenever i try to open a chest or press a button, red text in chat says 'you don't have permission for this area." I got stuck in the silverfish dungeon twice because of this. I have tried restarting my game multiple times, and obviously it didn't work.

**Comment by sammyvsparks** [comment]
@bmarshall79 try using a empty hand, some weapons are retextured blocks which prevent usage due to WorldGuard mechanics.

**Comment by Moe-Ronickah** [comment]
Duplicate of #3902 .  If you had searched for "you don't have permission", you would have found it.
