### ISSUE TITLE
63 Liquified Emeralds - [Jungle Fever] Can't finish the Quest

### ISSUE THREAD

**Issue by Pelliott13** [Wynncraft/Issues#5567]
Sorry if i posted it in the wrong category but here it goes...

I began the quest Jungle Fever and as you know you need to go at Almuj and get 64 Liquified Emeralds.
The thing is, I only got 63! So when I came to Worid, I wasn't able to finish the quest.
If you can do something to give me one more, give me the XP or fix it, it will be perfect <3

Thanks for taking time to resolve this bug! :)

IG: Pelliott_ -->  (was Pelliott13)

**Comment by sammyvsparks** [comment]
Hello, Try using **/fixquests** and see if that returns the lost Liquid Emerald as it is a quest item. It is possible you accidentally threw it and since they are experience bottles it glitched due to minecraft mechanics.

**Comment by Moe-Ronickah** [comment]
Do a search for "jungle fever" and see how many times a single LE has magically disappeared "cough" from the 64LE for the quest.

Get rid of all of the 63 special LE, then use /fixquests, as sammy suggested, and you'll be fine.

**Comment by Pelliott13** [comment]
/fixquests doesn't work :/ It keeps giving me 2 Purple Crystal Shard but not the 1 Liquified Emerald missing...

**Comment by YunoFGasai** [comment]
@Pelliott13 fill up your inventory with emeralds, then split a stack of emeralds and with half the stack in your cursor left click on the stack of le (do this also for the 2 shards you got). this should get rid of them, after this do /fixquests

**Comment by Moe-Ronickah** [comment]
Let me emphasis this part:
**"Get rid of all of the 63 special LE, then use /fixquests, as sammy suggested, and you'll be fine."**

**Comment by Pelliott13** [comment]
Thanks alot it worked :D I didn't do the part ''Get rid of all the 63 LE'' last time.

**Comment by Kapuuu** [comment]
I can't get rid of them
 
:(

Maybe im just stupid

**Comment by thecoolkogut4** [comment]
fill up your inventory with emeralds, right click the emeralds to split a stack (eg if you right click 64 eme you get 32 in your inventory + 32 movable) then use the 32 and click on the 63le. (doesint have to be emeralds or 64) sorry, kind of hard to explain. if you have anymore questions let me know

**Comment by Kapuuu** [comment]
yeayea i understand how you do it but it wont work for me

**Comment by thecoolkogut4** [comment]
thwn try to put the 63 into your daily rewards chest

**Comment by Kapuuu** [comment]
I've already taken that today.. :(

**Comment by Kapuuu** [comment]
Hmm.. Guess I'll just never get the quest done :/

**Comment by thecoolkogut4** [comment]
one last way I can think of, put it into a class and delete it. (I recommend  clearing the entire inventory before you delete it as everything will disapear) everything in the class will disapear and the level will reset

**Comment by Kapuuu** [comment]
Thank you so much that worked. luv ya man <3
