### ISSUE TITLE
Cursed Wand is Cursed - Lifesteal Targetting Player

### ISSUE THREAD

**Issue by sammyvsparks** [Wynncraft/Issues#5568]
I know there is a duplicate somewhere but I cannot find it again (sorry ;-;) however today i noticed my Curse Wand with -6/4s LifeSteal seems to be hitting me back instead of doing nothing. I am not sure if this is intentional or a bug but it buids up fairly fast when it toggles faster then regen does.

**Comment by XavierEXE** [comment]
Negative life steal is supposed to damage the user...
Or are you referring to knockback? I don't get knocked back when negative life steal hurts me.

**Comment by Moe-Ronickah** [comment]
In order to use the Curse Wand safely, you should have armor and/or accessories that have enough +Life Steal to overcome at least some of the disadvantage of using a cursed wand.

**Comment by sammyvsparks** [comment]
Ah, Alright. I never knew they intended negative life steal to harm players. I thought it just lowered your overall lifesteal from monsters.

**Comment by Moe-Ronickah** [comment]
It will lower your life points down to a very low level, however, it won't kill you.
