### ISSUE TITLE
Sudden agility level drop

### ISSUE THREAD

**Issue by MrFancyPantss** [Wynncraft/Issues#5569]
Whilst I was playing my agility level suddenly dropped down from 7 to 4 and now I can not use my weapon anymore.

**Comment by Trixter313** [comment]
Does the skill say it's being affected by your armor? Something else you're wearing probably had negative agility. Take all your armor off and clear your hotbar to see if it goes back to normal.

**Comment by MrFancyPantss** [comment]
I have tried taking off all my armor and clearing my hotbar, nothing had happened when I've done so and the agility stayed the same

**Comment by MrFancyPantss** [comment]
I have also tried removing all the items in my inventory yet still nothing changed.

**Comment by Trixter313** [comment]
So does the skill say it's being affected by your armor when you mouse over the skill? Also, do your skill points add up to the correct amount you should have? (It should be double your levels minus 2 since you start at level 1 and not 0)

**Comment by MrFancyPantss** [comment]
The skill does not say it's being affected though once I calculated the overall amount of points it seems to be over by 8 points. I'm currently level 21 so I suppose this is a bug? (If I am level 21 I am supposed to have 40 points then but somehow once I calculated the overall amount it was 48 points)

**Comment by Trixter313** [comment]
Did you check to see if any of the other skills say that they are being affected by your armor? Your armor might be adding points to your other ones, giving you the slightly higher skill point total.

**Comment by MrFancyPantss** [comment]
Yes, my strength skill is being affected by my armor adding to it 8 more skill points but besides that none of my other skills are being affected by armor, only my strength.

**Comment by Moe-Ronickah** [comment]
OK, right now, or whenever you read this, go ingame.  Take off all of your armor and ACCESSORIES, clear your hotbar.  Now check your skill points.  Is the total correct?  If it is, then something in your hotbar, one accessory or more, or a piece of armor is/was affecting your skill points, and your player skill points are fine.  Then, it's a matter of checking your CURRENT armor, accessories, and weapons for you to see what other effects they have.

**Comment by MrFancyPantss** [comment]
I came to an understanding that my sudden agility drop was caused by a pair of boots I received at one of the quests at Detlas. I have already checked everything and my skill points are just as they should be, 8 have been added to my agility because of the armor I've been wearing. 

Sorry for causing all this mess and waste of time ^^
