### ISSUE TITLE
Cannot start Flight in Distress! 

### ISSUE THREAD

**Issue by PixlCraftr** [Wynncraft/Issues#5571]
I don't know if this was already posted because everyone only writes "Flight in Distress" in the Title!

The quest book says, that I have to speak to the Passenger Controllant to start the quest, but he only says "Can I see your passport please? Oh, without a passport, I'm afraid you can't board."

So he says the same thing as he would say when my level isn't high enough, but I'm level 78.

**Comment by PixlCraftr** [comment]
Problem seems to be, that "Acquiring Credentials" is a quest that needs to be finished before starting "Flight in Distress". It would be nice if it stands in the book (like "Finding the Light" for example)

**Comment by AckroWynn** [comment]
Acquiring Credentials is a quest for level 74, whilst FiD is 75. I just assumed everyone would do Acquiring Credentials before FiD.

**Comment by PixlCraftr** [comment]
yeah, but i had both quests and wanted to do flight in distress first because of the connection between cinfras and detlas you get. a little hint like you see at "Finding the Light" and "Realm of Light" won't hurt ;)
