### ISSUE TITLE
Need Help joining a guild

### ISSUE THREAD

**Issue by setery10** [Wynncraft/Issues#5573]
After changing my name back I can't read messages in my guild it says I'm in it and also says I'm not in it.
My old IGN was: IGotLostInSauce
My new IGN is: Setery
If a staff could help fix this issue with my guild that would be great.
Here's a screenshot.
![2016-07-24_12 19 55](https://cloud.githubusercontent.com/assets/8347065/17084942/2c3b0ff2-5199-11e6-8b07-2066d08769fc.png)
I am the Guild owner and I can't leave or join the guild

**Comment by Moe-Ronickah** [comment]
This is actually a duplicate of #3665 , even though the issue titles are different.  It all revolves around problems with the guild coding.  You can follow the issue there, if you want to.

**Comment by sammyvsparks** [comment]
There is a way around this if you own the guild, sadly it requires disbanding it fully.

**Comment by Moe-Ronickah** [comment]
Please contact yosteric5 on the forums concerning this issue to see if he knows of any other fix.

**Comment by setery10** [comment]
Oh sorry meant to reply to this, it's fixed maybe a mod fixed it or something else? Either way this can be closed although we have duplicate players.

**Comment by Shmexy** [comment]
its not fixed for me :(
