### ISSUE TITLE
bank error

### ISSUE THREAD

**Issue by EricSalata** [Wynncraft/Issues#5574]
Hello, my game name is YourLocalGamer, and my bank glitched out, and I can't open it, could my bank please be reset to default where there is one row unlocked, so I can use my bank again, thanks.

**Comment by Moe-Ronickah** [comment]
Try right-clicking on your enderchest with an empty hand.  If you tried to open it with certain weapons, you may have gotten an error message, because some weapons still retain properties of their original item class.  Let us know if this works for you.

**Comment by EricSalata** [comment]
Sorry, It didn't work, no matter what I click with it won't open.

**Comment by EricSalata** [comment]
Does it have to be reset? I have nothing valuable in it, but I fully unlocked my bank and stored materials in it. So I'm fine if I lose it all.

**Comment by Villageacules** [comment]
Try opening in different versions of Minecraft, re-logging, and switching between classes.

**Comment by EricSalata** [comment]
that didn't work either.

**Comment by EricSalata** [comment]
Is there anyway I can reset it?

**Comment by Villageacules** [comment]
@EricSalata there isn't any way to reset your bank specifically, but if you really wanted me to (as a last resort,) I could tell Salted to wipe your character and that **MIGHT** reset your bank. Its a big risk if you want me to do so, unless you just want to use other accounts as bank (this may be a bit irritating, but hey, it works.

Please respond to this comment, post a message on my profile on the forums, or send me a PM on the forums if you want to speak with me in private.

**Comment by EricSalata** [comment]
Yea, please tell him to wipe everything. Thank you so much!

**Comment by EricSalata** [comment]
Wait, would it remove my pet and vip+ rank?

**Comment by EricSalata** [comment]
It shouldn't right?

**Comment by Villageacules** [comment]
@EricSalata No, your ranks won't be wiped. I'll get you wiped in the next few days depending on how participating Salted is.

**Comment by EricSalata** [comment]
Thanks you so much!

**Comment by Villageacules** [comment]
@EricSalata Would you please tell me your exact username? (caps sensitive)
