### ISSUE TITLE
Kicked for flying repeatedly

### ISSUE THREAD

**Issue by TheEpicCorgi** [Wynncraft/Issues#5576]
Whenever a server restarts i get put in the lobby, But becuase of the lag that happens i get stuck in the air for a second. the game registers it as flying and kicks me back to another lobby. the process continues to repeat until i find a way to close minecraft

**Comment by Moe-Ronickah** [comment]
This is a duplicate of #5409 .  You can follow our discussion, there, and see if we can help you, also.
