### ISSUE TITLE
Glitch caused me to get the reward in Shattered Minds Quest Early

### ISSUE THREAD

**Issue by IncBear101** [Wynncraft/Issues#5577]
So I talked to the guy who I'm supposed to talk to (Elder Berusia) but then when he finished talking, he gave me forty EB, early, and then when I finished the quest, I didn't get the reward EB. So I got the EB 1 stage before I was supposed to get it. This is a reminder that this still happens if this is a duplicate, and if this isn't a duplicate, someone should look into it.
![2016-07-24_19 45 49](https://cloud.githubusercontent.com/assets/20328015/17088435/1ab7c75e-51d8-11e6-8501-96725894bb57.png)

**Comment by IncBear101** [comment]
Now if I was lying, then what's the point of making a whole issue about it

**Comment by awemanrank100** [comment]
You're supposed to go back to Likeru after talking to Elder Berusia for your final reward.

**Comment by Moe-Ronickah** [comment]
@IncBear101 , did someone accuse you of lying?

Please follow awemanrank100's advice.  You haven't finished the quest, yet.

**Comment by IncBear101** [comment]
So I finished talking to Likeru, then he gave me the chest plate reward and the XP, but not the reward money

**Comment by IncBear101** [comment]
The 40 EB I "got" from Elder Berusia was supposed to be my reward money

**Comment by IncBear101** [comment]
Some people at my old school don't believe me at stuff I did and they accuse me of lying its like they don't want to believe it y'know

**Comment by IncBear101** [comment]
Also, good morning

**Comment by Moe-Ronickah** [comment]
I must have been tired.  40 EB x 64 E = 2560 emeralds.  Exactly as promised in the Wiki.
