### ISSUE TITLE
My Mana is glitched

### ISSUE THREAD

**Issue by DD1GamingYT** [Wynncraft/Issues#5580]
I was doing a quest where I needed to get some emerald blocks... I go to Almuj and get some... Shortly after my mana would go to 3 then drain down like I am spamming heal on myself... I have already re logged...  and changed classes. If this has happened to other people I hope you can fix it... Thank you :)
DD1GamingYT

**Comment by Moe-Ronickah** [comment]
Check to see if you have negative mana regen.
