### ISSUE TITLE
Resource Pack Interrupted

### ISSUE THREAD

**Issue by Superrocky1** [Wynncraft/Issues#5582]
Hi! Recently, I have decided to get back into Wynncraft. I am able to join fine using a mac on the 1.10 version of minecraft. However, I am having a problem with the resource pack being downloaded. Once I enter a server, it starts downloading the resource pack. It is then stopped because of the class selection screen popping up, which causes me to have to re-log, only to come back to it being interrupted once again. If there is any solution to this, I would love some help.

Thanks!

**Comment by EricSalata** [comment]
I had the same thing happen to me, quit to minecraft's title screen, go to server resources packs, and delete all of the wynncraft ones, it may be named "legend", delete all of them, then log back on, this should fix it.

**Comment by Moe-Ronickah** [comment]
Also, WynnCraft is 1.8.9 compliant.  If you use any higher version of MC, you do so at your own risk.

**Comment by Sorceric** [comment]
Moe, does that mean if I played Wynncraft in 1.8.9+ (like 1.10 e.g) and the resource pack stops working, would that mean that I can't play Wynncraft anymore? Because i still can't find a solution to fixing it even though I followed your instructions

**Comment by Moe-Ronickah** [comment]
No way, Sorceric.  We will find a way to fix this.  Get ahold of BlahBlah161616 on the forums, please.  He is running a Mac also, and had a similar problem.  Ask him for instructions and lets see what happens.

**Comment by ColinRioux** [comment]
If this hasn't been answered– I suggest logging in with resource pack off and/or with a different version of minecraft, and toggle autojoin:`/toggle join`. Essentially, this will automatically log you into a class, letting you download the resource pack, and perhaps will prevent interruption. Then, when you need to change your class, you can do: `/class` or `/classes`. 

In terms of mac, this isn't a **mac only** issue, because I'm on mac currently and am not coming across this issue.

**Comment by Moe-Ronickah** [comment]
@Sorceric , ColinRioux is colin350, I believe.  He has extensive experience with Macs and he is a new admin on the Wiki.  Try his advice, please.  I want to see you back in-game.

**Comment by Superrocky1** [comment]
@ColinRioux Thank you for the advice, but it has not worked out for me. I have toggled the auto join on, and that lets me prompt the resource pack, but after clicking yes to download it, it just stops again and gives me the "You do not have the resource pack" message.

**Comment by Sorceric** [comment]
@ColinRioux how do you "toggle auto join"?

**Comment by ColinRioux** [comment]
`/toggle autojoin`

For mac users: 
If you still have trouble downloading the pack, you can download the file titled: "legacy" that is apart of this repository. After downloading, rename the file to `legacy.zip` and then open the zip. Then move the unzipped folder into the resourcepack folder in your minecraft folder.

**Comment by Sorceric** [comment]
@ColinRioux no like where do i put the command , because it doesn't work in the wynncraft server

**Comment by Trixter313** [comment]
You would type it into the chat. You can't be in the lobby while you do it either, you must be logged into a class.

**Comment by Sorceric** [comment]
@Trixter313 except the problem is I can't CHOOSE  a class because I fall down the void whenever i try to choose a class and unable to do any commands.

**Comment by Trixter313** [comment]
@Sorceric did you disable the resource pack like it said in @ColinRioux original comment? (Multiplayer > Wynncraft > Edit > Server Resource pack)

**Comment by Sorceric** [comment]
@Trixter313 It still says "You can't use commands right now!"

**Comment by ColinRioux** [comment]
You must be logged into a server to toggle auto join, not the lobby. I
suggest disabling server resource packs in the server settings. Then
joining wynncraft. If you still fall through the void, try joining the
nether server instead and see if that works.

Just some advice: stay calm, we will get through this. The more patient and
relaxed you are, the easier it is to help you.

**Comment by Superrocky1** [comment]
@ColinRioux Where can I find and download the "legacy" file at? Sorry if I missed something.

**Comment by Trixter313** [comment]
@Superrocky1 https://github.com/Wynncraft/Issues/blob/master/legacy

**Comment by Moe-Ronickah** [comment]
I tried to tp him to me, in game, and it didn't work.

**Comment by Sorceric** [comment]
@ColinRioux yea I'm calm atm I'm just playing Minigames for now ^_^

**Comment by Moe-Ronickah** [comment]
@Superrocky1 , I'm trying some more ideas with Sorceric, today, hopefully.  Don't give up.

**Comment by Moe-Ronickah** [comment]
@Superrocky1 , are you still unable to log in to Wynn to play?

**Comment by Moe-Ronickah** [comment]
RESOLVED
