### ISSUE TITLE
TP to start, World°3, 2m under ground

### ISSUE THREAD

**Issue by AntonioNoack** [Wynncraft/Issues#5583]
Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue. <- nope, but I am feeling helpless. I'll try to relog.... if this doesn't work I'll be sad...

Exact: I died at Lv3, and was ported back but I am unable to get out of the house because I am in the floor. I know this because I can see it when I am jumping

**Comment by AntonioNoack** [comment]
It worked but it's stupid that you have to relog

**Comment by Trixter313** [comment]
If you ever get stuck somewhere you can use /kill and it will get you out. =)
