### ISSUE TITLE
World Border

### ISSUE THREAD

**Issue by RekyuGan** [Wynncraft/Issues#5585]
I was traveling the map and I found a world border.
With the mage you can teleport you. And I teleport me ine the world broder.
I can't escape, please I need help.

**Comment by RekyuGan** [comment]
If this is not a bug please forgive me. (I'm french, and I don't speak english very well)
I'm in the wall since 2 week.

**Comment by Trixter313** [comment]
I'm sorry to hear that! Luckily, all you need to do to get out is use the command /kill with 3+ soul points. We hope you enjoy your time playing Wynncraft! =)
