### ISSUE TITLE
Diaglouge not showing up

### ISSUE THREAD

**Issue by ThePyromaniac** [Wynncraft/Issues#5586]
The NPC at X: 197, Z: -2170, when you accept his quest, and click on him again, he says a blank message. Not his name, or anything. 

(Quest: https://wiki.wynncraft.com/index.php?title=Mansion_Delivery)

**Comment by Villageacules** [comment]
This quest was made before we reworked the quest system and added fallback dialogue. This isn't a bug, but rather an inconvenient and outdated "feature." Closed.
