### ISSUE TITLE
Quest items lagging away

### ISSUE THREAD

**Issue by DaddaPadda** [Wynncraft/Issues#5587]
I was doing the quest Shadow of the Beast, i took a little brake and came back and boom suddenly one of my quest items were glitched away. The only way its seems that i can get a new one is to level up a new character to level 60 ish and try to do the quest again but as i dont have that much spare time for just one quest item i really dont know what to do. If i could get a new one my name in minecraft is xXDaddaPaddaXx and the items name is Stringy Hair. Thanks for you're response.

**Comment by Trixter313** [comment]
1. What does it say in your quest book for that quest?
2. Does using the command /fixquests do anything?
3. Can you go back to where you got the stringy hair and get more?

**Comment by DaddaPadda** [comment]
Thanks, i didn't know /fixquests was a thing. Hope you have a nice day!

**Comment by Trixter313** [comment]
Yay, glad we could resolve your issue. We hope you enjoy your time playing Wynncraft!
