### ISSUE TITLE
SKILLS RANDOMIZED

### ISSUE THREAD

**Issue by Ainhoa03** [Wynncraft/Issues#5589]
my skill levels are usually mixed

**Comment by EricSalata** [comment]
Wait, do you mean your kills were randomly assorted when you came back on?

**Comment by EricSalata** [comment]
Skills*  sorry.

**Comment by Ainhoa03** [comment]
No, what I mean is that I changed the skills when he wants and how he wants

**Comment by Moe-Ronickah** [comment]
This isn't making any sense.  It sounds as if you are replying to someone else at the start of your issue, based on your last message.

**Comment by Legomix13** [comment]
@Moe-Ronickah no,with 'he' refers to the server
