### ISSUE TITLE
Lost LE

### ISSUE THREAD

**Issue by Kfajver** [Wynncraft/Issues#5590]
I welcome. Today I went away all over the city called Troms. In the equipment I had 47 LE because I wanted to show off for the friend, after taking them from the box and Trade doing my emeralds disappeared. I don't have them neither in the equipment nor in the box and my friend doesn't also have them. I have a screen shoot which I did 3 days ago but there is shown that I have shown 41 LE. what am I supposed to do? http://screenshot.sh/m3AUwOUz0Hrjr

**Comment by EricSalata** [comment]
Check you, your Friend, and the banks. Also click around in your invetories, it might appear, but wynncraft has a strict no refund policy on in game items, unless there is a server wide rollback, you can't get them back, sorry.

**Comment by Trixter313** [comment]
As mentioned above, try clicking in the empty spaces of your inventory and make sure to check everywhere. Unfortunately Wynncraft has a strict no refunds policy as the admins are very busy and it's very difficult to tell who truly needs it and who is trying to abuse it.

If it was possibly dropped, I'd suggest changing your drop key to something you're less likely to accidentally press. Also, if you have something valuable to you I'd say try and not move it around to much as that increases the chances of something happening to it.
