### ISSUE TITLE
Stuck in the Sky

### ISSUE THREAD

**Issue by 99leo** [Wynncraft/Issues#5591]
Hello,
I am a mage level 20 and teleported me up on the mountain by the Pigmen Ravine, now I'm stuck there can't teleport away (now I also threw away my wand) and can't move at all, I also don't have a teleportation scroll. So please could you either fix this bug completely or somehow get me back on earth?
Name on server: leop2
Thank You

**Comment by EricSalata** [comment]
Yea, do /kill or /die, make sure you have 3 or more soul points.

**Comment by 99leo** [comment]
Thank you Issue solved very quickly

**Comment by EricSalata** [comment]
You can close the issue now, thanks.

**Comment by Moe-Ronickah** [comment]
@EricSalata , you can close any issue that you open, just for future reference.
