### ISSUE TITLE
player riding?

### ISSUE THREAD

**Issue by EricSalata** [Wynncraft/Issues#5593]
Hey, sorry about this I looked up this and couldn't find anything else about it, also I don't know if this is the right place to report this, but are player riding and pet riding glitched?

**Comment by Trixter313** [comment]
Hello! What do you mean exactly by glitched? To ride players you have to be VIP and to ride pets you must be VIP+, if you're not able to ride at all. Is this what you meant? Thanks!

**Comment by EricSalata** [comment]
Wait, can a vip+ ride people to? Because I am a vip + and can't do it, is there a certain way to do it?

And the pet thing is, whenever you right click you automatically go onto your pet and it becomes a horse.

Thank you for your time!

**Comment by EricSalata** [comment]
I'm pretty sure I just can't figure it out =)

**Comment by Trixter313** [comment]
To ride a player, make sure you're right clicking on them with an empty hand.

As for the pet issue, I have found the original issue for it, it was closed and sort of difficult to find. It is currently a known issue and we are pretty much just stuck on trying to fix it. https://github.com/Wynncraft/Issues/issues/3783

Let me know if you're able to ride players and if so, this issue can be closed. =)

**Comment by EricSalata** [comment]
Oh, I never tried  if with an empty hand, I'll do that later, thank you!

**Comment by EricSalata** [comment]
Yup it worked, thanks

**Comment by Trixter313** [comment]
Glad to hear!
