### ISSUE TITLE
Green Skinned Trouble bug

### ISSUE THREAD

**Issue by hvchvc4** [Wynncraft/Issues#5594]
When i "Follow the light" in the Green Skinned Trouble cave, I enter the black wool portal, but then it just says 'null' and teleports me away. Please fix it, I'm about to levelup and it's the only quest i can do for my level now. Thanks. -7x3
Proof - http://imgur.com/a/KHRPo

**Comment by Trixter313** [comment]
What does it say in your quest book? I'd also suggest retracing your steps a bit to see if maybe you missed a trigger to continue further in the quest.

**Comment by Moe-Ronickah** [comment]
OK, here's the [Wiki for this quest](https://wiki.wynncraft.com/index.php?title=Green_Skinned_Trouble).  After reading through this, have you missed anything?  What stage are you on?

**Comment by Freemiiner** [comment]
I finished this quest and got teleported into a block and resorted to /kill ;-;

**Comment by Moe-Ronickah** [comment]
RESOLVED
