### ISSUE TITLE
Bob glitch?

### ISSUE THREAD

**Issue by Monkey1miner** [Wynncraft/Issues#5596]
IGN: _NovaPvP

I'm really scared that I not be able to ever level up now I killed Bob with some people get the seal and finished the quest! I had all my Xp routed to my guild and finished the quest and I didn't level up after completing the quest and getting the corrupted treasure D: I have screenshot proof of all of this please help so I can level up and continue playing D: 
![2016-07-27_13 44 03](https://cloud.githubusercontent.com/assets/20363648/17188076/4e48cf70-5401-11e6-9a23-65d51e182dac.png)
![2016-07-27_13 44 42](https://cloud.githubusercontent.com/assets/20363648/17188074/4e44f01c-5401-11e6-9287-5d5fcaf8811d.png)
![2016-07-27_13 48 49](https://cloud.githubusercontent.com/assets/20363648/17188077/4e495940-5401-11e6-9c11-9e38d68b4ce3.png)
![2016-07-27_13 43 58](https://cloud.githubusercontent.com/assets/20363648/17188075/4e4588e2-5401-11e6-825f-bbc7df74e622.png)

**Comment by EricSalata** [comment]
Hi, are you asking if your game glitched?

Your game isn't glitched, all of your xp just went to your guild, So you didn't get any yourself. 

If you want xp, set it to give 0 xp to your guild.

**Comment by EricSalata** [comment]
Oh. Are you saying your guild didn't get any xp?

**Comment by Monkey1miner** [comment]
No I got no XP And I cant level up from level 74 to 75 to continue after I killed Bob!

**Comment by Trixter313** [comment]
Because your XP was being sent to your guild and everything worked properly, this isn't an issue or bug. In this case there is nothing we can do and all we can suggest is making sure to change your XP contribution to something lower or even 0 if you'd like to prevent it from happening again. You'll have to farm and do dungeons to get to the next level.

**Comment by Shmexy** [comment]
you did /guild xp 100 so you give all the xp to your guild...
