### ISSUE TITLE
Horse glitch!

### ISSUE THREAD

**Issue by EmeraldEyeofhelp** [Wynncraft/Issues#5597]
Whenever I ride a horse it won't save the data of where I am and the chunks won't load. So when I get off the horse it will teleporte me back to where I got on the horse.

**Comment by EricSalata** [comment]
Hello,
What version of minecraft are you in?
Please use 1.8.9 or lower, this might fix it.

**Comment by EmeraldEyeofhelp** [comment]
I tried it didn't work

**Comment by Trixter313** [comment]
When you tried 1.8.9 were you also using any mods or mod loaders or was it vanilla Minecraft?

**Comment by EmeraldEyeofhelp** [comment]
vanilla

**Comment by sammyvsparks** [comment]
@EmeraldEyeofhelp That issue is known to happen on higher versions of minecraft, ensure you are using 1.8.9 by changing the version.

**Comment by Grauly** [comment]
well... i have the same bug, i think its global, so i lost my legandary bow through that glitch:
I dropped it ,i didnt maent so, got out of the boat i was in, lost the location, and it despawned, can somone help me? The bow was called "Thunderstorm".

**Comment by EmeraldEyeofhelp** [comment]
sorry to hear about your bow.
