### ISSUE TITLE
Strange Blocks

### ISSUE THREAD

**Issue by LightTrainer** [Wynncraft/Issues#5599]
Hey guys this will seem odd but when I logged in today I noticed there were these strange pink and black blocks around. Is there some sort of graphics glitch or something?
![image](https://cloud.githubusercontent.com/assets/20692403/17196680/6430945c-5434-11e6-8b3a-b15647d380e2.png)

**Comment by XavierEXE** [comment]
It's because you're using 1.9 or 1.10, I can tell based on the way the wand looks in your hotbar. Play on version 1.8.9 and the issue should fix itself.

**Comment by EricSalata** [comment]
Yea, 1.9 added new textures which arent supported yet.
