### ISSUE TITLE
Cannot see servers in the main Server Selection screen.

### ISSUE THREAD

**Issue by icninja** [Wynncraft/Issues#5600]
I cannot see any of the servers when right clicking the compass, walking into the portal in the hub, or typing /server. I can see the actual chest screen, and can select whether i want a Wynncraft or Wizard Fortress server, but no blocks show up as servers. I have tried relogging, waiting for the servers to load, restarting my client, and restarting my computer (mac), and none of these has resolved the issue. Screenshot attached below.

<img width="355" alt="screen shot 2016-07-28 at 7 57 47 pm" src="https://cloud.githubusercontent.com/assets/16701797/17208836/963ad93e-54fd-11e6-821f-56d30f481c48.png">

**Comment by Sorceric** [comment]
do /lobby , your in a lobby that is currently glitched.

**Comment by EricSalata** [comment]
Leave minecraft  then come back on.

**Comment by Moe-Ronickah** [comment]
Duplicate of #5012 .
