### ISSUE TITLE
Missing Bob's mythic wand

### ISSUE THREAD

**Issue by Mattyboy84** [Wynncraft/Issues#5601]
toay i logged on to mywncraft servers and my bobs mythic wand was missing, it isnt in my inventory and wasnt iin my echest or on any other calsses. please could a member of staff contact me so we can sort this out.

**Comment by Trixter313** [comment]
Unfortunately we can't do anything in cases where an ingame item goes missing. Wynncraft has a strict no refunds policy. The most likely cause for this is that it was accidentally dropped and all we can do is suggest you change your drop key to something you're less likely to hit to try and prevent something like this from happening again.

You can look around on the forums or ask players ingame if they can sell you a weapon to use.

**Comment by SATMC** [comment]
Rip matty
