### ISSUE TITLE
Guild attack

### ISSUE THREAD

**Issue by Adrien-31** [Wynncraft/Issues#5604]
I'm trying to do some guilds attacks but I can't beacause "Your guild is already in a battle" since 4 hours.

**Comment by Trixter313** [comment]
This issue usually fixes itself with time. The longest it's lasted that I know of is 2 days but let us know if it starts working for you.

**Comment by tobocoolman2000** [comment]
I tried to do a guild attack but when I got into the battle no mobs spawned. So we can never take and control territories.

**Comment by sammyvsparks** [comment]
Known issue, guilds are fairly broke currently and known to be buggy. Try different servers and locations and eventually it will work. @tobocoolman2000

**Comment by Moe-Ronickah** [comment]
There are multiple descriptions of this same issue, in various ways, here.  This is a duplicate, and guilds are currently broken.  The admins are aware of these issues and are working on them.  No, no one knows when guilds will be fixed.
