### ISSUE TITLE
Shadow of the Beast Capitalization Inconsistency

### ISSUE THREAD

**Issue by Trixter313** [Wynncraft/Issues#5612]
Just a small issue, for the quest Shadow of The Beast, the pink wool's capitalization is off from the others.
The others say, "This **A**ncient **G**uardian drops one [this] wool". The pink wool says, "This **a**ncient **g**uardian drops one [this] wool" with lowercased ancient guardian.

Here's a link to an imgur album showing the different wools: http://imgur.com/a/28mSf

I noticed a lot of small corrections like this being fixed recently and figured this was worth a shot, especially with an update on the horizon so it could be pushed to the play server pretty soon.

**Comment by AckroWynn** [comment]
@Trixter313 I'll be sure to look in to it when I get back home later today, or tomorrow.
Notifying ya when it's done.

**Comment by Trixter313** [comment]
Awesome! Hope it can be fixed and without much work. =)

**Comment by XavierEXE** [comment]
How do you even find stuff like this, lol

**Comment by Trixter313** [comment]
Not sure myself xD
Maybe a small case of OCD

**Comment by Moe-Ronickah** [comment]
Some people are just more in-tune with tiny variations.  They notice and fix things on GitHubs, they find Waldo while everyone else is still scratching their heads, and they notice strange inconsistencies in people's logic in print.  Speaking of, I know of one guy, who tends to execute those inconsistencies.  :)

**Comment by AckroWynn** [comment]
@Trixter313 Fixed!

**Comment by Trixter313** [comment]
Woot!! =)
Thank you for being so on top of the issue tracker
