### ISSUE TITLE
I still don't have my rank.

### ISSUE THREAD

**Issue by Sparkydalmation** [Wynncraft/Issues#5613]
Alright, its been at least 10 hours and i still don't have my rank. I need help.

**Comment by Trixter313** [comment]
When you typed in your username did you make sure to have the correct capitalization? Usernames are case sensitive and must match exactly. You should be able to see what you typed in the receipt that was emailed to you.

Also, we are talking about it ingame and not on the forums correct?

**Comment by Sparkydalmation** [comment]
Yes, ingame. I will check my email now.

**Comment by Sparkydalmation** [comment]
No, my username is exact: Sparkydalmation. Only one capital.

**Comment by Trixter313** [comment]
Hmm, well your best option in this situation after checking these things is to send an email to support@wynncraft.com to see if they can help you. Explain your question and have your receipt ready in case they need any information from it.

Let me know the outcome here, whether they help resolve it or not for you. Thanks!

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
