### ISSUE TITLE
Help Me Pls

### ISSUE THREAD

**Issue by PlayBooyBr** [Wynncraft/Issues#5617]
I'm trapped beneath the earth someone help me please. Print: prnt.sc/bz7bno
( https://cloud.githubusercontent.com/assets/20730731/17261526/8d813b30-55ac-11e6-90f9-b03c8ab1e4e0.png )

my nick:  PlayBooy_Br

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out. =)
