### ISSUE TITLE
lol, what a strange bug.

### ISSUE THREAD

**Issue by EricSalata** [Wynncraft/Issues#5619]
this is funny, it's a strange bug that is so random,
If you try to open a door with bone meal, it opens then closes really fast, this isnt a major bug, its just something i thought i might just point it out.

**Comment by EricSalata** [comment]
Something i thought i would point out*

**Comment by Trixter313** [comment]
I don't think it is really much of a bug, there are many things in Wynncraft that you must do with an empty hand and using an empty hand should solve the issue. =)

**Comment by sammyvsparks** [comment]
I reported something similar on this with bonemeal glitching on certain items, The developers know about that and are working to get that patched per what support told me.
