### ISSUE TITLE
My Friend Lost All his stuff and got degraded to Level 4

### ISSUE THREAD

**Issue by Pyrotimegamer** [Wynncraft/Issues#5620]
Hello Evryone My brother and i and a friend of mine started playing together on the Wynncraft Server Untill we disconected he had all of his stuff but when he reloged this morning all of his stuff was gone and his level was 14 and got deranked to rank 4 if you could get my brother his level and stuff back that would be cool his ign name is gugy9 if you could fix this "glitch" that would be cool 

I Aprechiate ur Help 

Pyro

**Comment by Pyrotimegamer** [comment]
Just to so i DONT get eny confusion he still had his 10 soulpoints and he also logged out inside of detlas

**Comment by Trixter313** [comment]
It demoting his level is a bit odd; I don't know what would cause that but I see that he has leveled up to 11 now and luckily it happened early on so it is easier to get the levels back. Wynncraft has a strict no refunds policy for ingame items so unfortunately we can't return any items that were lost.

**Comment by Pyrotimegamer** [comment]
Ok whell Thank you for your help But if this would happen again is there a way that you guys can give him his levels back or is that included in the non refund Policy? thank you

**Comment by Trixter313** [comment]
The only thing we typically refund are things that are purchased with real money.

**Comment by Moe-Ronickah** [comment]
Please remind your friend to change his MC password, as soon as he can.  This really sounds like someone may have used his account and deleted one of his classes.

ALSO, if you, he, or anyone else accidentally right-clicks a class, which opens the Delete Class box, be certain to read the options and tell it "NO".  Don't hit escape.  There is a bug in it that can wipe a class by accident.

**Comment by Pyrotimegamer** [comment]
Ok Thanks for the help but I dont think he accidently deleted it cause he still was level 4 and still had his class he just got deranked and lost his items above lv 4 :/

**Comment by omintrevor** [comment]
i lost all my things to but i didnt get down graded please help

**Comment by Moe-Ronickah** [comment]
@omintrevor , you have a different issue than this.

**Comment by Moe-Ronickah** [comment]
@Pyrotimegamer , I believe that someone else may have been playing on his account, deleted his level 14 class, then tried to get the same class back to level 14, but only got to level 4.  Is that possible?
