### ISSUE TITLE
Unable to give items to Garull for 'Temple of the Legends'

### ISSUE THREAD

**Issue by Azsorlex26** [Wynncraft/Issues#5621]
Alright, so, I'm doing the quest called 'Temple of the Legends', and I'm up to the part where I'm giving the 64 Rotten Flesh, Leather and Blaze Powder to the armour smith called 'Garull'. Yes, I've made sure that these are the correct items, there are 64 of each, just as Garull asked for, and yes I've tried different servers and logged on at numerous times, but this is the same outcome:

![2016-07-30_18 05 41](https://cloud.githubusercontent.com/assets/8101141/17269085/7aec1b3a-5682-11e6-8c01-5a59f74f6c67.png)

![2016-07-30_18 05 43](https://cloud.githubusercontent.com/assets/8101141/17269086/814acd50-5682-11e6-9813-54b2d6a4fddd.png)

![2016-07-30_18 05 44](https://cloud.githubusercontent.com/assets/8101141/17269087/887dfe94-5682-11e6-8a28-d0c3db69f4e3.png)

![2016-07-30_18 05 57](https://cloud.githubusercontent.com/assets/8101141/17269090/8d9163a8-5682-11e6-95bb-17bea2c61610.png)

I have no idea what's causing this. Please help me out; I've wanted to do this quest for a long time ;-;

**Comment by XavierEXE** [comment]
What does your quest book say, and are the items from before the Gavel Update, or did you get the recently?

**Comment by mrhandycat** [comment]
I think you prove some very good points here..... Firstly, the quest book does say to bring Garull the listed items, but the blaze powder and leather I got two years ago before I stopped playing. I'll try to get more blaze powder and leather through grinding/buying and then comment back here if it worked or didn't (god this is going to be painful... Dx)

**Comment by Trixter313** [comment]
Good luck! Hopefully it isn't too bad. Can't wait for the status update =)

**Comment by Azsorlex26** [comment]
yeeaaahhh I think it is the issue... I haven't done all the grinding but I can already see a difference: the old blaze powder's text was white and all it said was 'Blaze Powder', but this new blaze powder is grey and says 'Blaze Powder' *next line 'Junk Item'. Thanks for the help :)

**Comment by Azsorlex26** [comment]
Finally! It's done! Thanks for the help XavierEXE
