### ISSUE TITLE
Green Skinned Trouble Teleport bug after boss fight

### ISSUE THREAD

**Issue by EmilGrouleff** [Wynncraft/Issues#5624]
Hello all, me and my friend just won over Gregg'r in the quest Green Skinned Trouble, but after we took the portal behind the boss we got teleported to nowhere and suicide doesn't work for some reason it just says "Did you mean /sucicide" which BTW doesn't do anything either.
We don't know what do do please help us :(

[Pictures of it]
![2016-07-30_19 00 29](https://cloud.githubusercontent.com/assets/19330161/17271861/f3daab7e-5687-11e6-8ca0-92d5fb866e07.png)
![2016-07-30_19 01 16](https://cloud.githubusercontent.com/assets/19330161/17271864/09f23e72-5688-11e6-8d07-18868503b98c.png)
![2016-07-30_19 01 25](https://cloud.githubusercontent.com/assets/19330161/17271865/0b172f4c-5688-11e6-96af-d4b6bdafe196.png)

Thanks /Limeg7 (IGN)

**Comment by Trixter313** [comment]
Using /kill should work. =)
