### ISSUE TITLE
When i join a world i fall through the ground and the GUI menu to choose a class does not show up

### ISSUE THREAD

**Issue by Combatcompute** [Wynncraft/Issues#5626]
i am right now not able to play wynncraft because when i try to join a world i fall straight through the ground and the GUI menu to choose my class does not show up. it has nothing to do with the resource pack because that loads up fine and everything is ok. i can also not sue any commands in that area i have tried to do /class and other commands like that, that would allow me to choose my character but the only command i can do is /hub. please help me and if you need to contact me my skype is combatcompute
using my skype i will be able to answer you much quicker because i do monitor websites like this a lot so please help me and thanks for reading my issue

**Comment by sammyvsparks** [comment]
What version of minecraft are you using?
Also is your resource pack set to auto download and enable?
You can also try resetting your resource pack in your .minecraft/server-resource-packs/ directory (it should be named "legacy")

**Comment by Combatcompute** [comment]
it has nothing to do with my resource pack the GUI menu is not showing up

**Comment by Trixter313** [comment]
What about the part where @sammyvsparks asked the Minecraft version? We reccomend using 1.8.9 and using anything higher is at the users own risk because using higher versions can cause issues in themselves. If your using anything higher, try using 1.8.9 and see if it helps at all.

**Comment by frostedflakes123** [comment]
This happens to me too the texture pack loads just fine but I just keep falling into the void.I am using 1.8.9 too and that still didn't help
