### ISSUE TITLE
Guild Leader

### ISSUE THREAD

**Issue by colninja** [Wynncraft/Issues#5627]
I used to be the leader of my guild. Then it got rid of my rank as owner for some reason, but the rest of my members have their ranks. The guild is called WynnWarfare.

**Comment by sammyvsparks** [comment]
Did you change your name?

**Comment by colninja** [comment]
I changed my name to my original name.

**Comment by sammyvsparks** [comment]
You should remain leader if you changed back, but if you namechange you loose access to the guild due to bugs in the current system.

**Comment by colninja** [comment]
Okay thank you :D
