### ISSUE TITLE
Low-SP warning does not appear when dropping to 1 SP

### ISSUE THREAD

**Issue by TheDollarBill** [Wynncraft/Issues#5628]
I died at 3 soul points and dropped down to 1 soul point, but I did not receive the warning that tells me I have less than 2 soul points remaining. This warning only appears when dying to 2 soul points, and does not display when dying to 1 soul point.

I've noticed this many times already but haven't thought much about it until I nearly lost all my items due to the warning not appearing.

Here's an image of me dying to 1 soul point. https://i.imgur.com/AvWEzeW.png
Image of what the warning looks like: https://i.imgur.com/4rqfAhq.png

**Comment by sammyvsparks** [comment]
Hm, Never noticed that. @AckroWynn mind looking into this?

**Comment by AckroWynn** [comment]
Nothing we can do. Simply never get those low SP levels, and just AFK in a safe spot in a town, to regenerate them.

**Comment by Moe-Ronickah** [comment]
This is a coding issue that only admins can address.

**Comment by Moe-Ronickah** [comment]
The SP system has been overhauled.
