### ISSUE TITLE
Glitched through a block and stuck??

### ISSUE THREAD

**Issue by eclipsepanther** [Wynncraft/Issues#5629]
Hi. I was exploring the great city of Llevigar when suddenly I glitched through a block and got stuck in one of the prison cells. I did /kill to escape so I can play again! But that was a scary experience and I have no idea how it managed to happen.

**Comment by Trixter313** [comment]
What class are you using? It could have been getting off a horse that caused it but if it was mage you could have accidentally teleported in.

**Comment by theIglooo** [comment]
If this is what I think it is, it wasn't a glitch. Here's how you get in and out: https://www.youtube.com/watch?v=J2pnMI7EQaQ

**Comment by eclipsepanther** [comment]
yes that's exactly it! thanks! I was so confused  I thought I did something wrong >.<
