### ISSUE TITLE
I've lost my quest item and Legendary bow!

### ISSUE THREAD

**Issue by JohnnyArk** [Wynncraft/Issues#5630]
I started the quest Lord of the Clock and was on my way to Mt. Wynn, then the server restarted and i came back on and my horse was glitching out straight away. Then my clock quest item disappeared and i couldn't get it back. Then i clicked on my Legendary Bow and it disappeared and i tried to get both items back but i couldn't. I can provide screenshot proof of me not having the clock but i have no proof that i had the bow. I can tell you what the bow is called and give you a picture of what bow it is but that's all the proof i have. :(
![2016-07-31_18 38 18](https://cloud.githubusercontent.com/assets/20751195/17275512/779925f0-574e-11e6-8a2e-a8a5e83d154a.png)
![2016-07-31_18 37 52](https://cloud.githubusercontent.com/assets/20751195/17275513/779b6766-574e-11e6-8d2d-7e854a90ee69.png)
![image](https://cloud.githubusercontent.com/assets/20751195/17275530/e657c05a-574e-11e6-818b-e3c5b917a961.png)
 
Thanks in advance.

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy whether there is proof or not so we can't do anything about the bow but if you use the command /fixquests it should return the clock so you can complete the quest. I'd ask around to see if someone can give you a new bow for your level.

**Comment by JohnnyArk** [comment]
Okay man, thanks for the help!
