### ISSUE TITLE
Didn't get XP WynnExcavation D

### ISSUE THREAD

**Issue by bartiiiee** [Wynncraft/Issues#5631]
When I was about to complete WynnExcavation Site D I checked everything. Literally, I checked if I was on double xp server, if my guild contribute xp was not to on (it was 0%). And so I finished it, and I immediately looked at my xp bar. Not a single progession, like literally none. So I started panicking, and I thought maybe I have to relog. And so I relogged and still none, and I started asking some high level players if they experienced the same thing. But they all said they didn't. And then a guy said, maybe check your guild list, to see if maybe something went wrong. And so I did, and guess what. It said 1661589 XP (1200000 XP from the quest) and I was just you know. Shocked. And so I was like, I checked my xp percentage amount and it said 0%. But still it transfered my xp from the quest into the guild.. 
Is there any way to transfer it back please? I love my guild but I need the xp at the moment more then they need it. Please have a solution..

Kind Regards, 

Bart (IGN: bartiiiee)

**Comment by Moe-Ronickah** [comment]
I'm sorry, but there is nothing that we can do.  I can only suggest that you check that your guild xp is set to zero well before you go to turn in any quest.
