### ISSUE TITLE
The Mercenary Quest is broken?!

### ISSUE THREAD

**Issue by zMarco** [Wynncraft/Issues#5632]
The Ba'al is not in your place in The Mercenary Quest. maybe he dont exist, idk. Coordinates :  X 1399 Z -2263. I lost 8 souls trying to get the Ba'al but its impossible! :(
 Screenshot: http://prntscr.com/bzt64i

**Comment by Trixter313** [comment]
The screenshot is in the wrong location. Follow the wiki page for the quest or look for a video.
https://wiki.wynncraft.com/index.php?title=The_Mercenary (Especially the tips area at the bottom might help)
