### ISSUE TITLE
Reset Scroll Problem

### ISSUE THREAD

**Issue by Raeigor** [Wynncraft/Issues#5633]
Hello !

I have just pointed out a bug who carrived at me. My name is Raeigor in game. I am level 40 Mage and I have 78 points of competences used.

I used a scroll that I just get in a quest at the Amnesia Tower to reset my competences points and I had in return my 78 points of competences. 

Unfortunately, when I clicked on the different books representing different competences, these stayed at the number 0. I clicked several times on each before the numbers of points I have change, but I wasted several points of competences for nothing. 
Some minutes later (at the same instant or I write this post, while I thought that it was a bug), I realise that they appeared and I am now with points of competences which I didn't want, and I wonder if it would be possible to get another scroll in refund, because it took me a long time to get this one. 
I thank you for advance for your precious help and hope to get an answer fast. 
I apologise for my level of English which is not fabulous, I am French and I hope that you understood me. 

Thank you, Raeigor

In the picture, you can see the look of it now, but before the books of Strength, Dexterity, Defense and Agility were at 0 points visually. 

To the website : http://www.hostingpics.net/viewer.php?id=32077920160731162109.png
Or the image himself is attached
![2016-07-31_162109](https://cloud.githubusercontent.com/assets/20754920/17277104/48f327ae-573b-11e6-98ef-79a082e8f03a.png)

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so unfortunately we can't do anything in this case. You can buy another skill reset scroll or, if you'd like, there is supposed to be a way to reset your points for a few soul points coming in the next update, the Gameplay Update, so you can wait for that. The only thing I'd we don't have an exact release date for the update and it could be a bit of time away still.

**Comment by Raeigor** [comment]
So sad right now I spend so much time getting this scroll. Thank you for the info
