### ISSUE TITLE
bank error #2

### ISSUE THREAD

**Issue by EricSalata** [Wynncraft/Issues#5636]
Hello, as some of you may know my bank glitched last week and was unopenable, and I tried everything, and no matter what I clicked with it said , Error. I ended up fixing with /fixquests,  but now it doesn't work, and doesn't say error, and /fixquests.
And my question is, is there a way I can transfer my vip+ to am another account? Or get an account reset?

Thank you for your time.

**Comment by EricSalata** [comment]
Sorru, auto correct messes me up. /fixquests doesnt work*

**Comment by EricSalata** [comment]
Sorry*, ok, im turning auto correct off

**Comment by YunoFGasai** [comment]
try opening the bank with an open hand.
I think we stopped doing rank transfers but I'm not certain.
as to an account reset you can delete all of your classes and start again.

**Comment by EricSalata** [comment]
I tried, nothing worked, and I deleted all my classes, but it still doesn't work, and i meant account wipe, because that MIGHT reset the bank

Thanks

**Comment by EricSalata** [comment]
The only reason i was hoping for a rank transfer, is so i could play on a diff acount, so my bank won't glitch.

**Comment by EricSalata** [comment]
I was reading some posts, and people were saying that rank transfers were allowed, but the account giving the rank gets banned, is this still a thing?

**Comment by Moe-Ronickah** [comment]
Yes, it does get banned.  If you want to go through with having your account transferred, you will need to contact support@wynncraft.com .

**Comment by EricSalata** [comment]
Alright, they are going to review my purchase reciept, then make a decision off of thag, thank you!

**Comment by EricSalata** [comment]
Alright, they are going to review my purchase reciept, then make a decision off of thag, thank you!
