### ISSUE TITLE
Pirate's Trove quest

### ISSUE THREAD

**Issue by Iceicle** [Wynncraft/Issues#5637]
Hey, I don't know if this is a bug or not. But when I was to do this quests, and search for a black stone, I got the first clue from the NPC. That was ok. The clue said "Toward the sunset among northern flowers shaded by quarts". Well sounded eacy. I found a block of coal. Not shure if that was the black stone. But I searched the hole garden on the west side. And no other black stones was to be found. So I guessed it was the one I had already found. But on the stone or around it, there were no sign or annything that pointed against the next clue. To find the next clue I had to go on Wynncraft Wiki. There I found all of them but I wasn't sure if i could find the tresure without "activating" or "finding" all of the clues. So I disided to write this and whait for answers. What am I suposed to find. Is it a glitsh or have I just not found the right place.

Pleace help

Thx

**Comment by Trixter313** [comment]
I believe that it puts the clue in chat when you find it, not on an actual ingame sign. Did nothing appear in chat? Also what did it say in your quest book?

**Comment by Moe-Ronickah** [comment]
Trixter, you are correct in that the next clue appears in the chat, and not on any sign.

**Comment by Iceicle** [comment]
Thx for the help. The clue did not apear in my chat the first time but in my qust book.
