### ISSUE TITLE
Purple and Blue Parkour Glitch

### ISSUE THREAD

**Issue by TheSlyMiner** [Wynncraft/Issues#5638]
I was doing the quest Purple and Blue and when it came time for me to do the parkour, I realized that I couldn't do it. The problem is that the glass pane you have to jump on makes my character glitch out. I can't complete the parkour due to this, so I can't complete the quest. This has also happened on other glass panes in the world of Wynn for me. I would greatly appreciate It if something could be done to fix this issue. Thank you,
                                                                                               TheSlyMiner

**Comment by Trixter313** [comment]
What version of Minecraft are you using to play Wynncraft? We recommend using 1.8.9 and anything higher is at the user's own risk because it causes a bunch of issues of it's own. If you're using anything higher, please try 1.8.9 and let us know if it helps at all. Thanks!

**Comment by TheSlyMiner** [comment]
Switching to 1.8.9 worked. Thank you so much. :D

**Comment by Trixter313** [comment]
Glad to hear =)
