### ISSUE TITLE
Green Skinned Trouble - Stuck in a wall

### ISSUE THREAD

**Issue by Freemiiner** [Wynncraft/Issues#5639]
After obtaining the fire axe from the boss fight, I was teleported out of the arena via the obsidian/coal thing thats always there. But it teleported me into a wall or something (i can hear water) at the coordinates: -1866 28 -4899
I am unable to move, use my horse, use teleport scrolls, or even use my ability to get out. Could I please be teleported out to a safe place  or have the blocks around me removed so I can use a teleport scroll?
I will leave my computer on overnight if that helps any?? Thank you!!

**Comment by Freemiiner** [comment]
My ign is: Freemiiner

**Comment by Trixter313** [comment]
I'm not sure if you fixed it or not because you closed the report but just in case it was accidental, you can use /kill with 3+ soul points to get out of most places. =)
