### ISSUE TITLE
Silverfish Dongeon broken

### ISSUE THREAD

**Issue by Raeigor** [Wynncraft/Issues#5640]
Hello, Raeigor again.
2 majors bugs in 2 days i love it !

Anyway i'm in silverfish dongeon wich is broken : the redstone system is broken himself.
There is no Tripwire hook so the system is no active.

In total in 2 days I lost 68 Emeralds Blocks for nothing (reset scroll that bug 2 times but the first was free with the quest and silverfish key but i'm not able to go to the boss) 

I'll transfert you a picture of it.

![image](https://cloud.githubusercontent.com/assets/20754920/17294631/4fa01734-57f8-11e6-9243-61138e639403.png)

Thanks for your attention and I apologise for my bad English i'm French.
Raeigor

**Comment by Trixter313** [comment]
Is it still broken if you switch to a different world? Sometimes things get temporarily broken on one server but get fixed when that server restarts.

**Comment by AckroWynn** [comment]
Any dungeon-related issues will be solved with the next update, seeing as we have reworked them.

@Trixter313

**Comment by Raeigor** [comment]
I will test next time thank you ! Hope for the new update to come soon !
