### ISSUE TITLE
Item bomb glitch

### ISSUE THREAD

**Issue by xGenji** [Wynncraft/Issues#5641]
Alright,There was a item bomb party on detlas on my server.Then I though I could drop another one at the same time too!But the server do not allow me to do that.When I want to drop the item bomb after that item bomb ended(From other players),I realised i only got  1 left instead of 2.I can only give the screenshot that the server do not allow me to throw an item bomb.I understand this proof nothing but you guys(Staff) could try throw 2 item bomb by 2 person at the same time and see if one of them lose her/his item bomb with this glitch.If this glitch happen to you guys,can I have my item bomb back?Since it is important to him as it count as real life money
![2016-08-02_00 46 50](https://cloud.githubusercontent.com/assets/20777531/17302294/1ef06a98-584e-11e6-8071-e64cd2125498.png)

**Comment by Moe-Ronickah** [comment]
Hi!  Thank you for letting us know about this, however, we do not work with issues of real life money.  Please send an email to support@wynncraft.com, with all of the details.  They have access to all of the tools necessary to help you with this.
