### ISSUE TITLE
Inventory Glitch...

### ISSUE THREAD

**Issue by YahyasFinalForm** [Wynncraft/Issues#5642]
I lost a white horse when I logged on! I KNOW i had it before logging off, but when i got on, IT WAS GONE! Please help me!

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so we can't do anything to return the horse if it disappeared.

You can try to click the empty spaces of your inventory to see if it is hiding in one.

Also, we suggest you change the drop hotkey to something other than q that you will be less likely to accidentally press as it could have accidentally been dropped.
