### ISSUE TITLE
Quest item glich?!

### ISSUE THREAD

**Issue by SirQuantumNarwal** [Wynncraft/Issues#5645]
when i was high enough level to do wynn excavation site b i was really happy but then i realised i didnt have the crystal shard which is a quest item so you are unable to drop it or get rid of it. i checked my echest but it isnt in it so now i am unable to finish all the quests someone please help me

**Comment by Trixter313** [comment]
If you don't have it in any inventories you should try using the command /fixquests to return the quest item. Let us know if that helps at all =)

**Comment by SirQuantumNarwal** [comment]
thankyou so much it worked perfectly ^^ 

    On Monday, August 1, 2016 8:25 PM, Nick Cipriani <notifications@github.com> wrote:
 

 If you don't have it in any inventories you should try using the command /fixquests to return the quest item. Let us know if that helps at all =)—

**Comment by Trixter313** [comment]
Glad to hear!
