### ISSUE TITLE
I got glitched in a block.

### ISSUE THREAD

**Issue by PatheticKoala** [Wynncraft/Issues#5646]
I need help at X: 1023 , Z: -1505  , please help, I am stuck in a fence, and can't teleport. Also, I reloged 3 times and restarted my MineCraft twice.
![45e8d674744930bfc6b5074dc162180fcee25a01b80ca44ac6 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/20786698/17317220/173a6fa6-5830-11e6-953e-fc9f2113e6af.png)

**Comment by Trixter313** [comment]
You can use the command /kill with 3+ soul points to get out of most places. =)
