### ISSUE TITLE
Sudden performance decrease

### ISSUE THREAD

**Issue by Cristian8987** [Wynncraft/Issues#5647]
So when i  join wyncraft with liteloader mod i play for 1 min then the performance starts decreasing all the way to 1 fps slowly. Idk why is this happening. Ive noticed this issue only in wyncraft not other servers

**Comment by Trixter313** [comment]
What version

**Comment by Cristian8987** [comment]
forge 1.8 with liteloader mod

**Comment by Cristian8987** [comment]
plz help me

**Comment by Cristian8987** [comment]
no using vanilla im fine but i need liteloader for spell macros. It works on any other server appart from this one

**Comment by Moe-Ronickah** [comment]
Try using MC 1.8.9, with Forge for 1.8.9, with LiteLoader for 1.8.9.  I'm using that combination, and it works perfectly well.

**Comment by Cristian8987** [comment]
Ill try

**Comment by Cristian8987** [comment]
cand do it because macros mod doesnt work on that

**Comment by Trixter313** [comment]
Unfortunately we can only really help out when the player is using 1.8.9 because using other versions causes issues in itself. 

The only thing I can suggest is try using another macro mod that does support 1.8.9. Here is a link to one that I found: https://minecraft.curseforge.com/projects/macrokey-keybinding/files

**Comment by Cristian8987** [comment]
That mod doesnt recognise my mouse buttons and i cant do spell macros just command ones

**Comment by ColinRioux** [comment]
I'm sure there is an older version of your macros mod that you are using. I'd go to the developer page. If you are using the one through lightloader, as shown here: http://www.liteloader.com/mods, I would download the 1.8 version, and try again. 

http://www.liteloader.com/mod/macros <== This does exist btw.
