### ISSUE TITLE
Health won't regenerate?

### ISSUE THREAD

**Issue by Eytherix** [Wynncraft/Issues#5648]
I'm trying to finish quests and stuffs, that sorta of thing and I noticed that my health wasn't regenerating. I drank a 3/3 +150 health potion and it regenerated a bit of my health. I then realized that I was actually losing my health slowly. I dropped from 638 to 49 within 10 minutes. I've already tried dying to see if it would stop after I respawned, which it didn't then tried switching worlds and that didn't help either. I just want to play the game but I'm afraid I'll lose my soul points and all my stuff.

**Comment by EricSalata** [comment]
Do you have negative health regen on your weapon and or armor?

**Comment by Eytherix** [comment]
Thank you so much! I never thought of that, I only paid attention to the +200 health on it.
