### ISSUE TITLE
Reclaiming the house not giving enough emeralds

### ISSUE THREAD

**Issue by xGoldenBlade** [Wynncraft/Issues#5650]
So I was doing the reclaiming the house quest and when I completed it it said "+6144 emeralds" but in reality it only gave me 2588 emeralds(42 blocks).
![2016-08-02_17 40 54](https://cloud.githubusercontent.com/assets/20805370/17350118/87fc80c8-58d8-11e6-853b-dbe1e006fccd.png)
![2016-08-02_17 39 59](https://cloud.githubusercontent.com/assets/20805370/17350121/9139bd36-58d8-11e6-97a5-5c8a0c6aacb2.png)

**Comment by Moe-Ronickah** [comment]
Thank you for reporting this.

@Villageacules , would you take a look into this quest, and see if the quest rewards are supposed to be 6144 or 2588 emeralds, please?

As to the amount of emeralds lost, if any, we can't do anything about it.  I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency.

**Comment by Villageacules** [comment]
I'll take a look at it tonight, on vacation in LA I'll be back to apartment in a few hours.

**Comment by Moe-Ronickah** [comment]
No rush.  Enjoy your vacation, first and foremost.

**Comment by AckroWynn** [comment]
@Moe-Ronickah This is one of the classical cases of when people receive a lower amount of emeralds than they sould've. This quest does indeed give one stack and 32 EB in reward.

**Comment by Moe-Ronickah** [comment]
Thanks for the confirmation, Ackro.

@xGoldenBlade , I'm sorry that this bug hit you, however, I'm glad that you let us know about it.  Unfortunately, this bug is still alive and well.

**Comment by Villageacules** [comment]
@Moe-Ronickah Looks to be already fixed, closed.
