### ISSUE TITLE
Broken Chestplate

### ISSUE THREAD

**Issue by ComeHere11** [Wynncraft/Issues#5651]
![2016-08-02_23 28 07](https://cloud.githubusercontent.com/assets/20807625/17352903/d81f1248-5908-11e6-8109-742745c845f1.png)
Broken chestplate

**Comment by EricSalata** [comment]
Were you away from wynncraft for a long time?

**Comment by ComeHere11** [comment]
My friends chestplate and he was away for a long time

**Comment by Trixter313** [comment]
This was something that happened to a lot of items with special characters in their name and should be fixed now and only effect older items. We reccomend just throwing out the item if you don't want it and finding something else to use. It shouldn't happen with any new items you get.

If you'd like to look at the original issue for this, you can find it here: https://github.com/Wynncraft/Issues/issues/3175
=)
