### ISSUE TITLE
Help , my 44lv  archer acc. was lost !!!!!

### ISSUE THREAD

**Issue by Sushiee** [Wynncraft/Issues#5654]
Name : Sushie_
Class  :Archer
Level : 44
My acc was  disappear from my /class today , but i did nothing , help me plz , thank you

**Comment by Trixter313** [comment]
Did you see a message pop up ever that asked if you wanted to delete the class?

**Comment by Sushiee** [comment]
no , i did nothing and my class have disappear

**Comment by Moe-Ronickah** [comment]
Are you absolutely certain that you did not accidentally right-click on archer in the class selection box?  You would have seen a box pop up with a green check mark and a red X.  Are you certain that you don't remember seeing that?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
