### ISSUE TITLE
Wynncraft horse bug

### ISSUE THREAD

**Issue by Davidoff142** [Wynncraft/Issues#5655]
When i playing wynncraft i went to llevigator and i bouth a weapon and my horse was disapered and i dont have money to buy another 2 houses to evolve to black horse. please help

Davidoff142

**Comment by Trixter313** [comment]
You can try clicking the empty spaces of your inventory to see if it's hiding in there. It's also possible that you accidentally dropped it so we suggest changing your drop key to something you're less likely to press.

Wynncraft has a strict no refunds policy so unfortunately we can't give you any items back.
