### ISSUE TITLE
nerf ranged mobs

### ISSUE THREAD

**Issue by TheEpicCorgi** [Wynncraft/Issues#5656]
the ranged mobs shoot way to fast for my warrior to attack. i struggle big time in the ToA when i have to do a room with 10 ranged mobs attacking me non stop

**Comment by Trixter313** [comment]
You can post suggestions here https://forums.wynncraft.com/forums/general-suggestions.69/
Thanks! =)

**Comment by Moe-Ronickah** [comment]
This is an issue that the admins and developers are aware of - it's been mentioned on the forums.  With that, you can bet that it is on the table to be worked on.  When?  I don't know.  In the mean time, you'll have to level up your warrior to be able to handle the mobs.
