### ISSUE TITLE
Vanilla items from way back

### ISSUE THREAD

**Issue by djbil** [Wynncraft/Issues#5657]
Hey, i have some vanilla items from way back in the old days. i have
11 smooth stone
1 lime wool

They have no effect but they look like weapons.

Is this bannable?
I dont know what to do with these

**Comment by Trixter313** [comment]
You can simply drop them in the trashcan located in the Deltas or Cinfrass bank to get rid of them.

**Comment by Moe-Ronickah** [comment]
Take Trixter's advice = dispose of them properly, where no one else can pick them up.  Vanilla items are bannable.
