### ISSUE TITLE
Broken Threads on Forums - Cant read Changelog #3 

### ISSUE THREAD

**Issue by Chri630** [Wynncraft/Issues#5659]
So I'm trying to read the new changelog that came up today but I can't get to it. Is it because alot of people are trying to access it or what? Either way I thought I would report it just incase something was wrong. 
![image](https://cloud.githubusercontent.com/assets/16396890/17411303/dac7fa8a-5a45-11e6-8af3-5994ce2e9c4c.png)

**Comment by Trixter313** [comment]
It seems to be an issue right now that is caused by a staff member commenting on a thread and it doing this. Hopefully will be resolved soon.

**Comment by Moe-Ronickah** [comment]
It's the Content Team bug, coming back to haunt us.  All we can do is wait for an admin to fix it.
