### ISSUE TITLE
Lost my "Bob's Mythic Spear" during a server crash - Toxicokwak

### ISSUE THREAD

**Issue by Toxicokwak** [Wynncraft/Issues#5660]
Hello.
I come to report an issue I have encountered right after Gavel's update. There were a lot of people and servers were quite full, and when I logged in for the first time after the update, I quickly identified my items. When I came to my newly acquired "Bob's Mythic Spear", the server crashed and it disappeared. Is it possible for me to restore it, or for the team to refund me another one ?  Unfortunately, I don't have any screenshot of me with this weapon before it occured :confused:

I will be really thankfull for a solution to my problem.

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so unfortunately we can't do anything to return the item.

The only bit of advice I can give is to change your drop key to something your less likely to accidentally press. That might not have been what happened here but it can help prevent it from happening at all. =)
