### ISSUE TITLE
Quest Chat Bug

### ISSUE THREAD

**Issue by SpyWatcher** [Wynncraft/Issues#5662]
For some reason I clicked on the quest npc but they won't say anything. I tried to do it with other classes but it works.
![giphy](https://cloud.githubusercontent.com/assets/20846639/17417209/f8d1f6ba-5a46-11e6-92c6-f7fb5750bc1b.gif)

**Comment by Trixter313** [comment]
What does it say in your quest book?

**Comment by SpyWatcher** [comment]
It says this
![2016-08-04_14 13 50](https://cloud.githubusercontent.com/assets/20846639/17418505/ba522458-5a4d-11e6-910c-8e90b695299a.png)

**Comment by SpyWatcher** [comment]
But I already got the dusty will
![2016-08-04_14 14 49](https://cloud.githubusercontent.com/assets/20846639/17418537/e1922c98-5a4d-11e6-9167-52003082312e.png)

**Comment by Trixter313** [comment]
If you have the will all you should have to do is bring it back to Sayleros in Detlas

**Comment by SpyWatcher** [comment]
ok thx

**Comment by Trixter313** [comment]
Let us know if talking to Sayleros fixes the issue =)

**Comment by SpyWatcher** [comment]
it works

**Comment by Trixter313** [comment]
Yay, great to hear!
