### ISSUE TITLE
Wynncraft excavation problem

### ISSUE THREAD

**Issue by HellGoat2** [Wynncraft/Issues#5663]
So i had my 2 yellow crystal after site a, but when i started site b, i quitted RIGHT BEFORE the quest started, so now i don't have a yellow crystal anymore. I went back to site a to kill the mumie and get another one but i'm not sure if it will work, because its not a quest item but an untradable item. If there is anyway i can get it back, plz send me a message on my email so we can meet up and discuss it.

**Comment by Trixter313** [comment]
If going through A again and using that shard doesn't work, does using the command /fixquests help at all?

**Comment by HellGoat2** [comment]
I did not try /fixquest

**Comment by HellGoat2** [comment]
It worked, ty

**Comment by Trixter313** [comment]
Great, glad to hear =)
