### ISSUE TITLE
(EDIT) i LEARNED /kill))HELP STUCK AT -10043.5, 47.5, -10687.5 near the spider boss door 

### ISSUE THREAD

**Issue by the-brothers1** [Wynncraft/Issues#5664]
so i was just grinding my 46 skeleton keys so I can get spider keys, when I teleported into this random spot where im on a half slab and I got my head in a block -.- I cant teleport out with a scroll or a teleport spell... Is this the end of my journey of being a wizard? find out next time on wyncraft mage playthrough

I cant upload a file so here is a Link (my skin is link from LOZ)

C:\Users\Perry\AppData\Roaming\.minecraft\screenshots\2016-08-05_01.58.54.png

C:\Users\Perry\AppData\Roaming\.minecraft\screenshots\2016-08-05_02.28.40.png

and finaly

C:\Users\Perry\AppData\Roaming\.minecraft\screenshots\2016-08-05_02.30.09.png

**Comment by the-brothers1** [comment]
help me...

**Comment by the-brothers1** [comment]
I learned about /kill so nvm this post

**Comment by ColinRioux** [comment]
@Moe-Ronickah Please close.
