### ISSUE TITLE
The WynnExcavation Site A quest impossible to complete upon server reset.

### ISSUE THREAD

**Issue by mattp12** [Wynncraft/Issues#5666]
Hello,

I have started the quest "The WynnExcavation Site A", and the server I was in was also restarting. I did not notice this until I saw the countdown from ten. What is happening is that i brought the decrypted message back to Vade, but he wants me to go back up to the tents to Tesha to decrypt it... but it was already decrypted... here are some screenshots... as you can see in one of them, Tesha is wanting Vade is look at the decrypted message, but when I went back down, we wanted me to go back. The server was restarting when I talked to Vade after it was decrypted, if that helps. Help is appreciated. :)
![2016-08-05_16 25 11](https://cloud.githubusercontent.com/assets/8071273/17449739/750c28b6-5b2a-11e6-96d0-fdbd341e990e.png)

![2016-08-05_16 25 40](https://cloud.githubusercontent.com/assets/8071273/17449726/68e5e068-5b2a-11e6-971a-a593329f9f22.png)

![2016-08-05_16 25 04](https://cloud.githubusercontent.com/assets/8071273/17449711/4fe94870-5b2a-11e6-958e-8c224c31a0a4.png)

**Comment by EricSalata** [comment]
Try /fixquest

**Comment by mattp12** [comment]
Ah, I forgot that was a command. Thanks! I will try that :)

**Comment by ColinRioux** [comment]
Please close @Moe-Ronickah or @Trixter313

**Comment by Trixter313** [comment]
Just to make sure, did /fixquests work for you @mattp12 ? Thanks!

**Comment by Moe-Ronickah** [comment]
I am going to safely assume, having not heard back from the op, that /fixquests worked.
