### ISSUE TITLE
Stuck at the 0,0 landing

### ISSUE THREAD

**Issue by NakedSnakeMIA** [Wynncraft/Issues#5667]
So i recently joined, and everytime i join a server it spawns me in a box with a villager, a sign, and a chest not letting me choose a class or anything. Sometimes it makes me fall into an endless void with no chance of dying. Ive tried using 1.8.9, ive tried the resoruce texture pack re-download. The only thing i know is that the sign is Signed by -Salted. So please help me here!!!

**Comment by Trixter313** [comment]
Could you post a screenshot of you in the box to give us a little more info? Also, do you have your ingame items on your player while in the box? And do you have auto join turned on? Thanks!

**Comment by ColinRioux** [comment]
Also, could you send along your client information? Thanks.

**Comment by AckroWynn** [comment]
He must've been teleported to the 0,0,0 coordinations, where we have a lot of signs.
@NakedSnakeMIA please do perform /kill, if possible.

**Comment by frostedflakes123** [comment]
This happens to me too except the texture pack loads and I just fall straight into the void without being teleported anywhere and the class selection gui doesn't come up

**Comment by ColinRioux** [comment]
Make sure you're using 1.8.9. However, if you are, try uninstalling any
mods. If that doesn't work, could you give me a work up of client
information? Thanks!

**Comment by Moe-Ronickah** [comment]
This issue is still on the books, and we are still looking for a solution.

**Comment by Moe-Ronickah** [comment]
@NakedSnakeMIA , we've had a lot of updates since you first tried to join the game.  Would you try to join, again, please, and let us know if you can or cannot join in?

**Comment by Moe-Ronickah** [comment]
I have now found out that this is not a feature, however, it's not exactly a bug, either.  It can happen when there are connection issues between the player and our server.  The landing location, ~0,0,0 , is an effect of the way that Wynncraft is made.  It is highly unlikely that this will ever be fixed, because of the complexity of fixing it.
