### ISSUE TITLE
class glitched

### ISSUE THREAD

**Issue by omintrevor** [Wynncraft/Issues#5669]
when i signed in i had nothing but 3 starter archer class bows please help

**Comment by ColinRioux** [comment]
@omintrevor Please delete your previously created issue. Having duplicates won't force anyone to respond any sooner. 

When was the last time you logged on to Wynncraft besides today? 
What level are you?
And, what's your ign?

Thanks

**Comment by omintrevor** [comment]
i logged on about 4 hours before the glitch thing.I'm level 55. ign-ominous_trevor

**Comment by Moe-Ronickah** [comment]
@omintrevor , I'm going to take a guess here and suspect that you left the game, while you were in a city, and went AFK.  The three starter bows tells me that you died three times.  One your first death, at zero soul points, you dropped everything.  When you re-spawned, you received one starter bow.  Then, each time that you died, you received another starter bow.

Don't AFK anywhere, unless you are up, high, in a building.
