### ISSUE TITLE
Silverfish Dungeon Stage 1 is not working

### ISSUE THREAD

**Issue by AmunRa34** [Wynncraft/Issues#5670]
I recently tried to start my silverfish dungeon. At the first stage, no matter how many emeralds I drop into the holes in the snakes' mouths, or items onto the pressure plates in the parkour, the diamond door won't open!

**Comment by Trixter313** [comment]
Does it work if you try doing it on another world?

**Comment by omintrevor** [comment]
theres more then just the snakes mouth u have to do  total 3 pressure plates 2 snake mouths

**Comment by AmunRa34** [comment]
I logged out and tried it again, and the dungeon worked. Thanks to you all for your help!
