### ISSUE TITLE
Inaccessible Chest Gregg'r

### ISSUE THREAD

**Issue by WInf9Kieran** [Wynncraft/Issues#5671]
At the coordinates -1850 24 -4909 is a chest that has a block over it. It's a high tier chest. I found this while doing the Quest Green skinned trouble

**Comment by Moe-Ronickah** [comment]
Thank you for reporting to this us.

@AckroWynn 
@Villageacules

**Comment by AckroWynn** [comment]
@Moe-Ronickah I checked in our chests.yml, and it seems to already be solved!

**Comment by Villageacules** [comment]
Already personally fixed. Closed.
