### ISSUE TITLE
crash bug?

### ISSUE THREAD

**Issue by deathsbreath** [Wynncraft/Issues#5672]
every time I connect to a world my game crash even when I restart my compter and minecraft

**Comment by Trixter313** [comment]
What version of Minecraft are you using to play? We reccomend using 1.8.9 for Wynncraft; If you're using something else try using 1.8.9 and see if it helps.

**Comment by ColinRioux** [comment]
If it turns out to not be the version, can you please send me both your minecraft client information (i.e, what version, how much ram, settings, etc.) as well as your computer setup.

Thanks

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
