### ISSUE TITLE
Green Skinned Trouble

### ISSUE THREAD

**Issue by ThePyromaniac** [Wynncraft/Issues#5675]
I've attempted the secret door within the quest Green Skinned Trouble and when I do the lights successfully, and jump in, I get teleported out with this in the chat: 
![bdfe619828ddbdfb883fff7e6670a282](https://cloud.githubusercontent.com/assets/19894985/17460955/4f07eae2-5c38-11e6-9137-018f9bcd9954.png)

**Comment by ThePyromaniac** [comment]
I jumped in, and am now stuck inside the hole, continuously being teleported into the wall spamming "null"

**Comment by ThePyromaniac** [comment]
Server 8, and cannot leave, as there's mobs nearby and cannot use a scroll.

**Comment by ThePyromaniac** [comment]
Used /kill and am now out.

**Comment by Moe-Ronickah** [comment]
You had to have skipped a step in the quest.

**Comment by ThePyromaniac** [comment]
I did not. I followed everything I was supposed to do, via the Wiki, down to a T.

**Comment by ColinRioux** [comment]
What does your quest book say? 
If it tells you to return to the final NPC, then try `/fixquest`
