### ISSUE TITLE
Can't Leave Guild

### ISSUE THREAD

**Issue by tomisdaman27** [Wynncraft/Issues#5676]
BUG: Stuck in my guild as the leader, cannot pass on leadership to others in order to leave. /guild leave takes my 3 soul points but keeps me in Guild. Guild name; Fishers of Wynn. Please disband the guild, thank you. Also, some names in the guild show up twice.

**Comment by Moe-Ronickah** [comment]
Duplicate of #3665 .  Please read and follow that issue for more information.

**Comment by tomisdaman27** [comment]
3665 is unsolved, my report is unsolved and still awaiting an email from support. I just need my guild disbanded.

**Comment by Moe-Ronickah** [comment]
Yes, we know that guilds are still broken.  Read #3665.  All of it.
