### ISSUE TITLE
Guild Bug, Cant leave

### ISSUE THREAD

**Issue by Stormyeriki** [Wynncraft/Issues#5677]
Ive got quite some problems with leaving my guild, im a recruiter and since a changed name... well... its impossible to change guild! Id be thankful if you could like get me off the guild, like kicking me or else.

Thanks, Stormyeriki

PD: My guild is Dah Epic Goats (lvl.29)

**Comment by Moe-Ronickah** [comment]
Duplicate of #3665 . Please read and follow that issue for more information.
