### ISSUE TITLE
Server-join-gui is invisible

### ISSUE THREAD

**Issue by Grauly** [Wynncraft/Issues#5678]
Sometimes i want to join wynncraft servers, i cant choos cause there are no clay-things, the rest of the gui is still there

**Comment by Trixter313** [comment]
This is a currently known issue with certain lobbies. As a temporary fix, if you switch to another hub you should be able to find anotherr that is working correctly.

**Comment by Moe-Ronickah** [comment]
/server, /hub, /lobby <= any of those should work
