### ISSUE TITLE
Item bugged away

### ISSUE THREAD

**Issue by Grauly** [Wynncraft/Issues#5679]
MY legandary bow bugged away:
i sat in my boat, dropped my bowun wanted, hopped out of my boat, got dislocated, i searched for 10min, diddnt found it. can you help me?
The bow was called "Thunderstorm"
Thanks.

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so there's nothing we can to do return the item. To prevent something like this from happening again, I'd suggest you change your drop key to something you're less likely to accidentally press.
