### ISSUE TITLE
I lost my class archer level 34 ....

### ISSUE THREAD

**Issue by XxAndres19xX** [Wynncraft/Issues#5680]
My name is enderboss19, two days ago I lost my class and donot why. What happened was that dead and I take the server. When I returned to get my class was not

**Comment by Trixter313** [comment]
So are you saying that you lost your levels and your items or just your items?

**Comment by XxAndres19xX** [comment]
Perdi todo, el nivel, mis items y nose el porque

**Comment by XxAndres19xX** [comment]
I lost everything, level, and my items donot why

**Comment by Trixter313** [comment]
It sounds like you may have accidentally deleted the class. Do you remember seeing a message asking you to confirm or not confirm deleting your class?

**Comment by XxAndres19xX** [comment]
I did not at any time I got a message. At that time lag and had dead. Out the server and when I enter my class was not. I know that with right-click the account is deleted

**Comment by Moe-Ronickah** [comment]
If you have lost a class, and haven't fallen for a scam, then please read this post, here, about what may have happened to you.

[Unintentional Deletion of a Class](https://forums.wynncraft.com/threads/unintentional-deletion-of-a-class.138254/l)
