### ISSUE TITLE
Lost a Good Item Due to Server Glitch

### ISSUE THREAD

**Issue by Fahdypoo** [Wynncraft/Issues#5684]
Around two weeks ago, back when I was level 60, I was taking off my Shameful Greeves which I got from doing the Iron Heart Pt 2 quest.  The server was lagging, and when I took them off and put them into my inventory, they just disappeared. I checked to see if I dropped them and they weren't there - it was due to the server glitching. Worst of all, the Shameful Greeves were max loot bonus (39%). Someone told me today that you can actually report this and get them back, so here I am reporting the situation (he said you may need a screenshot, however I had only been on the server for around 2 weeks then - I was very new and didn't know much). I would really appreciate it if I could get my Shameful Greeves back. Thank you. P.S. My username is Glamazon_

**Comment by ColinRioux** [comment]
Since it's a quest item, try `/fixquest`

**Comment by Fahdypoo** [comment]
I did, it doesn't work though. /fixquests only gives back quest items, for example: Bobs Crushed Soul. Is there any other solution?

**Comment by ColinRioux** [comment]
If it is not a Quest Item:

Unfortunately, this follows the strict no refund policy (https://forums.wynncraft.com/threads/have-you-ever-lost-your-items-in-game-and-want-to-get-them-back.143196/#post-1593529). 

Otherwise: @Moe-Ronickah or @Trixter313 can elaborate.

**Comment by Fahdypoo** [comment]
Even though if it was the servers fault for being buggy? RIP

**Comment by ColinRioux** [comment]
Yes.

**Comment by Fahdypoo** [comment]
Okayyyy
