### ISSUE TITLE
Died And Lost My Weapon (Not losing all soul points)

### ISSUE THREAD

**Issue by kep57** [Wynncraft/Issues#5686]
FIRST OFF - I haven't played for 2 months, so I have no idea if this is a new thing or just a weird bug. 

So I was trying to grind to 84 a bit because I was bored, and I got in a bad spot and died. After I respawned and my Maelstrom was gone from my inventory, all my characters, and my bank. Although I have no proof I asked owenj333 and Meyoko about it and they said they didn't know what was wrong either. Thanks for reading this and I hope everything can be sorted out

**Comment by kep57** [comment]
P.S. My ign is kep57

**Comment by ColinRioux** [comment]
You probably had **3 or less** soul points, thus, when you died, you dropped your items. 

However, what's confusing is that you lost all your characters. I screen shot would be appreciated. 
It doesn't make sense that when you died, that you would lose each of your characters (as it's saved in a database). Are you sure that you didn't delete them, purposely, or that any of your friends have access to your account? 

Meanwhile, the no refund policy still stands, in terms of getting your items back. Your classes, well, @Moe-Ronickah will have more to say.

**Comment by Trixter313** [comment]
@ColinRioux I think they are saying that the Maelstrom disappeared from all their classes, not all their classes disappeared.

@kep57 The most likely scenario is that the weapon was accidentally dropped either by pressing the drop key or while in your inventory. Wynncraft has a strict no refunds policy so there's nothing we can do about the item. The only suggestion I have is to change your drop key to something you're less likely to accidentally press to hopefully prevent something like this from happening again. Thanks!
