### ISSUE TITLE
Lost my DXP

### ISSUE THREAD

**Issue by nms3456** [Wynncraft/Issues#5689]
Someone threw dxp so i tried to triple the xp by throwing another dxp, it said that someone already threw dxp, so my dxp did nothing and it disappeared for no reason. It was supposed to come back to me.
Please fix this bug and give me my dxp back, my Minecraft name is nms3456.

**Comment by Coooldude34u** [comment]
It didnt dissapear for no reason. You tried to make TXP, didnt because thats how wynncraft works.
You will NOT be getting your DXP back. Wynncraft has a no refund policy.

**Comment by nms3456** [comment]
It's not fair, I bought this dxp with money and it's gone doing nothing.

**Comment by ColinRioux** [comment]
@nms3456 You are welcome to contact Wynncraft support (support@wynncraft.com), as you did pay money for it. But no promises anything is done about it.

**Comment by Moe-Ronickah** [comment]
@Coooldude34u , the policy is actually better expressed as  "I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency."

@nms3456 , the no-refunds policy does not apply to items that are purchased through real-world currency.  Those are decided on a case-by-case basis.  As ColinRioux suggested, please contact support@wynncraft.com and describe to them your situation.
