### ISSUE TITLE
Tower of Ascension - Horse Glitch

### ISSUE THREAD

**Issue by Freemiiner** [Wynncraft/Issues#5690]
I was getting bored of grinding to level 60 so I was inventing new ideas to grind faster, so I came up with grinding mobs my level in the Tower of Ascension. Now of course I didn't wish to get hit by the mobs so I just rode my horse around the Lava Imps or whatever they are. When I got off my horse to attack, I glitched through the floor and fell into the void (nice setup of the rooms btw, I could see them all from the bottom :smile: ). Well this happened. Twice. Could you find a way for this not to happen. Thanks :laughing:

**Comment by ColinRioux** [comment]
Please report the coords of the hole here: https://forums.wynncraft.com/threads/community-project-filling-holes-open-2-closed-44.123931/

**Comment by Moe-Ronickah** [comment]
You are not expected to use a horse in ToA.  Doing so may have unintended consequences.  This is not an issue.
