### ISSUE TITLE
Tower of Ascension invite grindd 

### ISSUE THREAD

**Issue by ries01** [Wynncraft/Issues#5692]
I was grinding in the Tower of Ascension on floor 2 level 7 when i saw a guy standing on the fences with the sign on it. that made it so the mobs couldn't hit him and he could grind invite. 

he also had a auto clicker on but i forgot to write his name down. like this they can grind with auto clicker for days and be ad level 100 in no time. 

i hope this will be fixed 
greetings ries01

**Comment by ColinRioux** [comment]
@Villageacules

**Comment by Villageacules** [comment]
Mobs can go over fences this update, making this issue repair obsolete.
