### ISSUE TITLE
Hunger Of The Gerts glitch?

### ISSUE THREAD

**Issue by Coooldude34u** [Wynncraft/Issues#5693]
Im doing Hunger of the Gerts Part II and when im at the captured gert, i try to leave after ive talked to the captured gert and he says ''Talk to gert first! Gert no want to starve here!'' the gert wont let me leave.

**Comment by ColinRioux** [comment]
What does your quest book say?

**Comment by Coooldude34u** [comment]
Yes, it matches. Turn the power off at (cords)

**Comment by Trixter313** [comment]
Did you already turn off the power and talk to the first Gert after you turned it off?

**Comment by Coooldude34u** [comment]
No, you see. Im at the part where you FIRST encounter the captured gert.

**Comment by Coooldude34u** [comment]
Umm. Im a dumbass. I was trying to get out of the main door. not the stairs at the side.

**Comment by Coooldude34u** [comment]
Its all fixed.

**Comment by Coooldude34u** [comment]
Thanks for helping me!

**Comment by Coooldude34u** [comment]
you guys are the best

**Comment by Trixter313** [comment]
Glad to hear it was fixed in the end =)
Have fun with the rest of the quest!

**Comment by Coooldude34u** [comment]
ew
