### ISSUE TITLE
Ocean Mini-Dungeon Bug

### ISSUE THREAD

**Issue by truesurvivor9** [Wynncraft/Issues#5694]
My friend and I tried doing the Ocean Mini-Dungeon and when we arrived at the puzzle, we found that it was bugged. The water doesn't flow down, so it won't activate the door. Here's a video of it:
https://www.youtube.com/watch?v=IsO0gx0v198&feature=youtu.be

**Comment by Villageacules** [comment]
Fixed, closed

**Comment by Moe-Ronickah** [comment]
No, it's fixed on the build server.  It'll be in-game when the map gets pushed next time.

**Comment by Villageacules** [comment]
@rt6yhjyuvy6 It will be fixed when the dungeon gets pushed this update.
