### ISSUE TITLE
Missing Emeralds

### ISSUE THREAD

**Issue by EnderManKing** [Wynncraft/Issues#5699]
I had 51 EB. And it just disappeared. I didn't drop it. But it disappeared.

**Comment by ColinRioux** [comment]
Wynncraft enforces a strict no refund policy (https://forums.wynncraft.com/threads/have-you-ever-lost-your-items-in-game-and-want-to-get-them-back.143196/#post-1593529). Unfortunately, we don't know what happened to your emeralds, and believe me, no one took them. You must've mistakenly dropped them. It happens.
