### ISSUE TITLE
Animal Boss

### ISSUE THREAD

**Issue by beintruder** [Wynncraft/Issues#5700]
On my warrior I can knock the animal dungeon boss out of the area and then I can't kill him, because of this I have to lose 2 soul points and an animal key...
I'm sorry if someone else has made this post, I don't know how to use this website very well.
![2016-08-09_18 43 55](https://cloud.githubusercontent.com/assets/20938729/17539342/3f5d99bc-5e62-11e6-8820-cf339d76c522.png)

**Comment by ColinRioux** [comment]
Pretty sure this is a known issue, right @Moe-Ronickah ?

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3191

It's been fixed internally and will be fixed on the play servers when the next map push occurs. =)
