### ISSUE TITLE
Ocean Mini-Dungeon Puzzle Still Broken

### ISSUE THREAD

**Issue by truesurvivor9** [Wynncraft/Issues#5701]
It doesn't seem like the puzzle in the Ocean Mini-Dungeon has been fixed. The previous issue I posted about this has been replied to, saying it was fixed. However, it still seems like it's broken.
https://www.youtube.com/watch?v=ZmRidP-wVDU&feature=youtu.be

**Comment by Trixter313** [comment]
It's been fixed internally. You should see it on the play server when the next map update occurs. =)
