### ISSUE TITLE
Bug in "The Lost" quest

### ISSUE THREAD

**Issue by DominikGamer** [Wynncraft/Issues#5703]
I lost three of those letters what I need to do the quest. When I write /fixquests
I do not get them back and I can't finish the quest. Please fix bug. Sorry for my bad English.

**Comment by ColinRioux** [comment]
@AckroWynn

**Comment by DominikGamer** [comment]
?

**Comment by DominikGamer** [comment]
?

**Comment by DominikGamer** [comment]
?

**Comment by AckroWynn** [comment]
Can you not simply go back to their spots to pick them up?

**Comment by DominikGamer** [comment]
No, I can't.

**Comment by DominikGamer** [comment]
I cannot continue the quest unfortunately so.

**Comment by AckroWynn** [comment]
Can you try and re-do the quest, following maybe some type of guide? If that does not work, please do respond here.

**Comment by AckroWynn** [comment]
All right. I will make them Quest Items if they aren't already. May I ask, how did you lose them?

**Comment by DominikGamer** [comment]
When I tried to start the quest I don't have enough space in my inventory so I throw 3x64 emerald out.
But the hostile monsters pushed me into the emeralds and I picked up them and I did not obtain the letters because of this.

**Comment by DominikGamer** [comment]
@AckroWynn  Can you fix this bug?

**Comment by AckroWynn** [comment]
Oh, well, that is very unfortunate. It's also odd how /fixquests didn't fix this, because they are indeed Quest Items. 

Well, if you are unable to retrieve your items, you will not be able to finish the quest on this class, unless you get the items from another.

**Comment by DominikGamer** [comment]
:(

**Comment by DominikGamer** [comment]
Is there anybody who can fix this?

**Comment by AckroWynn** [comment]
Sadly, no. Not in your case.
Unless, we re-do the quest in some way, but I don't see that happening.

**Comment by DominikGamer** [comment]
This is very bad news for me. :(

**Comment by AckroWynn** [comment]
Closing due to no eventual fix.
