### ISSUE TITLE
Item Database API does not send a response.

### ISSUE THREAD

**Issue by SliceThePi** [Wynncraft/Issues#5705]
Using the format provided in:
https://docs.wynncraft.com/public/items/
I attempted to query several times over a time period of a few weeks, assuming it was temporary downtime. I've tried the example link, as well as other formats, and each time I try, CloudFlare says something along the lines of:
Error 504 Ray ID: 2d05e854b49a094a • 2016-08-10 19:39:20 UTC
Gateway time-out

**Comment by ColinRioux** [comment]
That is not the API link you should be using. It should be in the format
http://api.wynncraft.com/....
The docs are also significantly outdated. There is a post in the
rules&information section of the forums that has the updated documentation
and the corresponding http queries.

If you have any more API related questions, I suggest contacting me
directly through github or on the forums.

**Comment by ColinRioux** [comment]
Here's a link to the documentation: https://forums.wynncraft.com/threads/wynncraft-public-api.127085/ 

If you need help with http requests, feel free to give me a shout.
