### ISSUE TITLE
cheaper but better potions?!

### ISSUE THREAD

**Issue by war-master-9** [Wynncraft/Issues#5707]
Hi i was getting a potion in olux there was 2 one for a lvl 45 player that healed 560 hp that costed 27 e then there was one for a lvl 50 player that healed 750 hp that costed only 23 e. i know its not big but still :D
![image](https://cloud.githubusercontent.com/assets/20957893/17571878/374576d4-5f0f-11e6-8823-42e60a709f5e.png)

![image](https://cloud.githubusercontent.com/assets/20957893/17571883/41b29318-5f0f-11e6-9d0a-b0d480f064a5.png)

**Comment by war-master-9** [comment]
![image](https://cloud.githubusercontent.com/assets/20957893/17571862/25f13f8a-5f0f-11e6-8655-c3d4732e84a6.png)

**Comment by Moe-Ronickah** [comment]
"It's not a bug, it's a feature."
@AckroWynn or @Villageacules

**Comment by Villageacules** [comment]
I'll bug Salted about it.

**Comment by Villageacules** [comment]
Fixed, closed. Will be pushed this update.
