### ISSUE TITLE
Falling Forever Unable to use commands

### ISSUE THREAD

**Issue by BurnedDesigns** [Wynncraft/Issues#5708]
So I have a friend who was playing and when the server restarted we joined a lobby and he said he was falling and he fell through the world and just keeps falling. We tried to have him use the /kill command but he cant use commands we then tried a staff member teleport him but then he just kept falling still. We are unsure of the issue but we just want to play some wynncraft!

**Comment by Villageacules** [comment]
Are you sure he can't use /kill? Has he tried multiple times? It might be that his agility is high, since all /kill does is do a ton of damage. Because the only way out of situation (as far as I'm concerned, a mod might teleport you) is to /kill.

**Comment by Moe-Ronickah** [comment]
Your friend needs to make this issue report.  An anonymous player cannot be helped with this issue.  Sometimes, I've successfully tped players to me, in game, and gotten them out of this.  Have your friend make a GitHub account, and post his/her issue here, and I can try to get them tped to me.
