### ISSUE TITLE
Bug in the quest : "Grave Digger"

### ISSUE THREAD

**Issue by FantaStar** [Wynncraft/Issues#5710]
Hello, I would like to help with a bug I found on the quest "Grave Digger". I have to give 24 bone meal to continue the quest but after having farmer is 24 bone meal Priest told me to go look for item still unknown to me then that the quest book told me to give the bone meal. Help me !

![2016-08-11_13 57 59](https://cloud.githubusercontent.com/assets/20969650/17588089/ccee15a2-5fcc-11e6-8ee5-6a9e15d01dcb.png)
![2016-08-11_13 58 15](https://cloud.githubusercontent.com/assets/20969650/17588096/df4159e4-5fcc-11e6-8d8a-8225b89f6a1f.png)

**Comment by AckroWynn** [comment]
You are supposed to follow the quest book. The dialogue seems to be messed up, which I think was fixed, and will be out the next update.
