### ISSUE TITLE
Not Gaining Soul Points

### ISSUE THREAD

**Issue by BurnedDesigns** [Wynncraft/Issues#5711]
Title Says it all but to elaborate a little more Ive gone about 10 days already and not gained a single soul point is the max ammount 11 or is that just a glitch because my friend has 15 and when it becomes day time it would say that I get one point but I don't it stays at 11.

**Comment by ColinRioux** [comment]
It depends on your level. This should give you the summary: https://wiki.wynncraft.com/index.php?title=Soul_Points

If you claim you stay at 11, you are probably under level 30, yes? 

Your friend must be higher than level 75?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
