### ISSUE TITLE
Spell casting Right click duplication 

### ISSUE THREAD

**Issue by JackyKit123** [Wynncraft/Issues#5713]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.
Casting spell of RLR/RRR causes an issue which after you finished casting a RLR/RRR spell
the right click is duplicated and you are put into a state of casting 'R _ _ '
this messed up combo sometime, I am not sure if I described it correctly

**Comment by ColinRioux** [comment]
This is a known bug I'm pretty sure @Villageacules

**Comment by Villageacules** [comment]
Spell detection was improved recently with a slightly different system, will be pushed in this update.
