### ISSUE TITLE
Glitched Quest

### ISSUE THREAD

**Issue by Brickmaster5094** [Wynncraft/Issues#5714]
I was trying to do the Lazarus's Pit quest and when I went to turn it in, the water wasn't in my inventory anymore. It's not in my bank, nor a separate character.

**Comment by 0x0000null** [comment]
Try `/fixquests`, it will give you all quest items that you're missing

**Comment by Brickmaster5094** [comment]
Thank you so much, it worked.

**Comment by tigersrule28** [comment]
I did the animal dungeon, and when i used one of my abilities, the boss cow flew out of the arena, and he is not teleporting back and we can no longer damage him. can it be made so the cow also stays within the boundaries?
