### ISSUE TITLE
Typo in /find syntax message

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#5715]
If you type `/find`, the message displayed has a typo:

> Invalid **synthax**: /find [player]

<img width="984" alt="image" src="https://cloud.githubusercontent.com/assets/16504771/17608161/5dfec50c-5fdf-11e6-95a8-7731221ae035.png">

**Comment by AckroWynn** [comment]
This is an admin issue.

**Comment by Villageacules** [comment]
Uhm, it's spelled correctly...

**Comment by Villageacules** [comment]
I've notified Jumla, I'll close when this gets fixed.

**Comment by AckroWynn** [comment]
![image](https://cloud.githubusercontent.com/assets/7467934/17644501/47d76392-6188-11e6-9b57-eb225f3dad5e.png)

**Comment by Villageacules** [comment]
oops, sorry
