### ISSUE TITLE
Flying Is Not Enabled On This Server Keeps Kicking Me

### ISSUE THREAD

**Issue by SoonToBeCanadian** [Wynncraft/Issues#5716]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

I did /lobby and it kicked me for flying when I wasn't. Whenever I try going back on the server, it keeps kicking me until I have to exit out my minecraft. I don't know why, since I don't use hacks.

http://prntscr.com/c4vxjl

**Comment by Trixter313** [comment]
What version of Minecraft are you using? We reccomend using 1.8.9 and using anything else is at the user's own risk because other versions can cause issues in themselves. If you're using another version, try using 1.8.9 and let us know if it helps. Thanks! =)

**Comment by Moe-Ronickah** [comment]
#5289
