### ISSUE TITLE
Missing Objects on the map

### ISSUE THREAD

**Issue by ComputerDude** [Wynncraft/Issues#5718]
So I found a few things missing on the online map.
1. Dead Island has no name.
2. The start of Christmas Chaos, WynnExcavation site C and Tribal Aggression do not appear.

**Comment by Moe-Ronickah** [comment]
Elements is working on an overhaul of the map, so we will have to wait and see what it looks like when it's done.

**Comment by Moe-Ronickah** [comment]
RESOLVED
