### ISSUE TITLE
Escape spell does not work / will not end if you are on the edge of a block

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#5723]
_This bug applies to both the escape spell and the spider jump spell. Only "escape spell" is written for concision._

The escape spell refuses to activate if you are on the edge of a block and there is no block directly below you. Your mana is not used, however the amount of mana required for the spell _does_ increase.

Also, the "escape/spider jump spell state" does not end if you land on the edge of a block. However, note that it _does_ end if the block directly underneath you is close enough to you. In this state, walking is much slower and jumping sometimes causes you to be glitched back down. When the centre of the player _is_ above a block, the spell correctly ends and everything returns to normal.

The issue is that the code (probably) checks for the block underneath the centre of the player, which means that being on the edge of a block causes the code to think that you are in midair, which causes the spell not to activate or end.

**Comment by thecoolkogut4** [comment]
I'm experiencing the same thing while using escape on my hunter.

**Comment by YunoFGasai** [comment]
that's an interesting bug, kinda weird I haven't heard about it before.

**Comment by DebugingLonks** [comment]
I know all about this one ;) 

Landing on a edge of a block checks that you are on a block, if you are exactly on the edge and land (Hold sneak while falling) You will not see the sparks/hear sound (if you are lvl 65+ i mean...) the "Jumping up and down glitching" is the game thinking you are STILL falling even though you are not (Before barriers were added to ToL this happens all the time to me. Well in the training room the archer camping spots...)
