### ISSUE TITLE
Help- stuck in the Secret Library.

### ISSUE THREAD

**Issue by schmooz53** [Wynncraft/Issues#5724]
Is there any way to escape this dilemma? I was entering the Secret Library (on my way to Gundalf) and the pistons reclosed on me. I'm not taking any damage, but I can't use town scrolls and I can't die so I can't escape.

**Comment by schmooz53** [comment]
Edit: Solved it. I was able to suffocate myself by closing out, reopening, and walking into the corner and for some reason, in order to take damage, you must be constantly trying to walk in that corner.

The downside is that it takes forever to kill yourself if you have over 1000 hp and suffocation only takes 4.5 away per second.

**Comment by Trixter313** [comment]
Typing the command /kill into chat with 3+ soul points should get you out. =)
