### ISSUE TITLE
Leveling up

### ISSUE THREAD

**Issue by Sparkler1361** [Wynncraft/Issues#5725]
Hey everyone. So I was farming and on the very brink of getting to level 66. I stopped killing guys for a second, and I levelled up. But, it did not say anything in the chat for me to read and I also do not have the arrow rain on my wynncraft Character. I am a level 66 archer. My IGN is Grarkler. Please fix this soon, as I was really looking forward to the arrow rain. Can someone also tell me what this arrow rain looks like? When I use my shield, it looks like normal and doesn't do anything else. I still got my Skill Points to spend, though

**Comment by Moe-Ronickah** [comment]
Arrow Rain is Arrow Shield, it's just renamed for the Hunter class.
