### ISSUE TITLE
Horse Moving Glitch

### ISSUE THREAD

**Issue by PhungMaster** [Wynncraft/Issues#5727]
For some reason whenever I ride on my horse I randomly go to different locations to where I'm supposed to be. For example i could be at the entrance at Detlas but on my screen I'm in the suburbs on my horse. The problem is that I get attacked from mobs on my real location. My IGN is PhungMaster,

Thanks for your help

**Comment by Trixter313** [comment]
This is usually caused by using an unrecommended version of Minecraft. Make sure you're using 1.8.9 and let us know if that fixes the issue.

**Comment by Moe-Ronickah** [comment]
RESOLVED
