### ISSUE TITLE
BugReport-Quest-WynnExcavation site A

### ISSUE THREAD

**Issue by Jayzomb** [Wynncraft/Issues#5730]
Hello!
The Quest ,**,Wynncraft Excevation Site A**,, is not working, i did it over 5 times an every time i kill the Pharao i get one of these yellow Crystals, but when i want to go out (through this black ,,hole,, or however i gonna call it, it wont work) it says (in the chat) ,,you feel you need to complete something first,, But i did all i should to complete this Quest (i need to do this Quest so I can do the Quest: Wynncraft Exevation Site B) I hope you Guys can Fix this! Thank you for your time.

Jayzomb

![2016-08-13_21 30 04](https://cloud.githubusercontent.com/assets/21012841/17645209/2d6809dc-619f-11e6-882e-b0e4a5a7dc03.png)

**Comment by Trixter313** [comment]
What does it say in your quest book?

I'd suggest doing /kill and going back into the tomb area to get another shard. There is a book update location midair when you drop into the tomb and if the game lags while you go through the area it won't count or update your book, not letting you progress.

Let us know if that helps at all, thanks!

**Comment by Jayzomb** [comment]
The Book says: Go talk to the Lab Assistant Tesh in the tents at
[1082,96,-1799] But i already talked to him. and i killed the Pharao about
10 Times (i have enough shards). Look at the Screens its 100% a Bug. Maybe
you can reset this Quest so I can do it Again?[image: Inline-Bild 1][image:
Inline-Bild 3][image: Inline-Bild 2]

2016-08-14 0:02 GMT+02:00 Nick Cipriani <notifications@github.com>:

**Comment by Trixter313** [comment]
Does typing the command /fixquests into chat return anything for this quest? It seems you've gotten stuck on a part of the quest that glitches for many people. We cannot currently reset any quests.

**Comment by AckroWynn** [comment]
I am still scratching my head, because as far as I can see, the quest is fully functioning. It's very short, and you shouldn't be able to get stuck, yet you do.

**Comment by Moe-Ronickah** [comment]
Type /fixquests.  It has some kind of effect that seems to help in situations like this, even though you many not be missing anything.

**Comment by Trixter313** [comment]
Closing due to no response
