### ISSUE TITLE
Wynncraft Site C

### ISSUE THREAD

**Issue by TesdroMC** [Wynncraft/Issues#5731]
Ok, so I did the quest already and when I tried to give the shard shard to the guy to complete the quest, the shard disappeared and the quest still hasn't completed. Then it says "The Purple Crystal Shard from WynnExavation Site B is required to start this quest." But I already did it, and its still in my quest book saying that its started. I did /fixquest and got the purple shard to give to him but I still can't give the shard to him. Fix this!

**Comment by AckroWynn** [comment]
I'd like you to screenshot your quest book, and redo all of the quest stages you did earlier, to make sure you didn't lag through a region.

**Comment by TesdroMC** [comment]
![2016-08-16_17 35 58](https://cloud.githubusercontent.com/assets/21014826/17720596/07fcf10e-63d8-11e6-8760-2a4f2a58a5ad.png)

**Comment by TesdroMC** [comment]
Thats the last stage, and when I tried to report back to Excavator Placardus, he says that line to start the quest, the needing purple shard part.

**Comment by Moe-Ronickah** [comment]
Please try /fixquests and let us know if that works.  Sometimes it has the unexpected effect of causing some quests to set stages to completed, for some unknown reason.

**Comment by Moe-Ronickah** [comment]
@TesdroMC , did you get this resolved or is it still a problem?
