### ISSUE TITLE
Quest-breaking Bug Memory Paranoia

### ISSUE THREAD

**Issue by tomisdaman27** [Wynncraft/Issues#5733]
My account name is "Jaymon"

Initially the problem was that I'd get stuck in Stage 20 of the quest, and I couldn't bring the Master Key to the room. I could get the Master Key fine, and my quest book said "Bring the key to the Master Bedroom.". I was definitely at the correct door, but it did not have a Quest NPC tag, and I couldn't feed it the Master Key. 

I've tried the following:
- Logging out and logging back in
- Suiciding and running back
- Doing each step of the quest again
- Changing wynncraft servers
- Moving around near the door to trigger the quest update.

After I tried doing each step of the quest again, I ended up at the point where the Master Bedroom was wide open, yet I was still stuck at Stage 20. I desperately need help in completing this quest, thank you!

**Comment by tomisdaman27** [comment]
Any help?

**Comment by Trixter313** [comment]
I'd suggest looking at videos of others doing the quest and try to replicate what they do. It sounds like you are just missing a quest trigger, but I'm not sure where.

**Comment by ColinRioux** [comment]
There is a certain place on the map that triggers the quest npc tag (I've had the issue). It's not necessarily near the door, but I think it's along one of the walls. I'd watch a video like @Trixter313 said. 

It's not bugged / broken, you probably just went the wrong way to the door.
