### ISSUE TITLE
missing virgo

### ISSUE THREAD

**Issue by Mattyboy84** [Wynncraft/Issues#5734]
when i was loot grinding i found legendary boots 96-100 when i id it it was a virgo with 3/4 mana 75 reflection and 70 thorns and about 55 exploging (it was close to to that i dont remember i just got it when it left), then my game froze and i disconnected due to a server java error when i got back on it wasnt in my inventory i believe this isnt my fault and i would like a new virgo with stats close to these or 30le as compensation ;p ty
![2016-08-14_08 52 13](https://cloud.githubusercontent.com/assets/20701784/17648085/5fd90f44-6201-11e6-90cf-341a43f6a16a.png)

https://gyazo.com/ab539d5d275737e8e099ab2674687f28

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so we can't do anything for the item. Because this appears to have been a one time weird connection issue, there isn't really much we can fix either.
