### ISSUE TITLE
Iron Heart II Broken :(

### ISSUE THREAD

**Issue by Charliebubblegum** [Wynncraft/Issues#5735]
So i was doing iron heart and got the rope from daxe and i tied the guy up then i got kicked for no reason :( then i came back on and my quest book didnt update and i cant go in the factory even with the helmet on PLZ FIX THIS SOON... cause i really wanna do this quest :P

**Comment by Trixter313** [comment]
Does using the command /fixquests return the rope?

**Comment by ColinRioux** [comment]
You should do what @Trixter313 said, but do you even have the helmet?

**Comment by Charliebubblegum** [comment]
yes I do

**Comment by Charliebubblegum** [comment]
ok ill try do /fixquests

**Comment by Charliebubblegum** [comment]
OMG it worked thnx so much
