### ISSUE TITLE
Quest Glitch

### ISSUE THREAD

**Issue by Celsonic** [Wynncraft/Issues#5736]
![2016-08-14_19 40 13](https://cloud.githubusercontent.com/assets/21028327/17652889/f1d0435e-6256-11e6-8460-932844fc1673.png)

It seems like I have the quest finished, however it does not say it in the book.

**Comment by Trixter313** [comment]
Cook Assistant is the quest that involves the cook, not Potion Making. https://wiki.wynncraft.com/index.php?title=Cook_Assistant

**Comment by Celsonic** [comment]
Sorry Kinda Screwed up there thx :D
