### ISSUE TITLE
MY BLACK HORSE IS GONE :(

### ISSUE THREAD

**Issue by GinjaNinja2112** [Wynncraft/Issues#5737]
PLEASE HELP ANY WYNNCRAFT ADMIN! I logged on my minecraft account today, GinjaNinja2112, and my black horse was gone! I logged on yesterday and it was there, i used it to travel, but now its gone! PLEASE HELP!

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so we can't do anything about the lost item but it sounds like the horse was accidentally dropped. To prevent something like that from happening again, we suggest changing your drop hotkey to something you're less likely to accidentally press.

**Comment by Moe-Ronickah** [comment]
1- If your drop key is still "Q", change to something far away from that area of your keyboard.
2- Never log out while still riding a horse, if you did.
