### ISSUE TITLE
Frost Bitten quest glitch

### ISSUE THREAD

**Issue by SirFoxIII** [Wynncraft/Issues#5738]
I went and got the lava for *I don't remember his name* and he said go to give the bucket to Alein so I went over and talked to him but he didn't say anything so i'm stuck.

**Comment by Trixter313** [comment]
What does it say in your quest book?

**Comment by SirFoxIII** [comment]
Obtain 8 lava from the spring and return to Alein with the bucket.

**Comment by Trixter313** [comment]
I'm assuming you figured out the problem since you closed the issue?
