### ISSUE TITLE
Soul Points

### ISSUE THREAD

**Issue by WynncraftRyc** [Wynncraft/Issues#5739]
Yesterday, I was doing the quest masterpiece, and died sometime. I finished the quest and afked at Caissop's. I looked at the screen to check for mobs, and in order i saw the place night - day - night. I gained 2 soul points there. I started Death Whistle, and died while going to the leaves. I spawned in Olux with no low soul points messages. I went back there and died again and lost my items. I got confused and didn't look at the soul points because of the lack of the message.

Ps: i know that there is no refunds.

**Comment by Trixter313** [comment]
So what part is the issue you're reporting here?

**Comment by ColinRioux** [comment]
If your issue is that you lose 2 soul points per death, that isn't an
issue. If you die with 3 or less soul points, you will drop your items. If
you need quest items back from quests you've started / completed, try
/fixquests
