### ISSUE TITLE
My wynncraft crashed everytime I log in the server

### ISSUE THREAD

**Issue by m62605486** [Wynncraft/Issues#5740]
my system is win10

clean client not even using mods

it was fine a week ago. Right now I can't even log in the wynncraft only wynncraft make my mincraft crash. 
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb6ca1a41c, pid=7020, tid=3980
#
# JRE version: Java(TM) SE Runtime Environment (8.0_25-b18) (build 1.8.0_25-b18)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.25-b02 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig9icd64.dll+0x57a41c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Terrence\AppData\Roaming\.minecraft\hs_err_pid7020.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by Trixter313** [comment]
What version of Minecraft are you using to try and play? We recommend using 1.8.9 to play and anything else is at the user's own risk. Let us know if using 1.8.9 fixes the issue for you, thanks!

**Comment by ColinRioux** [comment]
Actually Nick, based on the log, it seems that he/she is using 1.8.

If he/she hasn't, he/she should use 1.8.9 from now on.

It'd be good if you could tell me how to reproduce the issue @m62605486

**Comment by AckroWynn** [comment]
Would you please go and look up this document in your library:
C:\Users\Terrence\AppData\Roaming.minecraft\hs_err_pid7020.log

**Comment by 0x0000null** [comment]
See [MC-32606](https://bugs.mojang.com/browse/MC-32606).

**Comment by m62605486** [comment]
I fixed it! it's becasue I didn't disable my on board Intel graphic card, now I m only using my GTX960M to run minecraft no crash at all. Thanks guys
