### ISSUE TITLE
going trew floor

### ISSUE THREAD

**Issue by ries01** [Wynncraft/Issues#5741]
Its probably happend to more people. but I couldn't find more posts of it so here is mine. 
i was in the animal dungeon ad the button. when i got of my horse i gliched trew the floor into the redstone behind it. i wasn't in any small area or with my head in a roof but i still went trew the floor.
i hope you guys can fix it. if not until now i had it only once so no big reason to complain :)

greetings Ries01

**Comment by Trixter313** [comment]
Getting off horses can cause going through blocks issues even in vanilla Minecraft so there's not much Wynncraft can do to fix that part but the dungeons are getting reworked in the next update so this area won't be there for much longer anyway.
