### ISSUE TITLE
Wrong Spell Cast (+Horse problems)

### ISSUE THREAD

**Issue by jetpackguy48** [Wynncraft/Issues#5742]
This happens quite a bit but wasn't bothered until the tribal aggression quest where It kept doing the ice snake when I wanted to do something else, its not my mouse I have a good gaming mouse, I know what spells are what and what buttons I pressed, because it did this I kept wasting mana and died and kept losing soul points and eventually had 2 so i just disconnected also, there may be something about this already, but when I dismount my horse I usually get teleported back and sometimes I loose health for no reason, and twice I slowly sank into the ground on it also sometimes chunks don't load on it, I don't know if any of the horse ones are to do with Wynncraft or my computer, but some must be because its not that bad

**Comment by Trixter313** [comment]
The spell system is supposed to be getting changed up a bit in the next update and the horse issue is caused by using a Minecraft version other than 1.8.9.  Using another version of Minecraft could also be causing the spell issue as well.

**Comment by jetpackguy48** [comment]
I will use minecraft 1.8.9 then, my friend also had the gorse problem so I
will tell them too
