### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by Tanginator** [Wynncraft/Issues#5744]
![2016-08-15_14 02 02](https://cloud.githubusercontent.com/assets/21043403/17673966/73ef600a-62f1-11e6-9906-dc77cbe2562a.png)

Need help i have missing texture everywere since i use liteloader with VoxelMap

**Comment by Tanginator** [comment]
I think it's grass texture

**Comment by Trixter313** [comment]
What version of Minecraft are you using? We reccomend using 1.8.9 to reduce the chance of issues occurring. Let us know if switching to 1.8.9 fixes your issue, thanks!
