### ISSUE TITLE
Class selection bug

### ISSUE THREAD

**Issue by xVyrus** [Wynncraft/Issues#5747]
Hi, my name is Vyrus. My friend by the username "Jayshwan" (No quotes) is experiencing an issue with the class selection menu. On login, after selecting his desired server, he falls through the tiny dark room you enter when you select your class. No selection box appears, and after multiple attempts of trying the .net (play.wynncraft.net) server, and logging out and logging back in, the issue has still not been resolved. Look into this bug, please and thank you.

The issue has been resolved (Exactly 1 minute ago) but i'm worried it may happen to others.

**Comment by Trixter313** [comment]
What version of Minecraft is your friend using? We reccomend using 1.8.9.
They could also try using /kill with 3+ soul points.

We also prefer to talk to the person experiencing the issue directly so if
they could make an account and come on here that would be great.

**Comment by xVyrus** [comment]
The issue was resolved. Although this could happen to over users. No commands are allowed in the class selection world. I have never experienced this bug in the 3 years of playing on this server

https://wynncraft.com/stats/player/iVyrus
