### ISSUE TITLE
My friend is stucked

### ISSUE THREAD

**Issue by iLightZ** [Wynncraft/Issues#5749]
As you saw in the title, my friend PsyFox is stuck in a block. I wish I had the help of an administrator to tp him outside the block because he can not move. I has already tried to give him teleporting scrolls but he could not get a right click on the sheet. I also tried the duel but it did not work. Thank you for help.

![lolptdr](https://cloud.githubusercontent.com/assets/21062508/17704906/7cb784f2-63a4-11e6-961e-0686226e8fb4.png)

**Comment by Trixter313** [comment]
You can use the command /kill to get out of most stuck predicaments. =)

**Comment by iLightZ** [comment]
Thank you!
