### ISSUE TITLE
Spin Attack Stealing Negative Effects

### ISSUE THREAD

**Issue by Endertricity** [Wynncraft/Issues#5750]
When I cast a spin attack, there is a chance that I recieve slowness for no reason - like I'm attacking myself, but not dealing damage. 

Video evidence...
https://www.youtube.com/watch?v=tv7HbbRVIAo

**Comment by Moe-Ronickah** [comment]
I was just using my assassin with no problems.  Is this still happening to you?  Does it happen on all servers?

**Comment by XavierEXE** [comment]
@Moe-Ronickah This happens if you use spin attack twice in a row in quick succession on the same mob, the first spin attack gives the mob slowness and the second spin attack "steals" the slowness and gives it to you, which is indeed a bug.

**Comment by Moe-Ronickah** [comment]
@Endertricity , was this fixed in the latest update?

**Comment by Endertricity** [comment]
Nope.

**Comment by Madib00** [comment]
This has been a thing for years.

**Comment by DebugMC** [comment]
As far as ik this is still a bug. Also please add the class tag :P

**Comment by Moe-Ronickah** [comment]
It's no longer a bug, it's a feature.
