### ISSUE TITLE
Please Help me, Im stucked at X: -1943 Y: 142 Z: -5643 

### ISSUE THREAD

**Issue by SrEnderPvP** [Wynncraft/Issues#5752]
This is not the first time it happens, there are now 3 times that using the spell of teleportation I get stuck in rare places that can not get out, and ended up using scrolls that are not cheap, the difference is that this time not let me wear a scroll, I'm stuck. I was looking "The Hive"

**Comment by Trixter313** [comment]
You can use the command /kill with 3+ soul points to get out of most stuck predicaments.

**Comment by SrEnderPvP** [comment]
Thanks mate!!! Really thanks!!
