### ISSUE TITLE
lost all my stuff and keeps happening every time i logg on to the server

### ISSUE THREAD

**Issue by GoodmanGaming** [Wynncraft/Issues#5753]

**Comment by GoodmanGaming** [comment]
a month ago i lost all my stuff and thought that it might have been my brother, but when i slept over at my friends house i brought the computer over to his house. When i then logged on to the server i lost all my stuff again. the same thing happend the day after. every time it happends i spawn with the beginner bow/oak wood bow.

**Comment by GoodmanGaming** [comment]
ive spent 5 le in total in just trying to get my stuff back.

**Comment by Trixter313** [comment]
What level are your soul points at when your items disappear? If you die with less than 3 soul points all of your items drop and you get an oak weapon.

**Comment by GoodmanGaming** [comment]
i logg out with 12 soul points and when i logg back on its still on 12.... the weird thing is that i have a warrior account but the items there hasnt been deleted!!!

**Comment by Moe-Ronickah** [comment]
Please, immediately change your MC account password, and do not share it with anyone.

Which class is this happening on?
Have you ever accidentally right-clicked on a class in the class selection room?  If you have, have you closed the dialogue box by using "Esc" or clicking the "X"?  **DON'T TEST THIS WITH ESC** "Esc" is currently bugged and there is a high risk of losing your class if you exit the dialogue box using it.
