### ISSUE TITLE
Missing texture blocks.

### ISSUE THREAD

**Issue by mobinblack** [Wynncraft/Issues#5755]
So im using journymap and forge 1.10.2 but whenever I join there are a bunch if missing texture blocks or entities (im not sure). So please help because this is quite annoying.

![2016-08-17_10 57 10](https://cloud.githubusercontent.com/assets/21084277/17741230/688e50a8-6469-11e6-8621-f56469216764.png)

**Comment by ende124** [comment]
Are you using Optifine?

**Comment by mobinblack** [comment]
No.

**Comment by Trixter313** [comment]
We currently recommend players use 1.8.9 to play Wynncraft and using
anything else is at the user's own risk. Please try using 1.8.9 to play and
let us know whether the issue persists or is fixed. Thanks!

**Comment by mobinblack** [comment]
Whenever I use 1.8.9 EVERYTHING is missing textures.

**Comment by mobinblack** [comment]
I got it to work!

**Comment by Trixter313** [comment]
Glad to hear! =)
