### ISSUE TITLE
Stuck in "limbo" multiple times

### ISSUE THREAD

**Issue by PurpleCrobatchop** [Wynncraft/Issues#5756]
First there's this spider cave thing
when I pressed the boss room button, I got Timed out for some reason, relog, still got a few timeouts, when I finally get into the game I'm in this weird place: https://youtu.be/epvtIpYPRGk

Now I tried to swim from Selchar to the bear zoo. Except I went to this strange island-moutain with literally no mobs or signs of life ever. No land connections to Wynn proper either. Didn't capture that.

Then I /kill and tried again, I even bought a boat this time. I when to the isles between Selchar and the zoo, and I am automatically dismounted from the boat, boat is gone. Í'm stuck: https://youtu.be/gmJ8o0k0btM EDIT: I logged out and in the game again, so far it seemed to work. But that does not negate the fact that things like these should not happen.

Please don't just tell me to /kill. This has gone too far.

**Comment by ende124** [comment]
> Please don't just tell me to /kill. This has gone too far.
Use a scroll.

**Comment by Moe-Ronickah** [comment]
@PurpleCrobatchop , your comments in the vids were very funny.

First, somehow, you glitched through a corner of the map, into the unfilled region under the mountains.
Second, you were in a protected area, that players are supposed to be excluded from.  So, once you got in, you couldn't get out.

When you logged out and then back in, the game detected that your player was trying to enter a forbidden area, and rejected that, placing you somewhere where you were allowed to be.

No, things like shouldn't happen, and we try to prevent them, but things like this do happen in MC.  I'm glad that you got out.

**Comment by PurpleCrobatchop** [comment]
Thanks so much!
