### ISSUE TITLE
I'm Stuck in a Wall

### ISSUE THREAD

**Issue by asianironman** [Wynncraft/Issues#5758]
Could an admin teleport me out of this wall I'm stuck and i can't get out i tried using my moves, using scrolls, and re logging nothing worked i just want to get out of this wall. I was doing a quest and was teleported and it glitched me into the wall.

**Comment by asianironman** [comment]
my location is -1867, 29, -4899

**Comment by Trixter313** [comment]
Typing the command /kill into chat with 3+ soul points should get you out.
