### ISSUE TITLE
Spawning in the start area after dying in quest

### ISSUE THREAD

**Issue by zephlee1** [Wynncraft/Issues#5761]
I will spawn in the cart that you start in,yes the start cart where it broke down or something,if I die in the shattered minds quest where there is the rainbow thing with parkour.

**Comment by Trixter313** [comment]
Some quests teleport you to an area outside of the normal Wynncraft map, making you respawn in odd places sometimes. Also, the beginning area is the fallback teleport area in case something goes wrong and it can't teleport you to the nearest place.

**Comment by Moe-Ronickah** [comment]
This is a duplicate, too.
