### ISSUE TITLE
"Looks Like You're Drifting Afloat..." page's home link only works with one slash

### ISSUE THREAD

**Issue by SpeedyNinja** [Wynncraft/Issues#5766]
### Explanation
When you enter an invalid URL on the main [Wynncraft] (https://wynncraft.com) website, you reach a page containing: *"Looks Like You're Drifting Afloat..."* followed by a *"Click here to go home"* link.

This link works if the incorrect URL contains only one slash after the domain name. If the URL contains a larger directory with more than one slash, the *"Click here to go home"* link will just change the last directory name and you will remain on the, *"Click here to go home"* page.

#### One slash: (works)
* [https://wynncraft.com/oops](https://wynncraft.com/oops)
* [https://wynncraft.com/sgfdh](https://wynncraft.com/sgfdh)

#### Two or more slashes: (doesn't work)
* [https://wynncraft.com/home/map](https://wynncraft.com/home/map) <- Doesn't exist anymore (how I found this bug)
* [https://wynncraft.com/a/b/c](https://wynncraft.com/a/b/c)
* [https://wynncraft.com/help/](https://wynncraft.com/nope/) <- Two slashes still

### Solution (I can't change it but here's how)
To solve the problem, this line (the link) needs to be changed from,
    <pre><code>\<a href="home" class="h3"\>Click here to go home\</a\></code></pre>
to, (notice the / before home)
    <pre><code>\<a href="/home" class="h3"\>Click here to go home\</a\></code></pre>

(I have only tested this on firefox)

**Comment by Elements-** [comment]
Thanks will be patched in next update :)

**Comment by Moe-Ronickah** [comment]
Thank you!
