### ISSUE TITLE
I accidently bought the wrong item.

### ISSUE THREAD

**Issue by qscfth2001** [Wynncraft/Issues#5767]
I dont really know where to post this issue and if it could be solved, however as the title says i accidently bought Olux's Prized Wand instead of Olux's Prized Bow for 1  Crushed Bigfoot Bone after doing the quest Shadow of the Beast
If you could swap the wand for the bow or swap the wand for the bigfoot bone i would be very greatful
Thank you.

Game Name: qscfth2001 
Class: Archer
![2016-08-18_11 33 45](https://cloud.githubusercontent.com/assets/21101491/17770948/68ee24fe-6538-11e6-9ca2-eca2c511b168.png)
![2016-08-18_11 33 48](https://cloud.githubusercontent.com/assets/21101491/17770949/6d4c2bae-6538-11e6-96a3-013b1732017f.png)

**Comment by Trixter313** [comment]
Wynncraft has a no refunds policy so there's nothing we can do in this situation. Your options are you can do the quest again on another class or you can buy the bow from another player.
