### ISSUE TITLE
dep weapon

### ISSUE THREAD

**Issue by deathsbreath** [Wynncraft/Issues#5769]
my oxul's prized wand turn into depessing wand and then I dropped  because I didn't need it so help

**Comment by Trixter313** [comment]
What most likely happened is you accidentally dropped the Olux wand and picked up a depressing wand. We've never had any reports of weapons just changing into something else.

Wynncraft has a strict no refunds policy so there's nothing that we can do for you in this situation. I'd recommend changing your drop key to something else that is less likely to be accidentally pressed. You can also ask around and try to buy another Olux wand from a player.
