### ISSUE TITLE
wynn exevation site a bug

### ISSUE THREAD

**Issue by arnoud26** [Wynncraft/Issues#5772]
here is my problem:
i wanted to do wynnnexcevation site a so i talked to excevator vade. he gave me the paper and told me to talk to tesha. she said that i needed to go back to vade. But, vade still says that i need to go to tesha.
i have tried /fixquests and it wont work. i hope you guys can reset the quest on my lvl 53 mage. my in game name is: GalacticGamerNL.

**Comment by arnoud26** [comment]
Ps THE translated writings (paper from tesja ) is also gone

**Comment by AckroWynn** [comment]
If the papers are gone, then you're completely stuck.
