### ISSUE TITLE
Missing Jester Necklaces

### ISSUE THREAD

**Issue by PhungMaster** [Wynncraft/Issues#5773]
I had 2 Jester Necklaces yesterday but when I went to sleep and woke up it just randomly disappeared. Could you please help me get them back as they are my prized possessions and I really don't wanna lose them. They were in my bank.

**Comment by Trixter313** [comment]
Did you recently upgrade your bank space?

**Comment by PhungMaster** [comment]
Yes... but why would this affect it disappearingredients overnight?

**Comment by Trixter313** [comment]
You probably didn't notice them until the next day or it was a delayed reaction. This appears to be a duplicate of https://github.com/Wynncraft/Issues/issues/4091 where items that are reskinned glass panes disappear from the bank when you upgrade it. Wynncraft has a strict no refunds policy so we can't return the item but we are working on fixing it so it doesn't happen again.
