### ISSUE TITLE
I am stuck !!

### ISSUE THREAD

**Issue by Phanthyo** [Wynncraft/Issues#5774]
I m stuck in wynncraft, coords: -595 124 -1160 !!!
I threw my weapon without express and it soar! omg
Look when we throw an object! and I lost my gun ...
http://image.noelshack.com/fichiers/2016/33/1471609873-2016-08-19-14-30-08.png

Help me please ...
Ps: je suis français désolé pour mon anglais je ne le métrise pas encore bien :/

**Comment by Trixter313** [comment]
You can type the command /kill into chat to get out. As for the weapon, we
have a no refunds policy so we can't return it. I'd recommend changing your
drop key to something less likely to be pressed accidentally. You will have
to use another weapon or buy one from another player.
Close #5774
