### ISSUE TITLE
Bob the Zombie (Bob's Tears)

### ISSUE THREAD

**Issue by RadioactiveL** [Wynncraft/Issues#5776]
I have recently reached level 45. My friend wanted me to do Bobs Tomb with him. So we started the quest. We got the 1 Rose each and when we reached Ragni we started killing Bob the Zombie. At first he wasn't dropping Bob's Tear, eventually it dropped and my friend went to pick it up but it had dissapeared and was not in either of our inventories. So we kept killing Bob the Zombie, eventually this happened a 2nd time and the tear dissapeared. So we kept killing Bob the Zombie, this same thing had happened multiple times. I eventually had realized that it had to be some sort of bug. I contacted a Mod about it. He/she talked to me for a little bit until he/she asked what the problem was and then once I told him he/she never responded.

**Comment by Trixter313** [comment]
Does switching to another world fix the issue? And to clarify, both you and your friend ended up with no tears?

**Comment by RadioactiveL** [comment]
Yes. And we switched multiple times so more bobs would spawn.

**Comment by YunoFGasai** [comment]
I'll try to test it today

**Comment by RadioactiveL** [comment]
Ok thank you

**Comment by Moe-Ronickah** [comment]
What you may be seeing, is that Bob throws a tear at you as his attack.  When he actually drops a tear, if you are close enough, it jumps into your inventory.  I just checked, and Bob is still dropping real tears, just fine.
