### ISSUE TITLE
WynnExcavation Site C Bug

### ISSUE THREAD

**Issue by siphsky** [Wynncraft/Issues#5777]
Hi, I started the quest and when I'm back to the excavator to complete the quest.  When I talk to the npc, it said "The purple Crystal Shard from WynnExcavation Site B is required to start this quest.".  I have done /fixquests to get purple shards and it said the same thing.  So I can't complete the quest :/

**Comment by Trixter313** [comment]
What does it say in your quest book?

**Comment by ColinRioux** [comment]
Closing for further notice.
