### ISSUE TITLE
Bobs Tomb Glitch

### ISSUE THREAD

**Issue by Celsonic** [Wynncraft/Issues#5778]
You can get into bobs tomb without having 3 people by getting a horse, jumping into the wall the getting off it and eventually you will get on the other side. I can not show this due to the fact that I was Killed by a player made invasion while afk.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3730

It appears to have been changed on the build server and will be live on the play server in the next map update.
