### ISSUE TITLE
Breathing Helmet Lost

### ISSUE THREAD

**Issue by Endeh** [Wynncraft/Issues#5779]
So I  was about to do Underice and noticed I couldn't find my breathing Helmet. I tried /fixquests.. no breathing helmet. I thought 'Hmm odd. I guess I could borrow one of my higher classes helms' ... on 3 other classes. No breathing helmets anywhere not even after fixquests. I thought about making a new class to get another helmet but I much rather not. Any help?

**Comment by Endeh** [comment]
Sorry. I figured out why. I have one breathing helmet on a class I thought I checked. So all my other classes won't give me one from /fixquests. I guess I have to share a helm between 4 classes.

I actually was about to close this. But is a bug to only able to have 1 type of quest item between multiple classes?

**Comment by Trixter313** [comment]
With some quest items you have to have 0 for fixquests to return anything. I wouldn't worry about it, you shouldn't need any more than one at a time anyway and the Underwater quest is supposed to be getting redone for the next update I believe so you might have to redo the quest anyway.
