### ISSUE TITLE
Quest Bug

### ISSUE THREAD

**Issue by SpyWatcher** [Wynncraft/Issues#5780]
For some reason when I do quest I don't get emeralds for finishing them

**Comment by Trixter313** [comment]
To be able to fix anything we would need to know what quest(s) you are referring to.

**Comment by SpyWatcher** [comment]
Thieving Rodents and Prison Story

**Comment by Moe-Ronickah** [comment]
Is your inventory full?  If it is, you won't get any emeralds, obviously.
Unless you have no emeralds in your inventory, it's hard to tell what may have happened, because it's easy to miscount emeralds.

**Comment by Moe-Ronickah** [comment]
All emerald rewards were reportedly changed.  Hopefully this also fixed whatever caused this issue.
