### ISSUE TITLE
Removed Quest Item

### ISSUE THREAD

**Issue by MoiKeh** [Wynncraft/Issues#5781]
My Friend SamKeh lost his quest item from the quest An Iron Heart Part 2. I don't know how to get the quest item back but im hoping a mod sees this and gives him the item. Thank you for looking at my response and give him  the quest item

**Comment by Trixter313** [comment]
Could you tell us what the item is that is missing?

Also, does typing the command /fixquests into chat return it?

**Comment by Trixter313** [comment]
Closing due to no response. If it's still happening, please have your friend make an issue again.
