### ISSUE TITLE
Falling through world wynncraft

### ISSUE THREAD

**Issue by NerrawChase** [Wynncraft/Issues#5785]
Hey everyone i'm in need of some help pretty bad! 
I'm fairly new to the server and have absolutely fallen in love with all you guys and the wynncraft servers! I have recently purchased VIP+ even! But for some reason when i went to go log in today and connect to a world i get taken to wear im prompted to pick a class but instead i just continually fall through the world in abyss.. I have tried everything i can think of from redownloading minecraft, to restarting my computer, turning the WynnPack on and off but still same thing
It's odd because i can log in using any other account and play just fine but my actual account i use to play just keeps on falling through the world! 

Please if any of you know the fix help me out!!!

**Comment by Trixter313** [comment]
Does it let you use the command /kill?

**Comment by ItsWittle** [comment]
This is exactly what happened with me! I made an earlier post about it around 3 days ago, I'm not even able to perform any commands so I can't /kill myself or anything. 

(If you want to look at my post) -
https://github.com/Wynncraft/Issues/issues/5760

**Comment by NerrawChase** [comment]
@Trixter313 Im able to use commands /lobby and /hub nothing else, ive tried ever possible one i could think of. My username is Nerraw___(that's 3 underscores), VIP+ and im running latest version of minecraft.

**Comment by YunoFGasai** [comment]
try logging in to the nether through the lobby signs and do /autojoin I'm not sure it will fix your problem but its worth a shot.

**Comment by Trixter313** [comment]
Also, we reccomend using 1.8.9 to play Wynncraft currently as using other versions can cause issues in themselves.

**Comment by NerrawChase** [comment]
@Trixter313 I switched over to 1.8.9 and still having issue, Its weird because i am able to log into different mc accounts and play just fine but not my actual account! 

I really dont want to have to start all over on a different account plus i just got VIP+! 

@YunoFGasai I fall through the world doing that too already tried  it :/

**Comment by Moe-Ronickah** [comment]
@NerrawChase  "I switched over to 1.8.9 and still having issue, Its weird because i am able to log into different mc accounts and play just fine but not my actual account!"

Whose accounts are you logging into, if they aren't your actual account?

**Comment by Moe-Ronickah** [comment]
@ItsWittle , Salted fixed your position error a little while ago.  You are good to go.

**Comment by Sorceric** [comment]
@Moe-Ronickah @Trixter313  can someone notify me when the problem has been solved? tyvm c;

**Comment by Moe-Ronickah** [comment]
@Sorceric , check back with the next update and see what happens.  Sometimes, updates fix things that are linked with other problems.  Right now, is there no known solution, and Salted and Jumla have been trying to crack this.

**Comment by NerrawChase** [comment]
It's been 4 days and still not able to play!! I really wish someone could help me.. None of the Wynncraft staff have been answering me or the ones that do answer me cant do anything and says theyre going to tell someone who can but still nothing

**Comment by Sorceric** [comment]
@NerrawChase just be patient it'll make it easier. Just saying.

**Comment by NerrawChase** [comment]
@Sorceric Its been nearly a week now.. Ive posted on here as well as wynncraft forums and i even talked to some of the staff and still nothing! I basically spent money on a server i cant even play.

**Comment by Moe-Ronickah** [comment]
@NerrawChase , we don't have a solution for this error, YET.  The admins are aware of it, and we all are seeking a solution for it.  You aren't the only one with this - that's not comforting, I know.  This issue is a real pain.

**Comment by NerrawChase** [comment]
@Moe-Ronickah Then don't you think it would be only fair to give me a refund for the money i spent on this server? Or maybe at the least transfer my stuff to a different account?

**Comment by Moe-Ronickah** [comment]
@NerrawChase , you need to take up your last question with support@wynncraft.com, as we only handle technical support issues, not monetary support issues.
