### ISSUE TITLE
Quest item deleted glitch

### ISSUE THREAD

**Issue by AMCBrosky** [Wynncraft/Issues#5786]
Hi Julma. So if you did't get the converstion i sent you here is the official bug report area for me 2 tell u what happened. So during the quest Aldorei's Secret part 2 i lost the quest item Elvish Medallion due to a glitch. When i was at the last bit of dialogue i had 2 clear my inventory so i threw some crap on the ground then started the text. but midway through the text i picked up the items resulting in me not getting the rewards & losing the quest item. then i went & killed the boss 2-3 times but it did not give me the receipt as a drop so i could not do the dialogue for the bad route so i'm stuck. i've been in rage quit denial of wynncraft for about a year and its high time i finish it. because i'm a completionist could you please look into this bug and give me the Elvish Medallion.

AMCBrosky

**Comment by Trixter313** [comment]
Does using the command /fixquests return the missing item?

**Comment by AMCBrosky** [comment]
did not know it existed mb

**Comment by AMCBrosky** [comment]
now how do i get rid of the other quest items i don't need?

**Comment by Trixter313** [comment]
You can place it in your daily reward inventory and exit it and it should get rid of it. =)
