### ISSUE TITLE
Assassin Spin Attack on Frozen Ice Snake Mobs Glitch

### ISSUE THREAD

**Issue by PhungMaster** [Wynncraft/Issues#5788]
So I frequently play with my brother who is a mage and we grind together. But the problem is that when he ice snakes, which freezes the enemies, then I use spin attack on the frozen enemies I get frozen because of me stealing the enemies effects. The problem is is that I should only be taking the positive effects and not the negative ones like freezing which is really weird.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/5750
