### ISSUE TITLE
Quest not there

### ISSUE THREAD

**Issue by IceyDucky** [Wynncraft/Issues#5789]
I gave traveled far and wide and found a quest not in its position 
So here is the photos
of the map and the place I am now
![2016-08-21_02 52 47](https://cloud.githubusercontent.com/assets/21150037/17834853/4fc6ce94-674b-11e6-8d74-69c699812dc4.png)

![capture](https://cloud.githubusercontent.com/assets/21150037/17834854/551a1f86-674b-11e6-9c05-2590ea9b546b.PNG)

**Comment by YunoFGasai** [comment]
the icon locations aren't supposed to be 100% accurate, also the map is rendered at an angle so it is possible that the quest start is on the other side of the mountain
