### ISSUE TITLE
Old legendary items are glitched

### ISSUE THREAD

**Issue by NinyahHellKitties** [Wynncraft/Issues#5792]
Hello! I'm a Wynncraft player by the username NinjaKittyQuake, lvl 47. 
So in the past before a few updates I had two extremely wonderful legendary items, a legendary warrior item(spear) and a legendary helmet. 
When I went to get them out of my bank they.. didn't seem right. I couldn't even tell if they were the right ones, the names were glitched into long lines of purple text and I couldn't use them. [http://imgur.com/a/Ru1K8](url)
[http://imgur.com/a/6z0FA](url)
These are the two glitched items.. may I have them fixed..?

**Comment by Moe-Ronickah** [comment]
I'm betting that those are a Fierte and a Pelier, with accented characters.  They won't get updated, so you might as well just throw them away.
