### ISSUE TITLE
the boat merchant is gone on the island 'the bear zoo'

### ISSUE THREAD

**Issue by ene5353** [Wynncraft/Issues#5793]
I was going to the Island 'the bear zoo' but the boat merchant was gone. I know he need to be there because I used the wynncraft world map (https://map.wynncraft.com/#/-522/64/-2556/min/0/0) can someone fix this?

**Comment by ColinRioux** [comment]
Have you tried relogging/ switching servers?

**Comment by YunoFGasai** [comment]
boat merchants seem to vanish randomly on servers

**Comment by Moe-Ronickah** [comment]
Duplicate of #4178 .

As Yuno said, sometimes boat merchants just walk away.  The don't tell us why, just go do other business.  Switching servers usually catches one on the job.
