### ISSUE TITLE
New version of server, lost my classes ?

### ISSUE THREAD

**Issue by leo120201** [Wynncraft/Issues#5795]
So, I am a very big fan of Wynncraft, and I played it very often before.
I just stopped playing for a while (like 6 months or more...) and I had a mage level 48 and other classes with smallest levels.
So, I came on the server yesterday and I had all my classes, with their levels and the same spells as the last time. Necessarily I choosed my mage, and started playing, when I discovered that my Staff wasn't able anymore to create spells, and my armors were all "Unidentified". (So I am naked, without any armours, and with a unusable mage staff.)
I still have all of my Emeralds, and my old quest items but... I think you know what I mean.

Thank you for reading, and please take back my classes. ^^'
If you want my Skype it is : leo120201  (I've got screenshots of my problem if needed...)
                                                                                                         leo120201_

**Comment by Trixter313** [comment]
This is intended, in the Gavel update all items were unidentified for everyone. All you should have to do is identify them again. =)

**Comment by leo120201** [comment]
And how do I fix my spells.. ?

**Comment by Trixter313** [comment]
Did you identify your wand? Also, is the wand still using the old item system?

If you're not sure, posting an image of the wand's info would help. Thanks!

**Comment by leo120201** [comment]
![2016-08-21_19 29 32](https://cloud.githubusercontent.com/assets/21157286/17838806/119362be-67d6-11e6-9429-a48deacf84c5.png)
Yea, i think that's an old model and I can't identify it, but I need a weapon, I can't fight without a good level wand... :/ Can't I get another one with the same stats ? Or Something like that ? That should be very helpful... And thanks for helping !

**Comment by leo120201** [comment]
I just don't have weapons anymore, I identified all my wands, they are all higher than my level...
I just can't do anything... x)

**Comment by Trixter313** [comment]
Ah, it is one with a special character. In the update many if those got broken.

Unfortunately Wynncraft has a strict no refunds policy so there isn't much we can do in this situation. You can ask around towns to buy another weapon or you can kill some weak mobs and work your way up to another weapon.

**Comment by ColinRioux** [comment]
There are some weapons that weren't carried over or were "updated". With
these older models, unfortunately, there is nothing you can do but grind
for a newer staff. If you need a weapon to grind I'd buy one from a Weapon
Merchant.
