### ISSUE TITLE
My friend gets kicked

### ISSUE THREAD

**Issue by bluehooded** [Wynncraft/Issues#5796]
My friend keeps getting kicked for flying everytime he enters the server please fix it please

**Comment by ColinRioux** [comment]
If he has time to /kill tell him to do that. If he's falling into an
endless void tell him to use version 1.8.9. And if he's using mods tell him
to stop.

**Comment by Moe-Ronickah** [comment]
Tell your friend to post his own issues, because we have no idea who he is, where he is, or what else may be happening to his character.
