### ISSUE TITLE
Dark Forest Wall Glitch

### ISSUE THREAD

**Issue by xXCincmincXx** [Wynncraft/Issues#5799]
I was in the Dark Forest doing Taproot, and I was trying to get to Tiek again, and there was in invisible wall. I tried to follow the wall until it ended, but I followed it for ten minutes and I couldn't find an exit. I don't know what to do about this.
![2016-08-21_22 00 07](https://cloud.githubusercontent.com/assets/20261283/17841834/c38ef910-67ea-11e6-8efc-738b7eb28b9e.png)

**Comment by thecoolkogut4** [comment]
are you sure that's what you are meant to do for the quest? most of the time they put a wall in there to stop you from going the wrong way.

**Comment by Trixter313** [comment]
Yeah, you're probably trying to go somewhere you aren't meant to. What does it say in your quest book?

**Comment by xXCincmincXx** [comment]
It says I'm supposed to go back to Tiek, and I checked the wiki and I'm going the right direction from what I could remember. I'll try again as soon as I can.

**Comment by xXCincmincXx** [comment]
I tried it again, while making sure that I was going the right way, but it still won't let me.

**Comment by xXCincmincXx** [comment]
I mean I could always do /kill but I don't really want to travel a long time just because of a wall.

**Comment by xXCincmincXx** [comment]
I decided to do /kill, I did what you guys did, but it still didn't work for me.

**Comment by ColinRioux** [comment]
What's your context? Have you already entered the taproot? Have you left? Are you turning in the quest? Are you returning with the flowers? Are you in the light forest?

**Comment by ColinRioux** [comment]
There has been no response in at least 30 days. If your issue still persists, please make a new issue (while checking if there are no duplicates first).
