### ISSUE TITLE
Inventory cleared

### ISSUE THREAD

**Issue by RealSano** [Wynncraft/Issues#5803]
Hello my name is RealSano my inventory was today cleared with my archer lvl 52.And i dont died with 2 soul points  i have a weak weapon and armor from my friend and in my enderchest was a ammulett.

RealSano

**Comment by AckroWynn** [comment]
Can you show us a picture of your inventory, and the amount of soulpoints you have?

**Comment by ColinRioux** [comment]
As stated on the wiki (http://wiki.wynncraft.com), if you die with 3 or less soul points, you will drop your items.

**Comment by RealSano** [comment]
@AckroWynn  i can
![2016-08-23_16 12 43](https://cloud.githubusercontent.com/assets/21175675/17895201/9c6280c4-694c-11e6-82dd-2ff93722f5c7.png)

**Comment by RealSano** [comment]
@AckroWynn   yes i can

![2016-08-23_16 12 43](https://cloud.githubusercontent.com/assets/21175675/17895249/ccb1fb7e-694c-11e6-92b2-c14e900c5461.png)

**Comment by RealSano** [comment]
Ups sry
:(

**Comment by AckroWynn** [comment]
What weapon is that in your inventory? If it is an oak bow, then you must've glitched out and died + lost everything. If it is not, then I might want to believe someone else has gotten access to your account. To be on the safe side, I recommend that you change your password.

**Comment by RealSano** [comment]
Is a Jungle wood bow from my friend

**Comment by AckroWynn** [comment]
But, what was it before you took the Jungle bow?

**Comment by RealSano** [comment]
Nothing

**Comment by RealSano** [comment]
before the jungle bow i have only 1 generator ammulet

**Comment by AckroWynn** [comment]
Oh, in that case, you were, with a high chance, hacked.

**Comment by Moe-Ronickah** [comment]
@RealSano , change your MC user account password.  As Ackro said, this looks like a hack.

**Comment by RealSano** [comment]
Yes i was hacked ... and now ?

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so we can't return any lost ingame items. You could ask around and someone will likely be willing to donate stuff or sell you something.
