### ISSUE TITLE
After Gavel update my wand bugged.

### ISSUE THREAD

**Issue by qscfth2001** [Wynncraft/Issues#5804]
So, Gavel is ben out for some time now but i never reported this bug so here it is. The wand i had in my bank i remember was very good wand but now it displays random text and numbers. i posted an image below of what it looks like bare in mind that i used tiny  GUI to show as much text as possible.

![2016-08-22_15 56 34](https://cloud.githubusercontent.com/assets/21101491/17860006/b3919056-6883-11e6-9835-2c93bbbac98c.png)

Game name: Acemeth

**Comment by Trixter313** [comment]
We've determined that this issue shouldn't happen to new items and was just
a one time thing. We recommend throwing out the broken weapon and getting a
new one.
