### ISSUE TITLE
Server login

### ISSUE THREAD

**Issue by tigersrule28** [Wynncraft/Issues#5808]
I am having a hell of a time trying to get into Wynncraft. the past two days i have been unsucsessful in getting on a server. Beforehand, everything was fine and i was grinding out quests. nothing has changed for my internet, so i think the problem may be in the server. Help me.

**Comment by Charliebubblegum** [comment]
OMG SAME TH:ING HAPENING TO ME

**Comment by Charliebubblegum** [comment]
yay I fixed it :D

**Comment by ColinRioux** [comment]
It's not server related, as the server is still online. If you are getting an unknown host error, please view my guide here: [http://www.planetminecraft.com/blog/unknown-host-errorcant-resolve-host-name-client-fix-17-all-platforms/](url).

If you are able to join the lobby but not a server, try `/lobby 5` or re-logging. You could also try joining the nether first.
