### ISSUE TITLE
Quest glitch: flight in distress

### ISSUE THREAD

**Issue by cannibals** [Wynncraft/Issues#5809]
I killed the pirate queen and got the ring, but accidentally clicked captain ackbar right before the server restarted, and he took the ring from me. Now i am unable to do ANYTHING
http://imgur.com/a/coGRh

**Comment by AckroWynn** [comment]
If you are still at the stage of having to speak to Ackbar, you can actually return to the queen (by redoing the quest stages; read the wiki for a walkthrough), kill her, and return with another ring!

**Comment by cannibals** [comment]
nope. i did /kill and i am now in lexdale and i am unable to leave. this is really screwed up.

**Comment by AckroWynn** [comment]
Can you show me your quest book?

**Comment by Moe-Ronickah** [comment]
Cannibals, please show him your quest book.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
