### ISSUE TITLE
Gliched items in my inventory

### ISSUE THREAD

**Issue by RytisXZX** [Wynncraft/Issues#5810]
i have left wynncraft for couple of months now when i came back some of my items were glitter,don't remember the names tho
![screenshot 2016-08-23 19 01 31](https://cloud.githubusercontent.com/assets/16591687/17899451/0b51aac0-6964-11e6-9c32-4b8d141d021a.png)
![screenshot 2016-08-23 19 02 11](https://cloud.githubusercontent.com/assets/16591687/17899478/1e683b06-6964-11e6-8f4f-1d6a148a7c4b.png)

**Comment by Trixter313** [comment]
Some items were broken in the Gavel update when updating to the new item system, mainly ones with special characters and accents. We suggest just throwing the items out and getting new ones. This shouldn't happen to any new items you get.
