### ISSUE TITLE
Hunger of the Gerts Frustrating Glitch

### ISSUE THREAD

**Issue by IncBear101** [Wynncraft/Issues#5812]
So, as curious as I was, I escaped above the most lowest Gert Camp, and as it says "Gert see human, gert kill human" or something similar, I can't seem to move, because it keeps teleporting me up before I fall into the gert camp, and since I cant go in, it teleports me around 10 blocks above where I was in the air. Help? This is my fault, cause I'm bad at quests. Heres a screenshot if I can get one: 
![2016-08-23_13 59 42](https://cloud.githubusercontent.com/assets/20328015/17907601/f74ce906-6939-11e6-8b82-c2d942ad87a8.png)
![2016-08-23_13 59 43](https://cloud.githubusercontent.com/assets/20328015/17907607/fa7c1098-6939-11e6-90a9-c276be73e766.png)

**Comment by IncBear101** [comment]
Update: The server lagged/stopped, so I fell, and landed in Lexdale. How would I fix this if I were to forget and this happened again?

**Comment by Trixter313** [comment]
You can use the command /kill with 3+ soul points to get out of most stuck situations. =)
