### ISSUE TITLE
Can't leave Guild apparently

### ISSUE THREAD

**Issue by IceyDucky** [Wynncraft/Issues#5813]
I have tried so many times to leave, I have been kicked from the Owner of the guild and I am yet still in the guild, here is a picture of me leaving the guild and staying in it.
![2016-08-23_22 39 49](https://cloud.githubusercontent.com/assets/21150037/17910887/c63e4f50-6982-11e6-8f0b-7ca7d430e466.png)

**Comment by ColinRioux** [comment]
Yes guilds are currently bugged and will hopefully be fixed in the next update. Sorry for the inconvenience. @Moe-Ronickah

**Comment by Trixter313** [comment]
I see that you've changed your name before, meaning you're experiencing issue #3665
