### ISSUE TITLE
Untradable stacking glitch

### ISSUE THREAD

**Issue by cannibals** [Wynncraft/Issues#5814]
if I throw an LE on the ground, and someone throws one on top, they can pick up both of them
same goes for TOA shards, but the person glitching needs at least one shard to throw on top

**Comment by Trixter313** [comment]
I believe this has been reported before and there's not really anything we can do to prevent this. It's a vanilla Minecraft mechanic that items of the same type will stack when dropped on one another on the ground and once they combine there's no way to tell whose is whose. The best thing I can suggest to make sure this doesn't happen to you is be careful with your emeralds and don't put them in your hotbar.
