### ISSUE TITLE
Excessive Y value - Falling threw The World

### ISSUE THREAD

**Issue by InVentPvP** [Wynncraft/Issues#5816]
When ever I try to log into my mage account I fall threw the map, roughly Y-89000000000000000000000, it wont allow me to do any commands nor will it let me use teleportation scrolls, it also crashes the server I try to log into. Please Help me and Thank you for your time! <3

http://prntscr.com/c9qqwz

**Comment by InVentPvP** [comment]
my Username is InVentPvP_

**Comment by Trixter313** [comment]
Someone who can fix it for you should be around soon.

Just to cover the basics just in case, could you try switching to 1.8.9 instead of 1.8? 1.8.9 is currently the version we recommend for players because using other versions can cause issues in itself.

**Comment by InVentPvP** [comment]
that didn't work

**Comment by Sorceric** [comment]
@ InVentPvP then wait for the next update to update.

**Comment by Moe-Ronickah** [comment]
@InVentPvP , you should be OK, now.  Please let us know if you are able or unable to play, again.  Thanks.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
