### ISSUE TITLE
Guild Glitch

### ISSUE THREAD

**Issue by amit1230** [Wynncraft/Issues#5817]
My friend created new guild so i left my guild and i tried to join his guild but it doesnt worked
when he tried to invite me to the guild it told him that im already in guild and when i did /guild left its said: you are not in a guild
pls help me .-.

**Comment by ColinRioux** [comment]
We are aware that guilds are bugged. Hopefully they'll be fixed in the update. @Moe-Ronickah 
@Trixter313
