### ISSUE TITLE
Texture bug 

### ISSUE THREAD

**Issue by mastermeter** [Wynncraft/Issues#5818]
i use the 1.10 version with forge 1.10 and optifine 1.10and i have a bug with the texture of the tall grass.

http://image.noelshack.com/fichiers/2016/34/1472044943-2016-08-24-15-15-01.png
http://image.noelshack.com/fichiers/2016/34/1472044947-2016-08-24-15-15-24.png

thanks for helping.

**Comment by ColinRioux** [comment]
The texture pack is made to use with 1.8.9 so I suggest using 1.8.9 if you
want correct textures.
