### ISSUE TITLE
Weapon Bug

### ISSUE THREAD

**Issue by mono2338** [Wynncraft/Issues#5819]
I attack with my bow to the ground and it pop out a sentence said"You don't have permission for this area"

**Comment by YunoFGasai** [comment]
that's because your bow is actually a block cant really be fixed

**Comment by mono2338** [comment]
but there nothing happen before

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3902

**Comment by Moe-Ronickah** [comment]
Not all bows are retextures of the same items.
