### ISSUE TITLE
Random damage when attacking with a wand

### ISSUE THREAD

**Issue by wes1327** [Wynncraft/Issues#5820]
I've randomly been getting damaged when attacking anything with my wand from a distance, attacking multiple targets deals more damage, couldn't play well due to this bug.

**Comment by XavierEXE** [comment]
Does you want have a negative life steal identification?

**Comment by wes1327** [comment]
I don't have negative life steal, nor is it on my weapon.

**Comment by XavierEXE** [comment]
maybe on your armour or accessories? Otherwise, I'm not sure.

**Comment by wes1327** [comment]
Nothing in my weapons and such, I had help getting my stuff back when I died.

**Comment by wes1327** [comment]
Seems I do have negative health steal, lol.
