### ISSUE TITLE
Aldorei's Secret Part II

### ISSUE THREAD

**Issue by Poiu429** [Wynncraft/Issues#5823]
Right so I'm too lazy to see if this has been posted before, but if it has, sorry for wasting your time.

So awhile ago, I finished Aldorei's Secret Part I. I clicked on Kansard, and got the medallion. I have not done the quest since.
Later, I was looking in my bank (and storage classes) and noticed that **on top of the elven medallion, I had the receipt.** Both are quest items, and I'm supposed to only have one. TBH though, idk how it happened.

**Comment by Trixter313** [comment]
You most likely did /fixquests and it returned the one you didn't choose. To get rid of the one you don't want you can simply put it in your daily rewards inventory.
