### ISSUE TITLE
Quest bug

### ISSUE THREAD

**Issue by InawsRX** [Wynncraft/Issues#5824]
I am doing WynnExcavation Site A , the quest book say [ Go to talk the Lab Assistant Tesh in the tents at [1082,69,-1799] ] I have talk to that guy already but the quest book haven't update. But Tesh say [take that to Vade,and don't read it !]

**Comment by Trixter313** [comment]
Does using the command /fixquests return anything important for this quest?

**Comment by InawsRX** [comment]
He say [ You have no missing quest items... ]

**Comment by Trixter313** [comment]
Many people get stuck at this point and we unfortunately do not have a fix right now. Until we can fix it I suggest focusing on other quests and aspects of the game.

**Comment by PineOMatic** [comment]
I have a similar problem but for the end of the quest. After returning from the tomb, It tells me to go back to Excavator Vade, but they go back to saying "Have you translated that text yet?" etc. It really BUGS me that it would happen right at the end of the quest. Is there any way that I can fix this? I've tried /fixquests as well but it doesn't work. Any Suggestions?

**Comment by Trixter313** [comment]
If /fixquests doesn't work you could try going back through the tomb. Other than that there's nothing I know of that could help.

**Comment by Moe-Ronickah** [comment]
@PineOMatic , do you have the crystal with you when you go back to talk with Vade?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
