### ISSUE TITLE
Stuck in a block...

### ISSUE THREAD

**Issue by moumbear** [Wynncraft/Issues#5826]
So, as you could probably tell from the title, I'm stuck in a block I accidentally went into a bed, when I got out I as inside the wall and floor... If an admin could teleport me somewhere else it would be nice, thanks :)

**Comment by thecoolkogut4** [comment]
if you have 3 or more soul points you can do /kill to get out of the block.

**Comment by Moe-Ronickah** [comment]
This is a multiplayer game.  Don't even try to use a bed.
