### ISSUE TITLE
Unable to obtain relics

### ISSUE THREAD

**Issue by coreynj** [Wynncraft/Issues#5827]
I've been standing here, smacking the same powder relic over and over, and it simply wont give it to me. I haven't obtained it yet, I just got here and smacked it over and over, so I shouldn't have a cooldown. What is happening?

**Comment by thecoolkogut4** [comment]
the new powders (the ones that are getting added in the update this weekend) are not given in the relics yet.

**Comment by ColinRioux** [comment]
If you are not in the beta server, then you won't be able to access the new powders until the update formally releases.

**Comment by coreynj** [comment]
That's not what I mean. I tried to obtain the Green Powder IV and it simply won't give me it, no matter how long I wait or how many times I try.

**Comment by gettodachopa** [comment]
powders green 2, and all the others tier 4-6 are disabled at this moment, you will be able to get it after next update
