### ISSUE TITLE
"You don't have permission for this area."

### ISSUE THREAD

**Issue by SlominPL** [Wynncraft/Issues#5828]
I've been looking for loot chests in Diamond Mines and I have encountered this problem:

http://screenshot.sh/n9iqyXGsDKKri

I can't open any loot chest due to no permissions. Is that alright?

**Comment by Moe-Ronickah** [comment]
Your bow is a re-textured item.  You will need to use either an empty hand, or hold something else in your hand.

**Comment by SlominPL** [comment]
Yes, I figured it out immediately after I'd posted it. Sorry for taking your time.

**Comment by Moe-Ronickah** [comment]
It's not a problem, we're glad to help.
