### ISSUE TITLE
Keep dieing for no reason

### ISSUE THREAD

**Issue by Sonic80000** [Wynncraft/Issues#5829]
I keep having trouble with my health, it keep reducing to 1, and then stop deducing, but when anything hit me once, I'm dead

**Comment by gettodachopa** [comment]
Check your armor, weapon, accessory, you may have some piece with negative Health Regen

**Comment by Sonic80000** [comment]
@gettodachopa  I checked, theres nothing wrong

**Comment by Trixter313** [comment]
What happens if a mage heals you or you use a health potion?

**Comment by Sonic80000** [comment]
@Trixter313 after they heal me, my health went to max, but it then also keep reducing to 1, then die

**Comment by Moe-Ronickah** [comment]
If this is still occurring, please click on your compass, then mouse over the players head on the top far right of the pop-up.  Take a screen cap of that, and post it here, please.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
