### ISSUE TITLE
Falling through world, stuck in the walls, and getting teleported to spawn

### ISSUE THREAD

**Issue by gettodachopa** [Wynncraft/Issues#5830]
So basically you can fall through the world or get stuck in the wall when dismounting the horse, 
Falling the world happens very often in the tower of ascension, and get stuck in a wall if you dismount the horse near any wall.
This only happens if dismounting the horse walking.

Other bug is getting teleported to spawn, 
When entering a world or switching class your class is teleported to spawn (game spawn near ragni)

**Comment by Trixter313** [comment]
The horse part is a vanilla Minecraft issue that we can't really do anything about, just try to be careful when dismounting in a small space.

The beginning area is a fallback teleport so if anything goes wrong and it can't teleport you to where it was supposed to, it has somewhere to put you.
