### ISSUE TITLE
Iron Heart Part 2 Rewards not given

### ISSUE THREAD

**Issue by John62534** [Wynncraft/Issues#5831]
When i turned in my quest for Iron Heart Part 2 into the detective, it did not give me the leggings. Is there a way for me to get the leggings even if I already completed the quest?

**Comment by Trixter313** [comment]
Was your inventory full at the time of quest completion? Wynncraft has a strict no refunds policy so we can't return the leggings. The only thing you can try to do is use the command /fixquests to see if it returns the item.
