### ISSUE TITLE
I'm stuck in a block.

### ISSUE THREAD

**Issue by Telv** [Wynncraft/Issues#5832]
I'm a mage so I have the teleport spell, I used the teleport spell in the animal dungeon because I didn't know where to go. I tried to teleport through but I got stuck in a 1 block high spot, my head is stuck in a block and when I try to teleport or anything to get out it says try and move away a few blocks but I can't move.

**Comment by Trixter313** [comment]
You can use the command /kill with 3+ soul points to get out of most stuck situations. =)
