### ISSUE TITLE
Trapped in a hole!!

### ISSUE THREAD

**Issue by Clarky52** [Wynncraft/Issues#5833]
I slept in a bed at the inn near detlas, when I got up from the getting trapped in a 1by1 hole where scrolls don't work.

**Comment by Trixter313** [comment]
You can use the command /kill with 3+ soul points to get out. Try not to sleep in any more beds to prevent getting stuck like this again. =)

**Comment by Moe-Ronickah** [comment]
WynnCraft is a mutli-player game.  Don't sleep in beds.  Ever.
