### ISSUE TITLE
Health Regen Percentage ID broken?

### ISSUE THREAD

**Issue by setery10** [Wynncraft/Issues#5834]
For some reason whenever I use an ID version of the Health Regen % it never applies additional health regen. For example If I have a base health regen of 70 and I have a health regen bonus of 50%, I don't get 105 health regen, I just get 70. Let me know if this is a bug or not.

**Comment by YunoFGasai** [comment]
I'm pretty sure it increases the rate at which your hp regenerates not the amount

**Comment by setery10** [comment]
Can someone else confirm this because I didn't know this, but thanks for the info!

**Comment by setery10** [comment]
Hello this is still open and no real answer :(

**Comment by Moe-Ronickah** [comment]
Take Yuno's word for it.
