### ISSUE TITLE
Typos in Beneath the Depths dialogue

### ISSUE THREAD

**Issue by TheDollarBill** [Wynncraft/Issues#5838]
**Typo #1:** In dialogue line [3/10] with Dalben before you give him the 20 emerald blocks, "aquire" is spelled incorrectly. (presumably spelled "acquire")

Screenshot of the dialogue: https://i.imgur.com/s0KxjOh.png

-

**Typo #2:** In dialogue line [6/10], "idotic" is spelled incorrectly. (presumably spelled "idiotic")

Screenshot of the dialogue: https://i.imgur.com/8o5dIKZ.png

-

**Typo #3:** In dialogue line [10/10], the "b" in "blocks" should be capitalized.

Screenshot of the dialogue: https://i.imgur.com/WoSkVol.png

**Comment by AckroWynn** [comment]
Fixed!
