### ISSUE TITLE
 I will not charge the resource pack

### ISSUE THREAD

**Issue by Fexi1** [Wynncraft/Issues#5840]
perpiacere could you help me? I entered on wynncarft three days ago for 2 days went by last night does not want to hear anymore to go I did everything agiornato the launcher etc. but still no go I do not know what to do please help me!

**Comment by Trixter313** [comment]
Is the issue that the resource pack isn't enabled?

If so, go to Multiplayer > Wynncraft > Edit and make sure server resource packs is enabled.

Does that solve your issue?

**Comment by Fexi1** [comment]
trixter313 already done but should not be

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
