### ISSUE TITLE
Bug with loot chest

### ISSUE THREAD

**Issue by SlominPL** [Wynncraft/Issues#5841]
There is a bug with loot chest (tier 3 or 4, idk). I found it during quest "Green Skinned Trouble" in underwater cave. I'm sending screenshot with coordinates. 
Problem is chest can't be opened due to block above it.

Screenshot:
http://screenshot.sh/mKMe0gAEP56H4

**Comment by Moe-Ronickah** [comment]
Ackro, I though that this got fixed?

**Comment by SlominPL** [comment]
Yes, it has been fixed yesterday, I think. I checked it out today and chest can be opened already.
