### ISSUE TITLE
I'm stuck

### ISSUE THREAD

**Issue by SlominPL** [Wynncraft/Issues#5842]
I've been doing WynnExcavation Site B quest. I picked up purple cristal and went through portal. It teleported me to a wall and now I'm stuck. There's screenshot with cords:
http://screenshot.sh/m3ezg0LND0Exm

**Comment by SlominPL** [comment]
Btw - I can't even use my teleport scroll.

**Comment by Trixter313** [comment]
Using the command /kill should get you out.
