### ISSUE TITLE
Entering the Dojo: Shijue Door Barriers

### ISSUE THREAD

**Issue by KnightlyGlade** [Wynncraft/Issues#5844]
If there is a format to submit a bug, I'm sorry for not putting it up. I'm new to github.

Anyways I'm doing a very new quest, as said in the title. However, there are barriers that are blocking the Shijue Room. What should I do about it? Wait until the bug is fixed?

http://i.imgur.com/Cdmdj0p.png

**Comment by Trixter313** [comment]
Have you started the quest? If so, what does it say in your quest book?

**Comment by KnightlyGlade** [comment]
Solve the puzzle of sight in the Shijue Room in the sight challenge.

**Comment by ze-miner3000** [comment]
The same thing has happened to me.

**Comment by TheCalculatorCat** [comment]
In order to remove the barriers, you have to *complete* the puzzle by maneuvering the particles into the [Golden Block]

**Comment by TheLMiffy1111** [comment]
I can actually confirm this issue. Having completed the puzzles twice, the barrier blocks still don't get removed.

**Comment by Trixter313** [comment]
Are you still experiencing this issue? The 1st patch was supposed to fix some bugs with this quest: https://forums.wynncraft.com/threads/1-14-1-the-gameplay-update-patch-1.147905/

**Comment by Moe-Ronickah** [comment]
fixed
