### ISSUE TITLE
Silverfish Dungeon Broken at 1st Stage.

### ISSUE THREAD

**Issue by Pokeninja54** [Wynncraft/Issues#5849]
At the 1st stage of the dungeon, nothing occurs. If you step on the pressure plate, nothing happens, and you are simply stuck there. I was with 4 other people (2 of which were mages, plus me), and we also found a way to go under the floor through a hole to the right of the entrance of the next stage. Needless to say, the redstoning of the 1st stage is broken, as we cannot access or do anything besides teleporting out and killing ourselves.

**Comment by Celsonic** [comment]
This happened to me too.. so many things are broken rip.

**Comment by AnonyPerson** [comment]
This has happened to me too, we tried changing worlds and when we stepped on the pressure plate it worked and the wave started. When we killed the boss and I put the token in the hopper however, nothing happened :/ sad waste of two keys, hope it gets fixed.

**Comment by TheD0ct0r101** [comment]
This is just ridiculous. Why would they release a patch saying its fixed when its not? Do they not test these little things before release?

**Comment by Trixter313** [comment]
Things can pop up last second or right when publishing the world to the public servers. Until it's fixed you can do lots of other fun things and it's a sort of small part of the game compared to all of the great new quests.

Rest assured, it will be fixed very soon. =)

**Comment by Trixter313** [comment]
Should be fixed now! https://forums.wynncraft.com/threads/1-14-1-the-gameplay-update-patch-2.148447/
