### ISSUE TITLE
Stuck In Dungeon

### ISSUE THREAD

**Issue by KillerBee524** [Wynncraft/Issues#5850]
I was doing the new Updated Dungeons and i got this the one part for 4 blue tokens, i got tokens that say to go further i dropped them but nothing happened. 
![2016-08-28_18 41 23](https://cloud.githubusercontent.com/assets/21299339/18038618/381a4c76-6d4f-11e6-8881-a9291a5db95a.png)
![2016-08-28_18 41 28](https://cloud.githubusercontent.com/assets/21299339/18038621/3e9e390e-6d4f-11e6-8aef-c428e88566f2.png)
For Me, Those Items were the only things that dropped for me. So Im Stuck, Im on Server 13, Outside of Troms

**Comment by KillerBee524** [comment]
Only Thing That Drops, and doesn't work
![2016-08-28_18 44 00](https://cloud.githubusercontent.com/assets/21299339/18038636/68b2d772-6d4f-11e6-95a7-3b59f899003d.png)

**Comment by KillerBee524** [comment]
Nevermind, u have to knock down pillars with yellow ones :P

**Comment by Trixter313** [comment]
Try switching to another world and doing it. If you want to get out you can use the command /kill.

**Comment by Trixter313** [comment]
Ah, glad to hear you resolved it
