### ISSUE TITLE
Bug with powder relics

### ISSUE THREAD

**Issue by Lorigami** [Wynncraft/Issues#5852]
So I've gone to both the yellow and blue tier 6 powder relics, and both have given me tier 3 or 4 powders. Big macho issue, seeing as this is the powder update n all. Is this supposed to happen?

**Comment by TheCalculatorCat** [comment]
Collected White Power VI, got White Powder IV… http://i.imgur.com/GQlns1p.png

**Comment by YunoFGasai** [comment]
this is supposed to happen

**Comment by Lorigami** [comment]
Welp. Waste of time to find relics then.
