### ISSUE TITLE
Galleon's Graveyard

### ISSUE THREAD

**Issue by PeterDorvay** [Wynncraft/Issues#5853]
Galleon's Graveyard seems to have many issues. There is a chest floating in the air above the island, The region name seems to be messed up, and there is no dungeon shop npc.

Screenshots: http://imgur.com/a/oBQdL

**Comment by Celsonic** [comment]
@PeterDorvay Thanks for the chest floating, the dungeon npc is outside the entrance, and the region name screw up can also be seen on the player info on the official website. Weird.

**Comment by Moe-Ronickah** [comment]
@Villageacules , any help here?

**Comment by Moe-Ronickah** [comment]
RESOLVED
