### ISSUE TITLE
Hidden City 

### ISSUE THREAD

**Issue by TheReggin** [Wynncraft/Issues#5855]
There's this glitch in this puzzle where when you have all the rings aligned at the same spot, it says, "I'm sorry, but you do not have permission to perform this command. Please contact a server administrator if you believe this is in error".

https://gyazo.com/d5accfa8a0a3e12c9f1df1980b7cd772

**Comment by TheCalculatorCat** [comment]
I'd like to add to this by providing a video of the same bug. It happens when you complete the ring of press a button after completing the ring:

https://youtu.be/Iv22-SWWui4

**Comment by YunoFGasai** [comment]
can confirm this is hapening

**Comment by TheLMiffy1111** [comment]
can confirm

**Comment by Trixter313** [comment]
Is this still happening since the 1st patch?

**Comment by Moe-Ronickah** [comment]
fixed
