### ISSUE TITLE
The Elemental Exercise quest reward can not be identified

### ISSUE THREAD

**Issue by ShayminKeldeo421** [Wynncraft/Issues#5856]
Message: "I can't identify this item! It can not be re identified!"

**Comment by Trixter313** [comment]
Could you post a screenshot of the item? Thanks!

**Comment by ZuraSenpai** [comment]
I can confirm this is true. I just did the quest today and couldn't identify the item.

![elemental exercise quest reward](https://cloud.githubusercontent.com/assets/21308230/18048966/2ceb0ea8-6d9a-11e6-8dd9-e185ae6ef71e.png)

**Comment by ZuraSenpai** [comment]
Here you go. I also could not identify the said item.
![elemental exercise quest reward_1](https://cloud.githubusercontent.com/assets/21308230/18049025/8083bf10-6d9a-11e6-8174-3b8f1c3a7292.png)
![elemental exercise quest reward_2](https://cloud.githubusercontent.com/assets/21308230/18049026/8083dcf2-6d9a-11e6-8841-c80abfdcb701.png)

**Comment by ZuraSenpai** [comment]
I've checked the item identifier today with this quest reward, and I've confirmed that the bracelet can now be properly identified with the item identifier. Thanks for the fix dev team.
![fixed](https://cloud.githubusercontent.com/assets/21308230/18071152/160a4b2c-6e08-11e6-9928-597baf7a04ac.png)

**Comment by Trixter313** [comment]
Glad to hear! =)
