### ISSUE TITLE
Some Build mess at the quest The Fortuneteller

### ISSUE THREAD

**Issue by motoki317** [Wynncraft/Issues#5858]
![2016-08-29_17 55 04](https://cloud.githubusercontent.com/assets/18257693/18046306/416879f6-6e12-11e6-94ba-0f73104ee8cc.png)
![2016-08-29_17 57 44](https://cloud.githubusercontent.com/assets/18257693/18046321/4b1cd28a-6e12-11e6-9685-14c2f61af5b9.png)

**Comment by ColinRioux** [comment]
@Villageacules

**Comment by Trixter313** [comment]
Is the issue still happening?

**Comment by Moe-Ronickah** [comment]
@AckroWynn ?

**Comment by AckroWynn** [comment]
That is work-in-progress barrier work you're seeing, if I recall correctly. Should be done on the build server already, as I put out a request for it!
