### ISSUE TITLE
Skeleton Key

### ISSUE THREAD

**Issue by ZerGom** [Wynncraft/Issues#5859]
So, a Zombie on the Emerald Trail just dropped a Skeleton Key instead of a Decreipt Sewers Key.

**Comment by ColinRioux** [comment]
Both skeleton keys and Decreipt Sewers keys exist in Wynncraft as of the update. Unless you kill a **key guardian**, don't expect any other mob to drop the new dungeon keys. You can upgrade from skeleton keys to the new dungeon keys in most major towns, one being Detlas. 

This isn't an issue, just a new feature. This key converter is very similar to the old emerald converter in 1.13
