### ISSUE TITLE
Creeper Mask

### ISSUE THREAD

**Issue by NovaTwinkle** [Wynncraft/Issues#5864]
Hey so I noticed today while completing the Creeper Infiltration quest that the Creeper Mask can't be identified.
I'm not sure if it's the update that's caused this or a personal issue.
I've tried quitting minecraft and reloading and that hasn't worked.
![2016-08-29_21 46 25](https://cloud.githubusercontent.com/assets/21309305/18050895/a3658c08-6e34-11e6-9354-6b887ac4eb1c.png)
![2016-08-29_21 46 57](https://cloud.githubusercontent.com/assets/21309305/18050901/b0879ff2-6e34-11e6-8755-02bc78628559.png)
Here we have screenshots of the unidentified quest item & the identifier refusing to identify the object. I have also tried the Ragni identifier as well as the Detlas identifier and the issue was the same.

**Comment by Trixter313** [comment]
Are you still experiencing this issue? Some quest items were fixed in the 1st patch: https://forums.wynncraft.com/threads/1-14-1-the-gameplay-update-patch-1.147905/

**Comment by NovaTwinkle** [comment]
All fixed, thank you very much :)

**Comment by Trixter313** [comment]
Glad to hear!

**Comment by pebblewolf** [comment]
Its doing this glitch for me again

**Comment by LordHelmchen98** [comment]
@pebblewolf The quest got revamped and if you didn't identify your old mask you can't do that anymore now. Just do the quest again to get a new mask.
