### ISSUE TITLE
Eltom Item Buyer

### ISSUE THREAD

**Issue by Thidical** [Wynncraft/Issues#5865]
![2016-08-29_13 05 34](https://cloud.githubusercontent.com/assets/21309792/18050999/ddef255a-6de9-11e6-9376-ba207f841d7f.png)
Eltom Item Buyer having some private time with an Eltom Citizen two blocks below where it should spawn ;)

X: 928 Y: 113 Z: 5497

**Comment by ColinRioux** [comment]
@Villageacules

**Comment by Trixter313** [comment]
Is the issue still happening? Sometimes things like this can temporarily happen.

**Comment by Thidical** [comment]
It looks like it's back in its correct place :)
![2016-09-02_10 17 37](https://cloud.githubusercontent.com/assets/21309792/18199030/8a8c206a-70f6-11e6-84b9-6333b68bba42.png)
