### ISSUE TITLE
lost my factory helmet [quest item]

### ISSUE THREAD

**Issue by victorysummery** [Wynncraft/Issues#5866]
hi, so after the recent update, my factory helmet turned into unidentified helmet. I was farming mobs for xp and items, and my inventory was full, so I decided to throw away all the junk item and the item in yellow text away for picking loot. therefore, i click on the item and throw it away in my inventory just to get a new item on the ground, then I noticed that the item I just throw was a quest item by reading the chat after closing the inventory page. when i try to throw away the stuff i just picked up, i noticed that the item is gone forever, so yea, would be great if someone can help me with this. 
ps, sorry about the bad eng

**Comment by thecoolkogut4** [comment]
type /fixquests on the class you lost the helmet on. it should give you back your helmet.
