### ISSUE TITLE
Elemental Exercise 

### ISSUE THREAD

**Issue by jetpackguy48** [Wynncraft/Issues#5867]
The reward item for elemental exercise wont identify for some reason, it says "I can't identify this item, it can't be reidentified", but its not identified, also I think powders are too easy to get now, I got for in under an hour and I think this is too often and does the neutral to fire mean less neutral but more fire damage?, also, the new soul point system might be unfair to people that get internet or bad computer related deaths (such as old computers that lag too much and a generally bad internet)

**Comment by Trixter313** [comment]
The issue should be fixed. You can post suggestions on the forums, in the suggestions area. =)

**Comment by jetpackguy48** [comment]
its fixed
