### ISSUE TITLE
A bug about the ??? quest.

### ISSUE THREAD

**Issue by Liamzigge** [Wynncraft/Issues#5869]
Minecraft name: Loka1234 rank: [Vet]

I dont know if your really allowed to talk about this, but i have completed the ??? quest and i even have the altum spatium in my inventory but for some reason it says Not Started.

I dont know what caused this and if a mod reads this i am more than happily to give details about the quest to verify that i have done it.

Thankful for any answers :)

**Comment by ColinRioux** [comment]
There has been a new version of **???** released with the 1.14.1 update (as stated in the changelog). The old one has been removed. It's now okay to talk about the quest. In other words, if you completed the old ???, you can still do the new one, and talk about it as much as you want. 

So, you are supposed to keep your Altum Spatium (if you have it), and everything is okay. 
Please close @Trixter313
