### ISSUE TITLE
assassin vanish spell 

### ISSUE THREAD

**Issue by casparof** [Wynncraft/Issues#5870]
uhm idk if its a bug but its really shit

when i vanish my mana (aka food) is going down when i am running 
if its a bug pleas fix it when it is not do something on it cuzz it sucks really bad en assassin is shit buzz of that tnx

**Comment by Sxmi** [comment]
That's because Vanish is a spell which causes you to gain speed, jump boost and invisibility therefore it should take mana instead of using your spring bar. So this is intended and does infact buff the Assassin due to the new spring bar implementation.

**Comment by Trixter313** [comment]
I agree with @Sxmi
