### ISSUE TITLE
Powders of same type not stacking

### ISSUE THREAD

**Issue by mistleberry** [Wynncraft/Issues#5871]
You can't stack the powder you buy from the merchant on the Enzan's Brother's quest with any other powders you have received from Relics, even if they are the same type and level.

**Comment by ries01** [comment]
also powders that you already had don't stack with relic powders

**Comment by mistleberry** [comment]
Yes, they both don't stack.

**Comment by Dystinct** [comment]
My Personal Quick Fix:
If you drop the troubling powder on the ground, fill up your inventory slots with items and then walk back over the powder. As long as you have a powder of the **SAME** _type_ and _level_ it will stack @mistleberry

**Comment by CrapotteQc** [comment]
They need to fix it!!!

**Comment by Moe-Ronickah** [comment]
It can't be fixed, it will never be fixed, there is nothing to do about it.  If it's an old powder and a new powder, we are out of luck.

**Comment by theonlygusti** [comment]
No, I disagree.

Just write some code that scans the inv. for 'old' powders and makes them like the new ones so they can be fixed.

This is ridiculously easy, just look in each slot for an item of correct type and name :P Then replace it with the 'new' stackable version.

**Comment by theonlygusti** [comment]
@Moe-Ronickah

**Comment by LordHelmchen98** [comment]
Or just upgrade them at the powder master. Anyway the devs have enough other stuff to do.
