### ISSUE TITLE
Underice quest 

### ISSUE THREAD

**Issue by ries01** [Wynncraft/Issues#5873]
I don't know if this is me being stupid but, I was doing the underice quest all went well until I came to the part to get bait to catch the fish. becose there was none. they say its in the lumber camp but there is simpely none in the camp. I also joined defferent servers and checked the quest book but there is no bait in the lumber camp northwest.

**Comment by ColinRioux** [comment]
Well for starters: https://wiki.wynncraft.com/index.php?title=Underice

To get the bait, you must kill the mob in the lumber camp (in the left house). 
Then to catch the fish, drop the bait into the water by the dock. Then the pufferfish should drop. 

Some tips: Kill the bait mob a few times to have spare bait in case the fish doesn't drop.

**Comment by sethcon55** [comment]
I don't know if this is me being stupid as well, but the "mob" is simply not spawning, and I cannot obtain the bait.

**Comment by 0x0000null** [comment]
I can't seem to find any neutral mobs as the wiki describes.

**Comment by Moe-Ronickah** [comment]
The pufferfish spawn on the dock, behind you, so that you don't lose them in the depths of the river.  You're just too focused on the pretty splashing water.  So was I, originally.
