### ISSUE TITLE
Alderoi's Secret part II puzzle does not work

### ISSUE THREAD

**Issue by xElitaa** [Wynncraft/Issues#5875]
I am playing through Aldorei's Secret Part II, and it appears that the puzzle with the shrine doesn't work at all. After trying everything I could, I looked on the wiki for the answer, and the pressure plates that are supposed to be changing the clay blocks to emerald blocks do not function.

**Comment by Trixter313** [comment]
Is the issue still happening and does switching to another world help? Sometimes redstone can get randomly broken on just one world until the world restarts.

**Comment by Trixter313** [comment]
Should be fined! https://forums.wynncraft.com/threads/1-14-1-the-gameplay-update-patch-2.148447/
