### ISSUE TITLE
Horses Floor (Skeleton Dungeon)

### ISSUE THREAD

**Issue by ModingMc** [Wynncraft/Issues#5879]
Fell into redstone in skeleton dungeon.

http://imgur.com/gallery/agnM2

**Comment by Trixter313** [comment]
You can use /kill with 3+ soul points to get out. Horses glitching through blocks sometimes is a vanilla Minecraft issue so there's not much we can do about it. I'd just suggest to be careful when you're using the horse in the dungeon.
