### ISSUE TITLE
Potion Making quest item

### ISSUE THREAD

**Issue by Endertricity** [Wynncraft/Issues#5885]
When I was going into the boss room for Potion Making, a higher level player came in, killed the boss, got the item, and ran. Now the boss won't spawn for me and I have no way of geting Essren's Coat.

**Comment by 0x0000null** [comment]
Exit through the portal and go back in

**Comment by Endertricity** [comment]
you think I haven't done that?

**Comment by 0x0000null** [comment]
Try switching servers; the boss should respawn.

**Comment by Endertricity** [comment]
THIS STILL DOESN'T WORK, WHY'D YOU CLOSE IT
Changing lobbies does nothing.
/class does nothing.

Because my low-level warrior needed to complete the quest, I got up to that point on my high-level assassin, and gave the coat to my warrior. So, now my assassin can't finish the quest.
![screen shot 2016-08-31 at 9 50 45 am](https://cloud.githubusercontent.com/assets/17186189/18131376/8cc86c2c-6f60-11e6-80b4-d49cd52cd578.png)

**Comment by Endertricity** [comment]
Never mind, there were some invisible pressure plates I needed to stand on. I got the coat, everything's good now. (But your answers didn't work)
