### ISSUE TITLE
Missing items.

### ISSUE THREAD

**Issue by spockmenow** [Wynncraft/Issues#5887]
After logging onto the update I went to the powder merchant and started trading all of my powders in. Then after doing so I went to bank to grab my LE (I had 31) but I couldn't find my LE at all. Later on after trying to farm for more money in an attempt to get it back thinking maybe I spent it on powder (which is unlikely) I went to my bank to grab my horse after checking my inventory and I had no chestnut horse (28/30). I have a feeling this is not just a mistake on my part.

**Comment by Moe-Ronickah** [comment]
I have a feeling that you may either still be using "Q" for your drop key, or that you got hacked.
