### ISSUE TITLE
Dying while fighting Gorgu will respawn you in the Beginner Area

### ISSUE THREAD

**Issue by fourthhero** [Wynncraft/Issues#5888]
If you die fighting Gorgu during the "A Fighting Species" quest, you'll respawn in the beginner area, as in the area when you first start a new class, before Ragni. Not sure what other info to give other than that.

**Comment by Trixter313** [comment]
Some quests teleport you out of the normal Wynncraft map so when you die you can respawn in a different place than expected. Also, the beginning area is the fallback teleport location in case something goes wrong so you will rarely be teleported there on death.
