### ISSUE TITLE
Can't join in the hub

### ISSUE THREAD

**Issue by xxXDragon67Xxx** [Wynncraft/Issues#5890]
Is been a while every time try to log in the hub i been kicked for fly i can't do nothing only wait if a miracle can let me join

**Comment by xxXDragon67Xxx** [comment]
pls help :,C

**Comment by Trixter313** [comment]
Try holding shift or try holding forward right after clicking join so that your player does the action immediately when logging in.

Duplicate of https://github.com/Wynncraft/Issues/issues/5289
