### ISSUE TITLE
I got stuck in a 1 by 2 block are after sleeping in a bed at night as a joke

### ISSUE THREAD

**Issue by AnotherLoLfan** [Wynncraft/Issues#5893]
I was exploring and found a Inkeeper and as it was night as a joke i slept in one of the beds but when i woke up in a 1 by 2 block area if possible can you fix this.
![Bug](https://cloud.githubusercontent.com/assets/21321619/18069161/173716ee-6e3d-11e6-96b8-1072a8047d47.png)

**Comment by xElitaa** [comment]
Just do /kill

**Comment by apeklets** [comment]
Same thing happened to me. /kill or /die will fix it for you. But obviously this isn't supposed to happen

**Comment by xElitaa** [comment]
These bugs aren't really priority to be fixed since it's not the servers direct fault, as it isn't necessary to sleep in beds. They have higher priorities than an unfortunate bug that just costs you 2 soul points.
