### ISSUE TITLE
Ice Nations Quest Helm Glitch

### ISSUE THREAD

**Issue by xSlaying** [Wynncraft/Issues#5894]
After I finished Ice Nations quest about 2 weeks ago, I identified the helm, and put it on. I haven't taken it off so far, but after the new update came out, the helmet suddenly became unidentified. Thx for reading this! :D -xSlaying

**Comment by Celsonic** [comment]
pretty sure you have to /fixquests

**Comment by ColinRioux** [comment]
Or you can reidentify the item.
