### ISSUE TITLE
Breathing Helmet

### ISSUE THREAD

**Issue by Zamora09** [Wynncraft/Issues#5895]
The breathing helmet is broken for the "From the Mountains" Quest, you cannot go into the whirlpool with the helmet on

**Comment by loly110** [comment]
Breathing Helmet 2?
You can buy it at neesak's armour shop

**Comment by Trixter313** [comment]
Let us know if @loly110 's suggestion resolved your issue, thanks!

**Comment by Moe-Ronickah** [comment]
RESOLVED

**Comment by Celsonic** [comment]
If so @Moe-Ronickah Lock please?

**Comment by Moe-Ronickah** [comment]
Missed that.
