### ISSUE TITLE
Elemental Exercise is BUGGED HELP

### ISSUE THREAD

**Issue by shockingstar** [Wynncraft/Issues#5896]
So the first time I tried this quest I got stuck between the two rooms that suppose to collapse. So I had to kill myself. When I came back I could not reenter the room thats suppose to collapse and now its an invisible wall. And I can't leave the cave so once again I had to kill myself. I would just ignore this quest but i can't get rid of the quest items which takes up space. Me and my friend runedson are having this problem I don't know if someone can try resetting this quest for  us or something

**Comment by Trixter313** [comment]
What does it say in your quest book and does using the command /fixquests return anything for the quest?

**Comment by shockingstar** [comment]
@Trixter313 I tried /fixquests it gave me back an item i already had which is used to get the elemental item. My quest book says to get the root from the cave, which i go to but then i get stuck because theres an invisble wall at the end of the cave

**Comment by Trixter313** [comment]
Hmm, I haven't had any personal experience with this quest so I can't give specific advice but hopefully someone who can help will come along shortly.

**Comment by Moe-Ronickah** [comment]
RESOLVED
