### ISSUE TITLE
Underice Quest Helmet Glitch

### ISSUE THREAD

**Issue by KappaKlaus123** [Wynncraft/Issues#5897]
I was recently completing the newly edited Underice Quest. Once I got into the underwater cave, I took of my Breathing Helmet II, and put on a different helmet. When I did that I was teleported the tutorial area that a new player is sent to when they first log on. 

![2016-08-29_19 25 45](https://cloud.githubusercontent.com/assets/21322832/18070878/e6a7e26a-6e1e-11e6-8251-47fc60250315.png)

**Comment by ColinRioux** [comment]
This is a known "bug". I wouldn't really call it bug. It's like a failsafe mechanism of sorts. The same would happen if you took off the Gert mask in the Gert camp or taking off the climbing helmet in Maro peaks.

**Comment by KappaKlaus123** [comment]
Oh ok. Thanks for the info!
