### ISSUE TITLE
Powder Won't stack

### ISSUE THREAD

**Issue by CrapotteQc** [Wynncraft/Issues#5899]
I can't stack green powder 1 on green powder 1... I tried with yellow and red too... Not working!

**Comment by coreynj** [comment]
It would seem that the NBT values for powders obtained from Relics and powders obtained from chests are different, so they refuse to stack together.

**Comment by 0x0000null** [comment]
The NBT data is the same, which is why they seem to stack client-side, but for some reason the server refuses to allow them to stack.

**Comment by ninja2003** [comment]
They got to fix this. it is sooooo annoying

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/5871
