### ISSUE TITLE
Maltic Citizen Dialogue Typo

### ISSUE THREAD

**Issue by GlitchDoesMC** [Wynncraft/Issues#5900]
![oie_kgrs7dl6y0o8](https://cloud.githubusercontent.com/assets/13888446/18071995/4167191a-6e28-11e6-8b9a-b7bfd609ebbf.png)

I'm sure that word is supposed to be 'of', not 'os'.
Didn't know where to post these kinds of things so I decided GitHub would be a good place.

**Comment by Moe-Ronickah** [comment]
@AckroWynn

**Comment by AckroWynn** [comment]
Done!
