### ISSUE TITLE
Died in a fighting species, spawned at the beginning

### ISSUE THREAD

**Issue by Phton** [Wynncraft/Issues#5902]
So, I died in a fighting species while fighting Gorgu, and then I spawned at the beginning at the king's recruit.
![2016-08-29_20 59 20](https://cloud.githubusercontent.com/assets/21324239/18072478/a62410ca-6e2c-11e6-86f5-1c4842b45fc7.png)

**Comment by Trixter313** [comment]
The beginning area is a fallback teleport incase something goes wrong, so you will rarely be teleported here on death.
