### ISSUE TITLE
Stuck in Ice Barrow Dungeon

### ISSUE THREAD

**Issue by DimaIva** [Wynncraft/Issues#5906]
Hi all. Why im stuck when I got teleported to boss? Im stuck in black coal box 3x3x3.
![2016-08-30_03 35 00](https://cloud.githubusercontent.com/assets/21330149/18078719/2188f66a-6e9e-11e6-83c5-753e225f93ed.png)
![2016-08-30_03 35 04](https://cloud.githubusercontent.com/assets/21330149/18078721/23ef0642-6e9e-11e6-92c8-29148eac2ae0.png)

**Comment by Trixter313** [comment]
Try using the command /kill and doing the quest again.

Let us know if that solves the problem, thanks!

**Comment by Trixter313** [comment]
Also it appears some issues for this area have been fixed: https://forums.wynncraft.com/threads/1-14-1-the-gameplay-update-patch-1.147905/
