### ISSUE TITLE
Silverfish(old) dungeon missing blocks 

### ISSUE THREAD

**Issue by mrdeadi** [Wynncraft/Issues#5907]
Lot of missing blocks,and open'd redstone and command-blocks system.
Pic's:

1: http://i.imgur.com/Gqo0X2t.png
2: http://i.imgur.com/nbEoMVu.png
3: http://i.imgur.com/3t6DVbX.png
4: http://i.imgur.com/96dQCC0.png

Please fix ^^

**Comment by Trixter313** [comment]
If the old dungeon is gone this is no longer an issue.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/5849
