### ISSUE TITLE
Recipe For Disaster bug

### ISSUE THREAD

**Issue by Kroko64** [Wynncraft/Issues#5909]
It says in the questbook that i have to present my dish to Hamsey but i cant enter the Chef's dining room

**Comment by thecoolkogut4** [comment]
im having the same problem, ive tried to switch servers but that wont do anything.

**Comment by Trixter313** [comment]
Are you still experiencing issues with this quest? The 1st patch was supposed to fix some issues with this quest: https://forums.wynncraft.com/threads/1-14-1-the-gameplay-update-patch-1.147905/

**Comment by thecoolkogut4** [comment]
I figured out what's wrong, when you go to the place to get tp'ed, there is a trip wire the looks for the item in your inventory (pie, stew etc) if it finds it then it will tp you, but if it doesn't (which it doesn't find for everyone) it won't tp you.

**Comment by Moe-Ronickah** [comment]
Trip wires have been fixed, I believe.
