### ISSUE TITLE
Quest: The House of Twain

### ISSUE THREAD

**Issue by BlackPhoeniix** [Wynncraft/Issues#5911]
It is impossible to identify the helmet quest

**Comment by Daimont** [comment]
Same here, i didnt started the quest, just looking for the full ghost set but the helmet cannot be identify

**Comment by Trixter313** [comment]
Are you still experiencing this issue? Some quest items were fixed in the 1st patch: https://forums.wynncraft.com/threads/1-14-1-the-gameplay-update-patch-1.147905/

**Comment by 808hunters** [comment]
i still cant unidentify it

**Comment by Trixter313** [comment]
@808hunters did you mean identify or unidentify?

**Comment by Trixter313** [comment]
Should be fixed now =)
https://forums.wynncraft.com/threads/1-14-1-the-gameplay-update-patch-2.148447/
