### ISSUE TITLE
I Beat The Decreipit Sewers! Twice In A Row??

### ISSUE THREAD

**Issue by Nexonix** [Wynncraft/Issues#5915]
Yup, you read the title. For some reason when I beat the decreipit sewers dungeon, it registered twice, i got double the loot, xp etc. Heres a snapshot of my chat that displayed it twice
![2016-08-30_09 13 30](https://cloud.githubusercontent.com/assets/21341984/18097612/5d197700-6e93-11e6-89c4-0f3ecac797cf.png) don`t worry tho, I threw away the items that I got from the second win away where no one would find it. including the emeralds, but sadly, I cant get rid of the xp. Oh well...

**Comment by Trixter313** [comment]
I'd say this was probably just a one time glitch, if it happens again let us know. =)
