### ISSUE TITLE
Elemental exercise cant continue 

### ISSUE THREAD

**Issue by rallygrabben** [Wynncraft/Issues#5919]
in elemental exercise at the end when you are going to give the study results to Ragon i cant get the study results, i threw out the fire wand when i was going to kill the beast to get space for the thing he droped and when i gave the thing to Ragon i was going to pick the wand up again but it was not there
and then i did not think much about it but when i came back from the cave i needed the study results but i did not have the wand so i could not continue the quest so now im stuck. Hope you can help me have a good day.

My minecraft name is rallygrabben.

**Comment by Trixter313** [comment]
Does using the command /fixquests return any items for the quest that help? Also, what does it say in your quest book?

**Comment by rallygrabben** [comment]
Thanks and i dont remember what it said in my book
