### ISSUE TITLE
ID Switch

### ISSUE THREAD

**Issue by DirtyDoge** [Wynncraft/Issues#5921]
Not sure if this is intentional or not, but the IDs on my Altum Spacium were switched from 20% XP and 10% reflection to 11% XP and 20% reflection, it didn't have to be re-identified or anything.
This happened a day after the gameplay update released.

**Comment by Trixter313** [comment]
Do you have a screenshot of the item's previous identifications or do you just remember it that way? Is it possible you just remembered it incorrectly?

**Comment by DirtyDoge** [comment]
I don't think I have a screenshot, will look later.
But I highly doubt I would forget something as awesome as a max XP Altum Spacium.

**Comment by Moe-Ronickah** [comment]
ID's on many items have been updated.
