### ISSUE TITLE
Necklace Vanished

### ISSUE THREAD

**Issue by DoctorWhen** [Wynncraft/Issues#5924]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.
I was playing Wynncraft and noticed that the legendary necklace I got from WynnExcavation D vanished. I did not die so I am wondering what happened. Thanks,
DoctorWhen

**Comment by Trixter313** [comment]
Did you recently upgrade your bank storage?

**Comment by DoctorWhen** [comment]
no, the last time I upgraded my bank storage was 1.75 years ago

**Comment by Trixter313** [comment]
Okay, then all we can do is assume that it was accidentally dropped. We know nothing more than you do about the particular item being lost. Wynncraft has a strict no refunds policy so there's nothing we can do to return the lost item. To prevent hotbar items from being accidentally dropped you can change your drop key to something else that's less likely to be accidentally pressed but you could still drop something while moving things in your inventory so just be cautious of it.

**Comment by DoctorWhen** [comment]
it was not in my hotbar, it was equipped.

**Comment by Trixter313** [comment]
It was most likely accidentally taken off and thrown then. Luckily, the necklace itself isn't untradable so you can buy another from a player.
