### ISSUE TITLE
Can't spend Skill Points anymore

### ISSUE THREAD

**Issue by zoggi2000** [Wynncraft/Issues#5925]
Hi,

Well i have played for a few hours now and already leveled up and used my skill points, but when I try to spend points, they dont add anything but i use them up.
Even after relogging, reselecting the character and reseting my skill points pultiple times, I still cant spend any skill points anymore

**Comment by Trixter313** [comment]
Take all armor and accessories off and add up your spent soul points to see if it totals the amount you're supposed to have.

**Comment by zoggi2000** [comment]
Oh, I know why my skill points didnt show up...
My helmet gives me -3 Strength and -4 Defense, so when I added points they still weren't there because of my helmet... I'm a big idiot ^^
Thank you for your help!

**Comment by Trixter313** [comment]
Glad to hear it got sorted out! =)
