### ISSUE TITLE
Unidentified Abyssal Amulet cannot be identified, but Gernald's Amulet can be re-identified repeatedly?

### ISSUE THREAD

**Issue by MusicScore** [Wynncraft/Issues#5932]
As the title suggests. After completing the Eye of the Storm quest, when I try to identify the unidentified Abyssal Amulet, the Item Identifier returns the message "I can't identify this item! It can not be reidentified." Yet, when I go to re-identify Gernald's Amulet, I can probably infinitely re-identify it. I've already tried it once, and the Item Identifier does not stop me from putting Gernald's Amulet back into the loop.

**Comment by Trixter313** [comment]
The recent update made reidentifying items possible by just putting them back in the identifier so that is intended but you should be able to identify the other amulet.

**Comment by MusicScore** [comment]
I've logged out and logged back in, but the Item Identifier still refuses to identify the Abyssal Amulet.

**Comment by Moe-Ronickah** [comment]
@AckroWynn , do you know if this was fixed?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
