### ISSUE TITLE
Resource Pack Grass Texture Issue

### ISSUE THREAD

**Issue by SirMrTacky** [Wynncraft/Issues#5933]
Alright so I decided to download a mini map mod so it can make getting to quests much easier and when i log into wynncraft with the mod enabled the texture of grass just turns into those pink/black tiled error blocks. For some reason this is only on wynn's official texture pack and i have not seen it happen with any other texture pack I used it with. If there is any way to fix this error or download the texture pack without having to download another mini map mod, a response will be greatly appreciated. Image of the error below.

![2016-08-30_21 13 39](https://cloud.githubusercontent.com/assets/21346081/18112659/3c3515a8-6ef7-11e6-9fd0-d43fca93d19e.png)

![2016-08-30_21 14 05](https://cloud.githubusercontent.com/assets/21346081/18112675/5ce095c0-6ef7-11e6-8e5f-8719ad87f68c.png)

**Comment by ColinRioux** [comment]
Please use 1.8.9

Even with the Gameplay update, Wynncraft's main version (and texturepack version) is still 1.8.9. 

The network just allows 1.9 and 1.10 clients.

**Comment by SirMrTacky** [comment]
alright thanks ill just use the outdated version then...
