### ISSUE TITLE
Dungeons + Deaths

### ISSUE THREAD

**Issue by Ninjazzzzzz** [Wynncraft/Issues#5934]
Basically, here's how it goes.
My assassin is in the Ice Barrows dungeon, and I switch classes to my Archer, which is in Rodoroc. While in Rodoroc, my Archer died, and I respawned outside the Ice Barrows dungeon.

This means that when you have a class in a dungeon, you will, no matter what, respawn at the entrance. Even when you switch classes, this will happen.

**Comment by Moe-Ronickah** [comment]
If you were in a boss fight, and switch classes, that will always happen.  Do you remember if you were in the boss fight?

**Comment by Moe-Ronickah** [comment]
@Ninjazzzzzz , hello?

**Comment by Ninjazzzzzz** [comment]
My bad, I forgot about this.
No, I wasn't in the boss fight, I was in one of the rooms before it.
I think the reason this happens is because the game still thinks that you're in the dungeon since it isn't completed, and it will automatically spawn you outside the dungeon after dying.

**Comment by Moe-Ronickah** [comment]
I don't believe that this should be happening anywhere except during a boss fight.

**Comment by Moe-Ronickah** [comment]
@AckroWynn , was this behavior changed, recently?

**Comment by AckroWynn** [comment]
@Moe-Ronickah I have alerted Salted, and he said he will bring it up with Jumla today. Thank you for reporting!
