### ISSUE TITLE
Issue of not receiving Vip +/Vet benefits

### ISSUE THREAD

**Issue by bolt88** [Wynncraft/Issues#5937]
I'm not sure if this is just me but i have noticed that i am not receiving the in game benefits of Vip+ i'm only receiving Vip benefits. I'm for sure not getting the 'Mythical Player Effects' and the 'Attack Animations ' that Vip+ should have, im also not receiving the skeleton horse cloak and undead disguises. Iv been Vip + for a long time (Vet tag) but i have been to lazy to fix this but finally i am here. 
I am not certain if anyone else has this issue or if i'm the only one but hopefully this can be fixed?
Thanks :)

-Note i am receiving all other Vip+ and Vip benefits just not these.

**Comment by Moe-Ronickah** [comment]
As this is an issue dealing with real-world money, please contact support@wynncraft.com and describe the problems to them.  Be aware that it may take them up to four days to respond, not including the notice about an issue number.
