### ISSUE TITLE
war scream and life steal for warrior is not working 

### ISSUE THREAD

**Issue by Memoriesoo** [Wynncraft/Issues#5938]
I was grinding around Rodoroc, everything goes well until I discover that I can't deal damage with war scream (poison is still working). This annoys me a lot. This may not be a specific case as my friend also says that its not working. 
Please have this bug fixed SOONtm so as to let warriors play normally :P

**Comment by ALEEEEEEEEEEX** [comment]
Yeah having the same problems..

**Comment by Moe-Ronickah** [comment]
fixed
