### ISSUE TITLE
Under the Underworld crypt entrance.

### ISSUE THREAD

**Issue by mistleberry** [Wynncraft/Issues#5945]
So I was riding on my horse, going to the underworld crypt to do the dungeon, but, as I got off of my horse to give the key collector the key, I fell under the map. I have a picture with my coords to show you where I am, and I teleported out.
![2016-08-31_10 49 15](https://cloud.githubusercontent.com/assets/21312604/18124232/494b609a-6f69-11e6-8394-cc1c9e6aa56d.png)
![2016-08-31_10 49 27](https://cloud.githubusercontent.com/assets/21312604/18124233/494d9630-6f69-11e6-9a55-5b56a64c14f2.png)

**Comment by Moe-Ronickah** [comment]
Don't ride horses into tight spaces, MC doesn't like it.
