### ISSUE TITLE
Stuck in stone

### ISSUE THREAD

**Issue by XFarwar** [Wynncraft/Issues#5946]
Hi, I used the spell wich teleports you where you are looking to, and now im stucked in this coords:
-616 / 54 / -3053. I tried using a scroll, but it doesn't work, also re-using the spell, but nothing happens.

Can you help me please? I need to be online?

Thanks.(ps: sorry for my english xD)

**Comment by Trixter313** [comment]
Using the command /kill should get you out. =)
