### ISSUE TITLE
Cant join wynncraft

### ISSUE THREAD

**Issue by Ninni51** [Wynncraft/Issues#5948]
Everytime I try to enter wynncraft I manage to get into the lobby to choose a server, but when I choose one it simply remains stuck at "downloading terrain" help please

**Comment by ColinRioux** [comment]
A few questions:
1. Have you tried letting it "finish" downloading the terrain?
2. Are you using version 1.8.9?
3. Have you tried disabling the texture pack?
4. It could also be your network, what's your download speed at speedtest.net ?

**Comment by Ninni51** [comment]
thanks man it was the 1.8.9 the problem I fixed it
