### ISSUE TITLE
Purple and Blue

### ISSUE THREAD

**Issue by ThatChudley** [Wynncraft/Issues#5949]
I'll get straight to the point- the jumping parkour in Purple and Blue is an absolute freakin' joke. Since minecraft updated, the old glass panes have become tiny, difficult to see, and even harder to land on, let alone to be able to somehow get a run up on them for jumping! Also, assassin classes' shadow clone is now solid and willpush you off of the 1x1 platforms even when you hold shift. Also the squid frequently climb up the waterfalls and knock you off - even after having killed all of the squid in the pool. 

I am aware that lag is something that cannot specifically be fixed and is therefore inevitable and will occasionally screw a player on a puzzle like this, however, when the puzzle is unecessarily difficult to a level where it is beyond joyless and into the realms of wrist-slittingly painful, it needs to be changed. 

I would suggest removing the squid from the area completely and sometimes the magic area node creatures follow you anyway and shoot at you. Also I suggest making all of the puzzle out of the stone half slabs, or making it so it doesn't disappear (Although that style is fun- like in Aldorei's secret part 2).

I really hate to show any dislike to Wynncraft as I truly love it- but this section NEEDS editing. Many thanks

That_Chudley

**Comment by MusicScore** [comment]
js you can still log on with 1.8.x, so the glass panes become much more visible.

**Comment by Trixter313** [comment]
This would go better in the suggestions area on the forums: https://forums.wynncraft.com/forums/general-suggestions.69/
