### ISSUE TITLE
Even more guild bugs

### ISSUE THREAD

**Issue by Clarence117** [Wynncraft/Issues#5951]
People with a changed name cannot be promoted in the guild, and now that leader spammed the command giving me captain, I now see triple chat and my name has been quadruplicated in the guild. Of course, I don't have captain. Haven't seen this bug before.

**Comment by thecoolkogut4** [comment]
yup, this happens in my guild all the time. tell him to make you the rank that you were before you got captain then to kick you. (this fixes the bug for me)
