### ISSUE TITLE
Crashing in bank causes loss of items

### ISSUE THREAD

**Issue by MMaster321** [Wynncraft/Issues#5952]
When i crash in my bank i lose items i have lost my sprintguard pants and i need them D: How do i stop this?

**Comment by thecoolkogut4** [comment]
sorry your post is a little confusing. when you open your bank up you crash? is that correct? or did you crash while you bank was open and you lost your items?

**Comment by ColinRioux** [comment]
I'd still like to know how to reproduce this issue.
That aside, Wynncraft still enforces a strict no refund policy. There are no exceptions, as this keeps the game fair to all players.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
