### ISSUE TITLE
I lost my Class

### ISSUE THREAD

**Issue by MightyJuiceBox** [Wynncraft/Issues#5953]
I was playing Wynncraft on 8/30/16 And I had just completed a quest so I decided to get off because it was getting late. Then on 8/31/16 I got back on to play more and my Archer class was just gone. I don't know how it happened and does anyone one know if there is a way to fix it? Also this is what I saw when I opened it. 

![2016-08-31_11 01 38](https://cloud.githubusercontent.com/assets/21366234/18136288/5f97dbf2-6f6a-11e6-9e4e-2b6a65701aca.png)

**Comment by thecoolkogut4** [comment]
they have a no refund policy so you won't be getting your class back any time soon... You probably clicked delete class when you logged off.

**Comment by MightyJuiceBox** [comment]
But that screen doesn't show when you log off

**Comment by IcyShrub** [comment]
Maybe marked it for delete when you got on? So when you got on the next time it had finished the countdown.

**Comment by DirtyDoge** [comment]
Did you accidentally go into the delete class "are you sure" screen by right clicking the class?
Once in there, you have to click the no X, not press esc or the yes checkmark.
