### ISSUE TITLE
Olux Spear

### ISSUE THREAD

**Issue by LuckyLuke313** [Wynncraft/Issues#5954]
Dear Wynncraft team,

today (31.08.2016) around 18:26 my "Olux Prized Spear" just disappeared from my inventory i killed a Zombie near Troms and it disappeared i did not drop the Weapon it just disappeared. I guess this is the right Thread to post if not i am sorry.

Thanks for your fast help

LuckyLuke313

**Comment by ColinRioux** [comment]
Wynncraft enforces a strict no refund policy. This goes for all players and there are no exceptions. Sorry, but you'll probably find a better spear down the line.

**Comment by Moe-Ronickah** [comment]
Change your drop from "Q" to "Delete".
