### ISSUE TITLE
Taproot broken for Finding the Light

### ISSUE THREAD

**Issue by Zamora09** [Wynncraft/Issues#5956]
I am trying to start the quest for Finding the Light, I have the taproot in my inventory but it doesn't let me to talk to the Forest Guardian.

http://prntscr.com/ccl9b4

I am assuming the taproot doesn't work but it could be something else

**Comment by thecoolkogut4** [comment]
you also need the volt goat horn to start the quest. a yellow sheep drops the horn in the light forest. (it spawns close to the ultimate weapon quest start)

**Comment by Zamora09** [comment]
Yea thanks, I got it
