### ISSUE TITLE
Horse Glitch and *theoretically* how to fix it.

### ISSUE THREAD

**Issue by ReyDeLosCreepers** [Wynncraft/Issues#5957]
since the gavel update or earlier, horses have been kind of broken, i found out how the bug theoretically works and how to theoretically fix it.

1. what is the bug, sometimes when you are riding a horse, chucks will stop loading, music will appear to stop playing, and when you get of you're horse, you will be near the location where the chucks appeared to stop loading, it happens often and gets annoying.

2. it works because when you are on the horse, the server lags, and thinks you and the horse are in a different place from where it appears to be on the players screen. the server thinks that the horse got stuck on a block but it appears that you are still moving from the players point of view. music stops playing because it plays from where the server think it plays, and if you get far away from it, you won't hear it.  and chucks will stop loading because they load from. etc.

3. I think it is fixable by teleporting where the server thinks the horse and player is to where the player thinks the horse is or vice versa using the execute command.

**Comment by ColinRioux** [comment]
The horse "glitch" happens because wynncraft, even with the new update, is still version 1.8.9. (It just allows higher version clients to connect to the network). 

I suggest downgrading to 1.8.9 and I 100% guarantee the glitch is fixed.
