### ISSUE TITLE
Shattered Mind Talked to NPC as the server restarted

### ISSUE THREAD

**Issue by DJNothing** [Wynncraft/Issues#5959]
So I was stupid and Talked to the NPC in "Shattered Mind" while the server was restarting and now she wont update my Quest book
It says: "Try to find civilization in the strange forest"
But Likeru? who would update the quest book just says: "Well?! Did you find the rabbit yet? No?! Then go find it! It went in the house,by the big frog! HELLO FROG!"
If some staff could set my Questbook to the next stage that would be nice.

IGN: xINothing

**Comment by DJNothing** [comment]
Still need help

**Comment by Trixter313** [comment]
Does using the command /fixquests return any quest items for the quest?

**Comment by DJNothing** [comment]
This quest doesnt need any items.

**Comment by Moe-Ronickah** [comment]
Just try /fixquests anyways.  Sometimes it resets internal quest markers.  If it doesn't work, you are out of luck, for now.
