### ISSUE TITLE
Powder upgrade glitch

### ISSUE THREAD

**Issue by SkySaito** [Wynncraft/Issues#5960]
Hello there !
As the new update arise, I have found a bug about the newly powder master. When you try to upgrade your powders without giving him 4 items, he will give you your powders back. But he will still keep the money. Is that because he's just a vicious little guy or a normal bug ? Thanks for incoming responses and possibly a fix !
Sky's out !

**Comment by Moe-Ronickah** [comment]
@AckroWynn , are powder merchants mean?

**Comment by AckroWynn** [comment]
I will report this to Salted! Thanks ;D

**Comment by AckroWynn** [comment]
Reported!

**Comment by Moe-Ronickah** [comment]
RESOLVED
