### ISSUE TITLE
Theorick is Broken

### ISSUE THREAD

**Issue by nathanwold** [Wynncraft/Issues#5962]
I was in the Ice Barrows fighting Theorick when one of my spells (I was playing as a warrior) knocked Theorick into the edge of the arena but the game wouldn't let me get to him. So I killed him using my spells and it congratulated me for completing the dungeon but didn't teleport me out and just respawned another Theorick on top of me. This continued until eventually i died. Please fix this glitch and give me the dungeon rewards and 3 hours of my life back.

**Comment by Moe-Ronickah** [comment]
@Villageacules
