### ISSUE TITLE
Flykick Loops - 'Freezing' game while in lobbies.

### ISSUE THREAD

**Issue by BravelyTorn** [Wynncraft/Issues#5963]
Recently I've been encountering an annoying (feature?) bug when first logging onto the Wynncraft lobby server. Occasionally I will spawn in a block above the platform. My character stays in the air while the server loads (I see the dirt menu, but other players see me floating). Whenever this happens, the server detects it as flying and kicks me. The issue is that it doesn't kick me from the game and send me to the server list (Which is the decent and polite thing to do), but instead it rapidly sends me to lobby after lobby; essentially creates an inescapable kickloop that requires the program to be killed to close.

If this is a bug, can it get fixed soon? I can't even log in anymore.

If this is a feature, can the devs stop being jerks? There is more detriment than there is benefit to incessantly giving players a 'blindfolded spin' that they can't escape from.

**Comment by Moe-Ronickah** [comment]
It's a minecraft issue, so please, go post on the minecraft issue tracker about it.  Oh, and ask them to stop being jerks.
