### ISSUE TITLE
Died repetitively one after another on WC15

### ISSUE THREAD

**Issue by D3monw3st12345** [Wynncraft/Issues#5964]
Ok, so I was going to the boss altar in the sky island. As I went down the water fall I failed my charge onto the parkour. I was now falling into the void, I died it respawned me in Rodoroc, it then killed me right after I spawned. Here are the screen shots. https://gyazo.com/a4170b46eae62ba27c6edeb9a4a2d0e5 
I am still searching through my console to find out the timestamp, although when this did happen I took a gyazo, which was recorded to be taken at 5:41 PM on WC15.

**Comment by D3monw3st12345** [comment]
This happened AGAIN. https://gyazo.com/e1f1cf6012e3d29aa7025b4eb25cf19d

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, and I have tested this on our testing server and have no longer been able to reproduce this.
