### ISSUE TITLE
Loot chest in Almuj that cannot be opened

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#5965]
This loot chest cannot be opened because it spawns with a solid block above it.

Coordinates: approximately `877 67 -1932`

<img width="2560" alt="unreachablechest" src="https://cloud.githubusercontent.com/assets/16504771/18151918/7a2babfa-6fa7-11e6-9586-9d7eb166b93d.png">

**Comment by Moe-Ronickah** [comment]
@AckroWynn

**Comment by AckroWynn** [comment]
Fixed!
