### ISSUE TITLE
not getting proper xp

### ISSUE THREAD

**Issue by RadiantSkarm19** [Wynncraft/Issues#5966]
i didnt get my proper xp from finishing toa :/
![2016-08-31_19 53 10](https://cloud.githubusercontent.com/assets/21375281/18152729/5b236bc2-6fb5-11e6-972a-f97bd84c1400.png)

**Comment by coreynj** [comment]
The real question is how the fuck did you beat Tower of Ascension at level 48?

**Comment by RadiantSkarm19** [comment]
oh i just used my main to get all the shards then tried to survive thru all the attacks with my archer xD

**Comment by DirtyDoge** [comment]
I believe the amount of XP changes in ToA and Hive depending on level.

**Comment by nathanwold** [comment]
It could have something to do with the fact that when you did this quest the first time you might have had armor and weapons that gave a high exp bonus but you don't have that on your lower lvled character

**Comment by Moe-Ronickah** [comment]
I'm sorry, but there is no evidence here that you didn't get the proper XP.
