### ISSUE TITLE
Random barrier blocks outside Llevigar

### ISSUE THREAD

**Issue by coreynj** [Wynncraft/Issues#5967]
I found some invisible blocks (I assume they're barrier blocks) in a field outside of Llevigar at -1920, -4827.

![2016-08-31_21 15 45](https://cloud.githubusercontent.com/assets/21165622/18153045/56754810-6fc0-11e6-803f-2b9e8e94e1b0.png)

**Comment by Moe-Ronickah** [comment]
@AckroWynn
