### ISSUE TITLE
Glass Bottles wont drop.

### ISSUE THREAD

**Issue by icninja** [Wynncraft/Issues#5970]
I'm doing the lvl 31 "Green Gloop" quest, and i must collect 5 glass bottles. On all the sources i can find, they drop from low level zombies around Ragni and the Emerald trail. However, i am unable to find any from any of the mobs near the identifier, and other places on the Emerald trail. I have spent 2 hours farming the one area, and have been unable to find a single drop. I do not see any other way to obtain glass bottles. Please fix. :/

**Comment by Moe-Ronickah** [comment]
Glass bottles now drop in Almuj.  You need to go to the Almuj Bazaar, and on the left, right at the entrance, is a stairwell that leads to a basement.  Kill all of the wild potions that you need.  Most will drop water bottles.
