### ISSUE TITLE
/kill bugs

### ISSUE THREAD

**Issue by MigasVelas500** [Wynncraft/Issues#5971]
i went to maro peaks to kill baab for reincarnation, to leave quickly i did /kill but i didnt spawn in selchar like i was expecting, i spawned in Kandom-Beda (lvl 95) i didnt even visit that town once and there i was with no clue where i was.
The same thing happened, i was in Gavel doing the quest "A Fighting Species" when i did /kill to get to a nearby town, i spawned in the Tutorial area of Wynn

**Comment by thecoolkogut4** [comment]
don't /kill for fast travel anymore, that would fix the problem.

**Comment by nathanwold** [comment]
doing /kill will respawn you at the nearest respawn point regardless of weather you have been there or not

**Comment by Moe-Ronickah** [comment]
You might want to read the change logs on the forums, too.

**Comment by MigasVelas500** [comment]
but when i was in gavel, and i did /kill i went to the tutorial area, shoudn't i spawn on a Gavel city?

**Comment by Trixter313** [comment]
The tutorial area is the fallback teleport in case something goes wrong so there's always a small chance you could be teleported there instead.
