### ISSUE TITLE
Corrupted Decrepit Sewers Shop's Chestnut Horse Trade Broken

### ISSUE THREAD

**Issue by ImSickPT** [Wynncraft/Issues#5973]
![screenshot_2](https://cloud.githubusercontent.com/assets/13498603/18174387/4d7f5368-7065-11e6-8ab9-005ac32cd044.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/13498603/18174391/536b35b2-7065-11e6-83ef-18f74f49ac4d.png)

I think that the chestnut horse trade is broken because why would you need 1 chestnut horse to buy another chestnut horse??

**Comment by chrisko131** [comment]
i think its 100% right
da max level of an original chestnut horse can only be up to 30

**Comment by ImSickPT** [comment]
@chrisko131 so basically the dungeon is a waste of time...
