### ISSUE TITLE
Recipe for disaster

### ISSUE THREAD

**Issue by chrisko131** [Wynncraft/Issues#5974]
i just made a stew,but Hamsey didn accept it,he just keep repeating"Aa,mon ami! and bluh bluh bluh..."

**Comment by AckroWynn** [comment]
You need to enter the dining hall. There are signs pointing where it is.

**Comment by chrisko131** [comment]
i cant enter it,i can hear like a click sound but it didn tp me

**Comment by thecoolkogut4** [comment]
the trip wire detecting the pie, stew, etc isn't alway finding the item. i had the exact problem.

**Comment by AckroWynn** [comment]
Yes, it is not working. But, I do believe they have fixed the issue, so it will be out in a few hours/days.

**Comment by AckroWynn** [comment]
Actually, I'll keep it open until it's confirmed to be fixed.

**Comment by Moe-Ronickah** [comment]
Or for 5 days without any new reports of it.

**Comment by SirKyler** [comment]
+1 can't enter the dining hall with Omelet on me.

**Comment by WhettoWen** [comment]
+1 can't enter with steww

**Comment by WhettoWen** [comment]
Just want to say it still doesn't work because I don't want mods to think this isn't fixed

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
