### ISSUE TITLE
Old boat merchant

### ISSUE THREAD

**Issue by Wozab** [Wynncraft/Issues#5975]
I found an old boat merchant and I thougt I would try to get it removed by posting it here.
![2016-09-01_20 05 19](https://cloud.githubusercontent.com/assets/9615421/18178764/f1ef7ae4-707f-11e6-8524-134ecaf1a987.png)

The coordinates are: 1170 35 -3843

**Comment by Moe-Ronickah** [comment]
@AckroWynn , are all of these poor fellows supposed to be sent into retirement?

**Comment by AckroWynn** [comment]
Removed!
