### ISSUE TITLE
Website player stat showing old dungeons, and new names are broken

### ISSUE THREAD

**Issue by kristin-meshka** [Wynncraft/Issues#5976]
When you go to look at someone in stats system this is what you see
![Picture of Prolem](https://cloud.githubusercontent.com/assets/12241212/18179771/453057ee-7041-11e6-9325-17e5e1f6039a.png)

**Comment by Moe-Ronickah** [comment]
Nice.  Really nice.

**Comment by Moe-Ronickah** [comment]
RESOLVED
