### ISSUE TITLE
The Passage Boss

### ISSUE THREAD

**Issue by CubicParadox** [Wynncraft/Issues#5977]
I'm level 57, and currently doing the quest "The Passage." However, it appears impossible for me to defeat the boss, so I cannot complete the quest until I'm a much higher level than the minimum, even though it claims to be an easy quest.

**Comment by thecoolkogut4** [comment]
the difficulty of a quest refers to how many stages it has, not how hard it is. eg easy quests are 1-3 stages, medium 4-7, hard 8+ (I'm not sure if the #'s are correct but that's the way it works)

**Comment by Moe-Ronickah** [comment]
You're going to need better gear.  ("We're going to need a bigger boat.")
