### ISSUE TITLE
Wind Prison is broken

### ISSUE THREAD

**Issue by slimeonatree** [Wynncraft/Issues#5978]
For some reason Wind prison doesn't give knockback or extra damage.

**Comment by Moe-Ronickah** [comment]
Did you use lv4 or higher powders?

Also, it's on the forums at [https://forums.wynncraft.com/threads/how-to-use-wind-prison-not-working.149024/](https://forums.wynncraft.com/threads/how-to-use-wind-prison-not-working.149024/), so it should be fixed fairly quickly, as it's kind of a big deal.

**Comment by Moe-Ronickah** [comment]
@slimeonatree , do you know if this is fixed, yet?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
