### ISSUE TITLE
I LOST MY WAND AGAIIIINNNNNN

### ISSUE THREAD

**Issue by rangandungas** [Wynncraft/Issues#5980]
MAN I COMPLETED THE SPIDER DUGEON WITH THE WAND ON MY HANDS AND SIMPLY THE ARAKADICUS EYE REPLACED IT AND THE WAND WASNT ON MY INVENTORY OR ON THE FLOOR. I THINK MY INVENTORY WAS FULL BUT THIS IS NOT A JUSTIFICATION TO IT DISAPPEAR

**Comment by TeenageCat** [comment]
I don't think they refund often. Sorry for your loss.

**Comment by rangandungas** [comment]
yeah, i have lost  2 legendary daggers with bugs  of the game already

**Comment by Trixter313** [comment]
All we can assume is that the item was accidentally dropped. Wynncraft has a strict no refunds policy so we can't return the item.
