### ISSUE TITLE
"Flying is not enabled on this Server"

### ISSUE THREAD

**Issue by Chri630** [Wynncraft/Issues#5981]
I looked up already posted issues about this but there was only one of them and did not suit what I was looking for. So I'd like to report a bug though I have some speculations to why this might be happening. First of all I would guess this is mostly due to my low level laptop. It does not have the best specs in the world which might be why. Hes why i think this, When I try to log on to the server it takes quite a long time, usually 30s (Withlist in the hub). I assume I get kicked because naturally when you spawn in your a bit above the ground when u log. So I assume since my pc takes to long to log in the server registers me as being in the air too long and kicks me for flying. This could either be my problem or a problem on the servers end but I'd like to still play none the less. Also this has only started happening recently, I used to be able to play just fine despite my terrible specs on my laptop. 
![2016-09-01_20 21 10](https://cloud.githubusercontent.com/assets/16396890/18188776/b1f5c4ea-7082-11e6-8d57-f50c5cb55ae2.png)

**Comment by Chri630** [comment]
I have managed to get on but the problem still is not resolved. I tried doing animal dungeon and got kicked again because i was in the air too long.

**Comment by 0x0000null** [comment]
Same happens to me. About 35% of the chance I can get in after 2 minutes of "loading/downloading terrain". The other 65% of the time, I get kicked for flying immediately after the terrain loading has finished

**Comment by Moe-Ronickah** [comment]
#5289
