### ISSUE TITLE
Dwarven Soldiers

### ISSUE THREAD

**Issue by Ninjazzzzzz** [Wynncraft/Issues#5982]
For some reason, dwarven soldiers drop the armor they're wearing, and occasionally their head. This may lead to some.. uh.. well nothing really. Just something that should be fixed.
Coords of the cave are 1500, 46, -5175.
[http://i.imgur.com/lZafZNZ.png](url)

**Comment by Moe-Ronickah** [comment]
It's been that way since the Gavel update.  It's just for fun.
