### ISSUE TITLE
Quest: Beneath the Depths

### ISSUE THREAD

**Issue by AikiCraft** [Wynncraft/Issues#5983]
Quest: Beneath the Depths

I have " Faded map " But Javier has disappeared, I can not complete my quest ='(

**Comment by AikiCraft** [comment]
I can not do this step:  Stage 3
» Give the Faded Map to Javier.

**Comment by Moe-Ronickah** [comment]
Are you telling us that Javier is no longer on any server that you have tested?  Please, look around for him, just in case his position was recently changed, and let us know what is going on.

**Comment by AikiCraft** [comment]
I found the coordinated X -640 / Z -3118 not the X- 701 / Z -3085
 Thank you
