### ISSUE TITLE
Lost 30 SKILL points

### ISSUE THREAD

**Issue by nethricek** [Wynncraft/Issues#5986]
Hello. Today after reseting my skill points I have lost 30 of them. I have a base of 162 skill points and I would really appreciate if I could get them back. I have a level 70 warrior so it would be really nice to get them back. thank you.

**Comment by SkySaito** [comment]
Hi.
With a level 70 character, you should only have 138 skill points and no more. Aside from gaining another level so. So you really lost anything. But if you don't have this number of points, then it's a problem. Put a screenshot of your skills and give more information next post. Thanks.

**Comment by nethricek** [comment]
ok still weird. everytime I did a skill reset I wrote down how I want all my skill points
