### ISSUE TITLE
Tribal Mask

### ISSUE THREAD

**Issue by SlimeyM8** [Wynncraft/Issues#5988]
**Problem**: When I Bought the mask in the village the skin wont load in and it looks really ugly as well 
is there a way to fix it

**Comment by Moe-Ronickah** [comment]
Could you post a picture of this, please, and let us know what version of MC you are using.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
