### ISSUE TITLE
Hole to the void in the Lost Sanctuary dungeon

### ISSUE THREAD

**Issue by KiriKorn** [Wynncraft/Issues#5989]
In the Lost sanctuary dungeon, where you have to farm the TNT, after the third door, near the little lake, there's a hole, to nothing. Yeah, that's it. Patch it up, Grian.

**Comment by Moe-Ronickah** [comment]
What are the coordinates of this hole?
Did you try changing servers?

**Comment by Sxmi** [comment]
Found/Fixed :)
