### ISSUE TITLE
Powder bug

### ISSUE THREAD

**Issue by Piethegr8** [Wynncraft/Issues#5992]
I am not sure, as this might be intentional but today I put my tier 3 red powder in the upgrade powder slot in the powder merchant and I accidentally clicked confirm and I got a tier 1 red powder. And no this is not asking for a refund. I know the wynncraft refund policy which is NO REFUNDS (:(

**Comment by Moe-Ronickah** [comment]
Is that all that you did?  Because if it is, it definitely sounds like an issue.

**Comment by Piethegr8** [comment]
Well sucks to be me

**Comment by Moe-Ronickah** [comment]
I need someone gutsy enough to try this with a Tier 2 powder, please.

**Comment by DebugingLonks** [comment]
@Moe-Ronickah Tested, it works normally for me. I do know there is a bug however relating to this. Putting in 4 low lvl powders and 1 high lvl can cause this (I THINK) untested however.

**Comment by Moe-Ronickah** [comment]
RESOLVED
