### ISSUE TITLE
Loading into Game issue.

### ISSUE THREAD

**Issue by Azthalls** [Wynncraft/Issues#5993]
Every time i try to load into WynnCraft I am not able to play. First i'm either stuck on the Loading Terrain or Downloading Terrain menu. After 5min of that when i Log in, i'm stuck with no Chunks loaded. Once they load my character keeps getting kicked for flying. I've tried restarting my game, signing out, killing my Character, and more. But I cannot seem to fix it.

**Comment by Moe-Ronickah** [comment]
I'm willing to bet that this is not still going on, is it?

**Comment by Trixter313** [comment]
Closing due to no response.
