### ISSUE TITLE
/fixquests is broken

### ISSUE THREAD

**Issue by MusicScore** [Wynncraft/Issues#5996]
In an ironic twist of events, it appears that the **/fixquests** command is broken. I've currently started (but not completed) the Wynn Excavation Site D quest, and completed the Aldorei's Secret Part 1 quest. When I performed the **/fixquests** command, it immediately returned to me the Receipt (which I was not supposed to get, as I had chosen Kansard over Corak) and an additional 2 Purple Crystal Shards. I now have a total of 10 Purple Crystal Shards, 2 Yellow Crystal Shards, 1 Elven Medallion, and 1 Receipt.

**Comment by Moe-Ronickah** [comment]
I can think of a catchy tune to sing that list to . . ..

It's all expected behavior, and it's based on the assumption that you would have finished a quest that you started, before using /fixquests.
