### ISSUE TITLE
Underground Crypt 

### ISSUE THREAD

**Issue by Ember333** [Wynncraft/Issues#5997]
I've found some problems in the underground crypt dungeon while I've been farming it, some has made my life absolutely miserable, I lost soo much stuff despite having more than 1/2 SP

First Issue: Parkour. On the first guardian island, the boss' text doesn't come up (not that important but I'll note it). This is the butcher island.
Second: On the second guardian's island, the boss (was it a legionnaire or something?) doesn't always despawn when the bridge goes down. I often find that After the bridge is down I run halfway up the tower to find he followed me and then he kills me. Additionally, he throws me off the tower as I parkour it....
Finally, In Charon's chamber, the boss likes to hide 1/2 the time out the back down a drop, where you can't reach, and the AI won't direct the mobs to, hence making the dungeon impossible to clear at that point.

These are the issues I've found so far.

**Comment by Moe-Ronickah** [comment]
@AckroWynn and @Villageacules , are these expected behaviors, or issues that can be fixed?

**Comment by Villageacules** [comment]
I'll check these things out.

**Comment by Moe-Ronickah** [comment]
RESOLVED
