### ISSUE TITLE
Sand-Swept Tomb Dungeon Boss Bug

### ISSUE THREAD

**Issue by damocleas** [Wynncraft/Issues#6000]
You do not have enough time to kill the first stage of the boss before the floor falls and when it does fall the first stage falls with the 2nd stage and you have to fight both, It's really annoying for me and my friend who are both using new-ish characters at level 40 for the dungeon and we aren't strong enough to basically 1 hit it like an old normal 60+ character.

**Comment by Moe-Ronickah** [comment]
Simple solution: level up and get better gear.  Also, the minimum level for any dungeon is based upon the strongest class, the warrior.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
