### ISSUE TITLE
Taproot quest bug

### ISSUE THREAD

**Issue by Epicdolphinator** [Wynncraft/Issues#6001]
So ive just turned lvl 64 and decided to finally do the quest Taproot. At a certain part it requires you to gather 3 types of flowers in Tiaks garden Vervain,Ginseng and Lobelia once gathered i gave it to the witch and she says the same message over and over that we need those 3 flowers. So i decided to get the 3 again and it doesnt work. I tryed /fixquests and it only give me the purple glass for wynnexcavation site C. 
![2016-09-03_00 56 46](https://cloud.githubusercontent.com/assets/21965827/18222826/6c14e65a-7171-11e6-9070-a2e471d17424.png)

**Comment by Moe-Ronickah** [comment]
The flowers that you need don't grow in her garden, next to her hut.  They grow "elsewhere", in her "garden".  Remember, she is very powerful, so her garden is fairly large.  Nothing is extremely far away, however, you might have to do a bit of parkour to get to at least one of the flowers.
