### ISSUE TITLE
When i am riding my horse it says i am flying then kicks me

### ISSUE THREAD

**Issue by TheLemunGuy** [Wynncraft/Issues#6003]
My horse keeps glitching out and saying that i am flying. For example i was just riding my horse to the Sand-Swept tomb when it said i was flying, so then it kicked me. When i got back on my be weeapon, The Olux's Prized Wand with 2 tier 4 earth powders on it was gone. I hate wynncrafts update because of the quests too. Please could i get my wand back.

**Comment by Trixter313** [comment]
What version of Minecraft are you using? We recommend using 1.8.9 as using other versions can cause issues in themselves. Wynncraft has a strict no refunds policy but we would like to make sure it doesn't happen again. Let us know if using 1.8.9 fixes the issue, thanks!

**Comment by TheLemunGuy** [comment]
I am using 1.10.2
