### ISSUE TITLE
I'm VIP+ but forums say im VIP

### ISSUE THREAD

**Issue by sk011b0y** [Wynncraft/Issues#6005]
Title Says It All

**Comment by Trixter313** [comment]
When did you purchase VIP+ and did you go from VIP to VIP+ or straight to VIP+?

**Comment by sk011b0y** [comment]
I purchased vip+ atleast 10 months ago and I upgraded from vip

**Comment by Moe-Ronickah** [comment]
Contact support@wynncraft.com.  They may be able to help get it fixed.
