### ISSUE TITLE
Sherk's quest broken?

### ISSUE THREAD

**Issue by EnderPenguin1** [Wynncraft/Issues#6009]
**This may contain spoilers**

I have the Black Veil. I went to the maiden's tower to use it and it says I don't have it. Am I missing something or is it glitching?

**Comment by Trixter313** [comment]
Did you make sure to put the veil on?

**Comment by EnderPenguin1** [comment]
I have it on. It still doesn't work.

**Comment by EnderPenguin1** [comment]
Nevermind. I got it to work
