### ISSUE TITLE
I beat Underworld Crypt Twice!?!?

### ISSUE THREAD

**Issue by TIROW2** [Wynncraft/Issues#6010]
![2016-09-03_20 50 28](https://cloud.githubusercontent.com/assets/16447510/18227046/c3349820-7218-11e6-9bbd-0acad5e7ca57.png)

As you can see I beat the Dungeon twice in a row...
My friend DarkStarMoonPvP and I finished the quest at the same time and he also completed it twice.

**Comment by IcyShrub** [comment]
This can also happen with Decrepit Sewers. Was running through with a friend and we both beat it twice.

(I doubt this is related but there are also times where you kill the boss and the dungeon doesn't end so you have to kill it a second time.)

**Comment by StrandedKnights** [comment]
this happens some times because the new Dungeons

**Comment by Celsonic** [comment]
This has happened before the update as well, basically it detects when players in the zone have killed a boss, and there is a glitch where sometimes if you do it correctly and quickly do another blow as your doing a killing blow causes it to give you double the rewards. Usually happens with crowded servers.

**Comment by Celsonic** [comment]
Still Happening for some reason, Adding proof.

**Comment by Celsonic** [comment]
![2016-12-29_15 08 37](https://cloud.githubusercontent.com/assets/21028327/21553884/24775a16-cdd9-11e6-8f78-0545d7608cb1.png)

**Comment by Moe-Ronickah** [comment]
You pretty much have to be fast enough to hit the "dead" boss as it is regenerating, before the code tells it that it must die.  It's part of the "kill mob" safety system that prevents dead mobs from ghosting.  This will be with us for a long, long, time.  Consider it a feature, now.
