### ISSUE TITLE
Galleon's Graveyard Glitches

### ISSUE THREAD

**Issue by Celsonic** [Wynncraft/Issues#6012]
During the armored pirate stage, somehow I attained an extreme amount of speed, I'm assuming the same speed of the heat seeking cannon-balls. When I was in vanish [As An Assassin] I was hooked sometimes by the boss [Not Spoiling It Lol]. When I did this dungeon with another person, during the transition between the whirlpools and armored pirate it glitched me out.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.

**Comment by Celsonic** [comment]
Can confirm this is just a minecraft mechanic unfortunately.
