### ISSUE TITLE
The Canary Call bug

### ISSUE THREAD

**Issue by MedievalBladeRPG** [Wynncraft/Issues#6013]
By logging out and logging back in while inside the cave with poisonous gas, one can remove the nausea effect. I found this unintentionally after over an hour of being offline, so i'm not sure if this can be triggered within a shorter amount of time.

https://gyazo.com/1dc2ee6efdfee7241559377f05be93eb

**Comment by Moe-Ronickah** [comment]
It is, fortunately, very intentional.  Now, I'm going back to laying down, and hoping that this dizziness goes away.  Here, birdy, birdy, birdy.
