### ISSUE TITLE
Quest Not Giving You Item

### ISSUE THREAD

**Issue by Slime1480** [Wynncraft/Issues#6014]
Soon i'll do Temple Of Legends quest and i saw in a video i need a corrupted potato from "The angy village" quest, well, i did that quest but when i saw my bank there wasn't any corrupted potato, what i have to do? if i dont have that item i cant do Temple Of Legends quest...

**Comment by Trixter313** [comment]
If you did the quest and don't have the potato using the command /fixquests should return it. If it doesn't, double check all of your inventories.
