### ISSUE TITLE
My warroir was delted when i didnt delet it

### ISSUE THREAD

**Issue by TuthPick** [Wynncraft/Issues#6015]
I had a level 23 warrior i was grinding on my mage then i went to switch to my warroir and it was deleted and idk why it was cause i didnt deleted

**Comment by ColinRioux** [comment]
Well, unfortunately there is a no refund policy that is strictly enforced by the Wynncraft staff. Apparently this is happening a lot, and there are two causes:
1. You could be deleting your class unknowingly
2. Or there is a bug (which the developers are aware of)
