### ISSUE TITLE
WynnEx Site B Reward List Not Complete

### ISSUE THREAD

**Issue by Pyromanical** [Wynncraft/Issues#6016]
In WynnEx Site B, when you complete it, it only shows the top of the rewards page.  It says you only get 50k xp, but you also get 2 Purple Crystal Shards, and a bunch of emerald blocks.
![2016-09-03_20 19 19](https://cloud.githubusercontent.com/assets/21978993/18228460/c6e75f92-7214-11e6-81c2-d5b8fdad923d.png)

**Comment by Moe-Ronickah** [comment]
Scroll down?

**Comment by Pyromanical** [comment]
I couldn't scroll down, because that was the bottom of the text I got.

**Comment by Moe-Ronickah** [comment]
@AckroWynn , any ideas?

**Comment by AckroWynn** [comment]
Fixed!
