### ISSUE TITLE
Mechanical Chip getting un-textured

### ISSUE THREAD

**Issue by RaymondZGames** [Wynncraft/Issues#6017]
just as title says
Mechanical Chip getting un-textured when you switch worlds or change classes making it useless

**Comment by Moe-Ronickah** [comment]
Titles are meant to be short, sweat, and to the point.  Post your issue where it belongs, please.

**Comment by Moe-Ronickah** [comment]
The Mechanical Chip is an item that loses it's NBT data when you change classes or worlds, and it will not be altered, as it is meant to do this.
