### ISSUE TITLE
um, mechanical chip?

### ISSUE THREAD

**Issue by izzy4234** [Wynncraft/Issues#6019]
The place where the mechanical chip is supposed to be spawning isn't working and in turn is not spawning the mechanical chip

**Comment by Trixter313** [comment]
Is it working if you switch to another world?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
