### ISSUE TITLE
Minecraft skin not loading in Wynncraft.

### ISSUE THREAD

**Issue by Eskalade** [Wynncraft/Issues#6021]
When I login to some other server, my skin works, but once I enter the Wynncraft World, it resets to Alex. The skin works in the lobby, not in the individual worlds.

**Comment by Moe-Ronickah** [comment]
Wynncraft stores skins, itself, for speed, in game.  It can take several hours to reload a new skin.  Also, this error sometimes occurs purely at random.  Are you still having this issue?

**Comment by Eskalade** [comment]
I asked one of my friends, who said that his skin didn't work, but turns out that it might be client-based. I saw his skin perfectly well, yet on his screen, he claimed that he was Steve. Nt sure abt this tho, might want to seek more clarification.

**Comment by Trixter313** [comment]
Are you using 1.8.9? That is the version we recommend using.

**Comment by Eskalade** [comment]
I have tried using 1.8.9, but some textures, especially grass blocks do not load, and pop up as purple and black tiles. Might it be something wrong with my texture pack?

I downloaded this WynnCraft texture pack online, as I could not download it from the game itself. If so, how can I fix this?

**Comment by Trixter313** [comment]
If you try to download the one right from the server now does it still not work?

**Comment by Eskalade** [comment]
Thing is, I don't know how to download the one from the server. I have enabled server resource packs but I don't get the notification to download it :/

**Comment by Trixter313** [comment]
If you click on Multiplayer > Wynncraft > Edit and server resource packs is enabled it should automatically download when you login to a world.

**Comment by Eskalade** [comment]
The pack does download, but my MC crashes once it starts. How can I fix this?

**Comment by Trixter313** [comment]
So it crashes not in the lobby but when you login to a play world? If you could paste the crash log into something like http://pastebin.com/ and put the link to it here that might be helpful.

**Comment by DebugingLonks** [comment]
Put armor on and take off

#7143 (I think) for my own reference

**Comment by Moe-Ronickah** [comment]
RESOLVED
