### ISSUE TITLE
Teleported to Tutorials Area, after I joined

### ISSUE THREAD

**Issue by RobinPH** [Wynncraft/Issues#6023]
So, Im on Gelibord getting a Green Powder Relic, and got Disconnected (Timed out), then joined again but I was afk in choosing Class and AFKed for several minutes like 5-10mins. then after I choose my Archer class I was shocked because I spawn in Tutorial Area instead of Gelibord. Some Pictures

http://i.imgur.com/bybZn9Z.png
http://i.imgur.com/fS2JjHZ.png
http://i.imgur.com/TZYIXlX.png
http://i.imgur.com/QeGt6D7.png
and I finished this Tutorial then teleported to Ragni.

And another one, when I click a block or something using my bow "Relic Bow" it says "You don't have permission for this area." (anywhere in the world)

**Comment by Trixter313** [comment]
The beginning area is the fallback teleport location in case anything goes wrong so you will occasionally be teleported there.

The second issue is because Wynncraft weapons are retextured blocks and the server doesn't allow you to place blocks. Using an empty hand to click things should work.
