### ISSUE TITLE
Items Not Working In The Nether

### ISSUE THREAD

**Issue by GoldNinjaSlayer** [Wynncraft/Issues#6025]
When I try to use Ignition or Squall's Breath in the nether, they don't work. I don't know if this is happening to any of the other items though.
Here is a link to show what the weapons look like:
http://imgur.com/a/yTemE

**Comment by Trixter313** [comment]
The items only look like this while in the nether?

**Comment by GoldNinjaSlayer** [comment]
Yes, and I can't use spells or attack with them

**Comment by Moe-Ronickah** [comment]
This was happening to items in Guild Wars.  Let us know if this is still happening after 24 hours.

**Comment by GoldNinjaSlayer** [comment]
It hasn't been fixed yet.

**Comment by Celsonic** [comment]
I've got one of these items, still not fixed .-.

**Comment by Celsonic** [comment]
Not fixed yet I have a christmas event item... not working in the nether

**Comment by Moe-Ronickah** [comment]
@AckroWynn , would you bring this to Jumla's attention, please?  I believe that he has to transfer the data from the game code to the guild server code.

**Comment by Moe-Ronickah** [comment]
This problem is being handled on the forums at [https://forums.wynncraft.com/threads/list-of-items-unusable-in-guild-wars.128718/](https://forums.wynncraft.com/threads/list-of-items-unusable-in-guild-wars.128718/)
