### ISSUE TITLE
Unable to log in to WynnCraft Servers

### ISSUE THREAD

**Issue by JohnDSi** [Wynncraft/Issues#6027]
I can't log in to any Wynncraft Server past the Lobby, I just get stuck at Downloading Terrain. I've reinstalled minecraft and switched versions but that hasn't worked. 've also joined multiple servers without a problem. While downloading terrain others can see me floating on the server and when I do load in after 10 min the server freezes on my end, I see everything in chat that has happened in the past 10 minutes, the noteblock music gets REALLY fast, and then I get kicked for flying.

**Comment by JohnDSi** [comment]
This glitch was fixed by a staff tping me to ground level as I load in client side but am floating on the server. Therefore when I finally loaded in I wasn't kicked for flying.

**Comment by Trixter313** [comment]
Glad to hear!

**Comment by JohnDSi** [comment]
However, the downloading terrain for 5 min continues to exist
