### ISSUE TITLE
House of Twain Merchant

### ISSUE THREAD

**Issue by BadPunGenerator** [Wynncraft/Issues#6031]
The house of twain merchant is not there or where he is sapose to be, ive gone on different worlds and tried to find him but i cant.

**Comment by ALEEEEEEEEEEX** [comment]
They changed the way to get the hat/mask.

**Comment by Moe-Ronickah** [comment]
@ALEEEEEEEEEEX , please elaborate.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
