### ISSUE TITLE
Jungle Dungeon failed tp room, also no text

### ISSUE THREAD

**Issue by CMWizard** [Wynncraft/Issues#6033]
I was running through the new jungle dungeon, and after going through the final door, marked for the boss, I was tp'd to a black room. I know this is standard, except no text appeared and it didn't tp me back out. I could hear the pressureplates/tripwires, but nothing was happening. I even tried jumping to untrigger and trigger them again. When I used /class, it tp'd me out of the dungeon entirely and showed the standard "you logged out during a boss fight..." thing

**Comment by Trixter313** [comment]
When you go back in does it happen again or was it a one time issue?

**Comment by CMWizard** [comment]
It was a one-time issue so far as I know. I had two keys and the first time went fine.

**Comment by CMWizard** [comment]
I know that because it was one-time makes it relatively useless to post about, just wanted to make sure you guys knew it happened.

**Comment by CMWizard** [comment]
Because true glitches are consistent

**Comment by Trixter313** [comment]
It was most likely caused by lag. Thanks for the report!
