### ISSUE TITLE
Blue Powder V Relic

### ISSUE THREAD

**Issue by ranger958** [Wynncraft/Issues#6034]
So, I just found the Blue Powder V Relic and cracked the seal in eager anticipation... but it gave me a Blue Powder I... seeing as "I" does not equal "V", I was wondering if this could be fixed.

Ranger958

**Comment by Trixter313** [comment]
Powder relic V's drop up to V powders but also anything below. It's similar to horse breeding where you will get a random one but up to V.

**Comment by ranger958** [comment]
Ah, Thanks for the clarification!

Ranger958
