### ISSUE TITLE
Spell Lag

### ISSUE THREAD

**Issue by ethandonley2002** [Wynncraft/Issues#6037]
So I originally had this computer that runned wynncraft just fine. It was a mac from 2014 that could run wynncraft smoothly and it could still work fine during the gameplay update as well. But then I bought a new computer, the 2016 Macbook model. I updated java and made the settings make it so it can run minecraft fast. But however, the spells gets inconsistently laggy for no reason. And I am running 1.8.9 of minecraft to prevent horse lag issues. But how do I make the spells go more consistent and there being little to no input delays?

**Comment by ethandonley2002** [comment]
anyone?

**Comment by Trixter313** [comment]
Unfortunately many of the people who help on here are inexperienced with Macs, including me. I'm not really sure what else to suggest. You say you updated Java, what version did you update it to? Using 1.8.9 is great, no issues there. Have you tried using Optifine?

**Comment by Trixter313** [comment]
Also, could you go into detail on what you mean by input lag? Thanks!

**Comment by setery10** [comment]
Which Java version is minecraft selecting when you go into the profiles?

**Comment by Moe-Ronickah** [comment]
1) Post all of your changes that you made to make MC run faster.
2) Did you change mice?  If yes, were you running any type of mouse enhancement software on your older Mac that you aren't running now?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
