### ISSUE TITLE
House of Twain Quest Broken

### ISSUE THREAD

**Issue by Pyromanical** [Wynncraft/Issues#6038]
I'm doing the house of Twain quest, and according to the wiki, there should be a Ghostly Merchant in the tower, which there isn't.  Also, in the secret room behind the fireplace, the painting covering the signs is missing, and when you throw emeralds onto the soul sand on the grave, it doesn't pick them up.  
![2016-09-04_18 31 49](https://cloud.githubusercontent.com/assets/21978993/18234512/e62ce62e-72cd-11e6-856a-daee8b67cbca.png)
![2016-09-04_18 05 44](https://cloud.githubusercontent.com/assets/21978993/18234513/eb0f54ec-72cd-11e6-9c95-cbecc622dfc9.png)

**Comment by BadPunGenerator** [comment]
The only thing wrong with me is the ghostly merchant isnt there

**Comment by Pyromanical** [comment]
I'm on a new server now, and the emeralds went into the soul sand, so idk why it wasn't working for me earlier.  Since the only problem is that the ghostly merchant is missing, this is now a duplicate, and I'll close it.
