### ISSUE TITLE
Nodguj Island Boat Pass took me to Selchar instead

### ISSUE THREAD

**Issue by Pixelific** [Wynncraft/Issues#6040]
Self explanatory, I used the Nodguj boat pass and it instead took me to Selchar

**Comment by Celsonic** [comment]
If someone used a pass just as you got on the boat, you are sent to the location.

**Comment by Pixelific** [comment]
That didn't happen. I happened to be recording at the time it happened. Here the video is:
https://www.youtube.com/watch?v=mq2OJWReqeQ&feature=youtu.be&ab_channel=Pixelific

**Comment by Moe-Ronickah** [comment]
@AckroWynn , is this an error?  Do boat passes work, even if you may have never been somewhere, before?

**Comment by AckroWynn** [comment]
Hey, where did you try to go to Nodguj from?
Nemract? Selchar? Et.c.

**Comment by Pixelific** [comment]
I went from Nemract.

**Comment by AckroWynn** [comment]
I'll report this to Lotem! Thanks :D

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
