### ISSUE TITLE
Mana Potion Glitched

### ISSUE THREAD

**Issue by Celsonic** [Wynncraft/Issues#6041]
Self explanatory 
http://i.imgur.com/47ZFzO6.png
Buggy merchant in troms

**Comment by Trixter313** [comment]
If you switch to another world is the merchant still glitched?

**Comment by Celsonic** [comment]
Still Broken alright

**Comment by Moe-Ronickah** [comment]
This is just a coding error, it's still should be the correct potion.

**Comment by Thaecrasis** [comment]
I just tried buying/using those mana potions and they didn't work. They just act as regular water bottles. Right clicking them doesn't do anything, and holding right click drinks them like in vanilla minecraft.

Images of potions:
[Mana3](https://puu.sh/sEFIF/d8e99db6fc.png)
[Mana4](https://puu.sh/sEFII/365645a21b.png)

Video of trying to use Mana3 to no effect: https://www.youtube.com/watch?v=tPWKl1MdhYA

**Comment by Moe-Ronickah** [comment]
Okey, @AckroWynn , can you fix this, or does it need to be passed up to admin?

**Comment by DebugingLonks** [comment]
This is still an issue. I have seen this within the last 48 hours

**Comment by DebugMC** [comment]
Issue has been fixed.
