### ISSUE TITLE
WynnExcavation Site B /fixquests Reward Bug

### ISSUE THREAD

**Issue by TenLetterz** [Wynncraft/Issues#6043]
I've completed all the wynnexcavation site quests, but when i do /fixquests, I still get purple crystal shards for some odd reason. I assumed it started when i finished site b, because when I tried to fix a different quest, it gave me the purple crystals that I already have. It's also happening for yellow crystal shards as well once I finished site d.

Please fix this. I don't want to keep fixing other quests just to end up filling up inventory and bank space.

**Comment by Moe-Ronickah** [comment]
It's supposed to work this way.  If you use /fixquests, it will return anything to you that you don't have that you will need later on.
