### ISSUE TITLE
Tribal Sanctuary altar problem.

### ISSUE THREAD

**Issue by ziment** [Wynncraft/Issues#6044]
This boss altar don't tp you to boss arena. I activated tripwire, but all it does write some text and nothing. 
Image : http://i.imgur.com/uog1YQw.png
P.S. u can't enter arena without tp because of barrier blocks

**Comment by Trixter313** [comment]
If you try doing in on another world does it still happen?

**Comment by ziment** [comment]
Yes, it doesn't helps.

**Comment by kerpsolem** [comment]
Same problem ! two time i try and i'm stuck again... rest to do /kill to go out

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
