### ISSUE TITLE
Clothing bug

### ISSUE THREAD

**Issue by ThePyromaniac** [Wynncraft/Issues#6045]
I am a VIP+, yet I cannot using clothing. In the Use Menu. 
![ddc550bd0c48c4baf4bf8991bad884f9](https://cloud.githubusercontent.com/assets/19894985/18242097/e5a84c22-7311-11e6-98ad-7549497607d4.gif)

**Comment by Trixter313** [comment]
The clothing area hasn't been implemented yet.
