### ISSUE TITLE
Aquarius Armor - Elemental Defense Error

### ISSUE THREAD

**Issue by JackyKit123** [Wynncraft/Issues#6046]
https://youtu.be/B1jxFSCld_U
My elemental def without wearing aquarius is 50 -100 -100 -100 50
but when I wear aquarius, my all my elemental def got minus by 100 becoming -100 -200 -200 -200 -100 despite my aquarius gives +80water -92earth -10earth def
it happens on some of the other armor that gives elemental def too

**Comment by setery10** [comment]
I can confirm that I should not have any elemental defenses over 1000 but I do

**Comment by Moe-Ronickah** [comment]
@JackyKit123 , without knowing what you took off, or what you were at before you put on the Aquarius, there is no way for us to know what is really happening.

@setery10 , please post a screenshot of this.

**Comment by JackyKit123** [comment]
@Moe-Ronickah as posted in the video , before I put on the Aquarius , I was not wearing any chestplate

**Comment by setery10** [comment]
@Moe-Ronickah 
If everything worked like I think it should work then I should have:
Fire Defense: 245 * .25 = 61
Thunder Defense: 245 * .16 = 39
Air Defense: 175 * .06 = 10.5
Earth Defense: 245 * .38 = 93
Water Defense: 175 * .23 = 40
Unless there are different calculations then this math shouldn't be wrong.
![2016-09-11_15 33 27](https://cloud.githubusercontent.com/assets/8347065/18419959/35cd5440-7835-11e6-845d-f90418aaedd2.png)
![2016-09-11_15 33 28](https://cloud.githubusercontent.com/assets/8347065/18419957/35cd09e0-7835-11e6-9cdb-7954e55ac017.png)
![2016-09-11_15 33 30](https://cloud.githubusercontent.com/assets/8347065/18419958/35cd32e4-7835-11e6-906d-9f3092151619.png)
![2016-09-11_15 33 31](https://cloud.githubusercontent.com/assets/8347065/18419960/35cd72ae-7835-11e6-9494-d249d1964447.png)
![2016-09-11_15 33 32](https://cloud.githubusercontent.com/assets/8347065/18419961/35cdc04c-7835-11e6-979f-25bb331126f8.png)
![2016-09-11_15 33 34](https://cloud.githubusercontent.com/assets/8347065/18419962/35d12066-7835-11e6-80f6-b87a0e5411d1.png)
![2016-09-11_15 33 35](https://cloud.githubusercontent.com/assets/8347065/18419966/35e3697e-7835-11e6-8423-3d011adbe576.png)
![2016-09-11_15 33 36](https://cloud.githubusercontent.com/assets/8347065/18419965/35e2dbe4-7835-11e6-96e7-5eed94d7348b.png)
![2016-09-11_15 33 40](https://cloud.githubusercontent.com/assets/8347065/18419964/35e2dde2-7835-11e6-9837-edebb3899f3c.png)
![2016-09-11_15 33 43](https://cloud.githubusercontent.com/assets/8347065/18419967/35e42a8a-7835-11e6-8aaa-17428b731d91.png)

**Comment by WhettoWen** [comment]
I can confirm that Aqua gives -100 in all defenses and not only in thunder.

**Comment by Moe-Ronickah** [comment]
@JackyKit123 , your video does not hold on a pre- shot at all, and the post shot is so brief that it's nearly impossible to read it without pausing.

**Comment by Moe-Ronickah** [comment]
@setery10 , you are talking about a completely different issue.  Please open a new issue with all of the same information.

**Comment by setery10** [comment]
@Moe-Ronickah , wow didn't know that was different from this

**Comment by Moe-Ronickah** [comment]
@setery10 , also, I don't see where you have any elemental defenses over 1000.
@WhettoWen , as I've told @JackyKit123 , we need to see before and after pics of your info screen.

Before anyone gets too upset, the Compass data has many problems, so hang on while I get a hold of some more help and information.

**Comment by Moe-Ronickah** [comment]
Doubly Confirmed what I already suspected: Compass info is NOT reliable, especially for Elemental Defenses.  This is not an unknown issue, but your armor is working just fine.
