### ISSUE TITLE
Texture Bug!

### ISSUE THREAD

**Issue by theelectronic00** [Wynncraft/Issues#6047]
![2016-09-05_14 03 32](https://cloud.githubusercontent.com/assets/21990606/18247290/fa9f3568-7371-11e6-8231-916fcc283a25.png)

The flowers or the grass is all pink and black! I tryed everything but i don't know what to do?!

**Comment by Trixter313** [comment]
Using 1.8.9 should fix the issue. That is our currently recommended version as using other versions can cause issues in themselves such as this.
