### ISSUE TITLE
Bob's Tears dropping from mobs

### ISSUE THREAD

**Issue by Rastin2** [Wynncraft/Issues#6049]
I've been farming at the Crazy Wolf Tamer mob near Nesaak and once every 2-5 minutes I go and kill all the hungry wendigos nearby and sometimes get Bob's Tears, I'm not sure if this is supposed to happen or not but I feel like it's not, thus I came to report it here. (I've also been getting depressing items from lv40+ mobs but idk if that's a bug or not)

**Comment by ColinRioux** [comment]
@AckroWynn

**Comment by xBreaksx** [comment]
This was confirmed by some GM or Moderator that it's supposed to happen because it was too hard and inconvenient to farm Bob in Ragni and Hungry Wendigos are apparently depressed, so they drop bob's tear.

@AckroWynn please confirm for me, thanks :)

**Comment by AckroWynn** [comment]
Yup, it is supposed to be happening! Let's just assume that Bob dropped a tear to the wolves, and... Well, I guess they just carried it with them.
