### ISSUE TITLE
Llevigar Entrance Guild Issue

### ISSUE THREAD

**Issue by Jamesym100** [Wynncraft/Issues#6050]
So, a little backstory.
I lost my bow, so I went to Llevigar to get a new one, after I was done I headed out of Llevigar towards Wynn... I noticed that at Llevigar Entrance there was no Guild controlling it...

So, I went and tried to capture it... this is what happens:
![image](https://cloud.githubusercontent.com/assets/15308443/18254209/504aa170-7393-11e6-889c-3784d52bfa41.png)

I then type /guild defend:
![image](https://cloud.githubusercontent.com/assets/15308443/18254223/67db2652-7393-11e6-9373-284bc92260a4.png)

I have tried a few times, I am a Guild Chief, we are a new guild (lv 7) and own no territory... so I thought this was perfect... but, I geuss not...

Am I doing something wrong or is this a server-side glitch?

**Comment by ColinRioux** [comment]
Hi!
This is a server side glitch to my knowledge, as I have been able to reproduce the issue. There are some territories in gavel that are bugged, and I am hoping the CT will soon be able to fix it. In the meantime, be patient. And if you want territories, Wynn is the best option.

**Comment by Jamesym100** [comment]
alright, thanks!
