### ISSUE TITLE
Connectivity to Worlds

### ISSUE THREAD

**Issue by Dystinct** [Wynncraft/Issues#6051]
When connecting to **ANY** Wynncraft World, it can take anywhere from 10 seconds to 6 minutes just to connect. At which point when I do connect I end up getting kicked for flying (I was leaving a dungeon before all the ping issues started so I am stuck in the sky). My ping to the server is consistently at 170 where as before it was around 80. This has been happening for the past 4 days where nothing has changed besides Update 1.14.1 - Patch 3. I am not saying that it is because of the patch, but when this patch went out suddenly my ping was doubled. I have recorded a video of me logging in to the lobby and selecting a random server while sitting there for 4 minutes just to connect and getting kicked for "flying".

I have also tried it with multiple different versions of Minecraft (1.8.8 - 1.10.2). Still to no avail.

Would love to get back to Wynncraft soon as I have been playing before even the VIP town was a thing (3 years).

**Comment by Trixter313** [comment]
1.8.9 is the version we recommend players use, just fyi and we've seen some reports of this recently. You can try using the command /kill as fast as possible to get your player back in the normal map or if it lets you log in to the nether you can try the command /toggle autojoin to see if that helps. If neither of those work a staff member might have to teleport you back into the map.

**Comment by Dystinct** [comment]
I am not outside of the map. I am located in front of the skeleton dungeon just floating there. My friend took this picture of me floating there where all I saw was just void.

![](https://cdn.discordapp.com/attachments/152988107329896449/222207115488526336/2016-09-05_00.11.02.png)
