### ISSUE TITLE
Gosh darnet Iron Heart Part II (Darn Dr. Urelix bug)

### ISSUE THREAD

**Issue by XxNinMario64xX** [Wynncraft/Issues#6052]
So Ive recently done the Iron Heart Part I, but here's the problem. The quest thought I took Dr. Urelix's bribe even though I was standing far away from him. More precisely, around 10 blocks. As soon as I opened my quest book, I saw a message in chat informing me I did the quest, then I realized that Dr. Urelix had said Ive made the right decision. I didnt want to take his bribe at ALL! I just wanted the greaves of honor, but now i CANT get them due to this bug... glitch... or whatever its called! Please, if you can, reset the quest and rollback my EXP before i did this quest so i can get the greaves of honor. You can take out the greaves of shame, I really dont want them...

P.S I wasnt facing Dr. Urelix at ALL when looking at my quest book

**Comment by XxNinMario64xX** [comment]
oh yeah, and the emeralds can go as well. all 512/768 of them

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy to keep the game fair so we can't change your quest or the times you received. Sometimes stepping on a pressure plate near a quest NPC will trigger them, which might have happened here.

**Comment by XxNinMario64xX** [comment]
Ah ok, thanks for clarifying. P.s Where do I find this "policy" you speak of? I want to see if there are any others I should know about in case i get caught up in the situation again :/

**Comment by Trixter313** [comment]
I don't believe the refund policy is written down in a specific place but if you search the forums for 'no refund'  you'll see the massive amount of posts about it. Situations where it was something purchased with real money are determined on a case by case basis and have a possibility of being refunded but everything else doesn't.

You can find a list of rules here: https://forums.wynncraft.com/threads/game-forum-rules.111874/
