### ISSUE TITLE
Item named Bug

### ISSUE THREAD

**Issue by Lynnners** [Wynncraft/Issues#6055]
I have found an item with the name "Bug", claiming to report how I found it so they can fix it.

I found it from a Jinko mob.

**Comment by Trixter313** [comment]
Could you post a screenshot of the item here? Thanks!

**Comment by Lynnners** [comment]
http://prntscr.com/cej0hk

**Comment by Zellnotronus** [comment]
![2016-09-05_15 29 34](https://cloud.githubusercontent.com/assets/17558794/18256072/5a5cf114-737e-11e6-92b9-8d99caa8fa2e.png)

I found this near the entrance to the red meteor cave.

**Comment by ThunderRemix** [comment]
I can confirm that these drop.

**Comment by ThunderRemix** [comment]
I can confirm that these spawn sometimes when the door breaks... but I don't know if it's fixed now.

**Comment by DebugingLonks** [comment]
I can confirm its not fixed. I have 2 (I just told a mod and then threw them away)

**Comment by Moe-Ronickah** [comment]
RESOLVED
