### ISSUE TITLE
The Hidden City memory puzzle not working

### ISSUE THREAD

**Issue by xBreaksx** [Wynncraft/Issues#6057]
The Hidden City quest has a memory puzzle that you must do in order to go inside the cave at the top of the cliff on the eastern side of Eltom.

_How to replicate this bug:_
**Solution One:**
1. Hit the button once to start the puzzle.
2. Complete the puzzle once.
3. Press the button again.
4. Click on a wooden button that is not the correct answer to the puzzle.
5. It should look something like this:
   ![2016-09-05_15 19 48](https://cloud.githubusercontent.com/assets/11200616/18255883/4d6bf3d0-737c-11e6-971a-be4442c836e5.png)

**Solution Two:**
(Not sure if this solution is buggy, ntb tested.)
1. Make sure you bring a friend.
2. One of you presses the button to start the puzzle.
3. The person who didn't press the start button completes the puzzle.
4. It should look something like this:
![2016-09-05_15 19 48](https://cloud.githubusercontent.com/assets/11200616/18255883/4d6bf3d0-737c-11e6-971a-be4442c836e5.png) (Same picture but it's the same bug)

**Comment by xBreaksx** [comment]
Sorry, note that the puzzle will stay like that that is shown in the picture forever

**Comment by Moe-Ronickah** [comment]
I'm really confused.  Just what is the issue here?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
