### ISSUE TITLE
Qira Hive Barrier gap

### ISSUE THREAD

**Issue by Saint-Iggy** [Wynncraft/Issues#6059]
Near Qira hive there is a spot where you can get out of the map walls, co-ords are 405, -5422. From there I was able to walk on air and get stuck on the other side of the invis walls.
![2016-09-05_16 21 53](https://cloud.githubusercontent.com/assets/21955098/18256633/f9031dbe-7385-11e6-9aa2-62f2c5e0e5da.png)
![2016-09-05_16 22 01](https://cloud.githubusercontent.com/assets/21955098/18256632/f901d9ae-7385-11e6-978d-2cd6a6a637b5.png)
![2016-09-05_16 21 39](https://cloud.githubusercontent.com/assets/21955098/18256634/f90421e6-7385-11e6-8cbf-7b851b0afe9d.png)

**Comment by ALEEEEEEEEEEX** [comment]
It's just barriers..

**Comment by Saint-Iggy** [comment]
Yea, but it might be something to fix. since it gets you out of the map.

**Comment by Moe-Ronickah** [comment]
@AckroWynn , can you patch this, please?

**Comment by Moe-Ronickah** [comment]
I've been all over this area, and I can't find a way through.  I suspect that it was a one-time server error.
