### ISSUE TITLE
Escape Spell for Archer won't work

### ISSUE THREAD

**Issue by 22chienri** [Wynncraft/Issues#6061]
I am level 16 now and using the archer class. I have the Flaming Bow and can't use the escape spell. It takes away my mana, but does nothing. I've tried using other bows, but that won't work either. I've been using 1.8. Please help me with this problem. I've died 3 times because I forgot my escape spell didn't work.

**Comment by ColinRioux** [comment]
Was it working before?

**Comment by 22chienri** [comment]
Yes. I it was working before

**Comment by Trixter313** [comment]
When did it stop working and can you think of any changes you made around then that might have caused it? This seems like a really odd issue.

**Comment by 22chienri** [comment]
Srry for the trouble. I found out that my mouse left click button was kind-of broken, so it didn't work. I got a new mouse and now it works.

**Comment by Trixter313** [comment]
Glad to hear you got it resolved!
