### ISSUE TITLE
Selling items at the Treasure Shop in Selchar causes intense lag

### ISSUE THREAD

**Issue by LabyrinthMaster** [Wynncraft/Issues#6063]
In Selchar, when you sell your items to the treasure shop guy in Selchar, it creates lag and rollbacks. It doesn't affect just you, but all players on and around the island. 

Location : https://i.imgur.com/2uoO1IX.png

**Comment by Trixter313** [comment]
Could you explain it a bit more? Also, if you switch to another world does it still happen?

**Comment by LabyrinthMaster** [comment]
When you sell an item to the treasure shop, you have this short half a second lag, it affects only the world you are in and the players on the island when you're doing it. Now, if you want to sell multiple items, like 40 pearls or something else, the server freezes for a few seconds.  It doesn't convert the items instantly as it does with the emerald merchants at the bank.

**Comment by Moe-Ronickah** [comment]
We need someone else to confirm this, please.
