### ISSUE TITLE
-127 Defense Stat Points Bug (Proably just cosmetic)

### ISSUE THREAD

**Issue by ALEEEEEEEEEEX** [Wynncraft/Issues#6064]
![2016-09-06_17 33 44](https://cloud.githubusercontent.com/assets/20970407/18283428/7730611c-7465-11e6-8603-d4471c6c6b93.png)

Luckily it doesn't seem to affect my skill points it might mess something up when I reset/spend skill points tough.

**Comment by ColinRioux** [comment]
Could you rename this issue to reflect your actual issue? Then it will get waitlisted.

**Comment by Trixter313** [comment]
When did you first notice it like this? It might go away with a little bit of time.

**Comment by thecoolkogut4** [comment]
This happens when you go over X amount of points. just cosmetic (as you said)
