### ISSUE TITLE
Need help , Cant play or move when i log in 

### ISSUE THREAD

**Issue by thediamondkittie** [Wynncraft/Issues#6065]
I dismounted my horse near ternaves and it glitched me into an empty wall of 1 block wide 4 blocks tall , i cannot use scrolls to get out for some reason and i cant get out any other way , any help ? 
![2016-09-06_20 49 41](https://cloud.githubusercontent.com/assets/22036899/18288505/9028e1a4-7473-11e6-9253-862466701749.png)
![2016-09-06_20 49 43](https://cloud.githubusercontent.com/assets/22036899/18288508/98a93464-7473-11e6-8562-d32a581627e3.png)

**Comment by ColinRioux** [comment]
A good command to know is `/kill`. It will just kill your player, remove 2 soul points, and spawn you at the nearest spawn point.

**Comment by thediamondkittie** [comment]
omg how did i not think of this ? thank you so much im such an idiot
