### ISSUE TITLE
Bug with hidden city quest

### ISSUE THREAD

**Issue by Lorigami** [Wynncraft/Issues#6070]
So, I'm at the one cave with the memory puzzle, and even though I'm clicking the button, nothings happening. I proceeded to check the walkthough to see if maybe I'm doing something wrong, and I'm clearly not. In replacement of colored blocks and buttons there's straight gray clay and a distinct lack of buttons. Neither /class or switching servers changes this. Plsfix, I need xp.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/6057

**Comment by Lorigami** [comment]
Actually, not the same issue. Theirs is colored mine is just straight gray.

**Comment by Trixter313** [comment]
I think what color they are is less important but they both have the same main issue of lacking the necessary buttons.

**Comment by Lorigami** [comment]
Seeing as the colors are necessary for the puzzle, that's not so. Plus, you have to trigger theirs somehow. Mine just appeared that way.
