### ISSUE TITLE
Powders ability

### ISSUE THREAD

**Issue by amit1230** [Wynncraft/Issues#6072]
I used two tier 4 air powders and one water powder tier 4 on bob's mythic wand but the ability doesnt working i do shift and hit and its still dont working pls try to fix it

**Comment by setery10** [comment]
Did you try charging it up by attacking?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
