### ISSUE TITLE
health going down

### ISSUE THREAD

**Issue by yayarne** [Wynncraft/Issues#6074]
my health keeps going down for no reason, there are no mobs nearby. I've relogged multiple times and I also unequiped my armor. Nothing helps. please help

**Comment by setery10** [comment]
Maybe your weapon or accessories/armor has negative health regen, check your stats on your compass.

**Comment by ICHIGOunserscore** [comment]
It would help if you found your answer already you should shutdown this issue

**Comment by Trixter313** [comment]
25 days with no response from OP, assuming issue is fixed.
