### ISSUE TITLE
TOA floor 2 lvl 10 boss doesn't drop token?

### ISSUE THREAD

**Issue by 00gogo00** [Wynncraft/Issues#6075]
As title, I have killed him ~10 times in the past few days with no drop.  I am soloing him, and the weapon I am using is Poisoned Wood (A staff with 1-5 neutral damage and 528/3s posion) if that is the problem.

**Comment by LordHelmchen98** [comment]
I have no idea if that's correct but I could imagine that poison on a mob doesn't count as your damage so it says you haven't dealt enough damage and nobody else has so it doesn't drop anything. Try using another wand or message me ingame. ign: Lord_He1mchen. I could help you get the drop.

**Comment by ColinRioux** [comment]
There has been no response to this issue in at least 30 days, nor has there been any other issues like it which have been reported. If this issue still persists, please feel free to open a new issue, if not, ignore this message.
