### ISSUE TITLE
Armor Disappearing

### ISSUE THREAD

**Issue by GhastGio** [Wynncraft/Issues#6076]
Last night (from today), I was playing on my assassin, and then later I switched over to my archer.  However, when I did this, the armor I was wearing was gone! It wasn't in my inventory, either.  I tried clicking where the armor was, any empty slots in my inventory, nothing.  My inventory was quite full, I had at least 2 open slots.  I had significantly less health (only 260), so this proves I wasn't wearing armor.  Could this just be another dumb inventory glitch caused by lag?  Sorry I couldn't get proof, I don't know what could prove this.

**Comment by ICHIGOunserscore** [comment]
Wynncraft has a no refund policy rip

**Comment by Moe-Ronickah** [comment]
@ICHIGOunserscore , you did not address the question that was asked.

@GhastGio , it's possible that it was an inventory glitch and it's possible that it was a connection issue.  If you were in the same place that you were when you exited the game, either one of those could have caused it to happen.  If you weren't where you left from, there are several other possibilities.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
