### ISSUE TITLE
Laggy Horses

### ISSUE THREAD

**Issue by Cibcabco** [Wynncraft/Issues#6077]
Hello there,
This has been around for a long time now; the horses seem to lag out and freeze. If there is a footstep sound of the horse, it disappears when this lag happens, even if you move. Same thing goes for the theme musics in the background. The only way to fix this issue is by getting out of the horse, but that pushes to back to the place where this freeze happens. MAKE THE HORSES GREAT AGAIN!

Thank you.

**Comment by Celsonic** [comment]
Switch to a server without lag or deal with it .-.

**Comment by Moe-Ronickah** [comment]
If you are using any version of Minecraft higher than 1.8.9, please change to 1.8.9 or lower, as there are known bugs in horse movement in higher versions.

**Comment by thecoolkogut4** [comment]
this bug was apparently fixed in a mini patch tonight. *I have not tested it though

**Comment by ColinRioux** [comment]
This bug should be fixed for version 1.9 or higher. However, there may be new bugs as a result to this patch. 

Some to look out for: 
proxy disconnect
minecraft crashing
etc.

If this happens, please confirm that your issue isn't already posted, and post it as a new issue.

**Comment by DebugingLonks** [comment]
This issue has been resolved, but supposedly boats are broken (unconfirmed)

**Comment by Moe-Ronickah** [comment]
RESOLVED
