### ISSUE TITLE
Memory Paronia Quest bug

### ISSUE THREAD

**Issue by Charliebubblegum** [Wynncraft/Issues#6078]
SO I went to where the masterbedroom is  and it didn't teleport me to the past before everything was destroyed please help D:

nvm I fixed that but now I got a key and it says you need a key but I got one....

now it teleported me to the start of the game

now I got back and I got stuck inside the stairs so I did /kill

now its the key thing again

**Comment by Charliebubblegum** [comment]
nvm I fixed that but now I got the key and it says YOU NEED A KEY but I got one plz help D:

**Comment by Charliebubblegum** [comment]
OMG IT TELEPORTED ME TO THE START OF THE GAME

**Comment by Charliebubblegum** [comment]
Just great I got back and now I'm inside the stairs so I had to do /kill

**Comment by Charliebubblegum** [comment]
Now it says I need a key again ugh

**Comment by k0fEin** [comment]
Yep, can confirm, teleported me to start of the game when i was about to open master bedroom. Im pissed now.

**Comment by Charliebubblegum** [comment]
I am pissed so much I literally gotta pee I'm not kidding

**Comment by Charliebubblegum** [comment]
Its working now I just had to wait a little bit

**Comment by Charliebubblegum** [comment]
😄
