### ISSUE TITLE
Ice Barrows boss Door

### ISSUE THREAD

**Issue by N64Craft** [Wynncraft/Issues#6080]
so the boss door teleport got stuck, and the door closed, so now my friend and I are
![2016-09-08_14 08 39](https://cloud.githubusercontent.com/assets/22085710/18367048/19de999c-75ce-11e6-99bc-16736b421eb3.png)
![2016-09-08_14 08 44](https://cloud.githubusercontent.com/assets/22085710/18367053/1ba96e14-75ce-11e6-8117-bfcb25eddaf2.png)

 pretty much stuck.
![2016-09-08_14 08 34](https://cloud.githubusercontent.com/assets/22085710/18367010/f1517dbe-75cd-11e6-9221-fec4741ff56c.png)

**Comment by Trixter313** [comment]
You can use the command /kill to get out. =)
