### ISSUE TITLE
Ik-El-Van Speer

### ISSUE THREAD

**Issue by Ma124** [Wynncraft/Issues#6081]
![2016-09-09_12 09 30](https://cloud.githubusercontent.com/assets/22096295/18383562/78bf55d8-7686-11e6-84b4-7ff1af3e5b39.png)
you can see the raw code and you can't sell it to an item buyer because 'it isn't a weapon'

**Comment by Trixter313** [comment]
Did you recently pick it up like this or have you had it?

**Comment by Ma124** [comment]
I picked it today up.
________________________________
Von: Nick Cipriani<mailto:notifications@github.com>
Gesendet: ‎09.‎09.‎2016 12:38
An: Wynncraft/Issues<mailto:Issues@noreply.github.com>
Cc: Ma124<mailto:ma_124@outlook.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [Wynncraft/Issues] Ik-El-Van Speer (#6081)


Did you recently pick it up like this or have you had it?

**Comment by Trixter313** [comment]
Hmm, where did you pick it up at? Is it possible that another player dropped it or was it a mob drop?

**Comment by Ma124** [comment]
I think I got it from an other player.
________________________________
Von: Nick Cipriani<mailto:notifications@github.com>
Gesendet: ‎09.‎09.‎2016 23:51
An: Wynncraft/Issues<mailto:Issues@noreply.github.com>
Cc: Ma124<mailto:ma_124@outlook.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [Wynncraft/Issues] Ik-El-Van Speer (#6081)


Hmm, where did you pick it up at? Is it possible that another player dropped it or was it a mob drop?

**Comment by Trixter313** [comment]
Ah, that makes sense. In a previous update some items with special characters were broken like this and it's suggested to just get rid of them because they won't really do anything. You probably picked it up after someone discarded it. I'd recommend throwing it in the trash can at a town so no one picks it up again.

**Comment by Ma124** [comment]
OK, I'll do it.
________________________________
Von: Nick Cipriani<mailto:notifications@github.com>
Gesendet: ‎10.‎09.‎2016 13:47
An: Wynncraft/Issues<mailto:Issues@noreply.github.com>
Cc: Ma124<mailto:ma_124@outlook.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [Wynncraft/Issues] Ik-El-Van Speer (#6081)


Ah, that makes sense. In a previous update some items with special characters were broken like this and it's suggested to just get rid of them because they won't really do anything. You probably picked it up after someone discarded it. I'd recommend throwing it in the trash can at a town so no one picks it up again.
