### ISSUE TITLE
Bank Item Disappearance bug

### ISSUE THREAD

**Issue by Staraptia** [Wynncraft/Issues#6086]
So I opened my bank and clicked on a Jester Ring and while it was selected it just disappeared without even dropping as an item on the floor. I know it wasn't a ghost item, too.  

I don't know if this is relevant but I was using my lvl 24 Warrior bank class and I was holding a Fierte and any time I'd right click or left click a message would pop up in chat telling me that 'Fierte is for level 56 only', but I'm not sure if this relates to the problem at all.

This is the first time this has happened and I'm pretty paranoid that it'll happen again.

EDIT: I've also noticed that you can't drop items when you're looking at your bank anymore, neither with Q or clicking outside the bank borders. Maybe this is where the problem is occurring?

**Comment by Keegandalf** [comment]
I had a similar problem. I had 4 emerald blocks and 43 emeralds. When the bank unlocked the 2nd row using the 4 blocks it also took the 43 emeralds.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
