### ISSUE TITLE
Item desc too big to fit on screen

### ISSUE THREAD

**Issue by bunngo** [Wynncraft/Issues#6087]
So basically I identified a legendary dagger and the items enchants and description make it so the player cant see the damage or name of the weapon
![2016-09-09_15 28 55](https://cloud.githubusercontent.com/assets/22087787/18400090/5a2a988c-76a2-11e6-90eb-7e478ffc003c.png)

**Comment by Trixter313** [comment]
If you change your GUI scale to something smaller or look at the item while you have your bank open you should be able to see it all. Other than than that there's not much we can do about it.
