### ISSUE TITLE
Black box

### ISSUE THREAD

**Issue by Creepo9000** [Wynncraft/Issues#6088]
My mage is stuck in the black box thing where you pick your class, and it doesn't have any scrolls. Someone pls help meh. Cri
![2016-09-09_14 25 38](https://cloud.githubusercontent.com/assets/22105822/18400082/f1428fee-7699-11e6-898a-4c632392ec51.png)

**Comment by brainscript** [comment]
@Creepo9000 How are people not being able to use a f***ing search function???! :rage1:
[Is it soooooooooo hard to enter text and press a f*******ing key on your keyboard?!](https://github.com/Wynncraft/Issues/issues?utf8=%E2%9C%93&q=stuck%20in%20black%20box)

**Comment by Trixter313** [comment]
You can use the command /kill with 3+ soul points to get put of most stuck situations. =)

**Comment by Trixter313** [comment]
@brainscript please don't be rude and angry in responses here, thank you!

**Comment by brainscript** [comment]
@Trixter313 Thanks for deleting my comment. -.- I just _don't like_ people creating a GitHub account to ask such a _not so smart_ question. Imagine all the inactive GitHub accounts that _not so smart little children_ created just to be able to ask a question here ...

GitHub is a [Git](https://git-scm.com/) "hoster" and Git is for developers and not for _not so smart little children playing WynnCraft and not being able to use a search function_, thank you!

**Comment by Trixter313** [comment]
This is the place to report issues so it's inevitable that we will get people here who aren't developers. In the end it would be nice if we never got duplicate reports but it isn't that much of a hassle. Just close and mark as duplicate.
