### ISSUE TITLE
Guild attacking bug

### ISSUE THREAD

**Issue by Ichigo1221** [Wynncraft/Issues#6092]
When I try to attack any guild's territory I can't join the battle. 
I have 3 min countdown, and, after this time I get teleported to empty map, where mob's don't spawn, or don't even get teleported and, when try to use /guild attack again, it say's my guild is already in battle.

**Comment by LordHelmchen98** [comment]
Guilds are very bugged and that happens quite often. If no mobs are spawning try it again. If you don't get teleported change the server. How often did you try that? Most of the time it works after a few attempts.

**Comment by Ichigo1221** [comment]
I Tried to raid some terrains about 6 or 7 times. Only 1 worked. (Is that normal, that after death I respawn on attack map again in horde of mobs, and die 2nd time, loosing only 1 soul point?)
Usually I get teleported to empty map, if i try again, I don't even get tped.

**Comment by LordHelmchen98** [comment]
Hmm I don't know about the soul points but yes it is normal that you respawn on the war map again. you spawn there and then get tped after a few seconds.
My guild had a similar problem once it was so annoying to try and try without getting anything. but after a few days it was better. I hope you'll be able to attack soon as well.
