### ISSUE TITLE
Armor disappearing

### ISSUE THREAD

**Issue by GaPoiVN** [Wynncraft/Issues#6093]
I logged in with my archer , and all my armors were gone. But I didnt logged in with my pc , I logged in with another pc , is that the problem?

**Comment by Trixter313** [comment]
Was your inventory full at the time of logging in?

**Comment by Moe-Ronickah** [comment]
GaPo, what about your stats?  Did you notice anything unusual with them?  Any error messages of any kind?

**Comment by GaPoiVN** [comment]
no , i logged in and all my armors is just disappearing , like there is nothing at armor slots , no  skill points glitch , and i have like 12 inventory slots free

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
