### ISSUE TITLE
Dissapearing Items

### ISSUE THREAD

**Issue by FlameForest** [Wynncraft/Issues#6098]
Today I was on WynnCraft, and decided to go on my second account to get something done. When I got back onto my main account, half of my items were gone. I just dealt with it and got my items back, It took around an hour to get all of the scrolls I had. Later in the day I did the same thing. I went on the other account I have, and came back to the other one. Once again, about half of my items and armor dissapeared. Does anyone know how to fix this? I have no idea what is going on.

**Comment by Trixter313** [comment]
Could you post a screenshot of your inventory right after the bug happens? Also, when you switch do you have both open at once or are you closing and restarting Minecraft?

**Comment by Celsonic** [comment]
Someone killed you with a player made invasion probably.

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
