### ISSUE TITLE
Unable to message friend who's clearly online?

### ISSUE THREAD

**Issue by coreynj** [Wynncraft/Issues#6099]
So, I'm trying to message one of my friends. He just shouted, and he's clearly on WC17. He's on my friends list, but it doesn't say he's online, and it won't let me message him. Help?

**Comment by Trixter313** [comment]
Are you using the exact capitalization and spelling as their username?

**Comment by coreynj** [comment]
Yes, but that shouldn't matter, it shouldn't be case sensitive to begin with.

**Comment by ThunderRemix** [comment]
Did you check if he had his resource pack loaded? There is a bug that prevents outside msging from other servers except the one he is on.

**Comment by Displaid** [comment]
Are you sure you're doing /msg? If you are, just try going on his server or logout and come back in.

**Comment by thecoolkogut4** [comment]
a while ago there was a bug where you can't cross server message, I belive this occurred when that happend and the problem already got fixed.

**Comment by Moe-Ronickah** [comment]
Sometimes, you may have to log off and back on, too, to fix this.  Thankfully, it isn't a permanent situation.
