### ISSUE TITLE
I lost all my Legendary amor after Upgrading to Vip+

### ISSUE THREAD

**Issue by owie24** [Wynncraft/Issues#6100]
After upgrading from vip to Vip+ i went back to my lvl 59 assassin class to the realization that i had no amor on and yes i did have amor on before i upgraded. I checked my bank my other characters but it was nowhere and i didn't lose it b cuz the minimum amount of soul points i have while adventuring out is 8 so if an admin could see this and help me out that would be great.

**Comment by Trixter313** [comment]
When you logged in with no armor was your inventory full?

**Comment by owie24** [comment]
No

**Comment by owie24** [comment]
It was pretty much empty

**Comment by WizardOfWynn** [comment]
Strict no refund polixy

**Comment by owie24** [comment]
Did i ever ask for a refund, no i asked for my legendaries back

**Comment by AscendedKitten** [comment]
Returning any items that got lost, no matter how, isn't possible due to the No Refund policy.

**Comment by Moe-Ronickah** [comment]
This is extremely strange.  I can't remember this ever happening, before now, so, did you upgrade from VIP to VIP+ while you were in-game?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
