### ISSUE TITLE
Lost Bob's Wand

### ISSUE THREAD

**Issue by Charliebubblegum** [Wynncraft/Issues#6101]
My friend lost bobs wand and cant get it back plz help us his name is alexlou1 and mine is charliebubblegum

**Comment by WhettoWen** [comment]
Wynn has a strict no refund policy, sorry. Your wand is gone if it despawned.

**Comment by Trixter313** [comment]
Please have your friend make their own bug report, we'd prefer to talk directly with them. Thanks!
