### ISSUE TITLE
Green Skinned Trouble

### ISSUE THREAD

**Issue by Angerworld** [Wynncraft/Issues#6102]
here same problem as told many times before but without a solution maybe it goes away after some time but again. when you must do the puzzle when following the light. when the block disseapears you fall in a portal but instead of being teleported u get stuck with falling over and over again with the message null in your inbox. yes i did every step of the quest i changed servers i restarted the game.

**Comment by ColinRioux** [comment]
There has been no response in at least 30 days. If your issue still persists, please make a new issue (while checking if there are no duplicates first).
