### ISSUE TITLE
Underworld Dungeon Boss Sometimes Unbeatable

### ISSUE THREAD

**Issue by Voridy** [Wynncraft/Issues#6103]
While playing Wynncraft and beating the Underworld Dungeon multiple times, I found that the boss (Charon) can sometimes fall off the cliff behind where he spawns and either be killed almost instantly from the fire, or be essentially invincible by not being able to get hit.
http://imgur.com/a/ecSV4
That is a very blurry picture of what I am talking about. I am sorry it could not be high quality.
A way I found you could beat him, after being in the boss fight for 20+ minutes because of this, is actually hitting your own soldiers, in my case the general, off the cliff to kill Charon. 
It is also odd that the soldiers do not always jump off the cliff to kill him.
Just a bug that could be fixed by invisible blocks or something, but thank you for reading!

**Comment by Moe-Ronickah** [comment]
Players are not supposed to attack Charon, directly.
