### ISSUE TITLE
Guild Leave/Join/Create bug

### ISSUE THREAD

**Issue by Meowlegend** [Wynncraft/Issues#6104]
![2016-09-11_00 05 53](https://cloud.githubusercontent.com/assets/16465515/18415336/c1bd8c68-77b3-11e6-9e1d-7a81f3ab4a11.png)
If you look in the chat, you see that I leave my guild, but it doesn't allow me to create a new one

**Comment by ZeeLeoNardo** [comment]
Yea Having same problem here..

**Comment by Celsonic** [comment]
Did you change your ign recently?

**Comment by Moe-Ronickah** [comment]
Meowlegend has been changing names every 30 days.  This is a duplicate of #3665 .  You can follow the issue, there.
