### ISSUE TITLE
Tribal Sanctuary Boss Altar

### ISSUE THREAD

**Issue by Displaid** [Wynncraft/Issues#6105]
After throwing the 12 eyes into the altar, I was teleported in but couldn't get into the boss fight. And then, a friend came and stayed in there so items don't despawn. So I came back and went back in and still couldn't get in.

**Comment by Moe-Ronickah** [comment]
I was just in there, yesterday, so please try again.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
