### ISSUE TITLE
Wynncraft I Bought Vip+ a very long time ago 

### ISSUE THREAD

**Issue by Wolfypvp123** [Wynncraft/Issues#6106]
Wynncraft i bought vip+ a very long time ago and i dont have xp bomb or disguise.

**Comment by Trixter313** [comment]
What do you mean by disguise? Do you mean where it turns you into another mob like a spider or chicken? Also, are you sure you didn't use the XP bomb already?

**Comment by thecoolkogut4** [comment]
type /use, then click on the skull (skeleton head). Does it show any mobs eggs there? If yes what happens when you click on an egg?

**Comment by Moe-Ronickah** [comment]
If you have any problems with items purchased with real world currency, please contact [support@wynncraft.com](support@wynncraft.com) , give them all of the details of the purchase, including the transaction number, and tell them what problems you are having.
