### ISSUE TITLE
Antipodes attacking other enemies

### ISSUE THREAD

**Issue by KarnivoreSheep** [Wynncraft/Issues#6107]
The Level 95 "Antipode" aggressive mobs keep attacking other enemies at the Freezing Heights.

**Comment by ColinRioux** [comment]
Antipode, by definition, is something that is the direct opposite of something else. 

I'm not fully sure if this is a bug or not, but the Antipode's mob purpose may be to attack anything, including players and other mobs.

**Comment by KarnivoreSheep** [comment]
Could be. Could also be a malicious side-effect of its fiery spell it spews in a large area. It might hit mobs who start a cycle of retaliation until one of them dies.

**Comment by Moe-Ronickah** [comment]
RESOLVED
