### ISSUE TITLE
Taproot quest bugged

### ISSUE THREAD

**Issue by ZeeLeoNardo** [Wynncraft/Issues#6108]
When I talk to tiek, she tells me that she needs the 3 flowers, I got the 3 flowers though, she does not accept it. Am I doing something wrong? 

https://www.youtube.com/watch?v=-cVwVGv9L-c&feature=youtu.be

**Comment by Trixter313** [comment]
The quest book is misleading, you need the flowers from around her house but not the ones in her garden. Those have already begun getting tainted. Follow the clues that she says in chat to get the correct versions of the flowers.

Let us know if this helps, thanks!

**Comment by Celsonic** [comment]
If your stuck, just watch a tutorial by HippieSnuggles or whatever. You can also look at the wiki :D.
