### ISSUE TITLE
wynnexcavation site a

### ISSUE THREAD

**Issue by jeroen01** [Wynncraft/Issues#6109]
I'm doing the excavation site a and when i jumped down i saw something really strange. a item frame with a bow and a torch on top of it:
![2016-09-11_13 58 53](https://cloud.githubusercontent.com/assets/22130537/18417178/124bcc7e-7829-11e6-9447-42fa5c57a830.png)

**Comment by Displaid** [comment]
Its not game changing so it shouldn't matter

**Comment by Trixter313** [comment]
No telling whether it's intended decoration or not but it isn't hurting anything.
