### ISSUE TITLE
The Canary Calls quest deleted my pure ):

### ISSUE THREAD

**Issue by CarlEmilRP** [Wynncraft/Issues#6111]
So, i fell down the ''Redstone'' hole in The Canary Calls, and couldn't get out. I tried /class, shifting servers, and teleporting. I eventually used /kill, and it put me inside the blocks of the starting caravan. (The one all new charecters spawn in). I used /class to get out of the blocks, and when i got in again, my Pure was gone ):

Can i get a refund? I really don't know what to do now...

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so we can't return any items.

What most likely happened is the drop key was accidentally pressed in the confusion or just typing of commands. That's all we can assume as we know nothing more than you do. To make sure that doesn't happen you can change your drop key to something less likely to accidentally be pressed.
