### ISSUE TITLE
Connection Lag

### ISSUE THREAD

**Issue by xXEmanuXx** [Wynncraft/Issues#6112]
Everytime i connect to WynnCraft i have a lag because i live in Italy and my ping to WynnCraft is too high. There is a way to fix this?

**Comment by Trixter313** [comment]
Unfortunately there's not much we can do about location based lag. All I could suggest is maybe try restarting the router but that might not help too much.

**Comment by xXEmanuXx** [comment]
Thanks a lot! :D
