### ISSUE TITLE
Elemental spell damage bugged

### ISSUE THREAD

**Issue by Madib00** [Wynncraft/Issues#6113]
Spells are meant to deal elemental damages, like assassin's spin deals thunder and mage's meteor deals earth and fire. When I use a weapon that DOESNT HAVE NEUTRAL DAMAGE the spells deal only the damages that my weapon has on it. For example, my assassins Archangel deals ONLY air damage with every spell. This has been happening since the gameplay update. Please fix this asap, because it completely destroys my damage. 
Sincerely, Madib00

**Comment by WhettoWen** [comment]
This isn't a glitch it's because archangel only has air damage therefore it can only deal air damage.

**Comment by Madib00** [comment]
My archangel dealt the damages before the gameplay update. So basically Archangel was nerfed to be shit now? I used to do 5-6k spins, now they do only 2.5-3k.

**Comment by ColinRioux** [comment]
Yes some items were nerfed in the most recent update. I'm not positive if Archangel specifically was nerfed, but it's quite possible.

**Comment by Madib00** [comment]
This applies to all items that don't have any neutral damage. Also possibly to items that have powders on them that take away the neutral damage.

**Comment by Madib00** [comment]
The weird thing is, that archangel's stats are exactly the same as before. It just doesn't deal other damage than air anymore. 
I guess the behavior of non-neutral damage weapons was changed in the update and I just gotta deal with it?

**Comment by Moe-Ronickah** [comment]
"I guess the behavior of non-neutral damage weapons was changed in the update and I just gotta deal with it?"  Yes, because the previous behavior was unintentional.  That was, in fact, the glitched behavior.
