### ISSUE TITLE
Tower of Ascension Completion Glitch

### ISSUE THREAD

**Issue by SIRFARMER03** [Wynncraft/Issues#6115]
I completed the Tower of Ascension at level 50, and when I turned it in, it only leveled me up once, but it said it gave me 925,000 experience. I have a screenshot here: http://imgur.com/gallery/nRyTH
thank you

**Comment by Celsonic** [comment]
According to the wiki.... You probably should have leveled up 4 levels, I don't know why this happened, most likely the server did not want to process you leveling up lol.

**Comment by Moe-Ronickah** [comment]
The Wiki currently lists the updated XP for the quest; it is 375 000.
