### ISSUE TITLE
Jungle Fever Glitch

### ISSUE THREAD

**Issue by MIsterPenguino** [Wynncraft/Issues#6117]
I entered the Almuj Labyrinth, and put the emerald on the pressure plate died. The quest book said talk back to Worid but he says I have the insufficient items,. I went back in the Labyrinth and got inside and I couldn't talk to the Almuj bank. Please fix this and help! 

IGN: MisterPenguino

**Comment by MIsterPenguino** [comment]
Please fix! Thanks You.

**Comment by Trixter313** [comment]
I'm sort of confused with the report, how many issues are you reporting here? Could you also go into detail with the issue(s)? Thank you!

**Comment by Moe-Ronickah** [comment]
You still need to go to the bank, go into the labyrinth, and talk with the Almuj Banker in the labyrinth.

**Comment by MIsterPenguino** [comment]
My Problem: I can't talk to the Almuj Banker.
Bug: I got to the door of the labyrinth and died but my quest book still updated. Does that make sense?

**Comment by MIsterPenguino** [comment]
I talked to worid and he said you havent done what ive asked, and i cant talk to the almuj banker. after you get to the door the game may think you completed the maze without dying

**Comment by MIsterPenguino** [comment]
![ej](https://cloud.githubusercontent.com/assets/22135808/18604135/69d77d3a-7c3e-11e6-9c20-fab417ca060c.png)

**Comment by Trixter313** [comment]
Hmm, try using the command /fixquests to see if it gives you the items you were supposed to get in the labyrinth.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
