### ISSUE TITLE
Bob's Lost Soul Thingy

### ISSUE THREAD

**Issue by Austinator** [Wynncraft/Issues#6118]
I went to turn in the Rose and Bob's Tear for the Quest, but it doesn't do anything.
![bob](https://cloud.githubusercontent.com/assets/22136140/18420195/70ce149c-7832-11e6-8945-b3ae9a3dfe78.PNG)

![bob2](https://cloud.githubusercontent.com/assets/22136140/18420196/765e587c-7832-11e6-8339-7a9ce310b193.PNG)

**Comment by Trixter313** [comment]
What does it say in your quest book and could you post screenshots of the tear and rose's info?

**Comment by Austinator** [comment]
![2016-09-11_15 27 26](https://cloud.githubusercontent.com/assets/22136140/18420292/920390f4-7834-11e6-8d32-5eba57ee77f4.png)

![2016-09-11_15 29 35](https://cloud.githubusercontent.com/assets/22136140/18420293/95b3923a-7834-11e6-90d6-6e70ceb748d0.png)

![bob3](https://cloud.githubusercontent.com/assets/22136140/18420297/9f82e3ba-7834-11e6-85a4-a0851f4cd4b9.PNG)

**Comment by Austinator** [comment]
Sorry, I jsut realized it says Wedyf, not Tarod :package:
