### ISSUE TITLE
Green Skinned Trouble Glitch ( Not being able to finish quest )

### ISSUE THREAD

**Issue by Okzidee** [Wynncraft/Issues#6119]
I had almost finished the quest Green Skinned Trouble, I had the axe of Llevigar, and talked to Detective Jackson, then after he was done talking, it says empty some space in your inventory, so I did, then it says
"I would kill them myself, if it wasn't for the treaty. If you can help me, I can help you. Bring me [5 Axe Heads] from the Green, Red and Black Orc camps"
My IGN is KitKatKys, i'm a level 44 Warrior, Please help!

**Comment by Okzidee** [comment]
![2016-09-11_19 50 50](https://cloud.githubusercontent.com/assets/22137959/18421451/4076b854-7859-11e6-8c43-12b3e13e2083.png)
![2016-09-11_19 50 55](https://cloud.githubusercontent.com/assets/22137959/18421452/470df98e-7859-11e6-8652-62ba2e545d92.png)
![2016-09-11_19 51 02](https://cloud.githubusercontent.com/assets/22137959/18421453/4958b076-7859-11e6-8058-9c0ead8be9ac.png)
![2016-09-11_19 51 10](https://cloud.githubusercontent.com/assets/22137959/18421455/4d3422d4-7859-11e6-99cf-b2f5a7a667bc.png)
![2016-09-11_19 51 19](https://cloud.githubusercontent.com/assets/22137959/18421456/4ee849f2-7859-11e6-92b2-28287316fead.png)

**Comment by Celsonic** [comment]
You need like 5 of each axe head from each of the camps. Look on the wiki for more detail.

**Comment by Moe-Ronickah** [comment]
Celsonic, you've missed what he wrote.  He already had the Axe of Llevigar.

@AckroWynn , can you shed some light on this?  Is the quest failing if the player doesn't have enough space open, and does the detective take the axe, anyway?

**Comment by AckroWynn** [comment]
@Moe-Ronickah So if I am getting this straight; Are the axes being taken away, even though only that warning message appeared?

**Comment by Moe-Ronickah** [comment]
@Okzidee , you passed the various axe heads to Detective Jackson, then went and got the Axe of Llevigar, correct?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
