### ISSUE TITLE
That One Missing Bookshelf

### ISSUE THREAD

**Issue by DCM627** [Wynncraft/Issues#6121]
![2016-09-11_20 00 38](https://cloud.githubusercontent.com/assets/19480434/18421562/5f48cea0-785b-11e6-95c4-40b8d852f9b3.png)
Sorry to be that guy, but there's a missing bookshelf in Gundalf's Library...  I feel so nitpick-y doing this, but what must be done, must be done.

**Comment by Moe-Ronickah** [comment]
Duplicate.
Known by the builders.
They wanted it that why.
No, I don't know why.
LOL

**Comment by DCM627** [comment]
Did not see that issue anywhere else... odd...
