### ISSUE TITLE
Duplicated quest item

### ISSUE THREAD

**Issue by Samattack2000** [Wynncraft/Issues#6124]
This is a bug I got not so long ago: While doing the Creeper infiltration quest and got the mask, I got 2 masks at the same time instaid of one. I know how to get rid of quest items (drop them in an other charater and delete it) but it's still strange that I got 2 masks at once.

**Comment by Trixter313** [comment]
It was most likely just a one time glitch that won't happen again or happens rarely. As you said, it's easy enough to fix if it does happen luckily.
