### ISSUE TITLE
Nemrak nametag boat glitch.

### ISSUE THREAD

**Issue by DerpyBean** [Wynncraft/Issues#6125]
Ok so I went to Rooster Island on the boat, took a minute, I finished the quest and threw the Nemrak nametag into the boat. It teleported me midocean with the 'moving' boat, and now its been 2 hours of me AFK on this god forsaken boat with no escape... No ONE NO ONE is helping me.

**Comment by ThunderRemix** [comment]
/kill or scroll is your only way out.
