### ISSUE TITLE
Dagger disappearing on right click

### ISSUE THREAD

**Issue by rafaazul3** [Wynncraft/Issues#6126]
This has happened twice to me now. I right click my dagger and it simply disappears.

**Comment by Celsonic** [comment]
Either the server was too slow to update it or something on your side...

**Comment by Trixter313** [comment]
What is your drop key set to? I'd recommend changing it to something other than the default 'Q' as it can be very easy to accidentally press that button.

**Comment by Moe-Ronickah** [comment]
Are you right-clicking on your dagger, in your inventory screen?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
