### ISSUE TITLE
Green Skinned Trouble.

### ISSUE THREAD

**Issue by CompactVenom12** [Wynncraft/Issues#6128]
Upon completing the 6th stage "Kill Orc Leader Gregg'r to obtain the Axe of Llevigar" I was sent through the exit and teleported to X-1867  Y28 Z-4899 facing SW and it seems that I am in a wall of some sort.. I'm currently on my level 54 Archer, and unable to move at all.. Which then limits me to using my archer. Is there any way to fix this..

**Comment by Trixter313** [comment]
Sorry for the late reply, you should be able to use the command /kill to get out of the space!
