### ISSUE TITLE
Elemental DMG % on weapons dont work

### ISSUE THREAD

**Issue by CelestialPandas** [Wynncraft/Issues#6129]
PLEASE FIX THIS! I have a dagger named the specialist which relies on its elemental dmg% to be good. It currently doesn't work and does barely any damage even though it has above 600% elemental dmg.

**Comment by Celsonic** [comment]
We need evidence first.

**Comment by WhettoWen** [comment]
It's not a bug, use common sense. 600% of 0 is 0. It has no damage ,you need to place powders
