### ISSUE TITLE
I demand a justice

### ISSUE THREAD

**Issue by LordKwadracik** [Wynncraft/Issues#6130]
There was a big lag on server while i was identifying a helmet from Temple of the Legends (Quest), and i just lost it . So  i am asking  can you give it back to me ? Cus it is unfair because i cant do this quest now . 
Thank you in advance

**Comment by thecoolkogut4** [comment]
do /fixquests to get the helmet back.

**Comment by Celsonic** [comment]
I don't think that the unpurified helmet is a quest item.

**Comment by LordKwadracik** [comment]
thank you soo much guys ;) /fixquests is working <3
