### ISSUE TITLE
Bug Decripted Sewers Boss

### ISSUE THREAD

**Issue by RedstoneTrip** [Wynncraft/Issues#6132]
Ive found a bug while fighting the boss in Decripted Sewers, he got stuck in barrier blocks and is unable to move and attack, and i cant attack him. Hope you see this :)
I do not have the proof to show this bugg, because its hard to get this bug. Sorry!
#RedTrip

**Comment by Moe-Ronickah** [comment]
I'm sorry, but we would need at least a screenshot of this before we can even consider it.
