### ISSUE TITLE
Quest Jungle fever bug

### ISSUE THREAD

**Issue by RealSano** [Wynncraft/Issues#6133]
In my quest book stand go to worid  but i speak to worid and he say  *Hey! Are you done with what I asked?* pls help me

**Comment by Trixter313** [comment]
Where did you leave off on the quest?

**Comment by violentsquid8** [comment]
This is happening to me as will. IGN is violentsquid8 It was months ago but I'm sure i left of at at the maze part of the quest. I did it today, right clicking on the guy at the end of the maze caused no dialogue. I went back to worrid in deltas and I got "Hey! Are you done with what I asked?"

**Comment by RealSano** [comment]
Sry but i dont know where i did leave :/

**Comment by Moe-Ronickah** [comment]
How about if both of you try /fixquests, and see if you get back the untradeable quest 64LE?

**Comment by RealSano** [comment]
Oh yes thx
