### ISSUE TITLE
Death Whistle displays incorrect text 

### ISSUE THREAD

**Issue by Pixelific** [Wynncraft/Issues#6134]
This was a previous issue reported ( #3295 ), but I am bringing it up again for a different reason. The user in that issue had problems with getting up the mountain, but I am reporting an issue because of the text it displays when you enter a certain area. If you enter anywhere within a range of coal blocks somewhat half way near the top, it will just display "/". I believe this is an error and is probably meant to display text/lore as to why you should not be near the coalblocks. I was pretty confused at first as to why a slash was showing and I was getting teleported back. (please note I'm not reporting this issue for the teleport-backs and instead for the incorrect/missing text it shows)

Here is a video for reference:
https://www.youtube.com/watch?v=lbYELMBgdSo&feature=youtu.be&ab_channel=Pixelific

**Comment by Moe-Ronickah** [comment]
@AckroWynn , would you check in to this, please?

**Comment by AckroWynn** [comment]
Fixed the issue by not letting you proceed without going through the bottom teleport area.
