### ISSUE TITLE
Can't Log Into Any Worlds

### ISSUE THREAD

**Issue by builderJP** [Wynncraft/Issues#6135]
I was in the Ocean Cave (Sarnfic) fighting the drowned citizens and I was at 99% XP at level 63 and I had VIP+. I had to go, so I logged off of Minecraft by disconnecting. I went back on and I logged onto World 1, which had 50 players. It was stuck at the "Loading terrain" for a longer time than usual, so I force quit and then I rejoined and tried a different world. I did this a lot and I had the same results. I was using a Gameband, so I went to my normal Minecraft I installed on my computer and I went into Wynncraft, and I had the same problem. I restarted the computer and tried it on both, and had the same results. Wynncraft is my favorite server and I don't know what happened. Please help me!

**Comment by Moe-Ronickah** [comment]
Just let it sit and load.  Don't even worry, unless it takes more than 5 minutes.  Loading time is dependent on a lot of things that neither you or we have any control over.

**Comment by ColinRioux** [comment]
@Moe-Ronickah I was about to respond...

**Comment by builderJP** [comment]
K. Im setting a timer for 5 minutes. Hopefully it loads.

**Comment by builderJP** [comment]
Also, I've been watching Youtube waiting for it to load for a while......so yeah

**Comment by builderJP** [comment]
Waited for 5 minutes, nothing happened. .-. I need help.

**Comment by builderJP** [comment]
Forgot to mention this, every time I join a server now, I glitch upwards like I'm lagging while falling.
