### ISSUE TITLE
chip problem

### ISSUE THREAD

**Issue by deathsbreath** [Wynncraft/Issues#6138]
in the part of ??? where you have to throw the chip on the yellow but the door wont open

**Comment by ColinRioux** [comment]
Yes, it's a known bug that sometimes the flower won't accept the chip. One known reason is if the chip has reverted to an "alex" head.

**Comment by SpeedyNinja** [comment]
I'm pretty sure that this is intentional, the quest is supposed to be unfair and there are multiple items related to the quest that also fail to work after a server change.

**Comment by ThunderRemix** [comment]
@SpeedyNinja I would have to disagree. The server cannot store the NBT data from some items correctly. Just look at the fact that the hive tokens and dungeon tokens break to alex skin.  This is indeed a server issue, not intentional.

**Comment by Moe-Ronickah** [comment]
At the present time, this issue cannot be fixed.  Changing servers, or logging off, will change the NBT data, and players will simply have to restart the quest at whatever stage in order to get the quest items necessary.
