### ISSUE TITLE
Underwater Quest

### ISSUE THREAD

**Issue by Displaid** [Wynncraft/Issues#6139]
When entering the hole next to Omango, apparently you can't enter it because you need to have a breathing helmet. But... I traded my breathing helmet for the breathing helmet II (I don't remember, I may have threw it away, tried /fixquests already)

**Comment by Moe-Ronickah** [comment]
If you threw away the breathing helmet, either one or two, then you have no other option than to start a new class and share the helmets.  Never throw away quest items.

**Comment by Displaid** [comment]
I didn't throw away the breathing helm. You have to offer the breathing
helm for the Underice quest. Sorry for the late reply.
