### ISSUE TITLE
Lost Stuff by texture pack not enabling

### ISSUE THREAD

**Issue by iJoep** [Wynncraft/Issues#6141]
Can i get my stuff back i lost all my stuff by using other pack and disabling it is there someway to fix this or so i can get my stuff pack

**Comment by Moe-Ronickah** [comment]
I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency.  You might be able to find someone to buy your lost item from, or, possibly, someone who will even give you one, for free, depending on the value of your item.  Ask around in Detlas and check the Trade Market on the forums.  Good luck.

And re-enable our texture pack.
