### ISSUE TITLE
Cosmic Armor bug

### ISSUE THREAD

**Issue by Wiffer17** [Wynncraft/Issues#6142]
When I wear my cosmic armor from the ??? quest, I start losing health instead of gaining it. I think this is a bug.

**Comment by Moe-Ronickah** [comment]
Would you post pictures of all of your armor and all of your accessories, so that we can see what is actually going on, please?

**Comment by Moe-Ronickah** [comment]
Never mind the pics, the compass is NOT reliable for elemental defenses, at all, so don't worry about it.
