### ISSUE TITLE
The Bugged Leo

### ISSUE THREAD

**Issue by Mattyboy84** [Wynncraft/Issues#6143]
after applying a leo too my set i noticed the defence didnt add up and i found this:
i dont know if this is a known bug but i think this is important

https://gyazo.com/502f0457e8b46734b0cd2b31576e327c

**Comment by Moe-Ronickah** [comment]
There also seems to be an issue with the Aquarius right now.  I don't know if it's visual or real, yet, as the Compass data is often very inaccurate.  I'm checking into it, so don't get worried, yet.

**Comment by Moe-Ronickah** [comment]
Compass info is NOT reliable, especially for Elemental Defenses.  This is not an unknown issue, but your armor is working just fine.
