### ISSUE TITLE
Guild

### ISSUE THREAD

**Issue by EnderPenguin1** [Wynncraft/Issues#6144]
I can't leave my guild with /guild leave, My leader doesn't get on so he can't kick me. The guild is ButterButt BTW.

**Comment by thecoolkogut4** [comment]
If you are in the guild two times and /guild leave won't work, then that also means it won't work when the owner/chief(s) kicks you. You are stuck in the guild till they fix the bug. (There are lots of people stuck in guilds, its not just you)
