### ISSUE TITLE
2nd Puzzle in Nohno's lab Glitched

### ISSUE THREAD

**Issue by Celsonic** [Wynncraft/Issues#6145]
I've done A B C D part of the puzzle yet I can't do this one? 
![2016-09-14_19 06 25](https://cloud.githubusercontent.com/assets/21028327/18533080/7ae3dc18-7aae-11e6-994f-369d27e51606.png)

**Comment by thecoolkogut4** [comment]
when did you do the puzzle? today? or was it a few days ago?

**Comment by Celsonic** [comment]
Figured out the issue it was on a certain server
