### ISSUE TITLE
Leaving guild not working

### ISSUE THREAD

**Issue by Napalm467** [Wynncraft/Issues#6146]
Whenever I type in guild chat it shows up twice, and I cannot leave the guild.  When I try to do /guild leave, it will show up with the sign thing and when I type "yes" in the sign it consumes my soul shards but does not actually let me leave.  Please help.

**Comment by thecoolkogut4** [comment]
If you are in the guild two times and /guild leave won't work, then that also means it won't work when the owner/chief(s) kicks you. You are stuck in the guild till they fix the bug. (There are lots of people stuck in guilds, its not just you).
