### ISSUE TITLE
Players not able to see me.

### ISSUE THREAD

**Issue by CalAnders** [Wynncraft/Issues#6147]
So, when I log into Wynncraft, no one is able to see me and when I go into my inventory or third person mode, my skin looks like the default skin. This only happens to me on Wynncraft for whatever reason. But if you can, please get back to me to help me fix this error. It is starting to drive me crazy!!

Thanks so much!

- CalAnders

**Comment by ThunderRemix** [comment]
Make sure your resource pack is working and you are on 1.8.9.

**Comment by CalAnders** [comment]
I am on 1.8 but the WynnPack is not available for use on my 8 year old computer. I just use the official pack downloaded separate in my resource pack list. And this 'glitch' has been going on for 4 weeks now.

**Comment by CalAnders** [comment]
I also have tried adding resource packs on and off my wynncraft IP in the server list. Nothing is working to add it back on.

**Comment by Moe-Ronickah** [comment]
Cal, are you on a pc or a Mac?  Have you tried making certain that you are using the latest MC launcher?  Can you try a different version of the rp?

Does anyone know what, if anything, changed 4 weeks ago in MC?

**Comment by CalAnders** [comment]
I am on Mac and I have tried newer versions of minecraft. I am currently on 1.8.9 because horses are glitched in 1.9+

**Comment by Moe-Ronickah** [comment]
He told me ingame that he fixed this.  It definitely had something to do with his resource pack, but I don't remember exactly what he did.
