### ISSUE TITLE
Skill points from set bonus not showing in compass

### ISSUE THREAD

**Issue by CMWizard** [Wynncraft/Issues#6148]
I am currently using 7 pieces of the morph set. it should provide a set bonus of 11 of each skill point. However, when i look in my compass, this is not reflected. the books update their numbers to match the base number plus given armor and accessory values, but not the 11 of each sp type that the set bonus gives. I have a base of 75 int, and armor and acc.s alone give 32 int. Adding the 11 set bonus, I should have 118 int. However, i only have 107.

**Comment by Moe-Ronickah** [comment]
The compass is notoriously bugged.  Don't worry about it, they are actually there.
