### ISSUE TITLE
Ice key boss found on llevigar plains

### ISSUE THREAD

**Issue by DehPancakeGod** [Wynncraft/Issues#6149]
I was out adventuring the other day i came from the swamp of olux onto the llevigar plains to find a ice borrows key mob thingy i ended up killing it but is it meant to be across the map like that? i dont think so please fix

**Comment by LordHelmchen98** [comment]
Key Guardians, no matter what the theme of the dugeon is, spawn in areas with the same level as the dungeon and around the dungeon (I think only for Galleons Graveyard there is another option as you can get the keys for that by the seaskipper captain)
