### ISSUE TITLE
Amshord scroll bug

### ISSUE THREAD

**Issue by Liamzigge** [Wynncraft/Issues#6150]
Hello fellow readers, a few updates ago i traveled to amshord and bought 7 scrolls, but when i tried to use them they say "you have never been to that town" witch is just wtf becouse I bought them and did not trade for them. 
happy for help :)

**Comment by thecoolkogut4** [comment]
did you buy them on class X then use it on class X? or you bought it on class X, put it in your bank and tried to use it on class Y?

**Comment by ColinRioux** [comment]
Closing due to no response.
