### ISSUE TITLE
Spawning outside a corridor after /class (Fortuneteller)

### ISSUE THREAD

**Issue by LordHelmchen98** [Wynncraft/Issues#6151]
Right before the question room in the quest 'The Fortuneteller' there is a small corridor. I went there and then changed the server. I wanted to try to prevent mobs from attacking me so I stood here:
http://puu.sh/rcyni/8f4bae23de.png
But then I changed the server and I spawned in a wall so I did /class. When I chose my mage again I spawned outside.
http://puu.sh/rcymw/631b557a27.png The arrow points about to the position where I spawned.
I dont know if its possible to fix that, but I thought you should know about that.

**Comment by Celsonic** [comment]
U use 5zig :D what is ur ign

**Comment by LordHelmchen98** [comment]
Uhh I don't think that's why this page exists. Anyway this is not 5zig this is called labymod which is slightly better in my opinion.

**Comment by Trixter313** [comment]
I think it could easily be fixed by adding some blocks above so it isn't so thin and easy to get out of. Whether it's something that will be done, we'll have to see what the builders think. =)

**Comment by FreeProGamer** [comment]
Try using [https://forums.wynncraft.com/threads/are-you-stuck.89123/](url)

**Comment by LordHelmchen98** [comment]
Are you serious?!? I know how to get back. you may have seen on the screenshots that I took the screenshots when I was on my level 100 class. This is a bug/glitch report and you would know that if you read the chat.

**Comment by LordHelmchen98** [comment]
@Trixter313 Any updates? I guess I/you could close it if its fixed.

**Comment by Trixter313** [comment]
No updates from me, I don't have connections with any builders to ask about this.

**Comment by Moe-Ronickah** [comment]
FIRST: This place exists for issue reporting, tracking, and assistance, only.

When you change servers, or switch classes, MC will rarely, if ever, place you in exactly the same spot.  You are usually placed just one block higher, but rarely displaced to the side, that I've ever seen.

@AckroWynn , can we get this fixed, although I seriously doubt that it will happen very often?

**Comment by AckroWynn** [comment]
As Trixter said, it's a matter of thickening the wall layers. I will do that once I return home from school today.
