### ISSUE TITLE
Yahya's House Bug ???

### ISSUE THREAD

**Issue by Celsonic** [Wynncraft/Issues#6152]
I put in all 3 items into the hopper, yet it does not open the door.
![2016-09-15_19 34 32](https://cloud.githubusercontent.com/assets/21028327/18570876/bccfefa4-7b7b-11e6-8d0c-352f811a1f15.png)
![2016-09-15_19 34 31](https://cloud.githubusercontent.com/assets/21028327/18570877/bd77e90c-7b7b-11e6-88b3-1188f53e9030.png)
![2016-09-15_19 34 30](https://cloud.githubusercontent.com/assets/21028327/18570878/be396e60-7b7b-11e6-9f48-2f69e4494048.png)

**Comment by Celsonic** [comment]
It has been broken since the last time the server went down, Think it has something to do with it. Please look into it. My group has been trying for the 10th time.

**Comment by Terarii** [comment]
U need fresh map, that doesn't have "Scaling at 1:1 (Level 0/4)" in the description

**Comment by Celsonic** [comment]
K Thank you .-.
