### ISSUE TITLE
Quest item duplication bug

### ISSUE THREAD

**Issue by Terarii** [Wynncraft/Issues#6155]
1. Open your bank
2. Drag and drop quest item, then fast close your bank
3. Yay you have 2 useless items!
![2016-09-16_19 38 26](https://cloud.githubusercontent.com/assets/22234802/18581765/ded5414a-7bb6-11e6-81d9-ac1fd35bc241.png)
(please delete these masks from my bank)

**Comment by Trixter313** [comment]
To get rid of any unwanted items you can put them in your daily rewards area. Just make sure you don't delete something you might need later.
