### ISSUE TITLE
Texture Pack Bug

### ISSUE THREAD

**Issue by FreeProGamer** [Wynncraft/Issues#6156]
Sometimes, when I am joining wynncraft, my bows and some other items are just getting derped, they are rotated, bigger/smaller than needed and more, here I have some screenshots (my ign is CaptainPotato132)

![2016-09-16_20 08 47](https://cloud.githubusercontent.com/assets/21259184/18594828/86696f10-7c4a-11e6-88d3-465739a78856.png)
![2016-09-16_20 08 49](https://cloud.githubusercontent.com/assets/21259184/18594832/866dec70-7c4a-11e6-8a8c-7c2fec1f6db1.png)
![2016-09-16_20 08 52](https://cloud.githubusercontent.com/assets/21259184/18594831/866c99d8-7c4a-11e6-8a10-b57f5cc7f497.png)
![2016-09-16_20 08 56](https://cloud.githubusercontent.com/assets/21259184/18594830/866c1d64-7c4a-11e6-8726-f4d0998cfedb.png)
![2016-09-16_20 09 01](https://cloud.githubusercontent.com/assets/21259184/18594829/866c00ae-7c4a-11e6-92ce-892c3eb4c430.png)
![2016-09-16_20 09 03](https://cloud.githubusercontent.com/assets/21259184/18594833/866e22da-7c4a-11e6-94ce-40bcbb3df4b5.png)
![2016-09-16_20 09 07](https://cloud.githubusercontent.com/assets/21259184/18594834/86869a22-7c4a-11e6-86a6-c04eab21df09.png)
![2016-09-16_20 09 10](https://cloud.githubusercontent.com/assets/21259184/18594835/868b7312-7c4a-11e6-9ad1-16164d85699c.png)
![2016-09-16_20 09 19](https://cloud.githubusercontent.com/assets/21259184/18594836/868c0980-7c4a-11e6-9ef8-a68c85dbc051.png)

**Comment by LordHelmchen98** [comment]
Which mc-version are you using? There are many bugs that only happen if you arent playing on 1.8.9 (1.8.8 woks also fine for me). Also the resource pack is made for 1.8.9

**Comment by FreeProGamer** [comment]
It happened when I used 1.9, 1.10 and maybe sometimes 1.8 (not sure about 1.8)

**Comment by Trixter313** [comment]
Try using just 1.8.9 for a while and see if the issue stops happening.

If it does, let us know. =)

**Comment by FreeProGamer** [comment]
Kk, I just don't really like 1.8 anymore xD

**Comment by Trixter313** [comment]
Wynncraft is made for 1.8 so unfortunately using other versions can cause issues.

**Comment by FreeProGamer** [comment]
Why


נשלח ממכשיר הSamsung שלי

-------- הודעה מקורית --------
מאת: Nick Cipriani <notifications@github.com> 
תאריך: 17.9.2016  19:24  (GMT+02:00) 
אל: Wynncraft/Issues <Issues@noreply.github.com> 
עותק: FreeProGamer <bekerman122@gmail.com>, Author <author@noreply.github.com> 
נושא: Re: [Wynncraft/Issues] Texture Pack Bug (#6156) 

Wynncraft is made for 1.8 so unfortunately using other versions can cause issues.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Wynncraft/Issues","title":"Wynncraft/Issues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Wynncraft/Issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Trixter313 in #6156: Wynncraft is made for 1.8 so unfortunately using other versions can cause issues."}],"action":{"name":"View Issue","url":"https://github.com/Wynncraft/Issues/issues/6156#issuecomment-247786119"}}}

**Comment by Trixter313** [comment]
It just isn't meant to be played with any version other than 1.8 as of right now, it is built on 1.8 still so using higher versions that aren't meant for it can cause issues.

Has the issue you reported been happening since you switched to 1.8.9 only?

**Comment by Moe-Ronickah** [comment]
Sometimes the resolution in the resource pack is picked incorrectly.  It does not affect game play, and appears to be an MC issue.  I'm closing this as it is a visual issue that does not affect game play.
