### ISSUE TITLE
My skill points keep being reset! ITS GETTING ANNOYING!

### ISSUE THREAD

**Issue by finleyuk8** [Wynncraft/Issues#6157]
Recently my skill points have been getting pushed back... ITS GETTING ANNOYING! I've heard that this bug was fixed in July (I wasn't a player back then) but apparently it hasn't this has lead to the game becoming UNPLAYABLE! I cant where my armour or use my weapon! I REALLY hope this is fixed soon as this is the 3rd time this glitch has happened to me in a month! PLEASE HELP! IGN: Finleyuk8

**Comment by LordHelmchen98** [comment]
Entirely reset? So you had to spend them again? Im just curious because I had a similar bug but it wokred again after doing /class.

**Comment by finleyuk8** [comment]
not fully reset just reduced to a lower ammount

**Comment by Trixter313** [comment]
Is your armor affecting your skill points? Some could be subtracting skills. If a skill is being affected it will say so when you mouse over it.

**Comment by DebugingLonks** [comment]
#4120 #6531 #6838 and many many more.

**Comment by Moe-Ronickah** [comment]
duplicate of #4120
