### ISSUE TITLE
Hole in new ??? quest floor

### ISSUE THREAD

**Issue by Moe-Ronickah** [Wynncraft/Issues#6158]
This is persistent, and was just reported to me.

http://i.imgur.com/SOi4eW5.png

**Comment by Celsonic** [comment]
If you go through it it will teleport you into the nether with anyone around you sometimes.

**Comment by Moe-Ronickah** [comment]
@AckroWynn , I think this is job for you, please.

**Comment by AckroWynn** [comment]
This has been fixed! Thanks.
