### ISSUE TITLE
"Defense Info" not working properly

### ISSUE THREAD

**Issue by Marianol24** [Wynncraft/Issues#6159]
The information displayed in the Defense Info menu (which you can see in the compass) is completely bugged

You can see that this ring should give me +3 air defense, and that it doesn't have any defensive ID 
![image](https://cloud.githubusercontent.com/assets/13055887/18594716/b06c59ea-7c17-11e6-9dff-0520733d8fc8.png)
But when I put it on, it says I have 3 of each defense except for thunder (I have no other piece of armor or accesory equipped, and don't have any weapon in my hotbar)
![image](https://cloud.githubusercontent.com/assets/13055887/18595346/a87d7004-7c1a-11e6-899a-d6dbc4b1615b.png)

Another example: Look at the stats these leggings have
![image](https://cloud.githubusercontent.com/assets/13055887/18595442/2be96b96-7c1b-11e6-83ad-bdc2e1ac5482.png)

When I equip them, the stats that appear in the compass are completely different (just like before, I have no ther piece of armor or weapon equipped)

![image](https://cloud.githubusercontent.com/assets/13055887/18595446/3226b8d8-7c1b-11e6-8bcb-4324d8b2f341.png)

**Comment by LordHelmchen98** [comment]
The defense information found in the compass is bugged. It should work fine although its not shown in the compass. Everything else (health in the defense info, stat bonuses, ...) should be correct.

**Comment by Moe-Ronickah** [comment]
See "compass error".
