### ISSUE TITLE
Im not in my guild that i created

### ISSUE THREAD

**Issue by ThePeach999** [Wynncraft/Issues#6160]
so i made a guild on 9/15/16 at 8:40 pm, the guild was for me and my friends to be in, so i fill out the name which is NoBody and the tag is EUP it said that i need 5le to make it, i made it and i was never put in my own guild so im like oh wow the guild hall just robbed me of my money, someone said that i should      wait a little bit so i did and nothin plz help and sry for the long bug report.

**Comment by thecoolkogut4** [comment]
The guild was created 19 hours ago and there is only one person who is the guild whos name is"ThePeach" and ThePeach is the owner of the guild.

What is your ign? When you type /g contribute what happens?

**Comment by ThePeach999** [comment]
Ign ThePeach and it says when I'm playing that I'm not in it I tried
inviting my friend but it says I need to be in a guild so IDK what to do

**Comment by thecoolkogut4** [comment]
I'm guessing you changed servers after making the guild, correct? Sorry, I don't know what else you could do. The website shows that your in a guild and the owner of it but your not really in it. weird :/

**Comment by ThePeach999** [comment]
I am thepeach and I didn't change servers at all, I guess I need to make a
new guild I guess

**Comment by ThunderRemix** [comment]
A guild called Nobody exists already, which is a reserved name for unclaimed territory and for players without guilds.

**Comment by ThePeach999** [comment]
So that's why it's bugging out?

**Comment by Moe-Ronickah** [comment]
Probably so.  It looks like you'll need to make another guild, if you want to.
