### ISSUE TITLE
Help! My necklace (the reward from Gernald in Underice) dissapeared!

### ISSUE THREAD

**Issue by TeenageCat** [Wynncraft/Issues#6162]
Please help I really need the necklace :(

**Comment by LordHelmchen98** [comment]
Wynncraft has a strict no-refund policy. If that necklace is untradeable you can only get it again with another class otherwise you can buy it from other players.

**Comment by Trixter313** [comment]
Did you recently upgrade your bank?

**Comment by TeenageCat** [comment]
I did actually Trixter

**Comment by Trixter313** [comment]
Ah, then you're experiencing the issue in https://github.com/Wynncraft/Issues/issues/4091

Bank upgrades can currently get rid of any items that are retextured glass panes, like necklaces.
