### ISSUE TITLE
Items disappearing. 

### ISSUE THREAD

**Issue by ZeeLeoNardo** [Wynncraft/Issues#6165]
Hello, so today when i logged on I encountered an issue, I lost my "Meep" which is a unique ring and also my legendary pants "Crystal". I have checked my bank, other classes for it, though it was not anywhere to be found. I'd love to have them back since they were really good pants. 

I also encountered the same issue when i was level 20ish where I lost my legendary wand.

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy and to even figure out what happened we would need more info. All we can do is assume they were accidentally dropped.
