### ISSUE TITLE
Dissapearing Scroll

### ISSUE THREAD

**Issue by FearlessDragon58** [Wynncraft/Issues#6166]
I just entered Almuj for the first time. I bought a tp scroll for Almuj for 52e. the guy said thank you, and when i closed the menu, i checked for it. its gone
i teleported to detlas, hoping it had just disappeared for a bit. it was still gone. i tried to buy a new. He said thank you then that i didnt have enough. it still took the money. i need a scroll but the game just takes my money.

**Comment by TheNeonUmbreon** [comment]
It is a problem with the server, some of the servers seem to take your money but not give you a scroll, I recommend stay of server 4 until this bug is fixed

**Comment by Trixter313** [comment]
Are you still experiencing this issue? I just logged on and successfully purchased some scrolls.

**Comment by FearlessDragon58** [comment]
No, it was a problem, but i logged on today, and i successfully bought a scroll. too bad it took 104 emeralds from me though. im saving for a horse now and need all the e i can get.
