### ISSUE TITLE
An Iron Heart Part II - Factory Helmet Missing

### ISSUE THREAD

**Issue by TheNeonUmbreon** [Wynncraft/Issues#6170]
I started playing again after a while off the server, and I have reached level 60 and have started An Iron Heart Part II. The quest is telling me to 'Take the north-east path to the factory (Requires Factory Helmet from An Iron Heart Part I)", but the problem is that I don't have the helmet...   I have completed Iron Heart Part I and have had the same issue with Underice with the Underwater Helmet (Easily fixed by making a second class and doing the quest to get the helmet), but the thing is that I don't have the time to sit here and grind a new class all the way to 49 because of an old glitch that allowed you to lose quest items. Can someone help me please.

**Comment by Trixter313** [comment]
Does using the command /fixquests return it?

**Comment by TheNeonUmbreon** [comment]
Yes it worked thanks you, I never knew that was a command xD

**Comment by Trixter313** [comment]
Glad to hear!
