### ISSUE TITLE
Bob's Weapons Are Glitching

### ISSUE THREAD

**Issue by DevinPritts** [Wynncraft/Issues#6171]
I couldn't find anywhere there was this issue. A legendary weapon has sharpness 1 on it and it wont identify. http://imgur.com/a/r0ZNz this is what i get when I try to identify it. Hopefully you can help, mainly because this should be a bobs weapon.

**Comment by MadDog1238** [comment]
I have the same issue Devin...

**Comment by Celsonic** [comment]
I am not a pro, but I assume when you got it there was extreme lag on the server, and the server couldn't load up all the tags onto the item?

**Comment by DevinPritts** [comment]
No idea about the tags just the server was probably lagging. When I first loaded it in.

**Comment by MadDog1238** [comment]
well i tried 3 days ago before i left for a trip and it still hasnt been fixed....

**Comment by Trixter313** [comment]
This is a new issue that I don't believe has been reported before. Someone should be able to look into it soon!

**Comment by DevinPritts** [comment]
Thank you @Trixter313  (don't know if that works or not lol) hope it gets fixed. :)

**Comment by Feksa** [comment]
I also have a Bob's mythic Spear which has sharpness 2... It won't identify either, hope this will get looked into soon...

**Comment by Feksa** [comment]
I can't identity my bobs mythic spear either: 
![image](https://cloud.githubusercontent.com/assets/11356733/19327501/445bb7a6-909d-11e6-8beb-800072a79501.png)
The message the item identifier says is in the background, behind my inventory.

**Comment by Moe-Ronickah** [comment]
@Imaxe , can you see if the sharpness attributes can be removed from all of Bob's Mythical weapons, please?  I'll bet that that is what is causing this problem.

**Comment by Moe-Ronickah** [comment]
I'm sorry to say, but these items are not fixable.  You can keep them as mementos, you can throw them away, or give them away, but you can't sell them to another player.
