### ISSUE TITLE
Reincarnation Mooington bug

### ISSUE THREAD

**Issue by onurhanxd** [Wynncraft/Issues#6172]
When I started the quest , I go to Skiens Island . I find the mooington's gate and find the wardener too .I get the key , throw it to hopper but gate didn't open . :/

**Comment by Celsonic** [comment]
Did you switch servers when you got the key and dropped it into the hopper?

**Comment by onurhanxd** [comment]
Yeah 3 or 4 times

**Comment by Trixter313** [comment]
What does your quest book say as well?

**Comment by onurhanxd** [comment]
I did the quest with my friend She was a mage. She used Ice snake and mooington came near us and got the hide . But when I throwed the key in the hopper the door didn't open.btw my quest book Said Bring back 1 Cluckles' Favourite Feather, Baab's Wool, and Mooington's Skin to Batelu.

**Comment by SrT3J4S** [comment]
Yes, I have the same Problem too.... I cant do the quest :(

**Comment by onurhanxd** [comment]
Yeah , Another person have the same problem

**Comment by SrT3J4S** [comment]
I just did it... Switch servers again and again till the door works, mine worked on world 8

**Comment by onurhanxd** [comment]
When I changed my server It didn't work and I not changed  one or two server but The moointon gate is really broken

**Comment by SrT3J4S** [comment]
Well, it worked for me, if u wanna do the quest then keep changing world and try world 8, it worked on world 8 for me

**Comment by onurhanxd** [comment]
I did the quest with different method
Btw thanks . But you couldn't do that in your first try so Pls fix that

**Comment by Moe-Ronickah** [comment]
@onurhanxd "I did the quest with different method".  What method did you use?

**Comment by onurhanxd** [comment]
I Didn't open the gate . I just killed him near the Iron bars and I get the hide.Thats my "different method".

**Comment by Moe-Ronickah** [comment]
That's good to know!  Still, I'd rather that the gate opens.

**Comment by onurhanxd** [comment]
Thats will be better. I want that chest :D

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
