### ISSUE TITLE
Error rendering world

### ISSUE THREAD

**Issue by Woodster2001** [Wynncraft/Issues#6173]
every time I join a server it kicks me out of Minecraft completely. it said I was flying before it happened the first time when I was on the ground
![screenshot](https://cloud.githubusercontent.com/assets/22258827/18609014/73810da4-7cef-11e6-9ed8-96ad0dc4ef2b.png)

**Comment by Celsonic** [comment]
This happens to me sometimes, it's just that Minecraft is used to starting up at a usual resolution probably. Just make Minecraft Fullscreen windowed and join WynnCraft.

**Comment by Moe-Ronickah** [comment]
I'm going to take a gu . . .. never mind.  It's an issue with 1.10.1.  Wynncraft is 1.8.9, so we suggest that you play Wynncraft with 1.8.9, or lower.
