### ISSUE TITLE
Help with account.

### ISSUE THREAD

**Issue by SirMrTacky** [Wynncraft/Issues#6174]
Hey I'm here because I have an issue regarding the VIP+ bonuses. I have tried contacting the support team but they are taking an abnormally long time to respond. its been a little over 2 weeks so if you guys can do anything about this, please help. This is what I have posted:

Dear Wynncraft Support Team,

Hello there, I am writing this because I have a problem with the VIP+ bonuses. This started a long, long time ago and now I have come to see if I can fix this problem. I have not received most of the perks that come with the VIP+ rank and I would like to receive some of the items i was promised there are pictures below of what i am missing. 

![unnamed](https://cloud.githubusercontent.com/assets/21346081/18609050/47d51296-7cc6-11e6-9917-12ce0a238f10.png)
Just saying hello.
![unnamed](https://cloud.githubusercontent.com/assets/21346081/18609065/a84f1388-7cc6-11e6-8d0f-92bdd082af9a.png)
Here I am missing the Attack Effects: Lava, Emerald, and Letter.
![unnamed](https://cloud.githubusercontent.com/assets/21346081/18609071/bc952436-7cc6-11e6-86df-7f820ec1cd54.png)
Here I am missing the Effects: Music, and Heart
![unnamed](https://cloud.githubusercontent.com/assets/21346081/18609073/d0f9c058-7cc6-11e6-9f7c-5644562752df.png)
Here i have yet to receive the Silverfish Pet
![unnamed](https://cloud.githubusercontent.com/assets/21346081/18609078/e06b01f0-7cc6-11e6-8465-94a3212a1eda.png)
And here I do not have any of the Undead Disguises

Everything else I have gotten like the bombs and OST Jukebox, only these things I am missing. Thank you for your help.

-In Game Name: "SirMrTacky"

**Comment by Trixter313** [comment]
Unfortunately anything to do with real money purchases is down to the support team. I have also noticed my messages not getting a response from them. All we can do is wait for them to respond.
