### ISSUE TITLE
Resource pack kicking bug

### ISSUE THREAD

**Issue by VOVOT** [Wynncraft/Issues#6175]
I have quite slow PC and in 9 of 10 cases, when I'm joining game, when is my computer realy slowly downloading, it will disconnect me, because I don't have resource pack yet. I think it'll be better if it will download resource pack immediately after connecting to the server.

**Comment by Moe-Ronickah** [comment]
If you search for "resource pack", you will find 120 issues, only 16 of which are still open.  Would you please read through all 120 of them (I'm not being mean and I'm not kidding) and see if any of them match what you are seeing?  Thanks, in advance.

**Comment by ColinRioux** [comment]
No response, duplicate of many issues potentially. Closing...
