### ISSUE TITLE
Stuck in Tutorial Area!

### ISSUE THREAD

**Issue by Zaqwe51** [Wynncraft/Issues#6176]
When you first start a class, you go through the tutorial area. Someone who is a level 56 mage should not be in there. "Should." I was using the seaskipper boat to take me back to Llevigar, when his dialog stopped. No items, no dialog, nothing. I waited for a couple of minutes with no result. When nothing happened i thought, "Well I'll just /kill and go back to Llevigar or something." When I /killed, however, I was sent to under the starting wagon. I can't teleport out and I'm stuck in the ground. The only way that I could be able to get out is by using my teleport scroll. 
![2016-09-17_11 14 10](https://cloud.githubusercontent.com/assets/22259264/18609184/ae12d838-7cc9-11e6-8d02-4b1a7a57df2e.png)

**Comment by Zaqwe51** [comment]
Update: I logged back in and now I'm inside a block and I can't use my teleport scroll. PLS HALP

**Comment by Zaqwe51** [comment]
WOHOOOOOOOOOOOO I /killed again and made it back to Ragni! :) Still, thats a pretty bad glitch and I hope it can be fixed.

**Comment by Trixter313** [comment]
For some things you are teleported outside of the normal map and as always, when you die you are brought to the nearest visited spawn point. The caravan just happened to be the nearest spawn point for you.
