### ISSUE TITLE
Incorrect sign display in the Lost Sanctuary

### ISSUE THREAD

**Issue by Samattack2000** [Wynncraft/Issues#6177]
This is just a small building error, but it's still one:
![2016-09-15_23 16 07](https://cloud.githubusercontent.com/assets/22138639/18609581/4683f2ba-7cd3-11e6-990a-b125424f10ee.png)
It's hard to see, but both signs are supposed to be the same, but one says you need 5 TNT, the other says 6. In the truth, it's 5.

**Comment by Moe-Ronickah** [comment]
@AckroWynn , we have a simple one.

**Comment by AckroWynn** [comment]
Can you give me the exact coords. I went with the ones on the HUD, but there are not two signs near each other there.
