### ISSUE TITLE
Beyond the Grave reward

### ISSUE THREAD

**Issue by DJNothing** [Wynncraft/Issues#6178]
In beyond the grave after you complete the quest it wont say in chat that you got raging wind. You still get it tho https://gyazo.com/68ac897f7bc95cd616a049d76525fc3a

**Comment by Celsonic** [comment]
They need to update it. You get a galleons graveyard key from Beneath the Depths as well, but it won't say so.

**Comment by Moe-Ronickah** [comment]
@Villageacules , can you fix these?

**Comment by AckroWynn** [comment]
Fixed!
