### ISSUE TITLE
An Iron Heart Part II: Factory Helmet

### ISSUE THREAD

**Issue by BenP2033** [Wynncraft/Issues#6179]
Me and my friend had just gotten to level 58 and we went to do the Iron Heart Part II quest. When we went to interrogate Elio, we couldn't enter the house, even though both of us had the factory helmet on. We tried switching servers and still couldn't go in. Can anyone help?
![2016-09-17_12 56 04](https://cloud.githubusercontent.com/assets/20451832/18610390/8716b60a-7cd8-11e6-8592-f6e8dc9716f6.png)
![2016-09-17_12 56 15](https://cloud.githubusercontent.com/assets/20451832/18610392/8c97df78-7cd8-11e6-8bea-b71da9a98c56.png)

**Comment by Trixter313** [comment]
What does it say in your quest book?

**Comment by Imaxe** [comment]
This is strange. I did this quest today and it worked fine. 
Try reidentify the item or get a new factory helmet. (Migh be a problem with the old one if you got it a long time ago)

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
