### ISSUE TITLE
Not getting xp from quests?

### ISSUE THREAD

**Issue by DeadlyShadow1** [Wynncraft/Issues#6180]
I did some quests and did not recieve any xp at all for them im not sure when you contribute xp to your guild if it takes the % or not

**Comment by Trixter313** [comment]
Quest XP does follow the guild contribute rule, explaining why the xp was lessened.

You can lessen the perc2nt you're contributing or if you'd like to not have your quests contribute any xp you can set it to 0 right before you finish them.
