### ISSUE TITLE
Wrong death checkpoint in Shattered Minds?!

### ISSUE THREAD

**Issue by Lulink13** [Wynncraft/Issues#6181]
I died from fall damage during the quest Shattered Minds: it was in the staircase room with the "odd mushroom" enemies and the stained clay.
I did visit the elf town where the quest started, but somehow I re-spawned at the beginning of the tutorial. 
(on a personal side-note, I had no scroll with me... Yaaay.)

**Comment by Trixter313** [comment]
Some parts of quests teleport you outside of the normal playing map, making the closest respawn point sometimes something you wouldn't expect.

**Comment by Lulink13** [comment]
I totally understood why this happens, but it's a problem, right? You sound like it's not going to be fixed.

**Comment by Trixter313** [comment]
It has been suggested on the forums and reported here and the admins  know about it. Last thing said about it is it would be to difficult to fix, so we'll see if it eventually gets changed or not.
