### ISSUE TITLE
Guild Glitch

### ISSUE THREAD

**Issue by AgentPanda** [Wynncraft/Issues#6182]
So today, I invited a member to my guild and he couldn't join. I tested this out with my alt and it didn't work either. Is there anyway I can fix this? Also, can you uninvite players to your guild?
Thanks.

**Comment by LordHelmchen98** [comment]
Did you try to join multiple times? It often works after a few tries. It it doesnt work I guess you will have to wait until the guilds get fixed.
I dont think you can uninvite people but you can still kick them if they get in.

**Comment by Moe-Ronickah** [comment]
Guilds are heavily glitched.  If you do a search for "guild", you will find 384 issues, of which "only" 24 are still open.  There is nothing anyone can do at this time to fix any problems with any guilds.  They need to be heavily recoded.
