### ISSUE TITLE
 My Bobs Mythic Bows is Broken

### ISSUE THREAD

**Issue by MadDog1238** [Wynncraft/Issues#6185]
G'day, Can someone plz help me, im having trouble with my "Bobs Bow" i used to play alot and i have started again, but i tried to identify my "Bobs Bow" and it says the item cant be identified again.... can someone plz help me, i spent so much time getting that bow and now i cant even use it

-MAD_DOG1238

**Comment by ThunderRemix** [comment]
Yet another item falls to this issue.

**Comment by MadDog1238** [comment]
Can Someone plz help me with this! its been 4 days since i posted the last comment!!

**Comment by AckroWynn** [comment]
Please post a picture of it.

**Comment by legoman724** [comment]
You can't re-identify a bobs mythic because it has set stats which you get when you buy it

**Comment by Moe-Ronickah** [comment]
Without a picture, there is little to nothing that we can tell you.

**Comment by Trixter313** [comment]
Appears to be a duplicate of https://github.com/Wynncraft/Issues/issues/6171
