### ISSUE TITLE
Teleport Glitch

### ISSUE THREAD

**Issue by Collor** [Wynncraft/Issues#6189]
I have the mage class and ofcourse i can use the teleport spell, but sometimes i get stuck somewhere in the map, and then i cannot use a teleport scroll or my spell to glitch back out, so i have to do /kill
and sometimes i do not have enough soul points to do that without losing some of my stuff.
so fix this please

**Comment by Trixter313** [comment]
This is just something that can happen, same with dismounting horses sometimes putting players through walls. All we can suggest is try to not teleport in corners or close to walls.
