### ISSUE TITLE
Teleporting to Llevigar?

### ISSUE THREAD

**Issue by pajrc1234** [Wynncraft/Issues#6190]
This had happened twice.
I was going in the haunted mask thing (the "Hallowynn 2014" quest) and the game lags and the guards kill me. That's not the bad part (I'm totally fine with that)

I get teleported to Llevigar. Llevigar in Gavel. I've been to it once before it even happened, but then it happened twice. It should teleport me to Maltic (that's the closest town, I think -- if not then Nemract).
I don't care about the lag part, just I want it to teleport to Maltic rather than the other side of the reigon.

**Comment by LordHelmchen98** [comment]
I think you get teleported while doing the quest. After the teleport you are far from maltic and even the normal map and at the place where you get teleported to Llevigar is the closest town. This also happens in other quests.

**Comment by Trixter313** [comment]
Some quests teleport you to places outside of the normal playing map, causing this to happen at times. Staff knows about it and currently doesn't have a fix.
