### ISSUE TITLE
Lost Legendary Dagger because of horse

### ISSUE THREAD

**Issue by noahminemaster** [Wynncraft/Issues#6191]
Today, 9/18/16 in US, I was in brimming large in 1.10. I was riding my horse when I accidently pressed Q, my horse glitched me back when I dropped it because you can't interact with your horse while doing stuff with your inventory. So my Dagger dropped and it was no where to be found, I checked chat but nothing about entities deleted. Please fix this glitch and please give me my Dagger back if you can. The info I know about it is that it sealed 90-120 dmg and was for lvl 44.

**Comment by Madib00** [comment]
I'm no moderator, but wynncraft unfortunately has a strict no-refund policy. I lost a legendary chestplate for lvl 95 today too and had to buy one for 22Le.

**Comment by Trixter313** [comment]
We recommend using 1.8.9 to play Wynncraft, using other versions can cause issues such as horse glitches.

Also, I'd suggest changing your drop key to something you're less likely to accidentally press to prevent the loss of any items you want to keep.
