### ISSUE TITLE
Lost Boat

### ISSUE THREAD

**Issue by Orangello** [Wynncraft/Issues#6192]
Boat sailed onto invisible chunk, fell off the world and lost boat.

**Comment by Orangello** [comment]
Also, placed new boat down, item disappeared and no boat

**Comment by Orangello** [comment]
Never mind, boat is back

**Comment by Madib00** [comment]
what the f**k :D

**Comment by ThunderRemix** [comment]
@Moe-Ronickah close this

**Comment by Orangello** [comment]
Still broken!
I have one boat when I should have two

**Comment by rmcar17** [comment]
Just use the seaskipper instead of boats, if your client has trouble keeping up with the server that is your own problem. I know how annoying lag is with boats. Just use the seaskipper.

**Comment by Trixter313** [comment]
Boats being laggy and odd is vanilla Minecraft multiplayer issues, as suggested above I'd recommend just using the seaskipper when possible to not have to deal with it.
