### ISSUE TITLE
Lazarus' Pit is broken again

### ISSUE THREAD

**Issue by Madib00** [Wynncraft/Issues#6193]
I'm at the part where I have to "inspect the house nearby". The dude just says the same 1 line over and over, I can't proceed. I've went through the whole pit liek 3 times and /killed once to repeat it, but it still won't work. 
"Oh no! The pit has arisen another one. Get back, foul demon!"
Basically I'm stuck between stages 9-10. The wiki says to walk closer to the dude, but that doesn't work.

**Comment by Pyromanical** [comment]
Yup, I am having the same problem

**Comment by Madib00** [comment]
I solved the problem. You have to walk upstairs in the house and the quest book will update. Then just talk to the npc.
