### ISSUE TITLE
Underworld Crypt Door Not Opening

### ISSUE THREAD

**Issue by FlimmFlamm** [Wynncraft/Issues#6194]
Hello, as the title says, I can't get the door of the Underworld Crypt to open. I've tried multiple worlds, and I've talked to the general several times, no dice. I'm pretty sure this is a bug of some juncture, and not just me being dumb.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
