### ISSUE TITLE
The Forgery

### ISSUE THREAD

**Issue by Celsonic** [Wynncraft/Issues#6196]
![2016-09-18_20 40 18](https://cloud.githubusercontent.com/assets/21028327/18620425/34f36b6c-7de0-11e6-8382-7f7044b3e6f1.png)
![2016-09-18_20 39 30](https://cloud.githubusercontent.com/assets/21028327/18620426/35c9207c-7de0-11e6-81ff-a55b7eb85488.png)

**Comment by Celsonic** [comment]
I found a forgery with only Corrupted decrepit sewer key.

**Comment by ThunderRemix** [comment]
Um... I'm only guessing here that the Pit key is using Nii Runes and not whatever rune it's supposed to use.

**Comment by Celsonic** [comment]
Thunder I'm going to guess that during the map push not all of the servers changed.

**Comment by Moe-Ronickah** [comment]
But they have, now.  Map pushes only affect servers as the servers are re-loaded.
