### ISSUE TITLE
Dungeon Keys

### ISSUE THREAD

**Issue by rmcar17** [Wynncraft/Issues#6197]
Mobs outside Ragni still drop the skeleton dungeon key whilst the relative key merchant only accepts the decrepit sewers key. So mobs still drop the wrong dungeon keys.

**Comment by ColinRioux** [comment]
I'm pretty sure that that is known, and you can trade Skeleton keys for Decrepit Sewers keys at the key conversion merchant in Detlas.

**Comment by rmcar17** [comment]
That is true but the game was intended for mobs post update to drop the new keys. They are still dropping the old keys.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/5968
It was closed as fixed so most likely it will be fixed in the next minor update or patch but I'll wait for @Moe-Ronickah to confirm.

**Comment by rmcar17** [comment]
Okay thanks, didn't see the other post
