### ISSUE TITLE
Randomly Disappearing Items

### ISSUE THREAD

**Issue by Eisean** [Wynncraft/Issues#6198]
While playing on the server with my friend we were leaving from Detlas and I looked down to my hotbar and noticed my wand ("The Head Knocker") was missing. Though I had swore that it was there a moment ago. I know the server gets rid of drops but I had it just a second ago and if I had dropped it I would have at least saw it disappear. The item randomly was removed and I don't know why. Please help.

**Comment by ColinRioux** [comment]
Well, 

Wynncraft enforces a **strict no refund policy**. That means you don't get refunds, and no one else does. This is how Wynncraft maintains fairness. 

In terms of it dropping / randomly removing, thank you for reporting it, and I don't have an actual fix except if you have the tendency to drop your items, I'd change the key assigned from `Q` to something else.
