### ISSUE TITLE
??? Hay Bale Puzzle Not Working

### ISSUE THREAD

**Issue by Muddykipper** [Wynncraft/Issues#6199]
So, I've been trying to get into the blue meteor for 2 hours.  I know exactly what to do, but when I get the Hay Sickle and try to push the hay bales, they don't move.  Sometimes they do, and sometimes when I jump they work, but they almost never work if I'm just walking at them with the Hay Sickle.  I was doing this alone with no one else with me.  Sometimes I killed the Crazy Elf Farmer again and got another Sickle, and sometimes switching between the two or three others would make the bales move.

I've been doing this for two hours and finally gave up when none of them would move anymore.

**Comment by thecoolkogut4** [comment]
if you switch servers with the hay sickle, it will break. Everytime you switch servers you need to kill the elf to get a new one.

**Comment by Celsonic** [comment]
Basically there is like an NBT tag saying that if this item is held, this block can be moved or whatever. When you switch servers the NBT tag doesnt fully transfer

**Comment by Muddykipper** [comment]
I forgot to mention, I never switched servers when this was happening.  I stayed in the same server, and the one time I DID change servers, I threw out the Sickles I had and got a new one.

**Comment by Imaxe** [comment]
Has this been fixed?

**Comment by Phatfox2** [comment]
it hasnt been fixed; the same thing happened to me.

**Comment by thecoolkogut4** [comment]
does it work if someone else trys it? or just you? are you disguised when you try it?

**Comment by Phatfox2** [comment]
it works if someone else tries it..... 

and im not disguised when i try it

**Comment by Moe-Ronickah** [comment]
This is still happening ever now and then; I keep getting questions about it in-game.

**Comment by DebugingLonks** [comment]
#7088 I TOLD YOU ALL XD
(Anyway) try jumping and sneaking 1 block away (no gap I mean directly next to it, but not pushing against it)

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.

**Comment by DebugMC** [comment]
@Moe-Ronickah Issue is still alive. Sorry for not commenting :P its not related to minecraft though

**Comment by Louis-D** [comment]
Indeed. Just to keep this bug alive.

**Comment by LordHelmchen98** [comment]
Honestly guys, I really wonder why you are having those problems. In all the attempts I did I never faced anything like that.
Which mc version were you using?

**Comment by Lakebighead** [comment]
If you're using 1.9+ and have auto jump that may be the problem.

**Comment by LordHelmchen98** [comment]
To clear that up. It seems like this problem is caused purely by mc versions. 1.8 and 1.9 should work fine but using 1.10+ will most likely cause problems, because Wynncraft is hardcoded for 1.8 and higher version are causing bugs and glitches like this one.
