### ISSUE TITLE
Underice Quest Lvl 43

### ISSUE THREAD

**Issue by BrutusGunn** [Wynncraft/Issues#6200]
So when i try to do the underice quest it wont let me go down under the ice as it's say i don't have the proper equipment. however, iv'e been wearing the breathing hat like asked and it's not working

**Comment by LordHelmchen98** [comment]
For the quest you need the 'Breathing Helmet II'. Were you wearing that or the 'Breathing Helmet I'? If you still have the 'Breathing Helmet I' you have to talk to the guy again and give him the helmet. You can buy the 'Breathing Helmet II' from the armour merchant in Nesaak. If you have that already I have no idea why its not working.

**Comment by BrutusGunn** [comment]
Well I got the Breathing Helmet II and it didn't work but I will try giving
the Helmet I to the guy.
Thanks for helping

**Comment by Trixter313** [comment]
Let us know if your issue gets resolved next time you try, thanks!

**Comment by BrutusGunn** [comment]
The quest is working now, after i gave him the 'Breathing Helmet I'
Thanks
