### ISSUE TITLE
Glitched Guild

### ISSUE THREAD

**Issue by EriTheKoala** [Wynncraft/Issues#6202]
My guild Roaming Autumin (RIA) is glitched there are some people in the guild twice and i can't leave or disband the guild. plz someone help me either kick me from the guild or disband the guild all together.
Thank you.

**Comment by thecoolkogut4** [comment]
If you changed your name you get put into the guild two times which makes it so you can't leave. There is nothing you can do about it at the moment.

**Comment by Trixter313** [comment]
Duplicate of #3665
