### ISSUE TITLE
glitched quest

### ISSUE THREAD

**Issue by br222** [Wynncraft/Issues#6204]
when i was playing i completed the quest "elemental exercise" then an error occurred and disconnected me from the server and now the mission says it is not complete buy ti did not get my 100 emeralds

**Comment by thecoolkogut4** [comment]
click the final NPC one more time to finish the quest. If you had to give him an item (that was a quest item) type /fixquests to get it back. If you had to give him a untradable item, you would have to go and get that item again (from its original spot)

**Comment by Moe-Ronickah** [comment]
Finished? Fixed?  Still broken?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
