### ISSUE TITLE
HELP ME PLZ BUG !!!!!!!!!!!!

### ISSUE THREAD

**Issue by NICELYYYYYYYYYYYYY** [Wynncraft/Issues#6206]
Hello guys
My friends Immortaal_ has a bug.
With the Update he has lost his Climbing Helmet and he don't do the Reincanation quest !
Pls give one for him !

**Comment by Trixter313** [comment]
Your friend should be able to use the command /fixquests to get it returned.

**Comment by NICELYYYYYYYYYYYYY** [comment]
THANKS YOU MEN I LOVE YOU

**Comment by Trixter313** [comment]
Glad it helped! =)
