### ISSUE TITLE
Texturepack bug

### ISSUE THREAD

**Issue by TheError007** [Wynncraft/Issues#6207]
Hey guys , i had to reinstall minecraft and redownload your texture pack and this happend 
![2016-09-19_20 36 15](https://cloud.githubusercontent.com/assets/22303558/18644728/c55cbf3a-7eaa-11e6-96d0-fbf3b82f5843.png)
![2016-09-19_20 43 50](https://cloud.githubusercontent.com/assets/22303558/18644725/c554e1b6-7eaa-11e6-9450-c0242624b0e3.png)
![2016-09-19_20 43 54](https://cloud.githubusercontent.com/assets/22303558/18644726/c555aefc-7eaa-11e6-87ba-9c56874cf7bd.png)
![2016-09-19_20 43 58](https://cloud.githubusercontent.com/assets/22303558/18644727/c55b9ff6-7eaa-11e6-870c-78f32f6ba8f2.png)
![2016-09-19_20 44 02](https://cloud.githubusercontent.com/assets/22303558/18644729/c562f058-7eaa-11e6-98a5-2081ba1dd709.png)

I will be happy if someone helps :)

**Comment by thecoolkogut4** [comment]
if you are on 1.9, delete the texture pack (named Legacy) then log into the server with version 1.8 & reinstall the texturepack.

**Comment by Trixter313** [comment]
We recommend using 1.8.9 for Wynncraft.
