### ISSUE TITLE
Wynnpack not working (at all) and forums sign up broken

### ISSUE THREAD

**Issue by poolcool2** [Wynncraft/Issues#6208]
Today I decided to try the server and the pack would start loading but never appeared.
even when I reconnected to the server 4 times.

I was going to get a forums account but when I tried it said the captcha wasn't completed correctly (when it obviously was)
even when I tried 6 times.

**Comment by ColinRioux** [comment]
Have you tried refreshing the captcha before typing it in? Also have you confirmed that you certainly didn't create an account already? (Sometimes it bugs). 

You need to be patient for the pack to load. If it freezes, then it's just loading it, and sometimes it takes a long time. If it simply doesn't load it, you could try switching minecraft versions, or downloading the legacy from this repository.

**Comment by Trixter313** [comment]
We recommend using 1.8.9 to play Wynncraft, is that the version you tried?

**Comment by poolcool2** [comment]
I was using 1.8 I also tried 1.8 shaders (I didn't use the shaders because my computer is very bad)

**Comment by poolcool2** [comment]
the captcha would either just show a check mark or would ask to click images and it didn't work either time.

**Comment by poolcool2** [comment]
I just tried 1.8.9 and I even deleted EVERYTHING from my server-resource packs folder and now instead of thinking that its working when its not now It still didn't work and the game knew this so it kept saying that I need to get it which made lag spikes which made me die so really playing in 1.8.9 was worse than when I was playing in 1.8.

If anybody could just link me to a place to download the wynnpack then I could do it that way to fix the problem.

**Comment by xJon** [comment]
I can't sign up to the forums as well. It always says reCAPTCHA incorrect although it is.

**Comment by Trixter313** [comment]
The captcha is definitely not acting correctly right now.

@poolcool2 you can download a version of the Wynnpack [here](https://github.com/Wynncraft/Issues/blob/master/legacy) but it isn't recommended as you will not receive any pack updates through that method.

**Comment by xJon** [comment]
Any idea when the registration will be fixed?

**Comment by Trixter313** [comment]
@xJon No known estimate yet.

**Comment by xJon** [comment]
I just managed to register, so I suppose it's fixed now.

**Comment by Trixter313** [comment]
Wonderful to hear!
