### ISSUE TITLE
This isn't a bug much more than a small glitch

### ISSUE THREAD

**Issue by GetSnailed** [Wynncraft/Issues#6209]
I couldn't find any other category accept for this one to ask for help on getting a quest item back. I lost it somehow and I'd enjoy it back. It's the quest item "Breathing Helmet I." Which as most of you know, helps you breathe underwater in an early on quest. Well since I lost it, I can no longer do the revamped quest "UnderIce," Nor can I do any underwater diving in Selchar. This isn't a major issue except the fact that the glitched quest will sit there without any way of me completing it.

**Comment by rmcar17** [comment]
/fixquests 
That command replaces any lost quest items.
