### ISSUE TITLE
Beyond the Grave easter egg has not been updated

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#6210]
A very, very minor bug.

### Spoiler alert!

In the spelling puzzle in Beyond the Grave, if you spell "END", there is a fake "quest completed" and "level up" message. The "quest completed" message does not show the correct amount of XP or emeralds.

This, obviously, does not affect gameplay in any way.

Easter Egg|Completion
:--:|:--:
<img width="911" alt="1" src="https://cloud.githubusercontent.com/assets/16504771/18654861/29ea5f46-7e99-11e6-9693-d443cecb3689.png">|<img width="961" alt="2" src="https://cloud.githubusercontent.com/assets/16504771/18654860/29e93850-7e99-11e6-9afa-ef8025473533.png">

**Comment by Coooldude34u** [comment]
I

**Comment by Coooldude34u** [comment]
I think this is supposed to happen.

**Comment by Moe-Ronickah** [comment]
This is meant to occur.
