### ISSUE TITLE
xp bombs (URGENT BECAUSE THEY COST IRL MONEY)

### ISSUE THREAD

**Issue by TheKingOfAnimals** [Wynncraft/Issues#6211]
if there is already an xp bomb going on your server and you try to throw one, then it doesn't let you but you still lose a bomb. I lost two bombs this way as it glitched and said 'KnightMareOfWynn's bomb has expired' but it hadn't so I tried to throw one and it did it, I presumed it was a glitch so tried again before noticing that it has subtracted bombs from my account. I'm not sure there's any way I can prove it but I would be very grateful if, even if you couldn't refund my bombs, you could fix the glitch so that this doesn't happen to anyone else.

Thank you for taking the time to read my glitch report.

**Comment by Trixter313** [comment]
If you'd like to try to get a refund still, you can try emailing support@wynncraft.com with what happened and they will consider it. Although their response time hasn't been the best recently they should get to it eventually.

**Comment by Coooldude34u** [comment]
Its a wynn bug, but I do not think its fixable. I dont know why you tried to throw another dxp anyway. And there is a no refund policy on wynn

**Comment by Trixter313** [comment]
@Coooldude34u the refund policy doesn't apply to items that cost real money. Those are handled on a case by case basis by Wynncraft support.

**Comment by Trixter313** [comment]
Actual issue should be resolved by recent patch https://forums.wynncraft.com/threads/1-14-2-wynncraft-patch-1.163111/
