### ISSUE TITLE
poison damage not working at all.

### ISSUE THREAD

**Issue by TheActa2r179h** [Wynncraft/Issues#6212]
hi, i should deal 6400 in poison damage, but when i hit mobs nothing happens, could you fix that?

**Comment by legoman724** [comment]
Poison damage is damage that happens after you hit the mob, eg if you have 300/3s poison then 300 damage in the 3 seconds after you hit the mob, I'm also not sure if this triggers every time but I think so

**Comment by TheActa2r179h** [comment]
It's working now, but i don't know why it didn't in the beginning.
