### ISSUE TITLE
/fixquests isn't giving me the right items

### ISSUE THREAD

**Issue by GetSnailed** [Wynncraft/Issues#6216]
I made a small complaint about not having my "Breathing Helmet 1" the other day, and upon reading the answer, I did attempt to do the command /fixquests. It gave me some items I already have, and not to mention that it refuses to give me the Breathing helmet. What do I do?

**Comment by LordHelmchen98** [comment]
Well if you cant get it back this way, you can get it again very easily. Just create a new class and get it to level 8 so you can do the Underwater quest again. After that bring put the helmet in your bank and take it with your the class you need it for. Then you can delete the new class if you dont need it or use it as a bank class.

**Comment by thecoolkogut4** [comment]
do /fixquests on the class you lost the item on.

**Comment by Trixter313** [comment]
/fixquests is known to be very buggy and odd. As @LordHelmchen98 said, luckily, it is relatively easy in this case to get around by leveling another class a bit and doing the quest.
