### ISSUE TITLE
i cant even explain... lets call it class bug?

### ISSUE THREAD

**Issue by hvchvc4** [Wynncraft/Issues#6217]
http://imgur.com/a/v5zZ9
copy this link. youll see a photo of me, as my warrior class, after i opened the class menu and chose warrior. in the photo youll see me holding a normal spear, and my spear is fighting spirit (tisasun's proof texture). also, you can see that im hovering over my necklace, and alot of purple codes show up. you will also see 3 wands, unidentified, but when i hover on it it shows the name (sage, joker, unholy wand) like you renamed it in an anvil. no colors and no lore.
idk if you need to fix this bug i think its a rare bug.
my ign is FactionsSenpai if you wanna contact me.

**Comment by thecoolkogut4** [comment]
im pretty sure the bug in the first place is that you are in the class selection menu WHILE on a class, because of that (which your not meant to be in) it makes the item names glitch out.

**Comment by hvchvc4** [comment]
ok ty
