### ISSUE TITLE
Can't post?

### ISSUE THREAD

**Issue by pajrc1234** [Wynncraft/Issues#6218]
This isn't about the game, it's about the forums.

I literally cannot post on the forums. When I try to make a thread, it doesn't show the thing where I actually type in my content. And then I can't post because I need 10 characters (I don't want to post anyway - I can't get anything to say because of this).

I was going to apply for a guild just a minute ago, and the text box thing still wasn't there! I really wanted to join a guild because I haven't been able to get one from in game, so this would've been the only way to join one.

**Comment by thecoolkogut4** [comment]
maybe a plugin for the browser is causing this. Do you have adblocker or some other extension, if you do disable all of them and try to see if you can post normally.

**Comment by pajrc1234** [comment]
I don't have any extensions.

**Comment by Trixter313** [comment]
What browser are you using?

**Comment by pajrc1234** [comment]
Google Chrome. I already posted a few times but then it stopped working

**Comment by Trixter313** [comment]
Try doing it in another browser, does the box show up then?

**Comment by Moe-Ronickah** [comment]
Fixed or not fixed?

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
