### ISSUE TITLE
Lazarus Pit Quest Bug

### ISSUE THREAD

**Issue by minecraftsman03** [Wynncraft/Issues#6221]
When I go to the graveyard, the text that's supposed to appear isn't showing up, so it's impossible for me to continue the quest, this has been happening for quite sometime, please help.

**Comment by thecoolkogut4** [comment]
what does your quest book tell you to do?

**Comment by Coooldude34u** [comment]
#questbookchecks

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
