### ISSUE TITLE
2 glitched Items in my Bank ender Chest

### ISSUE THREAD

**Issue by 3535677** [Wynncraft/Issues#6222]
I have a stack of 64 arrows and 2 compasses that say characther info in my enderchest bank that wont go away if I click them they refuse to move or be thrown out can an admin go into my ender chest and force delete them?
![image](https://cloud.githubusercontent.com/assets/22357795/18732264/d9e3be64-802f-11e6-8686-e9c1fde2bef0.png)

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3147

**Comment by Moe-Ronickah** [comment]
First question - have you been gone for a long time?
Second, we don't recommend that you use any MC version higher than 1.8.9.

**Comment by 3535677** [comment]
I cant recall , but  I am fairly certain a long time ago I did play on the
server which is why those bugged items are there.
