### ISSUE TITLE
Relics not giving right powders

### ISSUE THREAD

**Issue by valttii** [Wynncraft/Issues#6224]
I wanted to get the tier 5 and 6 yellow powders but when i got to the relic shrines and broke the seal both of them gave me the tier 2 yellow powder instead of the tier 5 and 6 powders, in chat it said "you broke the tier 5/6 seal +tier 2 yellow powder". Please fix and i would like the powders i couldn't get. Btw i took a screenshot but i don't know how to post pictures.

**Comment by LordHelmchen98** [comment]
That works correctly although I dont like it either. But if you break a t5 relic you only have a chance to actually get a t5 powder, which is quite annoying in my opinion as I went to all 5 t6 relics and got 1 t3 and 4 t2's :/

**Comment by thecoolkogut4** [comment]
Powder relic VI's drop up to VI powders but also anything below. It's similar to horse breeding where you will get a random one but up to VI. (Same thing for V, they drop up to V but there is a high chance it goes under)

**Comment by valttii** [comment]
Thanks for clearing it up! But I must say thats a very frustrating and stupid thing to put in the game and not make it very clear to all players.
