### ISSUE TITLE
Changing a thread's title in the forums

### ISSUE THREAD

**Issue by xJon** [Wynncraft/Issues#6227]
Unfortunately I can't manage to do so. When I change it and click "save", the page refreshes but no change occurs.

**Comment by Trixter313** [comment]
Changes can sometimes take a while to be shown or it could have been an odd caching thing. Did it eventually update for you?

**Comment by xJon** [comment]
No, even after a few days.

**Comment by Coooldude34u** [comment]
I would say, keep trying or just inform the people looking at the thread like this:

(Sairy Glitch)
oops! i meant to say ''Fairy Glitch'' 

like that.

**Comment by xJon** [comment]
*"Did you try to turn it on and off again?"*
..
Any chance for an actual fix?

**Comment by Moe-Ronickah** [comment]
Which thread?  What's the title?  What do you want to change it to?  Is the thread locked or open?  Are you the original thread author?

**Comment by xJon** [comment]
*My* thread, I'm the original thread author. It's not locked. [Link](https://forums.wynncraft.com/threads/wynncraft-plus-a-lightweight-wynncraft-modpack-for-technic%E3%80%90solder%E3%80%91%E3%80%901-8-9-1-10-2%E3%80%91.154832/)

**Comment by Moe-Ronickah** [comment]
OK.  Now I see it.  It's not a bug, it's the forum software rules.  It can't be forcibly changed, by anyone.  I tried to alter it, and it reverted.

**Comment by xJon** [comment]
So why is this an option? 

![](http://image.prntscr.com/image/dc956f26afff40f4a2b671d2fccb72b6.jpeg)
