### ISSUE TITLE
Death Whistle quest.

### ISSUE THREAD

**Issue by Moderocky** [Wynncraft/Issues#6230]
<img width="559" alt="screen shot 2016-09-23 at 17 56 02" src="https://cloud.githubusercontent.com/assets/14147477/18794402/44ee8f12-81b7-11e6-8dbc-0aa18f76d30a.png">
Voer won't accept my leaf, no matter how many I bring. This has been happening for at least four months and nobody has done anything to fix it. I'm having to farm zombies to try and reach a level with a working quest.

**Comment by ColinRioux** [comment]
You're giving Voer the wrong flower, most likely. Have you gone to the exact location in your quest book?

**Comment by legoman724** [comment]
Are you escape spelling up the mountain? If so then go through the teleporter blocks in the hole in it at the bottom, go up in the area that you tped to and then you'll be at the top, it should work then

**Comment by Coooldude34u** [comment]
you are probaly using the right flower, but you cannot teleport up the mountain. You have to go through the hole in the path. Then it should work

**Comment by Trixter313** [comment]
Please let us know if the issue is resolved for you or not. Thanks!

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
