### ISSUE TITLE
Cant join guild.

### ISSUE THREAD

**Issue by mobinblack** [Wynncraft/Issues#6231]
that is the picture I have, as you can see I was invite to guild but I could not join
.
![image](https://cloud.githubusercontent.com/assets/21084277/18799848/fdf2a134-81a7-11e6-9b68-113bfa7a771e.png)

**Comment by ColinRioux** [comment]
If you have changed your in game name recently, there is a known bug that you can't leave or join guilds. Sorry for the inconvenience.

**Comment by mobinblack** [comment]
Haven't changed my name EVER before.

**Comment by PixlCraftr** [comment]
it is a common bug. for me it worked after i invited players for 10-20 times

**Comment by Coooldude34u** [comment]
what you do, is after like 10 or something tries, you relog. Make sure its a different world tho.

**Comment by Moe-Ronickah** [comment]
@mobinblack , in the upper right corner of your image, you have a map mod loaded.  No problem.  You have entity radar on.  That's a problem.  Turn it off.
