### ISSUE TITLE
Teleport problems (SOS please respond)

### ISSUE THREAD

**Issue by ConSavvy** [Wynncraft/Issues#6234]
I used a teleport spell in the Mansion for the Mansion Delivery quest. It appears to have teleported me into the roof. I cannot use TP spell again as my head is in the roof, and Teleport scrolls won't work. Please respond, or TP me out if you are an admin. My Username is Con__Savvy

**Comment by ConSavvy** [comment]
I got out, but PLZ fix the bug

**Comment by ColinRioux** [comment]
Please, in the future, don't open and close the issue / bump. For future reference, if you're stuck, try `/kill` with 4 or more soul points.
