### ISSUE TITLE
Mystic Sandals minus elemental stats

### ISSUE THREAD

**Issue by TiaDarkstrider** [Wynncraft/Issues#6235]
My mystic sandals say they are +10 water, - 5 thunder and -1 earth but in my defense info it is -10 air, -10 earth and -10 thunder.
![2016-09-24_19 51 37](https://cloud.githubusercontent.com/assets/22411924/18807669/8a64444a-8290-11e6-8ab3-51e60581abc2.png)
![2016-09-24_19 51 52](https://cloud.githubusercontent.com/assets/22411924/18807670/8a64733e-8290-11e6-9b0e-3566eb7d9f14.png)

**Comment by DJNothing** [comment]
compass is bugged

**Comment by Trixter313** [comment]
As said above, the compass is currently known to be incorrect and being worked on. It should be fixed soon!
