### ISSUE TITLE
Stuck in a wall

### ISSUE THREAD

**Issue by pushi2009** [Wynncraft/Issues#6237]
Slept in a bed in a house near Llevigar at -1966, -4762 and now my top half is stuck in the ceiling. Tried using scrolls, won't work, please fix

**Comment by Trixter313** [comment]
You can use the command /kill to get out. For future reference, try to not sleep in beds on Wynncraft. Thanks!

**Comment by pushi2009** [comment]
Okay, thanks a lot!
