### ISSUE TITLE
Ice barrows Stuck bug

### ISSUE THREAD

**Issue by 1manned** [Wynncraft/Issues#6238]
2 of my friends and i went to the ice barrows dungeon. All 3 of us got to the boss stage and pressed the button and went in. my 2 friends got sent in but i got stuck in a black box with a trapwire sound on the floor. i had to kill my self to get out. 
![bug](https://cloud.githubusercontent.com/assets/22414997/18809046/93da7832-8240-11e6-953a-bde7dca991d4.png)

**Comment by Coooldude34u** [comment]
I've seen this glitch, its because when multiple people come there is a chance that wynncraft will bug and not process the fact that there is more than the number of people it sent. It bugs the trapwires. Just keep trying and it should work if u try alone

**Comment by Moe-Ronickah** [comment]
Actually, this is a known MC mechanic error.

**Comment by thesteeltoenail** [comment]
I don't think this should be closed, it just happened to me and a friend. I would like to see a fix.
