### ISSUE TITLE
Can't connect to wynncraft website/wiki/map 

### ISSUE THREAD

**Issue by Gegaba** [Wynncraft/Issues#6239]
Hi. One problem I have lasts for a month. When I try to connect to sites, the page just does not load, and every time this error [image](http://imgur.com/a/oZ4yj).
What I was trying to make : 
checked PC for viruses, 
turned off the firewall, 
wrote my internet service provider,
connected by cable directly, bypassing the router
booting in safe mode with network drivers
used different browsers
connect to the website from my tablet, using the neighbor's Wi-Fi
and many other things... nothing helps.
I recently found another player from Russia, who has the same problem, so I decided to write here. Can you help?

**Comment by Celsonic** [comment]
Wynncraft took to long to respond... or its blocked on your service. Who knows.

**Comment by Coooldude34u** [comment]
erhm, use a different internet. Or maybe make that picture ENGLISH so i can indentify the problem more clearly.

**Comment by Gegaba** [comment]
k, here [http://imgur.com/a/3XkBf](url)
different internet - "using the neighbor's Wi-Fi" - did not help
and my internet provider said that from his side everything is fine

**Comment by ColinRioux** [comment]
Have you tried connecting via a cellphone (both through data and on your wifi connection)? 
Also are you having this problem with http and https sites. Wynncraft and all it's child sites are secure, or https. 
Have you tried using VPN? Perhaps you're IP banned? 
You could also try using public DNS. 

There could be quite a few factors. Based on what you've tried, those aren't the answers right now. Try what I've suggested, if nothing prevails, comment back.

**Comment by Gegaba** [comment]
Have you tried connecting via a cellphone (both through data and on your wifi connection)? -- I have no phone, only a tablet and a laptop. Yesterday I reset the router to factory settings and set up again, tried to connect - not help.
Also are you having this problem with http and https sites. Wynncraft and all it's child sites are secure, or https. -- no, all other sites, besides these three, normally open.
Have you tried using VPN? -- Yes, I installed the vpn yesterday, sites now open, but it is not very convenient, have to wait in line to join. I would like to solve the problem without using vpn.
Perhaps you're IP banned? -- maybe, but I don't know how to find out
You could also try using public DNS -- tried to change on google public DNS - 8.8.8.8 - not help
:(

**Comment by Villageacules** [comment]
@Gegaba Is still still happening?

**Comment by Moe-Ronickah** [comment]
@Gegaba , please clear your browser history files and let us know if that works.

**Comment by Gegaba** [comment]
@Moe-Ronickah a week ago the site started to open, so that everything is ok now
