### ISSUE TITLE
Seaskipper Issues.

### ISSUE THREAD

**Issue by Celsonic** [Wynncraft/Issues#6240]
Basically part of the map was cut out when someone copied and pasted it into here.
![2016-09-24_17 30 10](https://cloud.githubusercontent.com/assets/21028327/18811427/db8dbeb4-827c-11e6-8482-e88cebe6481d.png)

**Comment by Celsonic** [comment]
Also, I used the Seaskipper from Selchar to Zhight island and somehow got here. 
![2016-09-24_17 38 16](https://cloud.githubusercontent.com/assets/21028327/18811462/f0903b10-827d-11e6-9cea-c33ca2bbe8f8.png)

**Comment by Coooldude34u** [comment]
Its just a couple editing, command glitches. Ignore them, but if you do experience problems with actually getting to your destination, post them

**Comment by Celsonic** [comment]
K changed the title.

**Comment by Imaxe** [comment]
This terrain error is fixed. :)
