### ISSUE TITLE
WynnExcavation Site C Respawning in Almuj

### ISSUE THREAD

**Issue by MaDmaxwell311** [Wynncraft/Issues#6244]
I was at the part of the quest where I was looking at the red crystal and then a WynnExcavation Guard shot me, but instead of respawing at the nearest city to the volcano, you respawn at Almuj.

**Comment by LordHelmchen98** [comment]
When you are inside the volcano for the quest you get teleported so you are not on the normal map anymore but far away from the normal cities. Therefore it searches for the closest city when you die and apparently Almuj was the closest one. That happens not only in WynnExcavation C but in many quest where you get teleported off the map. If you die in the Shattered Minds quest, for example, you get to the caravan-guy at very beginning of Wynn.
