### ISSUE TITLE
Can't see wynncraft map

### ISSUE THREAD

**Issue by ninja2003** [Wynncraft/Issues#6245]
Since the new updated wynncraft map i haven't been able to see the map here is a screenshot:
![picture](https://cloud.githubusercontent.com/assets/7515479/18814414/a7ef13e6-8312-11e6-9b6d-1f2a176159d2.PNG)
Heres what the text says:

> If you can see this message, there is likely a problem loading the Overviewer javascript components. Check the javascript console for error messages.

And here is the javascript console:
![console](https://cloud.githubusercontent.com/assets/7515479/18814421/0e1db604-8313-11e6-886e-5b7a3d8ea4db.PNG)

**Comment by LordHelmchen98** [comment]
Once this happened to me as well but it worked after I refreshed. I guess you have tried that as well, haven't you?

**Comment by jonvtran** [comment]
I had this problem too. They way I fixed it was going to browsing history and clearing my cookies and cache since the problem started to happen.

**Comment by Moe-Ronickah** [comment]
RESOLVED
