### ISSUE TITLE
25/09/2016 spotted mass spam - Crashed wynncraft

### ISSUE THREAD

**Issue by RealmLord** [Wynncraft/Issues#6246]
So I was playing Wynncraft, while being in Detlas about 20 commands appearing in the chat per second, all saying that a single player has 'typed' the wrong spell command. This happened for at least 10 seconds, before Wynn came to a massive crash, about 5 hours have already passed after the crash occurred, and I still cannot log back in. Message when trying to log in:

Could not connect to default or fallback server, please try again later: java.net.ConnectException

**Comment by Trixter313** [comment]
https://twitter.com/Wynncraft/status/779963360867602432

Staff is aware of the issue and working on a fix. I'll update here when there's a change.

**Comment by Moe-Ronickah** [comment]
Servers are up.
