### ISSUE TITLE
Can't proceed with quest. 

### ISSUE THREAD

**Issue by bvcxz654321** [Wynncraft/Issues#6247]
In the quest "Fantastic Voyage" I was doing the quest and got to the part where I have to give Relend the soup. After I gave him the soup I left the lobby because it was laggy so I can join a new one. After I joined back the quest book told me to give him the soup. I try clicking on him but he won't let me proceed with the quest.

**Comment by benjaminqp479** [comment]
do /fixquests    ??????

**Comment by bvcxz654321** [comment]
I know I did that's how I got my soup back.

**Comment by Imaxe** [comment]
So is this fixed?

**Comment by bvcxz654321** [comment]
No

**Comment by Trixter313** [comment]
So you're still stuck on the part where you have to give them the soup, even after using /fixquests?

**Comment by bvcxz654321** [comment]
Yes

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
