### ISSUE TITLE
Random Barriers

### ISSUE THREAD

**Issue by DirtyDoge** [Wynncraft/Issues#6248]
By the Tribal Sanctuary boss altar, I found a string of barriers. Here is proof:
![2016-09-25_12 16 21](https://cloud.githubusercontent.com/assets/21346185/18816980/9829b472-831a-11e6-971b-4081ed219ec1.png)

**Comment by Imaxe** [comment]
I'm pretty sure it's supposed to be there. I'll close this thread soon

**Comment by Imaxe** [comment]
I
