### ISSUE TITLE
Breathing Helmet Problems

### ISSUE THREAD

**Issue by NinjaMaster909** [Wynncraft/Issues#6249]
So, I was helping a friend with the underwater quest (the one where you get the breathing helmet I) and I couldn't help him through the underwater section because I supposedly didn't have a breathing helmet. I in fact did have a breathing helmet, but it was the breathing helmet II! So this quest isn't detecting this breathing helmet II.

**Comment by Trixter313** [comment]
Does using the command /fixquests return the helmet I?

**Comment by LordHelmchen98** [comment]
You said you only had a Breathing Helmet II, so I guess you did the new Underice quest. Therefore there are two options. Either you have another class that has done Underwater but not Underice, then you can use the breathing helmet of this class, or you create a new class level it to level 8 and do the quest again yourself.
@Trixter313 as he has done the Underice quest I dont think he will get the Breathing Helmet I by doing /fixquests.

**Comment by NinjaMaster909** [comment]
@LordHelmchen98 Well...couldn't it be a little easier to just fix Underwater so that it also detects the Breathing Helmet II?

**Comment by LordHelmchen98** [comment]
Well yeah right that **could** be done but I only told you what your possibilities are right now. And to be honest I think there are things that are more important to fix.

**Comment by Moe-Ronickah** [comment]
@NinjaMaster909 , and @LordHelmchen98 , please pm me on the forums.

**Comment by Imaxe** [comment]
We can only detect one item per region. Which means, you'll need the proper helmet.

**Comment by Moe-Ronickah** [comment]
Imaxe, welcome to the club.  Builder, GM, and/or CB?  I want to know what I can assign to you.

**Comment by Moe-Ronickah** [comment]
RESOLVED
