### ISSUE TITLE
EMPTY tier 2 chest !

### ISSUE THREAD

**Issue by EnderManKing** [Wynncraft/Issues#6250]
![screenshot from 2016-09-24 15 04 33](https://cloud.githubusercontent.com/assets/20938040/18817536/81b418e8-8317-11e6-8e65-9e1ab078355e.png)

i don't know what happened ! but i found this in my game !

**Comment by TeenageCat** [comment]
low-level area high-level character

**Comment by Moe-Ronickah** [comment]
We really need the coordinates of the chest, to see if this is persistent or if this is a temporary glitch while the servers are acting up.

**Comment by EnderManKing** [comment]
Ok. I'll get the coordinates.

**Comment by EnderManKing** [comment]
The cords are 607 55 -1470

**Comment by Moe-Ronickah** [comment]
@AckroWynn , can you take a look at this and see what the problem may be?

**Comment by Celsonic** [comment]
@Moe-Ronickah The merchants.. now this... who knows...

**Comment by EnderManKing** [comment]
Did I do something wrong? I'm concerned. I really don't want to get banned. I just want to help,

**Comment by EnderManKing** [comment]
Hey I was hacked. My password doesn't work, and the only reason I can post this is because it is through an email. A little help ?

**Comment by ColinRioux** [comment]
I don't quite understand why your account would be "hacked" considering it has no public personal information and no projects. But in terms of your "password" have you confirmed you're typing it in correctly / can you reset it? 

You haven't done anything wrong, it's probably just a wynncraft bug. If you were doing something wrong, I would think you wouldn't post an issue.

**Comment by EnderManKing** [comment]
But there's my problem ! I did re

**Comment by AckroWynn** [comment]
@Moe-Ronickah I checked on our GM-server, and it seems to be working just fine.
