### ISSUE TITLE
Trade Bug / Crash

### ISSUE THREAD

**Issue by BazarLaNouille** [Wynncraft/Issues#6251]
I trade items for look ID's and the server crash i reconnect to the server and i don't ave my items (3 Third eye( wich 2 cheated ids))

**Comment by Moe-Ronickah** [comment]
I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency.  You might be able to find someone to buy your lost item from, or, possibly, someone who will even give you one, for free, depending on the value of your item.  Ask around in Detlas and check the Trade Market on the forums.  Good luck.
