### ISSUE TITLE
game crash when going near the dungeon near ragni

### ISSUE THREAD

**Issue by samohtseyah** [Wynncraft/Issues#6255]
I am on 1.10.2 with no mods and when i go on the server and go near the dungeon near ragni

[crash-2016-09-25_14.53.54-client.txt](https://github.com/Wynncraft/Issues/files/491919/crash-2016-09-25_14.53.54-client.txt)
[crash-2016-09-25_14.52.48-client.txt](https://github.com/Wynncraft/Issues/files/491920/crash-2016-09-25_14.52.48-client.txt)

**Comment by Moe-Ronickah** [comment]
First, I'm not opening your text files.  Second, Wynncraft is 1.8.9 compliant, and we suggest that you don't use any higher version of Minecraft.
