### ISSUE TITLE
Rymek doesn't act as a proper respawn point

### ISSUE THREAD

**Issue by Amariithynar** [Wynncraft/Issues#6256]
When you die in the close vicinity- or even inside of- Rymek, it doesn't respawn you at the location, instead shunting you significantly out of the way to the town of Tenhaves nearby. To return you have to go all the way around a fairly large mountain and go down into the chasm once again just to return to the general area; it can take over a minute with a teleport-spec mage build to get there efficiently, longer for other classes who can only run, though horses do assist somewhat.

As it is a town missing only the function of an emerald merchant (instead replaced by Rymek dealer merchants who deal in gold) but otherwise feature complete, it should properly respawn those who die in the area at that town.

**Comment by Moe-Ronickah** [comment]
@AckroWynn , any ideas on this?

**Comment by AckroWynn** [comment]
@Moe-Ronickah For now, it is intentional. If you die to Bob, you would respawn there, which we do not want. When we get a not-so-bad respawning system, we will change this.

**Comment by Amariithynar** [comment]
Is there any way that you could tie that directly to the killing blow being dealt by Bob, instead? When you're levelling and going through the area normally, it's incredibly vexing.

**Comment by Amariithynar** [comment]
...Why was this closed when there's still an issue involved?

**Comment by Trixter313** [comment]
As stated above, the current functionality is intended. If sometime in the undetermined future the respawn system changes it can be changed.

**Comment by Amariithynar** [comment]
Which doesn't answer "Is there any way that you could tie that directly to the killing blow being dealt by Bob, instead? When you're levelling and going through the area normally, it's incredibly vexing.", but whatever.

**Comment by Trixter313** [comment]
If you'd like to post a suggestion, there is a section on the forums for them: https://forums.wynncraft.com/forums/general-suggestions.69/

This page is mainly for issues, ''what if..." or "could this..." questions typically do better in the suggestions area on the forums as that's what it's intended for and you can get community feedback on your idea as well. =)

**Comment by Amariithynar** [comment]
It was a question about a potential alternative solution to just locking
respawns out of Rymek on a technical level.

**Comment by AckroWynn** [comment]
To answer your question, no we can not. That is why I said that in the future, when we get a better spawning system, it might be possible.

**Comment by Amariithynar** [comment]
Thank you.
