### ISSUE TITLE
My Rank

### ISSUE THREAD

**Issue by BoostedApeRage** [Wynncraft/Issues#6257]
Hello I'm BoostedApeRage I recently purchased a rank upgrade and It said wait about 10-15 minutes I waited 30-40 I bought Vip-Vip+ And I asked a mod but he logged off on me and only said there is a problem I want to know whats the problem so I can be sure I get the rank I payed for please read this I have the email stating the proof of my purchase so please fix this I would love to play more with my rank

**Comment by ColinRioux** [comment]
Keep the email with proof of purchase, and if you still don't get it, email `support@wynncraft.com` with proof.

**Comment by Moe-Ronickah** [comment]
Right now, with the store undergoing some major changes, purchases have been going very slowly.  I'm sorry for the delay, however, all we can do is to wait this out.  Please do as ColinRioux suggested, and make certain that you keep your email proof of purchase.
