### ISSUE TITLE
Bob's Lost Soul - Bug? / Inconsistency

### ISSUE THREAD

**Issue by Xeraphiim** [Wynncraft/Issues#6259]
I logged onto an old lvl 40 character I had a couple years ago, and, just recently, did the Temple of the Legends quest. I didn't have Bob's Crushed Soul on hand since I didn't do the Lost Soul quest yet. I got the crushed soul and then did the Legends quest. But now I want to do Bob's Lost Soul and now I can't. The blacksmith won't allow me to extract the weapons. So now I can't do Reincarnation lvl 74, and I don't know what to do.

**Comment by Imaxe** [comment]
Can you give a more detailed description of your problem. 
ToL is a lvl 60 something quest, so you couldnt have done that on your lvl 40.

**Comment by Trixter313** [comment]
How did you get the crushed soul without doing Bob's Lost Soul in the first place? Also, does using /fixquests do anything?

@Imaxe I'm guessing they didn't mention leveling up the class a bit, if you look on the stats page the character is level 81.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
