### ISSUE TITLE
Unable to identify armor sets

### ISSUE THREAD

**Issue by AutumnElegy** [Wynncraft/Issues#6260]
I have a Tribal armor set and a black cap from pre-gavel and I can't identify it

http://prntscr.com/cme2yl

**Comment by Moe-Ronickah** [comment]
It's too late to do anything with these.  The only thing that you can do is toss them into a disposal, or into lava.  You can keep them, if you want to, but they are worthless.

**Comment by Imaxe** [comment]
As Moe said, the items are broken. So I'm closing this thread
