### ISSUE TITLE
grass error with forge or xaeros minimap mod

### ISSUE THREAD

**Issue by bluemusic999** [Wynncraft/Issues#6261]
why hello there... for some reason when i use forge.. or atleast xaeros [minimap](http://www.minecraft-downloads.com/xaeros-minimap/) for somereason the grass in the game is a purple and black box (like those from garrys mod when you dont have the css textures) tho when i upload the server on just optifine, its normal grass... it really bugs me and i REALLY wanna use a minimap mod, and i just find it really annoying that there are so many black and purple boxes everywhere... ((also its just the grass, i couldnt find any other blocks that are not purple and black, its just the walk threw grass
![2016-09-26_19 20 36](https://cloud.githubusercontent.com/assets/18036471/18829204/97cf200c-841e-11e6-8919-af43ab581f9e.png)
![2016-09-26_19 21 13](https://cloud.githubusercontent.com/assets/18036471/18829205/97d0298e-841e-11e6-8144-7f16540cdaab.png)
![2016-09-26_19 21 15](https://cloud.githubusercontent.com/assets/18036471/18829206/97d2fb32-841e-11e6-99b4-4b9d4bb32b04.png)
![2016-09-26_19 21 21](https://cloud.githubusercontent.com/assets/18036471/18829209/97e25456-841e-11e6-9d58-e4f31968de8f.png)
![2016-09-26_19 21 47](https://cloud.githubusercontent.com/assets/18036471/18829208/97dc7860-841e-11e6-81ba-f006df21f0fa.png)
![2016-09-26_19 21 53](https://cloud.githubusercontent.com/assets/18036471/18829207/97dc0682-841e-11e6-995c-e865d2928def.png)

**Comment by LordHelmchen98** [comment]
Which Minecraft version are you using? Wynncraft is based on 1.8.9 and so is the resource pack. The pack is known be bugged in 1.9 or 1.10.

**Comment by bluemusic999** [comment]
im using 1.10.2 and 1.10 but when i dont use forge the grass is normal

**Comment by Moe-Ronickah** [comment]
1:  Turn off your entity radar.  We don't allow it in our game.
2:  This is a forge problem.  Wynncraft is 1.8.9 compliant, and we do not recommend playing Wynncraft on any higher version of Minecraft.

**Comment by ThunderRemix** [comment]
Close this issue. :/

**Comment by Imaxe** [comment]
This isn't really a wynncraft issue... Try changing version or just uninstall the map or something.
