### ISSUE TITLE
The House of Twain Quest Bug

### ISSUE THREAD

**Issue by bjw54321** [Wynncraft/Issues#6263]
I started the quest, The House of Twain and got to the part where you collect the Ghostly items. I got the Ghostly Ingredient and the Ghostly Quill. I went to the backyard and waited for a mob to spawn so I could collect the seeds but nothing spawned. The phantoms spawned but that was it. I waited for a boss to spawn and i walked around the place but he didn't spawn. So I searched this to see if i was in the right spot and I was. Is this just affecting my computer or am I in the wrong place? Please let me know by the way my user for this is not the same as mine in Wynncraft.

**Comment by Imaxe** [comment]
Did you try changing server? It should be the correct location

**Comment by bjw54321** [comment]
Yes I tried changing servers and I re-logged but the boss still won't spawn.

**Comment by Imaxe** [comment]
I can take a look at the spawn region soon! I completed that quest and found the mob quite easily

**Comment by Moe-Ronickah** [comment]
@bjw54321 , have you gotten on with the quest, or are you still having trouble?

**Comment by bjw54321** [comment]
I figured it out. Thanks for the help guys!
