### ISSUE TITLE
Didn't get xp on memory paranoia

### ISSUE THREAD

**Issue by benjaminqp479** [Wynncraft/Issues#6264]
After I completed the memory paranoia quest, I was still at level 67 with no progress. It said it gave me 375,000 xp, but I didn't get any.
<img width="1045" alt="screen shot 2016-09-26 at 12 37 33 pm" src="https://cloud.githubusercontent.com/assets/22455074/18845415/4e8171ca-83e7-11e6-8203-8419ee52f325.png">
<img width="1129" alt="screen shot 2016-09-26 at 12 38 08 pm" src="https://cloud.githubusercontent.com/assets/22455074/18845420/51339a10-83e7-11e6-86c2-94b0fbd7c2ac.png">

**Comment by Celsonic** [comment]
Your in game name please?

**Comment by benjaminqp479** [comment]
benjaminqp479

**Comment by thecoolkogut4** [comment]
If you are in a guild, your /guild xp could of been set to 100 resulting in giving all of the XP from the quest to the guild.
