### ISSUE TITLE
Quest: Unable to proceed, a confused farmer

### ISSUE THREAD

**Issue by LunarProximity** [Wynncraft/Issues#6266]
My username is LunarProximity. Basically, I was doing the ' A confused farmer ' quest, but I stumbled onto a stub. I did not use the cow passage, but instead walked by land back to the farmer to tell him Drale wasn't a cow. I completed it without using the 2 cow passage papers, but it did not give me the rewards nor completion, although it did say " Quest book updated " when I finished talking to the farmer. Afterwards, I went back to Drale at the Deltas Suburbs and used the cow passage from there on, but that did not end in completion.

**Comment by LunarProximity** [comment]
I fixed it. All I had to do was relog.

**Comment by TeenageCat** [comment]
I read the title as Unable to proceed, sincerely a confused farmer.
