### ISSUE TITLE
House of Twain, Eyes of the beast 

### ISSUE THREAD

**Issue by Veneni** [Wynncraft/Issues#6270]
Hello, I'm Veneni and i often play on Wynncraft as you guys might know. So i'm level 49 and i started the quest called ''house of twain''. Everything was going quite well untill i got to the part where i had to drop emeralds or objects in the ''beast'' his eyes. So i did, but it appears only one side of the eyes trigger and it's the right side. So i'm asking you dear Wynncraft Staff to solve this problem so i can continue on my journey in Wynncraft.
Thanks for reading,
Have a nice day,
Veneni / Remy

**Comment by Imaxe** [comment]
Im a bit confused. But did you drop an emerald in the wither skull carpet's both eyes? Did the fireplace open up? 
If not, try switching servers and see if that works

**Comment by Trixter313** [comment]
Did @Imaxe's suggestion fix your issue?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
