### ISSUE TITLE
A problem with the Gert Camp

### ISSUE THREAD

**Issue by RedwoodWynn** [Wynncraft/Issues#6272]
So me and a friend were doing the Gert part II quest. Nothing too special. He decides to fool around by taking off his helmet. We both knew that when you take off the helmet, it kicks you out of the gert camp right out by the entrance..... Or at least..... So we thought...... I see him disappear in thin air. Then I get a weird message. He exclaims WTF so I start to wonder whats going on. So I message him and he tells me to take off my helmet. So I do and.... yeah.

![screen shot 2016-09-27 at 5 30 34 pm](https://cloud.githubusercontent.com/assets/22484056/18892909/87d7a8e8-84d9-11e6-90ff-098a0be6b6e5.png)

We teleport to the tutorial. So just be warned.... Don't take off your gert helmet o.o

**Comment by shinyeldrago** [comment]
I did the same thing before and it put me back to the tutorial if i toke off my helmet   so yea...

Do not  take off helmets kids.... and do not do Gerts

**Comment by Moe-Ronickah** [comment]
Sorry, ya' all, but this isn't an issue.  If you invade the Gert's camp, and take off that MASK, they will see who you are and send you packing.
