### ISSUE TITLE
getting kicked

### ISSUE THREAD

**Issue by shinyeldrago** [Wynncraft/Issues#6273]
Hi I have been having a problem with Wynncraft lately. about the hub sometimes when i log into to
the server i glitch out and i get kicked for flying? i am not flying But when i glitch out it does it constantly.
It says Flying not Enabled on this server?  and my minecraft is stuck in a loop  that is constantly logging in to Wynncraft and i have to wait like 5min for it to work. 

Anyone els have this problem?

**Comment by Imaxe** [comment]
I have this problem when my internet connection isnt the best.

**Comment by LordHelmchen98** [comment]
Yeah I have that as well when I am laggin. Sometimes I even get this multiple times when I'm logging in to a lobby after getting kicked from a server.

**Comment by shinyeldrago** [comment]
ok

**Comment by Moe-Ronickah** [comment]
Not a Wynncraft issue, but an MC issue.
