### ISSUE TITLE
Stuck in Lost Sanctuary

### ISSUE THREAD

**Issue by Turmfalke2** [Wynncraft/Issues#6275]
hi,
I walked through some invisible teleporter thingy and ended up in a room with a 'Scared Creeper'. I killed that creeper and it dropped a tnt, which having not better use for it I dropped in the hopper. This spawned a light tnt, but up on it's explosion nothing happened. The wall is still completely unharmed. I farmed that creeper a bit and after dropping ~10 more tnts into the hopper it placed an unlit tnt next to it.

I am still stuck. Please work on your quest/dungeon design, it feels like it purely consists of stumbling around until you hit the right teleport trigger and apparently here it is missing.

**Comment by Imaxe** [comment]
First of all, the dungeon/quest designs are really good. You probably skipped some dialogue or just didnt pay attention. 
And to solve your problem, try changing server.

**Comment by Amariithynar** [comment]
Usually they're designed well, agreed, but sometimes something bugs. I've had that wall bug too, same with the boss to the Sand-Swept Dungeon, jumping out of the arena and requiring a mage to be able to hit him through the floor. While the server swap usually fixes things, sometimes you only have the choice to /kill yourself, much like when you randomly teleport into an upside down half-slab and can't move or use a TP scroll.

**Comment by Moe-Ronickah** [comment]
Chill, everyone.  Sometimes the triggers get buggy on some servers, and work fine on others.  That usually places it squarely on being an MC mechanic issue, but not always.  Anyway, we are all here to help make Wynncraft the best experience possible.  We are all on the same team.

**Comment by Amariithynar** [comment]
Yup, that we are. However, Imaxe trying to say that the problem is PEBCAK only was something that needed to be refuted. It's not an issue of Wynncraft being poorly coded or any such thing- they're issues that occur primarily because of it being built upon Minecraft, which has its own host of bugs, especially around non-standard movement and script running, especially in large scale multiplayer server situations.

**Comment by Moe-Ronickah** [comment]
@Turmfalke2 , are you still stuck in there?  We have no other reports of this that I am aware of, so, I'm really curious.  If you got out, how did you fix your situation?

**Comment by Turmfalke2** [comment]
No, a week later I played again and everything worked, except that the boss is ridiculous tanky and killed me after a 20 minute fight or so. I don't feel like going through all the you need to collect x and throw in a hopper chain again, I think wynncraft might not be for me. I am better off playing mmorpgs build on a proper engine.
