### ISSUE TITLE
perte de stuff

### ISSUE THREAD

**Issue by francaisfou31** [Wynncraft/Issues#6277]
J'ai un ami, Xani007, qui a perdu son stuff, il etait entérrée dans la terre, ne pouvais plus bouger, ni cassé bloc ( normal) et il c'est déco-reco qu'il a perdu tout sont stuff, est il possible de lui rendre? Sa classe est mage.

**Comment by thecoolkogut4** [comment]
Désolé, mais Wynncraft a une politique stricte de remboursement, votre ami ne serez pas avoir l'une de ses articles de retour du personnel.

**Comment by Imaxe** [comment]
Could someone translate this?

**Comment by thecoolkogut4** [comment]
translate.google.ca was it that hard?

**Comment by francaisfou31** [comment]
le problème est réglé, apparemment lil a récup tout son stuff.
