### ISSUE TITLE
Party XP not working properly

### ISSUE THREAD

**Issue by Amariithynar** [Wynncraft/Issues#6279]
Since I've started playing, I've been playing with someone (who introduced me to the server in the first place), and I noticed the only time we actually share exp is the same as when I do with non-partied people- that is, when we both hit a mob at least once before it dies. If either of us one-shot something, the other doesn't get any xp. I noticed it when we first started playing, but just assumed it worked like that since it popped the name of the killer up above the enemy (or shared if we both hit it); however, when going through the Wiki recently, it indicates that partied members are supposed to always share XP.

**Comment by thecoolkogut4** [comment]
you don't get a notification when you get xp from a party. Party xp goes into your xp bar directly. it does not say shared when you/someone in the party kills the mob. It says shared when two people do X amount of damage to a mob.

**Comment by Amariithynar** [comment]
Not saying that it says that you see it; please actually read what I wrote. What I'm saying is that I have not been getting XP when she kills something, and she doesn't get it when I kill something, unless we both hit the mob, while in a party. This has caused our levels to vary by as much as 8 bars of XP at various times throughout the past 45 levels, completing all the same quests as well.

**Comment by Trixter313** [comment]
How are you sure that you aren't getting XP?

You might be misunderstanding the XP breakdown, party members get 10% of the XP from a kill, not 50/50 or even amounts.

**Comment by thecoolkogut4** [comment]
you only get xp from a party if your within 20 (I think it's 20) blocks of eachother. if your farther then that you would share xp. one of you might have a little more xp bonus then the other, one of you might be killing more mobs then the other

**Comment by Amariithynar** [comment]
Okay, that 20 block limit might actually be it. We were farming in Bob's Tomb during an XP bomb recently and sometimes we would actually get xp shared and it was obvious (such as when she dinged off my kill), but sometimes we weren't (I'd kill a handful of mobs and she'd tell me she got nothing and vice versa)- sometimes we were on opposite sides of the Tomb, sometimes we were closer together. 

And yes, I never expected shared XP to be 100% to everyone, or even a 50% split between teammates. However, the mechanics of partying are obscured to the point not even the wiki has anything about this; it really should be more visible, so that people know the specifics of how it works.

**Comment by Trixter313** [comment]
Ah, that would make sense since the tomb is a decently large area. If you'd like to post about adding more information about parties to the Wiki, there is a suggestions area on the forums: https://forums.wynncraft.com/forums/general-suggestions.69/

Thanks!
