### ISSUE TITLE
I coudn't enter warrior class

### ISSUE THREAD

**Issue by ZunBa** [Wynncraft/Issues#6280]
before reading this, I'm not good at english. I believe that you understand 

I login this server first time since last year, before garvel update.
I had 62lv warrior, but I couldn't login this warrior class, except the other classes
How can solve this problem.
Help me

video about this problem
https://youtu.be/q_ucLeYZgVY

**Comment by AuburnTigerFan55** [comment]
I'm having the same problem too except mine is with the mage class.

**Comment by Trixter313** [comment]
Duplicate of #5418

Unfortunately there's nothing that the player can do about it, it is up to the admins to fix. There is currently no estimated time for a fix.
