### ISSUE TITLE
Lost emeralds

### ISSUE THREAD

**Issue by alromaithi1993** [Wynncraft/Issues#6282]
i have lost a stack of emerald blocks and they are no where to be found. I right clicked the emerald merchant and changed my last couple of emeralds to complete the stack of emerald blocks, then when i opened my ender chest, i dragged the stack of emeralds outside the box, but the shouldn't be dropped i know that. however, when i opened my inventory i couldn't find the stack, i only have the 2 blocks of emerald that i had before

**Comment by Imaxe** [comment]
You could've dropped them somewhere else and just had so called "ghost items" or you could've suffered the disappearing items glitch. 
Its a weird glitch where items respawn directly after you've thrown em out.

**Comment by alromaithi1993** [comment]
i need a moderator to help me out

**Comment by Imaxe** [comment]
Nobody can help you with this problem, Wynncraft has a no refund policy. So you won't get it back. Sorry about that
