### ISSUE TITLE
WynnExcavation Site C - Volcanic Isles

### ISSUE THREAD

**Issue by iMaryy** [Wynncraft/Issues#6284]
So me and my boyfriend were doing quests yesterday (09/28/2016) and we started the quest WynnExcavation Site C, in this quest we need use a purple shard that we have. so basically we were doing the quests toguether and just me (iMary) completed the quest and now when i try to do the quest again its says i need the purple shard but the point is i already have this.

http://prntscr.com/cnv3wd 
http://prntscr.com/cnv42h

I Hope you can help me.
Thank You

iMary

**Comment by ColinRioux** [comment]
Try `/fixquests` and see if it gives you a new variation of the purple shard. If that doesn't work, please comment.

**Comment by Trixter313** [comment]
Did @ColinRioux's suggestion help?

**Comment by iMaryy** [comment]
Yes, they helped me

**Comment by Trixter313** [comment]
Great, glad to hear!
