### ISSUE TITLE
Bank Detlas / Account reseting

### ISSUE THREAD

**Issue by Pandaaaaz** [Wynncraft/Issues#6285]
Bonjour,

J'ai reset ma classe Archer car j'etais niveau 43 environ je voulais tout reprendre du début.
A mon arrivé a la banque j'ai tout mes anciens items ce qui est très embétant des items des quetes que je n'es pas encore fait ou autre. Merci de bien vouloir faire le nécessaire pour reset ma bank.
Mon profil : https://forums.wynncraft.com/members/pandaaaaz.74142/

Bonne soirée

**Comment by Imaxe** [comment]
Can someone translate?

**Comment by Pandaaaaz** [comment]
Hi' 
I try tout translate but i'm not english. 
So before I got an account level 40 and I reset it.
Now my account is level 15 but I got the old item in the detlas's bank. It's a problem. Can you reset my bank chest please ? 

Thanks

**Comment by Pandaaaaz** [comment]
Ok the bug its finish. i have clear my bank. Thans to the mod " Dodo " On teamspeak for the help.

Thanks
