### ISSUE TITLE
Old Animal Key Drop

### ISSUE THREAD

**Issue by damocleas** [Wynncraft/Issues#6286]
The sheep in front of Detlas still drop the old Animal key, this may apply to other mobs in the area but I haven't tested this.
![2016-09-29_17 14 37](https://cloud.githubusercontent.com/assets/21964105/18972868/b363e98c-864f-11e6-9cc0-360d88027927.png)

**Comment by LordHelmchen98** [comment]
You can get Skeleton Keys from mobs as well. There are several thread about it here.

**Comment by Imaxe** [comment]
I'll take a look at this later :)

**Comment by Imaxe** [comment]
This is now fixed
