### ISSUE TITLE
I do not have Breathing Helmet 2

### ISSUE THREAD

**Issue by xSuperJMCx** [Wynncraft/Issues#6288]
Hello!
I have just started the quest 'From the Mountains' and I do not have the breathing helmet. I need it to complete the quest, but it is not here. I tried /fixquests, but it said I was not missing any items. I checked my other class and bank and I do not have it. How do I fix this? 

Thanks, 
James

**Comment by Ejiroo** [comment]
Rush lvl with a new character and do the quest, come on dont are a hard quest :)

**Comment by Ejiroo** [comment]
And you get the breathing helmet in Underice quest ;)

**Comment by Samattack2000** [comment]
You can also buy the breathing helmet 2 at Nesaak in the armor shop (for 2 EB)
