### ISSUE TITLE
Bugging horses

### ISSUE THREAD

**Issue by MrRedCrack** [Wynncraft/Issues#6290]
Horses are buggy for me, when i ride the horse for a while, then dismount, i often get teleported to another place, where my horse is actually at. This problem made me very frustrated, eg. I ride my horse to almuj, then i dismount, i get teleported back to ternaves, where i started riding my horse. When i get teleported, i can see that my horse ran into a wall, but when im riding my horse i dodged every obstacles.
By the way, this bug killed me several times, which got me triggered, when i was riding my horse in the mesa area, suddenly I am getting attacked by nothing, when i dismounted, I found out I was surrounded by a bunch of zombies, but it was too late, i get killed by them instantly :/

In game name: DrCrack

**Comment by thecoolkogut4** [comment]
its best to play on MC version 1.8 (not 1.9/1.10). if your on 1.8 the horses will be 99.9% less buggy.

**Comment by Imaxe** [comment]
As thecool said, the horses don't sync correctly in 1.10. So use 1.8 to prevent the bug.
