### ISSUE TITLE
Thee maiden tower Erlard refusing to accept the "black veil"

### ISSUE THREAD

**Issue by randleog** [Wynncraft/Issues#6291]
https://www.youtube.com/watch?v=5S4r9OyftEE&feature=youtu.be

**Comment by Imaxe** [comment]
You arent supposed to give it to him, you are supposed to enter the tower

**Comment by randleog** [comment]
it doesnt let me in

**Comment by Trixter313** [comment]
It doesn't let you in even after putting on the veil?

**Comment by Dodo-Bird** [comment]
@randleog Wear the Black Veil then enter the tower. After entering the tower go up the ladder and kill the witch. Once you kill the witch, bring the drop to Sherk and the quest will end.

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
