### ISSUE TITLE
Water Powder (T1 only) wont stack.

### ISSUE THREAD

**Issue by Kra3tys** [Wynncraft/Issues#6292]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.
In the title.
They'll stack if they're from the same server.
Besides that though, when i switch and collect a new one, they wont.

**Comment by LordHelmchen98** [comment]
Well I dont know if you have tried that already but often it helps to throw them out of your inventory and pick them up again. Otherwise if its t1 only I think it should not be too hard to get more of them and upgrade them to t2.

**Comment by Moe-Ronickah** [comment]
There is currently a hidden data entry that we cannot see, that makes powders obtained from relics differ from powders obtained from drops.  No, they won't stack.  Yes, this is a duplicate.  Yes, the admins know about it.  No, I don't know when it will get fixed.
