### ISSUE TITLE
Lazarus Pit Quest

### ISSUE THREAD

**Issue by MysticalLion** [Wynncraft/Issues#6293]
I'm at the step where I've jumped down into the pit.  The quest book says inspect the house. I have checked up the wiki. All that happens when I talk to Sesad is that it keeps repeating the same dialogue..

**Comment by LordHelmchen98** [comment]
Your quest book hasnt updated. Its kind of annoying and hard to update it. You should try to enter the house from different angles.

**Comment by Trixter313** [comment]
Did @LordHelmchen98's suggestion resolve the issue?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
