### ISSUE TITLE
Aldorei's Secret Part I

### ISSUE THREAD

**Issue by xAdrii** [Wynncraft/Issues#6295]
i just finished the quest but the reward list looked kinda weird so i looked in my inventory and didnt got the emeralds that the quest said
![2016-10-01_01 47 52](https://cloud.githubusercontent.com/assets/22553260/19010050/bf5c6d3c-877a-11e6-8dd7-654538051783.png)
![2016-10-01_01 47 56](https://cloud.githubusercontent.com/assets/22553260/19010051/bf5f4264-877a-11e6-825f-cd774340a518.png)

**Comment by Imaxe** [comment]
You had 2 choices, and you chose the ones which gives you 0 emeralds. 
If you look at the quest rewards you can clearly see 
+0 Emeralds / 8192 Emeralds
