### ISSUE TITLE
Unbann Glitch

### ISSUE THREAD

**Issue by parsakarami03** [Wynncraft/Issues#6297]
Hello staff of wynncraft I'm here to report s bug on my ban recently I just got unbanned but when I try going into a world it says I am still banned could you please fix this bug if you want I can prove with an image
Thank you for your help

**Comment by ColinRioux** [comment]
Have you confirmed that you are **immediately** unbanned? More often than not, you'll have to wait a certain time frame (from 24hours to a week) if your appeal has been accepted. If that time has passed since your appeal has been accepted and you're still retaining this issue, please let us know.

**Comment by parsakarami03** [comment]
@colinrioux I have waited 2 days for my ban as that was the wait time I got but the problem is I can go into hub but I can't access of the servers/worlds I do have a image to show what I mean 


Thank you for your help

**Comment by Trixter313** [comment]
Is there an error message that appears when you try to enter a world?

**Comment by Moe-Ronickah** [comment]
@parsakarami03 , what is your minecraft user name?

**Comment by parsakarami03** [comment]
@Moe-Ronickah it's Master_Playsmc

**Comment by parsakarami03** [comment]
@Trixter313 it says you have been banned for fly hacks when I it's says I'm unbanned in Fourms and I can go into hub aswell 2 days have also finished

**Comment by parsakarami03** [comment]
@Moe-Ronickah what should I do?

**Comment by Moe-Ronickah** [comment]
One second . . . . this should have been sent to me in a pm, not here, it would have been much faster.
Unbanned on the 28th with a 48 hour hold.
System should have unbanned on the 30th.
Well, I'm going to have to wait until panel is back up and running to see what happened.

**Comment by Moe-Ronickah** [comment]
I banned you for fly hacking.  You appealed, you got unbanned.  I banned you AGAIN for fly hacking.  You were in the lobby, doing I don't know what, because I'm not the person who banned you, there.  You have not appealed either your second ban for fly hacking, nor your lobby ban.  This issue rests on your actions.  You may appeal, again, if you want to rejoin the game.

![](http://i.imgur.com/dyA8iwu.png)
