### ISSUE TITLE
Elemental Exercise Quest Glitch

### ISSUE THREAD

**Issue by MrBeanyGuy** [Wynncraft/Issues#6298]
I started the quest Elemental Exercise and it teleported me to the area of the collapsed cave. However enemies are not dropping the Scorched Roots that i require, and the only way for me to leave is to use a teleport scroll. Any suggestions?
FYI - I'm stuck right now because i don't want to use and then buy another scroll.

**Comment by Imaxe** [comment]
They arent supposed to drop the roots, just progress through the cave and you'll see.
