### ISSUE TITLE
TaprootQuest Bug [she wont accept flowers]

### ISSUE THREAD

**Issue by PhenomalBear** [Wynncraft/Issues#6299]
Taproot Quest is bugged out, I got the 3 flowers for the quest, but Tiek isn't accepting the flowers I have.

**Comment by Imaxe** [comment]
Please more detail... 
And I guess you have to wrong flowers, did you already give her flowers? 
Please pay attention to the quest book and dialogue

**Comment by PhenomalBear** [comment]
I did give her the right flowers, I looked at the YT video

**Comment by PhenomalBear** [comment]
and even searched up in wiki for flower coordinates

**Comment by PhenomalBear** [comment]
![2016-10-01_12 43 25](https://cloud.githubusercontent.com/assets/22555924/19015549/c22a4bba-87d4-11e6-9730-6e63dd3ba4bb.png)
![2016-10-01_12 43 26](https://cloud.githubusercontent.com/assets/22555924/19015551/c22e828e-87d4-11e6-9323-ef839b81d99f.png)
![2016-10-01_12 43 23](https://cloud.githubusercontent.com/assets/22555924/19015550/c22b4e7a-87d4-11e6-8113-33b8e2724773.png)

**Comment by PhenomalBear** [comment]
![2016-10-01_12 44 40](https://cloud.githubusercontent.com/assets/22555924/19015556/e5b2f29e-87d4-11e6-9264-7bdb1430313b.png)

**Comment by PhenomalBear** [comment]
I already have them

**Comment by EpicZephos** [comment]
odd, try dropping and picking it back up

**Comment by PhenomalBear** [comment]
did it, won't fix it

**Comment by Moe-Ronickah** [comment]
The flowers that you have were obtained from the coordinates listed in the Wiki, and absolutely not from Tiek's garden?  [https://wiki.wynncraft.com/index.php?title=Taproot_(Quest)](https://wiki.wynncraft.com/index.php?title=Taproot_(Quest))

**Comment by PhenomalBear** [comment]
they are not from tiek's garden
tiek's garden are wilted ones, in my inventory, it does not say "wilted" you can go and check it out yourself

**Comment by CrystalGarnet** [comment]
Bud, you must give her the garden ones first THEN the ones from the outside places. Same thing happened and i had the facepalm of the years when I saw the 3 on the garden.

**Comment by Moe-Ronickah** [comment]
<facepalm> @CrystalGarnet is probably correct.  If her Royal Tiek doesn't turn you down first, you can't give her the ones that she really wants.  Did giving her the wilted ones let you complete the quest?

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
