### ISSUE TITLE
The Mercenary Quest Glitch "you have no permission for this area"

### ISSUE THREAD

**Issue by PeterL2001** [Wynncraft/Issues#6300]
When doing the "The Mercenary" Quest after starting it you will be unable to interact with lootchests buttons and more. This already happened to 2 of my accounts, causing them to be unable to do things like dungeons too. According to this you may guess that this is very bad for me and it´d be appreciated to be fixed.

Thanks for your Support ~PeterL2001

**Comment by Imaxe** [comment]
What exactly is your problem? Not being able to interact with stuff in the world after starting a quest? 
Thats impossible. 
I think you press buttons and stuff with your weapon, which you cant do, press them with another item. (like your soul points) The quest has nothing to do with this

**Comment by PeterL2001** [comment]
Ok that war the Problem thanks for telling :D its just like it happened to 2 of my characters after starting the quest :P i think just random then
