### ISSUE TITLE
Beneath the depths problem

### ISSUE THREAD

**Issue by riptidecraft** [Wynncraft/Issues#6302]
In the level 60 quest Beneath the Depths I am in the maze where you go to find the treasure map Javier wants to continue the quest but as it says on the quest guide on the wiki that the maps should be falling from the ceiling however I see no pieces of paper and the dead pirate that spawns in there doesn't drop anything. Is there anything I'm missing here or is this a bug? And as a side note I keep hearing a noise and getting moved around when I hear it

**Comment by Umaruun** [comment]
The puzzle continues. Throw an Emerald Block on the carpet on the grave at the end of the room. A tunnel will open on the other side and you continue the maze. At the end of that second maze the Faded Map is a small lv 0 mob laying on the ground.

**Comment by riptidecraft** [comment]
Oh an emerald block I see I threw in a regular emerald to see if anything happened thank you!
