### ISSUE TITLE
Missing Horse

### ISSUE THREAD

**Issue by thequest99** [Wynncraft/Issues#6303]
I haven't played for a while and when I came back some of my gear was gone but most of all my horse isn't there. I tried to look for it in all of my characters inventory and I also tried to buy another horse but the guy acted as I already have (because I did back when I played) and that I still have it but I don't have it. If you need my user name it is TheQuest99

**Comment by thecoolkogut4** [comment]
the server has a strict no refund policy. There are 2 ways to get a horse. #1 Complete the quest stable story then use the horse merchant. #2 buy a horse from a player.

**Comment by thequest99** [comment]
I did #1 but now I cant get my horse is gone and I cant to that quest again.

**Comment by thecoolkogut4** [comment]
once you do the quest, it gives you access to the horse merchant. since you completed the quest you can go back to where you started/finished it (ternaves) and buy another horse

**Comment by Moe-Ronickah** [comment]
I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency.  You might be able to find someone to buy your lost item from, or, possibly, someone who will even give you one, for free, depending on the value of your item.  Ask around in Detlas and check the Trade Market on the forums.  Good luck.

**Comment by thequest99** [comment]
The way I "lost" the horse was I logged in after a long time and it wasn't in my inventory and the spot where I bought it last time it wont let me buy another.

**Comment by Trixter313** [comment]
The horse merchant in Ternaves won't sell you a horse?

**Comment by thequest99** [comment]
I dont know the name of the place but the only place where I knew I could get a horse from last time was the small town east south east just outside the desert.

**Comment by thecoolkogut4** [comment]
from deltas (Center town) towards the desert, follow the path then go a little to the right and that's the town where you buy horses from. if you hit the wall for almuj (desert) you've gone too far. I can get your cords if you still need it later.

**Comment by thequest99** [comment]
If you're talking about ternaves then that's the place where I'm at and it wont let me buy a horse because when I talk to the horse guy he asks how my horse is doing or something, I don't really remember. and it was a black horse that despawned out of my inventory, along with some weapons and armor. I think that might have happened  when they re did the stats for stuff and made it so you have to identify the item before using it.

**Comment by Trixter313** [comment]
Are you sure you're talking to the horse merchant and not the quest NPC? The person you buy the horse from should be in a building near the quest NPC.

**Comment by thecoolkogut4** [comment]
as nick said, you talk to the horse merchant inside of a barn/shack. when you click it a GUI should open up and when you click the saddle you buy a horse (if you have the $for it)

**Comment by thequest99** [comment]
Thanks but is there a way I can get compensated for my horse despawning out of my inventory? Its REALLY annoying that after whatever update it is just gone.

**Comment by Trixter313** [comment]
As stated above, Wynncraft has a strict no refunds policy for ingame items not achieved with real money. There are a number of things that could have happened, even just accidentally dropping it is a possibility.

You mentioned some gear was missing too, that makes me wonder if someone else might have access to your account and could have done it. Horses weren't affected by the update that unidentified all items, they stayed untouched. If you think it's possible that someone else did it I'd suggest changing the Minecraft password and possibly the associated email account's password as well.

**Comment by thequest99** [comment]
Nobody else has my minecraft login
