### ISSUE TITLE
Something weird is pushing me around

### ISSUE THREAD

**Issue by IIFennecII** [Wynncraft/Issues#6304]
I did try to search for this but did not find anything. So the thing is I literally get pushed around by some mystic invisible force. Trying to grind? no get pushed down into the horde. Trying to escape? no get flung back into the ones in pursuit. trying to get somewhere dangerous or just explore? feck nah get pushed somewhere. I have no idea what is causing this problem. At first I thought it was the wither and unit collision but I tried changing versions of minecraft but the problem just got more severe.

**Comment by thecoolkogut4** [comment]
if you go into MC Version 1.8, your pushing problems will be resolved.

**Comment by Trixter313** [comment]
Did @thecoolkogut4's suggestion resolve the issue? We recommend 1.8.9 for Wynncraft.

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
