### ISSUE TITLE
Wynncraft - Crashing

### ISSUE THREAD

**Issue by ICHIGOunserscore** [Wynncraft/Issues#6307]
I am crashing from these stupid bats In the hive on the fire floor this is the error im getting can anyone help?

http://imgur.com/fVG6SJi

**Comment by ICHIGOunserscore** [comment]
I think it means: minecraft thinks the bat doesn't have items but they do so it crashes me can anyone help me fix this I think however made this mob might need to fix it

**Comment by Trixter313** [comment]
What version of Minecraft are you using to play Wynncraft? We recommend using 1.8.9 as using other versions can cause issues in itself.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
