### ISSUE TITLE
I can't leave my guild

### ISSUE THREAD

**Issue by djgunner44** [Wynncraft/Issues#6308]
It saying I left the guild but shows i'm still in it. I can take a screenshot and show you if anyone wants to see.

**Comment by LordHelmchen98** [comment]
I guess you have changed your name while being in that guild. Most players who change their name while being in a guild are stuck after the change. You have to wait until guilds get fixed which will hopefully happen with the next update.

**Comment by Trixter313** [comment]
Duplicate of #3665
