### ISSUE TITLE
guild's member bugs

### ISSUE THREAD

**Issue by GuerrierHache** [Wynncraft/Issues#6311]
Hello.In my guild, Dragon Bleu , we have a 3 times the same guild members and 2 owners,the same owner.
https://wynncraft.com/stats/guild/Dragon%20Bleu

**Comment by LordHelmchen98** [comment]
They probably changed their names while in the guild. Although I dont know why your guild owner would want to leave thats the only possibility I heard of. Most players who change the name while in a guild get stuck. Hopefully this will be fixed in the next update.

**Comment by Trixter313** [comment]
Weird guild name changes are all being directed to issue #3665
