### ISSUE TITLE
Raw Spell dmg is glitched

### ISSUE THREAD

**Issue by Realityfloat** [Wynncraft/Issues#6313]
so... i think its a bug, idk ._.
i have exactly +693 raw spell dmg and 9% spell dmg and when i use multihit (my weapon is Nirvana) it doesnt use the spell dmg

**Comment by Moe-Ronickah** [comment]
How do you know that it doesn't?

**Comment by Realityfloat** [comment]
[https://youtu.be/YIBUQJ0fOLc](url)
here, i recorded this video so you can see that my spells are only dealing -water- dmg
