### ISSUE TITLE
new temple of legends problem

### ISSUE THREAD

**Issue by glitchesss** [Wynncraft/Issues#6314]
when I try to get the maro peek jewel(what ever it called) I cant get I tried killing the jewel miner

**Comment by Trixter313** [comment]
Does this Wiki page help you find it? https://wiki.wynncraft.com/index.php?title=Maro%27s_Eye_Jewel

**Comment by ColinRioux** [comment]
Like said explicitly on the wiki, you don't kill the jewel miner to get it. Closing now.
