### ISSUE TITLE
Game crashed and our gear disappeared

### ISSUE THREAD

**Issue by zickietestar** [Wynncraft/Issues#6315]
Wynncraft Help,

Everyone once in a while a server goes down without warning unlike the server reload that is told to us at least 10 minutes in advance. My friend Pure_Fades and i were showing each other our Legendary gear when the server stopped unexplainably. I lost "knights leggings" and "Millennium" while he lost "Adamantite" and "Crystal". Is there a way to get our items back? We both worked really hard to get our gear.

-Zickietestar
-Pure_Fates

**Comment by LordHelmchen98** [comment]
Im sorry to say this, but Wynncraft has a strict no-refund policy. You wont get back any items. :/
