### ISSUE TITLE
Gemstone Dust

### ISSUE THREAD

**Issue by qscfth2001** [Wynncraft/Issues#6316]
I was about to start the quest Aldorei's Secret Part I and it says i need a Gemstone Dust to start the quest. I could not find it my bank so i searched on the wynn wiki about it, it says you get the dust from completing Lost in the Jungle quest which i made sure i did, and yes I have. Before you guys tell me to look properly I did, I looked on every class and the bank and I do not have it.
Game username: qscfth2001
![2016-10-02_19 43 36](https://cloud.githubusercontent.com/assets/21101491/19022848/119b14a4-88d9-11e6-8fc3-373bc31dda28.png)

**Comment by Realityfloat** [comment]
try /fixquests

**Comment by Trixter313** [comment]
Did @Realityfloat's suggestion resolve the issue?

**Comment by qscfth2001** [comment]
yes it has thanks guys

**Comment by Trixter313** [comment]
Glad to hear!
