### ISSUE TITLE
Lost Soles Quest Really bad glitch

### ISSUE THREAD

**Issue by CallMeSpoonZ** [Wynncraft/Issues#6322]
Ok so i started the lost soles quest with a full inv and it said to give him the boots i had on so i gave him the boots picked my stuff back up and then that was that he talked and said oh ye take the boots back and find out the 4 digit code or whatever but my inventory was full so i basically lost the boots forever because it said inventory is full. it didnt drop them on the ground and i dropped some stuff for space and clicked on him again and said can you bring me these boots AGAIN the only way to get the boots is from a quest ive ALREADY completed So what the heck do i do!!! PLEASE HELP MEEE

**Comment by Trixter313** [comment]
Does using the command /fixquests return the boots?

**Comment by CallMeSpoonZ** [comment]
ill try

**Comment by CallMeSpoonZ** [comment]
AH! thankyou although i do need to ID them again

**Comment by Trixter313** [comment]
Glad to hear you got the boots back!
