### ISSUE TITLE
raw spell damage

### ISSUE THREAD

**Issue by Realityfloat** [Wynncraft/Issues#6323]
.i have +693 raw spell dmg and 9% spell dmg and when i use any spell (my weapon is Nirvana) it doesnt works
[https://youtu.be/YIBUQJ0fOLc](url)
here, i recorded this video so you can see that my spells are only dealing -water- dmg

**Comment by Moe-Ronickah** [comment]
You're link is broken.

**Comment by Realityfloat** [comment]
https://www.youtube.com/watch?v=YIBUQJ0fOLc

**Comment by Moe-Ronickah** [comment]
Thank you for the video. I've been a little under the weather, so I apologize for this late response.  I've forwarded your report to admins so that they can look into this.

**Comment by Moe-Ronickah** [comment]
RESOLVED
