### ISSUE TITLE
Hole in Underworld Crypt

### ISSUE THREAD

**Issue by Mantix2** [Wynncraft/Issues#6325]
In Underworld Crypt dungeon there's a hole at the first mob encounter and when you fall in it you are stuck if your not a Warrior.

Please correct this because i fell in it and im stuck.

**Comment by Trixter313** [comment]
Could you post a screenshot of the hole?

Also, you can use the command /kill to get out if you're still stuck.

**Comment by Imaxe** [comment]
Please show a screenshot, there isnt anything I can do if I dont know the location.

**Comment by ColinRioux** [comment]
Fixed!
