### ISSUE TITLE
/fixquests issue

### ISSUE THREAD

**Issue by MusicScore** [Wynncraft/Issues#6326]
This is more or less a continuation of my last issue, but the circumstances have changed.

I've completed the WynnExcavation Site D quest, and both Aldorei's Secret quests. However, because I had used /fixquests immediately after Aldorei's Secret Part I quest, I got a Receipt as well as a Medallion. Fast forward to me completing Part II, and I completed the quest using the token. I cannot get rid of the Receipt.

Same issue with the WynnExcavation Site D quest. I've completed it, yet using /fixquests still yields +2 Purple Crystals, so I still have 2 Yellow Crystals and (now) 14 Purple Crystals.

I would like to have these items removed, and possibly a small fix for the /fixquests issue regarding it still giving me Purple Crystals?

**Comment by Trixter313** [comment]
To get rid of items that you are **sure** you no longer need you can drop them in your daily rewards and they should go away.

As for the issue itself, it has been reported before and is known by staff but as to when it might be fixed we don't have an answer. Staff is most likely working on more important features at the moment.
