### ISSUE TITLE
Mage Island Bug

### ISSUE THREAD

**Issue by CrystalGarnet** [Wynncraft/Issues#6327]
Hello. There is a problem.
On the Temple of the Legends quest, at one point you are given the task to go to Mage Island and get some  Sky Flux to progress.
Here's the deal:
Everytime I'm near the area, whenever I click both right or left click, a HUUUUGE lagspike freezes the screen for a couple seconds then keeps going like I didn't even click. I know its not my Laptop since when I died and respawned at Breeminglar, I did the same thing but no lag happened.

Is something going on with Mage Island? or is something else happening? Please try and answer this.

Thanks sincerily,
~_iiCrystalGarnet (name changed from Crystal_Garnet)

**Comment by Trixter313** [comment]
Hmm, I'm not sure why it would only happen in a certain area. We recommend using 1.8.9 for Wynncraft, is that the version you're using right now? Also how is your FPS in the area while it's not frozen, lower than what it normally is for you in other places in Wynncraft or about the same?

**Comment by XavierEXE** [comment]
I honestly don't know why this area would lag so much, usually we only hear issues like this about areas like Nivla Woods, the Dark Forest, or anywhere with a crap ton of leaves. Maybe Optifine would help if you don't have it already?

**Comment by CrystalGarnet** [comment]
Thanks. I got someone to help me through the quest and managed to get the
flux for me. Also, I literally only play Minecraft 1.8.9 and use 1.8.9
Optifine. Thanks for the help, I did fix some of the lag, but I hopefully
don't have to go back. Again, thanks so much

-_iiCrystalGarnet

2016-10-14 13:34 GMT-04:00 XavierEXE <notifications@github.com>:
