### ISSUE TITLE
Bob's Seal of Approval

### ISSUE THREAD

**Issue by Kavenoke** [Wynncraft/Issues#6328]
So me and my 2 other friends are killing Bob's Reincarnation and after killing it for the first time, 2 seal of approval's drop, 1 for each of my friends but not me. We then proceeded to kill it another 4 times, 3 of the times the same result as the first occurred, them getting 1 each and me getting none, and the other time nothing dropped for anyone, except for the armour and weapon and Bob's Reincarnation. Admins please do something because im not killing him again!!!!!
IGN's:
friends - Cloudly
            - The007Vaderz
Myself - Kavenoke

**Comment by Trixter313** [comment]
Do you have low damage or are you not attacking that often? It drops an item for everyone who did decent enough damage, do if you didn't do enough damage you won't get a drop.

**Comment by Kavenoke** [comment]
I am constantly attacking and for 2 of the times that we killed Bob, i did the damage while they tanked and kept aggro

**Comment by thecoolkogut4** [comment]
if you kill him again, tell your friends not to pick up the paper, wait 30 seconds then you should be able to pick it up

**Comment by Kavenoke** [comment]
Um as much as i would just love to get the paper, I've already killed him 5
times! is there anyway i can just get given the paper?

**Comment by Moe-Ronickah** [comment]
@Kavenoke , NO.  There is no way for you to get any locked quest item without actually obtaining it on your own.  That is an anti-cheat decision.  As thecoolkogut4 said, tell your "friends" to stay away from the drops until AFTER you get Bob's Seal of Approval.  Oh, and tell them that it was nice of them to get extra's for their other classes, at your expense.
