### ISSUE TITLE
Beneath The Depths map not dropping

### ISSUE THREAD

**Issue by NovaFG** [Wynncraft/Issues#6329]
Hi, i'm trying to complete the Beneath The Depths quest and when in the Skull Cave, in the main room, I threw in the required emeralds for the dialogue to appear but no map, I continued thinking It may be later on but nothing was given to me, Please help me as I don't want to keep sending my Emeralds into that monstrous hopper ;-;.

**Comment by Trixter313** [comment]
This was reported in issue https://github.com/Wynncraft/Issues/issues/6302 and it appears that you have to throw a block in the hopper. Let us know if this solves your issue, thanks!

**Comment by kkbirdy** [comment]
Throwing in the EB doesn't give you the map, a door opens up in the opposite side of the room to the altar and you have to go through a maze to get the map.

**Comment by Moe-Ronickah** [comment]
@NovaFG , I hope that kkbirdy's explanation helped you.
