### ISSUE TITLE
Tower of Ascension xp Bug

### ISSUE THREAD

**Issue by Leosuper99** [Wynncraft/Issues#6330]
Hey, i completed the Tower of Ascension and got only 1 lvl,.
My question is : When will the bug fixxed,and can I get the xp again?

**Comment by Leosuper99** [comment]
https://gyazo.com/f7e643fbe3a44283df1106b7f162eb7e

**Comment by TeenageCat** [comment]
What's the problem?

**Comment by Leosuper99** [comment]
I got not the right experience from the tower of ascension

**Comment by Moe-Ronickah** [comment]
Duplicate of #6312
