### ISSUE TITLE
Sesad Glitch (Lazarus Pit Quest)

### ISSUE THREAD

**Issue by NumeroPhobia** [Wynncraft/Issues#6332]
So apparently, in the 9th/10th stage in the quest, Lazarus Pit, you're supposed to talk to Sesad and get the Water to return back to Burtur. That's not happening in my case.

So what's happening, for me, is that when I talk to Sesad, the only line that pops up is: "Oh no! The pit has arisen another one. Get back, foul demon!" Usually after that line, the [Quest Book Updated] line would pop up, but it doesn't for me, so now I'm stuck in an infinite loop of the same line whenever I talk to Sesad.

Is there a way to fix this? (And yes, I tried moving closer and farther...)

**Comment by Imaxe** [comment]
What does your quest book say?

**Comment by WynncraftRyc** [comment]
You have to go upstairs, or wander around the house first. If your Quest Book says "Talk to sesad" though, I don't know.

**Comment by Moe-Ronickah** [comment]
@NumeroPhobia , try following a walk-through, on youtube, and let us know if you are still stuck.

**Comment by Imaxe** [comment]
@NumeroPhobia You need to go up to the attic and look around until the quest book updates

**Comment by Moe-Ronickah** [comment]
@NumeroPhobia , were you able to complete the quest?

**Comment by NumeroPhobia** [comment]
I got it a whiel back, but wasn't online to give the status update.
