### ISSUE TITLE
Unban error

### ISSUE THREAD

**Issue by ArtofPixels1** [Wynncraft/Issues#6334]
Hi I'm doing this for a friend who Recently got unbanned from wynncraft after waiting 2 days so he log back in for 10 seconds and then he get banned again so I was still in hub trying to access his compass but it said he was banned later on he got kicked and banned again for the same reason when it clearly said he was unbanned on fourms and  so in shot he was able to log in again for 10 seconds before getting banned the next second his username is Master_PlaysMC

**Comment by Moe-Ronickah** [comment]
Your friend has already posted his issue, here.  Don't make duplicate posts, please.
