### ISSUE TITLE
Something is terribly wrong.

### ISSUE THREAD

**Issue by Lone-Scout** [Wynncraft/Issues#6335]
In the last few sessions, I have been experiencing increasing issues.To give a baseline, I am a level 53 mage. I have been playing for five days. I am wielding a "Sage" wand with 1x IV Air Powder. It started with the message, "You don't have permission for this area." whenever I right clicked. This prevented me from using my staff when interacting with the environment. The issue was limited to the staff, so I wasn't overtly concerned. However, recently, upon logging in, I have found that not only is that issue still present, but I cannot do a number of things. First, I cannot use either boats, horses, or teleport scrolls from my inventory. Second, I cannot use anything to deal damage. My melee attack will go as far as a mob, but instantly disappear. My teleport will transport me, but no damage is conferred. My meteor will only render if it will not impact any mobs. My ice snake will render until it would hit a mob, then stop. Please. HELP!

**Comment by Lone-Scout** [comment]
Relogging solved the damage issue, but not the "Permission" issue.

**Comment by Imaxe** [comment]
You get a permission error because the weapon is a block, it gives you an error when you right click a block. The wand still works, its just annoying with the chat spam
