### ISSUE TITLE
Guild 

### ISSUE THREAD

**Issue by Alphacrafting** [Wynncraft/Issues#6337]
I can't leave my guild, I keep in typing yes into the sign and after I will lose 3 soul points but I cant leave.

**Comment by Imaxe** [comment]
You probably changed your name. Didn't you? You can't leave a guild if you've changed the name. This will be fixed in the future.

**Comment by Alphacrafting** [comment]
If I change my name back to original will it work?

**Comment by Trixter313** [comment]
Duplicate of #3665 

You can try changing it back but I believe that that hasn't worked for people in the past.
