### ISSUE TITLE
My Bad Wolf disappeared :'( ...

### ISSUE THREAD

**Issue by kroen99** [Wynncraft/Issues#6339]
Hello, I was just about to film pics for my new shop that I just opened and after taking a pic of my first item for the shop - my bad wolf, I got disconnected and it disappeared. 
It's not my fault/my internet's fault or whatever, it was a bug that deleted one of my best items..
I have a picture of it right before it disappeared and some after it did:
before it disappeared:
http://prnt.sc/cqc1oe

and after:
http://prnt.sc/cqc1t1

http://prnt.sc/cqc1vc

I know some people try to fake those kind of stuff but please believe me I have those proofs plus my boots were diamond made, 2-3 years back before i quit. 
Please return me my boots they were really good and I'd like to have them back due to it wasn't my fault and you guys can do everything you can to check I don't have them/anyone I know or whatever, them being made of diamond should make it hard to fake right?. 
sorry if I'm quite annoying but I will just really like to have them back please.
forum name - kroen_99
in game name - koren_99

**Comment by LordHelmchen98** [comment]
Wynncraft has a strict norefund policy. You won't get back any items :/

**Comment by kroen99** [comment]
Please help !

**Comment by LordHelmchen98** [comment]
Dude as I told you, you won't get back any items. You will have to grind for the boots or buy them. You are not the only one by the way there are loads of people who lost items and didnt get back anything as well.

**Comment by Imaxe** [comment]
Norefund policy, sorry about that
