### ISSUE TITLE
WynnExcavation Site A glitch

### ISSUE THREAD

**Issue by saarq** [Wynncraft/Issues#6341]
So, I just get done in the tomb with the Pharaoh part when you exit, and it tells me to return to Vade, so, I go to him, and he tells me to go bring papers to the guy who translates the papers, which i have done, so i go to the guy and he tells me to go give Vade the papers, which again i have done, I have no idea what to do, please help.

**Comment by CorzaFTW** [comment]
This has also happened to me, but when I did /fix quests it gave me 2 items I don't need, now I have 2 more inventory slots filled with random junk. Please fix this.

(Ign- Educator)

**Comment by Moe-Ronickah** [comment]
Both of you are reporting duplicate issues.  If you do a search through the issues, you will find the answers that you are looking for.
