### ISSUE TITLE
Wynncraft craftmas chaos quest not working

### ISSUE THREAD

**Issue by PancakeKnight** [Wynncraft/Issues#6346]
I had just complete the craftmas chaos quest and after beating the boss and talking to old tom I went back to talk to Santa and when I click on him nothing happens so I cant complete the quest.

**Comment by Imaxe** [comment]
1. Check your quest book. 
2. Look at a walkthrough
3. Tada, solved!

**Comment by PancakeKnight** [comment]
Wow really I never tried that. Im not an idiot when I click on Santa he doesn't say anything

**Comment by Moe-Ronickah** [comment]
@PancakeKnight , some people don't try any of things, first.  By now, I'm sure that you've changed servers.  Did that fix the problem?

**Comment by PancakeKnight** [comment]
Ive tried changing servers and reloging. And the Santa npc still doesn't work

**Comment by Moe-Ronickah** [comment]
@AckroWynn , can you check to see if Santa is working?  Thanks.

**Comment by AckroWynn** [comment]
When you say nothing happens, do you mean that literally nothing appears in your chat? Or nothing, as in, the stage is not updated, and the quest simply doesn't finish?

**Comment by PancakeKnight** [comment]
It doenst give me any rewards and doesn't finish the quest

**Comment by AckroWynn** [comment]
I meant, does anything appear in chat?
Does the NPC talk, at all?

**Comment by PancakeKnight** [comment]
It doesnt say anything

**Comment by XavierEXE** [comment]
What does your quest book say to do?

**Comment by PancakeKnight** [comment]
Go back to the present and talk to Santa
