### ISSUE TITLE
Hollow Sirene quest problem...

### ISSUE THREAD

**Issue by GhostlyLeagues** [Wynncraft/Issues#6347]
Hello there.
I have just experienced a problem with the quest called Hollow Sirene.
So, i was just doing the quest and i was done with everything, and i just had to turn it in. I drop an item so i can get the rewards from the quest, but when i turned it in, i didn't get the 1 le i should've gotten. This was my inventory before i completed the quest. (I had the item in the free spot) https://gyazo.com/54d73a9e004db0fbcdf8d7d5f36f1d00 Yes i did have 1 le, 41 eb's and 57 emeralds with me.
My guess is that the quest's code says something like this, coded ofc:
"See if the player has 1 le. If the player doesn't have 1 le, give one to the player. If the player does have 1 le, do nothing." (just my thought on the problem...)
Please do fix this issue, and i hope nothing like this happens for anyone else in the future. Have an awesome day to everyone who sees this message!
-Ghostly

**Comment by LordHelmchen98** [comment]
Did you get 16 eb? If so you are just fine because the wiki (hope there was no change with the gameplay update) says you get 1024 emeralds which are 16 eb. 1le are 4096 emeralds.

**Comment by GhostlyLeagues** [comment]
I didn't get anything out of the quest. except xp. Plus, it said in chat + 4096 Emeralds, or something like that.

**Comment by Imaxe** [comment]
Nope, I dont see anything wrong with this. 
It gives you 16 EB. 
Which it probably did too, you just didnt pay attention to the EB amount you had before the quest :)

**Comment by Moe-Ronickah** [comment]
@GhostlyLeagues , I'm sorry, but without both before and after pics, we can't even begin to troubleshoot this.  A couple of general suggestions, though: before completing any quest, have multiple item slots open; try to not have any emeralds, in any denomination, on your character.  Remember, the game is coded on top of MC, which has it's own bugs.
