### ISSUE TITLE
Can not identify bobs wand

### ISSUE THREAD

**Issue by unusualphysics** [Wynncraft/Issues#6348]
![2016-10-07_15 12 08](https://cloud.githubusercontent.com/assets/22690207/19205572/8c3a650a-8ca0-11e6-838f-65ca2352a383.png) 
![2016-10-07_15 14 10](https://cloud.githubusercontent.com/assets/22690207/19205601/bd4a8bf2-8ca0-11e6-9466-00ef201583a9.png)

**Comment by Imaxe** [comment]
This is a known bug, and its being worked on. It's not that simple to solve apparently

**Comment by unusualphysics** [comment]
Thanks, Imaxe 👍

**Comment by Moe-Ronickah** [comment]
How old is that wand?  Did you just obtain it or is it from pre-Gavel?

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/6171
