### ISSUE TITLE
Cannot leave guild nor join a new one.

### ISSUE THREAD

**Issue by Aurma** [Wynncraft/Issues#6349]
I've recently tried leaving a guild, but it doesn't seem to work because of my name change,
i do not know why, i am a VIP+ , and the guild chat gets spammed allot as well,
here's proof.
![2016-10-07_23 57 10](https://cloud.githubusercontent.com/assets/22699136/19210479/cf332f10-8ce9-11e6-8137-f758cbd40498.png)

**Comment by LordHelmchen98** [comment]
You will have to deal with it. There is no way to leave a guild once you are stuck because of a name change. You will have to wait until the guild get fixed.

**Comment by thecoolkogut4** [comment]
if you were vip with a creeper pet before the vip+ update you got vip+ automatically when it came out.  you are stuck in the guild for now. nothing you can do

**Comment by Moe-Ronickah** [comment]
If you had actually done a search on "can't leave guild", you would have found 45 issues.  If you had searched for "guild", you would have found 392 issues.  I'll bet you really didn't do a search.  In any event, this is a duplicate.
