### ISSUE TITLE
Texture Pack Issue

### ISSUE THREAD

**Issue by FrasierHD** [Wynncraft/Issues#6350]
I just go this new stick called the "Kelight's Toothbrush" and instead of it being a stick, its a stonebrick slab.
![a1435bf217f7390804cbb8a22b6ea0a1](https://cloud.githubusercontent.com/assets/22711210/19213552/6a022bd2-8d34-11e6-80a4-c3977ca94624.png)
![dafad8122028969ac48abd9c6e26874f](https://cloud.githubusercontent.com/assets/22711210/19213553/6b71c4e6-8d34-11e6-96b4-a290f02eaf2f.png)

**Comment by LordHelmchen98** [comment]
Hmm obviously theres a problem with the resource pack. Does it stay like this after restarting? And are you playing on 1.8.9? If you are on 1.8.9 and it stays like this I really dont know what to do but if you are playing on 1.9 or higher I recommend trying 1.8.9 as wynncraft is made for that version and there are bugs occuring in higher versions.

**Comment by Moe-Ronickah** [comment]
Search for "Kelight's Toothbrush", find issue #6140 .  Yep, it's a duplicate.  Take LordHelmchen98's advice and play in MC 1.8.9 or lower, because that is what Wynncraft is coded for.  I'll bet that changing the MC version fixes it.
