### ISSUE TITLE
Jungle Fever Bug

### ISSUE THREAD

**Issue by ElCoshe1000** [Wynncraft/Issues#6351]
HELLO, Today **8/10/16** y was trying to make the Jungle Fever when I finished the mission _**I DIDNT RECIEVE MY LE**_ can you fix this bug and give me my LE my username is 

TS_ElCoshe1000

**Comment by Moe-Ronickah** [comment]
First, we have no proof of what you did or did receive.
Second, if you had LE in your inventory, sometimes MINECRAFT bugs will cause you to not receive quest LE.
Third, I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency. Good luck.
