### ISSUE TITLE
Quest item Bug

### ISSUE THREAD

**Issue by oOTheExpirienOo** [Wynncraft/Issues#6353]
I lost one of the 5 Letters of the quest The Lost /fixquests doesnt work my inventory was half empty while doing it.I dropped the item and it despawned instant but there was no hopper or something what can collect any item.The area where i dropped it was the bear cave in the near of the quest start.Than i looked in my bank or other class inventorys there was nothing.Now i cant finish the quest and dont want to lev up my other class.Maybe theres a way to get the item back.Pls help me Thx.(My english is not very good,I am from Germany)Have a nice day.

**Comment by Moe-Ronickah** [comment]
We cannot reset individual quests for players.  Try /fixquests and see if that works for you, but be certain to have multiple inventory slots open.

**Comment by The007Vaderz** [comment]
The007Vaderz

I finished defeating the boss: Pirate Queen in Flight in Distress and since i was doing the quest with a partner i did not receive the quest item and jump into the exit with the reward, so i am unable to finish the quest since i needed the reward from the pirate queen boss.

**Comment by LordHelmchen98** [comment]
@The007Vaderz You should be able to just go through the quest again if you go from teleport to teleport again. Dont talk to the NPC's. Then defeat the Pirate Queen again and get the item to finish the quest.
