### ISSUE TITLE
Stuck in the Corrupter of worlds cave

### ISSUE THREAD

**Issue by kkbirdy** [Wynncraft/Issues#6357]
In the corrupter of worlds cave as an archer it is possible to get stuck before the boss fight, 
In the room where he dissapears the floor and drops you if you Escape just before he does it it is possible to not fall down, because there are invisible blocks all around and the trigger is outside the blocks it is now impossible to get out without /kill, which loses 2 soul points and possibly several items.

This just annoyed me as i was trying to complete the quest, it should be-able to be fixed by simply opening the hole for longer.

**Comment by Moe-Ronickah** [comment]
@AckroWynn , can you look into changing the timing on this, please?

**Comment by Imaxe** [comment]
This issue has been fixed, it'll be fixed in the next map push
