### ISSUE TITLE
Boss bar not going away

### ISSUE THREAD

**Issue by LotKnockMC** [Wynncraft/Issues#6359]
![2016-10-08_19 44 23](https://cloud.githubusercontent.com/assets/16809010/19217661/6cf9da7c-8d95-11e6-928d-2ce93df5ab28.png)
Pretty much, the boss bar doesn't go away after the dxp ends. This isn't too huge a problem since XP bombs are few and far between now, but /class doesn't fix it, and it's a minor annoyance.

**Comment by thecoolkogut4** [comment]
if your in a guild, that solves the problem (you would see the guild bar instead). besides doing that I dont know what else you can do, sorry

**Comment by LotKnockMC** [comment]
It goes away after re-logging but it is still a glitch so I figured I'd report it

**Comment by Moe-Ronickah** [comment]
Let's just hope that this is temporary.

**Comment by LotKnockMC** [comment]
oh didn't actually see any duplicates. :P
