### ISSUE TITLE
Airship glitch?

### ISSUE THREAD

**Issue by TheBeardyMage** [Wynncraft/Issues#6360]
Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue. Help, i tried doing the airship mission, and at the part where the big airship appears, I fell off and instead of tping back to the ship, i was stuck on the invisible block barrier. I did /kill, went balk to the airship, but it put me with the first steps of the quest. I did the child part easily, but it wont accept when i do the sound puzzle for the engineer, even though i did the puzzle correctly. Please help so i can finish this quest, my mc name is MikeHunt_TB

**Comment by thecoolkogut4** [comment]
when you die you need to do all the prior steps before the part.(Just the ones that tp u) so go to the child, then i think the room, engineer, sound, room etc. (that's not the correct order) you don't need to talk to anyone, just go to the tp zones

**Comment by Moe-Ronickah** [comment]
As the first line says, please do a search, first.  If you search for "flight", you will find 30 issues, including yours.  I know, for certain, that your issue is a duplicate, and I know, for certain, that taking thecoolkogut4's advice will help you finish the quest.
