### ISSUE TITLE
3 bugs - Quest Rewards, Spells and Loot chests

### ISSUE THREAD

**Issue by DaDerpGoat** [Wynncraft/Issues#6361]
I hopped on WynnCraft today on my archer class hoping to get to level 19 to get some bomb whatever spell, and once I Got to level 19, I went to open a loot chest and it said: You do not have permission for this area. THIS IS SO ANNOYING!!! It spams my chat every time I right click with my bow or talk to an NPC, or try to open these loot chests. It won't stop, and even relogging constantly over the space of 30 minutes and constantly retrying different things will not work. Anyway, back to the story, I relogged to open the chest (already tried it a billion times before but I was hoping to get lucky this time) and as soon sa I got back on, the spell had disappeared! Not sure if bomb whatever is passive, but it wasn't showing up in my character info, and I couldn't use it! I am still level 19, but no spell. Also, previously, I only gained half the emeralds I was promised by a quest NPC who asked me to get him eggs, milk and wheat. What a rip off. Anyway thanks for reading, and please fix these ASAP as I am getting bored of this server very quickly with loot, quests and spells not working.

**Comment by WynncraftRyc** [comment]
Same happens to me, I can't push buttons or open loot chests.

**Comment by LordHelmchen98** [comment]
Ok first of all the permission bug is related to your weapon. It is because the weapons are retextured item like halfslabs. You simply have to use your bare hands to open the chests.
Secondly you get the bomb spell at level 21 so no reason to rage about that 'the spell had disappeared'.
And last of all which quest did you do and how many emeralds did you get?

**Comment by Moe-Ronickah** [comment]
Every one of these are duplicate issues.
