### ISSUE TITLE
Duplicate quest items.

### ISSUE THREAD

**Issue by AdoptedMouse** [Wynncraft/Issues#6363]
So since the last update its not longer possible to drop items out of your bank. It will spawn back in your inventory if you try it. But if you try to [REDACTED]This shouldnt be possible.

**Comment by Moe-Ronickah** [comment]
You are correct, it shouldn't be possible.  It also shouldn't be posted here, but, rather, sent to support@wynncract.com, as it is a duping glitch.  That's already been take care of.

**Comment by MysticalBlaze** [comment]
That also happened to me, now I have 4 Purple Crystal Shards from WynnExcavation and even after I've completed it I can't get rid of them. What should I do? Just wait for the bug to be fixed?

**Comment by LordHelmchen98** [comment]
You can put 2 of them into your daily reward.
