### ISSUE TITLE
Morph-Topaz

### ISSUE THREAD

**Issue by MysticalBlaze** [Wynncraft/Issues#6364]
After playing through my Warrior and Mage classes (the Warrior being at lvl 82), I still haven't found Morph-Topaz in any loot chests, despite it being a lvl 12 item and I loot like crazy. I also haven't gotten any problems with the other Morph Set items.
  So, is it currently unobtainable? Or am I just VERY unlucky?

**Comment by LordHelmchen98** [comment]
Probably you are very unlucky, because Im pretty sure its available.

**Comment by thecoolkogut4** [comment]
loot chests on the level 12 class. loot chests give loot based on  your level *If there are no mobs near by*. if you loot chests at level 82 you are never going to get a level 12 item from  a chest (inless there are level ~12 mobs near the chest)

**Comment by Moe-Ronickah** [comment]
RESOLVED

**Comment by MysticalBlaze** [comment]
First, I know I won't get level 12 loot at level 82, so I leveled up my mage to 12 and I still found nothing.
  Also, 

> _If there are no mobs near by.
  So, if there are level 12 mobs near a loot chest, the loot will be level 12? That doesn't make a lot of sense.

**Comment by thecoolkogut4** [comment]
if you loot a chest with a mob beside it, the loot inside of the chest is based off of the level of the mob. you need to open tier 3+ chests to get accessories

**Comment by MysticalBlaze** [comment]
Question closed.
  After like 20 chests I found one. Guess I was just unlucky.
