### ISSUE TITLE
Boat Disapear??

### ISSUE THREAD

**Issue by olivercool103** [Wynncraft/Issues#6368]
I spent 2 EB on a boat and it disappeared, i want my Ebs back
My friend lost his too
My username: snowrider777
Friends username: megablastman

**Comment by thecoolkogut4** [comment]
there is a strict no refund policy so you wont be getting your eb/a boat back.

**Comment by Trixter313** [comment]
Also it's very likely that they were just dropped. There's no way for us to know.
