### ISSUE TITLE
Serpents Kiss

### ISSUE THREAD

**Issue by RogueStray** [Wynncraft/Issues#6369]
I recently bought the serpents kiss mage weapon from the sewer dungeon and after a server reset, the poison effect of the weapon stopped working. I tried relogging and switching servers, the poison just stopped working.

IGN: Str4y

**Comment by thecoolkogut4** [comment]
so your holding the weapon, then when you hit a mob once it does its default damage  (2-4) and thats it? look above the mob's head. does it show -25 damage after you hit it? the weapon does 25 damage every second for three seconds.

**Comment by XavierEXE** [comment]
Poison is glitched on some worlds, try to find one where poison is working as usual.
