### ISSUE TITLE
[BUG] Hollow Sirene Graveyard 

### ISSUE THREAD

**Issue by CallitAlex** [Wynncraft/Issues#6371]
Hey,

I am just doing the Hollow Sirene Quest and I am at Stage 5 where you have to go to the graveyard and enter the scientist's tomb. In front of the tomb where you have to click the button for the quest to go on I left my horse and was bugged in the ground. Here is an kind of "command center" with lots of command blocks and redstone and so on. I will attach screenshots where you can see where I am right now.

Coordinates: approx. X: -600 Y: 36 Z: -5340
![2016-10-10_13 44 09](https://cloud.githubusercontent.com/assets/22744606/19235105/ee824ac4-8eef-11e6-9381-97e51603edb8.png)
![2016-10-10_13 44 27](https://cloud.githubusercontent.com/assets/22744606/19235107/ee854fc6-8eef-11e6-9af5-f1b53bf92b67.png)
![2016-10-10_13 44 29](https://cloud.githubusercontent.com/assets/22744606/19235106/ee849a54-8eef-11e6-998b-3a2f02640582.png)

**Comment by Imaxe** [comment]
Horse bug, did you use 1.10. If so, horses are really bugged there. Use 1.8 instead.

**Comment by Umaruun** [comment]
Kill yourself

**Comment by Moe-Ronickah** [comment]
Wynncradt is 1.8.9 compliant.  The use of any higher version of MC is at your own risk, and yes, this is a bug with horses in higher versions of MC.
