### ISSUE TITLE
Rayshyroth won't accept sky vapor.

### ISSUE THREAD

**Issue by obliviaxel** [Wynncraft/Issues#6372]
I am trying to do the Temple of The Legends quest, and even though I have 12 Sky Vapor, Rayshyroth won't accept it. He keeps saying, "Remember, check your quest book for guidance."

**Comment by obliviaxel** [comment]
He also won't accept if I hold them out.

**Comment by ThiefPanda** [comment]
You need 1 light dust from the nether

**Comment by LordHelmchen98** [comment]
The one who posted #6373 had to take one Light Dust with him. Did you try that?
@Moe-Ronickah I saw you are also someone who manages the wiki. Can it maybe be added that you need to have a Light Dust in your inventory when you try to hand in the Sky Vapors? (I hope its ok to tag you for this although you probably would have seen this anyway.)

**Comment by Moe-Ronickah** [comment]
The Wiki is updated, now.

@LordHelmchen98 , it's OK to tag me in a situation like this.

**Comment by Moe-Ronickah** [comment]
@obliviaxel , is your issue fixed?  Can you complete the quest, now?

**Comment by LordHelmchen98** [comment]
Alright thanks. I would have done that myself, although I would have to figure out how wiki stuff works, but I don't have permissions anyway.

**Comment by thecoolkogut4** [comment]
I completed the quest yesterday and it worked fine. Hopefully the light dust was OP's problem

**Comment by XavierEXE** [comment]
When entering the cave to get the Sky Vapor, there is a tripwire that updates your quest book. Rayshyroth won't take the vapor if you don't hit that tripwire, so go back down to the cave and walk in slowly rather than using spells or sprinting. Your quest book should update.

**Comment by ColinRioux** [comment]
There has been no response in at least 30 days. If your issue still persists, please make a new issue (while checking if there are no duplicates first).
