### ISSUE TITLE
Temple of the Legends bug

### ISSUE THREAD

**Issue by ThiefPanda** [Wynncraft/Issues#6373]
Every time im trying to give Rayshyroth the 12 sky vapors he says "Remember, check your quest book for guidance"

**Comment by LordHelmchen98** [comment]
Wow that was an incredibly fast duplicate. You managed to post this within 5 minutes after this one was posted: #6372.
Its better to just have one thread about this and as the other one was posted first it will probably be used as the 'original' one. Unfortunately I don't know how to fix it but I recommend looking on the other thread.

**Comment by ThiefPanda** [comment]
Nvm i fixed it (i needed 1 light dust)

**Comment by Imaxe** [comment]
Duplicate
