### ISSUE TITLE
HELP I'M STUCK

### ISSUE THREAD

**Issue by jantoise** [Wynncraft/Issues#6374]
i'm stuck in a 1x1 hole in a random place by my horse.
i think i'm glitched under a house.

cords:179 71 -1627

oh yeh the horses are glitching a bit aswell when u go into a small room

**Comment by jantoise** [comment]
its k there was an ocelot in the hole aswell and i let me die

**Comment by thecoolkogut4** [comment]
if your stuck do /kill to get out. looks like the ocelot put you out of your misery though :/

**Comment by LordHelmchen98** [comment]
I bet you were using 1.9 or higher. Horses are glitched in those versions. If you are using 1.8.9 it should work as supposed to.

**Comment by Umaruun** [comment]
Kill yourself
