### ISSUE TITLE
Infinite Purple Crystal Shards.

### ISSUE THREAD

**Issue by kkbirdy** [Wynncraft/Issues#6375]
I don't know why but for some reason i can /fixquests and get infinite purple crystal shards. (I've only tested up to a stack becasuse i don't want to waste inventory slots.)

I have completed site C anyway and have started site D so i shouldn't even need a shard.

I have no idea how this happens and doesn't have a major effect on game play but it may lead to other issues with the /fixquests command.

(If it's to do with my player my IGN is kkbirdy )

**Comment by thecoolkogut4** [comment]
duplicate of  #1965
