### ISSUE TITLE
Items Dissapeared?

### ISSUE THREAD

**Issue by xJaed** [Wynncraft/Issues#6376]
When I was walking by the Roots of Corruption to get to Elkurn, I notice that all items in my inventory had dissapeared. Everyting in my inventory except for the armor that I was wearing and the items in my accessory slots had dissapeared. I'm not sure when it dissapeared but I know that I checked my inventory when I left Detlas and it was almost full. I also had quest items in my inventory that had dissapeared and when I went to the beginnings of the quests to get them back, I couldn't, because I was already too far along in the quest which implies that I might not be able to do the quest. I am aware that I may not get my items back but this glitch could be an issue for other players (if I wasn't the only one). Maybe I'm missing something, and I could've put my items somewhere but I fear that is not the case. Please explain why this might've happened.

**Comment by Imaxe** [comment]
It's really vague, we can't really look into this without more information about what you did.
Maybe you died? Maybe you dropped items? 
/fixquests will fix quest items. 
@xJaed

**Comment by Moe-Ronickah** [comment]
@xJaed , does anyone else have access to your account?  Is it possible that you opened MC and went in to Wynncraft, then left your login open and walked away, so that someone could have gotten access to your account?

**Comment by XavierEXE** [comment]
Did you recently check your compass menu? There's a glitch with some accounts, including one of mine, that "clears" your inventory after viewing the pet menu and other glitched menus through the compass. The items should still be there, but they all are invisible because of this glitch. Relogging fixed the issue for me.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
