### ISSUE TITLE
Extra Quest items need help

### ISSUE THREAD

**Issue by DragonSlayerTJ** [Wynncraft/Issues#6378]
So i did /fixquests to get 1 item back for a quest but i got a bunch back from quests i've already finished Please help

**Comment by Umaruun** [comment]
Make a new character, go to detlas, take the items and delete it

**Comment by Trixter313** [comment]
You should also be able to put the items in your daily rewards and get rid of them. Just make SURE you don't need them as some items aren't returned with /fixquests and you could get stuck in a quest for a long time until it is fixed.
