### ISSUE TITLE
my guild this bugged I can not leave

### ISSUE THREAD

**Issue by kaikezz** [Wynncraft/Issues#6379]
my guild this bugged I can not leave

Screenshots

step by step look at all
1- http://prntscr.com/csbd62
2- http://prntscr.com/csbcie
3- http://prntscr.com/csbclt
4- http://prntscr.com/csbco3
5- http://prntscr.com/csbcsz
6- http://prntscr.com/csbdl4

Help meeeeee

my guild this bugged I can not leave

**Comment by thecoolkogut4** [comment]
since you changed your name after you joined the guild, your stuck in it and can't leave. there is nothing you can do atm

**Comment by Moe-Ronickah** [comment]
If you search for "can't leave my guild", you will see many duplicates of your issue.
