### ISSUE TITLE
Square black and purple

### ISSUE THREAD

**Issue by Anaozao** [Wynncraft/Issues#6381]
when I install the server texture, appear several pictures on my screen all over the map, you know why?

**Comment by LordHelmchen98** [comment]
Probably you are using 1.9 or higher. In those versions you will find many resource pack bugs. You should try using 1.8.9 because Wynncraft and the resource pack as well are made for 1.8.9

**Comment by Anaozao** [comment]
thank you so much ^^

**Comment by LordHelmchen98** [comment]
You're welcome.
(Guess you can close this now)
