### ISSUE TITLE
desapearing courage mask

### ISSUE THREAD

**Issue by Penguin007Agent** [Wynncraft/Issues#6382]
Yesterday i bought a courage mask with the bead and thoday it didnt have a texture so i put it in my inventory and relogged but when i did the mask was gone and it doesnt appear even restarting minecraft

**Comment by Umaruun** [comment]
Well I dont know about it dissapearing, but no refund policy.
And skulls losing their texture after switching servers/disconnecting is a known bug.
That happens to Dungeon Tokens, too.
The Courage Mask will still work tho.

**Comment by Trixter313** [comment]
With little record of what happened there's no way of knowing what happened to the item. It could have even been accidentally dropped for all we know. Nevertheless, as mentioned above, there is nothing we can do to return the item due to the no refund policy.
