### ISSUE TITLE
My Wand Doesn't Work 

### ISSUE THREAD

**Issue by Retalation** [Wynncraft/Issues#6383]
I Have A Wand And I Wont Do Any Thing Here Are Some Screen Shots
  ![2016-10-11_14 56 36](https://cloud.githubusercontent.com/assets/22777195/19284221/fb1c02ba-8fc2-  11e6-9603-fe673467f507.png)
![2016-10-11_14 56 42](https://cloud.githubusercontent.com/assets/22777195/19284228/05fc064e-8fc3-11e6-9ea5-29ec34e26b19.png)

Plz Send Help

**Comment by LordHelmchen98** [comment]
Apparently the first picture is broken and I doubt anyone can tell you why it isnt working by looking on the second one.

**Comment by Umaruun** [comment]
Well 1 screenshot wont show anything. Try making a Video or something like that. Bug Reports have to be recreatable.

**Comment by ColinRioux** [comment]
@Retalation, have you confirmed that you have identified the item?

Also if it's depressing, it'll most likely do little-nothing.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
