### ISSUE TITLE
VIP -> VIP+ Glitched?

### ISSUE THREAD

**Issue by Celsonic** [Wynncraft/Issues#6384]
So, a "Friend" surprised me with VIP, and directly afterwards upgrading me to VIP+. I'm assuming that this happened so fast. When I click on the VIP -> VIP+ on the store, it redirects me back. I'm going to assume that this happened too quickly, and the server couldn't recognise the purchase. Just to back me up, here is the transaction.
Sub Total: 25.00 USD
Tax: 0.00 USD
Total: 25.00 USD
Gateway: PayPal
Transaction ID: 1LH04602EX594451X
Username: Celsonic
Date: 9th October 2016 23:31

There is a lot of assuming here, but please take your time to confirm this. Don't rush. This is posted ~24 hours after reported through the support email.

**Comment by ColinRioux** [comment]
First of all, is the $25 for the `VIP` or `VIP --> VIP+` transaction? 
Also, can you be a bit more specific around: "I'm assuming that this happened so fast. When I click on the VIP -> VIP+ on the store, it redirects me back". 

How I am interpreting it, is that the store is not letting you choose upgrade. If so, you can simply buy VIP again and it'll upgrade you. 

However, if you've been charged a total of $50 ($25 for VIP, $25 for Upgrade), please be specific here. It'll make it easier in the future.

**Comment by Celsonic** [comment]
Charged total of 50$, 25 for VIP, 25 for the upgrade, When I click on the icon to upgrade to VIP+, it redirects me back to the original page. This is the 25$ for the VIP -> VIP+ transaction. I'll ask for the VIP transaction information.

**Comment by Celsonic** [comment]
Misinformation between the person who bought me VIP, sorry for the inconvenience.
