### ISSUE TITLE
My friend got stuck in between blocks with teleport

### ISSUE THREAD

**Issue by killxgen1** [Wynncraft/Issues#6386]
How can my friend get unstuck hes a mage and it teleport him into a 1 block open place and he cant get out HELP PLEASE

**Comment by ColinRioux** [comment]
`/kill`
Only use if you have 4 or more soul points.

**Comment by robi7** [comment]
as a mage this happend to me many times you can use /kill or use teleport scroll if you have

**Comment by Moe-Ronickah** [comment]
RESOLVED by @ColinRioux
