### ISSUE TITLE
All of my gear is gone

### ISSUE THREAD

**Issue by 83n70** [Wynncraft/Issues#6388]
All of my gear needs to be identified and I identified 1 piece and it was not the same as the original piece of armor. I had mostly legendary gear which took literally days of farming to get.

**Comment by LordHelmchen98** [comment]
I guess you're gear was from before the gavel update. There is no way to get armor like it was before gavel. How is it different? If you mean the formatting and stats system you have to deal with that because that's how armor works now.

**Comment by Moe-Ronickah** [comment]
83n70, please go to our forums and read about the [Gavel and Gameplay updates](https://forums.wynncraft.com/forums/news.64/).  This will help you, immensely.
