### ISSUE TITLE
"Failed to login: the authentication are currently down for maintenance.

### ISSUE THREAD

**Issue by ThaDucks** [Wynncraft/Issues#6391]
I'm trying to join the server but i get this message: "Failed to login: the authentication are currently down for maintenance." I tried to google it but found some old posts and i was wondering how to fix it or what should i do.

**Comment by LordHelmchen98** [comment]
This is most likely an issue with servers of Mojang. Unfortunately I dont think theres something to solve this. You have to wait until those servers work again. :/

**Comment by Moe-Ronickah** [comment]
It is most definitely a Minecraft authentication issue, and not specific to Wynncraft.
