### ISSUE TITLE
I lost my fiery spear!

### ISSUE THREAD

**Issue by DodoPvP** [Wynncraft/Issues#6392]
During the quest Elemental Exe I had to trade in my fiery spear for study results but the server was restarting just when I gave Ragon the study results, so I joined another world so now I lost the study results and Ragon won't let me complete the quest..

**Comment by LordHelmchen98** [comment]
Try to do /fixquests ingame it should give you the spear back.

**Comment by Moe-Ronickah** [comment]
Please, never try to complete a quest with less than 5 minutes to go before the server resets.  You are just taking a big risk with doing that.
