### ISSUE TITLE
Can't play because of pack?

### ISSUE THREAD

**Issue by xkillerx15** [Wynncraft/Issues#6393]
ever since the update I can't play wynncraft anymore because when i use the required texture pack i just simply lag WAY to much, i get a max of 5FPS whilst normally i'd easily get 60-100 FPS Without the pack, anyone knows a way to fix it? I really want to be able to play again, i also am VIP on the server so i wouldn't want my money to be wasted because of me being unable to play

**Comment by LordHelmchen98** [comment]
I have no idea if it affects the fps but the pack is for 1.8.9 are you playing on that version? (it's recommended anyway as there are some bugs in higher versions)
Also are you using Optifine? It should help you get some more fps as well.

**Comment by xkillerx15** [comment]
I have already logged in with 1.8.9 optifine but still gives like a max of 5fps not even :'( i really want to play wynncraft again but i just simply can't because of the pack

**Comment by Surra-1** [comment]
Have you ever logged onto a wynncraft server without the resource pack on, to confirm it is in fact the pack causing your lag?

Check to make sure your game is set to fast graphics, and not fancy. You could also try decreasing your particles, or use some of other options to decrease your video settings.

**Comment by xkillerx15** [comment]
without the pack it runs perfectly fine, but the game makes 0 sense without the pack, all my graphics are set to it's minimal to have the least ammount of lag possible, still doesn't fix it

**Comment by LordHelmchen98** [comment]
You can also open the serverresourcepack folder in your .minecraft folder. Then look for the wynnpack I think it's called 'legacy' there. Open it with 7zip or winrar or anything like that and then take all the files and copy them to another zipped folder. You have to put that folder into you normal resource pack folder. Then open Minecraft again and choose that resource pack and also disable the serverpack for wynncraft. It should now show you the wynncraft textures. The only issue with that is that it will show you a message every few seconds which says you should play with the wynnpack that you can download.

**Comment by xkillerx15** [comment]
still doesn't fix the fps lag @LordHelmchen98

**Comment by LordHelmchen98** [comment]
Welp. I don't think I can help you then.
Only one thing. If you press F3 how much RAM does it show you on the top right corner?

**Comment by battle00333** [comment]
I have the same issue.
With resourcepack: http://prntscr.com/cy7gr6
Without resourcepack: http://prntscr.com/cy7h8h

**Comment by battle00333** [comment]
Can confirm it is infact not the resourcepack. something else on the server is causing the drop in FPS.

it DOES happen alot faster with the resourcepack enabled. but slowly without it.

**Comment by Moe-Ronickah** [comment]
@xkillerx15 , would you try to log on on a school or library computer, please, and tell us what happens?
Same request with youi, @battle00333 .
Thanks.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
