### ISSUE TITLE
Excavator Vade's grammar and colour issues.

### ISSUE THREAD

**Issue by SpringVibes** [Wynncraft/Issues#6394]
http://imgur.com/a/DGZzx

Colours need to be changed

im to be changed to I'm

"Can't you see im busy here!" Should be a '?'

**Comment by thecoolkogut4** [comment]
pretty sure he is taking on the role of a mean personality. I think he is more directed to yelling at the player then being more nice. 


( bank)

**Comment by Imaxe** [comment]
Thanks for reporting this issue! This is now fixed and will be fixed when we do an update.
