### ISSUE TITLE
Quest Issue- WynnExcavation Site D

### ISSUE THREAD

**Issue by Meowlegend** [Wynncraft/Issues#6395]
IGN- StoryNight
Description- Im on the last step of the quest, it says speak to the king of ragni. I speak to him and he says the first thing he says after you first join.

https://www.youtube.com/watch?v=eJBVAjEMlVk&feature=youtu.be

**Comment by LordHelmchen98** [comment]
Right now the video is private. You have to set it as unlisted if you want others to be able to watch it.

**Comment by Imaxe** [comment]
Im not sure what you mean by this. Cause the video you linked is private :P 
But I'm guessing you're speaking to the wrong king? The one in ragni isnt the correct one. 
There is one after the boss fights, so I recomend going through everything again.
