### ISSUE TITLE
Identifying glitch

### ISSUE THREAD

**Issue by ThisAintMario9** [Wynncraft/Issues#6397]
I found this bug were I can't identify my armour making it unusable.

**Comment by Trixter313** [comment]
Sorry for the late reply, could you give us more details? Posting some screenshots of the armor pieces would be very helpful. Thanks!

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
