### ISSUE TITLE
Weapon Disappearance 

### ISSUE THREAD

**Issue by Charliebird2** [Wynncraft/Issues#6400]
Today as I was playing Wynncraft, There was a sudden, moderately sized , lag spike which cause my game to freeze and approximately 10 seconds later, my character was stuck in a totally invisible world. Then my game froze again, I left it for a few minutes thinking it would turn out ok, however i was suddenly kicked from the server for "flying". When i re-joined I was very surprised to see that my weapon (The Divide) was not there and in its place was the starter assassin weapon. I realise that it is impossible to ever retrieve the weapon back but if anybody knows anything about this glitch or experienced it please feel free to respond to this Issue. Thank you for reading.  :D

**Comment by Trixter313** [comment]
Sorry for the late reply, were your other items still there? Could you post a screenshot of generally what was in your inventory at the time as well? Thanks!

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
