### ISSUE TITLE
Underice Quest Bug/Help

### ISSUE THREAD

**Issue by ItzzAngry** [Wynncraft/Issues#6401]
I dropped the "seeds" and the pufferfish apeared, but when I killed it, didn't drop anything, or I didn't find. What can I do? please I need help!!!!

**Comment by LordHelmchen98** [comment]
Try to get the seeds again and do it another time.

**Comment by Trixter313** [comment]
Are you still experiencing the issue?

**Comment by Moe-Ronickah** [comment]
The pufferfish did drop what it was supposed to, however, drops from unusual mobs can sometimes land and bounce.  Look around, over, and under on your next attempt.

**Comment by ItzzAngry** [comment]
Thanks guys, I got it again :smile:
