### ISSUE TITLE
Dévoreuse

### ISSUE THREAD

**Issue by SirLorenz0** [Wynncraft/Issues#6403]
I didn't play Wynncraft for quite some time. Now I startet playing again. In my Inventory was this Wand called Dévoreuse. It can't be Identified and can't be used so I'm not sure what I should do with it. Also it can't be sold.e

**Comment by Imaxe** [comment]
Just throw it away. 
Im pretty sure items with é broke in the Gavel update. The spear Fiérte (spelling?)  is also broken. 
And dont sell it to other people, you're not allowed to sell bugged items, so I suggest you to just throw it out :)
