### ISSUE TITLE
Fantastic Voyage, Stew problem.

### ISSUE THREAD

**Issue by MasterGarfieldYT** [Wynncraft/Issues#6404]
Hi. All the info from the player that has trouble on the screenshot |
                                                                                                         V
![image](https://cloud.githubusercontent.com/assets/22862564/19414553/2ee97f56-931e-11e6-8bef-eca43799fdf8.png)

**Comment by Trixter313** [comment]
Please have the person experiencing the problem post an issue, it makes working with them easier. Thanks!

**Comment by Stena1392** [comment]
I'm having the same problem, have you fixed it?
