### ISSUE TITLE
Hope this is a glitch. 

### ISSUE THREAD

**Issue by Miss-Koko** [Wynncraft/Issues#6405]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

Hi there I'm currently doing elemental exercise and I got the context from the guy and I gave him the books but when I identified the braclet it says I didn't complete it. 

Please halp.

**Comment by Trixter313** [comment]
What does it say in your quest book for the quest?

**Comment by Miss-Koko** [comment]
It says I have to give him my fire wand in exchange for the books, but I've already done that because I gave the main guy his study books back based on the quest.

Sent from my iPhone

On 20 Oct. 2016, at 7:00 am, Nick Cipriani <notifications@github.com<mailto:notifications@github.com>> wrote:


What does it say in your quest book for the quest?

-

**Comment by Trixter313** [comment]
Hmm, does the command /fixquests return any items for this quest? It seems the book didn't update when you handed over the fire wand.

**Comment by Miss-Koko** [comment]
I have to give him the study books back which are now in my inventory thank you again :)

Sent from my iPhone

On 20 Oct. 2016, at 7:00 am, Nick Cipriani <notifications@github.com<mailto:notifications@github.com>> wrote:


What does it say in your quest book for the quest?

-

**Comment by Trixter313** [comment]
Glad to hear!
