### ISSUE TITLE
Hunger of Gerts part II broke plz halp

### ISSUE THREAD

**Issue by yornthegamer** [Wynncraft/Issues#6406]
I was doing the Hunger of Gerts part II and tried talking to the captured gert but it wont continue. If anyone has advice (i tried relog /class and stuff) i would  like to know

**Comment by Imaxe** [comment]
@yornthegamer Mind posting screeshots of your quest book? 
You might've missed a stage or something, maybe watch a quest guide and follow that :D

**Comment by yornthegamer** [comment]
The quest book says: Talk to the Captured Gert but when i try it does not work
I also tried a guid by mister sebbelonien but also it still doesnt work

**Comment by yornthegamer** [comment]
:(

**Comment by yornthegamer** [comment]
I fixed it by spamming spells (maybe intentional maybe because of raging) so i finished the quest :D

**Comment by LordHelmchen98** [comment]
Yeah well this is a little bit stupid I had problems with that myself. Sometimes it just wont accept that you click onthe mob.
@Imaxe On the picture you can see there are iron bars with a small hole. I wonder if problems like that could be prevented if the hole was one block higher.
http://puu.sh/rKRGN/6a453cb83c.png
