### ISSUE TITLE
Glitch with reincarnation

### ISSUE THREAD

**Issue by BasicallyBasix** [Wynncraft/Issues#6409]
Okay, so I have killed Bob 2 times now and I still have yet to get a drop from him. The people I killed him with got theirs while I got nothing. Why is this happening

**Comment by LordHelmchen98** [comment]
Well you probably didnt deal enough damage so it only dropped for the other players but normally if there is a drop on the ground you can pick it up after like 10-15 seconds if nobody else picked it up yet.
