### ISSUE TITLE
Guild member duplication issue

### ISSUE THREAD

**Issue by Kra3tys** [Wynncraft/Issues#6410]
In my guild, Ultimo de Lumine, some of the members are doubled on tab and in /guild list.
I cannot kick these players and they cannot leave.
I simply ask my old guild be deleted so I can make a new one.

**Comment by LordHelmchen98** [comment]
Duplicate of #3665

There are several guilds like yours with bugged members. So far I haven't heard of a single one that got deleted by admins. You will have to wait until the guilds get fixed.

**Comment by Cyanah** [comment]
I'm in the same guild as Kra3tys, and not a day later, the guild was already bugged with 1 person that has been dublicated. I took a "screenshot" to show that this is real and are identical.

https://gyazo.com/c4bd7d1db473f69b4a2c28c80c00a571

**Comment by LordHelmchen98** [comment]
As I said that is well known and I still havent heard of a guild that got deleted or fixed. Those glitches happen if someone changed his name while being in a guild. If the player then tries to leave the guild he will find himself unable to leave. Also he will get listed twice.
The guy you showed in the picture joined your guild on October 16th 2016 with the name TheFancyCraft1 and changed his name one day later to TheSpookyCraft1. Thats why he got glitched and listed twice.
