### ISSUE TITLE
Guild troubles?

### ISSUE THREAD

**Issue by GooberPlays** [Wynncraft/Issues#6413]
OK so I recently left my old guild and my friend started a new one and whenever she tries to invite me it says I'm already in a guild. But I try typing /Guild leave and it tells me I'm not in a guild anyo ne know why this is happening

**Comment by LordHelmchen98** [comment]
Hmm this is not as common as those name change glitches but it is also related to guilds and Im afraid you have to wait until guilds get fixed :/

**Comment by thecoolkogut4** [comment]
I'm guessing you changed your name after you joined the guild, because of that you stuck in it till a guild update.
