### ISSUE TITLE
Spawning outside of the spawn

### ISSUE THREAD

**Issue by TylerDaNerd** [Wynncraft/Issues#6415]
I was wondering if someone could help because when i spawn in it says loading and I start falling out of the world before I can even chose a class. Any help would be much appreciated. 

Here is a screenshot: http://i.imgur.com/uUuzELW.png

If you are wondering my username is: TylerDaNerd

**Comment by ColinRioux** [comment]
Have you tried re logging / changing your internet connection?

**Comment by TylerDaNerd** [comment]
I have tried changing internet and now there is a lot of signs that say to not mess with the chest and there is another one that says to do /kill but when I do /kill it says that I cant use commands right now.

**Comment by Trixter313** [comment]
Hmm, I believe that players used to be placed in the chest area when they didn't have the resourcepack enabled but I see in your screenshot that you have it enabled. Does using 1.8.9 produce the same outcome?

**Comment by Snowflake03** [comment]
I'm having the same issue. I've tried logging on on multiple versions (1.8.9, 1.9.4, 1.10.2), and am getting the same result.
I have the resource pack enabled.

**Comment by TylerDaNerd** [comment]
Yes it has the same outcome and im still using the texture pack and spawning in the chest area.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
