### ISSUE TITLE
3 Bugs

### ISSUE THREAD

**Issue by HonzaSTECH** [Wynncraft/Issues#6417]
Please excuse my bad English.

Hello, today I´ve discovered 3 bugs in wynncraft.
  First, I think, that Ring of Generosity (reward for Memory paranoia quest) has wrong min. level vaule. Memory paranoia quest is for level 67, but Ring of Generosity if for level 69. I am not sure, if this is bug, or it is deliberate.¨

![b1](https://cloud.githubusercontent.com/assets/19894267/19492885/db1519be-9578-11e6-96cd-df756c2c3d57.png)
![b2](https://cloud.githubusercontent.com/assets/19894267/19492900/e8950748-9578-11e6-8096-dfdb9dcbc983.png)

  Second, I found an empty loot chest. I don´t know, which mechanism are you using for loot chests, but I think, this would be fixed, if you add 1 emerald to each loot chest in source code of Wynncraft.

![a](https://cloud.githubusercontent.com/assets/19894267/19492910/f340a6de-9578-11e6-923f-512916f14b62.png)

  And finaly, when I was doing Memory paranoia quest, I fell through the floor of the Erca manison when I dismounted from my horse. I had to use /kill command. Look at screenshots. There is little village under the manison. I think, this would be fixed, if you build multilayer floor in the manison. I think, that current floor of the manison is only one block thick.

![c1](https://cloud.githubusercontent.com/assets/19894267/19492952/08974416-9579-11e6-8c03-f36fef32ca9a.png)
![c2](https://cloud.githubusercontent.com/assets/19894267/19492954/0cf52d16-9579-11e6-9a8f-2956c3b3cd6a.png)
![c3](https://cloud.githubusercontent.com/assets/19894267/19492964/113eb3ba-9579-11e6-8d03-0e4d20a57407.png)
![c4](https://cloud.githubusercontent.com/assets/19894267/19492971/15e65eb8-9579-11e6-8339-c419f6a2087d.png)
![c5](https://cloud.githubusercontent.com/assets/19894267/19492974/1a477640-9579-11e6-930a-d10802e4def2.png)
![c6](https://cloud.githubusercontent.com/assets/19894267/19492978/1d5540c4-9579-11e6-9e57-fbf033c713bb.png)
![c7](https://cloud.githubusercontent.com/assets/19894267/19492982/20af618c-9579-11e6-96df-6e020ea4c05e.png)
![c8](https://cloud.githubusercontent.com/assets/19894267/19492987/23a3f448-9579-11e6-806a-b24bb3eaf697.png)

**Comment by LordHelmchen98** [comment]
Ok first of all the ring. I dont think that is a bug or a mistake because Im pretty sure thats not the only quest reward that doesnt match the quest level.
Secondly you mentioned the empty loot chest. I guess staff knows about that since it was pretty common after the gavel release. I havent seen a completely empty chest for a while though.
And last of all I bet you are using 1.9 or higher as horse glitches happen quite often in those versions. I recommend using 1.8.9 as wynncraft was made for that version and many bug occur in higher versions. But I guess you are right there could still be added some layers.

**Comment by HonzaSTECH** [comment]
Thanks, but I was using 1.8.9 optifine when this happend.

**Comment by LordHelmchen98** [comment]
Well then I dont know why the horse bugged. It never happened to me.

**Comment by HonzaSTECH** [comment]
Ok, thank you anyway.

**Comment by Moe-Ronickah** [comment]
NEVER ride a horse inside of any area when you are doing a quest.  NEVER.  We cannot predict how Minecraft will behave under these conditions.  Minecraft assumes that you will only ride a horse outdoors.
