### ISSUE TITLE
Item Bomb 

### ISSUE THREAD

**Issue by paptatje** [Wynncraft/Issues#6421]
I used my item bomb and now it is away but it didnt go off what happend and can i get it back

**Comment by LordHelmchen98** [comment]
For issues related to real life currency you have to send an email to support@wynncraft.com.

**Comment by paptatje** [comment]
i got it when i bought vip

**Comment by LordHelmchen98** [comment]
You should still send a mail to the support as it was bought with a real life currency although it was kind of a 'bundle'. They can probably help you and maybe give you another item bomb.

**Comment by paptatje** [comment]
k thanks

**Comment by LordHelmchen98** [comment]
You're welcome
