### ISSUE TITLE
Wynncraft Excavation B bug?

### ISSUE THREAD

**Issue by FR3SHPR1NCE** [Wynncraft/Issues#6423]
So I've finished the quest called Excavation A (about 8-9 months ago), logged in for the first time since then and can't start the Excavation B quest, even though I have the yellow crystal shard in my inventory. 

I do remember starting Excavation B and getting to the very end, only to find that it was glitched and no purple shards spawned. After logging in almost a year later, the quest book tells me I've started the quest, but I still need to talk to Lykron and when I do, he simply replies with 'Hello there! We are working very hard here at this excavation site! We have one in Almuj as well, I think you should check it out!' 

I assume that's the message you'd receive if you hadn't completed the first quest, which I have. 

Any help would be appreciated.

FR3SHPR1NCE

**Comment by Trixter313** [comment]
Does using the command /fixquests return any crystals to you? There are two different yellow crystal items, one from inside the temple, on the ground, and one that you get from finishing the quest. You might accidentally have the incorrect version.

**Comment by FR3SHPR1NCE** [comment]
Yes, sorry I didn't mention I've used that command as well, it says I have no missing quest items.

**Comment by Trixter313** [comment]
You said that you did start Excavation B, what does it say in your quest book, exactly? Does it mention the purple shard? If you did it a while ago and got to the end but there were no shards at the time, going back through the quest and getting a purple shard then bringing it to Lykron should fix the issue.

**Comment by FR3SHPR1NCE** [comment]
No, the quest book states that I have to talk to Lykron. Regardless, I did try to go through the quest anyway - I managed to get to the puzzle door but clicking on the buttons brought up the message 'You do not have permission for this area'. I had to use a teleport scroll to get out.

**Comment by Trixter313** [comment]
Ohh, the permission issue is a known problem with weapons because they are retextured slabs and the game thinks you are trying to place them. If you switch to an empty hand and try the puzzle again it should work. Let me know!

**Comment by FR3SHPR1NCE** [comment]
Well now I feel silly, it worked. But maybe this permission issue should be of relatively high priority since it creates annoying problems like this! Either way, many thanks for your help :)

**Comment by Trixter313** [comment]
Glad to hear it got worked out. The permission issue is talked about in issue https://github.com/Wynncraft/Issues/issues/4548 and currently we don't know of a way to fix it. Luckily it is easy to fix, by using an empty hand.
