### ISSUE TITLE
Bug report!

### ISSUE THREAD

**Issue by Piveau** [Wynncraft/Issues#6424]
Hello,
I'm blocked between invisible blocks and I can't use schroll for tp in a city and I can't use the tp spell.
My pseudo in game is Piveau. I hope than you can find a solution.

PS: My english is bad because I'm french sorry :(

**Comment by Piveau** [comment]
I'm In front of Troms in the mountain

**Comment by LordHelmchen98** [comment]
If you have more than 5 soul points do /kill. You will respawn in Troms at the cost of two soul points.
