### ISSUE TITLE
WynnExcavation Site A Bug

### ISSUE THREAD

**Issue by mono2338** [Wynncraft/Issues#6425]
When i walk to the diamond block in the center,it said"A strong force is preventing your entry"

**Comment by LordHelmchen98** [comment]
Did you really search for duplicates? If you search for 'a strong force is preventing your entry ' you get your thread and three others which are  #3464 #5045 and #5791. Look there and try see if those solution suggestions help you. If not ask again.

**Comment by mono2338** [comment]
but my quest book didnt update and it stuck at stage 2

**Comment by Trixter313** [comment]
What does your quest book say?

**Comment by mono2338** [comment]
![2016-10-21_18 37 25](https://cloud.githubusercontent.com/assets/21146220/19595662/89e67e2e-97bd-11e6-86b0-6cbb17a262d1.png)

**Comment by Trixter313** [comment]
Hmm, does using the command /fixquests return the paper that you give to Tesha? Or do you have that paper on you?

**Comment by mono2338** [comment]
i have try to use the command /fixquests and it didnt work and yes i have the pape,btw what the name of the paper(just for check)

**Comment by Trixter313** [comment]
I'm not sure what the exact name of the item is but here is the link to the Wiki for the quest, to verify you did everything correctly: https://wiki.wynncraft.com/index.php?title=WynnExcavation_Site_A

What does Tesha say when you try to talk to them?

**Comment by mono2338** [comment]
![2016-10-21_19 13 20](https://cloud.githubusercontent.com/assets/21146220/19596712/78466792-97c2-11e6-80f8-c19f785a0500.png)

**Comment by ExZiByte** [comment]
you have to talk to vade after tesha then you can enter the tomb

**Comment by Trixter313** [comment]
This quest is tricky and unfortunately many people get stuck in this very part of the quest. There is nothing the user can do to fix it, we just have to wait until an admin does something about it. There is already an issue open for this that has the exact same issue as you, issue https://github.com/Wynncraft/Issues/issues/4079.

Please follow that thread if you'd like to stay updated on the status of the issue. Thanks!
