### ISSUE TITLE
finding the light bug

### ISSUE THREAD

**Issue by greeny111** [Wynncraft/Issues#6426]
when i try to wake the forrest guardian with a taproot it won't work i have tried reloging and /fixquests and it won't start

**Comment by LordHelmchen98** [comment]
Around the guardian there is a mob that spawns rarely. Its called Volt Goat and it drops an item you need to start the quest.

**Comment by greeny111** [comment]
okay

**Comment by greeny111** [comment]
did you do the quest?

**Comment by thecoolkogut4** [comment]
with the volt goat horn in your inventory (volt goat is a yellow sheep) and the taproot right click the wooden block in the tree to start the quest
