### ISSUE TITLE
Server still doesn't exist?

### ISSUE THREAD

**Issue by darkfury45** [Wynncraft/Issues#6427]
I've tried every IP in the book, play.wynncraft.net, play.wynncraft.com, play.wynncraft.org, node7.wynncraft.com, and nothing seems to work. It just says that there is no server with the ip address. Any ideas?

Oh, and Moe-Ronickah. For a "temporary" server glitch, I imagined it would have been fixed soon.
If it's taken a week and STILL hasn't been fixed, then I don't think this is something transient.
I'm not lashing out at you, but I'm still unable to connect and you just closing the thread and shrugging it off isn't helping.

**Comment by thecoolkogut4** [comment]
go to speedtest.net what are the results? maybe try connecting to "ipfix.wynncraft.com" that might fix it?

the results would be ping, upload and download speed (from speedtest.net)

**Comment by darkfury45** [comment]
by ipfix.wynncraft.com, do you mean connect to the server with that ip on minecraft? If so then no.

Taking speedtest.net showed that I have a download speed of 35mbps (25 when trying to connect to a server in England) and an upload of 4-5mbps (which is rather poor really)

**Comment by thecoolkogut4** [comment]
yes and with that connection you should be able to connect to the server, the only other thing i could think of is your computer.  can you connect to any other MC servers?

**Comment by darkfury45** [comment]
I can connect to a multitude of servers, hosted throughout NA and EU as well.
I won't list the servers though, because that's poor etiquette and I believe a violation of the rules.

**Comment by Moe-Ronickah** [comment]
df, I've got one question for you, have you tried to connect to any of those addresses even if MC says that there is nothing there?  I do this every day for play.wynncraft.com, because MC throws a fail very, very, quickly.

**Comment by darkfury45** [comment]
I've tried, each and every one of them, to no avail. The error I get is as follows:
java.net.ConnectException: Connection timed out: no further information:

It's giving me no information other than connection timed out, so I'm not getting any response from the server.

**Comment by darkfury45** [comment]
I'm afraid that might not be a possibility for a while, but I'll try it when I can.

**Comment by thecoolkogut4** [comment]
I got an idea, is there a possibility for parental controls turn on for your internet? because if it is there might be an option restricting you from connecting to the server.

**Comment by darkfury45** [comment]
Thanks for the suggestion thecoolkogut4, but that didn't work either.

**Comment by Moe-Ronickah** [comment]
Any luck with trying a computer from outside of your home?

**Comment by darkfury45** [comment]
Tragically none.

**Comment by Moe-Ronickah** [comment]
Your account isn't, by any chance, a free account, is it?

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
