### ISSUE TITLE
I died an it lost my legendary wand when i died but i had soul points

### ISSUE THREAD

**Issue by skyguy6626** [Wynncraft/Issues#6428]
I was doing Iron heart part 2 when going to the second guy i got the horse d sync issue then when i got off i was attacked and killed when i respawned i spawned with an oak stick and i looked for my wand but couldnt find it

**Comment by LordHelmchen98** [comment]
Im afraid you won't get back any items due to wynncrafts strict norefund policy. And the big majority of horse glitches happen in Minecraft 1.9 or higher so I bet you were using one of them. To prevent horse glitches I recommend using Minecraft 1.8.9 as wynncraft was made for it.

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
