### ISSUE TITLE
[Skill Bug] Skills aren't going up when using skill points.

### ISSUE THREAD

**Issue by sitdownsun** [Wynncraft/Issues#6429]
So I got these really nice rare leggings the other day, and it said I needed to have my defense to 10. I was at 8. I leveled up, and added the 2 needed points to make my dense 10. I go to put the leggings on, and it tells me that I need to have my defense 10. I check my skills again, and my defense is still 8. So I figured it was just a small bug, and so I leveled up again. It showed my defense finally being 10.. Figured "sweet, I'll just add 2 more to be safe", so I made my defense 12. My defense is still 8, and my skill points are gone.

**Comment by thecoolkogut4** [comment]
you mostlikely have a weapon/Armour that give +-skill points. take off all of your Armour and accessories, then try to put the pants on.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
