### ISSUE TITLE
Ice barrows first parkour challenge bug

### ISSUE THREAD

**Issue by MrRedCrack** [Wynncraft/Issues#6432]
When I did the parkour LEGITIMATELY, I couldn't push the button to open the door, it says I do not have permission for that area.

Proof:
http://imgur.com/a/KKzqE
Please fix that asap, I'm now stuck in the dungeon :P I don't wanna lose my soul points

**Comment by LordHelmchen98** [comment]
It's most likely because of your Weapon. Use your bare hands instead to click the button and you should be fine.

**Comment by MrRedCrack** [comment]
fixed thanks :P

**Comment by MrRedCrack** [comment]
Erm how do i close it?

**Comment by MrRedCrack** [comment]
Thanks :P didnt notice it

**Comment by LordHelmchen98** [comment]
You're welcome :)
