### ISSUE TITLE
Bug of the tower of accension

### ISSUE THREAD

**Issue by ExZiByte** [Wynncraft/Issues#6434]
There is a bug on floor 2 level 10 in the boss room where the boss doesn't drop the token that you need to finish the floor. I have killed the boss 14 times and he hasn't dropped the token please fix soon.

**Comment by HonzaSTECH** [comment]
Weren't the tokens burned in some flame? Try to change WC server if it is always happening. I got this token normally before a few weeks.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
