### ISSUE TITLE
Stuck in the walls of Wynn Excavation Site A

### ISSUE THREAD

**Issue by Ed-James** [Wynncraft/Issues#6435]
Hello, upon completion of the Quest "Wynn Excavation Site A", I found myself trapped in a wall at 1244, 52, -1766. Apparently teleportation scrolls cannot free me of my imprisonment nor can my Archer's Escape spell. To whom it may concern, please get me out of here!
My IGN is: ED_JAME5
Thank you for your time

**Comment by LordHelmchen98** [comment]
Just do /kill if you have more than 5 soul points. That helps you out of any situation where you are stuck. You will get teleported to the closest city just like a normal death.

**Comment by Ed-James** [comment]
Will do, thank you
