### ISSUE TITLE
Randomly taking damage?

### ISSUE THREAD

**Issue by Acolyte-1** [Wynncraft/Issues#6436]
At random times throughout playing - ALWAYS when I put on/remove armour or any items - I will take damage. It has killed me before, as I play as an Archer. It's extremely irritating to randomly start dying while riding my horse through the wilderness with no monsters nearby.
Sorry if this is a duplicate, I couldn't find anything similar. I'm rather new.

Any help appreciated!

(My username is *underscore*Mx*underscore*)

**Comment by Trixter313** [comment]
Does any of your gear have negative health regen?

Also, does this only really happen while riding your horse? If so, what version of Minecraft are you using? We recommend 1.8.9 for Wynncraft as using higher versions can cause issues, an example being with horses. The movement gets out of sync and your horse could actually be somewhere other than where it appears to be on your screen, sometimes even walking into some monsters that you can't see.

Taking damage when removing armor makes sense as some armors add health and when you take those armors off the game needs to deduct health.

**Comment by Acolyte-1** [comment]
No, none of my gear has that

I'm using 1.1.10, I'll change that to 1.8.7 That seems to be exactly what you're describing! That is happening to me, the delayed horse glitch. I'll make sure to go into 1.8

Thanks so much for the help!

**Comment by Trixter313** [comment]
Glad to hear, enjoy your time playing Wynncraft!
