### ISSUE TITLE
Spam Emails Glitch

### ISSUE THREAD

**Issue by hypehype** [Wynncraft/Issues#6438]
Aight. So I got a copyandpaste email from Wynncraft saying they want me back. It was under my first username, and I was on the day before, so I am guessing this is a bug.

Fix it by making it delete old names and check for the newer ones.
Picture: http://imgur.com/a/GeRnR

**Comment by Moe-Ronickah** [comment]
This has been passed along to our current Community Manager.  Sorry for the annoyance, we'll see what's going on.  Thanks for letting us know.

**Comment by Celsonic** [comment]
aka pretzule is da best.

**Comment by Moe-Ronickah** [comment]
RESOLVED
