### ISSUE TITLE
Matryoshka Shell Vanish?

### ISSUE THREAD

**Issue by ConSavvy** [Wynncraft/Issues#6439]
I was wearing a Matryoshka Shell, when I removed my morph- amythyst that allowed me to wear the shell and some other armor. I died, but before I did, I saw the item inside my inventory. When I respawned, it wasn't there. I checked back at the site, and it poofed. The death-drop log showed that I dropped 5 zombie eyes, but not the Shell. Plz respond, as the Chestplate had 2 T4 lighting powders, 2 T4 Fire powders, and 2 T4 Earth powders, and I want it back. PS, I had almost full soul points

**Comment by LordHelmchen98** [comment]
Unfortunately you won't get back anything due to wynncrafts strict norefund policy. 
If it's hard for you to beat the boss altar again I can probably help you if we find a time when we can meet.

**Comment by Moe-Ronickah** [comment]
There is a chance for a lag delay between what you see, as a character, and what the server sees.  Unfortunately, it sounds as if it hit you, hard.

**Comment by DebugMC** [comment]
Ignore that ^

**Comment by Moe-Ronickah** [comment]
Ignore what, @DebugMC ?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
