### ISSUE TITLE
Spamming errors when using Olux's Prized Bow

### ISSUE THREAD

**Issue by MrRedCrack** [Wynncraft/Issues#6440]
Although it is not an important bug, but it annoys me very much.

Before i use that bow and I used other kind of bows, I can press buttons and punch/shoot pots without any message, but when i use my bow (name as stated above), it appears the "You don't have permission for this area." Error message like every time when i do those stuffs, even when i was just shooting stuffs at some areas(eg: Temple of the Legends)! This is an annoying spam bug, I hope it will be fixed.

**Comment by LordHelmchen98** [comment]
This is because it's a retextured slab. The game thinks you want to place it and therefore shows you that message. Unfortunately there's no way to fix it. You will have to deal with it and use another weapon or your bare hands for doors or chests etc.

**Comment by MrRedCrack** [comment]
sigh.

**Comment by MrRedCrack** [comment]
By the way, I'm in adventure mode right? then why does the game detect that I'm placing blocks? This makes no sense lol

**Comment by MrRedCrack** [comment]
My other bow is a bedrock. But it works perfectly when i use it. I really need an explanation on this :P

**Comment by LordHelmchen98** [comment]
Hmm I don't think you are in adventure mode because I think in adventure mode you aren't able to destroy grass or flower pits, are you?

**Comment by MrRedCrack** [comment]
If I'm not in adventure mode, I will see the outlines around the block. By the way for the flower pot thing, if I'm not in adventure mode I will break it instantly without any delay. The game detects when im shooting into the pot or punching it before the pot breaks, I think.

**Comment by MrRedCrack** [comment]
If you don't want to answer my question, just tell me to close the issue or you can close it yourself :P I'm okay with that, I'm just curious about this bug

**Comment by MrRedCrack** [comment]
Furthermore, I cant destroy grass!

**Comment by LordHelmchen98** [comment]
Oh welp then it's probably adventure mode but then I don't know why the game thinks you want to place the slab. Probably it's related to a plugin but I can't say for sure.
Also I don't have any permissions here. I'm just a random dude who tries to do his best to help people who have problems.

**Comment by MrRedCrack** [comment]
Oh, I see. I thought you are a staff, but thanks for the help anyway :)

**Comment by LordHelmchen98** [comment]
You're welcome. And no I'm not a staff member. Maybe I will be one in future who knows. But as they don't want people to ask for it (actually I don't know how they think about it on github lol) I won't ask/beg for it.

**Comment by Trixter313** [comment]
This issue is talked about in https://github.com/Wynncraft/Issues/issues/4548
