### ISSUE TITLE
My wand is gone :'(

### ISSUE THREAD

**Issue by generatox** [Wynncraft/Issues#6442]
Once I finished my quest, I would look for a double XP. AND reconnecting me I did not have my wand (Ohms 'Wish) in my inventory :( please help !!! I was too much hassle to find this wand :'(

**Comment by LordHelmchen98** [comment]
Unfortunately you wont get back any items due to wynncrafts strict norefund policy. You will have to buy it or grind for it :/

**Comment by Trixter313** [comment]
Also there's no way for us to tell what happened to it with the little information there is. It could be as simple as it being accidentally dropped. In case that is what happened, I'd recommend changing your drop key to something other than the default 'q'. This will help reduce the chances of accidentally dropping an item.
