### ISSUE TITLE
Some reason can't open any wynncraft lootchests, i get message: you don't have premission this area.

### ISSUE THREAD

**Issue by DrHikki** [Wynncraft/Issues#6443]
Hello, i have odd problem when i play wynncraft, i can't open any loot chests and get message when use class ability :  you don't have premission this area.
Yesterday was totally fine lvling up normally and done some quest in snowy are (45-51)
But today i start getting these odd inssues, first i think its lag because before that server kick me out for flying when i was only riding horse, but now when lag is gone i still have it  these messages poping out and cant loot it any random lootchests.
![2016-10-22_17 31 38](https://cloud.githubusercontent.com/assets/22999483/19620139/ce641f22-987e-11e6-8baf-738b13d25ce1.png)

**Comment by LordHelmchen98** [comment]
This is cause by your weapon. Its a retextured slab and for some unknown reason the game thinks you want to place it which you are not allowed to. If you want to open doors, chest,... just use your bare hands or another item.

**Comment by DrHikki** [comment]
thanks, i try out that hopelly that works :)
