### ISSUE TITLE
Fantastic Voyage Odd Stew

### ISSUE THREAD

**Issue by DaBlueTigerGirl** [Wynncraft/Issues#6445]
I am not sure if this is being worked on or not, but when I try to give Relend the Odd Stew, he just repeats the same message. This message is "If you need to create something, there are utilities on the beach..." I cannot give him the stew. I have tried to restart my game, change classes, etc. yet, it still does not allow me to continue. Hope you can fix this!

**Comment by Trixter313** [comment]
What happens when you enter the dining hall? Do you hear a click sound?

**Comment by DaBlueTigerGirl** [comment]
what do you mean by dinning hall? I am on Gateway Island

**Comment by Trixter313** [comment]
Oops. I had this mixed up with issue https://github.com/Wynncraft/Issues/issues/5974 for "Recipe for Disaster".

Here is the Wiki page for Fantastic Voyage, try following all of the steps again exactly and see if it helps at all. Sometimes there is an area you have to enter that updates the quest and people accidentally skip over it. https://wiki.wynncraft.com/index.php?title=Fantastic_Voyage

**Comment by DaBlueTigerGirl** [comment]
ok ty
