### ISSUE TITLE
Resource Pack issue?

### ISSUE THREAD

**Issue by Jordan-Mianite** [Wynncraft/Issues#6447]
with the wynnpack there is pink&black blocks everywhere, but they are passthrough, help?

**Comment by Trixter313** [comment]
What version of Minecraft are you using? We reccomend using 1.8.9 for Wynncraft as using other versions can cause issues such as this.

**Comment by Jordan-Mianite** [comment]
Ok, Thanks!

**Comment by Trixter313** [comment]
Let us know if switching to another version worked, thanks!

**Comment by Roblochon19** [comment]
Hey ! I have the bug too. I use the modpack with curse, i launch the game with the version : Minecraft forge-12.18.0.2000. I see pink&black textures, i know they are tall grasses, but i dont know how to fix it.

**Comment by Trixter313** [comment]
Wynncraft isn't meant for versions higher than 1.8.9. I looked up 'wynncraft curse modpack' and found one, I'm assuming it's the one your using, and I see that it only supports 1.10. You will have to ask the mod author to support 1.8.9 and if they don't you will have to find something else. Or just keep using it with the missing textures grass, whichever you prefer.
