### ISSUE TITLE
/fixquests keep giving the purple crystal shard

### ISSUE THREAD

**Issue by MrRedCrack** [Wynncraft/Issues#6448]
when i do /fixquests, it gives me 2 purple crystal shards, but when i do it again, it gives me another 2 purple crystal shards. I tried to throw them away, and i couldn't decrease the number of the purple shards that i have in my inventory.

I have finished excavation site C and I should only get 1 shard. Right?

**Comment by LordHelmchen98** [comment]
Yes if you finish Wynnexcavation C you only get one shard.
Also the bug with the purple shards is a known bug and if you search a little bit you get plenty examples of players who encountered this bug as well. You just have to put those items in your daily reward or fill up your inventory and then replace the quest item (e.g. with emeralds) so there is no empty slot where the quest item can be placed again. But be careful apparently you finished Wynnexcavation site c so you already used one of them but you still need one for Wynnexcavation site d.

**Comment by MrRedCrack** [comment]
Thanks :)
