### ISSUE TITLE
Quest: WynnExcavation Site B

### ISSUE THREAD

**Issue by BenjaThePig** [Wynncraft/Issues#6450]
Whats happening is that im trying to do the quest WynnExcavation Site B. Works fine until i get to the NPC called Flendar. You can see on the picture that he is supposed to push me into the hole in front of me. But he doesn't. When i try to jump in it my self nothing happens
![00c8fe5e07e044d0bee18dd10752b7fb](https://cloud.githubusercontent.com/assets/23014601/19627340/f0b443f6-9944-11e6-882f-fd7360066d0c.png)

Thanks for taking time to read! :)
- BenjaThePig

**Comment by LordHelmchen98** [comment]
What does your quest book say? I bet it didnt update at some point. You should try to trigger an update by wandering around a bit until your book updates and you can continue.

**Comment by BenjaThePig** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/23014601/19627442/2cb6c3b8-9947-11e6-8489-40fd166f5e18.png)

**Comment by BenjaThePig** [comment]
Wait it's because i had to complete WynnExcavation Site A...
