### ISSUE TITLE
Flight In Distress button misplacement

### ISSUE THREAD

**Issue by CMWizard** [Wynncraft/Issues#6453]
during the quest, after being captured, while making the key to escape, i found a button misplaced. one essential to creating the key properly. I found this on server 14, not sure if it's universal yet. Here's an image of it. 
![2016-10-23_20 31 12](https://cloud.githubusercontent.com/assets/10286454/19631309/532181e6-9960-11e6-802c-0b01f2a20f73.png)

**Comment by CMWizard** [comment]
just transferred to world 5, button is correctly placed.

**Comment by Moe-Ronickah** [comment]
I hate single-server glitches.  I wish that we knew why they happened.
I'm so glad that switching servers worked for you!
