### ISSUE TITLE
Can't proceed quest items broken (PLEASE HELP ME!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!)

### ISSUE THREAD

**Issue by RapidzGaming** [Wynncraft/Issues#6454]
IGN: RapidzGaming
Class: Archer - Level 55
Quest: WynnExcavation Site C
![untitled](https://cloud.githubusercontent.com/assets/23020960/19631729/bb6312f8-996d-11e6-938d-9bd4ab759c87.png)

**Comment by thecoolkogut4** [comment]
is that the quest item purple shard in your hand? or is it the untradeable one? you need the quest item to start the quest.

**Comment by RapidzGaming** [comment]
yes its the quest item

**Comment by RapidzGaming** [comment]
if it helps im an old player and have been playing for over 2 years or so

**Comment by RapidzGaming** [comment]
plus ive tried /fixquests

**Comment by RapidzGaming** [comment]
oh, i already strated the quest now i needed to report back thats when the proble started

**Comment by Trixter313** [comment]
What does it say on your quest book for this quest?

**Comment by RapidzGaming** [comment]
i fixed it it was a text bug i needed the red one

**Comment by Trixter313** [comment]
Ah, glad to hear!

**Comment by DebugingLonks** [comment]
@Moe-Ronickah Do I see a entity radar...
@Trixter313
