### ISSUE TITLE
Bug report where my creeper mask is gone

### ISSUE THREAD

**Issue by dutejsn** [Wynncraft/Issues#6455]
I just finish the Creeper Infiltration quest and I have a creeper mask in my backpack. I don't like the status so I decide to throw it away. But it notice me that I need it for future quest, so it was automatically picked up. The thing is, my backpack is full at the time, and I think the emerald that was picked up instantly with the creeper mask and it somehow overtaken the creeper mask's position. And now I can't find the creeper mask in my backpack or on the ground.

If you guys read this I would need a creeper mask, my game character is name Kinght and warrior class. (I will try to leave a space in my backpack so you guys can put the mask in there...)

**Comment by thecoolkogut4** [comment]
type /fixquests to get the helmet back

**Comment by dutejsn** [comment]
thank you
