### ISSUE TITLE
Poison isnt damaging monsters

### ISSUE THREAD

**Issue by MrRedCrack** [Wynncraft/Issues#6457]
My Olux Prized Bow and the Bamboo Cuff both has the ability to poison monsters, and I've checked all other armors, rings and stuffs and none of them lowers the poison. But, when I'm attacking monsters, they aren't getting poisoned with the right amount when they are added together.

Did I misunderstood something about the poison thing or is it a bug? 

By the way, I've searched the closed issues about the poison thing and none of them helped :/

**Comment by MrRedCrack** [comment]
ugh. Im stupid

**Comment by CheeseLover** [comment]
i have the same prob my poison doesn't work pls fix
