### ISSUE TITLE
Cant Access My Assassin Class

### ISSUE THREAD

**Issue by Mavelent** [Wynncraft/Issues#6458]
It wont let me access my Assassin class when i try to change. I can access all my other classes just not assassin

**Comment by MrRedCrack** [comment]
Have you tried relogging?

**Comment by Mavelent** [comment]
yes

**Comment by LordHelmchen98** [comment]
If you can't choose it because of an error message look here #5418

**Comment by Trixter313** [comment]
@Mavelent do you think that the linked issue above is the same as yours or are you experiencing something else? Thanks!

**Comment by Mavelent** [comment]
@Trixter313 Yes i think it is linked to that issue  D:

**Comment by Trixter313** [comment]
Okay, if you'd like to stay updated on the status of the problem please follow the original issue. Thanks!
