### ISSUE TITLE
Glitch in the Detlas bank

### ISSUE THREAD

**Issue by TYREX5** [Wynncraft/Issues#6459]
My archer is stock in the roof of the Detlas bank. Whene i have disconnected, my archer, he was in the bank, but whene i have connected and choose my archer class, he was spawn inside the roof same a glitch.
Sorry for my english, i am french.
cordially
![2016-10-24_15 21 03](https://cloud.githubusercontent.com/assets/23031738/19647315/ca9e8460-99fd-11e6-9630-5afa20abc869.png)

**Comment by LordHelmchen98** [comment]
As you obviously have more than 5 soul points you can just do /kill to get out.

**Comment by TYREX5** [comment]
sorry, i don't now i can use this commande.
thank you

**Comment by LordHelmchen98** [comment]
You're welcome

**Comment by Moe-Ronickah** [comment]
This area has now been filled in and should be inaccessible.

**Comment by LordHelmchen98** [comment]
Nooo no potato stash for mages anymore .-.
