### ISSUE TITLE
Bug Galleon Dongeon

### ISSUE THREAD

**Issue by mastermeter** [Wynncraft/Issues#6460]
I am doing a dongeon with a friend and when we went to the next room my friend was tp between 2 doors .

http://image.noelshack.com/fichiers/2016/43/1477317893-2016-10-24-16-00-01.png

**Comment by LordHelmchen98** [comment]
Was this when you get tped to the Armored Pirate?
If so you just reminded me of something I wanted to report as well xD

**Comment by Surra-1** [comment]
If your friend is still stuck, he will need to use a tp scroll, or /kill. Make sure he is above 5 soul points before doing /kill.

**Comment by mastermeter** [comment]
that's it and we don't want to use /kill :(

**Comment by mastermeter** [comment]
we lose a dongeon key it's annoying

**Comment by LordHelmchen98** [comment]
Well ok so thats how it looks inside. I took it when I was stuck in there http://puu.sh/rTXpw/ac7c4b41d0.png
Also is your friend a mage?

**Comment by LordHelmchen98** [comment]
My bad its an archer right?

**Comment by mastermeter** [comment]
archer

**Comment by LordHelmchen98** [comment]
Well if he was a mage I think it would be possible but I dont think theres a solution for any other class.

**Comment by mastermeter** [comment]
i search a modo or someone who can help us but nobody :(
