### ISSUE TITLE
Resource Pack breaks game. 

### ISSUE THREAD

**Issue by amen123abc** [Wynncraft/Issues#6462]
Each time I try to hop into a world, the resource packs begins to download, which proceeds to break my game and cause it to not respond. Eventually that stops, but then every other second the game continues to freeze up and not respond. What kind of problem could this be?

**Comment by LordHelmchen98** [comment]
I have no idea if that helps but are you playing in 1.8.9? If not try it as Wynncraft was made for that version.

**Comment by robertm1771** [comment]
@amen123abc Only thing that comes to my mind at this time is to check for free disk space. I have had such problems in other games when my SSD got full before I noticed it.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
