### ISSUE TITLE
I lose my Mythic in Hopper from Seaskipper by lag

### ISSUE THREAD

**Issue by SrEnderPvP** [Wynncraft/Issues#6463]
It was an accident, i was in the seaskipper boat, and i drop my "pure" wand by error, its a mythic and i really need it, i have no more good wands, i lose my chestnut today in the Corrupted sewers dungeon today i was in a full server and there was like a 30% lag, i try to drop my seaskipper pass and i drop y pure wand, please, i need my wand, if u can get it again, or give me a new one i will be really thankful, please, i really need that wand.

**Comment by LordHelmchen98** [comment]
Uhh you will be "thankless"? I guess you mean thankful right?
But I have to destroy your hope. Wynncraft has a strict norefund policy and you wont get back any items.

**Comment by robertm1771** [comment]
@SrEnderPvP I will try and do this in a nice way vs the other message.
If you look up hopper in the issues section you will find a number of such hopper problems. If you check the replies to these you will notice the "strict no refund policy" stated from people in authority. I am sorry for you loss.

**Comment by Trixter313** [comment]
To try and prevent accidentally dropping an item, I'd suggest changing the drop key to something that you're less likely to accidentally press. If it was dropped from the open inventory there's not much you can do to combat that except being extra careful.
