### ISSUE TITLE
Hollow Sirene Quest Cant access buttons on gravestones

### ISSUE THREAD

**Issue by sazzibelle** [Wynncraft/Issues#6464]
The buttons on the gravestones are not accessible for me to move on to the crypt part of the quest.

![2016-10-24_16 17 29](https://cloud.githubusercontent.com/assets/23040802/19664316/6b1e3ec4-9a05-11e6-980d-84285098f31a.png)

![2016-10-24_16 03 06](https://cloud.githubusercontent.com/assets/23040802/19664206/06d8819a-9a05-11e6-8077-148036de7e09.png)

**Comment by LordHelmchen98** [comment]
Just use your bare hands or another item. This problem is cause by your weapon because its a retextured slab. The game thinks you want to place it which is not allowed. Theres unfortunately no fix for that issue.

**Comment by sazzibelle** [comment]
Okay that worked.  I'll remember that in the future.  Thanks for the fast response.

**Comment by LordHelmchen98** [comment]
You're welcome
