### ISSUE TITLE
CAN'T LEAVE GUILD

### ISSUE THREAD

**Issue by Mystogen** [Wynncraft/Issues#6465]
I've been in a guild for some time now, and no one in my guild is ever on. I have been wishing that this glitch would be fixed, but it seems it has not been fixed yet. The message comes up and everything, but when I type in yes, I lose 3 soul points, but i'm still in the guild. Please help me!

**Comment by thecoolkogut4** [comment]
guilds are broken there is nothing you can do about it. your stuck in till they fix guilds

**Comment by Mystogen** [comment]
Do u know when it will be fixed?

**Comment by thecoolkogut4** [comment]
probably when the refractor comes out so 6months? maybe?

**Comment by Mystogen** [comment]
Ooof

**Comment by Mystogen** [comment]
ty

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3665
