### ISSUE TITLE
Ineffective Archer Escape

### ISSUE THREAD

**Issue by Rockobar** [Wynncraft/Issues#6466]
Hello, I am a relatively new player, however I find this issue peculiar. Ever since level 11, as an Archer I've utilised Escape (LLL) to travel around more quickly. However, after a whileI noticed that I wouldn't travel as far, but my trajectory propelled me upwards rather than along the usual horizontal plane. It is not because of the Speed buff granted by level 2 Escape, as the issue was prevalent before I reached level 2 Escape. Only occasionally will Escape propel as far as it used to and seemingly sporadically.

Thank you
Rockobar

**Comment by LordHelmchen98** [comment]
You should try to jump and use Escape in the air. Normally this works for me.

**Comment by Trixter313** [comment]
Are you sure you're looking the right way? If you look more at the ground it will send you more upward but if you look more horizontally it will send you more horizontally backward.

**Comment by Rockobar** [comment]
Even when looking horizontally it tends to shoot you upwards. Trying to time a jump as LordHelmchen says does increase the odds of moving horizontally, but not as accurately as intended.

**Comment by AscendedKitten** [comment]
It's been more than a month without a reply to this issue, and there've been no further reports.
If the problem persists, feel free to open a new issue!
