### ISSUE TITLE
bug in a donjon Sand Swept

### ISSUE THREAD

**Issue by FanatikGamer** [Wynncraft/Issues#6467]
Hi , i'm FanatikGamer and i'm blocked in a donjon Sand Swept because i can't have a token for open the door , i have do 2 time the boss for open the door and the loot dropped but i can't retrieve the hammer 
please come help me i can't leave a donjon exped i'm dead 

sorry for my english but i'm french and i'm bad in english ^^

ty for help

**Comment by thecoolkogut4** [comment]
is the hammer a item that your buy for the shop? if it is when you finish the dungeon you get a 2 "tokens"  that you spend in the shop

**Comment by FanatikGamer** [comment]
it's fixed after a restart server
