### ISSUE TITLE
Ice Barrows 

### ISSUE THREAD

**Issue by Blaaaaa1** [Wynncraft/Issues#6468]
There is a spot where u cant get out as a assasin. In the big room with the lake and a massive ice pillar in the middle. Hard to describe where it is, if it's possible, a staff could come online and i would show the spot.

**Comment by Trixter313** [comment]
If you could post a screenshot of the issue or the coordinates, that would help. Also if you're still stuck you can get out using the command /kill

**Comment by Blaaaaa1** [comment]
I died there, and i cant get there anymore because i die everytime.

**Comment by LordHelmchen98** [comment]
I helped him to get there and got screenshots.
http://puu.sh/rWotA/52419bddae.png
http://puu.sh/rWhCG/271d78e515.png

**Comment by Moe-Ronickah** [comment]
@Imaxe , would you take a look at this area and see if an escape route for assassins was somehow overlooked, please?

**Comment by LordHelmchen98** [comment]
Hmm an escape route? This is a 1x1 hole which doesn't lead anywhere. I think this could just be filled up with barrier blocks.

**Comment by Moe-Ronickah** [comment]
@AckroWynn , would you take a look at this?

We WILL get this fixed.

**Comment by AckroWynn** [comment]
That has been fixed. Should be out already.
