### ISSUE TITLE
Item Has Same Intel Stat As Another But One is a 1 star and the other is a 3 star

### ISSUE THREAD

**Issue by TooCancerous** [Wynncraft/Issues#6469]

**Comment by TooCancerous** [comment]
![2016-10-25_20 51 30](https://cloud.githubusercontent.com/assets/23066170/19709470/df6f27da-9af4-11e6-8304-078852745874.png)
![2016-10-25_20 51 32](https://cloud.githubusercontent.com/assets/23066170/19709472/e1134d0a-9af4-11e6-8cb2-dca4e63de52b.png)

**Comment by TooCancerous** [comment]
The Intelligence stat is at 8 and 3 stars which means it is perfect but the other morph steel has 8 intelligence but 1 star

**Comment by Surra-1** [comment]
The way the stars are calculated, let's a smaller number (like 8) have 1, 2, or 3 stars.
* = 101% - 124%
** = 125% - 129%
*** = 130%
The base Id in the chestplate is 6
*     6 x 124% =  7.44 (I think they still round up)
**   6 x 129% =  7.79 That rounds to 8
*** 6 x 130% =  7.8    That rounds to 8

**Comment by TooCancerous** [comment]
oh k

**Comment by Moe-Ronickah** [comment]
Thanks, Surra.
