### ISSUE TITLE
im stuck

### ISSUE THREAD

**Issue by KasperTheDarkGhost** [Wynncraft/Issues#6471]
i was riding over a mountainrange and i bugged out and now im stuck in a prison somewhere and i cant get out, and the map is broken so i can't even see where i am

**Comment by Surra-1** [comment]
If you a 100% stuck, then use a tp scroll. As a last resort check to make sure you are above 5 soulpoints, and type /kill

**Comment by KasperTheDarkGhost** [comment]
i dont have any scrolls with me so yeah il just kill myself

**Comment by KasperTheDarkGhost** [comment]
thanks for the help

**Comment by KasperTheDarkGhost** [comment]
welp rip op ring

**Comment by Surra-1** [comment]
No problem
