### ISSUE TITLE
Mt. Wynn

### ISSUE THREAD

**Issue by LuiJepsen** [Wynncraft/Issues#6472]
I do not know if u can call this a bug, but it is an issue non the least. I really like the idea of the quest, but when u kill a mob and it respawns 2 sec after u just killed it, it is getting really hard. But the worst part is probably everytime im doing the parkour part at the bottom, there will either be a skeleton falling down from above shooting me into the lava which kills me, or a zombie falling straight down in to my head knocking me into the lava. These things honestly ruin the quest for me

**Comment by Surra-1** [comment]
Buy some health pots from a town near your level, or wait until you are a higher level.

**Comment by MrRedCrack** [comment]
You have to do the parkour quickly so that mobs cant shoot you fast enough :D

**Comment by Trixter313** [comment]
Have you been able to complete it yet? Since we don't have other reports of this and many players have completed it I don't think it's an issue with the quest. If you'd like, you could post about making it easier in the suggestions area on the forums to see other's input on it.
