### ISSUE TITLE
Cinfras Guild War

### ISSUE THREAD

**Issue by Kra3tys** [Wynncraft/Issues#6473]
Cinfras mobs aren't spawning when i try to initiate a guild war.
This has happened every time.

**Comment by LordHelmchen98** [comment]
This is just another bug with guilds. Its the same with Lava Lake aka Frozen Heights. I haven't tested each territory but once I heard all the Gavel territories are bugged.

**Comment by thecoolkogut4** [comment]
right now, you can only liberate wynn territories as all of the gavel ones are broken
