### ISSUE TITLE
Ice Barrows Group Entry Issue

### ISSUE THREAD

**Issue by Afterburner0** [Wynncraft/Issues#6474]
I, along with two friends, had trouble at the end of the Ice Barrows dungeon. Specifically, we had trouble spawning into the boss room. Only one person from our group of three was able to teleport into the boss room. We had this problem both of the times we attempted the dungeon. This glitch is odd because 1) every transition in Ice Barrows worked fine until the boss transition. 2) In every other dungeon so far, all of us were able to spawn into the boss room successfully.

Thank you for your time, and I hope a solution is reached soon.

**Comment by thecoolkogut4** [comment]
did you try and switch worlds? some times specific world's get glitched

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
