### ISSUE TITLE
Corrupted Lost Sanctuary TP Broken

### ISSUE THREAD

**Issue by Frostvenom795** [Wynncraft/Issues#6478]
You can't TP into the corrupted version of Lost Sanctuary.

![2016-10-27_20 32 48](https://cloud.githubusercontent.com/assets/4985049/19790487/8f23dbb6-9c86-11e6-8ae9-cd08525b99bc.png)

**Comment by LordHelmchen98** [comment]
They encountered some problems with the Corrupted Lost Sanctuary dungeon. Thats why there are portals already but you dont have access yet.
Look here: https://forums.wynncraft.com/threads/hallowynn-is-out.161480/
