### ISSUE TITLE
A Grave Mistake - Too many bugs

### ISSUE THREAD

**Issue by MrRedCrack** [Wynncraft/Issues#6480]
There are so many bugs in this quest that makes it almost uncompletable without going into different servers. First of all, I've been stuck in so many 1 block areas that was supposed to teleport me to other place. Second, the hole in the first house in some servers are also broken, the hole is there, and we are not able to fall into the underground area. Sometimes the floating paper is not even there! This bug is massively bugged for me, please fix that as soon as possible. :/

EDIT#1: Furthermore, so many players have been stuck on the place where there is an anvil with a skull on top.

EDIT#2: For now, this quest is impossible for me to complete as I will be stuck in a cutscene everytime.

**Comment by Celsonic** [comment]
![2016-10-28_16 27 37](https://cloud.githubusercontent.com/assets/21028327/19821292/93c2d2bc-9d2b-11e6-84e3-b5771d8b639d.png)
At the end and STUCK....

**Comment by Moe-Ronickah** [comment]
This should be fixed sometime tonight, we think.

**Comment by MrRedCrack** [comment]
this is now fixed and I am able to finish the quest now
