### ISSUE TITLE
2016 hallowynn quest

### ISSUE THREAD

**Issue by ConSavvy** [Wynncraft/Issues#6482]
I did the quest in terms of finding all the dialogue, but I can't get the rewards. I even talked to ghost Twain, but no rewards from the quest giver. Also, many reports of players getting stuck in the houses or in the 'cutscenes'

**Comment by Kneesnap** [comment]
I am having the same issue, with the inability to claim rewards after the final cutscene.
IGN: Kneesnap

Screenshot: http://prnt.sc/czwqg9

**Comment by Kneesnap** [comment]
Whenever I use a teleport scroll I get this message: "You cannot teleport while in a storyline."

/killing myself respawns myself in the cult area.

**Comment by Trixter313** [comment]
What does it say in your quest book? Also, does /fixquests return any items for this quest?

**Comment by Kneesnap** [comment]
Quest Book: ".;I. ,told;. .,you; :to, .,stay; .away';"

I'm not going to run /fixquests until I get my daily rewards for today, as I don't want to have to hold onto those items until then.

**Comment by marnetcho** [comment]
I need moderateur I'm stuk in a house and I can't move I try everythings

**Comment by Moe-Ronickah** [comment]
We are hoping to have these issues fixed this evening.

**Comment by Kneesnap** [comment]
Sweet! Thanks for your hard work, it really shows. The quest (forgetting the bugs) was an impressive leap, and I hope that the dev team continues to make more things like this possible.

**Comment by Moe-Ronickah** [comment]
Thank you!  I will pass your compliment along.

**Comment by Celsonic** [comment]
#6480

**Comment by FreeProGamer** [comment]
I cannot find the 3rd door, also I am regretting I starter the quest because now i cannot use scrolls, neither die. Please fix the quest as soon as possible!

**Comment by Trixter313** [comment]
Is this issue still occurring? There was a recent patch that supposedly fixed some issues with the new quest. https://twitter.com/Wynncraft/status/792191614349258753

**Comment by Kneesnap** [comment]
I'll check in a little bit.

**Comment by LordHelmchen98** [comment]
@Trixter313 It's fixed so this can be closed now.

**Comment by FreeProGamer** [comment]
Yes it was fixed, I finished the Quest but you cannot use scrolls till you relog
