### ISSUE TITLE
Aldories secret part 2

### ISSUE THREAD

**Issue by SteveY111555** [Wynncraft/Issues#6486]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

I did not get my reward of 10,000 something emeralds or 450,000 XP or my my elves dissapointment after i finished the quest!

**Comment by SteveY111555** [comment]
what do i do
please give my my reward and fix the quest

**Comment by Moe-Ronickah** [comment]
Medallion or receipt, the choice is yours.  [Your choice](https://wiki.wynncraft.com/index.php?title=Aldorei%27s_Secret_Part_II) affects your reward.
