### ISSUE TITLE
The Quest "Potion Making" has frozen

### ISSUE THREAD

**Issue by Dalmatinerfreund** [Wynncraft/Issues#6488]
I brought 8 Red Mushrooms to the assistant and the new text came, but after i clicked again on him he said, that he wants 8 red mushrooms. So I tryed to collected 8 Red Mushrooms again and give it to him but nothing happend. Also the boss is not appering. Can the quest be resetted cause i can do nothing? I relogged to!

**Comment by HazardEST** [comment]
this has been posted before.
[https://github.com/Wynncraft/Issues/issues/6437](url)
