### ISSUE TITLE
Sand Dungeon - 2 bosses!?

### ISSUE THREAD

**Issue by AvengedDev** [Wynncraft/Issues#6489]
Hello. I'm not sure if it's supposed to be this way, but the past couple times I've gone in the Sand Swept Tomb, I've had to face two of the final boss. I've died doing so, and I've completed the dungeon before when it was just one. I think this is a bug, thanks for reading.

**Comment by Moe-Ronickah** [comment]
@AckroWynn , can you check this out, please?

**Comment by thecoolkogut4** [comment]
this happens in every dungeon every so often.

**Comment by AvengedDev** [comment]
Nice to know... Although I don't think it's supposed to be this way. Please fix this, I'm sick of dying to 2 bosses.

**Comment by thecoolkogut4** [comment]
hey, some people like it as they get the dungeon xp and reward twice. but yeah it's not meant to be like this

**Comment by AckroWynn** [comment]
@Moe-Ronickah I have no idea if we're even able to fix this, as it's been an issue ever since dungeons were first introduced.

**Comment by Moe-Ronickah** [comment]
So be it.  The challenge is on; get better weapons, better armor, and be prepared for Groundhog Day 3, Wynncraft Dungeons.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
