### ISSUE TITLE
Corrupted Lost Sanctuary Key lore typo

### ISSUE THREAD

**Issue by ImSickPT** [Wynncraft/Issues#6491]
http://prntscr.com/d05u7y

**Comment by Moe-Ronickah** [comment]
Nice catch!  @AckroWynn , can you fix this or get it fixed?

**Comment by ImSickPT** [comment]
@Moe-Ronickah @AckroWynn I found out that the level and coords are the same too!

**Comment by Moe-Ronickah** [comment]
It's the same dungeon, just renamed.  However, not everything got renamed at the same time in the same way.  It's an oversight, really, but one that should be easily fixed.

**Comment by AckroWynn** [comment]
@Moe-Ronickah I don't know how to fix that. It's something for Salted, I guess.

**Comment by Moe-Ronickah** [comment]
Passed to admin.

**Comment by Moe-Ronickah** [comment]
Please follow this on $5994
