### ISSUE TITLE
My Defense Values Are Wrong.

### ISSUE THREAD

**Issue by AaronnWall2107** [Wynncraft/Issues#6493]
[Deleted for you.]

My Armour gives me the wrong defense value when equipped.

for example, some of my Armour or weapons, or any other rings/bracelets have a + fire defense on them, yet somehow I am stuck with -22 fire defense, and this is the same all of the defenses, they just don't add up to the correct thing, now I just keep getting killed very quickly from things that are a lower level then me.

![2016-10-28_19 49 52](https://cloud.githubusercontent.com/assets/23126828/19818613/6fa82d56-9d48-11e6-938d-d498c1fe2418.png)

![2016-10-28_19 50 00](https://cloud.githubusercontent.com/assets/23126828/19818606/6751db48-9d48-11e6-99f7-7a28efd687a1.png)

![2016-10-28_19 50 03](https://cloud.githubusercontent.com/assets/23126828/19818615/75291b8c-9d48-11e6-9565-25b117274ad4.png)

![2016-10-28_19 50 07](https://cloud.githubusercontent.com/assets/23126828/19818618/78367464-9d48-11e6-96ac-759e54137dc1.png)

![2016-10-28_19 50 13](https://cloud.githubusercontent.com/assets/23126828/19818621/7ba44dce-9d48-11e6-9995-f2a4cfc87283.png)

![2016-10-28_19 50 54](https://cloud.githubusercontent.com/assets/23126828/19818625/7fabca0a-9d48-11e6-8380-d03cbdb7e740.png)

![2016-10-28_19 50 56](https://cloud.githubusercontent.com/assets/23126828/19818631/86df22d6-9d48-11e6-9b68-0e9ce9e13334.png)

![2016-10-28_19 51 00](https://cloud.githubusercontent.com/assets/23126828/19818634/8a396b08-9d48-11e6-8332-aa0d35d45d37.png)

**Comment by Moe-Ronickah** [comment]
It's a bug with the compass data calculation, it's not real.  It's just the compass displaying something strange, as usual.
