### ISSUE TITLE
Hallowynn quest bug

### ISSUE THREAD

**Issue by Meefz** [Wynncraft/Issues#6495]
Hi ive been to all the places in stage 2, 3 times and nothing is happening

**Comment by Trixter313** [comment]
Is this issue still occurring? There was a recent patch that supposedly fixed some issues with the new quest. https://twitter.com/Wynncraft/status/792191614349258753

If it is still occurring, could you go into a little more detail? What does it say in your quest book? Thanks!

**Comment by Moe-Ronickah** [comment]
RESOLVED
