### ISSUE TITLE
My warrior class

### ISSUE THREAD

**Issue by redsoxno10** [Wynncraft/Issues#6496]
I have not played my warrior class since a year ago, and appearently it is like "not compatable" or something because it won't ever load. I have tried multiple servers, many diferent times of day (i didn't think that mattered) and it still didn't work. if you devs can figure it out, my username is Sudoman.

**Comment by LordHelmchen98** [comment]
If you get a error message every time you try to choose your class, this is a duplicate of #5418

**Comment by Trixter313** [comment]
@redsoxno10 Please let us know if you get any error messages, or if it is a duplicate of the issue linked above. Thanks!

**Comment by redsoxno10** [comment]
I put what i saw in the #5418
