### ISSUE TITLE
Galleon's Graveyard Dungeon is bugged.

### ISSUE THREAD

**Issue by FabianTheGreat** [Wynncraft/Issues#6497]
I finished the Galleon's Graveyard Dungeon, using the cannons to kill Redbeard, but nothing happened. He dropped his sword, but I wasn't teleported out or anything (Im assuming killing Redbeard is the last part, because he was the Boss). I waited for him to respawn to kill him again, and the same thing happened,
I don't have a recording software, but I took snapshots of the swords he dropped, if that counts as proof?

Snapshots: 
http://imgur.com/a/ciYYc 
http://imgur.com/a/0Y4A4

p.s. This is my very first bug report, so if I did something wrong in reporting the bug, I'd very much like to know.

**Comment by Trixter313** [comment]
What does it say in your quest book for the quest?

**Comment by FabianTheGreat** [comment]
As the name implies, it is a Dungeon, not a quest. So, it has no effect on my quest book.

**Comment by Trixter313** [comment]
Whoops, my bad.

You definately are supposed to be teleported out upon the death of the boss. There have been a couple patches recently and sometimes just one world can get temporarily messed up. If you try again now does it teleport you out as expected?

**Comment by FabianTheGreat** [comment]
I would like to try again, but I can't get on ATM, and I only had the one key to get in. I got the key as a mob drop and don't know if there is a merchant I can buy it from.
But next time I have a key for it, I'll most definitely try it out!

**Comment by nightmare142857** [comment]
there isn't any merchant, that means u have to gather keys by urself (u can collect this key in lots of ways, like fighting guardians in oceans, or near fountain of youth and dark forest. It can also be acquired from Seaskipper)

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
