### ISSUE TITLE
Seaskipper Captain

### ISSUE THREAD

**Issue by HazardEST** [Wynncraft/Issues#6498]
I used him to get to Selchar from Mage island and then i got stuck in the middle of ocean with him.
![2016-10-29_11 41 00](https://cloud.githubusercontent.com/assets/11006855/19828364/aab93500-9dcc-11e6-86a2-54456fb7774b.png)

**Comment by thecoolkogut4** [comment]
if you still stuck on it type /kill, or use a to scroll to get out. try to take the sea skipper again on a new server from selchar to mage island and see if it works.
