### ISSUE TITLE
Shattered Minds bug

### ISSUE THREAD

**Issue by jonathanchan001** [Wynncraft/Issues#6499]
Hello!

While i was doing the Shattered Minds quest and i was at the last stage, I talked to Likeru in the drug-trip version of the village. Afterwards I went to talk to Likeru again in the "real" wynncraft world, she only had the one-liner when a player hasn't gotten the mushrooms like she said, but I went through with all that already.

So I did /kill and when I respawned in the tutorial area, it wasn't fixed, and when i did /fixquests I didn't get the mushrooms. Any suggestions? Thanks.

**Comment by Porcotron** [comment]
To get The item you need to talk with an old lady on The hole that you come from

**Comment by Trixter313** [comment]
Here is the link to the wiki for the quest, use that to check that you did everything you needed to do and let us know if it helps, thanks!

https://wiki.wynncraft.com/index.php?title=Shattered_Minds

**Comment by jonathanchan001** [comment]
Hey!  I did as you said and it worked fine. Thanks for the help!

**Comment by Trixter313** [comment]
Glad to hear! =)
