### ISSUE TITLE
Corrupted Infested Pit bug (stuck)

### ISSUE THREAD

**Issue by ImSickPT** [Wynncraft/Issues#6500]
There is a problem on the corrupted infested pit dungeon... When you get to the corrupted hanging man part, the wall of barriers preventing you from going forward isn't removed, making players stuck... Like me... By the way, the cutscene isn't resettable...

**Comment by ImSickPT** [comment]
Even though I was able to get unstuck by changing servers, I still think this bug should be fixed.

**Comment by Moe-Ronickah** [comment]
This is an issue that crops up every now and then on any MC server with multiple words, afaik.  Sometimes bosses won't spawn, sometimes puzzles won't work.  I'm sorry for your inconvenience, and it really was, however, you found the only fix for it that we currently know of - changing worlds.
