### ISSUE TITLE
2016 Halloween Quest Bug

### ISSUE THREAD

**Issue by Brother-Nugget** [Wynncraft/Issues#6501]
After a day of  bug fixes for the new halloween quest, I went to go try it to see if I could get some xp.  I collected all the clues and then got teleported to the big door at the back of the graveyard. It didn't let me get past the door and just kept on saying "Stay away". I've tried to find a way how to fix this, but I failed. Also, when the door closes and you're still trying to get tped to finish the quest, you get stuck there and the door blocks you so that you keep on getting tped back and forth in the same spot.

**Comment by Trixter313** [comment]
What does it say in your quest book for the quest?

**Comment by Brother-Nugget** [comment]
It says "Stay away" or something like it. I'm pretty sure that's the same thing it says when you start the quest.

**Comment by Brother-Nugget** [comment]
Never mind. It's been fixed now.

**Comment by Trixter313** [comment]
Glad to hear =)
