### ISSUE TITLE
relic bow

### ISSUE THREAD

**Issue by banfio** [Wynncraft/Issues#6502]
so of course i'm not going to describe where it is or anything, but there seems to be an issue with the entrance to it's location, going through the usual method of opening it leaves an obstruction that seems impossible to get around. the person who led me there was as baffled as i was

**Comment by thecoolkogut4** [comment]
did you try to switch servers and go in or is it broken for you on every server?

**Comment by banfio** [comment]
I've tried switching servers, the blockage seems to be independent of server

**Comment by LordHelmchen98** [comment]
I can confirm this. I tested it and I had the same issue. The block in the middle of the 3x3 door doesn't get removed by the pistons.

**Comment by ceejayvee23** [comment]
I am having this same problem. Please almighty gods of Wynn, fix this.
![2016-11-05_22 02 39](https://cloud.githubusercontent.com/assets/23287259/20034865/b4775490-a3a4-11e6-8480-045de189654f.png)

**Comment by ceejayvee23** [comment]
I have found a workaround for the time being... place a boat on the other side and hop into it.

**Comment by banfio** [comment]
Fair enough

**Comment by Moe-Ronickah** [comment]
@AckroWynn - we seem to have a doorway that would like some TLC . . ..

**Comment by AckroWynn** [comment]
So, can someone tell me where this door is? Coordinations, please.

**Comment by AckroWynn** [comment]
I upgraded it to being a CMD door. No more glitchiness!
