### ISSUE TITLE
Untradeable Items

### ISSUE THREAD

**Issue by Masterpringles** [Wynncraft/Issues#6503]
Will i ever need these untradeable items? I have the done the quest for the items i need it there

**Comment by Blaaaaa1** [comment]
I guess not, but you shouldnt post it in the Issues section.

**Comment by thecoolkogut4** [comment]
you don't need to keep them. feel free to throw them out. but be aware that you might not be able to get the item back. to get it back you might need to redo a quest, or go through some long process.
