### ISSUE TITLE
Stuck in the hole

### ISSUE THREAD

**Issue by Nehpilin** [Wynncraft/Issues#6504]
I and my friend were in the hotel we found on the road, we lie in bed and when we got up we left in the hole and could not use the Scroll of Teleportation 
![a0kcuh ktkslaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/23140032/19831231/a39ce610-9de3-11e6-9119-d57b43dae995.png)

**Comment by ColinRioux** [comment]
`/kill` will be your friend. Can you also report this hole to YunoGasai on the forums? Thanks.
