### ISSUE TITLE
Maiden Tower

### ISSUE THREAD

**Issue by Blaaaaa1** [Wynncraft/Issues#6505]
There is a way to kill the cursed maiden without having the helmet. If she falls down the ladder you can just open the doors and kill her outside. 
![2016-10-29_19 01 17](https://cloud.githubusercontent.com/assets/23065455/19831438/49b9094a-9e0a-11e6-921a-ac81276742b4.png)
![2016-10-29_19 01 22](https://cloud.githubusercontent.com/assets/23065455/19831439/4b46063c-9e0a-11e6-9818-7b89c241f52d.png)

**Comment by thecoolkogut4** [comment]
pretty sure u need the helmet in order to proceed with the quest, so having it won't help. the quest boom updates with the helmet if im correct? and you can't skip that step
