### ISSUE TITLE
Item Bomb Glitch

### ISSUE THREAD

**Issue by Cyanah** [Wynncraft/Issues#6507]
![item bomb 2 failure](https://cloud.githubusercontent.com/assets/22920656/19832183/1ddd1092-9e1d-11e6-91f9-d1f73a4c31f6.png)
![item bomb 2 failure2](https://cloud.githubusercontent.com/assets/22920656/19832184/1dde871a-9e1d-11e6-8dfa-820b19bf32b3.png)

After buying VIP+ I received 2 Item Bombs. After I saw the update sneakpeak from Salted's post I decided to drop my Item Bombs and tried 1 when everyone was ready. Sadly it was still disabled and we had to wait. After the update (Friday the 28th), a day later, I tried dropping my second Item Bomb, since it didn't give my 2nd back. After trying my second bomb, I saw I didn't had any Item Bombs left. I think this is a bug and my screenshot of my second Item bomb failure. I didn't record it, since I thought it wasn't necessary.

**Comment by thecoolkogut4** [comment]
you won't be getting the bomb back, you should of waited for the post saying item bombs have been reenabled.

**Comment by Trixter313** [comment]
Anything dealing with real life money should be emailed to support@wynncraft.com

Cases like this are dealt with on a case by case basis so you can email them and see what they say.
