### ISSUE TITLE
Double message in guild chat bug

### ISSUE THREAD

**Issue by Porcotron** [Wynncraft/Issues#6508]
When anything in guild chat happens it send 2 messages to me. Its annoying

**Comment by Surra-1** [comment]
If you change your name in a guild, there is a possibility you will see double chat.

**Comment by thecoolkogut4** [comment]
there is nothing you can do to get is resolved. (if you change your name again u get triple chat)

**Comment by Porcotron** [comment]
That's sad ;-;
