### ISSUE TITLE
A Grave Mistake - Tomb Entrance Denial

### ISSUE THREAD

**Issue by AshAngg2000** [Wynncraft/Issues#6510]
So I did most of the quest before the fix and got all the dialogue pieces, and then when I played through each one again I didn't get any dialogue. And now it won't let me through into the tomb...

**Comment by Trixter313** [comment]
Are there any messages that pop up in chat? Also, what does it day in your quest book for the quest?

**Comment by AshAngg2000** [comment]
When I try to enter it says "Stay away" and my quest book says "I told you to stay away"

**Comment by Gamzeemakara21** [comment]
I have this same problem. I've gone through all 4 steps with a friend, he was able to go through the door, and i wasn't. Any way i could reset my quest status or fix it at all?

**Comment by AshAngg2000** [comment]
Leaving the area and returning fixed the issue.
