### ISSUE TITLE
Lost legendary wand

### ISSUE THREAD

**Issue by benjaminqp479** [Wynncraft/Issues#6511]
Well, long story short, the item identifier glitched. I was identifying this legendary wand i found from grinding and my inventory was full. When i identified it, it said, you did not have enough space in your inventory so I dropped your items on the ground. But when I through my spare emeralds out, I didn't pick it up. I walked around for a few minutes and couldn't find it.

**Comment by benjaminqp479** [comment]
<img width="1952" alt="screen shot 2016-10-29 at 10 09 35 pm" src="https://cloud.githubusercontent.com/assets/22455074/19834218/9330baae-9e24-11e6-8a51-2946c24b7027.png">

**Comment by benjaminqp479** [comment]
I am not asking for a refund I just want wynncraft to upgrade their crappy system

**Comment by benjaminqp479** [comment]
fix*

**Comment by thecoolkogut4** [comment]
weird, identified something yesterday with a full in and it dropped on the ground and I picked it up.

**Comment by LordHelmchen98** [comment]
If I identify stuff in Troms with a full inventory this happens to me as well. It just doesn't spawn next to me but higher and therefore it gets to a floor above me.

**Comment by 1b8** [comment]
That happened to me too, with one of the rings from the Hallowynn quest. You should mention that it was in Troms.

Someone said sometimes they spawn on the second floor of the building.

**Comment by Moe-Ronickah** [comment]
1b8 has the general idea of what is really happening.  When an item is identified, and your inventory is full, the identifier actually has to pass the item to you through a mechanic that quite literally drops the item to you.  This is the only way that MC works, at this time.  So, when the item falls from above you, if your inventory is full, then it is possible for the item to land above you, also.  You can see this effect when you complete a dungeon and the rewards fall from above you.  At this time, this is an MC mechanic and we can't change it.
