### ISSUE TITLE
I have lost items / Halloween context

### ISSUE THREAD

**Issue by shov** [Wynncraft/Issues#6512]
In my explanations when I talk about monsters and ghosts I mean Halloween decorations in lobby.

Some time ago (yesterday) I logged out leaving several items from ghosts and monsters dummies on my character in lobby (including armor, helmet, pants, boots and few items in inventory)..

Today I login and saw empty slots on my main character (1st Assassin) in places same of places I had items in lobby yesterday!

Another my observation is I lost the minecraft Skin as if I newbie who had no any armor item never. And when I got some helmet (or pants =) dont remember) from the bank, I got screen reload and my minecraft skin is back..

Sorry bad eng.. In game my nickname is Shov4ik

**Comment by thecoolkogut4** [comment]
sorry but there is a strict no refund policy.

**Comment by Moe-Ronickah** [comment]
This really sounds as if you had a glitch happen between you and the server, because your skin got reset, if only temporarily.  Please, in the future, if you find anything in the lobby, get rid of it before you go into a game world.
