### ISSUE TITLE
"A grave mistake" teleport bug

### ISSUE THREAD

**Issue by dafireflame** [Wynncraft/Issues#6513]
i started the quest and got passed the point where it reads the first 4 dialog 
Once there was a man,
who helped the spirits pass on,
however he was still
mortal.

which i was then taken the coordinates of 287 77 -561 (not exact coordinates) i then proceeded towards the area with coal blocks and got the message "stay away" however it would teleport me into a wall which gets created after i entered and the wall pushes me back toward the coal block and created a loop of me teleporting into the wall and being pushed towards the coal blocks.

i did manage to escape from the loop due to another player entering the area.

also i was on world 1

**Comment by dafireflame** [comment]
also i looked up a video on the quest and it it allows the person in the video to be teleported when they go towards the coal blocks after they got the first 4 dialog

so i think my quest is bugged as well

**Comment by dafireflame** [comment]
i also went back to all 4 dialog areas to see if i missed one but they all didn't do anything new

**Comment by Trixter313** [comment]
Sorry for the late reply, what does it say in your quest book for the quest?

**Comment by dafireflame** [comment]
" i told you to say away" i think

**Comment by Moe-Ronickah** [comment]
1: You are certain that you got all four quest dialogues?
2: Did you try changing servers when you got caught in that loop?
I can't remember another instance of this, so I'm hoping that is was just a one-time server bug.

**Comment by dafireflame** [comment]
1: yes 
2: yes, it took me to the world spawn where you start the tutorial 

I also got caught in it agin but someone was there so they triggered the tripwire and i got out. 
I also got someone to help test it by myself opening the door with the tripwire and they walked in (they had not done all 4 dialogs) which got them stuck in the loop. 
Dont worry i let them out straight after XD

**Comment by dafireflame** [comment]
Oh and the test was on another world but i cant remember which one

**Comment by dafireflame** [comment]
I have not tried this bug since then which was a day after i first posted on this so i do not know if it still occurs

**Comment by Moe-Ronickah** [comment]
What version of MC are/were you playing on?

**Comment by dafireflame** [comment]
ok it looks like i can now get inside of the door now so i cant test if the bug still happens but thanks if you looked into it.
not sure why i can now get in but thanks guys for trying to help

**Comment by dafireflame** [comment]
...
okay...
so i continued through to the final room using the key to enter the door but NOW i'm stuck in here...
i had a floor glitch where you get stuck in the ground and cant get out.
the dialog happened, 
"[1/2] ???: you were warned not to enter this forsaken place.
[2/2] ???: But since you have made it thusfar, I suppose I shall show you the truth..."
but i didn't get teleported and now i'm stuck in this room with no way out and apparently infinitly invisible

**Comment by Moe-Ronickah** [comment]
At this point, try changing classes several times.  Every time that you change classes, MC checks your position, and Wynn always brings a player in game slightly above the registered position.  See if that will, maybe, trigger the cut scene.  You can also try changing servers several times.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
