### ISSUE TITLE
Guild promotion glitch

### ISSUE THREAD

**Issue by CallMeSpoonZ** [Wynncraft/Issues#6514]
So im in this Guild (Perihorn)
and there is this glitch which is bugging me and my leader
for some reason i cant be promoted in the guild or kicked or leave
its really weird i think I've tried everything.
Please just reply if you think you know the issue or atchually have this issue yourself.
Thanks

**Comment by thecoolkogut4** [comment]
since you changed your name, you get doubled in the guild therefor resulting in you not being able to be kicked/promoted/demoted and having double chat. you can't currently do anything to resolve this glitch.

**Comment by CallMeSpoonZ** [comment]
wow well that sucks

**Comment by CallMeSpoonZ** [comment]
do you know when they will fix this?

**Comment by thecoolkogut4** [comment]
probably with the refractor update in a couple of months :/

**Comment by CallMeSpoonZ** [comment]
well fuck. thanks anyway
