### ISSUE TITLE
Resource Pack not Loading

### ISSUE THREAD

**Issue by GreenNope** [Wynncraft/Issues#6515]
I am running Minecraft 1.10, with the latest launcher. My resource pack will not load. I have it enabled on this server, and tried everything [here](https://forums.wynncraft.com/threads/cant-play-wynncraft-because-of-the-pack-heres-how-to-fix.98023/).

**Comment by Surra-1** [comment]
If you are still having resource pack related issues, I would suggest you switch to version 1.8.9

**Comment by Trixter313** [comment]
Let us know if switching to 1.8.9 fixes the issue. Thanks!

**Comment by GreenNope** [comment]
Sorry, it's still not working when i switch to 1.8.9.

**Comment by Moe-Ronickah** [comment]
Is it working, now?  The RP has been "a bit" slow, lately, for everyone.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
