### ISSUE TITLE
Items Dissapearing gitch/bug

### ISSUE THREAD

**Issue by darthcharlus** [Wynncraft/Issues#6516]
Today while i was on Wynncraft numerous items have glitched out of my inventory for reasons beyond my knowledge. The first was a brand new black horse that disappeared after i rode it then put it into my inventory. I had just bred it and this was my first time using it. The other main item was a tier IV thunder powder i had had for some time in my inventory. I was journeying from Nemract to Nessak to do the frostbitten quest, and leveled up to 48 along the way. I was just about to put the powder on my new legendary when i realized it wasn't in my inventory or my bank. Other missing items include: 2 emerald blocks, a boat, and a depressing bow. is there anything you could do to get these items back and/or fix this bug for other people? my in game username is darthcharles with no caps. I hope this bug is fixed soon.

**Comment by LordHelmchen98** [comment]
Well as Im not a staff-member I dont know if that can be fixed and I cant really ask, but unfortunately I have to tell you there is no way to get your items back as Wynncraft has a strict norefund policy.

**Comment by darthcharlus** [comment]
aww... well i hope the glitch is fixed anyways.

**Comment by Moe-Ronickah** [comment]
I'll take a guess that your drop key is "Q".  If it is, please change it to something far away from your movement keys.  [I use "Delete".]
