### ISSUE TITLE
Green Skinned Trouble is Broken

### ISSUE THREAD

**Issue by RareDiamondOcean** [Wynncraft/Issues#6517]
Everything in the quest is fine until you get to the puzzle in the cave. And yes, I did do it twice to where the hole opened. When I dropped into the hole, it teleported me around 5 blocks up, all it said was "null." I couldn't get out unless I used teleport, so I did. I hopped servers seeing if it was just a server issue, on my sixth server I decided to stay in the hole until the pistons closed on me. It glitched my head into the block that closes the hole, so I was stuck. I used /hub to get out and on the next server, it teleported me to the beginning of the game, thankfully with all of my items. I went all the way back to where it was, but the same glitch still occurred.

**Comment by KitiNek0** [comment]
Same thing happening to me but me and someone else are stuck together in the hole, scrolls won't even work

**Comment by Trixter313** [comment]
Is the issue still happening?

**Comment by KitiNek0** [comment]
Me and my friend got through it. Can't fully remember but im pretty sure we just relogged and it teleported us

**Comment by RareDiamondOcean** [comment]
No, the whole thing was my mistake. I read the wiki and I went ahead of the
quest, so it wouldn't let me proceed.

**Comment by Trixter313** [comment]
Glad to hear you both got through it!
