### ISSUE TITLE
Missing textures in server ressource pack

### ISSUE THREAD

**Issue by Cedd00** [Wynncraft/Issues#6519]
Hey guys,

Two days ago it began. A few textures just disappeared right infront of my eyes. It began with fences, and went over to wild growing grass.
Now it shows me die pink and black squared debug texture of missing blocks.
Fences are alright again by now while I'm not using another ressource pack but the grass is still bugging.

I already deleted the legacy and every other file @ %appdata%/.minecraft/server-ressource-pack   ...
What can i do to fix this?
![2016-10-31_09 24 40](https://cloud.githubusercontent.com/assets/23164430/19851986/ee3d48da-9f60-11e6-8072-6fab1988827a.png)

**Comment by Surra-1** [comment]
Try to delete the wynncraft server resource pack, and use version 1.8.9.

**Comment by Cedd00** [comment]
With 1.8.9 it works just fine, but it's annoying to change the version every time I want to change the server. There must be a better solution to fix this issue.

**Comment by Surra-1** [comment]
To fix it the other way, remove the server resource pack once again. Launch the game on your preferred version. Open the new generated pack with winrar, then locate and delete the tall_grass.json file from the blockstates folder.

**Comment by Cedd00** [comment]
Okay the bug with the minecraft:tallgrass blocks is fixed but the fence posts are still buggy. but thanks for your help anyways :)

**Comment by Cedd00** [comment]
Wow... But now there's something else fucked up... 
![2016-10-31_13 20 16](https://cloud.githubusercontent.com/assets/23164430/19853996/dc3060da-9f6c-11e6-97f2-16d61f332ad5.png)

**Comment by ItsYourPlay** [comment]
Than I think you must play on the 1.8.9 and must change everytime your version sry for that.

**Comment by Trixter313** [comment]
You can create two profiles in the launcher to open different versions if you'd like to make things easier as well.
