### ISSUE TITLE
help me I block in the wall

### ISSUE THREAD

**Issue by adamcar** [Wynncraft/Issues#6520]
Pls help, my possition : 1438 77 -1977     Nickname : adamcar

**Comment by Surra-1** [comment]
If you are 100% stuck, you have 2 options.
1: Use a tp scroll.
2: Make sure you are above 5 soulpoints, and type /kill.

**Comment by thecoolkogut4** [comment]
you can do everything that surra said, plus a 3rd option which is to spam /class, everytime you class you go up 1/2 blocks. if you do this enough you will reach the top of the mountain/house/blocks
