### ISSUE TITLE
pet rename

### ISSUE THREAD

**Issue by TwilightGalaxy** [Wynncraft/Issues#6521]
hello, i have vip rank and can not rename pet. when i tried /rename it said i did not donate.

**Comment by Surra-1** [comment]
I believe you need to buy the name tag to rename pets/horses.

**Comment by thecoolkogut4** [comment]
type /buy and click on the name tag. if you have enough gold coins it will buy it, if not you would have to wait in till the new update to be able to rename pets/horses.
