### ISSUE TITLE
respawn position

### ISSUE THREAD

**Issue by TwilightGalaxy** [Wynncraft/Issues#6522]
i was on my hunter account in sand swept dungeon, and before i enter the boss room i switched to my archer in Detlas to make a trade. My archer somehow died in detlas, but i got respawned in front of sand swept dongeon where my hunter class was, so i had to let the mob kill me and it get me back to detlas again.

**Comment by JackyKit123** [comment]
it happens becuz when you enter a dungeon
the server registers your respawn location to be outside the dungeon
so as if u die inside dungeon, you would spawn in front of the dungeon
the respawn location wont be reset unless
1. you completed the dungeon
2. you died
I think the case switching class should also clear the registration but it would be hard to re-register when you switch back
so my suggestion is to finish the dungeon before you swap class or simply DON'T DIE

**Comment by Moe-Ronickah** [comment]
"so my suggestion is to finish the dungeon before you swap class" is exactly what we have been suggesting for this for quite some time.  If you enter a dungeon, don't change classes.
