### ISSUE TITLE
Riding/sailing bug!

### ISSUE THREAD

**Issue by LuxiiLux** [Wynncraft/Issues#6523]
Well, when I'm riding a horse or I'm in a boat, it does not go where I should be. It's a problem I have had in a long time now! But now it gets out of hands. I don't know if anyone has the same problem as me.. Can someone help me please??

**Comment by Surra-1** [comment]
Seems like a 1.10 bug, if you are in 1.10 or 1.9 try to use 1.8.9

**Comment by thecoolkogut4** [comment]
as surra said, wynn is at it optimal performance when using version 1.8.9, try switching versions and see if it helps.
