### ISSUE TITLE
Could not connect to default or fallback server

### ISSUE THREAD

**Issue by DarkBacca** [Wynncraft/Issues#6524]
Ever since yesterday, I keep getting this message while trying to login onto Wynncraft. I'm on a mac, but on my PC, wynncraft works fine. 
![screen shot 2016-10-31 at 12 13 16 pm](https://cloud.githubusercontent.com/assets/20028693/19861607/96446be2-9f63-11e6-927f-a2a686bb3de9.png)

**Comment by Surra-1** [comment]
Try to connect with the ip play.wynncraft.org, or play.wynncraft.net
I think that will help.

**Comment by DarkBacca** [comment]
It doesn't, but thanks anyway

**Comment by thecoolkogut4** [comment]
try fix.wynncraft.com can you connect to other servers or is it just wynn?

**Comment by DarkBacca** [comment]
just wynn

**Comment by DarkBacca** [comment]
seems to be working now tho, so closing this thread
