### ISSUE TITLE
Aldorei's secret Part 1

### ISSUE THREAD

**Issue by desservaux** [Wynncraft/Issues#6526]
I didn't get the rewards at the end of the quest. I chose to give the boots to Kansard. I hope you'll fix the bug soon, thanks in advance.

**Comment by thecoolkogut4** [comment]
what happens if you talk to one of the other npcs? what does your quest book say?

**Comment by desservaux** [comment]
It says I've finished the quest but I type /fixquests and it gave me the item so I assume the bug is fixed?
