### ISSUE TITLE
Teleporter in a quest dont work

### ISSUE THREAD

**Issue by ItsYourPlay** [Wynncraft/Issues#6529]
Today I started the quest Shattered Minds and I wanted to go into the cave where I need to go (-1160 -5008) and after I entered the cave I wanted to take the teleporter that I need to do the quest (-1147 -5112) but when i go into the teleporter I dont get teleported and I dont know why. I always tryed to relog or start minecraft again but it doesnt help.
I hope someone can help me.
Ingamename: ItsYourPlay

**Comment by Inklin235** [comment]
Same issue with this quest Teleporter, we tried multiple worlds but nothing worked.

**Comment by thecoolkogut4** [comment]
I did this quest yesterday and it worked perfectly. try running in circles, walk out then back in, and jump around to try to get tped.

**Comment by nic1998** [comment]
Doesn't work for me either, I tried moving in it and changing servers,

Here's a video (sorry for how dark it is) :  [https://www.youtube.com/watch?v=QU4DIn0ePNU&feature=youtu.be](url)

Hopefully this gets fixed soon. :+1:

**Comment by Gjef** [comment]
Got the same problem

**Comment by ItsYourPlay** [comment]
I hope we dont need to wait too long

**Comment by ItsYourPlay** [comment]
IT WAS FIXED

**Comment by Trixter313** [comment]
Glad to hear!
