### ISSUE TITLE
A Grave Mistake bug

### ISSUE THREAD

**Issue by Robox25** [Wynncraft/Issues#6530]
Thx for fixing it i could finally get text 1/4 to 4/4.I can open that big door at X=283 Y=75 Z=-573 but i cant enter it.It just tells me to "Stay Away".It tryed to do all the text part again but its not working and text isnt showing.

P.S.
Thx for your time.

**Comment by thecoolkogut4** [comment]
did you try to switch servers?

**Comment by Robox25** [comment]
yes stuck like this for 3rd day so i just wrote a report

**Comment by thecoolkogut4** [comment]
try to completely leave the area (go to the front of the twain house) then walk back slowly, don't sprint or use any spells

**Comment by Robox25** [comment]
tryed
