### ISSUE TITLE
Skill Points Bug

### ISSUE THREAD

**Issue by Xanderkh** [Wynncraft/Issues#6531]
![image](https://cloud.githubusercontent.com/assets/23178954/19874489/cc13bdb0-9fac-11e6-91c4-4ec8f9a141b8.png)

The Image says all...

**Comment by thecoolkogut4** [comment]
I don't get it, what is the picture showing?

**Comment by Xanderkh** [comment]
The picture is showing I have 64 skill points, but when i pass the mouse out he says i have 73 skills points

**Comment by LordHelmchen98** [comment]
It's fine. You have 73 skill points but Minecraft is not made for stacks with more than 64 items so wynncraft can't make it a higher number. That's why you have 73 points but your compass only shows 64.
