### ISSUE TITLE
Server restart, Items gone 

### ISSUE THREAD

**Issue by J3wdice** [Wynncraft/Issues#6532]
I was at a bank. and I saw the server restarting in 10 seconds, so I went to go in my chest get my 30 EB to buy some health potions for the hard quest tower of ascension. I log back into the server and my EB were not in my inventory nor my ender chest.

**Comment by thecoolkogut4** [comment]
if you are looking for a refund, that's not gonna happen as the server has a strict no refund policy. this is probably because *dont know if it actualy works this way but* you took the stuff out right after banks saved then players data saved. you took it out in between the two and you lost it

**Comment by J3wdice** [comment]
I put 1 eb in my inventory as server restarted and lost all the 30 eb I literally have no money now o_o. Well if anyone wants to be kind then you can /msg j3wdice

**Comment by Trixter313** [comment]
To prevent something like this from happening again I'd suggest changing to another world when you first see that the current one is restarting.
