### ISSUE TITLE
Hallowynn quest -Getting stuck in church cutscene

### ISSUE THREAD

**Issue by PearlescentMoon** [Wynncraft/Issues#6534]
I've tried twice now, and to the same result. I get to the place where '???' starts telling me the 'truth'. It gets to the church cutscene, and nothing happens; I'm just stuck in an invisible box, forcing me to have to /kill my character and lose soul points to get out of it. It won't complete the quest due to this and I'd have to walk through the giant door once again and replace the key to the crypt.

Private video here of the glitch: https://www.youtube.com/watch?v=URjn9G41B-U&feature=youtu.be

*As I was writing this, another player joined after 10 minutes, and it proceeded onto the next vision. Unfortunately, it then glitched/lagged and kicked me for 'flying'. Joined again, and now I'm stuck somewhere else. >_<

Is there anything that would trigger (or rather not trigger) all this to occur?

**Comment by LordHelmchen98** [comment]
In order to show that video to others you have to set it as unlisted. If it's private only you are able to see it.
Unfortunately I can't help you with your problem as it worked for me without any problems.

**Comment by thecoolkogut4** [comment]
completely walk out of the area (to the front of the twain house) and try to walk back with no spells/sprint.

**Comment by PearlescentMoon** [comment]
Tried it again 9 hours later and it finally worked. :) Not sure what was up with it, but after 4 tries, it's a go. ^-^
