### ISSUE TITLE
Halloween quest Grave Mistake Telling off the Truth issue

### ISSUE THREAD

**Issue by Sapphire-4ever** [Wynncraft/Issues#6535]
when i get to the part were it tells you the truth it froze and wont show me anything so my character is stuck looking at the house floating in mid air. I am not lagging and have relogged which didn't work please help.
My username = Sapphire_4ever

I can also still use spells and i Have not tried using a tp scroll but i don't want to lose my progress.

**Comment by Trixter313** [comment]
If you're stuck and moving around/relogging doesn't get you out the only other way would be to use a scroll or /kill.

The quest was recently patched and fixed issues similar to this. Let us know if everything goes smoothly the second try. Thanks!
