### ISSUE TITLE
Item incorrectly textured

### ISSUE THREAD

**Issue by Cheetah1** [Wynncraft/Issues#6536]
The Warrior weapon Hunter is textured as a Stone Brick Slab, instead of its weapon (I will get a picture soon)

**Comment by LordHelmchen98** [comment]
I guess you are playing in 1.9 or higher. As Wynncraft was made for 1.8.9 and the resource pack as well you should try to use 1.8.9 and see if its fixed if you use that version.

**Comment by Cheetah1** [comment]
Yes, I am using 1.10.2, I can try it out
