### ISSUE TITLE
Bugged account

### ISSUE THREAD

**Issue by FalseGod01** [Wynncraft/Issues#6541]
I stopped playing on the server like two years ago so my old account was bugged and I deleted it and created a new one. But after playing a while and a view server restarts I landed in the room where a Player gets teleported to after a big update with my old account. It worked again but it was only lvl 12 or 14 and my new one was lvl 22. Now both of them are mixed up. I got some items from the new and from the old account. Also I'm still lvl 22 but my quests were set back to the old account. It's not a big Problem for me because I didn't doo that many quests and I can get the items back somehow but it's still a huge bug.
(sorry for the bad english) :)

**Comment by Moe-Ronickah** [comment]
Please give me the Minecraft and Wynncraft names of both of them and I'll see if we can find an explanation.

**Comment by FalseGod01** [comment]
I created them both with the Minecraft account FalseGod01.

**Comment by Moe-Ronickah** [comment]
RESOLVED.  Thanks for bringing this to our attention.
