### ISSUE TITLE
Unable to remove item skin

### ISSUE THREAD

**Issue by tyarrow1** [Wynncraft/Issues#6542]
I just got an item skin by combining my old VIP items, and it seems that I am unable to disable it. Whenever I click the option again for the skin again (like disguising) the item skin doesn't disable, nor is there a chat message. After a few minutes, the message will repeat that I set the skin.

I personally find wielding a skewered steak hilarious, but others (especially in 1.8) might be annoyed by this.

**Comment by Trixter313** [comment]
Fixed in recent patch https://forums.wynncraft.com/threads/1-14-2-wynncraft-patch-1.163111/
