### ISSUE TITLE
Can't play in 1.9.x

### ISSUE THREAD

**Issue by TwilightGalaxy** [Wynncraft/Issues#6544]
Hello after the update some item skin is not able to be viewed in 1.8.x, so i tried to play in 1.9.x how ever, i tried 1.9, 1.9.4 and both of them i am not able to log in the server. It will say something like "Could not connect to default or fallback server,please try again later: java.net.ConnectException"
my 1.8.x works fine, but not 1.9.x
pls help

**Comment by Trixter313** [comment]
Hmm, are you still experiencing this issue?

**Comment by ColinRioux** [comment]
There has been no response in at least 30 days. If your issue still persists, please make a new issue (while checking if there are no duplicates first).
