### ISSUE TITLE
Cant Ride My Horse

### ISSUE THREAD

**Issue by dumbetan** [Wynncraft/Issues#6545]
Every time I try to ride my horse I crash io.netty.handler.codec.DecoderException: IntArray with size 1 is bigger than allowed 0

**Comment by LordHelmchen98** [comment]
What's your mincraftversion? Normally I would recommend 1.8.9 since that's the version wynncraft was originally made for but now that they implemented those item textures I guess it's best to play in 1.9.x

**Comment by Trixter313** [comment]
1.8.9 is still the most functional version, as horses are still broken in 1.9+

Let us know if using 1.8.9 resolves the issue. Thanks!

**Comment by ColinRioux** [comment]
Horses has been fixed as of this month for 1.9+. Also:

It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
