### ISSUE TITLE
My VIP+ particles and I'm not receiving mob totems

### ISSUE THREAD

**Issue by Ademic** [Wynncraft/Issues#6547]
![2016-11-01_20 39 46](https://cloud.githubusercontent.com/assets/23205293/19916146/a732f560-a074-11e6-891c-abf9443f8fb9.png)
I have the VIP+ rank but i still get this message

**Comment by LordHelmchen98** [comment]
For issues related to realworldcurrency you should send a mail to support@wynncraft.com.

**Comment by thecoolkogut4** [comment]
I'm pretty sure, not 100% but with the new update you don't automatically get particles with the rank.

**Comment by Ademic** [comment]
I got the rank before the update, does that mean that I lost all of my previous particle effects?

**Comment by Trixter313** [comment]
I still have my previous particles, it's probably just a weird issue you're experiencing. Make sure to email support so they can help resolve it.
