### ISSUE TITLE
Bomb glitch

### ISSUE THREAD

**Issue by Trasque370** [Wynncraft/Issues#6548]
I just bought 16 xp bombs and 24 shout bombs. At first on the server, I had my shouts, and then the server had that massive shutdown (ask salted, he was the only one on). then I went into my bomb thing in my compass thing, and it keeps saying "you don't have any of that item type". I am getting frustrated and didn't know what else to do. PLZ FIX

**Comment by LordHelmchen98** [comment]
For issues related to realworldcurrency you should send a mail to support@wynncraft.com

**Comment by thecoolkogut4** [comment]
send a email to support (email mentioned above) with your ign, transaction ID, and a explanation of what happend
