### ISSUE TITLE
Missing Curse

### ISSUE THREAD

**Issue by KTricker** [Wynncraft/Issues#6549]
Not sure if this is the right place however everytime i load wynncraft enhanced modpack and join the server. i recieve and error message on the screen saying "missing curse please use curse"
![image](https://cloud.githubusercontent.com/assets/23204073/19925850/1a020d90-a135-11e6-9abe-2ce91bfeeba8.png)

**Comment by MrRedCrack** [comment]
Imo this isn't the best place for you to report modded stuffs like this, my suggestion is posting this to the creator's website.

**Comment by thecoolkogut4** [comment]
this does not belong what so ever here. github is for reporting bugs on official wynncraft made things which the mod pack is not

**Comment by KTricker** [comment]
ok thx
