### ISSUE TITLE
The shop is still bugged for me

### ISSUE THREAD

**Issue by facelys** [Wynncraft/Issues#6550]
When i try to buy Hero the site just refreshes and deletes everything that i've written.
I have tried to pay with different currencies because i thought something might be bugged with SEK, but it still refreshes when i use Euro or USD :/
Help pls

**Comment by LordHelmchen98** [comment]
Are you sure all scripts are working properly? If not try ctrl+F5 and try again.

**Comment by facelys** [comment]
I've not checked the scripts but i have tried ctrl+f5 :/
i dunno what to doooooo :,(

**Comment by facelys** [comment]
Nevermind, it randomly started working! :)
