### ISSUE TITLE
Bug with the Treasure Guardian in "Beneath the Depths"

### ISSUE THREAD

**Issue by WoodWarriorJan** [Wynncraft/Issues#6552]
The Treasure Guardian is stuck in a wall when I use the Bash spell or the Uppercut spell on my Warrior.

**Comment by JackyKit123** [comment]
Warrior spells pushing mobs thru wall is a known bug
Trying doing /class or relof

**Comment by Moe-Ronickah** [comment]
@AckroWynn , any fix for this?  I thought that all of the boss areas had been pretty well barricaded.

**Comment by AckroWynn** [comment]
@Moe-Ronickah That's for the newly made bosses ;D
I'll see what I can do!
