### ISSUE TITLE
Map missing API key?

### ISSUE THREAD

**Issue by Louis-D** [Wynncraft/Issues#6553]
https://gyazo.com/07653ad2c0724b2ff4fe84ad37f18771
https://gyazo.com/d468a592b1aa9a1b976ebbf9b9a151e6

**Comment by Terraphax** [comment]
i have the same issue

**Comment by JackyKit123** [comment]
I can confirm this happens on me till now
But I believe is an issue of google

**Comment by Moe-Ronickah** [comment]
Clear your browser cache and let us know what happens.

**Comment by Villageacules** [comment]
Due to lack of activity on this issue, I'm closing. It's been 30+ days.
