### ISSUE TITLE
Cant See the New Shop

### ISSUE THREAD

**Issue by piglover69** [Wynncraft/Issues#6554]
When I go to the Shop It Tell me this  How Dose one Fix this

![](https://i.imgur.com/DPO0Zg6.png)

**Comment by MercyGRID** [comment]
Clear your cache by pressing Ctrl and F5.

**Comment by Enigmatia** [comment]
Please also ensure that you Chrome is fully up to date by visiting chrome://help/ via your address bar/omni bar

**Comment by piglover69** [comment]
Thanks MercyGRID You helped alot
