### ISSUE TITLE
Boat hopper eats items

### ISSUE THREAD

**Issue by WunchYT** [Wynncraft/Issues#6555]
I just got "The Divide" (dagger) and turned lvl 30 so I decided to take a boat to Selchar from Nemract and do the christmas quest. I accidentally threw my Divide in the boat hopper instead of the Selchar boat pass. It gave me the captain's message that I hadn't used a boat pass, but I was never given my item back.

**Comment by redfoxkit** [comment]
Fairly certain Wynncraft has a no refund policy so it's not abused. Meaning you cannot get your item back. It happens to a fair amount of people, but you'll have to move on.

**Comment by WunchYT** [comment]
Ok, thanks.
