### ISSUE TITLE
New textures bug

### ISSUE THREAD

**Issue by OMGitsTomix** [Wynncraft/Issues#6556]
I've seen many other threads with people saying that they can't remove their gear skin,that's one problem,second problem is that my texture pack is really bugged,Its bugged only on 1.9+,(I've tried 1.9,1.9.4,1.10 and 1.10.2,every time I switched version I also deleted and downloaded the server texture pack again)Sometimes I get the new 3D textures on skins even though I didn't got them from crates,they just randomly appear as my weapon skin.If you think that you can help me fix my texture pack please tell me how,thanks.And as you can see on this thread,there are more people then me with the same problem ( https://forums.wynncraft.com/threads/162479/ )

**Comment by Trixter313** [comment]
Are you still experiencing this since the recent patch?

**Comment by Moe-Ronickah** [comment]
RESOLVED
