### ISSUE TITLE
/kill issues

### ISSUE THREAD

**Issue by ConSavvy** [Wynncraft/Issues#6558]
While on the Seaskipper, I used /kill because I went to the wrong area, but it made me go to the starter area.... though my character was a level 75.
![2016-11-02_19 29 30](https://cloud.githubusercontent.com/assets/22406565/19954145/db7effc6-a132-11e6-9c6c-7476d430e2c3.png)
![2016-11-02_19 29 30](https://cloud.githubusercontent.com/assets/22406565/19954146/e09e5b28-a132-11e6-8d41-85915175ffa0.png)

**Comment by thecoolkogut4** [comment]
the seaskipper is off map, because of that when you /killed you got tped to the closest "city" and the closest one was the tutorial
