### ISSUE TITLE
Keystone Guardian Too High Level...?

### ISSUE THREAD

**Issue by StrangeOne101** [Wynncraft/Issues#6559]
I believe the Keystone Guardian in the Underground Ruins dungeon is too high for the level the dungeon is meant to be at. At present, it has 98,480 health, which is ridiculous for a level 60 mob in a level 54 dungeon. On top of that, it regens around 5k health at a time. As I am writing this, I am a level 64 archer that can survive fine in level 70-75 areas and yet I can only deal 6k damage before it regens 5k. In the light forest, you can find key guardians with 20k health and their regen is nothing on this keystone guardian (I can kill them fine), so I'm sure this is just a balancing bug that has been looked over.

Thanks!

**Comment by WoodWarriorJan** [comment]
I think these Dungeons are made to do them together with some other people. :)

**Comment by StrangeOne101** [comment]
Turns out I was mistaken on the purpose of the guardian. I thought you were meant to kill it for a key, but you are just meant to lead it somewhere. My bad.

Issue closed.
