### ISSUE TITLE
Invincible Zombies from Totem

### ISSUE THREAD

**Issue by TheGamingReaver** [Wynncraft/Issues#6560]
I decided to try out Mob Totems for the first time and dropped one at -54 70 -1882. All was going well, just killing lots of zombies and a few infested pit key guardians.After 5 minutes the totem ran out and for some reason either some of the mobs left over from the totem or something became impossible to damage. They would keep following me as long as I stayed within sight. They also no longer damaged me. I assumed it may have just been a glitch that left behind basically ghosts of mobs only I could see but when I walked them to Detlas guards tried and failed to kill them plus a couple other players thought they were my pets or something. They couldn't hurt the zombies either. I decided the best course of action was to relocate them to the lava pits near the nether portal for them and everybody else's sake. They didn't die from that either but they  were swimming around down there having a blast. I then accidentally stepped in the portal and when I got back I was either in the wrong server or they despawned.
![2016-11-03_02 14 32](https://cloud.githubusercontent.com/assets/8367700/19957636/b342d38e-a16e-11e6-8a8f-d96761b18cc9.png)
![2016-11-03_02 16 59](https://cloud.githubusercontent.com/assets/8367700/19957639/b513815e-a16e-11e6-958c-6a7f850c8d90.png)
![2016-11-03_02 21 24](https://cloud.githubusercontent.com/assets/8367700/19957632/a8b34c00-a16e-11e6-9c23-a9a26a5de0c5.png)

**Comment by thecoolkogut4** [comment]
if no one is in the area type /class, wait 5 seconds then go back to despawn the mobs. you need to do that after every totem to get rid of the ghost mobs.

**Comment by TheGamingReaver** [comment]
That seemed to work thanks. Still, I hope it gets fixed at some point soon since if anyone else is near by they won't despawn plus that despawns any loot on the ground.

**Comment by Trixter313** [comment]
Can you reproduce this now? There is a patch rolling out now that might have fixed it.

Let us know, thanks!

**Comment by thecoolkogut4** [comment]
this got fixed after the latest patch
