### ISSUE TITLE
Stuck in cutscene while quest grave mistake

### ISSUE THREAD

**Issue by Grauly** [Wynncraft/Issues#6562]
I am in the final stage of a grave mistake and the cutscene ment to play now dosnt play, i am stuck looking at the church.
hope you can fix that 
-Grauly

**Comment by Grauly** [comment]
i did it again on a other server and it didnt work eather, stuck again. cant complete the quest...
help me.

**Comment by thecoolkogut4** [comment]
walk back out of the area, then slowly walk back in

**Comment by Grauly** [comment]
how can i walk out of a barrier cage?
it happend while inside the cutscene at church final stage... I did already kill me and started the cutscene again, but same happend.
what now?

**Comment by Grauly** [comment]
how can i walk out of a barrier cage?
it happend while inside the cutscene at church final stage... I did already kill me and started the cutscene again, but same happend.
what now?

**Comment by Grauly** [comment]
trying again now with a higher render distace, maybe it works now

**Comment by Grauly** [comment]
it worked. i dont know what i did wrong, but maybe its the render distance. but now everything worked out. is the a minimum render distance espcely for wynn?

**Comment by Trixter313** [comment]
I was most likely just an odd one time issue, possibly due to some broken redstone on a specific world.
