### ISSUE TITLE
Climbing Helmet lost

### ISSUE THREAD

**Issue by robinkip4** [Wynncraft/Issues#6563]
I was the quest zhight island doing and when I had the Climbing Helmet required but I have not in my bank or my inventory him so I can no longer continue with the quest, what do I do now?

**Comment by LordHelmchen98** [comment]
Have you tried /fixquests? If that doesnt work and you havent stored it in another class Im afraid you have to get it again with another class because you wont get it back by staff due to the strict norfeund policy.

**Comment by robinkip4** [comment]
tnx man i forgot the /fixquests command
