### ISSUE TITLE
Underworld Crypt Dungeon

### ISSUE THREAD

**Issue by SpeederSam** [Wynncraft/Issues#6564]
I (SpeederSam) am working to complete the crypt dungeon and the third survival platform will not spawn the mage. I am stuck on the platform, unable to proceed or go back. Please help. 
Thanks
SpeederSam

**Comment by SpeederSam** [comment]
I just tried jumping off the edge and it teleported me to the next area. Mage still would not spawn.

**Comment by SpeederSam** [comment]
Another update... After trying to proceed to the next area (fighting for token) barrier blocks completely stopped progress. The mobs spawned but I was unable to fight them due to the barrier blocks completely blocking the path. I will continue to try to glitch around and give any update. Please help

**Comment by SpeederSam** [comment]
Another update...I was able to get through... I think it may have been server lag and it wasn't registering as me trying to enter. The rest worked okay.

**Comment by Trixter313** [comment]
Glad to hear it all worked out!
