### ISSUE TITLE
Texture Bug

### ISSUE THREAD

**Issue by AwessomeInATux** [Wynncraft/Issues#6565]
After the store update, I just noticed Bob's Mythic Wand has a durability bar underneath the model. This is probably an easy fix, but I wanted to make it known, in case no one does already.

**Comment by thecoolkogut4** [comment]
some item textures go by the durability of the item, bobs mythic wand has X durability to display X texture. if you want to fix this go into mc version 1.9 (1.9 fixes some textures, but it breaks horses, and some other textures).

**Comment by Trixter313** [comment]
Also as long as the item functions properly it should be fine.
