### ISSUE TITLE
Underworld Crypt bug in last battle

### ISSUE THREAD

**Issue by Thaecrasis** [Wynncraft/Issues#6567]
I was trying Underworld Crypt for the first time, and when I got to the final battle I was completely stumped because I couldn't figure out any way to spawn the indicated units. There were invisible barrier blocks around each spawn point and no pressure plates (except on the Scout platform, but I still couldn't step on it). I looked at videos of people doing the battle, and I am unable to spawn the units the way it's done in player recordings.

Here's a video of the issue: https://www.youtube.com/watch?v=4OLwm9vs_ak

[Playing on Minecraft version 1.8.9 since I heard that was the best version to use for this server, and with optifine as the only mod.]

**Comment by Moe-Ronickah** [comment]
Whenever anything like this happens, change servers.  There are some bugs that crop up in MC that can cause this, but we don't know why.

**Comment by SirYe** [comment]
Yeah I second this issue... I tried twice and ran into this glitch both times.
Could not try again ( no more keys )
