### ISSUE TITLE
My rank isnt working

### ISSUE THREAD

**Issue by Arrowhawk5** [Wynncraft/Issues#6568]
I just purchased my new VIP+ rank about 2 hour ago and it still hasn't loaded! please help.

**Comment by thecoolkogut4** [comment]
for any issues regarding the store please email support at support@wynncraft.com with your IGN, transaction id, and an explanation of what is going on.

**Comment by LordHelmchen98** [comment]
It can take up to 24 hours to load your rank. If you still don't have it after 24 hours you should do what is explained above.
