### ISSUE TITLE
No VIP discount?

### ISSUE THREAD

**Issue by pemut** [Wynncraft/Issues#6569]
So im a VIP but I got no discounts. 
![screenshot 1](https://cloud.githubusercontent.com/assets/23249508/19990623/0b86862e-a1fd-11e6-9145-10a4b7a7dc64.png)

**Comment by thecoolkogut4** [comment]
i have the same problem but with a vip+, cleared cache, changed name again, reloaded the page, tried everything. just need to wait for them to fix it.

**Comment by Trixter313** [comment]
Are you still experiencing this issue? It works correctly for me. Remember that usernames are case sensitive.

Also, have you ever changed your Minecraft username?

**Comment by pemut** [comment]
It still is happening.
 I've never changed my username

**Comment by Moe-Ronickah** [comment]
I just checked and it's working.  How about for you guys?

**Comment by pemut** [comment]
Nope I still have the issue.

**Comment by Moe-Ronickah** [comment]
Some recent fixes went through.  @pemut , @thecoolkogut4 , still having this problem?

**Comment by thecoolkogut4** [comment]
yes, hero is still $100 for me when it's meant to be $50

**Comment by Moe-Ronickah** [comment]
OK, email [support@wynncraft.com](support@wynncraft.com), and they'll help you directly.  Just tell them what is happening, and what you want to purchase.

**Comment by DebugingLonks** [comment]
@Moe-Ronickah I had this, but uppon reloading it fixed

**Comment by Moe-Ronickah** [comment]
This problem is cause because we have changed the back-end vendor who we make sales through.  It nearly always requires action to be taken by [support@wynncraft.com](support@wynncraft.com), by hand, in order for it to be fixed.
