### ISSUE TITLE
Wrath of the mummy door not working

### ISSUE THREAD

**Issue by koohikoo** [Wynncraft/Issues#6570]
so I just started the wrath of the mummy quest. I had the pink wool and enter no problem. I then go through and think I figured out the code, does not work. so I go to the wiki to find out the proper code only to realize my code was right. this time when I press the buttons I noticed in the chat it says: "You don't have permission for this area." so I change worlds, leave the the server and rejoin, and restart Minecraft. nothing worked.

**Comment by thecoolkogut4** [comment]
"You don't have permission for this area." is because you are clicking it with your weapon. click the button with an empty hand and it should work.
