### ISSUE TITLE
0% Lag turned into 100% Lag

### ISSUE THREAD

**Issue by Lazeron** [Wynncraft/Issues#6571]
Hello Wynncraft Devs i recently have a problem with the servers when ever i go out to the wilderness it is very laggy and kicks me and when i try logging on it says i have to restart minecraft am not lagging on any other server and i can't enjoy the server or even the game i try restarting my  internet thinking the problem was my internet but no  i tryed logging on again and its still lagging i die everytime in the wilderness becuase of this so please fix this thank you 👍

**Comment by Moe-Ronickah** [comment]
Please lower your render distance.

**Comment by AscendedKitten** [comment]
It has been more than 30 days without a response to this issue. 
If your issue still persists, feel free to open a new one trying to describe it with as much detail as possible.
