### ISSUE TITLE
Help I'm stuck

### ISSUE THREAD

**Issue by SecretMermaid** [Wynncraft/Issues#6572]
I am stuck in the tip of the height limit, I was teleporting around so get to the time valley faster and now i'm STUCK. HELP.

**Comment by SecretMermaid** [comment]
I've tried the teleport to try and get out, ive tried to use there teleport scroll, ive tried exiting and relogging, and NOTHING IS WORKING.

**Comment by LordHelmchen98** [comment]
If you have more than 5 sou points do /kill. It will teleport you to the closes city and subtract 2 soul points just like a normal death

**Comment by SecretMermaid** [comment]
Many many thanks

**Comment by LordHelmchen98** [comment]
You're welcome.
You should close it now that its solved.
