### ISSUE TITLE
Where did my 100+ Shouts go? 

### ISSUE THREAD

**Issue by TimThePvpMaster** [Wynncraft/Issues#6573]
So Today I was on WC1 Detlas, and I wanted to shout I was purchasing a Lament, and selling a chestnut, so I went to my bombs section on my compass. When I clicked the 'Bombs' tab, it said I had none. Where did my 3 Party Bombs / 1 Xp Bomb / and 100+ Shouts go? Is this a Temp-bug?? I'm quite confused.

**Comment by TimThePvpMaster** [comment]
Just confirmed with JackyKit , another player. It's just a bug on my end.

**Comment by thecoolkogut4** [comment]
so the issue is resolved?

**Comment by TimThePvpMaster** [comment]
No, only doesn't work for me.

**Comment by thecoolkogut4** [comment]
any problems related the store should be sent to support, support@wynncraft.com email them with the transaction ID, your ign, and an explanation (and possibly screenshots) of your problem.

**Comment by TimThePvpMaster** [comment]
Well that's the problem, my VIP+ and stuff were bought by a friend, it's just weird because they all disapeared randomly.

**Comment by TimThePvpMaster** [comment]
I don't mind not having the shouts etc, I just spent a lot of GC's on em and now they are gone... Odd

**Comment by Trixter313** [comment]
We can't help with anything having to do with real currency. I'd suggest still trying to send an email to support to see what they say.

**Comment by opps123456789** [comment]
same here, it's been 12 days since my last reply!!!
