### ISSUE TITLE
Merchant prices not showing until *after* you purchase something

### ISSUE THREAD

**Issue by Thaecrasis** [Wynncraft/Issues#6575]
Recently (only showed up yesterday and today for me), when I go to a merchant, the prices don't show up, but I can still buy things at their coded price. When I purchase one thing from a shop then the prices show up for everything.

Screenshots showing no listed prices: http://imgur.com/a/UONrY

Video showing the complete bug: https://www.youtube.com/watch?v=TNLy-XJ3cZI

**Comment by Ewoutvhw** [comment]
Me and my friend CS64BIT are experiencing this exact same bug, also since yesterday.

**Comment by Trixter313** [comment]
Fixed by recent patch! Should be correct within 2-3 hours, if it isn't already.

**Comment by ggroggs** [comment]
Thanks, all looks fine for me now.
