### ISSUE TITLE
texture pack/ salesmen

### ISSUE THREAD

**Issue by bakuscout** [Wynncraft/Issues#6579]
so first off when i got on my favorite bow looked like a wooden slab. and secondly the shopkeeps are glitched they dont show prices and i cant even sell stuff to the treasure dude.

**Comment by LordHelmchen98** [comment]
Have you tried to delete your serverresourcepack? If not go to your .minecraft folder open the serverresourcepack folder and then delete the 'legacy' file.
The price bug is a duplicate of #6575

**Comment by bakuscout** [comment]
Thanks for getting back to me so soon, and sorry about making a duplicate report.
