### ISSUE TITLE
I LOST MY WEAPON !!!!! URGENT !!!

### ISSUE THREAD

**Issue by Xanderkh** [Wynncraft/Issues#6580]
WHEN I ENTERED THE WYNNCRAFT TODAY MY WEAPON DISAPPEARED IDK HOWWWWWWWWW????
WAS A REAPER OF SOUL... I HAVE EVIDENCES ABOUT IT

BEFORE TODAY(SORRY FOR THE SMALL IMAGE, BUT YOU CAN SEE THERE IS A WEAPON IN THE 1ST SLOT.
http://prnt.sc/d37een
http://prnt.sc/d37ex7
http://prnt.sc/d37f32
http://prntscr.com/d37f8c

TODAY
http://prnt.sc/d37g1m

HELP... THAT WAS MY ONLY WEAPON.
(THAT BONE GIVES SPEED BUT DOES NOT GIVES DAMAGE)

P.s: I already saw my bank and the weapon is not in the bank

**Comment by LordHelmchen98** [comment]
Wynncraft has a strict norefund policy. Sad as it is you wont get back your weapon.

**Comment by Xanderkh** [comment]
LordHelmchen98 But It is server's fault... Is not mine fault! I lost my weapon with a server's bug.

**Comment by Trixter313** [comment]
Also there's no way of us knowing what caused it. It could have been accidentally dropped, and to prevent that from happening I'd suggest changing your drop key to something less likely to accidentally be pressed.
