### ISSUE TITLE
Breathing Helmet II LOST

### ISSUE THREAD

**Issue by xPandaPvPerx** [Wynncraft/Issues#6581]
So, usually with my quest items, if it doesn't allow you to drop them, then you don't need them later on. I dropped my Breathing Helmet 2 to then find out in "From The Mountain" quest that you need it. Now, you cannot buy a new one from Saryy then redo it not can you trade it. Anyway that i could be given one and the emeralds be taken away from me since this has stopped my adventure on Wynncraft.

**Comment by LordHelmchen98** [comment]
You can buy the Breathing Helmet 2 for two EB from the armor merchant in Nesaak.

**Comment by xPandaPvPerx** [comment]
Holy sh*t, thank you so much. Was crapping myself after losing it. Cheers dude.
