### ISSUE TITLE
Powder and Poison

### ISSUE THREAD

**Issue by KirbyPlayzMC** [Wynncraft/Issues#6582]
Hello. I just recently started playing Wynncraft and loved it. I'm now 18 levels, and I luckily got 2 poison armour, which means that after i hit an enemy they will take 20 damage per second for 3 seconds. I got a new weapon, then used an earth powder tier 2 to upgrade it (I really only want earth powder because I mainly do strength, and I have a +15% damage on earth damage, while the others are weaker.) then i noticed that the poison effect was GONE, then I was in a panic that I removed the powder from my weapon by a powder master. The poison still dind't work and I relogged. The poison worked again.
I don't understand this whole, and I lost a tier 2 earth powder (which i only want to use) and 35 emeralds(for adding and removing the powder.) I want to have an explanation on this and what I should do, and I want to have my things back :(      ....
I know it really isn't much but I love Wynncraft and I really want to have this problem solved. Sorry for the long text.
Best wishes
-Kirby

**Comment by JackyKit123** [comment]
about your issue,
I am 69% sure that this bug has nothing to with powders
It's probably just poison broke in certain servers which sometime happens making poison malfunction

**Comment by KirbyPlayzMC** [comment]
Ok, and I want to ask about armour. Does the positive effect show in the description of the armour?
Because I only see the negative effect.

**Comment by JackyKit123** [comment]
Plz specify what negative effect that u r seeing and can you provide ss?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
