### ISSUE TITLE
Pelier Helmet not updated from update?

### ISSUE THREAD

**Issue by pikachu3215** [Wynncraft/Issues#6583]
I have a legendary helmet "Pelier" and it hasn't updated. Here's a screenshot.
![2016-11-05_11 20 30](https://cloud.githubusercontent.com/assets/23271960/20027253/f4c7fb2c-a349-11e6-98cd-f3db235b25eb.png)
Thanks!

**Comment by thecoolkogut4** [comment]
that happened to items with special letters in the name. keep it as a collectable, your not allowed to sell it. you will not be getting an updated version of the helmet.

**Comment by pikachu3215** [comment]
Okay, thanks.
