### ISSUE TITLE
Mythic Loss

### ISSUE THREAD

**Issue by Trasque370** [Wynncraft/Issues#6584]
Hello wynncraft admins!
I was mob grinding and I found a mythic! When I went to identify it in the middle of identification the entire server shut down D:
I went back online after some things got sorted out, I guess, and the mythic was GONE!!!
I was really frusterated, and I don't expect you to give my mythic back. Please fix this so other players dont get hit by the same thing
Thank you so much :D 
-TheMythicTras

**Comment by ColinRioux** [comment]
Hello, thank you for at least being the first one to understand the no refund policy. I'll keep this open so moderators see it.

**Comment by Trixter313** [comment]
If the restart was a scheduled restart I'd suggest changing to a new world as soon as possible before the server restarts so nothing like this can happen.

If it was unexpected there's not much we can do. Unexpected restarts are, unexpected, and there will be some data loss when they happen unfortunately.
