### ISSUE TITLE
Guild bug

### ISSUE THREAD

**Issue by nightmare142857** [Wynncraft/Issues#6585]
Just when I changed my name from Nightkiller407 to Nightmare142857, I came across a guild issue that when I type /guild list then My name appear twice. Not only that, when I use /g to talk or executing commands about my guild, The message also appears twice. Why is it happening? And Can someone help with this?
My guild name is rekt, so fine.

**Comment by LordHelmchen98** [comment]
There's no way to solve it. That happens to most people who change their names while being in a guild. The big majority gets stuck just like you. Guess you haven't tried it yet but you won't be able to leave or get kicked. You will also not be able to be promoted/demoted. Slightly rarer is the issue that your messages appear twice. (In my guild is a glitched member and his messages don't appear twice.) Unfortunately you and plenty of others have to wait until the guilds get fixed.
