### ISSUE TITLE
Quest bugged out

### ISSUE THREAD

**Issue by Kolking3268** [Wynncraft/Issues#6587]
The quest Wynncraft Excavation site A is bugged out for me. I did the quest and killed the boss, When I return to the person I need to talk to he says : have you got that text yet? I told u too to bring it too the tent and Give it too Tesha But I already did it .
Can someone please fix this?

**Comment by LordHelmchen98** [comment]
Duplicate of #4079
Have you tried /fixquests? If that doesn't work apparently there is nothing you can do :/
