### ISSUE TITLE
1.9+ TEXTURE PACK NOT LOADING

### ISSUE THREAD

**Issue by flick415** [Wynncraft/Issues#6590]
So I heard that there was new textures/skins for the weapons that only users in 1.9+ can use.  I went on 1.9.4 and checked out what they look like.  The texture pack started to load, but it didn't load in the textures after it "supposedly completed loading".  So I tried deleting and readding the server making sure that the server texture pack is "Enabled".  I tried changing different versions of minecraft such from 1.9-1.10.2.  I went to %appdata% folder and deleted the legacy folder and tried restarting minecraft numerous times.  But every time the texture pack would not load.  It only works for 1.8.9 and below for me so if anyone could help me, I would really appreciate it.  Thank you for your time, and I hope you have a wonderful day!

**Comment by ColinRioux** [comment]
Hi, in this repository is a legacy file. Try downloading that and putting it in `%appdata%` if that doesn't work, reply. Thank you.

**Comment by flick415** [comment]
I have tried adding it to my resource packs, but no luck.  Thanks trying tho!

**Comment by flick415** [comment]
Where is the repository located?

**Comment by ColinRioux** [comment]
@flick415 This is the repository. Scroll up to the top of this page, and click the *code* tab. Then you'll see a list of files before you, and click *legacy*. Then click the *Download* on the page.
