### ISSUE TITLE
Horse Bugge

### ISSUE THREAD

**Issue by GuillianG** [Wynncraft/Issues#6591]
its when u use the horse than it give a bugge, if u run whit it and than jump of it teleport u back
u keep moving on the horse and on the map its also moving but when u jump of it give a bugg

and also can u support me to unban idk why i got a ban for there stand  u got band by flyhacks
but, i play this game like for now 4 a 5days and i like it, and i dont use that hacks

**Comment by thecoolkogut4** [comment]
you might not use fly hacks, but do you use other types? join 1.8.8 to fix the horse bug. appeal your ban on forums.wynncraft.com
