### ISSUE TITLE
Can't get into the quest "A grave Mistake"

### ISSUE THREAD

**Issue by KitiNek0** [Wynncraft/Issues#6594]
Me and my friend can't walk up to the NPC called Alem. We looked online for help and everyone just walks up to him. Does this mean we can't do the quest?

**Comment by ColinRioux** [comment]
Hi, please refer to the wiki for help: 
https://wiki.wynncraft.com/index.php?title=A_Grave_Mistake

Please see the spoiler in step 2.

**Comment by Trixter313** [comment]
Let us know if following the Wiki helps resolve the issue, thanks!

**Comment by MarioSonicL** [comment]
I had the same problem but it seems that you can only get in after completing The House of Twain quest.

**Comment by KitiNek0** [comment]
Oh, well I totally cheated into doing it then lol, that explains why my
friend couldn't. I just teleported until I clicked Alem and then teleported
into the grave yard and did it

**Comment by Moe-Ronickah** [comment]
RESOLVED
