### ISSUE TITLE
"A Grave Mistake"

### ISSUE THREAD

**Issue by PapaD16** [Wynncraft/Issues#6596]
During the final part of the quest when I was being teleported around the area I lost connection. When I returned to the server I was still stuck in one of the clear boxes, but I didn't keep teleporting. Now I am just stuck in this box, whenever there is time I hope I could get teleported out.

IGN: xImTrash

**Comment by Trixter313** [comment]
You can use the command /kill to get out of most stuck situations.

You could also try relogging or switching worlds but if that fails, /kill.
