### ISSUE TITLE
Angry Village Quest Reward 

### ISSUE THREAD

**Issue by IcyShrub** [Wynncraft/Issues#6597]
When you complete the Angry Village quest the npc says he got some emeralds to pay you with. The quest rewards only show XP and a corrupted potato though. 
![2016-11-05_20 21 07](https://cloud.githubusercontent.com/assets/21267762/20034709/b611cb78-a395-11e6-819a-71d81428452f.png)

**Comment by thecoolkogut4** [comment]
wow! good catch @AckroWynn mind looking into this?

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/5511
