### ISSUE TITLE
Potion Making Bug (Current)

### ISSUE THREAD

**Issue by scol131** [Wynncraft/Issues#6598]
I was doing the quest, and my higher level friend, whom is questing to get me up to his level, defeated the boss, causing me to not get the chest plate and fail the mission.

Can someone assist me with this problem?

**Comment by Trixter313** [comment]
If you kill the boss again you should be able to get a drop for yourself as well.

**Comment by scol131** [comment]
Thats the thing, It wont allow me to kill it again, nontheless, get the potion again.

**Comment by ColinRioux** [comment]
Hi, could you please be more specific / provide screenshots? Thanks.

**Comment by scol131** [comment]
Ok, I'll give some screenshots tonight.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.

**Comment by Fdomc** [comment]
I am having the same issue was there a fix for this?
