### ISSUE TITLE
Craftmas Chaos Questbook

### ISSUE THREAD

**Issue by IcyShrub** [Wynncraft/Issues#6599]
When you go to start the quest the book should say "Talk to Tom in Selchar at <coords>"
![2016-11-05_21 31 47](https://cloud.githubusercontent.com/assets/21267762/20034981/54f3831c-a3a0-11e6-873b-c3a1bbc4f127.png)

**Comment by thecoolkogut4** [comment]
@AckroWynn i believe you could fix this?

**Comment by AckroWynn** [comment]
Fixed!
