### ISSUE TITLE
Loot Chest Particles 

### ISSUE THREAD

**Issue by IcyShrub** [Wynncraft/Issues#6606]
Chest particles show when no chest in there.
![2016-11-06_02 05 33](https://cloud.githubusercontent.com/assets/21267762/20036165/b628d96e-a3c5-11e6-9584-3976658827f5.png)

**Comment by Moe-Ronickah** [comment]
This is a very old issue.  @AckroWynn , is there a fix for this?  I know that the chest in spider cave near the statue entrance to Troms is notorious for this.

**Comment by AckroWynn** [comment]
This is an issue a GM can not fix. If anything, it would be Jumla, but it might have to do with lag, and it is not a gamebreaking issue, so it will not get prioritized. @Moe-Ronickah
