### ISSUE TITLE
Potential bug with horse breeding

### ISSUE THREAD

**Issue by Thaecrasis** [Wynncraft/Issues#6607]
I can't be sure if I'm just extremely unlucky, but I've tried breeding to get a black horse, and failed 8 times in a row. At 50% success rate each time, that would be a 0.34% chance of occurring. I've heard other people complain about having troubles breeding horses recently, so perhaps it might be a bug.

**Comment by LordHelmchen98** [comment]
I don't know what you mean by 50% success rate but the chances for breeding are:
20% better tier
50% same tier
30% worse tier

**Comment by Thaecrasis** [comment]
I thought those percentages meant that if you used two of the same tier horses, there'd be a 50% chance of success; one higher tier and lower tier (e.g. one chestnut and one brown, for whatever reason) there'd be a 20% chance; and if you used one lower tier (e.g. one black, and one brown, to get a chestnut), there'd be a 30% chance of success.

I guess that's not how it works then?

I was confused because of the wording in the wiki about horse breeding:
"By combining 2 of the same Tier horse you have a higher chance of getting a higher tier horse. "
So I presumed that meant that the 50% chance was attributed to using 2 of the same tier horses.

**Comment by LordHelmchen98** [comment]
If you use two horses of the same tier you have a 20%chance to get a better one, a 50% chance to get a horse of the same tier and a 30% chance to get a worse horse. But if you use two horses of different tiers it will always take the lower tier so if you breed a black and a chestnut you can get a black maybe stay at chestnut or even get a brown but never get a white.
