### ISSUE TITLE
Full inventory message when accessing bank

### ISSUE THREAD

**Issue by Trixter313** [Wynncraft/Issues#6609]
The message, "There wasn't room in your inventory, so items were dropped." appears even when just opening and closing your bank with a full inventory. Seems unintended.

https://youtu.be/PvrqDEEq3qo

**Comment by thecoolkogut4** [comment]
I get this too.

**Comment by LordHelmchen98** [comment]
I guess everyone gets this.

**Comment by Moe-Ronickah** [comment]
It's Jumla's fault.  (It really is.)

**Comment by Moe-Ronickah** [comment]
This is an intended warning, just a warning, to anyone who has a full player inventory, because it's easy to lose things that way when accessing the bank.
