### ISSUE TITLE
Lost Sanctuary wall glitch

### ISSUE THREAD

**Issue by Imperialking** [Wynncraft/Issues#6610]
When walking through the lost sanctuary as a mage the wall that triggers the explosive bridge does not activate and leaves me stuck in the first area. I killed myself and restarted, but it occurred again.

**Comment by Moe-Ronickah** [comment]
Which version of MC are you playing on?  You mentioned that you are playing as a mage.  Are you certain that you didn't tp into the area, either?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
