### ISSUE TITLE
Invisible Mobs and NPCs

### ISSUE THREAD

**Issue by princessbinas** [Wynncraft/Issues#6613]
I know there is another instance mentioned on here about invisible mobs (and I made sure to get on servers that had little to no lag and having under 40 players with Optifine on). But I have another problem coupled with it. There are invisible NPCS, and these are important ones, such as the admiral in Amuji (however you spell that desert city's name). I can't remember them all, but they are all over the place and it is annoying and making completing quests take longer.

I am playing with the Optifine version of 1.10.2.

**Comment by thecoolkogut4** [comment]
does this still happen when you remove all of your mods?

**Comment by princessbinas** [comment]
Yes. It still occurs.

**Comment by reapin** [comment]
I am having the same problem
I also am using optifine

**Comment by LordHelmchen98** [comment]
Is it necessary for you to play in 1.10? If not I think you should try to use a lower version. I don't use 1.10 so I don't know if it's a problem with the version but this never happened to me in 1.8.9 or 1.9.4

**Comment by reapin** [comment]
I just went to a version that doesn't have optifine and it seems to have fixed it for me.

**Comment by Moe-Ronickah** [comment]
Which version?

**Comment by DebugMC** [comment]
happens to me, but they usualy appear if i wait a second or do /class...

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
