### ISSUE TITLE
I got perm banned for nothing

### ISSUE THREAD

**Issue by MCtroller3936** [Wynncraft/Issues#6614]
I got banned for flying and when I made a ban appeal it said It was refused because I was banned for the same offense. Last I checked I haven't been banned before. I quit Minecraft for a long time and it is possible that someone hacked my account in that time. I think that is the reason that I have a history of being banned a lot. I could have been banned recently because I was lagging while using escape spells which stacked them and ejected me farther than normal, which could be mistaken for flying. I know I don't have any proof that this is true. But I know I'm not lying. Wynncraft is my favorite server and I would never do anything to get banned from it. Please take this into consideration and see if there is any way I can be unbanned.

**Comment by thecoolkogut4** [comment]
this is where you report bugs, not a place to appeal bans. Your only chance to get unbanned is to make a honest appeal on the forums.

**Comment by MCtroller3936** [comment]
I did but it was denied

**Comment by thecoolkogut4** [comment]
there is not much more you can do :/ maybe wait a few months type out a long appeal and hope for the best
