### ISSUE TITLE
Negative Totem Time

### ISSUE THREAD

**Issue by thecoolkogut4** [Wynncraft/Issues#6616]
http://prntscr.com/d41tsp
http://prnt.sc/d3zca9

This is due to the server lagging (i think), but this is still a bug as the totem stays for longer than what its meant to be. Mobs still get a boosted spawn rate in the - time.

**Comment by Moe-Ronickah** [comment]
Noted and on the fix-it list.

**Comment by DebugingLonks** [comment]
Is fixed to my knowledge. The max I have seen it get to before recently was -30minutes, now the max seems to be -1!

**Comment by thecoolkogut4** [comment]
nope, still going on. I've had -3 yesterday.

**Comment by Moe-Ronickah** [comment]
RESOLVED
