### ISSUE TITLE
Enemies attacking places you're not standing in

### ISSUE THREAD

**Issue by manawesome326** [Wynncraft/Issues#6617]
Sometimes, after running past or going near a group of mobs, they'll all converge on a random spot, and start attacking it as if you were there, dealing damage to you. They'll also become invincible. Running away doesn't help, as they just keep attacking the same spot as if you're standing there. The mobs usually figure out where you really are after a few seconds, but because you can't kill them in that time, and there are usually quite many, you die before that happens. This doesn't seem to happen on other servers, even ones that have similar amounts of lag.

To reproduce:  

1. Have terrible ping
2. Go anywhere near a group of mobs

**Comment by opps123456789** [comment]
Use 1.8

**Comment by puddles31** [comment]
This happens usually when you are on a horse. This happens because horse mechanics have changed from 1.8 and 1.9/10. Use 1.8 to stop this glitch happening.
