### ISSUE TITLE
You don't have permission for this area

### ISSUE THREAD

**Issue by IcyShrub** [Wynncraft/Issues#6618]
This loot chest can't be opened.
![2016-11-07_01 01 13](https://cloud.githubusercontent.com/assets/21267762/20049003/f336b162-a485-11e6-8c9c-bed821b9ac10.png)
Found another 
![2016-11-07_01 03 56](https://cloud.githubusercontent.com/assets/21267762/20049029/2049cdce-a486-11e6-9634-596a16dc9253.png)
Never mind it's something else. That pops up anytime I right click anything. In this picture I right clicked on the stone block. It only happens when right clicking with my first weapon (fierce thunder). That doesn't pop up if I use my fist or the other weapon. I'm unable to interact with chests or buttons while holding that weapon. This persists even after changing servers.
![2016-11-07_01 08 06](https://cloud.githubusercontent.com/assets/21267762/20049130/c2f3244e-a486-11e6-94d7-de5aca070ec7.png)

**Comment by thecoolkogut4** [comment]
yup your right, it is your weapon. some weapons are blocks so when you try to open the chest, it thinks you want to place the block.

**Comment by IcyShrub** [comment]
Aight. It's not an issue just slightly annoying because I have to lose my special to click buttons.
