### ISSUE TITLE
Invisible Totem

### ISSUE THREAD

**Issue by IcyShrub** [Wynncraft/Issues#6619]
If you place a totem and then die the totem is invisible when you come back. The timer is still there and mobs still spawn more.

**Comment by thecoolkogut4** [comment]
does the timer still count down, or is it frozen giving it a unlimited time? I think it despawns because nothing is in the chunk and because of that it goes away (just like how items go away when you leave the chunk)

**Comment by IcyShrub** [comment]
It functions completely normally except now it's being stealthy.

**Comment by thecoolkogut4** [comment]
oh that's not as bad as I  thought. it's probably because you left the area and when you leave any area in wynn all entities despawn so this is no exception
