### ISSUE TITLE
Totem Not Increasing Spawn

### ISSUE THREAD

**Issue by IcyShrub** [Wynncraft/Issues#6620]
I placed a totem in the WynnEx B area where mine zombies spawn. They didn't spawn any faster and none of the special ones spawned. 
Coords:
![2016-11-07_01 23 45](https://cloud.githubusercontent.com/assets/21267762/20049577/7e877550-a489-11e6-8536-e4e6c5278f2d.png)

**Comment by thecoolkogut4** [comment]
maybe you just placed it in a area where the spawn rate is super low for the mobs?

**Comment by IcyShrub** [comment]
I still should get special mobs though shouldn't I?

**Comment by thecoolkogut4** [comment]
you should, but I think the totem just multiplies the original spawn rate by X and if the original one is so low it won't make that much of a diffrence.
