### ISSUE TITLE
Ghostly Boots As a Chestplate

### ISSUE THREAD

**Issue by IcyShrub** [Wynncraft/Issues#6621]
Had this for a while now. Never questioned it until I actually put the set on and it marked it as boots. Also got the ghostly tunic and it's for a higher level than this and has different id's. If I equip helmet, legs, boots, and this chestpeice I appear to get the set bonus multiple times.
![2016-11-07_03 14 19](https://cloud.githubusercontent.com/assets/21267762/20052186/7ae32f98-a498-11e6-905d-c3e91b8b4a58.png)

**Comment by thecoolkogut4** [comment]
duplicate #4747
