### ISSUE TITLE
''Green Skinned Trouble'' Gliched

### ISSUE THREAD

**Issue by Collor** [Wynncraft/Issues#6622]
When i try to enter the teleporter it says ''Null'' in chat

![2016-11-07_10 59 51](https://cloud.githubusercontent.com/assets/22276316/20053606/a69a9e28-a4d9-11e6-81b2-3956e924d51f.png)
![2016-11-07_10 59 55](https://cloud.githubusercontent.com/assets/22276316/20053640/cf01547e-a4d9-11e6-9acf-a5043e46b60a.png)

**Comment by LordHelmchen98** [comment]
What does you quest book say?

**Comment by Collor** [comment]
Hunt down the orcs from the green/red/black camps i did that then it said that i needed to turn them in

**Comment by Moe-Ronickah** [comment]
OK, here's [the Wiki for this quest](https://wiki.wynncraft.com/index.php?title=Green_Skinned_Trouble). After reading through this, have you missed anything? What stage are you on?

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
