### ISSUE TITLE
I can't disable attack effects

### ISSUE THREAD

**Issue by RedwoodWynn** [Wynncraft/Issues#6623]
So I was checking out some of the new attack effects I got out of crates and once I was finished I realized that there was no way to disable them again.......

**Comment by thecoolkogut4** [comment]
what happens when you try to click the particle effect that is currently enabled?

**Comment by Arrowhawk5** [comment]
I have this same problem and none of the normal solutions have worked

**Comment by RedwoodWynn** [comment]
@thecoolkogut4 It just exits the use menu and does nothing.

**Comment by thecoolkogut4** [comment]
weird I removed my particles yesterday, I'll try this again when I get home

**Comment by RedwoodWynn** [comment]
@thecoolkogut4 I can remove my player effects, its just attack effects I can't

**Comment by thecoolkogut4** [comment]
ohh attack effects, my bad I got confused. I'll still test it out though. thanks for letting me know

**Comment by Arrowhawk5** [comment]
Is anyone going to followup on this thread?

**Comment by Moe-Ronickah** [comment]
Sure.  Go back into your /use dialogue. Click on the exact same effect that you currently have. It should be disabled.

**Comment by JuicedBananas** [comment]
Clicking the same effect to turn it off doesn't work. I have 2 attack effects, I can switch between them but can't turn them off altogether.

**Comment by LordHelmchen98** [comment]
It doesn't work for me either.

**Comment by Moe-Ronickah** [comment]
Juiced, how did you fix this?

**Comment by LordHelmchen98** [comment]
I don't know if he found anything new but if only happened what he said he didn't fix anything. You can choose a new attack effect and replace old ones but you can't get back to the default eeffects.

**Comment by Moe-Ronickah** [comment]
RESOLVED
