### ISSUE TITLE
Rise of the Quartron Quest

### ISSUE THREAD

**Issue by IcyShrub** [Wynncraft/Issues#6624]
Should say Talk to Nasea in Karoc Quarry at <coords>
![2016-11-07_05 41 41](https://cloud.githubusercontent.com/assets/21267762/20056676/0660c6e8-a4ad-11e6-8d63-fea651189047.png)

**Comment by Moe-Ronickah** [comment]
@Villageacules

**Comment by Moe-Ronickah** [comment]
It's best to tag our primary three Builders/GMs/CMDs.

**Comment by Villageacules** [comment]
Fixed, closed.
