### ISSUE TITLE
Temple of legend

### ISSUE THREAD

**Issue by Armin2002** [Wynncraft/Issues#6626]
The tol quest rayshyroth part didnt work. i have 2x64 sky vapor but he didnt accept it.
:(
(and i didnt have full inventory)
And he said "check your quest book for guidance"
Sorry for bad english im Hungarian.

**Comment by LordHelmchen98** [comment]
Unfortunately ingame nothing tells you to take the star dust with you as well, but I guess that's the item you didn't have with you.

**Comment by Armin2002** [comment]
ohh ty how to get star dust?

**Comment by thecoolkogut4** [comment]
when you get the star dust, make sure you activate the trip wire so it will update your quest. walk down on the stairs slowly.

**Comment by LordHelmchen98** [comment]
There was no part where you had to get it already? Sorry I haven't done the quest since the Gameplayupdate but I thought at that part of the quest you already had to do the Nether part. Oh and sorry I think it's called Light Dust not Star Dust and you can get it in the Nether area in a cave.

**Comment by Armin2002** [comment]
i will go to the nether first.
i had only 1 light dust

**Comment by Armin2002** [comment]
how much do i need?

**Comment by LordHelmchen98** [comment]
Only one I guess, but if you had that already make sure you activate that trip wire mentioned above.

**Comment by Armin2002** [comment]
thanks for helping me :D
