### ISSUE TITLE
??? Last part

### ISSUE THREAD

**Issue by Yotam4** [Wynncraft/Issues#6627]
So me and my friend did ??? And we were at the last puzzle and I had to afk for a second and now 1 person is stuck at the last room. Could someone please get him to the puzzle room?
I've put hours into this and I don't wanna redo it.
-Yotam

**Comment by thecoolkogut4** [comment]
your gonna need to find someone to help him go thrugh. I might be able to later tonight my ign is TheDarkSoul msg me when you see me online

**Comment by ColinRioux** [comment]
Next time, please post this on the forums as this really isn't a bug. Thank you.
