### ISSUE TITLE
Quest items (only) in bank duplicating

### ISSUE THREAD

**Issue by razorrider7** [Wynncraft/Issues#6628]
When a player drops an item out of the bank menu (while accessing your bank), and the item is a quest item, it duplicates the quest item. I accidentally did this a few times and now have 16 of yahya's stained bowl. Is there an way I can remove them?

**Comment by thecoolkogut4** [comment]
#6419 duplicate

**Comment by razorrider7** [comment]
I just realized why nothing showed up when I searched for it... I accidentally forgot to remove isOpen tag in search.
