### ISSUE TITLE
[Bug] Christmas chaos: can't talk to Santa

### ISSUE THREAD

**Issue by Malien** [Wynncraft/Issues#6629]
So yesterday I was doing  [X-Mas quest](https://wiki.wynncraft.com/index.php?title=Craftmas_Chaos) ... Everything was fine... But when I've spoken to Santa last time (in the last dialogue when he should give you reward) on the almost last phrase I was disconnected from server with a problem *(also, I've never encountered this type of server disconnection before. It looked as it was a JSON file with text in red in it. But unfortunately I was too dumb to remember the problems description)*

As for now I can't talk to Santa anymore and can't get my reward! And what's more annoying , is that there is now a quest in quest book marked "Started" that I could not complete!

By the way, my quest book says that I need to talk to Santa **and I can't do that** 😡

Hope you can solve that problem as fast as possible and get me my reward (or at least clear it from my quest book)

*P.S. I did found similar [issue](https://github.com/Wynncraft/Issues/issues/5298) on this repository, but it was closed, because The author didn't reply for long time 😔*

**Comment by Thaecrasis** [comment]
I'm not sure if /fixquests will help in this case, but if there is no other fix, it might be worth a shot. When you talked to Santa before, did he take away the crystal shard? It's possible that if that's the case, getting the item back with that command might allow you to talk to Santa again.

**Comment by thecoolkogut4** [comment]
as he said above me, if you had to give santa a QUEST ITEM at the end of the quest do /fixquests if you had an untradable item then you need to back track and get that item back (might req you to start from the begining/middle of quest)

**Comment by Rellia** [comment]
You have to kill evil santa to get the corrupted shard back. I believe they have the same item ID's, and you should be able to hand it over easily if /fixquest doesn't work

**Comment by Moe-Ronickah** [comment]
RESOLVED
