### ISSUE TITLE
Dropped items

### ISSUE THREAD

**Issue by mcdeathgod** [Wynncraft/Issues#6630]
I know dropped items cant be picked up by other players for a short period of time due to carelessness. 
But I just dropped a saddle in the sewer dungeon accidentally, and I couldn't get it back since it fell into the hopper. Its worth 24EB ( a lot for me ). Is there any way to roll back?

**Comment by thecoolkogut4** [comment]
there is a strict no refund policy. there won't be any roll back or refund, sorry
