### ISSUE TITLE
Quest Reset 

### ISSUE THREAD

**Issue by Rockobar** [Wynncraft/Issues#6633]
At the end of An Iron heart II, you are given a choice of who to report to in order to finish the quest. You may speak either to Dr.Urelix or to Detective Hart where you will finish the quest morally reprehensible or sound respectively. I saw the choice being given and my quest book updating. I turned away to check my quest book by right clicking it, unfortuantely instead it confirmed to Dr.Urelix I wished to take his morally dubious yet utilitarian bribe. 

I am aware that there is a 'no refunds' policy for items on Wynncraft, however I mistakenly clicked in too close a vicinity to a Quest NPC. I'd ask if this particular quest could be reset on my account Rockobar, specifically my Archer class. I'd be willing to surrender all items and xp obtained from the end of the quest and redo it completely if need be. I know a time before I finished the quest was 3:00pm GMT 8th November 2016. It is not the rewards that concern me, but that I heavily invest in my character from a roleplaying perspective and so would prefer that I pick the other conclusion to the quest. I hadn't thought interacting with my quest book would trigger a Quest ending event.

The event triggering:
<a href="http://imgur.com/vSI3pF1"><img src="http://i.imgur.com/vSI3pF1.png" title="source: imgur.com" /></a>
Thank you
Rockobar

**Comment by Rockobar** [comment]
P.S. I have the reward of 12 blocks and Shameful Greaves in my chest separate if you wish to remove them.

**Comment by LordHelmchen98** [comment]
This is a known problem and you are definitely not the only one who accidentally clicked their questbook or anything else while standing near Dr. Urelix. Unfortunately as you already know there's the norefund policy and you won't get back anything. Also I strongly doubt anyone will reset this quest for you as it really is not very likely staff makes any exceptions.

**Comment by Rockobar** [comment]
Thank you for the response, I'm glad to hear that this has been a problem to others. The reason why I would say it is not under the no refunds policy is that it does not concern the matter of items, but character progression that is now hindered due to a fault in the quest design. 
A very interesting quest btw.

Would a staff member comment if they would accept this request?
