### ISSUE TITLE
Ariodo's Lab Incomplete

### ISSUE THREAD

**Issue by Rockobar** [Wynncraft/Issues#6634]
I was exploring the Jungle and explored this particular fellow's Lab. However, I noticed that there are specific blocks with signs that seem to break the meta of the game and were different to the terrain monitoring signs. 

<a href="http://imgur.com/0i1uVRz"><img src="http://i.imgur.com/0i1uVRz.png" title="source: imgur.com" /></a>

<a href="http://imgur.com/YHLDaFy"><img src="http://i.imgur.com/YHLDaFy.png" title="source: imgur.com" /></a>

<a href="http://imgur.com/M2Bbms6"><img src="http://i.imgur.com/M2Bbms6.png" title="source: imgur.com" /></a>

Perhaps the Build team were refurbishing the area during the recent Update and forgot to remove some markers?

Thank you
Rockobar

**Comment by thecoolkogut4** [comment]
@AckroWynn

**Comment by AckroWynn** [comment]
They are not there on the build server. No idea why it isn't fixed over there. But, nothing more I can do.
