### ISSUE TITLE
Can't connect to any server

### ISSUE THREAD

**Issue by Elmaric** [Wynncraft/Issues#6635]
Hi,
I connected on Wynncraft servers and when I try to join a server by right-clicking the compass there's no servers at all.
Any way to solve this problem or this is just a temporary bug.
Thanks,

Elmaric

**Comment by LordHelmchen98** [comment]
That was just a bugged lobby that shouldn't be a problem at all. You just have to type /hub. Most likely you will get a message that you are already on that server but if so just repeat to do /hub until you get to a working lobby.

**Comment by ColinRioux** [comment]
In the case `/hub` doesn't work. You can re-log or type `/lobby` 
Or you can be specific about which lobby number, and type `/lobby <1-5>`. (For example: `/lobby 5`)
