### ISSUE TITLE
Infinite downfall after joining

### ISSUE THREAD

**Issue by Cartillius** [Wynncraft/Issues#6636]
Hello,

![2016-11-08_19 40 15](https://cloud.githubusercontent.com/assets/22212290/20113562/2c09544c-a5f1-11e6-9142-ef1d10f2ca28.png)
![2016-11-08_20 10 28](https://cloud.githubusercontent.com/assets/22212290/20113568/2efe6f70-a5f1-11e6-847e-69931e534ba4.png)
![2016-11-08_20 10 29](https://cloud.githubusercontent.com/assets/22212290/20113571/310120d8-a5f1-11e6-9431-e17a0d3e5b16.png)

I know this Issue already exists multiple times, but none of them helped.

Since yesterday after joining a world I keep falling down. I tried to dis- and reactivate and delete the resource pack and also to reinstall minecraft. I also fall down in the nether and I can’t use the /kill, /class, /toggle autojoin or /help command.
Have you an answer I haven’t tried or found?

Greetings
Cartillius

**Comment by ColinRioux** [comment]
Which minecraft version are you using?

**Comment by Cartillius** [comment]
I tried it with 1.10.2, 1.9.4 and 1.8.9 and it didn't worked
