### ISSUE TITLE
Can't make a guild.

### ISSUE THREAD

**Issue by obliviaxel** [Wynncraft/Issues#6637]
When I try to make a guild, nothing happens. I have seven LE. Does anyone know how to fix this?

**Comment by thecoolkogut4** [comment]
you have to be level 40+ to make a guild.

**Comment by obliviaxel** [comment]
I know.

**Comment by Moe-Ronickah** [comment]
Do you get any kind of message, at all?  How long are waiting before deciding that nothing happens?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
