### ISSUE TITLE
Realm of Light - "Exit" NPC broken

### ISSUE THREAD

**Issue by Westribution** [Wynncraft/Issues#6638]
In the quest "The Realm of Light" when you go to follow the trail of corruption you go down into the cave following the tail of red tiles and obtain the "seeds of corruption" and pass through a portal after giving it to the exit npc, but for me when I go to give the seeds to the npc its talk bar comes up blank and doesn't let me go through. Anyone know how to get that to work?

**Comment by thecoolkogut4** [comment]
what does your quest book say? does it say obtain some dust, mushrooms etc?

**Comment by Moe-Ronickah** [comment]
Where, [exactly](https://wiki.wynncraft.com/index.php?title=The_Realm_of_Light_(Quest)), are you stuck?

**Comment by AscendedKitten** [comment]
It's been more than 30 days without a reply to the issues, and there haven't been any further reports. 
If the problem persists, feel free to open a new one!
