### ISSUE TITLE
The Star Thief dosen't  spawn

### ISSUE THREAD

**Issue by spookyspider978** [Wynncraft/Issues#6639]
Doesn't help

**Comment by thecoolkogut4** [comment]
make sure your at the right spot, try to /class or switch servers. sometimes it might take awhile

**Comment by Trixter313** [comment]
Did @thecoolkogut4's suggestion help?

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response. Assuming issue has been resolved. If issue hasn't, please make a new issue, and try to be more specific. Thank you.
