### ISSUE TITLE
Relics named after Colour instead of Element

### ISSUE THREAD

**Issue by Scotsguy** [Wynncraft/Issues#6641]
When breaking a Relic's Seal, it says "You broke the [Colour] Powder [Number]'s seal!", although it should say "You broke the [Element] Powder [Number]'s seal!"

![Screenshot](https://i.imgur.com/otztr2r.png)

**Comment by Moe-Ronickah** [comment]
@Imaxe , I don't remember if this hard coded or if you can fix this.

**Comment by Moe-Ronickah** [comment]
Relics are still labelled by their color, also.

Passed to admin.
