### ISSUE TITLE
You don't have the permission

### ISSUE THREAD

**Issue by RohFrenzy** [Wynncraft/Issues#6642]
Hey ... since today my character get the message "u dont have the permission for this area" - it happend if i punch the ground with my spear (stone-halfslap) ... i cant use buttons or open chests :/

**Comment by LordHelmchen98** [comment]
Unfortunately there's no way to fix it. Its caused because the game thinks you want to place that slab (only happens with restructured slabs) so you will have to use your bare hands or another weapon to open doors or chests or click on buttons.

**Comment by RohFrenzy** [comment]
ok thanks ... hm ... :/
