### ISSUE TITLE
Quest reset. (flight in distress)

### ISSUE THREAD

**Issue by Kristupas900** [Wynncraft/Issues#6643]
I died in the quest. When i come back. First time i can sleep but the another time i cant sleep me. So what i need to do. Just if you can reset for me that quest so please reset.

**Comment by LordHelmchen98** [comment]
You have to follow the storyline but no need to talk to the NPC's. Maybe you have to go to the captain or to that button puzzle. You can look it up on wiki.wynncraft.com.

**Comment by Kristupas900** [comment]
I just do 10 times but nothing happind.

**Comment by Kristupas900** [comment]
When i do that puzzle nothing happind to the engineer.

**Comment by thecoolkogut4** [comment]
i died in the quest before, you just have to go to all tp regions in order. *not exact order* so like baby, room, engeneer, roof, room, etc...

**Comment by Kristupas900** [comment]
I dont know what happind but its fixed. Thanks guys for the help.

**Comment by LordHelmchen98** [comment]
You're welcome. (I guess you can close it now.)
