### ISSUE TITLE
Server Resource pack texture issue

### ISSUE THREAD

**Issue by TheRPingPandemic** [Wynncraft/Issues#6647]
Hello,

So I download the server resourcepack, and I load into the world. When I load in, I notice that the grass has no texture. What's the problem? How do I fix?

![2016-11-10_07 08 17](https://cloud.githubusercontent.com/assets/23379991/20178065/a53d2a82-a71d-11e6-8677-4d03bf4d575e.png)

**Comment by LordHelmchen98** [comment]
You should try to delete the legacy file. You can find it in the serverresourcepack folder inside your .minecraft folder.

**Comment by TheRPingPandemic** [comment]
Alrighty, I'll try it.

**Comment by TheRPingPandemic** [comment]
![2016-11-10_09 08 49](https://cloud.githubusercontent.com/assets/23379991/20179681/542e5564-a725-11e6-88bf-90bbf6569a69.png)


Nope, didn't fix it.

**Comment by thecoolkogut4** [comment]
open the legacy file with winzip, go to I think* block states, delete Tallgrass file. *might not be in block states just delete all the tall grass files in the pack that you find. that should fix it

**Comment by TheRPingPandemic** [comment]
I'll test it out and see.

**Comment by thecoolkogut4** [comment]
please turn off your radar as it is not allowed on the server.  @Moe-Ronickah

**Comment by TheRPingPandemic** [comment]
Okay, my apologies. I will. I didn't see anything about mods or anything like that on the website or wiki.

**Comment by thecoolkogut4** [comment]
did my answer fix your issue with the pack? just read the rules https://forums.wynncraft.com/threads/game-forum-rules.111874/ to make sure you dont break any of them. just to be on the safe side

**Comment by thecoolkogut4** [comment]
just leave it as its original file and use winzip to open it in the same state. atleast it's fixed though!

**Comment by TheRPingPandemic** [comment]
Well, if I use the pack as the resourcepack and not the server resourcepack, the message shows up that tells me to enable server resourcepacks for it to work. If I have the pack in resourcepacks, and it works, how do I get rid of that message without having to install the server resourcepack without it overriding the fixed resourcepack?

And the only other mods I use are Waila (Which seems irrelevant on the server, and I'll probs be disabling. I've already disabled the minimap), SAO UI (Which changes the position and look of my health and hunger bars), Matmos (Which provides me with atmosphere sounds, such as ocean waves, wind, crickets, etc.), Shaders (Because shaders :/), and Ambience (Which provides me with  background music, but seeing as the server has it's own music I might end up disabling Ambience as well.).

**Comment by TheRPingPandemic** [comment]
Oh, I also use BetterFoilage as well.

**Comment by thecoolkogut4** [comment]
you can keep mods that don't effect your game play. your allowed to use a mini map (just without radar) the sounds doesint give you a advantage etx

**Comment by TheRPingPandemic** [comment]
Yes, and what about those messages about the server resourcepack and downloading it, etc.?

**Comment by thecoolkogut4** [comment]
you need to use the server side pack to get rid of the messages. open the legacy up with winzip and edit/save it there so you don't need to change the file extension

**Comment by TheRPingPandemic** [comment]
There's nothing in the server-resourcepacks called legacy. And when I try to open it with WinZip it just tries to zip the file.

I'm on a Mac. Dunno if that helps or anything...

**Comment by thecoolkogut4** [comment]
yup it's b/c your on a Mac.  not quite sure how to do it on a Mac sorry

**Comment by TheRPingPandemic** [comment]
It's fine. I'll maybe just run the fixed resourcepack and have the serverside one disabled and deal with the message till a solution can be found. Thanks anyways.

**Comment by TheRPingPandemic** [comment]
Could someone provide me with a server resourcepack that has the grass fixed?

**Comment by ColinRioux** [comment]
Not sure why you're using WinZip on a mac. In the repository, there is a tutorial on how to download the most recent legacy pack from this repository directly. (https://github.com/Wynncraft/Issues/blob/master/RP%20DOWNLOAD%20INSTRUCTIONS.md)
You can download the file here: https://github.com/Wynncraft/Issues/blob/master/legacy

I can summarize the tutorial, since I wrote it. After dowloading the legacy file, you'll want to go into the `Downloads` folder via finder. There, right click `legacy` and choose rename. Rename the file to `legacy.zip`. Once completed, double-click the file to unzip it using Mac's built-in program– Archiver. Then, you'll have the resourcepack folder, and drag / drop into your `minecraft/resourcepacks` folder. You can make your edits inside the legacy folder. 

Let me know if you have any questions. 

Please turn off your radar, and you could always try running 1.8.9 or 1.10.2 if you still are having issues.

**Comment by thecoolkogut4** [comment]
whenever I tried fixing it like how you said, the pack (grass) just broke everytime I started up the game again. he already fixed it as in removed the grass, now he is looking to fix it while it is in server resource packs (so it won't spam him saying he doesint have the pack)

**Comment by TheRPingPandemic** [comment]
I've turned off the radar. I'm just using the map feature of the mod so I don't need to continuously switch between the browser map and the game.

**Comment by AscendedKitten** [comment]
It's been more than a month without a reply to this issue.
If the problem still persists, feel free to open a new one.
