### ISSUE TITLE
I connect and in the next second i die

### ISSUE THREAD

**Issue by Alexbaka** [Wynncraft/Issues#6648]
When i leave the server,the next time i connect i die. I think i know why this happens but dont know how to fix it. Its because i leave in a zone where there are monsters or nearby monsters (like a villige nearby a whole field of monsters) and they attack me while im not on the server,this should not have happend,right?

Ex: I wanted to go to The Great Bridge and i go on a tree because i had to go to school and when i was back i was dead.

**Comment by thecoolkogut4** [comment]
if your not logged into the server you don't die. you probably took damage as you were logging out our logging in (like when the texture pack loads)
