### ISSUE TITLE
My skin not showing up while in server

### ISSUE THREAD

**Issue by TheRPingPandemic** [Wynncraft/Issues#6649]
Well, My skin shows up in the lobby, but not in the world. Instead I'm Alex. Plz help. I'd prefer my elf skin for an archer over Alex.

**Comment by LordHelmchen98** [comment]
Often it updates if you put off an armor piece and equip it again.

**Comment by TheRPingPandemic** [comment]
I've tried that. I looked into the server resource pack that I managed to open, and turns out they put in a default skin texture for both Steve and Alex. Maybe there's a way to bypass or change it?

**Comment by Rellia** [comment]
I had that for a while, like a week, then it stopped

**Comment by TheRPingPandemic** [comment]
Maybe it'll happen for me too or something.

**Comment by ColinRioux** [comment]
I've been able to reproduce the issue while playing on 1.10.2, wynncraft only. You could try 1.8.9, if it bothers you much.

**Comment by MrRedCrack** [comment]
^ColinRioux it happens to me, even when I'm playing in 1.8.9.

**Comment by ColinRioux** [comment]
Then it's a resource pack issue most likely.

**Comment by DebugingLonks** [comment]
Its not ;3 how to produce: log off (like completly no /hub!), join any WC (any ver), look in your inv your alex. Also happens always when making a new class for me. Just take off a armor part then put it on.
