### ISSUE TITLE
Store has no options

### ISSUE THREAD

**Issue by Rellia** [Wynncraft/Issues#6650]
I cannot access the store on the website since halloween and I am on the PC. I click the store tab, and sign in with my name, then have no option to select an item for purchase. Also how do I pay without Paypal?

**Comment by thecoolkogut4** [comment]
you have to pay with paypal if you want to buy something from the shop

**Comment by ColinRioux** [comment]
Your name must be your in-game name as well. If it doesn't work, try refreshing the page.

**Comment by Rellia** [comment]
No my problem is that I can't see any items to select for purchasing, and why does it HAVE to be paypal..? That sucks... okay, how do I buy a gift card that I can use?

**Comment by Rellia** [comment]
![image](https://cloud.githubusercontent.com/assets/23388884/20212968/fac57abe-a7fd-11e6-916d-512041b4c64b.png)

**Comment by LordHelmchen98** [comment]
That should be fixed after pressing ctrl + f5

**Comment by Rellia** [comment]
wow...... okay. It eventually worked. Thanks
![image](https://cloud.githubusercontent.com/assets/23388884/20218656/92dd9074-a81d-11e6-9903-fd8713b83b8d.png)

**Comment by LordHelmchen98** [comment]
Jup worked l. That's how it's supposed to look like.

**Comment by Rellia** [comment]
Thank you. case closed
