### ISSUE TITLE
Wiki outdated

### ISSUE THREAD

**Issue by Rellia** [Wynncraft/Issues#6652]
Several quests have been updated to the point that the wiki sends you to completely the wrong places now. For example: Bob's lost soul quest, to acquire a rose without killing the Mooshroom, the wiki tells you to kill The Lonely Spider. The Lonely Spider is a mob that exists and I wasted half an hour with 61% looting trying to get the rose off it, when there was a Lonely Rose 300 blocks south...

**Comment by ColinRioux** [comment]
Hi, as an administrator of the wiki, I will make sure that my colleagues are on that. However, this isn't a bug. So please refrain from posting this here, but instead on the forums. 

The unfortunately fallacy with the wiki is that it's a wiki. Meaning, editors edit what they want or when they can. With each update, most of us can't cover everything. That being said, I encourage you to create an account, look at the guidelines and join us.

**Comment by Rellia** [comment]
Yeah sure I'd love to help out with the wiki, if you trust me to. Sorry I haven't been able to use the forums, I barely could get onto Github...
