### ISSUE TITLE
Lost my maxed out tier 2 horse and boat.

### ISSUE THREAD

**Issue by Massam10** [Wynncraft/Issues#6654]
I was sailing in my boat when i hit the edge of the world as it stopped loading in. By Sailing into this I glitched out and couldn't move. I went into my inventory and clicked on an item which happened to be my maxed out 20/20 tier 2 horse but the saddle dissipated. I had to re-log because I couldn't move and when i logged back in both my boat, which was the special one that gets a movement speed buff when other boats are around, and my horse were gone. I don't have any proof of having these items but i hope that I can get these back, I don't care much for the boat but the horse costs a lot and took a long time to lvl up.

**Comment by Rellia** [comment]
Are you sure these items don't just have invisible sprites in your inventory? sometimes the icons disappear and you can click the items spot and they'll come back. Maybe

**Comment by Massam10** [comment]
No i clicked around the the items are gone. when I logged back in I even went on the same server to check if they were on the ground underwater but nothing to be found.

**Comment by thecoolkogut4** [comment]
you can buy another boat at most of the islands, you would have to buy a brown horse and upgrade it. there is a strict no refund policy so you won't be getting the items back from staff. sorry

**Comment by Massam10** [comment]
That's fine. Thanks for the info.

**Comment by Trixter313** [comment]
Try to not click on any items in your inventory while your player is glitching, it most likely won't end well.
