### ISSUE TITLE
Seaskipper from Selchar to Skiens Island Glitch

### ISSUE THREAD

**Issue by puddles31** [Wynncraft/Issues#6655]
When you try to take the boat from Selchar to Skeins Island, the Seaskipper Captain will tell you that you're going, but once you're on the boat, he doesn't say or do anything else and nothing happens. The only way out is to /kill

**Comment by Rellia** [comment]
you could press the button under the clock?

**Comment by thecoolkogut4** [comment]
does this happen on every server you go on? or was it just the one?

**Comment by puddles31** [comment]
As far as I'm aware, pushing the button under the clock does nothing. And when I was on the boat, if I switched servers it was fine.

**Comment by thecoolkogut4** [comment]
the button does do nothing. also I think if you switch servers mid way on the sea skipper you'll get stuck. atleast your issue is resolved.
