### ISSUE TITLE
Ice Barrows boss

### ISSUE THREAD

**Issue by Rellia** [Wynncraft/Issues#6657]
Instead of going to the boss I was teleported to some random black 3 by 3 hole

That's so rubbish

**Comment by Rellia** [comment]
I was trapped in an obsidian box where I was glitching through the floor and there were a lot of command blocks around me... place it was the most lag I have ever had ever. took 5 minutes for anything I typed to get sent on my end

**Comment by thecoolkogut4** [comment]
sometimes for getting tped you first go to a black box (run and jump around in there) then it will hopefuly* to you out to where your meant to go.

**Comment by Rellia** [comment]
I was doing that the whole time but nothing happened :(
But thanks

**Comment by Trixter313** [comment]
If moving around or switching to another world don't help you can use the command /kill to get out.

**Comment by Rellia** [comment]
Yeah I know, @Trixter313, but it's just such a pain that that boss fight is so processing intensive and I lag out every single time I try it
