### ISSUE TITLE
Not getting a chesplate I should get at a quest

### ISSUE THREAD

**Issue by Zevii** [Wynncraft/Issues#6658]
Hey wynncraft,

I (confluens) recently did a quest called ''finding the light'' and if I am right you supposed to get a chestplate if you complete it, but I didn't get the chestplate. So if someone can help me get the chestplate it would be verry nice. BTW it also doesn't work if I try to do /fixquests.

Kind regards,
Confluens

**Comment by thecoolkogut4** [comment]
fix quests only give quest items back (the ones that you can't drop out of your inv) i think the chestplate your reffering to is un tradable so you won't be able to get it back inless you do the quest again on a other class. wynn has a strict no refund policy so you won't be getting your items back from staff.

**Comment by Trixter313** [comment]
If you look on the Wiki there is no chest plate reward for this quest. https://wiki.wynncraft.com/index.php?title=Finding_The_Light
