### ISSUE TITLE
Missing Chestplate

### ISSUE THREAD

**Issue by frxshmrc** [Wynncraft/Issues#6659]
Lost my "Hide of Gregg'r" Chestplate because it were automatical undressed at the moment I had a full Inventory, what should I do now? :|

**Comment by thecoolkogut4** [comment]
I don't believe it is a quest item, since it isint you would #1 buy another one from a player (if it is not untradable #2 do the quest again on another class to get the Armour back. wynn has a strict no refund policy which means staff will not be giving you your chestplate back.

**Comment by Rellia** [comment]
How can you complete a quest with a full inventory? It doesn't let you...

**Comment by thecoolkogut4** [comment]
@Rellia I think he just lost a chestplate while his inventory was full. I don't think he finished a quest with a full inventory

**Comment by Rellia** [comment]
ah okay. I didn't see much benefit of that chestplate over my own anyway.
