### ISSUE TITLE
Golden pants metadata broken. Name of item: "Priest's underwear"

### ISSUE THREAD

**Issue by skylarkblue1** [Wynncraft/Issues#6660]
After a few months of not playing a couple of my friends persuaded me to come back on to play again. 2 items in my inventory appear to have broken in one of the updates and I can't do anything with them except just chuck them away.

Both are golden pants and both are called "Priest's underwear" and have the same tag when hovering over them. Because it's been so long I cannot remember where I got them from or whatever.

![](http://image.prntscr.com/image/e4892594103e4a398cfa286d691f0dac.png)

**Comment by Rellia** [comment]
Try pressing F3 + f or F3 + h. I had this and it isn't permanent

**Comment by skylarkblue1** [comment]
Tried that already, wouldn't change it at all.

**Comment by LordHelmchen98** [comment]
I dont think there is a way to fix it and you won't get new ones due to wynncrafts strict norefund policy. You can either keep them (don't know why anyone would do that tho) or throw them away. They cannot be used against mobs.

**Comment by skylarkblue1** [comment]
Oh, just looked and found the forum post someone made about this issue. Looks like they got a slight update and the old ones are just broken now.

I'll guess I'll just chuck them away and try and find them again.. I do wish there was a way to go and play the old wynncraft though but not needing to make new characters and such, I kinda enjoyed it better then the updates >.<
