### ISSUE TITLE
Tower of Amnesia Coords are wrong

### ISSUE THREAD

**Issue by rdog21183** [Wynncraft/Issues#6661]
The coords in the quest book for Tower of Amnesia are about 200 blocks off.
When it tell you where the guy is the coords are wrong.
This can be a problem for newbies and i just wanted to point it out.
The actual coords and they are X: 85 Y: 74 Z: -1196

**Comment by Rellia** [comment]
But the map actually titles the tower...

**Comment by rdog21183** [comment]
Still, they should fix the coords

**Comment by Moe-Ronickah** [comment]
@AckroWynn , do you have the ability to work in the quest book, or is that admin only?

**Comment by AckroWynn** [comment]
Fixed!
