### ISSUE TITLE
Daggers Relic Unaccessible

### ISSUE THREAD

**Issue by puddles31** [Wynncraft/Issues#6662]
Currently, the Daggers Relic is unaccessible, as when you drop down onto the leaves, there is a block missing making it impossible to get to the hole with the pressure plate and ladder. This is on all servers.

![2016-11-12_09 59 54](https://cloud.githubusercontent.com/assets/23398205/20237024/c3f8be1c-a8be-11e6-892e-8ee8917df9e2.png)
Sorry if the image is bad, but where my pointer is should be a leaf block.

**Comment by Rellia** [comment]
No actually this is a trick that my brother and I found out. For getting in there you walk or crouch walk forwards and jump, and you land on the block you're looking at. You can't just land on it by walking or sprinting forwards. Try this a couple times. It should work. ;)

**Comment by puddles31** [comment]
I tried this but I hit my head off the block. Also, is the block supposed to be gone? Most videos on this relic have a block there.

**Comment by puddles31** [comment]
Nevermind, it took like 15 attempts but it works. Thanks!

**Comment by Rellia** [comment]
Wait the block is usually there? Oh okay... aww. Thought it was using a rare knowledge
Yeah you can never make it if you don't jump first. You are very welcome, friend. Sorry it took 15 attempts :(
