### ISSUE TITLE
Guild is bugged (Nobody Guild)

### ISSUE THREAD

**Issue by poepser132** [Wynncraft/Issues#6664]
When guilds where introduced I (poepser132) created a guild named WynnRaiders (VIO) A year or so later I bugged and there was no owner. Now I left the guild and created a new one named: QuatroPuppy (QTP)
but when I try to invite someone he/she gets a message but they can't join because it says they are not invited. when I do /guild stats it says I am in the guild: Nobody without an owner and no members. I hope my account can be fixed as this really ruins my experience.

![image](https://cloud.githubusercontent.com/assets/12009237/20238885/33cd3d54-a8f5-11e6-8cac-98cacbf12be6.png)

**Comment by thecoolkogut4** [comment]
guilds are really glitchy at the moment. there is nothing you can currently do.
