### ISSUE TITLE
Help! I'm stuck!

### ISSUE THREAD

**Issue by Aardwolph** [Wynncraft/Issues#6665]
I finished killing the Orc boss in the quest, Green Skinned Trouble, but as soon I walked through the coal block portal in the back of the room, I was teleported to a pitch-black area in the coordinates: X(-1866) Y(28) Z(-4899). I can only move about one block and, it sounds like I'm walking on stone, and there are sounds of running water close by. I don't see any name tags or mob tags.

I don't have anything that can teleport me out, and I have tried relogging but it spawned me back in the same place. 

Please help!

**Comment by Rellia** [comment]
/kill will kill you, but you'll respawn with all your items except some junk... This happened to me too in the Frozen Barrows Dungeon... Unfortunately it's the only way if you don't have teleports

**Comment by Aardwolph** [comment]
Thank you very much!
