### ISSUE TITLE
Bob's Lost Soul Quest Bug

### ISSUE THREAD

**Issue by hotcatmom** [Wynncraft/Issues#6666]
I've been killing bob for days and he still hasn't dropped a single tear. I need to finish this quest to progress and idk what to do

**Comment by Rellia** [comment]
What's your looting chance? If it's really high then I don't know what's wrong, but I can get you a tear if you like?

**Comment by puddles31** [comment]
Bob's Tear is a very rare drop from him. It can take a while, but try to get high loot bonus on armour and weapons, it will make your life easier.
