### ISSUE TITLE
Corrupted Lost Sactuary Dungeon Bug

### ISSUE THREAD

**Issue by oOTheExpirienOo** [Wynncraft/Issues#6667]
After the last Jump an Run the Boss say a sentences but after my second walktrough it doesnt happend. When this happen and you go in the teleporter to the boss the sentences: Arakadius: Ah the main Course has arrived. You look so good,i Think i´ll have a taste of myself Comes and you are stuck in a black room.

**Comment by Rellia** [comment]
Why are you farming that dungeon, though?

**Comment by oOTheExpirienOo** [comment]
A +85% fire dmg Leggings. I tried the dungeon a twice after this bug because i hoped that it maybe will work right after that strange bug.

**Comment by Rellia** [comment]
Huh... well, honestly I don't think it's worth it... you'll that the leggings are a weakness for so little health and armour quite quickly

**Comment by puddles31** [comment]
Firstly, the dungeon is called Infested Pit, not Lost Sanctuary. Secondly, this black box is used to teleport players and give dialogue at the same time. To get out, simply run and jump around (usually in the centre) and you should be teleported.

**Comment by Rellia** [comment]
@puddles31 that doesn't always work. I got trapped and never saw anything of the frozen barrows dungeon boss, and for 20 minute i was lag running around in the box, and then started glitching through the floor and saw all the command blocks... the only way to get out was /kill

**Comment by Rellia** [comment]
Also maybe it is the lost sanctuary dungeon with the wrong boss dungeon text from Infested pit

**Comment by oOTheExpirienOo** [comment]
@puddles31 Infested pit is the Spider Dungeon as Corrupted Dungeon. Lost Sactuary is the Animal dungeon in Corrputed

**Comment by puddles31** [comment]
@oOTheExpirienOo The Infested Pit was the old spider dungeon, and the corrupted version is called the Corrupted Infested Pit. same with Lost Sanctuary and Corrupted Lost Sanctuary.

@Rellia That wouldn't make any sense, if it was the Arakadicus talking then it's the Infested Pit.

**Comment by thecoolkogut4** [comment]
run around and jump in the bodlx to get tped or /kill no need for off topic info.  did this help?

**Comment by oOTheExpirienOo** [comment]
Jumping around in the box dont help but /kill works

**Comment by oOTheExpirienOo** [comment]
Today i tried the dungeon again and all worked
