### ISSUE TITLE
Fortuneteller Castle Hole

### ISSUE THREAD

**Issue by DirtyDoge** [Wynncraft/Issues#6668]
I found a little hole all the way behind the castle that can be used to enter the room you are teleported to in the quest.
![2016-11-12_11 56 46](https://cloud.githubusercontent.com/assets/21346185/20239828/c152bfe4-a8cf-11e6-9b53-aea4903f700a.png)

EDIT: This hole leads somewhere else it seems, but I still don't think someone's supposed to get there.
EDIT2: Looks to me like it's directly behind the castle teleporter, you can get back by going to the lump of coal blocks.

**Comment by thecoolkogut4** [comment]
im not exactly sure what the picture is showing. is there a hole in the wall where u can enter and skip part of the quest? does it only work if you use mage teleport?

**Comment by Moe-Ronickah** [comment]
@Imaxe , can you fix this?

**Comment by ColinRioux** [comment]
Fixed!
