### ISSUE TITLE
Horses

### ISSUE THREAD

**Issue by pr1tce** [Wynncraft/Issues#6669]
I beleive i have found a bug. i was gonna get the next teir horse after black, but when i combined the 2 brown horses, they turned into a brown horse instead of a black one. so when i combined my black horse with this so called black horse it turned into a brown horse. thanks for your considiration

**Comment by thecoolkogut4** [comment]
when you combine horses its not a 100% chance you get a higher tier. i believe its 30% for a higher, 10 for a lower, and 60% for the same. *not exact %*
