### ISSUE TITLE
The Lost quest is broken

### ISSUE THREAD

**Issue by Fluffy2305** [Wynncraft/Issues#6670]
In The Lost quest, I've delivered all of the messages but it still says that I need to deliver one more. When I do /fixquest it says that I have all of my quest items, even though I've delivered all of the letters.

**Comment by ColinRioux** [comment]
Hi, what does your quest book say?

**Comment by Fluffy2305** [comment]
Oh, sorry this is so late, but the quest book says "Find the last missing member of Dejol's crew"

**Comment by Moe-Ronickah** [comment]
Find a walk-through on youtube, and follow it, please.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
