### ISSUE TITLE
Seaskipper passes to nemract not working

### ISSUE THREAD

**Issue by Peeves5200** [Wynncraft/Issues#6671]
Whenever i use a pass to go to nemract (tried from selchar and mage island more than once) i get stuck on the boat and the dialogue doesnt continue so im stuck on the boat permanently. Also using /kill then spawns me at the beginning of the game which makes it more annoying

**Comment by ColinRioux** [comment]
Hi can you please provide screenshots or a video (so I can attempt to reproduce the issue)?

**Comment by Moe-Ronickah** [comment]
Duplicate of #6389
