### ISSUE TITLE
Missing Saddle

### ISSUE THREAD

**Issue by Aardwolph** [Wynncraft/Issues#6672]
In Nesaak, I was identifying a few items. Prior to that I was going through the forest on a Tier 2 Black level 20/20 horse. When I went to bank my items, I noticed the saddle to spawn the horse with was gone. I looked around the town to see if I had dropped it, but I still couldn't find it. I checked my bank and carefully went through each slot, and the saddle wasn't there.

I have no idea what happened to my horse. Can anyone help? And am I able to get my horse back?

**Comment by thecoolkogut4** [comment]
the server has a strict no refund policy, staff won't be giving you the horse back... sorry.

**Comment by Aardwolph** [comment]
Do you know where I can buy a new horse?

**Comment by thecoolkogut4** [comment]
if you did the quest "Stable Story" you can buy a horse at around x: 837 z:-1640. the horse merchant is in a house.
