### ISSUE TITLE
Galleon Graveyard Lack of Permissions

### ISSUE THREAD

**Issue by Rockobar** [Wynncraft/Issues#6673]
On relogging into a different server and killing the Armoured Pirate with the cannons, the room would not allow me to proceed to the next section. It says I did not have the permission to interact with the button that would open the door.

<a href="http://imgur.com/1Fl9JhI"><img src="http://i.imgur.com/1Fl9JhI.png" title="source: imgur.com" /></a>

As a result I had to /kill. I imagine this could be an issue with all other dungeons if you have to switch servers.

**Comment by puddles31** [comment]
Were you holding a weapon at this time? It's best to have an empty hand when interacting with things like buttons.

**Comment by thecoolkogut4** [comment]
some weapons are blocks, when you  click the button with your weapon the server things you want to place the block. to fix this, click the button with a empty hand or with your soul point.
