### ISSUE TITLE
Saddle

### ISSUE THREAD

**Issue by Kvietl** [Wynncraft/Issues#6674]
I saw an issue similar with a saddle disappearing, but a reply said there was a strict no refund policy. I got a saddle from the stable story quest, does that still apply to the no refund policy?

**Comment by thecoolkogut4** [comment]
yes if you lost your horse (saddle) that you got from stable story you won't be able to get it back. if you want another one you would have to buy it from the horse merchant or another player. the no refund policy covers everything.
