### ISSUE TITLE
bug /guild defend

### ISSUE THREAD

**Issue by djacobs12345** [Wynncraft/Issues#6675]
hello i have a problem whit defend the guild territory so i cant do /guild defend i get a internal error so ye what can i do about it???

**Comment by thecoolkogut4** [comment]
are you attacking that place near llivigar? the one there is broken. guilds are really buggy right now so if switching servers doesn't fix it I'm not sure what will.

**Comment by djacobs12345** [comment]
ow oke thx annyway
