### ISSUE TITLE
House of Twain quest - Library phantom unkillable

### ISSUE THREAD

**Issue by Chieftain7** [Wynncraft/Issues#6676]
I am currently on the House of twain quest, and on the part where I need the 3 ghost drops for the ghost cap. I have read that you must defeat the library, lab, and garden phantoms to get the items. However, When I spawn the library phantom, it only attacks me and takes no damage whatsoever. I can't do anything except run, and as far I know there shouldn't be invincible enemies. Please help! I am an assassin.

**Comment by thecoolkogut4** [comment]
Hey! I got a few questions for you to try and resolve the issue. The weapon that you are using,  is it one  that the mob is weak to? Do you have enough damage on your weapon to actually harm it? Did you try switching servers? Did you ask someone to help you hit it to see if they do damage?

**Comment by Rellia** [comment]
It's weak to fire damage and I only did this quest 5 days ago. I managed perfectly fine. Regardless, you don't actually need to kill them. The ghostly cap can be acquired as a loot drop from just killing mobs. The cap you get from the items to the hopper is just dyed, but you can receive the whole set by farming in the mansion. So if you REALLY can't do anything against the librarian, just know it's not specifically required to complete the quest

**Comment by Doobig10** [comment]
I've had similar issues with bosses and being assassin fast attack speed doesn't really work well on some as they regen too fast and/or don't take damage as weapons are much weaker (even though against most enemies its enough) ... I recommend getting a friend to help with it get them though lower its health super low then use a special or something to kill it as that generally works

**Comment by AscendedKitten** [comment]
It has been more than 30 days without a response to this issue. 
If your issue still persists, feel free to open a new one trying to describe it with as much detail as possible.
