### ISSUE TITLE
Fantastic Voyage Portal not working

### ISSUE THREAD

**Issue by ChillDrake** [Wynncraft/Issues#6677]
You know fantastic voyage, and at the end of the other world, there is a portal leading back to the overworld? Well yeah. I went through that portal, and now I can't get out :c
If a mod or someone else could fix or tell me how to fix this issue I would be VERY grateful. Losing a level 90 class is NOT something that I want to do.

**Comment by Trixter313** [comment]
You could try switching to another world or doing /class a few times but if that doesn't work you can type /kill to get out.
