### ISSUE TITLE
Im stuck while trying to complete Craftmas Chaos

### ISSUE THREAD

**Issue by LameDude** [Wynncraft/Issues#6678]
I was doing the quest Craftman's Chaos and I was at Selchar (30 years ago after destroying the crystal) trying to find Corrupted Santa. I followed a friend and I suddenly I saw a black screen after I teleported. 
Coordinates if you need them: 5961.300/ 45.00000 / -13037.300
Username: OscarChang

**Comment by Trixter313** [comment]
You should be able to use the command /kill to get out. =)
