### ISSUE TITLE
bug /guild defend 

### ISSUE THREAD

**Issue by djacobs12345** [Wynncraft/Issues#6681]
it stil not working so ye

**Comment by thecoolkogut4** [comment]
make sure you own the territory, what piece of land are you trying to defend?

**Comment by djacobs12345** [comment]
i try to defend llevigar

**Comment by thecoolkogut4** [comment]
as I said on your other issue, llivigar is currently glitched and you can not defend it.

**Comment by djacobs12345** [comment]
and i cant attack also now so

**Comment by djacobs12345** [comment]
i whant to attack katoa but i am now in a war server but it isent working so can you help my out

**Comment by thecoolkogut4** [comment]
keep on trying. sometimes it takes 10+ tries to get a working war.

**Comment by djacobs12345** [comment]
ow oki thx
