### ISSUE TITLE
Why cant I use a voxelmap like normal without missing textures like grass on wynncraft 

### ISSUE THREAD

**Issue by Skylocks8** [Wynncraft/Issues#6682]
I like to use voxelmap mod bc it helps with coordinates and I like to use the wynncraft texture pack and I cant have both. Please Help!
![2016-11-13_16 44 35](https://cloud.githubusercontent.com/assets/23439888/20249115/767b1fd8-a9c0-11e6-86d1-8c7e4b31d076.png)

**Comment by LordHelmchen98** [comment]
Does the voxelmap require forge? I think there are some problems with forge. However I heard it should work if you delete the file for tall grass in the legacy file in your server resourcepacks folder.

**Comment by DebugingLonks** [comment]
#6733 @LordHelmchen98 @Skylocks8 I just noticed. Read his chat.
