### ISSUE TITLE
My friend can not join! Please help!

### ISSUE THREAD

**Issue by CalAnders** [Wynncraft/Issues#6683]
So, my friend Ethankuczarski can not join Wynncraft because of whatever reason. He is getting an error message saying, "Flying is not enabled on this server." It does this for some time and then his minecraft crashes. Is this a bug or just his computer being old and laggy?

If you could get back to me, I would appreciate it greatly!

Thanks!

~ CalAnders

**Comment by LordHelmchen98** [comment]
Its not his computer or his internet. This is an issue with the connection to the Wynncraft-servers. I live in a european country so my connection to servers in amerika isnt the best anyway and sometimes (expecially if there are more than 1000 players on the network) this happens for me as well.

**Comment by CalAnders** [comment]
Thanks!

**Comment by Moe-Ronickah** [comment]
RESOLVED
