### ISSUE TITLE
Realm of Light Quest Issue

### ISSUE THREAD

**Issue by Whiteguy48** [Wynncraft/Issues#6685]
Hi, So I was doing the Realm of Light mission and got tot the cave and killed the Seed of Corruption. I then proceeded to pick up the item on the floor named Seed of Corruption, however when trying to exit with the seed in my inventory, the game requests that i go kill the Seed of Corruption, even though I have the drop already. I have tried to relog with and without the seed, throwing the seed out many times and getting a new one, going back out the cave, and coming back in and proceeding to kill the item dropper again, and it still will not let me go pass. What can I do to fix this?
![2016-11-13_17 42 42](https://cloud.githubusercontent.com/assets/9968256/20250877/99289bd4-a9c8-11e6-8e4c-f898155080df.png)
![2016-11-13_17 43 39](https://cloud.githubusercontent.com/assets/9968256/20250890/bc8728c0-a9c8-11e6-9eb4-5e367b4c01cf.png)

**Comment by Rellia** [comment]
Is the mob called Seed of Corruption?

**Comment by Whiteguy48** [comment]
Yes, as far as I can tell it is the only thing that can drop that mission item anyways

**Comment by Moe-Ronickah** [comment]
If this isn't working on any specific server, you will need to change servers, and kill the boss again.  The drop from the other server will not work because it's data, that isn't visible, will have changed.

**Comment by Whiteguy48** [comment]
Alright I'll see if a server switch will help

**Comment by Whiteguy48** [comment]
So I have tried a Multitude of servers, removing the item Seed of Corruption each from my inventory and obtaining a new one from that specific server, and each time I still get the same message and I am still not allowed through

**Comment by Whiteguy48** [comment]
OK.. I found the problem, the issue is that i didn't have the quest helmet on and was using my regular gear, so i guess it needed it although it doesn't tell you you need it on at all times, anyways thank you for the contribution.
