### ISSUE TITLE
Troms' Potion Merchant

### ISSUE THREAD

**Issue by MysticSloth** [Wynncraft/Issues#6686]
The mana potions that the merchant sells do not do anything. 
![2016-11-13_17 53 23](https://cloud.githubusercontent.com/assets/13672237/20251864/baaea952-a9d1-11e6-850b-e5b313905d28.png)

**Comment by ICHIGOunserscore** [comment]
Yea that guy a scammer xD

**Comment by Moe-Ronickah** [comment]
Regardless of whether or not the item's information is being displayed properly, have a you purchased one and tried it?

**Comment by MysticSloth** [comment]
Yeah, the potion was in my hotbar and did nothing when I tried to use it.

**Comment by Moe-Ronickah** [comment]
OK.  I'll pass this along.  Thanks for reporting and checking it.

**Comment by Moe-Ronickah** [comment]
@Imaxe , is this anything that you have any control over?

**Comment by Imaxe** [comment]
@Moe-Ronickah 
@MysticSloth  Issue will be fixed in the next map push
