### ISSUE TITLE
Horse dissapeard

### ISSUE THREAD

**Issue by Kolking3268** [Wynncraft/Issues#6688]
My horse was in my inventory, I log offline and then my Black horse is gone , Please help me

**Comment by thecoolkogut4** [comment]
you can but another one from a player, or from the horse merchant* the server has a strict no refund policy so staff won't be giving you your horse back

*must have completed the quest stable story to access

**Comment by Rellia** [comment]
I might sell mine, if you like... DMEW_Rell ign
