### ISSUE TITLE
Weapon in hopper

### ISSUE THREAD

**Issue by Elmaric** [Wynncraft/Issues#6690]
Hi,
I'm Elmaric, Assassin lv.56 and I was doing the Overgrowth ruins dungeon with my friends when I ... dropped my legendary weapon lv.51 in the hopper where you're supposed to put diamond tokens ... Is there any way to get it back ?

Thanks

PS: I know that's not a bug but I didn't know where to put that topic

Elmaric

**Comment by Rellia** [comment]
nope sorry
You have to get another one. There's a no refund no exceptions on the server.

**Comment by ColinRioux** [comment]
Hi, long answer short: Wynncraft enforces a **strict no refund policy**. What that means is that regardless of the scenario, since it's not a quest item, there is no way to get it back. It is put in place to ensure fairness.
