### ISSUE TITLE
Fourm Issue

### ISSUE THREAD

**Issue by Locky1110** [Wynncraft/Issues#6692]
I dunno if there is a certain place where i can put forum bugs, but here we go.
I also dunno if this happens to everyone.
Basically I can't scroll down on the preferences page, meaning i can't change my theme from Hallowynn to WynnCraft
Thank you and sorry if this was a waste of time
Locky1110

**Comment by Trixter313** [comment]
If you scroll to the bottom of the screen on the forums home page there should be an area in the bottom left that says HalloWynn and if you click on it you should be able to change the theme to something else.

Let me know if this other method helps at all, thanks!

**Comment by LordHelmchen98** [comment]
Just use this link https://forums.wynncraft.com/misc/style?style_id=12&_xfToken=28664%2C1479213362%2C1a6df959a3c77c34bb68d609f1128fb1361434c3
