### ISSUE TITLE
HELP ME STUCK

### ISSUE THREAD

**Issue by Yolza** [Wynncraft/Issues#6695]
HELP ME IM STUCK IN A BARREIR  BLOCK AN I ACCIDENTLY DROPPED MY LEGENDARY MAGE WAND

**Comment by Yolza** [comment]
IM REWIPE BTW

**Comment by Rellia** [comment]
oh ouch... sorry but you will have to find another one. If you're still stuck, you gotta /kill I guess

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so we cannot return your wand but you can use the command mentioned above to get out.

To try and prevent accidentally dropping an item I'd suggest changing the drop key to something else that is less likely to be accidentally pressed.
