### ISSUE TITLE
Quest Items Stuck in Bank

### ISSUE THREAD

**Issue by TheMattIzBack** [Wynncraft/Issues#6697]
Before the new big update, I had multiple quest items in my bank. Now, I cant throw them away, trade them, sell them, or use them! Theyre just forever stuck in my bank taking up space... Can a mod come delete them form my inventory?

**Comment by LordHelmchen98** [comment]
Quest items were never tradeable. They are supposed to stay there and not to be throw away as you might need them for later quests. To be fair some are just filling your bank and arent used for a later quest so far but if there will ever be a quest that needs one of them you might need them.
However if you really want to get rid of them you can put them into your daily reward. But be careful. Most of the time you get them back by doing /fixquests but if you dont get them back nobody will give you one of them. You would have to get another class to the level and quest that gives you that quest item.

**Comment by Rellia** [comment]
If you want to delete the quest items, make a new character, put the items in it's inventory, then delete the character
