### ISSUE TITLE
Wynncraft Enhanced Mod Pack

### ISSUE THREAD

**Issue by firefox0809** [Wynncraft/Issues#6699]
When I launch the Enhanced modpack on curse and connect, it says I have to update and the message won't go away. I checked and I also have the latest version.
![screen shot 2016-11-15 at 12 49 49 pm](https://cloud.githubusercontent.com/assets/23468916/20323530/f88ed20e-ab31-11e6-9071-8e6b02307a2f.png)

**Comment by Rellia** [comment]
Why are you using a modpack?

**Comment by LordHelmchen98** [comment]
This is not a bug of wynncraft itself so its not supposed to be posted here. For this to be solved you should message the creators of the modpack.

**Comment by firefox0809** [comment]
It is an Issue so...

**Comment by LordHelmchen98** [comment]
Yes its an issue and ye maybe if you are lucky you can find someone who can help you here but actually this was posted a few threads earlier although its not really obvious as the guy who created the thread created it in a kinda strange way (#6694). Also its not an issue with Wynncraft but with the modpack and here on github you are supposed to report bugs that are directly related to wynn (e.g. commandblock bugs). However the Enhanced modpack is not an official wynncraft modpack but fanmade so the mods, builders,... that are looking over the github threads cant help you with that.

**Comment by thecoolkogut4** [comment]
yes, it is an issue but ones simply does not report a apple bug to Microsoft.  (this is what your doing just with diffrent products)

**Comment by ColinRioux** [comment]
Please report this issue to the developers of the mod-pack, not Wynncraft. Wynncraft enhanced is a third-party application made by community members (with the permission of Wynncraft). 

[See Wynncraft Enhanced's Forum Post](https://forums.wynncraft.com/threads/custom-modpack-❀-wynncraft-enhanced-❀-590-supporters-party-hp-display-custom-worldmap-more.139677/)

If there is no support information listed there or on their website, I suggest messaging on of the users listed in the "Credits" section.
