### ISSUE TITLE
Grave digger - Bug item - Read more...

### ISSUE THREAD

**Issue by CrisOnoCris** [Wynncraft/Issues#6702]
I can´t complete the quest because when i kill the Sayleros' brother , his don´t drop the Dusty will and i can complete the quest. Plz, help me.

**Comment by LordHelmchen98** [comment]
Have you tried switching the server?

**Comment by CrisOnoCris** [comment]
nooo. why?

**Comment by LordHelmchen98** [comment]
Maybe its only bugged on one server.

**Comment by CrisOnoCris** [comment]
i try but his dont drop the item D:

**Comment by thecoolkogut4** [comment]
as you sure your killing the right person? maybe the drop is spawning somewhere else in the room and you can't see it, try killing him multiple times, and  as lord said try switching servers.

**Comment by CrisOnoCris** [comment]
yes i sure. I try to switch server and i try to kill but his not drop the item and i lost MANY ITENS

**Comment by thecoolkogut4** [comment]
maybe wait for someone to help you kill it. I recommend not leaving a city of you are less then 5sp because you have a risk of losing your good items
