### ISSUE TITLE
Can't Connect to the Server

### ISSUE THREAD

**Issue by Alexbaka** [Wynncraft/Issues#6703]
So i try to connect the server and i get this error:
Could not connect to default or fallback server, please try again later : io.netty.channel.AbstractChannel$AnnotatedConnectedException
I tryed To change the version,Change to optifine and back,tryed other resolution (Idk i changed the resolution recently and that might work),Tryed another launcher and even Direct connect.
![2016-11-16](https://cloud.githubusercontent.com/assets/23382370/20355950/6cfd295a-ac23-11e6-8613-cc3fb637dfdd.png)

**Comment by thecoolkogut4** [comment]
can you connect to other servers or is it just wynn?

**Comment by Alexbaka** [comment]
just wynn

**Comment by thecoolkogut4** [comment]
try to use the ip "fixjoin.wynncraft.com"

**Comment by Alexbaka** [comment]
I have no idea how this will work but i will try

**Comment by Alexbaka** [comment]
no, did not work

**Comment by thecoolkogut4** [comment]
try play.wynncraft.Xyz


replace xyz with com, net.
or replace play with node7

**Comment by Alexbaka** [comment]
ok
i tryed the thing with net-com but with xyz not

**Comment by Alexbaka** [comment]
it did not work to replace xyz with com/net

**Comment by Alexbaka** [comment]
but node7 worked

**Comment by Alexbaka** [comment]
Thanks you really helped me

**Comment by LordHelmchen98** [comment]
@thecoolkogut4 https://forums.wynncraft.com/threads/i-need-those-alternative-ips.165074/#post-1876974

**Comment by ColinRioux** [comment]
If it does in fact damage the backend, an alternate method I found would be to switch to version 1.8.9, login, then close 1.8.9 and reopen 1.10.2/1.11 and login.
