### ISSUE TITLE
Didnt Recieve Quest Rewards

### ISSUE THREAD

**Issue by Doobig10** [Wynncraft/Issues#6704]
Hallowynn 2016 Didn't give me the "Trick" Or "Treat" Rings That Apparently I'm supposed to get? Is this An issue on my part or is it a glitch because ive been having similar issues such as not getting the right number of emeralds on other quests however ive never not gotten an item I'm supposed too?

**Comment by thecoolkogut4** [comment]
maybe the rings were exclusively for Halloween and they removed it as a reward since it is over. did it say + trick and + treat when you finished the quest?

**Comment by Doobig10** [comment]
I'm pretty sure they were listed when I finished but that may still be the issue if so that would be sad

**Comment by Moe-Ronickah** [comment]
That reward is no longer obtainable.
