### ISSUE TITLE
Didn't receive full quest rewards for WynnExcavation B

### ISSUE THREAD

**Issue by corscott5** [Wynncraft/Issues#6705]
For the quest WynnExcavation B, I only received 1 purple crystal when it said I should receive 2 (I don't know if that will be an issue later), and although I do not know how many emeralds I had in my inventory to start with, I only had 893 (13 blocks and 61 emeralds) after the quest, which is supposed to give an additional 1536 emeralds. I'm not sure if xp was affected but I was about mid level 46 and now I am mid level 47.
![2016-11-16_11 41 41](https://cloud.githubusercontent.com/assets/23505458/20356597/fe5b1258-abf2-11e6-90d8-4e8d6ad9ac19.png)
![2016-11-16_11 41 34](https://cloud.githubusercontent.com/assets/23505458/20356605/03cacef4-abf3-11e6-9023-20daf252350a.png)

*edit: spelling

**Comment by LordHelmchen98** [comment]
Try if /fixquests gives you the missing shard.

**Comment by Rellia** [comment]
Do you actually need 2 crystals?

**Comment by LordHelmchen98** [comment]
Yes you do. One for Wynnexcavation Site C and one for Site D.

**Comment by corscott5** [comment]
It didn't do anything. Said I had no missing quest items. I'm still missing the emeralds either way

**Comment by Moe-Ronickah** [comment]
Somewhere, in the GitHub closed issues, are numerous duplicates of this.
1: The number of shards that you end up with is not listed correctly during the quest.
2: NEVER complete a quest with any LE, EB, or E in your inventory, because all 3 can interfere with how much reward, if any, that you will receive.
