### ISSUE TITLE
Okay, legit I'm not showing off, I'm getting too many legendaries

### ISSUE THREAD

**Issue by Rellia** [Wynncraft/Issues#6706]
My character gets A LOT more than the average character for legendary loot drops. After 4 weeks, I have a 62 archer, 20 knight, and 11 assassin (notable characters). And by this point, I'm not kidding, I've had 50+ legendaries... 7 in my very first hour playing. So many legendaries that I greatly undervalue every legendaries price and started dropping them because I was getting so many and running out of money. 3 week later I know their actual value, and other players are incredulous... Is there any way you can lower the legendary spawn rate for my character because it's just... I don't know... HELP

**Comment by thecoolkogut4** [comment]
get -loot bonus gear to get less legendarys

**Comment by Rellia** [comment]
but I was getting them before I got to ragni...

**Comment by Rellia** [comment]
Also, I haven't seen ANY -loot bonus gear...

**Comment by thecoolkogut4** [comment]
your getting a lot of legendary in the tutorial! I wouldent be complaining this way you'll have good armor to start your classes off.

**Comment by Rellia** [comment]
It's boring though... Like in 1 minute I picked up three legendaries... it's too much. It spoils the enjoyment of discovering a legendary

**Comment by ICHIGOunserscore** [comment]
I want your luck

**Comment by ColinRioux** [comment]
Could you:
Right click the compass, hover over the player head in the upper right, and tell me what the Loot Bonus percentage is? 

In terms of lowering it though... I doubt they'll lower it for you. You could just have great luck.

**Comment by Moe-Ronickah** [comment]
Looking into what I can find out.

**Comment by Imaxe** [comment]
I doubt there is an issue with your character getting more legendaries that usual. 
I suppose you're just lucky ^^

**Comment by Moe-Ronickah** [comment]
OK, the chances of getting legendarys and mythics was increased, very slightly.  It's just pure RGN and loot bonus.  Some people have better "luck" than others, and nothing is broken.
