### ISSUE TITLE
Stuck doing quest

### ISSUE THREAD

**Issue by PixelatedGalaxy** [Wynncraft/Issues#6707]
I was doing the Temple of Legends quest and I'm stuck in the are directly above the CoW and I cant get out. I've tried doing /kill and the same problem occurs.

**Comment by ICHIGOunserscore** [comment]
try a new server

**Comment by Trixter313** [comment]
Does the issue still happen to you? I'm assuming it isn't anymore but if it is, just comment back and I can reopen the issue. Thanks!
