### ISSUE TITLE
Staff was stolen by Pirate Boss

### ISSUE THREAD

**Issue by byVite** [Wynncraft/Issues#6708]
The Pirate Boss pullt me to him and the staff was gone.
It was a Sage for level 47 players

The time was:
22:45

Ign: byVite

**Comment by LordHelmchen98** [comment]
Wynncraft has a strict norefund policy s you won't get back your sage. And is it possible you accidentally pressed your button to throw out something? If it's still 'Q' I recommend rebinding it.
