### ISSUE TITLE
Health regen percentage isnt working

### ISSUE THREAD

**Issue by MrRedCrack** [Wynncraft/Issues#6710]
I have +144% health regen and +36 health regen. But when I am regen'ing, I still only get 36 health regen every 4 seconds. Did i misunderstood about the percentages for the health regen?

I've tried relogging, switching servers.

**Comment by thecoolkogut4** [comment]
% = Regenerates a % of health that you have missing I belive 

raw = how much gets added on per normal Regen.

if you have 1000% health Regen when  you have 10k total health but only have 1k health your health will come back super fast till you hit around 6k health then it slows down 

*not exactly numbers and im not 100% I'm correct*

**Comment by Rellia** [comment]
Yeah I'd really like to know how this actually works too

**Comment by MrRedCrack** [comment]
I don't understand anything in your explanation.

**Comment by thecoolkogut4** [comment]
The amount of hp you regenerate without ids, is based of the amount of hp you got.
this regeneration that is uninfluenced by ids, I'll call 'base regeneration.'

% hp regen multiplies this base regeneration the same way % spell damage multiplies your spell damage.

So, like, if you regenerate 1hp each period of time you regenerate something. (1 hp might seem very low, but on my assassin it happens all the time.) You will regenerate 1 + (amountof%hpregen x 0.1)

So the formula for your hp regen =
BASE REGENERATION + (AMOUNT-OF-%HP-REGEN x 0.1) + RAW HP REGEN

posted by creature on the wynncraft forums. I take no credit

**Comment by MrRedCrack** [comment]
Ok, thanks.
