### ISSUE TITLE
Weapon lost

### ISSUE THREAD

**Issue by Wiebedesma** [Wynncraft/Issues#6711]
I was playing on the wynn server in nesaak and I lagged a lot when i was dragging my weapon I losted it and i c'ant find it, it was the joker i'm lvl 47 and my ign is Wiebedesma. can I get it back???

**Comment by LordHelmchen98** [comment]
Unfortunately you cant get it back due to Wynncrafts strict norefund policy.

**Comment by Wiebedesma** [comment]
I have no weapon what should I do and farming I can't without weapon

**Comment by LordHelmchen98** [comment]
Try to get a weapon in a city from a merchant or ask other players if they have somthing for your level.

**Comment by Wiebedesma** [comment]
okay, thank you
