### ISSUE TITLE
Can't kick from Guild

### ISSUE THREAD

**Issue by Rexolboy** [Wynncraft/Issues#6712]
So the leader of my guild wants to kick AFK people to add new people. But there is a bug where already we have 2 of the same people and we can't kick them from the guild : https://gyazo.com/3f927de9a801bbee98284f0f9d3390d6
https://gyazo.com/2ce952c0eaadbf5ce4a2e3c7791d3b9c
In the first screen, you see Briac, the 2nd highest ranking officer "kicking" Wideaz multiple time, but in the second screenshot, you can see that he is still in tab, and still twice. LAD_Zaqe is also in double in tab

If someone could help, that would be sweet

**Comment by LordHelmchen98** [comment]
Thats because Wideaz changed his name while being in your guild. That causes issues with the guild system. Unfortunately there is no fix for this. Wideaz will stay in your guild being bugged until guilds get fixed.

**Comment by Moe-Ronickah** [comment]
Please, follow our front page instructions on finding if you issue has already been posted.  You might, or might not, find a solution.
