### ISSUE TITLE
Donator Rank Glitches

### ISSUE THREAD

**Issue by blackmagic9988** [Wynncraft/Issues#6713]
So I'm VIP+ and It's been two days yet none of my totems have regenerated, and I haven't gotten my daily crate. If possible can someone look into these issues.

I really would like to get my crates, and totems back plz.

**Comment by thecoolkogut4** [comment]
Hey! For any issues regarding purchases from the store, please email support@wynncraft.com and they will resolve your issue. I don't think they will give you totems and crates from the days that you didn't get it, but they will hopefully fix it to where you get them everyday!
