### ISSUE TITLE
Didn't receive items after finishing quests

### ISSUE THREAD

**Issue by BaconStrips111** [Wynncraft/Issues#6718]
I have just done the Underice Quest and A Grave Mistake Quest, and for both quests I have not received the items that were listed after completing the quest.  I did receive the exp and emeralds that were rewarded once completing the quests but that was it.  I have already tried /fixquests and that did not help.  My inventory was full when I was doing those quests, could that have contributed to the problem?  Any help is appreciated.

**Comment by LordHelmchen98** [comment]
I don't know about Underice but I'm pretty sure as Graves Mistake is the Halloween quest for this year, the rewards were Halloween exclusive. You can't get them anymore because Halloween is over.

**Comment by Rellia** [comment]
bit mean making the quest level 50 then... I was 38 as my highest character and missed it by a week because of house of twain quest needed first

**Comment by BaconStrips111** [comment]
@LordHelmchen98  Ah that would make sense for the Halloween quest, I didn't know the rings were Halloween exclusive as I didn't see anything like that mentioned on the wiki for the quest.  However, that still doesn't explain why I have not received the quest item for the Underice quest.

**Comment by Moe-Ronickah** [comment]
"My inventory was full when I was doing those quests, could that have contributed to the problem?"  Without a doubt, yes.  There was no where to put any items in your inventory.  And, I'm sorry to say, you probably will never receive anything else for it, because, as far as the game is concerned, you successfully completed the quest.  Never, ever, ever, turn in a quest without open inventory slots.

**Comment by BaconStrips111** [comment]
@Moe-Ronickah Sorry when I said "My inventory was full when I was doing those quests,.." I meant my bank inventory was full.  My characters inventory definitely had space for the item.  What I meant by saying that, is could it be possible the item would have been put into my bank storage if it was not full, once completing the quest.  Sorry for the confusion.

**Comment by LordHelmchen98** [comment]
The items can't be placed into your bank only in your inventory. Also did you get anything when talking to either Gernald or Calamaro? You don't get the items when talking to the guy on the frozen lake but when you talk to one of the two others.

**Comment by BaconStrips111** [comment]
I talked to Calamaro, giving him the pufferfish.  When I looked up the quest on wiki it says I should have received Calamaro's Token along with exp and some emeralds.  I only received the emeralds and exp when completing the quest.  Also here is the wiki page I am referring to https://wiki.wynncraft.com/index.php?title=Underice

**Comment by LordHelmchen98** [comment]
Oh Im sorry I didnt see this. Actually you already get Calamaros token when you give him the pufferfish not when you get back to Fredris to finish the quest. However as explained above you wont get it back due to Wynncrafts strict norefund policy.
