### ISSUE TITLE
Quest: The shadow of the beast

### ISSUE THREAD

**Issue by Rellia** [Wynncraft/Issues#6719]
Done all the requirements and the book is telling to enter the cave, yet trying to enter the cave tells: "Magic in this cave is too intene for mortals to withstand"

Is this a bug, or have I followed the wrong candles?

**Comment by LordHelmchen98** [comment]
It should be the cave to the left just after you walk into the forrest. There is blood on the ground and fences on the sides with candles on it.

**Comment by Rellia** [comment]
Do you have to climb a trail to reach some mushrooms around a path then a bridge in a cave?

**Comment by Rellia** [comment]
nvm
XD

**Comment by LordHelmchen98** [comment]
Pretty sure the cave at the end of that trail is related to the Taproot quest :)

**Comment by Rellia** [comment]
yep it is. I was being blind XD
