### ISSUE TITLE
UNDERGROUND!!?!

### ISSUE THREAD

**Issue by TheGalaxyOwner** [Wynncraft/Issues#6720]
When i used my Almuj scrool somehow i ended underground.... i can't die i can't move so i'm stuck...please help me

**Comment by LordHelmchen98** [comment]
Do /kill if you have more than 5 soul points.

**Comment by TheGalaxyOwner** [comment]
I can't join io.netty.channel....

**Comment by LordHelmchen98** [comment]
Why are you not able to join? Do you get a fallback message?
If so try .org or .net instead of .com at the end of your ip.

**Comment by TheGalaxyOwner** [comment]
Everything works now ty again :)
