### ISSUE TITLE
Glitched

### ISSUE THREAD

**Issue by RDSpecter** [Wynncraft/Issues#6721]
Hi i'm stuck in the boat called the Seaskipper I can't get out of the boat because of invisible blocks and the boat isn't taking me anywhere. So if one of the admins or moderators could just teleport me out or something that'd be great. (btw my im game name is RDSpecter).

Thanks

**Comment by thecoolkogut4** [comment]
type /kill or use a to scroll to get out

**Comment by ColinRioux** [comment]
You could also try switching servers.
