### ISSUE TITLE
I can not level up for anything that i do!

### ISSUE THREAD

**Issue by Stefffo** [Wynncraft/Issues#6723]
I have tried leveling up in every class possible and it will just not let me. Please help me i really like this game and it is ruining it for me. My username in game is Steff_Gamz

**Comment by LordHelmchen98** [comment]
Did you set the amount of xp that goes to your guild to 100% in the past? If so do /guild xp 0 to get all the xp yourself.

**Comment by Stefffo** [comment]
oh thanks dude. you really were a big help. i thought i broke my minecraft for a while there.
