### ISSUE TITLE
Beneath the Depths, the boss: "Pirate Guard" cannot drop head to open the passage behind the wall. 

### ISSUE THREAD

**Issue by G0naB3** [Wynncraft/Issues#6725]
Skull cave, that "pirate guard" cant drop the head .. and next passage is behind the wall.. and you cant open it..

**Comment by EnderManKing** [comment]
actually. i am doing the quest right now.....you're right. i've killed him 3 times. no head.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
