### ISSUE TITLE
No servers avalible...?

### ISSUE THREAD

**Issue by EnderManKing** [Wynncraft/Issues#6727]
NO servers.
8:24 AM Western Time. 
![2016-11-19_08 24 15](https://cloud.githubusercontent.com/assets/20938040/20456322/e14173ec-ae31-11e6-9f91-88c9e6eb9899.png)

**Comment by ColinRioux** [comment]
Hi, this is a duplicate issue. There are numerous ways to fix: 

1. Type `/lobby` and then a number between 1 and 5. For example: `/lobby 4`
2. Only type `/lobby` 
3. Type `/hub`
4. Relog
