### ISSUE TITLE
House of Twain: Twain's Phantom

### ISSUE THREAD

**Issue by Falondor** [Wynncraft/Issues#6729]
I have been working on the House of Twain quest. I am at the part when you have to kill Phantom Twain and he doesn't drop his journal. I have killed him 3 times and still no luck. Anyone know why?

**Comment by ColinRioux** [comment]
Does Phantom Twain keep respawning instantly?

I noticed when I did the Salyeros' Brother quest on my lower class 2 weeks ago, I had to kill many different "forms" of Sayleros' Brother in order to finally get an easy to kill mob that dropped the item. Maybe Phantom Twain works the same what

**Comment by Trixter313** [comment]
Did @ColinRioux's information help you resolve the issue or is it still happening?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
