### ISSUE TITLE
Olux's Dusty Clock

### ISSUE THREAD

**Issue by Rockobar** [Wynncraft/Issues#6732]
Hello, I noticed a minor continuity error with the item Olux's Dusty Clock required for the Clock Mystery.

<a href="http://imgur.com/nLuL8dw"><img src="http://i.imgur.com/nLuL8dw.png" title="source: imgur.com" /></a>

As you can see the clock says it is at 5:25, when in fact in the Clock Tower the pressure plate is between 4 and 5. 

<a href="http://imgur.com/wiVDnbH"><img src="http://i.imgur.com/wiVDnbH.png" title="source: imgur.com" /></a>

This can be easily remedied by change the time on the Dusty Clock to 4:25. 

Thank you
Rockobar

**Comment by AscendedKitten** [comment]
Thanks for the report, and sorry for the rather slow reply! 
I edited the clock, once an update is pushed it should correctly display 4:25
