### ISSUE TITLE
Trying to fix missing grass textures???

### ISSUE THREAD

**Issue by BudderBiscuit** [Wynncraft/Issues#6733]
I have the same annoying missing grass texture bug as so many people, but when I went to my legacy file in the server-resource-packs folder (opened with 7-zip), it had no texture files in it?
(Path: C:\Users\ecksdee\AppData\Roaming\.minecraft\server-resource-packs\legacy\assets\minecraft\textures\)
From there it splits into 2 folders, entity and item, which are both completely empty.

Am I looking in the wrong place, or do I have to suffer pink and black blocks forever?

![2016-11-19_20 58 02](https://cloud.githubusercontent.com/assets/16129198/20460073/65724af4-ae9d-11e6-9f8a-8284be89cb76.png)

**Comment by LordHelmchen98** [comment]
Strange my legacy file has textures. Open [this] (https://github.com/Wynncraft/Issues/blob/master/legacy) page and dowload the legacy file there. Try if it works when you replace your legacy file with that one.

**Comment by BudderBiscuit** [comment]
I tried, but it didn't work. I switched from 1.10.2 to 1.8.9 and that seemed to have fixed it.

**Comment by LordHelmchen98** [comment]
Yeah with 1.10 this happens pretty often as Wynncraft and the resourcepack were made for 1.8.9 and in higher versions there are many texture issues. However Im using 1.9.4 to see the item skins and its working fine as well.

**Comment by DebugingLonks** [comment]
It happens to me on 1.8-1.11 :3 anyway, I have the manual install and just load that up.
