### ISSUE TITLE
Killing An NPC

### ISSUE THREAD

**Issue by flier66666** [Wynncraft/Issues#6735]
I was sitting in Ragni and all of a sudden I got this
![2016-11-20_00 18 36](https://cloud.githubusercontent.com/assets/12567592/20461578/469dfbc2-aeb7-11e6-9c71-4652a4e634c1.png)

Not really that big of a problem, just thought it was funny.

**Comment by ColinRioux** [comment]
Could you please describe your issue better?

Your image is also of the NPC Sayleros in Detlas, not Ragni.

**Comment by Imaxe** [comment]
Are you refering to the mission? 
If so, thats not really an issue. That's just how the missions work
