### ISSUE TITLE
1.8 texture pack

### ISSUE THREAD

**Issue by Nikenine** [Wynncraft/Issues#6736]
1.8 up texture pack   the bow is still not change the picture still is Half brick

**Comment by LordHelmchen98** [comment]
You should try to replace the legacy file in your server resourcepack folder with the file on [this page] (https://github.com/Wynncraft/Issues/blob/master/legacy).

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
