### ISSUE TITLE
My Bob's Wand Just Disappeared

### ISSUE THREAD

**Issue by Anson6311** [Wynncraft/Issues#6737]
I was fighting in corrupt decrepit sewers last night
After 12PM (California time), my wand just disappeared in my hand
There's a chance that I throw my wand out by accident
But there's no fire/lava near, and at that place just flat floor and still water that I can easily pick items up
My in-game ID is Anson6311, I cannot fight without Bob's wand
Is that a bug?

**Comment by Anson6311** [comment]
I can remember that I added 3 tier-4 thunder powder on my Bob's wand, is that causing the bug?

**Comment by LordHelmchen98** [comment]
Hmm that should obviously not happen but you wont get your bobs wand back due to Wynncrafts strict norefund policy.
