### ISSUE TITLE
Purchase

### ISSUE THREAD

**Issue by CrypticNaz** [Wynncraft/Issues#6738]
I purchase vip rank, 4 item bomb, and 5 crate but have not receive it in the game username is CrypticNaz

**Comment by LordHelmchen98** [comment]
This is a page for bugreports not for issues related to realworld currency. For issues like yours you have to contact the support. Therefore send an email to support@wynncraft.com

**Comment by CrypticNaz** [comment]
thx sorry for posting it here first time i did this

**Comment by LordHelmchen98** [comment]
Dont worry, you are not the only one.
By the way when you mail them add your transaction code otherwise they wont be able to help you..

**Comment by CrypticNaz** [comment]
here is the transaction code:
1BH03173MK089441Y

**Comment by thecoolkogut4** [comment]
id remove the ID ASAP, email it to support and they will deal with the issue. email them with your IGN, ID, and a explanation of what happend.
