### ISSUE TITLE
API getMyLocation has data missing

### ISSUE THREAD

**Issue by GamersForOne** [Wynncraft/Issues#6739]
As title says, some data is missing from the getMyLocation on the API.

The map states that you will see your party, friends and guild that are on your server, but the only one that shows is the party. I'm currently online on WC1 with 1 friend also on WC1 and I'm not in a party. Doing a request at https://api.wynncraft.com/map/getMyLocation gives me `{"name":"Kirdow","server":"WC1","x":980,"y":23,"z":-5038,"health":4655.016557990974,"maxHealth":8956,"party":[],"request":{"timestamp":1479672740}}`, where you can see that I can only see a party tag, which is empty. There's no friends tag available, and I don't know about guild, as I'm not in one.

So conclusion: the API:getMyLocation request only shows you and your party members, and does not show your friends (and not your guild?).

**Comment by LordHelmchen98** [comment]
Strangeif I do this it gives me this:

> {"name":"Lord_He1mchen","server":"WC20","x":491,"y":67,"z":-1557,"health":10235,"maxHealth":10235,"party":[{"name":"MinecraftPixels1","x":-860,"y":76,"z":-929,"health":6975.646468578353,"maxHealth":8068}],"request":{"timestamp":1479673365}}<
MinecraftPixels1 is actually not with my in a party but on my friend list

**Comment by thecoolkogut4** [comment]
it works for me, shows party, guild, and friends.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
