### ISSUE TITLE
Texture problems

### ISSUE THREAD

**Issue by EnderManKing** [Wynncraft/Issues#6740]
My dagger has no texture and my Mask Of Courage has no texture PLZ HELP.
![2016-11-20_18 33 29](https://cloud.githubusercontent.com/assets/20938040/20468090/147b56d2-af50-11e6-9258-8c2a27cae094.png)

**Comment by LordHelmchen98** [comment]
Try playing in a lower Minecraft version. The recommended version is 1.8.9 as this is the version Wynncraft was made for. However Im using 1.9.4 to see the item skins and its working fine as well.

**Comment by ColinRioux** [comment]
This is happening as a result of version 1.11 to my knowledge. If it's annoying you, try 1.10.2 or below.
