### ISSUE TITLE
Can't open the fireplace

### ISSUE THREAD

**Issue by IForseeYou** [Wynncraft/Issues#6741]
I can't seem to throw tribute into the other eye of the beast...
![2016-11-21_12 47 18](https://cloud.githubusercontent.com/assets/23572916/20471031/ed96f08c-afe8-11e6-8264-39cea79106ec.png)

**Comment by Thegamerplus1** [comment]
change server

**Comment by Moe-Ronickah** [comment]
@IForseeYou , did changing servers fix this for you?

**Comment by IForseeYou** [comment]
yep
