### ISSUE TITLE
After Completing Craftmas Chaos Quest I Went Back Into The Portal And Coudnt Get Out Help Me!!!

### ISSUE THREAD

**Issue by PinkAhNeh** [Wynncraft/Issues#6742]
So I Finished The Craftmas Chaos Quest And I Accidently Went Back Into The Fireplace Portal So I Tried To Go Back Using The Hour Glass Building But it Didn't Work Im Stuck Now Help Me!!!

**Comment by LordHelmchen98** [comment]
You can either walk through again and just go to the places where you get teleported or do /kill if have more than 5 soul points.
