### ISSUE TITLE
Can't join the server

### ISSUE THREAD

**Issue by Elmaric** [Wynncraft/Issues#6743]
Hello,
Every time I try to join the server since yesterday night, I can't connect at all on Wynncraft. Is there any issue  because this is very annoying :/
Here is the error message : Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException
Thanks,

Elmaric

PS: I live in France so yesterday night isn't the same time for you I think

**Comment by Surra-1** [comment]
Try to connect with play.wynncraft.org, or play.wynncraft.net. Other than that, you can might just have to wait a bit.

**Comment by Elmaric** [comment]
Ok,
I have already tried every possible version and every possible IP before, I forgot to mention it.
And that's already 21 Hours I wait :'(

**Comment by thecoolkogut4** [comment]
every version as in ip versions? or Mc version?

try to join on 1.8.8 with no mods and connect to either .net or .com

**Comment by Elmaric** [comment]
Okay ! It worked in 1.8.8 and after working in this version it now works in every version ... Idk why, but thanks

Elmaric

**Comment by Moe-Ronickah** [comment]
RESOLVED
