### ISSUE TITLE
HELP! Won't let me connect

### ISSUE THREAD

**Issue by judeclark** [Wynncraft/Issues#6744]
For some reason, it will not let me connect to your server. I have tried everything from restarting my game to re-installing my game. PLEASE HELP ME!!!

This is what the error says:
"Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException"

P.S I have also tried changing it from .org and .net AND tried changing MC versions, but I have had no luck from doing this, it only let me do this for a very short amount of time and it's not letting me do it anymore

**Comment by thecoolkogut4** [comment]
I know you said you switched versions but did you switch to 1.8.8? with .com and .net?

**Comment by judeclark** [comment]
yes, i have

**Comment by Moe-Ronickah** [comment]
@judeclark , are you still having this problem?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
