### ISSUE TITLE
wynncraft map is broken.

### ISSUE THREAD

**Issue by CommonSentence** [Wynncraft/Issues#6745]
The wynncraft map is broken for me, idk about other players, but when i open the link, all it says is "If you can see this message, there is likely a problem loading the Overviewer javascript components. Check the javascript console for error messages." the wynncraft logo and a black screen... that is it xP idk if you know about this already if it is my side though, how can i fix this? xP https://gyazo.com/b3d6ea8a70e8922c23be0932bd382400

**Comment by princessbinas** [comment]
It's broken for me too. It did not give me any errors that related to the map in the console though.

**Comment by N8Lars** [comment]
Happened to me too yesterday and man is it frustrating trying to play this w/o a map.  Don't know if it has a connection to the issue, but the problem occurred after I had logged into my feed the beast server.

**Comment by LordHelmchen98** [comment]
Normally it works again after a while. If it doesn't I don't know if that helps but you could try to delete all your cookies for that page.

**Comment by Moe-Ronickah** [comment]
dupe #6245

**Comment by SupremeOtashi** [comment]
same is happening for me...
