### ISSUE TITLE
Can't enter factory in An Iron Heart Part II

### ISSUE THREAD

**Issue by DESTRUCTOR987** [Wynncraft/Issues#6746]
So i can't get into the factory even though i have the factory helmet from iron heart one and i am trying to do iron heart 2 and it wont work.

**Comment by thecoolkogut4** [comment]
you need to talk to a npc (forget the name) then put the helmet on. after you give the emeralds you go to a NPC then to the factory. 

what does your quest book say?

**Comment by ColinRioux** [comment]
Are you sure you're following the correct steps like @thecoolkogut4 said above? 
See here: [wiki](https://wiki.wynncraft.com/index.php?title=An_Iron_Heart_Part_II)

**Comment by Trixter313** [comment]
Let us know if the issue is resolved now, thanks!

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
