### ISSUE TITLE
Strange Item Bug (Rip 3 Stacks le)Important

### ISSUE THREAD

**Issue by oOTheExpirienOo** [Wynncraft/Issues#6748]
I selected a class (i had laags at the moment) then i was in the black box with the archer class select item in my hotbar and I dropped it, after 1min i joined the wc and my ignis was in the middle of no where.Pls say me theres a way to get my ignis back thats all whad i had.

**Comment by LordHelmchen98** [comment]
Im pretty sure there isn't. D:
I guess you know Wynncrafts norefund policy. :/

**Comment by oOTheExpirienOo** [comment]
I hope they can give me my ignis back i have 0 emeralds or other weapon what i can use.

**Comment by thecoolkogut4** [comment]
they won't give you your Ignis or any other item back from staff because of their strict no refund policy.

**Comment by oOTheExpirienOo** [comment]
So ist useless to create this issue

**Comment by thecoolkogut4** [comment]
pretty much, yeah. you were lagging and accidently threw a item out.

**Comment by oOTheExpirienOo** [comment]
Yes the item what you click to select your class
