### ISSUE TITLE
Flight in Distress

### ISSUE THREAD

**Issue by CaptainTerrible** [Wynncraft/Issues#6749]
There is a glitch in the Flight in distress quest that is game breaking
after i accidently fell off while exploring i had to kill myself to get back but when i returned to the airship it started me from the beginning (i had just finished helping the mechanic) when i attempted to go back to where i left off the quest demanded me to find the child again but afterwards i was unable to speak to Captain Ackbar and i was therefore stuck without a way out

**Comment by Surra-1** [comment]
Throughout the quest you go through multiple tp  regions that move you to duplicates of the ship. Each duplicate has different npcs, so if you are to die you must make sure to go back to the spot you were at before. Follow  the steps of the quest, and you should get back to where you left off.

**Comment by LordHelmchen98** [comment]
In addition to the previous post, just go to every spot where you get teleported don't try to talk to the npc's again until you get to the point where you died in your previous attempt.

**Comment by thecoolkogut4** [comment]
go on the wiki, look at where it says you get tped go to thouse spots and soon enough you'll be back at where you left off

*as they have said above me

**Comment by Moe-Ronickah** [comment]
Please do a proper search for "Flight in Distress".  You will find 32 issues, including this one.  The advice is going to be the same for most of them: walk through the quest from the very beginning, eventually, you will get to where you left off.  Or fell off.
