### ISSUE TITLE
FML The game hates me

### ISSUE THREAD

**Issue by EpicfaceXD** [Wynncraft/Issues#6759]
Dear admins,
My username is EPlCFACE (the capital i in my name is a lower case L) and my main account is a lv 80 mage. I was on server 1 and around 9:40 pm 11/22/16, I drank a drunkness potion I found on the ground in Detlas just for fun. Because I saw it lasted for 2 minutes, I switched to my lv 23 archer account to do some trading. When I return as my mage 15-20 minutes later, I find that all my armor is gone, including: Spectre (31% spell damage), Millenium (220-230 spell damage), Kratke (20% spell damage), and Sodeta boots (11% spell damage and 30% XP bonus).
I am not sure if this has happened to anyone before but to anyone seeing this, could you please help me?
Thanks a lot.

**Comment by EpicfaceXD** [comment]
I was reading forums on the "strict no refund policy" I keep seeing and I guess after reading it, my problems can't be solved unless I have recording proof. Sorry for the trouble of asking.
Thanks anyways,
EPlCFACE

**Comment by LordHelmchen98** [comment]
I can understand why you asked but as you already found out it's not possible to get your armor back. However you are by far not the only one facing that issue.

**Comment by thecoolkogut4** [comment]
I guess you got too drunk and threw everything out. don't drink and play wynn :)  your right about the no refund policy.

**Comment by EpicfaceXD** [comment]
I miss my sodeta boots already ;-;
