### ISSUE TITLE
Unable to remove Yellow & Purple Crystal Fragment

### ISSUE THREAD

**Issue by RavenTheWise** [Wynncraft/Issues#6760]
I would like to Remove the Yellow & Purple Crystal Fragments, I cannot do this due to them being Quest Items. Can you help me?

**Comment by LordHelmchen98** [comment]
If you have done Wynnexcavation site d already and are sure you don't need them anymore, you can just put them into your daily chest to get rid of them.

**Comment by RavenTheWise** [comment]
Thanks, Will do when i get home!
