### ISSUE TITLE
Wolf Paw dissapeared

### ISSUE THREAD

**Issue by INTRUDER74** [Wynncraft/Issues#6762]
recently playing, I had joined a server in which 2 of my accessories (ring and bracelet) popped out of their slots, mentioning they had needed __ of this stat, etc. They were both in my inventory at the time, but when I clicked on the wolf paw to put it back in, it simply vanished. I looked all over the floor, and clicked on every inventory spot just incase it was a visual bug. I tried joining another server, and that did not work either. I know, its not the greatest bracelet, but it really did help, if there's any way to get it back, please contact me.

  P.S, the ring is still there, just the bracelet is gone.

**Comment by thecoolkogut4** [comment]
the server has a strict no refund policy, staff will not be giving you the bracelet back. if you want another one you would have to ask players, buy one, or open up a lot of loot chests

**Comment by INTRUDER74** [comment]
Ok, thanks for the response, I just wasn't sure if there was anything I could do.
