### ISSUE TITLE
Quest bug 

### ISSUE THREAD

**Issue by Ekute** [Wynncraft/Issues#6763]
I can't finish Thieving Rode (quest lvl 2)
I found lot of wedding ring, but i can them give to Farmer Kelri.

**Comment by LordHelmchen98** [comment]
The wedding rings you get from the normal silverfishes are not the correct ones. Search for a cave with the "Giant Rat" inside. Kill that rat and bring the drop of that rat to Kelri.

**Comment by Ekute** [comment]
Nice thanks you :D
