### ISSUE TITLE
Old quest issues  Lord of the clock

### ISSUE THREAD

**Issue by SlyGuy1809** [Wynncraft/Issues#6765]
Hello, I was just wondering if I can fix this. Ok well it been quite a while since I have been online and I can see that there has been a few changes. So I was gonna finish a quest I started before I left but for the quest part where  I have to throw the clock in to the lava pit I could not do it because I had no clock? So I looked at many lets plays to figure it out but nothing helped. So this is the last place I had to go to get help. Any info is helpful.

_Sly_Pamuya_

**Comment by ColinRioux** [comment]
Align what's in your quest book with the stage in: [https://wiki.wynncraft.com/index.php?title=Lord_of_the_Clock](https://wiki.wynncraft.com/index.php?title=Lord_of_the_Clock)

**Comment by SlyGuy1809** [comment]
Ok so I tried to follow the quest and I did what it said but when I right clicked on Frudo nothing showed up in the chat log.  it was no text just a bunch  of empty space. please help.

**Comment by LordHelmchen98** [comment]
You should try if the command /fixquests gives you the clock back.

**Comment by Trixter313** [comment]
Did @LordHelmchen98's suggestion resolve your issue or is it still not working?

**Comment by akiradm** [comment]
i tried fixquests but i dident get a clock can someone help me with this cus i have the same problem D:

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
