### ISSUE TITLE
Boats

### ISSUE THREAD

**Issue by NeatoBurrito** [Wynncraft/Issues#6770]
I realized I'm a chump but bear with me.
I bought 2 2 EB boats from Nodguj and when I tried right clicking or pressing Q the boat would not successfully be placed down. When I left clicked, the boat was placed down and promptly disappeared. The second time I managed to get on but the chunks weren't loading and when time caught up with itself, there was no boat and I had lost 4 EB total. I have forgotten the price of boats and how to maneuver them so can someone tell me how boats work or can I get a 4 EB refund?

**Comment by LordHelmchen98** [comment]
Normally you just right click on water (on the ground is possible as well to have some fun xD) and then right click it again to enter.
And you wont get back anything due to wynncrafts strict norefund policy.

**Comment by NeatoBurrito** [comment]
> Normally you just right click on water 
I've done that twice and lost 4 EB

**Comment by NeatoBurrito** [comment]
> Normally you just right click on water    


I've done that twice and lost 4 EB

**Comment by NeatoBurrito** [comment]
> Normally you just right click on water 

doesn't work

**Comment by LordHelmchen98** [comment]
Which Minecraft version are you using?

**Comment by Moe-Ronickah** [comment]
@NeatoBurrito , that sounds so glitchy, that I would have closed Wynn, closed MC, and started both back up.  Is this still going on?

**Comment by DebugMC** [comment]
@Moe-Ronickah @LordHelmchen98 @NeatoBurrito Its a odd bug in vanilla, its just a bug. Just click the slot your boat was on in your inventory and you will have it again. This is a really odd bug that has been happening for a long time.

**Comment by TBlazeWarriorT** [comment]
I have lost a boat a few days ago and havent found it (All my bank and inventory was moved, still no boat). It's really, really unlikely that I dropped the boat too, and I'm not exactly sure when I lost it, but I'm quite sure he isn't coming back, nor have I dropped it.

**Comment by DebugMC** [comment]
Known bug. Click the slot in your inventory where your boat was. Also boats are destroyed when running into blocks so it is possible you were lagging and the boat hit a block you hadn't seen.
