### ISSUE TITLE
Falling to the void bug

### ISSUE THREAD

**Issue by FrozenJelly** [Wynncraft/Issues#6773]
so first off im just sit at detlas and this happen http://imgur.com/a/ng1S5 i dont really know wat is this but when im log off and log back in to lobby like normal day but when im log in WC server this happen http://imgur.com/a/D4Q7X  i can only do /lobby command

**Comment by rainbowx1994** [comment]
Having the same problem too :( Hopefully it will be fixed soon.

**Comment by Moe-Ronickah** [comment]
@FrozenJelly  and @rainbowx1994 , is this still happening, or are you able to get back in-game?

**Comment by rainbowx1994** [comment]
Its still happening :(

**Comment by Moe-Ronickah** [comment]
I know that we got jelly back in.  @rainbowx1994 , did we get this resolved for you?

**Comment by DebugingLonks** [comment]
it happens to me occasionaly, but i can get out of it via picking a class/relogging...

**Comment by Moe-Ronickah** [comment]
RESOLVED
