### ISSUE TITLE
Red crystal shard

### ISSUE THREAD

**Issue by Elmaric** [Wynncraft/Issues#6774]
Hi,
I'm a level 70 assassin and when I decided to do the quest WynnExcavation D I decided to take all 3 shards in my enderchest but when I took the red one, I lagged and it litteraly disappeared from my inventory and my enderchest, and it was not on the ground. I can't progress anymore, please help me !
Is it possible to get back "Red crystal shard" (Quest item not untradable item) ?
Thanks,

Elmaric

**Comment by LordHelmchen98** [comment]
Do /fixquests. If that doesnt work you have to get the shard with another class. :/

**Comment by Elmaric** [comment]
So if it doesn't work I'll have to create another character and level it up to lv. 55 ...

**Comment by Elmaric** [comment]
Because it actually doesn't work ...

**Comment by Elmaric** [comment]
Can anyone help me ?

**Comment by LordHelmchen98** [comment]
Doubt it. Wynncraft has a strict norefund policy and no player can give it to you as it is a quest item.

**Comment by Trixter313** [comment]
Have you double checked all of your classes and bank to make sure it isn't in any of those locations? You could also try clicking on the empty spaces in any inventories to see if it is hiding in one. Unfortunately if that doesn't help and /fixquests doesn't return it there might not be a fix for a while.

**Comment by Moe-Ronickah** [comment]
Put as many items from your player inventory into your enderchest, then try /fixquests.  Let us know if this works.

**Comment by FalconAl** [comment]
I also have the same problem but I am missing the Yellow Shard quest item. Do I **have** to use another class to repeat the same quest to get the quest item?

**Comment by LordHelmchen98** [comment]
@FalconAl If you have to do Wynnexcavation Site B and you can neither find the Yellow Crystal on another class nor get it back by doing /fixquests you will have to start a new class if you want to finish the quest with your main class. You can finish Site A with your second class and put the Crystal into your bank then take it with your main class and use it for Site B. However the second class will then have the same problem.

**Comment by Moe-Ronickah** [comment]
Hang On Snoopy!!  @Elmaric and @FalconAl , without any fanfare, the quests were changed so that you don't have to have the crystals taking up inventory space.  Go try the next stage, and see what happens.  Let us know what happens.  Good Luck!!

**Comment by Moe-Ronickah** [comment]
With no comments from the players having trouble, I'm closing this because the issue has been resolved.
