### ISSUE TITLE
Falling into the void during class selection

### ISSUE THREAD

**Issue by rainbowx1994** [Wynncraft/Issues#6775]
So I am trying to play on the Wynncraft server and every time I enter a world, I end up falling into the void and it doesn't show me any class selection box. 

Here is what happens about 10 seconds after I enter the world http://imgur.com/KLALKtP

**Comment by rainbowx1994** [comment]
Can anyone answer my question? :(

**Comment by Imaxe** [comment]
This happens if your internet connection is bad. Do you have bad connection?
If not, I'll talk to Salted about it :)

**Comment by rainbowx1994** [comment]
No its not my internet connection. I have tried everything.
I just keep falling into the void with no class selection :/

**Comment by Moe-Ronickah** [comment]
dupe #6773
