### ISSUE TITLE
Unable to complete Death Whistle

### ISSUE THREAD

**Issue by Grauly** [Wynncraft/Issues#6780]
I cant complete The quest "Death Whistle" cause the wich dosnt drop the flower. I tyred several times on different servers but it didnt work.

help me.

**Comment by ColinRioux** [comment]
There has been a new boss implementation to a few mobs, one being Sayleros' brother. To tell if this has been implemented on the witch, a few things can happen:
1. The witch respawns directly after.
2. The respawn has less health than the first one. 
3. After a few kills, it will drop.

**Comment by LordHelmchen98** [comment]
So your quest book tells you to kill the witch and you are sure you didn't skip the part where you have to go onto that mountain? Did you try it on different servers? That may sound dumb, but I did this quest today and it worked perfectly fine when I did it.

**Comment by Grauly** [comment]
so...  found out:
-you are not allowed to use escapespell in order to get to the laef. I used escape. I re-did it, gave him the leaf. and than went to the witch. The witch didnt drop the flower. what now?

**Comment by Imaxe** [comment]
@Grauly Are you sure that you're killing the correct witch?
Since @LordHelmchen98 completed the quest with no problem I doubt it wouldn't work for you.
Try looking up a quest guide on how to complete it

**Comment by LordHelmchen98** [comment]
Are you sure you killed the witch in the cave where the pink carpets on the ground are leading to? There is a second but wrong witch on a mountain pretty much next to it.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
