### ISSUE TITLE
Lost Sanctuary glitch

### ISSUE THREAD

**Issue by deathcorecrafter** [Wynncraft/Issues#6781]
me and my friend (dragonSlayerIN) were in the Lost Sanctuary by the bridge but when my friend was re-log because of the internet him items just disappeared. item by item even he have still the soul points total: 12 so is there maybe a way too fix this because I friend become very mad from this bug or something
and he didnt choose a other class

**Comment by Moe-Ronickah** [comment]
Did your friend die every time that he logged back in?

**Comment by deathcorecrafter** [comment]
no he didnt die because i protect him so he can re-log with dying

**Comment by Rellia** [comment]
has he tried clicking where his items were in the inventory? They may have still been there. And is this the corrupted Lost Santuary? Or just the normal Lost Sanctuary?

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.

I also have tested Lost Sanctuary numerous times on our testing server, and have had no issues. In the next map update (corkus), any changes made to this dungeon will be reflected on the main server.
