### ISSUE TITLE
Cant upgrade skill points

### ISSUE THREAD

**Issue by SAT9** [Wynncraft/Issues#6782]
I reset my skill points by clicking on the compass and confirmed it and now i cant upgrade them back because the books that you click on to upgrade have disappeared. It says I have 52 skill points to spare and  I cannot use them. Also the reset skill points button has disappeared. Please advise. 
![2016-11-26_16 31 37](https://cloud.githubusercontent.com/assets/24192499/20641932/da9097d4-b3fa-11e6-9be3-4ba906a513d0.png)
![2016-11-26_16 31 44](https://cloud.githubusercontent.com/assets/24192499/20641936/e7dd0814-b3fa-11e6-8f65-d913c5ff1d6c.png)

**Comment by LordHelmchen98** [comment]
Does this happen on every server?

**Comment by Moe-Ronickah** [comment]
By now, you have logged off and back on.  Is this still happening?

**Comment by SAT9** [comment]
yes and yes. Anyway its fine now, i just used an older version of minecraft: 1.8.9
