### ISSUE TITLE
There is no scroll icon 

### ISSUE THREAD

**Issue by pinkjemm** [Wynncraft/Issues#6783]
I was trying to see on the wynncraft map (most useful tool for exploring wynncraft) when i realized there is no scroll icon on Nesaak on the map but there a scroll merchant in game

**Comment by LordHelmchen98** [comment]
Yeah there are some wrong icons and also missing icons (e.g. the key merchant for the old animal dungeon). Staff knows about it and will hopefully fix it in future.

**Comment by pinkjemm** [comment]
thanks
