### ISSUE TITLE
Need stringy hair item to complete the shadow of the beasts 

### ISSUE THREAD

**Issue by Lufs** [Wynncraft/Issues#6787]
Im a Lvl 54 Assassin My Username is SouthKouria And i accidently threw out the stringy hair item to complete the shadow of the beasts quest And now He Cant get it Back And I cant Finish The Quest Pls Comment To Help!!!!!

**Comment by BlueDragonzz** [comment]
Do /fixquests, that should give back missing quest items to any quests you are doing, if not I am sorry that I have wasted your time.

**Comment by Lufs** [comment]
Its a Untradable Item Not a Quest I am In need of help from a Administrator!

**Comment by ColinRioux** [comment]
Hi what does it say in your quest book?

**Comment by Lufs** [comment]
This Was Fixed. Closed
