### ISSUE TITLE
I lost my Bob's Mythical Bow with 2 Tier 4 Air powders and 1 Tier 4 Water powder!

### ISSUE THREAD

**Issue by BlueDragonzz** [Wynncraft/Issues#6788]
Hello wynncraft staff. I was in the Undergrowth Ruins dungeon with my friend, and I accidentally threw the bow into the token hopper. I have at least 4-5 eye witnesses that know I have the bow, and at least 1 of them knows I have the powders. I was wondering if you could respond back to me soon, because I just got the bow the day I lost it, and I really want it back.

-Thankyou for taking your time to read this thread.
-BlueDragonz

**Comment by LordHelmchen98** [comment]
Unfortunately you won't get it back due to wynncrafts strict norefund policy :/

**Comment by BlueDragonzz** [comment]
:(
Why does that have to be a thing. I was using a level 55 bow for so long, and I was looking for ward to this bow. This item is supposed to symbolize that you beat one of the greatest warriors and you are actually good at the game. Now people will think I look like a fool since I did one wrong mistake. They will laugh at me for my clumsiness. :/

**Comment by BlueDragonzz** [comment]
I know pleading won't help but please, I am desperate for this. This was the only good bow I have got in a long time,/ I know this probably won't work, but please, I'm begging you. I just want the bow back since it symbolizes that you beat the hardest boss in wynn ( and not gavel) I know this won't work probably but this is my last cry for help, I am desperate :(

**Comment by ColinRioux** [comment]
Like @LordHelmchen98 said, Wynncraft enforces a strict no-refund policy. This is put in place to maintain fairness among all players. Although it may sound "unfair" or "horrible", it actually also let's the staff team do their jobs and help improve Wynncraft. 

In the future, please don't open a new issue if it's referring to lost items (i.e, dropping them into a hopper). Instead, ask if you could buy one off someone via the store section of the forums or ingame.
