### ISSUE TITLE
I Lost A Stack of LE to a Reroll glitch

### ISSUE THREAD

**Issue by Heysou1** [Wynncraft/Issues#6795]
![2016-11-27_12 00 40](https://cloud.githubusercontent.com/assets/24211705/20651379/37fa7af4-b499-11e6-9bf8-a609f373c9dc.png)

![2016-11-26_15 28 57](https://cloud.githubusercontent.com/assets/24211705/20651376/2ced907e-b499-11e6-8b80-c6589e5d824e.png)

I was doing a mythic trade for Az. It was with koren_99 and I was paying a stack of LE plus a 41% Xp bonus Bad Wolf along with a few other items. The reroll happened on World 10 and when I logged back on (World 10 was down so I moved to 11) the stack of LE was missing and so were my Bad Wolf.

**Comment by ColinRioux** [comment]
Hi, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.
