### ISSUE TITLE
"A Grave Mistake" Quest Bug (Barriers)

### ISSUE THREAD

**Issue by MikeCGZ** [Wynncraft/Issues#6797]
Greetings reader,

I've been going through the quest a grave mistake and I've gotten to the final cutscene when it says "you've come this far... I guess I'd better show you the truth" and now I got stuck so I did /kill. I thought I could use this to get out of the barriers. It worked but now I can't finish the quest and I can't restart it! Please help!

**Comment by LordHelmchen98** [comment]
Try to go into the huge door do the last part again. Hopefully you get teleported if you do it again.

**Comment by MikeCGZ** [comment]
LordHelmchen,

I cannot do what you have instructed as it no longer lets me go there. I am at the area of the quest where you first start and that door no longer opens. I need to reset the quest if possible or get back to where the large doors are located. Please see if you can do something to help me as I would like to see how this exiting quest ends.

**Comment by MikeCGZ** [comment]
Please disregard all previous reports as I have fixed my quest.
