### ISSUE TITLE
Wynncraft Excavation Site C

### ISSUE THREAD

**Issue by Retains** [Wynncraft/Issues#6798]
Okay so i have already done the quest on my level 89 Assassin no issues but this time i tried to do it on my archer and my warrior but apparently i don't have any crystal shards exept for the very first one, when i try do '/fixquests' it just says no missing quest items can be found. Please fix this Wynncraft i have also found many bugs to do with /fixquests which have been a issue when i had to start new classes just to get certain quest items. IGN: Retains

**Comment by LordHelmchen98** [comment]
/fixquests is known to be bugged especially with shards of the Wynnexcavation quests for a long time. So yeah let's hope staff finds some time to fix this.

**Comment by Moe-Ronickah** [comment]
@Retains , do you have any open space in your player inventory, at least 8 slots open, when you try using /fixquests?  Have you checked all of your other classes to see if the shards are on them?

**Comment by Retains** [comment]
I have checked all other classes i also lost about 5 Legendarys of high value and i did have atleast 8 slots open

**Comment by Retains** [comment]
I have checked all other classes i also lost about 5 Legendarys of high value and i did have atleast 8 slots open

**Comment by Moe-Ronickah** [comment]
I'm sorry.  Are you saying that you "lost about 5 Legendarys" due to /fixquests?

**Comment by Moe-Ronickah** [comment]
Without any fanfare, the quests were changed so that you don't have to have the crystals taking up inventory space. Go try the next stage, and see what happens. Let us know what happens. Good Luck!!

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
