### ISSUE TITLE
I stuck in somewhere

### ISSUE THREAD

**Issue by dkswoqkfl** [Wynncraft/Issues#6799]
I slept in a bed and when I woke up I was in small place. And teleport scroll doesn't work. Please help me

**Comment by LordHelmchen98** [comment]
If you have more than 5 soul points do /kill to get out.

**Comment by Moe-Ronickah** [comment]
Yes, you are in a small place; your head is in a layer of blocks directly above the bed.

NEVER sleep in a bed on a server - you won't make the server go to sleep, and you will get trapped.
