### ISSUE TITLE
Memory Paranioa; Master key not working

### ISSUE THREAD

**Issue by sandzila** [Wynncraft/Issues#6802]
I got the master key from the kid's room and took it to the master bedroom, the game then told me I needed a key to enter even though I had one. 

I tried dropping the key and getting a new one but no luck
I even tried going in with multiple copies of the key but still no luck
Relogged and tried with old keys: no luck
Dropped all old keys, relogged got new key: failure

I'm out of ideas here and would like to finish this quest

**Comment by LordHelmchen98** [comment]
Sometimes there are problems with the tripwires on the floor. Are you sure you activated every necessary tripwire?

**Comment by sandzila** [comment]
Okay so I found a work around, you have to go to the door "after the warping" then drop the key and pick it up again I order for the door to accept it.
