### ISSUE TITLE
Wynnpack not working

### ISSUE THREAD

**Issue by PsychoNater** [Wynncraft/Issues#6806]
When I go onto a world in wynncraft it says downloading wynnpack the resourse pack but it does not download this is really bothering me so plz fix it my username for minecraft is PsychoNater

**Comment by LordHelmchen98** [comment]
Once you joined a server you can try to press F3+s or F3+t to reload your textures.

**Comment by PsychoNater** [comment]
it still won't load

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
