### ISSUE TITLE
Lost Tier 2 Horse and stuck in a 2x2 fence

### ISSUE THREAD

**Issue by bySparkie** [Wynncraft/Issues#6809]
I was riding my Tier 2 Horse, when I suddly got teleport back, and got stuck in a fence(2x2).
I tried everything, but it didn't help. And all of the sudden, my horse(item) was gone. I don't know if I dropped it or something, but it disappeared. I would appreciate it if I would get my Tier 2 Horse back. Thanks for noticing.

Note: If my spelling is bad, I'm terribly sorry, but I'm from Austria. :)

**Comment by LordHelmchen98** [comment]
To get out of that hole do /kill if you have more than 5 soul points.
And unfortunately wynncraft has a strict norefund policy. Therefore you wont get back your black horse :/
