### ISSUE TITLE
Attack Effects

### ISSUE THREAD

**Issue by Locky1110** [Wynncraft/Issues#6810]
A few days ago i bought VIP+ and one of the crates i opened contained an attack effect. i clicked it but now i cant shut it off. is there a command that can do it?

**Comment by LordHelmchen98** [comment]
I think it should be possible to just click it again in order to turn it off.

**Comment by LordHelmchen98** [comment]
Nvm I just got an attack effect (didnt have one so far as I got vip+ only two days ago) and it doesnt work for me as well.

**Comment by Moe-Ronickah** [comment]
Your issue is a duplicate of #6623  .  You can follow your issue on that thread.
