### ISSUE TITLE
Missing skill books in player menu

### ISSUE THREAD

**Issue by YoshiPoshi** [Wynncraft/Issues#6812]
It's been around about 4 years since I last played Wynn so my account's probably gone through many versions. I came back on to play today and found I had a ton of skill points to spend but when I clicked on the compass there were no skill books in the middle. I clicked in the area where it should be and I apparently was able to spend a skill point. 

So basically my problem is that my skill books are invisible and I can't see what skill I'm clicking or how many points I have in each skill.

![wynncharinfo](https://cloud.githubusercontent.com/assets/24285764/20781722/19a50080-b753-11e6-85c8-7de077cb05ca.png)

My IGN is LiberalLiability

**Comment by LordHelmchen98** [comment]
Which minecraft version are you using? It should work in 1.8 or 1.9.

**Comment by legoman724** [comment]
This also happens to me and I'm using 1.11, just put a skill point in the skill and the book will pop up

**Comment by YoshiPoshi** [comment]
Thanks guys! It works now!

**Comment by Moe-Ronickah** [comment]
RESOLVED
