### ISSUE TITLE
Dungeon Hoppers for tokens broken

### ISSUE THREAD

**Issue by DrainLegacy** [Wynncraft/Issues#6813]
I was doing the Infested Pit dungeon on level 52 as i had never did it before,but when i was about to drop in the tokens for the "Slay" subquest,i accdientally dropped my wand "Curse" in.It had Water IV and Earth IV powder enchantments on it.Needless to say,i didn't manage to get the wand back.Please fix/help

IGN:DrainLegacy

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by Imaxe** [comment]
Sorry but we have a strict no-refun policy so you won't get it back.
