### ISSUE TITLE
Above sky Barrier

### ISSUE THREAD

**Issue by ttykox59** [Wynncraft/Issues#6815]
As you know, there is a barrier that prevents you from getting to high in the gavel region (idk about wynn) and I was able to glitch my way above it, you probably should fill in ever single nook and cranny around the mountains because I accidentally teleported into one with my "teleportation" spell and started to leave and re-join the server to see if I could get unstuck. Instead of getting back down, whenever the map was re-loading, I could move around for a short second or two. This allowed me to jump up the barrier blocks before getting stuck again and onto the top of the sky-barrier...

![2016-12-01_17 26 52](https://cloud.githubusercontent.com/assets/16859065/20815905/cd113446-b7ed-11e6-9565-c5ff81b019ba.png)

**Comment by LordHelmchen98** [comment]
So why would anyone want to glitch on top of the barriers? Is there any advantage you get by getting there? Are you able to get below the barriers in another way than scrolls and /kill?
Personally I dont see why this is an important issue that has to be fixed very fast.

**Comment by ttykox59** [comment]
It's probably not that big of a deal, but it allows you to see all the redstone that they have put around the edge of the map. They may want to fix it if another quest like ??? comes out because you can find it's redstone stuff (like how I found the wynntron and one of their basic redstone testing sites) 

![2016-12-02_16 57 44](https://cloud.githubusercontent.com/assets/16859065/20859681/2c9d8e6e-b933-11e6-8fd7-57bbeea50b49.png)

**Comment by Villageacules** [comment]
Please don't make issues about you being trapped, use the /kill command to respawn at the nearest town.
