### ISSUE TITLE
wynnpack STILL not working

### ISSUE THREAD

**Issue by PsychoNater** [Wynncraft/Issues#6816]
the wynnpack wills STILL not load when even when I press f3+t

**Comment by ColinRioux** [comment]
Hi, we prefer that you don't post duplicate issues, instead comment on your original post. 

You could try re-adding the wynncraft server. I.e, delete Wynncraft from your server list, and re-add it.

**Comment by PsychoNater** [comment]
I tried that it didn't work either and sorry about the duplicate I didn't know

**Comment by ColinRioux** [comment]
Please send me computer information, i.e operating system, total amount of memory, and minecraft version. As well as internet provider information, which includes going to `speedtest.net`, and giving me your download speed & upload speed, and your internet provider (i.e, Comcast). 

Thanks.

**Comment by PsychoNater** [comment]
sorry I can't give you that information

**Comment by ColinRioux** [comment]
Okay, well a temporary fix would be to download the "legacy" file from [here](https://github.com/Wynncraft/) and place that in your resource pack folder in your minecraft folder. 

Other than that, I cannot help you, I am sorry.

**Comment by Synchr0** [comment]
hi, i would like some help because my wynnpack dont want to load and i read all the topic that i found and this doesn't adjust my problem.
Thank you in advence
![2016-12-04_19 42 04](https://cloud.githubusercontent.com/assets/24374176/20868356/0034d12a-ba5a-11e6-9729-356a2f6ffd6b.png)

**Comment by ColinRioux** [comment]
Try this:

After booting minecraft, click on multiplayer, click once on wynncraft, and then click edit. Then on the option: `Server Resourcepack`, choose prompt instead of enabled/disabled. Then login, and when prompted, click yes.

**Comment by teuntheman** [comment]
if i then still not works try updating your minecraft launcher. This worked by a guy i know. So many it will work

**Comment by Moe-Ronickah** [comment]
DUPLICATE
