### ISSUE TITLE
My Emeralds!

### ISSUE THREAD

**Issue by WynncraftLover123** [Wynncraft/Issues#6817]
I am a level 32 archer class on Wynncraft in Almuj. I was grinding to be able to access the Stable Story quest and recieved multiple unidentified items. I went to the bank to get some more emerald blocks and I was kicked from the game, while dragging the emeralds to my inventory. I logged back on and looked in my bank to see them all gone, an empty space where they should have been! It was around 47 blocks and I now no longer have them. I love playing Wynncraft but this might have stopped me because now I only have the emeralds on me and my other classes. Please help!
Cheers.

**Comment by WynncraftLover123** [comment]
My Minecraft name is ItzDaBoi if that is important.

**Comment by ColinRioux** [comment]
Unfortunately, Wynncraft enforces a strict no-refund policy. This means you
won't have your items returned to you. This may sound unfair, but
it actually maintains fairness among the player base. I'm sorry.

**Comment by WynncraftLover123** [comment]
Now I can't finish the Stable Story quest because I can't afford a horse. RIP Wynncraft 2016.

**Comment by ColinRioux** [comment]
Actually, you get a horse as a result of the stable story quest. Buying one
is only required after completion if you need a new one or want to attempt
to upgrade your tier. See:
https://wiki.wynncraft.com/index.php?title=Stable_Story
