### ISSUE TITLE
Resource Pack problems

### ISSUE THREAD

**Issue by CrazDC** [Wynncraft/Issues#6818]
Every time i log in a server (not the lobby) the resource pack takes a while to load, but almost all the time it disconnects just after the pack loads. Sometimes it disconnects, times out, and rarely it crashes. But, when it doesn't disconnects, I don't have any lag or anything bad after that, so I havee to join and enter the server, usually, 4 to 8 times to play.

**Comment by ColinRioux** [comment]
Try the second to last comment [here](http://www.minecraftforum.net/forums/support/unmodified-minecraft-client/2447420-minecraft-crashes-every-time-that-i-try-to-use-a).

This has been a global issue, not specifically for wynncraft. I have gotten this before, and sometimes it's related to internet and sometimes it's related to your client. Try what is suggested, and if it doesn't work recomment.

**Comment by CrazDC** [comment]
The problem, in my case, is that it only happens on Wynncraft, in that forum post they talk about Hypixel, but Hypixel's resourcepack always loads correctly (and other servers too). I tried what the comments you suggested said, but it didn't work.

**Comment by CrazDC** [comment]
Ok, my sister fixed it. She changed the resource pack from enabled to prompt and downloaded it again.
