### ISSUE TITLE
Can't finish headless hunt.

### ISSUE THREAD

**Issue by Venemian** [Wynncraft/Issues#6819]
I have 2 memento of the lost but nothing happens when I kill the trapped souls besides memento of the lost dropping. No updates in book, no messeges in chat or on screen, and what I believe to be is the exit to the cave, behind the gulloutine looking thing is blocked by an invisible wall. help me!~

**Comment by Venemian** [comment]
Well, there is also a weird sound but it ends and still nothing happens.

**Comment by ColinRioux** [comment]
Well, I'm going to direct you to the [wiki](https://wiki.wynncraft.com/index.php?title=The_Headless_Hunt). 

If you have followed the wiki through, and still believe you have discovered a **bug**, please re-comment. This place isn't for "quest help" but for bug reports. 

If this is a bug report, could you please be more specific and provide screenshots and/or a video? 
Thanks.

**Comment by Venemian** [comment]
So, according to the wiki, I should be on Stage 8, and I am.

Even after I kill the trapped spirits, nothing happens, and I am scared to attempt to use a scroll in case I mess the quest up even more. I am on MC 1.11 although I doubt that matters because the all 7 previous stages worked out fine. Also, yes I re-logged to see if it would fix itself.

https://youtu.be/AfUQu-KZD80

**Comment by Venemian** [comment]
Please help me this still isn't fixed.

**Comment by ColinRioux** [comment]
The best thing you can do right now is be patient. In fact, the developers have so much on their plate right now that they aren't going to jump to your request, even if you donated or not. 

I will take a look into it tomorrow afternoon, in the meantime, either wait, go outside, start a new class, or do something productive.

**Comment by Venemian** [comment]
Alright, thanks anyways I guess.

**Comment by LordHelmchen98** [comment]
There is no update that should happen after you defeat the Trapped Souls, but there are some coal blocks which teleport you outside that room. When you got teleported you should be able to return the drop to Referick.

**Comment by Imaxe** [comment]
As @LordHelmchen98 said, you have to return to Referick with the soul.
