### ISSUE TITLE
Randomly got teleported to the beginning of Wynn during a quest! :(

### ISSUE THREAD

**Issue by Fr0sto** [Wynncraft/Issues#6821]
I was literally in the middle of talking to Relend for the last time to complete the quest Fantastic Voyage, when the world restarted and I found myself (stuck in the ground) where level 1's start. I don't know how to get back to where I was and I would much like to be teleported there so I can finish the quest. 

My IGN is FrostLord and I was using a level 90 Archer

**Comment by LordHelmchen98** [comment]
As I assume no moderator will teleport you I recommend looking on the [wiki page of Fantastic Voyage](https://wiki.wynncraft.com/index.php?title=Fantastic_Voyage) to see what you have to do. If you want to get back to the stage that you tried to do before the restart, you have to walk through the guest from the beginning (don't try to talk to NPC's, just go to the places where you get teleported.)

**Comment by Fr0sto** [comment]
Just getting back there is a solid 45 minutes worth of work.. let alone going through the entire quest after that. I can do it, I suppose, but can you please get this fixed in the future??

**Comment by Moe-Ronickah** [comment]
This is a known issue, at we are working on trying to find a reliable fix.
