### ISSUE TITLE
Flight in Distress  Quest

### ISSUE THREAD

**Issue by xTheLordPython** [Wynncraft/Issues#6823]
I was doing flight in distress an when i was fighting the pirate queen i died because i forgot pots and now i cant get back to the ship and i cant talk to the captain and its like i never did the quest but when i find the boy it does nothing

Please help me

**Comment by archie426** [comment]
This is probably wrong but try /fixquests

**Comment by xTheLordPython** [comment]
i did that and gave me a elven medallion

**Comment by archie426** [comment]
oh, well I dont know then, sorry

**Comment by xTheLordPython** [comment]
np xD

**Comment by xTheLordPython** [comment]
its sorted now

**Comment by thecoolkogut4** [comment]
go to all of the to regions again that are on the ship. eg: go to the child, go to your room etc.

**Comment by archie426** [comment]
If it is sorted can you close it please?
