### ISSUE TITLE
Health Regeneration Issues (Marzilon)

### ISSUE THREAD

**Issue by Marzilon** [Wynncraft/Issues#6824]
Hello, I would like to address an issue that my friends and I have been experiencing on the Wynncraft server with health regeneration. This issue was not common throughout my whole time playing on the server, but recently my friend and I have been stuck at a certain health level for long periods of time. We did make sure to check our stats to see if possibly something that we had equipped was causing us to slow down our regen. but that was not the issue. If anything could be done to fix this issue please help or contact me if there's anything I could do to help. Thank you in advance! - Marzilon

**Comment by archie426** [comment]
Have you tried hurting yourself and seeing what happens?

**Comment by Marzilon** [comment]
Yes, I have already stated that my health has been stuck at a certain level for well passed the regular time.

**Comment by Marzilon** [comment]
Figured it out on my own, the issue has been resolved.
