### ISSUE TITLE
Cant wear accessories

### ISSUE THREAD

**Issue by SAT9** [Wynncraft/Issues#6825]
I cant wear any accessories

**Comment by ColinRioux** [comment]
You need to be more specific, by providing screenshots or some other sort of visual evidence / aid. 

Can you also confirm you have enough skill points in the proper areas to wear the accessories?

**Comment by SAT9** [comment]
yes

**Comment by SAT9** [comment]
i cant wear any accessories, nothing to do with requirements

**Comment by archie426** [comment]
As @ColinRioux said, please provide a screenshot
