### ISSUE TITLE
Fantastic Voyage Boat Glitch

### ISSUE THREAD

**Issue by alle-nau** [Wynncraft/Issues#6828]
I am doing the Fantastic Voyage quest and I can't get through the obstacles. The obstacles themselves are not too difficult if the barriers/teleporters weren't glitched. If I get even kind of close to a spike, I am immediately teleported back without even touching them. I have actually beat this one time after about an hour of work, and I was teleported back after reaching the end. I hope this will be fixed or looked at! Thanks!

**Comment by ColinRioux** [comment]
Try playing with 1.8.9

**Comment by archie426** [comment]
I would keep this open so the devs can see this. Although people may think this is an unsolved issue

**Comment by Moe-Ronickah** [comment]
DUPLICATE OF #5556 .  Swim it.
