### ISSUE TITLE
Wynnexcavation Site A

### ISSUE THREAD

**Issue by LordHelmchen98** [Wynncraft/Issues#6830]
A few days ago I was doing Site A and when I finished it I only got one yellow shard, but I thought it might be a bug that only happend once (still annoying though). Then a bit later I heard from someone else who did Site A and Site B and both times he only got one shard so he has none left for Site D. So I decided to do it with another class and got only one again. As you need two yellow and red shards (one yellow shard for Site B one red for Site C and one of both for Site D) I think this really shoud be fixed as it will be a big problem for lots of players.
When I did it the second time I recorded it to have proof if it actually only gives you one shard. [Watch it here](https://youtu.be/9RWscHnXcSg)
And before someone replies with the norefund policy, no I'm not asking for a refund I just want this to be fixed to prevent possible issues coming up in the future. (Still going to be annoying to get more shards with classes I will probably delete right after I got the shards xD)

**Comment by LordHelmchen98** [comment]
Nevermind someone just told me you only need the red one for Wynnexcavation Site D now, which I didnt know because nobody I asked before knew it and I was afraid I had to get extra shards if I do Site B and D.

However I think if thats possible it should still be changed in the quest dialogue, because it still says you get 2 shards although you only get one.

**Comment by Rellia** [comment]
Yeah that is weird, but I just thought it was some RP, considering the player is said to have all 4 crystals on them and combines them in site D. But eh.

**Comment by Moe-Ronickah** [comment]
Some of the quests got updated and in order to save inventory space, you no longer need to carry around or store extra fragments.  You "have them", but they are invisible, so to speak.  Don't blame me, I'm just the messenger.

**Comment by peter13212** [comment]
have u tried: /fixquests      :?
