### ISSUE TITLE
"Jungle Fever" quest glitch

### ISSUE THREAD

**Issue by S1imer** [Wynncraft/Issues#6831]
I was doing the "Jungle Fever" questline, and I finally got the LE to bring to World. I brought it, and the guy said, "So you gonna help me?" Or whatever. I checked my inventory, and I only had 63, not 64. I don't know if I wasn't given 64, or if I dropped one. I tried dropping one, and it says, "You will need this item in later quests!" So I couldn't of dropped it. My IGN is "S1imer", and I really need to complete this quest.

**Comment by archie426** [comment]
Hmm, try /fixquests

**Comment by S1imer** [comment]
I tried /fixquests, and it said, "You have no missing quest items... Check your bank and other class inventories". I think it is detecting if you have 1 of the item, not 64, so it doesn't detect I am missing them, I'll see if trading off to other characters work.

**Comment by archie426** [comment]
Oh, strange

**Comment by Villageacules** [comment]
@S1imer Look for the LE in other banks, inventories, etc...

**Comment by Moe-Ronickah** [comment]
Nothing strange here, folks.  It's another duplicate of #5567.  Follow the advice in there, and all will be well.
