### ISSUE TITLE
An Iron Heart Part 2 gwest bug

### ISSUE THREAD

**Issue by PsychoNater** [Wynncraft/Issues#6832]
It won't let me enter the factory even with the rope and the factory helmet from the previos qwest "an iron heart part 1" it says a factory helmet is recaured to enter even thogh I have it on and the rope

**Comment by LordHelmchen98** [comment]
What does your quest book say?

**Comment by PsychoNater** [comment]
never mind I figered it out sorry I was just doing the qwest wrong XD
