### ISSUE TITLE
bug in quest

### ISSUE THREAD

**Issue by EmilyMoon** [Wynncraft/Issues#6833]
Why i have the quest item and i cant finish the quest ? is that a bug ?

**Comment by archie426** [comment]
Try dropping the item and doing /fixquests

**Comment by LordHelmchen98** [comment]
Please describe your issue a little bit better. What quest were you doing? What did it say in your chat?

**Comment by CrazDC** [comment]
If that quest item is an armor part and you have it equiped, take it out. That happened to me with the abysso galoshes

**Comment by LordHelmchen98** [comment]
It might be possible he has to equip it as well (e.g Creeper Mask, Climbing Helmet, Breathing Helmet, etc..)

**Comment by Moe-Ronickah** [comment]
I'm sorry, but there is not enough information here for anyone to help you.  Please make a proper issue report, with full details, and we can try to help.
