### ISSUE TITLE
A grave Mistake Bug,

### ISSUE THREAD

**Issue by DaftReaperr** [Wynncraft/Issues#6834]
I was in the Cathedral in the "a grave mistake" quest and was in the part behind the guardian, I hub'ed / server restart while in the schematic  and i cannot move/ get out.

**Comment by archie426** [comment]
do /kill if you have 12 soulpoints

**Comment by LordHelmchen98** [comment]
Anything above 5 soul points should be enough, but @archie426 is right, do /kill and then go back to the cathedral. It should be possible to walk through again just like you did the first time.

**Comment by Moe-Ronickah** [comment]
RESOLVED
