### ISSUE TITLE
Glitch near Llevigar

### ISSUE THREAD

**Issue by S4trat** [Wynncraft/Issues#6835]
Ok so I didn;t find this bug it was shown to me so I decided to record it here is the video.

https://www.youtube.com/watch?v=pY0F_TH8muU&feature=youtu.be

**Comment by LordHelmchen98** [comment]
Oh wow I guess thats not how its supposed to be xD
@Imaxe I'm pretty sure you can fix this.

**Comment by Imaxe** [comment]
This should no longer be accessible!
Thanks for reporting this issue
