### ISSUE TITLE
BOB DIDNT DROP JUST PAPER.....

### ISSUE THREAD

**Issue by EnderManKing** [Wynncraft/Issues#6836]
1. Bob dropped The items followed in the picture, i was with 2 other people, none of us could pick it up
2. I have fought bob 17 times now with other people, and i have STILL not gotten the paper, plz help this too.
![2016-12-04_08 11 14](https://cloud.githubusercontent.com/assets/20938040/20868699/eb99dd5e-ba1e-11e6-9ffd-6404a861ed34.png)

**Comment by Imaxe** [comment]
The mob drops it's gear if it is killed by another mob

**Comment by dyredhead** [comment]
that's true
bob can be killed by another  mob

**Comment by Rellia** [comment]
You will not get the recommendation letter yourself unless you have contributed to the mobs death by at least part of their health. If you let other players kill the mob for you, you will never get it by just being there. Considering you are level 74 still, and the quest is level 74, it looks to me that you let them deal most of the damage. If you want, I can take part in this too, DMEW_Rell level 81 archer, and I will kite Bob while you attack as much as you can, but let me be the tank. This has worked before with Bob, and CoW.
Also, as stated by these two above, the mobs actual items can drop, usually if they are killed by a mob, but not always, and they are untradeable items, making them impossible for players to pick up, even moderators, unless they are in the admin server. Those items aren't loot, they are the corpse.

**Comment by dyredhead** [comment]
yea what she said
