### ISSUE TITLE
The fortune teller questions room

### ISSUE THREAD

**Issue by legoman724** [Wynncraft/Issues#6840]
When in the questions room in the castle in the fortune teller quest I could visibly see multiple command blocks that were in the room, they were just in midair in the room itself. Note that if other people view them as different blocks it may just be a texture pack issue as I also view some weapons as different ones(eg a dagger might look like a wand)

**Comment by thecoolkogut4** [comment]
try to completely remove/delete your texture pack in the serverresourcepack folder and tetogarcia.  that might fix it.

**Comment by Moe-Ronickah** [comment]
@thecoolkogut4 , I don't know what "tetogarcia" means.
@legoman724 , did removing your texture pack fix the issue, when the texture pack re-downloaded?

**Comment by thecoolkogut4** [comment]
haha autopredict on my phone. dont really know what happend their

**Comment by AscendedKitten** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
