### ISSUE TITLE
wynncraft lost soles

### ISSUE THREAD

**Issue by dyredhead** [Wynncraft/Issues#6845]
gardon doesint allow me to continue the quest after the map clue. any help

**Comment by LordHelmchen98** [comment]
Have you looked at the [wiki page](https://wiki.wynncraft.com/index.php?title=Lost_Soles)? Also what does your quest book say?

**Comment by dyredhead** [comment]
wait ill try

**Comment by dyredhead** [comment]
it worked thanks my book just updated

**Comment by dyredhead** [comment]
it works now

**Comment by dyredhead** [comment]
wait but where is the secret passage you open

**Comment by dyredhead** [comment]
it didn't work never mind

**Comment by LordHelmchen98** [comment]
Behind Granold there is this statue thing. If you climb it you can reach those wool blocks. Somewhere next to the wool blocks there is a small tunnel that opens.
I'm sure you can find some videos on YouTube about the quest as well.

**Comment by dyredhead** [comment]
tanks

**Comment by dyredhead** [comment]
it worked
