### ISSUE TITLE
WynnExcavation Site A ( Teleport bug/glitch ) 

### ISSUE THREAD

**Issue by BlaupilzHD** [Wynncraft/Issues#6846]
Im stuck in 1x1 hole. It goes like this, after i defeat the boss i suppose to teleport to the enterence of the tomb,but it didnt i teleport to 1x1 hole. I already try switching server still no effect and i cant use scroll. So i really need admin to teleport me.

the hole located at : x : 1246 y : 48 z : -1765
![2016-12-06_13 58 08](https://cloud.githubusercontent.com/assets/24390287/20916348/e7e1df9a-bbbd-11e6-9994-9b76e8c68d29.png)

**Comment by MrRedCrack** [comment]
/kill is the best option to get out when youre stuck

**Comment by BlaupilzHD** [comment]
thx it work !
