### ISSUE TITLE
Jungle Fever Quest Bug

### ISSUE THREAD

**Issue by Healve** [Wynncraft/Issues#6847]
I had a problem with a quest, called Jungle Fever. I can't speak with the Worid, NPC of the Jungle Village so I can't complete the quest, hope you fix it, thanks.

**Comment by LordHelmchen98** [comment]
Since the gameplay update there is another 'Worid'-NPC in the Emerald stash in Detlas.

**Comment by Moe-Ronickah** [comment]
@Healve , did you talk to the "real" Worid?

**Comment by AscendedKitten** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
