### ISSUE TITLE
Aldorei's Secret II

### ISSUE THREAD

**Issue by Rellia** [Wynncraft/Issues#6849]
On the beacon spawning parkour challenge, it is literally impossible for me to make the jumps, because every single time a beacon spawns in front of me, the screen freezes for a second. Can you please make the leaves around the outside of the room a much longer but actually possible hard static parkour challenge? As an option for people who get stuck in mid air, then fall out of the sky?

This is really depressing...

**Comment by ColinRioux** [comment]
@Rellia, I would like you to note, this is probably really low on the priority list. This could be the result of your computer either not having enough memory or you having a poor internet connection. Until more people start having this "issue" and are posting that they can't "complete" the quest, then it'll be come a bug.

**Comment by Rellia** [comment]
@ColinRioux Okay thanks... I am well aware of this. I was just saying because I am a player who really loves to explore the brilliant world that has been created, and that's why I bought VIP+. I am just suggesting giving a static harder and longer parkour challenge to anything redstone intensive, just for other people who just love exploring the world like I do, but sometimes can't make the parkour, due to what I've highlighted. But thanks for replying.
I also wasn't having a good day yesterday so I wanted to enjoy some wynncraft. But oh well.
