### ISSUE TITLE
Bob's Lost Soul Depressing Items Dissapeared

### ISSUE THREAD

**Issue by BERFTHEALMIGHTY** [Wynncraft/Issues#6851]
My friend sucks with computers so i had to do this for him. We were doing the quest "Bob's lost soul" when he had gone to the blacksmith to turn in the depressed items and then the server restarted. He logged back on and talked to the Blacksmith and the blacksmith told my friend to bring him the 4 depressing items. Now, the depressing items being a pain to get you can understand why we wouldn't want to good 4 more depressing items again, especially 4 different ones. Could anyone do something about this? My friend's IGN is FERFTHEALMIGHTY

**Comment by LordHelmchen98** [comment]
Since the Gameplay Update the depressing items aren't that rare anymore. Just go to the wolf cave near Nesaak and grind there for like 5-10 minutes and you should be able to get all four items.

**Comment by Rellia** [comment]
@LordHelmchen98 where is that wolf cave? I can't find it at all...

**Comment by LordHelmchen98** [comment]
Go out of Nesaak to the south east towards the Ice Barrows Dungeon. Not too many blocks before getting to the dungeon there is like a hole in the ground. If you go in there you will find some bridges leading to the wolf cave deeper in the hole.
