### ISSUE TITLE
My Friend GunSlayer

### ISSUE THREAD

**Issue by ZayoodPlayzMC** [Wynncraft/Issues#6852]
My friend gunslayer got his classes deleted he was a assasin lvl 46 or something like that, his assasin class is a lvl 6 now please please recover his class

**Comment by ColinRioux** [comment]
Well, unfortunately, there is the possibility that you your friend is remembering his level wrong, or he deleted it somewhere along the way and restarted. This is the **first** time I've heard of this issue, which is interesting. 

Unfortunately, Wynncraft does have a strict no refund policy, even if he lost his level and/or class. This may seem unfair, but it actually maintains fairness among the player base. In fact, recovering your friend's stuff can be seen as an advantage to other players, who will then ask for Wynncraft to return their items as well. It's a long and complicated process. 

Also, I hate to be a bit realistic, but I doubt the server could recover it, or if they have a backup. In fact, now that he has logged in and he's only level 6, it probably overwrote his data file.

**Comment by Villageacules** [comment]
As the previous comment said ^ the no refund policy is active, ^ and if your friend wants issues to have attention to them, he should post them himself.
