### ISSUE TITLE
Skill Point cap?

### ISSUE THREAD

**Issue by 5pb** [Wynncraft/Issues#6853]
When I try to put on more than 64 points on one skill it takes my skill points but does not increase my skills, my friends are also having the same issue, is there a way to fix this?

**Comment by LordHelmchen98** [comment]
Thats because Minecraft cant show more than 64 item in one stack. You still get your skill points. Just hover over you skill point books for more information about how many you actually have.

**Comment by 5pb** [comment]
Thank You
