### ISSUE TITLE
Wynncraft excavation site A bug

### ISSUE THREAD

**Issue by OptimisticPeach** [Wynncraft/Issues#6854]
Hello, I have found a bug the other day and have tried to report it to a staff member. Finding one got frustratingly hard, so I came here. When the player enters the tomb before starting the quest or talking to vade for the second time, the player is unable to travel deeper than just before the centre of the room. The player is also able to enter the side room. But when the player enters the side room, and goes back out of it on the side that would lead to the half of the main room that is supposed to be inaccessible, it turns out the player can evade the barrier, and enter the other half of the main room.

**Comment by OptimisticPeach** [comment]
Anyone?

**Comment by Trixter313** [comment]
Sorry for the late reply, seeing as there isn't really much the player can do and it isn't really an area that is supposed to be hard to get into, I think this should be fine left as it is.
