### ISSUE TITLE
Can't kick guild member

### ISSUE THREAD

**Issue by Yaythegreat** [Wynncraft/Issues#6855]
I own a guild in Wynncraft and I am having a problem where I am trying to kick a member from my guild, the chat states I have kicked the person but after several attempts the person cannot be kicked, I have no inclination of a name change nor can I contact the person outside of the game (to try and get them to leave the guild them self). What should and can I do?

**Comment by LordHelmchen98** [comment]
Duplicate of #3665
I quickly checked your guild on the stats page and I guess you were trying to kick PoweradePlayz, TheRealEnderLord, SeniorAli, Lolitaro or Chara_KillerTrue. All of them changed their names after they joined your guild.
Unfortunately there is nothing you can do until guilds get fixed.

**Comment by Yaythegreat** [comment]
Ok thanks you
