### ISSUE TITLE
Multiple Issues with One Thousand Meters Under

### ISSUE THREAD

**Issue by Killerbug191** [Wynncraft/Issues#6856]
I was told to report this a while ago....

1. It's very easy to clip outside of the submarine when you are teleported back in. If this happens, there is no way back in, and you are forced to restart the quest. I suggest adding a command block which will teleport you back to the area you were previously in (or back to the quest start. Either one would work).

2. If the server restarts while you are on the part where you have to survive for a minute or two while the bridge is being built, you will be stuck. The monsters will still spawn, but the area acts as if that part of the quest wasn't started (no "npcs", no bridge, no count down), and you are unable to leave. Adding a way to restart this part would be nice.

3. Right after accepting the quest, it's possible to walk by the secretary. The cutscene will still play, but the main exit won't work, and the other one restarts the cutscene. http://prnt.sc/dh54yv

**Comment by Imaxe** [comment]
1. Fixed.
2. Nothing I can do about this :/
3. Fixed! You now need to talk to the secretary before entering
