### ISSUE TITLE
 Can not leave the area

### ISSUE THREAD

**Issue by OnoyaNiki** [Wynncraft/Issues#6857]
I can not leave this area. 
![javaw 2016-12-09 21-58-18-381](https://cloud.githubusercontent.com/assets/24478424/21053172/d1d2cd8c-be5a-11e6-9734-47fb840341bb.jpg)
![javaw 2016-12-09 21-58-33-044](https://cloud.githubusercontent.com/assets/24478424/21053176/d898f33a-be5a-11e6-9dc4-2fd14a1ee3f8.jpg)

I can not leave this area and I can not use available Teleport Scroll. Help me please. by Niki_Huhu

**Comment by ColinRioux** [comment]
`/kill` with 3 or more soul points.

**Comment by OnoyaNiki** [comment]
ok
