### ISSUE TITLE
Guild xp

### ISSUE THREAD

**Issue by BigSmileMinecraft** [Wynncraft/Issues#6858]
Hello, I'm have created a guild a long time ago (when gavel was released) and at that moment the guilds were bugged. But here we are, many months later, I still don't have xp displayed in /guild list, even if I grind for a bit with /guild xp 100 (with a lvl 91). 
![image](https://cloud.githubusercontent.com/assets/18381575/21061700/b3ef3b32-be4d-11e6-96aa-34af75702a0f.png)
The weird thing about is that my xp does get added to the total xp.
So yeah, don't know if the thing that is causing it can be fixed.
Anyways thank you for reading this.

**Comment by ColinRioux** [comment]
Anything having to do with guilds is on this super duper long list that will hopefully be fixed sometime in the near future. 

Some sort of "guild refresh" could cause your xp to refresh. This can be achieved by: someone leaving or joining the guild, or simply by taking a territory.

**Comment by BigSmileMinecraft** [comment]
Well a "guild refresh" doesn't work, I added 2 new members not to long ago to my guild, but my xp is still at 0

**Comment by ColinRioux** [comment]
Alright, well I'll file and keep the thread open until proven fixed.

**Comment by Moe-Ronickah** [comment]
DUPLICATE
