### ISSUE TITLE
Olux's Prized wand down hopper

### ISSUE THREAD

**Issue by PsychoNater** [Wynncraft/Issues#6859]
I acksodentily  threw my olux's prized wand down the hopper for the the boss totem near the idoboi village and I was wondering if its possible to get it back

**Comment by LordHelmchen98** [comment]
Wynncraft enforces a strict norefund policy. Therefore you wont get back your wand. You might be able to get a new one by someone else.

**Comment by PsychoNater** [comment]
its a untradeable item that you get when you complete the shadow of the beast

**Comment by LordHelmchen98** [comment]
Yeah you get it from Shadow of the Beast but its tradeable.

**Comment by PsychoNater** [comment]
oh well that's gonna be hard to get back

**Comment by ColinRioux** [comment]
Even if it were `Untradeable`, you still wouldn't be able to get it back. It'd be different if it were a quest item and `/fixquests` wasn't working.
