### ISSUE TITLE
Character info bugged. Can't see any of the skills.

### ISSUE THREAD

**Issue by LordViperagyil** [Wynncraft/Issues#6860]
I stopped playing around 1.8, and when i come back yesterday everything was fine but the only skill i could see as the little book was damage defence and intelligance. later i got some stuff whicj needed some levels on a different skill but it was missing. i resetted my skills but now all of them are blank. I can still click on them and they get the points but no name, icon, or numerical value on any of them. i also have a wand which has broken discreption with the code appaering instead of the normal stuff.

**Comment by thecoolkogut4** [comment]
try to log in with 1.8.8 with no mods, does the problem still occur?

**Comment by LordViperagyil** [comment]
So the problem is with the 1.11 version?

**Comment by LordHelmchen98** [comment]
Yes. Wynncraft was made for 1.8.9 and the servers are running on 1.8.9. Therefore that's the version with least bugs and glitches. The bug you found was already reported and the guy who faced it was able to fix it by playing in 1.8.x

**Comment by LordViperagyil** [comment]
it worked. how can close this?
