### ISSUE TITLE
Glitched wand.

### ISSUE THREAD

**Issue by LordViperagyil** [Wynncraft/Issues#6863]
I had a break since 1.8 and when i come back one of my wand called devarose was gliched in it discreption. its shows the coding of the discreotion instead of the actual discreption.

**Comment by LordHelmchen98** [comment]
I bet this weapon was called Dévoreuse before. Unfortunately every weapon with an é in their name got glitched like yours. Its useless and can be thrown away (im not certain if you can keep it as a souvenir but I'm pretty sure you are not allowed to sell this).

**Comment by LordViperagyil** [comment]
okay thanks. is there an other wand to that level or there is a gap of wands there?

**Comment by LordHelmchen98** [comment]
There are lots of wands you just have to grind a bit. If you don't have a weapon due to this bug, buy one from a weapon merchant in any town.
