### ISSUE TITLE
gliched block

### ISSUE THREAD

**Issue by DasOcto64** [Wynncraft/Issues#6864]
Hello... I've played on this server for a while and I got stuck in some glicked blocks and I can't get out.I tried all the methods possible but I couldn't....
Can enyone find a solution perhaps trade me a scroll if it is possible?
-Robert

**Comment by ColinRioux** [comment]
`/kill` with 3 or more soul points.

**Comment by teuntheman** [comment]
if you're a mage you can many teleport out of it.

**Comment by DasOcto64** [comment]
I already tried all the things... i tried to teleport but i am gliched near
the abandoned mines of lvl 25 and it sais that i have to move away from
blocks in order to teleport...but i am blocked in a block -_-

Pe 10 dec. 2016 18:02, "teuntheman" <notifications@github.com> a scris:

**Comment by DasOcto64** [comment]
I didn.t tried to /kill me yet... it may work

Pe 10 dec. 2016 18:57, "StarFox" <robbybaciu@gmail.com> a scris:

**Comment by DasOcto64** [comment]
I will respond to this msg saying if it did/didn.t work

Pe 10 dec. 2016 18:57, a scris:
