### ISSUE TITLE
Right-Click Issue 

### ISSUE THREAD

**Issue by turtle0821** [Wynncraft/Issues#6865]
Ever since I completed all quests up to lvl 26, I can't seem to right click. It's not laggy, and I right click on other servers. I can parkour just fine in the lobby, but can't right click. It's driving me insane because I can't use any spells and I'm a mage so I'm useless. Pls help

**Comment by LordHelmchen98** [comment]
So it doesn't detect your right click or does something show up in your chat?

**Comment by ColinRioux** [comment]
I've encountered something similar before. What I have done as a solution is press `esc` and then click `Back to Game`. Sometimes the calibration gets funky.

**Comment by turtle0821** [comment]
thanks ColinRioux, it worked
