### ISSUE TITLE
Wynncarft excavatian site a bug

### ISSUE THREAD

**Issue by teuntheman** [Wynncraft/Issues#6866]
When i came out of the tomb and i talked to that guy he sad exactly the same thing about the tablet. like have you been to the lab to translate it but when i went there the guy in the lab sad i needed to bring it back but i didn't have anything so then i knew it was glitching. Can anyone help me with this?

**Comment by Villageacules** [comment]
Look at a quest video and see if you're doing anything wrong, you probably aren't.

**Comment by teuntheman** [comment]
I already did but i did nothingbwrong

**Comment by Moe-Ronickah** [comment]
DUPLICATE #6341 .  HINT: Kill the pharaoh, pick up his crystal, go talk to Vade.
