### ISSUE TITLE
How to change ur MC username on forums

### ISSUE THREAD

**Issue by IEatChickenWingz** [Wynncraft/Issues#6868]
so on the forums it stills says ChickenWing_ and my new ign is alovablechicken how to change?

**Comment by LordHelmchen98** [comment]
I You can't change it yourself but it should update after some time so you may have to wait.

**Comment by Villageacules** [comment]
Try /forums or /forum, I forget the command to connect with your new IGN in-game.

**Comment by Moe-Ronickah** [comment]
Is this resolved?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
