### ISSUE TITLE
connection Bug

### ISSUE THREAD

**Issue by KAM078** [Wynncraft/Issues#6869]
I haveing problems trying to enter wynncraft. The server keep saying I am flying but I 'am not. this is happening when ever I enter the game it keeps 'flying is not able' and it also keep trying to load terrain but it do it all over again I am not doing anything. 
Also try to reset sever by deleting it and re entering it 
IT ONLY EFFECTING WYNNCRAFT NOT ORTHER 2 SEVER

**Comment by OptimisticPeach** [comment]
This is caused by the server's flying detection. As on many servers, it every once in a while bugs out. I cannot help you, but a staff member can.

**Comment by LordHelmchen98** [comment]
Sometimes this happens to me as well, mostly if the network is very full. Try to enter very empty servers in order to get on a server. Also for me it often helps if I quit Wynn and join again so the server pack isn't loaded yet.

**Comment by ColinRioux** [comment]
It may also be wise to use 1.8.9 for the time being, see if that does anything. I don't suppose it would, but playing on the native version could fix somethings on the server side.

**Comment by Villageacules** [comment]
@KAM078 Is this still happening?

**Comment by LostMySample** [comment]
This happens to me too :I I don't know how to fix it :_:

**Comment by Moe-Ronickah** [comment]
Duplicate of #5289 .  Read the advice given there.
