### ISSUE TITLE
Changed class while on fire and lost armor

### ISSUE THREAD

**Issue by TheOGPickle** [Wynncraft/Issues#6870]
So, chances are this issue has been pointed out numerous times, but after switching from my archer (I'd also like to point how that I was on fire before I made the switch) to my warrior to get a few things done and later relogging as an archer again, I had noticed that all my armor had disappeared, amounting to about 100le worth of armor gone. . So, I have no idea if this is tied to the skill point glitch that happened a while back, but there was no notification of any skill point requirements. It'd be appreciated if you looked into this.

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by Moe-Ronickah** [comment]
"(I'd also like to point how that I was on fire before I made the switch)"  I'm sorry, but that shouldn't be in parentheses.  It's never advisable to do that in Wynncraft because of the complexity of the game, on top of MC.
