### ISSUE TITLE
Items tranformed into depressing 1

### ISSUE THREAD

**Issue by toma99** [Wynncraft/Issues#6871]
I had a 22% xp bonus dagger called influence I put it in my bank before doing a quest when i was done i came to use it to grind and it became a lv 1 depressing dagger. pls help

**Comment by ColinRioux** [comment]
Unfortunately Wynncraft enforces a **strict no refund policy**. What that means is that you won't be getting your item back. Although it may sound unfair, it actually maintains fairness across the player base. We're sorry.

**Comment by Villageacules** [comment]
Closed, no refund policy is and will always be active.
