### ISSUE TITLE
Glitches relic boots

### ISSUE THREAD

**Issue by Cameronsmsms** [Wynncraft/Issues#6872]
I right clicked the relic boots with a full inventory so It didn't give me the boots my username is MemezYT how can I fix this?

**Comment by teuntheman** [comment]
try /fixquests

**Comment by LordHelmchen98** [comment]
/fixquests won't work as they are only untradeable and not a quest item. However you can get relic items more than once. There is a cool down but after a few hours you can get the items again. Therefore you just have to go there again with some empty slots in your inventory and get the boots once more.
