### ISSUE TITLE
Tower of Ascension Floor 1 Bug

### ISSUE THREAD

**Issue by ULSTICK** [Wynncraft/Issues#6873]
I was playing in Tower of ascension. when i reached level 8 or 9. i accidently teleported into a wall, i dont know what to do now.

here's a screenshot of it

![2016-12-11_17 33 56](https://cloud.githubusercontent.com/assets/23027094/21079566/12a5ffaa-bfc8-11e6-9657-9667d88b53e8.png)
![2016-12-11_17 27 36](https://cloud.githubusercontent.com/assets/23027094/21079567/12a797de-bfc8-11e6-8c68-4b605561df1f.png)

i know i can use scroll, or suicide to get out. i just wanna let u guys know)

**Comment by LordHelmchen98** [comment]
Do /kill to get out.
@Imaxe can you fill that up please?

**Comment by Imaxe** [comment]
I will! Thanks for reporting this issue.
Thanks @LordHelmchen98 for tagging me
