### ISSUE TITLE
inventory/class glitching

### ISSUE THREAD

**Issue by YoruKage** [Wynncraft/Issues#6875]
I was just switching classes and moving some quest items and then suddenly when i try to og to my mage, he is holding a bow With only a leather helmet on and is in ragni. i think the inventory from my hunter got copied over to my mage and his items deleted.

**Comment by thecoolkogut4** [comment]
this has happend before, I remember the admins were trying to recreate the bug. 
unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by Moe-Ronickah** [comment]
I can't find the original of this issue, Yoru.  I know that it is here, somewhere.  It seems that every now and then, when someone switches between classes, a lot, something goes horribly wrong.  The only advice that we have is that you play the class for a few minutes, walk around, whatever, between every 4 or 5 class switches.

NightMage, if there is something that I can help with, let me know what you need.

**Comment by DebugingLonks** [comment]
...i feel like trying this from my good class to my bad one, but im not going to. and + what if it went backwards ;3

**Comment by DebugMC** [comment]
Here Moe.

#4790

**Comment by Moe-Ronickah** [comment]
Thanks, Debug!

Your issue is a duplicate, as listed, above.  You can follow your issue on that thread.

AND don't fast-switch classes.
