### ISSUE TITLE
The House of Twain bug

### ISSUE THREAD

**Issue by SoulAndreas** [Wynncraft/Issues#6876]
When i tried the house of twain the other day with a friend we fought the last boss but it didnt drop the journal so we were then unable to finish the quest.

**Comment by ColinRioux** [comment]
How many times did you attempt to kill the boss?

**Comment by Moe-Ronickah** [comment]
@SoulAndreas , whenever something like this happens, always switch servers, then try again.

**Comment by SoulAndreas** [comment]
ok ty
