### ISSUE TITLE
Seaskipper Fast Travel Issue

### ISSUE THREAD

**Issue by CerberucVic** [Wynncraft/Issues#6877]
I was at the Pirate Cove. I bought a Selchar Boat Pass and I threw it in the hopper. I was teleported to the boat and waited until I was teleported to Selchar. But there's the problem... I waited a minute or so, but I was still on the Seaskipper's boat. I didn't want to be there forever 'cause I wanted to go to the Mage Island. What did I do? I typed /kill, so I would appear in anywhere else (that would be better than be on the boat forever). And for my surprise, I spawned at Ragni's Lookout (Fruma?)!! Yep... It was like starting the game again, but with all my lvl. 60 gear... I did everything I needed to get back to Wynn by Ragni. And it worked! I was back to Wynn. Seriously, nothing on my inventory was affected, and I can play as always with this character but this is still an issue. Oh, and of course I used 14 emeralds for the boat pass and it was for nothing, because I couldn't go to Selchar this time. You can see the screenshot I took when I was back in Ragni's Lookout. And I needed to buy that Plain Leather Cap in order to get back to Wynn.
![2016-12-11_14 29 15](https://cloud.githubusercontent.com/assets/22283069/21081774/a43b83fe-bfb4-11e6-9f23-0a43e5df9b7f.png)

**Comment by LordHelmchen98** [comment]
That happens due to the respawn system. When you die you get teleported to the closest 'town'. If you start a class and die you get teleported to that guy at the caravan. The Seaskipper is offmap and apparently close to the starting area of Wynncraft so if you do /kill the caravan is the closest respawn point and that's why you got there.

**Comment by Moe-Ronickah** [comment]
LordHelmchen98 is absolutely correct, and the Content Team is aware of this issue.  And working on it.
