### ISSUE TITLE
Lost Sanctuary Bug

### ISSUE THREAD

**Issue by cookiebearz** [Wynncraft/Issues#6879]
The trip wire from a running area has disappeared meaning the invisible blocks are in the way and you can't get past. This leads to the dungeon not being able to be completed. Any help?

**Comment by LordHelmchen98** [comment]
You should try to change the server.

**Comment by Moe-Ronickah** [comment]
RESOLVED

**Comment by Soma5356** [comment]
I am also having this issue. The barrier is up and I cannot cross the bridge.
