### ISSUE TITLE
Little visual glitch...

### ISSUE THREAD

**Issue by Ezohn** [Wynncraft/Issues#6881]
![screen shot 2016-12-11 at 5 56 48 pm](https://cloud.githubusercontent.com/assets/22990347/21084097/e7776874-bfcb-11e6-8ee2-715462060b7c.png)
 
This is a legendary level 33 spear called chaleur. It's kind of weird. I think this bug is fixed by relogging, but sometimes the server you're on fills up so you can't really come back if you wanted to. This is bad if it has dxp, or a grind party.

**Comment by ColinRioux** [comment]
Are you playing on 1.8.9?

**Comment by LordHelmchen98** [comment]
Yeah most likely he is plating in 1.8.9 otherwise he would probably see one of the item skins.
I thought that glitch was fixed. Apparently it's not but I don't think there's another way to fix it but to change the server.

**Comment by Moe-Ronickah** [comment]
The 1.8.9 resource pack does not have the space necessary in order to properly display many items.  Try using a 1.9+ MC version, and it will be visible.
