### ISSUE TITLE
Kicked for Flying in Cutscene bug

### ISSUE THREAD

**Issue by ULSTICK** [Wynncraft/Issues#6884]
I got kicked for flying in a cutscene in the Grave Mitsake quest. and it wont continue the cutscene when im back. then i /kill myself to get out from the (bugged) cutscene.

![2016-12-12_14 37 51](https://cloud.githubusercontent.com/assets/23027094/21091577/b2a5eb44-c079-11e6-8c17-e097e1ac40c6.png)

and sometimes i get kicked for Flying over and over when in lobby. until i disconnect and join again
Please FIX this!!

**Comment by ULSTICK** [comment]
Now im Stuck in the middle of a cutscene again
![2016-12-12_15 02 09](https://cloud.githubusercontent.com/assets/23027094/21091950/05756848-c07c-11e6-8244-c3b6fc3f8556.png)

**Comment by LordHelmchen98** [comment]
I don't know of any possibility for you to get teleported other than switching servers or jumping around and hope you activate something that teleportation you. However it's your connection to the Wynncraft servers that causes you to be kicked for flying and I hardly believe there is anything that Wynncraft can do to make this better.

**Comment by ULSTICK** [comment]
why my connection is bad though. i have no problem with any other servers, only wynncraft is laggy

**Comment by Moe-Ronickah** [comment]
Because Wynncraft is very complex.  Much more complex than mini-game servers.  You can also try changing versions, because sometimes, and no one is certain as to why, one version of MC may fail where another version works.
