### ISSUE TITLE
My chestnut turned into a new brown horse and its untradable now too

### ISSUE THREAD

**Issue by Amoraa** [Wynncraft/Issues#6885]
i was breeding some horses with my friends, and when i was going back to detlas (in my old chestnut that was 13/35) to store the spare horses, i put the mouse over it, and it turned into a untradable BROWN horse ._. and i think theres impossible to have a untradable brown 1/10 as a proof. And no, i didnt bred the 2nd slot of my inv (where my horse was) and even if i did, what could happen, is it turning into a t2, i think

any help? or am i just screwed?
![image](https://cloud.githubusercontent.com/assets/16783145/21104063/4694c9aa-c06c-11e6-9754-6729a120bd72.png)

**Comment by ColinRioux** [comment]
Interesting, haven't seen this one before. 

But, unfortunately, Wynncraft enforces a strict no-refund policy. This means you won't be getting your items back. Although this may seem unfair, it actually maintains fairness among the player base. Will keep open until resolved.

**Comment by Villageacules** [comment]
Haven't seen this before... interesting topic, must be a one-time thing... is it actually untradable? Did you try trading it with another player? The meta might be there but it might still be tradable.

**Comment by Moe-Ronickah** [comment]
@Amoraa , is this horse still bugged, or was it a temporary glitch?
