### ISSUE TITLE
I can't get my prize for the Out Of My Minds quest

### ISSUE THREAD

**Issue by SavageBuns** [Wynncraft/Issues#6888]
![2016-12-12_15 48 35](https://cloud.githubusercontent.com/assets/24532237/21116438/93e62b92-c083-11e6-8767-a92386594bd3.png)
I finished the quest

**Comment by SavageBuns** [comment]
OML  I have very bad eyes

**Comment by LordHelmchen98** [comment]
So its resolved now?

**Comment by SavageBuns** [comment]
yes
