### ISSUE TITLE
Glitch maybe?

### ISSUE THREAD

**Issue by NEXUSPOWER15** [Wynncraft/Issues#6889]
My Stuff In My Inv and bank was empty when i logged in

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by Moe-Ronickah** [comment]
@NEXUSPOWER15 , what, exactly, is your in game name, please?

**Comment by Moe-Ronickah** [comment]
Never mind.  You clicked on a link for a free cape or a free rank, either in Wynncraft, or in another server.  Your account was compromised - stolen - by a phisher.  You must change your Minecraft password to something other than what it is.  You can go onto our forums and learn more about phishing scams.  We suggest that you use two or three words as your password, but do not use a common phrase.
