### ISSUE TITLE
Disappearing scrolls?

### ISSUE THREAD

**Issue by dyredhead** [Wynncraft/Issues#6890]

**Comment by dyredhead** [comment]
when I use a teleport scroll it doesn't update that I use it. so I have to drag it into my inventory to update it each time. it gets really confusing when I forget to update it and log off. when I log back on it looks like a scroll disappeared from my inventory

**Comment by dyredhead** [comment]
its not a big issue but it will just make the game smoother.(if this glitch is only happening to me pls tell me)

**Comment by thecoolkogut4** [comment]
it takes a minute or two for the scrolls to update sometimes.
