### ISSUE TITLE
Quest: Potion Making

### ISSUE THREAD

**Issue by SaltyShron** [Wynncraft/Issues#6893]
http://prntscr.com/diziuz
http://prntscr.com/dizip2

After delivering 8 Red Mushroom to the Quest NPC , you need to kill a boss and bring an item back to the Quest NPC. The Boss is not there for me, but it already says in the quest book that I killed him and need to deliver him the item.
When I click on the Quest NPC it still says he needs these 8 Red Mushrooms.

**Comment by LordHelmchen98** [comment]
I think most of the time it works, if you change the server.

**Comment by JackyKit123** [comment]
This bugged is acknowledge by an admin, they have slighty changed it, try switching servers especially for those which are just restarted, let us know if the problem continues

**Comment by Moe-Ronickah** [comment]
I'm going to take it that this was fixed, as the OP hasn't responded.
