### ISSUE TITLE
My character is gone.

### ISSUE THREAD

**Issue by DMCHestia** [Wynncraft/Issues#6894]
help... I have not deleted it.

The character that was raised so hard was deleted.
The level was not so high 37/Assassin. 
The quest progressed to 26%.

omg.. Why did this happen to me ...?

Do you have korea admin?
열심히 키운 캐릭터가 삭제되었습니다.
레벨은 그리 높지않은 37정도였지만 . 친구와 같이 즐겨하고. 던전을 돌아 맞춘 던전 아이템들도
다사라지고.. 퀘스트진행도 26%쯤 됬었는데..

**Comment by LordHelmchen98** [comment]
Unfortunately Wynncraft enforces a strict norefund policy and therefore you wont get your class back. However Im not sure if they could restore it anyway.

**Comment by yoitsabraham** [comment]
same ive been playing for a week non stop my character i grinded so  hard to get to level 37/mage had good gear good weapons and had completed 35 quests i log in today and its gone im really upset all my time was wasted in nothing
