### ISSUE TITLE
Taproot glitched

### ISSUE THREAD

**Issue by SavageBuns** [Wynncraft/Issues#6895]
it says i have to speak to Tiek but i doesn't work
![2016-12-13_16 12 51](https://cloud.githubusercontent.com/assets/24532237/21159478/5e69caa6-c14f-11e6-8cdc-b3cf6db9445e.png)

**Comment by LordHelmchen98** [comment]
At what stage of the quest are you? Did you just get out of the cave?

**Comment by JackyKit123** [comment]
try redoing the quest following the stages written on Wynncraft Wiki
if the issue remains, provide a detailed explanation.

**Comment by SavageBuns** [comment]
LordHelmchen98, i just left the taproot thing

**Comment by Moe-Ronickah** [comment]
You're where? [https://wiki.wynncraft.com/index.php?title=Taproot_(Quest)](https://wiki.wynncraft.com/index.php?title=Taproot_(Quest))

**Comment by AscendedKitten** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
