### ISSUE TITLE
Fighting species glitch

### ISSUE THREAD

**Issue by deamogon** [Wynncraft/Issues#6896]
while i was doing the quest A Fighting Species i decided to see what would happen if i took off my orc mask. Following that it teleported me to the bottom of the base in a stuck hole. I had 11 sp so i did /kill
that teleported me to the ragni out skirts.  I have video as a level 78 exploring the area/trying to take over ragni out skirts/ trying to get to fruma cause i like lore
 unfortunately the video is a big file and if you are interested in the video please contact me wynncraft forums as Deamos

-Deamogon/Deamos

**Comment by LordHelmchen98** [comment]
You are not supposed to put off your helmet, therefore it should teleport you out of the area where you need it. Apparently something went wrong and you got stuck.
The reason why you got teleported to the out skirts is the current respawn system. When you die you get teleported to the closest 'town' and in the out skirts there is one of the respawn points. Many quest areas are offmap and a lot of them are on the east side of the map. Therefore the out skirts are the closest area to the quest areas and if you die you get there.
