### ISSUE TITLE
Typo in Wrath of the Mummy quest book

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#6897]
![2016-12-14_15 40 10](https://cloud.githubusercontent.com/assets/5206120/21169930/d5f2d070-c214-11e6-83fc-030aa32e420b.png)

I think it should be "you", not "your", in the screenshot above. Thanks!

**Comment by thecoolkogut4** [comment]
@Villageacules

**Comment by Villageacules** [comment]
Oh, Salted's 2013 grammar mistakes. Fixed.
