### ISSUE TITLE
Ragni bank: One of the signs says "you" instead of "your"

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#6898]
![2016-12-14_16 20 31](https://cloud.githubusercontent.com/assets/5206120/21170438/47b91ba2-c219-11e6-964c-fd2a46d71ea6.png)

See screenshot.

**Comment by thecoolkogut4** [comment]
@Villageacules

**Comment by Villageacules** [comment]
Will fix when I get home in an hour or two.

**Comment by Villageacules** [comment]
Fixed

**Comment by Numbermaniac** [comment]
@Villageacules I had a look, it's still like that?

**Comment by Villageacules** [comment]
The map only updates during updates, the map hasn't been changed yet. @Numbermaniac
