### ISSUE TITLE
Stuck in the wynn excavation site a quest

### ISSUE THREAD

**Issue by PlantPoop** [Wynncraft/Issues#6899]
I am stuck i fell down the diamond block and now i am stuck down here i know the code for the diary riddle is 6384 i enter it but everytime i click the button it says you do not have permission i am stuck down here and i dont have a teleport scroll to get out

**Comment by LordHelmchen98** [comment]
I assume you clicked on the button with your weapon. Most likely you weapon is a retextured half slab. Item which are retextured half slabs are known to produce issues like yours. The game thinks you want to place that slab and obviously you aren't allowed to place it therefore you get a permission message. To activate the button click it with any item that is not a retextured half slab (for example your bare hands or your soul points). If that's bot the reason for your issue do /kill and look if you missed any quest book update.

**Comment by Moe-Ronickah** [comment]
Closing.  No second comment, so it's been resolved.
