### ISSUE TITLE
Stuck in corrupted infested pit dungeon

### ISSUE THREAD

**Issue by Daridon248** [Wynncraft/Issues#6901]
basicallly when ended the corrupted hanged man animation and becomed a mob,when i killed it with archer bombs,the barriers doesn't dissapear,leaving me stucked there without any manner to advance
[Here are some screenshots](http://imgur.com/a/oN5v3)

**Comment by Daridon248** [comment]
I looked something,if you stay some blocks back before the animation dissapears pass this,and when switch servers it can be started again,but is so annoying to stay stuck for this

**Comment by thecoolkogut4** [comment]
as you said you could switch servers and if that does not work you can /kill if you have more then 5 soul points.

**Comment by Villageacules** [comment]
Do /kill.
