### ISSUE TITLE
Skillpoints MISSING

### ISSUE THREAD

**Issue by pipdort** [Wynncraft/Issues#6902]
![img_14122016_154140](https://cloud.githubusercontent.com/assets/24575271/21200376/3fb3d31c-c204-11e6-8ab2-a8b25050a59b.png)
The skills are missing. Both my girlfriend and I are missing our skillpoints.

**Comment by LordHelmchen98** [comment]
Sometimes this happens in 1.11. I heard it comes back if you click it, but I recommend using 1.8 or 1.9.
1.8 because Wynncraft was made for 1.8.9 and is running on that version. 1.9 because I dont have any bugs in 1.9 except horse bugs, but Im pretty sure those horse bugs are in 1.11 as well.

**Comment by Moe-Ronickah** [comment]
It's a visual glitch, only, and LordHelmchen98 nailed the reason why and how to fix it.
