### ISSUE TITLE
I keep getting kicked from the main lobby even though Im not flying at all.

### ISSUE THREAD

**Issue by LostMySample** [Wynncraft/Issues#6904]
So, for the last couple of days I have tried to log on, I get to the hub and It says "Flying is not enabled on this server" and it tries to relog me and it does this again and again. Sometimes it only does it like 4 or 6 times but today it did it more than 8 times!
 
Please reply ASAP

**Comment by thecoolkogut4** [comment]
try to join the server on mc version 1.8.8

**Comment by LordHelmchen98** [comment]
I had some problems as well. Most of the time it loads faster if you try to join less crowded servers and then you don't get kicked for flying. Just choose servers with less than 30 people, better lease than 20.

**Comment by LostMySample** [comment]
AIght, so it doesn't happen when I log on to a wynncraft server. It happens when I log in to the actual server, it does this multiple times

**Comment by ColinRioux** [comment]
I've noticed this to be the case for me when running 1.9.2 or higher (up to 1.11). And I've gotten it on not just wynncraft. If you haven't done so already, I suggest playing on 1.8.8 or 1.8.9.

**Comment by Villageacules** [comment]
This is client-sided, all I can recommend is get rid of any mods you're using or switch to a different Minecraft version.

**Comment by Moe-Ronickah** [comment]
#5289
