### ISSUE TITLE
resorce pack

### ISSUE THREAD

**Issue by xSuguha** [Wynncraft/Issues#6907]
ok so i have followed your steps on how to get the resource pack but for some reason it won't download, so could you please look into this and help me get this fixed

**Comment by thecoolkogut4** [comment]
https://github.com/Wynncraft/Issues/raw/master/legacy what happens when you click this link? it should download it.

**Comment by xSuguha** [comment]
it does not work i put it in my resource pack  folder but it does not work

**Comment by thecoolkogut4** [comment]
once its in your resource pack folder, press esc -) resource packs -) legacy. do that to load the back

**Comment by ColinRioux** [comment]
If you are on mac, follow the mac guide here: https://github.com/Wynncraft/Issues/blob/master/RP%20DOWNLOAD%20INSTRUCTIONS.md

**Comment by AscendedKitten** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
