### ISSUE TITLE
Enchanted flower

### ISSUE THREAD

**Issue by Rellia** [Wynncraft/Issues#6908]
My level 13 mage one time when I logged on had an enchanted flower on it. Until today. I have been completely stumped for what the flower is for in wynn, considering this character is too low to survive gavel. However, Now I have an 83 Archer and started into the belly of the beast, and acquired one. I have no idea how my mage got one, because it's a quest item, and is just taking up inventory space now... you can check my account, I only have one character at a high enough level, and not enough time spent in Wynncraft to have had another one and deleted it. It just spawned in the inventory for no reason... how can I get rid of this quest item? I have two now, but one will never go..
(DMEW_Rell)

**Comment by thecoolkogut4** [comment]
put it in your daily chedy to get rid of it

**Comment by Villageacules** [comment]
Do not get rid of quest items, they are not meant to get rid of. There is intended to eventually be a quest item bank.
