### ISSUE TITLE
Sand-Swept Dungeon No Reward Glitch

### ISSUE THREAD

**Issue by KingNBubby** [Wynncraft/Issues#6913]
Hello! I just killed the boss in the sand swept dungeon and I'm still stuck on the top floor. Can you help? Thanks! 
![2016-12-17_07 17 49](https://cloud.githubusercontent.com/assets/24623820/21287871/e9f6957c-c429-11e6-8af4-588a6fc37d44.png)

**Comment by ColinRioux** [comment]
You can `/class` and see if it respawns boss. If by chance you keep on killing the boss but are still stuck, please re-comment. If you want to leave the dungeon, you can `/kill` with 5 or more soul points.

**Comment by KingNBubby** [comment]
Ok, thank you!
