### ISSUE TITLE
Fantastic Voyage Odd Stew Glitch

### ISSUE THREAD

**Issue by Stena1392** [Wynncraft/Issues#6916]
I was doing Fantastic Voyage happy as can be, until this weird glitch. I made the odd stew for Relend and he seems to think I don't have it, even though I do. I refreshed my game and restarted my computer, I asked a few of my friends for help, they he'd no clue. I been made 1 of them do it with me. Does anyone have any idea on how to help me? Msg me if you do on wynncraft @ Stena1392. Thanks!

**Comment by Trixter313** [comment]
Have you also tried looking up a tutorial to follow? There might be a detail you're missing, here is the Wiki link for the quest. Follow that and see if it helps at all. Thanks!\

https://wiki.wynncraft.com/index.php?title=Fantastic_Voyage

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
