### ISSUE TITLE
Class deleted/Tier 3 horse lost

### ISSUE THREAD

**Issue by Jorno10** [Wynncraft/Issues#6917]
Please help me. I deleted my lvl 32 Mage class to make room for a warrior one to play with a friend, i played for a couple of minutes on my warrior i went to get my horse on my assassin lvl 12 class but it was gone with my tier 3 horse still in it.

**Comment by LordHelmchen98** [comment]
So your mage and assassin we're both entirely deleted? Or is your mage still there and your assassin is gone?
However, if both or only your assassin got deleted, wynncraft enforces a strict norefund policy anyway so you won't get your class/items back, but it could be helpful for staff members to know a bit more about your issue so they can maybe fix this.

**Comment by Villageacules** [comment]
No refunds/rollbacks, sorry.
