### ISSUE TITLE
Potion Making BROKEN!

### ISSUE THREAD

**Issue by DerpyTaxes** [Wynncraft/Issues#6918]
I am in the middle of the potion making quest and when i go up to Seb it said to get [8 Red Mushrooms] so i did i got the 8 and went back to him but then i tried to give it to him and it repeats to say to get him [8 Red Mushrooms]

I cannot complete the quest therefor I will never have 100% in my quests and not be able to get the reward for it.

**Comment by ColinRioux** [comment]
Duplicate of #6437

There is no reward for 100% quest completion.
