### ISSUE TITLE
I put a Steam Punk Bow skin on my bow.

### ISSUE THREAD

**Issue by Jacob32587** [Wynncraft/Issues#6919]
I added a Steam Punk bow skin on my bow and it looks like this.

![2016-12-18_11 31 13](https://cloud.githubusercontent.com/assets/24637448/21294903/a5d9b872-c516-11e6-9bdb-e652600fafe3.png)

**Comment by Jacob32587** [comment]
I scrapped my Cow Disguise, Sheep, Pig, Magic effect, Fire Effect to get it. :(

**Comment by LordHelmchen98** [comment]
That's because you are using 1.8. Unfortunately those item skins are not compatible with 1.8. You have to use 1.9 to see them.
