### ISSUE TITLE
Im stuck in mid air

### ISSUE THREAD

**Issue by victorysummery** [Wynncraft/Issues#6923]
hi, I was doing a lv 83quest and finding the mage. I used escape spell to jump to mid air after climbing a mountain, then when im dropping, i keep getting tp back up into mid air when im dropping and a ??? says something like "you are too weak i can blow you away with my spell sth". So now I'm basically stuck in mid air
-ign: victory_summery

**Comment by victorysummery** [comment]
nvm i just relog and im in the starting tut area some how

**Comment by Rellia** [comment]
yes I'm getting the exact same problem. check out my report just before this one

**Comment by thecoolkogut4** [comment]
try to walk up the mountain and walk up the stairs. "I used the escape spell" which probably means you skipped a trip wire and got stuck.

**Comment by Villageacules** [comment]
Please try /kill next time this happens.
