### ISSUE TITLE
2897XP From 3292XP Mission

### ISSUE THREAD

**Issue by SlimeOre123** [Wynncraft/Issues#6924]
http://prntscr.com/dlbq71 :P

**Comment by Rellia** [comment]
yes it happens... it depends on your equipment and how quickly you accomplish the mission

**Comment by Villageacules** [comment]
Widely known issue, missions are to be reworked in the future.

**Comment by Villageacules** [comment]
Also, please be weary in naming your issue and don't use slang. This is a formal site.

**Comment by SlimeOre123** [comment]
ok

**Comment by DebugingLonks** [comment]
Occasionally you get less xp ( ͡° ͜ʖ ͡°)
