### ISSUE TITLE
Deleting charcters/classes

### ISSUE THREAD

**Issue by rofllmaohaha** [Wynncraft/Issues#6925]
For some odd reason i can't delete characters/classes
When i right click a class to delete it and confirm nothing happens (playing on 1.8 but tried on 1.9.2 and still didn't work)

**Comment by LordHelmchen98** [comment]
It takes some time to delete it. You can use the class slot as soon as the time is over.

**Comment by Moe-Ronickah** [comment]
@rofllmaohaha , can you still not delete a class or character?

**Comment by AscendedKitten** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
