### ISSUE TITLE
Glitch compass in my bank chest

### ISSUE THREAD

**Issue by Stickzz** [Wynncraft/Issues#6926]
Hello , first , sorry for my english because i'm not english ^^

So , I have a compass in my bank chest who is an old compass of an old update , and i can't remove it.

Can you please remove it or give me instructions for removed the compass ? (I know others peoples have the same bug) 

Thank you !

**Comment by Trixter313** [comment]
This was a long standing issue before and was fixed for most people, so I think we can help you. There isn't much you can do to fix it, a staff member with the proper privileges will have to intervene. Please comment back what your Minecraft username is so someone can help. Thank you!

**Comment by Stickzz** [comment]
Thank you for you answer ! :)

My username is : Papy_Thagore , and the compass is on the top of my chest ^^

Thank you !

**Comment by Moe-Ronickah** [comment]
The compass has been removed.  You're welcome, in advance.  :)
