### ISSUE TITLE
The mini dungeon containing vengeful sirens has an obsidian gateway at the end which isn't a teleporter?

### ISSUE THREAD

**Issue by Rellia** [Wynncraft/Issues#6930]
The mini dungeon containing vengeful sirens has an obsidian gateway at the end which isn't a teleporter? I fought my way through several layers of high level enemies for nothing? Is it a joke?
![mini dungeon end](https://cloud.githubusercontent.com/assets/23388884/21330012/6e8dad60-c633-11e6-9895-58e206df9906.png)

**Comment by LordHelmchen98** [comment]
I'm pretty sure all the mini dungeons in Gavel are broken, so is this one. Maybe they will be reworked/fixed with the next major update but for now you should stay outside of them.

**Comment by Rellia** [comment]
ah okay. Thank you @LordHelmchen98
