### ISSUE TITLE
Wrong Warp Discovered! (WynnChristmas Event)

### ISSUE THREAD

**Issue by Charizard841a** [Wynncraft/Issues#6931]
Hello! While I was trying out the Obstacle course on the new Wynncraft Christmas event, I noticed I was receiving a lot of Crash messages, I relogged only myself spawning above lusoco, above the mountains where the Barriers allow players to not reach, I don't know why or how, but I am currently stuck there. 
I will /kill to teleport out but here are pictures of it.
![2016-12-19_15 46 44](https://cloud.githubusercontent.com/assets/24661665/21333348/02fe97be-c604-11e6-84cf-3d8654593c48.png)
![2016-12-19_15 46 51](https://cloud.githubusercontent.com/assets/24661665/21333349/02ff230a-c604-11e6-85af-bd0b27d6e001.png)
![2016-12-19_15 49 10](https://cloud.githubusercontent.com/assets/24661665/21333352/0306e180-c604-11e6-95f8-64fd2f9cdae1.png)
![2016-12-19_15 49 33](https://cloud.githubusercontent.com/assets/24661665/21333350/03039818-c604-11e6-84b0-563fe592fa29.png)
![2016-12-19_15 49 34](https://cloud.githubusercontent.com/assets/24661665/21333351/03047792-c604-11e6-998a-c01b47687e5f.png)
![2016-12-19_15 52 47](https://cloud.githubusercontent.com/assets/24661665/21333347/02fcfc56-c604-11e6-8eb3-dc99cfc898fe.png)

**Comment by Villageacules** [comment]
Command blocks are being fixed, thank you.

**Comment by AscendedKitten** [comment]
It's been 30 days without a response to this issue, or any further reports. If the problem persists, feel free to open a new issue.
