### ISSUE TITLE
Meaningful Holiday Quest

### ISSUE THREAD

**Issue by RogueHatter** [Wynncraft/Issues#6932]
Hello, My name is the RogueHatter. I am an amateur editor on the wiki and am new to the Wynncraft community. I started the Meaningful Holiday quest, also hoping to be the first to create the quest page when I discovered a bug. I got to the part where you go through the tunnel to talk to Reshad. I went to right-click on him when no text appeared. Because of this, I cannot continue the quest. My friend, CookedPelvis has also received the same problem of the NPC being broken just like me. I see 3 people just standing next to Reshad waiting for him to be fixed so they can continue the quest. If you could fix this it would be greatly appreciated. Thank you for your time in reading this bug report.

-RogueHatter

**Comment by ColinRioux** [comment]
I'll pass the message on to one of the CT. 

Also you beat me to the page creation :p 

@Villageacules

**Comment by Villageacules** [comment]
Can you tell us exactly what your quest book says? You may have missed a region or an NPC.

**Comment by Tisawesomeness** [comment]
I am also getting this glitch.
![2016-12-19_21 20 00](https://cloud.githubusercontent.com/assets/17386338/21336060/f1fcced6-c630-11e6-849f-f1b1b9518e71.png)

**Comment by RogueHatter** [comment]
My quest book says the same thing as Tisawesomeness.

-RogueHatter

**Comment by ColinRioux** [comment]
Basically the player is unable to converse with the NPC by right clicking. There is no dialogue.

**Comment by Tisawesomeness** [comment]
@Villageacules The NPC itself doesn't seem to work.

**Comment by CookedPelvis** [comment]
I had the same problem previously, and it was fixed. But now, there is another issue. When I click on Reshad, it delivers the dialogue:

[1/1] Reshad: Welcome to my farm! I'm currently preparing a large harvest for a big feast happening in Detlas soon.

This seems to be pre-quest or too low stage dialogue, and my quest book did not update after talking to him. My quest book is the same as @Tisawesomeness

**Comment by Trixter313** [comment]
@CookedPelvis I was stuck on that part but then noticed there was a circle of blue particles to the left of Reshad. When I walked into them I was able to continue the quest and finish it.

The quest is definitely broken but some people have been able to make it through. Grian on the forums said they were going to fix some quest issues tomorrow, I'm assuming they meant this one as well.

**Comment by Numbermaniac** [comment]
Reshad was saying nothing for me before, but I disconnected and rejoined about 15 minutes later, and Reshad worked for me! The blue particles @Trixter313 mentioned are a teleport to the next stage of the quest.

**Comment by SkullheadPlays** [comment]
I too was having this problem but when i back tracked and went through the tunnel again and talked to nick then talked to the lady then nicks friend it worked so try that because it worked for me.
