### ISSUE TITLE
how to enter bobs tomb again?

### ISSUE THREAD

**Issue by dyredhead** [Wynncraft/Issues#6933]
how do you enter bobs tomb when you have to get into the tomb?

**Comment by dyredhead** [comment]
it says on wiki I have permeant access after the bobs lost sole quest.

**Comment by dyredhead** [comment]
I'm doing bobs recaranation

**Comment by RogueHatter** [comment]
You still need three people to open Bob's tomb in Nesaak, not sure what tomb you are talking about if you aren't talking about that one.

-RogueHatter

**Comment by dyredhead** [comment]
even if you did the bobs lost sole?

**Comment by dyredhead** [comment]
I thought it gives you permanent access

**Comment by dyredhead** [comment]
and I don't have any friends that play wynncraft

**Comment by Villageacules** [comment]
@dyredhead @RogueHatter This does **not** belong on the GitHub issue tracker. I believe the place you're looking for is https://forums.wynncraft.com/forums/questions.89/.
