### ISSUE TITLE
Decrepit Sewers Dungeon Glitch

### ISSUE THREAD

**Issue by Heaxeus** [Wynncraft/Issues#6934]
In the Decrepit Sewers Dungeon, I get past the room in which you must kill enemies to get tokens to throw in a hopper to open a gate to go into a corridor. However, in the corridor, about halfway down, there is an invisible wall with the boss of the dungeon saying that I do not value my life.

Others have posted about this issue, but a fix was nowhere to be found. Is this a permanent thing that can't be fixed, or am I doing something wrong?

**Comment by Heaxeus** [comment]
Changes versions from 1.11 to 1.8.9 has fixed it.

**Comment by DebugMC** [comment]
#6340

**Comment by CloudyBogdan** [comment]
I used 1.11.2 and there was a wall but now I use 1.10 and it works
