### ISSUE TITLE
"Hidden City"

### ISSUE THREAD

**Issue by J0shthomp** [Wynncraft/Issues#6935]
When I try to inspect the house like it says in the quest I am stopped and the NPC doesn't respond and do its little chatter like it should in the quest. Instead he is just standing there. 

![dammit](https://cloud.githubusercontent.com/assets/24664751/21338122/e0c2aafc-c638-11e6-80eb-6a03b4d49de4.jpg)

![2016-12-19_22 16 56](https://cloud.githubusercontent.com/assets/24664751/21338128/e9047416-c638-11e6-94b7-2b3d9debea00.png)

I've tried changing worlds, doing /kill and other stuff. There is one way up and I have run up and down countless times. Can someone tell me how to fix this???

**Comment by beddarcheddar** [comment]
Myself and another guy I just found online are having the same issue. We tried hopping as well, to no avail. I tried entering the puzzle again too.

**Comment by AscendedKitten** [comment]
It's been more than 30 days without a response to this issue. There've been no further reports of this issue to my knowledge, but if it persists feel free to open a new one.
