### ISSUE TITLE
Worldedit //line through map starting at -559 -3568 in ocean

### ISSUE THREAD

**Issue by TheOriginalFestix** [Wynncraft/Issues#6936]
Worldedit //line through map starting at -559 -3568 in ocean on Server 4. Coal blocks. Leads almost to Volcanic Isles.

**Comment by Trixter313** [comment]
Is it only on server 4 or is it on other ones as well? If it's limited to one server it might be temporary and fix itself after the specific world restarts.

**Comment by TheOriginalFestix** [comment]
I am yet to check this.

**Comment by Numbermaniac** [comment]
It appears to be Obsidian actually, and it's on Server 1 right now.

**Comment by Hawkndrag** [comment]
And server 5 Has this as well 
![2016-12-20_01 55 59](https://cloud.githubusercontent.com/assets/20382077/21340933/ad8c2978-c657-11e6-805a-169fb5d1431f.png)

**Comment by thefinpat** [comment]
it is on all servers I think or at least it is also on server 19 as well
![image](https://cloud.githubusercontent.com/assets/24681602/21358114/9e7d72d4-c6cf-11e6-9703-c708cf7b2b8d.png)

**Comment by thefinpat** [comment]
it took me roughly 6 minutes to get from one end on the coastal trail to the other end

**Comment by Trixter313** [comment]
Hmm, it's odd that it isn't on _every_ server but it does appear to be sticking around. Maybe there are a couple backup worlds that the servers pull from when they restart and only one of the backup worlds has this mistake. Not sure, just speculation.

Anyway, it should be fixed soon, hopefully.

**Comment by AckroWynn** [comment]
It's not there on the build server. There have been map updates since then, I believe, so the issue should be nonexistant.
