### ISSUE TITLE
Seasail on Selchar - doesn't work to Dead Island

### ISSUE THREAD

**Issue by wizardcheetah55** [Wynncraft/Issues#6937]
I have dropped 3 passes to Dead Island at the Seasail Merchant pan on the ship. Nothing happens. I even exited and re-entered on a different server. The same problem occurred.

**Comment by Numbermaniac** [comment]
I threw in 2 passes to Nemract and it did nothing, too. :(

**Comment by wizardcheetah55** [comment]
I just tried it again. It works now. This can be closed.
