### ISSUE TITLE
Repeatedly getting kicked out since Wynnter Update (Bug with Missions)

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#6938]
Ever since this Wynnter update I just get kicked out at random times. It always seem to happen when I stop moving, like if I was just walking, and then I stop, I can sometimes get kicked. Minecraft 1.8.9, I don't know what I'm doing to trigger this kick. Screenshot is the error I'm getting. I never had this issue before this most recent update.
![screen shot 2016-12-20 at 17 44 58](https://cloud.githubusercontent.com/assets/5206120/21340707/6ca10020-c6dc-11e6-952f-23de69c538b0.png)

**Comment by JuicedBananas** [comment]
Also experiencing this, appears to be linked to missions starting and ending, every time it's occurred to me I've either heard the sound that plays when one starts, had one end, or typed "/dismiss".

**Comment by Numbermaniac** [comment]
Yeah, seems like it's also happening to me when I /dismiss or fail a mission.

**Comment by forrester-marc** [comment]
Getting kicked every time I complete a mission here.

**Comment by OfficialAlexUK** [comment]
been getting the same thing

**Comment by naybelline** [comment]
I'm also experiencing this...

I am also getting the missions noise too and then the disconnection 

http://prntscr.com/dlple3

**Comment by naybelline** [comment]
http://prntscr.com/dls7ho

**Comment by thecoolkogut4** [comment]
im also getting tbis error too, its quite annoying.

**Comment by InsertnamespaceHere** [comment]
Me too ;-;

**Comment by forrester-marc** [comment]
Note that if /dismiss still gets you kicked, you can avoid disconnection by returning to /hub, then logging back into your game server.

**Comment by NadikiShadowcrafter** [comment]
This happens when time runs out, when /dismiss is used, and I assume if you complete it as well... It's annoying af, especially for those of us that take 5 minutes to join/load the resource pack.

**Comment by infered5** [comment]
I can confirm this happens with a 1.10.2 client running only Forge and Optifine. Happens when you complete, fail, or dismiss the mission, regardless of location or mission.

**Comment by Charizard841a** [comment]
The Combination of the fallback glitch while going through a portal/exit can also result to a wrong warp. I discovered that 2 days ago.

**Comment by Moe-Ronickah** [comment]
Missions have been disabled until this is resolved.

**Comment by DebugMC** [comment]
This should be left open though, anyway on 1.10 this is not an issue oddly.
