### ISSUE TITLE
any way of fixing this?

### ISSUE THREAD

**Issue by OfficialAlexUK** [Wynncraft/Issues#6940]
i have been kicked a lot of times today and it keeps saying https://gyazo.com/5033eae9e0157ba455d2ad4c0eeebe75 and i dont know how to fix it, because it keeps happening every 5mins

**Comment by forrester-marc** [comment]
It's happening whenever you get a mission.  https://github.com/Wynncraft/Issues/issues/6938

**Comment by naybelline** [comment]
Same!
