### ISSUE TITLE
Wynncraft map glitch

### ISSUE THREAD

**Issue by Jacob32587** [Wynncraft/Issues#6942]
I would traveling the ocean then I noticed the map on the website was going off the map here's where I am and what It looked like on the Wynncraft map.
![wynncraft map glitch](https://cloud.githubusercontent.com/assets/24637448/21359846/894da4ca-c6ab-11e6-9ce2-81b99e399c3f.PNG)
![Uploading 2016-12-20_11.58.24.png…]()

**Comment by Jacob32587** [comment]
There's air ballons and houses on mountains but there's invisible blocks so I can't climb the mountains

**Comment by Trixter313** [comment]
If you switch to another world then back to world 10 does it fix itself? It might just be a weird one time issue.

**Comment by aceIEOT** [comment]
When they added corkus, they had to expand the ocean where you are. The map just hasn't updated to show the new additions yet. Just keep sailing east until you get to the volcanic isles or an island close and you should be back on track.

**Comment by DebugingLonks** [comment]
Also happens when fighting CoW or doing dungeons (at least the sewers one)

**Comment by Lowrider800** [comment]
That is because these places are not in the actual wynncraft game, these are the places you get teleported to because of a ship travel, or dungens, and other things.
