### ISSUE TITLE
Recipe for Disaster: Salt Mines Broken

### ISSUE THREAD

**Issue by TheEricZ** [Wynncraft/Issues#6943]
The cave is permanently collapsed for me even though I have never completed the portion that causes the collapse and have yet to get the salt. I have tried walking out of the cave and back in, changing classes, changing servers, logging out and back in, and yet the cave still stays collapsed, preventing me from going further with the quest.

**Comment by thecoolkogut4** [comment]
are you sure your at the right place? Im pretty sure there are two caves right ontop of eachother and you migjt be in the wrong one

**Comment by TheEricZ** [comment]
I'm pretty certain. I even checked an online walkthrough when I first saw the wall.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
