### ISSUE TITLE
Trouble with going into "General's Orders" quest town.

### ISSUE THREAD

**Issue by SlipperySlimYT** [Wynncraft/Issues#6944]
I was climbing in the mountains around the General's Orders quest town to do it, and I use my Escape Spell, and I get stuck while it is repeatedly saying, "You do not have access to this town yet." So I'm stuck, and I accidentally drop my legendary Maelstrom bow.

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town. Once in the town you can walk (no spells so you wont get stuck again) and try to start the quest

Goodluck!

**Comment by SlipperySlimYT** [comment]
>I know. I did that, but I lost my Maelstrom Bow in the process...

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy so unfortunately we can't do anything to return the item. To prevent accidentally dropping an item again, I'd suggest changing the drop item key to something that is less likely to be accidentally pressed.
