### ISSUE TITLE
Player Head textures default to Steve when you log into the game.

### ISSUE THREAD

**Issue by MichaelPriebe** [Wynncraft/Issues#6945]
Wasn't really a problem because it was rare you would ever get an item that uses player head, but with the Craftmas Gifts now its very prevalent.

**Comment by thecoolkogut4** [comment]
this happend before and still does, hive tokens, and othet ones also break. thanks for the report though!

**Comment by Numbermaniac** [comment]
It used to happen to me even before the Wynnter update. Taking off a helmet and walking a block seems to fix it.

**Comment by princessluna1999** [comment]
i log on to this sever and chose thing and then im a dude i agirl and i don't approve of my skin be a due

**Comment by Numbermaniac** [comment]
@princessluna1999 If you're getting the default Steve skin, that's a glitch as we said. If that's your normal skin, you may want to change your skin, then.

**Comment by DebugingLonks** [comment]
@ColinRioux this issue is really important actually. The items for ??? don't work if they are steve (and the painting doesn't either idek) LordHelmenchmen can tell you about it, he helped me when I had to deal with this issue. Its important for other quests, but I don't remember which.

**Comment by LordHelmchen98** [comment]
@DebugingLonks `LordHelmenchmen` xD
Also @Numbermaniac that wasnt the topic here. If you have skulls with textures they loose their textures sometimes and have a normal steve skin.

**Comment by Numbermaniac** [comment]
@LordHelmchen98 I was responding to @princessluna1999 's comment, which sounded like they were complaining about the Steve skin when you log in, but with the appalling grammar and spelling I couldn't tell for sure.

**Comment by LordHelmchen98** [comment]
@Numbermaniac I wasn't talking about your second comment but about your first. However let's just stop this, it's unnecessary.

**Comment by DebugMC** [comment]
@AscendedKitten this should prob be renamed "Items with NBT glitch when switching servers" since this is not only for player heads (like paintings from skiens island) or Hive vouchers (or so I have heard)
