### ISSUE TITLE
ONLY RED CRYSTAL NONE OF THE OTHERS

### ISSUE THREAD

**Issue by hockeyloverkid** [Wynncraft/Issues#6947]
i only have the red crystal from site c plz tell me!!

**Comment by ColinRioux** [comment]
`/fixquests`

**Comment by hockeyloverkid** [comment]
i did that

**Comment by hockeyloverkid** [comment]
doesnt work says i sould check my e chest or my inv

**Comment by ColinRioux** [comment]
Can you confirm you did sites A and B?

**Comment by hockeyloverkid** [comment]
yes

**Comment by Villageacules** [comment]
https://forums.wynncraft.com/threads/guide-to-contributing-on-official-github-issue-tracker.170506/ Please refer to our community guide to properly creating an issue.
