### ISSUE TITLE
??? Quest (red meteor puzzle bugged)

### ISSUE THREAD

**Issue by MindBolt** [Wynncraft/Issues#6951]
So, i tried to make the puzzle to enter the red meteor in ??? and the up arrow to move the green thingy is bugged, it wont move it up so the only options are left, right and down, please i need help, i tried switching servers and nothin works.

**Comment by ColinRioux** [comment]
Please modify your post to reflect: https://forums.wynncraft.com/threads/guide-to-contributing-on-official-github-issue-tracker.170506/

And please add screenshots. Thank you.
