### ISSUE TITLE
??? Quest: Red Meteor Puzzle not Working Properly

### ISSUE THREAD

**Issue by MindBolt** [Wynncraft/Issues#6953]
in the stage where you have to get into the Lab by solving a puzzle that needs to paint all blocks green, the up arrow that controls the green color is not working properly, making it impossible to solve it, making the completion of the ??? unreachable, I have tried switching servers and game version but it still not responds.

**Comment by naybelline** [comment]
Having the same problems, can't move the up button :(

**Comment by LordHelmchen98** [comment]
Confirmed. It happens for me as well.
I recorded it so evidence can be found [here](https://youtu.be/7SLgIrsgUZg)

**Comment by Villageacules** [comment]
Closed under the assumption it is now working.
