### ISSUE TITLE
Powders look like ink sacs when dropped

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#6956]
![2016-12-21_18 35 05](https://cloud.githubusercontent.com/assets/5206120/21381781/5fe6e13a-c7b1-11e6-8e02-2e22a2cb2b15.png)

Seems to do this for all powders, tested with Thunder II and Fire I and Earth I.

**Comment by LordHelmchen98** [comment]
Hmm I have the same issue if I kill 'Flarelings' in the Molten Heights but I'm pretty sure drops I get from other mobs aren't looking like ink sacks.

**Comment by Moe-Ronickah** [comment]
They are supposed to look like ink sacs.  You killed a mob that is colored by it's own ink sac, so, when you kill it, you collect the ink sac and dry it, and convert it into a powder.
