### ISSUE TITLE
Died in a quest in Wynn; spawned in Llevigar

### ISSUE THREAD

**Issue by LegendaryUlk** [Wynncraft/Issues#6959]
I was in a mission in Wynn which is called, 'Macabre Masque' and when i died i spawned in Llevigar. I am level 23 and for some reason i spawned in a place 5000 blocks away. -_- Now i have to pay to get back and restart the mission. Here is a screenshot of me in Llevigar.

![image](https://cloud.githubusercontent.com/assets/23142956/21392344/4b01a054-c787-11e6-9f2e-6284674bcb52.png)

**Comment by LordHelmchen98** [comment]
I assume you have been in Llevigar before. If not I'm speechless. If you have been there you got there due to the current respawn system. The area in Macabre Masquerade is offmap and apparently the closest respawn point was Llevigar.
