### ISSUE TITLE
mission creash

### ISSUE THREAD

**Issue by weshuiz** [Wynncraft/Issues#6960]
there are minimissions as i lilke to call them
for example miission: kill 10 rased dead for 300xp
after a mission like that almost reaches 5 seconds left i will creash and i have to restart minecraft in order to keep playing this is been bugging me for 2 days now i think becuse thats the 1 time i enouterd that
im lvl 60 mage if that matters

**Comment by NadikiShadowcrafter** [comment]
I am having the same issue. Whenever I fail a mission, I crash with the message: "Could not connect to default or fallback server, please try again later: java.net.ConnectException". It's super annoying, and made me crash in the middle of The Eye of the Storm quest so I had to redo all three levels of the puzzle.

**Comment by weshuiz** [comment]
hmm iuntresting this seems to happen to more players im getti g the same error rasult

**Comment by NadikiShadowcrafter** [comment]
The crash also happens if I use /dismiss. I don't know if completing the mission causes it yet, but I assume it does. So basically, if I get a mission, I'm screwed.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/6938

**Comment by NadikiShadowcrafter** [comment]
This also happens to my brother and my cousin, so it seems too common to be isolated to a few people

**Comment by NadikiShadowcrafter** [comment]
Oh well yep, there's a main error thread. Close the issue, refer to the main one
