### ISSUE TITLE
The Coordinates Of The House Of Twain NPC Are Wrong.

### ISSUE THREAD

**Issue by DeleteTheFox** [Wynncraft/Issues#6961]
Well, In the Quest book it shows that the NPC that starts the quest for The house of Twain is located in this coordinates: -10, 76, -451

https://cloud.githubusercontent.com/assets/24701383/21397146/cdaa7b32-c789-11e6-8be9-74dc9cebc579.png

But in reality he is located in this coordinates: 11, 76, -455

https://cloud.githubusercontent.com/assets/24701383/21397195/006cd358-c78a-11e6-9d70-fb4d0a813e80.png

It's just 20 blocks, but i spent a lot of time in the other side of the mountain (In the Tower of ascension area) looking for him, so i suggest it get fixed.

**Comment by ColinRioux** [comment]
@Villageacules

**Comment by Villageacules** [comment]
Fixed, closed.
