### ISSUE TITLE
Meaningful Holiday causes extreme client lag

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#6963]
During [Stage 7](https://wiki.wynncraft.com/index.php?title=Meaningful_Holiday#Stage_7) of the Meaningful Holiday quest, you are asked to follow Nick, and he disappears into a "portal". The portal creates over 16,000 particles, which is enough to drag my FPS down from 60 to 8.

Screenshot (note the particle count, `P: 16390`)|<img width="2560" alt="particles" src="https://cloud.githubusercontent.com/assets/16504771/21406513/ecc352ae-c780-11e6-889b-b6f91be92bdd.png">
---:|:--:

**Comment by xCykrix** [comment]
I had to restart my minecraft entirely to get up to 20FPS for this area. Once you warp through and getting ready to warp was absolute hell.

**Comment by ColinRioux** [comment]
You could turn off particles, frankly. Or put them to minimal
