### ISSUE TITLE
Glitched Horse

### ISSUE THREAD

**Issue by DChen3254** [Wynncraft/Issues#6965]
I was riding the Jungle outside of Troms on my white horse and out of nowhere I was kicked from the game. When I reconnected my horse was gone. I know that I won't get my horse back but I was wondering if this could be connected to the string of glitches that followed the Wynnter update. Thanks for reading.

**Comment by naybelline** [comment]
My friend lost his helmet to that glitch too,  he was just putting it on and the served kicked him .. helmet gone. I've donated him another but still crappy

**Comment by ColinRioux** [comment]
Items disappearing after being kicked has been going on for quite some time now. But there will be more and more glitches as the player base demands new content. I have no idea when it'll be fixed, but my apologies.
