### ISSUE TITLE
Random Disconnects on 1.8.9

### ISSUE THREAD

**Issue by xCykrix** [Wynncraft/Issues#6968]
Hello, For the past week this issue has been driving me up a wall. I get (attached image) usually when I connect or a server "goes down" but does not actually go offline, and kicks me back to the lobby and/or disconnects me entirely.

![image](https://cloud.githubusercontent.com/assets/12182390/21414745/d57d1250-c7c7-11e6-9c16-0c08ad5881d6.png)

Image of Chat
![image](https://cloud.githubusercontent.com/assets/12182390/21414752/f1da1da8-c7c7-11e6-8e6f-5ae5ce2f037d.png)

**Comment by xCykrix** [comment]
6 times in a hour already..

**Comment by thecoolkogut4** [comment]
not 100% sure but i believe it is from the missions that pop up every so often.

**Comment by xCykrix** [comment]
Possibly, but how does that explain my disconnect logging in aswell? It happens ingame and main menu. @thecoolkogut4

**Comment by ColinRioux** [comment]
Admins are aware of it. 

My hypothesis is it has something to do with a server being down + the version proxy. Not sure though. Best to remain patient. It's been happening to me too.

**Comment by xCykrix** [comment]
@ColinRioux I'm pretty sure that is the cause too. I heard some people mention missions will disconnect you in certain places such as the Demon Cave. However that sounds most logical for most of the issues.

**Comment by DebugingLonks** [comment]
You should reopen, this happens on every version lol
