### ISSUE TITLE
Bug of Block

### ISSUE THREAD

**Issue by PedroVitorBr** [Wynncraft/Issues#6970]
Me and my friend were playing on the server, completing quests until when a person finished killing the boss and when he teleported to leave the cave he bugged the block and was unable to move and so we stopped playing on the server. I would like to return to play without server with it only so far not desbugou. I wish some team would help him so we could play again.

Sorry my Inglish I'm not very fluent

**Comment by thecoolkogut4** [comment]
he bugged the block? do you mean he got stuck in a block?

**Comment by Trixter313** [comment]
Your friend can type the command /kill into chat and it should get them out.
