### ISSUE TITLE
Stuck in Nemract

### ISSUE THREAD

**Issue by BaconPai** [Wynncraft/Issues#6972]
I'm stuck in Scroll Merchant's roof in Nemract, relogging doesn't work and I can't use teleport scrolls to get out 
pics from me and my friend; https://images.discordapp.net/.eJwFwdENhCAMANBdGIBaqj1wG4IEzSklUOPH5Xb3vZ-5-2lWs6u2sQJsx0jSNztUeizZFpFy5tiOYZNcEFVj2q9cdQAyUVi8n9gHIiaH4BgZw4dmZOeJ5snDXb9VnmpbLeb_AgiKIuI.YCNfWK_aBgjKZ_yJQi2uzwW356c

https://images.discordapp.net/.eJwFwUEOhCAMAMC_cLelrSL4mQ1BgiYqBOpps3_fma95-2U2c6i2sSHu50i17zC09lgylFrLlWM7B6R6Y1SN6bjzowPJiYTFe-t8EHHChOzIUZgp-NUGtqudkS25iXhi_rAAEywe2lPM7w-MhyOu.Smz_bX4sbFjjqs0jEbQvAThWD3A

**Comment by LordHelmchen98** [comment]
Do /kill if you have more than 5 soul points.
