### ISSUE TITLE
Don't have permission to press buttons in WynnExcavation Site A

### ISSUE THREAD

**Issue by AFluffyPlatypus** [Wynncraft/Issues#6974]
Whenever I try to press a button in WynnExcavation Site A or open a loot chest, it comes up with an error message telling me that I don't have permission for this area [See screenshot]. This means that I can't press the buttons in Stage 5 (https://wiki.wynncraft.com/index.php?title=WynnExcavation_Site_A#Stage_5 ) to get to the next room, leaving me stuck.

**Comment by Trixter313** [comment]
This usually happens when you try and interact with something while holding a weapon. Since many items are retextured blocks the game thinks you're trying to place a block. Pressing the button with an empty hand should work.
