### ISSUE TITLE
New Craftmas quest provides free teleport to Almuj even after completion

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#6975]
If you've already completed the Craftmas 2016 quest, then you go back into the ballroom, and then try to exit from the same portal, Nick's speech plays again, and then you're teleported to Almuj for the last part of the quest. It's theoretically a free teleport from Detlas to Almuj even after the quest is done, but I don't know if it's intentional or not.

**Comment by LordHelmchen98** [comment]
This is not a bug. Thats just how quests work. You can access them more than once (lets ignore Purple and Blue). Also in my opinion I still get to Almuj faster by foot than by using this option.

**Comment by Moe-Ronickah** [comment]
RESOLVED
