### ISSUE TITLE
Small typo with Head Engineer's dialogue in Heart of Llevigar

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#6978]
![2016-12-22_19 54 06](https://cloud.githubusercontent.com/assets/5206120/21454065/7f5f05f6-c969-11e6-9bd8-635fe34a7e14.png)
See screenshot. Message 5/6 should be "best bet **is**", not "best bet **it**".

**Comment by AckroWynn** [comment]
Fixed!
