### ISSUE TITLE
I Lost An Almuj's Liquified Emerald And I Can't Finish The Quest Now

### ISSUE THREAD

**Issue by ThatGuyDucky** [Wynncraft/Issues#6979]
I was doing the jungle fever quest, and I got the 64 LE as usual, and as I was running back to Worid in the Jungle and I accidentally pressed right click and threw my LE, but it didn't come back, and it disappeared from the stack and so I had 63, At first I thought I was just lagging so I waited for a bit but it didn't come back, so I restarted my Minecraft but I still had 63, So I Thought it was a visual glitch and when I went to speak to him but it wouldn't let me finish the quest, I checked the quest book if I was doing something wrong but it told me to speak to Worid and that is what I was doing, I have tried /fixquests but it said I have no missing quest items.
Please help fix this as I don't know what to do, I cant complete this quest. :(

**Comment by LordHelmchen98** [comment]
You could try to glitch them out of you inventory (e.g. put them in your daily reward or fill up your inventory replace the LE and then close your inventory) and then do /fixquests.

**Comment by LordHelmchen98** [comment]
Welp. Did you get back anything or is it just gone now?
However, regardless if you got the 64le back or not, if you really want to finish that quest I'm afraid you have to level up another class just to get those 64le and then you could switch the LE to your first class and delete the new one as you would have the same problem with it.
