### ISSUE TITLE
No Class to be found

### ISSUE THREAD

**Issue by Omnireg** [Wynncraft/Issues#6981]
This issue doesnt effect me, but a friend of mine. The account name is "khewanlala"
They attempted to play, and on the class selection screen there was no class available, and I remember them having a lvl50+ Mage. Not sure what caused this, switching servers didnt help, restarting and playing diffrent versions didnt help either.

**Comment by Trixter313** [comment]
So their class doesn't show up? The first thing I think of is they might have accidentally deleted their class. If you right click on a class you can delete it and if you just exit the confirmation without clicking the decline button it will delete it anyway.

**Comment by Moe-Ronickah** [comment]
@Omnireg , are you certain that you are spelling your friend's MC account correctly?

**Comment by DebugingLonks** [comment]
lol i had this before no fix still, im not even going to ask for it, but all my classes (2 were lvl 100) got deleted and all my stuff, but not bank ;( anyway im rebuilding now so dw about trying to fix it

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
