### ISSUE TITLE
Can't login it

### ISSUE THREAD

**Issue by OfficialAlexUK** [Wynncraft/Issues#6983]
this is what happens when i tried to join https://gyazo.com/4480f502211eea64b931b57f6e1249ed 
keep in mind this is my first time today logining

**Comment by LordHelmchen98** [comment]
Although it's fixed apparently I want to ask you one thing: Did you click on a fishy link in the last days? If not, I guess everything is ok. But if so and if some of your items are missing, I highly recommend you change your Minecraft password.
