### ISSUE TITLE
My friend invited me to his guild[TOS], but i used [/guild join TOS] but failed.

### ISSUE THREAD

**Issue by wuhyman** [Wynncraft/Issues#6985]
My friend invited me to his guild[TOS], but i used [/guild join TOS] but failed.

**Comment by LordHelmchen98** [comment]
What did it say in your chat? Most likely it's just a temporary issue. Switch to another server and tell your friend to invite you again then try to join again. It should work that way.

**Comment by wuhyman** [comment]
thx

**Comment by Trixter313** [comment]
@wuhyman is your issue resolved now?

**Comment by wuhyman** [comment]
I also cannot join. It said [You have been invited to join Forgotten Memories by Hope_Fox! Type / guild join TOS to accept!
Then I used /guild join TOS, but it said that [You were not invited to join TOS]

**Comment by Trixter313** [comment]
The first thing I think of is this issue: https://github.com/Wynncraft/Issues/issues/5839 but it's hard to check whether there's another guild with the same prefix because you can't search for prefixes on the Wynncraft site.

**Comment by wuhyman** [comment]
So do not have any way to solve this kind of problem just now?

**Comment by Trixter313** [comment]
No, not currently. Guilds are very buggy right now and are due for a revamp.

**Comment by DebugingLonks** [comment]
It happened to me, its happened to me many times actually. Try doing /guild join (Players name), relogging, and if that doesn't work try typing in the actual guild name

**Comment by Moe-Ronickah** [comment]
"**try typing in the actual guild name**"

**Comment by DebugMC** [comment]
Tried this last night after making my name Debug__, it says "You were invited to join HippiesOfSnuggles" (The guild im in. I left pre-name change to prevent bugs :P) It would say i was not invited. I then relogged, switched servers and it said its full (which it wasnt) but i got in eventually

**Comment by Moe-Ronickah** [comment]
RESOLVED
