### ISSUE TITLE
The realm of light quest bug

### ISSUE THREAD

**Issue by PsychoNater** [Wynncraft/Issues#6987]
when your and soposed to kill light beetles and give they drop glowing powder to Heliorion the beetles don't drop anything

**Comment by LordHelmchen98** [comment]
They don't drop the dust everytime. Sometimes you have to kill plenty of beetles until you get the dust.

**Comment by PsychoNater** [comment]
I was trying for about an hour and they still would not drop

**Comment by PsychoNater** [comment]
Plus they re-gen way to fast

**Comment by Trixter313** [comment]
If you go to another server do they drop?

**Comment by PsychoNater** [comment]
No

**Comment by LordHelmchen98** [comment]
The Beetles do drop it. I just went to that place and got some powders after the first few killed beetles. I dont know if you are just very unlucky or if you have negative loot bonus, but for me it worked perfectly fine.
I recorded it for you: [Video](https://youtu.be/jpRYCHf5rTM)
