### ISSUE TITLE
Mechanical chip door

### ISSUE THREAD

**Issue by Stavrosmet** [Wynncraft/Issues#6989]
![2016-12-25_12 21 24](https://cloud.githubusercontent.com/assets/24762474/21470708/db578628-ca9d-11e6-949f-a60ca5630772.png) 
![2016-12-25_12 21 37](https://cloud.githubusercontent.com/assets/24762474/21470709/dfef940a-ca9d-11e6-9e93-7e998c4462de.png) 

I throw the mechanical chip on the flower and it doesnt take it

**Comment by LordHelmchen98** [comment]
Unfortunately that happens sometimes, you have to switch to another server and do it again.

**Comment by Stavrosmet** [comment]
i do but nothing

**Comment by ColinRioux** [comment]
You need to remain on the same server that you got the mechanical chip on, and you can't log out after getting it. It's NBT data glitch that I'm sure they are aware of. You're going to have to get it again, walk to the gert camp, and drop it in. 

It's unfortunate but that's how it works.
