### ISSUE TITLE
Taproot tiek

### ISSUE THREAD

**Issue by MarianKitka** [Wynncraft/Issues#6991]
I was doing the taproot quest,but on stage 12 (speak to Tiek) Tiek will say "I wrote down what you need to do in your book. The forest needs us". I was in taproot location 2 times, I have all items and still I cant go further. I tried changing server and still nothing. 
![tiek](https://cloud.githubusercontent.com/assets/24763642/21471284/07c18dc6-caad-11e6-8739-090404662d94.jpg)
![tiek2](https://cloud.githubusercontent.com/assets/24763642/21471295/5a490bdc-caad-11e6-9da7-4a77d3b3f776.jpg)

**Comment by ColinRioux** [comment]
There are many variations of Tiek, are you sure you're speaking to the right one. Did you perchance do /kill anytime before getting to where you are now?

**Comment by MarianKitka** [comment]
I'm speaking to the right  one, the one I started quest with. He or she
will just say that I need to do something I already done and have in my
inventory.

26 gru 2016 01:39 "Colin Rioux" <notifications@github.com> napisał(a):

**Comment by LordHelmchen98** [comment]
So you already passed the two huge rocks?

**Comment by MarianKitka** [comment]
I was in the taproot,everything was right and I got the dead plant. Next
task was to talk with tiek, but it's like it didn't counted. I was there 2
times to be sure, but tiek still says that she wrote down what I need to
do.

26 gru 2016 19:31 "Lord Helmchen" <notifications@github.com> napisał(a):

**Comment by LordHelmchen98** [comment]
If you still werent able to solve it I can maybe meet you ingame and then we can do it together.

**Comment by MarianKitka** [comment]
Ok then.  That would be nice.


29 gru 2016 00:44 "Lord Helmchen" <notifications@github.com> napisał(a):

**Comment by LordHelmchen98** [comment]
I can't meet you ingame right now but apparently your time zone is gmt +1 as well, so I guess we will find a time when we can meet.

**Comment by MarianKitka** [comment]
Yeah I received mail at 1 am so I couldn't play either.

29 gru 2016 01:25 "Lord Helmchen" <notifications@github.com> napisał(a):

**Comment by LordHelmchen98** [comment]
Hmm I did the quest without any problems today. Have you finished it yourself now? Otherwise tell me when you can get online.

**Comment by MarianKitka** [comment]
Still didnt do it. I have all required items in inventory (I think so),but still I cant speak with Tiek

**Comment by Moe-Ronickah** [comment]
"Return to Tiek with 1 Ginseng, 1 Lobelia, and 1 Vervain," but not the one's from her garden, right?

**Comment by LordHelmchen98** [comment]
@Moe-Ronickah As MarianKitka said they got the Dead Plant I think it's later in the quest but we didn't meet yet.
However @MarianKitka if we can't meet ingame take a look [on this wiki page](https://wiki.wynncraft.com/index.php?title=Taproot).

**Comment by MarianKitka** [comment]
Checked wiki, I did everything right. I'm on Chapter 12 I think and I can't
speak with him (have all right items in inventory)

18 sty 2017 14:38 "Lord Helmchen" <notifications@github.com> napisał(a):

**Comment by Moe-Ronickah** [comment]
If, by "Chapter 12", you really mean Stage 12, then this is highly confusing.  Why?  Because you've told us that you are stuck way earlier in the quest.  HOWEVER, if you haven't finished the quest, but are at Stage 12, then Tiek, in the "present" Gavel forest, has nothing to say to you until you finish the quest.

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
