### ISSUE TITLE
Quest didn´t give me all the emerald blocks

### ISSUE THREAD

**Issue by Nooobninja** [Wynncraft/Issues#6994]
i made the "reclaiming the house" -quest and in the chat you can see that i did get 6144 emeralds but in my inventory were just 2176 emeralds. Is this a bug or something? Or did i just do something wrong?
[wynn.pdf](https://github.com/Wynncraft/Issues/files/672276/wynn.pdf)

**Comment by Trixter313** [comment]
Hmm, this issue appeared to be fixed in this report: https://github.com/Wynncraft/Issues/issues/5650
but apparently it's still around.

We will look into it. Thanks for reporting!

**Comment by Trixter313** [comment]
Also, here are the images from the pdf so no one else has to download it:
![file-page1](https://cloud.githubusercontent.com/assets/7178055/21475743/b8b53556-cafd-11e6-96a8-e40c3697e1ff.jpg)

**Comment by AscendedKitten** [comment]
The issue seems to be fixed, I replayed the quest and the reward was correct.
