### ISSUE TITLE
Stuck in a vision (Memory Paranoia)

### ISSUE THREAD

**Issue by HunHero** [Wynncraft/Issues#6995]
I was doing th Memory Paranoia quest, watched the vision which was about master Caritat and Timmy talking. The  "What's this spoon doing in the fireplace? Maybe you should bring it back to the Kitchen to find out where it came from." text didnt appeared yet, so i walked towards the library door and suddenly it dropped me back to the vision and im stuck here, cant move, and cant use TP scroll. 
Can someone help me how to get out from here? 

![2016-12-25_19 53 29](https://cloud.githubusercontent.com/assets/24766484/21472481/2839b6a2-cadd-11e6-9a5f-57efd6faa056.png)
![2016-12-25_19 54 27](https://cloud.githubusercontent.com/assets/24766484/21472482/2e7db5e0-cadd-11e6-922d-b3348527b7a4.png)

**Comment by Trixter313** [comment]
You can try doing /class or switching to another server but if that doesn't work you can always use /kill to get out of stuck situations.
