### ISSUE TITLE
Legend Guard's Plate requires Warrior class instead of Warrior/Knight class

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#6996]
The **Legend Guard's Plate**, obtainable by killing the Temple of the Legends boss, says `Class Req: Warrior` instead of `Class Req: Warrior/Knight`. I have not checked if it is usable in the Knight class.

   Screenshot of Legend Guard's Plate:   |<img width="470" alt="plate" src="https://cloud.githubusercontent.com/assets/16504771/21473394/e5b3866a-cabd-11e6-97c6-bae730c1f2b9.png">
---:|:--:

If it is unusable in the Knight class, then technically, this means that Wynncraft violates the EULA.

**Comment by Trixter313** [comment]
Hopefully someone can test to see if it works on Knight as well. I'm thinking it most likely will. Also I'm not sure it would be a EULA violation since anyone can be a warrior. If it were Knight only, then I could see it.

**Comment by 0x0000null** [comment]
It seems that it *is* usable in the Knight class. (Or at least there's a check mark next to it when you're in a Knight class.) But it should still be changed to `Warrior/Knight`.

Also forgot to mention that this issue is also present on the website.

**Comment by ColinRioux** [comment]
@Villageacules Not sure if you can fix this, but perhaps pass this on to Selvut?

**Comment by dyredhead** [comment]
it does work, my friend is a level 95 and he is a knight it worked for him. sadly he doesn't play any more

**Comment by dyredhead** [comment]
well if something didn't change then it should work and this is just a typo

**Comment by Villageacules** [comment]
I tested the item on GM on a knight class, and it is in fact, usable. Closed.

**Comment by 0x0000null** [comment]
But the text should still be changed.
