### ISSUE TITLE
Logging into a game server

### ISSUE THREAD

**Issue by Scorpioxzz** [Wynncraft/Issues#6997]
I can log into the actually server itself, but when I try to log into a game server, it takes like 5 minutes to join, and 3/4 of the time it just auto disconnects me.

**Comment by ColinRioux** [comment]
As it seems most people don't have this issue, my first hypothesis is that it has to do with your internet connection. It probably auto disconnects you because it is taking too long. 

Can you do a speedtest and let me know your download/upload speed? Thanks.

**Comment by Scorpioxzz** [comment]
My download speed is 9.77 Mbps and my upload speed is 1.40 Mbps

**Comment by DebugingLonks** [comment]
It happens to me all the time, one way you can try to fix this is to /toggle autojoin. This stops it from kicking you when you join :3 i do know it has to do with resourcepack btw

**Comment by Moe-Ronickah** [comment]
@Scorpioxzz , do you have any mods installed, and if yes, which ones?

**Comment by Scorpioxzz** [comment]
I use to play on Wynncraft Enhanced, but now I just use optifine 1.8.8 with labymod and it work fine.

**Comment by Moe-Ronickah** [comment]
RESOLVED
