### ISSUE TITLE
Llevigar: Emerald Merchant is missing in first eastern stall of bank

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7000]
On the western side of Llevigar bank, there is an emerald merchant in all three stalls:
![2016-12-26_22 43 00](https://cloud.githubusercontent.com/assets/5206120/21481551/10595ffc-cbbd-11e6-954e-8e1dfd515f2b.png)

But on the eastern side, the first one is missing:
![2016-12-26_22 43 10](https://cloud.githubusercontent.com/assets/5206120/21481557/22a7be2e-cbbd-11e6-9c3d-0f057454f74e.png)

**Comment by LordHelmchen98** [comment]
@Imaxe is that something you can fix?

**Comment by Imaxe** [comment]
This is now fixed.
It will be updated when we do a map push.
