### ISSUE TITLE
WynnExcavation Site B: Typo in Lykron's text

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7001]
See screenshot, Message 1/1. "colleague" is spelt wrong.
![2016-12-26_18 56 44](https://cloud.githubusercontent.com/assets/5206120/21481597/a8d32524-cbbd-11e6-9073-4a55e658389a.png)

**Comment by Scorpioxzz** [comment]
It's spelled right...

**Comment by LordHelmchen98** [comment]
Uhh. Second last line. "colleauge" is spelt correctly? @Scorpioxzz

**Comment by ColinRioux** [comment]
In the screenshot it is spelt `colleagues`. See: [](https://www.merriam-webster.com/dictionary/colleague).

**Comment by ColinRioux** [comment]
<img width="465" alt="screen shot 2016-12-26 at 3 32 00 pm" src="https://cloud.githubusercontent.com/assets/4181161/21486314/87095d06-cb80-11e6-8a8e-58d73c108159.png">
Typo not in quest dialogue, but normal dialogue. @Villageacules

**Comment by Imaxe** [comment]
Typo fixed! 
Will be fixed next time we push!
