### ISSUE TITLE
Perm Ban Bug after Appeal + Reply

### ISSUE THREAD

**Issue by RealmLord** [Wynncraft/Issues#7002]
I realise I'm simply 'mooning' my own guilt at this moment about what I've done, but I already feel like an a**hole enough for doing what I've done. I created an appeal after my perm ban (the second I got it) with an honest reasoning for what I did, it was rushed, therefore I decided to re-write it the following day worrying that it's nowhere near good enough. So I wrote my name in the username section where Wynncraft identifies players, only to find this "We only accept ban appeals for permanent bans", which of course surprised me because as I tried to log into Wynncraft and see how much time I have to wait, it still said I'm permanently banned.

**Comment by LordHelmchen98** [comment]
So the answer by a mod was that they don't accept appeals for temp bans? I was never banned and I barely have contact to people who were banned so I don't really know what you should do but if I was in your situation I would create a new thread starting with an explanation of your situation (maybe tag the moderator who replied to your previous thread) and why you think there was a mistake, followed by your previous appeal again. However keep it nice and avoid to be rude whatever you write then you should get a second chance.

**Comment by ColinRioux** [comment]
Closing as no response has been provided. Assuming issue is resolved. If not, please create another issue.
