### ISSUE TITLE
Bank issue

### ISSUE THREAD

**Issue by EdPlayZ** [Wynncraft/Issues#7003]
I accidentally bought the 6th row in my bank and i lost some items. 4 Jester necklaces that i have found out that i have lost so far.

**Comment by LordHelmchen98** [comment]
Although it may seem unfair Wynncraft enforces a strict norefund policy to keep up fairness among all players. Therefore you won't get back any items.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/4091
