### ISSUE TITLE
Class Switching

### ISSUE THREAD

**Issue by KryptoLyte** [Wynncraft/Issues#7005]
Alright, so here's the deal; The other morning I got on Wynncraft after not having played in a looong time, When it spawned me in the Reset room place (I have no idea what the place is called) I was on my archer, so I did /class to switch to my mage. Though whenever I click on my mage it waits about 10 seconds and then says "There has been an error... try again." I keep trying but it won't let me log into my mage.
I've tried everything people have told me to try, change the IP from .com to.net and vise versa, spam /hub tried deleting my assassin class even, but nothing seems to fix this.
![error](https://cloud.githubusercontent.com/assets/24783573/21487789/d1c8e2be-cba1-11e6-95ed-941ec19d8d64.png)

**Comment by ColinRioux** [comment]
Well the `122%` xp can be a clear sign something is up. Let me tag @Moe-Ronickah so he can help you.

**Comment by LordHelmchen98** [comment]
Duplicate of #5418 
Though the 122% may be interesting but considering what Moe-Ronickah posted in the original thread I doubt anything/anyone can help you.

**Comment by KryptoLyte** [comment]
Sorry, I must have skimmed over it too fast and didn't see it.
