### ISSUE TITLE
Stuck in tutorial with no weapon

### ISSUE THREAD

**Issue by Madoxx10** [Wynncraft/Issues#7007]
I recently opened Wynncraft on my account (Darknight1233845) and found myself in the Update Room. Since I haven't played Wynncraft in a year, I wasn't wearing any armor or had any usable weapons (But my inventory was filled with unidentified equipment). 

I then left the Update Room, expecting myself to be in a city or something like that, but instead I was back in the tutorial area. I find myself stuck outside the cave, because without a weapon, animals don't seem to drop emeralds, so I can't proceed...Help?

**Comment by Trixter313** [comment]
You should still get emeralds even without a weapon. The drop rate might not be as high as you were expecting, keep trying to kill them ans let us know if you get past.

**Comment by Madoxx10** [comment]
xD I made it work. Issue solved, lol

**Comment by Trixter313** [comment]
Glad to hear!
