### ISSUE TITLE
V.S.S Seaskipper gives no dialogue on way to Selchar, player remains stuck. 

### ISSUE THREAD

**Issue by PsychoNater** [Wynncraft/Issues#7008]
Everytime you go in the sea ss sea skipper and go to selcher the boat guy does not say anything and you just stand there and it won't take you to the destination and have to /kill

**Comment by Numbermaniac** [comment]
Yeah, one of the VSS boats is broken, it doesn't do anything when you drop in a hopper. Rather than killing, you can buy a boat from the merchant for 2EB and ride the boat across the ocean.

**Comment by PsychoNater** [comment]
No I mean it teleports you to the boat but your just stuck there and the guy says nothing so you have to have a scroll or do /kill

**Comment by Numbermaniac** [comment]
Oh, right. That's a different issue, then.

**Comment by PsychoNater** [comment]
Yes

**Comment by RogueHatter** [comment]
I've had this happen to me too. The NPC spammed the first bit of dialogue over and over again. I was with my friend at the time and we sat there for 10 minutes before we gave up and did /kill. The problem for us was having multiple people on the VSS Seaskipper at one time and it screwed it up. I suggest just waiting and going again later, it worked when we waited.

-RogueHatter

**Comment by Numbermaniac** [comment]
@RogueHatter between what towns were you travelling?

**Comment by DebugingLonks** [comment]
I go all the time from nemract there... no problem for me :3 but this seems like #7081

**Comment by Moe-Ronickah** [comment]
@DebugMC , please, this isn't a forum, it's an issue reporting and solving GitHub.  This is a very real issue, and just Saturday night, it hit another player.  I went to investigate, and sure enough, we stayed there, in limbo, for well over 5 minutes.  Sometimes, the Seaskipper is broken.

**Comment by Numbermaniac** [comment]
Switching servers always seems to fix it, by the way.

**Comment by Moe-Ronickah** [comment]
@Numbermaniac , unfortunately, not always.  I wish it did.

**Comment by Trixter313** [comment]
Since most of the reports I've seen for this issue have been while going to Selchar, I'd like to note that another player in issue https://github.com/Wynncraft/Issues/issues/7618 experienced this as well, but while going to Pirate Cove.

**Comment by Saron100** [comment]
I experienced something similar: But I have been teleported to the Ship, and the Captain didn't start telling me something as usual. I soon recognized, that i was stuck, so i typed /kill. Well, and now, I'm in the Tutorial Part of the map. I think it is behind Ragni, that's what my coordinates tell me. Strangely, i have also lost one piece of my gear, but that's nothing big for me to worry about. Can someone help me getting out of here?
(I haven't found a #xxxx for that.)

**Comment by DebugMC** [comment]
You just have to do the tutorial. /kill does that on the boat.

**Comment by Tee7even** [comment]
The same thing just happened with me on the way (well, "way") from _Nemract_ to _Llevigar_. The Seaskipper Captain said nothing on the boat and I was stuck, then I typed "/kill" and respawned at the tutorial location.

**Comment by numbermaniac** [comment]
@Tee7even For next time, you can try switching servers a few times, that might make it work.

**Comment by Saron100** [comment]
Thanks for your help, but since i couldn't start or complete the tutorial, i had to kill myself once more. After that, i respawned in Ragni.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.

**Comment by DebugMC** [comment]
Still an issue

**Comment by LordHelmchen98** [comment]
@DebugMC im pretty sure none of the boats is actually broken right now so if you get stuck thats a one time issue and players can switch servers to fix it.
