### ISSUE TITLE
Purple and Blue Nedlom Dialogue Glitch 

### ISSUE THREAD

**Issue by NeonRider6** [Wynncraft/Issues#7010]
If you try to talk to Neldom in the Purple and Blue quest, you will get blank text. The quest book just says "Go deeper into the heart of the lake"

**Comment by ColinRioux** [comment]
[https://wiki.wynncraft.com/index.php?title=Purple_and_Blue](https://wiki.wynncraft.com/index.php?title=Purple_and_Blue)

It seems you are on stage 10, you won't speak to Nedlom until stage 12. If you've stumbled across Nedlom, there's a good chance you either didn't run over a trip wire, or you entered the wrong way (even if there is a wrong way). I recommend either retracing your steps. 

If you don't respond in 24 hours, I will close this issue assuming it's resolved.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
