### ISSUE TITLE
Stuck in must be new

### ISSUE THREAD

**Issue by natdog400** [Wynncraft/Issues#7011]
I looked and couldn't find this issue but plz correct me if wrong my brother is stuck in must be new where you buy pitons and inspect your items first the use the door behind you he cant leave how can he fix this me and him want to play but we cant because of this

**Comment by Trixter313** [comment]
There might be a walkway with coal blocks that teleports players out but if nothing else works, you can always use the command /kill to get unstuck.

Let us know if this helps, thanks!

**Comment by natdog400** [comment]
Will try thank you

**Comment by natdog400** [comment]
Thank you so much guys my brother is so happy!!!!!

On Dec 26, 2016 10:33 PM, "tyler getman" <skilleracc400@gmail.com> wrote:

Will try thank you

**Comment by Moe-Ronickah** [comment]
RESOLVED
