### ISSUE TITLE
Cow pass still requires passes

### ISSUE THREAD

**Issue by Madoxx10** [Wynncraft/Issues#7012]
After I completed the cow quest (A confused farmer) that grants you free access to the Cow Pass, I realised that it still asks me for a pass. I've used the Cow Pass several times already and every time, the cow bouncer made me put a pass in the hopper. (Now I'm out of passes, lol)

Is there something more I have to do to actually get free access? When the quest completed, it clearly said I had access to the Cow Pass. xD

**Comment by Numbermaniac** [comment]
Yeah, every time you want to use it, you have to put in a Cow Pass. I believe it actually says if you hover over it, that it only gives access once.

**Comment by LordHelmchen98** [comment]
The cow pass that is meant by the text at the end of the quest is the actual path to the house close to Detlas. That isn't related to the papers you need to use the cow pass. However it's really not hard to get one of the tickets. Just kill a few mobs inside the cave or do the Lost Sanctuary dungeon a few times so you can buy the passes from the dungeon shop with fragments and you should be fine.

**Comment by Madoxx10** [comment]
Oh... xD Well, thanks for the info~
