### ISSUE TITLE
Lost Tower quest didn't give emeralds

### ISSUE THREAD

**Issue by Creeperlover2001** [Wynncraft/Issues#7014]
Steps to recreate: Have 2 of the Book of the Bones, and a nearly empty inventory

**Comment by Moe-Ronickah** [comment]
By "nearly empty", we can surmise that you had either emeralds or emerald blocks in your inventory.  In which case, the game mistakenly detected those as you having the emeralds from the quest.  Don't have emeralds, in any form, in your inventory, when completing quests.
