### ISSUE TITLE
Missing Texture on bow

### ISSUE THREAD

**Issue by BoszXV** [Wynncraft/Issues#7017]
On the legendary _Mesarock Arch_ bow, it doesn't have a bow texture and is just a regular prismarine block 
![2016-12-27_13 53 36](https://cloud.githubusercontent.com/assets/24793719/21501027/4320da1c-cc3c-11e6-8ec8-6db9cdf03466.png)

**Comment by thecoolkogut4** [comment]
join the server with Mc version  1.9 and up to fix the texture.

**Comment by BoszXV** [comment]
I'm using MC version 1.11

**Comment by LordHelmchen98** [comment]
Well that might be the problem as well. Can you try 1.9 and tell us if that helped?

**Comment by BoszXV** [comment]
On 1.9 it also has the same issue 
![2016-12-27_17 42 00](https://cloud.githubusercontent.com/assets/24793719/21505058/e524531a-cc5b-11e6-8649-c4d21db8f36e.png)

**Comment by LordHelmchen98** [comment]
Have you tried to delete the legacy file in your server-resourcepack folder?

**Comment by BoszXV** [comment]
yep, still get the same issue

**Comment by DebugingLonks** [comment]
It happens to that and stone slabs... and wool?

**Comment by Minimeep1** [comment]
The texture is a prismarine block. Duh. That's so cool! ;)

**Comment by DebugingLonks** [comment]
Wrong. Its Not. I ONCE got the texture on the item, its the same as the element bow (infinity, relic bow (from relic), and the bow 'relic' (lvl 12 legend). Also 'King of Blocks' has this texture ironically

**Comment by LordHelmchen98** [comment]
@DebugingLonks You don't say xD
I'm pretty sure @Minimeep1 was kidding. Though GitHub might not be the very best place for jokes.

@BoszXV In this repository there is a resource pack file you can download. Maybe you can try it with that one. Just rename it If necessary and replace the legacy file in your folder.
