### ISSUE TITLE
Arrows stuck in bank

### ISSUE THREAD

**Issue by Wolf10264** [Wynncraft/Issues#7018]
Hello, as the title says, arrows are stuck in my bank. I know this was an old issue from  (#3147) , but from what I read up so far, I need a staff member to remove the arrows from my bank. So, could someone remove them for me?
IGN: Wolf10264
![752165c90c15472c9700ca94bf66363e](https://cloud.githubusercontent.com/assets/24794221/21501821/3f265d2e-cc19-11e6-85eb-3303a60a340b.png)

**Comment by Imaxe** [comment]
I suggest messaging Pretzule about this.

**Comment by Moe-Ronickah** [comment]
@Wolf10264 , please do message Pretzule about this on the forums.  Thanks.
