### ISSUE TITLE
Hollow Sirene bug

### ISSUE THREAD

**Issue by survivalmonkney** [Wynncraft/Issues#7020]
I started the quest Hollow Sirene and when I went into the cave right after talking to Laloire (stage two on the wiki), it didn't stop me from going inside. I could explore freely, although the wiki says I should get some dialogue. I thought it might just be a questbook bug, so I went to talk to Laloire again but he didn't do anything. Seems like a lot of people have problems with this quest.

**Comment by LordHelmchen98** [comment]
Are you sure you didnt miss a quest book update because you skipped a tripwire?

**Comment by survivalmonkney** [comment]
I've walke up and down that path going down into the cavern about 10 times, so I doubt it. Where, exactly, is the tripwire? I'll try stomping on it.

**Comment by DebugingLonks** [comment]
Hit f3 and look around, you can see what your looking at on the right middle of f3 ;) thats how you find tripwire

**Comment by survivalmonkney** [comment]
Ok, thanks, I'll try it in the morning.

**Comment by survivalmonkney** [comment]
Yep, it worked. just had to explore a little deeper in the cave, thanks.
