### ISSUE TITLE
Lost Chestnut horse in boatride at underground cript

### ISSUE THREAD

**Issue by etronmortron36** [Wynncraft/Issues#7021]
couldnt grab it because it fell in the water and it keep tp me back to the boat. please help

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by Numbermaniac** [comment]
I thought you still have the saddle with you, so you can just click to despawn it? Or did you lose the saddle?

**Comment by etronmortron36** [comment]
I thossed the saddle and I couldn't jump I  the water to get it :(

**Comment by Trixter313** [comment]
There isn't really much we can do here, it doesn't let you jump in because we don't want the player leaving the boat.

The only thing I can suggest is changing your drop item key to something less likely to be accidentally pressed.

**Comment by etronmortron36** [comment]
I didn't know if there was something that could detect falling items and
put it back in the boat.
