### ISSUE TITLE
I lost my horse when I used the teleportation scroll

### ISSUE THREAD

**Issue by Zer0Spectr** [Wynncraft/Issues#7022]
I lost my black horse when I was teleporting to Rodoroc I didn't drop it I don't know what happened help me!!

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by Trixter313** [comment]
With what information you've gave us, and no other reports of horses randomly disappearing when using a scroll, all we can really do is assume that you accidentally dropped the horse.

I'd suggest changing your drop item key to something you're less likely to accidentally press to prevent it from happening again.

**Comment by DebugingLonks** [comment]
@Trixter313 I can tell you myself that this has happened before, both to me and to friends. Especially in the wynnter fair. Anyway, Im kind of confused, your horse is an entity, how do you loose a item...
