### ISSUE TITLE
a quest item dissapeared 

### ISSUE THREAD

**Issue by 0pu** [Wynncraft/Issues#7027]
I accidently dropped a quest item and it dissapeared and now I can't finnish the quest. The quest is called "in the shadow of the beast"

**Comment by LordHelmchen98** [comment]
Try /fixquests to get it back.

**Comment by Rellia** [comment]
You can't drop quest items. Is it the enchanted flower that you are talking about?

**Comment by 0pu** [comment]
I think the item is calle troll hair or something

**Comment by 0pu** [comment]
Öl

**Comment by 0pu** [comment]
It worked with /fixquests thank you
