### ISSUE TITLE
Beanstalk in "The Fortuneteller" fails to teleport player

### ISSUE THREAD

**Issue by Pickleonaraft** [Wynncraft/Issues#7028]
After climbing the beanstalk, the tripwire used to teleport the player causes you to glitch into a block. Additionally, the top section of the stalk stays in the sky after it vanishes. The quest currently cannot be completed. This bug has been tested by multiple people on multiple servers.

**Comment by Rellia** [comment]
What level quest is this?

**Comment by LordHelmchen98** [comment]
Most likely you missed a quest book update. Go to the bottom of the beanstalk and walk away from it along the path until your quest book updates. Then you can climb it again.

**Comment by Pickleonaraft** [comment]
My friend's book hasn't updated, but mine has updated to "Climb the beanstalk." I don't know what else I could do.

**Comment by LordHelmchen98** [comment]
What does your friends quest book say?

**Comment by Pickleonaraft** [comment]
His book is on the stage "Find the beanstalk." And mine is on "Climb the beanstalk."

**Comment by LordHelmchen98** [comment]
Hmm his book should be updated at the same place where yours updated. You should try if your friend can trigger a quest book update on another server.

**Comment by Pickleonaraft** [comment]
It works now for some reason. Thank for the help anyway!

**Comment by Numbermaniac** [comment]
Please click the close issue button if it has been resolved.
