### ISSUE TITLE
mage teleported into a hole in a wall and can't get out

### ISSUE THREAD

**Issue by dethmanme** [Wynncraft/Issues#7029]
My friend used the teleport spell, they are a mage, and teleported into a wall. The wall had a opened  space inside, so they cannot get out. They tried to use a teleport scroll, but the scroll did not work.

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!
