### ISSUE TITLE
Mummy Bandages Problem

### ISSUE THREAD

**Issue by OilyDoily** [Wynncraft/Issues#7032]
Im doing the ToL quest, when it asked for the Mummy Bandages, which I've tossed out! They aren't in my bank or in my mage class and I've tried doing /fixquests, but no luck. I would appreciate it massively if you could either give me another or tell me how to fix. Thank you in advance

**Comment by LordHelmchen98** [comment]
As it's a quest item it's untradeable so nobody else can just give one to you. Also Wynncraft enforces a strict norefund policy which means you won't get a Bandage from an admin or mod. Unfortunately the only way beside /fixquests is to create a new class just to get this bandage and then delete it again as you would have the same problem again if you continue to level the new class.

**Comment by ColinRioux** [comment]
To simplify what @LordHelmchen98 said, you would need to create another class, level it up to the Wrath of the Mummy quest, get the Mummy Bandages, and then transfer it to the other class using your bank. The only flaw to this solution is that this new class would be unable to complete the Temple of Legends quest (which is okay, as long as one of your characters can enter ToL).

**Comment by DebugingLonks** [comment]
@ColinRioux @LordHelmchen98 @OilyDoily The bandages can not be thrown out. The chestplate can be, but you do not need that. It looks like string i think, check your other classes (im not sure its string)

**Comment by LordHelmchen98** [comment]
@DebugingLonks I'm pretty sure it's a paper.
