### ISSUE TITLE
Relic Shrines will give you the item, but can't, if your inventory is full

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7033]
If you have a full inventory, then discover a relic shrine and claim it, the game will attempt to give you the item, but it can't because your inventory is full, so you will **never** get it. I found a Green Powder 4 Relic, but didn't get the Earth Powder because inventory was full, and touching it again does nothing. :(

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. Next time make sure you have an open slot. If you'd like you could  go back to the relic tje next day to get the powder again. (not really sure what time time has to be) however, thank you for reporting the bug.

**Comment by Numbermaniac** [comment]
Good to know. Will try going back and reclaiming it soon.
