### ISSUE TITLE
Lost my horse in Wynnter fair

### ISSUE THREAD

**Issue by ptdrmdr** [Wynncraft/Issues#7035]
I was playing the santa game in  the Wynnter fair, and the game bugged and i was stcuk in it without any fence coming out and i couldn,t leave, so i did /kill and i reapered in elkurn without my 22/20 chestnut horse..

**Comment by LordHelmchen98** [comment]
Wynncraft enforces a strict norefund policy. Therefore you won't get back any items.
Also is it possible you accidentally dropped it? However you should change your drop key to any key that can't be pressed accidentally.

**Comment by ptdrmdr** [comment]
there is no chance, i always have it in ym inventory unless i want to use it

**Comment by LordHelmchen98** [comment]
Hmm strange. Did it say anything in your chat? Normally it shouldn't be possible to loose a horse upon a death. Maybe something went horribly wrong and that plugin that should prevent you from losing your horse now deleted it. But I don't write plugins so I have no idea if that's plausible reason.

**Comment by Minimeep1** [comment]
I actually had the same issue, although I didn't die. I used a teleport scroll to get to Nemract and all of a sudden my brown horse was gone. I didn't drop it either, I know that because my friend was still in Detlas when I teleported and didn't see a saddle. (We acted fast too, so it didn't despawn)
No idea where that horse went.

**Comment by ColinRioux** [comment]
I'll tag Jumla, but you won't be getting your horse back due to the no-refund policy.

**Comment by DebugingLonks** [comment]
All ima say is:

22/20 Chesnut
explain pls

**Comment by LordHelmchen98** [comment]
@DebugingLonks Chestnuts are x/30 so in all likelihood it should be 22/30 and he pressed the wrong key.

**Comment by Moe-Ronickah** [comment]
Jumla will almost never see this, Ackro will.

**Comment by ptdrmdr** [comment]
i just misscliked the 30

**Comment by DebugMC** [comment]
Issue can be closed, wynnter fair is gone really. The builds are there, but no merchants+games
