### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Zeveriant** [Wynncraft/Issues#7038]
I am in a dungeon and whenever I log into the server I crash, I think it is because of world limit. If anyone knows how to solve this problem please tell me.

**Comment by ColinRioux** [comment]
Do you crash with the texture pack fully loaded or before it loads?
What version are you playing?
What's your internet download speed?

**Comment by ColinRioux** [comment]
Try playing on 1.8.9. 

I don't think that would resolve your issue, but worth a shot. Let me know.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
