### ISSUE TITLE
Key Merchant 

### ISSUE THREAD

**Issue by cheeselp** [Wynncraft/Issues#7039]
I have a little problem with the key merchant when i want to buy a key he means "I'm afraid you can not afford that" but actually I have enough money can you help me

**Comment by LordHelmchen98** [comment]
Does he ask for emeralds and you only have eb or the other way round? Unfortunately they can't convert EB to emeralds like Identifiers so you need to carry the correct amount of what he asks for.

**Comment by cheeselp** [comment]
I already tried that

**Comment by ColinRioux** [comment]
Which key merchant?

**Comment by DebugingLonks** [comment]
Sometimes you will  need 3 slots to get a item thats only 1 slot. Its thinkin about your eme+eme blocks+item. same happens if you have only 1 slot and try to turn eme to eb

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
