### ISSUE TITLE
i cant enter the cave in an iron heart part 1

### ISSUE THREAD

**Issue by endermage290r** [Wynncraft/Issues#7042]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

**Comment by ColinRioux** [comment]
Closing, please follow: https://forums.wynncraft.com/threads/guide-to-contributing-on-official-github-issue-tracker.170506/

When creating an issue. You're not specific enough for anyone to help you. Please also attach images.
