### ISSUE TITLE
Pant Glitch

### ISSUE THREAD

**Issue by AsrielPlayzMC** [Wynncraft/Issues#7044]
I just got a pair of "Priests Underwear" and it's in Italics and everything is messed up. 
![glitched pants](https://cloud.githubusercontent.com/assets/24847960/21574153/57fa5a32-ceab-11e6-8eb8-030874bf7ab2.png)

**Comment by ColinRioux** [comment]
@Imaxe

**Comment by DebugingLonks** [comment]
#7048

**Comment by Imaxe** [comment]
I do not see an issue with this, the yml is correct.
If you find this glitched item again, contact me.
