### ISSUE TITLE
Character stuck

### ISSUE THREAD

**Issue by aerrowkill** [Wynncraft/Issues#7045]
Hey so I was riding my horse by the bank in Almuj when I hopped off and found myself in a 3x3x3 cube of space. I can't get out of the hole and the coordinates are around 1025, -1964. if I could be teleported so like 1025, -1960 that would be great.

**Comment by JuicedBananas** [comment]
Just type /kill

**Comment by aerrowkill** [comment]
that's a command that works? awesome.
