### ISSUE TITLE
Unopenable Chest

### ISSUE THREAD

**Issue by Apocrophon** [Wynncraft/Issues#7046]
In the cave in Pirate cove (-673, -3193) there is a chest on the ceiling that cannot be opened.
![2016-12-30_16 59 06](https://cloud.githubusercontent.com/assets/24848664/21574953/566eeae6-ceb2-11e6-97bc-517bab40ad34.png)

**Comment by Apocrophon** [comment]
Tbh, I've know for a while but never got around to it, so sorry.

**Comment by LordHelmchen98** [comment]
@Imaxe Please fix this.

**Comment by Zeveriant** [comment]
The block above the chest, is that a full block? If so you probably won't be able to access it.

**Comment by Apocrophon** [comment]
Yeah, of course.
My point is that it's on the ceiling and likely wasn't supposed to.

**Comment by Imaxe** [comment]
I moved the chest! 
It will be online when we push!
Thanks for reporting
