### ISSUE TITLE
Stuck In Town Im Not Soposed To Be In

### ISSUE THREAD

**Issue by SCP35** [Wynncraft/Issues#7047]
So once upon a wynn, i was doing the " Finding The Light " quest and i was far away from  Cinfras so i said to myself " /kill to get back to the town quicker " and so i did /kill and it took me to Lexdale ( im lvl 71 and have no access to the town ) and when i want to leave the town, it pushs me back in the town when it should take you out the town, Current Coordinates are  -636 -5449, thats where im currently standing, if i could get teleported out ( Insert " That would be great " meme

**Comment by SCP35** [comment]
Edit: I used the Coordinates according to the Wynncraft map

**Comment by LordHelmchen98** [comment]
Are you trying to leave through an 'official' entrance or did you try to jump over a wall as well?

**Comment by ColinRioux** [comment]
You can't leave Lexdale through the entrance, try jumping over wall, as @LordHelmchen98 said. 

You should also take what happened as a learning experience. Many parts of quests are located off map, or under. Sometimes, these areas are located much further from the entrance. `/kill` is designed to take you to the nearest spawn point (town), which in most cases, isn't your desired town (unless you're in the main map). 

Another notable moments like this is doing `/kill` during one of the Gert quests, as it'll teleport you to the Caravan Driver.
