### ISSUE TITLE
I can not leave this area

### ISSUE THREAD

**Issue by OnoyaNiki** [Wynncraft/Issues#7049]
I can not leave this area and I can not use available Teleport Scroll. Help me please. by Niki_Huhu
![d898f33a-be5a-11e6-9dc4-2fd14a1ee3f8](https://cloud.githubusercontent.com/assets/24478424/21576787/17cf913c-cf70-11e6-83c8-2e0546196389.jpg)
![d1d2cd8c-be5a-11e6-9734-47fb840341bb](https://cloud.githubusercontent.com/assets/24478424/21576788/1cd8e46c-cf70-11e6-9227-fa276caa5ad3.jpg)

Please kill me.

**Comment by LordHelmchen98** [comment]
Duplicate of #6857. Please don't post about the same twice.
As Colin told you in your previous thread you can do /kill to get out. You won't loose anything but junk items. Hover over your soul points in your inventory for more information.
Also I created a conversation with you on the forums regarding the mod you are using. So yeah you might want to take a look at it.

**Comment by OnoyaNiki** [comment]
so sorry I'm not accustomed to this much program Department. Because I am foreigners

**Comment by OnoyaNiki** [comment]
I am Thai.

**Comment by OnoyaNiki** [comment]
Colin, Can you /kill me

**Comment by LordHelmchen98** [comment]
Just open your chat ingame and type /kill

**Comment by OnoyaNiki** [comment]
ok

**Comment by OnoyaNiki** [comment]
Thank you

**Comment by OnoyaNiki** [comment]
I can leave are.
