### ISSUE TITLE
Fierte ID glitch

### ISSUE THREAD

**Issue by zaxia12** [Wynncraft/Issues#7050]
After 2 years, i played Wynncraft again. I found everything including the updates to be fine and no bugs except my weapon for Warrior, Fierte, was completely broken. It did not give me the option to identify it or use it it just acted like any other normal item. The picture in these link, you'll see that the description looks completely different from any other weapon as I had it before the major update. Could you fix please

my Fierte decs: https://gyazo.com/804bf42056f003f94d6c768c472f2d8e
normal decs: https://gyazo.com/50f38543e81fd922def35dee9a43704c

**Comment by ColinRioux** [comment]
There are some weapons that were completely redone with the Gavel update. Fierte is one of them. 

In the most recent update, with the introduction of newer models, Fierte is no longer a shovel, but an orange stained clay block. As you can see, the difference between your Fierte and the Diablo is that the Diablo is now a clay block, meaning it's been updated, whereas your Fierte remains a shovel. 

Unfortunately, with the Gavel update, Wynncraft does not support converting old items. This plays along with the strict no-refund policy. 

Just note, that your Fierte isn't broken, it's just outdated. I'm sure you'll find a better weapon in the future anyways.
