### ISSUE TITLE
Hollow Sirene is completely broken

### ISSUE THREAD

**Issue by NinjaPiggy** [Wynncraft/Issues#7051]
So, in the quest Hollow Sirene, there is a point where you have to find an entrance to a scientist's grave. I found a grave where if you pressed the button, soulsand particles showed a path to a grave. When I stood on the grave, I got nausea, but nothing else happened. I looked at a video tutorial, and in the video the same thing happened, but afterwards a new trail appeared leading to the next part. So, that part is completely broken for me on all of the server I've tried.

**Comment by LordHelmchen98** [comment]
After following the particles you get to a grave with another button. Press it and you will see the new particles leading to another grave with a button and so on. If you can't find a button on the grave after following the particles you might be able to fix it by switching to another server.

**Comment by NinjaPiggy** [comment]
Oh, thanks. I didn't notice that.
