### ISSUE TITLE
Wrath of the mummy

### ISSUE THREAD

**Issue by aerrowkill** [Wynncraft/Issues#7052]
So I've hit a snag with a quest called Wrath of the mummy. It currently is telling me to walk to the bandit preventing me from entering but when I do it only repeats the one line about him wanting pink wool. there is no quest update or nothing. I tried to go get the wool but the hermit won't let me cross the bridge. any help would be great.

**Comment by ColinRioux** [comment]
https://wiki.wynncraft.com/index.php?title=Wrath_of_the_Mummy
