### ISSUE TITLE
texture pack broken

### ISSUE THREAD

**Issue by RoboKitty25** [Wynncraft/Issues#7053]
my game keeps telling me to set server resource packs to enabled so i do but the resource pack won't work

**Comment by ColinRioux** [comment]
You must edit the server on the multiplayer list, and set server resourcepacks to **prompt** not **enabled**. Then rejoin.
If that doesn't work, please comment with your version.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
