### ISSUE TITLE
Maiden Tower is missing commas between coordinates in quest book

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7058]
The coordinates normally have commas between them:
![2017-01-01_16 35 10](https://cloud.githubusercontent.com/assets/5206120/21580362/baee5d84-d043-11e6-8c93-b511a3b4ce16.png)

**Comment by Imaxe** [comment]
Issue fixed!
Will be online when we update, thanks for reporting the issue
