### ISSUE TITLE
Helmet for Light Realm

### ISSUE THREAD

**Issue by BioBioDeath** [Wynncraft/Issues#7059]
Hello,
I think this is known already but couldn't find it posted and also I need help with it personally but when accidentally throwing out quest items and picking up something else the quest item disappears and is impossible to get back. This happened to me after completing Finding the Light when I accidentally threw the helmet out for the light realm and I am curious if there is anyways I could get it back? My IGN is BioBioDeath as well and any other information needed I can supply as well

**Comment by thecoolkogut4** [comment]
if you type/fixquests you will get the helmet back.

**Comment by ColinRioux** [comment]
If that doesn't work, unfortunately there's not much more that you can do except, leveling up another class, and getting the item, and transferring it to your other class via your bank.
