### ISSUE TITLE
Horse not working right

### ISSUE THREAD

**Issue by deathlor12** [Wynncraft/Issues#7060]
I was just riding my horse in the light forest and then i logged off. Next time i went on, my horse was a donkey and it moved differently and would glitch more. Then it turned back into a horse but it still moves weird and glitches behind blocks so it's pretty much unusable now. Is there any way I could fix it?

**Comment by thecoolkogut4** [comment]
horses in Mc version 1.9 and up are broken/glitchy. If you want your horse to work I recommend you play in Mc version 1.8.

**Comment by deathlor12** [comment]
ok thank you
