### ISSUE TITLE
Spamming Seaskeeper

### ISSUE THREAD

**Issue by SlimeOre123** [Wynncraft/Issues#7061]
idk why 0-0 http://prntscr.com/dqcxob

**Comment by SlimeOre123** [comment]
all of my chat was spammed

**Comment by LordHelmchen98** [comment]
Please be more specific. Did you get teleported or were you stuck on the boat? Did the spam stop after a while?

**Comment by SlimeOre123** [comment]
that was like a normal sail but wiith a chat full of massages
