### ISSUE TITLE
I have a quest Item I can't get rid of

### ISSUE THREAD

**Issue by Minimeep1** [Wynncraft/Issues#7062]
I already used the item for the quest, corrupted shard, but for whatever reason, it's still in my inventory even though I finished CraftmasChaos. I've tried dropping it, dropping it into a cactus, into lava. I've tried dying with no soul points, but it won't get out of my inventory. Can someone remove it?

**Comment by Minimeep1** [comment]
Nvm, someone gave me a handy tip to use emeralds and get rid of it. No worries on this issue.

**Comment by LordHelmchen98** [comment]
If this is resolved just close it.
