### ISSUE TITLE
Item lost to server closes

### ISSUE THREAD

**Issue by nubtryhard** [Wynncraft/Issues#7063]
I accidentally dropped bobs mythic daggers on the ground, but when when i went to pick it up everything was frozen then i got kicked because of all the server shutdowns that have been happening today. Is there any way to get it back???
ign = BetAddict

**Comment by LordHelmchen98** [comment]
Sorry but Wynncraft has a strict norefund policy. Therefore you wont get the wand back. You can buy one from other players.
