### ISSUE TITLE
i lost items to server crash

### ISSUE THREAD

**Issue by Latroca519** [Wynncraft/Issues#7064]
i will try to be direct considering that English is not my native language
today (01/01/17) i entered wynncraft to organize my items and one of the things i wanted to do was upgrade my low level powders,i was upgrading all of them when suddenly the server crashed,when i came back i lost practically all my fire powders,i would be glad if someone could help me

**Comment by LordHelmchen98** [comment]
Sorry but Wynncraft enforces a strict norefund policy. Therefore you wont get back your powders.

**Comment by Latroca519** [comment]
ok,It seems I'm going to have to deal with this.thank you for answering anyway
