### ISSUE TITLE
Hompage|Store Bug|

### ISSUE THREAD

**Issue by Inflamenta** [Wynncraft/Issues#7065]
I can not buy more in the shop with my real account affairs in the shop as soon as I have to enter the playername and then go on to the next, goes directly back to the start.Wollte the guild actually make a joy but that has been done please help. Thank you Lg: Inflamena

**Comment by ColinRioux** [comment]
It seems that the in-game name you've been entering doesn't exists. See: [https://namemc.com/name/Inflamena%20](https://namemc.com/name/Inflamena%20) versus [https://namemc.com/name/Inflamenta%20](https://namemc.com/name/Inflamenta%20).

I suggest checking your **own** spelling before posting an issue. It seems your username is: **Inflementa** not **Inflemna**. You're missing a t. When I enter **Inflementa** as the username in the store, I get no problems.

**Comment by LordHelmchen98** [comment]
@ColinRioux I talked to him on TS and he explained it a little bit more precisely. He might have forgotten the t here but his username has the t in MC and here on GitHub and as he only created this GitHub account for this issue yesterday I assume he normally knows how to spell his name. He told me he tried to buy stuff with his alt and everything worked perfectly fine but when he switched back to his main he wasn't able to buy anything. Also after switching from his main to his alt and vice versa for many times I doubt he always entered the wrong name. However I suggested to clear his cache now. Lets see if that works.

**Comment by ColinRioux** [comment]
I would assume that clearing the cache could potentially fix it, but I'll keep it open in the mean time.

**Comment by LordHelmchen98** [comment]
Welp, just heard he has issue #6998 now :/

**Comment by Moe-Ronickah** [comment]
@Inflamenta ,  send an email to [support@wynncraft.com](support@wynncraft.com) . If you purchased VIP or VIP+ a long time ago, then your purchase went through a different buying system, and it may be messing you up.

**Comment by Moe-Ronickah** [comment]
Not a GitHub issue.
