### ISSUE TITLE
Lost Sanctuary: Garoth says "your" instead of "you"

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7067]
This is just before the boss battle, before you walk into the final dungeon area:
![2017-01-02_13 01 45](https://cloud.githubusercontent.com/assets/5206120/21584183/1c1e9048-d0f2-11e6-8b0d-db837a74a110.png)

**Comment by ColinRioux** [comment]
@Villageacules

**Comment by Villageacules** [comment]
Fixed, changes should appear in next patch/update.

**Comment by DebugingLonks** [comment]
gammer ftw
