### ISSUE TITLE
No Villagers

### ISSUE THREAD

**Issue by Apocrophon** [Wynncraft/Issues#7070]
The villagers that were in Pirate cove no longer spawn in.
This happened before the update, so idk what would cause it
![2](https://cloud.githubusercontent.com/assets/24848664/21584686/040e47de-d064-11e6-9ebf-1295194b5a4f.png)
![1](https://cloud.githubusercontent.com/assets/24848664/21584687/040e481a-d064-11e6-94a5-e2c2d664ff9a.png)

**Comment by Apocrophon** [comment]
The idle villagers spawn but the scroll merchant is gone as well...

**Comment by ColinRioux** [comment]
@AckroWynn

**Comment by Imaxe** [comment]
This issue is now fixed!
It will be online when we update.
Thanks for reporting the issue
