### ISSUE TITLE
Unbreaking pots

### ISSUE THREAD

**Issue by Apocrophon** [Wynncraft/Issues#7071]
I'm not sure why but in multiple cities, I've encountered multiple flower pots that will not break. They will not break no matter what. 
![Uploading 4.png…]()
![3](https://cloud.githubusercontent.com/assets/24848664/21584752/97f30bd8-d064-11e6-8a47-7254c6508765.png)

**Comment by Apocrophon** [comment]
![4](https://cloud.githubusercontent.com/assets/24848664/21584755/a0a52e64-d064-11e6-94b5-2f0007b00af8.png)

**Comment by ICHIGOunserscore** [comment]
they might just be there for looks

**Comment by Moe-Ronickah** [comment]
@Apocrophon , try hitting them with a different weapon.  That usually fixes the problem.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
