### ISSUE TITLE
Bug in the lion lair

### ISSUE THREAD

**Issue by HikonoMNK** [Wynncraft/Issues#7073]
Hello everyone, last night I was buggy inside the lion's lair. The bug is that they are stuck in the middle of the hole in a hole beside me there is a pumpkin and do not know how I used to teleport out of the magician but nothing please help me.
Hikono

**Comment by thecoolkogut4** [comment]
I think you said that you are stuck in a hole and can't get out? if so do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!
