### ISSUE TITLE
can't finish 1000 meters under because i lost the quest item due to bugs

### ISSUE THREAD

**Issue by TheActa2r179h** [Wynncraft/Issues#7074]
i was talking to the professor at the end of the quest, when the server lagged and kicked all of us out, and now i don't have the recepie and can't talk to the professor any longer.

**Comment by thecoolkogut4** [comment]
what happens when you type /fixquests? do you get it back?

**Comment by TheActa2r179h** [comment]
that worked, thanks for the help :)
