### ISSUE TITLE
I reached the to the start of the game in lvl 68

### ISSUE THREAD

**Issue by SlimeOre123** [Wynncraft/Issues#7076]
while doing the ToL quest, i was in maro peaks, i wore off my climbing helmet , and it teleported me to the start of the game http://prntscr.com/dqmgxl :P

**Comment by Moe-Ronickah** [comment]
It's never a good idea to remove any helmet or any other item that is required for you to complete a quest, while in the quest.  This is not an issue, it is an effect of the fact that we are using an MC map.
