### ISSUE TITLE
Permission in Area bug.

### ISSUE THREAD

**Issue by RogueHatter** [Wynncraft/Issues#7077]
Today I started The Worm Holes quest and I haven't been able to complete it. When I go to the end of the east cave to press the button I need to press to continue the quest it says, "You don't have permission for this area," in bold, red text. The same thing happened yesterday when I tried opening loot chests on my journey and it said the same thing. I've relogged several times and it still says, "You don't have permission for this area," in bold, red text. I have no idea what is going on but can someone help me fix this problem?

**Comment by dyredhead** [comment]
you are probably using a weapon that is a block. as you probably know the game is mostly based on the texture packs, such as a weapon could be a wooden slab, sandstone block, ETC. so the game thinks you are trying to place a block and that is not allowed. the simplest solution is to use an empty hand hope this helps.

**Comment by RogueHatter** [comment]
(I'm suck an idiot) Thank you, I forgot about the texture pack and now my problem is fixed!
