### ISSUE TITLE
Guild Attack broken, have waited 12 hours, no change. 

### ISSUE THREAD

**Issue by BioBioDeath** [Wynncraft/Issues#7078]
After losing in a guild battle, i now can't /guild attack as it says that a war is already happening.

**Comment by LordHelmchen98** [comment]
This should not be a problem because it should work again after a minute or two.

**Comment by BioBioDeath** [comment]
Well it's been 12 hours almost so I'm not sure why it is still like this

**Comment by LordHelmchen98** [comment]
Hmm strange which territory did you attack?

**Comment by BioBioDeath** [comment]
Zhight

**Comment by LordHelmchen98** [comment]
Weird it tells me that the territory is already in a battle. No idea what happened there.

**Comment by BioBioDeath** [comment]
hmm, i just found a post on the forums about guild problems and a moderator said they were broken atm

**Comment by LordHelmchen98** [comment]
Yeah guilds are pretty broken but I have never heard of an issue like this before.

**Comment by BioBioDeath** [comment]
I'm assuming all guilds are having this problem then

**Comment by thecoolkogut4** [comment]
has been happening for a long time, after ~2days this gets fixed.
