### ISSUE TITLE
Health Won't Regen

### ISSUE THREAD

**Issue by Minimeep1** [Wynncraft/Issues#7080]
I've tried joining different servers and suiciding, but my health won't regen if I take damage. I don't have any potion effects on me and I'm just super confused. I checked my items and nothing has negative health regeneration effects on it.
I'm literally gaining 1 hp ever 30 seconds and I have over 1.5k health... So it's taking forever.

**Comment by Minimeep1** [comment]
Alright, now my health is worse, I'm slowly losing health over time. I'm not poisoned, I'm just sitting in the bank...

**Comment by Minimeep1** [comment]
Alright, I'm losing a lot of soul points..  This is annoying, I'm not risking my legendaries until this gets fixed. I'm already spending a lot on health pots to be sure I don't die.

**Comment by DeleteTheFox** [comment]
If you have negative health regen it goes down ( i had a weapon that did that) if your hp is increasing slowly it's because it's probaly almost 0 hp regeneration, go to your stats and see how many hp regeneration you have, take a screenshot.

**Comment by Minimeep1** [comment]
https://gyazo.com/98166a620fc73d347966bc0dde678025

There isn't anything with health regen that goes down

**Comment by Minimeep1** [comment]
https://gyazo.com/45ad65c518fb449221b1ff29ce9dffa7

And this is the bow I'm using

**Comment by DebugingLonks** [comment]
Same here. If you'r a archer get the bow Cornacopia. and quick! its in the wynnter fair lvl 75 with +100% health regen and +100 health regen quite broken but get it while you can xD

**Comment by Moe-Ronickah** [comment]
@Minimeep1 , sometimes, thing in the compass don't work right.  If you still have this problem going on, I'd like to see the stats from each piece of armor and each accessory that you have on.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
