### ISSUE TITLE
Wand relic

### ISSUE THREAD

**Issue by Strouky** [Wynncraft/Issues#7082]
i've whent to the place that had the wand relic and click on the crystal but got nothing.
![2017-01-02_23 38 23](https://cloud.githubusercontent.com/assets/24886677/21600175/2c765d5a-d146-11e6-8bc5-f6a97bbdfecd.png)

look the chat its writen:
you have found a new relic [8/30]
you broke the Wand Relic's seal!
[+1 sealed Letter (4/10)]
and I just have the letter

**Comment by LordHelmchen98** [comment]
Sometimes you get those letters but if so you will never get anything else. Just go to the relic again after a few hours and get it again.

**Comment by Moe-Ronickah** [comment]
At one time, those sealed letters were worth a heck of a lot of LE.  Now that they have all been found and deciphered, they aren't worth as much, but you can probably find someone who still collects them.
