### ISSUE TITLE
I'm stuck in a cutscene in the quest, "A Grave Mistake". 

### ISSUE THREAD

**Issue by DushiSushi** [Wynncraft/Issues#7084]
So after going to all the places and getting through all the cutscenes, I reached the final cutscenes. However, my game crashed and when I logged back in, I was still stuck in a cutscene. It stays like that too. I can't use a teleport scroll + I can see a huge opening with command blocks. Please help! Thanks!

**Comment by LordHelmchen98** [comment]
You could do /kill to get out and try if it works if you go through the specific part again.
