### ISSUE TITLE
Off hand... (duel wielding hand from 1.9)

### ISSUE THREAD

**Issue by DragonHunter1202** [Wynncraft/Issues#7085]
I tried to put my wand "Diablo" in my off hand & it got deleted :'(

**Comment by DragonHunter1202** [comment]
Any chance I can get it back?

**Comment by LordHelmchen98** [comment]
Unfortunately Wynncraft enforces a strict norefund policy. Therefore you wont get your Diablo back. However Wynncraft is running on 1.8.9. You can still join Wynn with 1.9 but it has none of the 1.9 features so you shouldnt try to do anything that only works in 1.9+ but doesnt work in 1.8.

**Comment by DragonHunter1202** [comment]
:(
