### ISSUE TITLE
I lost some of my quest items

### ISSUE THREAD

**Issue by Adallx** [Wynncraft/Issues#7086]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.
I went to pick up loot and dropped a quest item by mistake, I have done this with the helmet from "An iron heart part 1" and the crystal from "Wynnexcavation B", and when it went to put the quest item back into my inventory it disappeared due to no space being in my inventory. Please help I can't continue these quests without the quest items.

**Comment by ColinRioux** [comment]
Use `/fixquests`, with free space in your inventory. If that doesn't work, unfortunately, you'll be forced to level up another class to retain those quest items.
