### ISSUE TITLE
A few issues in a post

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7088]
Eh decided to post all bugs ik at once :P 

First: Naming pets/horses with a apostrophe breaks it (Ex: name it Debug's Test)
Second: Pets block arrow bomb and a few other spells ive heard
Third: You 100% regen health on switching servers
Fourth: You can have a glitched trade (If needed I can show how, can't rly describe here) via doing /trade (not clicking) and the other player shift clicking while holding a book then clicking the done on gui will cause 1 player to be stuck in gui (unless they hit esc)
Fifth: In ??? (and possibly other quests) if 2 people stand on the same pressure plate in a meteor, then two people go to the other meteors, only 1 person in each meteor gets teleported (doesn't sound important but it is VERY annoying)
Sixth: The wheat puzzle in ??? doesn't work sometimes unless you jump while sneaking (IDEK)

rip ik thats a lot for 1 issue, if needed msg me ingame (DebugMC) and I can show you each (EXEPT NOT THE ??? stuff.. not doing that again)

**Comment by ColinRioux** [comment]
I think you mean apostrophe, not comma.

**Comment by DebugingLonks** [comment]
Yeah, i´ve now fixed that :P

**Comment by LordHelmchen98** [comment]
I heard you shouldnt post multiple issues in one thread.
However:

1. Agreed you will get `\u0027` for every ' in the name.
2. Agreed.
3. This doesnt hapen for me I have the same amount of health after switching servers.
4. Dont know about that.
5. Yeah its annoying but so far I though its meant to work like that.
6. This never really happened to me.

**Comment by Moe-Ronickah** [comment]
**# I heard you shouldnt post multiple issues in one thread.**

**Comment by DebugMC** [comment]
Same, so i have now closed issue. AscendedKittens told me so.
