### ISSUE TITLE
Water Bottle Merchant dissapeared!

### ISSUE THREAD

**Issue by Crazybear1233** [Wynncraft/Issues#7089]
I am doing the quest for the tiny fishermen and he needs 3 pigmen's meat and 1 water bottle...but when i saw on youtube how to get the water bottle ( because i didn't know how ) and there was a water bottle merchant in the video but i couldn't find him anywhere in Ragni...Any suggestions how to get water bottles?

**Comment by DebugingLonks** [comment]
Pretty sure he was removed. Not 100% on this though! Anyway, kill some lvl 1 mobs they usualy drop them.

**Comment by Scorpioxzz** [comment]
I'm pretty sure they changed the water bottle to a milk bucket, that's what I needed to get for that quest

**Comment by Crazybear1233** [comment]
but where do you get the milk bucket? :/

**Comment by DebugingLonks** [comment]
Koata ranch or watever. I think.
