### ISSUE TITLE
Poison, Thorns, and Reflection can take SP in fights (Duels and nether)

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7090]
Before you all tag me for having a duplicate of the issue with soul points in duels, this report is different (even tho it includes that)

Like the old issue, you can get SP taken away in duels, but here is the thing: I Don't have reflection. Nor thorns. The culprit here is POISON. Sometimes (not common I mean this has only happened a few times for me, and I lived the poison anyway) after the duel the poison won't stop. If a higher level player with high poison duels a low lvl, there is a chance the low lvl will actually die. But here is a super easy way to test this fact, go to the nether with a poison build. Lets say you are using the poison build _Leg has (I DO NOT KNOW THE POISON) it will kill my lvl 81 3 times after the first hit. Meaning after a death poison is not canceled. Also in duels all the time you can end a duel with like... five health. Your HP does not always regen after a duel. (Btw I have tested all of this on my alt).

**Edit 1/31/17**: In the nether, if a player has a really high poison they can kill you multiple times in 1 hit. (I have 5k hp on my mage, my friend _Leg will kill me, kill me again, then half my health. Thats 1 hit for 3 kills, this seems kind of broken - Colin

**Comment by DebugingLonks** [comment]
I can't tag it for some reason. Issue number is 3559 If i type it nothing happens lol

**Comment by LordHelmchen98** [comment]
You can still tag it :)
#3559

**Comment by thecoolkogut4** [comment]
your HP does not regen after a duel because of a bug that occurred last year.

**Comment by DebugMC** [comment]
What was the bug ._.

**Comment by DebugMC** [comment]
Edited so that I include all ways ids can kill you :I

**Comment by thecoolkogut4** [comment]
not 100% sure but you shouldent list a bunch of issues on this one issue. you should make a new issue per issue so it gets noticed. eg: poison making mobs drop x2 loot is not at all related to being killed and losing sp in a duel. (besides that poison is involved in both)

**Comment by DebugMC** [comment]
@thecoolkogut4 fixed

**Comment by DebugMC** [comment]
Fixed that  now :D

**Comment by Moe-Ronickah** [comment]
"Sometimes (not common I mean this has only happened a few times for me, and I lived the poison anyway) after the duel the poison won't stop."
If you can find a pattern, in either what you are wearing, or what you are being hit by, that would really help.  Otherwise, this one is going to be one of those that just sits, because, unless we know what it is that is broken, we can't fix it.

**Comment by Moe-Ronickah** [comment]
Refer to #3559 - game mechanics in duels.
