### ISSUE TITLE
Le disappeared

### ISSUE THREAD

**Issue by SaltyPotatoFart** [Wynncraft/Issues#7091]
So I was in a server when there was a lot of item bombs I sold a lot and got up to 64 emerald blocks me and my friends were in the same server and I went to le merchant got the Le then me being the idiot that I am  I right clicked it then it disappeared I got panicked I am very aware that Wynn has a very strict policy but I am hoping you can maybe look into this please.

**Comment by DebugingLonks** [comment]
They can always look into it, but you will NOT get a refund even if they know how.
