### ISSUE TITLE
Wynncraft Map Wont Show

### ISSUE THREAD

**Issue by SupremeOtashi** [Wynncraft/Issues#7092]
When I try to open the Wynncraft map it just says: If you can see this message, there is likely a problem loading the Overviewer javascript components. Check the javascript console for error messages.

And the rest is black.

Please help me to fix this issue. Thx! :)

**Comment by DebugingLonks** [comment]
Make sure java is updated, if it consists switch browsers. For a really detailed explanation do as it says and inspect element (right click)

**Comment by LordHelmchen98** [comment]
If you are using Chrome you could try to do Ctrl+F5 in order to clear your cache.

**Comment by Numbermaniac** [comment]
@DebugingLonks this is the online map, it uses JavaScript, not Java :)

If the other's steps didn't work, you may have an ad blocker or other plugin in your browser that's blocking it; if not, hit F12 (Windows) or Option-Command-J (Mac) and switch to the Console tab, and tell us what it says.

**Comment by ColinRioux** [comment]
If the above doesn't work, can you please confirm which browser you are using, and if you can view it on another browser. Trusted browsers are: 
Chrome
Firefox
Safari
IE 

I'm not saying you need to use one of these permanently if it works on a different one of them, I'm trying to deduce which browser. 

Some are assuming you are using chrome, but not everyone uses chrome.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.

**Comment by DebugMC** [comment]
@Moe-Ronickah issue is still alive for people (not for me but people have told me recently)
