### ISSUE TITLE
My Class was deleted and i have done nothing!

### ISSUE THREAD

**Issue by Agrozocker234** [Wynncraft/Issues#7096]
Hello,
Yesterday i played Wynncraft... all was normaly. Now I go in wynncraft. I want play but my class is delted. I don´t know why. Can you help me pls?

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by teuntheman** [comment]
I had this too and it was my best class

**Comment by DebugingLonks** [comment]
@thecoolkogut4 @teuntheman @Agrozocker234 more than likely he deleted your class on acident via right click. I have had  **TWO** of my lvl 100's deleted. ik the pain

**Comment by Moe-Ronickah** [comment]
If you have lost a class, and haven't fallen for a scam, then please read this post, here, about what may have happened to you.

[Unintentional Deletion of a Class](https://forums.wynncraft.com/threads/unintentional-deletion-of-a-class.138254/)

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
