### ISSUE TITLE
Wynnexcavation site D

### ISSUE THREAD

**Issue by Mafiamaestro** [Wynncraft/Issues#7098]
The YellowPuzzle isn't working, The lamps won't turn on in ANY lobby. Pls help :(

**Comment by LordHelmchen98** [comment]
The order is:
1. red, blue, green
2. yellow, red, blue, green, red
3. green, yellow, red, blue, yellow, blue, red

**Comment by Mafiamaestro** [comment]
I know, it doesn't work.

**Comment by LordHelmchen98** [comment]
Strange It worked for me a few days ago. I'll try that later.

**Comment by Mafiamaestro** [comment]
And?

**Comment by LordHelmchen98** [comment]
Oh sorry forgot about it :/
However I just did it without problems all lamps were working correctly.

**Comment by Moe-Ronickah** [comment]
@Mafiamaestro , if you ever run into a situation where something just doesn't work, try changing servers, first.  If that doesn't help, then log out, close MC, wait a few minutes, then try again.
Good luck, and Happy Wynning.
