### ISSUE TITLE
Wynncraft Excavation Site A Problem

### ISSUE THREAD

**Issue by IzLit** [Wynncraft/Issues#7099]
After running through the whole tomb and into the portal behind the Pharoah, my quest book updated and gave me my next instruction ; "Return and talk to Excavator Vade."

When I speak to Vade he tells me to go and speak to Tesha in the tent up on the hill, and when I speak to Tesha she tells me to speak to Vade. The process continues to cycle and I have not been able to resolve it by going through the tombs again. 

Both me and my friend b301 are experiencing the issue, please fix it as soon as possible.

**Comment by thecoolkogut4** [comment]
do you have the translation that Vade gave you at the start?

**Comment by teuntheman** [comment]
You need to kill the pharao because I had this problem too an someone sad it

**Comment by DebugingLonks** [comment]
I just did quest last night with my mage, no problem for me.

**Comment by IzLit** [comment]
@thecoolkogut4 No, I do not have the translation as I am pretty sure that the item was taken from me at some point during completion of the quest.

**Comment by IzLit** [comment]
@DebugingLonks Ok, thanks, I will try this to see if this will work.

**Comment by IzLit** [comment]
@DebugingLonks Thanks for letting me know.

**Comment by LordHelmchen98** [comment]
@IzLit The pharaoh drops a yellow crystal. Do you have that with you when you try to talk to Vade?

**Comment by Moe-Ronickah** [comment]
LordHelmchen98's question is the most likely question and answer to this issue.  You can leave the area, not kill the pharaoh, and not have the yellow crystal.  The yellow crystal is the trigger for Vade for the next step in the quest.
