### ISSUE TITLE
error contacting login servers

### ISSUE THREAD

**Issue by flywings512a** [Wynncraft/Issues#7102]
Why cant i join the server i try the restart the computer and use 1.9 , but it not working
![1](https://cloud.githubusercontent.com/assets/24930284/21669923/dd7b9efc-d34a-11e6-8018-1fdf06c4b5cf.jpg)

**Comment by redxdev** [comment]
Currently in the process of fixing this, keep trying to connect if you are having issues.

**Comment by redxdev** [comment]
This should be fixed as of about 1 minute ago.
