### ISSUE TITLE
Not Able To Leave Guild

### ISSUE THREAD

**Issue by LaraMeeps** [Wynncraft/Issues#7103]
I can't insert the video proof here since it's bigger than 10MB :/
https://www.youtube.com/watch?v=Qsitdf1nVn0&feature=youtu.be
That's the video that it won't let me add here.

I'm unable to leave my guild. I've tried 3 times and all 3 times it says I've left but I'm still in it... I've given it time, relogged, and repeated the process. Each time it's the same.

**Comment by DebugingLonks** [comment]
Guilds and such are broken, please don't post duplicates. 
#4099 
#3665
This is a known bug, sorry.
