### ISSUE TITLE
Trapped at the Detlas ball after restart

### ISSUE THREAD

**Issue by MrGragert** [Wynncraft/Issues#7105]
Ok, so I got back into wynncraft a few days ago and started doing the "Meaningful Holiday" quest. Every thing was going according to plan, until Nick started giving his speech at the ball. During the speech the server restarted and now I am stuck in a box made out of barriers and Nick isn't continuing his speech. I also can't seem to use any scrolls, so I'm unable to do anything about it on my own.

Is there a way to get out of this sticky situation?

**Comment by MrGragert** [comment]
Never mind, I did /kill and i'm out lol

**Comment by fralix** [comment]
Could someone please reopen that
even if MrGragert found a workaround, this bug is still present!
