### ISSUE TITLE
elemental exercise quest problem

### ISSUE THREAD

**Issue by firedreadlord** [Wynncraft/Issues#7106]
In stage 3 I reach the end of the cave but the cave didn't collapse and there's no dialogue. I try to do /fixquests but it just gave me one more study results. Then I re-login the game and finish the quest. But now I get an extra study results and I can't throw it away as it is quest item. What should I do?

**Comment by firedreadlord** [comment]
Ok thx

**Comment by LordHelmchen98** [comment]
Another simple option is to put it into your daily reward chest.

**Comment by Moe-Ronickah** [comment]
RESOLVED
