### ISSUE TITLE
elemental defence in compass glitched

### ISSUE THREAD

**Issue by michielman2** [Wynncraft/Issues#7108]
this might not be a glitch but that i dont understand something.

today i noticed that my elemental defence is a bit weird
it sais i have 
-130 fire defence
-210 air defence
-180 earth defence
-140 thunder
-50 water

but my actual defences on my armour weapon and ascesoires are
-86 fire +23%
-52 air +12%
+27 earth +22%
-125 thunder +20%
+130 water  +16%

if you need extra information on my armour you can contact me ingame my username is michielman2
i hope it gets fixed if its a bug and mostly the earth and water wich should be positive but arent

**Comment by thecoolkogut4** [comment]
your weapon doesint get counted into the compass, if you add that in would it fix it?

**Comment by LordHelmchen98** [comment]
Unless it wasn't fixed the defense stats in the compass are bugged. I heard some players saying it works correct for them but my compass never really worked properly. I'm pretty sure that was confirmed by a moderator so don't trust the defense stats in your compass (other stats like skill points or xp bonus,... are correct).

**Comment by Moe-Ronickah** [comment]
There are some bugs in the compass calculations, so, don't worry about the discrepancy, is just a visual error and not a calculation error.
