### ISSUE TITLE
I clicked on shout in /use, it consumed it, but didn't prompt me to shout

### ISSUE THREAD

**Issue by ghost** [Wynncraft/Issues#7109]
Title basically says it. I clicked on it, it removed me from the /use window as it normally would, but didn't tell me in chat what it normally does. Went back into /use and it consumed a charge. Tried again in case it was lag or something and same thing. A relog fixed the issue. But now im missing 2 shouts. :x

**Comment by LordHelmchen98** [comment]
For issues related to real world currency contact support@wynncraft.com.
Here on GitHub nobody can help you with that.

**Comment by Symfynx** [comment]
I just assumed it was a bug so I reported it.

**Comment by LordHelmchen98** [comment]
Yeah it sounds like a bug but apparently it was a one time thing that may or may not be able to recreate. However to get your shouts back you need to send an email.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
