### ISSUE TITLE
CURSE MISSSING!!! HELP PLS I WANT TO PLAY!!!!

### ISSUE THREAD

**Issue by Capivarazord** [Wynncraft/Issues#7112]
HEY GUYS, MY PROBLEM IS A FUCKING BORING THING, IN MY SCREEN THERE'S A RED MESSAGE THAT NOT GO AWAY, I ALREDY REINSTALL THE MODPACK, THE CURSE, MINECRAFT AND EVERYTHING YOU CAN IMAGINE, HELP ME PLEASE, I WANNA PLAY THIS GAME

http://imgur.com/a/Yn7Ix

**Comment by Trixter313** [comment]
Are you using a different launcher than the default official Minecraft one? Wynncraft doesn't need a mod pack or any mods at all to play so just using vanilla Minecraft with the default launcher should work fine.

**Comment by Imaxe** [comment]
@Capivarazord You don't need a modpack to play Wynncraft. That is just an add-on not created by the Wynncraft team, we are not able to help you with that.
Sorry! Just use the regular launcher and enjoy your stay at Wynncraft!

**Comment by LordHelmchen98** [comment]
As explained above the normal Wynncraft doesn't need a modpack or another launcher. If you still want to use Wynncraft enhanced post on the modpack thread on the forums because nobody here is able to help you as it is a fanmade modpack and not official.
