### ISSUE TITLE
Potion Making Quest

### ISSUE THREAD

**Issue by Audei** [Wynncraft/Issues#7113]
The Potion Making Quest is broken for me. Essren doesn't spawn, and the assistant still wants red mushrooms even though I've given him mushrooms.
![2017-01-05_19 50 33](https://cloud.githubusercontent.com/assets/17649334/21707085/127ef686-d381-11e6-92c7-d74d125aaedb.png)

**Comment by thecoolkogut4** [comment]
what does your quest book say?

**Comment by Audei** [comment]
Oh, it's fixed now, I just had to shoot the tripwire for some reason..?

**Comment by Audei** [comment]
(It said Bring back Essren's dusty coat)
