### ISSUE TITLE
Zhight Island quest: Tirt is missing a full stop in one message

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7115]
![2017-01-06_16 00 24](https://cloud.githubusercontent.com/assets/5206120/21709950/51f5ebae-d439-11e6-8267-336ffdedc31a.png)

Message 6/9.

**Comment by DeleteTheFox** [comment]
But message 6/9 is there

**Comment by thecoolkogut4** [comment]
@Villageacules line 6 is missing a .

**Comment by Imaxe** [comment]
Issue fixed! 
This will be online when we update.
Thanks for reporting this issue!
