### ISSUE TITLE
Can't leave my guild

### ISSUE THREAD

**Issue by Yroki** [Wynncraft/Issues#7117]
I can't leave my guild when I do /guild leave, then I enter "yes" in the sign, I lost my soulpoint but nothing else happen.
Can I Get some help for leave my guild please...

username: Yroki

**Comment by ColinRioux** [comment]
Duplicate of #3665. There's nothing that we can do to fix. You must wait until guilds are updated. (No one knows when that will be).

Next time, please search for other issues like yours.
