### ISSUE TITLE
Orc Skin Forums Page

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#7119]
So I was reading the Orc Skin and came over a typo. For some reason it's been written "Qonquerers" instead of "Conquerors" in the sidebar. Here's a link
https://wiki.wynncraft.com/index.php?title=Orc_Skin

- Annoying

**Comment by ColinRioux** [comment]
Hi, 
The wiki is a community project, and although the domain is wiki.wynncraft.com, it's not run by Wynncraft itself. Also, wiki complaints should go directly to the wiki administrators, who are listed in the site notice at the top of the wiki, not as a bug report (a wiki mistake, **isn't an in-game bug**).
