### ISSUE TITLE
Weird Glitch on Cowfusion

### ISSUE THREAD

**Issue by BioBioDeath** [Wynncraft/Issues#7120]
Hello, in the quest Cowfusion towards the end after you kill Veekhat, you give the key he drops to the dropper which is more of an NPC as you have to click it rather than throw it in. I did this and then another Veekhat spawned and killed me instantly. I then respawned in Lexdale and with what I am assuming is the next part needed in the quest, Veekhat's head. I checked the book which told me to go through the portal that must have opened moments before I died. I tried to return to this point so I could re-kill him and go through the portal but now I can not get past the cut scene where he becomes the Minotaur as leaves me in the box that I can't escape that I am supposed to be watching him from even though nothing is happening. Of course I can do /kill to escape but I still can't finish the quest either.
Thank you,
BioBioDeath

**Comment by thecoolkogut4** [comment]
do  you get stuck in the cut scene on every world or just the one? have you tried to /kill and try again on a new server?

**Comment by forrester-marc** [comment]
You can usually escape a cutscene box by backing into a corner and using /class.  It depends on exactly where the quest puts the invisible walls.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
