### ISSUE TITLE
Enter the Dojo broken ?!?

### ISSUE THREAD

**Issue by Fryelt** [Wynncraft/Issues#7121]
So the recent patch for the double xp week-end broke the 'Harvest Sugar' button on the tea ingredient harvesting stage : Pressing the button won't do anything, even tho it's supposed to give you sugar, even after trying going to different servers.
![2017-01-07_01 17 41](https://cloud.githubusercontent.com/assets/22244213/21739954/c65e0e02-d477-11e6-82a6-c56a8c8dae42.png)
![2017-01-07_01 17 44](https://cloud.githubusercontent.com/assets/22244213/21739955/c8a9e9e2-d477-11e6-9690-e8a7a17f2177.png)
![2017-01-07_01 17 45](https://cloud.githubusercontent.com/assets/22244213/21739957/cb4cf3a6-d477-11e6-9a6b-5965b02bd3fb.png)

**Comment by BioBioDeath** [comment]
I just ran into this problem as well

**Comment by LordHelmchen98** [comment]
@Villageacules I assume you are able to fix this and I hope its ok if I tag you.

**Comment by Villageacules** [comment]
I'll look into it on build.

**Comment by Villageacules** [comment]
Make sure you press the button in a low angle, the armorstand that has the "harvest sugar" name might be blocking you if you're hitting the button at a low angle.

**Comment by DohdoEXE** [comment]
What if you try pressing f3 + b, and hit where the armor stands hitbox doesn't interfere

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
