### ISSUE TITLE
Exploding not working?

### ISSUE THREAD

**Issue by GammingLizard** [Wynncraft/Issues#7123]
I've got 60% exploding on my Virgo and 50% exploding on my weapon, Ignition. My exploding chance isn't factoring in the buff from my weapon and it is only giving me a 60% chance.

**Comment by thecoolkogut4** [comment]
are you reading the 60% from your compass? if so then is incorrect. when you select your compass you do not have the buffs from your weapon, so when it shows the stats it takes out the stats of your weapon. let me explain that again, you only get the buff of a weapon WHEN you are holding it. when you hold your compass you arent holding the weapon so your not getting the buffs and your compass doesint factor in your weapon stats. I hope you understand what im trying to say, if i didint answer your question please let me know.

**Comment by GammingLizard** [comment]
I understand how the weapon buff works. It's just that it isn't acting as a 100% exploding buff, it seems to be working every 2/3 time I hit a mob.

**Comment by thecoolkogut4** [comment]
oh, not too sure then. It might be a 100% chance of activating out of 125. (100% might not mean it activates 100% of the time) thats the only thing i can think of

**Comment by GammingLizard** [comment]
Huh, ok thanks for hearing my issue. :)

**Comment by LordHelmchen98** [comment]
Exploding activates if you kill a mob not if you hit a mob. With 100% every dying mob should explode.

**Comment by DebugingLonks** [comment]
Exploding chances are broken really. There is a level 27 Legendary spear 'legendary smasher' that can have up to 40. on 8/10 kills it explodes, and my bow with +8% explodes like 6/10 so pretty sure explosion % is wrong.

**Comment by Moe-Ronickah** [comment]
RESOLVED
