### ISSUE TITLE
It is still possible to get Wynnter fair presents...

### ISSUE THREAD

**Issue by ttykox59** [Wynncraft/Issues#7124]
Even the the gate to the parkour section of the Wynnter fair was destroyed, it is still possible to go through its portal and complete the parkour, when you do, you will get the two presents that it would give as a reward (before getting stuck and having to use /kill). Probably doesn't matter because the merchants are gone though but idk, i'm just reporting a bug

**Comment by DohdoEXE** [comment]
It's not a bug, they just hadn't updated the map to get rid of the wynnter fair.

**Comment by DebugingLonks** [comment]
@ColinRioux please close this, I checked last night this has been fixed. Also you didn't have to /kill @ttykox59 the exit portal still works

**Comment by ttykox59** [comment]
The exit portal works, but after that, but the  "real" exit is blocked off
