### ISSUE TITLE
No quest reward

### ISSUE THREAD

**Issue by napster1** [Wynncraft/Issues#7127]
Hey,
My username is Napster1

I just did the quest: An iron heart part II
I did the quest until i got the leggings that u can take or bring back. but i had to go at that moment, so i logged off.

When i logged back in later today i still had the leggings but my quest was finished... But i didn't got to bring the leggings back nor did i got  **any rewards** (no emeralds, no 160000 xp and also no Greaves of Honor/ Shameful Greaves)

So i don't really care that i still have the leggings and couldn't bring them back. but i do want my rewards!

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug. Is it just this one quest that your not getting the reward for?

**Comment by napster1** [comment]
yes, but i think the problem lays on getting no rewards when being offline and finishing the quest. because i had to talk to a npc but i didn't do that, when i logged back in that day it said i completed the quest so i finished it when i was offline... so thats the bug (getting no rewards when finished a quest offline)

**Comment by napster1** [comment]
you also cant just give me the xp? i dont care about the other rewards

**Comment by thecoolkogut4** [comment]
oh, you logged out after your clicked the final npc?  just all you needed to do was reclick him when you logged back in. (and if you had any items you needed to give, you would need to get them back)

**Comment by DohdoEXE** [comment]
The real question is, why did you right click him and then log off right away?

**Comment by DebugingLonks** [comment]
Another bug relating to this is starting a quest and instantly logging out (or switching WC), this causes it not to start. (I did this because I didn't want to start a certain quest as it is currently not working right)

**Comment by napster1** [comment]
DohdoEXE did i read what i said?

**Comment by Moe-Ronickah** [comment]
@napster1 , please read the Wiki on [this quest](https://wiki.wynncraft.com/index.php?title=An_Iron_Heart_Part_II).  You said that you took the leggings.  Go identify them, they should be the Shameful Grieves.  If you took the leggings, you ended the quest, right there.

**Comment by napster1** [comment]
DUDE listen u did not read it the good way i said, I DONT GIVE A DAMM about those leggins i just want my  reward (a.k.a emeralds, experience?)

**Comment by LordHelmchen98** [comment]
As @thecoolkogut4 said Wynncraft enforces a strict norefund policy and that's why you won't get the emeralds and xp. This may seem unfair but actually this policy helps to keep up the fairness among all players.

**Comment by forrester-marc** [comment]
Read Moe-Ronickah's comment, this quest has two optional hand-in points.  You already have your XP and emeralds.  Also you are now an evil co-conspirator of the golem factory horror.  You monster.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
