### ISSUE TITLE
Missing Boat Merchants

### ISSUE THREAD

**Issue by zqck** [Wynncraft/Issues#7129]
Alright, so I noticed that all of the Boat Merchants have disappeared. I was trying to buy a boat in the Nodguj Nation because the server restarted without any warning while I was in my boat, so when I got back on, it was gone. There was no Boat Merchant there. Then I swam to the tree below it. http://prntscr.com/dsq72p No Boat Merchant there as well. http://prntscr.com/dsq7i6
Any help? I'm really trying to finish this quest...

EDIT: I swam to Nemract and got myself another boat there because their's is still there. 
EDIT 2: The merchant outside of Llevigar has lost theirs as well. http://prntscr.com/dss7g3 http://prntscr.com/dss84i

**Comment by ColinRioux** [comment]
Try switching servers.

**Comment by zqck** [comment]
Neither of those work.

**Comment by LordHelmchen98** [comment]
I might be wrong but think all the Boat Merchants have been removed you can only buy boats from Seasail Merchants now.

**Comment by ColinRioux** [comment]
Oh yes, @LordHelmchen98 is correct. Boat merchants no longer exist as of the update: 1.14.1. Instead you can only buy boats from Seasail Merchants, which are located next to the nearest V.S.S Seaskipper.
