### ISSUE TITLE
Enter the Dojo glitch?

### ISSUE THREAD

**Issue by EpicfaceXD** [Wynncraft/Issues#7130]
I have no clue why but in the 4th room of the quest where I have to make tea, i cannot harvest sugar which is essential to making the tea and completing the quest. Is this just lag or is it a bug?

**Comment by Lockilocke1** [comment]
I have that too, i can get every ingriedient. But if i press the button for sugar nothing happens

**Comment by LordHelmchen98** [comment]
Duplicate of #7121 
Please avoid duplicates and post on the original thread.

**Comment by almendris** [comment]
Alguna solucion...>?

**Comment by LordHelmchen98** [comment]
@almendris In future please try to talk in english. However for now I used google translator and no I dont think there is a solution yet.
