### ISSUE TITLE
Removing blocks from the training area in the temple beside troms

### ISSUE THREAD

**Issue by CHENS85** [Wynncraft/Issues#7131]
The mage class can remove blocks with the ice snake spell (im on server 21)
![2017-01-08_01 33 17](https://cloud.githubusercontent.com/assets/5460820/21747844/0afe49a2-d543-11e6-8095-318685c908bb.png)

**Comment by Numbermaniac** [comment]
Temple of the Legends, correct?

**Comment by CHENS85** [comment]
Yea

**Comment by thecoolkogut4** [comment]
visual glitch. right click where the block would be and it comes back.

**Comment by DohdoEXE** [comment]
I was about to report this. I did it to a block of ice tho

Welp, its a good thing you found it out or else it would've been a duplicate

**Comment by Moe-Ronickah** [comment]
RESOLVED
