### ISSUE TITLE
"Enter the Dojo" Sugar Bug/CMB not working?

### ISSUE THREAD

**Issue by Lockilocke1** [Wynncraft/Issues#7134]
I know this Bug is already on the forums, but i just wanted to report it against because i need the sugar, in the Quest "Enter the Dojo", for the green tea you have to brew as soon as possible

**Comment by Lockilocke1** [comment]
Duplicated #7130

**Comment by LordHelmchen98** [comment]
Actually it's a duplicate of #7121 so yeah look there for more information.
