### ISSUE TITLE
Experienced server-lag, re-logged, then my horse was gone.

### ISSUE THREAD

**Issue by sawforddiggin** [Wynncraft/Issues#7135]
So if you know a lot about the horses, there are a lot of errors that happen with them. Most of them are server-side catch-up issues. But this is the worst case that I have had to deal with as of late.

Here is what happened in a nutshell: I had left the server due to lag issues, but when I had reconnected, the tier 2 horse I had in my inventory disappeared. In a panic to get onto the same lag-ridden world, I find that it too had disappeared. So, I then go to the horse merchant and try craft a tier 2 horse once again. But due to the fact that crafting horses into greater tiers is rigged by a terrible percentage, not only was it a server-side glitch but a waste of 24 emerald blocks as it had trumped up with yet another tier 1 horse. Now I am furious with the already annoying horses and now with a greater, more burning passion of how unfair these beasts have become.

Thank you for your time of reading this error, as I know this problem appears a lot and you moderators and admins must deal with this on a vast scale.

~Saw

**Comment by thecoolkogut4** [comment]
so the problem is that you lost your horse due to lag? sorry, couldent really figure it out.

**Comment by sawforddiggin** [comment]
I lost the horse due to an unknown glitch from server hopping. Since the server I was on had lag. I was at Ragni's emerald merchants with my inventory **Closed!** Not even with in any of the ender chests.

**Comment by Villageacules** [comment]
Please title this issue properly.

**Comment by sawforddiggin** [comment]
Oh, I am terribly sorry... But in a simple term, searching "disappearing horse" does not show up twice.

**Comment by sawforddiggin** [comment]
Well, how can I put it in a way that would be duplicated if it were simpler and achieving large amounts of emeralds in a short span of time? How about this. A tier 2 horse simply disappearing from my inventory (Not pressing Q, dropping it out of my inventory or anything of the sort (at least, not to my knowledge)) and with a closed inventory, I leave to a different world only to notice that the horse had just disappeared. I immediately checked the villager's ender chest but to no avail. I then return to the lag-ridden world (which was only 5% at the time) and nothing was found there. This world was world 7. I double checked with each of my empty inventory slots to confirm it had completely disappeared in both worlds. I would replicate this again, but I am not the one who owns 1 million liquid emerald vials, emerald blocks or emeralds in general. If this isn't unique or specific enough as to what happened, then I am not sure how to satisfy you my friend.

**Comment by DebugingLonks** [comment]
Long story short, wynncraft has a no-refund policy and all of that.

**Comment by sawforddiggin** [comment]
Well that's just great.

**Comment by Moe-Ronickah** [comment]
"Not pressing Q, dropping it out of my inventory or anything of the sort (at least, not to my knowledge))"
Change your drop key to something else, like "Delete".
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
