### ISSUE TITLE
Website: Player "Last seen" field does not account for timezones

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7137]
If I've just left the server, for example, it says that I was last seen ~17 hours ago (daylight savings may change this number), because that's how far ahead Australia is of Wynncraft's North American servers. It should say "a minute ago", or something, but it fails to account for the time zone difference.

**Comment by DebugingLonks** [comment]
Clever.

**Comment by DebugingLonks** [comment]
Noticed a bug myself on this, I don't think I can reproduce it, but I looked at a players stats by typing name on the search bar (not on the website, by typing the url) then typed someone ELSES name in the stats bar and it gave me the 1st persons stats... (It said I hadn't been on in 3 years, and im on almost everyday) but not anymore

**Comment by Moe-Ronickah** [comment]
The server, and the forums, are on the time zone of wherever they are.  It's weird that the servers don't account for time zones, but they don't, they haven't, and they probably won't.
