### ISSUE TITLE
taproot quest cant get to the  taproot

### ISSUE THREAD

**Issue by endermage290r** [Wynncraft/Issues#7139]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

**Comment by DebugingLonks** [comment]
Are you even reading your own posts. Please post issues in the body not the title. Also issues where you do not delete the line saying to read, will prob get closed.

**Comment by Trixter313** [comment]
As @ColinRioux said in your other issue:
"Closing, please follow: https://forums.wynncraft.com/threads/guide-to-contributing-on-official-github-issue-tracker.170506/

When creating an issue. You're not specific enough for anyone to help you. Please also attach images."
