### ISSUE TITLE
Jera negative elemental defense

### ISSUE THREAD

**Issue by HazardEST** [Wynncraft/Issues#7141]
Jera has -50 negative defense on everything but when i look at compass, it gives -100 instead on everything.
I dont have any other items equipped.

**Comment by Kroko-fant** [comment]
do you have a Item with -% Deff ?

**Comment by HazardEST** [comment]
> I dont have any other items equipped.

**Comment by XavierEXE** [comment]
It's just a visual issue in the compass menu, the negative defense you have is only -50.

**Comment by Moe-Ronickah** [comment]
Please follow the instructions on the FIRST page of the GitHub to do a proper search.
