### ISSUE TITLE
Invis

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7143]
Ok first of all read #6147 that will tell you what you should know ;P

ok now, whenever making a new class, I can not see players, they can not see me (sometimes), if i use particles they can see that. I have sometimes seen invis players in detlas with particle effects (even sometimes floating ._.)

anyway, this is NOT because of my resource pack. This happens on 100% chance for me. It happens on my desktop (windows) and my laptop (Macbook Air) I have tried different minecraft versions too

**Comment by DebugingLonks** [comment]
ill post more later about it

**Comment by DebugingLonks** [comment]
Ok im back. So here it goes.

When someone makes a new character/if I make a new one, people in the spawn area sometimes will not be able to see me... oh i gtg again rip ill say even more when im back for the 3rd time

**Comment by DebugingLonks** [comment]
Also im active on the wynn discord if anyone wants to contact me there. Just look for someone with the name Debug (I may have it as deboat sometimes)

**Comment by thecoolkogut4** [comment]
When this happens do you have an Alex skin?

**Comment by Numbermaniac** [comment]
Yes, you do spawn invisible sometimes when you log in. You'll notice you have the default skin in F5 view, but you can fix it by taking off a piece of armor, walking a step, and then putting it back on. You'll be visible and your skin will reappear.

**Comment by DebugingLonks** [comment]
I do get alex skin, but either way for me it does not slowly fix. My skin does however.

**Comment by DebugMC** [comment]
Closed since I found #4721
