### ISSUE TITLE
Beneath The Depths Quest in Pirate Cove

### ISSUE THREAD

**Issue by TheMoltenPhoenix** [Wynncraft/Issues#7145]
The quest is faulty since when ever I go in the skull at the entrance to the pirate cove nothing happens. Pls tell me if this is a bug or not. Also if I'm not doing it right pls tell me how to do it.

**Comment by Numbermaniac** [comment]
What do you mean by "nothing happens"? It's not a portal, despite being obsidian/coal blocks at the entrance. You're meant to just walk in and find it.

**Comment by LordHelmchen98** [comment]
There is [this wiki page](https://wiki.wynncraft.com/index.php?title=Beneath_the_Depths) for the quest.

**Comment by DohdoEXE** [comment]
Well, you see, you have to do the maze first. Then you go to a room, then you drop an emerald to the entrance of the room, and then you profit

**Comment by DebugingLonks** [comment]
"Do not make mazes. Like ever. Those things are the devil." -GM Doc

**Comment by Moe-Ronickah** [comment]
RESOLVED
