### ISSUE TITLE
was able to breed my black horse and brown horse?

### ISSUE THREAD

**Issue by etronmortron36** [Wynncraft/Issues#7146]
So i spent the rest of my emeralds on getting horses and i accidentally got by black horses and was able to breed it with a brown and lost it in the presses. Is that a glitch that im able to do that?

**Comment by LordHelmchen98** [comment]
I dont know if it wasnt supposed to work like this when horses got implemented but it has been working like this as long as I can remember. You just have to take care and maybe double check if you really breed two horses of the same tier.

**Comment by Moe-Ronickah** [comment]
It is part of the normal horse breeding mechanic.
