### ISSUE TITLE
Stuck in The House of Twain graveyard

### ISSUE THREAD

**Issue by Swagnemyte** [Wynncraft/Issues#7147]
So I was doing the quest A Grave Mistake when the cutscene came and now I'm stuck because it glitched out. I'm just in an invisible box with nothing happening. Please fix this.

**Comment by Numbermaniac** [comment]
/kill if you have more than 5 soul points, or use a teleport scroll if you have one.

**Comment by DohdoEXE** [comment]
If you're scarred of /kill you could always relog. It worked for me in one of the puzzle thingies thingies

**Comment by kkbirdy** [comment]
I had that problem as well, i just had to /kill

**Comment by AscendedKitten** [comment]
If you have enough soulpoints, use /kill to exit. Otherwise, you can use a teleport scroll in case you have one.
