### ISSUE TITLE
Dungeon at start of game

### ISSUE THREAD

**Issue by prominecrafter05** [Wynncraft/Issues#7150]
i cant get past the hallway after the door, i get stuck on a barrier and cant get into the new area, please help

**Comment by DebugingLonks** [comment]
do /fixstart. Anyawy, are you saying the castle doesn't tp you to ragni? Its not a dungeon so im confused.

**Comment by prominecrafter05** [comment]
@debuginglonks The first dungeon possible, to the left of spawn lvl 9 recommended i believe (sorry for misunderstanding forgot the name of it) and i get stuck after the 18 token door, i go thro the hall and i get stuck on like an invisible barrier where i get the msg "how dare you trespass you must have no soul" or somethin like that

**Comment by DebugingLonks** [comment]
Ah! That part. I thought you meant you were stuck in the start zone. To get past it simply go on the other side of the hall instead of being in the water. It is so that you don't skip that message

**Comment by prominecrafter05** [comment]
@debuginglonks it still doesnt let me pass whether i am in the water or not, i have tried restarting the dungeon and walking back and forward from where the door closed

**Comment by prominecrafter05** [comment]
@debuginglonks i have also noticed that if i shoot and arrow it gets stuck on a block then goes thro after a second, the same when i drop an item

**Comment by Numbermaniac** [comment]
So you're in the Decrepit Sewers, and you've collected the 18 tokens to get past the first phase. So are you saying that you get blocked by an invisible wall inside the tunnel?

**Comment by DohdoEXE** [comment]
I think if you try going to the sides, it'll help you

**Comment by DebugingLonks** [comment]
Yeah @prominecrafter05 FYI you are shooting a barrier. Try going around it. later today I can show you if you are online msg me "DebugMC" is my ign

**Comment by prominecrafter05** [comment]
Yes @numbermaniac

**Comment by prominecrafter05** [comment]
@debuginglonks ok, ill be on server/lobby 16, come on when your ready

**Comment by prominecrafter05** [comment]
@debuginglonks 13 sorry

**Comment by prominecrafter05** [comment]
Nvm sorry, an admin fixed it

**Comment by DebugingLonks** [comment]
:D Thats great. Sorry for not being on, im at school I said I would do later :P If issue is fixed please close

**Comment by prominecrafter05** [comment]
@debuginlonks its ok, i had school aswell ty for help

**Comment by DebugMC** [comment]
No problem :D
