### ISSUE TITLE
I Have Probleme with quest

### ISSUE THREAD

**Issue by ZoRo01** [Wynncraft/Issues#7151]
Quest : WynnExcavation Site A
^
The quest theTranslation Paper i have lost 

i hope you can help me with this probleme

**Comment by DohdoEXE** [comment]
Please only leave issues if the problem is new. To find out, you can do this: site:github.com/Wynncraft/Issues/issues/ [Insert Issue Here]

If nothing pops up, you're free to upload an issue

**Comment by ZoRo01** [comment]
if i do /fixquests 

it the same nothing hanppning

**Comment by DebugMC** [comment]
Dupe of (Insert number here later I forgot)

**Comment by JeffTheNub** [comment]
/fixquest is a little bit glitchy now, so... maybe try it later?
