### ISSUE TITLE
WynnExcavation Site A (No shard drop from boss)

### ISSUE THREAD

**Issue by Madoxx10** [Wynncraft/Issues#7153]
Although i haven't found any issues exactly like mine, I have found other glitches with the WynnExcavation Site A... 

So I did the quest, blah blah and I got to the point where I needed to kill the boss. Since I'm a mage, I was meteor-ing him. XD Anyway, he was on the edge of the stairs (That you need to go down to attack him) so when I killed him, I didn't see his drop. I assumed it fell into the water so I killed him again, this time in the middle of the platform, and received a Yellow Chrystal. I headed back to Vade but he still says the same thing about wondering what the riddle means and telling me to get lost. /fixquests doesn't detect anything wrong. Help?

**Comment by DebugingLonks** [comment]
To trigger the update:

 -Leave going thru the coal blocks, not walking back
- Check your quest book for what it says
- Try again

**Comment by HowzitYall** [comment]
ah
playing as a mage is a huge pain when it comes to linear questing. Just backtrack as far as possible and (very important) walk with no TPing to the end
that fixes the problem most of the time

**Comment by Madoxx10** [comment]
Ah XD welp, I solved the issue. ^-^
