### ISSUE TITLE
Clock Dungeon Problem

### ISSUE THREAD

**Issue by HowzitYall** [Wynncraft/Issues#7157]
The clock dungeon needs a mortal fix
If you just linger in Cronus' chamber for 2-3 minutes, he just respawns, slightly defeating the purpose of grinding in a dungeon in general.
This might not be a problem for other classes as they need to heal, but a full stocked player or a mage with a good weapon (scroll of nythar) can just easily obtain all the clock parts.
Thanks for reading
Mr_Pasta

**Comment by AscendedKitten** [comment]
Kronus, like (most) other bosses, is supposed to respawn after death. 
Otherwise the farming of the clocks (8 clocks from each city would be required) would just take too long, and collecting them one time should be enough for the full reward, in case they manage to defeat Kronus multiple times.
