### ISSUE TITLE
More bugs

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7161]
More bugs for my list I posted a while ago (I thought it should be a separate issue.)

- Mobs burning to death drop armor (known bug)
- Bob can die from wooden sword explosion (Causing bug # 1 apparently)
- Powder from combining, powders from relics, powders from bombs, and powders from drops don't stack.
- Tier 4-6 relics don't give the right item. (It is tier 1-3 now no matter what)
- Dual wielding can cause item deletion
You can glitch out the map (not saying how I will show a moderator how) AND NO I AM NOT USING THIS 
(ik the rules lol just wanted to report)
- Stars on items are wrong (2-3 only)
- A 20 stat on a blue mask can have no stars
WynnExcavation Site A is not working right. (Ask others)
- Boats are sinking
- Dueling still can kill you
- Potions can be named Heal1-3 and stuff
- Mana Steal doesn't work 

- more to come in comments if I find more

**Comment by DebugMC** [comment]
Close

**Comment by LordHelmchen98** [comment]
>Stars on items are wrong (2-3 only)
 
Wrong by the way, it's even possible to have 1 star on max if max is 2 or 3 (e.g. some items with mana regen)

> Mana Steal doesn't work

Why? I never had problems with Mana Steal.
