### ISSUE TITLE
Guild Creation

### ISSUE THREAD

**Issue by GameScout180** [Wynncraft/Issues#7162]
I'm trying to create a guild. But whatever name I choose (using English characters) gives me this error: "Please use English characters A-Z name for your guild name."

Help me please.

**Comment by DebugMC** [comment]
Guilds are currently broken.

**Comment by thecoolkogut4** [comment]
if you dont mind me asking, what do you want to name your guild? and what level are you?

**Comment by GameScout180** [comment]
I am level 52 and me and my friend are naming it Quiet of the Lost

**Comment by thecoolkogut4** [comment]
What happens when you try a shorter name? Maybe Q of the L? I'm not too sure the name might be too long

**Comment by DebugMC** [comment]
You can't have spaces @GameScout180 @thecoolkogut4 ;) it has to be ' QuietOfTheLost ' no '

**Comment by ColinRioux** [comment]
@DebugMC Well, you can actually, since my guild is "Wynn Theory" 

I'm going to go with @thecoolkogut4 and assume it's too long of a name. If so, then there is a bug because it should be throwing a "too long" message instead of a "use characters" message.

**Comment by LordHelmchen98** [comment]
I think @thecoolkogut4 and @ColinRioux are right because I'm pretty sure the name can only have 16 character (spaces included) and this name has 17 characters.

**Comment by DebugMC** [comment]
Can someone add a guild tag to this issue :P

**Comment by Moe-Ronickah** [comment]
It doesn't need a name or a tag - their name is too long.
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
