### ISSUE TITLE
Bugged quest

### ISSUE THREAD

**Issue by 0pu** [Wynncraft/Issues#7164]
I played the wuest "flight in distress" and right after I escaped the pirate ship I got teleported to a black room and nothing happened. It felt like a string was missing or something. And then the only thing I had in my head was to do /kill and then I swapned in Lexdale. now the quest is really bugged if I try to go back and re-do it and I don't know what to do. Please help.

**Comment by DebugMC** [comment]
I could help you, but I haven't started the quest or the credentials one.

**Comment by AckroWynn** [comment]
You should use our skip feature. Enter the ship from Cinfras, and where the attendant stands, enter your room. Continue the quest from there.
