### ISSUE TITLE
Bug with Mask

### ISSUE THREAD

**Issue by Owbito** [Wynncraft/Issues#7165]
Hello! I just recently bought the "Mask of Fear" in the Jungle village just outside of trumbs. I loved the design of it and i could not wait to use it. but then for about 1 hour ago it became a boring Steve head. Its really not that fun to go around with a steve head on your adventure. I hope that somebody can help me and i really want to use it. Have a nice day :)

**Comment by DebugMC** [comment]
Sorry hate to tell you, this is a known bug, it has to do with NBT tags. Hopefully it will be fixed in the future.

**Comment by Owbito** [comment]
Oh, sad :(

**Comment by DebugMC** [comment]
If you could please close the issue ;P we try to keep the bugs we can't fix open
