### ISSUE TITLE
I stuck in the Quest: Meaningful Holiday

### ISSUE THREAD

**Issue by KatzeLauraa** [Wynncraft/Issues#7166]
I teleported me with a Teleport Scroll from the Candy island and now i can't back to end this Quest
Ingame name: PaedagoginLaurii

**Comment by Numbermaniac** [comment]
What happens if you go back to Ternaves and speak to Reshad again?

**Comment by KatzeLauraa** [comment]
Nothing. he don't speak with me

**Comment by KatzeLauraa** [comment]
Wait i saw a particel field and rightclicked it now i'm on the Candy Island but thanks
