### ISSUE TITLE
/Kill Bug

### ISSUE THREAD

**Issue by EN0xx** [Wynncraft/Issues#7167]
I don't know what Wynncraft moderators did, but every time I got stuck cause of others bugs that shouldn't be there too, I re-spawn at the first place ! You know, where you start the King's recruit quest... This is really weird, please help me. It happened more than 3 times, I got enough. Thanks.

**Comment by Numbermaniac** [comment]
Yeah, sometimes when you /kill it will respawn you in the King's Recruit area, since that is often the closest respawn point to areas outside of the map.

**Comment by DebugMC** [comment]
Known bug.

**Comment by ColinRioux** [comment]
It's not really a bug, it's just a mechanic which happens to not work in favor of the player. The development team are aware of it, and may choose to change the mechanic in the future.
