### ISSUE TITLE
Nether problem

### ISSUE THREAD

**Issue by MrBagdanelka** [Wynncraft/Issues#7168]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

In the nether don't works the "Wybel Fluff Bow", reboot this please.

**Comment by thecoolkogut4** [comment]
Until the new items are added to the database of the Nether and Guild War servers, they won't work on either one, respectively. Sorry, everyone, but this is the way it is. It just takes time for the databases to be updated.

### _reference: moe_
