### ISSUE TITLE
Respawned After /kill not in a Town or the Start

### ISSUE THREAD

**Issue by Pyromanical** [Wynncraft/Issues#7171]
I was doing A Grave Mistake (for like the 10th time, because I always get stuck in the church part of the cutscene), and I got stuck in the church part of the cutscene, did /kill like I always do.  Every other time I've done this, I respawn in Lusuco.  However, this time I respawned in the crypt of the church in the graveyard.  No clue why I respawned here, as I did the exact same /kill 5 mins before and I respawned in Lusuco.
This is where I respawned
![2017-01-14_11 07 14](https://cloud.githubusercontent.com/assets/21978993/21956577/cf39dcae-da49-11e6-823e-3a2003acafda.png)

**Comment by Pyromanical** [comment]
And I just got stuck and /kill'd in the same place again, and respawned in Lusuco again

**Comment by 0x0000null** [comment]
Weird. That's in the cathedral in Beyond the Grave.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
