### ISSUE TITLE
Old Item Stats

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#7172]
I logged into my warrior class and spawned in the update room. I haven't used that class since before the Gavel update. Then I noticed something wierd with my leggings. This screenshot was taken today:
http://imgur.com/a/VqHmb

**Comment by BasicallyNothing** [comment]
Also, this item can't be sold to the Item Buyer

**Comment by thecoolkogut4** [comment]
All items with non-english letters did not get updated to the new system.
