### ISSUE TITLE
Lost Sanctuary Floor Glitch

### ISSUE THREAD

**Issue by Bromides** [Wynncraft/Issues#7173]
When I began the boss fight with Garoth, I was running an fell into lava below the floor (the lava is there for later, when you blow the floor up). I almost died, but stopped burning and remained stuck under the floor inside the machinery, as seen here

![2017-01-14_18 57 52](https://cloud.githubusercontent.com/assets/17725324/21959207/11c8769a-da8e-11e6-830e-d4b503198898.png)

Has anyone else had this issue? And if not, is there some way to fix this, or is it a freak accident?

**Comment by ColinRioux** [comment]
Most likely a freak accident, to escape, use `/kill` with 5 or more soul points.

**Comment by Moe-Ronickah** [comment]
This sounds like the result of lag, either server or client side.
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
