### ISSUE TITLE
Nether's Scar Negative Defense - Wynncraft

### ISSUE THREAD

**Issue by Pontosaurus** [Wynncraft/Issues#7174]
I use Nether's Scar as my boots. I have an issue regarding its fire defense.
![nether sscar](https://cloud.githubusercontent.com/assets/25126754/21959311/d12b936c-da77-11e6-8ecf-b881977d18e3.png)

As you can see from the image above, Nether's Scar gives **+140 Fire Defense**.
Without wearing the boots, my fire defense is this: 
![beforenether sscar](https://cloud.githubusercontent.com/assets/25126754/21959322/158a936e-da78-11e6-96e7-a80c303bf491.png)

But, when I put on the boots, instead of my fire defense raising to **305**, it lowers to **25**.
![afternether sscar](https://cloud.githubusercontent.com/assets/25126754/21959325/32d15700-da78-11e6-9022-86cccbf21521.png)

This means that Nether's Scar is removing 140 fire defense instead of adding it. It seems that every other defense update on the boots works, as it lowers the air and water defenses and increases the thunder defense accordingly.
I hope this is a fixable issue, as I really like the statistics on this item.

Thanks,
Pontosaurus

**Comment by ColinRioux** [comment]
Hi, have you confirmed that wearing these boots negatively help you in game? It could just be a display issue, not a mechanic issue.

**Comment by LordHelmchen98** [comment]
Don't trust the defense stats in you compass. They are bugged.

**Comment by Pontosaurus** [comment]
Oh ok

**Comment by Moe-Ronickah** [comment]
RESOLVED
