### ISSUE TITLE
Flight in Distress wording issue

### ISSUE THREAD

**Issue by kkbirdy** [Wynncraft/Issues#7175]
Engineer Eric: You must be the 'uman the captain done told me.
Engineer Eric: We sure are havin' quite the situation down 'ere.
Engineer Eric: I dun looked at the machine but I dun see nothin' wrong.
Engineer Eric: Hmm dun worry. We can fix it.
Engineer Eric: Let's try turnin' it off and on again. That usually works.
Engineer Eric: Pro'lem is I gotta stay down 'ere, and that system to restart is on the top of the ship.
**Engineer Eric: You can get up there from **captain's quar'ers.****
Engineer Eric: There is a colour coded restart system atthe top. They made it nice and simple. But it only works if I press the same code down here.
Engineer Eric: I will be down here pressing buttons when I see you dun yer thing.
Engineer Eric: I'll write down the code of the buttons to press. Just head up to the top on the ship.

Eric specifically says you can get there from the captains quarters which is a lie, you get to it from the top of the ship where the captain is flying it, not the captains room marked as the captains quarters.
This is just a small wording issue which can be annoying.

**Comment by AckroWynn** [comment]
I've replaced it with something else! Thank you for noting.
