### ISSUE TITLE
Broken Item - Legendary Item:/ 

### ISSUE THREAD

**Issue by Freshmontano** [Wynncraft/Issues#7176]
I understand that my item has a non-english character and for that it was messed up after the Gaval update.  I'd like to know if it can be replaced as i spent a lot of time for it and lots of emeralds on it...
Picture of Legendary Item
https://gyazo.com/28366f3a8fb4a5c33b85ba16f1bb95df

**Comment by DebugMC** [comment]
We can not fix it, but I can give you a replacement item if I know your level (Also can i have dat xD I collect old items)

**Comment by Freshmontano** [comment]
oh ok :(

**Comment by DebugMC** [comment]
Hey can you come bak on for amin

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by ColinRioux** [comment]
Hi, actually this weapon was changed after the Gavel update. Therefore, old Fierté's are broken. 

The unfortunate consequence of the Gavel update is that items like that will not be refunded. This goes along with the no-refund policy. It's put it place to retain fairness among the players. The best thing you can do is either grind or buy a better item. I'm sure you could find plenty of players willing to give you better items for free.
