### ISSUE TITLE
Dernel Jungle should be level 60 on map

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7177]
Seeing as you're confronted by level 60 mobs the moment you walk in, it makes no sense for Dernel Jungle to be listed as lv 50 on the online map; it should be level 60.

**Comment by JeffTheNub** [comment]
I think it's right to say it's TOUGHLY suitable for a lv.50 player to head in the jungle, as the mobs are level 60 doesn't mean you have to be level 60. And also, I think you are advised to fight mobs that are MOSTLY between your level radius. Level 60 mobs might be not as hard to kill to you right?

**Comment by DebugMC** [comment]
I think it should be 60 too @JeffTheNub there are lvl 60 mobs that rapid fire ranged attacks, that is never fun. Also the quests involving that area are usualy in the lvl 60 area.

**Comment by Moe-Ronickah** [comment]
Nope, 50 is correct.  You can get in there, and work your way around, killing mobs with ranged attack, and gaining XP, at level 50.  With a decent warrior build - the standard for all areas - it's a level 50 area.
