### ISSUE TITLE
I Screwed Up.

### ISSUE THREAD

**Issue by EEopkc** [Wynncraft/Issues#7180]
So basically, Im lvl 78 and finished reincarnation, so i was bored and I decided to do /fixquests for absolutely no reason, and I ended up getting Chucks favourite feather and Healing Water. I checked for both of these items and they're not needed anymore, and i cant dispose of them cuz their quest items pls halp.

**Comment by thecoolkogut4** [comment]
put the items into your daily rewards to get rid of them. WARNING: /fixquests might not work when you try to get them back. Use at your own risk.
