### ISSUE TITLE
You can enter a restricted zone in a tunnel during Eye of the Storm quest

### ISSUE THREAD

**Issue by rmure** [Wynncraft/Issues#7182]
In the tunnel you enter after starting Eye of the Storm, there is a hole in the roof that you can spell-jump out of and explore the redstone wiring
![2017-01-15_21 36 05](https://cloud.githubusercontent.com/assets/25142520/21969539/0e79694c-db6d-11e6-858b-e093851eed17.png)
![2017-01-15_21 36 13](https://cloud.githubusercontent.com/assets/25142520/21969543/11ce7a1a-db6d-11e6-9d0a-8e0c45257a32.png)
![2017-01-15_21 36 20](https://cloud.githubusercontent.com/assets/25142520/21969546/15707376-db6d-11e6-802f-bcc190550313.png)

**Comment by DebugMC** [comment]
Thanks! Ill tell a builder ik :)

**Comment by thecoolkogut4** [comment]
@Villageacules

**Comment by DebugMC** [comment]
I told them, they said they looked at it, idk if its patched tho.

**Comment by Imaxe** [comment]
Issue has been fixed. 
Will take effect on the servers when we update. 
Thanks for reporting this issue!
