### ISSUE TITLE
Dungeon Hoppers

### ISSUE THREAD

**Issue by Lalala1000** [Wynncraft/Issues#7183]
I dropped my legendary dagger down the dungeon hopper in skeleton but i cant get it back by right clicking.also i know i am not the only one with this type of situation...
also if i could get it back that would be great.here's a list of what it is
I KNOW IT IS:minimum lvl of 9, it's a legendary
I THInK IT IS:attack lvl from 35 - 37 
I KNOW IT IS:the lore said something like "gang leaders would threaten their followers to follow the leader with this dagger.

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by rmure** [comment]
The weapon you're talking about is a dislocater, try to find 1 again
