### ISSUE TITLE
Quest Bug

### ISSUE THREAD

**Issue by PinHeadMcCree** [Wynncraft/Issues#7189]
For the quest the Shadow of the Beast I'm missing the first item, but have the other two.... and I can turn in the quest. All of the items were quest items and I somehow lost the first item, any help?
![2017-01-16_19 28 57](https://cloud.githubusercontent.com/assets/25163761/22004570/44af2410-dc22-11e6-9e9a-e13a895e03cb.png)
![2017-01-16_19 28 51](https://cloud.githubusercontent.com/assets/25163761/22004576/562ce736-dc22-11e6-8d54-1e8936677be9.png)

**Comment by PinHeadMcCree** [comment]
nvm i did /fixquests sry for your time.

**Comment by Numbermaniac** [comment]
Please press the Close issue button since it's resolved.
