### ISSUE TITLE
Nemract Bank: Emerald Merchant missing in one of the stalls

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7192]
3 of the "corners" have 2 emerald merchants in them:

![2017-01-17_17 51 48](https://cloud.githubusercontent.com/assets/5206120/22012423/1308fb4a-dce8-11e6-9587-77a992a38fea.png)
![2017-01-17_17 51 56](https://cloud.githubusercontent.com/assets/5206120/22012427/15bf6edc-dce8-11e6-80d2-f5afa4284d76.png)
![2017-01-17_17 51 58](https://cloud.githubusercontent.com/assets/5206120/22012431/17ec7434-dce8-11e6-9cb2-c3d5e8af2e33.png)

But one of them only has one merchant:

![2017-01-17_17 51 50](https://cloud.githubusercontent.com/assets/5206120/22012441/24c6554e-dce8-11e6-8bec-d1a657f0be38.png)

**Comment by LordHelmchen98** [comment]
@Villageacules

**Comment by DebugMC** [comment]
lol I noticed this, I thought it was intentional xD

**Comment by Imaxe** [comment]
Issue has been fixed. 
It will take effect on the servers when we update.
Thanks for reporting this issue!
