### ISSUE TITLE
Out of My Mind: Typo in one of the messages

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7193]
Message 11/11 in the first dialogue says "to" instead of "too":
![2017-01-17_18 44 00](https://cloud.githubusercontent.com/assets/5206120/22012495/5fe3097e-dce8-11e6-8974-7b39d97f9dd0.png)

**Comment by thecoolkogut4** [comment]
@Villageacules

**Comment by Imaxe** [comment]
Issue has been fixed.
Will take effect when we update.
Thanks for reporting!
