### ISSUE TITLE
Ice Barrows bug

### ISSUE THREAD

**Issue by Owbito** [Wynncraft/Issues#7194]
Hello fellow warriors :) There is a bug just in the end of the dungeon. when you're about to enter the boos battle in the black "Waiting room" that i will call it, it will not teleport you to the boss room. I tried to log in and out and even restart the dungeon but nothing happened both times. I dont know if im the only one having this problem but i hope that somebody can solve this. 

![udklip 2](https://cloud.githubusercontent.com/assets/25108022/22035601/d284028c-dcf0-11e6-8499-0cc6b46be2a1.PNG)

**Comment by Owbito** [comment]
Well, it works now. but it then lags A LOT in the boss battle. its impossible to win with this lag

**Comment by thecoolkogut4** [comment]
what happens if you turn particles off, are you still leggy? do you think the lag could be because of your computer?

**Comment by DebugMC** [comment]
There was an issue about this long ago. According to Moe lots of transparent blocks is causing your lag. I had no issue when running it myself. 

@Moe-Ronickah you said once that this was an issue and a builder needed to remove some ice blocks, has this happened?

**Comment by Imaxe** [comment]
@DebugMC 
If you want contact with a builder I suggest messaging them on the forums or sending a PM on discord instead of tagging a moderator :)

And yes, we reduced the amount of ice blocks so this issue should hopefully be fixed when we update :)
Thanks for reporting!

**Comment by DebugMC** [comment]
allrite
