### ISSUE TITLE
Item Bombs buyed

### ISSUE THREAD

**Issue by cheeselp** [Wynncraft/Issues#7195]
I am waiting for 20 min for my item bombs I have to wait or something has failed?

**Comment by LordHelmchen98** [comment]
For issues with real life currency please contact support@wynncraft.com. Send them an e-mail, tell them about your problem and include your transaction-id (not here).

**Comment by Moe-Ronickah** [comment]
@cheeselp , if your item bombs have not been credited to you, you absolutely should contact support at [support@wynncraft.com](support@wynncraft.com), as LordHelmchen98 said.  We cannot help with purchasing issues.
