### ISSUE TITLE
The Headless Hunt: Book icon is missing on map

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7198]
According to the quest book, it starts at [-1081,-5368]. However, on the map, at https://map.wynncraft.com/#/-1081/64/-5368/-3/0/0, no book icon is present.

**Comment by DebugMC** [comment]
The map isn't accurate :P if they are behind blocks it does that sometimes

**Comment by Moe-Ronickah** [comment]
The map is a skewed view of the game map, it is not generated from directly vertically above the game map, hence icon placements can easily appear out of place for objects that are above or below the plane of the map.
