### ISSUE TITLE
Lobby: A few blocks are part of The End biome instead of Plains

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7199]
From the lobby spawn point, go straight forward, behind the portal, down the stairs, across the bridge, and immediately after the bridge, exit into the grass area on the right. There are some blocks which are part of The End, so the sky goes black when you walk through them. Screenshots of some coordinates:
![2017-01-18_18 45 47](https://cloud.githubusercontent.com/assets/5206120/22055378/fee39a72-ddae-11e6-9117-8eef6a4b7a77.png)
![2017-01-18_18 46 12](https://cloud.githubusercontent.com/assets/5206120/22055379/ffd5c586-ddae-11e6-9e84-f99e0c7528a5.png)

**Comment by DebugMC** [comment]
Pretty sure its intentional, btw Woraxe has a good question in chat :P

**Comment by LordHelmchen98** [comment]
Hmm never heard of 96/101 but for me it's 98/101. That's because the quests Potion Making, Underice and ??? we're revamped and apparently the new ones weren't added to the api. But I don't know which other two quests don't count as finished in his book.

**Comment by thecoolkogut4** [comment]
@LordHelmchen98 posted on the wrong issue?

**Comment by DebugMC** [comment]
No, he was responding to my comment

**Comment by Moe-Ronickah** [comment]
Please stay on the topic of the issue.

**Comment by DebugMC** [comment]
Mk, but anyway, this has been in the game for a long time ever since we got this lobby (I mean like since we abandoned the stone brick + cobble one ) good days lol

**Comment by Villageacules** [comment]
We're currently working on a new lobby, and issues like these won't exist. However, thank you for reporting this in the meanwhile.
