### ISSUE TITLE
Dagger Aura Crash

### ISSUE THREAD

**Issue by wmafranz** [Wynncraft/Issues#7200]
I recently found a pretty big bug. I'm not sure why, but for some reason, whenever I cast Dagger Aura, the server I'm on will crash, for everyone on it, and we'll all get sent to the hub. I believe this happens for others too, because an identical crash happened when I was not using the spell. I try not to cast it, but sometimes do accidentally while casting other spells.

**Comment by DebugMC** [comment]
If this was happening yesterday, don't worry about it. If it still is I have no comments.

**Comment by wmafranz** [comment]
Yup. It fixed itself earlier. Now I feel like an idiot for putting this up...

**Comment by Numbermaniac** [comment]
No worries. You can press Close Issue, now that it's resolved.

**Comment by Moe-Ronickah** [comment]
Believe me, it didn't fix itself.  One issue got fixed, but that fix led to another issue - the one that you experienced.  So, the new issue got fixed.  So far, so good.
