### ISSUE TITLE
Bugs servers

### ISSUE THREAD

**Issue by VadimZent** [Wynncraft/Issues#7201]
Today we went to our favorite server is wynncraft, me and my friend,for some reason the server lag ,we waited until the worlds start, I went and my friend opened a chest day, I caught the bow(rare 48-52), I went to make the identification I had bow The Traveler , and I accidentally put in the identification(NPC) your bow(The Traveler) and the worlds were closed ( lost both Luka) please help me.

**Comment by LordHelmchen98** [comment]
Unfortunately Wynncraft enforces a strict norefund policy. Therefore you won't get your items back.
Hopefully the server will work properly soon so we all can play without crashing servers again but until it is fixed you should be very careful.

**Comment by ColinRioux** [comment]
Server crashing fixed as of a small mini-patch this evening.
