### ISSUE TITLE
Arrow and compass glitch

### ISSUE THREAD

**Issue by Jaizus** [Wynncraft/Issues#7202]
Hello everybody I have problem for 2-3 years... I have arrows and compass to stick(corner) in my enderchest someone can help me?
![2017-01-16_10 53 08](https://cloud.githubusercontent.com/assets/16886435/22067050/d8a19ace-dd4c-11e6-9b6e-7f3e050efc39.png)
![2017-01-16_10 53 04](https://cloud.githubusercontent.com/assets/16886435/22067054/daf3985e-dd4c-11e6-95d8-d880e84ee9b4.png)

**Comment by Imaxe** [comment]
@Jaizus 
Pretzule can help you if you message him on the forums with your ingame name :)
