### ISSUE TITLE
Link-crash

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7203]
There is a way to crash the server instantly by saying a certain link (no, i don't know the link) but in detlas someone says "Hey look @ this link" then the world crashes. No this isn't a report, just wanted to say this needs fixed. 

last I checked JuicedBananas was looking at this

**Comment by thecoolkogut4** [comment]
update 1.14.2 

- Better tools to fight against phishing (don't click links promising a minecon cape or a rank, it's a scam)

I'm guessing this bug involves that update. probably when you post a suspicious link in chat, everyone gets kicked.

**Comment by DebugMC** [comment]
Huh. Anyway he was intentionally doing it and wasn't stopped last I checked

**Comment by thecoolkogut4** [comment]
what happens when you check your MC log? does it show the link? if it does ì suggest emailing support@wynncraft.com with it

**Comment by thecoolkogut4** [comment]
this also could be related to the archer crash bug. (might be a coincidence that they happen at the same time) not too sure though.

**Comment by DebugMC** [comment]
They say 'look at this' *Crash* xD 

Also I don't crash when using arrow storm

**Comment by thecoolkogut4** [comment]
there was a patch that fixed the archer mayhem. does the "link" still crash the server/you? and there is nothing in the logs correct?

**Comment by DebugMC** [comment]
@thecoolkogut4 im closing issue due to a patch :P 
(Also I wasn't on the server, it never crashed **ME** it crashed a ton of others. I wasn't even online at the time.

**Comment by thecoolkogut4** [comment]
oh my bad, I thought you were reporting a problem that directly effected you :/
