### ISSUE TITLE
Galleon's Graveyard Key from Beneath the Depths quest doesn't stack with key from Guardian

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7205]
Pretty much all in the title. A Galleon's Graveyard key, that you get from Beneath the Depths, doesn't stack with the same key dropped by the Galleon's Graveyard Key Guardian.

**Comment by thecoolkogut4** [comment]
something for powers and other weapons.

**Comment by Moe-Ronickah** [comment]
1) This is a duplicate.
2) The admins know about it.
3) Thanks for reporting it, but I wish that you had done a more thorough issue search.
