### ISSUE TITLE
level 64 quest - A fighting Species - i can't use orc mask (im level 64)

### ISSUE THREAD

**Issue by ckcjfwls** [Wynncraft/Issues#7206]
2017 - 1 - 19 is happening

**Comment by Numbermaniac** [comment]
Do you get an error message when you try to wear it? It won't shift-click into place; you'll need to manually place it in your head slot.

**Comment by Villageacules** [comment]
Could you please elaborate more? Use our resources we have on the forums under the information section for information on how to inform us better of your issue.
