### ISSUE TITLE
Two small typos in the quest Lost Soles

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7207]
1: The New Quest Started message is missing a capital S on "Soles".
2: "Quest Book Updated" always has a capital U everywhere else.
Screenshots below.
![2017-01-19_18 22 12](https://cloud.githubusercontent.com/assets/5206120/22102286/03ef8846-de8b-11e6-9541-dcb7ee2dd78a.png)

![2017-01-19_19 03 32](https://cloud.githubusercontent.com/assets/5206120/22102302/174d905e-de8b-11e6-9eb7-844c16df2c56.png)

**Comment by thecoolkogut4** [comment]
@Villageacules

**Comment by AckroWynn** [comment]
The dialogue issues have been dealt with!
