### ISSUE TITLE
From the Mountains: One message is missing a full stop at the end

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7208]
Message 5/9 is missing a full stop at the end of its sentence:
![2017-01-19_19 23 25](https://cloud.githubusercontent.com/assets/5206120/22104192/3dd0f6ce-de92-11e6-8e6f-fbf3d77909e7.png)

**Comment by thecoolkogut4** [comment]
@Villageacules

**Comment by Moe-Ronickah** [comment]
I don't know if it's Vill's quest or not, but we can blame him, anyway, just to get it fixed.
@Numbermaniac , thanks for pointing this out.

**Comment by Villageacules** [comment]
I can fix this when I get home in an hour or so.

**Comment by Imaxe** [comment]
Vill never fixed it.
So I did, should be live when we update :)
