### ISSUE TITLE
Server problem/disconnected

### ISSUE THREAD

**Issue by Havoquinho** [Wynncraft/Issues#7209]
Every time I will enter a server of wynncraft it just load the 
world,and when is done I disconnect from server and on my screen say "disconnected"

What should I do?

**Comment by DebugMC** [comment]
@redxdev knows how to fix this I believe...

Also are you saying it just says Disconnected? I have had this a few times but not everytime I join...

**Comment by thecoolkogut4** [comment]
#6717

**Comment by Moe-Ronickah** [comment]
Jumla fixed a problem with servers crashing, but it opened up another problem, which has since been fixed.
