### ISSUE TITLE
Underworld Crypt blocked

### ISSUE THREAD

**Issue by Jaizus** [Wynncraft/Issues#7210]
Returned to the third waiting time (mini-boss) he does not appear and we remain to block

**Comment by DebugMC** [comment]
Erm... what? Try doing /class then picking your current one again... can you be more clear? Is the zombie not spawning?

**Comment by Imaxe** [comment]
What are you trying to say?

**Comment by Numbermaniac** [comment]
There's that part of Underworld Crypt where you have to survive 10,15,20 seconds (I think, maybe it's 15,20,25) for three enemies, one after the other. I think what he's saying is that the 3rd one didn't appear so he's now stuck.

**Comment by AscendedKitten** [comment]
Sadly there are quite a few issues with dungeons and redstone, as it's very fragile. 
You can leave the dungeon using /kill if you have more than 2 soulpoints, changing version might help you in future playthroughs.
