### ISSUE TITLE
Wynnpack... sort of?

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7212]
Sometimes when joining servers crafting tables, pots, and vines are missing texture, and items are 50x their size... (Drop one its hilarious to watch xD) 

Anyway I can't provide screenshots right now, I will try to do that later.

**Comment by thecoolkogut4** [comment]
Join MC version 1.8.9 to fix this issue. Just letting you know, in 1.8.9 gear skins will be broken.

**Comment by Moe-Ronickah** [comment]
Sometimes, when I change classes or worlds, the size of every object in my inventory changes.  It's a resolution error that's most likely and MC issue.

**Comment by DebugMC** [comment]
This happens on 1.8 too :I anyway, this is not from normal MC as don't get this on my server which uses apack.

**Comment by thecoolkogut4** [comment]
the pack in 1.8.9 works for me 100% of the time, once I join the server on any version  above 1.8.9 the textures start to become glitched

**Comment by DebugMC** [comment]
Well i was on 1.8 when it happend.

**Comment by thecoolkogut4** [comment]
does it still happen in 1.8 after you completely delete the resource pack in the server side resource pack folder? when you log in it should auto download again

**Comment by DebugMC** [comment]
Ihavea screenshot of a bow thats bigger than ragni ;P can't upload it, im not home and evenso Idon't have access for PC (Sryfor lack of spaces the spacebar on this pc is stuck and i haveto mash it xD)

**Comment by DebugMC** [comment]
I have it clientsided And  from the server :P (Ihave tried doing that though)

**Comment by ColinRioux** [comment]
I know what you are talking about, and it occurs not that often in my experience, and is an easy fix (by logging off and logging back on). If it were more consistent and had a huge effect on gameplay, I would deem this important, but thank you for reporting.

**Comment by TriggeredOldGuy** [comment]
f3 t would reload texture packs for u

**Comment by DebugMC** [comment]
Didn't fix I tried that. Btw

**Comment by Moe-Ronickah** [comment]
"This happens on 1.8 too :I anyway, this is not from normal MC as don't get this on my server which uses apack."

Texture pack display is client sided, so, it's MC rendering the rp in a strange way.  Unless some rp person made giant models of all of the items.

**Comment by DebugMC** [comment]
@TriggeredOldGuy tried it, it only works on the resource pack if its working right

@Moe-Ronickah the thing is I have the normal resource pack downloaded too but the server pack overrides it.

**Comment by Moe-Ronickah** [comment]
Client-side MC error.
