### ISSUE TITLE
From the Mountains Breathing helm 

### ISSUE THREAD

**Issue by cheeselp** [Wynncraft/Issues#7213]
I have the4 breathin helm 2 but i cant go in the Pool?

**Comment by thecoolkogut4** [comment]
what happens when you try to use a breathing helmet 1?

**Comment by cheeselp** [comment]
I dont tried it

**Comment by thecoolkogut4** [comment]
ok... maybe you could buy a new helmet in nesaak hopefully the new one will work.

**Comment by cheeselp** [comment]
Ist work thanks

**Comment by Moe-Ronickah** [comment]
RESOLVED
