### ISSUE TITLE
Clean Slate

### ISSUE THREAD

**Issue by deathswolfdoesmc** [Wynncraft/Issues#7214]
I logged on to Wynncraft today to do some questing, but all of my items on my level 31 character are gone. My skin is even reset to Steve. Is there something wrong server side?

**Comment by ColinRioux** [comment]
Well the skin reset to Steve is an issue regarding to versions 1.9-1.11.2 (since the network is still on 1.8.9). 

As for your items, there have you died with 5 or less soul points recently? The fewer soul points you have, the more items you lose upon death.

**Comment by deathswolfdoesmc** [comment]
Well, as for the items and soul points, I could understand a few items but my items have had a complete wipe. It's as if I had never made the character, other than my experience.

**Comment by DebugMC** [comment]
You probably clicked a link for a a free-minecon cape, that was a trick to steal your account, change your password immediately.

**Comment by Moe-Ronickah** [comment]
@deathswolfdoesmc , if you did click on a link for a free cape or free rank, please let us know, immediately, and do change your MC password.

If not, 
If you have lost a class, and haven't fallen for a scam, then please read this post, here, about what may have happened to you.

[Unintentional Deletion of a Class](https://forums.wynncraft.com/threads/unintentional-deletion-of-a-class.138254/l)

**Comment by Villageacules** [comment]
The issue looks like it was explained, even if something did go wrong for you there is a no-refund policy. Luckily, your level was only 31 so you didn't loose too much.
