### ISSUE TITLE
Guild

### ISSUE THREAD

**Issue by Scrambleking** [Wynncraft/Issues#7216]
My friend _OmegaGaming_ is unable to leave or be promoted in the guild, and is listed twice in the tab and in /guild list. We have also tried to kick him from the guild, but he is still stuck in it. He does not count twice to the guild limit tho, and it has been like this for a while.

 The guild is ShadowGuild.

**Comment by ColinRioux** [comment]
Hi, if your friend has changed his username recently, then he is unfortunately stuck until guilds are fixed (hopefully soon). Many other people are experiencing this issue. See #3665. There is no other way other than to have patience.
