### ISSUE TITLE
Big teleport bug

### ISSUE THREAD

**Issue by Jaizus** [Wynncraft/Issues#7218]
after a restart server i have been teleported... watch the screen please
![2017-01-19_23 08 39](https://cloud.githubusercontent.com/assets/16886435/22138286/119b17fa-de9d-11e6-90cd-e07c2516d352.png)
![2017-01-19_23 09 05](https://cloud.githubusercontent.com/assets/16886435/22138296/19141ca2-de9d-11e6-947c-4db77ef6832a.png)
![2017-01-19_23 09 40](https://cloud.githubusercontent.com/assets/16886435/22138297/1914a92e-de9d-11e6-9533-b993ec6f534c.png)
![2017-01-19_23 10 24](https://cloud.githubusercontent.com/assets/16886435/22138299/191b9d42-de9d-11e6-9dad-4327d93f97d5.png)
![2017-01-19_23 10 41](https://cloud.githubusercontent.com/assets/16886435/22138298/1915d0ba-de9d-11e6-8849-021077a70ee4.png)

PS: Nice building :o

**Comment by LordHelmchen98** [comment]
I assume that happened while you were in an offmap area. So you probably glitched through a wall. /kill will get you out of that area.
@Imaxe can you look at it and maybe add some extra blocks so nobody can glitch through walls?

**Comment by BlackbirdMC** [comment]
Would you please type /kill or use a scroll and respawn at the nearest town? Or you will be penalised for breaking the official [Wynncraft rules](https://forums.wynncraft.com/threads/game-forum-rules.111874/).

Thank you :)

**Comment by Jaizus** [comment]
I use the /kill and its good now:)

2017-01-29 17:07 GMT-07:00 Katherine <notifications@github.com>:
