### ISSUE TITLE
Broken chestplate

### ISSUE THREAD

**Issue by TriggeredOldGuy** [Wynncraft/Issues#7219]
![glitch chestplate](https://cloud.githubusercontent.com/assets/25246704/22150140/9232d758-df6b-11e6-9ddc-c87b9462256d.png)

wot happened

**Comment by thecoolkogut4** [comment]
that item was from before the gavel update. since it has a special character in its name it did not get updated

**Comment by Pyromanical** [comment]
Pre-gavel items with non English characters did that.  You can keep it, but selling it or giving it away is against the rules.

**Comment by Moe-Ronickah** [comment]
RESOLVED
