### ISSUE TITLE
Lost items while server closing

### ISSUE THREAD

**Issue by Xopy** [Wynncraft/Issues#7220]
**_Hello, 1 day ago there was a bug on the server when all worlds were closing, I didn't know that and joined world and tried to Identify my legendary gold boots, when it was completing the server closed and i lost my boots, can you give me them back, please? :cry:  _**

**Comment by DebugMC** [comment]
Unfortunately wynncraft has a strict no refund policy :( sorry

**Comment by Imaxe** [comment]
No refund policy sorry :/
Just grind for new items :)
