### ISSUE TITLE
My Hero Rank Hasn't Arrived

### ISSUE THREAD

**Issue by AnotherCleverIGN** [Wynncraft/Issues#7222]
Hello, I just bought the Hero rank, and it says it should arrive in 10 minutes or less, it's been about 20 minutes, and it hasn't arrived. Can it get checked on or something? Thanks

**Comment by Covergense** [comment]
Hi this is something that should be handled by sending an email to support@wynncraft.com with a copy of your receipt (as evidence of purchase).

**Comment by Villageacules** [comment]
This issue should be handled by our support team, the email address being support@wynncraft.com. Email them about any transaction problems.
