### ISSUE TITLE
A Grave Mistake (unpassable)

### ISSUE THREAD

**Issue by RandomPlayerWithBugs** [Wynncraft/Issues#7223]
This is the third time I've played the quest and it didn't let me pass the cut scene because I'm flying!?!?! I keep getting kicked for flying for no reason, I'm not flying at all. I know I'm lagging but seriously? three times? Please fix this, i want to complete quest

**Comment by LordHelmchen98** [comment]
Unfortunately the aforementioned lags are the reason why you get kicked. Join a server that has just restarted and try to complete it again.
