### ISSUE TITLE
Items dissappearing on the identifier?

### ISSUE THREAD

**Issue by BoredomCake** [Wynncraft/Issues#7224]
Hello.I was playing Wynncraft a few minutes ago and i got some unidentified items.I took them to the identifier guy, I placed my items to the identifier but the screen got canceld and in the chat it said ; "There was no space in your inventory so i dropped your items on the groud."
I looked around and no items were there.No body was around me aswell, so i dont think no one took them
and will i get my stuff back?

thank you for reading.

**Comment by LordHelmchen98** [comment]
Unfortunately Wynncraft enforces a strict norefund policy. Therefore you won't get your items back. However, sometimes those items get dropped on a floor above the player, so in case it happens again try to find them somewhere higher. But it's always better to keep some empty slots in your inventory
