### ISSUE TITLE
Inaccessible Loot Chest

### ISSUE THREAD

**Issue by RikioST** [Wynncraft/Issues#7225]
Barrier block directly above Loot Chest making it inaccessible. Near the Nesaak Great Bridge.
![2017-01-17_17 59 56](https://cloud.githubusercontent.com/assets/17153769/22177612/87111c54-dfc5-11e6-96bf-e936856b00a5.png)

**Comment by LordHelmchen98** [comment]
@Imaxe

**Comment by AscendedKitten** [comment]
The barrier has been removed, and the chest should be accessible once a map push happens. /close
