### ISSUE TITLE
Stuck in passage way!

### ISSUE THREAD

**Issue by Skylander140** [Wynncraft/Issues#7227]
#I am doing the Lost Soles quest and I was trying to find my way to the basement (which I don't know where it is) when I went through a passage way and got stuck inside 2 fences and blocks all around me. I cannot use teleport scrolls or any other boats/horses so I am stuck and unable to move. Please help get out of it and fix the issue.

**Comment by Skylander140** [comment]
I am on 1.11.2 btw.

**Comment by ColinRioux** [comment]
Do `/kill` with 5 or more soul points to get out.

**Comment by Skylander140** [comment]
thank you
