### ISSUE TITLE
I'm stuck in the ball room?

### ISSUE THREAD

**Issue by Triggaz** [Wynncraft/Issues#7228]
I was doing a quest and the server restarted now I'm stuck in the ball room there is no way out I have tired everything I don't have a teleport scroll so I'm just in the room need help to get out.

**Comment by ColinRioux** [comment]
Have you tried using the exit (coal block) portals at the back of the room? If that doesn't work, you can do `/kill` with 5 or more soul points. Be warned, I'm not sure where the ball room is relative to the map, so the nearest spawn point may be llevigar or the caravan.
