### ISSUE TITLE
Getting Stuck Under Olux Bank

### ISSUE THREAD

**Issue by Pyromanical** [Wynncraft/Issues#7229]
The floor of Olux bank is 1 block thick, when logging in, you get stuck in the floor, and sometimes, you even fall through to under the bank.  Adding a second layer of blocks under the bank floor would probably fix this.
![2017-01-21_21 02 48](https://cloud.githubusercontent.com/assets/21978993/22179580/93c8460e-e01d-11e6-9e3f-a0d083fcc2b7.png)

**Comment by ColinRioux** [comment]
You are correct, and the holes have been fixed. The changes will be made visible after the next map push.
