### ISSUE TITLE
Two typos in Memory Paranoia quest

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7230]
Message 1/4, should be "will be angry" rather than "with be angry".
Message 8/9: Should be "I got **it** from your study".
![2017-01-20_18 35 32](https://cloud.githubusercontent.com/assets/5206120/22180069/ca6211d0-e0b9-11e6-88f9-0d23b4653c84.png)
![2017-01-20_18 56 37](https://cloud.githubusercontent.com/assets/5206120/22180082/f5519e56-e0b9-11e6-89ec-e2ed2aa1b4e7.png)

**Comment by thecoolkogut4** [comment]
@Numbermaniac 

off topic: wow, the amount of typos you find are crazy

**Comment by AscendedKitten** [comment]
Thanks for submitting! The dialogue has been fixed and the changes will take effect once a new patch is released.

**Comment by Numbermaniac** [comment]
@thecoolkogut4 lol, yeah :)
