### ISSUE TITLE
From the Mountains: Typo in intermediate message

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7231]
The lowest white message on the screen, doesn't look like "of" should be in the sentence:
![2017-01-20_18 20 03](https://cloud.githubusercontent.com/assets/5206120/22180104/70d2e83c-e0ba-11e6-9830-c734cb0e8b55.png)

**Comment by thecoolkogut4** [comment]
@Villageacules

**Comment by Imaxe** [comment]
Thanks for reporting this issue, it has now been fixed!
Will take effect when we update
