### ISSUE TITLE
Cannot talk with the NPC alice

### ISSUE THREAD

**Issue by BoredomCake** [Wynncraft/Issues#7233]
Hello.Im on the creeper Infiltration quest and i cannot talk with the NPC called Alice.Im right clicking left clicking basically doing anything to intertact with her but not working.
can someone help?

**Comment by LordHelmchen98** [comment]
What does your quest book say?

**Comment by BoredomCake** [comment]
@LordHelmchen98 

 it says
--active quests--
-grave digger
-suspended flo.
-creeper inf.

**Comment by Imaxe** [comment]
@BoredomCake 
That does not help.
He meant the text on the Creeper Infiltration page in your book.

**Comment by AscendedKitten** [comment]
@BoredomCake you might've missed a step, as there'd be dialogue shown otherwise. You should compare the stage from your questbook (on the respective site for the quest) with the wiki, and check what step you are at.

**Comment by BoredomCake** [comment]
Ah,now it works.
Thanks a lot :)

23 Oca 2017 10:54 tarihinde "AscendedKitten" <notifications@github.com>
yazdı:

**Comment by DebugMC** [comment]
They are right, talking to alice before you are supposed to, or after you are done has no repeat dialogue
