### ISSUE TITLE
Got 1 level from Tower of Ascension as level 40

### ISSUE THREAD

**Issue by Happyfaceing** [Wynncraft/Issues#7234]
Did Tower of Ascension on my level 40 Archer and only got 1 level by the quest, it gives 925.000 exp and i needed 46.100 exp for 40 to 41. I should have gotten like level 50 and 1/4 of the exp to 51. Don't know if this is to prevent people to boost other classes or just a bug. 

Link of that i did the quest and only got 1 level -> http://prnt.sc/dytxe8

**Comment by Pyromanical** [comment]
This is to prevent people from boosting classes, it isn't a bug.  The xp is scaled to your level.

**Comment by Happyfaceing** [comment]
Thx for the answear

**Comment by DebugMC** [comment]
You killed death at 41? k.

**Comment by LordHelmchen98** [comment]
@DebugMC You can get the token with another class.
