### ISSUE TITLE
??? gear lost

### ISSUE THREAD

**Issue by NebulaVoid** [Wynncraft/Issues#7237]
I just finished ??? and id-ed my ??? armor and lost the boots can i get them back? (they were my only 25% xp boost piece of armor)

**Comment by Pyromanical** [comment]
Wynncraft has a no refunds policy, so sadly you can't get them back, you will have to do the quest on another class to get a new pair.

**Comment by NebulaVoid** [comment]
This is the reason i don't like wynncraft, if you're not gonna refund the item fix the glitch so it wouldn't need to be refunded in the first place :/

**Comment by Pyromanical** [comment]
How did you lose the item?  Saying you lost the boots could mean you dropped them on your own, or they actually disappeared due to a glitch.  If you don't explain the glitch, it can't be fixed.

**Comment by NebulaVoid** [comment]
i was identifying them and my inventory was full but i didn't notice because most of the time i end up with more space than i started so i was taking them out of the identifier and it said it dropped my boots on the ground but since its "untradeable"  it deleted them.

**Comment by Pyromanical** [comment]
This is a known issue.  Due to Minecraft Mechanics, when the item drops, it drops from above you, and can get stuck on the floor above you.  That is probably what happened.

**Comment by NebulaVoid** [comment]
It's still gone tho...

**Comment by DebugMC** [comment]
If you were still there you could have gotten it probs.

**Comment by NebulaVoid** [comment]
Maybe if someone told me before the server reset i woulda got it :/ and i would have been in the hour glass in detlas

**Comment by ruxtes** [comment]
About 30 blocks of emerald glitched out of my characters chest at the bank. any idea what caused this?
