### ISSUE TITLE
Galleon's Graveyard: Stuck

### ISSUE THREAD

**Issue by Victini998** [Wynncraft/Issues#7238]
During the Galleon Graveyard Dungeon, and after the Armored Pirate battle, I went through a portal. When I went through the portal, a cut scene occurred, and Redbeard spoke his 3 or so lines about fighting. However, after this nothing happened, and it made me stuck inside of the cutscene. I have attached the area where is has me stuck. I would teleport out but I do not want to lose the key for this dungeon
Thank you for reading this, and I hope this problem can be solved.
![2017-01-22_15 53 53](https://cloud.githubusercontent.com/assets/25286174/22185960/9764c93c-e0bc-11e6-88ef-cd09fb2359dd.png)

Some additional information: Minecraft 1.11

**Comment by AscendedKitten** [comment]
I am afraid there is no efficent way to continue the playthrough, so you'll have to leave using a teleport scroll or /kill. 
Sorry for the inconvenience!
