### ISSUE TITLE
Jester items Glitch

### ISSUE THREAD

**Issue by Purpwolf** [Wynncraft/Issues#7239]
When ever you put on a single jester item it applies -bonus effects for loot and XP even though they should not apply until a second item is used.

**Comment by ColinRioux** [comment]
There is 1 piece bonus shown here: https://wiki.wynncraft.com/index.php?title=Jester_Set

**Comment by AscendedKitten** [comment]
As @ColinRioux already said, the jester set is supposed to apply the "bonus" starting from 1 item, as seen [here](https://forums.wynncraft.com/attachments/jester-png.52300/).
