### ISSUE TITLE
Floating Loot Crates

### ISSUE THREAD

**Issue by ColinRioux** [Wynncraft/Issues#7240]
This is really not a big deal.
<img width="1088" alt="screen shot 2017-01-22 at 7 31 55 pm" src="https://cloud.githubusercontent.com/assets/4181161/22187730/8f6c25dc-e0d9-11e6-928c-903a26ac66c5.png">

To reproduce the issue:
1. Stand on above ground (like on a merchant tent in detlas)
2. Use your loot crate

**Comment by DebugMC** [comment]
yeep

**Comment by Moe-Ronickah** [comment]
It's really a non-issue, unless someone does it and loses a crate.
