### ISSUE TITLE
Cutscene bug happened twice

### ISSUE THREAD

**Issue by Gummy56** [Wynncraft/Issues#7243]
Yesterday, i was doing the "A grave mistake" quest and i got kicked for "Flying is not enabled on this server" in the middle of a cutscene because it glitched and then when i went back i was stuck in a box with barriers and nothing was happening... I used /kill to escape and then i tried doing the quest from the start but it wasnt working so now i'm stuck with that one quest that i can't complete... Today, i went to complete the "Galeon's graveyard" dungeon and when i finished the part with killing that armored guy with cannons i pressed the button to go to the next stage and a cutscene started, it was that cutscene were someone called "???" was talking and then i was stuck in a box with barriers again... i waited like 5 mins and then i logged off and logged in back and i was still stuck so i used /kill in the end 1. I wasted my time doing the dungeon 2. i wasted a key 3. i wasted 2 soul points

**Comment by Gummy56** [comment]
I tried doing the same dungeon again.... A BIG MISTAKE.. I killed that Armored guy again with the cannons and then i pressed the button to open thee door, the door opened! but there was a barrier wall infront of the door and i went in and the door behind me closed so i was stuck AGAIN... I'm done with this dungeon i will never do it again... 
![image](https://cloud.githubusercontent.com/assets/25297909/22203620/09747cee-e17f-11e6-8bb9-0a20cf93a935.png)

**Comment by Gummy56** [comment]
I logged out again when i was stuck between the walls and when i relogged it teleported me to the cutscene again and i was stuck again 
![image](https://cloud.githubusercontent.com/assets/25297909/22203789/c3ae8b72-e17f-11e6-9b32-0d2d830013f7.png)

**Comment by Gummy56** [comment]
I Logged off, changed minecraft version to 1.8.9 and it now works fine somehow...

**Comment by DebugMC** [comment]
ye 1.8 is more safe
