### ISSUE TITLE
A mistake on "A Grave Mistake"

### ISSUE THREAD

**Issue by Iceloono** [Wynncraft/Issues#7244]
I was starting the grave mistake quest, and when I got to the third line of dialog, I accidentally entered the same house twice. I realized my mistake when watching a guide, bur when I did the last part, the fourth dialog didn't show up, it just teleported me outside the house with no dialog.

**Comment by AscendedKitten** [comment]
I tried replicating the issue, but it works just fine for me. Do you still remember the order / which house teleported you out without a dialouge line?

**Comment by Iceloono** [comment]
I went mansion, the house with the surrounding skeletons, the lost arm, then accidentally the lost arm again. Im really not sure if there is a correct order or not, did i mess up the order or am i missing something?

**Comment by ColinRioux** [comment]
You need to visit the cathedral.

**Comment by Iceloono** [comment]
No duh, I meant cathedral by mansion, anyway, I figured it out in the end.
