### ISSUE TITLE
Bow relic

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7245]
Similar to #7221 the bow relic is hard to access, It took me over 30 tries, and i have a white horse. This used to be easy, did they shorten the time its open?

**Comment by DebugMC** [comment]
oh and it does open btw, i can see it open and my friends can get in, but it shuts so fast.

**Comment by thecoolkogut4** [comment]
try to switch servers. do you have - walks speed bonus? as you said it's a duplicate issue so why post it?  if you are interested in figuring out minor build patches I recommend you ask a builder (if they are allowed to disclose this information) on when/if they updated the relic.

**Comment by AscendedKitten** [comment]
I've tested it several times, and the duration has been extended now. 
It should be possible with all classes now, no horse required anymore!

**Comment by DebugMC** [comment]
@thecoolkogut4 i had a white horse :P doesn't matter.

@AscendedKitten thanks :D
