### ISSUE TITLE
Scrapping 

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7246]
You can not scrap 5 godly rewards, it says you do not have 5 of the tier. This is not true though, I put in five Angel Wings :P it should just give you another godly

**Comment by AscendedKitten** [comment]
Seems more like a suggestion than an issue to me.

**Comment by DebugMC** [comment]
@AscendedKitten this is an issue not a suggestion xD im saying you are unable to scrap 5 godlies, it says you have not put the same tier in the scrap gui, so please reopen :P

**Comment by DebugMC** [comment]
Basicly if you have a ton of godlies you don't want, your stuck with them. also a side bug involving scrapping is you can use weapon skins/effects and disguises if you have them enabled them scrap them. Attack effects will stay, effects don't, but weapon skins do.
