### ISSUE TITLE
Missing Inventory glitch

### ISSUE THREAD

**Issue by HarryShachar** [Wynncraft/Issues#7247]
So, at about Nov 20, I logged on wynncraft, search in my inventory and found nothing, except my quest items! I was really annoyed and checked mybank which was all OK, but any of the staff, if you're reading this, tell me what happend and how I can my items back.

**Comment by Pyromanical** [comment]
Sadly Wynncraft has a no refund policy, so you won't be able to get your items back.  Because you still had quest items, you probably went afk, and were killed over and over, causing you to drop your non-quest items.

**Comment by HarryShachar** [comment]
Thank you very much, I just wanted to know :) Also REALLY fast service!

בתאריך 23 בינו' 2017 19:48,‏ "Pyromanical" <notifications@github.com> כתב:
