### ISSUE TITLE
Skill Points Not Registering 

### ISSUE THREAD

**Issue by chesterlea1** [Wynncraft/Issues#7248]
IGN: chesterlea
Hello
         a few days ago i was fighting in a dungeon and all of a sudden all my armor and weapons were taken off because i didnt have the appropriate skill level to use them. i looked at all my stats and they were all messed up so i payed two soul points to reset them. i have 82 skill points to assign but when i do so, a point is used and there is no skill gained. im not sure what to do, if you could reply asap that would be greatly appreciated.

Thanks again

chesterlea.

**Comment by AscendedKitten** [comment]
It might be a visual issue, have you tried using another version yet?

**Comment by chesterlea1** [comment]
ive been using the newest version.... i just found out that my skill points dont start stacking until i put 5 points in each... so it says i have 82 skill points but in reality it only lets me spend 63

**Comment by AscendedKitten** [comment]
Oh, that's because the limitation for a stack in minecraft is at 64. 
Skillpoints invested in a stat that's already over 64 still count though, and you can see them by hovering over the respective icon. 
Also, you might use accessory or armor that reduces your skillpoints, which would explain the "not showing up".

**Comment by DebugMC** [comment]
Just to make it clear now, wynncraft has a no refund policy :P you won't get your items back

**Comment by chesterlea1** [comment]
im not missing any items. they were just uneqquipted

**Comment by chesterlea1** [comment]
no ascended, my stats were not over the 64 mark. they were reduced back to 0. i have 82 points to distribute between the 5 skills.

**Comment by chesterlea1** [comment]
i figured out the problem, thank you for your help! greatly appreciated!
