### ISSUE TITLE
Haven Antiquity: Typo in Cinfras' dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7251]
Message 3/6 should be "It is **a** sorrowful place":
![2017-01-24_12 13 00](https://cloud.githubusercontent.com/assets/5206120/22232035/0e5ab78e-e23b-11e6-95fb-a1842b9f4ab6.png)

**Comment by AscendedKitten** [comment]
Thanks for the report! 
The typo has been fixed, and changes will take effect once a new update is released.
