### ISSUE TITLE
Forbidden Prison: Quest completion didn't play a sound

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7253]
As far as I remember, quests usually play a short chime when you complete them. Forbidden Prison didn't play any sound when I completed it.

**Comment by AscendedKitten** [comment]
The sound is set through code as far as I know, and should play in all cases. Maybe your volume was a bit low, and you just overheard it?

**Comment by Numbermaniac** [comment]
Hmm...maybe. It's weird, because normally I always hear it. Thanks!
