### ISSUE TITLE
I get kicked everytime!

### ISSUE THREAD

**Issue by LilVictor** [Wynncraft/Issues#7254]
My computer is a bit slow, and almost everytime I try to join a world, I get kicked after the resource pack loads.. I don't know if this is a error or is just my computer. Could I do something to stop this?

**Comment by Pyromanical** [comment]
When logging in, do you join as your class or go to the class screen?  If you join as your class, do the command '/toggle autojoin'.  You will log into the class screen making it less likely for you to get kicked.

**Comment by LilVictor** [comment]
I go to the class selection.. I don't use autojoin because it takes 2 or 3 minutes to load the Wynnpack

**Comment by DebugMC** [comment]
@LilVictor You should directly download the resource pack to your computer. This majorly decreases the time it takes and prevents lag. I can't provide a download right now, but go to http://jumla.in/NN

**Comment by LilVictor** [comment]
How do I download the resource pack.. I mean there isn't any link or something? xD

**Comment by DebugMC** [comment]
There is, but im at school I can't look @ stuff

**Comment by DebugMC** [comment]
Wynncraft forums isn't like blocked, but it doesn't load correctly.

**Comment by DebugMC** [comment]
Can't guarantee this is the right one, but try http://jumla.in/NP I think this is a download link.

**Comment by LilVictor** [comment]
Thank you I will try this

**Comment by DebugMC** [comment]
no problem :D

**Comment by DebugMC** [comment]
if it fixed please close issue.

**Comment by Numbermaniac** [comment]
It's also uploaded to this repo - https://github.com/Wynncraft/Issues/blob/master/0b88c016c0b811591eac6045e66c5fbadb64928c
