### ISSUE TITLE
Glitched out the skeleton dungeon

### ISSUE THREAD

**Issue by Caldiniho** [Wynncraft/Issues#7259]
Earlier today i was in a situation where it wouldnt let me progress through the dungeon so i decided to log out and let my Soul Points regen while i went out, when i logged back in i was stuck in a wall and my soul points weren't any higher, so instead of standing around i did /class and walk around trying to get out of the wall, doing so somehow made me stand on top of the dungeon
Pictures as followed
![image](https://cloud.githubusercontent.com/assets/25325619/22257958/a230f1c8-e257-11e6-809e-e998d3cea1b5.png)
![image](https://cloud.githubusercontent.com/assets/25325619/22257965/a7b98812-e257-11e6-9895-1788316efc1d.png)

**Comment by DebugMC** [comment]
Do /kill, this is a area you should not be in and can get you banned.

Also @Moe-Ronickah once again someone is saying how to get out of the map if you could remove that.

**Comment by Villageacules** [comment]
Please /kill and leave this area and spawn at the nearest town immediately, or face harsh in-game punishment.
