### ISSUE TITLE
Incorrect minecraft username on the forums site

### ISSUE THREAD

**Issue by Zoqos** [Wynncraft/Issues#7260]
My forums name is Zoqos and my minecraft name is also Zoqos; however for 2 months it has remained as my old username: nycyi. If there is anyway to resolve this please let me know. Manual username change on the forums has been removed.

**Comment by Pyromanical** [comment]
No, you can't change it, it will change on its own, it just takes a long time.

**Comment by DebugMC** [comment]
@Zoqos is has not been removed. Click your profile and theres a button to change username, I can't check where though im at school.

@Pyromanical I did it like two-three days ago.

**Comment by Pyromanical** [comment]
@DebugMC He doesn't mean forum name, he means the name of the linked account

**Comment by DebugMC** [comment]
Last I checked it auto syncs...

**Comment by LordHelmchen98** [comment]
It should auto sync but apparently it doesn't everytime. However you can't do anything to fasten the process you just have to wait.
