### ISSUE TITLE
Mummy's Rag

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7261]
The quest to get Mummy's Rag is 36 (I think or its 34) and the chestplate has a level min of 38. 

If that's intentional  I will happily close issue, but no other quest I have done has a reward you can't use.

**Comment by Pyromanical** [comment]
I'm not sure if it was intentional or not, but iirc there are other quests that have rewards that can't be used until you level up.

**Comment by Numbermaniac** [comment]
The Memory Paranoia quest does this too; even though it's level 67, the Ring it gives you cannot be used until level 69.

**Comment by AscendedKitten** [comment]
As others said, I am also quite sure that it's intended.
 That was you also have some incentive to level up.

**Comment by DebugMC** [comment]
Allright. That seems correct :P I just wanted to check.
