### ISSUE TITLE
"Corrupted" Dungeons don't show up on website list.

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7262]
https://wynncraft.com/help click dungeons

There's a corrupted infested pit and corrupted lost sanctuary yet it says there isn't.

**Comment by DebugMC** [comment]
Btw I mean Corrupted Sewers shows up, but not Corrupted Pit or Corrupted Sky Sanctuary.

**Comment by Pyromanical** [comment]
Do you mean Lost Sanctuary, no such thing as Sky Sanctuary

**Comment by DebugMC** [comment]
Right. Sorry, madethat edit now.

**Comment by DebugMC** [comment]
Got a image

![meme](https://cloud.githubusercontent.com/assets/23243364/22448580/fbc2c3e8-e71f-11e6-9550-4f2f15290e76.png)

**Comment by Moe-Ronickah** [comment]
Fixed.
