### ISSUE TITLE
i in blocks.

### ISSUE THREAD

**Issue by tolya669** [Wynncraft/Issues#7263]
I teleported and got stuck in blocks. now I can't get out of them. what do i do? my nick kfire19.

**Comment by DebugMC** [comment]
Do /kill with 5 or more SP. Also please close the issue :P 

(Its a duplicate with a easy fix)

**Comment by AscendedKitten** [comment]
You can get out by using /kill in case you have 5 or more soulpoints

**Comment by DebugMC** [comment]
Would help though if you stated if you teleported by a spell or teleported from a quest/area/etc
