### ISSUE TITLE
Weapon skin problem?

### ISSUE THREAD

**Issue by JeffTheNub** [Wynncraft/Issues#7265]
Hi there, It's JeffTheNub and I'd want to report a problem about the weapon skin texture. I always want to know why are the weapon skins having "Glitched block" Texture ( A block which's made of purple/pink and black squares. But the weird thing is the weapon skin works for everyone and I have no clue why is this happening to me. I've tried everything (including reinstalling the wynn resource pack) trying to fix this and nothing changed. Can anyone tell me how to fix this?

**Comment by LordHelmchen98** [comment]
Weapon skins are shown as glitched blocks in 1.8 because 1.8 is not compatible with those skins. In order to be able to see the skins you have to use 1.9+.

**Comment by DebugMC** [comment]
as @LordHelmchen98 said, you can only  see them on 1.9+
