### ISSUE TITLE
Item Buyer lore on non-buyable items (Frame)

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7266]
#7186 DebugMC, please make that a separate issue report. -Moe

was about this, if you click the bottom row of a item buyer (especialy a dungeon scroll one) you can click nothing to see lore of the prices of items.

All you have to do is go to a dungeon scroll merchant, and click the bottom row of the gui (It has to be under an item) now the "Click an item to buy it" has the lore of 'Cost:  2 (Dungeon Name) fragment' or something along those lines, im not on mc rn so I can't check its msg

**Comment by DebugMC** [comment]
Also I can't remember exactly, but im pretty sure clicking the middle of the top row (where it shows an icon depending on merchant) does the same thing. Like on a Junk Buyer (or whatever its called) you click the flesh at the top.

**Comment by Pyromanical** [comment]
Do you mean merchant or item buyer or both?

**Comment by DebugMC** [comment]
Pretty sure all merchants.

**Comment by 0x0000null** [comment]
Can't seem to make it happen on emerald merchants, not sure about other ones

**Comment by DebugMC** [comment]
I got it on a potion+dungeon merchant so far

**Comment by DebugMC** [comment]
@AscendedKitten do you know if this is just client-sided? I have not tried to buy the item frame.

**Comment by Moe-Ronickah** [comment]
I believe that this was fixed in the last code update.
