### ISSUE TITLE
Restart After Gave NPC Item

### ISSUE THREAD

**Issue by FloatingGoat** [Wynncraft/Issues#7268]
So I accidentally gave an NPC his item as the server restarted and it didn't update my quest book... So is there a way I can get the item back to give to him or have my quest book updated?
I was on Finding the Light quest and I gave Damien his medicine as the server restarted but didn't get my quest book updates so I can't move on with the quest...
Thank you :D

**Comment by ColinRioux** [comment]
Try `/fixquests`. If that doesn't work, unfortunately, you'll have to level up another class and do the quest to get the item. Although that may suck, the Wynncraft team doesn't return items to maintain fairness among all the players. Sorry.
