### ISSUE TITLE
Lost my Legendary Shadow of Beast bow

### ISSUE THREAD

**Issue by n8kennedy100** [Wynncraft/Issues#7269]
I was doing the underworld crypt quest and I accidently dropped my bow onto the boat. Because the boat is a moving object the bow clipped through the boat and fell into the water and was unreachable due to people teleporting if they jump into the water. I could use an admin to maybe give it back or give me the item to buy another would be amazing.
Ign: djcg

**Comment by ColinRioux** [comment]
Wynncraft enforces a strict no refund policy. What this means is that you won't get your item back. Although this may seem unfair, it actually maintains fairness among the player base.
