### ISSUE TITLE
Eye of the Storm: Is the Pit of Despair NW or NE? (Possible typo)

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7270]
![2017-01-27_14 52 01](https://cloud.githubusercontent.com/assets/5206120/22360072/b62aaa20-e4a0-11e6-97da-02e34ce01f8b.png)

See screenshot. Text says North-West, but if that's the Pit it's referring to, then that's NE according to the game. Or is that not the right place?

**Comment by DebugMC** [comment]
Id say its more of a typo/error in text.

**Comment by AckroWynn** [comment]
Thanks for pointing that out! Fixed.
