### ISSUE TITLE
Flight in Distress: Commas missing in quest book coordinates

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7271]
See screenshot:
![2017-01-27_15 39 28](https://cloud.githubusercontent.com/assets/5206120/22364490/066f22a2-e4c6-11e6-8a44-1f1a54334675.png)

**Comment by DebugMC** [comment]
gasps

**Comment by AscendedKitten** [comment]
Thanks for the submission, the issue has been resolved!
