### ISSUE TITLE
Flight in Distress: 3 typos in messages

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7272]
1: "Quest Book Updated" is usually always with a capital letter at the start of each word, everywhere else.
2: Message 6/8: "using me **to** make their ship more secure"; "to" is missing.
3: Same as 1.
![2017-01-27_18 20 19](https://cloud.githubusercontent.com/assets/5206120/22364509/23acae8e-e4c6-11e6-881a-b82225b5f11c.png)
![2017-01-27_18 24 34](https://cloud.githubusercontent.com/assets/5206120/22364522/3527bf46-e4c6-11e6-9752-45e949b4a36d.png)
![2017-01-27_18 37 50](https://cloud.githubusercontent.com/assets/5206120/22364543/5ce34c6c-e4c6-11e6-985f-7c98c949671a.png)

**Comment by DebugMC** [comment]
wot

**Comment by AscendedKitten** [comment]
The typos were fixed, and the changes should apply once an update is pushed. 
Thanks for reporting the issue!
