### ISSUE TITLE
Meaningful Holiday

### ISSUE THREAD

**Issue by Onuants123** [Wynncraft/Issues#7273]
Hello! I'm stuck in the meaningful holiday quest. In the part, where Nick speaks to the ball quests, the server restarted and now I'm stuck. Any help?

**Comment by DebugMC** [comment]
Yeah :P do /kill with 5 or more SP (Or use a scroll)

**Comment by Imaxe** [comment]
Use a teleportation scroll or do /kill if you have 5 or more soul points and return to the ball and exit. The cutscene should play :)

**Comment by Onuants123** [comment]
Oh, thank you!
