### ISSUE TITLE
Meaningful Holiday NPC Dupe

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7274]
I Quite literally mean what the title says, you can dupe the npc ´nick´. When you have to get the food in ternevas you stand on a tripwire. If you just run on it and off then back on constantly (run off and on of it a lot) you can have up to 5 nicks talking at once. Also it says  _EXECUTED_ after each time you hit it. 

Also, I'm not asking for a refund, but I did the quest on my archer + mage and got santa boots, but when I did it on my assassin and warrior I didn't get it ( I don't even need them)

**Comment by Pyromanical** [comment]
Did you do the quest on assassin/warrior after the winter update/wynnter fair was removed?  You only get the items if you do the quest during the season.

**Comment by DebugMC** [comment]
Ah, didn't know that. Doesn't matter though :P

**Comment by DebugMC** [comment]
The npc still can be spawned constantly though. If needed I can show someone, but only if they are doing the quest. I don't have any classes near 34 who haven't done/can do it

**Comment by Pyromanical** [comment]
I can confirm that this has happened to me as well

**Comment by DebugMC** [comment]
yay

**Comment by DebugMC** [comment]
woops xD

**Comment by DebugMC** [comment]
It is also very hard to get nick to appear in the first place sometimes.

**Comment by Moe-Ronickah** [comment]
Too old to matter, as it was a temporary area.
