### ISSUE TITLE
Wynncraft API docs are outdated

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#7275]
The item database API doesn't seem to work for me. Am I doing something wrong?

The **"example request"** on [this page](https://docs.wynncraft.com/public/items/) shows:

>     https://api.wynncraft.com/public_api.php?action=items&command=75

However, for me, this returns:

>     {"error":"Invalid action"}

If this is intended, the API docs should be updated.

**Comment by Pyromanical** [comment]
https://forums.wynncraft.com/threads/wynncraft-public-api.127085/
This thread has the current API format on it.
The docs should probably be updated, though.

**Comment by 0x0000null** [comment]
So, the docs are just going to be left outdated?
