### ISSUE TITLE
I've lost my bow

### ISSUE THREAD

**Issue by LittleBangTheory** [Wynncraft/Issues#7276]
I have a big problem: i opened a chest in the forest and when I taken the emeralds in, I realized my bow wasn't in my inventory, not on the floor too... Nowhere. I just disappeared. I think a bug move the bow in the chest but it remained invisible.

**Comment by LordHelmchen98** [comment]
Unfortunately Wynncraft enforces a strict norefund policy which means you wont get your bow back.
Is it possible you accidentally dropped it? If you havent already you should change your drop-key to something that cant be pressed accidentally unlike 'Q'.
