### ISSUE TITLE
API returns 429 Too Many Requests despite being well below the limit

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#7277]
According to [this forum post](https://forums.wynncraft.com/threads/wynncraft-public-api.127085/), the rate limit for the Wynncraft API is **250 requests per 10 minutes**.

I am occasionally getting HTTP Error 429 (Too Many Requests) even though I am well below that limit.

I am only sending 1 request every 5 minutes (**2 requests/10min**).

|<img width="894" alt="too many requests" src="https://cloud.githubusercontent.com/assets/16504771/22392547/5457486c-e4af-11e6-91a0-e5dafe3c92fc.png">|
|:--:|

I adjusted my script to send 1 request every 15 minutes (**<1 request/10min**) and I am still getting this error every now and then.

I am not using a proxy, and I am certain that there are no other requests coming from my IP address.

**Comment by Numbermaniac** [comment]
That 429 error is annoying. I get it a lot on the map, and sometimes on player profiles, despite not having loaded a Wynncraft page for the last hour. Often results in a blank profile, or not updating my location on the online map.

**Comment by ColinRioux** [comment]
Could you define occasionally? Also could you be more specific on what your script does? I need some more context.

**Comment by 0x0000null** [comment]
I wrote a test script that sends a request to the Wynncraft API every five minutes. The error seems to happen every ~3-10 requests.

```python
#!/usr/bin/env python3
import sys
import time
import urllib.request as url

URL = 'https://api.wynncraft.com/public_api.php?action=playerStats&command=Salted'
DELAY = 300  # seconds

while True:
    try:
        last = time.time()
        print('[%s] Sending request... ' % (time.strftime('%H:%M:%S')), end='')
        sys.stdout.flush()
        response = url.urlopen(URL)
        if response.code // 100 == 2:
            print('\033[1;32m%d %s\033[m' % (response.code, response.msg))
        else:
            print('\033[1;31m%d %s\033[m' % (response.code, response.msg))
    except BaseException as e:
        print('\033[1;31m%s: %s\033[m' % (e.__class__.__name__, str(e)))
    try:
        time.sleep(last + DELAY - time.time())
    except KeyboardInterrupt:
        break
```

**Comment by ColinRioux** [comment]
You shouldn't be given a 429 error based on what you're doing, but I suggest only sending an API request when you need it. I don't know the ins and outs of the current setup (because it's not my job to maintain it), but like you said there is probably something with the rate limit. 

Is it possible that you have multiple instances of this test script running? (I doubt it, but it's always good to confirm). 

I also have no problem with the rate limit, except I don't do the request on a timely basis, it's more when someone wants player information. This is how Wynnapps works as well. But I guess if you want a program which updates in real time, this issue isn't helping. I'll look into it.

**Comment by 0x0000null** [comment]
Nope, there's no other instance running on my system.

```
$ ps -Aa | egrep -i 'python|wynn'
97185 ttys000    0:00.00 egrep --color=auto -i python|wynn
```

**Comment by AscendedKitten** [comment]
Not issue related, but I'd recommend you to cache all API results to avoid that problem. It also increases performance, and updating a player's data can be done in longer intervals.

**Comment by 0x0000null** [comment]
Issue seems to be fixed!

|<img width="444" alt="screen shot 2017-04-02 at 9 40 19 pm" src="https://cloud.githubusercontent.com/assets/16504771/24595614/0919c84a-17ed-11e7-92b3-958d13835321.png">|
|:--:|
