### ISSUE TITLE
Dungeon Scroll Merchant shows prices on the glass panes

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#7280]
<img width="2560" alt="screen shot 2017-01-28 at 10 03 33 am" src="https://cloud.githubusercontent.com/assets/16504771/22398614/2ec7e07e-e541-11e6-9ce2-5557bdf5efbb.png">

If you click on a glass pane on the border of the Dungeon Scroll Merchant inventory, prices will erroneously appear on the bottom row of items. I've only tested this in the Dungeon Scroll Merchant in Detlas.

**Comment by DebugMC** [comment]
Dupelicate of #7266 :P ty for image tho
