### ISSUE TITLE
A problem with a quest.

### ISSUE THREAD

**Issue by HiddenKuni** [Wynncraft/Issues#7281]
Currently my friend Delsin123 and I have been question quite a lot and we have come across a quest my friend can't seem to do, it's the Bigfoot quest. For some reason he can't seem to get the Bigfoot hair from Tolem, he has all the missing cow pieces but we can't seem to figure it out. If you could help us that would be greatly appreciated.

**Comment by HiddenKuni** [comment]
Questing*

**Comment by Pyromanical** [comment]
What does your quest book say?

**Comment by ColinRioux** [comment]
https://wiki.wynncraft.com/index.php?title=The_Shadow_of_the_Beast . Have you read the wiki?

**Comment by HiddenKuni** [comment]
The quest tells him to return the items back to dereg but for some reason the hair has disappeared from his inventory, we have checked every possible place, and he said he had it after we fought big foot and when we had gotten to Dereg and we turned In the quest the hair disappeared and only I was able to turn it in. The only thing I can think of is that it glitched.

**Comment by Pyromanical** [comment]
Do /fixquests
This should give the hair back, and then you should be able to turn in the quest.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
