### ISSUE TITLE
Flight In Distress Bug

### ISSUE THREAD

**Issue by viewtheboo** [Wynncraft/Issues#7283]
I'm level 75 and wanted to start the Flight in Distress quest but it's not letting me. It just says "Can I see your passport, please? Oh, without a passport, I'm afraid you can not board." but according to the wiki it says it should say something different and start the quest. PLEASE HELP! (BTW my ign is ViewTheBoo)
![2017-01-28_19 26 21](https://cloud.githubusercontent.com/assets/25409920/22400924/d87d19f6-e58f-11e6-8fc8-38f699b3ddc9.png)

**Comment by ColinRioux** [comment]
As said in the description, you need to complete https://wiki.wynncraft.com/index.php?title=Acquiring_Credentials and bring the dusty passport (quest reward) to the Passenger Controllant to start the quest.
