### ISSUE TITLE
Aldorie's Secret Part II

### ISSUE THREAD

**Issue by FrostyDragonz** [Wynncraft/Issues#7285]
I have completed the entire Aldorie's Secret II quest, and my quest book says to return my Elven Medallion back to Kansard, but every time I do she says, "You may now enter Aldorie Town! Go out, explore it and enjoy!". I do not know what to do, or how to turn this in so I am assuming it is glitched or bugged.

**Comment by FrostyDragonz** [comment]
![screen shot 2017-01-29 at 3 39 58 am](https://cloud.githubusercontent.com/assets/25413986/22403165/a47bcd56-e5d4-11e6-8adb-3447aea55bf1.png)
![screen shot 2017-01-29 at 3 39 45 am](https://cloud.githubusercontent.com/assets/25413986/22403166/a9f1b692-e5d4-11e6-908f-f3a85433ded5.png)
The first one shows I have the Medallion and the second one shows what my quest book says

**Comment by Pyromanical** [comment]
I think that is the wrong Corak and Kansard, you were supposed to give it to the Corak/Kansard at the end of the dungeon thingy, not the original ones from part 1.

**Comment by FrostyDragonz** [comment]
Oh, I'll try that, Thanks for the help.

**Comment by BlackbirdMC** [comment]
As Pyromanical said, the right NPCs (Corak/Kansard) for "Aldorei's Secret Part II" quest are located at the end of the dungeon.

Please let us know if the issue occurs again after talking to the right NPCs, thank you :)

**Comment by FrostyDragonz** [comment]
Yeah, I was blind and didn't see them, sorry
