### ISSUE TITLE
No Items

### ISSUE THREAD

**Issue by GamesHoly** [Wynncraft/Issues#7286]
When I log on to wynncraft all of my items are gone and I have tried restarting my game but nothing happens (and this has happened to me 6 times in the past week)

**Comment by thecoolkogut4** [comment]
do you think that someone else could  have access to your MC account? you should probably change the password

**Comment by Pyromanical** [comment]
Do you mean no items on your character or no items on your character and in your bank?  If you only are missing items on your character you probably died while afk and lost all your items.

**Comment by AscendedKitten** [comment]
Did you click any links sent to you via chat, promising e.g a minecon cape? 
If so, please immediatly contact a moderator, so your account can be locked until you've changed your password / made security changes.
Sadly the items can't be returned, since Wynncraft enforces a no-refund policy.

**Comment by Villageacules** [comment]
Due to extreme lack of activity, no response, and the no-refund policy, I'm closing.
