### ISSUE TITLE
Indentifier glitch

### ISSUE THREAD

**Issue by Ifly2m** [Wynncraft/Issues#7287]
So basically, I was doing the quest by name "Beneath The Depths" And i did the quest and all, at the end I got boots, legendary ones, they're called "Abysso Galoshes" and what's important, they're a quest item. So basically they were unindentified and I went to Indentifier, and I got the boots but without thinking I clicked on them *while having a full inventory* and the indentifier said "There was no space in your inventory. I dropped your items on the ground." And there was nothing but the boots are suppose to be there. The Abysso Galoshes boots are gone, and yes I've tried looking around for them, they weren't there, they're a quest item so basically I can't drop them so if the merchant drops them, they disappeared, and I do not know how to get them back. so basically can someone help?
![2017-01-29_16 45 55](https://cloud.githubusercontent.com/assets/25417701/22405419/95fbe72a-e642-11e6-86b3-c9910546c73b.png)
![2017-01-29_16 46 20](https://cloud.githubusercontent.com/assets/25417701/22405420/970b9b7e-e642-11e6-99cd-c51fd76f037b.png)

**Comment by Pyromanical** [comment]
Do /fixquests with an open inventory slot, you should get them back.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
