### ISSUE TITLE
Guild War Pets

### ISSUE THREAD

**Issue by thecoolkogut4** [Wynncraft/Issues#7290]
This is a new bug I've recently noticed. I'm well aware that guilds are 99.99% completely bugged but I just thought that I would share a new one that hasn't been posted for the devs to fixed for when guilds get re-written. If you have an armour stand pet *I've only tested it with the three that I have* they will not spawn in into wars, but normal pets (iron golem, MC mobs...) will. 

![image](https://cloud.githubusercontent.com/assets/8689385/22435534/67c9589a-e6ee-11e6-83a4-7cef35245faf.png)
the three pets shown  are penguin, grumpy old man, and the tiger.

**Comment by DebugMC** [comment]
It happened to me too with my pohtaytoh + fire dragon

**Comment by BlackbirdMC** [comment]
It also happens when you teleport (Mainly teleport regions) your pets disappear along with its name tag, particle effects and step sounds stay.

I believe it's not guild side, perhaps it has something to do with the pet system itself?

**Comment by thecoolkogut4** [comment]
@BlackbirdMC  in guild wars all npc's get removed ( and I'm guessing armor stands get removed too)

**Comment by JackyKit123** [comment]
@thecoolkogut4
Probs cuz guild war server and nether are outdated for the new pets

**Comment by thecoolkogut4** [comment]
This is still an issue, I just tested this 5 minutes ago.
