### ISSUE TITLE
Aldorei's Secret Part I: Typo in Elrund's dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7291]
Message 2/6: "thank **so you** much" should be "thank you so much":
![2017-01-28_16 22 50](https://cloud.githubusercontent.com/assets/5206120/22446505/44e5e45c-e7a1-11e6-8680-c15bc3da80e0.png)

**Comment by BlackbirdMC** [comment]
Fixed.

Thank you for the report :)
