### ISSUE TITLE
Purple and Blue: Typo(?) in Korun's dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7292]
Message 5/7: "gavel" should probably have a capital "G":
![2017-01-30_15 08 25](https://cloud.githubusercontent.com/assets/5206120/22447201/4297ecc8-e7a5-11e6-9b55-c8610babcedd.png)

**Comment by BlackbirdMC** [comment]
Fixed.

Thank you for reporting :)
