### ISSUE TITLE
The Hunger of Gerts I: Typo in Cikal's dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7293]
Message 11/11: "Gert's" shouldn't have an apostrophe.
![2017-01-30_18 04 34](https://cloud.githubusercontent.com/assets/5206120/22447453/ba222348-e7a6-11e6-8cd2-788605906c35.png)

**Comment by AscendedKitten** [comment]
Thanks for reporting the issue! It's been fixed, and changes will be pushed once an update is released.
