### ISSUE TITLE
Hunger of Gerts II: Typo (I think) in dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7294]
Message 7/8: "gert" should have a capital "G".
![2017-01-31_11 32 15](https://cloud.githubusercontent.com/assets/5206120/22450061/4351400c-e7b8-11e6-9378-02b58ccc7214.png)

**Comment by AscendedKitten** [comment]
The lower-case "gert" seems to be used a lot throughout the quest, I'll ask the GM who created the quest to make sure.

**Comment by AscendedKitten** [comment]
Sorry, took a while. The lowercase 'G' is intended, and all the others will be changed once an update is pushed.
