### ISSUE TITLE
Poison

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7296]
In the nether, if a player has a really high poison they can kill you multiple times in 1 hit. (I have 5k hp on my mage, my friend _Leg will kill me, kill me again, then half my health. Thats 1 hit for 3 kills, this seems kind of broken

**Comment by Pyromanical** [comment]
This is known, this happens in duels too.  Also, the nether is broken and completely unfair.  And this is a dupe issue I think

**Comment by ColinRioux** [comment]
Similar to #7090. Moved your comment here into that post. Please don't make another issue.

**Comment by DebugMC** [comment]
Kk.
