### ISSUE TITLE
Totem Damage bug?

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7297]
I'm really not sure what to call this, but I realised when grinding when doing smoke bomb (or whatever the ninja one is called) onto a group of mobs from a totem that only ones that did not have particles were being damaged. Once my totem ran out, I spammed smoke bomb and it did damage, but all mobs from totems were just ignoring my smoke.

If it helps, I tried this in multiple places. The place in particular I was grinding was the cave  by lusuco with the statue if that helps.

**Comment by DebugMC** [comment]
Has anyone tested? It is still happening to me..

**Comment by DebugMC** [comment]
Can confirm it as an issue, got a ton of ninja's to smoke bomb some mobs that were from totems, no damage was happening

**Comment by Moe-Ronickah** [comment]
RESOLVED
