### ISSUE TITLE
Glitch with my attack effect

### ISSUE THREAD

**Issue by gnltmd0131** [Wynncraft/Issues#7298]
my IGN is Yu_Shana and i have a glitch with my attack effects.
i cant use my attack effects on every class except mage (mage seems fine with all effects)
plz fix this asap :/

**Comment by Pyromanical** [comment]
By can't use, do you mean you get an error when you try and use the effect, or you can use the effect you just can't see it?

**Comment by DebugMC** [comment]
Try to turn your particles up (in video settings)

**Comment by DebugMC** [comment]
Also for assassin+warrior its a curved line by your feet. Depending on the particle it can be hard to see, for example you can't see enchant particles when you are on decreased particles, but you can on all.

**Comment by gnltmd0131** [comment]
i can use the effect but i cant see it (idk but mage is normal)
and i turned the particles setting to all already also ik the all classes particles form
i tested on two computer but same thing happened

**Comment by Pyromanical** [comment]
Are you sure you are looking in the right place?  Also, is it all attack effects or only one specific effect?
They work on all classes for me, idk why they wouldn't work for you.

**Comment by DebugMC** [comment]
Depending on the effect, it can be harder to see. Also hit f3, look on the left top it should say "P: (number)" when you attack does this number go up? If so that means the particles are displayed you just are not seeing them.

**Comment by DebugMC** [comment]
@gnltmd0131 what particles appear when you attack? Smoke?

**Comment by Yushana12** [comment]
@DebugMC No response is made even if I choose it. .

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
