### ISSUE TITLE
All my stuff is unindentified after i got unbanned

### ISSUE THREAD

**Issue by ezlmfao** [Wynncraft/Issues#7299]
So I was banned 3 years ago and yesterday i got unbanned. Now all of my stuff is unindentified and I lost my armor. What do ido

**Comment by Trixter313** [comment]
This is intended, there was an update that drastically changed items and
identifications so everyone's items were unidentified.

Welcome back to the server! Please read this thread to get up to speed with
any new rules for the forums and for ingame.
https://forums.wynncraft.com/threads/game-forum-rules.111874/

Thank you!

**Comment by ezlmfao** [comment]
I dont have any emeralds to get them back May i please get them unindentified or get emeralds?
