### ISSUE TITLE
Boat Travelling Bug

### ISSUE THREAD

**Issue by MarcieKing** [Wynncraft/Issues#7300]
Everytime i travel by boat it glitches out and there are tripwire hooks on the floor and barriers and the boat just doesnt take me anywhere so i had to kill myself twice please fix this

MC: MarcieKing
Skype: KingRektFace
World: 8

**Comment by DebugMC** [comment]
World name is important, the rest isn't :P For anyone who does not understand, he means the sea skipper. 

Also duplicate of #6498 #6655 #6671 #6877 #6937 #7008 (7008 especially!) #6724 #6721 lol lots of issues

**Comment by DebugMC** [comment]
Wynncraft's github now has 7k closed issues :O
