### ISSUE TITLE
No servers

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7301]
This is a known bug,  but no duplicates to my knowledge.

Sometimes in lobbies compasses show no servers (It doesn't fix on relog, switching lobbies does fix it)
You can /lobby to fix this, but its just a weird bug that on some lobbies there's no servers.

**Comment by DebugMC** [comment]
I mean its not really a problem, you can just fix it by switching servers. To my knowledge this is on lobby 3 usually but im not 100% on that

**Comment by BlackbirdMC** [comment]
I experience this inconvenience as well, I believe it only shows up in specific lobbies (Perhaps when they are restarted everything goes back to normal).

As you said, /lobby connects you to another lobby that isn't experiencing this bug, you can then browse any server you'd like.

**Comment by DebugMC** [comment]
Right, its just that I go in lobbies like that and people just sit there talking and are like 'is the network dead?' so I go on and say 'just do /lobby'

**Comment by thecoolkogut4** [comment]
duplicate of #6635

**Comment by DebugMC** [comment]
Oh, well then.
