### ISSUE TITLE
[reopen] Trapped at the Detlas ball after restart

### ISSUE THREAD

**Issue by fralix** [Wynncraft/Issues#7302]
Bug #7105 is still present!
My client crashed at the moment I wanted to leave the ballroom and after a reconnect, I got trapped in this barrier area. 
Current position: 10029 / 35 / 5421

**Comment by DebugMC** [comment]
@fralix this is a bug with minecraft itself, just do /kill with 3+ soulpoints (I recommend 5 though)

**Comment by DebugMC** [comment]
Also this is just a duplicate, you could just post on that one. Please close the issue :P

**Comment by AscendedKitten** [comment]
I am sorry that the problem persists, but using /kill with 5 or more soulpoints is the best solution at the moment. (unless you have a teleportation scroll; use those then of course!)
