### ISSUE TITLE
Possible typo in Hunger of Gerts II: Captured Gert's dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7303]
3/5: "Cut other gert in pice"? I know Gerts are bad at spelling, but I'm not sure if "pice" is intentional though.
![2017-01-31_12 07 09](https://cloud.githubusercontent.com/assets/5206120/22574353/8622a87a-ea02-11e6-857f-5aa58312c849.png)

**Comment by AscendedKitten** [comment]
Thanks for the report! The typo has been fixed, and changes will take effect once an update is pushed.
