### ISSUE TITLE
Temple of legends

### ISSUE THREAD

**Issue by wootxbeer** [Wynncraft/Issues#7304]
This is really unfair and upsetting. A few other people and I killed the Corruptor of Worlds for the 3 times in a row. Each time one person got two drops and I got zero. This is why we redid the battle so many times. It's not fair and I cannot do the battle on my own. Each time I did a decent amount of damage so I don't know why I didn't get a drop. If you need proof you can ask these people: **Venman** and **RogP**. My IGN is **Laputaa**.

**Comment by Pyromanical** [comment]
The boss mechanic is designed so you have to do 15% of damage to the boss to get the drop.  This is to stop you from getting carried by higher level players.  As long as you do 15% of the damage, you will get a drop.  If you can't do 15% of the damage, then try and get stronger gear so you can do more damage.

**Comment by wootxbeer** [comment]
i definitely did more than 15% damage tho ;-; there were only three of us and it doesnt make sense

**Comment by Pyromanical** [comment]
You should have been able to pick up one of the corrupted hearts then.  If 3 dropped, then 1 should have been yours.  Sometimes they can get stacked together on the ground and someone might have picked up 2 that way.  Sadly, you probably will just have to kill it until you are able to get one of the drops.

**Comment by Numbermaniac** [comment]
Usually, when these things drop, they can't be picked up by anyone else other than the person they "belong" to, unless that person doesn't pick it up for a while. Did you leave it for too long, perhaps?

**Comment by Pyromanical** [comment]
They fixed the leaving it for too long @Numbermaniac

**Comment by Numbermaniac** [comment]
Oh, is the drop an untradable item? @Pyromanical

**Comment by Pyromanical** [comment]
Yes, the corrupted heart from CoW is untradeable @Numbermaniac

**Comment by ColinRioux** [comment]
@Numbermaniac Essentially it's a mechanic where the drop is assigned to a specific player, where you can no longer wait 30-40s to pick up the drop for another player. The player it's assigned to either picks it up or it de-spawns. 

And the CoW heart has been an untradable item to begin with, so it's unrelated.

**Comment by Numbermaniac** [comment]
Oh, for some reason I thought you were talking about the Temple of Legends boss altar! Right, it's the CoW fight...I'm stupid, of course that's untradable. Whoops.

**Comment by ColinRioux** [comment]
Reported by @wootxbeer as fixed.
