### ISSUE TITLE
Elemental Exercise glitch

### ISSUE THREAD

**Issue by Stiffisharc567** [Wynncraft/Issues#7305]
I am currently working on completing the Elemental Exercise quest. When I try to break the root to get into the cave the Root entity does die, but when I kill it nothing happens and i just wait for it to respawn and kill it again and I cant get past the root. I don't know what is supposed to happen when I kill the Root, but I do know that I am supposed to be able to get past it but I cant.

**Comment by Stiffisharc567** [comment]
It fixed itself when I relogged, but this still seems important.

**Comment by Pyromanical** [comment]
This seems like a one off thing, as nothing like it has been reported, and relogging fixed it.  However, someone could probably look into it.

**Comment by DebugMC** [comment]
@Pyromanical its not, some1 just reported it.

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
