### ISSUE TITLE
Too many flower pots (I think)

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7306]
Not 100% on this, but I don't think there is supposed to be so many flower pots here. (Coords are 783 91 -2164 ) 
See [here](https://gyazo.com/b5a0030fddea821e8ebbd2707c89d335) (I saw this and was like eh)
But then I saw [this](https://gyazo.com/3aeb34b91adeea89786122cd895436fe) and was like uhhh
Then finally[ this](https://gyazo.com/37d242022e04dac5e65798c1e3852149) and I gave up. This is not meant to be like this. I think.

**Comment by DebugMC** [comment]
Unless the farmer makes flower pots for a living, I don't think this is correct :P

**Comment by AscendedKitten** [comment]
I know it might seem strange, but it's intended.
![unbenannt](https://cloud.githubusercontent.com/assets/17948365/22608777/a10b6080-ea5e-11e6-818e-f5d7ea4563af.png)

**Comment by DebugMC** [comment]
xD gg
