### ISSUE TITLE
Stuck in a place (Help)

### ISSUE THREAD

**Issue by SonicwarBR** [Wynncraft/Issues#7308]
Hello, I was trying to do the Lord of the Clock quest but then I walked into some kind of piston door and now I'm stuck here and can't play anymore. I don't know if its possible to report my problem to an Admin or someone to help me because I don't have a shout or whatsoever. My location at the moment is:
X: 52.700
Y: 67.00000
Z: -1311.700

**Comment by LordHelmchen98** [comment]
As long as you have 5+ soul points you can do /kill in order to get you unstuck. You will respawn at the nearest city. After you killed yourself you will have to do that part of the quest again.

**Comment by DebugMC** [comment]
Lord Of The Clock has no piston doors ._.

**Comment by LordHelmchen98** [comment]
@DebugMC There are two. One when you enter AND one when you exit Gundalfs library......

**Comment by DebugMC** [comment]
Oh true...

**Comment by AscendedKitten** [comment]
As @LordHelmchen98 said, it's recommended to use /kill with 5 or more soulpoints in order to respawn.
