### ISSUE TITLE
Horse enemies are a nightmare for Archers

### ISSUE THREAD

**Issue by forrester-marc** [Wynncraft/Issues#7309]
Enemy mobs based on the Minecraft horse can be (very briefly) mounted by right clicking.  This takes priority over firing bows for archers, making close range battles with horses a confusing mess of random teleportations.  It's especially problematic in the Tower of Ascension.

**Comment by DebugMC** [comment]
This should not be, I tried did ToA last night, the game won't let you mount them at all really. It just turns you. Known bug though so please close :P

**Comment by AscendedKitten** [comment]
Sadly it seems to be a default minecraft mechanic, which might be difficult to change. 
(see #3143)
