### ISSUE TITLE
Don't have permission for this area

### ISSUE THREAD

**Issue by wizardcheetah55** [Wynncraft/Issues#7310]
Level 86 - and still spend time in Troms. All of a sudden, when I went outside Troms to a nearby chest, the message was "you don't have permission for this area." Since I've spent time in the area since I was Level 50, I wonder what caused this. 
Thank you!

**Comment by AscendedKitten** [comment]
That's due to an interaction with certain item materials and chests, as they are used as tools by an installed plugin players don't have access to. Simply switching to another item / empty slot should fix it!

**Comment by wizardcheetah55** [comment]
Thanks - I was able to get into the chests, but will it always be this way?- That I have to move to an open box to open a chest? I've never had to do that before.

**Comment by LordHelmchen98** [comment]
It only happens if you are using a retextured half slab and apparently only if you threw that half slab out of your inventory once and then picked it up again but if a weapon breaks it will stay broken permanently.

**Comment by wizardcheetah55** [comment]
Don't know what a retextured half slab is. Actually, I don't know what a
half slab is either.

When I have my Bistmuthinite wand I get the “you don’t have permission”
message. I’ve used that wand for months. When I switch to my old Ethereal,
the message does not come on. Any thoughts as to why this is happening?

Stan Emert
206-250-9839
Skype: stan.emert

**Comment by LordHelmchen98** [comment]
Wynncraft has its own resourcepack and in that resourcepack lots of blocks got a different texture. Most of the weapons are actually wool blocks or wood blocks but with the resourcepack it looks like Ethereal or Bob's Mythic or something else. Some weapons are slabs (http://minecraft.gamepedia.com/Slab) and as AscendedKitten said, the slabs interact with a plugin unintentionally and that's what causes those permission messages.
