### ISSUE TITLE
Lost Sanctuary Dungeon: cannot progress through the dungeon when tnt is placed in the hopper.

### ISSUE THREAD

**Issue by trey1029** [Wynncraft/Issues#7311]
The first wall won't blow up when tnt is placed on the hopper

**Comment by AscendedKitten** [comment]
Try switching server or using a different (lower) version; this hasn't been reported before, so I don't think it's a permanent issue.

**Comment by ColinRioux** [comment]
I have tested this issue on our tested server (using version 1.9.2), and have had no problem with proceeding through the whole dungeon numerous times. Unfortunately, the changes to Lost Sanctuary won't be in effect until the next map push (probably Corkus update). Sorry for the inconvenience, but thank you for reporting this issue.
