### ISSUE TITLE
3 Miscellaneous Typos

### ISSUE THREAD

**Issue by RikioST** [Wynncraft/Issues#7312]
![2017-01-26_20 21 17](https://cloud.githubusercontent.com/assets/17153769/22614898/60c62234-ea2d-11e6-9de9-806b79040884.png)
Too. (Starting dialogue in Out Of My Mind quest)
![2017-01-29_14 12 05](https://cloud.githubusercontent.com/assets/17153769/22614896/60c381e6-ea2d-11e6-8e16-8005d9dfe6d4.png)
Is there supposed to be missing water there? (Wolf lady cave near Nesaak)
![2017-01-29_16 32 32](https://cloud.githubusercontent.com/assets/17153769/22614897/60c43348-ea2d-11e6-9f1b-4ac9f8d0ecf9.png)
Abandoned. (Some sign in Maro Peaks)

**Comment by Numbermaniac** [comment]
The first one of those was fixed in #7193.

**Comment by BlackbirdMC** [comment]
2. Fixed, thank you for reporting!

3. Fixed, thank you for reporting!
