### ISSUE TITLE
Quest:From the mountains (lvl:67)

### ISSUE THREAD

**Issue by bbrr0704** [Wynncraft/Issues#7313]
I can't get into the hole in the lake on top of mountain when I wear the breathing helmet II.

**Comment by AscendedKitten** [comment]
Please provide some more detail; is there any message? Where exactly are you trying to enter (coords)?

**Comment by bbrr0704** [comment]
http://imgur.com/a/JUczh
http://imgur.com/a/CJC1j

like this

**Comment by Pyromanical** [comment]
Have you tried taking it off and putting it back on?  Also, what does your quest book say, are you sure you are on the right stage?  I did this quest yesterday, and it worked just fine.

**Comment by bbrr0704** [comment]
ahh okay its my fault.
