### ISSUE TITLE
Fallen Delivery: Typo(s?) in Office Manager's dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7314]
4/4: "If" shouldn't be capitalised.
Also, is that a double space in 3/4 between "bridge" and "if"?
![2017-01-31_12 47 57](https://cloud.githubusercontent.com/assets/5206120/22616343/7f4c88ba-eaff-11e6-8285-c2d291c6ab24.png)

**Comment by BlackbirdMC** [comment]
Fixed.

Thank you for reporting!
