### ISSUE TITLE
General's Orders: Typo in Tylas' dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7315]
6/6: "his office **is** on the left side"; "is" is missing.
![2017-02-01_18 06 38](https://cloud.githubusercontent.com/assets/5206120/22616369/dfd78d6a-eaff-11e6-9842-62f9170ed7c5.png)

**Comment by BlackbirdMC** [comment]
Fixed

Thank you for reporting :)
