### ISSUE TITLE
General's Orders: Two typos in Lecade's dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7316]
Message 5/7: "thing" should be "things"
6/7: Should be "its" office, not "it's".
![2017-02-01_18 31 31](https://cloud.githubusercontent.com/assets/5206120/22616391/1a604f80-eb00-11e6-840b-f9a5577f8650.png)

**Comment by BlackbirdMC** [comment]
Fixed.

Thank you for reporting!
