### ISSUE TITLE
Wynnterfair posters in Troms

### ISSUE THREAD

**Issue by LordHelmchen98** [Wynncraft/Issues#7317]
I found two Wynnterfair posters and I'm pretty sure they should have been removed already because there was another GitHub thread about this, but I wasnt able to find it again. They are on both sides of the bank in Troms. 
![](http://puu.sh/tNL3A/b413d4f3ca.png)
![](http://puu.sh/tNL3h/40cc4e023c.png)
@Imaxe can you fix this?

**Comment by ColinRioux** [comment]
Those have been fixed on build for awhile now, and will be removed during the next map push (which will probably be the Corkus update).
