### ISSUE TITLE
From the Bottom: Typo in Yobon's dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7319]
1/3: "It looks like **It** has found its way home"; the second "It" shouldn't be capitalised.
![2017-02-04_17 18 00](https://cloud.githubusercontent.com/assets/5206120/22617783/260d9e98-eb21-11e6-8486-2e9d04a6f972.png)

**Comment by BlackbirdMC** [comment]
Fixed,

Thank you for reporting!
