### ISSUE TITLE
Big Bug: Duel killing

### ISSUE THREAD

**Issue by Iceloono** [Wynncraft/Issues#7321]
I was starting a new warrior class, and as I was level 9, I challenged a random Lvl 10 Mage. Now the next part I'm not sure if its my Internet or server, but the duel started and we exchanged spells. I was on low health, and tried to get close to him. After some basic attacks, he won the duel, but I used bash right after he used his basic attack and he disappeared/died. We tried to recreate this with me to make sure he wasn't trolling, and surely enough, I was killed, teleported to ragni, and most importantly, lost 2 soul points

**Comment by Iceloono** [comment]
This is probably harder to recreate with high level characters

**Comment by Iceloono** [comment]
Keep in mind, this is a random Mage, I had no control what he/she did in the duel.

**Comment by thecoolkogut4** [comment]
thorns and reflection on your Armour cause you to die (lose 2sp) in duels. I'm pretty sure this is a duplicate

**Comment by Pyromanical** [comment]
#3559 and #7090

**Comment by Iceloono** [comment]
No I made sure, no thorns or reflection, this is lvl 9. Neutral damage

**Comment by DebugMC** [comment]
@Iceloono no it is a dupe of #7090 :I I made that issue myself
