### ISSUE TITLE
Finding the Light: Message numbering changes during Ollie's dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7325]
Notice how it's 2/5 but then followed by 4/6. If the red text is a message, that's fine, but then the first two messages should be /6 instead of /5.
![2017-02-05_18 26 52](https://cloud.githubusercontent.com/assets/5206120/22624481/f309dd30-ebd0-11e6-8f55-143a1d801a4a.png)

**Comment by AckroWynn** [comment]
Fixed!
