### ISSUE TITLE
The Ultimate Weapon: Suggestion for Dodegar's dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7328]
The white text feels like it's in the wrong tense, compared to how this text usually functions in Wynncraft. May I suggest changing "said" to "says" and "perform" to "performs"?
![2017-02-05_12 57 39](https://cloud.githubusercontent.com/assets/5206120/22624527/a54d82de-ebd2-11e6-90d9-595d39c3fd5e.png)

**Comment by AckroWynn** [comment]
Fixed!
