### ISSUE TITLE
Finding the Light: Two typos in Ollie's later dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7329]
2/7: "even" is there twice in the same sentence.
6/7: "though" should be "through".
![2017-02-05_18 56 21](https://cloud.githubusercontent.com/assets/5206120/22624601/dd4c410a-ebd4-11e6-9b9b-5ea7bb0ff44f.png)

**Comment by AckroWynn** [comment]
Fixed!
