### ISSUE TITLE
Archer fly ability bug

### ISSUE THREAD

**Issue by CrazyKekssss** [Wynncraft/Issues#7332]
I have used the archer ability where you get thrown through the air, fell on a block gliched and got banned for flying. I did not have any mods hax etc.
My ingame name is CrazyKekssss.

**Comment by JuicedBananas** [comment]
Please post a ban appeal on our forums here if you want to be unbanned.
https://forums.wynncraft.com/forums/ban-appeals.84/

**Comment by LordHelmchen98** [comment]
Are you sure you got banned? Normally if something like that happens you only get kicked for flying.

**Comment by BasicallyNothing** [comment]
What Helmchen says is correct, if you were to use the escape and glitch on a block you would only get kicked for flying. You would not get banned if it didn't happen more than once.
