### ISSUE TITLE
Double Quest Items

### ISSUE THREAD

**Issue by GoDed** [Wynncraft/Issues#7333]
In my enderchest I have double the quest items and if I try to throw one out for more space it says: 'You will need this item in later quests!'. But since I have two of the quests items I dont need one of them and I want to get rid of it. Is there a way to still throw the item out?

https://gyazo.com/94f65ee84b5046d72e330b78b88fefbb

Thanks for looking at my thread :D

**Comment by Pyromanical** [comment]
Did you get those items on two different classes, or both from the same class?  If you got them from different character you will need both, so you can do quests on both characters.  If they are from the same character, you can place one in a loot chest or your daily chest, and it will delete it after you close the chest.

**Comment by GoDed** [comment]
OK, thanks!
