### ISSUE TITLE
Bug: Green Skinned Trouble 

### ISSUE THREAD

**Issue by Yinbee39** [Wynncraft/Issues#7334]
I am a level 45 Archer doing the "Green Skinned Trouble" quest. I got the item needed to complete the quest by killing the boss. But when I exited the boss area, it teleported me to a place I don't know. It is all black. I can still see my bow and everything in my item bar, but I am stuck and can't move forward or backwards or anything. It is just pitch black. Can someone help me?
![2017-02-05_12 08 24](https://cloud.githubusercontent.com/assets/25568120/22628090/e6627482-eb9b-11e6-9cef-167284dea0aa.png)

**Comment by Pyromanical** [comment]
If you have over 5 soul points, do /kill, you will respawn back in a town, probably Llevigar.  You could also use a scroll if you have one.

**Comment by Yinbee39** [comment]
Thank you so much! I will try it.

**Comment by AscendedKitten** [comment]
That's an issue with the redstone not triggering correctly, and as mentioned /kill should solve it. If the issue persists, try switching server/MC-version!
