### ISSUE TITLE
Disconnected and loss black horse

### ISSUE THREAD

**Issue by print116** [Wynncraft/Issues#7335]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

I have been disconnect because the server restarted and when I got back in I loss my black horse. Please help me get my horse back.

**Comment by Pyromanical** [comment]
Wynncraft has a strict no refund policy, so sadly you won't be able to get your horse back.  However, you can buy one from another player on the forums or in game.

**Comment by print116** [comment]
ok
