### ISSUE TITLE
Potion Making

### ISSUE THREAD

**Issue by WackyWaldo** [Wynncraft/Issues#7336]
I have 8 red mushrooms and when I go to turn them in the Assistant will not acknowledge that I have any red mushrooms. I cannot continue the quest :-:.

-WackyWaldo

**Comment by LordHelmchen98** [comment]
You probably already gave him the mushrooms but unfortunately the Assistant will always tell you this text while doing the quest. You have to enter the house kill Essren and return to the Assistant with Essrens Dusty Coat.

**Comment by ColinRioux** [comment]
Duplicate of #6437

**Comment by isaacdare** [comment]
I have a similar problem, expect Essren does not spawn inside his house.
