### ISSUE TITLE
Wheat Texture 1.11.2

### ISSUE THREAD

**Issue by RikioST** [Wynncraft/Issues#7337]
![2017-02-05_10 49 04](https://cloud.githubusercontent.com/assets/17153769/22630519/ce8e42a6-eb9f-11e6-8757-633941cfd3ab.png)
This is one of the wheat fields in Elkurn. Spot the two odd ones out? I am also playing in 1.11.2.

**Comment by ColinRioux** [comment]
The texture pack is coded for 1.8.9 not 1.11.2. Try 1.8.9 and see if it's fixed?

**Comment by BlackbirdMC** [comment]
It seems like it's showing up for 1.8.x also.

Fixed.

Thank you for reporting!
