### ISSUE TITLE
Tinemild TOTALLY wrong coordinates glitch

### ISSUE THREAD

**Issue by TBlazeWarriorT** [Wynncraft/Issues#7338]
"The Tower of Amnesia" "Talk to Tinemild in Detlas Suburb at [8574 -1206]
Unless I'm missing something, coordinate 8574 isn't even on the map. It's not just my questbook, I confirmed it with someone else.
http://i.imgur.com/JN0jeky.png

**Comment by Pyromanical** [comment]
It is x coord 85, y coord 74, not x coord 8574.  If it was one number, it would have been on one line.

**Comment by Numbermaniac** [comment]
Ok, so the mistake here is missing commas in the quest book. Typo, should be something @AckroWynn can fix.

**Comment by Villageacules** [comment]
Fixed, closed,
