### ISSUE TITLE
Lost sanctuary bug.

### ISSUE THREAD

**Issue by 2002Kenny2002** [Wynncraft/Issues#7339]
Me and my friend are in the santuary on server 5 and we could not progress due to commands not loading and tping us to the next area, just wanted to inform you to check it out.

**Comment by DebugMC** [comment]
Just do /kill with 5 or more SP (Or switch servers?)

**Comment by ColinRioux** [comment]
I have tested the dungeon on gm, and had no problem with teleportation. I was able to progress through with no problem. 

I'd try using the command `/kill` with 5 or more soul points or switching servers like @DebugMC 's suggestion. If nothing prevails, I suggest you wait for the next map push (probably Corkus update), and everything should be fixed.

**Comment by TBlazeWarriorT** [comment]
I had similar glitches on Sancuary recently too.
4, 5 and 6 tnt (on the hopper) doors were always open, boss suddenly died once (has full hp and randomly says I cleared the dungeon).
I'm not experienced on the dungeon (or on the server) but it looked really weird. At first I thought it could be some weird issue with other people doing the same dungeon at the same time, but I didn't see anyone and I do not know how the server works on that.

**Comment by Moe-Ronickah** [comment]
RESOLVED
