### ISSUE TITLE
Crates make people temporarily immortal

### ISSUE THREAD

**Issue by thecoolkogut4** [Wynncraft/Issues#7340]
first off, not too sure of a good title. if someone has one please let me know. 

If a player uses a crate and a mob kills the player, nothing will happen. the player will stay in the circle and will still be able to use the crate. The player will not get tp'ed (on death) after placing a crate.

**Comment by Pyromanical** [comment]
What happens to their health after they die?  This may be an intended feature, so people don't lose something worth real money to death, but that is entirely a guess.

**Comment by thecoolkogut4** [comment]
when you die, you spawn back with full health just as the normal system goes.

**Comment by Pyromanical** [comment]
Ohhh, I was confused.
So they still die, they just don't get tp'd to the nearest town.

**Comment by DebugMC** [comment]
Can confirm this one is true.

**Comment by AckroWynn** [comment]
We will be discussing this matter, and test it out ourselves.

**Comment by AckroWynn** [comment]
Salted has added it to his notes, and this issue might get resolved. It is not on the priority list, however, it has been noted.

**Comment by Moe-Ronickah** [comment]
RESOLVED
