### ISSUE TITLE
Seven-League Boots suddenly disappeared!

### ISSUE THREAD

**Issue by MEGANEnoKAMISAMA** [Wynncraft/Issues#7341]
Seven-League Boots suddenly disappeared.
On the way of Underwater quest
I noticed when I tried to cover a helmet.
XP bonus was + 18%.
Agility was +4.
I think the speed was about + 21%.
Will you please return it?

Sorry! I am using Google translation!

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by AscendedKitten** [comment]
I am sorry for your loss, but as already mentioned, your items can't be returned. However, I am sure some players are willing to provide a replacement when asked nicely!
