### ISSUE TITLE
All of my unique items aren't identified anymore.

### ISSUE THREAD

**Issue by Shanori** [Wynncraft/Issues#7342]
I checked if it's already been posted, but I couldn't find anything that seemed to be talking about the same issue.  Sorry if it's a repeat, but I couldn't find anything.

When I logged in recently, all of the unique/rare/legendary items in my inventory were no longer identified.  This means that I can no longer use any of my armor or weapons until I identify them again, which will be really expensive.  I haven't played in a long time, so that might be part of the problem, but this issue almost makes the game not worth playing anymore unless I start from scratch.

**Comment by DebugMC** [comment]
Yeah you prob left before gavel and now you have rejoined. Welcome back :P anyway, sorry you will have to re-identify any items, and any items with a special character like pélier (Not pelier it has to have the special e) will be broken. If I were online id give you the money to identify, but I can not be on right now :(

Anyway as I said earlier, welcome back to wynn and I hope you enjoy your stay :)

**Comment by Shanori** [comment]
@DebugMC  That's real unfortunate, thanks for the help though and the offer, but I think I'll be fine.

**Comment by DebugMC** [comment]
Allright. Please close the issue if you are okay now :)
