### ISSUE TITLE
Im Stuck! Help! (update: i got help, you can close this.)

### ISSUE THREAD

**Issue by xSamMC** [Wynncraft/Issues#7343]
Can someone please help me?, im stuck in mid air during the quest "Meaningful Holiday". right when i got the scene in the "Ball" when Nick starts to talk, the server resetted, and now im stuck in mid air and cant do anything at all. Can someone please get me our od here? i got some [screenshots]
![2017-02-07_15 22 54](https://cloud.githubusercontent.com/assets/25613726/22695568/803115a4-ed4b-11e6-8c98-9fd9ef25cda9.png)
![2017-02-07_15 40 43](https://cloud.githubusercontent.com/assets/25613726/22695665/ce6f1630-ed4b-11e6-8a89-0128edfc0fa9.png)

**Comment by DebugMC** [comment]
Right by comment click close issue :)

**Comment by DebugMC** [comment]
@xSamMC please close if you are okay now :P

**Comment by xSamMC** [comment]
Alright, thx
