### ISSUE TITLE
Quest(s) not marked on the map

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#7344]
So basically, the quests "The Canary Calls", "Enter the Dojo", "The Hidden City", "One Thousand Meters Under", "Recipe For Disaster" and "The Fortuneteller" is not marked with a book on the Wynncraft Map.

There should be a book right in the middle of the screen right here: 

The Canary Calls: https://map.wynncraft.com/#/676/64/-5020/max/0/0
Enter The Dojo: https://map.wynncraft.com/#/495/64/-5571/max/0/0
The Hidden City: https://map.wynncraft.com/#/661/64/-5070/max/0/0
One Thousand Meters Under: https://map.wynncraft.com/#/1108/64/-4555/max/0/0
Recipe For Disaster: https://map.wynncraft.com/#/949/64/-4475/max/0/0
The Fortuneteller: https://map.wynncraft.com/#/746/64/-4468/max/0/0

- Thanks

**Comment by BasicallyNothing** [comment]
If there is a format I didn't use it, sorry about that xD

**Comment by DebugMC** [comment]
Lots of quests are not on the map, sometimes intentional sometimes not. The map will be updated someday though... Soon™

**Comment by BasicallyNothing** [comment]
Fair enough, I'm not complaining as the forums is still an option.

**Comment by Pyromanical** [comment]
The map will probably updated after Corkus comes out, but if its anything like the gameplay update, it will take a few weeks for the map to actually get updated.

**Comment by Moe-Ronickah** [comment]
RESOLVED
