### ISSUE TITLE
Realm of Light: Possible typo in Aluxander's dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7345]
5/8: I think he means to say "I am **a** Heliolux" ("a" is missing).
![2017-02-06_10 53 21](https://cloud.githubusercontent.com/assets/5206120/22717005/bceba62a-edec-11e6-86ba-817252e2a182.png)

**Comment by Moe-Ronickah** [comment]
It's not an issue.  Heliolux speak of themselves the same way Q does in Star Trek.
