### ISSUE TITLE
Realm of Light: Two typos in Regulux's dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7346]
2/7: "Apologises" should be "Apologies".
5/7: There's a question mark followed by a full stop.
![2017-02-06_13 38 24](https://cloud.githubusercontent.com/assets/5206120/22717042/f375dff8-edec-11e6-8735-264ca3587113.png)

**Comment by ColinRioux** [comment]
Fixed!
