### ISSUE TITLE
??? Blue meteor puzzle wont work [Spoilers]

### ISSUE THREAD

**Issue by Shadoweagle5098** [Wynncraft/Issues#7349]
In order to get into the blue meteor, you need to complete a puzzle involving moving hay with a sickle. Kill an elf farmer to get the sickle, walk into hay to move it into a certain pattern, you know the drill. However, after trying on three multiple worlds, I haven't been able to move a single hay block. In case you're wondering, yes, I had the sickle in my hand. Please tell me if this quest has been changed or if there's I'm doing something wrong. Thanks!

**Comment by Pyromanical** [comment]
You have to get a new hay sickle each time you do it.  Were you killing the elf farmer each time, or using a hay sickle you already had?

**Comment by DebugMC** [comment]
@AckroWynn usualy I wouldn't tag you, but is it possible this part is kind of bugged? I know you need a new sickle, but sometimes the hay wont move anyway. To move it, I had to sneak jump and wait like 15s per time for it to move.

**Comment by Pyromanical** [comment]
That is just something that happens with the moving blocks puzzles in general, @DebugMC, the same thing happens on the 1000 meters under part like this.

**Comment by DebugMC** [comment]
Ah :P

**Comment by Shadoweagle5098** [comment]
All right, you're right. I got it working by doing that. While it IS tedious, at least I know what to do. thanks guys :D
