### ISSUE TITLE
Arrow storm bug

### ISSUE THREAD

**Issue by IForseeYou** [Wynncraft/Issues#7350]
Whenever I use the Arrow storm spell on a mob, it increases its health instead of taking damage.
![2017-02-08_21 24 30](https://cloud.githubusercontent.com/assets/23572916/22739355/3fbb1be0-ee46-11e6-9c6e-c86b19bd51c4.png)

![2017-02-08_21 24 35](https://cloud.githubusercontent.com/assets/23572916/22739364/45dbc0a6-ee46-11e6-97fa-551d52d4c53a.png)

The first screenshot shows the demon's initial health, and the second shows its health after I used arrow storm.

**Comment by DebugMC** [comment]
First of all, I would say you have negative lifesteal, but your using an Olux bow, so that's not a possibility. 

Does this happen always, or when you wear your specific armor, or just with that bow? 

Also note: You aren't using the resource pack :c

**Comment by IForseeYou** [comment]
I rarely use the ability, only recently. And, I don't use the resource pack because of a bad PC. I'll get 2 FPS if I have the resource pack on...

**Comment by ColinRioux** [comment]
I'd also like to note you only did 50 damage. On average, how much damage do you normally do? (if any other player could enlighten me, that'd be great).

**Comment by IForseeYou** [comment]
@ColinRioux the 50 damage was due to the poison from the bow I was using (Olux's Prized Bow).

**Comment by DebugMC** [comment]
![image](https://cloud.githubusercontent.com/assets/23243364/22802690/6e7e6504-eed7-11e6-8870-34c126f11d4b.png)


"50 Poison"

Anyway, that bow has no neutral dmg. Also, how can I see the arrows still firing in the picture, but the poison is doing dmg? Poison isn't started until after all dmg is done. 



Also very very very unlikely, but it could have done its 60s regen right when you hit it.

**Comment by IForseeYou** [comment]
The fire particles on both sides of the demon shows the range of the spell, arrow storm. And, when an arrow hits the mob, that arrow will do poison damage for only one second if you fire another arrow immediately which is what arrow storm does, obviously not all arrows will hit the mob because my aim is bad as you can see in the screenshot =p. And... The bow has neutral damage of 60 to a 100 if you look carefully...

**Comment by IForseeYou** [comment]
Another way to still see the arrows firing is obviously the blood particles showing the mob is still taking damage

**Comment by Pyromanical** [comment]
@DebugMC Where did you get that picture from?  I'm pretty certain my Olux bow has 150/3 poison, which makes sense with the picture.

**Comment by IForseeYou** [comment]
My bow also has 150/3s of poison. And, if its relevant, I added powders to the bow which reduced the neutral damage to 34 (minimum damage) - about 50.

**Comment by thecoolkogut4** [comment]
I'm pretty sure it's just the normal mob regen, but not 100%.

**Comment by AscendedKitten** [comment]
Might be that your damage using Arrowstorm was too insignificant, so the mob's health regeneration

**Comment by AscendedKitten** [comment]
Might be that your damage using Arrowstorm was too insignificant, so the mob's health regeneration was able to "outheal" it. I tested it using the same bow, and I've had no problems similiar to this one so far. 
(Sorry for the double post, mobile's acting up. Will be fixed once I can access my PC)

**Comment by DebugMC** [comment]
@thecoolkogut4 I got the picture by looking up "Olux Prized Bow" on google xD here:

**Comment by DebugMC** [comment]
So I was wrong, I posted the OLD olux' prized weapons as it has 15% loot bonus on it. So you are right c:

**Comment by Moe-Ronickah** [comment]
I'm closing this.  I've experienced this on every class.  It happens when you don't do enough damage, fast enough, just as @AscendedKitten said.
