### ISSUE TITLE
Got Kicked and lost a white horse and other items

### ISSUE THREAD

**Issue by Elemen0** [Wynncraft/Issues#7351]
I was runnin' around and looking at my loot on a lvl.7 character. I transferred my white horse onto that account using the bank and everyone got kicked and I lost everything.
Can I get some stuff back or can you fix the issue? 
Thnx

**Comment by Pyromanical** [comment]
Sadly, Wynncraft has a strict no-refund policy, so you won't be able to get your items back.  However, you can always buy the items from other players, or find a Good Samaritan who can give you some items for free.
