### ISSUE TITLE
House of Twain hopper full?

### ISSUE THREAD

**Issue by WhoviVortex** [Wynncraft/Issues#7353]
In the House Of Twain, you are required to put 3 items into a hopper to spawn a ghost. However, the items are not going in. Would there be any other reason to this? Or is it just the hopper being full? Or am I just putting it in the wrong place? Thanks.
![image](https://cloud.githubusercontent.com/assets/25668834/22794882/86ffc356-eeec-11e6-987b-2f711abfe845.png)

**Comment by LordHelmchen98** [comment]
The hoppers underneath are broken sometimes. In all likelihood the hoppers will be working on another server. So just change the server in order to do the quest.

**Comment by DebugMC** [comment]
He means if your on WC1 go on WC2 (for example) @WhoviVortex

**Comment by WhoviVortex** [comment]
Cheers guys. Appreciate the response.

**Comment by LordHelmchen98** [comment]
It its resolved you can close it now.
