### ISSUE TITLE
Breathing Helmet II Bug (Wynncraft pls fix this)

### ISSUE THREAD

**Issue by PvPxRobin** [Wynncraft/Issues#7356]
The Breathing Helmet II is not a quest item it is untradeable and you need it for From The Mountains and an untradeable item, is throwable and I threw it away, because it didn't say quest item so I thought you didn't need it anymore. Fixquests doesn't work, because it isn't a quest item so how can I get it back.Wynncraft pls help me.

**Comment by LordHelmchen98** [comment]
You can buy it from the armor merchant in Nesaak.
