### ISSUE TITLE
lag deleting items

### ISSUE THREAD

**Issue by Tyfyter** [Wynncraft/Issues#7358]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.
someone (SquareDudeZ) lost a "precision" bow completely to lag, it disappeared from his inventory somewhere around the spider cave in nivila forest

**Comment by LordHelmchen98** [comment]
Unfortunately Wynncraft has a strict norefund policy. Therefore SquareDudeZ wont get his precision back.

**Comment by Tyfyter** [comment]
Do you have a strict no-wurst policy?

On Feb 10, 2017 1:02 PM, "Lord Helmchen" <notifications@github.com> wrote:

Unfortunately Wynncraft has a strict norefund policy. Therefore SquareDudeZ
wont get his precision back.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Wynncraft/Issues/issues/7358#issuecomment-279018748>,
or mute the thread

**Comment by DebugMC** [comment]
@Tyfyter yes we do :(
