### ISSUE TITLE
Missing Item Frame in the quest Flight in Distress

### ISSUE THREAD

**Issue by LordHelmchen98** [Wynncraft/Issues#7359]
In the quest Flight in Distress, after you talked to the kid outside, you have to go to your cabin and sleep, but nothing shows you where your cabin is. In every other version of the airship there is an item frame that shows you where your cabin is, but when you have to go to your cabin for the first time there is no item frame so you cant really find the cabin if you dont know where you have to go.
Coordinates are -784 -8581
[I recorded it here](https://youtu.be/n4a2p4ePzWg)

**Comment by ColinRioux** [comment]
On build this seems to be fixed, so hopefully it'll be pushed in the next map update (corkus most likely). If the issue still persists after Corkus, let me know.

Thanks!
