### ISSUE TITLE
Old Item Bug/Issue

### ISSUE THREAD

**Issue by goldimp6** [Wynncraft/Issues#7362]
I have a old item that will not update to the Current item status (The name of the weapon is "Fierte"). Any Help?

**Comment by Pyromanical** [comment]
Nothing can be done to it sadly.  Any pre-Gavel items with special characters in them didn't update to the new item system.  You can keep it as a memento, or just throw it out, but selling it is against the rules.

**Comment by ColinRioux** [comment]
Hi please see #7176 for more information (final comment). @Pyromanical also sums it up.
