### ISSUE TITLE
Bob's Tomb

### ISSUE THREAD

**Issue by hotcatmom** [Wynncraft/Issues#7363]
I can't get Bob's Tomb in the quest Bob's Lost Soul open. I click the buttons and then stand on the pressure plate and nothing happens. I don't know what I'm doing wrong.

**Comment by LordHelmchen98** [comment]
You either need someone who can open it for you from inside the tomb or two other players who can help you, because if you want to open it from outside the tomb, the buttons and the pressure plate have to be activated at the same time.

**Comment by ColinRioux** [comment]
Please read the "How to Enter" section [here](https://wiki.wynncraft.com/index.php?title=Bob%27s_Tomb). This is not an issue, merely miscommunication.
