### ISSUE TITLE
Fantastic Voyage Glitch

### ISSUE THREAD

**Issue by Cynque** [Wynncraft/Issues#7364]
I did the fantastic voyage quest up until the cave that you open using a bomb created with items found on the island. (Around stage 23 in the guide to the quest - https://wiki.wynncraft.com/index.php?title=Fantastic_Voyage). When I logged back into the server, I was no longer in the cave. I spawned in at the place you start at when you make a new character. I walked back to Roland at Jofash Docks, and seemingly started over with the quest. Although, when I got to the part where I had to make the bomb, it said I already had, and I should take it to the boulder. I cannot make another bomb or get past the boulder to finish the quest. Someone please help

**Comment by Endeh** [comment]
Try /fixquests and the bomb. Make sure you have space in your inventory.

**Comment by Cynque** [comment]
I tried /fixquests and it didn't give me a new bomb. When I try to craft a new one it says I already made one and I can't make a new one.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
