### ISSUE TITLE
Masks from The Passage quest

### ISSUE THREAD

**Issue by SanderKappa** [Wynncraft/Issues#7365]
I bought a Mask of Courage, from The Passage quest. I logged off and logged on again, and the mask was just a steve head. Can you guys fix this?
![2017-02-12_10 45 48](https://cloud.githubusercontent.com/assets/25719528/22861093/792b35b4-f110-11e6-8431-7cce0c627340.png)

**Comment by LordHelmchen98** [comment]
I think that's an issue with NBT tags and I don't know if it can't be fixed but at least it is really hard to fix so if it's possible it will probably take a long time until it's fixed.

**Comment by thecoolkogut4** [comment]
you can't fix this, happens with most play heads.

**Comment by AscendedKitten** [comment]
This is a known issue, and sadly a bit more tricky to fix. 
However, the code-refactor done by Jumla might bring a change.
