### ISSUE TITLE
Sayleros' Brother wont die!

### ISSUE THREAD

**Issue by Lvnvceo** [Wynncraft/Issues#7366]
Saylero's brother wont die. 
When I try to kill him or "it" it dies but re-spawns so quickly and it doesn't drop the "will" I killed it 5 times already. Please fix this. keep up the good work on the server 👍

**Comment by LordHelmchen98** [comment]
This is intended. You have to kill several forms in order to get the drop.

**Comment by Lvnvceo** [comment]
Oh thank you.
