### ISSUE TITLE
Error in item loss

### ISSUE THREAD

**Issue by Enderdragon923** [Wynncraft/Issues#7368]
I was at 10 soul points and when i died, i lost a legendary spear i had (legendary smasher) . If i'm correct, at ten soul points you are only supposed to lose junk items. Please solve this and/or possibly give me my spear back.

**Comment by Endeh** [comment]
Are you sure you didn't drop it? Were you lagging? Sorry but Wynncraft has a strict no-refund policy, so they can't give you your item back.

**Comment by Enderdragon923** [comment]
I'm sure it's f it. However, I was fighting some bandits in a hole or something
