### ISSUE TITLE
Boats

### ISSUE THREAD

**Issue by TheArmandas** [Wynncraft/Issues#7370]
Whenever i place a boat down and try to swim it begins to sink, and also when i placed down my boat near the treasure island it disappeared i had space in my inv so i couldn't of dropped checked everything re-logged and nothing worked

**Comment by thecoolkogut4** [comment]
if you want to use a boat, I recommend using Mc version 1.8.9. be aware that when you go into 1.8.9 the wither bar won't load and some textures (for items) will be broken.

**Comment by DebugMC** [comment]
Duplicate of #7149 and #6770
