### ISSUE TITLE
Stuck on the travel ship

### ISSUE THREAD

**Issue by TheGamingSponge** [Wynncraft/Issues#7371]
I'm stuck on the travel ship with the Seaskipper Captain. I noticed something was wrong when I threw my ticket into the hopper and he didn't say anything. 5 minutes later, still on the ship and teleport scrolls aren't working. Disconnected and reconnect multiple times, and nothing's working. I am eternally stuck at 15k, 15k ;-;

**Comment by Pyromanical** [comment]
If you have more then 5 soul points, do /kill 
This will probably return you to the starting area, and you just have to walk thru it again.

**Comment by DebugMC** [comment]
This actually guaranteed will tp you to start :P

**Comment by AscendedKitten** [comment]
As @Pyromanical already said, using /kill with 5 or more soulpoints will return you to the closest town, which might be the starting area close to Ragni in this case due to the seaskipper being out-of-map.

**Comment by DebugMC** [comment]
Its ragni, 100% of the time.
