### ISSUE TITLE
Cant throw away my wynnexcavation crystal shard

### ISSUE THREAD

**Issue by tonytsetse** [Wynncraft/Issues#7372]
i cant throw away them (i already finished wynnexcavation site D)

**Comment by thecoolkogut4** [comment]
I do not recommend doing this as it MIGHT cause problems in the long run. but you can put it into your daily chest to get rid of it. warning: you might not be able to get the shard back with fixquests

**Comment by tonytsetse** [comment]
But i have already finished site D,do i still need site A+B's shards?

**Comment by Pyromanical** [comment]
Have you gotten those shards by doing A and B on another class, or did you get 2 from the same class?  If you finished all 4 WynnEx quests, and the extra shards aren't from a new class, then do what @thecoolkogut4 said.
