### ISSUE TITLE
lost saved data

### ISSUE THREAD

**Issue by MaxF4040** [Wynncraft/Issues#7374]

**Comment by Pyromanical** [comment]
Are you sure he isn't accidentally deleting his class?  If you open the delete menu, but esc out of it, instead of hitting the X, it can delete that class.  That's the only reason I could think of that could cause a class to delete itself.

**Comment by bulbaswat** [comment]
It's Bulbaswat. I am not deleting my class. When I load back into a world to select my class it says I'm back to level 1 or 2 then I load it up and I'm back at the starting area, all my progress erased.

**Comment by bulbaswat** [comment]
I think I figured it out. I was expecting a character to always stay in there slot and not move, but apparently it moves and sorts them based on level. Sorry for my stupidity.

**Comment by DebugMC** [comment]
@MaxF4040 if issue is fixed, please close :)
