### ISSUE TITLE
Sand dungeon boss glitch

### ISSUE THREAD

**Issue by Acerisk** [Wynncraft/Issues#7376]
Yesterday i fought the sand swept tomb boss many times to level u and get better gear however a couple of times that i fought it, there were two duplicates of the boss and the last time i fought him i somehow died instantly and re spawned inside a wall that i cant escape, someone pls help

**Comment by DebugMC** [comment]
@Acerisk /kill with 5 or more soulpoints to get out. Double boss spawn is a bug that has existed for a while though.

**Comment by AscendedKitten** [comment]
As @DebugMC said, the bug that certain bosses spawn multiple times has existed for quite some time, and is a bit more tricky to fix. You can use a teleportation scroll or /kill with 5 or more soulpoints to teleport back to the closest city, in case you are still suck.

Duplicate of #6796
