### ISSUE TITLE
The Bigger Picture Cave And Aldorei

### ISSUE THREAD

**Issue by Celsonic** [Wynncraft/Issues#7378]
I don't think they are suppose to be spawning and falling down here....
A GM should reduce the size of the spawning zone so it doesn't spawn in the cave.
![2017-02-14_19 04 47](https://cloud.githubusercontent.com/assets/21028327/22955177/be46aeba-f2e8-11e6-98a8-2bfc3dc45633.png)

**Comment by Moe-Ronickah** [comment]
Actually, while this was not intended, I'm closing it as being accidental, but not really affecting anything in the game, as the mobs are non-aggressive.
