### ISSUE TITLE
Lost yellow crystal due to an item bug

### ISSUE THREAD

**Issue by TheArmandas** [Wynncraft/Issues#7379]
when i completed excavation site a, i tried picking up an item and replaced the crystal with it without double checking. Now I'm unable to complete site B is there any way  of getting it back without trading?

**Comment by DebugMC** [comment]
Try /fixquests

**Comment by Pyromanical** [comment]
You are going to have to go through the site again to get the crystal.  I'm assuming you mean the untradeable version of the crystal you give to the excavator and not the quest item version you get from the excavator.  If you mean the quest item crystal you get from the excavator then do what @DebugMC said.

**Comment by Moe-Ronickah** [comment]
RESOLVED
