### ISSUE TITLE
Quest mistakes

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#7381]
I was doing "One Thousand Meters Under" and I found these two things that aren't right:
http://imgur.com/a/GmOOi

**Comment by DebugMC** [comment]
"Delete this line"

**Comment by thecoolkogut4** [comment]
are you talking about the chords in the book?

**Comment by LordHelmchen98** [comment]
I think the first picture is about the coords and the second one about the numbering of the dialogue.

**Comment by ColinRioux** [comment]
Thank you for reporting this issue! Both issues have been fixed.

These changes won't be reflected in-game until the next map update (which will probably be corkus). Thanks!
