### ISSUE TITLE
Shattered Minds Quest glitch

### ISSUE THREAD

**Issue by Stena1392** [Wynncraft/Issues#7382]
I was doing the quest, and I got Yahya's final form, I killed him. Now I can't leave the area where i killed him. A message states "It would be rude just to barge in on someone's house like that." Please help me.

**Comment by DebugMC** [comment]
How is it broken? please provide details :c

**Comment by thecoolkogut4** [comment]
try to walk back to where you got tped I to the room, then slowly walkacross the floor to see if you missed a tripwire or something.

**Comment by Numbermaniac** [comment]
Yeah @DebugMC I've done that one, but as @thecoolkogut4 said try walking back to the entry portal and walking through the tunnel again. Does your quest book say "Escape the wrath of Yahya"?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
