### ISSUE TITLE
Boat Bug

### ISSUE THREAD

**Issue by skulldude2004** [Wynncraft/Issues#7383]
I bought a Selchar boat pass because I need to do a quest, once I put it in the hopper it worked as normal but then nothing happened and in order to get off I had to use a Nemract teleport scroll. So I thought "Okay it'll work next time." I do it again doesn't work so I've wasted about 120 emeralds (I did the math for 2 Selchar boat passes and 2 Nemract teleport scrolls).

**Comment by skulldude2004** [comment]
And now I can't use a Nemract scroll to get back.

**Comment by skulldude2004** [comment]
Just went to check and I used 192 emeralds

**Comment by thecoolkogut4** [comment]
if that happens, i recommend you switch servers and try again.

**Comment by skulldude2004** [comment]
Okay yea I didn't think of that

**Comment by Numbermaniac** [comment]
Yeah if you get stuck while on the boat, switching servers always fixes it for me.

**Comment by Moe-Ronickah** [comment]
RESOLVED
