### ISSUE TITLE
Loot Chest + Mob Agro

### ISSUE THREAD

**Issue by thecoolkogut4** [Wynncraft/Issues#7384]
Normally when you open a chest, mobs won't attack you. If you are near a mob that has the pull spell (eg; the boss in demon cave) it will still pull you even though you have a loot chest open. Which #1 doesn't let you take everything from the chest, and #2 mobs can damage you again.

**Comment by DebugMC** [comment]
I never knew that was a feature...

**Comment by thecoolkogut4** [comment]
you learn something new everyday. please stay on topic though.

**Comment by DebugMC** [comment]
Allright. :P

**Comment by Moe-Ronickah** [comment]
I know that some code changes were made to chests, recently.  Is this still happening?
[PS, useless comments sometimes get deleted, that's why you don't see them anymore.]

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
