### ISSUE TITLE
Seeing what item your unidentified item will be

### ISSUE THREAD

**Issue by WayvernX** [Wynncraft/Issues#7385]
https://www.youtube.com/watch?v=vHBmpkZEbGY
So basically what happens is that a level 105 potion from that you get from killing high level mobs (you can't get them anymore) bugs out your inventory and you can see what item that the spear is going to be. It could have been a Tidebinder or a Harwrol but the glitch shows that its going to be a Harwrol

**Comment by DebugMC** [comment]
Well how about you get rid of the level 105 potion...


like srs
