### ISSUE TITLE
Queat (green skinned troubl)

### ISSUE THREAD

**Issue by Melker1234** [Wynncraft/Issues#7390]
When i completed the boss and i walked in that black Place where it where col blocks. I got telepoted to a tiny black room where im stuck and can not use a schrol our anything to get out pleas get me out and fix it. i realy like your server an i whana keap playing thats why i whant you to help me pleas telport me upp my usernamne is (DisaRonja) im in global 6 iff im not ther ill be in somwhere ells il be on a long time.

**Comment by DebugMC** [comment]
Please do /kill with 5 or more SP
