### ISSUE TITLE
stuck

### ISSUE THREAD

**Issue by GoodmanGaming** [Wynncraft/Issues#7391]
hello today I was supposed to do a quest, however i jump in to the meeting by acsident and im now stuck could u please help me?

**Comment by GoodmanGaming** [comment]
i meant the meeting in the quest in wynnexcovation site c

**Comment by Pyromanical** [comment]
Try just walking out, as that is what you do in the quest.  If that doesn't work, use a scroll or do /kill with 5+ soul points.
