### ISSUE TITLE
grave mistake stuck

### ISSUE THREAD

**Issue by trey1029** [Wynncraft/Issues#7395]
when  twain wants to show me wht he saw i get stuck in front of the house, i wanted to know if this was only me and if someone could get me unstuck

**Comment by trey1029** [comment]
i just b/ killed but it could still bug out

**Comment by ColinRioux** [comment]
Duplicate of:
#6730
#7373

Based on what you are describing, your issue is very similar to the issues #6730 and #7373. Frankly, the whole system needs to be reworked.
