### ISSUE TITLE
Seaskipper replaced item in inventory with a potion. 

### ISSUE THREAD

**Issue by Lhs88820** [Wynncraft/Issues#7399]
I was on the seaskipper to Nemract my Glare wand with a level 3 thunder powder applied to it at that time. When boat gave me the potion replaced my wand. Now I have no weapon and since it was legendary I can't get it back anytime soon. Can anyone please help? My username is EpicWolfGirl888.

**Comment by Pyromanical** [comment]
Sadly Wynncraft has a no refund policy, so you can't be given your wand back.  However, you can buy one from another player or find some nice player to give you a new one.

**Comment by Lhs88820** [comment]
Ok thank you!

**Comment by DebugMC** [comment]
@Lhs88820 I can't come on rn, but if you see me ingame (Debug__) I can happily give you one. However I do not know when I will be on, as I wrote this at school.
