### ISSUE TITLE
Vines

### ISSUE THREAD

**Issue by RikioPT** [Wynncraft/Issues#7403]
![2017-02-19_21 29 27](https://cloud.githubusercontent.com/assets/17153769/23115712/c184f522-f6ea-11e6-81df-461390d276d9.png)
These are the only gray leaves vines texture in this cave. It looks like the wrong vine texture.

**Comment by DebugMC** [comment]
The vine texture is intentionally in the game, but I think that is not intentional.

**Comment by ColinRioux** [comment]
Fixed on build. The changes will be reflected in the next map update (Corkus).
