### ISSUE TITLE
"Abysso galoshes" unindentified from "Lost Soles"

### ISSUE THREAD

**Issue by Eolyas** [Wynncraft/Issues#7405]
When you start the quest "Lost Soles", Ferndor took your boots "Abysso Galoshes" and, when he finished talking he gave them to you BUT unindentified. Can you correct that problem ?
![abysso galoshes](https://cloud.githubusercontent.com/assets/25902804/23126746/777dc25e-f778-11e6-8ab0-e5a1b74b4e4b.png)

**Comment by DebugMC** [comment]
Not a bug, all quest rewards from all quests are **ALWAYS** unidentified.

**Comment by Pyromanical** [comment]
He does not give back the Abysso Galoshes.  The entire point of the quest is to contrain the evil of the Abysso Galoshes, which is why you don't get them back.  You get a new pair of boots called Sodeta Boots.
