### ISSUE TITLE
Flight in Distress-Stuck in teleporter

### ISSUE THREAD

**Issue by BramPuReDutch** [Wynncraft/Issues#7406]
i escaped while being teleported to an other place in the quest Fight in Distress and now i cant finish it please help me! ;/

**Comment by ColinRioux** [comment]
If you are in an area in which you are stuck, you can type `/kill` with 5 or more soul points and you'll spawn in the nearest town. Then to pick up where you left off in the quest, simply go back to Letvus Airbase and board the airship, and you'll go to whatever stage you were in (as noted in your quest book).

**Comment by BramPuReDutch** [comment]
Hi, if i go back on the air ship i am at the start of the quest so.. I was
stuck in the teleport (the place caged in with coal blocks) so i need to
teleport with that.. :/


2017-02-20 17:16 GMT+01:00 Colin Rioux <notifications@github.com>:

**Comment by ColinRioux** [comment]
Going back on the airship won't put you at the start of the quest. Can you please tell me what your quest book says?

**Comment by AckroWynn** [comment]
If you have reached the part of getting to the parkour over to the pirate ship, you should just enter your room at the start of the quest. You know, where the attendant is standing.
