### ISSUE TITLE
Fantastic Voyage Boat not spawning

### ISSUE THREAD

**Issue by 123457665617501** [Wynncraft/Issues#7407]
So the part where you have to steer a vanilla boat around the rocks, the boat isn't appearing

**Comment by ColinRioux** [comment]
We recommend playing on 1.8.9 because Wynncraft is hardcoded to 1.8.9.

**Comment by Pyromanical** [comment]
You don't actually need a boat to do it, just swim through the area.  

@ColinRioux I though the boat part was removed, because people could get infinite free boats from it, but I could be totally wrong.

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
