### ISSUE TITLE
Stuck at Galleon's Graveyard Boss Cutscene

### ISSUE THREAD

**Issue by CharredCoal** [Wynncraft/Issues#7409]
Help! I am stuck in the cut scene to the boss at Galleon's Graveyard! Do I have to restart the dungeon or can this be fixed?

**Comment by thecoolkogut4** [comment]
try switching servers thst might fix it. also run around, jump to try and trigger something.

**Comment by DebugMC** [comment]
Its a bug with the dungeon. They have to do /kill with 5 or more SP, be on 1.8 (reccomended) or switch servers (being on 1.8 helps the most.)

**Comment by ColinRioux** [comment]
Galleons' Graveyard has been repaired on build, and has been tested successfully on gm. However, the changes made to Galleon's Graveyard won't be implemented until the next map push, which is Corkus.
