### ISSUE TITLE
House of Twain graveyard bug

### ISSUE THREAD

**Issue by Jaqwith49** [Wynncraft/Issues#7412]
When doing The House of Twain quest, I obtained the Ghostly Cap and identified it and went down to the graveyard outside. However, when I attempted to enter with the helmet on, I could not. All it said was "Stay away!". I have done everything before this point in the quest, including throwing the emeralds on the memorial behind the fireplace.

~Jaqwith49

**Comment by Pyromanical** [comment]
Try switching servers or taking it off and putting it on again.

**Comment by thecoolkogut4** [comment]
what does your quest book say?

**Comment by Jaqwith49** [comment]
Pyromanical, I've already tried that, but to no avail.
thecoolkogut4, I will try that shortly.

**Comment by montz13** [comment]
I have also experienced this bug - I also could not enter the graveyard. I have switched servers, obtained a new cap,which I identified at the house itself, and nothing seems to work.
This is my second cap - which I identified at the identifier at the house itself:
![2017-03-04_13 29 29](https://cloud.githubusercontent.com/assets/26185209/23579168/8f8e918c-00df-11e7-83eb-6778d09e6f97.png)
This is my first cap, which I identified at Nesaak:
![2017-03-04_13 29 31](https://cloud.githubusercontent.com/assets/26185209/23579169/8f92fcae-00df-11e7-8b83-8fc3d9123de5.png)

**Comment by Jaqwith49** [comment]
montz, I legit just learned this myself. That's the wrong graveyard. There's a small little graveyard out front of the House of Twain. This one in the back is only unlocked after the main quest, and is for a little bit of an expansion.

**Comment by montz13** [comment]
Oh OK - I have done it now - however the wiki says to left, which is ambiguous! Maybe this should be fixed

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
