### ISSUE TITLE
Sand Swept Tomb Dungeon Hashr going under the floor

### ISSUE THREAD

**Issue by NAREKRULES** [Wynncraft/Issues#7413]
My friend and I were fighting Hashr, and he glitched through the floor and we couldn't kill him because he was under the floor. 
![2017-02-21_15 10 01](https://cloud.githubusercontent.com/assets/25938066/23183473/2c7ae1c4-f84a-11e6-8828-5c5d18f8d6c1.png)

**Comment by DebugMC** [comment]
No idea, should fix next time you do dungeon.

**Comment by thecoolkogut4** [comment]
/kill to get out and try again, happen when you do spells.

**Comment by ColinRioux** [comment]
Certain spells can cause mobs to glitch out of certain areas. This is an example. This is a reported issue, and please use the above advice as a temporary solution.
