### ISSUE TITLE
Suspended Flower Quest Glitch

### ISSUE THREAD

**Issue by blazer102** [Wynncraft/Issues#7414]
My friend and I were doing the Suspended Flower Quest. We were going to teleport to Ragni, so I gave him a teleport scroll but his inventory was full so he threw out the flowers for the scroll and the flowers disappeared. He tried to go back to the cave to get more flowers, but it wouldn't work. Now he couldn't progress in the quest.

**Comment by Pyromanical** [comment]
Do /fixquests with an open inventory slot.
