### ISSUE TITLE
Unusable/old version Emerald + Junk

### ISSUE THREAD

**Issue by chia591** [Wynncraft/Issues#7417]
After coming back on the game after 2 years i have about 6 stacks of rotten flesh that isint marked as a junk item (not renamed, recolored) just regualr zombie flesh

**Comment by Pyromanical** [comment]
Just throw it out, it is a junk item just like the new rotten flesh.  I guess you could keep it as a memento, but thats about it.  It might count as a vanilla item, which you aren't allowed to have, but because it is not one that you obtained illegitimately, I'm not sure.
