### ISSUE TITLE
Cowfusion: Coordinates at one stage of quest book are over 3,000 blocks off

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7421]
See the screenshot. The coordinates in the book, and my actual coords, clearly do not match:
![2017-02-13_13 49 46](https://cloud.githubusercontent.com/assets/5206120/23199638/bde0f962-f923-11e6-9143-5fcfc7b48944.png)

**Comment by DebugMC** [comment]
I told someone about that and they told me it was fixed... (this was a long time ago)

**Comment by DebugMC** [comment]
Also I think those are the coordinates for something off map so its probably wrong.

**Comment by ColinRioux** [comment]
Guaranteed fixed! Will be pushed in the next map update (Corkus)
