### ISSUE TITLE
WynnExcavation Site D: Traitor Thomas' name tag is a little too low

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7424]
You can see in the first screenshot that "NPC" appears to be inside his head, which becomes even more apparent in the second screenshot:
![2017-02-22_13 50 16](https://cloud.githubusercontent.com/assets/5206120/23199893/59268648-f925-11e6-9392-58a4d423de48.png)
![2017-02-22_13 50 37](https://cloud.githubusercontent.com/assets/5206120/23199896/5c957bae-f925-11e6-8ab6-dd4896b356d2.png)

**Comment by thecoolkogut4** [comment]
switch servers and this should be fixed. when a GM makes any questions, they don't specify how high the tag is therefore making it a specific temporary error. (I'm pretty sure)

**Comment by AscendedKitten** [comment]
As @thecoolkogut4, switching server should fix the issue. GMs don't modify the height or position of the tag, so what you experienced is probably a unique displaying error.
