### ISSUE TITLE
WynnExcavation Site D: Typo in Traitor Amadel's dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7425]
8/8: I think it should be "It looks **like** it's deep in the jungle"; "like" is missing:
![2017-02-22_13 54 33](https://cloud.githubusercontent.com/assets/5206120/23199930/955a81d2-f925-11e6-9e2f-cd2b2fde517b.png)

**Comment by ColinRioux** [comment]
Fixed!
