### ISSUE TITLE
WynnExcavation Site D: Two signs have "Access" spelt wrong

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7427]
See screenshots.
![2017-02-22_14 20 32](https://cloud.githubusercontent.com/assets/5206120/23200107/99e57d0a-f926-11e6-9551-40e18458acc0.png)
![2017-02-22_14 20 39](https://cloud.githubusercontent.com/assets/5206120/23200108/9abe6bb0-f926-11e6-865c-f1bb2e358a6f.png)

**Comment by thecoolkogut4** [comment]
@Villageacules

**Comment by ColinRioux** [comment]
Fixed!
