### ISSUE TITLE
WynnExcavation Site D: Missing exclamation mark in Corrupted Amadel's dialogue?

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7428]
1/1: Is there meant to be an exclamation mark at the end?
![2017-02-22_14 40 09](https://cloud.githubusercontent.com/assets/5206120/23200289/9411ad9e-f927-11e6-9826-6448d645a9b2.png)

**Comment by thecoolkogut4** [comment]
if it's not a ! then for sure it's missing a . or something to end it.

**Comment by ColinRioux** [comment]
Fixed!
