### ISSUE TITLE
Weapon and permission.

### ISSUE THREAD

**Issue by Vas0sky** [Wynncraft/Issues#7429]
This problem appeared after I accidentally dropped my bow Maelstrom. Basically when you right click something the message pops up (You don't have permissions for this area) and you can't interact with anything with the bow in the hand. I know that the bow is a slab, the game thinks that you are trying to place it and so on, but I used to be able to open chests and such with the bow. It's extremely annoying, please fix it.

**Comment by DebugMC** [comment]
@Vas0sky we can not fix this bug yet, it may be fixed in corkus? I am not sure of this. The admin team is aware however. If you want to open/interact with things, just for the time switch to another item to open stuff (like have a normal bow next to it) or click with your soulpoints.

**Comment by thecoolkogut4** [comment]
duplicate, and do what debug said. open it with nothing in your hand/sp.
