### ISSUE TITLE
tp in rock

### ISSUE THREAD

**Issue by edwarncraft** [Wynncraft/Issues#7431]
hi i'm edwarncraft in game but i have a problem my rogue is lock in rock in -1866 / 28 / -4900 and i can't tp outside plz help me i love this serve and i don't want to lose mu character

**Comment by edwarncraft** [comment]
i tp in a new city but i lost two soul for this bug plz :'(

**Comment by DebugMC** [comment]
Yeah the only way out is /kill! Sorry :C

**Comment by ColinRioux** [comment]
Losing two soul points isn't a big deal, as long as you have full soul points. This also happened to be a fluke because there is no plausible explantation as to how you got your mage (not rogue) stuck in there. It's solid blocks.
