### ISSUE TITLE
mission Elemental Exercise

### ISSUE THREAD

**Issue by SpyGamer007** [Wynncraft/Issues#7432]
whenn i tryt to do this mission it wont let my go to the cave like i can go to there but when i killed the monster there it wont explode so i cant go furter sorry for my bad english
![i486 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/25963190/23226919/9c6ec124-f937-11e6-8d7e-81ac32427aea.jpg)

**Comment by DebugMC** [comment]
Why did you close this? I heard this was an issue a while ago. #7106 #7289 #7305

**Comment by Numbermaniac** [comment]
@DebugMC Chances are they fixed it by switching servers or something. If it's a duplicate as you suggest, it probably would've been closed anyway.

**Comment by SpyGamer007** [comment]
Yes i had chanced from world and than it worked idk why it was like that and sorry idk anymore what wirld it was where it diddend work the first time :/
