### ISSUE TITLE
WynnExcavation Site D: Carlos' message after the quest is 4/4 instead of 1/1

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7433]
He only says one thing but it's labelled as 4/4:
![2017-02-22_15 26 42](https://cloud.githubusercontent.com/assets/5206120/23238439/0f8f3c78-f9b6-11e6-98b6-ec2e7f605384.png)

**Comment by ColinRioux** [comment]
Fixed!
