### ISSUE TITLE
WynnExcavation Site D: 3 typos in Ragni's King's dialogue

### ISSUE THREAD

**Issue by Numbermaniac** [Wynncraft/Issues#7434]
7/18: "There" is after a comma, not a full stop, so it doesn't need to be capitalised.
13/18: "it's container" should be "its container".
16/18: "cities" should be "city's".
![2017-02-22_15 05 06](https://cloud.githubusercontent.com/assets/5206120/23238650/1b8aa6f6-f9b7-11e6-8ebb-c7a39283d099.png)
![2017-02-22_15 09 28](https://cloud.githubusercontent.com/assets/5206120/23238651/1bd22ba2-f9b7-11e6-9cae-8d4d0bd95836.png)
![2017-02-22_15 12 26](https://cloud.githubusercontent.com/assets/5206120/23238652/1bd25014-f9b7-11e6-856f-7f4d03c5a9f7.png)

**Comment by ColinRioux** [comment]
Fixed!
