### ISSUE TITLE
Item Toss Glitch

### ISSUE THREAD

**Issue by iHavenGod** [Wynncraft/Issues#7435]
(Warning: Salty)
IGN: iHavenGod
So I was in Llevigar, grinding away at the monsters there. My friend tells me to come back to Detlas so we can do a dungeon together. I switched my slot holding my Level 16 Black Horse with a Detlas Teleport Scroll, and placed the Saddle into my inventory. As soon as I hit "E" and closed it, the Saddle fell out at my feet. Not realizing this, I clicked teleport and vanished back to Detlas. I tried going back but the saddle despawned. Kinda salty, any way to fix this? I also lost a Legendary Dagger from this earlier.

**Comment by ColinRioux** [comment]
Unfortunately, Wynncraft enforces a strict no-refund policy. Switching slots tends to be glitchy (like pressing a number to switch an item to your hotbar), so I suggest not doing that in the future. Also try to be more careful with your items if you don't want to lose them as often. You'll find better items in the future, or by buying them from other players, but not from the admin team.
