### ISSUE TITLE
Loss of a Legendary Bow

### ISSUE THREAD

**Issue by FRHyrath** [Wynncraft/Issues#7442]
Hello,
I lost my Infinity bow by dropping it on the ground unwittingly, it was stuck in a half slab.
I would really like to get my bow or receive compensation.

Thanks you, FR_Hyrath

Image Link : https://www.noelshack.com/2017-08-1487967584-2017-02-24-19-37-56.png

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.
