### ISSUE TITLE
White horse loss

### ISSUE THREAD

**Issue by KyuubiFox** [Wynncraft/Issues#7443]
I was showing someone the demon cave and the mini boss ripped me off my white horse 40/40 and it disappeared instantly. happened around 8:40-8:50pm EST us&canada time. If you can please give my horse back.

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.
