### ISSUE TITLE
Banned for nothing reason 

### ISSUE THREAD

**Issue by lCay** [Wynncraft/Issues#7446]
I was still seeing a video of how to pass a mission and when I went back to the game was that it had been banned for using Hacked Client and was still and not only the OptiFine of the 1.8 use nothing rare you can check me if want to please desbanenme nickname: lCay_

**Comment by Pyromanical** [comment]
Please post a ban appeal on the forums here if you would like to be unbanned.
https://forums.wynncraft.com/forums/ban-appeals.84/

**Comment by ColinRioux** [comment]
This is a place for bug reports, not for requesting to be unbanned.
