### ISSUE TITLE
A stack of arrows

### ISSUE THREAD

**Issue by NeonCow** [Wynncraft/Issues#7448]
There is a stack of arrows in my bank that when ever I click it, it just goes right back in and I can't move it. I think it was before the whole texture pack thing and it's really annoying. And I've seen a admin responding to a thread like mine a year ago and nothing has been done

**Comment by ColinRioux** [comment]
Please see: #7367. If contacting Pretzule on the forums doesn't work, you'll have to standby until we determine anoter fix.
