### ISSUE TITLE
Underworld Crypt Glitch

### ISSUE THREAD

**Issue by captainkyrk** [Wynncraft/Issues#7450]
I was doing the underworld crypt and when facing the Forsaken Legion High Priest, I was stuck in his web and while trying to use my leap to get out, I was kicked for "flying". When I re-logged into a server, I am still on the platform, the bridge isn't down and the mini-boss isn't there, so I have no way to get past this point.
![screen shot 2017-02-25 at 10 14 20 pm](https://cloud.githubusercontent.com/assets/25847516/23336797/16c9afd4-fba8-11e6-9659-a79e8703bdd4.png)

**Comment by ColinRioux** [comment]
You must restart the dungeon, as it should've teleported you to the beginning after you were kicked / re-logged. Instead, you must do `/kill` with 5 or more soul points, and restart the dungeon (I know you spent a key, and probably salty for getting kicked, but we have a no-refund policy).
