### ISSUE TITLE
Lost my Factory Helmet for the Iron Heart Part 2 Quest

### ISSUE THREAD

**Issue by AlleyCat748** [Wynncraft/Issues#7451]
I have just reached level 58 and I am trying to do the Iron Heart Part 2 Quest, but I cannot seem to find the helmet anywhere. I've identified all of the helmets I have, tried /fixquests, and I still cannot find it anywhere. My friend that i'm playing with is having the same problem as well.
Please help! I really don't want to have to try to get it all over again.

**Comment by Pyromanical** [comment]
If /fixquests doesn't give you the helmet back that means it is either in your inventory, you are wearing it, it's in your bank, or in another classes' inventory.  Go double check all those places, and if it isn't there, try /fixquests again.

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
