### ISSUE TITLE
Problem with WynnExcation site A

### ISSUE THREAD

**Issue by Kroko-fant** [Wynncraft/Issues#7456]
I'm a little bit disappointed because I reported this issue some time ago but nobody fixed it.
My questbook says, that I must go to Tesh but he tells me to go to Vade. And Vade tells me how I can entry the cave but I can't enter the cave because my questbokk still says that I must talk to Vade.
IG: Kroko_fant class: warrior

**Comment by Pyromanical** [comment]
That might mean you are missing the paper Tesh is supposed to give you.  Do `/fixquests` with an open inventory slot, and see if you get the paper back, then talk to Vade again.

**Comment by Kroko-fant** [comment]
Now it's done thy
