### ISSUE TITLE
Dropped items from identifier nowhere to be found

### ISSUE THREAD

**Issue by Robotomy101** [Wynncraft/Issues#7457]
identified 5 set necklaces, a legendary lvl 64-68 helmet, lvl 60-64 legendary spear and a rare 60-64 wand, I clicked take all items after identifying and I apparently didn't have enough space, so it said items dropped on the ground, but they were nowhere to be found. i searched everywhere around the identifier house and on the top floor, i tried relogging into the same server and searching but i didn't find anything, i lost a spectre, a ry something legendary spear (didn't pay attention to the name) and a rare wand(which i dont really care about), please help me

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug. Next time that happens, check behind walls and dont /class or relog. Leaving the chunk when items are on the ground causes all of the items to despawn.
