### ISSUE TITLE
Yahya's Stained Bowl lost, fixquest doesnt work

### ISSUE THREAD

**Issue by TheFoun** [Wynncraft/Issues#7458]
Hello, my ingame name is msrtinmach_111, I wanted to do the the temple of legends quest today but when I searched my bank I was missing Yahya's Satained Bowl, I did /fixquests but it still didn't appear, please could anyone help me?

**Comment by Pyromanical** [comment]
That means you still have it, check all your classes and your bank again, because if `/fixquests` doesn't work, it means you still have it somewhere.

**Comment by TheFoun** [comment]
wow, I thought I deleted my old character, weird, but thanks, it was the only quest item I had on that character and now I am deleting that characters because I have better mage alredy
