### ISSUE TITLE
HELP!!! I'm Stuck and I can't Play!!!

### ISSUE THREAD

**Issue by assassinmaster** [Wynncraft/Issues#7461]
I was doing the Galleon's Graveyard Dungeon and I got stuck when the boss was talking or doing the dialogues in the chat. When they were talking, I was teleport inside an air block to see the scene and now I'm stuck in it FOREVER!!! Please help me get out!!! I just want to play :( P.S. Now I can't finish the dungeon too rip :( Also, my IGN is Brianqiu911CA and I'm level 66

**Comment by Pyromanical** [comment]
Do `/kill` to get out.  This is a well known bug, and it has been fixed on the build server, so I would suggest waiting until the next map push, which will probably be Corkus, to try the dungeon again.
