### ISSUE TITLE
Waffe durch einen läg verloren

### ISSUE THREAD

**Issue by chrissirsv** [Wynncraft/Issues#7463]
Hi ich habe meine Waffe weg eines lägs verloren und habe auch keine andere!!!!!!!! Kann mir bitte jemand helfen

**Comment by thecoolkogut4** [comment]
Hey dort, leider Wynncraft erzwingt eine strenge Rückerstattungsrichtlinie. Das heißt, du wirst deine Gegenstände nicht mehr erhalten. Vielen Dank für die Meldung des Bugs. * Verwendet Google Translate *
