### ISSUE TITLE
Relogged and got stuck inside house

### ISSUE THREAD

**Issue by TBlazeWarriorT** [Wynncraft/Issues#7467]
I logged out of the server on a completely normal spot, when I logged back in I was stuck inside a house at -168/34/-5394. It was a dark room, very small, no doors, holes, nothing, The only way to get out was to /kill. I know this might be a known/common issue, but it's still a unfair/annoying bug that should be fixed if possible. Thanks
[http://i.imgur.com/t54iO8P.png](url)
Direcyly uploading the image failed for some reason, so the screenshot is on the link above.

**Comment by ColinRioux** [comment]
Hi, thank you very much for reporting the hole, and it has been patched up. However, these changes won't be reflected until the next map push, which is Corkus. So for now, it'll still be a hole, but when Corkus is pushed it'll be fixed.

Thanks!
