### ISSUE TITLE
Stuck in Galleon's Graveyard

### ISSUE THREAD

**Issue by goldimp6** [Wynncraft/Issues#7468]
I'm stuck in Galleon's Graveyard at the end. I can not fix it from anything that I can do. The Cannons are glitched out and nothing really seems to be working. Any help? Ig name is goldimp6 .

**Comment by Pyromanical** [comment]
Do `/kill` to get out.  This has been fixed on the build server, and will be pushed onto the main server next map push, which will probably be Corkus.
