### ISSUE TITLE
Shattered Minds possibly broken

### ISSUE THREAD

**Issue by Henk385** [Wynncraft/Issues#7470]
I'm currently stuck at stage 7 of the Shattered Minds quest and when talking to the 'Likeru?' NPC, (the one located in the 'more colourful version' of Efelim) only one line of dialogue appears instead of the 6 that are listed on the wiki, as if I already talked to that NPC before, which is not the case. I then figured I'd watch a playthrough of the quest wondering if it might all have been my fault. However, when the other person talks to the NPC the 6 lines appear as usual, followed by a questbook update, which I didn't get. It still tells me to find a civilization of some sort. Because of this, I can't enter the house the NPC is asking me to investigate and, therefore, can't progress any further. 

Thank you for reading.

Kind regards,

Henk385

**Comment by Pyromanical** [comment]
What exactly does your questbook say?

**Comment by Henk385** [comment]
"try to find civilization within the strange forest"

**Comment by Pyromanical** [comment]
Try walking back on the back, that might trigger a questbook update which will then allow you to talk to Likeru?

**Comment by Henk385** [comment]
I tried that before to no avail. Also, a questbook update would have appeared in chat, which never happened in the playthrough I watched either.

**Comment by ColinRioux** [comment]
I suggest re-entering the new area, which is accessible via the same mushroom that you used to enter. To leave the area, you could try doing `/kill` with 5 or more soul points or using a teleport scroll.

**Comment by Numbermaniac** [comment]
That part of the quest book should update when you walk into the town. Did you maybe walk in to the "civilisation" from the side, perhaps? It should trigger the update when you walk in from the front.

**Comment by Henk385** [comment]
I did /kill and went through the entire cave and again but upon approaching the "civilization" again nothing happened and the NPCs respond the same way they've always done, without ever updating the questbook that is.

**Comment by ColinRioux** [comment]
Please confirm that you did in-fact go to the mushroom in the cave to be teleported to the new area? 

I'll also go test this in GM now.

**Comment by Henk385** [comment]
i was teleported to the new area, yes

**Comment by Henk385** [comment]
So I actually managed to find a solution. Apparantly, you need to bring along the bluecapped mushrooms to pass this stage of the quest. Since I failed to make it through the cave multiple times I completely forgot that quest item was a thing I had to bring with me. There was no indication of this on the wiki either and none of the NPCs in the quest mention the item at all, which seems less than convenient to me. Regardless, I want to thank you all so much for your help and advise.

Kind regards,

Henk385
