### ISSUE TITLE
Saddle disappeared similar to boats

### ISSUE THREAD

**Issue by Ebolacow** [Wynncraft/Issues#7471]
Today, i was riding my 15/20 black horse in deltas and when i got off and tried to despawn it by rechecking the saddle with my mouse, a glitch happened. After i clicked the saddle it despawned but a could of seconds later, the saddle went into my hand and then disappeared. I would have thought it was sort of like a boat disappearing glitch, however the horse did not reappear. Please help me

**Comment by ColinRioux** [comment]
Hi, Wynncraft enforces a strict no refund policy. What this means is that you will not be receiving your item back by us. However, it's possible to re-obtain the item by other means (players, buying one, etc). But I will keep this information open until further notice, as how you described it was new.

**Comment by Ebolacow** [comment]
OK thanks for the help, shame theres nothing to be done though

**Comment by ColinRioux** [comment]
There's a long to-do list, so this is the least of worries at the moment. There are other more important game breaking issues which are affecting a lot more people. Sorry for the inconvenience!
