### ISSUE TITLE
Powder shrines not giving correct powder tier

### ISSUE THREAD

**Issue by Robotomy101** [Wynncraft/Issues#7473]
here's an example: i found the tier 4 water powder shrine, i collect it, i get a tier 3 water powder. this has happened multiple times with not only the same shrine but many others. im not sure if this is intended to minimize the powder supply or something, but might as well report it. i also got a few screenshots
![2017-03-03_03 28 01](https://cloud.githubusercontent.com/assets/26049035/23534177/2070b046-ffc7-11e6-95dc-252d7198329f.png)
![2017-03-03_04 01 47](https://cloud.githubusercontent.com/assets/26049035/23534179/277b59a4-ffc7-11e6-9361-976e9babe343.png)
![2017-02-28_16 40 28](https://cloud.githubusercontent.com/assets/26049035/23534187/36c5383a-ffc7-11e6-9aaf-ec79db769638.png)
![2017-02-28_16 20 40](https://cloud.githubusercontent.com/assets/26049035/23534216/5bbe8a92-ffc7-11e6-94a5-c18092a5bf37.png)

**Comment by ColinRioux** [comment]
Hi please see: #6224 for more information on how the powder system works. This is in fact intentional.
