### ISSUE TITLE
Stuck in invisible box

### ISSUE THREAD

**Issue by thefakearlo** [Wynncraft/Issues#7474]
hi, my ign is jayjay104 and i got stuck in an invisible box while doing a quest i was in a part where i couldn't move and server restarted so i logged back in and i was stuck in the invisible box so i if someone could tp me out and into deltas it would be appreciated. i'm just gonna go afk for a while so an admin can tp me when they see this.

Cheers.

**Comment by Pyromanical** [comment]
Just do /kill with 5+ soul points, you'll respawn in the nearest town.
