### ISSUE TITLE
Immortal rat on Ragni causing mayhem

### ISSUE THREAD

**Issue by TBlazeWarriorT** [Wynncraft/Issues#7481]
I logged in into Ragni, and after a few minutes hearing silverfish noises... I found the culprit. It was an immortal rat, being infinitely attacked by the guards. (I did not cause the glitch, I don't know what did, and I tried to lure it outside Ragni so it does not kill the AFK players).
Here is some quick footage of the issue (sorry for external link, should have tried to upload directly on github but my internet upload is bad): https://vid.me/DIkM

**Comment by TBlazeWarriorT** [comment]
Oh, and I heard of a player shouting he died 7 times while AFK and lost all his items. That might have been caused by the rat

**Comment by Villageacules** [comment]
Can you give me the name (the tag that appears above its name) and its level? I can't seem to find it on the database...

**Comment by TBlazeWarriorT** [comment]
"Rat [Lv. 2]", is that it? I had to check the video above, otherways I wouldn't remember it

**Comment by TBlazeWarriorT** [comment]
By the way, I just saw a Ragni guard attack a Bob the Zombie (the one that drops the tear) and do no damage. However, he was not immortal, like the rat, and I killed him.

**Comment by LordHelmchen98** [comment]
@Vill

**Comment by LordHelmchen98** [comment]
@Villageacules I assume it was a broken server on which no mobs can be damaged.

**Comment by Villageacules** [comment]
Must have been an odd server-specific issue, I'll close.
