### ISSUE TITLE
Quest "From the Mountains" - Cannot move forward w/o Breathing Helmet

### ISSUE THREAD

**Issue by solovet** [Wynncraft/Issues#7482]
So after finishing a lvl 45 quest in Nesaak where I had to use the breathing helmet II, It was no longer considered a "quest item" and it let me throw it to the ground because I was under the impression you wouldn't need it in a later quest since after all, it didn't say it was a "quest item" anymore. Now i'm already full up on ender chest space because all the other quest items. So I naturally threw that junk helmet away immediately because #1, it let me. and #2 It didn't have the category of Quest Item anymore, only an untradeable. So please fix the breathing helmet not being a quest item bug, and please put a brand new helmet into my inventory. Thank you. My minecraft username is Solovet and I am a lvl 67 warrior as of posting this. I am also a VIP+ Also trying ./fixquests after checking the banks and inventories of all characters, still does not replace the breathing helmet.

**Comment by Numbermaniac** [comment]
It's not a quest item, and it's not meant to be. You can buy another Breathing Helmet from Nesaak's armour merchant.

**Comment by solovet** [comment]
awesome thx.
