### ISSUE TITLE
I LOST A QUEST ITEM!!!

### ISSUE THREAD

**Issue by assassinmaster** [Wynncraft/Issues#7483]
I'm currently level 68 and I'm doing the Temple of the Legends Quest where I have to give my quest items to finish it. I recently found out I lost one of my quest item somehow and now I can't complete the quest. The quest item that I'm missing is The Mummy's Bandage from doing The Wrath of the Mummy Quest. Please Help me!!! My IGN is Brianqiu911CA

**Comment by Numbermaniac** [comment]
No need to scream. Try /fixquests in-game and it should give it back. If it doesn't, check your bank or other classes if you have any.
