### ISSUE TITLE
Excavation Site A Quest Problem

### ISSUE THREAD

**Issue by quinacorn** [Wynncraft/Issues#7484]
It will not allow me to complete the Excavation Site A quest. I went and found the pharaoh, yet it would not allow me to speak to Excavator Vade to complete the quest. 

My username is Trinket57 

Thank you!

**Comment by Endeh** [comment]
You have to kill the Pharoh, he drops a 'Yellow Crystal Shard'. You need that in your inventory when you talk to Excavator Vade and you should be able to finish the quest. If you still cannot finish, try /fixquests.
