### ISSUE TITLE
World login bug

### ISSUE THREAD

**Issue by frostyland** [Wynncraft/Issues#7486]
java.lang.IllegalArgumentException: Parameter 'directory' is not a directory

That message pops up every time I log on wynn, please help

**Comment by Endeh** [comment]
Try restarting your Minecraft a few times. If that doesn't work it seems like a folder must be missing and it might be an issue with the server resource pack. Go into your .minecraft, then there should be a folder called "server-resource-packs", and if there is not one, create one with that exact name. If there is one, go inside and delete the file named "legacy" and try to join Wynn again.

**Comment by ColinRioux** [comment]
Can you be more specific? Like do you have trouble logging into the network or an individual server (i.e WC12).

**Comment by Villageacules** [comment]
@frostyland do you still have these issues or was it solved?

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
