### ISSUE TITLE
Arrows Locked in my Enderchest

### ISSUE THREAD

**Issue by Madn3ssMan** [Wynncraft/Issues#7487]
This has been an issue since i started Wynncraft. Back in the day on Wynncraft, every account on every class was given 64 arrows that were untradable (meaning you could not dispose of them) and most people were forced to place them in their banks due to the need of space in their inventory. So now, few years later, and many updates later, I, and many other people, are still stuck with STACKS of arrows in our banks taking up valuable room. Please respond. 
Thank you, Aidan

**Comment by Numbermaniac** [comment]
A moderator can get rid of them from your bank. @Moe-Ronickah should be able to help you with this; you may want to message him on the forums or in-game with your Minecraft username.

**Comment by ColinRioux** [comment]
See here as well: #7367
