### ISSUE TITLE
Can not finish Elemental Exercise, server reset bug

### ISSUE THREAD

**Issue by Madzoman** [Wynncraft/Issues#7492]
I started the quest elemental exercise as usual, and continued until i had to "Trade in my fire weapon and give the study results to Ragon". I got the study results and gave them to Ragon, and then he started to talk. When he was mid-talking the server reset and when i logged on he still had my "study results" and wanted them once again. Since i already gave them to him i cant get them anymore. What do i do?

**Comment by Endeh** [comment]
Do /fixquests and the study results should return to your inventory.

**Comment by ColinRioux** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
