### ISSUE TITLE
Shouting Bug?

### ISSUE THREAD

**Issue by playwynncraft** [Wynncraft/Issues#7493]
I don't see my shout but i lost the shout bomb? 

![1](https://cloud.githubusercontent.com/assets/26207616/23591615/358fab84-01f3-11e7-9bf7-6f7a7d628123.JPG)

**Comment by crazygurlisshy** [comment]
Seems as though guild chat, shout, and the online interactive map are not working. Figured I'd just mention that here instead of on every post that mentions the issue.

**Comment by playwynncraft** [comment]
How do I get my shouts back? (2)

**Comment by Pyromanical** [comment]
Email support@wynncraft.com, they can help you further there
