### ISSUE TITLE
Purple and Blue

### ISSUE THREAD

**Issue by Louis-D** [Wynncraft/Issues#7495]
In the quest Purple and Blue between stage 9 and 11 there is a parkour with a commandblock.
Due to the new glass panes, they are only tiny and the anticheat doesn't let you jump on / off them.
Thefore the parkour is impossible!

**Comment by thecoolkogut4** [comment]
try to do the parkour in Mc version 1.8.9, when in 1.8.9 you will have some Texturepack errors... when your done the parkour you can switch back to the other version.

**Comment by LordHelmchen98** [comment]
Either what @thecoolkogut4 said or you could also try to use your movement spell from a high point in the jump and run. (A great point is after climbing the first ladder if I remember that correctly)

**Comment by ColinRioux** [comment]
Final comment: Wynncraft is hard coded to 1.8.9, therefore, there is conflict with the new textures/game mechanics. I'd take @thecoolkogut4's suggestion.
