### ISSUE TITLE
Im stuck in a hole.

### ISSUE THREAD

**Issue by WumboWill** [Wynncraft/Issues#7497]
There is a hole, at the coordinates -6022, 52, -12959. I got stuck in it, and I cant jump out, use a scroll, or jump out. If I could get some help that would be nice, as well as fixing this area, (It is part of the Craftmas Chaos Quest and my name in game is Willminer1234)

**Comment by Pyromanical** [comment]
Just do /kill with 5+ soul points. About fixing the hole, @ColinRouix can probably do that.

**Comment by ColinRioux** [comment]
This hole has already been fixed on build, and won't be pushed to main until Corkus. Thank you for reporting, however.
