### ISSUE TITLE
I am stuck in wall

### ISSUE THREAD

**Issue by Electro014** [Wynncraft/Issues#7499]
I'm stuck in the wall when I filled quest. Coordinates -1865 -4904 31. Scrolls does not work and I can not deliver. It is a quest Green Skined Trouble and my name in game is Electro014.

**Comment by LordHelmchen98** [comment]
Do /kill if you have more than 5 soul points. Unfortunately you may have to go through the last part again.

**Comment by Electro014** [comment]
Okay

**Comment by Electro014** [comment]
And when you do that?

**Comment by ColinRioux** [comment]
The hole at those coords has already been fixed on build, but won't be pushed to main until the release of corkus.
