### ISSUE TITLE
lost my mythic in ender chest bug :(

### ISSUE THREAD

**Issue by antoinegu** [Wynncraft/Issues#7501]
I put my mythic Pure in my ender chest and the next day I went in it wasnt there anymore I would like to know why did this happen and if I can get it back. :(

**Comment by LordHelmchen98** [comment]
I have no idea why it happend, but unfortunately you cant get your item back because Wynncraft enforces a strict norefund policy.

**Comment by antoinegu** [comment]
..................... :(

**Comment by Villageacules** [comment]
Closed due to uselessness of issue and the no-refund policy.
