### ISSUE TITLE
Lunar spire

### ISSUE THREAD

**Issue by Robotomy101** [Wynncraft/Issues#7502]
lunar spine ingame has a -% water damage ID, but on the wynncraft item guide it isn't listed. just thought I'd point it out
![image](https://cloud.githubusercontent.com/assets/26049035/23675420/586fd334-038a-11e7-9e28-acd3a181c44d.png)

**Comment by LordHelmchen98** [comment]
There are several items with missing stats on the homepage. Therefore you should use http://wynnapps.tk/item/ when you look up the item stats. It more reliable.

**Comment by ColinRioux** [comment]
The API won't be updated until after Corkus' release (considering many new items are being added). For now, use @LordHelmchen98 's suggestion.
