### ISSUE TITLE
gliched quest book quests

### ISSUE THREAD

**Issue by weshuiz** [Wynncraft/Issues#7504]
when doing my normal thing in wynncraft i noticed a very ennoying bug some quests for example a grave mistake is not completed in my questbook but when talking to the quest npc saying i have finishised the quest i claimed te reward and completed the quest still its syaing i never started the strange thing is if i look at the quests that i have completeded its not there aswell now im confused and not sure 
whats quests are left to do and what quest i finished not sure if other players have the same problem but i do at least

**Comment by LordHelmchen98** [comment]
Can you post screenshots of that problem?

**Comment by Pyromanical** [comment]
Are you sure you are talking to the right NPC about the quest?

**Comment by ColinRioux** [comment]
I kind of have a gist on what you are referring to, but like the above said, could you please be more specific and try to be as clear as possible. If english is your first language, please use grammar appropriately if possible. Thanks.

**Comment by weshuiz** [comment]
![proof](https://cloud.githubusercontent.com/assets/15715107/23799195/00cce3e0-05a8-11e7-96b6-eb2c8cf61141.png)

Notice that im having the ghostly cap in my inventory that is only be optaineble by doing the quest
aswell as the npc thanking me now look at the quest book it says i did not even start it while i already have done it and this is not the only quest that is gliched for me further quests aswell

**Comment by weshuiz** [comment]
seems i have been mistaken sorry for bothering
