### ISSUE TITLE
Crash when i try to download the ressouce pack 

### ISSUE THREAD

**Issue by Troge** [Wynncraft/Issues#7505]
Hi, when I connect to the server, I choose one server to play, it tells me if I want to download the pack and when I try to download it, my game crash. I tried to set on the server settings enabled for server pack but it's not actually working.
Thanks for helping me (if I don't talk very well it's normal because I'm Tunisian )

**Comment by Troge** [comment]
ok now when i try to enter a server of winncraft 
![capture d ecran 10](https://cloud.githubusercontent.com/assets/26282234/23715818/366a6d04-042e-11e7-87e8-5ff26ded4766.png)

**Comment by Pyromanical** [comment]
I have looked this up, and according to Google, you can fix this by going into your .minecraft folder, and creating a folder called `server-resource-packs`.  If you aren't sure how to access the .minecraft folder, there are lots of tutorials on YouTube.

**Comment by Troge** [comment]
thank you but it still not working

**Comment by ColinRioux** [comment]
It seems you asked this on the forums, and are getting more luck there. This is client side as well, not directly server related. If you feel that the forums were a dead end, feel free to post a new issue including as much detail as possible.
