### ISSUE TITLE
Lvl 35 in starting area/quests

### ISSUE THREAD

**Issue by mathias0903** [Wynncraft/Issues#7506]
okay so i just did stable story to get a horse i shifte item and it despawned like it shoul but i begin glicthing so i disconect when i join back in im in the area you start in as lvl 1. like i could easy get out. its just a bit anyoing/werid
![wynecraft bug](https://cloud.githubusercontent.com/assets/16622186/23720087/f503760c-043d-11e7-9ca9-e3cb70f249e7.png)

**Comment by Pyromanical** [comment]
When you die, you respawn in the closest spawn point, which is normally a town.  I'm guessing that Stable Story has a part not on the main map.  When you die off-map, you usually respawn back at the starting area.  This is a well know bug.  All you have to do is walk through the area again.

**Comment by mathias0903** [comment]
well he is the thing i had finshed the quest. so in other words i was not in a dungeon or anything i was in Ternaves. and i know there is a respawn point there and i i didn´t die and im sure since i didn´t lose souls. so thats not the case. i belive it caused by spawning me in befor loading my progresse or somthing in that line
but i can see that my first text(and probaly this too) is a little hard to read and i apoligaze for that. english isn´t my first languhe.

**Comment by ColinRioux** [comment]
The start area is sort of a fail safe. So when you glitch or are in an area outside the map, if the backend server is unsure of where you are (like if the coords weren't saved to the database), it'll send you to the tutorial area. It's not a big deal to walk or use your horse to go back to Detlas/Almuj, but at least be glad that you weren't sent to a place that was further away. 

Thank you for reporting the issue, but I and the other members of the team are already aware of this issue. No idea on when it will be fixed, but know that it is logged.
