### ISSUE TITLE
/Fixquests gave me items from quests I have already completed.

### ISSUE THREAD

**Issue by goldimp6** [Wynncraft/Issues#7511]
I did /fixquests and got these 3 items, Chuckles favorite feather (Used for Cluck Cluck and Bob's Tomb), Healing water (Forget) and Receipt (Also a bug, I picked the elf madalian) And I cant get them out of my inv or bank what do I do?

**Comment by LordHelmchen98** [comment]
Put those unwanted items into your daily reward chest the next time you can claim it.
