### ISSUE TITLE
Items disappear.. 

### ISSUE THREAD

**Issue by 123457665617501** [Wynncraft/Issues#7512]
So basically I logged on with my inventory full. the server lagged and said "Lapis Necklace requires your intel to be 35" happened to everything. Then it all just disappeared. Uhh pls fix this?

**Comment by LordHelmchen98** [comment]
Unfortunately this bug exists for a very long time now and was tried to fix already, but there is no solution yet as far as I know. Apparently the game thinks you don't have the required skill points for accessories sometimes so they get kicked out of their respective slots into empty ones or into the void if you don't have empty slots. In future you should keep an empty inventory slot for every equipped accessory that requires skill points.

**Comment by Pyromanical** [comment]
#4120 is the original issue if you'd like to read more about it.
