### ISSUE TITLE
Galleons graveyard teleport bug

### ISSUE THREAD

**Issue by ArctiKdiablo** [Wynncraft/Issues#7513]
Basicly, 
I go trough galleons graveyard,
and after i kill the armoured pirate, i click the button, and go trough the door,
this initiates a teleport,
after that teleport i get put in a invis box, to see the dialog and have a overview,
But after this, it does not initiate the bossfight, it keeps me stuck in the box..

This has happened 3 out of 3 times for me so far,
and it is starting to get upsetting..

**Comment by ColinRioux** [comment]
Hi, like I've said to most people, we have been working on Galleon's Graveyard in preparation for Corkus, and have attempted to permanently fix all of the current bugs (which includes this one). Although, even when we fix bugs, new ones may arise. 

For now, the new and improved Galleon's Graveyard won't be pushed until the next map update, which is Corkus. I cannot disclose the release date, but it's soon™. For now, you'll have to wait and probably not do the dungeon if this has happened 100% of the time.

**Comment by ArctiKdiablo** [comment]
I have found a temporary fix for the dungeon, it might help with the
building process.
Relogging minecraft versions seems to always unstuck me now.
