### ISSUE TITLE
breathing helmet

### ISSUE THREAD

**Issue by sintiope** [Wynncraft/Issues#7514]
we can't make unederwater with the breathing helmet2

**Comment by thecoolkogut4** [comment]
do you mind explaining your issue a little bit more?

**Comment by ColinRioux** [comment]
You're supposed to complete the quest Underwater to get the Breathing Helmet I. In order to get the breathing helmet II, you need the breathing helmet I and must do Underice. You're not supposed to do Underwater with the breathing helmet II.

**Comment by AmbassadorArt** [comment]
you're not supposed to be able to start the Underice Quest (which is what the breathing helmet II is for) without having and handing over the Breathing Helmet I.  Therefore, if you want to do the Underwater Quest with "your friend," unless you have a Breathing Helmet I somewhere then you can't.  To get another Breathing Helmet I, do Underwater on a different class.

**Comment by ColinRioux** [comment]
The swimming to the treasure part of the quest really isn't that exciting, and could be the part that your friend does alone. The breathing helmet II isn't meant to work there, only the breathing helmet I. Follow @AmbassadorArt 's advice and get another breathing helmet I by doing the quest on another class and that transfer via your bank between other classes.
