### ISSUE TITLE
i cant open loot chests and push buttons

### ISSUE THREAD

**Issue by bruggmire** [Wynncraft/Issues#7516]
when ever i try to open a loot chest or push a button it says that you dont have permission to use this area

**Comment by thecoolkogut4** [comment]
try to open the loot chest/push the button with your soul point, or with an empty hand.

**Comment by bruggmire** [comment]
it worked but it doesn't make sense

**Comment by Pyromanical** [comment]
It is because the item you were using was a retextured half-slab, and the game thinks you were trying to place it, so it says you don't have permission to.  Just do what @thecoolkogut4 says are you'll be fine.
