### ISSUE TITLE
Powder Stacking

### ISSUE THREAD

**Issue by TheCatArchy** [Wynncraft/Issues#7517]
There's an issue where powders (of any kind/tier) won't stack if they drop from a powder imp or the flarelings. I was wondering if this is going to get fixed or not because it's kinda annoying to have to make 2 separate stacks :/ I think it's something with the items dropping as ink sacks instead of actual powder, but that could be wrong. Either way, just hoping for a fix!!

**Comment by thecoolkogut4** [comment]
duplicate of #5871

**Comment by TheCatArchy** [comment]
@thecoolkogut4 That thread is talking about old powders/merchant powders. I mean imp/flareling powders, or is it still the same?

**Comment by Moe-Ronickah** [comment]
It's the same.  We know about it, and a fix is in the works.

**Comment by TheCatArchy** [comment]
Ok, thanks!
