### ISSUE TITLE
Sage wand "You don't have permission..."

### ISSUE THREAD

**Issue by GreenByteSoftware** [Wynncraft/Issues#7518]
Hello,
It seems that my sage wand started to act weird. It did not happen before. When I right click on the ground or whatever it says in the chat "You don't have permission for this area." and it does not happen with other wands. I did not experience this before. My minecraft username if you need to check the item is GreenByte.

**Comment by GreenByteSoftware** [comment]
Update, just identified a new sage wand and it does not happen.

**Comment by weshuiz** [comment]
the error message "you do not have permission for that" is more commen then you think i also seem to have but but in my case it do not matter what whand i pick. as i use the teleport spell i also seem to get that error but with teleport only

**Comment by thecoolkogut4** [comment]
It is because the item you were using was a retextured half-slab, and the game thinks you were trying to place it, so it says you don't have permission to. To fix this right click with a empty hand/soul point.

**Comment by ColinRioux** [comment]
@thecoolkogut4 has the correct information. This may or may not be fixed in future updates, but as long as the server stays 1.8.9, it won't change.
