### ISSUE TITLE
Im stuck in ice dungeon

### ISSUE THREAD

**Issue by ZefengPlayz** [Wynncraft/Issues#7520]
the the part where u have to run across, the door is not opening, and i really have to do this dungeon to lvl up. Can you guys plz help me
![stuck](https://cloud.githubusercontent.com/assets/13813974/23826701/d6365828-0656-11e7-925f-03451e82b944.PNG)

**Comment by LordHelmchen98** [comment]
Have you tried switching the server?

**Comment by ZefengPlayz** [comment]
yea it worked, i thought if you switch server the dungeon will kick u out

**Comment by LordHelmchen98** [comment]
Only if you are in a boss room iirc.
