### ISSUE TITLE
Lost 48 emeralds blocks

### ISSUE THREAD

**Issue by Deelun345** [Wynncraft/Issues#7521]
I was bought 2 horses to breed and my inventory was full so i dropped 2 pieces of armor and I bought the horses and when i put them in the crafting i accidentally picked up the armor and when i click on it, it disappeared and i lost 48 emeralds block please can i have it back.

**Comment by LordHelmchen98** [comment]
Unfortunately Wynncraft enforces a strict norefund policy. Therefore you wont get the two horses back.
