### ISSUE TITLE
Banned for Hacked Client by opening Enderchest?

### ISSUE THREAD

**Issue by DwarriorD** [Wynncraft/Issues#7523]
I was on Santa Island and indentiefed a wand, opened my Enderchestand got banned for using hacked client? I don't get this so i'm asking for an urban I guess...

Kind Regards Daniel

**Comment by thecoolkogut4** [comment]
Go to [this page](https://forums.wynncraft.com/threads/%E2%9C%8E-appeal-submission-guide-%E2%9C%8E.89247/) on the forums and follow the instructions on the page.
