### ISSUE TITLE
item bug

### ISSUE THREAD

**Issue by pompeijwang** [Wynncraft/Issues#7524]
Hi wynncraft.
I had a promblem. My wand disappared the wand that i had was gained from the quest "the shadow of the beast" so there are no way to get it back. 
here is what happend: i was riding my horse while mobs attacked me. then I got off my horse and tried to acttack with my wand but it didnt work, i try casting a spell, it didnt work so i loged off wynncraft and when i got on. my wand just disappeared.
I really want my wand back cuz there are no way to get my wand back since it gained from a quest. I know it a lot to ask for to get an item that is obtained from a quest so if you sont want to give me wand back i understand.

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.
