### ISSUE TITLE
Banned Unfairly For Store Chargeback

### ISSUE THREAD

**Issue by KnixFice** [Wynncraft/Issues#7525]
To Whom this may concern, a dearest friend of mine, Rosoideae, was recently banned for a Store Chargeback. The reason this was unfair, was due to the fact that the rank was not purchased by her, but by her spouse, who is no longer supporting her. This spouse had evidently taken all of the money he had spent on her in the past 6 months, which includes the rank that he had bought her. I, KnixFice, will condone to the price withdrawl from that whom lost the money, so that Rosoideae can and may be able to play on the WynnCraft servers, once again.

- KnixFice

**Comment by thecoolkogut4** [comment]
For any store related issues, email support@wynncraft.com and they will help you resolve it.
