### ISSUE TITLE
Sand swept tomb - boss glitched out of map

### ISSUE THREAD

**Issue by TheMiscreatedGamer** [Wynncraft/Issues#7526]
Me and a friend battled against the boss Hashr earlier today, and it killed my friend. Upon it doing that it teleported out of the arena and was stuck there. I'm also stuck and IDK what to do.

**Comment by Numbermaniac** [comment]
/kill to get out, if you have more than 5 soul points.

**Comment by TheMiscreatedGamer** [comment]
I did the /kill, but I think that bug should be fixed because I lost out on fighting hashr due to it.

**Comment by ColinRioux** [comment]
Unfortunately, it's extremely hard to prevent mobs from glitching through walls or moving out of arenas, especially when there are spells like uppercut, war scream, and ice snake. There are many layers of blocks and barriers outside of each fighting space, mainly to prevent mages from teleporting out of the map. If a mob gets outside, there's really nothing that we can do. 

This is also a well known issue. We appreciate you reporting it, and we can assure you we're doing our best to fix it. Cannot tell you when or if it'll be fixed when Corkus is released. 

In the future, I'd be more careful with your spells if you want to prevent this issue.
