### ISSUE TITLE
Not allowed to open loot chests

### ISSUE THREAD

**Issue by scareLOL444** [Wynncraft/Issues#7528]
When trying to open loot chests it only returs the mesage "You don't have permission for this area." and does not open the chest. I have disconected-reconnected on the sevrer and it still does not work. It also does it on buttons.

![2017-03-13_19 47 00](https://cloud.githubusercontent.com/assets/26390570/23870726/b411c098-0827-11e7-84c1-255f5a8f20a8.png)
![2017-03-13_19 44 39](https://cloud.githubusercontent.com/assets/26390570/23870728/b4175a26-0827-11e7-9e55-2a57ebeb7adc.png)
![2017-03-13_19 45 29](https://cloud.githubusercontent.com/assets/26390570/23870727/b41486a2-0827-11e7-8eb3-d50c897dcdb5.png)
![2017-03-13_19 46 19](https://cloud.githubusercontent.com/assets/26390570/23870729/b41c4180-0827-11e7-827f-df7200362b78.png)

**Comment by scareLOL444** [comment]
Also the 13 soul points might not be normal and the only mod i'm using is optifine

**Comment by Pyromanical** [comment]
It is because the item you were using was a retextured half-slab, and the game thinks you were trying to place it, so it says you don't have permission to. To fix this right click with a empty hand/soul point.

**Comment by scareLOL444** [comment]
ok it worked thanks but it had alwas worked with this item before today

**Comment by Pyromanical** [comment]
Did you switch from 1.9+ to 1.8?  That might have been the reason you weren't getting it earlier.

**Comment by scareLOL444** [comment]
no I did not changed versions between before and after the message shown up I'm still in 1.11.2

**Comment by thecoolkogut4** [comment]
are you using an item skin? maybe it's because there was a mini update last night. not too sure, sorry
