### ISSUE TITLE
What happened to my Defenses?

### ISSUE THREAD

**Issue by AmbassadorArt** [Wynncraft/Issues#7529]
I started playing on my Mage again a few days ago and while adventuring around Sky Islands I felt like I was taking a suspiciously high amount of damage, so I checked my Defense Info and saw this...

![2017-03-12_16 37 14](https://cloud.githubusercontent.com/assets/8008265/23876020/f2868f2c-0811-11e7-95d2-71b481727d65.png)

Something is artificially lowering those Elemental defenses a LOT, which makes no sense because when I do the actual math for the equipment I DO have affecting these numbers, (Aquarius, Marsh Waders, Memento and Squid Anklet) I should supposedly have...

0 Fire, 
-100 Air
+60 Earth
-320 Thunder
+290 Water

I'd like some clarity as to whats going on here, if it's even affecting my gameplay and if so how do I fix it?

**Comment by thecoolkogut4** [comment]
duplicate #3179

**Comment by AmbassadorArt** [comment]
Well it would be duplicate if not for something I forgot to mention; this problem is ONLY on my Mage class.  All my other class's Compass Stats are accurate

**Comment by ColinRioux** [comment]
It's still a duplicate; I'll summarize in issue #3179 to keep all information in one issue. Thank you for reporting, however.
