### ISSUE TITLE
API returns invisible character after "???"

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#7531]
There is an invisible Unicode character returned by the API after the `???` in `"quest": "???"`.

<img width="1012" alt="screen shot 2017-03-14 at 11 25 18 am" src="https://cloud.githubusercontent.com/assets/16504771/23916367/2ab98f38-08a9-11e7-8ed4-5c277751f728.png">

See this for yourself via [`action=itemDB&search=Cosmic`](https://api.wynncraft.com/public_api.php?action=itemDB&search=Cosmic). This error is not exclusive to the Cosmic Set.

**Comment by LordHelmchen98** [comment]
Its not ingame but if you open the api in your browser ([look here](https://api.wynncraft.com/public_api.php?action=itemDB&search=Cosmic)) it shows you this icon: ֎

btw what tool are you using, I've never seen that.

**Comment by 0x0000null** [comment]
That's PyCharm with dark theme.

**Comment by ColinRioux** [comment]
Although it can be annoying that it returns an invisible character, there are many work arounds that you can come up with. Also 72k lines :/. 

By any chance, does this invisible character only appear when you are using PyCharm? I'm away on vacation at the current moment and cannot access a computer at this time.

**Comment by 0x0000null** [comment]
It just appears as a box when using that font (Fira Code). Using most other fonts will make it invisible, but it's still there.

**Comment by Numbermaniac** [comment]
I recall somebody saying in-game that it's actually intentional. The null character is added after the name because "???" was already taken by the [old ??? quest](https://wiki.wynncraft.com/index.php?title=Old_%3F%3F%3F_Quest), so they threw in an invisible character to give it a different name internally, but still appearing as "???" to the player.

**Comment by Villageacules** [comment]
This is for a reason, the character is actually used to indicate is the second ??? quest.
