### ISSUE TITLE
"Level 5" loot chest in level 40 area

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#7532]
[deleted]

**Comment by Numbermaniac** [comment]
Potions in loot chests seems to be peculiar. I think one near the Pigmen's Ravine entrance gives potions for your level instead of for around level 15, so it seems like a few are broken.

**Comment by 0x0000null** [comment]
I know that there are some cheats that give loot depending on your level and some that give loot of a fixed level. However, I haven't seen a loot chest that gives loot of an incorrect level before.

**Comment by thecoolkogut4** [comment]
loot chests give loot based off of the mobs level that are around it. if there are no mobs it goes off of the players level. is there any chance a low leveled mob was near you?

**Comment by 0x0000null** [comment]
No, and that doesn't explain why the chest right next to it gives level 40 items.
