### ISSUE TITLE
galleon's graveyard

### ISSUE THREAD

**Issue by Xoerium** [Wynncraft/Issues#7534]
il dungeon galleon's graveyard, si bugga nel discorso del pirata,costringendo il pleyer ad suicidarsi.

the dungeon galleon's graveyard, you bugged in pirate talk, forcing the Pleyer to suicide

**Comment by LordHelmchen98** [comment]
This bug is known. It has already been fixed on the build server, but it will be pushed with the Corkus update so you have to be patient.
