### ISSUE TITLE
Stuck in the map

### ISSUE THREAD

**Issue by Kisuno22** [Wynncraft/Issues#7536]
Hello,I'm french so, sorry for my English. ^^
I'm stuck in the map, I can't use the teleport. : /

![2017-03-14_22 27 05](https://cloud.githubusercontent.com/assets/26419918/23923409/dac5fbde-0906-11e7-853e-bfb159a3969f.png)

Thanks advance for your help,
Bye.

**Comment by LordHelmchen98** [comment]
Try to use a scroll if you have one. If that doesnt work out you can do /kill.

**Comment by Kisuno22** [comment]
Thanks 👍
