### ISSUE TITLE
Boss health bar

### ISSUE THREAD

**Issue by Feniku** [Wynncraft/Issues#7537]
For a while now, I've relived that I don't seem to have a Health Bar at the top of my screen can displays Towns/Guild level, and I have no idea how to fix this, please help me out

**Comment by LordHelmchen98** [comment]
I assume you are using the MC version 1.8. Unfortunately the bar isn't shown in that version. Use 1.9+ if you want to see it again.

**Comment by Feniku** [comment]
Alright
