### ISSUE TITLE
API returns VIP+ instead of Hero

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#7538]
The API says that my tag is `VIP+` even though I am `HERO` in-game.

<img width="609" alt="screen shot 2017-03-14 at 7 09 01 pm" src="https://cloud.githubusercontent.com/assets/16504771/23930477/c47a568a-08e9-11e7-8095-58a09584240c.png">|<img width="410" alt="screen shot 2017-03-14 at 7 09 22 pm" src="https://cloud.githubusercontent.com/assets/16504771/23930478/c532a672-08e9-11e7-8ffb-b2810f1989d1.png">
:--:|:--:

**Comment by ColinRioux** [comment]
Hero hasn't been added to the API yet, no known date on when it will be.
