### ISSUE TITLE
guildStats API does not return a player name in some cases

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#7539]
[deleted]

**Comment by LordHelmchen98** [comment]
I have no idea what PyCharm is doing there but please just look it up in a normal browser because it's shown just fine there. ([proof](https://api.wynncraft.com/public_api.php?action=guildStats&command=HackForums))

**Comment by 0x0000null** [comment]
>normal browser

I would be very surprised if the results differed depending on your browser. I downloaded the API response via `curl -fsSL '<url>' | jsonpp > hackforums.json`.

I know it's hard to see because it's not formatted but here it is in a "normal browser":

<img width="1085" alt="screen shot 2017-03-15 at 7 45 36 am" src="https://cloud.githubusercontent.com/assets/16504771/23954080/95e95392-0953-11e7-928f-6f07c07f84c1.png">

**Comment by LordHelmchen98** [comment]
Oh Im sorry I looked at the wrong thing and mixed it up. However I guess thats related to players glitching in guilds because of name changes. (#3665) Hopefully guilds will be rewritten soon but until that happens nothing will change here I guess.

**Comment by ColinRioux** [comment]
Unless I get to work on updating the API directly, I have no idea when this will be fixed, but I'll direct Elements here so he can see some of the issues. I can agree with @LordHelmchen98 in that I would assume after a name change the contribution and join date remains present (maybe in the case the player changes their name back). I realize it would be nice to not have that json object be there, but you could use an if statement and ignore it if it doesn't have certain fields. At least that's what I do.

**Comment by thecoolkogut4** [comment]
Christine and godly are one of the two oldest members in my guild.  I believe that could be causing the issue

**Comment by LordHelmchen98** [comment]
@thecoolkogut4 He is not talking about those two but about the paragraph below where you can see an incomplete member with only "contributed" and "joinedFriendly" but the parts "name", "rank" and "joined" are missing.
