### ISSUE TITLE
API returns wand named "default"

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#7540]
Is this intended?

<img width="1557" alt="screen shot 2017-03-15 at 8 49 36 am" src="https://cloud.githubusercontent.com/assets/16504771/23957445/9f2d2056-095c-11e7-93b5-757519713480.png">

See this for yourself via [`action=itemDB&search=default`](https://api.wynncraft.com/public_api.php?action=itemDB&search=default).

**Comment by ColinRioux** [comment]
Clearly it's a test item for the API. Intended or not, I don't think it poses any harm.

**Comment by Pyromanical** [comment]
"When you hit a mob with anything but a weapon (hand, random items) it will take the damage data from the "default" wand, which is 1-2." - Salted on a thread about this item

**Comment by 0x0000null** [comment]
TIL. Strange that it also gives +9 (base) intelligence.

**Comment by ColinRioux** [comment]
Oh interesting, still, the lore seems like a test item.
