### ISSUE TITLE
API erroneously adds backslashes to item lore

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#7543]
When square brackets (and possibly other characters) are added to the lore of an item (e.g. in `[Community Event Winner]`), two backslashes (or one backslash, after the string is parsed) are inserted before them in the API response.

<img width="870" alt="screen shot 2017-03-15 at 3 23 25 pm" src="https://cloud.githubusercontent.com/assets/16504771/23973428/64c04948-0993-11e7-9685-172a81f34903.png">

See this for yourself: [`action=itemDB&search=Sigil%20of%20Existence`](https://api.wynncraft.com/public_api.php?action=itemDB&search=Sigil%20of%20Existence)

**Comment by ThunderRemix** [comment]
Please, stop making these "issues" without explaining why they are "issues".

**Comment by 0x0000null** [comment]
The API adds backslashes before brackets in the item lore. This is incorrect as the string then expands to `\[Community Event Winner\]`. The backslashes do not appear in-game.

Is this intentional? Almost certainly not.

Is it a small issue? Yes. But that doesn't mean it shouldn't be fixed.

Is there a workaround? Yes--removing the backslashes in one's code. But it is quite hacky and it probably won't work in all situations.

Is there a reason to report it? Yes--I wanted to make sure that the issue is known and possibly get it fixed.

**Comment by Villageacules** [comment]
Again, this is intentional for proper formatting of the items. Notice how the \\s are before brackets.

**Comment by 0x0000null** [comment]
If the backslashes are removed in-game, why doesn't the API remove them?

**Comment by LordHelmchen98** [comment]
Because the api shows you the raw code and not the ingame information.

**Comment by Villageacules** [comment]
@0x0000null same reason why "&r&bLegendary Item" doesn't look like that in-game. Raw code =/ in-game text.

**Comment by 0x0000null** [comment]
|<img width="344" alt="screen shot 2017-03-20 at 11 25 16 am" src="https://cloud.githubusercontent.com/assets/16504771/24115237/ed6ab740-0d5f-11e7-84ba-557138ed04cf.png">|
|:--:|
