### ISSUE TITLE
Quest "WynnExcavation Site A" Impossible To Complete (For Me)

### ISSUE THREAD

**Issue by Bentcody** [Wynncraft/Issues#7544]
So I was doing the WynnExcavation Site A quest, and after clearing the tomb, the quest book says to go to Excavator Vade. I talked to him and he told me to bring a paper to the npc tesha. The cycle just repeats over and over so I have no idea what to do, is this a bug?

**Comment by LordHelmchen98** [comment]
Did you get a yellow crystal shard from the pharaoh?

**Comment by Bentcody** [comment]
no, he Isn't dropping it

**Comment by LordHelmchen98** [comment]
Have you tried it on different servers?

**Comment by teuntheman** [comment]
Did you kill the enemy in the temple?

**Comment by OMGitzRona** [comment]
found the solution, i hads the same thing. you need to kill again the pharaoh and go the vade

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
