### ISSUE TITLE
Lost Sanctuary (Animal Dungeon), Unable to proceed?

### ISSUE THREAD

**Issue by Mikutom** [Wynncraft/Issues#7545]
Hey! Thanks for reading this, first of all.

I'd like to report a bug on the Lost Sanctuary Dungeon, once known as the Animal Dungeon. In the dungeon, there are many parts (Of course.), the part which has a bug is the 2nd part. Running across a burning bridge that Garoth will burn down.

When I run past the monsters in the dungeon, I try to run past the bridge. However, I do not have to ability to do so. I cannot express the bug in words, but the video here speaks for itself.

https://youtu.be/i1Ya_EO-CXY

**Comment by LordHelmchen98** [comment]
Have you tried to switch servers?
When I tried it a few minutes ago I had no problems at this bridge.
https://youtu.be/bZyu4h0xipw

**Comment by Mikutom** [comment]
I don't believe I tried.. But I will attempt it. I'll get back to you ASAP.

**Comment by Villageacules** [comment]
@Mikutom I'm assuming that fixed the issue, I'll go ahead and close this. Contact me if anything else comes up regarding this issue, dungeons are important.
