### ISSUE TITLE
??? QUEST BUG

### ISSUE THREAD

**Issue by BeatsDJ** [Wynncraft/Issues#7548]
-

**Comment by LordHelmchen98** [comment]
Is it possible the person who got the painting switched classes or worlds? Because there is an issue with NBT tag which cause the painting to break after a class or server switch.

**Comment by BeatsDJ** [comment]
We were 4 people.

First I tried putting the items, same server, same class. - nothing
After that, my friend tried - nothing
We switched servers and another friend tried, - nothing

Now we still have one more friend with the items and he didn't use them yet.

**Comment by LordHelmchen98** [comment]
When trying again get the painting again. You have to get it on the same server and with no class change between getting it and dropping it into the hopper.
