### ISSUE TITLE
Stuck in Galleon's Graveyard

### ISSUE THREAD

**Issue by ReiSonata** [Wynncraft/Issues#7551]
I'm currently stuck in the dungeon in a cut scene with boats and undead pirates. please help

**Comment by LordHelmchen98** [comment]
What MC version are you using?

**Comment by ReiSonata** [comment]
I am using the latest version. later ,however, I came back on to find a hole in the cut-scene skipping that portion entirely.

**Comment by RubbrDucky** [comment]
Try using 1.8.9. Wynn was built for it.

**Comment by TiagoBr03** [comment]
I stuck at a scene of the ??? and The undead pirates on the ship i don't get teleported to the other ship and the ??? is not moving i had to /kill 2 times pls fix that because im suck of this i took so long for 4 Keys and it was only wasting time.

**Comment by Moe-Ronickah** [comment]
dupe of #7264
