### ISSUE TITLE
API returns "xp": null for Jumla's level 0 class

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#7553]
The API returns `"xp": null` for Jumla's level 0 mage class.

```javascript
{
  "username": "Jumla",
  "rank": "Administrator",
  ...
  "classes": {
    ...
    "mage": {
      "level": 0,
      "xp": null,
      "dungeons": {},
      "quests": ["King's Recruit"],
      "dungeonsAmount": "0 / 8",
      ...
      "playtime": 2611
    }
  },
  ...
}
```

See this for yourself via [`action=playerStats&command=Jumla`](https://api.wynncraft.com/public_api.php?action=playerStats&command=Jumla).

**Comment by ThunderRemix** [comment]
Please, stop making these "issues" without explaining why they are "issues".

**Comment by 0x0000null** [comment]
At first glance, I assumed that `"xp"` should never be `null` because that would mean that the player has no XP value. Thus, I wrote code on the assumption that `"xp"` will never be `null` and put it in a string without checking if it was `null` or not. Then one day, I requested Jumla's stats and got an error.

Is this intentional? Almost certainly not.

Is it a small issue? Kind of. But that doesn't mean it shouldn't be fixed.

Is there a workaround? Yes--checking if the field is `null` first.

Is there a reason to report it? Yes--I wanted to make sure that the issue is known and possibly get it fixed.

**Comment by LordHelmchen98** [comment]
It is not intentional to have a level 0 class either ...
I guess Jumla edited something in the code to give himself a level 0 class and I assume he didn't set any xp value or maybe that's necessary. Could be way off though as I'm not used to that stuff.

**Comment by Villageacules** [comment]
Admins do all kinds of crazy stuff with their levels, this isn't a bug.
