### ISSUE TITLE
Masks' skins not working

### ISSUE THREAD

**Issue by Moarsh** [Wynncraft/Issues#7556]
So I bought a mask from the Ibujo village (near Troms) and I swapped worlds and now my Mask Of Fear turned into a Steve head. It would be nice if the devs can patch this glitch and it's quite annoying to see yourself having a giant steve head, my friend ImLara has the same problem with me and I can see her Steve head so it's not a problem which 1 player can only see, all the server can
![2017-03-19_13 47 15](https://cloud.githubusercontent.com/assets/26526612/24083311/050d4c7e-0cab-11e7-99e7-732527607192.png)
![2017-03-19_13 50 38](https://cloud.githubusercontent.com/assets/26526612/24083312/0d95e194-0cab-11e7-9302-40f8268241f3.png)

**Comment by LordHelmchen98** [comment]
That happens after a class or server switch because NBT tags are missing after a change. I don't know if that can be fixed, but if it is I doubt it has a high priority as it is just a visual thing and not gamebreaking.

**Comment by ColinRioux** [comment]
Closing as it has been reported already, and the QA team is well aware of this issue.
