### ISSUE TITLE
"There has been an error.. Try again."

### ISSUE THREAD

**Issue by Iannbeas** [Wynncraft/Issues#7558]
Hello! Today I was playing with my friends and they told me to play on this server, but I received this message saying "There has been an error.. Try again."

I tried picking all the different classes, but it didn't work. Is my character data corrupt or something? Please help.
![2017-03-19_17 53 00](https://cloud.githubusercontent.com/assets/26531254/24086453/e643c0e4-0ccc-11e7-96cf-6ed4cfed4860.png)

**Comment by Pyromanical** [comment]
I would suggest reading @Moe-Ronickah's post on #5418, and see what you want to do

**Comment by Iannbeas** [comment]
I just read it @Pyromanical 

How can I contact him so he can "wipe my data" ?

**Comment by ColinRioux** [comment]
@Iannbeas you can either comment on #5418 or message Moe_Ronickah on the forums for more information. I suggest doing both.

**Comment by LordHelmchen98** [comment]
@Pyromanical @ColinRioux #7185

**Comment by Herugaa** [comment]
same help pliz
