### ISSUE TITLE
Tp bug "Green Skinned Trouble"

### ISSUE THREAD

**Issue by ZyFox2212** [Wynncraft/Issues#7561]
I am blocked in a wall because the tp after the boss in the quest "Green Skinned Trouble" dosen't work. 
I have no way to go outside the wall, someone can help me ? 

Screenshot: http://i.imgur.com/88U9K76.png?1

(Sorry for my bad english)

**Comment by LordHelmchen98** [comment]
If you have more than 5 soul points do /kill. (You might have to walk through again, but the teleport bug doesn't happen everytime)

**Comment by ColinRioux** [comment]
That hole has already been reported and already been fixed. Thank you though, for your report.
