### ISSUE TITLE
Quest: A Fighting Species

### ISSUE THREAD

**Issue by SmirrenIsMyName** [Wynncraft/Issues#7562]
So after I've killed Gorgu and walked through the portal back to the surface I ended up falling through a block and got stuck in the redstone contraption. Please take me out of here and resolve this bug

![2017-03-20_18 40 19](https://cloud.githubusercontent.com/assets/26552191/24113605/9efeac54-0d9d-11e7-98fa-a72034f139d5.png)

**Comment by SmirrenIsMyName** [comment]
Changing server did not help the issue. Also I am currently online and will wait until I get freed

**Comment by LordHelmchen98** [comment]
Do /kill if you have more than 5 soul points.

**Comment by SmirrenIsMyName** [comment]
Oh I did not know about this command. luckily I got teleported out. but thanks anyways :)

**Comment by ColinRioux** [comment]
Filled this hole, thank you!
