### ISSUE TITLE
Glitch with Veteran rank and time played

### ISSUE THREAD

**Issue by Wiihacker0** [Wynncraft/Issues#7564]
Hey I'm having an issue were I started playing 4 years ago but I don't have a Veteran rank, also my time played is all wrong, it says only 31 hours, but I know for sure I've played more. I have a total level of 236 with no vips. I'd appreciate any feedback
Thanks
-SpamKappa

**Comment by LordHelmchen98** [comment]
Only players who purchased a rank before the EULA update in August 2014 got a veteran rank and the time shown on the stats page is about a fifth of the real playtime.
