### ISSUE TITLE
Breathing Helmet I when I completed Underice?

### ISSUE THREAD

**Issue by Anthanay** [Wynncraft/Issues#7565]
I was doing the From the Mountains quest and in one step, they asked me to get a Breathing Helmet. So, I got my Breathing Helmet and noticed that it was a Breathing Helmet I when I completed the Underice quest. It wouldn't let me proceed without a Breathing Helmet I. Please help!
![2017-03-20_16 31 10](https://cloud.githubusercontent.com/assets/26558020/24126526/a4604d7c-0d8b-11e7-984c-57686fd080d4.png)
![2017-03-20_16 34 06](https://cloud.githubusercontent.com/assets/26558020/24126528/a73be1dc-0d8b-11e7-97b5-bfc67b949b32.png)

**Comment by LordHelmchen98** [comment]
For From the Mountains you need the Breathing Helmet II which can be bought from the armor merchant in Nesaak.
