### ISSUE TITLE
Ice Barrows - Hopper ate my weapon

### ISSUE THREAD

**Issue by Rigzd** [Wynncraft/Issues#7566]
On the first stage of the Ice Barrows Dungeon I accidentally threw my Level 42 Legendary Lightning Bolt Bow with thunder dust II on it into the hopper. Seeing as how it's a relatively easy mistake to make and you can't even open the hopper to get the mistakenly dropped item back. I would be thrilled if it could be returned to me. Thanks! 

My IGN: Rigzd

**Comment by Numbermaniac** [comment]
Sorry, but Wynncraft has a very strict no-refund policy. It's happened to people in the past - just make sure to be more careful next time :)
