### ISSUE TITLE
stuck in Galleon's graveyard

### ISSUE THREAD

**Issue by FrodobagginsTNT** [Wynncraft/Issues#7567]
Hello people on the forums, a friend and I were doing the Galleon's graveyard dungeon today, and I was waiting for him in the part with the cutscene where redbeard speaks of manning the cannons, and I fell in the water while exploring the boat. Instead of teleporting me back to the boat, it teleported me to a ship across the water that no one seems to have posted anything about. It contains four cannons activated by pressure plates, which create explosions when used.
Despite the fact, however, that it says to counter enemy fire, there is no enemy fire to counter, and it is therefore impossible to advance.
I have tried:
- using the escape spell to get to the opposite boat (blocked by barriers)
- using the land on the side to get to the opposite boat (blocked by barriers)
- shooting endlessly at the other ship
  Neither of these yielded any results.
![2017-03-21_15 46 12](https://cloud.githubusercontent.com/assets/26575144/24153290/4c101b20-0e4e-11e7-9be4-c3d60fe0b826.png)

![2017-03-21_15 39 35](https://cloud.githubusercontent.com/assets/26575144/24153269/3ff2fb00-0e4e-11e7-9777-16ab8e13e0d4.png)

Am I the only one who has experienced this issue?

**Comment by Pyromanical** [comment]
In case you don't know, do /kill to get out.  A number of issues on this dungeon have been reported, and it has been fixed on the build server, so this issue has probably has been fixed to.  These fixes will be pushed to the main server next map push, which will be Corkus.

**Comment by FrodobagginsTNT** [comment]
Pyromaniacal, thanks for your reply. I am aware of the fact that you can do /kill to get out, and I did that, but I was actually wondering what on earth the place is (old version of the dungeon, part of the dungeon still in development, or something else???). The reason I reported it in the first place was because I could find no evidence that anyone else had had this specific problem. If there is another thread relating to this, please comment the link, I'd like to see it.
