### ISSUE TITLE
Wynncraft Map doesn't work

### ISSUE THREAD

**Issue by ToasterAmol** [Wynncraft/Issues#7569]
The Wynncraft Map says that it has an error. I thought this was just a problem for me, but when I went on a different computer, the error still showed. I couldn't find anyone else talking about a problem like this. My username is minecraftthe1st.

**Comment by Pyromanical** [comment]
Can you tell us what the error says?

**Comment by ToasterAmol** [comment]
"If you can see this message, there is likely a problem loading the Overviewer javascript components. Check the javascript console for error messages." I looked at the Javascript and the error it gives is: Failed to load resource: the server responded with a status of 429 ()

**Comment by Numbermaniac** [comment]
That's a "too many requests" error. The server throws this a bit more than it should; when it does, all you can do is wait a few minutes and reload the page.

**Comment by ToasterAmol** [comment]
Alright, thanks, I was just worried because it has been doing this for a
few days. It worked after I waited for 10 minutes :)
