### ISSUE TITLE
Grave mistake cutscene broken

### ISSUE THREAD

**Issue by gangmembertowelie** [Wynncraft/Issues#7570]
literally cant get out of this invisible box that it put me in. nothing happens when a cutscene is supposed to show (which doesn't) 

https://gyazo.com/2573512d5880224eb446fdc95efa9532
https://gyazo.com/2573512d5880224eb446fdc95efa9532
https://gyazo.com/2573512d5880224eb446fdc95efa9532

**Comment by gangmembertowelie** [comment]
how the fuck u add labels

**Comment by gangmembertowelie** [comment]
ok so i /kill'd (had to waste a shout because i didnt even know what to do) but yeah this is still a bug but im freeeeeeeeeeeeeeeee #gang #skrt #spellicup

**Comment by Moe-Ronickah** [comment]
Oh, man.  Well, at least you have a sense of humor about it.  Yes, that particular cut scene has had problems at times, off and on, and most people just /kill, however, there is another option that seems to work; just change classes, several times, if you have to.  Also, you can try changing severs.

But please, no more jokes about killing anyone - it's really not appropriate.
Thanks.

**Comment by Villageacules** [comment]
Please consider using formal language when making issues, thanks.

**Comment by Pyromanical** [comment]
Related to #6730, different part of the cut scene, same problem
