### ISSUE TITLE
dropped weapon in hopper

### ISSUE THREAD

**Issue by TheTwitchyBlaze** [Wynncraft/Issues#7573]
So I was in a dungeon (last sanctuary) and I accidentally dropped my weapon (I think it was something like aujims something) and I couldn't get it back 

Thanks for checking

-Blaze

**Comment by Pyromanical** [comment]
Sadly Wynncraft has a no refund policy, so you won't be getting your item back.  I'm guessing the item you lost was Almuj's Daggers, you can get another one by buying one on the trade market or finding a nice player to give you another pair.  Just some advise, you can go into your game controls and set your drop key to something like delete, so you won't hit it and accidentally drop something again.
