### ISSUE TITLE
Quest book not updating

### ISSUE THREAD

**Issue by Crazyisback** [Wynncraft/Issues#7574]
I was doing the "meaningful holiday' quest and i had to go talk to the Npc in Ternaves and his dialogue went through but my quest book wasn't updated so I tried to talk to him again but it is just a message that you get if you talk to him randomly. I relogged thinking it might help but the same dialogue showed up, my quest book never updated. Is there any way this quest could be reset or quest book be updated?

**Comment by thecoolkogut4** [comment]
what does your quest book say?
