### ISSUE TITLE
Stuck & No Way Out

### ISSUE THREAD

**Issue by Zoa28** [Wynncraft/Issues#7577]
Hi, I've been stuck in this area for quite awhile and I can't remember when or how I've been stuck, but I need a tp out.
https://cloud.githubusercontent.com/assets/26662198/24316051/5ebcd63a-10a8-11e7-85e7-ee3e8a535be0.png

My user is Zoa28

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by AscendedKitten** [comment]
As @thecoolkogut4 said, you can use /kill to respawn in the closest town. Make sure you have 5 or more soulpoints, as you might lose items otherwise.
