### ISSUE TITLE
2 Bugs in a dungeon and in V.S.S. Seaskipper

### ISSUE THREAD

**Issue by ShElias** [Wynncraft/Issues#7580]
Dear Wynncraft Team,

here are some bugs!Please fix them.Sorry for my bad english.(Im German)

1:If you take a ship from Llevigar to Selchar you wont be teleport.You stuck in the ship.Im sure there are other bugs too with the Seaskipper.

2:If you are in the dungeon(Galleon's Graveyard)you stuck in the dungeon.After you killed the first boss and go through the door theres a barrier and you wont teleport.

Elias Schröder

Minecraft:Its_Elias

**Comment by ColinRioux** [comment]
These both are duplicates and already have been reported, thank you though for your time.
