### ISSUE TITLE
NPC Name Issue

### ISSUE THREAD

**Issue by Zombie1Productions** [Wynncraft/Issues#7582]
So I was exploring Gavel, just filling out my map, when suddenly I came across this guy.
![2017-03-25_15 31 58](https://cloud.githubusercontent.com/assets/17608640/24326655/7a2e8a44-1170-11e7-800e-1d873e538c1f.png)
As you can see, there isn't an "NPC" tag under his name.

**Comment by thecoolkogut4** [comment]
what happens when you switch servers? is the tag still down?

**Comment by AscendedKitten** [comment]
That's a client-side bug that seems to happen occasionally; the "NPC" tag is still there, just far below where it should be. Relogging / switching server should fix the issue.
