### ISSUE TITLE
Wither Skeleton Carpet Doesn't Work

### ISSUE THREAD

**Issue by Karmdyde** [Wynncraft/Issues#7583]
The droppers in the Wither Skeleton carpet's right eye don't work in "The House of Twain" quest. The droppers are needed to open the secret door in the fireplace. And without it, I can't progress in the quest.
![screen shot 2017-03-25 at 7 17 21 pm](https://cloud.githubusercontent.com/assets/26680938/24327169/b649c0b0-118f-11e7-84a1-fc4250c4c9bd.png)

Those emeralds shouldn't be there...

**Comment by thecoolkogut4** [comment]
what happens when you switch servers?

**Comment by Karmdyde** [comment]
Switching servers worked, thanks!
