### ISSUE TITLE
No Permission

### ISSUE THREAD

**Issue by FofLof** [Wynncraft/Issues#7584]
My friend cannot press any buttons or open any loot chests in any area of wynn or gavel. His username is kix2330.

**Comment by thecoolkogut4** [comment]
tell him to use a soul point or a empty slot in his Inventory to open the chest/click the button. his weapon is most likely a retextured half slab and when he right clicks the game things he is trying to place the block.

**Comment by FofLof** [comment]
His weapon is the dern's desolation

**Comment by thecoolkogut4** [comment]
does it work when he trys to open it with his soul point or with his empty hand?

**Comment by FofLof** [comment]
Thank you very much, it worked!
