### ISSUE TITLE
Floating Chest

### ISSUE THREAD

**Issue by RikioPT** [Wynncraft/Issues#7586]
![2017-03-25_16 39 40](https://cloud.githubusercontent.com/assets/17153769/24327998/1462d97c-117a-11e7-962f-65cf0e10f8e3.png)
May have been left there from Wynnter Fair.

**Comment by LordHelmchen98** [comment]
I told someone about this. Should be fixed with the next map push.

**Comment by DebugMC** [comment]
Duplicate of #7154 #7441

**Comment by LordHelmchen98** [comment]
I'm pretty sure it should be fixed, because Corkus is released now and the map was updated.
