### ISSUE TITLE
Troubles with WynnExcavation A

### ISSUE THREAD

**Issue by Nin0s** [Wynncraft/Issues#7587]
Hello, a friend of mine(ign octoman102) is having a problem with completing the WynnExcavation A quest.
He lost the paper you need to translate from Tesha and /fixquests is not giving him it back.

**Comment by LordHelmchen98** [comment]
Did your friend check, if he has it on another class?

**Comment by Nin0s** [comment]
Yes he did, and yes he checked his enderchest too

**Comment by ColinRioux** [comment]
Unfortunately the only solution for your friend currently is to level up another class and transfer the item. The only negative to this solution is that the other class probably won't be able to complete the quest either.

This is also a current known issue, no status on when it'll be fixed. #4079

**Comment by Nin0s** [comment]
getting to level 38 again is quite a long and boring road.. is there no other way? like restart the quest? or give him a yellow crystal so we can do the other excavations atleast?

**Comment by ColinRioux** [comment]
We have no way to give you quest items at this time. You'll unfortunately
have to do so.
