### ISSUE TITLE
Enter the Dojo-Water pit

### ISSUE THREAD

**Issue by NcEternal** [Wynncraft/Issues#7588]
The teleporter in the water pit doesn't work
![2017-03-26_12 26 28](https://cloud.githubusercontent.com/assets/26687318/24330491/a2894290-121f-11e7-9b76-530bcd1bb3fb.png)

**Comment by thecoolkogut4** [comment]
What happens when you switch servers? try running around and jumping

**Comment by NcEternal** [comment]
I already tried switching server...It does not work. I also walked around the pit for a bit but it doesn't work either.

**Comment by ColinRioux** [comment]
If you are at the start of the quest, the water pit is at 451, 110, -5568. The coords you are at is not the water pit, and isn't related to the quest.
