### ISSUE TITLE
Olux's Prized Spear replaced with Untradable Oak Wood Spear

### ISSUE THREAD

**Issue by CrazyBeanz** [Wynncraft/Issues#7589]
![2017-03-26_17 43 12](https://cloud.githubusercontent.com/assets/26692597/24333226/ed4581fa-124b-11e7-8171-ef501280f003.png)
My Olux's Prized Spear was replaced with an **Untradable** Oak Wood Spear, I don't know how this happened and was hoping I could get it back somehow.

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by ColinRioux** [comment]
What @thecoolkogut4 said still applies, no refunds unfortunately. However, the weapon you are holding the the spear you get when you first start out, is it possible you tried to drop that one but dropped your prize spear instead? (Not saying that's what you did, but it's in fact possible).
