### ISSUE TITLE
Hunger of the Gerts Part 1 Text Issue

### ISSUE THREAD

**Issue by Zombie1Productions** [Wynncraft/Issues#7590]
After you complete the quest "The Hunger of the Gerts Part 1", when you talk to Cikal, there is a typo in his dialogue.
![](https://i.gyazo.com/c4cb31012e08726013b13348b7da7bd9.png)
Instead of Gylia Watch, he says Gyila Watch.

**Comment by ColinRioux** [comment]
This has already been fixed and will be live in the next update: Corkus.
