### ISSUE TITLE
A problem with WynnExcavation site B

### ISSUE THREAD

**Issue by HiddenKuni** [Wynncraft/Issues#7594]
I'm currently doing the Wynn excavation site B quest with my warrior and I can't seem to go into the water pit, all it does is it gives me a blank msg and teleports me back up a block or two, and keeps repeating, I tried other servers but got the same result. If anyone can help, it would be greatly appreciated.

**Comment by ColinRioux** [comment]
What does your quest book say?

**Comment by HiddenKuni** [comment]
It currently says Bring the Yellow Crystal shard to Excavator Lykron at 39,63,-526

**Comment by AscendedKitten** [comment]
Being teleport back is probably a result of accidently skipping a stage; try using the quest's wikipage and re-do the steps prior to entering, it might be that you missed a region.

**Comment by HiddenKuni** [comment]
I belive I have figured out the problem

**Comment by joshuaxlino** [comment]
what was the problem? i am too experiencing this
