### ISSUE TITLE
Green Gloop

### ISSUE THREAD

**Issue by Nitsua234** [Wynncraft/Issues#7595]
I've got a problem with the Green Gloop quest behind Almuj. See, I haven't played in a while. Like a long while. In fact, my book still says that I had to give 5 bottles to Yodbon, who must've been the NPC for the previous quest. Whenever I talk directly to the new NPC (Eluzterp), an empty line is entered in the chat. Whenever I attempt to go in the dungeon, he tells me I can't go in there yet. Thank you for responses

**Comment by Pyromanical** [comment]
Have you tried talking to Yodbon with 5 bottles?  If you tried that, are you sure you are using the right bottles?

**Comment by Nitsua234** [comment]
like I said, yodbon isn't there anymore, i think Eluzterp owns the quest now. Also I had 16 bottle in my inventory.

**Comment by LordHelmchen98** [comment]
Yodbon is still there and you hvae to give him the 5 glass bottles.

**Comment by Nitsua234** [comment]
Oh, thank you. I didn't realize that! sorry for the stupidity, I couldn't see where to find yodbod though.
