### ISSUE TITLE
Meaningful Holdiay

### ISSUE THREAD

**Issue by BlueSkull10** [Wynncraft/Issues#7596]
During the quest Meaningful Holiday i have come across a bug with reshad. It wont let me click on him or talk to him. I asked someone else that was on the same quest as me and asked them if they can click reshad and they said they cant either. Please fix this bug so people like me can finish the quests.

**Comment by LordHelmchen98** [comment]
Sometimes it takes a while until it the game recognizes that you clicked Reshad. The only thing I can tell you is that it might be possible to finish the quest if you try to click him from every direction and if it doesnt work repeat it on a different server.

**Comment by AscendedKitten** [comment]
As @LordHelmchen98 said, that's caused by script and might be server-related. Try switching server or clicking him from different angles, that should fix it.
