### ISSUE TITLE
Cannot login to the lobby: Flying is not enabled on this server

### ISSUE THREAD

**Issue by Ms-Dragon** [Wynncraft/Issues#7599]
### **Before someone marks this as a duplicate and closes it, please actually read what I'm saying and help me along with the others find an actual answer. I've made these because all the closed threads have yet to help me on this case. A working answer would be very nice. Thank you.**

Hello, recently after a server restart, I've been getting a weird bug. After logging onto play.wynncraft.com (and play.wynncraft.net because apparently that works too), I keep getting kicked after getting the message, "Flying is not enabled on this server." I get kicked, reconnected, and then it just keeps looping.

![image](https://cloud.githubusercontent.com/assets/22614194/24380496/40bf30b8-1311-11e7-9204-c9db283a2d7a.png)
_Here you see the string of repetitive messages I received along with my task manager on the top._

Unlike most other players, who seem to successfully log in after the cycle goes on for a bit, my Minecraft will just completely end itself. This led me to believe that it was possibly a client error. The previous night I completely uninstalled and reinstalled both my Minecraft and Optifine. That didn't seem to work at all, as the problem still pops up. Currently I am using the Optifine 1.11.2 HD U B7 from [here](https://optifine.net/downloads), which has never had a problem before. On that topic, this glitch is _only_ happening on Wynncraft, as all my other servers run fine.

I went back to the Optifine website and downloaded the Optifine 1.11.2 HD U B6 in order to test the possibility of the problem being on my side. Unfortunately, I still keep getting kicked for flying.

![image](https://cloud.githubusercontent.com/assets/22614194/24381175/8209ee3e-1314-11e7-8631-8cc8cff24595.png)
_Here you can still see a repetitive loop of "Flying is not enabled on this server," messages. I'm also getting alerted of the B7 Optifine being out, proving that I am in fact on 1.11.2 B6._

I decided to test this glitch one more time, this time with the Optifine 1.11 HD U B7, which is a big downgrade from the 1.11.2 B7 Optifine.

![image](https://cloud.githubusercontent.com/assets/22614194/24381337/76da8dce-1315-11e7-92fd-024db27dfaee.png)
_Here's a picture of me logging into the 1.11 B7 account._

![image](https://cloud.githubusercontent.com/assets/22614194/24381348/8d941580-1315-11e7-9803-e2faf079da6b.png)
_As you can see here, I still got the error._

From all the different clients I used, none seemed to work, which made me believe that it wasn't my client. Half a second doesn't allow me to actually join a WC, as you can see my hotbar shows the compass and clock that you get in the hub (so please don't be ignorant and say, do /autojoin).

Also, before ya'll say anything, Optifine's only purpose is to increase FPS. It won't make you fly at all and the only real difference it has from Minecraft is extra options in the Video Settings.

I was wondering if either A) Any of ya'll got any ideas about what's going on and 2) if a staff can teleport me out of the location I am in when I log on. Thanks again!

**Comment by Ms-Dragon** [comment]
Apparently I accidentally posted it too soon. Anyways... 

![image](https://cloud.githubusercontent.com/assets/22614194/24381337/76da8dce-1315-11e7-92fd-024db27dfaee.png)
_Here's a picture of me logging into the 1.11 B7 account._

![image](https://cloud.githubusercontent.com/assets/22614194/24381348/8d941580-1315-11e7-9803-e2faf079da6b.png)
_As you can see here, I still got the error._

From all the different clients I used, none seemed to work, which made me believe that it wasn't my client. Half a second doesn't allow me to actually join a WC, as you can see my hotbar shows the compass and clock that you get in the hub (so please don't be ignorant and say, do /autojoin).

I was wondering if either A) Any of ya'll got any ideas about what's going on and 2) if a staff can teleport me out of the location I am in when I log on. Thanks again!

**Comment by LordHelmchen98** [comment]
From what I saw, I assume you only tried to use different clients on 1.11. Can you please try to use 1.9 (Im using 1.9.4) and tell what happens if you do?

**Comment by ColinRioux** [comment]
First off, this is the most well thought out, most descriptive issue which I have ever read. I would never dare to close something like this. 

Secondly, as you've read, others have been receiving this issue. So we are aware of it. Of course, we have no working solution yet, and until Corkus is released I won't be exploring these issues. But after, I plan to. Like @LordHelmchen98, I do suggest you try a different version. Wynncraft is hardcoded to 1.8.9, and uses a version proxy to allow other versions to connect. It's worth a shot since there are distinctive differences between 1.8.9, 1.9, and 1.10/1.11. 

Thirdly, I would like your crash report, if you get one, when your minecraft crashes. Even though you have deduced that this isn't client related, it'd still be helpful information. 

Fourthly, I can explain more in depth why this occurs. Essentially, the spawn point is actually floating above where you spawn. So if you are logging in, still loading, for x amount of time, the no-cheat goes berserk and kicks you to another lobby. Or at least I'm pretty confident it does if you get it over again. Then it kicks you to another lobby, and you're in the same exact position as before, only to get kicked again. I suggest trying to log in at a different location, i.e, a public library, a hotel, a friend's house, or really anywhere with free public wifi (if that's easily accessible). If you have no problems there, then we can deduce that it's your connection. If you still have the issue, then we can explore other options.

**Comment by Ms-Dragon** [comment]
> From what I saw, I assume you only tried to use different clients on 1.11. Can you please try to use 1.9 (Im using 1.9.4) and tell what happens if you do?

I have switched to 1.9.4 without Optifine and I was able to get on. Adding on to that, I was also able to connect on 1.10.2 and Optifine B7 1.11.2, which was the version I was originally using when I got kicked. Putting these two pieces together, I still do not believe that it was a client issue.

![image](https://cloud.githubusercontent.com/assets/22614194/24431144/dee59894-13df-11e7-8a9a-8742c305b5a5.png)
_As you can see here, I am logged into Wynncraft on Optifine 1.11.2._

> First off, this is the most well thought out, most descriptive issue which I have ever read. I would never dare to close something like this.
>
>Secondly, as you've read, others have been receiving this issue. So we are aware of it. Of course, we have no working solution yet, and until Corkus is released I won't be exploring these issues. But after, I plan to. Like @LordHelmchen98, I do suggest you try a different version. Wynncraft is hardcoded to 1.8.9, and uses a version proxy to allow other versions to connect. It's worth a shot since there are distinctive differences between 1.8.9, 1.9, and 1.10/1.11.
>
>Thirdly, I would like your crash report, if you get one, when your minecraft crashes. Even though you have deduced that this isn't client related, it'd still be helpful information.
>
>Fourthly, I can explain more in depth why this occurs. Essentially, the spawn point is actually floating above where you spawn. So if you are logging in, still loading, for x amount of time, the no-cheat goes berserk and kicks you to another lobby. Or at least I'm pretty confident it does if you get it over again. Then it kicks you to another lobby, and you're in the same exact position as before, only to get kicked again. I suggest trying to log in at a different location, i.e, a public library, a hotel, a friend's house, or really anywhere with free public wifi (if that's easily accessible). If you have no problems there, then we can deduce that it's your connection. If you still have the issue, then we can explore other options.

As I mentioned earlier, the problem magically seemed to fix itself so I really can't say anything. Unfortunately, when I went into the "crash_reports" folder, the only report in there was one from December. As for your other suggestion, I did not log in from a different location any time from when the problem appeared to when it solved itself.

I guess as of right now, the only real fix to the problem is just to give it time, as no other factors changed. Thanks for all your guys help and I hope ya'll manage to find a way to get rid of this glitch. :D

**Comment by ColinRioux** [comment]
Well a version change did resolve the issue, and allowed you to log in correctly. Sometimes you need to log into using a lower version, then re-log using the higher one in order for things to repair itself. This has been my solution for a number of connection related issues.

**Comment by theonlygusti** [comment]
@ColinRioux that didn't fix it for me. This problem persists using any version of MC: 1.11.2 (vanilla, 5zig mod, optifine), 1.9 (5zig), 1.8.9 (vanilla), 1.8 (vanilla, optifine)

Get this problem with them all.
