### ISSUE TITLE
Quest item is gone(TheAngryVillage)Corrupted Potato

### ISSUE THREAD

**Issue by ShElias** [Wynncraft/Issues#7602]
Daer Wynncraft team,

today i wanted to make the Temple of legends quest,but the corrupted potato is gone.I know why.In wynncraft(before Gavel)i dropped the item and take another item and then the quest item cant be moved in my inventory.Now the quest item is gone.I cant do the quest.Please Help!

Minecraft:Its_Elias

Skype:Elias Schröder_2002
(with car image)

**Comment by LordHelmchen98** [comment]
You should get it back if you do /fixquests.

**Comment by ShElias** [comment]
Before you close it let me check it pls.

Thx :D

**Comment by LordHelmchen98** [comment]
I cant close it anyway because I dont have the permissions. If it works out, thats something you have to do.

**Comment by ShElias** [comment]
oh xD but i tried you are an angel!thx a lot man
