### ISSUE TITLE
Animal dungeon coords

### ISSUE THREAD

**Issue by LOLCRAFT56** [Wynncraft/Issues#7605]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

Hi server, is that I think I got a issue or a problem with the dungeons, I  got 5 animal keys and it 

> says: grants access to the **animal dungeon** once
          coords: -271,80,-1049

> 

and the problem is that when I go to the coords there is the **Lost Sanctuary dungeon**.
images:  http://imgur.com/a/JFEtz
Thx if u can fix this
my nick is LOLCRAFT56

**Comment by ColinRioux** [comment]
Animal dungeon no longer exists. It's now called the lost sanctuary dungeon. If the key doesn't work, there is a converter merchant in detlas.
