### ISSUE TITLE
From the Bottom Nakoba

### ISSUE THREAD

**Issue by isax3** [Wynncraft/Issues#7606]
I am unable to interact with Nakoba in the Thanos Bazaar, which prohibits progression of the From the Bottom quest.

**Comment by numbermaniac** [comment]
What does Nakoba say? If he's looking for Troll Hair, you'll notice your quest book says "Find someone who wants to buy 10 Troll Hair."

You need to go outside Thanos and kill the Troll Hunters or Troll Savages until you get 10 of them. Nakoba won't start the quest until you have them.

If you're saying that he won't say anything when you talk to him, try switching servers; it might just be an issue on one server.

**Comment by isax3** [comment]
Nakoba is the one that takes the unusual egg, but when I right click on him nothing appears in chat and the quest book doesn't change. I'll try on another server. I've tried logging off and on again, so if it is only on one server, it's on world 8

**Comment by isax3** [comment]
I tried on other worlds, and none of them worked

**Comment by motoki317** [comment]
Nakoba is not the one who takes the Unusual Egg. You need to find a different NPC for that. Look into wiki again, and if you really couldn't hand your item to the right NPC, it could be a problem.
https://wiki.wynncraft.com/index.php?title=From_the_Bottom
