### ISSUE TITLE
I Haven't Logged On In Many Months And Archer Spell Levels Are Messed Up

### ISSUE THREAD

**Issue by rasyt123** [Wynncraft/Issues#7609]
I haven't logged on in quite a while and for some reason all of my spell levels do not match up with my current level of 67 on my archer.  It may be a bug from the past when I transitioned to the big update, but I was never able to figure it out. I last logged on before the Gavel update, so I was stuck inside the big update box. 

![2017-03-29_07 53 37](https://cloud.githubusercontent.com/assets/26770454/24461307/85fe1316-1455-11e7-8de8-dc4802572a71.png)

**Comment by LordHelmchen98** [comment]
Those levels shown next to the spells are the levels required to unlock them, so I dont see a problem here.

**Comment by rasyt123** [comment]
At Level 67, shouldn't I have higher level spells?

**Comment by LordHelmchen98** [comment]
No those numbers dont change.
It looks the same for my 101 mage.
![](http://puu.sh/v2pOq/dd336f51ec.png)

**Comment by rasyt123** [comment]
I get it now. Thanks!
