### ISSUE TITLE
horse glitch

### ISSUE THREAD

**Issue by bakuscout** [Wynncraft/Issues#7610]
when i dismount my horse he can move thru wall blocks and now im stuck outside of a boss fight cause i glitched thru the wall

**Comment by bakuscout** [comment]
found the glitch when the boss of the "house of twain" quest glitched thru a wall

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by ColinRioux** [comment]
We are aware of this glitch, thank you for being courteous and reporting it though, however.
