### ISSUE TITLE
I cant start find the light quest even know im holding the taproot

### ISSUE THREAD

**Issue by ZefengPlayz** [Wynncraft/Issues#7611]
i tried reloging and it still didnt work
![image](https://cloud.githubusercontent.com/assets/13813974/24478512/f053a854-148f-11e7-9a63-c2d81f0fbf14.png)

**Comment by thecoolkogut4** [comment]
you also need a volt goat horn to start the quest. to get the horn you kill the volt goat (yellow sheep in the light forest)
