### ISSUE TITLE
Seasail ship glitched

### ISSUE THREAD

**Issue by Traphex** [Wynncraft/Issues#7612]
So I was at Nemract and decided to go to LLegivar to get some quests done, I put in a Seasail for LLegivar and I get teleported to it but instead of me going to LLegivar I got stuck and it hasn't teleported me anywhere for 10 minutes now. Please teleport me out or help me my username is Traphex

**Comment by Traphex** [comment]
Alright Someone gave me a teleport scroll so I got out

**Comment by numbermaniac** [comment]
@Traphex in the future you can switch to a different server and it should start working.
