### ISSUE TITLE
Bobs Mythic Bow is GONE :( Idk why?!?!?

### ISSUE THREAD

**Issue by ShElias** [Wynncraft/Issues#7614]
Dear Wynncraft team,

Yesterday i did the quest with killing bob and bought  bobs mythic bow.

Today i reached lvl 75 by doing a quest (murder mystery)and the bow was not in my inventory!!Not in my bank!!not in my other classes!!Its gone!!Now i have no bow only a bad one.Please help!I dont dropped the bow.Im not crazy.Maybe some mod can give the bow back.However please help!I worked for this bow yesterday from lvl68-74.

Minecraft:Its_Elias

E-mail:elias.schroeder

Im very grateful if a mod or other player or admin can bring me back the bow.

**Comment by LordHelmchen98** [comment]
Unfortunately Wynncraft enforces a strict norefund policy. Therefore you wont get the weapon back, but you can buy another one from another player.
