### ISSUE TITLE
Gallons Graveyard has bugged out 3 times for me. (in a row, tried different servers)

### ISSUE THREAD

**Issue by Wiihacker0** [Wynncraft/Issues#7616]
So the other day I was tryin to get through Gallons graveyard since i'm lvl 66 and there's no quests for me.
but everytime I get past the armored pirate I get stuck in the barrier box.
![2017-03-30_11 53 24](https://cloud.githubusercontent.com/assets/26554073/24513936/96a38cf0-1540-11e7-8c23-2fe73a34f8e0.png)

**Comment by LordHelmchen98** [comment]
Galleons Graveyard has some known glitches, but they are fixed on the build server and the fixes will be public with the next map push (That will be Corkus which is announced for early april).
