### ISSUE TITLE
Problem at Twain Mansion

### ISSUE THREAD

**Issue by monkey4ggh** [Wynncraft/Issues#7619]
At Twain Mansion while you walk over the trip hook in the garden you can't get the ghost to spawn. Thus you can't finish the quest House of Twain.

**Comment by Trixter313** [comment]
Just checking, did you solve your issue and mean to close it? Thanks!

**Comment by monkey4ggh** [comment]
Yes I did. I was in the wrong area XD. I heard a trip wire hook in a place in the garden so I thought it was that one but it wasn't.

**Comment by Trixter313** [comment]
Okay, glad to hear you figured it out. =)
