### ISSUE TITLE
3 holes in the Ancient City (Wynnexcavation Site D)

### ISSUE THREAD

**Issue by LordHelmchen98** [Wynncraft/Issues#7620]
After someone messaged me about being stuck in a hole I found these three holes in the Ancient City.
![](https://puu.sh/v4U0l/38fd2e0036.png)
![](https://puu.sh/v4TZF/91cdca919f.png)
![](https://puu.sh/v4TXx/15a69b7a02.png)
It would be nice if someone could fill them up.
(@AscendedKitten these are the holes I told you about)

**Comment by ColinRioux** [comment]
Fixed!
