### ISSUE TITLE
Server Crashing during a quest

### ISSUE THREAD

**Issue by Scorpioxzz** [Wynncraft/Issues#7622]
I was doing the quest Cowfusion and I just finished talking to Drale after getting "milked" when the server crashed. When I logged back onto a server, it spawned me in the milking chamber with the quest book saying "Wait to be milked." But since I spawned in the chamber the milking process didn't initiate so I had to do /kill. When I went back to the barn to get back into the cow hideout the button wouldn't work to let me in. Anyone else had this issue with server crashes?

**Comment by thecoolkogut4** [comment]
go into the first cave(i think its the second step in the quest), i believe you get tped to a new location then try to go and push the button to get into the hideout

**Comment by Scorpioxzz** [comment]
Hmmm. Ok I'll try that.

**Comment by Scorpioxzz** [comment]
It worked :D. Thanks
