### ISSUE TITLE
Can't press buttons

### ISSUE THREAD

**Issue by DarkMaster98** [Wynncraft/Issues#7624]
If this is an April Fools prank, I'm not amused. Every time I press a button, I get the message 'you don't have permission to do that in this area.' I can't progress in quests or do dungeons if I can't press buttons.

**Comment by thecoolkogut4** [comment]
It is because the item you were using is a retextured half-slab, and the game thinks you were trying to place it, so it says you don't have permission to. To fix this right click with a empty hand or your soul point.

**Comment by DarkMaster98** [comment]
Yep, that worked. Thank you!
