### ISSUE TITLE
cant hit anything

### ISSUE THREAD

**Issue by justamanthatwantstoplay** [Wynncraft/Issues#7625]
i can hit anything and the npcs cant attack mobs either

**Comment by thecoolkogut4** [comment]
what server are you on?

**Comment by justamanthatwantstoplay** [comment]
13

**Comment by justamanthatwantstoplay** [comment]
and im on a pole surrounded by a bunch of weak zombies

**Comment by thecoolkogut4** [comment]
sorry, I didn't see the email notification. 13 seems to be fine on my end, and it has been 3 hours since you posted the issue (and the worlds restart every 3 hours) is this still going on for you?

**Comment by justamanthatwantstoplay** [comment]
thanks for the help man

**Comment by justamanthatwantstoplay** [comment]
its not
