### ISSUE TITLE
Enter the Dojo: Typo in Challenger Apprentice's after-quest dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7627]
"upmost" should be **"utmost"**: 
![2017-03-04_22 06 47](https://cloud.githubusercontent.com/assets/5206120/24585279/37183fec-17ca-11e7-8a13-e7dfce5ad60a.png)

**Comment by Trixter313** [comment]
After Googling, upmost apparently is a word that could go there but I agree that utmost could sound a bit more natural.

**Comment by ColinRioux** [comment]
Fixed!
