### ISSUE TITLE
Fantastic Voyage: Typo in Relend's dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7629]
Message 3/3: "get **of** this place"; "of" should be "off".
![2017-03-10_13 51 23](https://cloud.githubusercontent.com/assets/5206120/24585320/c8bbab96-17ca-11e7-9cf0-a0a868c5c1a1.png)

**Comment by ColinRioux** [comment]
Actually added the word out. Off seems weird. But fixed!
