### ISSUE TITLE
Fantastic Voyage: Two typos in Relend's Gateway Island dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7630]
2/7: "we can come up with **a** solution"; "a" is missing.
7/7: "You'll need those items **you** craft the bomb"; "you" should be "to".
![2017-03-10_14 11 36](https://cloud.githubusercontent.com/assets/5206120/24585336/30c43e38-17cb-11e7-83de-8aaef22785f3.png)

**Comment by ColinRioux** [comment]
Fixed!
