### ISSUE TITLE
Troubled Tribesmen: Typo in Krattson's dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7634]
4/6: "must of" should be "must have":
![2017-02-25_21 01 55](https://cloud.githubusercontent.com/assets/5206120/24585400/bc97a3e0-17cc-11e7-8b0f-4a9e44e7ec77.png)

**Comment by Trixter313** [comment]
Or you could use must've, which might be the effect the writer was going for.

**Comment by ColinRioux** [comment]
Fixed!
