### ISSUE TITLE
Guild bug, can't leave the guild

### ISSUE THREAD

**Issue by MythicalSora** [Wynncraft/Issues#7637]
Hi, I created a guild under my MC account MythicalSora (now KamuiKakashi) but now there is a bit of a problem. I got my brothers old MC account (Now MythicalSora) and me and TheBanditYT (Now SchoonMaakTeam) can't leave our guildto start a new one (Brotherion guild).

**Comment by LordHelmchen98** [comment]
Duplicate of #3665 
Unfortunately players get stuck in guilds after changing their names and there is no know fix for that. You will have to be patient until guilds get fixed.
