### ISSUE TITLE
Store Price Bug

### ISSUE THREAD

**Issue by globemaster123** [Wynncraft/Issues#7638]
So I bought VIP quite a time ago & wanted to buy VIP+ now, but it keeps saying that it costs 40$ instead of 20$, cause i allready got VIP.
IGN globemaster123

**Comment by DebugMC** [comment]
It says 40$, but it is 20$ dont worry. (It just says that to show the normal price)

**Comment by Trixter313** [comment]
Yeah, make sure you type your username in exactly as it is, any capitals included, and the price should be correctly reduced when it is in the cart.

Let us know if it does or doesn't work out, thanks!

**Comment by Pyromanical** [comment]
I'm assuming when you say "quite a time ago" you mean a really long time ago.  People who bought a rank before a store update (I think it was a store update), which happened a long time ago, didn't get their rank updated in the new store system.  You will need to email support@wynncraft.com, then they can manually add you to the system.  The price should be correct after that.

**Comment by globemaster123** [comment]
Yea, i'm already vip veteran, so i bought it like 2013 or something, but thanks guys ! :)

**Comment by LordHelmchen98** [comment]
As @Pyromanical said, in order to get the discount you have to contact the support because they are able to help you.
