### ISSUE TITLE
Wynnexcavation Site D

### ISSUE THREAD

**Issue by Camel1996** [Wynncraft/Issues#7639]
The first puzzle in the quest, in Trom`s Castle is broken. The 3 coloured blocks dont switch their colours anymore upon pressing the buttons. So you can't even "begin" the quest right now, hope this gets fixed soon :)

**Comment by ColinRioux** [comment]
Have you attempted to switch servers?

**Comment by Camel1996** [comment]
yep, tried on 10 different ones

**Comment by LordHelmchen98** [comment]
They are not supposed to switch their colors. You have to click them in the order of the previous quests and their related crystals.
