### ISSUE TITLE
I AM STUcK IN A BLOCK PLEASE TP ME OUT PLEASE AM LEVEL 42 USER TheKillersAce PLEASE HELP ME I CANT USE SCROLLS OR ANYTHING HELP ME!!!!!!!!!!!

### ISSUE THREAD

**Issue by TheKillersAce** [Wynncraft/Issues#7640]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

**Comment by Trixter313** [comment]
Whenever you are stuck you can use the command /kill to be teleported to the nearest respawn point. =)
