### ISSUE TITLE
Flight in Distress Quest Glitch

### ISSUE THREAD

**Issue by JoshuaPR999** [Wynncraft/Issues#7642]
So I'm doing the flight in distress quest, and on stage 16 (according to wiki) out of 17, the tripwire in the tp box doesn't work, and when i switch servers it teleports me out of the box that it teleports me in and I have to /kill and start the whole quest all over, just for it to do it again. This may just be a me problem but all the times I've done the quest it's screwed me over every time. 
![2017-04-02_17 43 58](https://cloud.githubusercontent.com/assets/26859350/24591291/2bf219ec-17cc-11e7-92c8-d217aa0003cd.png)

**Comment by AckroWynn** [comment]
It seems to work like it should on our build server. The only thing I added was a teleport commandblock that you can press to get back inside.

Try it on a different server!

**Comment by Player52** [comment]
Me too, i did the quest normally, but after killing the pirate queen i was stuck in the teleport room, i did /kill then started the quest again and the same thing happened. I can't complete the quest, please fix it!
