### ISSUE TITLE
Lost 3 items in Temple of Legends ;-;

### ISSUE THREAD

**Issue by Stirfink** [Wynncraft/Issues#7644]
So, i'm a lvl 68 mage (Currently) so i was doing Temple of Legends and i was on the second step where i give him Bobs lost soul mummy's bandage and sayleros's brother's ashes when my server was about to restart, i accidentally clicked the dude and gave him my items it took my items but it did not progress me in the quest so now i am stuck on the second step in that quest and i cant progress with out the items so i cant do ANYTHING. Please help.

**Comment by Trixter313** [comment]
You can try the command /fixquests to see if it returns the items to you. Let us know the outcome.

**Comment by Stirfink** [comment]
Mk

**Comment by Stirfink** [comment]
OMG THANKS

**Comment by Stirfink** [comment]
it only gave me the bandage and bobs soul
but i have an extra ashes

**Comment by Trixter313** [comment]
Glad to hear! Enjoy your time playing Wynncraft =)

**Comment by Stirfink** [comment]
Thanks!
