### ISSUE TITLE
Stuck Inside Blocks Somwhere, Can't Escaspe

### ISSUE THREAD

**Issue by CocoWuffle** [Wynncraft/Issues#7645]
My friend and I were riding in boats on the way to the ice islands when my friend needed to go afk, but when she did, her boat started sinking and she suffocated to death. At least that's what we thought, but when she came back to her screen, she was stuck in some dirt blocks and is completely immobile. We tried teleport scrolls, disconnecting, trying different worlds, me trying to find her, and nothing worked. We have no idea if she is still in Nemrack or if she's somewhere else and we have no idea how to get her out. She really doesn't want to have to restart since she has good gear and is a level 40, so if you could please help us out it'd be greatly appreciated <3

**Comment by Trixter313** [comment]
Whenever you get stuck you can use the command /kill to be teleported to the nearest respawn point. =)

**Comment by CocoWuffle** [comment]
Thank you so much!
