### ISSUE TITLE
Kicking me and rejoining me constantly.

### ISSUE THREAD

**Issue by CocoWuffle** [Wynncraft/Issues#7647]
Every once in awhile when I try to join wynncraft, it'll kick me automatically saying that "Flying isnt inabled" and then automatically trys to put me in a different hub, so constantly im being kicked, then added, kicked, then added, kicked, added, and so on until I crash, manage to exit off, or the server times out. I literally can't play, please, what do I do?

**Comment by Pyromanical** [comment]
Is the kicking happening in the world or in the lobby or both?  If it happens in the world, you probably have autojoin on.  To fix this, try and join a world with very few people in it, and the second you are able to type commands, do `/toggle autojoin`.  You will now log into the class screen, not your character.  If it happens in the lobby, relogging usually fixes it.
