### ISSUE TITLE
I don't earn any EXP points.

### ISSUE THREAD

**Issue by PopKoren** [Wynncraft/Issues#7648]
Hello,
Today I finished alot of quests, killed alot of monsters and still I didn't get even 1 exp bar, I guess my account is bugged? because I finished atleast 10 quests, for each I got 20k-30k EXP and my EXP bar is still empty.. help me please.

**Comment by thecoolkogut4** [comment]
are you in a guild? if you are your guild xp may be set to 100 (so all the xp you get goes to your guild). of your in a guild type /guild xp 0 (this way all the xp you get will go to you and none will go to the guild)

**Comment by PopKoren** [comment]
@thecoolkogut4 thank you so much, it was the problem, rip like 150k xp that went to my abandoned guild xD
