### ISSUE TITLE
Flying Blocks!

### ISSUE THREAD

**Issue by PinkGangsterGoat** [Wynncraft/Issues#7649]
I just did the quest Taproot for the 4th time, with my assassin. When I was walking around in the Dark Forest (the non-decayed one, specially made for Taproot), I saw two random blocks floating in the air, (I assume they were used for worldedit,) so I thought, why not report it on the bug report section before the map update (Corkus) comes out.
![2017-04-03_15 36 41](https://cloud.githubusercontent.com/assets/26873878/24611958/1e24397c-1884-11e7-811b-65a54b4ebb6e.png)
The coords of the floating blocks are: X:-1800, Z:-6680
Thanks!
~PinkGangsterGoat

**Comment by Pyromanical** [comment]
@ColinRioux

**Comment by ColinRioux** [comment]
Fixed!
