### ISSUE TITLE
Quest Cowfusion: Stuck in wall

### ISSUE THREAD

**Issue by SmirrenIsMyName** [Wynncraft/Issues#7650]
After I've exploded the boulder in the way I found a passage I could walk through. When I enterd the passage I got teleported into the wall and thats it. Server 3. And if you find me please teleport me back into this cave. Dont teleport me to the starting area again please :)
![2017-04-03_19 47 52](https://cloud.githubusercontent.com/assets/26552191/24622846/c10d1420-18a6-11e7-9944-82976abd7304.png)
![2017-04-03_19 47 43](https://cloud.githubusercontent.com/assets/26552191/24622852/c3e8ef20-18a6-11e7-9981-6629284b4f55.png)

**Comment by SmirrenIsMyName** [comment]
So I decided to do /kill. Now I cant get back into the place. The place where you get milked. the button does nothing

**Comment by SmirrenIsMyName** [comment]
My god. This is all a mess. I redid the quest on server 5 and it worked this time. Sorry for wasting your time. *Sigh*

**Comment by Trixter313** [comment]
I'm sorry to hear you had issues with the quest but glad to hear it ended
up working out!
