### ISSUE TITLE
weapons lost

### ISSUE THREAD

**Issue by TragicMagic1** [Wynncraft/Issues#7651]
i had a legendary weapon in my hotbar hit an ocelot then it disappeared and people were helping me look and since i didnt have a weapon i went back to my bank got my other legendary weapon hit an ocelot and it disappeared right from my hand and i cannot find them in my bank or inventory i tried relogging and restarting mc and it did not work in the slightest my stuff is still gone and that was my best weapons

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.
