### ISSUE TITLE
I'm blocked in a invisible block

### ISSUE THREAD

**Issue by Pontiyeur** [Wynncraft/Issues#7652]
Please help !
i'm blocked in the dungeon :-:
i d'ont have scroll
HELP
[]https://youtu.be/NWSyeggSbLg

**Comment by Pontiyeur** [comment]
I did /kill it's ok

**Comment by LordHelmchen98** [comment]
The Galleons Graveyard dungeon is known for several bugs so you should avoid it for now. When Corkus comes out those bugs should be fixed. Then you can try it again.
