### ISSUE TITLE
Need Admin To Help With Guild Glitch

### ISSUE THREAD

**Issue by KnixFice** [Wynncraft/Issues#7654]
I had made a guild last year in July, and a couple of people that had changed their name, and quit Wynncraft can't leave my guild and I would like to get rid of them. The guild name is Knix Clan (Knx) and I would also like to gain Ownership back. I had a couple of accounts that I had gotten rid of, FiceNRice was the leader of Knix Clan but I gave the account away after I had left the guild, and it had promoted my good friend Joey, MisterMario19 to owner. I would just appreciate it, if we had people that were able to contribute to the guild, instead of wasting guild space. The usernames are, WynnBeenix, AhM1ng, and CleansingFlames. Please remove them ASAP, if not too much to ask for.

**Comment by Moderocky** [comment]
My guild (very similar tag actually!) called Cartel / KIx, I can't kick member from for the same reason almost. :)

User: EntirelyBonkers - is in it twice and cannot leave or be kicked but she'd really like to join her friend's guild.

We would appreciate it if somebody could fix this as well :(

**Comment by LordHelmchen98** [comment]
Duplicates of #3665
Unfortunately there is no fix known for that so far. As there are countless people glitched in guilds it would take too much effort to remove all of them, which means you will have to be patient until guilds get fixed.
