### ISSUE TITLE
im stuck in a tree

### ISSUE THREAD

**Issue by ethan061903** [Wynncraft/Issues#7655]
So i kinda used the teleport spell and i got myself stuck in a tree if any mod can help tp me out that would be great! Please give me some live contact info such as a hangouts number or skype name because i will be sleeping because its 11:57pm right now so if anybody can help please do

**Comment by ethan061903** [comment]
Ive been looking through this i found that there is a /kill command imma try that




WISH ME LUCK

**Comment by LordHelmchen98** [comment]
Yeah /kill is the command you need. But be careful, if you have too less soul points you may loose stuff you wanted to keep, but if you have more than 5 everything should be fine.
