### ISSUE TITLE
My weapon is broken

### ISSUE THREAD

**Issue by Downroeschen** [Wynncraft/Issues#7657]
I'm Level 61 and had a Fierté when i stopped playing for a time. But now my Fierté is broken,
![jgdhjfgkjhhjj](https://cloud.githubusercontent.com/assets/18379967/24704547/6e83a27e-1a08-11e7-9656-a31eb296191b.PNG)
and my next best weapon is for level 48. So it isn't that useful on my level, I don't know what to do because i dont want to take ages to get a good weapon again, or spend my emeralds.

Is there any way to get it back? I was told that it's just a bug and will be fixed, but nothing happened.

**Comment by LordHelmchen98** [comment]
Unfortunately this weapon is broken and will stay broken. Before the Gavel update there was a weapon like the one you have called Fierté. But when the update was released the 'é' was changed to a normal 'e' and the old weapons broke and weren't useful like the one you have. Sadly the only way for you to get a new weapon is buying one or getting one from mobs or quests (There is a lvl 55 quest called 'The Shadow of the Beast' in Gavel. With the reward you can buy a weapon in Olux).
