### ISSUE TITLE
Jungle Fever, Almuj's Liquified Emeralds

### ISSUE THREAD

**Issue by taxiishooter** [Wynncraft/Issues#7658]
I am currently doing the "Jungle Fever" quest and i was returning to Detlas bank to talk to Worid and finish the quest, but i had the liquified emeralds in hand when i was about to talk to Worid, i accidentally threw one of the liquified emeralds as if it were a splash potion, i could not retrieve it. I logged on and off but it was still not in my inventory, when i talked to Worid he said  "Hey! Are you done with what i asked?".

**Comment by Trixter313** [comment]
If you put the 63 LE into a loot chest or your daily reward area to get rid of them and then use the command /fixquests it should give you all 64 back to finish the quest.

**Comment by taxiishooter** [comment]
Thank you!

On 5 Apr 2017 9:24 pm, "Nick Cipriani" <notifications@github.com> wrote:

If you put the 63 LE into a loot chest or your daily reward area to get rid
of them and then use the command /fixquests it should give you all 64 back
to finish the quest.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Wynncraft/Issues/issues/7658#issuecomment-291859765>,
or mute the thread

**Comment by taxiishooter** [comment]
Hi Nick, I tried putting the liquified emeralds in a loot chest but they
tell me "You will need this item in later quests"

**Comment by LordHelmchen98** [comment]
Nick wasn't talking about a random loot chest, but about your daily reward that you can claim when you open your compass menu.

**Comment by taxiishooter** [comment]
Oh,  I suppose i'll try that when I receive the daily reward

**Comment by Trixter313** [comment]
Sorry for the confusion on my part, I wanted to make it easier for you to do by including the loot chest as an option but I didn't verify that it would work like the daily reward does.

**Comment by taxiishooter** [comment]
Nah, it's fine the daily reward worked. Thanks for your help!

On 7 Apr 2017 5:28 am, "Nick Cipriani" <notifications@github.com> wrote:

Sorry for the confusion on my part, I wanted to make it easier for you to
do by including the loot chest as an option but I didn't verify that it
would work like the daily reward does.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Wynncraft/Issues/issues/7658#issuecomment-292328644>,
or mute the thread
