### ISSUE TITLE
rip le

### ISSUE THREAD

**Issue by oscarHUN** [Wynncraft/Issues#7659]
hi! my problem is i was in the city called troms and i had 64 eb. im level 61 so i asked my friend to change it for me for a liquid emerald. he made a joke, and threw it on the ground ring in front of that "bridge" in front of the tample, he picked it up and it disappered. what can i do now?

**Comment by ColinRioux** [comment]
Wynn enforces a strict no refund policy. What that means is that you won't be getting your LE back. Sorry!
