### ISSUE TITLE
galleon graveyard dungeon bug

### ISSUE THREAD

**Issue by C4ptainM0rgan** [Wynncraft/Issues#7660]
came across a bug during the dungeon, once i get in to phase 4 where you are on a ship firing cannons at red beard, it teleports me to his ship his ship where i just float above him which doesn't allow me to move at all. I found a way to fix it by typing /hub, joining a different world, typing /hub again and joining a different world again. it fixes the problem but skips that part of the dungeon all together. I tried to see if it would still do phase 4 by jumping into the water thus teleporting to the other ship once, but left me in a never ending battle. why? well 1) red bread's ship wasn't firing cannonballs at me and 2) every time I step on a pressure plate trying to fire at him, the cannonballs won't move. the only way to leave the dungeon is to type /kill thus leaving the dungeon and teleport to the nearest city, but it's a waste of both soul points and dungeon keys. please reply ASAP

**Comment by LordHelmchen98** [comment]
Right bow there are numerous bugs in the Galleons Graveyard dungeon, but those bugs should be fixed when Corkus comes out on Friday/Saturday (depending on time zone). Until then you shouldn't do the dungeon again.
