### ISSUE TITLE
Changed MC Username, Forums says old username.

### ISSUE THREAD

**Issue by ToTheMaxxx** [Wynncraft/Issues#7662]
Hi,
I've changed my Minecraft username a few days ago, and i noticed that on the forums, it still says my old username, i have looked for a way to Change my link to the forums account, but there have not been anyways of doing so.
I would like to change my forums link so it can update my username.

**Comment by Pyromanical** [comment]
Sadly nothing can be done about manually changing your Minecraft username on the forums.  It will automatically change eventually, but in some cases it will take weeks.  All you can really do is wait.
