### ISSUE TITLE
Factory Helmant Gone Missing?

### ISSUE THREAD

**Issue by CocoWuffle** [Wynncraft/Issues#7664]
A few days ago I completed An Iron Heart I and got an iron helment that I identified and used for the quest, which is the Factory Helment. It is a quest item so it is undroppable and untradeable. A few days later, this current day, I level up to level fifty eight and decided to start An Iron Heart II. I'm a few stages in when it tells me that I have to fetch my Factory Helment from the first quest. I go into my bank only to find it's nowhere to be seen and it isn't on my charecter. Where did it go? I couldn't have gotten rid of it. I did the quest. I have no idea, please help.

**Comment by thecoolkogut4** [comment]
type /fixquests  to get the helmet back

**Comment by ColinRioux** [comment]
If `/fixquests` doesn't work the only other solution is to level up another class and transfer it via your bank.
