### ISSUE TITLE
No Connection - Germany

### ISSUE THREAD

**Issue by globemaster123** [Wynncraft/Issues#7666]
Today, just like yesterday, I get no connection on the wynncraft server in the evening & when i'm able to connect to the server, I got 2000ms lag, when I check my internet connection I got my usual 15ms - 75MB Up/35MB down, does that has something to do with my country?

**Comment by LordHelmchen98** [comment]
Yes I'm pretty sure it's related to the country or maybe continent. As the servers are in Canada it's a pretty long distance and apparently the connection from Canada to Europe is pretty bad. I know quite a few players who are facing the same issue but I've never heard an American complaining about that. Therefore I don't think that is anything wynncraft can fix unfortunately.
