### ISSUE TITLE
stuck in bob's tomb

### ISSUE THREAD

**Issue by Blaytran** [Wynncraft/Issues#7667]
hello , im stuck in a wall in bob's tomb , that happened when i tried to do the warrior parkours with a mage (for see if i can do it with mage) and when i used the teleport spell that teleport me in the floor , can a moderator/admin can help me to exit that ? (i tried everythin ; spam tp spell , use a tp scroll , duel with someone to be kill...) coord ; X : 268 / Y : 71 / Z : -753

**Comment by Trixter313** [comment]
You can use the command /kill to be teleported to the nearest respawn point. =)
