### ISSUE TITLE
''There has been an error... Try again.'' when choosing a class

### ISSUE THREAD

**Issue by fcwai** [Wynncraft/Issues#7668]
I am fc1991 in game. I am new to this server :) But when I was gonna start playing on wynncraft, my character stuck in the black room as I can't choose any class, it said ''There has been an error... Try again.'' That's why I am looking for help :P 
Looking for someone to wipe my account's data on wynncraft.
Hmm... hope that I can play on this server before the HYPEEEEEEE Corkus update (?

**Comment by Pyromanical** [comment]
Another case of #7185.  I would say read the post there, but since you already know you want your account's data wiped, I would suggest messaging @Moe-Ronickah on the [forums](https://forums.wynncraft.com/members/moe_ronickah.12864/) for more information on getting your data wiped.

**Comment by LordHelmchen98** [comment]
@fcwai Moe-Ronickah already passed it to the admins so you dont have to post on #7185 again.
