### ISSUE TITLE
They were not banned but this hack requires use of a movement hacks!

### ISSUE THREAD

**Issue by Rani250** [Wynncraft/Issues#7670]
I did exactly the canyon condor quest for more, and I came out of the gold mine when an exploding dynamite. is not it a given speed and in the next instant thrown out of the server. I wanted to go back when it kicked off by connecting to wc8 whilst you have been banned.Reason use of movement hacks !!! please help me!

**Comment by thecoolkogut4** [comment]
Go to [this page](https://forums.wynncraft.com/threads/%E2%9C%8E-appeal-submission-guide-%E2%9C%8E.89247/) on the forums and follow the instructions on the page.
