### ISSUE TITLE
An Iron Heart Part II Broken

### ISSUE THREAD

**Issue by MinecraftPercabeth** [Wynncraft/Issues#7671]
It won't let me enter the factory house, saying "A Factory Helmet is required to enter" even though I _am_ wearing my factory helmet.

My quest book says "Interrogate Elio with the rope"

**Comment by Pyromanical** [comment]
Have you interrogated Elio yet?

**Comment by MinecraftPercabeth** [comment]
Ah, got it. The dialogue led me the believe Elio was in the factory, but I got it now, thanks!
