### ISSUE TITLE
Corkus Update

### ISSUE THREAD

**Issue by globemaster123** [Wynncraft/Issues#7672]
I'm sorry q.q (WC2)
![2017-04-07_20 49 57](https://cloud.githubusercontent.com/assets/26852210/24816502/4e9bb28a-1bd9-11e7-8657-cb944ad8bdce.png)
![2017-04-07_20 50 00](https://cloud.githubusercontent.com/assets/26852210/24816505/5169bbb0-1bd9-11e7-9f45-bbc8c5896a79.png)

**Comment by LordHelmchen98** [comment]
Did you pass the barriers somehow? (would be surprising because there were countless people trying to get inside)
If not I dont see anything wrong here.

**Comment by globemaster123** [comment]
No, no barriers, but there is a piston which moved a slab, should that happen?

**Comment by ColinRioux** [comment]
Fixed! Thank you.
