### ISSUE TITLE
Thunder Effect Does Nothing

### ISSUE THREAD

**Issue by depressedsnail** [Wynncraft/Issues#7677]
So I got excited when I got one of the new player effects, and when I tried it...
![screenshot_1](https://cloud.githubusercontent.com/assets/27039859/24824941/68101b68-1bd2-11e7-9374-0b8839c0bc4b.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/27039859/24824942/69670594-1bd2-11e7-898f-1abd8ae37497.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/27039859/24824943/6a8b27c0-1bd2-11e7-957c-ecc30500a20b.png)

**Comment by ColinRioux** [comment]
Are your particles turned on ?

**Comment by depressedsnail** [comment]
Yes, my particle effects are enabled

**Comment by Imaxe** [comment]
It works fine for me. Is the issue persists, change version.
