### ISSUE TITLE
Bob's Seal of Approval Not Dropping

### ISSUE THREAD

**Issue by AFluffyPlatypus** [Wynncraft/Issues#7679]
Two friends and I are fighting Bob's Reincarnation, and have killed him 5 times on multiple servers, both before and after Corkus came out. However, he's not dropping any Bob's Seals of Approval. We have tried killing him with spells and melee attacks, as well as killing him in the centre of the arena, but nothing has dropped. Please help!

**Comment by LordHelmchen98** [comment]
This should be fixed with the next map push, which will be in a few hours.
