### ISSUE TITLE
Can't select one class

### ISSUE THREAD

**Issue by NitroStarman** [Wynncraft/Issues#7680]
I have returned after a long time of not playing and I wanted to select my level 55 mage class. For some reason an error occurs when trying to select that saved character. I have 4 other saved character classes and I can select and play as them just fine. Only my level 55 mage character I cannot play as.

Here is a screenshot of what happens.
![2017-04-07_23 00 10](https://cloud.githubusercontent.com/assets/21976398/24825149/e996216e-1be6-11e7-918c-02d43739cdca.png)

I really don't want to lose that saved character as I have already invested a lot of time into it.
Is there something I need to do on my end or is it a bug?

**Comment by ZipperDeer** [comment]
I'm having the same problem with my level 49 Archer that i was playing right before the severs updated to Corkus and again all my other characters work. As NitroStarman stated i invested a lot of time into this character after coming back and making a new one and really don't want to lose it. Is there anything that can be done?

**Comment by ColinRioux** [comment]
Corkus has just been released. Please wait a few days and see if it fixes on it's own, and don't force it. If it doesn't, we will troubleshoot after a few days. Corkus is relatively unstable atm, like any other major update.

**Comment by ZipperDeer** [comment]
@ColinRioux I was so worried thank you so much!

**Comment by Moe-Ronickah** [comment]
Hang on a bit, please.  Let's give this a couple of days more to see if it irons itself out.  I may ask all of you for some information to see if we can isolate the problem, in another couple of days.

**Comment by DPlayer234** [comment]
Same issue here.
I distinctively remember having _autojoin enabled_ and the _last class_ I used is the one that doesn't work now.
And, since it may be relevant as well, it was also the _highest leveled class_ on my account and a Hunter.

**Comment by RLLL93** [comment]
answering to Moe-Ronickah, I lost my 55 lvl assassin account, which was acount i last played on. I was in the Olux swamp

**Comment by AiriaVSol** [comment]
For me to answer Moe-Ronickah, mine was my lvl 53 Warrior and i was just around Llevigar

**Comment by ZipperDeer** [comment]
Its been 5 days and nothings changed is the dev team going to release a fix or should i just give up and start over?

**Comment by ZipperDeer** [comment]
@LordHelmchen98 Thanks its been about a week now so ill wait a little longer

**Comment by ColinRioux** [comment]
I should be more specific that this issue is related to data corruption, or at least it has been in the past. The dev team is relatively small, and if the issue this time is in fact "data corruption" then there isn't much that can be done. Best to be patient for a little bit, after-all, it's only been 5 days since @Moe-Ronickah 's last comment. There have been many duplicates of this issue, which you can view by searching in issues "there has been an error".

**Comment by AiriaVSol** [comment]
So if there isn't anything to be done then i guess the Class should just be deleted then huh? Once it's all figured out then i guess we will know.

**Comment by ColinRioux** [comment]
Well if you can log in via other classes, it'd be good to know.

**Comment by RLLL93** [comment]
yes
every other

**Comment by AiriaVSol** [comment]
Every other class does work just fine. No delays or problems with the others, just my Warrior, which is the one i play the most on.

**Comment by NitroStarman** [comment]
> Well if you can log in via other classes, it'd be good to know.

All other saves work fine. Just my highest leveled character (lvl 55 mage) is glitched.

**Comment by RLLL93** [comment]
got a lvl 55 assassin too

**Comment by AiriaVSol** [comment]
I just right this minute checked with my Warrior that wasn't working. I'm in the server with it right now, so i would advise those who were also having troubling to see if you can get in with your character. 
   I hope it works out for the rest of you too and this wont reoccur for anyone else

**Comment by RLLL93** [comment]
works now tnx
 and BTW what was the problem in?

**Comment by NitroStarman** [comment]
I can select and use my mage now. I guess it was some kind of glitch.
