### ISSUE TITLE
Horses not spawning in...

### ISSUE THREAD

**Issue by Minilol** [Wynncraft/Issues#7681]
Whenever I right click my saddle, normally a horse comes out of it but for now, it does not. This happened with two other people that I talked to as well. Get this fixed ASAP please.

**Comment by thecoolkogut4** [comment]
what happens when you switch servers?

**Comment by Minilol** [comment]
Same thing still. I was running on the Wynncraft Enhanced pack. I'll see what happens on vanilla.
