### ISSUE TITLE
Not being able to attack mobs.

### ISSUE THREAD

**Issue by Minilol** [Wynncraft/Issues#7683]
While in-game, I can't inflict damage upon any hostile or peaceful mobs. I tried relogging to no prevail.

Mind fixing this soon please?

**Comment by thecoolkogut4** [comment]
what happens when you switch servers?

**Comment by Minilol** [comment]
Same thing. I even tried switching classes and still not working...

**Comment by Minilol** [comment]
I was on the Wynncraft Enhanced pack. Seems to be working fine now that I'm on Vanilla.
