### ISSUE TITLE
Corkus - Mixed Feelings (Quest)

### ISSUE THREAD

**Issue by Kwaihu** [Wynncraft/Issues#7685]
I was doing the quest mixed feelings, I first walked into the bar and went to talk to Javen, then It said "updated quest book" and I had to "talk to javen." and I went to go talk to him but I was stuck, couldn't move and couldn't talk to him. So I did /kill and then I came back to see if it would be fixed but now I cant even talk to him or do anything.

**Comment by PandaDraygon** [comment]
I did the same thing, I clicked on him to begin the quest, the three lines of dialogue appeared, was moved to an area enclosed by barriers and could continue to talk. I did /kill and came back but couldn't talk to him.

**Comment by Kwaihu** [comment]
Yea Panda, I'm trying to see if I can get a staff member to see this and maybe reset the quest for me or something. or whatever is possible

**Comment by N1NY** [comment]
same i got the same problem too at the quest

**Comment by arronquah555** [comment]
Same here,my in-game name is BlameTheHealer

**Comment by Kwaihu** [comment]
I hate having unfinished quests :(

**Comment by Marhzy** [comment]
I have a solution:
Join a server right after it restarted. The server is "fresh" and you can now continue from the cutscene.

**Comment by UnknownPoni** [comment]
I have it too. IGN: iWheatley.

**Comment by AscendedKitten** [comment]
Bug should be fixed now!
