### ISSUE TITLE
Stuck on ship to selchar

### ISSUE THREAD

**Issue by Powerwan** [Wynncraft/Issues#7686]
I am level 53 i went to corkus and i went on a boat with a guy that takes you to selchar and now i am stuck on it
![2017-04-08_14 43 44](https://cloud.githubusercontent.com/assets/17921125/24825864/ab42d800-1c6b-11e7-97df-95a923e0ad68.png)

**Comment by Glenncrafter** [comment]
I'm not a mod or a helper on this but have you tried to do /kill ?

**Comment by ColinRioux** [comment]
You need to complete the quest Envoy Part I to use the boat, hence the dialogue: "Hey! You aren't allowed on my ship!". We will be working on optimizing so you don't accidentally use the boat, but until you do the quest, you'll get stuck.
