### ISSUE TITLE
The Envoy I: No boat tp (quest got broken)

### ISSUE THREAD

**Issue by Glenncrafter** [Wynncraft/Issues#7691]
I did the envoy party I quest. When I got on boat and got tpd to the trip to corkus my mc crashed. The npc didn't coplete the story he was telling me and I didn't get tpd so I did /kill . Then I retried to go on the boat but now I don't even get tpd on the boat anymore. I even went manually to corkus and the 'Corkus Delegate' isn't there. Plz help me D:

**Comment by numbermaniac** [comment]
From Selchar, right click the guy at the boat first, THEN hop on to the boat; that should get you moving to Corkus. What does your quest book say?

**Comment by Moukassi** [comment]
I have exactly the same issue
