### ISSUE TITLE
The Envoy II: The quest book points me to the wrong place

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7694]
I didn't get to take a screenshot, but: early on in the quest, when you need to locate the catapult, the quest book gives you coordinates that point to the entrance of Avos. But if you go there, it kicks you back saying "the Avos look hostile, you should stay away".

The coordinates given need to be fixed to where the catapult actually is, at roughly [-1702,-3115].

**Comment by ColinRioux** [comment]
Fixed!
