### ISSUE TITLE
Cant login to my archer

### ISSUE THREAD

**Issue by gwylkill** [Wynncraft/Issues#7700]
I cant login to my lvl 82 archer, i have tried multiple times and it keeps saying that something went wrong. i  really need it because i want to play whit my brother.

**Comment by RLLL93** [comment]
I have the same problem with my 55 lvl. Assassin...

**Comment by RLLL93** [comment]
And where were you, when you logged of?

**Comment by gwylkill** [comment]
somwhere in detlas i think

**Comment by ColinRioux** [comment]
Please see #7680 for future updates.
