### ISSUE TITLE
problem, "creeper infiltration" and "out of my mind"....

### ISSUE THREAD

**Issue by GoodmanGaming** [Wynncraft/Issues#7701]
first of, there is nothing wrong with these quests.

before the corkus update i finished all quests up to lvl 83 and i was still lvl 83.... But now after the Corkus update it says that i havent even started on them..... it is weird bc if i havent finished creeper infiltration, then how have i finished ToL??? like you need the creeper mask to be able to get the purple helmet..... weird...

it might not be a glitch/bug..... it might be that they updated these two quests, but if so then please tell me as fast as possible.

**Comment by Glenncrafter** [comment]
Dude have you even seen the trailer ? they are renewed. You have to do them again -,-
