### ISSUE TITLE
I cant Connect

### ISSUE THREAD

**Issue by Clyenn** [Wynncraft/Issues#7702]
I cant connect to the server i press on my Archer class and than:
![2017-04-08_12 18 15](https://cloud.githubusercontent.com/assets/23523429/24828066/f24c2334-1c55-11e7-9cdd-aab99fad60f7.png)

Ingame Name : DoomsReturns

**Comment by RLLL93** [comment]
Same problem

**Comment by DerClassic** [comment]
Ye me to... But only with my Mage Class

**Comment by RLLL93** [comment]
I have it with my assassin class only too

**Comment by RLLL93** [comment]
And I think, that your Mage class has the biggest lvl of them all, yes?

**Comment by RLLL93** [comment]
and where were you when it happened?

**Comment by LordHelmchen98** [comment]
Duplicate of #7680 please look there for any future information.
