### ISSUE TITLE
Mixed Feelings - Corkus Quest

### ISSUE THREAD

**Issue by globemaster123** [Wynncraft/Issues#7703]
Javen won't walk to me
![2017-04-08_12 38 24](https://cloud.githubusercontent.com/assets/26852210/24828193/61d2dd54-1c58-11e7-911f-4c3e9cf78503.png)
![2017-04-08_12 38 28](https://cloud.githubusercontent.com/assets/26852210/24828192/61d17824-1c58-11e7-801b-b83198cbba21.png)

**Comment by AscendedKitten** [comment]
You bugged out of the offmap area; for now try to /kill and enter the bar again, hopefully the cutscene will play correctly.

**Comment by globemaster123** [comment]
Already tried it, sadly it doesn't work, still can't talk to him. Even as i was in that invisible cage he didn't talk to me

**Comment by AscendedKitten** [comment]
Yeah, the cutscene should restart itself in that situation without having to talk to him, but sadly that's buggy at the moment. I'll work on a fix, and you should be able to continue asap.

**Comment by globemaster123** [comment]
Thanks mate, tell me when you finished working on it :)

**Comment by Kwaihu** [comment]
Same Exact thing happened with me

**Comment by AscendedKitten** [comment]
Bug was fixed with the recent patch!
