### ISSUE TITLE
Can't select my Mage Class

### ISSUE THREAD

**Issue by DerClassic** [Wynncraft/Issues#7705]
Hey there, I can't select my Mage Class. Every other class is working as normal but since this morning I can't select my Mage Class anymore. I need help to fix this. Thank you
![ss 2017-04-08 at 12 59 10](https://cloud.githubusercontent.com/assets/27062675/24828367/932ef650-1c5b-11e7-9253-edfb2842a88c.jpg)

**Comment by RLLL93** [comment]
I have the same problem with my 55lvl Assassin
Mabye it is with the place where you've logged of, can you tell me the place?

**Comment by DerClassic** [comment]
I was in LLevigar...

**Comment by RLLL93** [comment]
Me too
or somewhere near

**Comment by numbermaniac** [comment]
#7702

**Comment by WindShadow22662** [comment]
I can't log into my mage as well its lvl 78 and i wanted to play

**Comment by WindowsEXE** [comment]
The class may possibly be corrupted... same thing with my warrior at level 21

**Comment by ColinRioux** [comment]
Duplicate of #7680. Please see there for future updates.
