### ISSUE TITLE
Out of my Mind Bug

### ISSUE THREAD

**Issue by ItsYourPlay** [Wynncraft/Issues#7706]
The door from the secret lab dont open i have the key and my questbook says:
Find a way inside the house at
[-705,58,-817]
I hope someone of you can help me.

**Comment by ColinRioux** [comment]
It's been fixed on build. Will be pushed with the next map push sometime today. I don't know the schedule, but best to be patient.

**Comment by ItsYourPlay** [comment]
Ok thank you for that information
