### ISSUE TITLE
Stuck in the beginning of the Mixed Feeling quest

### ISSUE THREAD

**Issue by PlsCake** [Wynncraft/Issues#7707]
So I have started the conversation with the NPC.
After the end of conversation, I was teleported to the same bar with barriers around.
However, nothing happened, the NPC wasn't talking so i typed /kill
I went to the bar again after my death but the NPC wasn't talking anymore.

Is there any way to fix it? qwq

**Comment by AscendedKitten** [comment]
I am sorry for the bug you experienced, and I am aware of it; it'll be fixed as soon as possible and you should be able to continue the quest then.
