### ISSUE TITLE
I don't have Yellow Crystal Shard

### ISSUE THREAD

**Issue by victorkemp007** [Wynncraft/Issues#7710]
Hi Dears staff member 

The last week i completed the WynnExcavation Site A and normaly i recived a Yellow Crystal Shard.
Can you give me the Yellow Crystal Shard ? Because i need them for complet the WynnExcavation Site B but i can't ... 
I'm connected all the day :D

**Comment by joshuaxlino** [comment]
i have the same problem... srry im not sure how to fix it.

**Comment by L4w3s** [comment]
Just a quick temporary fix for when quest items don't get given to you at the end of a quest, if you type /fixquests it should give you any quest item you are missing from quests you've already completed.

It won't fix the bug which causes you to not get a quest item, but it'll give you the quest item if the quest doesn't give it to you.

**Comment by victorkemp007** [comment]
Thx TOO MUCH DUDE
