### ISSUE TITLE
The Envoy II: Door of Mech base cannot be open.

### ISSUE THREAD

**Issue by maple3142** [Wynncraft/Issues#7714]
As title.
Quest book tell me have to "Retrieve the key from the base."
But the Door of it cannot be open.
coordinate: -1348 109 -2401

changing server not working too...

**Comment by ColinRioux** [comment]
This is because you need to actually use the catapult to use the door. By going in the region where the door is you can update your quest book, but do not update the ability to use the door. Until we fix the catapult, you'll have to find a server which has just restarted to use it.
