### ISSUE TITLE
my quest is glitched

### ISSUE THREAD

**Issue by joshuaxlino** [Wynncraft/Issues#7716]
WynnExcavation Site B mission started by its self and no story line popped up. I tried /dismiss but it says i have no active missions when it says WynnExcavation Site B status started... please help. and the npcs wont for WynnExcavation Site B just say to visit almuj WynnExcavation Site A. I got the crystal and brought it back to WynnExcavation Site B and it said to visit almuj still...

![2017-04-08_11 28 01](https://cloud.githubusercontent.com/assets/25727040/24830263/55ef7176-1c50-11e7-8714-296f3171c61c.png)
![2017-04-08_11 28 06](https://cloud.githubusercontent.com/assets/25727040/24830264/55f0a532-1c50-11e7-8ca0-5d0307e1d8a9.png)

**Comment by Glenncrafter** [comment]
Welcome in my world

**Comment by Moukassi** [comment]
Well that's weird , Note that missions arent quests tho . Try using /fixquest(s)

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
