### ISSUE TITLE
horse and boat glitch

### ISSUE THREAD

**Issue by GoodmanGaming** [Wynncraft/Issues#7717]
horse issue.

I jumped on the horse in detlas and I headed towards troms.... when I arrived in troms and I jumped of the horse I got teleported back to detlas... I tried to go by horse like 3 times but the same thing happened.. something significant is that I get teleported back to the exact spot where I jumped on the horse.

boat issue

it is basically the same just that when I jump of the boat I'm already at the sea bottom....

now there is no problem with the network bc I have 3 ping, 240 Mbps download and 300 Mbps upload

please  fix this as soon as possible bc its quite annoying to jump of the horse cuz you r taking dmg and then you are somewhere completely else being killed by mobs

**Comment by dukio** [comment]
For the horse it's wynn enhanced, maybe boat too....

either way without wynn enhanced riding a horse it's so laggy .... like before the fix.

**Comment by ColinRioux** [comment]
Horse issue have been patched again today as reported by one of our developers. As for boats: we have been aware of it for awhile.
