### ISSUE TITLE
Mixed Feelings

### ISSUE THREAD

**Issue by EthanolIsGod** [Wynncraft/Issues#7719]
I'm onto the 3rd clue, and talked to the female citizen, well tried to. Midway through the server restarted, so I changed server and talked to her again. However, nothing happened. I have tried everything from doing /kill and swapping servers to try to get her to talk to initiate the 'time race' but have had no success. Any help would be appreciated.

**Comment by AscendedKitten** [comment]
Should be fixed within the next patches, changes were made but I am not sure if the first update will include them; I am sorry for the issue, and hope that you'll be able to continue once the changes hit main.
