### ISSUE TITLE
Balloon won't show up in Mixed Feelings

### ISSUE THREAD

**Issue by AK-saurus** [Wynncraft/Issues#7723]
I got all 3 clues and followed the blood trail and all that, I walked around that area where the balloon is meant to be for a solid hour and didn't figure it out. I've /killed, switched servers, done /class, all that stuff. Nothing's working so here we are.

**Comment by AscendedKitten** [comment]
Should be fixed now, in case it still refuses to spawn try to trigger the tripwire at the parkour (just run through it again)!
