### ISSUE TITLE
"Desperatre Metal" map glitch

### ISSUE THREAD

**Issue by gangmembertowelie** [Wynncraft/Issues#7725]
Being Australian, my connection to the server isn't so great. This is the actual issue. So it kinda is a bug but kinda isn't. Basically what happens is when it breaks the floor below me at the bedroom part, I land in the water, but die. This may be due to the water being 1 block high. All you have to do is make the water 2 or 3 blocks deep. Thanks.

**Comment by LordHelmchen98** [comment]
This bug is known and is being fixed.
