### ISSUE TITLE
Items despawned while switching class

### ISSUE THREAD

**Issue by RENZ403** [Wynncraft/Issues#7729]
Hello,
one of my friends has run into an issue where he was stuck behind a Ladder in the Plaugue Laboatory.
I adviced him to try walk out with the class comand and when selecting his mage some of his Items where dropped, although he had the requirements to wear them.
Right afterwards he again tried to use the class comand because it didnt work the first time, while i was still there to load the chunk.
His Items immediatly despawned.
Can someone help me/him in this issue? His ingame name is Phoenixist.
Any help or advice is appreciated.

**Comment by WindowsEXE** [comment]
Sorry but Wynncraft has a strict no refund policy

**Comment by RENZ403** [comment]
Thanks for the advice in that case.
