### ISSUE TITLE
Envoy  part 1

### ISSUE THREAD

**Issue by war-master-9** [Wynncraft/Issues#7730]
i was doing the the quest envoy part 1 i was on stage 8 but then the server i was on went down and now i cant continue my quest. i was at 9/10 but didn't get to 10/10 to get ready for the next stage so i'm stuck at this one point in the quest

**Comment by Glenncrafter** [comment]
I had the same problem but then on stage 2. My mc crashed on the boat. You were probably talking with a NPC right, and he didn't complete his story right ?

**Comment by Moukassi** [comment]
I had the same issue as glenn but still cant resolve it

**Comment by Imaxe** [comment]
It should be fixed now, do /class and try again.
