### ISSUE TITLE
Some problem whit crashing server

### ISSUE THREAD

**Issue by dryter97** [Wynncraft/Issues#7731]
when i going to put a powder on my Bow i lost it when the server "38" crashed. some tim,e when a little probleme append like this i got some stuff disaper and dosnt bring back the stuff. some time is not easy to got.

Think you something can fix a problem like this? when you are trading a powder to a tier 4 and got probleme when the server just not see if the powder exist

**Comment by LordHelmchen98** [comment]
Well this is quite old, but I'll answer anyway. 
When a server crashes the data is not saved correctly so the powders were still in the powder masters menu. Usually they would go back to your inventory but as the server crashed they didn't.
However you won't get the powders back as Wynncraft enforces a strict norefund policy.
