### ISSUE TITLE
Loosing items glitch

### ISSUE THREAD

**Issue by LodHic3** [Wynncraft/Issues#7732]
So i had just finished the Fantastic Voyager quest and spawned near Detlas after the quest was done. Because i had just got the Pendant Of Prosperity i decided i would go to Detlas and identify it. On my way there i used my horse, once i got of my horse i saw that the Pendant Of Prosperity was glitching around in my inventory. Then i just disappeared and i looked for it and asked people around me, its just gone. I would appreciate if i could get a new one.

**Comment by WindowsEXE** [comment]
Sorry but Wynncraft has a strict no refund policy so sorry :(
