### ISSUE TITLE
"Royal Trials" server crash glitch

### ISSUE THREAD

**Issue by Edrin8** [Wynncraft/Issues#7733]
I was doing the airship puzzle in the Royal Trials quest and the server I was on crashed. After I connected to a different server, I was out of the airship. I was stuck on the clouds so I jumped into the void. I appeared at Ragni Outskirts and I had to travel all the way back.

**Comment by LordHelmchen98** [comment]
Unfortunately the airship part is off map and close to the outskirts. Therefore that was the closest respawn point. Maybe that system will get redone in future but for now we all have to handle stuff like that every then and now.
