### ISSUE TITLE
Lost items during Temple of the Legends quest.

### ISSUE THREAD

**Issue by Ermland2** [Wynncraft/Issues#7734]
So, i were doing the Temple of the legends quest ready to start with all items in my inventory. Then i thalk to him and all my items disappear as they should (he takes them) and he tells me to go to the nether portal. When i get there and to the man is needed to thalk to he tells me to get out and so i check the book again and i see that i need ti bring him the items again. But it cant work as i dont have them. Neither in the end chest or inventory. Please help me!

**Comment by RubbrDucky** [comment]
try /fixquests

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
