### ISSUE TITLE
The envoy part 2 

### ISSUE THREAD

**Issue by Bryanboyv1** [Wynncraft/Issues#7735]
QUESTBOOK:Retrieve the key from the basement

I cant enter the basement...

https://cloud.githubusercontent.com/assets/23386795/24831574/97d6e118-1c9c-11e7-9d60-ffe06fb5a402.png

Please help me.

**Comment by essem2** [comment]
works as intended. go around the building and enter it via the water stream

**Comment by Imaxe** [comment]
This has been fixed
