### ISSUE TITLE
Issue with an item from WynnExcavation Site A

### ISSUE THREAD

**Issue by treoo** [Wynncraft/Issues#7738]
QUEST : Go talk to the Lab Assistant Tesh in the tents at [1082,69-1799]

I dont get the item from when i talk to her

![2017-04-08_15 03 42](https://cloud.githubusercontent.com/assets/27090977/24832053/100b5194-1c6d-11e7-9829-691770dcbe03.png)

**Comment by treoo** [comment]
Ign: mateo1gamer

**Comment by LordHelmchen98** [comment]
You should have a paper called "Ancient Writing". Its required to talk to Tesha.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
