### ISSUE TITLE
Mixed Feelings Quest Starting Bug

### ISSUE THREAD

**Issue by iPushObeseKids** [Wynncraft/Issues#7740]
(This happened while I was starting the quest). I clicked on Javen and talked with him, at first I wasn't teleported until I walked behind the bar, after being teleported there were other people in the cutscene which messed it up for me. I got stuck and the cutscene wasn't playing, I didn't get teleported either. After doing /kill to get out and going back, Javen doesn't say anything and I cant be teleported into the cutscene. Please help, I cant continue the quest.

**Comment by AscendedKitten** [comment]
Heya! I am aware of the issue, and it should be fixed with the next patch.
(Duplicate of #7703)
