### ISSUE TITLE
Lost Items

### ISSUE THREAD

**Issue by x7i** [Wynncraft/Issues#7741]
I lost my items due to a roll back, I was on a server, and it shutdown randomly, like it wasn't planned l, didn't count down, nothing, and I logged back in and I check my inventory, MY ENTIRE MAGE SET IS GONE, I start to freak out trying to find it, but it's gone

**Comment by DebugMC** [comment]
Wynn has a strict no refund policy, sorry :C

**Comment by WindowsEXE** [comment]
As DebugMC said Wynncraft has a strict no refund policy so you won't get your mage set back, so sorry man I had to suffer the same when I lost all my armor
