### ISSUE TITLE
Health goes to default when i log in to a server/ die 

### ISSUE THREAD

**Issue by DoctorWhen** [Wynncraft/Issues#7743]
Whenever I die/ log in to a server, my hp goes from the 10k it usually is to around 500. i wanted to make this known so someone can fix it. 

thanks
DoctorWhen

**Comment by numbermaniac** [comment]
Have you checked your armour? It appears that, sometimes, on joining, the game takes off all your armour, causing your health to go down to ~500 as you said.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
