### ISSUE TITLE
I'm stuck on invisible blocks

### ISSUE THREAD

**Issue by xYatoIsABest** [Wynncraft/Issues#7744]
Version Français :
Salut staff de Wynncraft . Pseudo xYato , LvL : 52 et classe : Archer
Contexte : J'étais en train de faire une quête ( Stay , Away ) et puis quand j'étais dans le passé sur la famille "Twain" j'étais resté un moment sur des blocks invisibles du coup je me suis dis que c'était un crash ect... Mais quand j'ai changé de serveur j'étais resté coisser dans le block . 
Du coup est-que un membre du Staff pourrais me TP bien entendu je suis français :/ . Et oui du coup j'utilise Google traduction 

English version : 
Hi Wynncraft staff. Username xYato, LvL: 52 and class: Archer
Context: I was doing a quest (Stay, Away) and then when I was in the past on the family "Twain" I stayed for a while on invisible blocks of the blow I said to myself that ' Was a crash ect ... But when I changed the server I stayed stuck in the block.
So that is a member of the Staff could TP of course I am French: /. And yes of the coup I use Google translation

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by xYatoIsABest** [comment]
Oh duuuuuuuuuuuuuuuuuuuuuuuude thx for your FUCKING HELP OMFG
