### ISSUE TITLE
Issue with One Thousand Meters Under

### ISSUE THREAD

**Issue by jillianbrodsky** [Wynncraft/Issues#7745]
Hello! After the Corkus Update, I leveled up to level 95 and decided to do the One Thousand Meters Under quest. I started the quest normally, and continued doing it, but I am now stuck. At the part where you are supposed to push the white blocks to line up, they will not move. I have tried logging in and out and going to another world, but it does not work. I went to the discord chat and voiced my problem with the quest, and someone said they had the exact same problem. I also talked to Xavier and he said that it worked before the Corkus Update. Thank you for reading and have a nice day!

**Comment by ColinRioux** [comment]
Hi yes, there
