### ISSUE TITLE
Corkus - Fallen Factory - Commando Blocks

### ISSUE THREAD

**Issue by globemaster123** [Wynncraft/Issues#7746]
Hey guys, there is another "bug" in the Fallen Factory, exact at the same place where u couldn't cross the invisible blocks in the vents, because there are exposed Commandoblocks & because of that, you can't cross the vents (WC27 edited: every server)
![2017-04-09_01 42 49](https://cloud.githubusercontent.com/assets/26852210/24833342/63488756-1cc6-11e7-813b-79e46c7f5b41.png)
![2017-04-09_01 42 40](https://cloud.githubusercontent.com/assets/26852210/24833343/634b461c-1cc6-11e7-8185-f7970de5fadf.png)

**Comment by ColinRioux** [comment]
Thank you for reporting, this has been fixed on build and will be pushed sometime soon.
