### ISSUE TITLE
Login Falure

### ISSUE THREAD

**Issue by TrainKid5423** [Wynncraft/Issues#7747]
Ok so I saw the new update today and I went to log in went smoothly then I went to pick my class and I clicked my Level.55 mage (That I logged out on, on the volcanic isles) and it did not work. I tried multiple times and logged out many times tried that and closed minecraft. Still did not work. I tried with my Archer class and it worked fine. if some one could help me fix this I would be very appreciative because that is my main account. Minecraft name (TrainKid5423) (When I click the mage tab to log in it takes a moment then says "There has been an error... Try again.
Select a class! Each class is saved individually across all servers, you can come back at any time with /class and select another class!)
Please help I don't know what to do.

I have a feeling it because of the corkus update that this happened. With me being on a island close to where corkus is.

If you read this and know what to do please help or tell me what to do.
-TrainKid.

**Comment by TrainKid5423** [comment]
![2017-04-08_19 16 43](https://cloud.githubusercontent.com/assets/27105424/24833493/fbfeab10-1c8f-11e7-9769-bd632903df14.png)

**Comment by TrainKid5423** [comment]
![2017-04-08_19 17 53](https://cloud.githubusercontent.com/assets/27105424/24833498/1f58b02e-1c90-11e7-855a-88717b930b61.png)

**Comment by ColinRioux** [comment]
Please see #7185 or message @Moe-Ronickah on the forums. Thank you.
