### ISSUE TITLE
One Thousand Meters Under Teleport Glitch

### ISSUE THREAD

**Issue by Muddykipper** [Wynncraft/Issues#7750]
So, I'm trying to finish the quest I mentioned above.  However, after I finish scaring the monsters away from the window and try to go back to the beds, I get stuck in a black room and can't teleport out.  I've tried jumping, changing classes, changing servers, and killing myself and going back.  I get stuck there every time.

**Comment by LordHelmchen98** [comment]
This is known and will be fixed soon with the next map push.
