### ISSUE TITLE
Liquid Emerald can't be put in one stack

### ISSUE THREAD

**Issue by maple3142** [Wynncraft/Issues#7751]
As title.
these 3 LE I get from "Mixed Feeling" cannot be put in one stack with my others LE.
![](http://i.imgur.com/0jMinBC.png)

**Comment by DebugMC** [comment]
Turn it into emerald block, then into LE. I talked to colin on this, he said he knows

**Comment by LordHelmchen98** [comment]
As Debug said its known and will be fixed soon.
