### ISSUE TITLE
royal trials cutscene

### ISSUE THREAD

**Issue by MisterJoram** [Wynncraft/Issues#7757]
After you have finished the balloon flight you are teleported to a garden, and you just keep floating there in the air and nothing happens.

**Comment by LordHelmchen98** [comment]
This happened to me too but when I tried it on a different server that just restarted the dialogue triggered and I was able to continue.

**Comment by MisterJoram** [comment]
it didnt helped to me yet, but i will keep trying

**Comment by MisterJoram** [comment]
but did you just kept switching servers

**Comment by LordHelmchen98** [comment]
Are you still in the box? I did /kill (unfotunately you will get back to the caravan guy at the very beginning of wynn) and then did everything again on a fresh server. When I finished the airship part I got tped to that other room first then to the garden and luckily the dialogue triggered so I was able to continue.

**Comment by MisterJoram** [comment]
it worked after a couple of tries

2017-04-09 12:03 GMT+02:00 Lord Helmchen <notifications@github.com>:

**Comment by UnknownPoni** [comment]
I have the same problem. Should i just wait or should i keep trying the quest. over and over again.. *ive tried 6 times now. the fighting is getting annoying*

**Comment by LordHelmchen98** [comment]
I assume it will be fixed soon so it would probably be better to wait.

**Comment by LordHelmchen98** [comment]
It should be fixed. Can you try it again if you haven't done that already?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
