### ISSUE TITLE
Sand-Swept Tomb Dungeon gliched me into a wall

### ISSUE THREAD

**Issue by NetherCraftLP** [Wynncraft/Issues#7759]
after i died at the boss battle in the Sand-Swept Tomb, i got teleported in a wall/hill about 50 blocks from where you should land.... and the TP-scrolls don't help as well
![2017-04-09_12 10 07](https://cloud.githubusercontent.com/assets/27135627/24836605/48895404-1d20-11e7-9d29-0e51fed6fd51.png)

**Comment by ColinRioux** [comment]
`/kill` with 5 or more soulpoints.
