### ISSUE TITLE
Fallen factory glitch

### ISSUE THREAD

**Issue by SuperGoldenMario** [Wynncraft/Issues#7760]
So I was in Fallen factory I was witching servers to find a server to continue through because Fallen Factory did not work on my server. when I Selected my class on server 9 I got tped out of the map
![2017-04-09_06 07 09](https://cloud.githubusercontent.com/assets/20846466/24837529/17b8aa62-1ceb-11e7-8305-1256f017db34.png)

**Comment by ColinRioux** [comment]
Just `/kill` with 5 or more soul points.
