### ISSUE TITLE
One thousand meters under

### ISSUE THREAD

**Issue by Bryanboyv1** [Wynncraft/Issues#7761]
When u need to take a nap after the Broken Windshield,
I get tpped in this room and i cant get out of it,

I did /class, Change world, /kill and do everything over again, But none of these worked and i coulnt even use a scroll to. so /kill was my only way out

Please help me

https://cloud.githubusercontent.com/assets/23386795/24837584/8bdee7c0-1d37-11e7-9ea7-e880c39e3a80.png

**Comment by LordHelmchen98** [comment]
This issue is known and will be fixed soon with the next map push.
