### ISSUE TITLE
i can't join in class

### ISSUE THREAD

**Issue by victorayres** [Wynncraft/Issues#7763]
i tried to play in my mage class but every  time try in the chat apeer this  _"have been a erro... try again"_.  What i do to join in my class again?? some one can help me plz?

**Comment by AiriaVSol** [comment]
I cant play my Warrior class either because it claims '_There has been an error... Try _Again'__
( IGN; AiriaVSol )

**Comment by ColinRioux** [comment]
Duplicate of #7680. Please see there for future status.
