### ISSUE TITLE
Fallen Factory teleported in the void

### ISSUE THREAD

**Issue by Jobili** [Wynncraft/Issues#7764]
So i was doing the Fallen Factory dungeon, it was going good and when i arrived to the boss room, i got teleported into the void :/ so ye
![2017-04-09_12 30 43](https://cloud.githubusercontent.com/assets/17226516/24838993/ad8073f6-1d20-11e7-9e03-9774a6c45c6e.png)

**Comment by ColinRioux** [comment]
Clearly you glitched through the teleport room, for whatever reason. I increased the teleport height so maybe it'll load and you won't "glitch" through. In terms of getting back to the dungeon, you'll have to `/kill` and do it again.
