### ISSUE TITLE
Cant Connect to the server 

### ISSUE THREAD

**Issue by KiddoxMC** [Wynncraft/Issues#7765]
Every time i try to open the server this happens
![bandicam 2017-04-09 11-30-33-680](https://cloud.githubusercontent.com/assets/26636108/24839008/9464faf2-1d18-11e7-88ec-4287963179ae.jpg)

**Comment by victorayres** [comment]
you will need to enter in the server in a other version of minecraft

**Comment by KiddoxMC** [comment]
That didn't work
