### ISSUE TITLE
Lost Item

### ISSUE THREAD

**Issue by ItzAbbee** [Wynncraft/Issues#7766]
I was in the Lost Sanctuary dungeon and instead of throwing the TNT in the hopper, i threw my best/only weapon and i was wondering if there was any other way that i would get it back? It was a rare item and it was the BanHammer.

**Comment by ColinRioux** [comment]
Wynncraft enforces a strict no-refund policy, and what that means is that you won't be getting your item back.

**Comment by ItzAbbee** [comment]
Even if it was because it happened accidentally? There should be something that prevents this from happening because it probably has happened before.

**Comment by ColinRioux** [comment]
I have suggested the idea to salted that we replace hoppers with an item detector of sorts. When or If this will be put in-game is unknown. Could be never, could be sometime this year. The no-refund policy still stands regardless of the reasoning, primarily to maintain fairness among all the players. I'd like to note, we used to have a refund policy, but then it was abused to the point where we had to remove it altogether.
