### ISSUE TITLE
I lost all of my item in my inventory

### ISSUE THREAD

**Issue by Mathowen** [Wynncraft/Issues#7767]
I was disconnect approximately at 4pm(french hour) and I was reconnect approximately at 7pm half and all of my item was disappeared , and I was have 1 souls . I doesn't have screen of my inventory full . I lost my item just on my big reroll (My mage)

**Comment by ColinRioux** [comment]
When you die with 5 or less soul points, all of your items drop. You had 1 soul point when you re-logged. 

Wynncraft also enforces a strict no refund policy, and what that means is you won't be getting your items back. Next time, try to have maximum soul points and to disconnect in non-hostile areas if possible.

**Comment by Mathowen** [comment]
thanks for your answer
