### ISSUE TITLE
Nemract - Weapon Shop (Missed texture for weapon?) BUG

### ISSUE THREAD

**Issue by WulfGamesYT** [Wynncraft/Issues#7772]
Hey, I'm not sure if this is a bug but I was just browsing the weapons in Nemract Village, in World 20 and I saw that one of the weapons is a slab, maybe a missing texture for a wizards staff?

Anyway, here is the image I took: By the way im only using default texture pack and no mods what so ever, just the wynncraft pack.

![GitHub Logo](https://i.gyazo.com/ac40f3dc32af52c97f13ee32ab800031.png)

**Comment by ColinRioux** [comment]
This is normal, since the resourepack hasn't been fully updated since wynncraft's native version (1.8.9). With the introduction of weapon models, weapons are now retextured blocks.
