### ISSUE TITLE
Stuck on a boat to Zhight Island

### ISSUE THREAD

**Issue by ShrekOverlord** [Wynncraft/Issues#7773]
I got on a boat to Zhight Island (just to explore i am level 28) and then i got stuck on the ship for about an hour.. I'm kinda triggered right now.
![image](https://cloud.githubusercontent.com/assets/27163092/24840963/46e01b80-1d2d-11e7-862c-a89611f092d6.png) 
Thanks for your help. I am on World 30 at the time of this post!

**Comment by ShrekOverlord** [comment]
Okay its resolved i did /kill

**Comment by LordHelmchen98** [comment]
This issue is known and will be fixed soon. For now dont use the Seaskipper to Zight Island.
