### ISSUE TITLE
belly of the beast lighting glicth

### ISSUE THREAD

**Issue by dyredhead** [Wynncraft/Issues#7777]
I'm in ozoths mouth but because of a lighting glicht I cant see the parkour I'm doing. any sugestions?

**Comment by LordHelmchen98** [comment]
Have you tried F3+a or F3+t?

**Comment by dyredhead** [comment]
no ill try

**Comment by dyredhead** [comment]
didn't help :(

**Comment by LordHelmchen98** [comment]
Which MC version are you using?

**Comment by dyredhead** [comment]
1.9 optifine

**Comment by LordHelmchen98** [comment]
Have you tried to relog?

**Comment by dyredhead** [comment]
yes multipule times

**Comment by LordHelmchen98** [comment]
I just got there and its glitched for me as well. Ill let someone know about this.

**Comment by dyredhead** [comment]
ok thanks

**Comment by dyredhead** [comment]
is there some possible way a mod can creative and put a torch down?

**Comment by dyredhead** [comment]
nv I swithed to 1.8.9 and it is light again

**Comment by dyredhead** [comment]
thanks for your help anyway

**Comment by LordHelmchen98** [comment]
You're welcome
