### ISSUE TITLE
Personnal quest problem "Lord of the clock"

### ISSUE THREAD

**Issue by Lemrigue** [Wynncraft/Issues#7779]
Hi, I was doing the "Lord of the clock" quest where I had to talk to gundalf and throw his clock into the mt wynn, however, when I arrived to the Mt Wynn, I tried to throw the clock (I didn't see the PNJ Frudo), but then the clock dissapeared from my inventory (because there were a monster meat on the ground and it took the place of the clock when I clicked on it)

So is there a way to give me the clock once again so I can complete this quest, it would help thanks

**Comment by Pyromanical** [comment]
Do `/fixquests`
