### ISSUE TITLE
Need help with the catapult, kinda.

### ISSUE THREAD

**Issue by Aurakys** [Wynncraft/Issues#7780]
Hey so I was doing Envoy II and the catapult didn't work, so I went on without it by climbing the mountain. It was fine for a while until I got up to the factory I had to infiltrate after following the trail. The button on the emerald didn't let me in.

[https://gyazo.com/60b10474c29121af8b6dfdd5e0226aba](url)

So I went back to the catapult and it didn't do anything. Does anyone know how I can fix this issue?

**Comment by numbermaniac** [comment]
That door is confusing, after doing the quest myself I don't think you're meant to use that door. Around a side of the building you'll notice a long stream of water going down; I got into the base by swimming up that (it might take a while). Note that's it not the one directly below the door, but instead around another side of the building.

**Comment by Aurakys** [comment]
I'll try that later, thanks!

**Comment by ColinRioux** [comment]
You must press the button (on the emerald block) to summon Maxie again for the catapult to draw back down. Can confirm that this works on main. 

To open the inn door (at the farm house) you must first use the catapult, then talk to the grandmaster, in that order.
