### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by MysteryDust** [Wynncraft/Issues#7782]
I'm stuck in a glass box in the ballroom in deltas Nick usually gives a speech to the guests and that's where the people that do the quests stand in but I just got in the ballroom in an accident and now I'm stuck in the glass box when I tried to leave the ballroom
https://gyazo.com/1f5f7a557fb2df90f4315c18efc78d20
https://gyazo.com/bdafe562838d7bff306ff0d019ae7562
Well I hope you can help me because I'm stuck there and can't get out.
Ps I'm stuck with my archer class

**Comment by numbermaniac** [comment]
You can try `/class` and select your class again, see if that triggers Nick to talk. Otherwise, if you have more than 5 soul points, you can `/kill` to get out.

**Comment by MysteryDust** [comment]
I did the quest, I guess I need to do /kill then

**Comment by MysteryDust** [comment]
RIP souls points

**Comment by numbermaniac** [comment]
It's only two soul points, they'll regenerate after two in-game day cycles, lol. (You can press the "Close issue" button below the comment box if it's resolved.)

**Comment by MysteryDust** [comment]
Thank you very much @numbermaniac  <3
