### ISSUE TITLE
"You dont have permission for this area" cant open doors, chests, click buttons or interact with npcs 

### ISSUE THREAD

**Issue by St0rmfir3** [Wynncraft/Issues#7784]
after the corkus update was released everytime i tried to right click something [whether they were chests, npcs, the ground or anything] it would tell me that i dont have permission for this area

i assumed this was just a little glitch because the server just updated, but ive been trying everything i could [ive restarted minecraft, tried different classes, teleported to various cities to see if it works,] but it just keeps telling me the same thing??
this is very inconvenient because i am now unable to do quests or go to certain places because id need to open a door or interact with a button
![2017-04-10_12 42 27](https://cloud.githubusercontent.com/assets/27205805/24858375/630c58e0-1dec-11e7-85a8-0e6827930c82.png)

**Comment by LordHelmchen98** [comment]
This happens because your Weapon is a retextured half slab and for some reason the game thinks you want to place it. Use another item or your bare hands to interact with chests, door,... and you should be fine.
