### ISSUE TITLE
Wavebreaker + The Envoy pt 1

### ISSUE THREAD

**Issue by Moukassi** [Wynncraft/Issues#7786]
Hello ! 

Ive come across an issue wich is realy realy anoying.
I cant use the Wavebreaker to get to corkus but i can use it to go to selchar ( i activated all tripwires ).
Since i wasnt able to use the boat i couldn't spawn in the Delegate to and because of that i cant finish the quest.Sadly enough you need the quest to do another quest ( envoy 2 ). those 2 quests are basicly the entery quests of corkus and i dont want to miss them. ive been trying to fix the bug since the release and i contacted several staff ( they all said i should post something here ).I realy hope this bug can be resolved because it's a big part of the corkus gameplay. There are several bugs spread acros corkus 2 tho.
Well not a bug but there are empty caves and buildings and the spawn rate of some mobs are WAY to high.
I cant safely afk in corkus city because i keep getting killed and the guards will sometimes attack eachother and yourself.when i die on corkus i dont get tp'd to relos or corkus but most of the time Ragni or Llevigar.
If you are going to take action on these bugs could you inform me please ?

Thanks !

Moukassi

**Comment by MusicScore** [comment]
Can confirm that the Wavebreaker seemingly does not let you go to Corkus. I've already completed the Envoy I quest, and have been able to go to Corkus multiple times prior to today.

**Comment by Moukassi** [comment]
@MusicScore  I saw other posts about this issue ( Glenncrafter or something has the same issue as me , like exactly the same ).

**Comment by Imaxe** [comment]
This is fixed. It will take affect when we push the map :)

**Comment by Moukassi** [comment]
@Imaxe "When we push the map" ?
