### ISSUE TITLE
Diamond Hydro Necklace Punctuation.

### ISSUE THREAD

**Issue by Celsonic** [Wynncraft/Issues#7787]
Just a really small detail... noticed the period was missing at the end of the lore.
Nothing that big :)
![2017-04-10_09 50 31](https://cloud.githubusercontent.com/assets/21028327/24864885/8f5d5598-1dd3-11e7-9aeb-0334014e5aa7.png)

**Comment by Celsonic** [comment]
Found Another Error...
![2017-04-10_10 03 22](https://cloud.githubusercontent.com/assets/21028327/24865340/f4cf50b0-1dd4-11e7-8ae3-867945cd07d9.png)

**Comment by AscendedKitten** [comment]
Fixed! Thanks for reporting, changes will take effect once the new patch is applied.
