### ISSUE TITLE
Royal Trials

### ISSUE THREAD

**Issue by 4Bengals** [Wynncraft/Issues#7788]
Ok so I am in the last trial for Royal Trials and after she explains what to do I am stuck hanging above the mansion. This has happened to me twice now and I have tried to do /kill and /class and none of it will work. Can someone help me please and fix this?

**Comment by LordHelmchen98** [comment]
This is currently a bit broken but in work.
Sometimes it works if you try it on a fresh server but if you dont want to risk it you should wait a bit.
