### ISSUE TITLE
My Warrior doesn't work after the new update 

### ISSUE THREAD

**Issue by Ronnie0982** [Wynncraft/Issues#7792]
For some reason my level 78 warrior class don't work after Corkus got out, and i have no idea how to fix it...
![2017-04-10_20 16 45](https://cloud.githubusercontent.com/assets/4800840/24876120/c463eab6-1e2a-11e7-9d19-1b2d343c083a.png)

**Comment by DebugMC** [comment]
#7185

**Comment by LordHelmchen98** [comment]
Duplicate of #7680 please look there for future information. 
(@DebugMC)
