### ISSUE TITLE
Out of my mind misspelling

### ISSUE THREAD

**Issue by TheTankEngine** [Wynncraft/Issues#7793]
Very small, but in the text lines of the new out of my mind quest, there is a misspelling, it says were, instead of where. Small, but important! Cya!

**Comment by Pyromanical** [comment]
Could you post a picture of the mistake so the GMs can find it and fix it faster

**Comment by AckroWynn** [comment]
The two instances in the quest where the word "were" is mentioned are both grammatically correct.
