### ISSUE TITLE
Alkevo is Glitched

### ISSUE THREAD

**Issue by BenP2033** [Wynncraft/Issues#7796]
I'm fighting Alkevo (The Floor 6 Boss of TOA) and I get him down about 50,000 health and then he just respawns with full health. It takes me about ten minutes to get him down about that far. I tried just waiting and not attacking him and he still respawns. I've been attempting the boss for a few days now and same result every time.

**Comment by Pyromanical** [comment]
This is because of Alkevo's ability, suicide strike.  This isn't a glitch, you just aren't killing it fast enough.  Try and find a stronger weapon for your level or level up more so you can use a better weapon.  You can also ask a friend to help you kill it.

**Comment by BenP2033** [comment]
Ok, thanks for telling me.
