### ISSUE TITLE
blue meteor for ??? quest is broken

### ISSUE THREAD

**Issue by C4ptainM0rgan** [Wynncraft/Issues#7797]
me and my friend are trying to get to the blue meteor shard by doing the hay bale puzzle but nothing happens. it says in the wiki that fire works are supposed to go off when it's finished but they don't go off thus we can't do the parkor. we tried switching servers but it doesn't fix it. please reply ASAP

**Comment by ColinRioux** [comment]
Are you sure you are completing the puzzle correctly? The hammer shape of hay bales must be in a specific position.

**Comment by C4ptainM0rgan** [comment]
yes we are doing that but nothing happens

**Comment by C4ptainM0rgan** [comment]
nvm it fixed itself, but do keep it in mind
