### ISSUE TITLE
Mixed Feelings - Unprogressable

### ISSUE THREAD

**Issue by YouWynnILose** [Wynncraft/Issues#7798]
Hey there.
_______
I have just completed the first stage of the Mixed Feelings quests. It teleported me to a place that looked the same (with different coordinates) there are barriers blocking my way (I do know this is intentional). 
_______
However, I think the barrier blocked me clicking the npc and I cannot proceed because I cannot click on Javen. Also, according to a friend of mine, he said that the tavern should be on fire but it looked EXACTLY the same.
_______

**Comment by AscendedKitten** [comment]
Hey! When exactly did that issue occur? This is a known bug, and should've been fixed a while ago. In case you are still stuck, /kill with 5 or more soulpoints and then try to re-enter the tavern.
