### ISSUE TITLE
Elemental Defense Bug.

### ISSUE THREAD

**Issue by HolyYoshi** [Wynncraft/Issues#7799]
So when I changed my millennium chest plate to Booster Plate, I found a bug, or I think its a bug.

This is my armour before I changed the Millennium to Booster Plate:
http://imgur.com/NaP5URM
http://imgur.com/xF8E51d
http://imgur.com/vKxc2IM
http://imgur.com/pAMpuN7
http://imgur.com/rR9bmF9
http://imgur.com/8hoYNI2
http://imgur.com/vMqPV3F
http://imgur.com/wqH7E2s

Elemental Stats before changing to Booster Plate:
http://imgur.com/vIntBv7

This is my armour AFTER I changed the Millennium to Booster Plate:
http://imgur.com/uOWeoLp
http://imgur.com/NAjtzhg
http://imgur.com/aKTLLan
http://imgur.com/1VUr9f5
http://imgur.com/S02xhVu
http://imgur.com/KuXFvyN
http://imgur.com/efQdT2F
http://imgur.com/C5wa5wR

Elemental Stats AFTER changing to Booster Plate:
http://imgur.com/xtnzaPD

Conclusion:

As you can see, quite a bit of stats don’t make sense, for example. Before I changed my chestplate, I should have had  around -60 fire def. but in the end I have -195

Please fix ;-;

**Comment by Pyromanical** [comment]
The defenses in the compass are completely screwed up, don't trust it.  You just have to calculate your defenses manually.  This is a well known issue by the staff.

**Comment by LordHelmchen98** [comment]
Resolved
