### ISSUE TITLE
Stuck in the wall

### ISSUE THREAD

**Issue by MarkusTheKnusp3r** [Wynncraft/Issues#7803]
Hello Wynncraft Team. 
I was playing Wynncraft and were at maltic in the hole of the witch. The I used my teleport spell and I was stuck in the wall. I tried to use a teleport scroll but it doesn't work. Now I can't get out and do nothing. 
I home anyone of you can teleport me out that I can play again. 
Thanks for reading my bug Report.

**Comment by LordHelmchen98** [comment]
If you have more than 5 soul points do `/kill` to get out.
