### ISSUE TITLE
Recipe for disaster bug

### ISSUE THREAD

**Issue by TheMineNerf** [Wynncraft/Issues#7805]
So I chose to do the sky high pie for frank, but everytime I try to give him the items, he tells me I need to go and get the items.
![2017-04-11_17 00 28](https://cloud.githubusercontent.com/assets/10617419/24913025/8a2265ae-1ed8-11e7-96f7-ea92555088a5.png)
![2017-04-11_17 00 29](https://cloud.githubusercontent.com/assets/10617419/24913027/8a2a1a9c-1ed8-11e7-9e04-6138517f2e1c.png)
![2017-04-11_17 00 26](https://cloud.githubusercontent.com/assets/10617419/24913026/8a25fb2e-1ed8-11e7-8f8c-ab83cdec96a8.png)
![2017-04-11_17 01 22](https://cloud.githubusercontent.com/assets/10617419/24913036/929695ac-1ed8-11e7-9230-7eb1dd590806.png)

**Comment by Pyromanical** [comment]
What does your quest book say?

**Comment by TheMineNerf** [comment]
Bring your ingredients to your selected chef. I decided to go with kale, which workedm

**Comment by SmirrenIsMyName** [comment]
You need to make the wheat to flour. you do it close to where you got it from. Speak to the baker
