### ISSUE TITLE
Creeper Infiltration is bugged.

### ISSUE THREAD

**Issue by RazzorWind** [Wynncraft/Issues#7807]
I hate this re-done quest. The first time I re-did it, upon picking up the creeper skin, nothing happened. This time upon activating the cut scene and being blown back to the village, the quest made it so I cant attack anything. I also died because of it.

**Comment by RazzorWind** [comment]
Well what do you know! When I take off the creeper mask inside the cave, I get teleported AT THE BEGINNING of the map where you start out on a new character! Also world 5 is completely unplayable for me since i cant attack anything.

**Comment by numbermaniac** [comment]
Where exactly are you up to? You're not meant to take off the creeper mask inside the cave - then they'd know you were a human! If world 5 is broken, you might want to switch servers...

**Comment by RazzorWind** [comment]
Usually when taking off a item that is required to be in the area, the user gets teleported at the beginning of the area. This should happen, as it does with Maro Peaks and the climbing helmet. As of world 5 being broken, that issue had seemed to be fixed upon world restart.

**Comment by IcePirate1221** [comment]
I'm having a similar problem. When I went into the area where you're meant to collect the creeper skin, i went in with a party of two other players. Only one of us was able to collect the creeper skin. The creeper skin never loaded in for the other player and I.

**Comment by LordHelmchen98** [comment]
The starter area is kind of a backup place if some teleport stuff goes wrong. I don't know if that happened to you, but you are lucky you only tried to do creeper infiltration. Some people faced issues like that when doing something on the sky islands. Anyway I'll test that myself and if it teleport you to the beginning all the time I'll pass it to someone who can fix that.
