### ISSUE TITLE
Identifying glitch

### ISSUE THREAD

**Issue by Castelaization** [Wynncraft/Issues#7808]
in my inventory i have a item that is unidentified (the creeper mask to be specific) and i want to identify it, i go to an identifier and click on it, then it says that i cannot re-identify him. and i need this for the temple of legends quest for that dude in the basement.
Kind regards,
Castelaization

**Comment by Castelaization** [comment]
[Minecraft 04.11.2017 - 18.11.58.01.zip](https://github.com/Wynncraft/Issues/files/913905/Minecraft.04.11.2017.-.18.11.58.01.zip)
here is a video of it

**Comment by LordHelmchen98** [comment]
The quest Creeper Infiltration was revamped with the Corkus Update on April 7th. Now the Creeper Masks have set stats that are not supposed to be changed, therefore they cant be reidentified. The consequence of that is that old Creeper Masks which weren't identified cant get identified anymore.
However the new Creeper Infiltration quests shows you how to get another Creeper Mask and you can throw away the old one as Creeper Masks aren't quest items anymore but only untradeable items.
