### ISSUE TITLE
Items Disappearing on login

### ISSUE THREAD

**Issue by Dudman23** [Wynncraft/Issues#7809]
so i logged in to the game and started playing then there was some connection issues so after joining and disconnecting several times the issues were fixed but then i saw that my bow, a mesarock arch, was missing from my inventory, i know it wasn't dropped because i have drop bound to the other side of my keyboard. i'm frustrated about this because i lost it at LVL 38 and i had two T4 powders on it if someone could tell me what happened or how to prevent it, and if i can get it back or be compensated that would be great.
thank you

**Comment by Kroko64** [comment]
the exact same thing happened to me. I lost my Freedom bow that i payed 4 stacks of le for.

**Comment by DebugMC** [comment]
Wynncraft has a strict no refund policy, sorry :c

**Comment by Dudman23** [comment]
that's ridiculous, others and myself are losing items and wynncraft won't compensate for something that isn't our fault. i understand the thinking but it's still unfair, i get that some people want free stuff but preventing them is preventing others from getting help. I've had to go back to a standard bow doing 5% of the damage because of a bug and i get no help.

**Comment by DebugMC** [comment]
Just like you said, this is to prevent people from asking for free things. Also, we would have to do a rollback, which would effect everyone.. so no the staff will not be 'compensating' you xD
