### ISSUE TITLE
Building/CMD mistakes related to "Desperate Metal"

### ISSUE THREAD

**Issue by LordHelmchen98** [Wynncraft/Issues#7810]
In stage 2 of the new quest "Desperate Metal" you have to go into a water cave. When you do that and press the button in the middle it will spawn pillars so you don't have to swim back. I doubt it is intentional that it copies air in the corners of the pillars.
![](http://puu.sh/vgVcu/b57a09f432.png)

Close to it I also noticed that there is grass underwater. If thats not supposed to be seaweed I guess thats wrong ;)

![](http://puu.sh/vgUPi/17c389ef56.png) | ![](http://puu.sh/vgUWV/1a27125a79.png)
------------ | -------------

**Comment by Imaxe** [comment]
Issue has been fixed. It will take affect when we push a patch :)
