### ISSUE TITLE
WynnExcavation Site A Issue! (Can't complete quest anymore)

### ISSUE THREAD

**Issue by zjedo** [Wynncraft/Issues#7811]
When talking to Excavator Vade he tells me (Have you translated that test yet? I told you, take it to the tent up there and give it to Tesha!)
When i talk to Tesha he tells me (Take that to vade, and don't read it!)
He never gave me the Quest Item back and they both keep saying this.
I tried to kill the boss down below and when i kill him (5 min off fighting) nothing happens.

Extra info
My Quest book says (Return and talk to Excavator Vade)
I looked the quest up in the wiki and basicly i think the quest bugged out and skipped a part which made the quest be stuck at one point.

I tried /fixquests it says no items are missing.

I hope staff can restart the quest for me or that someone has a fix for me.

**Comment by Pyromanical** [comment]
If `/fixquests` doesn't work, that means the text should be on you, in your bank, or in another class.  Have you checked all those places?

**Comment by zjedo** [comment]
Yes it wasnt there but i found the issue i just wanted to close this.
What happend was when you go in you have to come out with the crystal otherwise they keep saying these things that confused me into thinking that i didnt received the item.
But i realized after kill the boss for the third time i got the crystal which first didnt drop.
I found out because there is fire in that room if the boss dies from the fire dmage he doesnt drop the crystal (in my case)
To be sure i tested it 2 more times and my theory is true.
Anyway when i talked to Vade and when i had the crystal everything whent smoothly.

**Comment by zjedo** [comment]
Anyway thx for the kind support
