### ISSUE TITLE
Fantastic Voyage - Boulder Bug

### ISSUE THREAD

**Issue by Lambabe** [Wynncraft/Issues#7812]
When doing the Fantastic Voyage quest [Level 90] on Gateway Island, I became glitched over the boulder north of Relend. I was on Stage 18, given the task to bring 5 Grainy Sand, 3 Saw Dust, and 1 Black Powder to the Crafting Table.

I obtained the materials and walked off the nearby tree tops to head to Relend, but became stuck over the area of the boulder as it reset my character due to me not reached the step to blowing up the boulder. It let me fall to the ground taking fall damage before resetting me back in the air, creating a loop. I unfortunately died before I could record the glitch. I respawned back on the tutorial stage of the map before Ragni.

I have attempted to travel back to Gateway Island but it is impossible to return back as I'm still midway through the quest. If I could get the quest reset, it would be appreciated.

My IGN is Lambabe; Level 91 Archer.

**Comment by Pyromanical** [comment]
I think you just get back on the boat in Joshfash to go back to Gateway Island.
