### ISSUE TITLE
Doing Memory Paranoria quest, stage 21

### ISSUE THREAD

**Issue by xPandaPvPerx** [Wynncraft/Issues#7813]
http://imgs.dlgames.co.uk/aK75nmc0dA.png

Randomly happens, can't even load into the world to class or /kill . Any ideas?

**Comment by thecoolkogut4** [comment]
are you currently using any mods when your playing on the server? If you are try to disable them/load a clean version of mc and see what happens. Are you able to join other MC servers?

**Comment by LordHelmchen98** [comment]
Apparently you removed your image(s). Therefore I assume your issue has been resolved.
If not just comment and I'll reopen it.
