### ISSUE TITLE
Zhight Island Bug

### ISSUE THREAD

**Issue by CodyC99** [Wynncraft/Issues#7815]
Every time I try to go to Zhight Island using the SeaSkipper it will tp me to the boat in the ocean but then it doesn't tp me to Zhight Island so I am stuck in the boat at sea. ![2017-04-11_19 35 24](https://cloud.githubusercontent.com/assets/27319057/24936348/1dbd8ba8-1eee-11e7-9314-fdccbef4296b.png)
![2017-04-11_19 35 29](https://cloud.githubusercontent.com/assets/27319057/24936365/3e5c0e70-1eee-11e7-937e-2659055be210.png)

Im stuck here

**Comment by LordHelmchen98** [comment]
This issue is known and will hopefully be fixed soon. Until it is fixed you should try to get there with a normal boat, because no matter where you start it will always teleport you broken Seaskipper that is supposed to bring players to Zight Island.

**Comment by CodyC99** [comment]
Ok thanks
