### ISSUE TITLE
Chunk error outside detlas 

### ISSUE THREAD

**Issue by thediamondkittie** [Wynncraft/Issues#7816]
Huge missing chunk right outside of Detlas as u head towards Ternaves/Almuj , Im in world 2 not sure if it is anywhere else 
![2017-04-12_02 01 04](https://cloud.githubusercontent.com/assets/22036899/24936815/6d4adf32-1f24-11e7-87ac-006516c60074.png)
![2017-04-12_02 01 13](https://cloud.githubusercontent.com/assets/22036899/24936831/87899190-1f24-11e7-9cec-b8c253a08c88.png)

**Comment by LordHelmchen98** [comment]
Currently there are some chunk errors. This problems is known and will be fixed as soon as possible.
In order to get out you will have to do `/kill`.

**Comment by Scorpioxzz** [comment]
This is literally everywhere...
![2017-04-11_18 47 33](https://cloud.githubusercontent.com/assets/24771034/24937714/650737fe-1ee7-11e7-81e5-ec0850d0144a.png)

**Comment by r1579** [comment]
![2017-04-11_22 37 10](https://cloud.githubusercontent.com/assets/27324796/24938968/6644ba80-1f08-11e7-91fb-5c8d6ecd3c43.png)

can also confirm that another error has been made outside troms

**Comment by DebugMC** [comment]
should be fixed by tomorrow.

**Comment by LordHelmchen98** [comment]
This has been fixed now.
