### ISSUE TITLE
Detlas Chunk Error

### ISSUE THREAD

**Issue by katelikesturtles** [Wynncraft/Issues#7817]
Detlas is having multiple chunk glitches. There are spots with no blocks until a certain point, and if you land without a horse, you will die. Is this a glitch, or did a mod screw with the terrain? Either way, I'm asking for myself and other players if it can be fixed anytime soon. Please respond as soon as possible.

**Comment by LordHelmchen98** [comment]
Duplicate of #7817 look there for more information.

**Comment by numbermaniac** [comment]
> Duplicate of #7817

@LordHelmchen98 I think you just linked back to this issue. You probably meant #7816 :)

**Comment by LordHelmchen98** [comment]
@numbermaniac wow didnt realize that thanks.
