### ISSUE TITLE
Glitched Item??

### ISSUE THREAD

**Issue by ItsTheUnknown** [Wynncraft/Issues#7818]
So, I was on my mage, which was just level 31 from doing the Underworld Crypt Dungeon, and right after I finished the dungeon, I realized that there was a wooden axe in my inventory. I'm not sure when I got it, whether I picked it up during the dungeon, or the drops glitched and it gave me the axe as a reward or falling item. I was originally going to report the holes in the ground around Detlas and other places, but I noticed somebody already had. Here is the screenshot I got of the axe. It is just a normal wood axe, and works as if you punched something with your hand, doing 1 damage and not telling me I can't use it or anything. By the way, I meant to report this about two days ago, when this happened, but I forgot to, and just now am here. Thank you.
![2017-04-09_15 59 02](https://cloud.githubusercontent.com/assets/27323430/24938248/f75cb6a8-1f03-11e7-80d9-8e98683a7e05.png)

If you need to contact me about this, my ingame name is FVShadow.

**Comment by LordHelmchen98** [comment]
The possession of vanilla items is illegal. Please throw this Axe away. Thank you.

**Comment by Hegezcc** [comment]
Apparently my friend got a lot of Wooden Axes by grinding the Underworld Crypt dungeon (I think not multiple axes per round, just doing the dungeon over and over). I assume issues like these should be reported to the code team, not only closed.

This is a real bug, related to Underworld Crypt dungeon, allowing for possession of vanilla Wooden Axe.
