### ISSUE TITLE
Mask Of Courage Glitch

### ISSUE THREAD

**Issue by BradCraft90** [Wynncraft/Issues#7820]
So recently I grinded the jungle boss altar for a while to get enough antic beads to purchase the mask of courage from the Tribal Merchant in the Iboju Village... it was pretty cool at first, 1900 health, cool perks, and the best part was it looked totally awesome... until I had to relog and when I got back on the mask was completely glitched and looked like a steve skin... this was really annoying and I couldn't figure out how to fix it, I eventually just grinded for 20 more antic beads to get a seconds mask and the SAME THING HAPPENED... it looked like a steve/alex skin... I know this isn't just me because my friend just had the same thing happen, the mask is still glitched and wont go back 
Screenshot -----> [http://i.imgur.com/yL8wf6n.png](url)
This takes away from the experience of the game as well as making it totally ugly to the point where neither me or my friend use it anymore... it would be awesome if this could be fixed, hopefully some time soon... thanks

**Comment by TBlazeWarriorT** [comment]
Happens to all masks, they only work after purchase until you log out. Same, I also hope it gets fixed, they look really cool when not broken yet.

**Comment by AscendedKitten** [comment]
Sadly this can't be easily fixed, as it's a default MC limitation; hopefully the upcoming code refactor allows us to change that.
