### ISSUE TITLE
Mixed Feelings: Typo in first citizen's dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7830]
1/6: "cities" should be "city's":
![2017-04-10_19 41 21](https://cloud.githubusercontent.com/assets/5206120/24956859/f51fbb3c-1fcc-11e7-877f-d131ccb66cc4.png)

**Comment by AscendedKitten** [comment]
Thanks for reporting! It's been fixed and changes will take effect once a new patch is released. 
For the future, please don't make seperate issues for every typo, that makes it way more tedious to fix.
