### ISSUE TITLE
Mixed Feelings: Typo just before the airship

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7831]
Grey text at the bottom: "unusuable" should be "unusable":
![2017-04-11_18 31 11](https://cloud.githubusercontent.com/assets/5206120/24956910/22f52934-1fcd-11e7-8a0d-2463753dbb33.png)

**Comment by AscendedKitten** [comment]
Thanks for reporting! It's been fixed and changes will take effect once a new patch is released.
For the future, please don't make seperate issues for every typo, that makes it way more tedious to fix.
