### ISSUE TITLE
Mixed Feelings: Typo in "ending" dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7832]
First grey text: "corkian citizen" probably needs a capital C, and I think it should either be "**a** Corkian citizen" or "Corkian citizen**s**":
![2017-04-11_18 35 29](https://cloud.githubusercontent.com/assets/5206120/24956950/4c2c73d4-1fcd-11e7-8505-89c1590cb1a7.png)

**Comment by AscendedKitten** [comment]
Thanks for reporting! It's been fixed and changes will take effect once a new patch is released.
For the future, please don't make seperate issues for every typo, that makes it way more tedious to fix.
