### ISSUE TITLE
Mixed Feelings: Typo in Security Executive's dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7833]
3/3: "properity" should be "property":
![2017-04-11_18 37 16](https://cloud.githubusercontent.com/assets/5206120/24957018/97361718-1fcd-11e7-9371-ebcd4474acbc.png)

**Comment by AscendedKitten** [comment]
Thanks for reporting! It's been fixed and changes will take effect once a new patch is released.
For the future, please don't make seperate issues for every typo, that makes it way more tedious to fix.
