### ISSUE TITLE
Out of my Mind: Formatting error(?) in Prentiss' dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7834]
4/10: I've seen bold text used in other quest dialogues. I assume that was meant to be used here too, for "was":
![2017-04-11_19 23 11](https://cloud.githubusercontent.com/assets/5206120/24957070/ca1b1980-1fcd-11e7-9278-cbdc0d04725e.png)

**Comment by AscendedKitten** [comment]
It's not really an issue, since using stars to emphasize something works better than having bold text in some instances, and I do think that it was done on purpose.
