### ISSUE TITLE
Out of my Mind: Possible typo in Ariodo's dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7835]
3/3: I'm not sure if the last word is intentional, or if it's meant to be "moment":
![2017-04-11_21 09 40](https://cloud.githubusercontent.com/assets/5206120/24957160/22d1dd2a-1fce-11e7-922b-f10c3df70fea.png)

**Comment by AscendedKitten** [comment]
It was already fixed a bit ago, and changes will take effect once a new patch is applied. Thanks for reporting!
