### ISSUE TITLE
Out of my Mind: Typo in Ariodo's puzzle dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7836]
5/8: On the last line, "were" should be "where":
![2017-04-11_21 10 20](https://cloud.githubusercontent.com/assets/5206120/24957206/4b05ab6e-1fce-11e7-8886-a86e895a538e.png)

**Comment by Pyromanical** [comment]
#7793 @AckroWynn this does have a misspelling, unless it was fixed on GM already

**Comment by AscendedKitten** [comment]
It was already fixed a bit ago, and changes will take effect once a new patch is applied. Thanks for reporting!
