### ISSUE TITLE
Out of my Mind: Typo in Prentiss' final dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7837]
11/11: "righly" should be "rightly":
![2017-04-12_18 16 05](https://cloud.githubusercontent.com/assets/5206120/24957257/792fa9ae-1fce-11e7-8eef-ca914f8c9077.png)

**Comment by AscendedKitten** [comment]
Thanks for reporting! It's been fixed and changes will take effect once a new patch is released.
For the future, please don't make seperate issues for every typo, that makes it way more tedious to fix.
