### ISSUE TITLE
Selchar: Typo in citizen's dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7838]
I think this was the citizen standing near the bridge to the bank, on the island side (not the bank side). "Maro peaks" should probably have a capital P. Also, I _think_ it should be "all that is left **are** the sheeps and rams". And I don't think "sheeps" is usually pluralised with an "s": I could be wrong, but I think "sheep" is also the plural.
![2017-04-12_18 24 10](https://cloud.githubusercontent.com/assets/5206120/24957570/7f976858-1fcf-11e7-8680-d16e77883cc3.png)

**Comment by AscendedKitten** [comment]
Thanks for reporting! It's been fixed and changes will take effect once a new patch is released.
For the future, please don't make seperate issues for every typo, that makes it way more tedious to fix.
