### ISSUE TITLE
Relos City: Typo in citizen's dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7839]
Lower 1/3: "wynn" is usually capitalised (capital W), from what I've seen previously. The citizen was just next to the coordinates in this screenshot:
![2017-04-12_18 42 36](https://cloud.githubusercontent.com/assets/5206120/24957670/c7f83d70-1fcf-11e7-96f5-0d19836270af.png)

**Comment by AscendedKitten** [comment]
Thanks for reporting! It's been fixed and changes will take effect once a new patch is released.
For the future, please don't make seperate issues for every typo, that makes it way more tedious to fix.
