### ISSUE TITLE
Desperate Metal: Typo in Fiery Mech-DM2's dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#7840]
2/2: "Intruded" should be "Intruder":
![2017-04-12_19 05 06](https://cloud.githubusercontent.com/assets/5206120/24957874/a51511c4-1fd0-11e7-9fda-6db47592d19d.png)

**Comment by AscendedKitten** [comment]
Thanks for reporting! It's been fixed and changes will take effect once a new patch is released.
For the future, please don't make seperate issues for every typo, that makes it way more tedious to fix.
