### ISSUE TITLE
Eating a Zombie Eye

### ISSUE THREAD

**Issue by XXHACTXX** [Wynncraft/Issues#7841]
Near Troms, if you get a zombie eye, and you try to hold right click while holding it to eat it, nothing happens, which makes sense, because why would it be in the game? But then when you ride a horse and try to eat it, it does the animation of eating it, it finishes eating, but the zombie eye you are holding doesn't go away, as if you didn't eat it, and you aren't supposed to eat zombie eyes. It is only a minor bug.

**Comment by Pyromanical** [comment]
I'm pretty sure being on horse doesn't effect the eating.  The eating animation starts when you try and eat food without full mana.  I'm guessing you had full mana when on the ground, so you couldn't eat, and not full mana on the horse, so the eating animation started.

**Comment by LordHelmchen98** [comment]
As said you can only 'eat' food if you don't have full mana. However this is not really a bug and definitely not gamebreaking as it doesn't consume the food so you still have the item afterwards. Therefore I don't think this has to be changed.
