### ISSUE TITLE
Lazarus Pit bugged

### ISSUE THREAD

**Issue by SunlessDawn** [Wynncraft/Issues#7843]
I was doing the quest Lazarus Pit but the code panel seems to be bugged. if i press the buttons nothing happens. I tried watching a youtube video to see if there was something that i was doing wrong but I did it right and the panel is still not working. does anyone maybe know how i can fix this? (i meant the panel with the wood buttons in stage 4 when you have to enter the basement of the ruined house incase this wasnt clear)

-SunlessDawn

**Comment by AscendedKitten** [comment]
Might be that the redstone on your server is broken, try switching to a different one!

**Comment by LordHelmchen98** [comment]
I just tried it and had no problems. Therefore I assume it was a one time issue and it has been resolved.
