### ISSUE TITLE
Europe region

### ISSUE THREAD

**Issue by globemaster123** [Wynncraft/Issues#7844]
Got lags from germany for the hole day, my connection is just fine & my ping is perfect, i just can't load into wynncraft, it's lagging like shhhh~
http://prntscr.com/evmzt8

**Comment by AscendedKitten** [comment]
Hey! Might be worth checking out this thread on the Wynncraft Forums, it seems to have helped a lot of players with a smimiliar issue.
https://forums.wynncraft.com/threads/fix-for-logging-into-a-wynncraft-server.183991/

**Comment by globemaster123** [comment]
Trying it, thanks !

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
