### ISSUE TITLE
Can't Complete 1000 Meters Under

### ISSUE THREAD

**Issue by RedLogicP** [Wynncraft/Issues#7845]
I finished 1000 meters under, then had to drop items to speak to the scientist at the end. I accidentally picked up an item as I spoke to him, and it said this: 
![2017-04-12_13 04 53](https://cloud.githubusercontent.com/assets/24531217/24970842/cc1b7fd0-1f83-11e7-81f9-0fc77afc1bb1.png)

Now when I right click him it just prints a blank message, my quest book says I haven't finished the quest.
(And no, /fixquests does not work, as it thinks I turned it in.)
Is there any way to fix this?

**Comment by Imaxe** [comment]
We have no idea what happened here :/
