### ISSUE TITLE
A Marauder's Dues Quest Spelled Incorrectly

### ISSUE THREAD

**Issue by Pokefrist** [Wynncraft/Issues#7847]
When you level up to Lv. 83, it shows the quests you've now unlocked. I took a glimpse at the quests as I leveled to 83 and saw a mistake with one of the quests written in the chat bar. The name of the quest is "A Marauder's Dues".

Look at the part with the quest name above. It shows a ^ symbol rather than an apostrophe.
![2017-04-13_09 51 45](https://cloud.githubusercontent.com/assets/27384193/24984190/51b4af1c-202f-11e7-906d-fb12a8543a69.png)

**Comment by Pyromanical** [comment]
Nothing can be done about this.  Because of the format quests are stored in, they cant have apostrophes.  All quests with apostrophes use the caret symbol instead.
