### ISSUE TITLE
House of Twain can't drop down in the graveyard

### ISSUE THREAD

**Issue by FriedRiceNinja** [Wynncraft/Issues#7848]
I got the ghost helmet did everything that needed to be done, but I left on accident and logged back in I got spawned outside and I can't go back inside

**Comment by Pokefrist** [comment]
Are you wearing the helmet whilst trying to go near the graveyard area? sometimes the world may not allow you to move your inventory around, you could always switch worlds if you haven't already. Just a suggestion
