### ISSUE TITLE
C.S.S Wavebreaker at fault

### ISSUE THREAD

**Issue by Pokefrist** [Wynncraft/Issues#7849]
I saw a loot chest sitting on the ship at Selchar and decided to try and open it up, when I clicked on it and it didn't open, I noticed the block above it wasn't allowing me to open the chest. I decided to ignore it until I was going to Corkus and noticed the block wasn't above the chest anymore. Is this a loot chest being misplaced on the ship at the dock/whilst riding or a building error with the ship's sails.
Screenshot of the C.S.S Wavebreaker parked at the Selchar pier:
![2017-04-13_16 34 38](https://cloud.githubusercontent.com/assets/27384193/24993005/b3b70ac4-2067-11e7-854e-a400f13243ef.png)

Screenshot of the C.S.S Wavebreaker being used in the ocean:
![2017-04-13_16 34 55](https://cloud.githubusercontent.com/assets/27384193/24993034/ddc89904-2067-11e7-8698-41065537d2c1.png)

I hope this helps the Wynncraft community in some way.

**Comment by ColinRioux** [comment]
Fixed on build, will be pushed in the next map push!
