### ISSUE TITLE
Can't complete Beneath the Depths quest, trigger doesn't fire.

### ISSUE THREAD

**Issue by zestysoft** [Wynncraft/Issues#7850]
Discussion here:
https://forums.wynncraft.com/threads/quest-milestone-not-triggering-for-beneath-the-depths.184287/

Example video here:
https://www.youtube.com/embed/hlT0ZuvAKdY?vq=hd1080&autoplay=1

Problem:  After killing the "Treasure Guardian" and picking up the gold bar "Ocean Treasure", questbook does not update and end NPC will not communicate with me to complete the quest.

**Comment by LordHelmchen98** [comment]
Your quest book is not supposed to update when you defeated the boys, but it should have updated when entering the cave. Can you try to trigger a quests book update at the entrance of the cave?

**Comment by zestysoft** [comment]
Dancing around the entrance solved the issue.
