### ISSUE TITLE
Fully Formed Amadel doesn't drop Amadel's Pendant upon death

### ISSUE THREAD

**Issue by Alexicon1** [Wynncraft/Issues#7851]
Was duoing the boss with a partner, we killed him (only just surviving) and there was no drop, and he respawned instantly and then killed us. And no, neither of us got it so it isn't me just not dealing enough damage to the boss. Kind of irritated as I bought so much gear for the fight but got cheated by a bug.

Cheers,
Alexicon1

**Comment by Pyromanical** [comment]
Final form of Amadel has two forms, did you kill both?  Only the second form drops the pendant.

**Comment by Imaxe** [comment]
The last form drops the pendant you need. You probably missed him :)
