### ISSUE TITLE
Sea Skipper Captain didn't put me on the boat

### ISSUE THREAD

**Issue by XXHACTXX** [Wynncraft/Issues#7852]
I was at Pirate Cove, I just completed the Beneath the Depths quest, and I was going to go to Llevigar to grind, so I bought a boat pass. When I put the boat pass into the hopper, the captain said "I'll get you there in no time," and he did. I was just teleported to the docks in front of Llevigar. This isn't a major bug, but Wynncraft might want to fix this.
http://imgur.com/xiODvgC
If you go to the link above, you will see he doesn't say anything about Llevigar, besides "Going to Llevigar?" And, he says "You are entering Pirate Cove," and then "You are leaving Pirate Cove," when I was already in Pirate Cove.

**Comment by Pyromanical** [comment]
I believe one of the sea skipper dialogues is just teleporting you straight there, so this might not be a bug.  About the leaving/entering Pirate's Cove, the region probably didn't cover the sea skipper enough, so it was partly in and partly out.

**Comment by numbermaniac** [comment]
The docks at the edge of Pirate Cove are not considered by the game to be part of Pirate Cove, so you'll get told you're leaving it as you approach the docks. Usually, if you get a boat pass to Llevigar, he teleports you there instantly because he doesn't really have anything to say, for some reason. Is that the bug you're reporting?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
