### ISSUE TITLE
Can't Pick Up Leucsaa's Journal

### ISSUE THREAD

**Issue by Mystical-Mist** [Wynncraft/Issues#7853]
So I've gone through the Leucsaa's mansion quest FOUR times now and haven't been able to complete it because I can't pick up the journal. I've restarted minecraft a few times and even waited a day to try it again in case of lag or something but I still haven't been able to pick it up! :( Any help? I searched the issues and didn't see anyone else complaining. And no, my inventory is not full.

![pic1](https://cloud.githubusercontent.com/assets/27423399/25004432/64b98270-2022-11e7-9d8c-17ef2f826c99.png)

**Comment by Pyromanical** [comment]
It's a mob, you have to kill it before you pick it up.

**Comment by Mystical-Mist** [comment]
Oh! Now I feel dumb lol
