### ISSUE TITLE
Normal Wooden Axe from Underworld Crypt dungeon

### ISSUE THREAD

**Issue by Simuciokas** [Wynncraft/Issues#7856]
Got a hold of a normal Wooden Axe from the Underworld Crypt dungeon (227;-1950)
Don't know at which stage I got it, but only noticed it while at the boss.
http://i.imgur.com/L6vqq0B.png

**Comment by LordHelmchen98** [comment]
Duplicate of #7818 
Apparently my assumption was wrong and you were not the one who originally created a thread here. However as I also answered on your thread on the forums, throw the item away if you haven't done it already.
