### ISSUE TITLE
My Wand Disappeared

### ISSUE THREAD

**Issue by EggLotad** [Wynncraft/Issues#7857]
So today I was having a few minor lag issues while connecting to the server and on the class selection menu, i was able to place my class icon into my inventory. Just out of curiosity i pressed Q and dropped the icon. but just as i did that, my game began to load and i entered Detlas. When i looked into my hotbar, my actual wand was gone. I asked the moderator Marion about it but they had said they had never heard of the issue and couldnt help. What i was thinking was maybe when i dropped the class icon due to lag maybe the server was loading my inventory in the caravan therefore i dropped my real wand when i was holding the icon in the same spot? This is literally just off the top of my head im not really sure how the Wynncraft class selection works. But if what i said was what happened and any moderators/admins are willing to look into the issue, my name is **EggLotad** and im a **Hero/Vet** and this all happened in **Server 1**
-Thank You,
         EggLotad

**Comment by EggLotad** [comment]
I forgot to mention the wand was a Glare with Tier 4 Thunder and Fire Powders

**Comment by AscendedKitten** [comment]
I am sorry for the loss you experienced, but due to Wynncraft's no-refund policy it can't be returned; however, I am sure that some players are willing to get you a replacement if asked nicely. You could also check out the forums.
