### ISSUE TITLE
Iron Heart I quest: Won't let me enter the cave where the defective iron golem is.

### ISSUE THREAD

**Issue by IntrepidCucumber-CNNFakeNews** [Wynncraft/Issues#7861]
I have talked to Duvale, and he requests that I get him "1 mechanical pieces" and "1 power source". However, I can't because every time I get near the mountain I tped away with the text: "Terrifying robotic clinks and clashes can be heard below. You feel you should stay away for now." I don't know why it won't let me progress, seeing as I've done everything I'm supposed to. Am I missing something, or is my quest glitched?

**Comment by AscendedKitten** [comment]
What does your quest book state? It could be possible that you just entered the mountain/cave in a different way, as the quest requires you to go the path so the region can trigger.

**Comment by IntrepidCucumber-CNNFakeNews** [comment]
I tried entering via the path you're supposed to take and it worked!
