### ISSUE TITLE
/fixquests bug

### ISSUE THREAD

**Issue by TheMusicGuy** [Wynncraft/Issues#7863]
So I'm not sure if this has been a new bug or it has been there for a while, but the command /fixquests gives quest items back if you lost them, but i did that and it gave me quest items for quests which i already did. They're taking in a bit of space which is quite annoying.
The items i got back from were:
- Maxie House key for the The envoy part II quest
- Healing water for the quest Lazarus Pit (i'm not sure, it's been a while since i have done that quest)
- Slime Scooper for the quest Green Gloop

The House key and the Healing water i got in my inventory while i got 2 Slime Scooper in my bank.
The class i got them on is Archer.
http://imgur.com/a/8FpRY (picture link with the items and quests completed).
You can delete this if there already has been a report of this bug.
Thank you for your time atleast.

IGN: The_Music_Guy

**Comment by AscendedKitten** [comment]
Yeah, sadly the command doesn't make a difference between completed quests and the ones not done yet; this might improve with the refactor, but for now you can just try to get rid of the items via e.g your dailychest (putting them in there to remove them, be careful though)
