### ISSUE TITLE
Stuck in wall during quest

### ISSUE THREAD

**Issue by SoftyBunny** [Wynncraft/Issues#7864]
While I was doing the quest "Green Skinned Trouble I got teleported into a wall, and I'm now stuck.

After I killed the boss down in the secret cave I quickly used the teleportation spell to get out since another boss spawned. I don't know if the teleportation spell was the cause, but after i stepped on the coal blocks I was teleported. I am now inside a block. I've clicked f5 and I saw that I was next to the supposed correct room, only a couple blocks inside the wall.

**Comment by AscendedKitten** [comment]
If using /class doesn't work, you can use /kill with 5 or more soulpoints; you will be teleported to the closest city.
