### ISSUE TITLE
Inventory Glitched

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7867]
I was trying to find things in my bank classes and put stuff in bank and switched and they were gone (no I am not asking for something), but when i went back, they were in my other classes inventory. So I put it in the bank again, and it disappears again. I soon realized, everything I was doing was being undone when I clicked something. (I lost nothing, and it fixed by leaving then rejoining,  but it is still an issue) 

I will try to provide an video next time it happens.

**Comment by thecoolkogut4** [comment]
This has happened to be about two times before. All I had to do was restart MC and it was all fixed.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
