### ISSUE TITLE
"Mixed Feelings" Not giving me the hint

### ISSUE THREAD

**Issue by Amonzip** [Wynncraft/Issues#7868]
Me and my friend are doing the "Mixed Feelings" quest and we are at stage 3. We talk to the first citizen. The thing is that he doesnt give the " [1/3] Hints ". The other two citizens do. I dont get why this is happening and we can not complete the quest and follow the trail. We tried doing the quest again and so on with /kill and nothing works. Please help!

**Comment by JackyKit123** [comment]
@Amonzip is your issue similar to #7774

**Comment by Amonzip** [comment]
@JackyKit123 This was the first time for me doing the quest but yes otherwise its the same

**Comment by numbermaniac** [comment]
Does the first citizen still say to go help out the others?

**Comment by Amonzip** [comment]
@numbermaniac yes

**Comment by AscendedKitten** [comment]
Might be a bit late, but try finishing all of the tasks and then relogging (or using /class); that should hopefully fix it.
