### ISSUE TITLE
Ba'al

### ISSUE THREAD

**Issue by Motoman3737** [Wynncraft/Issues#7870]
Other people must have found this: Ba'al is missing. I have checked the images on where he should be and I have died 6+ times getting there, 3 of the times dying right where he should have been.
![2017-04-14_20 54 20](https://cloud.githubusercontent.com/assets/27535980/25060547/de913772-2154-11e7-8b6f-8e548691c502.png)
My crosshairs should be on the spot where he should be.

**Comment by RubbrDucky** [comment]
I can confirm. I was trying to help a friend, he died so many times. I stayed at the spot, ba'al never spawned.

Try switching servers.

**Comment by Imaxe** [comment]
Ba'al should be in the "basement". Follow the trail of blood on the outside and it should lead you to some parkour and then you'll find Ba'al. Maybe the coords are off, I'll fix it

**Comment by LordHelmchen98** [comment]
I was there and found him where he is supposed to be, so I assume it works again now.
