### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by BatmanNicki** [Wynncraft/Issues#7871]
Hello Wynncraft Staff, some of my quest have reset but I still have some of the items. I don't understand this bug/glitch.

**Comment by LordHelmchen98** [comment]
Recently the quests 'Creeper Infiltration' and 'Out of my Mind' got revamped. Therefore they were reset and everyone has to do them again. Also you said you have items left. I assume by that you  mean a Creeper Mask. As you get a new one from the new quest you can throw the old one away.
Does that explain your issue?

**Comment by BatmanNicki** [comment]
yea it does thanks
