### ISSUE TITLE
Losing Armour After Corkus Update

### ISSUE THREAD

**Issue by WynnDOG** [Wynncraft/Issues#7873]
After corkus, when item requirements were changed, I had a squid anklet on me as well as a really amazing memento. But, at the time my inventory was full so when my items came off the slots, they disappeared. I don't care as much about the squid, but I'm annoyed from losing my memento.

**Comment by LordHelmchen98** [comment]
Thats unlucky and Im sorry for your loss, but you wont get the item back, because Wynncraft enforces a strict norefund policy.
