### ISSUE TITLE
Creeper Cave Logout and Login Glitch

### ISSUE THREAD

**Issue by RubbrDucky** [Wynncraft/Issues#7876]
You get teleported out of the map onto barrier blocks if you logout and log back in while standing next to Garull.

I had to /kill.
https://youtu.be/rDetclLBTEU

**Comment by LordHelmchen98** [comment]
Sorry for the inconvenience, but apparently this was a one time issue.
I just tried it and had no problems.
https://youtu.be/CKzkDD5vApk

**Comment by RubbrDucky** [comment]
I guess never mind then :P
