### ISSUE TITLE
cant connect

### ISSUE THREAD

**Issue by oscarHUN** [Wynncraft/Issues#7877]
this is so shitty... if i close my minecraft while im online on the server or my net/game crashes i cant login for days.... pls fix this cauz this is so fustrating... i can play on other server only wynncraft is fcked up

**Comment by thecoolkogut4** [comment]
what IP are you using to connect? try play.wynncraft.com play.wynncraft.net let me know how thouse go

**Comment by oscarHUN** [comment]
Sry for my langluage.... i was so pissed off! I ll try it out as soon as i can and i ll reply (i think play.wynncraft.com

**Comment by LordHelmchen98** [comment]
@oscarHUN is it fixed now?

**Comment by oscarHUN** [comment]
Yeah it is. The answer for my q is : if one doesnt work use the other ip instead. Always fix the problem
