### ISSUE TITLE
New patch - dropping items

### ISSUE THREAD

**Issue by Jagerme1ster** [Wynncraft/Issues#7878]
I haven't played in a while and decided to return to Wynncraft. All seemed well till I decided to join a server.

I dropped all equipped items following a patch. I worked hard on getting and improving that armour. Is there any way to be compensated?

The issue arrose when I spawned into a server. My character automatically dropped all equipped items (chest, legs, feet, head) and other players just rushed in and picked them up. :(

This was golden gear (level 20 - 25 I think) and all enchanted with powder.

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by Jagerme1ster** [comment]
I completely understand, and I think I will continue to play here even after having lost these items. After all, refunding would be nigh impossible with a large playerbase and without any means of keeping track of what players may have on them.
