### ISSUE TITLE
Spelling mistake in dialog

### ISSUE THREAD

**Issue by WulfGamesYT** [Wynncraft/Issues#7879]
Look, should be "you're" not "your"
https://gyazo.com/5c42c8a452238fce62b8fc4d2f9bc195

For Caras:
https://gyazo.com/f897c838f1cafcd82eaec15b29717841

**Comment by WulfGamesYT** [comment]
Also, just noticed again!
There is "your're" in there also, change that to the correct spelling.

**Comment by ColinRioux** [comment]
As you can tell, I don't know which quest you are referring to. If you could be specific and possible which quest stage, that'd be great! Thanks

**Comment by LordHelmchen98** [comment]
@ColinRioux Its the message you get from [Caras](https://wiki.wynncraft.com/index.php?title=Caras) if you haven't reached the required level for "Tribal Aggression".

**Comment by ColinRioux** [comment]
Fixed!
