### ISSUE TITLE
Over 100% guild XP

### ISSUE THREAD

**Issue by ElBley** [Wynncraft/Issues#7881]
![2017-04-15_22 59 29](https://cloud.githubusercontent.com/assets/23029925/25066748/bafa6802-222f-11e7-943b-35862b45b7c4.png)
I's been a while since we got 114% of XP, we are a small guild and we are not donating any XP anymore because It doesn't grow the counter

**Comment by thecoolkogut4** [comment]
This happens to all guilds and it is a well-known bug. My guild has over 1400%. The only thing you can do is wait and hope you eventually level up.

**Comment by ColinRioux** [comment]
This has already been reported. Closing.

**Comment by LordHelmchen98** [comment]
Actually it should update until you are level 52 (above level 52 guilds cant level up on their own), but in the lower levels it takes a bit more than 100% sometimes. However it shouldn't go above 120% before your guild levels up.
