### ISSUE TITLE
Weird block near the east entrace of the Corkus City potion shop

### ISSUE THREAD

**Issue by Equipa2** [Wynncraft/Issues#7883]
I was wandering around Corkus City in server 23 and i found this block:
![2017-04-15_22 52 20](https://cloud.githubusercontent.com/assets/16447942/25067032/5d815c44-222f-11e7-9bfd-7cd7d6568025.png)

**Comment by ColinRioux** [comment]
This has been fixed on build, will be pushed with next map push and was reported last night.
