### ISSUE TITLE
The Envoy Part I Powder Bug

### ISSUE THREAD

**Issue by MedievalBladeRPG** [Wynncraft/Issues#7890]
Using the /class command and going onto the same class during the stage of the quest in which you follow the delegate around town results in the spawning of a second delegate. At the conclusion of the tour, both will give you four powders, resulting in the acquisition of eight grey powders.

**Comment by thecoolkogut4** [comment]
so your saying every time you /class in that part of the quest another NPC spawns which results in more powders? or does it just work twice?

**Comment by Imaxe** [comment]
This is an abuse. Do not report it here
