### ISSUE TITLE
Quest Glitch

### ISSUE THREAD

**Issue by MattmanK924** [Wynncraft/Issues#7897]
Hiullo, a week or so ago, my friend and I were doing a quest named Frost Bitten. We were at the part at which we obtain the explosive from Cabac and then we give it to Alein. We both did so and agreed to get off for the night then. The next day, we got back on Wynncraft and to my friend's dismay, he found that the quest was broken even though mine was totally okay. Even though we both gave Alein the explosive, my friend still had to give it to Alein the next day. Since we gave Alein the explosive already, he couldnt give it to him. He tried relogging but it didnt work. We also tried gaining the explosive again by obtaining the 10 gunpowder from the imps but Cabac wouldnt give it to him. So he has no way to obtain the explosive as well as give it to Alein. Plz Harlp

**Comment by thecoolkogut4** [comment]
what does his questbook say?

**Comment by ColinRioux** [comment]
^

**Comment by MattmanK924** [comment]
something like give the explosive to Alein

**Comment by ColinRioux** [comment]
Is that in his quest book or yours?

**Comment by MattmanK924** [comment]
his

**Comment by ColinRioux** [comment]
Tell him to try `/fixquests`

**Comment by MattmanK924** [comment]
because my quest was totally fine, i could continue, but he couldnt

**Comment by MattmanK924** [comment]
o cool

**Comment by ColinRioux** [comment]
Did that work?

**Comment by MattmanK924** [comment]
what does that do?

**Comment by ColinRioux** [comment]
It returns items needed for quests.

**Comment by MattmanK924** [comment]
o

**Comment by ColinRioux** [comment]
Please update me if it worked.

**Comment by MattmanK924** [comment]
He's not online at the moment so as soon as he is on, ill try to msg

**Comment by LordHelmchen98** [comment]
@MattmanK924 was it possible to fix it?

**Comment by MattmanK924** [comment]
I'm not sure yet. He hasn't tried it yet even though I've tried making him do it

**Comment by MattmanK924** [comment]
Thanks, it did work
