### ISSUE TITLE
Stuck on black screen

### ISSUE THREAD

**Issue by PixelRealms** [Wynncraft/Issues#7898]
I completed a quest (can't remember the name sorry, I just remember you have to kill a lvl 50 orc after getting axe heads, then you bring the axe you got from the lvl 50 orc and give it to the guy who gave you the quest) and when I went into one of the teleporters to get out of one of the quest places it wouldn't load. Its been stuck on a black screen that hasn't loaded where I'm meant to go next, I can't see anything or move around because its like I'm stuck in one space. I can use spells and look at my inventory but the game itself wont load. I'm an archer on lvl 48 and I'd really like this to be sorted out as it has been stuck on the black screen since Friday (its now Monday for me).

**Comment by numbermaniac** [comment]
If you have 6 or more soul points, just do `/kill` to get out and be teleported to the nearest town.

**Comment by PixelRealms** [comment]
oh right! why didn't I try that? Thanks I'll try it next time I go on wynn =]
