### ISSUE TITLE
Yahya's Hopper not working

### ISSUE THREAD

**Issue by WackyMagician** [Wynncraft/Issues#7899]
Okay, I looked around for any solutions for this problem, but I haven't found any.

The problem is, my friend and I have been working on the ??? quest. We gathered all 3 pieces for Yahya's hopper, but the hopper does not work. We tried this a total of 7 times. We threw in the items slowly, we threw them in at different times, we jumped servers over and over. However, we still cannot fix this problem. It worked fine the first time I did the quest, ???.

Items we threw in; in order
Black Spoon (Memory Paranoia)
Skien's Island Painting
Strange Mushroom (Bigger Picture)

Thanks,

-WackyMagician

**Comment by ICHIGOunserscore** [comment]
the Skien's Island Painting had to be from the same server it was collected from

**Comment by LordHelmchen98** [comment]
As said above the painting has to be fresh. If you change classes or servers it breaks and cant be used anymore. The reason for this is an issue with NBT tag which get lost after a class or server change.
If you try it with a fresh painting it should work out.
