### ISSUE TITLE
Can't Kill Orc Guards or Gorgu in Quest "A Fighting Species"

### ISSUE THREAD

**Issue by CocoWuffle** [Wynncraft/Issues#7900]
Whenever I do quests, I usually ride on my horse so that I can skip past all the minor enemies so that I can go straight to the boss. I've never had problems until today. I rode all the way down to the boss cave where the leader of the orcs Gorgu is. The door didn't close fast enough and I had an army of orcs after me, so i turn around to do a spin attack spell and it didn't work. Maybe it was glitch or I ddi it wrong was what i thought. I tried again and it didn't work. I gave up and starting hitting them with my weapon (that i've had forever and alwasy worked) but no preveal. I relogged. I took off new armor in case that was the problem. Took off new accessories. Logged onto a different world. Nothing is wokring. I'm currently sitting onto of a tent with the boss and minions underneath me, with nothing to do but hope they dont find a way up. Please help.

**Comment by Imaxe** [comment]
They are in fact killable. You probably have bad gear. As you level up you need to get new weapons.

**Comment by LordHelmchen98** [comment]
@CocoWuffle Were you able to kill Gorgu now?

**Comment by RubbrDucky** [comment]
Did you do any damage? or were they not taking ANY?

**Comment by Locky1110** [comment]
What weapon did you use?

**Comment by CocoWuffle** [comment]
I have a legendary dagger, yu misinterpted my question. They don't take ANY damage

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
