### ISSUE TITLE
Creeper infriltration .

### ISSUE THREAD

**Issue by Bryanboyv1** [Wynncraft/Issues#7905]
The emerald block isnt stacking with my other emerald blocks, its kinda annoying please fix it thx!.

https://cloud.githubusercontent.com/assets/23386795/25088814/838939a2-2379-11e7-9f2a-b1cc34ee9b51.png

https://cloud.githubusercontent.com/assets/23386795/25088813/8377d61c-2379-11e7-9ceb-ce6280977ee5.png

**Comment by LordHelmchen98** [comment]
You can go to an emerald merchant and trade the EB to single emeralds and then back to a block. It will stack afterwards.
However this bug is known and should be fixed soo.
