### ISSUE TITLE
"Specal Offer"

### ISSUE THREAD

**Issue by r0rym1t2** [Wynncraft/Issues#7906]
So, I went into the store and saw the special offer with "any rank", so I decided to buy VIP+. I did not get the special offer rewards? what do I do to get them or can I not get them because I already had VIP?

**Comment by LordHelmchen98** [comment]
Only players who buy their first rank and players who got their first rank after October 31st 2016 get that special offer. If you bought your rank after that date you can send a mail to support@wynncraft.com, ask for that offer (include your ingame name).
