### ISSUE TITLE
Quest Item bugged

### ISSUE THREAD

**Issue by MysteryDust** [Wynncraft/Issues#7907]
At the quest Iron heart II the factory helmet is required and I have it, yet I can't enter the factory 
https://gyazo.com/b3390b8a1787b7d067466c01371206bf
https://gyazo.com/c2672e243ee88e99e116d686e2117113

**Comment by LordHelmchen98** [comment]
What does your quest book say?

**Comment by MysteryDust** [comment]
https://gyazo.com/fe1ac0b12ade9e38a01fdea6c6a129fa
But I already did so..?

**Comment by MysteryDust** [comment]
I think I know what happend when I clicked on elio the server restarted and when I join a different world my rope was gone and I couldn't talk to elio anymore

**Comment by MysteryDust** [comment]
But the question is how do I fix that since I can't get another rope from daxe

**Comment by LordHelmchen98** [comment]
The command /fixquests should give you the rope back. Then talk to Elio once more.
Tell me if that worked out.

**Comment by MysteryDust** [comment]
Yes It did thank you
