### ISSUE TITLE
Character deleted?

### ISSUE THREAD

**Issue by LeOllie** [Wynncraft/Issues#7911]
Hello,

I logged onto the server after logging off a few hours ago and one of my characters were removed. I recently donated to VIP and it was one of the extra two characters that was removed.

LeOllie

**Comment by DebugMC** [comment]
This happend to me before long ago, but there is a no refund policy, sorry.

**Comment by LordHelmchen98** [comment]
Unfortunately you wont get the class back due to said no refund policy, but I hope its not too bad as you said it was one of the new classes.
