### ISSUE TITLE
Rank has not appeared 

### ISSUE THREAD

**Issue by thediamondkittie** [Wynncraft/Issues#7914]
Okay so i know your not meant to make a post but send an email if u are having issues with purchases not going through but its been almost 23 hours since i bought my rank and nothing  , its been 21 hours since i sent an email and nothing , can someone tell me if im doing it wrong like did i send the email to the wrong person or is there certain things you have to say in the email ? any help is welcome

**Comment by LordHelmchen98** [comment]
If you sent the mail to support@wynncraft.com including your transaction-ID everything should be fine. After all they are no robots but humans and it might take a bit until they get to your mail. All you have to do is to be patient.
