### ISSUE TITLE
Quest improvement / spawn point changes

### ISSUE THREAD

**Issue by EndOfLin** [Wynncraft/Issues#7915]
In the new quest called desperate metal i found myself respawning in Llevigar when i died inside the 'parkour' cave. It is just a minor thing although a fix to this spawn point would be nice.

There is also some issues with the usage of slime blocks, sometimes when you land on the edge of a slime block, it dosen't bounce you like it should, instead you take fall damage (which shouldn't be taken)

Thank you in advance :)

**Comment by Equipa2** [comment]
When die you respawn in the nearest city you have already been, so to fix that they need to change the places of the quests or chance the sistem.

About the slime blocks, that is an issues from the game not the server. You can try it in a normal world.

**Comment by LordHelmchen98** [comment]
In addition to the spawnpoint issue: as already said you respawn at the closest spawnpoint. Unfortunately that means that you respawn at seemingly weird respawnpoints due to that system.
