### ISSUE TITLE
Memory Paranoia Bug

### ISSUE THREAD

**Issue by CodyC99** [Wynncraft/Issues#7916]
On the Memory Paranoia Quest during one of the cutscenese the one were timmy shoots the fire ball the quest book does not update and when you look around your player keeps moving its head.

**Comment by LordHelmchen98** [comment]
I dont know what you mean by "your player keeps moving its head", but if your book didnt update you might have to redo the quest until you get to that point in the quest again.

**Comment by numbermaniac** [comment]
@LordHelmchen98 I think what he's referring to by "your player keeps moving its head" is, in the cutscenes, your player is fixed into a certain position, so if you try to turn sideways you keep getting turned back to face the scene.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
