### ISSUE TITLE
Back to Starting Area Glitch

### ISSUE THREAD

**Issue by Abnormals** [Wynncraft/Issues#7919]
I was trying to defeat the boss, Gregg'r, and I totally forgot to use my potions. I died and ended back up to the starting point (See screenshot below).
![2017-04-17_20 00 29](https://cloud.githubusercontent.com/assets/23349643/25110321/c1c4a6aa-23a8-11e7-8e00-fe30b38a2ded.png)
As you can tell I am level 46 with 13 soul points...in this picture I have 11...meaning I died and I'm not just trying to troll you guys.
I don't know if you guys can teleport my player back to the Llevigar Plains. If you can that would be very helpful. I hope I didn't waste your time because you certainly didn't waste mine.

**Comment by Pyromanical** [comment]
This is a very well known bug.  When you die off map, you get sent to the closest respawn point, either a town or the starting area.  You are just going to have to walk back.

**Comment by LordHelmchen98** [comment]
You should easily be able to get back by using the Seaskipper from Nemract to Llevigar.
