### ISSUE TITLE
Seasail merchant icon not on map

### ISSUE THREAD

**Issue by Broather** [Wynncraft/Issues#7923]
On the cords. 716 ; -3345 there's a seasail merchant in game but no icon on the map.

**Comment by Pyromanical** [comment]
It will probably be on the map when the map gets updated for Corkus, which is happening Soon™

**Comment by LordHelmchen98** [comment]
As Pyromanical already said the icon will probably be on the map when it gets updated now that Corkus is out. There a some things which have to get fixed first, but the map will get updated when they are fixed.
