### ISSUE TITLE
A Grave Mistake quest bug

### ISSUE THREAD

**Issue by McSeed** [Wynncraft/Issues#7924]
Me and custode99, get stuck at the end of the quest "A Grave Mistake" in a hole chamber near the end rute, just wen you have to pass the giant door.
We can't escape because the teleport scrolls don't work.

Need Help...

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by McSeed** [comment]
ok
