### ISSUE TITLE
Quest items not getting removed

### ISSUE THREAD

**Issue by SmirrenIsMyName** [Wynncraft/Issues#7925]
Even after I've completed all possible quests with this character. the quest items never got removed after I've finished the quest the item was needed for. I find this very annoying since it takes up space which is needed.
![2017-04-18_19 28 38](https://cloud.githubusercontent.com/assets/26552191/25144344/b3f8af38-246d-11e7-88a8-c2d31432dde8.png)
![2017-04-18_19 28 50](https://cloud.githubusercontent.com/assets/26552191/25144346/b3f9ab22-246d-11e7-8b72-609de55f7876.png)
![2017-04-18_19 28 52](https://cloud.githubusercontent.com/assets/26552191/25144347/b3fbcf06-246d-11e7-897a-f621d496fa6b.png)
![2017-04-18_19 28 53](https://cloud.githubusercontent.com/assets/26552191/25144345/b3f92ada-246d-11e7-990d-b503a5bee9ad.png)
![2017-04-18_19 28 54](https://cloud.githubusercontent.com/assets/26552191/25144343/b3f76df8-246d-11e7-8c92-abc87b190c8c.png)
![2017-04-18_19 28 55](https://cloud.githubusercontent.com/assets/26552191/25144348/b4151af6-246d-11e7-9aa0-2c629a88ab70.png)
![2017-04-18_19 28 56](https://cloud.githubusercontent.com/assets/26552191/25144350/b41a9558-246d-11e7-8fc7-ce705015e6bc.png)
![2017-04-18_19 32 01](https://cloud.githubusercontent.com/assets/26552191/25144349/b41880ce-246d-11e7-87ec-1678ae66e04e.png)

**Comment by SmirrenIsMyName** [comment]
This is currently the only loot I got on this character. My level 100 warrior. and I would be grateful to get them removed complete so the /fixquests does not bring them back

**Comment by LordHelmchen98** [comment]
They don't get removed because if you want to enter those areas again you need the helmets. Sorry, but there is no way to remove them from /fixquests.
