### ISSUE TITLE
Won't let me join onto Wynncraft

### ISSUE THREAD

**Issue by kashfi354** [Wynncraft/Issues#7926]
Current IGN: Mybeautfldedbody

So I was doing the quest "Out of my Mind" with my friend when it had glitched out. My friend was following the NPC Ariodo but my one was apparently stuck in a corner in his office. I relogged to reset it maybe but I ended up with this message.

http://imgur.com/gallery/MnJVx

I've relogged etc all the thingies but kept getting this message.

**Comment by LordHelmchen98** [comment]
I assume you are using the IP play.wynncraft.com. You can use the suffixes .net or .org instead. If that doesnt work you can try to switch between mc versions.
However if those two options dont work all you can do is wait. It fixes itself over time.
