### ISSUE TITLE
Great Bridge Statue missing Block(Showing Redstone Stuff)

### ISSUE THREAD

**Issue by lilWaynezz** [Wynncraft/Issues#7927]
Hello,
Me (Waynezz) and my Friend(Amko) spotted a litte hole at the left Foot (when standing in front of it) of one of the statues. You can easily jumpin and see the Commandblocks and Redstone Stuff. We first thought it wasnt a mistake but showing the Redstone stuff couldnt be a Mistake. I also added some Pictures so that you can see where it is

![2017-04-19_00 53 15](https://cloud.githubusercontent.com/assets/27745852/25156503/3abb0732-249b-11e7-960e-8609b278f560.png)
![2017-04-19_00 53 24](https://cloud.githubusercontent.com/assets/27745852/25156504/3abbeed6-249b-11e7-99ff-ad16483713d4.png)
![2017-04-19_00 53 40](https://cloud.githubusercontent.com/assets/27745852/25156505/3abc202c-249b-11e7-8e8a-4272be73af6a.png)
![2017-04-19_00 58 32](https://cloud.githubusercontent.com/assets/27745852/25156519/5544c016-249b-11e7-97d8-1c923de187e2.png)

**Comment by ColinRioux** [comment]
Fixed!
