### ISSUE TITLE
Gear Skins not loading in

### ISSUE THREAD

**Issue by 1Glock1School** [Wynncraft/Issues#7933]
Hi, I've recently bought a rank (vip) and about 30 crates. I got some gear skins within opening them. Whenever I add them to my weapon, the just appear a black and purple not loaded texture box. Is their a way to fix this? I've tried different texture packs including the starter one. Thanks

- 1Glock1School

**Comment by thecoolkogut4** [comment]
join the serve ron mc version 1.9 and up to see the skins

**Comment by LordHelmchen98** [comment]
The weapon skins are based on the feature that changes tool skins depending on their durability. That feature got added in 1.9 and therefore 1.8 cant handle the gear skins on Wynncraft. As already said you have to use 1.9+ to see the skins.
