### ISSUE TITLE
Cannot see guild chat (haven't changed my username!)

### ISSUE THREAD

**Issue by enderbiscuit** [Wynncraft/Issues#7934]
I was talking in guild chat when, suddenly, the game stopped displaying any new messages I sent. I tried switching worlds, I tried relogging entirely, and then I tried rebooting Minecraft. None of that worked. The game refuses to let me see ANY guild chat now. What the hell am I supposed to do?

**Comment by thecoolkogut4** [comment]
every so often, a world stops recieving guild chat.  but as you said you switched servers and it still happening so its not this problem. the other problem that happens every so often is that guild on every server stops working, once this happens it normaly gets auto fixed within a few hours. (and sometimes messages & shouts break with it)

**Comment by enderbiscuit** [comment]
Ok thanks, at least I can find a little comfort now.

**Comment by LordHelmchen98** [comment]
@enderbiscuit As already said this happens every now and then, but it is known now and should be fixed soon.
