### ISSUE TITLE
Too less Skill Points after resetting!

### ISSUE THREAD

**Issue by Scrizzel** [Wynncraft/Issues#7935]
Hello i really need help,
I've resetted my hole skill points with a skill point resetting scroll and I have too less.
I can't wear my hole armor know. Then I resetted it with Soul points and I still have too less skill points.
I am level 58 and have 118 skill points before I had much more maybe it was a bug but I dont think so!

Please help me!

**Comment by thecoolkogut4** [comment]
maybe your armour/accessories  has -2 sp on it?  when you take your armour and accessories off are you still missing two?

**Comment by LordHelmchen98** [comment]
With level 58 you should be able to spend 114 skill points (you cant spend skill points at level 1 and then its 2 per level so 57*2=114). You can only get more skill points by armor stats.
