### ISSUE TITLE
Spawn problem

### ISSUE THREAD

**Issue by AbugRed** [Wynncraft/Issues#7936]
When I go back to the hub/lobby /whatever it's called, I get spawned in a funny spot and keep getting kicked for flying. It stops with a relog, but I thought I might point it out for you.

**Comment by lilWaynezz** [comment]
I had the same problem but only on the 1.9. If youre not using 1.10 then try it for me it worked :)

**Comment by Pyromanical** [comment]
This is well known to the staff.  When you log in, you get spawned in slightly above the ground.  If you lag a bunch when you join the hub, you are stuck in the spot above the ground for long enough to get kicked for flying.
