### ISSUE TITLE
Live map not working

### ISSUE THREAD

**Issue by FreddyFish** [Wynncraft/Issues#7938]
Live map is not working, i can't see myself on the map. Right not im in Almuj, but my head is not showing as it did a few days ago.

https://gyazo.com/ab82af735972e80460e620f3123823af

**Comment by LordHelmchen98** [comment]
Apparently its broken right now. That means you have to use good ol' coords ;)
Anyway this will most likely be fixed soon.

**Comment by FreddyFish** [comment]
I'm not sure why this is closed, because it's still an issue.

**Comment by numbermaniac** [comment]
Because it's a known bug, so the developers are aware and are working on fixing it.
