### ISSUE TITLE
Meaningful Holiday Quest

### ISSUE THREAD

**Issue by Ender9090** [Wynncraft/Issues#7940]
So basically the Meaningful Holiday quest is broken for me.
I have talked to Reshad, but it hasn't updated the book leaving me stuck.
![2017-04-20_16 08 45](https://cloud.githubusercontent.com/assets/27829677/25251613/0145758e-25e8-11e7-9118-c24b32a9b1e1.png)
After seeing this I tried going back to Nick, but...
![2017-04-20_16 09 52](https://cloud.githubusercontent.com/assets/27829677/25251655/1ce684fe-25e8-11e7-9897-a7b21d444b4c.png)
Thanks for any help in advance,
-Ender_Man9090

**Comment by LordHelmchen98** [comment]
Have you checked if `/fixquests` gives you anything related to Meaningful Holiday?

Also entity radars are not allowed in Wynncraft. Please turn them off.

**Comment by Pyromanical** [comment]
Try going back through the tunnel again, and talking to Reshad.

**Comment by Ender9090** [comment]
@LordHelmchen98 The entity radar is turned off, I just use it for waypoints. And yes I have tried using /fixquests
@Pyromanical I did sadly, nothing happened.

**Comment by meowtheboss** [comment]
this happened to me earlier when i was doing the same quest.  Go back to reshad, click on him, and nick will be walking up to you from the path

**Comment by Ender9090** [comment]
@meowtheboss Just did without any luck, if Nick walking up to me is supposed to be the next event it isn't happening. Thanks though.

**Comment by RubbrDucky** [comment]
Waypoint maps are legal @LordHelmchen98 thats not a entity radar

**Comment by thecoolkogut4** [comment]
@RubbrDucky i believe he is reffering to the second screenshot with the white dots representing entities. the white dots are entities because #1 in the first screenshots its in the dead center representing the player, and in the second shot, there is one in the center representing the player, and various other ones scattered around representing entities. *i believe so*

@Ender9090 the part where he walks to you is a little tricky, you have to click him fron various different angles to trigger his text.

**Comment by LordHelmchen98** [comment]
Thanks @thekoolkogut4. 
@RubbrDucky @Ender9090 I might have to update my knowledge of minimaps but I'm pretty sure those white dots are NPCs.

Unfortunately I don't know any other solution for Reshad though.

**Comment by Ender9090** [comment]
@LordHelmchen98 "Players" rather, sorry for forgetting about that I guess.
![2017-04-21_14 28 00](https://cloud.githubusercontent.com/assets/27829677/25291177/fab37b32-269e-11e7-9ddf-981fabd18148.png)
_AMAZING!!!!_
And so basically this quest is completely broken for me RIP.
