### ISSUE TITLE
Wrath of the Mummy Quest

### ISSUE THREAD

**Issue by meowtheboss** [Wynncraft/Issues#7942]
I'm trying to do the Wrath of the Mummy quest, but I can't enter the code in the door.  Every time i press a button, a message appears saying, "You don't have permission for this area."  Any idea on how to fix this, or a way i can enter?

**Comment by Pyromanical** [comment]
It is because the item you were using is a retextured half-slab, and the game thinks you were trying to place it, so it says you don't have permission to. To fix this right click with a empty hand or your soul point.
