### ISSUE TITLE
Skill points changing

### ISSUE THREAD

**Issue by Altered4Ego** [Wynncraft/Issues#7943]
So as of starting wynncraft I always put the same number of points into every skill. Keeping them even, so I've noticed and its gotten bad now, that they change. I I think 13 or so in each then now I have 23 in one and 3 in another. The really big problem is that I need 8 Agility to use my weapon, I only have 3. Anyone else having this issue

**Comment by numbermaniac** [comment]
Have you got weapons or armour that have skill point changes on them? That would be changing the number of points you have in each skill.

**Comment by Altered4Ego** [comment]
Well yes but I have had the same things since lvl 19 and they still go around. So its not any items

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
