### ISSUE TITLE
Breathing Helmet I Hotdam

### ISSUE THREAD

**Issue by yomanwatup** [Wynncraft/Issues#7944]
I use ./fixquests want to get back this ( ^  ) item ,but really nothin happened,dam,soo i stuck the UndericeA,help me for W33D #help#w33d#breathing helmet I#dam#pls#420#quickscoped./fixquests#bad english;(.pls halp. :D

**Comment by LordHelmchen98** [comment]
Do you need to start or continue the quest?

**Comment by yomanwatup** [comment]
i finished the quest

**Comment by LordHelmchen98** [comment]
So this has been resolved?

**Comment by Pyromanical** [comment]
If you've completed Underwater, and /fixquests doesn't work, then the helmet is somewhere in your bank or on a class.

**Comment by yomanwatup** [comment]
solved,thanks!:D W33D GuyS!!!!4snoopdog!
