### ISSUE TITLE
Didn't get Loot from Tribal Sanctuary

### ISSUE THREAD

**Issue by zoggi2000** [Wynncraft/Issues#7945]
Like the title says, the loot didnt appear after we defeated the tribal sanctuary boss. Mr_pyro_96 and me, zoggi2000 didnt get anything

**Comment by thecoolkogut4** [comment]
were you inventorys full? did no emeralds fall around you guys?

**Comment by zoggi2000** [comment]
no, nothing. we even stayed in the boss room and killed the other mobs. But even after that nothing dropped. Inventory was not full and no falling emeralds

**Comment by zoggi2000** [comment]
Okay now loot dropped, but i am still missing the 3 beads from the first fight
