### ISSUE TITLE
Messarock Arch is just a Dark Prismarine Block

### ISSUE THREAD

**Issue by 9DG** [Wynncraft/Issues#7946]
The Messarock Arch Legendary Bow is literally just Dark Prismarine Block, I don't know if this is a bug but i assume it is.
![bug](https://cloud.githubusercontent.com/assets/27873486/25299555/50034cc8-26ce-11e7-8b59-d60eb8f004c7.PNG)

**Comment by ColinRioux** [comment]
Yes, weapons are retextured blocks, but sometimes, there aren't textures for them. They still work, and will hopefully be fixed soon.
