### ISSUE TITLE
Can't Pickup Item for Quest!

### ISSUE THREAD

**Issue by smegbelock** [Wynncraft/Issues#7948]
Hi, so I was doing a quest and I got bugged and I teleported elsewhere with an item I needed to pick up. I couldn't pick it up, therefore I couldn't continue with the quest. Please help!

**Comment by RubbrDucky** [comment]
Which quest? be specific please!

**Comment by thecoolkogut4** [comment]
what happens if you try to hit/kill the item as if it was a mob? when you're looking at the item, left click it as you are trying to kill it. does this work? also as rubbrducky said, what quest and what item is it?

**Comment by numbermaniac** [comment]
You need to kill the creeper skin to pick it up. Since it sounds like you did, just run up to the tunnel again and that will drop you onto the tree, so you can try picking up the skin again.

**Comment by LordHelmchen98** [comment]
@smegbelock were you able to fix it?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
