### ISSUE TITLE
Quest: The Realm of Light

### ISSUE THREAD

**Issue by Gredolas** [Wynncraft/Issues#7950]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

When you follow the purple path to the cave which you can only enter with the Helmet of Shimering light and you enter the cave and then unequipp the helmet and equipp it again u get teleportet to the start of wynncrat (aka the tutorial)!

**Comment by ColinRioux** [comment]
Very well known. It's bec realm of light is located closest to tutorial area.
