### ISSUE TITLE
On Join spawning on wierd positions

### ISSUE THREAD

**Issue by lilWaynezz** [Wynncraft/Issues#7953]
So recently I got the Problem that when I join on any Server im often Spawning on top of the Map Border or on Top of any Building or in any Block. Now I spawned on top of Spieder Dungeon and I can run anywhere in this map. I dont know if im the only one who has this issue but its really frustrating

**Comment by thecoolkogut4** [comment]
next time you log out, make sure you have one block above you that is free. so you can jump up and down with nothing stopping you. If you make sure there is a gap above you, then you should be spawning in normally.
