### ISSUE TITLE
Buying a rank

### ISSUE THREAD

**Issue by C-r-i-m** [Wynncraft/Issues#7958]
I bought the VIP+ Rank and I didnt get the promotion of 2 free XP bombs, 2 free Item bombs and 5 free crates

**Comment by Pyromanical** [comment]
Did you upgrade to VIP+ or did you buy a rank for a first time?

**Comment by C-r-i-m** [comment]
I upgraded

**Comment by C-r-i-m** [comment]
Even I I upgrade it shouldnt matter because it says Quote: Value of $10 for FREE with the purchase of any rank! I Purchased the VIP+ rank, I didnt have it before, I paid money, and I have it now, thats purchasing the rank

**Comment by ColinRioux** [comment]
Please email support@wynncraft.com with your receipt/proof of purchase. This is for in-game issues, not money related issues.
