### ISSUE TITLE
Gavel Territories incorrectly named

### ISSUE THREAD

**Issue by SpringVibes** [Wynncraft/Issues#7961]
http://prntscr.com/ezs5x1

They should be Orc, not Gert. I think this is a mistake, anyway.

**Comment by thecoolkogut4** [comment]
I belive @SaltedSalmon deals with guild territories and can fix this.

**Comment by Villageacules** [comment]
This was done for a reason.

**Comment by thecoolkogut4** [comment]
This was actually fixed when corkus territories came out
