### ISSUE TITLE
Ice Nations - Quest Book Incorrect Info

### ISSUE THREAD

**Issue by WulfGamesYT** [Wynncraft/Issues#7963]
In the Quest Book, the quest Ice Nations has the info:
![Image](https://i.gyazo.com/c7a32b03a0d1fba09c448cd88e57f056.png)

But on the map on the website, its called Ice Islands...
Just simply correct that typo from Icy to Ice 👍 
![Image](https://i.gyazo.com/8b310eb70671113372a6d3d885f392ca.png)

**Comment by ColinRioux** [comment]
Fixed!
