### ISSUE TITLE
Texture Pack

### ISSUE THREAD

**Issue by wolfdragon1000** [Wynncraft/Issues#7964]
I was playing on wynncraft and when I left the texture pack didn't go away and so now when i try to get on any server the wynncraft texture pack won't go away. I have looked in the texture pack folder and nothing is there from wynncraft. Please help as soon as possible!

**Comment by LordHelmchen98** [comment]
That may seem like a dumb question, but did you close and restart MC?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
