### ISSUE TITLE
i am stuck and cant play now

### ISSUE THREAD

**Issue by TheFirstHarambe** [Wynncraft/Issues#7965]
i got stuck in a doungen inside of a wall. i dont know how i got stuck but i would love it if a mod could tp me out of there or something like that. at the moment i cant play because i am stuck inside tower/wall

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by TheFirstHarambe** [comment]
thank you
