### ISSUE TITLE
quest: Dwelling Walls

### ISSUE THREAD

**Issue by Femke05** [Wynncraft/Issues#7966]
i have enterd the house and completed the puzzle and my questbook says that i shoul talk to leucsaa, but when i do that he says to go back an find the book.

![wyn](https://cloud.githubusercontent.com/assets/27956958/25336562/609abca2-28f8-11e7-9133-0a0003a88d71.png)

**Comment by lilWaynezz** [comment]
When you completed the puzzle did you also get the Journal ?

**Comment by Femke05** [comment]
No i never had the journal

**Comment by LordHelmchen98** [comment]
If you go through the mansion correctly (first button twice, second one once) you should get to a hole in the bottom that leads to the exit. At the bottom of that hole you can find a "mob" that drops the journal if you hit it. If you have that with you, you should be able to finish the quest.

**Comment by LordHelmchen98** [comment]
@Femke05 were you able to get the Journal?

**Comment by Femke05** [comment]
Got it

**Comment by Femke05** [comment]
Thanks
