### ISSUE TITLE
Stuck.

### ISSUE THREAD

**Issue by georg420** [Wynncraft/Issues#7967]
I just turned lvl 83 and started The Envoy part I. Everything was ok until it was 1 min until it had to restart(the server) I was in the part with the vents and are stuck. I have Corkus and Cinfras Scrolls but they dont work. I am stuck inside a block. If anyone could teleport me out or anything that would be perfect! 

~Georg420

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!
