### ISSUE TITLE
Missing Cosmic armor chestplate

### ISSUE THREAD

**Issue by InvinciBOOM** [Wynncraft/Issues#7969]
So, i was just switching armor sets, taking off my Cosmic set, thena few minutes later, I realized my cosmic chestplate was missing. I'm attaching a picture of my inv/bank to show its not there. I promise its not on the ground anywhere. This is a bug from equiping and removing armor, so I am unsure if this is going to get a response.
![2017-04-24_19 19 45](https://cloud.githubusercontent.com/assets/12708191/25366244/4532bb42-2923-11e7-815c-93e88d84e569.png)
![2017-04-24_19 20 01](https://cloud.githubusercontent.com/assets/12708191/25366245/45492f62-2923-11e7-8402-8e2dc843e61b.png)

**Comment by thecoolkogut4** [comment]
You haven't asked for a refund, but I'd like to let you know that the server has a strict no refund policy so it won't be possible for you to get the chestplate back. Maybe next time you change your armour, double check to make sure its in your   inventory as we all make mistakes.

**Comment by InvinciBOOM** [comment]
I guess I will have to get another class to level 80.
