### ISSUE TITLE
Skills in compass not Showing

### ISSUE THREAD

**Issue by CaptainJLPv2** [Wynncraft/Issues#7971]
This is a bug that is caused when having too many skill points in a specific skill. ( It should say 148 intelligence but it doesn't pop up ). Please fix this bug. 

Image of the bug.
https://cloud.githubusercontent.com/assets/28000844/25380289/1bc0c8c8-29f3-11e7-9d84-f83ce8fb30bb.png

**Comment by thecoolkogut4** [comment]
Duplicate #4438
