### ISSUE TITLE
I am somehow stuck

### ISSUE THREAD

**Issue by LeftWardzero** [Wynncraft/Issues#7972]
To any Mod
Here is my story of how I got trapped
I was walking from the Ancient Nemract and came across a house, so I went in it and sleep in on of them. When I got out of the bed I somehow tp'd into 1 by 2 area and there is now why out. If any person who can help sees this, can you contact my to somehow get me out.

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!
