### ISSUE TITLE
Seluc Despawning in "The Canyon Guides" Quest

### ISSUE THREAD

**Issue by PixelyFoxxy** [Wynncraft/Issues#7973]
I was almost done with the quest, I was near the Bantisu and the NPC "Seluc" didn't follow me and despawned.

**Comment by thecoolkogut4** [comment]
Next time you do the quest, stay close to Seluc and make sure its following you. Walk slow and make sure it's on your tail. (If your more then a chunk or two away from it, then it despawns *If nobody else is near it*)

**Comment by Pyromanical** [comment]
On top of what @thecoolkogut4 said, if he just stops walking, punch him, that will usually get him to start following you again.
