### ISSUE TITLE
Ban bug

### ISSUE THREAD

**Issue by AnasPlazeGameZ** [Wynncraft/Issues#7976]
Ive recently been banned and because of my temper i started smashing the reconnect button in 10 time si could join the lobby is this a bug or do i have an extreme temper?

**Comment by ColinRioux** [comment]
Please make a ban appeal on the forums, not here.

**Comment by LordHelmchen98** [comment]
In addition: Yes it's a bug. Sometimes you can join the lobby, but you can't join servers.
