### ISSUE TITLE
STUCK on the boat from nemract to selchar!!

### ISSUE THREAD

**Issue by AbugRed** [Wynncraft/Issues#7979]
I was on my way to Selchar to go do a quest. In nemract, I bought a ticket and departed on my journey, however, something went wrong on the boat... The seaskipper captain wasn't talking like he usually does, there was a tripwire instead of the bell button, and no matter what I do, there is no way out. Ive tried relogging, tripping the wire, everything. Nothing is working and I am stuck somewhere on a boat that is not letting me off. Its been 20 minutes. I need help, I cant escape. I have no tp scrolls, I cant kill myself, nothing is working :( This is with my good character too.

**Comment by AbugRed** [comment]
Nevermind. Switching servers did the trick. Still an issue though

**Comment by LordHelmchen98** [comment]
In case this happens again and server switching doesnt help you can do `/kill` to get out.
