### ISSUE TITLE
Flower pots give vanilla flowers.

### ISSUE THREAD

**Issue by Hodsonius** [Wynncraft/Issues#7983]
As of Minecraft 1.11, flowers can be taken out of pots by right-clicking. Doing this on Wynncraft works and gives a vanilla flower. This works even without an empty hand. Accidentally discovered this and reported it as it could be used to easily obtain banned items.

**Comment by ThunderRemix** [comment]
These items are nothing more than ghosts. They disappear when interacted with, so this isn't an issue. /desolc

**Comment by LordHelmchen98** [comment]
As they disappear as soon as you click them its not gamebreaking at all so I dont think this is a problem.
