### ISSUE TITLE
im stuck need help 

### ISSUE THREAD

**Issue by bigfry666** [Wynncraft/Issues#7985]
hey im trying to do first dungeon the lvl 9 one but im stuck there is an invisible wall in the tunnels after ive put 18 tokens in the hopper but i cant carry on nor can i go back due to its closed behind me this there an unstuck command so i can get out of there ?

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by bigfry666** [comment]
okay thank you so much i tryed /help but nothing comes up
