### ISSUE TITLE
Wtf, why does this always happen?

### ISSUE THREAD

**Issue by liual1** [Wynncraft/Issues#7987]
![skarmavbild 2017-04-27 kl 9 40 47 fm](https://cloud.githubusercontent.com/assets/17669282/25472935/a6fc1948-2b2d-11e7-8b06-b25de1133eab.png)
When i die from ToA i almost always spawn under the world in lusuco...?

**Comment by thecoolkogut4** [comment]
What happens when you die and are in MC version 1.8-1.8.9?

**Comment by liual1** [comment]
@thecoolkogut4 ??? please rephrase your question? i use minecraft 1.10 ??

**Comment by thecoolkogut4** [comment]
Join the server on mc version 1.8.9. Once your on the server play normally intill you die, Once You die do you still spawn underground?

**Comment by liual1** [comment]
I tried what you said, and i did indeed spawn above ground, although it could just be a one time thing

**Comment by ColinRioux** [comment]
Wynncraft is hardcoded to 1.8.9, so best to use 1.8.9 if you can't stand some of the issues imposed by different minecraft versions which aren't meant to be backwards compatible. Also, based on your picture, you are using 1.11.2, which in my opinion, is rather unstable when playing Wynncraft. Most major servers are hard coded to 1.8.9, and 1.9.2/1.9.4 are generally stable so I suggest using those if you don't like 1.8.9.
