### ISSUE TITLE
Creeper Infaltration

### ISSUE THREAD

**Issue by JustAGamerO2016** [Wynncraft/Issues#7988]
Hey Wynncraft players and maybe owners

today i realised there is a problem with the mision Creeper Infaltration 
problem: the portal on step 2 where you are suposed to be teleported to the top of the ravinary dus not work

i realy want this to be fixed becuse im a player thad rlly want to get a 100% in my quest book

Greatings ProMiner_2013

**Comment by vChase42** [comment]
This is also happening to me, and I also saw it happen to someone else who was doing the same quest.

**Comment by PyroPrav** [comment]
Same thing happening to me.
When i walk into the portal, I can hear the pressure plates going off from standing on them, just no teleportation.

**Comment by PepinhoJp** [comment]
This is a bug, the staff already know about it, this will probably be fixed today!

**Comment by LordHelmchen98** [comment]
This was fixed and should work again now.
