### ISSUE TITLE
Quest Item Loss Glitch (The Shadow of the Beast)

### ISSUE THREAD

**Issue by Jiro888** [Wynncraft/Issues#7990]
Ok, so, admittedly, this happened mostly because of my own idiocy, so please bear with me for a few seconds.

So, the main problem I have surrounds the quest, "The Shadow of the Beast". This quest needs you to collect 3 quest items. The thing is, I accidentally lost one of the items: the beast's stringy hair. I had dropped it inside a naga den, trying to clear some inventory space, because I had thought it was simply string. By the time the notification stating that the item I was trying to drop was a quest item had popped up, I had replaced its place in my inventory, and had lost it.

Initially, I had thought it was just a bug, and that it would show up after a while. Maybe it was just lag. I waited around 5-ish minutes and still nothing happened. I then thought maybe I had to relog. Still nothing. 

Currently, I'm a bit afraid that I won't be able to complete the quest, and I'd like to ask if I could be able to get another piece of stringy hair so that I could finish it. I understand, though, if it won't be replaced because of my own negligence. Thank you kindly!

v(ovo)/

**Comment by thecoolkogut4** [comment]
Try to do /fixquests to get the item back.
