### ISSUE TITLE
making a new class

### ISSUE THREAD

**Issue by oscarHUN** [Wynncraft/Issues#7991]
when i try to start a new class its drops me to a room. there are signs with "wondering what happened?" "you died yo" "use /warp rangi"(this command doesnt work btw) .... what can i do ? i can show screenshots if u want but i quess that enough to tell me the way of solvation

**Comment by thecoolkogut4** [comment]
Did you relog/try to switch servers?

**Comment by TheSuperCheese** [comment]
nah still same problem

**Comment by spookykids** [comment]
ugh same problem here. Its happening to every newbie and new characters

**Comment by oscarHUN** [comment]
yeah /kill doesnt work and yeah

**Comment by Pyromanical** [comment]
Could one of you show screenshots of the room you're in

**Comment by oscarHUN** [comment]
http://prnt.sc/f1i2qb theres one. if u need more just tell me i have more

**Comment by PepinhoJp** [comment]
Mods already know about this bug, just wait a little bit, this will probably be fixed today!

**Comment by LordHelmchen98** [comment]
This got fixed so it should work now.

**Comment by oscarHUN** [comment]
Yeah i spawn in a obsidian room with two buttons and i can kill myslef
