### ISSUE TITLE
Stuck in a room near Ragni

### ISSUE THREAD

**Issue by FinnAminiKacke** [Wynncraft/Issues#7992]
I spawned in a lobby with signs saying "yo, you died use /warp ragni" but /warp ragni is an invalid command. please help

**Comment by thecoolkogut4** [comment]
Lobby as in the hub? What happens when you log out and log back in? Can you use the compass in your inventory to join a world?

**Comment by PepinhoJp** [comment]
This is a bug, mods already know, will probably be fixed today!

**Comment by ColinRioux** [comment]
Duplicate of #7991
