### ISSUE TITLE
Some issuses with Reshad in the quest called: Meaningful Holiday

### ISSUE THREAD

**Issue by ItZYaBoyLilZ** [Wynncraft/Issues#7993]
My friend and I had some issues with right clicking Reshad.
We finally could speak to him but he doesn't say what he is supposed to say.
he is saying: Welcome to my farm i'm currently preparing a large harvest for a big feast in detlas soon.
but he has to say: Welcome to my farm Looking to buy some of my fresh crops

We really want to finish this quest so can someone help?
thanks

**Comment by thecoolkogut4** [comment]
It's very hard to click him. Walk in circles around him clicking. Shift and click, jump and click, try to click him from various angles.

**Comment by PepinhoJp** [comment]
This bug isnt really rare now, did the cutscene start and stooped on his 4th text?

**Comment by XavierEXE** [comment]
What does your quest book say?

**Comment by Eiyaa** [comment]
I tried going back and talking to Nick and then Margaret, somehow it worked.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
