### ISSUE TITLE
Quest '' Out Of My Mind''

### ISSUE THREAD

**Issue by VenoxQtr** [Wynncraft/Issues#7995]
I have went to the undergrowth door, and then it told me to go another way in, but according to the cords I did not find any door, except the one behind the waterfall, I went in there, and went to one of the door and it won't let me go in there, I went back to the undergrowth and change servers, and still won't work. Any solution?? :/

Here is a video:
https://www.youtube.com/watch?v=QS8DCmrJtnk

**Comment by PepinhoJp** [comment]
Teleporters apparently are bugged and the spawn too, there are many bugh reports about this, just wait, these bugs will probably be fixed today!

**Comment by LordHelmchen98** [comment]
This got fixed and should work again now.
