### ISSUE TITLE
corrupted infested pit softlock

### ISSUE THREAD

**Issue by BrianMcFluffy** [Wynncraft/Issues#7996]
So, I was going through the new corrupted dungeons, and I got stuck after the parkour part. When I meet the dying adventurer, he gives me his final warning before dying and turning against me, and he tries to attack me, but the invisible wall doesn't despawn, meaning that he can't attack me, and that I can't continue on my quest, and the only way to get out is to kill myself, which doesn't help.

I've tried switching characters back and forth, leaving to the hub and coming back, disconnecting and reconnecting, closing minecraft and coming back, and turning on and off my computer, but none of those worked. The only thing I managed to do was spawn multiple copies of him...

![2017-04-27_18 40 56](https://cloud.githubusercontent.com/assets/17452007/25495001/eac36a5c-2b7b-11e7-9bb7-077f0cbb8456.png)

![2017-04-27_18 41 14](https://cloud.githubusercontent.com/assets/17452007/25495019/fd7a3dba-2b7b-11e7-8e91-1faadfc01e22.png)

![2017-04-27_18 49 37](https://cloud.githubusercontent.com/assets/17452007/25495084/43156b88-2b7c-11e7-8d1d-63ca21c8f2f7.png)

**Comment by PepinhoJp** [comment]
Why can't you use /kill, unfortunately it's the only way...

**Comment by Celsonic** [comment]
@PepinhoJp You can also switch servers.

**Comment by BrianMcFluffy** [comment]
@PepinhoJp No,no the problem isn't really leaving the dungeon, it's that I can't complete it, I know that I can commit seppuku but I at least wanted to see if anyone had a solution. Edit : Huzzah! I managed to run past the invisible walls (wich were three in number... Wow) by just rushing through... Still feel kinda cheaty but hey, it worked I guess...
