### ISSUE TITLE
Stuck in Mixed feelings

### ISSUE THREAD

**Issue by Stormyeriki** [Wynncraft/Issues#7997]
Stuck in Mixed feelings, the tavern owner wont talk to me...

**Comment by PepinhoJp** [comment]
The cutscene doesn't work?

**Comment by Stormyeriki** [comment]
Exactly

**Comment by Stormyeriki** [comment]
It doesnt show

**Comment by Stormyeriki** [comment]
PLz help

**Comment by PepinhoJp** [comment]
Try switching servers, If it doesn't work you'll have to use /kill and do things again!

**Comment by Stormyeriki** [comment]
Alright, imma do that

brb

**Comment by Stormyeriki** [comment]
K it worked after to suicides
Ty!

**Comment by PepinhoJp** [comment]
:D

**Comment by Stormyeriki** [comment]
Oh dang

**Comment by Stormyeriki** [comment]
now i got stuck in mid of cutscene: im invis, cant move, but no one shows up

**Comment by Stormyeriki** [comment]
Halp ;_;

**Comment by Stormyeriki** [comment]
hello?

**Comment by Stormyeriki** [comment]
wth well it fixed itself somehow
ill close this then lol
