### ISSUE TITLE
Climbing Helmet

### ISSUE THREAD

**Issue by TurtleGames101** [Wynncraft/Issues#7999]
Hi, I'm doing the quest Zhight Island and need to go into maro peaks in order to speak to Czytash.
Which requires the Climbing Helmet from the quest Ice Nations, I have checked all my classes and bank but I don't have the Climbing Helmet even though I have completed the quest.

My username is TurtleGames101

![capture](https://cloud.githubusercontent.com/assets/28115418/25501313/358b96b4-2b8a-11e7-80f4-a62aef68d79c.PNG)

**Comment by thecoolkogut4** [comment]
Type /fixquests to get the helmet back
