### ISSUE TITLE
Problem?

### ISSUE THREAD

**Issue by Yvngmadi** [Wynncraft/Issues#8000]
Players said I was invisible and my skin when I pressed F5 or E it was a steve skin.. Help? 💯

**Comment by Yvngmadi** [comment]
I also, relogged 10 times and logged out all the way 5 times :/

**Comment by thecoolkogut4** [comment]
Take your helmet off, then put it back on

**Comment by RubbrDucky** [comment]
confirmed it works (helmet off then on)
