### ISSUE TITLE
Creeper Infiltration

### ISSUE THREAD

**Issue by bob10234** [Wynncraft/Issues#8001]
It seems that, with the redesign of Creeper Infiltration one can not enter the cave with the old mask. Meaning I can not finish Temple of legends as I have to talk to Gaul inside the cave.

**Comment by RubbrDucky** [comment]
Redo the new quest, then!

**Comment by LordHelmchen98** [comment]
Its not a very long quest and if you are doing ToL your level should be high enough to easily do it.
So as already said you have to do the revamped quest in order to continue ToL.
