### ISSUE TITLE
Please fix the guild glitch

### ISSUE THREAD

**Issue by jiggling** [Wynncraft/Issues#8005]
We've been dealing with the guild glitch for quite awhile and updates upon updates upon updates have been coming out but none of them have even mentioned fixing the guild glitch :/ ive been wanting to play with friends but im stuck in a dead guild. and the owner refuses to disband so im screwed until the 5 years pass by when the guild glitch is fixed

**Comment by PepinhoJp** [comment]
You'll have to wait, sorry, it's boring but we can't do anything, guilds will have an update only for them, this issue is already known for months!

**Comment by LordHelmchen98** [comment]
Its planned but not sure when it will be finished. Sorry, but you will have to be patient.
