### ISSUE TITLE
Permissions Glitch

### ISSUE THREAD

**Issue by AkiTatsuo** [Wynncraft/Issues#8006]
Hey I've noticed from time to time when I play in Wynncraft that I'll lose permissions entirely, I have noticed I can still fight, gain loot (be it from mobs), and play normally, but it refrains me from opening doors, pressing buttons and opening chests, locking me out of areas and blocking me from getting loot from chests, its has on 5 different occasions locked me out of a T4 chest. *Edit I've isolated what causes this issue and it seems to be my staff (Detlas' Legacy Buff by T3 Water and Air powders) causing this issue, for now I've resorted to not opening things with my staff but it is an issue to be fixed. I wish I could fix it myself, but its something on your end.

![2017-04-29_00 34 49](https://cloud.githubusercontent.com/assets/28180497/25553563/d36f1fec-2c73-11e7-8a2e-619ca59a54c1.png)
Abandoned Mines, Near Nivla Forest

![2017-04-29_00 46 29](https://cloud.githubusercontent.com/assets/28180497/25553631/81c6df02-2c75-11e7-97c2-8ba068a73850.png)
Outside Eastern Gate of Detlas

~Veteran Minecrafter Aki Tatsuo

**Comment by LordHelmchen98** [comment]
This happens because your wand is a retextured half slab. For some reason the server thinks you want to place which isnt allowed. Theres no way to fix that.
If you want to interact with chests, doors, etc. just use another item (e.g. soul points) or your bare hands.
