### ISSUE TITLE
Green Gloop (Slime won't drop from Slimes)

### ISSUE THREAD

**Issue by CloudyBogdan** [Wynncraft/Issues#8007]
Hey Wynncrafters! I've got a bit of an issue. I am not able to obtain any slime from the slimes in the Slime cave. It just WON'T drop. The guy who wants 8 slime is asking me for it. How do I obtain it? I do have the slime scoop.

**Comment by PepinhoJp** [comment]
Go to the end of the cave, only the slime there drop the slimeballs!

**Comment by CloudyBogdan** [comment]
Ok thanks. My bad. It worked
