### ISSUE TITLE
Spelling issue first time talking to Ooni for "Prison Story"

### ISSUE THREAD

**Issue by lilman1423** [Wynncraft/Issues#8011]
He has a line of text (3/7) the first time you talk to him that says "Listen, I've been captured a few days ago..."

![ooni](https://cloud.githubusercontent.com/assets/1341017/25556634/b8e030a8-2cb4-11e7-83dd-0a53f9725335.png)

Grammatically it should be "Listen, I was captured a few days ago".

If the misspelling is part of his character then that's fine. I just thought I would let you know incase it wasn't intentional.

**Comment by ColinRioux** [comment]
Fixed
