### ISSUE TITLE
Crashed and Lost Quest Item

### ISSUE THREAD

**Issue by Jodj** [Wynncraft/Issues#8012]
I was just about to hand in a quest item to Ferndor ( Quest is Lost Soles ) when I suddenly crashed. Now when I crashed that had nothing to do with the server it was just my laptop, but when I came back, my quest item was gone.

Before I crashed I handed in my quest item, which was the legendary boots thing. After 5 seconds I crashed. I came back on and the quest item was gone.

**Comment by thecoolkogut4** [comment]
Type /fixquests to get the item back
