### ISSUE TITLE
Skeleton Horse Not Spawning Glitch

### ISSUE THREAD

**Issue by Spicyice101** [Wynncraft/Issues#8014]
I have a tier 2 black horse and have the skeletal horse cloak on, but two out of every three times it spawns a regular black horse instead of a skeleton one spawns. Its not as if it is never spawning, i just have to summon it two or three times to get the skeleton horse. This is not a one time thing, i have rejoined multiple times and this has been happening for days. I was wondering if someone knew what the issue was.

**Comment by thecoolkogut4** [comment]
What happens when you play on mc version 1.8? Does this still happen to you?

**Comment by Spicyice101** [comment]
it works in 1.8 thx
