### ISSUE TITLE
Bug WynnCraft on a mission

### ISSUE THREAD

**Issue by SrAnThoNny** [Wynncraft/Issues#8017]
Good day, yesterday afternoon was a mission and that was the light in my colony, and when entering the server I appear in a dark area where I was waiting for the mission to begin, I can not use the teleportation papers I can only Use the / servers command but still I can not get out of there, my nick is SrAnThoNny lvl 63, lock me up with my archer class, please help.

**Comment by LordHelmchen98** [comment]
If you have more than 5 soul points you can do `/kill` to get out.

**Comment by SrAnThoNny** [comment]
thanks :D
