### ISSUE TITLE
LOST MY WAND?

### ISSUE THREAD

**Issue by Zx-ksa** [Wynncraft/Issues#8018]
Hello, i was at wynncraft walking, and i opened my inventory. and while im opening my inventory the server restarted and my wand disappeared! .. all i remember about my wand is that it's 44-76 damage and it was legendary!

please help..

**Comment by LordHelmchen98** [comment]
Thats unfortunate and Im sorry for your loss, but Wynncraft enforces a strict norefund policy. Therefore you wont get your wand back.
