### ISSUE TITLE
Recipie for disaster quest glitch

### ISSUE THREAD

**Issue by What2121** [Wynncraft/Issues#8019]
in the quest recepie for disaster when you are trying to get the quicksalt from the cave on the meteor thing, in the cave is a big white wall blocking any progression, i have switched servers multiple times and even tried again the next day but the wall is always there, i looked up tutorials on the quest and nobody else seemed to be having this problem.

![2017-04-30_10 52 13](https://cloud.githubusercontent.com/assets/28229191/25566693/27d70624-2d93-11e7-8d57-e27cf6bdf95f.png)

thanks for your time :)
-What2121

**Comment by XavierEXE** [comment]
This is a known bug, it's being fixed as we speak and should be pushed on to the main servers soon.
