### ISSUE TITLE
"Reclaiming the House" doesn't display/give the right amount of emeralds

### ISSUE THREAD

**Issue by ChigoMinecraft** [Wynncraft/Issues#8021]
"Reclaiming the House" gives 3456 emeralds but it says its suppose to give 6114 emeralds
http://imgur.com/kEyKheB

http://imgur.com/OB6OEgJ

-Edit: also I know this bug has been reported before and it said it was fixed but it still isn't fixed

**Comment by LordHelmchen98** [comment]
Duplicate of #7040 
Also you didnt ask but I still want to add that there is no way to get the emeralds back due to Wynncrafts strict norefund policy.

**Comment by ChigoMinecraft** [comment]
I didn't make this to tell everyone I didn't get the emeralds I made this to tell gm's that the bug is still not fixed.

**Comment by LordHelmchen98** [comment]
Then please do this on the original thread in future.
