### ISSUE TITLE
Meteorite Spell Glitch

### ISSUE THREAD

**Issue by Narriz** [Wynncraft/Issues#8022]
My IGN is Narriz and I have a weird problem
For about a Year my Meteorite Spell isnt working correctly
I've made 2 new mages to see if it fixes itself, but it didnt
The problem is
When I cast Meteorite Spell the Meteorite disapears mid air not dealing any damage yet consuming mana
Please do something about it for Mage is my favourite class and I dont want to stop playing him because of some stupid Glitch

**Comment by What2121** [comment]
if you switch weapons as the spell is still casting, it will cancel the spell (i.e. meteor mid air)
hope this helps 👍

**Comment by Narriz** [comment]
Pal thank you so much
I have no idea how but this actually somehow worked
Now meteorites fall, all of them
Death and suffering to all :)

**Comment by LordHelmchen98** [comment]
Resolved
