### ISSUE TITLE
An Iron Heart Part I/II 

### ISSUE THREAD

**Issue by Spy21DD** [Wynncraft/Issues#8023]
While I was trying to complete the "An Iron Heart Part II" quest today, I realized that I didn't have the Factory Helmet from Part I. I searched my Bank and other classes and couldn't find it. Quest Items cannot be dropped or traded, so I do not know how I lost it. Is there any way I could get another Factory Helmet or to reset the "An Iron Heart" questline? 

Thanks,

Spy21DD

**Comment by thecoolkogut4** [comment]
type /fixquests to get the helmet back.

**Comment by Spy21DD** [comment]
Okay, thank you very much.
