### ISSUE TITLE
Taproot - Bugged

### ISSUE THREAD

**Issue by TurtleGames101** [Wynncraft/Issues#8024]
I'm doing the quest Taproot and I'm on stage 12 where I need to speak to Teik but she says "I wrote down what you need to do in your book. The forest needs us!". 
![capture5](https://cloud.githubusercontent.com/assets/28115418/25568823/b48ab532-2e03-11e7-9039-66ca1a2491c3.PNG)
Then I went into my book and it says"Speak to Teik"
![capture5a](https://cloud.githubusercontent.com/assets/28115418/25568826/c316625e-2e03-11e7-8040-edaacfc9882e.PNG)
My username is TurtleGames101

**Comment by XavierEXE** [comment]
What the quest book isn't specific about is WHICH Tiek you need to talk to. When you go through the cave the fairy leads you to, you are taken to the dark forest in the past, which is where the Tiek you're supposed to talk to is.
