### ISSUE TITLE
Trying to Enter Yahya's Basement

### ISSUE THREAD

**Issue by BlackCatZZZZZ** [Wynncraft/Issues#8026]
I am Currently trying to complete the quest ???. However when i tried dropping the items to get into yahya's basement it did not work. I dropped the spoon, The mushroom, and the painting into the dropping but the hidden room has not open. I have tried this on different servers with serval other people. I hope you can fix this as soon as possible. Thank you :3

**Comment by XavierEXE** [comment]
When you switch servers or change classes, the NBT data on the painting breaks which causes it to not work in the hopper. Did you change servers, change classes, log out, or crash while you had it? If so, that would be why it didn't work. The other two items don't have the same issue, so switching classes or servers with them should be fine.
