### ISSUE TITLE
Insane mob lag.

### ISSUE THREAD

**Issue by 21harrisont** [Wynncraft/Issues#8027]
I noticed there is a lot of mob lag. The world itself doesn't lag much, just the mobs. I feel like I know why. One time the game glitched out and I saw an armor stand hovering above an enemy. All of these armor stands must be detrimental to the server performance! Maybe remove the armor stands.

**Comment by RubbrDucky** [comment]
I can't talk for the CT or the admins, but I think the armor stands
actually are a part of hitbox detection and mob programming, so I think
that wouldn't work.

**Comment by ColinRioux** [comment]
To me it seems you've been one of the few experiencing it. Some mob entities are armor stand based, others aren't. Removing armor stands would defeat the point, and besides, a lot of the command work and aesthetics are done using armor stands.
