### ISSUE TITLE
Flordur spelling issue?

### ISSUE THREAD

**Issue by TheLimeGlass** [Wynncraft/Issues#8028]
Should this be `What brings you here?`

What happens when you click the npc when you can't access the quest.
![2017-05-01_00 37 53](https://cloud.githubusercontent.com/assets/16087552/25573915/b851790a-2e06-11e7-81f7-0b71ea8692eb.png)

**Comment by LordHelmchen98** [comment]
That (`What brings you here?`) is what it means, but `'ere` slang so it's fine and doesn't have to get changed.
