### ISSUE TITLE
Eluzlerp blank message

### ISSUE THREAD

**Issue by TheLimeGlass** [Wynncraft/Issues#8029]
This happens after the first dialog with Eluzlerp and just about to go get the slime scooper. If you click him again it returns a blank message.

![2017-05-01_00 04 51](https://cloud.githubusercontent.com/assets/16087552/25573975/352e3300-2e07-11e7-831d-0a7d0aae64da.png)

**Comment by LordHelmchen98** [comment]
So at that point of the quest you need to get the mashed insects?

**Comment by TheLimeGlass** [comment]
At this point, you have to go back and talk to his brother to get the slime scoop.

**Comment by LordHelmchen98** [comment]
Well I guess something could be added there (not sure as I'm not a CMD) that tells you to go to his brother, but as your book tells you what to do I don't think it's a gamebreaking thing. Therefore I don't think it has to be changed necessarily.
