### ISSUE TITLE
Wynncraft online map not showing current locatiom

### ISSUE THREAD

**Issue by finleyuk8** [Wynncraft/Issues#8031]
The wynncraft online map is not showing what server I am currently on or my current location in the world, could you please fix this as it is hard to navigate without!

**Comment by Pyromanical** [comment]
It's currently broken, and the Web Devs already know about it, and are trying to fix it.

**Comment by LordHelmchen98** [comment]
As already said its know. Until its fixed you have to use good ol' coords ;)
