### ISSUE TITLE
I die when i pick my class

### ISSUE THREAD

**Issue by Maximpyke** [Wynncraft/Issues#8032]
After picking my class randomly my health keeps going down until i die and it happens again because of this i cannot play wynncraft anymore and i am very sad

plz help

**Comment by LordHelmchen98** [comment]
Do you have armor with negative health regen?

**Comment by Maximpyke** [comment]
no I don't. i've went in wather then it started to lose health. i even took off my armor and my health is still low.

**Comment by PepinhoJp** [comment]
Any accessories?

**Comment by colin350** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
