### ISSUE TITLE
Lost Sanctuary Dungeon Bug

### ISSUE THREAD

**Issue by Monstaah** [Wynncraft/Issues#8033]
Me and my Friend found a bug we are in the Lost sanctuary Dungeon (right now world8) and we cant continue after the "Cutscene" where Garoth says us his name he normally says enough secrets,i have no reason to hide. My name is Garoth. .... and then after your last breath. he says Now DIE! and after that you would be able to run over the bridge. he dont say Now Die the barrier dont go away we cant continue we are stuck we would need to die and we dont want loose our nice equipment ._.

**Comment by Pyromanical** [comment]
Both of you should try doing `/class` at the same time, and see if when you come back it fixes itself.

**Comment by Monstaah** [comment]
we alrdy tried that didnt worked

**Comment by LordHelmchen98** [comment]
Have you tried different servers?

**Comment by Monstaah** [comment]
Worlds you mean? Yeah we did

**Comment by Monstaah** [comment]
Now it worked ...
