### ISSUE TITLE
Wrong teleport location?

### ISSUE THREAD

**Issue by zwellow** [Wynncraft/Issues#8034]
Today (5-1-2017) I was doing a quest called; Enter the Dojo. I've done the parkour, and entered the fighting area. But I had big lagg spike and died... But when I respawned I respawned in the starting area before Ragni? I guess thats not what has to happen...

Zwellow

**Comment by ittnoraA** [comment]
That happens because players respawn in the city that's nearest to them. However, plenty of quest areas are offmap, which means they're too far from cities. The server doesn't know where to respawn the player, so they end up back in the tutorial area.
