### ISSUE TITLE
Bob the zombie

### ISSUE THREAD

**Issue by BasterMC** [Wynncraft/Issues#8036]
i am farming bob the zombie for 2 hours and he doesn;t drop his tier :( why?

**Comment by ittnoraA** [comment]
The spawn rate for Bob the zombie is really low, same with his loot drop rate. 

You should try getting the tear by killing mobs around Nesaak instead, as they have a significantly higher spawn rate.

**Comment by BasterMC** [comment]
i am looking to buy one insted becouse it is fast but i don't find someone to sell it...

**Comment by LordHelmchen98** [comment]
If you cant find someone who can sell you a tear, you should go to the wolf den south east of Nesaak (between Nesaak and the Ice Barrows dungeon). Usually if you grind there its a matter of a few minutes until you find one.
