### ISSUE TITLE
Glitch With Using Shout Bombs

### ISSUE THREAD

**Issue by Official-Melted** [Wynncraft/Issues#8037]
Just wasted 2 shouts. No clue why they aren't working. Here is proof of the glitch.
![2017-05-01_11 00 26](https://cloud.githubusercontent.com/assets/28268921/25588633/e54a06e6-2e5d-11e7-982b-d635a29fe678.png)

**Comment by thecoolkogut4** [comment]
All cross world communication is currently down. Give it a few hours to fix by its self.

**Comment by LordHelmchen98** [comment]
Its known and (as already said) should be fixed in a few hours.
If you want to ask for a refund you can send a mail to support@wynncraft.com
