### ISSUE TITLE
stuck in the Lost Soles mansion

### ISSUE THREAD

**Issue by xsimonebeertjex** [Wynncraft/Issues#8039]
I was doing the lost Soles quest, and when I went to the second floor I got stuk in some pistons :(
I can't teleport out and I don't have a scroll on me, so I'm stuck.

Please someonehelp me!

**Comment by ittnoraA** [comment]
If you have 5 or more soul points, you should do /kill

You will respawn in the nearest town you've visited, most likely being either Iboju village or Troms

**Comment by xsimonebeertjex** [comment]
thanks a lot!!!
