### ISSUE TITLE
Lost wand

### ISSUE THREAD

**Issue by Nelnitorian** [Wynncraft/Issues#8040]
Hello! I am Nelnitorian ingame. Let me explain you the history of my wand.

Today at 15:03 CEST I was looking around Rodoroc just to explore and I went to Dogun zone (also Obsidian Guards). I was going to die so I started casting spells such us teleport, ice snake and heal. Once I thought I was almost saved, I just needed to use one more teleport... my wand disappeared. My wand had just disappeared from my inventory and I swear I didn't drop it. I started receiving hits; 1, 2, 3, 4... dead. I died because my wand disappeared from my inventory.

Once I respawned at Rodorc I opened inventory because I gone mad and I was given a "Oak Wood Stick". The one you start with, the untradeable one ![wynnwandinitial](https://cloud.githubusercontent.com/assets/28271500/25591811/6ca50f16-2eb6-11e7-9062-26f21152fe09.png) . I just was amazed, what the hell was going on? And my wand? I just went as fast as I could to the place I died... maybe I dropped it. Just when I arrived I looked for my wand. WOW, surprise! Nothing and I died because a wand 2-4 dmg... doesn't kill mobs with 5k life.

Respawned again at Rodoroc. Shit. Just leave the wand die in peace? Nah, I realised I had a non identified legendary wand in my inventory and I identified it as fast as I could. I had a Lunar Spine, great! Back again and try to search better where my wand was. Again in that fcking place. Dogun, where are you?

I commited genocide with all those Doguns. They got killed while I looked just to the rock, 
![wynnweapondeath_below_us](https://cloud.githubusercontent.com/assets/28271500/25592320/ac1ce07c-2eb8-11e7-9dde-a0e57398d3ea.png)
AND MY WAND? It wasn't there... I just gave up. Well, not at all... it will be always in my heart <3 .

What's the point of all this? I can't renember my weapon's name. I just can renember this: 
It was a rare weapon (maybe 92-96 or 97-100).
Had: Neutral + Water damage, it was Normal attack speed. It had +%water damage and +%spell damage. And it had this appearance: 
![wynnwandmissing](https://cloud.githubusercontent.com/assets/28271500/25592535/6f323b20-2eb9-11e7-8a2a-f96f7f11fcc8.png) .

What I am asking for is just for an explanation and, if possible, the wand, my wand (also de name of the wand, plz x'D)... Rquesticat in peace.

Sorry for my bad english and have a nice day/night ^^

Thanks for reading, Nelnitorian.

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by Nelnitorian** [comment]
Hello, thecoolkogut4. First of all thanks for the fasta answer. Next... still have the doubt. What's the wand's name? Also, where can I read the full manual of wynncraft's rules?

**Comment by thecoolkogut4** [comment]
https://forums.wynncraft.com/threads/game-forum-rules.111874/

I'm not too sure of the wants name, best bet into look it up on the item guide.

**Comment by Nelnitorian** [comment]
@thecoolkogut4 can't find where it talks about item refunds.

**Comment by thecoolkogut4** [comment]
Reffer to #317 where an ex-admin confirms the policy.

**Comment by Nelnitorian** [comment]
All what I can see is that lungyiin said that it was part of the beta. We aren't in beta, aren't we?

**Comment by Trixter313** [comment]
If you search the tracker for "no refund" 500+ issues should come up mentioning it.

Also, it is stated in step 5 of the guide to reporting issues here: https://forums.wynncraft.com/threads/guide-to-contributing-on-official-github-issue-tracker.170506/

Hope that clears the confusion! =)

**Comment by thecoolkogut4** [comment]
#2565 where a mod confirms it, Or use the search bar to find ~500 other similar cases. If you'd like let's see what @LordHelmchen98 Or @Trixter313 has to say

**Comment by Nelnitorian** [comment]
I am still confused. I can't see the similarity of their reports and mine. I have described what happened just as it occured and I gave an evidence that the server bugged (that starting wand can be only obtainable at the beggining of the game, right?) That's why I wrote down my report, because I thought I had evidences to have the wand back or, at least, an explanation of what happened.

I think that staff is saying that because they don't have proofs of that they say is real and they aren't lying.

**Comment by Trixter313** [comment]
I don't think that the issues linked were meant to be compared with yours to show similarity, just to show the no refunds policy in action.

The starter wand is also given to players when they die, although I think it is supposed to only happen when you run out of soul points completely.

The policy is the same for everyone, whether there is proof or not, to prevent the abuse of refunds as we cannot be sure that an item was lost to a bug or not. The github contributors usually don't have to power to spawn items in, even if they wanted to.

**Comment by Nelnitorian** [comment]
Yes, sure, but when a item can be refund? You are talking about how items aren't refund, but when are them refund?

I just don't know where I can see the item's refund policy. The one that says what items are refund and which not. I mean the rules, where I can find the extense file (the one that thecoolkogut4 gave me doesn't talk about item's refund).

Actually I feel really limited talking english, first time I use it for so loong and a few technical words... so please, be patient with my english. I do not understand "The github contributors usually don't have to power to spawn items in, even if they wanted to." You said that you don't have the power to spawn items?

**Comment by Trixter313** [comment]
I'm sorry for not being clear on the policy, and that we can't communicate in a language you are more comfortable with!

The policy is that no ingame items are refunded at all, no matter what the situation is. The only time refunds are considered are if it is something that was bought with real life money in the online​ shop.

What I meant by the sentence talking about spawning items in is that we do not have the power to give you the item back, even if we wanted to. We would have to defeat animals in game just like you, with no way of just making the wand to give to you.

Please feel free to let me know if I can clarify or reword anything else, thank you!

**Comment by LordHelmchen98** [comment]
This is really unfotunate and Im sorry for your loss, but the no refund policy still applies for your case. (Although it should probably be written down somewhere it is still a thing)

> Actually I feel really limited talking english, first time I use it for so loong and a few technical words... so please, be patient with my english. I do not understand "The github contributors usually don't have to power to spawn items in, even if they wanted to." You said that you don't have the power to spawn items?

We collaborators here on GitHub are usually either Mods, or CTs and sometimes even people without rank (Trixter). Im a Mod on Wynncraft but I still dont have any inventory editing permissions.

However I think the weapon you were using was probably `Requiem`. You wont get yours back, but I hope you can find/ buy yourself a new one.

@Trixter313 maybe it was changed with the sill point system update and you get a starter weapon once you loose your last weapon?

**Comment by Nelnitorian** [comment]
Ouchs... yes, I just understood what you tried to mean. So... if the battle is lost before starting I guess I am not going to receive my wand back soooo... any clue of what happened?

Thanks a lot, @LordHelmchen98 . It was that wand ^^

Sooo... just farm again and take another good Requiem xD Thanks all of you, guys. I don't know how GitHub works but can I rate you or something like that?

**Comment by Trixter313** [comment]
That is very kind, but there is no rating system in Github as far as I know. We are happy to help and appreciate the thanks.

As for what happened here, it is usually very hard to figure out. It could have been a simple thing like dropping the wand and not being able to find where it was dropped, or it could have been the game making a mistake and deleting the item. There is really no way for us to be sure.

Items randomly disappearing isn't a very common issue, with it happening very randomly, so I would not be too worried about it happening to you again.

**Comment by Nelnitorian** [comment]
I swear I didn't drop it. I have drop buttom in the O and I play with wasd so... I have to move right hand from the mouse to drop an item xD

As I said, have a nice day and thanks to @Trixter313 , @LordHelmchen98 and @thecoolkogut4 for helping me. If you know how to close my post, just do it and if you want to say something, say it.

Keep making Wynncraft better! :D

**Comment by LordHelmchen98** [comment]
Always glad to help people ;)
