### ISSUE TITLE
Weird moving items in inventory.

### ISSUE THREAD

**Issue by 21harrisont** [Wynncraft/Issues#8044]
I had two emerald blocks from a quest. It was in my second hotbar slot. I lost the emerald blocks due to a server bug. Somebody said I just dropped them, but I have proof. When holding down Q you only drop one item. So if I did press Q I would have retained one emerald block. Secondly, the bone meal replaced the emerald blocks. If I picked up a bonemeal it would have gone into my 3rd slot. But no, it replaced the emerald blocks! If I picked up mob trash on my way it would have gone into my third slot and not replace emeralds! Thirdly, the server as jacking up earlier, as I couldn't pick up mob loot.

IGN: Htoa

Need more proof? Ask a mod to check my inventory logs.

**Comment by RubbrDucky** [comment]
Please do not make multiple issue submissions. As stated before, Wynncraft
has a strict no refund policy.

I've had that glitch too though, lost my 24% xp cosmic set helmet to it...
Nothing i can do about it though.

**Comment by Trixter313** [comment]
If you hold CTRL (the default sprint key) and press the drop item button, it drops the entire stack. This could explain how all of it was dropped at once. That aside, there is no way for us to tell what really happened, as there are not individual logs of a player's inventory activity.

In case this is what happened, I would suggest changing your drop item key to something other than the default Q in hopes to prevent it from happening again. Something less likely to be accidentally pressed.

If you play a bit longer you will probably discover that it isn't too much of a daunting task to round up 2 more EB worth of emeralds, I hope.
