### ISSUE TITLE
Boat didn't drop

### ISSUE THREAD

**Issue by 21harrisont** [Wynncraft/Issues#8045]
I broke my boat and it didn't drop! WHERE ARE MY TWO EMERALD BLOCKS!!! I placed a boat, destroyed it but it didn't drop! How do I pick up a boat?

**Comment by RubbrDucky** [comment]
Please do not refer to past issues that were closed and refuted in new
issues.

Other than that, do you have pictures?

**Comment by Trixter313** [comment]
What do you mean by you destroyed it? As far as I know, you can't destroy Wynncraft boats by punching them or by crashing them.

**Comment by ittnoraA** [comment]
Wynncraft doesn't allow you to destroy boats. The way of getting a boat back is by entering and exiting it, and the boat gets automatically placed in your inventory. In general, boats seem to randomly glitch around and disappear upon placing. Thankfully you only lost 2eb, and should be able to easily get them back by grinding and completing quests.

**Comment by ColinRioux** [comment]
This is also an issue we've been aware of for a long time. You should also see: #7603 where I explained it more in depth.

For now, please use scrolls/seaskipper (when it's not broken lol)/spells to get places quicker. Or use boats on mc version 1.8.9
