### ISSUE TITLE
Stuck During "Grave Mistake" Quest

### ISSUE THREAD

**Issue by TheSucitivel** [Wynncraft/Issues#8046]
So, I did something really stupid while doing this quest. I was in a house, picked up 4 Abandoned Keys and found a hopper to unlock a door, and, I'm assuming because my computer lagged, the door didn't open until after I put all four keys in, and now I am stuck between that door and the next door which needs a key in the hopper.

**Comment by Trixter313** [comment]
If you're stuck you should be able to use the command /kill to get out. =)
