### ISSUE TITLE
Vanished Items

### ISSUE THREAD

**Issue by IgoMoo** [Wynncraft/Issues#8048]
I lost all my items randomly but bow's keep popping up in my inventory,all low level,Could staff give me back my stuff or something (if not then  a semi decent bow please,it was rare and my gear was expensive,no screenshots...)

**Comment by Pyromanical** [comment]
Sadly Wynncraft has a strict no refund policy, so you won't be given your items back.  Based on what you said, it sounds like you kept dying, and lost all your soul points.  If you get down to very few soul points, you lose all your items.  If you were playing while this happened, you need to be more careful about soul points and watch the messages in chat about them.  If you were AFK when this happened, then mobs probably got to you.  To make sure that doesn't happen again, it's always a good idea to AFK in the class screen.
