### ISSUE TITLE
My friend's trouble

### ISSUE THREAD

**Issue by Mar3kCz** [Wynncraft/Issues#8049]
My friend PandaCZE can't login to server, he was teleported to room.
Here are images:
![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/22253258/25624033/8d1e00fc-2f58-11e7-9674-076262734bcd.png)
![imgpsh_fullsize 1](https://cloud.githubusercontent.com/assets/22253258/25624048/92287c9e-2f58-11e7-8b4b-b2cf9f90b563.png)
![imgpsh_fullsize 2](https://cloud.githubusercontent.com/assets/22253258/25624052/96ac8b98-2f58-11e7-8c3c-ce9e8d7b4a69.png)

**Comment by Pyromanical** [comment]
Try doing `/kill`
