### ISSUE TITLE
Green Skinned Troble Quest Portal bug

### ISSUE THREAD

**Issue by ddddddddddddddddss** [Wynncraft/Issues#8055]
I started Green Skinned Trouble quest and in the cave of orcs there was a portal that was leading back to surface. It bugged and now im stuck in blocks, i cant use scrolls. My ig nick is dVu. Is it possible to tp me back to surface? Because im stuck for like an hour now
![2017-05-03_13 25 19](https://cloud.githubusercontent.com/assets/28345275/25656928/04487a62-3004-11e7-9e5f-1721fd0677d2.png)

**Comment by PepinhoJp** [comment]
They can't tp you out, you'll have to /kill

**Comment by XavierEXE** [comment]
Every time you do /class it will raise you up by 1 block, so keep doing that to get out of the ground.
