### ISSUE TITLE
Galleon's graveyard's cannon minigame

### ISSUE THREAD

**Issue by TomD011099** [Wynncraft/Issues#8056]
I'm doing the Galleon's graveyard ungeon and I have to do some kind of minigame with canons (not with the armoured pirate) and I don't know how to complete it.
![image](https://cloud.githubusercontent.com/assets/27888058/25660145/37076600-300b-11e7-9767-7bc338eb582c.png)

**Comment by PepinhoJp** [comment]
This isnt an issue, this is a question, please ask questions here: https://forums.wynncraft.com/forums/questions.89/ 

or join Wynncraft's Discord and post your issue: 

https://discord.gg/yJkSQwp

**Comment by TomD011099** [comment]
Sorry, I didn't know
