### ISSUE TITLE
Recipe For Disaster Bug?

### ISSUE THREAD

**Issue by EL3MENTPanda** [Wynncraft/Issues#8057]
I was doing the quest and i picked Brie as my mentor, so i went to the salt mines, and i dont know where to go, the wall is collapsed.
![2017-05-01_12 16 43](https://cloud.githubusercontent.com/assets/28315832/25670709/79516640-3025-11e7-8d0f-3faf2c012a2c.png)

**Comment by PepinhoJp** [comment]
This bug has already been fixed in the GM server, just wait with the next push it'll probably be fixed!

**Comment by EL3MENTPanda** [comment]
thx! i was worried i couldnt finish the quest.
