### ISSUE TITLE
Online Wynncraft Map Bug 

### ISSUE THREAD

**Issue by Sweetgrandmacake** [Wynncraft/Issues#8058]
The online Wynncraft map will not show my character icon or my party member's character icon. I have refreshed, changed into different worlds than refreshed, cleared my cookies and refreshed, tried a different browser and did the steps there too.

**Comment by JackyKit123** [comment]
try doing Ctrl + F5 to clear your cache

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
