### ISSUE TITLE
How do I ban appeal a forum ban?

### ISSUE THREAD

**Issue by 21harrisont** [Wynncraft/Issues#8059]
How do I ban appeal a forum ban? When I log into the forums I can't view the forums because I am banned. How do I appeal a forum ban, I can't accsess the ban appeal section! Lawsuit anybody?

**Comment by ittnoraA** [comment]
Hello! Unfortunately you cannot appeal a forum ban.

**Comment by PepinhoJp** [comment]
You can send an email to support@wynncraft.com
