### ISSUE TITLE
Cant play the Game

### ISSUE THREAD

**Issue by Mitokofeuerhuricane** [Wynncraft/Issues#8060]
I got Stuck in the ground infront of the Sand-swept dungeon after dieing in it. and Now i cant get out.
Changeing classes and then comeing back to the class thats stuck doesnt fix the problem neither is switching game servers.  

Please Help
-a Wynncraft player

**Comment by PepinhoJp** [comment]
The only way to fix this is using /kill

**Comment by ColinRioux** [comment]
Please `/kill` with 5 or more soul points. You'll spawn in the nearest town.
