### ISSUE TITLE
I can't open my monthly crate... help?

### ISSUE THREAD

**Issue by youriolatus** [Wynncraft/Issues#8061]
Hey guys, as you probably see in the title, i can't open my monthly crate. every time i press the poster button on the wynncraft store site it just reloads the page and it does nothing... can anyone help me please? thanks!

**Comment by PepinhoJp** [comment]
Go to the store, check if you put the right Username,then accept the terms of service and clickill "Claim for free" then the button will change to "Loading" I think or something like that, then just Join Wynncraft and the crate will be there, the button will always be "Loading" but the crate will load, it's a bug!

**Comment by youriolatus** [comment]
but thats the problem... i dont get that screen where i can write my username... the page just reloads as soon as i press the button

**Comment by ColinRioux** [comment]
Try clearing your cache. On mac, it's CMD + R. On windows, it's Ctrl + F5.

**Comment by youriolatus** [comment]
i did that multiple times... still didn't work :/

**Comment by PepinhoJp** [comment]
Is this the first time that you’re trying to get your crate? If it is email support@wynncraft.com, if it's not you will have to wait some days until the Crates reset for you!

**Comment by youriolatus** [comment]
well... this is my second time claiming it... but can't i send a email even if it is my second time???

**Comment by PepinhoJp** [comment]
Monthly Crates were added on April, 24, this isn't a bug, you haven't waited 1 month, this is the problem!

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.

**Comment by OuterCore** [comment]
youriolatus this happens to me too... idk how to fix it
