### ISSUE TITLE
Wynncraft Quest bug

### ISSUE THREAD

**Issue by wisebeetle** [Wynncraft/Issues#8062]
hello mods/admin/helper on my level 46 Mage I have done Wynn Site A and now I need to do B the level 46 level quest Wynn B I think and I can't find the quest item to start it i looked in my bank and /fixquests on all of my classes and checked there inventory and it not there plz help i need it

**Comment by ColinRioux** [comment]
Well first off all, there is no "helper" rank. We are not hypixel. Secondly, there is nothing that we can do. The only other solution is leveling up another class, doing Wynn site A, and transferring the reward via your bank. We cannot give quest items to you. However, we will log this issue.  

Please confirm that you are looking for: https://wiki.wynncraft.com/index.php?title=Yellow_Crystal_Shard .
