### ISSUE TITLE
Lazarus Pit

### ISSUE THREAD

**Issue by MinrRoyale** [Wynncraft/Issues#8066]
Hello, my ign is MineRoyale and I am having an issue with the quest lazarus pit. There is a stage where you are supposed to go to the top of a tower and read the signs, I have done this, exactly as seen in a playthrough by MrSebbelonian. It will not update my quest book, despite me trying on multiple versions and talking to the starter NPC again. My brother, on the same computer had no difficulty with this part of the quest. I don't know how you would fix it, but help would be nice.

**Comment by ittnoraA** [comment]
Try moving around and going right next to the signs. If that doesn't help, you should swap server and try moving around it again.

**Comment by MinrRoyale** [comment]
I have done all of those things and more.

**Comment by MinrRoyale** [comment]
I know it's not a problem at my end because my brother was able to do it on the same computer but on his MC account. So I 'think' (not sure) it's an issue with the connection.

**Comment by ColinRioux** [comment]
Hi, what does your quest book say?

**Comment by MinrRoyale** [comment]
The issue has resolved itself. Not really sure how.
