### ISSUE TITLE
Quest - A Grave Mistake

### ISSUE THREAD

**Issue by Viprin** [Wynncraft/Issues#8068]
In the middle of "A Grave Mistake" quest, I was kicked for flying. I come back on, and I'm stuck at the cutseen at [360. 85, 3483]. And I'm still stuck. Please help ;-;

**Comment by ittnoraA** [comment]
If you have 5 or more soul points, do /kill to respawn in the nesrest city.

**Comment by LordHelmchen98** [comment]
As @ittnoraA said you can do `/kill` if you have more than 5 soul points. You will have to redo the part where you got stuck.
