### ISSUE TITLE
Mob Resurrection Glitch

### ISSUE THREAD

**Issue by PickleSandwich** [Wynncraft/Issues#8070]
I don't know much about this, except for the fact that it's definitely not supposed to be here. So. I fighting fully formed Amadel. Got him to 50 HP,  hit him, and... He disappeared. Then reappeared. With full HP. Please fix this asap, because it's SERIOUSLY annoying...

Thanks!
-GalacticRedstone

**Comment by DaveZombee** [comment]
There are 3 stages to killing Fully Formed Amadel. I suggest you kill him in a group.
