### ISSUE TITLE
glichted weapon 

### ISSUE THREAD

**Issue by Waxto** [Wynncraft/Issues#8072]
on my wand [Hymn Of The Dead]  there is written that it has 200/3 poison but  when i attack an ennemy with it it does nothing could someone help me ? 

My ING : Waxto

**Comment by Waxto** [comment]
[](url)
![2017-05-05_15 26 04](https://cloud.githubusercontent.com/assets/28456813/25761029/58425706-31a7-11e7-9131-f6f45851145c.png)

**Comment by RubbrDucky** [comment]
do you have negative poison on any of your armor or accessories?

**Comment by Waxto** [comment]
no

**Comment by Waxto** [comment]
![2017-05-06_19 04 23](https://cloud.githubusercontent.com/assets/28456813/25776542/060448b2-328f-11e7-8814-ca754d18a5ae.png)

**Comment by Waxto** [comment]
![2017-05-06_19 04 25](https://cloud.githubusercontent.com/assets/28456813/25776544/0c87ff4e-328f-11e7-9543-415283a9c3c8.png)

**Comment by Waxto** [comment]
![2017-05-06_19 04 27](https://cloud.githubusercontent.com/assets/28456813/25776547/1550b008-328f-11e7-876c-86a08557de9f.png)

**Comment by Waxto** [comment]
![2017-05-06_19 04 28](https://cloud.githubusercontent.com/assets/28456813/25776550/227232d4-328f-11e7-80d7-5a35ea20f560.png)

**Comment by Waxto** [comment]
![2017-05-06_19 04 30](https://cloud.githubusercontent.com/assets/28456813/25776551/290b4022-328f-11e7-9506-05bb3baa9862.png)

**Comment by Waxto** [comment]
![2017-05-06_19 04 31](https://cloud.githubusercontent.com/assets/28456813/25776552/2e556544-328f-11e7-8d95-b3573cfaf58b.png)

**Comment by Waxto** [comment]
![2017-05-06_19 04 33](https://cloud.githubusercontent.com/assets/28456813/25776553/339031f6-328f-11e7-9f77-1f235f5b5cf9.png)

**Comment by Waxto** [comment]
![2017-05-06_19 04 35](https://cloud.githubusercontent.com/assets/28456813/25776554/382bdf12-328f-11e7-8f6e-5d0c4756f423.png)

**Comment by LordHelmchen98** [comment]
Are you sure it does nothing at all?
Poison activates after hitting a mob (note that it gets reset if you hit the mob again). It damages the mob three times by a third of your total poison (I'm not sure but I think it starts a second after you hit the mob and between each hit there is a second as well). You have 231 in total so it should deal 77 per hit.

**Comment by Waxto** [comment]
Ok thx i think it's that i'll try and i will tell you if it works !

**Comment by Waxto** [comment]
Oh yes it was that thx ! I thought it was not working lol
