### ISSUE TITLE
Logged on, lost items for no reason

### ISSUE THREAD

**Issue by rainbowcraft2** [Wynncraft/Issues#8073]
I logged on and started playing, but my items all fell off, with the error of 'insert stat type here' must be at least 'value here' to use this! And the items all fell. My inventory was full, and all the items that wouldn't fit just disappeared. I lost a Morph Topaz and a morph bracelet because of it. The thing is, I needed 2 strength for the ring, but I have more than 40. I know the policy is no refunds, but I do think this should be fixed. I also lost a necklace to it, but I don't remember what it was, because I had master before, and only recently changed it.
![2017-05-05_23 30 40](https://cloud.githubusercontent.com/assets/28475562/25770468/e7249b8a-31ea-11e7-9c1e-15edb1529432.png)
![2017-05-05_23 30 47](https://cloud.githubusercontent.com/assets/28475562/25770469/e72631ac-31ea-11e7-94cb-4a3dc211b363.png)

**Comment by ChigoMinecraft** [comment]
This is a glitch that wynncraft knows about, it happens when you don't have enough space in your inventory for your items because sometimes it loads in your items before your player so you drop stuff that you need +skill points to use.

**Comment by LordHelmchen98** [comment]
This is known for a very long time now and the admins tried to fix it already. However it seems to be a pretty difficult problem and they weren't able to find why this happens and therefore it wasn't possible to fix it.
In future you should try to keep one empty inventory slot for every accessory that requires skill points.
