### ISSUE TITLE
I am stuck!!

### ISSUE THREAD

**Issue by BasterMC** [Wynncraft/Issues#8076]
i am stuck in Nesaak in ground at x:112 y:73 z:-808 
plz help me get out!!!
THX ;3

**Comment by PepinhoJp** [comment]
The only way is /kill if you have +7 soul points or scrolls, the staff doesn't take people out!

**Comment by PepinhoJp** [comment]
Duplicate of #8075

**Comment by BasterMC** [comment]
thx
