### ISSUE TITLE
Bug GUILD !!! -Slorex

### ISSUE THREAD

**Issue by Slorex** [Wynncraft/Issues#8077]
Bonjour, je suis français désolé de ne pas pouvoir parler ANGLAIS... Bref voilà sur WynnCraft je suis dans une guilde ca fait plusieurs semaines que je veux la quitté mais je n'y arrive pas, pourtant je fais bien le /guild leave et j'écris "yes" ca me dit bien que j'ai quitté ma guilde mais je suis toujours dedans http://prntscr.com/f4rv67
![screenshot_24](https://cloud.githubusercontent.com/assets/28485239/25772461/95398fca-326b-11e7-97f6-90024d22af29.png)

**Comment by PepinhoJp** [comment]
Duplicate of #8063

**Comment by PepinhoJp** [comment]
Not the same issue but the same answer

**Comment by LordHelmchen98** [comment]
Actually its a duplicate of #3665 
Its unfortunate but we cant do anything for you. You will have to be patient until guilds get fixed.
