### ISSUE TITLE
Galleon's graveyard cannon game bug

### ISSUE THREAD

**Issue by TomD011099** [Wynncraft/Issues#8080]
I've noticed that when you log off and then log on while doing the cannon minigame the cannonballs don't move anymore. To solve this, you have to either wait until someone goes into the minigame or find a server on which the minicame was recently completed.
https://youtu.be/qOXtecnCxSA

**Comment by Villageacules** [comment]
Unfortunately, I think that this can't be avoided because of the way that Minecraft servers work. If I am incorrect, somebody tell me.

**Comment by LordHelmchen98** [comment]
Minimaps are allowed as long as you dont use entity trackers. Please turn them off.

**Comment by TomD011099** [comment]
@LordHelmchen98 sorry, I didn't know that, I won't use them again

**Comment by Moe-Ronickah** [comment]
Please read our [Game and Forum Rules](https://forums.wynncraft.com/threads/game-forum-rules.111874/).

**Comment by Moe-Ronickah** [comment]
When you're in a minigame, you're progress is being tracked by a script, sometimes.  It depends on the minigame.  If you leave, the script resets.  So, yes, @TomD011099 , your solutions are correct.  A pain in the neck, but correct.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
