### ISSUE TITLE
Resource Pack not working

### ISSUE THREAD

**Issue by Vulcrix** [Wynncraft/Issues#8081]
I have read every single thing on resource packs I could find but I cannot solve the issue for Wynncraft. I tried enabling resource packs, updating the launcher and deleting and reinstalling legacy. None have worked and I'm more frustrated than ever. Pls help

**Comment by PepinhoJp** [comment]
Try changing your Minecraft version...

**Comment by Moe-Ronickah** [comment]
Try this, @Vulcrix :

1) First go open Minecraft.
2) Delete the Wynncraft server.
3) Close out of Minecraft.
4) Restart Minecraft.
5) Add back the Wynncraft server.
6 ) Try running Wynncraft.

If it works, you should be able to change your 'server resource pack' setting from 'prompt; to 'enabled'.
This isn't unique to Wynncraft.

Let us know if this worked, please.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
