### ISSUE TITLE
Can't See Thomas in Creeper Infiltration

### ISSUE THREAD

**Issue by dankwoodplank** [Wynncraft/Issues#8083]
I've begun the creeper infiltration quest but now cannot find Thomas at the coordinates provided. Issue occurs on all servers.

**Comment by ColinRioux** [comment]
Hi, what does your quest book say? (Please take a screen shot or write down exactly what it says, could be a typo in quest book).

**Comment by Moe-Ronickah** [comment]
@dankwoodplank , sometimes the coordinates given in the quest book aren't exact, but rather, they are an indication of a general area.  Make sure that you look around that little village to see if you can find him.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
