### ISSUE TITLE
Couple of bugs/glitches I'm Experiencing.

### ISSUE THREAD

**Issue by OliverF0103** [Wynncraft/Issues#8085]
So i stopped playing wynncraft for a while, and roughly a week ago i started playing again, for some reason now when someone uses DXP the bar does not appear at the top of the screen. My build bar also doesn't Appear. Another problem i have is that i cannot type /guild stats to check my guild. Not sure how to fix this.

**Comment by LordHelmchen98** [comment]
Guilds are very glitched. I think right now the commands `/guild stats` and `/guild leaderboard` are broken.
However the reason why the bar isn't shown is your MC version. You can't see the bar in 1.8. I'd recommend to use 1.9 instead.
