### ISSUE TITLE
Powder relic not giving the right tier

### ISSUE THREAD

**Issue by BlackRoseRoseNoire** [Wynncraft/Issues#8086]
Hello everyone, I hope it's not a known bug.

I was goofing around the map and I unexpectedly discovered a new relic. So I rushed to get it but unfortunately, I think it gave me the wrong tier of powder. Not a big deal personally but I'm sure I have to tell it to the staff.

As you can see in the screenshot bellow, it is written that It gives me a T1 powder and it actually does. But shouldn't it be a T4 powder ? Maybe I didn't get how relics work. Hehe.

Well, have a nice day everyone ! Hope I did good.

BlackRose

[2017-05-07_11 28 06](https://cloud.githubusercontent.com/assets/28502659/25779518/9179541a-331a-11e7-8972-1a1bcc8e25d0.png)

**Comment by Trixter313** [comment]
Powder relics drop powders up to the tier that they are. So a tier 4 relic can drop levels 1-4. This is to prevent camping at the highest relic areas for easy high tier powders.

Hope that clarifies!

**Comment by BlackRoseRoseNoire** [comment]
Oh well, I feel dumb for thinking it was a bug. Sorry for the inconvenience.
Have a nice day, thanks a lot for the clarification !
