### ISSUE TITLE
Lost Cosmic Set (equiped) with 15 Soulpoints

### ISSUE THREAD

**Issue by games4thewin** [Wynncraft/Issues#8090]
I lost today a Cosmic Set with a 175 XP bonus in my Armor slots. Afer a relog I haven't got it back and it was not in my Inventory. Can someone help me.

**Comment by ittnoraA** [comment]
Sorry, wynncraft follows a strict "no refunds"-policy, which means you're not getting it back. The only way you can get it back is by redoing the quest on another class.
