### ISSUE TITLE
Random Invisible Barrier after start of Decrepit Sewers

### ISSUE THREAD

**Issue by LmnoGaming** [Wynncraft/Issues#8092]
i was going through the decrepit sewers and had just finished putting the tokens in the hopper and i then went through the gate only to be met with an invisible barrier, i had to do ./kill which made me lose my chance at defeating the boss. is this normal or just a bug? (P.S i was stuck between the gate and a random barrier preventing me from getting to the parkour)

**Comment by ittnoraA** [comment]
The barrier wall is there to make players unable to skip the dialogue while going through, but sometimes it resets improperly and gets stuck. All you had to do was to swap server and you could've gone through.

**Comment by LmnoGaming** [comment]
oh but when i logged back on again i was still stuck in between the gate and the barrier.

**Comment by LmnoGaming** [comment]
it's happend again when i tried going back in after killing myself
this is kinda getting annoying now, i went to another server after the bug happend and i still couldn't get through

**Comment by Moe-Ronickah** [comment]
@LmnoGaming which version of MC are you using?  There have been sporadic problems with MC 1.11 versions with tripwires - I've ran in to a few.  If you are using 1.11, try going through on 1.8.9, and let us know what happens.

**Comment by Kibbles0121** [comment]
I reinstalled the pack and that worked.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
