### ISSUE TITLE
stuck on boat when seaskipping

### ISSUE THREAD

**Issue by Dj8PoWer** [Wynncraft/Issues#8097]
i was going to go to Selchar through seaskipping, so i gave dropped my ticket into the hopper, it teleported me on the boat in the middle of the ocean but then nothing happens, the captain doesnt talk and i don't get teleported again, i had to use a scroll to leave.

**Comment by Pyromanical** [comment]
If that happens again, switch servers, and you should be able to complete the boat ride.

**Comment by PepinhoJp** [comment]
The Seaskipper sometime bugs, if you get stuck inside one of them you'll have to /kill and unfortunately you'll spawn in the starting area... @Pyromanical switching servers wouldn't work because it's a Redstone system and it’ll be disabled in the other server after the switch...

**Comment by ColinRioux** [comment]
We are aware of the situation that the seaskipper is broken. We are currently rewriting the system. If neither of the suggestions work for you, the only other thing you can do is to: use spells, scrolls, or boats to travel around the ocean.

**Comment by LordHelmchen98** [comment]
@PepinhoJp If it's broken on one server that doesn't mean it's broken on every server. Sometimes things are broken on one server but are working fine on all other servers. Every server is running on its own. Only if an error gets pushed it's on all servers.

**Comment by PepinhoJp** [comment]
I wasn't saying that it will be broken on every server @LordHelmchen98 , I was saying that you wouldn't be able to complete the ride if you're on the middle of the ocean, you would have to /kill and go there again on another server.

**Comment by LordHelmchen98** [comment]
@PepinhoJp wrong there is a tripwire on each boat that triggers your boat ride.
