### ISSUE TITLE
Stuck in a wall!

### ISSUE THREAD

**Issue by niki0012** [Wynncraft/Issues#8098]
I was doing a quest "The house of Twain" and when i got on one lobby i accidently bugged into a wall and cant return to original state, i cant move or teleport! Please help ;-;

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by niki0012** [comment]
thank you so much!
