### ISSUE TITLE
Wynncraft wynnexcavation site d

### ISSUE THREAD

**Issue by FanciestNir** [Wynncraft/Issues#8099]
Help im doing the wynncraft wynnexcavation site d quest and the pazzle after the parkour in site d doesnt work please help :D

**Comment by PepinhoJp** [comment]
Have you tried switching servers?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
