### ISSUE TITLE
Unable to identify old weapon from before the update

### ISSUE THREAD

**Issue by TDeltasora4** [Wynncraft/Issues#8100]
I've been on hiatus for a while and I came back just recently.  After gaining a feel for the new mechanics I decided to visit the rest of my classes to organize their items.  As usual I was transported to the update room with each class, but with my lvl 74 archer, my "bob's mythic bow" was missing, even more strange is that the wand that should be "bob's mythic wand" for my mage is unable to be identified.  Every time I try to click on the "unidentified wand" in the identifier's window, it says that "this item cannot be identified again.  here is a screenshot.  

![image](https://cloud.githubusercontent.com/assets/28544391/25823291/9a3e079a-3409-11e7-8422-3c6519f52ca3.png)

![image](https://cloud.githubusercontent.com/assets/28544391/25823306/a473c15a-3409-11e7-83b9-e2f53e5822cc.png)

**Comment by RubbrDucky** [comment]
This is a known bug, sorry.

Um...

Anyone wanna explain? I'm lazy :P

**Comment by TDeltasora4** [comment]
any way to get this fixed?  it should be prominent that I am unable to repeat the quest and gain another quest item to get another mythic item.

**Comment by ThunderRemix** [comment]
This will not be fixed until Jumla messes with the item identification system during the code refactor.

**Comment by LordHelmchen98** [comment]
That's because Bob's weapons have set values and can only be bought but not rerolled.
Unfortunately weapons from pregavel are UnIDed weapons now and if they have set values they can't be identified now.
There is no way to fix this, but it shouldn't be hard to get a new one for like 5le or less.
