### ISSUE TITLE
Issue with Naragath the demon prince

### ISSUE THREAD

**Issue by Coolbeanies** [Wynncraft/Issues#8101]
I've killed this mob like 3 times and it still doesn't drop the [Eye Of Blood]. I cannot continue my quest if this bug continues. Please help :(

**Comment by ittnoraA** [comment]
Are you sure you're killing the correct mob? There are 2 versions of Naragath, one which drops the Eye of Blood, and one which isn't supposed to be killed. I'd recommend you to take a look at a walkthrough on youtube for further help.

If you're sure you're attacking the correct one, try swapping servers and see if that works.

**Comment by colin350** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
