### ISSUE TITLE
Garoth Boss Fight

### ISSUE THREAD

**Issue by Azorable** [Wynncraft/Issues#8102]
I fell into the pit in Garoth's boss fight, as soon as it closed. Got stuck in a bunch of redstone.
![2017-05-08_16 15 48](https://cloud.githubusercontent.com/assets/28546185/25825881/8c487612-33f9-11e7-81f2-f31065d3c2a8.png)
![2017-05-08_16 13 43](https://cloud.githubusercontent.com/assets/28546185/25825882/8c487a9a-33f9-11e7-93f4-6760038897e6.png)

**Comment by ittnoraA** [comment]
I'm sorry to hear this happened to you. If you haven't already done this, type /kill if you have 5 or more soul points. 

I'll take a look at the redstone behind it and prevent the hole from closing when a player's in it.

**Comment by ColinRioux** [comment]
Closing since @ittnoraA got this one.
