### ISSUE TITLE
Unable to pick up creeper skin.

### ISSUE THREAD

**Issue by Eqs1** [Wynncraft/Issues#8103]
Edit: Didnt realize you needed to kill it :/

Was doing the creeper infil quest and goto the end and was when I got sent back to the ground I could not pick up the creeper skin I also tried to do it on multiple servers and nothing worked. If possible could the skin be added to my bank or something because I do not know how to complete the quest now.
========
Evidence of bug
========
https://gyazo.com/752ef659fd87057bf9e709b3f1acfd26
https://gyazo.com/6c36c76e959746da9256486b6f265244
https://gyazo.com/d297d8564bedf49b66b57c06696c453e
https://gyazo.com/104e1a4f30c5fc66cb69c161cbb0b9aa

IGN is Eqs

**Comment by ittnoraA** [comment]
The creeper skin is actually a mob that you need to kill to get the drop.
