### ISSUE TITLE
Lost rank

### ISSUE THREAD

**Issue by coltpwrs7** [Wynncraft/Issues#8106]
Hello, I used to play Wynncraft years ago before I left for the fire academy. I just got back recently and I no longer have my rank. My rank was Hero. I still have my characters and items ect. but no rank. If someone could help me out that would be great thanks!

**Comment by ittnoraA** [comment]
The HERO rank was added on the 31st of october 2016, so you couldn't have had it all those years ago.

**Comment by coltpwrs7** [comment]
Maybe it was not the hero rank then, It was some rank. All I remember is that it was the highest rank you could purchase at the time.

**Comment by coltpwrs7** [comment]
Possibly vip+?

**Comment by ittnoraA** [comment]
Could you provide a screenshot of you having the rank? Or something else that proves your statements to be legit?

**Comment by coltpwrs7** [comment]
Either way, Is there anyway you guys can check your records because I would like my rank back If possible!

**Comment by coltpwrs7** [comment]
No I could not.. Im not even on the same PC as I was back then

**Comment by ColinRioux** [comment]
You must email support@wynncraft.com. This is a place for bug issues not rank issues. You _may_ need to provide proof of purchase if you want to obtain your rank back.
