### ISSUE TITLE
Game deleted my bobs mythic spear

### ISSUE THREAD

**Issue by AMCBrosky** [Wynncraft/Issues#8107]
So i was doing the quest enter the dojo and i was in the combat challenge. And during the challenge while i got all 30 tokens needed. But then while i was putting the items in the hopper the game glitched and deleted my bobs mythic, i was hovering over the items yet it deleted the bobs mythic spear. I spent hours trying to beat bob and i need to get it back, please help.

**Comment by AMCBrosky** [comment]
also it didn't drop on the ground, i know that because it was not in the item piles.

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by AMCBrosky** [comment]
but i spent hours trying to get bobs mythic

**Comment by AMCBrosky** [comment]
i spent hours in order to beat bob

**Comment by AMCBrosky** [comment]
and months to get to the level i am at

**Comment by AMCBrosky** [comment]
due to the old leveling system

**Comment by AMCBrosky** [comment]
i can't go through that again.

**Comment by AMCBrosky** [comment]
please

**Comment by AMCBrosky** [comment]
i lost bobs mythic spear

**Comment by AMCBrosky** [comment]
please.

**Comment by AMCBrosky** [comment]
just. please.

**Comment by AMCBrosky** [comment]
all i ask for is my bobs mythic back

**Comment by AMCBrosky** [comment]
can you understand my problem

**Comment by thecoolkogut4** [comment]
Even if me or the Github Collaborators want to give you the item back, we can't because we do not have the power to spawn in items. Sorry.

**Comment by AMCBrosky** [comment]
the what do i do?

**Comment by thecoolkogut4** [comment]
You can level up another class, or you can buy one (I think it's tradable)

**Comment by AMCBrosky** [comment]
it took me months to level up another class.

**Comment by AMCBrosky** [comment]
as for the other class i hope i can buy one. granted i will need to use my assassin class to get it.

**Comment by AMCBrosky** [comment]
but why are they so strict?

**Comment by AMCBrosky** [comment]
is there a way to get it back?

**Comment by thecoolkogut4** [comment]
Please stop spamming, try to put everything into one post. You can make a new class, get the weapon, delete the class, and get another weapon if you want it that badly
