### ISSUE TITLE
Donkey glitch

### ISSUE THREAD

**Issue by Apocrophon** [Wynncraft/Issues#8108]
I was getting chests on Corkus when upon my spawning in my 16/25 Black horse, it instead spawned in a donkey @_@
It was significantly slower and jump height was less, but it did change back after I respawned it.

http://prntscr.com/f628ff

**Comment by ittnoraA** [comment]
This is only a visual bug occurring in higher versions of minecraft, so it shouldn't affect speed or jump height.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/7060

**Comment by Apocrophon** [comment]
*and it happened again just now
