### ISSUE TITLE
i cant get pick a class

### ISSUE THREAD

**Issue by boembaboem** [Wynncraft/Issues#8109]
If i pick a class i cant click on it to start the adventure it is bugging or something pls help me

greetings boembaboem

**Comment by ittnoraA** [comment]
Can you describe your problem with a bit more detail? Does your game crash? Do you get an error message?

**Comment by boembaboem** [comment]
IT gives me An error yes

**Comment by boembaboem** [comment]
And after the error that i have to Pick a class

**Comment by ittnoraA** [comment]
Are you able to screenshot/record the problem and post them here? Or at least give a more detailed description?

**Comment by theonlygusti** [comment]
@boembaboem do you get kicked for flying?

**Comment by LordHelmchen98** [comment]
I assume you have the same issue as #7185
Please read Moe-Ronickahs long post and then post below.
