### ISSUE TITLE
Area Issues

### ISSUE THREAD

**Issue by DankJuicyMemes** [Wynncraft/Issues#8111]
Hi! So there's this bug with the Pirate Trove's mission. I have done all the clues and I'm at the area where the treasure is at. But everytime I go inside it, it says "You have no reason to go there.".
Please help. Thanks.

**Comment by thecoolkogut4** [comment]
What does your quest book say?

**Comment by Locky1110** [comment]
Maybe you haven't talked to...
whats his name again?
Either way like what thecoolkogut4 said, what does your book say?

**Comment by colin350** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
