### ISSUE TITLE
Gear in lobby area

### ISSUE THREAD

**Issue by RedLogicP** [Wynncraft/Issues#8112]
This guy was shooting people (dealing no damage) in the lobby area.
![2017-05-10_18 43 24](https://cloud.githubusercontent.com/assets/24531217/25924433/b43f2b62-35b0-11e7-9b17-7ec61086b37e.png)

**Comment by Trixter313** [comment]
If you go to the archery range in the lobby you can get a bow and arrows for some target practice.
