### ISSUE TITLE
Bank broken

### ISSUE THREAD

**Issue by Xevitan** [Wynncraft/Issues#8116]
![2017-05-11_16 55 34](https://cloud.githubusercontent.com/assets/28638182/25976604/ebfeb6fc-366a-11e7-8128-9a269c504d5f.png)
My Wynncraft bank has several stacks of arrows in it that I can't remove. I don't care if you wipe my bank completely I would just like those arrows gone. ign = Xevitan

**Comment by ColinRioux** [comment]
Please message Pretzule on the forums.
