### ISSUE TITLE
"Out of my Mind" is broken for me

### ISSUE THREAD

**Issue by Aylridian** [Wynncraft/Issues#8117]
I was doing the Out of my Mind quest when I had nearly completed it, at the point where you get teleported outside the lab. I used my escape spell when I got out and it launched me away from the area where you get the dialogue. Now I'm stuck and my quest book won't update, and I can't get back into the lab to reinitiate the dialogue

**Comment by ColinRioux** [comment]
You must follow the steps to get the lab key again to return to the lab.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
