### ISSUE TITLE
The House of Twain: Marius grave wont accept emeralds/Quartz grave wont open

### ISSUE THREAD

**Issue by St0rmfir3** [Wynncraft/Issues#8119]
I've [along with a friend] been trying to finish the house of twain quest for a little while now,
[we've tried doing it on different servers and days already] but the grave where you're supposed to drop emeralds wont accept them?
Both of the photos attached are taken at almost the exact same time, but the grave just wont open and its really bothering me because I would like to finish this and a grave mistake, as im very interested in the lore.
Hoping to get a response back, thanks!

![1](https://cloud.githubusercontent.com/assets/27205805/26015380/0be723fe-3761-11e7-8cc8-67c125834c79.png)
![2](https://cloud.githubusercontent.com/assets/27205805/26015384/0ef10c7c-3761-11e7-9917-11c027b55329.png)

**Comment by LordHelmchen98** [comment]
This is a onetime bug.
You should be able to fix it by doing it on another server,
