### ISSUE TITLE
Loading terrain for extremely long time, then kicked for flying

### ISSUE THREAD

**Issue by theonlygusti** [Wynncraft/Issues#8121]
I can connect to wynncraft easily, and get into the hub on my first attempt without any problems.

When trying to enter a game server though, minecraft displays "Loading terrain" for sometimes over half an hour, and _then_ the world loads, but just for a split second before I am immediately kicked for flying and sent back to a lobby.

I made [a video](https://youtu.be/PxGEeavBiEc) to showcase this, unfortunately the video is kind-of best-case scenario, I was lucky that day and managed to log on both second attempts. Usually it takes much, much longer for me to login.

I play mainly on 1.11.2 clients now, Optifine, vanilla and 5zig mod, but this glitch happened on 1.8 and 1.9 _and_ 1.10 for me. I have not figured out how to get around it when it happens.

Of course, the reason for the kick is obvious, because minecraft spawns players a block higher than when they logged out so you are above air, maybe wynn could change this as a temporary fix? Or enable flying until the problem is solved?

I have also experienced the issue with Server resource packs disabled, and my render distance _always_ is only 2.

**Comment by PepinhoJp** [comment]
20 minutes is impossible, the server would kick you and the reason would be "Timed out", the kick thing, do you have "/toggle autojoin" enabled?

**Comment by theonlygusti** [comment]
@PepinhoJp the server does kick me, but for flying, because you get spawned a block above where you logged off.

Also, btw, I recently experienced a 35 min one, so 20 is definitely not a limit.

I get kicked for flying from the game, and spawn in a lobby, then get kicked for flying from like 8 lobbies in a row before finally settling.

I have that enabled.

**Comment by PepinhoJp** [comment]
Just disable autojoin, it bugs!

**Comment by theonlygusti** [comment]
@PepinhoJp it doesn't fix the problem

**Comment by theonlygusti** [comment]
The problem persists, tomorrow I will upload a video of what it looks like.

Unfortunately the video showcases some best-case scenarios, generally I can't log for about 3-5 attempts, but in the video it logs second attempt

**Comment by theonlygusti** [comment]
Here's the video:

https://youtu.be/PxGEeavBiEc

**Comment by SaltiestOfHobos** [comment]
Join a lobby with 30 players or less.

**Comment by LordHelmchen98** [comment]
Should be fixed.
