### ISSUE TITLE
Item Texture Missing

### ISSUE THREAD

**Issue by 1mag1nat1on** [Wynncraft/Issues#8122]
The item "Mesarock Arch" is missing its weapon texture for me. I'm using 1.10 and Wynncraft Enhanced Modpack.
[http://imgur.com/5Zr34JO]

**Comment by ColinRioux** [comment]
Yes, this is because Wynncraft weapon models are actually retextured blocks instead of actual weapons/tools (like spades). This isn't related to your version or modpack. 

Unfortunately, it won't go away until Wynncraft is ported up. For now, you'll have to use it as is.
