### ISSUE TITLE
Reclaiming the house quest glitch

### ISSUE THREAD

**Issue by luminytz** [Wynncraft/Issues#8124]
I killed the Gurg and went back to Ahmas with the 'Head of the Gurg' item but I cannot finish the quest. All Ahmas is saying is the line NPCs usually say when a quest is during progress.

**Comment by ColinRioux** [comment]
What does your quest book say?

**Comment by luminytz** [comment]
![capture](https://cloud.githubusercontent.com/assets/16329005/26022128/7af31148-37db-11e7-9711-8ad1f326aa24.PNG)
I have no idea if the ''basement'' is the problem as I only have found 2 entrances.

**Comment by ColinRioux** [comment]
Did you go to those coordinates?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
