### ISSUE TITLE
Just lost my item. for no reason? seems weird.

### ISSUE THREAD

**Issue by danewill** [Wynncraft/Issues#8125]
Hi, i'm danewill on the wynncraft server and I love it. But I have been losing a few random items lately. I drag them into my inventory, I do not press q, and they suddenly DISSEPEAR. "Q for me is to lose an item or throw it on the ground", so I do not know what happened. I have lost a potion, "Nothing Big" but I also lost My legendary rouge Dislocater weapon and a wither rib cage reward in the first dungeon. I'm really sad that I lost my dislocater, and I have no idea what caused me to lose it. I did not shift click it to the inventory, I honestly just dragged it up there. If anyone can help me and this issue, please respond. Thank you all for your generosity and helpfulness. Danewill Username.

**Comment by ColinRioux** [comment]
You were already very specific, but could you please talk through and try to explain your issue more clearly. I'm trying to gather as much information as possible so we can try and fix this issue in the future.

However, Wynncraft enforces a strict no-refund policy. This applies to all players, including moderators and content team members. What this means is that we won't return/refund you item, simply to maintain fairness amongst all of the players, even if you are being honest.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
