### ISSUE TITLE
Lost Bobs Mythic Spear because of a server crash

### ISSUE THREAD

**Issue by TurtleGames101** [Wynncraft/Issues#8129]
I was on server 27 on corkus island at the bank trying to access it when the server crashed then i went to server 23 and my spear is gone

**Comment by LordHelmchen98** [comment]
Unfortunately you wont get it back due to Wynncrafts strict norefund policy, but it shouldnt be too hard to get a new one as you can buy it from someone else for like 5 le (maybe less).

**Comment by TurtleGames101** [comment]
Isn't it untradeable?

**Comment by LordHelmchen98** [comment]
@TurtleGames101 Sorry for the late response. No Bob's mythic items are tradeable
