### ISSUE TITLE
Unable to retrieve item in Lost Tower

### ISSUE THREAD

**Issue by Everett1999** [Wynncraft/Issues#8130]
I was going through the lost tower with a  lower level friend when I changed my chestplate and due to a bit of lag, my chestplate was thrown out of my inventory rather than being reequiped. That wouldn't be a problem normally, but I looked around for it, and it was nowhere to be found. I was confused, until I noticed [this water stream](http://i.imgur.com/B0qUL4f.png). I tried it with a junk item, and I was unable to retrieve it once it flowed around the corner. I lost my Mummy's Rag chestplate, and as far as I know there is no way to get another without getting another class to do the quest, so this was particularly upsetting.

**Comment by LordHelmchen98** [comment]
Im sorry for your loss, but Wynncraft enforces a strict norefund policy. Therefore you wont get your item back.

**Comment by Everett1999** [comment]
I understand that, and that is fine, but the reason I opened a ticket is because I feel like something should be done about that water stream. Perhaps a block stopping the water from flowing to an inaccessible area is appropriate?
