### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by BONK3R** [Wynncraft/Issues#8133]
I was just changing out my chestplates, a booster plate and a Boreal-Patterned Chestplate. I replaced the Boreal with the Booster, while in 6th level Tower of Ascension, and I continued to ascend, as you do in the Tower of Ascension. At the boss level, I opened my inventory and to my dismay, found that my one-time Hive Chestplate was missing. I searched the tower inside and out and found nothing. I figured I must have just dropped it or something, but this happened a few days ago, when I was fighting various Hive bosses. I died and respawned in Thesead, where I changed around some wands to better prepare for the next boss. One of these wands was an Empire Builder with 2 tier 5 and 3 tier 4 green powders on it. When I arrived back at the Hive and prepared for entering the next boss room, of course, the wand was gone. No, this is not an attempt to get a free Hive Chestplate, I'll just spend another 14 hours grinding a character up to lvl80 to fight Qira again. I just want this bug to be fixed before I accidentally "drop" a mythic on the ground and waste 5 stacks of Liquid Emeralds. Thanks.

**Comment by ColinRioux** [comment]
My apologies, but the no-refund policy still stands. Reporting the issue numerous times that items are disappearing won't get it fixed any quicker. We are working on a refactor for the **entire** codebase (which takes time), and this will ideally be patched as a result (however, more issues could result from refactor).
