### ISSUE TITLE
Quest bug

### ISSUE THREAD

**Issue by wolfoxcs** [Wynncraft/Issues#8134]
the second quest (farmer kelry) not working. I find the ring but i can't give it to him.

**Comment by kanyunhk** [comment]
The ring you found by killing rats outside the cave is fake, walk further to the farm behind the farmer and you will see there is a cave, the real ring can be obtained by killing the Giant Rat in the cave.

**Comment by LordHelmchen98** [comment]
If you cant find the cave that kanyunhk already mentioned watch [this video](https://youtu.be/inGrmcAWFKA) to see where it is.
