### ISSUE TITLE
Duplicate Undroppable Items..?

### ISSUE THREAD

**Issue by camocat9** [Wynncraft/Issues#8135]
Hello! I love the feature that prevents you from throwing out important quest items for later, but I also found a bug. Someone who had finished all the quests with the diving helmet had dropped it in the Detlas bank, and I accidently picked it up. Now I have two of them, and I can't drop one because it's an "important quest item for later." I don't want this helmet to take up one of my spaces in my inventory or my echest until I reach level 60 or whenever I need it next... How could this be helped?
![two breathing helmets](https://cloud.githubusercontent.com/assets/28685851/26033326/f01646b0-3877-11e7-836d-ad8febe169f1.png)
(The helmet above it is the same thing..)

**Comment by BONK3R** [comment]
make a new class, bring it to Ragni, give the unwanted items to that class via enderchest, delete the class.

**Comment by PepinhoJp** [comment]
Or just put the item that you don't want in the crate area and it will disappear!

**Comment by LordHelmchen98** [comment]
What Pepinho means by that is your daily reward chest. Open it in your compass menu, put the item in the chest and then close it in order to get rid of the Breathing Helmet I.
