### ISSUE TITLE
Stuck Underground on the envoy part II

### ISSUE THREAD

**Issue by TurtleGames101** [Wynncraft/Issues#8138]
I was at the wave part in avos temple i put the pixie dust inside then the ground opened up and i was glitched under the floor
![2017-05-14_17 30 38](https://cloud.githubusercontent.com/assets/28115418/26035841/3e067388-38cb-11e7-937d-f1571cb340ec.png)

**Comment by ChigoMinecraft** [comment]
do /kill

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
