### ISSUE TITLE
stuck on the second boss floor of sand swept tomb

### ISSUE THREAD

**Issue by RayDuhSloth** [Wynncraft/Issues#8140]
The boss wont spawn and im stuck in the sand swept tomb on world 23

**Comment by RayDuhSloth** [comment]
Oh ya and my IGN is RayDuhSloth

**Comment by ColinRioux** [comment]
The only way to fix this is to `/kill` and do the dungeon again, if the boss isn't spawning, or have a friend run to the boss room while you're there. Switching worlds will revert you to the entranced of the dungeon w/out reward.
