### ISSUE TITLE
Lost the mushrooms for the Shattered Minds Quest

### ISSUE THREAD

**Issue by CriodeRio** [Wynncraft/Issues#8142]
So while the doing the Shattered Minds Quest, I must have dropped the mushrooms (The Quest Item) and I can't finish the Quest. It isn't a bug, it's just that I've lost the quest item. I went through again to see if I could get it, but it wasn't given to me. My problem shouldn't be too hard to fix, I just need a mod or admin to convene with me and give me the quest item.

**Comment by ColinRioux** [comment]
`/fixquests`

**Comment by CriodeRio** [comment]
Just did that but I still don't have the mushrooms.

**Comment by theonlygusti** [comment]
`/fixquests` works (or at least, has done for me many times)

Check: your bank _and_ _**all**_ of your classes' inventories

It would be strange if you couldn't regain the item.

**Comment by CriodeRio** [comment]
No, I think I just pressed Q and didn't realize while holding the item.

**Comment by theonlygusti** [comment]
You can't drop quest items anyway. Maybe you think you lost a quest item but in fact it was just some collectable you need for the quest's completion, e.g. the Wedding Ring in the first quest at Ragni.

The only way I lost quest items was by deleting secondary classes that were holding them, but /fixquests worked to recover them.

**Comment by Villageacules** [comment]
Please check your bank and all of your inventories. It's there if /fixquests doesn't work.
