### ISSUE TITLE
WynnExcavation Site A Paper bug

### ISSUE THREAD

**Issue by AllenClapx** [Wynncraft/Issues#8144]
![screen shot 2017-05-15 at 1 35 01 pm](https://cloud.githubusercontent.com/assets/28698543/26043894/5f690556-3973-11e7-9eb9-8a218ba9ac80.png)
I have done the quest where i give the translate paper to Vade and go into the tomb but when i came out the book say good find Vade and i did. But the NPC says to give him the translated paper to him. Can any admin help me

**Comment by Pyromanical** [comment]
Try `/fixquests`, see if it gives you the paper back, then give it back to him.  If that doesn't work then I'm not sure.

**Comment by colin350** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
