### ISSUE TITLE
Lost quite a few levels

### ISSUE THREAD

**Issue by Gesmoo** [Wynncraft/Issues#8149]
Me and my friend used to play WynnCraft for hours every day a few months ago, but due to getting an extremely busy agenda. We had to stop our binge playing and start studying.
Now we're back at it again, but when I joined the server, I seemed to have lost a lot of levels. I was an assassin level ~62, but now I'm just an assassin level 24.
This seems odd to me and I hope I don't have to regain all of those 38 levels.

**Comment by theonlygusti** [comment]
*My friend and I

*but due to a busying agenda, we had to stop....

**Comment by Gesmoo** [comment]
These grammarnazi's have infiltraded everywhere. Even commenting on irrelative exposition.
You make this world a better place gusti.

**Comment by theonlygusti** [comment]
*infiltrated

**Comment by Villageacules** [comment]
Sorry, rule #16 under "Game Rules," absolutely no refunds on in-game items.

**Comment by colin350** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
