### ISSUE TITLE
So many problems with kicked for flying

### ISSUE THREAD

**Issue by theonlygusti** [Wynncraft/Issues#8151]
I get kicked for flying _all the time_

E.g. just now, I was running the undergrowth ruins dungeon on the large slime block bounce parkour, and I lost my sprint so I used escape to go to the next one. I failed and used escape again, but got kicked for flying. Note: I didn't land on ground before second escape.

Also, going from the key collector (undergrowth ruins) to the entrance (the black stuff), I spawned into the Black box which is where the dungeon starts but got inside that black box (for flying.)

I don't know what the problem is, potentially my laggy internet, but it's a very frustrating problem. Perhaps wynncraft should look into a proper anticheat system?

**Comment by Gesmoo** [comment]
*E.g. just now, I was running through the undergrowth ruins...
*parkour and I lost my sprint, so I...
*Note: I didn't land on the ground before my second escape.
*Wynncraft.
*anti cheat

**Comment by theonlygusti** [comment]
@Gesmoo what? Your post will probably get deleted... I have no idea what you're doing.

**Comment by ColinRioux** [comment]
Unless you can suggest a homemade solution for an anti cheat system which can account for laggy internet, by all means, suggest it. Wynncraft is custom coded. Sure the system could be optimized, but some cheating clients take advantage of lag/loop holes to cheat. 

Your problem is stemming from poor internet connection.

**Comment by theonlygusti** [comment]
@ColinRioux Wynncraft has no anticheat atm apparently, I think just adding one would be a significant improvement as it would most likely fix this issue, among potential others. I don't get kicked from servers with more renowned anticheats, e.g. Hypixel, Mineplex, Badlion, even though my connections to them are same (very similar pings and traceroutes until the last few hops)
