### ISSUE TITLE
Trapped in the Decrepit sewer dungeon

### ISSUE THREAD

**Issue by TheDankestMatt** [Wynncraft/Issues#8152]
So today Flare_Fortress92 and I, (Garden_Asparagus) was trying out the Decrepit sewer dungeon when we found this glitch. When opening the first door i got to the part where it says you have no value for you life. Flare can pass through but when i try i hit an invisible wall. Even after redoing the whole thing i get stuck in there and i cannot leave the dungeon.

**Comment by ColinRioux** [comment]
This has been reported numerous times; therefore, we are well aware of the issue. Thank you for reporting, however... try to search for your issue next time (removing the "is:open" text to see both open and closed issues). 

You should not get kicked from the dungeon unless you are in the boss room, so try switching servers. If that doesn't resolve your issue, you can see if someone can do the first part again (and see if the wall goes away). Worst case, your only solution will be to `/kill` or to use a teleport scroll. 

Please be aware that we are doing everything in our power to fix this issue. I'm not sure if mc version is associated with the issue, but certainly playing on 1.8.9 (Wynn's default version) to be safe is always worthwhile for the least issues.

**Comment by TheDankestMatt** [comment]
Alright thanks, im new to the forums so i wasn't sure. I'll try 1.8 and if no luck im sure one of my friends can give me a scroll.
