### ISSUE TITLE
"There has been an error... try again"

### ISSUE THREAD

**Issue by Herugaa** [Wynncraft/Issues#8157]
All the issues who talk about this error are closed, so I create a new...

When I try to chose a class, I get an error in the tchat "There has been an error... try again".
Obviously, my player data need to be removed, but I not have anything to lose, so can you delete all for me please ?

My Minecraft username is DoTheWasshingUp.

![capture](https://cloud.githubusercontent.com/assets/28684624/26103102/3e41a89a-3a38-11e7-8c84-b08966a9880b.PNG)

**Comment by ColinRioux** [comment]
Will link @Moe-Ronickah so he can help you. If you could pass the message on that messaging Moe directly for data reset (on the forums) is more efficient than here. 

(Also thank you for being the first person to ever use a search bar +10000000)

**Comment by Herugaa** [comment]
@ColinRioux but how can I contact @Moe-Ronickah ? he is never present on Discord...
If I didn't understand, excuse-me, I'm french...

**Comment by AckroWynn** [comment]
@Herugaa He means that you could contact Moe on the forums, by sending a conversation message asking for the reset. It's more efficient than on here.

**Comment by Moe-Ronickah** [comment]
Your MC name in our records is "Craftman7000", and an admin has found you.  He's resetting your player data, so, try again in about 12 hours.

**Comment by Herugaa** [comment]
@Moe-Ronickah thank you very much ! it works !
