### ISSUE TITLE
my horse got sucked

### ISSUE THREAD

**Issue by karasuokane** [Wynncraft/Issues#8158]
I just inadvertently dropped a chestnut horse into the altar of the jungle and he got sucked. Can I find or impossible?

**Comment by theonlygusti** [comment]
I believe impossible, although it would be nice to have a diff. system to the hoppers so that it is possible.

**Comment by LordHelmchen98** [comment]
Unfortunately its not possible to get it back. No from the hopper and due to Wynncrafts strict norefund policy not from the staff team either.

**Comment by karasuokane** [comment]
it's unlucky, my brother had merged 3 weeks ago with 16 Le :D
