### ISSUE TITLE
An Iron Heart Part I: Golem isn't spawning

### ISSUE THREAD

**Issue by Scherzkeks** [Wynncraft/Issues#8159]
I was in the lair yesterday but in there wasn't any Golem.
I reconnected but in there was no Golem again.
I switched the server but in there was still no Golem.
Also today he isn't spawning
Screenshot of the Quest Book and the lair: http://imgur.com/a/mFN1t
Ingame Name: Scherzkeks199

**Comment by Pyromanical** [comment]
Are you sure you're looking in the right place for the Golem?

**Comment by Scherzkeks** [comment]
Yes I think so, the coordinates showed the entrance of this lair.

**Comment by Scherzkeks** [comment]
OOH I think I have the solution. I always jumped down xD
