### ISSUE TITLE
Always kicked for flying

### ISSUE THREAD

**Issue by theonlygusti** [Wynncraft/Issues#8161]
I am _always_ kicked for flying when joining the game servers.

I came up with a possible fix:

Why not put a barrier block under the player's feet when they spawn, and destroy it the instant that they move, type chat, turn head, etc.

Make the barrier block only for that one player, don't tell any other client it exists.

Ta-da! Now vanilla MC will not kick people for flying, and finally people can play the game!

**Comment by LordHelmchen98** [comment]
It was not fixed like you suggested, but you shouldn't have problems with it anymore.
