### ISSUE TITLE
Yellow Crystal not working?

### ISSUE THREAD

**Issue by dacokid** [Wynncraft/Issues#8162]
I've tried using the Yellow Crystal to start the WynnExcavation site B but this is the only thing that he NPC Lykron says. 

![](https://image.prntscr.com/image/d70de947065a42668ad803e38ddc18ae.png)

The quest says it has already started, but nothing happens.

*Edit1: I'll head to the Almuj Excavation Site and see what happens.

*Edit2: I went to WynnExcavation 1 and nothing happened there.

**Comment by Pyromanical** [comment]
Are you sure you are taking him the Quest Item Yellow Crystal you get from Excavator Vade in WynnExA, and not the the Untradeable Yellow Crystal you get on the ground in the WynnExA temple?

**Comment by dacokid** [comment]
@Pyromanical Well, seems like I'm using the Untradeable Yellow Crystal, and is the only one I got after finishing the WynnExA.

**Comment by colin350** [comment]
Try `/fixquests`

Also: It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to Wynncraft. If your issue still persists, feel free to make a new issue trying to describe it with as much detail as possible.
