### ISSUE TITLE
Stuck in Corkus

### ISSUE THREAD

**Issue by NicBOMB** [Wynncraft/Issues#8165]
I started the Envoy Part I mission and got to the part where the Mechs attack and Maxie gives backstory by teleporting the player to different sets. The server restarted while I was in one of the sets. I need to get put back in the scene for it to progress. Recording here: https://youtu.be/St0TLTptBiE
Yes I am playing music in the recording. Yes I use a minimap, shaders, and the Enhanced Modpack. I have a teleport scroll for Rodoroc to unstuck myself, however, I need to keep going with the quest. Any way to force me to get to the next stage of the quest? EDIT: I also logged back online and am now outside the invisible box for some reason. Weird.

**Comment by ChigoMinecraft** [comment]
do /kill , also please turn off the entity radar on your mini map because it is punishable.

**Comment by NicBOMB** [comment]
Okay. Didn't know radar was punishable. Totally don't need it anyways lol.
