### ISSUE TITLE
Server Closed Destroys Quest Item

### ISSUE THREAD

**Issue by AiriaVSol** [Wynncraft/Issues#8171]
I was doing Aldoreis Secret I, i began by getting the purple Gemstone Dust acquired from the Wynn Jungles, if i recall, it is from another Quest, Lost In The Jungle, which i already previously Completed. I gave the Gemstone Dust to Elrund but mid dialogue, the Server Closed, thus Deleting my Gemstone Dust and not allowing me to proceed with the Quest, keeping me stuck with him requiring me to go get the said Gemstone Dust which could only be gotten from the already finished Quest. If i could get the Gemstone Dust back, that would be great, otherwise i will Never be able to complete this quest.

Thank you

**Comment by Pyromanical** [comment]
`/fixquests`

**Comment by AiriaVSol** [comment]
I tried that at first, that's why i wrote this glitch note because it didn't work. Took about 70 times typing that in, but i finally got the dust back. Thanks
