### ISSUE TITLE
uhh... I'm stuck! Wizard's Teleport

### ISSUE THREAD

**Issue by NECR0BEAZT** [Wynncraft/Issues#8172]
Ok i'm not entirely sure if this is a bug, but I'm posting it here to help solve a problem some others may accidentally fall into. My Wizard account is currently stuck above the lion's den near Almuj at the coordinates 747 142 -2222 (according to the F3 Menu). I had a Teleport Scroll, but couldn't use it and lost it instead. My username is NECR0_BEAZT, and if anyone could help me in any way, I'd greatly appreciate the aid. I got stuck when trying to teleport onto a block. In the process, I instead went through a barrier block and am now stuck inside one. I hope nobody else has gone through this...

I'm including a screenshot of where i'm at too.
![2017-05-18_16 12 47](https://cloud.githubusercontent.com/assets/28791926/26223734/fb8dc64c-3be4-11e7-9559-6f7bb6147474.png)

**Comment by NECR0BEAZT** [comment]
Ok so I got out, but I was just letting you know that it is a possibility

**Comment by SaltiestOfHobos** [comment]
You can do /kill if you have enough soul points.  Recommended that you do it when your soul points are high so you don't lose items

**Comment by LordHelmchen98** [comment]
RESOLVED
