### ISSUE TITLE
Lost Soles piston's issue

### ISSUE THREAD

**Issue by CriodeRio** [Wynncraft/Issues#8174]
Hey, I know how to get out, but I just wanted to let any moderators know that the pistons in the "Lost Soles" quest are a death trap if you don't go quickly enough. They don't make you die, but you will however get stuck in the blocks they push in. I am now currently in a section with redstone devices and other things of the sort.
![2017-05-18_19 31 00](https://cloud.githubusercontent.com/assets/28696215/26230965/6d2951f6-3c01-11e7-9434-f82dcc2f2529.png)
![2017-05-18_19 37 26](https://cloud.githubusercontent.com/assets/28696215/26230974/7f597202-3c01-11e7-87b0-080a3f1bd0d2.png)

**Comment by CriodeRio** [comment]
I was just saying that the pistons should be slowed down so this doesn't happen to anyone else.

**Comment by ittnoraA** [comment]
If you're still stuck, you should do /kill to get out as long as you have 5 or more soul points. 

I can try asking for a permission to rework this contraption with command blocks, so it wouldn't happen again.
