### ISSUE TITLE
Creeper Skin glitch during Creeper Infiltration

### ISSUE THREAD

**Issue by dirtypedestrian** [Wynncraft/Issues#8175]
I was playing the Creeper Infiltration quest with my friend. After the creeper exploded and we were teleported, he ended up picking up both of the creeper skins. Since the skins are untradeable, now I am stuck in the mission. :/

**Comment by ChigoMinecraft** [comment]
do the cut scene again.

**Comment by ittnoraA** [comment]
The creeper skin mob should respawn automatically after a while. If you already jumped off the tree, you can get back by going through the cutscene again.

**Comment by dirtypedestrian** [comment]
Thanks!
