### ISSUE TITLE
Cant remove my player effect

### ISSUE THREAD

**Issue by Cire360** [Wynncraft/Issues#8176]
I recently scrapped the player effect i had active and now its glitched and wont go away. As much as i like effects its getting on my nerves

**Comment by ittnoraA** [comment]
Do you have any other player effects? If you do, just activate one of them and click on it again to disable it. If you don't, then you're out of luck

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
