### ISSUE TITLE
Cant stop dying in void

### ISSUE THREAD

**Issue by RayDuhSloth** [Wynncraft/Issues#8177]
When ever me and my friend join we spawn in a void and die repeatedly. please help

**Comment by Trixter313** [comment]
Could you post a screenshot? Also, do you have your character's items on you while stuck?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
