### ISSUE TITLE
Double (legendary ?) drop from a mob kill

### ISSUE THREAD

**Issue by Exyl77** [Wynncraft/Issues#8178]
I've sometimes dropped twice a legendary item from a mob. It happened with mobs from different levels, so i guess it's caused by my stats. It might also have happened when mobs were killed by poison, not sure about that though.
I link there my stats and weapons :
[Id bonuses](https://gyazo.com/cc82dba7cb54e16ba79f16853baf518e)
[First weapon](https://gyazo.com/8c4d23be69827d820ad037f572bbdaf8) 
[Second weapon](https://gyazo.com/2166f3bef799cfd205a5902b72b6e84e)

**Comment by Pyromanical** [comment]
It's one of two things probably.  Either there was a double loot bomb, or the double killing glitch happened and it dropped twice its loot.

**Comment by LordHelmchen98** [comment]
As Pyromanical said probably there was a double loot bomb. If a double loot bomb is active everything drops twice.
I doubt it was the double kill glitch though because it's very unlikely to get two legendary items that way.
