### ISSUE TITLE
All my stuff went bye-bye

### ISSUE THREAD

**Issue by 420killit** [Wynncraft/Issues#8179]
All my items were removed, including my armor and my legendary items, I logged in and I was bare, exposed, violated, I dont know where all my items went but I was in Almuj!

**Comment by Trixter313** [comment]
How many soul points did you have? When you die with low soul points you start losing items.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
