### ISSUE TITLE
Resource Pack Crashing

### ISSUE THREAD

**Issue by AgentPanda** [Wynncraft/Issues#8180]
My friend and I are trying to play Wynncraft but every time he gets on and he's asked to download the resource pack. It's fine for me but when he does it, he crashes.

**Comment by ittnoraA** [comment]
It sounds like they're missing the server resource packs folder. Tell your friend to go to their pc's **%appdata%**, open **.minecraft** and create a folder called **server-resource-packs**

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
