### ISSUE TITLE
Boat glitch

### ISSUE THREAD

**Issue by supertassu** [Wynncraft/Issues#8184]
Hello! <br>

I found a glitch about boats: when travelling from Nemract to Selchar, the water will get the boat underwater. When I arrived, I had 2 vanilla Oak boats.

**Comment by ChigoMinecraft** [comment]
please throw out the vanilla oak boats as it is bannable, also play on 1.8.9 if you want to fix this issue.

**Comment by LordHelmchen98** [comment]
RESOLVED
