### ISSUE TITLE
Quest item bugs "Factory helmet" / "Climbing helmet"

### ISSUE THREAD

**Issue by Nikkity** [Wynncraft/Issues#8185]
I have completed the "An Iron Heart II" quest yet I can not get rid of my factory helmet.

I also for some reason have two "Climbing helmet"(s) in my bank (apparently picked up after a random person threw this, like.. what?)

**Comment by LordHelmchen98** [comment]
Are you still facing the first issue? If so what does you quest book say? 
If you still have two climbing helmets you can put one of them into your daily reward chest.

**Comment by Nikkity** [comment]
I’m sorry but that response is way overdue, I’ve already quit the game.

Sent from Windows Mail
