### ISSUE TITLE
Losing items in Identifier

### ISSUE THREAD

**Issue by Tumblurr** [Wynncraft/Issues#8186]
Recently put a booster plate into the indentifier to get a new id because i wanted higher walk speed and the server crashed as it was indentifying, when i got back onto the server it was gone.

**Comment by Trixter313** [comment]
Wynncraft has a strict no refunds policy, so unfortunately we can't return the item. I also don't think there is much we can do, besides making sure the servers don't crash unexpectedly, which is always the goal.
