### ISSUE TITLE
I'm blocked

### ISSUE THREAD

**Issue by Newneos** [Wynncraft/Issues#8191]
Hello, i'm here beacause i want to talk of a bug in the Wynncraft Server.
Currently I would be stuck in a block in the coordinates -1865 28 -4897..
I realized this problem during a quest and when I went into a teleportation portal, I did not come out but I was stuck.
Today I can't play and I would like someone to help me.

Thanks a lot.

Newneos

**Comment by LordHelmchen98** [comment]
In order to get out you can just do `/kill` with more than 5 soul points.
