### ISSUE TITLE
Quest bug the lost 

### ISSUE THREAD

**Issue by iiBok** [Wynncraft/Issues#8196]
i deliverd all letters but it wont let me finish the quest i hope an admin or somthing like that can help me with that

**Comment by wussp0pp1nj1mb0** [comment]
Check your quest book. Make sure it doesnt say ''Deliver it to name'' or something

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
