### ISSUE TITLE
wynnexcavation site a

### ISSUE THREAD

**Issue by GoshGal** [Wynncraft/Issues#8199]
My Friend and I started the quest just fine. We got the paper to translate from Vade. We went to the Tesha and got her to translate it but i believe we never got it back. I want back to Vade and he started to say something and then the server was restarted. I did not mean to click on him  but i was fighting a spider and clicked him. Now we cant do anything with the quest. We looked it up on the Wynn wicki and did the riddle but it want let us past the diamond block (yes we got it to open). We also tried /fixquests and it did nothing. 
I am Gosh_Gal and my friend is Imdisfunctional. 

![minecraft 1 11 2 5_21_2017 10_17_17 pm](https://cloud.githubusercontent.com/assets/28851828/26290210/f8a2ba96-3e73-11e7-8048-c75326b32bc8.png)
![minecraft 1 11 2 5_21_2017 10_17_31 pm](https://cloud.githubusercontent.com/assets/28851828/26290214/fc2d914a-3e73-11e7-83c4-253cba051fd0.png)
![minecraft 1 11 2 5_21_2017 10_18_53 pm](https://cloud.githubusercontent.com/assets/28851828/26290220/fee466e8-3e73-11e7-91e3-6245f0e2f13b.png)
![minecraft 1 11 2 5_21_2017 10_20_03 pm](https://cloud.githubusercontent.com/assets/28851828/26290226/04dbfb2e-3e74-11e7-9d0b-ff85f683824b.png)
![minecraft 1 11 2 5_21_2017 10_20_36 pm](https://cloud.githubusercontent.com/assets/28851828/26290229/077c368c-3e74-11e7-9587-4733118e4fcd.png)

**Comment by Pyromanical** [comment]
Do `/fixquests`

**Comment by GoshGal** [comment]
We tried that it did not work

**Comment by NeckFace** [comment]
It happened to me too and i couldn't figure it out for about a year but then i realized that the item i needed was in my bank so search for that paper in your bank or other inventories to see if it works

**Comment by GoshGal** [comment]
I did that, still not there.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
