### ISSUE TITLE
Missing Abysso Galoshes, can't do Lost Soles quest.

### ISSUE THREAD

**Issue by Zakoa** [Wynncraft/Issues#8200]
The Abysso Galoshes have disappeared from my bank and inventory. I've tried /fixquests but the Galoshes are still missing, without the item I can't start the Lost Soles quest. Is there any other way i can get help by maybe contacting a staff member or something?

**Comment by PepinhoJp** [comment]
Have you checked your bank? Other classes inventories? If you still don't find it, I'm afraid you'll have to create another class and get the galoshes again... Wynncraft has a strict no-refund policy so they don't give items back!

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
