### ISSUE TITLE
Can't Connect to Servers

### ISSUE THREAD

**Issue by TheeNinjabunny** [Wynncraft/Issues#8201]
I can connect to the lobbies just fine, but I can't connect to any of the servers. I've tried all of them. I get into the server, but before the terrain loads it stops for around 20 seconds, goes to a dirt background screen, then I either get disconnected, timed out, or the error in the image. What should I do?

I just tried changing the resource pack option from "enable" to "prompt" and it kin of worked. It asked if I wanted to download the packs and when I hit yes it worked. I disconnected myself to change the server and it went back to giving me the errors I mentioned above.
![untitleddddd](https://cloud.githubusercontent.com/assets/28868266/26314831/cc5123ea-3ed4-11e7-9f45-80fe318bb7d9.png)

**Comment by PepinhoJp** [comment]
Try changing your version

**Comment by TheeNinjabunny** [comment]
Thank you for the suggestion. While I don't know how to change my version, I did try playing it in Forge and that seems to be working. I tried three times and it worked every time.

**Comment by LordHelmchen98** [comment]
What PepinhoJp meant by that is that you could have tried to use a different Minecraft version (using 1.9 instead of 1.11 for example). It's possible to change that in the Minecraft launcher. 
Nice to hear you found a workaround though.
