### ISSUE TITLE
My Skin Is Always Alex

### ISSUE THREAD

**Issue by MegaPandaGaming** [Wynncraft/Issues#8202]
everytime i go in a game my skin is alex
is this a bug or something other then that.
and when i load my save my weapons disappear.

**Comment by thecoolkogut4** [comment]
Sometimes this happens when you connect to the server without the resource pack. So are you using the default pack? Or are you using a different one

**Comment by MegaPandaGaming** [comment]
i'am using the resource pack

**Comment by HelloWynnter** [comment]
You just need to take your armor off and then put it back on.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
