### ISSUE TITLE
Pls Help im Glitched

### ISSUE THREAD

**Issue by XeNemesis** [Wynncraft/Issues#8203]
My main account is a lvl 56 archer and i was grinding in the Herb Caves when the server kicked for no reason and when i logged back on i was above the barrier blocks limiting how far up you can go so i cant get back down and i dont hack at all so please someone help because ive benn working hard on this account and I dont want to lose it.

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by XeNemesis** [comment]
This is a picture of me above the Great Bridge. 
![2017-05-22_19 59 11](https://cloud.githubusercontent.com/assets/28873879/26324122/66a51d76-3f29-11e7-8dc4-d96ffbfc37dc.png)

**Comment by XeNemesis** [comment]
Thanks!! You saved me!!
