### ISSUE TITLE
Missing Morph Topaz Ring

### ISSUE THREAD

**Issue by fatalmagi** [Wynncraft/Issues#8205]
hi i was just questing around traded an item with one of my friends and then i lost my morph - topaz ring and i was wondering if there was anyway i could get a new one as im now unable to wear half my armor with this ring missing and it is rather frustrating when your level 33 without ring and not able to wear boots due to it

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.
