### ISSUE TITLE
Deleting Items 

### ISSUE THREAD

**Issue by WarlordLogan** [Wynncraft/Issues#8206]
For some reason the server was lagging and I could not hit things, so I took off my hat and put it back on. A couple minutes later the server times out and I relog. When I arrive my hat is gone and it was my only legendary and now I cant fight because I am to weak.

**Comment by thecoolkogut4** [comment]
Ive had this happen to me, what ever i do it got undone and it was very annoying. Sadly there is nothing anyone can do as there is a strict no refund policy.
