### ISSUE TITLE
The boss of Corrupted Decrepit Sewers

### ISSUE THREAD

**Issue by MrRedCrack** [Wynncraft/Issues#8207]
The first time I try it, I beat the dungeon normally,
but when I continued to grind it, I found something weird...
The second time I try it, I had to kill the boss twice to beat it
And for the third time, I had to kill the boss thrice!
Is that intended?

**Comment by wussp0pp1nj1mb0** [comment]
Make sure to kill it with Melee. Not spells. If you use spells it may bug out.

**Comment by LordHelmchen98** [comment]
It's not intended, but happens quite often. 
However this is a well known issue and I'm pretty sure the devs know about it but I have no idea if they are able to fix this (anytime soon).
