### ISSUE TITLE
unban problems...

### ISSUE THREAD

**Issue by nicknico** [Wynncraft/Issues#8208]
it wont let me appeal for a unban because my username is incorrect but i know for a fact it is correct so what can i do?

**Comment by nicknico** [comment]
plus i was baned for "compromised account" and i changed my pass so i Shuld be able to join back but no i cant appeal so if i can be unbaned form here that would be good but if not, i need to be able to appeal.

Mc name: sans7

**Comment by thecoolkogut4** [comment]
Email support@wynncraft.com

**Comment by nicknico** [comment]
thank you!
