### ISSUE TITLE
Cannot Complete a Quest because of server restart

### ISSUE THREAD

**Issue by ItzMehh** [Wynncraft/Issues#8211]
So i was doing the Quest Elemental Exercise and done it all then when i was asked to return the fiery spear to Suri and give the study results back to Ragon. and as dialogue was being said it restarted and when i logged back into it the quest was not finished and i no longer had the items
all because it restarted at 5/6 Dialogue

**Comment by thecoolkogut4** [comment]
you need to repeat the last stage in the quest to get the item again, once you have the item talk back to Suri.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
