### ISSUE TITLE
Lost all Armor

### ISSUE THREAD

**Issue by HelloWynnter** [Wynncraft/Issues#8218]
Before 5/23/2017, I had a full set of endgame armour on me. But when I logged on to my archer in Wynncraft on 5/23/2017, all my armor was gone from me. The accessories are ok but i'm dissapointed that I lost my armor. (I wore the full set of the armor)

**Comment by HelloWynnter** [comment]
Username is: HelloWinter

**Comment by HelloWynnter** [comment]
It's called endgame armour but the thing is that it's the one that is in the range of level 66-72

**Comment by LordHelmchen98** [comment]
This a really weird glitch that happens sometimes. Happened to me too once. 
However I'm sorry for your loss, but due to Wynncrafts norefund policy you won't get it back.
