### ISSUE TITLE
Eye of the Storm boss Naragath

### ISSUE THREAD

**Issue by MissRoxie** [Wynncraft/Issues#8219]
Whenever I try and kill him, he does not drop the Eye of the Blood, which is the item i need to complete the quest. I've killed him about 3 times and still did not drop it.

Not sure what I should do about this quest.

**Comment by ittnoraA** [comment]
Duplicate of #8101

Try what was said on 8101 and report back with the results

**Comment by MissRoxie** [comment]
I tried it. I saw two forms of Naragath. One with the Hierophants and it had about 1 mil health. I ignored that one and proceeded to the next room where i could fight Naragath and defeat him. he still did not drop the Eye of Blood.

**Comment by LordHelmchen98** [comment]
There is not really an issue with this boss. It's just that he has two forms. Kill both of them in order to get the drop.
