### ISSUE TITLE
Stuck in the wall

### ISSUE THREAD

**Issue by Cobbothewizard** [Wynncraft/Issues#8220]
Hi,

inagme username: sTiCkY_MeSs
im currently stuck in the wall at the abandon mine... i used a teleport spell as i was hit and now im inside a block. cords are XYZ 742.33 / 29.00 / - 1291.300

can i get teleported back to Deltas? ive tried using my ragni teleport scroll but doesnt work...

thanks!

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by LordHelmchen98** [comment]
RESOLVED
