### ISSUE TITLE
Farmer kelri bugged quest

### ISSUE THREAD

**Issue by cummyorange** [Wynncraft/Issues#8222]
First "wedding ring" handed in, turned out to be a washer, now i have 16 wedding rings yet farmer kelri still asks for me to find his ring.

**Comment by thecoolkogut4** [comment]
you need to go to the cave that is inside of the war, and get the real ring, then give Kelri it and you should be able to finish the quest.

**Comment by LordHelmchen98** [comment]
RESOLVED
