### ISSUE TITLE
Legendary Island bug

### ISSUE THREAD

**Issue by Nisutec** [Wynncraft/Issues#8224]
Ich erhalte bei dem bosskampf kein Item. Ich denke das es an den Doppelten Namen liegt die manche Leute haben. Also bitte fixen sie endlich das Problem. SCHNELL BITTE

**Comment by thecoolkogut4** [comment]
Double name is a guild glitch and it should not effect mob drops.

**Comment by Nisutec** [comment]
aber warum erhalte ich dann von dem Boss kein Item sondern nur mein Kumpel ?

**Comment by thecoolkogut4** [comment]
OHHH, you need To do at least 15% (either 15% or 10%) of the damage to the boss in order to get the drop. That's also the same for every mob in Wynn.

**Comment by LordHelmchen98** [comment]
Wie thecoolkogut4 schon gesagt hat muss man 15% vom Schaden machen um ein item zu bekommen. Vermutlich hat dein Freund fast den kompletten Schaden gemacht und du fast keinen.
