### ISSUE TITLE
Bank deleted item

### ISSUE THREAD

**Issue by Catsupp72** [Wynncraft/Issues#8227]
First time using the bank so I wasn't sure what spots were what. Tried to deposit 5 emerald cubes into a space that i haven't unlocked yet due to being lower level. The items disappeared. In Detlas if that matters.

Unless it actually unlocked the space i was trying to use? Im level 12 and have 2 rows - is this normal or did i just buy a row?

**Comment by RedLogicP** [comment]
You bought a row.

**Comment by LordHelmchen98** [comment]
RedLogicP is right, expanding the bank seems to cause issues, but due to Wynncrafts norefund policy you won't get your items back sorry.
