### ISSUE TITLE
Map Bug?

### ISSUE THREAD

**Issue by Coffeebean30** [Wynncraft/Issues#8229]
So the map isn't showing my world number or my party currently online

**Comment by 1Glaicer1** [comment]
I m having error on the map i cant see my player =[ PLZ HELP FAST ! if u can!

**Comment by thecoolkogut4** [comment]
All cross server communications are down, as a result the map is also down. Give it a few hours and it should be back up and running.

**Comment by 1Glaicer1** [comment]
o Thx for the reply =D

**Comment by 1Glaicer1** [comment]
its been 3h still samee Plz reply

**Comment by thecoolkogut4** [comment]
Give it some time

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
