### ISSUE TITLE
Buying from the store and not getting them in game!

### ISSUE THREAD

**Issue by CityBlockHazard** [Wynncraft/Issues#8231]
I payed for the vip 1 package yesterday and still have not received it in game, might be a bug not sure but I have the paypal transaction and my character name. hope this gets looked at soon.

Thanks looking forward to my vip1

**Comment by thecoolkogut4** [comment]
For any store related issues, email support@wynncraft.com with your IGN, transaction ID, and your problem

**Comment by CityBlockHazard** [comment]
I emailed them yesterday and with all the info and still have not gotten an answer back, still a bug that might want to be checked. it happens thats why I am not to mad about it,

**Comment by LordHelmchen98** [comment]
I assume you got a mail now. Usually it doesn't take long but the support is not able to be online 24/7.
