### ISSUE TITLE
Game crashes when in lobby

### ISSUE THREAD

**Issue by MidgetMagic** [Wynncraft/Issues#8232]
The server allows me to log in and walk around but after trying to use the lobby or server select items the game crashes. I have logged in on other computers and it works so i know that it is not a account problem.

I am thinking it must be a file error of some sort. I have tried reinstalling minecraft but have had no luck

Has anyone else had this problem?

**Comment by thecoolkogut4** [comment]
Can you join other servers on the same computer?

**Comment by MidgetMagic** [comment]
I just tried and it crashed just starting another server, i didn't even log in all the way.

**Comment by thecoolkogut4** [comment]
What happend when you reinstall mc? 

Ate you using any mods? What happend if you connect without them?

**Comment by MidgetMagic** [comment]
I do not currently have any mods. 

After reinstalling mc the problems still occurs as before.  I even downloaded a different virus software the second time thinking maybe it was blocking something.

**Comment by MidgetMagic** [comment]
I am currently running version 1.11.12 if that matters.

**Comment by thecoolkogut4** [comment]
Well, from what you've said it seems like your computers the problem.  Try doing a software update.

**Comment by MidgetMagic** [comment]
I will try that next, i appreciate the quick response.

**Comment by thecoolkogut4** [comment]
No problem, at me know how it goes! Also, are you able to run other games on your computer?

**Comment by MidgetMagic** [comment]
Yes other games work.

After installing an update on the computer i restarted mc and it crashed but told me there was a java update this time. However, it did not fix the issue. I thought for sure a java update sounded like the culprit but i was wrong.

**Comment by thecoolkogut4** [comment]
I'm not too sure on what to do, sorry.

**Comment by ittnoraA** [comment]
To me it sounds like you're missing the server resource packs folder, which results in crashing upon trying to load the wynnpack. I'd recommend to open up your **.minecraft** folder from your computers **%appdata%** and check for a folder called **server-resource-packs**. If it doesn't exist, create one and try logging in again.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
