### ISSUE TITLE
Glitching blocks+weapons in 1.11.2

### ISSUE THREAD

**Issue by Apocrophon** [Wynncraft/Issues#8233]
I logged in and my weapons were like this: http://prntscr.com/fc8240

i moved around to see if the buffs worked, and saw this: http://prntscr.com/fc82hp

**Comment by ittnoraA** [comment]
Just relog and the pack should be fixed.

**Comment by thecoolkogut4** [comment]
Delete the resource pack in your server resource pack folder, then join the server again and download the pack that should fix it.

**Comment by Apocrophon** [comment]
Yeah, that worked

**Comment by Apocrophon** [comment]
alright, thanks
