### ISSUE TITLE
Map not working. Help please!!!

### ISSUE THREAD

**Issue by Sumo243** [Wynncraft/Issues#8236]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

I am not on the map and I don't know why. It worked a few days ago

**Comment by thecoolkogut4** [comment]
this is a temporary error, and it should get fixed soon

**Comment by Sumo243** [comment]
Ok thankyou

**Comment by LordHelmchen98** [comment]
It should work again (at least it does for me).
Sometimes it breaks for a bit, but usually it doesnt take too long until its fixed.
