### ISSUE TITLE
Fantastic Voyage - Didn't get the explosive to explode the boulder

### ISSUE THREAD

**Issue by MrRedCrack** [Wynncraft/Issues#8237]
When the quest dialogue said I've crafted the explosive, I didn't get it. I've used /fixquests but still didnt get it :/ help! im stuck in the quest area D:

**Comment by thecoolkogut4** [comment]
Switch worlds ans it should spawn. Make sure your at the right spot!

**Comment by MrRedCrack** [comment]
by the right spot you mean where?

**Comment by thecoolkogut4** [comment]
Where the cannon ball spawns

**Comment by MrRedCrack** [comment]
cannon ball? I'm at the stage where you need to craft the explosive from sand, sawdust and stuffs
and explode the boulder to get into a cave

**Comment by MrRedCrack** [comment]
I've shoved the ingredients into the crafting table and it said I have crafted one, but it didnt show up in my inv

**Comment by thecoolkogut4** [comment]
Whoops I thought you were at that part, my bad. what does your quest book say?

**Comment by MrRedCrack** [comment]
Use the explosive on the boulder.

**Comment by MrRedCrack** [comment]
How do I get the explosive now as there seems to be no other ways to get another one ;-;

**Comment by thecoolkogut4** [comment]
So you don't have it in your inv and /fixquests won't work. Try switching servers

**Comment by MrRedCrack** [comment]
turns out i didnt need the item, i just needed to press the button... -.-
