### ISSUE TITLE
Map error, Not Showing player 

### ISSUE THREAD

**Issue by 1Glaicer1** [Wynncraft/Issues#8238]
Helo i m 1Glaicer1 its been 1 day scince this happened and i cant see my player i m hoping that u can fix this error quick

**Comment by colin350** [comment]
This has been known for awhile, and cannot tell you the date of which it'll be fixed. Please note you aren't the only one in this position, and will have to be patient until it is fixed. For now, use coordinates and the wiki (wiki.wynncraft.com) to help you. That's how it used to work in the old days.
