### ISSUE TITLE
Decrepit Sewers 

### ISSUE THREAD

**Issue by MrKarthus** [Wynncraft/Issues#8239]
i think this should be a bug. there is something make me cant enter the boss room. But others can. And change world or lobby doesn't work
![2017-05-26_18 38 13](https://cloud.githubusercontent.com/assets/28990605/26514915/6aa986f6-4243-11e7-81bc-6ccc599ca329.png)

**Comment by Moe-Ronickah** [comment]
Have you tried changing versions of MC, or do you remember which version you were using at the time?

**Comment by jtwilson0715** [comment]
I had this same issue on 1.12. Me and my friend had to kill ourselves to leave the dang dungeon...

**Comment by LordHelmchen98** [comment]
Wynncraft is hardcoded for 1.8 so that's the version with least bugs and glitches. 1.9 is fine as well, but higher version often cause issues in Wynncraft. So in all likelihood that's probably your problem here.
