### ISSUE TITLE
I accidentally tossed my BOB'S MYTHIC BOW into a hopper and now it is gone... Is there anyway to get it back, or can someone give one to me (I'm desperate)?

### ISSUE THREAD

**Issue by ryanes23** [Wynncraft/Issues#8241]
Is there anyway to get my bow back? Can a mod or admin or someone give it back to me?

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.
