### ISSUE TITLE
Texture incorrect for steampunk flair

### ISSUE THREAD

**Issue by TheLimeGlass** [Wynncraft/Issues#8243]
The texture for the steampunk flair on my spear makes an incorrect purple and black texture.

![2017-05-27_00 08 40](https://cloud.githubusercontent.com/assets/16087552/26518604/b97e1990-4270-11e7-8493-749ec720eb60.png)
![2017-05-26_23 50 24](https://cloud.githubusercontent.com/assets/16087552/26518605/bab70c36-4270-11e7-9c9f-eb93b6abb1a2.png)

**Comment by thecoolkogut4** [comment]
I'm going to assume your in mc mc version 1.8.X, to fix this big join on 1.9 and up
