### ISSUE TITLE
Quest Bug Wrath of the Mummy

### ISSUE THREAD

**Issue by basketballbro123** [Wynncraft/Issues#8244]
I had some pink wool required for the quest and the bandit took it as normal but my quest book refuses to move on past the step 'talk to the bandit preventing you from entering' someone please help I cant progress in the quest

**Comment by colin350** [comment]
Not sure of the quest book updates, have you tried to enter the tomb?
https://wiki.wynncraft.com/index.php?title=Wrath_of_the_Mummy

**Comment by basketballbro123** [comment]
yes it allows me through no problem but doesn't count in my book

**Comment by basketballbro123** [comment]
I FIXED IT YAYYYY I just brought him a second piece of wool and that fixed it
