### ISSUE TITLE
Texture Bug

### ISSUE THREAD

**Issue by DiamondmodMC** [Wynncraft/Issues#8245]
It may or may not be a bug, but for me the Mesarock Arch bow texture, it's incorrect. I'm also using mc version 1.11+ so I don't know why this is not textured as a bow. :P
![2017-05-27_16 57 23](https://cloud.githubusercontent.com/assets/28997594/26520048/bcad013e-42fd-11e7-902a-9c2979bd7ffd.png)

**Comment by Vosgess** [comment]
Switch into 1.8.9 it's ok ^^

**Comment by DiamondmodMC** [comment]
Alright, thanks! It worked! ^.^
