### ISSUE TITLE
Lost Sanctuary Dungeon

### ISSUE THREAD

**Issue by mrmiijo** [Wynncraft/Issues#8246]
I had a key from Lost Sanctuary Dungeon. I go to this dungeon. But there is a barrier on the bridge and I can't continue. I also watched the video on the wiki, but in video, after the killing of the two protectors, barrier disappeared. What should I do? I do not have another key and I want the dungeon to pass. Thanks

Sorry for my bad english.

**Comment by LordHelmchen98** [comment]
If you are still in the dungeon try to do it on different server.
Other than that I didnt hear of anything that may help so far.
Also which MC version did you use when you tried to do the dungeon?

**Comment by mrmiijo** [comment]
I joined to a different server - world, but after it, I wasn't in the dungeon.
I used mc 1.11.2.

**Comment by colin350** [comment]
Please try using version 1.8.9.

**Comment by mrmiijo** [comment]
What's the difference between the versions? It has nothing to do with the barrier.

**Comment by qq413759591** [comment]
I also have this bug before. I throw away all TNT items for this dungeon in my inventory and now I can go through the bridge(also change the server).

**Comment by colin350** [comment]
@mrmiijo it is related to the barrier. Barrier mechanics are different in 1.9+ and Wynncraft is hardcoded to 1.8.9. Therefore, I suggest using 1.8.9. 

It also has been ~22 days without a response to this issue, so I'll assume it is fixed.
