### ISSUE TITLE
Meaningful Holiday bug

### ISSUE THREAD

**Issue by Sumo243** [Wynncraft/Issues#8251]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.
So I got to Ternaves but I can't talk to the guy I need to talk to ( Reshad). I don't know if it is a buy on my end or on the server end but I can't do the quest unless I can talk to this guy. Please help me

**Comment by thecoolkogut4** [comment]
Click him from various angles, you need to click him in the right spot. It takes about 30 sec to get it right.

**Comment by Sumo243** [comment]
Ok i'll try right now!

**Comment by Sumo243** [comment]
It worked! Thanks
