### ISSUE TITLE
I can't move the hay bales in ???

### ISSUE THREAD

**Issue by MrRedCrack** [Wynncraft/Issues#8253]
I kill the farmer, get the hay sickle, tried to move the hay bales but the dont respond to anything. Switched to multiple other servers, dropped out the hay sickle in my hand, kill the farmer again and get another one, and repeat, still, nothing happens.

This is making me frustrated

**Comment by colin350** [comment]
I have encountered this issue before by not playing on 1.8.9. Try switching versions, and try again. Wynn is hardcoded to 1.8.9, so when in doubt, switch versions.
