### ISSUE TITLE
The Shadow Of The Beast (Hazel)

### ISSUE THREAD

**Issue by TounyPlay** [Wynncraft/Issues#8254]
Why can't I talk to Hazel?

**Comment by Pyromanical** [comment]
What does your quest book say?

**Comment by TounyPlay** [comment]
"Follow the Footprints to find another victim of the beast"

**Comment by ChigoMinecraft** [comment]
https://wiki.wynncraft.com/index.php?title=The_Shadow_of_the_Beast

Hazel is for a different quest.
