### ISSUE TITLE
I got stuck in the wall!!!

### ISSUE THREAD

**Issue by DeadPirate** [Wynncraft/Issues#8255]
Hello,I have a problem. In the first dungeon I was stuck in the ceiling after the restart of server.. there's nothing I can do.. 
Well,get me out somehow :D 
My nickname Dead_Pirate
![2017-05-28_20 08 52](https://cloud.githubusercontent.com/assets/29018647/26529896/c3a884aa-43e2-11e7-90ca-1c84e142729b.png)
![2017-05-28_20 08 59](https://cloud.githubusercontent.com/assets/29018647/26529897/c3ac8bfe-43e2-11e7-9c46-6aad3e78ee19.png)
![2017-05-28_20 09 07](https://cloud.githubusercontent.com/assets/29018647/26529898/c3b0383a-43e2-11e7-9b3e-d3842276de15.png)
![2017-05-28_20 09 10](https://cloud.githubusercontent.com/assets/29018647/26529899/c3b6e644-43e2-11e7-8e39-80d7f0b76d4e.png)

**Comment by DeadPirate** [comment]
If you need my presence,you agree with the Moscow Time

**Comment by colin350** [comment]
`/kill` with five or more soul points.

Thank you for reporting the hole.
