### ISSUE TITLE
Teleport glitch

### ISSUE THREAD

**Issue by MisterFantaztic** [Wynncraft/Issues#8256]
My friend and I were doing the Infested Pit Dungeon, and at the end of the parkour he used the teleport spell, and ended up glitched inside of a block in the wall. He can't teleport out using the spell and his town scroll won't work. Logging out doesn't help, he couldn't die because nothing could hit him, and the server restarting didn't do anything. His username is LOBES1 and if there is some way you can teleport him back to Ragni or something like that it would be super appreciated.

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by MisterFantaztic** [comment]
Thank you!
