### ISSUE TITLE
Guild Attacks Not Working

### ISSUE THREAD

**Issue by bepic12** [Wynncraft/Issues#8257]
While trying to attack a guild territory, after the countdown had finished my guild members were not teleported to the fight. When trying to attack again, it only gave us the message, "Your guild is already in battle."

**Comment by thecoolkogut4** [comment]
Guilds are very buggy and this is also a well known issue. They are devs are aware and they are going to be recoding the entire guild system.

**Comment by LordHelmchen98** [comment]
As @thecoolkogut4 already said, guilds are really glitched and the code is pretty old. They will get fixed, but unfortunately there is no estimated date for that.
