### ISSUE TITLE
Started out at level 17

### ISSUE THREAD

**Issue by Barnabi20** [Wynncraft/Issues#8258]
I got on the server for the very first time a few minutes ago. I didn't go through any tutorial or anything. I spawned into the world and started attacking things and it felt way too easy. I used the compass to check my stats and realized my mage class was level 17 and had 30 skill points available.

**Comment by ittnoraA** [comment]
It sounds like you might have played on the server a few years ago and forgot it afterwards. Another explanation would be that someone figured out your password and used your account to play wynn. Perhaps it might've been someone who lives with you?
