### ISSUE TITLE
Class picking: There has been an error... Try again

### ISSUE THREAD

**Issue by DudePerson** [Wynncraft/Issues#8259]
I am a new player that has been trying to get started, but unfortunately, I've been getting an error every time I try to pick a class. It tells me "There has been an error.. Try again"
![2017-05-28_22 10 12](https://cloud.githubusercontent.com/assets/29024999/26535407/b71efce0-43f2-11e7-91dd-6a1fc98320f4.png)

**Comment by LordHelmchen98** [comment]
Does this happen no matter which class you try to pick? Also whats your ingame name?

**Comment by DudePerson** [comment]
Yes, also my IGN is TheXZone

**Comment by LordHelmchen98** [comment]
Well I would lead you to #7185, but I saw you found that thread already.
As you probably saw there, the only way to get rid of that issue is to wipe all of the player data and as you never played on Wynncraft I guess you have absolutely nothing to loose.
