### ISSUE TITLE
boat glich

### ISSUE THREAD

**Issue by nicknico** [Wynncraft/Issues#8260]
when i was sailing away on my boat the server restarted but when i joined back my boat was gone and now i'm stuck, and lost 128$. fix this please. thank you for reading.

**Comment by LordHelmchen98** [comment]
It shouldnt be too hard to get 128emeralds/2emerald blocks again. Also if you try to get anywhere specific I recommend the use of the Seaskipper.
Anyway boats are supposed to get back to your inventory, but this only works if the server detects that you get off your boat and that doesnt happend if the server restarts.
Therefore if you use your boat and see that the server restarts, you should get off the boat in future.
