### ISSUE TITLE
Friend and I are stuck in the wall after using a bed....

### ISSUE THREAD

**Issue by jspizz12** [Wynncraft/Issues#8261]
We used a bed in an INN and leaving the bed put us in the wall in a tight 1 by 1 block area and we cannot use teleportation scrolls to leave it... please help us get out of this predicament for we only just reached level 25 on our characters and it would suck to have to make new ones.

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!
