### ISSUE TITLE
Double Pet Extravaganza 

### ISSUE THREAD

**Issue by Nethertaker** [Wynncraft/Issues#8263]
Due to pets being cosmetic, this isn't "literally unplayable", but it still freaked me out.
when i logged in, I had my creeper spawned, and when i wanted to rename my new wybel I wanted to despawn it.
However, when i got to the pet menu, it said "spawn Grim [Creeper]".
After clicking it, I now have a duplicate pet.
Pressing despawn and respawn just does that to the duplicate 

???
Pic:
![image](https://cloud.githubusercontent.com/assets/18089634/26558081/bbc6d280-446b-11e7-94f0-96d588aa8881.png)

**Comment by Natooniel** [comment]
Nethertaker, although this "extravaganza" is surely mysterious, there is really no harm. I mean, look on the bright side; you get a free pet. If this truly does bother you, having 3 pets, try disabling the Wybel and just stick with 2 creepers. Good luck!

-Natooniel

**Comment by LordHelmchen98** [comment]
Sometimes if you had your pet spawned you get a duplicate if you join another server.
You should be able to fix that by switching servers again.
Then you will be able to rename your pets again.
