### ISSUE TITLE
Detlas' Legacy

### ISSUE THREAD

**Issue by Pendragon009** [Wynncraft/Issues#8265]
my detlas' legacy randomly dissapeared from my hand and was replaced by an oak stick it very upset me as   
that was pretty much my only powerful weapon i'm now back to using Sketiq (i'm currently a level 26)

**Comment by ittnoraA** [comment]
Hey! Unfortunately there is a strict "no refunds"-policy in Wynn, which means you're not getting your wand back. If you really want another one, you could try making a thread about it on the forums' trading section at https://forums.wynncraft.com/forums/trade-market.71/
