### ISSUE TITLE
Maltic Reccomendation Letter (Quest Item) Dissapearence!

### ISSUE THREAD

**Issue by Natooniel** [Wynncraft/Issues#8267]
Hello, as of about a year ago I was level 20 and had just completed the Maltic's Well quest when the Maltic Recommendation Letter disappeared. As a beginner I thought little of it. Yet "what goes up must come down" and I found myself, a year later, struggling to start the Temple of Legends quest, and mysteriously missing my Maltic Recommendation Letter. I have no way of retrieving it, as I have already finished the quest. If you have any info, please help me!

**Comment by ittnoraA** [comment]
Heya! There is a command, /fixquests which retrieves lost quest items.

**Comment by Natooniel** [comment]
Thanks so much!
