### ISSUE TITLE
Wynncraft Ressourcepack makes my game laggy

### ISSUE THREAD

**Issue by lordofsalts** [Wynncraft/Issues#8269]
Hi there,

my game starts lagging after a while when I use the Wynncraft ressource pack. When I join a server it's fine and it starts lagging more and more. The game is litrally unplayable after ~15 minutes. 

I have a pretty good PC so I don't think its my Computers fault. Aynway, here are the relevant data:
- Intel i5-6500
- 16 GB Ram
- Nvidia GTX 980 Ti
- Windows 10 64x

What I already tried:
- I downloaded the ressource pack and played with it locally -> Takes 20 min till unplayable
- played WITHOUT any ressource pack -> can play for hours without lags
- relogging to hub / changing server -> resets Lags
- when I press F3 to look at the memory it just stays beween 2% and 7% (I have allocated 12GB)
- I tried to lower my graphic specs or to use optiFine -> no changes

Do you guys have any ideas, please? I like playing Wynncraft but cannot with these lags.

Thank you in advance.

Best regards.
Lord_of_Salts

**Comment by ittnoraA** [comment]
To me it just sounds like your render distance is way too high. This results in your performance being great when you start, but eventually the fps starts dropping as more and more chunks get loaded without getting unloaded. 

Of course, using any resource pack will make your game a small bit slower since it's loading textures from several folders, but even the wynnpack shouldn't cause too horrific lag. Do other texture packs cause any lag for you? What about using other versions of minecraft?

**Comment by lordofsalts** [comment]
Thank you for the reply, I just found a solution to the problem.

When I played yesterday I noticed that the more entites are loaded into the game the slower the game gets. And when I tried to play without ressource pack I didnt have the problem so it must have been related to how the mc clients loads the ressource pack from the server. When I mentioned in my description that I used an downloaded rssource pack it was the 64x pack from somebody else who merged it together not the original one. 

So I downloaded the ORIGNAL Wynncraft ressourcepack from the server to use it locally and it worked for me.

Description How To:
When you navigate to the minecraft folder there is a folder server-ressource packs (sth like that, i am not at my computer) there are some files with random names. If you delete all and connect again to wynncraft and accept downloading the texture pack the only file there is the original Wynncraft Texture Pack. Of course you will need to manipulate the file to a .zip since it is only saved as "file" if you do this and copy it to your ressource pack folder and load it and disable using the one from the server everything works fine.

Its a sad story that you can't find the texturepack by searching on wynncraft since this problem exists. I also gave the packs to serval of my friends and they are happy with the new performance.

**Comment by LordHelmchen98** [comment]
@lordofsalts well its not that obviou, but actually you are able to find some information, download instructions and even a download link [here](https://github.com/Wynncraft/Issues).

**Comment by lordofsalts** [comment]
@LordHelmchen98 Oh, thank you! Even Dr. Google didn't show me those. :(
