### ISSUE TITLE
Bugged helmet

### ISSUE THREAD

**Issue by PoloTooth** [Wynncraft/Issues#8270]
I've got a helmet that is unidentified but when i try to get it identified it says: "I can't identify this item! It can not be reidentified" but i can't wear it due to it being unidentified. Is there any way to fix this?

**Comment by colin350** [comment]
Unfortunately there is nothing we can do to refund the item (e.g give you a replacement identifiable item), however, it would be an extreme help to us if you could attach a few images to this issue!
Thanks!
