### ISSUE TITLE
Lost my Az

### ISSUE THREAD

**Issue by Cenpyla** [Wynncraft/Issues#8272]
I was doing the Ice Barrows dungeon and I was on Phase 6 collecting tokens, and I accidentally dropped my Az (with two t6 thunder powders) into the hopper.

I don't know if this counts as a bug, but I don't have enough LE to buy a new Az. 

Is it possible for me to get it back?

**Comment by RubbrDucky** [comment]
sorry, wynn has a strict no refund policy

maybe next time use the wynn enhanced mod? it has item locks

**Comment by RubbrDucky** [comment]
and is 100% legal

**Comment by LordHelmchen98** [comment]
Im sorry for your loss, but as already said Wynncraft enforces a strict norefund policy.
You should maybe also think of rebinding your drop key.
