### ISSUE TITLE
Can't finish Lost Soles and WynnExcavation Site D cause of missing items that have been deleted...

### ISSUE THREAD

**Issue by MInecraftacrylic** [Wynncraft/Issues#8274]
1. Lost Soles:
The Lost Soles quest on my mage account. Basically, Abysso Galoshes got deleted after giving the boots to Ferndor. After he returns the boots, I picked up some emeralds, and my inventory was full thus, the boots was deleted, thus, I am not able to finish the Lost Soles quest.

2. WynnExcavation Site D:
The The WynnExcavation Site D quest on my assassin account. Basically, I am not able to finish the quest as when I talk to the Traitor Amadel, I didn't receive the dialogue that I was meant to get, I might have lost the map.

**Comment by ittnoraA** [comment]
Heya! There is a command, /fixquests which retrieves lost quest items.
