### ISSUE TITLE
Incorrect names for item JSON keys

### ISSUE THREAD

**Issue by 1blustone** [Wynncraft/Issues#8276]
I've been looking through the API, and [this](https://github.com/1blustone/wynn-model-viewer/blob/master/wynn-common.py) Python program I wrote made me aware of the fact that there are two oddities in key naming, both of which make it difficult to write a program that relies on the API.

There exist, for the items "Scroll of Nythiar" and "Yverlian Blade," two likely incorrectly named keys for the `material` property - namely, `materiaL` and `materials`. These are the only items to have these properties, which indicates that it is extremely likely to have been a mistake.

For reference:
<pre>{"name":"Yverlian Blade","tier":"Unique", ... "<b>materials</b>":"171:15","fireDamage":"23-50", ... }</pre>

<pre>{"name":"Scroll of Nythiar","tier":"Rare", ... "<b>materiaL</b>":"126:4","damage":"0-0", ... }</pre>

Can this be fixed? It is difficult and sometimes impossible to parse JSON output with inconsistent results.

[Script output for reference, near the bottom](https://pastebin.com/3cWdMSAA)

**Comment by thecoolkogut4** [comment]
Duplicate #8148 #8147

**Comment by 1blustone** [comment]
...except it still isn't fixed.

**Comment by colin350** [comment]
Currently only Jumla and Elements has access to updating the API. I'll forward it on to Jumla, but since we are working on refactor, it may not be updated until refactor is complete. Sorry for the inconvenience!

**Comment by 1blustone** [comment]
Sure it's possible, which is what I'm currently doing, but this sort of issue _should_ be avoidable, as frameworks like Gson serialize objects according to their actual field values.

Thanks anyway, looking forward to a possible fix in the distant future
