### ISSUE TITLE
No item names.

### ISSUE THREAD

**Issue by Kibbles0121** [Wynncraft/Issues#8277]
It's a small issue, yes. And it shouldn't be that big of a deal, but if you're like me, you enjoy grouping a large number of enemies together and hitting them with a devastating AoE attack, like the Assassins spin attack. I'd like to know what I'm picking up while on the field, and not having to open my inventory to see if I got an unidentified item, or just some trash item. Is there a way to fix this? It seems random on when it wants to work.

**Comment by LordHelmchen98** [comment]
Which item names? Are you using any modpacks?
If so thats an issue which is not supposed to be here on GitHub as Wynncraft has no official modpacks just fanmade ones. Instead ask on the respective threads on the forums.
If not please specify your issue.
