### ISSUE TITLE
wrong amount of mana/hunger

### ISSUE THREAD

**Issue by WiggleGhast** [Wynncraft/Issues#8278]
with the archer class if you use the arrow storm ability it consumes 6 mana/hunger while on the help page of the class it says 4. same with the escape ability. when you use it it consumes 3(building up when you use it multiple times in a row) but on the help page it just says 2. maybe there's something wrong with the other abilities/help pages as well but this is what i could find.

**Comment by DJNothing** [comment]
Help page is outdated.
And thats known since gavel released

**Comment by LordHelmchen98** [comment]
There are some other things on the help page which are outdated. Let's hope this will get updated in future.
