### ISSUE TITLE
Guild(gr8 meme) contribute taking LE

### ISSUE THREAD

**Issue by DJNothing** [Wynncraft/Issues#8279]
Contributing emeralds into the guild can cause the emeralds to disappear if you close the window where you put your emeralds in with E. happened to me with a stack of LE but was reproducable easy with 1 e.
also ik about no refund and that guilds are buggy in general

**Comment by thecoolkogut4** [comment]
This has been an issue for a long time. I've also lost stacks of LE due to this. Also, if you add more then 8 stacks of eb, eme, or LE it will not get added to the guild

**Comment by colin350** [comment]
#3665 for further reports...
