### ISSUE TITLE
Spelling mistake *Not a grammar Nazi*

### ISSUE THREAD

**Issue by ZeUnlucky** [Wynncraft/Issues#8280]
Welp, I just did quests and such, and I saw this:
![2017-06-01_11 54 35](https://cloud.githubusercontent.com/assets/28901862/26672296/50cdae74-46c1-11e7-9225-75261ca18a23.png)

As you can see, she's saying (4/6) where it don't belong, where she should say where it Doesn't belong. Im pretty sure this is the correct way to say it. My main language is not English, so if I'm wrong, I'm sorry, but I really do think they messed this up.

P.S. Don't mind me chatting to my friend up there ^-^

**Comment by Imaxe** [comment]
Thanks for reporting this issue. It has now been fixed, it will be online when we update :)
