### ISSUE TITLE
Lacrona doesn't say anything

### ISSUE THREAD

**Issue by TomD011099** [Wynncraft/Issues#8282]
I was going to start the suspended flowers quest, but Lacrona doesn't say anuthing. The quest does start and I know I can read what Lacrona said on the wiki. I've changed server (not in the video) but that doesn't work either.

https://youtu.be/1rtc18E7pG0

**Comment by LordHelmchen98** [comment]
What does your questbook say?

**Comment by TomD011099** [comment]
My questbook updated as usual, I completed the quest, but it's just inconvenient

**Comment by LordHelmchen98** [comment]
Alright then I assume Lacrona didnt talk to you because you already started the quest. Some NPCs just give you an empty line if you try to talk to them again, but your book should still tell you what to do next.
