### ISSUE TITLE
a junk food npc do not work

### ISSUE THREAD

**Issue by Spooown** [Wynncraft/Issues#8284]
I would like to sell 'ocelot tail' but it does not work.
There is written the basic name  ( Blaze rod, bone meal) 
:/

**Comment by LordHelmchen98** [comment]
Can you please sent the coordinates of that merchant and maybe a screen of the items?

**Comment by Spooown** [comment]
It's ok, correct names displayed again, i do'nt understand ^^

**Comment by LordHelmchen98** [comment]
Alright ,then I guess/hope it was a one time issue.
