### ISSUE TITLE
The house of Twain quest Beast eyes

### ISSUE THREAD

**Issue by TyphlosionPlays** [Wynncraft/Issues#8286]
I figured out that you need to drop an emerald or an item into the beasts eyes for the quest, but I cant for both i can drop it in the right eye but not the left so i am a bit confused. If you could fix it as soon as possible that would be great thanks, im in lobby 18 if it is just this lobby. <3

**Comment by thecoolkogut4** [comment]
Try switching worlds, that should fix it.
