### ISSUE TITLE
curse hissing please use curse

### ISSUE THREAD

**Issue by bikuta211** [Wynncraft/Issues#8287]
im using twitch app that i can only find when trying to find to download cursed but now that i have the app i try to play wynncarft enchanted and when i log in i get the message (curse hissing pleas use curse) i have no idea whats happening or how to get rid of the message pleas help

**Comment by thecoolkogut4** [comment]
This github is where you report bugs/issues on the official Wynncraft network. Wynncraft enhanced is not official so if you have an issue with that, you would need to speak to the mod developer. (Which would most likely be on the forums thread)

**Comment by ittnoraA** [comment]
Please post any bugs related to the modpack on this thread: https://forums.wynncraft.com/threads/unofficial-custom-modpack-❀-wynncraft-enhanced-❀-party-hp-display-custom-worldmap-more.139677/page-130#post-2290334
