### ISSUE TITLE
Missing Quest Item

### ISSUE THREAD

**Issue by jla619** [Wynncraft/Issues#8288]
I know this is somewhat of a regular occurrence, as I see on multiple issues, so I'll get straight to the point. I'm missing my Mummy's Bandage for the quest, "Temple of Legends." No matter if I spam /fixquests, it does not return and I only have one class. I recall that I think I might have somehow threw it out, but foolishly thinking that /fixquests would work on it.

**Comment by LordHelmchen98** [comment]
Did you really check everywhere (class **and** bank)?

**Comment by jla619** [comment]
Yes, I checked multiple times.
