### ISSUE TITLE
Stuck in a prison/jail in gavel, dont know how i got stuck, but i just am

### ISSUE THREAD

**Issue by ItsADoge** [Wynncraft/Issues#8289]
I was trying to do the pirates trove quest, and when going around I got the 2nd clue, i thought it meant going to the prison, i went up to the prison, looked around and tried to leave, when i stepped on the pressure plate infront of the door with a sign above it saying "Exit" i immeadiatly got put into a jail cell, with no warning/no text appearing, and i cant leave, need help, thanks

**Comment by ItsADoge** [comment]
![2017-06-02_11 58 39](https://cloud.githubusercontent.com/assets/29149629/26736273/007cdc18-478b-11e7-8ebd-239d6937b453.png)

**Comment by LordHelmchen98** [comment]
In order to get out you could either use a scroll in case you have one or do `/kill` with more than 5 soul points.
