### ISSUE TITLE
i'm stuck 

### ISSUE THREAD

**Issue by KingRid0102** [Wynncraft/Issues#8293]
hey can any admin help me i used my tp spell and i got stuck i'm in the dwellin walls quest and i got stuck i lost my stick by mistake and i can't move

**Comment by LordHelmchen98** [comment]
Im sorry for your loss, but Wynncraft enforces a strict norefund policy. Therefore you wont get your wand back.
In order to get out you can do `/kill` with more than 5 soul points.

**Comment by KingRid0102** [comment]
okay i don't need my wand back xDD
