### ISSUE TITLE
Wynncraft accessories

### ISSUE THREAD

**Issue by bookwrom** [Wynncraft/Issues#8294]
My user does not allow me to equip accesories  such as rings and amulets. This issue seems to be unique to my user since i have friends who also play Wynncraft yet they are able to equip rings and the like. Advice please?

**Comment by thecoolkogut4** [comment]
Some of them have specific requirements in order to equip them. Eg; you must be level x+, you must have y Skill points in z, you must have completed b quest. Etc. What rings are you trying to put on?

**Comment by bookwrom** [comment]
No i am referring to all accesories and all of the ones i try to put on have their requirements fulfilled.

**Comment by LordHelmchen98** [comment]
Which mc version are you using? If you are using 1.10 or 1.11 can you try if it works on 1.8 or 1.9?

**Comment by bookwrom** [comment]
i will try that

**Comment by bookwrom** [comment]
I have tried it and it does not work

**Comment by thecoolkogut4** [comment]
Is there an error message in chat when you try to put it on? What ring are you trying?

**Comment by bookwrom** [comment]
no there is no error message and it is not limited to rings it is amulets and the such too

**Comment by LordHelmchen98** [comment]
Do you have a way to record and upload that? Maybe that could help us solve the problem.

**Comment by bookwrom** [comment]
um....How to record on a mac?

**Comment by LordHelmchen98** [comment]
I dont use a mac so its different for me, but in [this vid](https://youtu.be/to2FX2VdOHU) a guy shows how he records videos for youtube.

**Comment by bookwrom** [comment]
i will use a phone

**Comment by bookwrom** [comment]
god that looks complicated

**Comment by thecoolkogut4** [comment]
Open up QuickTime player (default app/comes with your mac) go to file > new screen recording > click the red dot > click your screen >> I'm sure you can figure the rest out from here

**Comment by atenfyr** [comment]
Can confirm. ^
