### ISSUE TITLE
My morph gold boots just disappeared

### ISSUE THREAD

**Issue by RprRogue** [Wynncraft/Issues#8295]
I was moving them around my inventory when server restarted, now they are gone, can I have a refund? I just lost my main piece of armour

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by RprRogue** [comment]
so what do I do? I have no boots

**Comment by thecoolkogut4** [comment]
You can buy boots from a merchant, from a player, or you can grind to get new boots.
