### ISSUE TITLE
stuck in boss room of fallen factory

### ISSUE THREAD

**Issue by selene66** [Wynncraft/Issues#8296]
not much to say, I beat the boss but I didn't leave the room... idk how to do reproduce the problem, I was killing boss and his minions with phoenix wing and meteor spam.

![2017-06-03_14 53 24](https://cloud.githubusercontent.com/assets/29168231/26757336/61080ed0-486d-11e7-8d04-333817dbf444.png)

**Comment by CaptainJLPv2** [comment]
This has also happened to me as well.
The Boss didn't respawn, so i used /hub to find a new lobby to go to and then i was kicked out of the dungeon for what i think was supposed to be a combat-log related thing.
In this screenshot i was using the Wynncraft Enhanced Modpack.
![2017-07-09_22 13 00](https://user-images.githubusercontent.com/28000844/27993934-0a2e5b8c-64f6-11e7-8070-96d0030ca22c.png)

**Comment by LordHelmchen98** [comment]
Sometimes you don't get teleported out of a dungeon although you killed the boss. If that happens don't leave or do /class as that would kick you out of the dungeon. Just wait until it respawns and kill the boss again. Sometimes this happens more than once, but you should get teleport or if the dungeon eventually.
