### ISSUE TITLE
My totems broke

### ISSUE THREAD

**Issue by CrimsonWybel** [Wynncraft/Issues#8298]
Ok i logged in going to start leveling my assassin again from when i logged off last night i log on i got to place a totem and bam i had 8 totems somehow is this bad or what should i do just use them (well i used almost all them already but making this after i finished grinding for a while) so what should i do if it happens againthank you for your time p.s wynncraft is the best server ever

**Comment by CrimsonWybel** [comment]
should i just use them all or?!?!?!?

**Comment by LordHelmchen98** [comment]
Did you buy a rank?
Anyway use them and be a happy I guess. If you used them all and still have 8 the next day report back please.

**Comment by CrimsonWybel** [comment]
kk will do
