### ISSUE TITLE
Lost Item When I Skill Point Reset

### ISSUE THREAD

**Issue by lunes8** [Wynncraft/Issues#8300]
I absent mindedly reset my skill points to put on a pair of new leggings that needed intelligence 30. However, since I had no space in my inventory, my legendary boots Anchoryl asked 3 times for 25 of defense skill then disappeared.

**Comment by LordHelmchen98** [comment]
Im  sorry for your loss, but Wynncraft enforces a strict norefund policy. Therefore you wont get your boots back.
