### ISSUE TITLE
Potion Making

### ISSUE THREAD

**Issue by Flameslinger787** [Wynncraft/Issues#8301]
During the potion making quest, i brought the apprentice [8 red mushrooms]. My quest book updated and he told me to go kill the witch. However, i went into the boss room, but there was no witch. I spoke to the apprentice again, and he is asking for [8 red mushrooms]. I gathered 8 but he will not accept them. My quest book still says to kill the witch and bring back proof.
![2017-06-04_13 32 20](https://cloud.githubusercontent.com/assets/26472255/26763963/a6737bbc-492b-11e7-862e-b0cb46ead68f.png)
![2017-06-04_13 33 59](https://cloud.githubusercontent.com/assets/26472255/26763965/af474be2-492b-11e7-8934-5e41771c478e.png)

**Comment by LordHelmchen98** [comment]
Essren should be there if you switch to a different server and try to enter the house again.
