### ISSUE TITLE
reconnection "Forbidden Prison"

### ISSUE THREAD

**Issue by Eolyas** [Wynncraft/Issues#8303]
I have started the quest "Forbidden prison", then, after escape my cell, i quit the game for personnal reasons. After some times, I reconnect and I was at -10898 137 -12127 in the kind of place where you built the game. i moved a bit and take that screenshot.
![minecraft bug](https://cloud.githubusercontent.com/assets/25902804/26785741/3fc6a70c-4a04-11e7-8b4f-78501e94a019.PNG)
I used to play with a modpack called Wynncraft enhanced on Twitch(alias Curse) but i never had this problem before.
Can a moderator move my character to my cell ? Please.

Regards

**Comment by LordHelmchen98** [comment]
Im not sure what happened, but I assume you logged out with a block directly above you. In future take care that there is one block of air above you when you log out.
Unfortunately you will have to do `/kill` with more than 5 soul points.
Then you will have to go to the cell again.
