### ISSUE TITLE
I dont earn xp 

### ISSUE THREAD

**Issue by AlbertoManco** [Wynncraft/Issues#8304]
When i reach lvl 60 i dont earn more experience . I do quests , i farm but i dont get any exp , pls help

**Comment by ittnoraA** [comment]
Heya! You should make sure your guild XP isn't on 100%. You can do this by typing /guild xp 0 (or higher if you want to contribute a part of your earned xp to the guild you're in)

**Comment by LordHelmchen98** [comment]
@AlbertoManco Did that solve your problem?

**Comment by AlbertoManco** [comment]
yeah , thanks so much

**Comment by LordHelmchen98** [comment]
RESOLVED
