### ISSUE TITLE
Wynn Excavation Site A glitch

### ISSUE THREAD

**Issue by SquiddySlime** [Wynncraft/Issues#8305]
I was doing the Wynn Excavation Site A quest, beat the boss, went into the coal portal thing, and my questbook was updated to go and talk to the guy. When I talked to him, he says the same thing he said before I went in, and that I should give the tablet to the girl in the tent. But I already did that and went into the tomb... Can anyone help me? My username is SquiddySlime in game.

**Comment by LordHelmchen98** [comment]
The boss drops a yellow crystal. Did you pick one up? If you didnt you have to defeat the boss once more and get the drop.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
