### ISSUE TITLE
Kann wen nicht auf meiner Gilde Kicken

### ISSUE THREAD

**Issue by Nick1Z2** [Wynncraft/Issues#8307]
ich hab seit längeren eine Gilde namens Nightmare Warrior. Ich spiele in letzter zeit wider aktiv mit ein paar freunden wider und möchte die in meine Gilde einladen aber die ist fast voll und da wollte ich einen kicken aber das geht nicht . zwei Personen namens "ShadowPlays44" und "z_Liko_z" sind einfach doppelt in der liste und da wollte ich einen kicken das geht aber nicht ich weiß nicht warum bitte helft mir. wen ich /guild kick ShadowPlays44 oder /guild kick z_Liko_z dann passiert einfach nix

**Comment by thecoolkogut4** [comment]
This is a well known issue and there is currently no fix for it. All you can do is wait.

**Comment by LordHelmchen98** [comment]
Duplicate of #3665 
Hey @Nick1Z2,
unglücklicherweise haben Gilden einige Probleme. Dazu gehört dieser Glitch, bei dem Leute in einer Gilde doppelt sind und leider nicht gekickt werden können. Das wird dadurch verursacht, dass diese Personen ihren namen ändern. Leider kann das nicht so einfach gefixt werden, es sei denn du wärst bereit deine Gilde neu zu erstellen. Dazu müsstest du die Gilde verlassen bzw. wenn du die selbe neu erstellen wolltest müsstest du den chief in eurer Gilde demoten und dann die Gilde verlassen. Daraufhin wird diese gelöscht und du könntest eine neue erstellen. Gilden werden früher oder später gefixt damit dieser Glitch (und einige weitere) behoben werden kann aber bis dahin ist das die einzige Möglichkeit.

**Comment by Nick1Z2** [comment]
ah ok danke ich hab da nur das keine Problem ich und Freunde haben die Gilde auf level 15 hochgelevelt und ich hab auch aktuell nicht mehr genug Emerald für eine neu. und sorry das ich diesen beitragt doppelt gemacht habe verstehe diese Seite nicht ganz so hab die das erste mal genutzt

**Comment by LordHelmchen98** [comment]
Die Antwort kommt jetzt leider etwas spät, jedenfalls sind Gilden nunmal verbuggt unglücklicherweise. Da sind du und deine Freunde auch nicht die einzigen, die damit Probleme haben. Bis das komplett gefixt wird wird sich daran nichts ändern.
Und kein Problem jetzt weißt du ja wie's funktioniert :)
