### ISSUE TITLE
lifesteal problems

### ISSUE THREAD

**Issue by happyhippoman** [Wynncraft/Issues#8308]
um the life steal slow takes away my life like 1-10 health every 2-5 seconds when i get it back (plz help me i can't live with this

**Comment by LordHelmchen98** [comment]
You might have negative health regen. That takes away health over time.

**Comment by happyhippoman** [comment]
no  i have a lifesteal build its no like that

**Comment by happyhippoman** [comment]
well my erraito have -6 and my helm of berserker have -10 but does't it just make u regen slower?

**Comment by Kronomancer** [comment]
Raw negative health regen takes away your health every few seconds, so you should either replace those items or get an item that has enough **raw** positive health regen so it would cancel out the negative. A legendary bracelet Ra worked for me when I had this issue.

**Comment by LordHelmchen98** [comment]
RESOLVED
