### ISSUE TITLE
Potion Making Quest Bug

### ISSUE THREAD

**Issue by SabbyOfThePlayer** [Wynncraft/Issues#8310]
My friend and I are unable to finish the level 15 Potion Making quest.
Essren doesn't spawn even though we changed servers and tried /fixquests. I have looked through many other complaints, but none of the solutions worked. 
I just end up entering the same empty room over and over again. (I even tried standing on pressure plates, etc.)

**Comment by ittnoraA** [comment]
Try joining a server which has just restarted (player count is usually low on those). If it still doesn't work, please report back.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
