### ISSUE TITLE
Red WynnEcavation Crystal Disappeared.

### ISSUE THREAD

**Issue by CocoWuffle** [Wynncraft/Issues#8311]
Yesterday I grabbed my red WynnEcavation Shard out of my bank so i could finally start WynnEcavation Site D. Unfortunately, I had to go to the airport right after I talked to the first NPC. I logged off and havent been on since until now. I got on and found out to progress when I doubled checked if I had my shard. I didn't though. Confused, I went to go grab it from my bank. It wasn't there, I even have screenshots down below. Thinking it was a glitch, I did /fixquests. It said I wasnt missing anything! I also have no storage classes that could be holding it. I had the red crystal and I did the quest, so I dont know what to do. I have screenshots down below, please tell me if you figure anything out or if I can get another shard. :)
![2017-06-06_11 19 13](https://user-images.githubusercontent.com/26863192/26837196-d81f87fc-4aaa-11e7-86a4-9b0b8f71f7b5.png)
![2017-06-06_11 19 50](https://user-images.githubusercontent.com/26863192/26837214-e21621da-4aaa-11e7-9dca-491cb4ab9d63.png)
![2017-06-06_11 19 57](https://user-images.githubusercontent.com/26863192/26837285-10e84ec0-4aab-11e7-830d-675165b0c8d0.png)
![2017-06-06_11 20 01](https://user-images.githubusercontent.com/26863192/26837294-1499de08-4aab-11e7-84e7-b5c5c6b45bb4.png)

**Comment by ittnoraA** [comment]
What does your quest book say on WynnExcavation site D's page?

**Comment by CocoWuffle** [comment]
I'll check

**Comment by CocoWuffle** [comment]
![2017-06-06_17 23 49](https://user-images.githubusercontent.com/26863192/26852650-f0da13ac-4adc-11e7-8187-06925046392d.png)

**Comment by Kronomancer** [comment]
That means you started the quest already and don't need the crystals anymore I think

**Comment by CocoWuffle** [comment]
In the last Wynnexcavation site's, you had to give it to a certain NPC, but i'll attempt to continue without it.

**Comment by CocoWuffle** [comment]
So far I've been able to continue so I'm going to close this issue, thank you guys <3
