### ISSUE TITLE
Jemand ist Doppelt in meiner Gilde!

### ISSUE THREAD

**Issue by Nick1Z2** [Wynncraft/Issues#8313]
Hi ich hab einen Gilde aber in der Gilde sind zwei Personen doppelt drin. ich kann die beiden aber auch nicht Kicken. Einer der beiden hat die Gilde schon verlassen aber immer noch wider er in der Liste aufgelistet. bitte helft mir!

**Comment by LordHelmchen98** [comment]
Duplicate of #8307 and #3665 
Ich hab dir in #8307 ausführlich erklärt warum das so ist und was deine Optionen sind. Bitte erstell keine weiteren issues über das selbe Problem. Danke.
