### ISSUE TITLE
I can't join this server

### ISSUE THREAD

**Issue by tyty1190** [Wynncraft/Issues#8317]
Hello, since yesterday i can't join the serv. Go look video . https://www.youtube.com/watch?v=ArEE8eSD8V0

**Comment by LordHelmchen98** [comment]
Usually that should fix itself over time, but you can try to join with a different IP (assuming you use play.wynncraft.com you can use .net or .org as well). If that doesnt work either you can try different mc versions.

**Comment by Villageacules** [comment]
@tyty1190 Is this still happening?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
