### ISSUE TITLE
Lost Diablo due to barriers

### ISSUE THREAD

**Issue by DraXionHubz** [Wynncraft/Issues#8319]
Hello. I have lost my Diablo wand near the cave/tomb where Lost Royalty's skeleton resides. Since it is stuck inside my barrier, I could not retrieve my wand and have lost it. If there is anything you can do about this, please help. I have attached a screenshot of the wand being stuck outside my reach. Also, when I accidentally dropped my wand, it did not fall straight down onto the ground where I could pick it up, but rather bounced around in the barriers until it was out of reach.
![2017-06-07_11 55 04 copy](https://user-images.githubusercontent.com/19677150/26896557-0cbf1dcc-4b7a-11e7-8f07-a469c26308a1.png)

**Comment by DraXionHubz** [comment]
If you are able to help me with this issue, then please send the wand (if you can give me another) to the name "DraXionGamez"
Thanks.

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.
