### ISSUE TITLE
Stuck in flower cave and wont let me out.

### ISSUE THREAD

**Issue by JarCap** [Wynncraft/Issues#8320]
it wont let me run out of the cave it gives me a warning message saying i shouldnt disturb the flowers or something and my friend gets the same message while trying to go in. i think i glitched through while the server was lagging

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by LordHelmchen98** [comment]
RESOLVED
