### ISSUE TITLE
the mobs despawned in the area that i need to take token from it

### ISSUE THREAD

**Issue by iEpicLord** [Wynncraft/Issues#8322]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

**Comment by thecoolkogut4** [comment]
What happens when you switch servers? Where are you?

**Comment by iEpicLord** [comment]
in underworld crypt dungeon
i didn`t try

**Comment by thecoolkogut4** [comment]
Switching servers should fix it, let me know how it goes.

**Comment by iEpicLord** [comment]
i switched servers i`m now in detlas and the key is gone

**Comment by thecoolkogut4** [comment]
Were you in the boss room?

**Comment by iEpicLord** [comment]
no i was before the boat ride room

**Comment by thecoolkogut4** [comment]
Weird, maybe try it again on a different server and see how it goes.

**Comment by iEpicLord** [comment]
still in selcher

**Comment by thecoolkogut4** [comment]
When you switched server, are you sure you logged in with the right class? (Did you click the class that was in the dungeon when you logged in to the different server?)

**Comment by iEpicLord** [comment]
i have only one class

**Comment by thecoolkogut4** [comment]
Is there a possibility that you clicked on a teleport scroll to go to o selchar? Because I'm pretty sure it would tp you to the front of the dungeon

**Comment by iEpicLord** [comment]
my scroll isn`t in the hotbar
 i can get another key thanks for trying to help me

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
