### ISSUE TITLE
Need an Admin or Mod to remove a bugged Quest item from my Inventory

### ISSUE THREAD

**Issue by Lederjens** [Wynncraft/Issues#8323]
I finished the Quest "Cluck Cluck" level 23 just before doing the "Reincarnation" Quest lvl 75. 
By mistake i got two Items "Cluckles' Favourite Feather" in the Quest "Cluck Cluck" and when i went to finish "Reincarnation" the NPC took only one. 

Now i am Stuck with One Quest Item "Cluckles' Favourite Feather" in my Inventory that i can't get rid off.
I finished both Quests "Cluck Cluck" and "Reincarnation" and there is no further Quest where it is needed. Please remove the Item "Cluckles' Favourite Feather" out of my Inventory.

Ingame Name : Lederjens
![2017-06-08_03 17 49](https://user-images.githubusercontent.com/29266202/26908154-2b08ddd4-4bf9-11e7-92f2-dbf0af8c8fb1.png)

**Comment by ittnoraA** [comment]
If you followed the dialogue, you might've noticed that Nohno gave you the feather back. You're supposed to keep the feather until you reach the Temple of Legends quest, where you need the feather as proof of your heroic actions along your adventure.

**Comment by Lederjens** [comment]
I already did that Quest you are talking about, please stop posting suggestions and let and Admin or Mod help me to remove the bugged Quest Item.

**Comment by Lederjens** [comment]
I already did that Quest you are talking about, please stop posting suggestions and let an Admin or Mod help me to remove the bugged Quest Item.

**Comment by thecoolkogut4** [comment]
Just to clarify, you did and completed these three quests. Cluck cluck, temple of legends, and bobs reincarnation? Is it possible that the feather is from another one of your classes?

**Comment by Lederjens** [comment]
The coolkogut4 Yes i completed all 3 Quests you mentioned and no other character was the source of the Quest item. It is a bugged duplicate because i got 2 Feathers from the Cluck Cluck Quest

**Comment by thecoolkogut4** [comment]
If you'd like you can refer to #8135 to see how to remove the item from your inventory. Just letting you know that once it's gone there might be no getting it back as /fixquests doesn't always work.

**Comment by ittnoraA** [comment]
Just clarifying, that moderators have nothing to do with how the game is created, and admins don't have time to bother answering questions here. It'd be a good idea not to act hatefully towards a content team member such as myself, or anyone in general.  

If you want to get rid of the feather, another way of throwing it away is to put it in your bank, fill your inventory with items, grab the feather and exit the bank screen.

**Comment by Lederjens** [comment]
@ittnoraA If you read it again you will see It was no hate involved, just making sure to let you know that i can read and i already did that, so that suggestion didn't help. But your second one was very helpful @ittnoraA .

PROBLEM SOLVED BY FILLING UP INVENTORY AND GRABBING THE ITEM, THEN LEAVING THE BANK.
THREAD CLOSED
