### ISSUE TITLE
Lost items due to server lag

### ISSUE THREAD

**Issue by librickysimon** [Wynncraft/Issues#8325]
Hello!

I've recently lost a third of my inventory due to the server being extremely laggy.
I was in the cave behind the Jankan (Canyon Condor quest) looking for the gold needed, while on my horse. Suddenly, all mobs stopped moving and I continued going down to the Lava Monster area. I was temporarily teleported back to the place where the lag spike started and kept on receiving damage from the Lava Monster. I died near lava and lost a lot of items, namely an unidentified Legendary piece of armour. Here is an image of what I lost.
<img width="563" alt="screen shot 2017-06-08 at 14 07 24" src="https://user-images.githubusercontent.com/29277976/26931411-c2391888-4c60-11e7-9207-bb9fa178c638.png">
ButterBlaster44 was a witness (next to me IRL).

**Comment by librickysimon** [comment]
If possible, do you have a refund policy? I have recently lost items while connecting. (I came to this)
<img width="410" alt="screen shot 2017-06-08 at 15 43 34" src="https://user-images.githubusercontent.com/29277976/26931669-9606a6bc-4c61-11e7-813f-583ed105c5d9.png">

**Comment by ittnoraA** [comment]
Sorry, but wynncraft enforces a strict "no refunds"-policy, which means you won't be getting your items back. If you lost items while connecting, you might want to disable autojoining with /toggle autojoin
