### ISSUE TITLE
Unable to complete Elemental Exercise quest after purchasing wrong weapon 

### ISSUE THREAD

**Issue by lepermimethe1st** [Wynncraft/Issues#8326]
Purchased incorrect weapon.
Attempted to buy correct weapon and got message "I'm afraid you cannot afford that item" with incorrect weapon in inventory.
Tried to throw incorrect weapon away and got message "You will need this item in later quests."
Tried to sell weapon and am not able to.

Unable to continue quest.

**Comment by ittnoraA** [comment]
There are two merchants next to the quest npc. One sells you fire based weapons and the other one buys them back. Just sell your incorrect weapon to that exact merchant and buy a weapon which your class can use from the other.
