### ISSUE TITLE
Creepers infiltration quest.

### ISSUE THREAD

**Issue by RagingDanny1** [Wynncraft/Issues#8327]
I have just completed the cutscene of creeper's infiltration and was teleported to the top of the tree. However while im here i can not pick up the creepers skin that i need to complete the quest.

I have tried rewatching the cutscene several times but nothing has happened

**Comment by ittnoraA** [comment]
The creeper skin is actually a mob that you need to kill to be able to pick it up

**Comment by RagingDanny1** [comment]
Yes I realised after a guild mate showed me. It wasn't the most obvious
thing though.
