### ISSUE TITLE
Literally stuck. Please help.

### ISSUE THREAD

**Issue by MidnightDragons** [Wynncraft/Issues#8330]
There are barriers blocking my way, while the door closed behind me.
http://imgur.com/a/wS11i
I also do not want to lose my key that I used to get here.

**Comment by RubbrDucky** [comment]
Do /kill at 5+ sp.

**Comment by ittnoraA** [comment]
No, don't /kill if you want to continue the dungeon. Just swap the server you're on until it lets you through.

**Comment by LordHelmchen98** [comment]
Usually that's a problem with the minecraft version. 
I bet you were using 1.10+. Wynncraft is hardcoded for 1. 8 so that's the version with least bugs and glitches but 1.9 works pretty good as well.
