### ISSUE TITLE
Life stealing effect from leggings is working incorrectly

### ISSUE THREAD

**Issue by jess-a-curtain** [Wynncraft/Issues#8331]
I got an item and it has life steal issues
When I wore it, my life was dropping. 
And from wiki, I got

> Life Steal	+X/2s	Increases the amount of health you gain when dealing damage

Please fix it and I don't want to steal my own life T-T

Here is a pic if you wonder which item it is.
![bg](https://user-images.githubusercontent.com/29297333/26961014-85a05b86-4ca9-11e7-87e2-b6bfaba5a19d.PNG)

**Comment by thecoolkogut4** [comment]
the pants have -health regen which removes 22 some of your health. Also, life steal on activates if you do melee damage to a mob, it won't trigger (you won't get health) if you do a spell.

**Comment by LordHelmchen98** [comment]
RESOLVED
