### ISSUE TITLE
Logged on lost my inv

### ISSUE THREAD

**Issue by BrutalScar** [Wynncraft/Issues#8332]
I logged onto the server. When i logged on i lost all of my gear and weapons that were in my inventory. this is annoying as they were good items and took awhile for me to earn

**Comment by thecoolkogut4** [comment]
I recommend you turn off auto-join. Do this by typing /toggle autojoin in chat. Once you type it, you will get a message in chat saying something along the lines of "you will now see the class selection screen again!" this way when you log in, you'll have a smaller chance of dying when logging in.

**Comment by colin350** [comment]
It's also good to not log off in a place which is considered "dangerous." You don't know how many mobs will be in the area when you log in on any server, as each server is different in terms of spawning rates (which depend on how many players are in the chunks, if it's been loaded, etc etc). From now on, a recommendation from me is to follow what @thecoolkogut4 said and to also try and log off in a town whenever possible (or house). 

In terms of your items, Wynncraft enforces a strict no refund policy which applies to all players, including staff members and content team members. What this means is that you won't be returned your items. As unfortunate as this may sound, this is how we maintain fairness among all of our players and avoid abuse.
