### ISSUE TITLE
Music sounds like noteblocks instead of the resource pack noteblock music in 1.12

### ISSUE THREAD

**Issue by Locky1110** [Wynncraft/Issues#8333]
title says it all
if you play in 1.12, the music will just sound like normal noteblock music, rather than what noteblocks are supposed to sound like with the resource pack

**Comment by LordHelmchen98** [comment]
Wynncraft is hardcoded for 1.8 and so is the resource pack I think. That's probably what is causing this issue and is most likely something that can be resolved. Maybe it will get fixed when they start phasing out older versions but for now just use a lower version.
