### ISSUE TITLE
My jester necklace dissaperd from my bank.

### ISSUE THREAD

**Issue by Oskar2070** [Wynncraft/Issues#8336]
This problem could be a thief thats have located my account and somehow got the password or something beacuse my rings was in the bar which i rember its wasnt yesterday, so i feelt something was wrong and looked in my bank and everything was left and without my jester necklace and my friends necklace too.
i bought this necklace for 1,19 le, so i wonder how i should do or it just a theif..

**Comment by Oskar2070** [comment]
Nope, i haven't got any screenshots saddly.

**Comment by AckroWynn** [comment]
@Oskar2070 You should definitively change your Mojang password. You can do that here:
https://account.mojang.com/password

There is nothing else we can do for you!
