### ISSUE TITLE
Im Stuck in a Dungeon "Decrepit Sewers"

### ISSUE THREAD

**Issue by TheLizardHD** [Wynncraft/Issues#8340]
i cant move forward or backwords, im stuck between the door and invisible blocks. pls help

**Comment by ittnoraA** [comment]
Just swap server and you should be fine. If that didn't work, just keep swapping until it does work.

**Comment by lolorz13** [comment]
same issue, swapping doesn't work (tried 9 other servers) on the chance I don't have this bug at the first door I then get stuck at the second because there are visible blocks behind that one that appear to be candles.

**Comment by ittnoraA** [comment]
The second door you're talking about is a client side bug that only occurs on 1.9-1.12 versions. Try using any 1.8 version and I can guarantee they will be gone! As a matter of fact, tripwires have also been confirmed to not always trigger on versions higher than 1.8.9, so try using a 1.8 version and see whether it helps or not.
