### ISSUE TITLE
stuck outside of boss area, help?

### ISSUE THREAD

**Issue by kaizerboo** [Wynncraft/Issues#8342]
so i tried to summon the boss at the bovine barn but got stuck in a few blocks instead. i relogged and found myself OUTSIDE of the boss area.
![2017-06-11_00 46 24](https://user-images.githubusercontent.com/29338688/27004805-c51efd36-4e42-11e7-9767-65cae5c24742.png)
![2017-06-11_00 48 47](https://user-images.githubusercontent.com/29338688/27004806-c787b342-4e42-11e7-8abf-387f85800948.png)
for those who don't know, i was using the wynncraft enhanced modpack that i found on twitch which should not affect the server itself, thats why i had a minimap.

**Comment by kaizerboo** [comment]
if possible, can an admin teleport me back to the bovine barn?

**Comment by ittnoraA** [comment]
Do /kill if you have 5 or more soul points. Please do not explore any further, as that will result in a ban.

**Comment by kaizerboo** [comment]
ok, thx
