### ISSUE TITLE
My Quest Items Are Gone

### ISSUE THREAD

**Issue by WierdWaffle** [Wynncraft/Issues#8343]
Since I didn't really have any room in my vault or inventory for quest items I started looking in game by myself on how to get rid of them, then I realized that you can get rid of them from the daily crate. I got rid of 4 breathing helmets thinking I could just use one,  I also got rid of a lot of quest items not knowing I would need them later. If you could please help me because I really want to advance through the game knowing I can keep going, Also my username is WierdWaffle

**Comment by thecoolkogut4** [comment]
Type /fixquests to get your item back.
