### ISSUE TITLE
Twain Journal not dropping

### ISSUE THREAD

**Issue by MortisAeternalis** [Wynncraft/Issues#8344]
I killed Phantom Twain once, it didn't drop the journal, went to go back in and tossed in a Gernald's Amulet by mistake when trying to enter the room behind the fireplace in the mansion; killed the boss again after losing said valuable item via misclick, no drop yet again. Went and fought it a THIRD time, still nothing. If possible, I'd like the amulet back, if not, oh well, but the quest can't be completed if the boss never drops the item.

EDIT: After the sixth time, the journal finally dropped. Still out one quest reward alas thanks to it failing to drop the first time.

**Comment by MortisAeternalis** [comment]
Incidentally, after the sixth time, the journal finally dropped.

**Comment by colin350** [comment]
It's not supposed to drop the first time. To my knowledge twain has multiple forms, and it isn't until the final form will the item drop. This is mechanic is the same in the quest Salyeros' brother.

**Comment by MortisAeternalis** [comment]
I reset the dungeon all six times; it's only a one-off death, not multiple stages, or at least it wasn't when I fought it, so if it's supposed to be, then that's bugged as well, but thank you for the reply.
