### ISSUE TITLE
Can't get my Monthly Crate

### ISSUE THREAD

**Issue by FreeProGamer** [Wynncraft/Issues#8346]
Hello, it has been for two months as I cannot claim my monthly crate, I've tried it today and about a month ago, but neither of the times I've got the crate, it says I need to buy it. It does allow me to type the username but then when I click submit, it just does nothing, I've tried it from different computers but the same result, even if I re-log.

Can anyone help? I deserve 2 crates!

**Comment by colin350** [comment]
Are you typing your username correctly? Case matters.

**Comment by FreeProGamer** [comment]
Yes

**Comment by FreeProGamer** [comment]
I do

**Comment by FreeProGamer** [comment]
Shall I record everything starting by logging into Minecraft until trying to open the chest?
