### ISSUE TITLE
Charon Fight bug

### ISSUE THREAD

**Issue by ExpiredBL** [Wynncraft/Issues#8348]
![image](https://user-images.githubusercontent.com/29357107/27012841-3a730306-4ed0-11e7-89aa-8761ad82ee24.png)
This was dropped by one of Charon's army.

**Comment by ittnoraA** [comment]
It most likely wasn't dropped by a mob, but a content team member on the build server which is why it got carried onto live servers. Please throw it into a trash disposal or hand it over to a moderator, as owning illegal items might get you banned.

**Comment by ExpiredBL** [comment]
Already done, just wanting to make sure it was known by you guys ^_^
