### ISSUE TITLE
Can't get out of guild

### ISSUE THREAD

**Issue by NotAlignments** [Wynncraft/Issues#8349]
So apparently I can't get out of my guild.

I did /guild leave and when I typed yes in the sign, it said I officially left the guild but I looked on the TAB key and found my previous guild members on there and the initials are still in my chat name. I messaged the owner and I told him to kick me from the clan but it didn't work (it said I was kicked from the clan but I am the same effects happened (TAB key and initials). I have no idea what is happening but please help. Thanks and my user is Alignments if you were wondering what it was.

**Comment by thecoolkogut4** [comment]
This is a well known issue and there is currently no fix for it. All you can do is wait for the devs to fix guilds.

**Comment by NotAlignments** [comment]
that sucks

**Comment by colin350** [comment]
Please: #3665
