### ISSUE TITLE
Another decrepit sewers dungeon door issue

### ISSUE THREAD

**Issue by lolorz13** [Wynncraft/Issues#8351]
Provided I can get past the initial door issue with invisible blocks, I occasionally run into this issue:  
![2017-06-11_15 29 21](https://user-images.githubusercontent.com/22108177/27014277-55db840c-4ebb-11e7-8bcd-7250fe938518.png)
... and I cannot get to the boss.

-Swapping servers does not help:  
When I do swap the candles are not blocking access to the boss  
(I can see through the gaps in the stair decoration and from the platforms to the side)  
they appear a few milliseconds after I try to open the door.  
-Reopening the door does not remove them either  
-They are 1 block above the ground making teleports past them impossible

**Comment by lolorz13** [comment]
One of the servers rebooted (#8), this did not fix the issue either

**Comment by ittnoraA** [comment]
This happens because the server is causing glitched blocks appear on the door on 1.9-1.12. Just log in using any 1.8 version and you should be fine.
