### ISSUE TITLE
Lost Legendary Weapon in UnderIce quest

### ISSUE THREAD

**Issue by StellarWing** [Wynncraft/Issues#8353]
I lost my Legendary Weapon Fierce Thunder while doing this quest. I tried to throw the seed into the fishing place, but I threw my weapon instead. Now its gone. Can anyone fix this and maybe give me a new Fierce Thunder or Legendary Weapon? I'm sad

**Comment by RubbrDucky** [comment]
Wynn = strict no refund policy

Sorry

**Comment by StellarWing** [comment]
Sometimes I really do not like those things where you drop your weapon by accident and there goes your weapon, never to be seen again

**Comment by RubbrDucky** [comment]
Yeah rip my near perf cosmic helm that glitched in inv and disappeared...

**Comment by LordHelmchen98** [comment]
I'm sorry for your loss, but as already said Wynncraft enforces a strict norefund policy. Therefore you won't get your season back.
