### ISSUE TITLE
I am loosing health at an insane rate!

### ISSUE THREAD

**Issue by SpinningWorld** [Wynncraft/Issues#8354]
I have noticed recently that I loose health constantly. I can loose up to 90 health per minute if I am sprinting. I loose about 20 per minute **standing _still**. I have no negative effects on my armor.
This has caused me many deaths and lost items. There are a few ways I die:
1. I just battled a mob and I have very low health, suddenly I die randomly after the battle.
2. I am going threw a quest and I have to battle a ton of mobs at once (while using various combat maneuvers which involve sprinting) and I loose health to just moving which puts me at a disadvantage fighting mobs, and I die.
3. I will be adventuring and I have already gone threw all of my health potions and I come across a swarm of mobs which kill me.
I have lost practically all of my money and I can't gain much money because I waste it all on health potions.
Please fix this, I cannot continue to play normally and have a good time with this happening, I can't go adventuring, I can't fight mobs near or above my level, and I can't go on quests.

~SpinningWorld

**Comment by RubbrDucky** [comment]
what is your equipment? what level? Do you have negative lifesteal or
health regen?

**Comment by SpinningWorld** [comment]
It seems to be getting worse as I write this issue... I just had to use a full Lvl.30 healing potion in 3 minutes.

I originally had a fairly good gold chest plate and gold boots along with adventures helmet and leggings.
I am level 34.
I have no life steal but I have +4% health regen.

**Comment by SpinningWorld** [comment]
It keeps getting worse, now I loose around 100 a minute walking. And maybe 25 standing still...
I am skyping my friend right now and he does not have any of these effects...

**Comment by thecoolkogut4** [comment]
As rubberducky said, what equipment are you using (names please). This includes armour and accessorie.

**Comment by SpinningWorld** [comment]
Ok, Adventurers Cap and Pants. Morph-Gold. Slate Bow, Glacial Crest, Meridian. And I have a horse, idk if that does anything...

**Comment by Reefive** [comment]
You armor sucks. It's because you are level 34, and you are using level 20 stuff. Upgrade.

**Comment by SpinningWorld** [comment]
Ok, thanks for the tip, that seemed to help. Although my new armor has a lot of the same stats regarding health regen... I don't know how it was fixed, but thanks.
