### ISSUE TITLE
Quest glitch

### ISSUE THREAD

**Issue by TheSaltyDragon** [Wynncraft/Issues#8356]
I am glitched on the Out of my Mind quest. I beat the puzzle, but the door wouldn't open, so I had to teleport out with a scroll. I cannot get back to where I was.

**Comment by Reefive** [comment]
Just keep on redoing this.
Answers: Cart - 2A - Left / Cannon 1 - 7C - Left / Cannon 2 - 6B - Left / Fan - 10B - Left 
Just remember that. And don't move after you complete the puzzle. Just wait 3 seconds, until he says something.
