### ISSUE TITLE
Custom Skin Won't Work

### ISSUE THREAD

**Issue by Anonymous2401** [Wynncraft/Issues#8358]
So I'm talking about my regular character skin in Minecraft. When in the lobby it loads, but the moment I join it resets me to the default Alex skin. Is this supposed to happen, or am I doing something wrong?

**Comment by RubbrDucky** [comment]
Try taking off your helmet and putting it back on

**Comment by Anonymous2401** [comment]
I just started playing, I don't even have a helmet.

**Comment by FreeProGamer** [comment]
Try logging with version 1.8

**Comment by colin350** [comment]
Wynncraft is hardcoded to 1.8.9, so if you want your skin to load 99% of the time, best to join using 1.8.9. Other than that, this is a client side issue. If you want to play on 1.9+, you'll have to deal with it.
