### ISSUE TITLE
Huge bug

### ISSUE THREAD

**Issue by Zyoode7** [Wynncraft/Issues#8359]
i know a very very huge bug in wynncraft which can destroy Dungeons *my English is bad sorry but this bug is huge and you have to fix it right now* 

if you want know the bug contact with me on discord Zyoode7#0122 also i won't let you know if you don't give me something like hero

**Comment by Moe-Ronickah** [comment]
@Zyoode7 , if you have a forum's account, please contact me in a pm.  If you don't yet have one, please make one and contact me.
