### ISSUE TITLE
Stuck Outside The Map. (SuchAlex)

### ISSUE THREAD

**Issue by SuchAlex** [Wynncraft/Issues#8360]
So I exploring santa's island then apparently I fell off the mountain into like just a flat land. Please check it out and help. My username is SuchAlex. 
![2017-06-12_08 26 44](https://user-images.githubusercontent.com/29379267/27041454-e15891e0-4f48-11e7-9ef9-ec5cb2810971.png)
Here's proof it's wynncraft
![2017-06-12_08 26 48](https://user-images.githubusercontent.com/29379267/27041471-efbc371e-4f48-11e7-9106-fbefa00989a3.png)

**Comment by SuchAlex** [comment]
Nvm /kill I'm good

**Comment by ittnoraA** [comment]
Heya! If you have 5 or more soul points, do /kill to respawn in the nearest city you've visited. Please do not explore any further, as that will result in a ban.

**Comment by SuchAlex** [comment]
I have done thata

**Comment by SuchAlex** [comment]
Yes I immediately did /kill thank you. And I never explored more than that.

**Comment by LordHelmchen98** [comment]
RESOLVED
