### ISSUE TITLE
Quest doesnt work

### ISSUE THREAD

**Issue by OMGitzRona** [Wynncraft/Issues#8361]
I did the quest "WynnExcavation Site A" but when i came to take my reward he asks me to give a note to a guy again although i did it, but i tried again and the gut told me to go back to the first guy and duwahidhad please help

**Comment by FreeProGamer** [comment]
Can you screenshot it?

**Comment by OMGitzRona** [comment]
![2017-06-27_11 14 51](https://user-images.githubusercontent.com/29379791/27577717-69971738-5b2a-11e7-8483-9b656a65f799.png)
![2017-06-27_11 15 24](https://user-images.githubusercontent.com/29379791/27577718-699fee80-5b2a-11e7-884a-fbe842c086d2.png)
![2017-06-27_11 14 36](https://user-images.githubusercontent.com/29379791/27577719-69a78aaa-5b2a-11e7-9fad-a838c2708a5d.png)

**Comment by OMGitzRona** [comment]
found the solution, nvm.
