### ISSUE TITLE
An apologise \ a weird bug

### ISSUE THREAD

**Issue by Zyoode7** [Wynncraft/Issues#8362]
I want to apologise to Creecreeprs Sorry for what i said 

the bug is little bit weird and i didn't find any solution for it 

the bug is when you want to throw a quest item you just have to fill your inventory by Emeralds and put the quest item in the crafting location then the item will disappear and you can't get it back 
if there is a solution tell me what is it please :3

**Comment by ittnoraA** [comment]
If you want a quest item you've lost back, try typing /fixquests. Do keep in mind though, that the command doesn't work for all quest items.

**Comment by colin350** [comment]
If `/fixquests` doesn't work, your only other option is to level up a new class and transfer the quest item via your bank.
