### ISSUE TITLE
Cant talk to npcs

### ISSUE THREAD

**Issue by Orionw3333** [Wynncraft/Issues#8363]
I just started and i read that you can talk you npcs to get quests but i cant talk to npcs im right clicking and i tried every single button on my keyboard why is it not working?

**Comment by thecoolkogut4** [comment]
What quest are you trying to start and what level are you?

**Comment by Orionw3333** [comment]
Im lvl 1 and right now i am trying to talk to a npc but i cant talk to any npc`s

**Comment by thecoolkogut4** [comment]
What's the NPCs name? at level one I'm pretty sure the only quest you can do is kings recruit. What happens when you switch servers?

**Comment by Orionw3333** [comment]
let me check

**Comment by Orionw3333** [comment]
Ad











































































venturer

**Comment by Orionw3333** [comment]
the name of the npc`s are like adventurer and i was watching youtube on this server and it said every npc with a green name gives quests and the same thing happens in a different server in Wynncraft.

**Comment by thecoolkogut4** [comment]
Yes, if it's a green name that means it's a quest NPC. What quest are you trying to start?

**Comment by Orionw3333** [comment]
i dont know right now but i just cant talk to a NPC

**Comment by thecoolkogut4** [comment]
If you open your quest book, go to the coordinates of the first quest and start it there.

**Comment by Orionw3333** [comment]
ok, but do you know why i cant talk to a NPC?

**Comment by thecoolkogut4** [comment]
Its probably a NPC that only talks once you start a required quest.

**Comment by Orionw3333** [comment]
ok um i need help um im doing the kings recruit quest it says to follow the path but then it go`s to a broken bridge and i cant talk to any npc`s to find out what to do.

**Comment by thecoolkogut4** [comment]
There is a tree, on the left side of the path. On the tree at the bottom there should be a button. Push that button and the tree will fall downso you can cross.

**Comment by Orionw3333** [comment]
ok thx

**Comment by Orionw3333** [comment]
oh i also cant type nor see chat

**Comment by thecoolkogut4** [comment]
That's probably why you can see the NPCs talk... There's an option in your MC settings to turn chat back on. I'm not at my computer right now so I can't tell you exactly where. But you can google how to turn off and on Minecraft chat and I'm sure someone has made a tutorial.

**Comment by Orionw3333** [comment]
OH yeah i turned it off

**Comment by colin350** [comment]
From now on, please ask further questions in the Wynncraft/Questions section of the forums instead of here.
