### ISSUE TITLE
Sea Skipper Problems

### ISSUE THREAD

**Issue by pixelcreepE** [Wynncraft/Issues#8364]
I've been having trouble with the Sea Skipper boat.  I had to use two Llevigar passes to get on the boat, and am stuck on it.  The captain won't start talking, and there are some invisible blocks on the boat near the front.  I'm going to use /kill, but please fix this!

**Comment by ittnoraA** [comment]
Heya! There is no need for /kill. Just swap the server you're on and you should be fine. If you're still stuck after that, swap again!
