### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by stinger020604** [Wynncraft/Issues#8365]
Hi I am a lover of wynncraft but while using the teleport spell in the rangi dungeon I got stuck in a redstone wall of mechanics and cannot teleport out, use any teleport scroll. If you can pls help asap I would gladly appreciate it. Thank you.
-Jonahj6

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by stinger020604** [comment]
Thank you so much I appreciate it and thanks for the quik response
