### ISSUE TITLE
Quest BUG | Pigmen's Ravines

### ISSUE THREAD

**Issue by AlienYuNO** [Wynncraft/Issues#8369]
Im german, so sorry for the bad english. :)
-------------------------------------------------------

On the quest in the **Pigmen's Revines**, there is a bug with the reward.

The new questreward **(64e**) are not the same, as the rest of the money.
Its not possible to stack the **64e (1eb)** to the others.

I hope you understand, what i mean.

Its just a small bug and i love the new quest in the **Pigmen's Revines**.

YuNO :)

**Comment by AquaDragon10** [comment]
You could try converting it to 64 emeralds, then back into a block at a bank.

**Comment by LordHelmchen98** [comment]
Duplicate of #7905
Wie schon gesagt wurde kannst du einfach bei einer Bank den Block in einzelne emeralds und dann zurücktauschen. Ich bin mir nicht sicher ob es schon gefixt ist aber es ist bekannt und falls es noch nicht gefixt ist sollte es das bald sein.
