### ISSUE TITLE
Trapped in invisible blocks

### ISSUE THREAD

**Issue by SpectralPanda** [Wynncraft/Issues#8372]
Hey idk how this would be fixed but i was just to travel as a mage thru the jungle tops and i teleport into a tiny 1x1x2 hole surrounded by invisible blocks. I tried to teleport out of it but it wont let me. If someone could get back to me or someone who has block breaking perms to get me out. I would like to play my mage again :)

**Comment by ittnoraA** [comment]
Heya! If you have 5 or more soul points, do /kill to respawn in the nearest city you've visited.

**Comment by colin350** [comment]
Could you please list the coordinates if you had them?
