### ISSUE TITLE
Forums "Visit the Wynncraft Store!" Error

### ISSUE THREAD

**Issue by thecoolkogut4** [Wynncraft/Issues#8373]
"Get your Free Monthly Crate on our store! You can also purchase Ranks, Crates, Bombs & Pets for mob totems, weapon skins, server-wide double XP and more!"

should be changed to the following because pets aren't for mob totems, and you can't individually buy a specific weapon skins. (unless they are planning to do another shop update, if they are then I might be wrong)

Get your Free Monthly Crate on our store! You can also purchase Ranks for mob totems, Crates for weapon skins, Bombs, Pets, server-wide double XP and more!

**Comment by colin350** [comment]
Passing onto Jumla and Elements.
