### ISSUE TITLE
Winter's essence not being able to be equipped

### ISSUE THREAD

**Issue by librickysimon** [Wynncraft/Issues#8374]
Hey,

I can't use my Winter's Essence even though I have all the requirements.
<img width="332" alt="screen shot 2017-06-11 at 20 18 16" src="https://user-images.githubusercontent.com/29277976/27143266-1522284c-512e-11e7-9495-260019950d0c.png">
<img width="368" alt="screen shot 2017-06-14 at 18 19 24" src="https://user-images.githubusercontent.com/29277976/27143267-1a585d9a-512e-11e7-922b-c40f4f05aeb9.png">
<img width="640" alt="screen shot 2017-06-12 at 17 44 22" src="https://user-images.githubusercontent.com/29277976/27143282-25471afc-512e-11e7-8a49-e06bf507d9f3.png">

**Comment by ittnoraA** [comment]
Are you sure your stats still meet the requirements after you unequip your current leggings?

**Comment by librickysimon** [comment]
Ah. That's the problem
