### ISSUE TITLE
Can't finish quest

### ISSUE THREAD

**Issue by adelade** [Wynncraft/Issues#8375]
So I'm on the quest "Lord of the Clock" and when I was in the Mt. Wynn Cave talking to Frudo I died in the lava. This caused me to not have the clock anymore but never able to finish the quest. So whenever I go back down to talk to Frudo he doesn't say anything.

**Comment by colin350** [comment]
If what @ittnoraA recommended does not work, then your only other option would be to level up another class and transfer the quest item via your bank. The only flaw with that solution is that the new class will be unable to complete the quest if `/fixquests` doesn't work for the new class.

**Comment by adelade** [comment]
Thanks, I'll definitely try those!
