### ISSUE TITLE
Legendary Bow Deleted From My Inventory

### ISSUE THREAD

**Issue by MasterMinder1111** [Wynncraft/Issues#8376]
My friend nchavan and I were doing the Thomas quest in Pigman Ravine, and we were at the part where the creeper was going to blow us up. My friend was holding his Legendary bow, and suddenly, his bow got deleted from his inventory. We went back u to search for it, but it wasn't there. Please address this issue

Victim's in game name: nchavan
My in-game name: yasirr

**Comment by RubbrDucky** [comment]
sorry, wynn has a strict no refund policy

just get a new one or something

sorry

**Comment by MasterMinder1111** [comment]
k at least thanks for replying. My friend was depressed, so I played for like 3 hours and farmed till I got another legy bow
