### ISSUE TITLE
toa xp reward

### ISSUE THREAD

**Issue by bobcaboose** [Wynncraft/Issues#8377]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.
I have just completed the TOA quest and it said that it gave me 925000 xp. I was really close to becoming level 50 but now i have finished the quest, im only 64% of the way to level 51. I think that I only got 92500 xp from this.
thanks

**Comment by FreeProGamer** [comment]
Same here, I should've been at least level 63 but got level 61 with 80% (I was level 60)

**Comment by LordHelmchen98** [comment]
The XP reward from ToA scales with the level of the player, because players carried low level players through the quest so they were able to get an insane level boost. That's why you two got less XP. 
The best level to finish it is about 70.
