### ISSUE TITLE
Bug prevents completing decrepit sewers

### ISSUE THREAD

**Issue by liilAmy** [Wynncraft/Issues#8378]
I cannot move past the point where the second block of creepy text appears. I hear the triggering of a plate and get the message that is something like "you continue to trespass, you must not value your life". I am stopped at this point as if running into a wall. Every time i move up to the spot, it plays the message again.

**Comment by ittnoraA** [comment]
Heya! I'd recommend you to use any 1.8 version and trying again on a recently restarted world.

**Comment by LordHelmchen98** [comment]
As already said it should be fine if you use 1.8 it should be fixed E to use 1.9 as well.
