### ISSUE TITLE
BUG quest(The shadow of the Beast)

### ISSUE THREAD

**Issue by gao135** [Wynncraft/Issues#8379]
I can't perform the "The shadow of the Beast" task. I have passed all chain of quests, but when I try to hand over a quest at Dereg he sends me to pass everything zany. For delivery of quest I have all things, but can't hand over.
I already used command /fixquests

**Comment by thecoolkogut4** [comment]
What does your quest book say?

**Comment by gao135** [comment]
Kill the beast and return to Dereg with the three pieces of evidence of the beast’s existence.
I have killed all and have got all things.

**Comment by gao135** [comment]
And it is possible to nullify a quest somehow?

**Comment by LordHelmchen98** [comment]
If it says that you have to kill the beast you skipped a tripwire inside the boss room. Go there again and try to trigger it then it should work.
