### ISSUE TITLE
Quest Bug (SuchAlex)

### ISSUE THREAD

**Issue by SuchAlex** [Wynncraft/Issues#8382]
My username is SuchAlex. So I was doing the quest, "MeaningFul Holiday" So then I go teleported to the biome and I had to look for santa then I did but I fell off the mountain and took this picture. 

![2017-06-12_08 26 44](https://user-images.githubusercontent.com/29379267/27197057-bc9675ae-51c1-11e7-8b8e-b5cd50e135bf.png)

Then I was told by a staff member to do /kill and if I explored more I'll be banned I had no other way back up the mountain so I did /kill and I was at ragni. Now I cant go back because that's a quest I get teleported to. So now my book just says, 
![2017-06-15_11 58 21](https://user-images.githubusercontent.com/29379267/27197119-f15f72cc-51c1-11e7-9119-45f11b9c3c61.png)

And now I can't do this quest I hope staff has a way to fix this possibly restart this quest for me "SuchAlex" I will appreciate it. Thanks

**Comment by ittnoraA** [comment]
Heya! I believe you can go back to Reshad to make the portal reopen.

**Comment by SuchAlex** [comment]
Thanks
