### ISSUE TITLE
I am stuck in a piston and can not get out. 

### ISSUE THREAD

**Issue by AngeiStar2** [Wynncraft/Issues#8384]
Hello. My name is AngeiStar2 and i am stuck in a piston. I was doing the quest Lord of the clock. And on my way to gundalf's secret lab. I got stuck in the piston door leading into the lab. I have tried using my teleportation scroll to Ragni. But i can't use it because i am clicking on the piston's hitbox. Please help me out. :(

**Comment by ittnoraA** [comment]
Heya! If you have 5 or more soul points, do `/kill` to respawn in the nearest city you've visited.
