### ISSUE TITLE
No climbing helmet even though I completed quest?

### ISSUE THREAD

**Issue by mayorswaim** [Wynncraft/Issues#8385]
So I stopped playing and just came back. I'm trying to compete the Zhight Island quest and I need it, but a lot of my stuff vanished after the Gavel update.

![proof](https://user-images.githubusercontent.com/16410438/27208277-6e21d9e2-520a-11e7-9a4b-2f1b1ddaebdc.PNG)

**Comment by thecoolkogut4** [comment]
Type /fixquests to get your item back.

**Comment by mayorswaim** [comment]
thank you!
