### ISSUE TITLE
Adventurer's Armour : Taking damage quickly....

### ISSUE THREAD

**Issue by PEugen** [Wynncraft/Issues#8386]
Hi!

I recently collected the full Adventurer's Armour, but when I use it I take alot of damage and quickly.
But it stops if I take away the pants...

**Comment by FreeProGamer** [comment]
Do you mean that you are getting constantly and repetitively damaged by nothing?

**Comment by PEugen** [comment]
I am just a spoon! It's my wand!

*face palm*

xd

**Comment by LordHelmchen98** [comment]
RESOLVED
