### ISSUE TITLE
Beyond the Grave Teleport Bug

### ISSUE THREAD

**Issue by Goldstriker** [Wynncraft/Issues#8389]
During the Quest Beyond the Grave when it asks you to leave Death's realm after the puzzle when me and my friend went to the door that should teleport us out it brings us to a small box with four torches and a button, the button does nothing. I know this is wrong because the first time I did went through it brought me to the bridge where the quest continues, (My friend what brought to the bugged teleport) We did it three more times after each (I did /kill) and each time got put into the box.

**Comment by Goldstriker** [comment]
Okay turned out it was just the world's issue this can be closed

**Comment by Trixter313** [comment]
Glad to see it got resolved! 😃
