### ISSUE TITLE
Dwelling Walls Quest Outmap Glitch

### ISSUE THREAD

**Issue by Malguf** [Wynncraft/Issues#8390]
Relogged while inside of Dwelling Walls quest room with button and logged back in to find myself on top of the map.
http://imgur.com/a/2oPus

**Comment by Trixter313** [comment]
To get back to a playable area, you can use the command /kill with 5+ soul points. Please do this as soon as possible as using glitches to go to unintended areas is against the rules, but I understand that this wasn't intentional.

**Comment by LordHelmchen98** [comment]
RESOLVED
