### ISSUE TITLE
Stuck in Underworld Crypt

### ISSUE THREAD

**Issue by Skalylikesbudder** [Wynncraft/Issues#8391]
Me and 2 other people went in and got stuck in a room and cant move on there is no way to get out and we are stuck in here can a staff member please help us. My username in the game is skalylikesbudder.

http://tinypic.com/r/2d9qkw8/9

http://tinypic.com/r/2lbjokw/9

http://tinypic.com/r/iyfy9g/9

**Comment by Skalylikesbudder** [comment]
Well i found a pool of water and was able to kill my self but lost some items because of it

**Comment by Trixter313** [comment]
For future reference, you can use the command /kill to get out of most stuck situations, and as long as you have 5+ soul points you shouldn't lose anything too important.

**Comment by LordHelmchen98** [comment]
Usually there should be mobs again if you switch to another server.
Otherwise you can use `/kill` with more than 5 soul points as already said.
