### ISSUE TITLE
Stuck above Llevigar bank/Tier 4 chest with Warrior

### ISSUE THREAD

**Issue by Remixtech** [Wynncraft/Issues#8395]
Well above Llevigar bank is a small area with a Tier 4 chest a fountain and a potato stache. I wanted to loot the Tier 4 chest with my Warrior but i got stuck after I looted the chest is there a way out of the area?

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by Remixtech** [comment]
Thx 👍
