### ISSUE TITLE
House of Twain: The Grave do not Opened

### ISSUE THREAD

**Issue by TFSteveMC** [Wynncraft/Issues#8400]
After getting the Ghost Helmet, the Grave should be Opened, but in this case the Grave not Open

Please Wynncraft Team to fix this bug for me & another player can Complete the "House of Twain" Quest

**Comment by Trixter313** [comment]
Did you pay tribute to the grave behind the fireplace?

The wiki has the full steps in the spoiler https://wiki.wynncraft.com/index.php?title=The_House_of_Twain_(Quest)

**Comment by TFSteveMC** [comment]
i just do that Step by Step, okay
and i just do the entire quest all over again

**Comment by TFSteveMC** [comment]
thx for the tips (lol i think i just stupid xD)
