### ISSUE TITLE
My username is too old to be in the ban system so it doesn't show in the ban appeal search system

### ISSUE THREAD

**Issue by MrSplitYourBase** [Wynncraft/Issues#8401]
I was banned over 3 years ago and I would like to appeal to it but I think I was banned too long ago for my username to be in the system because when I searched for my username, it wouldn't appear. My old username is AwesomeWaterDude and my new username is MrSplitYourBase.
Links:
https://namemc.com/profile/MrSplitYourBase.2 (My new and old name)
https://gyazo.com/568788f97c33488f95331e854931a7ef (AwesomeWaterDude not showing up in the results)
https://gyazo.com/bf4fba0a56fd8b43ec2b1a712240bdfd (MrSplitYourBase not showing up in the results)
https://gyazo.com/766f12f41d0e3261f65fd5ee7e8e9fc3 (My ban status and information and disconnect message)

Provided with this information I would like to use this opportunity to kill two birds with one stone, since this bug I am reporting isn't very important I don't really care about it being fixed, I more care about being able to appeal somewhere so I am using this opportunity to appeal but I will copy and paste my appeal so if requested I can move it to another forum.

For 3 years I've missed wynncraft and I'm really sorry for my actions, I would of appealed sooner but I didn't think I'd be accepted, since I was guilty and I was really sad about it and mad at myself. Every once and a while I'd check up on wynncraft, watching youtube videos of people on it doing playthroughs and quest guides and I've read the news on the updates. Then today as I was doing my check up on wynncraft as I do whenever I am in the mood for reminiscing about my favorite server that I regrettable hacked on. I found a video where Grian said that wynncraft gives second chances and I decided that hopefully they would see my remorse for hacking and give me a second chance. So I ask of you if you will give me a second chance.

**Comment by thecoolkogut4** [comment]
Email support@wynncraft.com with your appeal. Goodluck!
