### ISSUE TITLE
My Removed Quest Items

### ISSUE THREAD

**Issue by KenatoMC** [Wynncraft/Issues#8405]
IGN: Kenato

More specifically my WynnExcavation Site C shard.
I had logged out an hour ago with my shard and
logged back in and found out that my shard was not
in my inventory.

Also I've started the site D quest without knowing I didn't
have the shard. Does Royal Advisor Carlos need the shard to continue?

Thank you!

**Comment by thecoolkogut4** [comment]
Type /fixquests to get your item back.

**Comment by KenatoMC** [comment]
I've had done that and I still don't posses it.

**Comment by thecoolkogut4** [comment]
Is it possible that the Shard is in your bank, or on another class?

**Comment by KenatoMC** [comment]
Nope, I check all of my 3 classes and my bank. None of them have the red shard.

**Comment by colin350** [comment]
The only other solution is to level up another class, complete Wynnexcavation C on that other class, and transfer the red shard via your bank.
