### ISSUE TITLE
Typo on Wiki (Llevigar's Library)

### ISSUE THREAD

**Issue by RedLogicP** [Wynncraft/Issues#8411]
This statement should have a period, not a question mark: "The new fortunes made by the Villagers has allowed them to construct an entire city to welcome the cheap labour arriving from the Wynn province?"
Thanks!

**Comment by Trixter313** [comment]
Fixed, thanks for the report!

**Comment by Trixter313** [comment]
I just realized these are quotes from the ingame chapters, so they might need to be fixed there as well. I edited all of the grammar and punctuation mistakes I found on the wiki, not sure if they are made ingame as well or if we want to keep the incorrect versions.

**Comment by RedLogicP** [comment]
I was wondering the same thing but didn't have the time to make my way to Llevigar. ;)

**Comment by LordHelmchen98** [comment]
Its correct ingame.
