### ISSUE TITLE
Restart player spawn due to Player collision in Santa Quest

### ISSUE THREAD

**Issue by shr210** [Wynncraft/Issues#8413]
While Walking on the path North west from Ternaves, the player walked into the path while someone was doing the Holiday Giving quest. They teleported with them to the quest area. Due to this, the player /killed themselves and they ended up spawning in the initial spawn, made to buy the leather cap and enter Ragni

Video upon request

**Comment by thecoolkogut4** [comment]
Hey there,

This is a very well known bug. When you die off map (during a quest, or for any other reason your outside), you get sent to the closest respawn point, either a town or the starting area. You are just going to have to walk back to where you died. 

Goodluck!
