### ISSUE TITLE
Used War scream on Baab and this happened

### ISSUE THREAD

**Issue by Remixtech** [Wynncraft/Issues#8415]
![screen shot 2017-06-19 at 10 25 08 pm](https://user-images.githubusercontent.com/19750990/27317926-6ff8aef8-553e-11e7-850f-af0e25d092ef.png)

**Comment by LordHelmchen98** [comment]
Warscream is known to push mobs into walls (or behind iron bars in this case). You just have to do /class and relog so it spawns again, maybe this will be fixed in future, but if so I dont know an estimated date for it.
