### ISSUE TITLE
Rymek Elevators do not work.

### ISSUE THREAD

**Issue by Tom250** [Wynncraft/Issues#8417]
Hej,
I did the Svin Quest lately and as I wanted to try the elevator it won't works. I was just staying and the bottom, waiting five minutes till I got died by Shooting Zombies with missingno-Projectiles. The Lift Person Thingy just said to enter it...
Help

**Comment by colin350** [comment]
Could you please give me the coordinates for which elevator? That way, I can fix it on build.
