### ISSUE TITLE
I'm Stuck the quest Lord Of The Clocks

### ISSUE THREAD

**Issue by MrDoof** [Wynncraft/Issues#8423]
Me And my friend (Slothlone) were doing the quest together. But he got the clock and i didn't so i can't do the quest.

**Comment by colin350** [comment]
Are you sure you also clicked Bulbo and got his dialogue?

**Comment by MrDoof** [comment]
Yeah i Did

**Comment by Trixter313** [comment]
What does your quest book day to do?

**Comment by MrDoof** [comment]
Destroy the clock in the depths of Mt. Wynn 

But I don't have the clock so i can't do it

**Comment by Trixter313** [comment]
Does using the command /fixquests return the clock?

**Comment by MrDoof** [comment]
ill try

**Comment by MrDoof** [comment]
Thanks i did it and it said to look in my enderchest so i did and somehow it ended up there

**Comment by Trixter313** [comment]
Glad to hear you found it!
