### ISSUE TITLE
Trapped in Troms Powder Master Building

### ISSUE THREAD

**Issue by ByThePowerOfScience** [Wynncraft/Issues#8426]
I, as a Mage, like to teleport places.  So imagine my surprise when I tried to teleport inside the Powder Master's house and found myself inside a small nook in the wall.
![2017-06-21_01 14 43](https://user-images.githubusercontent.com/16433721/27368198-22ccd94c-561f-11e7-9c26-2934b7b3a7fd.png)
![2017-06-21_01 15 07](https://user-images.githubusercontent.com/16433721/27368200-2539e18e-561f-11e7-97fd-b9916b0da4c9.png)
I am unable to teleport out, as well as unable to use teleport scrolls.
I could use a little help.

Username: ABadHaiku_
UUID: 48a5a976-9d08-421c-b4f3-1128c8f1aeba

**Comment by ByThePowerOfScience** [comment]
I managed to free myself by using /kill, but you guys should really patch that.

**Comment by colin350** [comment]
Patched.
