### ISSUE TITLE
Liquified Emeralds

### ISSUE THREAD

**Issue by FendiTony777** [Wynncraft/Issues#8428]
Ok so basically i dropped 32 le on the ground and they disappeared after 30-40 seconds i dropped them.
And i'm sure no one else took them, they just disappeared and became invisible.

I want a refund and i want this bug fixed. I just lost all of my money!
my IGN : is FendiTony777
i'd like to get a refund of 32le

**Comment by EpicZ501** [comment]
There is a no refund policy so you can't get it back for free. Try asking the community for some or get them back normally. Also are you 100% sure no one took it because sometimes people lie about stuff like this.

**Comment by thecoolkogut4** [comment]
This is not a bug and is an intended feature. After X Amount of time (I believe it's 20 seconds) le on the ground will despawn (go away). As epic said, there's nothing you can do to get it back. At least you learnt something for next time.
