### ISSUE TITLE
Wybel Horn Spear durability showing and stats not loading

### ISSUE THREAD

**Issue by Dubinzi** [Wynncraft/Issues#8429]
I checked all of the other durability-related bug reports and tried the solutions. I have relogged, switched servers, switched classes, and dropped and picked up the item. Nothing worked. The spear looks like this http://prntscr.com/fmgnyp
Since none of the tactics worked, I decided to see what would happen if the durability ran out. When I did this, the spear disappeared. When I right clicked the slot the spear was in, it reappeared, but it still takes durability (and its stats are still not added into my total stats). 

I also want to mention that my second not-as-good wybel horn spear also is having the same issues, but none of my other weapons are.

**Comment by thecoolkogut4** [comment]
Just to clarify, when you switch to hold the weapon your health does not go down?

**Comment by Dubinzi** [comment]
After not being on for about 6 hours, when I rejoined they worked fine, so I guess it was just a temporary thing.
