### ISSUE TITLE
Stuck at Llevigar

### ISSUE THREAD

**Issue by minusoo** [Wynncraft/Issues#8430]
Im minusoo, there was a Teleport Bug:'D
I can't move or teleport out of this._.
Could someone help me:'(?

Some Screenshots:

![2017-06-21_17 16 54](https://user-images.githubusercontent.com/29607021/27392225-6d09e9fa-56a6-11e7-905c-cd90b3fa0eec.png)

![2017-06-21_17 16 51](https://user-images.githubusercontent.com/29607021/27392229-6f251ed0-56a6-11e7-9f21-7de0c0221565.png)

**Comment by ittnoraA** [comment]
Heya! If you have 5 or more soul points, do `/kill` to respawn in the nearest city you've visited.
