### ISSUE TITLE
Able to fly out the Hub

### ISSUE THREAD

**Issue by ExpiredBL** [Wynncraft/Issues#8431]
![image](https://user-images.githubusercontent.com/29357107/27392332-5395ddc4-569e-11e7-9bd8-5ea73e915ec4.png)

The coordinates are: X137 Y138 Z1815

You can fly out of the map due to the border not covering this little gap. Have not tested the extent of the distance traveled.

**Comment by colin350** [comment]
The border does cover that gap. If you fly out a few blocks, you'll hit a wall of barriers. 

The lobby world is also separate from the main world.
