### ISSUE TITLE
One Thousand Meters Under Wiki Typo

### ISSUE THREAD

**Issue by RedLogicP** [Wynncraft/Issues#8433]
The wiki page for 1000 Meters Under (https://wiki.wynncraft.com/index.php?title=One_Thousand_Meters_Under) has a typo. The line "Scientist Ynnos: I as funded by a private organization, however that seems to have stopped. So... We had to make cuts in the budget."
Should have an 'am' instead of an 'as'. Thanks!

EDIT: And this line: "Celuuse: If you go to the east, you will find Rontaid out chief scientist. He'll know what to do." (It says "out" instead of "our")

**Comment by colin350** [comment]
The wiki isn't maintained by the team who manages in-game bug reports. Instead, use the site notice at the top of the wiki, and report the issue to a wiki administrator from now.

However, I have fixed these typos.
