### ISSUE TITLE
Quest (Death Wistle) Witch won't die

### ISSUE THREAD

**Issue by vinckjonas** [Wynncraft/Issues#8434]
In the quest Death Wistle where you have to kill a witch to get 1 Pink Pelulite. I tried killing the witch but she won't take any damage. (spells or auto attacks) She keeps staying at 5100 health. I tried changing servers but didn't change anything. Only thing that worked is putting her in fire, she dies but i don't get any item.

**Comment by thecoolkogut4** [comment]
What happens if someone else trys to kill it? The problem might be that you don't do enough damage.

**Comment by vinckjonas** [comment]
I tried auto attacking her for quite some time and she doesn't take any damage at all. Not even 1. Same for spells. I am a level 53 warrior.

**Comment by thecoolkogut4** [comment]
Maybe she has a defence to the element that your trying to damage it with? (I have not done this quest in a really long time, I'm just running through some basic questions)

**Comment by vinckjonas** [comment]
Yes i know. I tried every spell, 0 dmg. The frogs next to them easily get a lot of damage. And i looked up some videos where most of them killed the witch easily :s

**Comment by thecoolkogut4** [comment]
Not too sure what else to say, your best bet is to find someone to help you, if you can't find anyone I will possibly be able to tomorrow at around this time. Sorry 😔

**Comment by vinckjonas** [comment]
I'll try to look for someone and let something know on here. Thanks for the help anyway

**Comment by vinckjonas** [comment]
Ok so i tried going full damage build and still did 0 damage to the witch. So i found a mage and he could easily deal damage to the witch. I received the item. I guess it was a minor bug that happened to me. Still weird :s

**Comment by thecoolkogut4** [comment]
That's weird, well at least you have the drop! Now it's time to get a better damage build haha.
