### ISSUE TITLE
My gear is gone

### ISSUE THREAD

**Issue by a165** [Wynncraft/Issues#8435]
When I switch roles,I found out that the gear I was wearing was gone,The other items in the backpack are still there.

**Comment by Locky1110** [comment]
If you meant you were wearing the items on one class then switch to another class, the armor will stay on the previous class. The items should still be on the previous class. Can you try showing what you did to lose the gear?












i see what you did there by putting your wynn name so u can try to get a refund
btw theres a no refund policy
