### ISSUE TITLE
Horse bug

### ISSUE THREAD

**Issue by THEVangaurdain** [Wynncraft/Issues#8436]
Traded black horses together and got a chestnut horse... but then i saw the very bottom after a few minutes of riding around... https://gyazo.com/e7532f59806b5cc9175ba7f3b5afc5a7 idk if there is a fix or a way to get a new chestnut... IGN:THEVanGaurdian

**Comment by thecoolkogut4** [comment]
What happens when you relog?

**Comment by ittnoraA** [comment]
When you breed an untradable dungeon reward horse with another, the result will also be untradable. This isn't a bug, but a feature of the game.

**Comment by LordHelmchen98** [comment]
RESOLVED
