### ISSUE TITLE
Green Skinned Trouble wrong death warp

### ISSUE THREAD

**Issue by Radalls** [Wynncraft/Issues#8438]
I found out that in the end of the quest Green Skinned Trouble, when you go in the cave beneath the lake to kill the Orc boss (I forgot his name :D), if you die fighting him you will not be tp back to Llevigar but to the very beginning of the game (the way back to Llevigar is very long :/) i try this only two times but im sure this is not right (btw sorry for my bad english im french...)

**Comment by ittnoraA** [comment]
This happens because the cave is located offmap. Whenever a player dies, they get teleported to the nearest city they've visited, but if the distance is too large, the server defaults them into the world's main spawn, which is the tutorial.

**Comment by Radalls** [comment]
so there is no solutions ? :/ i guess i need to git gud then
thx btw
