### ISSUE TITLE
problem with "The Hunger of the gerts Part 2"

### ISSUE THREAD

**Issue by SolsticeDragon** [Wynncraft/Issues#8439]
Im at the part with the captured gert and the quest book says to speak with him but whenever I try to he only says "Human! come closer gert hunger gert eat human" and no matter what I do he wont say the quest stuff, Ive tried switching worlds and I have my mask on pls help.

**Comment by colin350** [comment]
Please read the final comment of: #6964

Also duplicate of #6964

**Comment by PoweradePlayz** [comment]
that happend to me to
