### ISSUE TITLE
stage 14 taproot problem 

### ISSUE THREAD

**Issue by disciple1776** [Wynncraft/Issues#8441]
![minecraft](https://user-images.githubusercontent.com/29661192/27488708-fc6eebee-5805-11e7-8868-db0795f73810.png) 
it says that I need to talk to tiek and I right click her and it says to go in between some shadow rocks and I don't proceed so if you could plz help that would be awesome

**Comment by SolsticeDragon** [comment]
Thats whats happening with my quest

**Comment by disciple1776** [comment]
btw my name is disciple1776

**Comment by disciple1776** [comment]
Please help...

**Comment by disciple1776** [comment]
i have done it

**Comment by LordHelmchen98** [comment]
RESOLVED
