### ISSUE TITLE
Lost Tier 2 Horse after dying with full soul points and teleported to Wynn starter area

### ISSUE THREAD

**Issue by KingAiden** [Wynncraft/Issues#8442]
I was doing the quest Green Skinned Trouble and while trying to defeat Gregg'r I died. I was then teleported to the starter area in Ragni and had lost my horse luckily i had a Llvengar TP scroll and finished the quest. 
My IGN is KingAiden
I would like my Tier 2 Horse back and please fix the bug

**Comment by thecoolkogut4** [comment]
Hey there,

This is a very well known bug. When you die off map (during a quest, or for any other reason your outside), you get sent to the closest respawn point, either a town or the starting area. You are just going to have to walk back to where you died. Also, did it say in chat that you lost your horse? 

Goodluck!

**Comment by KingAiden** [comment]
Also there was no notification after i had died that my horse had been taken

**Comment by colin350** [comment]
Wynncraft enforces a strict no refund policy, a policy which applies to all players, including staff and content team members. Although this seems unfair, it's actually our method of maintaining fairness among our playerbase. – Even if you are being honest, the no refund policy still stands.
