### ISSUE TITLE
My horse disappeared

### ISSUE THREAD

**Issue by Xxkittycatman** [Wynncraft/Issues#8443]
Like 5 minutes ago I breaded 2 t1 horses and got the outcome of another t1 horse which I'm not very annoyed of. I then had to relog due to lag issues and when I came back to the game, MY HORSE DISAPPEARED! 
If by any chance you could return to me a t1 horse I'd appreciate it.
IGN: Smokey_PvP

**Comment by Locky1110** [comment]
Wynncraft has a strict no refund policy so you wont be able to get your horse back
i mean its just one brown horse there very easy to buy

**Comment by Xxkittycatman** [comment]
very easy to buy? yup let me buy it with my 1 emerald block, I didn't use my whole life savings or anything

**Comment by Catfish2013** [comment]
I have a spare if you could meet me in game.

**Comment by Xxkittycatman** [comment]
Yes pls what's your ign

**Comment by Catfish2013** [comment]
Catfish2013, I am on now actually in W21.
