### ISSUE TITLE
Server restart and i m stuck in a quest

### ISSUE THREAD

**Issue by SlimeBoyYT** [Wynncraft/Issues#8447]
I was doing the Meaningful Holiday Quest and while i was listening to the description from nick and the server restart and i m stuck in the box 
Please help fast i cant do anything

**Comment by ittnoraA** [comment]
Heya! Unfortunately your only way of getting out is to do `/kill` if you have 5 or more soul points, and redo that part of the quest.

**Comment by SlimeBoyYT** [comment]
oh thx

**Comment by LordHelmchen98** [comment]
RESOLVED
