### ISSUE TITLE
Bugged Quest (Aldorei's Secret Part II)

### ISSUE THREAD

**Issue by Snakedrive** [Wynncraft/Issues#8448]
I talked to Togak after running through his dungeon and passing all the tests.  He told me to return to Kansard and Corak and turn in my item whether it be the receipt or medallion.  I died shortly after while trying to get back to Kansard and Corak, and now neither will talk to me about finishing the quest.  I have the medallion on me which i'd like to turn in, but Kansard ignores it and simply welcomes me into the village via dialogue from the first part of the quest.

**Comment by ittnoraA** [comment]
Heya! From what you're describing, it looks like you're not talking to the correct NPC. Are you sure you returned to the exact same phase of the quest as before? If you are, try swapping the server you're on and trying again.

**Comment by Snakedrive** [comment]
Turns out I'm just mental.  I completely ignored the Kansard in the room with Togak and went to the one at the entrance of the village instead.  Thanks for the help.  Sorry for wasting your time. lol
