### ISSUE TITLE
Lost Black Horse from inventory

### ISSUE THREAD

**Issue by Xenoshard** [Wynncraft/Issues#8451]
I took my horse from my hotbar and put it in the inventory and then entered a dungeon and the horse dissapeared. It was a 20/20 Black horse ow

**Comment by colin350** [comment]
Wynncraft enforces a strict no refund policy, a policy which applies to all players, including staff and content team members. Although this seems unfair, it's actually our method of maintaining fairness among our playerbase. – Even if you are being honest, the no refund policy still stands.
