### ISSUE TITLE
Leaving guild

### ISSUE THREAD

**Issue by BobblesOwO** [Wynncraft/Issues#8452]
SO this problem has been going on for a year now. I can't leave my guild, I do /guild leave, I confirm that I want to leave and when it gives me the sign to type "yes" I do it. But when I do type yes nothing happens. I would wait or press done. Nothing happens.

IGN: Bobbles

**Comment by thecoolkogut4** [comment]
This is a well known bug and there is currently no fix for it. There's nothing that you can do.

**Comment by colin350** [comment]
#3665
