### ISSUE TITLE
quest: dwelling wall

### ISSUE THREAD

**Issue by BigHammerWang** [Wynncraft/Issues#8453]
The first attached picture is taken from DrakeM1's video in which he found a working combination. The second picture is my situation. I understand that each time you press the button, you are teleported to a new position. In these pictures we have the same X and Z coordinates but in my room there is no staircase, so I think that there must be something wrong with the map.
![1](https://user-images.githubusercontent.com/29682096/27512447-d4856adc-58f4-11e7-94f5-57ace82d223c.png)
![default](https://user-images.githubusercontent.com/29682096/27512449-d92fa6f6-58f4-11e7-9ae8-8b8f0ddbcc9e.png)

**Comment by FreeProGamer** [comment]
The coordinates aren't the same, in the video the coordinates are -16283 21395 while your coordinates are -15284 21396

**Comment by LordHelmchen98** [comment]
As already said those two positions are about 1000 block away. Anyway I'm not entirely sure about the correct combination, but it is either first button twice and second button once or vice versa.
