### ISSUE TITLE
The Lost, One of the Letters!

### ISSUE THREAD

**Issue by iObliterate** [Wynncraft/Issues#8454]
I was doing a quest named "The Lost" and i lost one of the papers so i can't complete the quest,
Please help me :(

**Comment by ittnoraA** [comment]
Sorry, but the only way you can get it back is by creating another class, leveling it up to the quest level and taking the letter from that one.

Alternatively, you can wait until `/fixquests` gets updated.

**Comment by iObliterate** [comment]
When will the /fixquests gets updated?
because i am not gonna lvl up from lvl 1 - 85!a

**Comment by LordHelmchen98** [comment]
I don't know if anyone but the developers knows this and I'm not a dev and @ittnorA is not a dev either. However it might get updated with the code refactor update, but that will take a while.

**Comment by iObliterate** [comment]
Well Guess what, If /fixquest isn't gonna get updated then why play on this server if they don't care about it! Corkus is the only good thing!
