### ISSUE TITLE
Wynncraft Map Selchar

### ISSUE THREAD

**Issue by BradMcLake** [Wynncraft/Issues#8455]
I think that you forgot to add the bank icon on Selchar because I never knew that there was a bank on Selchar and I only figured it out a week ago. Can you fix this issue, please?

**Comment by LordHelmchen98** [comment]
The bank icon on selchar is not the only thing that is wrong. It will eventually get fixed, but don't expect an immediate update only for this icon. Also there are lots of signs in the cities leading to the most important shops. You can follow them to get to the bank for example.
