### ISSUE TITLE
Stuck in a Cobweb.

### ISSUE THREAD

**Issue by KenatoMC** [Wynncraft/Issues#8456]
I can't get out of this cobweb near Pastor Nitram in the cemetery. Can a mod please tp me out..

**Comment by KenatoMC** [comment]
Nevermind, i'll /kill.

**Comment by ittnoraA** [comment]
Heya! 

If you have 5 or more soul points, do `/kill' to respawn in the nearest city to you.

**Comment by LordHelmchen98** [comment]
RESOLVED
