### ISSUE TITLE
Stuck in The Envoy Part I

### ISSUE THREAD

**Issue by SoMisterG** [Wynncraft/Issues#8457]
[https://prnt.sc/fnxpoi](url)

I am stuck in here... and i dont know what to do... anyone a tip?

**Comment by ittnoraA** [comment]
Heya! 

Looks like the script event failed to trigger. If you have 5 or more soul points, do `/kill`, and redo that part of the quest on a different server.

**Comment by SoMisterG** [comment]
Tyyyy

**Comment by LordHelmchen98** [comment]
RESOLVED
