### ISSUE TITLE
I'm stuck in the quest Out Of Mind

### ISSUE THREAD

**Issue by Zaydenn** [Wynncraft/Issues#8458]
i'm stuck in a box of invisible blocks and i cant move i need a tp.

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by Zaydenn** [comment]
yes sorry i forgot this command thx

**Comment by LordHelmchen98** [comment]
RESOLVED
