### ISSUE TITLE
Lost my items due to Timing out

### ISSUE THREAD

**Issue by KenatoMC** [Wynncraft/Issues#8463]
I traded 5 LE to BetterDenYou and timed out. The stuff he gave to me is now gone from my inventory, the items were, Adamantite, Crystal, and Stalagmites. Please return these items to me as this is truly unfair. Also BetterDenYou probably has the LE I gave to him but he can keep if anyone can donate those items to me.

Thank you!

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.
