### ISSUE TITLE
Skipped quests and lost quest item

### ISSUE THREAD

**Issue by oMirki** [Wynncraft/Issues#8466]
Since I used those Relic shrines to grind, I level up pretty quick. I started the Underwater quest and get the helmet I but I didn't finish it. Then I went to do the UnderIce quest and it took away my breathing helmet I. Now I only have Breathing helmet II. Then when I back track to do the Underwater quest using helmet II it doesn't lemme in. What should I do?
P.S. I tried /fixquests it said I haven't no missing quest items.

**Comment by LordHelmchen98** [comment]
You can start a new class and level it until you get to level 8. Then do the Underwater quest to get the Breathing Helmet I. As you share the bank with all classes you can then put the helmet into your bank and take it out with your other class. That way you can use the Breathing Helmet I for both classes.
