### ISSUE TITLE
/kill Teleported to wrong city

### ISSUE THREAD

**Issue by FreeProGamer** [Wynncraft/Issues#8467]
Hello, I was helping to my friend in the "Halloween Quest" _Not that I've already completed the quest_, and then my friend died so I did /kill to come to the exit and help him from the beginning, but, although I've visited Detlas, Nemract and some more cities a whole lot times after Olux (I visited Olux a day or two before), for some reason it teleported me to Olux.
I do not have any evidences of the incident but I can tell you that it is not the first time /kill teleports me to wrong cities, I would like this problem to be fixed as soon as possible.

**Comment by PepinhoJp** [comment]
It's because those coal Teleporters teleport you to places outside of the map, just faking that they are really near where you starated and they build that quest's area where Olux is, that's why you spawn in Olux, it isn't a bug.

**Comment by FreeProGamer** [comment]
Oh ok, thank you :+1:

**Comment by FreeProGamer** [comment]
But sometimes it even teleports me to the recruiters area, that's how I found myself there twice, one time a few days ago.

**Comment by PepinhoJp** [comment]
Sometimes the system does that, hopefully with the refactor they'll find a way of improving that.
