### ISSUE TITLE
The Envoy part 2 doesn't work

### ISSUE THREAD

**Issue by DragonWarrior411** [Wynncraft/Issues#8468]
on my Minecraft account The envoy part 2 quest is glitched, i would like to know if there is a way to reset it

**Comment by PepinhoJp** [comment]
Can you give us more info? The stage? What happened? For now, here's the list of every The Envoy quest bug report:

https://github.com/Wynncraft/Issues/issues?utf8=✓&q=Envoy

**Comment by DragonWarrior411** [comment]
I need to go inside the secret Mech base but i can't open the door to it. when i try to open the door it says I need to use the catapult first

**Comment by DragonWarrior411** [comment]
but my quest book says "Retrieve the key from the base"

**Comment by DragonWarrior411** [comment]
btw sorry if i use bad english

**Comment by PepinhoJp** [comment]
Retrieve the key from the base actually is after completing the avos stage, you have to go to Corkus vault, do the farmer/mech stage, kill Mech X and leave, you can check more here: 

https://wiki.wynncraft.com/index.php?title=The_Envoy_Part_II

**Comment by DragonWarrior411** [comment]
thx i will try again and if it still doesnt work i will tell you

**Comment by LordHelmchen98** [comment]
Seems like this got resolved.
