### ISSUE TITLE
Snow Zombies/Hungry Wendigos dropping Bob's Tear?

### ISSUE THREAD

**Issue by Pokeer** [Wynncraft/Issues#8470]
I am not sure if this is a bug or not, but I was grinding at a cave with Snow Zombies and Hungry Wendigos and I got Bob's Tear (pls lemme keep it)

![image](https://user-images.githubusercontent.com/29733433/27592247-61df1eaa-5b2a-11e7-877a-bdf55cc81cb7.png)

**Comment by PepinhoJp** [comment]
It isn't a bug, since the Gameplay Update, mobs around Nesaak drop Depressing items and Bob's Tear.

**Comment by Catfish2013** [comment]
This explains SO MUCH. Thank you.

**Comment by LordHelmchen98** [comment]
RESOLVED
