### ISSUE TITLE
Lost Sanctuary Dungeon is COMPLETELY broken

### ISSUE THREAD

**Issue by StickyPistonCinema** [Wynncraft/Issues#8471]
My friend and I spent an hour looking for the lost sanctuary chicken guardians, and got a key. When we entered the dungeon, my friend got stuck in the initial black hole thing that you spawn in for 5 minutes and then got teleported. The first part of the dungeon is to run across the bridge in time, but when we started running barriers just block the way and we can't do anything. We've run back to the beginning and then tried to restart multiple times, and we've also used teleportation scrolls to get out and try to restart the dungeon, to no avail. Please help.

**Comment by RubbrDucky** [comment]
Try using 1.8.9.

**Comment by ittnoraA** [comment]
You should try swapping onto a recently restarted server, and using any 1.8 version just in case if the system behind the bridge creates client side ghost blocks.

**Comment by LordHelmchen98** [comment]
As already said you should use 1.8 (1.9 should be done as well). This is because Wynncraft is hardcoded for 1.8 and higher versions are allowed but often cause issues.
