### ISSUE TITLE
When putting a quest item in your inventory making it full it says items has been dropped on the ground

### ISSUE THREAD

**Issue by Norsee** [Wynncraft/Issues#8473]
I went to the bank and put the yellow crystal quest item in my inventory when there was one available spot left and it says in the chat that items has been dropped on the ground.

![image](https://user-images.githubusercontent.com/29736224/27599869-5cec8a0a-5b6a-11e7-8b65-d2cc425a8f3f.png)

**Comment by ittnoraA** [comment]
The server gives you this message whenever you exit bank while your inventory is full. This is to notify players about the chance of the item they're currently holding being dropped, since the server cannot detect it happening.
