### ISSUE TITLE
Stuck in Ice Barrows HALP

### ISSUE THREAD

**Issue by kael558** [Wynncraft/Issues#8474]
I am stuck in the ice barrows dungeon after the invisible bridges. The door wont open. I can hear the pressure plate clicking. And the first time, there were particle effects on the door, but it did not open. And it still won't open. World-hopping does not fix.
![bandicam 2017-06-27 13-45-40-506](https://user-images.githubusercontent.com/26678074/27601939-06752fae-5b3f-11e7-9ba9-cefe8a0abf00.jpg)
![javaw 2017-06-27 13-46-07-193](https://user-images.githubusercontent.com/26678074/27601947-0a4883d8-5b3f-11e7-9e86-383fc83c1a7e.jpg)

**Comment by ittnoraA** [comment]
You might've swapped into a world where it was broken. Just try swapping to a recently restarted server with only a few people in it.

**Comment by kael558** [comment]
thats strange because I didn't swap at when I was in as there wasnt a reason to. And yeah you're right about switching to a recently restarted server, cause that makes it work. Thanks
