### ISSUE TITLE
ChestPlate

### ISSUE THREAD

**Issue by KasaiGaming** [Wynncraft/Issues#8475]
I was in Detlas and having some lagging problems when the game kicked me out. I rejoined only to find that a very useful LEGENDARY chesplate that I was going to use was gone form my inventory. I rejoined multiple times but to no avail and I still don't have it. I understand its a bug but I really want that chestplate back because I killed tons of mobs while grinding to get it PLZ GIVE IT BACK

**Comment by ittnoraA** [comment]
Sorry for your loss, but unfortunately Wynn enforces a strict "no refunds" policy, which means you're not getting your item back.

**Comment by KasaiGaming** [comment]
Thank you and I understand but could u try to prevent this from happening
again?

**Comment by ittnoraA** [comment]
The developers of Wynn are working on an update to fix most of the currently existing known bugs and glitches
