### ISSUE TITLE
Dwelling walls quest

### ISSUE THREAD

**Issue by beastbb** [Wynncraft/Issues#8476]
I've completed the quest objectives until talking to Leucsaa, however, I don't have the specified book picked up to hand in, the book is placed on the floor, but I'm unable to pick up/interact with the book. the quest is currently located at nemract, please help

**Comment by ittnoraA** [comment]
Heya! The book is a mob which you need to kill to receive the drop.

**Comment by LordHelmchen98** [comment]
RESOLVED
