### ISSUE TITLE
Meaningful Holiday Quest : questbook didn't actualize 

### ISSUE THREAD

**Issue by SydObs** [Wynncraft/Issues#8477]
everything is in the title,
I was doing the quest Menaingful Holiday, and When I talked to Reshad, the stage 7 of the mission
He said his text, then Nick talked and said he will teleport me to Santa but it didn't teleport me and the quest book is stuck in the same step. when I talk again with Reshad, it doesn't repeat the quest.

![2017-06-28_12 17 05](https://user-images.githubusercontent.com/29751647/27632697-cf903db2-5bfc-11e7-8f95-d0e2cbdc9b78.png)
![2017-06-28_12 17 12](https://user-images.githubusercontent.com/29751647/27632698-cf90ba26-5bfc-11e7-92c2-03989dda4569.png)

**Comment by ittnoraA** [comment]
If you looked to your left during the cutscene, you might've seen Nick opening up the teleport for you. If you missed it, just swap the server you're on and talk to Reshad again.

**Comment by SydObs** [comment]
unfortunately, it is not.
I tried to switch on different servers, switch between my different class ect...
Still the same voice 

![2017-06-28_13 39 28](https://user-images.githubusercontent.com/29751647/27635497-8731215c-5c07-11e7-9467-091385f84669.png)
