### ISSUE TITLE
Wynncraft Excavations Site B Bug

### ISSUE THREAD

**Issue by BebopBLT** [Wynncraft/Issues#8480]
So i was doing the mission just like a normal person and boom when i finally finish the mission, it says reward : 1536 emeralds. I look in my inventory and i only have a block of emerald HALP.

~ BebopBLT

**Comment by PepinhoJp** [comment]
Wynncraft has a strict no refund policy, so they can't give you items that you lost back, next time try not having any emerald/emeralds blocks/liquid emeralds on your inventory, they might bug your emerald quantity, sorry.
