### ISSUE TITLE
Disapearing horse

### ISSUE THREAD

**Issue by SanicSpeedz** [Wynncraft/Issues#8482]
This is the 2nd time this happend. I had a black horse and when I placed it it glitched out of my inventory. I really dont want to spend like 3 le on a black horse a 3rd time. Can one of you help me or give me a new horse?

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.
