### ISSUE TITLE
Stuck inside blocks

### ISSUE THREAD

**Issue by SGTSCHMOO** [Wynncraft/Issues#8484]
I'm stuck inside blocks and I can't find any possible ways get out. I was in a middle of an quest and open a piston door and slammed me inside. Hoping if there is another way to get out
![2017-06-28_23 49 18](https://user-images.githubusercontent.com/29767385/27670670-7adcf93a-5c5c-11e7-91dd-2a90075eb5b2.png)

**Comment by PepinhoJp** [comment]
Duplicate of #88

You can also use a teleport scroll, you have enough soul points so you won't lose anything.

**Comment by llamabrine** [comment]
do /kill

**Comment by PepinhoJp** [comment]
That's what's written  if you click on the duplicate number....

**Comment by LordHelmchen98** [comment]
RESOLVED
