### ISSUE TITLE
Lost My Exile in a hopper in a dungeon.

### ISSUE THREAD

**Issue by SuchAlex** [Wynncraft/Issues#8485]
I lost my exile dagger inside a hopper inside a dungeon (undergrowth) I accidently dropped it in there.

![2017-06-23_21 47 15](https://user-images.githubusercontent.com/29379267/27671282-a2d908da-5c47-11e7-9c10-af2f7beed487.png)

Please possibly get it back?
That is my previous picture of that.

**Comment by PepinhoJp** [comment]
Duplicate of #7183

They won't give your item back even if you have proof that you had the item, sorry.

**Comment by SuchAlex** [comment]
Aww okay
