### ISSUE TITLE
Quest: A Grave Mistake

### ISSUE THREAD

**Issue by ColorBlind386** [Wynncraft/Issues#8487]
I was doing the quest: A Grave Mistake and when i was done at the end cutscene it just stopped and i was stuck in an invisible cube i did /kill and i went back and did the quest again but nothing happened so i can't do the quest and i did not get the reward... :(

**Comment by PepinhoJp** [comment]
Switch servers, the command blocks in your server were probably bugged, you have to do the cutscene again before continuing the quest.
