### ISSUE TITLE
Event Happening When Already Completed

### ISSUE THREAD

**Issue by lookItsAPootis** [Wynncraft/Issues#8488]
The link shows you what the bug is.
I'm new to making threads.
So I think it goes in the brackets. If not copy the link and paste it.

[https://www.youtube.com/watch?v=irzTaZ6msr8](url)

**Comment by lookItsAPootis** [comment]
It Is the quest I showed at the end of the book.

**Comment by lookItsAPootis** [comment]
I thought the username would change.

**Comment by lookItsAPootis** [comment]
oh well ¯\_(ツ)_/¯

**Comment by PepinhoJp** [comment]
There's no way of preventing that, the server gave you permission to enter that place and you'll keep that permission forever in that class, that's the same thing that happens with Memory Paranoia, you can do everything again.
