### ISSUE TITLE
EXP Glitch (ToA)

### ISSUE THREAD

**Issue by TheOGPickle** [Wynncraft/Issues#8489]
So I just completed Tower of Ascension on my level 40 mage. With this, I was expected to level up around 10 levels, but for some reason, the game decided to give me exactly the amount of xp I needed to level up once. I was supposed to receive 925000xp, however, I only received 46100xp even though both my xp indicator (Wynn Enhanced) and the post-quest log both stated I received 925000. Whether it's a glitch or if it's intentional, I rather not spend a lot of time on a quest and get nothing out of it, so if possible please look into this.

**Comment by numbermaniac** [comment]
This quest is scaled so that you can't collect the shards using a level 100 class and then use them with your lv40 to finish the quest effortlessly. See https://github.com/Wynncraft/Issues/issues/6312#issuecomment-251015599.

**Comment by LordHelmchen98** [comment]
RESOLVED
