### ISSUE TITLE
Lose Accessories when change class

### ISSUE THREAD

**Issue by Skyline294** [Wynncraft/Issues#8490]
After you /class, sometimes your skill points glitch to all 0 and makes the accessories require for skill points be taken off automatically. If your inventory is full, the accessories will simply disappear rather than dropping on the ground. 

I have lost my morph-ruby and clockwork (it's super hard to get a new one) due to the glitch. And I heard several other people lost valuable accessories because of it. Please fix.

**Comment by PepinhoJp** [comment]
Many people already lost items because of that bug, it's because your items load before your skill points, hopefully it'll be fixed with the code refactor.

**Comment by LordHelmchen98** [comment]
This is a well known issue and the devs already know about it so as already said we can only hope it's possible to fix that soon.
