### ISSUE TITLE
Dropped items disappear on V.S.S Seaskipper

### ISSUE THREAD

**Issue by Tejester** [Wynncraft/Issues#8494]
So I accidently dropped my black horse on the V.S.S Sea skipper and wasn't able to retrieve it. It in fact disappeared once it hit the floor of the boat. Please fix this bug so it doesn't occur again.

**Comment by PepinhoJp** [comment]
Sorry, Wynncraft has a strict no refund policy, so they can't give you items back, it isn't a bug, you probably dropped your horse near the hopper and it was "pulled". The floor doesn't make items disappear.

**Comment by Hegezcc** [comment]
But can one get those items back? I read someone threw a chestnut horse to hopper. What if someone accidentally thows in a white horse? Or quest item?

I think there should be a way to get those items back if they aren't valid V.S.S. Seaskipper tickets (or other items, as there are hoppers also in other places than docks).

**Comment by PepinhoJp** [comment]
Wynncraft has a strict no refund policy, if a quest item bugs (You cant drop them), you can try /fixquests to get the item back, if you dont get the item back, youll have to create another class to get the item, they can't know if you never had the item or if you really accidentally dropped it, it's the player's fault, it isn't a server-sided buh

**Comment by Hegezcc** [comment]
I know that Wynn has this policy. But could the hoppers be locked to allow only items they want? Hoppers are used in lots of places, and this would fix the bug but also allow determining what items the hopper wants. Eg. also in boss altars or hidden places
