### ISSUE TITLE
I am stuck in a block 

### ISSUE THREAD

**Issue by InesorEmilize** [Wynncraft/Issues#8495]
Hello please help me, I'm emilize and trying to explore a mountain I got stuck on a block surrounded by invisible block.I can't do anything I have try to me teleport with my stick and the teleportation card but nothing works.PLEASE help me :)

Thanks Emilize

**Comment by InesorEmilize** [comment]
I'm in X:-816 Y:124 Z:-1371

**Comment by InesorEmilize** [comment]
![aab79a97-9b5b-445d-9d4b-5cef83dce7ab](https://user-images.githubusercontent.com/29802751/27750297-7c8e6f12-5dd7-11e7-93d7-dfb79ae6b1b6.png)
![Uploading 2017-06-30_21.01.37.png…]()
![2017-06-30_21 01 39](https://user-images.githubusercontent.com/29802751/27750354-c24280de-5dd7-11e7-8518-37e146568fb7.png)
![Uploading 2017-06-30_21.01.48.png…]()

**Comment by InesorEmilize** [comment]
its ok i have do /kill

**Comment by AscendedKitten** [comment]
Sorry for the late reply, but as you found out you can use /kill in order to be teleported to the closest town, in case you have enough soulpoints.
