### ISSUE TITLE
one thousand meters under

### ISSUE THREAD

**Issue by Kolking3268** [Wynncraft/Issues#8502]
My computer crashed when I was at the first island 100 meters under, when I log back in I am in the jofash dock. I hope this will be fixed, now I have to get all the way back

**Comment by PepinhoJp** [comment]
This isn't a bug, it's to prevent the quest from bugging.

**Comment by AscendedKitten** [comment]
I am sorry for what you experienced, it's due to the current respawn system; upon death you'll be teleported to the closest town, and for offmap-areas this sometimes happens to be a rather distant location.
