### ISSUE TITLE
Extreme fps lag

### ISSUE THREAD

**Issue by KingRoob** [Wynncraft/Issues#8503]
I just logged in for the first time on my new computer after not playing because of fps problems on my old laptop. I am in Detlas and have 6 fps, the problem is, I have a GTX 1060 6gb, a i5 7600k and 16 gbs of RAM. I have 5 gbs of ram dedicated to the game and for some reason I only get a maximum of 16 fps, I have Optifine and I have set everything to fast and particles off, and my frames go down... My friend who has a i3 4170 and a GTX 960 gets 300 fps, I am very confused why I am lagging at all. It's only on this server on everything else I get north of 400 fps and in the lobby I am not lagging at all but as soon as I join the actual game I get 16 fps, please help.

**Comment by thecoolkogut4** [comment]
Are you playing with any mods? What happens when you turn them off?

**Comment by Louis-D** [comment]
Mind removing optifine? Optifine reduces performance on high end systems.
Also make sure your java is updated and 64bit. If your would mind sending us your settings that would be great.

**Comment by KingRoob** [comment]
I removed optifine and my frames as soon as I joined the server were around 150 then after a minute they went down to 14, also the longer the stay on the server the more my frames decrease. As for my settings: I have unlimited max fps, fast graphics, clouds off, vsync off, vbos is on and my render distance is set to 2, all of my drivers are up to date but for some inexplicable reason the problem persists.

**Comment by thecoolkogut4** [comment]
Try playing without the texturepack. Disable it in the server options. This should fix it. If It does, I'll tell you how to reenable it (hopefully without lag).

**Comment by Umbrew-Foxiroe** [comment]
Something that comes to mind may be the area you're in--well, more specifically, what's going on around you. You set particles to decreased or better yet minimal, right? If not, do that if possible. Maybe try going to somewhere less crowded than Detlas, or just a low population world in general. High pop worlds + Detlas tend to kill my FPS occasionally, really depends on what everyone there is up to and how many of them have particles coming from them, atleast for me.
Minecraft version could also be part of it, so knowing your MC version of your client may be helpful... Might be a version with a known RAM leak or something.

**Comment by ittnoraA** [comment]
If your framerate starts from a high amount and starts dropping, try lowering your view distance. Overtime, more and more chunks get loaded without getting unloaded, which causes severe fps issues even on high end systems.

**Comment by KingRoob** [comment]
I had turned off the servers texture pack and I didn't experience any frame lag for like 15 minutes but then I started getting somewhere around 20 fps. I am using a 64x64 resolution texture pack regularly and a few mods in 1.8.0, I do not think it can be a ram leak because it's only on Wynncraft, on every other server I do not experience any sort of frame lag, and yes my particles are turned down to minimal. I went to the dock near Nesaak to do a quest and I was getting 3 fps where there are no players and minimal entities. The server I was on had around 30 people on it and I only saw a few people while I was in Detlas. My view distance was on 2 and I had around 750fps in the middle of nowhere but over time it dropped down to like 20 while I was doing quests. Here is my fps when I first log in and 25 minutes later: http://imgur.com/a/nVFaK, I have the same settings I said before but I have the custom texture pack on.

**Comment by Umbrew-Foxiroe** [comment]
"in 1.8.0" I think there's the main issue. You're using 1.8.0 instead of 1.8.9 or whatever the highest version of 1.8 was. There's a good reason why people don't use low sub versions of updates like 1.8

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
