### ISSUE TITLE
Free monthly crate issue

### ISSUE THREAD

**Issue by Venemian** [Wynncraft/Issues#8504]
Its 1/7/17 and I claimed the crate as minecraft was loading up. I put in name (EsseoS) and clicked redeem and it sent me back to the store homepage so I figured I claimed it.

I went in game and clicked manage crates and it says I do not have any and I when I try to click the monthly crate post-it note or checkout button, it reloads the page for a millisecond and it puts me back at the store homepage. Help me please!

Restarting my browser did not help either.

**Comment by PepinhoJp** [comment]
You didn't go to the checkout page so you didn't claim it, wait some hours, last month only had 30 days and the one before had 31, wait some hours/tomorrow if you still can't claim it, reply here.

**Comment by Venemian** [comment]
I waited until 12 AM and tried it again and it didn't work. Same issue with
the page reloading no matter if I press the free crate post-it or checkout
button.

I tried one more time just now 9:27 and it still doesn't work. Same issue.

**Comment by PepinhoJp** [comment]
I tried claiming it for you, but I also couldn't, this happens when you can't claim your crate yet. Unfortunately we can't see when it will reset.

**Comment by Venemian** [comment]
So is there a way to fix this, or do I have to wait a month -_-

**Comment by Venemian** [comment]
7/5/17 still not working.

https://youtu.be/W2DVU0UsUSM

**Comment by Venemian** [comment]
please watch that video

**Comment by PepinhoJp** [comment]
Sorry for the late reply, email support@wynncraft.com

**Comment by LordHelmchen98** [comment]
If you haven't mailed them yet and it's still not working, you should do what PepinhoJp said.
