### ISSUE TITLE
i cant turn off my attack effect particle

### ISSUE THREAD

**Issue by Frostlyy** [Wynncraft/Issues#8505]
i cant turn off my attack effect particle, i tried to go to compass -> attack effect -> and press the same effect that are currently in use, but it doesnt do anything. i can turn off my player effect by doing this process but i cant see any way to turn off the attack effect. if this is a bug pls fix it and if it isnt can someone tell me how to turn the attack effect off? thankss ^^

**Comment by ittnoraA** [comment]
Are you sure you're clicking the correct effect? Crate rewards can have duplicates, and only re-clicking the same effect will disable it.

**Comment by Frostlyy** [comment]
i did. i tried using my emerald effect (no duplicate from crates) and re-click it to disable it, but it doesnt seem to work.

**Comment by Frostlyy** [comment]
anyone know any solution or is this just a bug? pls help

**Comment by UsernameJoe** [comment]
Same Problem with the fire particles...

**Comment by Catfish2013** [comment]
I also am having this exact same bug. It happens to me about 50% of the time.

**Comment by Catfish2013** [comment]
Opps, thought I was on a different thread. But I am having this bug to.

**Comment by FighterZ** [comment]
I am experiencing the exact same issue with all of my attack particles... I loved the dark mages default animation but for some reason i can't turn it off :(. I have tried many different ways and tried asking my guild friends but most of them doesn't seem to have this issue. Is this bug fixable? ty

**Comment by LordHelmchen98** [comment]
It's a known bug with attack effects. Sometimes it randomly resets, but you can't do it manually.
