### ISSUE TITLE
Recommended Minecraft version

### ISSUE THREAD

**Issue by xJon** [Wynncraft/Issues#8506]
I'm aware that in the past the recommended version, especially because of the horses, was 1.8.9.
Did Wynncraft update since?
Thank you!

**Comment by PepinhoJp** [comment]
You can use Wynncraft on 1.8 - 1.12, the best version still is 1.8, but you can't see the boss bar that tells you if there is/isn't DXP.

Please post issues here, bug reports, you can ask questions on the Discord Channel or on the questions section on the forums.

**Comment by xJon** [comment]
Thank you for the information.
