### ISSUE TITLE
V.S.S Seaskipper BIG Bug

### ISSUE THREAD

**Issue by mmilosz2003** [Wynncraft/Issues#8507]
i  threw my horse in the V.S.S Seaskipper and my horse has been Deleted!!

GIVE MY HORSE BACK!!!!!!!!!

THATS THE WORST BUG I EVER SEE IN MY LIFE

#RipMyHorse

**Comment by ittnoraA** [comment]
Players making mistakes is not a bug. I'm sorry to hear you lost your horse, but Wynn enforces a strict no refunds policy, which means you're not getting it back. You can try asking the community for help or try buying a new one here: https://forums.wynncraft.com/forums/trade-market.71/
