### ISSUE TITLE
Tier 4 Chest by Emerald Trail unavailable in 1.12

### ISSUE THREAD

**Issue by ComputerDude** [Wynncraft/Issues#8509]
In 1.12, fences now can connect to unsolid blocks, **such as stairs**. The Tier 4 chest location by Emerald Trail/Nivla Forest requires clicking between a fence and stair block, but users in 1.12 cannot since the fence connects to the stair.

**Comment by PepinhoJp** [comment]
Can you send coords? They are better than descriptions.

**Comment by ComputerDude** [comment]
-435 57 -1708. I got a screenshot of the glitch happening too:
![2017-07-02_18 38 26](https://user-images.githubusercontent.com/13712758/27774012-daab1a58-5f55-11e7-9e14-8533806f6682.png)

**Comment by LordHelmchen98** [comment]
Well as 1.12 is a very recent version, there are some issues that can occur. Best option would be to use a lower version, but I'll pass this to a builder so they can maybe do something here.
