### ISSUE TITLE
Climbing Helmet Bug

### ISSUE THREAD

**Issue by 7Angrybirdman7** [Wynncraft/Issues#8514]
Hello Wynncraftian!

I was doing the Zhight Island quest and had to go to Maro Peaks, in which I needed the climbing helmet. When I put on the helmet, there was a short loading screen (the screen was just dirt blocks) and somehow deleted my actual helmet. I have no idea how it happened, and would like it fixed.

Thanks,
7Angrybirdman7

**Comment by ittnoraA** [comment]
Heya! You can do `/fixquests` to retrieve the helmet.
