### ISSUE TITLE
Boat = 20,000 leagues under the Sea

### ISSUE THREAD

**Issue by RefuseHazard** [Wynncraft/Issues#8515]
Hello,
Sorry for my exelent english (#joke), i experiment the boat (buy for 2EB) [because i don't want to pay some tickets many times].
And the problem was, when i drive this, my boat flows... Impossible to drive on the water (but in.... ;) )
That All for that.

After my personal problem, and want to reach Elkurn passing by the river, put in the river and want to get in. *Pouf* The boat gone... Impossible to found him (by rightclicking), so now i have paid 2EB for... totaly nothing...

**Comment by thecoolkogut4** [comment]
Boats are glitchy in 1.9 and up. If you want to use it, play with Mc version 1.8.x

**Comment by colin350** [comment]
If you are stubborn about changing versions, alternate methods of travel include: scrolls, the seaskipper, horses, and spells.
