### ISSUE TITLE
Guild

### ISSUE THREAD

**Issue by PhantomSlayer24** [Wynncraft/Issues#8516]
I changed my name after I joined a guild and now I can't leave the guild i'm in.

**Comment by RubbrDucky** [comment]
Known issue. Happened to me too. We just have to deal with it until a guild
rework.

**Comment by colin350** [comment]
#3665 
[Example Duplicate Search](https://github.com/Wynncraft/Issues/issues?utf8=%E2%9C%93&q=guild)
