### ISSUE TITLE
i stuck in a block

### ISSUE THREAD

**Issue by bar8484** [Wynncraft/Issues#8517]
i played on your server i switched server from 12 to 2 and then i lagged and now i am stack in a block i went afk that you will be able to teleport me to somewhere normal please help me!!!

**Comment by PepinhoJp** [comment]
Duplicate of #88 

Just /kill with +6 soul points to leave the area or use a teleport scroll, mods don't tp people out from places.

**Comment by colin350** [comment]
[Example Duplicate Search](https://github.com/Wynncraft/Issues/issues?utf8=%E2%9C%93&q=stuck%20in%20block)
