### ISSUE TITLE
Teleported up when re log

### ISSUE THREAD

**Issue by gogodiego123** [Wynncraft/Issues#8518]
When I leave a server and come back, occasionally I will be teleported to the highest block, this is annoying because if I'm in a cave ill be teleported above it and usually out of the map. I'

m running out of soul to do /kill all the time. For example I'm trying to get to bobs tomb but when I re log I get tped out of the map, its quite annoying.
![stuck](https://user-images.githubusercontent.com/29901247/27841950-2cd2f53e-60ba-11e7-98c8-de5fba0e44bf.png)
this is behind those mountains where I spawned

**Comment by PepinhoJp** [comment]
Known issue, hopefully will be fixed later.

**Comment by PepinhoJp** [comment]
Read this issue: #8139
