### ISSUE TITLE
Quest Item

### ISSUE THREAD

**Issue by UnknownAccount404** [Wynncraft/Issues#8520]
i have this Quest item that wont go away even though i have completed the quest is there any command to get rid of this?

**Comment by UnknownAccount404** [comment]
![item](https://user-images.githubusercontent.com/29905337/27845314-1e4dabd4-60e3-11e7-8e11-1dd22147c994.png)
heres the item

**Comment by thecoolkogut4** [comment]
Fill up your inventory with emeralds, right click 2+ emeralds (so you split them in half)then click the clock. When you click the clock ESC out of your inventory and it should be gone. YOU MIGHT NOT BE ABLE TO GET IT BACK AFTER YOU DO THIS. USE WITH CAUTION

**Comment by UnknownAccount404** [comment]
alright thnx

**Comment by PepinhoJp** [comment]
Or you can just put it in your daily reward chest, it's easier

**Comment by quesswho** [comment]
This is not a glitch

**Comment by LordHelmchen98** [comment]
@guesswho if he finished the quest this is a glitch 
It seems to be resolved tho.
