### ISSUE TITLE
The Bigger Picture's razorouse king

### ISSUE THREAD

**Issue by Eskoidi** [Wynncraft/Issues#8523]
I've been stuck on The Bigger Picture quest's stage of killing the razorouse king for ages now, because the thing has so much health and regeneration, but not only that, it doesn't drop the needed item when I finally get it killed after god knows how long time of spamming the mouse's left button. I now have killed the king twice and both times it has not dropped the item needed for the hopper to continue.

**Comment by PepinhoJp** [comment]
Mobs not dropping items happens sometimes, you'll have to kill it again.
