### ISSUE TITLE
Broken fierte

### ISSUE THREAD

**Issue by Strikez121** [Wynncraft/Issues#8524]
So I haven't joined wynncraft in over 2 years and when I came back my Fierte remained in its old state and couldn't be identified/
![screen shot 2017-07-05 at 4 02 20 pm](https://user-images.githubusercontent.com/29914449/27863792-56849cde-61be-11e7-9788-fa2afc6e968b.png)

**Comment by thecoolkogut4** [comment]
This is because it has the é character. This is also a well known bug. There is nothing you can do at the moment to fix it. You can either keep it as a collectable, or throw it in the detlas trash. (Against the rules to sell it)

**Comment by colin350** [comment]
@thecoolkogut4 also didn't mention that besides the é character being an issue, many weapons were revamped after the Gavel update. This includes the Fierté. So although you still have it as a souvenir, it won't be of any use anyways.
