### ISSUE TITLE
Pet Menu Glitch

### ISSUE THREAD

**Issue by Marc0124** [Wynncraft/Issues#8527]
So this has been a issue for me for a while. When ever I open up my pet menu it just looks like this. http://imgur.com/6UKwuGd

I really have no clue how this happened. One day I opened my menu and it was like that. Sorry if someone already reported on this issue. I tried looking for some but didn't find any. Thanks any have a great and awesome day!

P.S this causes me to spawn pets, but never despawn them. So right now I have 3 creepers out and I cant despawn them, so it gets annoying.

**Comment by PepinhoJp** [comment]
Hey, your /use menu is corrupt, an admin will have to fix that, please email support@wynncraft.com
