### ISSUE TITLE
Potion Making Quest Glitch

### ISSUE THREAD

**Issue by BritSenpai** [Wynncraft/Issues#8530]
The quest is stuck, and I can't progress in it. The NPC "The Assistant" asks for 8 red mushrooms which I've already given him. I can't fight the mini-boss down the stairs because the quest things I haven't progressed.

Screenshots:
http://imgur.com/a/6ejWP

Thanks.

**Comment by PepinhoJp** [comment]
The Assistant will keep asking you to bring mushrooms, but you have to enter the house, go downstairs and kill the boss, if the boss isn't spawning, leave the boss room, switch servers and enter it again, that should fix.

**Comment by BritSenpai** [comment]
Thanks!

**Comment by colin350** [comment]
Please use our search feature next time before creating a new issue. Thank you.
