### ISSUE TITLE
Item lost glitch

### ISSUE THREAD

**Issue by roythepixel** [Wynncraft/Issues#8532]
I accidentally dropped my breathing cap but I picked something up as soon as I dropped it and since the game doesn't let you drop quest items, it tried to give the item back but glitched since my inventory was full. I know that the breathing cap is used for later quests so if an admin reads this, if you can give it to username: roythepixel, it would be greatly appreciated.

**Comment by PepinhoJp** [comment]
/fixquests if you lost Breathing Helmet I

Go to Nesaak and buy another one if you lost Breathing Helmet II
