### ISSUE TITLE
Finding The Light - Taproot bugs away

### ISSUE THREAD

**Issue by PardeyxD** [Wynncraft/Issues#8535]
I did the Taproot Quest and got the Taproot i need for the Finding The Light Quest.
I put it in the chest but finally it bugs away out of my Chest so i cant do the Quest :(

Can any Supporter help me with this problem, because i can't get the item again by doing the steps from the Taproot Quest?

**Comment by ittnoraA** [comment]
Heya! Try typing `/fixquests` to retrieve the item. If that doesn't work, you're unfortunately going to need to redo that quest on a different class to get the item back.

**Comment by PepinhoJp** [comment]
Try /fixquests to get the item back.

**Comment by PardeyxD** [comment]
Thank you very much :) I didn't know that command
