### ISSUE TITLE
[quest bug?] Stuck on Creeper Infiltration, no idea what to do.

### ISSUE THREAD

**Issue by wdtfshi** [Wynncraft/Issues#8536]
I'm trying to do the creeper infiltration quest and I seem to be stuck, after talking to Thomas he told me to follow the right wall through the ravine to find the cave and get some stones. After finding the cave I fought the pigmans. At the end of the cave there's the black teleporter thing to the top of the mountain, then a creeper appears and blows you away back to the ravine village. It says on chat that I should talk to Thomas about what I just saw, but the only thing he says is "I see you've come back, but you don't have what I asked for. I can't do anything until you fulfill your task.". I have no idea what to do now, every time I try to get to the top of the mountain the creeper keeps blowing me away. Any help is highly appreciated.

**Comment by mmilosz2003** [comment]
every time when the creeper blow up and your back to ravine village then near you can you find creeper skin when you got that then give it to Thomas

**Comment by wdtfshi** [comment]
Yeah I know that, I can't pick that up either. (I do have space in my inventory

**Comment by RubbrDucky** [comment]
u have to kill it

**Comment by AscendedKitten** [comment]
As @RubbrDucky mentioned, it's not a dropped item but an entity you have to hit before it drops the actual item.

**Comment by LordHelmchen98** [comment]
RESOLVED
