### ISSUE TITLE
Can't edit my Shop thread

### ISSUE THREAD

**Issue by SousNapTime** [Wynncraft/Issues#8537]
So, My shop thread on the trade market section cannot be edited via more options due to this:

http://prntscr.com/fsfhpd

I was recommended to start a new shop but, I don't wanna lose my views and rep for it. Any suggestions or solutions are much appreciated.

**Comment by thecoolkogut4** [comment]
Use a differet browser (safari, Firefox, etc...) and I'm 99% sure it will work.

**Comment by AscendedKitten** [comment]
That's not a bug with Wynncraft Forums or anything related; it's due to your browser blocking a certain feature of the scripts run by the website. I'd recommend you to either try another one, or change your browser-settings (maybe also clear cache)
