### ISSUE TITLE
Thousand Meters Under: 4 typos in dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#8540]
3/11: full stop missing at the end of the sentence.
![2017-07-02_18 08 58](https://user-images.githubusercontent.com/5206120/27939861-cd5400dc-630a-11e7-9b11-b8fe481481e4.png)

1/3 (bottom): Missing colon after Olof.
![2017-07-02_18 20 02](https://user-images.githubusercontent.com/5206120/27939890-f11c4d08-630a-11e7-984f-42dafdd02e0d.png)

3/3: Also missing colon.
![2017-07-02_18 20 11](https://user-images.githubusercontent.com/5206120/27939908-0c619ce4-630b-11e7-9bba-19a6a1004465.png)

3/3: Another missing colon.
![2017-07-02_18 31 12](https://user-images.githubusercontent.com/5206120/27939947-2834ae8e-630b-11e7-85cc-23e6add74e18.png)

**Comment by colin350** [comment]
Fixed!
