### ISSUE TITLE
Thousand Meters Under: 2 typos at end of quest

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#8541]
7/10: Missing full stop at end of sentence.
![2017-07-02_18 53 09](https://user-images.githubusercontent.com/5206120/27939977-56377924-630b-11e7-8c2b-57183fe0d887.png)

1/2: "that we your crewmates are gone"; I don't think "we" should be there.
![2017-07-02_18 54 27](https://user-images.githubusercontent.com/5206120/27939989-6a43cab2-630b-11e7-91dd-888ca02abdda.png)

**Comment by colin350** [comment]
Fixed!
