### ISSUE TITLE
Recipe for Disaster: Typos in Brie's and Talking Mushroom's dialogue

### ISSUE THREAD

**Issue by numbermaniac** [Wynncraft/Issues#8542]
1/8: "decided **to to** make the Zork Stew"; duplicate "to":
![2017-07-04_12 36 34](https://user-images.githubusercontent.com/5206120/27940043-b3f24e9a-630b-11e7-906e-2b4459b8de89.png)

between 6/9 and 7/9: "you pick to mushroom up"; I think "to" should be "the":
![2017-07-04_13 06 26](https://user-images.githubusercontent.com/5206120/27940068-da1a700c-630b-11e7-9e3e-28de397ce171.png)

**Comment by colin350** [comment]
Fixed!
