### ISSUE TITLE
Ice Barrows Dungeon: Final boss room, can't leave.

### ISSUE THREAD

**Issue by Catfish2013** [Wynncraft/Issues#8545]
Hello, I tried the Ice Barrows Dungeon for the first time today, and when I defeated the boss, I was not teleported out. I will try again later and see if I have the same problem, since my guild members haven't had this trouble, and I didn't see anyone with this issue when I looked through all the reported glitches. Any suggestions would be nice, I'll update this once I try again.

**Comment by LordHelmchen98** [comment]
Sometimes it doesn't teleport you out. Sometimes it even happens more than once.  Is a well known issue with dungeons. You just have to wait until the boss respawns, but don't do /class or log out as that will kick you out of the dungeon.
