### ISSUE TITLE
Flight in Distress

### ISSUE THREAD

**Issue by MrQueenSIr** [Wynncraft/Issues#8546]
so i have almost finished the quest i defeated the witch and my book says to go back to captain ackbar, but i im stuck in a coal room with a tripwire hook and i can not get out to finish the quest no matter if i /kill myself or not it just makes me do the quest over and over with the same problem occuring

**Comment by ittnoraA** [comment]
Did you try swapping the server you're on before retrying the part?

**Comment by ZeUnlucky** [comment]
@MrQueenSIr could you send a screenie?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
