### ISSUE TITLE
A Fighting Species

### ISSUE THREAD

**Issue by NateSaysYo** [Wynncraft/Issues#8548]
Hi, I was doing the A Fighting Species quest and I beat the boss and walked through the door and took off my current helmet and it hit me with the message the the Orcs don't want me here and it some how dropped the Orc mask when my inventory was full and now I can't complete the quest and I would really appreciate it if a moderator would help me as soon as possible.

**Comment by thecoolkogut4** [comment]
Type /fixquests to get your item back.

**Comment by NateSaysYo** [comment]
Thank you
