### ISSUE TITLE
Problems with hoppers

### ISSUE THREAD

**Issue by Katum3sa** [Wynncraft/Issues#8550]
During a dungeon, you maybe have hoppers for pass a door. But you don't have filters and unfortunatly i've drop my wepons into. And is impossible to get it after is action ...

Can you fix it ? and refund me ?

Thanks for reading my issue (and for the english i'm french ^^')

**Comment by ittnoraA** [comment]
This is not a bug. If you make a mistake and throw wrong items into a hopper, it's not our fault. Unfortunate for you, Wynn enforces a strict "no refunds"-policy, which means you won't be getting your items refunded.

**Comment by Katum3sa** [comment]
oh..... is difficult to concentrate on droping item in battle

**Comment by CaptainJLPv2** [comment]
I would suggest using the wynncraft enhanced mod pack, so you can put a lock on your slots, which makes it so you can'take move or throw out the item in those chosenumbers slots.

**Comment by LordHelmchen98** [comment]
I'm sorry for your loss but as already said you won't get it back.
