### ISSUE TITLE
beyond the grave, window won't break

### ISSUE THREAD

**Issue by St0rmfir3** [Wynncraft/Issues#8553]
It seems that beyond the grave is having a few issues with the window after solving the tombstone puzzle? I finished the puzzle, and after it states that the window shatters, it doesn't fully render in or properly place as it just glitches me into the air if i come near it
![2017-07-08_20 31 28](https://user-images.githubusercontent.com/27205805/27988207-f11a5e54-641c-11e7-91f2-28a96c4de14f.png)
i think everything is actually there, but it just glitches out [as i did get set on fire by an invisible block]
is there any way to fix this??

**Comment by ittnoraA** [comment]
Heyo! To me, it looks like client side ghost blocks are created upon completion of the puzzle. I'd recommend using a 1.8 version of minecraft while the animation plays. 

If that did not solve your problem, try completing the puzzle on a fresh, recently restarted server.

**Comment by St0rmfir3** [comment]
it worked! thanks so much :D
