### ISSUE TITLE
Fallen Factory Issue when Server Restart Happens

### ISSUE THREAD

**Issue by CaptainJLPv2** [Wynncraft/Issues#8559]
Whenever you are logged off by server restart near the RED button to start the machines ( gears and elevators ) and go back into another world you will be stuck above the fallen factory  where command blocks are
![2017-07-10_16 55 37](https://user-images.githubusercontent.com/28000844/28006179-900b4788-6591-11e7-8a65-844eb62a7342.png)
![2017-07-10_16 55 42](https://user-images.githubusercontent.com/28000844/28006224-c10d047a-6591-11e7-9d97-de117375730d.png)
![2017-07-10_16 58 47](https://user-images.githubusercontent.com/28000844/28006247-d42cf4ac-6591-11e7-990a-0b246f56a393.png)

.

**Comment by CaptainJLPv2** [comment]
In the screenshots above I am using the wynncraft enhanced modpack

**Comment by colin350** [comment]
Oh hey those are my command blocks!
Please do `/kill` immediately or you will risk being banned by a staff member. 

I'm not sure what is causing this but will look into it. Thank you.
