### ISSUE TITLE
I can't connect to Katoa.ca

### ISSUE THREAD

**Issue by ZeUnlucky** [Wynncraft/Issues#8562]
While trying to apply for GM, I couldn't connect to katoa.ca.
I tried doing what it recommends, but none of the solutions worked. 

ERR_CONNECTION_REFUSED

**Comment by colin350** [comment]
The website is a third-party tool designed by Dakota. However, based on the issue you are describing and my ability to access the website with no problem, this is client sided. Your best bet is to google solutions. Here are some which I found here:

https://www.quora.com/How-do-I-fix-ERR_CONNECTION_REFUSED-on-Chrome

Worst case, try using a free VPN service. An example would be spotflux. If you continue having issues, contact Dakota on the forums.
