### ISSUE TITLE
Bug in Tower of Ascension experience 

### ISSUE THREAD

**Issue by TREVCKC** [Wynncraft/Issues#8566]
Dear moderator, 
I have pass the Quest Tower of Ascension today, but i cannot get the experience at all, before doing the quest, my dark wage only level up from 49 to 50lv and 30000 exp more. But the system show me that i got 925000 exp from the quest.
May I get the exp back? i have do a screen cap and anyone please help me.......
My ingame name is TREVCKC, thanks for reading my message!

![experience bug](https://user-images.githubusercontent.com/30066220/28051698-940b507e-6638-11e7-9107-fe3122472d08.png)

**Comment by ittnoraA** [comment]
The quest doesn't give a static amount of xp. It adapts to the level you complete it in, and levels you up one time, to prevent people from transfering the shards from their higher level class onto their low leveled classes. The quest should be completed around lvl 70-75 for maximum amount of xp.

**Comment by AscendedKitten** [comment]
As @ittnoraA stated, the low amount of xp is a result of you completing the quest at Level 50 - Optimal would be around 75, the scaling xp mechanism was implemented to prevent others from carrying someone through to allow them to mass-levelup.
