### ISSUE TITLE
HP not accurate

### ISSUE THREAD

**Issue by NicBOMB** [Wynncraft/Issues#8568]
My Archer when using Cancer, Sundown Poncho, Cinderchain, Gaea-Hewn Boots, Prism, Prism, Prowess, Diamond Fusion Necklace should have 9900 hp, but I the health bar indicates 10405. This is every single time I login as well. One of the items might not be working right :( I'll add pictures later ;)

**Comment by RubbrDucky** [comment]
You have hp b/c of lvl ups, did u calculate that?
