### ISSUE TITLE
Can't continue Temple of Legends quest

### ISSUE THREAD

**Issue by Bastallio** [Wynncraft/Issues#8572]
There has been a similar issue to what has happened here, but it doesn't really have the same solution.
((link to the similar solution: https://github.com/Wynncraft/Issues/issues/8529 ))

Basically, I had swapped servers to join in a item bomb spam, and while that was happening I was doing the part of the Temple of Legends to where you need to go to Mage Island and talk to Rayshyroth. While the dialogue was happening, I wasn't paying attention and apparently the world reset, which is what I've assumed to be the cause of the problem. Whenever I got onto a different world, he kept on telling me to follow my quest book, which told me to get him the 12 Sky Vapors, which eventually I gave in and went in did, then I went back up there and he told me the same exact thing, making it impossible for me to continue and finish the quest. I would like to know if it would be possible to reset that specific part of the quest to where I can give it to him, because losing 6 items that you can only get from specific quests is really hard to recover from. Here are some screenshots to show proof of what happened.

![2017-07-12_01 44 25](https://user-images.githubusercontent.com/30105987/28105128-d4de0e1e-66a3-11e7-99d9-ef42e5a5fdab.png)

![2017-07-12_01 44 30](https://user-images.githubusercontent.com/30105987/28105138-dafd0912-66a3-11e7-96d0-8d2ae10aa56a.png)

![2017-07-12_01 44 44](https://user-images.githubusercontent.com/30105987/28105140-dea321d2-66a3-11e7-9f7a-f5ee10fa3400.png)

**Comment by PepinhoJp** [comment]
You also need to bring one Lightdust, you can find more info about that item on Wynn's wiki.

**Comment by Bastallio** [comment]
I'll go try that right now, I'll send another message here if it doesn't work, but otherwise, thanks for the help! <333
