### ISSUE TITLE
Wynn Excavation Site B bug (Solved)

### ISSUE THREAD

**Issue by GrGgamer** [Wynncraft/Issues#8574]
![2017-07-12_20 06 54](https://user-images.githubusercontent.com/30125933/28132710-e6636be4-673d-11e7-9525-e1902f1b5fb6.png)
![2017-07-12_20 07 06](https://user-images.githubusercontent.com/30125933/28132727-f6006214-673d-11e7-8fc1-4355af2408c0.png)
![2017-07-12_20 07 46](https://user-images.githubusercontent.com/30125933/28132730-f7e27f54-673d-11e7-9449-3ae028ed10bc.png)
![2017-07-12_20 07 58](https://user-images.githubusercontent.com/30125933/28132731-f8d910d0-673d-11e7-8f08-51ef24c5949e.png)

**Comment by quesswho** [comment]
You have to jump down even if he tells you not to.

**Comment by ittnoraA** [comment]
Have you done as the quest book says, and brought the shard from the previous site to Lykros?

**Comment by GrGgamer** [comment]
Thank you <3
