### ISSUE TITLE
Guild Problem

### ISSUE THREAD

**Issue by FrostyZenix** [Wynncraft/Issues#8577]
So, I went to the Guild Hub and I went on to make a guild, then without knowing the server restarted so I got sent to the lobby, with that the Guild creating stops, now everytime I try to create a Guild it doesnt work or active the NPC at all! Please help me.

**Comment by PepinhoJp** [comment]
Try doing /guild disband

**Comment by LordHelmchen98** [comment]
I'm pretty sure `/guild disband` doesn't even exist. You can try `/guild leave` though. 
Tell us if you were able to resolve it.

**Comment by FrostyZenix** [comment]
Thank you all I've been able to resolve the problem and I'm now in another guild, thank you all.
