### ISSUE TITLE
The House Of Twian's Quest having the wrong differculty.

### ISSUE THREAD

**Issue by EnderFXO** [Wynncraft/Issues#8578]
In the quest book the lvl 49 quest "The House Of Twian", the set differculty is Easy. But I keep getting swarmed by monsters both outside the mansion and inside the tunnel leading to the code submission. I lost my Legendary Staff to this quest and I'm not happy about that. So the question is that set differculty a bug or was it set like that? Because if it's not a bug then either the differculty needs to be changed or monster spawnrate needs to be nerfed dramatically.

**Comment by RubbrDucky** [comment]
just avoid them and use AoE spells to kill them. It's not that hard to
survive.

Quest difficulty is automatically set by the amount of steps in the quest.
It can't be changed manually.

**Comment by Locky1110** [comment]
its not a bug
they can't change the difficulty
it only says easy because its like only 2 stages
talk to guy
get book and bring to guy
k

**Comment by AscendedKitten** [comment]
As others stated, difficulty is determined by the amount of stages a quest has.
For now there's no way for us to set it manually, but hopefully that will be possible in the future.
