### ISSUE TITLE
bug mission

### ISSUE THREAD

**Issue by mysterioug** [Wynncraft/Issues#8581]
i kill rat and get the wedding ring but npc dont detect my ring

**Comment by RubbrDucky** [comment]
There are two versions: washer and real ring.

go into the cave to kill the miniboss to get the real ring.

**Comment by mysterioug** [comment]
oh ty

**Comment by mysterioug** [comment]
now how to bring drake back?

**Comment by colin350** [comment]
The report page is for reporting bugs not for quest help. If you need help with quests, please ask a question on the forums or on discord.
