### ISSUE TITLE
-395k XP to lvl 98

### ISSUE THREAD

**Issue by AstralEpic** [Wynncraft/Issues#8582]
I'm 103% to level 98, can someone please help me with this issue? Thanks!
![2017-07-13_18 55 21](https://user-images.githubusercontent.com/30165131/28195289-373b8388-67fe-11e7-99d4-868c3a9b5b28.png)

**Comment by thecoolkogut4** [comment]
What is your in-game name?

**Comment by ittnoraA** [comment]
I believe discoveries can cause this bug. Try killing any mob to see if you level up.

**Comment by AstralEpic** [comment]
AstralEpic

Also yes I tried, and it worked  thanks!

**Comment by AscendedKitten** [comment]
Issues was resolved.
