### ISSUE TITLE
Guild Player Needs To Be Kicked Glitch

### ISSUE THREAD

**Issue by SuchAlex** [Wynncraft/Issues#8584]
My now to be old member of the guild, Tranquility (PaT) on Wynncraft is glitched in our guild. And we're trying to kick him I hope you guys can kick him for us. His username currently is "WarTech" his old username when he joined our guild was "CreativityPlus". My username in Wynncraft is SuchAlex and the leader of the guild is "DemoGhost".
Thanks.

**Comment by ittnoraA** [comment]
Currently there is no fix for this bug, since the guild system was created before name changing was possible. The developers of Wynn are currently working on fixing it though, but as for now, your friend will be stuck until the update happens.

**Comment by AckroWynn** [comment]
This has been reported before, and guilds will eventually be fixed; we promise.
