### ISSUE TITLE
Glitched Quest items due to previous character

### ISSUE THREAD

**Issue by Moyx** [Wynncraft/Issues#8585]
So I currently have 2 of the same quest items as my old main Warrior had them in my enderchest, I cannot remove one of these items because it says I need it for a quest, if there's any sort of way an admin or someone on the staff team can take my duplicates away from me, that would be very much appreciated, thank you so much.
-Moyx

**Comment by thecoolkogut4** [comment]
Put it in your daily chest. Once you do this there is a possibility that you won't be able to get it back.

**Comment by Moyx** [comment]
Thank you so much! It worked, appreciated!
