### ISSUE TITLE
Map glitch

### ISSUE THREAD

**Issue by CaptainFight** [Wynncraft/Issues#8586]
I found a glitch in the wynncraft map, and its that the hat for the Player wont show in the map.

![image](https://user-images.githubusercontent.com/15091808/28234701-dbcb9816-6902-11e7-998b-c7b67e38621c.png)

![image](https://user-images.githubusercontent.com/15091808/28234709-ee10163c-6902-11e7-9c2e-66f299093d0e.png)

**Comment by RubbrDucky** [comment]
It only shows the mc skin head, not any layers/helmet/hat thing. Just edit
your skin, it takes like 2 minutes.
