### ISSUE TITLE
Item bomb glitch

### ISSUE THREAD

**Issue by NickFFS** [Wynncraft/Issues#8587]
I had bought the VIP rank and used my first item bomb fine, but when I used my second one, I clicked the "click here to claim them!" thing and it said "you have received: An internal error occurred while attempting to perform this command" I also received nothing for it.
![2017-07-14_20 14 46](https://user-images.githubusercontent.com/28676878/28234820-15ac81f2-68d2-11e7-986b-5104031cebd0.png)

**Comment by RubbrDucky** [comment]
just click again

**Comment by NickFFS** [comment]
i did
didnt work

**Comment by colin350** [comment]
We are aware of this issue, but if you feel that you deserve a refund, please email support@wynncraft.com with reasoning.
