### ISSUE TITLE
My mage got deleted

### ISSUE THREAD

**Issue by MajkySw** [Wynncraft/Issues#8588]
Yesterday i was afk in Troms city with my mage, because i dont had Soul points. But i fell asleep and today i woke up and i found out my mage missing. I have some photos about his existence, but i rly dont know how it happened. Please help me i rly dont want to exp him again.

**Comment by colin350** [comment]
From the statistics page, it says you joined 4 days ago. I'm hesitant to believe that you had a mage in Troms after playing for 4 days (unless you played for 4 days straight). Troms is also a safezone, and dying without soul points would not cause you to lose your class. Perhaps you accidentally deleted it? Perhaps you died, got frustrated, and deleted the class? Or perhaps you did crash and lost your class for some weird reason. 

Either way, Wynncraft enforces a strict no-refund policy, which applies to all players including content team members and staff members. What that means is that there is no way to recover your "lost" class.

**Comment by MajkySw** [comment]
Yes i was in Trom because i have 2 friends lvl 80 and they helped me with dungeon near Troms. And i srsly dont deleted my mage lvl 41, Because im now angry.

**Comment by MajkySw** [comment]
And if you want i told u i have some photos and u didnt ask on them so i rly dont understand you. Because u dont want to see my proofs. I i told u i fell asleep and after i woke up i found out my mage got deleted.
