### ISSUE TITLE
have a dungeon not working,is the lost sanctuary

### ISSUE THREAD

**Issue by KYD51** [Wynncraft/Issues#8591]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

**Comment by PepinhoJp** [comment]
Nobody can help you if you don't give more information and a bit of detail, you can check for duplicates to see if there are any other bugs like this one too.

**Comment by LordHelmchen98** [comment]
As already said there is nothing we can do for you without any information @KYD51
