### ISSUE TITLE
Shouting not working and Guild chat not showing up

### ISSUE THREAD

**Issue by MarandaIsBae** [Wynncraft/Issues#8593]
Shout Glitch
http://imgur.com/a/aBwj9

Guild Chat Bug/Glitch
https://youtu.be/nFbRH2AiUHk

**Comment by thecoolkogut4** [comment]
This is a known bug and happens every so often. This will be fixed within a few hours.

**Comment by LordHelmchen98** [comment]
In addition to the previous comment, you can send a mail to support@wynncraft.com in order to get your shout back.
