### ISSUE TITLE
Tier 2 & 3 crates will be all commons (and other issues with crates)

### ISSUE THREAD

**Issue by BloodyLombax** [Wynncraft/Issues#8594]
This seems to happen much too frequently. Also they'll do 3 or often more full rotations after clicking before stopping. Sometime even skip to the next spot after they stop, or halt strangely while still rotating nearly at full speed, meaning what you were going to land on is not what you'll get. It seems intentional and its disrespectful to the players who put money into this. Does the crate already decide what you will get before you click? Why not just have it open to an item then? Why give false hope?

**Comment by RubbrDucky** [comment]
That's how almost all game rng works: outcome decided as you open the crate.

**Comment by BloodyLombax** [comment]
I just tried so more, it landed on an Epic gear skin, and gave me a common Wybel. There wasn't even a common next to it.

**Comment by Locky1110** [comment]
For the epic it could've given you a wybel because it the skin didn't touch the chest.

Pretty sure the item is predetermined
and the animation is for suspense
they do the rotations after click so it seems as if the item is random

but yeah i don't really see anything wrong with the system

**Comment by AscendedKitten** [comment]
As others said this isn't an actual bug; there might be some visual inconsistencies, but the outcome is pre-determined, and the speed at which the items slow down is random as well.
