### ISSUE TITLE
Inventory and level loss

### ISSUE THREAD

**Issue by Seckmanjr** [Wynncraft/Issues#8597]
I have gotten on today ( July 17, 2017) and all my armour and weapons are missing in my inventory and my levels reset. all I have in my inv is a couple of quest items. my horse also reset back to teir 1

**Comment by CaptainJLPv2** [comment]
You haven't told anyone your minecraft password or email or something like have you? Thats the only way i would say they got "deleted."

**Comment by Seckmanjr** [comment]
No I havent.

**Comment by Seckmanjr** [comment]
and its to all my other classes

**Comment by Locky1110** [comment]
if this keeps happening, i recommend changing your password in case someone actually has your email and password. Wynn wouldn't have deleted all your stuff. Have you ever entered you email and password  in one of those websites that offer free stuff but its really just a scam, and if so, yeah you need to change your password,

**Comment by CaptainJLPv2** [comment]
And i really wouldn't believe that wynn deleted your account but you got a tier 1 horse still.

**Comment by AscendedKitten** [comment]
I am sorry for your loss, but sadly Wynncraft enforces a strict no-refund policy, since that'd be abuseable.
I haven't heard of a smiliar case before, but if you are certain that your account is not being used by someone else, please report back should the issue persist.
