### ISSUE TITLE
"Curse" Missing"

### ISSUE THREAD

**Issue by SuperViper** [Wynncraft/Issues#8601]
I want to know why it say's "CURSE MISSING Please use curse"?
I use the original modpack from twitch 
![image](https://user-images.githubusercontent.com/30214665/28248750-8c8ef224-6a52-11e7-8d6e-0f64dd895dc2.png)
![image](https://user-images.githubusercontent.com/30214665/28248758-af854544-6a52-11e7-8e86-19f296f47537.png)

**Comment by ittnoraA** [comment]
This website is dedicated for issues related to the game. Please post your problems about the modpack on it's original forums thread.

**Comment by colin350** [comment]
Furthermore: the Wynncraft Enhanced mod-pack isn't an official mod-pack. Therefore like @ittnoraA said, you should post issues with the mod-pack on the original forums thread or website. This is for in-game bug reports not related to third-party software. Thank you.
