### ISSUE TITLE
Unable to proceed in Elemental Excercise

### ISSUE THREAD

**Issue by AbsolLegacy** [Wynncraft/Issues#8602]
I am stuck at testing the fire weapon on the captured monster.  I play as a level 12 archer and everytime I kill the monster the server doesn't update my quest progress.  I've tried restarting the server or restarting minecraft.

User: Absol_Legacy

**Comment by Hegezcc** [comment]
If I recall right, you have to bring the monster drop back to the NPC.

**Comment by colin350** [comment]
Read the above comment.
