### ISSUE TITLE
1k Storms

### ISSUE THREAD

**Issue by ElPfeffo** [Wynncraft/Issues#8604]
I am on the last stage of the 1K storms easter egg, and I am certain I have completed the prior stages. When I drop the 3 cold blood onto the spikes, the wall opens, but the portal will not let me through. I tried switching servers and relogging. Is there a fix?

Thank you,
-ElPfeffo

**Comment by AscendedKitten** [comment]
(@Imaxe?)

**Comment by Imaxe** [comment]
That means that you missed a step or 2. Go through it all again and it should work :)
