### ISSUE TITLE
Dying in the middle a town while logged off

### ISSUE THREAD

**Issue by Mitchellp33** [Wynncraft/Issues#8605]
For some reason when I log off in a town and later log back in i'll be dead and most of time I log off i'm at a low amount of soul points so I end up losing half my gear and this happened to me several times in the past few days so than I have to find a place were monsters can't reach, so if i'm in a rush to get off and just log off in the middle of town i'm dead. Plz fix

**Comment by thecoolkogut4** [comment]
This is probably occuring on your end. When you log off do you quit Mc? Or log out of your account on your computer. If you just shut it down, or put it to sleep theres a possibility Mc still can be running and that means you could be taking damage. (Sorry typing this on my phone is something doesn't make scence let me know and I'll try my best to reword it)

**Comment by Mitchellp33** [comment]
yea but I complete exit me game and if I was still logged in the guards technically should protect me since I was in the middle of a town.

**Comment by AckroWynn** [comment]
Would you like to take a picture of your position, and inventory before you log off next time, and then take a picture next time it happens that you log in and being dead.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
