### ISSUE TITLE
attacking glitched out

### ISSUE THREAD

**Issue by armorpower** [Wynncraft/Issues#8606]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

as the title says my attack glitched out making me not even able to attack as if i was in adventure mode
further more this happened when i was in the house of twain if thats a thing there fix it its really really annoying when out of nowhere you cant hit anything that also includes spell damage things could still hit me but i could not hurt them also the cap needed for the quest makes it do able yes but it also makes it so i cant use my weapon do to i need strength this has happened in to many quests where i am forced to wear the armor which just makes me weaker and makes it so i lose my weapon and yes i was able to use my weapon when it stopped "working" if someone can help me as to why this might have happened that would be great thankfully going to a different world helped but i dont know why it happened in the first place

**Comment by creepeyboy** [comment]
are u using a weapon thats ussable by u?

**Comment by armorpower** [comment]
i said that in the issue "and yes i was able to use my weapon when it stopped "working" "

**Comment by thecoolkogut4** [comment]
If this is the bug that I think it is, you should be able to do damage again. It was just a temporary one. If it is snot fixed, can you do damage on another class?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
