### ISSUE TITLE
I have probelm with the resourcepack 

### ISSUE THREAD

**Issue by TimafeyArti** [Wynncraft/Issues#8608]
i enabled the resoucepack in the server list, but when i joinning one of the servers and want to play it wont let me join and writing,
"internal exception: java.lang.illegalargumentexception: parameter 'directory' is not a directory"
can someone help pls thx.

**Comment by thecoolkogut4** [comment]
What ip are you using to connect?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
