### ISSUE TITLE
I am glitched on a Quest (Jungle Fever)

### ISSUE THREAD

**Issue by JustANerdd** [Wynncraft/Issues#8612]
I have 62 of the 64 Almuj's Liquified Emerald...
please help it only gave my the 62 of 64...
My In Game Name is _Just_A_Nerd_ Thanks so much and I hope a mod or someone could solve the problem!

**Comment by Locky1110** [comment]
do /fixquests, this should fix the problem

**Comment by Villageacules** [comment]
@JustANerdd is your problem solved?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
