### ISSUE TITLE
Grave digger quest bug

### ISSUE THREAD

**Issue by Teardropp** [Wynncraft/Issues#8614]
The problem with this quest is that Saylero's brother doesn't drop his will. After he is killed he instantly respawns and sometimes drops items like a normal zombie (parts of armor, potions), but he doesnt drop any will at all. I tried connecting into another server, restarting my game, also I tried to kill him with new character and I asked my friend to kill him and nothing (I haven't dropped the will, neither my friend).  It makes the quest impossible and now I have to skip it.

**Comment by Teardropp** [comment]
Nvm this is not a bug. I just had to kill him a few times until he was undressed (if u know what i mean).

**Comment by AscendedKitten** [comment]
Closed since the issue was resolved.
