### ISSUE TITLE
WynnD

### ISSUE THREAD

**Issue by Maeyz** [Wynncraft/Issues#8619]
The Yellow Puzzle in WynnD is broken for me. Whatever I do the lights will not light up after I do the second light combo. Please help me.

**Comment by thecoolkogut4** [comment]
What happens when you switch world's?

**Comment by Maeyz** [comment]
It has done the same thing to me in each world I've changed.

**Comment by Maeyz** [comment]
It worked. Thank you for trying to help.

**Comment by AscendedKitten** [comment]
Closing since the issue was resolved.
