### ISSUE TITLE
No Summer Discount While Upgrading Ranks?

### ISSUE THREAD

**Issue by quinnrockstar** [Wynncraft/Issues#8620]
I currently have the VIP + rank and since there is summer sale, i thought "why not upgrade to the hero rank?" After looking through the store and the deals i realised that you dont get a discount on your purchase when you are upgrading to a higher rank, but if you are buying the rank for your first time you do get the discount. Since i already have vip+ which costed 40$ shouldn't it only cost 16$ to upgrade to hero because with the sale its on for 55.99$ Instead of 40$? Just wondering if there is a reason for no discount when upgrading ranks.. Thanks!

**Comment by AscendedKitten** [comment]
As far as I know the discount should be applied; might be worth sending a mail to support@wynncraft.com, since they are responsible for such issues.

**Comment by quinnrockstar** [comment]
Okay, thank you
