### ISSUE TITLE
Shattered Minds bug

### ISSUE THREAD

**Issue by KingAiden** [Wynncraft/Issues#8621]
I found the civilization in the forest and talked to Likeru? but it didn't say that my quest book had updated after ta talking to the npc i went up to the house with the ladder and did what it asked me to do but it said "It seems rude to just barge into someone's house like that." and now i can't finish the quest properly

**Comment by thecoolkogut4** [comment]
What does your quest book say?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
