### ISSUE TITLE
Crash on connecting to any lobby bc my character is in the nether

### ISSUE THREAD

**Issue by PetrifyingPear** [Wynncraft/Issues#8622]
I tried doing the Temple of Legends quest, and didn't know you could get the light dust from the pillars of corruption themselves instead of having to go to the nether, but the nether seems to be bugged too, since it disconnects me from the wynncraft server as soon as I log in (it doesn't matter which lobby I log in to). I also can't seem to change my character because it automatically logs me into the character I last played, which would be archer. If anyone knows how to fix this, please tell me how.

**Comment by thecoolkogut4** [comment]
Once in the nether, walk through the nether portal and you should be good to play on a normal world.

**Comment by PetrifyingPear** [comment]
No as in as soon as I connect to any of the servers it disconnects me immediately, I don't get to do /kill or /class to change my class, or move at all

**Comment by PetrifyingPear** [comment]
Nevermind, my friend managed to log me out as soon as I connected and did /kill, I couldn't seeing as I'd have a lagspike
