### ISSUE TITLE
Bob's Tomb Bug

### ISSUE THREAD

**Issue by xXInsidiousXx** [Wynncraft/Issues#8625]
Don't really know if this has been well known but, using the horse I can glitch through the stone wall at the entrance to get into the ice area leading up to the tomb. Skipping the 2 buttons and pressure plate part and getting into the room full of snow zombies.

**Comment by PepinhoJp** [comment]
Its a known bug, just don't do that, you might be banned for glitching if you abuse this glitch.

**Comment by xXInsidiousXx** [comment]
Thanks for the info, I was just curious if it was known or not.
