### ISSUE TITLE
stuck in the underworld crypt dungeon

### ISSUE THREAD

**Issue by DevastationV** [Wynncraft/Issues#8626]
ign:DevastationV
so i was doing the underworld crypt dungeon as my warrior class the dungeon went fine but when i went through the entrance for the boss i got into a black room stuck not being able to do anything.as of this post i am still stuck in the dungeon and no way of geting out

![wynn](https://user-images.githubusercontent.com/30307749/28400474-54e7adde-6ce1-11e7-9241-517ab4596abd.png)

**Comment by AscendedKitten** [comment]
I am sorry for the inconvenience; you can use a teleport scroll or /kill to return to the closest town.
Which version are you using? I'd recommend trying 1.8.x, as there might be some redstone issues otherwise.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can create a thread in the [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
