### ISSUE TITLE
Out of Bounds in Lobby

### ISSUE THREAD

**Issue by ukilop** [Wynncraft/Issues#8627]
So using lobby flight its possible to get semi-out of bounds. normally there's tele-boundaries to prevent it but those boundaries don't fully enclose the lobby and there's a way to sneak out. Although there is a 2nd barrier block boundary that prevents total out of bounds. In the video I am showing in what ways you can get "outside" the lobby.

Footage was taken *right* before posting and thus is current as of the post time of this issue.
https://youtu.be/eOZ4b9QAoMY

**Comment by colin350** [comment]
The set of barriers are there to not explore the map in general, which is why they are there. Of course the mechanic isn't meant to work the way that you can get past the permissions, but that's why the barriers are there as a failsafe.
