### ISSUE TITLE
Missing icons on map

### ISSUE THREAD

**Issue by Tom250** [Wynncraft/Issues#8633]
http://prntscr.com/fyffrf
Nemract - Emerald Merchnats are not shown up.
I tried to

- delete Cookies
- delete Cache
- other Browsers
- reinstall Browsers

**Comment by colin350** [comment]
Yes, that is not an issue directly related to you. To avoid the headache in the future, maybe best to ask other people if they are experiencing this issue. 

To my knowledge they need to be manually added. Perhaps it was missed. 
Thank you for your report.

**Comment by Tom250** [comment]
Okay, thank you!

**Comment by Villageacules** [comment]
Yes, this is a fault of the people who put those pins all over the map. Those pins aren't automatic.
However, whenever we update the website map for the a new update's map, I'm certain that we will also update the icons as well.

**Comment by iBlintz** [comment]
Please some one help me when i got to my map my player icon wont show up please some one help me ;(

**Comment by LordHelmchen98** [comment]
@iBlintz if you have any issues it would be helpful if you didnt post on thread with a different topic even if its only a little bit diferent. however this issue should be temporary and as you posted quite a while ago I assume its fixed now. if you face any other issues you can now post them in the [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
