### ISSUE TITLE
Items lost due to skillpoints

### ISSUE THREAD

**Issue by Maeyz** [Wynncraft/Issues#8635]
I reset my skillpoints with a full inventory and my boots dissapeared. Why does this happen?

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug. the boots most likely were on the ground beside you or somewhere around you.

**Comment by Maeyz** [comment]
Thanks for the help.
