### ISSUE TITLE
Vade's asking me to give him the tablet.... after I went in the tomb and solved the puzzle??

### ISSUE THREAD

**Issue by CleverCreations** [Wynncraft/Issues#8637]
I decided to to the quest called WynnExcavation Site A. I received the tablet, translated it, then proceeded into the tomb and did the puzzles. However, when I came out to talk to Vade (because the quest book said it was required), Vade told me to, yet again, go translate the tablet. However, this was done long before going into the tomb. To see if this would fix anything, I spoke to the person in the tent, and ran back to Vade, but to no avail. I also tried using the /fixquests command, and checked my bank. Nothing seems to be working, and it seems that I'm not the only one with this issue, however, it seems that the issue hasn't been solved. Some help would be greatly appreciated.

**Comment by Locky1110** [comment]
Did you kill the boss to get the shard?
If you didn't, the cause is probably the ct made him say that if the requirement wasn't made.

**Comment by logestheknifer** [comment]
The same thing happened to me. It was impossible for me to kill the boss because I accidentlly war screamed him into the pool below the stairs which is covered in barrier blocks. So I just went out the door and talked to Vade and the same message came up.

**Comment by LordHelmchen98** [comment]
Sometimes NPCs tell you the same over and over again although you already did what they are requesting. That happens when you need to bring them something that you don't have later in the quest.
The boss at the end drops a yellow crystal shard. Get that and you should be fine.
