### ISSUE TITLE
Amadel doesnt drop item?

### ISSUE THREAD

**Issue by TechnoBane** [Wynncraft/Issues#8638]
I killed the fully formed Amadel and he didnt drop anything, all that happened was the boss respawned with full health. Is the boss supposed to respawn or is it just a glitch?

**Comment by TechnoBane** [comment]
Ok I've tried to kill him again and he still didn't drop anything, this makes it impossible for me to complete the quest, Do i have to kill him like twice before he drops anything?

**Comment by thecoolkogut4** [comment]
I believe it has multiple forms. Which means you need to kill it multiple times. (You kill it then it pretty much insta respawns = 2nd form then kill it again, 3rd form...). If you don't get what I'm saying let me know and I'll try to rephrase it.

**Comment by TechnoBane** [comment]
oh ok, thanks for the help, but this just makes the boss so annoying
