### ISSUE TITLE
My Stats Page Must be Glitched...

### ISSUE THREAD

**Issue by Kybeah** [Wynncraft/Issues#8640]
Hi,

Ive been playing on Wynncraft for over 3 years now, I know this for sure.  When you search up my IGN, Kybeah, it shows this, which is correct.  But my stats page claims i only have 18 clocked ours.  I think this is oddly of, considering i've been playing on this server much more often lately, with usually 2 hour sessions every couple times a week.  It seems to be strikingly off.  Is there any way to refresh the stat or any way for  me or anyone else to get a correct playtime stat for me?
Here is my stat page
[https://wynncraft.com/stats/player/Kybeah](url)

I know it isn't just my stat page either.  Someone else I was talking to joined 3 months ago, but their stat page said 5 months ago.  
Thanks for the help!

**Comment by thecoolkogut4** [comment]
The time gets counted weirdly but there's nothing that you can do about it. Your friend might of joined before but forgot, or someone could of been on his account and joined, or your friend might just not recall when he first joined. There's currently nothing you/staff can do to fix this.

**Comment by LordHelmchen98** [comment]
The first join date should be correct, but you have to multiply the play time with about 5 to get a realistic time.
