### ISSUE TITLE
I feel uncomfortable in the trees.

### ISSUE THREAD

**Issue by GurenAM** [Wynncraft/Issues#8643]
I'm JPN, I am not good at English. I'm sorry.

I can not get out of the coordinates below.
x-124 y49 z-501
（It is North direction from Lusuco.）

I used Mage's magic, Teleport.
I got into the tree.
I can not get out of here.
I tried both Teleporting and scrolling.
Still, I could not get out.

Please get me out of here.
Thanking you in advance!!

**Comment by LA1S0N** [comment]
did you try /kill

**Comment by GurenAM** [comment]
Thank you!!
