### ISSUE TITLE
Ice Barrows dungeon

### ISSUE THREAD

**Issue by LA1S0N** [Wynncraft/Issues#8646]
Me and my friend were doing the Ice barrows dungeon and at the running part we got stuck because the door/wall wouldn't open. 

Anyone know what to do?

**Comment by AscendedKitten** [comment]
That's probably related to redstone issues; try switching version or server.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can create a thread in the [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
