### ISSUE TITLE
Can't Connect to a World

### ISSUE THREAD

**Issue by SytheofDeath** [Wynncraft/Issues#8647]
I can't seem to connect to any world. I can get into the server fine, I can walk around the lobby and do the lobby parkour just fine. But as soon as I try to connect to a world the game freezes and then disconnects me. I don't know what's wrong. Any help would be appreciated.

**Comment by thecoolkogut4** [comment]
Try joining the server in Mc version 1.8.9 with no mods. Let me know how that goes.

**Comment by SytheofDeath** [comment]
I fixed it. All i had to do was set "Enable Server Resource Pack" to "Prompt", I don't know why that worked but i did.
