### ISSUE TITLE
An Iron Heart Part II/2 and Factory Helm

### ISSUE THREAD

**Issue by xINTELLx** [Wynncraft/Issues#8649]
Did part 1 a long time ago when Gavel came out and then quit. I checked my bank and it's not there I believe the quest Bugged
Edit: Yes I've already done the command to fix quest items.

**Comment by thecoolkogut4** [comment]
You checked your bank, but have you checked some of your other classes? You said you tried fix quests, have you tried that on every class?

**Comment by Chewsterchew** [comment]
Surprisingly I also have this issue. It MIGHT be that it got unidentified when the identify overhaul update occured. I still don't wanna waste my precious emeralds on identifying _**Every. Single. Helmet.**_

**Comment by LordHelmchen98** [comment]
@Chewsterchew all the items got unidentified when gavel came out, but before gavel came out those quests didn't exist so you were not able to get a factory helmet before gavel that could be unidentified now
@xINTELLx were you able to resolve it by doing what thecoolkogut4 said?

**Comment by Chewsterchew** [comment]
Probably, do I have to identify every single helmet I own?

**Comment by LordHelmchen98** [comment]
@Chewsterchew Nah only if you need to wear one of the helmets.

@xINTELLx we can't help you without information. If you are still experiencing this issue, you can open a new bug report in the new section on the forums.
