### ISSUE TITLE
Horse bug in 1.8

### ISSUE THREAD

**Issue by FanciestNir** [Wynncraft/Issues#8650]
When I'm using 1.8x version the horses are running like they are running on ice and but on 1.9+ it's working perfectly anyway to fix it on 1.8? 
I don't use it on 1.9 because the right click is buggy help?

**Comment by thecoolkogut4** [comment]
There's currently no alternate solution to this, just what you said. Sorry.

**Comment by FanciestNir** [comment]
ok thanks for the answer

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can create a thread in the [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
