### ISSUE TITLE
can't play

### ISSUE THREAD

**Issue by adhamammar** [Wynncraft/Issues#8652]
I always spawn in the ground I can't move or play 
my minecraft name is  Ayman_afis

**Comment by Villageacules** [comment]
Can you tell us a bit more about your problem?
(Your coords, a screenshot would be helpful, etc.)

**Comment by adhamammar** [comment]
[Inline image 1]

On Mon, Jul 31, 2017 at 9:22 PM, Villageacules <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you tell us a bit more about your problem?
(Your coords, a screenshot would be helpful, etc.)

**Comment by Villageacules** [comment]
@adhamammar This image doesn't work...

**Comment by iBlintz** [comment]
i can't continue house of twain i through a emerald in the soul sand and then i died. but now i can't do it again someone help me

**Comment by LordHelmchen98** [comment]
@adhamammar if you spawn somewhere in the ground you should be able to get unstuck by doing `/kill`.

@iBlintz I have no idea why you commented here as this is not related at all, but usually this is a one time issue which means while it might be broken on one server it should work on others.
