### ISSUE TITLE
Soul Point Bug

### ISSUE THREAD

**Issue by DarkWolf336** [Wynncraft/Issues#8653]
I have had times when I was training zombies around Detlas and I would randomly die to the air, im not sure what happens but I hope you can find out :) Thanks!

**Comment by thecoolkogut4** [comment]
This is possibly due to your connection to the server, or just your connection in general. Do you lag on other servers?

**Comment by Villageacules** [comment]
@DarkWolf336 This isn't enough information for us to determine your problem. Can you elaborate?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
