### ISSUE TITLE
Floating Snow Golem

### ISSUE THREAD

**Issue by CyberNitra** [Wynncraft/Issues#8656]
This Bug isnt making any issues, but its still weird.
I was going to house of twain with my mage, as suddenly i saw something high up in the air.
I zoomed in and saw that it was a snow golem.
![2017-07-24_11 08 37](https://user-images.githubusercontent.com/30406010/28517886-4d6f2dd8-7066-11e7-8fbc-5d11f3d6679e.png)
![2017-07-24_11 08 40](https://user-images.githubusercontent.com/30406010/28517887-4d7569dc-7066-11e7-8fd2-f0160f422928.png)
![2017-07-24_11 08 54](https://user-images.githubusercontent.com/30406010/28517888-4d7c6070-7066-11e7-8099-307280d54aa0.png)

**Comment by Villageacules** [comment]
This is a rather comedic effect of the way Wynncraft's mob spawning system works... that is a very rare spawn, I wouldn't be too concerned. However, I recently lowered the chance of these mobs spawning above the sky barriers.
