### ISSUE TITLE
Ice Barrow dungeon boss fight

### ISSUE THREAD

**Issue by CyberNitra** [Wynncraft/Issues#8657]
Me and some others were doing the dungeon and we had been in the black teleportation chamber to get to the boss.  But nothing happened. So we just made some screenshots and typed in /kill. after that we tried it again and we were stuck again.
the next day i tried it again and it working.
Here is a pixture of me and 2 others hanging out in that room.
![2017-07-17_13 21 50](https://user-images.githubusercontent.com/30406010/28518020-c6967194-7066-11e7-8235-d8ef9430a1ad.png)

**Comment by thecoolkogut4** [comment]
If it doesn't work just /kill and try again on a new server.(like you did)

**Comment by LordHelmchen98** [comment]
As it's working now it might have been a one time issue on that specific server.
