### ISSUE TITLE
stuck in hole behind detlas suburbs

### ISSUE THREAD

**Issue by voxymoron** [Wynncraft/Issues#8659]
my username is voxymoron, and like the title says, im stuck.
at detlas suburbs i was talking to drale before turning around and falling in a hole between the stairs and fence.
i cant move out, the walls are too high. i dont have any teleportation magic. 
i tried to use a teleport scroll but there were "too many aggressive mobs nearby".
only two mobs have managed to fall in the hole with me, but they didnt do much to kill me.
i asked for help, no one would duel me.
please help!

**Comment by voxymoron** [comment]
edit: i didnt know about the kill command, but i think this should still be fixed so no other noobs are entrapped?

**Comment by voxymoron** [comment]
![image](https://user-images.githubusercontent.com/30418642/28542045-33dd14d6-7078-11e7-9fc2-25468efd8d80.png)

**Comment by PepinhoJp** [comment]
Can you send coords, please? Thanks!

**Comment by voxymoron** [comment]
307 68 -1626

**Comment by colin350** [comment]
Fixed

**Comment by voxymoron** [comment]
@colin350 thank you!
