### ISSUE TITLE
stuck in decrepit sewers

### ISSUE THREAD

**Issue by galenr150** [Wynncraft/Issues#8660]
I'm past the first bit on the decrepit sewers where you drop 18 tokens into the hopper and walk through the door and there is some invisible blocks in front of me and i cant leave. currently on server 9 as I'm writing this. cant teleport through the invisible blocks, and reconnecting to a different server doesn't help. no clue what's wrong.

**Comment by techtrails** [comment]
From the FAQ: 

> »

 Scenario: I'm stuck in a hole or box and can't get out. Can an admin teleport me out? Thx. IGN: wynner123

Please do /kill with 5 or more soul points.

**Comment by PepinhoJp** [comment]
Switch to 1.8 and you'll be able to continue

@techtrails being stuck is a different from not being able to continue because a barrier isn't allowing.
