### ISSUE TITLE
Changed skin 

### ISSUE THREAD

**Issue by BMMS4kids** [Wynncraft/Issues#8661]
When ever i log on to a world it changes my skin to the default alex skin, i tried going on the 1.12 version but still did not work help! 

thank you,
BMMS4kids

**Comment by PepinhoJp** [comment]
removs your armour and put it again.

**Comment by BMMS4kids** [comment]
I don't have armour 0_0

**Comment by PepinhoJp** [comment]
Get armour and put to reload

**Comment by colin350** [comment]
Have you tried playing on 1.8.9 or 1.9.2?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
