### ISSUE TITLE
Issue with Quest: "The Lost"

### ISSUE THREAD

**Issue by keviny3** [Wynncraft/Issues#8662]
Whilst completing the Canyon of the Lost Quest (Level 86) "The Lost", it became apparent that despite having met all five members of Dejol's crew, and giving away all of the letters, the quest book still claims that there is still one member left to be found.

/fixquests does not do anything - no letters are in the bank or in any other class inventory, and all NPC dialogue with Dejol and his crew imply that there is still one more member to find.

https://www.youtube.com/watch?v=rU2_hFyOtdU

As seen in the comments section of this video at the very top, this problem is not localised to myself only.

**Comment by colin350** [comment]
Please refer to #6032.
