### ISSUE TITLE
Bug Quest A Grave mistake

### ISSUE THREAD

**Issue by Amzy17** [Wynncraft/Issues#8663]
I tried to do the quest, and in the cathedral I was confused by the cutscene and couldn't go in. I have tried everything to make the cutscene replay, from logging on and off, changing server, to try and /kill, /dismiss and /fixquests, but none of it works. The cutscene just keeps bugging and I did all the other parts of the quests, but this last cutscene just doesn't want to replay so I can enter the space behind the statue.

**Comment by PepinhoJp** [comment]
Switch servers, the command block system was probably bugged in your server.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
