### ISSUE TITLE
My username is appearing in the guild 2 times even though I'm not in it

### ISSUE THREAD

**Issue by P250** [Wynncraft/Issues#8665]
I left my guild but apparently I'm still in it?!

**Comment by Locky1110** [comment]
Did you change your name while you were in the guild?
If you did, there's a glitch that makes it so you can't leave.

**Comment by thecoolkogut4** [comment]
There are various bugs that can get you stuck in a guild, unfortunately one of those happend to you. There is currently nothing you can do to fix this. All you need to do is wait for an update.

**Comment by P250** [comment]
Fuck me so hard. Can't I just change my name back to my old one?

**Comment by thecoolkogut4** [comment]
Some people say that fixes it, but everyone who I've seen do it, it does not work.

**Comment by P250** [comment]
How long has this been an issue for?

**Comment by AscendedKitten** [comment]
The issue has been around for more than a few months now, but with the code refactor guilds all together should be fixed and updated. I am sorry for the inconvenience.
