### ISSUE TITLE
Reshad glitch

### ISSUE THREAD

**Issue by SytheofDeath** [Wynncraft/Issues#8666]
I know this issue has been brought up before, but I still can't find any fix. I cannot talk to Reshad in the "Meaningful Holiday" quest. I just wanted to bring this up again because I haven't found a fix yet. Some help would be appreciated. :)

**Comment by thecoolkogut4** [comment]
Try clicking him from various angles.

**Comment by SytheofDeath** [comment]
I got it, idk how but i got it.
