### ISSUE TITLE
I'm blocked in Decrepit Sewers Dungeon

### ISSUE THREAD

**Issue by PhoGirlZz** [Wynncraft/Issues#8669]
A unseen wall is in the dungeons block me, i don't go back, and i can't continue the dungeon.
![2017-07-26_13 34 55](https://user-images.githubusercontent.com/30467119/28619137-4a0d0e4c-7207-11e7-8d16-a6cc45314ecb.png)
The dungeon says the message, but i can't continue.
I do this 2 times to anything problems.
Please help me.
Thanks for view post

**Comment by PhoGirlZz** [comment]
A gamer conseil go to /kill me for escaping this bug

**Comment by ittnoraA** [comment]
Heyo! To continue the dungeon, you need to swap onto a 1.8 version of minecraft, since the server is creating client side ghost blocks for you.
