### ISSUE TITLE
Issue with Creeper Infiltration quest

### ISSUE THREAD

**Issue by DerpyJimmy** [Wynncraft/Issues#8670]
I went through the caves, saw the creeper scene, and then it teleported me to a tree with an item on the ground that says "Creeper Skin", that I'm apparently supposed to pick up, but cant. I tried going through the cave 2 times in 1 world, and another in a different. Can't finish the quest  without the creeper skin it seems.

**Comment by thecoolkogut4** [comment]
It is a mob, you need to hit/kill it in order to pick it up.
