### ISSUE TITLE
The Envoy Part 1 - stuck in a block

### ISSUE THREAD

**Issue by DodgeyAsh** [Wynncraft/Issues#8672]
I was completing the quest The Envoy Part 1 and I was leaving the vent then it teleported me into a block. I'm currently stuck in it. [https://gyazo.com/f3e789f05aceb90cfdb9d3431d95c732](url)

**Comment by PepinhoJp** [comment]
/kill with +6 soul points or use a tp scroll, you'll have to enter the diner again and restart the whole dinner stage
