### ISSUE TITLE
stuck on somewhere

### ISSUE THREAD

**Issue by MotoSolar** [Wynncraft/Issues#8673]
At very first of the 'Desperate Metal'

the server announce restarting, so I just go back to hub and login different server.
and I pick up my assassin class again this thing happen.

[https://cdn.discordapp.com/attachments/272421978793705472/340015678000201728/unknown.png](url)

come quick and save my time. I need to leveling up

**Comment by ittnoraA** [comment]
Swap the world you're on. If you're still stuck after that, you can do `/kill` as long as you have 5 or more soul points.
