### ISSUE TITLE
Attack Effect Bug

### ISSUE THREAD

**Issue by JimblesJumble** [Wynncraft/Issues#8675]
Hello Wynncraft team!

So the other day I was going testing out some of the attack effects... I tried toggling one of them off but it just kinda stuck. I've tried re-logging a few times and toggling it once again but it just won't go.

Another small problem I've been having is certain powders not stacking in my bank system. One more thing, certain emeralds also don't transfer sometimes and result in me having to drop them and pick them up again.

My IGN is: JimblesJumble

Thank you so much for your patience! I hope it isn't too much of a hassle, and I appreciate your effort! Also it would be super great if you could actually e-mail me at: noahkf99@gmail.com

**Comment by colin350** [comment]
The two issues you listed are already known bugs and will ideally be resolved after refactor. Date on when refactor will be complete is unknown. There is nothing we can do individually for you.

For more information on:
- Attack effect disabling issue: #6623
- Powders not stacking: #6646 

In the future, please use the search bar to find duplicate issues.

**Comment by JimblesJumble** [comment]
Thank you so much, means a lot!

Have a good day!

Sincerely, Jimbles.
