### ISSUE TITLE
elemental exercise

### ISSUE THREAD

**Issue by mattanti** [Wynncraft/Issues#8677]
I have encountered a bug that makes it impossible for me to enter the cave with the root infront of it. so i would like some help from staff since the /fixquests doesn't help at all.

**Comment by ittnoraA** [comment]
Can you describe your problem with more detail? What does your quest book say?

**Comment by mattanti** [comment]
I tried to do the quest today and it worked, but since i tried the /fixquests command i still have 4 left over bows...

**Comment by colin350** [comment]
View comments here: #8679
