### ISSUE TITLE
Elemental Exercise - Fiery Weapons Bug

### ISSUE THREAD

**Issue by TheEmoPotato** [Wynncraft/Issues#8679]
For the quest "Elemental Exercise," I did /fixquests after I purchased a fiery weapon by accident, causing it to duplicate. Since I have 2, I have one remaining after giving it to the npc, and I can't throw it away because it's a quest item... And now I have a dagger forever stuck in my inventory D:

**Comment by ittnoraA** [comment]
Heyo! There's a neat trick for getting rid of unnecessary quest items. 

1. Put the dagger into your bank.

2. Fill your inventory with items.

3. Grab the dagger from your bank.

4 Exit bank.

**Comment by colin350** [comment]
Another solution is to place your item in your daily reward chest.
