### ISSUE TITLE
Attacks deal no damage

### ISSUE THREAD

**Issue by CyberBen1998** [Wynncraft/Issues#8681]
My attacks aren't doing any damage. I can still shoot arrows and use the special combo attacks, but they do nothing. I have restarted several times, and tried using a different character who was a mage. So right now I'm completely defenseless. Also, my Archer is level 35, is he supposed to have 70 skill points? Because I have 38. And I did look for a duplicate issue and found one, but it wasn't clear on how to fix it or if it just went away on its own.  Thanks for your help

**Comment by CyberBen1998** [comment]
Oops, 68. I have 68 skill points

**Comment by ittnoraA** [comment]
For the not dealing damage problem, it was already answered on your thread. Just log into a **different** world, and it should be fixed. 

And as for your skill point bug, does your armor/accessories have negative skill point stats? Are you sure you haven't just spent them?

**Comment by CyberBen1998** [comment]
Okay, so I can do damage now.. But no, I double checked and I have 68 skill points, and none of my items decrease them

**Comment by ittnoraA** [comment]
68 is the correct amount you're supposed to have. You receive 2 skill points every time you level up. When you're at level 35, you've leveled up only 34 times. Multiply 2 with 34, and you'll receive 68.

**Comment by CyberBen1998** [comment]
I thought that might be the case. I had just noticed that my skills had been moved around, and I wasn't sure if I lost some or they just mixed up randomly. But I reset them and all is well.  Thanks again for your help!
