### ISSUE TITLE
Disconnected/Timed Out

### ISSUE THREAD

**Issue by SytheofDeath** [Wynncraft/Issues#8683]
Ther have been other issues about this problem, but all of the ones I find are from a year ago. So I'm going to repost this now in hopes of getting this problem fixed. I was playing Wynncraft when I was hit with a MASSIVE amount of lag where I was the only thing that moved and I could only "Left click". Then the server would unfreeze for a split second, and then I would immediately get kicked. Whenever I log in again I can play for a couple of minutes and then I'm hit with the same lag and then I get kicked again. I love Wynncraft and I would like I continue to play it, but I can't. If anyone can help that would be great.

**Comment by opticsniper** [comment]
yea, i was lagging (server side) so when i went to the slim that drops charcoal i switched my legendary into my inventory with the charcoal, i then threw the charcoal. well when i took a second look at my inventory i had the charcoal but not my spear. I dont remember what it was but it did 0-150 damage and for me being a level 27ish it was really good, it also had a 45% expode inchant on it, and something else but i just want my spear back. :(

**Comment by PepinhoJp** [comment]
1st post - Sometimes servers lag, try finding a server that almost restarted and if you don't want tk trade don't gk to WC1/2/3.

2nd post - Wynncraft has a srict no refund policy, meaning that they can't give you items that you lost back.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
