### ISSUE TITLE
Seaskipper Nemract -> Llegivar Not Working.

### ISSUE THREAD

**Issue by Mac898** [Wynncraft/Issues#8684]
Taking a boat ride from Nemract to Llevigar, about 3 seconds in, the clock stops and the NPC will not talk. Thanks for any fixes

**Comment by Mac898** [comment]
Temporary Fix: Change server 5-10 times.

**Comment by PepinhoJp** [comment]
Sometimes the seaskipper system bugs, the only way of fixing it, just switch servers.
