### ISSUE TITLE
Pigman Ravine location where you can get stuck completly as Mage

### ISSUE THREAD

**Issue by TheMidnightG** [Wynncraft/Issues#8689]
Coordinates: x-821 y:124 z:-1173
I am stuck at this location in the pigman ravine and am unable to get out because I somehow managed to teleport into a 1 by 1 by 2 space surrounded completely by barrier blocks and am unable to use a teleport scroll to get out because they do not work if clicked on a block. my in game name is TheMidnightG so if an admin could either fix this or teleport me out of there that would be great.

**Comment by TheMidnightG** [comment]
I found the kill command thanks to another issue (posted by someone else for another location but already fixed) but still think this should be fixed

**Comment by Villageacules** [comment]
Thank you for pointing this out, it will be fixed in the next push.
