### ISSUE TITLE
Fought temple of legends boss and didn't get a drop

### ISSUE THREAD

**Issue by TheDragonsKnight** [Wynncraft/Issues#8692]
I killed the boss for the temple of legends and killed the boss and got no drop.

**Comment by thecoolkogut4** [comment]
If other people are there, make sure you do 10% of the damage to get a drop. Try killing it again on another world.

**Comment by LordHelmchen98** [comment]
I thought it was 15%.
Anyway as already said you need to deal enough damage if you are fighting it with friends, if not try different servers.
