### ISSUE TITLE
I can not identify my Bob's Mythic Dagger 

### ISSUE THREAD

**Issue by BeastBrodie0** [Wynncraft/Issues#8693]
I Tried to with all of my classes but it tells "Sorry I cant indetify that weapon. That weapon has already been identified. I have tried logging out and logging back and I refreshed it as many as I can remember. I would like to use the weapon that I fought hard for and that isn't fair for me to have to not be able to use it. 
Thank You.

**Comment by Villageacules** [comment]
Can you send me a screenshot of the item?

**Comment by BeastBrodie0** [comment]
Yes tomorrow morning I will

**Comment by Chewsterchew** [comment]
Day 3, no screenshot :(

**Comment by LordHelmchen98** [comment]
Thats because Bobs mythic items have set values that are not supposed to be changed. Therefore you cant reidentify them. Sadly the feature that prevents those wepons from being reidentified also prevents the unidentified items from getting identified for the first time.
