### ISSUE TITLE
Cannot Leave Guild

### ISSUE THREAD

**Issue by BigBenTX15** [Wynncraft/Issues#8694]
I have tried to leave my current guild multiple times. (At least 5.) Every time it says I have left my guild and takes soul points, but I never actually leave my current guild nor can I join a new guild. 

Could you please take me out of my current guild?
I would like to join a new one my best friend has made.

Username: BigBenTX
Guild: Lords of Prime

Thank you!

**Comment by Atnvo** [comment]
Hey,  I have the same problem. I joined a guild a long time ago and can't leave the guild anymore. 
IGN: Furious_Melon
Guild name: Night of Fire

**Comment by Eiyaa** [comment]
I was just about to make a report about this. I'm having problems too. I joined this guild in 2015 and have tried countless times to leave. Maybe it's because of my name changes?
My IGN is Eiya, and the guild is Guardians of Wynn. (WyG)

**Comment by RubbrDucky** [comment]
Guilds being bugged is a known issue, you just have to wait it out until a
fix like the rest of us :(

**Comment by colin350** [comment]
Like the README suggests, please don't post duplicate issues, instead comment on ones which are already open. See #3665.
