### ISSUE TITLE
Legendary Bow Got deleted

### ISSUE THREAD

**Issue by wynncrafts** [Wynncraft/Issues#8695]
So I'm level 25 name's Shad0wPhoenix and i was doing the Dwelling Walls quest when i accidentally dropped my bow into the teleport entrance to the mansion. I went to grab it and then it just got deleted as I went through. If anyone can help me with this please respond! It was a legendary with all elemental damage, 4-10 normal damage and normal attack speed.

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.
