### ISSUE TITLE
Cosmic boots are missing since I logged in.

### ISSUE THREAD

**Issue by HighlyDangerous** [Wynncraft/Issues#8697]
This morning I logged on, finding out my cosmic boots are missing. They were equipped on my boots slot the last time I logged out.
I am in no position to duplicate the ''glitch'' since I dont have another pair of cosmic walkers and im not in the believe that it happend because of that specific item. 

I am aware of the fact that you as server cannot do anything with the information given, but I hope that if this is a repetitious mention you will be. 
As for my boots, it would be great if I could get them back in any way. But I can understand if that isn't a possibility. 
Thanks for your attention and time.

HighlyDangerous.

**Comment by RubbrDucky** [comment]
I had the same thing happen to me with the cosmic helm...

Yeah we're not getting our items back ;-;

**Comment by colin350** [comment]
Wynncraft enforces a strict no-refund policy. What that means is that you won't be receiving your items back. Please note that this applies to all players, including staff and content team members. 

In terms of the issue, we are aware of it, and ideally refactor will fix it. Date as to when refactor will be complete is unknown.
