### ISSUE TITLE
Cant buy it denied my papall

### ISSUE THREAD

**Issue by monkeyjamie** [Wynncraft/Issues#8698]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

Hello i want to buy vip + 5 crates on ur server but it keeps denied my paypall i dont know how to fix this my firned in a other country gaved me a visa card 70$ and i can use it on every server but when i come on this server and i wanna buy vip it denies my paypall hope we can fix this or i pay to a admin and he gives me the ingame stuff or something let me know

**Comment by AscendedKitten** [comment]
I'd recommend contacting support@wynncraft.com; they are responsible for payment related issues.
