### ISSUE TITLE
Mesarock Arch bow doesnt have a texture

### ISSUE THREAD

**Issue by Basic6952** [Wynncraft/Issues#8700]
The mesarock arch bow doesn't have a texture it's just a prismarine block..
http://prntscr.com/g30gy9

**Comment by Basic6952** [comment]
Closed it because I thought it was fixed and realized it was another bow lmao

**Comment by AscendedKitten** [comment]
What version are you using? Down/up-grading should solve the issue.

**Comment by colin350** [comment]
This "issue" isn't really an issue because after the gavel update, weapons became retextured blocks. Please follow @AscendedKitten 's advice if you want to attempt to fix it.
