### ISSUE TITLE
Dwelling Walls Quest Broken

### ISSUE THREAD

**Issue by Elioot** [Wynncraft/Issues#8701]
I got Leucsaa's Journal from the mansion and have it in my inventory. but when I click her it does nothing. 
![image](https://user-images.githubusercontent.com/30631466/28835184-262c07e2-76aa-11e7-946b-b504af70e826.png)
![image](https://user-images.githubusercontent.com/30631466/28835189-2e42c98e-76aa-11e7-9be6-c94dc98f39b5.png)

**Comment by wynncrafts** [comment]
go through the actual exit instead of back tracking

**Comment by AscendedKitten** [comment]
As @wynncrafts stated, you probably went back the way you came in; there's an exit located close to where you found the journal.

**Comment by Elioot** [comment]
ok, thanks
