### ISSUE TITLE
The Envoy Part II

### ISSUE THREAD

**Issue by cameronee** [Wynncraft/Issues#8702]
Recently i have tried to do the quest The Envoy Part two and i'm at the part where it says "Meet the grandmaster behind her house and get over the gap and enter the temple" Before right as i went to the back the server reset and now it doesnt update the quest/she wont come make the bridge.

**Comment by AscendedKitten** [comment]
Try going through the house again, that might cause her to respawn.

**Comment by cameronee** [comment]
@AscendedKitten nope, still didn't work

**Comment by AscendedKitten** [comment]
Hmm, I'll try to check but according to the script it should trigger if you are in between **-1567, 163, -3322** and **-1543, 120, -3297**

**Comment by cameronee** [comment]
@AscendedKitten Still hasn't triggered :/

**Comment by LordHelmchen98** [comment]
I just tested it and it worked perfectly fine.
If you still have the issue try to find me ingame. (ign: Lord_He1mchen)
