### ISSUE TITLE
really annoying spamming 'you do not have persmission for this area'

### ISSUE THREAD

**Issue by fishysteph** [Wynncraft/Issues#8706]
ive been  really annoyed and totally laggged but also hasnt been able to attack by this annoying spam , i was in a commun area of the world when it started , i cant even fight anymore please help !
heres some images :
http://imgur.com/a/AKvFE

**Comment by AscendedKitten** [comment]
That's probably caused by the weapon you are using; some of them are re-textured blocks, and the system thinks you intend to place it which yields that error message. Maybe try switching / clicking with another item?
