### ISSUE TITLE
WynnExcavation Site B - Bug/Glitch idk

### ISSUE THREAD

**Issue by Didijey1234** [Wynncraft/Issues#8707]
So, Normal Stuff I started the quest, but near the place I already couldn't open some loot chests, continuing, going deep on it, when you reach the guy that throws you to the waterfall you get stuck like, you get teleported but always appear - 'You don't have permission to this area' - And when you reach the Puzzle, R.i.p M8 like you get stuck 4ever, like me cuz I forgot my Scrolls to teleport. Well, all I can do is a wait to you guys fix this bug/glitch. ( i Have Screenshots too ) ( Scroll Down pls) ( No I'm not Mad cuz I know that bugs/glitches happen =D 
Ps: I tried to put the code (124563) and the same thing appears - 'You don't have permission to this area'.
Or if somebody reaches me and bring some Scrolls to I continue my Journey I would be happy. =)
-
Plss Fix This.
-
![2017-07-31_19 20 23](https://user-images.githubusercontent.com/30672924/28898731-11b47654-77d7-11e7-8b7a-e6279aca0442.png)
-
![2017-07-31_19 20 25](https://user-images.githubusercontent.com/30672924/28898738-1a2a66fe-77d7-11e7-9c52-1502b8de9d88.png)
-
![2017-07-31_19 20 27](https://user-images.githubusercontent.com/30672924/28898762-2c5f2954-77d7-11e7-8f8b-b416b83e4eb7.png)
-
![2017-07-31_19 20 30](https://user-images.githubusercontent.com/30672924/28898771-339a6c2e-77d7-11e7-9f62-ce6d526c246e.png)
-
![2017-07-31_19 20 42](https://user-images.githubusercontent.com/30672924/28898783-4184f494-77d7-11e7-84ed-8ca237b1e81e.png)

**Comment by Elioot** [comment]
Use your fist. Not the weapon.

**Comment by Didijey1234** [comment]
Ohhh, ok ok Elioot i will try it right now =D
