### ISSUE TITLE
me and My friends are bugging in a Dungeon 

### ISSUE THREAD

**Issue by PaulxMioX** [Wynncraft/Issues#8709]
Hello my Name is Paul 16 years old my problem is that i bug in the Ice Barrow Dungeon whit my friends and we  cant do anything we need fast help we dont want to stuck there anymore 
in game names xMioX leSkylex BimFxmeBiqtch

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!
