### ISSUE TITLE
Can't log into server, server out of date

### ISSUE THREAD

**Issue by sjnasr** [Wynncraft/Issues#8712]
Hello

I'm unable to log into the server.  When I click join server on the server list it returns "Failed to connect to the server.  Outdated server!" 

On the server list, the following line BungeeCord 1.8x, 1.9x, 1.10x, 1.11x, 1.12x is across the Wynncraft title on the list.

**Comment by sjnasr** [comment]
I fixed it.  There was a new release of 1.12.1 which wasn't compatible.  I downgraded to 1.12.

**Comment by colin350** [comment]
Solution: 1.12.1 is currently not supported by Wynncraft.
