### ISSUE TITLE
Multiple wynncraft accounts? Part my fault, part sites fault

### ISSUE THREAD

**Issue by chaosemperor1997** [Wynncraft/Issues#8713]
**so i had a wynncraft account like 2 years ago and forgot i had it.**  
I made a new account because i forgot I had the old one but accidentally mistyped my player name.
Now my email is associated with my new account which doesn't have a minecraft account tied to it.
I can't reset my password because it thinks i'm resetting my new account. 
Now I don't know what to do. 
**Also apparently my minecraft account itself has 2 wynncraft accounts.**
One from 2 years ago and a second with all of my current stuff. At some point between a hiatus of myself playing the game, I was no longer able to access my builds so I just went with it.
 **Is someone able to tell me what I should do to regain access to my wynncraft web account?**

**Comment by colin350** [comment]
Best advice I can give you right now is to email support@wynncraft.com. They'll direct you to the next steps.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can create a thread in the [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
