### ISSUE TITLE
Stuck in a Wall

### ISSUE THREAD

**Issue by wierdo1093** [Wynncraft/Issues#8714]
I was at the entrance to Bob's Tomb(I don't know exactly where) and then I logged out. After I logged back in the next day, I was stuck in a wall/ceiling and could not move. Something similar has happened to me before, where I end up being put in the wrong spot after logging back in. Unfortunately, I don't have any teleport scrolls with me so I can't teleport out of the wall either.

**Comment by ittnoraA** [comment]
Heyo! If you have 5 or more soul points, do `/kill` to respawn in the nearest city to you.
