### ISSUE TITLE
I lost a boat

### ISSUE THREAD

**Issue by Santeripe** [Wynncraft/Issues#8716]
Hi, I was on my boat, on a little river next to Nemract when my Minecraft has crashed. I return on Wynncraft and I see that my boat has disappeared ! I'm on the water, with a lots of skeletons around me but no boat ! Please answer me fast, and sorry for the mistakes I'm French

**Comment by LA1S0N** [comment]
Boats are glitchy in Wynncraft so expect something like that to happen.

**Comment by Santeripe** [comment]
In 1.12 yes, but I was in 1.8, and in 1.8 boars are normal

**Comment by Santeripe** [comment]
Boats*

**Comment by thecoolkogut4** [comment]
If you disconnect and no players are around you, all the entities in the chunk will despawn. You logged out in the middle of the ocean, nobody was around and your boat went away. I'm 90% sure that's how it works and that this is not a bug.

**Comment by Santeripe** [comment]
I was in the middle of the river, next to Nemract and the church, and when I reconnected they were like 5-6 skeletons around me

**Comment by colin350** [comment]
Mob spawn rate is unrelated to chunk loading. @thecoolkogut4 is correct in that if you disconnect and no players are around you, the chunks you were in will unload (to reduce server lag). Doing so will cause entities to despawn. 

If the chunks were still loaded: Boats disappear if a player isn't in them. When you disconnected, the server was probably confused by whom the boat belonged to and despawned it (to reduce lag). It also doesn't have the feature to add items to a player inventory which is offline.
