### ISSUE TITLE
Out of my Mind Door malfunction

### ISSUE THREAD

**Issue by Moonmajesty** [Wynncraft/Issues#8719]
I am currently doing the the Out of my mind Quest and died fighting the Malignant Beast. When I went back and completed the cannon puzzle the door after won't open for me to continue. 
After using the /kill command and returning a second time I was able to continue. I assume that I completed the puzzle to quickly/ while he was still speaking and that glitched the game.

**Comment by colin350** [comment]
Could you attach a screenshot of which door you are referring to?

**Comment by Moonmajesty** [comment]
The game wont let me back in since I complete the quest, but I looked up a play through and took a screenshot of the door I'm talking about. 
![door](https://user-images.githubusercontent.com/30738953/29102433-e9cdf9c6-7c6d-11e7-9e9c-ef5b1b0b8892.PNG)

**Comment by LordHelmchen98** [comment]
You said you were able to continue after another attempt so it was probably a one time issue and most likely related to redstone like a few other things.
