### ISSUE TITLE
Underice didn't give me my Calamaro's Token.

### ISSUE THREAD

**Issue by KingShadowFall** [Wynncraft/Issues#8724]
I wanted to get the Calamaro's Bow so I did the quest; Underice. But after doing the quest (with inventory spaces freed) i got everything but the token, which was the one thing I was actually trying to get. I see that I'm not the only one that this happened to. I tried the command to get the quest items back but that didn't work. Please get back to me and help me get it back. Thank you.

**Comment by ittnoraA** [comment]
Note, that there are 2 possible endings for the quest. You'll only get Calamaro's token if you give the pufferfish to Calamaro. Giving the pufferfish to Gernald will result in him gifting you with a necklace.

Are you sure you got the correct ending?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can create a thread in the [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
