### ISSUE TITLE
I can't join any wynncraft world.

### ISSUE THREAD

**Issue by Rhowan** [Wynncraft/Issues#8725]
I can not join any wynncraft world, i can join the nether but i can't join the normal world where u play in.
If anybody knows a solution pls let me know.

**Comment by colin350** [comment]
What version are you using?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can create a thread in the [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
