### ISSUE TITLE
Banned on server, not on forums

### ISSUE THREAD

**Issue by GodOfMonsters** [Wynncraft/Issues#8726]
As the title describes the bug a bit, i'm banned on the server, but it doesn't say i'm banned if i go on forums. This most likely occured because of a server reset.

**Comment by ittnoraA** [comment]
Being banned ingame is a completely different thing than being banned from the forums. I'd recommend reading this thread for more information: https://forums.wynncraft.com/threads/game-forum-rules.111874/

**Comment by GodOfMonsters** [comment]
I'm banned ingame, but when i try to appeal on forums it says that i'm not banned ingame.

**Comment by PepinhoJp** [comment]
From what I heard appeals on the forums are bugged, email support@wynncraft.com
