### ISSUE TITLE
I'm having trouble with Memory Paranoia

### ISSUE THREAD

**Issue by Sarah10098** [Wynncraft/Issues#8727]
Hello Serverteam
I found a glitch in the Quest: Memory Paranoia
The Glitch is: I cant go to the Masters Bedroom.  It olso says the that i need a key wich i already have.
Sometimes it olso teleports me back to the turtorial of the whole game.
I really love the game wynncraft but that Glitch is really nasty.
please fix that glitch as fast as you can.
( sry if i didnt write right, because i speak and write normally german)
Greetings Sarah100898

**Comment by thecoolkogut4** [comment]
Hey there,

For the tutorial area, this is a very well known bug. When you die off map (during a quest, or for any other reason your outside), you get sent to the closest respawn point, either a town or the starting area. You are just going to have to walk back to where you died. For the quest part of the report, sorry I can't help you there 😢

Goodluck!

**Comment by LordHelmchen98** [comment]
Heyo, ich weiß nicht wie gut du Englisch sprichst, deshalb wiederhol ich das meiste einfach nochmal.
In Wynncraft gibt es überall (hauptsächlich in Städten) Punkte, zu denen man teleportiert wird, wenn man stirbt. Dazu wird immer der Punkt gewählt, der zum Todeszeitpunkt am nächsten ist. Leider sind die Questgebiete, zu denen man teleportiert wird, hauptsächlich abseits der normalen Karte und daher ist es möglich, dass plötzlich ein anderer Punkt näher ist. Deshalb wird man häufig zu falschen Punkten teleportiert und das Startergebiet scheint dafür am häufigsten ausgewählt zu werden. Möglicherweise wird das in Zukunft geändert, aber vorerst müssen wir alle damit leben. 
Was die Quest selbst angeht würde mich interessieren, was genau da passiert. Kommst du bis zur Tür bevor irgendwas passiert? Läufst du über eine tripwire die dich teleportiert? Was sagt dein Questbuch?

**Comment by Sarah10098** [comment]
Also Mein Questbuch sagt das ich in den MasterBedroom muss.
Ich bin also dahingegangen über die Tripwire wurde teleportiert vor das Mastersbedroom
dann bin ich mit dem key wie mann halt sollte an die Schlafzimmertür herangetreten.
Aber statt dass ich weiter teleportiert wurde wurde mir im chat immer gesagt das ich einen Schlüssel also Key benötige( also den Mastersbedroom key) den ich allerdings schon in der Hand hatte. Und 2 mal wurde ich dann nach mehrmaligem Versuch an den start des Spiels also Turtorial start tpt.

LG
Sarah10098

**Comment by LordHelmchen98** [comment]
Wenn du zum Master Bedroom teleportiert wirst, sollte theoretisch ein Zaun an der Tür sein, der eine Art NPC ist. Hattest du versucht den anzuklicken?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can create a thread in the [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
