### ISSUE TITLE
the resource pack wont work

### ISSUE THREAD

**Issue by puremech** [Wynncraft/Issues#8729]
The resource pack wont work i enabled it and it still wont work it asks if i want to download it and i say yes but it wont download it so i cant use the resource pack can anyone help me

**Comment by PepinhoJp** [comment]
From what you said, you can't use the resource pack, but you have to click "Yes" or "No", make it always enabled following this guide: https://forums.wynncraft.com/threads/cant-play-wynncraft-because-of-the-pack-heres-how-to-fix.98023/

**Comment by puremech** [comment]
i have done that and it still wont work

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can create a thread in the [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
