### ISSUE TITLE
I can't change my name on the forums.

### ISSUE THREAD

**Issue by ICantChangeMyName** [Wynncraft/Issues#8731]
When I first made my forum account I wanted to be edgy and have my name is weird fancey latters. I recently changed my Minecraft username and Now I want to do the same on the forums. It  says there is a 90 day wait period in between name changes but I never changed my forum name before and it wont let me change my name. When I go to change my name this happens. ( https://gyazo.com/da5ff8ae3c231389fb45cca3f422d724 ) On top of that I don't know where to change my Minecraft name on the forum.

**Comment by colin350** [comment]
Did you create your account less than three months ago?

**Comment by ICantChangeMyName** [comment]
I made it around 3 years ago

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can create a thread in the [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
