### ISSUE TITLE
Item Buyer wont work!!!

### ISSUE THREAD

**Issue by RAALightning** [Wynncraft/Issues#8732]
when I click my item, nothing happens. Even when i drag it up to the slot it doesn't work PLZ HELP MEH...

**Comment by PepinhoJp** [comment]
Try switching servers

**Comment by thecoolkogut4** [comment]
Left click it (make sure the item does not have unreadable or quest item written on it) then click the first slot in the item buyer. 

Which item buyer are you trying to use? What item(s) are you trying to sell?

**Comment by Moe-Ronickah** [comment]
When you put an item into the the item buyer's slot, and nothing happens, just click an empty slot.  It's a known, minor glitch.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can create a thread in the [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
