### ISSUE TITLE
once again, another guild glitch

### ISSUE THREAD

**Issue by Tobulance** [Wynncraft/Issues#8734]
sometimes, randomly, when teleporting to war you get a message that gives an error, thus permanently making it so that you are not able to war at all, so if you are a guild of high level, you have no hope of ever going any higher. currently my guild NYN is stuck in this and cant get out of it, and this is the 2nd time this has happened, if there is anyway to do some kinda command to free up a specific guild, i would greatly appreciate it

**Comment by thecoolkogut4** [comment]
This is a known issue and there's currently nothing to do that can fix it. My guild has been stuck in it countless amount of times. Its just something that you need to deal with. This normally lasts 2-10 days

**Comment by colin350** [comment]
#3664
