### ISSUE TITLE
Lost Sanc. glitch

### ISSUE THREAD

**Issue by traviryan88** [Wynncraft/Issues#8735]
Just right now, I was running the Lost Sanc. dungeon without any issues. My 3rd time around, I tried to get past the parkour just after you fall through the entrance. But I cant get through. It almost seems like something broke (like the tripwire string). I'm just stuck sitting at the first part because I can't get through to the next part because the barrier blocks are not allowing me. Someone else tried coming through it, and the same thing happened to him. This is on world 14.

**Comment by thecoolkogut4** [comment]
Try switching worlds, and use Mc version 1.8.9. let me know how it goes. Goodluck

**Comment by traviryan88** [comment]
I switched worlds and it worked. I guess ill have to start using 1.8.9 for wynn. Thanks for the help

**Comment by thecoolkogut4** [comment]
No problem, most of the bugs get fixed when you a) switch worlds b) use Mc version 1.8.9
