### ISSUE TITLE
Eye of the Storm

### ISSUE THREAD

**Issue by Abnormals** [Wynncraft/Issues#8737]
There's no way to prove this I don't think but I just killed Naragath and he didn't drop an Eye of Blood. I am so pissed right now, PLEASE HELP.

**Comment by thecoolkogut4** [comment]
Try switching servers, make sure you look all over the place to find the drop.

**Comment by Abnormals** [comment]
I did look everywhere.

**Comment by thecoolkogut4** [comment]
Was someone else with you? Is it a possible that they picked it up?

**Comment by Abnormals** [comment]
No I did it by myself, it took like 15 minutes

**Comment by thecoolkogut4** [comment]
I've been there before, it's a really busy room and it's dark, easy to miss (I believe). Try killing it again and see how it goes.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can create a thread in the [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
