### ISSUE TITLE
Stuck Underground

### ISSUE THREAD

**Issue by SleepyNapper** [Wynncraft/Issues#8739]
Hello, I was completing the quest Elemental Exercise, I got to the part where I was supposed to find another way out of the cave. And when I did and was about to teleport out, it didn't and now I'm stuck underground (I can't move). My character's name is SleepyNapper and I was on my lvl 10 Archer. Can you please move me out and into another town? I literally can't move and tried to get in touch with an Admin but no one was on. Thank you for reading this and I hope you can help me soon! Have a great day.

**Comment by DevilmineYT** [comment]
Hello SleepyNapper, If you bug in the Underground, use /kill or find a way out (Coalblocks mark the Exit)

**Comment by SleepyNapper** [comment]
thats the thing, I walked into the coal blocks and didn't get teleported but at the same time got stuck and couldn't move.. anyways thank you for answering ill do /kill to get out. Have a great day.
