### ISSUE TITLE
Item Deletion Glitch

### ISSUE THREAD

**Issue by DotExEWC** [Wynncraft/Issues#8741]
I was in Nemcract at 11:29 AM 8/9/2017. I identified the wand, and put my old wand in the bank, and was walking into the inscription store. When I clicked on the inscription worker, the GUI came up, but the wand disappeared. I walked around to make sure I didn't drop it, but it was gone.

**Comment by thecoolkogut4** [comment]
Is there a possibility that you dropped your wand? Last time I checked nothing should be taken away when clicking that NPC. Can you recreate this issue or was it just a one time thing? Even though you did not ask, I'd like to inform you about Wynncrafts strict non-refund policy which means you won't be getting the wand back. Sorry.

**Comment by DotExEWC** [comment]
It happens all the time when the server/me starts lagging. I cannot put certain items into certain slots, sometimes items dissapear from my hotbar, only to reappear when I open my inventory.

**Comment by thecoolkogut4** [comment]
I think that's just a client side thing which then effects your inventory in game. I know what your talking about, it's happend to me but that's client side lag which gets you to lose your items. Do you also get lag on other servers?

**Comment by DotExEWC** [comment]
No only on this one. Buuuut I'm also stuck :/

**Comment by DotExEWC** [comment]
also I might have glitched out a quest item and now its permanently gone. I clicked the item to make it float, and then a new item came in. I pressed e on accident and the item disappeared :/

**Comment by thecoolkogut4** [comment]
Type /fixquests to get your quest item back.

**Comment by DotExEWC** [comment]
You guys need to put these commands in /help XD it would make it so much easier, as I checked /help first lol.
