### ISSUE TITLE
Item deleted

### ISSUE THREAD

**Issue by Chingy02** [Wynncraft/Issues#8743]
I was doing the confused farmer quest and was on the second step when my weapon got deleted. I teleported to Detlas when it told me too and all of a sudden my Witherhead's bow was gone. I used another teleport scroll to get back to where I was (Ragni outskirts), but the bow was nowhere to be found. Please give me another Witherhead's bow as I see this as a glitch and it was not meant to be deleted. Thank you for your understanding.

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by colin350** [comment]
Reminder: the no-refund policy applies to all players, including staff members and content team members. There are also no exceptions.
