### ISSUE TITLE
Item Deleted Glitch

### ISSUE THREAD

**Issue by AirShadow** [Wynncraft/Issues#8744]
I had a legendary weapon, "Legendary Smasher", I used a teleport scroll, and my weapon disappeared, It was my only weapon, so if someone could help me, I wouldn't even know how to thank him !

Thank you for reading, AirShadow

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by DotExEWC** [comment]
Me too ;-; It happens to all of us, its kind of like a ritual.

**Comment by colin350** [comment]
Reminder: the no-refund policy applies to all players, including staff members and content team members. There are also no exceptions.
