### ISSUE TITLE
Stuck Above World Height Glitch :/ pls im stuck and cant get out ;-;

### ISSUE THREAD

**Issue by DotExEWC** [Wynncraft/Issues#8745]
My friend BuzzTom was exploring the mountains and using the teleportation spell, and teleported THROUGH the invisible blocks/ height limit. He accidentally did this, and when I tried to save him, it failed. I bought two teleportation scrolls and tried to glitch up with him. It failed, and I'm stuck with him in a 1x1x2 area. The teleportation scroll isn't working, and me and my friend have no way to get unstuck. help us please.
![2017-08-09_18 26 47](https://user-images.githubusercontent.com/30871292/29146648-4fd167f4-7d30-11e7-9e4e-e6047a20f8cf.png)

As you can see I'm looking at Minecraft:Barrier while facing downwards. It should be ABOVE me.

**Comment by DotExEWC** [comment]
As you can see I'm looking at Minecraft:Barrier while facing downwards. It should be ABOVE me.

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!
