### ISSUE TITLE
Issue Claiming Monthly Free Crate

### ISSUE THREAD

**Issue by Merpy** [Wynncraft/Issues#8746]
I've been trying to claim my monthly crate for the past few days with success, the first time I press the "Free Monthly Crate" button, it sends me to the page where I can enter my username, which I entered exactly with correct caps etc. It then takes me back to the store homepage and I tried pressing the monthly crate button again, but I do see that in the url bar it tries to send me to the checkout and then ends up sending me back to the store homepage over and over. Please let me know if this is a bug for others or it might just be me. Thanks <3

**Comment by thecoolkogut4** [comment]
If you already got your monthly crate this happens. When you login, check to see if you have a crate. Are you sure the last time you got a crate was a month ago?

**Comment by Merpy** [comment]
Do I need to wait the full 30-31 days?

**Comment by RubbrDucky** [comment]
no. It's exactly one month from when you last got it.

**Comment by Merpy** [comment]
Oh alright, I thought it just refreshes at the beginning of each month. Thanks <3
