### ISSUE TITLE
Quest Item Gone

### ISSUE THREAD

**Issue by Jmonster2** [Wynncraft/Issues#8749]
I was doing the quest Aldorei's Secret Part 1 and I was at the final part where you choose to either give the boots to Kansard or Corak. I gave the boots to Kansard but before his lines could finish I was kicked from the server. Now all it says is give the Sunblight boots to either one of them even though I no longer have it. It is completely gone. Not sure how you deal with this.

**Comment by thecoolkogut4** [comment]
Type /fixquests to get your item back.

**Comment by Jmonster2** [comment]
oh thank you so much. Never knew that was a command

**Comment by thecoolkogut4** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft!
