### ISSUE TITLE
boss drop glitch

### ISSUE THREAD

**Issue by ckeeperkiller924** [Wynncraft/Issues#8750]
I died 15 times and spent 5 le trying to kill the final boss of wynnexcavation site D then when I finally get close to killing him when some guy and his friend walk in steal the kill and the items that the boss drops for the quest goes to both of them but not me and now I'm broke from all the money I spent on potions

**Comment by thecoolkogut4** [comment]
You need to do 10% or more of the damage to the boss to get a drop. There's nothing else you can do but kill Amadel again.
