### ISSUE TITLE
??? has messed up teleport in blue meteor

### ISSUE THREAD

**Issue by Nike020410** [Wynncraft/Issues#8755]
My log:
23:43:56 | avt | Client thread | info | [CHAT] The madman's favorite food lies in a place of changing perspective.
23:43:56 | avt | Client thread | info | [CHAT] >Commencing warp sequence...

Screenshot, trimmed to make sure there are no insulting lines of text:
http://imgur.com/StY8fwX

The teleport didn't work in 1.12.1 and 1.8.9 (Yes, we did test it twice.).

Additional information: I got the slowness, I got blindness and particle effects. Everything. Anyone else got teleported (in 1.11+).

**Comment by thecoolkogut4** [comment]
Your in the wrong spot. You need to be inside of the meteor not ontop of it in order to get tped. I believe you need to press a button on the back of the meteor, then a piston door opens and you can go inside. Once inside step in the pressure plate and you'll get tped.

**Comment by Nike020410** [comment]
How should I get the message that I got rocketed or the stuff with teleport, I was **inside**.

**Comment by thecoolkogut4** [comment]
When your inside, don't go through the door just stand on the pressure plate

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can create a thread in the new [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
