### ISSUE TITLE
Site D issue

### ISSUE THREAD

**Issue by TieveAR** [Wynncraft/Issues#8756]
I was doing site D and had finished the shadow boss i went on to the 3rd and final boss and was able to kill him but he never dropped anything for me to get past and later re-spawned killing me while i was looking for the item he was supposed to drop, i don't want to deal with beating him on my own again and i was wondering why i wouldn't get the item from him. any info on this would be nice before i attempt to do this again thanks.  IGN:   _Tieve

**Comment by thecoolkogut4** [comment]
This is a new feature in wynn. When one mob dies another one instantly respawns (as a second form). So when you killed it the first time, it just brought it to the second form.

**Comment by TieveAR** [comment]
so it has to be killed multiple times then got it thanks.
