### ISSUE TITLE
Stuck underground

### ISSUE THREAD

**Issue by AirShadow** [Wynncraft/Issues#8757]
I was doing the "Green Skinned Trouble" Quest, i killed "Greggr" Then I went back in the exit and it teleported me undergroud at -1866, 28, -4898, please help me !
Like really HELP!

**Comment by AirShadow** [comment]
sorry for my bad English

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by AirShadow** [comment]
Ok thanks !

**Comment by AirShadow** [comment]
It worked!

**Comment by thecoolkogut4** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft!
