### ISSUE TITLE
Update Room

### ISSUE THREAD

**Issue by noeg166** [Wynncraft/Issues#8758]
Hi, My ingame name is noeg1662, and i haven't played in a long time and well my classes went in the update room and well the gear i had was changed to unidentified and i tried identifying some of my stuff and for like my dagger it thinks it isn't identified and it shows this http://imgur.com/a/dPhh6 so please help and also it would of been helpful to make the update room identifying free as a lot of my gear i had identified already got unidentified and i am apparently broke on that account so i can re identify my items and gear which is quite unfair since i already did hard work to identify them it did this to all my 5 classes i got and  I'm lvl 75 on assassin and warrior, lvl 47 on archer, 28 on mage, 12 on knight, and lvl 1 on hunter

**Comment by thecoolkogut4** [comment]
Everyone had to reidentify their items to convert them to the new system. Your not the only one.

**Comment by LordHelmchen98** [comment]
As thecoolkogut4 said you are not the only one who had to spend money on their items after the Gavel update. Regarding that dagger that cant be identified. Thats probably Bobs Mythic Dagger. It has set values and cant be reidentified. Sadly that is also the reason why you cant even identify it once.

**Comment by noeg166** [comment]
oo ok i see well thanks anyways
