### ISSUE TITLE
ToA 3rd floor boss

### ISSUE THREAD

**Issue by miningmoooshroom** [Wynncraft/Issues#8762]
I was doing the ToA quest, after killing the boss at 3rd floor, lvl75 witch-doctor-clone(I believe that's his name), he didn't drop the key, I killed him many times but it just didn't drop it.

**Comment by thecoolkogut4** [comment]
What happens when you switch worlds?

**Comment by miningmoooshroom** [comment]
I did /class, but it didn't work

**Comment by miningmoooshroom** [comment]
Nevermind, it works now.
Thanks!
