### ISSUE TITLE
The Envoy part II

### ISSUE THREAD

**Issue by cameronee** [Wynncraft/Issues#8763]
There are so many issues with this quest. I'm at the part where it says "Meet the grandmaster behind her house and get over the gap and enter the temple" right as i went to the back the server reset and now it doesnt update the quest/she wont come make the bridge. Someone told me the exact coordinates where the quest updates and I've tried everything i can do but it still wont update.

**Comment by thecoolkogut4** [comment]
What does your quest book say?

**Comment by ittnoraA** [comment]
Try re-entering the house, and going behind the house again. If that doesn't trigger the event, you should manually be able to get on top of the hill opposite of you.

**Comment by cameronee** [comment]
I've already tried going through the house, hasn't worked. My book says Meet the grandmaster behind her house and get over the gap and enter the temple"

**Comment by LordHelmchen98** [comment]
Usually the grandmaster should spawn if you trigger the tripwire inside the house and then walk behind the house.
If it doesnt you can create a thread in the new [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
