### ISSUE TITLE
fantastic voayge

### ISSUE THREAD

**Issue by victorayres** [Wynncraft/Issues#8764]
i was doing the fantastic voyage quest and when i was doing the explosives i didn't revived the explosive so i can't continum doing the quest. What i can do to get another explosive??

**Comment by thecoolkogut4** [comment]
What happens when you type /fixquests

**Comment by victorayres** [comment]
worked thank you vert much

**Comment by thecoolkogut4** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft!

**Comment by LordHelmchen98** [comment]
RESOLVED
