### ISSUE TITLE
Item glitch

### ISSUE THREAD

**Issue by cheeselp** [Wynncraft/Issues#8765]
Hello dear Wynncraft team I was in the Undergrowth Dungeon and when I just put the Tokens in my inventory bar, my bow has returned to the place so to say, and then I threw my bow into the hopper.
Is there any way to get my bow back. It was from the quest "The Shadow of the Beast"

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.
