### ISSUE TITLE
Daily loot streak broken?

### ISSUE THREAD

**Issue by poolcool2** [Wynncraft/Issues#8767]
So I started playing wynncraft again recently and decided to get my daily loot streak as high as possible, one it got around 5 (I was told 5 was max) It went back down to 1, I was confused so I decided to try again, but the very next day (today) it was still at 1, and I made sure to come back at 5:00 for both (I was told it resets after ~48 hours if not claimed)

**Comment by Moe-Ronickah** [comment]
It resets after 24 hours, and it's on Eastern Standard (or Daylight) Time.
