### ISSUE TITLE
Liquid Emerald has disappeared

### ISSUE THREAD

**Issue by Artlesshunterl** [Wynncraft/Issues#8768]
Hello, everyone on the Create Team.
When I talked to NPC while holding the Liquid Emerald just before, the Liquid Emerald that I had had disappeared, does my Liquid Emerald come back?

**Comment by thecoolkogut4** [comment]
No, it will not come back.

**Comment by Artlesshunterl** [comment]
oh...okey ;(

**Comment by acid-trip209** [comment]
sad
