### ISSUE TITLE
Anyone here?

### ISSUE THREAD

**Issue by Rulzzzz** [Wynncraft/Issues#8771]
"Someone told you more about the patriots of Corkus. you should continue to find the missing clue", Im stuck here. This is where the quest fucked me up. Ive already found all 3 NPC's. I've already done everything they told me. I watched a video and after the guy finished finding all 3 clues, i he needed to follow the blood trail. You see my friend, IT WONT LET ME FOLLOW THE BLOOD TRAIL.

**Comment by thecoolkogut4** [comment]
What happens when you switch servers?

**Comment by Rulzzzz** [comment]
I tried, same thing. "Quest book not updated"
