### ISSUE TITLE
Dwelling Walls is broken

### ISSUE THREAD

**Issue by joshish** [Wynncraft/Issues#8772]
I can't access the book. I have been doing it for 30 minutes and trying every option and I can't get to it.

**Comment by thecoolkogut4** [comment]
Google something along the lines of "dwelling walls walkthrough" to find out how to do the quest.

**Comment by joshish** [comment]
I have. But I still can't get to it. it is broken for me.

**Comment by acid-trip209** [comment]
there is another switch button on the third floor.Try and get there,when u do switch it once and go ontop of the book there will be a hole where u can drop down to the book.
