### ISSUE TITLE
Grave Digger brother won't drop and respawns on death

### ISSUE THREAD

**Issue by AdinAck** [Wynncraft/Issues#8774]
I am doing the grav edigger quest and saylerons brother will respawn when he dies and doesnt drop the will. I have switched servers, reloaded game, etc.

**Comment by thecoolkogut4** [comment]
You have to kill it multiple times. There are various forms and every time you kill it, you remove 1/x forms..

**Comment by LordHelmchen98** [comment]
RESOLVED
