### ISSUE TITLE
Lost Soles server restart glitch

### ISSUE THREAD

**Issue by Mammothh** [Wynncraft/Issues#8778]
Ok so i'm started the lost soles quest and gave the boots to Ferndor and mid conversation the server restarted. I log back in to find my boots gone and Ferndor still asking for the boots. Please help I know this isnt really a bug but I dont think there is another way to complete this quest, my username in minecraft is Mammoth. Thanks,
                           Jp.

**Comment by thecoolkogut4** [comment]
Type /fixquests to get your item back.

**Comment by Mammothh** [comment]
Thank you so much!
