### ISSUE TITLE
Mixed Feelings

### ISSUE THREAD

**Issue by Rulzzzz** [Wynncraft/Issues#8780]
"Someone told you more about the patriots of Corkus. you should continue to find the missing clue", Im stuck here. This is where the quest fucked me up. Ive already found all 3 NPC's. I've already done everything they told me. I watched a video and after the guy finished finding all 3 clues, i he needed to follow the blood trail. You see my friend, IT WONT LET ME FOLLOW THE BLOOD TRAIL. I tried switching servers, but it still wouldnt work. WTF wynncraft?

**Comment by RubbrDucky** [comment]
Are you on 1.8.9?

**Comment by Rulzzzz** [comment]
No i am on 1.12.
