### ISSUE TITLE
Boat glitch #HELP

### ISSUE THREAD

**Issue by arhimede007** [Wynncraft/Issues#8782]
When i try to sail with my boat..I go into the boat and then the boat drowns(goes into deep).Because  I cant use a boat I cant do some quests//(Pirates Trove, Ice Nation)
So please tell me what should i do??????

**Comment by acid-trip209** [comment]
U need to go to 1.8 or just swim there.1.10+ boats are different in terms of codes etc

**Comment by arhimede007** [comment]
Thanks a lot now I can level up!
