### ISSUE TITLE
Lost Sanctuary bug

### ISSUE THREAD

**Issue by Lenin1917** [Wynncraft/Issues#8784]
Dangeon: Lost Sanctuary (boss)
After drop out some TNT, falling out to redstone above lava pool. Help me plz \
![2017-08-16_16 58 16](https://user-images.githubusercontent.com/31068259/29362958-6e63a728-82a7-11e7-8c33-4220d75082af.png)
![2017-08-16_16 58 17](https://user-images.githubusercontent.com/31068259/29362957-6e6098e4-82a7-11e7-9c45-4d91fa54ac1b.png)
![2017-08-16_16 58 18](https://user-images.githubusercontent.com/31068259/29362956-6e5f1032-82a7-11e7-9e70-8c23a129496a.png)
![2017-08-16_16 58 19](https://user-images.githubusercontent.com/31068259/29362959-6e660eaa-82a7-11e7-9e63-5ab89328078a.png)
Nick: Lenin1917

o/

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by Lenin1917** [comment]
thx
