### ISSUE TITLE
Invisible wall bug and cant leave please help

### ISSUE THREAD

**Issue by cyberslouchgaming** [Wynncraft/Issues#8788]
I'm in the decrepit sewers dungeon and am stuck in the hall by an invisible barrier after the first door I tried dying and restarting with a new key but its still happening what am I doing wrong and how can I get passed this?

**Comment by thecoolkogut4** [comment]
Switch servers, and try playing on 1.8.9. keep switching servers till the barriers are gone

**Comment by cyberslouchgaming** [comment]
ok ty
I will do that

**Comment by colin350** [comment]
Please use the search bar next time to search for duplicate issues. Here's an example search: https://github.com/Wynncraft/Issues/issues?utf8=%E2%9C%93&q=decrepit%20sewers 
That's a lot of duplicates, I must say...
