### ISSUE TITLE
Stuck in Mixed Feelings

### ISSUE THREAD

**Issue by Rulzzzz** [Wynncraft/Issues#8789]
so apparently switching servers and changing versions work fine with some other quests, so how about Mixed feelings? :D

**Comment by thecoolkogut4** [comment]
Go ahead and try switching servers. Please stop making multiple issues, instead just comment on your original one.

**Comment by Rulzzzz** [comment]
Soooooooooooo switching servers is basically swicthing worlds?

**Comment by thecoolkogut4** [comment]
Correct.

**Comment by Rulzzzz** [comment]
nope, tried it. went to 1.8.9, joined ALL the worlds in lobby1,2 and 3

**Comment by Moe-Ronickah** [comment]
Rulzzzz, do not make more than ONE issue about the same problem.

**Comment by Rulzzzz** [comment]
Nope, still didnt work. Like the quest is actually so fucked up now

**Comment by colin350** [comment]
Hello,

@Moe-Ronickah has asked you nicely to stop making duplicate issues. In fact, you keep complaining that a staff member isn't helping you. Please let me clear some things up for you:
1. Bug reports ***are not*** maintained by staff members. They are handled by select volunteers and select quality assurance members. 
2. Staff members cannot fix your quest. We are sorry, but that is not how it works. 
3. Your tone and frustration is uncalled for. We will attend to your issue when we can. 

But, for the answer you've been probably waiting for:
The GM who designed the quest has been aware of this issue for a few months now, and it has already been attended to from our end. Unfortunately, we cannot push the fixes to production until the next update. You'll have to put aside your frustration and wait until the next update, which is confirmed to be very soon. 

Thank you.
