### ISSUE TITLE
Thanos - Small bug

### ISSUE THREAD

**Issue by xGoldie** [Wynncraft/Issues#8790]
I don't know if this is all the time or just my client, but I've noticed a small bug.
 When I enter the "Thanos" fort, it shows the text when you enter/leave an important location on my screen as normal, but it says "You are now leaving Thanos" instead of entering, and when I'm leaving it says "You are now entering Thanos" instead of leaving.
 Again, this might just be my client, but please consider checking it out!

**Comment by colin350** [comment]
We have pondered this issue, and since it's rather minimal, we are going to set it on the back burner for awhile.
