### ISSUE TITLE
Purple Error Blocks in Most Parts of Wynncraft (is it Just my side or is everyones side)

### ISSUE THREAD

**Issue by ArcGaming** [Wynncraft/Issues#8791]
![2017-08-16_17 36 33](https://user-images.githubusercontent.com/31084197/29391174-2e6b9fe2-82aa-11e7-9ec2-f8035845a654.png)

**Comment by thecoolkogut4** [comment]
Join the server on 1.8.9 to fix this issue

**Comment by ittnoraA** [comment]
Are you using forge/other modloaders? Did you download the pack automatically or manually? Which version of minecraft are you using?

**Comment by ArcGaming** [comment]
im on 1.12.1 and my bad i was asleep so i could not get to the pc to message in time 
and no mods and the texturepack was showing up but i dont no so what exactly going on will all i can say is it possibly the texturepack im not sure

**Comment by ArcGaming** [comment]
here what i did 
i booted up minecraft (1.12.1)
then i joined and i accepted the texturepack it asked me for
and when i was in detlas i saw the same thing and then to make sure 
i left deltas to look around but same thing was going on

**Comment by thecoolkogut4** [comment]
What happens when you join on 1.8.9?

**Comment by ArcGaming** [comment]
1.8.9 seem to work fine

**Comment by ArcGaming** [comment]
not sure if i missed it though anything

**Comment by colin350** [comment]
Wynncraft's RP doesn't have 1.12 support. Try playing on lower versions, such as 1.8.9 or 1.9, to fix this issue.

**Comment by ArcGaming** [comment]
okay
