### ISSUE TITLE
i can't download the resourcepack!!!!

### ISSUE THREAD

**Issue by tvermas** [Wynncraft/Issues#8792]
i already tried to clean my resourcepack map in my gamegear map
and i enabled my recourcepack but after the server said 'loading resource pack', he stop downloading at 100%but i didn't got the resource pack. HELP ME!!!!!!

**Comment by colin350** [comment]
Hi, can you comment with your native language so I can ask one of our representatives to help you?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
