### ISSUE TITLE
Wynncraft Excavation Site A Bug

### ISSUE THREAD

**Issue by JustForOneBug** [Wynncraft/Issues#8793]
Hello.

When I go to my quests book that's writting "Go talk to the lab Assistant Tesh in the Tents"
So I've talked to him and he said or maybe she said "Take that to Vade, And don't read him"
I went to Vade and he said "Hmm "Throw tribute an item blablabla" blablabla Be gone you!"
So I found the place, I threw one item and the passage open normaly but when I want to go at this passage that say "A strong force is preventing you entry".

I saw some issue like that so I decided to glitch with my Mage with teleport but when I kill the boss and bring the boss loot I can't escape to the room and I must use some Teleport Scroll for it.
When I talked to Vade after this he said the same dialogue and on my quests book there is always "Go talk to the lab Assistant Tesh in the Tents".

I'm a Mage lvl 60 and I leveling without using quest but now I want to doing quest not started or not finish and I've started Wynncraft Excavation Site A quests long time ago. I doesn't have any souvenirs when I talked at Tesh in the past.
I saw on youtube when you talk at tesh he gives him a paper, I doesn't have this paper and the /fixquests don't do anything ^^

So can you restart me the quest or maybe can you fix me that quest please ? Sorry for my bad english but I'm french.
Goodbye.

**Comment by JustForOneBug** [comment]
My pseudo IG is Zelli

**Comment by PepinhoJp** [comment]
Yes, that paper is bugged, you will have to create a new class to get the paper, I talked to the CT manager (Imaxe), they are aware of the issue, but have no idea how to fix it. This has already been reported. Next time, check for duplicates.

**Comment by JustForOneBug** [comment]
Ok so I will test the quest with one reroll for have the paper and if that's will do same bug I will say in this post.
Thanks.
