### ISSUE TITLE
Creeper Infiltration bug - Cannot enter cave.

### ISSUE THREAD

**Issue by Vehicola** [Wynncraft/Issues#8795]
_Before I get into the bug, I've already done this quest which might be the reason why. I found the Creeper Mask in my bank, but "unidentified", even though when I try to identify it it tells me "I can't identify this item! It can not be reidentified._

Anyways;
When I attempt to enter the cave, this message comes up in chat:
https://image.prntscr.com/image/J6uLhYswSiafFkNkUkSNDg.png

This is what my quest book currently looks like:
https://image.prntscr.com/image/n0deWL5xRTeRTB5qKD0TtQ.png

"Old" Creeper Mask _(Supposedly identified)_:
https://image.prntscr.com/image/6hestgSfSdus-Ja7DQkvVg.png

**Comment by colin350** [comment]
Creeper Infiltration has been redone, that's why you're old mask no longer works. Use: https://wynncraft.gamepedia.com/Creeper_Infiltration as a guide. There's a new variant of the Creeper mask which you need and you must follow the steps in the quest book to get there.
