### ISSUE TITLE
The Hunger of gerts 2 bug

### ISSUE THREAD

**Issue by yousefcraft888** [Wynncraft/Issues#8798]
i was playing with my brother to levelup we said lets finish the hunger of gerts part 2 when we got to the part when you talk to the captured gert it did not work i got near him i tried to get on another server and is still did not work
And i had the mask on 
my brother is in the power place

**Comment by LordHelmchen98** [comment]
If you werent able to finish it yet, try to speak to the gert in many different angles. Its kinda hard to trigger the dialogue.
