### ISSUE TITLE
My skill points are glitched

### ISSUE THREAD

**Issue by lylebean** [Wynncraft/Issues#8800]
i have found a bug on wynncraft that i have asked around and only affects my account, so i am a level 43 warrior, i have 86 skill points, but when i reset my skill points, it uses up 6 or so skill points to start a new skill to level 1, so when i am done putting my skill points in, i have lost 18 points, and then some of the rest of the points go into a random one without me clicking them to that. I dont know how to fix this and i have tried resetting my skillpoints a few times and nothing has worked. my in game name is lylebean, ive tried on different servers and it only seems to be affecting my warrior but that might be because i created it a couple years ago and just now started playing again, i have screenshots that i will try and attach to this post so you can see what i mean.
![2017-08-18_18 38 19](https://user-images.githubusercontent.com/31146044/29481475-343e6fc8-8447-11e7-9874-488370382b45.png)
![2017-08-18_18 38 35](https://user-images.githubusercontent.com/31146044/29481481-3966e50c-8447-11e7-9f90-e7c1eeb310d9.png)
![2017-08-18_18 40 10](https://user-images.githubusercontent.com/31146044/29481487-41967832-8447-11e7-9a13-21b1003ec874.png)
![2017-08-18_18 40 30](https://user-images.githubusercontent.com/31146044/29481488-419749a6-8447-11e7-9431-aa49841df7d4.png)
![2017-08-18_18 41 01](https://user-images.githubusercontent.com/31146044/29481489-419878e4-8447-11e7-9f3a-40272b0abf79.png)
![2017-08-18_18 41 26](https://user-images.githubusercontent.com/31146044/29481486-41944d6e-8447-11e7-95a5-40ebded1d38a.png)

**Comment by Locky1110** [comment]
Are you wearing any equipment that gives negative skill points?
if you are that's the cause.

**Comment by lylebean** [comment]
@Locky1110 i was wearing armor but ive tested it since and it still messes up, like the glitch affects all my skill points, even though my armor doesnt affect all of my skill points.

**Comment by LordHelmchen98** [comment]
If this is still happening please create a new thread in the new [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
