### ISSUE TITLE
Enter the Dojo quest bug.

### ISSUE THREAD

**Issue by CollinHughes** [Wynncraft/Issues#8801]
I was in the second room in the enter the dojo quest and died. it sent me back to the area you start at in wynn. this quest is located in gavel so i was surprised. and i thought you cant get back to the starting area when you start a new game. im not sure if this was a bug but i think it isnt suppose to happen
here is a few images of my level and the location.
![2017-08-18_20 59 46](https://user-images.githubusercontent.com/31147019/29482073-3c6303ec-8458-11e7-952e-02180a246373.png)
![2017-08-18_20 59 27](https://user-images.githubusercontent.com/31147019/29482076-50a981dc-8458-11e7-8aad-20b598f194dc.png)

**Comment by thecoolkogut4** [comment]
Hey there,

This is a very well known bug. When you die off map (during a quest, or for any other reason your outside), you get sent to the closest respawn point, either a town or the starting area. You are just going to have to walk back to where you died. 

Goodluck!
