### ISSUE TITLE
Gear skins + Giant quest

### ISSUE THREAD

**Issue by Markles123** [Wynncraft/Issues#8802]
When you have a gear skin equipped, and you ride a horse, and open your inventory, the gear skin goes away. You have to switch weapons in your hot bar and switch back to your weapon in order to re-apply it. This has worked with multiple skins, across all my classes, across both types of brown horses and my black horse.

When going to the cave and following the candles, the quest never updates, so it keeps repeating "You can smell the blood from here! It is looking dangerous... you had better not go in." This is especially irritating because this happens AFTER the coded door with the guardians outside, meaning once the door is closed behind me (like it is) I'm stuck in the dungeon with no way out. As I was a mage, I teleported past this, and I killed the giant that spawned (no text appeared) and tried to leave, but trying to get close to the black blocks that would have taken me out of the cave gave me the same message, so now I am stuck in the dungeon. 
Help please??

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by Markles123** [comment]
I teleported into the cave to begin with. Turns out I teleported PAST the trip wire that would otherwise update my quest book, that was the source of my problems. In the future please have a certain requirement to check your questbook BEFORE you can go past the guardians, so that way players like me will not end up stuck next to a wall and unable to move forward to exit
