### ISSUE TITLE
Quest lv30 Craftmas Chaos finished item bug

### ISSUE THREAD

**Issue by cvnddy** [Wynncraft/Issues#8803]
in the lvl.30 quest "Craftmas Chaos"
when i finished this quest .I think Santa should take that "quest item Corruption Relic Shard"
but it take away "Untradable item Corruption Relic Shard"
so there is a "quest item Corruption Relic Shard" stuck in my bag 
it is not feel good when you lost 1 space in your bag

**Comment by colin350** [comment]
When you right click your compass, each day, there should be a "daily reward chest" right below the skill points. Open it, place the item you want to remove in there, and close the chest.
