### ISSUE TITLE
Bag , with Fly 

### ISSUE THREAD

**Issue by HxbKopfschmxrzen** [Wynncraft/Issues#8805]
Good day server team,

I have just got a Ban because I Fly ... I'm sure I'm not hacking since I'm playing all the time with my friend "svenatwork" and we have a lot of fun ...
Now on the topic, and I am run wanted to finish the quest and then I was beaten by several zombies and then get up nockback, then I could move and wanted to irgentwie get down and then it happened.
I hope this explanation reciht to you, if not write me gladly!
This text I will similarly similar in Ban report send as it vlt. Very important

I wish you a good day!

With kind regards Joel | HxbKopfschmxrzen...

**Comment by PepinhoJp** [comment]
Please ban appeal on the forums section ban appeals, this GitHub is used for issues in the game, here's the ban appeal forums: 

https://forums.wynncraft.com/forums/ban-appeals.84/
