### ISSUE TITLE
Paintings

### ISSUE THREAD

**Issue by Legomannen** [Wynncraft/Issues#8807]
The paintings seems to have disapered. I noticed in some quests the signs and 2x2 holes, likr there would have been a painting on that spot.

**Comment by PepinhoJp** [comment]
Sometimes paintings disappear in some servers, you can just switch servers and they should appear again, next time please be more specific about where you saw missing paintings, etc...

**Comment by colin350** [comment]
Paintings are really glitchy, and we are aware of the issues with them. Newer quests are trying to avoid the use of them for that reason. 

However, thank you for your report, it's appreciated.
