### ISSUE TITLE
Wynncraft/Lord of the Clock

### ISSUE THREAD

**Issue by sweatytea** [Wynncraft/Issues#8809]
I played wynncraft for a while then totally stopped for about two years. I recently started to play again and I left off on Lord of the Clock. I already progessed to the part where I go to Mount Wynn but I couldn't talk to the NPC there. Then I started the quest over and the other NPCs said the stuff they say when youve already talked to them and after that I went to talk to the NPC at Mount Wynn again but it stills ends up blank when I talk to him! Solution??

**Comment by colin350** [comment]
I seem to not be following your explanation, what does your questbook say?

**Comment by sweatytea** [comment]
This is what my questbook says the quest is started and the instructions are "Destroy the clock in the depths of Mt. Wynn"

**Comment by Pinomo** [comment]
Hey sweatytea ! I'm french, but I had understand your problem. I had the same problem for me there are a few months ! ^^
     
 It's very simple: When you enter the volcano, and you speak to the PNG, you must have a particular Clock.
It is a Quest Item, it's impossible you can't have this Quest Item. So, take your clock (maybe in your chest bank) and go talk to the PNG ^^

See you ^^ :D

**Comment by sweatytea** [comment]
Thank you soo much! Turns out the clock was in my bank and I totally forgot about it when I picked up the quest again! I finally finished it :)
