### ISSUE TITLE
Rank Purchase: Bonus crates and bombs

### ISSUE THREAD

**Issue by CalAnders** [Wynncraft/Issues#8810]
To whom this may concern, 

My username is CalAnders and I've been playing Wynncraft for a long time. Aside my personal affects, I have this issue that I'd like to discuss and I'm not really sure exactly where to do this. 

1 of 2: When I purchased VIP+ before Gavel (Not sure when, positive before Gavel,) it came with 1 XP bomb as usual. But I decided to save this until I truly needed it when I was higher level. But the time came when I was going to use it and I discovered that it was no longer there! I know for a FACT that I did not use it before. 

2 of 2: I purchased VIP+ pre-Gavel like I mentioned already. As the new shop came out with the Gameplay Update, I noticed that ranks come with some Item bombs, XP bombs, and Crates. I never got these items though. Yet I purchased VIP+ already and I think I should be able to claim these rewards somehow. I didn't just pay the price of VIP+ for just the rank, I wanted the XP bomb as well as all the perks in a bundle form. Since I never used any of my bombs and they were removed after some update in Gavel,* I think I should be able to get them back to use them myself again. 

Thanks whoever reads this and hope you can help me in any way!

**Comment by colin350** [comment]
Please email support@wynncraft.com as they handle anything store related.
