### ISSUE TITLE
A boat bug

### ISSUE THREAD

**Issue by JustRoy1** [Wynncraft/Issues#8812]
If i go with the boat from Nemract to Llevigar ,the seaskipper captain only says his first text So we stay in the boat forever and if we do /kill we spawn in the beggining before ragni. and the second time the same thing happend again.
![2017-08-20_13 56 20](https://user-images.githubusercontent.com/31181933/29494714-b7149548-85b0-11e7-8283-cb23929c4692.png)

**Comment by JustRoy1** [comment]
he started talking when i got in another world ,this only happend in wc6

**Comment by TheSeahawkDerp** [comment]
Same happened to me...

**Comment by LordHelmchen98** [comment]
There is a tripwire on the boat, maybe you didn't trigger it. However this is a one time issue and server switching resolves it.
