### ISSUE TITLE
map.wynncraft.com

### ISSUE THREAD

**Issue by CooperGamezz** [Wynncraft/Issues#8814]
There is an issue with map.wynncraft.com, i can't see my friends and my self on it anymore.

Is it a bug or just an bad update?

**Comment by LA1S0N** [comment]
It's a bug. It's happening for me and it has lasted for a while now.

**Comment by LordHelmchen98** [comment]
Sometimes the map doesnt show you on the map. That should always be temporary and during that time just use coords. if you hover over a spot on the map it will show you the coords in the bottom left corner.
