### ISSUE TITLE
Enderchest& Quest item issue

### ISSUE THREAD

**Issue by Mayzees** [Wynncraft/Issues#8816]
I put two stacks of arrows in my ender chest a LONG time ago and its stuck in my ender chest now... Also i had a full inventory and accidentally threw out a quest item and I can't get it back now... Sorry for the inconvenience!

**Comment by thecoolkogut4** [comment]
Please message Pretzule on the forums to remove the arrows.

Type /fixquests to get your item back.

**Comment by LordHelmchen98** [comment]
RESOLVED
