### ISSUE TITLE
Stuck in mission Grave mistake

### ISSUE THREAD

**Issue by thelouisnator2** [Wynncraft/Issues#8817]
After the deigned tour they give you in a Grave mistake  about the kings life i found myself in an invisible box not being able to go on to the next part. I have no scrolls on me to escape and have no way to die so i am stuck in this box.  My IGN is the_louisnator2 on my archer class which is  lvl 54. (P.S. i did find another post about this but there was nothing after the initial report it was just resolved.)

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by thelouisnator2** [comment]
thank you
