### ISSUE TITLE
Not received the rank

### ISSUE THREAD

**Issue by Vincent008** [Wynncraft/Issues#8819]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.
I bought vip and I did not receive the rank after 10 minutes I can send proof of purchase
I delete the link as proof
my name in game is Vincent008

**Comment by thecoolkogut4** [comment]
I recommend you take down those pictures from GitHub, then email support@wynncraft.com with them and your issue. They handle all store related issues.
