### ISSUE TITLE
Twain Journal quest? 

### ISSUE THREAD

**Issue by shadedNight0905** [Wynncraft/Issues#8820]
Umm.... correct me if I'm wrong here, but to open the door to the fireplace in the Twain Mansion is to drop emeralds into the both eyes of the monster of the carpet, am I right? But I can't seem to be able to drop an emerald into the left eye, but I can drop in an emerald in the right eye. Am I doing something wrong with the quest?

**Comment by ittnoraA** [comment]
Swap the world you're on, and it should work. If not, just swap again.

**Comment by shadedNight0905** [comment]
oh. ok. i'll try that. thanks

**Comment by LordHelmchen98** [comment]
RESOLVED
