### ISSUE TITLE
Grave Digger quest

### ISSUE THREAD

**Issue by SleepyRoxas** [Wynncraft/Issues#8822]
Hello,

So I'm experiencing the following issues since a few days now, I'm trying to complete the Grave DIgger quest, and unfortunately, I can't. Everything goes fine until the last stage, where I have to defeat Sayleros's Brother boss. I can defeat it, but he doesn't drop the Dusty Will. I tried to kill him several times, with different weapons. I also tried to change of server, but nothing. It really doesn't want. I also tried to do the /fixquests and it didn't help either.. Hopefully you can help me out with this

**Comment by thecoolkogut4** [comment]
Kill him until he completely dies. When you kill him he should autorespawn. Kill him till he doesn't respawn right away and it should drop something.

**Comment by ittnoraA** [comment]
To be exact, the boss has several forms (9?). When you "kill" one, the one he transforms into is a small bit weaker than the previous form. To indicate this, the mob loses a part of it's body upon "dying". Beat all phases, and you should receive the drop.

**Comment by LordHelmchen98** [comment]
RESOLVED
