### ISSUE TITLE
Rank is gone?

### ISSUE THREAD

**Issue by floydnick** [Wynncraft/Issues#8823]
So i bought my rank when the VIP town was still a thing i quit for around a year and now my rank is gone and i'm just a vet. I'm just wondering why I don't have vip still i payed money for it and expect to still have it.

**Comment by thecoolkogut4** [comment]
Type /toggle get to get your vip tag back. Your still vip but just have a different tag for buying the rank before the EULA update.

**Comment by floydnick** [comment]
thank you.
