### ISSUE TITLE
Green Skinned Trouble Bugged! Cannot complete

### ISSUE THREAD

**Issue by SentinelCow** [Wynncraft/Issues#8824]
So, I think there is a bug in this quest.
When you must enter the lake, you have a test. (Move with the light)

After "moving", I can't fall in the hole. It's say:

"null"
"null"
"null"
...

**Comment by ittnoraA** [comment]
Swap the server you're on, and it ahould automatically be fixed. If not, swap again until it's working properly.

**Comment by LordHelmchen98** [comment]
RESOLVED
