### ISSUE TITLE
I can't post pictures in my shop

### ISSUE THREAD

**Issue by yousefcraft888** [Wynncraft/Issues#8825]
I can't post pics in my shop I want to show people what's the enchantment of the stuff

**Comment by ittnoraA** [comment]
Do you have 10 posts yet?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
