### ISSUE TITLE
My brothers le got scammed by the merchant

### ISSUE THREAD

**Issue by yousefcraft888** [Wynncraft/Issues#8829]
my brother want to exchange his le to eb he lost it he had 16 le now he has 6 only why

**Comment by PepinhoJp** [comment]
Sorry about the bug, but Wynncraft has a strict no-refund policy, they can't give you items that you lost back.

16. Refunds Policy
(We cannot refund items that are acquired in-game, no matter how they are lost. For any problems with items that are purchased through our store, please contact us at support@wynncraft.com.)
