### ISSUE TITLE
I lost my Yahya's bowl.

### ISSUE THREAD

**Issue by 6ed** [Wynncraft/Issues#8830]
I was going to the Skeleton Dungeon, but I got a Loot Chest so i emptied my inventory. I threw out my Yahya's Bowl somehow by just pressing q in my inventory alot. I thought it was glitching because it wasnt going out. I didn't know that I needed that item for another quest, because the messages in chat were blocked by the inventory.

**Comment by thecoolkogut4** [comment]
Type /fixquests to get your item back.

**Comment by Exoltic** [comment]
As the person above said, /fixquests should work.

**Comment by 6ed** [comment]
oh thanks!
