### ISSUE TITLE
Envoy part 2 isnt working

### ISSUE THREAD

**Issue by Cityfanart** [Wynncraft/Issues#8832]
I'm on the part where I "Retrieve the key from the base. " and every time I go through the underground thing .Maxie's Dialogue and him do not appeare and I don't know  what to do . I try switching the lobbies and redo the underground thing but it seems to not work.

**Comment by Cityfanart** [comment]
https://gyazo.com/80524218d5956b9b9509cef8bee4cf10
https://gyazo.com/4060fa9276bc1e013097360e93338c76

**Comment by Mammothh** [comment]
that happened to me on pt 1 i'm just stuck at stop the mechs from taking over the diner and there is no one to talk to and when i leave the diner maxi appears for like a second then just disappears with no dialogue

**Comment by LordHelmchen98** [comment]
I did it a few days ago and it worked perfectly fine. Were you able to fix it?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
