### ISSUE TITLE
Ice barrows out of map when server reset

### ISSUE THREAD

**Issue by RedBugOne** [Wynncraft/Issues#8833]
I was in the ice barrows when i changed servers i found myself on top of the dungeon( ? ) Anyway i was on the parkour part. I left on the 5th jump ( ? ) ( it was to the right )  and that was how i found myself outside of the map.

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by LordHelmchen98** [comment]
Sometimes there are some issues if there were blocks right above you when you logged out.
However as already said `/kill` will get you to the closest town if you got stuck anywhere.
