### ISSUE TITLE
Tower of Ascension quest bug!

### ISSUE THREAD

**Issue by Hakairyu** [Wynncraft/Issues#8834]
In my quest book i see the quest named as ''Tower of Ascension'' but i checked it on wiki and its a outdated quest still i dont know how can i take it out of my quest book cause its stuck as started quest!!

**Comment by ittnoraA** [comment]
Have you completed the quest?

**Comment by Hakairyu** [comment]
@ittnoraA no i didnt it just stuck in my quest book. i was going to do the quest but its removed so i dont know what to do with it :/

**Comment by ittnoraA** [comment]
The quest isn't removed, and you can still complete it.
