### ISSUE TITLE
My weapon is unusable

### ISSUE THREAD

**Issue by Mabala64** [Wynncraft/Issues#8835]
I bought a legendary warrior weapon called Fierté. Somehow this happened:
![wcaso](https://user-images.githubusercontent.com/31339824/29705566-ee4f3276-897e-11e7-8247-97fdeb228ed8.png)

**Comment by PepinhoJp** [comment]
Try doing /class and then coming back, if that doesn't work, try re-idying, if you can't re-id it, unfortunately it's bugged and useless...

**Comment by Mabala64** [comment]
Thanks for helping, but unfortunately it doesn't work :(

**Comment by LordHelmchen98** [comment]
I dont think there is any way to fix it and due to Wynncrafts norefund policy you wont get another one either.
You will have to look for a new weapon if you didnt already.
