### ISSUE TITLE
Please help me at meaningful holiday!

### ISSUE THREAD

**Issue by tenndonn** [Wynncraft/Issues#8836]
When I heard Nick's talk, server has restarted.
and I can't get out from here and can't use tp scroll now.
what can I do?
http://imgur.com/a/tJGnQ
http://imgur.com/IhRSh9K

**Comment by tenndonn** [comment]
I could get out by use /kill.
but I can't continue quest.

**Comment by tenndonn** [comment]
I could continue the quest!

**Comment by LordHelmchen98** [comment]
RESOLVED
