### ISSUE TITLE
Bed block glitch stuck HELP!!!

### ISSUE THREAD

**Issue by SpeederSam** [Wynncraft/Issues#8838]
So... I cant make this up. I found the secret area near the almuj dungeon and was exploring it. I somehow managed to get into the beds and ended up getting myself...stuck in a block. I had a friend bring me a teleportation scroll but it still wont work. PLEASE HELP IM STUCK WITH MY HIGHEST LEVEL ACCOUNT.

**Comment by SpeederSam** [comment]
Used /kill to get out...still look into it please.

**Comment by Slime1480** [comment]
Can you put a screenshot? It could helpm

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
