### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by vanadous** [Wynncraft/Issues#8839]
I am stuck in a black wool box and I can barely see anything. No spell I cast is helping me and I want to go back to regular gameplay. I used to play awhile ago and I want to play it again with friends. Please tell me how to get out

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by vanadous** [comment]
THANK YOU!!!!

**Comment by thecoolkogut4** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft!
