### ISSUE TITLE
/suicide in the nether

### ISSUE THREAD

**Issue by thecoolkogut4** [Wynncraft/Issues#8840]
When you are in the nether, if you type /suicide you get an error message of 
![image](https://user-images.githubusercontent.com/8689385/29738234-f5f1e254-89eb-11e7-912a-fca77c209f1b.png). Last time I checked you don't spell suicide like that... If you type /sucicide it says unknown command.

**Comment by ittnoraA** [comment]
This is a widely known bug, and also happens on main worlds.
