### ISSUE TITLE
T1 Crate Gone

### ISSUE THREAD

**Issue by iiQr** [Wynncraft/Issues#8841]
Right after I placed a T1 Crate, I got lagged and kicked when I re-logged, the crate was gone. Did I open the crate without me knowing it or did I lost the crate?

**Comment by Mammothh** [comment]
check your items?

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
