### ISSUE TITLE
Spell Combination Bug

### ISSUE THREAD

**Issue by iThinksUpDown** [Wynncraft/Issues#8842]
When I use a spell eg Right-Left-Right during a fight the next combination I try to do glitches out and registers me pressing Right-Right when I right click once. I can assure that I am not right clicking twice, I've tested this with my friend.

**Comment by ittnoraA** [comment]
This is a known bug, and only happens in versions 1.9-1.12. Every time you click on an entity/block, your client sends the server a packet for right clicking twice. If you want to prevent this from happening, you should play with any 1.8 version of minecraft.

**Comment by iThinksUpDown** [comment]
Sorry I couldn't find anything on it anywhere, maybe my search parameters need to change, this fixed my issue thank you.
