### ISSUE TITLE
I found your redstone wynn.

### ISSUE THREAD

**Issue by Alisadic** [Wynncraft/Issues#8843]
https://gyazo.com/ea0df3234a69be0b57af62429c0922df

I found this glitch i go on my horse on a corner of the house and i go of him and boom i am at the redstone this is at the lost soles quests

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by Alisadic** [comment]
I know

**Comment by Alisadic** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7997640-338040558_2-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by LordHelmchen98** [comment]
Its a well known glitch. I hope that will be fixed as soon as they phase out 1.8.
