### ISSUE TITLE
Bug in a quest

### ISSUE THREAD

**Issue by nicozoro56** [Wynncraft/Issues#8844]
Hi! i'm nicozoro56 and a just let this message to any moderator or anyone who can help me.
I'm actually stuck in the quest "Out of mind" because i solve the puzzle from Ariodo in a different way by placing the fan on 10-B
The cannon on 9-B
The another canon on 6-B
The car on 2-D
The Hammer on 8-B
Actually some good people help me out but other person can be block like me so i type this to notice you about the glitch (i think it's a car problem that doesn't really fit the "coconut") :p good luck
Dear friend 
nicozoro56

**Comment by Exoltic** [comment]
Im pretty sure if you do it the way Wynncraft intended after resetting the game it will work

**Comment by LordHelmchen98** [comment]
The button you click to start it should reset the puzzle if you click it again. Then you can redo it in a different way.
