### ISSUE TITLE
Creeper

### ISSUE THREAD

**Issue by Diio9oF** [Wynncraft/Issues#8845]
I got the quest Crepper Infiltration and when I go to get the crepper skin to give to Thomas I can't pick up skin, I tried to contacts helpers or somethins in the server but I didnt foud one, I really need help here, thank you
![sem titulo](https://user-images.githubusercontent.com/31379499/29746892-e8f139c4-8ae0-11e7-9925-c38b6a752497.png)

**Comment by thecoolkogut4** [comment]
The skin is a mob, attack it like a normal mob to pick it up.
