### ISSUE TITLE
Stuck at quest

### ISSUE THREAD

**Issue by Nesus** [Wynncraft/Issues#8846]
So I dont know if there is a format, if there is then I wont use it because it isnt nessasary. Anyways i was doing the halloween quest and i was at the end of the cutscene when it didnt teleport me out. I am stuck in a church like structure with a red carpet. I have been stuck here for 30 mins and i would like an admin to teleport me out and well put in a command where i can finish that quest. Here are some images of my location

http://imgur.com/a/VZx9T
and
http://imgur.com/a/pCsoZ

**Comment by Alisadic** [comment]
just do /kill

**Comment by LordHelmchen98** [comment]
I guess you got stuck in one of the cutscenes, right? As already said `/kill` is the command you need in case you are stuck. If you didnt finish the quest yet just try to repeat the respective stage of the quest.
