### ISSUE TITLE
Corrupted Infested Pit Boss Problem

### ISSUE THREAD

**Issue by RLLL93** [Wynncraft/Issues#8848]
So, I was doing the Corrupted infested pit dung. and when I killed the boss I wasn't telleported and another one spawned, who killed me.
I think you shoud try to repair that

**Comment by ittnoraA** [comment]
Dungeons don't count it as completion, if the final hit to it's boss is dealt by another mob, fire or specific spells. Keep this in mind the next time you're in a dungeon.

**Comment by LordHelmchen98** [comment]
Thats actually wrong @ittnoraA, if the boss burns to death it still counts as completed and you get tped out.
I think the rest is correct though.
