### ISSUE TITLE
Envoy pt 1

### ISSUE THREAD

**Issue by Mammothh** [Wynncraft/Issues#8852]
The quest is glitched with my quest book saying "stop the mechs from taking over the diner" and I cant talk to the mech because he inst there and when i leave maxi appears for a second and then disappears, not sure what to do.

**Comment by Exoltic** [comment]
Try relogging or switching servers. Kill the mechs inside the diner after you got there by going into the vents. Maxi should be there with blood around her, and she will open some fences so you can talk to the mech standing on top of the crates.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
