### ISSUE TITLE
I threw away my bow

### ISSUE THREAD

**Issue by XxTim55xX** [Wynncraft/Issues#8853]
I lost my legendary bow its some nesharaf? bow something with water circling around the bow as the design  i am currently in almuji and i went to the dungeon with my friend and while we were fighting in the dungeon i accidently pressed q and threw my legendary bow with spell damage 32% and 3/4 mana regen into the hopper in one of the dungeons
My Mc name is TheModeratorMC

**Comment by Exoltic** [comment]
Unfortunately Wynncraft has a no refund policy. If you dropped it then it should have still been on the ground, and it was you who dropped it, not a glitch in the game, even if it was by accident.

**Comment by XxTim55xX** [comment]
i dropped it the hopper

**Comment by thecoolkogut4** [comment]
Dropping it in a hopper, lava, into the void it's all the same thing. You pressed the drop key and there is nothing we can do about that.

**Comment by LordHelmchen98** [comment]
Due to the already mentioned norefund policy you wont get your bow back. Sorry.
