### ISSUE TITLE
Bug inside blocks

### ISSUE THREAD

**Issue by GeorgioMC** [Wynncraft/Issues#8855]
I was trying to find the Gundalf`s library, but i never see that.

I try to teleport in a small block and them... im here.

![2017-08-28_20 02 47](https://user-images.githubusercontent.com/12486493/29800795-f39c7384-8c39-11e7-9bf6-e280c5f1a8c4.png)

**Comment by LordHelmchen98** [comment]
As Slime1480 already said `/kill` will get you out. Be careful though, it will be like a normal death and if you have too low soul points there is a chance you drop important items. Therefore better not use `/kill` to get out of somewhere if you have 5 or less soul points.
