### ISSUE TITLE
Locked item

### ISSUE THREAD

**Issue by xRayne93** [Wynncraft/Issues#8856]
I have an issue with a locked item, and I am not sure if it has to do with the Wynncraft addon and I clicked something I should not have, or if this is a bug and it's stuck there, unable to be moved/tossed/sold. http://i.imgur.com/cWXHZlg.jpg

However, when I am accessing my bank chest, I am able to move the 'locked' item about or even store it away. http://i.imgur.com/io57ST7.jpg

This was only a junk item used as an example, but I am unable to do anything with weapons/armor/etc when they are in the single spot. This only seems to be happening in that single spot on the top row.

**Comment by ittnoraA** [comment]
This github page is dedicated to issues about the game, and only those. Please post any issues about the unofficial modpacks on their original forum threads.

**Comment by LordHelmchen98** [comment]
The original forum thread can be found [here](https://forums.wynncraft.com/threads/unofficial-custom-modpack-%E2%9D%80-wynncraft-enhanced-%E2%9D%80-party-hp-display-custom-worldmap-more.139677/) in case you weren't able to find it yet.
