### ISSUE TITLE
Bug skeletton dungeon 

### ISSUE THREAD

**Issue by Calican** [Wynncraft/Issues#8857]
can't move in skeletton dungeon, for three hours, invisible blocks at : You continue to trespass on my territory ? You must have no value for your life.

**Comment by Slime1480** [comment]
Can you put a screenshot? It could help.

**Comment by Calican** [comment]
And I can't tp because this messages : sorry you can't teleport... Try moving aways from blocks. 

There is no blocks...

**Comment by Calican** [comment]
![2017-08-29_12 46 05](https://user-images.githubusercontent.com/31438280/29817536-a74c7608-8cb8-11e7-9d89-7937ad254725.png)

**Comment by Calican** [comment]
hm it's good

**Comment by Calican** [comment]
But if I want to restart the dungeon, the bug remains

**Comment by Slime1480** [comment]
Probably is a dungeon bug, try to ask a mod.
If the bug continue stop going through, is a waste of money.

**Comment by Calican** [comment]
Or can I contact a moderator?
