### ISSUE TITLE
Bug skeletton dungeon

### ISSUE THREAD

**Issue by Calican** [Wynncraft/Issues#8858]
can't move in skeletton dungeon, for three hours, invisible blocks at : You continue to trespass on my territory ? You must have no value for your life.

And I can't tp because this messages : sorry you can't teleport... Try moving aways from blocks.

There is no blocks...

**Comment by Calican** [comment]
with all classes my archer my mage .....

**Comment by ittnoraA** [comment]
This happens because the system is creating client side ghost blocks on versions 1.9-1.12. To fix the problem and continue properly, swap onto a 1.8 version of minecraft.

**Comment by Calican** [comment]
ok thanks

**Comment by LordHelmchen98** [comment]
RESOLVED
