### ISSUE TITLE
my texture pack wont dowload

### ISSUE THREAD

**Issue by andystar22** [Wynncraft/Issues#8860]
i tried eerything its enbaled but when it loads nothing changes HELP

**Comment by thecoolkogut4** [comment]
https://github.com/Wynncraft/Issues/blob/master/RP%20DOWNLOAD%20INSTRUCTIONS.md

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
