### ISSUE TITLE
My Friend is Stuck

### ISSUE THREAD

**Issue by KingOfMelonz** [Wynncraft/Issues#8863]
So my friend (Being a mage) teleported around and somehow made it inside a small panel of nether portal blocks. The entire area has nether portal blocks so /kill isnt an option. He also cant open his inventory to get a teleportation scroll a TP out. Trying to use reverse teleportation doesn't work either and only results in "You can't teleport, try moving away from blocks." We have tried everything for nearly an hour now. I don't think there is any other way to get help unless an admin gets involved.

IGN: BobsLostSoul

**Comment by oOfamieOo** [comment]
my friend he is  stuck in the block 3 days plz help him you can /kill him plz in game his name is queenkavador
