### ISSUE TITLE
Horse Cloak Glitch

### ISSUE THREAD

**Issue by boomerzap** [Wynncraft/Issues#8864]
If you have a horse cloak such as the Zombie Horse Cloak equipped when you trade it up for an Epic Reward, your horse stays cloaked as a Zombie / Skeleton, even though you do not have the cloak any longer. You also cannot turn it off, as there is no option to in the pets menu.

**Comment by LordHelmchen98** [comment]
This is known and will hopefully get fixed in future. For now you will have to deal with it until you get a new horse skin.
