### ISSUE TITLE
corrupted sand swept tomb

### ISSUE THREAD

**Issue by LodHic3** [Wynncraft/Issues#8866]
I was doing a CSST party with lots of people  and when we went into the dungeon we got stuck in the cube you are supposed to get teleported away from. So i saw i hole in the roof and jumped up (i played archer). Outside i got to a flat world around the dungeon and i saw some stuff they had built. PLease place a block in the hole of the teleporting cube.

**Comment by ittnoraA** [comment]
Heyo! If you have 5 or more soul points, you should do `/kill` as soon as possible. Exploring the outside world any further will result in a ban.

**Comment by LordHelmchen98** [comment]
This is known and should be fixed soon.
