### ISSUE TITLE
stuck in a block

### ISSUE THREAD

**Issue by Manfartnugget** [Wynncraft/Issues#8868]
when going to the secret library I stepped on the pressure plate went through the passage a bit maybe I don't know what I was supposed to do but i got stuck between the piston and block and when I went to the lobby my screen was just black. I don't have any teleport scrolls on me so I guess the only way to get out is to get a friend to /trade me a scroll but that could take a while and will be a problem for some ppl and will get stuck forever

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by Manfartnugget** [comment]
I will try to respond to comments if you are trying to help

**Comment by Manfartnugget** [comment]
thank you

**Comment by Manfartnugget** [comment]
how do I get rid of this

**Comment by Manfartnugget** [comment]
Thanks and btw I just had to go to the lobby and back many times
