### ISSUE TITLE
Skeleton horse bug

### ISSUE THREAD

**Issue by LiquidDec** [Wynncraft/Issues#8870]
Very often if you use a Skeleton Horse Cloak and spawn a horse it will be a regular horse.

Video:
https://youtu.be/QdP9UocsAd0

**Comment by ittnoraA** [comment]
This is nothing more than a visual bug on your client, that happens on versions 1.9-1.12. If it does annoy you too much, you can always swap onto 1.8!

**Comment by LordHelmchen98** [comment]
RESOLVED
