### ISSUE TITLE
Lvl 70 Adamantite Chestplate Stats Incorrect

### ISSUE THREAD

**Issue by Orowaxx** [Wynncraft/Issues#8872]
I started using Adamantite today and I was very confused because it takes away much more elemental defense than it should.

**Adamantite Stats**
![unbenannt1](https://user-images.githubusercontent.com/31553703/29990137-2987e5c8-8f78-11e7-971c-ad5c41ca8666.PNG)

**My defense before equipping Adamantite**
![unbenannt](https://user-images.githubusercontent.com/31553703/29990166-5a83d68c-8f78-11e7-87ba-b0746522cc26.PNG)

**My defense after equipping Adamantite**
![unbenannt2](https://user-images.githubusercontent.com/31553703/29990178-7f995460-8f78-11e7-811e-892ffd112c76.PNG)

**Comment by thecoolkogut4** [comment]
The defenses in the compass are completely screwed up, don't trust it. You just have to calculate your defenses manually. This is a well known issue by the staff.

**Comment by Orowaxx** [comment]
Oh ok thanks for answering that quick 👍

**Comment by thecoolkogut4** [comment]
Your welcome! If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft!
