### ISSUE TITLE
Glitched In Grave Mansion Final Teleport.

### ISSUE THREAD

**Issue by GrimIsHere** [Wynncraft/Issues#8873]
https://gyazo.com/88777cc26f59af642c9e2e9e04dfe497
Stuck here, please help!

**Comment by ittnoraA** [comment]
Heyo! Since you have over 5 soul points, you can do `/kill` to respawn in the nearest city you've visited before.

**Comment by Slime1480** [comment]
Heyo! (Not coping Aroneti) This is because of your ping, it happened to me, i recommend trying the cinematic a better day.
Btw, it costed me like 20 Soul Points for completing the cinematic.

**Comment by LordHelmchen98** [comment]
I you were not able to complete the quest yet, get to the point right before you get teleported to all those cinematics, then go to the lobby and search for a server that just restarted as those should have least lag.
