### ISSUE TITLE
Guilds?

### ISSUE THREAD

**Issue by Markles123** [Wynncraft/Issues#8874]
I got kicked from a guild by an emotional chief, and the guild owner tried inviting me back but it says "this player is already in a guild" even though I'm not in one??? Please help????

Screenshot showing I cannot be invited: https://cdn.discordapp.com/attachments/353375758485553154/353377432318902273/image.png

![screenshot 16](https://user-images.githubusercontent.com/22185367/29992721-51cdf3b8-8f57-11e7-92aa-613d91cf125b.png)

**Comment by thecoolkogut4** [comment]
Try switching servers

**Comment by Markles123** [comment]
@thecoolkogut4 Already tried that, multiple times

**Comment by thecoolkogut4** [comment]
Then your most likely screwed. There's nothing you can do and they are currently reworking guilds. The only thing left to do is wait.

**Comment by Markles123** [comment]
@thecoolkogut4 Asdjakjdkjakaksdbkjawkjv jas thanks anyways though
