### ISSUE TITLE
I need assistance for Lord of the clock quest

### ISSUE THREAD

**Issue by creeperface0507** [Wynncraft/Issues#8875]

**Comment by ittnoraA** [comment]
Ya know, it's kinda hard to assist someone if they give no description about what they need help with.

**Comment by Slime1480** [comment]
If the problem is that you don't What to do, type in your browser "Wynncraft Lord of the clock wikipedia" it should give you all the information, but please, put more information.

**Comment by LordHelmchen98** [comment]
As you didnt prvide any information its impossible to help. If you are stil facing an issue with this quest please create a new issue and describe your problem.
