### ISSUE TITLE
Head "bug" in Gundalf´s Library in the quest "Lord of the Clock"

### ISSUE THREAD

**Issue by Equipa2** [Wynncraft/Issues#8876]
I was doing the Lord of the Clock quest and I saw that the heads are not books.
![2017-09-02_14 40 04](https://user-images.githubusercontent.com/16447942/29995954-15da5d38-8fed-11e7-859c-6721dc2f48e9.png)

**Comment by IShallNot** [comment]
It's not much of an issue just ignore it

**Comment by LordHelmchen98** [comment]
Although I thought it might be a one time issue, it really seems to be broken. However its being worked on and will soon be fixed.
