### ISSUE TITLE
Stuck outside of Out of my mind quest

### ISSUE THREAD

**Issue by Ethananous** [Wynncraft/Issues#8878]
Today I was playing the Out of my mind quest, and the scientist told me to go through the big door. I didn't know where to look, and the door ended up closing on me. I looked on the forums to see if anyone had a solution for this, and someone said to do /kill, to go back to the area and redo the puzzle. The problem is when I went back to the lab the door wouldn't teleport me to the puzzle room. Any way to fix this?

**Comment by thecoolkogut4** [comment]
What happens when you switch servers?

**Comment by Ethananous** [comment]
I was back where I had spawned when I did /kill.. but I think the issue might've sorted itself out now. The door teleported me once I walked out of it for some reason.
