### ISSUE TITLE
"The Lost" quest broke.

### ISSUE THREAD

**Issue by MadAcer** [Wynncraft/Issues#8879]
In the begining of the you get 5 letters which you have deliever to all 5 members of Dejou. After that, when I arrived at the first person I saw a legendary item dropped after slaying a mob. At that time my inventory was full and I was so desperate on picking it up. So I did and accidentally dropped one of the letter in the quest. After finding the rest of the member. I realized I couldn't finish the quest because I was missing a letter which I was suppose to deliever to a member. So I decided to do /fixquests. But nothing happened.

**Comment by Exoltic** [comment]
"The Lost" quest is broken for me too, even though I gave Dejol all the letters. Best of luck

**Comment by MadAcer** [comment]
Welp, rip quest.

**Comment by HexerTPB** [comment]
that also happened to me on another quest!

**Comment by LordHelmchen98** [comment]
Duplicate of #6032 
Sorry but I dont think there is any solution currently, although this has been an issue for quite a long time now.
