### ISSUE TITLE
powder relic

### ISSUE THREAD

**Issue by axelochvilhelm** [Wynncraft/Issues#8880]
The relic at -2159 -4293 when you claim it it says, "You have broken the water powder IV relic seal," but you get a water powder III instead.

**Comment by ittnoraA** [comment]
Going to a higher level relic increases your chances of receiving a better powder, but doesn't guarantee it. For example, you might go to a tier 6 relic and only gain a tier 1 powder out of it; It's purely luck based.

**Comment by axelochvilhelm** [comment]
but I have gotten it every single time I go there.
Even with my brother's account where he is like lvl 86

**Comment by ittnoraA** [comment]
Please read what I said carefully. The powder you'll get out of relics is completely random, which means getting only tier 3 powders is merely a coincidence. It doesn't matter how high leveled your class is, the chances will still remain the exact same.

**Comment by LordHelmchen98** [comment]
As already said its a chance to get the different tier powders. The higher the tier of the relic is the higher the powder (highest you can get is a tier 4 powder from a tier 6 relic though if I remember correctly).
