### ISSUE TITLE
Shatter Minds Quest broken??

### ISSUE THREAD

**Issue by GhostlyDeah240** [Wynncraft/Issues#8882]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

**Comment by GhostlyDeah240** [comment]
So I died in the part that looked like we were taking drugs and I fell to my death and died. So I re-spawned in the very beginning. Also for another quests Wynncraft Excavation site D I died and re-spawned in Olux witch is on the other side of the map

**Comment by Villageacules** [comment]
Please use the new bug report section on the forums! https://forums.wynncraft.com/forums/bug-reports.108/
