### ISSUE TITLE
WynnExcavation Site B

### ISSUE THREAD

**Issue by LinksReturn** [Wynncraft/Issues#8883]
I started the quest and the server restarted, so i no longer have the shard but the quest says "Status: Started" so i know I gave it to him. 
![2017-09-03_14 06 29](https://user-images.githubusercontent.com/31597153/30005864-73c1d77c-90b1-11e7-8293-016a8632aaee.png)

**Comment by ittnoraA** [comment]
To retrieve the lost shard, you should try doing `/fixquests`. If that doesn't work, you can return to Wynnexcavation site A and claim another one from it's boss.
