### ISSUE TITLE
The item "Clearsight Spectacles" is NOT a quest item! If deleted, it cannot be retrieved.

### ISSUE THREAD

**Issue by Veryangrybird66** [Wynncraft/Issues#8885]
I have seen this issue adressed before, however the problem is still not fixed. If the clearsight spectacles are accidentally deleted, then it is impossible to get them back. In my case. a bug happened when I was moving around items in my inventory and it got deleted. This item should be a quest item, however it is not. PLEASE HELP. Edit: Without this item, the quest "The realm of light" is impossible to complete.

**Comment by Villageacules** [comment]
Please use the new bug report section on the forums! https://forums.wynncraft.com/forums/bug-reports.108/
