### ISSUE TITLE
blocked

### ISSUE THREAD

**Issue by F4PLRUDA** [Wynncraft/Issues#8889]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.
Sorry i'm french,
I have a bad level in English.
Screen : https://image.noelshack.com/fichiers/2017/36/1/1504541906-2017-09-04-18-17-14.png
https://image.noelshack.com/fichiers/2017/36/1/1504541905-2017-09-04-18-17-26.png
https://image.noelshack.com/fichiers/2017/36/1/1504541906-2017-09-04-18-17-32.png
I have not even played, please help me !

**Comment by ittnoraA** [comment]
There's a button on the wall. How about you give it a push?

**Comment by F4PLRUDA** [comment]
nothing happens :(

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
