### ISSUE TITLE
Frankenstein Weapon Skin Bug

### ISSUE THREAD

**Issue by GoodNerms** [Wynncraft/Issues#8890]
This weapon can be found in the Nemeract weapon shop. The skin seems to be bugged, even tried re-logging.

![2017-09-04_09 42 15](https://user-images.githubusercontent.com/31628336/30034308-5d9ddeba-9155-11e7-92a2-8e41b771bfd5.png)

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
