### ISSUE TITLE
Skill Points

### ISSUE THREAD

**Issue by affrettando** [Wynncraft/Issues#8891]
My skill points (after being reset) won't go down to 0, some of them will be at 5 or 6 but still say I have 130 points, which would make them all 0. Then, after I set skill points some will randomly change from, say 30, to 47 or 40 to 26. This is very frustrating as I can't equip all of my gear because I can't balance my points evenly.

**Comment by ittnoraA** [comment]
Does your armor or accessories have positive/negative skill point stats?

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
