### ISSUE TITLE
I'm stuck on "A Grave Mistake" quest

### ISSUE THREAD

**Issue by ShoeDqddy** [Wynncraft/Issues#8893]
On the "A Grave Mistake" quest when you are teleported to the front so Twain can talk to you I'm glitched above the mansion and can't tp away or anything

ShoeDqddy_

**Comment by ittnoraA** [comment]
Heyo! If you have 5 or more soul points, you can do `/kill` to respawn in the nearest city to you.

**Comment by HexerTPB** [comment]
that seems like a grave mistake :3
