### ISSUE TITLE
Excavation Site D Final boss

### ISSUE THREAD

**Issue by Crazyisback** [Wynncraft/Issues#8895]
I am an archer class and i am stuck on fighting the Final Amadel boss (wither) my attacks will not damage him and i am stuck in the room. I do not want to die and do the entire 3 stage boss fight again.

**Comment by ittnoraA** [comment]
The quest boss isn't supposed to be beaten alone. Of course, you can solo him, but you'd better grab a couple of friends for help with the fight. 

Oh, and even if you die, you won't need to beat the previous phases again to get back to the third form.

**Comment by Crazyisback** [comment]
Thanks 😄  now imma need someone to come with me.
