### ISSUE TITLE
My Stats on Wynncraft.com

### ISSUE THREAD

**Issue by b3nnii** [Wynncraft/Issues#8898]
Hello I'm waiting for weeks now that my stats from my old MC name is moved to my new MC name!

Nothing has been done yet!

My old mc name was CookiesOfficial
and my new mc name is b3nnii

please fix the best possible

**Comment by b3nnii** [comment]
im getting pissed

**Comment by RubbrDucky** [comment]
It takes a while to carry over, it took 2 months for me. Just be patient.

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
