### ISSUE TITLE
Glitch with cannons in Galleon's Graveyard

### ISSUE THREAD

**Issue by Feltac** [Wynncraft/Issues#8900]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

**Comment by Feltac** [comment]
[https://prnt.sc/gi3kmx](url)

**Comment by Feltac** [comment]
https://prnt.sc/gi3kmx

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
