### ISSUE TITLE
Beast and bound bugged

### ISSUE THREAD

**Issue by xXM1g420Y0lO5wAG8laze1tN05c0p3Xx** [Wynncraft/Issues#8901]
I was fighting the beast boss with my archer and there was a point when thy were both in a corner. I don't know what happened as i didn't notice at first but the bound somehow got pushed into the wall and i couldn't kill it.

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
