### ISSUE TITLE
Bug in hole pls help me 

### ISSUE THREAD

**Issue by BastianPro** [Wynncraft/Issues#8902]
# i teleport in mini hole and i am trapped pls help me admin M name is BastianPro In minecraft Pls teleport me in ragani or out of the hole

**Comment by thecoolkogut4** [comment]
Hey there,

Do /kill if you have more than 5 soul points in order to get out. You will respawn in the closest town.

Goodluck!

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
