### ISSUE TITLE
Taproot quest bugged after over a year

### ISSUE THREAD

**Issue by Akamito** [Wynncraft/Issues#8903]
A year ago, I was unable to beat the quest on stage 14 because the parkour was glitchy and was forced to /kill because I was stuck. I was unable to do the stage 14 "Speak to Tiek." Now, I am unable to re-enter the Taproot. Is there anyway to get back inside so I can finish the quest?

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
