### ISSUE TITLE
Galleon graveyard battle ship part

### ISSUE THREAD

**Issue by Glenncrafter** [Wynncraft/Issues#8904]
At the part where you have to hit blackbeards ship 3 times. 

1. When you shoot 2 cannonballs after eachother and the first one explodes the second one also gets removed for some reason.

2. In my opinion they made this part too hard. Blackbeard shoots way too often with all 4 cannons and in general already too often.

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
