### ISSUE TITLE
I can't leave my guild 

### ISSUE THREAD

**Issue by IShallNot** [Wynncraft/Issues#8906]
I can't leave my guild I have tried to get my leader to kick me and can't leave myself also it's an annoying issue.

**Comment by Glenncrafter** [comment]
Did you change your name recently ?

**Comment by IShallNot** [comment]
Can't say recently it has been a few months already

**Comment by thecoolkogut4** [comment]
If /guild leave won't kick you then there nothing that you/staff can do. Guilds are currently being rewritten so hopefully this issue will get fixed soon.

**Comment by IShallNot** [comment]
Damn that sucks I guess I'll have to wait
