### ISSUE TITLE
Dying Disguised players can kick people

### ISSUE THREAD

**Issue by Locky1110** [Wynncraft/Issues#8907]
So if you use a dye to dye a player with a sheep disguise, it will end up kicking people nearby (i believe from what i have seen.) some person dyed me, and multiple people nearby were kicked.

So to do it you just need to right click a player disguised as a sheep with a dye and it will kick nearby players

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
