### ISSUE TITLE
Lost 40LE + Pure

### ISSUE THREAD

**Issue by Bennnnyy** [Wynncraft/Issues#8909]
I decided to test a guys Pure (mythic wand) he gave me the Pure, I give him 40LE, after a min or so, we swap back. Well, about a minute after I got the Pure. The server crashes, I log back on. The Pure is GONE!
He also says the 40LE is gone.

**Comment by thecoolkogut4** [comment]
There's nothing that can be done about this.

**Comment by Glenncrafter** [comment]
Deal with it I also lost my white horse so :/

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
