### ISSUE TITLE
Leveling

### ISSUE THREAD

**Issue by Diamonddreaking** [Wynncraft/Issues#8910]
My friend, frankshkreli, has had issues leveling up. Every dungeon we do, I get the EXP always, and EXP from all mobs say 0. What should he do?

**Comment by thecoolkogut4** [comment]
For every level difference you are from a mob you lose 3% of the XP. If s/he is level 50 killing level 1 mobs, s/he will be getting 0 XP. Another possibility is your friends guild XP might be at 100 which redirects all the XP s/he gets to their guild.

**Comment by Diamonddreaking** [comment]
thanks :D my friend had it at 100% guild XP lol

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
