### ISSUE TITLE
Invis NPC?

### ISSUE THREAD

**Issue by xJoshhhh** [Wynncraft/Issues#8911]
On the Quest 'Prison Story' I have collected the prison key (three times) and when I go back to give it to Ooni(NPC) the NPC is invisible/not there at the prison and I can only see green sparkles. Please help me, message me in game my IGN is xJoshhh. Thanks

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
