### ISSUE TITLE
Stuck in walls while spawning

### ISSUE THREAD

**Issue by mslekk** [Wynncraft/Issues#8912]
Its september 10th and I got on wynncraft cus 24/7 grind for levels I go into a world as mage and I spawned in a random wall. If anyone could help I would appreciate. My username is mslekk.

**Comment by mslekk** [comment]
Found out i can do /kill sorry xD

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
