### ISSUE TITLE
Server Restart and Boss Fight in Dungeon

### ISSUE THREAD

**Issue by Nike020410** [Wynncraft/Issues#8913]
DISCLAIMER: I totaly know what is going to happen: You will tell me about no refund and stuff and things, so no need to do that, I will go out, search my key guardian and do this masochism again.

The infuriating bug (can you call it that way?):
1. As you might recall Fallen Factory has a boss fight with core A, B and the main boss.
2. Restarts are announced 10 min in advance, that is kind of fine (for the most part).
3. You can get a restart sheduled while in a dungeon, which is (for the most part of the dungeon) fine.
4. Why does that happen and why don't you move people to an other server automagically, while in the boss fight? It really takes longer than 10 minutes, lots of grinding steps and three bosses in total.
5. Some real bug: After getting kicked for restart and rejoining I still have "Antikythera Firewall Pass A" (and B), they turned into Steves and were not removed from my inventory.

The suggestion (the part which is being put away for later/ever, I know):
Step 4 of the infuriating part.
Split the boss fight of Fallen Factory into the seperate parts, with "waiting room" in between, sothat both parts can be done solo, without op gear, in under 10 minutes and where you can leave while in the middle, which is actually there (throwing the passes in), but isn't implemented like that.
I don't know wether this is technically possible, but an earlier warning about restarts if in dungeon or no restart sheduling while in boss fight would be a nice thing.

**Comment by Nike020410** [comment]
Now it was possible to confirm: No the passes do not work in the dungeon as passes anymore.

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
