### ISSUE TITLE
Item dissapears during pickup

### ISSUE THREAD

**Issue by HexerTPB** [Wynncraft/Issues#8914]
I had finished the Sayleros' Brother's Ashes quest and went to do other quests, after i dropped some armour i accidently dropped the ashes while my inventory was full and because the items were near me i picked one of them and didnt get the ashes back...

In-Game name-AmitTheProBro
email for contact about the issue or more details- amittpb@gmail.com

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
