### ISSUE TITLE
Chest at X -435 Z -1714 can not be accesssed with newer versions

### ISSUE THREAD

**Issue by TheFourthRider** [Wynncraft/Issues#8915]
There is a Chest at Coordinates X -435 Y 57 Z -1714 underwater behind a fence. This chest can be looted with minecraft version 1.8 without problems, because the fence only is closed at one side. But in version 1.12 the fence is bound to the other side, too. This is why you can't click it anymore.

**Comment by Villageacules** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/
