### ISSUE TITLE
House of twain

### ISSUE THREAD

**Issue by BobblesOwO** [Wynncraft/Issues#8916]
I do not think anyone else had this problem, the hopper won't take the three items to make the ghostly cap

**Comment by BobblesOwO** [comment]
I was able to get through the quest but I didn't receive the ghost cap

**Comment by LordHelmchen98** [comment]
Have you tried different servers?

**Comment by BobblesOwO** [comment]
I tried on three different servers but it did not work, but I logged off for about 30 minutes and it fixed itself

**Comment by LordHelmchen98** [comment]
Alright
