### ISSUE TITLE
[BUG] I can't go to Nodguj Nation 

### ISSUE THREAD

**Issue by InwTanRew** [Wynncraft/Issues#8917]
I can't go out on seasail? why pls help 
can admin tp me to Nodguj?

![2017-09-27_08 25 03](https://user-images.githubusercontent.com/32316341/30891497-f190bb5a-a35d-11e7-8bf8-1dd35ffb1e8d.png)
![2017-09-27_08 25 01](https://user-images.githubusercontent.com/32316341/30891499-f196fb0a-a35d-11e7-8e11-7f17cff63b9d.png)

**Comment by thecoolkogut4** [comment]
Please use the new issue subsection on the forums - https://forums.wynncraft.com/forums/bug-reports.108/

Have you tried switching servers?

**Comment by InwTanRew** [comment]
Thank you

**Comment by LordHelmchen98** [comment]
Guess this has been resolved.
