### ISSUE TITLE
Bug with NPC's chat.

### ISSUE THREAD

**Issue by aquacom** [Wynncraft/Issues#8918]
When i'm doing a quest and an NPC talks to me, the first line of chat appear on grenn but the following ones are white.
![2017-09-30_18 03 02](https://user-images.githubusercontent.com/26070152/31047381-d34de150-a609-11e7-922a-8cf376d01876.png)
 Please help, Thanks

**Comment by LordHelmchen98** [comment]
This is a current issues due to a hot fix that is supposed to prevent hackers from crashing servers. It's being worked on and hopefully the devs will release an actual fix that fixes this color issue as well.
