### ISSUE TITLE
My character is stucked at -975 62 -1690

### ISSUE THREAD

**Issue by kimbokbok** [Wynncraft/Issues#8919]
My game was lagging and I found myself stuck here. Could you please bring me out? Thanks.
![2560-10-01_11 42 45](https://user-images.githubusercontent.com/32426782/31051868-144ba0cc-a69e-11e7-9e59-c95720cf8c64.png)

**Comment by LordHelmchen98** [comment]
You can do `/kill` in order to get unstuck.
