### ISSUE TITLE
Cannot enter temple of legend

### ISSUE THREAD

**Issue by cvnddy** [Wynncraft/Issues#8920]
I am 68 lv and solve ToL quest to kill KoW now.
That NPC said I can enter.
But I also can't go in even  I put on Purified Helmet.
someone can help me? Thanks!
MC username : cvnddy

**Comment by ittnoraA** [comment]
Is the helmet identified?

Have you tried talking to the NPC when the helmet is in your inventory? (not armor slot)

**Comment by cvnddy** [comment]
I even cant talk to that NPC (I think because it dont have any to say)
And NPC "already said" that I can go in the temple.
(quest book : Kill the CoF to and bring to proof....)
so I think it must be a bug not my problem.

**Comment by DebugMC** [comment]
@cvnddy you do not enter ToL. There is a cave right next to ToL that has the CoW. Thats where you go. Not ToL

**Comment by cvnddy** [comment]
Oh ,I will try later thx~

**Comment by cvnddy** [comment]
OK I meet the CoW. thx~
