### ISSUE TITLE
"???" Quest | Yahya's Trapdoor does not open.

### ISSUE THREAD

**Issue by CrypticError** [Wynncraft/Issues#8922]
Issue: Yahya's door does not open upon dropping the 3 items, Spoon, Small Mushroom, and Painting. This happened in a party of 6. We have tried 3 servers, all to the same effect.

**Comment by LordHelmchen98** [comment]
Did they one who got the painting switch classes or servers after getting it?
Doing that breaks it unfortunately because of NBT tags.

**Comment by CrypticError** [comment]
Ah, I see. Guess that makes sense. Unfortunately, I do believe that we did change servers.
