### ISSUE TITLE
Llevigar's library key corrupted

### ISSUE THREAD

**Issue by Latted** [Wynncraft/Issues#8923]
When i got the Llevigar's library key from the quest The Fortuneteller, i got in the library, but when i changed lobby, i couldn't get in. It corrupted or something. I tried today too and didn't get in, then my brother tried too, with his key, and didn't get in neither.

**Comment by LordHelmchen98** [comment]
Im pretty sure thats an issue with NBT tags. After switching classes/servers the key doesnt work anymore. If you want to look up the lore you can search for it in the wiki though.
