### ISSUE TITLE
[The Sewers of Ragni] Stuck in the quest

### ISSUE THREAD

**Issue by thomas-worm** [Wynncraft/Issues#8935]
Hello,

in the quest, you get stuck many times.
The skeleton does not drop a skull. Then you have to wait until another player opens the door. At the parcour there is a chance to get stuck in a strange dark room (perhaps underneath the parcour). There was no entrance any more. Single possible solution was to teleport to ragni. But when I started the quest again I got stuck at the explosive section because I don't have anymore explosive item.

Please make a possibility to restart the quest.

Regards,
Thomas

**Comment by LordHelmchen98** [comment]
At least the explosive part should be fixed.
Are you still stuck in any part of the quest?

**Comment by thomas-worm** [comment]
Thanks.
Now everything is fine.
