### ISSUE TITLE
A potentially gamebreaking bug regarding a chest (Fix asap)

### ISSUE THREAD

**Issue by MercioDeComercio** [Wynncraft/Issues#8937]
There's a tier 2 chest near to Nemrack, where the giant skull is located (the one of the quest). There is a tear 2 chest there, and every time it does the animation of opening and closing the cave, the chest, and all items inside it, get refreshed, as long as you don't close it, making it dissapear. This is a really gamebreaking glitch, as it allows for infinite equipment, and, as you can guess, infinite emeralds, and it should be fixed so it can't be abused any more.

**Comment by x-71** [comment]
more ppl probs know this now than before u posted this
would've been better to privately report a moderator/admin

**Comment by MercioDeComercio** [comment]
i knew about the consequences this would have, but i have never used this webpage, fo reported a but for wynncraft before, so i have no idea about how to send a private message to a mod. i just hope they fix it soon

**Comment by x-71** [comment]
besides i think chests have cooldowns now so you can't repeatedly abuse this glitch

**Comment by LilVictor** [comment]
It only gives you the cooldown when you choose a class

Em 31 de jan de 2018 1:49 PM, "x-71" <notifications@github.com> escreveu:

**Comment by LordHelmchen98** [comment]
It fixed. If it's not live yet it will be after the next map push.
Its not that bad as github isn't really in use anymore.
In future you should report bugs [here](https://forums.wynncraft.com/forums/bug-reports.108/)
However gamebreaking bugs don't belong there either. Please report gamebreaking bugs to a content team member or a moderator
