### ISSUE TITLE
Infested pit (and a little bit of Decrepit Sewers) bugs

### ISSUE THREAD

**Issue by Owgla** [Wynncraft/Issues#8938]
So i've been doing the dungeon quests and dungeons and on my second one there were a few things that i noticed that are out of place.
---------------------------------------------------------------------------------------------------------------

1#
Wall missing 3 block line
![2017-12-20_20 16 53](https://user-images.githubusercontent.com/19985469/34227164-24f19a2a-e5c4-11e7-9aa5-3a22e09a07cc.png)
![2017-12-20_20 17 06](https://user-images.githubusercontent.com/19985469/34227173-28bd264c-e5c4-11e7-9daf-449181a95fcf.png)
![2017-12-20_20 17 08](https://user-images.githubusercontent.com/19985469/34227176-2b917850-e5c4-11e7-9e99-93f6fdaaf916.png)
----------------------------------------------------------------------------------------------------------------

2#
Missing item frames with maps on the parkour
![2017-12-20_20 18 29](https://user-images.githubusercontent.com/19985469/34227204-3ea076ee-e5c4-11e7-868c-4acfa91193cc.png)
----------------------------------------------------------------------------------------------------------------

3#
Dungeon completion teleport
----------------------------------------------------------------------------------------------------------------
After i finished the dungeon i was teleported out and ended up inside a wall or something. I had to use /kill to be able to continue playing. Probably the only gamebreaking one i've found so far.
This is all i saw.
![2017-12-20_20 21 41](https://user-images.githubusercontent.com/19985469/34227263-76cf0a08-e5c4-11e7-9708-579ed49b33a2.png)

A similar thing happened the Decrepit Sewers where me and another person spawned 1 block into the ground (not gamebreaking but might aswell report it here).

**Comment by LordHelmchen98** [comment]
Sorry for the late response, but anyway:
1# this is intended. the spiders come into the room "through that tunnel" aka its their spawnpoint.
2# this actually seems broken. I'll pass it.
3# fixed already.
