### ISSUE TITLE
Stuck in the black after dungeons

### ISSUE THREAD

**Issue by thomas-worm** [Wynncraft/Issues#8939]
After completing the Decrepit Sewers or the Infested Pit the screen becomes fully black and no further movement is possible. Trying to port isn't possible because it says I should move away from blocks. Only possible solution is to use /kill and lose items and soul points. Can you please fix this to spawn the player on a real world position after dungeon completion?

**Comment by LordHelmchen98** [comment]
This problem has been fixed.
