### ISSUE TITLE
Lazarus Pit basement button not working

### ISSUE THREAD

**Issue by Kwstv** [Wynncraft/Issues#8942]
the Lazarus Pit quest basement all the button are not working so it impossible to finish the quest, hope can fix it.

**Comment by Chewsterchew** [comment]
Same issue here!

**Comment by Chewsterchew** [comment]
I've tried switching servers, I've switched to most of them, same issues. One changes to a gold block, I click another, nothing happens.

**Comment by Chewsterchew** [comment]
Found a forum post to go along with this, https://forums.wynncraft.com/threads/lazarus-pit-code.213345/. Be sure to yell there too

**Comment by Chewsterchew** [comment]
Appears to be fixed as of https://forums.wynncraft.com/threads/lazarus-pit-code-not-working.213219/
This can be closed now.
