### ISSUE TITLE
mana bug

### ISSUE THREAD

**Issue by maple3142** [Wynncraft/Issues#8947]
[youtube video](https://youtu.be/YyVKaD3LmBM)
My mana is always zero, still happened after switching server

**Comment by LordHelmchen98** [comment]
Looks like you have negative mana regen on an armor or accessory piece. Does this still happen to you?

**Comment by maple3142** [comment]
Yes, I have negative mana regen on my wand.
But I remember that it doesn't exists on my wand. (lunar spine)

**Comment by LordHelmchen98** [comment]
With the update the stats of Lunar Spine got changed a lot.
Anyway as you know what causes it, is your issue resolved bow?

**Comment by maple3142** [comment]
Yes, but it is my only wand, I cannot use it to kill any mobs to get a new wand...

**Comment by LordHelmchen98** [comment]
I'm sure you can find a new one. Just try to find someone who has a weapon for your level in Detlas on server one. Usually there are many other players there. You can also check the trade market on the forums.
However you know what the problem is, therefore this issue is resolved.
