### ISSUE TITLE
Somehow, my Mage kit ended up stuck in a block.

### ISSUE THREAD

**Issue by Wetmypants3000** [Wynncraft/Issues#8955]
Excuse me, when I was playing wyncraft, I clicked on my level 19 mage kit.I hadn't played in a long time.I clicked it and it looked like i was stuck in the middle of some sort of stone block.All my other accounts are trash and i really love this one.I also tried /stuck but apparently that won't work anymore. PLEASE FIX IT!!
Picture Below:VVVVV

 
![the wyn-craft problem](https://user-images.githubusercontent.com/35456940/34945183-6b94ce6e-f9d0-11e7-8a02-8cd08e6607f8.png)

**Comment by RubbrDuck** [comment]
try /kill

**Comment by LordHelmchen98** [comment]
I don't think `/stuck` has ever been in the game, but as RubbrDuck said `/kil` should get you out.
