### ISSUE TITLE
Memory Paranoia Teleports the Whole Server

### ISSUE THREAD

**Issue by NadikiShadowcrafter** [Wynncraft/Issues#8958]
At about 6:34 PM PST, on 1/25/17, on server 10, every player on the server was teleported to the same room in the Memory Paranoia mansion. We all left and for a while after that it continued to occasionally say Mr. and Mrs. Caritat’s dialogue when he’s doing his demon ritual across the whole server. Someone mentioned that it had happened to them four times earlier in the same day (don’t know if it was true or not). Really annoying though because I was almost done leading Seluc to the air temple.

**Comment by NadikiShadowcrafter** [comment]
Update: at 8:48 PM PST, on server 6, all players were teleported to a house in the Grave Mistake area (the one with the two armor stands that follow you) and then the server closed two minutes later. I believe both events were triggered by one person activating a teleport that accidentally teleports everyone.

**Comment by XManis1** [comment]
I had a similar problem, only it was in Timmy's room. i think i did it actually...

**Comment by NadikiShadowcrafter** [comment]
This glitch is making basically everyone suicidal, I had it happen to me 13 more times today across every server. It’s impossible to get anything done

**Comment by NadikiShadowcrafter** [comment]
Also:
-it’s almost always in the Grave Mistake room with the jack-in-the-box
-you don’t get teleported if you’re on a horse
-the door is locked so you can only get out by using a scroll, doing /kill, or going to another server (where you often get stuck again right away)

**Comment by Bryanboyv1** [comment]
Yhea had the same  today i got teleported to a small house and then the server crashed :/

**Comment by LordHelmchen98** [comment]
This was fixed a while ago.
