### ISSUE TITLE
Impossible To Access Alumj Bank And In Turn Complete 2 Quests

### ISSUE THREAD

**Issue by Doobig10** [Wynncraft/Issues#8961]
Upon return to this server after a few months of not playing I tried to attempt to do the "Jungle Fever" quest, this required access to alumuj bank which requirements have changed, this wasn't  a problem, I started to do the new quest "A Sandy Scandal" but when I reached the end and it told me to defuse the tnt and stop the bandits escaping, **_there was no tnt._**, when others came after about half an hour of me looking for things I might've missed in that room they also said they were having issues with the quest.

Please fix this bug as when I enter that room I'm trapped and the only way out is death, as well as the fact that I would rather like to complete the 2 quests and this makes them both impossible.

**Comment by Ajusa** [comment]
I also have encountered this bug

**Comment by LordHelmchen98** [comment]
`A Sandy Scandal` got fixed so you should be able to complete both quests now.
