### ISSUE TITLE
Bugged spear texture

### ISSUE THREAD

**Issue by catfish909** [Wynncraft/Issues#8963]
the unique spear hunter's texture seems to be bugged, as it displays to me as a stone brick half slab
![2018-02-01_16 29 11](https://user-images.githubusercontent.com/29007763/35704569-f3c0c0ea-076d-11e8-91a3-d79f94117b65.png)
could this be fixed

**Comment by LordHelmchen98** [comment]
This is known and its just one out of a few other weapons with a missing texture.
In future you should report bugs [here](https://forums.wynncraft.com/forums/bug-reports.108/).
