### ISSUE TITLE
Decrepit Sewers tokens

### ISSUE THREAD

**Issue by RawTech** [Wynncraft/Issues#8977]
Hello,

It looks like if you re-log or change server with tokens in your inventory during the Decrepit Sewers dungeon some of the metadata of the player-head item is lost during the item/inventory serialisation process.

Normal tokens attained by killing mobs:
![2018-04-01_21 11 36](https://user-images.githubusercontent.com/1685716/38177202-02ed9722-35f5-11e8-94a4-0219658b4ee0.png)

Tokens as they appear after re-logging:
![2018-04-01_21 11 38](https://user-images.githubusercontent.com/1685716/38177203-06625cb2-35f5-11e8-952a-06cf2f787d96.png)

I cannot vouch for this happening in every dungeon, I just noticed this particular behaviour today in Decrepit Sewers.

**Comment by LordHelmchen98** [comment]
That happens when a player changes classes or servers and unfortunately that happens with all (or at least most) heads. It's a known issue and will hopefully be fixed eventually, but for normal players there is no way to fix it.
