### ISSUE TITLE
Wynnexcavation Site C, Got caught and spawned in front of Ragni

### ISSUE THREAD

**Issue by enTrieD** [Wynncraft/Issues#8983]
So I was at the meeting of the Wynnexcavation Site C and got caught. I was then teleported to the very beginning of every character in front of Ragni at the caravan. I don´t think this is meant to be.

**Comment by LordHelmchen98** [comment]
This is a known issue with regions that should teleport you to a specific place.It will hopefully get fixed eventually.
Also please note that GitHub is not really used anymore. Please use the [Bug Reports section](https://forums.wynncraft.com/forums/bug-reports.108/) in future.
