### ISSUE TITLE
Chestnut horse missing?

### ISSUE THREAD

**Issue by hexon1033** [Wynncraft/Issues#8984]
I am really sad right now because my chestnut horse seems to have disappeared. I don't know if I just dropped it or if it just disappeared for some other reason, but I would at least like to know what happened to it. If it could be returned to me, that would be even better. Thank you.

**Comment by RubbrDuck** [comment]
Wynncraft has a strict no refund policy, sorry.

Where were you when it disappeared? Did you just suddenly notice its
disappearance?

**Comment by hexon1033** [comment]
I just noticed today. I think I lost it yesterday while I was in Ice Barrows.

**Comment by hexon1033** [comment]
It's okay though because I got another chestnut horse as a replacement.
