### ISSUE TITLE
Typo in "The Corrupted Village"

### ISSUE THREAD

**Issue by atenfyr** [Wynncraft/Issues#8985]
In the quest "The Corrupted Village," the book "Machine Use Instructions" contains a typo; the book states "Aquire an explosive item" rather than "Acquire a explosive item."

**Comment by RubbrDuck** [comment]
"Acquire an explosive item" should be the right thing to say. Any
screenshots?

**Comment by atenfyr** [comment]
![image](https://user-images.githubusercontent.com/7481976/38908439-cfa25a4a-4285-11e8-8882-e15faa82cc16.png)

**Comment by LordHelmchen98** [comment]
This got fixed now.
Please note that GitHub is not really used anymore. Please use the [Bug Reports section](https://forums.wynncraft.com/forums/bug-reports.108/) in future.
