### ISSUE TITLE
Fantastic Voyage Issue

### ISSUE THREAD

**Issue by hexon1033** [Wynncraft/Issues#8988]
I am doing the quest fantastic voyage, and it doesn't seem to be working. The captain of the ship told me to steer the ship, so I pressed the wheel. However, I was teleported to an island, and the captain is telling me, "Now you're the captain, hope the sea's not making you nauseous. Steer this ship, but you'll have to be cautious." I can't go anywhere because I keep getting teleported back to the same spot. I tried killing myself and retrying it, but the same issue happened. Please fix!

**Comment by hexon1033** [comment]
Also, I just looked at a walkthrough. It's the same in the walkthrough, except I don't have a pressure plate to step on.

**Comment by LordHelmchen98** [comment]
There used to be a boat that spawns when you step on the pressure plate, but the boat system got reworked and the boat in the quest got removed. Originally boats didnt go back to your inventory after using them, but now they do and the boat in this quest would spam your inventory as you get new ones over and over again and it could also be abused, therefore it got removed. 
It will probably get changed eventually, but for now you just have to swim.
Also please note that GitHub is not really used anymore. Please use the [Bug Reports section](https://forums.wynncraft.com/forums/bug-reports.108/) in future.
